### ISSUE TITLE
cutIPv6 documentation misleading

### ISSUE THREAD

**Issue by aycyang** [ClickHouse/ClickHouse#4517]
cutIPv6 is a Clickhouse function that zeroes out some bits from the end of an IPv6 or IPv4 address. The [documentation for cutIPv6(x, bitsToCutForIPv6, bitsToCutForIPv4)](https://clickhouse.yandex/docs/en/query_language/functions/ip_address_functions/#cutipv6-x-bitstocutforipv6-bitstocutforipv4) says that it

> Returns a string containing the address of the specified number of **bits** removed in text format.

However, the provided example contradicts this statement. Notice that the IPv6 address has its last 16 bits zeroed out, despite passing in 2 as `bitsToCutForIPv6`.

```
WITH
    IPv6StringToNum('2001:0DB8:AC10:FE01:FEED:BABE:CAFE:F00D') AS ipv6,
    IPv4ToIPv6(IPv4StringToNum('192.168.0.1')) AS ipv4
SELECT
    cutIPv6(ipv6, 2, 0),
    cutIPv6(ipv4, 0, 2)
```
```
┌─cutIPv6(ipv6, 2, 0)─────────────────┬─cutIPv6(ipv4, 0, 2)─┐
│ 2001:db8:ac10:fe01:feed:babe:cafe:0 │ ::ffff:192.168.0.0  │
└─────────────────────────────────────┴─────────────────────┘
```

Also, while the behavior of IPv4 address handling is unclear in this example, I confirmed that this function operates on bytes instead of bits for IPv4 as well.

This behavior was reproduced in the latest yandex/clickhouse-server Docker container running Clickhouse client version 18.10.3 and server version 19.1.9 revision 54413.

**Comment by toddyocum** [comment]
Does anyone know of a workaround for this if bits level of cuts is needed?

I figured it out for ipv4,using bitAnd, but am not sure for ipv6, which returns an Fixed(16) string for 
IPv6StringToNum()

Here is what I do for IPv4

 `IPv4NumToString(bitAnd(IPv4StringToNum(Destination_IPv4_Address), reinterpretAsUInt32(unhex(reverse('FFFFFF00'))))) AS `Destination_IPv4/24`, 
`

**Comment by filimonov** [comment]
> Does anyone know of a workaround for this if bits level of cuts is needed?

That string just contain a binary represenation of ipv6.

You can process that string by parts, but it's a bit tricky because of endianness.

Please try to follow:
```sql
WITH 
    IPv6StringToNum('2001:0DB8:AC10:FE01:FEED:BABE:CAFE:F00D') AS ipv6, 
    reverse(ipv6) AS ipv6_big_endian, 
    substring(ipv6_big_endian, 1, 8) AS lower_part_as_string, 
    substring(ipv6_big_endian, 9, 8) AS upper_part_as_string, 
    reinterpretAsUInt64(upper_part_as_string) AS upper_part_numeric, 
    reinterpretAsUInt64(lower_part_as_string) AS lower_part_numeric, 
    bitAnd(lower_part_numeric, 0xFFFFFFFFFFFFFF8) AS lower_part_numeric_bits_reset, 
    reinterpretAsFixedString(lower_part_numeric_bits_reset) AS lower_part_lower_bits_reset_as_string, 
    CAST(reverse(concat(lower_part_lower_bits_reset_as_string, upper_part_as_string)), 'FixedString(16)') AS fixed_ipv6
SELECT 
    hex(ipv6), 
    hex(ipv6_big_endian), 
    hex(upper_part_numeric), 
    hex(lower_part_numeric), 
    hex(lower_part_numeric_bits_reset), 
    hex(fixed_ipv6)

Row 1:
──────
hex(ipv6):                          20010DB8AC10FE01FEEDBABECAFEF00D
hex(ipv6_big_endian):               0DF0FECABEBAEDFE01FE10ACB80D0120
hex(upper_part_numeric):            20010DB8AC10FE01
hex(lower_part_numeric):            FEEDBABECAFEF00D
hex(lower_part_numeric_bits_reset): 0EEDBABECAFEF008
hex(fixed_ipv6):                    20010DB8AC10FE010EEDBABECAFEF008

1 rows in set. Elapsed: 0.002 sec. 
```

Same, oneliner: 
```sql
WITH 
    IPv6StringToNum('2001:0DB8:AC10:FE01:FEED:BABE:CAFE:F00D') AS ipv6, 
    CAST(concat(substring(ipv6, 1, 8), reverse(reinterpretAsFixedString(bitAnd(reinterpretAsUInt64(reverse(substring(ipv6, 9, 8))), 0xFFFFFFFFFFFFFF8)))), 'FixedString(16)') AS fixed_ipv6
SELECT 
    hex(ipv6), 
    hex(fixed_ipv6)
```

**Comment by DanRoscigno** [comment]
Doc was updated to correct `bits` to `bytes`
