### ISSUE TITLE
Optional components

### ISSUE THREAD

**Issue by podshumok** [ClickHouse/ClickHouse#4525]
I've noticed that some dependencies have corresponding `ENABLE_XXX` cmake variable but not all of them. Still it is possible to build without brotli, capnproto, hdfs3, icu, jemalloc, kafka, mongodb, mysql, odbc, and protobuf. Sometimes it is enough to `cmake -DENABLE_XXX=0` sometimes some more advanced trick is required. but resulting builds (at first glance) look ok. The only thing I can't disable for now is `ssl`.

So the questions are what components are really optional? Should we unionize enabling/disabling algorithm in some pr? Should failure to build without ssl be considered as a bug to be investigated for unconditioned includes and parts of code?

**Comment by alexey-milovidov** [comment]
SSL can also be disabled.

As it is used through Poco library, to disable it, you should specify `-D ENABLE_POCO_NETSSL=0`, if I remember correctly.

**Comment by alexey-milovidov** [comment]
> Should failure to build without ssl be considered as a bug to be investigated for unconditioned includes and parts of code?

Yes.

We can also add one more build variant to our CI - "minimal build" with the minimum possible number of components.

**Comment by proller** [comment]
Currently build without ssl and with functions impossible:
dbms/src/Functions/FunctionsHashing.h : 
#include <openssl/md5.h>
#include <openssl/sha.h>
But its easy to fix by disabling some functions

**Comment by podshumok** [comment]
AFAIR `md5` and `shaXXX` where there long before you added SSL support. How it was implemented back then?

**Comment by alexey-milovidov** [comment]
OpenSSL (and LibreSSL) contains two libraries:
- SSL;
- Crypto.

We have used OpenSSL from the beginning.
Hash functions are available inside `Crypto` component of `OpenSSL` library.

**Comment by alexey-milovidov** [comment]
@proller Do you want to continue with this task or "won't fix"?

**Comment by proller** [comment]
I want to add to many cmake/find_*.cmake something like
```
if (DEFINED ENABLE_XXX AND NOT ENABLE_XXX)
   return()
endif()```
