### ISSUE TITLE
Why is slow grants access from LDAP Active Directory?

### ISSUE THREAD

**Issue by ShulcevVA** [ClickHouse/ClickHouse#45294]
I am grants role to LDAP user, and role show very quickly for this user, but access real apply  more 30 minets.

    <ldap_servers>
        <my_ad_server>
            <host>adm-dc1.secret.ru</host>
            <port>389</port>
            <bind_dn>secret\{user_name}</bind_dn>
            <verification_cooldown>0</verification_cooldown>
            <user_dn_detection>
                <base_dn>OU=DNS Users,DC=secret,DC=ru</base_dn>
                <search_filter>(&amp;(objectClass=user)(sAMAccountName={user_name}))</search_filter>
            </user_dn_detection>
            <enable_tls>no</enable_tls>
        </my_ad_server>
    </ldap_servers>

    <user_directories>
        <ldap>
            <server>my_ad_server</server>
            <role_mapping>
                <base_dn>OU=DevOps System accounts,DC=secret,DC=ru</base_dn>
                <attribute>CN</attribute>
                <scope>subtree</scope>
                <search_filter>(&amp;(objectClass=group)(member={user_dn}))</search_filter>
                <prefix>clickhouse_</prefix>
            </role_mapping>
        </ldap>
    </user_directories>

**Comment by tbragin** [comment]
Not sure if this problem is still happening. 

If so, more specifics would needed to help here, such as 
- What version of ClickHouse? 
- What type of LDAP server & version?
- Some debug logs on both ends?
