### ISSUE TITLE
Increase background_pool_size without clickhouse server restart

### ISSUE THREAD

**Issue by dragonpic1988** [ClickHouse/ClickHouse#45295]
I want to increase <background_pool_size> with out clickhouse server restart
Use clickhouse-client 
Before, <background_pool_size>is 16
Then run: set background_pool_size=24
                select * from system.settings where name='background_pool_size'
<background_pool_size>correctly set 24
Then run: quit
But reconnect clickhouse-client and see <background_pool_size> in settings，It,s still 16

Is my method wrong, or is there any other way to increase this value with out clickhouse server restart

**Comment by dragonpic1988** [comment]
SSCHL0840 :) select * from system.settings where name='background_pool_size'
SELECT *
FROM system.settings
WHERE name = 'background_pool_size'
┌─name─────────────────┬─value─┬─changed─┬─description─────────────────────────────────────────────────────────────────────────────────────────               ──────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┐
│ background_pool_size │ 16    │       0 │ Number of threads performing background work for tables (for example, merging in merge tree). Only h               as meaning at server startup. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
└──────────────────────┴───────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────               ──────────────────────────────┴──────┴──────┴──────────┴────────┘
1 rows in set. Elapsed: 0.007 sec.
SSCHL0840 :) set background_pool_size=24
SET background_pool_size = 24
Ok.
0 rows in set. Elapsed: 0.001 sec.
SSCHL0840 :) select * from system.settings where name='background_pool_size'
SELECT *
FROM system.settings
WHERE name = 'background_pool_size'
┌─name─────────────────┬─value─┬─changed─┬─description─────────────────────────────────────────────────────────────────────────────────────────               ──────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┐
│ background_pool_size │ 24    │       1 │ Number of threads performing background work for tables (for example, merging in merge tree). Only h               as meaning at server startup. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
└──────────────────────┴───────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────               ──────────────────────────────┴──────┴──────┴──────────┴────────┘
1 rows in set. Elapsed: 0.004 sec.
SSCHL0840 :) quit
Bye.
[appuser@SSCHL0840 ~]$ clickhouse-client
ClickHouse client version 20.8.3.18.
Connecting to ck02:9000 as user admin.
Connected to ClickHouse server version 20.8.3 revision 54438.
SSCHL0840 :) select * from system.settings where name='background_pool_size'
SELECT *
FROM system.settings
WHERE name = 'background_pool_size'
┌─name─────────────────┬─value─┬─changed─┬─description─────────────────────────────────────────────────────────────────────────────────────────               ──────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┐
│ background_pool_size │ 16    │       0 │ Number of threads performing background work for tables (for example, merging in merge tree). Only h               as meaning at server startup. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
└──────────────────────┴───────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────               ──────────────────────────────┴──────┴──────┴──────────┴────────┘

**Comment by cangyin** [comment]
The settings you set with `SET` in clickhouse-client, is only effective in _current_ client session.
To make the setting effective across client sessions (or server wide), add it to `default` profile in user configuration (i.e. `users.xml` file).
Read the [relevant docs](https://clickhouse.com/docs/en/operations/configuration-files). 

Additinoally, The `background_pool_size` can be set both in server configuration and user configuration. And can be increased without server restart, but decreasing the value requires a restart, [see](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#background_pool_size).

**Comment by cangyin** [comment]
Changing configuration files will cause server to auto reload all configurations, when it detects a file change.

**Comment by den-crane** [comment]
see similar issue https://github.com/ClickHouse/ClickHouse/issues/43351
