### ISSUE TITLE
Clickhouse format fails when formatting DROP FUNCTION with ON CLUSTER clause and semicolon, 22.8.8.3+

### ISSUE THREAD

**Issue by NickStepanov** [ClickHouse/ClickHouse#45303]
**Describe the unexpected behaviour**

When running a Clickhouse-format command on a file containing DROP FUNCTION with ON CLUSTER clause and a semicolon at the end of the line, it fails with the 

`Code: 62. DB::Exception: Empty query. (SYNTAX_ERROR)`

**How to reproduce**
* Which ClickHouse server version to use
22.8.8.3+, haven't tested on earlier ones
* statements involved

use this command, saved as **test.sql** :

```
CREATE FUNCTION linear_equation AS (x, k, b) -> ((k * x) + b);

DROP FUNCTION linear_equation ON CLUSTER test;
```

* Queries to run that lead to unexpected result

The command is this:
`cat test.sql | clickhouse-format -n`

**Expected behavior**
Return a formatted content of the file.

**Error message and/or stacktrace**
```
root@37fea490c11a:/# cat test.sql | clickhouse-format -n
CREATE FUNCTION linear_equation AS (x, k, b) -> ((k * x) + b)
;

DROP FUNCTION linear_equation ON CLUSTER test
;

Code: 62. DB::Exception: Empty query. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8e1d808 in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x12df52ec in /usr/bin/clickhouse
2. mainEntryClickHouseFormat(int, char**) @ 0x8fcaca4 in /usr/bin/clickhouse
3. main @ 0x8e0b6a4 in /usr/bin/clickhouse
4. __libc_start_main @ 0x20e10 in /usr/lib/aarch64-linux-gnu/libc-2.31.so
 (version 22.8.8.3 (official build))
```

**Additional context**
It works in 2 cases:

1.  if we remove the last semicolon, after the DROP FUNCTION command.
2. If we don't use the ON CLUSTER clause:
```
root@37fea490c11a:/# cat test.sql | clickhouse-format -n
CREATE FUNCTION linear_equation AS (x, k, b) -> ((k * x) + b)
;

DROP FUNCTION IF EXISTS linear_equation
;

```

**Comment by han-cheng6** [comment]
# Addition affected statement
No only `DROP FUNCTION linear_equation ON CLUSTER test;` cause this problem, all the following line can cause this problem(may be not full):
```
USE test_database;

SYSTEM RELOAD MODELS ON CLUSTER cluster_name;

CREATE QUOTA abc TO ALL ON CLUSTER cluster_name;

CREATE ROW POLICY abc ON test.test TO ALL ON CLUSTER cluster_name;

DROP NAMED COLLECTION abc ON CLUSTER cluster_name;

CREATE INDEX index_a on test.test (a) TYPE INT GRANULARITY 8192;

BEGIN TRANSACTION;

COMMIT;

ROLLBACK;

SET TRANSACTION SNAPSHOT 123;

BACKUP TABLE test.table TO Disk('backups', '1.zip') ASYNC;
```
# The reason:
a) when a statement match its parser's last token, and there's not loop processing for the last token.
b) the ending semicolon will be not touched.
c) `token_iterator` (in `DB::tryParseQuery`) status as following pic:
<img width="598" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/1409809/a8464409-c3af-4345-b1ef-6cf281c339a9">
d) thus the ending semicolon is treated as new statement.
e) cause the empty statement exception.

# Counter example
All statement parsed by `ParserQueryWithOutput` are ok. As the parser's last token is`SETTINGS`. Parser for `SETTINGS` is `ParserSetQuery` which have following loop processing: 
```
    while (true)
    {
        if ((!changes.empty() || !query_parameters.empty() || !default_settings.empty()) && !s_comma.ignore(pos))
            break;
        ....
    }
```
Thus:
a) a statement last token is not `SETTING`, the ending semicolon is touched by `SETTINGS` parse
b) a statement last token is `SETTING`, the ending semicolon is touched by `ParserSetQuery` in the loop
c) `token_iterator` status as following pic:
<img width="577" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/1409809/dff29d86-3f9c-4d86-9396-051d508ce213">


# Solving idea
Call `token_iterator` `get()` function, let the ending semicolon be touched. Thus there will be no empty statement.
Or just let `const auto last_token = token_iterator.get();`, I'm not sure will this cause other problem.

Any problem for this idea?
Any better idea?
@alexey-milovidov
