### ISSUE TITLE
ThreadSanitizer: data race in test_s3_cluster WriteBuffer

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#45310]
We probably discussed this issue, but I can't find any open issue

https://s3.amazonaws.com/clickhouse-test-reports/45147/175491301330b5b82720d6b599ef19092a86b378/integration_tests__tsan__[4/6].html

stderrs:
https://pastila.nl/?0005660f/9416c49fccd7427c6cfb08098cc8913a
https://pastila.nl/?0005660f/47afb2b4088d4d169e9feff5fc65760c

**Comment by antonio2368** [comment]
should be fixed with https://github.com/ClickHouse/ClickHouse/pull/45240
