### ISSUE TITLE
TimeSeries sample values AggregateFunction

### ISSUE THREAD

**Issue by LiuYangkuan** [ClickHouse/ClickHouse#4532]
When we use ClickHouse as TimeSeries DB storage backend, we hope that ClickHouse can do more things when we query the sampled metrics. 

Consider that we need to aggregate sum of TimeSeries metrics for a specific period of time,  but the sample timestamp of TimeSeries not alignment. So we have to read all data into application and compute the aggregate result by linear interpolation.

**For example:**
```
tsA ((154000, 0.1),(154008, 0.3),(154015, 0.9),(154023, 0.5)) and
tsB ((154004, 1.3),(154010, 1.1),(154019, 1.2)) 
should compute the rate then aggregate sum together.
```
***we can‘t get result by ClickHouse SQL directly!***

If there is such kind of aggregate function,  query aggregate sum of TimeSeries mertics will be more
convenient.

**Comment by filimonov** [comment]
Recently (v19.1.0) `boundingRatio` function was added. It's quite simple - calculates the rate of growth by 2 border points (so it suits only for some limited number of cases).

Usage:
```
select sensorid, boundingRatio(time, value) from table group by  sensorid;
```

See some details/comments in https://github.com/yandex/ClickHouse/pull/3139

If that 2 point interpolation is ok for you can do something like: 

```
SELECT 
    sensorid, 
    toStartOfHour(time) AS h, 
    boundingRatio(time, value) AS rate, 
    argMin(value, time) - (rate * (min(time) - h)) AS interpolated_value_at_interval_start, 
    interpolated_value_at_interval_strart + (rate * 3600) AS interpolated_value_at_interval_end
FROM table 
GROUP BY 
    sensorid, 
    h
```
