### ISSUE TITLE
row policy lead to empty data

### ISSUE THREAD

**Issue by dingxiancheng** [ClickHouse/ClickHouse#45349]
clickhouse version:22.10.2.11

when I use user named default to create other user named marketing，I happened a very serious bug.
Default user has all privileges,but  I just grant some table read only privileges and row policies to user marketing.Following are my sql:

create user marketing IDENTIFIED WITH PLAINTEXT_PASSWORD BY '123456';
create role IF NOT EXISTS marketing_role;
GRANT select on cloud_patrol.user_combine to marketing_role;
GRANT select on cloud_patrol.user_behavior_analysis_combine to marketing_role;
GRANT marketing_role TO marketing;
create row policy marketing_user_combine_policy_no100 on cloud_patrol.user_combine using no=100 to marketing_role;
create row policy marketing_user_behavior_analysis_combine_policy_no100 on cloud_patrol.user_behavior_analysis_combine using no=100 to marketing_role;

After execute this sql,marketing user get right result,bug I use default user to query user_combine table or user_behavior_analysis_combine,the result is empty.

use default user:
select count(*) from user_combine ;    ----0
select count(*) from user_behavior_analysis_combine ;   ---0

This question is very serious,please fix it as soon as fast.

**Comment by cangyin** [comment]
What's the query result for `default` user, before creating the row policies?

**Comment by dingxiancheng** [comment]
> What's the query result for `default` user, before creating the row policies?

select count() from user_combine ; ----2282509
select count() from user_behavior_analysis_combine ; ---204427219

**Comment by dingxiancheng** [comment]
> What's the query result for `default` user, before creating the row policies?

This question happens certainly，you can try base on version 22.10.2.11.

**Comment by filimonov** [comment]
Did you read the docs? 

https://clickhouse.com/docs/en/sql-reference/statements/create/row-policy/#using-clause

> 
> note
> 
> If there are no row policies defined for a table then any user can SELECT all the row from the table. Defining one or more row policies for the table makes the access to the table depending on the row policies no matter if those row policies are defined for the current user or not. For example, the following policy
> 
> CREATE ROW POLICY pol1 ON mydb.table1 USING b=1 TO mira, peter
> 
> forbids the users mira and peter to see the rows with b != 1, and any non-mentioned user (e.g., the user paul) will see no rows from mydb.table1 at all.
> 
> If that's not desirable it can't be fixed by adding one more row policy, like the following:
> 
> CREATE ROW POLICY pol2 ON mydb.table1 USING 1 TO ALL EXCEPT mira, peter

**Comment by dingxiancheng** [comment]
I see！！！

**Comment by dingxiancheng** [comment]
But I think it is some complex.

**Comment by den-crane** [comment]
You are in a public library, you can take and read any book from any shelf.
At some point librarian decided to restrict access to one shelf with rare books and gave a key to John, it automatically restricted access from anyone else.

**Comment by dingxiancheng** [comment]
OK，I see，Thank you！
