### ISSUE TITLE
Clickhouse server not starting

### ISSUE THREAD

**Issue by rawat25ankit** [ClickHouse/ClickHouse#45352]
Below error is showing when checked in error logs with :
tail -f /var/log/clickhouse-server/clickhouse-server.log

2023.01.17 10:47:16.220106 [ 1034 ] {} <Debug> Application: Destroyed global context.
2023.01.17 10:47:16.222399 [ 1034 ] {} <Error> Application: DB::Exception: Multiple format_version.txt file: Cannot attach table `iqube`.`iqube_aggregated_old` from metadata file /var/lib/clickhouse/store/a46/a469b5d1-fce8-46dd-961b-d4c54d6cac5b/iqube_aggregated_old.sql from query ATTACH TABLE iqube.iqube_aggregated_old UUID 'fc3312b5-9795-4fe3-85b8-1c4bcbab4383'

**Comment by cangyin** [comment]
What's the version?

**Comment by tavplubix** [comment]
Workaround: remove one of the files 
Fixed in https://github.com/ClickHouse/ClickHouse/pull/43328

**Comment by rawat25ankit** [comment]
ClickHouse client version 22.2.2.1.

**Comment by rawat25ankit** [comment]
I am having data in it.. Will it not delete data if I delete the uuid

**Comment by tavplubix** [comment]
You do not need to delete data. You need to delete one `format_version.txt` file.

**Comment by tavplubix** [comment]
> ClickHouse client version 22.2.2.1.

Btw, this version is obsolete, you should upgrade.

**Comment by rawat25ankit** [comment]
with locate format_version.txt, I am getting only one format_version.txt against the mentioned UUID 'fc3312b5-9795-4fe3-85b8-1c4bcbab4383'

**Comment by tavplubix** [comment]
Another `format_version.txt` is on another disk. Check your configuration to find the path.

**Comment by rawat25ankit** [comment]
I tired to locate the uuid itself. Found that UUID in only one drive i.e. datadrive4.

root@prod-tvsm-cmo-clickhousedb-u347-aggregate-vm:/home/ubuntu# locate fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/datadrive/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/datadrive/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/detached
/datadrive1/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/datadrive1/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/detached
/datadrive1/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/moving
/datadrive2/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/datadrive2/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/detached
/datadrive3/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/datadrive3/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/detached
/datadrive4/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/datadrive4/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/detached
/datadrive4/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/format_version.txt
/datadrive5/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/datadrive5/clickhouse/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/detached
/var/lib/clickhouse/tmp/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383
/var/lib/clickhouse/tmp/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/tmp_merge_202107_5320_5670_11
/var/lib/clickhouse/tmp/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/tmp_merge_202109_6112_6481_6
/var/lib/clickhouse/tmp/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/tmp_merge_202111_7104_7591_8
/var/lib/clickhouse/tmp/store/fc3/fc3312b5-9795-4fe3-85b8-1c4bcbab4383/tmp_merge_202201_8200_9666_6

**Comment by rawat25ankit** [comment]
Will deleting this  format_version.txt will work?... 
So once the server starts, will data from all drives will be available
