### ISSUE TITLE
Invalid number of rows in Chunk column UInt32 position 1: expected 40960, got 3806: While executing MergeTreeThread. (LOGICAL_ERROR)

### ISSUE THREAD

**Issue by HesaMtiPu** [ClickHouse/ClickHouse#45354]
what kind of behavior is thrown from click-house whenever i run the query.not on all query .mostly query is execute properly.but in some query its through this type of exception. kindly suggest us ...Invalid number of rows in Chunk column UInt32 position 1: expected 40960, got 3806: While executing MergeTreeThread. (LOGICAL_ERROR)

Query :- ### select d, sum(count) As C from ( SELECT toDate(PacketTime) as d , count() As count FROM DNS_LOG WHERE IPVersion = 4 AND QR = 0 AND DstIP IN (Select DstIP from ANYCAST where Status = 1) AND toDate(PacketTime) = yesterday() GROUP BY PacketTime ) Group by d order by C DESC limit 5 ;

2023.01.17 16:57:25.050143 [ 411976 ] {43c13616-6e77-4283-bd7e-112228f8930b} <Error> TCPHandler: Code: 49. DB::Exception: Invalid number of rows in Chunk column UInt32 position 1: expected 40960, got 3806: While executing MergeTreeThread. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

Click house version :-  22.10.2.11 (official build).

**Comment by den-crane** [comment]
Can you share `show create table DNS_LOG`

**Comment by HesaMtiPu** [comment]
CREATE TABLE IF NOT EXISTS DNS_LOG ( 
   PacketTime DateTime64, 
   IndexTime DateTime64, 
   Server LowCardinality(String), 
   IPVersion UInt8, 
   SrcIP IPv6, 
   DstIP IPv6, 
   Protocol FixedString(3), 
   QR UInt8, 
   OpCode UInt8, 
   Class UInt16, 
   Type UInt16, 
   Edns0Present UInt8, 
   DoBit UInt8, 
   FullQuery String, 
   ResponseCode UInt8, 
   Question String CODEC(ZSTD(1)), 
   Size UInt16 
   )  
   ENGINE = MergeTree() 
   PARTITION BY toYYYYMMDD(PacketTime) 
   PRIMARY KEY (toStartOfHour(PacketTime), Server, reverse(Question), toUnixTimestamp(PacketTime)) 
   ORDER BY (toStartOfHour(PacketTime), Server,  reverse(Question), toUnixTimestamp(PacketTime)) 
   SAMPLE BY toUnixTimestamp(PacketTime) 
   TTL toDate(PacketTime) + INTERVAL 30 DAY -- DNS_TTL_VARIABLE 
   SETTINGS index_granularity = 8192;

**Comment by den-crane** [comment]
Did you use `delete`?

It could be a duplicate https://github.com/ClickHouse/ClickHouse/issues/40651

Try to upgrade to 22.10.6.3.

**Comment by HesaMtiPu** [comment]
Yes I used DELETE !!! but i did not understand this unexpected behavior after using DELETE Statement.
BTW Problem resolved for NOW and i did not make any changes in my server just simple executed my query and given successful result , so i do not  understand this unexpected behavior after using DELETE Statement.
Thanks for the help !!!!!

**Comment by den-crane** [comment]
1. 22.10.2.11 is obsolete
2. DELETE is experimental feature, you should not use in a production
3. it's a bug https://github.com/ClickHouse/ClickHouse/issues/40651
4. this bug has been fixed

**Comment by HesaMtiPu** [comment]
Thanks @den-crane !!!
