### ISSUE TITLE
Server doesn't distinguish a Cancel packet and an empty block in the end of insert query

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#45377]
```xml
<?xml version="1.0" ?>
<yandex>
	<allow_experimental_transactions>1</allow_experimental_transactions>
</yandex>
...

<?xml version="1.0"?>
<clickhouse>
	<profiles>
		<default>
			<implicit_transaction>1</implicit_transaction>
			<throw_on_unsupported_query_inside_transaction>0</throw_on_unsupported_query_inside_transaction>
		</default>
	</profiles>
</clickhouse>
```

```sql
create table dedup_test( A Int64) Engine = MergeTree order by A settings non_replicated_deduplication_window=1000;

clickhouse-client -q 'select * from numbers(50000000) format TSV' > deduptest.tsv

for i in `seq 1 50`; do echo $i; clickhouse-client --min_chunk_bytes_for_parallel_parsing=1000000 -q 'insert into dedup_test format TSV' <deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';  done
1
50000000
2
50000000
3
50000000
4
50000000
5
50000000
6
^C50888896
7
50888896
8
50888896
9
^C51888904
10
51888904
11
^C52138906
12
^C
```

Rows expected to be deduplicated, because insert is the same.
So it always should be 50000000.
But if I press `^C` client inserts an incomplete block, though it's expected to be rolled back by `implicit_transaction`.

@tavplubix

BTW, it works fine if I kill the client by `-9` from the parallel terminal.

```
for i in `seq 1 1500`; do echo $i; kill -9 `ps -ef|grep 'insert into dedup_test'|grep -v grep|awk '{print $2}'`; sleep 3; done
```

**Comment by den-crane** [comment]
Though, `kill-9` is also able to reproduce the incomplete insert.

**Comment by tavplubix** [comment]
Everything works as expected on the server side. 
The problem is that `clickhouse-client` does not cancel the insert query on ctrl-c. It simply stops parsing the input, so:
 - the server receives an "incomplete" block, so deduplication does not work because this block is different
 - the server successfully commits the implicit transaction

**Comment by tavplubix** [comment]
> (seems like we should introduce a special "end of data" packet in the native protocol, so the server will be able to know that a client died)

Well, we already have it. The problem is that the server does not distinguish an empty block at the end and `Cancel` packet during an insert procesing. 

Also I could reproduce an incomplete block insertion with `kill -9`, but seems like a transaction is correctly rolled back if a client is killed. 

> Though, kill-9 is also able to reproduce the incomplete insert.

@den-crane, did you mean that it reproduces only the issue with incomplete block, or that it reproduces implicit transaction commit as well?

**Comment by den-crane** [comment]
I don't know.


I mean this:

```sql



clickhouse-client -q 'select * from numbers(500000) format TSV' > deduptest.tsv


session1: for i in `seq 1 1500`; do echo $i; kill -9 `ps -ef|grep 'insert into dedup_test'|grep -v grep|awk '{print $2}'`; sleep 2; done

session2: for i in `seq 1 5000`; do echo $i; clickhouse-client --max_block_size=100000 --min_chunk_bytes_for_parallel_parsing=10000 -q 'insert into dedup_test format TSV' <deduptest.tsv ; clickhouse-client -q 'select count() from dedup_test';  done

339
┌─count()─┐
│  500000 │
└─────────┘
340
┌─count()─┐
│  500000 │
└─────────┘
341
┌─count()─┐
│  500000 │
└─────────┘
342
┌─count()─┐
│  500000 │
└─────────┘
343
Killed
┌─count()─┐
│  883120 │
└─────────┘
344
┌─count()─┐
│  883120 │
└─────────┘
345
┌─count()─┐
│  883120 │
└─────────┘
346
┌─count()─┐
│  883120 │
└─────────┘
347
```

My expectation that all inserts must be committed or rolled back and the table should always have 500000 rows or N*500000 number of rows (if dedup is not working properly).
Maybe I wrong with my understanding / expectations.

**Comment by den-crane** [comment]
the same issue as https://github.com/ClickHouse/ClickHouse/issues/27667
I had hope that transactions are able to solve it.

**Comment by den-crane** [comment]
I mean I had hope that the server will rollback an implicit transaction in case of "TCPHandler: Client has dropped the connection, cancel the query."

**Comment by tavplubix** [comment]
Yes, there's another issue: seems like a transaction is not rolled back on query cancellation.
