### ISSUE TITLE
Parsing type 'AggregateFunction(CUSTOM_FUNC('ABC', ['A'], 'CDE'), UInt64, String)' throws SYNTAX_ERROR

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#45383]
**Describe what's wrong**
We have a customized aggregate function with defined parameters, e.g. `CUSTOM_FUNC('ABC', ['A'], 'CDE')(UInt64, String)`. When the aggregate function's intermediate states are stored as a column, the type should be `AggregateFunction(CUSTOM_FUNC('ABC', ['A'], 'CDE'), UInt65, String)`. However, the SYNTAX_ERROR exception throws SYNTAX_ERROR exception. 

By debugging, we got that the parser regard '[' beside of `'A']` as a token and thus cannot parse the remained part `'A'], 'CDE'), UInt65, String)`. 

The potential bug postion is shown as following.
![image](https://user-images.githubusercontent.com/1518453/213108333-bf3eda30-f178-4bf7-9b6c-fb50929b0d27.png)

** reproduce ** 
Parse the type name `"AggregateFunction(CUSTOM_FUNC('ABC', ['A'], 'CDE'), UInt64, String)"` , will got an exception SYNTAX_ERROR.

![image](https://user-images.githubusercontent.com/1518453/213110991-ef87e142-65c8-4258-b1d6-5cec9e7d7414.png)

**Comment by tavplubix** [comment]
We don't have any `CUSTOM_FUNC`. If you use a custom build with modified source code then it's your responsibility to fix bugs that could be introduced by custom patches. 

```
dell9510 :) explain ast create temporary table test (x AggregateFunction(CUSTOM_FUNC('ABC', ['A'], 'CDE'), UInt64, String))

EXPLAIN AST
CREATE TEMPORARY TABLE test
(
    `x` AggregateFunction(CUSTOM_FUNC('ABC', ['A'], 'CDE'), UInt64, String)
)

Query id: 8f29a9af-a695-40cf-ad5b-2924d9ed2c16

┌─explain─────────────────────────────────────┐
│ CreateQuery  test (children 2)              │
│  Identifier test                            │
│  Columns definition (children 1)            │
│   ExpressionList (children 1)               │
│    ColumnDeclaration x (children 1)         │
│     Function AggregateFunction (children 1) │
│      ExpressionList (children 3)            │
│       Function CUSTOM_FUNC (children 1)     │
│        ExpressionList (children 3)          │
│         Literal 'ABC'                       │
│         Literal Array_['A']                 │
│         Literal 'CDE'                       │
│       Function UInt64                       │
│       Function String                       │
└─────────────────────────────────────────────┘

14 rows in set. Elapsed: 0.004 sec.

dell9510 :) select version(), value from system.build_options where name='GIT_HASH'

SELECT
    version(),
    value
FROM system.build_options
WHERE name = 'GIT_HASH'

Query id: 7751c6a9-47d1-4ebf-ad86-f3a0e5b27a91

┌─version()─┬─value────────────────────────────────────┐
│ 22.13.1.1 │ e9a2d5a912abadc5e43f5123933c3da65626d1c2 │
└───────────┴──────────────────────────────────────────┘
```

**Comment by Alex-Cheng** [comment]
Do we allow selecting Array type as paramter (NOT argument), such as Func(['a]')(..)? I just want to clarify it.
