### ISSUE TITLE
Flaky test test_ttl_move_memory_usage

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#45393]
@KochetovNicolai 

It is flaky in release build also
```
>       assert int(max_usage) < 3e9
E       AssertionError: assert 5072636928 < 3000000000.0
E        +  where 5072636928 = int('5072636928\n')
```

_Originally posted by @qoega in https://github.com/ClickHouse/ClickHouse/issues/45162#issuecomment-1387018181_

**Comment by KochetovNicolai** [comment]
Maybe it can be fixed after https://github.com/ClickHouse/ClickHouse/pull/47104

**Comment by tavplubix** [comment]
It did not fail for a while according to the CI DB
