### ISSUE TITLE
Flaky test_multiple_disks

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#45404]
Also failed `test_multiple_disks/test.py::test_background_move[mt]`

```
>           assert used_disks[0] == "external"
E           AssertionError: assert 'jbod1' == 'external'
E             - external
E             + jbod1
```
https://s3.amazonaws.com/clickhouse-test-reports/0/cfba9b19eb0941f4e40d216d55ef2a68f6d2cf5e/integration_tests__release__[2/2]/integration_run_parallel5_0.log

_Originally posted by @qoega in https://github.com/ClickHouse/ClickHouse/issues/45180#issuecomment-1387299684_

**Comment by tavplubix** [comment]
`test_multiple_disks/test.py::test_start_stop_moves[replicated]` is flaky too
https://s3.amazonaws.com/clickhouse-test-reports/49637/6f53ee289db7939188ce1d9bcbe97b4203205d58/integration_tests__asan__[4_6].html

**Comment by KochetovNicolai** [comment]
+1 `test_start_stop_moves[replicated]`
https://s3.amazonaws.com/clickhouse-test-reports/0/afdf7eaed7fab6d5f25663d66be97c301acc5195/integration_tests__asan__[4_6]/integration_run_parallel2_0.log

**Comment by qoega** [comment]
Maybe it is time to drop this test completely?

**Comment by qoega** [comment]
Proposed perfect gentleman solution: https://github.com/ClickHouse/ClickHouse/pull/51470

**Comment by CheSema** [comment]
I have found out that moves is stuck due to 
`part already assigned to background operation.`
for all parts.

Even when merges are canceled, the parts are added to the virtual parts. And if so, such parts are excluded from move.
