### ISSUE TITLE
Numeric expression have UInt64 instead of UIn32 which causes "There is no supertype for types UInt64, Int8" error

### ISSUE THREAD

**Issue by tema-popov** [ClickHouse/ClickHouse#45401]
**Describe what's wrong**

This query would fail with an error:
```sql
select 100 as number, if(isNull(number), -1, 60 * 60 * 24 * 90) as test_bug;
```
The error:

> Code: 386. DB::Exception: There is no supertype for types UInt64, Int8 because some of them are signed integers and some are unsigned integers, but there is no signed integer type, that can exactly represent all required unsigned integer values: While processing 100 AS number, if(number IS NULL, -1, ((60 * 60) * 24) * 90) AS test_bug. (NO_COMMON_TYPE) (version 22.11.1.1360 (official build))

But this equal query won't:
```sql
select 100 as number, if(isNull(number), -1, 7776000) as test_bug;
```

**Does it reproduce on recent release?**

It reproduces on 22.7.2.

**Expected behavior**

I expect the expression above to work without supertype error.

**Comment by tavplubix** [comment]
Everything works as expected, see https://clickhouse.com/docs/en/sql-reference/syntax/#literals and https://clickhouse.com/docs/en/sql-reference/functions/arithmetic-functions/ 

```
dell9510 :) select toTypeName(7776000) as t0, toTypeName(60) as t1, toTypeName(60 * 60) as t2, toTypeName(60 * 60 * 24) as t3, toTypeName(60 * 60 * 24 * 90) as t4

SELECT
    toTypeName(7776000) AS t0,
    toTypeName(60) AS t1,
    toTypeName(60 * 60) AS t2,
    toTypeName((60 * 60) * 24) AS t3,
    toTypeName(((60 * 60) * 24) * 90) AS t4

Query id: ef196405-5eb8-44d3-ad21-4f0412311344

┌─t0─────┬─t1────┬─t2─────┬─t3─────┬─t4─────┐
│ UInt32 │ UInt8 │ UInt16 │ UInt32 │ UInt64 │
└────────┴───────┴────────┴────────┴────────┘
```

**Comment by tema-popov** [comment]
Don't you find typing `60 * 60 * 24 * 90` to  `UInt64` but `7776000` to `UInt32` inconsistent? 

I would understand if an expression with a variable would be typed in this way as we don't know, what number we will multiply to, but in this case, there is an expression consisting of constants, which could be replaced with `7776000` at parsing SQL stage.

**Comment by den-crane** [comment]
```
 select 100 as number, if(isNull(number), 1, 60 * 60 * 24 * 90) as test_bug;
┌─number─┬─test_bug─┐
│    100 │  7776000 │
└────────┴──────────┘
```

WA:  toInt64

`select 100 as number, if(isNull(number), -1, toInt64(60 * 60 * 24 * 90)) as test_bug;`

>Don't you find typing 60 * 60 * 24 * 90 to UInt64 but 7776000 to UInt32 inconsistent?

It's consistent. Type interference operates by types not the exact values, because values can be different in different rows of the table.

And Clickhouse cannot cast  UInt64 to signed type Int64 automatically because it may lost data.

**Comment by tema-popov** [comment]
> And Clickhouse cannot cast UInt64 to signed type Int64 automatically because it may lost data.

Sure, that makes sense.

>  select 100 as number, if(isNull(number), 1, 60 * 60 * 24 * 90) as test_bug;
There is no visible problem because UInt8 and UInt64 could be cast to  UInt64, I understand that.

In my case, the problem is that I run  `if(isNull(number), -1, 60 * 60 * 24 * 90)` and get a typing error. in this case, it is a constant expression (which could be calculated and be equal to the UInt32 constant without any dependence on a row) But clickhouse casts `60 * 60 * 24 * 90` it to UInt64 and decides that UInt64 and Int8 don't have supertype, which makes sense. But the minimal type for a `60 * 60 * 24 * 90` in reality is UInt32 because the constant result of the expression is equal to 7776000 which is lower than 4294967295 and that could be discovered during query parsing and assigning explicit types in an expression.

So I would consider it a little problem in type caster, which results in a non-obvious error in query.

**Comment by den-crane** [comment]
Yes, but type interference is not implemented for this case (constant expressions), more general mechanism is used.
