### ISSUE TITLE
How to drop the partition sync?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#45426]
how to drop the partiton sync?

It is a mutation operation, is any way to operate sync? or any work aroud ways? 

thianks

version: 22.3.6.5

**Comment by DerekChia** [comment]
Add `replication_alter_partitions_sync=2` to your `ALTER TABLE .. DROP PARTITION ..`

replication_alter_partitions_sync - Wait for actions to manipulate the partitions. 0 - do not wait, 1 - wait for execution only of itself, 2 - wait for everyone.

https://clickhouse.com/docs/en/operations/settings/settings/#replication-alter-partitions-sync
https://clickhouse.com/docs/en/sql-reference/statements/alter/#synchronicity-of-alter-queries
