### ISSUE TITLE
`test_system_replicated_fetches` is flaky (suppressed)

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#45435]
https://s3.amazonaws.com/clickhouse-test-reports/0/85f32d8f4a6a88f24e923ea13238840aac21a25c/integration_tests__tsan__[2/4].html

test_system_replicated_fetches/test.py::test_system_replicated_fetches

```
>           assert (
                elem["bytes_read_compressed"] <= elem["total_size_bytes_compressed"]
            ), "Bytes read ({}) more than total bytes ({}). It's a bug".format(
                elem["bytes_read_compressed"], elem["total_size_bytes_compressed"]
            )
E           AssertionError: Bytes read (1052798552.0) more than total bytes (1052783734.0). It's a bug
E           assert 1052798552.0 <= 1052783734.0

```

FYI cc:@alesapin you added this check

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/45566/cd8c3bbcc5930797528597e6034ccf1cf8a1e5aa/integration_tests__tsan__[4/6].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/47839/27ef59d46e4f6812685c4051e62ff404df0f9cab/integration_tests__asan__[4/6].html

**Comment by tavplubix** [comment]
Suppressed by https://github.com/ClickHouse/ClickHouse/commit/81375431d99ea81de4f4e58931e75d97e590fada

But the test is still flaky:
https://s3.amazonaws.com/clickhouse-test-reports/48401/0e0e89d5964223a52758756f108f59e89f61d064/integration_tests__asan__[4/6].html

**Comment by alexey-milovidov** [comment]
It isn't disabled!
