### ISSUE TITLE
Question: PARTITION BY efficiency in MergeTree table.

### ISSUE THREAD

**Issue by ilya-girman** [ClickHouse/ClickHouse#45477]
Hello!
Sorry for disturbing, but I want to clarify can I use PARTITION BY in my case.
**The case:**
-  We have table with metrics for multitenant setup. We have columns like tenant_id and event_time. 
-  By requirements this table should be optimized for per-tenant use. 
-  Almost always tenant will query data for the LAST MONTH or for the LAST day. So we choose ORDER BY (tenant_id, event_time) key. And this works great.
-  Analytics want to use this database also for aggregated statistics (query will have range for event_time and no tenant_id specified). So we decided to add PARTITION BY toYYYYMM(event_time). 
- Table will contain data only for one year (will be controlled by database (TTL feature)). So we will get only 12 unique partition keys.
- Table engine will be ReplicatedMergeTree

**Our results**
Table with PARTITION BY gives us 25% less rows scanned for **analytical** queries on synthetic data. Tenant's queries are good in both cases.
**Question**
In many places it is pointed that PARTITION BY is not recommended to use for MergeTree-family engines. So I'm afraid that we can run into issues on production because of this decision.
Can we use PARTITION BY in this case or should we refuse to do this despite of better performance in our tests?

Thank you!

**Comment by den-crane** [comment]
>In many places it is pointed that PARTITION BY is not recommended to use for MergeTree-family engines.

What places?????? You have misunderstood something. 

PARTITION BY is only for MergeTree-family engines.

In your case I would recommend exactly `PARTITION BY toYYYYMM(event_time)`.

**Comment by ilya-girman** [comment]
Thank you a lot!
