### ISSUE TITLE
PFSense Cache Policy Name issue during installation

### ISSUE THREAD

**Issue by dkggpeters** [ClickHouse/ClickHouse#45514]
**Describe the unexpected behaviour**
Install binary script using the recommended script.

![image](https://user-images.githubusercontent.com/63671969/214077559-1d5424e9-07ab-4768-8e79-361e59c06b48.png)

PFSense is being ran on a Proxmox VM with Nic PCI Passthrough.

**How to reproduce**
1.) curl https://clickhouse.com/ | sh
2.) sudo ./clickhouse install

**Error message and/or stacktrace**
libc++abi: terminating due to uncaught exception of type DB::Exception: Undeclared cache policy name:
Abort
![Screenshot 2023-01-23 101848](https://user-images.githubusercontent.com/63671969/214077204-1393a610-ae03-4643-bee4-8514d9b85b97.jpg)

**Comment by kssenii** [comment]
To fix this you need to add `uncompressed_cache_policy` and `mark_cache_policy` as `LRU` or `SLRU` to server config. Or wait for https://github.com/ClickHouse/ClickHouse/pull/45524 where a proper default is added.

**Comment by dkggpeters** [comment]
I am still receiving the above error.

libc++abi: terminating due to uncaught exception of type DB::Exception: Undeclared cache policy name:
Abort

**Comment by kssenii** [comment]
> I am still receiving the above error.

did you update the config as I wrote?

**Comment by dkggpeters** [comment]
I am running the binary ./clickhouse install using curl -O https://s3.amazonaws.com/clickhouse-builds/45524/3a4d5ba07d7f240cddecb0d21b4035a6cbbca624/binary_freebsd/clickhouse && chmod a+x clickhouse

I only see a clickhouse.core file trying to be built and do not see any other files being generated.  How do I update the server config?

**Comment by kssenii** [comment]
it should be in `/var/lib/clickhouse-server/config.xml` by default

**Comment by dkggpeters** [comment]
When I run the ./clickhouse install or ./clickhouse server the only files with the name click* that get generated is clickhouse.core.  It bombs out with the error before anything files are extracted.  I did a search for any files with the name of click using find . | grep click to verify.

**Comment by kssenii** [comment]
then you can create a config file and pass it to clickhouse as `clickhouse server --config path_to_config/config.xml`

**Comment by dkggpeters** [comment]
Do I use the Set uncompressed_cache_policy=LRU or --uncompressed_cache_policy=LRU in the config.xml

Same for mark_cache_policy

**Comment by kssenii** [comment]
yes

**Comment by dkggpeters** [comment]
Still a no go.  It appears the binary file is ignoring the --config statement.

I still receive the same error.
