### ISSUE TITLE
BACKUP statement throws SyntaxError 

### ISSUE THREAD

**Issue by metheu** [ClickHouse/ClickHouse#45521]
**Describe the unexpected behaviour**
Trying to backup table to S3 and the backup fails to start. Syntax error on "BACKUP"

**How to reproduce**
* clickhouse version: 21.1.2.15
* `BACKUP TABLE db._test_table data on cluster 'cluster' TO S3('https://backup-s3/dev-backup/my_backup', 'xxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxx')`

**Expected behavior**
The table to be backed up to S3.

**Error message and/or stacktrace**
`Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1 ('BACKUP'): BACKUP TABLE db._test_table data data on cluster 'cluster' TO S3('https://backup-s3/dev-backup/my_backup'', 'xxxxxxxxxxxxx', 'xxxx'. Expected one of: ALTER query, Query with output, ALTER PROFILE, RENAME DATABASE, SHOW PRIVILEGES query, TRUNCATE, KILL, KILL QUERY query, SELECT query, possibly with UNION, list of union elements, ALTER ROLE, SELECT subquery, DESCRIBE query, SELECT query, subquery, possibly with UNION, SHOW GRANTS, SHOW CREATE, WATCH, CREATE SETTINGS PROFILE or ALTER SETTINGS PROFILE query, SHOW PROCESSLIST query, ALTER POLICY, ALTER USER, CREATE VIEW query, CHECK TABLE, SET ROLE, SELECT query, SELECT, REVOKE, CREATE USER, CREATE DICTIONARY, CREATE PROFILE, SET ROLE DEFAULT, EXPLAIN, ALTER SETTINGS PROFILE, SYSTEM, ALTER LIVE VIEW, RENAME TABLE, DROP query, SHOW ACCESS, OPTIMIZE query, USE, DROP access entity query, RENAME DICTIONARY, DETACH, SET, SHOW, DESC, OPTIMIZE TABLE, ...`

**Additional context**

I'm following the docs -> https://clickhouse.com/docs/en/operations/backup/, does this function/statement need to be enabled somehow?

**Comment by tavplubix** [comment]
> 21.1.2.15

This version is obsolete, you should upgrade.
