### ISSUE TITLE
Performance drop when switching to nested structures from separate columns

### ISSUE THREAD

**Issue by EgorSidorov** [ClickHouse/ClickHouse#45523]
I have a table visit with multiple columns where the results of experiments are recorded (there can be up to hundreds of thousands in the table).
Old structure look like:

create table IF NOT EXISTS visit
(
    VISITORCODE                            String,
    VISITNUMBER                            UInt16,
    TIMESTARTED                            DateTime,
    EXPERIMENT_ID Tuple(Nullable(DateTime64(3)), Nullable(UInt32)) (multiple rows for each id)
)
    engine = ReplacingMergeTree PARTITION BY toStartOfWeek(TIMESTARTED)
        ORDER BY (VISITORCODE, TIMESTARTED)
        SETTINGS index_granularity = 8192;

New structure:
create table IF NOT EXISTS visitContainerArray
(
    VISITORCODE                            String,
    VISITNUMBER                            UInt16,
    TIMESTARTED                            DateTime,
    `EXPERIMENT` Nested(ID UInt32,
    CONVERSIONAFTERTIME       DateTime64(3),
    VARIATIONID               UInt32)
)
    engine = ReplacingMergeTree PARTITION BY toStartOfWeek(TIMESTARTED)
        ORDER BY (VISITORCODE, TIMESTARTED)
        SETTINGS index_granularity = 8192;

After transferring the columns to the nested format and measuring the query speed (more than 100 million records for more than 1000 experiments were stored in the table), the reading speed from the new structure turned out to be 3-4 times slower. I reproduced a similar comparison for dynamically generated data, in the test case, the speed is 50% slower, but there are only 20 experiments. I believe that with an increase in the number of experiments, the difference will be more noticeable.

Old request: 405ms
New request: 621ms

Queries for comparison:
//621ms
SELECT COUNT(*) AS count,EXPERIMENT_131454.2 AS variation,toStartOfDay(toTimeZone(TIMESTARTED,'Europe/Berlin')) AS ventilation FROM visit WHERE  (EXPERIMENT_131454.1 IS NOT NULL) AND (0 OR (TIMESTARTED >= toUnixTimestamp(1622498400) AND TIMESTARTED < toUnixTimestamp(1646175600)))  GROUP BY variation, ventilation;
//626ms
SELECT COUNT(*) AS count,EXPERIMENT.VARIATIONID[indexOf(`EXPERIMENT.ID`, 131454)] AS variation,toStartOfDay(toTimeZone(TIMESTARTED,'Europe/Berlin')) AS ventilation FROM visitContainerNested WHERE  (has(`EXPERIMENT.ID`, 131454)) AND (0 OR (TIMESTARTED >= toUnixTimestamp(1622498400) AND TIMESTARTED < toUnixTimestamp(1646175600)))  GROUP BY variation, ventilation;
//405ms
SELECT COUNT(*) AS count,EXPERIMENT.VARIATIONID[indexOf(`EXPERIMENT.ID`, 131454)] AS variation,toStartOfDay(toTimeZone(TIMESTARTED,'Europe/Berlin')) AS ventilation FROM visitContainerArray WHERE  (has(`EXPERIMENT.ID`, 131454)) AND (0 OR (TIMESTARTED >= toUnixTimestamp(1622498400) AND TIMESTARTED < toUnixTimestamp(1646175600)))  GROUP BY variation, ventilation;

I tested both way of selecting: using ARRAY JOIN vs indexOf and nested columns as tuple vs as array. And array structure with indexOf query is more faster in my case.

Performance degradation with nested structure is unexpected, since it was assumed that the use of nested structures in this context is the standard approach.
Please advise what approaches can be used for nested structure so as not to lose performance.

Test case with 100 million rows and 20 experiments in attachment.
[consoleRequest.txt](https://github.com/ClickHouse/ClickHouse/files/10483512/consoleRequest.txt)

**Comment by den-crane** [comment]
What is `visitContainerNested` ?

>After transferring the columns to the nested format
>out to be 3-4 times slower

>621ms FROM visit
>405ms FROM visitContainerArray

You mean Arrays (Nested) are faster? Not slower. Right?

**Comment by den-crane** [comment]
Ah, do you mean you compared multiple columns VS Arrays?

**Comment by EgorSidorov** [comment]
Yes, I compared nested columns with multiple columns. Nested columns I tested as array and as tuple. visitContainerArray is a nested type of areay and visitContainerNested is a nested type of tuple.

**Comment by den-crane** [comment]
Like this?

1. visit = multiple column of    `Tuple(Nullable(DateTime64(3)), Nullable(UInt32))`

2. visitContainerArray = `Nested(ID UInt32, CONVERSIONAFTERTIME DateTime64(3), VARIATIONID UInt32)`

3. visitContainerNested = `Nested(Tuple(ID UInt32, Nullable(DateTime64(3)), Nullable(UInt32)))`

This is expected behaviour. 

In case 1  each experiment is stored in separate files and access to specific experiment cost X units.

In case 2, 3 all experiments are stored in stored in a single file and access to specific experiment cost X*N units. (number of experiments). Clickhouse reads all experiments and load into memory all experiments even if you query a single experiment.

check this https://kb.altinity.com/altinity-kb-schema-design/best-schema-for-storing-many-metrics-registered-from-the-single-source/

**Comment by mindgame73** [comment]
Hello :wave:  
I've remember asked similar question to @alexey-milovidov and got positive answer that strict type nested columns are fast enough compared to the traditional entity per column based schema. May be for the fist time using nested DM will not give big decreasing performance, but with large amount of data in it, as you say load all in memory will invoke potential issues later on. May be there are some improvements to come in future releases about it? Thanks.

**Comment by den-crane** [comment]
>nested columns are fast enough

Probably it means they are usable in some cases.

BTW why you don't store data in rows? Each experiment in the own row? Clickhouse likes rows not columns.

>breakdown for experiment A where we need join many experiments B,C,D

It's the easiest problem. You can make Nested (Array) from separate columns: `[col1, col2, col3]`

**Comment by den-crane** [comment]
>May be there are some improvements to come in future releases about it?

No, nothing like this.
