### ISSUE TITLE
Move data from one table to another with TTL

### ISSUE THREAD

**Issue by vlades233** [ClickHouse/ClickHouse#45530]
Hello everyone, 
I want to move some data from one table to another after TTL was expared. For example, table _Source_  has huge data with timestamp. TTL in this table set in 1 week. Is it possible to move data in destination table after 1 week with clickhouse tools without cronjobs? Engine is MergeTree. 
Thank you for your answer.

**Comment by den-crane** [comment]
No such feature. You can use `cronjobs` + `alter table ... move`.

**Comment by vlades233** [comment]
okey, thank you for your answer.
Have a good day.
