### ISSUE TITLE
Still flaky test_system_merges/test.py::test_mutation_simple[replicated]

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#45538]
New failure in this test (2023-01-22 22:09:56 > this merge)
https://s3.amazonaws.com/clickhouse-test-reports/0/c3d545b64aec058962775b079505610a8e35821a/integration_tests__release__[2/2].html

_Originally posted by @qoega in https://github.com/ClickHouse/ClickHouse/issues/45403#issuecomment-1401729607_

**Comment by tavplubix** [comment]
https://github.com/ClickHouse/ClickHouse/pull/45516
