### ISSUE TITLE
Missing instructions on how to install odbc bridge

### ISSUE THREAD

**Issue by AJK74** [ClickHouse/ClickHouse#45602]
Background
Create a new install on ubuntu latest as per the self managed install instructions [here](https://clickhouse.com/docs/en/install)

```
curl https://clickhouse.com/ | sh
sudo ./clickhouse install

```

Problem
The installer has not installed clickhouse-odbc-bridge.
I've not been able to find any documentation which explains how this can be installed.

I have found that this is by design, as per the comment in install.cpp.
[Install.cpp line 58](https://github.com/ClickHouse/ClickHouse/blob/master/programs/install/Install.cpp#L58)

Is there a straightforward way for me to add the odbc-bridge via this install route.

Thanks.

**Comment by DerekChia** [comment]
You can install clickhouse-odbc-bridge using any of the `clickhouse-common-static`

**Comment by AJK74** [comment]
Thanks @DerekChia 

so
```bash
curl -OL https://github.com/ClickHouse/ClickHouse/releases/download/v23.1.3.5-stable/clickhouse-common-static_23.1.3.5_amd64.deb

sudo dpkg -i clickhouse-common-static_23.1.3.5_amd64.deb
```

clickhououse-odbc-bridge is now in /bin
