### ISSUE TITLE
add docs for reading from partitioned data

### ISSUE THREAD

**Issue by DanRoscigno** [ClickHouse/ClickHouse#45609]
Please also check this issue https://github.com/ClickHouse/ClickHouse/issues/15171.

These engines are different from canonical engines where PARTITION BY can be added.
So worth to add an example how it can later be read. E.g. I mean if you try to read from a partitioned s3 table you will get an exception - which is not obvious and should be mentioned in docs. So you can have a partitioned table engine but can only write with it. Partitioned writes can be done with table function as well. Reading partitioned data can be done only with table functions or table engines without partition by. Also it is useful to read this data with wildcards.

**Comment by DanRoscigno** [comment]
Working through this:
- writing to partitions using the S3 Tabe Engine works
- reading from the individual partitions works
- reading from the table is not supported when partitions are used--it is my understanding that writing to partitions was added to assist in exporting data and not for creating tables to be used for analytics.

@kssenii can you please have a look at this?

Using the:
- docker compose from [examples](https://github.com/ClickHouse/examples/tree/5fdc6ff72f4e5137e23ea075c88d3f44b0202490/docker-compose-recipes/recipes/ch-and-minio-S3)
- [test](https://github.com/ClickHouse/ClickHouse/blob/master/tests/integration/test_storage_s3/test.py#L142-L166)

```sql
CREATE TABLE p
(
    `column1` UInt32,
    `column2` UInt32,
    `column3` UInt32
)
ENGINE = S3('http://minio:10000/clickhouse//test_{_partition_id}.csv', 'minioadmin', 'minioadminpassword', 'CSV')
PARTITION BY column3
```

```sql
insert into p values (1, 2, 3), (3, 2, 1), (78, 43, 45)
```

```sql
SELECT *
FROM s3('http://minio:10000/clickhouse//test_3.csv', 'minioadmin', 'minioadminpassword', 'CSV')

Query id: d21541a9-fc37-49c7-9496-afd0fb229a1d

┌─c1─┬─c2─┬─c3─┐
│  1 │  2 │  3 │
└────┴────┴────┘
```

```sql
SELECT *
FROM s3('http://minio:10000/clickhouse//test_1.csv', 'minioadmin', 'minioadminpassword', 'CSV')

Query id: c810ec25-dad8-455c-8afc-4b68e8a8fa69

┌─c1─┬─c2─┬─c3─┐
│  3 │  2 │  1 │
└────┴────┴────┘

1 row in set. Elapsed: 0.007 sec. 
```

```sql
SELECT *
FROM s3('http://minio:10000/clickhouse//test_45.csv', 'minioadmin', 'minioadminpassword', 'CSV')

Query id: 8c214928-f1ae-4238-81aa-1a2cc87718ae

┌─c1─┬─c2─┬─c3─┐
│ 78 │ 43 │ 45 │
└────┴────┴────┘

1 row in set. Elapsed: 0.009 sec. 
```

```sql
SELECT *
FROM p

Query id: 3ed56515-f168-4583-b7c3-d9c661289229


0 rows in set. Elapsed: 0.001 sec. 

Received exception from server (version 23.4.1):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Reading from a partitioned S3 storage is not implemented yet. (NOT_IMPLEMENTED)
```

**Comment by kssenii** [comment]
> it is my understanding that writing to partitions was added to assist in exporting data and not for creating tables to be used for analytics

yes, though you can read all partitions using globs, e.g. `SELECT *
FROM s3('http://minio:10000/clickhouse//test_*.csv', 'minioadmin', 'minioadminpassword', 'CSV')`

though I actually think reading from s3 storage could be allowed as well (just reading from all partitions which not difficult to do), I do not know why it was not done by the author of this feature.

**Comment by DanRoscigno** [comment]
> > it is my understanding that writing to partitions was added to assist in exporting data and not for creating tables to be used for analytics
> 
> yes, though you can read all partitions using globs, e.g. `SELECT * FROM s3('http://minio:10000/clickhouse//test_*.csv', 'minioadmin', 'minioadminpassword', 'CSV')`
> 
> though I actually think reading from s3 storage could be allowed as well (just reading from all partitions which not difficult to do), I do not know why it was not done by the author of this feature.

For now, I will document that the filename for the partition should include the parameter token ( `{_partition_id}` in the example above) and that filename globs work in addition to using the individual filenames.  I have similar text in the HDFS and file docs I think.  If we change to allow querying from the table directly we can update again.  Thanks all!
