### ISSUE TITLE
Syntax error on attempt to specify default expression for EPHEMERAL column 

### ISSUE THREAD

**Issue by Alex-Burmak** [ClickHouse/ClickHouse#45622]
While trying to upgrade ClickHouse from 22.3.17 LTS to 22.8.13 LTS I'm faced with the backward-incompatibility issue in  EPHEMERAL column functionality. Attempt to create or attach table with a function in default expression for EPHEMERAL columns now results to syntax error. 

```
CREATE TABLE users (
    uid Int16,
    event_date Date EPHEMERAL toDate(now())
) ENGINE=Memory;
```

```
Code: 62. DB::Exception: Syntax error: failed at position 67 ('toDate') (line 3, col 31): toDate(now())
) ENGINE=Memory;
. Expected one of: literal, NULL, number, Bool, true, false, string literal, NOT, COMMENT, CODEC, TTL, token, Comma, ClosingRoundBracket. (SYNTAX_ERROR)
```

https://fiddle.clickhouse.com/9225a990-c522-41ff-b722-f981cb7083de

The same is for the latest version.
https://fiddle.clickhouse.com/4f83492a-f18f-4c37-9c2f-87e52a18ba0c

But in 22.3 the same query works fine.
https://fiddle.clickhouse.com/cc4acc80-d8f5-442d-bcbf-e6ac52ea47aa

**Comment by tavplubix** [comment]
Maybe we should just backport https://github.com/ClickHouse/ClickHouse/pull/44026 (but I have no idea why it stopped working in 22.8)

**Comment by yakov-olkhovskiy** [comment]
It stoped working because another PR https://github.com/ClickHouse/ClickHouse/pull/36633 
and I'm not sure it was working correctly before.

**Comment by yakov-olkhovskiy** [comment]
fixed and backported:
https://github.com/ClickHouse/ClickHouse/pull/44026
