### ISSUE TITLE
Create standalone clickhouse-format utility

### ISSUE THREAD

**Issue by e-mars** [ClickHouse/ClickHouse#45628]
**Use case**
Users sometimes need to format queries locally without having to install a full version of ClickHouse.

**Describe the solution you'd like**
Stand-alone binary to format and validate queries prior to send to ClickHouse

**Describe alternatives you've considered**
Install ClickHouse and use the utility although not all features, even with clickhouse-local is not necessary.

**Comment by heavelock** [comment]
Having CH formatter would let us save quite a lot of hassle with misformated queries. We could simply pick them up on CI/pre-commit stage and be more sure about what we check into our codebase. 

Currently we are considering creating endpoint just for CH-formatter that could be used on a system test stage but tbh, it's far from being an optimal solution.

**Comment by alexey-milovidov** [comment]
This will be nice to have.

Just in case: if the binary size is not a concern, here is how to use it:
```
curl https://clickhouse.com/ | sh
mv clickhouse clickhouse-format
```

**Comment by heavelock** [comment]
Okay, it's easier that I thought then. For CI it will work - I can simply extract the artifact and use it around. However, it still is problematic to ship it around to users. Have you considered distributed it with python for example? Wrapping it with a thin layer of py would allow shipping it virtually to anyone and also would allow creating a pre-commit hook.

**Comment by heavelock** [comment]
Hey, any more thoughts on that issue?

**Comment by alexey-milovidov** [comment]
This is a good idea, and creating this standalone utility is a matter of modifying CMake files (build definition) a little.
