### ISSUE TITLE
MongoDB table function/engine error message: client driver may require an upgrade

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/ClickHouse#45621]
> You have to provide the following information whenever possible.

I am using the `mongodb` table function to query a collection running on Mac OS and the latest version of ClickHouse (22.13.1.3062). Here is the SQL command:

```
SELECT * FROM mongodb(
    '127.0.0.1:27017',
    'test',
    'my_collection',
    'test_user',
    'password',
    'log_type String, host String, command String',
    'connectTimeoutMS=10000'
)
```

> A clear and concise description of what works not as it is supposed to.

I get the following error (using the `mongodb` table function or the `MongoDB` table engine):

```
Query id: 65d733f6-6ee1-4270-bdd8-875fdd08db38


0 rows in set. Elapsed: 0.026 sec.

Received exception from server (version 22.13.1):
Code: 634. DB::Exception: Received from localhost:9000. DB::Exception: Got error from MongoDB: 
OP_QUERY is no longer supported. 
The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal, code: 5739101: While executing MongoDB. (MONGODB_ERROR)
```

If you research that error, it appears that OP_QUERY was deprecated after MongoDB 5+. This could totally be an issue with my setup, but I did try an old version of MongoDB and got the same error message. I tried updating the `mongo-c-driver` on my Mac, but I'm ClickHouse doesn't use a local driver.

> A clear and concise description of what you expected to happen.

I assumed I would get back the documents that I inserted in my mongodb collection, as a ClickHouse table.

**Comment by DerekChia** [comment]
I got the same error as well when using MongoDB version 6.0.4.
