### ISSUE TITLE
function like `identity` which will disable common subexpression elimination

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#45653]
**Use case**

generation of random values with random* functions within one row.

With current approach:

```
SELECT
    randomFixedString(15 + 1),
    randomFixedString(16)
```

You can't just wrap it in SQL CTE without exposing of additional parameter.

**Describe the solution you'd like**

```
SELECT
    disableCommonSubexElim(randomFixedString(16)),
    disableCommonSubexElim(randomFixedString(16))
```

**Describe alternatives you've considered**

```
SELECT
    randomFixedString(15 + 1),
    randomFixedString(16)

Query id: ed4f2f57-61bf-4b9e-a444-93bc398db721

┌─randomFixedString(plus(15, 1))─┬─randomFixedString(16)─┐
│ �h�0���Z<$g���a                       │ +���\�֊MM��o>               │
└────────────────────────────────┴───────────────────────┘
```

**Comment by alexey-milovidov** [comment]
The proposal is too unnatural. I don't want users to learn, know or rely on it.

**Comment by alexey-milovidov** [comment]
There should not be something named `SubexElim` instead of `SubexpressionElimination`.

**Comment by UnamedRus** [comment]
> The proposal is too unnatural. I don't want users to learn, know or rely on it.

Ok, but how to shadow usage of random function (for example IV generation in encode functions) from user via SQL CTE and don't expose internal specifics which disable unneeded optimizations?

**Comment by alexey-milovidov** [comment]
Every random generation function should have a "tag" argument for disambiguation.
Example:
```
milovidov-desktop :) SELECT rand('first'), rand('second')

SELECT
    rand('first'),
    rand('second')

Query id: 6bd6fbcd-9f6a-4a9f-83c2-ad563ce1205b

┌─rand('first')─┬─rand('second')─┐
│    3038212987 │      661317613 │
└───────────────┴────────────────┘
```

**Comment by alexey-milovidov** [comment]
Another issue should be created to add the "tag" argument where it is missing.
