### ISSUE TITLE
clickhouse-format doesn't hilite some identifiers

### ISSUE THREAD

**Issue by murfel** [ClickHouse/ClickHouse#45668]
Hey!

1. In this query the `identifier` is not hilited — is it intended behaviour? I think it should either be hilited as an identifier, or an alias.
```
$ ./clickhouse-format --hilite --query "with identifier as (select * from table) select * from table"
WITH identifier AS
    (
        SELECT *
        FROM table
    )
```
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTWithElement.cpp#L21

![image](https://user-images.githubusercontent.com/5155395/214872393-ab697d98-26a7-45d7-9579-d19071debd43.png)

2. And also there's another identifier output without being hilited, but I cannot come up with the query which corresponds to this code - any help?
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTWithAlias.cpp#L23

3. There seems to be an inconsistensy of manually applied hilite, as it's never removed within this if:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTFunction.cpp#L585

**Comment by KochetovNicolai** [comment]
1. Looks like a bug. Let's highlight.

**Comment by KochetovNicolai** [comment]
2. `clickhouse format --hilite --query "select a + 1 as b, a + 1 as b"`.

**Comment by KochetovNicolai** [comment]
3. Also bug
`clickhouse format --hilite --query "select * from view(select 1 from table group by 1) where 1"`
![image](https://user-images.githubusercontent.com/4092911/214894166-42d35a02-6314-4e79-acb7-4fe8b41e5a5e.png)
second select should not be highlighted

**Comment by murfel** [comment]
> 2. `clickhouse format --hilite --query "select a + 1 as b, a + 1 as b"`.
![image](https://user-images.githubusercontent.com/5155395/214898670-cb1eabd1-e9fc-426d-b659-1c77b0f8bb37.png)

Thanks! I will hilite the second `b` as an identifier, then.

**Comment by murfel** [comment]
Another bug, as agreed with Nicolai.

Using `hilite_none` when it doesn't do anything. Not visible to user.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTSystemQuery.cpp#L203

**Comment by murfel** [comment]
Here hilite has not been taken off.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/Access/ASTCreateRowPolicyQuery.cpp#L153

**Comment by murfel** [comment]
There's very little usage of `hilite_operator`. E.g. there's one use of `hilite_operator` to hilite the string `" = "`, but there are also 9 occurences of `" = "` in Parser/* that go without hiliting.

Using hilite https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTAssignment.h#L36

Not using hilite e.g. https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/Access/ASTSettingsProfileElement.cpp#L40

Just want to confirm that none of those are operators and it's not a mistake?

```
$ grep -rn "\" = \"" Parsers/*
Parsers/Access/ASTCreateQuotaQuery.cpp:63:        settings.ostr << " " << type_info.name << " = " << type_info.valueToString(max_value);
Parsers/Access/ASTSettingsProfileElement.cpp:40:        settings.ostr << " = " << applyVisitor(FieldVisitorToString{}, value);
Parsers/ASTAlterNamedCollectionQuery.cpp:33:                settings.ostr << " = " << applyVisitor(FieldVisitorToString(), change.value);
Parsers/ASTAssignment.h:33:        settings.writeOperator(" = ");
Parsers/ASTCreateNamedCollectionQuery.cpp:37:            settings.ostr << " = " << applyVisitor(FieldVisitorToString(), change.value);
Parsers/ASTCreateQuery.cpp:42:        s.ostr << (s.hilite ? hilite_keyword : "") << s.nl_or_ws << "ENGINE" << (s.hilite ? hilite_none : "") << " = ";
Parsers/ASTDictionary.cpp:121:        settings.ostr << it->name << " = " << applyVisitor(FieldVisitorToString(), it->value);
Parsers/ASTFunction.cpp:673:                "equals",          " = ",
Parsers/ASTSetQuery.cpp:37:        format.ostr << " = " << applyVisitor(FieldVisitorToString(), change.value);
Parsers/ASTSetQuery.cpp:59:        format.ostr << " = " << value;

```

**Comment by murfel** [comment]
Hilite has not been taken off x2
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTAlterQuery.cpp#L165

**Comment by murfel** [comment]
Unnecessary `hilite_none`
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTAlterQuery.cpp#L193

**Comment by murfel** [comment]
Hilite not taken off x3
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTAlterQuery.cpp#L486

**Comment by murfel** [comment]
Does this really need hilite before the internal thing is written?
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTColumnsMatcher.cpp#L49

**Comment by murfel** [comment]
This closing bracket should be hilited, just like its pairing opening bracket
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTCreateQuery.cpp#L436

**Comment by murfel** [comment]
Hilite not taken off x4
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTDictionaryAttributeDeclaration.cpp#L59

**Comment by murfel** [comment]
Unnecessary hilite_none (probably invisible to user)

https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTDictionary.cpp#L123

**Comment by murfel** [comment]
Matching parentesis is not hilited
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTDictionary.cpp#L164

**Comment by murfel** [comment]
The internal formatImpl doesn't need to be hilited
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTDropIndexQuery.cpp#L34

**Comment by murfel** [comment]
Hilite not taken off
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTFunctionWithKeyValueArguments.cpp#L30

**Comment by murfel** [comment]
Do the parentesis need to be keyword-hilited as well? Otherwise what's the use of canceling the hilite at the end of the function.

https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTFunctionWithKeyValueArguments.cpp#L88
(Didn't fix in refactoring yet - not sure if needed)

**Comment by murfel** [comment]
Hilite applied multiple times

https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTInsertQuery.cpp#L49

**Comment by murfel** [comment]
Hilite not taken off
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTKillQueryQuery.cpp#L31

**Comment by murfel** [comment]
Do we need space between `TESTSYNC` or `TESTASYNC`?
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTKillQueryQuery.cpp#L40

**Comment by alexey-milovidov** [comment]
@murfel I see it can be either `TEST`, `SYNC`, or `ASYNC`.

**Comment by alexey-milovidov** [comment]
So many bugs :) Your change will fix all of them.

**Comment by murfel** [comment]
I keep track of the bugs so that I could later check that my hiliting refactoring didn't affect any behaviour by running format before / after change on a bunch of SQL queries. But if I fix these bugs in my change (and I will), it **will** change behaviour,

So I'm thinking of fixing all these issues separately before refactoring.

**Comment by murfel** [comment]
Comma prob shouldn't be hilited as a keyword

https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTTablesInSelectQuery.cpp#L212

**Comment by murfel** [comment]
@alexey-milovidov  I keep track of the bugs so that I could later check that my hiliting refactoring didn't affect any behaviour by running format before / after change on a bunch of SQL queries. But if I fix these bugs in my change (and I will, and it's hard not to), it will change behaviour.

So I'm thinking of fixing all these issues separately before refactoring.

**Comment by alexey-milovidov** [comment]
Good, let's proceed this way.

**Comment by murfel** [comment]
Opening bracket is hilited, closing isn't 

https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTFunction.cpp#L865

**Comment by murfel** [comment]
`clickhouse-format --oneline --hilite --query "SELECT one, two FROM table, mable"`

doesn't hilite the first comma, but does hilite the second one. It's probably an unintentional hilite, as no commas are hilited in ASTExpressionList (first comma).

![image](https://user-images.githubusercontent.com/5155395/228198210-b0358c18-0c52-4405-aee1-a5fe6b2c91a5.png)

I attribute this unintentional behaviour to a dangling `hilite_keyword` in ASTTableJoin:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTTablesInSelectQuery.cpp#L151

The issue is found when testing the https://github.com/ClickHouse/ClickHouse/pull/45649 refactoring.

**Comment by KochetovNicolai** [comment]
```
clickhouse format --hilite --query "create table t as (select 1) comment 'hello'"
```
![image](https://user-images.githubusercontent.com/4092911/228210703-84146716-6e4b-4155-b871-e2160fd1b477.png)

**Comment by KochetovNicolai** [comment]
`clickhouse format --hilite --query "alter table tab add index index_name a + b type set GRANULARITY 1"`
`clickhouse format --hilite --query "alter table tab drop index index_name"`

![image](https://user-images.githubusercontent.com/4092911/228219152-8c0e5a9c-26a5-499f-9c78-ce786ce17288.png)

**Comment by KochetovNicolai** [comment]
```
clickhouse format --hilite --query "CREATE DICTIONARY somename (Name ClickHouseDataType DEFAULT '' EXPRESSION rand64()) SOURCE(HTTP(url 'http://[::1]/os.tsv' format 'TabSeparated' credentials(user 'user' password 'password') headers(header(name 'API-KEY' value 'key'))))"
```

![image](https://user-images.githubusercontent.com/4092911/228226127-4176eafc-c3d9-402a-9eba-417c7b1123b4.png)


It's hard to see what's wrong here.
Opening brackets:
`SOURCE(HTTP(URL`
![image](https://user-images.githubusercontent.com/4092911/228226423-629b39d2-4e4d-4efb-ae45-d0f86bf693cb.png)
(the first one is highlighted, the second one is not)
Closing brackets:
![image](https://user-images.githubusercontent.com/4092911/228226625-8e068499-f43b-42d0-bf71-e11ce0e8c533.png)

both not highlighted 
(maybe it's a different bug)

**Comment by murfel** [comment]
The one with SOURCE is listed above. I'll investigate if there are overlapping bugs.

Thank you!

**Comment by murfel** [comment]
> ```
> clickhouse format --hilite --query "CREATE DICTIONARY somename (Name ClickHouseDataType DEFAULT '' EXPRESSION rand64()) SOURCE(HTTP(url 'http://[::1]/os.tsv' format 'TabSeparated' credentials(user 'user' password 'password') headers(header(name 'API-KEY' value 'key'))))"
> ```
> 
> ![image](https://user-images.githubusercontent.com/4092911/228226127-4176eafc-c3d9-402a-9eba-417c7b1123b4.png)
> 
> It's hard to see what's wrong here. Opening brackets: `SOURCE(HTTP(URL` ![image](https://user-images.githubusercontent.com/4092911/228226423-629b39d2-4e4d-4efb-ae45-d0f86bf693cb.png) (the first one is highlighted, the second one is not) Closing brackets: ![image](https://user-images.githubusercontent.com/4092911/228226625-8e068499-f43b-42d0-bf71-e11ce0e8c533.png)
> 
> both not highlighted (maybe it's a different bug)

Since I fixed the SOURCE bug, there's no longer an inconsistency between matching opening/closing parenthesis. `CREATE DICTIONARY`, `SOURCE`, and `HTTP` are not hilited. However, the parenthesis within `HTTP` `FunctionWithKeyValueArguments` consisting of `ASTPair`s are hilited.

https://github.com/ClickHouse/ClickHouse/blob/8d72f75556bbbb7dbe5675324bb3e00634480492/src/Parsers/ASTFunctionWithKeyValueArguments.cpp#L30

![image](https://user-images.githubusercontent.com/5155395/228416340-8902f43d-1aa7-488b-b8d9-677b0a89beca.png)

It is weird but looks like (not a very thought-through but still) a choice. Won't be fixing it here but creating an umbrella issue to collect clickhouse-format funny behaviours #48140.

**Comment by murfel** [comment]
> Does these really need hilite before the internal thing is written? https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTColumnsMatcher.cpp#L49 https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTColumnsMatcher.cpp#L124 https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTColumnsMatcher.cpp#L202 https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/ASTColumnsMatcher.cpp#L248

The last thing left (hopefully). Can't come up with a triggering query with `ASTColumnsRegexpMatcher`, my best attempt is:

```
INSERT INTO table_name (columns.*) FROM INFILE 'filename'

InsertQuery__, 0x00007efc4fe38418
-Literal_'filename', 0x00007efc4fe50818
-Identifier_table_name, 0x00007efc4fe201d8
-ExpressionList, 0x00007efc4febedd8
--QualifiedAsterisk, 0x00007efc4febecf8
---Identifier_columns, 0x00007efc4fe20458
```
