### ISSUE TITLE
Allow duplicate nested -ForEach aggregate combinator 

### ISSUE THREAD

**Issue by rfraposa** [ClickHouse/ClickHouse#45675]
**Use case**

If appears that duplicate nested combinators do not work (like `-IfIf`), but `-ForEachForEach` actually does work and was disabled here: https://github.com/ClickHouse/ClickHouse/commit/1e7714d56d21ed8a225c59d0ce3e0c013e356bf6

**Describe the solution you'd like**

Allow the `-ForEach` aggregate combinator to be duplicated. This should work (and historically did work):

```
SELECT sumForEachForEach(matrix)
FROM 
(
    SELECT 
        1 AS id, 
        [[1, 3], [2, 4]] AS matrix
    UNION ALL
    SELECT 
        2 AS id, 
        [[2, 4], [3, 5]] AS matrix
    UNION ALL
    SELECT 
        3 AS id, 
        [[1, 2], [1, 0]] AS matrix
)
```

Result:

```
┌─sumForEachForEach(matrix)─┐
│ [[4,9],[6,9]]             │
└───────────────────────────┘
```

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/40776

**Comment by rfraposa** [comment]
Yup - duplicate. Do we know if other combinators can be nested properly, or is it just `-ForEach`?

**Comment by mrcrypster** [comment]
-ArrayArray seems to be also usefull (matrices aggregates)

**Comment by UnamedRus** [comment]
ResampleResample
