### ISSUE TITLE
PFSense Install Core Dumps

### ISSUE THREAD

**Issue by dkggpeters** [ClickHouse/ClickHouse#45684]
**I have tried the following solutions**
This is a continuation of my issue #45514 in which I tried what was requested and would still receive the below errors.

**Installation type**
PFSense 2.6 with FreeBSD 12.3 Stable

<img width="296" alt="PFSense" src="https://user-images.githubusercontent.com/63671969/214979731-ecc49de7-001a-4287-afd2-11c36a9df526.png">

**Source of the ClickHouse**
curl https://clickhouse.com/ | sh
./clickhouse install

**What you expected**

The installation script to run to completion.  I ran on my Ubuntu 22.04 VM which completed successfully and is working.

**The actual result**
<img width="640" alt="error" src="https://user-images.githubusercontent.com/63671969/214979155-b07590c4-5521-4d19-8838-02f628a118ff.png">

The install script would not try and copy files, setup directories, or add usernames or group for clickhouse.  The only activity that would occur was a core dump in which I ran a gdb on below.  It appears to be #8 which is causing the problem.

<img width="685" alt="clickhouse core" src="https://user-images.githubusercontent.com/63671969/214979475-66143df2-6d2b-40d6-8702-6a95d025ac5e.png">

I also did a cat clickhouse.core and the problems appear to happen after the below.

<img width="680" alt="schema" src="https://user-images.githubusercontent.com/63671969/214980481-8a419acd-cbc1-4f3f-b2cc-2b631ca033a5.png">

**Comment by alexey-milovidov** [comment]
If I want to reproduce it on AWS, what AMI should I use?

**Comment by alexey-milovidov** [comment]
No info was provided.
