### ISSUE TITLE
Docs: rename title of page to Deduplication Strategies

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/ClickHouse#45708]
**Describe the issue**
This deduplication page in the Docs is still a bit hard to find - Google doesn't find it easily
https://clickhouse.com/docs/en/guides/developer/deduplication/

I'd recommend a few changes, although feel free to implement as you think best:

1. Rename title of page to "Deduplication Strategies" per the left-hand-menu. The current title is long and probably not indexed well "Row-level Deduplication Strategies for Upserts and Frequent Updates"

2. I'd suggest moving the "Deduplication Strategies" menu link out from SQL->Guides and instead up to Ingest->Deduplication Strategies (this will uplevel the depth of this page by 1)

**Additional context**
The whole SQL->Guides list of menu options might be unnecessary if we can reinsert these pages to other locations in the Docs:
SQL->Guides:
- Deduplication Strategies
- Updating and Deleting Data
- JSON
- Transactional (ACID) support

**Comment by justindeguzman** [comment]
1. Renamed in this PR: https://github.com/ClickHouse/clickhouse-docs/pull/1379
2. This guide was moved in the Q1 2023 docs re-organization

**Comment by thomoco** [comment]
Thanks @justindeguzman - can we close this then?
