### ISSUE TITLE
Syntax error when CTE contains JSONEachRow

### ISSUE THREAD

**Issue by lewisdawson** [ClickHouse/ClickHouse#45709]
The following CTE fails to run with a code 62 syntax error on the `format JSONEachRow` line:
```SQL
create table default.test
(
    message string
)
engine = mergetree
order by message
;

insert into default.test values ('{"a": 1, "b": { "c": 2, "d": [1, 2, 3] }}');
insert into default.test values ('{"a": 10, "b": { "c": 20, "d": [10, 20, 30] }}');

with data_json as (
    select
        *
    from default.test
    format JSONEachRow
)

select * from data_json
;
```

The full error is:
```
Code: 62. DB::Exception: Syntax error: failed at position 68 ('format') (line 5, col 5): format JSONEachRow )  
select * from data_json. 
Expected one of: token, Dot, UUID, alias, AS, identifier, FINAL, SAMPLE, table, table function, subquery or list of joined tables, array join, LEFT ARRAY JOIN, INNER, ARRAY JOIN, JOIN, PREWHERE, WHERE, GROUP BY, WITH, HAVING, WINDOW, ORDER BY, LIMIT, OFFSET, SETTINGS, UNION, EXCEPT, INTERSECT. (SYNTAX_ERROR) (version 22.10.2.11 (official build))
```

System configuration:
OS: Debian 11 (Bullseye)
Clickhouse server: 22.10.2.11

Two questions:
1. Is this just not supported syntax or is this a bug? 
2. If it's not supported/bug, what's the best way to convert a string-typed json column into an actual JSON-typed column?

**Comment by den-crane** [comment]
this is not supported.

`format JSONEachRow` is supported for insert as an input format
`format JSONEachRow`is supported for queries as an output format

https://clickhouse.com/docs/en/guides/developer/working-with-json

https://kb.altinity.com/altinity-kb-schema-design/altinity-kb-jsonasstring-and-mat.-view-as-json-parser/
https://kb.altinity.com/altinity-kb-queries-and-syntax/jsonextract-to-parse-many-attributes-at-a-time/

**Comment by lewisdawson** [comment]
Thanks for the info @den-crane, appreciate you taking the time to answer my inquiry.
One more related question. Are there any plans to support `SELECT` casting to JSON without having to define the data's structure? For example:

```SQL
select
    cast('{"a": 1, "b": { "c": 2, "d": [1, 2, 3] }}' as json) as data
;
```

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/guides/developer/working-with-json/json-semi-structured#json-object-type

```sql
set allow_experimental_object_type=1;
create table J ( J JSON) Engine=MergeTree order by tuple();

insert into J select '{"a": 1, "b": { "c": 2, "d": [1, 2, 3] }}';

 DESCRIBE J SETTINGS describe_extend_object_types=1;
─name─┬─type──────────────────────────────────────────┬
 J    │ Tuple(a Int8, b Tuple(c Int8, d Array(Int8))) │
──────┴───────────────────────────────────────────────┴


select `J.a`, `J.b.c`, `J.b.d` from J;
┌─J.a─┬─J.b.c─┬─J.b.d───┐
│   1 │     2 │ [1,2,3] │
└─────┴───────┴─────────┘
```

**Comment by lewisdawson** [comment]
Thanks again for the assistance @den-crane!
