### ISSUE TITLE
No response from security@clickhouse.com

### ISSUE THREAD

**Issue by itrofimow** [ClickHouse/ClickHouse#45714]
Hi!

I've filed an issue to security@clickhouse.com and got no response within specified SLA of 5 working days.

What should i do next?

**Comment by thomoco** [comment]
Hi @itrofimow - I'm sorry to hear that, will ping the Security team right now. Stand by please

**Comment by itrofimow** [comment]
Wow, that's an extremely fast reply. Thank you @thomoco

**Comment by thomoco** [comment]
I'm sorry you waited 5 days....so not fast and usually much faster.... Working on it

**Comment by thomoco** [comment]
Hi @itrofimow - you should have received an initial response from the Security team now. It looks like your message unfortunately got routed into a Spam box, so thank you for your patience and for the additional contact, and sorry again. (We also disabled the spam checks on the security@clickhouse.com inbox.) We do take security reports very seriously here at ClickHouse and genuinely appreciate your security research and input. Once the dev team takes a deeper look at the report, we will provide further followup. Thanks - we'll close this issue at this time and please let us know if any further questions or reports

**Comment by itrofimow** [comment]
Got the email

I'm glad we've got this resolved, and notably this quickly. Thank you once again
