### ISSUE TITLE
generateRandom does not support some data types (Map, IPv4)

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#45726]
**Describe the issue**
Working on generating test data, I received at least the following errors:

```
The 'GenerateRandom' is not implemented for type IPv4: While executing GenerateRandom. (NOT_IMPLEMENTED) (version 22.13.1.1)

The 'GenerateRandom' is not implemented for type Map: While executing GenerateRandom. (NOT_IMPLEMENTED) (version 22.13.1.1)

# And when trying Enum types 
DB::Exception: Syntax error: ...  Unmatched parentheses: (. 
```

The [documentation](https://clickhouse.com/docs/en/sql-reference/table-functions/generate/) currently says ` Supports all data types that can be stored in table except LowCardinality and AggregateFunction.` which appears to be incorrect.

**Comment by tavplubix** [comment]
It will never be correct. We can update the documentation, but then we will add another data type and the documentation will become incorrect again. We can solve it by adding something like `insertRandomInto` or `createColumnWithRandomValues` virtual method to `IDataType` interface, so it always will be implemented for all data types.

**Comment by tavplubix** [comment]
>  Supports all data types that can be stored in table except LowCardinality and AggregateFunction.

Btw, it was recently implemented for LowCardinality: https://github.com/ClickHouse/ClickHouse/pull/45661

**Comment by genzgd** [comment]
Re Enum, I believe you're correct, my test code wasn't escaping quotes correctly.
