### ISSUE TITLE
Can't start the clickhouse cluster

### ISSUE THREAD

**Issue by hydezzz** [ClickHouse/ClickHouse#45746]
>I install the clickhouse cluster in kubesphere,the clickhouse version is v2.1.1 [21.1], and we have three nodes.

 # value.yaml

clickhouse:
  clusterName: all-nodes
  shardscount: 1
  replicascount: 3

  image: radondb/clickhouse-server:21.1.3.32
  imagePullPolicy: IfNotPresent

  resources:
    memory: "2Gi"
    cpu: "0.5"
    storage: "100Gi"

  user:
    - username: clickhouse
      password: c1ickh0use0perator
      networks:
        - "127.0.0.1"
        - "::/0"

  ports:
    tcp: 9000
    http: 8123

  svc:
    type: ClusterIP
    qceip:

busybox:
  image: busybox
  imagePullPolicy: IfNotPresent

zookeeper:
  install: true
  replicas: 3
  port: 2181
  image: radondb/zookeeper:3.6.1
  imagePullPolicy: IfNotPresent

>the first error problem 

<Error> default.tableName (ReplicatedMergeTreeRestartingThread): Couldn't start replication: Replica /clickhouse/tables/0/default/ tableName/replicas/chi-clickho-jeocis-all-nodes-0-0 appears to be already active (host: chi-clickho-jeocis-all-nodes-0-0-0.chi-clickho-jeocis-all-nodes-0-0.lowcode-app.svc.cluster.local, port: 9009, tcp_port: 9000, database: default, table:  tableName, scheme: http, ). If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/0/default/ tableName/replicas/chi-clickho-jeocis-all-nodes-0-0/is_active manually. Code: 224, e.displayText() = DB::Exception: Replica /clickhouse/tables/0/default/ tableName/replicas/chi-clickho-jeocis-all-nodes-0-0 appears to be already active (host: chi-clickho-jeocis-all-nodes-0-0-0.chi-clickho-jeocis-all-nodes-0-0.lowcode-app.svc.cluster.local, port: 9009, tcp_port: 9000, database: default, table: tableName, scheme: http, ). If you're sure it's not, try again in a minute or remove znode /clickhouse/tables/0/default/ tableName/replicas/chi-clickho-jeocis-all-nodes-0-0/is_active manually, Stack trace (when copying this message, always include the lines below):

>the second error problem 

{} <Error> default.tableName: auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 111, e.displayText() = Connection refused, Stack trace (when copying this message, always include the lines below):
 0. Poco::Net::ConnectionRefusedException::ConnectionRefusedException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xaa925c9 in /usr/bin/clickhouse
 2. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xaaa5dc4 in /usr/bin/clickhouse
 3. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) @ 0xaaa622b in /usr/bin/clickhouse
 4. Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) @ 0xaa7abb6 in /usr/bin/clickhouse
 5. Poco::Net::HTTPClientSession::reconnect() @ 0xaa6a0b5 in /usr/bin/clickhouse
 6. Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) @ 0xaa68bd5 in /usr/bin/clickhouse
 7. ? @ 0x7d4ca6d in /usr/bin/clickhouse
 8. DB::DataPartsExchange::Fetcher::fetchPart(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x7d44a91 in /usr/bin/clickhouse
 9. ? @ 0x7ceb546 in /usr/bin/clickhouse
 10. DB::StorageReplicatedMergeTree::fetchPart(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, std::__1::shared_ptr<zkutil::ZooKeeper>) @ 0x7c91ddc in /usr/bin/clickhouse
 11. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&) @ 0x7c8c79a in /usr/bin/clickhouse
 12. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x7c78a81 in /usr/bin/clickhouse
 13. ? @ 0x7ce883c in /usr/bin/clickhouse
 14. DB::ReplicatedMergeTreeQueue::processEntry(std::__1::function<std::__1::shared_ptr<zkutil::ZooKeeper> ()>, std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::__1::function<bool (std::__1::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x7ef4005 in /usr/bin/clickhouse
 15. DB::StorageReplicatedMergeTree::processQueueEntry(std::__1::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x7ca1a2a in /usr/bin/clickhouse
 16. ? @ 0x7ce93c5 in /usr/bin/clickhouse
 17. ? @ 0x7d40a2d in /usr/bin/clickhouse
 18. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x16fe10d in /usr/bin/clickhouse
 19. ? @ 0x17002b8 in /usr/bin/clickhouse
 20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x16fb06d in /usr/bin/clickhouse
 21. ? @ 0x16ff0d3 in /usr/bin/clickhouse
 22. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
 23. __clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

I don't know how to solve these problems
How can I fix it????

**Comment by alexey-milovidov** [comment]
> radondb/clickhouse-server:21.1.3.32

I don't know what is `radondb`, but it is definitely not the official ClickHouse version.
Also keep in mind, that version 21.1 is outdated. The recent version is 23.1.
