### ISSUE TITLE
how to install clickhouse-odbc-bridge

### ISSUE THREAD

**Issue by linqingping** [ClickHouse/ClickHouse#45769]
![image](https://user-images.githubusercontent.com/20528139/215434071-64f1e1cb-79f3-47ca-9339-f638a46ef754.png)
clickhouse version 22.7.1.3. 
can't find clickhouse-odbc-bridge.how to install it?

**Comment by linqingping** [comment]
> How did you install clickhouse?
use doinst.sh

**Comment by alexey-milovidov** [comment]
You can extract it from the tgz archive: 

https://clickhouse.com/docs/en/install/#from-tgz-archives

```
$ tar -xzvf "clickhouse-common-static-$LATEST_VERSION-${ARCH}.tgz" \
  || tar -xzvf "clickhouse-common-static-$LATEST_VERSION.tgz"
clickhouse-common-static-23.1.3.5/
clickhouse-common-static-23.1.3.5/usr/
clickhouse-common-static-23.1.3.5/usr/share/
clickhouse-common-static-23.1.3.5/usr/share/doc/
clickhouse-common-static-23.1.3.5/usr/share/doc/clickhouse-common-static/
clickhouse-common-static-23.1.3.5/usr/share/doc/clickhouse-common-static/CHANGELOG.md
clickhouse-common-static-23.1.3.5/usr/share/doc/clickhouse-common-static/README.md
clickhouse-common-static-23.1.3.5/usr/share/doc/clickhouse-common-static/LICENSE
clickhouse-common-static-23.1.3.5/usr/share/doc/clickhouse-common-static/AUTHORS
clickhouse-common-static-23.1.3.5/usr/share/bash-completion/
clickhouse-common-static-23.1.3.5/usr/share/bash-completion/completions/
clickhouse-common-static-23.1.3.5/usr/share/bash-completion/completions/clickhouse-client
clickhouse-common-static-23.1.3.5/usr/share/bash-completion/completions/clickhouse
clickhouse-common-static-23.1.3.5/usr/share/bash-completion/completions/clickhouse-bootstrap
clickhouse-common-static-23.1.3.5/usr/share/bash-completion/completions/clickhouse-local
clickhouse-common-static-23.1.3.5/usr/share/bash-completion/completions/clickhouse-benchmark
clickhouse-common-static-23.1.3.5/usr/bin/
clickhouse-common-static-23.1.3.5/usr/bin/clickhouse
clickhouse-common-static-23.1.3.5/usr/bin/clickhouse-extract-from-config
clickhouse-common-static-23.1.3.5/usr/bin/clickhouse-diagnostics
clickhouse-common-static-23.1.3.5/usr/bin/clickhouse-odbc-bridge                         <--- here it is
clickhouse-common-static-23.1.3.5/usr/bin/clickhouse-library-bridge
clickhouse-common-static-23.1.3.5/install/
clickhouse-common-static-23.1.3.5/install/doinst.sh
```

**Comment by nazfoxway** [comment]
@alexey-milovidov any reason why usr/bin/clickhouse-odbc-bridge  does not exist in latest versions? for example 24.4.1.2088 in https://packages.clickhouse.com/tgz/stable/clickhouse-common-static-24.4.1.2088-arm64.tgz

**Comment by alexey-milovidov** [comment]
@nazfoxway, it was moved to its own package, named `clickhouse-odbc-bridge`

**Comment by nazfoxway** [comment]
@alexey-milovidov  maybe you can share some links where to get it? I cant find it in documentation or tgz-archives. When installing via docker it does not come with clickhouse-odbc-bridge, so i guess it should be installed externally.

**Comment by alexey-milovidov** [comment]
Something like `apt-get install clickhouse-odbc-bridge`, from here: https://packages.clickhouse.com/deb/pool/main/c/clickhouse/

**Comment by MclellandG** [comment]
I'd suggest adding some information to the [docs page](https://clickhouse.com/docs/en/operations/utilities/odbc-bridge) as there is no indication that this requires a separate install - especially considering that it used to be bundled in the docker image.
