### ISSUE TITLE
JSONEachRow converts integer to string

### ISSUE THREAD

**Issue by MahmoudElhalwany** [ClickHouse/ClickHouse#45761]
i have a table that has id as Int64 and total as float when I query this table with Format JSONEachRow it return id as string but the total as numeric 

`Create table test(id Int64, total Float64) engine=Mergetree order by tuple()`

`select id, total from test Format JSONEachRow`

the result 

`{"id":"1", "total":50}`

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/settings/formats/#output_format_json_quote_64bit_integers

```
--output_format_json_quote_64bit_integers arg                                        Controls quoting of 64-bit integers in JSON output format.



select 1::UInt64 res format JSONEachRow;
```
