### ISSUE TITLE
Is there any way to optimize the speed of the first query?

### ISSUE THREAD

**Issue by tongle1** [ClickHouse/ClickHouse#45767]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
The first query of a table is much slower than the second query, regardless of whether the conditions of the two queries are consistent. Is there any way to optimize the speed of the first query?
first query
![image](https://user-images.githubusercontent.com/28292983/215418357-dc5c1409-ca35-488b-9adc-c29bd9f208d9.png)
second query
![image](https://user-images.githubusercontent.com/28292983/215418431-3b242f03-95fc-4f04-8e66-d70aa282caf9.png)
SQL : select * from table where column1=xxx order by column2

**Comment by den-crane** [comment]
can you share `ProfileEvents` from `system.query_log` ?

like this but for your slow query?

```
select avg(number) from numbers(1e10);
Query id: 38328310-9fb7-492c-89e0-ffa3ddef9262

SELECT
    n,
    v
FROM system.query_log
ARRAY JOIN
    `ProfileEvents.Names` AS n,
    `ProfileEvents.Values` AS v
WHERE (event_date = today()) AND (initial_query_id = '38328310-9fb7-492c-89e0-ffa3ddef9262') AND (type = 2)
┌─n─────────────────────────────────┬───────────v─┐
│ Query                             │           1 │
│ SelectQuery                       │           1 │
│ ArenaAllocChunks                  │           1 │
│ ArenaAllocBytes                   │        4096 │
│ TableFunctionExecute              │           1 │
│ NetworkReceiveElapsedMicroseconds │         262 │
│ NetworkSendElapsedMicroseconds    │        6254 │
│ NetworkSendBytes                  │       77111 │
│ SelectedRows                      │ 10000054965 │
│ SelectedBytes                     │ 80000439720 │
│ ContextLock                       │          16 │
│ RWLockAcquiredReadLocks           │           1 │
│ RealTimeMicroseconds              │    34744048 │
│ UserTimeMicroseconds              │     5877472 │
│ SystemTimeMicroseconds            │        5909 │
│ SoftPageFaults                    │         318 │
│ OSCPUWaitMicroseconds             │         787 │
│ OSCPUVirtualTimeMicroseconds      │     5883139 │
│ OSWriteChars                      │        6144 │
│ QueryProfilerRuns                 │          40 │
└───────────────────────────────────┴─────────────┘
```

**Comment by tongle1** [comment]
Hello,Thank you very much for your reply.The first query log is here:
![image](https://user-images.githubusercontent.com/28292983/215653519-aac213c8-5db7-41a3-96c8-0b41df2c2de2.png)
and the second query log is here:
![image](https://user-images.githubusercontent.com/28292983/215653589-5430a32a-f337-41a4-8253-1074e5c161db.png)

**Comment by tongle1** [comment]
> can you share `ProfileEvents` from `system.query_log` ?
> 
> like this but for your slow query?
> 
> ```
> select avg(number) from numbers(1e10);
> 
> Query id: 38328310-9fb7-492c-89e0-ffa3ddef9262
> 
> 
> 
> SELECT
>     n,
>     v
> FROM system.query_log
> ARRAY JOIN
>     `ProfileEvents.Names` AS n,
>     `ProfileEvents.Values` AS v
> WHERE (event_date = today()) AND 
>   (initial_query_id = '38328310-9fb7-492c-89e0-ffa3ddef9262') AND (type = 2)
> ┌─n─────────────────────────────────┬───────────v─┐
> │ Query                             │           1 │
> │ SelectQuery                       │           1 │
> │ ArenaAllocChunks                  │           1 │
> │ ArenaAllocBytes                   │        4096 │
> │ TableFunctionExecute              │           1 │
> │ NetworkReceiveElapsedMicroseconds │         262 │
> │ NetworkSendElapsedMicroseconds    │        6254 │
> │ NetworkSendBytes                  │       77111 │
> │ SelectedRows                      │ 10000054965 │
> │ SelectedBytes                     │ 80000439720 │
> │ ContextLock                       │          16 │
> │ RWLockAcquiredReadLocks           │           1 │
> │ RealTimeMicroseconds              │    34744048 │
> │ UserTimeMicroseconds              │     5877472 │
> │ SystemTimeMicroseconds            │        5909 │
> │ SoftPageFaults                    │         318 │
> │ OSCPUWaitMicroseconds             │         787 │
> │ OSCPUVirtualTimeMicroseconds      │     5883139 │
> │ OSWriteChars                      │        6144 │
> │ QueryProfilerRuns                 │          40 │
> └───────────────────────────────────┴─────────────┘
> ```



> can you share `ProfileEvents` from `system.query_log` ?
> 
> like this but for your slow query?
> 
> ```
> select avg(number) from numbers(1e10);
> 
> Query id: 38328310-9fb7-492c-89e0-ffa3ddef9262
> 
> 
> 
> SELECT
>     n,
>     v
> FROM system.query_log
> ARRAY JOIN
>     `ProfileEvents.Names` AS n,
>     `ProfileEvents.Values` AS v
> WHERE (event_date = today()) AND 
>   (initial_query_id = '38328310-9fb7-492c-89e0-ffa3ddef9262') AND (type = 2)
> ┌─n─────────────────────────────────┬───────────v─┐
> │ Query                             │           1 │
> │ SelectQuery                       │           1 │
> │ ArenaAllocChunks                  │           1 │
> │ ArenaAllocBytes                   │        4096 │
> │ TableFunctionExecute              │           1 │
> │ NetworkReceiveElapsedMicroseconds │         262 │
> │ NetworkSendElapsedMicroseconds    │        6254 │
> │ NetworkSendBytes                  │       77111 │
> │ SelectedRows                      │ 10000054965 │
> │ SelectedBytes                     │ 80000439720 │
> │ ContextLock                       │          16 │
> │ RWLockAcquiredReadLocks           │           1 │
> │ RealTimeMicroseconds              │    34744048 │
> │ UserTimeMicroseconds              │     5877472 │
> │ SystemTimeMicroseconds            │        5909 │
> │ SoftPageFaults                    │         318 │
> │ OSCPUWaitMicroseconds             │         787 │
> │ OSCPUVirtualTimeMicroseconds      │     5883139 │
> │ OSWriteChars                      │        6144 │
> │ QueryProfilerRuns                 │          40 │
> └───────────────────────────────────┴─────────────┘
> ```

Hello,Thank you very much for your reply.The first query log is here:
![image](https://user-images.githubusercontent.com/28292983/215653519-aac213c8-5db7-41a3-96c8-0b41df2c2de2.png)
SELECT
                    n,
                    v
                FROM system.query_log
                ARRAY JOIN
                    `ProfileEvents.Names` AS n,
                    `ProfileEvents.Values` AS v
                WHERE (event_date = today()) AND 
                  (initial_query_id = 'c73aa547-e6ac-4813-a51f-cb481d39c700') AND (type = 2)

SELECT
    n,
    v
FROM system.query_log
ARRAY JOIN
    `ProfileEvents.Names` AS n,
    `ProfileEvents.Values` AS v
WHERE (event_date = today()) AND (initial_query_id = 'c73aa547-e6ac-4813-a51f-cb481d39c700') AND (type = 2)

Query id: d700d913-555d-40ca-b98d-88a469ce32b6

┌─n────────────────────────────────────────────────┬──────────v─┐
│ Query                                            │          1 │
│ SelectQuery                                      │          1 │
│ FileOpen                                         │       3880 │
│ ReadBufferFromFileDescriptorReadBytes            │ 7541718101 │
│ ReadCompressedBytes                              │ 7261820732 │
│ CompressedReadBufferBlocks                       │     116435 │
│ CompressedReadBufferBytes                        │ 7648497966 │
│ OpenedFileCacheHits                              │        556 │
│ OpenedFileCacheMisses                            │       3880 │
│ IOBufferAllocs                                   │       6727 │
│ IOBufferAllocBytes                               │  855989280 │
│ FunctionExecute                                  │      19341 │
│ MarkCacheHits                                    │        176 │
│ MarkCacheMisses                                  │       1616 │
│ CreatedReadBufferOrdinary                        │       4436 │
│ DiskReadElapsedMicroseconds                      │   24540558 │
│ NetworkReceiveElapsedMicroseconds                │        122 │
│ NetworkSendElapsedMicroseconds                   │       1955 │
│ NetworkSendBytes                                 │     547409 │
│ SelectedParts                                    │        335 │
│ SelectedRanges                                   │       4514 │
│ SelectedMarks                                    │      18508 │
│ SelectedRows                                     │  151507128 │
│ SelectedBytes                                    │  757537902 │
│ ContextLock                                      │        202 │
│ RWLockAcquiredReadLocks                          │          4 │
│ RealTimeMicroseconds                             │  210228065 │
│ UserTimeMicroseconds                             │    7077939 │
│ SystemTimeMicroseconds                           │    1320050 │
│ SoftPageFaults                                   │      79312 │
│ OSIOWaitMicroseconds                             │   18537156 │
│ OSCPUWaitMicroseconds                            │      57044 │
│ OSCPUVirtualTimeMicroseconds                     │    8413940 │
│ OSReadBytes                                      │  467738624 │
│ OSWriteBytes                                     │       8192 │
│ OSReadChars                                      │ 7541719040 │
│ OSWriteChars                                     │      62464 │
│ QueryProfilerRuns                                │        184 │
│ ThreadPoolReaderPageCacheMiss                    │      18452 │
│ ThreadPoolReaderPageCacheMissBytes               │ 7541718101 │
│ ThreadPoolReaderPageCacheMissElapsedMicroseconds │   24540558 │
└──────────────────────────────────────────────────┴────────────┘

41 rows in set. Elapsed: 0.012 sec. Processed 4.74 thousand rows, 1.97 MB (387.42 thousand rows/s., 161.47 MB/s.)

and the second query log is here:
![image](https://user-images.githubusercontent.com/28292983/215653589-5430a32a-f337-41a4-8253-1074e5c161db.png)
 SELECT
                    n,
                    v
                FROM system.query_log
                ARRAY JOIN
                    `ProfileEvents.Names` AS n,
                    `ProfileEvents.Values` AS v
                WHERE (event_date = today()) AND 
                  (initial_query_id = 'd55c625e-2961-4f4b-9254-e2f8944fcaa1') AND (type = 2)

SELECT
    n,
    v
FROM system.query_log
ARRAY JOIN
    `ProfileEvents.Names` AS n,
    `ProfileEvents.Values` AS v
WHERE (event_date = today()) AND (initial_query_id = 'd55c625e-2961-4f4b-9254-e2f8944fcaa1') AND (type = 2)

Query id: a90faf50-9ff0-40ff-9310-5979939a37b7

┌─n────────────────────────────────────────────────┬──────────v─┐
│ Query                                            │          1 │
│ SelectQuery                                      │          1 │
│ FileOpen                                         │       3906 │
│ ReadBufferFromFileDescriptorReadBytes            │ 7444459946 │
│ ReadCompressedBytes                              │ 7191376781 │
│ CompressedReadBufferBlocks                       │     114242 │
│ CompressedReadBufferBytes                        │ 7551976669 │
│ OpenedFileCacheHits                              │        408 │
│ OpenedFileCacheMisses                            │       3906 │
│ IOBufferAllocs                                   │       6506 │
│ IOBufferAllocBytes                               │  781277029 │
│ FunctionExecute                                  │      19158 │
│ MarkCacheHits                                    │        106 │
│ MarkCacheMisses                                  │       1572 │
│ CreatedReadBufferOrdinary                        │       4314 │
│ DiskReadElapsedMicroseconds                      │  115407732 │
│ NetworkReceiveElapsedMicroseconds                │        216 │
│ NetworkSendElapsedMicroseconds                   │       2877 │
│ NetworkSendBytes                                 │     735683 │
│ SelectedParts                                    │        354 │
│ SelectedRanges                                   │       4511 │
│ SelectedMarks                                    │      18404 │
│ SelectedRows                                     │  150647145 │
│ SelectedBytes                                    │  753237987 │
│ ContextLock                                      │        202 │
│ RWLockAcquiredReadLocks                          │          4 │
│ RealTimeMicroseconds                             │  863787848 │
│ UserTimeMicroseconds                             │    5970674 │
│ SystemTimeMicroseconds                           │    2161911 │
│ SoftPageFaults                                   │      72331 │
│ OSIOWaitMicroseconds                             │  110344232 │
│ OSCPUWaitMicroseconds                            │      65151 │
│ OSCPUVirtualTimeMicroseconds                     │    8137364 │
│ OSReadBytes                                      │ 3673133056 │
│ OSWriteBytes                                     │       8192 │
│ OSReadChars                                      │ 7444458496 │
│ OSWriteChars                                     │     173056 │
│ QueryProfilerRuns                                │        763 │
│ ThreadPoolReaderPageCacheMiss                    │      18392 │
│ ThreadPoolReaderPageCacheMissBytes               │ 7444459946 │
│ ThreadPoolReaderPageCacheMissElapsedMicroseconds │  115407732 │
└──────────────────────────────────────────────────┴────────────┘

41 rows in set. Elapsed: 0.012 sec. Processed 4.74 thousand rows, 1.98 MB (390.37 thousand rows/s., 162.75 MB/s.)

**Comment by den-crane** [comment]
metric | q1 | q2 | q2/q1
-- | -- | -- | --
OSReadBytes | 467,738,624 | 3,673,133,056 | 7.85
OSIOWaitMicroseconds | 18,537,156 | 110,344,232 | 5.95
DiskReadElapsedMicroseconds | 24,540,558 | 115,407,732 | 4.70
ThreadPoolReaderPageCacheMissElapsedMicroseconds | 24,540,558 | 115,407,732 | 4.70
QueryProfilerRuns | 184 | 763 | 4.15
RealTimeMicroseconds | 210,228,065 | 863,787,848 | 4.11
OSWriteChars | 62,464 | 173,056 | 2.77

Q2 reads from the disk into Linux page cache **7.85 times more** data than Q1. The fast query uses cached data.
