### ISSUE TITLE
Illegal type IPv6 of argument of function notEmpty

### ISSUE THREAD

**Issue by kaworu** [ClickHouse/ClickHouse#45773]
**Describe what's wrong**

`notEmpty` does not accept an argument of type IPv6:
```
DB::Exception: Illegal type IPv6 of argument of function notEmpty
```

**Does it reproduce on recent release?**

Yes, starting ClickHouse v23.

Expected behavior with v22.12.3.5: https://fiddle.clickhouse.com/5abe165f-6c96-4b4f-b59e-2c7327a1b252
`DB::Exception` starting with v23.1.1.3077: https://fiddle.clickhouse.com/b619dd22-343c-41cd-8359-da2a6dd76360

**How to reproduce**

* Which ClickHouse server version to use: v23
* Queries to run that lead to unexpected result: `SELECT notEmpty(toIPv6('::1'))`

**Expected behavior**

The same behavior as ClickHouse before v23: `notEmpty` should evaluate to `0` when given the all-zeroes IPv6 address (i.e. `notEmpty(toIPv6('::'))`), and `1` otherwise.

**Comment by tavplubix** [comment]
Related to https://github.com/ClickHouse/ClickHouse/pull/43221
@yakov-olkhovskiy please take a look

**Comment by yakov-olkhovskiy** [comment]
The previous behavior was an unwanted side-effect of domain type - please notice, that IPv4 was always incompatible for this function. I would suggest that current behavior is correct and we keep it this way unless we already have user case(s) where this issue is critical.
cc @KochetovNicolai
