### ISSUE TITLE
LXD 5.0.2 and Clickhouse client

### ISSUE THREAD

**Issue by deemon87** [ClickHouse/ClickHouse#45770]
I have a ch client inside lxd containers.
CH version `23.1.1.3077`

Recently lxd upgraded from 5.0.1 to 5.0.2.
After the upgrade, I began to get a message from the client ch:
`<jemalloc>: Number of CPUs detected is not deterministic. Per-CPU arena disabled.`

After upgrade i also have some problem with get correct count of cpu from node_exporter, but this workaround resolved the problem: https://github.com/lxc/lxcfs/issues/581#issuecomment-1387264945

How can i resolve problem with clickhouse client? maybe someone can help?

Also my issue in LXD repo: https://github.com/lxc/lxcfs/issues/585#issue-1560037206

**Comment by alexey-milovidov** [comment]
This message is a warning. 

clickhouse-client detects the wrong information about the number of CPUs and will continue to work nevertheless.
