### ISSUE TITLE
Conversion from UInt64 to IPv4 is not supported

### ISSUE THREAD

**Issue by kolya7k** [ClickHouse/ClickHouse#45797]
New IPv4 as native code causes inserting IPv4 as UInt32 broken with error "Conversion from UInt64 to IPv4 is not supported";

CREATE TABLE users (ip IPv4) ENGINE=Memory;
INSERT INTO users VALUES (2319771222);
DB::Exception: Conversion from UInt64 to IPv4 is not supported:

**Comment by tavplubix** [comment]
Related to https://github.com/ClickHouse/ClickHouse/pull/43221
