### ISSUE TITLE
JOIN ON Parsing changes in 23.* leading to incorrect query rejection

### ISSUE THREAD

**Issue by phantom943** [ClickHouse/ClickHouse#45792]
Clickhouse incorrectly identifies equality condition in JOIN ON

```sql
with d1 as (
    select
        1 as user_id,
        2 as val
),
d2 as (
    select
        1 as user_id,
        5 as val_2
)
select *
from
    d1
inner join d2 
	on (
		1=1 
		and d1.user_id = d2.user_id
	)
```
This correctly works returning 1 row in ClickHouse 22.11.1.1360, but incorrectly fails in both 23.1.1.3077 and 23.2.1.261 (head) with exception 

```bash
SQL Error [352] [07000]: Code: 352. DB::Exception: Ambiguous columns in expression '1 = 1' in JOIN ON section: While processing 1 = 1. (AMBIGUOUS_COLUMN_NAME) (version 23.1.1.3077 (official build))¶, server ClickHouseNode [uri=http://clickhouse.analytic.dev.backe.io:32123/dbt_dd_src, options={use_server_time_zone=false,profile=dbt_web,use_time_zone=false}]
```

See [REPL](https://fiddle.clickhouse.com/a3d26baf-7c37-4947-9dbc-e05f1ef8e6f9)

**Comment by tavplubix** [comment]
Queries like this were intentionally forbidden in https://github.com/ClickHouse/ClickHouse/pull/44016. Maybe we should change the changelog category to "backward incompatible change" and update the changelog.

cc: @vdimir

**Comment by vdimir** [comment]
Changelog update PR https://github.com/ClickHouse/ClickHouse/pull/45820
