### ISSUE TITLE
Cannot specity table structure for table function `format`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#45808]
https://clickhouse.com/docs/en/sql-reference/table-functions/format/

**Use case**

```
SELECT * FROM format(TSV, 'cust_id UInt128', '20210129005809043707')
```

**How to solve**

Allow a three-argument version.

**Comment by FFFFFFFHHHHHHH** [comment]
Hi, I’d like to have a try :)
