### ISSUE TITLE
Spill to disk setting for large JOINs

### ISSUE THREAD

**Issue by marklit** [ClickHouse/ClickHouse#45814]
I have six tables that I want to join together. They have row counts between 70-100M records each. The following wasn't able to run on anything less than a system with 512 GB of RAM.

```sql
CREATE TABLE out ENGINE=Log AS
    SELECT a.h3_value as h3,
           7 AS h3_level,
           b.col1 as b_col,
           c.col1 AS c_col,
           e.col1 as census_2010,
           CONCAT(f.col1,
                  f.col2,
                  f.col3,
                  f.col4) as f_cols,
           IF(LENGTH(d.h3_value) > 5, True, False) as has_element
    FROM table_a a
    LEFT JOIN table_b b ON b.h3_7 = a.h3_value
    LEFT JOIN table_c c ON c.h3_7 = a.h3_value
    LEFT JOIN table_d d ON d.h3_value = a.h3_value
    LEFT JOIN table_e e ON e.h3_7 = a.h3_value
    LEFT JOIN table_f f ON f.h3_7 = a.h3_value;
```

I built a SQL generator that turned the above into 39 SQL statements and it was able to run on a system with 64 GB of RAM.

I know there are settings I can add to some queries to force them to spill to disk so they run on RAM-constrained systems, `SETTINGS max_bytes_before_external_sort=687091200` for example can be used with large `ORDER BY` statements. I've dug through the docs and looked at your [test cases](https://github.com/ClickHouse/ClickHouse/search?l=SQL&p=1&q=join+settings) but I can't see any such setting for the above `CREATE TABLE` statement.

I came across mentions of `SETTINGS join_algorithm = 'parallel_merge'` in other tickets but this doesn't look to be supported any longer.

```
Unexpected value of JoinAlgorithm: 'parallel_merge'. Must be one of ['direct', 'grace_hash', 'parallel_hash', 'prefer_partial_merge', 'hash', 'partial_merge', 'full_sorting_merge', 'auto', 'default']. (UNKNOWN_JOIN)
```

Both `parallel_hash` and `auto` exhausted my system's RAM in seconds.

Is there a setting I can give in the SQL query that will allow the above single `CREATE TABLE` statement to run on a RAM-constrained system (e.g. one with 64 GB of RAM rather than 512 GB)?

**Comment by UnamedRus** [comment]
You can check grace_hash https://github.com/ClickHouse/ClickHouse/pull/38191

**Comment by den-crane** [comment]
anyway JOIN improvements are in the roadmap https://github.com/ClickHouse/ClickHouse/issues/44767

**Comment by Aaaaaaron** [comment]
@den-crane den hello,  Do we have performance test data about grace has join?
