### ISSUE TITLE
Error too many parts

### ISSUE THREAD

**Issue by MarcShi001** [ClickHouse/ClickHouse#45812]
I want to insert data from zip file to clickhouse by bash script:

for xxx; do
  xxx xxx.zip xxx | clickhouse-client --input_format_csv_empty_as_default 1 -h $CH_HOST -u $CH_USER --password $CH_PASSWORD -- 
query="INSERT INTO table_demo FORMAT CSV"
done

The data is partition by date . Finally, I got a error too many parts(more than 100000). I check the parts by sql:
select partition, count(1) as part_count from system.parts where database = 'xxx' and table = 'table_demo' group by partition order by partition desc;
![image](https://user-images.githubusercontent.com/101505917/215684495-983c2bd4-95a6-405c-9527-b575b52c437b.png)

Many partitions have a lot of parts which haven`t been merged automatic.  But befor 20211105,  every partition only has 2 parts.
Under what  circumstances the parts of one partition will be merged automatic? 
Is there any idea to solve too may parts error? I have try to use buffer table engine, but I still got the too many parts error.

**Comment by MarcShi001** [comment]
Thanks for your reply. 
I have fixed the problem by modifing the 'parts_to_delay_insert ' value.
As you mentioned, insert data day by day is pretty good idea. In my case, the data from zip files was not organized by day. So I  didn`t insert data by day.
Thanks for your suggestion again.

**Comment by DerekChia** [comment]
The error is triggered because the number active parts in all partitions in total exceed 100000. Try changing your partition to month instead.

**Comment by MarcShi001** [comment]
yes. I use year_month instead of  year_month_day as partition. It works well. Thanks.

**Comment by yedelong** [comment]
> The error is triggered because the number active parts in all partitions in total exceed 100000. See `max_parts_in_total` under system.merge_tree_settings. Solution - try changing your partition to month instead.

Can we set the parameter 'max' to_ Parts_ In_ To solve the problem, I used 'ReplicatedReplacingMergetree' to increase the total size
