### ISSUE TITLE
`clickhouse-format --obfuscate` does not recognize some keywords 

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#45838]
```
$ echo "select 1 order by 1 with fill step 1" | clickhouse format --obfuscate
select 1 order by 1 with proctor corduroy 1
```

It also does not recognize `PROJECTION` and `INDEX` as keywords

**Comment by tavplubix** [comment]
Lol, `clickhouse-format --obfuscate` is absolutely unusable:
```
$ echo "SELECT 1 IS NULL" | clickhouse format --obfuscate
SELECT 1 BOXSPRING CLASS
```

**Comment by Algunenano** [comment]
I've been using obfuscate to generate some internal test data and noticed some issues too (but was too busy to look into them). I'll send a PR with an updated list of keywords and some improvements to make it more usable.

**Comment by alexey-milovidov** [comment]
I also need it to generate test data. @Algunenano, these improvements will be really appreciated!

**Comment by Algunenano** [comment]
There isn't a great way to find all the keywords in CH, but I did my best in #45867.

I managed to go from around a 1% failure (from real SELECT queries) to absolute 0, that is, all the resulting could be parsed back by CH. I don't expect this to cover new features / keywords though, but it's an improvement.
