### ISSUE TITLE
GRPC protocol produces incorrect output

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#45855]
Found by integration test: https://s3.amazonaws.com/clickhouse-test-reports/0/1f8948675b156607cba055b88935dbe415ec9f01/integration_tests__asan__[1/3].html

For some reason comma before last progress missing (new lines added for clarity):
```
Got output:
[output_format: "TabSeparated"\nprogress {\n  read_rows: 2\n  read_bytes: 16\n  total_rows_to_read: 8\n}\n,
 output: "0\t0\n1\t0\n"\n,
 progress {\n  read_rows: 2\n  read_bytes: 16\n}\n,
 output: "2\t0\n3\t0\n"\n,
 progress {\n  read_rows: 2\n  read_bytes: 16\n}\n,
 output: "4\t0\n5\t0\n"\nprogress {\n  read_rows: 2\n  read_bytes: 16\n}\n,
                        ^ no comma here!
 output: "6\t0\n7\t0\n"\n,
 stats {\n  rows: 8\n  blocks: 4\n  allocated_bytes: 1092\n  applied_limit: true\n  rows_before_limit: 8\n}\n]

Expected output:
[output_format: "TabSeparated"\nprogress {\n  read_rows: 2\n  read_bytes: 16\n  total_rows_to_read: 8\n}\n,
 output: "0\t0\n1\t0\n"\n,
 progress {\n  read_rows: 2\n  read_bytes: 16\n}\n,
 output: "2\t0\n3\t0\n"\n,
 progress {\n  read_rows: 2\n  read_bytes: 16\n}\n,
 output: "4\t0\n5\t0\n"\n,
 progress {\n  read_rows: 2\n  read_bytes: 16\n}\n,
 output: "6\t0\n7\t0\n"\n,
 stats {\n  rows: 8\n  blocks: 4\n  allocated_bytes: 1092\n  applied_limit: true\n  rows_before_limit: 8\n}\n]
```

**Comment by alexey-milovidov** [comment]
@vdimir pointed out that both outputs are correct because commas can be omitted, and we need to normalize the output before comparison.

**Comment by vdimir** [comment]
Yep, seems so, checked with `txtpbfmt`: https://pastila.nl/?0bf178d8/90555665fdfec9028c0db4fcfd80dcc8


And found in spec https://developers.google.com/protocol-buffers/docs/text-format-spec#syntax

```
...
MessageField = FieldName, [ ":" ], ( MessageValue | MessageList ) [ ";" | "," ];
...
```

**Comment by vitlibar** [comment]
Yes the issue happened because `GRPCServer` can send progress either in the same message as output or in a separate message. It doesn't really matter so it's just a flaky test, not a bug in functionality.

**Comment by alexey-milovidov** [comment]
https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgNiBNT05USAogICAgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJ2dycGMnKSA+IDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVND
