### ISSUE TITLE
19.1.10 cannot drop database with engine=Dictionary if it is not empty

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#4586]
I haven't noticed this before. I could drop and create a database with engine=Dictionary as many times as I wanted. Now it only allows to drop this database when there are no dictionaries (the database is empty).
```
:) drop database dict

DROP DATABASE dict

Received exception from server (version 19.1.10):
Code: 48. DB::Exception: Received from localhost:9000, ::1. DB::Exception: DatabaseDictionary: removeTable() is not supported.

0 rows in set. Elapsed: 0.088 sec.
```
The definition of the database:
```
$ cat /var/lib/clickhouse/metadata/dict.sql
ATTACH DATABASE dict
ENGINE = Dictionary
```

**Comment by SaltTan** [comment]
It works on the latest build (19.3.4.15)

**Comment by SaltTan** [comment]
It stopped working on 19.3.4.15 as well.
I'll try to reproduce

**Comment by filimonov** [comment]
```Received exception from server (version 19.4.2):
Code: 48. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: DatabaseDictionary: removeTable() is not supported. 
```

**Comment by tishkinis** [comment]
Code: 48, e.displayText() = DB::Exception: DatabaseDictionary: removeTable() is not supported (version 19.9.2.4)

**Comment by alexey-milovidov** [comment]
Implementation proposal:
- create a property of IDatabase that can say that all tables in database are "ephemeral" and should not be removed (by `removeTable`) on database drop.

**Comment by alexey-milovidov** [comment]
@vitlibar has fixed it in https://github.com/ClickHouse/ClickHouse/pull/10234 exactly as it was proposed.
