### ISSUE TITLE
ArrayJoin always creating extra rows in conditional statements

### ISSUE THREAD

**Issue by Dark-Hobbit** [ClickHouse/ClickHouse#45861]
**Describe the unexpected behaviour**
Suppose you want to have a query with a "if" or "multiIf" statement where one of the values calls "arrayJoin". Specifically I want to have a value which, if encountered, is countered into several other ones. The problem is, it seems "arrayJoin" creates multiple rows even if the conditional statement never gets to it.

**How to reproduce**
* Which ClickHouse server version to use
22.8.11.15
* Queries to run that lead to unexpected result
```
select if(scale = 'target_value', arrayJoin(['result_1', 'result_2']), 'result_3') as result
from (select 'wrong_value' as scale)
```

**Expected behavior**
2 rows with "result_1" and "result_2" if the condition is fulfilled or 1 row with "result_3" otherwise (like when scale is "wrong_value").

**Error message and/or stacktrace**
No error message, but it creates 2 rows with "result_3" in each instead.

**Comment by den-crane** [comment]
it's too long to explain, but it's expected behaviour by design.

You should use `arrayJoin(if`

```sql
SELECT arrayJoin(if(scale = 'target_value', ['result_1', 'result_2'], ['result_3'])) AS result
FROM
(
    SELECT 'wrong_value' AS scale
)

┌─result───┐
│ result_3 │
└──────────┘
```

**Comment by Dark-Hobbit** [comment]
Thank you for the reply and the solution!

That does make sense, could not think about it at the time. Perhaps could be a useful case to add to the documentation?
