### ISSUE TITLE
Code: 102. Unexpected packet from server xx.xxx.xxx.xx:xxxx (expected Data, Exception, Log or TableColumns, got Progress)

### ISSUE THREAD

**Issue by AlbinDavid** [ClickHouse/ClickHouse#45881]
**Insert Query executing and raising an exception**

**Happening in the latest version of clickhouse (version 3)**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**

* Clickhouse version 3 
* python native script to insert a row 

**Expected behavior**

**Code: 102. Unexpected packet from server xx:xx:xxx:xx:xxxx (expected Data, Exception, Log or TableColumns, got Progress)**

**Comment by tavplubix** [comment]
> Happening in the latest version of clickhouse (version 3)

There's no version 3.

Also no information abut the error was provided (when it's happening? how to reproduce it?). Please follow [the template](https://github.com/ClickHouse/ClickHouse/blob/master/.github/ISSUE_TEMPLATE/85_bug-report.md) next time and provide as much diagnostic info as possible.
