### ISSUE TITLE
[MaterializedPostgreSQL] Possibly conflicting publications when using more CHDBs with one PG

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#45891]
I have inspected publications in my PG that were created after running

```sql
CREATE DATABASE dbname ENGINE = MaterializedPostgreSQL
```

```sql
select * from pg_publication;
```

The publication with name `dbname_ch_publication` was created.

------------

Now consider a ClickHouse instance `A`

```sql
CREATE DATABASE dbname ENGINE = MaterializedPostgreSQL(...)
        SETTINGS
            materialized_postgresql_tables_list = 'table_a';
```

Publication `dbname_ch_publication` is created and using `select * from pg_publication_tables;` we can see `table_a` listed there.

-------------

Now consider a ClickHouse instance `B`

```sql
CREATE DATABASE dbname ENGINE = MaterializedPostgreSQL(...)
        SETTINGS
            materialized_postgresql_tables_list = 'table_b';
```

Publication `dbname_ch_publication` is created and using `select * from pg_publication_tables;` we can see `table_b` listed there.

My point is that `table_a` got removed from the publication that was created by clickhouse `A`.

**Comment by kssenii** [comment]
This was fixed in https://github.com/ClickHouse/ClickHouse/pull/55145.
You need to create a database with setting `materialized_postgresql_use_unique_replication_consumer_identifier=1`.
