### ISSUE TITLE
About field default value

### ISSUE THREAD

**Issue by sdk2** [ClickHouse/ClickHouse#4589]
Hello, I try to create a table with field default value and insert data to it, but I get an error.

create sql:
CREATE TABLE lq_test_db.default_value_insert_failed_test 
( timestamp UInt64, datetime DateTime DEFAULT toDateTime(timestamp / 1000)) 
ENGINE = MergeTree 
PARTITION BY toDate(timestamp / 1000) 
ORDER BY timestamp 
SETTINGS index_granularity = 8192;

insert sql:
insert into lq_test_db.default_value_insert_failed_test 
(timestamp, datetime) 
values 
(1551772800000, null);

error:
Code: 321. DB::Exception: Expression returns value NULL, that is out of range of type DateTime, at: null);

version:
ClickHouse client version 18.14.13.

Thanks.

**Comment by filimonov** [comment]
> Default values are evaluated only for columns, that are not listed in INSERT query.

So to make it work you need to change insert like that:
```sql
insert into lq_test_db.default_value_insert_failed_test (timestamp) values (1551772800000);
```

See also #86

**Comment by sdk2** [comment]
I understand it but I want to use "batch insert".
There are large amount of data, like
`INSERT INTO xxx (name, age) VALUES (Mike, 22), (John, NULL), (Lucy, 17)...`
I want to set "age" field default value is 18, John’s age should be 18.
Should I write two insert sql?

**Comment by tavplubix** [comment]
Now it works with setting `input_format_null_as_default=1` (#7215)
