### ISSUE TITLE
Direct import from files inside tar/zip/7z archives

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#45939]
@nikitakeba, https://github.com/ClickHouse/ClickHouse/issues/42194

Reading from files located inside archives with multiple files.

There are multiple places where we support reading from external files:
- SELECT ... FROM, INSERT INTO file/url/s3/hdfs
- INSERT ... FROM INFILE

And we already support:
- transparent reading of compressed files: gz, xz, bz2, lz4, zstd;
- globs for reading from multiple files: file{1..100}, file*... and parallel processing of them.

Now imagine files are located inside an archive with multiple files - like tar, zip, 7z - and we want to process a subset of files from the archive.

Example:

```
SELECT * FROM url('https://example.com/myfile{01..10}.tar.gz :: path/hello{1..9}.tsv')
```

Implementation will require:
- reading the archives and extracting ReadBuffers (byte streams) for a subset of files; if an archive contains an index, perform seeks for reading files; if not - implement streaming reads of files in the order of how they are placed in the archive.

Note: ClickHouse codebase already has support for reading files from zip archives.

**Comment by alexey-milovidov** [comment]
Another idea is HTML archives:

```
SELECT * FROM url('https://example.com/index.html :: hello{1..9}.tsv')
```

will download the HTML and search for the links on the page to the files matching the globs.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/16681

**Comment by UnamedRus** [comment]
May be manifest file support will be more univeral or/and add ability to just pass resultset as url param to table functions?

https://github.com/ClickHouse/ClickHouse/issues/16682

**Comment by alexey-milovidov** [comment]
Wow, it's implemented!
