### ISSUE TITLE
Update role ,user does't effect

### ISSUE THREAD

**Issue by bigdata-spec** [ClickHouse/ClickHouse#45948]
Hi，
My Clickhouse  version  is **22.8.1.2097**，sometimes  update role ,user does't effect.

**CREATE ROLE role1  on cluster 'ch_cluster';
CREATE USER user1 DEFAULT ROLE role1 on cluster 'ch_cluster';
GRANT  SELECT ON ods.table1 TO role1  on cluster 'ch_cluster';**
user1 can select ods.table1

then add table2 
**GRANT  SELECT ON ods.table2 TO role1  on cluster 'ch_cluster';**
**ALTER USER user1 DEFAULT ROLE role1 on cluster 'ch_cluster';**
but user1 cannot  select ods.table2

if i run:
**REVOKE on cluster 'ch_cluster'  role1 from user1;
GRANT  role1 TO user1 on cluster 'ch_cluster';**
user1 can select both table1 and table2；

is this normal？We can run REVOKE?

 thank you very much.

**Comment by rkozlo** [comment]
The best would be to show `show grants for role1` and `show grants for user`

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/46772

**Comment by bobelev** [comment]
Still reproducible on `22.8.17.17`

```
clickhouse-01a :) show grants for `alert-exporter-production-clickhouse-acl`


┌─GRANTS FOR `alert-exporter-production-clickhouse-acl`─────────────────────────────────────┐
…
│ GRANT SHOW, SELECT, dictGet ON devops.* TO `alert-exporter-production-clickhouse-acl`     │
…
└───────────────────────────────────────────────────────────────────────────────────────────┘

clickhouse-01a :) show grants for svc_ch_alerter


┌─GRANTS FOR svc_ch_alerter─────────────────────────────────────────────────────────────────────────────────┐
│ GRANT `alert-exporter-production-clickhouse-acl`, `…` TO svc_ch_alerter │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────┘


clickhouse-01a :) select user()

┌─currentUser()──┐
│ svc_ch_alerter │
└────────────────┘

clickhouse-01a :) use devops

Received exception from server (version 22.8.17):
Code: 497. DB::Exception: Received from clickhouse-01a:9000. DB::Exception: svc_ch_alerter: Not enough privileges. To execute this query it's necessary to have grant SHOW DATABASES ON devops.*. (ACCESS_DENIED)
```
