### ISSUE TITLE
DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts

### ISSUE THREAD

**Issue by MtpXV** [ClickHouse/ClickHouse#45946]
Hello!

Right now we are in process of implementing clickhouse support for analytics. Before that we stored all the data in PostgreSQL. At first we stumble on `Too many parts` problem when we just started testing it. We tried to fix it by storing rows into the batches and adding a buffer table. For a day it solved the problem but it has started again. And we can't insert anything without getting the error right now.

We have continues stream of data which we would like to store in clcikhouse. Right now pipeline is:

1. We store rows PostgreSQL
2. A job which transfers data to clickhouse runs every 5 minutes. We transfer data in the loop where we get batches by 5k rows from PostgreSQL and send them in clickhouse. 
3. Buffer table is put before the table

Size of batches can be varied form 100 rows - 100000 rows. 

DDL for table 
```
        CREATE TABLE table (
            id Int256,
            type String,
            timestamp DateTime,
            is_reference Bool,
            parent_id Nullable(Int256),
            size Nullable(Int256),
            some_id UUID,
            some_other_id UUID,
            bool_field Nullable(Bool),
            name Nullable(String),
            notes Nullable(String),
            height Nullable(Int256),
            some_attr Nullable(Bool),
            some_attr Nullable(Bool),
            some_attr Nullable(Bool),
            some_attr Nullable(Bool),
            some_attr Nullable(String),
            some_attr Nullable(String),
            some_attr Nullable(String),
            some_attr Nullable(String),
            some_attr Nullable(String)
            ) ENGINE MergeTree
            PARTITION BY toYYYYMM(timestamp)
            PRIMARY KEY (type, timestamp)
            ORDER BY (type, timestamp, id)
```

DDL for buffer table
```
            CREATE TABLE buffer_table as table
            ENGINE = Buffer(db, table, 1, 10, 100, 10000, 1000000, 10000000, 100000000)
```

Search queries mainly use `type`, `timestamp` and several some_attr fields depending on the `type`. So separate `types` will have different `some_attr` fields filled while others will be null. There are 5  `types` of rows. We can't change the schema of table due legacy stuff.

Right now we are not sure what can be changed to solve the issue. Would really appreciate advice.

**Comment by DerekChia** [comment]
Check out Asynchronous Inserts (https://clickhouse.com/docs/en/optimize/asynchronous-inserts/). With this setting, ClickHouse will create the batches before inserting rows. 

Too many parts error is a common error, and you may find what we described in our blog post useful - https://clickhouse.com/blog/common-getting-started-issues-with-clickhouse

**Comment by MtpXV** [comment]
Thanks for your response, but we have tried all the points mentioned in the blog post.

**Comment by DerekChia** [comment]
> Thanks for your response, but we have tried all the points mentioned in the blog post.

Do you mean that you are still getting too many parts error with Asynchronous Inserts?

**Comment by MtpXV** [comment]
Are not async insterts is nearly the same as buffer table which also stores data at RAM and then flushes data to the main table?

When we looked for the answer on the Internet we saw that many used similar pipeline which we do and they fixed the error.

Maybe there is an error with the  table design? I mean badly chosen primary key or order by?

**Comment by DerekChia** [comment]
You are partitioning by month, so this is ideal unless in each insert you have rows spanning over many months (hundreds). If this is the case, each of the partitions will create a new part and you may still hit the error.

**Comment by MtpXV** [comment]
No right now we have 4 partitions/months data only. Then not sure we are doing wrong. Primary key is okay also?

**Comment by alexber1277** [comment]
You don't have a field **Date**
I had the same problem. Not **DateTime**.
