### ISSUE TITLE
Why ENABLE_BMI disabled by default

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#45953]
The BMI is broadly supported in my opinion and it is helpful for performance. I am just wondering that why it is disabled by default. Is there any reason that I don't know?

![image](https://user-images.githubusercontent.com/1518453/216280634-124571d9-f535-4e57-ae50-dbd4a0e62574.png)

**Comment by rschu1ze** [comment]
They are too new.

[BMI1](https://en.wikipedia.org/wiki/X86_Bit_manipulation_instruction_set) was first supported with Intel Haswell which appeared in 2013. AMD introduced them under a different name a bit earlier if I read right. For reasons of backward compat, ClickHouse doesn't even require AVX1 which appeared in 2011 with Intel Sandy Bridge. Please refer to #40459 for further details. I think we can probably enable BMI1 in 1 or 2 years from now.

**Comment by Alex-Cheng** [comment]
@rschu1ze  Thank you. 2013 is ten years ago, I think it is old enough.

**Comment by rschu1ze** [comment]
Note that it is not generally disallowed to use BMI instructions. There is actually lots of code with AVX1/2/512 intrinsic, but it will depend on runtime-dispatch which falls back to a (mandatory) generic code path when the requested instruction set is not available (see src/Common/TargetSpecific.h for details).

**Comment by Alex-Cheng** [comment]
Thank you. When I build CH myself, and not explicit enable BMI, then the build will not include the BMI instructions, right?

**Comment by rschu1ze** [comment]
That is right. And as you rightfully mention, manually enabling BMI via CMake and then building ClickHouse is another alternative :)
