### ISSUE TITLE
Why size field of StringRef is 64bit (8 bytes)

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#45951]
StringRef is usually used for representing a string and contains a pointer and size. A pointer has to be 64 bit in my x64 machine, however the size is not necessarily 64bit in my opinion, because usually string's length is less then 65535 and two bytes is enough. 

For each string, 6 bytes are wasted. For big amount of strings, the wasted memory is considerable.

Why we choose 64bit (size_t) for string's size?

**Comment by alexey-milovidov** [comment]
4 bytes are sometimes not enough (there are memory ranges larger than 2 GB).

**Comment by alexey-milovidov** [comment]
Alignment often makes this saving useless. For example, if you have two StringRefs, one adjacent to another, the second one must be aligned by 8 bytes.

**Comment by Alex-Cheng** [comment]
in my cases, all strings are less than 1000, and we could avoid alignment by 8 bytes via designing a specific container class (i.e. another implementation of vector<string>. If we did it then we could save a lot of memory, e.g. for 1billion of strings it would save 8GiB memory.

**Comment by Alex-Cheng** [comment]
@alexey-milovidov please consider about the idea. I cannot re-open the ticket.

**Comment by alexey-milovidov** [comment]
It is possible to have strings larger than 4 GB in ClickHouse. Therefore, we should not use just 32 bits for string size.

**Comment by alexey-milovidov** [comment]
Here is an example with 5 GB string:

```
milovidov-desktop :) SELECT length(*) FROM file('/home/milovidov/Downloads/output.tsv', RawBLOB)

SELECT length(*)
FROM file('/home/milovidov/Downloads/output.tsv', RawBLOB)

Query id: 89bbcc01-06b1-4461-9574-2dd8acfd3826

┌─length(raw_blob)─┐
│       5491800000 │
└──────────────────┘

1 row in set. Elapsed: 4.174 sec. 

milovidov-desktop :)
```

**Comment by alexey-milovidov** [comment]
Limiting something to 32 bit is a signature of old software, I don't want to have these limitations in ClickHouse.

**Comment by Alex-Cheng** [comment]
Got it! And StringRef has two fields: ptr, size. As ptr is 8-bytes, then the size of StringRef still 8-bytes even if the size is changed to 32bit.
