### ISSUE TITLE
Add correct `ON CLUSTER` syntax for `SYSTEM SYNC REPLICA`

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#45963]
Usually we have `<command> ON CLUSTER <cluster>` syntax.
For some reason currently syntax is  `SYSTEM SYNC REPLICA ON CLUSTER <cluster> [<database>.]<table>`;

`ON CLUSTER` version is undocumented, so we need to add documentation for correct syntax and explain how to run it synchronously waiting all replicas to successfully run it.
https://clickhouse.com/docs/en/sql-reference/statements/system/#sync-replica

**Comment by tavplubix** [comment]
The current syntax is totally correct, documentation is updated in https://github.com/ClickHouse/ClickHouse/pull/45984

**Comment by qoega** [comment]
This is not consistent?
`SYSTEM SYNC REPLICA ON CLUSTER cluster test`
and
`SYSTEM RESTORE REPLICA test ON CLUSTER cluster`
`SYSTEM RESTORE REPLICA ON CLUSTER cluster test `
and
`DROP DATABASE [IF EXISTS] db [ON CLUSTER cluster]`
`DROP USER [IF EXISTS] name [,...] [ON CLUSTER cluster_name]`
`ATTACH TABLE [IF NOT EXISTS] [db.]name [ON CLUSTER cluster]`

It is a mess.
