### ISSUE TITLE
Easter egg or what?

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#45989]
Thought I was hacked...

https://github.com/ClickHouse/ClickHouse/blob/63bfa19465da977eab5e0af991b61074bb99646b/src/Client/ClientBase.cpp#L2223-L2226

Last time I saw similar issue was ant-design/ant-design#13098.

**Comment by den-crane** [comment]
it seems you use clickhouse-client not on daily basis )

**Comment by zhicwu** [comment]
> it seems you use clickhouse-client not on daily basis )

You got me :D I'm not complaining anything, but it's kind of scary when you're trying to do something serious...

**Comment by alexey-milovidov** [comment]
This is a legitimate feature. 
The original feature was suggested by Viktor Tarnavsky, implemented by me in 2015, and then enhanced by Amos Bird in 2020.
