### ISSUE TITLE
Missing documentation for `executable` table function and `Executable`, `ExecutablePool` engines.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#45993]

**Comment by alexey-milovidov** [comment]
https://presentations.clickhouse.com/meetup56/new_features/index.html#9

**Comment by rfraposa** [comment]
The table engines are added in https://github.com/ClickHouse/ClickHouse/pull/46048

**Comment by rfraposa** [comment]
Added a new page for the `executable` table function also
