### ISSUE TITLE
 Unexpected behaviour RBAC  for role_grants

### ISSUE THREAD

**Issue by bigdata-spec** [ClickHouse/ClickHouse#45990]
Hi， Recently I've been using roles and grants，But I find some problem：
 Clickhouse Version  is 22.8.1.2097 (official build).

Step1： **GRANT SHOW, SELECT, dictGet ON  *.*  TO bigdata_readonly_role**  
I can select all table by user who has bigdata_readonly_role role . it is right.

Step2： 
**REVOKE SELECT ON bp_cloud_basic_platform_mysql.vehicle_basic_dms_vehicle FROM bigdata_readonly_role                                                                                                                                                   
REVOKE SELECT ON ing_bp_cloud_basic_platform_mysql.vehicle_basic FROM bigdata_readonly_role                                                                                                                                            
REVOKE SELECT ON ing_tsp_cloud_tsp_manage_mysql.vehicle_basic_dms_vehicle FROM bigdata_readonly_role** 

I can still select all table  by user . it is not meet expectations， is this a bug？which version can fix it? 
Looking forward to your reply.

I also try reconnect by user  ,
and 
revoke bigdata_readonly_role from user....;
grant bigdata_readonly_role to user....;
but it does't effect.

![image](https://user-images.githubusercontent.com/23710717/216491833-95e7cafe-9dff-491a-b1b1-6a19cd718399.png)

**Comment by den-crane** [comment]
did you reconnect by user?

**Comment by bigdata-spec** [comment]
> did you reconnect by user?
Hi,
yes， close client and connect again.

**Comment by den-crane** [comment]
What if you revoke the role from the user and grant it back?

**Comment by bigdata-spec** [comment]
> What if you revoke the role from the user and grant it back?

I test **revoke the role from the user and grant it back.**   but user can still select all.

but  if I run **REVOKE SELECT ON bp_cloud_basic_platform_mysql.vehicle_basic_dms_vehicle FROM user on cluster 'ch_cluster' ;**  then  use can't select   bp_cloud_basic_platform_mysql.vehicle_basic_dms_vehicle   .

**Comment by den-crane** [comment]
I ask you to check what will happen if:

```
revoke bigdata_readonly_role from user....;
grant bigdata_readonly_role from user....;
```

**Comment by bigdata-spec** [comment]
> I ask you to check what will happen if:
> 
> ```
> revoke bigdata_readonly_role from user....;
> grant bigdata_readonly_role to user....;
> ```

I try this commad.  but  user still can select all table . I think it is not correctly.

**Comment by den-crane** [comment]
I see. I completely misunderstood your case. Sorry very much.

**Comment by bigdata-spec** [comment]
> I see. I completely misunderstood your case. Sorry very much. Disregard my comments.

Thank you for you reply. you are so warm-hearted.

**Comment by den-crane** [comment]
So you have a user: user1.
You have a role: role1.
You have several tables a the database: db1.

Then you execute 

```sql
GRANT role1 to user1 
GRANT SHOW, SELECT, dictGet ON *.* TO role1;
REVOKE SELECT on db1.t1 from role1;
```
And then user1 is still able to `select * from db1.t1` ? Right?

**Comment by bigdata-spec** [comment]
> So you have a user: user1. You have a role: role1. You have several tables in a database: db1.
> 
> Then you execute
> 
> ```sql
> GRANT role1 to user1; 
> GRANT SHOW, SELECT, dictGet ON *.* TO role1;
> REVOKE SELECT on db1.t1 from role1;
> ```
> 
> And then user1 is still able to `select * from db1.t1` ? Right?

yes，you are right. is this normal?

**Comment by den-crane** [comment]
I cannot reproduce it:

```sql
CREATE DATABASE db1;
CREATE TABLE db1.t1 (a Int) Engine=Memory;
CREATE TABLE db1.t2 (a Int) Engine=Memory;
CREATE USER user1 IDENTIFIED by 'bar';
CREATE ROLE role1;
GRANT role1 to user1; 
GRANT SHOW, SELECT, dictGet ON db1.* TO role1;
REVOKE SELECT on db1.t1 from role1;

select * from system.grants;
┌─user_name─┬─role_name─┬─access_type─┬─database─┬─table─────┬─column─┬─is_partial_revoke─┬─grant_option─┐
│ default   │ ᴺᵁᴸᴸ      │ ALL         │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            1 │
│ ᴺᵁᴸᴸ      │ role1     │ SHOW        │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
│ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
│ ᴺᵁᴸᴸ      │ role1     │ dictGet     │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
│ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ t1        │ ᴺᵁᴸᴸ   │                 1 │            0 │
└───────────┴───────────┴─────────────┴──────────┴───────────┴────────┴───────────────────┴──────────────┘

clickhouse-client -u user1 --password=bar --database=db1
┌─name─┐
│ t1   │
│ t2   │
└──────┘

select * from t1;
DB::Exception: user1: Not enough privileges.

select * from t2;
0 rows in set. Elapsed: 0.001 sec
```

**Comment by bigdata-spec** [comment]
> I cannot reproduce it:
> 
> ```sql
> CREATE DATABASE db1;
> CREATE TABLE db1.t1 (a Int) Engine=Memory;
> CREATE TABLE db1.t2 (a Int) Engine=Memory;
> CREATE USER user1 IDENTIFIED by 'bar';
> CREATE ROLE role1;
> GRANT role1 to user1; 
> GRANT SHOW, SELECT, dictGet ON db1.* TO role1;
> REVOKE SELECT on db1.t1 from role1;
> 
> select * from system.grants;
> ┌─user_name─┬─role_name─┬─access_type─┬─database─┬─table─────┬─column─┬─is_partial_revoke─┬─grant_option─┐
> │ default   │ ᴺᵁᴸᴸ      │ ALL         │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            1 │
> │ ᴺᵁᴸᴸ      │ role1     │ SHOW        │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> │ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> │ ᴺᵁᴸᴸ      │ role1     │ dictGet     │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> │ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ t1        │ ᴺᵁᴸᴸ   │                 1 │            0 │
> └───────────┴───────────┴─────────────┴──────────┴───────────┴────────┴───────────────────┴──────────────┘
> 
> clickhouse-client -u user1 --password=bar --database=db1
> ┌─name─┐
> │ t1   │
> │ t2   │
> └──────┘
> 
> select * from t1;
> DB::Exception: user1: Not enough privileges.
> 
> select * from t2;
> 0 rows in set. Elapsed: 0.001 sec
> ```

Hi，Which  version for your clickhouse？

**Comment by bigdata-spec** [comment]
@den-crane
 Hi, Can you tell me which your clickhouse version, 
I find a strang problem. last week I try RBAC, user still can select table  when I REVOKED table ,but today I find user can't select REVOKED table,
Does RBAC effect need time?if yes,how long?

**Comment by bigdata-spec** [comment]
> I used 23.1.2.9.
> 
> > Does RBAC effect need time?if yes,how long?
> 
> it's a bug in Clickhouse.

Thank you very much，My Clickhouse Version is 22.8.1.2097 (official build). 
yesterday I set RBAC ， it does't take effect immediately，but today  I find it take effect.
 Can you tell me which version fix this bug？

**Comment by den-crane** [comment]
>My Clickhouse Version is 22.8.1.2097 (official build).

You should upgrade to 22.8.13.20

>Can you tell me which version fix this bug？

There is no fix.

**Comment by bigdata-spec** [comment]
> 22.8.13.20

if not fix, upgrade to  22.8.13.20  is not meaningful.

**Comment by bigdata-spec** [comment]
> > I cannot reproduce it:
> > ```sql
> > CREATE DATABASE db1;
> > CREATE TABLE db1.t1 (a Int) Engine=Memory;
> > CREATE TABLE db1.t2 (a Int) Engine=Memory;
> > CREATE USER user1 IDENTIFIED by 'bar';
> > CREATE ROLE role1;
> > GRANT role1 to user1; 
> > GRANT SHOW, SELECT, dictGet ON db1.* TO role1;
> > REVOKE SELECT on db1.t1 from role1;
> > 
> > select * from system.grants;
> > ┌─user_name─┬─role_name─┬─access_type─┬─database─┬─table─────┬─column─┬─is_partial_revoke─┬─grant_option─┐
> > │ default   │ ᴺᵁᴸᴸ      │ ALL         │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            1 │
> > │ ᴺᵁᴸᴸ      │ role1     │ SHOW        │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> > │ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> > │ ᴺᵁᴸᴸ      │ role1     │ dictGet     │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> > │ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ t1        │ ᴺᵁᴸᴸ   │                 1 │            0 │
> > └───────────┴───────────┴─────────────┴──────────┴───────────┴────────┴───────────────────┴──────────────┘
> > 
> > clickhouse-client -u user1 --password=bar --database=db1
> > ┌─name─┐
> > │ t1   │
> > │ t2   │
> > └──────┘
> > 
> > select * from t1;
> > DB::Exception: user1: Not enough privileges.
> > 
> > select * from t2;
> > 0 rows in set. Elapsed: 0.001 sec
> > ```
> 
> Hi，Which version for your clickhouse？



> > I cannot reproduce it:
> > ```sql
> > CREATE DATABASE db1;
> > CREATE TABLE db1.t1 (a Int) Engine=Memory;
> > CREATE TABLE db1.t2 (a Int) Engine=Memory;
> > CREATE USER user1 IDENTIFIED by 'bar';
> > CREATE ROLE role1;
> > GRANT role1 to user1; 
> > GRANT SHOW, SELECT, dictGet ON db1.* TO role1;
> > REVOKE SELECT on db1.t1 from role1;
> > 
> > select * from system.grants;
> > ┌─user_name─┬─role_name─┬─access_type─┬─database─┬─table─────┬─column─┬─is_partial_revoke─┬─grant_option─┐
> > │ default   │ ᴺᵁᴸᴸ      │ ALL         │ ᴺᵁᴸᴸ     │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            1 │
> > │ ᴺᵁᴸᴸ      │ role1     │ SHOW        │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> > │ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> > │ ᴺᵁᴸᴸ      │ role1     │ dictGet     │ db1      │ ᴺᵁᴸᴸ      │ ᴺᵁᴸᴸ   │                 0 │            0 │
> > │ ᴺᵁᴸᴸ      │ role1     │ SELECT      │ db1      │ t1        │ ᴺᵁᴸᴸ   │                 1 │            0 │
> > └───────────┴───────────┴─────────────┴──────────┴───────────┴────────┴───────────────────┴──────────────┘
> > 
> > clickhouse-client -u user1 --password=bar --database=db1
> > ┌─name─┐
> > │ t1   │
> > │ t2   │
> > └──────┘
> > 
> > select * from t1;
> > DB::Exception: user1: Not enough privileges.
> > 
> > select * from t2;
> > 0 rows in set. Elapsed: 0.001 sec
> > ```
> 
> Hi，Which version for your clickhouse？

I try your sql ,but it does't take effect. user1 can still select db1.table1 and db1.table2.

**Comment by den-crane** [comment]
>if not fix, upgrade to 22.8.13.20 is not meaningful.

22.8.1.2097 is very very bad.

>I try your sql ,but it does't take effect. user1 can still select db1.table1 and db1.table2.

Clarify with versions and exact examples.

**Comment by bigdata-spec** [comment]
> > if not fix, upgrade to 22.8.13.20 is not meaningful.
> 
> 22.8.1.2097 is very very bad.
> 
> > I try your sql ,but it does't take effect. user1 can still select db1.table1 and db1.table2.
> 
> Clarify with versions and exact examples.
@den-crane 
![image](https://user-images.githubusercontent.com/23710717/217691666-154d2b2e-a372-43ff-924e-781d69423b36.png)

![image](https://user-images.githubusercontent.com/23710717/217691575-e6300216-02d3-4784-8a20-9d7e8980fb50.png)

user1 can still  select  all tables.

**Comment by den-crane** [comment]
I cannot reproduce it 

```
$ clickhouse-client -u user1 --password=bar --database=db1
ClickHouse client version 22.8.13.20 (official build).
Connecting to database db1 at localhost:9000 as user user1.
Connected to ClickHouse server version 22.8.13 revision 54460.

:) show tables;

┌─name─┐
│ t1   │
│ t2   │
└──────┘

2 rows in set. Elapsed: 0.001 sec.

:) select * from t1;
                             
0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 22.8.13):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: user1: Not enough privileges. To execute this query it's necessary to have grant SELECT(a) ON db1.t1. (ACCESS_DENIED)


:) select * from t2;

Ok.

0 rows in set. Elapsed: 0.001 sec.

```

**Comment by bigdata-spec** [comment]
@den-crane Thank you very much，The errors are random.
you are so warm-hearted.

**Comment by aadant** [comment]
We should not close this. We are still working on it.

**Comment by aadant** [comment]
> We should not close this. We are still working on it.

Ok i see this point to an existing issue. I agree this is a dupe.
