### ISSUE TITLE
short_circuit_function_evaluation doesn't work for Decimal data type

### ISSUE THREAD

**Issue by jasonbigl** [ClickHouse/ClickHouse#46005]
Clickhouse version 22.9.3

**Describe the unexpected behaviour**
`SELECT 5 as a, 0 as b, if(b = 0, 0, a / b) as c` works as expected

`SELECT toDecimal32(5, 4) as a, toDecimal32(0, 4) as b, if(b = 0, 0, a / b) as c`

throw a `DB::Exception: Division by zero`

why decimal data type calculate all branches? is there any way to avoid "Division by zero" exception for decimal data type?

Thank you.

**Comment by den-crane** [comment]
The issue  is only with constant. Because constant folding works another way.

```
SELECT materialize(toDecimal32(5, 4)) as a, materialize(toDecimal32(0, 4)) as b, if(b = 0, 0, a / b) as c
┌─a─┬─b─┬─c─┐
│ 5 │ 0 │ 0 │
└───┴───┴───┘

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/43838
