### ISSUE TITLE
Use of an Uninitialized Variable in StringSearcher.h

### ISSUE THREAD

**Issue by joey-bd** [ClickHouse/ClickHouse#46001]
@alexey-milovidov 
In ClickHouse/src/Common/StringSearcher.h, Coverity picked up a bug in lines 184 and 185 due to the use of an uninitialized variable `l_seq` and `u_seq`. 

I understand that there is an assignment made to `l_seq` and `u_seq` through either `memcpy` or `UTF8::convertCodePointToUTF8`. However, `UTF8::convertCodePointToUTF8` will initialize only up to the fifth element which leaves the sixth element uninitialized.

Is this an intended behavior? Thank you in advance.

**Comment by alexey-milovidov** [comment]
It's ok to have bytes uninitialized as long as the uninitialized memory is not used.
This code is covered by tests, and tests are run under MSan.
