### ISSUE TITLE
Flaky test: 02540_date_column_consistent_insert_behaviour

### ISSUE THREAD

**Issue by hanfei1991** [ClickHouse/ClickHouse#46017]
https://s3.amazonaws.com/clickhouse-test-reports/45985/0c7de1941ca7a1f7f53dff17a9c375e3b1a2b529/stateless_tests__release__s3_storage__[1/2].html

**Comment by Felixoid** [comment]
Fixed with https://github.com/ClickHouse/ClickHouse/pull/46007

**Comment by tavplubix** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/46007

**Comment by tavplubix** [comment]
Ha-ha, a race condition :)

**Comment by Felixoid** [comment]
Oh wow
