### ISSUE TITLE
Uncompatible types of subcolumn 'k1': Array(Int8) and Int8

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#46019]
(you don't have to strictly follow this form)

**Describe the bug**
A link to the report https://s3.amazonaws.com/clickhouse-test-reports/45568/dd64c8bacca0eb74239466a04760e21561207c9a/fuzzer_astfuzzerasan/report.html

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

**Comment by CurtizJ** [comment]
It's exactly the bug that was fixed in #45995. Is it possible that there was a race and old build was run with new tests fetched from master?

**Comment by Felixoid** [comment]
Yes, the `keeper-systemd` from #45568 is based on bb44a14a561e16f935d67639c276c096e474014c, which was before the fix. Thank you
