### ISSUE TITLE
clickhouse-server.aarch64 0:23.1.3.5-1 GLIBC_2.28 not found

### ISSUE THREAD

**Issue by van4oza** [ClickHouse/ClickHouse#46055]
Amazon Linux 2 can't run clickhouse

```
Установлено:
  clickhouse-client.aarch64 0:23.1.3.5-1
  clickhouse-server.aarch64 0:23.1.3.5-1                                                                   

Установлены зависимости:
  clickhouse-common-static.aarch64 0:23.1.3.5-1                                                                                                                                                                       

Выполнено!

[ec2-user@ip-10-0-7-11 ~]$ sudo /etc/init.d/clickhouse-server start

clickhouse: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by clickhouse)
```

**Comment by cangyin** [comment]
1. you can try upgrading GLIBC version to just 2.28. but be warned that this may break your system. so do some tests and be sured that it's ok to do so.

2. use docker images 

3. or compile from source

**Comment by alexey-milovidov** [comment]
I confirm - this is a major overlook in the build process.

```
[ec2-user@ip-172-31-10-102 ~]$ nm -D --with-symbol-versions ./clickhouse | grep -F 2.28
                 w statx@GLIBC_2.28
```

**Comment by alexey-milovidov** [comment]
@cangyin, your advice is ok, but ClickHouse should always work everywhere, no matter what.

**Comment by l1t1** [comment]
if no new feature of glibc 2.28 is needed,could clickhouse consider downgrade the lib verion int the package.

**Comment by rschu1ze** [comment]
Sorry for the delay, I am checking now.

**Comment by rschu1ze** [comment]
Doesn't happen on Ubuntu 22.04 (my daily driver), neither with downloaded builds (using universal.sh) nor with compiled builds.

But it reproduces with downloaded binaries (universal.sh) on Amazon Linux 2 which is stuck with 2018 packages and glibc 2.26. CI runs a check which should prevent such a situation (--> tests/ci/compatibility_check.py). Right now I suspect the self-extraction step is the problem because unpack fails with the error already and the CI check as far as I see doesn't check self-extraction.

**Comment by rschu1ze** [comment]
Nope, it is not related to self-extraction, it is a general problem. Just self-extracted clickhouse on an Ubuntu ARM system, copied the binary to the Amazon Linux ARM system and it refused to run.

Interestingly, all GLIBC symbols shown by `nm` are `U` (undefined). The only other undefined symbols are a few zstd tracing symbols (probably okay) and some memory tracker functions (surely okay). This is true for ARM and x86.

`statx` appears in `nm` output on ARM but not x86 (for whatever reason), and it is the only `w` (weak) symbol (for whatever reason). This might explain why only ARM is affected, on x86 the old system glibc of Amazon Linux 2 provides all symbols.

```
# ARM:
nm -D --with-symbol-versions clickhouse | grep GLIBC
...
U statfs@GLIBC_2.17 
U statvfs@GLIBC_2.17
w statx@GLIBC_2.28  
U stderr@GLIBC_2.17 
U stdin@GLIBC_2.17  
...
```

Biggest question mark is why the symbols are undefined at all ... need to look at build.ninja and  cmake build scripts.

**Comment by rschu1ze** [comment]
`statx()` [ended up in glibc-compatibility](https://github.com/ClickHouse/ClickHouse/pull/33435/files#diff-21b33bddf7bdb516d31f425f8534b22c8689dfbcf1311bf7739671d6dc804ae8) as per the [recent Rust integration](https://github.com/ClickHouse/ClickHouse/pull/33435) but only on non-ARM.

**Comment by alexey-milovidov** [comment]
Thanks!

Also, just for reference: you can find out who needs a symbol by doing the following:
1. Build ClickHouse as usual.
2. Remove the `clickhouse` binary.
3. Run `ninja -V` for the verbose mode.
4. Copy the linker's invocation command.
5. Add `-Wl,--trace-symbol=wtf` to find out where the symbol `wtf` comes from.

**Comment by rschu1ze** [comment]
Thanks, I saved the hint in my local tips-and-tricks file :-)
