### ISSUE TITLE
DB::Exception: Unexpected type Nullable(IPv6) of bloom filter index

### ISSUE THREAD

**Issue by xuyatian** [ClickHouse/ClickHouse#46059]
**Describe the unexpected behaviour**
CH 23.1.29. we got a "DB::Exception: Unexpected type Nullable(IPv6) of bloom filter index" error when creating table with Nullable(IPv6) of bloom filter index.
CH 22.3.2.2 no such issue.

**How to reproduce**
* Which ClickHouse server version to use
23.1.2.9
* `CREATE TABLE` statements for all tables involved
create TABLE test (`adom_oid` UInt32 CODEC(LZ4), `itime` DateTime CODEC(LZ4), `host_ip` Nullable(IPv6) CODEC(LZ4), INDEX sidx_host_ip host_ip TYPE bloom_filter(0.1) GRANULARITY 3) ENGINE = MergeTree PARTITION BY toYYYYMMDD(itime) ORDER BY (adom_oid, itime)  SETTINGS index_granularity = 8192

**Error message and/or stacktrace**
2023.02.05 10:24:22.995672 [ 1470001 ] {7bdc22e2-653b-40a5-bb05-582de1a36c82} <Error> TCPHandler: Code: 44. DB::Exception: Unexpected type Nullable(IPv6) of bloom filter index. (ILLEGAL_COLUMN), Stack trace (when copying this message, always include the lines below):

0. /home/yxu/code/ClickHouse/contrib/llvm-project/libcxx/include/exception:134: std::exception::capture() @ 0x188d0942 in /usr/bin/clickhouse
1. /home/yxu/code/ClickHouse/contrib/llvm-project/libcxx/include/exception:112: std::exception::exception[abi:v15000]() @ 0x188d090d in /usr/bin/clickhouse
2. /home/yxu/code/ClickHouse/contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x2fab91a0 in /usr/bin/clickhouse
3. /home/yxu/code/ClickHouse/src/Common/Exception.cpp:89: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x21003ace in /usr/bin/clickhouse
4. /home/yxu/code/ClickHouse/src/Common/Exception.h:64: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, int, bool) @ 0x188c7c4a in /usr/bin/clickhouse
5. /home/yxu/code/ClickHouse/src/Common/Exception.h:84: DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(int, FormatStringHelperImpl<std::__1::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&) @ 0x188c4133 in /usr/bin/clickhouse
6. /home/yxu/code/ClickHouse/src/Storages/MergeTree/MergeTreeIndexBloomFilter.cpp:92: DB::assertIndexColumnsType(DB::Block const&) @ 0x2a87e916 in /usr/bin/clickhouse
7. /home/yxu/code/ClickHouse/src/Storages/MergeTree/MergeTreeIndexBloomFilter.cpp:117: DB::bloomFilterIndexValidatorNew(DB::IndexDescription const&, bool) @ 0x2a87e3e4 in /usr/bin/clickhouse
8. /home/yxu/code/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<void (*&)(DB::IndexDescription const&, bool)>()(std::declval<DB::IndexDescription const&>(), std::declval<bool>())) std::__1::__invoke[abi:v15000]<void (*&)(DB::IndexDescription const&, bool), DB::IndexDescription const&, bool>(void (*&)(DB::IndexDescription const&, bool), DB::IndexDescription const&, bool&&) @ 0x2a84998d in /usr/bin/clickhouse
9. /home/yxu/code/ClickHouse/contrib/llvm-project/libcxx/include/__functional/invoke.h:480: void std::__1::__invoke_void_return_wrapper<void, true>::__call<void (*&)(DB::IndexDescription const&, bool), DB::IndexDescription const&, bool>(void (*&)(DB::IndexDescription const&, bool), DB::IndexDescription const&, bool&&) @ 0x2a849945 in /usr/bin/clickhouse
10. /home/yxu/code/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__1::__function::__default_alloc_func<void (*)(DB::IndexDescription const&, bool), void (DB::IndexDescription const&, bool)>::operator()[abi:v15000](DB::IndexDescription const&, bool&&) @ 0x2a849905 in /usr/bin/clickhouse
11. /home/yxu/code/ClickHouse/contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__1::__function::__policy_invoker<void (DB::IndexDescription const&, bool)>::__call_impl<std::__1::__function::__default_alloc_func<void (*)(DB::IndexDescription const&, bool), void (DB::IndexDescription const&, bool)>>(std::__1::__function::__policy_storage const*, DB::IndexDescription const&, bool) @ 0x2a8498b0 in /usr/bin/clickhouse

**Additional context**
it is related to this commit:
https://github.com/ClickHouse/ClickHouse/commit/4d144be39ca7ff81c2570c68485eb06f03d28529

**Comment by den-crane** [comment]
```sql
create TABLE test(
   a UInt32, 
   ip Nullable(IPv6), 
   INDEX x1 ip TYPE bloom_filter(0.1) GRANULARITY 3
)ENGINE = MergeTree ORDER BY (a);
```
