### ISSUE TITLE
domain(localhost) is empty

### ISSUE THREAD

**Issue by khamin** [ClickHouse/ClickHouse#46062]
**Describe the unexpected behaviour**

`SELECT domain('http://localhost')` return empty string.

**How to reproduce**

* Which ClickHouse server version to use: `22.12.2`

**Expected behavior**

Should return `localhost`.
Same for other single-level domains.

**Comment by cangyin** [comment]
That is expected. From comment of `FunctionDomain`, it returns:

https://github.com/ClickHouse/ClickHouse/blob/c4f4a1db35e0ece0d7fb8aa85bebe13dc0494699/src/Functions/URL/domain.h#L132-L135

**Comment by khamin** [comment]
> That is expected. From comment of `FunctionDomain`, it returns:
> 
> https://github.com/ClickHouse/ClickHouse/blob/c4f4a1db35e0ece0d7fb8aa85bebe13dc0494699/src/Functions/URL/domain.h#L132-L135

It does not change the fact that `localhost` is a valid domain.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/31106
