### ISSUE TITLE
Do ClickHouse support azure blob as external storage? If yes so is there any example?

### ISSUE THREAD

**Issue by chenjinxuan** [ClickHouse/ClickHouse#46069]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by UnamedRus** [comment]
You mean as Disk for MergeTree table?

Check PR https://github.com/ClickHouse/ClickHouse/pull/31505 and docs https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#table_engine-mergetree-azure-blob-storage

**Comment by alexey-milovidov** [comment]
ClickHouse has support for Azure blob storage as a backend, but it is not recommended for production, as there are no performance tests, and not every functional test is run over this backend. It is at the same stage as the HDFS backend.
