### ISSUE TITLE
Hello, everyone, I want to ask a question, can materialized view stop statistics?

### ISSUE THREAD

**Issue by cnzxc** [ClickHouse/ClickHouse#46061]
as title

**Comment by cangyin** [comment]
AFAIK, no. But you can create a new table same as the inner table, and [EXCHANGE](https://clickhouse.com/docs/en/sql-reference/statements/exchange) the two tables, so you got the table swapped out.

**Comment by den-crane** [comment]
```sql
detach table your_mat_view permanently;
```
