### ISSUE TITLE
Partitions never merge

### ISSUE THREAD

**Issue by malsumis** [ClickHouse/ClickHouse#4607]
Hi,

I have some pretty big partitions in my clickhouse server (over 1TiB in size). My issue is that they are not getting properly rolled up, even when I use `OPTIMIZE`. What can I do to resolve this?

My rollup settings:

```xml
<?xml version="1.0"?>
<yandex>
<graphite_rollup>
  <path_column_name>Path</path_column_name>
   <time_column_name>Time</time_column_name>
    <value_column_name>Value</value_column_name>
    <version_column_name>Timestamp</version_column_name>
```

>DESCRIBE TABLE default.graphite
>┌─name──────┬─type────┬─default_type─┬─default_expression─┐
>│ Path      │ String  │              │                    │
>│ Value     │ Float64 │              │                    │
>│ Time      │ UInt32  │              │                    │
>│ Date      │ Date    │              │                    │
>│ Timestamp │ UInt32  │              │                    │

>:) SELECT   table, sum(rows), partition, count() as number_of_parts,  formatReadableSize(sum(bytes)) as sum_size  FROM system.parts  WHERE table='graphite' GROUP BY table, partition  ORDER BY partition;

>┌─table────┬────sum(rows)─┬─partition─┬─number_of_parts─┬─sum_size───┐
>│ graphite       │ 298035905629 │ 201901    │              22 │ 1.84 TiB   │
>│ graphite │ 285865553849 │ 201902    │              17 │ 1.14 TiB   │
>│ graphite │  62455396718 │ 201903    │             241 │ 227.04 GiB │
>└──────┴──────────┴───────┴───────┴────────┘

Doing:
> :) OPTIMIZE TABLE default.graphite ON CLUSTER ch PARTITION 201901 FINAL;

Results in : 

>┌host┬─port-┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
>│ ch1 │ 9000 │      0 │       │                   1 │                0 │
>│ ch2 │ 9000 │      0 │       │                   0 │                0 │

>2 rows in set. Elapsed: 0.137 sec. 

Unfortunately the partition is not being merged and therefore rolled up.

I've looked through MergeTreeSettings.h and found a possible problem - maybe the parts are too big or some other. There is a setting, that might be blocking the merge process:

>     /** Maximum in total size of parts to merge, when there are maximum (minimum) free threads              
>     * in background pool (or entries in replication queue). */                                               \
>    M(SettingUInt64, max_bytes_to_merge_at_max_space_in_pool, 150ULL * 1024 * 1024 * 1024)                    
>    M(SettingUInt64, max_bytes_to_merge_at_min_space_in_pool, 1024 * 1024)                                    

150ULL * 1024 * 1024 * 1024 is 161061273600 bytes so about 0.15 TiB. Am I correct here? Will this help in any way or might there be any other issue preventing the rollup.

**Comment by filimonov** [comment]
@Felixoid does your recent changes address that?

**Comment by Felixoid** [comment]
I doubt. @malsumis did you build ClickHouse today or was it during long time?

**Comment by malsumis** [comment]
Actually we're using 18.14.18

**Comment by malsumis** [comment]
I pasted only the table definition of rollup.xml and forgot to paste in the actual retention config:


> :) select * from system.graphite_retentions;
>
>SELECT *
>FROM system.graphite_retentions 
>
>┌─config_name─┬─regexp─┬─function─┬─age─┬─precision─┬─priority─┬─is_default─┐
>│ graphite_rollup │ ^carbon\. │ avg      │       0 │        60 │        1 │          0 │
>│ graphite_rollup │ \.jmx\.   │ avg      │       0 │         1 │        2 │          0 │
>│ graphite_rollup │ \.jmx\.   │ avg      │  604800 │         5 │        2 │          0 │
>│ graphite_rollup │ \.jmx\.   │ avg      │ 3024000 │        60 │        2 │          0 │
>│ graphite_rollup │ ^.*\.max$ │ max      │       0 │        60 │        3 │          0 │
>│ graphite_rollup │ ^.*\.max$ │ max      │ 2592000 │       300 │        3 │          0 │
>│ graphite_rollup │ ^.*\.max$ │ max      │ 7776000 │      3600 │        3 │          0 │
>│ graphite_rollup │ ^.*\.min$ │ min      │       0 │        60 │        4 │          0 │
>│ graphite_rollup │ ^.*\.min$ │ min      │ 2592000 │       300 │        4 │          0 │
>│ graphite_rollup │ ^.*\.min$ │ min      │ 7776000 │      3600 │        4 │          0 │
>│ graphite_rollup │           │ avg      │       0 │        60 │    65535 │          1 │
>│ graphite_rollup │           │ avg      │ 2592000 │       300 │    65535 │          1 │
>│ graphite_rollup │           │ avg      │ 7776000 │      3600 │    65535 │          1 │

**Comment by Felixoid** [comment]
```
┌─config_name─────┬─regexp───┬─function─┬─age───────┬─precision───┬─priority─┬─is_default─┐
│ graphite_rollup │ ^carbon. │    avg   │ 0         │      60     │      1   │   0        │
│ graphite_rollup │ .jmx.    │    avg   │ 0         │      1      │      2   │   0        │
│ graphite_rollup │ .jmx.    │    avg   │ 604800    │      5      │      2   │   0        │
│ graphite_rollup │ .jmx.    │    avg   │ 3024000   │      60     │      2   │   0        │
│ graphite_rollup │ ^._.max$ │    max   │ 0         │      60     │      3   │   0        │
│ graphite_rollup │ ^._.max$ │    max   │ 2592000   │      300    │      3   │   0        │
│ graphite_rollup │ ^._.max$ │    max   │ 7776000   │      3600   │      3   │   0        │
│ graphite_rollup │ ^._.min$ │    min   │ 0         │      60     │      4   │   0        │
│ graphite_rollup │ ^._.min$ │    min   │ 2592000   │      300    │      4   │   0        │
│ graphite_rollup │ ^._.min$ │    min   │ 7776000   │      3600   │      4   │   0        │
│ graphite_rollup │          │    avg   │ 0         │      60     │  65535   │   1        │
│ graphite_rollup │          │    avg   │ 2592000   │      300    │  65535   │   1        │
│ graphite_rollup │          │    avg   │ 7776000   │      3600   │  65535   │   1        │
```
Actually, if all your metrics are started with `^carbon.`, then they will never compress because it does have only one retention. See https://github.com/yandex/ClickHouse/blob/84f1fe6e75a64ae4ede7c6b483328146e9339618/docs/en/operations/table_engines/graphitemergetree.md
> When processing a row, ClickHouse checks the rules in the `pattern` section. If the metric name matches the `regexp`, the rules from the `pattern` section are applied; otherwise, the rules from the `default` section are used.

In other words, only the first matched pattern is applied to metrics

**Comment by malsumis** [comment]
I understand that. We have multiple metrics that do not start with "carbon". Metrics starting with carbon are only a very small subset of all metrics.

SELECT countDistinct(Path)
FROM graphite 
PREWHERE Date = '2019-03-06'
WHERE Path NOT LIKE 'carbon%'

┌─uniqExact(Path)─┐
│         8324970 │

1 rows in set. Elapsed: 57.642 sec. Processed 9.50 billion rows, 635.41 GB (164.83 million rows/s., 11.02 GB/s.)

**Comment by alexey-milovidov** [comment]
@malsumis 
```
I've looked through MergeTreeSettings.h and found a possible problem - maybe the parts are too big or some other. There is a setting, that might be blocking the merge process:
```
That's right.

You can check the exact reason if you `SET optimize_throw_if_noop = 1`.
ClickHouse will throw an exception with detailed message about the reason if OPTIMIZE cannot proceed.

You can modify MergeTree settings in one of two ways:
- in configuration file in `<merge_tree>`;
- with `ALTER TABLE ... MODIFY SETTING` query. This is available in recent releases.

**Comment by Felixoid** [comment]
BTW, there's a project which does the job. https://github.com/innogames/graphite-ch-optimizer
The packaging is planned for the following week
