### ISSUE TITLE
Make EPHEMERAL columns visible in MATERIALIZED VIEW

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#46082]
**Use case**

A column is used by query in the materialized view but not needed to be stored in the main table.

**Describe the solution you'd like**

We can add this column as  EPHEMERAL to the main table and make it visible for MV query.

**Comment by alexey-milovidov** [comment]
@KochetovNicolai, fixed by #57461 as I guess.
