### ISSUE TITLE
DELTA CODEC don't support Nullable ?

### ISSUE THREAD

**Issue by TH-HA** [ClickHouse/ClickHouse#4609]
**Describe the bug**
   DELTA CODEC is not supported when column is nullable. As there is no mention of this restriction in the doc , it's either a Documentation bug or a bug in the feature. 
 
**How to reproduce**
  execute the following SQL :
```sql
CREATE TABLE IF NOT EXISTS some_table (
       `timestamp` DATETIME DEFAULT now(), 
       field0 Nullable(Int64)  CODEC(Delta(2),LZ4), 
       field1 Nullable(Int64)  CODEC(Delta(2),LZ4)  
) 
ENGINE = MergeTree PARTITION BY (toStartOfDay(`timestamp`)) 
ORDER BY (`timestamp`) SETTINGS index_granularity = 8192 ;
```
Clickhouse refuse to create the table : DB::Exception: Value of type Nullable(Int64) in memory is not of fixed size. 

* Which ClickHouse server version to use
ClickHouse 19.3.6

* Which interface to use, if matters
http via Tabix 

* Non-default settings, if any
None

**Comment by mjodeh** [comment]
any progress?

**Comment by filimonov** [comment]
Implementation for that case in more cumbersome, and questionable

1) codec is smth we apply on the top of numerical column. Internally Nullable(UIntXX) is 2 columns, it is not very clear how it should be applied there.
2) what is the `Delta(1,Null)` ?
