### ISSUE TITLE
Undocumented compression parameter for file()

### ISSUE THREAD

**Issue by vincent-octo** [ClickHouse/ClickHouse#46105]
The current [documentation for file](https://clickhouse.com/docs/en/sql-reference/table-functions/file) shows it has 3 parameters: path, format, and structure.

However, it appears a compression argument can also be given as a fourth parameter.
From this [ClickHouse blog post](https://clickhouse.com/blog/extracting-converting-querying-local-files-with-sql-clickhouse-local#workingwithlargefiles):

```
./clickhouse local -q "SELECT count(*) FROM file(hackernews.csv.gz, CSVWithNames,'auto', 'gzip')"
```

(the `'gzip'` at the end)

It would be nice to have this parameter added to the documentation, along with some explanation such as its possible values.

**Comment by vincent-octo** [comment]
Found some reference code here:
- https://github.com/ClickHouse/ClickHouse/blob/f6ebe11350c153d3faad35a5eea00fc79e00d821/src/TableFunctions/TableFunctionFile.h
- https://github.com/ClickHouse/ClickHouse/blob/f6ebe11350c153d3faad35a5eea00fc79e00d821/src/TableFunctions/TableFunctionFile.cpp

Though still not sure what would be the possible compression options.

**Comment by DanRoscigno** [comment]
Maybe in here too? https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/CompressionMethod.cpp

**Comment by vincent-octo** [comment]
Yes! This looks like the correct place :)

**Comment by DanRoscigno** [comment]
Thanks @vincent-octo for pointing this out.
