### ISSUE TITLE
Needless grave accent in file : programs/server/config.xml

### ISSUE THREAD

**Issue by shawn-fu** [ClickHouse/ClickHouse#46104]
**Description**
Version:  22.8.11.15-lts.

> When I enable some configurations, Clickhouse report config.xml has errors。I found It has needless grave accent in config.xml。
>Change log as follows：
https://github.com/ClickHouse/ClickHouse/commit/4af61fb9d390c3c908993a31a2b820a1d073c48d

```
    <!-- Disable AuthType Plaintext_password and No_password for ACL. --> 
    <!-- <allow_plaintext_password>0</allow_plaintext_password> -->
    <!-- <allow_no_password>0</allow_no_password> -->`
```
   The grave accent is needless.

**Comment by tavplubix** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/commit/72d8a04ee612fe561b60bedf0faa8c46f37491de
