### ISSUE TITLE
these `<disk>gcs</disk>` look like are not edited copy/paste errors

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#46134]
https://clickhouse.com/docs/en/integrations/s3/gcs-merge-tree/#storage_configuration--disks--cache

I don't get the idea of 3 times the same fragment.
```
            <gcs_main>
                <volumes>
                    <main>
                        <disk>gcs</disk>
                    </main>
                </volumes>
            </gcs_main>
```

May be it mean to have at least one time `<disk>cache</disk>` and policy should be named `default` in the first 2 pieces ?

**Comment by kssenii** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/758
