### ISSUE TITLE
Bloom filter skip index not used on array of strings

### ISSUE THREAD

**Issue by awitten1** [ClickHouse/ClickHouse#46142]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

I have a table with the following schema:

```
CREATE TABLE default.test_table
(
    `id` UUID,
    `timestamp` DateTime64(5),
    `output` Array(String),
    INDEX bloom_filter_output output TYPE bloom_filter GRANULARITY 2,
)
ENGINE = MergeTree
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 1024 
```

I would like to query for all rows with a particular string in the `output` string array.  I expect some granules to be dropped, but none are.  All rows are processed.

* Which ClickHouse server version to use

 23.1.2.9 

* Queries to run that lead to unexpected result

```
SELECT COUNT(*) FROM test_table WHERE has(output, 'polygon') SETTINGS use_skip_indexes=1;
```

When I run the above query with `SET send_logs_level = 'debug'` I see a line with `ac75) (SelectExecutor): Index `bloom_filter_output` has dropped 0/1018 granules.`

I also see the line 

```
1 row in set. Elapsed: 0.698 sec. Processed 71.00 thousand rows, 1.98 GB (101.69 thousand rows/s., 2.83 GB/s.)
```
(I have 71 thousand rows total).

**Comment by cangyin** [comment]
> Index bloom_filter_output has dropped 0/1018 granules

This log message means, the index is used. but after filtering data blocks using the index, no 'granules' are ignored.

**Comment by awitten1** [comment]
Thank you for your quick response and for explaining that.  That makes sense.  I'd like to understand why no granules can be ignored.

My understanding is that there is a bloom filter per block (consisting of, in my case, `1024 * 2` rows), with the default false positive rate of .025.  Is that understanding correct?  I would have guessed that most granules could be ignored, except for a few, where there is a false positive.  One additional factor is that these string arrays are kind of large (they have about 2000 strings on average).  Am I also correct to say that the false positive rate takes into account the size of the arrays?

**Comment by cangyin** [comment]
> My understanding is that there is a bloom filter per blo...

That's same as what I think.

Was the index 'bloom_filter_output' added before inserting data ?

Besides, for searching substrings or 'tokens' in string, use `tokenbf_v1` or `ngrambf_v1` index types.

**Comment by awitten1** [comment]
Do `tokenbf_v1` and `ngrambf_v1` work for arrays of strings?  It was added after, but I ran `ALTER TABLE test_table MATERIALIZE INDEX bloom_filter_output;` to materialize it.

**Comment by awitten1** [comment]
Actually it looks like `tokenbf_v1` is supported on string arrays.  Thanks!
