### ISSUE TITLE
Using variable name the same as column name

### ISSUE THREAD

**Issue by rejochandran** [ClickHouse/ClickHouse#46150]
Hi,
I have a table `mytable` and `mydate` is a column in it.
However, since the `SELECT` clause is dynamic, I need to pre-adjust the column with `addMinutes`. 
So, the column is added to the variable with the function such that in the event the column turns up in `SELECT` the variable is taken over than the actual value in the table.

`SELECT mydate FROM "mytable"`
> original value of `mydate` is returned

<br/>

`WITH addMinutes(mydate,300) AS mydate SELECT mydate FROM "mytable"`
> original value `mydate` is returned, expected to return variable value

The exact opposite happens; Even if the variable is mentioned (same name as the column), the actual column value overrides the `WITH` clause.

Do we have a workaround to use `WITH` clause variables with the same name as the columns in the table?

**Comment by DerekChia** [comment]
I think I know what you want to achieve.

Consider a table:
```
CREATE TABLE default.tbl
(
    `id` UInt32,
    `2022-10-01` UInt32,
    `2022-10-02` UInt32
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192
```

The following queries won't work:
```
WITH addDays(toDate('2022-10-01'), 1)::String as d
SELECT d FROM tbl

WITH toString(addDays(toDate('2022-10-01'), 1)) as d
SELECT d FROM tbl

WITH "2022-10-01" as d
SELECT toString(addDays(toDate(d), 1)) FROM tbl;
```

Only this works, and you want to dynamically generate the column name using `WITH`, correct?
```
WITH "2022-10-02" as d
SELECT d FROM tbl
```

**Comment by rejochandran** [comment]
Hey @DerekChia, thanks for the response :) 

Not exactly, let me re-phrase the issue with a similar example you mentioned above,

Consider this table:
```
CREATE TABLE default.tbl
(
    `id` UInt32,
    INSERT INTO default.tbl VALUES (1,toDateTime('2022-09-14T00:00:00')) Nullable(DateTime())
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192
```

Adding some data...
```
INSERT INTO default.tbl VALUES (1,toDateTime('2022-09-14T15:53:00'))
```

Querying to check...
```
SELECT created_date FROM default.tbl
```
Returns
| created_date        |
|---------------------|
| 2022-09-14 00:00:00 |

But, I have a scenario where the `SELECT` clause is dynamic and cannot apply any date functions and so, I try to override the column values with the same name as the column name such that when a the column is queried, it takes up the variable's (`WITH`) value than the actual column value

Say, I need to add a day to the  `created_date` every time its queried:
```
WITH addDays(created_date,1) as created_date SELECT created_date FROM default.tbl
```
this also returns
| created_date        |
|---------------------|
| 2022-09-14 00:00:00 |

If I rename the variable to something other than a column's name, the desired value shows up in the new variable, like so,
```
WITH addDays(created_date,1) as created_date_var SELECT created_date, created_date_var FROM default.tbl
```
| created_date        | created_date_var    |
|---------------------|---------------------|
| 2022-09-14 00:00:00 | 2022-09-15 00:00:00 |

Looks like the `SELECT` clause overrides the `WITH` clause if the name of column and variable respectively is the same.

**Comment by den-crane** [comment]
BTW, @kitaisreal 

```sql
CREATE TABLE t(a DateTime) ENGINE = Memory as select now();

WITH addDays(a,1) as a SELECT a FROM t;
┌───────────────────a─┐
│ 2023-02-08 18:21:39 │
└─────────────────────┘

WITH addDays(a,1) as a SELECT a FROM t settings allow_experimental_analyzer=1;

DB::Exception: Cyclic aliases for identifier 'a'. In scope WITH addDays(a, 1) AS a SELECT a FROM t SETTINGS allow_experimental_analyzer = 1. (CYCLIC_ALIASES)
```

**Comment by den-crane** [comment]
@rejochandran you can use  https://clickhouse.com/docs/en/sql-reference/statements/select/#replace

```sql
SELECT
    * REPLACE addDays(a, 1) AS a,
    t.a
FROM t
┌───────────────────a─┬───────────────────a─┐
│ 2023-02-09 18:21:39 │ 2023-02-08 18:21:39 │
└─────────────────────┴─────────────────────┘
```

**Comment by rejochandran** [comment]
Thank you @den-crane! works! 🎉 🎉
