### ISSUE TITLE
Add function `DATE_FORMAT` as a compatibility alias.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#46184]
**Use case**

Compatibility with MySQL.

**Describe the solution you'd like**

1. Make it a synonym of `formatDateTime`.
2. Add the support for `%i` and other missing format substitutions.
3. Fix the error code from ILLEGAL_COLUMN to a more appropriate one.

```
milovidov-desktop :) SELECT DATE_FORMAT(now(), '%Y-%m-%d %H:%i:%s')

SELECT DATE_FORMAT(now(), '%Y-%m-%d %H:%i:%s')

Query id: c24c519d-9f35-48a3-9ada-f9af8b4911a1


0 rows in set. Elapsed: 0.160 sec. 

Received exception:
Code: 46. DB::Exception: Unknown function DATE_FORMAT: While processing DATE_FORMAT(now(), '%Y-%m-%d %H:%i:%s'). (UNKNOWN_FUNCTION)

milovidov-desktop :) SELECT formatDateTime(now(), '%Y-%m-%d %H:%i:%s')

SELECT formatDateTime(now(), '%Y-%m-%d %H:%i:%s')

Query id: ab5ea92d-6026-4cc5-bdf9-6b8a8e8f77b4


0 rows in set. Elapsed: 0.002 sec. 

Received exception:
Code: 44. DB::Exception: Wrong syntax '%Y-%m-%d %H:%i:%s', unexpected symbol 'i' for function formatDateTime: While processing formatDateTime(now(), '%Y-%m-%d %H:%i:%s'). (ILLEGAL_COLUMN)

milovidov-desktop :)
```

**Comment by JakeBamrah** [comment]
Hey there! I am new to open source and I would like to get my feet wet. I think I would be able to give this a good shot.

After having a look, I believe all of the changes would take place in `src/Functions/formatDateTime.cpp`

**Comment by alexey-milovidov** [comment]
Thank you! Let's try.

> After having a look, I believe all of the changes would take place in src/Functions/formatDateTime.cpp

Yes.

**Comment by JakeBamrah** [comment]
Took me a little while to get my dev environment setup as I needed more space! :)

**Completed**
- Alias `formatDateTime` → `DATE_FORMAT`
- Add support for `%i` and `%r`
- Replace error code `ILLEGAL_COLUMN` → `NOT_IMPLEMENTED`

**TODO**
- Missing MySQL format substitutions: `a b c h i k l r s U v W X x`

Am I okay to add all of the above missing substitutions as part of this issue?

**Comment by alexey-milovidov** [comment]
Yes, it will be amazing!
