### ISSUE TITLE
build : ld.lld: error: unable to find library -lgcc_eh

### ISSUE THREAD

**Issue by githublaohu** [ClickHouse/ClickHouse#46189]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
ld.lld: error: unable to find library -lgcc_eh

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

OS：Linux open 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu22.04

flind gcc_eh :

roott@linux:/root/gcc-11.3.0/build$ sudo find /usr/lib -name "libgcc*"
/usr/lib/gcc/x86_64-linux-gnu/11/libgcc_s.so
/usr/lib/gcc/x86_64-linux-gnu/11/libgcc_eh.a
/usr/lib/gcc/x86_64-linux-gnu/11/libgcc.a
/usr/lib/x86_64-linux-gnu/libgccpp.so.1
/usr/lib/x86_64-linux-gnu/libgcc_eh.a
/usr/lib/x86_64-linux-gnu/libgccpp.so.1.4.1
/usr/lib/x86_64-linux-gnu/libgcc_s.so.1
/usr/lib/libgcc_eh.a

**Cmake version**
3.24.2

-DCMAKE_CXX_COMPILER_LAUNCHER=ccache 
-DCMAKE_BUILD_TYPE=Debug
 -GNinja 
-DENABLE_CLICKHOUSE_ALL=OFF 
-DENABLE_CLICKHOUSE_SERVER=ON 
-DENABLE_CLICKHOUSE_CLIENT=ON 
-DENABLE_LIBRARIES=OFF 
-DENABLE_UTILS=OFF 
-DENABLE_TESTS=ON 
-DUSE_ROCKSDB=ON 
-DENABLE_ROCKSDB=ON 
-DENABLE_JEMALLOC=ON

**Ninja version**
1.10.1

**Compiler name and version**
master -> remotes/origin/23.1

**Full cmake and/or ninja output**

/software/ide/clion/clion-2022.3.2/bin/cmake/linux/x64/bin/cmake --build /opensource/cpp-source/ClickHouse/build --target all -j 10
[0/2] Re-checking globbed directories...
[1/4007] Linking CXX executable contrib/llvm-project/llvm/bin/llvm-tblgen
FAILED: contrib/llvm-project/llvm/bin/llvm-tblgen 
: && /usr/bin/clang++ --target=x86_64-linux-gnu --sysroot=/opensource/cpp-source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/opensource/cpp-source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -g -O0 -g -gdwarf-4  -D_LIBCPP_DEBUG=0 --gcc-toolchain=/opensource/cpp-source/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/opensource/cpp-source/ClickHouse/build/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1 -no-pie -Wl,-no-pie -fno-pie    -Xlinker --no-undefined contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmMatcherEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmWriterEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/AsmWriterInst.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/Attributes.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CallingConvEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeEmitterGen.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenDAGPatterns.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenHwModes.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenInstruction.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenMapTable.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenRegisters.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenSchedule.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CodeGenTarget.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherGen.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcherOpt.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DAGISelMatcher.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DecoderEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DFAEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DFAPacketizerEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DirectiveEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DisassemblerEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/DXILEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/ExegesisEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/FastISelEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/GICombinerEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/GlobalISelEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InfoByHwMode.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InstrInfoEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/InstrDocsEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/IntrinsicEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/OptEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/OptParserEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/OptRSTEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/PredicateExpander.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/PseudoLoweringEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CompressInstEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RegisterBankEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/RegisterInfoEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SDNodeProperties.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SearchableTableEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SubtargetEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/SubtargetFeatureInfo.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/TableGen.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/Types.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/VarLenCodeEmitterGen.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86DisassemblerTables.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86FoldTablesEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86MnemonicTables.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86ModRMFilters.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/X86RecognizableInstr.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/WebAssemblyDisassemblerEmitter.cpp.o contrib/llvm-project/llvm/utils/TableGen/CMakeFiles/llvm-tblgen.dir/CTagsEmitter.cpp.o -o contrib/llvm-project/llvm/bin/llvm-tblgen  contrib/llvm-project/llvm/lib/libLLVMSupportd.a  contrib/llvm-project/llvm/lib/libLLVMTableGend.a  contrib/llvm-project/llvm/lib/libLLVMTableGenGlobalISeld.a  contrib/llvm-project/llvm/lib/libLLVMTableGend.a  contrib/llvm-project/llvm/lib/libLLVMSupportd.a  contrib/llvm-project/llvm/lib/libLLVMDemangled.a  base/glibc-compatibility/libglibc-compatibilityd.a  base/glibc-compatibility/memcpy/libmemcpyd.a  base/glibc-compatibility/libglibc-compatibilityd.a  base/glibc-compatibility/memcpy/libmemcpyd.a  -Wl,--start-group  contrib/libcxx-cmake/libcxxd.a  contrib/libcxxabi-cmake/libcxxabid.a  -lgcc_eh  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-14/lib/clang/14.0.0/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
ld.lld: error: unable to find library -lgcc_eh
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[10/4007] Building CXX object contrib/llvm-project/llvm/lib/MC/CMakeFiles/LLVMMC.dir/MCELFStreamer.cpp.o
ninja: build stopped: subcommand failed.

**Comment by alexey-milovidov** [comment]
Do you use the original, unmodified source code of ClickHouse?
Then you can compile exactly as in the build log from CI:
https://s3.amazonaws.com/clickhouse-builds/0/7cf71d1f828c2ac3a0a9491abdb4c580efc91050/clickhouse_build_check/report.html

You don't have to build ClickHouse.

Install the latest ClickHouse version as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by githublaohu** [comment]
@alexey-milovidov 
Clickhouse is an excellent OALP database. Want to read the source code. Through click, you only want to reserve two executable files, service and client. This will shorten the compilation time a lot.

**Comment by cangyin** [comment]
> ... reserve two executable files, service and client

Actually, clickhouse-server and clickhouse-client are just symbolic links to the single `clickhouse` executable.

**Comment by githublaohu** [comment]
All executable files are linked to clickhouse. When compiling, if only service and client are needed, there are only more than 6000 compiled files, and if all are compiled, there are 11200.

**Comment by githublaohu** [comment]
@alexey-milovidov  @cangyin  @bretthoerner   
If you want to contribute other message middleware in clickhouse, please help me, thank you

**Comment by alexey-milovidov** [comment]
This is strange because we don't link with the `gcc_eh` library in our build process.
We use LLVM's `libunwind` instead.

This error might happen if you use modified CMakeLists or if something is wrong with the build configuration.
You can check the build logs from the CI and ensure that everything is exactly the same.

**Comment by TheUnity42** [comment]
Good Morning, I have been encountering this same issue repeatedly over the last few days. I have tried multiple machines, but currently, only my Fedora laptop can build (albeit slowly). Could you point me in the right direction for those CI logs?

**Comment by azat** [comment]
@alexey-milovidov actually you can compile clickhouse without libuwind, by using `-DENABLE_LIBRARIES=OFF` or `-DUSE_UNWIND=OFF`, but I think that there is not a lot of sense in this nowadays, so it is better to simply remove `gcc_eh` support - #49438

**Comment by azat** [comment]
@TheUnity42 `-DUSE_UNWIND=ON` should fix the issue for you
