### ISSUE TITLE
JSON columns should handle arrays, too

### ISSUE THREAD

**Issue by candiduslynx** [ClickHouse/ClickHouse#46190]
Let's consider the following table:
```SQL
CREATE TABLE `tbl` (a String, b Object('json')) ENGINE=MergeTree ORDER BY (a)
```
Then the following is true:
* We can insert complex JSON data:
  ```sql
  INSERT INTO tbl VALUES ('a', '{"x":{"y":"z"}}')
  ```
* We can't insert array of JSON data:
  ```sql
  INSERT INTO tbl VALUES ('b', '[{"x":{"y":"z"}}]')
  ```

**Comment by candiduslynx** [comment]
@alexey-milovidov could you please share a bit more detail how this feature is enabled & what version of ClickHouse supports it?

**Comment by Slach** [comment]
@candiduslynx look to `st-wontfix` label
and look https://github.com/ClickHouse/ClickHouse/issues/54864

**Comment by candiduslynx** [comment]
@Slach, thanks for pointing that out.

As for the #54864, there's no mention of array of JSON values propagated there (although, `array(string)` is explicitly mentioned). I hope it won't be forgotten in the implementation.
