### ISSUE TITLE
deprecation of `default_database_engine` setting breaks ON CLUSTER queries in case of new replicas

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#46206]
**Describe the issue**
Cluster with `default_database_engine` setting set to Ordinary.
After upgrade to 22.8 and add of additional ClickHouse replicas.
New replica will use Atomic database engine by default for `default` database or any other DB.
Which will cause issue during ON CLUSTER queries, because Ordinary database engine can't replicate CREATE TABLE statements with table UUID.

**Additional context**
PR which introduced breaking change https://github.com/ClickHouse/ClickHouse/pull/38335

**Comment by tavplubix** [comment]
> Which will cause issue during ON CLUSTER queries, because Ordinary database engine can't replicate CREATE TABLE statements with table UUID.

AFAIK it can. Could you provide a reproducible example, please? 

https://github.com/ClickHouse/ClickHouse/blob/9b908a0be0bcf2b25ea289d50b250e80b31c43df/src/Interpreters/InterpreterCreateQuery.cpp#L1043-L1051

**Comment by UnamedRus** [comment]
```
CREATE TABLE default.test UUID '37b73969-dc35-4420-bf7e-2afd8eedd702'
(
    `key` UInt32
)
ENGINE = MergeTree
ORDER BY key
SETTINGS index_granularity = 8192

Query id: 16317bf8-97a8-4c43-ad24-cf8132705830


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 23.1.3):
Code: 80. DB::Exception: Received from localhost:9000. DB::Exception: Table UUID specified, but engine of database default is not Atomic. (INCORRECT_QUERY)
```
