### ISSUE TITLE
Document stream log compression

### ISSUE THREAD

**Issue by Tomatosoup97** [ClickHouse/ClickHouse#46203]
**Describe the issue**

I wanted to set up log compression, and as I didn't find relevant information in docs I started googling around and I came across this issue: https://github.com/ClickHouse/ClickHouse/issues/23860, and then went on to this merged to master pull request: https://github.com/ClickHouse/ClickHouse/pull/29219

which does exactly what I want - implements log compression via LZ4.

Based on this line `if (config.getRawString("logger.stream_compress", "false") == "true")`
I tried to set it up via `<stream_compress>` setting in `<logger>`, and it all worked flawlessly - logs are compressed!

There is no mention of this option in [logger docs](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-logger), even tho this change was merged over a year ago. Is there any particular reason for that? Is this change experimental and not advised to use, or rather is it just a missing entry in the docs? I'm asking as I'm a bit hesitant to use undocumented feature on production.

**Comment by DanRoscigno** [comment]
Thanks @Tomatosoup97
