### ISSUE TITLE
REPL client for clickhouse-keeper

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#46229]
**Use case**

It would be nice to have an embedded REPL client for `clickhouse-keeper` similar to `clickhouse-client` with all the basic commands including recursive deletion of the nodes. Additionally, in the future the functionality could be extended with adding new request types to keeper itself. 
We can even support multi-requests with some syntax like `BEGIN MULTIREQUEST` or `BEGIN TRANSACTION` and similar commands for `COMMIT`. But better to start with something simple and then iterate.

**Describe the solution you'd like**

Take a look how to `clickhouse-local` and `clickhouse-client` are written using replxx. And use our internal [ZookeeperClient class](https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ZooKeeper/ZooKeeper.h)  for making requests. Tricky part is that there is a possibility to build a standalone keeper (a very tiny binary) and this client should be also available there.

**Comment by azat** [comment]
FWIW for now I'm using `zk-shell`, it has recursive removal (`rmr`), `grep`, `find` - in other words "everything you need", to dig into keeper (especially with some CI artifacts).

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/37780
