### ISSUE TITLE
Implement `system.server_settings`

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#46231]
**Use case**

We already have `system.settings` for user level settings that can be changed in a scope of connection or query and `system.merge_tree_settings` for table level settings that could be specified in CREATE query. 

But we also have some settings that should be placed in top level config and server wide. For example `mark_cache_size` or `mark_cache_policy`. There is no way to see how a particular server is configured using SQL query without an access to configuration file.

**Describe the solution you'd like**

Use the same approach and the same infrastructure (take a look at `Core/Settings.h` file). Then inside `Server.cpp` during startup all such settings should be loaded from config file at once and then all the code should use settings object instead of manually loading them from config.
The system table itself should be implemented similar to existing ones. Of course, we any sensitive information specified in the configuration should be excluded from it.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/7663

**Comment by kssenii** [comment]
Related: https://github.com/ClickHouse/ClickHouse/pull/35878

**Comment by nikitamikhaylov** [comment]
Oops.
