### ISSUE TITLE
toStartOfDay with timezone returns another timezone

### ISSUE THREAD

**Issue by lee3164** [ClickHouse/ClickHouse#46237]
(you don't have to strictly follow this form)

**Describe the unexpected behavior**
toStartOfDay method with timezone returns an incorrect result sometimes. 

**How to reproduce**
incorrect result
![image](https://user-images.githubusercontent.com/8246969/217847527-6156861c-5680-489f-96d7-c4b8942e74aa.png)

correct result
![image](https://user-images.githubusercontent.com/8246969/217847584-ae5a3066-9862-46af-9dfe-f6dcee0f493c.png)

* Which ClickHouse server version to use
23.1.3.5

**Comment by den-crane** [comment]
Question about JDBC https://github.com/ClickHouse/clickhouse-jdbc/issues

**Comment by lee3164** [comment]
![image](https://user-images.githubusercontent.com/8246969/217855507-63659ad6-fa75-4b0e-b124-f6997c0aa3bc.png)
I used clickhouse-client to get the timestamp and it was incorrect also.

![image](https://user-images.githubusercontent.com/8246969/217855980-00d32917-138f-43b0-9e3f-9261cd2e8711.png)
1 hour is lost

**Comment by Algunenano** [comment]
'Europe/London' is not the same as GMT:

![image](https://user-images.githubusercontent.com/664253/217857831-0d3af550-4ae5-4ec2-af55-2b3b618c9ce1.png)

**Comment by lee3164** [comment]
> 'Europe/London' is not the same as GMT:
> 
> ![image](https://user-images.githubusercontent.com/664253/217857831-0d3af550-4ae5-4ec2-af55-2b3b618c9ce1.png)

Thanks, But how to explain my first two images above, when I used '2022-03-27', the result was in utc timezone, but '2022-03-28' was in '+1' timezone

**Comment by lee3164** [comment]
And in my code, I used debug mode and found it was the same as the images listed above, it was so confusing.

![image](https://user-images.githubusercontent.com/8246969/217861753-5678002f-e6c1-4aa2-b9f8-702567f7d197.png)

**Comment by Algunenano** [comment]
https://www.timeanddate.com/time/change/uk/london?year=2022

```
27 Mar
Forward 1 hour

27 Mar 2022 - Daylight Saving Time Started
When local standard time was about to reach
Sunday, 27 March 2022, 01:00:00 clocks were turned forward 1 hour to
Sunday, 27 March 2022, 02:00:00 local daylight time instead.
```

London changed timezones on `27 March 2022, 02:00:00`.
