### ISSUE TITLE
Move unsupported conditions of INNER JOIN from ON to WHERE.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#46254]
**Use case**

```
SELECT * FROM t1 INNER JOIN t2 ON t1.x = t2.y AND wtf(xyz)
```

should be translated to

```
SELECT * FROM t1 INNER JOIN t2 ON t1.x = t2.y WHERE wtf(xyz)
```

And

```
SELECT * FROM t1 INNER JOIN t2 ON wtf(xyz)
```

should be translated to

```
SELECT * FROM t1 CROSS JOIN t2 WHERE wtf(xyz)
```

**Describe the solution you'd like**

AST-based transformation.

**Comment by ucasfl** [comment]
Do we need add a setting to control these optimization?

**Comment by alexey-milovidov** [comment]
Let's add a setting just in case (if the implementation will break something, it will be easy to disable it).
