### ISSUE TITLE
Non-atomical insertion in Buffer tables

### ISSUE THREAD

**Issue by antonivakin** [ClickHouse/ClickHouse#46258]
We're writing to the buffer table and concurrently reading from it with period 200ms using insertion_time to filter the data that was already selected. We've expected that there won't be any data misses due to write atomicity. Actually, we've seen that some data is not selected within the same insertion_time.

**Describe what's wrong**

During insertions in Buffer table, sometimes select from same table miss previously inserted data.

**Does it reproduce on recent release?**

Yes, checked 23.1.3.5 and 22.4.5.9

**How to reproduce**

We are going to insert batches and do select from Buffer table concurently.
(select: ```SELECT insertion_time, count() FROM entity_buffer GROUP BY insertion_time ORDER BY insertion_time DESC LIMIT 20```)

Creating tables:
```
CREATE TABLE entity_log (
    name                    String,
    sender_time             DateTime64(9),
    value                   Float64,
	insertion_time          DateTime64(9) DEFAULT now64(9)

)
    ENGINE = MergeTree
    PARTITION BY toYYYYMM(sender_time)
    ORDER BY (name, sender_time);
	
ALTER TABLE entity_log ADD INDEX insertion_time_index insertion_time TYPE minmax GRANULARITY 1;

CREATE TABLE entity_buffer AS entity_log
    ENGINE = Buffer(
        currentDatabase(), entity_log,
        /* num_layers */ 1,
        /* min_time/max_time (sec) */ 1, 1,
        /* min_rows/max_rows */ 10000, 1000000,
        /* min_bytes/max_bytes */ 10000000, 100000000
    );
```

script to create datasets:
```
get_rows.sh

#!/bin/bash
for i in $(seq 1 $1); do
    t=$(date +"%T.%9N")
    echo "some_name, '2023-02-09 $t', $i.0";
done
```

create two datasets (with 10K and 50K rows):
```
./get_rows.sh 10000 > 10K.csv
./get_rows.sh 50000 > 50K.csv
```

script to insert batches (repeat N times: (insert 50K, sleep 200ms, insert 10K, sleep)):
```
inserter.sh

#!/bin/bash
for i in $(seq 1 $1); do
    cat 50K.csv | clickhouse-client --query="INSERT INTO entity_buffer (name, sender_time, value) FORMAT CSV"
    sleep 0.2
    cat 10K.csv | clickhouse-client --query="INSERT INTO entity_buffer (name, sender_time, value) FORMAT CSV"
    sleep 0.2
done
```

script to do select () and put results into files (1.txt, 2.txt, ...) with 200ms interval
```
fetcher.sh

#!/bin/bash
for i in $(seq 1 $1); do
    sleep 0.2
    clickhouse-client --query="select insertion_time, count() from entity_buffer group by insertion_time order by insertion_time desc limit 20 INTO OUTFILE '$i.txt'"
done
```

running:
run them in different sessions parallel:
```
./inserter.sh 30
```
```
./fetcher.sh 50
```

now we have 50 text files. Usualy some of them has problem (sometimes they are all good, need to repeat). In my case:
```
19.txt

2023-02-10 08:00:37.886877102	50000
2023-02-10 08:00:37.657374524	10000
2023-02-10 08:00:37.413039756	50000
2023-02-10 08:00:37.183678611	10000
2023-02-10 08:00:36.939817511	50000
2023-02-10 08:00:36.710102062	10000
2023-02-10 08:00:36.464408501	50000
2023-02-10 08:00:36.202912830	10000
...
```
```
20.txt

2023-02-10 08:00:38.130632106	10000
//// here should be more data!!!
2023-02-10 08:00:35.961135110	50000
2023-02-10 08:00:35.732208464	10000
2023-02-10 08:00:35.488500068	50000
2023-02-10 08:00:35.259793873	10000
2023-02-10 08:00:35.018389092	50000
2023-02-10 08:00:34.789574883	10000
2023-02-10 08:00:34.548661213	50000
...
```
```
21.txt

2023-02-10 08:00:38.130632106	10000
2023-02-10 08:00:37.886877102	50000
2023-02-10 08:00:37.657374524	10000
2023-02-10 08:00:37.413039756	50000
2023-02-10 08:00:37.183678611	10000
2023-02-10 08:00:36.939817511	50000
2023-02-10 08:00:36.710102062	10000
2023-02-10 08:00:36.464408501	50000
...
```

**Expected behavior**

Expected, that in new selects we can see data that was in previous result, but in result in 20.txt some rows wasn't selected

**Additional context**

Setting "settings optimize_read_in_order=0" in select (due to https://github.com/ClickHouse/ClickHouse/issues/42226) doesn't change behaviour

**Comment by loyd** [comment]
Ok, `wontfix`. Brilliant. So, consumers can skip inserted data literally for no reason, even after receiving `Ok.`. Even possible duplication of data will be a better solution. Btw, I see no mention of this behavior in the documentation.

So, there is no way to get streaming through CH with low latency (~100-200ms) without seriously increasing the load on the background merger, innit?

**Comment by loyd** [comment]
I think it's related to another closed issue, https://github.com/ClickHouse/ClickHouse/issues/29994. That problem was "fixed" by using only 1 layer, but it just became less likely to be reproduced.

**Comment by alexey-milovidov** [comment]
@loyd The `Buffer` table engine is independent of the target table's engine. For example, MergeTree does not use long locks on INSERT (only short locks inside data structures), allowing it to run many concurrent INSERTs and SELECTs. The table engine's interface does not allow the co-operation of locks between tables.

With asynchronous INSERTs, the need for Buffer tables is much less; that's why won't fix.
