### ISSUE TITLE
Weird pthread_cond_wait causing performance degrade from time to time

### ISSUE THREAD

**Issue by spff** [ClickHouse/ClickHouse#46257]
**Describe the situation**
Weird pthread_cond_wait when running `insert into select`. 

I got several clickhouse servers with same config(hardware spec/os/clickhouse-server version & config), they're processing pre-sharded data in parallel (8 clickhouse-server instances) in the below order.  
1. create table_a & view_a  
2. insert into table_a  
3. for each `task` in tasks:  
   3.1 create a temp_table & a `SummingMergeTree() PARTITION BY intDiv(time, 3600)`  
   3.2 `insert into temp_table select ... from view_a`  
   3.3 `insert into SummingMergeTree select from temp_table`  
   3.4 `drop table temp_table`  
   3.5 backup SummingMergeTree to s3  
   3.6 drop SummingMergeTree  

The full steps 1-3 will be executed periodically (no interlace). During step 3, multiple tasks will be dynamically dispatched.  
Sometimes, 2 specific (shard 6 & 7) clickhouse instances (out of 8) encountered this performance issue in step 3.2.  
That is, one step 3.2 supposed to be finished in 10 seconds began to be finished in 1500-1600 seconds. And all the rest tasks' step 3.2 in step 3 started to be finished in 1500-1600s. As the screenshot shown, the AVG CPU utilization is being 1 core (12.5% of 8 cores), and I found the weird pthread_cond_wait in trace_log.  
I've checked that there're no data skew, so each clickhouse instances should finish all the tasks with the similar amount of time.  

**How to reproduce**
* Which ClickHouse server version to use
   Ubuntu 20.04.5 LTS 22.11.1 revision 54460
* Which interface to use, if matters
ssl tcp, via python clickouse-driver(multple connections over gevent).  

* Non-default settings, if any
   {'join_use_nulls':'1','max_memory_usage':'19327352832','max_partitions_per_insert_block':'2500'}

* `CREATE TABLE` statements for all tables involved  
```
             CREATE TABLE table_a (...)
            ) ENGINE = MergeTree()
            order by tuple()
            settings index_granularity = 8192000, index_granularity_bytes = 0
            
            CREATE VIEW view_a AS SELECT
            ...
            FROM table_a

            CREATE TEMPORARY TABLE IF NOT EXISTS Mt1hwKPURnu029k0FrJRdA (...)
           
            CREATE TABLE task_a_51p44lpQRZGXMIjNdydsYw_7_0 (...)
                        ENGINE = SummingMergeTree()
                        PARTITION BY intDiv(time, 3600)
                        ORDER BY (...)
```            

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

* Queries to run that lead to slow performance
            step 3.2
            ```
             INSERT INTO Mt1hwKPURnu029k0FrJRdA
            (...)
            select
                ...
            from view_a
            settings max_memory_usage = 19327352832
            ```

**Expected performance**            

![grafana](https://user-images.githubusercontent.com/9722730/218053917-37c0e9fd-8377-4993-bd74-4ac8d7bc971e.png)
![query_screenshot](https://user-images.githubusercontent.com/9722730/218053933-14d3ea59-5a7e-41b8-9c67-a64301b43e48.png)
  
**Additional context**

**Comment by spff** [comment]
Hi @alexey-milovidov I understand there are so many open issues which may have higher priority, is there anything I can do to let someone help on this issue?

**Comment by alexey-milovidov** [comment]
`pthread_cond_wait` represents threads waiting for an event. This does not show any problem with performance.
Typically you have some threads working and others coordinating them and waiting most of the time.

To check where the CPU time is being spent, collect the flamegraphs only for `trace_type` = `CPU`.

> I found the weird pthread_cond_wait in trace_log

It is totally normal.

**Comment by alexey-milovidov** [comment]
We need to continue comparing the flame graphs between the servers. Also, let's compare the metrics from the system.metric_log and system.asynchronous_metric_log. The metrics can be also shown on a dashboard (available at `https://your-server:8123/dashboard`)

**Comment by spff** [comment]
After we applied `SYSTEM STOP MERGES` to most of the tables we're using, this issue has been eased(but not fully resolved).
