### ISSUE TITLE
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet (BUG)

### ISSUE THREAD

**Issue by a58457432** [ClickHouse/ClickHouse#4625]
insert into leaf_cert select * from leaf_cert_tmp;

leaf_cert_tmp  has1000000 rows， when insert  leaf_cert  , error:

Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, ::1

Connecting to database ct at localhost:9000 as user default.
Code: 210. DB::NetException: Connection refused (localhost:9000, ::1)

**Comment by a58457432** [comment]
it is a bug

**Comment by filimonov** [comment]
It is bug. We need more information - server version, table structure, and stacktrace, 

You can find stacktrace in /var/log/clickhouse-server/clickhouse-server.err.log

**Comment by den-crane** [comment]
It could be OOM due lack of memory because of insert into a wide table or merge of a heavy blob column or not related to insert.

**Comment by quinge10** [comment]
Have the same error on both ClickHouse 18.16.1 and ClickHouse 19.1.6.
But an error occurs when we select from table with a large amount of rows (~60M). We try to use MergeTree and ReplacingMergeTree and error appears in both cases.

We found on this resource that it depends on SSE. https://github.com/yandex/ClickHouse/issues/1617
Is it true? We have SSE 2 whereas clickhouse use SSE 4.2. Could this be the main problem?
Have 16GB RAM.

P.S. This error is not logged.

```SQL
CREATE TABLE Tab (
    t_id    Int32,
    c2      Int32,
    c3      Int32,
    c4      String,
    c5      Decimal(20, 15),
    c6      Int32,
    c7      Int32,
    c8      Int32,
    c9      String,
    c10     Int32,
    c11     Decimal(15, 2),
    c12     Int32,
    c13     Int32,
    c14     String,
    c15     DateTime,
    c16     DateTime,
    c17     Decimal(15, 2),
    c18     UInt8,
    c19     Int32,
    c20     UInt8,
    c21     DateTime,
    c22     UInt8,
    c23     String,
    c24     Int32,
    c25     String,
    c26     Int32,
    c27     Int64,
    c28     Decimal(15, 2),
    c29     UInt8,
    rv      UInt64
) ENGINE = ReplacingMergeTree(rv)
  PARTITION BY intDiv(t_id, 1000000)
  ORDER BY (t_id)
  SETTINGS  index_granularity = 8192;

SELECT  tupleElement(h.t, 1),
        tupleElement(h.t, 2),
        tupleElement(h.t, 3),
        tupleElement(h.t, 4),
        tupleElement(h.t, 5),
        tupleElement(h.t, 6),
        tupleElement(h.t, 7),
        tupleElement(h.t, 8),
        tupleElement(h.t, 9),
        tupleElement(h.t, 10),
        tupleElement(h.t, 11),
        tupleElement(h.t, 12),
        tupleElement(h.t, 13),
        tupleElement(h.t, 14),
        tupleElement(h.t, 15),
        tupleElement(h.t, 16),
        tupleElement(h.t, 17),
        tupleElement(h.t, 18),
        tupleElement(h.t, 19),
        tupleElement(h.t, 20),
        tupleElement(h.t, 21),
        tupleElement(h.t, 22),
        tupleElement(h.t, 23),
        tupleElement(h.t, 24),
        tupleElement(h.t, 25),
        tupleElement(h.t, 26),
        tupleElement(h.t, 27),
        tupleElement(h.t, 28),
        tupleElement(h.t, 29)
FROM    (
            SELECT  argMax((t_id,
                            c2,
                            c3,
                            c4,
                            c5,
                            c6,
                            c7,
                            c8,
                            c9,
                            c10,
                            c11,
                            c12,
                            c13,
                            c14,
                            c15,
                            c16,
                            c17,
                            c18,
                            c19,
                            c20,
                            c21,
                            c22,
                            c23,
                            c24,
                            c25,
                            c26,
                            c27,
                            c28,
                            c29),
                            rv) t
            FROM    Tab
            GROUP BY
                t_id
            ORDER BY
                t_id
            LIMIT 100
        ) h
```

Stack trace:
0. /usr/lib/x86_64-linux-gnu/libclickhouse.so.18.16(StackTrace::StackTrace()+0x16) [0x7f4e23729406]
1. /usr/lib/x86_64-linux-gnu/libclickhouse.so.18.16(+0x36f3572) [0x7f4e25671572]
2. /usr/lib/x86_64-linux-gnu/libclickhouse.so.18.16(+0x375063c) [0x7f4e256ce63c]
3. /usr/lib/x86_64-linux-gnu/libclickhouse.so.18.16(+0x37531ed) [0x7f4e256d11ed]
4. /usr/lib/x86_64-linux-gnu/libclickhouse.so.18.16(DB::Connection::receivePacket()+0x2e0) [0x7f4e25329e00]
5. clickhouse-client(+0x39b73) [0x561d20cb3b73]
6. clickhouse-client(+0x3bca3) [0x561d20cb5ca3]
7. clickhouse-client(+0x3e4af) [0x561d20cb84af]
8. clickhouse-client(+0x3ec2c) [0x561d20cb8c2c]
9. clickhouse-client(+0x40ead) [0x561d20cbaead]
10. clickhouse-client(+0x194f5) [0x561d20c934f5]
11. /usr/lib/libPocoUtil.so.60(Poco::Util::Application::run()+0x31) [0x7f4e2115afe1]
12. clickhouse-client(+0x3431e) [0x561d20cae31e]
13. /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f4e202b809b]
14. clickhouse-client(+0x1982a) [0x561d20c9382a]

**Comment by andrewrbe** [comment]
My logs:
https://gist.github.com/andrewrbe/42bbe8792b5450957456a6aa486d33c5

**Comment by filimonov** [comment]
@andrewrbe can you create a separate issue?

**Comment by andrewrbe** [comment]
It's prestable version. The issue was with table which i don't use any more

**Comment by filimonov** [comment]
Prestable version should not segfault. That case should be checked
