### ISSUE TITLE
MergeTreeBackgroundExecutorDB: No such file or directory. (FILE_DOESNT_EXIST)

### ISSUE THREAD

**Issue by bj1116** [ClickHouse/ClickHouse#46255]
<Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 107. DB::ErrnoException: Cannot open file /var/lib/clickhouse/data/default/log/tmp_merge_202208_6806656_8536086_61_7868164/partition.dat, errno: 2, strerror: No such file or directory. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

**Comment by tavplubix** [comment]
Please follow [this](https://github.com/ClickHouse/ClickHouse/blob/master/.github/ISSUE_TEMPLATE/85_bug-report.md) template and provide some diagnostic info/logs/steps to reproduce if you'd like to report an issue.
