### ISSUE TITLE
MaterializedMySQL (unsupported feature) MySQLParser bad handling of TRUNCATE queries 

### ISSUE THREAD

**Issue by brissonwilliam** [ClickHouse/ClickHouse#46251]
**Describe what's wrong**

TRUNCATE queries in mysql binlogs are not always parsed properly, causing the replication to break.

In mysql, the TABLE keyword, unlike the DROP statement, is not required. Clickhouse is not properly handling binlog events where TRUNCATE is not followed by TABLE keyword (not the actual table).

I think I found where the issue is in the code. In DB::MySQLParser::ParserDropQuery::parseImpl at line 47, it looks like the parser is expecting the work TABLE to be present alongside TRUNCATE, or else it's skipped and clickhouse throws a syntax error.

![image](https://user-images.githubusercontent.com/23560940/217961933-086523e7-dbb2-4e5d-8168-dc1b93a250ed.png)

For example, the following binlog events are causing parsing errors and my replication to break.
```
*************************** 5. row ***************************
   Log_name: binlog.000156
        Pos: 64887863
 Event_type: Query
  Server_id: 1
End_log_pos: 64887995
       Info: use `velstore`; create table test(i int primary key) /* xid=1141038 */


*************************** 12. row ***************************
   Log_name: binlog.000156
        Pos: 64888355
 Event_type: Query
  Server_id: 1
End_log_pos: 64888451
       Info: use `velstore`; TRUNCATE test /* xid=1141040 */

```

**Expected behavior**

The parser should not fail and replication shouldn't break on `TRUNCATE mytable_name` (without the TABLE keyword) when parsing binlogs. The TABLE keyword should not cause an ignore() to skip, that condition should be removed. If clickhouse requires that keyword for queries to be executed, it should probably be injected instead.

I believe this shouldn't be too hard to fix, I think I found the exact issue in the code. Though, I am not setup to compile c++ or build and test clickhouse. I would greatly appreciate it if someone could do this fix!

**Does it reproduce on recent release?**

Yes, I'm on ClickHouse server version 23.1.3 revision 54461.

**Error logs**

```
2023.02.03 18:25:49.863827 [ 27627 ] {} <Error> MaterializedMySQLSyncThread: Code: 538. DB::Exception: Cannot parse MySQL drop query.: While executing MYSQL_QUERY_EVENT. The query: TRUNCATE analytics_invoices_ln_acctime. (MYSQL_SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xddb0df5 in /usr/bin/clickhouse
1. ? @ 0x9b06eb6 in /usr/bin/clickhouse
2. DB::ParserExternalDDLQuery::parseImpl(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x14d62abc in /usr/bin/clickhouse
3. DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x14d401ce in /usr/bin/clickhouse
4. DB::ParserQuery::parseImpl(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x14d5f3e9 in /usr/bin/clickhouse
5. DB::IParserBase::parse(DB::IParser::Pos&, std::__1::shared_ptr<DB::IAST>&, DB::Expected&) @ 0x14d401ce in /usr/bin/clickhouse
6. DB::tryParseQuery(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, unsigned long, unsigned long) @ 0x14d9117e in /usr/bin/clickhouse
7. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, unsigned long, unsigned long) @ 0x14d9227a in /usr/bin/clickhouse
8. ? @ 0x138094fc in /usr/bin/clickhouse
9. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13808f2d in /usr/bin/clickhouse
```

**How to reproduce**
In mysql 
```
CREATE DATABASE test;
CREATE TABLE test.test(i int primary key);
INSERT INTO test.test VALUES(1);
```

Then, in clickhouse
```
SET allow_experimental_database_materialized_mysql = 1;

CREATE DATABASE replica
ENGINE = MaterializedMySQL('127.0.0.1:3306', 'test', 'username', 'pass');
```

Wait for replication to successfully build

Back to mysql 
```
USE test;
TRUNCATE test;
```

See clickhouse logs. It should have the query parsing error in there.

**Comment by subkanthi** [comment]
This seems to be fixed and truncates the table in ClickHouse, `TRUNCATE <table>` gets translated to 
```
2023.07.23 09:36:55.104149 [ 92139 ] {4da4625f-07bc-4e9b-a90a-2473e89b39a5} <Debug> executeQuery: (internal) /* Rewritten MySQL DDL Query */ TRUNCATE TABLE IF EXISTS mysql.test1 (stage: Complete)
```
