### ISSUE TITLE
Top N elements group by time

### ISSUE THREAD

**Issue by sundarv85** [ClickHouse/ClickHouse#4628]
Following is a sample schema

```
{
    name String,
    dateTime String,
    ....
    value UInt32
}
```

We would like to group them by timeseries. However, we are interested only in the top 5 elements with the highest value sum. 

```
SELECT any(name),
       sum(value)
FROM TABLE
WHERE name IN
    (SELECT name
     FROM TABLE
     GROUP BY name
     ORDER BY sum(value) DESC
     LIMIT 5)
GROUP BY name,
         toRelativeMinuteNum(dateTime)
```

The above gives the top 5 elements in the `IN` call and which are then used to again be grouped by name with the time bucket.

However, we would also like to get the calculated internal `sum(value)` also separately. So

```
SELECT any(name),
       sum(value),
  (SELECT name
   FROM TABLE
   GROUP BY name
   ORDER BY sum(value) DESC
   LIMIT 5) AS topSumNames
FROM TABLE
WHERE name IN topSumNames
GROUP BY name,
         toRelativeMinuteNum(dateTime)
```

This above fails with the error 
```
DB::Exception: Scalar subquery returned more than one row
```

Questions:

1. How to get the internal sub query value also in the select output
2. Is there a better way to perform this top 5 elements

The `LIMIT BY clause` is not working, when we put in the `dateTime` in the grouping.

**Comment by den-crane** [comment]
bad
```
SELECT name, toRelativeMinuteNum(dateTime) r,  ss, sum(value)
FROM TABLE inner join (SELECT name, sum(value) ss FROM TABLE GROUP BY name ORDER BY ss DESC LIMIT 5) using name
GROUP BY name, ss, r
```

better

```
create temporary table TX as 
SELECT name, sum(value) ss FROM TABLE GROUP BY name ORDER BY ss DESC LIMIT 5;

SELECT name, toRelativeMinuteNum(dateTime) r,  ss, sum(value)
FROM TABLE inner join (SELECT name, sum(value) ss FROM TX) using name
WHERE name in (select name from TX)
GROUP BY name,ss, r;

```

**Comment by sundarv85** [comment]
Thanks @den-crane. The INNER JOIN did the trick.

Could you explain more the difference between having a direct `SELECT` in the inner join, vs the `temporary table`. 

The issue is - this `sum(value)` and order changes based on the time range (1d or 1M) that is being queried. So we could not create a table that could cover various time ranges. With the `temporary table`, do you suggest to create the temporary table everytime a query is about to be executed? Also, how to make this temporary table work for parallel queries for different time ranges..

**Comment by den-crane** [comment]
> Could you explain more the difference between having a direct `SELECT` in the inner join, vs the `temporary table`. Why the former is `bad` while the other one is `better`

I had an idea that a filter `WHERE name in (select name from TX)` makes the query faster but now I am not so sure, because perhaps `using name` do the same in the *bad* query.
Though if you have `index` by name column it can be much faster with `WHERE name in `.
Check the speed and processed rows statistics on real data.

**Comment by blinkov** [comment]
@sundarv85, do you have any further questions?

**Comment by sundarv85** [comment]
Thanks @blinkov. No questions anymore. It worked.
