### ISSUE TITLE
MVs that depend on Views don't error or work when View gets deleted

### ISSUE THREAD

**Issue by fionera** [ClickHouse/ClickHouse#46305]
**Describe what's wrong**
When you create a MV that selects from a normal view and there the view afterwards it will create no error but also wont prevent you from deleting it. After a restart there is no error in the logs.

**Does it reproduce on recent release?**
Happens on 22.9.7.34 and 23.2.1.609 (I only tested these)

**How to reproduce**

1. create view that reads from a streaming table like kafka
2. create a mv that reads that view
3. delete original view

**Expected behavior**
Either an error in the logs or block of view deletion

**Error message and/or stacktrace**
-

**Additional context**
I would understand this if the MV inlines all other views into itself but I can't tell since the system table also only shows a `select * from <view>` as definition for the MV

**Comment by fionera** [comment]
This setup doesnt work at all apparently. I just noticed that the MV does not receive any data in my setup

**Comment by fionera** [comment]
shouldn't the creation of such MVs be blocked or throw an exception?

**Comment by den-crane** [comment]
It's a complicated question. Upon a mat view creation is not that easy to deduce it.
