### ISSUE TITLE
While executing BinaryRowInputFormat

### ISSUE THREAD

**Issue by JeasGo** [ClickHouse/ClickHouse#46318]
exception {
  code: 32
  name: "DB::Exception"
  display_text: "DB::Exception: Attempt to read after eof: While executing BinaryRowInputFormat"
  stack_trace: "0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xddb0cd5 in /usr/bin/clickhouse\n1. ? @ 0x887d9d6 in /usr/bin/clickhouse\n2. ? @ 0x887d823 in /usr/bin/clickhouse\n3. ? @ 0xddfd7d3 in /usr/bin/clickhouse\n4. DB::SerializationString::deserializeBinary(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x1279ba64 in /usr/bin/clickhouse\n5. DB::BinaryFormatReader::readField(DB::IColumn&, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::ISerialization const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1475a896 in /usr/bin/clickhouse\n6. DB::RowInputFormatWithNamesAndTypes::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x1475d918 in /usr/bin/clickhouse\n7. DB::IRowInputFormat::generate() @ 0x1473cdee in /usr/bin/clickhouse\n8. DB::ISource::tryGenerate() @ 0x146c1455 in /usr/bin/clickhouse\n9. DB::ISource::work() @ 0x146c0fc6 in /usr/bin/clickhouse\n10. DB::ExecutionThreadContext::executeTask() @ 0x146db246 in /usr/bin/clickhouse\n11. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x146d035c in /usr/bin/clickhouse\n12. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x146cf028 in /usr/bin/clickhouse\n13. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x146e09b7 in /usr/bin/clickhouse\n14. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x146e0b73 in /usr/bin/clickhouse\n15. ? @ 0x145ee879 in /usr/bin/clickhouse\n16. ? @ 0x145eab4e in /usr/bin/clickhouse\n17. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xde7dd56 in /usr/bin/clickhouse\n18. ? @ 0xde83081 in /usr/bin/clickhouse\n19. ? @ 0x7f4a1ddf2b43 in ?\n20. ? @ 0x7f4a1de84a00 in ?\n"
}

**Comment by den-crane** [comment]
> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.
