### ISSUE TITLE
 upgrade version：22.3.3.44 to 22.8.12.45

### ISSUE THREAD

**Issue by weiweili666** [ClickHouse/ClickHouse#46327]
1、when I upgrade version：22.3.3.44 to 22.8.12.45，I execute the cmd：
	rpm -Uvh clickhouse-common-static-dbg-22.8.12.45.x86_64.rpm --force --nodeps

2、then return this error：
	ERROR: Unpacking archive failed at file /usr/lib/debug/usr/bin/clickhouse-library-bridge.debug cpio: rename failed - is a directory

3、the rpm version remain like this

[root@cyber soft]# rpm -qa | grep clickhouse
clickhouse-common-static-dbg-22.3.3.44-1.x86_64
clickhouse-keeper-dbg-22.8.12.45-1.x86_64
clickhouse-common-static-22.8.12.45-1.x86_64
clickhouse-server-22.8.12.45-1.x86_64
clickhouse-keeper-22.8.12.45-1.x86_64
clickhouse-client-22.8.12.45-1.x86_64

How to upgrade version?

**Comment by alexey-milovidov** [comment]
Install it is following:
```
curl https://clickhouse.com/ | sh
```

**Comment by weiweili666** [comment]
We are an intranet, and we can only install it offline. Is there any other way?

> Install it is following:
> 
> ```
> curl https://clickhouse.com/ | sh
> ```


We are an intranet, and we can only install it offline. Is there any other way?

**Comment by DerekChia** [comment]
> We are an intranet, and we can only install it offline. Is there any other way?

yes, get the binaries here - https://github.com/ClickHouse/ClickHouse/releases/
