### ISSUE TITLE
ck 22.9.2.7 memory not freed

### ISSUE THREAD

**Issue by hbzhu** [ClickHouse/ClickHouse#46326]
ck version 22.9.2.7

Service has been running for several months，memory used show 
              total        used        free      shared    buff/cache   available
Mem:      30G         24G        2.0G        144M        3.7G         5.4G
Swap:      0B           0B           0B

I stop all query jobs，memory used not released，when I restart clickhouse-server，Looks normal

![image](https://user-images.githubusercontent.com/8680035/218413935-f2bdc266-2987-4ce1-b73d-cbc10969a720.png)

**Comment by alexey-milovidov** [comment]
It is ok if the memory remains allocated for ClickHouse. This is a memory pool that is used for subsequent allocations by the allocator. The memory shouldn't be freed.
