### ISSUE TITLE
 Attempt to read after eof: (while reading column c_lasttime): while executing MergetreeThread.ATTEMPT TO READ AFTER EOF)

### ISSUE THREAD

**Issue by XinCrystal** [ClickHouse/ClickHouse#46320]
hi ,i need help

server version 22.5.28

i used replacingMergeTree in local table, and created Distributed table for them. but when i query on Distributed table like this:
    select countl() from test where c_lasttime >= 2023-02-09 01:00:00' and c_lasttime <= '2023-02-09 23:00:00';

i got an error,the error is:  Attempt to read after eof: (while reading column c_lasttime): while executing MergetreeThread.ATTEMPT TO READ AFTER EOF)

table statement:
    CREATE TABLE zxtest.test on cluster cluster_d
(
  c_domain String,
  c_type String,
  c_value String,
  c_city String,
  c_lasttime DateTime
)
ENGINE = ReplacingMergeTree(c_lasttime)
PARTITION BY moduloOrZero(cityHash64(c_domain),32)
ORDER BY (c_domain,c_type, c_value)
SETTINGS min_rows_for_wide_part = 20000000,max_bytes_to_merge_at_max_space_in_pool = 21474836480, index_granularity = 8192,storage_policy = 'aaa'

CREATE TABLE zxtest.test on cluster cluster_q
(
  c_domain String,
  c_type String,
  c_value String,
  c_city String,
  c_lasttime DateTime
)
ENGINE = Distributed('cluster_d', 'zxtest', 'test', rand())

thanks a lot!

**Comment by cangyin** [comment]
Is the error reproducible?

**Comment by den-crane** [comment]
22.5.28 is obsolete. Upgrade to 23.1.3
