### ISSUE TITLE
Copy between two tables with the same set of columns uses source table ordering

### ISSUE THREAD

**Issue by AryGr** [ClickHouse/ClickHouse#46338]
**Summary:**
If you have two tables with the same set of columns, but a different ordering, then copying between them with a `INSERT INTO destination SELECT * FROM source` command unintuitively uses the column ordering found in the `source` table. 

**Example:**
Consider the following MRE:

```
-- Create an example source table
CREATE TABLE example_source_table (
    `id_column`     Int64,
    `first_name`    Nullable(String),
    `surname`       Nullable(String)
)
ENGINE MergeTree()
PARTITION BY id_column
PRIMARY KEY id_column;

-- Create an example destination table
CREATE TABLE example_destination_table (
    `id_column`     Int64,
    `surname`       Nullable(String),  -- note that this column is in a different position than in the source table
    `first_name`    Nullable(String)
)
ENGINE MergeTree()
PARTITION BY id_column
PRIMARY KEY id_column;

-- Check both tables exist
SHOW TABLES;

-- Insert hardcoded sample data into source table
INSERT INTO example_source_table (id_column, first_name, surname)
VALUES (1, 'Joe', 'Bloggs');

-- Copy contents of the source table into the destination table
INSERT INTO example_destination_table
SELECT *
FROM example_source_table;

-- Check contents of destination table. surname and first_name have been swapped around.
SELECT *
FROM example_destination_table;
```

We can see that data from column at position `i` in the source table is inserted into the column at position `i` in the destination, despite the fact that the name of column `i` in the source table differs from that in the destination table.

**Expected behaviour:**
The data would be inserted into the matching column of the destination table even if the position differs.

**Comment by den-crane** [comment]
It's feature of standard SQL, all databases do the same. https://stackoverflow.com/questions/9807724/does-insert-into-select-always-match-fields-by-ordinal-position

Because `INSERT INTO example_source_table (id_column, first_name, surname)` uses the order of `(id_column, first_name, surname)`, but column list can be omitted, and in this case it uses the order of the INSERT-ed table.
