### ISSUE TITLE
Space between colon and value behaving inconsistently

### ISSUE THREAD

**Issue by Fanvadar** [ClickHouse/ClickHouse#46389]
**Overview**
When you have the following JSON: `{"stake": 50}`, Clickhouse will consider this to be valid JSON that contains the param `stake` having type Int64 (see reproduce code). 

And yet Clickhouse will not be able to extract this value - instead it silently fails by defaulting to 0. 

This is a [documented](https://clickhouse.com/docs/en/sql-reference/functions/json-functions/) assumption:
> The JSON does not have space characters outside of string literals.

But it is documented above **all** JSON functions. Meaning one could reasonably assume that when an assumption is broken all functions will reflect that. 

Consider the scenario where we cannot see the JSON contents and can only interact with it using the functions available. In this scenario we would conclude that no assumptions were broken and the JSON looks like this: `{"stake": 0}`. 

**Reproduce**
```
select isValidJSON('{"stake": 50}'); -- returns `1`
select JSONHas('{"stake": 50}', 'stake'); -- returns `1`
select JSONType('{"stake": 50}', 'stake'); -- returns `Int64`
select visitParamExtractInt('{"stake": 50}', 'stake'); -- returns `0`?!
select visitParamExtractInt('{"stake":50}', 'stake'); -- returns `50`
```

**Expected behavior**
Ideally this should not be an assumption and you should be able to extract the value. But at the very least the Clickhouse functions should be more consistent with their assumptions.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/json-functions/#visitparamextractintparams-name

as Documented: **The JSON does not have space characters outside of string literals.**

**Comment by den-crane** [comment]
visitParam is special set of functions which supposed to work with special subset of JSON, very limited subset.
But visitParam is extremely fast.

**Comment by Fanvadar** [comment]
@den-crane Okay so the assumption is there for performance - that's reasonable. 

I'm suggesting that the other functions (e.g. `isValidJSON`, `JSONHas`, `JSONType`) operate with the same assumptions for clarity and consistency.

**Comment by den-crane** [comment]
I changed the doc today: https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/functions/json-functions.md

Initially in Clickhouse existed visitParam only as I understand Yandex internally uses this simplified subset of JSON.
So there is `visitParam*` functions and all other functions. 

`isValidJSON, JSONHas, JSONType, JSONExtract*`  they are "other" functions which use [simdjson](https://github.com/lemire/simdjson) library.

**Comment by den-crane** [comment]
The fact that visitParam are mentioned the first in the documentation is just the legacy.
Probably [simdjson](https://github.com/lemire/simdjson) functions should be the first.

**Comment by Fanvadar** [comment]
Thanks for the clarifications and for changing the docs, looks great. 

Do you know how big the performance difference is between `visitParam*` and `JSONExtract*`?

**Comment by den-crane** [comment]
>Do you know how big the performance difference is between visitParam* and JSONExtract*?

No. It depends on JSONs complexity.

Also check this https://kb.altinity.com/altinity-kb-queries-and-syntax/jsonextract-to-parse-many-attributes-at-a-time/
JSONExtract allows to parse multiple attributes by a time. So it can be faster than multiple visitParam calls.

With simple cases they are on par.

```sql
set max_threads=1;

select ignore(visitParamExtractInt('{"stake":50}', 'stake')) from numbers_mt(1e9) format Null;
0 rows in set. Elapsed: 0.549 sec. Processed 1.00 billion rows, 8.00 GB (1.82 billion rows/s., 14.58 GB/s.)

select ignore(JSONExtractInt('{"stake":50}', 'stake')) from numbers_mt(1e9) format Null;
0 rows in set. Elapsed: 0.554 sec. Processed 1.00 billion rows, 8.00 GB (1.81 billion rows/s., 14.45 GB/s.)
```
