### ISSUE TITLE
Is there a scheme to disable some SQL for a user?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#46390]
Is there a scheme to disable `SELECT *` for a user?

I don't want the operation of some visitors to take up a lot of resources. Is there any other scheme besides limiting the memory used by users?

Thanks!

**Comment by alexey-milovidov** [comment]
You can use the `max_columns_to_read` setting.
For example, you can limit the maximum number of columns in a query to 50.
