### ISSUE TITLE
Implement `system.database_replicas` table

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#46423]
**Use case**

If you have a cluster with Replicated databases, you probably may want to know about whether there are some inactive databases in a particular shard or you could be interested in a position of a log pointer of each database replica. 

**Describe the solution you'd like**

Implement system table similar to already existing `system.replicas`.

**Comment by tavplubix** [comment]
`system.clusters` already shows replicas of replicated databases, but `is_active` column would be useful

**Comment by ashwath** [comment]
@tavplubix: 
Can I use the following query to find number of server replicas as per CH
`select count(*) from system.clusters;`
I want to be 100% confirmed, as will we end up using this for horizontal-autoscaling logic.

**Comment by ashwath** [comment]
actually something like  `select count(*) from system.clusters where host_name like 'c-maroon-la-72-server-%'`
what do you think?

**Comment by tavplubix** [comment]
> Can I use the following query to find number of server replicas as per CH
> select count(*) from system.clusters;

No. But you can use `select count() from system.clusters where cluster='replicated_database_name'`. It will return the total number of replicas of a replicated database named `replicated_database_name`.

> What do we mean by "is_active" column? Is it possible there is an entry here but that's not really an active replica?

Yes, some replicas can be offline or readonly, for example. I don't know what is "horizontal-autoscaling logic" and what metrics you need for this logic, so it's hard to advise some "100% query", it depends on what you expect to get from this query. 

P.S. This repo is public.

**Comment by ashwath** [comment]
@tavplubix 

As we will add and remove server replicas, I want to figure out how many **server replicas(hosts)** ClickHouse thinks are available. It doesn't have to be corresponding to a particular database.
This should work for both cases when customers have any replicated tables or none. 

looks like `select count(*) from system.clusters where startsWith(host_name, 'c-$spoken_name-server')` works but need confirmation from an expert o it like yourself.

**Comment by tavplubix** [comment]
> `system.clusters` already shows replicas of replicated databases, but `is_active` column would be useful

The column is added in https://github.com/ClickHouse/ClickHouse/pull/48548
