### ISSUE TITLE
How to forbid  clickhouse role use show databases command  

### ISSUE THREAD

**Issue by bigdata-spec** [ClickHouse/ClickHouse#46427]
![image](https://user-images.githubusercontent.com/23710717/218940851-bcf88d32-6475-4e2b-b93f-51bd39dc3541.png)

but user1 can still use show databases command;
![image](https://user-images.githubusercontent.com/23710717/218940886-9d19ac3a-b3f9-46c7-ac63-c094793d3b98.png)

REVOKE SHOW DATABASES ON *.* FROM role_name;
 REVOKE  SHOW DATABASES  ON db1 FROM role1;
 REVOKE  SHOW DATABASES  ON db1.* FROM role1;
but there are not  take effect;
how to disable use show databases；
@den-crane  Can you help me？

**Comment by ilejn** [comment]
@bigdata-spec 
I am not sure that it makes sense,
but try setting access_control_improvements.select_from_information_schema_requires_grant 
configuration parameter to true
