### ISSUE TITLE
How to detect errors during processing in binary formats over HTTP?

### ISSUE THREAD

**Issue by loyd** [ClickHouse/ClickHouse#46426]
ClickHouse can send errors during requests if the processing fails.

For instance,
```sh
$ curl -v -sS 'http://localhost:8123/?max_execution_time=0.01' -d 'SELECT toUInt8(65 + number % 5) FROM system.numbers LIMIT 9000000 FORMAT RowBinary' > data
$ tail -c 300 data | hexdump -C
```

Result:
```
00000000  42 43 44 45 41 42 43 44  45 41 42 43 44 45 41 42  |BCDEABCDEABCDEAB|
00000010  43 44 45 41 42 43 44 45  41 42 43 44 45 41 42 43  |CDEABCDEABCDEABC|
00000020  44 45 41 42 43 44 45 41  42 43 44 45 41 42 43 44  |DEABCDEABCDEABCD|
00000030  45 41 42 43 44 45 41 42  43 44 45 41 42 43 44 45  |EABCDEABCDEABCDE|
00000040  41 42 43 44 45 41 42 43  44 45 41 42 43 44 45 41  |ABCDEABCDEABCDEA|
00000050  42 43 44 45 41 42 43 44  45 41 42 43 44 45 41 42  |BCDEABCDEABCDEAB|
00000060  43 44 45 41 42 43 44 45  41 42 43 44 45 41 42 43  |CDEABCDEABCDEABC|
00000070  44 45 41 42 43 44 45 41  42 43 44 45 41 42 43 44  |DEABCDEABCDEABCD|
00000080  45 41 42 43 44 45 41 42  43 44 45 41 42 43 44 45  |EABCDEABCDEABCDE|
00000090  41 42 43 44 45 41 42 43  44 45 41 43 6f 64 65 3a  |ABCDEABCDEACode:|
000000a0  20 31 35 39 2e 20 44 42  3a 3a 45 78 63 65 70 74  | 159. DB::Except|
000000b0  69 6f 6e 3a 20 54 69 6d  65 6f 75 74 20 65 78 63  |ion: Timeout exc|
000000c0  65 65 64 65 64 3a 20 65  6c 61 70 73 65 64 20 30  |eeded: elapsed 0|
000000d0  2e 30 31 33 31 37 30 35  37 33 20 73 65 63 6f 6e  |.013170573 secon|
000000e0  64 73 2c 20 6d 61 78 69  6d 75 6d 3a 20 30 2e 30  |ds, maximum: 0.0|
000000f0  31 2e 20 28 54 49 4d 45  4f 55 54 5f 45 58 43 45  |1. (TIMEOUT_EXCE|
00000100  45 44 45 44 29 20 28 76  65 72 73 69 6f 6e 20 32  |EDED) (version 2|
00000110  32 2e 31 30 2e 32 2e 31  31 20 28 6f 66 66 69 63  |2.10.2.11 (offic|
00000120  69 61 6c 20 62 75 69 6c  64 29 29 0a              |ial build)).|
0000012c
```

* `wait_end_of_query=1` is not always applicable, so I cannot rely on it in my generic client.
* AFAIK, there is no support for trailers: https://github.com/ClickHouse/ClickHouse/issues/21136.
* An error can be included in the same HTTP chunk as data, so I cannot check only the initial bytes of chunks.
* Trailing bytes of a chunk can be checked, but another question here: can this message be split into several chunks?
* Checks should rely on `(official build))` or `Code: `, but there are no guarantees by CH for these messages, innit?
* Binary formats can include bytes, such checks can reject valid data.

So, how to detect an error during parsing reliably?

**Comment by Algunenano** [comment]
> wait_end_of_query=1 is not always applicable, so I cannot rely on it in my generic client.

Can you expand more on this? In which situations isn't this applicable / won't work? In master at least, using `wait_end_of_query` should produce a better HTTP response code and a `X-ClickHouse-Exception-Code`. AFAIK, the only exception in master would be if also enable progress via headers (because the status needs to go before sending headers and you are asking to get progress asap).

I'd be interested to know if you have other cases where `wait_end_of_query=1` does not work as expected for error reporting, as I think of those as bugs.

**Comment by zhicwu** [comment]
> So, how to detect an error during parsing reliably?

I'm counting on the deserialization error for now :p Actually the scenario could be worse, as reported in ClickHouse/clickhouse-java#976, that sometimes ClickHouse closed the connection without sending any error. One workaround I thought about was to use the unique query id to check places like `system.query_log`(only when error occurred), but we know there's latency and the system tables might be disabled on PROD :)

Perhaps TCP/native interface is the right direction.

> Or you can switch to GRPC.

IMO gRPC is not ready for production, and looks like it's not actively maintained. Although it seems handling error better than HTTP along with some nice features, but it's slower than http(in Java, with netty and native lib), has issue dealing with lz4, and often triggers memory limit on server during testing.

**Comment by den-crane** [comment]
> that sometimes ClickHouse closed the connection without sending any error.

In case of what error?


> I thought about was to use the unique query id to check places like system.query_log

Small chances that you will be connected to the right Clickhouse with Cloud solutions.

**Comment by zhicwu** [comment]
> In case of what error?

At least error 160 as reported in https://github.com/ClickHouse/clickhouse-java/issues/976#issuecomment-1183397139 and https://github.com/trinodb/trino/issues/17758#issuecomment-1582535862

**Comment by loyd** [comment]
> I'm counting on the deserialization error for now

The problem here is that it's possible to (sometimes) decode binary data even if there is an error in the stream and just get garbage in data that can be very expensive.

Finally, I ended with checking every batch from the server if it ends with `))\n`:
```
// Format:
//   <data>Code: <code>. DB::Exception: <desc> (version <version> (official build))\n
fn extract_exception(chunk: &mut Bytes) -> Option<Error> {
    // `))\n` is very rare in real data and occurs with a probability of ~6*10^-8 in random ones.
    if chunk.ends_with(b"))\n") {
        extract_exception_slow(chunk) //< here checking "DB::Exception:" and "Code:"
    } else {
        None
    }
}
```

It's worked in our production for 8 months with multiple CH updates, but sadly, it can break eventually if CH changes this format. So, I run tests against all new releases to detect this.

It's dirty and not reliable, but it's fast enough.

Anyway, I will move away from HTTP eventually because it's much slower than the native interface, even simple `curl` works much slower on reading according to (engaged and populist, but in general indicative) https://github.com/ClickHouse/ch-bench#benchmarks

**Comment by mshustov** [comment]
@CheSema is working on a solution at https://github.com/ClickHouse/ClickHouse/pull/68800. The idea is following:

For ANY statements over HTTP the client has to check:
1. HTTP code
1. HTTP header `X-ClickHouse-Exception-Code`
1. transmission constrains like:
    - `Content Length`  all the data has been received
    -  `Transfer-Encoding: chunked` all chunks have been received including the empty last one
    
If all is good, then the response is reliable.
If something indicates an error, the client should not treat it as a successful response.

**Comment by CheSema** [comment]
I think I fixed HTTP. Now even curl understands that it is an error.

```
sema@semas-pc:~/work/tmp$ curl -v -sS 'http://localhost:8123/?max_execution_time=0.01' -d 'SELECT toUInt8(65 + number % 5) FROM system.numbers LIMIT 9000000 FORMAT RowBinary' > data
*   Trying 127.0.0.1:8123...
* Connected to localhost (127.0.0.1) port 8123 (#0)
> POST /?max_execution_time=0.01 HTTP/1.1
> Host: localhost:8123
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 82
> Content-Type: application/x-www-form-urlencoded
> 
} [82 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 19 Nov 2024 12:48:28 GMT
< Connection: Keep-Alive
< Content-Type: application/octet-stream
< X-ClickHouse-Server-Display-Name: functional-tests
< Transfer-Encoding: chunked
< X-ClickHouse-Query-Id: d3d3a9ab-c687-4b47-a192-a9ec133bfb16
< X-ClickHouse-Format: RowBinary
< X-ClickHouse-Timezone: Europe/Amsterdam
< Keep-Alive: timeout=10, max=9999
< X-ClickHouse-Summary: {"read_rows":"327045","read_bytes":"2616360","written_rows":"0","written_bytes":"0","total_rows_to_read":"9000000","result_rows":"0","result_bytes":"0","elapsed_ns":"2706569"}
< 
{ [65415 bytes data]
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
sema@semas-pc:~/work/tmp$ echo $?
18
```
