### ISSUE TITLE
No clickhouse-server.service

### ISSUE THREAD

**Issue by strokovnjaka** [ClickHouse/ClickHouse#46434]
There is no `clickhouse-server.service` after installing `ClickHouse server version 23.2.1.1629 (official build).` on `Ubuntu 22.04.1 LTS` via  the recommended 
```
curl https://clickhouse.com/ | sh
sudo ./clickhouse install
```

So, the [documentation](https://clickhouse.com/docs/en/install/#launch) is wrong, as I cannot start it as a service:

```
$ sudo service clickhouse-server start
Failed to start clickhouse-server.service: Unit clickhouse-server.service not found.
$ sudo /etc/init.d/clickhouse-server start
sudo: /etc/init.d/clickhouse-server: command not found
$ sudo systemctl start clickhouse-server.service
Failed to start clickhouse-server.service: Unit clickhouse-server.service not found.
```

The `clickhouse-server.service` was there in version 22.x.y., but not anymore.

Is there an easy way to start `clickhouse-server` as a service?

**Comment by Felixoid** [comment]
You need to install clickhouse as a package to get the service file. `sudo ./clickhouse install` doesn't provide additional package-specific files located in https://github.com/ClickHouse/ClickHouse/tree/master/packages
