### ISSUE TITLE
MySQL compatibility: add support for SHOW COLUMNS, SHOW FULL TABLES

### ISSUE THREAD

**Issue by mshustov** [ClickHouse/ClickHouse#46437]
**Use case**

ClickHouse with [Looker](https://cloud.google.com/looker) via MySQL protocol.

**Describe the solution you'd like**

When Looker scans a table 

> SHOW FULL COLUMNS FROM `hits_v1` FROM `datasets` LIKE '%'

the operation fails with 
>  <Error> executeQuery: Code: 62. DB::Exception: Syntax error: failed at position 11 ('COLUMNS'): COLUMNS FROM `hits_v1` FROM `datasets` LIKE '%'. Expected one of: DATABASES, CLUSTERS, 

The scan table operation must succeed.

**Additional context**
https://github.com/ClickHouse/ClickHouse/issues/9336#issuecomment-1001090069 
reports `SHOW FULL TABLES FROM .*` failed as well. I confirm the problem exists in `2023.1` release. Maybe we can fix both incompatibility problems. 

cc @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Field - field name
Type - the type name adapted for MySQL compatibility
Null - String, YES or NO
Key - String, MUL for the columns included in the primary key expression, otherwise empty String
Default - full default expression
Extra - empty string
Privileges - String, `Select`
Collation - Nullable(String), always NULL
Comment - column's comment

**Comment by Yukang-Lian** [comment]
Hi, @mshustov @alexey-milovidov , I am new here and am very interested in clickhouse. I want to try to complete this task. Could you please assign me? I will try my best to do it!

**Comment by alexey-milovidov** [comment]
@Yukang-Lian Thank you! This will be very helpful!

**Comment by mshustov** [comment]
@Yukang-Lian do you need any help with the issue?

**Comment by Yukang-Lian** [comment]
> @Yukang-Lian do you need any help with the issue?

Hi, @mshustov, thanks for your concern. Sorry for not updating the status in time. I just implemented a feature for Apache Doris some time ago. Recently, I have free time. I will complete this issue as soon as possible. If there is any problem, I will ask for your advice. Thanks a lot!
