### ISSUE TITLE
Log engine in disdributed and replicated cluster

### ISSUE THREAD

**Issue by FangLietao** [ClickHouse/ClickHouse#4645]
The distributed and replicated cluster was built, 
`<shard>`
            `<internal_replication>false</internal_replication>`
            `<replica>`
                `<host>host1</host>`
               ` <port>9002</port>`
              `<user>default</user>`
               ` <password>***</password>`
            `</replica>`
	   `<replica>`
                `<host>host2</host>`
               ` <port>9002</port>`
               ` <user>default</user>`
                `<password>***</password>`
            `</replica>`
  `</shard>`
 it can work well when i build local table on every node with engine=ReplicateMergeTree and build distributed table with engine=Distributed. But, if i build local tableA with engine=Log on host1, and insert data into tableA, and Exception is throwed like host2 does not exist tableA.
Log is not replicated engine,  but it try to insert data at another replicated node.

**Comment by engccq** [comment]
I have met the same issue.

**Comment by alexey-milovidov** [comment]
Could you please provide more details? The description is unclear for me.
If you create Log tables on all hosts and query Distributed table, everything should work fine as expected.

**Comment by den-crane** [comment]
No Info. No repro. 
Probably misconfiguration.
