### ISSUE TITLE
Clickhouse takes a large amount of virtual memory when running kafka data input.

### ISSUE THREAD

**Issue by kindred77** [ClickHouse/ClickHouse#4646]
OS version: Redhat 7
Clickhouse version: 19.3.5
total physical mem: 250G
I created the data input stream using the way in docs(kafka topic mapped table, materialized view and mergetree result table). It have run for 4 days, and I find the clickhouse-server process takes about 236G virtual memory and 15G physical memory.

**Comment by AlexPereverzyev** [comment]
Some observations -


Case 1: no messages/load

Every second _BackgroundSchedulePoolTaskInfo_ logs trace message - "Execution took ~2500 ms".

Prometheus metric _clickhouse_memory_tracking_in_background_schedule_pool_ grows constantly.

Overall memory leak depends on number of active Kafka consumers: ~300 MB/day for 6, ~600 MB/day - for 12, etc.

Dropping or detaching the materialized view stops Kafka polling, the memory leak and trace log messages. 

Kafka consumer setting _fetch_wait_max_ms_ has no effect.


Case 2: consistent message flow/load (~600 k/min)

_BackgroundSchedulePoolTaskInfo_ no longer logs execution duration, unless insert block is quite big (which is workarounded by adding more consumers).

_clickhouse_memory_tracking_in_background_schedule_pool_ - not growing anymore.


Seems Kafka polling background task leaks memory. 

Can we have configuration setting for READ_POLL_MS in _ReadBufferFromKafkaConsumer.cpp_?

**Comment by filimonov** [comment]
Does it reproduces on newer ClickHouse versions?
