### ISSUE TITLE
DB::Exception: Cannot read all data. Bytes read: 25190. Bytes expected: 55772

### ISSUE THREAD

**Issue by zhukai** [ClickHouse/ClickHouse#46463]
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xf7dbe0c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x54b13fa in /usr/bin/clickhouse
2. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0x54ead06 in /usr/bin/clickhouse
3. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&, bool) @ 0xca95026 in /usr/bin/clickhouse
4. DB::CompressedReadBufferFromFile::nextImpl() @ 0xca9744a in /usr/bin/clickhouse
5. void DB::deserializeBinarySSE2<1>(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>&, DB::ReadBuffer&, unsigned long) @ 0xcbb697b in /usr/bin/clickhouse
6. DB::ISerialization::deserializeBinaryBulkWithMultipleStreams(COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, DB::ISerialization::DeserializeBinaryBulkSettings&, std::__1::shared_ptr<DB::ISerialization::DeserializeBinaryBulkState>&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > >*) const @ 0xcb73352 in /usr/bin/clickhouse
7. DB::MergeTreeReaderCompact::readData(DB::NameAndTypePair const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>&, unsigned long, unsigned long, unsigned long, unsigned long, bool) @ 0xd738c53 in /usr/bin/clickhouse
8. DB::MergeTreeReaderCompact::readRows(unsigned long, unsigned long, bool, unsigned long, std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&) @ 0xd7385f5 in /usr/bin/clickhouse
9. DB::MergeTreeSequentialSource::generate() @ 0xd741b79 in /usr/bin/clickhouse
10. DB::ISource::tryGenerate() @ 0xd8e8bb5 in /usr/bin/clickhouse
11. DB::ISource::work() @ 0xd8e899a in /usr/bin/clickhouse
12. DB::SourceWithProgress::work() @ 0xda21a56 in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0xe0171ba in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0xd8f63e0 in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0xd8f6140 in /usr/bin/clickhouse
16. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0xd8fb25c in /usr/bin/clickhouse
17. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0xd8fb40c in /usr/bin/clickhouse
18. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0xd6633d7 in /usr/bin/clickhouse
19. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0xd66330b in /usr/bin/clickhouse
20. DB::MergeTask::execute() @ 0xd66693a in /usr/bin/clickhouse
21. DB::MergePlainMergeTreeTask::executeStep() @ 0xdf28265 in /usr/bin/clickhouse
22. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xd6738d3 in /usr/bin/clickhouse
23. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xd674486 in /usr/bin/clickhouse
24. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xf5c2cf1 in /usr/bin/clickhouse
25. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0xf5c472c in /usr/bin/clickhouse
26. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xf5c1731 in /usr/bin/clickhouse
27. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xf5c362e in /usr/bin/clickhouse
28. start_thread @ 0x814a in /usr/lib64/libpthread-2.28.so
29. __GI___clone @ 0xfcdc3 in /usr/lib64/libc-2.28.so
 (version 22.5.30.1690320 (CECloud build))
2023.02.16 14:59:13.118522 [ 190 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 33. DB::Exception: Cannot read all data. Bytes read: 25190. Bytes expected: 55772.: (while reading column c_d_owner): While executing MergeTreeSequentialSource. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

**Comment by tavplubix** [comment]
Please follow [this](https://github.com/ClickHouse/ClickHouse/blob/master/.github/ISSUE_TEMPLATE/85_bug-report.md) template and provide some diagnostic info/logs/steps to reproduce if you'd like to report an issue.
