### ISSUE TITLE
Clickhouse Breakdown Due to Complex Query

### ISSUE THREAD

**Issue by T-M-L-C** [ClickHouse/ClickHouse#46481]
Question:
On a machine with 128 GB memory and 16-core CPUs, clickhouse is configured by default for two nodes and stores more than 5 million data records. In a complex multi-table association query, clickhouse automatically breaks down each time when the query result reaches 59%. The following error is reported:
![image](https://user-images.githubusercontent.com/12447886/219379604-e16b1e0f-c5a2-401b-bb70-2f8f1d81a468.png)
Query SQL:
SELECT
a.MSISDN AS MSISDN,
a.OPPNUMBER AS OPPNUMBER,
b.STARTTIME AS STARTTIME
FROM
(
SELECT
*
FROM
MONITOR.TEST
) a,
(
SELECT
*
FROM
MONITOR.TEST
) b
WHERE
a.MSISDN = b.MSISDN
LIMIT
1;

**Comment by den-crane** [comment]
see https://clickhouse.com/docs/en/operations/settings/settings/#settings-join_algorithm

```sql
SELECT a.MSISDN AS MSISDN,
       a.OPPNUMBER AS OPPNUMBER,
       b.STARTTIME AS STARTTIME
FROM ( SELECT * FROM MONITOR.TEST ) a,
     ( SELECT * FROM MONITOR.TEST ) b
WHERE
a.MSISDN = b.MSISDN
LIMIT 1 
settings join_algorithm = 'grace_hash';
```

**Comment by T-M-L-C** [comment]
When I use join_algorithm = 'grace_hash' The following error is reported:
DB::Exception: Unexpected value of JoinAlgorithm: 'grace_hash'. Must be one of ['prefer_partial_merge', 'hash', 'partial_merge', 'auto']. 
But I solved this problem perfectly using the join_algorithm ='partial_merge' and I'd like to thank you for providing such a solution.
