### ISSUE TITLE
Try intel/x86-simd-sort library

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#46486]
Source code: https://github.com/intel/x86-simd-sort

**Comment by alexey-milovidov** [comment]
The use case for this library is limited.
We are using indirect sorting: sorting of indices and then permitting the columns with the permutation.

We can use this library in one of the following cases:

1. If all the following conditions are met:
- we are sorting by an integer or floating point data type;
- there are no other columns - this is the single column in the result;
- we are doing full sorting without LIMIT.

2. If all the following conditions are met:
- we are sorting by an integer of 32-bit size;
- we are doing full sorting without LIMIT.

In case (2), we can pack the value and the index in a single 64-bit field and apply this library.

**Comment by zhanglistar** [comment]
@nickitat @alexey-milovidov Check this, https://duckdb.org/2021/08/27/external-sorting

**Comment by alexey-milovidov** [comment]
@zhanglistar ok, but the article you've posted is about external sorting, while this task is about internal sorting.

**Comment by r-devulap** [comment]
> We are using indirect sorting: sorting of indices and then permitting the columns with the permutation.

The library does provide avx2/avx512 `argsort` which is indirect sorting of indices. Is that something of interest to this library?
