### ISSUE TITLE
Syntax error when using CODEC keyword

### ISSUE THREAD

**Issue by gabomgp4** [ClickHouse/ClickHouse#46496]
I'm trying to create a simple table in Clickhouse and it's failing with syntax error, only when I try to use CODEC configuration:

```sql
 CREATE TABLE customs (
      ym UInt16 CODEC(ZSTD)
  )
  ENGINE = MergeTree;
```

If I remove the CODEC(ZSTD) code from this sentence, it works. The shown error is:

    Expected one of: token, ClosingRoundBracket, Comma, DEFAULT, MATERIALIZED, ALIAS, COMMENT

It's now clear to me why this is not working :'(

Can someone say what I'm missing?

**Comment by den-crane** [comment]
do you have `ORDER BY ym` section ?

What Clickhouse server and Clickhouse client do you use? `select version()` ?

```
ClickHouse client version 23.1.2.9 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.1.2 revision 54461.
```

version of Clickhouse client is important
