### ISSUE TITLE
is PRIMARY KEY in ClickHouse equivalent to INDEX in other RDBMS???

### ISSUE THREAD

**Issue by huwngnosleep** [ClickHouse/ClickHouse#46514]
In Mysql, for example, when create table I can specify indexed field:
CREATE TABLE ... INDEX(...)

But in ClickHouse, I only have:
CREATE TABLE ... PRIMARY KEY(...) ORDER BY(...)

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/guides/improving-query-performance/sparse-primary-indexes/
https://clickhouse.com/docs/en/getting-started/example-datasets/nypd_complaint_data/#order-by-and-primary-key-clauses

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#order_by

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree/#choosing-a-primary-key-that-differs-from-the-sorting-key
