### ISSUE TITLE
Final keyword causes empty result for specific set of columns in select query

### ISSUE THREAD

**Issue by p-pekala** [ClickHouse/ClickHouse#46534]
**Describe the unexpected behaviour**
Whenever we use the FINAL keyword while querying a single table number of returned rows varies depending on the set of columns we want to query.

This query returns 0 rows:
```
select
    t.col1
from test.test_table_d t final
where t.col2 = 0;
```

This query returns multiple rows (probably the correct result):
```
select
    t.col3,
    t.col1
from test.test_table_d t final
where t.col2 = 0;
```

Removing the FINAL keyword from the first query we are also getting the correct result.

**How to reproduce**
I'm not sure if it is reproducible (haven't generated test data set).

ClickHOuse server version: 22.8.13.20

Cluster setting: 2 shards with 2 replicas each

* `CREATE TABLE` statements for all tables involved

```
CREATE TABLE IF NOT EXISTS test.test_table ON CLUSTER '{cluster}' (
    col4    String,
    col5    String,
    col3    Int32,
    col6    LowCardinality(FixedString(3)),
    col7     Int32                            
    col2     Int32,
    col8     Int32,
    col9     Int32,
    col1     UInt32,
    col10    UInt8                             
    col11    UUID,       
    col12    UUID,
    col13    UInt32                   
    col14    UInt32,
    col15    LowCardinality(String),
    col16    Enum('x' = 1, 'y' = 2, 'z' = 3),
    col17     DateTime('UTC') 
    col18    UInt32   
) ENGINE ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/test/test_table', '{replica}', (col13, col14, col18, col3, col7, col2))
PARTITION BY toYYYYMM(col17)
ORDER BY (cityHash64(col15), toDate(col17), col11, col4, col5)
PRIMARY KEY (cityHash64(col15), toDate(col17));
```

```
CREATE OR REPLACE TABLE test.test_table_d ON CLUSTER '{cluster}' AS test.test_table
ENGINE = Distributed('{cluster}', 'test', test_table, cityHash64(`col11`));
```

**Expected behavior**
Using the FINAL query I should get some results

**Comment by SaltTan** [comment]
This is because SummingMergeTree removes rows with zeroes in metrics

**Comment by den-crane** [comment]
For future readers:
I don't care about this issue.
But it's unexpected behaviour because of FINAL works incorrectly in this case. It makes the result dependent on columns in the select section. It eliminates zeroed rows if you query only one metric (with 0), and does not eliminates if you query more than 0.

In other words it does `having metric2 <> 0` instead of  `having metric2 <> 0 and metric1<>0`
