### ISSUE TITLE
union all ignores column names

### ISSUE THREAD

**Issue by niggin** [ClickHouse/ClickHouse#46531]
**Describe what's wrong**

When I try to union two tables with different column ordering using UNION ALL the order of columns is ignored and 

https://fiddle.clickhouse.com/58dd8f49-581a-41d3-980f-24c941c69308

**Does it reproduce on recent release?**

Yes

**Enable crash reporting**

**How to reproduce**

`SELECT
    1 AS a,
    2 AS b
UNION ALL
SELECT
    3 AS b,
    4 AS a`

**Expected behavior**

The result should contain two rows, with values (1, 2) and (4, 3)

**Error message and/or stacktrace**

The output is two rows with (1, 2) and (3, 4) values

**Additional context**

**Comment by tavplubix** [comment]
AFAIK it works as it should. Please provide a link to the SQL standard if you think it should take column names into account.

**Comment by niggin** [comment]
@tavplubix I think you are right that SQL standard states that column names are ignored in union all statement, only column types are validated. But it would be nice to have a disclaimer in documentation that explicitly states that column names are ignored even if they overlap, only column order is considered rendering final result

**Comment by tavplubix** [comment]
Feel free to open a pull request. You can do it by editing [this](https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/statements/select/union.md) file through GitHub web UI without checking out the repo locally (there's a "pencil" button).
