### ISSUE TITLE
WHERE Expression for WATCH Statement

### ISSUE THREAD

**Issue by eslof** [ClickHouse/ClickHouse#46555]
**Use case**

I'm still experimenting and noticed I can subscribe to live updates with something simple like;
`create live view event_tail as select * from event_log order by event_time desc limit 1;`

Our system has different clients with their own users and the clients have their own dashboard, it would be cool to be able to push updates to their WS connection for a "live activity log" of their users.
However; if say 10k users from 1000 different clients are making inserts, but only say 20 managers/clients are currently looking at the dashboard, I would have an overwhelming amount of unrelated triggers from a generic 'WATCH'.

So if I was able to only `watch event_tail where client_id = $connectedDashboardClient format JsonEachRow;` then I wouldn't have to worry about my system deserialising and processing 98% unneeded data.
Or something like `watch event_tail where client_id in ($connectedDashboardClients)` so I would only have to worry about sorting out those 20 connected clients managers logged into the dashboard (and maybe less overhead on the watching itself).

**Describe the solution you'd like**

```
WATCH [db.]live_view [EVENTS] [WHERE expr] [LIMIT n] [FORMAT format]
```
Like: 
```
create live view event_tail as select * from event_log order by event_time desc limit 1;
```
```
watch event_tail where client_id = 10
{"event_type":"debug","event_time":"2023-02-17 02:10:45.747118942","client_id":"10","_version":"10"}
{"event_type":"debug","event_time":"2023-02-17 02:10:46.201106771","client_id":"10","_version":"11"}
{"event_type":"debug","event_time":"2023-02-17 02:10:46.642759269","client_id":"10","_version":"12"}
```
E.tc.

**Describe alternatives you've considered**

Simply processing ALL events and filtering them out in our application back-end, but again there would be an overwhelming amount of unnecessary compute and such. Alternatively giving clients their own live views but I've read that this may not be good practice, and from the numbers it will be difficult to scale.

**Comment by alexey-milovidov** [comment]
LIVE VIEW is not supported.
