### ISSUE TITLE
How to connect kafka by using sasl_plaintext?

### ISSUE THREAD

**Issue by awenblue** [ClickHouse/ClickHouse#46551]
I update the config.xml  like blew
<img width="735" alt="image" src="https://user-images.githubusercontent.com/7802704/219852156-e795035a-8954-4def-b45a-d4798bfaa5df.png">
 
then restart clickhouse-server and use sql like:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/7802704/219852241-db31e363-49aa-4fa9-8635-b4ea6ec66709.png">

but receive the message 
/bootstrap: Disconnected: verify that security.protocol is correctly configured, broker might require SASL authentication (after 345ms in state UP)

Is that something i missed? 

I also tried that write a file in config.d , named kafka_preset1.xml 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/7802704/219852479-9f18f9c5-5d7c-4381-88a5-64b483f9afa0.png">

then restart clickhouse-server and execute sql like blow
CREATE TABLE queue1
(
    message String
)
ENGINE = Kafka(kafka_preset1, kafka_format = 'JSONEachRow')

Then I received that 
 TCPHandler: Code: 36. DB::Exception: There is no collection named `kafka_preset1` in config.

and use kafkacat test is ok.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/7802704/219852814-71c88c29-e12d-48b9-87ff-97cdd6f047f3.png">

orz...

Could you please help me for solving this problem? Thanks a lot!

**Comment by den-crane** [comment]
need to restart clickhouse to apply `named_collections` update.
