### ISSUE TITLE
merge processing is extremely slow for tables using S3 storage

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#46578]
**Describe the situation**

We're testing merge tree tables on S3 based on the 22.3 branch.

The cluster contains 4 replicas, and we found that merges are extremely slow.

Here's the result selecting from `system.merges` table on one replica.

![image](https://user-images.githubusercontent.com/6525742/220034471-f7cc9ff9-3432-4502-b2e9-62a0bd9a129a.png)

We can see that first 5 merge processing are very slow, especially the first one which has been running for 5000 seconds but the progress is less than 0.02.

And following is the result of `select name, value from system.settings where changed`

```text
    ┌─name─────────────────────────────────────────┬─value───────┐
 1. │ s3_min_upload_part_size                      │ 268435456   │
 2. │ s3_max_single_part_upload_size               │ 268435456   │
 3. │ use_uncompressed_cache                       │ 0           │
 4. │ background_pool_size                         │ 38          │
 5. │ background_fetches_pool_size                 │ 16          │
 6. │ load_balancing                               │ random      │
 7. │ skip_unavailable_shards                      │ 1           │
 8. │ log_queries                                  │ 1           │
 9. │ distributed_product_mode                     │ local       │
10. │ send_progress_in_http_headers                │ 1           │
11. │ http_headers_progress_interval_ms            │ 1000000     │
12. │ max_result_rows                              │ 1000        │
13. │ max_result_bytes                             │ 10000000    │
14. │ result_overflow_mode                         │ break       │
15. │ max_execution_time                           │ 60          │
16. │ max_memory_usage                             │ 20000000000 │
17. │ max_memory_usage_for_user                    │ 0           │
18. │ log_query_threads                            │ 0           │
19. │ parallel_view_processing                     │ 1           │
20. │ cancel_http_readonly_queries_on_client_close │ 1           │
21. │ max_partitions_per_insert_block              │ 1000        │
22. │ default_database_engine                      │ Ordinary    │
23. │ output_format_pretty_max_rows                │ 1000        │
24. │ output_format_pretty_max_value_width         │ 50000       │
25. │ output_format_pretty_color                   │ 0           │
26. │ output_format_pretty_row_numbers             │ 1           │
    └──────────────────────────────────────────────┴─────────────┘
```

We're still investigating such problem. We appreciate any ideas on this problem.

**Comment by FrankChen021** [comment]
Updates after adding span logs to MERGE processing and underlying httpclient requests.

1. prefetch is not enabled for MERGE

https://github.com/ClickHouse/ClickHouse/blob/7d48eae0f62ee0158c309bff380067e2614cc688/src/Storages/MergeTree/MergeTreeSequentialSource.cpp#L134-L148

However, the prefetch for remote_fs is defined as false in the ReadSettings,

https://github.com/ClickHouse/ClickHouse/blob/915a04c0ec44792ee4fe624d89a78bb4255ab7b3/src/IO/ReadSettings.h#L74-L75


 and the code above does not call 'Context::getReadSetting()' to get the default setting

2. During ExecuteAndFinalHorizontalPart phase, ClickHouse retrieves 8192 rows from remote stream each round. 
For very large source parts, this may cause lots of iterations. We're still checking if the larger merge_max_block_size might improves the performance during this phase.


cc @alexey-milovidov @tavplubix

**Comment by alexey-milovidov** [comment]
Many changes have been made since version 22.3, which is almost one year old.
We did not have ClickHouse Cloud (we did not use S3 in production) one year ago.

I'm monitoring some merges on s3 right now, and they are performing perfectly fine.
Although it is only tested on AWS S3; other S3-compatible storages can be slower.

**Comment by alexey-milovidov** [comment]
`remote_filesystem_read_prefetch` is set to `true` in master.

**Comment by FrankChen021** [comment]
@alexey-milovidov You're right, there're lots of improvement and bugfix after 22.3. We also going to rebase our version to 23.3 which is expected to be released this month.

In terms of the setting `remote_filesystem_read_prefetch` you mention above, it's already `true` on 22.3. 
The thing is, its value is not used during MERGE processing as you can see from the code I attached above.
