### ISSUE TITLE
Deref nullptr in TreeOptimizer.cpp

### ISSUE THREAD

**Issue by joey-bd** [ClickHouse/ClickHouse#46576]
@alexey-milovidov @4ertus2 
> You have to provide the following information whenever possible.

**Describe what's wrong**

Dereferencing a `nullptr` on line 494 of TreeOptimizer.cpp\
`data` is constructed with some attributes initialized but not all. `data.identifier` is by default initialized to `nullptr`\
Thus, calling `data.identifier->clone()` will result in dereferencing a `nullptr`

**Does it reproduce on recent release?**

Yes

TreeOptimizer.cpp
<img width="973" alt="Screenshot 2023-02-20 at 11 31 50 AM" src="https://user-images.githubusercontent.com/124345785/220003312-64053191-4d6c-4444-9f13-a0360fe6c95c.png">

MonotonicityCheckVisitor.h
<img width="1134" alt="Screenshot 2023-02-20 at 11 33 21 AM" src="https://user-images.githubusercontent.com/124345785/220003492-9963700d-6d99-4b2e-896d-2c9c20b3c459.png">

**Comment by ucasfl** [comment]
`identifier` will be filled in `visit`.
