### ISSUE TITLE
how to update json object value

### ISSUE THREAD

**Issue by leonirvanel** [ClickHouse/ClickHouse#46575]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
# clickhouse version
 22.8.5.29

# table structure
CREATE TABLE jsontest2
(
    `id` String COMMENT '',
    `attribute_info` Object('json') COMMENT ''
)
ENGINE = ReplacingMergeTree
ORDER BY id
SETTINGS index_granularity = 8192 │

# initial data
node227 :) insert into jsontest2(id, attribute_info) values('1', '{"key" : 1}');

# try to update json object value but failed
node227 :) alter table jsontest2 update attribute.newkey = toString(attribute_info.key);

Syntax error: failed at position 39 ('.'):

alter table jsontest2 update attribute.newkey = toString(attribute_info.key);

Expected one of: token, Equals

**Comment by den-crane** [comment]
JSON is experimental and is not supported
