### ISSUE TITLE
Dereferencing nullptr in ReplacingSortedAlgorithm.cpp

### ISSUE THREAD

**Issue by joey-bd** [ClickHouse/ClickHouse#46580]
**Describe what's wrong**
Line 79 in ReplacingSortedAlgorithm.cpp is potentially dereferencing a nullptr because `selected_row.all_columns` may be a nullptr.
<img width="955" alt="Screenshot 2023-02-20 at 4 09 58 PM" src="https://user-images.githubusercontent.com/124345785/220048628-667d910a-a1e5-4483-909b-cc18faad8c83.png">

One way this happens is if the `if` branch at line 56 is taken. Line 66 calls `selected_row.clear()` which sets `all_columns = nullptr`.
<img width="523" alt="Screenshot 2023-02-20 at 4 09 33 PM" src="https://user-images.githubusercontent.com/124345785/220048599-9e690547-f3c9-4038-bcb1-c8497cac5fbb.png">

Line 76 checks if `selected_row.empty()` and it will not return true as `owned_chunk != nullptr`. But `selected_row.all_columns` is set to `nullptr` earlier hence line 79 could be dereferencing a nullptr.

**Does it reproduce on recent release?**
Yes
@KochetovNicolai

**Comment by vdimir** [comment]
Thank you for the question!

I suppose checking `selected_row.empty()` in the same condition is enough because if we call `clear`, then `empty` will return false, and we won't evaluate other conditions in `if` after `||`.
