### ISSUE TITLE
with Float32 datatype store data with only 4 decimal place, stored result is deviate with original data

### ISSUE THREAD

**Issue by flyly0755** [ClickHouse/ClickHouse#46585]
> You have to provide the following information whenever possible.

**With float data 1521.1795, store with Float32 in clickhouse, the result is 1521.17944336**

but with Float64, the result is correct, same as 1521.1795.
Float32 usually can store 6 decimal place, I think.

**How to reproduce**

* Which ClickHouse server version to use
 version 21.12.3 revision 54452
* Which interface to use, if matters
dbeaver
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
CREATE TABLE diagtest2.floattest
(

    `id` UInt32,

    `ft1` Nullable(Float32),

    `ft2` Nullable(Float64)
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192

**Comment by UnamedRus** [comment]
>  Float32 usually can store 6 decimal place, I think.

But in your number `1521.1795` there is more than 6 significant decimal digits
This gives from 6 to 9 [significant decimal digits](https://en.wikipedia.org/wiki/Significant_figures) precision.

**Comment by den-crane** [comment]
PG

```
psql=> select cast('1521.1795' as real);
 float4
---------
 1521.18
(1 row)

psql=> select cast('1521.1795' as double precision);
  float8
-----------
 1521.1795
(1 row)

```
