### ISSUE TITLE
in the readme, you are missing the prebuilt binaries

### ISSUE THREAD

**Issue by mickeyperlstein** [ClickHouse/ClickHouse#46612]
in the main readme on how to install
one cannot find the ubuntu apt install method that can be seen [here: ](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-clickhouse-on-ubuntu-20-04)

**Comment by alexey-milovidov** [comment]
It's listed in the docs: https://clickhouse.com/docs/en/install/#self-managed-install

**Comment by mickeyperlstein** [comment]
similar, but why are there multiple running options?
sudo service clickhouse-server start
sudo clickhouse start

which one to use and why, most users are ubuntu, please take time to help them. the docs are not easy to follow

**Comment by alexey-milovidov** [comment]
`sudo clickhouse start` is the proper option to run ClickHouse. It works on any Linux distribution.

`sudo service clickhouse-server start` is a limited option for systems with SystemD support, such as Ubuntu (but only for very modern versions, as older versions did not have SystemD). I recommend not using this option, as less compatible. People add this option to the docs for completeness.
