### ISSUE TITLE
UBsan Hung check failed - 'Connection error, will retry:  [Errno 111] Connection refused' - 'Cache usage is not allowed'

### ISSUE THREAD

**Issue by SmitaRKulkarni** [ClickHouse/ClickHouse#46615]
https://s3.amazonaws.com/clickhouse-test-reports/46487/f3f459fe3411d7a86d2048455d502d134f57a01c/stress_test__ubsan_.html

`Connection error, will retry:  [Errno 111] Connection refused`
https://s3.amazonaws.com/clickhouse-test-reports/46487/f3f459fe3411d7a86d2048455d502d134f57a01c/stress_test__ubsan_/hung_check.log

`Logical error: \'Cache usage is not allowed (query_id: 15764668-f9d5-44a9-bacd-67defd1d6ba7)\`
https://s3.amazonaws.com/clickhouse-test-reports/46487/f3f459fe3411d7a86d2048455d502d134f57a01c/stress_test__ubsan_/fatal_messages.txt

**Comment by kssenii** [comment]
it was fixed in https://github.com/ClickHouse/ClickHouse/pull/46521.
