### ISSUE TITLE
[feature] clickhouse-keeper `raft` four letter command and store last accepted peers config in /var/lib/clickhouse-keeper/peers on disk

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#46643]
**Use case**
Need to answer to following questions
Which current state of quorum, is quorum achieved or not?
Which nodes is stored in NuRaft quorum and which status of each node from perspective of current node?
Which status of the current node (leader, follower)?

**Describe the solution you'd like**

`echo "raft" | nc 127.0.0.1:2181`
store last "accepted" peers config in human readable format somewhere /var/lib/clickhouse-keeper/peers

**Describe alternatives you've considered**

Metrics in Prometheus endpoint

**Comment by Slach** [comment]
23.7+ 

`clickhouse-keeper client -q "get /keeper/config"`

will show current config state

but it will helpfull show
"node adding in progress"

**Comment by Slach** [comment]
@myrrc @pufit would you implement this feature or we should close issue?

**Comment by Slach** [comment]
moreover, currently "get /keeper/config" doesn't work when voting in progress

so i propose 
I propose to store last "accepted" peers config in human readable format for node somewhere `/var/lib/clickhouse-keeper/peers`

It allows us better understand when `reconfig add server.X=XXX` exactly rollout to the nodes

**Comment by Slach** [comment]
cc @myrrc @antonio2368 could you share your mention?

**Comment by myrrc** [comment]
While implementing `reconfig`, I've discussed it with @antonio2368, and the decision was against this text file.

In Zookeeper, the whole reconfig batch is decided on a single voting so we can write a file with an updated config -- it will be applied eventually.

On the other hand, in Keeper each command part is decided on separately due to limitations of Nuraft protocol so there is a consistency issue -- what if a reconfig add 1,2 fails on 2? What should be written to disk?

Same considerations were for implementing `/keeper/config` so it's not a "normal" node stored on disk.

**Comment by Slach** [comment]
let me describe details

currently, i tried to adopt `clickhouse-keeper` to Kubernetes

I decided to use `Statefulset` with replicas + headless kubernetes `Service` to deploy

each keeper node 

startup procedure:
- check service DNS endpoint if resolved then get /keeper/config
- if config contains current node, then generate config with all nodes
- if config doesn't contains current node, then generated config where current node `<start_as_learner>true</start_as_learner>`

after it, i also have readiness probe (start after 10 seconds, every 10 seconds) 
- if DNS service endpoint doesn't exists then exit 0 because this is first node in quorum
- else get /keeper/config and check is current node present
  - if yes exit 0
  - if no, then execute `reconfig add server.X=XXX` and exit 0
  
and liveness probe which start after 60 seconds every 10 seconds and just check ruok==imok

also, i have preStop hook:
- get /keeper/config, if config size > 1
- if yes, then execute `reconfig remove MY_ID` and wait when client connections in cons will empty, after that send signal to clickhouse-keeper process 


I try to avoid multiple execution the same command `reconfig add server.X` on multiple keeper nodes and i need to know when add will complete exactly

so implement of `raft` command which will work even when voting in progress or file on local disk with last accepted peer list, looks as the best solution

**Comment by alexey-milovidov** [comment]
> currently, i tried to adopt clickhouse-keeper to Kubernetes

Bad idea.

> if no, then execute reconfig add server.X=XXX and exit 0

Reconfig should never be automated.
