### ISSUE TITLE
ClickHouse download via curl throwing invalid certificate error

### ISSUE THREAD

**Issue by ozgune** [ClickHouse/ClickHouse#46657]
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**

I'm using the simple curl-based self-managed install on macOS Ventura

**Source of the ClickHouse**

curl https://clickhouse.com/ | sh

**Expected result**

Binary gets downloaded

**The actual result**

Fails with error. When I remove the "sh" part, I see an invalid certificate error.

```html
ozgun@192 dev % curl https://clickhouse.com/     
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<meta http-equiv="refresh" content="0">

<title>content.clickhouse.com | 526: Invalid SSL certificate</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />
```

**How to reproduce**

On MacOS, run the quick start guide steps.

**Comment by alexey-milovidov** [comment]
Does not reproduce anymore.

**Comment by alexey-milovidov** [comment]
Although this error may happen if you have a wrong DNS record for clickhouse.com.
