### ISSUE TITLE
schema inference for hive

### ISSUE THREAD

**Issue by lksv** [ClickHouse/ClickHouse#46655]
**Use case**

I would like to use quite complex Hive table. But there is no easy way to get schema. As I know, schema inference is possible for other (e.g. mysql, s3, etc.) but not for Hive.

**Describe the solution you'd like**

Be able to call `CREATE TABLE table ENGINE=Hive('thrift://my-hive:9083', 'db', 'table') PARTITION (...) ORDER BY ()` without specifying schema.

Table function `hive` needs to change a little bit as well (accept schema parameter as NULL or empty string).

 
**Additional context**

There is one workaround, but it is not usable in most use cases: If you have direct access hdfs, where hive keeps row files, you can fulfill schema by that files:

```
CREATE TABLE
 ...
ENGINE=Hive(..)
PARTITION (first_partition_key, second_parttion_key)
...
EMPTY AS
SELECT
   *,
   0::Int32 as first_partition_key,
   0:Int32 as second_parttion_key
FROM hdfs(...)
SETTINGS input_format_parquet_import_nested=1
```

But it is necessary to direct access to hdfs under Hive.

**Comment by alexey-milovidov** [comment]
We don't support Hive.
