### ISSUE TITLE
[RFC] replicated unique merge tree

### ISSUE THREAD

**Issue by hanfei1991** [ClickHouse/ClickHouse#46650]
This RFC is based on https://github.com/ClickHouse/ClickHouse/pull/44534. Let's review the idea of local unique merge tree first:

## Local Unique Merge Tree

When a new part comes, first check the cache to find out all the conflicted keys and their locations in parts, then generate `delete bitmaps` for the impacted parts.

The original RFC proposed to store bitmaps in the part, this voilents the immutibily of part, though. Nevertheless, we can store the bitmaps in another directory, and organize them like https://github.com/ClickHouse/ClickHouse/issues/19627 

We can concurrently write temp part, but have to commit writes one by one.

![image](https://user-images.githubusercontent.com/20884546/220377155-3debd8b6-75ff-422c-84a9-0816e59ddd5d.png)

Besides, what if two parts is merging when another part is generating bitmaps for the two old parts? Don't worry. If we decide to add bitmaps for a part, and know it's merging, we hold a buffer for the conflicting keys of this part. When the merge is commiting, it will collect the buffers and calculate bitmap.

Of course, merge commit and write commit can't process at the same time. They shard a lock called `write merge lock`

![image](https://user-images.githubusercontent.com/20884546/220402384-30679b9d-43ea-4e05-a5d1-966ca24113fc.png)

*In this case, merge commit must be after write commit*

## Replicated Version

We don't sync `delete bitmaps` and `cache` across replicas. We maintain the local bitmaps and cache, instead.

When we download/write a new part or merge parts, we do the same precedure as above. The difference is, a part with lower block id cannot generate bitmap for a part with higher block id, instead, it will generate bitmap for itself after checking parts with higher block id. It's easy to prove the eventual consistency.

![image](https://user-images.githubusercontent.com/20884546/220399374-0678cb6e-286b-4db4-9186-21e7b8e8c921.png)

*Part 2 generates bitmap for Part 1, and is generated a bitmap when checking Part 3, because 3>2*

Note that we have to download merge part by dependency, if not, there is a case like:

![image](https://user-images.githubusercontent.com/20884546/220368058-66d1a717-8b05-4eb5-8a8f-f06337eb4c98.png)

At first we both have part 1 part 2 in replica 1 / 2.

1. a new part comes, and generates bitmap for part 1 / 2
2. after 1, part 1 and 2 are merged, because of bitmap, the key 1 / 2 are deleted
3. replica 2 downloads part 1_2, then, we cannot read key 1 / 2 in replica 2

so we have to download part 3 before downloading 1 / 2

**Comment by JackyWoo** [comment]
hi hanfei1991, is there any plan for the RFC?

**Comment by hanfei1991** [comment]
@JackyWoo no

**Comment by JackyWoo** [comment]
Thank you
