### ISSUE TITLE
RWLockAcquiredWriteLocks

### ISSUE THREAD

**Issue by OrangeFlag** [ClickHouse/ClickHouse#4666]
Can you describe what that parameter mean? We have something strange on one node of cluster and when we research stats, we got those information:

|                               | Clickhouse2 | Clickhouse1 | Clickhouse7 | Clickhouse4 | Clickhouse5 | Clickhouse8 |
|-------------------------------|-------------|-------------|-------------|-------------|-------------|-------------|
| RWLockAcquiredWriteLocks      | 3516455     | 41          | 41          | 47          | 43          | 43          |
| RWLockReadersWaitMilliseconds | 722521281   | 14822206    | 403924      | 501652      | 1661477     | 2102570     |

So, as you see we have a problem with clickhouse2, about 3 hours of LockAcquiredWriteLocks a day
Maybe you can realize something like 'locks' list, that help to understand the heart of the matter?
This is almost all the information that I have and can tell

**Comment by alexey-milovidov** [comment]
RWLock metrics are related to table locks. As far as I remember, write lock is used for ALTER queries.
So, the question is: do you have significantly more ALTER queries on ClickHouse2?

**Comment by OrangeFlag** [comment]
@alexey-milovidov We have a lot of drop operation, because we have custom batch replication system, that gives us a guarantee of data consistency.

**Comment by blinkov** [comment]
@OrangeFlag, do you have any further questions?
