### ISSUE TITLE
Distributed Engine - How to choose sharding key by condition?

### ISSUE THREAD

**Issue by huwngnosleep** [ClickHouse/ClickHouse#46708]
My cluster has 3 shards. I have a distributed table with a column named "sharding_key" ranges from 1 to 100, I want records with sharding_key from 1 to 30 go to shard 1, sharding_key from 31 to 60 go to shard 2 and the rest go to shard 3.

How can  I implement that without manually insert into local table in each shard?

**Comment by realyota** [comment]
Your sharding key for `Distributed` engine should be set like this:

```
CREATE TABLE distributed_table
(
....
)
ENGINE = Distributed(cluster_name, database, table, multiIf(sharding_key <= 30, 1, sharding_key <= 60, 2, 3))
```
