### ISSUE TITLE
toStartOfDay is not working when combined with timezones on 1970-01-01

### ISSUE THREAD

**Issue by inakisoriamrf** [ClickHouse/ClickHouse#46713]
toStartOfDay is not working when combined with timezones on 1970-01-01

Working:
```
SELECT version()

┌─version()─────────────────┐
│ 22.3.10.24.altinitystable │
└───────────────────────────┘


SELECT
    toDateTime('1970-01-01 00:00:00') AS d0,
    toStartOfDay(d0) AS d1

┌──────────────────d0─┬──────────────────d1─┐
│ 1970-01-01 00:00:00 │ 1970-01-01 00:00:00 │
└─────────────────────┴─────────────────────┘


SELECT
    toDateTime('1970-01-01 00:00:00') AS d0,
    toTimezone(d0, 'Europe/Madrid') AS d1


┌──────────────────d0─┬──────────────────d1─┐
│ 1970-01-01 00:00:00 │ 1970-01-01 01:00:00 │
└─────────────────────┴─────────────────────┘

```

Not working (note the 1970-01**-02** 00:00:00)
```
SELECT
    toDateTime('1970-01-01 00:00:00') AS d0,
    toStartOfDay(d0, 'Europe/Madrid') AS d1

┌──────────────────d0─┬──────────────────d1─┐
│ 1970-01-01 00:00:00 │ 1970-01-02 00:00:00 │
└─────────────────────┴─────────────────────┘


```
Fiddle with the last version failing

https://fiddle.clickhouse.com/a1c76fdc-b4b6-461b-97d5-1f1c3fa78680

**Does it reproduce on recent release?**

Yes, in lastest

**Expected behavior**

It returns 1970-01-01 00:00:00

**Comment by rschu1ze** [comment]
1970-01-01 with timezones is a bit buggy ... #42653 #42615

**Comment by alexey-milovidov** [comment]
> 22.3.10.24.altinitystable

This is not the official build.

We *strongly* do not recommend using alternative builds from third-party companies.

Read this on why you can't expect any support for "altinity": https://clickhouse.com/docs/knowledgebase/difference_between_official_builds_and_3rd_party
