### ISSUE TITLE
Parametrized view - what is the syntax to use in IN clause? Is it possible to use parameter in subquery?

### ISSUE THREAD

**Issue by ermadan** [ClickHouse/ClickHouse#46741]
It's not clear from the [documentation](https://clickhouse.com/docs/en/sql-reference/statements/create/view/) or [Altinity article](https://kb.altinity.com/altinity-kb-queries-and-syntax/altinity-kb-parameterized-views/) how to use parametrized views.
Parametrized view works fine with the equality clause:
```
create or replace view live_agents_pv2 as
select * FROM default.service_library sl 
    where account_id = {account_id2:Int32} 
```
Fails with error UNKNOWN_QUERY_PARAMETER with IN clause:
```
create or replace view live_agents_pv2 as
select * FROM default.service_library sl 
    where account_id in ({account_id2:Array(Int32)}) 
```
It also fails when I use a parameter in a nested query:
```
create or replace view live_agents_pv2 as
select * from (
select * FROM default.service_library sl 
    where account_id = {account_id2:Int32} )
```

version 23.1.3.5

DDL:
```
CREATE TABLE default.service_library
(
account_id Int32,
checksum String,
cluster_agent_id Int32,
entity_guid String,
language String,
name String,
real_agent_id Int32,
version String,
created_at DateTime DEFAULT now(),
run_id Int32,
is_dead UInt8 DEFAULT 0
)
ENGINE = ReplacingMergeTree(created_at)
ORDER BY (account_id, entity_guid, name, version, cluster_agent_id, real_agent_id)
TTL created_at + toIntervalDay(3)
```

**Comment by ermadan** [comment]
DDL:
` CREATE TABLE default.service_library
(
    `account_id` Int32,
    `checksum` String,
    `cluster_agent_id` Int32,
    `entity_guid` String,
    `language` String,
    `name` String,
    `real_agent_id` Int32,
    `version` String,
    `critical` Array(String),
    `high` Array(String),
    `medium` Array(String),
    `low` Array(String),
    `critical_cnt` UInt8,
    `high_cnt` UInt8,
    `medium_cnt` UInt8,
    `low_cnt` UInt8,
    `created_at` DateTime DEFAULT now(),
    `run_id` Int32,
    `is_dead` UInt8 DEFAULT 0
)
ENGINE = ReplacingMergeTree(created_at)
ORDER BY (account_id, entity_guid, name, version, cluster_agent_id, real_agent_id)
TTL created_at + toIntervalDay(3)
`

**Comment by winterrobert** [comment]
Yeah it would be great with some examples and notes about any limitations that exists.
