### ISSUE TITLE
Join in materialized view is 60x slower than in select statement.

### ISSUE THREAD

**Issue by qiang5714** [ClickHouse/ClickHouse#46757]
**Describe the situation**

Seems materialized view with join not working with **FillRightFirst** plan, please loot at the script blew.

Thank you for your time. 

Select statement statistics: 
`0 rows in set. Elapsed: 0.021 sec. Processed 262.02 thousand rows, 2.10 MB (12.69 million rows/s., 101.50 MB/s.)`

Materialized view statistics(a insert statement to source table):

`1 row in set. Elapsed: 1.422 sec.`

**How to reproduce**
1. Create null table t_null;
2. Create mergetree table t_numbers with 100000000 rows;
3. Execute Select Statement 1 as blow code;
4. Create materialized view with the same query;
5. Insert only 1 record into t_null to trigger materialized view;

* Which ClickHouse server version to use
ClickHouse client version 22.8.13.20 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.8.13 revision 54460.

* Non-default settings, if any
None

* `CREATE TABLE` statements for all tables involved

`CREATE TABLE t_numbers
(
    `A` UInt64,
    `B` String
)
ENGINE = MergeTree
ORDER BY A;`

 `CREATE TABLE t_null
(
    `A` UInt64,
    `B` String
)
ENGINE = Null;`

`CREATE MATERIALIZED VIEW mv_null
ENGINE = MergeTree
ORDER BY A AS
SELECT
    null_outer.A,
    concat(null_outer.B, subquery.B)
FROM t_null AS null_outer
LEFT JOIN
(
    SELECT
        num.A,
        'inner' AS B
    FROM t_numbers AS num
    INNER JOIN t_null AS null_inner ON num.A = null_inner.A
) AS subquery ON null_outer.A = subquery.A;`

* Sample data for all these tables

`INSERT INTO t_numbers SELECT
    number,
    toString(cityHash64(number))
FROM numbers(100000000)`

* Queries to run that lead to slow performance

Query 1, which runs very fast!

`SELECT
    null_outer.A,
    concat(null_outer.B, subquery.B)
FROM t_null AS null_outer
LEFT JOIN
(
    SELECT
        num.A,
        'inner' AS B
    FROM t_numbers AS num
    INNER JOIN t_null AS null_inner ON num.A = null_inner.A
) AS subquery ON null_outer.A = subquery.A;
`
Query 2, which runs very slow!

`INSERT INTO t_null VALUES(1, 'insert');`
 

**Expected performance**
Statement in materialized view runs as fast as select statement, instead of 67x slow.

**Additional context**

If we check the plan, clickhouse choose FillRightFirst for both inner and outer join, may be materialized view is not using the same plan?

EXPLAIN
SELECT
    null_outer.A,
    concat(null_outer.B, subquery.B)
FROM t_null AS null_outer
LEFT JOIN
(
    SELECT
        num.A,
        'inner' AS B
    FROM t_numbers AS num
    INNER JOIN t_null AS null_inner ON num.A = null_inner.A
) AS subquery ON null_outer.A = subquery.A

Query id: 0e4c95b7-204e-4922-8d01-414f6ad86758

┌─explain──────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))                                                      │
│   Join (JOIN **FillRightFirst**)                                                                     │
│     Expression (Before JOIN)                                                                     │
│       ReadFromStorage (Null)                                                                     │
│     Expression ((Joined actions + (Rename joined columns + (Projection + Before ORDER BY))))     │
│       Join (JOIN **FillRightFirst**)                                                                 │
│         Expression (Before JOIN)                                                                 │
│           ReadFromMergeTree (rtd.t_numbers)                                                      │
│         Expression ((Joined actions + (Rename joined columns + (Projection + Before ORDER BY)))) │
│           ReadFromStorage (Null)                                                                 │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by den-crane** [comment]
You compare incorrectly.

t_null has ENGINE = Null, so it's empty in the SELECT and not empty in the MATVIEW!!!

```sql
CREATE TABLE t_Memory ( A UInt64,B String ) ENGINE = Memory;
INSERT INTO t_Memory VALUES(1, 'insert');

SELECT null_outer.A, concat(null_outer.B, subquery.B) 
  FROM t_Memory AS null_outer LEFT JOIN 
 ( SELECT num.A, 'inner' AS B FROM t_numbers AS num 
   INNER JOIN t_Memory AS null_inner ON num.A = null_inner.A ) AS subquery ON null_outer.A = subquery.A; 

1 row in set. Elapsed: 0.406 sec. Processed 100.00 million rows, 800.00 MB (246.21 million rows/s., 1.97 GB/s.)
```

**Comment by den-crane** [comment]
You can use this 

```
CREATE MATERIALIZED VIEW mv_null ENGINE = MergeTree ORDER BY A AS SELECT null_outer.A, concat(null_outer.B, subquery.B) 
   FROM t_null AS null_outer 
   LEFT JOIN ( 
               SELECT A, 'inner' AS B FROM t_numbers where A in (select A from t_null)    
             ) AS subquery ON null_outer.A = subquery.A;

INSERT INTO t_null VALUES(1, 'insert');

1 row in set. Elapsed: 0.021 sec.

INSERT INTO t_null VALUES(1, 'insert');

1 row in set. Elapsed: 0.014 sec.
```

**Comment by qiang5714** [comment]
@den-crane 
Thank you for you time. I understand that t_null is not null in materialized view, I did this on purpose because I want to find a way to trigger a materialized view from another table except the left most one in the Join.

Suppose we have two tables, t_left and t_right, a materialized view will not trigger by t_right if we use 

`t_left join t_right on t_left.id = t_right.id`

but, if my program can collect both t_left.id and t_right.id,  and we change the view to 

`t_null left join (t_left join t_right on t_left.id = t_right.id) as t_inner on t_null.id = t_inner.id `

then all data changed in t_left and t_right will trigger the materialized view。 And, If t_left and t_right is very large, we should use t_null as a filter, put it in the right side, that should make t_left join t_right very fast， that's what I want.  just like what your advice did:

`t_null left join (t_left join t_right on t_left.id = t_right.id and **t_right.id in (select trigger.id from t_null trigger)**) as t_inner on t_null.id = t_inner.id 

My question is, Why my query is slow than yours, or **why IN operator is faster than join**?

Thank you.

**Comment by den-crane** [comment]
Clickhouse inner join has an optimization to join with empty tables:

```sql
CREATE TABLE left ( A UInt64,B String ) ENGINE = MergeTree ORDER BY A as 
SELECT number, toString(cityHash64(number)) FROM numbers(100000000);

CREATE TABLE right ( A UInt64, B String ) ENGINE = MergeTree ORDER BY A;

select count() from left inner join right using A;

1 row in set. Elapsed: 0.010 sec. Processed 261.64 thousand rows, 2.09 MB (27.24 million rows/s., 217.93 MB/s.)


insert  into right SELECT number, toString(cityHash64(number)) FROM numbers(1);

select count() from left inner join right using A;
1 row in set. Elapsed: 0.367 sec. Processed 100.00 million rows, 800.00 MB (272.51 million rows/s., 2.18 GB/s.)
```
what's why SELECT with join with engine Null is fast.

---------------------
Clickhouse JOIN does not use indexes, Clickhouse IN uses indexes.

```sql
select count() from left inner join right using A;
1 row in set. Elapsed: 0.367 sec. Processed 100.00 million rows, 800.00 MB (272.56 million rows/s., 2.18 GB/s.)

select count() from left inner join right using B;
1 row in set. Elapsed: 1.030 sec. Processed 100.00 million rows, 2.84 GB (97.12 million rows/s., 2.76 GB/s.)

select count() from left where A in (select A from right);
1 row in set. Elapsed: 0.010 sec. Processed 8.19 thousand rows, 65.54 KB (856.87 thousand rows/s., 6.85 MB/s.)

select count() from left where B in (select B from right);
1 row in set. Elapsed: 0.932 sec. Processed 100.00 million rows, 2.84 GB (107.29 million rows/s., 3.05 GB/s.)
```
`where A in (` is fast because it uses primary index of the `left`

**Comment by qiang5714** [comment]
Got it, no more questions. Thank you very much!
