### ISSUE TITLE
 DB::Exception: New storage policy `default` shall contain volumes of old one

### ISSUE THREAD

**Issue by windylcx** [ClickHouse/ClickHouse#46759]
alter table test.t1  modify setting storage_policy='local_and_remote_one_g';

![image](https://user-images.githubusercontent.com/917238/220834006-088ed4cd-2600-48fb-8706-2fbd94ae955b.png)

i try to modify the exists table's storage policy, it show the exception message, don't know why .

**Comment by Algunenano** [comment]
You can't change the storage policy if the new one doesn't contain the volume from the old one.
