### ISSUE TITLE
NTILE is scary

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#46763]
**Describe the issue**

I can write this:
```
ntile(4) OVER (ORDER BY price DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS quartile
```

But this does not work:
```
ntile(4) OVER (ORDER BY price DESC) AS quartile
```

While it works in MS SQL Server: https://learn.microsoft.com/en-us/sql/t-sql/functions/ntile-transact-sql?view=sql-server-ver16

**Comment by vdimir** [comment]
Since `ntile` supports only a particular frame type, we can use it without explicit specification and forbid specifying any other ones.

In MS SQL the function 'ntile' may not have any window frame.
