### ISSUE TITLE
After upgrading to 23.1.3.5, I got a error named UNKNOWN_IDENTIFIER

### ISSUE THREAD

**Issue by Onehr7** [ClickHouse/ClickHouse#46767]
ClickHouse server version: 23.1.3.5

SQL:
```sql
SELECT 
	a.v
FROM 
	(SELECT arrayJoin(['v1', 'v2', 'v3']) AS v) AS a
JOIN (
	SELECT 'v1' AS v) AS b
ON 
	a.v = b.v
```

Then `SELECT * FROM system.errors`, 
the `last_error_message`  of  `UNKNOWN_IDENTIFIER` is 
`Missing columns: 'b.v' 'v' while processing query: 'v = b.v', required columns: 'v' 'b.v' 'v' 'b.v'`

**Comment by UnamedRus** [comment]
23.2 works

```

SELECT a.v
FROM
(
    SELECT arrayJoin(['v1', 'v2', 'v3']) AS v
) AS a
INNER JOIN
(
    SELECT 'v1' AS v
) AS b ON a.v = b.v

Query id: cbb1721f-d9e7-43c4-9b04-7945ea6a574c

┌─v──┐
│ v1 │
└────┘

1 row in set. Elapsed: 0.003 sec.


```

**Comment by Palooz** [comment]
Upgraded from `22.12.3.5` to `23.2.4.12` and started seeing this `UNKNOWN_IDENTIFIER` for the first time.
No operational changes except the upgrade, same data, same schemas.

For me, the error message is:
```
Missing columns: 'name' 'i1.name' while processing query: '(i1.name AS `--i1.name`) = concat('.inner.', name AS `--t.name`)', required columns: 'i1.name' 'name' 'i1.name' 'name'
```
