### ISSUE TITLE
how to delete records from a table use filter condition in another table?

### ISSUE THREAD

**Issue by huwngnosleep** [ClickHouse/ClickHouse#46761]
I have a distributed table, I ran:

```ALTER TABLE db.local_table ON CLUSTER cluster_name DELETE WHERE key IN db.local_temp_table```

each local_table has ~10M records, distributed table is total 30M and local_temp_table has ~9M records
but this query took a very long time to run, and I no record deleted data in local_table

what is the correct way to do it?

**Comment by DerekChia** [comment]
how long is very long? please share the output of `system.mutations`
