### ISSUE TITLE
Error in query execution

### ISSUE THREAD

**Issue by vinith-reddy25** [ClickHouse/ClickHouse#46774]
**Query1**: """select toStartOfQuarter(toDateTime(transactiondate)) as transactiondate,SUM(debitamountinaccountingcurrency) as sum from callhealth.callhealth_financialledger GROUP BY toStartOfQuarter(toDateTime(transactiondate))"""

**Query2**: """select toStartOfQuarter(toDateTime(transactiondate)) as transactiondate,SUM(debitamountinaccountingcurrency) as sum from callhealth.callhealth_financialledger GROUP BY toStartOfQuarter(toDateTime(transactiondate)) as transactiondate"""

**Query1** is giving following error, where as **Query2** is working fine. Both queries are technically same. In clickhouse only I'm facing this issue with Query1.

giving error as follows:
"""Code: 215. DB::Exception: Column `transactiondate` is not under aggregate function and not in GROUP BY. Have columns: ['sum(debitamountinaccountingcurrency)','toStartOfQuarter(toDateTime(toStartOfQuarter(toDateTime(transactiondate))))']: While processing toStartOfQuarter(toDateTime(transactiondate)), sum(debitamountinaccountingcurrency). (NOT_AN_AGGREGATE) (version 23.2.1.2151 (official build))"""

**Comment by den-crane** [comment]
@Algunenano

**Comment by vinith-reddy25** [comment]
Getting same error for "22.3.15" tag for docker images "clickhouse/clickhouse-server" and "bitnami/clickhouse".

I want to use bitnami charts, can you tell for which tag of "bitnami/clickhouse", it will work fine

**Comment by Algunenano** [comment]
Out of the 2 queries, the first one has never worked AFAIK and the second one has worked in the past and it's a bug. It's also fixed by https://github.com/ClickHouse/ClickHouse/pull/46609

> I want to use bitnami charts, can you tell for which tag of "bitnami/clickhouse" image(https://hub.docker.com/r/bitnami/clickhouse/), it will work fine

No idea how bitnami creates its tags. Sorry. For CH you could use something like https://fiddle.clickhouse.com/98dcae7f-ea5a-4e12-9a0e-9e2eb9f56b80 to test it, but it's going to find only old and unpatched releases which will contain known bugs and vulnerabilities.

**Comment by vinith-reddy25** [comment]
> 

If Query 2 is also not working in latest version, then What is the equivalent query to it? There will be an equivalent query that will be working with the same output
