### ISSUE TITLE
Getting Clickhouse to start on reboot of Ubuntu 20 LTS

### ISSUE THREAD

**Issue by marklit** [ClickHouse/ClickHouse#46808]
I've installed ClickHouse 22.13.1.2332 on Ubuntu 20 LTS.

```bash
$ curl https://clickhouse.com/ | sh
$ sudo ./clickhouse install
```

When I reboot the system I need to start ClickHouse again manually rather than it starting automatically. The install docs lead me to believe this command will allow ClickHouse to automatically launch after each reboot but this doesn't work.

```bash
$ sudo systemctl enable clickhouse-server
```

```
Failed to enable unit: Unit file clickhouse-server.service does not exist.
```

Any idea how I get ClickHouse to launch automatically after rebooting Ubuntu 20 LTS?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/install/#install-from-deb-packages

or 

```
sudo curl -o /etc/systemd/system/clickhouse-server.service https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-server.service 

systemctl daemon-reload
systemctl enable clickhouse-server
```

**Comment by marklit** [comment]
Awesome, thank you.
