### ISSUE TITLE
Why Skipping Indexes not work in or querys?

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#46807]
Case like this:
 CREATE TABLE default.ips
(
    time DateTime default now(),
	srcIp String,
    dstIp String,
    INDEX srcIp_index srcIp TYPE bloom_filter GRANULARITY 1,
    INDEX dstIp_index dstIp TYPE bloom_filter GRANULARITY 1	
)
ENGINE = MergeTree
ORDER BY time

insert into  default.ips(srcIp,dstIp) values('10.1.1.1','10.1.1.2'),('10.1.1.3','10.1.1.4')

query:
select count(1) from default.ips where  (srcIp = '1.1.1.1')
![image](https://user-images.githubusercontent.com/5574794/221088309-0b9d1176-3eb1-4931-81be-14a7f1147476.png)
srcIp_index work!

select count(1) from default.ips_local where  (srcIp = '1.1.1.1' or dstIp = '1.1.1.1')
![image](https://user-images.githubusercontent.com/5574794/221088448-70a8c5e7-ad8a-4bc4-8045-f7257fea8c73.png)
both srcIp_index  dstIp_index not wok!!!

Is it possible make srcIp_index and  dstIp_index work together to speed up query?

**Comment by den-crane** [comment]
You can use combined index `(srcIp, dstIp) TYPE bloom_filter GRANULARITY 1` it will work for all cases: `where (dstIp = '1.1.1.1')`, `where (srcIp = '1.1.1.1')`,  `where (srcIp = '1.1.1.1' and dstIp = '1.1.1.1')`,  `where (srcIp = '1.1.1.1' or dstIp = '1.1.1.1')`.

```
CREATE TABLE default.ips
(
time DateTime default now(),
srcIp String,
dstIp String,
INDEX Ip_index (srcIp, dstIp) TYPE bloom_filter GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY time;
```

**Comment by kaynewu** [comment]
> You can use combined index `(srcIp, dstIp) TYPE bloom_filter GRANULARITY 1` it will work for all cases: `where (dstIp = '1.1.1.1')`, `where (srcIp = '1.1.1.1')`, `where (srcIp = '1.1.1.1' and dstIp = '1.1.1.1')`, `where (srcIp = '1.1.1.1' or dstIp = '1.1.1.1')`.
> 
> ```
> CREATE TABLE default.ips
> (
> time DateTime default now(),
> srcIp String,
> dstIp String,
> INDEX Ip_index (srcIp, dstIp) TYPE bloom_filter GRANULARITY 1
> )
> ENGINE = MergeTree
> ORDER BY time;
> ```

but this way only applicable for those two field,  what if there are ten or more fields?  Random combination of ten fields  is quite a lot

**Comment by den-crane** [comment]
> but this way only applicable for those two field, what if there are ten or more fields?

Why do you think this way only applicable for two field?

You don't have much options. OR is not implemented for multiple skip indexes.

10 skip indexes is a good performance killer.
