### ISSUE TITLE
Performance degrades with projection for unrelated groupBy having query

### ISSUE THREAD

**Issue by BernhardCW** [ClickHouse/ClickHouse#46818]
**Describe the situation**
The groupBy queryplan changes from ReadFromMergeTree to ReadFromStorage(projection) after creating an (unrelated) projection 

```
CREATE TABLE bench1
(
    year Int32,
    group Int16,
    id FixedString(64),
    value Float32
) ENGINE = MergeTree
PARTITION BY year
ORDER BY ( group );
```

**Query 1:** Aggregate  `SELECT avg(value) FROM bench1 GROUP BY group HAVING year=2021`
**Query 2:** Groupby for a specific ID `SELECT avg(value) FROM bench1 GROUP BY id HAVING id = (select id from bench1 limit 1)
`
Situation **without** projection: 
* Query1 is fast (as expected): 10000 rows in set. Elapsed: **0.354 sec.** Processed 166.68 million rows, 1.67 GB (471.51 million rows/s., 4.72 GB/s.)
* Query2 is slow (as expected): 1 row in set. Elapsed: 11.562 sec. Processed 500.00 million rows, 32.00 GB (43.25 million rows/s., 2.77 GB/s.)

Now we add a projection on id to speed up Query 2.
```
ALTER TABLE bench1 ADD PROJECTION id (select * order by id)
ALTER TABLE bench1 MATERIALIZE projection id
```

Situation **with** projection:
* Query1 is slower (**not expected**): 10000 rows in set. Elapsed: **0.577 sec.** Processed 166.68 million rows, 1.67 GB (289.12 million rows/s., 2.89 GB/s.)
* Query2 is fast (expected): 1 row in set. Elapsed: 0.023 sec. Processed 204.80 thousand rows, 13.14 MB (8.99 million rows/s., 576.58 MB/s.)

**How to reproduce**
* Clickhouse Server 23.2.1 revision 54461
* Test data used
```
INSERT INTO bench1 SELECT 
		toInt16(randUniform(2019, 2022)),
		toInt16(randUniform(0, 10000)),
		randomPrintableASCII(64),
		randUniform(0,100)
	FROM numbers(500_000_000)
```

**Expected performance**
No degraded performance after unrelated projection is created

**Additional context**

The queryplan for query1 changes from
```
┌─explain─────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY)) │
│   Aggregating                               │
│     Expression (Before GROUP BY)            │
│       ReadFromMergeTree (default.bench1)    │
│       Indexes:                              │
│         MinMax                              │
│           Keys:                             │
│             year                            │
│           Condition: (year in [2021, 2021]) │
│           Parts: 10/25                      │
│           Granules: 20351/61045             │
│         Partition                           │
│           Keys:                             │
│             year                            │
│           Condition: (year in [2021, 2021]) │
│           Parts: 10/10                      │
│           Granules: 20351/20351             │
│         PrimaryKey                          │
│           Condition: true                   │
│           Parts: 10/10                      │
│           Granules: 20351/20351             │
└─────────────────────────────────────────────┘
```
to 
  
```
┌─explain──────────────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))                  │
│   Aggregating                                                │
│     Expression (Before GROUP BY)                             │
│       ReadFromStorage (MergeTree(with Normal projection id)) │
└──────────────────────────────────────────────────────────────┘
```

Note this **only** happens when the `having year=2021` is included. Otherwise the queryplan stays the same.

Note2: this is a minimal synthetic example. For our usecase performance for query1 droped from 0.36s to 6.3s.

**Comment by nickitat** [comment]
we build not optimal pipeline in case of reading from projection (aggregation will be single-threaded). issue #38801
as a workaround you could set `allow_experimental_projection_optimization = 0`
