### ISSUE TITLE
Clickhouse process crashed during execute queries

### ISSUE THREAD

**Issue by yej2021** [ClickHouse/ClickHouse#46829]
> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

Not reproduce .

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

The query does not cause the instance to crash.

**Error message and/or stacktrace**

2023.02.03 15:59:49.513281 [ 31475 ] {} <Fatal> BaseDaemon: (version 21.3.4.25, no build id) (from thread 28103) (query_id: 65251581-513a-4cec-a8c3-87a43be75de7) Received signal Aborted (6)
2023.02.03 15:59:49.513293 [ 31475 ] {} <Fatal> BaseDaemon: 
2023.02.03 15:59:49.513304 [ 31475 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fb653d2e4e7 0x7fb653d2fbd8 0xdefc9e0 0x94736b1 0x94736ea
2023.02.03 15:59:49.524813 [ 31475 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x364e7 in /usr/lib64/libc-2.17.so
2023.02.03 15:59:49.524841 [ 31475 ] {} <Fatal> BaseDaemon: 4. abort @ 0x37bd8 in /usr/lib64/libc-2.17.so
2023.02.03 15:59:49.583228 [ 31475 ] {} <Fatal> BaseDaemon: 5. _Unwind_Resume @ 0xdefc9e0 in /opt/ClickHouse-v21.3.4.25-lts/clickhouse/bin/clickhouse
2023.02.03 15:59:49.583583 [ 31475 ] {} <Fatal> BaseDaemon: 6. ? @ 0x94736b1 in /opt/ClickHouse-v21.3.4.25-lts/clickhouse/bin/clickhouse
2023.02.03 15:59:49.586193 [ 31475 ] {} <Fatal> BaseDaemon: 7. void boost::context::detail::fiber_entry<boost::context::detail::fiber_record<boost::context::fiber, FiberStack&, DB::RemoteQueryExecutorRoutine> >(boost::context::detail::transfer_t) @ 0x94736ea in /opt/ClickHouse-v21.3.4.25-lts/clickhouse/bin/clickhouse
2023.02.03 15:59:57.486762 [ 31475 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 6EA6ADD699C24515305E9C7410CA2970. There is no information about the reference checksum.
2023.02.03 16:00:10.513599 [ 22711 ] {} <Fatal> Application: Child process was terminated by signal 6.

**Additional context**

> Add any other context about the problem here.

**Comment by tavplubix** [comment]
You are using a custom build, so it's your responsibility to debug and fix crashes like this. Also 21.3 is obsolete, it's almost 2 years old. Feel free to reopen this issue if it can be reproduced with a recent release from the official ClickHouse repository.
