### ISSUE TITLE
Bc check: Existing table metadata in ZooKeeper differs in TTL

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#46834]
https://s3.amazonaws.com/clickhouse-test-reports/46820/7ff8d2d3d5a5ff77bff2e3c41b57458183bbf623/stress_test__debug_.html

```
[ 419228 ] {} <Error> test_metadata_cache.check_part_metadata_cache (ReplicatedMergeTreeAttachThread): Initialization failed, table will remain readonly. Error: Existing table metadata in ZooKeeper differs in TTL. Stored in ZooKeeper: , parsed from ZooKeeper: , local: p + toIntervalYear(10)

```

It's something new: [link](https://play.clickhouse.com/play?user=play#d2l0aCAKJyVCYWNrd2FyZCUnIGFzIG5hbWVfcGF0dGVybiwKJyVFeGlzdGluZyB0YWJsZSBtZXRhZGF0YSBpbiBab29LZWVwZXIgZGlmZmVycyBpbiBUVEwlJyBhcyBjb250ZXh0X3BhdHRlcm4sCicyMDIyLTA5LTAxJyBhcyBzdGFydF9kYXRlLAooNDU0NjEpIGFzIG5vaXN5X3BycywKKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIGFzIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpzZWxlY3QgCnRvU3RhcnRPZkhvdXIoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCBhbnkocmVwb3J0X3VybCkKZnJvbSBjaGVja3Mgd2hlcmUgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyIG5vdCBpbiAKKHNlbGVjdCBwdWxsX3JlcXVlc3RfbnVtYmVyIGFzIHBybiBmcm9tIGNoZWNrcyB3aGVyZSBwcm4hPTAgYW5kIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgY2hlY2tfbmFtZSBpbiBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpIAphbmQgdGVzdF9uYW1lIGxpa2UgbmFtZV9wYXR0ZXJuIGFuZCB0ZXN0X2NvbnRleHRfcmF3IGlsaWtlIGNvbnRleHRfcGF0dGVybgphbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gbm9pc3lfcHJzCmFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knLCAnZmFpbHVyZScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj)

Probably triggered by 01233_check_table_with_metadata_cache

**Comment by tavplubix** [comment]
Hm, looks like it started to fail when 23.2 was released

**Comment by tavplubix** [comment]
Probably related to https://github.com/ClickHouse/ClickHouse/pull/33933

**Comment by sunny19930321** [comment]
let me look at this problem

**Comment by sunny19930321** [comment]
the problem doesn't seem to be due to pr https://github.com/ClickHouse/ClickHouse/pull/33933. when zookeeper gets the TTL, it doesn't get it

**Comment by alexey-milovidov** [comment]
Most likely it is no longer relevant.
