### ISSUE TITLE
Remove "asynchronous connection drain"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#46843]
It causes complications.

**Comment by alexey-milovidov** [comment]
This pull request is to be reverted: https://github.com/ClickHouse/ClickHouse/pull/25674

**Comment by alexey-milovidov** [comment]
This fixes #46806.

**Comment by amosbird** [comment]
> This fixes #46806.

According to the discussion in https://github.com/ClickHouse/ClickHouse/issues/37686 it seems that this PR does not actually address #46806. It appears to be resolved by https://github.com/ClickHouse/ClickHouse/pull/67702.
