### ISSUE TITLE
how to filter data in json array with jsonpath

### ISSUE THREAD

**Issue by yepengxj** [ClickHouse/ClickHouse#46851]
I use jsonpath to filter json array, like 
`select JSON_QUERY('{"arr":[{"pric":10}, {"pric": 20}]}', '$.arr[?(@.pric==10)]')
`
but clickhouse can't parse jsonpath. 
`DB::Exception: Unable to parse JSONPath: While processing JSON_QUERY('{"arr":[{"pric":10}, {"pric": 20}]}', '$.arr[?(@.pric==10)]'). (BAD_ARGUMENTS) (version 22.8.3.13 (official build))`
Is that way to filter json array data? Thanks

clickhouse version : 22.8.3.13

**Comment by den-crane** [comment]
```sql
SELECT
    JSON_QUERY('{"arr":[{"pric":10}, {"pric": 20}]}', '$.arr[*].pric') AS x,
    CAST(x, 'Array(Int64)') AS y,
    CAST(has(y, 10), 'Bool') AS z


┌─x────────┬─y───────┬─z────┐
│ [10, 20] │ [10,20] │ true │
└──────────┴─────────┴──────┘
```

**Comment by den-crane** [comment]
see https://docs.oracle.com/database/121/SQLRF/functions091.htm#SQLRF56718

**Comment by den-crane** [comment]
```sql
SELECT
    JSONExtract('{"arr":[{"pric":10}, {"pric": 20}]}', 'arr', 'Array(Tuple(Int64))') AS x,
    x.1 AS y,
    CAST(has(y, 10), 'Bool') AS z

┌─x───────────┬─y───────┬─z────┐
│ [(10),(20)] │ [10,20] │ true │
└─────────────┴─────────┴──────┘
```

**Comment by yepengxj** [comment]
@den-crane Thanks for help
