### ISSUE TITLE
can i use sql to create aggregate function 

### ISSUE THREAD

**Issue by zhujing0227** [ClickHouse/ClickHouse#46916]
i can use sql to create a function according this https://clickhouse.com/docs/en/sql-reference/statements/create/function
```sql
CREATE FUNCTION name [ON CLUSTER cluster] AS (parameter0, ...) -> expression
CREATE FUNCTION linear_equation AS (x, k, b) -> k*x + b;
```
but how to create aggregate function use sql?

**Comment by ucasfl** [comment]
No, currently, user defined aggregate functions is not suppoted.
