### ISSUE TITLE
Clickhouse-client Code: 36. DB::Exception: Positional options are not supported. (BAD_ARGUMENTS) bash script

### ISSUE THREAD

**Issue by mtgnoah** [ClickHouse/ClickHouse#46973]
Here is my bash script for inserting parquets in parallel to clickhouse. It keeps giving me the error I put in the title though and I don't know why. I tried running the command without the backslash and I still get the same issue. I was attempting to adapt this tutorial to my needs [https://tech.marksblogg.com/faster-clickhouse-imports-csv-parquet-mysql.html](url)

```
#!/bin/bash
time (for FILENAME in /mnt/sdc/traces/part-*.snappy.parquet; do
            echo $FILENAME
            xargs -P 6 -n 1 -0 clickhouse-client --receive_timeout=100000 --query=\"INSERT INTO ethereum.traces FORMAT Parquet\" < $FILENAME
        done)
```

**Comment by den-crane** [comment]
You have misunderstood how xargs works.
Even if you fix a typo your script will run in a single thread.

You should use this

```
find /mnt/sdc/traces/ -type f -name 'part-*.snappy.parquet' | xargs -P 6 -n 1 clickhouse-client --receive_timeout=100000 --query="INSERT INTO ethereum.traces FORMAT Parquet"
```
