### ISSUE TITLE
JSON: How to define a Data Skipping Index for a JSON key

### ISSUE THREAD

**Issue by ertyagi** [ClickHouse/ClickHouse#46974]
How do define a [Data Skipping Index](https://clickhouse.com/docs/en/guides/improving-query-performance/skipping-indexes ) for a key in a JSON column?

Sample table:
`CREATE TABLE json_test
(
    rowId    String,
    user     JSON
)
ENGINE = MergeTree ORDER BY (rowId);`

Insert one row:

`INSERT INTO json_test VALUES('xxxxxxx', '{"userName": "test", "userId": 123, "email": "test@abcd.com"}');`

Try to define an index on key `userName` on JSON column `user`:
`ALTER TABLE json_test ADD INDEX userNameIndex user.userName TYPE set(100) GRANULARITY 2;`

Error:
`Received exception from server (version 23.2.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'user.userName' while processing query: 'user.userName', required columns: 'user.userName' 'user.userName'. (UNKNOWN_IDENTIFIER)`

Thank you in advance!

**Comment by Algunenano** [comment]
It's not supported and the type is deprecated and will be removed.
