### ISSUE TITLE
Failed build  -no-pie

### ISSUE THREAD

**Issue by k-morozov** [ClickHouse/ClickHouse#47012]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
Ubuntu 18.04.6 LTS
> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**
3.26
**Ninja version**
1.8.2
**Compiler name and version**
clang++-15
**Full cmake and/or ninja output**

cmake build:

`/usr/local/bin/cmake --build build --target clickhouse-server -j 9
[0/2] Re-checking globbed directories...
[2726/11231] Linking CXX executable contrib/protobuf-cmake/protoc
FAILED: contrib/protobuf-cmake/protoc 

: && /usr/bin/clang++-15 --target=x86_64-linux-gnu --sysroot=/home/dev/repo/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=dev/repo/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -g -O0 -g -gdwarf-4  -D_LIBCPP_DEBUG=0 --gcc-toolchain=dev/repo/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=dev/repo/ClickHouse/build/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1 -no-pie -Wl,-no-pie    -Xlinker --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o -o contrib/protobuf-cmake/protoc  contrib/protobuf-cmake/lib_libprotocd.a  contrib/protobuf-cmake/lib_libprotobufd.a  -lpthread  contrib/zlib-ng-cmake/lib_zlibd.a  base/glibc-compatibility/libglibc-compatibilityd.a  base/glibc-compatibility/memcpy/libmemcpyd.a  base/glibc-compatibility/libglibc-compatibilityd.a  base/glibc-compatibility/memcpy/libmemcpyd.a  -Wl,--start-group  contrib/libcxx-cmake/libcxxd.a  contrib/libcxxabi-cmake/libcxxabid.a  contrib/libunwind-cmake/libunwindd.a  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :

/usr/bin/ld.lld: error: unknown argument: -no-pie
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2734/11231] Building CXX object contrib/flatbuffers/CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o
ninja: build stopped: subcommand failed`

**Comment by rschu1ze** [comment]
I don't have an Ubuntu 18.04 to try but I find this snippet in file "contrib/grpc/CMakeLists.txt"

```cmake
if (NOT DEFINED CMAKE_POSITION_INDEPENDENT_CODE)
  set(CMAKE_POSITION_INDEPENDENT_CODE TRUE)
endif()
```

and `CMAKE_POSITION_INDEPENDENT_CODE` is turned off in the top-level CMakeLists.txt file (in order to set the `-no-pie` flag manually, depending on the architecture). Maybe you could remove the first snippet?

**Comment by k-morozov** [comment]
I have updated Ubuntu from 18 to 20.04.
There is no problem now :)
