### ISSUE TITLE
Any good documents/examples for *-Transform?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#47054]
I am writing a transform and try to learn from existent code. However I found some questions in WindowTransform, e.g. I am wondering that if the `!has_input` is needed while input has been set to be 'not needed' in below code.
```C++
    if (!has_input && input.hasData())
    {
        input_data = input.pullData(true);
    }
```
The method `prepare` handles and changes IProcessor::Status, with some rules. I am curious if I can get some documents about these rules. 

Thank you in advance.

**Comment by alexey-milovidov** [comment]
If there is documentation, it should be located in the comments inside the code, e.g., in the `IProcessor.h` file.
I'm not sure if it has complete documentation.
