### ISSUE TITLE
Insert multiple values

### ISSUE THREAD

**Issue by VSMironov** [ClickHouse/ClickHouse#47079]
When trying to run a script to insert multiple values using a single insert command, I get an error.

ClickHouse client version 23.1.3.5 (official build).

 /tmp/test.sql
```
create table test(a varchar, b varchar) ENGINE MergeTree order by a;

insert into test(a, b) values
('a', 'b'),
('c', 'd'); 
```

clickhouse-client  --multiquery --multiline --queries-file /tmp/test.sql

```
Code: 62. DB::Exception: Syntax error: failed at position 2 (''c''): 'c', 'd');
. Expected one of: SELECT query, possibly with UNION, list of union elements, SELECT query, subquery, possibly with UNION, SELECT subquery, SELECT query, WITH, FROM, SELECT, EXPLAIN. (SYNTAX_ERROR)

```
```
select * from test;

┌─a─┬─b─┐
│ a │ b │
└───┴───┘
```

But if you change the values in the script in one line, the script will behave correctly.
```
insert into test(a, b) values
('a', 'b'),('c', 'd');
```

**Comment by den-crane** [comment]
it's expected. 
`values` is not compatible with `-- multiquery`

**Comment by VSMironov** [comment]
OK, but how do I execute this script?
I removed the `--multiquery` flag, but it didn't help.

**Comment by den-crane** [comment]
right, it's not possible, unfortunately.
