### ISSUE TITLE
view with limit by can not pushdown the predicate

### ISSUE THREAD

**Issue by DangoTinker** [ClickHouse/ClickHouse#47119]
1.   select * from  test_table where ping_time >'2023-03-02' limit  1 by  time,mac

2.  create view test_view  as select * from test_table  limit 1 by time,mac
     select * from  test_view where ping_time >'2023-03-02'

I want to avoid duplicate rows with select. 
1 is ok but make it to view(like 2) is not(DB::Exception: Memory limit (for query) exceeded: would use 13.48 GiB (attempt to allocate chunk of 4279696 bytes), maximum: 9.31 GiB).
Should I give up using views?

**Comment by den-crane** [comment]
Automatic pushdown is forbidden in this case because it will change result of the query.
