### ISSUE TITLE
force_index_by_date does not throw INDEX_NOT_USED exception if there is an unused partition key.

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#47144]
**Describe the unexpected behaviour**
When force_index_by_date is set, selecting from a table where the partition key is unused does not throw an exception as it has in the previous versions.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 23.2.1 
* Queries to run that lead to unexpected result
```
CREATE TABLE y (date_time DateTime64(3), x String) Engine=MergeTree PARTITION BY toDate(date_time) ORDER BY tuple();

INSERT INTO y SELECT toDateTime64('2020-01-01 00:00:00.000',3)+number , '' FROM numbers(1);

SELECT count() FROM y  WHERE toDateTime64(date_time,3) >= toDateTime64('2020-01-10 00:00:00.000',3) SETTINGS force_index_by_date=1
```

**Expected behavior**
Throws `INDEX_NOT_USED` exception.

**Comment by den-crane** [comment]
because it uses the pruning

```sql
set send_logs_level = 'debug';

SELECT count() FROM y  WHERE toDateTime64(date_time,3) >= toDateTime64('2020-01-10 00:00:00.000',3) SETTINGS force_index_by_date=1
Selected 0/1 parts by partition key, 0 parts by primary key, 0/0 marks by primary key, 0 marks to read from 0 ranges
```

it was implemented in 22.9

https://github.com/ClickHouse/ClickHouse/pull/39864
https://github.com/ClickHouse/ClickHouse/pull/40219
