### ISSUE TITLE
singleValueOrNullState with Array(Nullable(UInt32)) argument throws exception. version 23.2.1

### ISSUE THREAD

**Issue by MyroTk** [ClickHouse/ClickHouse#47142]
**Describe the unexpected behaviour**
Using `SELECT singleValueOrNullState(array_nullable_uint32) FROM table_name` returns the exception `DB::Exception: Nested type Array(Nullable(UInt32)) cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT)` .

Worked in previous ClickHouse versions.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse server version 23.2.1
* Queries to run that lead to unexpected result
```
CREATE TABLE x (array_nullable_uint32__ Array(Nullable(UInt32))) ENGINE MergeTree() ORDER BY tuple();

INSERT INTO x (`array_nullable_uint32__`) VALUES ([4294967295]), ([0]), ([NULL]), ([4141473992]), ([1154045914]), ([225271039]), ([27707455]), ([4237794322]), ([1571209559]), ([2330188970]);

SELECT singleValueOrNullState(array_nullable_uint32__) FROM x;
```

**Comment by alsugiliazova** [comment]
https://github.com/ClickHouse/ClickHouse/issues/43140

Same. Can be closed.
