### ISSUE TITLE
Incorrect Grouping Aggregation 

### ISSUE THREAD

**Issue by olearyl94** [ClickHouse/ClickHouse#47155]
**Describe the unexpected behaviour**
Grouping and summing not giving correct values with if statement in sub-query.

**How to reproduce**
version - 22.4.5.9
Query giving unexpected behaviour:
`select toStartOfInterval(dt, interval 30 minute) as date_time, sum(ss_aux), count() from (
select dt, 
if(runningDifference(sumIf(number, label = 'a'))<0, 0,runningDifference(sumIf(number, label = 'a'))) as ss_aux
from (select date_add(interval 5 + number*5 minute, toStartOfInterval(now(), interval 5 minute)) as dt, 'a' as label, number from system.numbers limit 100) as n 
group by dt 
order by dt ) as d 
group by date_time
order by date_time`
Result:
┌───────────date_time─┬─sum(ss_aux)─┬─count()─┐
│ 2023-03-02 17:30:00 │           0 │       1 │
│ 2023-03-02 18:00:00 │           3 │       6 │
│ 2023-03-02 18:30:00 │           6 │       6 │
│ 2023-03-02 19:00:00 │          15 │       6 │
│ 2023-03-02 19:30:00 │           0 │       6 │
│ 2023-03-02 20:00:00 │          91 │       6 │
│ 2023-03-02 20:30:00 │           8 │       6 │
│ 2023-03-02 21:00:00 │          32 │       6 │
│ 2023-03-02 21:30:00 │          47 │       6 │
│ 2023-03-02 22:00:00 │          73 │       6 │
│ 2023-03-02 22:30:00 │          90 │       6 │
│ 2023-03-02 23:00:00 │         158 │       6 │
│ 2023-03-02 23:30:00 │          77 │       6 │
│ 2023-03-03 00:00:00 │         152 │       6 │
│ 2023-03-03 00:30:00 │         115 │       6 │
│ 2023-03-03 01:00:00 │         334 │       6 │
│ 2023-03-03 01:30:00 │         164 │       6 │
│ 2023-03-03 02:00:00 │         124 │       3 │
└─────────────────────┴─────────────┴

Adding groupArray(ss_aux) to outer query gives expected behaviour:
`select toStartOfInterval(dt, interval 30 minute) as date_time, sum(ss_aux), count(), groupArray(ss_aux) from (
select dt, 
if(runningDifference(sumIf(number, label = 'a'))<0, 0,runningDifference(sumIf(number, label = 'a'))) as ss_aux
from 
(select date_add(interval 5 + number*5 minute, toStartOfInterval(now(), interval 5 minute)) as dt, 'a' as label, number from system.numbers limit 100) as n 
group by dt order by dt ) as d 
group by date_time order by date_time`
Result:
┌───────────date_time─┬─sum(ss_aux)─┬─count()─┬─groupArray(ss_aux)─┐
│ 2023-03-02 17:30:00 │           1 │       2 │ [0,1]              │
│ 2023-03-02 18:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 18:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 19:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 19:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 20:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 20:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 21:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 21:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 22:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 22:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 23:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-02 23:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-03 00:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-03 00:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-03 01:00:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-03 01:30:00 │           6 │       6 │ [1,1,1,1,1,1]      │
│ 2023-03-03 02:00:00 │           2 │       2 │ [1,1]              │

**Comment by tavplubix** [comment]
> version - 22.4.5.9

This version is obsolete. Please upgrade to one of the supported versions (https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease) and check if it's still reproducible in recent releases

**Comment by tavplubix** [comment]
Anyway, we still highly recommend upgrading

**Comment by den-crane** [comment]
I see, it's not bug. It's the incorrect query.

[runningDifference](https://clickhouse.com/docs/en/sql-reference/functions/other-functions/#runningdifferencex) should be in the external query, after order by

```
    SELECT
        dt,
        sum(num) x,
        runningDifference(x) y,
        if(y < 0, 0, y) AS ss_aux
    FROM n
    GROUP BY dt
    ORDER BY dt ASC   ----<<<<<<<--
```

expected
```
    SELECT
        runningDifference(x) y,
        if(y < 0, 0, y) AS ss_aux
        FROM (
          SELECT
            dt,
            sum(num) x,
         FROM n
        GROUP BY dt
       ORDER BY dt ASC )
```

**Comment by den-crane** [comment]
```sql
SELECT
    toStartOfInterval(dt, toIntervalMinute(30)) AS date_time,
    sum(ss_aux),
    count()
FROM
(
    SELECT
        dt,
        if(runningDifference(sm) < 0, 0, runningDifference(sm)) AS ss_aux
    FROM
    (
        SELECT
            dt,
            sumIf(number, label = 'a') AS sm
        FROM
        (
            SELECT
                toIntervalMinute(5 + (number * 5)) + toStartOfInterval(now(), toIntervalMinute(5)) AS dt,
                'a' AS label,
                number
            FROM system.numbers
            LIMIT 100
        ) AS n
        GROUP BY dt
        ORDER BY dt ASC
    )
) AS d
GROUP BY date_time
ORDER BY date_time ASC

Query id: 4477dc7a-cbbc-485b-a273-928841f644d1

┌───────────date_time─┬─sum(ss_aux)─┬─count()─┐
│ 2023-03-02 20:30:00 │           5 │       6 │
│ 2023-03-02 21:00:00 │           6 │       6 │
│ 2023-03-02 21:30:00 │           6 │       6 │
│ 2023-03-02 22:00:00 │           6 │       6 │
│ 2023-03-02 22:30:00 │           6 │       6 │
│ 2023-03-02 23:00:00 │           6 │       6 │
│ 2023-03-02 23:30:00 │           6 │       6 │
│ 2023-03-03 00:00:00 │           6 │       6 │
│ 2023-03-03 00:30:00 │           6 │       6 │
│ 2023-03-03 01:00:00 │           6 │       6 │
│ 2023-03-03 01:30:00 │           6 │       6 │
│ 2023-03-03 02:00:00 │           6 │       6 │
│ 2023-03-03 02:30:00 │           6 │       6 │
│ 2023-03-03 03:00:00 │           6 │       6 │
│ 2023-03-03 03:30:00 │           6 │       6 │
│ 2023-03-03 04:00:00 │           6 │       6 │
│ 2023-03-03 04:30:00 │           4 │       4 │
└─────────────────────┴─────────────┴─────────┘
```

**Comment by den-crane** [comment]
```sql
create table n Engine = Memory as 
SELECT toIntervalMinute(5 + (number * 5)) + toStartOfInterval(now(),     toIntervalMinute(5)) AS dt,  number
FROM numbers(100);

SELECT
    toStartOfDay(dt) AS date_time,
    sum(ss_aux),
    count()
FROM
(
    SELECT
        dt,
        sum(number) x,
        runningDifference(x) y,
        if(y < 0, 0, y) AS ss_aux
    FROM n
    GROUP BY dt
) AS d
GROUP BY date_time
ORDER BY date_time ASC;
┌───────────date_time─┬─sum(ss_aux)─┬─count()─┐
│ 2023-03-01 23:00:00 │          69 │      28 │
│ 2023-03-02 23:00:00 │        1558 │      72 │
└─────────────────────┴─────────────┴─────────┘
```
Let's remove excessive ORDER BY dt

```sql
SELECT
    toStartOfDay(dt) AS date_time,
    sum(ss_aux),
    count()
FROM
(
    SELECT
        dt,
        sum(number) AS x,
        runningDifference(x) AS y,
        if(y < 0, 0, y) AS ss_aux
    FROM n
    GROUP BY dt
) AS d
GROUP BY date_time
ORDER BY date_time ASC
┌───────────date_time─┬─sum(ss_aux)─┬─count()─┐
│ 2023-03-01 23:00:00 │          69 │      28 │
│ 2023-03-02 23:00:00 │        1558 │      72 │
└─────────────────────┴─────────────┴─────────┘
```
result is the same

groupArray does not allow to automatically remove ORDERBY because the result of groupArray depends on it.
the same with my LIMIT 10000000000.
