### ISSUE TITLE
Requests can be processed when dictionaries are not ready yet even though dictionaries_lazy_load is set to false

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#4717]
If dictionaries_lazy_load is set to false, CH loads dictionaries at startup.
But CH starts accepting requests BEFORE loading dictionaries:
```
2019.03.14 16:06:48.603246 [ 1 ] {} <Information> DatabaseOrdinary (test): Starting up tables.
2019.03.14 16:06:48.603730 [ 1 ] {} <Debug> Application: Loaded metadata.
2019.03.14 16:06:48.604450 [ 1 ] {} <Information> Application: Listening http://[::]:8123
2019.03.14 16:06:48.604521 [ 1 ] {} <Information> Application: Listening tcp: [::]:9000
2019.03.14 16:06:48.604577 [ 1 ] {} <Information> Application: Listening interserver http: [::]:9009
2019.03.14 16:06:48.604778 [ 1 ] {} <Information> Application: Available RAM: 31.39 GiB; physical cores: 12; logical cores: 24.
2019.03.14 16:06:48.604790 [ 1 ] {} <Information> Application: Ready for connections.
2019.03.14 16:06:48.604808 [ 1 ] {} <Information> EmbeddedDictionaries: Loading dictionaries.
```
As a result some requests can go through before all the dictionaries are ready, especially if there are many dictionaries in the system. 
I am wondering, is it possible to load dictionaries AFTER loading metadata, but BEFORE accepting connections?

**Comment by KochetovNicolai** [comment]
Now it's not possible, but I think not very difficult to implement (the order is fixed now in src/programms/Server.cpp). Probably, we need special setting for this (otherwise, queries which don't need dictionary will also wait).

**Comment by SaltTan** [comment]
I don't think it's bad that all queries will wait.
ClickHouse is supposed to shut down anyway if dictionaries_lazy_load is false and there were errors during dictionaries loading.
Moreover, it works exactly like this in all versions earlier than 19.x, all queries have to wait because dictionaries are loaded even before tables if there are objects with engine=Dictionary #2870

**Comment by alexey-milovidov** [comment]
@filimonov Please validate the current behaviour (it was changed multiple times).

**Comment by SaltTan** [comment]
I have checked 19.17.6.36.
With `dictionaries_lazy_load=false` CH starts up and then loads dictionaries asynchronously:
```
2020.01.03 16:13:58.949511 [ 1 ] {} <Information> Application: Listening http://[::]:8123
2020.01.03 16:13:58.949537 [ 1 ] {} <Information> Application: Listening for connections with native protocol (tcp): [::]:9000
2020.01.03 16:13:58.949559 [ 1 ] {} <Information> Application: Listening for replica communication (interserver) http://[::]:9009
2020.01.03 16:13:58.949672 [ 1 ] {} <Information> Application: Available RAM: 31.29 GiB; physical cores: 4; logical cores: 8.
2020.01.03 16:13:58.949678 [ 1 ] {} <Information> Application: Ready for connections.
2020.01.03 16:13:58.949690 [ 1 ] {} <Information> EmbeddedDictionaries: Loading dictionaries.
2020.01.03 16:13:58.949703 [ 1 ] {} <Information> EmbeddedDictionaries: Loaded dictionaries.
2020.01.03 16:13:58.954386 [ 44 ] {} <Debug> executeQuery: (internal) SELECT `one`, `one` FROM `system`.`one`;
2020.01.03 16:13:58.954393 [ 45 ] {} <Debug> executeQuery: (internal) SELECT `dummy`, (dummy) AS `two` FROM `default`.`dict_invalidate`;
```
CH does not shut down if it cannot load dictionaries, it continues to try:
```
2020.01.03 16:13:58.954855 [ 45 ] {} <Error> ExternalDictionariesLoader: Could not load external dictionary 'invalidate', next update is scheduled at 2020-01-03 16:14:03
2020.01.03 16:13:58.955052 [ 44 ] {} <Error> ExternalDictionariesLoader: Could not load external dictionary 'one', next update is scheduled at 2020-01-03 16:14:03

2020.01.03 16:14:08.921633 [ 45 ] {} <Error> ExternalDictionariesLoader: Could not load external dictionary 'invalidate', next update is scheduled at 2020-01-03 16:14:15
2020.01.03 16:14:08.921755 [ 44 ] {} <Error> ExternalDictionariesLoader: Could not load external dictionary 'one', next update is scheduled at 2020-01-03 16:14:14

2020.01.03 16:14:18.922244 [ 45 ] {} <Error> ExternalDictionariesLoader: Could not load external dictionary 'invalidate', next update is scheduled at 2020-01-03 16:14:24
2020.01.03 16:14:18.922367 [ 44 ] {} <Error> ExternalDictionariesLoader: Could not load external dictionary 'one', next update is scheduled at 2020-01-03 16:14:23
```
If this is the expected behaviour then the documentation needs to be changed:
> If false, all dictionaries are created when the server starts, and if there is an error, the server shuts down.
https://clickhouse.yandex/docs/en/operations/server_settings/settings/#server_settings-dictionaries_lazy_load

**Comment by vitlibar** [comment]
The current behaviour was implemented to fix hanging of the server when it's starting with some dictionaries which take a lot of time to be loaded. Earlier the server used to load all dictionaries synchronously on its start (if `dictionaries_lazy_load=false`) and back then it was enough to have one long-loading dictionary to hang the server on start.

**Comment by blinkov** [comment]
@SaltTan, do you have any further questions?

**Comment by SaltTan** [comment]
I don't have questions, but the documentation has not been changed to reflect the new behaviour.

**Comment by filimonov** [comment]
Actually, the current behavior is VERY questionable.

And it's hard to call it logical. 

I think the user should be able to choose (even per dictionary actually) when to load it:
* on first access
* on server start (asynchronously / non-blocking)
* on server start,  before processing connections (synchronously / blocking)

Lack of option nr. 3 is an important usability issue.
