### ISSUE TITLE
Centos7's cvm install version 23.1.4.58 systemctl statr error! 

### ISSUE THREAD

**Issue by bjfk2006** [ClickHouse/ClickHouse#47179]
return error msg: Failed to get D-Bus connection: Operation not permitted

**Comment by cmsxbc** [comment]
There is a mistake in systemd unit file, which may cause systemd runtime directory permission wrong. I had fixed in #46461 and introduced in 23.2. If it's impossible to upgrade, You can apply this fix to the systemd file.

**Comment by bjfk2006** [comment]
Version 23.2 has been verified successfully, thank you very much

**Comment by lee-myring-maverick** [comment]
@bjfk2006 Hi 👋...Will this fix be back ported to version 22.* stable release channel?

**Comment by den-crane** [comment]
I think this issue is in 22.12 only https://github.com/ClickHouse/ClickHouse/pull/45568 
and 22.12 will be out of support in two weeks.
