### ISSUE TITLE
delete on cluster where doesn't work 

### ISSUE THREAD

**Issue by fekinada** [ClickHouse/ClickHouse#47186]
I'm deleting rows from a replicated table with this command
> delete from test ON CLUSTER 'ch-clickhouse' where time_bucket<='2022-01-01 00:00:00'

but get this error 
>DB::Exception: Syntax error: failed at position 64 ('where'): where time_bucket<='2022-01-01 00:00:00'. Expected one of: NO DELAY, SYNC, INTO OUTFILE, FORMAT, SETTINGS, end of query. (SYNTAX_ERROR) (version 22.12.3.5 (official build))

I am using 22.12.3.5 version, I also tried 23.2.2 version, but I got the same error. 
for table creation 
>show create table test
"CREATE TABLE default.test
(
id LowCardinality(UInt64),
key1 UInt32 CODEC(T64, LZ4),
time_bucket DateTime64(0) CODEC(DoubleDelta, LZ4),
key2 LowCardinality(UInt8),
time2 DateTime64(0) CODEC(DoubleDelta, LZ4)
)
ENGINE = ReplicatedMergeTree('/default/test', '{replica}')
PARTITION BY toYYYYMM(time)
ORDER BY (id, key1, time_bucket)
SETTINGS index_granularity = 8192".

And when I delete using a command without "ON CLUSTER"
>delete from test where time_bucket<='2022-01-01 00:00:00'

It deletes from all replicated tables. So, is this the expected behavior? If yes, then what is the purpose of using "ON CLUSTER" in the command?

**Comment by davenger** [comment]
Hi @fekinada 'ON CLUSTER' clause allows to run the query on partitions of Distributed table (distributed table might be confused with replicated table but they are orthogonal to each other: partitions of distributed table are spread across the cluster nodes and contain different subsets of rows while replicas of replicated table store the same data). 
In your case distributed table would look something like:
"CREATE TABLE default.test **ON CLUSTER 'ch-clickhouse'**
(
id LowCardinality(UInt64),
key1 UInt32 CODEC(T64, LZ4),
time_bucket DateTime64(0) CODEC(DoubleDelta, LZ4),
key2 LowCardinality(UInt8),
time2 DateTime64(0) CODEC(DoubleDelta, LZ4)
)
ENGINE = ReplicatedMergeTree('/default/test', '{replica}')
PARTITION BY toYYYYMM(time)
ORDER BY (id, key1, time_bucket)
SETTINGS index_granularity = 8192"

Version 23.2.2 should have 'ON CLUSTER' support as it was added in this PR #45786
One reason why you might get the error on 23.2.2 could be that the client that you use to send the query is of older version (22.12?) and it fails to parse the query.
