### ISSUE TITLE
Implement `string_to_map` function

### ISSUE THREAD

**Issue by ucasfl** [ClickHouse/ClickHouse#47185]
Check https://docs.databricks.com/sql/language-manual/functions/str_to_map.html

**Comment by Vikrant-Khedkar** [comment]
hey @ucasfl  can i work on this

**Comment by ucasfl** [comment]
> hey @ucasfl can i work on this

sure.

**Comment by Vikrant-Khedkar** [comment]
@ucasfl hey where will i be adding this function can you give me a little brief about that , will be a great help

**Comment by ucasfl** [comment]
> @ucasfl hey where will i be adding this function can you give me a little brief about that , will be a great help

Please check `src/Functions/IFunction.h` and other functions implementation under directrory `src/Functions/`.

**Comment by ucasfl** [comment]
@Vikrant-Khedkar Hi, any progress?

**Comment by kritinsharma** [comment]
@ucasfl is it still open? Can I work on it?

**Comment by kritinsharma** [comment]
@ucasfl Since the implementation involves regular expressions, can I use C++ regex or should I implement it on my own or should I do something else?

**Comment by ucasfl** [comment]
> @ucasfl Since the implementation involves regular expressions, can I use C++ regex or should I implement it on my own or should I do something else?

It's shouldn't  involves regular expressions, I think you can check `base/base/find_symbols.h`.

**Comment by kritinsharma** [comment]
@ucasfl I am having a little trouble in determining the type of keys and values of the map that should be returned. Would the key type and value type always be string type? If not, how can I determine the key/value types from the string?

**Comment by ucasfl** [comment]
> @ucasfl Will the delimiters always be single characters?

Yes.

**Comment by kritinsharma** [comment]
@ucasfl I have implemented the function but right now it works only for default values of the delimiters. This is because I have not been able to figure out how to use functions from `base/base/find_symbols.h` for characters (the delimiters) not known at compile time.

**Comment by rschu1ze** [comment]
@kritinsharma Thanks a lot! Let's continue the technical discussion about #48561 in #48561 😄
