### ISSUE TITLE
test_materialized_database_support_all_kinds_of_mysql_datatype flaky

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#47197]
Stats:
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X21hdGVyaWFsaXplZF9kYXRhYmFzZV9zdXBwb3J0X2FsbF9raW5kc19vZl9teXNxbF9kYXRhdHlwZSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

Example:
https://s3.amazonaws.com/clickhouse-test-reports/45382/4cf11d9a84ea228de7c0f9822d43ba092da2b04e/integration_tests__asan__[4/6].html

```
>           assert (
                result_got == result_set
            ), f"Got result {result_got}, while expected result {result_set}"
E           AssertionError: Got result 2	2	22	9223372036854775807	-2	2	22	18446744073709551615	-2.2	2.2	-2.22	2.222	2.2222	2021-10-07	text	varchar	BLOB	2021-10-07 18:32:57	2021-10-07 18:32:57.482786	2021-10-07 18:32:57	2021-10-07 18:32:57.482786	2021	-3020399000000	-46798000001	000000000101000000D55C6E30D4095E40DCF0BBE996493E40	11	3	22	varbinary	GREEN
E           1	1	11	9223372036854775807	-1	1	11	18446744073709551615	-1.1	1.1	-1.111	1.111	1.1111	2021-10-06	text	varchar	BLOB	2021-10-06 18:32:57	2021-10-06 18:32:57.482786	2021-10-06 18:32:57	2021-10-06 18:32:57.482786	2021	3020399000000	3020399000000	00000000010100000000000000000000000000000000000000	10	1	11	varbinary	RED
E           , while expected result 1	1	11	9223372036854775807	-1	1	11	18446744073709551615	-1.1	1.1	-1.111	1.111	1.1111	2021-10-06	text	varchar	BLOB	2021-10-06 18:32:57	2021-10-06 18:32:57.482786	2021-10-06 18:32:57	2021-10-06 18:32:57.482786	2021	3020399000000	3020399000000	00000000010100000000000000000000000000000000000000	10	1	11	varbinary	RED
E           2	2	22	9223372036854775807	-2	2	22	18446744073709551615	-2.2	2.2	-2.22	2.222	2.2222	2021-10-07	text	varchar	BLOB	2021-10-07 18:32:57	2021-10-07 18:32:57.482786	2021-10-07 18:32:57	2021-10-07 18:32:57.482786	2021	-3020399000000	-46798000001	000000000101000000D55C6E30D4095E40DCF0BBE996493E40	11	3	22	varbinary	GREEN
```

**Comment by KochetovNicolai** [comment]
[Fail not very ofter, but good to fix](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgY2hlY2tfc3RhcnRfdGltZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICAtLUFORCB0ZXN0X3N0YXR1cyBMSUtFICdGJScKICAgIC0tQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCB0ZXN0X25hbWUgbGlrZSAnJXRlc3RfbWF0ZXJpYWxpemVkX2RhdGFiYXNlX3N1cHBvcnRfYWxsX2tpbmRzX29mX215c3FsX2RhdGF0eXBlJScKT1JERVIgQlkgY2hlY2tfbmFtZSwgdGVzdF9uYW1lLCBjaGVja19zdGFydF90aW1lIGRlc2MgbGltaXQgMTA=)

**Comment by devcrafter** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/47547, see [fix](https://github.com/ClickHouse/ClickHouse/pull/47547/files#diff-a17d4bb3aec8b258e7d883f25f0f12d99afa58171125ed45cb188158353f2758R2066)
