### ISSUE TITLE
runningDifference doesn't work with (U)Int128, (U)Int256, (U)Int512

### ISSUE THREAD

**Issue by andWhatShouldISay** [ClickHouse/ClickHouse#47194]
runningDifference doesn't work with (U)Int128, (U)Int256, (U)Int512

I have checked the source code and it seems the developers have completely forgotten about these datatypes in the runningDifference's implementation

**Comment by filimonov** [comment]
Indeed 

```
SELECT runningDifference(toUInt128(number))
FROM numbers(10)

Received exception:
Code: 43. DB::Exception: Argument for function runningDifference must have numeric type.: While processing runningDifference(toUInt128(number)). (ILLEGAL_TYPE_OF_ARGUMENT)
```


But anyway, it's better & safer to use window functions instead. 

```
select a - any(a) OVER (ORDER BY a ASC ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) FROM (select toUInt128(number) as a from numbers(10));
-- or
select a - lagInFrame(a) OVER (ORDER BY a ASC) FROM (select toUInt128(number) as a from numbers(10));
``

because runningDifferent works only in the scope of block:

```
select runningDifference(number) as a from numbers(10) settings max_block_size=3;
```

Default block size if ~65K rows, and better not to change it if you want to have a good performance. 

In other words runningDifference can work properly only if you have less than 65K rows in the result set, while window functions works properly always.

**Comment by andWhatShouldISay** [comment]
In my case, I have a column consisting of a billion sorted ``Int128``s, and I can tolerate ``runningDifference``'s and ``runningDifferenceStartingWithFirstValue``'s behavior at the blocks' borders. What has the better performance, ``runningDifference`` or the window functions suggested by you?  Thanks.

**Comment by filimonov** [comment]
runningDifference is simpler, so it can be faster. But to know for sure you need to benchmark it.
