### ISSUE TITLE
RFC: clickhouse-client `CONNECT` command to switch between connections interactively

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#47192]
we can introduce a command `CONNECT ...` similar to `USE <db>` which will allow us to speak to a different server w/o leaving the interactive mode of clickhouse. 

That allows checking the different servers w/o leaving to the shell every time 

The syntax can be:

```
CONNECT 'clickhouse://host:port?setting1=val&database=...&secure=...'; -- if connection is not defined 
CONNECT 'connection_defined_in_config_file'; -- if connection is defined in https://github.com/ClickHouse/ClickHouse/pull/45715
```

That can also allow writing flat SQL test scenarios talking to several clickhouse servers in sequence. 

```
CONNECT 'server1conn';
CREATE TABLE test123 ON CLUSTER '...' ... ;
CONNECT 'server2conn';
DROP TABLE test123
... 
```

Uncertain moments here:
1) should the settings be preserved?
2) should the old connection / session be preserved if we will decide to switch back to it.

(i would answer 'no' to both because it's simpler, and less confusing)

**Comment by filimonov** [comment]
BTW: that can also allow to use clickhouse-local as a clickhouse-client (or vice-versa)

**Comment by alexey-milovidov** [comment]
Looks not worth the effort.
