### ISSUE TITLE
Nullable Avro records and Array types for Clickhouse Kafka engine

### ISSUE THREAD

**Issue by dheerajathrey** [ClickHouse/ClickHouse#47238]
Hi
I am trying to read postgres cdc avro data from Kafka using Kafka engine.

The avro schema looks something like this.

<pre>
{
  "connect.name": "xxxxx.Envelope",
  "fields": [
    {
      "default": null,
      "name": "before",
      "type": [
        "null",
        {
          "connect.name": "xxxx.Value",
          "fields": [
            {
              "name": "id",
              "type": "string"
            },
            {
              "default": null,
              "name": "createdAtInSecs",
              "type": [
                "null",
                "long"
              ]
            },
            {
              "default": null,
              "name": "updatedAtInSecs",
              "type": [
                "null",
                "long"
              ]
            },
            {
              "default": null,
              "name": "editMeta",
              "type": [
                "null",
                {
                  "connect.name": "io.debezium.data.Json",
                  "connect.version": 1,
                  "type": "string"
                }
              ]
            },
            {
            "name": "tags",
            "type": [
                "null",
                {
                    "type": "array",
                    "items": [
                        "null",
                        "string"
                    ]
                }
            ],
            "default": null
        },
          ],
          "name": "Value",
          "type": "record"
        }
      ]
    },
    {
      "default": null,
      "name": "after",
      "type": [
        "null",
        "Value"
      ]
    },
    {
      "name": "op",
      "type": "string"
    },
    {
      "default": null,
      "name": "ts_ms",
      "type": [
        "null",
        "long"
      ]
    }
  ],
  "name": "Envelope",
  "namespace": "some_namespace",
  "type": "record"
}
</pre>

The schema here uses the Avro union for the fields "before", "after" and "tags" which can also have a NULL value.

Though both the fields "before" and "after" of type **record** can have NULL value, clickhouse does not support a "Nullable Tuple" datatype.
Similarly for the field "tags" it could be NULL or Array(Nullable(String)), but again clickhouse does not support a "Nullable Array" datatype.

So I tried to define my tables as below which does not work.

<pre>
CREATE TABLE db.data_stream
(
before Tuple
	(
	id String,
	createdAtInSecs Nullable(bigint),
	updatedAtInSecs  Nullable(bigint),
	editMeta Nullable(String),
        tags Array(Nullable(String))
	),
after Tuple
	(
	id String,
	createdAtInSecs Nullable(bigint),
	updatedAtInSecs  Nullable(bigint),
	editMeta Nullable(String),
        tags Array(Nullable(String))
	),
ts_ms bigint,
op String
)
ENGINE = Kafka()
SETTINGS
kafka_broker_list = 'broker:9092',
kafka_topic_list = 'topic',
kafka_group_name = 'consumer-group',
kafka_num_consumers = 1,
kafka_format = 'AvroConfluent',
format_avro_schema_registry_url='https://username:url-encoded-password@schema-registry'

CREATE TABLE db.data_local
(
id String,
tags Array(Nullable(String)),
ts_ms bigint,
op String
)
ENGINE = ReplacingMergeTree(ts_ms)
ORDER BY id
SETTINGS index_granularity = 8192

CREATE MATERIALIZED VIEW db.data_mv TO db.data_local
AS SELECT
id,
tupleElement(before, 5) as tags,
ts_ms,
op
FROM db.data_stream
</pre>

So my above table definition throws the following error:
<pre>
DB::Exception: Type Tuple(id String,createdAtInSecs Nullable(bigint),updatedAtInSecs  Nullable(bigint),editMeta Nullable(String)) is not compatible with Avro Union:
[
"null",
{ "type": "record",
   "fields": [
....
....
....
</pre>
To put it simply, how to handle cases where Tuple or Array need to be Nullable?

Expected table definition that I want it to work
<pre>
CREATE TABLE db.data_stream
(
before Nullable(Tuple
	(
	id String,
	createdAtInSecs Nullable(bigint),
	updatedAtInSecs  Nullable(bigint),
	editMeta Nullable(String),
        tags Nullable(Array(Nullable(String)))
	)),
after Nullable(Tuple
	(
	id String,
	createdAtInSecs Nullable(bigint),
	updatedAtInSecs  Nullable(bigint),
	editMeta Nullable(String),
        tags Nullable(Array(Nullable(String)))
	)),
ts_ms bigint,
op String
)
ENGINE = Kafka()
SETTINGS
kafka_broker_list = 'broker:9092',
kafka_topic_list = 'topic',
kafka_group_name = 'consumer-group',
kafka_num_consumers = 1,
kafka_format = 'AvroConfluent',
format_avro_schema_registry_url='https://username:url-encoded-password@schema-registry'

</pre>

Does anyone have a solution to this?

If this is a feature that needs to be implemented, this can be moved to feature tag.

**Comment by ucasfl** [comment]
Which version of ClickHouse you use? It should have been fixed in https://github.com/ClickHouse/ClickHouse/pull/45276.

**Comment by dheerajathrey** [comment]
@ucasfl Clickhouse version: 22.12.1. I am guessing this should fix the issue for both the types "record" as well as "Array".

**Comment by ucasfl** [comment]
> @ucasfl I am using Clickhouse version: 22.12.1. Does #45276 fix the issue for both the types "record" and "Array"?

It should works, you can take a check.
