### ISSUE TITLE
insert from distributed table with conditional function will lose data

### ISSUE THREAD

**Issue by farlearn** [ClickHouse/ClickHouse#47257]
Hi, I've used clickhouse for quite a while, i found a potential 'bug' these days that, when insert into from a distributed table with conditional functions, data will be lost in the target table.

the source tables are created as following, and about **500,000,0** records are inserted into the src table:
```
CREATE TABLE src_local ON CLUSTER cluster1
(
`f1` String,
`f2` String
)            
ENGINE = MergeTree()
ORDER BY (`f1`);

CREATE TABLE src on cluster  cluster1  as  src_local 
ENGINE = Distributed('cluster1', '',  src_local, cityHash64(`f1`))
```

the target tables are created as following:
```
CREATE TABLE tgt_local ON CLUSTER cluster1
(
`f1` String,
`f2` UInt8 CODEC(Gorilla, LZ4)
)            
ENGINE = MergeTree()
ORDER BY (`f1`);

CREATE TABLE tgt on cluster  cluster1  as  tgt_local 
ENGINE = Distributed('cluster1', '',   tgt_local, cityHash64(`f1`))
```

And here is the insert sql:

```
INSERT INTO  tgt  
  SELECT `f1`, if(`f2` = '', 0, 1)
  FROM src
```

After the insert sql exed, I run '`SELECT count() FROM tgt`' , i can only get about **180,000,0** records. I checked that the **records are from src_local table accross the cluster**.

And if i run following **count sql**, i can get the right number as src table.
```
SELECT count() FROM(
  SELECT `f1`, if(`f2` = '', 0, 1)
  FROM src
)
```

And if I **remove the conditional function** from the insert sql as following, tgt table has the right number as src table.
```
INSERT INTO  tgt  
  SELECT `f1`, 1
  FROM src
```

And if I **insert from local table** as following, tgt table has the right number as src_local table.
```
INSERT INTO  tgt  
  SELECT `f1` , if(`f2` = '', 0, 1)
  FROM src_local
```

There seems a bug when **insert** from **distributed** table with **conditional** function. **combining these 3 conditions** will causing data lost. Please help analysis this case. thx.
FYI,
My ch version: **22.2.2.1**
My ch cluster setting:
```
    <remote_servers>
        <cluster1>
            <shard>
                <replica>
                    <host></host>
                    <port>9000</port>
                    <user></user>
                    <password></password>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host></host>
                    <port>9000</port>
                    <user></user>
                    <password></password>
                </replica>
            </shard>
            <shard>
                <replica>
                    <host></host>
                    <port>9000</port>
                    <user></user>
                    <password></password>
                </replica>
            </shard>
        </cluster1>
    </remote_servers>
```

**Comment by den-crane** [comment]
1. 22.2.2.1 is out of support.

2. `UInt8 CODEC(Gorilla, LZ4)` -- Gorilla can be used only with Float64 columns

**Comment by azat** [comment]
Cannot confirm this:

```sql
CREATE TABLE src_local
(
`f1` String,
`f2` String
)
ENGINE = MergeTree()
ORDER BY (`f1`);

CREATE TABLE src as src_local
ENGINE = Distributed('test_cluster_two_shards', currentDatabase(), src_local, cityHash64(`f1`));

SET allow_suspicious_codecs=1;
CREATE TABLE tgt_local
(
`f1` String,
`f2` UInt8 CODEC(Gorilla, LZ4)
)
ENGINE = MergeTree()
ORDER BY (`f1`);

CREATE TABLE tgt as tgt_local
ENGINE = Distributed('test_cluster_two_shards', currentDatabase(), tgt_local, cityHash64(`f1`));

INSERT INTO src_local SELECT number::String, if(rand() % 2, '', number::String) FROM numbers(1000000);

INSERT INTO tgt_local
  SELECT `f1`, if(`f2` = '', 0, 1)
  FROM src;

SYSTEM FLUSH DISTRIBUTED tgt;

SELECT count() FROM tgt;

SELECT count() FROM(
  SELECT `f1`, if(`f2` = '', 0, 1)
  FROM src
);
```

```
4000000
2000000
```

*Note, results are so, because `test_cluster_two_shards` contains two local nodes, and so first SELECT returns doubled count*

@farlearn can you share exact reproducer?

**Comment by farlearn** [comment]
I find the problem has relation with DBeaver client. I executed all sqls from DBeaver, if I execute insert sql from clickhouse client, nothing wrong.

Following is the suspicious log when executed insert from DBeaver (the estimated count is 1694000, while the read count is 65409):

> 2023.03.07 17:08:05.853986 [ 25489 ] {} <Debug> TCP-Session: c72e2fde-f124-439d-887f-72a3ac72d185 Creating query context from session context, user_id: 2e2d955c-01f5-9292-bc71-2cc4eb001110, parent context user:cmds
> 2023.03.07 17:08:05.854329 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Debug> executeQuery: (from 10.80.139.16:54106, user: cmds, initial_query_id: 44f07e44-10f4-4f1d-b4c2-7d6e15d3a304) SELECT `f1`, if(`f2` = '', 0, 1) FROM `cmds`.`src_local` (stage: Complete)
> 2023.03.07 17:08:05.855033 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Trace> ContextAccess (cmds): Access granted: SELECT(f1, f2) ON cmds.src_local
> 2023.03.07 17:08:05.855192 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Trace> ContextAccess (cmds): Access granted: SELECT(f1, f2) ON cmds.src_local
> 2023.03.07 17:08:05.855248 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
> 2023.03.07 17:08:05.855398 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Debug> cmds.src_local (012d4a9d-6840-4365-863f-5a69d16305cc) (SelectExecutor): Key condition: unknown
> 2023.03.07 17:08:05.855442 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Debug> cmds.src_local (012d4a9d-6840-4365-863f-5a69d16305cc) (SelectExecutor): Selected 1/1 parts by partition key, 1 parts by primary key, 207/207 marks by primary key, 207 marks to read from 1 ranges
> 2023.03.07 17:08:05.855462 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Trace> cmds.src_local (012d4a9d-6840-4365-863f-5a69d16305cc) (SelectExecutor): Spreading mark ranges among streams (default reading)
> 2023.03.07 17:08:05.855494 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Trace> MergeTreeInOrderSelectProcessor: Reading 1 ranges in order from part all_1_5_1, approx. **1694000** rows starting from 0
> 2023.03.07 17:08:05.860310 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Information> executeQuery: Read **65409** rows, 1.42 MiB in 0.006098 sec., 10726303.706133159 rows/sec., 233.40 MiB/sec.
> 2023.03.07 17:08:05.860464 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Debug> MemoryTracker: Peak memory usage (for query): 1.30 MiB.
> 2023.03.07 17:08:05.860498 [ 25489 ] {0a72a486-28cf-415a-98c8-2f3ff4110ac0} <Debug> TCPHandler: Processed in 0.006799082 sec.

I guess the problem might be with DBeaver, not clickhouse

**Comment by azat** [comment]
So, should the issue be closed?
