### ISSUE TITLE
Progress bar is not correct for compressed file

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#47250]
**Describe the unexpected behaviour**
```
clickhouse-client --progress --time --query "INSERT INTO hits FROM INFILE 'hits.tsv.zst'"
```

Progress is moving faster than expected and reaches 100% before the data is inserted.

**Comment by Avogar** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/51088
