### ISSUE TITLE
Offiical woboq code browser has not been updated since May 2022

### ISSUE THREAD

**Issue by rf** [ClickHouse/ClickHouse#47264]
The woboq source code browser at https://clickhouse.com/codebrowser/ClickHouse/index.html has not been updated since May 2022. Something is wrong with the automatic regeneration of the code browser.

**Comment by DanRoscigno** [comment]
@Felixoid do you know about how this is generated?

**Comment by cangyin** [comment]
I want to relate to my issue #46299

**Comment by Felixoid** [comment]
I've tried to update woboq in https://github.com/ClickHouse/ClickHouse/pull/46383, but didn't succeed.

We need to ask @alesapin for help

**Comment by Felixoid** [comment]
The image appeared to be broken completely, and it's fixed in #49692, should be fixed after https://github.com/ClickHouse/ClickHouse/actions/runs/4920914920/jobs/8799487163 is finished

**Comment by Felixoid** [comment]
So, the code is updated in https://s3.amazonaws.com/clickhouse-test-reports/codebrowser/index.html, the site will be updated soon too https://github.com/ClickHouse/clickhouse-website-worker/blob/master/src/codebrowser.ts#L11
