### ISSUE TITLE
INSERT DateTime grab delimiter

### ISSUE THREAD

**Issue by n00bik** [ClickHouse/ClickHouse#4727]
Hello. I have a question about INSERT command. Manual says that \N is the NULL in TabSeparated FORMAT.

I try insert this data (file attached [install_2017-10-04.zip](https://github.com/yandex/ClickHouse/files/2987052/install_2017-10-04.zip))
`2017-10-04      2017-10-04 23:54:10     \N      \N      \N      2017-10-04      2017-10-04 23:54:10     \N      \N      \N      0       \N      Organic \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      CN      Zhongshan       14.126.109.87   1       zh-Hans-CN      1507141258000-7328408   00000000-0000-0000-0000-000000000000    aadef6d6-6b26-49ca-af43-6fb3cffabe12    \N      35F258F5-C32C-40D6-9FBF-C1E54A553C09    ios     iPad Mini 1     \N      9.3.4   440     473     id738480930     0       \N      2017-10-04 00:00:00     \N      \N      \N      \N`

my table structure is
`CREATE TABLE default.install (
 cohort Date,
  installdatetime DateTime,
  attributiontype String,
  attributedtouchtype String,
  attributedtouchtime DateTime,
  eventdate Date,
  eventdatetime DateTime,
  eventname String,
  eventvalue String,
  eventrevenuecurrency String,
  eventrevenueusd Decimal(9,
 4),
  partner String,
  mediasource String,
  channel String,
  keywords String,
  campaign String,
  campaignid String,
  adset String,
  adsetid String,
  ad String,
  adid String,
  adtype String,
  siteid String,
  subparam1 String,
  subparam2 String,
  subparam3 String,
  subparam4 String,
  subparam5 String,
  costmodel String,
  costvalue Decimal(9,
 4),
  costcurrency String,
  countrycode String,
  city String,
  ip String,
  wifi UInt8,
  language String,
  appsflyerid String,
  advertisingid String,
  idfa UUID,
  androidid String,
  customeruserid String,
  platform String,
  devicetype String,
  devicebrand String,
  osversion String,
  appversion UInt16,
  sdkversion UInt16,
  appid String,
  isretargeting UInt8,
  retargetingconversiontype String,
  insert_timestamp DateTime,
  fb_adgroup_id UInt64,
  fb_adgroup_name String,
  order_id String,
  pack_name String
) ENGINE = MergeTree() PARTITION BY cohort ORDER BY appid SETTINGS index_granularity = 8192;
`

and have this error https://i.imgur.com/zzfIlKt.png
`Code: 27. DB::Exception: Cannot parse input: expected \t before: \\N\t2017-10-04\t2017-10-04 23:54:10\t\\N\t\\N\t\\N\t0\t\\N\tOrganic\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\t\\N\tCN\tZhongshan\t14.126.109.87\t1\tzh-Hans-CN\t1507141258: (at row 1)

Row 1:
Column 0,   name: cohort,                    type: Date,          parsed text: "2017-10-04"
Column 1,   name: installdatetime,           type: DateTime,      parsed text: "2017-10-04 23:54:10"
Column 2,   name: attributiontype,           type: String,        parsed text: "<BACKSLASH>N"
Column 3,   name: attributedtouchtype,       type: String,        parsed text: "<BACKSLASH>N"
Column 4,   name: attributedtouchtime,       type: DateTime,      ERROR: text "<BACKSLASH>N<TAB>2017-10" is not like DateTime`

Please tell me,  attributedtouchtime in data =\N, but CH grab \N with \t to attributedtouchtime, ignoring tab delimiter ?

**Comment by KochetovNicolai** [comment]
I think the reason why ClickHouse can't parse data is that column type should be Nullable to be able to store Null. So, \N for String type was parsed as string "N", but \N for DateTime caused a error. Try to change all columns which can store Null to Nullable type. (String -> Nullable(String), DateTime -> Nullable(DateTime), etc.)

**Comment by n00bik** [comment]
ok, but why insert in not null datetime is working?

`
drop table if EXISTS test;
CREATE TABLE IF NOT EXISTS test (
	name String,
	installdatetime datetime
) ENGINE = MergeTree()
PARTITION BY name ORDER BY installdatetime;

insert into test values('x',)
select * from test;
`

**Comment by den-crane** [comment]
>ok, but why insert in not null datetime is working?

because CH did not support Null(nullable) a year ago, and substitutes them with default values for each type String '', Date 0, Int64 0

CREATE TABLE IF NOT EXISTS test (name String
really means
CREATE TABLE IF NOT EXISTS test (name String Default ''

**Comment by alexey-milovidov** [comment]
It is possible to implement `input_format_null_as_default` and `input_format_empty_as_default` settings in future.

**Comment by n00bik** [comment]
thank you!

**Comment by qoega** [comment]
Resolved in #6055 and #7215
