### ISSUE TITLE
DB::Exception: Missing columns

### ISSUE THREAD

**Issue by heyboV** [ClickHouse/ClickHouse#47288]
I have a SQL such like
`select
	1 as `c0`
from
	(
	select
		C.`字段` AS `字段`
	from
		(
		select
			2 as bb) A
	LEFT JOIN (
		select
			'1' as `字段`
		 ) C ON
		1 = 1
	LEFT JOIN (
		select
			1 as a) D ON
		1 = 1) as `T0`
where
	`T0`.`字段` = '1'`
I got a Missing columns Error.
![image](https://user-images.githubusercontent.com/19544252/223307094-366d0a4d-1183-4eb6-a81e-de22137e605a.png)
When I replace all Chinese characters with  English characters, the SQL works。
![image](https://user-images.githubusercontent.com/19544252/223307829-b9c1e865-453e-47a6-bb47-e6b0fb8ae268.png)
In addition, When I change the alias with some other Chinese characters  that different to column name, the SQL also works.
![image](https://user-images.githubusercontent.com/19544252/223308507-00891942-8e27-4e27-9ba7-668bb7c5c265.png)
Clickhouse Server version is ClickHouse 23.2.3.17.
Is it a bug?
Thanks!

**Comment by Alex-Cheng** [comment]
It should be a bug, I can produce it too and I cannot find a workaround yet.

**Comment by den-crane** [comment]
@Alex-Cheng provide a repro

**Comment by Alex-Cheng** [comment]
https://fiddle.clickhouse.com/4ab4f391-34b0-42f1-97b0-7e7a5a3b0e0b
