### ISSUE TITLE
[FR] move partitions between 2 tables atomically.   

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#4729]
**Use case**
In certain maintenance scenarios when you move partitions between two tables, it would be cool to have atomic detach/attach command, to guarantee that no selects will 'see' intermediate state (when there is no data for a partition for a while, or when there is doubled data). It can be needed during migration from MergeTree to ReplicatedMergeTree (or vice versa), for moving data between storages (like described here https://www.altinity.com/blog/2019/3/5/do-it-yourself-multi-volume-storage-in-clickhouse ) etc.  

**Describe the solution you'd like**
ALTER TABLE dst MOVE PARTITION '2019-09-20' FROM TABLE src;
1) src table locked
2) partition get copied to detached of dst (if possible by hard link, if not by usual file copy)
3) dst table locked
4) attach partition on dst & check that it was successful
5) drop partition on src 
6) unlock tables

**Describe alternatives you've considered**
1) manual copy / ATTACH / DETACH - manual filesystem manipulation, data can be changed during the copy, data is doubled for a while
2) DETACH / manual copy / ATTACH  - manual filesystem manipulation, no data for a while 
3) ALTER TABLE dst ATTACH partition FROM src / DROP  - almost good, but can't work cross storages (hard link based),  doubled data for a while

Also, it would be cool to allow file-copy fallbacks for `freeze` / `attach partition from` if hard link creation fails.

**Comment by aadant** [comment]
This is similar to ALTER TABLE ... EXCHANGE PARTITION in MySQL see https://dev.mysql.com/doc/refman/5.6/en/partitioning-management-exchange.html

**Comment by nvartolomei** [comment]
https://github.com/ClickHouse/ClickHouse/pull/6168

**Comment by filimonov** [comment]
For multi-disk case target table should have super set of disks of source table, in that case that move between tables (based on hardlinks) will be possible. After part moved from one table to another you can move it to another table by `Alter table dest move partition to volume... `
