### ISSUE TITLE
TimeoutStartSec=infinity dosent work on CentOS 7

### ISSUE THREAD

**Issue by alexeyrusnak** [ClickHouse/ClickHouse#47293]
Hi I have updated ClickHouse to 23.2.3 on CentOS 7

To restart I execute command and have error

systemctl restart clickhouse-server
Job for clickhouse-server.service failed because a timeout was exceeded. See "systemctl status clickhouse-server.service" and "journalctl -xe" for details.

If I remove TimeoutStartSec=infinity from /usr/lib/systemd/system/clickhouse-server.service it starts working well.

On CentOS 8 TimeoutStartSec=infinity working well

**Comment by Hipska** [comment]
I'm having the same problem in CentOS 7.

**Comment by Hipska** [comment]
It seems to be introduced in [#46613](https://github.com/ClickHouse/ClickHouse/pull/46613) and [#47051](https://github.com/ClickHouse/ClickHouse/pull/47051).
