### ISSUE TITLE
Materialized view ignoring subquery in WHERE clause 

### ISSUE THREAD

**Issue by HassanAlgoz** [ClickHouse/ClickHouse#47301]
This issue is probably related to #5562, which was closed by saying v19 supports subqueries. But it seems to me the issue is back again. I couldn't find anything in the documentation, guides, tutorials, nothing that explains this case.

**Describe what's wrong**

The subquery inside the materialized view doesn't work.

```SQL
CREATE MATERIALIZED VIEW IF NOT EXISTS spending_analytics
            ENGINE = AggregatingMergeTree()
                ORDER BY (year, account_id)
AS
SELECT
       account_id,
       toYear(created_at) AS year,
       sumSimpleState(amount) AS sum
FROM transaction
WHERE id NOT IN (SELECT original_tx_id FROM transaction WHERE type = 'REVERSAL')
GROUP BY (account_id, year);
```

**Does it reproduce on recent release?**

- Server version: `clickhouse/clickhouse-server:22.3.17`
- Client version: `22.3.17.13`
- Default settings

**How to reproduce**

A table, a view, and a sub-query in the WHERE clause inside this view.

Insert data to the table, and see that the view ignores that condition.

**Expected behavior**

I expect data to be filtered using the WHERE clause which includes the subquery but it doesn't.

**Comment by den-crane** [comment]
That is expected. `transaction` refers an inserted buffer in all cases not the real table.
You can use `view` as a workaround.

```
create view transaction_v as select * from transaction;


CREATE MATERIALIZED VIEW IF NOT EXISTS spending_analytics
....
WHERE id NOT IN (SELECT original_tx_id FROM transaction_v WHERE type = 'REVERSAL')
```

**Comment by HassanAlgoz** [comment]
What do you mean it is **inserted buffer**? it is just a table:
```
CREATE TABLE IF NOT EXISTS account_transaction (
     ...
) ENGINE = ReplacingMergeTree(updated_at)
        PARTITION BY toYYYYMM(created_at)
        ORDER BY (toYYYYMMDD(created_at), account_id, id);
```

The documentation doesn't mention anything about tables being buffers. Can you refer me to somewhere which I can understand more about the subject?

**Comment by den-crane** [comment]
see https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by den-crane** [comment]
https://clickhouse.com/blog/using-materialized-views-in-clickhouse

**Comment by ponizvezdochka** [comment]
> That is expected. `transaction` refers an inserted buffer in all cases not the real table. You can use `view` as a workaround.
> 
> ```
> create view transaction_v as select * from transaction;
> 
> 
> CREATE MATERIALIZED VIEW IF NOT EXISTS spending_analytics
> ....
> WHERE id NOT IN (SELECT original_tx_id FROM transaction_v WHERE type = 'REVERSAL')
> ```

This does not work anymore. Dirty hack: use `select from merge(schema, table_regexp)`

See: https://fiddle.clickhouse.com/6a633c3d-8540-440b-8293-2fb39a96168b
