### ISSUE TITLE
Push down predicate for Multi-Join

### ISSUE THREAD

**Issue by Slind14** [ClickHouse/ClickHouse#4731]
Hi there,

I gave the new flat multi-join a try. When I implemented it the query time exponentially increased e.g.

Query with both joins: **3444ms**

```sql
SELECT 
    group AS "_group",
    count() as "count",
    date AS "_date", 
    count() * AVG(valJoin1)) AS "valJoin1", 
    SUM(valJoin2) AS "valJoin2" 
FROM `main` r 
ANY LEFT JOIN (
    SELECT 
        toStartOfHour(timestamp) AS "dateHour", 
        device, 
        country_name, 
        val AS "valJoin1" 
    FROM `joinOne` 
    WHERE toDate(date) BETWEEN '2019-03-08' AND '2019-03-15'
    GROUP BY dateHour, device, country_name
) j1 ON toStartOfHour(r.timestamp) = j1.dateHour AND r.device = j1.device AND r.country_name = j1.country_name 
ANY LEFT JOIN (
    SELECT 
        impressionUUID, 
        if(sum(event) > 0, 1, 0) AS "valJoin2" 
    FROM `joinTwo` 
    WHERE (toDate(date) BETWEEN '2019-03-08' AND '2019-03-15') 
    GROUP BY impressionUUID
) j2 ON j2.impressionUUID = r.impressionUUID 
GROUP BY _group, _date
```

Query without join (400k rows in main) : **31ms**

```sql
SELECT 
    group AS "_group",
    count() as "count",
    date AS "_date"
FROM `main` r
GROUP BY _group, _date
```

Query with join on joinOne (8k rows in joinOne) : **73ms**

```sql
SELECT 
    group AS "_group",
    count() as "count",
    date AS "_date", 
    count() * AVG(valJoin1)) AS "valJoin1",
FROM `main` r 
ANY LEFT JOIN (
    SELECT 
        toStartOfHour(timestamp) AS "dateHour", 
        device, 
        country_name, 
        val AS "valJoin1" 
    FROM `joinOne` 
    WHERE toDate(date) BETWEEN '2019-03-08' AND '2019-03-15'
    GROUP BY dateHour, device, country_name
) j1 ON toStartOfHour(r.timestamp) = j1.dateHour AND r.device = j1.device AND r.country_name = j1.country_name
GROUP BY _group, _date
```

Query with join on joinTwo (200k rows in joinTwo) : **178ms**

```sql
SELECT 
    group AS "_group",
    count() as "count",
    date AS "_date", 
    SUM(valJoin2) AS "valJoin2" 
FROM `main` r
ANY LEFT JOIN (
    SELECT 
        impressionUUID, 
        if(sum(event) > 0, 1, 0) AS "valJoin2" 
    FROM `joinTwo` 
    WHERE (toDate(date) BETWEEN '2019-03-08' AND '2019-03-15') 
    GROUP BY impressionUUID
) j2 USING (impressionUUID)
GROUP BY _group, _date
```

**Comment by 4ertus2** [comment]
Hi,

Performance depend on JOINs order. Could you try with switched j1 and j2. There's no logic that switches them to the best order yet.

The second thing that you may check is would it depend on count of columns that are not in the query or not. I can imagine a situation then it would get more (up to all) columns from some table. Not only required ones. So would it be the same time if there's only affected columns in tables?

The third, you may rewrite your joins with subselects. In fact it's the thing ClickHouse actually do now with your joins itself. It wraps joins to subselects one by one in order they are written: (select ... (select ... main join j1 ...) join j2 ...)

**Comment by Slind14** [comment]
I tested it the other way around as well which is slightly slower. 2-4%

**Comment by 4ertus2** [comment]
Trying to reproduce. There's 3 times difference between 1 join vs 2 joins on my data (with same result). And 1% difference between multiple joins vs joins via subselects.

```
SELECT count(dt.d_year)
FROM date_dim AS dt
INNER JOIN store_sales ON dt.d_date_sk = store_sales.ss_sold_date_sk
WHERE dt.d_year = 1998

1 rows in set. Elapsed: 9.375 sec. Processed 18.07 million rows, 3.24 GB (1.93 million rows/s., 345.64 MB/s.)

SELECT count(dt.d_year)
FROM date_dim AS dt
INNER JOIN store_sales ON dt.d_date_sk = store_sales.ss_sold_date_sk
INNER JOIN (SELECT toInt32(1998) as year) s ON s.year = dt.d_year

1 rows in set. Elapsed: 30.727 sec. Processed 18.07 million rows, 3.24 GB (588.18 thousand rows/s., 105.47 MB/s.)

SELECT count(dt.d_year)
FROM (SELECT d_year FROM date_dim INNER JOIN store_sales ON date_dim.d_date_sk = store_sales.ss_sold_date_sk) dt
INNER JOIN (SELECT toInt32(1998) as year) s ON s.year = dt.d_year

1 rows in set. Elapsed: 30.348 sec. Processed 18.07 million rows, 3.24 GB (595.52 thousand rows/s., 106.79 MB/s.)
```

**Comment by Slind14** [comment]
@4ertus2 

> The second thing that you may check is would it depend on count of columns that are not in the query or not. I can imagine a situation then it would get more (up to all) columns from some table. Not only required ones. So would it be the same time if there's only affected columns in tables?

You are right, this seems to be the case. When use a sub query to select all the required fields from main first it only takes 300ms.

Is this there a workaround or fix which does not require doing the pre-select of the required columns?

**Comment by 4ertus2** [comment]
There's no workaround for now. We need to make some improvement in code.

**Comment by Slind14** [comment]
@4ertus2 do you think this is something that will be looked into/resolved soon?

**Comment by 4ertus2** [comment]
I'll try to make some solution this or next week in master branch. But there's some risks that it will not fix the problem.

**Comment by Slind14** [comment]
Thanks It will be great if this can be solved on CH side.

**Comment by 4ertus2** [comment]
Here is PR with option that may help. In fact, I still cannot reproduce the problem. So it would be great if you check it on your queries.

**Comment by Slind14** [comment]
I'm not seeing any difference. I pulled your cross branch, ran the release script and installed `clickhouse-common-static_19.5.1_amd64` as well as `clickhouse-server_19.5.1_all.deb``, was that the way to do it?

**Comment by 4ertus2** [comment]
Yup,

You need to 'set multiple_joins_omit_unused_columns = 1' and run your queries. Then rerun them with 'set multiple_joins_omit_unused_columns = 0'. So we can check if the option is working. We need times for
1. queries without option enabled
2. queries with option enabled
3. queries with subselect that remove unneeded columns from main.

If it works we'll enable the option by default later. It's not fully safe. Some queries can fail if it removes more columns then needed.

P.S.: It's better to run every case 4 times, discard first result and get median of 3 others.

**Comment by Slind14** [comment]
**stable**
 - normal query **2469ms**
 - with subselect **300ms**

**cross branch**
`set multiple_joins_omit_unused_columns = 1`
 - normal query **2479ms**
 - with subselect **300ms**

`set multiple_joins_omit_unused_columns = 0`
 - normal query **2476ms**
 - with subselect **300ms**

**Comment by 4ertus2** [comment]
Quite strange. Could you get me your schema (maybe obfuscated) and query with subselect to reproduce?

**Comment by Slind14** [comment]
schema https://gist.github.com/Slind14/8f36b6fa74fd982b01f751cc2e2fd199
query https://gist.github.com/Slind14/e2f264bbe1743a6084b8e32c0e26db4e
query subselect https://gist.github.com/Slind14/6b8fdf55b3fccf0e4a52d73537f0cba0

Does this help?

I could also give you access to the test-server if a simple NDA is fine by you?

**Comment by 4ertus2** [comment]
No need, I think. If you remove 'WHERE (toDate(date) >= '2019-03-14') AND (toDate(date) <= '2019-03-20')' from the last query with subselect you should get the same 2.5s.

Could we check it? Leave only the last WHERE section (after last JOIN) in your subselect variant.
Also you may be interested to try the query without subselects + 'set enable_optimize_predicate_expression = 1'.

**Comment by Slind14** [comment]
> No need, I think. If you remove 'WHERE (toDate(date) >= '2019-03-14') AND (toDate(date) <= '2019-03-20')' from the last query with subselect you should get the same 2.5s. Could we check it? Leave only the last WHERE section (after last JOIN) in your subselect variant.

You are right, without the `where` in the subselect it goes to 2500ms.

Would the `PREWHERE` solve this?

I'll try the second one in a second.

**Comment by Slind14** [comment]
`set enable_optimize_predicate_expression = 1` results in 2500ms as well

**Comment by 4ertus2** [comment]
> Would using PREWHERE instead solve this?
No, PREWERE needs special push down itself.

> set enable_optimize_predicate_expression = 1 results in 2500ms as well
I'll remove it. Hypothesis, that it could help is wrong.

**Comment by Slind14** [comment]
Is there any way to let it filter before doing the join without a subselect?

**Comment by 4ertus2** [comment]
For now you'd better use subselects.

**Comment by Slind14** [comment]
I just checked, this seems to be only the case when multiple joins are at work. With one join doing the subselect is even more expensive.

**Comment by Slind14** [comment]
@4ertus2 is there any other way? The query is built dynamically and the only I way see to achieve that on my end would be to parse the entire query, somehow detect which columns it requires and to add these to the subselect.

**Comment by 4ertus2** [comment]
There's no need to detect columns. You may use * or table_name.* in subselects.
You also could make a view with pre-filtration and select from it.

**Comment by Slind14** [comment]
Doesn't this load all the columns which we do not need?

**Comment by 4ertus2** [comment]
As we checked current algorithm works well and there's no difference between JOINS with multiple_joins_omit_unused_columns set and not set. Current multiple JOIN extract all columns at AST section in expectation that they would be removed at later processing stages. multiple_joins_omit_unused_columns forced to remove them at AST stage. And if there's no difference then current algo is well enough. All the difference is there's no WHERE section applying filter for the first tables.

**Comment by Slind14** [comment]
ok, thanks
