### ISSUE TITLE
Dereferencing nullptr in arrayReverse.cpp

### ISSUE THREAD

**Issue by joey-bd** [ClickHouse/ClickHouse#47327]
@alexey-milovidov @tavplubix @KochetovNicolai 

**Describe what's wrong**
![Screenshot 2023-03-08 at 3 22 36 PM](https://user-images.githubusercontent.com/124345785/223647842-1259eea4-38c0-48d2-a98b-af1b5fe677fb.png)
Line 95 potentially dereferences a `nullptr` by doing `res_nullable_col->getNullMapColumn()`. As checked in line 77, `res_nullable_col` could be `nullptr` hence there's a possibility that line 95 is dereferencing this `nullptr`.

**Comment by CheSema** [comment]
It looks suspicious at first glance. But as I see res_data is an empty copy if src_data. 
I suppose the invariant has to be correct
 `bool(src_nullable_col) == bool(res_inner_col)`.

I can add such assertion here. If you wish, you could contribute it by your self.
