### ISSUE TITLE
Dereference nullptr in Selectors.h

### ISSUE THREAD

**Issue by joey-bd** [ClickHouse/ClickHouse#47328]
@KochetovNicolai @tavplubix 

**Describe what's wrong**

![Screenshot 2023-03-08 at 3 28 38 PM](https://user-images.githubusercontent.com/124345785/223649010-c2b21578-9929-464f-b409-9c00738ae2d3.png)
Line 136 explicitly checks if `source_ptr == nullptr` but line 143 dereferences it.

**Comment by tavplubix** [comment]
There's a chance that `typeid(*source_ptr)` can be evaluated at compile time, but anyway, I failed to understand what this code checks. Maybe we can simply replace this `LOGICAL_ERROR` with `chassert(source_ptr);`

**Comment by alexey-milovidov** [comment]
@joey-bd, what is the name of the static analyzer that you've been testing?

**Comment by joey-bd** [comment]
Coverity

**Comment by alexey-milovidov** [comment]
We also use Coverity, but filtering false positives becomes too tedious.

**Comment by joey-bd** [comment]
Is it a false positive here? I thought it was a valid bug as we've checked that `source_ptr == nullptr` but we then dereference it in line 143.

**Comment by alexey-milovidov** [comment]
If there is no way to trigger it, it is not a bug.

**Comment by jh0x** [comment]
In the standard (5.2.8, expr.typeid) it says:

> When `typeid` is applied to an expression other than a glvalue of a polymorphic class type, the result refers
> to a `std::type_info` object representing the static type of the expression. Lvalue-to-rvalue (4.1), array-to-
> pointer (4.2), and function-to-pointer (4.3) conversions are not applied to the expression. If the type of the
> expression is a class type, the class shall be completely-defined. **The expression is an unevaluated operand
> (Clause 5).**

Also, there's an example on [cppreference.com](https://en.cppreference.com/w/cpp/language/typeid) that shows it's OK to do in certain cases.
