### ISSUE TITLE
Dereferencing nullptr in OptimizeIfChains.cpp

### ISSUE THREAD

**Issue by joey-bd** [ClickHouse/ClickHouse#47326]
@alexey-milovidov @tavplubix @kamalov-ruslan 
**Describe what's wrong**
We are potentially dereferencing a `nullptr` in the if branch at line 68.
![Screenshot 2023-03-08 at 3 10 03 PM](https://user-images.githubusercontent.com/124345785/223644673-35bafac2-b40a-4c6d-899e-d92db2ad8250.png)
Here, as checked for in the first condition of line 68, `function_args` could be a `nullptr`. If it is, we will take this branch to throw the exception but line 71 dereferences `function_args` by doing `->children.size()`.

This is a dereference of a `nullptr`

**Comment by CheSema** [comment]
Thanks for pointing out for such suspicious places.
As I see function_node->arguments has been checked at line 63. However the check lefts a room for a bug, arguments might have a different type.
Lest add one more check/assertion to be sure here.
