### ISSUE TITLE
Dereferencing nullptr in validateNestedArraySizes.cpp

### ISSUE THREAD

**Issue by joey-bd** [ClickHouse/ClickHouse#47325]
@hexiaoting 
**Describe what's wrong**
Line 80 potentially dereferences a `nullptr`
![Screenshot 2023-03-08 at 2 55 32 PM](https://user-images.githubusercontent.com/124345785/223640817-760252ec-f34a-4693-845c-8a5c25c7075c.png)
`typeid_cast` in line 63 could return a `nullptr` as confirmed by line 64.
I believe one way this happens is if `arguments[0].column.get()` returns a `nullptr` too. This would mean line 66 will return false.
Hence, we have the following values:

- `condition_column` = `nullptr`
- `is_condition_const` = false
- `condition` = false

With this, line 77 returns false so we do not break. Then in line 80, the first check returns true as `!is_condition_const` will return true and then we'll dereference `condition_column` by calling `->getData()[i]` on it.

This leads to a dereference of a `nullptr`.

**Does it reproduce on recent release?**
Yes

**Enable crash reporting**

**Comment by tavplubix** [comment]
> Does it reproduce on recent release?
> Yes

How to reproduce it? Please provide a test that reproduces this nullptr dereference.

Seems like the argument can be either `UInt8` or `Nullable(UInt8)`, we can add an assertion to make it more clear. However, I'm not sure about `LowCardinality(UInt8)`.
