### ISSUE TITLE
system.parts inconsistent quoting

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#4735]
18.16 address quoting problems in system.parts.  See #3109 and #3652.

After that change all the single values partition names are unquoted always (also for Strings / DateTimes etc), and it is inconsistent, so for example - you can't just create alters from system.parts in a simple manner because String / Date / DateTime - based partitions are also unquoted.

Check that:
```sql
SELECT 'ALTER TABLE '  || table || ' DETACH PARTITION ' || partition from system.parts group by table, partition ORDER BY table, partition;

 ALTER TABLE toyyyymm_partitioning DETACH PARTITION 201802      -- ok
 ALTER TABLE empty_partitioning    DETACH PARTITION tuple()     -- ok 
 ALTER TABLE tuple_partitioing     DETACH PARTITION (3,3,'333') -- ok 
 ALTER TABLE float_part            DETACH PARTITION 0.001       -- ok
 ALTER TABLE int_part              DETACH PARTITION 0           -- ok
 ALTER TABLE date_partitioning     DETACH PARTITION 2018-05-16           -- wrong, quotes needed
 ALTER TABLE string_partitioning   DETACH PARTITION string_partition_id  -- wrong, quotes needed
 ALTER TABLE datetime_partitioning DETACH PARTITION 2019-03-20 14:12:59  -- wrong, quotes needed
```

**Comment by SaltTan** [comment]
It would be nice if ALTER TABLE could accept system.parts.partition_id as a partition identifier.
We would not need any complicated logic then to generate ALTER statements...

**Comment by den-crane** [comment]
> It would be nice if ALTER TABLE could accept system.parts.partition_id as a partition identifier.
> We would not need any complicated logic then to generate ALTER statements...

I concur 

and PARTITION expect an expression (201802 === 201802/2*2+0)
so I prefer PARTITION_ID or ( PARTITION ID )

`ALTER TABLE int_part  DETACH PARTITION_ID 'all'`
`ALTER TABLE int_part  DETACH PARTITION_ID '20180516'`

with strict checking that PARTITION_ID 'all' exists and DETACH / OPTIMIZE / DROP performed to this PARTITION_ID

**Comment by alexey-milovidov** [comment]
The issue is no longer relevant as the syntax with PARTITION ID was added.
