### ISSUE TITLE
The splitByChar function cannot use invisible characters

### ISSUE THREAD

**Issue by ZXBmmt** [ClickHouse/ClickHouse#47369]
My business data is split per row with '\036'. I want to split columns using splitByChar, but an error is reported.

The usage is as follows:

select splitByChar('\036',message) as signSec from kafka.kafka_padx_otc_v2_log limit 10;

Code: 36. DB::Exception: Received from localhost:9000. DB::Exception:  Illegal separator for function splitByChar. Must be exactly one byte..

**Comment by cangyin** [comment]
As per #37765, literals like '\036' are not parsed as oct numbers. you have to use hexidecimal form.

```sql
select splitByChar('\x41', 'XXAYY')

┌─splitByChar('A', 'XXAYY')─┐
│ ['XX','YY']               │
└───────────────────────────┘
```

**Comment by den-crane** [comment]
You mean?

Decimal | Octal | Hex | Binary | Value | Description
-- | -- | -- | -- | -- | --
030 | 036 | 1E | 0001 1110 | RS | request to send/record separator

```sql
select  splitByChar('\x1E', 'A\x1EAA');
┌─splitByChar('', 'AAA')─┐
│ ['A','AA']             │
└────────────────────────┘
```

```sql
select  splitByChar(char(30), 'A\x1EAA');
┌─splitByChar(char(30), 'AAA')─┐
│ ['A','AA']                   │
└──────────────────────────────┘
```

**Comment by ZXBmmt** [comment]
yes, thank you very much !
