### ISSUE TITLE
Rework style-check image

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#47367]
It now uses bash for the checking and python for result processing.

I want to get rid of bash in favor of pure python.

Besides that, there's another useful linter for Dockerfiles https://github.com/hadolint/hadolint, it's time to use it.

**Comment by alexey-milovidov** [comment]
I like the check-style script - it's easy to modify and support.

**Comment by alexey-milovidov** [comment]
I also have bragged multiple times about this script on social media. It proved to be effective.

**Comment by alexey-milovidov** [comment]
Also, to highlight - I am the main user and consumer of this script.

**Comment by Felixoid** [comment]
It's nothing about `check-style` script, but about `clickhouse/style-check` image. The `entrypoint` is badly designed and will be rewritten to a pure python implementation

**Comment by Felixoid** [comment]
It's done, thanks to Max
