### ISSUE TITLE
how to efficient query each time bucket one point?

### ISSUE THREAD

**Issue by zdyj3170101136** [ClickHouse/ClickHouse#47388]
table schema:
```
CREATE TABLE default.parca_index_local
(
    `timestamp` DateTime('UTC') CODEC(Delta(4), ZSTD(1)),
    `labels.key` Array(LowCardinality(String)) CODEC(ZSTD(1)),
    `labels.value` Array(LowCardinality(String)) CODEC(ZSTD(1))
)
ENGINE = MergeTree
PARTITION BY toDate(timestamp)
ORDER BY (timestamp)
SETTINGS index_granularity = 1024
```

labels is a unique key-value pair.

i want to split query time by bucket, and let per time bucket of one unique label one point.
assume time bucket is 3 second:
```
SELECT
    any(totalValue),
    any(labels.key),
    any(timestamp)
FROM parca_index
WHERE (timestamp > '2023-03-08 02:54:00') AND (timestamp < '2023-03-08 03:54:00')
GROUP BY
    toInt64(toUInt64(timestamp) / 3),
    labels.key,
    labels.value
```

it is not very efficient.

1, query use any:
```
SELECT
    any(labels.key),
    any(labels.value),
    any(timestamp)
FROM parca_index
WHERE (timestamp > '2023-03-08 02:54:00') AND (timestamp < '2023-03-08 03:54:00')
GROUP BY
    toInt64(toUInt64(timestamp) / 3),
    labels.key,
    labels.value

18969355 rows in set. Elapsed: 11.673 sec. Processed 22.54 million rows, 1.39 GB
```

2, query directly:
```
SELECT
   labels.key,
   labels.value,
   timestamp
FROM parca_index
WHERE (timestamp > '2023-03-08 02:54:00') AND (timestamp < '2023-03-08 03:54:00')

22534604 rows in set. Elapsed: 4.850 sec. Processed 22.54 million rows, 1.39 GB 
```

#### version
```
21.8.2 
```

**Comment by davenger** [comment]
Hi @zdyj3170101136 could you please provide an example of what is inside label.key and label.value arrays (how many elements they typically contain in each row?) and what the expected query result should look like? BTW, have you tried newer ClickHouse version, because there might have been performance improvements since 21.8.2?

**Comment by zdyj3170101136** [comment]
> 你好@zdyj3170101136您能否提供一个示例，说明 label.key 和 label.value 数组中的内容（每行通常包含多少个元素？）以及预期的查询结果应该是什么样子？顺便说一句，您是否尝试过更新的 ClickHouse 版本，因为自 21.8.2 以来性能可能有所改进？

the label key value is a unique series (every minute one point).
it may contain 6 ~ 10 value.
![截屏2023-03-13 上午10 18 20](https://user-images.githubusercontent.com/52686065/224593150-bca346bd-01c0-4548-955b-16a9f37ba2c3.png)

**Comment by zdyj3170101136** [comment]
each label key, value is a unique series, just like prometheus.
so i expect the performance just like prometheus.
 we can easily find one time point each time bucket per series in a large search time range.

**Comment by den-crane** [comment]
18969355 rows in set.
