### ISSUE TITLE
Different passwords for each database

### ISSUE THREAD

**Issue by vinith-reddy25** [ClickHouse/ClickHouse#47394]
Can we have different passwords for each database created in clickhouse

Let say we have two databases "helloworld1" and "helloworld2". So, to run queries on different databases we will use different passwords?

I need above functionality in sqlalchemy uri: 
**clickhousedb://default:password1@clickhouse:8123/hellowolrd1
clickhousedb://default:password2@clickhouse:8123/helloworld2**

**Comment by davenger** [comment]
@vinith-reddy25 you will need to create 2 users with different names (e.g. default1 and default2) with the corresponding passwords:

clickhousedb://default1:password1@clickhouse:8123/hellowolrd1
clickhousedb://default2:password2@clickhouse:8123/helloworld2
