### ISSUE TITLE
How to deploy disaster recovery

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#47392]
We have clickhoue cluster already, includes 3 servers. Now, we are going to deploy the disaster recovery environment. We can accept the high delay, even backup the increment data in each day.

Is there any suggestion?  any online or off-line solution? 

Thanks!

**Comment by davenger** [comment]
Hi @taotaizhu-pw! Just want to double check it you have seen the doc on backup/restore https://clickhouse.com/docs/en/operations/backup ?
