### ISSUE TITLE
json object type can't use data skipping indexes 

### ISSUE THREAD

**Issue by coulsonm** [ClickHouse/ClickHouse#47418]
**Describe what's wrong**

Json object type can't use data skipping indexes when create table

**Does it reproduce on recent release?**

Experienced in our production on version 22.3.3

**How to reproduce**
Create table like this:
`CREATE TABLE json
(
    `o` Object('json'),
    INDEX index1 o.a TYPE bloom_filter GRANULARITY 4
)
ENGINE = Memory`

then

`Received exception from server (version 22.3.3):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'o.a' while processing query: '`o.a`', required columns: 'o.a' 'o.a'. (UNKNOWN_IDENTIFIER)
`
I know it's not the right way.Is there any other way to use index？

**Comment by CurtizJ** [comment]
Currently it's not supported. It will be possible to do this with `JSONExtract` after #41529 will be merged.
