### ISSUE TITLE
how to find housekeeper node path when using clickhouse-copier 

### ISSUE THREAD

**Issue by huwngnosleep** [ClickHouse/ClickHouse#47417]
I read the tutorial in https://clickhouse.com/docs/en/operations/utilities/clickhouse-copier/, the command to run is:
```
clickhouse-copier --daemon --config keeper.xml --task-path /task/path --base-dir /path/to/dir
```

but I got a trouble with --task-path, I don't know what my node path is. How can I retrieve this information?

**Comment by CurtizJ** [comment]
`--task-path` can be any unique path for task in keeper, e.g. `/clickhouse-copier/task_1`.  If this node doesn't exist it will be created automatically by `clickhouse-copier`.
