### ISSUE TITLE
23.2 silently ignores some rows from parquet + returns fake data. regression from 22.12

### ISSUE THREAD

**Issue by chfanboy** [ClickHouse/ClickHouse#47447]
23.2 has very weird behaviour when reading parquet. Some rows are completely and silently! ignored. Moreover, it depends on columns it reads, for some columns it returns data, when I query a different subset of columns - nothing is returned.

Here is a file that reproduces the problem - [https://ch-chronos.s3.amazonaws.com/data.parquet](https://ch-chronos.s3.amazonaws.com/data.parquet)

Query that returns data:

```jsx
SELECT exchange_ts
FROM file('/var/lib/clickhouse/user_files/data.parquet')
WHERE exchange_ts = 1670964058771367936

Query id: 80f16e7c-876c-4256-9de4-b96f3b37a86b

┌─────────exchange_ts─┐
│ 1670964058771367936 │
└─────────────────────┘
```

If I query all columns, nothing is there:

```jsx
SELECT *
FROM file('/var/lib/clickhouse/user_files/data.parquet')
WHERE exchange_ts = 1670964058771367936

Query id: 502a8833-b056-4362-86a1-b5b39ba43ea3

Ok.
```

Moreover, it returns fake data which does not even exist in the file.

Following query returns 2 rows, one of which does not exist

```jsx
SELECT
    exchange_ts,
    market,
    product
FROM file('/var/lib/clickhouse/user_files/data.parquet')
WHERE exchange_ts = 1670946478544048640

Query id: 55b64592-0e7d-4c7c-a23b-79ab8edc4eb1

┌─────────exchange_ts─┬─market─┬─product────┐
│ 1670946478544048640 │ NASDAQ │ cqs_pillar │
└─────────────────────┴────────┴────────────┘
┌─────────exchange_ts─┬─market─┬─product────┐
│ 1670946478544048640 │ ARCA   │ cqs_pillar │
└─────────────────────┴────────┴────────────┘

Now query just exchange_ts and market:
SELECT
    exchange_ts,
    market
FROM file('/var/lib/clickhouse/user_files/data.parquet')
WHERE exchange_ts = 1670946478544048640

Query id: c6ea7c2c-6e95-401f-bb5f-4751d75e83ad

┌─────────exchange_ts─┬─market─┐
│ 1670946478544048640 │ ARCA   │
└─────────────────────┴────────┘

Single row, and that is corrent.

cross check in pandas:
import parndas as pd
df = pd.read_parquet('/tmp/data/data.parquet')
df = df.loc[df['exchange_ts'] == 1670946478544048640]
print(df)

This returns single row

22.12 also returns single correct row
```

Summary - for this concrete file 22.13 returns complete mess. 22.12 works just fine

**Comment by den-crane** [comment]
repro

https://fiddle.clickhouse.com/f17fddd7-024d-4d1c-bb64-5033e6df95d0

**Comment by den-crane** [comment]
@Avogar

**Comment by Avogar** [comment]
After some research I found that this PR led to such behaviour: https://github.com/ClickHouse/ClickHouse/pull/45878
@liuneng1994 Let's first investigate how it led to it. If we won't find a problem soon, let's revert this PR.

**Comment by den-crane** [comment]
it returns different results with different `input_format_parquet_max_block_size`

https://fiddle.clickhouse.com/06919bc6-1421-4bd6-9553-2402c940cf59

**Comment by Avogar** [comment]
It may be a bug in arrow library. I will investigate it on Monday and will try to write a c++ script that reproduces it just using arrow library. If so, we will revert that PR and submit an issue to arrow lib.

**Comment by alexey-milovidov** [comment]
@Avogar, why don't revert immediately?

**Comment by Avogar** [comment]
I just suspected that there is a bug on our side and we can fix it easily. I just checked one more time and cannot find a bug on our side. Let's revert. I will add a test with a file from this PR a bit later.

**Comment by Avogar** [comment]
Done
