### ISSUE TITLE
Inconsistent docs with absolute path in `format_schema`

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#4745]
[Docs](https://clickhouse.yandex/docs/en/interfaces/formats/#formatschema) says:

> If you input or output data via the client the file name specified in the format schema can contain an absolute path or a path relative to the current directory on the client

Running this:

```sql
SETTINGS format_schema = '/var/lib/clickhouse/format_schemas/message.proto:Message'
```

Results in 

```
Received exception from server (version 19.4.1):
Code: 36. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Absolute path in the 'format_schema' setting is prohibited: /var/lib/clickhouse/format_schemas/message.proto.
```

Not sure what's proper behaviour, just reporting inconsistence

**Comment by alexey-milovidov** [comment]
Server cannot use absolute path for security reasons.
Client can accept absolute path.

**Comment by olgarev** [comment]
@alexey-milovidov Documented already, please remove the `comp-documentation` label.

**Comment by alexey-milovidov** [comment]
Perfect.
