### ISSUE TITLE
is there any option to force large-memory query to use disk?

### ISSUE THREAD

**Issue by huwngnosleep** [ClickHouse/ClickHouse#47461]
I have a query may consume about 40Gb RAM running on a server which has only 32Gb, I saw an option of GROUP BY external, but for in case "any" other operations? May be we have an option like max_memory_before_using_external?

Or just for external JOIN, it will help me a lot.

**Comment by den-crane** [comment]
>but for in case "any" other operations

No.

There is 
groupby - `max_bytes_before_external_group_by` 
sort - `max_bytes_before_external_sort arg`
join - `join_algorithm` (join_algorithm = 'grace_hash')  https://gist.github.com/den-crane/0c67d37d9ee4fb3e3251ef27cb8a8d4b
