### ISSUE TITLE
Add a function `nodeNumber`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#4747]
**Use case**
Return a sequential number for every shard participated in distributed query execution. For tests.
Example:

```
SELECT shardNumber() FROM remote('127.0.0.{1,2}', system.one)

0
1
```

**Comment by alexey-milovidov** [comment]
For #4741

**Comment by alex-krash** [comment]
@alexey-milovidov , this function will not take into consideration topology of clusters, described in configuration?
Why I am asking - we have host being assigned to multiple clusters/shards.
```
SELECT 
    groupArray((cluster, shard_num)) AS cluster_and_shard, 
    host_name
FROM system.clusters 
WHERE host_name = 'clickhouseuds1.mlan'
GROUP BY host_name
ORDER BY host_name ASC

┌─cluster_and_shard────────────────────────────┬─host_name───────────┐
│ [('all_mlan',5),('common',3),('uds_mlan',3)] │ clickhouseuds1.mlan │
└──────────────────────────────────────────────┴─────────────────────┘

```

**Comment by alexey-milovidov** [comment]
It will assign numbers to shards dynamically depending on the set of shards participated in a query.

**Comment by olegkv** [comment]
@alexey-milovidov maybe nodeNumber() would be better? 
Query can run on some arbitrary set of nodes, these nodes are not always part of any cluster or can be parts of multiple clusters, and using word "shard" could be confusing with real shards, like alex-krash mentioned..

**Comment by alexey-milovidov** [comment]
> maybe nodeNumber() would be better?

Yes, this name is better.

**Comment by alexey-milovidov** [comment]
It was implemented through virtual column: https://github.com/ClickHouse/ClickHouse/pull/7624
