### ISSUE TITLE
Is the clickhouse-copier support backup incremental data in each day to DR env?

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#47517]
We would build the Disaster Rcovery Environment. Our prod clickhouse cluster env has 3 nodes. Is it possible to run clickhouse-copier  in each day once at 5:00AM to backup the incremental data to DR servers?

If it is not a good solution, is there any suggestion? thanks!

**Comment by Alex-Cheng** [comment]
I am also interested in the topic.

**Comment by hyj629222521** [comment]
me too

**Comment by hkrutzer** [comment]
I don't know about clickhouse-copier but maybe https://kb.altinity.com/altinity-kb-setup-and-maintenance/clickhouse-backup-diff/ can be of help.

**Comment by taotaizhu-pw** [comment]
we already used clickhouse-backup to backup the whole data in each day. 

But, we have not found how to backup the incremental data.



***@***.***
 
From: Hans Krutzer
Date: 2023-03-13 21:21
To: ClickHouse/ClickHouse
CC: taotaizhu-pw; Author
Subject: Re: [ClickHouse/ClickHouse] Is the clickhouse-copier support backup incremental data in each day to DR env? (Issue #47517)
I don't know about clickhouse-copier but maybe https://kb.altinity.com/altinity-kb-setup-and-maintenance/clickhouse-backup-diff/ can be of help.

**Comment by hkrutzer** [comment]
The page I linked makes a full backup on mondays and differential/incremental backups every hour.

**Comment by taotaizhu-pw** [comment]
> The page I linked makes a full backup on mondays and differential/incremental backups every hour.

Thanks!   Does this solution need mid storage for transition, such as s3 ? Any point to point solution?

**Comment by taotaizhu-pw** [comment]
any reply from clickhouse?

**Comment by taotaizhu-pw** [comment]
hello?
