### ISSUE TITLE
OOM on group by query

### ISSUE THREAD

**Issue by rikuiki** [ClickHouse/ClickHouse#47521]
> You have to provide the following information whenever possible.

select v, count(*) ... group by 1 produces OOM

> A clear and concise description of what works not as it is supposed to.

I created table from external tsv as MergeTree:

set max_memory_usage = 8000000000;
set max_memory_usage_for_user = 8000000000;
set max_bytes_before_external_group_by = 10000000;
set max_bytes_before_external_sort = 10000000;

create table if not exists t ENGINE = MergeTree() order by v1 as
select *
from file('/usr/proj/tsv-*', TabSeparated, 'v1 text, v2 text, v3 text, seq bigint');

Table has 3B rows.

I run following query:

select v1, count(*) from t group by 1 limit 5;

I receive following error:

Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 7.45 GiB (attempt to allocate chunk of 4225696 bytes), maximum: 7.45 GiB.: While executing SourceFromNativeStream. (MEMORY_LIMIT_EXCEEDED)

**Comment by rikuiki** [comment]
Alexey, maybe you have a chance to comment why do you think it is not a potential bug?..

**Comment by nickitat** [comment]
memory limit currently strictly limits only pre aggregation phase (separate aggregation on execution threads). at the time of merging we need to bring smth around `total_aggr_state_size * aggregation_memory_efficient_merge_threads / NUM_BUCKETS (=256)` into memory. and you got error at merging phase as you see.
as a workaround you could try to lower `aggregation_memory_efficient_merge_threads` if increasing memory limit is not an option.
#40588 is aimed to address this issue

**Comment by rikuiki** [comment]
Thank you for explanation!

> it is not a good idea to set max_bytes_before_external_group_by too low. 

I did this just for testing purposes, to check if ClickHouse can handle aggregation when data doesn't fit into memory, and reduced it even more when seen OOM.
