### ISSUE TITLE
A confusion about the command of Explain

### ISSUE THREAD

**Issue by zyxdSTU** [ClickHouse/ClickHouse#47523]
I try to use the command of explain to verify the  sql statement is correct.
When I execute the command `explain insert into student values(1, '小明', 2), (2, '小红', 1), (3, '小黑', 2);`,  it goes wrong. 
![image](https://user-images.githubusercontent.com/26239665/224651658-2b297429-747c-4f24-900c-5ce9b8395507.png)
But I can execute `insert into student values(1, '小明', 2), (2, '小红', 1), (3, '小黑', 2);` no problem,
so can you tell me, what's wrong.

**Comment by Alex-Cheng** [comment]
EXPLAIN statement is only applicable for SELECT query. Refer the following syntax:
![image](https://user-images.githubusercontent.com/1518453/224911734-ca7590f2-6182-4674-9a27-ee0508f76f24.png)

**Comment by Alex-Cheng** [comment]
The example you given will utilize the `MergeTreeSink` to complete insertion behavior.

**Comment by zyxdSTU** [comment]
> The example you given will utilize the `MergeTreeSink` to complete insertion behavior.
Got it, Thanks
