### ISSUE TITLE
any way to avoid "division by zero" for decimal datatype without if ?

### ISSUE THREAD

**Issue by jasonbigl** [ClickHouse/ClickHouse#47524]
Hi,

the "division by zero" for decimal exception can be avoid by if and short_circuit_function_evaluation.

but the problem is our product allows user to write a formula to define a column, the formula is not fixed and can be complicated, such as: cost/(clicks + views) * 100.

we will validate the formula and make it legal, but the problem is it's hard to rewrite the formula with if statement to avoid "division by zero" problem when comes with decimal.

in such case, is there any otherway to avoid the exception? (without if or multiIf statement)
return inf or 0 or anything else would be fine, just don't throw exceptions.

Thank you very much.

**Comment by den-crane** [comment]
There is no sql way to catch/suppress exception.
