### ISSUE TITLE
trying to get name of not a column: Set for table function

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#47533]
```sql

SELECT count() FROM mysql(mysql('127.0.0.1:9004', currentDatabase(), foo, 'default', '', SETTINGS connection_pool_size = 1), '127.0.0.1:9004', currentDatabase(), foo, '', '')

```

https://s3.amazonaws.com/clickhouse-test-reports/47316/027db789d6a40fa11a3dfbc93bbda1825a8371d6/fuzzer_astfuzzerasan/report.html

https://s3.amazonaws.com/clickhouse-test-reports/47316/027db789d6a40fa11a3dfbc93bbda1825a8371d6/fuzzer_astfuzzerubsan/report.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/5d64841276d5439c9ed0066eaf7afc19f78b664a/fuzzer_astfuzzerasan/report.html

**Comment by alexey-milovidov** [comment]
Not fixed :(

**Comment by alexey-milovidov** [comment]
`SELECT * FROM numbers(SETTINGS x = 1)`
