### ISSUE TITLE
Add compression_codec to system.parts and system.parts_columns

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#47555]
**Use case**

Need to know when ALTER TABLE applies partially to some parts
Need to know when some columns have different compression and codec in different parts

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

add `compression_codec` field to system.parts and system.parts_columns
use default_compression_codec.txt and *.bin files as source of true

**Comment by den-crane** [comment]
see default_compression_codec column in  system.parts

**Comment by Slach** [comment]
If we define custom codec for column? is present in system.parts_columns?

**Comment by den-crane** [comment]
>If we define custom codec for column? is present in system.parts_columns?

It presents in the system.columns.

It is impossible to know the real codec without reading the bin file.
