### ISSUE TITLE
Incorrect values insertion into the `is_deleted` column of new ReplacingMergeTree engine

### ISSUE THREAD

**Issue by AlmostIvanSidorov** [ClickHouse/ClickHouse#47579]
Disabling the `optimize_on_insert` setting can result in the insertion in a ReplacingMergeTree table of incorrect data into the `is_deleted` column. As a consequence, running `SELECT ... FINAL` queries on the inserted tables leads to an exception.

https://fiddle.clickhouse.com/17113269-e156-4cd3-b00c-6622050c15b9

**How to reproduce:**

ClickHouse version 23.2
```
CREATE TABLE default.test
(
    `id` String,
    `version` UInt32,
    `is_deleted` UInt8
)
ENGINE = ReplacingMergeTree(version, is_deleted)
ORDER BY id
SETTINGS index_granularity = 8192

SET optimize_on_insert=0;

INSERT INTO test VALUES ('data1', 1, '6');

SELECT * from test FINAL

```
**Result:**
Received exception from server (version 23.2.3):
Code: 117. DB::Exception: Received from localhost:9000. DB::Exception: Incorrect data: is_deleted = 6 (must be 1 or 0).: While executing ReplacingSorted. (INCORRECT_DATA)

**Comment by tavplubix** [comment]
Workaround: https://clickhouse.com/docs/en/sql-reference/statements/create/table#constraints
