### ISSUE TITLE
Invalid number of rows in Chunk column UInt64 in AggregatingTransform 

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#47572]
```
Logical error: 'Invalid number of rows in Chunk column UInt64 position 1: expected 34590, got 34591'.
```

https://s3.amazonaws.com/clickhouse-test-reports/47304/dd77962048473da7343b639ecb9ed424ad23a40a/fuzzer_astfuzzermsan/report.html

**Comment by Algunenano** [comment]
Report is gone and there is no reproducer
