### ISSUE TITLE
Different String but have the same ngramSimHash

### ISSUE THREAD

**Issue by alps99w** [ClickHouse/ClickHouse#47580]
CH Version: 22.3.2.1.

SELECT ngramSimHash('https://ayarnstory.co.uk/products/brooklyn-tweed-lofthttps://beehivewoolshop.com/products/loft-brooklyn-tweedhttps://brooklyntweed.com/collections/loft-pattern-collectionhttps://brooklyntweed.com/products/lofthttps://fancytigercrafts.com/collections/brooklyn-tweedhttps://hillcountryweavers.com/products/lofthttps://loopknitting.com/en-us/products/brooklyn-tweed-lofthttps://shop.mckinneyknittery.com/shop/c/p/Brooklyn-Tweed-Loft-x44749423.htmhttps://the-blue-purl.shoplightspeed.com/yarn/fingering/brooklyn-tweed-loft/https://twistedyarnshop.com/products/brooklyn-tweed-lofthttps://unwindfiberarts.com/products/brooklyn-tweed-lofthttps://www.artofyarn.com/brooklyn-tweed-loft-old-world.htmlhttps://www.blackmountainyarnshop.com/products/brooklyn-tweed-lofthttps://www.blacksheepyarns.ca/products/brooklyn-tweed-lofthttps://www.churchmouseyarns.com/products/brooklyn-tweed-lofthttps://www.purlsoho.com/loft.htmlhttps://www.ravelry.com/yarns/library/brooklyn-tweed-lofthttps://www.toltyarnandwool.com/products/brooklyn-tweed-lofthttps://www.woolandcompany.com/yarn/super-fine-fingering/brooklyn-tweed-loft/https://yarnsub.com/yarns/brooklyn_tweed/loft') AS simHash
UNION ALL
SELECT ngramSimHash('https://alejandrorioja.com/increase-alexa-rank/https://blog.linkody.com/guides/increase-alexa-rankingshttps://bloggingden.com/get-better-alexa-rank/https://brandastic.com/blog/what-is-alexa-rank/https://kinsta.com/blog/alexa-rank/https://prnews.io/blog/how-to-increase-alexa-rank.htmlhttps://seattlewebsitedesign.medium.com/using-alexa-and-improving-alexa-rank-df388332e543https://seo.london/how-increase-alexa-ranking/https://wpengine.com/resources/wordpress-alexa-ranking/https://www.admecindia.co.in/digital-marketing/10-very-important-tips-improve-alexa-ranking-website/https://www.egroup.com.cy/news-and-publications/145-increase-your-alexa-rankhttps://www.ionos.com/digitalguide/online-marketing/search-engine-marketing/how-can-i-increase-my-alexa-rank/https://www.jimmilan.com/increase-alexa-rank/https://www.linkedin.com/pulse/what-alexa-rank-how-increase-2021-digital-gabbarhttps://www.quicksprout.com/how-to-increase-alexa-ranking/https://www.quora.com/How-can-I-Improve-my-Alexa-rankinghttps://www.shoutmeloud.com/increase-domain-authority.htmlhttps://www.webhopers.com/improve-alexa-ranking-fasthttps://www.wikihow.life/Improve-Your-Alexa-Ranking') AS simHash

Query id: 49cf33ce-4205-471d-95d2-31191c500827

┌────simHash─┐
│ 2475118590 │
└────────────┘
┌────simHash─┐
│ 2475118590 │
└────────────┘

**Comment by alexey-milovidov** [comment]
This is fine. SimHash is an approximate algorithm.
