### ISSUE TITLE
ClickHouse FLOAT 64 precision problem

### ISSUE THREAD

**Issue by T-M-L-C** [ClickHouse/ClickHouse#47600]
When the version of the ClickHouse database is 21.8. 8.1, the field type of a column in the data table is FLOAT64, and the inserted data is 1.14, the query result is 1.1400000000000001. How to solve this problem?
![image](https://user-images.githubusercontent.com/12447886/225193019-2d432a13-4362-460e-9148-535639fcd619.png)

**Comment by den-crane** [comment]
You can use Decimal type.
Or `round( ,2)`

see https://github.com/ClickHouse/ClickHouse/issues/17933

**Comment by T-M-L-C** [comment]
Thank you for providing the perfect solution to this problem.
