### ISSUE TITLE
Question about code of WindowTransform::prepare()

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#47605]
Shouldn't we invoke `output.finish()` when `output.isFinished() == false` and `isCancelled() == true`?

![image](https://user-images.githubusercontent.com/1518453/225244203-e8f908a3-1598-4e8b-a5ae-09acc124bda8.png)

The member variable `output_data` is always reused and never get reset. Is there any unwanted remaining of old `output_data` which output as a part of new block? 

![image](https://user-images.githubusercontent.com/1518453/225253100-1fdfb146-94a8-4f95-8d72-f333560c155f.png)

**Comment by davenger** [comment]
AFAIS output_data gets moved, so its contents gets cleared
