### ISSUE TITLE
ClickHouse replication workflow with details

### ISSUE THREAD

**Issue by zbhuang2008** [ClickHouse/ClickHouse#47618]
Is there any doc about the details of replication internals in clickhouse (how replication works inside clickhouse) ?
So far, I only found some description from "Overview of ClickHouse Architecture", https://clickhouse.com/docs/en/development/architecture/, but this description is still missing a lot of details. something like the following part - for example, when insertion happens in the clickhouse node1, it will push the LogEntry to zookeeper. The other clickhouse node2 detects this change then fetches this LogEntry from the zookeeper and wraps up as a task and puts into its task queue and wait for it to be executed. When this task is being picked, it will download the data from clickhouse node1.

Appreciate it if someone can give me some hint/direction about how to find those details (for example, how to setup the debug env  so that I can debug through to understand those details). 

Thanks.

**Comment by davenger** [comment]
You can find some more details here https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/
Also you can look at the comments in the code describing how it works, e.g. here
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageReplicatedMergeTree.h#L46-L88
