### ISSUE TITLE
Catboost: HTML Form Exception: Field value too long when trying to use on dataset

### ISSUE THREAD

**Issue by oleg-savko** [ClickHouse/ClickHouse#47616]
When Try to execute function `catboostEvaluate` on dataset (approximately with more then 2150 records), its throw exception:

`Code: 86. DB::HTTPException: Received error from remote server /catboost_request?version=1&method=catboost_libEvaluate. HTTP status code: 500 Poco::Exception. Code: 1000, e.code() = 0, HTML Form Exception: Field value too long,. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER) (version 22.12.3.5 (official build)) , server ClickHouseNode [uri=http://warehouse.moneyman.ru:8126/default, options={socket_timeout=3000000,session_id=DataGrip_9c45cb7e-1db0-43c5-bf64-4242ce1fbce8}]@-2019543159`

If it use with less records its work fine (ex: limit 2000).
 And problem not in records trying with different offset, and with my data I get error always near ~2150 records (with less work fine).

Seems, like its using http protocol for communication and I should tune some params, can you please tell how to figure out this case?

Already tried increasing params like: 
```
- http_max_field_value_size 
- http_max_chunk_size 
```

but they dont help(

**Comment by oleg-savko** [comment]
Any suggestions @kssenii @rschu1ze  ?

**Comment by rschu1ze** [comment]
Yes, function `catboostEvaluate` communicates with the library bridge (which loads the catboost library) using HTTP (original PR: #39629).

Could you please include the callstack of the exception? (it should be printed into the server log)
As far as I read the code, a large enough value for setting `http_max_field_value_size` should fix the problem, but I would like to verify.

What would be even better (if the data is not sensitive) is if you could provide a little repro:
- the query you use to invoke `catboostEvaluate` and
- the table (or subset) with feature data which is send to catboost for evaluation.

Thanks a lot!

**Comment by oleg-savko** [comment]
@rschu1ze any new or suggestion?

ps: currently, like workaround, I emulate batches in my query using group by + arrays, and then it can be performed:
```
select 
      arrayMap((...) -> 
              catboostEvaluate(
                  '/etc/clickhouse-server/models/catboost_model_uplift.cbm',
                  ...
              ),
                  groupArray(feat_1),
                  ...
                  groupArray(feat_n)
              )                       as predictions,
      group_num
from score_dataset
group by group_num
```

**Comment by rschu1ze** [comment]
@hellais Thanks ... unfortunately the repro you provided on riseup is gone. Would you like to check why? (permission problem?). In the meantime I'll try to repro the issue by myself with some test data from CI.

**Comment by rschu1ze** [comment]
Fond a repro (tests/integration/test_catboost_evaluate/test.py, `testAmazonModelManyRows()`, insert many more than 7500 rows).

**Comment by rschu1ze** [comment]
The exception is generated on the library-bridge side and the server merely reports it. It looks like the library-bridge doesn't consider changed settings like `http_max_field_value_size`, it always uses the default setting values. Hard-coding `settings.http_max_field_value_size` in the code to `std::numeric_limits<size_t>::max()` enables catboost on bigger datasets (I tried up to 100k rows in my local experiment).

**Comment by rschu1ze** [comment]
I think the problem is somewhere in `IBridge::main()` which creates the `Context` (that holds the settings) for the library-bridge process.

```cpp
auto shared_context = Context::createShared();
auto context = Context::createGlobal(shared_context.get());
context->makeGlobalContext();
```

I suspect the code lacks some event notifier registration that updates the settings when the cfg file changes.

**Comment by rschu1ze** [comment]
After digging further, I understood that the library-bridge process is not supposed to read the server XML/YAML config (which makes sense if one considers that 99% of all settings contained in these files are server-specific). The library-bridge only accepts a bunch of cmd line arguments. When the server starts the library-bridge (after getting timeouts in pings), it reads its own config and passes library-bridge-specific settings to the cmd line.

So the fix will be to add a new cmd line argument for `http_max_field_value_size` (+ some related options) and pass a sufficiently large value.

**Comment by oleg-savko** [comment]
> After digging further, I understood that the library-bridge process is not supposed to read the server XML/YAML config (which makes sense if one considers that 99% of all settings contained in these files are server-specific). The library-bridge only accepts a bunch of cmd line arguments. When the server starts the library-bridge (after getting timeouts in pings), it reads its own config and passes library-bridge-specific settings to the cmd line.
> 
> So the fix will be to add a new cmd line argument for `http_max_field_value_size` (+ some related options) and pass a sufficiently large value.

any suggestion, when it can be done?

**Comment by rschu1ze** [comment]
You'd need #47616 ... the PR message has more details.
