### ISSUE TITLE
RBAC: Support GRANT wildcard for databases and tables 

### ISSUE THREAD

**Issue by e-mars** [ClickHouse/ClickHouse#47624]
**Use case**

For granting users or roles to a defined set databases and tables using a prefix when naming are used to delineate resources.
Useful so that automation in apps and scripts can create and grant privileges.

**Describe the solution you'd like**

Being able to issue a commands like:
```
GRANT SELECT ON db_example*.* TO my_role;
GRANT ALL ON db1.table_* TO my_user;
```
When new databases and tables are added with the pattern, the roles should automatically be applied.

**Describe alternatives you've considered**
explicit grants to each database or table in a set

**Comment by evillique** [comment]
Asterisks are not generally mingled with matches in ClickHouse. Maybe it is better to add separate databases and tables matches? For example:
```
GRANT SELECT ON DATABASES('db_example').TABLES('table_') TO my_role;
GRANT SELECT ON db_example.TABLES('table_') TO my_role;
GRANT SELECT ON DATABASES('db_example').table TO my_role;
```

cc: @alexey-milovidov

**Comment by DerekChia** [comment]
The [Merge table engine](https://clickhouse.com/docs/en/engines/table-engines/special/merge) allows the use of regular expression to match the table names in the specified DB or DBs. Would be good to have similar behavior for GRANT too

```
CREATE TABLE all_visitors (id UInt32) ENGINE=Merge(REGEXP('ABC_*'), 'visitors');
CREATE TABLE WatchLog as WatchLog_old ENGINE=Merge(currentDatabase(), '^WatchLog');
```

**Comment by sebw91** [comment]
This would be very useful for automating end-to-end tests that use clickhouse

**Comment by xiaom** [comment]
It will be quite useful in our use case as well. 

We have a data QA pipeline which queries against production tables daily (read-only access) and generates results in a `qa_` prefixed tables. This feature will make our operation easier.

**Comment by Vukiz** [comment]
We have dynamically created databases and it would be great to be able to set up access to these databases without the need for manual interaction.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/65311

**Comment by vitlibar** [comment]
@vitlibar closed by https://github.com/ClickHouse/ClickHouse/pull/65311?

Yes, the following syntax
```
GRANT SELECT ON db_example*.* TO my_role;
GRANT ALL ON db1.table_* TO my_user;
```
should work now.

**Comment by tobiaslins** [comment]
I just got tricked by the docs - can we please add a note that this is only available for future versions? <picture data-single-emoji=":thank-u:" title=":thank-u:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/thank-u/d8cfba149bdf5566.gif" alt=":thank-u:" align="absmiddle"></picture>

**Comment by seilerre** [comment]
Me too :) Great feature, but a "bit" misleading in the docs.

**Comment by roman-vynar** [comment]
Misleading docs telling about wildcard grants but nothing in the changelog. 
So it's not yet released? :)

**Comment by e-mars** [comment]
@justindeguzman could you please a take a look and update docs?

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/71167
