### ISSUE TITLE
What is Clickhouse MySQL Engine limitation for batch import csv?

### ISSUE THREAD

**Issue by derstiff** [ClickHouse/ClickHouse#47633]
I have some wiered issue with MySQL Engine. When importing csv file into the table, the whole process crushes with following error:

```
Code: 1000. DB::Exception: Received from xxx.xxx.xxx.xxx:9000. DB::Exception: mysqlxx::ConnectionLost: MySQL server has gone away (xxx.xxx.xxx.xxx:3306). (POCO_EXCEPTION)
```

Through trial and error, it was found out that if there are 13015 rows in csv, then the import to mysql passes without errors. If you add one more roiw - an error occurs. If I remove half of the characters of 13016 row - the import passes without errors.

Each line is ~298-310 characters long. The total number of characters in the file is 3806000.

I guess, the reason is that there is some kind of engine limitation or a bug, but I'm not sure.

Clickhouse version:

```
ClickHouse client version 22.5.1.2079 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.5.1 revision 54455.
```

Table is a regular table with MySQL engine:

```sql
-- auto-generated definition
CREATE TABLE sc.some_data
(
   Date Date,
   ...
)
   ENGINE = MySQL('xxx.xxx.xxx.xxx:3306', '...', '...', '...', '...');
```

Import:

```sh
clickhouse-client --host="xxx.xxx.xxx.xxx" -q "INSERT INTO sc.some_data FORMAT CSV" --max_execution_time=0 < "data.csv"
```

**Comment by davenger** [comment]
@derstiff looks like you might be seeing this issue https://github.com/ClickHouse/ClickHouse/issues/34168 and you might need to increase `read_write_timeout` setting.

**Comment by derstiff** [comment]
@davenger all timers are at max values - still getting the same error.

Temporary workaround is to split csv into smaller chunks:

```sh
split -l 500 --numeric-suffixes "$report_path" "$reports_dir/${uuid}.csv"
rm -f "$report_path"

for chunk_path in "$reports_dir/${uuid}.csv"*; do
   # importing...
done

```

**Comment by davenger** [comment]
@derstiff can you try to repro this problem on a newer version? 22.5 doesn't seem to have the fix. It was backported to the following versions: [v23.2.4.12-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.2.4.12-stable)  [v23.2.3.17-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.2.3.17-stable) [v23.2.2.20-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.2.2.20-stable) [v23.2.1.2537-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.2.1.2537-stable) [v23.1.5.24-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.1.5.24-stable) [v23.1.4.58-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.1.4.58-stable) [v23.1.3.5-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.1.3.5-stable) [v23.1.2.9-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.1.2.9-stable) [v23.1.1.3077-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.1.1.3077-stable) [v22.12.5.34-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.12.5.34-stable) [v22.12.4.76-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.12.4.76-stable) [v22.12.3.5-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.12.3.5-stable) [v22.12.2.25-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.12.2.25-stable) [v22.12.1.1752-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.12.1.1752-stable) [v22.11.6.44-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.11.6.44-stable) [v22.11.5.15-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.11.5.15-stable) [v22.11.4.3-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.11.4.3-stable) [v22.11.3.47-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.11.3.47-stable) [v22.11.2.30-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.11.2.30-stable) [v22.11.1.1360-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.11.1.1360-stable) [v22.10.7.13-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.10.7.13-stable) [v22.10.6.3-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.10.6.3-stable) [v22.10.5.54-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.10.5.54-stable) [v22.10.4.23-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.10.4.23-stable) [v22.10.3.27-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.10.3.27-stable) [v22.10.2.11-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.10.2.11-stable) [v22.10.1.1877-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.10.1.1877-stable) [v22.9.7.34-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.9.7.34-stable) [v22.9.6.20-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.9.6.20-stable) [v22.9.5.25-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.9.5.25-stable) [v22.9.4.32-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.9.4.32-stable) [v22.9.3.18-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.9.3.18-stable) [v22.9.2.7-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.9.2.7-stable) [v22.9.1.2603-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.9.1.2603-stable) [v22.3.19.6-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.3.19.6-lts) [v22.3.18.37-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.3.18.37-lts) [v22.3.17.13-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.3.17.13-lts) [v22.3.16.1190-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v22.3.16.1190-lts)

**Comment by derstiff** [comment]
Update to a higher version seems working.
