### ISSUE TITLE
SIGILL in gwp asan: Failed to deallocate in guarded pool allocator memory

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#47646]
https://s3.amazonaws.com/clickhouse-test-reports/0/1223b8959b4d075010bd66ca22f85f6d22bd15d2/stress_test__debug_.html

More failures: [link](https://play.clickhouse.com/play?user=play#d2l0aCAKJyVzaWclJyBhcyBuYW1lX3BhdHRlcm4sCiclZ3dwJScgYXMgY29udGV4dF9wYXR0ZXJuLAonMjAyMi0xMi0wMScgYXMgc3RhcnRfZGF0ZSwKKDQ1NDYxKSBhcyBub2lzeV9wcnMsCignU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBhcyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKc2VsZWN0IAp0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgYXMgZCwKY291bnQoKSwgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpLCBhbnkocmVwb3J0X3VybCkKZnJvbSBjaGVja3Mgd2hlcmUgc3RhcnRfZGF0ZSA8PSBjaGVja19zdGFydF90aW1lIGFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyIG5vdCBpbiAKKHNlbGVjdCBwdWxsX3JlcXVlc3RfbnVtYmVyIGFzIHBybiBmcm9tIGNoZWNrcyB3aGVyZSBwcm4hPTAgYW5kIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgY2hlY2tfbmFtZSBpbiBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpIAphbmQgdGVzdF9uYW1lIGlsaWtlIG5hbWVfcGF0dGVybiBhbmQgKHRlc3RfY29udGV4dF9yYXcgaWxpa2UgY29udGV4dF9wYXR0ZXJuKQphbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gbm9pc3lfcHJzCmFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knLCAnZmFpbHVyZScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj)

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/47916/eeb5a4c24138695e1b72977f4b29eb45d423f968/stress_test__debug_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/46c0c80bffcd126eeb4607587eeaa08bd747b8d5/stress_test__debug_.html

**Comment by tavplubix** [comment]
@hanfei1991, did you have time to take a look at this issue?

**Comment by hanfei1991** [comment]
@tavplubix I will look at it this week. But TBH, this problem is very confusing to me and hard to investigate because it only occures in debug mode. If I can't find out what is wrong this week, I think we'd better to disable it in debug mode.

**Comment by tavplubix** [comment]
Yes, that's strange. Maybe it's because we don't use jemalloc in builds with sanitizers, only in release and debug builds. But we don't have Stress tests with release builds. 

Also this may help: https://github.com/ClickHouse/ClickHouse/issues/37001

But it's okay to disable gwp-asan in debug builds in Stress tests
