### ISSUE TITLE
Is there any examples about StorageConfiguration and policies?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#47666]
I feel hard to get understood by documents about storage configuration and policies. But I am sure that the feature is wonderful and I want to use it. I found I can learn quickly by examples. So could you please give me some examples?

Thank you very much.

**Comment by den-crane** [comment]
https://altinity.com/blog/2019/11/29/amplifying-clickhouse-capacity-with-multi-volume-storage-part-2

**Comment by den-crane** [comment]
Or https://clickhouse.com/docs/en/integrations/s3#configure-clickhouse-to-use-the-s3-bucket-as-a-disk

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-multiple-volumes_configure

https://clickhouse.com/docs/en/integrations/gcs#storage_configuration--policies--gcs_main

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-moving-table-to-another-device./

**Comment by Alex-Cheng** [comment]
Thank you man.
