### ISSUE TITLE
Hints for HTTP handlers

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#47662]
**Use case**

A user can mistakenly write `dashboad` instead of `dashboard`.

**Describe the solution you'd like**

Provide hints for similar existing handlers, similar to how we are doing for function names in SQL.

**Comment by blazingbhavneek** [comment]
Hey there! 👋 I'm new to this repository and eager to contribute! 🌟 @alexey-milovidov Are you still working on this? Or can I give it a shot?

**Comment by alexey-milovidov** [comment]
@blazingbhavneek we are not currently working on this, and you can take it!
