### ISSUE TITLE
Clean column when there's no space

### ISSUE THREAD

**Issue by asurovenko-zeta** [ClickHouse/ClickHouse#47675]
Hello,

I have a huge table for few Tb, and on disk there's no extra space. I need to remove something to keep working, but when I trying to do 'alter table my_table clear column my_column in partition "202302"' then the mutation just hangs in the mutation table and nothing happens. I have about 90Gb free space and I believe to drop column I need some more temporary space to make that action.
What can I do in such situation?

Thanks

**Comment by den-crane** [comment]
provide 
```sql
select * from system.mutations where not is_done \G
```

**Comment by asurovenko-zeta** [comment]
default,my_table,mutation_16475834.txt,CLEAR COLUMN my_column IN PARTITION '202302',2023-03-17 14:42:29,[''],[16475834],"['202303_16<a lot partitions>75833_0']",160,0,"",1970-01-01 00:00:00,""

**Comment by den-crane** [comment]
It's not the vertical result: `\G`

It's seems like the mutation is not started by it's unclear without column names.
Check CH logs and system.merges / system.replication_queue
