### ISSUE TITLE
02346_full_text_search is flaky (suppressed)

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#47696]
Flaks in master
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMjM0Nl9mdWxsX3RleHRfc2VhcmNoJScgYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScpIGdyb3VwIGJ5IGQgb3JkZXIgYnkgZCBkZXNj

There was PR
https://github.com/ClickHouse/ClickHouse/pull/46279
and it did not help.

Some times it fails like this
https://s3.amazonaws.com/clickhouse-test-reports/0/e49c249f73f7c4c1f35df98f99d7f4cd83b108ec/stateless_tests__tsan__[3/3].html

some time like this `Cannot quickly remove directory`
https://s3.amazonaws.com/clickhouse-test-reports/0/05fae287297102eaa0ded2d17199b50bf3dc252d/stateless_tests__release__databaseordinary_.html
That error was also tried to be fixed , here https://github.com/ClickHouse/ClickHouse/pull/40151

**Comment by rschu1ze** [comment]
Fixed via #60466
