### ISSUE TITLE
code highlight is not visible with light mode

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#47698]
https://clickhouse.com/docs/en/integrations/gcs#storage_configuration--policies--gcs_main

**Comment by cangyin** [comment]
and side bar is scrolling with doc content, which make it inconvenient to go back for the menu when you read down far.

**Comment by rfraposa** [comment]
Highlighting was fixed - thank you for noticing this @den-crane 

The scrolling sidebar is on our "to do" list to fix (or feel free to submit a PR).
