### ISSUE TITLE
does SimpleAggregateFunction can support anyLast of array(Non_empty) datatype

### ISSUE THREAD

**Issue by bestpayAmes** [ClickHouse/ClickHouse#47706]
I have a wide table, the array columns are SimpleAggregateFunction(anyLast,Array(string)),but when insert one column,anther column will be setter [](empty);

**Comment by den-crane** [comment]
Provide an example of the input data and desired result.
Probably you need groupArrayArray , not anyLast.

**Comment by marising** [comment]
Using this array aggregation function `SimpleAggregateFunction(groupArrayLastArray,Array(Array(string)))` can meet your needs
