### ISSUE TITLE
[bug] greatCircleDistance results inconsistent with documentation

### ISSUE THREAD

**Issue by LemonLiTree** [ClickHouse/ClickHouse#47708]
greatCircleDistance results inconsistent with documentation
![image](https://user-images.githubusercontent.com/109049295/226107060-9432ddd1-4693-4338-bfb6-df5c8d33e320.png)

![image](https://user-images.githubusercontent.com/109049295/226107069-fd94e869-b78e-47d4-a1e9-520a4d6cc62b.png)

**Comment by den-crane** [comment]
The implementation of greatCircleDistance has been changed 3 years ago greatCircleDistance, but the example was not updated.

**Comment by alexey-milovidov** [comment]
Please update the documentation accordingly.
