### ISSUE TITLE
Environmental dataset from sensors.community

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#47711]
https://sensor.community/en/

It contains crowd-sourced data from temperature, pressure, humidity, noise, and air quality sensors across the world.
The license allows redistribution and even commercial use: https://opendatacommons.org/licenses/dbcl/1-0/
The rights to use the dataset for testing ClickHouse are also implied.

The database size is about 20 billion records - good for a test dataset for time series.

### Download the data

```
for i in {2015..2023}; do for j in {01..12}; do curl -sS "https://archive.sensor.community/csv_per_month/${i}-${j}/" | grep -o -P '>[^<]+\.zip<' | sed -r -e 's!>([^<]+\.zip)<!https://archive.sensor.community/csv_per_month/'${i}-${j}'/\1!'; done; done | tee files.txt

cat files.txt | xargs -L1 -P10 wget --continue
```

Fun fact: after I downloaded almost all the archive, it stopped being accessible: https://github.com/opendata-stuttgart/sensor.community/issues/223

I didn't abuse it, and I hope it will become available again. Nevertheless, the download, use, and redistribution are not only permitted but also welcomed by the license.

### Create a table

```
CREATE TABLE sensors
(
    sensor_id UInt16,
    sensor_type Enum('BME280', 'BMP180', 'BMP280', 'DHT22', 'DS18B20', 'HPM', 'HTU21D', 'PMS1003', 'PMS3003', 'PMS5003', 'PMS6003', 'PMS7003', 'PPD42NS', 'SDS011'),
    location UInt32,
    lat Float32,
    lon Float32,
    date Date DEFAULT toDate(timestamp),
    timestamp DateTime,
    P1 Float32,
    P2 Float32,
    P0 Float32,
    durP1 Float32,
    ratioP1 Float32,
    durP2 Float32,
    ratioP2 Float32,
    pressure Float32,
    altitude Float32,
    pressure_sealevel Float32,
    temperature Float32,
    humidity Float32
) ENGINE = MergeTree ORDER BY (timestamp, sensor_id);
```

### Unpack and insert the data

```
find . -name '*.zip' | xargs -P $(nproc) -I{} bash -c 'unzip -p "{}" | clickhouse-client --query "INSERT INTO sensors FORMAT CSVWithNames" --format_csv_delimiter ";" --date_time_input_format best_effort --input_format_allow_errors_ratio 0.5 --input_format_allow_errors_num 10000 --parts_to_throw_insert 10000; echo "{}"'
```

The data can sometimes be dirty. Skipping a few records is ok.
The table size is 309 GB.

### Test the inserted data

![Screenshot_20230319_013052](https://user-images.githubusercontent.com/18581488/226147414-0c1e74d7-e23f-4475-adac-ba1502b3b0d1.png)

**Comment by rfraposa** [comment]
I'll add it to the docs...except what about this?

> Fun fact: after I downloaded almost all the archive, it stopped being accessible: https://github.com/opendata-stuttgart/sensor.community/issues/223

Does that mean your `curl` command isn't working anymore?

**Comment by DanRoscigno** [comment]
@alexey-milovidov can you put the data in GCS or S3 please so we can use it without worrying about it being inaccessible form the source?

**Comment by alexey-milovidov** [comment]
Yes, it does not work anymore. I will copy the downloaded archive to s3, so it will not be lost.

**Comment by alexey-milovidov** [comment]
Hm, it's opened. I will try to download the remaining data.

**Comment by alexey-milovidov** [comment]
The data is downloaded. Moreover, the archive started to work considerably faster after downtime :)

**Comment by alexey-milovidov** [comment]
The data size is 389 GB in 919 files.

**Comment by alexey-milovidov** [comment]
`zst` files are 252 GB in total

**Comment by alexey-milovidov** [comment]
One file is damaged. Fix it:

```
zstd -c -d 2017-03_bme280.csv.zst | grep -v ';$' | zstd > 2017-03_bme280_1.csv.zst
rm 2017-03_bme280.csv.zst
```

**Comment by alexey-milovidov** [comment]
Inserting to a local server, option 1:
```
find . -name '*.zst' | xargs -P $(nproc) -I{} bash -c 'clickhouse-client --query "INSERT INTO sensors FROM INFILE '"'{}'"' FORMAT CSVWithNames" --format_csv_delimiter ";" --date_time_input_format best_effort --input_format_allow_errors_ratio 0.5 --input_format_allow_errors_num 10000 --parts_to_throw_insert 10000; echo "{}"'
```

**Comment by alexey-milovidov** [comment]
Upload to s3:
```
aws s3 cp --recursive --profile xyz . s3://clickhouse-public-datasets/sensors/monthly
```

**Comment by rfraposa** [comment]
Awesome - thanks! I will write up a new page in the "Example datasets"

**Comment by alexey-milovidov** [comment]
#48133

**Comment by alexey-milovidov** [comment]
The number of records in the table is 20 693 824 131.

**Comment by rfraposa** [comment]
Page is here: https://clickhouse.com/docs/en/getting-started/example-datasets/environmental-sensors

**Comment by alexey-milovidov** [comment]
@rfraposa 

> The 1.67T is compressed down to 1.30T, and there are 20.69 billion rows:

Here is a mistake.

**Comment by alexey-milovidov** [comment]
Overall great tutorial!

**Comment by alexey-milovidov** [comment]
Fixed: https://github.com/ClickHouse/ClickHouse/pull/48166
