### ISSUE TITLE
Setting use_structure_from_insertion_table_in_table_functions doesn't work properly with virtual columns.

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#47730]
**Describe what's wrong**
The setting `set use_structure_from_insertion_table_in_table_functions=1` doesn't work properly

setting:
```
set use_structure_from_insertion_table_in_table_functions=1;
insert into function file(data.LineAsString) select 'Hello';
```

table with the same column name:
```
create table test (_path String) engine=Memory;
insert into test select _path from file(data.LineAsString);

Received exception:
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_path String String(size = 0)
_path LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))). (AMBIGUOUS_COLUMN_NAME)
```
here error makes perfect sense, since virtual column `_path` is a LowCardinality(String) but table column is `String`, however, the cause of error shows that something wrong is going on here - apparently the columns matched by name and not by position which is stated in manual. And seemingly due to this we have some wrong behavior here:
```
insert into test select CAST(_path as String) from file(data.LineAsString);

Received exception:
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_path String String(size = 0)
_path LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))). (AMBIGUOUS_COLUMN_NAME)
```
and even more strange here:
```
drop table test;
create table test (_path LowCardinality(String)) engine=Memory;
insert into test select _path from file(data.LineAsString);

Received exception:
Code: 80. DB::Exception: This input format is only suitable for tables with a single column of type String.: While executing File. (INCORRECT_QUERY)
```
not sure about this one - probably this is because `file()` table function produce single `String` column, and virtual columns were not taken into account.

However for table with different than `_path` column name there is no issue:
```
drop table test;
create table test (aaa String) engine=Memory;
insert into test select _path from file(data.LineAsString);
```
but from code it's seems that in this case the setting `use_structure_from_insertion_table_in_table_functions` is ignored and CAST is added.

**Does it reproduce on recent release?**
reproduces on current master

**Comment by Avogar** [comment]
This is all is expected and not a problem with `use_structure_from_insertion_table_in_table_functions` setting. Using `use_structure_from_insertion_table_in_table_functions=1` means that we forcing ClickHosue to use structure from table in talbe function without any checks. So, if `use_structure_from_insertion_table_in_table_functions=1` these two queries are identical:
```
create table test (_path String) engine=Memory;
insert into test select _path from file(data.LineAsString);
```
```
create table test (_path String) engine=Memory;
insert into test select _path from file(data.LineAsString, auto, '_path String');
```
And the second query will procude the same error (it doesn't depend on `use_structure_from_insertion_table_in_table_functions` setting).

For these cases we have `use_structure_from_insertion_table_in_table_functions=2 (auto)` when structure from insertion table is ignored when query contains virtual columns.

**Comment by Avogar** [comment]
So, it's the same as:
```
avogar-dev :) select _path from file(data.LineAsString, auto, '_path LowCardinality(String)');

SELECT _path
FROM file(data.LineAsString, auto, '_path LowCardinality(String)')

Query id: be742aac-f670-4f8f-9203-63c95b36850e


0 rows in set. Elapsed: 0.010 sec.

Received exception:
Code: 80. DB::Exception: This input format is only suitable for tables with a single column of type String.: While executing ParallelParsingBlockInputFormat: While executing File. (INCORRECT_QUERY)

avogar-dev :) select _path from file(data.LineAsString, auto, '_path String')

SELECT _path
FROM file(data.LineAsString, auto, '_path String')

Query id: aa80686f-7ec2-4bc0-8040-9562f1ef5025


0 rows in set. Elapsed: 0.006 sec.

Received exception:
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_path String String(size = 0)
_path LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))). (AMBIGUOUS_COLUMN_NAME)

avogar-dev :) select CAST(_path as String)  from file(data.LineAsString, auto, '_path String')

SELECT CAST(_path, 'String')
FROM file(data.LineAsString, auto, '_path String')

Query id: b938be3c-b126-4603-9291-3a1bf5cfd61d


0 rows in set. Elapsed: 0.006 sec.

Received exception:
Code: 352. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
_path String String(size = 0)
_path LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))). (AMBIGUOUS_COLUMN_NAME)

```

**Comment by yakov-olkhovskiy** [comment]
...though we still have a strange case when name in the insertion table is not matching with select name and it works, while for matching names it doesn't with exception 352. But it also is not dependent on `use_structure_from_insertion_table_in_table_functions` setting. Apparently the error 352 is indicative of using name matching instead of position.

**Comment by Avogar** [comment]
For `file` table engine (and I guess for `s3/url/hdfs`) it makes sense to not use virtual columns and don't add them to block when structure contains column with same name.

**Comment by Avogar** [comment]
> We specifically state in docs that matching is by position and imply that using same names is ok:

But here we don't have any problems with `insert ... select ...`, all these 356 errors are from select part of a query. And it happens because in `StorageFile` we add column `_path LowCardinality(String)` when we have `_path` column in select statement (it can alsow be inside any functions):
https://github.com/ClickHouse/ClickHouse/blob/cb0065fba2366e30b1479857cc5566233635dfd8/src/Storages/StorageFile.cpp#L724-L730

So, we just don't check if we already have column `_path` in the block:
https://github.com/ClickHouse/ClickHouse/blob/cb0065fba2366e30b1479857cc5566233635dfd8/src/Storages/StorageFile.cpp#L529-L547
