### ISSUE TITLE
DB::Exception: Database engine MaterializedPostgreSQL cannot have arguments (version 21.4.3.21 (official build))

### ISSUE THREAD

**Issue by fideism** [ClickHouse/ClickHouse#47741]
CREATE DATABASE database_a
ENGINE = MaterializedPostgreSQL('127.0.1.0:5432', 'database', 'admin', '123456')
SETTINGS materialized_postgresql_schema_list = 'schema_a';

- 21.4.3.21

**Comment by tavplubix** [comment]
> 21.4.3.21

This version is obsolete, you should upgrade.
