### ISSUE TITLE
Validate query in clickhouse

### ISSUE THREAD

**Issue by vinith-reddy25** [ClickHouse/ClickHouse#47742]
I want to validate query in clickhouse. I have an sql query which is running in other DBs, but when I ran same query in clickhouse, it is failing. For example, 

**select tt.productname from test.testing as TT*

It will fail in clickhouse as "TT" is case sensitivity. I want to validate the sql query without creating table and database. How to validate the query without creating table?

**Comment by Alex-Cheng** [comment]
You could use `EXPLAIN` for the purpose, for example
```SQL
SELECT * FROM  db1.not_exist_table;
```

**Comment by den-crane** [comment]
You cannot validate it general without a database and a table.

It's valid query. BTW.

```
select tt.productname from test.testing as TT;

SELECT tt.productname
FROM test.testing AS TT

Query id: ad886239-649c-4431-88b1-d92bd7272b12

Ok.

0 rows in set. Elapsed: 0.016 sec.
```

**Comment by den-crane** [comment]
Also valid for example

```
select from from from;

SELECT from
FROM from

Query id: 689bd7d6-5a17-4df8-9b9f-5625f8066c0c

Ok.

0 rows in set. Elapsed: 0.002 sec.
```

**Comment by den-crane** [comment]
But it is valid query

see: 

```
clickhouse :) select tt.productname from test.testing as TT;

SELECT tt.productname
FROM test.testing AS TT

Query id: ad886239-649c-4431-88b1-d92bd7272b12

Ok.

0 rows in set. Elapsed: 0.016 sec.
```

**Comment by vinith-reddy25** [comment]
> But it is valid query

Which clickhouse version you are using?

**Comment by den-crane** [comment]
> > But it is valid query
> 
> Which clickhouse version you are using?

ANY. `tt.productname` is the name of a column. That's why: "You cannot validate it in general without a database and a table."

```
create table  test.testing (`tt.productname` String) Engine=Memory;

select tt.productname from test.testing as TT
```
