### ISSUE TITLE
clickhouse install: `--link` and `--noninteractive` (`-y`) options

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#47750]
**Use case**

`--noninteractive` or `-y` for headless installations - don't ask questions.

`--link` - create a symlink to the binary instead of copying it to `/usr/bin/` - it is useful when `/usr/bin/` is located on a slow volume, while there is a fast volume.

**Comment by ningObito** [comment]
@alexey-milovidov  install clickhouse from rpm package,  no entry to set -y or --noninteractive ?
