### ISSUE TITLE
insert from INFILE large than 4G causes "inflateReset failed: buffer error"

### ISSUE THREAD

**Issue by farlearn** [ClickHouse/ClickHouse#47756]
I recently found that when insert from **large gzip file (>4G)**, clickhouse will throw error like this:
`Code: 354. DB::Exception: inflateReset failed: buffer error: While executing ParallelParsingBlockInputFormat: While executing File: data for INSERT was parsed from file: (in query: insert into RAW from INFILE '20190805.csv.gz' FORMAT CSVWithNames). (ZLIB_INFLATE_FAILED)`

This happens as long as the gzip file is larger than 4GB.

Here is my command, I run the sql from ch client:
`clickhouse-client --host="127.0.0.1" --port="9000" --user="" --password="" --database="" --query="insert into RAW from INFILE '20190805.csv.gz' FORMAT CSVWithNames"`

FYI, my env version:
_Red Hat 4.8.5-39
ClickHouse server version 23.2.3.17 (official build).
ClickHouse client version 23.2.3.17 (official build).
gzip 1.5_

**Comment by CurtizJ** [comment]
Looks like it was introduces in #43927. Please, try to run query with setting `storage_file_read_method='pread'`

**Comment by farlearn** [comment]
> Looks like it was introduced in #43927. Please, try to run query with setting `storage_file_read_method='pread'`

Has this bug been fixed?
