### ISSUE TITLE
In many places, the description turned black and I couldn't see it

### ISSUE THREAD

**Issue by iammagicc** [ClickHouse/ClickHouse#47763]
This is the website:https://clickhouse.com/docs/zh/guides/best-practices
You should fix the relevant page tags.

**Comment by serxa** [comment]
@DanRoscigno I can see this problem in other places in docs as well:
https://clickhouse.com/docs/en/optimize/sparse-primary-indexes
Look like the font color is wrong for the text hidden under "triangle" in Dark Mode:
<img width="398" alt="Screenshot 2023-03-21 at 00 08 23" src="https://user-images.githubusercontent.com/1014716/226485302-a0ba8089-1263-426c-a02f-55b038033eeb.png">

**Comment by iammagicc** [comment]
Yes,It's uncomfortable
![image](https://user-images.githubusercontent.com/69392179/226512368-8e696f0c-77e7-416f-ab45-4c40467975ea.png)
![image](https://user-images.githubusercontent.com/69392179/226512421-1d790293-923e-41b6-ae5d-10f9e415f550.png)

**Comment by ucasfl** [comment]
https://github.com/ClickHouse/clickhouse-docs/pull/917 fixed it?

**Comment by rfraposa** [comment]
It appears to be an issue with the article on sparse primary indexes, which contained a ton of custom HTML tags. This should fix it: https://github.com/ClickHouse/clickhouse-docs/pull/918

**Comment by iammagicc** [comment]
https://clickhouse.com/docs/zh/guides/best-practices
This is a Chinese online document,maybe need a know Chinese people to fix it?

**Comment by iammagicc** [comment]
https://clickhouse.com/docs/zh/guides/best-practices
This is a Chinese online document, maybe someone who knows Chinese needs to fix it?

**Comment by rfraposa** [comment]
@iammagicc - I think it's working now. It just took a while for the changes to appear live in the docs.

**Comment by iammagicc** [comment]
Thanks.Most of the page is fixed, with only a few blemishes. It's that the picture still doesn't show the background.In the middle part of the web page, now it looks like this.
![image](https://user-images.githubusercontent.com/69392179/226777264-973161ff-3763-45a0-b363-25f2fc09ef38.png)

![image](https://user-images.githubusercontent.com/69392179/226777106-85ef63d5-5f22-4ee9-8e1b-615f0900f8e0.png)

**Comment by iammagicc** [comment]
Thanks.Most of the page is fixed, with only a few blemishes. It's that the picture still doesn't show the background.In the middle part of the web page, now it looks like this.
![image](https://user-images.githubusercontent.com/69392179/226777400-f3a711c0-27ba-4eb8-840e-67803b14d2a4.png)

It should be like this.
![image](https://user-images.githubusercontent.com/69392179/226777428-627ce107-7911-4280-895a-3ccf1fd29c95.png)

**Comment by rfraposa** [comment]
Just FYI: I can't "recreate" this issue - the images all look good for me. If it's still broken, let's create a new GH issue

**Comment by iammagicc** [comment]
Don't bother you, now it can barely be read, without much impact
