### ISSUE TITLE
Configuring parameters of `tokenbf_v1`

### ISSUE THREAD

**Issue by awitten1** [ClickHouse/ClickHouse#47788]
I have a question on settings parameters for the `tokenbf_v1` data skipping index.  This index requires parameters for the size of the filter (in bytes), the number of hash functions, and the seed of the hash functions.  

In order to compute optimal values for the bloom filter size, and the number of hash functions, I need to know the number of values being stored (see the calculator [here](https://hur.st/bloomfilter/)).  

I have been approximating this value with the quantity: `index_granularity * GRANULARITY * average words in string field`.

Does this seem like a good starting point for tuning this index?

**Comment by serxa** [comment]
Yes, this is the right formula. `tokenbf_v1` creates a separate bloom filter for every `GRANULARITY` granules. Each granule contains `index_granularity` rows. So the size of the filter equals the number of words in `index_granularity * GRANULARITY` rows. Note that by default tables have adaptive index granularity.

P.S. You might be also interested in new experimental [inverted indexes](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/invertedindexes) for full-text search.

**Comment by den-crane** [comment]
see https://altinity.com/blog/skipping-indices-part-2-bloom-filters

**Comment by rschu1ze** [comment]
Just to add: to compute the number of tokens per `index_granularity * GRANULARITY` rows, you can use SQL function `tokens()` ([docs](https://clickhouse.com/docs/en/sql-reference/functions/splitting-merging-functions#tokens)). It will be impractical to calculate this value per granule but you can do it for the entire column and break it down to an average number of tokens per granule.
