### ISSUE TITLE
S3 disk: poor usability in configuration

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#47809]
**Describe the issue**

```
endpoint: 'https://shared-merge-tree.s3.eu-central-1.amazonaws.com/'
```
> No key in S3 uri

```
endpoint: 'https://shared-merge-tree.s3.eu-central-1.amazonaws.com/t'
```
> S3 path must ends with '/'

**What to do**

Allow using it from the root, and append `/` automatically if needed.

**Comment by dgeorgi** [comment]
Can I give this task a shot?

**Comment by mkmkme** [comment]
I'd like to work on this one.

**Comment by xiaolei565** [comment]
take

**Comment by xiaolei565** [comment]
> @xiaolei565 thanks for your effort, but please next time check if the issue had been already taken. I was working on this.

sorry，i have close this PR

**Comment by mkmkme** [comment]
@xiaolei565 no need to closing this :) I think your code is good for this effort. And after all, you've already spent your time on this :)

**Comment by xiaolei565** [comment]
@mkmkme I'm so sorry, I didn't realize this problem before. If you have already developed it, I won't reopen PR anymore.If you haven't developed it yet and are willing to give me this chance, I will reopen this PR, thanks🤝

**Comment by mkmkme** [comment]
@xiaolei565 No problem, really! I don't have any code to push related to this task, so far I've been only reviewing the parts of it to see how to approach the problem.
So please, feel free to re-open your pull request! 🙂

**Comment by xiaolei565** [comment]
@mkmkme thanks 😊

**Comment by alexey-milovidov** [comment]
Three people volunteered, but no one did it. This task is open.

**Comment by mkmkme** [comment]
@alexey-milovidov didn't https://github.com/ClickHouse/ClickHouse/pull/52600 fix it?

**Comment by alexey-milovidov** [comment]
Thank you! We forgot to close.
