### ISSUE TITLE
hdfs & cache -> wrong data/results

### ISSUE THREAD

**Issue by lksv** [ClickHouse/ClickHouse#47836]
A have enabled HDFS cache as bellow. It seems working, but sometimes queries do not work with all the data. For example, `SELECT toStartOfHour(toDateTime64(Timestamp / 1000000, 6, 'Europe/Prague')) AS h, count() FROM hive.streaming_click_clean_logs WHERE (year = 2023) AND (month = 3) AND (day = 20) GROUP BY h ORDER BY h ASC` returns data up to 5 p.m. of that day. When I disable the cache (by changing `<enable>true</enable>` to `<enable>false</enable>` I see all the data correctly.

I would like to ask for update documentation as well.

By the https://clickhouse.com/docs/en/engines/table-engines/integrations/hive#how-to-use-local-cache-for-hdfs-filesystem it is possible to use `settings use_local_cache_for_remote_fs = 0` to disable cache. But this settings do not exists any more? I tried:

* `use_local_cache_for_remote_storage`,
* `SHOW FILESYSTEM CACHES` (and `SYSTEM DROP FILESYSTEM CACHE`)

but it seems not working for this type of case. Does this `<local_cache_for_remote_fs>` is somehow old way how to configure cache for HDFS? If so, how can I use `<storage_configuration>`?

```xml
  <local_cache_for_remote_fs>
        <enable>true</enable>
        <root_dir>/var/lib/clickhouse/local_cache</root_dir>
        <limit_size>1000559096952</limit_size>
        <bytes_read_before_flush>1048576</bytes_read_before_flush>
  </local_cache_for_remote_fs>
```

Table definition:
```
CREATE TABLE hive.streaming_click_clean_logs
(
    `Timestamp` Nullable(Int64),
    ...
    `year` UInt32,
    `month` UInt32,
    `day` UInt32
)
ENGINE = Hive('thrift://our-hive-addr:9083', 'default', 'streaming_click_clean_logs')
PARTITION BY (year, month, day)
ORDER BY timestamp
SETTINGS input_format_parquet_import_nested = 1
```

**How to reproduce**
Unfortunately, do not know how to reproduce. 

**Error message and/or stacktrace**
There are no error messages in log connected with this issue.

**Comment by lksv** [comment]
Version: 23.2.2.20 (ubuntu deb).

As I wrote above, I cannot reproduce it. When it happens It is consistent until I disable cache.

**Comment by den-crane** [comment]
As I understand you use Parquet?
How are your files structured? Folders / filenames ? Do you use partitioning by folder names?
Check which files are processed with and without the cache using `select ...,_file` virtual column.

**Comment by lksv** [comment]
Yes, it's Parquet files.

Particulary, the table is created by following DDL. I hope that this answers the question about folder structure:

```sql
            CREATE TABLE IF NOT EXISTS hive.streaming_click_clean_logs
            ENGINE = Hive('thrift://xxxx:9083', 'default', 'streaming_click_clean_logs')
            PARTITION BY (year, month, day)
            ORDER BY timestamp SETTINGS  input_format_parquet_import_nested = 1
            EMPTY AS
            SELECT
                *,
                CAST('0', 'UInt32') AS year,
                CAST('0', 'UInt32') AS month,
                CAST('0', 'UInt32') AS day
            FROM hdfs('hdfs://xxxx/warehouse/streaming_click_clean_logs/year=2023/month=3/day=20/*.parquet')
            SETTINGS input_format_parquet_import_nested=1, input_format_max_rows_to_read_for_schema_inference = 1000000
```

Example of filenames (directory `hdfs://xxxx/warehouse/streaming_click_clean_logs/year=2023/month=3/day=20/*.parquet`):
* `streaming.click.clean_log-2023-03-21-13-30-CET-2023-03-21-14-00-CET-0.parquet`
* `streaming.click.clean_log-2023-03-21-13-00-CET-2023-03-21-13-30-CET-0.parquet`

Each file contains data for particular hour.

Currently I am experiencing the bug again. It looks, that clickhouse does not process any new files (or maybe do not know about updates in files) after particular time.

```
SELECT
    toStartOfHour(toDateTime64(Timestamp / 1000000, 6, 'Europe/Prague')) AS h,
    _file,
    count()
FROM hive.streaming_click_clean_logs
WHERE (year = 2023) AND (month = 3) AND (day = 21)
GROUP BY
    h,
    _file
ORDER BY h DESC
LIMIT 10

Query id: 5d4f495e-96c7-4386-97f7-d51856ebe8c0

│ 2023-03-21 12:00:00 │ streaming.click.clean_log-2023-03-21-12-30-CET-2023-03-21-13-00-CET-0.parquet │   56483 │
│ 2023-03-21 12:00:00 │ streaming.click.clean_log-2023-03-21-12-00-CET-2023-03-21-12-30-CET-0.parquet │   54620 │
│ 2023-03-21 11:00:00 │ streaming.click.clean_log-2023-03-21-11-00-CET-2023-03-21-11-30-CET-0.parquet │   53581 │
│ 2023-03-21 11:00:00 │ streaming.click.clean_log-2023-03-21-11-30-CET-2023-03-21-12-00-CET-0.parquet │   53622 │
│ 2023-03-21 10:00:00 │ streaming.click.clean_log-2023-03-21-10-30-CET-2023-03-21-11-00-CET-0.parquet │   53617 │
│ 2023-03-21 10:00:00 │ streaming.click.clean_log-2023-03-21-10-00-CET-2023-03-21-10-30-CET-0.parquet │   52864 │
│ 2023-03-21 09:00:00 │ streaming.click.clean_log-2023-03-21-09-30-CET-2023-03-21-10-00-CET-0.parquet │   53332 │
```

**Comment by lksv** [comment]
UPDATE: When I restart the server, clickhouse see all the data. So maybe it is not connected to filesystem cache?

**Comment by lksv** [comment]
@den-crane I found out, that it's easily reproducible:

* To HDFS comes continuously new data, partitioning by path /year=*/month=*/day=*/files*.parquet  (e.g. each hour new file)
* When I asks for latest data, then current state for current day is cached and no new data is answered any more for this day.
* Next day the new data is accessible (with the same cache problem) but the cache problem keeps.
* restart helps.

It seems to be as critical issue: It is not possible use queries for current day data (and setup clickhouse daily restart is needed for older data).

**Comment by lksv** [comment]
Unfortunately, the workaround mentioned in #55204 does not work.

I tried the following:

* Dropping the system FILESYSTEM cache
* SELECT ... SETTINGS use_local_cache_for_remote_storage = 0. (btw, in the [doc](https://clickhouse.com/docs/en/engines/table-engines/integrations/hive#usage-example) the settings `use_local_cache_for_remote_fs` but it does not exists any more)

However, these steps were unsuccessful. Currently, the only workaround I am aware of is restarting the server.

**Comment by alexey-milovidov** [comment]
Hadoop is not supported.
