### ISSUE TITLE
New murmur2 function (use Kafka DefaultPartitioner seed value)

### ISSUE THREAD

**Issue by dbug-river** [ClickHouse/ClickHouse#47834]
As we are consuming from Kafka using the DefaultPartitioner as the partition strategy and writing into an `all-sharded` cluster, it would be a good idea to have the murmur2 function that is implement by Kafka using the specific seed value so that we could implement a `Distributed Table` with such a hashing functionality and query for the specific key directly on the resolving cluster node.

Seed information can be found here: https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/utils/Utils.java#L480
```
    @SuppressWarnings("fallthrough")
    public static int murmur2(final byte[] data) {
        int length = data.length;
        int seed = 0x9747b28c;
        // 'm' and 'r' are mixing constants generated offline.
        // They're not really 'magic', they just happen to work well.
        final int m = 0x5bd1e995;
        final int r = 24;
```

**Comment by nickitat** [comment]
> I wonder if it'd make sense to have parametric functions (not [parametric aggregate functions](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/parametric-functions)) for this case

when all parameters are compile constants performance should be better. on the other hand there shouldn't be many other widely used variants of murmur hash )
