### ISSUE TITLE
Allocator class can have different size depending on NDEBUG value

### ISSUE THREAD

**Issue by halayli** [ClickHouse/ClickHouse#4784]
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/Allocator.h#L30

While it's not a bug per se, having a class size dependent on NDEBUG can be problematic for anyone linking to clickhouse or within clickhouse source code if a module needs to explicitly disable/ignore the flag.

**Comment by alexey-milovidov** [comment]
I understand the issue. It can be solved by inserting a padding variable `char pad[sizeof(pcg64)]` but I think, we should not do it because it will increase the size of many objects, including PODArray. And there are many cases when sizeof PODArray is critical (e.g. aggregate function states).

**Comment by alexey-milovidov** [comment]
It can be solved by wrapping https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/Allocator.h#L5 into `#ifndef ALLOCATOR_ASLR` and explicitly defining ALLOCATOR_ASLR to 0 in your code that use ClickHouse headers.

**Comment by alexey-milovidov** [comment]
You can send the required modifications in a PR.
