### ISSUE TITLE
Functional tests for async inserts are flaky

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#47866]
02015_async_inserts_5 - https://s3.amazonaws.com/clickhouse-test-reports/0/5add1e1b2e9439abe7fe2ed0052ef91cf9c2ad54/stateless_tests__tsan__[3/3].html
02015_async_inserts_1 - https://s3.amazonaws.com/clickhouse-test-reports/0/00c05f7f8b8f11bcb9c11e54c9bec6b77932933f/stateless_tests__tsan__[3/3].html
02481_async_insert_race_long - https://s3.amazonaws.com/clickhouse-test-reports/47770/1073c7f3c942949d1f5de6956fab9b3bcde8b34b/stateless_tests__debug__s3_storage__[6/6].html
02187_async_inserts_all_formats - https://s3.amazonaws.com/clickhouse-test-reports/46085/886b5309632eb2b2d9b2d5122b1a492bbdf82e09/stateless_tests__tsan__[2/5].html 

See CI DB: [link](https://play.clickhouse.com/play?user=play#d2l0aCAKJzAlYXN5bmNfaW5zZXJ0JScgYXMgbmFtZV9wYXR0ZXJuLAonJSUnIGFzIGNvbnRleHRfcGF0dGVybiwKJzIwMjItMTItMDEnIGFzIHN0YXJ0X2RhdGUsCig0NTQ2MSkgYXMgbm9pc3lfcHJzLAooJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgYXMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzCnNlbGVjdCAKdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgZ3JvdXBVbmlxQXJyYXkodGVzdF9uYW1lKSwgYW55KHJlcG9ydF91cmwpCmZyb20gY2hlY2tzIHdoZXJlIHN0YXJ0X2RhdGUgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgcHVsbF9yZXF1ZXN0X251bWJlciBub3QgaW4gCihzZWxlY3QgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm4gZnJvbSBjaGVja3Mgd2hlcmUgcHJuIT0wIGFuZCBzdGFydF9kYXRlIDw9IGNoZWNrX3N0YXJ0X3RpbWUgYW5kIGNoZWNrX25hbWUgaW4gYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSAKYW5kIHRlc3RfbmFtZSBsaWtlIG5hbWVfcGF0dGVybiBhbmQgdGVzdF9jb250ZXh0X3JhdyBpbGlrZSBjb250ZXh0X3BhdHRlcm4gYW5kIHRlc3RfY29udGV4dF9yYXcgbm90IGxpa2UgJyVDYW5ub3RTZW5kUmVxdWVzdCUnCmFuZCBwdWxsX3JlcXVlc3RfbnVtYmVyIG5vdCBpbiBub2lzeV9wcnMKYW5kIHRlc3Rfc3RhdHVzIGluICgnRkFJTCcsICdGTEFLWScsICdmYWlsdXJlJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=)

**Comment by tavplubix** [comment]
Still flaky:
https://s3.amazonaws.com/clickhouse-test-reports/0/828cee6b8109ac404bd2d63df6681680ca661ac0/stateless_tests__tsan__[3/3].html
https://s3.amazonaws.com/clickhouse-test-reports/0/a307e0d95db7afcf8df13870456d8fc624308081/stateless_tests__tsan__[3/3].html

**Comment by KochetovNicolai** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/5d26b0cf7c16a996054e837e29593ebdabe7e20d/stateless_tests__asan__[2_4].html

**Comment by KochetovNicolai** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/50720760825e76a964c95aa4ba377c4ab147d0f5/stateless_tests__debug__[3_5].html

**Comment by alexey-milovidov** [comment]
| check_start_time | check_name | test_name | report_url |
|-:|:-|:-|:-|
| 2024-02-23 16:19:22 | Stateless tests (ubsan) [1/2] | 02810_async_insert_dedup_replicated_collapsing | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__ubsan__[1_2].html |
| 2024-02-23 16:19:22 | Stateless tests (ubsan) [1/2] | 02134_async_inserts_formats | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__ubsan__[1_2].html |
| 2024-02-23 16:19:22 | Stateless tests (ubsan) [1/2] | 02015_async_inserts_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__ubsan__[1_2].html |
| 2024-02-23 16:19:22 | Stateless tests (ubsan) [1/2] | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__ubsan__[1_2].html |
| 2024-02-23 16:21:27 | Stateless tests (asan) [1/4] | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__asan__[1_4].html |
| 2024-02-23 16:21:30 | Stateless tests (asan) [2/4] | 02884_async_insert_native_protocol_2 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__asan__[2_4].html |
| 2024-02-23 16:26:38 | Stateless tests (tsan) [5/5] | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__tsan__[5_5].html |
| 2024-02-23 16:35:56 | Stateless tests (debug) [2/5] | 02884_async_insert_native_protocol_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__debug__[2_5].html |
| 2024-02-23 16:41:35 | Stateless tests (msan) [3/6] | 02015_async_inserts_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__msan__[3_6].html |
| 2024-02-23 16:41:35 | Stateless tests (msan) [3/6] | 02884_async_insert_native_protocol_3 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__msan__[3_6].html |
| 2024-02-23 16:41:37 | Stateless tests (msan) [5/6] | 02810_async_insert_dedup_replicated_collapsing | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__msan__[5_6].html |
| 2024-02-23 16:41:52 | Stateless tests (msan) [4/6] | 02726_async_insert_flush_stress | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__msan__[4_6].html |
| 2024-02-23 16:51:36 | Stateless tests (release) | 02884_async_insert_native_protocol_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release_.html |
| 2024-02-23 16:51:36 | Stateless tests (release) | 02884_async_insert_native_protocol_2 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release_.html |
| 2024-02-23 16:51:36 | Stateless tests (release) | 02714_async_inserts_empty_data | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release_.html |
| 2024-02-23 16:51:36 | Stateless tests (release) | 02884_async_insert_native_protocol_3 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release_.html |
| 2024-02-23 16:51:36 | Stateless tests (release) | 02884_async_insert_native_protocol_1 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release_.html |
| 2024-02-23 16:51:36 | Stateless tests (release) | 02726_async_insert_flush_stress | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release_.html |
| 2024-02-23 16:53:16 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [2/4] | 02725_async_insert_table_setting | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release__analyzer__s3__databasereplicated__[2_4].html |
| 2024-02-23 16:53:16 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [2/4] | 02156_async_insert_query_log | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release__analyzer__s3__databasereplicated__[2_4].html |
| 2024-02-23 16:53:16 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [1/4] | 02421_type_json_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release__analyzer__s3__databasereplicated__[1_4].html |
| 2024-02-23 16:53:16 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [1/4] | 02884_async_insert_native_protocol_3 | https://s3.amazonaws.com/clickhouse-test-reports/0/7ea44f95e3a402f93f6e4e6267feac0131d172d5/stateless_tests__release__analyzer__s3__databasereplicated__[1_4].html |
| 2024-02-23 17:42:07 | Stateless tests (aarch64) | 02714_async_inserts_empty_data | https://s3.amazonaws.com/clickhouse-test-reports/0/f70d4d9372e02790c7c585a41862b70efc0b6fd4/stateless_tests__aarch64_.html |
| 2024-02-23 17:42:07 | Stateless tests (aarch64) | 02726_async_insert_flush_stress | https://s3.amazonaws.com/clickhouse-test-reports/0/f70d4d9372e02790c7c585a41862b70efc0b6fd4/stateless_tests__aarch64_.html |
| 2024-02-23 18:21:12 | Stateless tests (release, analyzer) | 02884_async_insert_native_protocol_2 | https://s3.amazonaws.com/clickhouse-test-reports/0/57306706b31a5a383bcf3df71aefdee1b826dd06/stateless_tests__release__analyzer_.html |
| 2024-02-23 18:21:12 | Stateless tests (release, analyzer) | 02884_async_insert_native_protocol_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/57306706b31a5a383bcf3df71aefdee1b826dd06/stateless_tests__release__analyzer_.html |
| 2024-02-23 18:21:12 | Stateless tests (release, analyzer) | 02193_async_insert_tcp_client_1 | https://s3.amazonaws.com/clickhouse-test-reports/0/57306706b31a5a383bcf3df71aefdee1b826dd06/stateless_tests__release__analyzer_.html |
| 2024-02-23 18:21:12 | Stateless tests (release, analyzer) | 02134_async_inserts_formats | https://s3.amazonaws.com/clickhouse-test-reports/0/57306706b31a5a383bcf3df71aefdee1b826dd06/stateless_tests__release__analyzer_.html |
| 2024-02-23 18:21:12 | Stateless tests (release, analyzer) | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/57306706b31a5a383bcf3df71aefdee1b826dd06/stateless_tests__release__analyzer_.html |
| 2024-02-23 18:30:21 | Stateless tests (asan) [1/4] | 02421_type_json_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__asan__[1_4].html |
| 2024-02-23 18:30:21 | Stateless tests (asan) [1/4] | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__asan__[1_4].html |
| 2024-02-23 18:30:28 | Stateless tests (asan) [2/4] | 02193_async_insert_tcp_client_1 | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__asan__[2_4].html |
| 2024-02-23 18:30:50 | Stateless tests (asan) [3/4] | 02134_async_inserts_formats | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__asan__[3_4].html |
| 2024-02-23 18:32:23 | Stateless tests (ubsan) [1/2] | 02456_async_inserts_logs | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__ubsan__[1_2].html |
| 2024-02-23 18:32:24 | Stateless tests (ubsan) [2/2] | 02884_async_insert_native_protocol_2 | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__ubsan__[2_2].html |
| 2024-02-23 18:34:25 | Stateless tests (msan) [1/6] | 02570_fallback_from_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__msan__[1_6].html |
| 2024-02-23 18:36:22 | Stateless tests (msan) [5/6] | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__msan__[5_6].html |
| 2024-02-23 18:38:22 | Stateless tests (tsan) [3/5] | 02714_async_inserts_empty_data | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__tsan__[3_5].html |
| 2024-02-23 18:38:22 | Stateless tests (tsan) [3/5] | 02570_fallback_from_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__tsan__[3_5].html |
| 2024-02-23 18:38:22 | Stateless tests (tsan) [3/5] | 02456_async_inserts_logs | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__tsan__[3_5].html |
| 2024-02-23 18:40:25 | Stateless tests (tsan) [5/5] | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__tsan__[5_5].html |
| 2024-02-23 18:43:58 | Stateless tests (debug) [1/5] | 02884_async_insert_native_protocol_2 | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__debug__[1_5].html |
| 2024-02-23 18:44:26 | Stateless tests (debug) [3/5] | 02810_async_insert_dedup_replicated_collapsing | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__debug__[3_5].html |
| 2024-02-23 19:00:42 | Stateless tests (ubsan) [1/2] | 02570_fallback_from_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__ubsan__[1_2].html |
| 2024-02-23 19:00:45 | Stateless tests (ubsan) [2/2] | 02726_async_insert_flush_stress | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__ubsan__[2_2].html |
| 2024-02-23 19:08:34 | Stateless tests (msan) [1/6] | 02456_async_inserts_logs | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__msan__[1_6].html |
| 2024-02-23 19:09:23 | Stateless tests (msan) [4/6] | 02156_async_insert_query_log | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__msan__[4_6].html |
| 2024-02-23 19:12:42 | Stateless tests (asan) [3/4] | 02570_fallback_from_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__asan__[3_4].html |
| 2024-02-23 19:12:42 | Stateless tests (asan) [3/4] | 02134_async_inserts_formats | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__asan__[3_4].html |
| 2024-02-23 19:12:42 | Stateless tests (asan) [2/4] | 02884_async_insert_native_protocol_2 | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__asan__[2_4].html |
| 2024-02-23 19:12:42 | Stateless tests (asan) [2/4] | 02884_async_insert_native_protocol_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__asan__[2_4].html |
| 2024-02-23 19:12:42 | Stateless tests (asan) [2/4] | 02725_async_insert_table_setting | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__asan__[2_4].html |
| 2024-02-23 19:12:43 | Stateless tests (asan) [1/4] | 02714_async_inserts_empty_data | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__asan__[1_4].html |
| 2024-02-23 19:13:10 | Stateless tests (asan) [4/4] | 02884_async_insert_native_protocol_1 | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__asan__[4_4].html |
| 2024-02-23 19:14:35 | Stateless tests (tsan) [1/5] | 02156_async_insert_query_log | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__tsan__[1_5].html |
| 2024-02-23 19:16:35 | Stateless tests (tsan) [2/5] | 02884_async_insert_native_protocol_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__tsan__[2_5].html |
| 2024-02-23 19:16:35 | Stateless tests (tsan) [2/5] | 02421_type_json_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__tsan__[2_5].html |
| 2024-02-23 19:16:35 | Stateless tests (tsan) [2/5] | 02134_async_inserts_formats | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__tsan__[2_5].html |
| 2024-02-23 19:17:31 | Stateless tests (tsan) [3/5] | 02810_async_insert_dedup_replicated_collapsing | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__tsan__[3_5].html |
| 2024-02-23 19:17:31 | Stateless tests (tsan) [3/5] | 02714_async_inserts_empty_data | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__tsan__[3_5].html |
| 2024-02-23 19:17:31 | Stateless tests (tsan) [3/5] | 02193_async_insert_tcp_client_1 | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__tsan__[3_5].html |
| 2024-02-23 19:23:49 | Stateless tests (debug) [2/5] | 02884_async_insert_native_protocol_1 | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__debug__[2_5].html |
| 2024-02-23 19:24:38 | Stateless tests (debug) [3/5] | 02456_async_inserts_logs | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__debug__[3_5].html |
| 2024-02-23 19:26:49 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [1/4] | 02810_async_insert_dedup_replicated_collapsing | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__release__analyzer__s3__databasereplicated__[1_4].html |
| 2024-02-23 19:28:19 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [3/4] | 02015_async_inserts_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__release__analyzer__s3__databasereplicated__[3_4].html |
| 2024-02-23 19:28:27 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [4/4] | 02884_async_insert_native_protocol_1 | https://s3.amazonaws.com/clickhouse-test-reports/0/1a4b4d493fbdbe911c33b0fb08c93f138e422b75/stateless_tests__release__analyzer__s3__databasereplicated__[4_4].html |
| 2024-02-23 19:50:39 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [1/4] | 02421_type_json_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__release__analyzer__s3__databasereplicated__[1_4].html |
| 2024-02-23 19:50:39 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [1/4] | 02884_async_insert_skip_settings | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__release__analyzer__s3__databasereplicated__[1_4].html |
| 2024-02-23 19:50:50 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [3/4] | 02570_fallback_from_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__release__analyzer__s3__databasereplicated__[3_4].html |
| 2024-02-23 19:50:50 | Stateless tests (release, analyzer, s3, DatabaseReplicated) [3/4] | 02015_async_inserts_4 | https://s3.amazonaws.com/clickhouse-test-reports/0/e325afa350228090bb707f8e986e6bbcef2cdcae/stateless_tests__release__analyzer__s3__databasereplicated__[3_4].html |
| 2024-02-23 20:02:36 | Stateless tests (asan) [1/4] | 02714_async_inserts_empty_data | https://s3.amazonaws.com/clickhouse-test-reports/0/6a7fef13bad72b86d3061e894235115ea2a14477/stateless_tests__asan__[1_4].html |
| 2024-02-23 20:02:36 | Stateless tests (asan) [1/4] | 02810_async_insert_dedup_replicated_collapsing | https://s3.amazonaws.com/clickhouse-test-reports/0/6a7fef13bad72b86d3061e894235115ea2a14477/stateless_tests__asan__[1_4].html |
| 2024-02-23 20:02:36 | Stateless tests (asan) [1/4] | 02421_type_json_async_insert | https://s3.amazonaws.com/clickhouse-test-reports/0/6a7fef13bad72b86d3061e894235115ea2a14477/stateless_tests__asan__[1_4].html |

**Comment by nikitamikhaylov** [comment]
One more failure of `02884_async_insert_skip_settings` https://s3.amazonaws.com/clickhouse-test-reports/66549/c428e35170596afefa41da3f357e7f7cf9e31708/stateless_tests__ubsan_.html

**Comment by Algunenano** [comment]
Looking at https://s3.amazonaws.com/clickhouse-test-reports/0/3c2c5b3ed5183daa402ba7c06aee488e86196d95/stateless_tests__msan__[2_3].html (`02884_async_insert_skip_settings`).

The problem is that the first query did not respect the min timeout and flushed almost inmediately:

```
2024.07.18 20:50:25.891375 [ 77394 ] {50686054-78fe-49f4-9ccb-cfedd17f0406} <Debug> executeQuery: (from [::1]:52386) (comment: async_insert_skip_settings_1) INSERT INTO t_async_insert_skip_settings VALUES  (stage: Complete)
2024.07.18 20:50:25.893464 [ 77394 ] {50686054-78fe-49f4-9ccb-cfedd17f0406} <Trace> AsynchronousInsertQueue: Asynchronous timeout increased from 50 to 100000 for queue shard 14.
2024.07.18 20:50:25.895616 [ 77394 ] {50686054-78fe-49f4-9ccb-cfedd17f0406} <Trace> AsynchronousInsertQueue: Have 1 pending inserts with total 4 bytes of data for query 'INSERT INTO test_fh9979s2.t_async_insert_skip_settings FORMAT Values'
2024.07.18 20:50:25.901053 [ 77394 ] {50686054-78fe-49f4-9ccb-cfedd17f0406} <Debug> TCPHandler: Processed in 0.01693224 sec.
2024.07.18 20:50:25.906115 [ 77394 ] {} <Trace> TCP-Session: 5a1d1a41-2ab8-453c-8cbe-8df077341da7 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2024.07.18 20:50:25.913507 [ 77394 ] {289e05ea-8057-4b1e-9870-c2e843eb7a8e} <Debug> executeQuery: (from [::1]:52386) (comment: async_insert_skip_settings_1) SET insert_deduplication_token = '2'; (stage: Complete)
2024.07.18 20:50:25.914648 [ 3444 ] {b42cd76d-46a3-4563-a220-65776d85d375} <Trace> test_fh9979s2.t_async_insert_skip_settings (69c3caa2-ddb4-4333-a690-c6baf9a6d491): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2024.07.18 20:50:25.915236 [ 3444 ] {b42cd76d-46a3-4563-a220-65776d85d375} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 89.33 GiB.
2024.07.18 20:50:25.917186 [ 77394 ] {289e05ea-8057-4b1e-9870-c2e843eb7a8e} <Debug> TCPHandler: Processed in 0.01282148 sec.
2024.07.18 20:50:25.920163 [ 1510 ] {} <Trace> system.session_log_sender.DistributedInsertQueue.default: Finished processing `/var/lib/clickhouse/store/76c/76cc58a5-a599-48fe-8cd8-b0534c21fd40/shard1_replica1/148.bin` (took 1539 ms)
2024.07.18 20:50:25.920790 [ 1510 ] {} <Trace> system.session_log_sender.DistributedInsertQueue.default/Bg: Execution took 1540 ms.
2024.07.18 20:50:25.922178 [ 77394 ] {} <Trace> TCP-Session: 5a1d1a41-2ab8-453c-8cbe-8df077341da7 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2024.07.18 20:50:25.927081 [ 3444 ] {b42cd76d-46a3-4563-a220-65776d85d375} <Trace> MergedBlockOutputStream: filled checksums all_1_1_0 (state Temporary)
2024.07.18 20:50:25.928908 [ 3444 ] {b42cd76d-46a3-4563-a220-65776d85d375} <Trace> test_fh9979s2.t_async_insert_skip_settings (69c3caa2-ddb4-4333-a690-c6baf9a6d491) (Replicated OutputStream): async insert part, part id all, block id (all_1), offsets (1), size 1
2024.07.18 20:50:25.929732 [ 77394 ] {34ab6833-9470-4b93-b317-c3a54c2123d8} <Debug> executeQuery: (from [::1]:52386) (comment: async_insert_skip_settings_1) SET log_comment = 'async_insert_skip_settings_2'; (stage: Complete)
2024.07.18 20:50:25.932108 [ 1527 ] {} <Trace> KeeperDispatcher: Processing requests batch, size: 1, bytes: 316
2024.07.18 20:50:25.933479 [ 77394 ] {34ab6833-9470-4b93-b317-c3a54c2123d8} <Debug> TCPHandler: Processed in 0.01315936 sec.
2024.07.18 20:50:25.936034 [ 1527 ] {} <Trace> KeeperDispatcher: Processing requests batch, size: 1, bytes: 333
2024.07.18 20:50:25.938153 [ 77394 ] {} <Trace> TCP-Session: 5a1d1a41-2ab8-453c-8cbe-8df077341da7 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2024.07.18 20:50:25.938844 [ 3444 ] {b42cd76d-46a3-4563-a220-65776d85d375} <Trace> test_fh9979s2.t_async_insert_skip_settings (69c3caa2-ddb4-4333-a690-c6baf9a6d491): Renaming temporary part tmp_insert_all_1_1_0 to all_0_0_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2024.07.18 20:50:25.940459 [ 1527 ] {} <Trace> KeeperDispatcher: Processing requests batch, size: 1, bytes: 830
2024.07.18 20:50:25.944937 [ 77394 ] {d6a93b48-01e9-48f5-b17a-042dc568dd30} <Debug> executeQuery: (from [::1]:52386) (comment: async_insert_skip_settings_2) INSERT INTO t_async_insert_skip_settings VALUES  (stage: Complete)
2024.07.18 20:50:25.945723 [ 1480 ] {} <Trace> test_fh9979s2.t_async_insert_skip_settings (69c3caa2-ddb4-4333-a690-c6baf9a6d491): Scheduling next merge selecting task after 8011ms
2024.07.18 20:50:25.947187 [ 77394 ] {d6a93b48-01e9-48f5-b17a-042dc568dd30} <Trace> AsynchronousInsertQueue: Asynchronous timeout increased from 100000 to 120000 for queue shard 14.
2024.07.18 20:50:25.947689 [ 3444 ] {b42cd76d-46a3-4563-a220-65776d85d375} <Debug> AsynchronousInsertQueue: Flushed 1 rows, 8 bytes for query 'INSERT INTO test_fh9979s2.t_async_insert_skip_settings FORMAT Values'
2024.07.18 20:50:25.947795 [ 1389 ] {} <Debug> test_fh9979s2.t_async_insert_skip_settings (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000000 - log-0000000000

```

This log is suspicious:
```
2024.07.18 20:50:25.893464 [ 77394 ] {50686054-78fe-49f4-9ccb-cfedd17f0406} <Trace> AsynchronousInsertQueue: Asynchronous timeout increased from 50 to 100000 for queue shard 14.
```

The queue was unused before and with default values. It turns out that in this case we use the timeout of the queue before updating, instead of the one passed as settings

**Comment by Algunenano** [comment]
NVM, the problem is no that, the problem is hash collision.

The simplest way to reproduce it:
* Set server `async_insert_threads` to 1, so collision is guaranteed.
* Set `async_insert_busy_timeout_min_ms` and `async_insert_busy_timeout_max_ms` to 10000ms (so you don't want to wait forever).
* Restart the server.
* Execute the test once: OK
* Wait 10+ seconds.
* Execute the test again: KO

After this, waiting 10s and running the test again seems to fail around 50% of the time (1 ok, 1 failure).

The problem seems to be around `max_busy_timeout_exceeded`. It checks the last insert time of the shard to decide whether to immediately flush the query (ignoring min time). This works fine if there are no collision with previous unrelated queries, but it seems extremely error prone (by default we only have 16 queues) 

Immediate flushing might make sense if the query / target table is the same (and even then I wonder if it's expected since it's ignoring `async_insert_busy_timeout_min_ms` time) but once you consider collisions there is no way to know when inserts will be flushed. 

We can either remove the immediate flush or remove the test.

**Comment by alexey-milovidov** [comment]
Removing the test (that checks that the flush occurs not earlier than some time) is ok.
We should assume that the flush can occur earlier than expected for some reason.

**Comment by alexey-milovidov** [comment]
Not fixed: https://github.com/ClickHouse/ClickHouse/issues/67298

**Comment by alexey-milovidov** [comment]
Fixed.
