### ISSUE TITLE
Errorneous predicate handling/optimization

### ISSUE THREAD

**Issue by CyberKexx** [ClickHouse/ClickHouse#47862]
**Describe what's wrong**

It seems that sql function is being applied to data which should be filtered beforehand.

If you try
https://fiddle.clickhouse.com/66aaa9fd-ea9a-4ca7-9acd-81ebdca271c1
If you uncomment the "where" clause, CH fails. If you then uncomment the "limit" clause, which possibly forces inner select materialization, it starts working again.

**Does it reproduce on recent release?**

According to Fiddle - yes

**How to reproduce**

Just run the query from link provided

**Expected behavior**

Enabling "where" clause in outer select shouldn't break the execution

**Error message and/or stacktrace**

Received exception from server (version 23.2.4):
Code: 32. DB::Exception: Received from localhost:9000. DB::Exception: Attempt to read after eof: Cannot parse Int64 from String, because value is too short: While processing (toInt64((['115'] AS `field.value`)[indexOf([15] AS `field.id`, 10)]) > 0) AND (indexOf(`field.id`, 10) != 0). (ATTEMPT_TO_READ_AFTER_EOF)

**Comment by den-crane** [comment]
works with allow_experimental_analyzer

```sql
select toInt64(lookup_res) as cast_res
from (
    select field.value[val_idx] as lookup_res
    from (
        select
            indexOf(field.id, 10) as val_idx,
            field.value
        from (
            select  [10] as `field.id`, ['110'] as `field.value`
            union all
            select  [15] as `field.id`, ['115'] as `field.value`
        )
        where val_idx != 0
    )
)
  where cast_res > 0
settings allow_experimental_analyzer=1
┌─cast_res─┐
│      110 │
└──────────┘
```

**Comment by rschu1ze** [comment]
Simplifying the query further

```sql
select toInt64(lookup_res) as cast_res
from (
    select
        indexOf(field_id, 10) as val_idx,
        ['110'][val_idx] as lookup_res
    from (
        select arrayJoin([[10], [15]]) as field_id
    )
    where val_idx != 0
)
where cast_res > 0
settings allow_experimental_analyzer = 0
    -- fails with = 0 (old code), succeeds with = 1 (analyzer)
```

Error (old code):

```
Received exception from server (version 24.3.2):
Code: 32. DB::Exception: Received from localhost:9000. DB::Exception: Attempt to read after eof: Cannot parse Int64 from String, because value is too short: while executing 'FUNCTION toInt64(arrayElement(['110'], indexOf(arrayJoin([[10], [15]]), 10)) :: 2) -> toInt64(arrayElement(['110'], indexOf(arrayJoin([[10], [15]]), 10))) Int64 : 1'. (ATTEMPT_TO_READ_AFTER_EOF)
```

which is what one would expect (original array `[15]` produces `val_idx = 0` which produces `lookup_res = ''` which throws in `toInt64()`. So I think that the analyzer is buggy here.

**Comment by Algunenano** [comment]
Let's add a test for the analyzer and close it

**Comment by rschu1ze** [comment]
We can't close it, this is a bug in the Analyzer.

**Comment by Algunenano** [comment]
> We can't close it, this is a bug in the Analyzer.

Both messages / tests say that it works with the analyzer and I've tested it and it passes in master. Are you sure it's a bug in the analyzer?

**Comment by rschu1ze** [comment]
Ah, I missed the inner `WHERE` clause, you are right, thanks. Let me write a test, then we can close this issue.
