### ISSUE TITLE
Clickhouse takes up a lot of memory when it starts

### ISSUE THREAD

**Issue by MrLi-Ran** [ClickHouse/ClickHouse#47872]
The clickhouse memory usage increases during startup, eventually reaching 50 GB, which takes up half of the server's memory.
And no queries about the business are executed at this point.

![f01b0ba75267a99a2f46743551b511e](https://user-images.githubusercontent.com/71914643/226790630-72752b7e-1143-46e4-b231-bc54862d4475.png)

How do I define the problem.

**Comment by cangyin** [comment]
for possible reference: 
- #44029

**Comment by MrLi-Ran** [comment]
> for possible reference:
> 
> * [Memory leak in version 22.8.9.24. #44029](https://github.com/ClickHouse/ClickHouse/issues/44029)

I try to find the problem through the method in # 44029
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/

And i find another problemon.
On a single node, my server contains 10 databases, including approximately 3.6 billion  records, and taking up 100 GB  on disk.
With this amount of data I have been getting startup times about 1.5h
And I cannot obtain any records of this time slot in system.query_log and system.asynchronous_metric_log.
Can the amount of data and the number of partitions be the cause of this problem?

**Comment by MrLi-Ran** [comment]
> problem



> for possible reference:
> 
> * [Memory leak in version 22.8.9.24. #44029](https://github.com/ClickHouse/ClickHouse/issues/44029)

I try to find the problem through the method in # 44029
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/

And i find another problem.
On a single node, my server contains 10 databases, including approximately 3.6 billion  records, and taking up 100 GB  on disk.
With this amount of data I have been getting startup times about 1.5h
And I cannot obtain any records of this time slot in system.query_log and system.asynchronous_metric_log.
Can the amount of data and the number of partitions be the cause of this problem?

**Comment by den-crane** [comment]
please share

```
SELECT
    database,
    table,
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.parts
WHERE (active = 1) AND (database LIKE '%') AND (table LIKE '%')
GROUP BY
    database,
    table
ORDER BY part_count DESC
limit 20;
```

**Comment by MrLi-Ran** [comment]
> please share the output of
> 
> ```sql
> SELECT
>     database,
>     table,
>     formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
>     formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
>     formatReadableSize(sum(primary_key_bytes_in_memory_allocated)) pk_mem,
>     round(usize / size, 2) AS compr_rate,
>     sum(rows) AS rows,
>     count() AS part_count
> FROM system.parts
> WHERE (active = 1) AND (database LIKE '%') AND (table LIKE '%')
> GROUP BY
>     database,
>     table
> ORDER BY part_count DESC
> limit 20;
> ```
![49bd1abad724e179d5ca777de5db0b5](https://user-images.githubusercontent.com/71914643/227214025-d5bbc829-bc97-4941-bfa7-73ae1e808270.png)
![95ae6f504d2cfd70b602a1d43ecc7ad](https://user-images.githubusercontent.com/71914643/227214028-099bab8f-ea3a-4704-87d9-913ca3387cb3.png)
![23c767325b1dbe61194eba91b5b4baa](https://user-images.githubusercontent.com/71914643/227214032-9bb11ea1-72ab-494b-b428-60f9f011242f.png)
![baffaf29ba107819d0e727ccf9d70d1](https://user-images.githubusercontent.com/71914643/227214035-6b577f97-ac64-487b-a223-9081e3853be8.png)

**Comment by den-crane** [comment]
Can you please also share 

```
SELECT
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    formatReadableSize(sum(primary_key_bytes_in_memory_allocated)) pk_mem,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.parts
WHERE (active = 1) AND (database LIKE '%') AND (table LIKE '%');
```

And `show create table table_with_2621_parts`

**Comment by MrLi-Ran** [comment]
> 
![bdccf20d31036ae7c0caefd5ea2b8c3](https://user-images.githubusercontent.com/71914643/227220957-b96f5ae6-5382-4017-af27-8705e9dffada.png)

![152cc72ef0d95573f8768f7aa4059c3](https://user-images.githubusercontent.com/71914643/227220975-060a5d7b-71e4-43ae-8fda-afd91b70a244.png)

There are 1112 fields in this table.

**Comment by MrLi-Ran** [comment]
> Can you please also share
> 
> ```
> SELECT
>     formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
>     formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
>     formatReadableSize(sum(primary_key_bytes_in_memory_allocated)) pk_mem,
>     round(usize / size, 2) AS compr_rate,
>     sum(rows) AS rows,
>     count() AS part_count
> FROM system.parts
> WHERE (active = 1) AND (database LIKE '%') AND (table LIKE '%');
> ```
> 
> And `show create table table_with_2621_parts`
![bdccf20d31036ae7c0caefd5ea2b8c3](https://user-images.githubusercontent.com/71914643/227221277-df6e3dfa-1c78-4fb0-bfa0-646077e7962b.png)
![152cc72ef0d95573f8768f7aa4059c3](https://user-images.githubusercontent.com/71914643/227221303-a364df7b-9f70-4e67-90f3-c29e7771eee9.png)

There are 1112 fields in this table.

**Comment by den-crane** [comment]
All of this is expected.

You have ~1000 tables -- too many. https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/
You have - 170 000 parts -- over too many. Expected number of parts -- up to 5000 may be 10000 per server.

`Partition by (U0X01%50, toYYYYMMDD(realtime))` is not recommended. Expected partitioning is `Partition by ( toYYYYMM(realtime))`
