### ISSUE TITLE
clickhouse v22.33 update to v23.2, One of the machines cpu load goes up high

### ISSUE THREAD

**Issue by Caius1L** [ClickHouse/ClickHouse#47876]
The clickhouse cluster in our team has three shards. when upgraded all three machines from 22.33 to 23.2, but we found that the CPU of one of them increased, even if we stopped data writing, We also found that another shard has been distributing write requests to it, what is the reason?other two shard is ok

**Comment by CheSema** [comment]
It may happens that my colleagues know some ongoing issues, but I don't. 
Could you provide more information please? It would be very helpful.
- How did it increase? Full one core or several or just a fraction of core, what a fraction?
- If it consistent problem which is reproducible, Is it possible to collect several stack traces within ten seconds gap?
- Are there active merge/replication processes active on cluster? Some statistic information from  system.replication_queue could say about it.

**Comment by Caius1L** [comment]
> 我的同事可能知道一些持续存在的问题，但我不知道。你能提供更多信息吗？这将是非常有帮助的。
> 
> * 它是如何增加的？完整的一个核心或几个或只是一小部分核心，什么分数？
> * 如果是可重现的一致问题，是否可以在十秒内收集多个堆栈跟踪？
> * 群集上是否有活动的合并/复制进程？来自system.replication_queue的一些统计信息可以说。
> 
> 可能是有用的资源 https://kb.altinity.com/altinity-kb-setup-and-maintenance/who-ate-my-cpu/

![image](https://user-images.githubusercontent.com/41660881/227084966-9ccc9e63-7a28-48c8-8e52-2a64e1c7ab76.png)
This is the cpu load that caused problems with clickhouse after we upgraded. We have not done any upgrades at the business level, but only upgraded the version of clickhouse
After the upgrade is complete, we have a lot of the following errors:
1.ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):
2.too many parts(from other clickhosue shard)

**Comment by Caius1L** [comment]
> 我的同事可能知道一些持续存在的问题，但我不知道。你能提供更多信息吗？这将是非常有帮助的。
> 
> * 它是如何增加的？完整的一个核心或几个或只是一小部分核心，什么分数？
> * 如果是可重现的一致问题，是否可以在十秒内收集多个堆栈跟踪？
> * 群集上是否有活动的合并/复制进程？来自system.replication_queue的一些统计信息可以说。
> 
> 可能是有用的资源 https://kb.altinity.com/altinity-kb-setup-and-maintenance/who-ate-my-cpu/

I checked some clickhouse parameters according to your suggestion, and there seems to be no special attention.

**Comment by CheSema** [comment]
@Caius1L I noticed that you closed the question. Did you find out something?

**Comment by Caius1L** [comment]
> @Caius1L I noticed that you closed the question. Did you find out something?

Sorry, my coworker may have closed the question by mistake, bro, we didn't fix it. It seems that after upgrading from a lower version, the load on our system has increased a lot, and the problem of too many parts has frequently appeared

**Comment by den-crane** [comment]
> > @Caius1L I noticed that you closed the question. Did you find out something?
> 
> Sorry, my coworker may have closed the question by mistake, bro, we didn't fix it. It seems that after upgrading from a lower version, the load on our system has increased a lot, and the problem of too many parts has frequently appeared


It's unclear how upgrade is related to the ingestion increase. Provide more info.

**Comment by den-crane** [comment]
no info, not actionable issue
