### ISSUE TITLE
How to import local compressed file using input(structure)? 

### ISSUE THREAD

**Issue by libinyl** [ClickHouse/ClickHouse#47886]
How do I import my local **compressed** file into clickhouse using `input(structure)` ? 

Actually , I want import my local json.gz file into clickhouse while keeping its original json line.

I already have a workaround: 

1. decompress my json.gz to my_json.json
2. cat  my_json.json | clickhouse-client --query={sql as bellow}

```sql
INSERT INTO
	my_table
select
	origin_log as origin_log, -- keep original json line
	fromUnixTimestamp64Milli((JSONExtractInt(origin_log, 'started_at'))) as started_at ,-- parse time
        -- ... and parse other fields
from
	input('origin_log String') FORMAT JSONAsString
```

but it's very slow due to the large decompressed json file (20+ times larger!).  

Can I import **json.gz** diectly?   I have checked the **from file()** approach but it can't keep the origin json line.

**Comment by den-crane** [comment]
`zcat my_json.json | clickhouse-client --query={sql as bellow}`

**Comment by libinyl** [comment]
> `zcat my_json.json.gz | clickhouse-client --query={sql as bellow}`

I thought it would also be slow because it still send decompressed data; The total time is still limited by network I/O . But I will try it. thanks!

**Comment by CheSema** [comment]
It might be useful, there is a lot of cases how to load json.
https://clickhouse.com/docs/en/integrations/data-formats/json
Also I see that is possible to directly read compressed data from s3. 

About client. It sends compressed data to the server. Yes, the some amount of cpu would be consumed to compression, but the size would be nearly the same.
Useful resources:
https://clickhouse-driver.readthedocs.io/en/latest/features.html#compression

PS:
Hard level on: https://clickhouse.com/docs/en/faq/integration/json-import
It it possible to use http api to send file as a resource. Server would open it, decompress it, read from it. Make sure that it compressed with codec which server understand.

**Comment by den-crane** [comment]
Do you mean the server is remote? 
You can use curl and send gz file to a clickhouse-server and SQL in the URL

```
curl "http://localhost:8123/?enable_http_compression=1&query=INSERT+INTO+my_table+...." \
-H 'Accept-Encoding: gzip'   -Ss  --data-binary @my_json.json.gz
```
