### ISSUE TITLE
Unexpected background_schedule_pool_size default value

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#47900]
While doing config changes I noticed this message in my logs:

```
2023.03.22 16:08:19.721420 [ 500718 ] {} <Warning> BackgroundSchedulePool/BgSchPool: Tried to increase the number of threads but the new threads count (16) is not greater than old one (128)
```

This was surprising since I wasn't changing the number of threads, so I wasn't expecting any change there.

It seems that the size of this pool is initialized to 128 here:

https://github.com/ClickHouse/ClickHouse/blob/606da9a73fc01e35bbf0f68c247a67568438f071/src/Interpreters/Context.cpp#L2224-L2240

But the default value is declared as 16 here:

https://github.com/ClickHouse/ClickHouse/blob/5c4da5aa4a08ea2fe1cfa279fc1ec8c4e6e7f68f/src/Core/ServerSettings.h#L68

These values should match. And ideally, instead of 2 hardcoded values Context should be using the default values from SERVER_SETTINGS for all its settings.

**Comment by Algunenano** [comment]
> #45189 (comment)

That's supposed to be fixed. I'm not using any profile settings and when I do set server settings they work.

In this case though there are 2 different default values conflicting.

**Comment by den-crane** [comment]
I mean 

_we discussed it Clickhouse team and they are agree that these settings should be removed from default profile, anyway they are marked as obsolete for more than 6 months._


profiles.default.background_schedule_pool_size -- should not exist.

You can make a PR and remove all code related to 

```
background_buffer_flush_schedule_pool_size
background_pool_size
background_move_pool_size
background_fetches_pool_size
background_common_pool_size
background_schedule_pool_size
background_message_broker_schedule_pool_size
background_distributed_schedule_pool_size
```

**Comment by Algunenano** [comment]
I do not care if and when the default profile settings go away. You can make the PR to remove them if you think that's necessary.

This is about an issue with one of the non deprecated settings.

**Comment by den-crane** [comment]
Ah, I see. 
I misunderstood.
I thought 128 came from  https://github.com/ClickHouse/ClickHouse/blob/a31c0d8eeef3d698e0fd8404ba86a9f0fc513f0c/src/Core/Settings.h#L755

**Comment by filimonov** [comment]
I think this should reolve the issue https://github.com/ClickHouse/ClickHouse/pull/48055/files#diff-3f7b59d638c38403accf4f916f98a03ceecfae10cdd71bac4cd2cc2d9b08cae1L70
