### ISSUE TITLE
Distributed table query consistency problem

### ISSUE THREAD

**Issue by mywrong** [ClickHouse/ClickHouse#47926]
We have a CK cluster with four nodes, this cluster has two shards and each shard has two replicas, it is named cluster1. We will build a distributed table on this cluster.
We found a phenomenon, use "insert into A format CSV" to write data to the distributed table, then use "insert into B select * from A" immediately, and finally use "select count(*) from B" to query B amount of data. There is a certain probability that the amount of data in B obtained by the query is smaller than the amount of data in A.

How can we ensure the consistency of distributed table data queries in the double copy?

Our operation is as follows：

1. Create tables A and A_local

```
create table `db`.`A_local` on cluster cluster1
(
    ...
)
    engine = ReplicatedMergeTree('/clickhouse/tables/db/A_local/{shard}', '{replica}')
        ORDER BY tuple()
        SETTINGS allow_nullable_key = 1, index_granularity = 8192;
```

```
create table `db`.`A` on cluster cluster1 as `db`.`A_local`
    engine = Distributed('cluster1', 'db', 'A_local', rand())
    SETTINGS allow_nullable_key = 1, index_granularity = 8192;;
```

2. Create tables B and B_local whose table structure is consistent with A and A_local.

```
create table `db`.`B_local` on cluster cluster1
(
    ...
)
    engine = ReplicatedMergeTree('/clickhouse/tables/db/B_local/{shard}', '{replica}')
        ORDER BY tuple()
        SETTINGS allow_nullable_key = 1, index_granularity = 8192;
```
```
create table `db`.`B` on cluster cluster1 as `db`.`B_local`
    engine = Distributed('cluster1', 'db', 'B_local', rand())
    SETTINGS allow_nullable_key = 1, index_granularity = 8192;
```

3. Insert data into table A. We use java to import CSV files into Clickhouse. “csvPath” is the absolute path of the CSV file，“uri” is the address of one of the clickhouse nodes.

```
import com.clickhouse.client.*;
ClickHouseNode server = ClickHouseNode.of(uri); 
ClickHouseClient.load(server, A,
    ClickHouseFormat.CSV, ClickHouseCompression.NONE, csvPath).get(); 
```

4. Insert data into table B.
`insert into B select * from A`

5. Query the amount of data in table B
`select count(*) from B`

we use clickhouse 22.3.6.5.
In order to solve this problem, we try to configure the following parameters:
insert_quorum=0
insert_quorum_parallel=0
select_sequential_consistency=1
![image](https://user-images.githubusercontent.com/53046813/227150940-13aa840e-a644-44e7-821f-6947cebe6bde.png)
But these parameters don't seem to work.

What is the right way ?

**Comment by mywrong** [comment]
Yes, we have set `insert_distributed_sync = 1` and `internal_replication=true` on each node before, but this does not seem to work.
`load_balacing` is set to `random`. We suspect that the problem is due to the `select` query randomly selecting replicas that haven't finished syncing yet
Is there a parameter that can control the `select` query to only take effect on the replica that contains complete data?

**Comment by tavplubix** [comment]
Probably you need SYSTEM SYNC REPLICA as well.

> Is there a parameter that can control the select query to only take effect on the replica that contains complete data? 

`select_sequential_consistency`, but it has poor usability and you'll need SYSTEM SYNC REPLICA anyway

**Comment by mywrong** [comment]
Thank you for your reply @tavplubix .
`SYSTEM SYNC REPLICA` may not be suitable for our usage scenario, because it may reduce performance. Our scenario requires data to be consistent and as high-performance as possible.
We may try to use a single-replica cluster to solve this problem, but may lose the high availability of multiple replicas.
If ClickHouse has a better solution, please let us know, thanks.

**Comment by tavplubix** [comment]
> Our scenario requires data to be consistent and as high-performance as possible.
> We may try to use a single-replica cluster to solve this problem, but may lose the high availability of multiple replicas.

Unfortunately, it seems to be impossible. If you write data with `insert_quorum[_parallel] = <number of replicas>` (or just use a single-replica cluster), then you obviously lose availability: all writes fail if at least one replica is down.

If you write to some subset of replicas, then the rest of the replicas obviously become inconsistent, so you have to sync them somehow.

> If ClickHouse has a better solution, please let us know, thanks.

Maybe https://github.com/ClickHouse/ClickHouse/issues/47794 will help a bit

**Comment by mywrong** [comment]
Thank you for your answer, we will continue to follow the solution to this problem. @tavplubix

**Comment by mywrong** [comment]
Thank you for your answer, we will continue to follow the solution to this problem. @tavplubix

**Comment by mywrong** [comment]
Thank you for your answer, we will continue to follow the solution to this problem. @tavplubix
