### ISSUE TITLE
Explain a difference between auth methods

### ISSUE THREAD

**Issue by dmlogv** [ClickHouse/ClickHouse#47924]
Hi all. I just wanna talk about the slightly confusing descriptions of user authentication methods.

**Describe the issue**

```
IDENTIFIED WITH no_password
IDENTIFIED WITH plaintext_password BY 'qwerty'
IDENTIFIED WITH sha256_password BY 'qwerty' or IDENTIFIED BY 'password'
IDENTIFIED WITH sha256_hash BY 'hash' or IDENTIFIED WITH sha256_hash BY 'hash' SALT 'salt'
IDENTIFIED WITH double_sha1_password BY 'qwerty'
IDENTIFIED WITH double_sha1_hash BY 'hash'
```

I think it's not very clear and don't answer on the following (and other) questions:

- What a user exactly should place between the quotes?
- How it will be logged by ClickHouse? 
  - Or: who should hash the password: client or server? 
  - Or: is it safe to use `sha256_password` and transmit a plain password via my network? :)
- How (and where) it will be stored?

It would be very cool if you describe everything for complete laymen.

**Comment by rfraposa** [comment]
Good point. I tried to clarify some of the details with https://github.com/ClickHouse/ClickHouse/pull/47991
