### ISSUE TITLE
Missing/unclear docs about multi-expression secondary indexes

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#47923]
The docs on [data skipping indices](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-data_skipping-indexes) state that they are build over an expression

```sql
INDEX index_name expr TYPE type(...) [GRANULARITY granularity_value]
```

"Expression" is used in the docs in singular, i.e. the index is build over a *single* expression.

But then the example

```sql
CREATE TABLE table_name
(
    u64 UInt64,
    i32 Int32,
    s String,
    ...
    INDEX a (u64 * i32, s) TYPE minmax GRANULARITY 3,
    INDEX b (u64 * length(s)) TYPE set(1000) GRANULARITY 4
) ENGINE = MergeTree()
...
```

builds index `a` over *two* expressions. What happens in case of > 1 expression is not intuitively clear. E.g. does the index (in this case a `min-max` index) store one minimum/maximum pair per expression? (if so, why would one not have two indices instead?). Are both expressions somehow combined (that would be weird but there are other databases which do that kind of stuff, usually based on string concatenation)?

The best option would be if the docs describe + given an example for single-expression skipping indices first, and then threat multi-expression indexes as a special "extension", along with a separate example.

**Comment by CurtizJ** [comment]
The expression `(u64 * i32, s)` is considered as tuple and index `a` is built over a tuple, which doesn't make sense. Actually expression `(u64 * length(s))` is also considered as tuple of one element, but one-element tuples are flattened to single argument column on a parser level. You can see it by executing `SHOW CREATE TABLE`:

```sql
SHOW CREATE TABLE table_name

Query id: 189ee6b1-e1fa-4896-b033-889e57e51215

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE default.table_name
(
    `u64` UInt64,
    `i32` Int32,
    `s` String,
    INDEX a (u64 * i32, s) TYPE minmax GRANULARITY 3,
    INDEX b u64 * length(s) TYPE set(1000) GRANULARITY 4
)
ENGINE = MergeTree
ORDER BY u64
SETTINGS index_granularity = 8192 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by rschu1ze** [comment]
Okay, so > 1 expression will usually be useless but we should also not disallow it. I'll update the example in the docs.
