### ISSUE TITLE
ClickHouse spends time in makeSetsForIndex for skip index with use_skip_indexes=0

### ISSUE THREAD

**Issue by chbota** [ClickHouse/ClickHouse#47947]
**Describe the situation**
When you have a skip index defined on a table and are using an `IN (...)` construction, ClickHouse will always spend time in `makeSetsForIndex` regardless of the value of `use_skip_indexes`.

For some of our queries, evaluating the skip index takes more time than just reading all the rows so we set `use_skip_indexes=0` for these queries. However, we still see significant performance regression on these queries from simply having a skip index defined on the table because of the time spent in `makeSetsForIndex`.

Setting `use_skip_indexes=0` and `use_index_for_in_with_subqueries=0` resolves the performance regression

**Expected performance**
I would expect us not to do any work related to skip indexes if `use_skip_indexes` is set to 0

**Comment by chbota** [comment]
Got it - possible I'm misunderstanding what's happening in that function. If that's the case though, why would disabling it remove the performance overhead of the skip index?

If we don't have the skip index defined, there's no performance difference between use_index_for_in_with_subqueries=1 and use_index_for_in_with_subqueries=0

**Comment by chbota** [comment]
adding repro steps:

first, create a table like:

```
CREATE TABLE default.index_perf_repro
(
    `a` String,
    `b` String,
    `c` String,
    INDEX idx_c c TYPE bloom_filter GRANULARITY 1
)
ENGINE = MergeTree
ORDER BY (a, b)
SETTINGS index_granularity = 8192
```

insert a bunch of data:

```
insert into index_perf_repro select * from generateRandom('a String, b String, c String') limit 5000000;
```

query using an `IN (subquery)` construction filtering over `c`:

```
SELECT count()
FROM index_perf_repro
WHERE (c IN (
    SELECT *
    FROM generateRandom('c String')
    LIMIT 100000000
)) AND startsWith(a, 'a')
```

the key is the inner query result set needs to be very large for the time spent building sets to be noticeable in the trace logs


some example queries w/ the various configurations:

first, save target list of `c` values to temporary table
```
CREATE TEMPORARY TABLE target_c AS
SELECT *
FROM generateRandom('c String')
LIMIT 100000000
```


index defined, use_skip_indexes=1, use_index_for_in_with_subqueries=1 takes ~20sec
```
SELECT count()
FROM index_perf_repro
WHERE (c IN (
    SELECT *
    FROM target_c
)) AND startsWith(a, 'a')
SETTINGS use_skip_indexes = 1, use_index_for_in_with_subqueries = 1
```

index defined, use_skip_indexes=0, use_index_for_in_with_subqueries=1 takes ~19sec
```
SELECT count()
FROM index_perf_repro
WHERE (c IN (
    SELECT *
    FROM target_c
)) AND startsWith(a, 'a')
SETTINGS use_skip_indexes = 0, use_index_for_in_with_subqueries = 1
```

index defined, use_skip_indexes=0, use_index_for_in_with_subqueries=0 takes ~17sec
```
SELECT count()
FROM index_perf_repro
WHERE (c IN (
    SELECT *
    FROM target_c
)) AND startsWith(a, 'a')
SETTINGS use_skip_indexes = 0, use_index_for_in_with_subqueries = 0
```

index not defined takes ~17sec
```
ALTER TABLE index_perf_repro
    DROP INDEX idx_c;

SELECT count()
FROM index_perf_repro
WHERE (c IN (
    SELECT *
    FROM target_c
)) AND startsWith(a, 'a');
```

**Comment by CurtizJ** [comment]
Got it, thank you. Looks like a real issue.
