### ISSUE TITLE
Default compression behavior

### ISSUE THREAD

**Issue by arodmond** [ClickHouse/ClickHouse#47949]
I have a CH DB version 22.03 with some data running with compression method zstd.
I have changed in the file config.xml to compression method lz4
After restart CH, I have noted that only new data inserted in a table has parts with file default_compression_codec.txt CODEC(LZ4) and the old data previous to the change has parts with: CODEC(ZSTD(1))
My question is:
A change in the default compression method only works for new data inserted or I need to run OPTIMIZE TABLE ... FINAL in all the tables to apply the changes?

**Comment by den-crane** [comment]
>A change in the default compression method only works for new data inserted 

yes. Only newly inserted and merged data.

> I need to run OPTIMIZE TABLE ... FINAL in all the tables to apply the changes?

Yes, you need.

**Comment by arodmond** [comment]
Thank you.
