### ISSUE TITLE
File-based input/output (rather than S3) for Iceberg, DeltaLake, and Hudi table engines

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/ClickHouse#47960]
> (you don't have to strictly follow this form)

Power user is requesting capability to use the DeltaLake, Iceberg, and Hudi table engines with a local file. Current support only appears to support s3() or url(), for example:

* https://clickhouse.com/docs/en/engines/table-engines/integrations/deltalake
* https://clickhouse.com/docs/en/engines/table-engines/integrations/iceberg
* https://clickhouse.com/docs/en/engines/table-engines/integrations/hudi

Existing docs notes include statements such as the following:
`Note that the Delta Lake table must already exist in S3, this command does not take DDL parameters to create a new table.` 

> A clear and concise description of what is the intended usage scenario is.

Usage scenario is to provide local file-based table support for Iceberg, DeltaLake, and Hudi. Perhaps using clickhouse-server or clickhouse-local

> A clear and concise description of what you want to happen.

Users may not have this data in an existing S3 or URL-accessible location. Allowing local file access expands current usage and is an extension of current scope

> A clear and concise description of any alternative solutions or features you've considered.

Not sure of a good workaround. User would have to procure an S3 bucket or URL-based location with the current functionality.

> Add any other context or screenshots about the feature request here.

n/a

**Comment by UnamedRus** [comment]
IMO, we should just have single table "engine" (EXTERNAL) for all integration stuff. https://github.com/ClickHouse/ClickHouse/issues/46823

Just like with dictionaries.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/48040

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/59767

**Comment by melvynator** [comment]
Tracking Delta Lake separately. Not enough traction for Hudi right now. Closing in favor of https://github.com/ClickHouse/ClickHouse/issues/68043
