### ISSUE TITLE
The server cannot be started with error code: 231

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#47966]
The cluster contains three nodes, 1 share 3 replica.  Because of the insufficient storage resource (hard disk), one node cannot be started with the following error message. The other two nodes work fine. 

We already expand the storage capacity, but the server still cannot be started. How can we fix this issue to start the server?

ClickHouse Version: 22.3.6.5

Thanks!  

2023.03.24 11:54:27.848223 [ 22270 ] {} <Information> KeeperLogStore: Compaction up to 46805802 finished new min index 46904391, new max index 46906088
2023.03.24 11:54:27.849463 [ 22280 ] {} <Information> RaftInstance: creating a snapshot for index 46906086
2023.03.24 11:54:27.849481 [ 22280 ] {} <Information> RaftInstance: create snapshot idx 46906086 log_term 9
2023.03.24 11:54:27.849508 [ 22280 ] {} <Information> RaftInstance: create snapshot idx 46906086 log_term 9 done: 22 us elapsed
2023.03.24 11:54:27.926131 [ 22257 ] {} <Error> Application: Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table ls_chdb.dwd_acc_valtable (13bf9dbf-909c-4e35-941e-54579af0b68e) doesn't look like the set of parts in ZooKeeper: 1.86 million rows of 3.68 million total rows in filesystem are suspicious. There are 3 unexpected parts with 1855466 rows (1 of them is not just-written with 1824024 rows), 0 missing parts (with 0 blocks).: Cannot attach table `ls_chdb`.`dwd_acc_valtable` from metadata file /var/lib/clickhouse/store/a61/a614fce3-631f-4494-ade2-9104abb9a24e/dwd_acc_valtable.sql from query ATTACH TABLE ls_chdb.dwd_acc_valtable UUID '13bf9dbf-909c-4e35-941e-54579af0b68e' (`SEQ_NO` String, `PORT_ID` Nullable(String), `PORT_NAME` Nullable(String), `BOOKSET_ID` Nullable(String), `PROFIT_TYPE` Nullable(String), `VAL_DATE` Date, `DETAIL_DIST` Nullable(String), `LAYERING_ID` Nullable(String), `SUBJECT_NO` Nullable(String), `SUBJECT_NAME` Nullable(String), `FSUBJECT_ID` Nullable(String), `NUM_AMT` Nullable(Decimal(24, 7)), `UNIT_COST` Nullable(Decimal(24, 7)), `O_CCY` Nullable(String), `B_CCY` Nullable(String), `EX_RATE` Nullable(Decimal(30, 14)), `O_COST` Nullable(Decimal(24, 7)), `B_COST` Nullable(Decimal(24, 7)), `B_COST_PERCENT` Nullable(Decimal(30, 14)), `CLOSE_PRICE` Nullable(Decimal(30, 14)), `O_MARKET_VALUE` Nullable(Decimal(24, 7)), `B_MARKET_VALUE` Nullable(Decimal(24, 7)), `B_VALUE_PERCENT` Nullable(Decimal(30, 14)), `O_VALUE_INCREMENT` Nullable(Decimal(24, 7)), `B_VALUE_INCREMENT` Nullable(Decimal(24, 7)), `SEC_STATE` Nullable(String), `EQUITY_INFO` Nullable(String), `BAL_FLAG` Nullable(String), `SHADOW_PRICE_VALUE` Nullable(Decimal(24, 7)), `MARKET_VAL_DATE` Nullable(DateTime), `CREATE_USER` String, `CREATE_DEPT` Nullable(String), `CREATE_TIME` DateTime, `UPDATE_USER` String, `UPDATE_TIME` DateTime, `INPUT_TYPE` String, `_sign` Int8 DEFAULT 1, `SUBJECT_SEQ` Decimal(20, 0)) ENGINE = ReplicatedCollapsingMergeTree('/clickhouse/tables/13bf9dbf-909c-4e35-941e-54579af0b68e/{shard}', '{replica}', _sign) ORDER BY SEQ_NO SETTINGS index_granularity = 8192. (TOO_MANY_UNEXPECTED_DATA_PARTS), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37173a in /usr/bin/clickhouse
1. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, unsigned long&, unsigned long&, unsigned long&, unsigned long, unsigned long const&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, unsigned long&&, unsigned long&, unsigned long&, unsigned long&, unsigned long&&, unsigned long const&) @ 0x15ffb117 in /usr/bin/clickhouse
2. DB::StorageReplicatedMergeTree::checkParts(bool) @ 0x15febb8b in /usr/bin/clickhouse
3. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, bool) @ 0x15fde1b0 in /usr/bin/clickhouse
4. ? @ 0x16540696 in /usr/bin/clickhouse
5. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15f4949a in /usr/bin/clickhouse
6. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x15263a1b in /usr/bin/clickhouse
7. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, bool) @ 0x15309f0a in /usr/bin/clickhouse
8. ? @ 0x15338caa in /usr/bin/clickhouse
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb41b7ca in /usr/bin/clickhouse
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb41d964 in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb418b97 in /usr/bin/clickhouse
12. ? @ 0xb41c71d in /usr/bin/clickhouse
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.3.6.5 (official build))
2023.03.24 11:54:27.926316 [ 22257 ] {} <Information> Application: Shutting down storages.
2023.03.24 11:54:27.926326 [ 22257 ] {} <Information> Context: Shutdown disk ck1
2023.03.24 11:54:27.926330 [ 22257 ] {} <Information> Context: Shutdown disk default

**Comment by ucasfl** [comment]
Try `touch /path_to/clickhouse-server/flags/force_restore_data` and restart server. 

Reference: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#recovery-after-complete-data-loss

**Comment by xsong123** [comment]
> Try `touch /path_to/clickhouse-server/flags/force_restore_data` and restart server.
> 
> Reference: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#recovery-after-complete-data-loss

i have the same below error ,  above solution can fix the error that ZooKeeper throwed?
Caught exception while loading metadata: Code: 231. DB::Exception: The local set of parts of table ls_chdb.dwd_acc_valtable (13bf9dbf-909c-4e35-941e-54579af0b68e) doesn't look like the set of parts in ZooKeeper: 1.86 million rows of 3.68 million total rows in filesystem are suspicious
