### ISSUE TITLE
Introduce `SYSTEM STOP CONNECTIONS` query

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#47972]
**Use case**

Similar to existing queries `SYSTEM STOP MERGES`, `SYSTEM STOP REPLICATED SENDS` this query should stop accepting new connections from any ports (except internal one) and close existing connections by killing all the queries.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

New ActionsBlocker for this event and the similar approach as OvercommitTracker uses to stop existing queries?

**Comment by mlex** [comment]
> stop accepting new connections from any ports (except internal one) and close existing connections by killing all the queries.

Even better to also/additionally/alternatively 
* stop accepting new queries through existing connections
* wait for already running queries until they complete and then automatically close the connection

This way we could implement a "drain-gracefully" functionality where one replica is removed from the cluster slowly (no new connections by removing the replica from the loadbalancer, no new queries via existing connections via this feature here) but gracefully (all existing queries get time to succeed).

**Comment by mgill25** [comment]
> wait for already running queries until they complete and then automatically close the connection

IMHO It would be prudent to include a hard time-limit after which we force-kill the queries. For long-running queries, if we're waiting for _graceful termination_ before the connection closes, we might be waiting for a long time.

**Comment by alexey-milovidov** [comment]
We already have it; it is named `shutdown_wait_unfinished` in the server's config.
You just set it up to a high value and stop the server.

**Comment by mgill25** [comment]
@alexey-milovidov Stopping the server needs to be decoupled from the connection drop, since the connections only need to be dropped for external connections. For internal  communication, a lightweight `SYSTEM SYNC REPLICA` (https://github.com/ClickHouse/ClickHouse/issues/47794) needs to be issued before server can be stopped.

**Comment by alexey-milovidov** [comment]
@nikitamikhaylov, need to reassign or close.

**Comment by alexey-milovidov** [comment]
I recommend to implement it as SYSTEM STOP LISTEN name / SYSTEM START LISTEN name for the available servers.
For example, it will allow stopping MySQL protocol, or the interserver protocol, etc. that can be useful for debugging.
