### ISSUE TITLE
Get precise current time from ClickHouse query

### ISSUE THREAD

**Issue by a-rodin** [ClickHouse/ClickHouse#4797]
The `now()` function returns the current time with one second precision. However, I would like to also have ability to retrieve current fraction of second with high precision (preferably up to nanoseconds). Is it somehow possible to do?

I'm aware that ClickHouse datetime type doesn't support fractions of seconds and I'm ok with just putting the nanosecond part to a separate integer column.

Background: I would like to store order of messages coming from `Kafka` engine and time with high precision seems to be a good candidate to be sorting key for this purpose.

**Comment by den-crane** [comment]
select now(), sleep(1),n from (select number, now() n from numbers(5) settings max_block_size=1)

IMHO now() is a constant per query.

**Comment by alexey-milovidov** [comment]
> IMHO now() is a constant per query.

Yes. It is documented. now() is a constant expression and it allows to use index for expressions like `x >= now() - INTERVAL 1 MINUTE`

We can provide a separate function that will return precise time of invocation. But functions in ClickHouse are invoked for vectors, not for single values. The result will still be constant for a single block of data.

**Comment by a-rodin** [comment]
@den-crane @alexey-milovidov Yes, `now()` is evaluated once per query, but it seems like the query for Kafka tables is executed for each batch / message. For example, I have tables like this:

```sql
CREATE TABLE IF NOT EXISTS test_kafka (
  message String
) ENGINE = Kafka
SETTINGS
  kafka_broker_list = 'localhost:9092',
  kafka_topic_list = 'test-events',
  kafka_group_name = 'test-events-group',
  kafka_format = 'JSONEachRow',
  kafka_row_delimiter = '\n';

CREATE MATERIALIZED VIEW IF NOT EXISTS test
ENGINE = MergeTree()
PARTITION BY toYYYYMM(dateTime)
ORDER BY (dateTime)
AS SELECT
  message,
  toDateTime(now()) AS dateTime
FROM test_kafka;
```

Then I put messages to Kafka with some delay:
```sh
(echo '{"message": "hello"}'; sleep 10; echo '{"message": "world"}')  | kafka-console-producer.sh --broker-list kafka:9092 --topic test-events
```

So that the rows in the view have different timestamps:
```
┌─message─┬────────────dateTime─┐
│ hello   │ 2019-03-25 18:05:33 │
│ world   │ 2019-03-25 18:05:40 │
└─────────┴─────────────────────┘
```

**Comment by a-rodin** [comment]
Yes, `now()` is evaluated once per query, but it seems like queries for materialized views are executed for each batch separately and thus have different `now()` values. For example, I have tables like this:

```sql
CREATE TABLE IF NOT EXISTS test_kafka (
  message String
) ENGINE = Kafka
SETTINGS
  kafka_broker_list = 'localhost:9092',
  kafka_topic_list = 'test-events',
  kafka_group_name = 'test-events-group',
  kafka_format = 'JSONEachRow',
  kafka_row_delimiter = '\n';

CREATE MATERIALIZED VIEW IF NOT EXISTS test
ENGINE = MergeTree()
PARTITION BY toYYYYMM(dateTime)
ORDER BY (dateTime)
AS SELECT
  message,
  toDateTime(now()) AS dateTime
FROM test_kafka;
```

Then I put messages to Kafka with some delay:
```sh
(echo '{"message": "hello"}'; sleep 10; echo '{"message": "world"}')  | kafka-console-producer.sh --broker-list localhost:9092 --topic test-events
```

So that the rows in the view have different timestamps:
```
┌─message─┬────────────dateTime─┐
│ hello   │ 2019-03-25 18:05:33 │
│ world   │ 2019-03-25 18:05:40 │
└─────────┴─────────────────────┘
```

**Comment by a-rodin** [comment]
> But functions in ClickHouse are invoked for vectors, not for single values. The result will still be constant for a single block of data.

Yes, so returning to the example with Kafka it means that multiple consecutive rows can still have single value of the function.

As a proposal: may be it would be a useful feature to expose Kafka messages metadata as special functions for tables with Kafka engine, so that it is would be possible to explicitly know offset/partition for each row that came as a Kafka message.

**Comment by alexey-milovidov** [comment]
> As a proposal: may be it would be a useful feature to expose Kafka messages metadata as special functions for tables with Kafka engine, so that it is would be possible to explicitly know offset/partition for each row that came as a Kafka message.

Yes, it is technically possible with "virtual columns" (in the same way as it's possible to query `_table` in Merge tables or `_part` in MergeTree tables).

**Comment by blinkov** [comment]
@a-rodin, do you have any further questions?

**Comment by a-rodin** [comment]
@blinkov No, thanks for asking!

The idea about exposing Kafka metadata fields (https://github.com/ClickHouse/ClickHouse/issues/4797#issuecomment-476324427 and https://github.com/ClickHouse/ClickHouse/issues/4797#issuecomment-477359590) was somewhat off-topic, so in case of someone wants to continue discussing it, it can be put into a separate issue.

**Comment by filimonov** [comment]
> @blinkov No, thanks for asking!
> 
> The idea about exposing Kafka metadata fields ([#4797 (comment)](https://github.com/ClickHouse/ClickHouse/issues/4797#issuecomment-476324427) and [#4797 (comment)](https://github.com/ClickHouse/ClickHouse/issues/4797#issuecomment-477359590)) was somewhat off-topic, so in case of someone wants to continue discussing it, it can be put into a separate issue.

That was implemented about a year ago.
