### ISSUE TITLE
Can't not successfully git submodule update --init

### ISSUE THREAD

**Issue by chenzepeng140** [ClickHouse/ClickHouse#48009]
I have run git submodule update --init and return nothing,it seems run successfully,but next time when I try install ClickHouse,same error occurs

> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

Operating system
macOS 12.2.1

Cmake version
3.26.1
Ninja version
1.10.2
Compiler name and version
16.0.0
Full cmake and/or ninja output

**Full cmake and/or ninja output**

(base) zepengchen@laojiekedeMacBook-Pro build %         git submodule update --init                                                                                                                   
(base) zepengchen@laojiekedeMacBook-Pro build %  cmake ..  -DCMAKE_C_COMPILER=$(brew --prefix llvm)/bin/clang -DCMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- Using compiler:
Homebrew clang version 16.0.0
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
-- Using linker: <default>
-- Using archiver: /usr/bin/ar
-- Using ranlib: /opt/homebrew/opt/llvm/bin/llvm-ranlib
-- Using install-name-tool: /usr/bin/install_name_tool
-- Using objcopy: /usr/local/bin/objcopy
-- Using strip: /usr/bin/strip
-- Using ccache: /opt/homebrew/bin/ccache (version 4.8)
-- Git HEAD commit hash: 3eb2a1cc5b273319327d96829c8f8e225aa531fc
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   CMakeLists.txt
	modified:   contrib/AMQP-CPP (modified content)
	modified:   contrib/avro (modified content)
	modified:   contrib/aws (modified content)
	modified:   contrib/aws-c-cal (modified content)
	modified:   contrib/aws-c-common (modified content)
	modified:   contrib/aws-c-io (modified content)
	modified:   contrib/aws-crt-cpp (modified content)
	modified:   contrib/aws-s2n-tls (modified content)
	modified:   contrib/azure (modified content)
	modified:   contrib/base64 (modified content)
	modified:   contrib/bzip2 (modified content)
	modified:   contrib/c-ares (modified content)
	modified:   contrib/cctz (modified content)
	modified:   contrib/cld2 (modified content)
	modified:   contrib/crc32-s390x (modified content)
	modified:   contrib/crc32-vpmsum (modified content)
	modified:   contrib/datasketches-cpp (modified content)
	modified:   contrib/dragonbox (modified content)
	modified:   contrib/fastops (modified content)
	modified:   contrib/grpc (modified content)
	modified:   contrib/hashidsxx (modified content)
	modified:   contrib/hive-metastore (modified content)
	modified:   contrib/krb5 (modified content)
	modified:   contrib/lemmagen-c (modified content)
	modified:   contrib/libcpuid (modified content)
	modified:   contrib/libdivide (modified content)
	modified:   contrib/libgsasl (modified content)
	modified:   contrib/libhdfs3 (modified content)
	modified:   contrib/librdkafka (modified content)
	modified:   contrib/libstemmer_c (modified content)
	modified:   contrib/libunwind (modified content)
	modified:   contrib/liburing (modified content)
	modified:   contrib/mariadb-connector-c (modified content)
	modified:   contrib/morton-nd (modified content)
	modified:   contrib/nanodbc (modified content)
	modified:   contrib/nats-io (modified content)
	modified:   contrib/nlp-data (modified content)
	modified:   contrib/orc (modified content)
	modified:   contrib/replxx (modified content)
	modified:   contrib/rocksdb (modified content)
	modified:   contrib/s2geometry (modified content)
	modified:   contrib/sqlite-amalgamation (modified content)
	modified:   contrib/sysroot (modified content)
	modified:   contrib/ulid-c (modified content)
	modified:   contrib/unixodbc (modified content)
	modified:   contrib/vectorscan (modified content)
	modified:   contrib/wordnet-blast (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	"CMakeLists\347\232\204\345\211\257\346\234\254.txt"
	gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz

no changes added to commit (use "git add" and/or "git commit -a")
CMake Error at CMakeLists.txt:39 (message):
  Submodules are not initialized.  Run

  	git submodule update --init

-- Configuring incomplete, errors occurred!

**Comment by chenzepeng140** [comment]
git submodule update --init
Cloning into '/Users/zepengchen/ClickHouse/contrib/thrift'...
fatal: unable to access 'https://github.com/apache/thrift/': Failed to connect to github.com port 443: Operation timed out
fatal: clone of 'https://github.com/apache/thrift' into submodule path '/Users/zepengchen/ClickHouse/contrib/thrift' failed
Failed to clone 'contrib/thrift'. Retry scheduled
Cloning into '/Users/zepengchen/ClickHouse/contrib/yaml-cpp'...
fatal: unable to access 'https://github.com/ClickHouse/yaml-cpp/': Failed to connect to github.com port 443: Operation timed out
fatal: clone of 'https://github.com/ClickHouse/yaml-cpp' into submodule path '/Users/zepengchen/ClickHouse/contrib/yaml-cpp' failed
Failed to clone 'contrib/yaml-cpp'. Retry scheduled
Cloning into '/Users/zepengchen/ClickHouse/contrib/zlib-ng'...
^C
(base) zepengchen@laojiekedeMacBook-Pro build % git submodule update --init
Cloning into '/Users/zepengchen/ClickHouse/contrib/thrift'...
Cloning into '/Users/zepengchen/ClickHouse/contrib/yaml-cpp'...
fatal: unable to access 'https://github.com/ClickHouse/yaml-cpp/': Failed to connect to github.com port 443: Operation timed out
fatal: clone of 'https://github.com/ClickHouse/yaml-cpp' into submodule path '/Users/zepengchen/ClickHouse/contrib/yaml-cpp' failed
Failed to clone 'contrib/yaml-cpp'. Retry scheduled
Cloning into '/Users/zepengchen/ClickHouse/contrib/zlib-ng'...
Cloning into '/Users/zepengchen/ClickHouse/contrib/yaml-cpp'...
Submodule path '../contrib/NuRaft': checked out 'b56784be1aec568fb72aff47f281097c017623cb'
Submodule path '../contrib/abseil-cpp': checked out '215105818dfde3174fe799600bb0f3cae233d0bf'
Submodule path '../contrib/annoy': checked out 'f2ac8e7b48f9a9cf676d3b58286e5455aba8e956'
Submodule path '../contrib/arrow': checked out 'd03245f801f798c63ee9a7d2b8914a9e5c5cd666'
Submodule path '../contrib/aws-c-auth': checked out '30df6c407e2df43bd244e2c34c9b4a4b87372bfb'
Submodule path '../contrib/aws-c-compression': checked out 'b517b7decd0dac30be2162f5186c250221c53aff'
Submodule path '../contrib/aws-c-event-stream': checked out '39bfa94a14b7126bf0c1330286ef8db452d87e66'
Submodule path '../contrib/aws-c-http': checked out '2c5a2a7d5556600b9782ffa6c9d7e09964df1abc'
Submodule path '../contrib/aws-c-mqtt': checked out '882c689561a3db1466330ccfe3b63637e0a575d3'
Submodule path '../contrib/aws-c-s3': checked out 'a41255ece72a7c887bba7f9d998ca3e14f4c8a1b'
Submodule path '../contrib/aws-c-sdkutils': checked out '25bf5cf225f977c3accc6a05a0a7a181ef2a4a30'
Submodule path '../contrib/aws-checksums': checked out '48e7c0e01479232f225c8044d76c84e74192889d'
Submodule path '../contrib/boost': checked out '03d9ec9cd159d14bd0b17c05138098451a1ea606'
Submodule path '../contrib/boringssl': checked out '8061ac62d67953e61b793042e33baf1352e67510'
Submodule path '../contrib/brotli': checked out '63be8a99401992075c23e99f7c84de1c653e39e2'
Submodule path '../contrib/capnproto': checked out 'dc8b50b999777bcb23c89bb5907c785c3f654441'
Submodule path '../contrib/cassandra': checked out 'f4a31e92a25c34c02c7291ff97c7813bc83b0e09'
Submodule path '../contrib/corrosion': checked out 'd9dfdefaa3d9ec4ba1245c7070727359c65c7869'
Submodule path '../contrib/cppkafka': checked out '5a119f689f8a4d90d10a9635e7ee2bee5c127de1'
Submodule path '../contrib/croaring': checked out 'f40ed52bcdd635840a79877cef4857315dba817c'
Submodule path '../contrib/curl': checked out 'c12fb3ddaf48e709a7a4deaa55ec485e4df163ee'
Submodule path '../contrib/cyrus-sasl': checked out 'e6466edfd638cc5073debe941c53345b18a09512'
Submodule path '../contrib/double-conversion': checked out 'cf2f0f3d547dc73b4612028a155b80536902ba02'
Submodule path '../contrib/fast_float': checked out '7eae925b51fd0f570ccd5c880c12e3e27a23b86f'
Submodule path '../contrib/flatbuffers': checked out 'eb3f827948241ce0e701516f16cd67324802bce9'
Submodule path '../contrib/fmtlib': checked out 'b6f4ceaed0a0a24ccf575fab6c56dd50ccf6f1a9'
Submodule path '../contrib/google-benchmark': checked out '2257fa4d6afb8e5a2ccd510a70f38fe7fcdf1edf'
Submodule path '../contrib/googletest': checked out '71140c3ca7a87bb1b5b9c9f1500fea8858cce344'
Submodule path '../contrib/h3': checked out 'c7f46cfd71fb60e2fefc90e28abe81657deff735'
Submodule path '../contrib/icu': checked out 'a56dde820dc35665a66f2e9ee8ba58e75049b668'
Submodule path '../contrib/icudata': checked out 'c8e717892a557b4d2852317c7d628aacc0a0e5ab'
Submodule path '../contrib/idxd-config': checked out 'f6605c41a735e3fdfef2d2d18655a33af6490b99'
Submodule path '../contrib/jemalloc': checked out '41a859ef7325569c6c25f92d294d45123bb81355'
Submodule path '../contrib/libpq': checked out 'e071ea570f8985aa00e34f5b9d50a3cfe666327e'
Submodule path '../contrib/libpqxx': checked out 'a4e834839270a8c1f7ff1db351ba85afced3f0e2'
Submodule path '../contrib/libprotobuf-mutator': checked out 'a304ec48dcf15d942607032151f7e9ee504b5dcf'
Submodule path '../contrib/liburing': checked out 'f5a48392c4ea33f222cbebeb2e2fc31620162949'
Submodule path '../contrib/libuv': checked out '3a85b2eb3d83f369b8a8cafd329d7e9dc28f60cf'
Submodule path '../contrib/libxml2': checked out 'f507d167f1755b7eaea09fb1a44d29aab828b6d1'
Submodule path '../contrib/llvm-project': checked out '4bfaeb31dd0ef13f025221f93c138974a3e0a22a'
Submodule path '../contrib/lz4': checked out '4c9431e9af596af0556e5da0ae99305bafb2b10b'
Submodule path '../contrib/magic_enum': checked out '38f86e4d093cfc9034a140d37de2168e3951bef3'
Submodule path '../contrib/miniselect': checked out 'be0af6bd0b6eb044d1acc4f754b229972d99903a'
Submodule path '../contrib/minizip-ng': checked out 'f3d400e999056ca290998b3fd89cc5a74e4b8b58'
Submodule path '../contrib/msgpack-c': checked out '46684265d50b5d1b062d4c5c428ba08462844b1d'
Submodule path '../contrib/openldap': checked out '8688afe6bc95ebcd20edf4578c536362218cb70a'
Submodule path '../contrib/openssl': checked out '19cc035b6c6f2283573d29c7ea7f7d675cf750ce'
Submodule path '../contrib/protobuf': checked out '6bb70196c5360268d9f021bb7936fb0b551724c2'
Submodule path '../contrib/qpl': checked out 'd75a29d95d8a548297fce3549d21020005364dc8'
Submodule path '../contrib/rapidjson': checked out 'c4ef90ccdbc21d5d5a628d08316bfd301e32d6fa'
Submodule path '../contrib/re2': checked out '13ebb377c6ad763ca61d12dd6f88b1126bd0b911'
Submodule path '../contrib/sentry-native': checked out 'ae10fb8c224c3f41571446e1ed7fd57b9e5e366b'
Submodule path '../contrib/simdjson': checked out '1075e8609c4afa253162d441437af929c29e31bb'
Submodule path '../contrib/snappy': checked out 'fb057edfed820212076239fd32cb2ff23e9016bf'
Submodule path '../contrib/sparsehash-c11': checked out 'cf0bffaa456f23bc4174462a789b90f8b6f5f42f'
Submodule path '../contrib/thrift': checked out '2a93df80f27739ccabb5b885cb12a8dc7595ecdf'
Submodule path '../contrib/wyhash': checked out '991aa3dab624e50b066f7a02ccc9f6935cc740ec'
Submodule path '../contrib/xxHash': checked out '3078dc6039f8c0bffcb1904f81cfe6b2c3209435'
Submodule path '../contrib/xz': checked out '869b9d1b4edd6df07f819d360d306251f8147353'
Submodule path '../contrib/yaml-cpp': checked out '0c86adac6d117ee2b4afcedb8ade19036ca0327d'
Submodule path '../contrib/zlib-ng': checked out '50f0eae1a411764cd6d1e85b3ce471438acd3c1c'
Submodule path '../contrib/zstd': checked out '945f27758c0fd67b636103a38dbf050266c6b90a'
Submodule path '../contrib/yaml-cpp': checked out '0c86adac6d117ee2b4afcedb8ade19036ca0327d'

**Comment by ucasfl** [comment]
It's looks like you don't update and download submodules successfully due to network.

**Comment by rschu1ze** [comment]
> Failed to connect to github.com port 443: Operation timed out

Agree, this looks like a network issue.

Just for reference, here are the steps I use to setup everything needed to compile ClickHouse:
- `git clone https://github.com/ClickHouse/ClickHouse.git`
- `cd ClickHouse`
- `git submodule update --init --recursive`
