### ISSUE TITLE
Is projection related to data volume?

### ISSUE THREAD

**Issue by Bing-dwendwen** [ClickHouse/ClickHouse#48033]
CREATE TABLE mytablebytime (
  id String,
  group_id UInt64,
  value int,
  group_count int,
  capture_time UInt32,
  date Date,
  timestamp UInt64,
  INDEX minmax_capture_time capture_time TYPE minmax GRANULARITY 3
)
ENGINE = ReplacingMergeTree(timestamp)
PARTITION BY date
ORDER BY (capture_time, id);

ALTER TABLE mytablebytime ADD PROJECTION mytablebytime_agg
 (
     SELECT
         id,
         capture_time,
         argMax(group_id, timestamp) As group_id,
         argMax(date, timestamp) As date,
         argMax(value, timestamp) AS value,
         argMax(group_count, timestamp) AS group_count
     GROUP BY capture_time, id
 );

CREATE VIEW mytablebytime_view AS
SELECT
    id,
    capture_time,
    argMax(group_id, timestamp) As group_id,
    argMax(date, timestamp) As date,
    argMax(value, timestamp) AS value,
    argMax(group_count, timestamp) AS group_count
FROM mytablebytime
GROUP BY capture_time, id;

SET allow_experimental_projection_optimization=1, force_optimize_projection=1;

// Now I'm going to insert 200,000 data
INSERT INTO mytablebytime (id, group_id, value, group_count, capture_time, date, timestamp)
SELECT
   concat('group', toString(number)) AS id,
    rand(0) % 100000 As group_id,
    rand() AS value,
    rand() AS group_count,
    toUInt32(toDateTime('2022-01-01 00:00:00') + number) AS capture_time,
    toDate(toDateTime(capture_time)) AS date,
    toUInt64(now()) AS timestamp
FROM numbers(200000)

// The full data query succeeds
select * from mytablebytime_view

// But when I inserted 10 million data
INSERT INTO mytablebytime (id, group_id, value, group_count, capture_time, date, timestamp)
SELECT
   concat('group', toString(number)) AS id,
    rand(0) % 100000 As group_id,
    rand() AS value,
    rand() AS group_count,
    toUInt32(toDateTime('2022-01-01 00:00:00') + number) AS capture_time,
    toDate(toDateTime(capture_time)) AS date,
    toUInt64(now()) AS timestamp
FROM numbers(10000000)

//  the second query went wrong
select * from mytablebytime_view

// failed: No projection is used when allow_experimental_projection_optimization = 1 and force_optimize_projection = 1(PROJECTION_NOT_USED)

**Comment by Bing-dwendwen** [comment]
https://fiddle.clickhouse.com/d025c2f3-d418-4ac4-98d3-e5859feb9474

**Comment by den-crane** [comment]
```
INSERT INTO mytablebytime
...
FROM numbers(200000)

size of the table :
┌─database─┬─table─────────┬─compressed─┬─uncompressed─┬─compr_rate─┬───rows─┬─part_count─┐
│ default  │ mytablebytime │ 3.89 MiB   │ 7.90 MiB     │       2.03 │ 200000 │          3 │
└──────────┴───────────────┴────────────┴──────────────┴────────────┴────────┴────────────┘
```

size of the proj.:
┌─database─┬─table─────────┬─name──────────────┬─compressed─┬─uncompressed─┬─compr_rate─┬───rows─┬─part_count─┐
│ default  │ mytablebytime │ mytablebytime_agg │ 4.74 MiB   │ 14.01 MiB    │       2.95 │ 200000 │          3 │
└──────────┴───────────────┴───────────────────┴────────────┴──────────────┴────────────┴────────┴────────────┘

INSERT INTO mytablebytime
...
FROM numbers(10000000)

size of the table :
┌─database─┬─table─────────┬─compressed─┬─uncompressed─┬─compr_rate─┬─────rows─┬─part_count─┐
│ default  │ mytablebytime │ 198.56 MiB │ 416.93 MiB   │        2.1 │ 10200000 │        128 │
└──────────┴───────────────┴────────────┴──────────────┴────────────┴──────────┴────────────┘

size of the proj.:
┌─database─┬─table─────────┬─name──────────────┬─compressed─┬─uncompressed─┬─compr_rate─┬─────rows─┬─part_count─┐
│ default  │ mytablebytime │ mytablebytime_agg │ 242.05 MiB │ 728.20 MiB   │       3.01 │ 10200000 │        128 │
└──────────┴───────────────┴───────────────────┴────────────┴──────────────┴────────────┴──────────┴────────────┘
```

The projection is bigger than the table. And they have the same number of rows
Clickhouse reads the table, because it needs to read less bytes and process less bytes.

Also projection against ReplacingMergeTree produces incorrect results  https://github.com/ClickHouse/ClickHouse/issues/24778

Also see https://github.com/ClickHouse/ClickHouse/issues/32753
