### ISSUE TITLE
[MaterializedPostgreSQL] Rows don't delete if TABLE OVERRIDE option is used

### ISSUE THREAD

**Issue by joikrex** [ClickHouse/ClickHouse#48039]
We found issue with MaterializedPostgreSQL if use TABLE OVERRIDE option in create database query (without this option all works fine)
If we delete row in PG this row doesn't delete in Clickhouse.
Clickhouse version: 22.10.4.23
PG version: 14.6

Steps to reproduce:

--create table in postgres
CREATE TABLE public.test_table (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	test_date timestamp without time zone NOT NULL,
	test_value int4 NOT NULL,
	CONSTRAINT test_table_pkey PRIMARY KEY (id)
);

--create materializedpostgresql database in clickhouse with table override in test_table
CREATE DATABASE test_repl
ENGINE = MaterializedPostgreSQL('host:port', 'database', 'user', 'password')
SETTINGS materialized_postgresql_tables_list = 'test_table'
TABLE OVERRIDE test_table (PARTITION BY toYYYYMM(test_date));

--insert one row in postgres
INSERT INTO public.test_table (test_date, test_value)
VALUES('2023-03-01', 1);
--row shows in clickhouse

--update row
UPDATE public.test_table
SET  test_value = 2
WHERE id = 1;
--row is updated in clickhouse

--delete row
DELETE FROM public.test_table
WHERE id = 1;

--select row in clickhouse by date
SELECT * 
FROM test_repl.test_table
WHERE test_date = '2023-03-01';
-- row shows

--select row in clickhouse without conditions
SELECT * 
FROM test_repl.test_table;
-- row doesn't show

**Comment by kssenii** [comment]
Hi @joikrex 
It does not reproduce on the recent clickhouse version.
Added integration test of this case in https://github.com/ClickHouse/ClickHouse/pull/57593.
