### ISSUE TITLE
can't drop and select a table on V20.9.2.20

### ISSUE THREAD

**Issue by zhituanchen** [ClickHouse/ClickHouse#48034]
Hi there is a problem:

I execute query :"drop table DWS__DWD_IFACE_INVOKE__INVOKE_COST_TIME__E__1M__RCLMXH;" 
and "SELECT * FROM DWS.DWS__DWD_IFACE_INVOKE__INVOKE_COST_TIME__E__10S__FYYKF9 LIMIT 0, 200"
It is different table.

It's hanging up.
I went to execute "KILL QUERY WHERE query_id ='xxx'". it is invalid. I can't kill it.

**Comment by cangyin** [comment]
please paste the error messages for each SQL statement.

**Comment by den-crane** [comment]
20.9.2.20 is out of support. You need to upgrade to a stable version. Try 23.2.4.
