### ISSUE TITLE
SELECT 1 as ping - takes 3 minutes to finish

### ISSUE THREAD

**Issue by vasyaabr** [ClickHouse/ClickHouse#48043]
**SELECT 1 as ping - takes 171 seconds to finish**

Random queries takes much time to finish, while query_duration_ms is small or near zero. We have examined system.query_log and see folowing:

```
SELECT
    query_start_time,
    event_time,
    event_time - query_start_time AS fullDurationSec,
    round(query_duration_ms / 1000) AS queryDurationSec,
    fullDurationSec - queryDurationSec AS unknownWorkSec
FROM system.query_log
WHERE event_date = today()
ORDER BY unknownWorkSec DESC
LIMIT 10

┌────query_start_time─┬──────────event_time─┬─fullDurationSec─┬─queryDurationSec─┬─unknownWorkSec─┐
│ 2023-03-24 12:34:02 │ 2023-03-24 12:37:23 │             201 │               30 │            171 │
│ 2023-03-24 12:34:01 │ 2023-03-24 12:36:52 │             171 │                0 │            171 │
│ 2023-03-24 12:34:01 │ 2023-03-24 12:36:52 │             171 │                0 │            171 │

```

**How to reproduce**

We can reproduce this behaviour on our system, using raw HTTP requests. From 100 query launches, ~10 comes with additional time, spent for unknown reasons.

**Expected behavior**

event_time - query_start_time = query_duration_ms / 1000 in system.query_log

**Additional context**

ClickHouse server version 22.3.2 revision 54455

trace_log disabled.

query-log example:
[slow_ping_query_log_example.txt](https://github.com/ClickHouse/ClickHouse/files/11077357/slow_ping_query_log_example.txt)

Hardware:
Dell PowerEdge R630
CPU Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
RAM 128 Gb
Swap off
OS Debian 10 ( Linux  5.10.0-0.deb10.1
6-amd64 #1 SMP Debian 5.10.127-2~bpo10+1 (2022-07-28) x86_64 GNU/Linux )
RAID 1 of 6 ssd KINGSTON SEDC500M3840G , total volume  10.477 TB
Network bandwidth 10 Gbit/s
Clickhouse installed as systemd service, neither docker nor any virtualisation is used.

**Comment by vasyaabr** [comment]
@Alex-Cheng is there a way to check this?

**Comment by vasyaabr** [comment]
@tavplubix done with traces. Is it ok, or we can add / change something?
[query_log_data.txt](https://github.com/ClickHouse/ClickHouse/files/11080489/query_log_data.txt)
[trace_data_full.csv.tar.gz](https://github.com/ClickHouse/ClickHouse/files/11080490/trace_data_full.csv.tar.gz)

We inadvertently turned on tracing and a very high tracing frequency on one of the production replicas, and server load turned overwhelming. So don't be surprised that SELECT 1 took 20 seconds to complete. But the problem with extra time reproduced succesfully.

**Comment by tavplubix** [comment]
It was waiting in `ProcessList::insert`:
```
DB::ProcessList::insert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::IAST const*, std::__1::shared_ptr<DB::Context const>)
DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*)
DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&)
DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&)
DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&)
DB::HTTPServerConnection::run()
Poco::Net::TCPServerConnection::start()
Poco::Net::TCPServerDispatcher::run()
Poco::PooledThread::run()
Poco::ThreadImpl::runnableEntry(void*)
```

Of course it should not wait there for that long and it looks like a bug. However, it does not make sense to continue investigation.

> ClickHouse server version 22.3.**2** revision 54455

Sorry, I did not notice that previously. This version is obsolete and you must upgrade. The latest patch version in the 22.3 branch is 22.3.**19**. Patch releases contain important bugfixes and it's highly recommended to upgrade to the newest patch versions withing a branch as soon as it released. 

Moreover, 22.3 is the oldest of the supported branches, and we are going to stop supporting it in a few days (after releasing 23.3)

**Comment by vasyaabr** [comment]
Upgrade to 22.3.19 solved the problem (but added some new ones).
