### ISSUE TITLE
remove log_comment value from Settings column in query_log table

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#48046]
**Describe the issue**
Users can (and will put in log_comment setting some context of that particular query, which is useful for debugging)

But currently it's being doubled in `log_comment` column AND in Settings column (because user define log_comment as setting)

IE double disk usage

**Expected behavior**
No duplication of data.

**Comment by alexey-milovidov** [comment]
I think it's ok for consistency. The settings column contains all the settings - this is good.

**Comment by UnamedRus** [comment]
But, you can set `query_id` for query via http or tcp protocol without any issue.
Can we use the same mechanic for log_comment then?

What the point of features, if they can't be used together? https://github.com/ClickHouse/ClickHouse/issues/48430
