### ISSUE TITLE
Implement the Data Lake Engines on Azure 

### ISSUE THREAD

**Issue by alifirat** [ClickHouse/ClickHouse#48040]
**Use case**

Read Data lakes formats from any cloud providers (AWS, Azure, GCP). 

**Describe the solution you'd like**

Today, it's possible to use the Data Lake Engines on AWS and since the protocol between S3 and GCP is compatible, I'm pretty sure it's possible on GCP but it's not possible from Azure. It would be great to have the existing Data Lake Engines working on  Azure also. To be more precise, we expect to use the Apache Iceberg and / or Delta Lake engines on Azure. 

**Describe alternatives you've considered**

Expect switching to a new technology than ClickHouse, there is no alternative that includes ClickHouse for that.

**Comment by melvynator** [comment]
Will be prioritized in Q3.

**Comment by melvynator** [comment]
https://github.com/ClickHouse/ClickHouse/pull/68210
