### ISSUE TITLE
expose real _pool size in metrics

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#48066]
Pools can be dynamically increased but cannot be decreased.

If a pool decreased from 32 to 8 then
```
server_settings = 8
system.metrics = 6 (Number of active tasks)
```
And 32 -- the real current size of a pool is not visible.

I suggest to expose it i.e. in `system.metrics` as `BackgroundMovePoolSize   │    32 │ Size of BackgroundProcessingPool for moves`

**Comment by filimonov** [comment]
Already implemented in https://github.com/ClickHouse/ClickHouse/pull/47656
