### ISSUE TITLE
How to safely migrate the Zookeeper of ClickHouse to a new cluster?

### ISSUE THREAD

**Issue by henryyan** [ClickHouse/ClickHouse#48087]
The components are installed using Helm Charts, ClickHouse version: 21.12.3.32, and Zookeeper needs to be upgraded from 3.6.2 to 3.8.1 (from bitnami). I have created a ClickHouse cluster that depends on a Zookeeper cluster named test1, and now I want to replace test1 with a Zookeeper cluster named test2. I have tried the following methods (each operation first stops ClickHouse's read and write operations):

1. Shut down the original Zookeeper cluster, keep the PVC, mount the PVC of the original cluster after upgrading the new version of Zookeeper, wait for the Zookeeper cluster to start successfully, and then start the ClickHouse cluster. It prompts that data cannot be written, and an error is reported: *DB::Exception: Table is in readonly mode (zookeeper path: /clickhouse/tables/2/default-tenant-prj/2023-03-20/clickhouse-clusters1/hits). (TABLE_IS_READ_ONLY) (version 21.12.3.32 (official build))*
2. Keep both clusters and use the zkcopy tool to copy the /clickhouse data in Zookeeper to the new Zookeeper cluster
I'm seeking help on how to safely migrate to a new Zookeeper cluster. Or, can ClickHouse automatically write data back to Zookeeper on the new Zookeeper cluster, like Kafka?

**Comment by cangyin** [comment]
how about `kubectl edit <zookeeper-deployment>` and replace zookeeper 3.6.2 image with zookeeper 3.8.1 ?

I think that should just work. according to [apache zookeeper release notes](https://zookeeper.apache.org/releases.html#:~:text=ZooKeeper%20clients%20from%203.5.x%20onwards%20are%20fully%20compatible%20with%203.8.x%20servers.):

> ZooKeeper clients from 3.5.x onwards are fully compatible with 3.8.x servers.

**Comment by henryyan** [comment]
> how about `kubectl edit <zookeeper-deployment>` and replace zookeeper 3.6.2 image with zookeeper 3.8.1 ?
> 
> I think that should just work. according to [apache zookeeper release notes](https://zookeeper.apache.org/releases.html#:~:text=ZooKeeper%20clients%20from%203.5.x%20onwards%20are%20fully%20compatible%20with%203.8.x%20servers.):
> 
> > ZooKeeper clients from 3.5.x onwards are fully compatible with 3.8.x servers.

My requirement is not to upgrade the zookeeper version in place, but to switch from one old cluster to another, so I want to migrate zookeeper node data to new cluster.

**Comment by cangyin** [comment]
we can continue on the first method.

1. get all readonly tables:
```sql
SELECT
    hostname() AS host,database,table,is_session_expired,is_readonly,future_parts,
    zookeeper_exception,last_queue_update_exception
FROM clusterAllReplicas('{cluster}',system.replicas) WHERE is_readonly ORDER BY host
```
2. if there're just a few of readonly tables, for each readonly table, manually do:

delete zookeeper node for the Replicated*MergeTree table, and

```sql
SYSTEM RESTART REPLICA  <you -table>
SYSTEM RESTORE REPLICA  <you -table>
```

ref: https://altinity.com/blog/a-new-way-to-restore-clickhouse-after-zookeeper-metadata-is-lost

**Comment by henryyan** [comment]
> we can continue on the first method.
> 
> 1. get all readonly tables:
> 
> ```sql
> SELECT
>     hostname() AS host,database,table,is_session_expired,is_readonly,future_parts,
>     zookeeper_exception,last_queue_update_exception
> FROM clusterAllReplicas('{cluster}',system.replicas) WHERE is_readonly ORDER BY host
> ```
> 
> 2. if there're just a few of readonly tables, for each readonly table, manually do:
> 
> delete zookeeper node for the Replicated*MergeTree table, and
> 
> ```sql
> SYSTEM RESTART REPLICA  <you-table>
> SYSTEM RESTORE REPLICA  <you-table>
> ```
> 
> ref: https://altinity.com/blog/a-new-way-to-restore-clickhouse-after-zookeeper-metadata-is-lost

Ok, so I'll verify that.
Thanks

**Comment by alexey-milovidov** [comment]
Option 2 cannot work - the `zkcopy` tool is non-functional and harmful: https://github.com/ksprojects/zkcopy/issues/15
