### ISSUE TITLE
ClickHouse v23.2.4.12 can't start by systemctl on CentOS 7.9, but use service start ok

### ISSUE THREAD

**Issue by gohonsen** [ClickHouse/ClickHouse#48090]
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**
The os version is CentOS 7.9 
Install clickhouse 23.2.4.12 by  use `yum install -y clickhouse-server clickhouse-client`

**The actual result**
After install, I run `systemctl start clickhouse-server` to start clickhouse server, but failed; But use `service clickhouse-server start ` or `/etc/init.d/clickhouse-server start ` can start successfully. 

The step such as:

`systemctl start clickhouse-server.service`

> Job for clickhouse-server.service failed because a timeout was exceeded. See "systemctl status clickhouse-server.service" and "journalctl -xe" for details.

`systemctl status clickhouse-server.service`

> clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
>    Loaded: loaded (/usr/lib/systemd/system/clickhouse-server.service; enabled; vendor preset: disabled)
>    Active: activating (auto-restart) (Result: timeout) since 一 2023-03-27 20:44:19 CST; 7s ago
>   Process: 28637 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=%t/%p/%p.pid (code=killed, signal=TERM)
>  Main PID: 28637 (code=killed, signal=TERM)
> systemd[1]: Failed to start ClickHouse Server (analytic DBMS for big data).
> systemd[1]: Unit clickhouse-server.service entered failed state.
> systemd[1]: clickhouse-server.service failed.

`cat /usr/lib/systemd/system/clickhouse-server.service`

> [Unit]
> Description=ClickHouse Server (analytic DBMS for big data)
> Requires=network-online.target
> #NOTE: that After/Wants=time-sync.target is not enough, you need to ensure
> #that the time was adjusted already, if you use systemd-timesyncd you are
> #safe, but if you use ntp or some other daemon, you should configure it
> #additionaly.
> After=time-sync.target network-online.target
> Wants=time-sync.target
> 
> [Service]
> Type=notify
> 
> #NOTE: we leave clickhouse watchdog process enabled to be able to see OOM/SIGKILL traces in clickhouse-server.log files.
> #If you wish to disable the watchdog and rely on systemd logs just add "Environment=CLICKHOUSE_WATCHDOG_ENABLE=0" line.
> User=clickhouse
> Group=clickhouse
> Restart=always
> RestartSec=30
> #Since ClickHouse is systemd aware default 1m30sec may not be enough
> TimeoutStartSec=infinity
> #%p is resolved to the systemd unit name
> RuntimeDirectory=%p
> ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=%t/%p/%p.pid
> #Minus means that this file is optional.
> EnvironmentFile=-/etc/default/%p
> #Bring back /etc/default/clickhouse for backward compatibility
> EnvironmentFile=-/etc/default/clickhouse
> LimitCORE=infinity
> LimitNOFILE=500000
> CapabilityBoundingSet=CAP_NET_ADMIN CAP_IPC_LOCK CAP_SYS_NICE CAP_NET_BIND_SERVICE
> 
> [Install]
> #ClickHouse should not start from the rescue shell (rescue.target).
> WantedBy=multi-user.target

`service clickhouse-server start`

>  chown -R clickhouse: '/var/run/clickhouse-server/'
> Will run sudo -u 'clickhouse' /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon
> Waiting for server to start
> Waiting for server to start
> Server started

`/etc/init.d/clickhouse-server start`

>  chown -R clickhouse: '/var/run/clickhouse-server/'
> Will run sudo -u 'clickhouse' /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon
> Waiting for server to start
> Waiting for server to start
> Server started

Then I modify /usr/lib/systemd/system/clickhouse-server.service  _**Type=notify**_ to _**Type=simple**_,  clickhouse server start successfully, but there's nothing display after command finished.

`systemctl start clickhouse-server`
`ps -ef | grep click`
clickho+  3985     1  1 13:27 ?        00:00:00 clickhouse-watchdog        --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
clickho+  3986  3985 49 13:27 ?        00:00:00 /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid

**Comment by den-crane** [comment]
replace `TimeoutStartSec=infinity` with `TimeoutStartSec=0`

duplicate https://github.com/ClickHouse/ClickHouse/issues/47717 https://github.com/ClickHouse/ClickHouse/issues/47293
