### ISSUE TITLE
mutation stuck and can't be killed

### ISSUE THREAD

**Issue by skgmtmy** [ClickHouse/ClickHouse#48091]
i have a table(engine=mergeTree), several days ago, all new mutation can't be executed. then i want to select from system.mutations, the query just stuck and even i kill the query, then i can't query from the table, if i kill all mutation for the table, the cpu cost of clickhouse will be very high, and i have to restart clickouse-server. so, what can i do now.

**Comment by skgmtmy** [comment]
clickhouse-server version is 21.12.2

**Comment by tavplubix** [comment]
> clickhouse-server version is 21.12.2

This version is obsolete. It does not contain important bugfixes. You have to upgrade.

Also provided information is not enough to help (we need steps to reproduce/a list of queries, server logs, stacktraces, etc)
