### ISSUE TITLE
Crash in EXPLAIN PIPELINE graph for StorageMerge

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#48100]
https://s3.amazonaws.com/clickhouse-test-reports/47986/f6de2160419b2f0111a59deb2dc535cee90dceff/fuzzer_astfuzzerubsan/report.html

```sql
DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS merge1;

CREATE TABLE foo (`Id` Int32, `Val` Int32) ENGINE = MergeTree ORDER BY Id;
INSERT INTO foo SELECT number, number FROM numbers(100);

CREATE TABLE merge1 AS foo ENGINE = Merge(currentDatabase(), '^foo');

EXPLAIN PIPELINE graph = 1, compact = 1 SELECT * FROM merge1;
```

We have destroyed plan for reading from child SourceStep in StorageMerge, but use pointer to it in `printPipelineCompact`.

**Comment by evillique** [comment]
https://github.com/ClickHouse/ClickHouse/issues/48094
https://github.com/ClickHouse/ClickHouse/issues/48053
