### ISSUE TITLE
how to restrict query access to count() only ?

### ISSUE THREAD

**Issue by tahayk** [ClickHouse/ClickHouse#48113]
Is it possible to create a user that can run `count` queries only without reading the data (without `WHERE` or `GROUP BY`) ? 

```sql
SELECT count() FROM access_test.tab1;
```

the only workaround I found so far is to allow the user to access 1 column:
```sql
CREATE USER IF NOT EXISTS 'user'
    IDENTIFIED WITH SHA256_PASSWORD BY 'mypassword';

CREATE ROLE 'restricted-role';
GRANT 'restricted-role' TO 'user';
GRANT SELECT (_timestamp) ON access_test.tab1 TO 'restricted-role';
```

**Comment by den-crane** [comment]
no such feature. Probably should be solved by implementing views with owning.
