### ISSUE TITLE
Does catboostEvaluate work for CatBoostRegressor?

### ISSUE THREAD

**Issue by oleg-savko** [ClickHouse/ClickHouse#48117]
`catboostEvaluate` work fine for classification model `CatBoostClassifier`, but when I try to evaluate it for regression `CatBoostRegressor`, its execute without errors, but numbers doesn't match if model execute in python.

Does it should work or it not supported?

@rschu1ze  do you know?

**Comment by rschu1ze** [comment]
Tbh, I hardly know the specifics of catboost, and that includes "Classifier" vs. "Regressor" models. Perhaps there is a rounding/casting error. If you provide me a repro, then I could try to look closer.
