### ISSUE TITLE
partition replace

### ISSUE THREAD

**Issue by elau7e** [ClickHouse/ClickHouse#48149]
Hello!
How can the be executed following query?
alter table target_tbl replace partition (
    select top 1 partition from `system`.parts where table in ('tbl_cache') /*or any question returns partition name */
) from tbl_cache
;
This is required to complete the next case.
I want to implement the following behavior of system tables: target_tbl and tbl_cache. Tables has identical structure and partitioned by "actuality" (Data). Everyday a new portion of data is placed in target_tbl. One partition is formed and named like 'YYYY-MM-DD'. Fore example '2023-03-29'. Further i want add single partition of tbl_cache into target_tbl as new if the partition is not there or replace existing one. 
I think best way for this is command **alter table ... replace ...** . And i want do this command independent from partition name. It is possible?
Maybe there is another way to implement a similar scenario without explicitly specifying the date?

Thank you!

**Comment by den-crane** [comment]
No. Such alters are not supported.
You can generate an SQL script:

```sql
 
select 'alter table target_tbl replace partition '||partition||' from tbl_cache;' 
from ( 
select top 1 partition from system.parts where table in ('tbl_cache') /*or any question returns partition name */
)
;
```
