### ISSUE TITLE
23.3 (master) - some changes in max_bytes_before_external_group_by

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#48176]
```
# query 1
Select CAST(number % 65536, 'Nullable(UInt16)' ) as my_key, uniqExact(number) from numbers_mt(50000000) GROUP BY my_key FORMAT Null SETTINGS max_bytes_before_external_group_by=10000;

# query 2
Select CAST(number % 65536, 'UInt16' ) as my_key, uniqExact(number) from numbers_mt(50000000) GROUP BY my_key FORMAT Null SETTINGS max_bytes_before_external_group_by=10000;
```

(the only difference is the data type of `my_key`)

### 23.2

query 1 with Nullable(UInt16) => max_bytes_before_external_group_by works
query 2 with UInt16           => max_bytes_before_external_group_by does not work

### 23.3 (master)

query 1 with Nullable(UInt16) => max_bytes_before_external_group_by does not work
query 2 with UInt16           => max_bytes_before_external_group_by does not work

Expectation - that it should work always once the memory usage get higher.

**Comment by nickitat** [comment]
external aggregation is used only after we converted aggregation to two-level. previously `nullable_keys128` was used and now `nullable_key16` is used thanks to this pr: #45772. `nullable_key16` is not convertible to two-level.
imo current behaviour is the right one.
