### ISSUE TITLE
Using SELECT inside arrayMap() function

### ISSUE THREAD

**Issue by derstiff** [ClickHouse/ClickHouse#48191]
I have a string with comma-separated `id`s (example: `'123,456,789'`) and I need to replace each of that id with it's `name` from another table (with fields `id (Int32), name (String)`), so this `'123,456,789'` transforms to this - `'nameA,nameB,nameC'`.

I tried the most naive approach:

```sql
SELECT
   arrayMap(x -> (SELECT name FROM tableB WHERE id = toInt32(x)),
            splitByChar(',', '123,456,789'));
```

But it doesn't work at all: `Missing columns: 'x' while processing query`.

What am I doing wrong?

**Comment by den-crane** [comment]
It's a correlated subquery. They are not supported.
You can use a dictionary or JOIN.

Example with dictionary:

```sql

create  table  tableA ( s String ) 
Engine = Memory as select '123,456,789';




create  table  tableB ( id Int32, name String ) 
Engine = Memory as 
select * from values((123,'nameA'),(456, 'nameB'),(789, 'nameC'));



CREATE DICTIONARY tableB_dict ( id Int32, name String ) 
PRIMARY KEY id SOURCE(CLICKHOUSE(TABLE tableB )) 
LIFETIME(MIN 0 MAX 0) LAYOUT(HASHED());



SELECT
   arrayMap(x -> dictGet('tableB_dict', 'name', toUInt64(x)),
            splitByChar(',', s))
from tableA

['nameA','nameB','nameC']
```
https://fiddle.clickhouse.com/ccd837f5-83f5-4a1b-8568-4a74680eab40
