### ISSUE TITLE
0 elements of column line when executing vertical merge

### ISSUE THREAD

**Issue by JingYanchao** [ClickHouse/ClickHouse#48217]
> You have to provide the following information whenever possible.
I find this error log in my system,  but I can not replay it, when I analyze the stream I find this should not happen,  that's confuse me
Can someone help to give an explain
my clickhouse version is 22.8.8.3
By the way: the column seem always to be Int64 type

ERROR LOG:

Cannot fetch required block. Source 0: While executing ColumnGathererTransform. (RECEIVED_EMPTY_DATA), Stack trace (when copying this message, always include the lines below):

DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 49. DB::Exception: Written 0 elements of column line, but 12416311 rows of PK columns. (LOGICAL_ERROR), Stack trace (when copying this message, always include 

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
22.8.8.3 is obsolete.
Upgrade to 22.8.15.23

**Comment by JingYanchao** [comment]
> 22.8.8.3 is obsolete. Upgrade to 22.8.15.23

Thanks a lot,  I will upgrade my clickhouse.  Could you please tell me the fix merge request. Thanks a lot
