### ISSUE TITLE
Increase precision of query_start_time in query_thread_log table

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#4821]
**Use case**

Better visibility into query thread scheduling.

**Describe the solution you'd like**
Add another column, ie query_start_time_microseconds_delta that will record microsecond part of query_start_time.

**Comment by alexey-milovidov** [comment]
> query_start_time_microseconds

I prefer this variant (separate column with microseconds part).

**Comment by alexey-milovidov** [comment]
I prefer this field in both query_log and query_thread_log for consistency.

**Comment by bharatnc** [comment]
@nvartolomei I think this issue can be closed. This was implemented via #14252 and the `system.query_log` and `system.query_thread_log` tables should have `query_start_time_microseconds` fields containing the `microseconds` resolution.

**Comment by nvartolomei** [comment]
@bharatnc thanks!

**Comment by bharatnc** [comment]
Just to note that relevant changes for this feature can be found addressed by both #14252 and #14831.

**Comment by bharatnc** [comment]
> @nvartolomei I think this issue can be closed. This was implemented via #14252 and the `system.query_log` and `system.query_thread_log` tables should have `query_start_time_microseconds` fields containing the `microseconds` resolution.

Just to note that relevant changes for this feature is addressed by both #14252 and #14831.
