### ISSUE TITLE
deduplicaton in ReplacingMergeTree has no effect on the materialized view stored in a SummingMergeTree table

### ISSUE THREAD

**Issue by acmeguy** [ClickHouse/ClickHouse#48229]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I have data streaming into a simple ReplacingMergeTree table. A materialised view also selects from it into a SummingMergeTree table with almost the same structure. (Using: CREATE MATERIALIZED VIEW src TO agg_table AS)

Sometimes the same data arrives twice. 
The main ReplacingMergeTree table handles that beautifully. 

The materialized view is correctly updated for single inserts, but duplicate inserts are accumulated/aggregated in the SummingMergeTree table, even though the duplicates are removed from the source table.

This means that number in the materialized view is off by the number of duplicate rows and their values.

**How to reproduce**
ClickHouse 2.32.4.12

**Expected behaviour**
When records are de-duplicated, then a "negated row" or a "delta row" needs to be sent into the materialized to avoid double counting.

**Comment by den-crane** [comment]
by design https://clickhouse.com/blog/using-materialized-views-in-clickhouse

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by den-crane** [comment]
Yes, it's by design. MatView is not aware about the source table engine. It intercepts data from the inserts and never reads the source table. Moreover the source table can be always empty if for example it utilize Engine = Null.

**Comment by den-crane** [comment]
ChatGPT: Whenever new data is inserted into the source table, the materialized view is updated automatically. However, the materialized view is not directly connected to the source table's engine and does not actively read from it.

Instead, the materialized view "listens" for insert events on the source table and captures the data that is being inserted. This means that even if the source table is empty or has a different engine type (such as a "Null" engine), the materialized view can still be updated as long as new data is being inserted into the source table.

**Comment by acmeguy** [comment]
I understand, I think. I just find it massively disappointing that a trigger for the MV Insert is done before the main table engine has "validated" the record or collapsed it with an existing record. 

Are there easy workarounds for this or a pattern that would not create unusable MVs when dealing with duplicate data?

**Comment by acmeguy** [comment]
In other words. The MV insert triggers seem to be the original insert statements rather than - in fact - an insert trigger for a fully processed insert by the source table engine. 

Both would work for the null table engine, assuming it would create a record-inserted trigger for every addition for the table.

Please let me know if there is a workaround known for this.
