### ISSUE TITLE
Add statistical aggregate function `kolmogorovSmirnovTest`

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#48228]
**Use case**

https://en.wikipedia.org/wiki/Kolmogorov%E2%80%93Smirnov_test

This type of statistical test is useful to check the equality of two distributions. In addition it can be easily modified to check whether a sample comes from normal distribution by performing the test against a normally distributed sample. (Normal distribution is just an example, you can perform a test against sample from any distribution).

Previously there was an attempt https://github.com/ClickHouse/ClickHouse/pull/37873 to add a Shapiro-Wilk test for normality, but it has one very big disadvantage - it works only for relatively small samples (< 2500), which it not applicable for ClickHouse use-case.

**Describe the solution you'd like**

Take a look how `welchTTest` or `studentTTest` are implemented. 

**Describe alternatives you've considered**

As an alternative `andersonDarling` test could be also implemented.

**Comment by FFFFFFFHHHHHHH** [comment]
KolmogorovSmirnovTest need to sort the two samples. Can I save the all row data in aggreagtefunction-data sort at last? Whether it will cause OOM, or let's say there's a lot of duplication in the sample to use Bucket sort.

**Comment by ucasfl** [comment]
> KolmogorovSmirnovTest need to sort the two samples. Can I save the all row data in aggreagtefunction-data to sort at last? Whether it will cause OOM, or let's say there's a lot of duplication in the sample to use Bucket sort.

You can check `AggregateFunctionWindowFunnel.h` or `AggregateFunctionIntervalLengthSum.h` if you need keep the data be sorted at last.

**Comment by FFFFFFFHHHHHHH** [comment]
> > KolmogorovSmirnovTest need to sort the two samples. Can I save the all row data in aggreagtefunction-data to sort at last? Whether it will cause OOM, or let's say there's a lot of duplication in the sample to use Bucket sort.
> 
> You can check `AggregateFunctionWindowFunnel.h` or `AggregateFunctionIntervalLengthSum.h` if you need keep the data be sorted at last.

OK, I get it. I'd like to have a try. @nikitamikhaylov
