### ISSUE TITLE
reinterpret support for complex types: Array(UInt32) and others

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#48240]
**Use case**

decode uniqExact state in order to extract source data or Hash of source data (for Strings)
(IE replace uniqExact in AggregatingMergeTree table with approx aggregate function)

**Describe the solution you'd like**

```
SELECT reinterpret(CAST(uniqExactState(CAST(arrayJoin([127000, 10, 3123891283]), 'UInt32')), 'String'), 'Array(UInt32)')

┌─pipe_uint32(uniqExactState(CAST(arrayJoin([127000, 10, 3123891283]), 'UInt32')))─┐
│ [10,127000,3123891283]                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘

```

**Describe alternatives you've considered**

```
<yandex>
  <function>
    <type>executable</type>
    <execute_direct>0</execute_direct>
    <name>pipe_uint32</name>
    <return_type>Array(UInt32)</return_type>
    <argument>
      <type>String</type>
    </argument>
    <format>RowBinary</format>
    <command>cat</command>
    <send_chunk_header>0</send_chunk_header>
  </function>
</yandex>

SELECT pipe_uint32(uniqExactState(CAST(arrayJoin([127000, 10, 3123891283]), 'UInt32')))

┌─pipe_uint32(uniqExactState(CAST(arrayJoin([127000, 10, 3123891283]), 'UInt32')))─┐
│ [10,127000,3123891283]                                                           │
└──────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
The Array data type is not represented by a single continuous chunk in memory, and implementation of `reinterpret` will be unnatural.

**Comment by UnamedRus** [comment]
Ok, any other variant which will allow you to convert between any combination of data types?

It's quite common, when you need to manipulate with column types for aggregate states, and currently you can't do that, and it's dumb.

You always need to use some awful workarounds because states for: quantilesTDigestIfState, quantilesTDigestState, quantileTDigestState, quantilesTDigestIfState(0.1), quantilesTDigestIfState(0.3,0.4) are compatible, but you can't just easily convert between them.

**Comment by amosbird** [comment]
> You always need to use some awful workarounds because states for: quantilesTDigestIfState, quantilesTDigestState, quantileTDigestState, quantilesTDigestIfState(0.1), quantilesTDigestIfState(0.3,0.4) are compatible, but you can't just easily convert between them.

It's doable now, with simple CAST.

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/pull/83399
https://fiddle.clickhouse.com/1b905d70-a40e-4a8c-a238-f72c01c7af1d

```
SELECT reinterpret(substr(CAST(uniqExactState(CAST(arrayJoin([127000, 10, 3123891283]), 'UInt32')), 'String'),2), 'Array(UInt32)')
[10,127000,3123891283]
```
