### ISSUE TITLE
Missing functions in system.functions

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#48260]
I was expecting to see every built-in function to be presented in `system.functions`.
However there are some functions like `date_add`, `timestamp_sub`, `timestamp_add` missing.

https://fiddle.clickhouse.com/a028f696-69fa-4192-842e-d5c9ba751a34
```sql
SELECT name 
FROM system.functions 
WHERE name ilike 'timestamp%';

-- empty resultset
```

**Comment by evillique** [comment]
`date_add` and `timestamp_add` are aliases for `plus` function, `timestamp_sub` - for function `minus`.

**Comment by ramazanpolat** [comment]
Thanks for clarification @evillique.

I still think that those functions need to be present in `system.functions` because they already exist in ClickHouse documentation.
