### ISSUE TITLE
clickhouse restart repeatly when start kafka engine 

### ISSUE THREAD

**Issue by windy629** [ClickHouse/ClickHouse#48268]
my clickhouse version is 22.8.5.29. server os is centos 7.9.2009
when i stop clickhouse server : systemctl stop clickhouse-server, and then reboot my server.
and  systemctl start clickhouse-server.
the clickhouse server restart repeatly. the error log is 

2023.03.30 23:45:01.969457 [ 4001 ] {} <Fatal> BaseDaemon: ########################################
2023.03.30 23:45:01.969509 [ 4001 ] {} <Fatal> BaseDaemon: (version 22.8.5.29 (official build), build id: 92504ACA0B8E2267) (from thread 3416) (no query) Received signal Illegal instruction (4)
2023.03.30 23:45:01.969523 [ 4001 ] {} <Fatal> BaseDaemon: Illegal operand.
2023.03.30 23:45:01.969546 [ 4001 ] {} <Fatal> BaseDaemon: Stack trace: 0x1851741b 0xd876d60 0xd8964e1 0x13c12e47 0x13c1373d 0x13c14be9 0x148a7964 0x15de45fc 0x11bf12f0 0x15bedbc9 0x15c0db4a 0x15c020bb 0x15c01288 0x15c1209d 0x15e72d2b 0x15de39b8 0x15de3539 0x15de2ff8 0x15c0db4a 0x15c020bb 0x15c01019 0x15c00e1d 0x15bff9ec 0x14219cdd 0x14217d7f 0x13e3e858 0x13e41136 0x13e41e6c 0xa487348 0xa48a55d 0x7ff81d007ea5 0x7ff81ccfe9fd
2023.03.30 23:45:01.969598 [ 4001 ] {} <Fatal> BaseDaemon: 2. simdjson::haswell::implementation::create_dom_parser_implementation(unsigned long, unsigned long, std::__1::unique_ptr<simdjson::internal::dom_parser_implementation, std::__1::default_delete<simdjson::internal::dom_parser_implementation> >&) const @ 0x1851741b in /usr/bin/clickhouse
2023.03.30 23:45:01.969613 [ 4001 ] {} <Fatal> BaseDaemon: 3. ? @ 0xd876d60 in /usr/bin/clickhouse
2023.03.30 23:45:01.969628 [ 4001 ] {} <Fatal> BaseDaemon: 4. DB::ExecutableFunctionJSON<DB::NameJSONExtractString, DB::JSONExtractStringImpl>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xd8964e1 in /usr/bin/clickhouse
2023.03.30 23:45:01.969643 [ 4001 ] {} <Fatal> BaseDaemon: 5. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13c12e47 in /usr/bin/clickhouse
2023.03.30 23:45:01.969660 [ 4001 ] {} <Fatal> BaseDaemon: 6. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13c1373d in /usr/bin/clickhouse
2023.03.30 23:45:01.969670 [ 4001 ] {} <Fatal> BaseDaemon: 7. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x13c14be9 in /usr/bin/clickhouse
2023.03.30 23:45:01.969680 [ 4001 ] {} <Fatal> BaseDaemon: 8. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool) const @ 0x148a7964 in /usr/bin/clickhouse
2023.03.30 23:45:01.969705 [ 4001 ] {} <Fatal> BaseDaemon: 9. DB::ExpressionTransform::transform(DB::Chunk&) @ 0x15de45fc in /usr/bin/clickhouse
2023.03.30 23:45:01.969724 [ 4001 ] {} <Fatal> BaseDaemon: 10. DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x11bf12f0 in /usr/bin/clickhouse
2023.03.30 23:45:01.969733 [ 4001 ] {} <Fatal> BaseDaemon: 11. DB::ISimpleTransform::work() @ 0x15bedbc9 in /usr/bin/clickhouse
2023.03.30 23:45:01.969748 [ 4001 ] {} <Fatal> BaseDaemon: 12. DB::ExecutionThreadContext::executeTask() @ 0x15c0db4a in /usr/bin/clickhouse
2023.03.30 23:45:01.969756 [ 4001 ] {} <Fatal> BaseDaemon: 13. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15c020bb in /usr/bin/clickhouse
2023.03.30 23:45:01.969764 [ 4001 ] {} <Fatal> BaseDaemon: 14. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x15c01288 in /usr/bin/clickhouse
2023.03.30 23:45:01.969772 [ 4001 ] {} <Fatal> BaseDaemon: 15. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x15c1209d in /usr/bin/clickhouse
2023.03.30 23:45:01.969782 [ 4001 ] {} <Fatal> BaseDaemon: 16. DB::ExecutingInnerQueryFromViewTransform::onGenerate() @ 0x15e72d2b in /usr/bin/clickhouse
2023.03.30 23:45:01.969791 [ 4001 ] {} <Fatal> BaseDaemon: 17. ? @ 0x15de39b8 in /usr/bin/clickhouse
2023.03.30 23:45:01.969797 [ 4001 ] {} <Fatal> BaseDaemon: 18. ? @ 0x15de3539 in /usr/bin/clickhouse
2023.03.30 23:45:01.969804 [ 4001 ] {} <Fatal> BaseDaemon: 19. DB::ExceptionKeepingTransform::work() @ 0x15de2ff8 in /usr/bin/clickhouse
2023.03.30 23:45:01.969813 [ 4001 ] {} <Fatal> BaseDaemon: 20. DB::ExecutionThreadContext::executeTask() @ 0x15c0db4a in /usr/bin/clickhouse
2023.03.30 23:45:01.969820 [ 4001 ] {} <Fatal> BaseDaemon: 21. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15c020bb in /usr/bin/clickhouse
2023.03.30 23:45:01.969829 [ 4001 ] {} <Fatal> BaseDaemon: 22. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x15c01019 in /usr/bin/clickhouse
2023.03.30 23:45:01.969836 [ 4001 ] {} <Fatal> BaseDaemon: 23. DB::PipelineExecutor::execute(unsigned long) @ 0x15c00e1d in /usr/bin/clickhouse
2023.03.30 23:45:01.969845 [ 4001 ] {} <Fatal> BaseDaemon: 24. DB::CompletedPipelineExecutor::execute() @ 0x15bff9ec in /usr/bin/clickhouse
2023.03.30 23:45:01.969853 [ 4001 ] {} <Fatal> BaseDaemon: 25. DB::StorageKafka::streamToViews() @ 0x14219cdd in /usr/bin/clickhouse
2023.03.30 23:45:01.969862 [ 4001 ] {} <Fatal> BaseDaemon: 26. DB::StorageKafka::threadFunc(unsigned long) @ 0x14217d7f in /usr/bin/clickhouse
2023.03.30 23:45:01.969869 [ 4001 ] {} <Fatal> BaseDaemon: 27. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13e3e858 in /usr/bin/clickhouse
2023.03.30 23:45:01.969879 [ 4001 ] {} <Fatal> BaseDaemon: 28. DB::BackgroundSchedulePool::threadFunction() @ 0x13e41136 in /usr/bin/clickhouse
2023.03.30 23:45:01.969885 [ 4001 ] {} <Fatal> BaseDaemon: 29. ? @ 0x13e41e6c in /usr/bin/clickhouse
2023.03.30 23:45:01.969897 [ 4001 ] {} <Fatal> BaseDaemon: 30. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa487348 in /usr/bin/clickhouse
2023.03.30 23:45:01.969906 [ 4001 ] {} <Fatal> BaseDaemon: 31. ? @ 0xa48a55d in /usr/bin/clickhouse
2023.03.30 23:45:01.969921 [ 4001 ] {} <Fatal> BaseDaemon: 32. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2023.03.30 23:45:01.969935 [ 4001 ] {} <Fatal> BaseDaemon: 33. clone @ 0xfe9fd in /usr/lib64/libc-2.17.so

 it seems kafka enging cause to restart.
when I drop the all the MATERIALIZED VIEW for kafka source to target table.
the clickhouse server can start success. But when I recreate the  MATERIALIZED VIEW.
the clickhouse restart repeatly again.
I don't know what is going on. who can help me to solve the problem?

**Comment by windy629** [comment]
I have reproduce the error. when I execute 
select JSONExtractString(msg,'agentId') from normal_dt limit 1;
the error reproduce again. It will make clickhouse server restart.
what is wrong with JSONExtractString ?

**Comment by windy629** [comment]
before I restart the server . I upgrade the linux kernel 
from 
3.10.0-1160.15.2.el7.x86_64
to
6.2.8-1.el7.elrepo.x86_64

It is ok before kernel upgrade. Does the clickhouse conflict with some linux kernel?

**Comment by tavplubix** [comment]
> Received signal Illegal instruction (4)
> simdjson

Seems like your CPU does not support some instruction sets

**Comment by windy629** [comment]
I have solved this problem. After upgrade kernel, the CPU does not support avx. JSONExtractString function can't work.
When I downgrade kernel to 6.0.0.1, it works. Thks.
