### ISSUE TITLE
Arrow malformed LowCardinality dictionaries: ArrowIndexError

### ISSUE THREAD

**Issue by kcajf** [ClickHouse/ClickHouse#48275]
```
ClickHouse server version 23.2.4 revision 54461
```

I am making HTTP query requests to clickhouse with `FORMAT Arrow` or `FORMAT ArrowStream`. When I enable the setting `output_format_arrow_low_cardinality_as_dictionary=1` and query `LowCardinality(String)` columns, I often see errors like `ArrowIndexError: Index 5 out of bounds` when decoding the arrow data using pyarrow. These errors always go away when I remove `output_format_arrow_low_cardinality_as_dictionary=1`

I haven't been able to build a reproducible small example of this, but I consistently see it on large real-world tables.

**Comment by kcajf** [comment]
I've also discovered with testing now that the output of `output_format_arrow_low_cardinality_as_dictionary=1` is non-deterministic. Re-running the same query sometimes produces a valid arrow response and sometimes not. It also seems like if the returned row count is smaller, it is more likely to give a valid response.

**Comment by Avogar** [comment]
It would be great if you can try to create a reproducible example. You can use your table, but with obfuscated data. Or you can tell me the structure of your table and the approximate number of rows in it, so I will try to reproduce it.

**Comment by Avogar** [comment]
And what kind of query do you have? Is it just `select` from a table or something more comples? Do you use `Merge` table engine?

**Comment by Avogar** [comment]
Newermind, I undrestood what is the problem. We use the dictionary from the LowCardinality column from the first block of data. But it is not guaranteed that the column from the next block will have the same dictionary. So, we need to constract dictionary on each block. Thanks for your report, I will fix it and backport to supported versions.

**Comment by kcajf** [comment]
Thanks @Avogar - I'm glad you were able to spot the problem - I was finding it difficult to reproduce, presumably because my dummy data was not hitting this case.
