### ISSUE TITLE
Clickhouse every 30 Seconds execute a SQL and report error for more than 3 months

### ISSUE THREAD

**Issue by DingZhengCN** [ClickHouse/ClickHouse#48319]
3 month ago, I use Clickhouse version:21.7, I've found a error log like :

```
2023.04.02 04:44:57.638053 [ 9347 ] {2966c181-e7e8-41d3-8c87-0a99e0ca12d6} <Error> executeQuery: Code: 252. DB::Exception: Too many partitions for single INSERT block (more than 5000). The limit is controlled by 'max_partitions_per_insert_block' setting. Large number of partitions is a common misconception. It will lead to severe negative performance impact, including slow server startup, slow INSERT queries and slow SELECT queries. Recommended total number of partitions for a table is under 1000..10000. Please note, that partitioning is not intended to speed up SELECT queries (ORDER BY key is sufficient to make range queries fast). Partitions are intended for data manipulation (DROP PARTITION, etc). (TOO_MANY_PARTS) (version 23.2.4.12 (official build)) (from [::ffff:10.0.2.188]:45126) (in query: INSERT INTO cobo_dwm.dwm_custody_fee_hour (id, asset_coin, balance, custody_wallet_id, fee_income, fee_income_usd, withdraw_fee, withdraw_fee_usd, to_chain_fee, to_chain_fee_usd, collect_fee, collect_fee_usd, other_fee, manual_amount, withdraw_amount, withdraw_amount_usd, org_id, remote_wallet_id, usd_price, pdates) VALUES), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0c86b5 in /usr/bin/clickhouse
1. ? @ 0x8941ed0 in /usr/bin/clickhouse
2. DB::MergeTreeDataWriter::splitBlockIntoParts(DB::Block const&, unsigned long, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>, std::__1::shared_ptr<DB::ChunkOffsets>) @ 0x144380e3 in /usr/bin/clickhouse
3. DB::MergeTreeSink::consume(DB::Chunk) @ 0x145b4a42 in /usr/bin/clickhouse
4. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x14a14422 in /usr/bin/clickhouse
5. ? @ 0x14944feb in /usr/bin/clickhouse
6. ? @ 0x14944d39 in /usr/bin/clickhouse
7. DB::ExceptionKeepingTransform::work() @ 0x1494461f in /usr/bin/clickhouse
8. DB::ExecutionThreadContext::executeTask() @ 0x14766aec in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x1475bcfb in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x1475b0e8 in /usr/bin/clickhouse
11. DB::TCPHandler::processInsertQuery() @ 0x1470c9a4 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x14704022 in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x14719259 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x1761d1b4 in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x1761e3db in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x177a5767 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x177a319d in /usr/bin/clickhouse
18. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
19. __clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
```
But the data seems all is normal and maybe I rewrite the data success, so the error msg was ignored.

Last week I upgraded Clickhouse to version 23.2, I found the error msg had last for 3 month. There are many logs in system.query_log with a same  **initial_query_id** , it create a new query_log record every 30 secs, the query_log shows the setting values like :

```
{'load_balancing':'random','max_execution_time':'600','max_memory_usage':'10000000000','max_memory_usage_for_user':'25000000000','send_logs_level':'none','max_partitions_per_insert_block':'5000','max_memory_usage_for_all_queries':'25000000000','allow_experimental_window_functions':'1'}
```

I've tried this list (**the query_log not follow the new settings**):

- Merge data to reduce the partitions of this table to less than 5000;
- Change max_partitions_per_insert_block to 0 or other number;
- Change other settings ,such like : max_insert_retries , max_execution_time , timeout_overflow_mode ,,, even use a same query_id to replace the old one, but no use ; 
- Rename the table (The error message change to 'table not exists' but still be executed every 30 secs);
- Restart and restart and restart ;

Now seems the error make Clickhouse crashed every 3~5 days.  How can I fix it ?

**Comment by den-crane** [comment]
When you insert into distributed table the data is stored in the folder of the distributed table as a file `<number>.bin`.
Later the distributed monitor reinserts data into *mergeTree, if the insert fails with any error, then the distributed monitor re-tries until succeed.

You can remove this `<number>.bin` or set `max_partitions_per_insert_block=0`.


```
cat /etc/clickhouse-server/users.d/memory_usage.xml
<?xml version="1.0" ?>
<clickhouse>
    <profiles>
        <default>
            <max_partitions_per_insert_block>0</max_partitions_per_insert_block>
        </default>
    </profiles>
</clickhouse>
```

restart is mandatory because the distributed monitor initialized own settings with Clickhouse start only.

**Comment by DingZhengCN** [comment]
> When you insert into distributed table the data is stored in the folder of the distributed table as a file `<number>.bin`. Later the distributed monitor reinserts data into *mergeTree, if the insert fails with any error, then the distributed monitor re-tries until succeed.
> 
> You can remove this `<number>.bin` or set `max_partitions_per_insert_block=0`.
> 
> ```
> cat /etc/clickhouse-server/users.d/max_partitions_per_insert_block.xml
> <?xml version="1.0" ?>
> <clickhouse>
>     <profiles>
>         <default>
>             <max_partitions_per_insert_block>0</max_partitions_per_insert_block>
>         </default>
>     </profiles>
> </clickhouse>
> ```
> 
> restart is mandatory because the distributed monitor initialized own settings with Clickhouse start only.

Thanks for reply. I tried doing this, but it doesn't work , I confirmed the value of  max_partitions_per_insert_block for many times.

```
SELECT value FROM system.settings where name='max_partitions_per_insert_block' -- return 0
```

Seems that Clickhouse use the old "max_partitions_per_insert_block" value which setup by long time ago, not the current set one.

**Comment by DingZhengCN** [comment]
> When you insert into distributed table the data is stored in the folder of the distributed table as a file `<number>.bin`. Later the distributed monitor reinserts data into *mergeTree, if the insert fails with any error, then the distributed monitor re-tries until succeed.
> 
> You can remove this `<number>.bin` or set `max_partitions_per_insert_block=0`.
> 
> ```
> cat /etc/clickhouse-server/users.d/max_partitions_per_insert_block.xml
> <?xml version="1.0" ?>
> <clickhouse>
>     <profiles>
>         <default>
>             <max_partitions_per_insert_block>0</max_partitions_per_insert_block>
>         </default>
>     </profiles>
> </clickhouse>
> ```
> 
> restart is mandatory because the distributed monitor initialized own settings with Clickhouse start only.

Thank you , this worked for me.
