### ISSUE TITLE
clickhouse write s3 exception

### ISSUE THREAD

**Issue by liugs0213** [ClickHouse/ClickHouse#48336]
> You have to provide the following information whenever possible.
**Describe what's wrong**
Execute sql: alter table dataset_v4_test_all_2 move partition '202302' to disk 'arch';
![image](https://user-images.githubusercontent.com/55676558/229478725-d88551a3-c9de-4904-8df8-4fc64c915ea2.png)

The table contains 5000 columns and has about 8 GB partitions. Net Exception: Cannot assign requested address: An exception occurs when data is moved from the nvme to s3
Exception cause: This parameter must occur when the number of tcp connections reaches 28283
![image](https://user-images.githubusercontent.com/55676558/229478802-5d985d5c-80c8-413a-8306-5024cc52a433.png)
![image](https://user-images.githubusercontent.com/55676558/229478873-f26ebe76-2ac0-47cf-a0e9-b674adde7922.png)

I want to know if there's a way to control the number of concurrent requests

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by Algunenano** [comment]
There have been multiple improvements in connection to s3 in 24.4 by @CheSema (like https://github.com/ClickHouse/ClickHouse/pull/62249). Updating and testing with this version is recommended
