### ISSUE TITLE
output_format_pretty_grid_charset = 'ASCII' uses bold escape char in the header

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#48351]
https://fiddle.clickhouse.com/f3ea2f5b-8fc4-42e3-8186-8d11337a6d31

current 
```
+-[1msuppkey[0m-+-[1mbrand[0m---+-[1mcategory[0m-+-[1mquantity[0m-+
|       1 | BRAND_A | 1        |     1500 |
|       1 | BRAND_A | 2        |     4200 |
|       1 | BRAND_A | 3        |     1600 |
```

expected
```
+-suppkey-+-brand---+-category-+-quantity-+
|       1 | BRAND_A | 1        |     1500 |
|       1 | BRAND_A | 2        |     4200 |
|       1 | BRAND_A | 3        |     1600 |
```

**Comment by KochetovNicolai** [comment]
https://github.com/ClickHouse/ClickHouse/blob/9a108f3f0eb8c998402f18bd021f40c07de40df2/src/Processors/Formats/Impl/PrettyBlockOutputFormat.cpp#L247

**Comment by jh0x** [comment]
`output_format_pretty_grid_charset` doesn't change much, apart from choosing box drawing characters.

It seems to behave better with `PrettyCompactNoEscapesMonoBlock` - as per:

https://github.com/ClickHouse/ClickHouse/blob/9a108f3f0eb8c998402f18bd021f40c07de40df2/src/Processors/Formats/Impl/PrettyBlockOutputFormat.h#L21

and:

https://github.com/ClickHouse/ClickHouse/blob/9a108f3f0eb8c998402f18bd021f40c07de40df2/src/Processors/Formats/Impl/PrettyBlockOutputFormat.h#L78-L84

Another option is to explicitly disable colours (as bolding is also a "form of colour" via ANSI escape sequence):

```sql
SET output_format_pretty_color = FALSE;
```

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/e65e97e3-2cce-4106-96e9-7d3ea04d5a4a
