### ISSUE TITLE
Error querying DeltaLake table - CANNOT_EXTRACT_TABLE_STRUCTURE

### ISSUE THREAD

**Issue by cmackenzie1** [ClickHouse/ClickHouse#48359]
**Describe what's wrong**

Unable to read DeltaLake table from S3. 

```sql
SELECT * FROM deltaLake('https://s3.amazonaws.com/example-bucket/table', 'access_key', 'secret_access_key')
```

**Does it reproduce on recent release?**

Tested on `23.4.1.49` and `23.4.1.211`

**Enable crash reporting**

N/A

**How to reproduce**

1. Create DeltaLake using the example script in delta-rs https://github.com/delta-io/delta-rs/blob/main/rust/examples/recordbatch-writer.rs
2. Query DeltaLake table stored in S3

**Expected behavior**

A result of the data stored in the DeltaLake table

**Error message and/or stacktrace**

```
Received exception:
Code: 636. DB::Exception: Cannot extract table structure from Parquet format file, because there are no files with provided path in S3. You must specify table structure manually: Cannot extract table structure from Parquet format file. You can specify the structure manually. (CANNOT_EXTRACT_TABLE_STRUCTURE)
```

**Comment by tavplubix** [comment]
cc: @rubin-do

**Comment by kssenii** [comment]
Let's wait for https://github.com/ClickHouse/ClickHouse/pull/47307 and see if it still reproduces, there are a lot of fixes in this PR.

**Comment by kssenii** [comment]
But I assume your case does not work as your data might be partitioned, this is fixed in https://github.com/ClickHouse/ClickHouse/pull/47307.
