### ISSUE TITLE
I have a question about the `untuple` function

### ISSUE THREAD

**Issue by rgzntrade** [ClickHouse/ClickHouse#48368]
- Duplicate column names due to untuple

# Version
- 23.3.1.1731

# Recurrence
``` sql 
SELECT ( (('1', ('11', '12')).2).2) AS src, (untuple(('1', ('11', '12')).2)) AS src2;
```

# Error Info
Code: 15. DB::Exception: Column 'tupleElement(tupleElement(('1', ('11', '12')), 2), 2)' already exists: While processing (('1', ('11', '12')).2).2 AS src, untuple(('1', ('11', '12')).2) AS src2. (DUPLICATE_COLUMN) (version 23.3.1.1731 (official build))

**Comment by alexey-milovidov** [comment]
It's not possible to have the original tuple and untuple in the same SELECT query.
