### ISSUE TITLE
Using parameters as value in parameterized view

### ISSUE THREAD

**Issue by peder1001** [ClickHouse/ClickHouse#48374]
I have already done the following without success:
- Documentation checked ✅
- Slack channel #help asked ✅

So I will ask here:

**Q: How can I pass a parameter/variable when selecting from a parameterized view?**

For example, the documentation allows us to use:

`SELECT * FROM view(column1=value1)`

So, this works fine:

`SELECT * FROM view(column1=22)`

In my situation, I have a parameterized view which is selecting from another parameterized view:

```
CREATE VIEW test AS

SELECT a, b, c FROM x WHERE a = {h:String}
```

So, I have a parameterized view called test, now I want to create another parameterized view to select from test:
```
CREATE VIEW test2 AS

SELECT 
a, 
b * 2 as d, 
c * 2 as e
FROM 
test(h = {j:String} )
```

This gives an error: 

> Code: 456. DB::Exception: Substitution `h` is not set. (UNKNOWN_QUERY_PARAMETER) (version 23.3.1.2823 (official build))

Is there a more correct way to do this? If it is not supported, what do you think about this as a feature request?

**Comment by lampjian** [comment]
You shouldn't define a prameterized view from the alike view, and this way makes no sense to me.

**Comment by crazyproger** [comment]
@lampjian Could you explain why?

Suppose I have complex query like 
```
select smt from (<subquery 1> some join <subquery 2>)
```
And it might be that each subquery is also complex. 

When your tables are very big - every subquery typically contains `where pk between X and Y`(mostly it is dates). 
It is possible to create one view with parameters for all subqueries PK intervals.
But what if I want to reuse some subquery in more than one view?
The only way is to make it parameterised view. And I can not find any negative impact from this possibility.

**Comment by crazyproger** [comment]
duplicates #54916

**Comment by nikitamikhaylov** [comment]
Everything works in `24.4` https://fiddle.clickhouse.com/72c04606-685d-45ce-bf75-935de27cc32d
