### ISSUE TITLE
Standalone Keeper Server won't start

### ISSUE THREAD

**Issue by joshbartley** [ClickHouse/ClickHouse#48397]
Attempting to setup a 3 node cluster with 2 replicas and 1 standalone clickhouse-keeper instance.

Version Numbers
Two data nodes
`clickhouse-server -V` ClickHouse server version 23.3.1.2823
One keeper node
`clickhouse-keeper -V` ClickHouse keeper version 23.3.1.2823

**How to reproduce**
 
Installed using the instructions at https://clickhouse.com/docs/en/architecture/horizontal-scaling. On the 3rd node I installed only clickhouse-keeper. I updated the  keeper_config.xml file and set the `server_id` to 3 and set the `<raft_configuration>` to the 3 nodes.

**Expected behavior**

Keeper would connect and show as a connection on the other 2 nodes.
 
**Error message and/or stacktrace**

<Warning> RaftConfiguration: Config will be ingored because a server with ID 1 is already present in the cluster on a different endpoint (localhost:9234). The endpoint of the current servers should not be changed. For servers on a new endpoint, please use a new ID. 
<Information> KeeperDispatcher: Server still not initialized, will not apply configuration until initialization finished.

I have also attempted to remove all files from the coordination directory to reset the state and it did not seem to help.

**Comment by DanRoscigno** [comment]
Hi @joshbartley can you please upload the configs for the three servers?  Also, what version of ClickHouse are you running?
