### ISSUE TITLE
Local time zones in some countries doesn't change with adjust day light

### ISSUE THREAD

**Issue by mkbeai** [ClickHouse/ClickHouse#48411]
hi,
Local time zones in some countries doesn't change with adjust day light
for example in new rule at Asia/Tehran time local doesn't change with adj day light then it's always +03:30 please change it or add a feature for config adjust day light.
thanks

**Comment by den-crane** [comment]
Need to update tz database to 2023c
https://data.iana.org/time-zones/tzdb/NEWS

```
Release 2023c - 2023-03-28 12:42:14 -0700

  Changes to past and future timestamps

    Model Lebanon's DST chaos by reverting data to tzdb 2023a.
```

**Comment by mkbeai** [comment]
I updated tz data base and now os is ok but Not clickhouse,
I also restarted Clickhouse several times.
