### ISSUE TITLE
Does a query for a distributed table ensure high availability?

### ISSUE THREAD

**Issue by myabcc17** [ClickHouse/ClickHouse#48416]
We built a clickhouse cluster on Kubernetes with a zookeper.

8 kubernetes worker nodes with 3 shards and 2 replica, leaving 2 worker nodes as spare.

We also configured ingress to enable http requests to specific domains.

Clickhouse tables are configured as distributed tables.

Let's do the configuration above and then assume a situation.
One of each shard's replica died, and a total of three clickhouse servers died. ingress has removed endpoints for dead clickhouse server pods.
It then sends a query to the distributed table with the http interface.

The results were sometimes successful or sometimes unsuccessful. The reason for the failure was that a query request was sent to the dead clickhouse server.

ingress removed the endpoint for the dead clickhouse service, but at the end, the request found in the error that it went to the dead clickhouse server.
```
chi-builder-builder-0-1 -> dead replica

Caused by: java.sql.SQLException: Code: 198. DB::Exception: Not found address of host: chi-builder-builder-0-1: While executing Delayed. (DNS_ERROR) (version 22.8.11.15 (official build))
, server ClickHouseNode [uri=http:/{host}:80/default]@-1135759246
```
If I get a request to the clickhouse server via ingress, does the query go back to the zookeeper? Does zookeeper send distributed queries for dead clickhouse?

```
$ SELECT * FROM system.clusters

cluster, shard_num, replica_num, host_name, host_address
------------------------------------------------------------
builder, 1, 1, chi-builder-builder-0-0, XX.XX.XX.XX
builder, 1, 2, chi-builder-builder-0-1, 
builder, 2, 1, chi-builder-builder-1-0, XX.XX.XX.XX
builder, 2, 2, chi-builder-builder-1-1, 
builder, 3, 1, chi-builder-builder-2-0, XX.XX.XX.XX
builder, 3, 2, chi-builder-builder-2-1, 
```

**Comment by den-crane** [comment]
You issue related to https://github.com/ClickHouse/ClickHouse/issues/45683
https://github.com/ClickHouse/ClickHouse/pull/43179

You need to upgrade to 23.3. That fix is not included into 22.8
