### ISSUE TITLE
test_multiple_disks/test.py::test_concurrent_alter_move_and_drop[mt]

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#48421]
[Link](U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2NvbmN1cnJlbnRfYWx0ZXJfbW92ZV9hbmRfZHJvcCUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l)

https://s3.amazonaws.com/clickhouse-test-reports/0/802cd805c8400d46794c737dc8b806c38399e9ca/integration_tests__tsan__[2/4].html

Not very often, but fails with `Cannot reserve 1.00 MiB`.
(maybe already fixed, cannot find)

**Comment by serxa** [comment]
This test does random ALTER MOVE PARTITION and ALTER DETACH PARTITION. And as I can see reserved space for disk `external` gradually decreases to zero. It actually takes a lot of time and just happens not on every run.

**Comment by serxa** [comment]
Not sure how to properly fix it.
