### ISSUE TITLE
json format have the style error

### ISSUE THREAD

**Issue by lzc-up** [ClickHouse/ClickHouse#48446]
I am not a native English speaker, please forgive me if there are any grammar errors
### environment 
- docker image Ubuntu 22.04 
-  clickhouse server  (ver. 23.2.4.12)
-  drive clickhouse 0.4.0
-  datagrip
i use Mac os use datagrip connect clichouse server.

###  question 
- query SQL
`SELECT * FROM system.columns LIMIT 1 FORMAT JSON`
 the datagrip query result 
![10-33-44-snipaste](https://user-images.githubusercontent.com/39999449/230257850-80b9706f-8e6e-4574-8a52-b18a27ccf039.jpg)
i think it's encode json error , but how to setting it
- this is my use docker clickhouse-client query the same SQLresult this json encode right
![10-40-01-snipaste](https://user-images.githubusercontent.com/39999449/230258762-199ff982-aec1-4976-be06-8e1b0a9c2640.jpg)

Very sincere thanks, if you can help me solve this confusion.

**Comment by lzc-up** [comment]
i think it's maybe jdbc drive bug

**Comment by den-crane** [comment]
Not a ClickHouse server issue
