### ISSUE TITLE
ClickHouse server version 22.9.7 revision 54460 mapUpdate

### ISSUE THREAD

**Issue by csucjh** [ClickHouse/ClickHouse#48449]
`SELECT
    concat('{"level":"', toString(number), '"}') AS line,
    CAST([('aa', '00000000'), ('bb', '321982720520421376'), ('cc', 'network'), ('dd', '2913')], 'Map(String, String)') AS labels,
    CAST([('level', if(JSONType(line, 'level') = 'String', JSONExtractString(line, 'level'), JSONExtractRaw(line, 'level')))], 'Map(String, String)') AS extra_labels,
    mapUpdate(extra_labels, labels) AS labels1
FROM numbers(1, 1)
`

When I execute this sql in ClickHouse server version 22.9.7 revision 54460，the result is:
`line:         {"level":"1"}
labels:       {'aa':'00000000','bb':'321982720520421376','cc':'network','dd':'2913'}
extra_labels: {'level':'1'}
labels1:      {'level':'1','aa':'00000000'}
`
labels1 is error, but it right on version  22.3.6 revision 54455

`line:         {"level":"1"}
labels:       {'instanceId':'00000000','pkgLogId':'321982720520421376','domain':'network','logFileId':'2913'}
extra_labels: {'level':'1'}
labels1:      {'level':'1','instanceId':'00000000','pkgLogId':'321982720520421376','domain':'network','logFileId':'2913'}
`

**Comment by CurtizJ** [comment]
> it right on version 22.3.6

Yes, it was fixed in #48118. Maybe we can partially backport this PR, but I'm not sure whether it's worth it. Anyway, version 22.9 is already out of support.
