### ISSUE TITLE
change docker / container image to log to console by default

### ISSUE THREAD

**Issue by cjw296** [ClickHouse/ClickHouse#48448]
**Describe the unexpected behaviour**

The most common behaviour of software running it docker/podman/etc containers is to write their logs to stdout by default.
The clickhouse container image at `docker.io/clickhouse/clickhouse-server` does not appear to do this and, instead, writes logs to a file inside the container.

**How to reproduce**

```
$ docker run docker.io/clickhouse/clickhouse-server
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
Processing configuration file '/etc/clickhouse-server/users.xml'.
Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'
```

**Expected behavior**

I should see the server's logging as things happen, particularly waiting for the `<Information> Application: Ready for connections.` message.

Instead, this logging is only written to `/var/log/clickhouse-server/clickhouse-server.log` inside the server.

I believe https://github.com/ClickHouse/ClickHouse/issues/2241#issuecomment-885219681 provides the appropriate configuration, but this should be the default in the container image at `docker.io/clickhouse/clickhouse-server`

**Comment by cjw296** [comment]
See https://github.com/ClickHouse/ClickHouse/pull/48452

**Comment by alexey-milovidov** [comment]
An easy workaround is possible, so there is no need to change the default.

**Comment by Felixoid** [comment]
Well, adding :-1:  to every comment that described the reason to not change defaults is not very cooperative as well. I am not teaching you how to behave, for sure, but your problem has a very, VERY simple solution:

```docker run -it clickhouse/clickhouse-server:head -- -L - -E -```

Instead of that, you try to convince changing the defaults, without actually digging into the reasons for these defaults. And you look upset at us because we care about our users.

**Comment by alexey-milovidov** [comment]
@cjw296 Sorry for refusing this PR. No offense!
