### ISSUE TITLE
Distributed query and I/O error: Broken pipe

### ISSUE THREAD

**Issue by JessicaChen123** [ClickHouse/ClickHouse#48451]
Hi all:
I have a Distributed MergeTree table X in a cluster of 2 nodes in total.
There're some queries running selecting data from node 1(192.168.1.3), they finish successfully. However, I can see a lot of errors like this in the log of node 2(192.168.1.5):

> Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket ( 192.168.1.3:62654),stack trace (when copying this message,always include the lines below):
> Poco: : Exception: : Exception(std:: -__1_lisbasic_string<char,
> std: l::char_traits<char>, std::.-l::allocator‹chard const&, int) a Oxd76db4c in /usr/bin/clickhouse
> DB:: Exception:: Exception(std::std::-_l::char_traits‹char>, std:: __l::allocator‹char>const&,
> B: :WriteBufferFromPocoSocket::nextImpl() @ 0xb9f3f23 in /usr/bin/clickhouse
> DB: : TCPHandler: :sendData (DB: : Block const&) @ Oxae5be7c in /usr/bin/clickhouse
> DB::TCPHandler::processOrdinaryQuervWithProcessors()@Oxae5aae5in/usr/bin/clickhouse
> DB:: TCPHandler: :runImpl() @ Oxae56188 in /usr/bin/clickhouse
> DB: : TCPHandler::run() @ Oxae60a77 in /usr/bin/clickhouse
> Poco::Net: : TCPServerConnection: :start() a Oxd6e2f07 in /usr/bin/clickhouse
> Poco: :Net: : TCPServerDispatcher::run() @ Oxd6e3367 in /usr/bin/clickhouse
> Poco: :PooledThread: :run() @ Oxd7c4587 in /usr/bin/clickhouse
> Poco:: ThreadImpl: :runnableEntry(void*) @ Oxd7clfa6 in /usr/bin/clickhouse/build/eglibc-oGUzwX/eglibc-2.19/nptl/pthread_create.c:312: start_thread @ 0x8184 in /usr/lib/debug/lib/x86.54-linux-gnu/libpthread-2.19.s0
> /build/eglibe-oGUzwX/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:113:
> clone a oxfa37d in /udsr/lib/debug/lib/x86_64-linux-gnu/libe-2.19.s0

Question:
Is the port 62654  a dynamic port that used in inter-server communication whithin a ClickHouse cluster?
If yes, Is there a value range of this kind of dynamic port?
What could be the root cause of this I/O error? (Clickhouse v21.8.12.29)

**Comment by den-crane** [comment]
21.8 is obsolete since 22.8.
You should upgrade
