### ISSUE TITLE
when clickhouse-keeper use in product env？

### ISSUE THREAD

**Issue by lhcg** [ClickHouse/ClickHouse#48450]
when clickhouse-keeper use in product env？whether it has dateline?
I see the version is on hub.docker.com, it has always been head-alpine version.

**Comment by antonio2368** [comment]
ClickHouse Keeper is production ready since exactly 1 year ago (from version 22.3).

> I see the version is on hub.docker.com, it has always been head-alpine version.

It follows the exact same versioning and releases as ClickHouse server.
You have `latest` (`latest-alpine`), `22.3` (`22.3-alpine`), `22.3.1`... and all other versions
