### ISSUE TITLE
Often encounter error 'reading method io_uring is only supported in Linux' on version 23.2.4-stable version

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#48484]
My clickhouse is running in Ubuntu linux os.

I have disabled the io_uring with `-DENABLE_LIBURING=0` and sometimes no exception but casually the exception 'reading method io_uring is only supported ...' was thrown.

**Comment by cangyin** [comment]
ensure that the setting `local_filesystem_read_method` is not set to `io_uring`.

a query with the setting value `io_uring` can also cause the exception, for exmaple:
```sql
SELECT * FROM <DB>.<TABLE> SETTINGS local_filesystem_read_method='io_uring';
```

**Comment by Alex-Cheng** [comment]
Thank you very much.
