### ISSUE TITLE
Backup to S3 ability to define storage class

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#48513]
**Use case**

```
BACKUP TABLE database.tbl  TO S3(....,KEY, SECRET_KEY, s3_storage_class='STANDARD_IA')
```

**Describe the solution you'd like**

It will be possible to define storage class in s3 string

**Comment by rvasin** [comment]
I am working on it. If it's possible please assign me to this task.

**Comment by rvasin** [comment]
BTW in current C++ code implementation probably it's better to use it in this format:

```sql
BACKUP TABLE database.tbl  TO S3(....,KEY, SECRET_KEY)
SETTINGS s3_storage_class='STANDARD_IA'
```

Here S3 is "backup engine" and in C++ code all arguments of engine are expected to be literals.

In case of usage s3_storage_class with other backup engines we may throw an exception.
