### ISSUE TITLE
clickhouse common join and distributed join

### ISSUE THREAD

**Issue by WenDing-Y** [ClickHouse/ClickHouse#48529]
1.tablea  two shard,one replica,tableb  two shard one replic

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/19184146/230532561-2e303818-3087-49b5-b4bd-56f7d10980bc.png">

2.the question

I have looked at some information and found that in the case of a distributed table, the semantics of a join are correct, only enlarging the read. Therefore, I introduced a global join, but I found that the semantics of a join are incorrect. It only joins on local nodes, and partitioned data does not join across nodes

3.example
the sql

`select count(*) from tablea_all join tableb_all on tablea_all.user_id=tableb_all.user_id where tablea_all.user_id=1` 

the result is 1,not 2

`select count(*) from tablea_all join tableb_local on tablea_all.user_id=tableb_local.user_id where tablea_all.user_id=1` 

the result is 1,not 2

**The semantics of these two SQL statements are the same, and they will execute the following SQL statement on both nodes**

`select count(*) from tablea_local join tableb_local on tablea_local.user_id=tableb_local.user_id where tablea_local.user_id=1` 

the global join

`select count(*) from tablea_all global join tableb_all on tablea_all.user_id=tableb_all.user_id where tablea_all.user_id=1`

the result is 2

I want to know if my understanding is correct

**Comment by den-crane** [comment]
see https://gist.github.com/den-crane/55f4b8d7caf9b644a347a62729be3848
see distributed_product_mode https://clickhouse.com/docs/en/operations/settings/settings#distributed-product-mode
https://clickhouse.com/docs/en/sql-reference/operators/in

**Comment by den-crane** [comment]
In your case is impossible to join locally because tablea is not sharded by key.
Only distributed_product_mode=allow and GLOBAL join can provide the correct result.
