### ISSUE TITLE
_mark virtual column

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#48530]
Per Slack, I think there is no option to select on _marks (row groups). The problem is I have a 1.2 billion row table, it has 4 parts, each part is very massive and would be inefficiently exported via Parquet, for example. Ideally I could arbitrarily sub-divide the table into smaller 3GB files (or whatever size) instead of 4x30GB files.

I could code around a high cardinality column but that requires ex-ante knowledge of the table. 

I am positing a better way which should be easier to implement: namely to expose a _mark virtual column. It has the advantage of being equally spaced and arbitrarily granular, and potentially contiguously numbered (disk-seek efficiency?). As @hodgesrm  points out, marks are numbered within a _part and thus I would imagine a query pattern as follows (hopefully transparent R syntax):
```{r}

df=clickhouse_query('select _part as part,_mark as mark,sum(data_compressed_bytes) as size_of_ from db.table group by all')
# partition it somehow into size groups or whatever, in this case 10 bins within each part
df[,binning:= ceiling(1:length(mark)*10),by=list(part)] 

for(i in 1:n_distinct(df[,list(mark,part)]) ){
   sub_df=df[binning==i,]
  marklist=paste("'",sub_df$mark,"'",collapse=',') # some sort of expression to get something like 'mark.0','mark.1','mark.2'
   query=" select * from db.table where _part='{sub_df$part}' and _mark in ({marklist})"
   system(' clickhouse-client --query="{query} Format Parquet > {folder_for_output}/databucket_{i}.parquet' %>% str_glue
} 

```

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/30530
