### ISSUE TITLE
lowerUTF8 working incorrect with russian symbols

### ISSUE THREAD

**Issue by MaltseF** [ClickHouse/ClickHouse#48535]
![image](https://user-images.githubusercontent.com/26347006/230593374-d5f121e7-12d7-40fb-8ecb-8ee035bc343e.png)
![image](https://user-images.githubusercontent.com/26347006/230593379-add9ad5b-db81-492b-86bb-35bc46a3c676.png)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/42756
already fixed https://github.com/ClickHouse/ClickHouse/pull/42812 https://fiddle.clickhouse.com/4b93568b-ef0f-4987-ade2-25738b107091

v22.10.3.27-stable.md:* Backported in [#42864](https://github.com/ClickHouse/ClickHouse/issues/42864): Fix lowerUTF8()/upperUTF8() in case of symbol was in between 16-byte boundary (very frequent case of you have strings > 16 bytes long). [#42812](https://github.com/ClickHouse/ClickHouse/pull/42812) ([Azat Khuzhin](https://github.com/azat)).
v22.11.1.1360-stable.md:* Fix lowerUTF8()/upperUTF8() in case of symbol was in between 16-byte boundary (very frequent case of you have strings > 16 bytes long). [#42812](https://github.com/ClickHouse/ClickHouse/pull/42812) ([Azat Khuzhin](https://github.com/azat)).
v22.9.5.25-stable.md:* Backported in [#42863](https://github.com/ClickHouse/ClickHouse/issues/42863): Fix lowerUTF8()/upperUTF8() in case of symbol was in between 16-byte boundary (very frequent case of you have strings > 16 bytes long). [#42812](https://github.com/ClickHouse/ClickHouse/pull/42812) ([Azat Khuzhin](https://github.com/azat)).
