### ISSUE TITLE
reinterpretAsString returns different length when input is fixed type integer

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#48592]
**Describe the unexpected behaviour**
reinterpretAsString returns different length when input is fixed type integer

**How to reproduce**
* Which ClickHouse server version to use
Current master branch. 

As you see, reinterpret returns different length of results when input argument is always an UInt64 number, which I think is not as expected, because reinterpretAsString should always returns String represented by identical bytes in memory with input argument, no matter whether the bytes sequence has trailing zero bytes.  
```  sql
SELECT length(reinterpret(CAST('1', 'UInt64'), 'String'))

Query id: 7e9b7464-01ea-46e2-8c39-130e3f8bba69

┌─length(reinterpret(CAST('1', 'UInt64'), 'String'))─┐
│                                                  1 │
└────────────────────────────────────────────────────┘

SELECT length(reinterpret(CAST('1000', 'UInt64'), 'String'))

Query id: 4dff4e8a-127c-4409-8884-7c3b9acf1d5e

┌─length(reinterpret(CAST('1000', 'UInt64'), 'String'))─┐
│                                                     2 │
└───────────────────────────────────────────────────────┘


SELECT length(reinterpret(CAST(-1, 'UInt64'), 'String'))

Query id: 768f5e8d-b2cb-4239-b7c3-c4ee4a1219d8

┌─length(reinterpret(CAST(-1, 'UInt64'), 'String'))─┐
│                                                 8 │
└───────────────────────────────────────────────────┘
```

**Comment by taiyang-li** [comment]
I'll fix it somehow.

**Comment by alexey-milovidov** [comment]
As documented: https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#reinterpretasstring

**Comment by taiyang-li** [comment]
@alexey-milovidov it is possible to provide a setting to decide whether to keep null bytes or not in reinterpretAsString?
