### ISSUE TITLE
Clickhouse query / client hang sometimes but has increased frequency 

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#48599]
We are currently facing an issue with our 2-node cluster running ClickHouse. Although the cluster operates normally, there are times when one of the nodes suddenly hangs. When this occurs, attempting to connect to the client using clickhouse-client also hangs without providing a prompt. Furthermore, running certain system queries such as cluster queries from the working node only provides partial results and subsequently hangs, while most other system queries also hang. However, it's worth noting that distributed table queries from the working node seem to be functioning normally

```
query form working node 
SELECT *
FROM clusterAllReplicas('{cluster}', system.processes) 

<<some result>>

← Progress: 5.00 rows, 11.26 KB (0.11 rows/s., 254.31 B/s.)                                                                                                     
5 rows in set. Elapsed: 44.264 sec. 

<<stuck here never returns>

```

Restarting the node is the only way to solve the issue currently

**Comment by serxa** [comment]
Not obvious what it might be. Could you please provide the output of either:
```
clickhouse-client --allow_introspection_functions=1 -q "SELECT thread_id, query_id, arrayStringConcat(arrayMap(x, y -> concat(x, ': ', y), arrayMap(x -> addressToLine(x), trace), arrayMap(x -> demangle(addressToSymbol(x)), trace)), '\n') as trace FROM system.stack_trace format Vertical" > stacktraces.txt
```
or, if the first one also hangs or not work for any other reason (note that the server might be unavailable for some time, be careful):
```
gdb -ex 'set pagination off' -ex "set logging file gdb.log" -ex 'set logging on' -ex 'backtrace' -ex 'thread apply all backtrace' -ex 'backtrace' --pid `pidof clickhouse-server`
```

**Comment by UnamedRus** [comment]
Do you run a lot of DDL queries?

**Comment by shawel** [comment]
@serxa  test run on gdb reveals permission issue 

clickhouse is deployed in kubernetes aws arm node.. 

```
Attaching to process 1
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
Warning: 'set logging on', an alias for the command 'set logging enabled', is deprecated.
Use 'set logging enabled on'.

Copying output to gdb.log.
Copying debug output to gdb.log.
No stack.
No stack.
(gdb) 
```

**Comment by shawel** [comment]
> Do you run a lot of DDL queries?

@serxa. DDL not so much.  we have around 15 kafka tables and we use MV quite a bit though.

**Comment by serxa** [comment]
> run on gdb reveals permission issue

`sudo gdb` should help if it is available. If not, you have only the first option with a query.

**Comment by den-crane** [comment]
@shawel clickhouse-version ?

**Comment by shawel** [comment]
The current version we are using is 23.3, but I have observed the issues since version 22.8 or so, ~ 5 months ago when we transitioned to using ARM and a 2-node cluster from a standalone setup. The lockup issue occurs every few days, and as a temporary solution, we are using chproxy to mitigate the problem.

**Comment by den-crane** [comment]
Do you have swap?

**Comment by den-crane** [comment]
Also do you have `system.trace_log` ?
Try to disable it.

```
cat /etc/clickhouse-server/config.d/z_log_disable.xml
<?xml version="1.0"?>
<clickhouse>
    <trace_log remove="1"/>
</clickhouse>
```

**Comment by shawel** [comment]
@den-crane applied config to turn off trace.  no there is no swap

**Comment by shawel** [comment]
this issue no longer appears once the trace log is removed.
