### ISSUE TITLE
Shared metadata storage

### ISSUE THREAD

**Issue by zjial** [ClickHouse/ClickHouse#48620]
**Use case**

Currently, ClickHouse (CK) stores all metadata in local files. Each CK instance in a cluster has its own local metadata. These metadata represent one kind of system state of a CK instance. It is hard to dynamically remove or add CK instances without separating the metadata. To this end, we want to add an option to store metadata on a shared storage (e.g. keeper or distributed KV stores).

**Describe the solution you'd like**

For compatibility purposes, each instance stores its metadata in a different namespace in the shared store. When recreating an instance you only need to select the corresponding namespace in the shared store without using original local disk storage. For example:

* instance-1 → /clickhouse/instance-1/{databases,tables,acl,...}
* instance-2 → /clickhouse/instance-2/{databases,tables,acl,...}

The logic for manipulating metadata on shared storage is roughly the same as on local disk, except that it calls the remote storage interface and uses a different serialization method. In addition, we need to consider how to upload metadata from the local storage to the shared storage when CK nodes first boot with the shared storage option. We plan to support the following types of metadata:

***Database DDL***

Database DDL is stored as pure sql txt files in metadata/. When CK nodes first boot on the shared storage, the original code for metadata initialization is used to load DDL from txt files in metadata/, then upload them to the shared storage. When these CK nodes boot again, the original code is skipped and the SQL String (i.e. Database metadata) is loaded directly from the shared storage.

***Table DDL***

Similar to Database DDL, Table DDL is stored as pure sql txt files in metadata/$DB_UUID/. Due to the asynchronous operation of the drop table, there may be some dropped table sql files under metadata_dropped/ . When CK nodes first boot on the shared storage, the original code for loading Table metadata is used to load DDL from txt files in metadata/$DB_UUID/and metadata_dropped/ , then upload them to the shared storage. When these CK nodes reboot, the original code is skipped and the SQL String is loaded directly from the shared storage.

***MergeTreePart***

MergeTreePart-related metadata includes uuid, columns, checksums, partition, ttl_infos, rows_count and so on, which used to be loaded from disk when the node initially starts. After we add the option of storing metadata in the shared storage, the processing of MergeTreePart-related metadata is as follows:

* When CK nodes first boot on the shared storage, the original code for metadata initialization is used to load MergeTreePart from files in data part directory in disk, then upload them to the shared storage.
* When these CK nodes boot again, the original code is skipped and we directly load MergeTreePart-related metadata from the shared storage, then builds the MergeTreePart.
* Every time we remove, add and modify any parts, we remove metadata of these parts in the shared storage (add metadata of new parts to the shared storage if generating new parts).

***Config***

The main server configuration files are stored in config.xml, users.xml, {config, users}.d/*.xml. When CK nodes first boot on the shared storage, the original code for Config metadata is used to load configs from these xml files, then upload them to the shared storage. When rebooting, the original code is skipped and the config is loaded directly from the shared storage as an in-memory object. Since we stored the config metadata on the shared storage, the original way of changing configs by altering xml files is no longer applicable. Hence, we have implemented new sql statements to add/modify/delete config parameters on the shared storage.

***Dict***

Dictionaries can be created with xml files or DDL queries. The process of dictionaries DDL queries on the shared storage is the same as table DDL. For dictionaries created with xml files, the configuration files on the local disk are uploaded to the shared storage at first startup. At subsequent startup, the configuration files of the dictionary will not be obtained from the local disk but from the shared storage. The update and creation of dictionaries with xml files are also performed directly in the shared storage and then synchronized to the nodes. The process of dictionary queries has not changed.

***UDF***

There are two types of user defined functions, namely executable user defined functions and sql user defined functions. 
The xml configuration files of external executable user-defined functions and the DDL queries of sql user defined functions  are migrated to the shared storage at first startup.  At subsequent startup, these xml configuration files and DDL queries are fetched from the shared storage instead of local disks. In addition, the executable files for executable user defined functions are still kept locally on the node instead of the shared storage.  The update and creation of executable user defined functions are also performed directly in the shared storage and then synchronized to the nodes. The process of user defined functions queries has not changed.

***ACL***

ACL-related metadata mainly includes two types of permission management objects: (1) Access Entity statically defined in the configuration file with tag entries and (2) Access Entity dynamically generated in SQL-driven way with pure sql text. When CK nodes first boot on the shared storage, the original code for ACL metadata is used to parse access entities from configuration files and sql text files, then upload them to the shared storage. It is worth noting that with shared storage configured, the access entities persisted on local disk are migrated to shared storage on the first startup. When rebooting, the original code is skipped and the access entity is loaded directly from the shared storage as an in-memory objects instead of from local disk.

***About Shared Storage***

In our current implementation, we choose FoundationDB as the shared storage because of its good performance and scalability. To avoid the bottleneck of ZooKeeper in large-scale CK deployment, we have also developed FDBKeeper as an alternative implementation of IKeeper. This can avoid deploying both ZooKeeper and FoundationDB.

**Comment by UnamedRus** [comment]
> Similar to Database DDL, Table DDL is stored as pure sql txt files in metadata/$DB_UUID/.

There is Replicated database engine, it work like Atomic, but all tables created in it automatically replicated and created on all Replicas.  (IE if we use exclusively Replicated databases, no need to manually handle durable storage for table metadata)

> Dictionaries can be created with xml files or DDL queries. 

Currently the only reason for using xml based dictionaries is executable dictionaries, it was made in suck way because of security considerations. It's completely possible to allow creation of executable dictionaries via SQL, so no need to care about .xml based dictionaries.

> There are two types of user defined functions, namely executable user defined functions and sql user defined functions.

Same for functions.
BTW, SQL functions already can be stored in ZK https://github.com/ClickHouse/ClickHouse/pull/46085

> ACL-related metadata mainly includes two types of permission management objects: (1) Access Entity statically defined in the configuration file with tag entries and (2) Access Entity dynamically generated in SQL-driven way with pure sql text.

Same for users, RBAC users already can be replicated via ZK https://github.com/ClickHouse/ClickHouse/pull/27426

(And may be we don't need to care about xml based users)

So only topics, which are not covered yet are:
* Database replication
* MergeTreePart
* Config


BTW, ByConity folks also use FoundationDB as their metadata storage https://github.com/ByConity/ByConity

**Comment by ccat3z** [comment]
@UnamedRus You're right, most topics already have a Replicated solution on Keeper. Perhaps what we request is a shared unified meta store (aka Catalog in [ByConity](https://github.com/ByConity/ByConity)) for all types of metadata without local storage.

**Comment by lqhl** [comment]
Hi @alexey-milovidov ,

We have developed a shared metadata storage based on ClickHouse 22.3 (the design is described in this issue), and we would like to rebase it on the master and contribute it to the community.

We understand that this is a significant feature and it may require considerable effort to merge it into ClickHouse. Could you please inform us whether the community is willing to accept this feature and what steps we can take to facilitate this process?

**Comment by alexey-milovidov** [comment]
Please don't hesitate to send a pull request.

**Comment by lqhl** [comment]
@alexey-milovidov @ddorian we've submitted our implementation in #54567

**Comment by lqhl** [comment]
@alexey-milovidov what does label `st-fixed` mean?

**Comment by alexey-milovidov** [comment]
Implemented and available in ClickHouse Cloud.

**Comment by xleoken** [comment]
> @alexey-milovidov @ddorian we've submitted our implementation in #54567

Great feature!
