### ISSUE TITLE
Whether the java language udf function is supported?

### ISSUE THREAD

**Issue by create1072627512** [ClickHouse/ClickHouse#48622]

**Comment by vdimir** [comment]
You may check executable UDFs. They can be written in any language since it's just an executable file run in a separate process that reads input data from stdin.

https://github.com/ClickHouse/ClickHouse/issues/38446

Feel free to ask if you have any further questions regarding it.

**Comment by create1072627512** [comment]
Can you give a java sample? thank you

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-functions/executable
