### ISSUE TITLE
Detect output format by file exctension in clickhouse-local (and maybe in client also)

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#48634]
```
clickhouse local --query "SELECT * FROM table" < California.jsonl > California.parquet
```

Similar how we detect it for input format.

**Comment by Avogar** [comment]
Hi! No, currently I don't work on it. Feel free to implement it. I will assign it to you. If you have any questions, ask here, I will try to help

**Comment by HowePa** [comment]
Is this still working?

**Comment by Avogar** [comment]
Nobody is working on it right now, feel free to implement it.
