### ISSUE TITLE
roundAge returns incorrect value

### ISSUE THREAD

**Issue by ianton-ru** [ClickHouse/ClickHouse#48640]
Function **roundAge**, describe from [documentation](https://clickhouse.com/docs/en/sql-reference/functions/rounding-functions#roundagenum):

> If the number is less than 18, it returns 0. Otherwise, it rounds the number down to a number from the set: 18, 25, 35, 45, 55.

But for 1-17 it returns 17.

```
SELECT
    number,
    roundAge(number)
FROM
(
    SELECT number
    FROM system.numbers
    LIMIT 20
)

┌─number─┬─roundAge(number)─┐
│      0 │                0 │
│      1 │               17 │
│      2 │               17 │
│      3 │               17 │
│      4 │               17 │
│      5 │               17 │
│      6 │               17 │
│      7 │               17 │
│      8 │               17 │
│      9 │               17 │
│     10 │               17 │
│     11 │               17 │
│     12 │               17 │
│     13 │               17 │
│     14 │               17 │
│     15 │               17 │
│     16 │               17 │
│     17 │               17 │
│     18 │               18 │
│     19 │               18 │
└────────┴──────────────────┘

```

Repordused at least on versions 22.8, 23.2, 23.3

**Comment by rschu1ze** [comment]
@ianton-ru For backward compatibility reasons, it will be better to not break the existing semantics, i.e. update the docs instead. 0/18/25/35/45/55 behavior can be easily emulated using [multiIf](https://clickhouse.com/docs/en/sql-reference/functions/conditional-functions#multiif).
