### ISSUE TITLE
Results WITH TOTALS were not cached in Query Cache

### ISSUE THREAD

**Issue by LiyuTzyAge** [ClickHouse/ClickHouse#48677]
> You have to provide the following information whenever possible.

**Describe what's wrong**
When WITH TOTALS and Query Cache are used in queries, the results returned by query cache do not contain the WITH TOTALS results.

**Before the query cache takes effect**
 :) select t1,count() from t5 group by t1 with totals order by t1 desc limit 11

┌─t1─┬─count()─┐
│ aa │      28 │
└────┴─────────┘

Totals:
┌─t1─┬─count()─┐
│    │      28 │
└────┴─────────┘

**After the query cache takes effect**

 :) select t1,count() from t5 group by t1 with totals order by t1 desc limit 11

┌─t1─┬─count()─┐
│ aa │      28 │
└────┴─────────┘

**Comment by rschu1ze** [comment]
Repro:

```sql
create or replace table tbl (grp UInt64, kf UInt64) ENGINE = MergeTree order by grp;
insert into tbl values (1, 3), (2, 2), (1, 4), (1, 1);

set allow_experimental_query_cache = 1;
select grp, sum(kf) from tbl group by grp with totals SETTINGS use_query_cache = 1;
select grp, sum(kf) from tbl group by grp with totals SETTINGS use_query_cache = 1;
```

**Comment by rschu1ze** [comment]
Same problem exists for `SETTINGS extremes = 1`.

**Comment by LiyuTzyAge** [comment]
@rschu1ze hi, I see that the new implementation with totals will not be cached, but we use a lot of scenes, can you implement it

**Comment by rschu1ze** [comment]
Yepp, I'll try
