### ISSUE TITLE
Poco::Exception. Code: 1000, e.code() = 0, SAXParseException: Invalid token in '/etc/clickhouse-server/config.xml', line 7 column 1,

### ISSUE THREAD

**Issue by GVA-Guillaume** [ClickHouse/ClickHouse#48672]
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**

DOCKERIZED - DOCKER 

Packages, docker, single binary, curl?

**Source of the ClickHouse**

ARG REPO_CHANNEL="stable"
ARG REPOSITORY="deb https://packages.clickhouse.com/deb ${REPO_CHANNEL} main"
ARG VERSION="23.3.1.2823"
ARG PACKAGES="clickhouse-client clickhouse-server clickhouse-common-static"

apt-get install --allow-unauthenticated --yes --no-install-recommends ${packages}

A link to the source. Or the command you've tried

"deb https://packages.clickhouse.com/deb ${REPO_CHANNEL} main"

Dockerfile : https://github.com/ClickHouse/ClickHouse/

**Expected result**

Bind on 9440 tls secure port

What you expected

Bind on 9440 tls secure port

**The actual result**

What you get

Processing configuration file '/etc/clickhouse-server/config.xml'.
Poco::Exception. Code: 1000, e.code() = 0, SAXParseException: Invalid token in '/etc/clickhouse-server/config.xml', line 7 column 1, Stack trace (when copying this message, always include the lines below):

0. Poco::XML::SAXParseException::SAXParseException(String const&, Poco::XML::Locator const&) @ 0x17881e9e in /usr/bin/clickhouse
1. Poco::XML::ParserEngine::handleError(int) @ 0x17886907 in /usr/bin/clickhouse
2. ? @ 0x17885a7c in /usr/bin/clickhouse
3. Poco::XML::ParserEngine::parse(Poco::XML::InputSource*) @ 0x17885093 in /usr/bin/clickhouse
4. Poco::XML::SAXParser::parse(String const&) @ 0x17884524 in /usr/bin/clickhouse
5. Poco::XML::DOMBuilder::parse(String const&) @ 0x1786d438 in /usr/bin/clickhouse
6. Poco::XML::DOMParser::parse(String const&) @ 0x1786c842 in /usr/bin/clickhouse
7. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::shared_ptr<Poco::Event> const&) @ 0x14e6c694 in /usr/bin/clickhouse
8. DB::ConfigProcessor::loadConfig(bool) @ 0x14e6f0d4 in /usr/bin/clickhouse
9. BaseDaemon::reloadConfiguration() @ 0xe3d8aaf in /usr/bin/clickhouse

**How to reproduce**

* For Linux-based operating systems: provide a script for clear docker container from the official image
* For anything else: steps to reproduce on as much as possible clear system

>>  /config.xml', line 7 column 1, >> common  <clickhouse> root element

10. BaseDaemon::initialize(Poco::Util::Application&) @ 0xe3da161 in /usr/bin/clickhouse
11. DB::Server::initialize(Poco::Util::Application&) @ 0xe212a83 in /usr/bin/clickhouse
12. Poco::Util::Application:

**Comment by rschu1ze** [comment]
Could you please include file "/etc/clickhouse-server/config.xml" into this issue? The server complains that something is wrong on line 7.

(I am generally a bit confused by this report. I would really like to help with the issue but it would be great if you could describe more clearly the steps you did and provide some more context. Thanks!)

**Comment by rschu1ze** [comment]
Please re-open in case there is an updtae, thanks!

**Comment by julien-alpaca** [comment]
I am having the same issue. Deployed in k8s. Image: docker.io/bitnami/clickhouse:25.2.1-debian-12-r0


```
Processing configuration file '/opt/bitnami/clickhouse/etc/config.xml'.
Merging configuration file '/opt/bitnami/clickhouse/etc/conf.d/00_default_overrides.xml'.
Poco::Exception. Code: 1000, e.code() = 0, Exception: Failed to preprocess config '/opt/bitnami/clickhouse/etc/config.xml': SAXParseException: Invalid token in line 1 column 18, Stack trace (when copying this message, always include the lines below):

0. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::shared_ptr<Poco::Event> const&, bool) @ 0x0000000014e1f048
1. DB::ConfigProcessor::loadConfig(bool, bool) @ 0x0000000014e1f8f7
2. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000f2280a9
3. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000f178c3b
4. Poco::Util::Application::run() @ 0x0000000017d1d8fa
5. DB::Server::run() @ 0x000000000f178950
6. mainEntryClickHouseServer(int, char**) @ 0x000000000f175a73
7. main @ 0x0000000009eff6e1
8. ? @ 0x00007996d03ec24a
9. ? @ 0x00007996d03ec305
10. _start @ 0x0000000006a9002e
 (version 25.2.1.3085 (official build))
```

**Comment by rschu1ze** [comment]
Could you please include file "/etc/clickhouse-server/config.xml" into this issue? The server complains that something is wrong on line 1.

(I am generally a bit confused by this report. I would really like to help - maybe you could describe more clearly the steps you did and provide some more context. Thanks!)

**Comment by julien-alpaca** [comment]
> Could you please include file "/opt/bitnami/clickhouse/etc/config.xml" into this issue? The server complains that something is wrong on line 1.
> 
> (I am generally a bit confused by this report. I would really like to help - maybe you could describe more clearly the steps you did and provide some more context. Thanks!)

Thanks for helping. After digging up a little bit it seems the config file contains $ sign end of lines.

```
docker run --rm bitnami/clickhouse:25.4.1-debian-12-r0 cat -A /opt/bitnami/clickhouse/etc/config.xml | head -n 20

<?xml version="1.0"?>$
<!--$
  NOTE: User and query level settings are set up in "users.xml" file.$
  If you have accidentally specified user-level settings here, server won't start.$
  You can either move the settings to the right place inside "users.xml" file$
   or add <skip_check_for_incorrect_settings>1</skip_check_for_incorrect_settings> here.$
-->$
<clickhouse><logger><!-- Possible levels [1]:$
$
          - none (turns off logging)$
          - fatal$
          - critical$
          - error$
          - warning$
          - notice$
          - information$

```

**Comment by julien-alpaca** [comment]
> > Could you please include file "/opt/bitnami/clickhouse/etc/config.xml" into this issue? The server complains that something is wrong on line 1.
> > (I am generally a bit confused by this report. I would really like to help - maybe you could describe more clearly the steps you did and provide some more context. Thanks!)
> 
> Thanks for helping. Here are the first lines of the config.xml file:
> 
> ```
> docker run --rm bitnami/clickhouse:25.4.1-debian-12-r0 cat -A /opt/bitnami/clickhouse/etc/config.xml | head -n 20
> 
> <?xml version="1.0"?>
> 
> <clickhouse><logger><!-- Possible levels [1]:
> ```

For context, I am trying to deploy [langfuse helm chart](https://langfuse.com/self-hosting/kubernetes-helm) (which depends on clickhouse) with the default config. Thanks.

**Comment by rschu1ze** [comment]
The issue did not reproduce for me with the latest ClickHouse version.

@julien-alpaca Could you please provide [minimally reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) in the form of a minimal but _full_ config file which does not work?

Please also open a new bug report as it is not clear that the current issue is the same as the original one.

**Comment by julien-alpaca** [comment]
> The issue did not reproduce for me with the latest ClickHouse version.
> 
> [@julien-alpaca](https://github.com/julien-alpaca) Could you please provide [minimally reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) in the form of a minimal but _full_ config file which does not work?
> 
> Please also open a new bug report as it is not clear that the current issue is the same as the original one.

I was able to deploy with the previous version:
`helm install langfuse langfuse/langfuse --version 1.2.4 -n langfuse -f values.yaml`

Thanks.
