### ISSUE TITLE
Does ClickHouse kafka engine support read Avro message without schema register service?

### ISSUE THREAD

**Issue by dongxiao-yang** [ClickHouse/ClickHouse#48684]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

Hi , we are trying to test ClickHouse kafka engine with Avro format , for some reason we don't want to involve confluent Avro schema register service , when I send full Avro message into kafka topic and trying to consume it with ClickHouse kafka engine , I  always get this error 

```
`2023.04.12 08:41:06.464979 [ 1026391 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): std::exception. Code: 1001, type: avro::Exception, e.what() = Invalid data file. Magic does not match: , Stack trace (when copying this message, always include the lines below):

0. avro::DataFileReaderBase::readHeader() @ 0x1889e32b in /usr/bin/clickhouse
1. avro::DataFileReaderBase::DataFileReaderBase(std::__1::unique_ptr<avro::InputStream, std::__1::default_delete<avro::InputStream>>) @ 0x1889e668 in /usr/bin/clickhouse
2. DB::AvroRowInputFormat::readPrefix() @ 0x15426f02 in /usr/bin/clickhouse
3. DB::IRowInputFormat::generate() @ 0x154490f0 in /usr/bin/clickhouse
4. DB::ISource::tryGenerate() @ 0x153d3575 in /usr/bin/clickhouse
5. DB::ISource::work() @ 0x153d3106 in /usr/bin/clickhouse
6. DB::StreamingFormatExecutor::execute() @ 0x153f9644 in /usr/bin/clickhouse
7. DB::KafkaSource::generateImpl() @ 0x14c440c8 in /usr/bin/clickhouse
8. DB::KafkaSource::generate() @ 0x14c4756f in /usr/bin/clickhouse
9. DB::ISource::tryGenerate() @ 0x153d3575 in /usr/bin/clickhouse
10. DB::ISource::work() @ 0x153d3106 in /usr/bin/clickhouse
11. DB::ExecutionThreadContext::executeTask() @ 0x153ee166 in /usr/bin/clickhouse
12. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x153e335c in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x153e1d99 in /usr/bin/clickhouse
14. DB::PipelineExecutor::execute(unsigned long) @ 0x153e1b9d in /usr/bin/clickhouse
15. DB::CompletedPipelineExecutor::execute() @ 0x153e04dd in /usr/bin/clickhouse
16. DB::StorageKafka::streamToViews() @ 0x14c3a02c in /usr/bin/clickhouse
17. DB::StorageKafka::threadFunc(unsigned long) @ 0x14c37461 in /usr/bin/clickhouse
18. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x133abe41 in /usr/bin/clickhouse
19. DB::BackgroundSchedulePool::threadFunction() @ 0x133af40a in /usr/bin/clickhouse
20. ? @ 0x133b032e in /usr/bin/clickhouse
21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe809ef6 in /usr/bin/clickhouse
22. ? @ 0xe80f0c1 in /usr/bin/clickhouse
23. ? @ 0x7f95fa030609 in ?
24. clone @ 0x7f95f9f55133 in ?
 (version 22.12.2.25 (official build))`
```

Looks like ClickHouse is still trying to read kind of 'Header'  from kafka message ,  so can I say for kafka engine , ClickHouse can't parse Avro raw format message without schema register service?

**Comment by PcdPanda** [comment]
Hi @dongxiao-yang, I got the same error, did you resolve it?

**Comment by dongxiao-yang** [comment]
@PcdPanda  we finally use Json instead

**Comment by xinstein** [comment]
Any updates? Does the parsing overhead and storage inefficiency of json format bother you enough to reconsider using avro again?

> @PcdPanda we finally use Json instead

**Comment by PcdPanda** [comment]
I'm not a big fan of Json, so I'm not using any kafka engine but implement my own server parsing data from Kafka and do typical insertions.

**Comment by xinstein** [comment]
> I'm not a big fan of Json, so I'm not using any kafka engine but implement my own server parsing data from Kafka and do typical insertions.

FYI, I ended up migrating to protobuf, the data size is halved compared to schemaless avro
