### ISSUE TITLE
Why has LTS gone from 23.3 2 weeks ago to 22.8

### ISSUE THREAD

**Issue by andycol** [ClickHouse/ClickHouse#48685]
I noticed 2 weeks ago the latest LTS version was 23.3 and then since last week the latest LTS version is back down to 22.8

Curious why that is?

**Comment by tavplubix** [comment]
The latest LTS is 23.3. Where/how did you notice that?

**Comment by andycol** [comment]
> The latest LTS is 23.3. Where/how did you notice that?

on this page 
https://github.com/ClickHouse/ClickHouse/releases
![image](https://user-images.githubusercontent.com/13945173/231434071-da58e45b-ae30-4a96-8cb7-6ccb4ef7530d.png)

**Comment by Felixoid** [comment]
It's just literally the latest release, not the one with the greatest number.

Could you suggest a way how to interact with GitHub releases to avoid such confusion?

**Comment by den-crane** [comment]
BTW, if releases are published the same day, then github displays a release with the biggest release version on the top. So releases are sorted by a day and a release version on https://github.com/ClickHouse/ClickHouse/releases
