### ISSUE TITLE
How to use Clickhouse Token Bloomfilters with Arrays and Like Statement

### ISSUE THREAD

**Issue by Lumotheninja** [ClickHouse/ClickHouse#48681]
How can I leverage bloomfilters on array(string) in Clickhouse.

For example, I have this data structure:

```
create table test_schema.test_table (
partition_time            DateTime64(9
,keys                     Array(String)
) ENGINE = ReplicatedReplacingMergeTree('some/path', '{replica}')
PARTITION BY toYYYYMMDD(partition_time)
TTL toDateTime(partition_time) + toIntervalDay(1)
SETTINGS index_granularity = 8192;
```
and I build a token bloomfilter on keys
```
alter table test_schema.test_table INDEX test_bf_idx `keys` TYPE tokenbf_v1(4096, 2, 0) GRANULARITY 1;
```

When I use the condition `has(keys,'some_key')`, I can see it leveraging the bloom filter. But I could not use the bloomfilter for like queries. I have tried array filter and array join, but still it is not using bloomfilter:
```
where notEmpty(arrayFilter(x -> x LIKE '%some_key%', keys) )
```
and
```
select * from 
(select arrayJoin(keys) as val from schema.table)
where val like '%some_key%'
```

Can someone show me how I can use the token bloomfilter built on an array for LIKE statements, (i.e. use bloomfilter for like statement on an array)

**Comment by CheSema** [comment]
One more thing, I struggle to understand how particular tokenbf_v1 bloomfilters is able to help with like queries. 
In my test example it dropped 0 granules.


That works
```
SET send_logs_level='trace';
select * from test_table WHERE
                    hasToken(arrayStringConcat(keys, '; '), 'key5')
                    SETTINGS force_data_skipping_indices='test_bf_idx';
```


And that also works
```
SET send_logs_level='trace';
select * from test_table WHERE
                    has(keys, 'key1')
                    SETTINGS force_data_skipping_indices='test_bf_idx2'
```
where
test_bf_idx2 is 
`...ADD INDEX test_bf_idx2 keys TYPE tokenbf_v1...`
and I assume that keys is an array of exact tokens. If it is wrong, than you need just materialize such column from column keys.

**Comment by Lumotheninja** [comment]
Hi @den-crane @CheSema thanks for your replies, I have tried it out, and the bloomfilter on arrays in good for exact match and tokenized match, but not for substring match for elements in the array

In the case of exact match on array elements, I find just using plain bloomfilters and the `has(array, elem)` function is sufficient.  

For tokenized match, I find that arrayStringConcat method together with a token_bf on the concatenated array makes "% blahblah %" matching on "prefix_blahblah_postfix". However, if the keys are not tokenized then searching for "cat" in "concatenate will not use the bloomfilter

Maybe I will try inverted index for FTS
