### ISSUE TITLE
Catboost evaluation library permission denied when using catboostEvaluate 

### ISSUE THREAD

**Issue by owenzhw** [ClickHouse/ClickHouse#48680]
Hi, I'm trying to deploy clickhouse on a new machine by docker.

However when I finished complie Evaluation library for catboost, I try the SQL as the tutorial did:

`SELECT
    catboostEvaluate('/root/catboost_model.bin', RESOURCE, MGR_ID, ROLE_ROLLUP_1, ROLE_ROLLUP_2, ROLE_DEPTNAME, ROLE_TITLE, ROLE_FAMILY_DESC, ROLE_FAMILY, ROLE_CODE) AS prediction,
    ACTION AS target
FROM amazon_train
LIMIT 1
`

The result got an error:
>std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in posix_stat: failed to determine attributes for the specified path: Permission denied ["/catboost/catboost/libs/model_interface/libcatboostmodel.so"] Cannot print extra info for Poco::Exception (version 22.11.6.44 (official build)) , server ClickHouseNode [uri=http://localhost:8123/default, options={custom_http_params=session_id=DataGrip_0eca8982-3ed6-422c-bfa1-fdc4fba691e6}]@828859528

I think this is an access permission issue and I change it by
`chown -R clickhouse /catboost`

However the error still exist. Anyone could help?

**Comment by rschu1ze** [comment]
Hi, I would like to understand the steps in more detail and ideally be able to reproduce this locally. I assume that you compiled the catboost library according to their [docs](https://catboost.ai/en/docs/concepts/c-plus-plus-api_dynamic-c-pluplus-wrapper). Did you then use the official docker image (which one, specifically) or roll your own? How did you include the catboost library in the image (e.g. via `--mount`)? How does your ClickHouse server configuration file look like? More details and/or a repro are appreciated, thanks!

**Comment by owenzhw** [comment]
Sorry for the late reply. I fixed the problem after I changed the permission for `/root` folder. this is caused by the catboost is compiled under root folder so it also need permission.
