### ISSUE TITLE
Cannot find column less(id, 100) in ActionsDAG result. (UNKNOWN_IDENTIFIER)

### ISSUE THREAD

**Issue by hardstep33** [ClickHouse/ClickHouse#48682]
Good afternoon, I ran into such a problem that I'm trying to select from a view and I'm catching an error. I found how to fix the error - turn off the optimization "setting optimize_read_in_order" , but in my opinion this setting should not throw an exception.

version Clickhouse 23.3.1.2823-lts

example:
https://fiddle.clickhouse.com/66ae12fb-11ee-4684-b07f-531119686419

or
```
drop table if exists default.test_array_joins
;
create table default.test_array_joins
(
    id UInt64 default rowNumberInAllBlocks() + 1,
    arr_1 Array(String),
    arr_2 Array(String),
    arr_3 Array(String),
    arr_4 Array(String)
) engine = MergeTree order by id
;
insert into default.test_array_joins (id,arr_1, arr_2, arr_3, arr_4)
SELECT number,array(randomPrintableASCII(3)),array(randomPrintableASCII(3)),array(randomPrintableASCII(3)),array(randomPrintableASCII(3))
from numbers(1000)
;
create  or replace view default.v4test_array_joins as SELECT * from default.test_array_joins where id != 10
;
select * from default.v4test_array_joins
array join columns('^arr')
where match(arr_4,'a')
  and id < 100
ORDER by id limit 1 by arr_1 settings optimize_read_in_order = 1
```

Another interesting case is if in the where clause add a known true condition first. It's work without errors!)
```
select * from default.v4test_array_joins
array join columns('^arr')
where true and match(arr_4,'a')
  and id < 100
ORDER by id limit 1 by arr_1 settings optimize_read_in_order = 1
```

**Comment by tavplubix** [comment]
A bit simpler example: https://fiddle.clickhouse.com/18fc9813-952b-4fae-94d2-5ab4e00a960b
It was broken between 22.10 (https://fiddle.clickhouse.com/ed81cd19-1a54-4e2f-9e75-570e28f76e76) and 22.11 (https://fiddle.clickhouse.com/33924041-a1b9-46a2-b1fd-0f872fcb8139)

**Comment by hardstep33** [comment]
Another workaround:  convert_query_to_cnf = 1
