### ISSUE TITLE
About We tried using ClickHouse as a remote storage for Prometheus

### ISSUE THREAD

**Issue by lyl2008dsg** [ClickHouse/ClickHouse#4868]
**Use case**
I tried to store metrics with Nested,  and  expected Calculated Growth Rate.
e.g http://www.silota.com/docs/recipes/sql-mom-growth-rate.html

```
CREATE TABLE IF NOT EXISTS app_metrics(
   partition Date DEFAULT toDate(timestamp),
   timestamp DateTime DEFAULT now(),
   instance_id String,
   metric String,
   tags Nested
   (
     key String,
     value String
   ),
   value Float64
  ) ENGINE = MergeTree(partition, (timestamp, metric), 8192);
```
A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**
 Clickhouse is expected to provide functions like MySQL `lag()` or `lead()` ?

**Describe alternatives you've considered**
Or alternatives solution e.g https://rextester.com/ERTQ26880

**Additional context**
We tried using ClickHouse as a remote storage for Prometheus. 
Gauge 、Histogram and so on are satisfied，hower  what should Counter of prometheus do?

ps. https://groups.google.com/forum/#!topic/clickhouse/d5Np4j_nkYk

**Comment by filimonov** [comment]
Thanks for feedback.

lead/lag - you are looking for window functions. They are not supported currently, but there are some workarounds using arrays. Please follow main issue: #1469
