### ISSUE TITLE
Materialized view has no data

### ISSUE THREAD

**Issue by Narzhan** [ClickHouse/ClickHouse#48701]
I've tried to create a materialized view which would aggregate accesses to a given website for each day and which would be aggregated by id of a client. Source data for this view are inserted to table traffic which has following structure:

CREATE TABLE traffic 
( 
`id_client` UInt16,    
`domain_l2` String,   
`geoip_country_code2` String,  
`query` String,   
`server` String,  
`timestamp` DateTime,  
`ttl` UInt16 
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/shard_0/traffic_db', 'replica_00')
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (intHash32(id_client), timestamp)
SAMPLE BY intHash32(id_client)
TTL timestamp + toIntervalDay(11)
SETTINGS index_granularity = 8192; 

For the view I wanted to have a destination table:

CREATE TABLE traffic_daily_aggregated
(
    `domain_l2` String,
    `timestamp` DateTime,
    `sum_hits` AggregateFunction(count),
    `id_client` UInt16
)
ENGINE = AggregatingMergeTree
PARTITION BY domain_l2
ORDER BY (domain_l2, timestamp, id_client)

and the view in question:

CREATE MATERIALIZED VIEW traffic_daily_aggregated_mv
TO traffic_daily_aggregated
AS
SELECT
    toDate(timestamp) AS timestamp,
    domain_l2,
    countState() as sum_hits,
    id_client
FROM traffic
GROUP BY
    domain_l2,
    timestamp,
    id_client

However I don't see any data in the table traffic_daily_aggregated after some data were inserted to the source table. I'm not sure whether the Replicated table is the reason that I cannot see any data. I've also tried changing the engine on the destination table traffic_daily_aggregated to ReplicatedMergeTree('/clickhouse/tables/shard_0/traffic_db_mv', 'replica_00') but to no avail. I'm running two CH instance 21.3 with 3 Zookeepers.

**Comment by den-crane** [comment]
yes, the engine should be  ReplicatedAggregatingMergeTree

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by Narzhan** [comment]
If I've already tried this are there any steps I can make to troubleshoot why there are still no data in either table?

**Comment by den-crane** [comment]
It works fine for me https://fiddle.clickhouse.com/59e56d03-7308-4ed4-88ab-2c68c22beced

**Comment by Narzhan** [comment]
I've tried to use a Materialized view without the destination table using the ReplicatedAggregatingMergeTree engine and for some reason it is working now.
