### ISSUE TITLE
Enhance usability of `INTO OUTFILE` clause for SELECT queries

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#48716]
**Use case**

There is a possibility to write `INTO OUTFILE` to export the result of SELECT query, but if a file with a specified name exists on filesystem - there will be an exception.

**Describe the solution you'd like**

Add another keywords to parser to be able to write something like `INTO OUTFILE APPEND 'file.txt'` or `INTO OUTFILE REWRITE 'file.txt'`

**Describe alternatives you've considered**

Probably we can add a user-level setting instead?

**Comment by alexey-milovidov** [comment]
It will sound better as `APPEND INTO OUTFILE`, not `INTO OUTFILE ... APPEND`.
But it should also be considered with OVERWRITE option.
