### ISSUE TITLE
Support embedded indexes in Parquet

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#48725]
Use column indexes from Parquet for faster query execution

Reference:
https://github.com/apache/parquet-format/blob/2a481fe1aad64ff770e21734533bb7ef5a057dac/PageIndex.md
https://stackoverflow.com/questions/26909543/index-in-parquet

**Comment by danthegoodman1** [comment]
Probably related to https://github.com/ClickHouse/ClickHouse/issues/23297

**Comment by alexey-milovidov** [comment]
It is implemented.
