### ISSUE TITLE
clickhouse-client timings output file instead of stderr

### ISSUE THREAD

**Issue by jangorecki** [ClickHouse/ClickHouse#4872]
Due to the issues related to `query_log` table reported in #4518 I am measuring timings of queries using `clickhouse-client -t` argument, as suggested in documentation.
```
  -t [ --time ]                         print query execution time to stderr in
                                        non-interactive mode (for benchmarks)
```
Precisely speaking, I am redirecting STDERR to a file so I can extract timings in automated manner.
```sh
cat "clickhouse/groupby-clickhouse.sql" | clickhouse-client -t -mn --max_memory_usage=$CH_MEM --format=Pretty --output_format_pretty_max_rows 1 2> clickhouse/log/groupby_G2_1e9_1e2_0_0.out
```
This works quite well
```sh
cat clickhouse/log/groupby_G2_1e9_1e2_0_0.out 
#45.763
#2.864
#...
```
as long as there is no real error raised by clickhouse-client, then file looks like
```sh
cat clickhouse/log/groupby_G2_1e9_2e0_0_0.out
#36.362
#2.290
#...
#197.714
#Error on processing query: SELECT id3, sum(v1) AS v1, avg(v3) AS v3 FROM G2_1e9_2e0_0_0 GROUP BY id3;
#Code: 32, e.displayText() = DB::Exception: Attempt to read after eof: while receiving packet from localhost:9000, 127.0.0.1, Stack trace:
```
In such cases my log files are useless as they cannot be automatically processed.

----

I would like to request an extra argument to `clickhouse-client`, lets say `tout` (or `tfile`), to provide a file name to write timings, rather than using STDERR, which to be fair, should not be used for storing query timings.

**Comment by jangorecki** [comment]
any chance to have this feature incorporated? seems to be pretty straightforward. `query_log` doesn't seems to be reliable, as explained in linked issue.

**Comment by nvartolomei** [comment]
Workaround, if you don’t want to wait for this feature/fix: generate query ids, then sleep for few seconds flush logs and get timings from query log table.

**Comment by alexey-milovidov** [comment]
> any chance to have this feature incorporated?

It's quite easy to implement, the chance is high. But this feature request is not assigned to anyone in my team right now.

**Comment by alexey-milovidov** [comment]
Also you can use `grep -P '^\d'` to preprocess your file.

**Comment by alexey-milovidov** [comment]
I treat this feature request as having very low priority.
It targets a very specific use case and a workaround is easy.

**Comment by jangorecki** [comment]
@alexey-milovidov could you provide PR I'd that resolved this issue? Or a least link to documentation about the feature.

**Comment by alexey-milovidov** [comment]
@jangorecki I'm closing it because no one is willing to implement it in 3.5 years.
I also don't need this feature. If you need this feature, you can implement it.

**Comment by jangorecki** [comment]
@alexey-milovidov that's fine, just the status "closed as completed" was misleading, therefore my question.
