### ISSUE TITLE
Is there a way to change the key value of the tuple by joining it with the code table?

### ISSUE THREAD

**Issue by hongym7** [ClickHouse/ClickHouse#48733]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

Is there a way to change the key value of the tuple by joining it with the code table?

A table

subject           context (Type : Object('json'))
Hello             {"A" : 0, "B":1, "C"10}
Hi                  {"A" : 0, "B":1, "C"10}
Bye                {"A" : 0, "B":1, "C"10}

B table

code            new_code
A                       AAA01
B                       ABA02
C                       BBB01

I wanna get below result

Hello             {"AAA01" : 0, "ABA02":1, "BBB01"10}
Hi                  {"AAA01" : 0, "ABA02":1, "BBB01"10}
Bye                {"AAA01" : 0, "ABA02":1, "BBB01"10}

**Comment by nickitat** [comment]
pls provide an example on SQL with the source tables and desired result table

**Comment by den-crane** [comment]
no info
