### ISSUE TITLE
How to update LTS version to newest LTS version

### ISSUE THREAD

**Issue by Mall0c** [ClickHouse/ClickHouse#48743]
The documentation (https://clickhouse.com/docs/en/operations/update#multiple-clickhouse-server-versions-in-a-cluster) states:

> We make an effort to maintain a one-year compatibility window (which includes 2 LTS versions). This means that any two versions should be able to work together in a cluster if the difference between them is less than one year (or if there are less than two LTS versions between them). However, it is recommended to upgrade all members of a cluster to the same version as quickly as possible, as some minor issues are possible (like slowdown of distributed queries, retriable errors in some background operations in ReplicatedMergeTree, etc).
> 
> We never recommend running different versions in the same cluster when the release dates are more than one year. While we do not expect that you will have data loss, the cluster may become unusable

Currently I am using 22.3.2 in a cluster with a single shard and three replicas. I am not quite sure about the wording in the documentation: can I update from 22.3.2 to 23.3 directly? There are less than two LTS versions between them, exactly one: 22.8. But still I am not 100% safe if I understand the text correctly. So should I do 22.3.2 -> 23.3 or should I do 22.3.2 -> 22.8 -> 23.3?

Thanks

**Comment by den-crane** [comment]
you can update from 22.3.2 to 23.3 directly

Be careful, test  23.3 in your stage environment. There are plenty issues and backward incompatibilities. Your application can be incompatible with 23.3.
