### ISSUE TITLE
When there are a large number of mergeTree tables , the database startup speed does not meet the expectation.

### ISSUE THREAD

**Issue by h1k** [ClickHouse/ClickHouse#48742]
(you don't have to strictly follow this form)

**Describe the situation**
When merge_tree_metadata_cache is enabled, the database startup speed does not meet the expectation.
**How to reproduce**
8 clickhouse-server (4 shards 、 2 replications) and 6 clickhouse-keeper (3 + 3 clusters)
Generate 100,000 replication merge tree tables. (Each table contains about 30 to 60 fields, excluding the insert operation). After the clickhouse-server service is restarted, it takes 8 hours to complete the startup.

* Which ClickHouse server version to use
Release v23.3.1.2823-lts

* `CREATE TABLE` statements for all tables involved
like this:
```
create table default.test1  (
field1 Nullable(String) ,
field2 Nullable(String) ,
field3 Nullable(String) ,
...) Engine= ReplicatedMergeTree('/clickhouse/tables/databasename/test1/{shard}', '{replica}') order by tuple() settings 
 use_metadata_cache=true;
```

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?
I hope it to be completed in less than 10 minutes,
Because of the test results mentioned in this PR, it can achieve this boot speed.
#https://github.com/ClickHouse/ClickHouse/pull/32928

**Additional context**
My guess is that When there is no data in the table, the table metadata is not cached because no cache information is found in system.merge_tree_metadata_cache. 
In the future, I will add data to these tables and see the startup effect.
Are there any parameters that can be configured for optimization? I don't have much cache-related information.

**Comment by den-crane** [comment]
see https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/

**Comment by den-crane** [comment]
it is expected that you have about 100 replicated tables. By design.

**Comment by den-crane** [comment]
it is expected that you have less than 100 replicated tables. By design.

**Comment by h1k** [comment]
Thank you for the answer. I would like to add that I have about 500,000 tables, and the amount of data in each table is about 30 million. Most tables are written once and queried multiple times in real time. I want to guarantee query performance without losing data. Would the log family engine be the right type? Or is there a more suitable engine?

> 请参阅https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/

**Comment by h1k** [comment]
> > have about 500,000 tables, and the amount of data in each table is about 30 million.
> 
> **You should store all of them in a single table.**
> 
> > I want to guarantee query performance without losing data. Would the log family engine be the right type? Or is there a more suitable engine?
> 
> No. Engine Log does not guarantee data consistency/durability.

The 500,000 tables are independent, and the table structure is different.

**Comment by den-crane** [comment]
>The 500,000 tables are independent, and the table structure is different.

It does not matter. Make it the same.
