### ISSUE TITLE
When using s3 zero copy, the files of different tables are in the same directory of S3

### ISSUE THREAD

**Issue by coulsonm** [ClickHouse/ClickHouse#48747]
**Describe what's wrong**

I am tring s3 zero copy to save  disk spaces. Now All files are in the same level directory of S3 even though they belong to different tables. It's difficult to clean up the specified table data.

**Does it reproduce on recent release?**

On version 23.3

**How to reproduce**
Any table used s3 zero copy.
Is there any way to keep the directory consistent with the local disk？Is there any other good way to use it?

**Comment by den-crane** [comment]
It's not related to zero copy.
By design all objects of all tables are stored in the same directory of S3 bucket.

>It's difficult to clean up the specified table data.
?? You don't need it. Use `drop table` or `truncate` Clickhouse removes objects by itself.

>Is there any way to keep the directory consistent with the local disk？Is there any other good way to use it?

No
