### ISSUE TITLE
Should roaring bitmaps be optimized?

### ISSUE THREAD

**Issue by sebver** [ClickHouse/ClickHouse#48751]
Roaring bitmaps have a `run_optimize` [function](https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/roaring.h#L483) that can make them quite a bit more space efficient. For example when adding a 0 .. 1000 range a bitmap can be compressed from 2016 to 15 bytes.

However I don't see this function called anywhere in clickhouse's code. I can imagine this is because of performance issues, or because we already have compression anyway. But I still wanted to check: this is deliberate and not an oversight?

**Comment by UnamedRus** [comment]
It's not 2016 bytes, but still much bigger than 15 bytes.
Even if there is some performance consideration about not optimizing, i think it make sense to do it before serialization. (ie before writing to disk or sending over network)

```
SELECT byteSize(groupBitmapState(number))
FROM numbers(1000)

Query id: 9267e838-92b9-4acc-aade-fa6c3b3b680f

┌─byteSize(groupBitmapState(number))─┐
│                                304 │
└────────────────────────────────────┘
```

**Comment by sebver** [comment]
I agree, just to show CH can already work with the optimized version, I manually optimized a bitmap:
```
SELECT bitmapToArray(CAST(unhex('010F3B300000010000E70301000000E703'), 'AggregateFunction(groupBitmap, UInt16)'))
```
This will give numbers 0 to 1000 and is only 17 bytes.

For us it could make a big difference because we (eventually) end up with bitmaps with long sequences of numbers.

**Comment by Algunenano** [comment]
It was done in https://github.com/ClickHouse/ClickHouse/pull/55044
