### ISSUE TITLE
ClickHouse won't parse url-encoded tabs and newlines in query parameters over the HTTP interface

### ISSUE THREAD

**Issue by michaelsmithxyz** [ClickHouse/ClickHouse#48769]
There's some confusing behavior around parsing tabs and newlines in strings when they're supplied in query parameters over the HTTP interface (testing on version 22.8).

Including a URL-encoded literal tab in a string param fails:
```
➜ curl -sS "http://localhost:8123?param_arg1=abc%09123" -d "select {arg1:String} format JSONEachRow"
Code: 457. DB::Exception: Value abc	123 cannot be parsed as String for query parameter 'arg1' because it isn't parsed completely: only 3 of 7 bytes was parsed: abc. (BAD_QUERY_PARAMETER) (version 22.8.13.20 (official build))
```

Including the tab as an escape sequence in a param works:
```
➜ curl -sS "http://localhost:8123?param_arg1=abc\t123" -d "select {arg1:String} format JSONEachRow"
{"_CAST('abc\\t123', 'String')":"abc\t123"}
```

Including the tab in the query as a literal value works:
```
➜ curl -sS "http://localhost:8123" -d "select 'abc	123' format JSONEachRow"
{"'abc\\t123'":"abc\t123"}
```

I'd expect a URL-encoded tab literal in a query parameter string to behave the same as a tab literal in an in-query string literal.

Skimming the code (working down from `ReplaceQueryParamVisitor`) it seems like the string-parsing code used for params has special handling for tabs and newlines, but it's not clear from the context (to me anyway!) why that is (assuming I have the right spot!): https://github.com/ClickHouse/ClickHouse/blob/267cd097bfba60b684cc3e7b7d73c506642f9c0d/src/IO/ReadHelpers.cpp#L505

**Comment by alexey-milovidov** [comment]
Query parameters are parsed from the "escaped" format, similar to TSV.
This gives benefits, such as the possibility to unambiguously parse NULLs as `\N`.

Therefore, the tab character should be encoded as `\t` or `\` and tab. 
Then, consequently, it has to be encoded as `%5Ct` or as `%5C%09`.
