### ISSUE TITLE
Unable to connect from tableau server 2021.3.8 error FAB9A2C5

### ISSUE THREAD

**Issue by gnaveenkr** [ClickHouse/ClickHouse#48761]
An error occurred while communicating with ClickHouse JDBC by ANALYTIKA PLUS
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
connect timed out, server ClickHouseNode(addr=, db=default)@-44420824
Unable to connect to the ClickHouse JDBC by ANALYTIKA PLUS server "". Check that the server is running and that you have access privileges to the requested database.
Connector Class: clickhouse_jdbc, Version: 0.2.5

I am able to connect from tableau desktop 2021.3.8 but when I copy the
jdbc jar file clickhouse-jdbc-0.3.2-patch8-shaded.jar to C:\Program Files\Tableau\Drivers
taco file clickhouse_jdbc_0.2.6.taco copyied  to C:\Program Files\Tableau\Connectors

**Comment by tavplubix** [comment]
Check that the server is running and that you have access privileges to the requested database.

Also, it could be an issue with ANALYTIKA PLUS (whatever it is) or Tableau or Windows

Anyway, provided information is not enough to help

**Comment by vfilatov** [comment]
This is the logs from server side.
2023.04.13 11:41:45.777922 [ 3416145 ] {3d80520c-3125-4d88-923d-e8939a1b89a7} <Error> ReadWriteBufferFromHTTP: HTTP request to `http://127.0.0.1:9019/ping?use_connection_pooling=1` failed at try 1/1 with bytes read: 0
/unknown. Error: Connection refused. (Current backoff wait is 100/1600 ms)
2023.04.13 11:41:46.035603 [ 3416145 ] {3d80520c-3125-4d88-923d-e8939a1b89a7} <Error> executeQuery: Code: 410. DB::Exception: clickhouse-jdbc-bridge is not running. Please, start it manually. (EXTERNAL_SERVER_IS_NOT_RESPONDING) (version 23.3.1.2823 (official build)) (from 10.30.129.67:4832) (in query: select concat('jdbc(''', name, ''')') as TABLE_SCHEM, null as TABLE_CATALOG from jdbc('', 'SHOW DATASOURCES') where TABLE_SCHEM like '%' order by name)

Is there a way to avoid queries from `jdbc('', 'SHOW DATASOURCES')`
