### ISSUE TITLE
Implement `SYSTEM DROP [DATABASE] REPLICA 'replicaname' FROM SHARD 'shardname'`

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#48788]
**Use case**

The query `SYSTEM DROP REPLICA` may take long time to finish (up to several hours, because we need to delete all replica related nodes from [Zoo]Keeper. Additionally there could be a lot of tables, databases, etc and during this deletion process the server may be in some inconsistent state - some tables will have a replica, some are not + it is also quite hard to automate this process, because you need to carefully understand the current state. 

**Describe the solution you'd like**

Implement a query to a replica from everywhere (for example one shard) at once. For dropping table replicas we should first mark every replica as lost and only then delete all the nodes from [Zoo]Keeper. 

**Additional context**

Additionally it would be nice if this query will be idempotent, so we can easily retry deletion from external scripts. This behavior could be controlled by a special setting and applicable to all `SYSTEM DROP` commands.

**Comment by tavplubix** [comment]
> up to several hours

It's because the optimization for zero-copy replication is missing, see https://github.com/ClickHouse/ClickHouse/pull/35946. We should fix it.

**Comment by tavplubix** [comment]
> `SYSTEM DROP [DATABASE] REPLICA 'replicaname' FROM SHARD 'shardname'`

See also https://github.com/ClickHouse/ClickHouse/pull/48548:
https://github.com/ClickHouse/ClickHouse/blob/a1fda047f6aa561b0a6ed4b6e15fc57888002570/docs/en/sql-reference/statements/system.md?plain=1#L95-L102

**Comment by tavplubix** [comment]
> Implement a query to a replica from everywhere (for example one shard) at once.

It already works:
```
SYSTEM DROP REPLICA 'replica_name';
SYSTEM DROP DATABASE REPLICA 'shard_name|replica_name';
```

> For dropping table replicas we should first mark every replica as lost and only then delete all the nodes from [Zoo]Keeper.

We already do:
https://github.com/ClickHouse/ClickHouse/blob/467ecf45e12cccfeb200378918636e168a0c5daa/src/Storages/StorageReplicatedMergeTree.cpp#L953-L955

**Comment by nikitamikhaylov** [comment]
@tavplubix About marking replica as lost. I meant we should first mark **every** table replica, then delete all the data from **all** the replicas from [Zoo]Keeper. Not mark and delete for each table, because seems like we don't do this in parallel.

**Comment by tavplubix** [comment]
> About marking replica as lost. I meant we should first mark every table replica, then delete all the data from all the replicas from [Zoo]Keeper. Not mark and delete for each table, because seems like we don't do this in parallel.

What problem is it supposed to solve?

**Comment by nikitamikhaylov** [comment]
Possibly inconsistent state if deletion goes wrong or any exception occur or just deletion take too much time.

**Comment by tavplubix** [comment]
Marking replicas as lost will not solve any consistency issues.
