### ISSUE TITLE
CurrentMetrics::ZooKeeperWatch higher than actual value reported by ZK

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#4881]
Hi,

I've noticed that v19.1.15 reports higher number for `CurrentMetrics::ZooKeeperWatch`, but when looking directly at ZK I see a very different value.

CurrentMetrics::ZooKeeperWatch reports 1290 watches.

ZK server handling this connection reports the following:

```
1 connections watching 668 paths
Total watches:668
```

This is right after a fresh start.

**Comment by alexey-milovidov** [comment]
This is minor issue.

I have quickly checked the code and it looks Ok.
If you really want to debug, you can add debug print every time, `CurrentMetrics::ZooKeeperWatch` is incremented or decremented in ZooKeeperImpl.cpp.

**Comment by nvartolomei** [comment]
I found a few cases of "watch leak". One example is detaching tables, watches are not removed. Re-attaching a table multiple will create 2 watches. On an usual server with some activity these go away on the first event on the watched paths.

This might or might not be related to the original issue. I guess the implications are very minor and the issue can be ignored.

**Comment by alexey-milovidov** [comment]
Some inconsistency in number of watches reported by ClickHouse and ZooKeeper is not an issue.

> My guess is that if a connection setups multiple watches for the same path it is counter only once by ZK.

I have no idea, but the hypothesis is viable.
