### ISSUE TITLE
Support `bitCount` and `bitHammingDistance` for `String` and `FixedString`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#48827]
**Use case**

Vector search databases often use conversion of the vector space into bit-vectors, where every bit represents a subspace of the space divided by random hyperplanes. The hamming distance on these bit-vectors represents an approximation of the distance in the original vector space. The typical size of a bit-vector is 4 * N, where N is the original number of dimensions. It can be significant in size, larger than 256-bit, requiring to use of the FixedString data type.

```
SELECT toFixedString('Hello, world!!!!', 16) AS x, toFixedString('Goodbye, xyz!!!!', 16) AS y, 
    bitAnd(x, y), bitCount(x), bitHammingDistance(x, y)
```

Example:

![annoy](https://user-images.githubusercontent.com/18581488/232365185-edff95b7-fd0f-4744-a7df-385bf09203f9.png)

https://pastila.nl/?06d88bfc/ab814eec85d5bbf8d27496884d95c55d

**Comment by ucasfl** [comment]
@alexey-milovidov For tupleHammingDistance, if the input strings have different size, how to calculate their distance?

**Comment by alexey-milovidov** [comment]
Strings are compared in the same way as if the shorter string is right-padded by zero bytes to the size of the longest string. In other words, every excessive bit of the longer string is compared with zero bit.

Example: let's compare "Hello" and "Hellow":
```
┌─bin('Hello')─────────────────────────────┐
│ 0100100001100101011011000110110001101111 │
└──────────────────────────────────────────┘
┌─bin('Hellow')────────────────────────────────────┐
│ 010010000110010101101100011011000110111101110111 │
└──────────────────────────────────────────────────┘
```

It will be the same as the comparison of "Hello\0" and "Hellow":
```
┌─bin('Hello\0')───────────────────────────────────┐
│ 010010000110010101101100011011000110111100000000 │
└──────────────────────────────────────────────────┘
```

The character `w` has 6 non-zero bits:
```
01110111
```

So, the Hamming distance is 6.

**Comment by blazingbhavneek** [comment]
Hey there! 👋 I'm new to this repository and eager to contribute! 🌟 Could you kindly suggest some entry point or files to look into?

**Comment by alexey-milovidov** [comment]
@ucasfl is already working on it.
