### ISSUE TITLE
`dotProduct` should work for arrays

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#48828]
**Use case**

Vector search databases.

**Implementation**

Currently, it works only for tuples.

```
SELECT dotProduct([1., 2.], [3., 4.])
```

Although it can be easily emulated by the following expression:
```
arraySum((x, y) -> x * y, arr1, arr2)
```

And this expression is quite fast, but there is one downside: if the arguments have Float32 data type, the intermediate expressions, and the result will have Float64 data type.

A dedicated `dotProduct` implementation should keep the calculation within the same data type.
Additionally, it could be further optimized.

**Comment by FFFFFFFHHHHHHH** [comment]
I'd like to do it.
