### ISSUE TITLE
The behavior of filtering by primary key is completely different when "allow_experimental_projection_optimization" is enabled or disabled.

### ISSUE THREAD

**Issue by katigri** [ClickHouse/ClickHouse#48823]
There is a large table with many fields and data. I am performing a simple select query of the form "select count() where id=123", with the table ordered by this id. When I execute this query, magically, it reads 1.17 million rows in approximately 0.3 seconds. However, if I add "allow_experimental_projection_optimization = 0", the query takes only 0.004 seconds to read 41k rows. I did not have this problem with the previous installation (which used version 23.1.1, while the current one uses 23.3.1 and involves migrating data via insert from remote to new physical servers). What should I pay attention to? Where could the problems be?

Please see this link for more information:
https://pastila.nl/?01b84b53/2c765ea83820b70a1218b1ded906cb2b

With "explain", we get the following picture:
https://pastila.nl/?04d0928e/804c59170baf4e3d3f9514fb4f3a4b70

Can you please advise on what to do? The performance of my working cluster has suddenly degraded.

**Comment by katigri** [comment]
Artem Pershin воспроизвел аналогичное поведение на минималках https://fiddle.clickhouse.com/a5d2c546-3bec-45ff-bec7-03bc896b770e

**Comment by den-crane** [comment]
wa  query_plan_optimize_primary_key=0

**Comment by den-crane** [comment]
wa query_plan_optimize_projection=0;

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/46537  @KochetovNicolai
