### ISSUE TITLE
HTTP status code: 500 Received error: Code: 373. DB::Exception: Session is locked by a concurrent client. (SESSION_IS_LOCKED) (version 23.3.1.2823 (official build)) 

### ISSUE THREAD

**Issue by hiking-coder** [ClickHouse/ClickHouse#48829]
version: 23.3.1.2823
Issue:HTTP status code: 500 Received error: Code: 373. DB::Exception: Session is locked by a concurrent client. (SESSION_IS_LOCKED) (version 23.3.1.2823 (official build)) 

I connected to tableau through the universal ODBC, but found that after the multi-tab workbook was published, I queried the report of the first tab without an error, but if at this time when I click to switch to another tab, the Session is locked error is reported, is there any way to solve it
![企业微信截图_16814601308959](https://user-images.githubusercontent.com/83748516/232367057-b667dcf6-23e6-4b9f-aef9-8a3e02bbdd0a.png)

**Comment by mshustov** [comment]
@hiking-coder what ODBC driver version do you use? I'd expect [the latest version](https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.2.1.20220905) to have the fix https://github.com/ClickHouse/clickhouse-odbc/pull/398

**Comment by hiking-coder** [comment]
> @hiking-coder what ODBC driver version do you use? I'd expect [the latest version](https://github.com/ClickHouse/clickhouse-odbc/releases/tag/v1.2.1.20220905) to have the fix. see [ClickHouse/clickhouse-odbc#398](https://github.com/ClickHouse/clickhouse-odbc/pull/398)

Hello, I installed the ODBC version as follows, is it the latest version, the current situation, sometimes report the above error, sometimes not, stability is average
![image](https://user-images.githubusercontent.com/83748516/232641508-45c93815-c7e8-4acf-8fe5-bc1adc4d2449.png)

**Comment by mshustov** [comment]
@hiking-coder, do you mind transferring the issue to [ODBC driver](https://github.com/ClickHouse/clickhouse-odbc/) repository?

**Comment by hiking-coder** [comment]
> @hiking-coder, do you mind transferring the issue to [ODBC driver](https://github.com/ClickHouse/clickhouse-odbc/) repository?

I don't mind, just hope to fix the problem, thanks
