### ISSUE TITLE
How clickhouse respect alter delete and insert order 

### ISSUE THREAD

**Issue by pulina** [ClickHouse/ClickHouse#48836]
I have some ETL task that collects data and insert them into clickhouse (22.3.* version). Typically data are inserted into distributed + replicated table (4x4) in bathes. If there is some problem with one or more batches we need to reprocess some of them. Data in reprocessed batch may be same as data inserted before or differ, entirely or partially. Reprocess may occur when we spot problem after few minutes or few days there is no rule here (Mention this to address possibile problem with deduplication mechanism). On reprocessing we do query like: 

```
ALTER TABLE table ON CLUSTER cluster DELETE 
WHERE event_date > {batch_start_date} AND event_date <= {batch_end_date}
```

This will create mutation and my question is whenever execution time of this mutation influence insert that occurs right after ALTER TABLE query?  If data inserted after ALTER QUERY called and before actual execution of mutation may disappear if they meet WHERE clause conditions?

**Comment by Algunenano** [comment]
For MergeTree tables any part has a `data_version` number which related to when the part was created and what mutations are pending to be applied.

Let's say that currently your parts are in `data_version=5` and you send a mutation (delete, replace, whatever). Any new part that is inserted will have `data_version=6`, that is they don't need to apply anything, while old parts will be "mutated" in the background from version 5 to version 6 by applying the query.
So data inserted before the mutation was sent receives the value of 5 and will be mutated. Data inserted after the mutation was sent will receive the value of 6 and won't be mutation.

**Comment by pulina** [comment]
Ok and after that there probably will be some part merging and we will end up with correct amount of data in single partition.  Than you.

**Comment by Algunenano** [comment]
> Ok and after that there probably will be some part merging and we will end up with correct amount of data in single partition.

Yes. And merges only happen across parts with the same `data_version`, so before merging old data with new data the old one needs to be mutated.
