### ISSUE TITLE
Is Clickhouse TTL by tumbling window or sliding window

### ISSUE THREAD

**Issue by Lumotheninja** [ClickHouse/ClickHouse#48839]
For Clickhouse, when we apply TTL say toDateTime(partition_time) + toIntervalDay(1),

lets say now is 17 April 2023 17:39:00 in GMT+8, does it means the data is guaranteed for past 24 hours, or from 17 April 2023 00:00:00 until present or maybe even 17 April 2023 00:00:00 until present?

**Comment by den-crane** [comment]
`toDateTime(partition_time) + toIntervalDay(1)` -- "slide"
`toSartOfWeek(toDateTime(partition_time)) + toIntervalDay(1)` -- "tumble"

slide is not read slide. TTL works eventually. So data will be removed someday.
