### ISSUE TITLE
```move_factor``` no effect, one of disk usage is still high

### ISSUE THREAD

**Issue by ChaoHsupin** [ClickHouse/ClickHouse#48847]
```move_factor```  had no effect. I set it 0.1,  but disk used over 90% . I don't know if there is a configuration error.

clickhouse image version: 22.2.3.5
config:
````
<policies>
          <default>
            <volumes>
              <ssd_volume>
                <disk>ssd</disk>
              </ssd_volume>
            </volumes>
          </default>
          <hdd0_hdd1_only>
                <volumes>
                  <hdd0_hdd1_volume>
                    <disk>hdd0</disk>
                    <disk>hdd1</disk>
                  </hdd0_hdd1_volume>
                </volumes>
                <move_factor>0.1</move_factor>
          </hdd0_hdd1_only>
.....
<policies>
````

query in ```system.storage_policies```
I never used policy with hdd0_only、hdd1_only or hot_and_cold；
![image](https://user-images.githubusercontent.com/34222824/232480742-2be72323-dd93-4614-8d1b-ad7d2db05f64.png)

in host
![image](https://user-images.githubusercontent.com/34222824/232481252-5319e5c8-02a1-48ad-8ad6-b67228399e55.png)

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by CheSema** [comment]
Hi.

As I see in the [doc](https://clickhouse.com/docs/en/operations/system-tables/storage_policies).
> move_factor ([Float64](https://clickhouse.com/docs/en/sql-reference/data-types/float)) — Ratio of free disk space. When the ratio exceeds the value of configuration parameter, ClickHouse start to move data to the next volume in order.

Your data is moved in background from hdd0 to hdd1 when hdd0 is full more that 90%. I want to highlight that it does not work in opposite direction. It is not supposed that data is moved from hdd1 to hdd0 within move_factor settings. May be you need to consider apply some TTL roles here to free the space from hdd1.

**Comment by CheSema** [comment]
It seems like I WAS WRONG in my first answer.

The [doc](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree)

> move_factor — when the amount of available space gets lower than this factor, data automatically starts to move on **the next volume** if any (by default, 0.1). ClickHouse sorts existing parts by size from largest to smallest (in descending order) and selects parts with the total size that is sufficient to meet the move_factor condition. If the total size of all parts is insufficient, all parts will be moved.

> In the background, parts are moved between volumes on the basis of the amount of free space (move_factor parameter) according to the order the volumes are declared in the configuration file. **Data is never transferred from the last one and into the first one**. One may use system tables [system.part_log](https://clickhouse.com/docs/en/operations/system-tables/part_log#system_tables-part-log) (field type = MOVE_PART) and [system.parts](https://clickhouse.com/docs/en/operations/system-tables/parts#system_tables-parts) (fields path and disk) to monitor background moves. Also, the detailed information can be found in server logs.

In your case only one volume exists. No moving happens. But still, only one direction for moving exists.

**Comment by ChaoHsupin** [comment]
> It seems like I WAS WRONG in my first answer.
> 
> The [doc](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree)
> 
> > move_factor — when the amount of available space gets lower than this factor, data automatically starts to move on **the next volume** if any (by default, 0.1). ClickHouse sorts existing parts by size from largest to smallest (in descending order) and selects parts with the total size that is sufficient to meet the move_factor condition. If the total size of all parts is insufficient, all parts will be moved.
> 
> > In the background, parts are moved between volumes on the basis of the amount of free space (move_factor parameter) according to the order the volumes are declared in the configuration file. **Data is never transferred from the last one and into the first one**. One may use system tables [system.part_log](https://clickhouse.com/docs/en/operations/system-tables/part_log#system_tables-part-log) (field type = MOVE_PART) and [system.parts](https://clickhouse.com/docs/en/operations/system-tables/parts#system_tables-parts) (fields path and disk) to monitor background moves. Also, the detailed information can be found in server logs.
> 
> In your case only one volume exists. No moving happens. But still, only one direction for moving exists.

@CheSema Thanks for your reply. so  between  disk no ```move_factor``` config item. reference you doc, i discovery config item about ```load_balancing``` can be balancing between disk.
