### ISSUE TITLE
Add handshake timeout setting

### ISSUE THREAD

**Issue by ekonkov** [ClickHouse/ClickHouse#48854]
I believe it is a good idea to add protocol-level timeout for receiving HELLO-packet from remote server -  let's call it handshake timeout.

It should help to fail fast and try with other replica in cases when server is able to respond on network level but dramatically overloaded and unable to handle query.

**Comment by Avogar** [comment]
I am working on it. What units will be better for this setting? Seconds (like in `connect_timeput/receive_timeout` or milliseconds (like in `connect_timeout_with_failover_ms`)?

**Comment by ekonkov** [comment]
I believe it is a good idea to stick with milliseconds.
