### ISSUE TITLE
Clickhouse in Kubernetes GKE

### ISSUE THREAD

**Issue by bzon** [ClickHouse/ClickHouse#4886]
We set up a replicated Clickhouse in GKE with persistent volumes. It consists of x number of statefulsets (number of shards), 1 headless service for discovery and 1 statefulset for zookeeper. Scaling will be manual which requires updating the config map and hardcoding the Clickhouses hosts' addresses. We also use Prometheus to watch the performance of the cluster. We use replicated merge tree tables for write and distributed tables for read.

We ran some benchmark and it's all good.

Our worry now is just the operation cost of maintaining it because it's not auto scalable. Though we are experienced in Kubernetes, we are not that much with Clickhouse operations. We want to know if there is some stuff to consider before we head to production.

* Schema Migration best practices.
* We expect billions of rows per day.
* VM sizing. Zookeeper and Clickhouse run on specific node groups. How many instances do we need for each? How much CPU and ram.
* Disk sizing.
* Zookeeper best practices - this is the [YAML](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#creating-a-zookeeper-ensemble) that we based our Zookeeper cluster on. Is there any existing config in here that we should be aware of increasing or new config to add as per [the official doc](https://clickhouse.yandex/docs/en/operations/tips/)?

Thanks, folks. 🎉

**Comment by filimonov** [comment]
[Altinity](https://github.com/Altinity) ( [website](http://altinity.com) ) is currently working on clickhouse operator for Kurbenetes. That should automate most of ClickHouse-specific tasks.

Please check that  https://github.com/Altinity/clickhouse-operator/ (beta stage currently), any feedback/review would be helpful especially if you have Kubernetes expertise.

**Comment by bzon** [comment]
@filimonov I actually tried it out and it's superb. But we are going to production in a couple of months so we really can't use it.

**Comment by alex-zaitsev** [comment]
> @filimonov I actually tried it out and it's superb. But we are going to production in a couple of months so we really can't use it.

@bzon , what features are you missing in Altinity operator? We can pay more attention on those to make it useful earlier for you.

**Comment by bzon** [comment]
@alex-zaitsev the most important thing is proven stability and production scaling patterns (documentation). Think use cases for production workloads at a massive scale. Basically, the best practices in clickhouse operational work that clickhouse operator is solving and how does it do it.

**Comment by alex-zaitsev** [comment]
@bzon This is exactly what we are planning to do. The core functionality is pretty much complete. We should have 0.2 release with core functionality complete in a few days, and switch to testing and operational documentation after that.

What is your use case? Are you going to deploy many ClickHouse clusters, or a single cluster with many nodes?

**Comment by bzon** [comment]
@alex-zaitsev Perfect! We currently have a single Clickhouse cluster to serve 1 billion rows per day.
