### ISSUE TITLE
Different CityHash64 results in Clickhouse and in Java for integers

### ISSUE THREAD

**Issue by timoha199490** [ClickHouse/ClickHouse#48869]
Hi everyone!

I ran into a problem. When i use clickhouse cityhash64 function for integer number, i get next value 
for ex
SELECT cityHash64(400) 
400 -> 7486062792514096083
But when i try to get the same result in java, i can't.  I'm using CityHash_v1_0_2. 
For string i can get the same result, in java and in clickhouse. But when i try to generate hash for integer number, results is different. 
So, question is - what is algorithm to create the same hash with java code as it is on clickhouse?

**Comment by den-crane** [comment]
see https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseCityHash.java

https://github.com/ClickHouse/clickhouse-java/issues/610
https://github.com/ClickHouse/ClickHouse/issues/22696

**Comment by timoha199490** [comment]
> see https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseCityHash.java
> 
> [ClickHouse/clickhouse-java#610](https://github.com/ClickHouse/clickhouse-java/issues/610) #22696

I've already seen that links, in first case i don't see cityhash64 method. In second case i found information only about hash for string.
I've read much information, but haven't found info about hash for integer number =(

**Comment by rschu1ze** [comment]
@timoha199490 Could you please clarify if you mean by "try to get the same result in java"
- hashing with a standalone Java implementation of CityHash or
- hashing with the CityHash implementation of clickhouse-java which @den-crane linked (https://github.com/ClickHouse/ClickHouse/issues/48869#issuecomment-1511953252)?

I think you know already that ClickHouse uses an older version of CityHash, see
- https://github.com/ClickHouse/ClickHouse/blob/fbe7df73a24733f4ce0b133cb83b8acf962398a3/contrib/cityhash102/include/city.h#L50
- https://clickhouse.com/docs/en/native-protocol/hash

I am not a Java developer, so just as a wild guess: could you check if it has to do with the default signedness of Java integers? The cityHash SQL function is implemented here: https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/FunctionsHashing.h - in case of doubt compare the differences to the Java code at source level :-)

**Comment by timoha199490** [comment]
@rschu1ze 
Ok, i'll try to explain. I'm using 1.0.2 version of hash. I've got code here https://github.com/dpoluyanov/achord/blob/master/src/main/java/com/github/mangelion/achord/CityHash_v1_0_2.java
Hash for string value '400' in clickhouse:
`SELECT cityHash64('400')  result -> 2833628431030933762`

hash for string value '400' in java while using 1.0.2 cityhash64:
`String stringForHash = "400";
        long result = CityHash64.cityHash64(stringForHash.getBytes(StandardCharsets.UTF_8), 0, stringForHash.getBytes(StandardCharsets.UTF_8).length);`
`result -> 2833628431030933762`
In first case for string value it works correct.

In second case it looks next
Clickhouse hash:
`SELECT cityHash64(400)  result -> 7486062792514096083`

hash for integer value 400 in java while using 1.0.2 cityhash64:

`Integer numForHash = 400;`
`byte[] numBytes = new byte[1];`
`numBytes[0] = numForHash.byteValue();`
`long result2 = CityHash64.cityHash64(numBytes, 0, numBytes.length);`
`result - >  -5514707915076938675`

It looks like i'm using wrong way to send bytes of integer value to hash function. And  can't get the same result in clickhouse and java for integer.

**Comment by alexey-milovidov** [comment]
The number 400 does not fit in a single byte, therefore the Java code is incorrect.

**Comment by alexey-milovidov** [comment]
Let's try this:

```
Integer numForHash = 400;
byte[] numBytes = ByteBuffer.allocate(Integer.BYTES).putInt(numForHash).array();
long result2 = CityHash64.cityHash64(numBytes, 0, numBytes.length);
System.out.println(result2); // Output: 7486062792514096083
```

![Screenshot_20230419_103533](https://user-images.githubusercontent.com/18581488/233018022-cc21d852-19d5-4757-8b97-04d1871579da.png)

**Comment by timoha199490** [comment]
Thanks a lot! As i thought, i used wrong way to create byte array. Thank you for correct code!

**Comment by Yxang** [comment]
I find a problem occurs when java `byte` or `int` is transformed to `long` when the sign is carried into a longer data type, while our intention is not to carry this sign to match the corresponding C code's behavior. My issue occurs at function `Fetch32` calls. Fix could be changing `Fetch32(s, index)` expression into `Fetch32(s, index) & 0xFFFFFFFFL`.

Hope this would help.
