### ISSUE TITLE
test_cache_with_full_disk_space is flaky

### ISSUE THREAD

**Issue by novikd** [ClickHouse/ClickHouse#48860]
https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcHVsbF9yZXF1ZXN0X251bWJlcgpGUk9NIGNoZWNrcwpXSEVSRSAxCi0tICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzIExJS0UgJ0YlJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBwb3NpdGlvbih0ZXN0X25hbWUsICd0ZXN0X2NhY2hlX3dpdGhfZnVsbF9kaXNrX3NwYWNlJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQw==

Report: https://s3.amazonaws.com/clickhouse-test-reports/48787/a1f21a5fc427e860199aa9e1db3c1c4177a340f7/integration_tests__asan__[6/6].html

**Comment by CheSema** [comment]
https://github.com/ClickHouse/ClickHouse/pull/49110#issuecomment-1520338570
after fixing one problem, next one appears.

**Comment by CheSema** [comment]
```
2023.04.27 08:14:18.347288 [ 209 ] {d3e4f537-6565-4ad5-a19e-ba8b7ea1cb9c::all_1_6_1} <Debug> MergeTask::PrepareStage: Merging 6 parts: from all_1_1_0 to all_6_6_0 into Wi
de with storage Full

...

2023.04.27 08:14:20.116772 [ 12 ] {203d8b67-d2b0-4bc5-8fba-5e26bd5ee7cb} <Debug> executeQuery: (from 172.16.1.1:45528) DROP TABLE IF EXISTS s3_test NO DELAY (stage: Complete)

...

2023.04.27 08:14:20.402136 [ 209 ] {} <Trace> default.s3_test (d3e4f537-6565-4ad5-a19e-ba8b7ea1cb9c): Part all_1_6_1 in temporary state can be removed without unlocking shared state
```

That is bad :(
CH started merge. Table is dropped during the merge. The part is temporary. It is deleted by parts destructor. But no s3 data deleted.

Recent changes are done here by me.
https://github.com/ClickHouse/ClickHouse/pull/43866

And now I'm not sure that those changes are correct. 
When part is about to call d-tor in temporary state, 2 followed option exist:
If the part is created within download process, than s3 data has to stay intact.
If the part is created as a result of merge, it consists new data, no one except this replica owns that s3 data, s3 data has to be deleted.

**Comment by CheSema** [comment]
Will continue the work about discovered issues in https://github.com/ClickHouse/ClickHouse/issues/49385
