### ISSUE TITLE
Is building shared libraries disabled?

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#48877]
With 23.3 branch, building flags as "USE_STATIC_LIBRARIES" and "SPLIT_SHARED_LIBRARIES" are all removed. Is building shared libraries disabled which is convinent for developing?

**Comment by rschu1ze** [comment]
Hi @etah000 Yes, recent ClickHouse only allows to create static libraries. This was done to lower the maintenance overhead and costs for CI builds.
