### ISSUE TITLE
Since 23.3 Arrow output format is compressed by default, possible wrong default value of output_format_arrow_compression_method

### ISSUE THREAD

**Issue by Arvamer** [ClickHouse/ClickHouse#48882]
23.3 enabled by default compression for arrow format, which may not be supported by all clients. This is probably mistake, as according to documentation default value for `output_format_arrow_compression_method` is `none`.

**How to reproduce**
* ClickHouse version: 23.3.1

```sql
SELECT default
FROM system.settings
where name = 'output_format_arrow_compression_method'
```

returns `lz4_frame`, while it should be `none`.

**Comment by alexey-milovidov** [comment]
Yes, it was changed to be similar to the Parquet format.
You can change the setting value back or set `compatibility` to `23.2`

**Comment by Arvamer** [comment]
If it was international then documentation should be updated. It still says that default value is `none`.
