### ISSUE TITLE
delete on cluster where doesn't work 

### ISSUE THREAD

**Issue by PierreNowak** [ClickHouse/ClickHouse#48892]
hello, related to this issue [47186](https://github.com/ClickHouse/ClickHouse/issues/47186)

    CREATE TABLE purchases ON CLUSTER 'default'
    (
        `dt` DateTime,
        `customer_id` UInt32,
        `total_spent` Float32
    )
    ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/table_name','{replica}')
    ORDER BY dt
    SETTINGS index_granularity = 8192;

    INSERT INTO purchases SELECT
        now() - randUniform(1, 1000000.),
        number,
        15 + round(randExponential(1 / 10), 2)
    FROM numbers(1000000)

    SELECT * FROM purchases
    dt                 |customer_id|total_spent|
    -------------------+-----------+-----------+
    2023-04-06 21:24:08|     330458|      16.64|
    2023-04-06 21:24:08|     919961|      18.97|
    2023-04-06 21:24:10|     724975|      31.77|
    2023-04-06 21:24:11|     504706|      26.76|
    2023-04-06 21:24:12|     471373|      18.05|
    2023-04-06 21:24:12|     984609|      15.16|
    2023-04-06 21:24:13|     323720|      45.64|
    2023-04-06 21:24:15|     873776|      20.76|
    2023-04-06 21:24:17|     203074|      20.46|

Try to delete with the command in the doc here: https://clickhouse.com/docs/en/sql-reference/statements/delete

    DELETE FROM purchases ON CLUSTER 'default' WHERE total_spent > 20;

Fails with:

    SQL Error [62] [07000]: Code: 62. DB::Exception: Syntax error: failed at position 48 ('WHERE'): WHERE total_spent > 20
    . Expected one of: NO DELAY, SYNC, INTO OUTFILE, FORMAT, SETTINGS, end of query. (SYNTAX_ERROR) (version 23.3.1.30095 (official build))
    , server ClickHouseNode [uri=https://****.us-east-1.aws.clickhouse.cloud:443/default, options={sslmode=STRICT,use_server_time_zone=false,sslkey=,sslcert=,use_time_zone=false,sslrootcert=}]
  
Where this one works fine:

    ALTER TABLE purchases ON CLUSTER 'default'  UPDATE `_row_exists`=0 WHERE total_spent > 20

What's weird is that this one works "fine" aswell ( no ON CLUSTER clause ):

    DELETE FROM purchases WHERE total_spent > 20;

what am I doing wrong :/ ?

    SELECT version()
    
    23.3.1.30095

**Comment by davenger** [comment]
@PierreNowak what client do you use to send queries: is it `clickhouse client` or something else?
I'm asking this because error message `Syntax error: failed at position 48 ('WHERE'): WHERE total_spent > 20` reports position 48 but WHERE token in the query `DELETE FROM purchases ON CLUSTER 'default' WHERE total_spent > 20;` starts at position 43. So my suspicion is that the query somehow gets rewritten by the client.

**Comment by PierreNowak** [comment]
aaaaaah

It is run from dbeaver ( + http port )

I tested on a new version clickhouse-client and it's working.
aaaand I upgraded dbeaver driver and it's working.

thank you

**Comment by mohaa8844** [comment]
Kindly review 
https://kb.altinity.com/altinity-kb-setup-and-maintenance/suspiciously-many-broken-parts/
