### ISSUE TITLE
system.query_log logs S3 Table Credentials

### ISSUE THREAD

**Issue by niger-prequel** [ClickHouse/ClickHouse#48901]
**Describe the issue**
Using AWS Access and Secret keys with [S3 table funcitons](https://clickhouse.com/docs/en/sql-reference/table-functions/s3) in a query . [Some other systems we have used before](https://docs.databricks.com/security/keys/redaction.html) are smart enough to redact those credentials from their query log. 

**How to reproduce**
* Run an S3 table query like `SELECT 
* RUN `SELECT * from s3('https://s3.awsamazone.com/..., 'key', 'secret', 'csv', '...') LIMIT 10`

**Expected behavior**
The credentials would be replaced with `[REDACTED]` in the query log

**Additional context**

**Comment by Ryado** [comment]
This is already the case, I just double checked in ClickHouse Cloud and the secret key is replaced by `[HIDDEN]`

```
[c-violet-ce-86-server-0] 2023.04.19 18:15:31.002115 [ 729 ] {bdbd5712-9905-47bd-a626-8dec3d9fff22} <Debug> executeQuery: (from 105.99.12.145:58608) SELECT * FROM s3('https://storage.googleapis.com/clickhouse-docs/nyc-taxi/trips_0.gz', '<my_key>', '[HIDDEN]', 'TSVWithNames') LIMIT 2 (stage: Complete)
```

Can you share an example along with the ClickHouse version number ?

**Comment by niger-prequel** [comment]
This was version `22.8`. Do you know which release this went out in?

**Comment by alexey-milovidov** [comment]
@niger-prequel watch it on YouTube: https://www.youtube.com/watch?v=sREupr6uc2k
