### ISSUE TITLE
The clickhouse server process exited unexpectedly while reading a file from hdfs

### ISSUE THREAD

**Issue by xywendz** [ClickHouse/ClickHouse#48919]
2023.04.19 12:07:36.361840 [ 24768 ] {} <Fatal> BaseDaemon: (version 23.2.1.2537 (official build), build id: 50BDF08E4BF0B9023E0CA4AEFD09296FFEFF146B) (from thread 24900) Terminate called for uncaught exception:
2023.04.19 12:07:36.361888 [ 24768 ] {} <Fatal> BaseDaemon: Code: 87. DB::Exception: Fail to seek HDFS file: hdfs://cluster/, error: HdfsIOException: InputStreamImpl: cannot read file: /user/hive/warehouse/project=shuhe/day=20230301/part-01586-0814858d-ad43-4c6e-bf15-706afddf48b1-c000, from position 4159494, size: 1048576.  Caused by: HdfsTimeoutException: Read 8 bytes timeout. (CANNOT_SEEK_THROUGH_FILE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0b2315 in /usr/bin/clickhouse
1. ? @ 0x9f0da5e in /usr/bin/clickhouse
2. ? @ 0x12317cf7 in /usr/bin/clickhouse
3. DB::ReadBufferFromHDFS::seek(long, int) @ 0x12316c86 in /usr/bin/clickhouse
4. DB::AsynchronousReadBufferFromHDFS::seek(long, int) @ 0x1239f560 in /usr/bin/clickhouse
5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.361936 [ 24768 ] {} <Fatal> BaseDaemon:
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0b2315 in /usr/bin/clickhouse
1. ? @ 0x9f0da5e in /usr/bin/clickhouse
2. ? @ 0x12317cf7 in /usr/bin/clickhouse
3. DB::ReadBufferFromHDFS::seek(long, int) @ 0x12316c86 in /usr/bin/clickhouse
4. DB::AsynchronousReadBufferFromHDFS::seek(long, int) @ 0x1239f560 in /usr/bin/clickhouse
5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.361962 [ 24768 ] {} <Fatal> BaseDaemon: 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe0b2315 in /usr/bin/clickhouse
1. ? @ 0x9f0da5e in /usr/bin/clickhouse
2. ? @ 0x12317cf7 in /usr/bin/clickhouse
3. DB::ReadBufferFromHDFS::seek(long, int) @ 0x12316c86 in /usr/bin/clickhouse
4. DB::AsynchronousReadBufferFromHDFS::seek(long, int) @ 0x1239f560 in /usr/bin/clickhouse
5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.361980 [ 24768 ] {} <Fatal> BaseDaemon: 1. ? @ 0x9f0da5e in /usr/bin/clickhouse
2. ? @ 0x12317cf7 in /usr/bin/clickhouse
3. DB::ReadBufferFromHDFS::seek(long, int) @ 0x12316c86 in /usr/bin/clickhouse
4. DB::AsynchronousReadBufferFromHDFS::seek(long, int) @ 0x1239f560 in /usr/bin/clickhouse
5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362001 [ 24768 ] {} <Fatal> BaseDaemon: 2. ? @ 0x12317cf7 in /usr/bin/clickhouse
3. DB::ReadBufferFromHDFS::seek(long, int) @ 0x12316c86 in /usr/bin/clickhouse
4. DB::AsynchronousReadBufferFromHDFS::seek(long, int) @ 0x1239f560 in /usr/bin/clickhouse
5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362026 [ 24768 ] {} <Fatal> BaseDaemon: 3. DB::ReadBufferFromHDFS::seek(long, int) @ 0x12316c86 in /usr/bin/clickhouse
4. DB::AsynchronousReadBufferFromHDFS::seek(long, int) @ 0x1239f560 in /usr/bin/clickhouse
5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362056 [ 24768 ] {} <Fatal> BaseDaemon: 4. DB::AsynchronousReadBufferFromHDFS::seek(long, int) @ 0x1239f560 in /usr/bin/clickhouse
5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362073 [ 24768 ] {} <Fatal> BaseDaemon: 5. DB::LocalFileHolder::~LocalFileHolder() @ 0x1231e56b in /usr/bin/clickhouse
6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362099 [ 24768 ] {} <Fatal> BaseDaemon: 6. ? @ 0x1232660f in /usr/bin/clickhouse
7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362119 [ 24768 ] {} <Fatal> BaseDaemon: 7. ? @ 0x1237888b in /usr/bin/clickhouse
8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362135 [ 24768 ] {} <Fatal> BaseDaemon: 8. ? @ 0x1284e221 in /usr/bin/clickhouse
9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362151 [ 24768 ] {} <Fatal> BaseDaemon: 9. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362167 [ 24768 ] {} <Fatal> BaseDaemon: 10. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362189 [ 24768 ] {} <Fatal> BaseDaemon: 11. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362208 [ 24768 ] {} <Fatal> BaseDaemon: 12. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362227 [ 24768 ] {} <Fatal> BaseDaemon: 13. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362243 [ 24768 ] {} <Fatal> BaseDaemon: 14. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362261 [ 24768 ] {} <Fatal> BaseDaemon: 15. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362277 [ 24768 ] {} <Fatal> BaseDaemon: 16. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362292 [ 24768 ] {} <Fatal> BaseDaemon: 17. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362306 [ 24768 ] {} <Fatal> BaseDaemon: 18. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.362321 [ 24768 ] {} <Fatal> BaseDaemon:  (version 23.2.1.2537 (official build))
2023.04.19 12:07:36.372507 [ 25379 ] {} <Fatal> BaseDaemon: ########################################
2023.04.19 12:07:36.372634 [ 25379 ] {} <Fatal> BaseDaemon: (version 23.2.1.2537 (official build), build id: 50BDF08E4BF0B9023E0CA4AEFD09296FFEFF146B) (from thread 24900) (query_id: 2c01bea0-a872-4b1f-8341-af7c0148f099) (query: insert into xx select * from xx where project='' and day='20230301';) Received signal Aborted (6)
2023.04.19 12:07:36.372677 [ 25379 ] {} <Fatal> BaseDaemon:
2023.04.19 12:07:36.372720 [ 25379 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fa1a13d0387 0x7fa1a13d1a78 0xe301e5c 0x1a1df4c3 0x1a1df42e 0x893900b 0x1231e5e1 0x1232660f 0x1237888b 0x1284e221 0x1285097a 0x12855a1b 0x146ebd82 0x146fed39 0x175ff854 0x17600a7b 0x17787e07 0x1778583d 0x7fa1a176fea5 0x7fa1a1498b0d
2023.04.19 12:07:36.372820 [ 25379 ] {} <Fatal> BaseDaemon: 2. raise @ 0x36387 in /usr/lib64/libc-2.17.so
2023.04.19 12:07:36.372854 [ 25379 ] {} <Fatal> BaseDaemon: 3. abort @ 0x37a78 in /usr/lib64/libc-2.17.so
2023.04.19 12:07:36.372896 [ 25379 ] {} <Fatal> BaseDaemon: 4. ? @ 0xe301e5c in /usr/bin/clickhouse
2023.04.19 12:07:36.372941 [ 25379 ] {} <Fatal> BaseDaemon: 5. ? @ 0x1a1df4c3 in /usr/bin/clickhouse
2023.04.19 12:07:36.372986 [ 25379 ] {} <Fatal> BaseDaemon: 6. std::terminate() @ 0x1a1df42e in /usr/bin/clickhouse
2023.04.19 12:07:36.373017 [ 25379 ] {} <Fatal> BaseDaemon: 7. ? @ 0x893900b in /usr/bin/clickhouse
2023.04.19 12:07:36.373046 [ 25379 ] {} <Fatal> BaseDaemon: 8. ? @ 0x1231e5e1 in /usr/bin/clickhouse
2023.04.19 12:07:36.373066 [ 25379 ] {} <Fatal> BaseDaemon: 9. ? @ 0x1232660f in /usr/bin/clickhouse
2023.04.19 12:07:36.373096 [ 25379 ] {} <Fatal> BaseDaemon: 10. ? @ 0x1237888b in /usr/bin/clickhouse
2023.04.19 12:07:36.373134 [ 25379 ] {} <Fatal> BaseDaemon: 11. ? @ 0x1284e221 in /usr/bin/clickhouse
2023.04.19 12:07:36.373172 [ 25379 ] {} <Fatal> BaseDaemon: 12. DB::QueryPipeline::~QueryPipeline() @ 0x1285097a in /usr/bin/clickhouse
2023.04.19 12:07:36.373210 [ 25379 ] {} <Fatal> BaseDaemon: 13. DB::QueryPipeline::reset() @ 0x12855a1b in /usr/bin/clickhouse
2023.04.19 12:07:36.373232 [ 25379 ] {} <Fatal> BaseDaemon: 14. DB::TCPHandler::runImpl() @ 0x146ebd82 in /usr/bin/clickhouse
2023.04.19 12:07:36.373265 [ 25379 ] {} <Fatal> BaseDaemon: 15. DB::TCPHandler::run() @ 0x146fed39 in /usr/bin/clickhouse
2023.04.19 12:07:36.373297 [ 25379 ] {} <Fatal> BaseDaemon: 16. Poco::Net::TCPServerConnection::start() @ 0x175ff854 in /usr/bin/clickhouse
2023.04.19 12:07:36.373327 [ 25379 ] {} <Fatal> BaseDaemon: 17. Poco::Net::TCPServerDispatcher::run() @ 0x17600a7b in /usr/bin/clickhouse
2023.04.19 12:07:36.373358 [ 25379 ] {} <Fatal> BaseDaemon: 18. Poco::PooledThread::run() @ 0x17787e07 in /usr/bin/clickhouse
2023.04.19 12:07:36.373381 [ 25379 ] {} <Fatal> BaseDaemon: 19. Poco::ThreadImpl::runnableEntry(void*) @ 0x1778583d in /usr/bin/clickhouse
2023.04.19 12:07:36.373437 [ 25379 ] {} <Fatal> BaseDaemon: 20. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
2023.04.19 12:07:36.373472 [ 25379 ] {} <Fatal> BaseDaemon: 21. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
2023.04.19 12:07:36.998248 [ 25379 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: E9EEDE564FADE8C5C10B54D957E56740)
2023.04.19 12:07:58.281976 [ 24766 ] {} <Fatal> Application: Child process was terminated by signal 6.

**Comment by alexey-milovidov** [comment]
We won't fix HDFS.

**Comment by xieminrui** [comment]
Is this problem fixed in later versions? If I want to reproduce this problem, can I reproduce it by interrupting the network between clickhouse cluster and hdfs cluster while reading hdfs table?

**Comment by alexey-milovidov** [comment]
Not sure. But we didn't look at the HDFS code.
