### ISSUE TITLE
Throw exception when cannot parse dataTime64

### ISSUE THREAD

**Issue by lzydmxy** [ClickHouse/ClickHouse#48925]
**Describe the unexpected behaviour**
when use `toDateTime64` to parse string, some strings are parsed as default value.
```sql
SELECT toDateTime64('2023wwww', 3)

Query id: 0a9643d8-3052-4c10-8259-b1ae8e6263f6

┌─toDateTime64('2023wwww', 3)─┐
│     1970-01-01 08:00:00.000 │
└─────────────────────────────┘
```
We should throw `CANNOT_PARSE_DATETIME` Exception.

**Comment by alexey-milovidov** [comment]
This behavior is allowed by the specification in the docs.

**Comment by lzydmxy** [comment]
> This behavior is allowed by the specification in the docs.
But I don't think this behavior is expected by user.
```
```
