### ISSUE TITLE
Understanding space reclaim process in Lightweight Deletes

### ISSUE THREAD

**Issue by Vasu7052** [ClickHouse/ClickHouse#48928]
We were recently playing around with lightweight deletes on our production clickhouse cluster (v22.8). we deleted around 1.3B records from our table and we monitored our disk usage for around for a week and disk size was not at all reduced. 
we know that: "Users should be aware that by relying on normal background merge cycles, rows will only be eventually removed from the disk. While excluded from search results, the rows will reside on disk until their part is merged. The time taken for this to happen is not deterministic."

We just have two questions regarding this:
1. Is there a way to know whether these soft deleted rows are actually removed from the disk or not?
2. Can we force these merge cycles to occur so that the soft deleted rows are removed from the disk as well thus clearing up some disk space?

**Comment by CheSema** [comment]
Hi!

> Is there a way to know whether these soft deleted rows are actually removed from the disk or not?

Yes, look at [parts_columns](https://clickhouse.com/docs/en/operations/system-tables/parts_columns) table. Find you table there.
If a part has a column "_row_exists" that means your light weight deletion has not been actually applied for that part. Also compare value in column 'rows' with count(*) from this part,  that would show you how many rows actually stored in that part vs how many of them is alive. 

> Can we force these merge cycles to occur so that the soft deleted rows are removed from the disk as well thus clearing up some disk space?

Try this [OPTIMIZE](https://clickhouse.com/docs/en/sql-reference/statements/optimize). if you have a big table that could be resource consuming. You could try to run it for each partition separately.

**Comment by Vasu7052** [comment]
@CheSema thank you for such a quick response. I just have few more queries.

1. Let's say there is a part that has 100 rows out of which i performed lightweight deletions on 30 rows only (which were also deleted from disk later), so will this part still have _row_exists column?
2. If i executed a lightweight delete query that deletes from multiple parts, then is there a way to [OPTIMIZE](https://clickhouse.com/docs/en/sql-reference/statements/optimize) all those relevant parts in single query?
3. `Also compare value in column 'rows' with count(*) from this part, that would show you how many rows actually stored in that part vs how many of them is alive` can you also please share any relevant clickhouse document regarding alive rows.

**Comment by Vasu7052** [comment]
@CheSema thank you for such a quick response

**Comment by CheSema** [comment]
> @CheSema thank you for such a quick response. I just have few more queries.
> 
> 1. Let's say there is a part that has 100 rows out of which i performed lightweight deletions on 30 rows only (which were also deleted from disk later), so will this part still have _row_exists column?

Yes. A part has the column '_row_exists' as long as deletion is delayed. The deletion marker is stored in that column. Only after the marked rows are deleted physically the column `_row_exists` disappears. Information from that column is used for filtering out the data when you perform select.

> 2. If i executed a lightweight delete query that deletes from multiple parts, then is there a way to [OPTIMIZE](https://clickhouse.com/docs/en/sql-reference/statements/optimize) all those relevant parts in single query?

See the query `OPTIMIZE FINAL`.  [Doc](https://clickhouse.com/docs/en/sql-reference/statements/optimize). It could be resource consuming.

> 3. `Also compare value in column 'rows' with count(*) from this part, that would show you how many rows actually stored in that part vs how many of them is alive` can you also please share any relevant clickhouse document regarding alive rows.

I don't know appropriate page. So I just try to explain it a little bit. 
`select name, rows from system.parts_columns where table='test_table' and active and name='20220227_1120_86733_3'` -- it shows how many rows in the part on the disk.
`select count(*) from test_db.test_table where _part='20220227_1120_86733_3'` -- it shows the number of rows.  Lightweight deletes is applied for the results, so you do not see deleted rows in the result set.
