### ISSUE TITLE
How to know if a ReplicatedMergeTree is update-to-date

### ISSUE THREAD

**Issue by frinkr** [ClickHouse/ClickHouse#48930]
Hi,

We have a cluster with two replicas, and a load balancer which forwards any query to one of them. After INSERT/ALTER UPDATE a ReplicatedMergeTree table in replica A, the load balancer need to know if replica B has synced the data so it can forward SELECT queries to replica B.

The problem is how to know if a table of ReplicatedMergeTree  in replica B is update-to-date. Does ClickHouse have any special SQL to check the sync status? Or is there any recommandation of middleware to check it?

Thanks.

**Comment by den-crane** [comment]
```
select absolute_delay from system.replicas where tables = 'mytable';

select * from system.asynchronous_metrics where metric = 'ReplicasMaxAbsoluteDelay';

$ curl 'http://localhost:8123/replicas_status'

```

**Comment by frinkr** [comment]
Is the 'absolute_delay ' relative to INSERT only, or also ALTER UPDATE?

**Comment by den-crane** [comment]
both.
