### ISSUE TITLE
Why does the Lightweight delete operation wait for all replicas to complete?

### ISSUE THREAD

**Issue by zjial** [ClickHouse/ClickHouse#48964]
@davenger Hi, Why does the Lightweight delete operation wait for all replicas to complete? Refer to this line of code: [code](https://github.com/ClickHouse/ClickHouse/blob/019e677a152adfea1912fab79ec5dd45791a6304/src/Interpreters/InterpreterDeleteQuery.cpp#L102).

**Comment by davenger** [comment]
The idea was to make DELETE query synchronous, so that it resembles the behavior of DELETE in other databases.

**Comment by feixue1121** [comment]
@davenger according to this design, in case that one replica of a shard failed, then delete operations on all other nodes will wait until this replica recover from the failure?

**Comment by lqhl** [comment]
Then the statement in [this documentation](https://clickhouse.com/docs/en/guides/developer/mutations#lightweight-deletes) is wrong:

> Lightweight deletes are asynchronous by default. Set mutations_sync equal to 1 to wait for one replica to process the statement, and set mutations_sync to 2 to wait for all replicas.
