### ISSUE TITLE
Only if clickhouse-client configuration file contains a certificate: password authentication over TLS connection (native interface) broken since 23.3

### ISSUE THREAD

**Issue by snar** [ClickHouse/ClickHouse#48974]
**Describe the issue**

Before 23.3 client connecting over TLS was able to authenticate using password.
For now the only option is to use SSL certificate authentication.

**How to reproduce**
* Which ClickHouse server versions are incompatible

Behaviour changed in this commit: https://github.com/ClickHouse/ClickHouse/pull/47596
as you can see [here](https://github.com/ClickHouse/ClickHouse/commit/eddda2eb7381eeb45568cb8a7b1eacc01095d9a4#diff-653c0a18dfdaa86262c78dc6b25550add0487f165b4ad053e86f530388f6203aR1234) if user established TLS communication using certificate, this certificate is tried for authentication (and fails when user configured for password authentication), without fallback to password authentication.

* Which interface to use, if matters

Native interface over SSL.

* Non-default settings, if any

Standard SSL as described [here](https://clickhouse.com/docs/en/guides/sre/configuring-ssl),
user is configured to use password authentication.

**Error message and/or stacktrace**
Stack traces during failed authenication (it's a FreeBSD build, so frames are shown as addresses):

2023.04.19 14:28:50.763882 [ 164298 ] {} <Trace> TCPSHandlerFactory: TCP Request. Address: [::1]:17945
2023.04.19 14:28:50.767775 [ 164298 ] {} <Debug> TCPHandler: Connected ClickHouse client version 22.1.0, revision: 54455, database: default, user: default.
2023.04.19 14:28:50.767832 [ 164298 ] {} <Debug> TCP-Session: 805cd27a-19c4-41a8-8aeb-a537373838ac Authenticating user 'default' from [::1]:17945
2023.04.19 14:28:50.767989 [ 164298 ] {} <Error> Access(user directories): from: ::1, user: default: Authentication failed: Code: 36. DB::Exception: Credentials required. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):

0. 0x13f46256
1. 0xd6786bb
2. 0x1191b9b2
3. 0x1191afc7
4. 0x11916c67
5. 0x11916b85
6. 0x1193656e
7. 0x11916b31
8. 0x11875745
9. 0x128f573b
10. 0x135a36f7
11. 0x1359e191
12. 0x135ae8bc
13. 0x13f3488c
14. 0x13f34d7a
15. 0x13f9dd27
16. 0x13f9b80f
17. 0x8363f6a78
 (version 23.4.1.1)
2023.04.19 14:28:50.768451 [ 164298 ] {} <Debug> TCP-Session: 805cd27a-19c4-41a8-8aeb-a537373838ac Authentication failed with error: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

2023.04.19 14:28:50.768574 [ 164298 ] {} <Error> ServerErrorHandler: Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED), Stack trace (when copying this message, always include the lines below):

0. 0x13f46256
1. 0xd6786bb
2. 0x8b9df32
3. 0x11875a1a
4. 0x128f573b
5. 0x135a36f7
6. 0x1359e191
7. 0x135ae8bc
8. 0x13f3488c
9. 0x13f34d7a
10. 0x13f9dd27
11. 0x13f9b80f
12. 0x8363f6a78
 (version 23.4.1.1)

**Additional context**
Workaround: reconfigure user from password to certificate authentification
as described [here](https://clickhouse.com/docs/en/guides/sre/ssl-user-auth).
On the other hand, certificate + password is simple enough 2FA: certificate is something you have and password is something you know, so it would be good to restore this functionality.

**Comment by alexey-milovidov** [comment]
Does not reproduce with the default settings:
```
milovidov@milovidov-desktop:~$ clickhouse-client --host play.clickhouse.com --secure --user play
ClickHouse client version 23.4.1.1.
Connecting to play.clickhouse.com:9440 as user play.
Connected to ClickHouse server version 23.4.1 revision 54462.

play-eu :)
```

Most likely, the issue happens when you also have a certificate configured for clickhouse-client.
Nevertheless, we will fix it.

**Comment by alexey-milovidov** [comment]
I've changed the issue title to reflect this.
