### ISSUE TITLE
test_storage_hdfs Can't wait HDFS to start

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#48975]
https://s3.amazonaws.com/clickhouse-test-reports/48664/61635eb2d345881a7fd84a2c2708d9d2d02c3e04/integration_tests__release__%5B3/4%5D.html

Happens not too often: [ci db](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNvdW50KCkgYXMgYywgbWF4KHB1bGxfcmVxdWVzdF9udW1iZXIpLCBjaGVja19zdGFydF90aW1lLCBhbnkoY2hlY2tfbmFtZSksIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgLS1BTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyA9ICdFUlJPUicKCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3N0b3JhZ2VfaGRmcyUnCkdST1VQIEJZIHJlcG9ydF91cmwsIGNoZWNrX3N0YXJ0X3RpbWUKSEFWSU5HIGMgPiAyMApPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2M=)

**Comment by KochetovNicolai** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/108afc4d907606702429541416b668aacc43e974/integration_tests__release__[3/4].html
