### ISSUE TITLE
Add support of `FROM INFILE` in `CREATE AS SELECT` statement

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#48972]
**Use case**

I want to create table and load data from file that is stored near `clickhouse-client`.
Schema can be derived automatically for `file()` table function.
But when you use `file()` in `clickhouse-client` it tries to read file on the server.
There is `INSERT ... FROM INFILE ` statement, but `INSERT` can't be used in `CREATE AS SELECT`.

**Describe the solution you'd like**

Add support of `INFILE` in select statement.

`CREATE TABLE t ENGINE=MergeTree ORDER BY (c0) AS SELECT * FROM INFILE 'input.csv'`

**Comment by alexey-milovidov** [comment]
In this specific wording, the feature would be very unnatural.
What you need is https://clickhouse.com/docs/en/sql-reference/table-functions/input

**Comment by qoega** [comment]
>What you need is https://clickhouse.com/docs/en/sql-reference/table-functions/input

I specifically try to rewrite input to this query. To use it without explicit format and schema. And with a way to use better parallel read.

**Comment by alexey-milovidov** [comment]
Then you need another feature - type and format inference for the `input` table function.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/36355

**Comment by qoega** [comment]
Faced with it again: 

```
Code: 636. DB::Exception: Received from localhost:9000. DB::Exception: Table function 'input' was used without structure argument but structure could not be determined automatically. Please, provide structure manually. (CANNOT_EXTRACT_TABLE_STRUCTURE)
(query: CREATE TABLE tmp ENGINE = MergeTree AS SELECT * FROM input() FORMAT CSVWithNames)
```
