### ISSUE TITLE
Is there any way to modify database's comments?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#48971]
We can specify comments for databases when we were creating them, with query `CREATE DATABASE ... COMMENT`. However I failed to find a way to modify comments, the statement `ALTER DATABASE MODIFY COMMENT` does not work at all.

Is there any way to modify database's comments?

**Comment by davenger** [comment]
No, currently it is not implemented.

**Comment by Alex-Cheng** [comment]
I think it should be a feature to modify database comment, as we can specify the comment when creating a database.

**Comment by cliffburdick** [comment]
@Alex-Cheng @davenger was this ever added?
