### ISSUE TITLE
RFC: allow fault injection at any point of code.

### ISSUE THREAD

**Issue by hanfei1991** [ClickHouse/ClickHouse#48982]
Right now we have had fault injection in ZooKeeper and MemTracker, but we cannot precisely control when and where to fail in tests. It's based on random distribution right now.

For example, I want to write an integration test like this:

1. node 1 insert to a replicated table, get block 1 
2. node 2 insert to a replicated table, get block id 2, but network partitioned before final commit, 
3. node 1 insert to a replicated table, get block 3
4. when step 2 timeout for a while, the lock of block 2 is cleaned. at this timepoint, we merge block 1 and block 3 and get block 1_3
5. node 2 retries because of hardware_error, if it still use block id 2, the test will fail, because block_2 conflicts with block 1_3

In some cases, we want to inject a fault in a particular line and enable/disable it whenever we want. Here is the implementation in TiFlash https://github.com/pingcap/tiflash/blob/master/dbms/src/Common/FailPoint.h and how they use it https://github.com/pingcap/tiflash/blob/master/tests/fullstack-test/fault-inject/alter-table.test

In ClickHouse, we can support `system enable failpoint *****` to enable a failpoint. Anyone has better suggestions?

**Comment by tavplubix** [comment]
JFYI see also `ThreadFuzzer::maybeInjectSleep()`, `ThreadFuzzer::maybeInjectMemoryLimitException()` and `system start/stop thread fuzzer`. 

I like the idea of adding named failure points. It also makes sense to make the failure probability configurable for each named failure point.
