### ISSUE TITLE
When key is Nullable(String), the aggregate operator converts the empty string to null

### ISSUE THREAD

**Issue by liuneng1994** [ClickHouse/ClickHouse#48997]
> You have to provide the following information whenever possible.

**Describe what's wrong**

![image](https://user-images.githubusercontent.com/16730247/233553522-a94eecdc-9af9-4ada-afe0-a7333503c217.png)

**Does it reproduce on recent release?**

23.3

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

https://fiddle.clickhouse.com/a4be8131-1332-4f87-b342-853f349f43b2

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by liuneng1994** [comment]
I'm working on this bug

**Comment by den-crane** [comment]
introduced in 23.3
