### ISSUE TITLE
How can I use other S3 params when using s3-backed-mergetree?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#49002]
When I use [s3-backed-mergetree](https://clickhouse.com/docs/en/integrations/s3#s3-backed-mergetree),I can use these S3 params:

```xml
<access_key_id>ABCDEFGHIJKLMNOPQRST</access_key_id>
<secret_access_key>Tjdm4kf5snfkj303nfljnev79wkjn2l3knr81007</secret_access_key>
<proxy>proxy</proxy>
```

> refer to https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#configuring-the-s3-disk

But how can I use other S3 params when using s3-backed-mergetree? Such as:

```text
signature_v2
check_ssl_certificate
check_ssl_hostname
ssl_client_cert_file
ssl_client_key_file
```

> refer to https://s3tools.org/usage

Thanks!

**Comment by alexey-milovidov** [comment]
No, these parameters are not supported.

**Comment by LGDHuaOPER** [comment]
Can ClickHouse use aws-cpp-sdk config and credentials by reading these files https://docs.aws.amazon.com/sdkref/latest/guide/file-location.html ?
