### ISSUE TITLE
ORC format support

### ISSUE THREAD

**Issue by kindred77** [ClickHouse/ClickHouse#4903]
We use ORC format in our hdfs cluster and want to query these data using hdfs table engine in CH.
I find apache arrow which has supported ORC format have been added to submodule in CH.
Do you have a plan to support ORC format?

**Comment by blinkov** [comment]
This obviously needs to be done at some point, but no ETA yet.

**Comment by kindred77** [comment]
thanks

**Comment by akonyaev90** [comment]
I would like to help with this task. Can you give any recommendations for implementation?

Which format implementation can I take as a model for study and a pattern? May be Parquet?

Arrow::parquet used for parquet-format. Does it good idea  use arrow::ORC for orc-format?

**Comment by kindred77** [comment]
I think arrow:ORC is ok.

https://github.com/apache/arrow/blob/master/cpp/src/arrow/adapters/orc/adapter-test.cc

**Comment by blinkov** [comment]
Support for output is still missing

**Comment by alexey-milovidov** [comment]
Current status: ORC output format is still to do.

**Comment by alexey-milovidov** [comment]
Current status: ORC output format is available since version 20.6.
