### ISSUE TITLE
Memory usage with multiple JOINs

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#4904]
> select version();
SELECT version()
┌─version()─┐
│ 19.4.1.1  │
└───────────┘
>DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Memory limit (for query) exceeded: would use 30.00 GiB (attempt to allocate chunk of 262144 bytes), maximum: 30.00 GiB: (while reading column ID): (while reading from part /var/lib/clickhouse/data/ods/SaleOrders/all_45_50_1/ from mark 20 with max_rows_to_read = 24576). 
>0 rows in set. Elapsed: 7.413 sec. Processed 18.68 million rows, 15.03 GB (2.52 million rows/s., 2.03 GB/s.)
>select so.OrderCreateTime, \
  c.CityName, \
  buser.BizUserName, \
  sku.FirstDisPlayCategory, \
  sku.Brand, \
  soi.ProductName, \
  sku.UnitPriceClass, \
  so.OrderType, \
  soi.ReduceCouponAmount \
from SaleOrders so \
inner join SaleOrderItem soi ON so.ID = soi.OrderID \
inner join City c ON so.CityID=c.ID \
inner join bizuser buser ON so.BizUserID=buser.ID \
inner join ProductSKUSpe sku ON sku.ProductSKUID=soi.ProductSKUID \
where so.OrderCreateTime >= '2019-01-01 00:00:00' \
AND so.OrderCreateTime <= '2019-01-31 00:00:00' AND so.OrderCompleteTime >= '2019-01-01 00:00:00' \
AND so.OrderCompleteTime <= '2019-01-31 00:00:00' AND so.CityID IN(100,402,404) AND so.StatusID IN (7,10)\
ORDER BY  so.OrderCreateTime,c.CityName \
LIMIT 30, 30;

--Questions:
no matter how much memory increased,it appreas like aboe.how avoid it or set right memory. The dataset i store in clickhouse 36G, Original data size is about 225G.

**Comment by blinkov** [comment]
@vkingnew how exactly have you've tried to increase the memory limit?

**Comment by vkingnew** [comment]
The default memory about 10G，I tried 20G ,30G,40G appears the same error.The Mache total Memory is 48G.And I how to avoid this error message?I need to change some settings?

**Comment by 4ertus2** [comment]
There's related issue #4731
The reason why you get it is disabled enable_optimize_predicate_expression. That is still experimental feature. You may try to enable it or use workaround and rewrite you query with subselects duplicating where sections into them manually:

```
from (selct * from SaleOrders where AND OrderCreateTime <= '2019-01-31 00:00:00' AND OrderCompleteTime >= '2019-01-01 00:00:00' 
AND OrderCompleteTime <= '2019-01-31 00:00:00' AND CityID IN(100,402,404) AND StatusID IN (7,10)) so 
inner join SaleOrderItem soi ON so.ID = soi.OrderID 
inner join (select * from City where ID IN(100,402,404)) c ON so.CityID = c.ID 
inner join bizuser buser ON so.BizUserID = buser.ID 
inner join ProductSKUSpe sku ON sku.ProductSKUID = soi.ProductSKUID 
```

We know that it's not clear for users that multiple join are not OK with disabled push down and going to solve it a bit later.
