### ISSUE TITLE
Run Clickhouse on TEE(Intel SGX)

### ISSUE THREAD

**Issue by MLikeWater** [ClickHouse/ClickHouse#49040]
> Consider running Clickhouse in TEE ([Intel SGX](https://github.com/intel/linux-sgx)) based on Occlum to achieve joint data analysis capability, but currently [Occlum ](https://occlum.readthedocs.io/en/latest/binaries_compatibility.html)requires running programs to compile using PIE (Position-Independent-Executable) and PIC. How to configure CMakeCache.txt?
**Operating system**

> Ubuntu 20.04 LTS

**Cmake version**
cmake version 3.20.0+

**Comment by MLikeWater** [comment]
You can refer to the MySQL on Occlum compile the example:
https://github.com/occlum/occlum/blob/master/demos/mysql/dl_and_build_mysql.sh

**Comment by rschu1ze** [comment]
Please don't modify CMakeCache.txt directly. Maybe you could try
- to build with `-DCMAKE_POSITION_INDEPENDENT_CODE=1` (off by default, https://github.com/ClickHouse/ClickHouse/blob/fc101a33cdba22b9db22c00bf92fee5e998f5cdc/CMakeLists.txt#L424)
- and also comment out the block here https://github.com/ClickHouse/ClickHouse/blob/fc101a33cdba22b9db22c00bf92fee5e998f5cdc/CMakeLists.txt#L425?

**Comment by MLikeWater** [comment]
@rschu1ze Thank you for your support.

Following the above tips, I still had a bit of a problem compiling the project. The specific operation process is as follows:
### 1. Compile successfully with cmake:
```
mkdir build && cd build
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 ..
```

### 2. Execute the ninja command:
```
ninja -j$(nproc)
```
An error has occurred:
```
# ninja -j$(nproc)
[0/2] Re-checking globbed directories...
[2/7716] Linking CXX executable contrib/protobuf-cmake/protoc
FAILED: contrib/protobuf-cmake/protoc 
: && /usr/bin/clang++-15 --target=x86_64-linux-gnu --sysroot=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/data/clickhouse/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -flto=thin -fwhole-program-vtables --gcc-toolchain=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/data/clickhouse/ClickHouse/build/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1  -flto=thin -fwhole-program-vtables   -Xlinker --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o -o contrib/protobuf-cmake/protoc  contrib/protobuf-cmake/lib_libprotoc.a  contrib/protobuf-cmake/lib_libprotobuf.a  -lpthread  contrib/zlib-ng-cmake/lib_zlib.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  -Wl,--start-group  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
ld.lld-15: error: cannot open Scrt1.o: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[5/7716] Building C object contrib/openldap-cmake/CMakeFiles/_ldap_r.dir/__/openldap/libraries/libldap/filter.c.o
ninja: build stopped: subcommand failed.
```
Check the environment, there are files:
```
# find / -name Scrt1.o
/data/clickhouse/ClickHouse/contrib/sysroot/linux-aarch64/aarch64-linux-gnu/libc/usr/lib64/Scrt1.o
/data/clickhouse/ClickHouse/contrib/sysroot/linux-riscv64/lib/riscv64-linux-gnu/Scrt1.o
/data/clickhouse/ClickHouse/contrib/sysroot/linux-s390x/s390x-linux-gnu/libc/usr/lib64/Scrt1.o
/data/clickhouse/ClickHouse/contrib/sysroot/linux-s390x/s390x-linux-gnu/libc/lib64/Scrt1.o
/usr/lib32/Scrt1.o
/usr/libx32/Scrt1.o
/usr/lib/x86_64-linux-gnu/Scrt1.o
```
Setting cmake -DCMAKE_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu" or LIBRARY_PATH etc will not work.

Note:
I also encountered an error earlier:
```
/data/clickhouse/ClickHouse/contrib/aws-crt-cpp/include/aws/crt/Types.h:11:10: fatal error:  'aws/io/socket.h' file not found
#include <aws/io/socket.h>
```
Solve the problem in the following ways:
```
git clone https://github.com/awslabs/aws-crt-cpp.git
cd aws-crt-cpp
git submodule update --init
mkdir build && cd build
cmake ..
make && sudo make install
```

**Comment by alexey-milovidov** [comment]
> ld.lld-15: error: cannot open Scrt1.o: No such file or directory

We have fixed this error. Now you can build the PIE.

**Comment by MLikeWater** [comment]
When compiling with cmake:
```
git clone https://github.com/ClickHouse/ClickHouse.git
git checkout master
cd ClickHouse
git submodule update --init
mkdir build && cd build
cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 ..
```

So it's still '-no-pie-wl,-no-pie':
```
-- LINKER_FLAGS =  --gcc-toolchain=/root/clickhouse_occlum/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/root/clickhouse_occlum/build/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1 -no-pie -Wl,-no-pie
```

And execute the command:
```
ninja -j$(nproc)
```

```
In file included from /root/clickhouse_occlum/contrib/aws-crt-cpp/include/aws/crt/DateTime.h:8:
/root/clickhouse_occlum/contrib/aws-crt-cpp/include/aws/crt/Types.h:11:10: fatal error: 'aws/io/socket.h' file not found
#include <aws/io/socket.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
[195/7049] Building CXX object contrib/aws-cmake/CMakeFiles/_aws.dir/__/aws/aws-cpp-sdk-s3/source/model/GetBucketMetricsConfigurationRequest.cpp.o
FAILED: contrib/aws-cmake/CMakeFiles/_aws.dir/__/aws/aws-cpp-sdk-s3/source/model/GetBucketMetricsConfigurationRequest.cpp.o
/usr/bin/ccache /usr/bin/clang++-15 --target=x86_64-linux-gnu --sysroot=/root/clickhouse_occlum/cmake/linux/../../contrib/sysroo
```

**Comment by Root-Three-ai** [comment]
> > 
> 
> Yes, the command has been executed. Repeated execution does not return any result. All Submodules have been pulled.
> 
> ```
> # git submodule update --recursive --init
> # ninja -j$(nproc)
> [0/2] Re-checking globbed directories...
> [2/8810] Linking CXX executable contrib/protobuf-cmake/protoc
> FAILED: contrib/protobuf-cmake/protoc 
> : && /usr/bin/clang++-15 --target=x86_64-linux-gnu --sysroot=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/data/clickhouse/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4 --gcc-toolchain=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/data/clickhouse/ClickHouse/build/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1    -Xlinker --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o -o contrib/protobuf-cmake/protoc  contrib/protobuf-cmake/lib_libprotoc.a  contrib/protobuf-cmake/lib_libprotobuf.a  -lpthread  contrib/zlib-ng-cmake/lib_zlib.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  -Wl,--start-group  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
> ld.lld-15: error: cannot open Scrt1.o: No such file or directory
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> [5/8810] Building C object contrib/openldap-cmake/CMakeFiles/_ldap_r.dir/__/openldap/libraries/libldap/abandon.c.o
> ninja: build stopped: subcommand failed.
> ```
I am currently also trying to run ClickHouse on Occlum. Have you solved this issue?

**Comment by Root-Three-ai** [comment]
> > 
> 
> Yes, the command has been executed. Repeated execution does not return any result. All Submodules have been pulled.
> 
> ```
> # git submodule update --recursive --init
> # ninja -j$(nproc)
> [0/2] Re-checking globbed directories...
> [2/8810] Linking CXX executable contrib/protobuf-cmake/protoc
> FAILED: contrib/protobuf-cmake/protoc 
> : && /usr/bin/clang++-15 --target=x86_64-linux-gnu --sysroot=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/data/clickhouse/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -O2 -g -DNDEBUG -O3 -g -gdwarf-4 --gcc-toolchain=/data/clickhouse/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/data/clickhouse/ClickHouse/build/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1    -Xlinker --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o -o contrib/protobuf-cmake/protoc  contrib/protobuf-cmake/lib_libprotoc.a  contrib/protobuf-cmake/lib_libprotobuf.a  -lpthread  contrib/zlib-ng-cmake/lib_zlib.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  -Wl,--start-group  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.builtins-x86_64.a  -lc -lm -lrt -lpthread -ldl && :
> ld.lld-15: error: cannot open Scrt1.o: No such file or directory
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> [5/8810] Building C object contrib/openldap-cmake/CMakeFiles/_ldap_r.dir/__/openldap/libraries/libldap/abandon.c.o
> ninja: build stopped: subcommand failed.
> ```

I am currently also trying to run ClickHouse on Occlum. Have you resolved this issue? Is ClickHouse running correctly on Occlum now? I look forward to communicating with you!

**Comment by rschu1ze** [comment]
@Root-Three-ai Did you run into the issue during your experiments? Afaik, nobody managed to run ClickHouse on Occulum yet. Any experiments or help are appreciated.

**Comment by Root-Three-ai** [comment]
> [@Root-Three-ai](https://github.com/Root-Three-ai) Did you run into the issue during your experiments? Afaik, nobody managed to run ClickHouse on Occulum yet. Any experiments or help are appreciated.

Can ClickHouse be compiled into PIE and PIC formats? Is there a PIE format RPM package available for ClickHouse?

**Comment by rschu1ze** [comment]
> Can ClickHouse be compiled into PIE and PIC formats?

Yes:
https://github.com/ClickHouse/ClickHouse/blob/17e8e8058b2b1af8e4ad1e7eada62f2085df0662/CMakeLists.txt#L430-L452

> Is there a PIE format RPM package available for ClickHouse?

The RPM packages ([here](https://github.com/ClickHouse/ClickHouse/releases)) are built with ThinLTO. As a result, they are not position-independent (see above link).

**Comment by Root-Three-ai** [comment]
> > Can ClickHouse be compiled into PIE and PIC formats?
> 
> Yes:
> 
> [ClickHouse/CMakeLists.txt](https://github.com/ClickHouse/ClickHouse/blob/17e8e8058b2b1af8e4ad1e7eada62f2085df0662/CMakeLists.txt#L430-L452)
> 
> Lines 430 to 452 in [17e8e80](/ClickHouse/ClickHouse/commit/17e8e8058b2b1af8e4ad1e7eada62f2085df0662)
> 
>  # We enable position independent encoding for all build types except build with -flto=thin: 
>  # 1. Position independent binaries and libraries have no limit for maximum size of relocation. It allows to avoid 
>  # multiple sophisticated problems like linking with sanitizers or linking of rust. 
>  # 2. Position independent binaries and libraries are a little bit slower, than position dependent. We consider 
>  # build with -flto=thin as trully "production" build where each % of performance is important. 
>  # 3. For some unknow reason -flto=thin lead to some other way of linkage. For example for rust libraries build 
>  # we don't see any relocation-related errors without -fPIC, but with enabled -flto=thin. While without 
>  # -flto=thin we have relocation errors like: 
>  # rust-lld: error: relocation R_X86_64_32S cannot be used against symbol 'SEED_encrypt'; recompile with -fPIC 
>  # 
>  # NOTE: -fno-pie disables -fPIC, so that is why we check ENABLE_THINLTO in the branch bellow 
>  # 
>  # For some sophisticated platforms we have different issues with fPIC: 
>  # For example riscv toolchain itself compiled without fPIC 
>  if (NOT ENABLE_THINLTO AND (ARCH_AMD64 OR ARCH_AARCH64)) 
>      set(ENABLE_POSITION_INDEPENDENT_BINARY 1) 
>  endif() 
>   
>  if (ENABLE_POSITION_INDEPENDENT_BINARY) 
>      set (CMAKE_POSITION_INDEPENDENT_CODE OFF) 
>      set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC") 
>      set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC") 
>  endif() 
> > Is there a PIE format RPM package available for ClickHouse?
> 
> The RPM packages ([here](https://github.com/ClickHouse/ClickHouse/releases)) are built with ThinLTO. As a result, they are not position-independent (see above link).

This means we need to compile ClickHouse with PIE ourselves. Do you have any reference materials for self-compilation? Thank you very much！

**Comment by Root-Three-ai** [comment]
> > Can ClickHouse be compiled into PIE and PIC formats?
> 
> Yes:
> 
> [ClickHouse/CMakeLists.txt](https://github.com/ClickHouse/ClickHouse/blob/17e8e8058b2b1af8e4ad1e7eada62f2085df0662/CMakeLists.txt#L430-L452)
> 
> Lines 430 to 452 in [17e8e80](/ClickHouse/ClickHouse/commit/17e8e8058b2b1af8e4ad1e7eada62f2085df0662)

> > Is there a PIE format RPM package available for ClickHouse?
> 
> The RPM packages ([here](https://github.com/ClickHouse/ClickHouse/releases)) are built with ThinLTO. As a result, they are not position-independent (see above link).

This means we need to compile a PIE version of ClickHouse ourselves. Do you have any reference materials for self-compilation? Thank you very much.

**Comment by Root-Three-ai** [comment]
> > Do you have any reference materials for self-compilation?
> 
> https://clickhouse.com/docs/development/developer-instruction https://clickhouse.com/docs/development/build

From the information you've provided, the versions required for Clang, Ubuntu, and others are too high for us to obtain. We intend to use CentOS 7 or CentOS 8 to compile and install a lower version of ClickHouse, such as v23.9.6.20-stable. How should we achieve this, and what help can you provide? Thank you very much.

**Comment by rschu1ze** [comment]
I suppose compiling with CentOS (7 or 8) is feasible though you'd be on your own in case of problems. Also 2023 versions of ClickHouse are no longer supported (see [here](https://clickhouse.com/docs/faq/operations/production#how-to-choose-between-clickhouse-releases)) so again, you would be on your own in case of problems. But perhaps building an old code state with a Linux distro from around that time will work.

**Comment by Root-Three-ai** [comment]
> I suppose compiling with CentOS (7 or 8) is feasible though you'd be on your own in case of problems. Also 2023 versions of ClickHouse are no longer supported (see [here](https://clickhouse.com/docs/faq/operations/production#how-to-choose-between-clickhouse-releases)) so again, you would be on your own in case of problems. But perhaps building an old code state with a Linux distro from around that time will work.

`cmake version 3.22.0`
`clang version 17.0.6`

I execute the following command to compile.

`git clone --recurse-submodules https://github.com/ClickHouse/ClickHouse.git`
`cd Clickhouse`
`git checkout v24.8.6.70-lts`
`mkdir build & cd build`
`cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 ..`

But an error has occurred.

`CMake Error at contrib/llvm-project/llvm/CMakeLists.txt:77 (message):
  Requested CMAKE_CXX_STANDARD=14 which is less than the required 17.`

The cause of this exception and how can I resolve it?

<img width="655" alt="Image" src="https://github.com/user-attachments/assets/31831864-42ae-43bb-901e-17c994b44a4c" />

**Comment by Root-Three-ai** [comment]
> After `git checkout v24.8.6.70-lts`, please run `git submodule update --recursive --init`. Then try again.

After following your instructions, I successfully completed the compilation.
`git checkout v24.8.6.70-lts`
`git submodule update --recursive --init`
`mkdir build & cd build`
`cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 ..`

When executing `make` but encountered this error 

`[  2%] Building ASM object contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aes-x86_64.s.o
clang: error: no such file or directory: '/opt/meituan/projects/clickhouse/ClickHouse/build/contrib/openssl/crypto/aes/aes-x86_64.s'
clang: error: no input files
make[2]: *** [contrib/openssl-cmake/CMakeFiles/crypto.dir/build.make:13399: contrib/openssl-cmake/CMakeFiles/crypto.dir/__/openssl/crypto/aes/aes-x86_64.s.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6033: contrib/openssl-cmake/CMakeFiles/crypto.dir/all] Error 2
make: *** [Makefile:166: all] Error 2`

<img width="1206" alt="Image" src="https://github.com/user-attachments/assets/67bb7d4c-060f-47f4-bacc-d53198aded6a" />

**Comment by Root-Three-ai** [comment]
> After `git checkout v24.8.6.70-lts`, please run `git submodule update --recursive --init`. Then try again.

According to what you said, I could compile successfully with cmake. 
`cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 ..`

However, when I executed `make`, I encountered the following error. 
`make[2]: *** No rule to make target 'src/Functions/CMakeFiles/clickhouse_functions_obj.dir/CRC.cpp.o', needed by 'src/unit_tests_dbms'.  Stop.`
`make[1]: *** [CMakeFiles/Makefile2:22062: src/CMakeFiles/unit_tests_dbms.dir/all] Error 2`
`make: *** [Makefile:166: all] Error 2`

<img width="984" alt="Image" src="https://github.com/user-attachments/assets/25a4b40d-eddf-4781-b947-87babdb7f0d3" />

The cause of this exception and how can I resolve it? Thanks a lot!

**Comment by rschu1ze** [comment]
Run CMake with `-DENABLE_TESTS=1`.

**Comment by Root-Three-ai** [comment]
> Run CMake with `-DENABLE_TESTS=0`.

When I ran CMake with `-DENABLE_TESTS=0`, this issue disappeared. However, a new error has arisen.

`make[2]: *** No rule to make target 'src/Functions/CMakeFiles/clickhouse_functions_obj.dir/FunctionFactory.cpp.o', needed by 'programs/clickhouse-library-bridge'.  Stop.`
`make[1]: *** [CMakeFiles/Makefile2:33327: programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/all] Error 2`

<img width="1179" alt="Image" src="https://github.com/user-attachments/assets/79c0efcf-a87d-40bd-8f0b-32ded837a0fc" />
The cause of this exception and how can I resolve it? Thanks a lot!

**Comment by Root-Three-ai** [comment]
> Run CMake with `-DENABLE_TESTS=0`.

I was able to successfully compile after retrying, but the resulting executable is not in PIE format; it remains as EXEC. As shown in the image below.
`cmake -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DENABLE_TESTS=0 ..`

<img width="792" alt="Image" src="https://github.com/user-attachments/assets/8701521a-b5ab-4baa-a681-62143e60d869" />
Why is this happening?

**Comment by Root-Three-ai** [comment]
> Run CMake with `-DENABLE_TESTS=0`.

I compiled ClickHouse and ran it on the LibOS named Occlum. However, this LibOS does not support the fcntl syscall with the parameter cmd = 1032 (F_GETPIPE_SZ). 

`Syscall { num = Fcntl, fd = 8, cmd = 1032, arg = 0 }`

Could you advise on which non-essential module can be disabled during the compilation of ClickHouse to avoid this unsupported command?
