### ISSUE TITLE
Is there any tools (GUI is preferred) for adding, deleting, syncing a replica in a cluster?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#49062]
We have a cluster with several replicas, but I feel difficult to managing it. E.g. it is hard to add new replica, because it involves copying data from cluster to the new replica and modifying config.xml to include the new node and maybe some adopting work for the new replica. It is time-consuming and easy to do mistake.

Shall I have a GUI tools for easily managing my ClickHouse cluster? 

Can you recommend any vendor for such a service or product?

**Comment by cangyin** [comment]
[ckman](https://github.com/housepower/ckman) can be one of the tools, which provides data rebalancing feature, and some other cluster managing functions.

**Comment by Alex-Cheng** [comment]
> [ckman](https://github.com/housepower/ckman) can be one of the tools, which provides data rebalancing feature, and some other cluster managing functions.

ckman seems to be maintained by only one person, and update slowly. Is it good enough?

**Comment by cangyin** [comment]
we tried it, but not using it.
