### ISSUE TITLE
Is there any comprehensive and easy-to-understand explaination for these metrics? 

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#49067]
As shown in below screenshot, these CPU-related metrics are very interesting but I feel difficult to get a comprehensive explainations for these metrics(although actually I know some of them). The ClickHouse document does not touch them either. 

![image](https://user-images.githubusercontent.com/1518453/233832933-3ed23796-1793-4c6f-9e8a-3244fb103831.png)

I suggest a document page for these metrics for ClickHouse because it may be important for users.

**Comment by alexey-milovidov** [comment]
https://pastila.nl/?00014be2/6cb3dc5f2fc8f3c8ae55bd8a2ea39c2d.md

https://github.com/ClickHouse/ClickHouse/pull/43194
