### ISSUE TITLE
Need a smart proxy to routine queries to up-to-date replica nodes in a cluster

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#49060]
**Use case**
For scaling capability and fault tolerance of ClickHouse, we build up a multi-replica cluster with a load balancer. We have a series of write queries such as creating tables/databases, updating tables, adding columns and etc. Then we will do some read queries on the results of previous write queries. The problem is that our cluster is a "eventually-consistency" cluster, which means not all replicas are up-to-date at some point of time. We need a "smart" proxy to routine a query to the replica which has the up-to-date databases/tables.

**Describe the solution you'd like**
A "smart" proxy or similar features to routine a query to the replica which has the up-to-date databases/tables for avoiding executing a query in a cluster replica whose database is not synced completely.

```
        +-------+
        | proxy |
        +-------+
            |
  +------------------+
  |         |        |
+-----+  +-----+  +-----+
|  A  |  |  B  |  |  C  | 
+-----+  +-----+  +-----+
```
The proxy should check the proper replica among cluster replicas A, B, C, which have the up-to-date databaes or tables required by the current query.

**Describe alternatives you've considered**
Otherwise, we have to develop such a "smart proxy" ourselves.

**Comment by alexey-milovidov** [comment]
You can use Distributed table as this smart proxy. It will skip the replicas that don't have tables and, with the help of the `max_replica_delay` setting, skip stale replicas.

**Comment by Alex-Cheng** [comment]
Thank you very much. Does Distributed table engine exam the table's status and skip those replica which is not up-to-date? To achieve this, Distributed table needs to check the ZooKeeper nodes 'log_pointer' and 'log' for the ReplicatedMergeTree table.
