### ISSUE TITLE
Manually execute the Optimize operation : Cannot select parts for optimization

### ISSUE THREAD

**Issue by lxswbr** [ClickHouse/ClickHouse#49074]
A new cluster was built. After the data was inserted, the following exception occurred after manually executing the Optimize final. DB::Exception: There was an error on [xx.xxx.xxx.xxx:9000]: Code: 388. DB::Exception: Cannot select parts for optimization: Part 9_2331_2337_2 has already been assigned a merge into 9_2331_2344_3 (in partition 9). (CANNOT_ASSIGN_OPTIMIZE) (version 22.3.2.1)
This exception message is still reported after multiple retries.
But my other cluster of the same version has never had this exception. How did this exception cause it? How to solve it

**Comment by cangyin** [comment]
maybe [detach the partition](https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#detach-partitionpart) and attach it back helps.

**Comment by alexey-milovidov** [comment]
Parts are already selected for optimization.

**Comment by shotgun-20** [comment]
> Parts are already selected for optimization.

Does this exception interrupts OPTIMIZE ... FINAL query? Or OPTIMIZE will go on till there's something left to merge?

**Comment by alexey-milovidov** [comment]
@shotgun-20, if there are already merging parts, OPTIMIZE FINAL will be a no-op.
