### ISSUE TITLE
does CH minmax skipping indexes work with string values (base 36)?

### ISSUE THREAD

**Issue by jasonbigl** [ClickHouse/ClickHouse#49084]
Hi,

I'm trying to use the minmax data skipping indexes, but couldn't find a answer about how does CH get the min and max value.

**Did it also work for base 36 values?**

for example, there is three values in column "log_id": `9mz1`, `9mz2` and `9mz3`, can CH properly get the min and max value of this column if I set a minmax indexes for it?

Can I use query like `select '9mz3' > '9mz1'` to confirm that CH are correctly treating the value?

Thank you very much

**Comment by lingtaolf** [comment]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/87509571/233895513-1c3ea981-ca90-44af-8eb0-8b64b0eb741b.png">
Can work with string.

**Comment by lingtaolf** [comment]
But , It seems sort in lexicographical order which means sql `select * from t where str>'9mz901` will get the result str is `9mz91`.

**Comment by jasonbigl** [comment]
@lingtaolf seems the CH are indeed doing string ordering by lexicographical, thank you very much for the info

`select '2' > '10';`

```
┌─greater('2', '10')─┐
│                  1 │
└────────────────────┘
```
