### ISSUE TITLE
Support nullable values in external dictionary

### ISSUE THREAD

**Issue by crakjie** [ClickHouse/ClickHouse#4910]
related to #2351

Because we have a use case where some values of a dictionary can be Nullable. It's could be nice to have this feature.

**Comment by ShonT** [comment]
We too have a use case where we need null values in a dictionary and is stopping us from migrating our data to CH. Any update on when we could use this?

**Comment by sszc** [comment]
Our existing case requires that the external dictionary field can be NULL.

**Comment by marrocksd** [comment]
This is really neccessary

**Comment by Slind14** [comment]
this was working fine in 19.16.x and doesn't work anymore in 20.3.x blocking updating.

**Comment by alexey-milovidov** [comment]
@Slind14 I don't understand what was working fine? There support for NULL values in external dictionaries never existed.

**Comment by alexey-milovidov** [comment]
The implementation is being developed by @kitaisreal in #18236.

**Comment by Slind14** [comment]
> @Slind14 I don't understand what was working fine? There support for NULL values in external dictionaries never existed.

A dict with a table as source that contains nullable works in 19.x

**Comment by filimonov** [comment]
@kitaisreal fixed?

**Comment by kitaisreal** [comment]
@filimonov currently supported for Flat, Hashed, ComplexKeyHashed, Direct, ComplexKeyDirect, RangeHashed.
Cache, ComplexKeyCache, SSDCache, SSDComplexKeyCache, Polygon, IPTrie are not yet supported.

**Comment by kitaisreal** [comment]
Nullable type is supported for all dictionary layouts except IPTrie.
