### ISSUE TITLE
02516_projections_with_rollup flaky test (timeout)

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#49129]
stats
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMjUxNl9wcm9qZWN0aW9uc193aXRoX3JvbGx1cCUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

failture in master
https://s3.amazonaws.com/clickhouse-test-reports/0/a7db8d1d71f15dbbc9b5490c147913334fd006b9/stateless_tests__debug__[2/5].html

**Comment by tavplubix** [comment]
It did not fail for a while according to the CI DB
