### ISSUE TITLE
Cannot open file `tmp_mut_20230423_0_14350_6277_15670/uuid.txt`: Permission denied

### ISSUE THREAD

**Issue by huisede** [ClickHouse/ClickHouse#49128]
**Describe the issue**
I want to drop an existing projection on my local table on cluster(data are continuously inserting into local table), here are the queries：

ALTER TABLE live.live_flow_stay_time_local on cluster xxxxx
	ADD PROJECTION live_id_proj
	( 
	    SELECT 
	    	dt, platform, LID, minuteIdx, tenMinIdx, hourIdx, content_type_cd, sum(stm_rt)
	    GROUP BY dt, platform, LID, minuteIdx, tenMinIdx, hourIdx, content_type_cd
	) 
[OK]

ALTER TABLE live.live_flow_stay_time_local on cluster xxxxx MATERIALIZE PROJECTION live_id_proj
[OK]

ALTER TABLE live.live_flow_stay_time_local on cluster xxxxx drop PROJECTION live_id_proj
Code: 341. DB::Exception: Exception happened during execution of mutation '0000000002' with part '20230423_0_14350_6277_15669' reason: 'Code: 76. DB::ErrnoException: Cannot open file /data5/*****/clickhouse/data/store/ded/ded50fae-d9b7-42b1-a167-7cab828887e3/tmp_mut_20230423_0_14350_6277_15670/uuid.txt, errno: 13, strerror: Permission denied. (CANNOT_OPEN_FILE) (version 22.3.2.1)'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED) (version 22.3.2.1)

**How to reproduce**
ClickHouse 22.3.2.1
DBeaver 21.3.2

**CREATE TABLE statements for all tables involved**

CREATE TABLE live.live_flow_stay_time_local on cluster xxxxx
(
    `source` String,
    `sub_source` String,
    `origin_value` String,
    `platform` String,
    `browser_uniq_id` String,
    `LID` String,
    `content_type_cd` String,
    `content_cate_cd` String,
    `report_time` String,
    `stm_rt` UInt32,
    `minuteIdx` UInt16,
    `tenMinIdx` UInt16,
    `hourIdx` UInt16,
    `dt` Date DEFAULT toDate(report_time)
)
ENGINE = ReplicatedMergeTree('/clickhouse/xxxxx/live/live_flow_stay_time_local/{shard}',
 '{replica}')
PARTITION BY dt
ORDER BY (LID,
 browser_uniq_id,
 platform,
 minuteIdx)
TTL dt + toIntervalDay(7)
SETTINGS storage_policy = 'jdob_ha',
 index_granularity = 8192`

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by sunny19930321** [comment]
projection Deletion. Metadata in the zk will not be deleted. Is zk metadata deletion performed asynchronously
Received exception from server (version 22.3.2):
Code: 517. DB::Exception: Received from 11.97.78.122:9600. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. It means that this replica still not applied some of previous alters. Probably too many alters executing concurrently (highly not recommended). You can retry this error. (CANNOT_ASSIGN_ALTER)
