### ISSUE TITLE
(Should/Could) Avro format decimal support ingestion where bytes.size < field_type_size

### ISSUE THREAD

**Issue by davidrobbo** [ClickHouse/ClickHouse#49130]
**Describe the unexpected behaviour**

I'm using AvroConfluent format with a field in my avro schema as:
`
{ "name": "aDecimal", "type": { "logicalType": "decimal", "precision": 22, "scale": 3, "type": "bytes" }
`
Ingesting from confluent, my records contain variable bytes size as opposed to being fixed to 16 for all records. During ingestion, I receive an error informing me ` Cannot parse type Decimal(22, 3), expected binary data with size 16, got 1:`

**How to reproduce**
* I expect the easiest way would be to introduce a decimal field to an existing test in `src/tests/queries/0_stateless/data_avro/logical_types.avro` where bytes.size < 16

**Expected behavior**
Any avro decimal value with byte.size 1-to-16 able to be parsed to (i.e. for my use case) Decimal(22,3)

**Error message and/or stacktrace**
Expect `src/src/Processors/Formats/Impl/AvroRowInputFormat.cpp#L177` is where this occurs

2023.04.21 12:27:27.568775 [ 204 ] {} void DB::StorageKafka::threadFunc(size_t): Code: 376. DB::Exception: Cannot parse type Decimal(22, 3), expected binary data with size 16, got 1: while parsing Kafka message (topic: test-topic, partition: 0, offset: 0)': While executing Kafka. (CANNOT_PARSE_UUID), Stack trace (when copying this message, always include the lines below):

DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe1e20b5 in /usr/bin/clickhouse
? @ 0x14a8879c in /usr/bin/clickhouse
? @ 0x14a89006 in /usr/bin/clickhouse
? @ 0x14a8a88c in /usr/bin/clickhouse
? @ 0x14a8b0b1 in /usr/bin/clickhouse
? @ 0x14a8a9f6 in /usr/bin/clickhouse
? @ 0x14a8b0b1 in /usr/bin/clickhouse
? @ 0x14a735d4 in /usr/bin/clickhouse
? @ 0x14a73621 in /usr/bin/clickhouse
DB::AvroConfluentRowInputFormat::readRow(std::vector<COWDB::IColumn::mutable_ptrDB::IColumn, std::allocator<COWDB::IColumn::mutable_ptrDB::IColumn>>&, DB::RowReadExtension&) @ 0x14a75814 in /usr/bin/clickhouse
DB::IRowInputFormat::generate() @ 0x14a921ae in /usr/bin/clickhouse
DB::ISource::tryGenerate() @ 0x14a14f95 in /usr/bin/clickhouse
DB::ISource::work() @ 0x14a14b06 in /usr/bin/clickhouse
DB::StreamingFormatExecutor::execute() @ 0x14a38b84 in /usr/bin/clickhouse
DB::KafkaSource::generateImpl() @ 0x14264535 in /usr/bin/clickhouse
DB::KafkaSource::generate() @ 0x14267caf in /usr/bin/clickhouse
DB::ISource::tryGenerate() @ 0x14a14f95 in /usr/bin/clickhouse
DB::ISource::work() @ 0x14a14b06 in /usr/bin/clickhouse
DB::ExecutionThreadContext::executeTask() @ 0x14a2e70a in /usr/bin/clickhouse
DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic*) @ 0x14a2377b in /usr/bin/clickhouse
DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14a228d1 in /usr/bin/clickhouse
DB::PipelineExecutor::execute(unsigned long) @ 0x14a22571 in /usr/bin/clickhouse
DB::CompletedPipelineExecutor::execute() @ 0x14a20add in /usr/bin/clickhouse
DB::StorageKafka::streamToViews() @ 0x14257124 in /usr/bin/clickhouse
DB::StorageKafka::threadFunc(unsigned long) @ 0x14255135 in /usr/bin/clickhouse
DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x127c0686 in /usr/bin/clickhouse
DB::BackgroundSchedulePool::threadFunction() @ 0x127c356a in /usr/bin/clickhouse
? @ 0x127c43ae in /usr/bin/clickhouse
ThreadPoolImplstd::thread::worker(std::__list_iterator<std::thread, void*>) @ 0xe2b13f3 in /usr/bin/clickhouse
? @ 0xe2b7061 in /usr/bin/clickhouse
? @ 0x7f0dd6dfbb43 in ?
? @ 0x7f0dd6e8da00 in ?
(version 23.3.2.37 (official build))

**Comment by davidrobbo** [comment]
@tavplubix Perhaps you could help?

**Comment by Avogar** [comment]
Hi! Thank you for your feedback. Unfortunately, by now we just don't support such Decimals as in your file in Avro format. I will try to add support for such cases.

**Comment by davidrobbo** [comment]
Thanks for confirming @Avogar. I'm new to ClickHouse, so not sure how long support has been available for decimals in Avro (and therefore AvroConfluent), but I believe how we are serialising is the recommended approach so peculiar others haven't run into this sooner.

Adding some examples values from the confluence GUI which hopefully helps confirm the behaviour I've described that would lead to the error:
`
...
{
  "type": "Buffer",
  "data": [
    0
  ]
},
{
  "type": "Buffer",
  "data": [
    1,
    201,
    195,
    128
  ]
}
{
  "type": "Buffer",
  "data": [
    0,
    195,
    80
  ]
}
...
`

**Comment by Avogar** [comment]
Actually, support for Decimals in Avro was added quite recently

**Comment by davidrobbo** [comment]
@Avogar is there anything I can do to assist with this? Pointer to examples in the confluent serdes libs? A bit of manual testing once ready? Let me know :) thanks again

**Comment by Avogar** [comment]
I will start working on this after next week (because I will be on vacation all next week). I will ask questions if any here, thanks for your help!
It will be great if you will attach an example Avro file for testing.

**Comment by davidrobbo** [comment]
As I'm using ConfluentAvro, I'm not heavily involved in the low level code that handles the writing of bytes on the producer side, so am struggling to produce an example file with confidence it would reflect the same contents as would the KafkaAvroSerializer/input from confluent. 

Believe the the code in question is found in `org.apache.avro:avro:1.11.1` `package org.apache.avro, class Conversions.DecimalConversion`.

However, have used the below code to generate what I believe is the correct representation (adding in case others can confirm or correct to help out)

```
// some java...
byte[] score = new BigDecimal("2.1").unscaledValue().toByteArray();
StringBuilder sb = new StringBuilder();
for (byte b : score) {
    sb.append(String.format("\\u%04x", b));
}
// sb.toString() == "\u0008\u0034"

// decimal.avsc
{
  "fields": [
    {
      "name": "decimal",
      "type": {
        "logicalType": "decimal",
        "precision": 22,
        "scale": 3,
        "type": "bytes"
      }
    }
  ],
  "name": "ARecord",
  "namespace": "com.something",
  "type": "record"
}

//decimal.json
{
  "decimal": "\u0008\u0034"
}
```
Then used the following command to generate what I hope is useful for you! `java -jar avro-tools-1.11.1.jar fromjson --schema-file decimal.avsc decimal.json > decimal.avro` (and then `gzip decimal.avro` which can be decompressed with `gzip -d decimal.avro.gz` as github seemingly doesn't support avro file uploads)
[decimal.avro.gz](https://github.com/ClickHouse/ClickHouse/files/11414041/decimal.avro.gz)

**Comment by davidrobbo** [comment]
Hi @Avogar. Just checking if this is still something that you may be able to look into?,Very excited to use it as will unlock some exciting avenues for me.

**Comment by Avogar** [comment]
Sorry for delay, had a lot of other tasks. Hope will be able to start working on it this week.

**Comment by davidrobbo** [comment]
In the interim, are you/anybody aware of existing methods that might be used as a workaround? Wondering if perhaps I could preserve decimal fields as bytes in my table(s) and use some combination of existing clickhouse functions in my queries to convert to decimal

**Comment by Avogar** [comment]
I will create a PR with support for decimals with bytes.size less than expected.
As a workaround, you can try smth like:
```
avogar-dev :) select reinterpret(reverse(leftPad(decimal, byteSize(42::Decimal(P, S)) - length(d), '\0')), 'Decimal(P, S)') from file(data.avro, auto, 'decimal String')
```

**Comment by davidrobbo** [comment]
There still seems to be something a bit off with Decimal support and the AvroConfluent format. My topic contains values (i.e.) like `-2000000.000` that are being ingested into CH as `2674967.296`

**Comment by davidrobbo** [comment]
@Avogar seemingly reporting positives decimal correctly however - could it be negatives are not handled?

**Comment by davidrobbo** [comment]
After a bit of investigation, I believe 2's compliment is not being handled.

Positive decimal example working correctly end-to-end/Confluent-to-ClickHouse:
AvroConfluent ByteBuffer = `[0, 207, 6]`
Binary = `00000000 11001111 00000110`
Decimal = `52998`
Expected CH Decimal(22,3) = `52.998`
Actual CH Decimal(22,3) = `52.998`

Negative decimal example working incorrectly end-to-end/Confluent-to-ClickHouse:
AvroConfluent ByteBuffer = `[136, 202, 108, 0]`
Binary = `10001000 11001010 01101100 00000000`
Decimal = `2294967296`
Decimal 2's compliment = `-2000000000`
Expected 2's compliment = `-2000000.000`
Actual CH Decimal(22,3) = `2294967.296`

**Comment by Avogar** [comment]
Thanks for testing, indeed there is a bug in the logic, I will fix it

**Comment by Avogar** [comment]
Fix: https://github.com/ClickHouse/ClickHouse/pull/50668

**Comment by davidrobbo** [comment]
I see the fix is approved - I have some time today to test if it can be merged

**Comment by MarekMaj** [comment]
> I will create a PR with support for decimals with bytes size less than expected today. As a workaround, you can try smth like:
> 
> ```
> avogar-dev :) select reinterpret(reverse(leftPad(decimal, byteSize(42::Decimal(P, S)) - length(d), '\0')), 'Decimal(P, S)') from file(data.avro, auto, 'decimal String')
> ```

Hi Avogar,
could you decipher what 42 number and 'd' stand for? Does this workaround work for negative values?

**Comment by Avogar** [comment]
Actually I just realized that that query is a bit incorrect. There should be `leftPad(decimal, byteSize(42::Decimal(P, S)), '\0')` instead of `leftPad(decimal, byteSize(42::Decimal(P, S)) - length(d), '\0')` (no substruction needed).

> could you decipher what 42 number and 'd' stand for? 

42 is just a random number I casted to `Decimal(P, S)` to execute `byteSize` to know the byte size of the data type (you can use just constant value if you know the size). `d` was just a typo, it should be `decimal`.

>  Does this workaround work for negative values?

To support negative values, the query will become more complex (the pad value depends on the negativity of value):
```
:) with byteSize(42::Decimal(P, S)) as type_size select reinterpret(reverse(if(bitSlice(d, 1, 1) == x'80', leftPad(decimal, type_size, x'ff'), leftPad(decimal, type_size, x'00'))), 'Decimal(P, S)') as correct_decimal from file(decimals.avro, auto, 'd String')
```

You can create a UDF to use it:
```
:) create function convert_decimal as (decimal) -> reinterpret(reverse(if(bitSlice(decimal, 1, 1) == x'80', leftPad(d, byteSize(42::Decimal(P, S)), x'ff'), leftPad(d, byteSize(42::Decimal(P, S)), x'00'))), 'Decimal(P, S)')
:) select convert_decimal(decimal) from file(data.avro, auto, 'decimal String')
```

I tested it with some local data (I have values of Decimal(14, 4) with different sizes):
```
:) create function convert_decimal as (decimal) -> reinterpret(reverse(if(bitSlice(decimal, 1, 1) == x'80', leftPad(d, byteSize(42::Decimal(14, 14)), x'ff'), leftPad(d, byteSize(42::Decimal(14, 4)), x'00'))), 'Decimal(14, 4)')

:) select convert_decimal(d) as res from file(decimals.avro, auto, 'd String')

SELECT convert_decimal(d) AS res
FROM file(decimals.avro, auto, 'd String')

Query id: 39d295e1-a8c7-43d9-a37f-2a86d8ecf6e3

┌──────────────res─┐
│                0 │
│                1 │
│              1.1 │
│            12.12 │
│          123.123 │
│        1234.1234 │
│       12345.1234 │
│      123456.1234 │
│     1234567.1234 │
│    12345678.1234 │
│   123456789.1234 │
│  1234567890.1234 │
│                0 │
│               -1 │
│             -1.1 │
│           -12.12 │
│         -123.123 │
│       -1234.1234 │
│      -12345.1234 │
│     -123456.1234 │
│    -1234567.1234 │
│   -12345678.1234 │
│  -123456789.1234 │
│ -1234567890.1234 │
└──────────────────┘

24 rows in set. Elapsed: 0.001 sec.

```

Should work, but it will be better if you will test it on your data

**Comment by MarekMaj** [comment]
@Avogar we applied your workaround by creating function
`CREATE FUNCTION IF NOT EXISTS convert_decimal ON CLUSTER 'cluster' as (val, type) -> reinterpret(reverse(if(bitSlice(val, 1, 1) == x'80', leftPad(val, byteSize(CAST('42', type)), x'ff'), leftPad(val, byteSize(CAST('42', type)), x'00'))), type);`

and so far it looks good, we have not found any discrepancies with expected results. Thanks for your support!
