### ISSUE TITLE
Clickhouse v23.3 broke compatibility with Spark by using LZ4 compression format for Parquet

### ISSUE THREAD

**Issue by ei-grad** [ClickHouse/ClickHouse#49141]
**Describe the issue**
Clickhouse server v23.3 changed the compression format for Parquet from SNAPPY to LZ4, which is not supported by the current Spark version. The LZ4 compression method used by Clickhouse v23.3 (LZ4_RAW) is only widely adopted in the parquet-cpp implementation and arrow library, and not in the parquet-mr implementation used by Spark.

**How to reproduce**

  1. Run the following command with Clickhouse v23.3:
```
docker run -i --rm clickhouse/clickhouse-server:23.3 clickhouse local --query 'SELECT 1 FORMAT Parquet' | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
```
Output: `LZ4`

  2. Run the same command with Clickhouse v23.2:
```
docker run -i --rm clickhouse/clickhouse-server:23.2 clickhouse local --query 'SELECT 1 FORMAT Parquet' | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
```
Output: `SNAPPY`

**Additional context**
The LZ4_RAW compression format used by Clickhouse v23.3 is only supported in the recent release of parquet-mr (1.13.0), which is not included in the latest Spark versions (2.4.0, and others). As a result, the compatibility between Clickhouse and Spark is broken. A possible solution is to revert to using SNAPPY compression format by default.

Corresponding Spark issue to support LZ4_RAW compression in Parquet: https://issues.apache.org/jira/browse/SPARK-43273

Spark gives the following error when reading Parquet files generated by ClickHouse v23.3 with default Parquet compression:
```
No enum constant org.apache.parquet.hadoop.metadata.CompressionCodecName.LZ4_RAW
```

As a workaround one can use [output_format_parquet_compression_method](https://clickhouse.com/docs/en/operations/settings/formats#output_format_parquet_compression_method) parameter to specify other compression methods, for example `snappy` or `zstd`, which are supported by Spark. But this parameter was only introduced in v23.3, so there is no strict way to update Clickhouse version safely without redeploying Spark application together with cluster upgrade.

**Comment by Avogar** [comment]
The default compression was changed to `lz4` by @alexey-milovidov advice :) https://github.com/ClickHouse/ClickHouse/pull/47114#discussion_r1125478335
I am ok to get back to snappy

**Comment by alexey-milovidov** [comment]
Ok, let's revert back to snappy.

**Comment by ei-grad** [comment]
> if Spark does not support LZ4

Spark supports the different one, and it is a long story in Apache community, but 

> it's a problem of Spark

for sure

But still, introducing (as it become) a breaking change without a grace period, making it not possible for the client code to implement a clear logic to work with both versions of Clickhouse, is not a good practice also, and this is the Clickhouse's users problem they have to deal with.

I mean - you couldn't just add `output_format_parquet_compression_method` parameter because previous Clickhouse version doesn't support it. And you couldn't run queries on new Clickhouse version because it began to output data in different format. You have to stop the service, upgrade Clickhouse, and then deploy new service version using `output_format_parquet_compression_method` parameter.

If there was an intermediate Clickhouse version supporting `output_format_parquet_compression_method` but keeping the default behavior unchanged - just upgrade to this CH version and deploy new service version with `output_format_parquet_compression_method` without downtime. And then you won't have problems when next CH version would change default behavior apparently, and you can even then switch to LZ4 when Spark support it (or just use zstd for better compression ratios where CPU is not critical).

**Comment by ei-grad** [comment]
Actually, there is another issue which could also be more-or-less critical for some users - 23.3 introduced the compression for Arrow format, which was uncompressed before that. Compressed Arrow data behave differently when used with memmap (compressed columns are decompressed into the process memory), so it is also breaking change.

For ORC, which compression method has been also changed, I don't see any problems.

As of my current understanding, it would be more hustle with changing this defaults in Clickhouse server code. Rather this issues should be highlighted somewhere in CHANGELOG (or in the format docs?), and it could be suggested workaround for affected users to specify needed compression method in server config in profile default settings.

**Comment by ei-grad** [comment]
Also, there is a place in docs where default values are not updated - https://clickhouse.com/docs/en/operations/settings/formats#output_format_parquet_compression_method

> output_format_parquet_compression_method - compression method used in output Parquet format. Default value - snappy.

**Comment by ei-grad** [comment]
@alexey-milovidov

**Comment by Algunenano** [comment]
You can use the compatibility setting:
```
/mnt/ch/official_binaries $ ./clickhouse-common-static-23.2.1.2537/usr/bin/clickhouse local --query 'SELECT 1 FORMAT Parquet' | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
SNAPPY
/mnt/ch/official_binaries $ ./clickhouse-common-static-23.4.1.1943/usr/bin/clickhouse local --query 'SELECT 1 FORMAT Parquet' | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
LZ4
/mnt/ch/official_binaries $ ./clickhouse-common-static-23.2.1.2537/usr/bin/clickhouse local --compatibility 23.2 --query 'SELECT 1 FORMAT Parquet' | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
SNAPPY
/mnt/ch/official_binaries $ ./clickhouse-common-static-23.4.1.1943/usr/bin/clickhouse local --compatibility 23.2 --query 'SELECT 1 FORMAT Parquet' | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
SNAPPY
```

**Comment by ei-grad** [comment]
@Algunenano is it a setting which would only work with clickhouse-client / clickhouse-local? Can it be set by client on HTTP interface?

**Comment by Algunenano** [comment]
You can pass it anywhere where settings are allowed, including users.xml, the query itself or http:

```
$ ./clickhouse-common-static-23.4.1.1943/usr/bin/clickhouse local --query "SELECT 1 SETTINGS compatibility='23.2' FORMAT Parquet" | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
SNAPPY
```

```
/tmp $ curl 'http://clickhouse-01:48123/?query=SELECT%201%20FORMAT%20Parquet' --output - | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   281    0   281    0     0   214k      0 --:--:-- --:--:-- --:--:--  274k
LZ4


/tmp $ curl 'http://clickhouse-01:48123/?query=SELECT%201%20FORMAT%20Parquet&compatibility=23.2' --output - | python -c 'import sys, io, pyarrow.parquet as pq; f = pq.ParquetFile(io.BytesIO(sys.stdin.buffer.read())); print(f.metadata.row_group(0).column(0).compression)'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   283    0   283    0     0   174k      0 --:--:-- --:--:-- --:--:--  276k
SNAPPY
```
