### ISSUE TITLE
MySQL compatibility: SHOW KEYS

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/ClickHouse#49140]
**Use case**

Some BI tools like QuickSight want to query indices using the following query:

```mysql
SHOW KEYS FROM `cell_towers` FROM `default`;
```

**How to reproduce**

* Which ClickHouse server version to use: the latest main branch version will do. I used the head Docker image from the beginning of April: `23.4.1.170`
* Which interface to use, if it matters: MySQL
* `CREATE TABLE` statements for all tables involved: use [cell towers](https://clickhouse.com/docs/en/getting-started/example-datasets/cell-towers) dataset, then query via MySQL protocol

**Describe the solution you'd like**

SHOW KEYS statement is supported.

**Comment by rschu1ze** [comment]
@ilejn Thanks, fix: https://github.com/ClickHouse/ClickHouse/pull/60514
