### ISSUE TITLE
Result of OUTER JOIN is incorrect

### ISSUE THREAD

**Issue by wangxiaoying** [ClickHouse/ClickHouse#49166]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Result columns of `OUTER JOIN` currently is not forced to be nullable. Thus the result might be incorrect.

**How to reproduce**
Here is a toy example:
```sql
CREATE OR REPLACE TABLE test
(
    id UInt64
)ENGINE = MergeTree
ORDER BY id;

CREATE OR REPLACE TABLE test1
(
    id UInt64, 
    flag Bool
)ENGINE = MergeTree
ORDER BY id;

insert into test values (1), (2);
insert into test1 values (2, true);

```

And here is the result of query `select * from test left join test1 on test.id = test1.id`:
```
┌─id─┬─test1.id─┬─flag──┐
│  1 │        0 │ false │
│  2 │        2 │ true  │
└────┴──────────┴───────┘
```

Looks like both `test1.id` and `test1.flag` are filled in with their default value when there is not match.

The issue will escalate for queries like `select * from test left join test1 on test.id = test1.id and flag is NULL` since the result will become empty, which is incorrect under the semantic of left join.

**Expected behavior**
Result columns of `OUTER JOIN` should be nullable, even the child table is not.

**Additional context**
Such queries (left join + is null filter) are usually generated after rewriting of queries with `NOT EXSITS`.

**Comment by tavplubix** [comment]
See `join_use_nulls` setting:
```
dell9510 :) select * from test left join test1 on test.id = test1.id

SELECT *
FROM test
LEFT JOIN test1 ON test.id = test1.id

Query id: 9d0fbd77-a466-480a-a5cf-06b686894d49

┌─id─┬─test1.id─┬─flag──┐
│  1 │        0 │ false │
│  2 │        2 │ true  │
└────┴──────────┴───────┘

2 rows in set. Elapsed: 0.032 sec. 

dell9510 :) set join_use_nulls=1

SET join_use_nulls = 1

Query id: 882510d6-06ee-4a29-9cf2-bbde8cdba70c

Ok.

0 rows in set. Elapsed: 0.003 sec. 

dell9510 :) select * from test left join test1 on test.id = test1.id

SELECT *
FROM test
LEFT JOIN test1 ON test.id = test1.id

Query id: 96c9a1bd-5294-4254-af2d-362bc2d1849f

┌─id─┬─test1.id─┬─flag─┐
│  1 │     ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │
│  2 │        2 │ true │
└────┴──────────┴──────┘

2 rows in set. Elapsed: 0.026 sec. 
```
