### ISSUE TITLE
test_distributed_load_balancing/test.py::test_load_balancing_first_or_random is flaky

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#49176]
```
=================================== FAILURES ===================================
_____________________ test_load_balancing_first_or_random ______________________
[gw1] linux -- Python 3.8.10 /usr/bin/python3

    def test_load_balancing_first_or_random():
        unique_nodes = set()
        for _ in range(0, queries):
            unique_nodes.add(get_node(n1, settings={"load_balancing": "first_or_random"}))
>       assert len(unique_nodes) == 1, unique_nodes
E       AssertionError: {'n1', 'n2', 'n3'}
E       assert 3 == 1
E        +  where 3 = len({'n1', 'n2', 'n3'})
```

https://s3.amazonaws.com/clickhouse-test-reports/0/259d23303f63d17faa99723ddba9d9ba53ae5b9a/integration_tests__asan__[1/6].html

https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2xvYWRfYmFsYW5jaW5nX2ZpcnN0X29yX3JhbmRvbSUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/47475/43cf31a98eaa53b2c7af9859e2b03dc31706d7d8/integration_tests__tsan__[1_6].html

**Comment by alexey-milovidov** [comment]
No failures on master for the past half a year.
