### ISSUE TITLE
01961_roaring_memory_tracking is still flaky

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#49180]
`Expected server error code '241' but got no server error`
https://s3.amazonaws.com/clickhouse-test-reports/0/d4394ac9493132dd17a2166b455249cfe1d0394d/stateless_tests__aarch64_.html
https://s3.amazonaws.com/clickhouse-test-reports/0/3315acd122e0094d633043518e5189705f638950/stateless_tests__release_.html

https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMTk2MV9yb2FyaW5nX21lbW9yeV90cmFja2luZyUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l

**Comment by alexey-milovidov** [comment]
Not anymore.

**Comment by tavplubix** [comment]
Still flaky https://s3.amazonaws.com/clickhouse-test-reports/58649/2cf74aea5c618bb228eb582b9aaa4481f2879e11/stateless_tests__release__s3_storage__[1_2].html

**Comment by alexey-milovidov** [comment]
Fixed.
