### ISSUE TITLE
can't create sessions via dbeaver

### ISSUE THREAD

**Issue by VeryFunnyMan** [ClickHouse/ClickHouse#49219]
I specify session_id and session_timeout in the driver properties through dbeaver, but when I try to `CREATE TEMPORARY TABLE ...` I still get the error "There is no session or session context has expired". 

If using http I execute a request, write session_id and session_timeout, then a temporary table is created.

`http://host:port/?user=user&password=password&session_id=session_id&session_timeout=600&database=database&query=CREATE%20TEMPORARY%20TABLE...`
how to fix it?

Standard clickhouse driver com.clickhouse:clickhouse-jdbc:RELEASE 0.3.2
clickhouse 22.9.3.18
dbeaver 22.2.1.202209251341
I have full permissions

**Comment by den-crane** [comment]
works for me
<img width="693" alt="Screenshot 2023-04-26 at 10 22 27 PM" src="https://user-images.githubusercontent.com/19737682/234743615-b8d63ba1-ef34-45c1-bd6d-42f1934f7365.png">

**Comment by VeryFunnyMan** [comment]
> works for me

I did the same. the difference is I had to add user proprity "session_id"
and im on win10 21H2
![image](https://user-images.githubusercontent.com/42913013/234780700-c5681f85-e8f6-43e7-9ec0-e9275d933c3e.png)

**Comment by den-crane** [comment]
Ask this https://github.com/yandex/ClickHouse-jdbc/ 
question is not related to server
