### ISSUE TITLE
Wrong results when using LowCardinality columns as join pivots (`USING` column) across tables 

### ISSUE THREAD

**Issue by agaurav** [ClickHouse/ClickHouse#4923]
**Describe the bug**
It seems LowCardinality(String) have different hashed value in different tables for the same string value.

I have a region column in different tables as type `LowCardinality(String)`, the JOIN seems to give empty rows for some values of Region while there are matching rows in the two subqueries.

**How to reproduce**
* ClickHouse server version : v19.4.3

* Example with two tables 

table 1
``` sql
CREATE TABLE test.quants
(
    TS                         DateTime,
    Region                  LowCardinality(String),
    Metric                   LowCardinality(String),
    QuantAvg             Float64,
    Updated               DateTime
)
ENGINE = ReplacingMergeTree(Updated)
PARTITION BY (Region, toYYYYMM(TS))
PRIMARY KEY (Region, TS)
ORDER BY (Region, TS,Metric)
```

table 2
``` sql
CREATE TABLE test.trends
(
    TS                         DateTime,
    Region                  LowCardinality(String),
    Metric                   LowCardinality(String),
    TrendAvg             Float64,
    Updated               DateTime
)
ENGINE = ReplacingMergeTree(Updated)
PARTITION BY (Region, toYYYYMM(TS))
PRIMARY KEY (Region, TS)
ORDER BY (Region, TS,Metric)
```

Now the following join queries will give empty results even while having matching rows for some regions while correct results for others.
``` sql
SELECT TS,Region,Metric, QuantAvg, TrendAvg FROM 
(
      SELECT 
             TS,Region,Metric,QuantAvg 
      FROM test.quants
      WHERE Region = 'asia'
) ALL LEFT JOIN (
      SELECT 
             TS,Region,Metric, TrendAvg 
      FROM test.trends
      WHERE Region = 'asia'
) USING TS,Region,Metric
```

**Comment by KochetovNicolai** [comment]
It would be helpful if you can show some rows that can't match.
Can you also check that it's a problem with LowCardinality? Just cast LowCardinality to String:
```sql
SELECT TS,Region,Metric, QuantAvg, TrendAvg FROM 
(
      SELECT 
             TS, cast(Region as String) as Region, cast(Metric as String) as Metric,QuantAvg 
      FROM test.quants
      WHERE Region = 'asia'
) ALL LEFT JOIN (
      SELECT 
             TS,cast(Region as String) as Region, cast(Metric as String) as Metric, TrendAvg 
      FROM test.trends
      WHERE Region = 'asia'
) USING TS,Region,Metric
```
Does this query work fine?

**Comment by agaurav** [comment]
The above query didn't work as well but its seems removing `LowCardinality` field as partitioning key worked. 
I will try to provide a data dump to reproduce the above after some obfuscation. The actual query and table is much larger with multiple joins and pivots.

**Comment by KochetovNicolai** [comment]
Thanks!

**Comment by filimonov** [comment]
@agaurav any news here?

**Comment by agaurav** [comment]
@filimonov sorry got lost in some ongoing work. I will generate the data and schema to reproduce during the weekend.

**Comment by alexey-milovidov** [comment]
@agaurav I hope the weekend went well?
