### ISSUE TITLE
`01320_create_sync_race_condition_zookeeper` tsan data race

### ISSUE THREAD

**Issue by serxa** [ClickHouse/ClickHouse#49230]
[not often](https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSA9ICcwMTMyMF9jcmVhdGVfc3luY19yYWNlX2NvbmRpdGlvbl96b29rZWVwZXInCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgZGVzYywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l) but tsan fails with different a data [races](https://s3.amazonaws.com/clickhouse-test-reports/0/dee22621836d3795e41597cb459b447e85829444/stateless_tests__tsan__[3/5]/run.log)

race [one](https://pastila.nl/?006c8193/539c4ca86744a99d3bf612762a3837ad)
race [two](https://pastila.nl/?006c8193/dd140d032e136b6aff87c6cc36e77212)

**Comment by tavplubix** [comment]
The first one - https://github.com/ClickHouse/ClickHouse/pull/49302
The second one looks like https://github.com/ClickHouse/ClickHouse/issues/49156
