### ISSUE TITLE
Count how many times a function is executed in a query [profiling]

### ISSUE THREAD

**Issue by aramperes** [ClickHouse/ClickHouse#49245]
Is there a built-in way to estimate/count on _how many_ blocks a specific function was used when processing a query? For example, while my query says `Processed 2.23 million rows, 409.61 MB (5.20 million rows/s., 954.94 MB/s.)`, I'd like to demonstrate if a `WHERE splitByRegexp(...)` function is applied 2.23 million times, or much less.

`query_log` has the array of `used_functions`, but as I understand it, this is collected when parsing the query.

I'm unclear if `trace_log` would trace individual function calls, it seems to be more for timings?

**Comment by aramperes** [comment]
Possibly, building ClickHouse with code coverage enabled would achieve this?

**Comment by Algunenano** [comment]
CH functions are always called in blocks, not per row.

Simplifying things: Supposing a query like `SELECT column2 FROM table WHERE has(splitByRegexp(regex, column), '42')` and Mergetree, currently CH will try to initialize a pipeline with multiple threads for reading the affected columns (column and column2) in parallel. Once it has the necessary data for a part, the threads will start executing `splitByRegexp` by blocks (see `max_block_size`, by default 65k).

It's currently not possible to determine the number of calls to individual function in a query, but ProfileEvents does include the nº of all function calls done (per block) in a query.


E.g.:

```
SELECT sleepEachRow(0.001)
FROM numbers(10)

'FunctionExecute':1,
```

```
SELECT sleepEachRow(0.001)
FROM numbers(10)
SETTINGS max_block_size = 3

'FunctionExecute':4,
```
