### ISSUE TITLE
clickhouse backup error cant attach partitions for table  XXX  code 999 message connection loss path

### ISSUE THREAD

**Issue by senlin1991** [ClickHouse/ClickHouse#49246]
I encountered an error while using "clickhouse backup" to import data to the "ClickHouse Keeper" cluster node. I attempted to modify the "operation_timeout_ms" of the configuration file config.xml in ClickHouse Keeper, After increasing the ms parameter to ten minutes, there were some effects, but eventually an error was still reported. When you continue to increase this value, it no longer has any effect, which is a bit strange

2023.04.28 15:03:45.721833 [ 12206 ] {} <Error> InterserverIOHTTPHandler: Code: 24. DB::Exception: Cannot write to ostream at offset 186507440. (CANNOT_WRITE_TO_OSTREAM), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37173a in /usr/bin/clickhouse
1. DB::WriteBufferFromOStream::nextImpl() @ 0xb481432 in /usr/bin/clickhouse
2. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x168cfc31 in /usr/bin/clickhouse
3. DB::HashingWriteBuffer::nextImpl() @ 0x16253864 in /usr/bin/clickhouse
4. DB::WriteBuffer::write(char const*, unsigned long) @ 0xb386376 in /usr/bin/clickhouse
5. ? @ 0xb51da89 in /usr/bin/clickhouse
6. DB::DataPartsExchange::Service::sendPartFromDisk(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::WriteBuffer&, int, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IMergeTreeDataPart>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<DB::IMergeTreeDataPart> > > > const&) @ 0x1624745e in /usr/bin/clickhouse
7. DB::DataPartsExchange::Service::processQuery(DB::HTMLForm const&, DB::ReadBuffer&, DB::WriteBuffer&, DB::HTTPServerResponse&) @ 0x162433e7 in /usr/bin/clickhouse
8. DB::InterserverIOHTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::InterserverIOHTTPHandler::Output&) @ 0x166525f8 in /usr/bin/clickhouse
9. DB::InterserverIOHTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x16652f31 in /usr/bin/clickhouse
10. DB::HTTPServerConnection::run() @ 0x168c8cbb in /usr/bin/clickhouse
11. Poco::Net::TCPServerConnection::start() @ 0x19b801ef in /usr/bin/clickhouse
12. Poco::Net::TCPServerDispatcher::run() @ 0x19b82641 in /usr/bin/clickhouse
13. Poco::PooledThread::run() @ 0x19d3f609 in /usr/bin/clickhouse
14. Poco::ThreadImpl::runnableEntry(void*) @ 0x19d3c960 in /usr/bin/clickhouse
15. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
16. clone @ 0xfe8cd in /usr/lib64/libc-2.17.so
 (version 22.3.6.5 (official build))
2023.04.28 15:03:45.725030 [ 12206 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 32, I/O error: Broken pipe, Stack trace (when copying this message, always include the lines below):

**Comment by alexey-milovidov** [comment]
You should ask the authors of clickhouse-backup.
