### ISSUE TITLE
aarch64 build broken after #48833

### ISSUE THREAD

**Issue by jrdi** [ClickHouse/ClickHouse#49254]
ISA-L was introduced in #48833, and looks like it's only available for x86 architectures. This completely broke MacOs M1 compilation, and I guess also any other ARM-based architecture.

**Comment by alexey-milovidov** [comment]
@jrdi, we check the build for Mac OS M1 in every PR and master by cross-compilation on Linux, and the build is available for download and installation as usual. It means only native, manual compilation is broken.

**Comment by jrdi** [comment]
@nikitamikhaylov I've also done a clean rebuild after merging the PR, and everything is working fine. Yours seems to be trying to compile isa-l, do you have Intel or M1?

**Comment by nikitamikhaylov** [comment]
@jrdi I'm not using Mac, this is Manjaro Linux on X86-64...

**Comment by jrdi** [comment]
Sorry, I thought you were talking about macOS Mojave 🤦‍♂️

**Comment by rschu1ze** [comment]
As far as I see, assembly is used in three contribs:
- HDFS/Hadoop (part of most builds): needs yasm
- QPL (experimental/optional): needs nasm
- ISAL (new and mandatory per #48833): needs nasm

Updated the build guide, please install `nasm` + make a scratch build.
