### ISSUE TITLE
Droping Detached Parts in Clickhouse

### ISSUE THREAD

**Issue by Vasu7052** [ClickHouse/ClickHouse#49257]
Hi Team,

Is it safe to DROP DETACHED PARTITIONS from a ClickHouse node using this query 
`ALTER TABLE database.table DROP DETACHED PARTITION '__partition_id__';` 

where `__partition_id__` is received from this query `select database, table, partition_id from system.detached_parts where table = 'xyz' and partition_id is not NULL group by database, table, partition_id order by database, table, partition_id`

The ultimate purpose is to free up some disk space.

Few questions regarding this:
1. Is it safe to perform this action
2. If yes, what should be the ideal frequency of this action on a single node?
3. Are there any checks we need to do before performing this action on a node?

**Comment by den-crane** [comment]
1. it is safe
2. any
3. you can if you want https://kb.altinity.com/altinity-kb-useful-queries/detached-parts/

BTW Clickhouse can do it automatically, if you enable it in MergeTree settings 

```
┌─name───────────────────────────────────────────────────────────┬─value───┬─changed─┬─description───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┐
│ merge_tree_clear_old_broken_detached_parts_ttl_timeout_seconds │ 2592000 │       0 │ Remove old broken detached parts in the background if they remained intouched for a specified by this setting period of time. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
│ merge_tree_enable_clear_old_broken_detached                    │ 0       │       0 │ Enable clearing old broken detached parts operation in background.                                                            │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
└────────────────────────────────────────────────────────────────┴─────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴────────┘
```
