### ISSUE TITLE
`01600_parts_types_metrics_long` and `01600_parts_states_metrics_long` timeout (release, analyzer)

### ISSUE THREAD

**Issue by serxa** [ClickHouse/ClickHouse#49262]
Just one repro yet
Report: https://s3.amazonaws.com/clickhouse-test-reports/49099/a67a84d4cce3ea8a24faa719af323d5f5a1630af/stateless_tests__release__analyzer_.html

**Comment by novikd** [comment]
This is supposed to be fixed in #49318
