### ISSUE TITLE
Latest Master Branch can not compile because contrib/isa-l  

### ISSUE THREAD

**Issue by mateng0915** [ClickHouse/ClickHouse#49291]
> You have to provide the following information whenever possible.

**Describe what's wrong**
**Latest  master branch** can not compile  in Ubuntu (Commit id is **3f959848bd6631f0a86e06d7a3eb9bfc1177a8d2**)

After cmake successfully , during ninja (make install) phase, will throw the error
![image](https://user-images.githubusercontent.com/26053753/235043866-7e9e76fe-eaa0-45fc-9afe-cfb78d49a818.png)

**How to reproduce**
Pull latest master branch
using Ubuntu 
compile the cmake type=release version clickhouse
after cmake done,
ninjia will throw error

**Then Rest to commit** **0caa34f55e4e3d2de8b03b003e895d2434fceb16** 
![image](https://user-images.githubusercontent.com/26053753/235044136-cf7d160e-d00a-4ba4-97bf-c0725932422d.png)

**Compile can successfully**

Thought should be **isa-l lib issue** 

* Which ClickHouse server version to use
Latest master 
The latest commit id is  **3f959848bd6631f0a86e06d7a3eb9bfc1177a8d2**

**Expected behavior**
Compile Successfully

**Comment by jrdi** [comment]
See this comment: https://github.com/ClickHouse/ClickHouse/issues/49254#issuecomment-1526068381

**Comment by alexey-milovidov** [comment]
All builds in the master branch compile successfully.
