### ISSUE TITLE
RESTORE TABLE db.table SETTINGS ... (use different storage policy for restore of backup)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#49304]
**Use case**

Currently during backup restore, it's allow you to restore table as is, with source storage policy.
But it's not always desired behavior, for example if you have tiered storage, during RESTORE TABLE, ClickHouse tries to reserve space in storage policy according to volume order only, and not TTL policy. So old parts can land on local disk instead of s3.

In order to avoid pollution of local disk with old data, it would be good to have ability to restore data to another storage policy.
For example, one which will have only s3 disk. (It also make restore much more faster, ie data needs to be copied from s3 to s3)

**Describe the solution you'd like**

RESTORE TABLE db.table SETTINGS storage_policy='s3'; FROM Backup ....

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/39199

**Comment by sirvickr** [comment]
Please assign me to this task, I'm starting to work on it.
