### ISSUE TITLE
when using HTTP client, double quoted strings are escaped incorrectly in queries

### ISSUE THREAD

**Issue by pkit** [ClickHouse/ClickHouse#49311]
**Describe what's wrong**

When using perfectly valid JSON-encoded strings like these: `{"data": "\"quoted data\""}` inside a query the escaped double quotes become unescaped...

**Does it reproduce on recent release?**

Yes

**How to reproduce**

https://fiddle.clickhouse.com/fd97d7b5-27dc-469a-b7ec-4939f1e4bf72

**Expected behavior**

Escapes `\"` should stay there
If using dual escapes `\\"` they do stay there, but dual escaped JSON is obviously invalid...

It works ok using URL params, but sending big JSONs through URL params is a pretty bad idea.

**Comment by alexey-milovidov** [comment]
As documented:

```
milovidov-desktop :) SELECT '\"', '\\"', $$\"$$

┌─'"'─┬─'\\"'─┬─'\\"'─┐
│ "   │ \"    │ \"    │
└─────┴───────┴───────┘
```

**Comment by pkit** [comment]
@alexey-milovidov that's TCP :)
Try HTTP

```
$ cat 1.sql
SELECT '\"', '\\"', $$\"$$
```

```
$ curl --data @1.sql  http://localhost:8123
"	\\"	\\"
```

**Comment by alexey-milovidov** [comment]
```
milovidov@milovidov-desktop:~$ curl --data-binary @1.sql  http://localhost:8123/?default_format=Pretty
┏━━━━━┳━━━━━━━┳━━━━━━━┓
┃ '"' ┃ '\\"' ┃ '\\"' ┃
┡━━━━━╇━━━━━━━╇━━━━━━━┩
│ "   │ \"    │ \"    │
└─────┴───────┴───────┘
```

**Comment by pkit** [comment]
Hmm, will check it out then. Maybe the fact that it passes through clickhouse-connect means something.
It seems to use `format=Native` though
