### ISSUE TITLE
Operators for two- (or n-) stage aggregations

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#4933]
**Use case**
Imagine having a table representing Facebook analytics data (just an example) with the following columns:
day -> date
account_id -> id of the Facebook page
number_of_fans -> number of fans for a certain page at a certain date
post_comments -> number of comments on a given Page at a certain date

Now I would like to compute *simultaneously* the total number of comments in my table (easy, just a sum) AND the total number of fans (which means, for each day I have to sum up all the fans of the different pages and then I have to do an argMax(number_of_fans, day)).

Now this is something that we can currently do via a very hacky usage of Arrays (generating tuples, sorting them in both directions, finding ranges, and then apply arrayReduce twice. Obviously this is not going to scale very nicely and also results in quite hard-to-debug query code.

I have a few ideas in mind on how we could make this pattern (which I believe happens a lot in analytics) easier to implement:

**Describe the solution you'd like**
Idea #1: arrayGroupBy(lambda, arr) function that turns an array into an array of array - each having in common the same group key. This would still mean working with arrays but most of the hacky stuff highlighted above is gone
Idea #2: extend arrayReduce so that it is possible to provide an arbitrary reduce lambda rather than just the name of the aggregation function
Idea #3: somehow abstract away the usage of array entirely, and implement a syntax that looks like this:

``argMax(sumBy(number_of_fans, day), day)``

where the -By suffix does not return a single number, but an array of tuples, and the argMax finalizes the aggregation as needed.

I believe #1 should be low hanging enough and has probably other positive fallbacks in different use cases.

**Describe alternatives you've considered**
Aside from array hacking, it is possible to solve this by self-joining the table with itself, which is also another not-so-nice pattern.

Thanks for your consideration!

**Comment by filimonov** [comment]
While your propositions sound interesting, it looks like you can solve your task in more natural way currently

SELECT day, sum(number_of_fans), sum(post_comments)

**Comment by filimonov** [comment]
While your propositions sound interesting, it looks like you can solve your task in more natural way currently
```sql
SELECT
sum(comments), 
argMax(fans, day) 
FROM
(
SELECT
day, 
sum(number_of_fans) AS fans, sum(post_comments) AS comments
FROM table
GROUP BY day
) 
```

**Comment by andrea-s** [comment]
Thank you for your kind response @filimonov!

It it true that in this (somewhat simplified) version of the problem one could use a subquery like this - but doing as you suggest will "pre-rollup" the data, preventing metrics that depend on the "account_id" field to be calculated. Examples of such metrics:

number_of_pages -> uniq(account_id)
comments_in_a_subset_of_pages -> sumIf(comments, account_id in (...))

Thank you for pointing this out, this is much closer to the actual situation we are dealing with.

**Comment by helloIAmPau** [comment]
Any update on this? The `arrayGroupBy` proposal by @andrea-s sounds very interesting to me and could be a perfect solution for a couple of use cases I'm currently working on.

**Comment by UnamedRus** [comment]
arrayGroupBy is implemented by -Map combinator in https://github.com/ClickHouse/ClickHouse/pull/24539, starting from 21.12

**Comment by alexey-milovidov** [comment]
@UnamedRus But the quality of implementation is in question.
