### ISSUE TITLE
Replace table statement is not working as expected

### ISSUE THREAD

**Issue by owenzhw** [ClickHouse/ClickHouse#49339]
**Describe the unexpected behaviour**

I'm using replace table statement. The SQL is like this:
`create or replace table test_table
(
    Id UInt64
) ENGINE = MergeTree()
    Order By Id
`

And it failed with error code:
`Code: 1. DB::Exception: System call renameat2() is not supported. (UNSUPPORTED_METHOD) (version 22.11.6.44 (official build)) , server ClickHouseNode [uri=http://localhost:8123/default, options={custom_http_params=session_id=DataGrip_d6184e4f-7043-4e47-90ea-9ba033a901d1}]@-886638798`

I'm using official docker image [clickhouse/clickhouse-server:22.11.6]. Anyone could help?

**How to reproduce**

Run this SQL twice：
`create or replace table test_table
(
    Id UInt64
) ENGINE = MergeTree()
    Order By Id
`
* Which ClickHouse server version to use
22.11.6
using official docker image

**Expected behavior**

SQL can‘t be executed with error code.

**Error message and/or stacktrace**

`Code: 1. DB::Exception: System call renameat2() is not supported. (UNSUPPORTED_METHOD) (version 22.11.6.44 (official build)) , server ClickHouseNode [uri=http://localhost:8123/default, options={custom_http_params=session_id=DataGrip_d6184e4f-7043-4e47-90ea-9ba033a901d1}]@-886638798`

**Comment by alexey-milovidov** [comment]
REPLACE and EXCHANGE tables are supported only on the operating systems with the atomic file exchange operation.
Linux is supported, but not Windows or Mac.

**Comment by Hubbitus** [comment]
That [is not supported on NFS file system for example too](https://news.ycombinator.com/item?id=9856180).

@alexey-milovidov, it strange to see what **some of instructions does not work on some situations**, is not?
Like `EXCHANGE TABLES ...` may be failed suddenly.
Can it be re-implemented in more safe manner?

**Comment by alexey-milovidov** [comment]
@Hubbitus, it cannot be easily reimplemented without the support for atomic `renameat2`.

**Comment by Hubbitus** [comment]
Is not [qemu patch](https://qemu-devel.nongnu.narkive.com/XPwbYDO2/patch-linux-user-implement-renameat2-when-defined) helpful to emulate call with `rename` when `renameat2` is not supported?

**Comment by Algunenano** [comment]
> REPLACE and EXCHANGE tables are supported only on the operating systems with the atomic file exchange operation.
Linux is supported, but not Windows or Mac.

Mac is also supported if the host supports `renamex_np` with `RENAME_SWAP`)-> https://github.com/ClickHouse/ClickHouse/pull/36133

**Comment by alexey-milovidov** [comment]
@Hubbitus it does not look like this patch emulates it with `rename`, moreover, it sounds impossible.

**Comment by yzq1314** [comment]
Hi, I would like to ask if there is a solution to this problem? I'm currently experiencing the same issue, using storage persistence in kubernetes containers it reports System call renameat2() is not supported.
