### ISSUE TITLE
HTTPS: toJSONString produced invalid JSON when single quote present in String

### ISSUE THREAD

**Issue by BenoitRanque** [ClickHouse/ClickHouse#49348]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
The `toJSONString` function may produce invalid JSON strings if underlying String columns include single quotes.

**How to reproduce**
* Which ClickHouse server version to use
Observed in 23.3
* Interface
https
* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE test (
  id Int64,
  name String
)
ORDER BY id;
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
```sql
INSERT INTO test(id, name) VALUES (1, 'O''reilly');
```
* Queries to run that lead to unexpected result
Run this request over https:
```sql
SELECT toJSONString(name) FROM test;
```
Result:
```json
"O\'reilly"
```
*Note*: In the web console, the result will apear as `"O'reilly"`, it seems to not be affected by this issue. Also note this behavior also happens when serializing more complex structures such as tupples or arrays, that in turn have string fields.
**Expected behavior**
`toJSONString` should produce valid JSON strings.
The [JSON spec](https://www.rfc-editor.org/rfc/rfc8259#section-7) does not allow escaped single quotes in strings.

**Comment by alexey-milovidov** [comment]
It is output according to the data format you choose:

```
milovidov-desktop :) SELECT toJSONString('O''reilly')

SELECT toJSONString('O\'reilly')

Query id: 6e61edc7-ba53-41bc-a5a7-2e0af684af40

┌─toJSONString('O\'reilly')─┐
│ "O'reilly"                │
└───────────────────────────┘

1 row in set. Elapsed: 0.002 sec. 

milovidov-desktop :) SELECT toJSONString('O''reilly') FORMAT TSV

SELECT toJSONString('O\'reilly')
FORMAT TSV

Query id: 441e82b0-77c7-45c5-b37a-34c94514de0c

"O\'reilly"

1 row in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SELECT toJSONString('O''reilly') FORMAT CSV

SELECT toJSONString('O\'reilly')
FORMAT CSV

Query id: 785fec57-302d-45ad-b178-e8f174221853

"""O'reilly"""

1 row in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SELECT toJSONString('O''reilly') FORMAT JSON

SELECT toJSONString('O\'reilly')
FORMAT JSON

Query id: 5ad57ec7-5de9-4f5b-94b3-ef2b54013475

{
        "meta":
        [
                {
                        "name": "toJSONString('O\\'reilly')",
                        "type": "String"
                }
        ],

        "data":
        [
                {
                        "toJSONString('O\\'reilly')": "\"O'reilly\""
                }                                                                                                                                                                                                             
        ],

        "rows": 1,

        "statistics":
        {
                "elapsed": 0.001053071,
                "rows_read": 1,
                "bytes_read": 1
        }
}

1 row in set. Elapsed: 0.001 sec.
```

When the data format is unspecified in the HTTP interface, it uses the TSV format.

**Comment by alexey-milovidov** [comment]
The `toJSONString` string returns an opaque value of type String (that contains a valid JSON).
Then (regardless of the contents of the string), the string can be formatted according to any of the supported formats, as TSV, CSV, Parquet, etc.

For example, if you output it in the JSON format, you will get JSON inside a string inside JSON:
```
"\"O'reilly\""
```
