### ISSUE TITLE
ORDER BY clause after ANY LEFT JOIN changes the selected row from the  ANY LEFT JOIN

### ISSUE THREAD

**Issue by AviSarmani** [ClickHouse/ClickHouse#49346]
Hi,
We're using ANY LEFT JOIN under the assumption that ANY LEFT JOIN takes the first record that matches the criteria in the left table and adding an order by clause on the main table changes the row selected.
Using fiddler we see that the change started in version 23. Is it the intended result?

**How to reproduce**

CH version: 23.3.1.2823
```
CREATE TABLE id_val(`id` UInt32) ENGINE = TinyLog;
INSERT INTO id_val VALUES (1);

CREATE TABLE id_val_join(`id` UInt32, `val` UInt32) ENGINE = TinyLog;
INSERT INTO id_val_join VALUES (1,10)(1,20);
```
We want to fetch the record from id_val with the first matching row in a descending order(in this case, 20)
(https://fiddle.clickhouse.com/8f61f210-c7f9-42e9-8fae-1700545a1622)

```
SELECT
	id_val.id,
	left_join.val
FROM
	id_val ANY LEFT JOIN (
				SELECT
					*
				FROM
					id_val_join
				ORDER BY
					val desc
) AS left_join ON
	id_val.id = left_join.id
```
and it works correctly.
The problem is that when we add an order by to the outer select clause, it changes the selection of the left any join.
```
SELECT
	id_val.id,
	left_join.val
FROM
	id_val ANY LEFT JOIN (
				SELECT
					*
				FROM
					id_val_join
				ORDER BY
					val desc
                                 ) AS left_join ON
	id_val.id = left_join.id
ORDER BY id_val.id asc
```
(https://fiddle.clickhouse.com/391c71c2-2432-40fd-9b16-cb2c7889ec21)
In this way we get 10 although we only changed the order by on the outer join

Any insights would be appreciated
Best Regards, 
Avi

**Comment by den-crane** [comment]
ANY LEFT JOIN takes first of any record. Not the first record.

New optimization removes excessive ORDER BY (it does not change the result).

You can hack the optimizer by LIMIT trick

```
SELECT
	id_val.id,
	left_join.val
FROM
	id_val ANY LEFT JOIN (
				SELECT
					*
				FROM
					id_val_join
				ORDER BY
					val desc
                limit 10000000000000 -------<<<<<---
                                 ) AS left_join ON
	id_val.id = left_join.id
ORDER BY id_val.id asc
---
1	20
```

https://fiddle.clickhouse.com/648c485e-7c4b-4a6d-9ef9-c46da36b2b20

**Comment by den-crane** [comment]
And also you can use `limit 1 by`

```sql
SELECT
	id_val.id,
	left_join.val
FROM
	id_val ANY LEFT JOIN (
				SELECT
					*
				FROM
					id_val_join
				ORDER BY
					val desc
                LIMIT 1 by id    -------<<<<<---
) AS left_join ON
	id_val.id = left_join.id
ORDER BY id_val.id asc
---
1	20
```

https://fiddle.clickhouse.com/3925d984-3277-443b-97e4-bcbfdb245f4d

**Comment by AviSarmani** [comment]
Thank you @den-crane for the clarification.
I used argmax so that the internal table has only one record for each id and it fixes the issue.
(https://fiddle.clickhouse.com/71494f07-c1e8-4cfa-91a5-56343289a610)
Have a great day.
