### ISSUE TITLE
DB::Exception: Unknown codec family: 1Z4. (UNKNOWN_CODEC)

### ISSUE THREAD

**Issue by Meppo** [ClickHouse/ClickHouse#49340]
> You have to provide the following information w
**Describe what's wrong**

clickhouse version: ` (version 22.9.3.18 (official build))`

I have ReplicatedAggregatingMergeTree table `total` with 6 billion records,  I do the query `optimize table total final`  to deduplicate data , it's not working, check the log:

the /var/log/clickhouse-server/clickhouse-server.err.log in all replicated machine print the same message:

`
 [ 13709 ] {} <Error> 8f236d40-3c65-4ae4-9f40-12b8b97aafe6::all_112156_705953_18 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 432. DB::Exception: Unknown codec family: 1Z4. (UNKNOWN_CODEC), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../src/Common/Exception.cpp:69: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x78d627a in /usr/lib/debug/usr/bin/clickhouse.debug
1. ./build_docker/../src/Compression/CompressionFactory.cpp:0: DB::CompressionCodecFactory::getImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IAST> const&, DB::IDataType const*) const @ 0x1132f423 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/../contrib/libcxx/include/__utility/swap.h:37: DB::CompressionCodecFactory::get(std::__1::shared_ptr<DB::IAST> const&, DB::IDataType const*, std::__1::shared_ptr<DB::ICompressionCodec>, bool) const @ 0x1132db52 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/../src/Compression/CompressionFactory.cpp:0: DB::CompressionCodecFactory::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::optional<int>) const @ 0x1132d3d8 in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/../contrib/libcxx/include/__utility/swap.h:37: DB::Context::chooseCompressionCodec(unsigned long, double) const @ 0x11a21e31 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/../src/Storages/MergeTree/MergeTreeData.cpp:0: DB::MergeTreeData::getCompressionCodecForPart(unsigned long, DB::MergeTreeDataPartTTLInfos const&, long) const @ 0x12afde35 in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/../src/Storages/MergeTree/MergeTask.cpp:0: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() @ 0x12a828cd in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/../contrib/libcxx/include/__functional/function.h:711: bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()> >(std::__1::__function::__policy_storage const*) @ 0x12a92209 in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/../contrib/libcxx/include/__functional/function.h:843: DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x12a88b6b in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/../src/Storages/MergeTree/MergeTask.cpp:0: DB::MergeTask::execute() @ 0x12a8e97a in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:0: DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x12c95ee4 in /usr/lib/debug/usr/bin/clickhouse.debug
11. ./build_docker/../src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:0: DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x12c95142 in /usr/lib/debug/usr/bin/clickhouse.debug
12. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:157: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x78ad80b in /usr/lib/debug/usr/bin/clickhouse.debug
13. ./build_docker/../src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:0: DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0x78ad250 in /usr/lib/debug/usr/bin/clickhouse.debug
14. ./build_docker/../base/base/../base/wide_integer_impl.h:772: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::worker(std::__1::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x797c1ec in /usr/lib/debug/usr/bin/clickhouse.debug
15. ./build_docker/../src/Common/ThreadPool.cpp:0: void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false> >::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x797ef17 in /usr/lib/debug/usr/bin/clickhouse.debug
16. ./build_docker/../base/base/../base/wide_integer_impl.h:772: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x797872c in /usr/lib/debug/usr/bin/clickhouse.debug
17. ./build_docker/../contrib/libcxx/include/__memory/unique_ptr.h:312: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>, bool)::'lambda0'()> >(void*) @ 0x797de3e in /usr/lib/debug/usr/bin/clickhouse.debug
18. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
19. __clone @ 0xfe8dd in /usr/lib64/libc-2.17.so
 (version 22.9.3.18 (official build))
`

total schema like this:
```sql
CREATE TABLE IF NOT EXISTS total(
    mac String,
    name AggregateFunction(argMaxIf,String,DateTime,Bool),
    f_time AggregateFunction(min,Int64),
    l_time AggregateFunction(max, Int64),    
    online AggregateFunction(argMaxIf,Bool,DateTime,Bool),
    ht_count AggregateFunction(sumIf, UInt64, Bool),
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
ORDER BY (mac);
```

compression config
```xml
    <compression>
        <case>
            <min_part_size>10000000000</min_part_size>
            <min_part_size_ratio>0.01</min_part_size_ratio>
            <method>1z4</method>
        </case>
    </compression>
```

now I  don't know  how to fix this error. help...

**Comment by Meppo** [comment]
error compression config

**Comment by smallLian** [comment]
> error compression config

@Meppo Is this problem caused by compression configuration error?  What is the correct compression configuration?
