### ISSUE TITLE
Default logging level is very verbose, why?

### ISSUE THREAD

**Issue by sephii** [ClickHouse/ClickHouse#49357]
Is there a reason why the log level in the default configuration file is set to `trace`? This doesn’t really look like a useful value for a production deployment (keeping this log level will quickly use a lot of disk space). In the version of ClickHouse packaged for Nix, we’re considering setting the default level to `info` or `warning` (see the [related PR](https://github.com/NixOS/nixpkgs/pull/190933)).

However, changing this upstream would be preferable.

PS: the Slack invite link in the GitHub question template is not valid anymore.

**Comment by den-crane** [comment]
see https://github.com/ClickHouse/ClickHouse/pull/48452#issuecomment-1506986107
