### ISSUE TITLE
DB::CacheMetadata::doCleanup() Logical error: 'false'.

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#49386]
Stress test failure: https://s3.amazonaws.com/clickhouse-test-reports/49365/0f6a4b973e0029f6c400385891077378aa2f0787/stress_test__tsan_.html

**Comment by kssenii** [comment]
will wait for next failure after https://github.com/ClickHouse/ClickHouse/pull/49387

**Comment by tavplubix** [comment]
Next failure: https://s3.amazonaws.com/clickhouse-test-reports/0/b414760d4387ce9a99920fe80b2b8fc2a58f1b66/stress_test__debug_.html
