### ISSUE TITLE
What's the plan/road map for the zero copy feature?

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#49383]
For S3 backend merge tree, zero copy improves the replication performance drastically. 
On our cluster, we observed that the duration of DownloadParts averagely took 200ms to complete with zero copy while it took more than 7 seconds to complete without zero copy. The slow replication process slows down the merge which at last causes TOO MANY PARTS problem.

This feature is still marked as experimental and the it's turned off by default since 22.8. 
Even though we noticed that a lots of zero copy related issues have been fixed since last year, but it's not clear that when this feature is going to be ready or will it be supported or deprecated at last?

So my question is:
1. what's the plan to bring it as a production ready feature?
2. If zero copy is not recommended to use, what can we do to improve the FETCH performance?

**Comment by alexey-milovidov** [comment]
Zero-copy replication is a poorly designed feature; it barely works. We don't expect it will be ready for production usage.

**Comment by FrankChen021** [comment]
I'm wondering what's your plan on this feature? deprecate it or improve it? 
If it's going to be deprecated, I think our team will come up with another solution on the replication performance.

**Comment by alexey-milovidov** [comment]
It will be left in an experimental stage for a long time, maybe several years.

**Comment by ringerc** [comment]
Any chance of elaborating on what's wrong with it or some references to concrete issues? I'm wondering if it's fundamentally unfixable or if improvements are possible.
