### ISSUE TITLE
Flaky test `test_ssl_cert_authentication`

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#49400]
https://s3.amazonaws.com/clickhouse-test-reports/0/0f6a81843fa2b5b86b8a7ac238d18b9fcdf5c657/integration_tests__release__[4_4].html

**Comment by tavplubix** [comment]
Still flaky
https://s3.amazonaws.com/clickhouse-test-reports/50392/2357c033889484abe86d0890d89097a101b386a1/integration_tests__release__[4_4].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/50487/42393b51ee1747e838c71196a29eb305fca6257c/integration_tests__asan__[6_6].html

**Comment by KochetovNicolai** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/52151/ec21230c42caa69e9c25cee6bf070eab2b74f4be/integration_tests__release__[4_4].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/c6e6fd761317662c05532d695c20be72f8e847d2/integration_tests__release__[4_4].html

**Comment by kssenii** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/53124/5382442da0dbf4fd7060943d3c074b0fecf8e0e1/integration_tests__release__[4_4].html
