### ISSUE TITLE
Flaky test `test_keeper_snapshots_multinode/test.py::test_restart_multinode`

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#49446]
https://s3.amazonaws.com/clickhouse-test-reports/49211/a08225d9ea4d0ca6ddf665a1b5b7fc69b2147137/integration_tests__tsan__[5_6].html

**Comment by antonio2368** [comment]
Should be fixed by https://github.com/ClickHouse/ClickHouse/pull/52358
