### ISSUE TITLE
Illegal instruction     (core dumped)

### ISSUE THREAD

**Issue by 314926481** [ClickHouse/ClickHouse#49487]
My system includes the following content
uname -a
Linux ecs-uos1050e.novalocal 4.19.90-2201.4.0.0135.up1.uel20.aarch64 #1 SMP Mon Feb 21 18:36:06 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

I am executing yum -y localinstall clickhouse-server-23.4.2.11.aarch64.rpm city and reported the following error：

/var/tmp/rpm-tmp.ox7hqU: line 57: 346616 Illegal instruction     (core dumped) ${CLICKHOUSE_GENERIC_PROGRAM} install --user "${CLICKHOUSE_USER}" --group "${CLICKHOUSE_GROUP}" --pid-path "${CLICKHOUSE_PIDDIR}" --config-path "${CLICKHOUSE_CONFDIR}" --binary-path "${CLICKHOUSE_BINDIR}" --log-path "${CLICKHOUSE_LOGDIR}" --data-path "${CLICKHOUSE_DATADIR}"
warning: %post(clickhouse-server-0:23.4.2.11-1.aarch64) scriptlet failed, exit status 132

Error in POSTIN scriptlet in rpm package clickhouse-server
  Verifying: clickhouse-server-23.4.2.11-1.aarch64 

Installed:
  clickhouse-server-23.4.2.11-1.aarch64

Complete!

The above is my error message, requesting help

**Comment by alexey-milovidov** [comment]
Install ClickHouse as follows:

```
curl https://clickhouse.com/ | sh
```

It will automatically select the proper AArch64 variant.
