### ISSUE TITLE
neighbor function issue with nested queries

### ISSUE THREAD

**Issue by kmehl** [ClickHouse/ClickHouse#49494]
Hello, 

I noticed a bug with neighbor function when I use it in nested queries.

in this simple query, I would like to get the **previous** number for every number: 
```
SELECT number, neighbor(number, -1) as previous 
FROM numbers(5)
ORDER BY number ASC
```

so I got:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/11167844/236172663-3095f8e7-ab04-4715-8cc4-cb44c05a4050.png">

It Ok, as the previous number of 3 is 2.

But when I nested the query so that I can reverse order by number decreasing:
```
SELECT *
FROM (
  SELECT number, neighbor(number, -1) as previous 
  FROM numbers(5)
  ORDER BY number ASC
)
ORDER BY number DESC
```

I got:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/11167844/236173009-14ed409c-b47a-4ce2-83c6-d56944140542.png">

As you can see the previous number of 3 is now 4!

It seems like neighbor is not computed in it current SELECT, but that of the highest level.

**Comment by UnamedRus** [comment]
Use lagInFrame, leadInFrame functions instead, `neighbor` is not consistent function in it's behavior

**Comment by den-crane** [comment]
ClickHouse release 22.4, 2022-04-19

A new query plan optimization. Evaluate functions after ORDER BY when possible. As an example, for a query SELECT sipHash64(number) FROM numbers(1e8) ORDER BY number LIMIT 5, function sipHash64 would be evaluated after ORDER BY and LIMIT, which gives ~20x speed up. [#35623](https://github.com/ClickHouse/ClickHouse/pull/35623) ([Nikita Taranov](https://github.com/nickitat)).

**Comment by den-crane** [comment]
hack

```sql
SELECT *
FROM (
  SELECT number, neighbor(number, -1) as previous 
  FROM numbers(5)
  ORDER BY number ASC
)
WHERE previous > -10000
ORDER BY number DESC
┌─number─┬─previous─┐
│      4 │        3 │
│      3 │        2 │
│      2 │        1 │
│      1 │        0 │
│      0 │        0 │
└────────┴──────────┘
```

**Comment by den-crane** [comment]
cc @nickitat

**Comment by nickitat** [comment]
thx, I'll take a look

**Comment by nem0-z** [comment]
> hack
> 
> ```sql
> SELECT *
> FROM (
>   SELECT number, neighbor(number, -1) as previous 
>   FROM numbers(5)
>   ORDER BY number ASC
> )
> WHERE previous > -100000000
> ORDER BY number DESC
> ┌─number─┬─previous─┐
> │      4 │        3 │
> │      3 │        2 │
> │      2 │        1 │
> │      1 │        0 │
> │      0 │        0 │
> └────────┴──────────┘
> ```

Would you mind explaining how exactly this "hack" works? I tried applying similar logic to a more complex query and I am still having the same issue as OP.

**Comment by den-crane** [comment]
@nem0-z when I used `previous` (`neighbor(number, -1)`) is in the filter I forbade to move neighbor function to the later stage of the pipeline.

In fact it's better use this form

```sql
SELECT *
FROM (
  SELECT number, neighbor(number, -1) as previous 
  FROM (select * from numbers(5)   ORDER BY number ASC)
  WHERE previous > -100000000
  limit 10000000000
)
ORDER BY number DESC
┌─number─┬─previous─┐
│      4 │        3 │
│      3 │        2 │
│      2 │        1 │
│      1 │        0 │
│      0 │        0 │
└────────┴──────────┘
```
