### ISSUE TITLE
Support compression for Keeper protocol

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#49507]
[Zoo]Keeper Client and [Zoo]Keeper server communicate using custom TCP protocol: https://github.com/ClickHouse/ClickHouse/blob/27f9384717ba12f99a5fca74021edbacee4d3fc0/src/Common/ZooKeeper/ZooKeeperImpl.cpp#L57-L265.
ZooKeeper has quite strict (but configurable) limitations on request/response size but for Keeper we don't have them. For large multi-requests and big responses (for example `getChildren` response) we can have big advantages from compression, because both requests and responses should compress well.

We already support compression in client-server TCP protocol: https://github.com/ClickHouse/clickhouse-private/blob/c496ff8dc14f1a5f115c257e96c9b1d16e628e32/src/Server/TCPHandler.cpp#L1745-L1748. And in client-server HTTP protocol: https://github.com/ClickHouse/clickhouse-private/blob/c496ff8dc14f1a5f115c257e96c9b1d16e628e32/src/Server/HTTPHandler.cpp#L575-L581. 

The same technique can be applied -- wrap our TCP socket with compressed buffer on both sides:
1) Server: https://github.com/ClickHouse/ClickHouse/blob/27f9384717ba12f99a5fca74021edbacee4d3fc0/src/Server/KeeperTCPHandler.cpp#L309-L310
2) Client: https://github.com/ClickHouse/ClickHouse/blob/27f9384717ba12f99a5fca74021edbacee4d3fc0/src/Common/ZooKeeper/ZooKeeperImpl.cpp#L412-L413

To determine do we need to use compression or not, user can specify special tag in client's configuration: https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/zookeeper.xml#LL1C1-L10C1, like `<compressed_protocol>true</compressed_protocol>`. I think the best way for Keeper Client to tell Server about compression is protocol version constant https://github.com/ClickHouse/ClickHouse/blob/27f9384717ba12f99a5fca74021edbacee4d3fc0/src/Common/ZooKeeper/ZooKeeperConstants.h#L47. If client configured to use compression, tried to send `ZOOKEEPER_PROTOCOL_VERSION_WITH_COMPRESSION` (1) but received an exception it should just retry without compression.

cc @antonio2368, @alexey-milovidov

**Comment by zhanglistar** [comment]
@alesapin What't the performance of keeper comparing with apache zookeeper?

**Comment by helifu** [comment]
Seems only one single thread processes the requests, so there is no chance of a big performance improvement, am I right?

Here is the code:
https://github.com/ClickHouse/ClickHouse/blob/bb2acb50d2d65226e5ceb51d0d83a70f4283ce60/src/Coordination/KeeperDispatcher.cpp#LL188C40-L188C40
