### ISSUE TITLE
Failed `01605_dictinct_two_level`

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#49502]
`01605_dictinct_two_level` [doesn't seem to be flaky](https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyUwMTYwNV9kaWN0aW5jdF90d29fbGV2ZWwlJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==) but failed at https://s3.amazonaws.com/clickhouse-test-reports/49093/ef9c3a3ca13b0d785536668cc9f2daedb7b2112c/stateless_tests__release__wide_parts_enabled_.html

https://github.com/ClickHouse/ClickHouse/issues/49093#issuecomment-1534642493

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/51866/fe356f2f8af02ac114d3dca8bc56916be45bf38c/stateless_tests__release__wide_parts_enabled_.html

**Comment by alexey-milovidov** [comment]
No recent failures. I only found a few group failures with other tests a long time ago.
