### ISSUE TITLE
MySQL compatibility: mixed case queries

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/ClickHouse#49510]
**Use case**

When using MySQL protocol to connect BI tools (for example, QuickSight) to ClickHouse, the following query is executed to introspect the dataset size, and it fails:

```sql
SELECT 
  data_length 
FROM 
  information_schema.TABLES 
WHERE 
  table_schema = 'default' 
  AND table_name = 'cell_towers';
```

**Describe the solution you'd like**

Mixed case `<database>.<TABLE>` (or maybe even `<DATABASE>.<table>`) works.

**Additional context**

An example log of a failing query:

```
2023.04.25 13:26:44.562738 [ 319 ] {mysql:96:11ad169d-0139-456a-abc7-e9fdfae004f6} <Error> executeQuery: Code: 60. DB::Exception: Table information_schema.TABLES doesn't exist. (UNKNOWN_TABLE) (version 23.4.1.1157 (official build)) (from 35.158.127.201:43000) (in query: SELECT data_length FROM information_schema.TABLES WHERE table_schema = 'default' AND table_name = 'cell_towers')
```

**Comment by mshustov** [comment]
should be closed by https://github.com/ClickHouse/ClickHouse/pull/50961
