### ISSUE TITLE
FR: aggregate UDF state de/serialization

### ISSUE THREAD

**Issue by myrrc** [ClickHouse/ClickHouse#49514]
**Use case**

Using UDF in an AggregatingMergeTree.

**Proposed solution (short)**

1. API to de\serialize state of a (possibly compound) UDF like `(x, y) -> sum(x) / sum(y)` as functions `[de]serializeStoredProcedureState`.
2. Changes to AggregatingMergeTree that would use (1) and allow storing UDFs as fields in itself.

**Proposed solution (long)**

The issue has initially arisen while looking at avgWeighted bugs https://github.com/ClickHouse/ClickHouse/issues/43928 and
https://github.com/ClickHouse/ClickHouse/issues/31768

avgWeighted can be trivially implemented as a UDF (~not a [U]DF, so I'll call these entities _stored procedures_) and that would remove the burden of maintaining complex invariants. However, many users have this function as a field in AggregatingMergeTree, so they need a migration plan. I propose

1. Changing UDF `src/Functions/UserDefined` to `src/Functions/StoredProcedures` and splitting the storage to a user-defined storage and system-defined storage (for example, avgWeighted implementation as `CREATE FUNCTION avgWeighted AS (x, w) -> toFloat64(sum(x * w) / sum(w))` would go to system-defined storage).
2. Changing `CREATE FUNCTION` interpreter to determine whether supplied function is aggregate (~it contains at least one aggregate function in its body), if aggregate, creating a deterministic state containing a product type of states of each contained aggregate function). Such state should be stored as a contiguous memory region.
3. Changing query execution pipeline. While executing an aggregate function part of the stored procedure, this function part should be supplied a correct `AggregateDataPtr` pointing to stored procedure state part.
4. Adding API to de[serialize] stored procedures. 

**Additional context**

Related discussion: https://github.com/ClickHouse/ClickHouse/pull/48615

**Comment by UnamedRus** [comment]
> API to de\serialize state of a (possibly compound) UDF like (x, y) -> sum(x) / sum(y) as functions [de]serializeStoredProcedureState.

It sounds for me like UDAF support?

https://www.postgresql.org/docs/current/sql-createaggregate.html
Basically, it contain 2 functions underneath:

SFUNC - aggState/aggMergeState in ClickHouse
FINALFUNC - aggMerge in ClickHouse

```
CREATE AGGREGATE average(numeric) (
  sfunc     = Tuple(count UInt32, sum UInt32),
  stype     = userAvgState,
  finalfunc = userAvgMerge,
  initcond  = (0,0)
);
```

**Comment by myrrc** [comment]
Yes, if implemented, it would add aggregate support. My suggestion is just to make the "aggregate-ness" of the function transparent to user for ease of use.

**Comment by UnamedRus** [comment]
I think, main usecase of UDAF, when people want to have something specific, which can't be solved by simple sum/sum (or any other combination of normal agg function results)
