### ISSUE TITLE
If a dictionary is created with a complex key, automatically choose the "complex key" layout variant.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#49523]

**Comment by xbthink** [comment]
It is my first time to contribute to open source project, I have created a pr #49587 .
Can you @alexey-milovidov  assign to me? and if there are some other requirements about contributing, please let me know. Thanks

**Comment by alexey-milovidov** [comment]
Thank you! Now the remaining parts are - checking review comments and finishing the tests.

**Comment by xbthink** [comment]
Thank you for your reply, I got it.
