### ISSUE TITLE
Is there any roadmap for secondary index

### ISSUE THREAD

**Issue by fancyqlx** [ClickHouse/ClickHouse#49535]
Hi, i found there is some secondary indexes for clickhouse, such as min-max, bloom, set, inverted index. I wonder to know is there any roadmap about what kinds of secondary index we will support further?

**Comment by alexey-milovidov** [comment]
The nearest thing is to evaluate and test full-text indices.

**Comment by melvynator** [comment]
There are a few things we are going to work on in 2024:

- Vector search, and consolidation of the ANN index: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/annindexes (where the Usearch index will be repurposed)
- Full-text indices GA: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/invertedindexes
