### ISSUE TITLE
Dictionary can not support LowCardinality ?

### ISSUE THREAD

**Issue by EvanLai0819** [ClickHouse/ClickHouse#49532]
Hi Team,

When I try to create dictionary with LowCardinality and return below error, do you have any idea ?

My clickhouse version is 22.3.17.13-stable

`SQL Error [50][07000]: Code: 50.DB::Exception: Unknown type LowCardinality(String) for dictionary attribute.`

**Comment by den-crane** [comment]
Cannot.

Duplicate https://github.com/ClickHouse/ClickHouse/issues/11764
