### ISSUE TITLE
<Fatal> Application: Child process was terminated by signal 11. Without any other logs

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#49546]
https://s3.amazonaws.com/clickhouse-test-reports/49534/179eddee01c7318cdf5679aeefb1fd58b93e8476/stateless_tests__release__databasereplicated__[2_4].html

Triggered in this PR https://github.com/ClickHouse/ClickHouse/pull/49534

Test that failed first 01683_text_log_deadlock, but most likely it had other reason

**Comment by OPieNa** [comment]
We have same encounter, only found: Application: Child process was terminated by signal 11.
version: 22.8.10.29 (official build).

**Comment by cosen-wu** [comment]
We have also same encounter. version: 23.8.9.54-lts

**Comment by Algunenano** [comment]
Signal 11 doesn't mean anything beyond a segfault. It can't be debugged without traces, logs, reproducer... Closing this since it can't be investigated.
