### ISSUE TITLE
PROJECTION_NOT_USED error when upgrading version ClickHouse to 23.3.2.37

### ISSUE THREAD

**Issue by dolgovnv** [ClickHouse/ClickHouse#49542]
There was a problem with projections when updating version ClickHouse to 23.3.2.37.

In version 22.8.4.7, this code works:
```
create table t (
  area LowCardinality(String), 
  codeEvent UInt16, 
  timestamp DateTime64, 
  mnemonic LowCardinality(String) default '', 
  queueBasicName LowCardinality(String) default '', 
  isActive UInt8 default 0, 
  PROJECTION projection_by_ts (
    select 
      area, 
      codeEvent, 
      queueBasicName, 
      mnemonic, 
      timestamp, 
      isActive 
    order by 
      timestamp, 
      mnemonic, 
      queueBasicName
  )
) engine = MergeTree partition by toStartOfMonth(timestamp) 
order by 
  (
    mnemonic, queueBasicName, timestamp
  );
insert into t (
  area, codeEvent, timestamp, mnemonic, 
  queueBasicName, isActive
) 
values 
  ('test', 1, now(), 'mn', 'q1', 1);
select 
  queueBasicName, 
  area, 
  mnemonic 
from 
  t prewhere timestamp < now() + 1 
  and timestamp >= (now() - INTERVAL 1 hour) 
where 
  isActive = 1 
group by 
  queueBasicName, 
  area, 
  mnemonic settings force_optimize_projection = 1;

```

https://fiddle.clickhouse.com/d0ab83bb-4d84-4c54-8135-24aed8061078

In version 23.3.2.37, it fails with the following error:

> Received exception from server (version 23.3.2):
Code: 584. DB::Exception: Received from localhost:9000. DB::Exception: No projection is used when allow_experimental_projection_optimization = 1 and force_optimize_projection = 1. (PROJECTION_NOT_USED)

https://fiddle.clickhouse.com/12443feb-5cd4-4d8b-ae45-023b54a66169

**Comment by den-crane** [comment]
@dolgovnv Why the projection should be used here? I think correct behaviour to do not use the projection here.
