### ISSUE TITLE
Quantifying column monotonicity

### ISSUE THREAD

**Issue by kcajf** [ClickHouse/ClickHouse#49543]
Sometimes, I have some columns that I suspect are locally quite monotonic and would benefit from e.g. a `minmax` data-skipping index.

I suppose what I would like to do is perform some GROUP BYs on the index granules, for example count the proportion of times that `(first == min) AND (last == max) GROUP BY index_granule`. Is there a way to do this?

**Comment by al13n321** [comment]
There's no (easy) way to inspect the granules right now. It would probably make sense to add index granule index as a virtual column, similar to `_part` virtual column.

It can be approximated by counting rows:
```
:) create temporary table t (k Int64, v Int64) engine = MergeTree order by k
:) insert into t select number, number*100 + rand64() % 1000 from numbers(10000000)

:) select countIf(min = first and max = last)/count() from (select min(v) as min, max(v) as max, argMin(v, row_idx) as first, argMax(v, row_idx) as last from t group by _part, intDiv(rowNumberInAllBlocks() as row_idx, 8192))

SELECT countIf((min = first) AND (max = last)) / count()
FROM
(
    SELECT
        min(v) AS min,
        max(v) AS max,
        argMin(v, row_idx) AS first,
        argMax(v, row_idx) AS last
    FROM t
    GROUP BY
        _part,
        intDiv(rowNumberInAllBlocks() AS row_idx, 8192)
)

Query id: 204c2450-41ae-4996-b96c-1c3a95ed105c

┌─divide(countIf(and(equals(min, first), equals(max, last))), count())─┐
│                                                   0.1875968992248062 │
└──────────────────────────────────────────────────────────────────────┘
```

---

Not sure how good `min = first and max = last` is as a measure of sortedness. I guess what we're actually interested in is how much the granules' [min, max] ranges overlap with each other. I can't think of an efficient way to calculate it within clickhouse. An inefficient way is to use FULL OUTER JOIN to look at all pairs of granules:
```
:) create temporary table granules (part LowCardinality(String), min Int64, max Int64)
:) insert into granules select _part, min(v), max(v) from t group by _part, intDiv(rowNumberInAllBlocks() as row_idx, 8192)

:) select count() from granules
┌─count()─┐
│    1288 │
└─────────┘

:) select count() as pairs, countIf(a.max >= b.min and a.min <= b.max)/count() as overlaps from granules a full outer join granules b on a.part = b.part
┌──pairs─┬────────────overlaps─┐
│ 693032 │ 0.03227556591903404 │
└────────┴─────────────────────┘
```

This takes O(number_of_granules ^ 2) memory, so it'll work up to maybe tens of thousands of granules, which is hundreds of millions of rows in the original table.

**Comment by al13n321** [comment]
Another idea for a measure of monotonicity: count neighboring granules with overlapping [min, max] ranges. This can be done efficiently using `neighbor` function: https://clickhouse.com/docs/en/sql-reference/functions/other-functions#neighbor
