### ISSUE TITLE
Mysql field type decimal convert to String

### ISSUE THREAD

**Issue by samz406** [ClickHouse/ClickHouse#4954]
hello! I use command ,extract data from Mysql.
`CREATE table sales_fact_sample_flat_1 ENGINE=MergeTree order by the_year  AS    SELECT  * FROM mysql(192.168.103.44:3306, cboard,sales_fact_sample_flat, root,admin);
`
I found a problem that  the field of  mysql decimal  convert string.

mysql
![image](https://user-images.githubusercontent.com/3055810/55865977-fdfbfe00-5bb1-11e9-98ce-b44ff0b90ece.png)

clickhouse 
![image](https://user-images.githubusercontent.com/3055810/55865952-f3416900-5bb1-11e9-8f53-290d5c79050c.png)

Is that right?

**Comment by 4ertus2** [comment]
Decimal conversion for external storages and dictionaries is not supported yet.
As workaround you may try to create Decimal ALIAS column for Strings ones with toDecimal() expression.

**Comment by samz406** [comment]
ok，I have another question. mysql can be use  
mysql(192.168.103.44:3306, cboard,sales_fact_sample_flat, root,admin),
this is convenience,  it can be  auto create table  and insert data. So i want to extract data from oracle to clckhouse,can you give me some advise? soon I want extract source data from db2, mogodb,Postgres hdfs and so on!

**Comment by 4ertus2** [comment]
There're external dictionaries https://clickhouse.yandex/docs/en/operations/table_engines/dictionary/

There're also readonly ODBC/JDBC engines. But they are still not in docs. You may configure odbc.ini and then create table with ENGINE = odbc('dsn=test', table). It uses unixodbc under the hood.

**Comment by filimonov** [comment]
Reopening that, just to have it in backlog.

**Comment by 4ertus2** [comment]
Same issue with enums #3985

**Comment by 4ertus2** [comment]
More general request #1270

**Comment by kitaisreal** [comment]
Fixed in scope of #11512.
With `mysql_datatypes_support_level` specified to `decimal`.
