### ISSUE TITLE
docker container logs to /var/log/clickhouse-server instead only to /dev/stdout

### ISSUE THREAD

**Issue by monotek** [ClickHouse/ClickHouse#49566]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

The docker container logs to /var/log/clickhouse-server instead only to /dev/stdout.

**How to reproduce**
Create a clickhouse installation with Clickhouse operator. 

Thats the output of on of the clikhouse containers right after start:
```
k -n logging logs -f chi-clickhouse-logging-replicated-1-0-0
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-hostname-ports.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-macros.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/chop-generated-zookeeper.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-01-listen.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-02-logger.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-03-query_log.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/01-clickhouse-04-part_log.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/chop-generated-remote_servers.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/chop-generated-settings.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/custom.xml'.
Logging warning to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log

```

```
k -n logging exec -it chi-clickhouse-logging-replicated-0-0-0 -- bash
clickhouse@chi-clickhouse-logging-replicated-0-0-0:/$ ls -al /var/log/clickhouse-server/
total 20
drwxrwxrwx 1 clickhouse clickhouse 4096 May  5 16:43 .
drwxr-xr-x 1 root       root       4096 Mar 10 21:41 ..
-rw-r----- 1 clickhouse clickhouse 2735 May  5 16:49 clickhouse-server.err.log
-rw-r----- 1 clickhouse clickhouse 2735 May  5 16:49 clickhouse-server.log
clickhouse@chi-clickhouse-logging-replicated-0-0-0:/$ 

```

**Expected behavior**

No logs are written to the filesystem of the container.

**Comment by alexey-milovidov** [comment]
I don't think it's a problem.
I know that according to some best practices, the logs in Docker should go to stdout.
But we shouldn't always follow these practices.

When logs go to stdout, they usually end up in some external system that cannot handle logs well.
In contrast, when logs are written to a file, you can go into a container and look.

**Comment by monotek** [comment]
Best practice is to run container with read only filesystem, following the official kubernetes restricted container policy standards. 

We even enforce that in our clusters.

There is absolutely no benefit doing it otherwise, as the containers logs are going to stdout additionally.

Would be nice this behaviour could be reconsidered. 

Otherwise a lot of people might just not able to use Clickhouse in kubernetes. For example this should hit everybody who is running an openshift kubernetes cluster.

**Comment by alexey-milovidov** [comment]
Interesting - we are using ClickHouse in Kubernetes, but it writes logs normally.

Also, just to note: our Docker container is just a tiny wrapper over ClickHouse. There is no big value in this wrapper.
If you need some customization, you can just write another Dockerfile.

**Comment by zonescape** [comment]
This config does the job:

```xml
<clickhouse>
    <logger>
        <log>/dev/null</log>
        <errorlog>/dev/null</errorlog>
        <console>1</console>
    </logger>
</clickhouse>
```
