### ISSUE TITLE
LIVE VIEWs not supported for JSON columns

### ISSUE THREAD

**Issue by dilyevsky** [ClickHouse/ClickHouse#49571]
> You have to provide the following information whenever possible.

**Describe what's wrong**

When creating a LIVE VIEW with SELECT against JSON columns a WATCH fails with "Missing columns ... (UNKNOWN_IDENTIFIER)" error.

Example: https://fiddle.clickhouse.com/d7c00c22-b047-4448-8724-5f4fb69ae0a9

**Does it reproduce on recent release?**

Yup (see fiddle)

**Enable crash reporting**

n/a

**How to reproduce**

Settings included in the example:

```
SET allow_experimental_object_type = 1;
CREATE TABLE json
(
    o JSON
)
ENGINE = Memory;

INSERT INTO json VALUES ('{"a": 1, "b": { "c": 2, "d": [1, 2, 3] }}');
SELECT o.a, o.b.c, o.b.d[3] FROM json;

SET allow_experimental_live_view = 1;

CREATE LIVE VIEW lv AS SELECT o.a, o.b.c, o.b.d[3] FROM json;
WATCH lv;
```

**Expected behavior**

Would be nice to have full watch capability for JSON cols.

**Error message and/or stacktrace**

n/a

**Additional context**

Possibly related to https://github.com/ClickHouse/ClickHouse/issues/37584 if my understanding of how it's implemented is correct. Filing this issues separately for someone to triage and confirm.

**Comment by dilyevsky** [comment]
Oh one extra bit of info when trying to WATCH entire JSON column, the error is slightly different:

```
:) CREATE LIVE VIEW lv AS SELECT o FROM json;

CREATE LIVE VIEW lv AS
SELECT o
FROM json

Query id: eed8b151-d978-4284-a555-7a83b9d07826

Ok.

0 rows in set. Elapsed: 0.001 sec.

:) WATCH lv;

WATCH lv

Query id: 97bc9e01-be32-4817-8681-983381d03e68


0 rows in set. Elapsed: 0.166 sec.

Received exception:
Code: 48. DB::Exception: ColumnObject must be converted to ColumnTuple before use. (NOT_IMPLEMENTED)
```

**Comment by alexey-milovidov** [comment]
We don't support either LIVE VIEW, or the JSON data type.
The experimental flag indicates this.

**Comment by dilyevsky** [comment]
@alexey-milovidov should this be re-classified as FR then? Seems like pretty useful thing to have overall...

**Comment by melvynator** [comment]
@dilyevsky We have a RFC for JSON: #54864
