### ISSUE TITLE
Setting up ClickHouse on CloudLab

### ISSUE THREAD

**Issue by saarthdeshpande** [ClickHouse/ClickHouse#49575]
Hi,

I'm trying to setup ClickHouse on a CloudLab xl170 machine (Intel E5-2640v4 64-bit CPU). On runnning `cmake --build build`, I get this error: 

> [0/2] Re-checking globbed directories...
> [1/11753] Building ASM object contrib/libunwind-cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersRestore.S.o
> FAILED: contrib/libunwind-cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersRestore.S.o 
> /usr/bin/cc --sysroot=/proj/schedpolicies-PG0/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -D_DEBUG -D_LIBUNWIND_IS_NATIVE_O
> NLY -D_LIBUNWIND_NO_HEAP=1 -isystem /proj/schedpolicies-PG0/ClickHouse/contrib/libunwind/include --gcc-toolchain=/proj/schedpolicies-PG0/ClickHouse/cmake/linux
> /../../contrib/sysroot/linux-x86_64 -ffile-prefix-map=/proj/schedpolicies-PG0/ClickHouse=.  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasync
> hronous-unwind-tables -ffile-prefix-map=/proj/schedpolicies-PG0/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries  -O2 -g -DNDEBUG -O3 -g -gdw
> arf-4    -D OS_LINUX -O3 -fno-exceptions -funwind-tables -fno-sanitize=all -Wno-unused-but-set-variable -MD -MT contrib/libunwind-cmake/CMakeFiles/unwind.dir/_
> _/libunwind/src/UnwindRegistersRestore.S.o -MF contrib/libunwind-cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersRestore.S.o.d -o contrib/libunwind
> -cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersRestore.S.o -c /proj/schedpolicies-PG0/ClickHouse/contrib/libunwind/src/UnwindRegistersRestore.S
> cc: error: argument to ‘-gdwarf-’ should be a non-negative integer
> cc: error: unrecognized command line option ‘--gcc-toolchain=/proj/schedpolicies-PG0/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64’
> cc: error: unrecognized command line option ‘-mbranches-within-32B-boundaries’
> [2/11753] Building ASM object contrib/libunwind-cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersSave.S.o
> FAILED: contrib/libunwind-cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersSave.S.o 
> /usr/bin/cc --sysroot=/proj/schedpolicies-PG0/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -D_DEBUG -D_LIBUNWIND_IS_NATIVE_O
> NLY -D_LIBUNWIND_NO_HEAP=1 -isystem /proj/schedpolicies-PG0/ClickHouse/contrib/libunwind/include --gcc-toolchain=/proj/schedpolicies-PG0/ClickHouse/cmake/linux
> /../../contrib/sysroot/linux-x86_64 -ffile-prefix-map=/proj/schedpolicies-PG0/ClickHouse=.  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasync
> hronous-unwind-tables -ffile-prefix-map=/proj/schedpolicies-PG0/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries  -O2 -g -DNDEBUG -O3 -g -gdw
> arf-4    -D OS_LINUX -O3 -fno-exceptions -funwind-tables -fno-sanitize=all -Wno-unused-but-set-variable -MD -MT contrib/libunwind-cmake/CMakeFiles/unwind.dir/_
> _/libunwind/src/UnwindRegistersSave.S.o -MF contrib/libunwind-cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersSave.S.o.d -o contrib/libunwind-cmake/CMakeFiles/unwind.dir/__/libunwind/src/UnwindRegistersSave.S.o -c /proj/schedpolicies-PG0/ClickHouse/contrib/libunwind/src/UnwindRegistersSave.S
> cc: error: argument to ‘-gdwarf-’ should be a non-negative integer
> cc: error: unrecognized command line option ‘--gcc-toolchain=/proj/schedpolicies-PG0/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64’
> cc: error: unrecognized command line option ‘-mbranches-within-32B-boundaries’
> ninja: build stopped: subcommand failed.

How can I fix this?

**Comment by alexey-milovidov** [comment]
ClickHouse can only be built with `clang`. There is no support for `gcc`.

PS. What is CloudLab?

**Comment by saarthdeshpande** [comment]
As per the steps on the ClickHouse documentation, I run `cmake -S . -B build` with `CC=clang-15` and `CXX=clang++-15`. This runs successfully. The step after this is to run `cmake --build build`, which fails. The error shown above is what follows. How can I resolve it?

Cloudlab provides access to machines (similar to AWS EC2) for research purposes.

**Comment by alexey-milovidov** [comment]
For some reason, the build in your example uses `cc` instead of `clang`.

I'm building ClickHouse by the following instruction:
https://clickhouse.com/docs/en/development/developer-instruction

```
mkdir build
cd build
CC=clang-16 CXX=clang++-16 cmake ..
ninja
```

**Comment by saarthdeshpande** [comment]
Fixed that and installed `cmake` with only `clang-15` and uninstalled `gcc`, but I have other errors that occur on running `ninja`:

> failed: contrib/llvm-project/llvm/lib/Target/X86/X86GenDisassemblerTables.inc /proj/schedpolicies-PG0/ClickHouse/build/contrib/llvm-project/llvm/lib/Target/X86/X86GenDisassemblerTables.inc cd /proj/schedpolicies-PG0/ClickHouse/build && /proj/schedpolicies-PG0/ClickHouse/build/contrib/llvm-project/llvm/bin/llvm-tblgen -gen-disassembler -I /proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/llvm/lib/Target/X86 -I/proj/schedpolicies-PG0/ClickHouse/build/contrib/llvm-project/llvm/include -I/proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/llvm/include -I /proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/llvm/lib/Target /proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/llvm/lib/Target/X86/X86.td --write-if-changed -o contrib/llvm-project/llvm/lib/Target/X86/X86GenDisassemblerTables.inc -d contrib/llvm-project/llvm/lib/Target/X86/X86GenDisassemblerTables.inc.dKilled

**Comment by saarthdeshpande** [comment]
Another error on `ninja clickhouse-server clickhouse-client`:

>failed: contrib/llvm-project/llvm/lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86ISelDAGToDAG.cpp.o /usr/bin/ccache /usr/bin/clang++-15 --target=x86_64-linux-gnu --sysroot=/proj/schedpolicies-PG0/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_GNU_SOURCE -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/proj/schedpolicies-PG0/ClickHouse/build/contrib/llvm-project/llvm/lib/Target/X86 -I/proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/llvm/lib/Target/X86 -I/proj/schedpolicies-PG0/ClickHouse/build/contrib/llvm-project/llvm/include -I/proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/llvm/include -I/proj/schedpolicies-PG0/ClickHouse/base/glibc-compatibility/memcpy -isystem /proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/libcxx/include -isystem /proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /proj/schedpolicies-PG0/ClickHouse/contrib/libunwind/include --gcc-toolchain=/proj/schedpolicies-PG0/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/proj/schedpolicies-PG0/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -w -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie -std=c++14 -fvisibility=hidden   -D OS_LINUX -g0 -Werror -nostdinc++ -MD -MT contrib/llvm-project/llvm/lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86ISelDAGToDAG.cpp.o -MF contrib/llvm-project/llvm/lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86ISelDAGToDAG.cpp.o.d -o contrib/llvm-project/llvm/lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86ISelDAGToDAG.cpp.o -c /proj/schedpolicies-PG0/ClickHouse/contrib/llvm-project/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp
