### ISSUE TITLE
[Question] How to split tuple into multiple columns with specific name.

### ISSUE THREAD

**Issue by frank-zsy** [ClickHouse/ClickHouse#49583]
Hi, community, the slack link in the issue template is outdated and I failed to join the slack channel, so I will raise the issue here.

ClickHouse version: `22.8.5.29`

I am trying to do something with `arrayJoin` and `multiIf` like below:

```sql
SELECT
	arrayJoin(multiIf(uid=1,[tuple(1,'a')],uid=2,[tuple(2,'b')],uid=3,[tuple(3,'c'),tuple(4,'d')],[tuple(-1,'Others')])) AS items,
	items.1 AS id,
	items.2 AS name,
	COUNT() AS count
FROM (SELECT arrayJoin([1, 2, 3]) AS uid)
GROUP BY id, name
```

But the SQL above throws `DB::Exception: Column 'uid' is not under aggregate function and not in GROUP BY`.

I am confused since `items` column does not contains `uid` anymore after the selection, why should `uid` in the `GROUP BY` or under aggregate function?

Further more, since I can not specify the column names with `untuple`, so I can not use it either.

Is there a better way to do this? Thanks for the time.

**Comment by den-crane** [comment]
`GROUP BY    items,`

```sql
SELECT
    arrayJoin(multiIf(uid = 1, [(1, 'a')], uid = 2, [(2, 'b')], uid = 3, [(3, 'c'), (4, 'd')], [(-1, 'Others')])) AS items,
    items.1 AS id,
    items.2 AS name,
    COUNT() AS count
FROM
(
    SELECT arrayJoin([1, 2, 3]) AS uid
)
GROUP BY
    items,
    id,
    name

┌─items───┬─id─┬─name─┬─count─┐
│ (2,'b') │  2 │ b    │     1 │
│ (1,'a') │  1 │ a    │     1 │
│ (3,'c') │  3 │ c    │     1 │
│ (4,'d') │  4 │ d    │     1 │
└─────────┴────┴──────┴───────┘

SELECT
    (arrayJoin(multiIf(uid = 1, [(1, 'a')], uid = 2, [(2, 'b')], uid = 3, [(3, 'c'), (4, 'd')], [(-1, 'Others')])) AS items).1 AS id,
    items.2 AS name,
    COUNT() AS count
FROM
(
    SELECT arrayJoin([1, 2, 3]) AS uid
)
GROUP BY
    id,
    name
┌─id─┬─name─┬─count─┐
│  1 │ a    │     1 │
│  2 │ b    │     1 │
│  4 │ d    │     1 │
│  3 │ c    │     1 │
└────┴──────┴───────┘
```

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-queries-and-syntax/pivot-unpivot/#unpivot

**Comment by frank-zsy** [comment]
@den-crane Thanks for the reply, actually I really need to use only `id` and `name` as group key since this is used in a framework so the columns used are fixed. The second way you provide is good enough for current situation, great thanks~
