### ISSUE TITLE
rpm install error. version: clickhouse-common-static-dbg-23.3.2.37.x86_64.rpm

### ISSUE THREAD

**Issue by duhy-max** [ClickHouse/ClickHouse#49589]
when i install clickhouse-common-static-dbg-23.3.2.37.x86_64.rpm  an error occur .

**Installation type**

rpm -ivh clickhouse-common-static-dbg-23.3.2.37.x86_64.rpm 

**[Source of the ClickHouse](https://github.com/ClickHouse/ClickHouse/releases/download/v23.3.2.37-lts/clickhouse-common-static-dbg-23.3.2.37.x86_64.rpm)**
 
**Expected result**

```install sucess without error info .```

**The actual result**

```
error: unpacking of archive failed on file /usr/lib/debug/usr/bin/clickhouse-library-bridge.debug:cpio:rename failed - is a directory
error:clickhouse-common-static-dbg-0:23.3.2.37-1.x86_64:install failed
```

I searched for the error message, usually because the rpm package is incomplete or incorrect. My rpm package md5 value is
MD5 (clickhouse-common-static-dbg-23.3.2.37.x86_64.rpm) =` 04b56ef53d616ad97fcf94eb999f3c27`

**Comment by Felixoid** [comment]
There's zero info to reproduce the issue, so I can't help here anyhow besides the attempt to reproduce on my own.

Here's an [example](https://pastila.nl/?009cc50c/5ce4c85645311563ea22fd4fbe7d7cc5) of the packages' installation on fedora:37 docker container.

**Comment by duhy-max** [comment]
sorry for zero info .
os：suse 12 sp5
I installed it through rpm package management, not yum。

`rpm -ivh clickhouse-common-static-dbg-23.3.2.37.x86_64.rpm `

What other information do I need to provide

**Comment by Felixoid** [comment]
I need a reproducing case. https://github.com/ClickHouse/ClickHouse/blob/master/.github/ISSUE_TEMPLATE/96_installation-issues.md?plain=1#L30

How can I get your state? Did you try the clear docker container?

**Comment by Felixoid** [comment]
Here's an [output](https://pastila.nl/?009cc50c/267737ab6ee6943f2cd7549434569d02) of the installation process in a clear `opensuse/leap` docker container. As you see, no errors regarding strange things in `/usr/lib/debug/usr/bin/clickhouse-library-bridge.debug`

And here's the package's files:

```
# rpm -ql clickhouse-common-static-dbg
/usr/lib/debug/usr/bin/clickhouse-library-bridge.debug
/usr/lib/debug/usr/bin/clickhouse-odbc-bridge.debug
/usr/lib/debug/usr/bin/clickhouse.debug
/usr/share/doc/clickhouse-common-static-dbg/AUTHORS
/usr/share/doc/clickhouse-common-static-dbg/CHANGELOG.md
/usr/share/doc/clickhouse-common-static-dbg/LICENSE
/usr/share/doc/clickhouse-common-static-dbg/README.md
```

Your system is in an inconsistent state in `/usr/lib/debug/usr/bin/`, so check what's there.

**Comment by Felixoid** [comment]
BTW, after some work on the attempt to reproduce it, I've added the documentation on how to install the repository on systems with `zypper` package manager, see https://github.com/ClickHouse/ClickHouse/pull/49629/files#diff-29b42264bb6f0c1ef758532ab3ccb48afaceee84d83e0b8b6ed9c12822aa1c01R190

**Comment by alexey-milovidov** [comment]
@duhy-max if your system has a broken package manager, I recommend installing ClickHouse as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by duhy-max** [comment]
@Felixoid Thanks . 

Actually I upgraded from a lower version clickhouse to 23.3.2.37.   

First, I uninstalled clickhouse by command `rpm -e clickhouse-xxx`

Then I stopped the clickhouse service `systemctl stop clickhouse-server`


When I upgraded the version before, it was installed normally next `rpm -ivh *.rpm`

According to your prompt。 


I found that /usr/lib/debug/usr/bin/ directory has an exception file

`---------- 1 root root 885962296 may 8 09:05 clickhouse-library-bridge.debug;64584ac0`

and some previous version files。 

then i `rm clickchouse*`

Now , I install sucess by use `rpm -ivh clickhouse*`

My environment does not have internet access and can not use docker container .

But finally I solved it by your tips.
