### ISSUE TITLE
Unexpected "DISTINCT" result with empty string

### ISSUE THREAD

**Issue by Onehr7** [ClickHouse/ClickHouse#49622]
+ ClickHouse Version

    `23.4.2.11`

+ DDL
    ```sql
    CREATE TABLE test
    (
        c1 String,
        c2 String,
        c3 String
    )
    ENGINE = ReplacingMergeTree
    ORDER BY (c1, c3);
    
    INSERT INTO test(c1, c2, c3) VALUES
        ('', '', '1'), ('', '', '2'),('v1', 'v2', '3'),('v1', 'v2', '4'),('v1', 'v2', '5');
    ```

```sql

SELECT c1, c2, c3 FROM test GROUP BY c1, c2, c3;
┌─c1─┬─c2─┬─c3─┐
│    │    │ 2  │
│ v1 │ v2 │ 4  │
│ v1 │ v2 │ 3  │
│    │    │ 1  │
│ v1 │ v2 │ 5  │
└────┴────┴────┘

SELECT DISTINCT c1, c2, c3 FROM test;
┌─c1─┬─c2─┬─c3─┐
│    │    │ 1  │
│ v1 │ v2 │ 3  │
│ v1 │ v2 │ 4  │
│ v1 │ v2 │ 5  │
└────┴────┴────┘

```
Why does the query result of this DISTINCT clause not contain rows where c3 is 2

**Comment by den-crane** [comment]
It's a bug in `optimize_distinct_in_order`

https://fiddle.clickhouse.com/47480a95-3ee1-4047-be35-2af029581735

@devcrafter

**Comment by devcrafter** [comment]
Minimal example:
```sql
CREATE TABLE test
(
    `c1` String,
    `c2` String
)
ENGINE = MergeTree
ORDER BY c1;

INSERT INTO test(c1, c2) VALUES ('1',  ''), ('2', '');

SELECT DISTINCT *
FROM test

Query id: 29f37b24-c93e-4e05-bac4-d26e8f1f48cf

┌─c1─┬─c2─┐
│ 1  │    │
└────┴────┘
```

`ZeroValueStorage` is _not_ cleared in `ClearableHashSet*` when `clear()` is called

Details:
The `ClearableSetVariants` is used to determine distinct values in non-sorted columns(`c2` in example above) inside ranges in sorted columns (`c1` is sorted column).
In the example above, there are 2 ranges, 1 row each, and for both ranges `c2` contains zero value for `String`.
Before counting distinct values in each range, the `clear()` is called for the`ClearableHashSet*` for corresponding type, the code is [here](https://github.com/ClickHouse/ClickHouse/blob/33e1888ca74fa8388a7f214970b8a60d7a96555a/src/Processors/Transforms/DistinctSortedChunkTransform.cpp#L76). But the `clear()` call doesn't clear `ZeroValueStorage` in the hash set, so the empty string in the second range considered as already counted
