### ISSUE TITLE
Server kafka/host@realm not found in Kerberos database

### ISSUE THREAD

**Issue by jjftmac** [ClickHouse/ClickHouse#49648]
My confix.xml like this:
**<kafka>
                <bootstrap_servers>mrs63:21007,mrs64:21007,mrs94:21007</bootstrap_servers>
                <security_protocol>SASL_PLAINTEXT</security_protocol>
                <sasl_mechanism>GSSAPI</sasl_mechanism>
                <sasl_kerberos_keytab>/etc/clickhouse-server/config.d/user.keytab</sasl_kerberos_keytab>
                <sasl_kerberos_principal>dmp@HADOOP.COM</sasl_kerberos_principal>
                \<debug>security\</debug>
                <auto_offset_reset>latest</auto_offset_reset>
        </kafka>**

log:
{} <Notice> StorageKafka (kerberos_kafka_test_queue): [rdk:LIBSASL] [thrd:sasl_plaintext://mrs63:21007/bootstrap]: sasl_plaintext://mrs63:21007/bootstrap: GSSAPI client step 1
2023.05.08 11:05:18.429569 [ 20288 ] {} <Warning> StorageKafka (kerberos_kafka_test_queue): Can't get assignment. Will keep trying.
2023.05.08 11:05:18.448884 [ 20395 ] {} <Critical> StorageKafka (kerberos_kafka_test_queue): [rdk:LIBSASL] [thrd:sasl_plaintext://mrs63:21007/bootstrap]: sasl_plaintext://mrs63:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/mrs63@HADOOP.COM not found in Kerberos database)
2023.05.08 11:05:18.449038 [ 20395 ] {} <Error> StorageKafka (kerberos_kafka_test_queue): [rdk:ERROR] [thrd:sasl_plaintext://mrs63:21007/bootstrap]: 3/3 brokers are down
2023.05.08 11:05:18.983036 [ 20261 ] {} <Warning> StorageKafka (kerberos_kafka_test_queue): Can't get assignment. Will keep trying.
2023.05.08 11:05:18.983422 [ 20396 ] {} <Notice> StorageKafka (kerberos_kafka_test_queue): [rdk:LIBSASL] [thrd:sasl_plaintext://mrs64:21007/bootstrap]: sasl_plaintext://mrs64:21007/bootstrap: GSSAPI client step 1
2023.05.08 11:05:19.046956 [ 20396 ] {} <Critical> StorageKafka (kerberos_kafka_test_queue): [rdk:LIBSASL] [thrd:sasl_plaintext://mrs64:21007/bootstrap]: sasl_plaintext://mrs64:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/mrs64@HADOOP.COM not found in Kerberos database)
2023.05.08 11:05:19.047172 [ 20396 ] {} <Error> StorageKafka (kerberos_kafka_test_queue): [rdk:ERROR] [thrd:sasl_plaintext://mrs64:21007/bootstrap]: 3/3 brokers are down
2023.05.08 11:05:19.536429 [ 20259 ] {} <Warning> StorageKafka (kerberos_kafka_test_queue): Can't get assignment. Will keep trying.
2023.05.08 11:05:20.088913 [ 20246 ] {} <Warning> StorageKafka (kerberos_kafka_test_queue): Can't get assignment. Will keep trying.
2023.05.08 11:05:20.123860 [ 20397 ] {} <Notice> StorageKafka (kerberos_kafka_test_queue): [rdk:LIBSASL] [thrd:sasl_plaintext://mrs94:21007/bootstrap]: sasl_plaintext://mrs94:21007/bootstrap: GSSAPI client step 1
2023.05.08 11:05:20.452200 [ 20397 ] {} <Critical> StorageKafka (kerberos_kafka_test_queue): [rdk:LIBSASL] [thrd:sasl_plaintext://mrs94:21007/bootstrap]: sasl_plaintext://mrs94:21007/bootstrap: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server kafka/mrs94@HADOOP.COM not found in Kerberos database)
2023.05.08 11:05:20.452333 [ 20397 ] {} <Error> StorageKafka (kerberos_kafka_test_queue): [rdk:ERROR] [thrd:sasl_plaintext://mrs94:21007/bootstrap]: 3/3 brokers are down
2023.05.08 11:05:20.641760 [ 20245 ] {} <Warning> StorageKafka (kerberos_kafka_test_queue): Can't get assignment. Will keep trying.

**Server kafka/hostname@HADOOP.COM not found in Kerberos database**

My principal is dmp@HADOOP,but actually is kafka/hostname@HADOOP.COM ...

Is the principal must be [service_name]/hostname@realm?
if not ,how can I do ?

kafka/hadoop.hadoop.com@HADOOP.COM in the kerberos database,
so can i set the [hostname] to [hadoop.hadoop.com]?

Thanks!

**Comment by alexey-milovidov** [comment]
Hadoop is not supported.

**Comment by jjftmac** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by alexey-milovidov** [comment]
@jjftmac, thank you. Have a good vacation!

**Comment by alexey-milovidov** [comment]
> My confix.xml like this:

You made a mistake - the file should be named "config.xml", not "confix.xml"
