### ISSUE TITLE
Add settings `allow_suspicious_codecs`.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#4966]
If this setting is turned off (default), don't allow to create a table with nonsense codec declarations:
- a codec that does some transformations but does not compress data without compressing codec later in the list (example: `CODEC(Delta)`);
- more than one generic compression codec (example: `CODEC(LZ4, ZSTD)`);
- type-dependent transformation after generic compression codec (example: `CODEC(LZ4, Delta)`).

Always allow to attach a table.
These combinations of codecs are still available for tests (under this setting).

**Comment by adrian17** [comment]
> a codec that does some transformations but does not compress data without compressing codec later in the list (example: CODEC(Delta));

That means that the example in documentation should be updated, right?

```
CREATE TABLE codec_example
(
    timestamp DateTime CODEC(DoubleDelta),
    slow_values Float32 CODEC(Gorilla)
)
```
https://clickhouse.tech/docs/en/sql-reference/statements/create/#create-query-specialized-codecs

**Comment by alexey-milovidov** [comment]
@adrian17 Both `DoubleDelta` and `Gorilla` compresses data.

PS. `DoubleDelta` codec has bad name (the origin of this name is from some paper). It is not just about applying Delta transformation two times, it also encodes small integers in less number of bits.

**Comment by alexey-milovidov** [comment]
But I recommend to always add LZ4 just in case:

```
CREATE TABLE codec_example
(
    timestamp DateTime CODEC(DoubleDelta, LZ4),
    slow_values Float32 CODEC(Gorilla, LZ4)
)
```
