### ISSUE TITLE
AST Fuzzer (msan): use-of-uninitialized-value in StringSearcher

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#49672]
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/49636/fe02317d4595ddcea9837dc5a33f047242653642/fuzzer_astfuzzermsan/report.html)

Stacks:
https://pastila.nl/?030ef1b1/7e71a0d51ee89c61ce8ca97856c021e2
https://pastila.nl/?0269eed6/0c3c7e9b0b6c6db8cbc7dbeed06ce055
https://pastila.nl/?0269eed6/2d09fe39393369b364c2d304993d12cc

Look like something related to string searcher
CC @rschu1ze

**Comment by rschu1ze** [comment]
Minimal repro: `SELECT positionUTF8(concat('xyz', randomStringUTF8(15), '\0'), 'needle')` (msan build)

**Comment by rschu1ze** [comment]
More minimal repro: `SELECT lowerUTF8(concat(randomStringUTF8(50), '\0', 'x'))`. My first suspicion was the SIMD optimizations in #46289 caused this but it looks like `concat()` messes up its output. Checking further ...
