### ISSUE TITLE
CentOS 7 X86_64 build ClickHouse v23.3.2.37-lts failed

### ISSUE THREAD

**Issue by zenvzenv** [ClickHouse/ClickHouse#49689]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**

Linux

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

Virtual Box 7.0.4

CentOS 7 3.10.0-693.el7.x86_64

**Cmake version**

cmake version 3.26.3

**Ninja version**
ninja version 1.10.2

**Compiler name and version**
CC=/usr/local/bin/clang CXX=/usr/local/bin/clang++

clang version 16.0.3 (/opt/llvm-project/clang da3cd333bea572fb10470f610a27f22bcb84b08c)

Target: x86_64-unknown-linux-gnu

Thread model: posix

**Full cmake and/or ninja output**

**cmake output**
-- Cross-compiling for target:
-- Using compiler:
clang version 16.0.3 (/opt/llvm-project/clang da3cd333bea572fb10470f610a27f22bcb84b08c)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
-- Using linker: <default>
-- Using archiver: /usr/local/bin/llvm-ar
-- Using ranlib: /usr/local/bin/llvm-ranlib
-- Using install-name-tool: /usr/local/bin/llvm-install-name-tool
-- Using objcopy: /usr/local/bin/llvm-objcopy
-- Using strip: /usr/local/bin/llvm-strip
-- Using *ccache: no (disabled via configuration)

-- Git HEAD commit hash: 1b144bcd101ddf23466ba67e4fa0fd27afb9c060
# HEAD detached at v23.3.2.37-lts
nothing to commit, working directory clean
-- CMAKE_BUILD_TYPE: Release
-- No official build: A checksum hash will not be added to the clickhouse executable
-- Default libraries: -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl
-- Using libunwind: unwind
-- Using exception handler: unwind
-- Some symbols from glibc will be replaced for compatibility
-- Unit tests are enabled
-- Building for: Linux x86_64
-- Adding contrib module boringssl (configuring with boringssl-cmake)
-- Adding contrib module miniselect (configuring with miniselect-cmake)
-- Adding contrib module pdqsort (configuring with pdqsort-cmake)
-- Adding contrib module crc32-vpmsum (configuring with crc32-vpmsum-cmake)
-- crc32-vpmsum library is only supported on ppc64le
-- Adding contrib module sparsehash-c11 (configuring with sparsehash-c11-cmake)
-- Adding contrib module abseil-cpp (configuring with abseil-cpp-cmake)
-- Adding contrib module magic_enum (configuring with magic-enum-cmake)
-- Adding contrib module boost (configuring with boost-cmake)
-- Adding contrib module cctz (configuring with cctz-cmake)
-- Packaging with tzdata version: 2023c
-- Adding contrib module consistent-hashing (configuring with consistent-hashing)
-- Adding contrib module dragonbox (configuring with dragonbox-cmake)
-- Adding contrib module vectorscan (configuring with vectorscan-cmake)
-- Adding contrib module jemalloc (configuring with jemalloc-cmake)
-- jemalloc malloc_conf: percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000
-- Adding contrib module libcpuid (configuring with libcpuid-cmake)
-- Adding contrib module libdivide-cmake (configuring with libdivide-cmake)
-- Adding contrib module libmetrohash (configuring with libmetrohash)
-- Adding contrib module lz4 (configuring with lz4-cmake)
-- Adding contrib module murmurhash (configuring with murmurhash)
-- Adding contrib module replxx (configuring with replxx-cmake)
-- Adding contrib module unixodbc (configuring with unixodbc-cmake)
-- Adding contrib module nanodbc (configuring with nanodbc-cmake)
-- Adding contrib module capnproto (configuring with capnproto-cmake)
-- Adding contrib module yaml-cpp (configuring with yaml-cpp-cmake)
-- Adding contrib module re2 (configuring with re2-cmake)
-- Adding contrib module xz (configuring with xz-cmake)
-- Adding contrib module brotli (configuring with brotli-cmake)
-- Adding contrib module double-conversion (configuring with double-conversion-cmake)
-- Adding contrib module croaring (configuring with croaring-cmake)
-- Adding contrib module zstd (configuring with zstd-cmake)
-- Adding contrib module zlib-ng (configuring with zlib-ng-cmake)
-- Adding contrib module bzip2 (configuring with bzip2-cmake)
-- Adding contrib module minizip-ng (configuring with minizip-ng-cmake)
-- Adding contrib module snappy (configuring with snappy-cmake)
-- Adding contrib module rocksdb (configuring with rocksdb-cmake)
-- Adding contrib module thrift (configuring with thrift-cmake)
-- Adding contrib module arrow (configuring with arrow-cmake)
-- Using toolchain file: /opt/ClickHouse/cmake/linux/toolchain-x86_64.cmake.
-- CMAKE_CXX_FLAGS:  --gcc-toolchain=/opt/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Wno-enum-constexpr-conversion -fsized-deallocation  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/opt/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w
-- Proceeding with version: 1.12.0.372
-- Adding contrib module avro (configuring with avro-cmake)
-- Adding contrib module protobuf (configuring with protobuf-cmake)
-- Adding contrib module openldap (configuring with openldap-cmake)
-- Adding contrib module grpc (configuring with grpc-cmake)
-- Adding contrib module msgpack-c (configuring with msgpack-c-cmake)
-- Adding contrib module corrosion (configuring with corrosion-cmake)
No such file or directory
CMake Warning at contrib/corrosion/cmake/FindRust.cmake:176 (message):
  The rustc executable was not found.  Rust not installed or ~/.cargo/bin not
  added to path? Aborting further actions of find_package(Rust).
Call Stack (most recent call first):
  contrib/corrosion-cmake/CMakeLists.txt:8 (find_package)

-- Not using rust
-- Adding contrib module wyhash (configuring with wyhash-cmake)
-- Adding contrib module cityhash102 (configuring with cityhash102)
-- Adding contrib module libfarmhash (configuring with libfarmhash)
-- Adding contrib module icu (configuring with icu-cmake)
-- Adding contrib module h3 (configuring with h3-cmake)
-- Adding contrib module mariadb-connector-c (configuring with mariadb-connector-c-cmake)
-- Adding contrib module googletest (configuring with googletest-cmake)
-- Adding contrib module llvm-project (configuring with llvm-project-cmake)
-- The xar file format has been deprecated: LLVM_HAVE_LIBXAR might be removed in the future.
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.10.2
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86
-- Adding contrib module llvm-project (configuring with libfuzzer-cmake)
-- Adding contrib module llvm-project (configuring with gwpasan-cmake)
-- Adding contrib module libxml2 (configuring with libxml2-cmake)
-- Adding contrib module aws;aws-c-auth;aws-c-cal;aws-c-common;aws-c-compression;aws-c-event-stream;aws-c-http;aws-c-io;aws-c-mqtt;aws-c-s3;aws-c-sdkutils;aws-s2n-tls;aws-checksums;aws-crt-cpp;aws-cmake (configuring with aws-cmake)
-- Adding contrib module base64 (configuring with base64-cmake)
-- Adding contrib module simdjson (configuring with simdjson-cmake)
-- Adding contrib module rapidjson (configuring with rapidjson-cmake)
-- Adding contrib module fastops (configuring with fastops-cmake)
-- Adding contrib module libuv (configuring with libuv-cmake)
-- Adding contrib module liburing (configuring with liburing-cmake)
-- Adding contrib module AMQP-CPP (configuring with amqpcpp-cmake)
-- Adding contrib module cassandra (configuring with cassandra-cmake)
-- Adding contrib module curl (configuring with curl-cmake)
-- Adding contrib module azure (configuring with azure-cmake)
By default, if no option is selected, on POSIX, libcurl transport adapter is used.
-- Adding contrib module sentry-native (configuring with sentry-native-cmake)
-- Adding contrib module fmtlib (configuring with fmtlib-cmake)
-- Adding contrib module krb5 (configuring with krb5-cmake)
-- Adding contrib module cyrus-sasl (configuring with cyrus-sasl-cmake)
-- Adding contrib module libgsasl (configuring with libgsasl-cmake)
-- Adding contrib module librdkafka (configuring with librdkafka-cmake)
-- librdkafka with SASL support
-- librdkafka with SSL support
-- Adding contrib module nats-io (configuring with nats-io-cmake)
-- Adding contrib module libhdfs3 (configuring with libhdfs3-cmake)
-- Enable kerberos for HDFS
-- checking compiler: CLANG
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- yes
-- enable perf checksum
-- Adding contrib module hive-metastore (configuring with hive-metastore-cmake)
-- Adding contrib module cppkafka (configuring with cppkafka-cmake)
-- Adding contrib module libpqxx (configuring with libpqxx-cmake)
-- Adding contrib module libpq (configuring with libpq-cmake)
-- Adding contrib module NuRaft (configuring with nuraft-cmake)
-- Adding contrib module fast_float (configuring with fast_float-cmake)
-- Adding contrib module datasketches-cpp (configuring with datasketches-cpp-cmake)
-- Adding contrib module hashidsxx (configuring with hashidsxx-cmake)
-- Adding contrib module libstemmer_c (configuring with libstemmer-c-cmake)
-- Adding contrib module wordnet-blast (configuring with wordnet-blast-cmake)
-- Adding contrib module lemmagen-c (configuring with lemmagen-c-cmake)
-- Adding contrib module nlp-data (configuring with nlp-data-cmake)
-- Adding contrib module cld2 (configuring with cld2-cmake)
-- Adding contrib module sqlite-amalgamation (configuring with sqlite-cmake)
-- Adding contrib module s2geometry (configuring with s2geometry-cmake)
-- Adding contrib module c-ares (configuring with c-ares-cmake)
-- Adding contrib module qpl (configuring with qpl-cmake)
-- Not using QPL
-- Adding contrib module morton-nd (configuring with morton-nd-cmake)
-- Adding contrib module annoy (configuring with annoy-cmake)
-- Adding contrib module xxHash (configuring with xxHash-cmake)
-- Adding contrib module google-benchmark (configuring with google-benchmark-cmake)
-- Adding contrib module ulid-c (configuring with ulid-c-cmake)
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536 - Success
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536 - Success
-- compiler C   = /usr/local/bin/clang  --gcc-toolchain=/opt/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Wno-enum-constexpr-conversion  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/opt/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O3 -DNDEBUG
-- compiler CXX = /usr/local/bin/clang++  --gcc-toolchain=/opt/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Wno-enum-constexpr-conversion -fsized-deallocation  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/opt/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -O3 -DNDEBUG
-- LINKER_FLAGS =  --gcc-toolchain=/opt/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -rdynamic -no-pie -Wl,-no-pie
-- Using Poco::Crypto
-- Using Poco::Data::ODBC
-- /opt/ClickHouse/src: Have 9838 megabytes of memory.
        Limiting concurrent linkers jobs to 2 and compiler jobs to 3 (system has 4 logical cores)
-- Will build ClickHouse 23.3.2.1 revision 54472
-- ClickHouse modes:
-- Server mode: ON
-- Client mode: ON
-- Local mode: ON
-- Self-extracting executable: OFF
-- Benchmark mode: ON
-- Extract from config mode: ON
-- Compressor mode: ON
-- Copier mode: ON
-- Format mode: ON
-- Obfuscator mode: ON
-- ODBC bridge mode: ON
-- Library bridge mode: ON
-- ClickHouse install: ON
-- ClickHouse git-import: ON
-- ClickHouse keeper mode: ON
-- ClickHouse keeper-converter mode: ON
-- Clickhouse disks mode: ON
-- ClickHouse su: ON
-- bash_completion will be written to /usr/local/share/bash-completion/completions
-- Target check already exists
-- /opt/ClickHouse/utils: Have 9838 megabytes of memory.
        Limiting concurrent linkers jobs to 2 and compiler jobs to OFF (system has 4 logical cores)
-- Configuring done (3.0s)
-- Generating done (2.0s)
-- Build files have been written to: /opt/ClickHouse/build

**ninja output**
[0/2] Re-checking globbed directories...
[2/8545] Linking CXX executable contrib/protobuf-cmake/protoc
FAILED: contrib/protobuf-cmake/protoc
: && /usr/local/bin/clang++ --target=x86_64-linux-gnu --sysroot=/opt/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/opt/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Wno-enum-constexpr-conversion -fsized-deallocation  -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/opt/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -O3 -DNDEBUG --gcc-toolchain=/opt/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -rdynamic -no-pie -Wl,-no-pie    -Xlinker --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o -o contrib/protobuf-cmake/protoc  contrib/protobuf-cmake/lib_libprotoc.a  contrib/protobuf-cmake/lib_libprotobuf.a  -lpthread  contrib/zlib-ng-cmake/lib_zlib.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  -Wl,--start-group  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl && :
/opt/rh/devtoolset-9/root/usr/bin/ld: cannot find -lpthread
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
[5/8545] Building C object contrib/openldap-cmake/CMakeFiles/_ldap_r.dir/__/openldap/libraries/libldap/getdn.c.o
ninja: build stopped: subcommand failed.

**Comment by nickitat** [comment]
you need to install `pthread`

**Comment by eleksir** [comment]
> you need to install `pthread`

кэп? тебе сложно самому сделать yum search pthread? и вот если бы ты хоть чуть-чуть погрузился в вопрос, то наверно советывал бы поставить не pthread, а тот пакет, в который это входит.

Но давай, давай я тебе подскажу: просто с закрытыми глазами - нужны glibc-devel glibc-static glibc-headers. Вот если ответишь это, то формальность будет соблюдена - "какой-то" ответ ты дал.

Однако, скорее всего проблема кроется несколько глубже.
------------------------------------------------------------------------------------------------------

Je vous demande pardon. I could not hold myself and avoid critique of such a low-grade stackoverflow-indian-like recommendation.

I'd want to say that "pthread" you advice to install is part of packages glibc-headers + glibc-devel + glibc-static and actually all these packages should be installed on builder.

But also i'd like to mention that i met same kind of problem with different options - clickhouse refuses to build with clang-16.0.6, complaining to same troubles:
```
/usr/bin/ld: cannot find -lpthread
```

around protobuf lib.
This happens if i run default build with minimal set of flags, just like that:
```
cd ClickHouse
mkdir build
cmake -S . -B build
cmake --build build
```

and if i run build with
```
cmake -S . -B build -DENABLE_LIBRARIES=0 -DENABLE_EMBEDDED_COMPILER=0
cmake --build build
```

it ends up with 
```
/usr/bin/ld: cannot find -lrt
/usr/bin/ld: cannot find -lpthread
```

And it looks like trouble lies somewhere deeper.

**Comment by zenvzenv** [comment]
I have solved this problem. The solution is to recompile `LLVM-16.0.3`. It may be caused by the low version of `lld` on the compilation machine.The compile cmd follow:
```shell
scl enable devtoolset-9 rh-python36 'cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lld" -G "Unix Makefiles" ../llvm-project/llvm'
scl enable devtoolset-9 rh-python36 'make -j $THREADS && make install'
```
