### ISSUE TITLE
'mutex lock failed: Invalid argument' when inserting into file() using clickhouse-local in debug build

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#49684]
Just:
```
% programs/clickhouse local -q "insert into function file('t.parquet', Parquet, 'a Int8') values (1)"
libc++abi: terminating due to uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
zsh: IOT instruction (core dumped)  programs/clickhouse local -q 
```

Stack trace (on revision 8bc04d5fa8f395ea10d9f96a244e54c49fe72c94): https://pastila.nl/?00548a42/f56fa8a5ad21b50cfb214d676690405a

StorageFile is destroyed before StorageFileSink that points into StorageFile::rwlock.

Stack traces where StorageFile and StorageFileSink are destroyed: https://pastila.nl/?00548a42/2844213983b0afc92efd8bdd1efa4cf8

I can't tell what's the intended behavior: should StorageFile always outlive all its StorageFileSink-s, or should StorageFileSink have a shared_ptr to the mutex?

**Comment by evillique** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/56710
