### ISSUE TITLE
allow_experimental_parallel_reading_from_replicas multplies results

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#49708]
```sql
CREATE TABLE test (id UInt64, date Date)
ENGINE = MergeTree
ORDER BY id
as select *, today() from numbers(100);

CREATE TABLE IF NOT EXISTS  test_d as test
ENGINE = Distributed(test_cluster_one_shard_three_replicas_localhost, currentDatabase(),test);

SELECT count(), sum(id) 
FROM test_d
SETTINGS allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 3, prefer_localhost_replica = 0;
┌─count()─┬─sum(id)─┐
│     300 │   14850 │
└─────────┴─────────┘

SELECT count(), sum(id) 
FROM test_d
┌─count()─┬─sum(id)─┐
│     100 │    4950 │
└─────────┴─────────┘
```

**Comment by alexey-milovidov** [comment]
It works perfectly: https://fiddle.clickhouse.com/25e9c9e5-e3f4-4e85-9c2b-ddca5f08bd2e

**Comment by den-crane** [comment]
3 replicas not 3 shards
https://fiddle.clickhouse.com/629d52be-eb36-41b9-b416-d10d0536c116

**Comment by den-crane** [comment]
allow_experimental_parallel_reading_from_replicas + prefer_localhost_replica=0

**Comment by devcrafter** [comment]
> 3 replicas not 3 shards https://fiddle.clickhouse.com/629d52be-eb36-41b9-b416-d10d0536c116

Thanks, @den-crane. Will check

**Comment by chandrsoni** [comment]
Think the issue might be here https://github.com/ClickHouse/ClickHouse/blob/832d6e3eb5c495fc82afa1cdf333db421d819425/src/Client/HedgedConnections.cpp#L185

**Comment by devcrafter** [comment]
Currently, to ensure that parallel replicas are used, please set `allow_experimental_parallel_reading_from_replicas=2`

https://fiddle.clickhouse.com/400ec8aa-7da7-4108-948e-725098ce2747

**Comment by chandrsoni** [comment]
I have the same result on my setup even with allow_experimental_parallel_reading_from_replicas=2 on my replicated setup.

the fiddle and my test for the same query gives out multiples as results.

https://fiddle.clickhouse.com/d44c1195-4719-4d70-9be2-db344ca493a6

+-count()-+-sum(id)-+
|     100 |    4950 |
+---------+---------+
+-count()-+-sum(id)-+
|     400 |   19800 |
+---------+---------+

**Comment by devcrafter** [comment]
> I have the same result even with allow_experimental_parallel_reading_from_replicas=2 on my replicated setup.
> 
> the fiddle and my test for the same query gives out multiples as results.
> 
> https://fiddle.clickhouse.com/d44c1195-4719-4d70-9be2-db344ca493a6
> 
> +-count()-+-sum(id)-+ | 100 | 4950 | +---------+---------+ +-count()-+-sum(id)-+ | 400 | 19800 | +---------+---------+

Before, it was necessary to set `use_hedged_requests=0` to enable parallel replicas (see https://fiddle.clickhouse.com/4e2de94e-10f0-408f-9a89-8cb4fbf7769f)
After https://github.com/ClickHouse/ClickHouse/pull/57542, it's not necessary anymore. Try the `head` version in the fiddle, it's more recent (23.12.1, currently).
