### ISSUE TITLE
Short-circuit on group by ... having and limit

### ISSUE THREAD

**Issue by mkherlakian** [ClickHouse/ClickHouse#49711]
We're wondering why one of our queries is scanning more data than it theoretically could. 

We're using `ReplicatedVersionedCollapsingMergeTree`, and our table structure is the following:

```
CREATE TABLE default.events
(
    `created_at_id` String,
    `id` String,
    `workspace_id` String,
    `_status` Nullable(String),
    `state` Nullable(String),
    `version` Int64,
    `sign` Int8
)
ENGINE = ReplicatedVersionedCollapsingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', sign, version)
ORDER BY (workspace_id, created_at_id)
TTL toDateTime(created_at) + toIntervalDay(35)
SETTINGS index_granularity = 8192
```
(Omitted a few columns not relevant for this discussion

created_at_id is a string column that we created to optimize for our querying pattern (cursoring), that guarantees uniqueness - it's a concatenation of created_at a unix timestamp, and the row's id.

We're trying to get X rows matching some filters but on their latest state only. 

Let's say an event had a state of `FAILED` and subsequently a state of `SUCCESS`, until collapsing happens, we'd have 3 rows for that id:

| id     | state  | version | sign  |
|--------|--------|--------|--------|
| 1683656370561000evt_123 | FAIL | 1 | 1 |
| 1683656370561000evt_123 | FAIL | 1 | -1 |
| 1683656370561000evt_123 | SUCCESS | 2 | 1 |

We're working with workspaces that have over 50M rows each, and a total of 500-1B rows.

The query to get let's say the 20 most recent by created_at that we're trying is:

```
SELECT * 
FROM events 
WHERE created_at_id IN (
  SELECT created_at_id
  FROM events
  WHERE workspace_id = 'test'
  GROUP BY team_id, created_at_id
  HAVING sum(sign) > 0
  ORDER BY team_id, created_at_id
  LIMIT 20
)
```

This takes 15 seconds and yields the following EXPLAIN:
```
┌─explain────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))        │
│   ReadFromMergeTree (default.events)               │
│   Indexes:                                         │
│     PrimaryKey                                     │
│       Keys:                                        │
│         created_at_id                              │
│       Condition: (created_at_id in 20-element set) │
│       Parts: 17/17                                 │
│       Granules: 838/51223                          │
└────────────────────────────────────────────────────┘
```

`838` would be almost all of the granules for that workspace.

Our expectation is that since we're scanning the data in order of the primary key, it would aggregate in a streaming fashion and return rows as they get aggregated, but that doesn't seem to be the case.
Is there an optimization that we could apply, or is there another more efficient way of approaching this?

The idea of getting the rows where sum > 0 is that if we added a filter for let's say FAIL, the previous versions of an uncollapsed row wouldn't be in the results since the sum of those would be 0.

We also tried with `SETTINGS optimize_aggregation_in_order=1` but that did not seem to have any effect.

Any help/suggestion would be much appreciated!

**Comment by den-crane** [comment]
This query scans all rows

```
SELECT * 
FROM events 
WHERE created_at_id IN
```

Try this

```
SELECT * 
FROM events 
WHERE workspace_id = 'test' 
     and   created_at_id IN ...
```

Clickhouse indexes work by prefix almost the same as other databases.

--------------------

This query scans all rows with `workspace_id = 'test'`
```
  SELECT created_at_id
  FROM events
  WHERE workspace_id = 'test'
  GROUP BY team_id, created_at_id
  HAVING sum(sign) > 0
  ORDER BY team_id, created_at_id
```

optimize_aggregation_in_order cannot work here because `GROUP BY` does not match with prefix of a table's `ORDERBY`.

`GROUP BY team_id, created_at_id`  !~ `ORDER BY (workspace_id, created_at_id)`

**Comment by mkherlakian** [comment]
Thanks @den-crane for the reply. The `team_id` was an oversight, it's supposed to be `workspace_id` in the query.

so the query we're using is effectively:

```
SELECT * 
FROM events 
WHERE created_at_id IN (
  SELECT created_at_id
  FROM events
  WHERE workspace_id = 'test'
  GROUP BY workspace_id, created_at_id
  HAVING sum(sign) > 0
  ORDER BY workspace_id, created_at_id
  LIMIT 20
)
```

The subquery is slow.
The `select * FROM` bit allows us to select all the columns for those ids, but that part is pretty fast. It's really the

````
  SELECT created_at_id
  FROM events
  WHERE workspace_id = 'test'
  GROUP BY workspace_id, created_at_id
  HAVING sum(sign) > 0
  ORDER BY workspace_id, created_at_id
  LIMIT 20
```

That's slow with aggergating 35M rows on `created_at_id`...
That's where I would've expected `optimize_aggregation_in_order` to work, but it doesn't seem to make a difference...

**Comment by mkherlakian** [comment]
Follow up to the above - 

```
SELECT created_at_id
FROM events
WHERE (workspace_id = 'test') AND (_status = 'SUCCESSFUL')
GROUP BY 1
HAVING sum(sign) > 0
LIMIT 10
SETTINGS optimize_aggregation_in_order = 1

┌─created_at_id──────────────┐
│ 1680641053882000evt_HrEjCa │
│ 1680639591625000evt_Dap73R │
│ 1680640555678000evt_gMvHP8 │
│ 1680640498101000evt_DHbQl5 │
│ 1680637893288000evt_VUzFCb │
│ 1680637588483000evt_sJePIv │
│ 1680638867555000evt_rohDnK │
│ 1680638990720000evt_QrLZ35 │
│ 1680640447139000evt_sMUIp1 │
│ 1680641302058000evt_T373GT │
└────────────────────────────┘

10 rows in set. Elapsed: 0.324 sec. Processed 1.14 million rows, 118.44 MB (3.53 million rows/s., 366.09 MB/s.)
```

So `optimize_aggregation_in_order=1` works in this case, but as soon as I add an ORDER BY it goes back to scanning the full set. Also notice that the rows are not in order.

```
SELECT created_at_id
FROM events
WHERE (workspace_id = 'test') AND (_status = 'SUCCESSFUL')
GROUP BY 1
HAVING sum(sign) > 0
ORDER BY 1 DESC
LIMIT 10
SETTINGS optimize_aggregation_in_order = 1

Query id: e8ba169b-bebe-49e2-ba8c-88a66b316c93

┌─created_at_id──────────────┐
│ 1683683071811000evt_MGI9SH │
│ 1683683071456000evt_5inEuE │
│ 1683683071378000evt_0QJGWu │
│ 1683683070522000evt_PoNB1U │
│ 1683683070363000evt_VLzmfF │
│ 1683683069619000evt_TkxQ4R │
│ 1683683069581000evt_oexy5o │
│ 1683683069336000evt_jAXeIT │
│ 1683683069177000evt_1K3GEV │
│ 1683683069140000evt_NiBHx9 │
└────────────────────────────┘

10 rows in set. Elapsed: 10.887 sec. Processed 36.24 million rows, 3.77 GB (3.33 million rows/s., 346.10 MB/s.)
```

Rows are in the correct order, but it processed 36M rows which is about how many we have for `test`.

**Comment by den-crane** [comment]
Clickhouse does not have optimization for groupby in order and sort in order together, though such optimization is possible.

```sql
CREATE TABLE events
(
    `created_at_id` String,
    `id` String,
    `workspace_id` String,
    `_status` Nullable(String),
    `state` Nullable(String),
    `version` Int64,
    `sign` Int8
)
ENGINE = VersionedCollapsingMergeTree(sign, version)
ORDER BY (workspace_id, created_at_id)
as select number, number, 'test', 'SUCCESSFUL', '', 1, number%10 != 0
from numbers(1e6);

insert into events
select number, number, 'not_test', 'SUCCESSFUL', '', 1, number%10 != 0
from numbers(1e6);

SELECT created_at_id
FROM events
WHERE (workspace_id = 'test') AND (_status = 'SUCCESSFUL')
GROUP BY workspace_id, created_at_id
HAVING sum(sign) > 0
--ORDER BY workspace_id DESC, created_at_id desc
LIMIT 10
SETTINGS optimize_aggregation_in_order = 1, max_threads = 1, max_block_size = 1000

10 rows in set. Elapsed: 0.005 sec. Processed 2.00 thousand rows, 97.76 KB (417.75 thousand rows/s., 20.42 MB/s.)


SELECT created_at_id
FROM events
WHERE (workspace_id = 'test') AND (_status = 'SUCCESSFUL')
GROUP BY workspace_id, created_at_id
HAVING sum(sign) > 0
ORDER BY workspace_id DESC, created_at_id desc
LIMIT 10
SETTINGS optimize_aggregation_in_order = 1, max_threads = 1, max_block_size = 1000

10 rows in set. Elapsed: 0.432 sec. Processed 1.00 million rows, 48.89 MB (2.32 million rows/s., 113.26 MB/s.)
```
