### ISSUE TITLE
Parquet "input_format_parquet_compression_method"

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/ClickHouse#49756]
**Use case**
Community user was getting a 403 error when I try to run INSERT of a Parquet dataset format that is `.gz.parquet`

The name of the dataset file was `part-00000-595ff019-d100-454a-91fd-c4c51e9f14ea-c000.gz.parquet`

Discussion was here in Community Slack :
https://clickhousedb.slack.com/archives/CU478UEQZ/p1683731244687099

**Describe the solution you'd like**
ClickHouse Parquet format settings already include this setting:

output_format_parquet_compression_method
https://clickhouse.com/docs/en/operations/settings/formats#output_format_parquet_compression_method

Why not also have an option for the input format compression method to solve this type of need? E.g., 
input_format_parquet_compression_method

**Describe alternatives you've considered**
Was thinking that if the Parquet dataset file is renamed with .gz as the filename extension, it might work by default via extension handling, e.g.,:
`part-00000-595ff019-d100-454a-91fd-c4c51e9f14ea-c000.parquet.gz`

**Additional context**
May apply to other format types other than just Parquet also.

**Comment by alexey-milovidov** [comment]
You can read '.gz.parquet' file if you specify both the data format and compression explicitly:
```
SELECT * FROM file('test.gz.parquet', Parquet, auto, gz)
```

**Comment by alexey-milovidov** [comment]
While the proper way is to rename it to `.parquet.gz` and it will work straight ahead:
```
SELECT * FROM file('test.parquet.gz')
```
