### ISSUE TITLE
Can I drop columns with low disk I/O?

### ISSUE THREAD

**Issue by MattMH** [ClickHouse/ClickHouse#49783]
OK , I have read all those documents 
https://clickhouse.com/docs/en/sql-reference/statements/alter/column#clear-column
https://clickhouse.com/docs/en/sql-reference/statements/drop
Both  
1. ALTER TABLE tbl DROP COLUMN col  
2. ALTER TABLE tbl CLEAR COLUMN col 
are mutation function which means it will cause a merge IO and consumed a lot of disk I/O
ClickHouse is Column-oriented database ,Intuitively, I think that ClickHouse supports a low-cost method to delete COLUMNS.

**Comment by den-crane** [comment]
To solve these commands CH recreates all parts in the table, hardlinks all files of the table.
If the table has a million files (~ 500 columns * 1000 parts, pretty average table) , then it will be more than million random I/O operations.
