### ISSUE TITLE
arrayMap unwraps tuples with a single element

### ISSUE THREAD

**Issue by jorisgio** [ClickHouse/ClickHouse#49781]
**Describe the unexpected behaviour**

```
SELECT arrayMap(e -> e, [tuple(NULL)])

Query id: 0acdde56-2f1e-43ea-8de5-b69a84465f15

┌─arrayMap(lambda(tuple(e), e), [tuple(NULL)])─┐
│ [NULL]                                       │
└──────────────────────────────────────────────┘
```

**How to reproduce**
* clickhouse version 23.4.2.1, it was returning tuple in 23.3

**Expected behavior**
ArrayMap with identity lamba should return an array of tuples, not an array of the tuple value.

**Comment by den-crane** [comment]
broken in 23.4

https://fiddle.clickhouse.com/64fc2276-031d-4352-b7d6-aa5fb9912541
