### ISSUE TITLE
Starting Clickhouse server 23.3.2.37 fails with Code: 173 exception

### ISSUE THREAD

**Issue by abhishekunotech** [ClickHouse/ClickHouse#49786]
I recently uninstalled 22.3.8.39 version on my Amazon Linux VM and instead installed 23.3.2.37 version. 

Setup worked fine with no errors. Starting the clickhouse server with the command

`sudo clickhouse start` 

fails with the exception below - 

`
Code: 173. DB::ErrnoException: MMappedFileDescriptor: Cannot mmap 30.00 B., errno: 19, strerror: No such device.
`

**How to reproduce**
Clickhouse Version: 23.3.2.37
OS Details:
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Command Used: sudo clickhouse start
All default settings.

**Expected behavior**
Clickhouse server should start.

**Error message and/or stacktrace**

```
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/listen.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
2023.05.11 13:07:02.071909 [ 6080 ] {} <Information> SentryWriter: Sending crash reports is disabled
2023.05.11 13:07:02.079917 [ 6080 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
Code: 173. DB::ErrnoException: MMappedFileDescriptor: Cannot mmap 30.00 B., errno: 19, strerror: No such device. (CANNOT_ALLOCATE_MEMORY), Stack trace (when copying this message, always include the lines below):

 (version 23.3.2.37 (official build))
2023.05.11 13:07:02.128777 [ 6081 ] {} <Trace> BaseDaemon: Received signal -2
2023.05.11 13:07:02.128846 [ 6081 ] {} <Information> BaseDaemon: Stop SignalListener thread

```

**Additional context**
Uninstalling 23.3.2.37 and reinstalling 22.3.8.39 works just fine.

**Comment by tavplubix** [comment]
> Stack trace (when copying this message, always include the lines below)

Please provide the stacktrace as well

**Comment by abhishekunotech** [comment]
> Please provide the stacktrace as well

Code: 173. DB::ErrnoException: MMappedFileDescriptor: Cannot mmap 30.00 B., errno: 19, strerror: No such device. (CANNOT_ALLOCATE_MEMORY), Stack trace (when copying this message, always include the lines below):

It just has the version line below - 

` 
(version 23.3.2.37 (official build))
`

**Comment by abhishekunotech** [comment]
Fix

`rm -rf /usr/lib/debug/usr/bin/clickhouse.debug`


Reference taken from #42480
