### ISSUE TITLE
The woboq browser finds some compiling issues, for example re2_st/re2.h

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#49845]
The codebrowser has been always finding issues in the code, but we ignored them.

Here's the report example https://s3.amazonaws.com/clickhouse-test-reports/49701/4dcdcf4c11b5604f1c5d3121c9c6fea3e957b605/woboq_build.html. In https://s3.amazonaws.com/clickhouse-test-reports/49701/4dcdcf4c11b5604f1c5d3121c9c6fea3e957b605/woboq_build/codebrowser_generator.log there are myriads of errors.

It would be nice to have them solved, I guess. Related to https://github.com/ClickHouse/ClickHouse/pull/49701

**Comment by rschu1ze** [comment]
RIP Woboq https://github.com/ClickHouse/ClickHouse/issues/50077#issuecomment-1807555621
