### ISSUE TITLE
Delegating grants to views

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#49849]
**Use case**

Create a view and give access to a user to the view without giving full access to the underlying tables.
Views can be used to restrict access to the underlying tables.

**Describe the solution you'd like**

```
CREATE VIEW ... WITH GRANT ...
```

If the user has particular grants, they can attach these grants to a view.
The grants will be provided to any user querying the view if the user has access to the view and only in the context of querying this view.

**Describe alternatives you've considered**

There are many alternative options, and this proposal is just one of them.

**Comment by vitlibar** [comment]
Good idea! It won't solve anything, but it definitely will make the life easier to start with.

I think internally providing grants to a view should be like providing grants to another user.
I mean we have commands
```
GRANT <privileges> ON <table> TO <anotheruser>
GRANT <roles> TO <anotheruser>
```
so we need to invent a command to grant privileges to a view.

**Comment by vitlibar** [comment]
Something like
```
CREATE VIEW view1 WITH GRANT(SELECT(x) ON tbl) AS SELECT x FROM tbl;
```
or
```
GRANT SELECT(x) ON tbl TO role1;
CREATE VIEW view1 WITH GRANT(role1) AS SELECT x FROM tbl;
```

**Comment by den-crane** [comment]
I don't understand why Clickhouse doesn't want to adopt owner/definer approach like almost all other databases.
It's not too late.
We can consider that all existing objects belong to "default" owner. Or to owner with a database name.

**Comment by vitlibar** [comment]
@den-crane
Yeah, probably you're right, we even already have a task for that: https://github.com/ClickHouse/ClickHouse/issues/19228

**Comment by karpoftea** [comment]
hi there! are there any plant to implement grants for views?

**Comment by vitlibar** [comment]
The work in progress, see https://github.com/ClickHouse/ClickHouse/pull/54901

**Comment by a-pono** [comment]
It would be awesome to have this feature!  With huge tables it's not possible to add all columns from other tables for filtering by row policy. Having materialized view per user also is very expensive in terms of storage.
