### ISSUE TITLE
UInt128 changed to some other value in client console query

### ISSUE THREAD

**Issue by dongxiao-yang** [ClickHouse/ClickHouse#49868]
Hi , I'm trying to store some ids in a UInt128 column for example value is `6236126411163181435228183259164671874` , but when later trying to apply a filter on this column it can not work looks like it's value get changed during process.

**How to reproduce**

```
CREATE TABLE default.test_UInt128
(
    `id_128` UInt128
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY id_128
SETTINGS index_granularity = 8192

insert into default.test_UInt128 values (toUInt128('6236126411163181435228183259164671874'))

SELECT
    id_128,
    toTypeName(id_128)
FROM default.test_UInt128

Query id: 78b17d55-3097-4bc6-9abb-058e4d067686

┌────────────────────────────────id_128─┬─toTypeName(id_128)─┐
│ 6236126411163181435228183259164671874 │ UInt128            │

```

so there is a value `6236126411163181435228183259164671874` in test table in column

Then try to apply a filter 

`select * from default.test_UInt128 where id_128 = 6236126411163181435228183259164671874` or  
`select * from default.test_UInt128  where id_128 = toUInt128(6236126411163181435228183259164671874)`
both got no record match .

A small test below showing ClickHouse are not treating value as UInt128 format and changed it's value even with toUInt128 converter 

```
select 6236126411163181435228183259164671874 as a , toTypeName(a) , toUInt128('6236126411163181435228183259164671874') as b , toTypeName(b) ,  toUInt128(6236126411163181435228183259164671874) as c , toTypeName(c);

SELECT
    6.236126411163181e36 AS a,
    toTypeName(a),
    toUInt128('6236126411163181435228183259164671874') AS b,
    toTypeName(b),
    toUInt128(6.236126411163181e36) AS c,
    toTypeName(c)

Query id: 0b85b255-c794-42e8-b006-18f1fc5843de

┌────────────────────a─┬─toTypeName(6.236126411163181e36)─┬─────────────────────────────────────b─┬─toTypeName(toUInt128('6236126411163181435228183259164671874'))─┬─────────────────────────────────────c─┬─toTypeName(toUInt128(6.236126411163181e36))─┐
│ 6.236126411163181e36 │ Float64                          │ 6236126411163181435228183259164671874 │ UInt128                                                        │ 6236126411163181046097152928288075008 │ UInt128                                     │ 
```

* Which ClickHouse server version to use 
ClickHouse server version 23.4.1 revision 54462
* Which interface to use, if matters 
ClickHouse client console

**Additional context**

> Add any other context about the problem here.

**Comment by tavplubix** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/38480
