### ISSUE TITLE
[ARM] Request to Specify ClickHouse Version during Installation

### ISSUE THREAD

**Issue by zenghuasheng** [ClickHouse/ClickHouse#49878]
RPM packages only support modern ARM cores, such as Graviton 2, 3.

For older ARM cores, install ClickHouse as follows:
```
curl https://clickhouse.com/ | sh
```

_Originally posted by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/49814#issuecomment-1546781571_

Dear alexey,

I hope this message finds you well. I recently installed ClickHouse 23.5.1 following the instructions provided, and I'm grateful for the guidance and support provided by the project.

I wanted to inquire about the possibility of specifying a particular version of ClickHouse during the installation process. Specifically, I am interested in installing version 23.2.4.12. I have reviewed the available documentation and configuration options, but I couldn't find a clear way to specify the desired version.

Could you please guide me on how to install a specific version of ClickHouse? It would be immensely helpful if you could provide instructions or point me to the relevant documentation or resources.

Thank you for your attention to this matter, and I appreciate the effort you have put into maintaining and improving ClickHouse. Your contributions have been invaluable to the community.

Best regards,
zenghuasheng

**Comment by alexey-milovidov** [comment]
Thank you for the kind words!

The installation steps are as follows:
1. Find the pull request for the particular release: https://github.com/ClickHouse/ClickHouse/pull/46793
2. Find the commit similar to [Update autogenerated version to 23.2.7.1 and contributors](https://github.com/ClickHouse/ClickHouse/pull/46793/commits/b460eb70bf29b19eadd19a1f959b15d186705394) related to the particular version.
3. Press the red cross to open the list of checks.
4. Find "ClickHouse Build Check" and press the "Details": https://s3.amazonaws.com/clickhouse-test-reports/46793/b460eb70bf29b19eadd19a1f959b15d186705394/clickhouse_build_check/report.html
5. Find the rows for compiler = clang-*-aarch64, build type = relwithdebuginfo, sanitizer = none - there are multiple rows.
6. Download the artifacts for these builds.
7. Extract the clickhouse binary.
8. Find a binary that is suitable for your architecture.

**Comment by rschu1ze** [comment]
A more "official" method compared to downloading binaries from CI is described [here](https://clickhouse.com/docs/en/install#from-tgz-archives) (adjust the version as needed, it installs ClickHouse for all users though). Packages of older versions are also available [here](https://github.com/ClickHouse/ClickHouse/releases).

**Comment by alexey-milovidov** [comment]
@rschu1ze, there are no packages for older ARM CPUs.

**Comment by zenghuasheng** [comment]
> Thank you for the kind words!
> 
> The installation steps are as follows:
> 
> 1. Find the pull request for the particular release: [Release pull request for branch 23.2 #46793](https://github.com/ClickHouse/ClickHouse/pull/46793)
> 2. Find the commit similar to [Update autogenerated version to 23.2.7.1 and contributors](https://github.com/ClickHouse/ClickHouse/pull/46793/commits/b460eb70bf29b19eadd19a1f959b15d186705394) related to the particular version.
> 3. Press the red cross to open the list of checks.
> 4. Find "ClickHouse Build Check" and press the "Details": https://s3.amazonaws.com/clickhouse-test-reports/46793/b460eb70bf29b19eadd19a1f959b15d186705394/clickhouse_build_check/report.html
> 5. Find the rows for compiler = clang-*-aarch64, build type = relwithdebuginfo, sanitizer = none - there are multiple rows.
> 6. Download the artifacts for these builds.
> 7. Extract the clickhouse binary.
> 8. Find a binary that is suitable for your architecture.

Thank you for your response! I really appreciate your help and will have a try. I'll let you know how it goes. Thanks again!

**Comment by zenghuasheng** [comment]
> A more "official" method compared to downloading binaries from CI is described [here](https://clickhouse.com/docs/en/install#from-tgz-archives) (adjust the version as needed, it installs ClickHouse for all users though). Packages of older versions are also available [here](https://github.com/ClickHouse/ClickHouse/releases).

Also thanks for your answer!

**Comment by rschu1ze** [comment]
> @rschu1ze, there are no packages for older ARM CPUs.

Tbh, I don't think we should provide packages for compat builds (x86 / ARM). They are IMHO in the same category as sanitizer builds and Debug builds - basically a development tool. Having packages for them would only address a very small audience and waste space.

I also thought about adding a `--version` flag to universal.sh. But assuming it is only a tool to get started quickly but (theoretically) not used for production, it's probably not worth it.

So instead, I updated the install docs here: #50359

**Comment by zhulu01** [comment]
> ```
>           RPM packages only support modern ARM cores, such as Graviton 2, 3.
> ```
> 
> For older ARM cores, install ClickHouse as follows:
> 
> ```
> curl https://clickhouse.com/ | sh
> ```
> 
> _Originally posted by @alexey-milovidov in [#49814 (comment)](https://github.com/ClickHouse/ClickHouse/issues/49814#issuecomment-1546781571)_
> 
> Dear alexey,
> 
> I hope this message finds you well. I recently installed ClickHouse 23.5.1 following the instructions provided, and I'm grateful for the guidance and support provided by the project.
> 
> I wanted to inquire about the possibility of specifying a particular version of ClickHouse during the installation process. Specifically, I am interested in installing version 23.2.4.12. I have reviewed the available documentation and configuration options, but I couldn't find a clear way to specify the desired version.
> 
> Could you please guide me on how to install a specific version of ClickHouse? It would be immensely helpful if you could provide instructions or point me to the relevant documentation or resources.
> 
> Thank you for your attention to this matter, and I appreciate the effort you have put into maintaining and improving ClickHouse. Your contributions have been invaluable to the community.
> 
> Best regards, zenghuasheng

大佬，clickhouse的这个资源页面报错，这个包能帮忙提供一下，非常感谢。
地址链接：https://s3.amazonaws.com/clickhouse-builds/23.2/b460eb70bf29b19eadd19a1f959b15d186705394/package_aarch64/clickhouse-client-23.2.7.1-arm64.tgz    
页面报错截图：
![image](https://github.com/ClickHouse/ClickHouse/assets/59040322/ca950694-1ebb-4c0e-808f-8aba8c87d931)

我的邮箱：237270020@qq.com
