### ISSUE TITLE
Lightweight delete does not inactive partition from system.parts

### ISSUE THREAD

**Issue by antip00** [ClickHouse/ClickHouse#49909]
version 23.3.2.37
Steps to follow:
1. Create table:
```CREATE TABLE qkrq  (id Int64, x Int64) Engine = MergeTree PARTITION BY id ORDER BY id```
2. Insert data into the table:
```INSERT INTO qkrq values (1,1), (2,2)```
3. Delete data from the table:
```DELETE FROM qkrq WHERE id = 1```
4. Force merge:
```OPTIMIZE TABLE qkrq FINAL```
5. Check partition 1 is inactive:
```select partition from system.parts where table='qkrq' and active=1```
returns:
```
┌─partition─┐
│ 1         │
│ 2         │
└───────────┘
```
data is deleted but partition without data is active

expected behavior:
only 2 partition is active

**Comment by tavplubix** [comment]
That's expected, `system.parts` shows some internal implementation-defined information. `select id from qkrq` will return only 2.

**Comment by den-crane** [comment]
It's only for a time while initial part exists.
https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#old-parts-lifetime

https://fiddle.clickhouse.com/271701ec-8378-4cb1-8d58-1c6cd7d51d68
(change old_parts_lifetime to see the difference)

The same behaviour with other engines  https://fiddle.clickhouse.com/271701ec-8378-4cb1-8d58-1c6cd7d51d68
