### ISSUE TITLE
Stress Test (debug): chassert() in DB::CacheMetadata::doCleanup()

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#49910]
[A link to the report
](https://s3.amazonaws.com/clickhouse-test-reports/49503/0d585746de23feee1b323b850f6c76331006e5c0/stress_test__debug_.html)

cc @kssenii

**Comment by kssenii** [comment]
duplicate of https://github.com/ClickHouse/ClickHouse/issues/49386
