### ISSUE TITLE
S3 Wildcard Issue When Using OR (Not usable)

### ISSUE THREAD

**Issue by warleysa** [ClickHouse/ClickHouse#49929]
There is an issue with performance when using the S3 Wildcard below.

**Clickhouse Versions Tested (We have about 20 total servers):** 
- clickhouse/clickhouse-server:23.4.2.11 
- clickhouse/clickhouse-server:23.1.3.5
- clickhouse/clickhouse-server:23.2.1.2537

**_Wildcard Used from Documentation:_** {some_string,another_string,yet_another_one} — Substitutes any of strings 'some_string', 'another_string', 'yet_another_one'

_**Without Wildcard:**_ 
- **Expected result:** Return all data under presto_data/config/bts_id=555251 folder (5 files, 4MB total)
- **S3 Path:** us-east-1.amazonaws.com/presto_data/config/bts_id=555251/*
- **Speed:** Finishes in about 1 second

_**With Wildcard:**_
- **Expected result:** Return all data under presto_data/config/bts_id=555251 folder (5 files, 4MB total) AND presto_data/config/bts_id=555256 folder (4 files, 3MB total)
- **S3 Path:** us-east-1.amazonaws.com/presto_data/config/bts_id=_**{555251,555256}**_/*
- **Speed:** Never Finishes; Memory Limit Error after about 150 seconds

Thanks!

**Comment by warleysa** [comment]
One note. The folder for "presto_data/config/" has about 20k-500k folders in it (depending on our customer). It might be trying to list all the folders before applying the {} wildcard. I guess I had expected it to be linear with the choices so it would only check for those 2 paths without a directory list. Hope that helps explain a little more.

**Comment by tavplubix** [comment]
The problem is that it lists all `bts_id`s (all keys with `presto_data/config/bts_id=` prefix) and only then tries to apply the regexp and find matching keys:
https://github.com/ClickHouse/ClickHouse/blob/7fbf87be176081411918ae35f040f338892d1416/src/Storages/StorageS3.cpp#L165-L182

However, it could only list `presto_data/config/bts_id=555251` and `presto_data/config/bts_id=555256` and it would be much more optimal

**Comment by warleysa** [comment]
> @warleysa : It lists folder/files with prefix "presto_data/config/bts_id=". Do you have 20k-500k folders with the same prefix? If yes, then it does list them all and try to match the glob.

Yes. We have that many folders with the same prefix there. It is partitioning in Parquet. Some of the larger folders have large sets of data. 

The suggestion from [tavplubix](https://github.com/tavplubix) seems to be the optimal approach that could be taken. 

Thanks all!

**Comment by MaheshGPai** [comment]
Any update on this?

**Comment by warleysa** [comment]
> Any update on this?
I am wondering about an update on this as well. We have been forced to use PrestoDB for Parquet data with such partitioning and then post process data in Python. This is leading to about 100x as much data being processed overall since we cannot use Clickhouse this to pre filter the data.

**Comment by SmitaRKulkarni** [comment]
@MaheshGPai @warleysa 
Unfortunately no updates, I plan to implement this shortly.

**Comment by MaheshGPai** [comment]
@SmitaRKulkarni any update on this?

**Comment by alexey-milovidov** [comment]
@MaheshGPai, currently no update, and the task is not in progress.
