### ISSUE TITLE
Unable to import IPv6 addresses using Protobuf

### ISSUE THREAD

**Issue by vincentbernat** [ClickHouse/ClickHouse#49924]
**Describe the issue**
Since version 23, it is not possible to directly import IPv6 addresses from Protobuf (as bytes). This was working fine with 22.3.

**How to reproduce**
In `/var/lib/clickhouse/format_schemas/flows.proto`:
```proto
syntax = "proto3";
message FlowMessage {
bytes ExporterAddress = 3;
}
```

Create a table:
```sql
CREATE TABLE default.flows
(
    `ExporterAddress` IPv6
)
ENGINE = MergeTree
ORDER BY ExporterAddress
SETTINGS index_granularity = 8192
```

Insert using Protobuf format:
```console
$ echo <intentionally removed - could contain sensitive user information> | xxd -r -p | clickhouse clickhouse-client -q "INSERT INTO flows SETTINGS format_schema='/var/lib/clickhouse/format_schemas/flows.proto:FlowMessage' FORMAT Protobuf"
Code: 676. DB::ParsingException: Cannot parse IPv6 : While executing ProtobufRowInputFormat: data for INSERT was parsed from stdin: (in query: INSERT INTO flows SETTINGS format_schema='/var/lib/clickhouse/format_schemas/flows.proto:FlowMessage' FORMAT Protobuf): (in file/uri (fd = 0)): (at row 1)
. (CANNOT_PARSE_IPV6)
```

When using 22.3, there is no error:
```
369034ef06d4 :) select * from flows

SELECT *
FROM flows

Query id: b31771a4-b1a6-442e-a9eb-84bc7b944036

┌─ExporterAddress──────┐
│ ::ffff:192.168.0.254 │
└──────────────────────┘

1 row in set. Elapsed: 0.002 sec.
```

This is still reproducible with master.

**Comment by yakov-olkhovskiy** [comment]
@vincentbernat 
I'm not sure how it worked in 22.3 (there were some changes regarding IP types since then), but this protobuf message doesn't look like a correct FlowMessage - `protoc` also failed to decode it:
```
$ echo 01D00207C802E409B802AAE503C002BB03B00206A802DD8D0232046564676542096175737472616C69614A096B6F62617961736869D2010C7366702D736670706C757331E2011C506F72743A204675747572652042726F616462616E64202857414E29A00202CA010D7366702D736670706C75733132DA010E506F72743A2057692D466920415098020292010241559A010241552214676174657761792E6B6F626179617368692E6175E801E807F001E80708C9C586A30610041A1000000000000000000000FFFFC0A800FE70F93A78C17652102404BF40C2040000552CF311EEFDECCE5A1024046800400608040000000000002005 | xxd -r -p | protoc --decode=FlowMessage flows.proto
Failed to parse input.
```
could you provide more context please? where you got this message from?

**Comment by vincentbernat** [comment]
The varint at the beginning for length is the two first bytes.
```
 22:50 ❱ echo D00207C802E409B802AAE503C002BB03B00206A802DD8D0232046564676542096175737472616C69614A096B6F62617961736869D2010C7366702D736670706C757331E2011C506F72743A204675747572652042726F616462616E64202857414E29A00202CA010D7366702D736670706C75733132DA010E506F72743A2057692D466920415098020292010241559A010241552214676174657761792E6B6F626179617368692E6175E801E807F001E80708C9C586A30610041A1000000000000000000000FFFFC0A800FE70F93A78C17652102404BF40C2040000552CF311EEFDECCE5A1024046800400608040000000000002005 | xxd -r -p | protoc --decode=FlowMessage flows.proto
ExporterAddress: "\000\000\000\000\000\000\000\000\000\000\377\377\300\250\000\376"
```

**Comment by yakov-olkhovskiy** [comment]
ok
seems previously we treated protobuf bytes for IPv6 as binary but now it is trying to parse it as a string... will fix it

**Comment by den-crane** [comment]
I suspect Clickhouse `select ... format Protobuf` can generate the the same.

**Comment by yakov-olkhovskiy** [comment]
> please avoid disclosing more of it

I removed user data in comments...

**Comment by vincentbernat** [comment]
I don't think this is a problem as long as the data is "encoded". It's just not casually visible by a search engine. I was just warning that it would be best not to display it in clear text (with a complete output of protoc for example).

**Comment by yu-re-ka** [comment]
CC @fionera is this related to changes you had to make in netmeta when upgrading to 23.x and can any 'hacks' be reverted once this is fixed?

**Comment by fionera** [comment]
> CC @fionera is this related to changes you had to make in netmeta when upgrading to 23.x and can any 'hacks' be reverted once this is fixed?
> 
> like [monogon-dev/NetMeta@9e959c4](https://github.com/monogon-dev/NetMeta/commit/9e959c4f80af520a4b276e19cb098d8d529f23d1)

Yep this sounds like it
