### ISSUE TITLE
Code: 62. DB::Exception: Syntax error: failed at position ... Expected one of: AS, EXCEPT TABLE, EXCEPT TABLES, token, Comma, ON, TO. (SYNTAX_ERROR)

### ISSUE THREAD

**Issue by cansayin** [ClickHouse/ClickHouse#49920]
Hi all,

I receive following error after running command below.

clickhouse-client --user="$clickhouse_user" --password="$clickhouse_password" --host="$clickhouse_host" --port="$clickhouse_port" --query="BACKUP DATABASE ${database_name} TO Disk('backups','${database_name}.${branch_name}.zip')" 

Code: 62. DB::Exception: Syntax error: failed at position 21 ('Disk'): Disk('backups','..zip'). Expected one of: AS, EXCEPT TABLE, EXCEPT TABLES, token, Comma, ON, TO. (SYNTAX_ERROR)

Even i delete the database and branch name from command and give backup name as "test" but didnt work.

clickhouse-client --user="$clickhouse_user" --password="$clickhouse_password" --host="$clickhouse_host" --port="$clickhouse_port" --query="BACKUP DATABASE ${database_name} TO Disk('backups','test.zip')" 

Code: 62. DB::Exception: Syntax error: failed at position 21 ('Disk'): Disk('backups','test.zip'). Expected one of: AS, EXCEPT TABLE, EXCEPT TABLES, token, Comma, ON, TO. (SYNTAX_ERROR)

Could someone can help me for this issue?
 Thanks

**Comment by cansayin** [comment]
Hi,

Sure.

root@9c8c4daf105e:~# clickhouse-client
ClickHouse client version 23.4.2.11 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.4.2 revision 54462.

Btw, same command line works on my previous script.

Thanks

**Comment by den-crane** [comment]
works for me
```
database_name=ddd; clickhouse-client --query="BACKUP DATABASE ${database_name} TO Disk('backups','test.zip')"
Received exception from server (version 23.5.1):
Code: 318. DB::Exception: Received from localhost:9000. DB::Exception: The 'backups.allowed_disk' configuration parameter is not set, cannot use 'Disk' backup engine. (INVALID_CONFIG_PARAMETER)
(query: BACKUP DATABASE ddd TO Disk('backups','test.zip'))
```

**Comment by al13n321** [comment]
`database_name` and `branch_name` are empty or unset, as can be seen from the error message: `Disk('backups','..zip')`, expanded from `Disk('backups','${database_name}.${branch_name}.zip')`

**Comment by devopscloudnexus** [comment]
I have a similar error on clickhouse 23.4.4.16.
```
backup all databases on cluster 'test' to S3('https://test-clickhouse-backup.s3.amazonaws.com/my_backup_02', 'AKIAXXXX', 'XXXX')

Syntax error: failed at position 12 ('databases'):
Expected one of: EXCEPT DATABASE, EXCEPT DATABASES, EXCEPT TABLE, EXCEPT TABLES, token, Comma, ON, TO
```

**Comment by al13n321** [comment]
@vitlibar: ^   I see that the documentation says "BACKUP ALL DATABASES [...]" is a valid query, but ParserBackupQuery.cpp doesn't seem to accept it.
