### ISSUE TITLE
How to trigger a full update in dictionary?

### ISSUE THREAD

**Issue by lee3164** [ClickHouse/ClickHouse#49936]
Hello, I'm using clickhouse dictionary now, I've confugured a http source dictionary, like this:
```
create dictionary if not exists user_attrs
(
    uid UInt64,
    city UInt64
    sex uint8
)
primary key uid
source ( HTTP(url 'http://xxx' format 'TabSeparated' update_field 'update_time') ) 
layout ( HASHED_ARRAY())
lifetime ( 5);
```
with the update_filed, I could do incremental update when our some users change their address. 
But I have some question about dictionary:
1. How to delete entries in dictionary? for example, one user deregisters his account, so the record related to him is no longer useful. How to do garbage collection?
2. Sometimes, I want to do a full update of this dictionary, how to do it?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/statements/system#reload-dictionaries
