### ISSUE TITLE
 DELETE query is not supported

### ISSUE THREAD

**Issue by MurderWind** [ClickHouse/ClickHouse#49946]
> You have to provide the following information whenever possible.

**Describe what's wrong**
 DELETE query is not supported on cluster
> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**
   yes

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**
CREATE TABLE if not exists default.DEMO_LOCAL on cluster demo
(
id Int64,
stu_code Int32,
stu_name String,
total_cnt Int64,
update_time DateTime
)
Engine=ReplicatedReplacingMergeTree(update_time)
PARTITION BY toYYYYMM(update_time)
ORDER BY (id);

CREATE TABLE if not exists default.DEMO_ALL on cluster demo
as default.DEMO_LOCAL
ENGINE = Distributed(demo, default, DEMO_LOCAL, intHash64(id));

insert into default.DEMO_ALL values (2, 5001, 'shenzhan1', 55002, 'TLM',timestamp '2023-04-22 15:02:53.000');
insert into default.DEMO_ALL values (2, 5001, 'shenzhan1', 55002, 'TLM',CURRENt_timestamp);
insert into default.DEMO_ALL values (2, 5001, 'shenzhan1', 55002, 'TLM',timestamp '2023-04-20 15:02:53.000');

DELETE FROM default.DEMO_ALL ON CLUSTER demo where id in (2)

* Which ClickHouse server version to use
  ClickHouse Server version: 23.3.1.2823

* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
 delete enabled

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**
 DELETE query is not supported

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
Clickhouse does not support DELETE against Distributed tables. You should use DEMO_LOCAL instead.


```sql
DELETE FROM default.DEMO_LOCAL ON CLUSTER demo where id in (2)
```
