### ISSUE TITLE
Segmentation fault when adding a JSON column

### ISSUE THREAD

**Issue by DenisGee** [ClickHouse/ClickHouse#49944]
Hello everyone

**Describe what's wrong**

So, when I add JSON column with default statement in existing table and try to select data from it I get a clickhouse crash (Segmentation fault)

**Does it reproduce on recent release?**

Yes

**How to reproduce**

```
CREATE TABLE testJson
(
	i Int8,
	jString String
) ENGINE = MergeTree
ORDER BY i;

INSERT INTO testJson (i, jString)
SELECT 1, '{"a":"123"}';

ALTER TABLE testJson ADD COLUMN j2 JSON default jString;

SELECT *
FROM testJson;
```

**Expected behavior**

Adding a JSON column without the Segmentation fault

**Error message and/or stacktrace**

stacktrace from crash_log
2. DB::SerializationNumber<char8_t>::serializeBinary(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const @ 0x8a704c3 in /usr/bin/clickhouse','
3. DB::SerializationTuple::serializeBinary(DB::IColumn const&, unsigned long, DB::WriteBuffer&, DB::FormatSettings const&) const @ 0x12e21c73 in /usr/bin/clickhouse','
4. DB::IRowOutputFormat::write(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) @ 0x14d46043 in /usr/bin/clickhouse','
5. DB::IRowOutputFormat::consume(DB::Chunk) @ 0x14d45d6e in /usr/bin/clickhouse','
6. DB::ParallelFormattingOutputFormat::formatterThreadFunction(unsigned long, unsigned long, std::shared_ptr<DB::ThreadGroup> const&) @ 0x14e5637e in /usr/bin/clickhouse','
7. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe48d6d5 in /usr/bin/clickhouse','
8. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe48ff15 in /usr/bin/clickhouse','
9. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe489501 in /usr/bin/clickhouse','
10. ? @ 0xe48ed81 in /usr/bin/clickhouse','
11. start_thread @ 0x7fa3 in /usr/lib/x86_64-linux-gnu/libpthread-2.28.so','
12. clone @ 0xf906f in /usr/lib/x86_64-linux-gnu/libc-2.28.so']	ClickHouse 23.4.1.1943

<img width="532" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/110493658/3f03af98-2715-4a17-9f19-ab72f016486c">

If anyone has problems with starting up clickhouse-server because the error you have to erase from clickhouse metadata the line about added column (and after starting up recreate the table, if its Replicated)

**Comment by alexey-milovidov** [comment]
> So, when I add JSON column

ClickHouse does not support JSON columns, as pointed out in the docs: https://clickhouse.com/docs/en/sql-reference/data-types/json
