### ISSUE TITLE
JSON parser interpret large whole numbers as doubles

### ISSUE THREAD

**Issue by SupaHam** [ClickHouse/ClickHouse#49949]
> You have to provide the following information whenever possible.

All JSON parsing silentely fails when clickhouse attempts to parse a double number (-57783588950605040000) as an integer.

> A clear and concise description of what works not as it is supposed to.

JSON parser should fallback to double when the number is larger than int64.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**
Yes,

```
VERSION_FULL,ClickHouse 23.4.2.11
VERSION_DESCRIBE,v23.4.2.11-stable
VERSION_INTEGER,23004002
SYSTEM,Linux
VERSION_GITHASH,b6442320f9dc85d127bfaf84febe76e9294b2407
VERSION_REVISION,54473
VERSION_DATE,
BUILD_TYPE,RelWithDebInfo
SYSTEM_PROCESSOR,x86_64
CMAKE_VERSION,3.26.3
C_COMPILER,/usr/bin/clang-15
C_COMPILER_VERSION,15.0.7
CXX_COMPILER,/usr/bin/clang++-15
CXX_COMPILER_VERSION,15.0.7
C_FLAGS, --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fexperimental-new-pass-manager -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -flto=thin -fwhole-program-vtables -fno-pie
CXX_FLAGS, --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=.=. -falign-functions=32 -mbranches-within-32B-boundaries -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-c++20-compat -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-ctad-maybe-unsupported -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-double-promotion -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-prototypes -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-vla -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -flto=thin -fwhole-program-vtables -fno-pie
LINK_FLAGS," --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=.._docker/ld.lld -rdynamic -Wl,--gdb-index -Wl,--build-id=sha1 -no-pie -Wl,-no-pie  -flto=thin -fwhole-program-vtables"
BUILD_COMPILE_DEFINITIONS,
USE_EMBEDDED_COMPILER,1
USE_GLIBC_COMPATIBILITY,ON
USE_JEMALLOC,ON
USE_UNWIND,ON
USE_ICU,1
USE_H3,1
USE_MYSQL,1
USE_RDKAFKA,1
USE_CAPNP,1
USE_BASE64,1
USE_HDFS,1
USE_SNAPPY,1
USE_PARQUET,1
USE_PROTOBUF,1
USE_BROTLI,1
USE_SSL,1
OPENSSL_VERSION,1.1.1g
OPENSSL_IS_BORING_SSL,1
USE_VECTORSCAN,ON
USE_SIMDJSON,1
USE_ODBC,1
USE_GRPC,1
USE_LDAP,1
TZDATA_VERSION,2023c
USE_KRB5,1
USE_FILELOG,1
USE_BZIP2,1
USE_AMQPCPP,1
USE_ROCKSDB,1
USE_NURAFT,1
USE_NLP,1
USE_LIBURING,1
USE_SQLITE,1
USE_LIBPQXX,1
USE_AZURE_BLOB_STORAGE,1
USE_AWS_S3,1
USE_CASSANDRA,1
USE_YAML_CPP,1
USE_SENTRY,1
USE_DATASKETCHES,1
USE_AVRO,1
USE_ARROW,1
USE_ORC,1
USE_MSGPACK,1
GIT_HASH,b6442320f9dc85d127bfaf84febe76e9294b2407
GIT_BRANCH,23.4
GIT_DATE,2023-05-02 06:58:35 +0000
GIT_COMMIT_SUBJECT,Merge pull request #49375 from ClickHouse/backport/23.4/48765
```
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**
`select '{"foo": -57783588950605040000}' as data, JSONExtractString(data, 'foo') as bar;`

**Expected behavior**

> A clear and concise description of what you expected to happen.

Expecting `bar` to contain "-57783588950605040000". Returns empty value.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

No error messages and/or stacktraces

**Additional context**

Importing large volume of data using s3 and i get faulty final states of half inserted data and having to comb through each row to find where the json parsing has failed for the cause of error.

A solution to this problem is to forcibly set the number as decimal, but as mentioned this data is in s3 (backups) and i would need to modify each of the faulty json blobs externally to get clickhouse to interpret the large number as a double. It would be ideal if there was at least a setting that made the json parser more relaxed and understanding instead of completely failing. The current context of my use is an ingest table that extracts a few key columns for efficiency, but as it stands the s3 import fails because it fails to parse an 'empty' date.

`select '{"foo": -57783588950605040000.0}' as data, JSONExtractString(data, 'foo') as bar;`
Returns
bar as `-57783588950605040000`

**Comment by Algunenano** [comment]
Works fine without simdjson:

```
:) select '{"foo": -57783588950605040000}' as data, JSONExtractString(data, 'foo') as bar settings allow_simdjson=1

SELECT
    '{"foo": -57783588950605040000}' AS data,
    JSONExtractString(data, 'foo') AS bar
SETTINGS allow_simdjson = 1

Query id: fbfaca44-bc66-4498-afc3-141e991b3009

┌─data───────────────────────────┬─bar─┐
│ {"foo": -57783588950605040000} │     │
└────────────────────────────────┴─────┘

1 row in set. Elapsed: 0.001 sec. 

:) select '{"foo": -57783588950605040000}' as data, JSONExtractString(data, 'foo') as bar settings allow_simdjson=0

SELECT
    '{"foo": -57783588950605040000}' AS data,
    JSONExtractString(data, 'foo') AS bar
SETTINGS allow_simdjson = 0

Query id: 5e57e447-4731-43bc-9502-9e2c90605902

┌─data───────────────────────────┬─bar───────────────────┐
│ {"foo": -57783588950605040000} │ -57783588950605040000 │
└────────────────────────────────┴───────────────────────┘

1 row in set. Elapsed: 0.000 sec. 

```

**Comment by SupaHam** [comment]
Apologies. Closing now.

**Comment by den-crane** [comment]
this number does not fit into UInt64 BWT  -57783588950605040000

```
select toUInt64(-1)/2;
9223372036854776000

select toUInt64(-1);
18446744073709551615
```

**Comment by SupaHam** [comment]
The number is a pitch float64 rotational value, which in itself is not a reasonable number in the environment of this data.

**Comment by SupaHam** [comment]
> Works fine without simdjson:
> 
> ```
> :) select '{"foo": -57783588950605040000}' as data, JSONExtractString(data, 'foo') as bar settings allow_simdjson=1
> 
> SELECT
>     '{"foo": -57783588950605040000}' AS data,
>     JSONExtractString(data, 'foo') AS bar
> SETTINGS allow_simdjson = 1
> 
> Query id: fbfaca44-bc66-4498-afc3-141e991b3009
> 
> ┌─data───────────────────────────┬─bar─┐
> │ {"foo": -57783588950605040000} │     │
> └────────────────────────────────┴─────┘
> 
> 1 row in set. Elapsed: 0.001 sec. 
> 
> :) select '{"foo": -57783588950605040000}' as data, JSONExtractString(data, 'foo') as bar settings allow_simdjson=0
> 
> SELECT
>     '{"foo": -57783588950605040000}' AS data,
>     JSONExtractString(data, 'foo') AS bar
> SETTINGS allow_simdjson = 0
> 
> Query id: 5e57e447-4731-43bc-9502-9e2c90605902
> 
> ┌─data───────────────────────────┬─bar───────────────────┐
> │ {"foo": -57783588950605040000} │ -57783588950605040000 │
> └────────────────────────────────┴───────────────────────┘
> 
> 1 row in set. Elapsed: 0.000 sec. 
> ```

thanks for the info. It looks like it runs about half slower, but i was able to chain multiple files using UNION ALL for double performance again :D
