### ISSUE TITLE
UNKNOWN_TYPE exception in client doesn't go away in subsequent queries

### ISSUE THREAD

**Issue by hkrutzer** [ClickHouse/ClickHouse#49940]
**Describe what's wrong**

```
local :) SELECT generateUUIDv4() FORMAT Arrow;

SELECT generateUUIDv4()
FORMAT Arrow

Query id: a36c025b-5e6a-4b2f-8df7-0f782e550171

Exception on client:
Code: 50. DB::Exception: The type 'UUID' of a column 'generateUUIDv4()' is not supported for conversion into Arrow data format. (UNKNOWN_TYPE)

local :) SELECT 1;

SELECT 1

Exception on client:
Code: 50. DB::Exception: The type 'UUID' of a column 'generateUUIDv4()' is not supported for conversion into Arrow data format. (UNKNOWN_TYPE)

local :) SELECT 1 FORMAT CSV;

SELECT 1
FORMAT CSV

Exception on client:
Code: 50. DB::Exception: The type 'UUID' of a column 'generateUUIDv4()' is not supported for conversion into Arrow data format. (UNKNOWN_TYPE)
```

**Does it reproduce on recent release?**

ClickHouse client version 23.4.2.11 (official build).
Connected to ClickHouse server version 23.4.1 revision 54462.

**How to reproduce**
See above

**Expected behavior**

Subsequent queries that use a different format should work

**Additional context**

Same happens with Parquet

**Comment by s71m** [comment]
hello! 
I suppose this error still actual for format Arrow

SELECT generateUUIDv4() FORMAT Arrow;
or
SELECT * FROM <some_table>  FORMAT Arrow
 Code: 50. DB::Exception: The type 'UUID' of a column 'uid' is not supported for conversion into Arrow data format.: While executing ArrowBlockOutputFormat. (UNKNOWN_TYPE) (version 24.10.1.2812 (official build))
