### ISSUE TITLE
Query Performance of SSB Regressed by 18%

### ISSUE THREAD

**Issue by ZhiguoZh** [ClickHouse/ClickHouse#49965]
**Describe the situation**
Compared with [1cbdba0](https://github.com/ClickHouse/ClickHouse/commit/1cbdba037825413c4bde48371298dda9b4ecd2da), a commit on Apr 25th, the QPS of SSB workload has regressed by **~18%** on the latest ClickHouse [3d26232](https://github.com/ClickHouse/ClickHouse/commit/3d26232cc0ceb4e7e0901526e6d733501990815a). The following table lists the detailed regression rate of each sub-query and the geomean of the QPS.

![image](https://github.com/ClickHouse/ClickHouse/assets/26588299/2f4c96d8-49fa-4fea-8103-382903acfb1c)
Fig 1. The performance loss of all queries leads to an overall regression of 18% 

**How to reproduce**
* Which ClickHouse server version to use
We took [1cbdba0](https://github.com/ClickHouse/ClickHouse/commit/1cbdba037825413c4bde48371298dda9b4ecd2da) as the baseline, and compared the QPS on [3d26232](https://github.com/ClickHouse/ClickHouse/commit/3d26232cc0ceb4e7e0901526e6d733501990815a) with it.
* Which machine is used for the performance tests
ICX server (Intel Xeon Platinum 8380 CPU, 80 cores, 160 threads)
* How to generate the data and what are the queries that lead to slow performance
We followed the [official document of SSB workload](https://clickhouse.com/docs/en/getting-started/example-datasets/star-schema) for generating data, creating schema, inserting data and defining the SQL queries. A scale factor of **100** is used in generating the data. **All** of the 13 sample queries are found low-performance compared with the baseline, [1cbdba0](https://github.com/ClickHouse/ClickHouse/commit/1cbdba037825413c4bde48371298dda9b4ecd2da), as Fig 1 shows.
* How to collect the performance metrics
The [clickhouse-benchmark](https://clickhouse.com/docs/en/operations/utilities/clickhouse-benchmark) serves as the client for sending SQL queries to the server and measures the QPS in **10 seconds**. Each query would be executed for **5 times** and average QPS is taken as the sub-score. The geomean of all sub-scores is the total score.

**Expected performance**
Recover the performance to a comparable level of [1cbdba0](https://github.com/ClickHouse/ClickHouse/commit/1cbdba037825413c4bde48371298dda9b4ecd2da).

**Performance issue analysis**
Q1.1 is taken as a specific example for the analysis.

As is shown in Fig 2, the most obvious change of hotspots is from **_native_queued_spin_lock_slowpath_**, which is a spin lock for constructing critical sections in the kernel. In the earlier version, this function only accounted for **~9%** (ThreadPool + ThreadPoolRead) of the total cycles. However, when it comes to the latest version, it has significantly increased to **~50%**(ThreadPool + ThreadPoolRead).
![image](https://github.com/ClickHouse/ClickHouse/assets/26588299/9c038416-834d-4bf4-94f5-4eb0dca9a3ec)
Fig 2. The hotspots of CPU cycles in earlier (upper) and latest (bottom) versions of ClickHouse

The kernel stack of **_native_queued_spin_lock_slowpath_** (Fig 3) shows that this function, which suggests the severeness of lock contention in the kernel, is led by the system calls of **_sys_rt_sigaction, sys_timer_create, sys_timer_settime_**. On the other side, its user stack (Fig 4) denotes these system calls are issued from **_DB::QueryProfilerBase<DB::QueryProfilerCPU>::QueryProfilerBase_**, which initialize the query profiler of a thread by creating and configuring the timers. 

![image](https://github.com/ClickHouse/ClickHouse/assets/26588299/efc0f0ed-7af8-4f93-adaf-4f0e40c8d507)
Fig 3. Kernel stack of native_queued_spin_lock_slowpath

![image](https://github.com/ClickHouse/ClickHouse/assets/26588299/b0431fb8-7dac-4f1f-99b7-fc0f260a4141)
Fig 4. User stack of native_queued_spin_lock_slowpath

Then why the cycles on **_native_queued_spin_lock_slowpath_** surged in recent versions of ClickHouse? The call count of **_DB::QueryProfilerBase<DB::QueryProfilerCPU>::QueryProfilerBase_** might be sufficient for explaining it. When executing Q1.1 for only once, as Fig 5 shows, on the latest version of ClickHouse, the call count of QueryProfilerBase is enhanced by **3x** compared with the earlier one, and this will no doubt increase the invocations of the system calls and intensify the lock contentions in kernel. It could be inferred that a recent commit may have optimized the thread pool so that there are more threads available for executing the queries. However, when they attach themselves to the thread groups, they are forced to initialize their query profilers, which results in the high cycle-ratio of **_native_queued_spin_lock_slowpath_**.

![image](https://github.com/ClickHouse/ClickHouse/assets/26588299/4cd4dd63-49ed-422c-9ab9-58da218c6c17)
Fig 5. The call count of QueryProfilerBase in earlier (upper) and latest (bottom) versions of ClickHouse

**Proposed solution and performance impact**
Maybe we could turn to maintain the per-thread timers instead of creating and deleting them whenever a thread is added to a new group, considering that the cost of timer creation and deletion is so high. Fortunately, we identified an earlier PR, #48778, which has achieved what we intended to. We could observe in Fig 6, all of the queries benefits from this optimization, some of them even got improved by **~30%** and the overall QPS could be significantly improved by **~18%**. This performance regression could be recovered by the solution in #48778.

![image](https://github.com/ClickHouse/ClickHouse/assets/26588299/bff58a44-85b7-4c02-9ba5-d60f73b04656)
Fig 6. PR #48778 recovered the performance loss

**Comment by nickitat** [comment]
thank you for bringing out attention, it is sad that we overlooked this pr.
I also noticed some strange overhead from cpu profiler. as a workaround it was enough to `set query_profiler_cpu_time_period_ns = 0, query_profiler_real_time_period_ns = 0`

**Comment by jiebinn** [comment]
> 

Hi @nickitat , thanks you to review the PR. I have ever made a PR to disable the query profiler by default #43463 . But I also think the always-on query profiler is an excellent feature in clickhouse and we could not simply close it. The user also might not be aware of it. 
Instead, we could mitigate the big global timer overhead by maintaining per-thread timer_id rather than create/delete frequently.

**Comment by ZhiguoZh** [comment]
Hi Nikita, thanks so much for your quick response and for driving the fix of this performance issue. It really helps us a lot!

And I've confirmed the performance impact of this merged PR on my machine, which shows an overall QPS improvement of **17.7%** (details in the following figure).
![image](https://github.com/ClickHouse/ClickHouse/assets/26588299/5a0a05d3-c555-4da3-a25c-3cacc244d453)

I will close this issue as the performance has almost recovered. Thanks again for your effort!
