### ISSUE TITLE
Clickhouse stuck my server

### ISSUE THREAD

**Issue by asurovenko-zeta** [ClickHouse/ClickHouse#49963]
I successfully started my ClickHouse server and start to get data on it. And after a while, after about 250 Gb data my server completely frozen. I can't enter on in throught ssh even. After reboot I my server handled additional few megabytes of data and I entered to in using ssh, but after few second server again completely frozen.
I believe it's something like system limits, something like limit of files descriptors or so.
Can you support me to find a problem? What topics should I read to tweak my system to work with ClickHouse?
I using **AWS EC2 m5.xlarge** with **Centos 8** on it.

**Comment by asurovenko-zeta** [comment]
I have got metrics from server and realise that server stuck on **busy iowait**
What can it be?

**Comment by den-crane** [comment]
Check hardware/replace server , check swap / disable swap.
