### ISSUE TITLE
数据同步到clickhouse 到时候任务没有失败，数据丢失了很多

### ISSUE THREAD

**Issue by qiuyanCqy** [ClickHouse/ClickHouse#49974]
任务报错如下：
<Error> executeQuery: Code: 33. DB::Exception: Cannot read all data. Bytes read: 4090. Bytes expected: 12413.: While executing ParallelParsingBlockInputFormat. (CANNOT_READ_ALL_DATA) (version 22.11.1.1360 (official build))
从一个时序数据库读取到clickhouse,clickhouse 的引擎没有折叠

报错如下：
<img width="479" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/131990172/b461465f-19f6-4355-89db-d8d795be6d8e">

**Comment by den-crane** [comment]
It looks like the inserted data is incorrect and ClickHouse is unable to parse it.

22.11 is out of support. You should upgrade to 23.4

Try to disable parallel parsing, it helps to identify the issue in the input data `input_format_parallel_parsing=0`

**Comment by qiuyanCqy** [comment]
At present, it is caused by network problems. Can the error of upgrading to 23 be solved? Is the problem of data loss in data transmission?

**Comment by yedelong** [comment]
I also encountered this issue when inserting data. Have you resolved it? （cannot read all data.bytes read: 861993. Bytes expected: 10010058）May I ask how to solve this reading problem?

**Comment by yedelong** [comment]
I imported a batch of data into the cluster and frequently encountered the error 'cannot read all data'. I don't know how to solve it

**Comment by yedelong** [comment]
[![微信图片_20231023174952](https://github.com/ClickHouse/ClickHouse/assets/75054677/fb5211d0-eef6-4700-a2f1-36dfb8669b42)](url)
