### ISSUE TITLE
Schema reading or inference for PostgreSQL Table Engine (and potentially other similar Table Engines)

### ISSUE THREAD

**Issue by thomoco** [ClickHouse/ClickHouse#49972]
**Use case**
When using the PostgreSQL Table Engine (and perhaps similarly other Table Engines), the schema from the source PostgreSQL database table should be inferred or mapped directly over to ClickHouse.

**Describe the solution you'd like**
The PostgreSQL Database Engine already uses "DESCRIBE TABLE" to get the real-time table structure from the source PostgreSQL database:
https://clickhouse.com/docs/en/engines/database-engines/postgresql

It would be helpful if the PostgreSQL Table Engine would also use the same schema reading process. This would allow users to perform a CREATE TABLE...ENGINE = PostgreSQL without having to define the table schema as they do today, and ease the connection or synchronization to PostgreSQL tables.

This would allow a simpler CREATE TABLE statement that would look a lot like the existing CREATE DATABASE...ENGINE = PostgreSQL statement (except CREATE TABLE...):
https://clickhouse.com/docs/en/engines/database-engines/postgresql#creating-a-database

**Describe alternatives you've considered**
Not aware of alternatives. Using schema reading or inference wherever possible is helpful for users.

**Additional context**
n/a

**Comment by evillique** [comment]
As a workaround, it seems like `CREATE TABLE t AS postgresql(...)` [syntax](https://clickhouse.com/docs/en/sql-reference/statements/create/table#from-a-table-function) should work
