### ISSUE TITLE
two `Werror` failures

### ISSUE THREAD

**Issue by yu-re-ka** [ClickHouse/ClickHouse#49988]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**

NixOS Linux aarch64, kernel 6.2.0-asahi

**Cmake version**

3.25.3

**Ninja version**

1.11.1

**Compiler name and version**

clang 15.0.7

**Full cmake and/or ninja output**

https://logs.ofborg.org/?attempt_id=25e6840a-4209-4af5-b31a-5a5b0e338a12&key=nixos%2Fnixpkgs.232612

Now I have set `-DWERROR=OFF` to work around this, but without that each of these warnings will fail the build:

```
[40/10573] Building C object base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/glibc-compatibility.c.o
/build/source/base/glibc-compatibility/glibc-compatibility.c:167:21: warning: attribute declaration must precede definition [-Wignored-attributes]
void __attribute__((__weak__)) explicit_bzero(void * buf, size_t len)
                    ^
/nix/store/zpk0j9a40g36fhkv3ksa3ndv2ld8g943-glibc-2.37-8-dev/include/bits/string_fortified.h:70:8: note: previous definition is here
__NTH (explicit_bzero (void *__dest, size_t __len))
       ^
1 warning generated.
```

and later on:

```
[9300/10573] Building CXX object src/CMakeFiles/dbms.dir/Coordination/Changelog.cpp.o
/build/source/src/Coordination/Changelog.cpp:282:13: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
            ftruncate(file_buffer->getFD(), initial_file_size + file_buffer->count());
            ^~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by alexey-milovidov** [comment]
We build with clang-16, not clang-15.
The full build logs can be found here: https://s3.amazonaws.com/clickhouse-test-reports/0/a2c3de50820996549e975a0aceeb398ccc2897b5/clickhouse_build_check/report.html

**Comment by alexey-milovidov** [comment]
Not checking the return value of ftruncate is a real offense, now we have to also figure out why this does not produce a warning in the CI.

**Comment by Algunenano** [comment]
> Not checking the return value of ftruncate is a real offense, now we have to also figure out why this does not produce a warning in the CI.

Is seems glibc only enables the warning if `if __USE_FORTIFY_LEVEL > 0`. Seeing the other error (`string_fortified.h`) I'm guessing nix's defaults to enabling fortifying somehow

**Comment by yu-re-ka** [comment]
Can we also figure out `warning: attribute declaration must precede definition [-Wignored-attributes]` ? I tested again with the master branch and clang 16, and this still errors out unless I disable fortify.
Also, would you consider enabling fortification in the CI, since it helps uncover these bugs?
