### ISSUE TITLE
Unable to start after changing the IP address in the clickhouse configuration file to a domain name

### ISSUE THREAD

**Issue by hyj629222521** [ClickHouse/ClickHouse#49985]
clickhouse version  22.3.6.5
The main documents include：
/etc/clickhouse-server/config.xml
/etc/clickhouse-server/metrika.xml

The abnormal information is as follows
![微信图片_20230518181625](https://github.com/ClickHouse/ClickHouse/assets/59154295/95741ece-5384-4377-946a-38882ed6ea38)

**Comment by den-crane** [comment]
You need to use recovery mode https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper#recovering-after-losing-quorum
