### ISSUE TITLE
Replication Queue Stacking Problem

### ISSUE THREAD

**Issue by hjun881** [ClickHouse/ClickHouse#49986]
### bug
Our scenario is to run a task to write data to ck, and after inserting the data, use the `OPTIMIZE TABLE table_name FINAL` Remove duplicates However, there are often issues with the accumulation of replication queues

The query replication queue statement is as follows:
```sql
sql>select version();
┌─version()─┐
│ 22.3.2.1  │
└───────────┘
sql>select count() from system.replication_queue
5000
```

The error message is as follows:
```
Not executing fetch of part 416f8ff774e7cbd6f6226f523e3eafdf_127_127_0 because 12 fetches already executing, max 12.
Not executing log entry queue-0000112215 for part 20230517_10663_10663_0 because it is covered by part 20230517_0_11110_1311 that is currently executing
```

The replication queue monitoring information is as follows:
![image](https://github.com/ClickHouse/ClickHouse/assets/18508499/500b9e33-0f9d-406c-850a-d91aa7e3910c)

**The above error has had a significant impact on our business. Could you please take a look? Thank you**
---

**Comment by den-crane** [comment]
22.3.2.1  is out of support.

`OPTIMIZE TABLE table_name FINAL` this is not recommended per documentation.
At least you should use `OPTIMIZE TABLE table_name FINAL settings optimize_skip_merged_partitions=1` to avoid of re-merging the old data.

>The above error has had a significant impact on our business

How long replication queue impacts?

**Comment by hjun881** [comment]
1. replication queues exceeding 1000 has an impact on our business What if we can lower the replication queue. What is the reason for the above error and how to avoid it
2.  Stacked tasks are all `GET_PARTS` this have nothing to do with the performance of zookeeper
```
Not executing fetch of part 416f8ff774e7cbd6f6226f523e3eafdf_127_127_0 because 12 fetches already executing, max 12.
Not executing log entry queue-0000112215 for part 20230517_10663_10663_0 because it is covered by part 20230517_0_11110_1311 that is currently executing
```

**Comment by den-crane** [comment]
I suggest to use `settings optimize_skip_merged_partitions=1`

>Not executing fetch of part 416f8ff774e7cbd6f6226f523e3eafdf_127_127_0 because 12 fetches already executing, max 12.

try
```
cat /etc/clickhouse-server/users.d/background_fetches_pool_size.xml
<clickhouse>
    <profiles>
        <default>
            <background_fetches_pool_size>32</background_fetches_pool_size>
        </default>
    </profiles>
</clickhouse>
```

**Comment by hjun881** [comment]
I have already adjusted all the configurations mentioned above and cannot solve the problem. When this replication queue backlog occurs, restart the previous backlog of ck and partially eliminate it. Is there a possibility of deadlock causing the backlog

Here are the specific configurations of ck:

```xml
?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <optimize_throw_if_noop>0</optimize_throw_if_noop>
            <optimize_skip_merged_partitions>1</optimize_skip_merged_partitions>
            <!--<insert_keeper_max_retries>5</insert_keeper_max_retries>-->
            <background_common_pool_size>8</background_common_pool_size>
            <background_move_pool_size>36</background_move_pool_size>
            <background_fetches_pool_size>36</background_fetches_pool_size>
            <background_pool_size>64</background_pool_size>
            <max_final_threads>64</max_final_threads>
            <background_schedule_pool_size>160</background_schedule_pool_size>
            <background_distributed_schedule_pool_size>64</background_distributed_schedule_pool_size>
            <max_memory_usage>171798691840</max_memory_usage>
            <max_memory_usage_for_user>274877906944</max_memory_usage_for_user>
            <max_memory_usage_for_all_queries>647681068236</max_memory_usage_for_all_queries>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>random</load_balancing>
            <max_partitions_per_insert_block>20000</max_partitions_per_insert_block>
            <max_execution_time>14400</max_execution_time>
            <max_query_size>102410241024</max_query_size>
            <distributed_ddl_task_timeout>1200</distributed_ddl_task_timeout>
            <send_timeout>600</send_timeout>
            <receive_timeout>600</receive_timeout>
            <http_send_timeout>600</http_send_timeout>
            <http_receive_timeout>600</http_receive_timeout>
            <log_queries>1</log_queries>
            <constraints>
               <max_memory_usage>
                    <min>1000</min>
                    <max>80000000000</max>
                </max_memory_usage>
            </constraints>
        </default>
    </profiles>
</yandex>
```

**Comment by hjun881** [comment]
I only know that the replication queue is piled up, and there is no monitoring indicator showing how many replication tasks are generated per second. Is it possible that the replication queue is piled up due to too many replication tasks

**Comment by hjun881** [comment]
We used a large number of `insert ...... into select ....` And can multiple table join statements be merged into a large wide table to control batch size

For example:

```sql
insert into fin_dw.tag_offline_label_data_merge(data_hour,user_no,wlh_homepage_action_days) 
select     toDateTime('2023-05-21 04:01:38'),    user_no,
    array(dateDiff('day',toDate(data_day),today())) as wlh_homepage_action_daysfrom ods.prd_lbrs_tag_user_wlh_homepage_visit_labelprewhere pday = '20230520' and user_no != 'NULL'
 settings max_execution_time = 72000,insert_distributed_sync = true
```
