### ISSUE TITLE
I can not find `release` script

### ISSUE THREAD

**Issue by zenvzenv** [ClickHouse/ClickHouse#49984]
**Describe the issue**

https://github.com/ClickHouse/ClickHouse/blob/master/docs/zh/development/build.md#%E8%BF%90%E8%A1%8C%E5%8F%91%E5%B8%83%E8%84%9A%E6%9C%AC-yun-xing-fa-bu-jiao-ben

I tried to build the release package of clickhouse locally. I found this official article. In the section `运行发布脚本`, I couldn't find the `release` script mentioned in the article.

**Comment by cangyin** [comment]
it is now `docker/packager/packager`

**Comment by zenvzenv** [comment]
Ok, I found the packaging script of docker. Is there any packaging script related to rpm, for example: `spec` file.
By the way, should the above document be updated with the correct content?

**Comment by cangyin** [comment]
> any packaging script related to rpm

yes. it is `packages/build`

> spec file

besides the `packages/build`

**Comment by zenvzenv** [comment]
Thank you very much, I still have a question, when I build the binary file from the source code, the branch I am in is `v23.3.2.37-lts`, but the version of the binary I built is `v23.3.2.1`, I want to ask Is this normal?

**Comment by cangyin** [comment]
`v23.3.2.37-lts` is a tag. the version is calculated in script `tests/ci/git_helper.py`:

https://github.com/ClickHouse/ClickHouse/blob/5635c1bc26e1eaf636a1d237db18e1267cceb485/tests/ci/git_helper.py#L170-L177

where the last digit in version string is called `tweak`, so yes

> but the version of the binary I built is v23.3.2.1, I want to ask Is this normal

it is normal.
