### ISSUE TITLE
How can i enable system.session_log table ?

### ISSUE THREAD

**Issue by cansayin** [ClickHouse/ClickHouse#49994]
hi all,

I receive following error. How can i enable this table ?

SELECT *
FROM system.session_log

Query id: 197e548c-ac52-41c3-98e5-54c0fe43d390

0 rows in set. Elapsed: 0.032 sec. 

Received exception from server (version 23.4.2):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table system.session_log doesn't exist. (UNKNOWN_TABLE)

Thanks

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/blob/f98c337d2f9580fa65c8d21de447ab6e8fe3d781/programs/server/config.xml#L1252
