### ISSUE TITLE
[Improvement] Infer Data Lakes schemas by reading the metadata

### ISSUE THREAD

**Issue by alifirat** [ClickHouse/ClickHouse#50012]
**Use case**

As a User, I would like to have an instant creation when creating a DataLake table like Iceberg or Delta Lake. 

**Describe the solution you'd like**

Today, I have the feeling that the schema inference of the Data Lakes is inferred by reading the data files directly. The main issue I see with this approach is that if we have millions of data files, it's going to take a while to just infer the schema. 

To me, the schema can be infer by reading the metadata: 
- For Iceberg, if you reads the `v{N}.metadata.json` there is a field called `schemas` that contains all the fields. 
- For Delta Lake, if you the reads the path `metadata.schemaString` you also have the schema. 

To me, the improvements are going to be on 2 side: 
- performance: reading a simple JSON file on S3 against reading N files on S3 
- cost: 1 single AWS call for the schema vs multiple calles 

A potential drawback if the schema changes during the time:
- Well in this case, as like any ClickHouse table today, the user may need to run an alter table command or recreate the table since it's a read-only mode ? 

**Describe alternatives you've considered**

Don't look to alternatives. 

**Additional context**

See #49958 #49959

**Comment by kssenii** [comment]
For Iceberg we do already infer schema from metadata (from https://github.com/ClickHouse/ClickHouse/pull/55695), for DeltaLake it will be added once https://github.com/ClickHouse/ClickHouse/pull/63201 is merged.

**Comment by nikita-vanyasin** [comment]
Hi @kssenii I see that multi-parts checkpoint files are [not supported yet](https://github.com/ClickHouse/ClickHouse/blob/708d5bbc2df46537c09656d591265a597184761b/src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadata.cpp#L495). Is it on roadmap? Should I create a separate ticket for it?

**Comment by nikita-vanyasin** [comment]
Maybe clickhouse can just ignore the missing parts though (current it tries to download the part and whole query fails).

From DeltaLake [protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#v2-spec):
> Because a multi-part checkpoint cannot be created atomically (e.g. vulnerable to slow and/or failed writes), readers must ignore multi-part checkpoints with missing parts.

**Comment by kssenii** [comment]
> Hi @kssenii I see that multi-parts checkpoint files are [not supported yet](https://github.com/ClickHouse/ClickHouse/blob/708d5bbc2df46537c09656d591265a597184761b/src/Storages/ObjectStorage/DataLakes/DeltaLakeMetadata.cpp#L495). Is it on roadmap? Should I create a separate ticket for it?

yes, please do.

> Maybe clickhouse can just ignore the checkpoint though (currently it tries to download the part and whole query fails).
From DeltaLake [protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#v2-spec):
Because a multi-part checkpoint cannot be created atomically (e.g. vulnerable to slow and/or failed writes), readers must ignore multi-part checkpoints with missing parts.

This documentation advises to ignore only uncompleted checkpoint files, which can easily be identified. So for completed checkpoint files - we should read them.

**Comment by divanik** [comment]
I'd like to inquire about the status of this issue. Given that two pull requests have been merged:

https://github.com/ClickHouse/ClickHouse/pull/55695
https://github.com/ClickHouse/ClickHouse/pull/63201

It seems these PRs should address the original concern. Could you please explain why this issue remains open?
If there are additional problems or incomplete features related to DeltaLake that need discussion, I suggest creating a separate issue for those topics. This will help keep each issue focused and make it easier to track progress.
Could you please provide an update on the current status and whether this specific issue can be closed? If it should remain open, what are the outstanding items that still need to be addressed?

**Comment by kssenii** [comment]
Yes, we can close it.
