### ISSUE TITLE
Order by DESC limit n,m query  takes a lot of memory 

### ISSUE THREAD

**Issue by wzisheng** [ClickHouse/ClickHouse#50019]
**How to reproduce**
v22.3.2.2

create table if not exists test_table01 (
  mater_id String 
  ,device_no String 
  ,image_url String 
  ,url_type String 
  ,creative_type String 
  ,ad_code String 
  ,slot_code String 
  ,style String 
  ,width Double 
  ,height Double 
  ,requpper int 
  ,fill int 
  ,fill_rate Double 
  ,shows int 
  ,show_rate Double 
... some more columns
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(report_date)
PRIMARY KEY (report_date, shows)
ORDER BY (report_date, shows, ad_code, slot_code, own_name, image_url, device_no, url_type, click_rate, fill_rate, show_rate)
TTL report_date + INTERVAL 7 DAY;

SELECT  shows,mater_id, device_no, image_url, url_type, creative_type　FROM test_table01 WHERE report_date = '2023-05-15'　order by report_date DESC, shows DESC LIMIT 84890000,10 settings max_threads = 4;

**with 100 million rows in it, only select 5 columns will lead to memory limit exceeded** 
Code: 241. DB::Exception: Received from 192.168.0.5:9000. DB::Exception: Memory limit (total) exceeded: would use 24.72 GiB (attempt to allocate chunk of 4211824 bytes), maximum: 24.72 GiB: (while reading column report_date): (while reading from part store/24e/24e9a528-e0a4-4db8-864f-85c7fc4eaadb/20230516_1_96_3/ from mark 5431 with max_rows_to_read = 8192): While executing MergeTreeThread. (MEMORY_LIMIT_EXCEEDED)

**Comment by wzisheng** [comment]
@den-crane  hi, do you have any idea for this？

**Comment by den-crane** [comment]
try to add `settings max_threads=1, max_block_size=2048`

**Comment by alexey-milovidov** [comment]
Update to the latest version 23.4.
