### ISSUE TITLE
Code: 27. DB::ParsingException: Cannot parse input: expected

### ISSUE THREAD

**Issue by cansayin** [ClickHouse/ClickHouse#50035]
Hi all,

I am running a script which insert some queries to the table. However clickhouse can not insert following syntax as a string.

Can somebody help me for this issue ?

Thanks

Code: 27. DB::ParsingException: Cannot parse input: expected '(' before: 'SELECT * FROM viewIfPermitted(SELECT message FROM system.warnings ELSE null(\\\'message String\\\'))\nSELECT DISTINCT arrayJoin(extractAll(name, \\\'[\\\\\\\\w_]{2,}\\\')) A':  at row 0: While executing ValuesBlockInputFormat: data for INSERT was parsed from stdin: data for INSERT was parsed from query: (in query: INSERT INTO audit_logs.logs (timestamp, user, query) VALUES ('2023-05-19 18:03:22', 'can', 'SELECT * FROM viewIfPermitted(SELECT message FROM system.warnings ELSE null(\'message String\'))')). (CANNOT_PARSE_INPUT_ASSERTION_FAILED)

**Comment by santrancisco** [comment]
Not quite sure here but I'm just guessing the script may not escape the single quotes of the query being inserted and caused syntax error?
