### ISSUE TITLE
Woboq broken after Clang 16 upgrade

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#50077]
Woboq builds (for [1]) broke after #49678, potentially related: [2]

To reproduce:
1. build Woboq locally and run `cmake` for ClickHouse, see docker/test/codebrowser/Dockerfile for instructions
2. run Woboq locally, see docker/test/codebrowser/build.sh for instructions

For me, 2. produces:

```
~/repo/ch4 (master) $ ~/Downloads/woboq_codebrowser/generator/codebrowser_generator -b /home/ubuntu/repo/ch4/build -a -o /home/ubuntu/Downloads/out -p "test:/home/ubuntu/repo/ch4:test"
[0%] Processing /home/ubuntu/repo/ch4/base/base/JSON.cpp                                                                                                                                   
FATAL Error: /home/ubuntu/repo/ch4/contrib/llvm-project/libcxx/include/stddef.h:45: 'stddef.h' file not found                                                                              
Error: /home/ubuntu/repo/ch4/contrib/llvm-project/libcxx/include/__type_traits/is_array.h:40: reference to unresolved using declaration                                                    
Error: /home/ubuntu/repo/ch4/contrib/llvm-project/libcxx/include/__type_traits/remove_extent.h:25: reference to unresolved using declaration                                               
Error: /home/ubuntu/repo/ch4/contrib/llvm-project/libcxx/include/__type_traits/type_list.h:28: reference to unresolved using declaration                                                   
Error: /home/ubuntu/repo/ch4/contrib/llvm-project/libcxx/include/__type_traits/type_list.h:30: reference to unresolved using declaration                                                   
Error: /home/ubuntu/repo/ch4/contrib/llvm-project/libcxx/include/__type_traits/type_list.h:36: reference to unresolved using declaration                                                   
Error: /home/ubuntu/repo/ch4/contrib/llvm-project/libcxx/include/__type_traits/aligned_storage.h:28: reference to unresolved using declaration
[...]                                             
```

which is the same as in CI [3].

@azat @Felixoid 

[1] https://clickhouse.com/codebrowser/ClickHouse/index.html (folder src/ is missing)
[2] https://github.com/ClickHouse/ClickHouse/pull/49678/files#diff-74ee3d6d5fdb9cd435096b93d713eeaa6130eeea2ed045fb1dd71d68fcfccaa7
[3] https://s3.amazonaws.com/clickhouse-test-reports/0/8b77e2096cdd601c2797f930637ddef419e382be/woboq_build/run.log

**Comment by Felixoid** [comment]
It complains on the line https://github.com/ClickHouse/llvm-project/blob/remove-locales/libcxx/include/stddef.h#L45, that is removed in https://github.com/llvm/llvm-project/blob/main/libcxx/include/stddef.h#L45

Just curious, what about updating llvm-project? It's 30k+ behind the main

**Comment by Felixoid** [comment]
So, I've hardcoded the image from #49701, and it works. It's a temporary workaround, and the issue will remain open.

**Comment by alexey-milovidov** [comment]
We've removed Woboq.

As an alternative, we can implement our own code browser, although it will be a waste of time.

**Comment by Felixoid** [comment]
The leftovers of it will be removed in #56501. To jump over the code, GH now has the web VS code. It doesn't look like 100% replacement, but on the other hand, we have it for completely free
