### ISSUE TITLE
TimeZone parameter do not work

### ISSUE THREAD

**Issue by Votan13** [ClickHouse/ClickHouse#5007]
**Describe the bug**
In the version 19.4.1.1 timezone config parameter does not take in considiration.

**How to reproduce**
* Which ClickHouse server version to use 19.4.1.1
* Non-default settings, setup time zone UTC

[root@server ~]# clickhouse-client 
ClickHouse client version 19.4.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.4.1 revision 54416.

server :) select now(); 

SELECT now()
┌───────────────now()─┐
│ 2019-04-15 15:06:43 │
└─────────────────────┘
1 rows in set. Elapsed: 0.003 sec. 

server :) Bye.
You have mail in /var/spool/mail/root
[root@server ~]# grep timezone /etc/clickhouse-server/config.xml
    <timezone>UTC</timezone>

[root@server ~]# date
Mon Apr 15 15:07:25 EEST 2019

**Expected behavior**
Like it was in older versions.
[root@server ~]# clickhouse-client 
ClickHouse client version 18.14.10.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.10 revision 54409.

server :) select now();

SELECT now()
┌───────────────now()─┐
│ 2019-04-15 12:06:29 │
└─────────────────────┘
1 rows in set. Elapsed: 0.002 sec. 

server :) Bye.
[root@server ~]# grep timezone /etc/clickhouse-server/config.xml
    <timezone>UTC</timezone>

**Additional context**
[root@server ~]# date
Mon Apr 15 15:07:25 EEST 2019

**Comment by den-crane** [comment]
duplicate https://github.com/yandex/ClickHouse/issues/4658
