### ISSUE TITLE
Wrong results of the comparison for NaN values

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50075]
**Describe what's wrong**

The two semantically-equivalent SELECT statements should output the same results, but they did not.

**Does it reproduce on recent release?**

It can be reproduced in the latest version.

**How to reproduce**

Version: 23.5.1.1 (commit d509d7277b08627b05f7cc02049da904c53c507e)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/5d6862eb-20c6-45a3-a35d-9218c2b77e23

_Set up database_

```sql
create table t2 (c9 String, c10 Float32, primary key(c9)) engine = MergeTree;
insert into t2 values ('1', nan);
```

_SELECT statement 1_

```sql
select  
  count(*)
from 
  t2 as ref_0
where ref_0.c10 >= (case when true then ref_0.c10 else max2(0, 1) end);
```

As `(case when true then ref_0.c10 else max2(0, 1) end)` can be replaced with `ref_0.c10`, I get the semantically-equivalent SELECT statement:

_SELECT statement 2_

```sql
select  
  count(*)
from 
  t2 as ref_0
where ref_0.c10 >= ref_0.c10;
```

**Expected behavior**

The two SELECT statements output the same results.

**Actual behavior**

SELECT statement 1 outputs:
```
┌─count()─┐
│       0 │
└─────────┘
```

SELECT statement 2 outputs:
```
┌─count()─┐
│       1 │
└─────────┘
```
They are different.

**Additional context**

This bug still exists even when I `set compile_expressions=0`

**Comment by tavplubix** [comment]
Simpler example:
```
dell9510 :) select nan = nan

SELECT nan = nan

Query id: 412781bf-5626-474e-a6f9-1502e0e60718

┌─equals(nan, nan)─┐
│                1 │
└──────────────────┘

1 row in set. Elapsed: 0.014 sec. 

dell9510 :) select materialize(nan) = nan

SELECT materialize(nan) = nan

Query id: 0c7cdb46-ec8b-4adb-b59e-e1c2b5878999

┌─equals(materialize(nan), nan)─┐
│                             0 │
└───────────────────────────────┘

1 row in set. Elapsed: 0.008 sec. 
```

**Comment by alexey-milovidov** [comment]
@JZuming 

We specifically decided to leave `nan` comparison implementation-defined to allow optimizations, see the comment here: https://github.com/ClickHouse/ClickHouse/pull/50287/files#diff-efc7dfb3281a1d7695917227c3693049da6206cbb388d4f4b81035ec6366c20eL1233

Nevertheless, now we fixed it for your convenience!
Thank you for the report.
