### ISSUE TITLE
Example of projection from documentations is not work

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#50093]
ClickHouse v.23.3.2.37

Trying to work with projections example from ClickHouse documentation, but its not work.
Link to example from doc:
https://clickhouse.com/docs/en/sql-reference/statements/alter/projection#example-filtering-without-using-primary-keys

code:
```
CREATE TABLE visits_order
(
   `user_id` UInt64,
   `user_name` String,
   `pages_visited` Nullable(Float64),
   `user_agent` String
)
ENGINE = MergeTree()
PRIMARY KEY user_agent;

ALTER TABLE visits_order ADD PROJECTION user_name_projection (SELECT * ORDER BY user_name)

ALTER TABLE visits_order MATERIALIZE PROJECTION user_name_projection;

INSERT INTO visits_order SELECT
    number,
    'test',
    1.5 * (number / 2),
    'Android'
FROM numbers(1, 100);


SELECT
    *
FROM visits_order
WHERE user_name='test'
LIMIT 2;

SELECT query, projections FROM system.query_log WHERE query_id='<query_id>'
```

So, when i try to check projections  column from query_log, i see nothing ([])
What i do wrong?

**Comment by tavplubix** [comment]
cc: @amosbird

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/4b0ce12f-9353-4c39-9e4a-d72070f1f75a

Interesting that 
`WHERE user_name='test'` does not use the projection, it looks like CBO
`WHERE user_name='1test'` uses the projection but `system.query_log` is empty anyway
