### ISSUE TITLE
use_environment_credentials=1 does not allow to use public S3 buckets

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#50129]
After use_environment_credentials is on by default (https://github.com/ClickHouse/ClickHouse/pull/47397) public S3 buckets can not be used w/o unsetting this variable. Users get an error:

```
DB::Exception: Could not list objects in bucket '<bucket_name>' with prefix '<bucket_prefix>', S3 exception: `AccessDenied`, message: 'Access Denied'. (S3_ERROR)
```

Even the public docs get broken this way, like this one: https://clickhouse.com/blog/getting-data-into-clickhouse-part-3-s3

This is inconvenient and unexpected for S3 function. If bucket is publicly accessible w/o the password, users expect it works the same in ClickHouse as well.

Probably 'use_environment_credentials' should not apply to S3 function, but only to S3 disk. Or have two different settings for disk and function.

**Comment by antonio2368** [comment]
Thanks for tagging me @alex-zaitsev, didn't notice the issue!

I enabled the `use_environment_credentials` by default for convenience so the entire chain can be used.
If for some reason your credentials fail on the public bucket I added `NOSIGN` keyword described here `https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#accessing-public-buckets`.

Please tell me if this works for you. Also, I couldn't find a sure way for determining if a bucket and all its objects are publicly accessible.
