### ISSUE TITLE
Select with exact table's ORDER BY is slow on MergeTree

### ISSUE THREAD

**Issue by Su33ke** [ClickHouse/ClickHouse#50139]
**Cluster setup**
21.11.5.33
3 shards, 2 replicas each.

**Table**
The table contains 800mil of rows.
```
CREATE TABLE IF NOT EXISTS table
(
    DateCreated             DateTime,
    EventDate               DateTime,
    IsIncident              Byte,
    EventSource             UInt8
    ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
PARTITION BY toYYYYMM(EventDate)
ORDER BY (IsIncident, toStartOfDay(EventDate), EventSource, EventDate)
PRIMARY KEY (IsIncident, toStartOfDay(EventDate), EventSource)
;;
```

**Query**
```
select *
from table
order by IsIncident, toStartOfDay(EventDate), EventSource, EventDate
limit 0,10;;
```

**Result**
`10 rows in set. Elapsed: 340.259 sec. Processed 836.31 million rows, 567.49 GB (2.46 million rows/s., 1.67 GB/s.)`

**Question**
Could you please advice why does this query requires a full table scan? We actually don't need such query, but it clearly illustrates our issue: when we filter it by low cardinality IsIncident, EventSource and toStartOfDay(EventDate) predicates and sort just by EventDate, it gives bad performance.

**Comment by den-crane** [comment]
>PARTITION BY toYYYYMM(EventDate)

Clickhouse reads all partitions. 
You need to add condition by `EventDate` 

try 

```
select *
from table
where EventDate <= today()-365
order by IsIncident, toStartOfDay(EventDate), EventSource, EventDate
limit 0,10 settings max_block_size=100, max_threads=1;
```

**Comment by den-crane** [comment]
>Correct, but does it really need to read all parts, assuming we want only top 10 entries sorted by table's ORDER BY? 
>It looks like the short-circuiting is not working in this case.

This optimization is not implemented and is not planned.
