### ISSUE TITLE
map subscripting and NULL

### ISSUE THREAD

**Issue by ArturFormella** [ClickHouse/ClickHouse#50179]
Hello!
I have to rewrite the whole table with value conversion as follows:
1 => -1
2 => -2
5 => 7
other values without change.
I use CREATE TABLE + SELECT + map(1,-1, 2, -2, 5, 7)[old_value];

Regular subscription returns 0 instead of NULL.

For example number 9:
SELECT coalesce(map(1,-1, 2, -2, 5, 7)[9], 9)
Result: 0
Excepted result: 9

SELECT map(1,-1, 2, -2, 5, 7)[9]
Result: 0
Excepted result: NULL

I can't distinguish between a null value and a zero. toNullable(9) doesn't change anything.

select version();
23.2.4.12

**Comment by CurtizJ** [comment]
You need to cast map to type with `Nullable` value:

```
SELECT CAST(map(1, -1, 2, -2, 5, 7), 'Map(Int64, Nullable(Int64))')[9] AS a

┌────a─┐
│ ᴺᵁᴸᴸ │
└──────┘
```
or

```sql
SELECT map(1, toNullable(-1), 2, -2, 5, 7)[9] AS a

┌────a─┐
│ ᴺᵁᴸᴸ │
└──────┘
```

**Comment by ArturFormella** [comment]
This is not intuitive. Still unexpected behavior in my opinion. It's worth knowing that.
