### ISSUE TITLE
Restarting a server with CH 23.2.6.34 and additional mounted disks may lead to data loss

### ISSUE THREAD

**Issue by vmihailenco** [ClickHouse/ClickHouse#50178]
I believe what happened is the following:

1. Server with CH was stuck and restarted via AWS console
2. Server was rebooted but some extra disks were not mounted properly when CH was automatically started by systemd
3. CH was able to start and started processing requests, but some parts from the missing disks were missing
4. Shortly after CH was restarted again to pick up missing disks/parts but refused to start with errors like

```
023.05.24 07:56:10.473737 [ 984 ] {} <Error> Application: Caught exception while loading metadata: Code: 49. DB::Exception: Part 39002_2921783_2922054_4 intersects next part 39002_2921793_2927145_7. It is a bug!: Cannot attach table
```

5. After manually removing conflicting parts CH was able to start. Parts from the missing disks appeared in `system.parts` table.

**Comment by tavplubix** [comment]
> some extra disks were not mounted properly

That's the reason. ClickHouse did not find some parts and replaced them with empty parts, it's expected behavior.

You can attach the missing parts manually.

The exception message was incomplete: https://github.com/ClickHouse/ClickHouse/pull/50180

**Comment by vmihailenco** [comment]
>may lead to a scary error message

It leads to a broken ClickHouse and data loss.

Changing a scary message to a funny one does not help in any way.

>You can attach the missing parts manually.

Care to show how I can merge conflicting parts?

**Comment by alexey-milovidov** [comment]
You can attach the conflicting parts with the ALTER TABLE ... ATTACH query.

**Comment by tavplubix** [comment]
> It leads to a broken ClickHouse and data loss.

It's expected behavior, see https://github.com/ClickHouse/ClickHouse/pull/50180#discussion_r1204015098 
Also, no data is actually lost, and it's pretty easy to recover and attach the "lost" data back.

> Changing a scary message to a funny one does not help in any way.

Changing the message helps to understand that it's not a bug in case of inappropriate operation
