### ISSUE TITLE
Network traffic is large between ClickHouse and Keeper

### ISSUE THREAD

**Issue by frinkr** [ClickHouse/ClickHouse#50175]
We have a cluster with 5 nodes, and more than 60K ReplicatedMergeTree tables. We observed that the network traffic between CH and Keeper is about 150Mbit per second, even if the cluster is not executing any sql. Is it normal to have such large network traffic?

**Comment by tavplubix** [comment]
> more than 60K ReplicatedMergeTree tables

It's the reason. Here's a workaround:

```
   <merge_tree>
        <cleanup_delay_period>300</cleanup_delay_period>
        <merge_selecting_sleep_ms>60000</merge_selecting_sleep_ms>
   </merge_tree>
```

See also https://github.com/ClickHouse/ClickHouse/issues/31919

**Comment by frinkr** [comment]
It works, thanks!
