### ISSUE TITLE
Protobuf format implementation

### ISSUE THREAD

**Issue by topofstack** [ClickHouse/ClickHouse#50189]
Hi, I’m trying to understand implementation of protobuf support in ClickHouse in more details. Looking at the source files https://clickhouse.com/codebrowser/ClickHouse/src/Formats/index.html I’ve got the impression that messages received from Kafka are manually parsed on the basis of the .proto file and fields are converted into clickhouse format.

The .proto format is rich and it’s hard to understand the way proto types are converted to clickhouse types from just looking at clickhouse sources.

Is there some kind of specification to clarify the mapping between proto and clickhouse types and the way this conversion is implemented?

**Comment by santrancisco** [comment]
I think the information you want is in [our documentation about protobuf](https://clickhouse.com/docs/en/interfaces/formats#protobuf) :

```
This format requires an external format schema.
```

And regarding the conversion:

```To find the correspondence between table columns and fields of Protocol Buffers’ message type ClickHouse compares their names. This comparison is case-insensitive and the characters _ (underscore) and . (dot) are considered as equal. If types of a column and a field of Protocol Buffers’ message are different the necessary conversion is applied.```

So it comes down to having proper external format schema file to determine this i would say
