### ISSUE TITLE
how to use a lua scripts for create function on clickhouse?

### ISSUE THREAD

**Issue by yehaotong** [ClickHouse/ClickHouse#50199]
I do this sql for create a function:
`INSERT INTO lua_scripts VALUES ('to_upper', '
                function to_upper(input_string)
                  local upper_string = string.upper(input_string)
                  return upper_string
                end');`
but is has problem:
`yntax error: failed at position 25 ('(') (line 1, col 25):

CREATE FUNCTION to_upper(input_string String) RETURNS String
LANGUAGE 'LUA'
NAME 'lua_scripts.to_upper'
SETTINGS 'allow_suspicious_udfs' = 1;

Expected one of: ON, AS`
how to use a lua scripts for create function on clickhouse?

**Comment by cangyin** [comment]
the syntax does not look like ClickHouse UDF. see [doc for user defined SQL functions](https://clickhouse.com/docs/en/sql-reference/statements/create/function)

if you want to use lua, [Executable User Defined Functions](https://clickhouse.com/docs/en/sql-reference/functions/udf#executable-user-defined-functions) should help to achieve that.


this is how I can execute arbitrary bash script inside ClickHouse:

```xml
<!-- config of Executable User Defined Functions -->
<functions>
    <function>
        <type>executable</type>
        <name>exec</name>
        <return_type>String</return_type>
        <argument>
            <type>String</type>
            <name>cmd</name>
        </argument>
        <format>RawBLOB</format>
        <command>cat | bash</command>
        <execute_direct>0</execute_direct>
    </function>
</functions>
```
then inside ClickHouse console:
```sql
SELECT exec('echo Hello World!; ls /var/lib/clickhouse/data | head -3')

Query id: 636f420b-f173-4245-8d37-da77d8dcb601

┌─exec('echo Hello World!; ls /var/lib/clickhouse/data | head -3')─┐
│ Hello World!
analytics
automated
business
                           │
└──────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.030 sec.
```
