### ISSUE TITLE
type is reported as Nullable though it isn't

### ISSUE THREAD

**Issue by pkit** [ClickHouse/ClickHouse#50213]
```
SELECT *
FROM numbers((
    SELECT coalesce(id, 0)
    FROM t5
    WHERE id = 1
), 1)

Query id: 2031197f-f861-4156-9513-8c028e78f62c


0 rows in set. Elapsed: 0.006 sec. 

Received exception from server (version 23.4.2):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type Nullable(UInt64) expression, must be numeric type. (ILLEGAL_TYPE_OF_ARGUMENT)
```
https://fiddle.clickhouse.com/0c574c66-fac4-441e-bcb3-a6bc385b55c6

Seems like the nullability is checked too early.
Overall it seems like everything is checked too early when we are talking about arguments for a table function (TF).
Joins don't seem to work too as it can never find the identifier if used as a TF argument...

**Comment by pkit** [comment]
Ah, lol 
it works if done on select result:
```
SELECT *
FROM numbers(coalesce((
    SELECT id
    FROM t5
    WHERE id = 1
), 0), 1)
```

**Comment by den-crane** [comment]
Subqueries always return nullable types

related https://github.com/ClickHouse/ClickHouse/issues/30972 https://github.com/ClickHouse/ClickHouse/issues/36027

ClickHouse release v21.9, 2021-09-09
Backward Incompatible Change

    Now, scalar subquery always returns Nullable result if it's type can be Nullable. It is needed because in case of empty subquery it's result should be Null. Previously, it was possible to get error about incompatible types (type deduction does not execute scalar subquery, and it could use not-nullable type). Scalar subquery with empty result which can't be converted to Nullable (like Array or Tuple) now throws error. Fixes 

https://github.com/ClickHouse/ClickHouse/issues/25411. https://github.com/ClickHouse/ClickHouse/pull/26423 (Nikolai Kochetov).
