### ISSUE TITLE
S3 http_keep_alive_timeout, use ConnectionPool

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#50217]
Use http_keep_alive_timeout and ConnectionPool for S3
> Almost done here #49732

Well. After  #49732 we  found several points to grow.  [PoolBase](https://github.com/ClickHouse/ClickHouse/blob/bbd70932e21bc3f52eacf962386ad44c19c62e97/src/Common/PoolBase.h#L31) does not meet the goals. We need mode specific ConnectionPool with particular features. 

- spread connections over all the resolved addresses  (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- use resolved addresses from different resolves with ttl in case when resolved each time only one different address (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- do not return a stale connection (keep_alive_timeout has passed), find the fresh one (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- do not iterate through all connections when you need one, different containers for vacant and in-use. (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- track all connections, even those which is under soft limit, they are useful too and can be reused (we see cases, when it is above the limits, sessions from prefetches are not reused in the following reads) (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- when ConnectionPool has more connections than a soft limit, evict free connection faster than keep_alive_timeout but still leave a chances to reuse them (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- the code which do reconnect for connection has to be altered in order to return one connection (if it is broken than it is just destroyed) and take already open one from the ConnectionPool (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- `ReadBufferFromS3PreservedSessions` is broken, it shows only explicit reset of session. (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- sessions are only reused when they are marked with `HTTPSessionReuseTag`. Only few pieces of code do that. For example, `fileExists` closes session after.  (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- limits work for the groups of connections: disks, storages, http(the rest). (addressed in https://github.com/ClickHouse/ClickHouse/pull/58845)
- proactive create some count session, but for some time after last usage. Forgotten instances should not do anything eventually.

**Comment by CheSema** [comment]
I will make a test to prove it and fix if Im right.

**Comment by CheSema** [comment]
Almost done here 
https://github.com/ClickHouse/ClickHouse/pull/49732

**Comment by nickitat** [comment]
just a comment for clarity. from perf standpoint the main point to improve is to avoid synchronous (re)connect right after we took session from pool. it happens when we manually reset the session previously, or it was idling and keep-alive timeout expired or it is a new session (maybe smth else). by removing bad sessions, retaining a few over the limit and maybe proactively opening new ones and connecting them in bg we could mitigate this problem.
when we have to `connect` it not only means we will pay connect cost, but it is potentially a connect timeout. those have huge impact on query duration.

**Comment by nickitat** [comment]
also would be really nice to get rid of this [crutch](https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/HTTPCommon.h#L58-L64) by implementing the logic of http session validation inside pool or session classes.
so far sessions are reused only in places when we manually supported this machinery with tags (it is only couple of places).

**Comment by nickitat** [comment]
and probably have a separate pool per each endpoint is not a good idea, because we don't limit the total number of connections sitting in all pools.

**Comment by CheSema** [comment]
> also would be really nice to get rid of this [crutch](https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/HTTPCommon.h#L58-L64) by implementing the logic of http session validation inside pool or session classes.
> so far sessions are reused only in places when we manually supported this machinery with tags (it is only couple of places).

I do not know how it could be done. Do you have some ideas?

**Comment by nickitat** [comment]
> > also would be really nice to get rid of this [crutch](https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/HTTPCommon.h?rgh-link-date=2024-01-16T23%3A45%3A28Z#L58-L64) by implementing the logic of http session validation inside pool or session classes.
> > so far sessions are reused only in places when we manually supported this machinery with tags (it is only couple of places).
> 
> I do not know how it could be done. Do you have some ideas?

I heard an idea that it is possible with http2 because it decouples streams and connections and you could freely destroy all streams once they are not needed anymore. 
but in the circumstances we're currently placed - no, I have no ideas.
