### ISSUE TITLE
How to control parallelization in fine granularity for a query including aggregation.

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#50228]
We have a special customized function `func1` which requires running in sequential behavior, i.e. single thread, while the SQL include a complex aggregation which requires parallel computing (i.e. multi-threads) for performance. With settings `max_threads=1`, it will force the whole SQL query to run in single thread. I am seeking for a way to control the aggregation runs in parallel while the evaluation of fucntion `func1` runs in single thread. 

For example, given that I want to run the below query
```
select func1(), * from (select avg(a), sum(b) from t1 group by k1);  -- t1 is a big table
```
As the func1() requires running in single thread, I have to add `settings max_threads=1`, the query will become:
```
select func1(), * from (select avg(a), sum(b) from t1 group by k1 order by k1) settings max_threads=1;  -- t1 is a big table
```
The pipeline will be:
```
read merge tree (x 1)
    -> evaluating expression(x 1)
    -> aggregate  (x 1)
    -> sorting  (x 1)
    -> evaluating expression (x 1) -- the func1() evalution here
```
The problem is that the aggregation is running in single thread, very bad performance!!!

Without settings 'max_threads=1', the func1() will be evaluated in mult-thread in the case of that the table contains multi-partitions, although the `sorting` pipeline step has already conbine multiple data streams into single one. As shown as following corresponding pipeline, 
```
read merge tree in multiple partitions (in multi-threads)
    -> aggregation
    -> partial sort  (one data stream per partition)
    -> evaluation func1()  -- (it is also in multi-threads)
    ->  merge partial sorted result
```

Can we evaluate the func1() in single thread and paralize the aggregation and other steps?

**Comment by davenger** [comment]
@Alex-Cheng you might try adding 'order by k1' to outer query as well to and not adding 'settings max_threads=1':

```
select func1(), * from (
    select k1, avg(a), sum(b) from t1 group by k1 order by k1
) order by k1
```
Just curious, what is this func1 that has such restrictions? Smth similar to rowNumberInAllBlocks? If this is the case maybe you can use 'k1' column itself to identify unique rows because you are already grouping by it.

**Comment by Alex-Cheng** [comment]
@davenger Thank yo for suggestion. But it seems not completely resolve my problem. 

```SQL
select * from (select running_total() as res from t1 order by k1) order by res;

drop table if exists test_table;

create table test_table(id Int64, par Int64) engine=MergeTree order by id;

insert into test_table select number as id, 1 as par from numbers(100000000);

--- query 1
select max(d) from (select pro_running_total(res) as d from (select  (t) as res from (select any(id) as t from test_table group by id) order by t ) order by res);

--- query 2
select max(d) from (select pro_running_total(res) as d from (select  (t) as res from (select any(id) as t from test_table group by id) order by t ) order by res) settings max_threads=1; 
```

The difference between query 1  and query 2 is the additional `settings max_threads=1`. The results are different and the query 2's result is correct.

Thank you for help.
