### ISSUE TITLE
Changes in #47519 cause queries to fail on some bitmap columns

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#50233]
The PR #47519(since 23.3) imposes the size restriction to 1GiB when reading data from bitmap columns.

https://github.com/ClickHouse/ClickHouse/blob/f1a3c9cfd5c9c533fdba7478ed0b209d9bb71262/src/AggregateFunctions/AggregateFunctionGroupBitmapData.h#L125-L131

This introduces backward compatibilty problem. We have lots of cases that the cardinality of a bitmap is tens of millions, however, after #47519, we can't read these data any more.

A very simple case illustrates this problem.

```sql
CREATE TABLE bitmap_test
(
    `id` UInt64,
    `bitmap` AggregateFunction(groupBitmap, UInt64)
)
ENGINE = AggregatingMergeTree
ORDER BY id

-- simulate to generate 50,000,000 different id
INSERT INTO bitmap_test SELECT
    toUInt64(101),
    groupBitmapState(rand64())
FROM numbers(50000000)

-- TOO_LARGE_ARRAY_SIZE error is raised since 23.3
-- Before 23.3 it only takes some time and some memory to compute the cardinality
SELECT bitmapCardinality(bitmap) FROM bitmap_test
```

If the data is inserted in old version, and after upgrading to 23.3, queries fail to compute `bitmapCardinality` or execute some other functions.

I think this size restriction during read does not make sense, because we can still insert more than 1GiB data to the bitmap.

**Comment by Avogar** [comment]
We've should introduce a setting that allows to change this maximum value. I will add it
CC: @alexey-milovidov

**Comment by alexey-milovidov** [comment]
Ok, but there should be protection from overflow anyways.
