### ISSUE TITLE
SegmentFault of attaching partition if altering table at the same time

### ISSUE THREAD

**Issue by fancyqlx** [ClickHouse/ClickHouse#5025]
**Describe the bug**
Hi. Recently we found a segment fault when attaching partitions. The log shows that there are altering operations and attaching operations at the same time. I have checked the code, and found attach function has no lock to prevent altering table schema. The stack is as follows.

I think I can add a lockStructureForAlter in the attachPartition function. If you think it makes sense, I will fix this problem later.

![image](https://user-images.githubusercontent.com/6196299/56278234-7590d680-6138-11e9-99f9-07d08c26e7c7.png)

**How to reproduce**
Sorry for that I have not reproduced this bug. May be the concurrency of my test is too low to reproduced it.

* Which ClickHouse server version to use
18.14.10

* Which interface to use, if matters
there are two kinds of operations we found in log:
alter table xxxx add column xxxxxx
alter table xxxx attach partition xxxxxx

**Comment by alexey-milovidov** [comment]
This part of code was changed in recent versions. Does the issue reproduce with latest stable release?

**Comment by alexey-milovidov** [comment]
We don't have `HaMergeTree` in our codebase.
