### ISSUE TITLE
clickhouse21.8.13.6  ReplicatedReplacingMergeTree replica can not sync data from another replica

### ISSUE THREAD

**Issue by sun-11y** [ClickHouse/ClickHouse#50259]
Previously, it was good because the upgrade activated zookeeper, which resulted in the inability to synchronize data

error.log:
<Error> default.metrics (952d52ab-5f4b-4ea7-952d-52ab5f4b9ea7): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 86, e.displayText() = DB::Exception: Received error from remote server /?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2F1%2Fdefault.metrics%2Freplicas%2Fclickhouse1&part=202305_4111692_4111781_22&client_protocol_version=7&compress=false. HTTP status code: 500 Internal Server Error, body: , Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8febd9a in /usr/bin/clickhouse
1. DB::assertResponseIsOk(Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&, std::__1::basic_istream<char, std::__1::char_traits<char> >&, bool) @ 0xe4a9523 in /usr/bin/clickhouse
2. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatablePooledSession> >::call(Poco::URI, Poco::Net::HTTPResponse&) @ 0x10d22ccc in /usr/bin/clickhouse
3. DB::detail::ReadWriteBufferFromHTTPBase<std::__1::shared_ptr<DB::UpdatablePooledSession> >::ReadWriteBufferFromHTTPBase(std::__1::shared_ptr<DB::UpdatablePooledSession>, Poco::URI, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char> >&)>, Poco::Net::HTTPBasicCredentials const&, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, DB::RemoteHostFilter const&) @ 0x10d1f842 i

info.log:
2023.05.26 11:31:51.444123 [ 183 ] {} <Trace> default.metrics (ReplicatedMergeTreeQueue): Not executing log entry queue-0000078080 for part 202305_4090016_4090016_0 because it is covered by part 202305_4069607_4132368_325 that is currently executing.
2023.05.26 11:31:51.444136 [ 183 ] {} <Trace> default.metrics (ReplicatedMergeTreeQueue): Not executing log entry queue-0000077549 for part 202305_4089345_4089628_73 because it is covered by part 202305_4069607_4132368_325 that is currently executing.
2023.05.26 11:31:51.444145 [ 183 ] {} <Trace> default.metrics (ReplicatedMergeTreeQueue): Not executing log entry queue-0000077550 for part 202305_4089345_4089629_74 because it is covered by part 202305_4069607_4132368_325 that is currently executing.

**Comment by sun-11y** [comment]
Previously, it was good because the upgrade activated zookeeper, which resulted in the inability to synchronize data

**Comment by alexey-milovidov** [comment]
Upgrade ClickHouse to version 23.4 and replace ZooKeeper with ClickHouse Keeper.
