### ISSUE TITLE
allow_experimental_inverted_index=true for play.clickhouse.com

### ISSUE THREAD

**Issue by pakud** [ClickHouse/ClickHouse#50268]
could you please allow use of inverted index feature for play.clickhouse.com? 

right now when i go to https://play.clickhouse.com/play?user=play and run 

```
SELECT * FROM stackoverflow WHERE Body LIKE '%apache spark%' LIMIT 100    
```

i'm getting
```
Code: 287. DB::Exception: Unsupported inverted index version 1. (UNKNOWN_FORMAT_VERSION) (version 23.5.1.291 (official build))
```

thanks a lot!

**Comment by cangyin** [comment]
but now I am getting:
```
Code: 164. DB::Exception: Cannot modify 'allow_experimental_inverted_index' setting in readonly mode. (READONLY) (version 23.5.1.291 (official build))
```

**Comment by alexey-milovidov** [comment]
I will drop the inverted index.
They are experimental (not ready for use) anyway.

**Comment by alexey-milovidov** [comment]
Done.

**Comment by alexey-milovidov** [comment]
@rschu1ze, by the way, the full-text search indices cannot become production ready as long as they are named "inverted". The "inverted" name is too generic.
