### ISSUE TITLE
Wrong result of SELECT statement with compile_expressions in recent commits (head version)

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50269]
**Describe what's wrong**

The two semantically-equivalent SELECT statements should output the same results, but they did not.

**Does it reproduce on recent release?**

It cannot be reproduced in the latest version, but it can be reproduced in the head version.

**How to reproduce**

Version: 23.5.1.1 (commit 3e6314675c6467bc4dd78f659bac862f7e9648f8)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/184cce9d-1e87-4666-afc1-97d281cc11cd

_Set up database_

```sql
create table t1 (pkey UInt32, c4 UInt32, c5 Float32, primary key(pkey)) engine = MergeTree;
insert into t1 values (12000, 36, 77.94);
```

_SELECT statement 1_

```sql
select  
  subq_1.c_4_c3362_6 as c_1_c3371_2
from 
  (select  
        corr(ref_0.c4,ref_0.c4) over w0 as c_4_c3362_6 
      from 
        t1 as ref_0
      window w0 as (partition by ref_0.c5 order by ref_0.pkey asc)
  ) as subq_1
where not (not (subq_1.c_4_c3362_6 <> subq_1.c_4_c3362_6));
```

As `not (not (subq_1.c_4_c3362_6 <> subq_1.c_4_c3362_6))` can be replaced with `subq_1.c_4_c3362_6 <> subq_1.c_4_c3362_6`, I get the semantically-equivalent SELECT statement:

_SELECT statement 2_

```sql
select  
  subq_1.c_4_c3362_6 as c_1_c3371_2
from 
  (select  
        corr(ref_0.c4,ref_0.c4) over w0 as c_4_c3362_6 
      from 
        t1 as ref_0
      window w0 as (partition by ref_0.c5 order by ref_0.pkey asc)
  ) as subq_1
where subq_1.c_4_c3362_6 <> subq_1.c_4_c3362_6;
```

**Expected behavior**

The two SELECT statements output the same results.

**Actual behavior**

They are different.

SELECT statement 1 outputs:
```
+-------------+
| c_1_c3371_2 |
+-------------+
|         nan |
+-------------+
```

SELECT statement 2 outputs an empty result.

**Additional context**

1. This bug can be triggered only in the head version, so it should be involved by recent commits.
2. At the first several times, the SELECT statement 1 outputs an empty result. But after several tries, the results become incorrect, similar to #50039.
3. if `set compile_expressions = 0`, the bug disappears, so it should be also related to compile_expressions.

**Comment by alexey-milovidov** [comment]
@JZuming Thank you!

It was intended behavior for NaNs; see the comment: https://github.com/ClickHouse/ClickHouse/pull/50287/files#diff-efc7dfb3281a1d7695917227c3693049da6206cbb388d4f4b81035ec6366c20eL1233

Nevertheless, we fixed it.
