### ISSUE TITLE
LOGICAL_ERROR: Argument column doesn't match result column

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50266]
**Describe what's wrong**

The SELECT statement should output results normally, but it threw an exception.

**Does it reproduce on recent release?**

It can be reproduced in the latest version.

**How to reproduce**

Version: 23.5.1.1 (commit 3e6314675c6467bc4dd78f659bac862f7e9648f8)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/c96ea11f-e2f6-4070-a5ae-d8cccc20b9d1

_Set up database_

```sql
create table t5 (vkey UInt32, pkey UInt32, c18 Float32, c19 UInt32) engine = Log;
insert into t5 values (3, 13000, 73.90, 83);
```

_Bug-triggering query_

```sql
select
  subq_0.pkey as c_1_c1193_15
from
  t5 as subq_0
where sipHash128(0, subq_0.c18,
                 bitShiftRight(case when false then (sipHash128(subq_0.pkey,
                     subq_0.c18, 'S')) else '1' end, 0)
                ) is not null;
```

**Expected behavior**

The SELECT statement is executed without any error.

**Actual behavior**

It throws an exception:
```
Received exception from server (version 23.4.2):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Argument column 'Const(String)' size 1 doesn't match result column size 0 of function sipHash128: while executing 'FUNCTION sipHash128(0 : 2, c18 : 1, bitShiftRight(if(false, sipHash128(pkey, c18, 'S'), '1'), 0) : 8) -> sipHash128(0, c18, bitShiftRight(if(false, sipHash128(pkey, c18, 'S'), '1'), 0)) FixedString(16) : 9'. (LOGICAL_ERROR)
(query: select
  subq_0.pkey as c_1_c1193_15
from
  t5 as subq_0
where sipHash128(0, subq_0.c18,
                 bitShiftRight(case when false then (sipHash128(subq_0.pkey,
                     subq_0.c18, 'S')) else '1' end, 0)
                ) is not null;)
```

**Additional context**

The earliest reproducible version is 22.12 in fiddle: https://fiddle.clickhouse.com/9143f462-6a76-4fe3-96c6-629973d27f32

Before version 22.12, the query can be executed without any error (e.g. no error in 22.11.6.44-alpine, https://fiddle.clickhouse.com/25211646-b6bb-4c6f-ac05-bb6071cfa436). It outputs one row:

```
+--------------+
| c_1_c1193_15 |
+--------------+
|        13000 |
+--------------+
```

**Comment by Avogar** [comment]
Seems like the same problem as in https://github.com/ClickHouse/ClickHouse/issues/50236 and https://github.com/ClickHouse/ClickHouse/issues/50282. Replated PR: https://github.com/ClickHouse/ClickHouse/pull/50279 (it may not fix this bug, but I will investigate in further)
