### ISSUE TITLE
grants access/use named collections

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#50277]
Named collections is powerful feature.

When you create a named collection it became accessible to all users. There is no way to restrict this access.

I propose to implement a new feature `grant USE named collection collection1 to user1`.
any verb: `USE` or `EXECUTE` or `ACCESS`.

Now named collection is a security flaw. 

1. You create named_collections with access to a S3 bucket -- anybody can use it (XML users/SQL users with access to s3 function).
2. You create named_collections with access to a mysql database -- anybody can access it and moreover anybody can access any database / any table, because mysql function allows to override table.
3. Password can be exposed, because you can override mysql host and query own malicious mysql server, which will grab the password.

---

Also maybe add another feature into named_collections, and forbid override keys:

```
CREATE NAMED COLLECTION mymysql AS
user = 'myuser',
password = 'mypass',
host = '127.0.0.1',
port = 3306,

allow_to_override = false         --<<<<<----

;
```

Or `allow_to_modify` or `modifiable`

**Comment by den-crane** [comment]
@alexey-milovidov

**Comment by UnamedRus** [comment]
Another idea is 

> allow_to_override = false         --<<<<<----

Could be per key=value pair property

```
CREATE NAMED COLLECTION mymysql AS
user = 'myuser' OVERRIDABLE,
password = 'mypass',
host = '127.0.0.1',
port = 3306,

allow_to_override = false         --<<<<<----

;```

**Comment by kssenii** [comment]
> This task is already discussed - ACL for named collections.

yes, but currently there are only grants for `CREATE/SHOW/ALTER/DROP NAMED COLLECTION`, but not for use `USE`, added it here https://github.com/ClickHouse/ClickHouse/pull/50625.

**Comment by kssenii** [comment]
Part of the proposed is implemented in https://github.com/ClickHouse/ClickHouse/pull/50625.
Part with `"allow_to_override"` will add in a separate PR.

**Comment by kssenii** [comment]
> @kssenii I could work on this issue if it's okay for you.

yes, thank you!

> The idea would be to work on something like what was proposed https://github.com/ClickHouse/ClickHouse/issues/50277#issuecomment-1565162706: a new keyword to allow overrides

yes, looks good.

> denied by default with a global setting to control whether this new behaviour is enabled on not (to not break existing setups).

I'd rather have a server level config setting like "allow_named_collection_override_by_default" which is true by default (for compatibility).
