### ISSUE TITLE
 the connection loss of the clickhouse -> zookeeper when excuting "alter drop projection". 

### ISSUE THREAD

**Issue by fuziru1** [ClickHouse/ClickHouse#50286]
Hi author, I encounter a question when I execute the SQL "alter table ssb1.test_projection drop projection project_test;".  the table ssb1.test_projection is 1shared2prelicas with the diskS3,  allow_remote_fs_zero_copy_replication = true; when the table has differ part number, it has two result:
  1. work exception. the session of clickhouse -> zookeeper snap out,  when the table ssb1.test_projection  has 10000 part. Meanwhile the other tables becoming Read-Only.
  2. work well.  when the table ssb1.test_projection  has 2000 part 

the scene with executing Step{1-3} :
```
Step1 :
create table ssb1.test_projection on cluster cluster_1shard_2replicas
(
   timestamp DateTime,
   ne Int32,
   request_id String,
  a    String,
  b Int32,
  PROJECTION project_test 
  (
         select * order by ne, a
   )
)  engine = ReplicateMergeTree('/clickhouse/tables/{shard}/ssb1.test_prejection', '{replica}')
partition by toDate(timestamp)
order by (request_id)
SETTINGS storage_policy = 'disks3', min_bytes_for_wide_part = 0, allow_remote_fs_zero_copy_replication = 1;

Step2:  to make the table have 10000 parts;
insert into ssb1.test_projection select '2022-05-11 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-12 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-13 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-14 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-15 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-16 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-17 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-18 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-19 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);
insert into ssb1.test_projection select '2022-05-21 12:13:00' number/2, 1, '1', '2', number/4 from numbers(1000);


Step3:
"alter table ssb1.test_projection drop projection project_test;"
```

`the Step3 results`:
Received exception from server (version 22.3.6):
Code: 999 DB:exception: Received from 10.31.33.111:9000. DB:exception: Connection loss. (KEEPER_EXCEPTION).

notice: the 'DB:exception: Connection loss.' in the clickhouse-server.log is the session the clickhouse->zookeeper expired.

**Comment by den-crane** [comment]
set https://github.com/ClickHouse/ClickHouse/issues/11933#issuecomment-661310032

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-zookeeper/jvm-sizes-and-garbage-collector-settings/

`-Djute.maxbuffer=8388608`
