### ISSUE TITLE
Wrong result of SELECT statement with compile_expressions in recent commits (affected version: 21-23.5.1)

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50283]
**Describe what's wrong**

The SELECT statement with contradictory WHERE conditions should return empty results. However, it outputs one row.

**Does it reproduce on recent release?**

It can be reproduced in the latest version.

**How to reproduce**

Version: 23.5.1.1 (commit 3e6314675c6467bc4dd78f659bac862f7e9648f8)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/7b30dc3b-efea-4b23-937c-6fcb19893bbc

_Set up database_

```sql
create table t1 (c6 UInt32, c7 UInt32, primary key(c6)) engine = MergeTree;
insert into t1 values (76, 57);
```

_bug-triggering query_

```sql
select
    c_5_c1470_1 as c_2_c1479_2
  from
    (select
          stddevSamp(ref_10.c6) as c_5_c1470_1
        from
          t1 as ref_10) as subq_1
  where ((subq_1.c_5_c1470_1 = subq_1.c_5_c1470_1)
        and (not (subq_1.c_5_c1470_1 = subq_1.c_5_c1470_1)));
```

**Expected behavior**

The query must output empty because the conditions `(subq_1.c_5_c1470_1 = subq_1.c_5_c1470_1)` and `(not (subq_1.c_5_c1470_1 = subq_1.c_5_c1470_1))` are contradictory. 

**Actual behavior**

It outputs one row
```
+-------------+
| c_2_c1479_2 |
+-------------+
|         nan |
+-------------+
```

**Additional context**

1. At the first several times, the query output an empty result. But after several tries, the results become incorrect, similar as #50039
2. This bug still exists after the fix for https://github.com/ClickHouse/ClickHouse/issues/50039
3. if `set compile_expressions = 0`, the bug disappears, so it should be also related to compile_expressions.
4. The earliest reproducible version is 21 in fiddle: https://fiddle.clickhouse.com/617e1e6d-8e5c-41a7-acca-31c8bff38e04, which is different from #50269 (only head version).
5. Before version 21, the query outputs empty (e.g. 21.12.4.1-alpine: https://fiddle.clickhouse.com/c16460b5-3011-4fa9-b641-c0266a227c14).

**Comment by alexey-milovidov** [comment]
@JZuming Thank you!

It was intended behavior for NaNs; see the comment: https://github.com/ClickHouse/ClickHouse/pull/50287/files#diff-efc7dfb3281a1d7695917227c3693049da6206cbb388d4f4b81035ec6366c20eL1233

Nevertheless, we fixed it.
