### ISSUE TITLE
Undetermined results of SELECT statement using bitShiftRight

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50281]
**Describe what's wrong**

The SELECT statement should output the same results at different times, but it did not.

**Does it reproduce on recent release?**

It can be reproduced in the latest version.

**How to reproduce**

Version: 23.5.1.1 (commit 3e6314675c6467bc4dd78f659bac862f7e9648f8)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/c692c213-5fd9-4f93-a2d0-702dc9eff08e

_Set up database_

```sql
create table t1 (pkey UInt32, c5 UInt32, c7 UInt32, primary key(pkey)) engine = MergeTree;
insert into t1 values (40000, 73, 1);
insert into t1 values (52000, 85, 1);
insert into t1 values (53000, 1, 8);
insert into t1 values (59000, 1, 72);
insert into t1 values (62000, 16, 17);
```

_Bug-triggering query_

```sql
select 
    count(*)
  from 
    t1 as ref_14
  where ref_14.c7 <= bitShiftRight(ref_14.c5, ref_14.pkey);
```

**Expected behavior**

The SELECT statement should always output the same results at different times.

**Actual behavior**

It output different results when ClickHouse execute this query multiple times:
```
First try:
0
Second try:
0
Third try:
0
Fourth try:
2
Fifth try:
2
```

**Additional context**

The earliest reproducible version is 21 in fiddle: https://fiddle.clickhouse.com/88a0858d-351f-4bc4-86f5-7fd51f372411

Before version 21, the query output the same results at different tries (e.g. in 20.12.8.5-alpine, https://fiddle.clickhouse.com/7f2a63f9-ae8b-4a0a-aead-889f12e34c83). It outputs:

```
First try:
2
Second try:
2
Third try:
2
Fourth try:
2
Fifth try:
2
```

**Comment by alexey-milovidov** [comment]
@JZuming The bit shift for an amount larger than the data type size is an undefined behavior: - in ClickHouse; - in C++; - in CPU.
