### ISSUE TITLE
how i can use udf function xml file like test_function.xml and  graphite_rollup.xml used together

### ISSUE THREAD

**Issue by yehaotong** [ClickHouse/ClickHouse#50289]
when i add a test_function.xml on /etc/clickhouse-server/,the content is : 
`<functions>
    <function>
        <type>executable</type>
        <name>test_function_python</name>
        <return_type>String</return_type>
        <argument>
            <type>UInt64</type>
            <name>value</name>
        </argument>
        <format>TabSeparated</format>
        <command>test_function.py</command>
    </function>
</functions>`
and it can use select test_function_python(toUInt(2)) no problem,but when i add a graphite_rollup.xml file on /etc/clickhouse-server/conf.d,the content is : 
`<?xml version="1.0" ?>
<yandex>
    <graphite_rollup>
        <path_column_name>tags</path_column_name>
        <time_column_name>ts</time_column_name>
        <value_column_name>val</value_column_name>
        <version_column_name>updated</version_column_name>
        <default>
            <function>avg</function>
            <retention>
                <age>0</age>
                <precision>10</precision>
            </retention>
            <retention>
                <age>86400</age>
                <precision>30</precision>
            </retention>
            <retention>
                <age>172800</age>
                <precision>300</precision>
            </retention>
        </default>
    </graphite_rollup>`
and something went wrong , I saw the log: 
`Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/test_function.xml'.`
printing non-stop，It looks like these two file configurations are incompatible，how I can fix?

**Comment by cangyin** [comment]
your configuration content of graphite_rollup is wrong, which should be like:
```xml
<clickhouse>
    <graphite_rollup>
        <path_column_name>tags</path_column_name>
        <time_column_name>ts</time_column_name>
        <value_column_name>val</value_column_name>
        <version_column_name>updated</version_column_name>
        <default>
            <function>avg</function>
            <retention>
                <age>0</age>
                <precision>10</precision>
            </retention>
            <retention>
                <age>86400</age>
                <precision>30</precision>
            </retention>
            <retention>
                <age>172800</age>
                <precision>300</precision>
            </retention>
        </default>
    </graphite_rollup>
</clickhouse>
```

BTW, the log
```
Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/test_function.xml'.
```
does not give much information, you should copy the error log right below or above it.

**Comment by yehaotong** [comment]
> 

Hello, I can only obtain this information from the log
`Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/test_function.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/desen_function.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/test_function.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/desen_function.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/test_function.xml'.
Merging configuration file '/etc/clickhouse-server/conf.d/graphite_rollup.xml'.
Processing configuration file '/etc/clickhouse-server/desen_function.xml'.`
And I keep scrolling all the time, whether I jump to debug or trace the logs, and I will graphic_ rollup.xml is adjusted to:
`<clickhouse>
    <graphite_rollup>
    </graphite_rollup>
</clickhouse>
`
the same phenomenon, like graphite_ Rollup.xml and *_function.xml  two configurations have never been compatible

**Comment by cangyin** [comment]
seems like you are running ClickHouse in Kubernetes? try get into the POD, and find the log directory (default to `/var/log/clickhouse-server/`), and do

```sh
tail -f clickhouse-server.log
```
you can see detailed logging information.

later times, you can turn on config `logger.console` in order the ClickHouse logs can be captured by Kubernetes.

**Comment by yehaotong** [comment]
> seems like you are running ClickHouse in Kubernetes? try get into the POD, and find the log directory (default to `/var/log/clickhouse-server/`), and do
> 
> ```shell
> tail -f clickhouse-server.log
> ```
> 
> history logs are compressed as clickhouse-server.log.N.gz files.
> 
> later times, you can turn on config `logger.console` in order the ClickHouse logs can be captured by Kubernetes.

I was run on docker compose on docker container,and I find tihs error log on /var/log/clickhouse-server/clickhouse-server.err.log:
`
2023.05.29 02:21:40.694191 [ 69 ] {} <Error> ExternalUserDefinedExecutableFunctionsLoader: Failed to load config file '/etc/clickhouse-server/test_function.xml': Poco::Exception. Code: 1000, e.code() = 0, Exception: Failed to merge config with '/etc/clickhouse-server/conf.d/graphite_rollup.xml': Exception: Root element doesn't have the corresponding root element as the config file. It must be <functions>, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1b540eec in /usr/bin/clickhouse
1. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::__1::shared_ptr<Poco::Event> const&) @ 0x1740314d in /usr/bin/clickhouse
2. DB::ConfigProcessor::loadConfig(bool) @ 0x17403452 in /usr/bin/clickhouse
3. DB::ExternalLoaderXMLConfigRepository::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15e4f5a4 in /usr/bin/clickhouse
4. DB::ExternalLoader::LoadablesConfigReader::readFileInfo(DB::ExternalLoader::LoadablesConfigReader::FileInfo&, DB::IExternalLoaderConfigRepository&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x15e42b05 in /usr/bin/clickhouse
5. DB::ExternalLoader::LoadablesConfigReader::readRepositories(std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0x15e3f789 in /usr/bin/clickhouse
6. DB::ExternalLoader::LoadablesConfigReader::read() @ 0x15e309f3 in /usr/bin/clickhouse
7. DB::ExternalLoader::PeriodicUpdater::doPeriodicUpdates() @ 0x15e4890a in /usr/bin/clickhouse
8. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ExternalLoader::PeriodicUpdater::*)(), DB::ExternalLoader::PeriodicUpdater*>(void (DB::ExternalLoader::PeriodicUpdater::*&&)(), DB::ExternalLoader::PeriodicUpdater*&&)::'lambda'()::operator()() @ 0x15e4a9f7 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb7a7ba7 in /usr/bin/clickhouse
10. ? @ 0xb7ab5dd in /usr/bin/clickhouse
11. ? @ 0x7f4882d2e609 in ?
12. __clone @ 0x7f4882c53133 in ?
 (version 22.4.5.9 (official build))
2023.05.29 02:21:45.697064 [ 69 ] {} <Error> ExternalUserDefinedExecutableFunctionsLoader: Failed to load config file '/etc/clickhouse-server/desen_function.xml': Poco::Exception. Code: 1000, e.code() = 0, Exception: Failed to merge config with '/etc/clickhouse-server/conf.d/graphite_rollup.xml': Exception: Root element doesn't have the corresponding root element as the config file. It must be <functions>, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1b540eec in /usr/bin/clickhouse
1. DB::ConfigProcessor::processConfig(bool*, zkutil::ZooKeeperNodeCache*, std::__1::shared_ptr<Poco::Event> const&) @ 0x1740314d in /usr/bin/clickhouse
2. DB::ConfigProcessor::loadConfig(bool) @ 0x17403452 in /usr/bin/clickhouse
3. DB::ExternalLoaderXMLConfigRepository::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15e4f5a4 in /usr/bin/clickhouse
4. DB::ExternalLoader::LoadablesConfigReader::readFileInfo(DB::ExternalLoader::LoadablesConfigReader::FileInfo&, DB::IExternalLoaderConfigRepository&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x15e42b05 in /usr/bin/clickhouse
5. DB::ExternalLoader::LoadablesConfigReader::readRepositories(std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) @ 0x15e3f789 in /usr/bin/clickhouse
6. DB::ExternalLoader::LoadablesConfigReader::read() @ 0x15e309f3 in /usr/bin/clickhouse
7. DB::ExternalLoader::PeriodicUpdater::doPeriodicUpdates() @ 0x15e4890a in /usr/bin/clickhouse
8. ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ExternalLoader::PeriodicUpdater::*)(), DB::ExternalLoader::PeriodicUpdater*>(void (DB::ExternalLoader::PeriodicUpdater::*&&)(), DB::ExternalLoader::PeriodicUpdater*&&)::'lambda'()::operator()() @ 0x15e4a9f7 in /usr/bin/clickhouse
9. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb7a7ba7 in /usr/bin/clickhouse
`

**Comment by yehaotong** [comment]
<Error> ExternalUserDefinedExecutableFunctionsLoader: Failed to load config file '/etc/clickhouse-server/test_function.xml': Poco::Exception. Code: 1000, e.code() = 0, Exception: Failed to merge config with '/etc/clickhouse-server/conf.d/graphite_rollup.xml': Exception: Root element doesn't have the corresponding root element as the config file. It must be <functions>, Stack trace (when copying this message, always include the lines below):

**Comment by yehaotong** [comment]
> seems like you are running ClickHouse in Kubernetes? try get into the POD, and find the log directory (default to `/var/log/clickhouse-server/`), and do
> 
> ```shell
> tail -f clickhouse-server.log
> ```
> 
> history logs are compressed as clickhouse-server.log.N.gz files.
> 
> later times, you can turn on config `logger.console` in order the ClickHouse logs can be captured by Kubernetes.

can I link you on your qq?  I sent a friend request on your qq

**Comment by cangyin** [comment]
cf: #47493

**Comment by yakov-olkhovskiy** [comment]
same as #47485
