### ISSUE TITLE
Unexpected error: Amount of memory requested to allocate is more than allowed (CANNOT_ALLOCATE_MEMORY)

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50282]
**Describe what's wrong**

The SELECT statement should output results normally, but it threw an exception.

**Does it reproduce on recent release?**

It can be reproduced in the latest version.

**How to reproduce**

Version: 23.5.1.1 (commit 3e6314675c6467bc4dd78f659bac862f7e9648f8)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/3baedf23-b65f-48d9-96f3-b6e0e24c55e4

_Set up database_

```sql
create table t2 (c11 Float32, primary key(c11)) engine = MergeTree;
insert into t2 values (1.0);
```

_Bug-triggering query_

```sql
select  
  ref_0.c11 as c_4_c3197_0
from 
  t2 as ref_0
where (bitShiftLeft(case when (ref_0.c11 is null) then '' else '' end, 1) 
      || (case when (ref_0.c11 < ref_0.c11) then '1' else '' end)) is not null;
```

**Expected behavior**

The SELECT statement is executed without any error.

**Actual behavior**

It throws an exception:
```
Received exception from server (version 23.4.2):
Code: 173. DB::Exception: Received from localhost:9000. DB::Exception: Amount of memory requested to allocate is more than allowed: while executing 'FUNCTION concat(bitShiftLeft(if(isNull(c11), '', ''), 1) : 8, if(less(c11, c11), '1', '') : 7) -> concat(bitShiftLeft(if(isNull(c11), '', ''), 1), if(less(c11, c11), '1', '')) String : 9'. (CANNOT_ALLOCATE_MEMORY)
(query: select  
  ref_0.c11 as c_4_c3197_0
from 
  t2 as ref_0
where (bitShiftLeft(case when (ref_0.c11 is null) then '' else '' end, 1) 
      || (case when (ref_0.c11 < ref_0.c11) then '1' else '' end)) is not null;)
```

**Additional context**

The earliest reproducible version is 22 in fiddle: https://fiddle.clickhouse.com/e966ca0d-28ac-47ff-883d-499f1c9bb3ea

Before version 22, the query can be executed without any error (e.g. no error in 21.12.4.1-alpine, https://fiddle.clickhouse.com/65065a1c-dbbe-4b56-ae71-073de2f6daaf). It outputs one row:

```
+-------------+
| c_4_c3197_0 |
+-------------+
|           1 |
+-------------+
```

**Comment by Avogar** [comment]
Interesting:
```
avogar-dev :) select bitShiftRight(if(materialize(1), '1', '1'), 1)  from numbers(1)

SELECT bitShiftRight(if(materialize(1), '1', '1'), 1)
FROM numbers(1)

Query id: a9ace4bf-439b-4bcd-91aa-4713e1a4131e

┌─bitShiftRight(if(materialize(1), '1', '1'), 1)─┐
│                                                │
└────────────────────────────────────────────────┘
┌─bitShiftRight(if(materialize(1), '1', '1'), 1)─┐
│                                                │
└────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.013 sec.
```

Returns 2 rows instead of 1. I will investigate

**Comment by Avogar** [comment]
Seems like the same issue as in https://github.com/ClickHouse/ClickHouse/issues/50236. Some bug in function `if`. Related PR: https://github.com/ClickHouse/ClickHouse/pull/50279
