### ISSUE TITLE
Slow queries when querying from distributed table

### ISSUE THREAD

**Issue by seeIT-51** [ClickHouse/ClickHouse#50303]
**Describe the unexpected behaviour**
After upgrading from v21.8.15.7 to v22.8.16.32,  we found that the same query on Distributed engine spend much more time (more than 18 seconds) than corresponding MergeTree table (only more than 1 second).  
![image](https://github.com/ClickHouse/ClickHouse/assets/16160730/8c501e69-e252-41b9-9ad3-a1eea7c76449)
![image](https://github.com/ClickHouse/ClickHouse/assets/16160730/1245d28b-4450-46f6-b849-8f4233e082df)

But at version  v21.8.15.7, the time spend on queries to Distributed and MergeTree are nearly the same.

**How to reproduce**
* We are using v22.8.16.32
* settings are as follows:
![image](https://github.com/ClickHouse/ClickHouse/assets/16160730/f2078675-9b2b-4ae4-a7b7-003989fa13be)
cluster config is as follows:
![image](https://github.com/ClickHouse/ClickHouse/assets/16160730/acfa77ed-00dc-4556-a162-0bea0d5ec186)

* session_local is a mergetree table 
![image](https://github.com/ClickHouse/ClickHouse/assets/16160730/293d9564-3932-44a4-9d8d-a08b8998ab17)  
session is a distributed table of session_local
![image](https://github.com/ClickHouse/ClickHouse/assets/16160730/57fd0fb4-b960-4059-9b99-2e3faf3c5655)

* Queries to run that lead to unexpected result
`SELECT uid,last_packet,first_packet,src_port,dst_port,protocols,node,src_mac,dst_mac,dst_ip_v4,dst_ip_v6,src_ip_v4,src_ip_v6 FROM session_local WHERE (last_packet >= '1682417471435000000' AND last_packet < '1685009461000000000')  order by last_packet desc limit 0,10;`

**Expected behavior**
Query to Distributed table spend nearly the same time as query to Mergetree table.

**Additional context**
Comparing the trace log, I found that MergingSortedTransform time on query to Distributed  is much more than query to Mergetree table. 
![image](https://github.com/ClickHouse/ClickHouse/assets/16160730/2ca40720-7127-4256-a626-77d943a0083a)

**Comment by den-crane** [comment]
Please share `ping localhost`

**Comment by kkkaaa2010** [comment]
> Please share `ping localhost` and `select name,value from system.settings where changed`

1. `ping localhost` 
![1685437939107](https://github.com/ClickHouse/ClickHouse/assets/16028400/55398082-4ae5-4887-b82d-41f6039cbd4a)

2. `select name,value from system.settings where changed`
![1685438014034](https://github.com/ClickHouse/ClickHouse/assets/16028400/ad949efd-e760-4c19-8c44-644847cd949f)

@den-crane  Looking forward to your reply

**Comment by kkkaaa2010** [comment]
> try the same query with an append `.... settings distributed_aggregation_memory_efficient=0`

I tried, but this setting is not working

![企业微信截图_1685504158342](https://github.com/ClickHouse/ClickHouse/assets/16028400/0382ba79-7aeb-47f6-b531-967bbd085886)

**Comment by den-crane** [comment]
Can you please share

```
select Names, Values 
from system.query_log array join  ProfileEvents.Names as Names,  ProfileEvents.Values as Values
 where query_id = '...' and type=2;
```
for both queries ?

**Comment by kkkaaa2010** [comment]
@den-crane 

Thank you to help. The two queries are basically the same.

![image](https://github.com/ClickHouse/ClickHouse/assets/16028400/e5b0c429-d012-4e97-9272-ab6d50ac9cf6)

**Comment by kkkaaa2010** [comment]
I discovered another situation. 
Debug log shows, MemoryTracker requests 1GB of memory each time, and the distributed table takes approximately 5 seconds.
Is it possible that this is the reason?

![1](https://github.com/ClickHouse/ClickHouse/assets/16028400/0c403723-ca6a-4791-8b43-812b3597afdb)

![2](https://github.com/ClickHouse/ClickHouse/assets/16028400/62f8e9b5-fb03-45cf-af4d-c1fa62d8bf2c)

**Comment by kkkaaa2010** [comment]
> JFYI: I hate pictures. I don't look at them. It's a torture.
> 
> Please share `select * from system.replicas where table= 'session_local' \G;`

No results in `system.replicas`.

**Comment by den-crane** [comment]
Interesting that queryprofilerruns is very different.

try 

```
$ cat /etc/clickhouse-server/config.d/z_log_disable.xml
<?xml version="1.0"?>
<clickhouse>
    <asynchronous_metric_log remove="1"/>
    <metric_log remove="1"/>
    <query_thread_log remove="1" />  
    <query_log remove="1" />
    <query_views_log remove="1" />
    <part_log remove="1"/>
    <session_log remove="1"/>
    <text_log remove="1" />
    <trace_log remove="1"/>
    <crash_log remove="1"/>
    <opentelemetry_span_log remove="1"/>
    <zookeeper_log remove="1"/>
</clickhouse>
```
and restart CH

**Comment by kkkaaa2010** [comment]
@den-crane Hi, my friend, I upgrade 22.8.16.32 to 22.12.6.22, and the problem has disappeared! I don't know why.

Anyway, thank you very much!
