### ISSUE TITLE
Wrong results of SELECT statement with cityHash64

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50320]
**Describe what's wrong**

The two semantically-equivalent SELECT statements should output the same results, but they did not.

**Does it reproduce on recent release?**

It can be reproduced in the latest version.

**How to reproduce**

Version: 23.5.1 (commit 806ef08e5f6b3fc93993d19aac505290e9bfa554)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/1a7bd380-e863-41da-a50e-bacdaeeae528

_Set up database_

```sql
create table t1 (c10 UInt32, c12 Float32) engine = MergeTree order by c10;
create table t4 (vkey UInt32, c26 Float32) engine = MergeTree order by vkey;
insert into t1 values (41, 26.14);
```

_SELECT statement 1_

```sql
select  
   count(*)
  from 
    t4 as ref_4
      right outer join t1 as ref_5
      on (ref_4.c26 = ref_5.c12)
  where ((case when 1 = 1 then 0 else (ref_5.c10 - ref_5.c10) end) + cityHash64(0, 0, 0)) >= 1;
```

As `(case when 1 = 1 then 0 else (ref_5.c10 - ref_5.c10) end)` can be replaced with `0`, I get the semantically-equivalent SELECT statement:

_SELECT statement 2_

```sql
select  
   count(*)
  from 
    t4 as ref_4
      right outer join t1 as ref_5
      on (ref_4.c26 = ref_5.c12)
  where (0 + cityHash64(0, 0, 0)) >= 1;
```

**Expected behavior**

The two SELECT statements output the same results.

**Actual behavior**

They are different.

SELECT statement 1 outputs:
```
+---------+
| count() |
+---------+
|       0 |
+---------+
```

SELECT statement 2 outputs:
```
+---------+
| count() |
+---------+
|       1 |
+---------+
```

**Additional context**

The earliest reproducible version is 18 in fiddle: https://fiddle.clickhouse.com/b1b47fb8-372d-4a82-b5c6-c146d89f352c

**Comment by alexey-milovidov** [comment]
Minimal example:
```
explain syntax select 1 where (if(1 = 1, 0, 1 - 1) + cityHash64(0, 0, 0)) > 0;
```

**Comment by yakov-olkhovskiy** [comment]
Apparently the result of `if(1 = 1, 0, 1 - 1)` has type of `Int16` and `cityHash64(0, 0, 0)` is `UInt64` = 13941544710297623600 (most significant bit is set), and `plus` promotes calculation to signed Int64 - as a result we have a negative number.

**Comment by alexey-milovidov** [comment]
Behaves according to the specs.

**Comment by yakov-olkhovskiy** [comment]
Clarification:
During arithmetic addition/subtraction we promote integers to signed upper binary - i.e. UInt16=>Int32, Uint8=>Int16 and so on - in order to solve integer overflow problem. However 64 bit is a maximum for automatic promotion, as a result if an argument of arithmetic addition/subtraction is 64 bit then then overflow is still possible.
As a workaround I would suggest an implicit promotion:
```
...
where ((case when 1 = 1 then 0 else (ref_5.c10 - ref_5.c10) end)::Int128 + cityHash64(0, 0, 0)) >= 1;
```

**Comment by JZuming** [comment]
Thank you @alexey-milovidov @yakov-olkhovskiy for explaining it! I see. I will then adjust the test-case generation methods of my fuzzer.
