### ISSUE TITLE
The query with rowNumberInAllBlocks produces unstable results

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#50333]
**Describe the unexpected behaviour**
The query with rowNumberInAllBlocks produces unstable results.

**How to reproduce**
https://fiddle.clickhouse.com/3c761263-d3ad-4e8d-8703-7ed55a88635b
```
drop table if exists table1;

create table table1 (`A` LowCardinality(String), `B` LowCardinality(String)) engine=MergeTree order by `B`;
insert into table1 values('a', 'b2');
insert into table1 values('a', 'b1');
insert into table1 values('a', 'b3');

select c1, c2 , groupArray(c2) over (partition by c1 order by c0 ASC) AS res   from (select rowNumberInAllBlocks() as c0, `A` as c1 , `B` as c2 from table1 order by `B` ASC) order by c2 ASC;

```

**Expected Result**
Run the query for several times, you will find that the result varis. I feel the result at least should be stable.

**Comment by den-crane** [comment]
Can be hacked

```sql
select c1, c2 , groupArray(c2) over (partition by c1 order by c0 ASC) AS res   
from (
          select rowNumberInAllBlocks() as c0, `A` as c1 , `B` as c2 from table1 order by `B` ASC 
          limit 10000000000
          ) 
order by c2 ASC;
```

--
Disclaimer: I want to clarify that I am just an ordinary person on the Internet.
I have no connection or association with Clickhouse, Inc. or its development team.
It is important to note that my opinion holds no value and should not be considered.

**Comment by Alex-Cheng** [comment]
@den-crane 
Although you are not from ClickHouse team, you are obviously professional on ClickHouse.

**Comment by Alex-Cheng** [comment]
@den-crane  BTW, why adding `limit` clause can resolve the problem. I see the only difference is the adding of `limit` caluse.

**Comment by den-crane** [comment]
Because your query is slightly incorrect. `rowNumber` should be in the outer select of ORDERBY (sourced by ordered stream).

like this

```sql
select c1, c2 , groupArray(c2) over (partition by c1 order by c0 ASC) AS res   
from (
          select rowNumberInAllBlocks() as c0, `A` as c1 , `B` as c2
          from  
                      (   ---- here we make ordered stream for rowNumberInAllBlocks
                           select * from table1 order by `B`
                  )
          ) 
order by c2 ASC;
```

Because of this incorrectness the optimization of excessive orderbys uses the opportunity and removes `order by B`.

`limit 10000000000` prevents this optimization.
