### ISSUE TITLE
Truncate fails to remove part from zookeeper

### ISSUE THREAD

**Issue by SmitaRKulkarni** [ClickHouse/ClickHouse#50341]
Truncate removes the part locally but fails to remove from zookeeper (could be due to any issue on keeper like connection lost). 
After restarting server, this causes clickhouse to read the part from zookeeper and report it as 'part lost forever'.

**Comment by tavplubix** [comment]
AFAIK, it's not possible, because `DROP_RANGE` (`TRUNCATE` works on top of it) removes parts from ZooKeeper first, and only after that it removes parts from disk. Do you have some logs showing the opposite?

**Comment by tavplubix** [comment]
https://github.com/ClickHouse/ClickHouse/blob/e4c8c4cecfb80c4afdae961c4ab8a64d42dc84d9/src/Storages/StorageReplicatedMergeTree.cpp#L1939-L2004
