### ISSUE TITLE
Incorrect query results when added hardcoded column which matches a filter column

### ISSUE THREAD

**Issue by geopet85** [ClickHouse/ClickHouse#50351]
Apologies for the weird title but I couldn't find a better one.

**Describe what's wrong**

I am getting incorrect results when adding a hardcoded column in the results, which matches the filtering column: 

```
CREATE TABLE users (test Int16) ENGINE=MergeTree() order by test;

INSERT INTO users select number from numbers(10);

SELECT count(*) as count FROM users where test=1;

// this returns 1

SELECT count(*) as count, 1 as test FROM users where test=1;

// this returns 10, 1
```

https://fiddle.clickhouse.com/a7ecbe9b-93f6-438a-8cf6-1740a528d61d

**Does it reproduce on recent release?**

I believe it applies to every single release. 

**Expected behavior**

Is this expected? It seems like the filtering occurs as a later step?

I am not getting a similar behaviour in Postgres:

```
create table test (test Int8);

insert into test select generate_series (1,10);

select count(*) from test where test=1;

// this returns 1 in postgres

select count(*), 1 as test from test where test=1;

// this returns 1, 1 in postgres
```

**Comment by den-crane** [comment]
This expected behaviour. Column aliases in CH behaves differently and more profound than the other databases.

In Clichkouse it's possible to do 

```
select x 
from ...
where (a as x) = 10
group by ((y%10) as a) as y
```

see workarounds https://fiddle.clickhouse.com/70920710-08e2-4076-a087-3428c9653481



https://clickhouse.com/docs/en/operations/settings/settings#prefer-column-name-to-alias
