### ISSUE TITLE
How to run the independent tests locally?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#50388]
I modified source code of ClickHouse and want to check if I break anything. However I found some of test cases are dependent that requires additional prerequisition, e.g. test `02124_clickhouse_dictionalry_with_predefined_configuration` requires a predefeined dictionary in ClickHouse configuration.

Thus I want to run the tests which not require any prerequisitions. What should I do if I just want to run all independent tests(not require any prerequistion, e.g. 02124_uncompressed_cache)?

Thank you.

**Comment by CheSema** [comment]
What the config do you use?
That tests needs special section in config. That section is provided in our test config here: https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/named_collection.xml. Most likely you need to just update the configs.

**Comment by al13n321** [comment]
I don't think there's a flag or list of tests that work with minimal server config. There's `--fast-tests-only` and `--no-shard`, but even then many tests require various specific things to be present in config, like replicas and disks.

Some possible ways to go about it:
 * Run all tests on master, grep the list of names of tests that passed, then run those tests with your changes.
 * Send a draft pull request and see what fails in CI. This may require approval from someone on the ClickHouse team to kick off the CI.
 * Run the server with the whole `tests/config/config.d` as the config. I'm not sure whether this requires running multiple servers (on the same host), and how difficult it is to set up. Might be easy, but I haven't tried.
 * Find tests relevant to your changes (by searching in `tests/queries/0_stateless`) and run just them.
 * Run all tests with `--fast-tests-only` and `--no-shard`, then skim the results to look for real failures. Not-real failures are usually obvious by errors saying that things are missing from config.

**Comment by Alex-Cheng** [comment]
> What the config do you use? That test needs special section in config. That section is provided in our test config here: https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/named_collection.xml. Most likely you need to just update the configs.

I use my own config.xml file without [named_collection.xml](https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/named_collection.xml). So I should use the config.xml and relatives from ClickHouse repository.

**Comment by CheSema** [comment]
> > What the config do you use? That test needs special section in config. That section is provided in our test config here: https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/named_collection.xml. Most likely you need to just update the configs.
> 
> I use my own config.xml file without [named_collection.xml](https://github.com/ClickHouse/ClickHouse/blob/master/tests/config/config.d/named_collection.xml). So I should use the config.xml and relatives from ClickHouse repository.

Yes, it is supposed that tests work with the config from the repository.

**Comment by Alex-Cheng** [comment]
Many thanks to all of you.
