### ISSUE TITLE
clickhouse very slow in my query

### ISSUE THREAD

**Issue by rnrl1215** [ClickHouse/ClickHouse#50380]
CREATE TABLE test.user_log
(
 `created_at` DateTime,
 `user_id` UInt64,
 `age` UInt64,
 `sex` String,
`event_name` String,
`action_name` String,
`keys` Array(String),
`values` Array(String)
)
ENGINE = MergeTree
ORDER BY (created_at, event_name, action_name);

---------------------------------------------------------------
total data : 15,937,504
---------------------------------------------------------------

SELECT COUNT(user_id)
FROM user_log
WHERE created_at BETWEEN '2022-01-11 00:00:00' AND '2023-01-11 23:59:59'
AND event_name = 'cash'
AND action_name = 'deposit'
AND values[1] = '233' -- this is number of  machine 

---------------------------------------------------------------
select result 131,550

why my query slowly?
 
i read that 'In most cases you do not need a partition key'
so i did not define partition by

**Comment by cangyin** [comment]
By what criterion the query is slow, does it cost minutes to finish?

**Comment by den-crane** [comment]
created_at - DateTime , very high cardinal column. By putting it to the leading position you are loosing the ability to position by `event_name, action_name`


try `ORDER BY (event_name, action_name, created_at);`
 
try `partition by toYYYYMM(created_at)  ORDER BY (event_name, action_name, created_at);`

https://kb.altinity.com/engines/mergetree-table-engine-family/pick-keys/

**Comment by den-crane** [comment]
>say that Partitioning does not speed up queries
>Optional. In most cases, you don't need a partition key, and if you do need to partition, generally you do not need a 
>partition key more granular than by month. Partitioning does not speed up queries

It's simplified explanation for newbies to discourage them to use PARTITIONING incorrectly.
