### ISSUE TITLE
Exception: Unknown column, when selecting function of alias from subquery.

### ISSUE THREAD

**Issue by larspars** [ClickHouse/ClickHouse#50417]
**Describe what's wrong**

Selecting functions of aliases in subqueries throws an error.

```
CREATE TABLE t1 (i32 Int32, i32_alias Int32 ALIAS i32) ENGINE = MergeTree ORDER BY i32;

SELECT * FROM (SELECT identity(i32_alias) FROM t1);
```

```
DB::Exception: Unknown column: identity(i32), there are only columns . (UNKNOWN_IDENTIFIER)
```

**Does it reproduce on recent release?**

Yes, it seems broken since 22.3 and up to latest.

**How to reproduce**

See fiddle:

https://fiddle.clickhouse.com/c7a97d9c-d3fa-4cd9-a161-8ad456cb6528

**Comment by vdimir** [comment]
Will be fixed in new analyzer (`SET allow_experimental_analyzer = 1`). I'll check how easy to fix it in current analyzer

**Comment by vdimir** [comment]
Current workaround is to set `SET optimize_respect_aliases = 0`. Feel free to reopen an issue if it's not an option for some readon
