### ISSUE TITLE
After upgrade from version 22.8 lts to version 23.3.2.37 lts, the path of replication in zk disappeared completely and increased ZooKeeperWait 

### ISSUE THREAD

**Issue by i1l-ba** [ClickHouse/ClickHouse#50431]
Describe the issue
After upgrade from version 22.8 lts to version 23.3.2.37 lts, the path of replication in zk disappeared completely and increased ZooKeeperWait and BackgroundSchedulePoolTask

How to reproduce
We are using clickhouse in virtual server(KVM) 5.4.0-70-generic #78~18.04.1-Ubuntu
Setup: 4 shards replicated (8 nodes total).
Using  ReplicatedMergeTree engine (and similar others)
The update procedure included only the change binary files.
Solved by completely restart/restore replica

Problems of ZooKeeperWait,BackgroundSchedulePoolTask still staying 

<img width="914" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/98915297/d2a735a7-b2c2-4a13-9e4b-cc6f18c3a732">

**Comment by den-crane** [comment]
How many Replicated tables do you have?

see https://github.com/ClickHouse/ClickHouse/issues/43647
https://github.com/ClickHouse/ClickHouse/pull/42878#issuecomment-1450520809

```
   <merge_tree>
        <cleanup_delay_period>300</cleanup_delay_period>
        <merge_selecting_sleep_ms>600000</merge_selecting_sleep_ms>
   </merge_tree>
```

**Comment by i1l-ba** [comment]
approximately 100

**Comment by den-crane** [comment]
>Solved by completely restart/restore replica

so, the issue resolved ?

**Comment by i1l-ba** [comment]
it's help to return path in zk

**Comment by den-crane** [comment]
> yes,it's help to return path in zk

clarify please

**Comment by i1l-ba** [comment]
I don't understand why it grew so fast BackgroundSchedulePoolTask ? how is it related to zk waitings ?

**Comment by i1l-ba** [comment]
parameters from https://github.com/ClickHouse/ClickHouse/issues/43647 was helped

**Comment by den-crane** [comment]
zookeeperWait and BackgroundSchedulePoolTask are irrelevant.
