### ISSUE TITLE
Linux 6.1.22 on RISC-V failed to support TaskStats interface

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#50456]
> I've successfully built ClickHouse on today's master but cannot check if it will run. I give about a 30% chance for it.
https://drive.google.com/file/d/1LHwtaPBJlSQYPppPMfUbML99H9UJKy4r/view?usp=sharing

I've started the server of this version of clickhouse on risc-v. But when I execute the SQL, I got this error:

server:
<img width="712" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/37319050/f6397557-d067-4416-a0f8-990068d0fe38">

client:
<img width="709" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/37319050/1a0bfcbd-ba5e-4b13-9704-820ed0c95795">

Operating system

`Linux fedora-riscv 6.1.22 #1 SMP Tue May  9 00:07:19 EDT 2023 riscv64 GNU/Linux`

@alexey-milovidov @ernado 
Any help is much appreciated!

_Originally posted by @Joeywzr in https://github.com/ClickHouse/ClickHouse/issues/40141#issuecomment-1571500633_

**Comment by Joeywzr** [comment]
👍🏻It works.
