### ISSUE TITLE
Not possible to install ClickHouse Server and Keeper on same host

### ISSUE THREAD

**Issue by msestak** [ClickHouse/ClickHouse#50461]
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**

rpm install

**Source of the ClickHouse**

[Release v23.4.2.11-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.4.2.11-stable)
and
[Release v23.4.1.1943-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.4.1.1943-stable)

**Expected result**

It was possible in previous versions of ClickHouse to install server and Keeper on same host. Didn't find in documentation that this is not allowed any more so probably a build issue.

**The actual result**

Installing ClickHouse server and Keeper on same host fails.

**How to reproduce**
RHEL 8.6
```bash
[root@bdtclick01 clickhouse-23.4.1.1943-stable]# yum install clickhouse-client-23.4.1.1943.x86_64.rpm clickhouse-common-static-23.4.1.1943.x86_64.rpm clickhouse-keeper-23.4.1.1943.x86_64.rpm clickhouse-server-23.4.1.1943.x86_64.rpm
Updating Subscription Management repositories.
EPEL8_REPO                                                                                                                                                                                                    83 kB/s | 2.3 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                                                                                                         55 kB/s | 4.1 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                                                                                                      63 kB/s | 4.5 kB     00:00
Error:
 Problem: package clickhouse-keeper-23.4.1.1943-1.x86_64 conflicts with clickhouse-server provided by clickhouse-server-23.4.1.1943-1.x86_64
  - package clickhouse-server-23.4.1.1943-1.x86_64 conflicts with clickhouse-keeper provided by clickhouse-keeper-23.4.1.1943-1.x86_64
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Probably because both rpms (server one and keeper one) pack same binary (/usr/bin/clickhouse-keeper)
```bash
# when keeper installed
# try to install server fails
[root@bdtclick01 clickhouse-23.4.2.11-stable]# rpm2cpio clickhouse-server-23.4.2.11.x86_64.rpm | cpio -idmv
/etc/clickhouse-server/config.xml
/etc/clickhouse-server/users.xml
/etc/init.d/clickhouse-server
/lib/systemd/system/clickhouse-server.service
/usr/bin/clickhouse-copier
cpio: /usr/bin/clickhouse-keeper not created: newer or same age version exists   # <-- ERROR here
/usr/bin/clickhouse-keeper
/usr/bin/clickhouse-report
/usr/bin/clickhouse-server
/usr/share/doc/clickhouse-server/AUTHORS
/usr/share/doc/clickhouse-server/CHANGELOG.md
/usr/share/doc/clickhouse-server/LICENSE
/usr/share/doc/clickhouse-server/README.md
525 blocks
```

**Comment by den-crane** [comment]
>[Release v23.4.2.11-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.4.2.11-stable)
>[Release v23.4.1.1943-stable](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.4.1.1943-stable)
>Probably because both rpms (server one and keeper one) pack same binary (/usr/bin/clickhouse-keeper)

Yes, because they both depend on  clickhouse-common-static package.
Probably it has sense to install the same version -  23.4.2.11

**Comment by den-crane** [comment]
Ah, I see

```
yum install clickhouse-client-23.4.1.1943.x86_64.rpm \
      clickhouse-common-static-23.4.1.1943.x86_64.rpm \
      clickhouse-keeper-23.4.1.1943.x86_64.rpm \
      clickhouse-server-23.4.1.1943.x86_64.rpm

- package clickhouse-server-23.4.1.1943-1.x86_64 conflicts 
 with clickhouse-keeper provided by clickhouse-keeper-23.4.1.1943-1.x86_64
```

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-keeper.yaml#L14

https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-server.yaml#L14

They both have the file https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-server.yaml#L56 and https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-keeper.yaml#L32

Not sure what you try to achieve, but clickhouse-server contains clickhouse-keeper.
