### ISSUE TITLE
Shadow variables in higher order functions/improve error message for naming collisions

### ISSUE THREAD

**Issue by buyology** [ClickHouse/ClickHouse#5046]
On ClickHouse `19.4.54416`:

```sql
:) select sum(c1) v FROM (select 1 c1, ['v'] c2) WHERE arrayExists((v) -> v == 'v')
```

```sql
SELECT sum(c1) AS v
FROM
(
    SELECT
        1 AS c1,
        ['v'] AS c2
)
WHERE arrayExists(v -> (v = 'v'))

Received exception from server (version 19.4.54416):
Code: 184. DB::Exception: Received from localhost:9000. 
DB::Exception: Aggregate function sum(c1) is found in WHERE or PREWHERE in query.

0 rows in set. Elapsed: 0.101 sec.
```

I would expect the arguments specified in `arrayExists` to shadow any column aliases or at least have the error message hint that a collision might be the case.

**Comment by den-crane** [comment]
The problem that you may need to use external columns in lambda function

SELECT sum(c1) AS v
FROM
(
    SELECT
        1 AS c1,
        ['v'] AS c2,
        ['d'] **as d**
)
WHERE arrayExists(i -> (**d** = ['d']), c2)

**Comment by alexey-milovidov** [comment]
I agree, lambda argument name should shadow captured column names.
