### ISSUE TITLE
Multiple APPLY with array lambda wrong sorting

### ISSUE THREAD

**Issue by CMBCKSRL** [ClickHouse/ClickHouse#50462]
I was trying to use `APPLY` modifier in my query to convert all the columns into arrays and then sort them according to the order of one array.

Here is my example:
https://fiddle.clickhouse.com/2a22349b-3dbb-4feb-9af1-bdcda62eb8a4

I expect arraySort to be applied to every `groupArray` column with sorting according to `groupArray(dt_save_row)`, but it seems to simply sort each array without looking at `groupArray(dt_save_row)` order.

May be I am doing something wrong.

It is reproduced on 23.3.2.37 and earlier but on 23.4 this query fails.

**Comment by den-crane** [comment]
AFAIK such APPLY is not supported

Fails with allow_experimental_analyzer https://fiddle.clickhouse.com/c393155a-2b58-48cc-8a26-da4e9b227035

Fails with 23.4 and master https://fiddle.clickhouse.com/ec12a5df-8f87-44c6-9920-f716e4be6222
