### ISSUE TITLE
why client-cli must host

### ISSUE THREAD

**Issue by hustxjs** [ClickHouse/ClickHouse#50464]
i use clickhouse-client connect local host,  why must write --host myIP ? 
if not write it say: Code: 210.DB::NetException:Connectionrefused (localhost:9000)

**Comment by l1t1** [comment]
use `clickhouse local`

**Comment by alexey-milovidov** [comment]
You are using a modified ClickHouse version.

```
client-cli
```

There is not such program as client-cli.

```
Code: 210.DB::NetException:Connectionrefused (localhost:9000)
```

ClickHouse client always correctly prints whitespaces when needed. For example, it will print "Connection refused" instead of "Connectionrefused" as in your version.
