### ISSUE TITLE
Logical error: 'Read unexpected size. ...'

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#50468]
https://s3.amazonaws.com/clickhouse-test-reports/0/0c15a2ddc66e1cabf31537a85e77ae255610c955/stress_test__ubsan_/fatal_messages.txt

**Comment by kssenii** [comment]
https://github.com/ClickHouse/ClickHouse/pull/50470

**Comment by alesapin** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/50833/dc4a2fb07d29a4fe5818a42aa6c17be9bd59ccb7/stress_test__ubsan_.html

**Comment by Algunenano** [comment]
Another one: https://s3.amazonaws.com/clickhouse-test-reports/51160/b1cedf0e42548011e95c3ec09e8245fb44d3e1ce/stress_test__ubsan_.html

**Comment by kssenii** [comment]
Still cannot understand, added more logging https://github.com/ClickHouse/ClickHouse/pull/51187, will wait for failures after it is merged

**Comment by CurtizJ** [comment]
One more failure:

https://s3.amazonaws.com/clickhouse-test-reports/51164/5e500cc799ced3b183bb1aefdf56aa7cb2e83646/stress_test__ubsan_.html

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/51499/fe6031e480fd4ae3db018a379e67a9d2f1c04480/stress_test__ubsan_.html
