### ISSUE TITLE
Question: two CH instance startup on the same one data folder

### ISSUE THREAD

**Issue by athree** [ClickHouse/ClickHouse#50460]
my test clickhouse is 22.9.

i startup two CH instance on the same data folder with config.lsiten_reuse_port=1, it seems the two instance both works well on Select. 
1. Is it supported by designed?
2. if not support, where is the corner bad case i would get?
3. if support, does the two instance has a sync same view on databases/tables/parts? 

Additional：
1. the two CH instance work on same listen port;
2. the same data folder means: i make two empty different directory(e.g DA/DB) for the two instance(e.g IA/IB) as config.path. And there is another exist directory(e.g DE) with data, i just link "DE/metadata, DE/data, DE/store" to "DA/metadata, DA/data, DA/store" and same to "DB/metadata, DB/data, DB/store". Then the two instance(IA/IB) use self config.xml with own path(DA/DB) and runtime flagfile(pidfile/status/uuid) generated in own path.
3. inditify two instance with serverUUID();

if this way is possible, it seems loadMetadata can be a such lite process, i mean: start IA -> start IB -> shutdown IA. cc @serxa @nickitat @den-crane  any commnets?

thanks

**Comment by tavplubix** [comment]
> i startup two CH instance on the same data folder

It's not supported, and eventually you will get your data corrupted. The second instance should have failed to start with an error like `Code: 76. DB::Exception: Cannot lock file /path/to/data/status. Another server instance in same directory is already running.`. Bypassing this check is a bad idea.
