### ISSUE TITLE
Timeout when trying to drop/alter any partition

### ISSUE THREAD

**Issue by g-t-675** [ClickHouse/ClickHouse#50496]
We use monthly partitioning for our analytics data in clickhouse but as of now we are not able to drop any partition out of the main table:

```
alter table dnsquery_raw drop partition '202205'

ALTER TABLE dnsquery_raw
    DROP PARTITION '202205'

Query id: 830db950-7a26-4740-b445-6affa9d25aab

0 rows in set. Elapsed: 120.448 sec. 

Received exception from server (version 21.3.20):
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Timeout while waiting for already running merges. 
```
We also tried DETACH and ALTER but those also didn't work.

**Comment by den-crane** [comment]
21.3.20 is out of support. Current version of Clickhouse cancel running merge in case of DROP PARTITION

**Comment by g-t-675** [comment]
Anything we can make on 21.3.20? We can't upgrade right away before clearing up some of these. Can we delete manually from the shadow folder after freezing the partition? Or would that corrupt the data?

**Comment by den-crane** [comment]
> Can we delete manually from the shadow folder after freezing the partition? Or would that corrupt the data?

You should not intervene manually.
Check merges 

```
 select  table, round(elapsed*(1/progress)-elapsed,2) estimate ,elapsed, progress, is_mutation,formatReadableSize(total_size_bytes_compressed) size,
 formatReadableSize(memory_usage) mem 
  from system.merges order by progress desc 
```
