### ISSUE TITLE
INSERT SELECT falls with Memory limit exception

### ISSUE THREAD

**Issue by alexm93** [ClickHouse/ClickHouse#5051]
**How to reproduce**
* create initial table 
`CREATE TABLE test
(
    sign FixedString(27),
    batch FixedString(10),
    emission_type UInt8,
    version UInt32,
    ch_sign Int8
)
ENGINE = MergeTree()
PARTITION BY emission_type
ORDER BY (sign, version)
SETTINGS index_granularity = 8192`

* fill table with about 2 billions rows
* try to create another table
`CREATE TABLE test2
ENGINE = MergeTree()
PARTITION BY emission_type
ORDER BY sign
SETTINGS index_granularity = 8192 AS
SELECT
    sign AS sign,
    argMax(emission_type, version) AS emission_type,
    argMax(batch, version) AS batch
FROM test
GROUP BY sign
HAVING sum(ch_sign) > 0`

**Expected behavior**
Table test2 should be created, but query falls with Memory limit exception or hangs on 98%.

**Error message and/or stacktrace**
![image](https://user-images.githubusercontent.com/33417101/56369296-c4567300-6201-11e9-8947-a53fc8ae5a4a.png)

**Additional context**
* Clickhouse 19.1.9
* Settings
<max_memory_usage>20000000000</max_memory_usage>         <max_bytes_before_external_group_by>10000000000</max_bytes_before_external_group_by>

**Comment by filimonov** [comment]
Does the select itself (i.e. without insert) finishes successfully?

**Comment by alexm93** [comment]
> Does the select itself (i.e. without insert) finishes successfully?

Yes, this query falls with Memory limit exception.
`SELECT
    sign AS sign,
    argMax(emission_type, version) AS emission_type,
    argMax(batch, version) AS batch
FROM test
GROUP BY sign
HAVING sum(ch_sign) > 0
LIMIT 1`

**Comment by den-crane** [comment]
@alexm93 Is it still valid? Do you  have reproducible example? Sample dataset ?
