### ISSUE TITLE
Incorrect SELECT statement using toYear() in head version

### ISSUE THREAD

**Issue by JZuming** [ClickHouse/ClickHouse#50520]
**Describe what's wrong**

The SELECT statemnt must return empty but it returns one row.

**Does it reproduce on recent release?**

It cannot be reproduced in the latest version, but it can be reproduced in head version (23.5.1.2568). So the bug might be involved by recent commits.

**How to reproduce**

Version: 23.5.1 (commit eb5985e5fc0e83c94aa1af134f2718e9fe87979c)

Easy reproduce in ClickHouse fiddle: https://fiddle.clickhouse.com/299a6ee1-0155-4f7e-9383-ee721a47bdee

_Set up database_

```sql
create table t0 (vkey UInt32, c4 DateTime) engine = Log;
```

_SELECT statement_

```sql
select toYear(ref_2.c4)
from 
  (select 1 as c_5_c1798_0) as subq_0
    full outer join t0 as ref_2
    on (subq_0.c_5_c1798_0 = ref_2.vkey)
where toYear(ref_2.c4) = 1 and toYear(ref_2.c4) = 1970;
```
Because `toYear(ref_2.c4) = 1` and `toYear(ref_2.c4) = 1970` in the WHERE clause cannot be satisfied simultaneously, the statement must return nothing. 

**Expected behavior**

The SELECT statement outputs empty.

**Actual behavior**

The SELECT statement outputs one row:
```
+------------+
| toYear(c4) |
+------------+
|       1970 |
+------------+
```

**Additional context**

In latest version of fiddle (https://fiddle.clickhouse.com/cf81bed9-0512-4dba-abdc-0d56ab57aee1), the SELECT statement outputs empty.

**Comment by JZuming** [comment]
This issue might be related to #50488. I report this one as its bug-triggering test case is much simpler.

**Comment by evillique** [comment]
The bug does not seem to reproduce on the latest version
