### ISSUE TITLE
Unmap some memory in fatal signal handler to reduce size of core dumps

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#50523]
We currently have core dumps disabled in cloud because they're big. But core dumps are useful! What can we do? Some ideas:
 * Enable them anyway, with some aggressive throttling (e.g. one per day) and eviction (e.g. store at most one core dump at a time).
 * Dump a core only if memory usage is small enough, e.g. < 30 GB.
 * Unmap some memory ranges in signal handler. E.g. if most of the memory usage is some cache which is rarely useful in core dump, we can unmap that cache, and it won't be included in the core dump. I've seen this done in another project, it was pretty simple and worked well.
   - This can also be conditional on memory usage being high enough.
   - If it's hard to track down most of the memory usage (e.g. it's not in one or two big caches but spread throughout lots of different small objects), we can just unmap everything except stacks of all threads.
 * Use breakpad and its minidumps, as suggested by Sergei Trifonov. From a cursory reading, minidumps sound like the previous item (unmapping everything but stacks) but worse. But I'm not sure.

**Comment by alexey-milovidov** [comment]
You can pass a flag MADV_DONTDUMP for mmaps (and for jemalloc's mmaps), and it will suffice for compact but usable dumps.

**Comment by canhld94** [comment]
> We currently have core dumps disabled in cloud because they're big. But core dumps are useful! What can we do? Some ideas:
> 
> * Enable them anyway, with some aggressive throttling (e.g. one per day) and eviction (e.g. store at most one core dump at a time).
> * Dump a core only if memory usage is small enough, e.g. < 30 GB.
> * Unmap some memory ranges in signal handler. E.g. if most of the memory usage is some cache which is rarely useful in core dump, we can unmap that cache, and it won't be included in the core dump. I've seen this done in another project, it was pretty simple and worked well.
>   
>   * This can also be conditional on memory usage being high enough.
>   * If it's hard to track down most of the memory usage (e.g. it's not in one or two big caches but spread throughout lots of different small objects), we can just unmap everything except stacks of all threads.
> * Use breakpad and its minidumps, as suggested by Sergei Trifonov. From a cursory reading, minidumps sound like the previous item (unmapping everything but stacks) but worse. But I'm not sure.


Hi @al13n321 what's the status for this issue? We suffered from big core dump files as well and plan to implement some alternative crash reporting. As of my experiences and reading:

- We're using option 1, but tbh it's suck.
- Breakpad is straightforward and easy to implement, but the minidumps sometimes contains too little information and become less useful.
- Mysql is using `MADV_DONTDUMP` to prevent dumping buffer pools; so we can probably do the same thing in CH. Some concerns are:
   - We can pass `MADV_DONTDUMP` to mmap in `Allocator` w/o doubts, but for jemalloc how do we know that it going to use mmap? Probably we don't want to enable `MADV_DONTDUMP` for every mem allocation.
   - What if system doesn't support `MADV_DONTDUMP`?
   - How we can enable `MADV_DONTDUMP`? At compile time or at runtime with a server setting? I'm worried about performance if we do it at runtime (Mysql does it at runtime, but it is enabled only for buffer pools allocator, so the performance impact shouldn't be much).
  
@al13n321 if you haven't started yet then maybe I can implement this task :). cc @alexey-milovidov

**Comment by canhld94** [comment]
And seem `mmap` in `Allocator` will be removed soon :) #52792

**Comment by canhld94** [comment]
> Probably we don't want to enable `MADV_DONTDUMP` for every mem allocation.

Naive idea: `MADV_DONTDUMP` any mem allocator > 8/16/32/64 MB

**Comment by al13n321** [comment]
> Naive idea: MADV_DONTDUMP any mem allocator > 8/16/32/64 MB

Last time I looked at `system.jemalloc_bins`, most memory was in very small allocations (e.g. 16 bytes), so this wouldn't help. Feel free to check the stats on your workload, maybe it's different.

I guess we can't easily do anything better than unmapping the whole heap / asking jemalloc to use MADV_DONTDUMP / using breakpad. Doing better would require (a) better understanding where the memory is going, and (b) refactoring to make the most memory-heavy components (e.g. caches) use arenas or something like that.

> What if system doesn't support MADV_DONTDUMP?

Linux has supported it for 14 years, it's fine. And if it's not supported, the memory simply won't be excluded from core dumps, that's fine too.

> How we can enable MADV_DONTDUMP? At compile time or at runtime with a server setting?

A server setting seems like the easiest option.

> I'm worried about performance if we do it at runtime (Mysql does it at runtime, but it is enabled only for buffer pools allocator, so the performance impact shouldn't be much).

It's just an madvise call after each mmap call, it's fine.

> We can pass MADV_DONTDUMP to mmap in Allocator w/o doubts, but for jemalloc how do we know that it going to use mmap? Probably we don't want to enable MADV_DONTDUMP for every mem allocation.

Per above, I don't have better ideas than to enable it for every mem allocation. So we just need a way to make jemalloc call madvise after each mmap. Jemalloc surely uses mmap, it's the only reasonable way to get memory from the OS on Linux.

> @al13n321 if you haven't started yet then maybe I can implement this task :)

Sure, feel free.

Thoughts on how to go about it (feel free to ignore if you want):
* The first thing to try would be to figure out a way to use MADV_DONTDUMP in jemalloc. There's https://github.com/facebook/folly/blob/main/folly/experimental/JemallocNodumpAllocator.cpp . Looks like it creates a new jemalloc arena and uses extent_hooks to make this arena use a custom mmap-like function, which does mmap+madvise. But I worry that using one arena would be slow because normally jemalloc uses per-core arenas for speed. So it seems better to use extent_hooks (documented in https://jemalloc.net/jemalloc.3.html) to reconfigure all existing arenas instead. That may be racy (other threads may be allocating memory in these arenas), but that's likely fine.
* If jemalloc integration turns out infeasible or insufficient for some reason, we could perform the madvise(MADV_DONTDUMP) calls from elsewhere, after reading `/proc/self/maps` to get the memory ranges. Maybe this would be in a signal handler just before crashing (but reading a file is probably not signal-safe), or maybe it would just be done periodically from some background thread.

**Comment by canhld94** [comment]
@al13n321 So far, I've implemented two approaches:

1. Using breakpad: work fine, and with a little hack we can make breakpad generates coredump file on linux along with minidump file. --> our fork likely will go with this approach first
2. Hack into jemalloc: there's one background thread that scan all arenas, decorate the arena's `extent_hooks.alloc` with a `madvise(MADV_DONTDUMP)` call. We keep track which arenas has been decorated to make sure we only do 1 for each arena.

(2) can work fine too, but I have some concerns:
- Using background task to scan all arenas seems like an overkill, I don't know if we can know the number of (default) arenas in advance and only decorate them all at once.
- So, we just don't dump any pieces of memory allocated by jemalloc --> we only dump stack, no different from breakpad
- Don't know the performance impact yet. There's one [attempt](https://github.com/jemalloc/jemalloc/pull/1023) to directly add MADV_DONTDUMP to jemalloc to not dump grow-retained regions, but it's abandoned because of performance reason.

I think (2) will be better if we use custom arenas. E.g. rocksdb has [jemalloc_no_dump_allocator](https://github.com/facebook/rocksdb/blob/main/memory/jemalloc_nodump_allocator.cc) to allocate memory that they know it's definitely not useful for debugging. The allocator has custom arenas, and can support multi-arenas too. In ClickHouse, we can create no dump allocator for: PODArray, HashMap... and other allocations (e.g. local variables) using default arena can still be dumped.

Anw, I will submit PR for (1) and (2) soon.

**Comment by canhld94** [comment]
> If jemalloc integration turns out infeasible or insufficient for some reason, we could perform the madvise(MADV_DONTDUMP) calls from elsewhere, after reading /proc/self/maps to get the memory ranges. Maybe this would be in a signal handler just before crashing (but reading a file is probably not signal-safe), or maybe it would just be done periodically from some background thread.

For this one, I didn't try it yet but one question is which memory range we want to unmap? It's too dangerous to unmap everything, even in the signal handler.

**Comment by jorisgio** [comment]
> I think (2) will be better if we use custom arenas. E.g. rocksdb has [jemalloc_no_dump_allocator](https://github.com/facebook/rocksdb/blob/main/memory/jemalloc_nodump_allocator.cc) to allocate memory that they know it's definitely not useful for debugging. The allocator has custom arenas, and can support multi-arenas too. In ClickHouse, we can create no dump allocator for: PODArray, HashMap... and other allocations (e.g. local variables) using default arena can still be dumped

agree with this. One option is to plug it to another level though, like caches and buffers are allocated to special arena set. Hashmap i think it is too coarse, join states,  aggregation states, and join tables, markcaches, caches, or dictionaries makes sense not to dump.  

(i think in our case the bigger problem is dictionaries/join tables, they are sometimes 500GB and dumping them is most of the time useless and painfully slow). 

But there are a lot of hashtables that make sense to dump still.

**Comment by al13n321** [comment]
I agree that it should ideally be at a subsystem level, not at container data structures level.

> E.g. rocksdb has [jemalloc_no_dump_allocator](https://github.com/facebook/rocksdb/blob/main/memory/jemalloc_nodump_allocator.cc) to allocate memory that they know it's definitely not useful for debugging.

AFAIU, rocksdb has a much cleaner breakdown of memory usage: usually almost all of the memory is used by block cache, which uses arena allocators, which can be easily unmapped / madvised / use custom allocator. That's actually what the OP referred to with "I've seen this done in another project, it was pretty simple and worked well" - in signal handler we unmapped memory ranges corresponding to rocksdb block cache.

In CH there are maybe 15-20 different things that can use a lot of memory in practice:
 * Buffer tables,
 * Join tables,
 * Set tables,
 * Memory tables,
 * temporary tables,
 * query cache,
 * uncompressed cache,
 * mark cache,
 * dictionaries,
 * running queries (aggregation state, output waiting to be ORDER BY-ed),
 * primary key of loaded data parts.

This list is incomplete (I checked one real server, and memory usage was much higher than the sum of all of these).
Our understanding and observability of what uses the bulk of memory has a lot of room for improvement.

Maybe even without full understanding we can incrementally switch all these things one by one to a custom jemalloc arena. And maybe add consistently named metrics along the way, so that a memory usage breakdown can be obtained with something like `select * from system.metrics where metric like '%MemoryBytes'`.

**Comment by alexey-milovidov** [comment]
Low priority.
