### ISSUE TITLE
`test_hedged_requests/test.py::test_async_connect` flaky test

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#50544]
Link https://s3.amazonaws.com/clickhouse-test-reports/50521/57070227a8468f68f9caede43b4d93ad286a2d00/integration_tests__tsan__[1_6].html

**Comment by Avogar** [comment]
That commit didn't contain my fix yet, I guess: https://github.com/ClickHouse/ClickHouse/pull/50480
Let's close. If it will fail again, let me know

**Comment by ilejn** [comment]
@Avogar 
https://s3.amazonaws.com/clickhouse-test-reports/48941/5efecdb58af9b3d18c504c16f0bfdee71fb94cca/integration_tests__tsan__[5_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel1_0.log
