### ISSUE TITLE
`test_profile_events_s3/test.py::test_profile_events` flaky test

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#50543]
Link: https://s3.amazonaws.com/clickhouse-test-reports/50521/57070227a8468f68f9caede43b4d93ad286a2d00/integration_tests__tsan__[1_6].html

**Comment by KochetovNicolai** [comment]
https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3Byb2ZpbGVfZXZlbnRzX3MzJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBkZXNjLCBjaGVja19uYW1lLCB0ZXN0X25hbWUK

https://s3.amazonaws.com/clickhouse-test-reports/0/f118cba17e014620b9d13246f95cbb936dbe07f4/integration_tests__tsan__[1_6].html

https://s3.amazonaws.com/clickhouse-test-reports/0/4fd674a3b23f9bed6b3e1cf1ca84c704c003597e/integration_tests__asan__[1_6].html

https://s3.amazonaws.com/clickhouse-test-reports/0/f0bfd44e13cd09b12f0add52097fa0041ba31594/integration_tests__tsan__[1_6].html

**Comment by CheSema** [comment]
Ofcourse it would flacks %(
 
assert stat2[metric] == metrics2[metric] - metrics1[metric]

Event is omit in Map when it never happened 
KeyError: 'WriteBufferFromS3WaitInflightLimitMicroseconds'

**Comment by CheSema** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/51412
