### ISSUE TITLE
clickhouse-benchmark should be able to count errors / exceptions

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#5056]
clickhouse-benchmark should be able to count errors/exceptions instead of printing them to stdout

Ideally - number of erroneous requests overall, plus stats per error type. 

Like numbers of connection problems, the number of particular exceptions etc.

**Comment by alexey-milovidov** [comment]
Ok.

We can simply implement a mode to continue after printing an error.

PS. To perform load testing with query_log on testing environment, I just filter some queries and ensure that all other queries execute successfully:

```
grep -Fv "\\'banners\\'" queries.tsv | grep -Fv "\\'phrases\\'" | grep -v _data | grep -v visits_total | grep -v user_param_layer | grep -v calls_log | grep -vF ' remote(' | clickhouse --benchmark -c16 --randomize=1 --distributed_product_mode=local --user=web --min_execution_speed=0 --max_execution_time=0
```

**Comment by filimonov** [comment]
Context: I was using `clickhouse-benchmark` as a stress test tool. You probably saw that: https://www.altinity.com/blog/clickhouse-in-the-storm-part-1

As with each kind of DoS - after reaching some critical load (in terms of concurrency and qps)
proper queries are not able to be served properly anymore (like too many connections or similar problems). The number/percentage of such errors is quite an important metric.

**Comment by alexey-milovidov** [comment]
Ok. BTW, clickhouse-benchmark creates fixed number of connections at startup and use them all the time.

**Comment by alexey-milovidov** [comment]
@akuzm has added this option a year ago: #11616.

Unfortunately:
- it was added without a note in changelog;
- it is named `--continue_on_errors` instead of `--ignore-error`;
(this is quite chaotic change, my apologies)

Example:

`clickhouse-benchmark --query "SELECT throwIf(1)" --continue_on_errors`
