### ISSUE TITLE
NULL::LowCardinality(Nullable(T)) NOT IN bug

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#50570]
**Describe what's wrong**

ClickHouse will return NULL value for operator NOT IN with 0-set

**Does it reproduce on recent release?**

Yes, 23.3

**How to reproduce**
```
SELECT lc
FROM
(
    SELECT CAST(NULL, 'LowCardinality(Nullable(String))') AS lc
)
WHERE lc NOT IN (
    SELECT *
    FROM
    (
        SELECT materialize(CAST('', 'LowCardinality(Nullable(String))') AS lc)
    )
    WHERE 0
)

┌─lc───┐
│ ᴺᵁᴸᴸ │
└──────┘


SELECT lc
FROM
(
    SELECT materialize(CAST(NULL, 'Nullable(String)')) AS lc
)
WHERE lc NOT IN (
    SELECT *
    FROM
    (
        SELECT materialize(CAST('', 'LowCardinality(Nullable(String))') AS lc)
    )
    WHERE 0
)


Ok.

0 rows in set. Elapsed: 0.009 sec.
```

**Expected behavior**

Query will return 0 rows always

**Additional context**

Version with bug introducted is 21.6

https://fiddle.clickhouse.com/c8e03c2d-6879-4ae5-b565-a485d1c56f5d

**Comment by aadant** [comment]
@alexey-milovidov it is a wrong result. We found it while migrating a system that complies with the SQL standard :-)
+ it is a regression.

**Comment by Enmk** [comment]
### Notes to self
expected result is: empty

Looks like it was introduced somewhere between `21.6.4` and `21.6.5`.
Also present in `21.3`, was backported (or re-introduced) somewhere between `21.3.12` and `21.3.13`

**Comment by zvonand** [comment]
**Notes 2:**

it is not only about 0-set: https://fiddle.clickhouse.com/5236d6f9-47a2-4bbf-9b67-4ef03a37a58e

**Comment by zvonand** [comment]
@UnamedRus Could you please change issue name to smth like "NULL::LowCardinality(Nullable) NOT IN bug"? 0-set mention may be a bit misleading here, and String too. E.g. [this example](https://fiddle.clickhouse.com/8c45c0d7-d1dd-4cce-9569-c673e4f10f11) will also go wrong.

**Comment by zvonand** [comment]
Yes, it is, but it fails for non-empty set also.
Added a wrong likg to my prev comment
See https://fiddle.clickhouse.com/c40cccc9-41c3-4642-a0ad-cb962e6859ed
