### ISSUE TITLE
LOG engine count() after TRUNCATE is not empty

### ISSUE THREAD

**Issue by techkuz** [ClickHouse/ClickHouse#50578]
> A clear and concise description of what works not as it is supposed to.

When I do TRUNCATE on LOG ENGINE table, it deletes records, but count() is not empty

> A link to reproducer

https://fiddle.clickhouse.com/9ee5ac13-56b9-4b78-9f61-66f0e8e49de6

**Does it reproduce on recent release?**
Yes

**How to reproduce**

* Which ClickHouse server version to use
23.4.2.11
* Which interface to use, if matters
fiddle
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE default.test_log
(
    `crypto_name` String,
    `trade_date` Date
)
ENGINE = Log
SETTINGS index_granularity = 8192;
```

* Sample data for all these tables
`INSERT INTO default.test_log (crypto_name, trade_date) VALUES ('abc', '2021-01-01'), ('def', '2022-02-02');`
* Queries to run that lead to unexpected result
```
TRUNCATE TABLE default.test_log;
SELECT count(*) FROM  default.test_log;
```
2
**Expected behavior**
count is 0
> A clear and concise description of what you expected to happen.

as `select` from the table after `truncate` returns nothing, `count` should return 0

**Comment by ucasfl** [comment]
Reproduced.
