### ISSUE TITLE
Custom key parallel replicas: Implicit transformation of tables to cluster calls

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#50596]
Right now custom key parallel replicas don't have a great user experience.

You go from writing this:
```
SELECT count() FROM replicated_numbers
```

To need to write:
```
SELECT count() FROM cluster(test_cluster_one_shard_three_replicas_localhost, currentDatabase(), replicated_numbers)
```
Plus some settings, like:
* max_parallel_replicas: 3
* parallel_replicas_custom_key_filter_type: `default`
* parallel_replicas_custom_key: `sipHash64(number)`

It would be great if you could still write the first query but get parallel replicas implicitly, that is, without having to call `cluster()` in the query itself.

Pure parallel replicas already have a similar setting `cluster_for_parallel_replicas`, so I'd reuse that setting and automagically convert any replicated merge trees into whatever distributed storage is necessary to execute the plan with parallel replicas.

I don't think a setting to enable this would be necessary and instead the implicit conversion should always be on (if parallel_replicas_custom_key is on), but it could also be added if necessary.

**Comment by antonio2368** [comment]
After 1 year I implemented what you wanted https://github.com/ClickHouse/ClickHouse/pull/65453
