### ISSUE TITLE
Projections ignore lightweight deletes

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#50613]
```
create table e (k Int64) engine MergeTree order by k
insert into e values (1) (2)
delete from e where k = 2
alter table e add projection p (select sum(k))
alter table e materialize projection p

:) select * from e

SELECT *
FROM e

Query id: 94daf75d-c0ed-40d0-aa4d-71b1c5313e41

┌─k─┐
│ 1 │
└───┘

1 row in set. Elapsed: 0.001 sec. 

:) select sum(k) from e settings allow_experimental_projection_optimization=0

SELECT sum(k)
FROM e
SETTINGS allow_experimental_projection_optimization = 0

Query id: 16a9172f-9181-4ac9-a18b-0489a6580580

┌─sum(k)─┐
│      1 │
└────────┘

1 row in set. Elapsed: 0.002 sec. 

:) select sum(k) from e settings force_optimize_projection=1

SELECT sum(k)
FROM e
SETTINGS force_optimize_projection = 1

Query id: c6e26779-53c2-43be-a8b3-e3154bcd5adb

┌─sum(k)─┐
│      3 │
└────────┘

1 row in set. Elapsed: 0.005 sec. 
```

The last query returns incorrect result - as if the row `k = 2` wasn't deleted.

It was probably not intended for projections and lightweight deletes to be able to coexist at all. If you swap the `delete from` and the `add projection` queries, the `delete from` is rejected because a projection exists. I guess we should add a similar check the other way - refuse to add projection if any parts have lightweight deletes?

**Comment by alexey-milovidov** [comment]
This issue cannot be fixed.

**Comment by den-crane** [comment]
Projection may not exists for a part and then it will be built on the fly, so if _row_exists exists in the part, then a projection can be calculated for this part, on the fly, taking into account the rows _row_ex
