### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by liangli-hue** [ClickHouse/ClickHouse#50617]
ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer, Stack trace (when copying this message, always include the lines below):

Poco::IOException::IOException(int) @ 0xbb949fb in /usr/bin/clickhouse
Poco::Net::ConnectionResetException::ConnectionResetException(int) @ 0x9c54539 in /usr/bin/clickhouse
? @ 0x4d82360 in /usr/bin/clickhouse
Poco::Net::SocketImpl::receiveBytes(void*, int, int) @ 0x9c63058 in /usr/bin/clickhouse
Poco::Net::HTTPSession::receive(char*, int) @ 0x9c47aa4 in /usr/bin/clickhouse
Poco::Net::HTTPSession::get() @ 0x9c47b0b in /usr/bin/clickhouse
Poco::Net::HTTPHeaderStreamBuf::readFromDevice(char*, long) @ 0x9c41e52 in /usr/bin/clickhouse
Poco::BasicBufferedStreamBuf<char, std::__1::char_traits, Poco::Net::HTTPBufferAllocator>::underflow() @ 0x9c41d08 in /usr/bin/clickhouse
std::__1::basic_streambuf<char, std::__1::char_traits >::uflow() @ 0xc5ebf3a in /usr/bin/clickhouse
std::__1::basic_istream<char, std::__1::char_traits >::get() @ 0xc5f2766 in /usr/bin/clickhouse
Poco::Net::HTTPRequest::read(std::__1::basic_istream<char, std::__1::char_traits >&) @ 0x9c445d3 in /usr/bin/clickhouse
Poco::Net::HTTPServerRequestImpl::HTTPServerRequestImpl(Poco::Net::HTTPServerResponseImpl&, Poco::Net::HTTPServerSession&, Poco::Net::HTTPServerParams*) @ 0x9c4700e in /usr/bin/clickhouse
Poco::Net::HTTPServerConnection::run() @ 0x9c6b510 in /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start() @ 0x9c68017 in /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run() @ 0x9c6840d in /usr/bin/clickhouse
Poco::PooledThread::run() @ 0xbbfaf4f in /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*) @ 0xbbf81b8 in /usr/bin/clickhouse
? @ 0xbbf98e9 in /usr/bin/clickhouse
start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
clone @ 0xfe88d in /usr/lib64/libc-2.17.so

**Comment by filimonov** [comment]
The 'peer' (i.e. some client who connected to clickhouse via HTTP, or some middleware) did reset (=close) the connection.

It's quite common when some healthcheck do connect to the clickhouse and then immediately close the connection.

Nothing you can do on the server side.

**Comment by liangli-hue** [comment]
May I ask how to solve this problem

**Comment by tavplubix** [comment]
> May I ask how to solve this problem

This "problem" is on client's side, so we cannot help

**Comment by liangli-hue** [comment]
> > May I ask how to solve this problem
> 
> This "problem" is on client's side, so we cannot help

Hi, when I used the clickhouse jdbc driver 0.3.2, the issue with code=104 seemed to have been resolved. I hope my answer can help more people. thanks
