### ISSUE TITLE
Materialized View not getting updated when pushing to Distributed Table

### ISSUE THREAD

**Issue by Vasu7052** [ClickHouse/ClickHouse#50618]
Hi Team,

I have two databases in our clickhouse cluster i.e `my_db_shard` & `my_db`. I have a data table present in `my_db_shard` with ReplicatedMergeTree(...) and a distributed table in `my_db` with Distributed(...)

I have created a materialized view in my shard database (`my_db_shard`) with query:
```
CREATE MATERIALIZED VIEW my_db_shard.agg_table_mv
ENGINE = AggregatingMergeTree
PARTITION BY toStartOfWeek(...)
ORDER BY (...)
SETTINGS index_granularity = 8192
AS
SELECT ... FROM my_db_shard.src_data_table
WHERE ...
GROUP BY ...
```

Here's the issue: When I insert data directly into the shard table (`my_db_shard.src_data_table`), the materialized view (`agg_table_mv`) updates correctly. However, when I attempt to insert data into the distributed table (`my_db.src_data_table`), the materialized view is NOT getting updated. The data in `my_db.src_data_table` & `my_db_shard.src_data_table` is being updated correctly after inserting to distributed table, and there are no error logs present in the log file.

Our ClickHouse version is 21.12.3.32.

**Comment by filimonov** [comment]
> Our ClickHouse version is 21.12.3.32.

version is not supported. 

> materialized view is NOT getting updated. 

It should be updated on the node which will get the data from the distributed table. Ensure the distibuted table properly passes the data to shards, and that you check the proper shard for the data.

**Comment by Vasu7052** [comment]
@filimonov thanks for quick response. 

i have checked that the distributed table is properly passing the data to shards. but the materialized views created on top of those shards are not being updated. i have checked all nodes just to be sure.

However when i try to insert directly to the shard, its corresponding materialized view gets updated correctly.

**Comment by Vasu7052** [comment]
i have one more quick question if you dont mind.

One of the columns in my materialized views is like this:
```
...
argMaxIfState(last_agg_value, timestamp, someCondition) as last_agg_value,
...
```

Now when we try to apply TTL condition on this particular column like this:
```
ALTER TABLE my_db_shard.`.inner_id.sometable` MODIFY TTL timestamp + INTERVAL 150 MONTH WHERE (last_agg_value != 'true');
```

It's throwing us error:
`
DB::Exception: Cannot convert String to AggregateFunction(argMaxIf, String, DateTime, UInt8): while executing 'FUNCTION notEquals(last_agg_value : 0, 'true' :: 1) -> notEquals(last_agg_value, 'true') UInt8 : 2': While executing TTL. (TYPE_MISMATCH)
`

are we doing something wrong?

**Comment by den-crane** [comment]
>WHERE (argMaxIfMerge(last_agg_value) != 'true');

try `finalizeAggregation(last_agg_value) != 'true'` BTW, it will never work correctly, because merges are eventual and `TTL WHERE` is unusable in general.

**Comment by den-crane** [comment]
What is the engine of src_data_table ? Is it replicated?

**Comment by Vasu7052** [comment]
> What is the engine of src_data_table ? Is it replicated?

yes, the engine is `ReplicatedMergeTree`. shard table resides in `my_db_shard` db and its replica resides in next node's `my_db_replica` db. I have also checked that in both shard and replica, data is being updated.

**Comment by Vasu7052** [comment]
i have update our Clickhouse to 22.8.13.20, still the issue exists
