### ISSUE TITLE
ClickHouse read timed out

### ISSUE THREAD

**Issue by rnrl1215** [ClickHouse/ClickHouse#50645]
I did a clickhouse load test about select count query in application
- jemeter-> spring boot -> jdbc driver -> clickhouse

Click House Specifications
- clickhouse version is 23.2.4.12
- jdbc driver version is 0.4.2

I found that cpu is used a lot and occur read time out
 i used jmeter for test
- Number of Threads: 1000
- Ramp-up period: 1
- Loop count: 1

first response query speed is 84ms, but The load time continues to increase.

response time of request1: 84ms
response time of request2: 90ms
...
....
...
response time of request100: 34533ms
response time of request101: 45555ms

how fix slow response speed ?

Table
-----------------------------------------------------
CREATE TABLE test.user_log
(
created_at DateTime,
user_id UInt64,
age UInt64,
sex String,
event_name String,
action_name String,
keys Array(String),
values Array(String)
)
ENGINE = MergeTree
PARTITION BY (toYYYYMM(created_at), event_name)
ORDER BY (event_name, action_name, created_at);
----------------------------------------------------------

Query
----------------------------------------------------------
SELECT COUNT(user_id)
FROM user_log
WHERE created_at  >= '2022-01-11 00:00:00' 
AND  created_at <= '2023-01-11 23:59:59'
AND event_name = 'cash'
AND action_name = 'deposit'
AND values[1] = '233' -- this is number of machine
----------------------------------------------------------

RowNumber
----------------------------------------------------------
total rows  is 16,000,000
----------------------------------------------------------

**Comment by cangyin** [comment]
> Number of Threads: 1000

ClickHouse is designed as a OLAP system, not OLTP system. It will not handle high concurrent queries. Typical concurrency should be about 100.
