### ISSUE TITLE
Clickhouse performance down when table ttl is triggered？

### ISSUE THREAD

**Issue by yehaotong** [ClickHouse/ClickHouse#50659]
I am using CH as log storage and my CH version is 22.3.3.44. Our system produces about 2 billion logs per day. And I want to use ttl to Control the movement of data over a period of time to s3 for cold and hot cold storage.But I'm not sure if adding this ttl will have a significant impact on the performance of the ck itself.Before this, I had used TTL to delete expired data,everything works well before the table ttl is triggered. When the ttl is triggered, the lag between kafka and CH consumer increases fast which causes the log record delay.Will using ttl to expire data and move it to s3 also have this consequence？
Below is the information:
`
CREATE TABLE `logs`.`logs`
(
  _time_second_ DateTime,
  _source_ String,
  _cluster_ String,
  _log_agent_ String,
  _namespace_ String,
  _node_name_ String,
  _node_ip_ String,
  _container_name_ String,
  _pod_name_ String,
  http_traceid String,
  http_client_ip String,
  http_elapse Nullable(Float32),
  http_status Nullable(Int16),
  http_method String,
  http_origin String,
  http_domain String,
  http_path String,
  http_from String,
  http_user_agent String,
  message String
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(_time_second_)
ORDER BY _time_second_
TTL toDateTime(_time_second_) + INTERVAL 7 DAY TO DISK 's3'
SETTINGS index_granularity = 8192, storage_policy = 'hot_cold';

CREATE TABLE `logs`.`logs_stream`
(
  _source_ String,
  _pod_name_ String,
  _namespace_ String,
  _node_name_ String,
  _container_name_ String,
  _cluster_ String,
  _log_agent_ String,
  _node_ip_ String,
  _time_ String,
  http_traceid String,
  http_client_ip String,
  http_elapse Nullable(Float32),
  http_status Nullable(Int16),
  http_method String,
  http_origin String,
  http_domain String,
  http_path String,
  http_from String,
  http_user_agent String,
  _log_ String
) ENGINE = Kafka SETTINGS kafka_broker_list ='locahost:9092', kafka_topic_list = 'eks-logs', kafka_group_name = 'clickhouse',kafka_skip_broken_messages=10000,kafka_format = 'JSONEachRow', kafka_num_consumers = 6, kafka_thread_per_consumer=10;

CREATE MATERIALIZED VIEW `logs`.`logs_view` TO `logs`.`logs` AS
SELECT
  parseDateTimeBestEffort(_time_) AS _time_second_,
  _source_,
  _cluster_,
  _log_agent_,
  _namespace_,
  _node_name_,
  _node_ip_,
  _container_name_,
  _pod_name_,
  http_traceid,
  http_client_ip,
  http_elapse,
  http_status,
  http_method,
  http_origin,
  http_domain,
  http_path,
  http_from,
  http_user_agent,
  _log_ AS message
FROM `logs`.`logs_stream`
WHERE 1=1;
`

**Comment by yehaotong** [comment]
> > When the ttl is triggered, the lag between kafka and CH consumer increases fast which causes the log record delay.
> 
> It's manageable. You can configure TTL to remove whole parts instead of rows.
> 
> > Will using ttl to expire data and move it to s3 also have
> 
> That is unlikely. TTL move has another nature.

The meaning is that I can boldly enable this ttl in the production environment for data expiration and move it to s3 without worrying about the impact on ck due to the large amount of data that needs to be moved？

**Comment by den-crane** [comment]
>The meaning is that I can boldly enable this ttl in the production environment for data expiration and move it to s3

It depends of the way how you are going to enable TTL for the existing data.

**Comment by yehaotong** [comment]
> > The meaning is that I can boldly enable this ttl in the production environment for data expiration and move it to s3
> 
> It depends of the way how you are going to enable TTL for the existing data.

The operation I performed on TTL mentioned above, and whether there will be any consequences of adding TTL delete data to s3 in the future, causing CK itself to be unresponsive. I refer to the previous answer: https://github.com/ClickHouse/ClickHouse/issues/36727

**Comment by den-crane** [comment]
I would apply it using "safe" way.

```
alter table logs modify ttl toDateTime(_time_second_)  +  INTERVAL 2 WEEK TO DISK 's3' settings materialize_ttl_after_modify=0;

alter  table logs move partition w to TO DISK 's3';
alter  table logs move partition x to TO DISK 's3';
alter  table logs move partition y to TO DISK 's3';
alter  table logs move partition z to TO DISK 's3';
```

**Comment by yehaotong** [comment]
> I would apply it using "safe" way.
> 
> ```
> alter table logs modify ttl toDateTime(_time_second_)  +  INTERVAL 2 WEEK TO DISK 's3' 
> settings materialize_ttl_after_modify=0;
> 
> alter  table logs move partition w to TO DISK 's3';
> alter  table logs move partition x to TO DISK 's3';
> alter  table logs move partition y to TO DISK 's3';
> alter  table logs move partition z to TO DISK 's3';
> ```

In this place, through ttl toDateTime(_time_second_)  +  INTERVAL 2 WEEK TO DISK 's3'，Didn't CK already move the partition of historical data to s3? Why do I have to manually do it below:
```
 alter  table logs move partition w to TO DISK 's3';
alter  table logs move partition x to TO DISK 's3';
alter  table logs move partition y to TO DISK 's3';
alter  table logs move partition z to TO DISK 's3';
```

**Comment by den-crane** [comment]
This setting `settings materialize_ttl_after_modify=0;` will prevent move the partition of historical data to s3

**Comment by den-crane** [comment]
materialize_ttl_after_modify=1 -- can cause drastic immediate impact which will cripple your system

**Comment by yehaotong** [comment]
> materialize_ttl_after_modify=1 -- can cause drastic immediate impact which can cripple your system

Thank you very much for your suggestion and explanation. It was very helpful to me!
