### ISSUE TITLE
test_tlsv1_3 is flaky (test_https_wrong_cert, test_https_non_ssl_auth)

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#50679]
https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICAtLUFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdPSycKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3Rsc3YxXzMlJwpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQo=

https://s3.amazonaws.com/clickhouse-test-reports/0/21e3b6df572cf71fab41940cad0be84b1833e49b/integration_tests__release__[3_4].html

https://s3.amazonaws.com/clickhouse-test-reports/0/9b49469e545ed6cfc95377e4f063678ac5fa92c8/integration_tests__release__[3_4].html

**Comment by al13n321** [comment]
There's also 'unknown ca' error in test_ssl_cert_authentication/test.py::test_https_non_ssl_auth: https://s3.amazonaws.com/clickhouse-test-reports/49367/dc23d5cb08a5540a167dca46488c7b30d0ca7a6c/integration_tests__release__[4_4]/integration_run_parallel4_0.log

Does it look like the same problem? Should we add retries there too?

**Comment by antaljanosbenjamin** [comment]
To be honest I am not sure. With the BrokenPipe error I had less worries, because that means (at least in my understanding) that the connection between the server and the client died in a not graceful way. However the `EOF occurred in violation of protocol` sounds more frightening. I have no idea what would be the best.

**Comment by antaljanosbenjamin** [comment]
@alexey-milovidov decided to ignore the `EOF occurred...` error also in #52796 .
