### ISSUE TITLE
Expose if an error from ClickHouse is retriable 

### ISSUE THREAD

**Issue by mzitnik** [ClickHouse/ClickHouse#50695]
**Use case**

When working with ClickHouse, it is hard to understand whether a query/insert is retriable. 
ClickHouse as a list of errors https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/ErrorCodes.cpp 

**Describe the solution you'd like**

Instead of populating this logic into clients or an applicative layer. I suggest adding another field.  
```
#define APPLY_FOR_ERROR_CODES(M) \
    M(0, OK, false) \
    M(1, UNSUPPORTED_METHOD, false) \
    M(2, UNSUPPORTED_PARAMETER, false) \
    M(252, TOO_MANY_PARTS, true) \
```  

Add the new field to the message. So the client can parse it and decide what to do.

**Comment by Algunenano** [comment]
From the point of view of ClickHouse, it's currently not possible to just say that an error code is always retriable as the error might happen in a situation where retrying will lead to duplicated data (in a nested materialized view for example).

There are some situations where we know that retrying is safe, like if nothing was written in the query and it's a server error. We can start there and then, if necessary, improve the cases where some data has been written by the query but retrying could be safe still (for example, via transactions rollback, deduplication, no non-deterministic functions in columns or materialized views, etc).

**Comment by Algunenano** [comment]
I found an unexpected inconvenience in how we count written rows on replicated tables.

We count them as we write them to storage, not when the part is promoted to active (after being accepted in keeper). This means that if an insert fails because keeper is down we have already counted `written_rows`, so it's not possible to say safely nothing was stored only with that metric.

**Comment by alexey-milovidov** [comment]
It will be simpler to use exponential backoff + monitoring for all exceptions.
