### ISSUE TITLE
Clickhouse Keeper server 

### ISSUE THREAD

**Issue by ashraf-4** [ClickHouse/ClickHouse#50694]
[keeper1.txt](https://github.com/ClickHouse/ClickHouse/files/11685474/keeper1.txt)
[keeper2.txt](https://github.com/ClickHouse/ClickHouse/files/11685475/keeper2.txt)
[keeper3.txt](https://github.com/ClickHouse/ClickHouse/files/11685476/keeper3.txt)

Hi 
actually I did the same as this document [Replication for fault tolerance | ClickHouse Docs] https://clickhouse.com/docs/en/architecture/replication
the result was :
1- All services came up (clickhouse server in node 1 and 2 , also clickhouse keeper in keeper 1,2 and 3 
2 - when I created data bases on cluster it’s replicated correctly but when create any table using Replicated MergTree Engin it’s not replicated 
3- what I noted the keeper1 server still in standalone mode and the others servers didn’t came as followers 
it showing 
 "This instance is not currently serving requestsroot"

i attached keeper servers configuration file as txt, please help me about this issue 
```[tasklist]
### Tasks
```

**Comment by ashraf-4** [comment]
i will attach additional files 
[config1.txt](https://github.com/ClickHouse/ClickHouse/files/11685658/config1.txt)
[config2.txt](https://github.com/ClickHouse/ClickHouse/files/11685660/config2.txt)
[remote-servers.txt](https://github.com/ClickHouse/ClickHouse/files/11685664/remote-servers.txt)

config1 for clickhouse server 1 
config 2 for clickhouse server 2 
remote server is config file for <remote_server> section

**Comment by DanRoscigno** [comment]
@ashraf-4 can you ping between keeper 1 and the other 2 keepers?  And can you verify the IP addresses are all correct in the files, or send the actual files?

**Comment by DanRoscigno** [comment]
I tested the configs in the docs at https://clickhouse.com/docs/en/architecture/replication with version 23.4.1 and everything works as expected:
```
❯ echo mntr | nc localhost 9181
zk_version	v23.2.4.12-stable-8fe866cb035e2779ec17af6805cb50225160d42c
zk_avg_latency	0
zk_max_latency	0
zk_min_latency	0
zk_packets_received	0
zk_packets_sent	0
zk_num_alive_connections	0
zk_outstanding_requests	0
zk_server_state	follower
zk_znode_count	6
zk_watch_count	0
zk_ephemerals_count	0
zk_approximate_data_size	1271
zk_key_arena_size	4096
zk_latest_snapshot_size	0
zk_open_file_descriptor_count	48
zk_max_file_descriptor_count	18446744073709551615
❯ echo mntr | nc localhost 9182
zk_version	v23.2.4.12-stable-8fe866cb035e2779ec17af6805cb50225160d42c
zk_avg_latency	0
zk_max_latency	2
zk_min_latency	0
zk_packets_received	10
zk_packets_sent	10
zk_num_alive_connections	1
zk_outstanding_requests	0
zk_server_state	leader
zk_znode_count	6
zk_watch_count	1
zk_ephemerals_count	0
zk_approximate_data_size	1271
zk_key_arena_size	4096
zk_latest_snapshot_size	0
zk_open_file_descriptor_count	54
zk_max_file_descriptor_count	18446744073709551615
zk_followers	2
zk_synced_followers	2
❯ echo mntr | nc localhost 9183
zk_version	v23.2.4.12-stable-8fe866cb035e2779ec17af6805cb50225160d42c
zk_avg_latency	1
zk_max_latency	3
zk_min_latency	0
zk_packets_received	10
zk_packets_sent	10
zk_num_alive_connections	1
zk_outstanding_requests	0
zk_server_state	follower
zk_znode_count	6
zk_watch_count	1
zk_ephemerals_count	0
zk_approximate_data_size	1271
zk_key_arena_size	4096
zk_latest_snapshot_size	0
zk_open_file_descriptor_count	53
zk_max_file_descriptor_count	18446744073709551615
❯ docker compose exec clickhouse-01 clickhouse-client
ClickHouse client version 23.4.1.1943 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.4.1 revision 54462.

cluster_1S_2R node 1 :) CREATE DATABASE db1 ON CLUSTER cluster_1S_2R

CREATE DATABASE db1 ON CLUSTER cluster_1S_2R

Query id: 8616f93f-be6e-468f-b11f-8ae00418f2e3

┌─host──────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ clickhouse-02 │ 9000 │      0 │       │                   1 │                0 │
│ clickhouse-01 │ 9000 │      0 │       │                   0 │                0 │
└───────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘

2 rows in set. Elapsed: 0.124 sec. 

cluster_1S_2R node 1 :) CREATE TABLE db1.table1 ON CLUSTER cluster_1S_2R
(
    `id` UInt64,
    `column1` String
)
ENGINE = ReplicatedMergeTree
ORDER BY id

CREATE TABLE db1.table1 ON CLUSTER cluster_1S_2R
(
    `id` UInt64,
    `column1` String
)
ENGINE = ReplicatedMergeTree
ORDER BY id

Query id: 93ee7144-bb05-4ecc-8b26-8a8871f3bf48

┌─host──────────┬─port─┬─status─┬─error─┬─num_hosts_remaining─┬─num_hosts_active─┐
│ clickhouse-01 │ 9000 │      0 │       │                   1 │                0 │
│ clickhouse-02 │ 9000 │      0 │       │                   0 │                0 │
└───────────────┴──────┴────────┴───────┴─────────────────────┴──────────────────┘

2 rows in set. Elapsed: 0.123 sec. 

cluster_1S_2R node 1 :) INSERT INTO db1.table1 (id, column1) VALUES (1, 'abc');

INSERT INTO db1.table1 (id, column1) FORMAT Values

Query id: 9de69f5f-25b6-4674-88b7-d116d2277621

Ok.

1 row in set. Elapsed: 0.021 sec. 

cluster_1S_2R node 1 :) Bye.
❯ docker compose exec clickhouse-02 clickhouse-client
ClickHouse client version 23.4.1.1943 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.4.1 revision 54462.

cluster_1S_2R node 2 :) SELECT *
FROM db1.table1

SELECT *
FROM db1.table1

Query id: 1a787942-ac5d-46d2-916f-4006bb515fe6

┌─id─┬─column1─┐
│  1 │ abc     │
└────┴─────────┘

1 row in set. Elapsed: 0.003 sec.
```
[configs.zip](https://github.com/ClickHouse/ClickHouse/files/11692994/configs.zip)

If you use docker, here is the compose file that I used:
[docker-compose.txt](https://github.com/ClickHouse/ClickHouse/files/11693016/docker-compose.txt)

**Comment by ashraf-4** [comment]
> @ashraf-4 can you ping between keeper 1 and the other 2 keepers? And can you verify the IP addresses are all correct in the files, or send the actual files?

i will attach actual files
Note: all servers are pinging each others also when i telenet using 2181 port it's connecting. 
[My_clickhouse.zip](https://github.com/ClickHouse/ClickHouse/files/11702962/My_clickhouse.zip)


keeper1 :
root@kepper1:/etc/clickhouse-keeper# echo mntr | nc localhost 2181                           zk_version      v23.4.2.11-stable-b6442320f9dc85d127bfaf84febe76e9294b2407
zk_avg_latency  0
zk_max_latency  1
zk_min_latency  0
zk_packets_received     2049
zk_packets_sent 2049
zk_num_alive_connections        2
zk_outstanding_requests 0
zk_server_state standalone
zk_znode_count  240
zk_watch_count  4
zk_ephemerals_count     1
zk_approximate_data_size        81908
zk_key_arena_size       28672
zk_latest_snapshot_size 0
zk_open_file_descriptor_count   41
zk_max_file_descriptor_count    18446744073709551615
zk_followers    0
zk_synced_followers     0

keeper2:
root@kepper2:/home/gama# echo mntr | nc localhost 2181
This instance is not currently serving requestsroot@kepper2:/home/gama#

keeper3:
root@kepper3:/home/gama# echo mntr | nc localhost 2181
This instance is not currently serving requestsroot@kepper3:/home/gama#

**Comment by ashraf-4** [comment]
i reinstall the config files into config.d path. 

also i reinstalled the clickhouse keeper  using this steps : 

-sudo apt-get install -y apt-transport-https ca-certificates dirmngr
-GNUPGHOME=$(mktemp -d)
-sudo GNUPGHOME="$GNUPGHOME" gpg --no-default-keyring --keyring /usr/share/keyrings/clickhouse-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8919F6BD2B48D754
-sudo rm -r "$GNUPGHOME"
-sudo chmod +r /usr/share/keyrings/clickhouse-keyring.gpg

-echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
-sudo apt-get update

but also same errors happens , i will attach logs from all keepers. 
[logs from keeper2.txt](https://github.com/ClickHouse/ClickHouse/files/11715375/logs.from.keeper2.txt)

[logs from keeper1.txt](https://github.com/ClickHouse/ClickHouse/files/11715376/logs.from.keeper1.txt)

[logs from keeper 3.txt](https://github.com/ClickHouse/ClickHouse/files/11715374/logs.from.keeper.3.txt)

**Comment by DanRoscigno** [comment]
Check all of your config files and see if any of them refer to localhost, the error message is saying that the keeper server cannot open port 9234 on localhost, but it should not be trying to open anything on localhost, it should be using either the hostname or the IP addr of the actual servers.

**Comment by ashraf-4** [comment]
> Check all of your config files and see if any of them refer to localhost, the error message is saying that the keeper server cannot open port 9234 on localhost, but it should not be trying to open anything on localhost, it should be using either the hostname or the IP addr of the actual servers.


for bad luck nothing referring to local host as all config files same as clickhouse docs. 
but i need to confirm one thing, when you installed clickhouse keeper-servers did you install clickhouse server or only keeper server is enough.

**Comment by DanRoscigno** [comment]
ok, I tested in VMs and had to switch to using `/etc/clckhouse-keeper/keeper_config.xml` . It is possible to set the path to the config on the commandline, but since systemctl looks for the above I am sticking with that file.  The docs will be updated in about ten minutes.  Thanks for finding this issue @ashraf-4 !

**Comment by ashraf-4** [comment]
thanks Dan ,i will test it again and comeback to you ASAP.

**Comment by ashraf-4** [comment]
Dan, Please confirm if you test it successfully  after changing the file to correct path /etc/clickhouse-keeper/keeper.config

**Comment by DanRoscigno** [comment]
> Dan, Please confirm if you test it successfully after changing the file to correct path /etc/clickhouse-keeper/keeper.config

yes, everything worked fine.  Here are the configs etc. that I used.  If you use vagrant, there is a vagrantfile.
[replication.zip](https://github.com/ClickHouse/ClickHouse/files/11757873/replication.zip)

**Comment by DanRoscigno** [comment]
If you loop in mounted_files there are two shell scripts, one for clickhouse-01 and 02, and one for the three keeper servers to copy the files into place.

**Comment by ashraf-4** [comment]
Hi Dan, i configured VM as we agreed about path now all config file are matched to docs . 
the result came like this : 
1- database replication , successfully 
2- table replication , successfully 
but when i inserted data inside tables not replicated , i used this command "SELECT * FROM system.replication_queue" 
it showing all data which should replicate.
 in err.log for keeper2 and 3  "showing always "2023.06.16 08:27:41.981220 [ 1372 ] {} <Error> RaftInstance: 1 nodes (out of 2, 2 including learners) are not responding longer than 10000 ms, at least 2 nodes (including leader) should be alive to proceed commit
2023.06.16 08:27:41.981264 [ 1372 ] {} <Warning> RaftInstance: we cannot yield the leadership of this small cluster
2023.06.16 08:27:41.981675 [ 1372 ] {} <Warning> RaftInstance: Receive AppendEntriesRequest from another leader (2) with same term, there must be a bug. Ignore it instead of exit.
2023.06.16 08:27:41.981686 [ 1372 ] {} <Warning> RaftInstance: no response is returned from raft message handler

**Comment by DanRoscigno** [comment]
Thanks @ashraf-4 

Support told me that when Keeper nodes are reconfigured that they may need a new ID.  They added this note to the docs:
```
note

If for any reason a Keeper node is replaced or rebuilt, do not reuse an existing server_id. 
For example, if the Keeper node with server_id of 2 is rebuilt, give it server_id of 4 or higher.
```

So, can you stop the keepers and edit /etc/clickhouse-keeper/keeper_config.xml on each server and change this section to have `<id>4</id>`, `<id>5</id>`, and `<id>6</id>` instead of 1,2,3:
```xml
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>clickhouse-keeper-01</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>2</id>
                <hostname>clickhouse-keeper-02</hostname>
                <port>9234</port>
            </server>
            <server>
                <id>3</id>
                <hostname>clickhouse-keeper-03</hostname>
                <port>9234</port>
            </server>
```

And in the same file on each server change the `<server_id>1</server_id>` line:
- on clickhouse-keeper-01 change `<server_id>1</server_id>` to `<server_id>4</server_id>`
- on clickhouse-keeper-02 change `<server_id>2</server_id>` to `<server_id>5</server_id>`
- on clickhouse-keeper-03 change `<server_id>3</server_id>` to `<server_id>6</server_id>`

**Comment by ashraf-4** [comment]
> Thanks @ashraf-4
> 
> Support told me that when Keeper nodes are reconfigured that they may need a new ID. They added this note to the docs:
> 
> ```
> note
> 
> If for any reason a Keeper node is replaced or rebuilt, do not reuse an existing server_id. 
> For example, if the Keeper node with server_id of 2 is rebuilt, give it server_id of 4 or higher.
> ```
> 
> So, can you stop the keepers and edit /etc/clickhouse-keeper/keeper_config.xml on each server and change this section to have `<id>4</id>`, `<id>5</id>`, and `<id>6</id>` instead of 1,2,3:
> 
> ```
>         <raft_configuration>
>             <server>
>                 <id>4</id>
>                 <hostname>clickhouse-keeper-01</hostname>
>                 <port>9234</port>
>             </server>
>             <server>
>                 <id>5</id>
>                 <hostname>clickhouse-keeper-02</hostname>
>                 <port>9234</port>
>             </server>
>             <server>
>                 <id>6</id>
>                 <hostname>clickhouse-keeper-03</hostname>
>                 <port>9234</port>
>             </server>
> ```
> 
> And in the same file on each server change the `<server_id>1</server_id>` line:
> 
> * on clickhouse-keeper-01 change `<server_id>1</server_id>` to `<server_id>4</server_id>`
> * on clickhouse-keeper-02 change `<server_id>2</server_id>` to `<server_id>5</server_id>`
> * on clickhouse-keeper-03 change `<server_id>3</server_id>` to `<server_id>6</server_id>`

Hi Dan, 
finally all keepers working fine and clickhouse servers also .
root@keeper1:/etc/clickhouse-keeper# echo mntr | nc localhost 9181
zk_version      v23.5.2.7-stable-5751aa1ab9f2364dbed942a78c3083215fdbf11a
zk_avg_latency  0
zk_max_latency  6
zk_min_latency  0
zk_packets_received     8969
zk_packets_sent 8975
zk_num_alive_connections        2
zk_outstanding_requests 0
zk_server_state leader
zk_znode_count  75
zk_watch_count  6
zk_ephemerals_count     2
zk_approximate_data_size        22513
zk_key_arena_size       12288
zk_latest_snapshot_size 0
zk_open_file_descriptor_count   45
zk_max_file_descriptor_count    18446744073709551615
zk_followers    2
zk_synced_followers     2

but i am still stuck in date replication ,till now data not replicated, in log file everything is normal and he leader keep contact with follower.
alos in " system.replication_queue"  i can see the row which waiting to replicate. 
please advice.

**Comment by DanRoscigno** [comment]
Hi @ashraf-4 did the data replicate?  Please have a look at the docs on best practices, maybe you should be using async inserts and are not?  My testing was with a small amount of data as I was running all five machines in VMs on my laptop.  Replication should happen very quickly on production machines.  Best practices: https://clickhouse.com/docs/en/optimize/asynchronous-inserts

**Comment by ashraf-4** [comment]
> Hi @ashraf-4 did the data replicate? Please have a look at the docs on best practices, maybe you should be using async inserts and are not? My testing was with a small amount of data as I was running all five machines in VMs on my laptop. Replication should happen very quickly on production machines. Best practices: https://clickhouse.com/docs/en/optimize/asynchronous-inserts

Hi @DanRoscigno the data didn't replicated yet i tried many ways. 

[leader log .txt](https://github.com/ClickHouse/ClickHouse/files/11817957/leader.log.txt)
[node1.txt](https://github.com/ClickHouse/ClickHouse/files/11817958/node1.txt)
[node2.txt](https://github.com/ClickHouse/ClickHouse/files/11817959/node2.txt)
 this is log files from servers i didn't see anything abnormal, kindly advice .

**Comment by DanRoscigno** [comment]
ok, let's start with a minimal test.  Try the steps in this doc starting from *Testing* https://clickhouse.com/docs/en/architecture/replication#testing

**Comment by ashraf-4** [comment]
> ok, let's start with a minimal test. Try the steps in this doc starting from _Testing_ https://clickhouse.com/docs/en/architecture/replication#testing

Hi Dan , i already do same test. 
till this step every thing is working fine : 2-Create a table on the database using the ReplicatedMergeTree table engine.
and if i insert data in node1 it wont replicate in node2 ,
also if i insert data in node2 it wont replicate in node1. 
but in both case when i apply this command "SELECT * FROM  system.replication_queue ; " 
i can see all data which waiting to replicate.

**Comment by DanRoscigno** [comment]
@ashraf-4 I asked someone else to have a look, I can't see the issue.

**Comment by alex1704** [comment]
@ashraf-4 what error do you see when you execute "SELECT * FROM system.replication_queue ; "?
