### ISSUE TITLE
Bad usability of exception messages when a file already exists in INTO OUTFILE

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#50707]
**Describe the issue**
```
milovidov-desktop :) SELECT * FROM numbers(10) INTO OUTFILE 'numbers.tsv'

SELECT *
FROM numbers(10)
INTO OUTFILE 'numbers.tsv'

Query id: 4512f761-2b36-4a25-9ccd-22982a17eb64

Ok.
Exception on client:
Code: 76. DB::Exception: Code: 76. DB::ErrnoException: Cannot open file numbers.tsv, errno: 17, strerror: File exists. (CANNOT_OPEN_FILE) (version 23.5.1.1). (CANNOT_OPEN_FILE)
```

1. It prints Ok, but then prints the exception message.
2. It prints `Code: 76.` and `Exception` twice.
3. It prints `CANNOT_OPEN_FILE` twice.
4. It does not suggest the usage of the `APPEND` syntax.

**Comment by zhicwu** [comment]
How can we enforce file override? FYI, I added exclamation mark suffix for this in JDBC driver, for example:
```sql
SELECT * FROM numbers(10) INTO OUTFILE '~/numbers.tsv'
file         |format|compression|level|bytes|
-------------+------+-----------+-----+-----+
~/numbers.tsv|TSV   |none       |   -1|   20|

SELECT * FROM numbers(10) INTO OUTFILE '~/numbers.tsv'
SQL Error [HY000]: Output file [/Users/zhicwu/numbers.tsv] already exists!

SELECT * FROM numbers(10) INTO OUTFILE '~/numbers.tsv!'
file         |format|compression|level|bytes|
-------------+------+-----------+-----+-----+
~/numbers.tsv|TSV   |none       |   -1|   20|
```

**Comment by alexey-milovidov** [comment]
@zhicwu Introduce `INTO OUTFILE '...' TRUNCATE` similarly to `INTO OUTFILE '...' APPEND`.

PS. I don't like the idea of an exclamation mark because it is a "mini-language" inside a file name, and maybe the file name can contain an exclamation mark already.

**Comment by zhicwu** [comment]
Thanks. Will sync the change in jdbc driver for consistency.

**Comment by alekar** [comment]
@alexey-milovidov I'll take this.
