### ISSUE TITLE
Permissions for ReadOnly User

### ISSUE THREAD

**Issue by T-M-L-C** [ClickHouse/ClickHouse#50716]
When I set the user TEST to read-only for ClickHouse, I want the TEST user to no longer have write permissions. In the actual test process, the data can still be loaded to the database by using the  ./clickhouse-client -host 127.0.0.1 -u TEST --query="${insertsql}" . However, when I log in to the ClickHouse server and run the insert into table values('Field 1','Field 2') command, the system prompts that the user has only read-only permission. Why?

![image](https://github.com/ClickHouse/ClickHouse/assets/12447886/79cbb62e-55ff-44bc-a11e-adf06c5dd101)

**Comment by den-crane** [comment]
1)
>In the actual test process, the data can still be loaded to the database by using the ./clickhouse-client -host 127.0.0.1 -u TEST --query="${insertsql}" . 

2)
>However, when I log in to the ClickHouse server and run the insert into table values('Field 1','Field 2') command, the system prompts that the user has only read-only permission. Why?

What is the difference between 1 & 2 ? What do you mean by "actual test process" ?
Provide reproducible example.

**Comment by T-M-L-C** [comment]
The difference between 1 and 2 is that 1 uses the clickhouse-client -q "INSERT INTO sometable FORMAT CSV" < data_small.csv mode and 2 uses the PreparedStatement pstmt = connection.prepareStatement("insert into sometable values(?, ?, ?)"); mode. No error is reported. The system prompts that the current database user Test has only the read-only permission.

**Comment by den-crane** [comment]
OK. 
Another question. Why do you try to make `default` profile readonly? `default` profile is a system profile and server cannot work properly if the system profile is readonly.

**Comment by T-M-L-C** [comment]
This is just an example I gave. The actual format is as follows:
![image](https://github.com/ClickHouse/ClickHouse/assets/12447886/4e504c13-1406-4c48-b0c0-a8d70b26cf3a)

I expect this configuration to ensure that the TEST user does not have any write permissions, but  uses the clickhouse-client -q "INSERT INTO sometable FORMAT CSV" < data_small.csv mode. Data can be written to ClickHouse through the TEST user.How to solve this scenario problem?

**Comment by den-crane** [comment]
you should pass a username with  clickhouse-client: ` clickhouse-client -u test --password`
BTW, it's impossible to pass epmty password for non-default user using clickhouse-client.
I was able to login by the test user only using prompt + key `<Enter>`.



```xml
cat /etc/clickhouse-server/users.d/test.xml
<?xml version="1.0"?>
<clickhouse>
    <profiles>
        <readonly>
            <readonly>2</readonly>
        </readonly>
    </profiles>
    <users>
        <test>
            <profile>readonly</profile>
        </test>
    </users>
</clickhouse>
```

```sql
create table test (A Int64) Engine=Log;
```

```bash
# clickhouse-client -u test --password
ClickHouse client version 23.3.3.52 (official build).
Password for user (test):
Connecting to localhost:9000 as user test.
Connected to ClickHouse server version 23.3.3 revision 54462.

Warnings:
 * Some obsolete setting is changed. Check 'select * from system.settings where changed' and read the changelog.

chdw1-2.sde894.mycmdb.net :) insert into test values(1);

INSERT INTO test FORMAT Values

Query id: 13b5813b-9c1d-44ec-bd1e-27a65dd6831d


0 rows in set. Elapsed: 0.001 sec.

Received exception from server (version 23.3.3):
Code: 164. DB::Exception: Received from localhost:9000. DB::Exception: test: Cannot execute query in readonly mode. (READONLY)
```
