### ISSUE TITLE
Azure blob storage as destination for embedded backup

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#50747]
**Use case**

BACKUP TABLE xxx TO AzureBlobStorage(....)

**Describe the solution you'd like**

Native support for backups to Blob Storage

**Describe alternatives you've considered**

Backup to blob storage based disks, but it needs to backup local metadata

**Comment by alesapin** [comment]
Implement 2 classes similar to https://github.com/clickhouse/ClickHouse/blob/master/src/Backups/BackupIO_S3.h#L17-L64

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/56988
