### ISSUE TITLE
Inter server inserts (Distributed table engine) do not use max_memory_usage from config

### ISSUE THREAD

**Issue by Nikoslav** [ClickHouse/ClickHouse#50744]
Inter server inserts do not use max_memory_usage from config. It stays at 10^9b ~9.31Gb.

Config(tried 10G, 20G, 0, same result):
`<max_memory_usage>0</max_memory_usage>`
Clickhouse settings

`max_memory_usage                            │ UInt64     │ 0`
`max_memory_usage_for_user                   │ UInt64     │ 0` 

Clickhouse collects config, but does not use it.

Error msg:
```

2023.06.08 11:49:25.709330 [ 3545951 ] {} <Error> default.table.DirectoryMonitor: Code: 241. DB::Exception: Received from node3:9440. DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 4219652 bytes), maximum: 9.31 GiB. OvercommitTracker decision: Memory overcommit isn't used. OvercommitTracker isn't set.. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ffe9a in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> > >(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<char const*>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<std::__1::basic_string_view<char, std::__1::char_traits<char> > >::type>, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, std::__1::basic_string_view<char, std::__1::char_traits<char> >&&) @ 0xa3f2517 in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xa3f1f01 in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xa3f1932 in /usr/bin/clickhouse
4. DB::Memory<Allocator<false, false> >::alloc(unsigned long) @ 0xa45fda4 in /usr/bin/clickhouse
5. DB::MergeTreeDataPartWriterOnDisk::Stream::Stream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, unsigned long, DB::WriteSettings const&) @ 0x1592b694 in /usr/bin/clickhouse
6. ? @ 0x159351ec in /usr/bin/clickhouse
7. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x14231b31 in /usr/bin/clickhouse
8. DB::SerializationNullable::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x1425b1a5 in /usr/bin/clickhouse
9. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::__1::shared_ptr<DB::IDataType const> const&) const @ 0x14231f35 in /usr/bin/clickhouse
10. DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::IAST> const&) @ 0x1592ecfe in /usr/bin/clickhouse
11. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x1592eb4a in /usr/bin/clickhouse
12. DB::MergeTreeDataPartWide::getWriter(std::__1::shared_ptr<DB::IDataPartStorageBuilder>, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const @ 0x1591ebb4 in /usr/bin/clickhouse
13. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder>, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, std::__1::shared_ptr<DB::MergeTreeTransaction> const&, bool, bool, DB::WriteSettings const&) @ 0x15a15892 in /usr/bin/clickhouse
14. DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x15a021ce in /usr/bin/clickhouse
15. DB::MergeTreeSink::consume(DB::Chunk) @ 0x159fa860 in /usr/bin/clickhouse
16. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x15f93588 in /usr/bin/clickhouse
17. ? @ 0x15eeb7f7 in /usr/bin/clickhouse
18. ? @ 0x15eeb519 in /usr/bin/clickhouse
19. DB::ExceptionKeepingTransform::work() @ 0x15eead8e in /usr/bin/clickhouse
20. DB::ExecutionThreadContext::executeTask() @ 0x15d158ca in /usr/bin/clickhouse
21. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15d09e3b in /usr/bin/clickhouse
22. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x15d09008 in /usr/bin/clickhouse
23. DB::TCPHandler::processInsertQuery() @ 0x15cae2cc in /usr/bin/clickhouse
24. DB::TCPHandler::runImpl() @ 0x15ca5e5a in /usr/bin/clickhouse
25. DB::TCPHandler::run() @ 0x15cba1d9 in /usr/bin/clickhouse
26. Poco::Net::TCPServerConnection::start() @ 0x18a2eb93 in /usr/bin/clickhouse
27. Poco::Net::TCPServerDispatcher::run() @ 0x18a2feed in /usr/bin/clickhouse
28. Poco::PooledThread::run() @ 0x18bf2849 in /usr/bin/clickhouse
29. Poco::ThreadImpl::runnableEntry(void*) @ 0x18bf0102 in /usr/bin/clickhouse
30. ? @ 0x7f3047ebeb43 in ?
31. ? @ 0x7f3047f50a00 in ?
: While sending /clkhsdb/clickhouse/data/default/table/shard3_replica1/58621.bin. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ffe9a in /usr/bin/clickhouse
1. DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) @ 0xa4710fe in /usr/bin/clickhouse
2. DB::Connection::receiveException() const @ 0x15b933a5 in /usr/bin/clickhouse
3. DB::Connection::receivePacket() @ 0x15b9b46f in /usr/bin/clickhouse
4. DB::RemoteInserter::onFinish() @ 0x157a2412 in /usr/bin/clickhouse
5. DB::StorageDistributedDirectoryMonitor::processFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15794213 in /usr/bin/clickhouse
6. DB::StorageDistributedDirectoryMonitor::run() @ 0x1578f1c4 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13f2eef8 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePool::threadFunction() @ 0x13f317d6 in /usr/bin/clickhouse
9. ? @ 0x13f3250c in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4c1a48 in /usr/bin/clickhouse
11. ? @ 0xa4c4c5d in /usr/bin/clickhouse
12. ? @ 0x7f4a98dfcb43 in ?
13. ? @ 0x7f4a98e8ea00 in ?
 (version 22.8.15.23 (official build))

```

**How to reproduce**
version(LTS): 22.8.15.23 or 23.3.2 revision 54462
A big table with ~1500 columns, many of them of Array(Nullable(Int64)) type.
CREATE TABLE data.table
(
    `date_start` DateTime64(3, 'UTC'),
    `date_end` DateTime64(3, 'UTC'),
    `ttldate` Date,
    `node` String,
...
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(date_end)
ORDER BY (date_end, node)
TTL ttldate + toIntervalDay(800)
SETTINGS index_granularity = 8192

CREATE TABLE default.table
(
    `date_start` DateTime64(3, 'UTC'),
    `date_end` DateTime64(3, 'UTC'),
    `ttldate` Date,
    `node` String,
...
)
ENGINE = Distributed('cluster', 'data', 'table', sipHash64(ttldate))

CREATE MATERIALIZED VIEW mview.table TO default.table
(
    `date_start` DateTime64(3, 'UTC'),
    `date_end` DateTime64(3, 'UTC'),
    `ttldate` Date,
    `node` String,
    ...
)
AS
SELECT *
FROM kafka.table

**Comment by den-crane** [comment]
DirectoryMonitor uses default profile during data insertion

Please share the full config with `max_memory_usage`.

**Comment by den-crane** [comment]
Also DirectoryMonitor requires Clickhouse restart to apply changes in the profile.

**Comment by Nikoslav** [comment]
<profiles>
        <default>
            <receive_timeout>1800</receive_timeout>
            <background_pool_size>24</background_pool_size>
            <max_block_size>655360</max_block_size>
            <max_insert_block_size>524288</max_insert_block_size>
            <max_memory_usage>0</max_memory_usage>
            <max_parser_depth>0</max_parser_depth>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>random</load_balancing>
            <background_schedule_pool_size>32</background_schedule_pool_size>
        </default>
    </profiles>


I have rebooted several times.

**Comment by den-crane** [comment]
I see.

Can you do this:

```
mkdir /clkhsdb/clickhouse/mytmp
mv /clkhsdb/clickhouse/data/default/table/shard3_replica1/58621.bin /clkhsdb/clickhouse/mytmp
```
and check for errors again

**Comment by den-crane** [comment]
check the date of the file, is it the new file or the old?

```
ls -l  /clkhsdb/clickhouse/data/default/table/shard3_replica1/58634.bin
```

**Comment by Nikoslav** [comment]
Date is the same, but size and contents are different.
Inside shard3_replica1:
-rw-r----- 1 clickhouse clickhouse  3416272 Jun  7 15:07 58621.bin
-rw-r----- 1 clickhouse clickhouse   760497 Jun  7 15:07 58623.bin
-rw-r----- 1 clickhouse clickhouse   639272 Jun  7 15:07 58625.bin
-rw-r----- 1 clickhouse clickhouse   708498 Jun  7 15:07 58627.bin
-rw-r----- 1 clickhouse clickhouse   867720 Jun  7 15:07 58629.bin
-rw-r----- 1 clickhouse clickhouse   847412 Jun  7 15:07 58631.bin
-rw-r----- 1 clickhouse clickhouse   914437 Jun  7 15:07 58633.bin
-rw-r----- 1 clickhouse clickhouse 10992354 Jun  7 15:10 58635.bin
-rw-r----- 1 clickhouse clickhouse  2374161 Jun  7 15:10 58637.bin
-rw-r----- 1 clickhouse clickhouse   980255 Jun  7 15:10 58639.bin
-rw-r----- 1 clickhouse clickhouse   964257 Jun  7 15:10 58641.bin
-rw-r----- 1 clickhouse clickhouse   868472 Jun  7 15:11 58643.bin
-rw-r----- 1 clickhouse clickhouse   829331 Jun  7 15:11 58645.bin
-rw-r----- 1 clickhouse clickhouse  8054624 Jun  7 15:14 58647.bin
-rw-r----- 1 clickhouse clickhouse   959341 Jun  7 15:14 58649.bin
-rw-r----- 1 clickhouse clickhouse   501397 Jun  7 15:14 58651.bin
-rw-r----- 1 clickhouse clickhouse   487360 Jun  7 15:14 58653.bin
-rw-r----- 1 clickhouse clickhouse   530220 Jun  7 15:14 58655.bin
-rw-r----- 1 clickhouse clickhouse   490905 Jun  7 15:14 58657.bin
-rw-r----- 1 clickhouse clickhouse   509561 Jun  7 15:14 58659.bin
-rw-r----- 1 clickhouse clickhouse  3544048 Jun  7 15:17 58661.bin
...
About 5k files, 4Gb in size total.

58634.bin is from shard2_replica1, to avoid confusion. I removed the first file in line from both shards.
What is curious is that on shard1, insert was successful and all 3 have the same config and hw.

Thanks!

**Comment by Nikoslav** [comment]
I have tested this on other versions:
22.8.15.23
22.8.16.32
23.5.2.7

**Comment by Nikoslav** [comment]
Update: if i use synchronous inserts(insert_distributed_sync=1) it works fine.

**Comment by alexey-milovidov** [comment]
New ClickHouse versions, including 23.5, 23.6, and 23.7, have `max_memory_usage` unlimited by default, while older versions have it limited to 10 GiB. This means that the issue is less relevant for newer versions, but you can have `max_memory_usage` set to 10 GiB stuck somewhere in configuration files.

**Comment by Nikoslav** [comment]
Version on all nodes: 
23.5.2 revision 54462

Settings on all nodes:
┌─name─────────────────────────────┬─type───┬─value─┐
│ max_memory_usage                 │ UInt64 │ 0     │
│ max_memory_usage_for_all_queries │ UInt64 │ 0     │
│ max_memory_usage_for_user        │ UInt64 │ 0     │
└──────────────────────────────────┴────────┴───────┘


Error:
2023.08.07 05:21:03.370507 [ 1384287 ] {c7e37172-314d-4caf-86c6-2cf4cd9884e5} <Error> executeQuery: Code: 241. DB::Exception: Memory limit (for query) exceeded: would use **9.31 GiB** (attempt to allocate chunk of 4360304 bytes), maximum: 9
.31 GiB. (MEMORY_LIMIT_EXCEEDED) (**version 23.5.2.7** (official build)) (from [::ffff:10.139.121.17]:53708) (in query: INSERT INTO...
VALUES), Stack trace (when copying this message, always include the lines below):
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e3453d5 in /usr/bin/clickhouse
1. ? @ 0x000000000e351b4a in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x000000000e35169b in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x000000000e350fe9 in /usr/bin/clickhouse
4. CurrentMemoryTracker::alloc(long) @ 0x000000000e315f05 in /usr/bin/clickhouse
5. Allocator<false, false>::alloc(unsigned long, unsigned long) @ 0x00000000081475c4 in /usr/bin/clickhouse
6. ? @ 0x000000000e3932e2 in /usr/bin/clickhouse
7. DB::MergeTreeDataPartWriterOnDisk::Stream::Stream(String const&, std::shared_ptr<DB::IDataPartStorage> const&, String const&, String const&, String const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, DB::WriteSettings const&) @ 0x00000000148bdc13 in /usr/bin/clickhouse
8. ? @ 0x00000000148cef5c in /usr/bin/clickhouse
9. DB::ISerialization::enumerateStreams(DB::ISerialization::EnumerateStreamsSettings&, std::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x0000000012ddc293 in /usr/bin/clickhouse
10. DB::SerializationNullable::enumerateStreams(DB::ISerialization::EnumerateStreamsSettings&, std::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x0000000012e03af2 in /usr/bin/clickhouse
11. DB::ISerialization::enumerateStreams(std::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::shared_ptr<DB::IDataType const> const&, COW<DB::IColumn>::immutable_ptr<DB::IColumn> const&) const @ 0x0000000012ddc5c1 in /usr/bin/clickhouse
12. DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, std::shared_ptr<DB::IAST> const&) @ 0x00000000148c5b87 in /usr/bin/clickhouse
13. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::shared_ptr<DB::IMergeTreeDataPart> const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, String const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x00000000148c5a3e in /usr/bin/clickhouse
14. DB::MergeTreeDataPartWide::getWriter(DB::NamesAndTypesList const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x00000000148b09e1 in /usr/bin/clickhouse
15. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::shared_ptr<DB::IMergeTreeDataPart> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::vector<std::shared_ptr<DB::IMergeTreeIndex const>, std::allocator<std::shared_ptr<DB::IMergeTreeIndex const>>> const&, std::shared_ptr<DB::ICompressionCodec>, std::shared_ptr<DB::MergeTreeTransaction> const&, bool, bool, DB::WriteSettings const&) @ 0x00000000149fc7ba in /usr/bin/clickhouse
16. DB::MergeTreeDataWriter::writeTempPartImpl(DB::BlockWithPartition&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, long, bool) @ 0x00000000149f5c95 in /usr/bin/clickhouse
17. DB::MergeTreeSink::consume(DB::Chunk) @ 0x0000000014b7fe5c in /usr/bin/clickhouse
18. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x0000000014ff5986 in /usr/bin/clickhouse
19. ? @ 0x0000000014f3c0eb in /usr/bin/clickhouse
20. ? @ 0x0000000014f3be1c in /usr/bin/clickhouse
21. DB::ExceptionKeepingTransform::work() @ 0x0000000014f3b6d8 in /usr/bin/clickhouse
22. DB::ExecutionThreadContext::executeTask() @ 0x0000000014d36289 in /usr/bin/clickhouse
23. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014d2cf10 in /usr/bin/clickhouse
24. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x0000000014d2c6c8 in /usr/bin/clickhouse
25. DB::TCPHandler::processInsertQuery() @ 0x0000000014cdb9f6 in /usr/bin/clickhouse
26. DB::TCPHandler::runImpl() @ 0x0000000014cd2c80 in /usr/bin/clickhouse
27. DB::TCPHandler::run() @ 0x0000000014ce8579 in /usr/bin/clickhouse
28. Poco::Net::TCPServerConnection::start() @ 0x0000000017c2ec54 in /usr/bin/clickhouse
29. Poco::Net::TCPServerDispatcher::run() @ 0x0000000017c2fe71 in /usr/bin/clickhouse
30. Poco::PooledThread::run() @ 0x0000000017dacb27 in /usr/bin/clickhouse
31. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017daa55c in /usr/bin/clickhouse

**Comment by alexey-milovidov** [comment]
This 10 GB limit comes from somewhere in configuration files.

**Comment by Nikoslav** [comment]
Sorry to bother you, but i cannot find the 10G limit anywhere.

root@node1:/etc/clickhouse-server# grep -ri max_memory_usage .
./users.d/users.xml:            <max_memory_usage>0</max_memory_usage>

root@node2:/etc/clickhouse-server# grep -ri max_memory_usage .
./users.d/users.xml:            <max_memory_usage>0</max_memory_usage>

root@node3:/etc/clickhouse-server# grep -ri max_memory_usage .
./users.d/users.xml:            <max_memory_usage>0</max_memory_usage>

This is under the default block like so:
<clickhouse>
    <profiles>
        <default>
            <max_memory_usage>0</max_memory_usage>
       </default>
    </profiles>
</clickhouse>

**Comment by Nikoslav** [comment]
Still the same with version 23.7.4 revision 54465.
