### ISSUE TITLE
Use with as statement to avoid duplicate query not work

### ISSUE THREAD

**Issue by YingHongBin** [ClickHouse/ClickHouse#50741]
**Describe the unexpected behaviour**
I want to use with as expression to avoid duplicate query to improve query performance. The sql like
```
WITH table1 AS
(
    subquery
)
SELECT (
(
    do some query from table1
) AS metric 1,
(
    do some query from table1
) AS metric 2
```
Accroding to the final response time, is seems the table1 subquery is executed mutli-times, but it is expected to executed once and stored as tmp table to be used in following query.

**Comment by den-crane** [comment]
it's expected behaviour, WITH does not materialize data, no such feature.
The final query expands `table1` with the `subquery` twice, and executes it twice.
By design.
