### ISSUE TITLE
Perf tests: error in `join_set_filter`

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#50752]
https://s3.amazonaws.com/clickhouse-test-reports/50710/d82a8a6a1060928837ddf0449f4fdebdb15f376d/performance_comparison_[1_4]/report.html

**Comment by vdimir** [comment]
I'll try to resubmit the test without unstable queries https://github.com/ClickHouse/ClickHouse/pull/60674 Will see if it pan out
