### ISSUE TITLE
docker run error 

### ISSUE THREAD

**Issue by samz406** [ClickHouse/ClickHouse#5079]
Hi！ I docker run clickhouse error, as follow error info.
![image](https://user-images.githubusercontent.com/3055810/56500906-44047a80-653f-11e9-83e6-58adbcafb668.png)

My OS is centos 7.4,pull latest image.

**Comment by filimonov** [comment]
Maybe connected with #4947

**Comment by filimonov** [comment]
Also such an error can happen if clickhouse-extract-from-config fails
