### ISSUE TITLE
Allow using `cluster`, `clusterAllReplicas`, `remote`, and `remoteSecure` without table name.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#50808]
**Use case**

```
SELECT hostname(), uptime() FROM clusterAllReplicas(default, system.one)
```

Let's allow writing it this way:
```
SELECT hostname(), uptime() FROM clusterAllReplicas(default)
```

**Additional context**

For `remote`, `remoteSecure` allow short form only if there is only one argument, and there is no database, table, user names, and password.

Also, let's think about introducing the notion of the default cluster.

**Comment by LiuYangkuan** [comment]
Please assign to me.

**Comment by alexey-milovidov** [comment]
@LiuYangkuan thank you!

**Comment by alexey-milovidov** [comment]
Done.
