### ISSUE TITLE
Add `hostname` column to every system log table.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#50815]
**Use case**

Sometimes you want to make system log tables replicated across the cluster.
But then you need to know where the records originated.

**Describe the solution you'd like**

`hostname LowCardinality(String)`

**Additional context**

By default, the column will be redundant (containing just a single value). This is fine.

I'm not sure if `hostname` is enough, and don't we need an IP address, FQDN, or display name as well? But let's start with the hostname only.

**Comment by MrSach** [comment]
Hello, I would be interested to explore this feature request.
Where can I start with this?

**Comment by alexey-milovidov** [comment]
See the usages of the `SystemLog` class and the function `getFQDNOrHostName()`.

**Comment by MrSach** [comment]
Thank you for your response to this.
Would the usages be in the header/source files, or would they be found somewhere else?

I also have some other development-related queries, but I am not sure where to ask them.
Is this a good place to ask them?

**Comment by alexey-milovidov** [comment]
You can also ask in https://clickhouse.com/slack

**Comment by alexey-milovidov** [comment]
> Would the usages be in the header/source files, or would they be found somewhere else?

The changes are expected both in .h and .cpp.

**Comment by MrSach** [comment]
Thank you for letting me know this.
I will see where would be most sensible to add the hostname to start with.
As for the slack link, I will look into that too.

**Comment by jsat97** [comment]
@MrSach Could you pls provide an example of a similar field in the code which could be used as a guideline ?

**Comment by bharatnc** [comment]
I think this can be closed, implemented in #55894
