### ISSUE TITLE
Add a column `is_obsolete` to `system.settings` and similar tables.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#50819]
**Use case**

```
Warnings:
 * Some obsolete setting is changed. Check 'select * from system.settings where changed' and read the changelog.
```

but how do I know?

**Additional context**

The warning message should list the specific obsolete settings as well.

**Comment by tavplubix** [comment]
> Check 'select * from system.settings where changed' and read the changelog.

> but how do I know?

By reading the changelog? In many cases, settings become obsolete due to a backward incompatible change. Such change may have other unexpected effects, so reading the changelog is much better than simply removing a changed setting from the config just because `clickhouse-client` suggested to do so

**Comment by alexey-milovidov** [comment]
@tavplubix, ok, but I think the proposed usability improvement is still worth it - we will be more user-friendly.
