### ISSUE TITLE
Automatically field detection ingestion from kafka topic JSON messages.

### ISSUE THREAD

**Issue by MahRokhK** [ClickHouse/ClickHouse#50825]
I'm trying to stream into a clickhouse table from a kafka topic messages (in JSON format), in the way that it would automatically detect all the existing fields in messages and whenever there's a new field in the messages, it would automatically make corresponding column in the clickhouse destination table. (obviously the value of the new column for the previously ingested messages would be null) 
my second preference is that the data type of the new auto added columns would be the same as the value of the new field. (but this is my second priority and if there's no way to have both advantages I prefer the first as auto field detection is necessary for me)

I've tried Kafka Table Engine (set up with a materialized view and  a destination table with merge tree) but it is only responding to the fields which are defined in the "CREATE TABLE" command (with kafka engine) and all the other fields inside of the kafka topic messages are dropped in the first step when it is fetching from the topic with kafka table engine. 

I've tried "SET input_format_skip_unknown_fields=0" in clickhouse client but it seems that it doesn't have effect on kafka table engine. at the firs place I think that the fetcher from kafka topic ( the kafka table engine) should be able to scratch all the fields existing in the message not only the ones I define in the create command. 

The point is that  there are too many fields in the messages and there's a possibility that a new field would be added to them at any time. and I don't want to handle this evolution manually with "ALTER TABLE" command as the time of additions might be unknown and the data might be lost.

**Comment by MahRokhK** [comment]
also if there is any other approach to do so rather than kafka table engine I would be tankful to mention it with few details.

**Comment by den-crane** [comment]
https://stackoverflow.com/a/76425038/11644308

https://clickhouse.com/docs/en/sql-reference/formats#jsonasstring

https://kb.altinity.com/altinity-kb-schema-design/altinity-kb-jsonasstring-and-mat.-view-as-json-parser/

https://kb.altinity.com/altinity-kb-queries-and-syntax/jsonextract-to-parse-many-attributes-at-a-time/
