### ISSUE TITLE
CASE expression with nullable type doesn't work

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/ClickHouse#50827]
> You have to provide the following information whenever possible.

The following SQL fails:

```
:) select case 1::Nullable(Int32) when 1 then 1 else 0 end;
```

Error:

```
Received exception from server (version 23.5.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: First argument and elements of array of second argument of function transform must have compatible types: both numeric or both strings.: While processing caseWithExpression(CAST('1', 'Nullable(Int32)'), 1, 1, 0). (ILLEGAL_TYPE_OF_ARGUMENT)
```

> A clear and concise description of what works not as it is supposed to.

I would expect this to return `1`

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

https://fiddle.clickhouse.com/2091d88d-162a-41a6-9e7c-a67091a4b3a7

**Does it reproduce on recent release?**

It does. Here's the information from `clickhouse client` startup:

```
ClickHouse client version 23.3.2.1.
Connecting to database ibis_testing at localhost:9000 as user default.
Connected to ClickHouse server version 23.5.1 revision 54462.
```

**Comment by alexey-milovidov** [comment]
Will be addressed by this pull request: https://github.com/ClickHouse/ClickHouse/pull/40493

**Comment by SaltTan** [comment]
It worked in 23.4 https://fiddle.clickhouse.com/0fd07687-9dfa-4887-8cf7-efdd0056a502

**Comment by SaltTan** [comment]
maybe #48300 is related?
