### ISSUE TITLE
Exception: default expression and column type are incompatible.: Cannot attach table

### ISSUE THREAD

**Issue by Wachynaky** [ClickHouse/ClickHouse#50847]
Hello, when trying to start CH, it gives an error. The error message in the logs seems to indicate that the problem is in a UDF function.

`0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e3453d5 in /usr/bin/clickhouse
1. ? @ 0x000000000e3ed57d in /usr/bin/clickhouse
2. DB::FunctionFactory::getImpl(String const&, std::shared_ptr<DB::Context const>) const @ 0x00000000127f6f88 in /usr/bin/clickhouse
3. DB::FunctionFactory::get(String const&, std::shared_ptr<DB::Context const>) const @ 0x00000000127f7aaa in /usr/bin/clickhouse
4. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x0000000013173556 in /usr/bin/clickhouse
5. DB::ActionsMatcher::visit(DB::ASTFunction const&, std::shared_ptr<DB::IAST> const&, DB::ActionsMatcher::Data&) @ 0x0000000013174172 in /usr/bin/clickhouse
6. ? @ 0x0000000013167e95 in /usr/bin/clickhouse
7. DB::ExpressionAnalyzer::getRootActions(std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ActionsDAG>&, bool) @ 0x0000000013145c5b in /usr/bin/clickhouse
8. DB::ExpressionAnalyzer::getActionsDAG(bool, bool) @ 0x0000000013157445 in /usr/bin/clickhouse
9. DB::ExpressionAnalyzer::getActions(bool, bool, DB::CompileExpressions) @ 0x0000000013157916 in /usr/bin/clickhouse
10. DB::validateColumnsDefaultsAndGetSampleBlock(std::shared_ptr<DB::IAST>, DB::NamesAndTypesList const&, std::shared_ptr<DB::Context const>) @ 0x00000000141d00e7 in /usr/bin/clickhouse
11. DB::InterpreterCreateQuery::getColumnsDescription(DB::ASTExpressionList const&, std::shared_ptr<DB::Context const>, bool) @ 0x0000000013938b62 in /usr/bin/clickhouse
12. DB::createTableFromAST(DB::ASTCreateQuery, String const&, String const&, std::shared_ptr<DB::Context>, bool) @ 0x0000000012e3147a in /usr/bin/clickhouse
13. DB::DatabaseOrdinary::loadTableFromMetadata(std::shared_ptr<DB::Context>, String const&, DB::QualifiedTableName const&, std::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) @ 0x0000000012e5160f in /usr/bin/clickhouse
14. ? @ 0x00000000139e4fff in /usr/bin/clickhouse
15. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e41d363 in /usr/bin/clickhouse
16. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e41fb55 in /usr/bin/clickhouse
17. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e4191f4 in /usr/bin/clickhouse
18. ? @ 0x000000000e41e9e1 in /usr/bin/clickhouse
19. ? @ 0x00007f27d128f18a in ?
20. ? @ 0x00007f27d131dbd0 in ?
 (version 23.5.2.7 (official build))
2023.06.11 02:59:34.173329 [ 56059 ] {} <Error> Application: DB::Exception: Unknown function embeddingsprueba: While processing _CAST(embeddingsprueba(texto) AS embedido_tmp_alter8001877707753062078, 'Array(Float32)') AS embedido: default expression and column type are incompatible.: Cannot attach table `default`.`yttable3` from metadata file /var/lib/clickhouse/store/94a/94a90c24-690b-401a-9716-8027d5875ef4/yttable3.sql from query ATTACH TABLE default.yttable3 UUID '611bf5a1-96de-4b66-832a-b2c27572f5c7' (`fecha` Date, `fichero` String, `texto` String, `linea` String, `duracion` Float32, `comienza` Array(String), `tiempo` Float32, `embedido` Array(Float32) DEFAULT embeddingsprueba(texto)) ENGINE = MergeTree ORDER BY fecha SETTINGS index_granularity = 8192
2023.06.11 03:00:05.011128 [ 57157 ] {} <Warning> Application: Setting merges_mutations_memory_usage_soft_limit was set to 31.33 GiB (62.65 GiB available * 0.50 merges_mutations_memory_usage_to_ram_ratio)
2023.06.11 03:00:05.145645 [ 57408 ] {} <Warning> ParseRemoteDescription: Port is not found for host: mecagoenlos.com. Using default port 3306
2023.06.11 03:00:05.145810 [ 57408 ] {} <Warning> ParseRemoteDescription: Port is not found for host: localhost. Using default port 3306
2023.06.11 03:00:05.154144 [ 57157 ] {} <Error> Application: Caught exception while loading metadata: Code: 46. DB::Exception: Unknown function embeddingsprueba: While processing _CAST(embeddingsprueba(texto) AS embedido_tmp_alter1112821177341622878, 'Array(Float32)') AS embedido: default expression and column type are incompatible.: Cannot attach table `default`.`yttable` from metadata file /var/lib/clickhouse/store/94a/94a90c24-690b-401a-9716-8027d5875ef4/yttable.sql from query ATTACH TABLE default.yttable UUID '6484350d-aebf-403a-91c8-d94b45806e02' (`fecha` Date, `fichero` String, `texto` String, `linea` String, `duracion` Float32, `embedido` Array(Float32) DEFAULT embeddingsprueba(texto)) ENGINE = MergeTree ORDER BY fecha SETTINGS index_granularity = 8192. (UNKNOWN_FUNCTION), Stack trace (when copying this message, always include the lines below)`

and I don't know how to resolve it

**Comment by Wachynaky** [comment]
Deleting /var/lib/clickhouse/store/94a/94a90c24-690b-401a-9716-8027d5875ef4/yttable3.sql and /var/lib/clickhouse/store/94a/94a90c24-690b-401a-9716-8027d5875ef4/yttable.sql works, but I'm not sure if it's the correct way to solve the problem

**Comment by den-crane** [comment]
see 
 * https://github.com/ClickHouse/ClickHouse/issues/41327
 * https://github.com/ClickHouse/ClickHouse/pull/43539

You need to recreate the table.
