### ISSUE TITLE
Send trace logs returned with query result in structured format

### ISSUE THREAD

**Issue by markandpathak** [ClickHouse/ClickHouse#50842]
### Discussed in https://github.com/ClickHouse/ClickHouse/discussions/50762

**Use case**
We plan to use Clickhouse Cloud in our upcoming product. In our case number of users will be querying our database. For each query we would like to meter the amount of RAM used and execution time and charge users for their usage. For that purpose we need query log data.  Apart from that we also need these metrics for performance monitoring purposes. But as per current scenario we need to poll the `query_log` system table for each query ID. 

If I enable setting `send_logs_level = trace` while executing query, it does return logs, it contains all the required information like execution time, peak memory usage, bytes read etc. The only problem is that this data is unstructured. If same data is provided in structured manner so that end application can directly parse the logs that can be very helpful. Application can directly meter the usage or directly report metrics to monitoring service like Prometheus.

**Describe the solution you'd like**

Clickhouse already generates all metrics, it is returned in logs just in unstructured manner & it is inserted in `query_log` table. I just propose to send logs in structured manner for `send_logs_level` setting. It can be JSON or can be any other structured format with all metrics in standard format (bytes, millisecond etc) which can be easily parsed by end application.

We can introduce a setting `send_logs_format` to control the log format

For example If we consider clickhouse-go client, I propose that interface should be like:
```go
ctx := clickhouse.Context(context.Background(), clickhouse.WithProgress(func(p *clickhouse.Progress) {
    fmt.Println("progress: ", p)
    totalRows += p.Rows
}), clickhouse.WithProfileInfo(func(p *clickhouse.ProfileInfo) {
    fmt.Println("profile info: ", p)
}), clickhouse.WithLogs(func(log *clickhouse.Log) {
    fmt.Println("Peak memory: ", log.PeakMemoryBytes)
    fmt.Println("Execution Time: ", log.ExecutionTimems)
    // Export log data to Prometheus endpoint
    // Run some metering task 
}))

```

**Describe alternatives you've considered**

Current alternative is to log the query ID/Pass the queryID for each executed query, store it along with other data like user ID for which query was invoked. Run a separate service which processes these stored queryIDs in batches and aggregate all the data from `query_log` table.  This can do the trick but it's not much efficient or scalable. Proposed solution enables user to process the metrics at the point of request itself.

**Additional context**

I've just learned Clickhouse, from the responses from slack community and github discussion, I proposed a solution. Let me know if there are any alternative ways to achieve the same but I might not be aware about.

**Comment by alexey-milovidov** [comment]
ClickHouse native protocol provides metrics in a structured format during query execution: https://clickhouse.com/docs/en/native-protocol/server#profile-events

**Comment by markandpathak** [comment]
@alexey-milovidov Thank you for the clarification. I'll look into the profile events returned with the query. I'll post if I run into some issue
