### ISSUE TITLE
Collect logs for the system.text_log table even before it is initialized, to record the server startup.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#50843]
**Use case**

I want to count on the system.text_log table for logs.
That's why I need all the logs there.

**Describe the solution you'd like**

Initialize the queue earlier and let it buffer the events before table initialization.

**Comment by kardymonds** [comment]
Please assign to me

**Comment by alexey-milovidov** [comment]
Thank you! This will be very appreciated!
