### ISSUE TITLE
Clickouse server on RPI4 (ARM64)

### ISSUE THREAD

**Issue by robertonav20** [ClickHouse/ClickHouse#50852]
**I have tried the following solutions**: https://github.com/uptrace/helm-charts

**Installation type**
Helm pull the image 22.10 but i try the latest tag [23.5.2.7-alpine](https://hub.docker.com/layers/clickhouse/clickhouse-server/23.5.2.7-alpine/images/sha256-6889ed0bd4205bd32ebff95d43a511becc3c1a02229f8a391ede870beb13df36?context=explore)

Here my linux version
[pi@raspberry ~]$ uname -a
Linux raspberry.node.home 5.15.78-1-MANJARO-ARM-RPI #1 SMP PREEMPT Sat Nov 12 17:13:38 UTC 2022 aarch64 GNU/Linux

**Expected result**

I expect the container start successfully

**The actual result**
The version 22.10 i got this logs
```
/entrypoint.sh: line 40:    23 Illegal instruction     (core dumped) clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key='storage_configuration.disks.*.path'
/entrypoint.sh: line 41:    25 Illegal instruction     (core dumped) clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key='storage_configuration.disks.*.metadata_path'
```

Meanwhile with the 23.5.2.7-alpine the container don't logs

**How to reproduce**

1. install k3s cluster on raspberry pi4 8gb
2. install helm
3.
```
repo add uptrace https://charts.uptrace.dev
helm repo update uptrace
helm install -n uptrace --create-namespace my-uptrace uptrace/uptrace
```

**Comment by alexey-milovidov** [comment]
Install as a single binary:
```
curl https://clickhouse.com/ | sh
```

Do not use Docker, Helm, or Kubernetes.

**Comment by alexey-milovidov** [comment]
If you want to use containers, create a regular Ubuntu container, and install ClickHouse there.

**Comment by robertonav20** [comment]
Thank you for your reply, but I need to deploy it in a container inside the kubernetes cluster.
Do you support this situation?

**Comment by den-crane** [comment]
> Thank you for your reply, but I need to deploy it in a container inside the kubernetes cluster. Do you support this situation?

It's very easy, create a container with ubuntu copy CH binary into this container, commit container as image and publish the new image into dockerhub or your own docker registry.

**Comment by robertonav20** [comment]
Ok thanks for the guide, but I don't understand because the docker image tagged with arm64 doesn't work

**Comment by rschu1ze** [comment]
Raspberry Pi 4 has a Broadcom BCM2711 CPU which contains 4x [ARM Cortex-A72](https://en.wikipedia.org/wiki/ARM_Cortex-A72) cores and implements the ARMv8-A feature level. ClickHouse requires at least feature level [ARMv8.2-A](https://en.wikipedia.org/wiki/AArch64#ARMv8.2-A), see also [here](https://github.com/ClickHouse/ClickHouse/blob/ac7caace8a9caa556824588d209652fef07e6260/cmake/cpu_features.cmake#L20).

I guess the [description at DockerHub](https://hub.docker.com/r/clickhouse/clickhouse-server) should include a note.

As a workaround, you may either (1) [compile ClickHouse](https://clickhouse.com/docs/en/development/build) by yourself with CMake option `-DNO_ARMV81_OR_HIGHER=1`, or (2) get a pre-build binary for ARMv8.0 ("compatibility build", see [here](https://clickhouse.com/docs/en/install#install-a-ci-generated-binary), the process is a bit ugly though and such binaries are not tested in CI, hence not recommended for production usage), or (3) use the one-click installer mentioned [above](https://github.com/ClickHouse/ClickHouse/issues/50852#issuecomment-1586133975) - it picks the right ARM binary for the current platform and copy it into the container as @den-crane suggested.

**Comment by alexey-milovidov** [comment]
@rschu1ze, when you do

```
curl https://clickhouse.com/ | sh
```

(the officially recommended installation method)
it downloads the proper version automatically.

**Comment by robertonav20** [comment]
So, if i understand correctly the current arm64 image don't support rpi4 because the hardware is old and you suggest to create a custom image starting from ubuntu arm64 then install clickhouse and finally use it on kubernetes cluster, right?

**Comment by alexey-milovidov** [comment]
Yes, we have both builds in the form of binaries, but only one Docker image for servers, which requires newer instructions.

**Comment by rschu1ze** [comment]
> How to specify the version to download?

That's currently not possible. (To make it work, the user would need to specify the SHA hash or there would have to be a version-to-SHA mapping internally).

But in 99.99% of all cases, there is no need to download a version other than `master`. For the remaining 0.01% of all situations you can use a docker image, see [here](https://clickhouse.com/docs/en/install#from-docker-image).

**Comment by LGDHuaOPER** [comment]
> > How to specify the version to download?
> 
> That's currently not possible. (To make it work, the user would need to specify the SHA hash or there would have to be a version-to-SHA mapping internally).
> 
> But in 99.99% of all cases, there is no need to download a version other than `master`. For the remaining 0.01% you can use a docker image, see [here](https://clickhouse.com/docs/en/install#from-docker-image).

Yes, you are right. But I need to build one image at AArch64 Architecture, and I need to use v23.10, but now `curl https://clickhouse.com/ | sh` download v24.1. I don't know what to do now.

**Comment by rschu1ze** [comment]
I guess you like to run `curl https://clickhouse.com/ | sh` inside `docker build`.
I see two alternatives:
- download the v23.10 ARM artifacts from https://github.com/ClickHouse/ClickHouse/releases and include them into the image
- if you need more control, you could also do a build by yourself: https://clickhouse.com/docs/en/development/developer-instruction (just checkout the v23.10 tag).

**Comment by LGDHuaOPER** [comment]
> I guess you like to run `curl https://clickhouse.com/ | sh` inside `docker build`. I see two alternatives:
> 
> * download the v23.10 ARM artifacts from https://github.com/ClickHouse/ClickHouse/releases and include them into the image
> * if you need more control, you could also do a build by yourself: https://clickhouse.com/docs/en/development/developer-instruction (just checkout the v23.10 tag).

OK. I will choose No.1. But I have some questions. Does this approach require manual preparation? For example, prepare clickhouse user groups, create necessary directories(/var/lib/clickhouse, /var/log/clickhouse-server), etc.

**Comment by rschu1ze** [comment]
I just see that the [install docs](https://clickhouse.com/docs/en/install#from-tgz-archives) also have a section on installing from tarballs. There are tarballs for LTS and normal releases, including 23.10. If you follow the instructions (i.e. call `doinst.sh`), you should be good.

**Comment by alexey-milovidov** [comment]
@LGDHuaOPER, you can run the version 24.1 and imagine that it is 23.10.

**Comment by marshallm94** [comment]
I realize I'm commenting on a ~ year-old issue, but I'm in a similar situation (wanting to run ClickHouse on a Raspberry Pi 4); this is obviously a pretty vague question, but - **what is the speedup I could expect using ClickHouse (on a Pi) vs PostgresSQL?**

I have a table with ~140 million records, and a simple `GROUP BY` took 1 hour 15 minutes with MariaDB, and that same query took ~30 minutes with PostgresSQL 11.

In order to run ClickHouse on my Pi, I would have to get a new SD card, download a 64 bit OS, transfer everything over, etc. -so I'm trying to get a sense of whether all that work is only going to get me a ~5-10 minute improvement on the query, or if I could expect something better.

Thanks in advance to anyone that answers

**Comment by rschu1ze** [comment]
> but do you think the potential improvement is proportional to these results?

Yes. A major use case of ClickHouse are single-table aggregations, I'd expect comparable speedups on Raspberry Pi as on your Mac.

**Comment by marshallm94** [comment]
> > but do you think the potential improvement is proportional to these results?
> 
> Yes. A major use case of ClickHouse are single-table aggregations, I'd expect comparable speedups on Raspberry Pi as on your Mac.

Beautiful - thanks for replying; was completely expecting that comment to go into the abyss

**Comment by rschu1ze** [comment]
Btw., I can recommend the "community Slack" (see [here](https://github.com/ClickHouse/ClickHouse)) which is a quite active public forum around ClickHouse questions.

**Comment by marshallm94** [comment]
On the off chance that someone ends up here from google, wondering if it is worth the effort to change their OS in order to install ClickHouse, here is a comparison of what I experienced; same hardware, 2 different OS', 3 different DBMS on one dataset:

- Hardware: Raspberry Pi 4:
  - query: `SELECT TradeDate, Symbol, AVG(Volume) from Intraday group by 1,2;`:
  - dataset size: ~ 150 million records.
    - OS: 32-bit Raspian OS:
      - query duration on postgresql 11: `Time: 1922298.531 ms (32:02.299)`
      - query duration on mariadb 10.3: `749416 rows in set (1 hour 17 min 24.771 sec)`
      - query duration on clickhouse: **NA**
        - clickhouse only supports postgres >= 12.
    - OS: 64-bit Ubuntu 24.04.1 LTS:
      - query duration on postgres 16: `Time: 1317791.897 ms (21:57.792)`
      - query duration on mariadb 10.11: `754195 rows in set (2 hours 23 min 10.757 sec)`
      - query duration on ClickHouse 24.10.1.1088: **4.34 minutes**
        - `775629 rows in set. Elapsed: 260.530 sec. Processed 150.05 million rows, 3.41 GB (575.95 thousand rows/s., 13.08 MB/s.)`

**Comment by lvntbkdmr** [comment]
I've managed to install Plausible CE with Clickhouse on RPI4. You can follow the instructions [here](https://github.com/lvntbkdmr/plausible-rpi).
