### ISSUE TITLE
AWS S3 permissions needed

### ISSUE THREAD

**Issue by CaueP** [ClickHouse/ClickHouse#50898]
What are the needed [AWS S3 permissions](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html) to properly integrate S3 as storage (cold storage) with ClickHouse?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/integrations/s3#configuring-s3-for-clickhouse-use

```
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::mars-doc-test",
                "arn:aws:s3:::mars-doc-test/*"
```
