### ISSUE TITLE
clickhouse-keeper-client binary missing

### ISSUE THREAD

**Issue by stephenmcrowe** [ClickHouse/ClickHouse#50895]
**Describe the issue**

According to [the changelog](https://clickhouse.com/docs/en/whats-new/changelog), the [native keeper client](https://github.com/ClickHouse/ClickHouse/pull/47414) `clickhouse-keeper-client` binary should be available with the latest release. However, when I search for the binary within [the releases page](https://github.com/ClickHouse/ClickHouse/releases) in either 23.5.2.7-stable or 23.5.1.3174-stable, it's not there. I am interested in using the native client. Could you please add it and/or update the documentation?

**Comment by alexey-milovidov** [comment]
There is no symlink, but you can run it as
```
clickhouse keeper-client
```

(with whitespace instead of `-`)

**Comment by stephenmcrowe** [comment]
Ah, I've been running it as lightweight as possible, using just the [clickhouse keeper docker images](https://registry.hub.docker.com/r/clickhouse/clickhouse-keeper/tags). Would you be able to symlink it there, or do I need to switch to using the clickhouse server image?

**Comment by pufit** [comment]
> Ah, I've been running it as lightweight as possible, using just the [clickhouse keeper docker images](https://registry.hub.docker.com/r/clickhouse/clickhouse-keeper/tags). Would you be able to symlink it there, or do I need to switch to using the clickhouse server image?

Yes, we will add keeper-client to the keeper standalone binary!

**Comment by pufit** [comment]
https://github.com/ClickHouse/ClickHouse/pull/50964 was merged, so `clickhouse-keeper client` will be available after the next release!
