### ISSUE TITLE
Info about frozen parts in system.parts table.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5090]
Available in `is_frozen UInt8` column in `system.parts`.

For implementation: add a field `bool is_frozen` to `MergeTreeDataPart`. When part was frozen at runtime, set this field. At the server startup, check access of `columns.txt` or something like that. If it is non-writeable, the data part is frozen.

For Yandex.Cloud.

**Comment by proller** [comment]
https://github.com/yandex/ClickHouse/pull/5471
