### ISSUE TITLE
DB::Exception: Unknown table function azureBlobStorage: or incorrect parameterized view

### ISSUE THREAD

**Issue by devMarlee** [ClickHouse/ClickHouse#50959]
I tried using the azureBlobStorage function from the Release v23.5.2.7-stable, however, the function does not seem to work.

Machine: Macbook Pro M1 (ARM)
Docker image: clickhouse/clickhouse-server:23.5.2.7

Query that I am making through the client:

`SELECT * FROM azureBlobStorage('https://myAccount.blob.core.windows.net', 'testdir', '/somePath/somename.snappy.parquet', 'myAccount', 'myAccountKey', 'Parquet', 'auto', 'Column_1 String') `

Is there something I am missing?

**Comment by devMarlee** [comment]
@alesapin

**Comment by gingerwizard** [comment]
@SmitaRKulkarni this is reproducible on latest i.e. `curl https://clickhouse.com/ | sh`

**Comment by alexey-milovidov** [comment]
The integration with Azure is only supported on Linux machines, not on Mac.
