### ISSUE TITLE
Types of column 1 in section IN don't match: UInt32 on the left (INDEX scan)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#50956]
**Describe the issue**
IN set doesn't do automatic type casting

**How to reproduce**

```
CREATE TABLE tst_in (key UInt32) ENGINE=MergeTree ORDER BY key AS SELECT number FROM numbers(1000000);

SELECT count()
FROM tst_in
WHERE key IN (
    SELECT number
    FROM numbers(1000)
);


Received exception from server (version 23.6.1):
Code: 53. DB::Exception: Received from localhost:9000. DB::Exception: Types of column 1 in section IN don't match: UInt32 on the left, UInt64 on the right. (TYPE_MISMATCH)
(query: SELECT count()
FROM tst_in
WHERE key IN (
    SELECT number
    FROM numbers(1000)
);)


If we disable index analysis it does work

SELECT count()
FROM tst_in
WHERE identity(key IN (
    SELECT number
    FROM numbers(1000)
));

1000


```

23.6
https://fiddle.clickhouse.com/da1d7790-2140-49bf-a502-d77d1238239f

23.4
https://fiddle.clickhouse.com/28617010-1c3e-4af0-a53a-d000f0d92003

**Comment by canhld94** [comment]
@UnamedRus in your opinion, should we cast set elements to `UInt32` or cast `key` to `UInt64`?

A related MR #50078 solves a different  issue, but with a little effort can solve this issue as well.

**Comment by UnamedRus** [comment]
> @UnamedRus in your opinion, should we cast set elements to UInt32 or cast key to UInt64?

We need to cast to most subtype, check discussion on similar problem with joins:

https://github.com/ClickHouse/ClickHouse/issues/21794#issuecomment-860880336

**Comment by SaltTan** [comment]
No exception in 23.6 https://fiddle.clickhouse.com/09057b64-bda6-46df-a2cc-163a211b937e

**Comment by Algunenano** [comment]
Most likely fixed in https://github.com/ClickHouse/ClickHouse/pull/49570
