### ISSUE TITLE
Lz4DeflatingWriteBuffer works with S3 incorrectly

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#50975]
Lz4DeflatingWriteBuffer writes compressed data directly to the working_buffer of below buffer bypassing write method.

Here Lz4DeflatingWriteBuffer checks if below buffer has enough space. Lz4DeflatingWriteBuffer makes _wrong_ assumption that calling `out->next();` increases the space. Actually that call do no-op if there is still some space left.

https://github.com/ClickHouse/ClickHouse/blob/e2d8299b232635210916fea3c18bf04351151aed/src/IO/Lz4DeflatingWriteBuffer.cpp#L63-L68

As a result Lz4DeflatingWriteBuffer ends up with exception (I added more details to the string):
```
2023.06.14 10:47:03.082967 [ 8 ] {INSERT_INTO_TABLE_FUNCTION_FAIL_UPLOAD_PART_lz4} <Error> TCPHandler: Code: 617. DB::Exception: LZ4 failed to encode stream. LZ4F version: 100, CodeName: ERROR_dstMaxSize_tooSmall, in_capacity: 1048497, out_capacity: 6, cur_buffer_size: 1048497, min_compressed_block_size: 9. (LZ4_ENCODER_FAILED), Stack trace (when copying this message, always include the lines below):
```

**Comment by CheSema** [comment]
After fix this the tests need to be updated: 
test_checking_s3_blobs_paranoid/test.py::test_upload_s3_fail_create_multi_part_upload
test_checking_s3_blobs_paranoid/test.py::test_upload_s3_fail_upload_part_when_multi_part_upload

**Comment by antonio2368** [comment]
> Actually that call do no-op if there is still some space left.

I don't understand this part. `next()` always does:
```cpp
        bytes += bytes_in_buffer;
        pos = working_buffer.begin();
```
Shouldn't that mean it flushes the data and resets the working buffer to full capacity?

**Comment by antonio2368** [comment]
It makes sense but it's a bit tricky and I expect more places doing the same mistake.
Maybe add a comment to `WriteBuffer::next` that it doesn't guarantee anything for the new capacity (it can be same or different from previous). In this PR seems okay https://github.com/ClickHouse/ClickHouse/pull/56938

**Comment by CheSema** [comment]
> It makes sense but it's a bit tricky and I expect more places doing the same mistake. Maybe add a comment to `WriteBuffer::next` that it doesn't guarantee anything for the new capacity (it can be same or different from previous). In this PR seems okay #56938

Our buffer's interface is vague. We do quite tricky things with it in oder to achieve one-copy cost on a stack of 2-4 such buffers.
I will add such comment for `WriteBuffer::next`.
