### ISSUE TITLE
Getting error while running `clickhouse client --password`

### ISSUE THREAD

**Issue by bhagya1101** [ClickHouse/ClickHouse#50971]
Getting this error whenever trying to run `clickhouse client --password` .
`ClickHouse client version 23.6.1.315 (official build).
Password for user (default): 
Connecting to localhost:9000 as user default.
TimeoutSetter: Can't reset timeouts: Poco::Exception. Code: 1000, e.code() = 22, Invalid argument, Stack trace (when copying this message, always include the lines below):

 (version 23.6.1.315 (official build))
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000). (NETWORK_ERROR)`

I am new to clickhouse, so i dont know how to solve this

**Comment by DerekChia** [comment]
Welcome to ClickHouse. Can you confirm that your server is running? You can check it with `clickhouse status` and should see something like this:

```
root@c2abf1b361f9:/# clickhouse status
Found pid = 1 in the list of running processes.
The process with pid = 1 is running.
```

**Comment by bhagya1101** [comment]
> Welcome to ClickHouse. Can you confirm that your server is running? You can check it with `clickhouse status` and should see something like this:
> 
> ```
> root@c2abf1b361f9:/# clickhouse status
> Found pid = 1 in the list of running processes.
> The process with pid = 1 is running.
> ```

Yeah its working and got the response as 
`/var/run/clickhouse-server/clickhouse-server.pid file exists and contains pid = 60210.
The process with pid = 60210 is running.`

**Comment by rschu1ze** [comment]
@bhagya1101 Does this happen only with `--password`? Could you try a simpler invocation, e.g. `clickhouse client --query "SELECT 1"`?

**Comment by rschu1ze** [comment]
And which OS are you running on?

**Comment by bhagya1101** [comment]
> @bhagya1101 Does this happen only with `--password`? Could you try a simpler invocation, e.g. `clickhouse client --query "SELECT 1"`?

I don't know why but when i ran it with same command again, it started.
Though, I didn't understand what's the problem but it's solved I guess.
Thanks

**Comment by bhagya1101** [comment]
> And which OS are you running on?

macOS

**Comment by devcrafter** [comment]
Checked on my MacBook https://pastila.nl/?046af54c/a5e3a2bce92c13e0716fbdde5e7491e3
```
System Software Overview:
  System Version:	macOS 13.4.1 (22F82)
  Kernel Version:	Darwin 22.5.0

Hardware Overview:
 Model Name:	MacBook Pro
 Model Identifier:	MacBookPro18,1
 Model Number:	Z14V001BPZE/A
 Chip:	Apple M1 Pro
 Total Number of Cores:	10 (8 performance and 2 efficiency)
 Memory:	32 GB
```
