### ISSUE TITLE
Version folding engine data merge issues

### ISSUE THREAD

**Issue by Zhangft-M** [ClickHouse/ClickHouse#50973]
When I use the version to collapse the tree, there are three pieces of data, all three data definitions have the same primary key, version and sign data with 1 have several fields NULL but not primary keys, when partitioning merge, version 1, sign -1 data is deleted, but the other two data are retained
for example 
（1,NULL,"aaaa",500,1,1）
（1,0,"aaaa",500,-1,1）
（1,0,"aaaa",1000,1,2）
After merging:
（1,NULL,"aaaa",500,1,1）
（1,0,"aaaa",1000,1,2）
the first value is Primary key

**Comment by den-crane** [comment]
Provide `show create table + insert`

**Comment by Zhangft-M** [comment]
Excuse me, I've found the cause, the primary key field is not unique when creating the table
