### ISSUE TITLE
clichouse-client search started to reset terminal tabs titles

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#50990]
I've upgraded to 23.3 from 22.8 and noticed when I exit from client ctrl-R search terminal tabs titles are cleaned.

```
echo -ne "\033]0;server 7\007"                   tab = [ server 7 ]

clickhouse-client
ctrl-R -> enter                                  tab = [ default ]
```

**Comment by alexey-milovidov** [comment]
What is the mechanics of tab titles, and how could they be changed?
I've never heard about it.

**Comment by den-crane** [comment]
@alexey-milovidov https://tldp.org/HOWTO/Xterm-Title-3.html

Do you use terminal with tabs? try `echo -ne "\033]0;server 7\007"`

**Comment by alexey-milovidov** [comment]
Does not change anything in Konsole.

**Comment by den-crane** [comment]
Konsole https://stackoverflow.com/a/21380108/11644308

**Comment by alexey-milovidov** [comment]
You should submit this report to "Skim" - a Rust library.
