### ISSUE TITLE
LWD + projection

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#50991]
Denny, [Jun 12, 2023 at 5:11:09 PM]:
I suggest to treat a part with _row_exists like a part without the materialized projection

Alexey Milovidov, [Jun 12, 2023 at 5:14:43 PM]:
Ignoring projections if the part has mutated rows. That's a good idea, we can do it under a setting.

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/50969
* https://github.com/ClickHouse/ClickHouse/issues/50891
* https://github.com/ClickHouse/ClickHouse/issues/50613

**Comment by UnamedRus** [comment]
The same could work for *ReplacingMergeTree tables, if we have more than 1 part in partition -> skip projection

**Comment by UnamedRus** [comment]
> With ReplacingMergeTree it is easier to re-calculate projection from the merged part for each merge (in the end of a merge), anyway this logic is already implemented for mutations (alter delete/update).

Problem that recalculation of projection doesn't solve problem when you have multiple parts in partition, and each part have it' own projection.

So it should be both, recalculation + calculate from raw data if > 0 parts

**Comment by den-crane** [comment]
Ah, you mean final queries?

**Comment by UnamedRus** [comment]
Yes

**Comment by KochetovNicolai** [comment]
+1 for the idea from @Algunenano, but I would like to modify it slightly.
I think that we should not allow returning an incorrect query result. So, if the LWD mask can't be applied to the projection, there is no reason to store it as well.

I would prefer to have only one (merge tree) setting (e.g. `lightweight_mutation_projection_mode`), which is applied for alter. Options are:

- `throw` (by default). Throw exception if there is any projection in table DDL. User should drop all the projections manually before running the query.
  - It would be cool to allow running mutation if all the affected parts have no projection. But it seems to be hard to implement, so let's skip it for now.
  - Later, we can allow writing LWD mask for some projections (sort which has all the required columns; aggregate with required columns in GB key)
- `drop`. Drop projection if we can't write LWD mask for it. (Initially, drop all the projections).
- `rebuild` (maybe later). Write LWD mask in the part, but rebuild the projection. Might be useful if projections are light.
- `fallback_to_heavy` (maybe later, needs a better name). Fallback to normal heavy mutation for parts with projections, write LWD for other parts. Probably, might be useful in rare case (a small number of parts with projection; the time of rebuilding the projections ~ the time of rewriting the part).

Technically, we can still have `ignore` for compatibility.

It is good to add some introspection to see which projections are affected.

As a first step, we can implement only `throw` and `drop` (and maybe `ignore`), without supporting LWD mask for projections.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/71089
