### ISSUE TITLE
Has problem when setting storage_policy

### ISSUE THREAD

**Issue by yehaotong** [ClickHouse/ClickHouse#50994]
this is my table 
 ```
CREATE TABLE s3.hot_cold_ttl_test
(
    `VendorID` UInt8,
    `VendorName` String,
    `origin_time` DateTime
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(origin_time)
ORDER BY origin_time
SETTINGS index_granularity = 8192, storage_policy = 'default'
```
and when I try 
` alter table s3.hot_cold_ttl_test modify SETTING storage_policy = 'logs_hot_cold'`
It has error:
Received exception from server (version 22.4.5):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: New storage policy contain disks which already contain data of a table with the same name. (LOGICAL_ERROR)
My storage config is :
```
<policies>
        <s3>
            <volumes>
            <main>
                <disk>s3</disk>
            </main>
            </volumes>
        </s3>
        <hot_cold>
            <volumes>
                <hot>
                    <disk>default</disk>
                </hot>
                <cold>
                    <disk>s3</disk>
                </cold>
            </volumes>
        </hot_cold>
        <logs_hot_cold>
            <volumes>
                <default>
                    <disk>default</disk>
                </default>
                <cold>
                    <disk>s3</disk>
                </cold>
            </volumes>
        </logs_hot_cold>
    </policies>
```

**Comment by den-crane** [comment]
22.4.5 is out of support. You need to upgrade to 23.5.



please provide 

```
select * from system.disks;

SELECT * FROM system.storage_policies;

select database, table, disk_name, partition, sum(rows),
   formatReadableSize(sum(bytes_on_disk)) size, count() part_count
from system.parts where table like '%hot_cold_ttl_test%' and active
group by database, table,disk_name, partition
order by partition;

```

**Comment by yehaotong** [comment]
> 22.4.5 is out of support. You need to upgrade to 23.5.
> 
> please provide
> 
> ```
> select * from system.disks;
> 
> SELECT * FROM system.storage_policies;
> 
> select database, table, disk_name, partition, sum(rows),
>    formatReadableSize(sum(bytes_on_disk)) size, count() part_count
> from system.parts where table like '%hot_cold_ttl_test%' and active
> group by database, table,disk_name, partition
> order by partition;
> ```

select * from system.disks:
─name────┬─path──────────────────────────┬───────────free_space─┬──────────total_space─┬─keep_free_space─┬─type──┬─cache_path───────────────────────────────┐
│ default │ /var/lib/clickhouse/          │         235851415552 │         499963174912 │               0 │ local │                                          │
│ s3      │ /var/lib/clickhouse/disks/s3/ │ 18446744073709551615 │ 18446744073709551615 │               0 │ s3    │ /var/lib/clickhouse/disks/s3/data_cache/ │
└─────────┴───────────────────────────────┴──────────────────────┴──────────────────────┴─────────────────┴───────┴──────────────────────────────────────────┘

SELECT * FROM system.storage_policies:
┌─policy_name───┬─volume_name─┬─volume_priority─┬─disks───────┬─volume_type─┬─max_data_part_size─┬─move_factor─┬─prefer_not_to_merge─┐
│ default       │ default     │               1 │ ['default'] │ JBOD        │                  0 │           0 │                   0 │
│ hot_cold      │ hot         │               1 │ ['default'] │ JBOD        │                  0 │         0.1 │                   0 │
│ hot_cold      │ cold        │               2 │ ['s3']      │ JBOD        │                  0 │         0.1 │                   0 │
│ logs_hot_cold │ default     │               1 │ ['default'] │ JBOD        │                  0 │         0.1 │                   0 │
│ logs_hot_cold │ cold        │               2 │ ['s3']      │ JBOD        │                  0 │         0.1 │                   0 │
│ s3            │ main        │               1 │ ['s3']      │ JBOD        │                  0 │           0 │                   0 │
└───────────────┴─────────────┴─────────────────┴─────────────┴─────────────┴────────────────────┴─────────────┴─────────────────────┘

select database, table, disk_name, partition, sum(rows),
                   formatReadableSize(sum(bytes_on_disk)) size, count() part_count
                from system.parts where table like '%hot_cold_ttl_test%' and active
                group by database, table,disk_name, partition
                order by partition:
0 rows in set. Elapsed: 0.046 sec.
