### ISSUE TITLE
AWS Auth can't parse credential file in 23.5

### ISSUE THREAD

**Issue by lazywei** [ClickHouse/ClickHouse#51003]
**Describe what's wrong**

We're using aws credential file for auth, and ClickHouse isn't able to parse it. It works in 23.4 but after upgrading to 23.5 we're seeing these logs

```
2023.06.14 17:30:34.078990 [ 519 ] {fa1bf02b-6a80-4178-970c-e75fe9a1193e} <Information> AWSClient: ProfileConfigFileAWSCredentialsProvider: Setting provider to read credentials from /.aws/credentials for credentials file and /root/.aws/config for the config file , for use with profile default
2023.06.14 17:30:34.079031 [ 519 ] {fa1bf02b-6a80-4178-970c-e75fe9a1193e} <Information> AWSClient: Aws::Config::ConfigFileProfileFSM: Unknown property: aws_access_key_id in the profile: default
2023.06.14 17:30:34.079040 [ 519 ] {fa1bf02b-6a80-4178-970c-e75fe9a1193e} <Information> AWSClient: Aws::Config::ConfigFileProfileFSM: Unknown property: aws_secret_access_key in the profile: default
2023.06.14 17:30:34.079045 [ 519 ] {fa1bf02b-6a80-4178-970c-e75fe9a1193e} <Information> AWSClient: Aws::Config::ConfigFileProfileFSM: Unknown property: aws_session_token in the profile: default
```

**Does it reproduce on recent release?**

On `ClickHouse server version 23.5.1 revision 54462`

**Enable crash reporting**

N/A

**How to reproduce**

* Version 23.5.1
* Ask CH to read the credential file by using the following Envs (force disable ec2 metadata and web identity token file)
```
AWS_DEFAULT_REGION=us-west-2
AWS_EC2_METADATA_DISABLED=true
AWS_REGION=us-west-2
AWS_SHARED_CREDENTIALS_FILE=/.aws/credentials
AWS_WEB_IDENTITY_TOKEN_FILE=""
```

**Expected behavior**

CH should be able to parse the credential file properly because it's working in previous version.

**Comment by antonio2368** [comment]
Based on my tests it does parse correctly the information from the credentials file but for some reason that log was added in the SDK. Because by default we print only up to `INFO` level from the AWS SDK you only see `Unknown property` message.
Also, the message seems wrong in general, I will take a look if AWS SDK needs to be patched.

Can you just verify that the keys do work when you define them in credentials file?
