### ISSUE TITLE
UDF functions from system.functions table is not replicated when starting a new node

### ISSUE THREAD

**Issue by xpolb01** [ClickHouse/ClickHouse#51030]
We have an issue where sometimes one of our Clickhouse nodes goes down and we need to bring in a new node, everything is being replicated as expected except those user-defined functions. To solve it we have to go through our migrations, gather those and execute them separately on the new node. What would be the best way to manage this? We are also using [clickhouse-operator](https://github.com/Altinity/clickhouse-operator) so not sure if this is something that has to be raised with them too

**How to reproduce**
1. Add UDFs to `system.functions` table
2. delete the pod with one of the replicas
3. On the new node there is not going to be UDS in the `system.functions` table

**Expected behavior**
I would expect UDFs to be present in the `system.functions` table

**Comment by UnamedRus** [comment]
UDF by default is stored on filesystem, so they are not replicated.

But you can enable ZK based storage for them
https://github.com/ClickHouse/ClickHouse/pull/46085
