### ISSUE TITLE
Change HTTP code for /replicas_status on the delayed replica

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#5104]
**Use case**
Either on fine and bad case `/replicas_status` answers with 200. For the load balancers which are able to recognize http code only, it's difficult to use this handler as a health check.

**Describe the solution you'd like**
Maybe one of the next codes could fit better:
```
412 Precondition Failed (RFC 7232)
    The server does not meet one of the preconditions that the requester put on the request.
416 Range Not Satisfiable (RFC 7233)
    The client has asked for a portion of the file (byte serving), but the server cannot supply that portion. For example, if the client asked for a part of the file that lies beyond the end of the file.[48] Called "Requested Range Not Satisfiable" previously.
425 Too Early (RFC 8470)
    Indicates that the server is unwilling to risk processing a request that might be replayed.
```

**Comment by alexey-milovidov** [comment]
It's a server-side error (not something depend on client), so 5xx code should be sent.
`503 Service Unavailable` looks reasonable.

**Comment by Melancholic** [comment]
See here #9126
