### ISSUE TITLE
Update memory_amount every time memory settings from config are changed.

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#51084]
https://github.com/ClickHouse/ClickHouse/blob/1cb7ba4895e0666eeba8654a45ec8c124b904864/programs/server/Server.cpp#L1116-L1140

Here is the code which updates `max_server_memory_usage` setting from config in runtime. However, this code does not update `memory_amount`. As a result, if cgroup limit was increased and setting `max_server_memory_usage` was changed, we still hit the limit `default_max_server_memory_usage =memory_amount * max_server_memory_usage_to_ram_ratio`.

Let's update `memory_amount` if `max_server_memory_usage` or `max_server_memory_usage_to_ram_ratio` was changed.

Note: if we decrease `max_server_memory_usage` first, and then change cgroup limit, check over `max_server_memory_usage_to_ram_ratio * (old) memory_amount` would be invalid. I think it's acceptable.

**Comment by kardymonds** [comment]
Please assign to me

**Comment by kardymonds** [comment]
@KochetovNicolai 
I suggest just  always update memory_amount (without detecting changing settings). 
The reasons:
- case: user changed `memory_amount` (cgroup) + did not change `max_server_memory_usage_to_ram_ratio`, user just want to update `default_max_server_memory_usage`;
- below in the function `memory_amount` is also used for update `default_merges_mutations_server_memory_usage`;
- there is no functionality to check if the parameter is updated (maybe add, but it is not clear why)
