### ISSUE TITLE
Executable UDF path w/ clickhouse-local

### ISSUE THREAD

**Issue by lmangani** [ClickHouse/ClickHouse#51089]
Related to ancient https://github.com/ClickHouse/ClickHouse/issues/31188

It currently seems pretty much impossible to run executable UDFs using `clickhouse-local`. As its now well known, modern clickhouse demands UDF scripts to reside in a [user_scripts_path](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server_configuration_parameters-user_scripts_path) and while this is simple with `clickhouse-server`, so far I could not find an equivalent SET parameter to convince `clickhouse-local` into using a custom user scripts folder location. On the other hand, the dynamic /tmp folder is impossible to use or guess.

Fictional example: 
```
SELECT * FROM executable('./some_script.py', TabSeparated, 'name String', (SELECT name));
```
```
DB::Exception: Executable file ./some_script.py does not exist inside user scripts folder /tmp/clickhouse-local-2818615-1686929524-9014242541746612907/user_scripts/. (UNSUPPORTED_METHOD)
```

UDF functions (`CREATE FUNCTION test AS x -> (x + 1);SELECT test(1);`) work fine in comparison.

Any suggestions?

**Comment by alexey-milovidov** [comment]
This is easy, we only have to provide the ability to change this path in the configuration,
and should it will be available as `clickhouse-local ... -- --user_scripts_path`.
plus allow it by default for better usability.
