### ISSUE TITLE
Unable to connect to HDFS: HdfsRpcException: RPC channel to "ip:port" got protocol mismatch

### ISSUE THREAD

**Issue by yusiwen123** [ClickHouse/ClickHouse#51080]
#### Describe the unexpected behaviour

I want to use HDFS engine on Clickhouse, But an error occurred when I query:
Unable to connect to HDFS: HdfsRpcException: RPC channel to "ip:port" got protocol mismatch: RPC channel cannot find pending call: id = -33.. (NETWORK_ERROR)

#### How to reproduce

- Which ClickHouse server version to use:

```
22.10.2.11
```
- config.xml :
```
 <hadoop_kerberos_keytab>/etc/keytab/test.keytab</hadoop_kerberos_keytab>
 <hadoop_kerberos_principal>test@TEST</hadoop_kerberos_principal>
 <hadoop_security_authentication>kerberos</hadoop_security_authentication>
 <libhdfs3_conf>/etc/clickhouse-server/hdfs-client.xml</libhdfs3_conf>
```
- query: 
```
SELECT *
FROM hdfs('hdfs://ip:port/data/, 'TSV', 'column1 String, column2 String')
LIMIT 2;
```

- comment:
I noticed that in the core-site.xml configuration file of my Hadoop 3.2.0 environment, the "hadoop.rpc.protection" setting is configured as "authentication+privacy," but I don't really understand what it means. Additionally, my hdfs-client.xml is also configured with Kerberos and HA.

**Comment by santrancisco** [comment]
Related to this issue - https://github.com/ClickHouse/ClickHouse/issues/22236  and I see you already asked a question there. 

> I noticed that in the core-site.xml configuration file of my Hadoop 3.2.0 environment, the "hadoop.rpc.protection" setting is configured as "authentication+privacy," but I don't really understand what it means. 

Another ClickHouse user explained the error message you're receiving here (RPC id -33) https://github.com/ClickHouse/ClickHouse/pull/16621#issuecomment-808635139 so I think you're looking at the right spot. 

I'm not familiar with Hadoop but i would suggest trying different version of clickhouse - maybe latest to see if that config works? ALso just to rule out the issue being anything else, you could try temporary set hadoop.rpc.protection to just authentication only and see if your Hadoop setting is correct?
