### ISSUE TITLE
clickhouse build-in metric 'ClickHouseMetrics_PartMutation' is always zero

### ISSUE THREAD

**Issue by wuguowei1994** [ClickHouse/ClickHouse#51144]
**ClickHouseMetrics_PartMutation is clickhouse build-in metric, we need to use it to monitor our cluster. But this metric is always zero although we executed ALTER command.**

![alter is done](https://github.com/ClickHouse/ClickHouse/assets/20394628/1843be48-e558-48e3-a08e-25fc56a4b19e)

In picture above, our mutation is finish. But ClickHouseMetrics_PartMutation is always zero in the last 30 minutes...

Server version:
ClickHouse server version 22.13.1 revision 54461.

Client version:
ClickHouse client version 22.13.1.1278

**Comment by tavplubix** [comment]
PartMutation metric shows the number of currently executing part mutations (kind of equivalent to `select count() from system.merges where is_mutation=1`)

> version 22.13.1.1278

It's a very old testing version (nightly build). Please use one of the supported stable versions: https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease
