### ISSUE TITLE
Disk types not listed

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#51166]
Looking at https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-multiple-volumes_configure there are no docs on the full list of supported `type`s. I know there is `s3` from the S3 docs, and there seem to also be `web` and `cache` based on examples of nested dynamic storage, but it would be very helpful to know the list of types and how to use them.

**Comment by DanRoscigno** [comment]
Thanks @danthegoodman1 .  I looked through the CI tests and this is the list:

- azure_blob_storage
- cache
- encrypted
- hdfs
- local
- local_blob_storage
- s3
- s3_plain
- web

Note that I have not gone beyond grepping and sorting, and I may have an error or two.  I will have a closer look.

**Comment by DanRoscigno** [comment]
(and s3 is S3, MinIO, GCS, etc.)
