### ISSUE TITLE
A function `firstLine` to extract the first line from a multi-line string

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#51172]
**Describe alternatives you've considered**

```
extract(s, '^[^\r\n]+')
```

**Comment by infdahai** [comment]
I'd like to take this task.

**Comment by ucasfl** [comment]
> I'd like to take this task. And can I ask where is the function placed on?

It can be a new function under `src/Functions/`.

**Comment by mkmkme** [comment]
Hey @infdahai! Are you working on this task? If not, I'd like to take it instead.

**Comment by alexey-milovidov** [comment]
@mkmkme Thank you! Reassigned...
