### ISSUE TITLE
AST fuzzer issue `Logical error: 'Trying create stream to read to mark №0 but total marks count is 2'.`

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#51181]
(you don't have to strictly follow this form)

**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/51163/662152dddc1280023ba04956f6f0d0c2d2b96785/fuzzer_astfuzzerasan/report.html

**How to reproduce**
Not sure if it's connected to updated images https://s3.amazonaws.com/clickhouse-test-reports/51180/662152dddc1280023ba04956f6f0d0c2d2b96785/ci_running.html

**Comment by Algunenano** [comment]
Report is gone
