### ISSUE TITLE
Wrong lambda caching

### ISSUE THREAD

**Issue by bogoslovskiy** [ClickHouse/ClickHouse#51184]
Environment:
clickhouse/clickhouse-server:23.3.4.17 (docker)

I would like to get subsequences from a general sequence as array of arrays. Splitting to subsequences by timestamps in the general sequence.

For example, general sequence is:
['2023-06-19 08:30:00', '2023-06-19 08:31:00', '2023-06-19 08:34:00', '2023-06-19 08:35:00', '2023-06-19 09:30:00', '2023-06-19 09:31:00', '2023-06-19 10:47:00', '2023-06-19 10:48:00', '2023-06-19 10:58:00', '2023-06-19 11:40:00']

SQL:
``` sql
SELECT 
    ['2023-06-19 08:30:00', '2023-06-19 08:31:00', '2023-06-19 08:34:00', '2023-06-19 08:35:00', -- first sequence, break at 1
    '2023-06-19 09:30:00', '2023-06-19 09:31:00', -- next sequence, break at 5
    '2023-06-19 10:47:00', '2023-06-19 10:48:00', -- next sequence, break at 7
    '2023-06-19 10:58:00', -- next sequence, break at 9
    '2023-06-19 11:40:00'] -- next sequence, break at 10
    AS Source,
    arrayFilter(
        i -> i = 1 OR date_diff('minute', toDateTime(Source[i - 1]), toDateTime(Source[i])) >= 10,
        arrayEnumerate(Source)) AS Breaks,
    arrayMap(
        bi -> (bi, arraySlice(Source, Breaks[bi], bi < length(Breaks) ? Breaks[bi + 1] - Breaks[bi] : NULL)),
        arrayEnumerate(Breaks)) AS Groups;
```

Result:
Breaks: [1, 5, 7, 9, 10]
Groups: [('1', ['2023-06-19 08:30:00', '2023-06-19 08:31:00', '2023-06-19 08:34:00', '2023-06-19 08:35:00']), ('2', ['2023-06-19 10:47:00', '2023-06-19 10:48:00']), ('3', ['2023-06-19 10:47:00', '2023-06-19 10:48:00']), ('4', ['2023-06-19 11:40:00']), ('5', ['2023-06-19 11:40:00'])]

For simple lambda:
``` sql
...
    arrayMap(
            bi -> (bi, arraySlice(Source, Breaks[bi], 1)),
            arrayEnumerate(Breaks)) AS Groups
```

Result:
Breaks: [1, 5, 7, 9, 10]
Groups: [('1', ['2023-06-19 11:40:00']), ('2', ['2023-06-19 11:40:00']), ('3', ['2023-06-19 11:40:00']), ('4', ['2023-06-19 11:40:00']), ('5', ['2023-06-19 11:40:00'])]

Looks like wrong arraySlice function caching inside the lambda. Wrong because of some arguments of function inside the lambda are not a const and have various values, that affect the result.

Is there some workaround?
Thank you!

**Comment by den-crane** [comment]
1. I cannot reproduce the issue. https://fiddle.clickhouse.com/ba4da3fb-a274-4493-b70e-1e4073a43d6e https://fiddle.clickhouse.com/df16b9c2-5f79-4998-af97-09a1d2594663
2. Do not reuse lambda variable names if you are. 

3. Check arrayDifference, arraySplit https://fiddle.clickhouse.com/caf4d52c-6e9b-4905-8b8c-6abf3ed55d9c

Avoid arrayEnumerate as much as possible, when you pass an Array into lambda, you are making the copy of the array and amplify the memory usage.

**Comment by bogoslovskiy** [comment]
> 1. I cannot reproduce the issue. https://fiddle.clickhouse.com/2bf301f8-9148-4aeb-9b06-c5c8b50f8a11 https://fiddle.clickhouse.com/a6c9af83-d84e-438f-9ced-ffcfc6f3a017
It is my mistake. I have seen your example with "format Vertical" and have tried it. Have got valid result. Then have tried query via clickhouse-client and have got valid result too. Error reproduces in the Rider (DataGrip) with ClickHouse driver 0.4.2, in horizontal default format. So, I will try to find possibility to report them about it.
> 2. Do not reuse lambda variable names if you are.  High-order functions can grasp a lambda variable from another function (it's a bug, it was fixed in the new experimental analyzer).
> 3. Check arrayDifference, arraySplit https://fiddle.clickhouse.com/caf4d52c-6e9b-4905-8b8c-6abf3ed55d9c
> 
> Avoid arrayEnumerate as much as possible, when you pass an Array into lambda, you are making the copy of the array and amplify the memory usage.
Thank you for your attention! And sorry me, you have wasted your time.

Issue closed. There is nothing to fix.

**Comment by TomAndersen0714** [comment]
Try to avoid using Arrays in Lambda Expressions, which can multiply the memory overhead. 

```
(21.8.14.5)

create table X(A Array(String)) engine = Memory;

insert into X select arrayMap(x->toString (x) , range(1, 1001)) from numbers(50);

select arrayFilter(x->x='666', A) from X format Null;
-- Peak memory usage (for query): 0.00 B.

select arrayFilter((x, y)->A[y]='666', A, arrayEnumerate(A)) from X format Null;
-- Peak memory usage (for query): 1.00 GiB.

select arrayFilter((v, k)-> k = 666, A, keys) from (select A, arrayEnumerate(A) as keys from X) format Null;
-- Peak memory usage (for query): 0.00 B.
```
