### ISSUE TITLE
RPM Packages are not signed

### ISSUE THREAD

**Issue by reyjrar** [ClickHouse/ClickHouse#51202]
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

Disabling GPG Checks for packages provided by third parties is not good form.

**Installation type**

RPM Packages

**Source of the ClickHouse**

[Clickhouse YUM Repository](https://packages.clickhouse.com/rpm/clickhouse.repo)

**Expected result**

Signed packages.

**The actual result**

Unsigned Packages.

```
Package clickhouse-client-23.5.3.24.x86_64.rpm is not signed
```

**How to reproduce**

We require signed packages from all our upstream repositories. I know the repo_md is signed, but the packages are no longer signed.  They used to be signed when distributed via `rpm.clickhouse.tech`.

```
rpm -qi -p clickhouse-server-22.2.2.1-2.noarch.rpm
warning: clickhouse-server-22.2.2.1-2.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID e0c56bd4: NOKEY
Name        : clickhouse-server
Version     : 22.2.2.1
Release     : 2
Architecture: noarch
Install Date: (not installed)
Group       : Converted/database
Size        : 105221
License     : see /usr/share/doc/clickhouse-server/copyright
Signature   : RSA/SHA1, Thu 17 Feb 2022 02:47:30 PM UTC, Key ID c8f1e19fe0c56bd4
Source RPM  : clickhouse-server-22.2.2.1-2.src.rpm
Build Date  : Thu 17 Feb 2022 11:05:03 AM UTC
Build Host  : ip-172-31-18-106.ec2.internal
Relocations : (not relocatable)
Summary     : Server binary for ClickHouse
Description :
ClickHouse is a column-oriented database management system
that allows generating analytical data reports in real time.

This package provides clickhouse common configuration files


(Converted from a deb package by alien version 8.95.)
```

This is the first time we've encountered an upstream which failed to sign the packages.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/41968

**Comment by reyjrar** [comment]
So, the last comment on the closed ticket you referenced is exactly my concern and you closed my ticket

Do you know how infuriating that this? Seriously, FFS, you are the only upstream not signing RPMs in my list of 25 upstreams.

**Comment by den-crane** [comment]
I closed this issue because it is an exact duplicate, and it's my duty to close duplicates.

I happen to be facing the same problem as you by pure coincidence. However, I comprehend the reasoning behind Clickhouse,inc.'s decisions and hold it in high regard. I don't possess any entitlement to make demands regarding an open-source product. My only prerogative is to contribute in any way I can.
