### ISSUE TITLE
Sign Your RPMs So They Can Be Verified

### ISSUE THREAD

**Issue by reyjrar** [ClickHouse/ClickHouse#51206]
I just had an issue closed referencing a closed issue which **did not solve or address the issue**.

Here's the rub.

You sign the metadata, you don't sign the packages.

This means, I can validate the metadata, but when I mirror your repository, I have to regenerate the metadata.

So, now the only host that can verify the validity of the packages is the host pulling the mirrors directly.

This is not sufficient to validate the integrity of the package at install time.

**Internal policies require we only use GPG signed packages from upstreams.** Without signed packages, I have to discard Clickhouse from my infrastructure because I do not have the time to manage my own builds.

**Installation type**

RPM Packages

**Source of the ClickHouse**

RPM Mirrors

**Expected result**

Signed packages so they can be validated on the hosts which are installing them.

**The actual result**

Signed metadata, unsigned packages. This means the end-points cannot validate the packages since we use a mirroring scheme because none of our production infrastructure has direct access to the internet.

**How to reproduce**

1. Search for an open issue in the issues, find none
2. Open a new issue stating, "hey, this is broken"
3. Watch an issue get closed without resolution referencing an issue that also did not get resolved and did not address the concern raised.
4. Debate your hold on reality

Please, follow best practices and sign **BOTH** the packages and the metadata.  I know you can do it. You were doing it just fine before migrating to `packages.clickhouse.com`.

**Comment by den-crane** [comment]
https://clickhouse.com/support/program


-------
Disclaimer: I want to clarify that I am just an ordinary person on the Internet.
I have no connection or association with Clickhouse, Inc. or its development team.
It is important to note that my opinion holds no value and should not be considered.

**Comment by bkuschel** [comment]
Why only rpms? debs and Docker images can be signed as well... just sayin'

**Comment by UnamedRus** [comment]
If you don't need bleeding edge releases, you can check our builds in mean time, they should have signatures

https://builds.altinity.cloud/

**Comment by Felixoid** [comment]
@reyjrar what's wrong with `repocync --download-metadata`?

**Comment by Felixoid** [comment]
What is the issue with signing packages and images:

1. We have to download, assign and reupload the huge amount of data
2. We don't have a signing key on our builders, only on the repository management host
3. Having different packages in the repository and the build artifacts bucket stinks to me. And addressing the issue with security, when every builder has a key, stinks to me even worse.

If somebody has a solution to the states above rather than claims "just do it", I am open to discussion.

**Comment by reyjrar** [comment]
> @reyjrar what's wrong with `repocync --download-metadata`?
> 
> ```
> ~/ebs/experiment-mirror-rpm/lts/clickhouse-lts$ ls repodata/
> 312ebe2e8c3235414f98632ce52143b9ef9260e095ed66b956b35d5c1face133-other.sqlite.bz2
> 34674e0f9889abafae4761bee8ce2a8424743151ca36e0ec2abb2c598af73fe2-primary.xml.gz
> 7d48d79b93a2d26bcb911b4ab4bc41d5a86b5407c1f28aa71aa3ea424f94b889-filelists.xml.gz
> a3f6b013415af360108f27fa206ad3dac376d326f54c76bbd34654a326eafae7-primary.sqlite.bz2
> aff114c7853d75992e059538ad6054e2da49fa2ef3383dde7ff0169a58d5d0b4-filelists.sqlite.bz2
> e8b240cf7f669da84285a7330791eb08c9da5534e10dcd6bd40bdb09cf049344-other.xml.gz
> repomd.xml
> repomd.xml.asc
> ```
> 
> I got this directory with the following command:
> 
> ```
> reposync -p ~/ebs/experiment-mirror-rpm/lts --download-metadata --repo=clickhouse-lts
> ```

That's essentially what we do, but we use a date-versioned snapshot approach, which performs a metadata regeneration to ensure packages in the repository are all represented in the metadata.  There have been a few cases where upstreams delete older packages. By regenerating the metadata, we ensure the packages we have match the repodata at that point.  It's not perfect, but it does solve a lot of problems.

We are evaluating the plausibility of enabling `repo_gpgcheck`, downloading and verifying package checksums that way, and then signing any unsigned packages with our signing key so we can fill in the trust for the end-points themselves. The goal here is that all the packages are signed and we can audit systems for unsigned packages as security problem.

**Comment by reyjrar** [comment]
> What is the issue with signing packages and images:
> 
>     1. We have to download, assign and reupload the huge amount of data
> 
>     2. We don't have a signing key on our builders, only on the repository management host
> 
>     3. Having different packages in the repository and the build artifacts bucket stinks to me. And addressing the issue with security, when every builder has a key, stinks to me even worse.
> 
> 
> If somebody has a solution to the states above rather than claims "just do it", I am open to discussion.

For 2. You probably should not use the same key for the build system as the repo management system. You can publish multiple keys in the `gpgkey=` section of the yum/dnf.conf. Alternatively, you can publish a `gpgcakey=` which you use to issue keys for building and metadata creation.

For 3. With `gpgcakey=` each builder can have its own key, which may or may not be easier to work with? AFAIK, there's no CRL for yum/dnf keys, so adding more keys under a cakey might be problematic if you lose the private key. I might be mistaken about the CRL, it's possible GPG can solve that in some manner.

Either way, I think it's best to have 2 keys in this situation, one for building, one for metadata signing. That way there's no need to share the private key across two systems.

**Comment by Felixoid** [comment]
After taking it for a weekend, here is what I think.

Signing the RPM packages is a recommendation, and so far there are 3 persons in more than 1.5 years who explicitly complain about unsigned packages. For reference, here's the the first ticket about it #41968

One of my y main concerns is signing 1TB of packages in R2 storage. Whatever can go far south there. Signing in place requires the preparation of the infrastructure to have both:

- optional signing of the RPM packages with [nfpm](https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-client.yaml#L29), I know it supports ENV expansion
- working w/o any keys still for local builds
- having it securely. Once again, now our runners are accessible by developers. This is a blocker from my POV

And after a moment the list is addressed, one needs to regenerate a huge tone of existing RPM packages.

So, I am fine to have this issue opened. But I don't jump into it. The benefit of having the packages signed is pretty much neglectable compared to changing existing access requirements to our runners.
