### ISSUE TITLE
AST Fuzzer: Invalid number of rows in Chunk column Object position 2: expected 1, got 0

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#51204]
**Describe the bug**
[A link to the report](https://s3.amazonaws.com/clickhouse-test-reports/0/96b2908f419d3d85f1598df4fe4528e105044534/fuzzer_astfuzzerasan/report.html)

**How to reproduce**
```sql
SELECT '0.02' GROUP BY GROUPING SETS (('6553.6'), (CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')')))
```
Stack
```
2023.06.20 16:07:17.126948 [ 532 ] {b85bf966-e63a-4f6d-a719-9c58db2b59b7} <Fatal> : Logical error: 'Invalid number of rows in Chunk column Object position 2: expected 1, got 0'.
2023.06.20 16:07:17.127761 [ 537 ] {} <Fatal> BaseDaemon: ########################################
2023.06.20 16:07:17.127878 [ 537 ] {} <Fatal> BaseDaemon: (version 23.6.1.1 (official build), build id: B131DB96CDF9195C03C1AAB3E91FDFAF343467C5, git hash: 96b2908f419d3d85f1598df4fe4528e105044534) (from thread 532) (query_id: b85bf966-e63a-4f6d-a719-9c58db2b59b7) (query: SELECT '0.02' GROUP BY GROUPING SETS (('6553.6'), (CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')')))) Received signal Aborted (6)
2023.06.20 16:07:17.127969 [ 537 ] {} <Fatal> BaseDaemon: 
2023.06.20 16:07:17.128049 [ 537 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007fd6ce7ea00b 0x00007fd6ce7c9859 0x0000561ecabc0512 0x0000561ecabc13bd 0x0000561eb821ecdb 0x0000561ee218f38f 0x0000561ee290dca0 0x0000561ed366aa1e 0x0000561ee21b04cd 0x0000561ee21fd6ee 0x0000561ee21dfc45 0x0000561ee21e2782 0x0000561ecae69510 0x0000561ecae73bee 0x0000561ecae60b71 0x0000561ecae6d90d 0x00007fd6ce9a1609 0x00007fd6ce8c6133
2023.06.20 16:07:17.128152 [ 537 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x00007fd6ce7ea00b in ?
2023.06.20 16:07:17.128234 [ 537 ] {} <Fatal> BaseDaemon: 4. abort @ 0x00007fd6ce7c9859 in ?
2023.06.20 16:07:17.314505 [ 537 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:42: DB::abortOnFailedAssertion(String const&) @ 0x0000000024894512 in /workspace/clickhouse
2023.06.20 16:07:17.499298 [ 537 ] {} <Fatal> BaseDaemon: 6.1. inlined from ./build_docker/./src/Common/Exception.cpp:65: DB::handle_error_code(String const&, int, bool, std::vector<void*, std::allocator<void*>> const&)
2023.06.20 16:07:17.499428 [ 537 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:93: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000248953bd in /workspace/clickhouse
2023.06.20 16:07:27.303958 [ 537 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x0000000011ef2cdb in /workspace/clickhouse
2023.06.20 16:07:27.357832 [ 537 ] {} <Fatal> BaseDaemon: 8. ./build_docker/./src/Processors/Chunk.cpp:73: DB::Chunk::checkNumRowsIsConsistent() @ 0x000000003be6338f in /workspace/clickhouse
2023.06.20 16:07:27.417911 [ 537 ] {} <Fatal> BaseDaemon: 9.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:580: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::data[abi:v15000]() const
2023.06.20 16:07:27.418019 [ 537 ] {} <Fatal> BaseDaemon: 9.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:760: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::__annotate_delete[abi:v15000]() const
2023.06.20 16:07:27.418075 [ 537 ] {} <Fatal> BaseDaemon: 9.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:431: ~vector
2023.06.20 16:07:27.418119 [ 537 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:25: DB::ExpressionTransform::transform(DB::Chunk&) @ 0x000000003c5e1ca0 in /workspace/clickhouse
2023.06.20 16:07:27.569438 [ 537 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__utility/swap.h:35: std::enable_if<is_move_constructible<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value && is_move_assignable<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>::value, void>::type std::swap[abi:v15000]<COW<DB::IColumn>::immutable_ptr<DB::IColumn>*>(COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&, COW<DB::IColumn>::immutable_ptr<DB::IColumn>*&)
2023.06.20 16:07:27.569555 [ 537 ] {} <Fatal> BaseDaemon: 10.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/vector:1950: std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>::swap(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>>&)
2023.06.20 16:07:27.569613 [ 537 ] {} <Fatal> BaseDaemon: 10.3. inlined from ./build_docker/./src/Processors/Chunk.h:64: DB::Chunk::swap(DB::Chunk&)
2023.06.20 16:07:27.569658 [ 537 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Processors/ISimpleTransform.h:33: DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) @ 0x000000002d33ea1e in /workspace/clickhouse
2023.06.20 16:07:27.657666 [ 537 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Processors/ISimpleTransform.cpp:99: DB::ISimpleTransform::work() @ 0x000000003be844cd in /workspace/clickhouse
2023.06.20 16:07:27.687805 [ 537 ] {} <Fatal> BaseDaemon: 12.1. inlined from ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*)
2023.06.20 16:07:27.687890 [ 537 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:92: DB::ExecutionThreadContext::executeTask() @ 0x000000003bed16ee in /workspace/clickhouse
2023.06.20 16:07:27.801095 [ 537 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:255: DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000003beb3c45 in /workspace/clickhouse
2023.06.20 16:07:27.937597 [ 537 ] {} <Fatal> BaseDaemon: 14.1. inlined from ./build_docker/./src/Processors/Executors/PipelineExecutor.cpp:351: operator()
2023.06.20 16:07:27.937723 [ 537 ] {} <Fatal> BaseDaemon: 14.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394: decltype(std::declval<DB::PipelineExecutor::spawnThreads()::$_0&>()()) std::__invoke[abi:v15000]<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
2023.06.20 16:07:27.937792 [ 537 ] {} <Fatal> BaseDaemon: 14.3. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479: void std::__invoke_void_return_wrapper<void, true>::__call<DB::PipelineExecutor::spawnThreads()::$_0&>(DB::PipelineExecutor::spawnThreads()::$_0&)
2023.06.20 16:07:27.937853 [ 537 ] {} <Fatal> BaseDaemon: 14.4. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235: std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>::operator()[abi:v15000]()
2023.06.20 16:07:27.937899 [ 537 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000003beb6782 in /workspace/clickhouse
2023.06.20 16:07:28.064175 [ 537 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:0: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x0000000024b3d510 in /workspace/clickhouse
2023.06.20 16:07:28.161750 [ 537 ] {} <Fatal> BaseDaemon: 16. ./build_docker/./src/Common/ThreadPool.h:230: ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0x0000000024b47bee in /workspace/clickhouse
2023.06.20 16:07:28.272016 [ 537 ] {} <Fatal> BaseDaemon: 17. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:0: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x0000000024b34b71 in /workspace/clickhouse
2023.06.20 16:07:28.414105 [ 537 ] {} <Fatal> BaseDaemon: 18.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>, std::default_delete<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>>::reset[abi:v15000](std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>*)
2023.06.20 16:07:28.414238 [ 537 ] {} <Fatal> BaseDaemon: 18.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
2023.06.20 16:07:28.414289 [ 537 ] {} <Fatal> BaseDaemon: 18. ./build_docker/./contrib/llvm-project/libcxx/include/thread:297: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x0000000024b4190d in /workspace/clickhouse
2023.06.20 16:07:28.414341 [ 537 ] {} <Fatal> BaseDaemon: 19. ? @ 0x00007fd6ce9a1609 in ?
2023.06.20 16:07:28.414391 [ 537 ] {} <Fatal> BaseDaemon: 20. clone @ 0x00007fd6ce8c6133 in ?
2023.06.20 16:07:29.255737 [ 537 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 45D619A4FEBF58697637DC371E0C8650)
2023.06.20 16:07:40.475407 [ 537 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2023.06.20 16:07:40.475642 [ 537 ] {} <Fatal> BaseDaemon: Changed settings: receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, distributed_product_mode = 'local', table_function_remote_max_addresses = 200, prefer_global_in_and_join = true, max_execution_time = 10., max_memory_usage = 10000000000, enable_optimize_predicate_expression = false, allow_introspection_functions = true, mutations_sync = 1, optimize_functions_to_subcolumns = true, allow_experimental_object_type = true
2023.06.20 16:08:15.041493 [ 151 ] {} <Fatal> Application: Child process was terminated by signal 6.

**Comment by devcrafter** [comment]
The error is reproduced straightaway. Most of the time, the query returns `NOT_IMPLEMENTED` which is presumable correct error. The `NOT_IMPLEMENTED` is returned on `AggregatingTransform` in the pipeline. But sometimes, for a reason, execution is reaching `ExpressionTransform` on top of Aggregation. In such case, we get the error

<pre>
EXPLAIN PIPELINE header = 1
SELECT '0.02'
GROUP BY
    GROUPING SETS (
        ('6553.6'),
        (CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')')))

Query id: 890e9027-1c71-4aec-bd0f-355ead3b9c04

┌─explain──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ (Expression)                                                                                                                                                                                                                                             │
│ ExpressionTransform × 2                                                                                                                                                                                                                                  │
│ Header: '0.02' String: '0.02' String Const(size = 0, String(size = 1))                                                                                                                                                                                   │
│   (Aggregating)                                                                                                                                                                                                                                          │
│   <b>ExpressionTransform × 2</b>                                                                                                                                                                                                                                │
│   Header: __grouping_set UInt64: __grouping_set UInt64 UInt64(size = 0)                                                                                                                                                                                  │
│           '6553.6' String: '6553.6' String String(size = 0)                                                                                                                                                                                              │
│           <b>CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')') Object('json'): CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')') Object('json') Object(size = 0)</b>                                            │
│     <b>AggregatingTransform × 2</b>                                                                                                                                                                                                                             │
│     Header: '6553.6' String: '6553.6' String String(size = 0)                                                                                                                                                                                            │
│       Copy 1 → 2                                                                                                                                                                                                                                         │
│       Header × 2 : '6553.6' String: '6553.6' String Const(size = 0, String(size = 1))                                                                                                                                                                    │
│                     CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')') Object('json'): CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')') Object('json') Const(size = 0, Object(size = 1, Int8(size = 1))) │
│                     dummy UInt8: dummy UInt8 UInt8(size = 0)                                                                                                                                                                                             │
│         (Expression)                                                                                                                                                                                                                                     │
│         ExpressionTransform                                                                                                                                                                                                                              │
│         Header: '6553.6' String: '6553.6' String Const(size = 0, String(size = 1))                                                                                                                                                                       │
│                 CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')') Object('json'): CAST(CAST('{"x" : 1}', 'Object(Nullable(\'json\'))'), 'Object(\'json\')') Object('json') Const(size = 0, Object(size = 1, Int8(size = 1)))     │
│                 dummy UInt8: dummy UInt8 UInt8(size = 0)                                                                                                                                                                                                 │
│           (ReadFromStorage)                                                                                                                                                                                                                              │
│           SourceFromSingleChunk 0 → 1                                                                                                                                                                                                                    │
│           Header: dummy UInt8: dummy UInt8 UInt8(size = 0)                                                                                                                                                                                               │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
</pre>

**Comment by rschu1ze** [comment]
Happened also here: https://s3.amazonaws.com/clickhouse-test-reports/50276/11e37cab2191f4ca0f82e61914cff5da4ce4f045/fuzzer_astfuzzerubsan/report.html . Similar to above, it reproduces only sometimes, in other cases it returns NOT_IMPLEMENTED.
