### ISSUE TITLE
insert query doesn't have inlined data

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#51232]
I was testing `async_insert`, but cannot get INSERT to work asynchronously.

```sql
CREATE TABLE testasync
(
    `x` UInt32,
    `s` String
)
ENGINE = MergeTree
ORDER BY x
SETTINGS async_insert=1;

SET send_logs_level='debug';

INSERT INTO testasync(x,s) FORMAT CSV 1,'otOXud5QePZmYxbBWldYDl2WJDDPoVDSreFsmpPo';
```

and it spits:
```
<Debug> executeQuery: Setting async_insert=1, but INSERT query will be executed synchronously (reason: insert query doesn't have inlined data)
```

but I do provided data in INSERT query, right after `FORMAT CSV`.

so, what does the 'inlined data' mean in the logs, and how should I provide inlined data to ClickHouse?

ClickHouse Version: latest

see https://fiddle.clickhouse.com/7393d595-89bb-416c-a813-f9524b331b9f

**Comment by den-crane** [comment]
async_insert setting needs to be passed to the clickhouse-client.
clickhouse-client does not check the table settings, only own arguments.
