### ISSUE TITLE
MultiZookeeper for clickhouse cluster more 36 shards

### ISSUE THREAD

**Issue by it-forever** [ClickHouse/ClickHouse#51267]
On clusters with more than 36 shards and frequent insertion, the bottleneck is the zookeeper. Your presentation slide 43 https://presentations.clickhouse.com/meetup54/keeper.pdf lists a complex configuration.
What solutions use multizookeeper now and are there any clear recommendations where more than one zookeeper cluster should be used?

**Comment by den-crane** [comment]
>On clusters with more than 36 shards and frequent insertion, the bottleneck is the zookeeper.

How frequent insertion is? 

>multizookeeper

AFAIK multizookeeper has sense if you have ~1000 Clickhouse nodes.

**Comment by it-forever** [comment]
the size of 1 batch is 120-130 mb, 1 time in 10 seconds.
2000 tables of them 1500 replica factor =12|36|72
summary inserted data ~2GBps

Zookeeper Node Characteristics: CPU 12, RAM = 64Gb * 3 count, For metrics znode_count = 35+Mil

**Comment by den-crane** [comment]
>2000 tables

try

```
cat /etc/clickhouse-server/config.d/cleanup_delay_period.xml
<?xml version="1.0"?>
<yandex>
    <merge_tree>
       <cleanup_delay_period>300</cleanup_delay_period>
       <merge_selecting_sleep_ms>60000</merge_selecting_sleep_ms>
    </merge_tree>
</yandex>
```

see https://github.com/ClickHouse/ClickHouse/issues/31919 , https://github.com/ClickHouse/ClickHouse/pull/50107
