### ISSUE TITLE
formatDateTime handles fractional seconds wrongly before 1970 using DateTime64

### ISSUE THREAD

**Issue by stefan-veezoo** [ClickHouse/ClickHouse#51262]
**Describe what's wrong**

When formatting fractional seconds before 1970, they get "inverted" and instead of it being for example 13ms before the next second it will be 13ms after the next second:

```
SELECT formatDateTime(toDateTime64('1971-01-01 00:00:00.987', 3), '%Y-%m-%d %H:%i:%s.%f');
> 1971-01-01 00:00:00.987

SELECT formatDateTime(toDateTime64('1969-01-01 00:00:00.987', 3), '%Y-%m-%d %H:%i:%s.%f');
> 1969-01-01 00:00:01.013
```

Fiddle: https://fiddle.clickhouse.com/3c2eda68-f5d0-4261-ba0c-697d764401fc

**Comment by kardymonds** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/51290
