### ISSUE TITLE
Querying system.tables connects to external databases when it doesn't need to.

### ISSUE THREAD

**Issue by fdondi-doublecloud** [ClickHouse/ClickHouse#51277]
Using version 23.4.2.11 (official build)

**Describe the issue**
We are encountering a problem where after creating a database with external Postgres engine, if the database is unavailable, any query to system.tables fails -even if we want to ignore all the tables on that database, there seems to be no way to do so.

**How to reproduce**
Easiest way to reproduce is
`CREATE DATABASE test_db ENGINE = PostgreSQL('google.com:5432', 'dummy', 'dummy', 'dummy' );`
then anything involving `sytem.tables` will fail

**Expected behavior**
Data that cannot possibly be different should be available without calling the remote database. For instance:
- System.tables.engine (can only be `PostgreSQL` for the tables on the database)
- System.tables.has_own_data (can only be `False` for the tables on the database)
This should allow filtering, for instance 
`SELECT * FROM system.tables WHERE has_own_data` 
`SELECT * FROM system.tables WHERE engine != 'PostgreSQL'` 
should succeed without calling the Postgres external database, since no table there can pass the `WHERE` filter. 
`SELECT * FROM information_schema.tables WHERE table_type = 'BASE TABLE'` is also a candidate. 

**Error message and/or stacktrace**
Client:
`Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
Ok.
Query was cancelled.

0 rows in set. Elapsed: 4993.768 sec. `

Server:
`2023.06.22 14:47:49.903484 [ 19212 ] {98108465-0e42-4fed-ae64-a20dbae7e37a} <Error> virtual DB::DatabaseTablesIteratorPtr DB::DatabasePostgreSQL::getTablesIterator(DB::ContextPtr, const DB::IDatabase::FilterByNameFunction &) const: Code: 614. DB::Exception: Try 5. Connection to `google.com:5432` failed with error: connection to server at "google.com" (2a00:1450:4010:c0b::66), port 5432 failed: timeout expired
connection to server at "google.com" (2a00:1450:4010:c0b::71), port 5432 failed: timeout expired
connection to server at "google.com" (2a00:1450:4010:c0b::64), port 5432 failed: timeout expired
connection to server at "google.com" (2a00:1450:4010:c0b::8b), port 5432 failed: timeout expired
connection to server at "google.com" (173.194.73.100), port 5432 failed: timeout expired
connection to server at "google.com" (173.194.73.101), port 5432 failed: timeout expired
connection to server at "google.com" (173.194.73.139), port 5432 failed: timeout expired
connection to server at "google.com" (173.194.73.138), port 5432 failed: timeout expired
connection to server at "google.com" (173.194.73.113), port 5432 failed: timeout expired
connection to server at "google.com" (173.194.73.102), port 5432 failed: timeout expired

. (POSTGRESQL_CONNECTION_FAILURE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /usr/bin/clickhouse
1. ? @ 0x12463f2c in /usr/bin/clickhouse
2. postgres::PoolWithFailover::get() @ 0x1272382b in /usr/bin/clickhouse
3. DB::DatabasePostgreSQL::getTablesIterator(std::shared_ptr<DB::Context const>, std::function<bool (String const&)> const&) const @ 0x139f37cb in /usr/bin/clickhouse
4. ? @ 0x1250f5f0 in /usr/bin/clickhouse
5. DB::ISource::tryGenerate() @ 0x14d22235 in /usr/bin/clickhouse
6. DB::ISource::work() @ 0x14d21da6 in /usr/bin/clickhouse
7. DB::ExecutionThreadContext::executeTask() @ 0x14d3aa6a in /usr/bin/clickhouse
8. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14d3073b in /usr/bin/clickhouse
9. ? @ 0x14d3246f in /usr/bin/clickhouse
`

**Comment by Alex-Burmak** [comment]
Support of executing `SELECT * FROM system.tables WHERE engine != 'PostgreSQL'` without accessing PostgreSQL is the most useful scenario. Of course, the same behavior is expected for other integration engines.
cc @KochetovNicolai

**Comment by jsc0218** [comment]
the case is special to Postgres, since in the code it is created async (first create instance and then connect to it), fixed at https://github.com/ClickHouse/ClickHouse/pull/56609, https://github.com/ClickHouse/ClickHouse/pull/56648, https://github.com/ClickHouse/ClickHouse/pull/56813
