### ISSUE TITLE
Wrong result of function `transform`

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#51322]
**Describe what's wrong**

```sql
SELECT transform(-1, [-1, 2], ['f', 's'], 'g')
```

```
┌─transform(-1, [-1, 2], ['f', 's'], 'g')─┐
│ g                                       │
└─────────────────────────────────────────┘
```

The expected result is `f`.

**Additional context**

Those cases work correctly:

```sql
SELECT transform(2, [-1, 2], ['f', 's'], 'g')
```

```
┌─transform(2, [-1, 2], ['f', 's'], 'g')─┐
│ s                                      │
└────────────────────────────────────────┘
```

```sql
SELECT transform(-1::Int64, [-1, 2]::Array(Int64), ['f', 's'], 'g') AS res
```

```
┌─res─┐
│ f   │
└─────┘
```

**Comment by tavplubix** [comment]
Broken between 22.6 (https://fiddle.clickhouse.com/c3f16e42-605d-42f7-8cfa-390617864e26) and 22.7 (https://fiddle.clickhouse.com/86955dac-51bc-41e9-a9e5-d9804e14fde7)

**Comment by tavplubix** [comment]
Hm, no, it was broken by a backported bugfix:
22.7.6 - g - https://fiddle.clickhouse.com/636ebb2b-aa4f-44b2-b175-cffbe17b6520
22.7.5 - f - https://fiddle.clickhouse.com/ed0cc60e-0e47-4357-a6b6-05c026bab17a

**Comment by alexey-milovidov** [comment]
@tavplubix This bug is not because I've removed garbage from the codebase but because I didn't remove enough.
