### ISSUE TITLE
In ClickHouse with decimal type, when inserting the value '4.00' into the database, it is directly truncated to '4' with the decimal part '.00' being removed.

### ISSUE THREAD

**Issue by hcymysql** [ClickHouse/ClickHouse#51358]
### In ClickHouse with decimal type, when inserting the value '4.00' into the database, it is directly truncated to '4' with the decimal part '.00' being removed.

dbbackup-192-168-176-204 :) desc t2;

DESCRIBE TABLE t2

Query id: 285507e8-027c-4a59-9f2f-12d4133bb065

┌─name──┬─type───────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ id    │ Int32          │              │                    │         │                  │                │
│ total │ Decimal(18, 2) │              │                    │         │                  │                │
└───────┴────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

2 rows in set. Elapsed: 0.002 sec. 

dbbackup-192-168-176-204 :) ```insert into t2 values(1,4.00)```

INSERT INTO t2 FORMAT Values

Query id: 20106973-2de2-4224-9046-547705219a8a

Ok.

1 row in set. Elapsed: 0.007 sec. 

dbbackup-192-168-176-204 :) select * from t2;

SELECT *
FROM t2

Query id: 8f80a71b-4054-4924-868c-066fb9260351

┌─id─┬─total─┐
│  1 │     4 │
└────┴───────┘

1 row in set. Elapsed: 0.004 sec.

![image](https://github.com/ClickHouse/ClickHouse/assets/19261879/9f46474b-5e52-4909-bd28-100192052e4f)

# This is Decimal BUG?

**Comment by alexey-milovidov** [comment]
4.00 is equal to 4 exactly.

**Comment by den-crane** [comment]
it's about printing.

```sql
select '4.00'::Decimal(18, 2);
┌─CAST('4.00', 'Decimal(18, 2)')─┐
│                              4 │
└────────────────────────────────┘

set output_format_decimal_trailing_zeros=1;
select '4.00'::Decimal(18, 2);
┌─CAST('4.00', 'Decimal(18, 2)')─┐
│                           4.00 │
└────────────────────────────────┘
```

https://github.com/ClickHouse/ClickHouse/pull/27680

**Comment by hcymysql** [comment]
Thank you! This parameter solved my problem.

**Comment by hcymysql** [comment]
> it's about printing.
> 
> ```sql
> select '4.00'::Decimal(18, 2);
> ┌─CAST('4.00', 'Decimal(18, 2)')─┐
> │                              4 │
> └────────────────────────────────┘
> 
> set output_format_decimal_trailing_zeros=1;
> select '4.00'::Decimal(18, 2);
> ┌─CAST('4.00', 'Decimal(18, 2)')─┐
> │                           4.00 │
> └────────────────────────────────┘
> ```
> 
> #27680

Thank you! This parameter solved my problem.
