### ISSUE TITLE
Subsequence string matching

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#51389]
**Use case**

A variant of fuzzy search, you can find in many IDEs.

**Describe the solution you'd like**

`hasSubsequence(a, b)` - returns 1 if `a` contains all the symbols of `b` in the order.

For example:
```
hasSubsequence('garbage', 'arg') = 1
hasSubsequenceUTF8
hasSubsequenceCaseInsensitive
hasSubsequenceCaseInsensitiveUTF8
```

**Comment by kardymonds** [comment]
Please assign to me
