### ISSUE TITLE
ReplicatedSummingMergeTree do not support Map?

### ISSUE THREAD

**Issue by daoweili** [ClickHouse/ClickHouse#51385]
CREATE TABLE metrics.testSumMap
(
    `id` UInt64,
    `dist` Map(String, UInt64),
    `failed` UInt64
)
ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/metrics/testSumMap', '{replica}')
ORDER BY id
SETTINGS index_granularity = 8192

insert into metrics.testSumMap(id,dist,failed)  values(1, {'1':1, '2':2, '3':3}, 1)
insert into metrics.testSumMap(id,dist,failed)  values(1, {'1':1, '2':2, '4':3}, 1)
insert into metrics.testSumMap(id,dist,failed)  values(1, {'1':1, '2':2, '4':3}, 2)

SELECT *
FROM testSumMap

Query id: 2ffcbca2-8726-4c66-877f-bcf3202d4c29

┌─id─┬─dist────────────────┬─failed─┐
│  1 │ {'1':1,'2':2,'4':3} │      1 │
└────┴─────────────────────┴────────┘
┌─id─┬─dist────────────────┬─failed─┐
│  1 │ {'1':1,'2':2,'4':3} │      2 │
└────┴─────────────────────┴────────┘
┌─id─┬─dist────────────────┬─failed─┐
│  1 │ {'1':1,'2':2,'3':3} │      1 │
└────┴─────────────────────┴────────┘

OPTIMIZE TABLE testSumMap FINAL

Query id: ee168b09-6b7c-450f-86b3-fb3f0151610b

Ok.

0 rows in set. Elapsed: 0.729 sec.

SELECT *
FROM testSumMap

Query id: 40368248-546a-4c4a-9a19-ad175caa4e0a

┌─id─┬─dist────────────────┬─failed─┐
│  1 │ {'1':1,'2':2,'3':3} │      4 │
└────┴─────────────────────┴────────┘

1 row in set. Elapsed: 0.002 sec. 

Hi, is this result right?

**Comment by den-crane** [comment]
`SimpleAggregateFunction (sumMap, Map(String, UInt64)),`

```sql
CREATE TABLE testSumMap
(
id UInt64,
dist SimpleAggregateFunction (sumMap, Map(String, UInt64)),
failed UInt64
)
ENGINE = SummingMergeTree
ORDER BY id;

insert into testSumMap values(1, {'1':1, '2':2, '3':3}, 1);
insert into testSumMap values(1, {'1':1, '2':2, '4':3}, 1);
insert into testSumMap(id,dist,failed) values(1, {'1':1, '2':2, '4':3}, 2);

optimize table testSumMap final;

select * from testSumMap
format Pretty
+----+---------------------------+--------+
| id | dist                      | failed |
+----+---------------------------+--------+
|  1 | {'1':3,'2':6,'3':3,'4':6} |      4 |
+----+---------------------------+--------+

```

https://fiddle.clickhouse.com/26c4d33e-c464-47ce-8948-01e6bac246cd
