### ISSUE TITLE
Coverage Analysis Question 

### ISSUE THREAD

**Issue by xiaoyong-z** [ClickHouse/ClickHouse#51394]
Is coverage analysis still runnable on latest functionStatelessTest and functionStatefulTest?

It seems that in history pr(https://github.com/ClickHouse/ClickHouse/pull/18312/files), clickhouse can run the coverage analysis on both functionStatelessTest and functionStatefulTest with the dockerfile in docker/test/coverage directory.

But in latest version, this docker file is removed.

**Comment by alexey-milovidov** [comment]
It is possible to collect coverage, but it takes a very long time, e.g., a day.
