### ISSUE TITLE
DateTime Default value on missing/empty key/value pair.

### ISSUE THREAD

**Issue by ilugid** [ClickHouse/ClickHouse#51401]
**Describe what's wrong**

A DateTime column with Default expr as now() does not populate value from now if the value being inserted is empty or if the column is missing in the data source.

**Does it reproduce on recent release?**

Yes. 23.2.2.20.

**How to reproduce**

* 23.2.2.20
* clickhouse-client
* Non-default settings: NA
*

```
CREATE TABLE default.data_set
(
    `createdAt` DateTime DEFAULT now()
)
ENGINE = Memory
```

```
CREATE TABLE default.data_set_kafka
(
    `createdAt` DateTime DEFAULT now()
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka-host:9092', kafka_topic_list = 'topic-name', kafka_group_name = 'kafka-group-name', kafka_format = 'JSONEachRow', kafka_skip_broken_messages = 10


or you can create a regular table just for testing.

CREATE TABLE default.data_set_kafka
(
    `createdAt` DateTime DEFAULT now()
)
ENGINE = Memory
```

```
CREATE MATERIALIZED VIEW default.data_set_mv TO default.data_set
(
    `createdAt` DateTime
) AS
SELECT multiIf(createdAt = NULL, now(), createdAt = 0, now(), createdAt)
FROM default.data_set_kafka


or even if you use just select without multiif, it does not work


CREATE MATERIALIZED VIEW default.data_set_mv TO default.data_set
(
    `createdAt` DateTime
) AS
SELECT createdAt FROM default.data_set_kafka
```

For regular kafka table (memory engine)
```
INSERT INTO default.data_set_kafka values ('2023-06-07')
INSERT INTO default.data_set_kafka values (NULL)
INSERT INTO default.data_set_kafka values ()
```

For insertion using kcat command.
```
{}
{"createdAt":""}
{"createdAt":"2023-06-29"}
```

* select * from default.data_set

**Expected behavior**

We expect values to have the result of now() for missing column or empty value for the createdAt field. Explicitly specifying NULL works, however other options do not work.

**Error message and/or stacktrace**
No error messages.

**Comment by UnamedRus** [comment]
> SELECT multiIf(createdAt = NULL, now(), createdAt = 0, now(), createdAt)

By default fields are non nullable

> SELECT multiIf(createdAt = NULL, now(), createdAt = 0, now(), createdAt)

In MV you should match not positions of columns, but their names

IE 

> SELECT multiIf(createdAt = NULL, now(), createdAt = 0, now(), createdAt) as createdAt

**Comment by ilugid** [comment]
That worked. Thanks!
