### ISSUE TITLE
Multi-provider zero copy replication

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#51417]
Scenario: You want to have a ClickHouse cluster that spans across different providers (or even different regions of the same provider) for reasons such as safety or low latency reads. In order to be able to scale you also want to separate compute and storage, so want to use cloud storage and zero copy replication.

Since the 2 subsets of machines are in different providers you, each should hold its own copy of the data; that is, you don't want a full zero copy replication, but zero copy replication among the servers sharing config/provider.

The problem: Zero copy replication, as defined right now, knows nothing about the storage configuration (region or bucket). You only get a path based on the part name and little else, but to know where the data is you need the config from the <disk>.

In the current situation, if you do something like having a different region or bucket in each provider configuration you end up with something like this:

- Server 1-1 ingests the part. Uploads it to its cloud storage. Creates ZK nodes (including the zero-copy one).
- Server 1-2, in the same provider as 1-1, gets notified about the new part. Confirms that it has access to the data in s3, so it annotates itself as also holding the data.
- Server 2-1, in a different provider, also gets notified about the new part. As 1-2, with zero copy replication it checks that it can access the data, but it can't because the bucket is different. To avoid data loss and be able to continue working,  it asks one of the other replicas (1-1 or 1-2) for a copy of the data (which forces a download + upload there), and then uploads it to its bucket. It won't use zero-copy replication since it doesn't have a good way to distinguish the 2 copies, and using the original ZK path would lead to avoid premature (or no) deletion.
- Server 2-2. Exact same as 2-1. It will have its own copy of the part in s3.

The good part is that this currently seems to work and avoids data loss. The bad part, you end up with 3 copies of the data, with all the servers in provider 1 using zero-copy, while each of the servers in provider-2 have its own copy of the data and are responsible for it.

In an ideal scenario, I would like each of the providers to act independently of each other and keep a single copy in cloud storage each. That way Server 1-1 and 1-2 will share the data, and server 2-1 and 2-2 will share a different copy of the data. Each copy would be independent in terms of deciding when to delete the data, that is, servers in region 1 shouldn't need access to the data in region 2 and vice versa.

In this ideal scenario, the first replica in the second provider (2-1) should be the one that notices the change in provider (because the zero-copy path doesn't match), downloads the data and uploads to its provider cloud storage, and activates a different zero-copy node in ZK. Subsequent replicas should a) wait for 2-1 to do its job and then b) use zero-copy on this data and not the original one.

Note that I've been talking about different providers the whole time, but the initial pain comes from s3 cross region replication. AFAIK there is no way to guarantee that once you PUT an object it will be available in all buckets (force/wait for confirmation), and this doesn't play well with CH zero copy replication.

Would something like this make sense? Maybe there is a simpler way to do this instead.

**Comment by UnamedRus** [comment]
Related 

https://github.com/ClickHouse/ClickHouse/issues/35684

https://github.com/ClickHouse/ClickHouse/issues/35684#issuecomment-1091914691
