### ISSUE TITLE
Flaky `test_postgresql_replica_database_engine` integration test

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#51416]
See [CIDB](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA1LTI2JyBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3Bvc3RncmVzcWxfcmVwbGljYV9kYXRhYmFzZV9lbmdpbmUlJyBhbmQgc3RhdHVzIGluICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpCm9yZGVyIGJ5IGNoZWNrX3N0YXJ0X3RpbWUgZGVzYw==)

**Comment by tavplubix** [comment]
It did not fail for a while according to the CI DB
