### ISSUE TITLE
Flaky test_disk_over_web_server

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#51437]
https://s3.amazonaws.com/clickhouse-test-reports/0/4b02d83999808ab06320ba82a4530bb958e6b51f/integration_tests__tsan__[5_6].html

It looks we did not stop ClickHouse when we started `static-files-disk-uploader` and it deleted a file or we just have incorrect data in path.

```
E               Exception: Command ['docker', 'exec', '-u', 'root', 'roottestdiskoverwebserver_node1_1', 'bash', '-c', '/usr/bin/clickhouse static-files-disk-uploader --test-mode --url http://nginx:80/test1 --metadata-path /store/6b3/6b3eb353-292f-499c-9bf3-6fe329a43b89/'] return non-zero code 1: Data path: "/store/6b3/6b3eb353-292f-499c-9bf3-6fe329a43b89", destination path: "http://nginx:80/test1"
E               std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in file_size: No such file or directory ["/store/6b3/6b3eb353-292f-499c-9bf3-6fe329a43b89/tmp_merge_all_1_10_2"]
E               Cannot print extra info for Poco::Exception (version 23.6.1.1 (official build))
```

**Comment by tavplubix** [comment]
May be related to https://github.com/ClickHouse/ClickHouse/issues/51156

**Comment by azat** [comment]
It is still flaky - https://s3.amazonaws.com/clickhouse-test-reports/65978/39e9f5dcde5d9a86f36c46974c7b0d47beb60259/integration_tests__asan__old_analyzer__[5_6].html

**Comment by azat** [comment]
Though it is a different test (for page cache) and different problem
