### ISSUE TITLE
Increased hardware configuration reduces performance

### ISSUE THREAD

**Issue by cyhyyq** [ClickHouse/ClickHouse#51456]
**Describe the situation**
Same data, same query conditions, same tables, same configuration
8C 16G 35 million/s
16C 16G 66.98 million/s
24C 16G 55.19 million/s
48C 32G 42.5 million/s
Since 16C, query performance has decreased with increasing configuration

**How to reproduce**
* Which ClickHouse server version to use
21.8.15.7.

* `CREATE TABLE` statements for all tables involved
CREATE TABLE IF NOT EXISTS logs_local ON CLUSTER test(
    a     String,
    b     String,
    c     Datetime,
    d     String,
    e     String,
    f      String,
    g     UInt16,
    h     UInt8,
    i      Int32,
    j       UInt8,
    k      UInt8,
    l       UInt8,
    m     Array(String),
    n      DEFAULT rand(),
    o      String
) ENGINE = ReplicatedMergeTree('/clickhouse/test/{shard}/logs', '{replica}')
PARTITION BY (toYYYYMMDD(qtime)) ORDER BY (a,b,c,d,e,f);

* Queries to run that lead to slow performance
select * from logs

**Expected performance**
performance should improve as CPU and memory increase

**Comment by alexey-milovidov** [comment]
Not enough info was provided.
