### ISSUE TITLE
Slow performance of count() query on MergeTree table with partitioning

### ISSUE THREAD

**Issue by fujiecai** [ClickHouse/ClickHouse#51454]
I have a MergeTree table with the following structure:

CREATE TABLE test (
  id Int64,
  time DateTime
) Engine=MergeTree PARTITION BY toRelativeHourNum(endtime) ORDER BY time;

The table contains data for the period between 2023/05/01 and 2023/06/01. Now, I want to count the number of records between 2023/05/15 and 2023/06/01 using the following SQL query:

SELECT COUNT() FROM test WHERE time>='2023-05-15 00:00:00';

I expected this query to be fast since it should only scan the partitions that contain data for the specified time range. However, the query takes a long time to execute, even though the table has only a few partitions.

To investigate further, I ran the following query:

SELECT COUNT() FROM test WHERE time>='2022-05-15 00:00:00';

This query should be as fast as SELECT COUNT() FROM test; since it covers the entire range of the table. However, it also takes a long time to execute.

I suspect that the partitioning scheme is causing the slow performance, but I'm not sure how to optimize the query to avoid scanning all partitions. Can you suggest any optimizations that I could try?

Thank you for your help.

**Comment by den-crane** [comment]
the problem that `time` is not related to `endtime`.

You have to filter by `endtime`! `WHERE endtime>=...`

**Comment by fujiecai** [comment]
> the problem is that `time` is not related to `endtime`.
> 
> You have to filter by `endtime`! `WHERE endtime>=...`

Sorry, I made a mistake in the demo of my issue. During testing, I did not confuse endtime and time, and the partition key was also time. However, when using time as a condition for count(), it only excluded one partition, and it was evident that the exclusion was not successful as all partitions were scanned. Then, a binary search on the primary key was performed.

But if I take a different approach and query the system.parts table to find the partitions that contain the data I need, and set the boundaries of time to only search within one partition, the query will be much faster.

**Comment by fujiecai** [comment]
> > the problem is that `time` is not related to `endtime`.
> > You have to filter by `endtime`! `WHERE endtime>=...`
> 
> Sorry, I made a mistake in the demo of my issue. During testing, I did not confuse endtime and time, and the partition key was also time. However, when using time as a condition for count(), it only excluded one partition, and it was evident that the exclusion was not successful as all partitions were scanned. Then, a binary search on the primary key was performed.
> 
> But if I take a different approach and query the system.parts table to find the partitions that contain the data I need, and set the boundaries of time to only search within one partition, the query will be much faster.

Actually, we only need to perform a binary search within one partition, while using the minmax values of the other partitions to exclude them from the search. This approach can significantly improve performance.
