### ISSUE TITLE
How can I install ClickHouse and Python in the same docker container?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#51452]
I want to install ClickHouse and Python in the same docker container, then I  can use [User Defined Functions](https://clickhouse.com/docs/en/sql-reference/functions/udf) and [User Scripts](https://clickhouse.com/docs/en/engines/table-engines/special/executable).

But I search google and see [this](https://chistadata.com/knowledge-base/how-to-install-clickhouse-and-python-in-the-same-docker-container/), this is incompatible. I want to build one image based on ClickHouse image, than I can install Python, Node.js and so on, but that bases on Python image.

What can I do?

Thanks!

**Comment by den-crane** [comment]
I would install python into official Clickhouse container. 

```
# cat Dockerfile
FROM clickhouse/clickhouse-server:latest

RUN apt update -y
RUN apt install -y python3

# docker build --tag clickhouse-python .
```

**Comment by LGDHuaOPER** [comment]
Do you need to add `ENTRYPOINT` or `CMD` statements?

**Comment by den-crane** [comment]
You do not.
