### ISSUE TITLE
Flaky integration `test_host_regexp_multiple_ptr_records`

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#51471]
see [CIDB](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA1LTI3JyBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2hvc3RfcmVnZXhwX211bHRpcGxlX3B0cl9yZWNvcmRzJScgYW5kIHN0YXR1cyBpbiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKQpvcmRlciBieSBjaGVja19zdGFydF90aW1lIGRlc2M=)

Sample reports: 
[one](https://s3.amazonaws.com/clickhouse-test-reports/50559/ddd8f6bba36b43339a7e7d45ae4f5181ebdba7a7/integration_tests__release__[3_4].html), [two](https://s3.amazonaws.com/clickhouse-test-reports/0/eb649873b379a29fec5584205558f70641f16bba/integration_tests__release__[3_4].html)

**Comment by tavplubix** [comment]
Still flaky: https://s3.amazonaws.com/clickhouse-test-reports/53167/396956d21d77b06c774b09272dfc37c28946c124/integration_tests__release__[3_4].html

cc: @arthurpassos

**Comment by arthurpassos** [comment]
> Still flaky: [https://s3.amazonaws.com/clickhouse-test-reports/53167/396956d21d77b06c774b09272dfc37c28946c124/integration_tests__release__[3_4].html](https://s3.amazonaws.com/clickhouse-test-reports/53167/396956d21d77b06c774b09272dfc37c28946c124/integration_tests__release__%5B3_4%5D.html)
> 
> cc: @arthurpassos

@tavplubix @alexey-milovidov I have ran this test several times in my local machine using the integration-tests docker image, they all fail. While digging a bit deeper, I found out the coredns server is not responding properly. `nslookup <ip>` returns an empty response, which is very awkward, it wasn't like that in the past. If I set up the very same environment with a local CH instance, it works as expected. Are you guys aware of any recent changes in the CI infra / integ tests image that might have caused this?

**Comment by alexey-milovidov** [comment]
We didn't, but not all of our dependencies are pinned. Let's pin coredns and as much else as possible to some specific version.

**Comment by arthurpassos** [comment]
> We didn't, but not all of our dependencies are pinned. Let's pin coredns and as much else as possible to some specific version.

@alexey-milovidov @tavplubix 

I just got a green run after pinning coredns version to `1.9.2`.

```
root@arthur:/# docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS            NAMES
b9bdd0e1faed   clickhouse/integration-test:latest   "clickhouse server -…"   35 seconds ago   Up 33 seconds                    roottesthostregexpmultipleptrrecords_clickhouse-server_1
84a4d8584255   clickhouse/integration-test:latest   "clickhouse server -…"   35 seconds ago   Up 33 seconds                    roottesthostregexpmultipleptrrecords_clickhouse-client_1
bf9dace16ae4   coredns/coredns:1.9.2                "/coredns"               45 seconds ago   Up 44 seconds   53/tcp, 53/udp   roottesthostregexpmultipleptrrecords_coredns_1
```


```
arthur@arthur:~/ClickHouse/tests/integration$ ./runner --binary ~/ClickHouse/cmake-build-debug/programs/clickhouse 'test_host_regexp_multiple_ptr_records'
2023-08-10 11:31:18,833 [ 41923 ] INFO : ClickHouse root is not set. Will use /home/arthur/ClickHouse (runner:42, check_args_and_update_paths)
2023-08-10 11:31:18,833 [ 41923 ] INFO : Base configs dir is not set. Will use /home/arthur/ClickHouse/programs/server (runner:77, check_args_and_update_paths)
2023-08-10 11:31:18,833 [ 41923 ] INFO : Cases dir is not set. Will use /home/arthur/ClickHouse/tests/integration (runner:90, check_args_and_update_paths)
2023-08-10 11:31:18,833 [ 41923 ] INFO : src dir is not set. Will use /home/arthur/ClickHouse/src (runner:97, check_args_and_update_paths)
2023-08-10 11:31:18,833 [ 41923 ] INFO : base_configs_dir: /home/arthur/ClickHouse/programs/server, binary: /home/arthur/ClickHouse/cmake-build-debug/programs/clickhouse, cases_dir: /home/arthur/ClickHouse/tests/integration  (runner:99, check_args_and_update_paths)
clickhouse_integration_tests_volume
Running pytest container as: 'docker run --net=host -it --rm --name clickhouse_integration_tests_3dhssh --privileged --dns-search='.' --volume=/home/arthur/ClickHouse/cmake-build-debug/programs/clickhouse-odbc-bridge:/clickhouse-odbc-bridge --volume=/home/arthur/ClickHouse/cmake-build-debug/programs/clickhouse:/clickhouse --volume=/home/arthur/ClickHouse/cmake-build-debug/programs/clickhouse-library-bridge:/clickhouse-library-bridge --volume=/home/arthur/ClickHouse/programs/server:/clickhouse-config --volume=/home/arthur/ClickHouse/tests/integration:/ClickHouse/tests/integration --volume=/home/arthur/ClickHouse/src/Server/grpc_protos:/ClickHouse/src/Server/grpc_protos --volume=/run:/run/host:ro --volume=clickhouse_integration_tests_volume:/var/lib/docker   -e DOCKER_CLIENT_TIMEOUT=300 -e COMPOSE_HTTP_TIMEOUT=600  -e PYTHONUNBUFFERED=1 -e PYTEST_ADDOPTS=" test_host_regexp_multiple_ptr_records   -vvv" clickhouse/integration-tests-runner:latest '.
Start tests
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /ClickHouse/tests/integration
configfile: pytest.ini
plugins: random-0.2, timeout-2.1.0, order-1.0.0, repeat-0.9.1, xdist-3.3.1
timeout: 900.0s
timeout method: signal
timeout func_only: False
collected 3 items                                                                                                                                                                                                 

test_host_regexp_multiple_ptr_records/test.py::test_host_regexp_multiple_ptr_v4_fails_with_wrong_resolution PASSED                                                                                          [ 33%]
test_host_regexp_multiple_ptr_records/test.py::test_host_regexp_multiple_ptr_v4 PASSED                                                                                                                      [ 66%]
test_host_regexp_multiple_ptr_records/test.py::test_host_regexp_multiple_ptr_v6 PASSED                                                                                                                      [100%]

========================================================================================== 3 passed in 108.80s (0:01:48) ==========================================================================================

```

**Comment by arthurpassos** [comment]
@alexey-milovidov will you guys accept a PR with the pinned version?

**Comment by tavplubix** [comment]
@Felixoid would not accept it, but I will :) 

(we need to pin everything that we use in the CI, see https://github.com/ClickHouse/ClickHouse/issues/51682)

**Comment by arthurpassos** [comment]
> @Felixoid would not accept it, but I will :)
> 
> (we need to pin everything that we use in the CI, see #51682)

Ok. I do not know exactly why `:latest` makes it fail, but the test was running just fine until some time ago (as far as I know, not sure when it started failing), so I guess it should be enough.

**Comment by Felixoid** [comment]
> @Felixoid would not accept it, but I will :)

it's not a completely true. Pinning makes sense, but as well the bug should be reported to the upstream.

My point is it won't be nice to end up with a very outdated infrastructure.

**Comment by alexey-milovidov** [comment]
I will also accept (and welcome) that PR.

**Comment by arthurpassos** [comment]
> I will also accept (and welcome) that PR.

https://github.com/ClickHouse/ClickHouse/pull/53286
