### ISSUE TITLE
Please allow no/empty consumer group in kafka engine

### ISSUE THREAD

**Issue by yctn** [ClickHouse/ClickHouse#5147]
currently its not possible to leave consumer group emty. as it will result in this error:
Received exception from server (version 19.1.6):
Code: 1001. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Local: Unknown group.

i know this is normaly a bad idea. but we wanted to consume some older data from kafka after a crash.

and with consumer groups you cant load old data.

so its usefull in emegency's to be able to do this. or during migrations this could be a handy.

so also provide a way to do -o beginning to pull in the entire topic

**Comment by champtar** [comment]
Why not just put a different group name ?

**Comment by yctn** [comment]
cause a different group name will not pull All the data. it will just start now. and now get the entire topic.

**Comment by filimonov** [comment]
> cause a different group name will not pull All the data.

That is not true (at least now). When you use some new group name engine Kafka by default will start reading the topic from the beginning. 

https://github.com/ClickHouse/ClickHouse/blob/18ce66bb3e1616a47e438b703c5d511b674bb605/src/Storages/Kafka/StorageKafka.cpp#L352

**Comment by filimonov** [comment]
You can adjsut that behavior by putting few lines in config.xml, like in that sample:

https://github.com/ClickHouse/ClickHouse/blob/18ce66bb3e1616a47e438b703c5d511b674bb605/docs/en/engines/table-engines/integrations/kafka.md#configuration-configuration
