### ISSUE TITLE
Cannot allocate RAFT instance due to "Address family not supported by protocol" (IPv6 disabled)

### ISSUE THREAD

**Issue by SavelyevPavel** [ClickHouse/ClickHouse#51474]
It's look like that resolving of issue #33381 hasn't fixed the problem with ClickHouse-Keeper on machines with disabled IPv6:

In /var/log/clickhouse-server/clickhouse-server.log we have:

2023.06.27 13:47:36.661896 [ 113898 ] {} <Error> RaftInstance: got exception: open: Address family not supported by protocol [system:97] on port 9234
2023.06.27 13:47:36.661947 [ 113898 ] {} <Debug> KeeperDispatcher: Server initialized, waiting for quorum
2023.06.27 13:50:36.662692 [ 113898 ] {} <Error> void DB::KeeperDispatcher::initialize(const Poco::Util::AbstractConfiguration &, bool, bool): Code: 568. DB::Exception: Failed to wait RAFT initialization. (RAFT_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ec73a in /usr/bin/clickhouse
1. DB::KeeperServer::waitInit() @ 0x16062e35 in /usr/bin/clickhouse
2. DB::KeeperDispatcher::initialize(Poco::Util::AbstractConfiguration const&, bool, bool) @ 0x1604df4a in /usr/bin/clickhouse
3. DB::Context::initializeKeeperDispatcher(bool) const @ 0x14875d4d in /usr/bin/clickhouse
4. DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0xa48d880 in /usr/bin/clickhouse
5. Poco::Util::Application::run() @ 0x189a11a6 in /usr/bin/clickhouse
6. DB::Server::run() @ 0xa47e8fe in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0xa47be97 in /usr/bin/clickhouse
8. main @ 0xa3da86b in /usr/bin/clickhouse
9. __libc_start_main @ 0x3ad85 in /usr/lib64/libc-2.28.so
10. _start @ 0xa19a46e in /usr/bin/clickhouse
 (version 22.8.6.71 (official build))

...and no listening ports from ClickHouse...
ss -tunlp
Netid                 State                  Recv-Q                 Send-Q                                 Local Address:Port                                  Peer Address:Port                Process                
udp                   UNCONN                 0                      0                                            0.0.0.0:111                                        0.0.0.0:*                                          
udp                   UNCONN                 0                      0                                          127.0.0.1:323                                        0.0.0.0:*                                          
udp                   UNCONN                 0                      0                                            0.0.0.0:45755                                      0.0.0.0:*                                          
tcp                   LISTEN                 0                      128                                          0.0.0.0:10050                                      0.0.0.0:*                                          
tcp                   LISTEN                 0                      128                                          0.0.0.0:111                                        0.0.0.0:*                                          
tcp                   LISTEN                 0                      128                                          0.0.0.0:22                                         0.0.0.0:*  

There are no uncommented IPv6 wildcards in config.xml, config.d configs and only one default user. To config.xml we added only:
<listen_host>0.0.0.0</listen_host>
<interserver_listen_host>0.0.0.0</interserver_listen_host>
Everything else is default after ClickHouse installed from rpm.

ClickHouse release: 22.8.6.71-lts
OS: RHEL 8

**Comment by antonio2368** [comment]
Can you try setting `keeper_server.enable_ipv6` to `false` in your XML?
`interserver_listen_host` support in Keeper is in 22.9+.

**Comment by SavelyevPavel** [comment]
Yes, `keeper_server.enable_ipv6` works! Thank you, @antonio2368!
