### ISSUE TITLE
federating same query to multiple CH clusters

### ISSUE THREAD

**Issue by Yadumathur** [ClickHouse/ClickHouse#51488]
Which feature your question relates to?
Federation of queries ( read ) across multiple CH clusters

Question details
I am looking at possibility of federating search queries across multiple CH clusters ( isolated installation ) which are in different region , Is that something which is in plan or coming up ?
We should be able to fetch results and merge them to show as aggregated results.
Is there something already in place ? which we can use or any third party service which can help us here ?

**Comment by nickitat** [comment]
you could use `remote` function to select from any CH cluster

**Comment by genzgd** [comment]
You can also define a "virtual cluster" to include all clickhouse nodes you want to query (even if they belong to different "logical" clusters), and create a Distributed table across those nodes that references underlying tables assuming those tables using the same structure.

**Comment by Yadumathur** [comment]
@genzgd we have these as different physical clusters , does virtual cluster works in that case while we create distributed table ?

**Comment by Yadumathur** [comment]
@nickitat could you please refer the example where I can pick up multiple physical clusters and federate a search using remote ?

**Comment by genzgd** [comment]
I've only done it in XML, but in that case you can create your `<virtual_cluster>` in the`<remote_servers>` element and add whatever nodes your want to query from both the "local" cluster and the "remote" cluster in their own shard elements:

```xml
<remote_servers>
    <virtual_cluster>
        <!-- This shard is from the local cluster -->
        <shard>
            <replica>
                <host>shard1_replica1.local_cluster.example.com</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>shard1_replica2.local_cluster.example.com</host>
                <port>9000</port>
            </replica>
        </shard>
        <!-- This shard is from the remote cluster -->
        <shard>
            <replica>
                <host>shard1_replica1.remote_cluster.example.com</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>shard1_replica2.remote_cluster.example.com</host>
                <port>9000</port>
            </replica>
        </shard>
    </virtual_cluster>
</remote_servers>
```

So then you can create your distributed table using this "virtual_cluster", and it will retrieve data from the local cluster as one shard, and the remote as a second shard, and combine that data in your queries as with any other sharded table.

**Comment by Yadumathur** [comment]
Thanks @genzgd , This helps 
I will try this out
