### ISSUE TITLE
A loop in a hierarchical dictionary crashes the server

### ISSUE THREAD

**Issue by tobia** [ClickHouse/ClickHouse#515]
The functions `dictIsIn()` and `dictGetHierarchy()` are not very robust in the face of a dictionary with a hierarchical loop.

If you define by mistake a dictionary with a loop in the parent ID attribute (even just by using `<null_value>` in an incorrect way), then `dictIsIn()` goes into an infinite loop and `dictGetHierarchy()` starts allocating memory for an infinite array.

They cannot be terminated by the client and need a `pkill -9 clickhouse-serv`

As a related note, the dictionaries seem to use a [hardcoded parent ID = zero](https://github.com/yandex/ClickHouse/blob/ed5b5211101fcff939a85bff90b8d764b7992d4a/dbms/include/DB/Dictionaries/IDictionary.h#L79) to mean "no parent" or "root node." But zero is actually a valid ID for a dictionary! I think this should at least be documented.

**Comment by alexey-milovidov** [comment]
@alesapin 
Please verify if it's possible to trigger this issue with the new dictionaries DDL queries.

**Comment by alexey-milovidov** [comment]
For `dictGetHierarchy` it was fixed in #1064
