### ISSUE TITLE
ClickHouse make whole instance stuck

### ISSUE THREAD

**Issue by asurovenko-zeta** [ClickHouse/ClickHouse#51515]
Hello,

My clickhouse working on AWS EC2 instance with 2 **gp3** disks. Main disk for 1000Gb (16000 IOPS, 1000 throughput) and disk for data with 16384Gb (16000 IOPS, 1000 throughput)
I have 4 instances in my cluster, all configured the same.
In random day, in random time random instance got stuck: on CPU basic chart in grafana coming from node_exporter just going to **25% Busy Iowait** 
I'll attach the chart with it.
And second thing I noticed it's that my servers keep trying to send data to ClickHouse than got stuck and just keep waiting till client timeout but anyway I have chart with TCP connections and number of that connections increasing. So the ClickHouse keep getting connections but noting else
<img width="1655" alt="Screenshot 2023-06-28 at 10 40 35" src="https://github.com/ClickHouse/ClickHouse/assets/80847074/693e3e4c-d75e-4dba-bb52-3caa1078ec70">
<img width="815" alt="Screenshot 2023-06-28 at 10 47 29" src="https://github.com/ClickHouse/ClickHouse/assets/80847074/73fa6e57-c867-4582-bab4-31b48932e540">

I do not see anything in .err.log. It happening regularly: once per 3-6 days.
Please help me to understand the problem.
Thanks!

**Comment by alexey-milovidov** [comment]
Let's check this: https://clickhouse.com/docs/knowledgebase/which-processes-are-currently-running

**Comment by alexey-milovidov** [comment]
Does it happen just once or multiple times?

Remember that disks (especially network disks like EBS) are unreliable. They can fail.

**Comment by asurovenko-zeta** [comment]
It happened already 5-6 times on 2/4 servers

**Comment by den-crane** [comment]
Provide `select version()`

**Comment by asurovenko-zeta** [comment]
> Provide `select version()`

23.4.2.11

**Comment by alexey-milovidov** [comment]
Check if upgrading to the master version will help.
Download the master version as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by asurovenko-zeta** [comment]
Should I install it?

**Comment by den-crane** [comment]
try this 

```
cat /etc/clickhouse-server/config.d/z_log_disable.xml
<?xml version="1.0"?>
<clickhouse>
    <trace_log remove="1"/>
</clickhouse>
```

**Comment by asurovenko-zeta** [comment]
> try this
> 
> ```
> cat /etc/clickhouse-server/config.d/z_log_disable.xml
> <?xml version="1.0"?>
> <clickhouse>
>     <trace_log remove="1"/>
> </clickhouse>
> ```
> 
> +restart

Done, I just turn off a trace log. Is this helps?

**Comment by den-crane** [comment]
>Done, I just turn off a trace log. Is this helps?

I hope.

**Comment by asurovenko-zeta** [comment]
> > Done, I just turn off a trace log. Is this helps?
> 
> I hope.

It just happened again few minutes ago after change z_log_disable

**Comment by den-crane** [comment]
> It just happened again few minutes ago after change z_log_disable

did you restart clickhouse after z_log_disable ?

**Comment by asurovenko-zeta** [comment]
> > It just happened again few minutes ago after change z_log_disable
> 
> did you restart clickhouse after z_log_disable ?

Yes

**Comment by den-crane** [comment]
I've reread https://github.com/ClickHouse/ClickHouse/issues/49963
So when it happens you are unable to connect to the server using ssh? You restart EC2 not Clickhouse to make it work?

**Comment by asurovenko-zeta** [comment]
> I've reread #49963 So when it happens you are unable to connect to the server using ssh? You restart EC2 not Clickhouse to make it work?

yes, correct

**Comment by den-crane** [comment]
Do you use XFS or ext4 ?

**Comment by asurovenko-zeta** [comment]
I made disk with this command:
`mkfs -t xfs /dev/nvme1n1`

**Comment by den-crane** [comment]
I would add one more replica to one of shards with ext4 and check how it will behave

**Comment by alexey-milovidov** [comment]
We use only ext4 in production.
XFS might have bugs.
