### ISSUE TITLE
The error message of modify the storage policy is incorrect

### ISSUE THREAD

**Issue by xiaolei565** [ClickHouse/ClickHouse#51516]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

**How to reproduce**

- ClickHouse 23.6.1.1
- master branch

```
--the config of storage_policy
<clickhouse>
    <storage_configuration>
    <disks>
        <disk_01>
            <path>/mnt/data1/ckdata/</path>
        </disk_01>
        <disk_02>
            <path>/mnt/data2/ckdata/</path>
        </disk_02>
    </disks>
    <policies>
        <jbod_policies>
            <volumes>
                <jbod_volume>
                   <disk>disk_01</disk>
                </jbod_volume>
            </volumes>
            <move_factor>0.2</move_factor>
        </jbod_policies>
        <jbod_policies_new>
            <volumes>
                <jbod_volume_new>
                   <disk>disk_02</disk>
                </jbod_volume_new>
            </volumes>
            <move_factor>0.2</move_factor>
         </jbod_policies_new>
    </policies>
  </storage_configuration>
</clickhouse>

-- create table sql
CREATE TABLE default.storage_policy_test
(
    `name` String,
    `age` String
)
ENGINE = MergeTree
ORDER BY name
SETTINGS storage_policy = 'jbod_policies', index_granularity = 8192

-- modify storage policy sql
ALTER TABLE default.storage_policy_test MODIFY SETTING storage_policy = 'jbod_policies_new'

-- error message
Received exception from server (version 23.6.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: New storage policy `jbod_policies` shall contain disks of old one. (BAD_ARGUMENTS)
```

the error message of modify storage policy is incorrect ，the message of 'New storage policy' should be jbod_policies_new

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [[clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80)](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by ddna1021** [comment]
I 'd like to do this work

**Comment by xiaolei565** [comment]
@alexey-milovidov @evillique why my pr canot be merged？

**Comment by evillique** [comment]
@xiaolei565 Sorry, did not notice your PR. You can however update your branch to the latest master and fix the article in the error message that I didn't notice was absent :)

**Comment by xiaolei565** [comment]
@evillique  That's all right. I've already resolved the conflict
