### ISSUE TITLE
Handling Zookeeper rebalancing after failover

### ISSUE THREAD

**Issue by devoxel** [ClickHouse/ClickHouse#51524]
**Use case**

We have a clickhouse cluster configured with `<zookeeper_load_balancing>nearest_hostname</zookeeper_load_balancing>`. This means that when a zookeeper node goes down, clickhouse nodes will move to the next available replica. This is as expected and a useful strategy in our context.

After this failover scenario happens, we can be left with a large imbalance of watchers in zookeeper. This is made worse by our clickhouse nodes being vertically large. This triples the P90 latency of our zookeeper nodes (from 15ms to 45ms).

In order to fix this, we currently have to manually rolling-restart the clickhouse cluster; or restart just the clickhouse instance that encountered the zookeeper issue.

**Describe the solution you'd like**

It would be useful if clickhouse had a `zookeeper_failover_timeout` setting. After the specified time passes after a fail-over event, the clickhouse node would timeout the connection and reconnect using the original strategy. This would rebalance the connections.

This would have the caveat that it would create churn, especially in cases where the zookeeper client is no longer reachable. We could expose a `zookeeper_failover_timeout_retries` config to limit the number of times this would occur in the runtime of a clickhouse process; or you could simply limit this failover timeout to happening once.

**Alternatives Considered**

One alternative is to have the `nearest_hostname` behave more like the normal `load_balancing` setting; have a rolling window of error counts and re-select zookeeper nodes based on that. However I don't think this really works unless you maintain error counts of zookeeper somehow in a distributed fashion; and that sounds over-complicated for this.

**Comment by devoxel** [comment]
I think my solution would require forcing session refreshes, but it is limited to only happening after failover events.

**Comment by tavplubix** [comment]
I think it's resolved by https://github.com/ClickHouse/ClickHouse/pull/50424
