### ISSUE TITLE
Method getDataAt is not supported for Nullable(UInt8) in case if value is NULL: While processing cityHash64

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#51541]
Use case: calculating the row checksum (when some rows have nulls) https://fiddle.clickhouse.com/298c92ff-7ea5-48e8-8f3d-862501d22c05 

tiny repro:
```
select cityHash64(tuple(Null::Nullable(UInt8)))
```

See PR: https://github.com/ClickHouse/ClickHouse/pull/40195

It used to work before version 22.9, and it was also backported to older versions. For example: 22.8.5 - works, 22.8.6 - fails with exception

**Comment by nickitat** [comment]
#48623
