### ISSUE TITLE
Add parseDateTimeBestEffortUS function.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5157]
In contrast to `parseDateTimeBestEffort`, prefer US style (mm/dd/yyyy) in case of ambiguouty.

**Comment by ucasFL** [comment]
Do we support mm.dd.yy or mm-dd-yy etc in US style, or just support mm/dd/yyyy?

**Comment by alexey-milovidov** [comment]
Let's prefer "US" order for all variants if `parseDateTimeBestEffortUS` is called...
(But if YYYY is the first, always treat the following as month and day.)

I'm not 100% sure what is better. In most cases, people write US format using slash as a separator.
From Wikipedia:

> The most commonly used separator in the all-numeric form is the slash (/), although the hyphen (-) and period (.) have also emerged in the all-numeric format recently due to globalization. 

https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_States
