### ISSUE TITLE
MacOS M1 can compile but not run

### ISSUE THREAD

**Issue by xiedeyantu** [ClickHouse/ClickHouse#51576]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

```
dyld[71800]: dyld cache '/System/Library/dyld/dyld_shared_cache_arm64e' not loaded: syscall to map cache into shared region failed
dyld[71800]: Library not loaded: '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation'
  Referenced from: '/Users/jensen/code/ClickHouse/build/programs/clickhouse'
  Reason: tried: '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation' (no such file), '/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation' (no such file)
[1]    71800 abort      ./clickhouse
```

**Operating system**
MacOS M1 12.6.7
> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**
cmake version 3.26.4
**Ninja version**
1.11.1
**Compiler name and version**
Homebrew clang version 16.0.6
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
**Full cmake and/or ninja output**

**Comment by alexey-milovidov** [comment]
You can download the pre-built version of ClickHouse as follows:
```
curl https://clickhouse.com/ | sh
```

The same command works on various OS and architectures.

**Comment by xiedeyantu** [comment]
> You can download the pre-built version of ClickHouse as follows:
> 
> ```
> curl https://clickhouse.com/ | sh
> ```
> 
> The same command works on various OS and architectures.

But I want to complete the compilation.

**Comment by rschu1ze** [comment]
This is unlikely a problem with the ClickHouse build.

@xiedeyantu Did you follow the steps on https://clickhouse.com/docs/en/development/build-osx? Is xcode installed?

Also, if you search online for `syscall to map cache into shared region failed` and `Library not loaded`, you will find many issues where environment paths are messed up. Does "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation" exist on your system?

**Comment by xiedeyantu** [comment]
> This is unlikely a problem with the ClickHouse build.
> 
> @xiedeyantu Did you follow the steps on https://clickhouse.com/docs/en/development/build-osx? Is xcode installed?
> 
> Also, if you search online for `syscall to map cache into shared region failed` and `Library not loaded`, you will find many issues where environment paths are messed up. Does "/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation" exist on your system?

The new system does not have this directory, and ninja compilation will report this error, while cmake build compilation will not report it. However, using vscode's codelldb debugging will cause problems.

**Comment by rschu1ze** [comment]
> The new system does not have this directory, and ninja compilation will report this error,

I am confused. The original report stated that compilation worked but then this sentence says that compilation failed.

Please check if some build prerequisite is missing on your system. Kindly check the [guide](https://clickhouse.com/docs/en/development/build-osx) again and make sure to have libraries/tools installed.

I suppose by "cmake build compilation" you mean CMake's configuration step.

> However, using vscode's codelldb debugging will cause problems.

Does the produced binary run at all or can you only not attach the debugger?

**Comment by qianyiwen2019** [comment]
I met the same problem, I builded clickhouse on my mac(macos monterey 12.3) following https://clickhouse.com/docs/en/development/build-osx, the build succeed.

but when I tried to to run it by "./build/programs/clickhouse-server --config-file ./programs/server/config.xml", it failed with error:

dyld[76457]: dyld cache '/System/Library/dyld/dyld_shared_cache_arm64e' not loaded: syscall to map cache into shared region failed
dyld[76457]: Library not loaded: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  Referenced from: /Users/xushicai/Documents/projects/clickhouse/ClickHouse/build/programs/clickhouse
  Reason: tried: '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation' (no such file), '/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation' (no such file)
zsh: abort      ./build/programs/clickhouse-server --config-file ./programs/server/config.xml

**Comment by korowa** [comment]
FWIW (just in case anyone will run into this): there are some issues with running 2G+ binaries on MacOS arm64 (the best explanation I've found is [this one](https://forums.approximatrix.com/viewtopic.php?id=919)).

Confirmed by producing 2G binary with `-DCMAKE_BUILD_TYPE=Debug -DDEBUG_O_LEVEL=0`, and facing this issue. As a workaround -- could be fixed by stripping debug symbols from the binary and keeping them separately:
```sh
# where ./clickhouse is a result binary
dsymutil ./clickhouse
strip -S ./clickhouse

# Alternative command with lower result binary size, but requiring more time to execute
strip -S -x ./clickhouse
```
