### ISSUE TITLE
Cannot write to finalized buffer

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#51589]
https://s3.amazonaws.com/clickhouse-test-reports/51545/006d05c6a7aacc6f1c321822725389778b8c299c/stress_test__ubsan_.html

```
 [ 4833 ] {c94f5a38-e2b2-4dbe-a1af-94917027dbdd} <Fatal> : Logical error: \'Cannot write to finalized buffer\'.
 [ 11470 ] {} <Fatal> BaseDaemon: ########################################
 [ 11470 ] {} <Fatal> BaseDaemon: (version 23.6.1.1, build id: 7387C1278E530F0251CB21E83FFBEE23A48DBF6D, git hash: 9b10d14ec57fc38c2e305563e9b13d84563a471f) (from thread 4833) (query_id: c94f5a38-e2b2-4dbe-a1af-94917027dbdd) (query: SELECT greatest(toUInt8(1), toUInt8(intHash64(number))) FROM system
 [ 11470 ] {} <Fatal> BaseDaemon: 
 [ 11470 ] {} <Fatal> BaseDaemon: Stack trace: 0x00007f0df3baa00b 0x00007f0df3b89859 0x000055d817626f68 0x000055d8176278ce 0x000055d80afb7eaf 0x000055d80afb7e27 0x000055d8271b0b48 0x000055d8271b4cbf 0x000055d82728079e 0x000055d828a2fd3e 0x000055d828a30e7a 0x000055d828cc5bd0 0x000055d828cc0cf1 0x0000
 [ 11470 ] {} <Fatal> BaseDaemon: 3. gsignal @ 0x00007f0df3baa00b in ?
 [ 11470 ] {} <Fatal> BaseDaemon: 4. abort @ 0x00007f0df3b89859 in ?
 [ 11470 ] {} <Fatal> BaseDaemon: 5. ./build_docker/./src/Common/Exception.cpp:49: DB::abortOnFailedAssertion(String const&) @ 0x0000000037833f68 in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 6. ./build_docker/./src/Common/Exception.cpp:93: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000378348ce in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 7. DB::Exception::Exception<char const (&) [33], void>(int, char const (&) [33]) @ 0x000000002b1c4eaf in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 8. DB::WriteBuffer::write(char const*, unsigned long) @ 0x000000002b1c4e27 in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 9. ./build_docker/./src/IO/WriteHelpers.h:0: DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000473bdb48 in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 10.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: std::unique_ptr<DB::OpenTelemetry::TracingContextHolder, std::default_delete<DB::OpenTelemetry::TracingContextHolder>>::operator bool[abi:v15000]() const
 [ 11470 ] {} <Fatal> BaseDaemon: 10. ./build_docker/./src/Server/HTTPHandler.cpp:1068: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000473c1cbf in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 11. ./build_docker/./src/Server/HTTP/HTTPServerConnection.cpp:69: DB::HTTPServerConnection::run() @ 0x000000004748d79e in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 12. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000048c3cd3e in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 13.1. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: std::unique_ptr<Poco::Net::TCPServerConnection, std::default_delete<Poco::Net::TCPServerConnection>>::reset[abi:v15000](Poco::Net::TCPServerConnection*)
 [ 11470 ] {} <Fatal> BaseDaemon: 13.2. inlined from ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:259: ~unique_ptr
 [ 11470 ] {} <Fatal> BaseDaemon: 13. ./build_docker/./base/poco/Net/src/TCPServerDispatcher.cpp:116: Poco::Net::TCPServerDispatcher::run() @ 0x0000000048c3de7a in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 14. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() @ 0x0000000048ed2bd0 in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 15.1. inlined from ./build_docker/./base/poco/Foundation/include/Poco/AutoPtr.h:205: Poco::AutoPtr<Poco::ThreadImpl::ThreadData>::operator->()
 [ 11470 ] {} <Fatal> BaseDaemon: 15. ./build_docker/./base/poco/Foundation/src/Thread_POSIX.cpp:350: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000048ecdcf1 in /usr/bin/clickhouse
 [ 11470 ] {} <Fatal> BaseDaemon: 16. ? @ 0x00007f0df3d61609 in ?
 [ 11470 ] {} <Fatal> BaseDaemon: 17. __clone @ 0x00007f0df3c86133 in ?
 [ 11470 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
 [ 11470 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
 [ 1628 ] {} <Fatal> Application: Child process was terminated by signal 6.
 [ 4833 ] {c94f5a38-e2b2-4dbe-a1af-94917027dbdd} <Fatal> : Logical error: \'Cannot write to finalized buffer\'.
```

**Comment by CheSema** [comment]
Nice

**Comment by CheSema** [comment]
this is real bug. Thank you guys!

https://github.com/ClickHouse/ClickHouse/blob/4686eb22c1ed59679ed2e03ad07223c3f91677b8/src/Server/HTTPHandler.cpp#L907

Here should not be finalize call. Because it might trigger finalize call for used_output.out_maybe_compressed. Which are going to be used for send error message.
The hardest thing is to write a test now.

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/33d7cca9df0ed9d91c3c8ed3009f92142ce69f9d/stress_test__debug_.html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/52559/673f7e038b3d3bd37b4f85c3e8144dbeb13f155d/upgrade_check__asan_.html

**Comment by CheSema** [comment]
No fails for a long time

https://play.clickhouse.com/play?user=play#V0lUSCAKWwooJ2hhZF9yZW1vdmFsX2NzbicsICdodHRwczovL2dpdGh1Yi5jb20vQ2xpY2tIb3VzZS9DbGlja0hvdXNlL2lzc3Vlcy81MTMzOScpLAooJ05vIHVzZXIgaW4gY3VycmVudCBjb250ZXh0JywgJ2h0dHBzOi8vZ2l0aHViLmNvbS9DbGlja0hvdXNlL0NsaWNrSG91c2UvaXNzdWVzLzU1MDQxJyksCignREI6OkNodW5rOjpjbG9uZUVtcHR5Q29sdW1ucycsICdodHRwczovL2dpdGh1Yi5jb20vQ2xpY2tIb3VzZS9DbGlja0hvdXNlL2lzc3Vlcy81NTE1MScpLAooJ1dyaXRlQnVmZmVyRnJvbUhUVFBTZXJ2ZXJSZXNwb25zZTo6bmV4dEltcGwnLCAnaHR0cHM6Ly9naXRodWIuY29tL0NsaWNrSG91c2UvQ2xpY2tIb3VzZS9pc3N1ZXMvNTUxNDgnKSwKKCdUaGUgYXNzb2NpYXRlZCBwcm9taXNlIGhhcyBiZWVuIGRlc3RydWN0ZWQnLCdodHRwczovL2dpdGh1Yi5jb20vQ2xpY2tIb3VzZS9DbGlja0hvdXNlL2lzc3Vlcy81NTE1NScpLAooJ0ludGVnZXIgZGl2aWRlIGJ5IHplcm8nLCAnaHR0cHM6Ly9naXRodWIuY29tL0NsaWNrSG91c2UvQ2xpY2tIb3VzZS9pc3N1ZXMvNTUxNTcnKSwKKCdpcyBPdXRkYXRlZCBhbmQgaGFzIGNyZWF0aW9uIFRJRCcsJ2h0dHBzOi8vZ2l0aHViLmNvbS9DbGlja0hvdXNlL0NsaWNrSG91c2UvaXNzdWVzLzUzNjE1JyksCignXCdpbnNlcnRlZFxcJywgJ2h0dHBzOi8vZ2l0aHViLmNvbS9DbGlja0hvdXNlL0NsaWNrSG91c2UvaXNzdWVzLzU1MTYzJyksCignU2hhcmQgbnVtYmVyIGlzIGdyZWF0ZXIgdGhhbiBzaGFyZCBjb3VudCcsICdodHRwczovL2dpdGh1Yi5jb20vQ2xpY2tIb3VzZS9DbGlja0hvdXNlL2lzc3Vlcy81NDMxNCcpLAooJ0RCOjpNZXJnZVRyZWVNYXJrc0xvYWRlcjo6bG9hZE1hcmtzKCknLCAnaHR0cHM6Ly9naXRodWIuY29tL0NsaWNrSG91c2UvQ2xpY2tIb3VzZS9pc3N1ZXMvNTQ1MDUnKQpdIEFTIGtub3duCgpzZWxlY3QgCmFycmF5Sm9pbihhcnJheUZpbHRlcih5LT5pc05vdE51bGwoeSksIGFycmF5TWFwKHgtPiBtYXRjaCh0ZXN0X2NvbnRleHRfcmF3LCB4LjEpID8geC4yIDogbnVsbCwga25vd24pKSBhcyBhID09IFtdID8gWyd1bmtub3duJ10gOiBhKSBhcyBpc3N1ZSwKcmVwbGFjZU9uZShyZXBvcnRfdXJsLCAnLmh0bWwnLCAnL2ZhdGFsX21lc3NhZ2VzLnR4dCcpIGFzIGZhdGFsX2Vycm9yX3VybCwgdGVzdF9jb250ZXh0X3JhdywgY2hlY2tfbmFtZSwgY29tbWl0X3NoYSwgY2hlY2tfc3RhcnRfdGltZSwgdGVzdF9zdGF0dXMsIHJlcG9ydF91cmwKZnJvbSBjaGVja3MgCndoZXJlIAp0ZXN0X3N0YXR1cyBub3QgaW4gWydPSycsICdTVUNDRVNTJywgJ1NLSVBQRUQnLCAnWEZBSUwnLCAnWEVSUk9SJ10gYW5kIAp0ZXN0X25hbWUgbGlrZSAnRmF0YWwlJyAKYW5kIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCmFuZCBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gaW50ZXJ2YWwgMzAgZGF5CmFuZCB0ZXN0X2NvbnRleHRfcmF3IGxpa2UgJyVDYW5ub3Qgd3JpdGUgdG8gZmluYWxpemVkIGJ1ZmZlciUnCmFuZCBjb21taXRfc2hhIG5vdCBpbiBbCidjOTExYzhkYWY0YmQ2MjYzMTVkNmI2N2YzNWVkN2VhMGY2YzQ3NmNlJywKJzExOGEwNjhhNGQxODhjYTIwMGNkNDY4YmU3NzQ1NzQ1ZDg2OGVmYmInLAonNWE1OTk2MTBjYWEwNDAxMWYzYTdmYjIwZWYxODU5YTlhNmJmMTEwZicsCiczNzEyM2QwNmIzOWI5ZDljZDc2MThiN2ZkODUyMWUzMTI3MDFjOTZhJywKJzc3ZGQyYTU1NmEzZDhkZDNkZmZhN2I3MzdiODM1NmNiOWI4M2MzODInLAonZWFjMmQyODZiNGFkMTNkZjAyNGExYzY3MDIyNWY3NGFmOGM0MTY4YicsCicyM2Q2N2ZjMmE0NmUwOTQyYmVlYmNkMTllN2Q5YzkyZmExMzIxOGNkJywKJzczNWY1NDNhZWIwY2ExZmM4ZGQ2MzBiYjAxZTFjMTFiZmY5OTRiM2YnLAonNDMzNzZmMDAzN2JhMzIzMTRjMGE0MmI1YWY5OTg2NTdmZDRkNGJlMScsCic4NjIyMzY5OWJlOTc3YWI5ZmJkMGFiZjg1MGRkNDAzMDNkMjNkNmI4JywKJ2MwYTQzZGY3NDljODI3Y2UxM2FiYjAxNWZhY2E0YWQ4YWI1MjQ2ODUnLAonNDcwY2UzNDQ0Y2Y5Y2UwM2QzZDE1NjA2YWEwYzI5MGUwMmZiY2VmOCcsCidlZmM0MGIzZTMwYTc2OTcxNzE3NzczMzZhZDVmN2MwOGNjN2NlZTMxJywKJ2EwZDI1ZmRkNTQzZWI2MWJmOGE3MGQxMjU0OTU2NTc5NGQzMzRmZmQnLAonZDY4MTQ2MjY0NjE0NWJlMjcxMTQyYmFkMjhkYmY3N2Q0NDhhOTNmMicKCl0Kb3JkZXIgYnkgaXNzdWUgZGVzYywgY2hlY2tfc3RhcnRfdGltZSBkZXNjCg==
