### ISSUE TITLE
Got exception when i'm trying to converte data from zookeeper to clickhouse-keeper

### ISSUE THREAD

**Issue by KyoUK4n** [ClickHouse/ClickHouse#51584]
* clickhosue version: `23.3.6.7-lts`

* clickhouse-keeper version: `23.3.6.7-lts`

* zookeeper version: `3.6.1`

* issue: 

i'm trying to use `clickhouse-keeper-converter`  converte data from zookeeper, but it doesn't work.

here is the exception:

```c++
Code: 48. DB::Exception: Not implemented operation 16. (NOT_IMPLEMENTED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe1dc395 in /usr/bin/clickhouse
1. ? @ 0xcee79ef in /usr/bin/clickhouse
2. ? @ 0x14f3ee8a in /usr/bin/clickhouse
3. DB::deserializeTxn(DB::KeeperStorage&, DB::ReadBuffer&, Poco::Logger*) @ 0x14f3dee1 in /usr/bin/clickhouse
4. DB::deserializeLogAndApplyToStorage(DB::KeeperStorage&, String const&, Poco::Logger*) @ 0x14f3f541 in /usr/bin/clickhouse
5. DB::deserializeLogsAndApplyToStorage(DB::KeeperStorage&, String const&, Poco::Logger*) @ 0x14f40c99 in /usr/bin/clickhouse
6. mainEntryClickHouseKeeperConverter(int, char**) @ 0xe3fee1f in /usr/bin/clickhouse
7. main @ 0x89e2593 in /usr/bin/clickhouse
8. __libc_start_main @ 0x7fc12ac8e083 in ?
9. _start @ 0x803136e in /usr/bin/clickhouse
 (version 23.3.6.7 (official build))
```

i also check this exception in the code, i found this:
![image](https://github.com/ClickHouse/ClickHouse/assets/18624741/0cfa8bcd-84b7-4380-962a-cb2d273610d6)

it seems the converter can't deserialize the type `16`, what type `16` means? and how can i fix this?

**Comment by tavplubix** [comment]
16 is for `reconfig` (https://github.com/apache/zookeeper/blob/77c1e4c872e7ff09b71345edc67f176ed5e68380/zookeeper-server/src/main/java/org/apache/zookeeper/ZooDefs.java#L68C16-L68C16), it's not supported by the converter 

Possible workaround: avoid reconfiguring ZooKeeper for a while, wait until the log is rotated (so there are no `reconfig` entries anymore), try again

**Comment by KyoUK4n** [comment]
@tavplubix Thanks for reply, I've been converted successfully after several attempts.
