### ISSUE TITLE
`select hasAll([1], ['a'])` raises an exception rather than returns 0 as documented

### ISSUE THREAD

**Issue by niebayes** [ClickHouse/ClickHouse#51581]
**Describe what's wrong**

Executing `select hasAll([1], ['a'])` would raise an exception.

> SELECT hasAll([1], ['a'])
Query id: c809db5e-e770-4eb3-a73e-68a7561acd47
0 rows in set. Elapsed: 0.442 sec.
Received exception:
Code: 386. DB::Exception: There is no supertype for types UInt8, String because some of them are String/FixedString and some of them are not: While processing hasAll([1], ['a']). (NO_COMMON_TYPE)

However, the [document](https://clickhouse.com/docs/en/sql-reference/functions/array-functions#hasall) says it would returns 0.

**Comment by alexey-milovidov** [comment]
This is the correct behavior. Documentation has to be updated.

**Comment by Mash707** [comment]
@alexey-milovidov I am new to open source and would to contribute to this issue. Could give some details as to what needs to be updated in the documentation. 
As per the documentation select hasAll([1], ['a']) should return 0 .
