### ISSUE TITLE
test_alter_moving_garbage/test.py::test_create_table[False-False] flacky

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#51605]
Cannot swap part '...', no such active part..

example on master
https://s3.amazonaws.com/clickhouse-test-reports/0/78c1f4bb52f6a7d8555b80c00de2cb0d52245080/integration_tests__asan__[1_6].html

stats:
https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2FsdGVyX21vdmluZ19nYXJiYWdlL3Rlc3QucHk6OnRlc3RfY3JlYXRlX3RhYmxlW0ZhbHNlLUZhbHNlXSUnIGFuZCB0ZXN0X3N0YXR1cyBpbiAoJ0ZBSUwnLCAnRkxBS1knKSBncm91cCBieSBkIG9yZGVyIGJ5IGQgZGVzYw==

**Comment by Algunenano** [comment]
Duplicated of https://github.com/ClickHouse/ClickHouse/issues/51342
