### ISSUE TITLE
Publish obfuscated hits_10m, hits_100m, hits_1000m datasets.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5162]
For engineers from Intel that will do low level optimizations for us,
and for engineers from MariaDB ColumnStore to help them tune performance of their system.

**Comment by akuzm** [comment]
hits_100m is already done, link in the docs https://clickhouse.yandex/docs/en/getting_started/example_datasets/metrica/

Only hits_1000m is left.

**Comment by alexey-milovidov** [comment]
Ok, it's enough.
