### ISSUE TITLE
clickhouse-keeper-client cannot read `number-nodes`

### ISSUE THREAD

**Issue by KyoUK4n** [ClickHouse/ClickHouse#51647]
I'm trying to check data in `clickhouse-keeper` through `clickhouse-keeper-client`.

I cannot input numbers to the cli?
![image](https://github.com/ClickHouse/ClickHouse/assets/18624741/252ca50d-f218-4889-8d1b-d62373851bf6)

The problem is that the sub entries of data are under the `shard` node, which will always be numbers.

Please fix this.

---

By the way, It seems like the `-` also not support.
![image](https://github.com/ClickHouse/ClickHouse/assets/18624741/a8367de7-c31e-4078-a7cc-d62c14544973)

**Comment by pufit** [comment]
Fixed here https://github.com/ClickHouse/ClickHouse/pull/51359
