### ISSUE TITLE
How to understand the 22.8 version?

### ISSUE THREAD

**Issue by beijishiqidu** [ClickHouse/ClickHouse#51675]
Hi All, 
I looked up the changelog on ClickHouse's official website. 

Example: https://clickhouse.com/docs/en/whats-new/changelog/2022#-clickhouse-release-228-2022-08-18

However, I found that there are many LTS tags for the current ClickHouse version 22.8. The corresponding versions of these tags are not described in the changelog.

v22.8.19.10-lts
v22.8.18.31-lts
v22.8.17.17-lts

So Which lts version should I use?  I also didn't find a description of the different tags, only a 22.8 changelog.

**Comment by Algunenano** [comment]
> So Which lts version should I use?

The latest (currently `v22.8.17.17-lts`). But consider 23.3, which is a newer LTS.

> I also didn't find a description of the different tags, only a 22.8 changelog.

Minor releases don't have a changelog. The only way that I know of to see differences is to check the commits.

**Comment by genzgd** [comment]
All releases of version 22.8 are LTS (Long Term Support).  That means for one year v22.8 will get all major bug fixes.  To get the latest bug fixes, you should always use the newest version.  In most cases any bugs fixes reported  in the ChangeLog for a new release  will be backported to the LTS versions shortly after that new release.

So the basic rule of thumb is you should use the latest LTS release to get the latest bug fixes, and it is guaranteed to backward compatible with previous versions of 22.8.

Trying to maintain a human created change log for all patch versions of all releases would be essentially impossible.  There are various tutorials on the web how to generate one between two tags using the git command line using commits/merged pull requests.  (In theory could automate that process on a web page or in Github itself, but I'm not aware  of such a tool being available.)

**Comment by den-crane** [comment]
and they pretty readable https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelogs/v22.8.19.10-lts.md

**Comment by genzgd** [comment]
So I'm guessing it was automated, nice :)
