### ISSUE TITLE
readBytes(and selectedBytes in ProfileEvents) is larger than the column total uncompressedSize

### ISSUE THREAD

**Issue by wxybear** [ClickHouse/ClickHouse#51670]
**How to reproduce**

* Which ClickHouse server version to use
ClickHouse server version 23.5.3.24 (official build).
* Which interface to use, if matters
just simplest SELECT statement
* Non-default settings, if any
no
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE default.log
(
    `timestamp` DateTime64(0, 'Asia/Shanghai'),
    `hostname` String CODEC(ZSTD(1)),
    `source` String CODEC(ZSTD(1)),
    `path` String CODEC(ZSTD(1)),
    `data` Map(String, String) CODEC(ZSTD(1)),
    INDEX idx_data mapKeys(data) TYPE bloom_filter(0.001) GRANULARITY 1,
    INDEX idx_hostname hostname TYPE bloom_filter GRANULARITY 1,
    INDEX idx_source source TYPE bloom_filter GRANULARITY 1,
    INDEX idx_path path TYPE bloom_filter GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toDate(timestamp)
ORDER BY timestamp
SETTINGS index_granularity = 8192
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
![image](https://github.com/ClickHouse/ClickHouse/assets/25052411/002e778d-1819-4b2b-b128-0ceb02d57295)
![image](https://github.com/ClickHouse/ClickHouse/assets/25052411/9c6ab383-c054-4bbc-9068-007a7e66b37f)
**Column data** is some kv(string to string) fields, **RequestId** is one of them
* Queries to run that lead to unexpected result
select * from log where data['RequestId'] = 'abcdefghijk'
**Expected behavior**
![image](https://github.com/ClickHouse/ClickHouse/assets/25052411/3ee7fb7c-60c2-4913-b170-4a78894a24d8)
**column data**'s uncompressedSize is 2.29T，but if I select some data from column data, readBytes is 4.36T... the result of byteSize func is also larger than the sum uncompressed size of system tables(parts and parts_column)
![image](https://github.com/ClickHouse/ClickHouse/assets/25052411/44bfae35-37a7-499c-ae98-22b5b77dbea5)
I think these two numbers should be close... I've looked at some code briefly and still don't quite get it. If this is normal, I hope you can tell me why. 
Thanks!

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by Algunenano** [comment]
The bytes in system.tables / system.columns are the bytes that the column occupies after serialization (but before compression) when stored into disk.

`byteSize` and system.query_log includes the size that the column occupies **in memory**, which includes padding and other. For example, in the case of a String column, the byte size is the size to store all of the strings plus the size to hold the offsets (to know where each string starts). So a string of 10 ascii chars will take 8 bytes + 1 NULL char + 8 bytes for offset = 19 bytes:

```
WITH temp AS
    (
        SELECT '1234567890' AS a
    )
SELECT
    a,
    byteSize(a)
FROM temp

Query id: 1adee7d3-de65-41cd-8c6a-3050a98637ed

┌─a──────────┬─byteSize(a)─┐
│ 1234567890 │          19 │
└────────────┴─────────────┘
```

For Map(String, String) the size is size of the underlying tuple, which is the sum of the 2 strings. I.e. you are paying for storing 2 offsets, which are not needed when storing to disk but are needed when keeping the data in memory.

**Comment by wxybear** [comment]
I had some misunderstandings before, thinking that the serialized data(serializeBinaryBulk) size also includes str and str size before compression, and the final size is consistent with ColumnString byteSize(); I read the code carefully and found that when serializing, str size is stored in var int, which should be the largest difference(Uint64 <-> varint)
