### ISSUE TITLE
Does ‘async_insert’ feature only works on http protocol?

### ISSUE THREAD

**Issue by Mum1996** [ClickHouse/ClickHouse#51702]
Here are two java jdbc client: ClickHoue-java and ClickHouse-native-jdbc
I have read the the doc:  https://clickhouse.com/docs/en/cloud/bestpractices/asynchronous-inserts

It seem that async_insert can only works on http protocol.
How can I use 'async_insert' feature by useing ClickHouse-native-jdbc?
(Buffer table has a trouble question:  the insert function will be blocked when the buffer flush data from memory to disks)

**Comment by den-crane** [comment]
async_insert initiated by the Clickhouse server for HTTP protocol.
For TCP protocol the client should support / form protocol packets in a way of async_insert.
So ClickHouse-native-jdbc driver have to support and initiate async_insert.
