### ISSUE TITLE
404 by the links to description templates

### ISSUE THREAD

**Issue by velavokr** [ClickHouse/ClickHouse#51706]
https://github.com/ClickHouse/ClickHouse/blob/master/docs/README.md#description-templates

All of the template links are 404, like on the screenshot.

![Screenshot from 2023-07-02 11-46-44](https://github.com/ClickHouse/ClickHouse/assets/10815678/3021c03a-c4ec-4d4e-bf48-b8188b8341e4)

**Comment by Mash707** [comment]
#51711

**Comment by Mash707** [comment]
I have fixed the links and given a PR

**Comment by Mash707** [comment]
> > I have fixed the links and given a PR
> 
> I think the documents you've linked to are the documentation itself, not documentation templates. Maybe it'll be better to also change the title from `Templates` to `Examples` to be more accurate.

I misunderstood the issue. In the Clickhouse-docs repo I managed to find one article related to how the docs should be written. https://github.com/ClickHouse/clickhouse-docs/blob/main/contrib-writing-guide.md

**Comment by DanRoscigno** [comment]
I can't find the commit that removed the templates, but I found the most recent copies of the files and will pop them back in.
