### ISSUE TITLE
[custom build] Received signal Segmentation fault: 11 

### ISSUE THREAD

**Issue by zwangsheng** [ClickHouse/ClickHouse#51727]
> You have to provide the following information whenever possible.

**Describe what's wrong**

When i start clickhouse server, will face the following issue and server will exit.

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

I face the issue with version `22.11.1.543` and updated to `23.7.1.123` still face this.

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.
```log
2023.07.03 18:22:20.246437 [ 27513 ] {} <Fatal> BaseDaemon: ########################################
2023.07.03 18:22:20.246460 [ 27513 ] {} <Fatal> BaseDaemon: (version 23.7.1.123 (official build), build id: , git hash: ce5ca7d2a5e85a027316d44b1c0a6ae646133872) (from thread 27419) (query_id: 6c2f7305-49ea-4809-af60-ef4750eb24f0) (query: ) Received signal Segmentation fault: 11 (11)
2023.07.03 18:22:20.246469 [ 27513 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: . Attempted access has violated the permissions assigned to the memory area.
2023.07.03 18:22:20.246473 [ 27513 ] {} <Fatal> BaseDaemon: Stack trace: 0x00000001956abec4
2023.07.03 18:22:20.246477 [ 27513 ] {} <Fatal> BaseDaemon: 0. 0x1956abec4
2023.07.03 18:22:20.246485 [ 27513 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2023.07.03 18:22:20.248353 [ 27513 ] {} <Fatal> BaseDaemon: No settings were changed
2023.07.03 18:22:20.250530 [ 27514 ] {} <Fatal> BaseDaemon: ########################################
2023.07.03 18:22:20.250538 [ 27514 ] {} <Fatal> BaseDaemon: (version 23.7.1.123 (official build), build id: , git hash: ce5ca7d2a5e85a027316d44b1c0a6ae646133872) (from thread 27413) (query_id: 654a198a-aeb1-4723-83ac-a1549128c46f) (query: ) Received signal Segmentation fault: 11 (11)
2023.07.03 18:22:20.250543 [ 27514 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: . Attempted access has violated the permissions assigned to the memory area.
2023.07.03 18:22:20.250546 [ 27514 ] {} <Fatal> BaseDaemon: Stack trace: 0x00000001956abec4
2023.07.03 18:22:20.250549 [ 27514 ] {} <Fatal> BaseDaemon: 0. 0x1956abec4
2023.07.03 18:22:20.250552 [ 27514 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2023.07.03 18:22:20.250569 [ 27514 ] {} <Fatal> BaseDaemon: No settings were changed
```

**Additional context**

> Add any other context about the problem here.

I changed one field value with String type.

**Comment by cangyin** [comment]
> I changed one field value with String type.

what field, is it a setting or a table column ?

 At least describe how to reproduce it.
 
You can use mother language if that's more comfortable for you.

**Comment by alexey-milovidov** [comment]
Custom, modified versions of ClickHouse are not supported.
