### ISSUE TITLE
Attempt to create ReplicatedMergeTree fails on subsequent attempts after an initial failed table creation

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/ClickHouse#5175]
We are creating some replicated merge tree tables and initially left out the sorting key, which led to this exception:

On `server-0`:

```
CREATE TABLE IF NOT EXISTS r0.events AS table_schemas.events
ENGINE = ReplicatedMergeTree('/clickhouse/clusters/counters_cluster/tables/{r0shard}/events', '{r0replica}')

Received exception from server (version 19.4.3):
Code: 42. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Storage ReplicatedMergeTree requires 5 to 6 parameters:
path in ZooKeeper,
replica name,
name of column with date,
[sampling element of primary key],
primary key expression,
index granularity
```

After fixing the sorting key (still on `server-0`) I was able to successfully create the table.

```
CREATE TABLE IF NOT EXISTS r0.events AS table_schemas.events
ENGINE = ReplicatedMergeTree('/clickhouse/clusters/counters_cluster/tables/{r0shard}/events', '{r0replica}')
ORDER BY (sourceID, hour)

Ok.

0 rows in set. Elapsed: 0.093 sec.
```

However, switching to `server-2` which has the other replica, running the create query led to this exception:

```
CREATE TABLE IF NOT EXISTS r1.events AS table_schemas.events
ENGINE = ReplicatedMergeTree('/clickhouse/clusters/counters_cluster/tables/{r1shard}/events', '{r1replica}')
PRIMARY KEY (sourceID, hour)
ORDER BY (sourceID, hour)

Received exception from server (version 19.4.3):
Code: 342. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Existing table metadata in ZooKeeper differs in sorting key expression. Stored in ZooKeeper: , local: sourceID, hour.

0 rows in set. Elapsed: 0.003 sec.
```

So I dropped the tables from both servers to be safe.  Checked zookeeper and saw that there was no metadata stored.

```
[zk: localhost:2181(CONNECTED) 17] ls /clickhouse/clusters/counters_cluster/tables/00
[]
```

Then I proceeded to create the tables on both servers again.  I started with `server-2` for no particular reason.  It was successful.

But when I went back to `server-0`, the creation failed with this error:

```
CREATE TABLE IF NOT EXISTS r0.events AS table_schemas.events
ENGINE = ReplicatedMergeTree('/clickhouse/clusters/counters_cluster/tables/{r0shard}/events', '{r0replica}')
ORDER BY (sourceID, hour)

Received exception from server (version 19.4.3):
Code: 342. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Existing table metadata in ZooKeeper differs in sorting key expression. Stored in ZooKeeper: sourceID, hour, local: .
```

Is there some other stale metadata I need to clear out from `server-0`?  I checked the replicas table after dropping the table and it was empty too.

**Comment by filimonov** [comment]
It sounds like something silly error, like connecting to bad zookeeper / bad commands copy& paste.  

Please repeat all the steps once again. Check the commands you execute are identical (even here, in issue i see they differ - in part of PRIMARY KEY (sourceID, hour)).  

If if not helps - please check the content of the following zookeeper nodes:

```
SELECT *
FROM system.zookeeper 
WHERE (path = '/clickhouse/clusters/counters_cluster/tables/00/events') AND (name = 'metadata')

SELECT *
FROM system.zookeeper 
WHERE (path = '/clickhouse/clusters/counters_cluster/tables/00/events/replicas/server-0') AND (name = 'metadata')

SELECT *
FROM system.zookeeper 
WHERE (path = '/clickhouse/clusters/counters_cluster/tables/00/events/replicas/server-1') AND (name = 'metadata')
```

**Comment by blinkov** [comment]
@abraithwaite, do you have any further questions?

**Comment by abraithwaite** [comment]
We can close this for now since it's pretty vague.  I do think that it would be helpful (mentioned it elsewhere, but can't remember where) I think it would be useful to include in that error message what the difference between zookeeper and the schema you're trying to apply is.  It's very difficult to debug zookeeper schema/metadata mismatches at this time.
