### ISSUE TITLE
Docker: init scripts execution order

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/ClickHouse#5176]
Setting up a distributed cluster, we ran into this:

```
12:42:34 $ kubectl logs counters-1
++ hostname -s
+ HOST=counters-1
+ [[ counters-1 =~ (.*)-([0-9]+)$ ]]
+ NAME=counters
+ ORD=1
+ cp /etc/clickhouse-server/config.d/1.sh /docker-entrypoint-initdb.d/
+ exec /entrypoint.sh
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Env variable is not set: CH_SHARD_R0
Env variable is not set: CH_REPLICA_R0
Env variable is not set: CH_SHARD_R1
Env variable is not set: CH_REPLICA_R1
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Include not found: networks
Include not found: networks
ClickHouse init process failed.
```

Digging in we noticed that the entrypoint script backgrounds the clickhouse process [1] before the non-executable environment scripts have been sourced [2] (which are for the macros).

[1] https://github.com/yandex/ClickHouse/blob/9e3c80d2edabb26caa4ddce26bdd0899453a5c7b/docker/server/entrypoint.sh#L55

[2] https://github.com/yandex/ClickHouse/blob/9e3c80d2edabb26caa4ddce26bdd0899453a5c7b/docker/server/entrypoint.sh#L73-L76

This causes the clickhouse server to exit non-zero and be rescheduled.

**Comment by filimonov** [comment]
docker-entrypoint-initdb.d is intended to initialize the database, so it starts clickhouse, run the init scripts, stops clickhouse, and after that run it again "normally".

Can I ask why do you need to run some scripts before that, and why those scripts fail? Why can't you use regular way of passing env to docker?

**Comment by abraithwaite** [comment]
Our environment variables for macros aren't being sourced before clickhouse quits.

We can't pass env through docker because we want the same configuration for each server in kubernetes (we're using a statefulset).  What this resulted in was us extending this image and copying in the few environment files we need to initialize the environments for each one.

```
13:26:33 $ cat docker/start-clickhouse.sh
#!/usr/bin/env bash

set -xe

HOST=`hostname -s`

if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
    NAME=${BASH_REMATCH[1]}
    ORD=${BASH_REMATCH[2]}
else
    echo "Failed to parse name and ordinal of Pod"
    exit 1
fi

cp /etc/clickhouse-server/config.d/$ORD.sh /docker-entrypoint-initdb.d/

exec /entrypoint.sh
```

**Comment by filimonov** [comment]
Sorry, I'm not following.

You need to run some script in a similar way to docker-entrypoint-initdb.d, but before first run of clickhouse? Right? 

If you had already modified the image it would be simpler also to source needed files from your modified entrypoint, as double start/stop of clickhouse in that scenario does not sound like a brilliant idea in such a production usecase.

**Comment by abraithwaite** [comment]
>  double start/and stop clickhouse does not sound like a brilliant idea in such a production usecase.

Totally agree.

But why even bother sourcing non-executable scripts if not to set the environment for clickhouse-server before it starts?  That's what I don't understand.

https://hub.docker.com/r/yandex/clickhouse-server/#how-to-extend-this-image

Perhaps the docs there should be updated.  Currently they say:

> After the entrypoint calls initdb it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service.

Maybe they should be:

> After the entrypoint calls initdb it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization _**immediately after starting the clickhouse-server.**_

**Comment by alexey-milovidov** [comment]
@filimonov As nothing has been done and no one is interested solving this issue, I will close it.

**Comment by abraithwaite** [comment]
I still care about this, I'm willing to do work to contribute, but got the impression that it was something that the core contributors wanted to address from the telegram channel IIRC.

**Comment by alexey-milovidov** [comment]
It will be very appreciated.

**Comment by filimonov** [comment]
> We still care about this, I'm willing to do work to contribute, but got the impression that it was something that the core contributors wanted to address from the telegram channel IIRC.
> 
> The point is to be able to set Clickhouse environment using environment files _before_ any scripts run. We can't do it at the statefulset level because we don't have the right information ahead of time. The only way for us to do it now is to extend the image, but we'd much rather not maintain an additional clickhouse docker image if possible.

Can you please sent PR with proposed changes?
