### ISSUE TITLE
when join table created with many LowCardinality(String) will cause Segmentation fault

### ISSUE THREAD

**Issue by foolfish3** [ClickHouse/ClickHouse#51770]
when join table created with many LowCardinality(String) ,Array(LowCardinality(String)) field, and fill a large number of rows,(about cost 150GB memory), will cause an error, make the clickhouse  Segmentation fault  and exit.

version 23.3

==================================================
this is log

2023.07.04 09:50:48.068076 [ 20697 ] {} <Fatal> BaseDaemon: ########################################
2023.07.04 09:50:48.068224 [ 20697 ] {} <Fatal> BaseDaemon: (version 23.3.2.37 (official build), build id: 2F54F417C7E2A810B4069A69AC827CF045266F9E) (from thread 20280) (query_id: 9b6e0427-2e10-4ebb-96ea-a4bd70846e60) (query: CREATE TABLE default.aaabbb ENGINE = Join(ANY, LEFT, uuid2) AS^M
            SELECT uuid2, `spå<8a><9f>æ<95><88>-15æ¥¼` FROM sop_e.entity_prod_91783_E_sputest_fix ^M
            WHERE `spå<8a><9f>æ<95><88>-15æ¥¼` != '') Received signal Segmentation fault (11)
2023.07.04 09:50:48.068283 [ 20697 ] {} <Fatal> BaseDaemon: Address: 0x7fdd057fefc0. Access: write. Attempted access has violated the permissions assigned to the memory area.
2023.07.04 09:50:48.069431 [ 20697 ] {} <Fatal> BaseDaemon: Stack trace: 0xcb8ef77 0xcb72e31 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107 0xcb74107

==================================================
this is create table SQL(all field almost LowCardinality(String) and `xxxx.name`  `xxxx.value`   is Array(LowCardinality(String)) )

CREATE TABLE sop_e.entity_prod_91783_E_sputest_tmpjoin ENGINE = Join(ANY, LEFT, source, item_id, sku_id, `trade_props.name`, `trade_props.value`, brand, name, key)
            AS
            SELECT clean_all_bid, clean_spuid, clean_pid, clean_arr_all_bid, clean_arr_spuid, clean_arr_pid, `clean_sp1`,`clean_sp2`,`clean_sp3`,`clean_sp4`,`clean_sp5`,`clean_sp6`,`clean_sp7`,`clean_sp9`,`clean_sp10`,`clean_sp11`,`clean_sp12`,`clean_sp13`,`clean_sp14`,`clean_sp15`,`clean_sp16`,`clean_sp17`,`clean_sp18`,`clean_sp19`,`clean_sp20`,`clean_sp21`,`clean_sp22`,`clean_sp23`,`clean_sp24`,`clean_sp41`,`clean_sp42`,`clean_sp43`,`clean_sp44`,`clean_sp45`,`clean_sp46`,`clean_sp47`,`clean_sp48`,`clean_sp49`,`clean_sp50`,`clean_sp51`,`clean_sp52`,`clean_sp53`,`clean_sp54`,`clean_sp55`,`clean_sp56`,`clean_sp57`,`clean_sp58`,`clean_sp59`,`clean_sp60`,`clean_sp61`, `clean_arr_sp1`,`clean_arr_sp2`,`clean_arr_sp3`,`clean_arr_sp4`,`clean_arr_sp5`,`clean_arr_sp6`,`clean_arr_sp7`,`clean_arr_sp9`,`clean_arr_sp10`,`clean_arr_sp11`,`clean_arr_sp12`,`clean_arr_sp13`,`clean_arr_sp14`,`clean_arr_sp15`,`clean_arr_sp16`,`clean_arr_sp17`,`clean_arr_sp18`,`clean_arr_sp19`,`clean_arr_sp20`,`clean_arr_sp21`,`clean_arr_sp22`,`clean_arr_sp23`,`clean_arr_sp24`,`clean_arr_sp41`,`clean_arr_sp42`,`clean_arr_sp43`,`clean_arr_sp44`,`clean_arr_sp45`,`clean_arr_sp46`,`clean_arr_sp47`,`clean_arr_sp48`,`clean_arr_sp49`,`clean_arr_sp50`,`clean_arr_sp51`,`clean_arr_sp52`,`clean_arr_sp53`,`clean_arr_sp54`,`clean_arr_sp55`,`clean_arr_sp56`,`clean_arr_sp57`,`clean_arr_sp58`,`clean_arr_sp59`,`clean_arr_sp60`,`clean_arr_sp61`, source, item_id, sku_id, `trade_props.name`, `trade_props.value`, brand, name, key
            FROM sop_c.entity_prod_91783_unique_items

**Comment by foolfish3** [comment]
![16874267205169](https://github.com/ClickHouse/ClickHouse/assets/35257284/735fec4b-ba38-4908-8222-67d8cd06e442)

**Comment by foolfish3** [comment]
two kinds of error log

**Comment by alexey-milovidov** [comment]
How to reproduce?

**Comment by foolfish3** [comment]
my db can reproduce the error, but is too big, will die on almost 150GB data every time. use less fields or insert less rows will make  error not happen.

**Comment by foolfish3** [comment]
change LowCardinality(String)  to String will cost much more memory,and no error occur

**Comment by Algunenano** [comment]
This might be related to https://github.com/ClickHouse/ClickHouse/pull/51064. Can you try the latest 23.3 (`v23.3.7.5-lts`)? Anything after 23.3.4 includes that fix.
