### ISSUE TITLE
MATERIALIZED column not working in Kafka engine

### ISSUE THREAD

**Issue by kmatt** [ClickHouse/ClickHouse#5177]
**Describe the bug**
Attempting to use a MATERIALIZED column with a constant in a Kafka engine table, but on SELECT the column is empty

**How to reproduce**
v19.1.14 revision 54413

```
CREATE TABLE kafka_test (
    data1 String,
    data2 String,
    constant String MATERIALIZED 'test'
) ENGINE = Kafka ...
```

**Expected behavior**

```
SELECT data1, data2, constant FROM kafka_test LIMIT 1;

'a', 'b', 'test'
'c', 'd', 'test'
```

**Error message and/or stacktrace**

```
SELECT data1, data2, constant FROM kafka_test LIMIT 1;

'a', 'b', ''
'c', 'd', ''
```

**Additional context**
Related to #5165 - attempting to put a topic name in the Kafka view.

**Comment by kmatt** [comment]
Using DEFAULT instead of MATERIALIZED results in same.

**Comment by abyss7** [comment]
As a quick workaround you can use `ALIAS` column instead.

**Comment by filimonov** [comment]
Support for Materialized columns in Kafka engine is highly questionable.
We expect the table with engine=Kafka should be a simple mapping of the data in the Kafka topic. 

If you need to have some derived columns, you can add them on the Materialized view level or with an alias.

My expectation about MATERIALIZED columns is that they should 'silently' and 'magically' appear in data. They should be materialized, i.e. stored physically. That's not possible for Kafka consumer. 

If you need a column which will always be calculated at the select time - that is how ALIAS columns work.
