### ISSUE TITLE
MySQL compatibility: SHOW KEYS output

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/ClickHouse#51782]
**Describe the unexpected behaviour**

BI tools such as QuickSight use `SHOW KEYS` queries to determine the primary keys of the dataset.
The output of the `SHOW KEYS` command is different from a real MySQL server.

"Real" MySQL:

```
mysql> SHOW KEYS FROM `cell_towers` FROM `mysql`;
+-------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| Table       | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
+-------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
| cell_towers |          0 | PRIMARY  |            1 | radio       | A         |           0 |     NULL |   NULL |      | BTREE      |         |               | YES     | NULL       |
| cell_towers |          0 | PRIMARY  |            2 | mcc         | A         |           0 |     NULL |   NULL |      | BTREE      |         |               | YES     | NULL       |
| cell_towers |          0 | PRIMARY  |            3 | net         | A         |           0 |     NULL |   NULL |      | BTREE      |         |               | YES     | NULL       |
| cell_towers |          0 | PRIMARY  |            4 | created     | A         |           0 |     NULL |   NULL |      | BTREE      |         |               | YES     | NULL       |
+-------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+------------+
```

ClickHouse via MySQL interface:

```
mysql> SHOW KEYS FROM `cell_towers` FROM `default`;
+-------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+--------------------------+
| table       | non_unique | key_name | seq_in_index | column_name | collation | cardinality | sub_part | packed | null | index_type | comment | index_comment | visible | expression               |
+-------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+--------------------------+
| cell_towers |          0 | PRIMARY  | NULL         | NULL        | A         | NULL        | NULL     | NULL   | NULL | primary    | NULL    | NULL          | YES     | radio, mcc, net, created |
+-------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+--------------------------+
```

**How to reproduce**
* Which ClickHouse server version to use: 23.6
* Which interface to use, if it matters: MySQL
* Non-default settings, if any: I added `use_mysql_types_in_show_columns` to the default profile.

```xml
  <profiles>
    <default>
      <load_balancing>random</load_balancing>
      <use_mysql_types_in_show_columns>1</use_mysql_types_in_show_columns>
    </default>
  </profiles>
```

* `CREATE TABLE` statements for all tables involved: [cell towers dataset](https://clickhouse.com/docs/en/getting-started/example-datasets/cell-towers) for ClickHouse, and a simple table like
```
create table cell_towers (radio TEXT, mcc INTEGER, net INTEGER, created DATETIME, PRIMARY KEY (radio, mcc, net, created));
```
for MySQL

* Queries to run that lead to unexpected result

```
SHOW KEYS FROM `cell_towers` FROM `default`;
```

**Expected behavior**
* The primary key is reported as a single row, whereas a composite key in MySQL is reported as 1 row per column
* There are NULLs in the output instead of numbers and/or empty strings in a real MySQL, and that supposedly causes QuickSight errors.

CC @tpanetti

**Comment by rschu1ze** [comment]
I made some improvements [here](https://github.com/ClickHouse/ClickHouse/pull/51796).

What the PR does not address yet is that there should be a separate line per primary / skipping index expression instead of a single line for all expressions, i.e. correct fields `column_name`, `seq_in_index`, and `expression`. The problem is that statement `SHOW KEYS` internally `SELECT`s from certain system tables, and ClickHouse currently only exposes the primary key expression in a form that is difficult to parse by means of SQL into an `Array(String)` (for which we then could then do an `arrayJoin()` to make multiple rows). For example, `system.tables.primary_key` may show `replaceOne(col1, 'x', 'y'), col2`. Simply splitting the PK expression along commas won't work and we certainly don't want a full-fledged SQL expression parser in SQL 😄 I am contemplating if we should rewrite the implementation to C++ or add a hidden field to an existing system table (if there is such a thing).
