### ISSUE TITLE
How to get cityHash64 or xxHash32 rightly in java?

### ISSUE THREAD

**Issue by huoarter** [ClickHouse/ClickHouse#51813]
env:
clickhouse-version: 22.3.2
# cityHash64
clickhouse-server:
```
localhost :) select cityHash64('lilei7_30709');

SELECT cityHash64('lilei7_30709')

Query id: 708e09c1-9070-4394-9ac0-2c1ee07b7cb2

Connecting to localhost:9078 as user ck_admin.
Connected to ClickHouse server version 22.3.2 revision 54455.

┌─cityHash64('lilei7_30709')─┐
│       10448144543165062476 │
└────────────────────────────┘

```
java code clickhouse-cityhash:  https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseCityHash.java

        String value = "lilei7_30709";
        System.out.println(ClickHouseCityHash.cityHash128(value.getBytes(),0, value.length())[0]);
        System.out.println(ClickHouseCityHash.cityHash128(value.getBytes(),0, value.length())[1]);
output: 
-5906256776557546790
-5820156431065750648

other java code: https://github.com/EwainCai/cityHash102-java
        String value = "lilei7_30709";
        System.out.println(CityHash.CityHash64(value.getBytes(),0, value.length()));
       -7998599530544489140

# xxHash32

localhost :) select xxHash32('lilei9_12993');

SELECT xxHash32('lilei9_12993')

Query id: c6c5a122-f5e8-4df9-bc98-cd0c960335a4

┌─xxHash32('lilei9_12993')─┐
│               2460323711 │
└──────────────────────────┘

code: https://github.com/lz4/lz4-java/tree/master/src/java/net/jpountz/xxhash
        String value = "lilei9_12993";
        XXHash32 xxHash32 = XXHashFactory.safeInstance().hash32();
        int hash = xxHash32.hash(value.getBytes(), 0, value.getBytes().length, 0);
        System.out.println(hash);
output:  -1834643585

I would like to use Java's hash algorithms to perform pre-hashing calculations on data using clickhouse-local. How can I ensure consistency with the hash algorithms used in distributed tables, such as cityHash64 and xxHash32?

**Comment by UnamedRus** [comment]
Can you check

https://github.com/ClickHouse/ClickHouse/issues/22696
https://github.com/ClickHouse/ClickHouse/issues/48869

**Comment by huoarter** [comment]
> Can you check
> 
> #22696 #48869

I have checked this many times, but i can not get right answer.

**Comment by UnamedRus** [comment]
```
other java code: https://github.com/EwainCai/cityHash102-java
String value = "lilei7_30709";
System.out.println(CityHash.CityHash64(value.getBytes(),0, value.length()));
-7998599530544489140



SELECT CAST(cityHash64('lilei7_30709'), 'Int64')

Query id: f99223b6-c39b-431f-86cd-57f8d8a6c7bc

┌─CAST(cityHash64('lilei7_30709'), 'Int64')─┐
│                      -7998599530544489140 │
└───────────────────────────────────────────┘
```

**Comment by huoarter** [comment]
> ```
> other java code: https://github.com/EwainCai/cityHash102-java
> String value = "lilei7_30709";
> System.out.println(CityHash.CityHash64(value.getBytes(),0, value.length()));
> -7998599530544489140
> 
> 
> 
> SELECT CAST(cityHash64('lilei7_30709'), 'Int64')
> 
> Query id: f99223b6-c39b-431f-86cd-57f8d8a6c7bc
> 
> ┌─CAST(cityHash64('lilei7_30709'), 'Int64')─┐
> │                      -7998599530544489140 │
> └───────────────────────────────────────────┘
> ```

Thank you, I understand the answer to the previous inconsistency issue. However, I have another question: When I use clickhouse-local to perform modulo calculation on cityHash64 pre-hashing, the results are different from using cityHash64 on ClickHouse distributed tables. I understand that ClickHouse distributed tables calculate shard modulo using cityHash64(name)%10+1, rather than CAST(cityHash64(name)%10,'Int64')+1. How can I perform the modulo calculation to achieve the same results?

**Comment by huoarter** [comment]
> ```
> other java code: https://github.com/EwainCai/cityHash102-java
> String value = "lilei7_30709";
> System.out.println(CityHash.CityHash64(value.getBytes(),0, value.length()));
> -7998599530544489140
> 
> 
> 
> SELECT CAST(cityHash64('lilei7_30709'), 'Int64')
> 
> Query id: f99223b6-c39b-431f-86cd-57f8d8a6c7bc
> 
> ┌─CAST(cityHash64('lilei7_30709'), 'Int64')─┐
> │                      -7998599530544489140 │
> └───────────────────────────────────────────┘
> ```
Thank you! You're really handsome!
