### ISSUE TITLE
support of open tracing in clickhouse 

### ISSUE THREAD

**Issue by TH-HA** [ClickHouse/ClickHouse#5182]
[open tracing ](https://opentracing.io/) is a standard allowing to trace distributed transaction. 
It work by simply by  put trace id  and spawn information into http header for instance ( https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md )  and propagate those information to the next layer. 
It start to be very popular as such visibility is key in distributed and micro service architecture.

Implementing such standard can allow:
   To have a consistent tracing between clickhouse and applicative layer
        - It may also require to have jdbc/odbc driver to evolve to have the full stack visible). 
   To have a good visibility and troubleshooting tool within a clickhouse cluster. ( if implementation propagate the traceid within the cluster when distributing request between nodes).

Additional source of information on the subject : 
Impementation of trace collector : https://www.jaegertracing.io/ 
Their is also an initiative to merge open tracing and open census ( google solution ) : https://medium.com/opentracing/merging-opentracing-and-opencensus-f0fe9c7ca6f0

Regards

**Comment by nvartolomei** [comment]
Can’t plus this enough. I would propose for open census as a two in one solution for both metrics and tracing, although I don’t have experience with it’s cpp client.

**Comment by nekenk1** [comment]
Would love to this that available in CH ! On .NET, the open tracing client is very well done and easy to integrate, of course it supports sampling which is required in many contexts where clickhouse is used. 

Tracing is one of the feature that was coming for free in monolith app time. Now, in the reign of microservices, we are really lacking tracing capabilities that open tracing and open census tries to fill. 

I'm using Jaeger right now to ingest traces, it's quite simple to use. Of course monitoring is still missing, I'm not sure how is it working in open census I didn't find any relevant integration/demo I could play with. Having Prometheus linked to those traces will certainly help too !

**Comment by filimonov** [comment]
It is interesting subject. Currentry you can do manual analysis by connecting events by initial_query_id in query_log, but probably tracing coung give better control on that.

Can you please describe what kind of events you expect to be collected? Just query/subquery start/end on each server participating?

**Comment by TH-HA** [comment]
Hello @filimonov 
To start with ,  yes query subquery propagated from the "root" query within the cluster with timing information. Those information can be usefull in multiple context and are generally hard to consolidate.
  Typically such information is very usefull in case of troubleshooting of course , but also during day to day cluster supervision. It will allow to highlight very quickly if one node if a bottleneck , if distribution is wrong ..... 
Of course those are a few use case purely internal to clickhouse , but this can be combined with a bigger picture where application running on the top of clickhouse can take benefit of such framework.  Typically have the full correlated traces going from a user request in a web UI to the backend serving the request is really a must have today.

Select queries are the most important , but insert can also take benefit of such feature. ( interesting to note that you can start to have the opentracing support into kafka ). 

On what @nvartolomei  was mentioning is open census is functionally larger than open tracing. Open Census also allow metrics collection.  Knowing that clickhouse already have prometheus supervision support, it may be a bit redundant ( but it may be consistent as the opencensus interface is a source supported by prometheus). 

Full approach on opencensus , and this is another subject ,should give  the ability to correlate the trace with the metrics is also a key element when doing some platform supervision. 


Another idea ( But here we go in something different than the initial request - If you think such idea is interesting and you want me to open a second ticket on that , just let me know ) : 
       If we follow the principle of open tracing , db drivers ( jdbc / odbc and also all the external drivers implemented for the different language ) will need to evolve to propagate the information from the incoming requests and generate new spawn.  
       May be it can be interesting to use the http server of clickhouse to expose rest services 
       Every service  implementation is a query with some parameters. The result and the format of the result can be either put in the request , either a parameter. 
        something like :
               specify : 
                   URL    user/myrequest 
                   REQUEST : select name,count(1) as entries from DB.TABLE where user=?user FORMAT ?format(json)
                          you can specify variable and default value- the format is just an example here.
                   DISCOVERY : Consul or any other service discovery directory in which the url can be declared  
                 then you have the following url answering the request 
                           https://chserver:8123/svc/user/myrequest?user=toto&format=json
                 
 By doing that , production ready analytic application can run with simplified interface ( all the analytics frameworks support rest api )  with no dependencies. 

In fact even the prometheus  support on clickhouse can be then implemented this way ( and extended to add applicative measure on the it ) :The exporter become some rest api relying on queries on the system tables. 

I'm mentioning this idea because it can drastically speed up adoption of the feature as the only interface to be used it http and  opentracing try to standardize its support in the http protocol. 

On the last part , yes i'm volunteer. I may have some hard time to work on this until end of june, but after that i hope i'll be  able to help.

**Comment by cce** [comment]
re: the mention of OpenTracing and OpenCensus as alternatives in the above comments, the two projects are actually merging:
https://medium.com/opentracing/merging-opentracing-and-opencensus-f0fe9c7ca6f0
https://medium.com/opentracing/a-roadmap-to-convergence-b074e5815289

The two projects have similar tracing APIs (OpenCensus has a metrics API in addition to tracing) and the metrics/tracing APIs will be consolidated into the new project, with OC and OT both deprecated by the end of the year. A C++ API is not in scope for the initial September release, but "the new project will continue to support existing instrumentation for two years, via a backwards compatibility bridge."

In case someone wants to work on this — Envoy is a good example of a C++ project with OpenTracing and OpenCensus integration. OpenTracing provides an API but no official trace serialization format, so pluggable "tracers" perform data serialization and reporting to an analysis backend. After adding a few built-in tracers Envoy added shared library support for loading user-provided tracers as well.

Some examples from Envoy of C++ tracing integrations:
https://github.com/envoyproxy/envoy/pull/2017 added initial OT support
https://github.com/envoyproxy/envoy/pull/2252 added OT shared library support for loading tracers
https://github.com/envoyproxy/envoy/pull/5387 added OpenCensus support, merged just yesterday

**Comment by filimonov** [comment]
Cross-linking: https://gist.github.com/alexey-milovidov/d62d73222d83b9319dc519cbb13aeff6

**Comment by crakjie** [comment]
The merger of OpenTracing and OpenCensus is called OpenTelemetry https://opentelemetry.io/

**Comment by filimonov** [comment]
> The merger of OpenTracing and OpenCensus is called OpenTelemetry https://opentelemetry.io/

![standartds joke](https://imgs.xkcd.com/comics/standards.png)

**Comment by alexey-milovidov** [comment]
This task is reserved for @Quid37.

**Comment by alexey-milovidov** [comment]
#10510

**Comment by YoannBuch** [comment]
Hi all, this may be of interest to some of you here: the APM solution [Instana](https://www.instana.com/) now offers this end-to-end visibility inside the ClickHouse cluster.

We talked about it during this [Altinity webinar](https://www.altinity.com/presentations/2020/07/09/adventures-in-observability-how-in-house-clickhouse-deployment-enabled-instana-to-build-better-monitoring-for-users). 

The slide of interest is slide 32:
![image](https://user-images.githubusercontent.com/513669/88311165-d8e0bf80-cd10-11ea-88c2-8e0fa4a79216.png)

I think this capability is really useful and I look forward to seeing the above opentracing/opentelemetry built-in support getting released, as we could also integrate it with Instana.

**Comment by alexey-milovidov** [comment]
#13444

**Comment by filimonov** [comment]
Please check / help review: https://github.com/ClickHouse/ClickHouse/pull/14195/files#diff-bdc158a0a0a1ffa9fdd2041444cf17abR1

**Comment by alexey-milovidov** [comment]
Basic support for OpenTelemetry has been merged and available in version 20.11 testing.
What is left to implement is convenient export of tracing data.

@akuzm is going to provide documentation / examples.

**Comment by sasah** [comment]
> Basic support for OpenTelemetry has been merged and available in version 20.11 testing.
> What is left to implement is convenient export of tracing data.
> 
> @akuzm is going to provide documentation / examples.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver

**Comment by akuzm** [comment]
We added some experimental support for OpenTelemetry: we accept trace context headers over HTTP and Native protocols, add a few spans for some stages of query execution, store them in the `system.opentelemetry_span_log` table, and propagate the trace context to remote ClickHouse servers and to URL engine.

https://clickhouse.tech/docs/en/operations/opentelemetry/

#14195
#16535

**Comment by akuzm** [comment]
Now that we have some [basic OpenTelemetry support](https://clickhouse.tech/docs/en/operations/opentelemetry/), I think we can close this issue and create more fine-grained feature requests as needed.
