### ISSUE TITLE
When I insert large dataset I get error "Code: 240. DB::ErrnoException: Allocator: Cannot mremap memory chunk from 64.00 MiB to 128.00 MiB"

### ISSUE THREAD

**Issue by mrxotey** [ClickHouse/ClickHouse#51826]
Clickhouse installation type: baremetal
Server memory: 377 GiB
OS: AlmaLinux 9
Kernel: 5.14.0-284.11.1.el9_2.x86_64

Clickhouse version: 22.3.11 revision 54455
RPM package repo: https://packages.clickhouse.com/rpm/stable/
Application uses interface: HTTP

Application inserts datasets in format CSV compressed with ZSTD
Compressed size of CSV file is 30 MB
Rows count: ~1,000,000
Columns count: 236

Database engine: Ordinary
Table engine: ReplicatedReplacingMergeTree

Sometimes during CSV insertion I get an error "Code: 240. DB::ErrnoException: Allocator: Cannot mremap memory chunk from 64.00 MiB to 128.00 MiB"
This error is blinking. I mean sometimes the error is occured but on retry CSV insertion is completed

Error log entry:
```
<Error> DynamicQueryHandler: Code: 240. DB::ErrnoException: Allocator: Cannot mremap memory chunk from 64.00 MiB 
to 128.00 MiB., errno: 12, strerror: Cannot allocate memory: While executing CSVRowInputFormat. (CANNOT_MREMAP)

[pid 119525] mremap(0x7f5fcbe00000, 67108864, 134217728, MREMAP_MAYMOVE <unfinished ...>
[pid 119525] <... mremap resumed>)      = 0x7f5bc2e00000
[pid 126632] mremap(0x7f5d94e00000, 67108864, 134217728, MREMAP_MAYMOVE <unfinished ...>
[pid 126632] <... mremap resumed>)      = 0x7f5bbae00000
[pid 126632] mremap(0x7f5d90e00000, 67108864, 134217728, MREMAP_MAYMOVE <unfinished ...>
[pid 126632] <... mremap resumed>)      = -1 ENOMEM (Cannot allocate memory)
[pid 126631] mremap(0x7f5d8ce00000, 67108864, 134217728, MREMAP_MAYMOVE <unfinished ...>
[pid 126631] <... mremap resumed>)      = 0x7f5d8ce00000
[pid 121783] mremap(0x7f5d15e00000, 67108864, 134217728, MREMAP_MAYMOVE <unfinished ...>
[pid 121783] <... mremap resumed>)      = 0x7f5ce9e00000
[pid 126631] mremap(0x7f5c55e00000, 268435456, 1073741824, MREMAP_MAYMOVE <unfinished ...>

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37453a in /usr/bin/clickhouse
1. DB::throwFromErrno(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, int) @ 0xb375506 in /usr/bin/clickhouse
2. Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) @ 0xb190ee6 in /usr/bin/clickhouse
3. void DB::PODArrayBase<8ul, 4096ul, Allocator<false, false>, 15ul, 16ul>::reserveForNextSize<>() @ 0xb3dbda7 in /usr/bin/clickhouse
4. DB::SerializationString::deserializeTextQuoted(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x1525a5b0 in /usr/bin/clickhouse
5. DB::SerializationArray::deserializeTextCSV(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x1521cd07 in /usr/bin/clickhouse
6. DB::CSVFormatReader::readField(DB::IColumn&, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::ISerialization const> const&, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x169a22c1 in /usr/bin/clickhouse
7. DB::RowInputFormatWithNamesAndTypes::readRow(std::__1::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::RowReadExtension&) @ 0x16983e85 in /usr/bin/clickhouse
8. DB::IRowInputFormat::generate() @ 0x16975290 in /usr/bin/clickhouse
9. DB::ISource::tryGenerate() @ 0x16905155 in /usr/bin/clickhouse
10. DB::ISource::work() @ 0x16904d1a in /usr/bin/clickhouse
11. DB::ExecutionThreadContext::executeTask() @ 0x169254a3 in /usr/bin/clickhouse
12. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16918efe in /usr/bin/clickhouse
13. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x1691824b in /usr/bin/clickhouse
14. DB::PipelineExecutor::execute(unsigned long) @ 0x16917b18 in /usr/bin/clickhouse
15. DB::CompletedPipelineExecutor::execute() @ 0x169165c4 in /usr/bin/clickhouse
16. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::__1::shared_ptr<DB::Context>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::optional<DB::FormatSettings> const&) @ 0x15d34ab3 in /usr/bin/clickhouse
17. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::__1::optional<DB::CurrentThread::QueryScope>&) @ 0x16645d87 in /usr/bin/clickhouse
18. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1664a532 in /usr/bin/clickhouse
19. DB::HTTPServerConnection::run() @ 0x168d1a7b in /usr/bin/clickhouse
20. Poco::Net::TCPServerConnection::start() @ 0x19b8992f in /usr/bin/clickhouse
21. Poco::Net::TCPServerDispatcher::run() @ 0x19b8bd81 in /usr/bin/clickhouse
22. Poco::PooledThread::run() @ 0x19d48d49 in /usr/bin/clickhouse
23. Poco::ThreadImpl::runnableEntry(void*) @ 0x19d460a0 in /usr/bin/clickhouse
24. ? @ 0x7f2e2b89f802 in ?
25. ? @ 0x7f2e2b83f450 in ?
```

Clickhouse settings:
- max_memory_usage: 50 GiB
- input_format_parallel_parsing: 0
- max_memory_usage_for_user: 0
- optimize_on_insert: 0

Server settings:
- transparent_hugepage/enabled: madvise (we tried all variants for this setting)
- overcommit_memory: 0
- and increased value for sysctl "max_map_count"

P.S.
Sorry for my terrible english :-(

**Comment by mrxotey** [comment]
Forget to tell some other Clickhouse's configuration:
- storage type: per-disk: clickhouse's storage configuration (we do not use RAID/LVM)
- zookeepers are installed on same servers (one clickhouse shard - one zookeeper replicaset) (data directories for zookeepers and clickhouses are located on different disks)

**Comment by den-crane** [comment]
https://t.me/clickhouse_ru/330713

такая же картина на 100+ таких же серверах с такой же конфигурацией 

ручки input_format_parallel_parsing, max_memory_usage крутил
transparent_hugepage/enabled madvise / always / never - пробовал все 3 варианта
overcommit_memory = 0, =1 пробовал тоже
max_map_count задирать пробовал

на 70+ таких же серверах с такой же конфигурацией и версией КХ, но
ось  Ubuntu 18.04.6
ядро 5.4.0-126-generic
работает нормально, в чем разница с alma найти не могу, есть идеи куда смотреть?

**Comment by mrxotey** [comment]
> https://t.me/clickhouse_ru/330713
> 
> такая же картина на 100+ таких же серверах с такой же конфигурацией
> 
> ручки input_format_parallel_parsing, max_memory_usage крутил transparent_hugepage/enabled madvise / always / never - пробовал все 3 варианта overcommit_memory = 0, =1 пробовал тоже max_map_count задирать пробовал
> 
> **на 70+ таких же серверах с такой же конфигурацией и версией КХ, но ось Ubuntu 18.04.6 ядро 5.4.0-126-generic работает нормально, в чем разница с alma найти не могу, есть идеи куда смотреть?**

Совершенно верно. Это мой коллега писал в ТГ.
Когда мы исчерпали все варианты сами, то тимлид попросил нарисовать ишью в гитхаб

**Comment by den-crane** [comment]
@mrxotey кстати какая ф.с.? Похоже что единственная нормальня ф.с. это ext4. 
В XFS много багов и КХ их проявляет.

**Comment by mrxotey** [comment]
> @mrxotey кстати какая ф.с.? Похоже что единственная нормальня ф.с. это ext4. В XFS много багов и КХ их проявляет.

Привет!

Используем ext4

А точнее: из 14 дисков (серверы 2U), 2 используются под систему (SSD) --- там живет система и зукиперы. Эти диски находятся под RAID 1 (mdadm)
Остальные 12 дисков затесетаплены под ext4 и они используются под хранение данных для КХ (main path Кликхауса находится на системных дисках)
Балансировка данных --- "storage_configuration" самого Кликауса

**Comment by den-crane** [comment]
>Балансировка данных --- "storage_configuration" самого Кликауса

не относится к проблеме, странное решение использовать storage_configuration, mdadm RAID0  будет работать в 1000500 раз быстрее, вместо одного диска запись и чтение будут с 12 дисков.

**Comment by mrxotey** [comment]
> > Балансировка данных --- "storage_configuration" самого Кликауса
> 
> не относится к проблеме, странное решение использовать storage_configuration, mdadm RAID0 будет работать в 1000500 раз быстрее, вместо одного диска запись и чтение будут с 12 дисков.

Согласен. Мы в какой-то момент рассматривали много вариантов для раздела хранения данных: LVM/RAID/ZFS.
Но в итоге пришли к "storage_configuration"

И причина вот в чем: на один шард приходится порядка ~100 ТБ данных (без учета избыточности), а фактор репликации --- 3. Поэтому стало сильно жалко тратить x6 места вместо x3
Поэтому рассматривая разные варианты решили, что "нативных" вариант с "storage_configuration" является оптимальным: при вылете диска --- не проблема вывести инстанс их раздачи и после замены диска запустить Клик с флагом "force_restore_data"

То есть смысл в том, что отресинкать ~100 ТБ данных (при вылете диска в случае RAID 0) или отресинкать ~8 ТБ данных при вылете диска в "storage_configuration" --- сильно большая разнаца

А отбалансировать парты по дискам (alter table .. move part..) --- не является проблемой. Обвязки для этого мы сделали

**Comment by mrxotey** [comment]
Seems this issue will be solved via https://github.com/ClickHouse/ClickHouse/pull/51686

**Comment by mrxotey** [comment]
Полагаю, что issue можно закрыть
Мы справились с проблемой путем апгрейда ядра до 6.1
