### ISSUE TITLE
Will restricted data still be loaded after using Row policy

### ISSUE THREAD

**Issue by yehaotong** [ClickHouse/ClickHouse#51827]
I plan to  storage cold data on s3, and I want to use row policy like :
`create row policy my_policy on mytable using  time > now()-toIntervalDay(14) to my_user`
To avoid S3 retrieval costs caused by unauthorized user queries.
And I tess on my local clickhouse and found that: 
```
[9707b547a446] 2023.07.05 11:52:38.025532 [ 45 ] {d3130532-c588-4197-9352-8017612f018f} <Debug> logs_erax.logs (21f16d73-41c8-4ec5-b380-f7f185d115bb) (SelectExecutor): Reading approx. 3 rows with 3 streams
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        5 │ test5      │ 2023-07-04 17:00:00 │
└──────────┴────────────┴─────────────────────┘
```
On my test table ,it has 3 rows,and 2 rows should be restricted by this row policy, but when I select * from logs, I found that 
`Reading approx. 3 rows with 3 streams`
Does this mean that even if the data is stored on s3 and there are row policy restrictions, it will still generate queries and incur retrieval costs？

**Comment by den-crane** [comment]
it depends on ORDERBY / PARTITION BY of the table and on Clickhouse version

**Comment by yehaotong** [comment]
> it depends on ORDERBY / PARTITION BY of the table and on Clickhouse version

my clickhosue version is 22.4.5, and my table is:
```
CREATE TABLE logs.logs
(
    `_time_second_` DateTime64(9),
    `_time_` String,
    `_source_` String,
    `_cluster_` String,
    `_log_agent_` String,
    `_namespace_` String,
    `_node_name_` String,
    `_node_ip_` String,
    `_container_name_` String,
    `_pod_name_` String,
    `caller` String,
    `message` String,
    `service` String,
    `stack` String,
    `type` String,
    `meta_client_ip` String,
    `meta_from` String,
    `meta_login_user_id` String,
    `meta_origin` String,
    `meta_slug` String,
    `meta_store_id` Int32 DEFAULT 0,
    `meta_x_request_id` String,
    `meta_traceid` String,
    `meta_sampled` String,
    `http_status` Int16 DEFAULT 0,
    `http_elapse` Float32 DEFAULT 0,
    `http_method` String,
    `http_path` String,
    `http_query` String,
    `http_domain` String,
    `http_user_agent` String,
    `http_duration` String,
    `rpc_status` Int16 DEFAULT 0,
    `rpc_elapse` Float32 DEFAULT 0,
    `rpc_method` String,
    `rpc_user_agent` String,
    `rpc_duration` String,
    `_raw_log_` String,
    `http_backend_addr` String,
    `http_request_content_size` Int64,
    `http_response_content_size` Int64,
    `http_duration_ns` Int64,
    `http_origin_duration_ns` Int64,
    `http_overhead_ns` Int64,
    `_alias_raw_log_` String ALIAS desen_function_python(_raw_log_),
    INDEX bf_metarequestid meta_x_request_id TYPE bloom_filter GRANULARITY 8192
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(_time_second_)
ORDER BY (_container_name_, _time_second_)
SETTINGS index_granularity = 8192, max_suspicious_broken_parts = 20, storage_policy = 'logs_hot_cold'
```

**Comment by yehaotong** [comment]
> it depends on ORDERBY / PARTITION BY of the table and on Clickhouse version

I test on my local clcikhosue:22.4.5, table is:
```
CREATE TABLE logs
(
    `VendorID` UInt8,
    `VendorName` String,
    `origin_time` DateTime('Asia/Shanghai')
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(origin_time)
ORDER BY origin_time
SETTINGS index_granularity = 8192, storage_policy = 'hot_cold'
```
And I insert 3 rows data to logs:
```
9707b547a446] 2023.07.06 02:32:05.596492 [ 45 ] {b38c1548-3974-4f51-9575-6e19a4ff7e9a} <Debug> logs_erax.logs (21f16d73-41c8-4ec5-b380-f7f185d115bb) (SelectExecutor): Reading approx. 3 rows with 3 streams
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        5 │ test5      │ 2023-07-04 17:00:00 │
└──────────┴────────────┴─────────────────────┘
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        2 │ test2      │ 2023-06-02 09:00:00 │
└──────────┴────────────┴─────────────────────┘
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        1 │ test1      │ 2023-06-01 09:00:00 │
└──────────┴────────────┴─────────────────────┘
```
then I 
```
create row policy logs_erax_policy on logs_erax.logs using  origin_time > now()-toIntervalDay(14) to erax_reader
alter table logs_erax.logs move partition '20230601' to disk 's3'
```
then I select * from logs aggin:
```
[9707b547a446] 2023.07.06 02:33:43.383389 [ 45 ] {18a4c6f9-902a-41f5-9651-5f1e9aec3c76} <Debug> logs_erax.logs (21f16d73-41c8-4ec5-b380-f7f185d115bb) (SelectExecutor): Reading approx. 3 rows with 3 streams
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        5 │ test5      │ 2023-07-04 17:00:00 │
└──────────┴────────────┴─────────────────────┘
```
I find that has query on s3,and return 3 rows,so I'm not sure if it's possible to restrict users from triggering query s3 through the row policy

**Comment by yehaotong** [comment]
> > PARTITION BY toYYYYMMDD(_time_second_)
> > ORDER BY (_container_name_, _time_second_)
> > origin_time > now()-toIntervalDay(14)
> 
> How Clickhouse can know that `origin_time` is related to `_time_second_`? Clickhouse does not have automatic min_max indexes. Clickhouse will read all rows to solve `where origin_time > now()-toIntervalDay(14)`
The test data above was tested using the following table：
```
CREATE TABLE logs_erax.logs
(
    `VendorID` UInt8,
    `VendorName` String,
    `origin_time` DateTime('Asia/Shanghai')
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(origin_time)
ORDER BY origin_time
SETTINGS index_granularity = 8192, storage_policy = 'erax_hot_cold'
```

**Comment by yehaotong** [comment]
> > PARTITION BY toYYYYMMDD(_time_second_)
> > ORDER BY (_container_name_, _time_second_)
> > origin_time > now()-toIntervalDay(14)
> 
> How Clickhouse can know that `origin_time` is related to `_time_second_`? Clickhouse does not have automatic min_max indexes. Clickhouse will read all rows to solve `where origin_time > now()-toIntervalDay(14)`

The test data above was tested using the following table:
```
CREATE TABLE logs_erax.logs
(
    `VendorID` UInt8,
    `VendorName` String,
    `origin_time` DateTime('Asia/Shanghai')
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(origin_time)
ORDER BY origin_time
SETTINGS index_granularity = 8192, storage_policy = 'erax_hot_cold'
```

**Comment by den-crane** [comment]
that's is confusing.

**Comment by yehaotong** [comment]
Perhaps my expression is not very clear, let me explain it again, I have a table in the production environment: logs:
```
CREATE TABLE logs.logs
(
    `_time_second_` DateTime64(9),
    `_time_` String,
    `_source_` String,
    `_cluster_` String,
    `_log_agent_` String,
    `_namespace_` String,
    `_node_name_` String,
    `_node_ip_` String,
    `_container_name_` String,
    `_pod_name_` String,
    `caller` String,
    `message` String,
    `service` String,
    `stack` String,
    `type` String,
    `meta_client_ip` String,
    `meta_from` String,
    `meta_login_user_id` String,
    `meta_origin` String,
    `meta_slug` String,
    `meta_store_id` Int32 DEFAULT 0,
    `meta_x_request_id` String,
    `meta_traceid` String,
    `meta_sampled` String,
    `http_status` Int16 DEFAULT 0,
    `http_elapse` Float32 DEFAULT 0,
    `http_method` String,
    `http_path` String,
    `http_query` String,
    `http_domain` String,
    `http_user_agent` String,
    `http_duration` String,
    `rpc_status` Int16 DEFAULT 0,
    `rpc_elapse` Float32 DEFAULT 0,
    `rpc_method` String,
    `rpc_user_agent` String,
    `rpc_duration` String,
    `_raw_log_` String,
    `http_backend_addr` String,
    `http_request_content_size` Int64,
    `http_response_content_size` Int64,
    `http_duration_ns` Int64,
    `http_origin_duration_ns` Int64,
    `http_overhead_ns` Int64,
    `_alias_raw_log_` String ALIAS desen_function_python(_raw_log_),
    INDEX bf_metarequestid meta_x_request_id TYPE bloom_filter GRANULARITY 8192
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(_time_second_)
ORDER BY (_container_name_, _time_second_)
SETTINGS index_granularity = 8192, max_suspicious_broken_parts = 20, storage_policy = 'logs_hot_cold'

```
And regularly move data from 14 days ago to s3 every day， which I consider as cold data.I want to use some means to restrict users from querying cold data, such as ordinary users can only access data within 14 days and cannot access data on S3 (there will be retrieval fees for querying S3).
So I want to verify locally that the row policy cannot be used to query user settings. Will it still initiate queries on s3.
I create this table on my local clickhouse:
```
CREATE TABLE logs_erax.logs
(
    `VendorID` UInt8,
    `VendorName` String,
    `origin_time` DateTime('Asia/Shanghai')
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(origin_time)
ORDER BY origin_time
SETTINGS index_granularity = 8192, storage_policy = 'erax_hot_cold'


```
There are currently three raws of data in it
```
9707b547a446] 2023.07.06 02:32:05.596492 [ 45 ] {b38c1548-3974-4f51-9575-6e19a4ff7e9a} <Debug> logs_erax.logs (21f16d73-41c8-4ec5-b380-f7f185d115bb) (SelectExecutor): Reading approx. 3 rows with 3 streams
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        5 │ test5      │ 2023-07-04 17:00:00 │
└──────────┴────────────┴─────────────────────┘
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        2 │ test2      │ 2023-06-02 09:00:00 │
└──────────┴────────────┴─────────────────────┘
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        1 │ test1      │ 2023-06-01 09:00:00 │
└──────────┴────────────┴─────────────────────┘
```
And create a raw policy:
`create row policy logs_erax_policy on logs_erax.logs using  origin_time > now()-toIntervalDay(14) to erax_reader`
And I use user: erax_reader to login in clickhosue and select * from logs,I find that:
[9707b547a446] 2023.07.06 08:12:29.748316 [ 46 ] {a96ef527-1285-4916-8752-17be15454922} <Debug> logs_erax.logs (21f16d73-41c8-4ec5-b380-f7f185d115bb) (SelectExecutor): Selected 3/3 parts by partition key, 3 parts by primary key, 3/3 marks by primary key, 3 marks to read from 3 ranges
[9707b547a446] 2023.07.06 08:12:29.750682 [ 46 ] {a96ef527-1285-4916-8752-17be15454922} <Debug> logs_erax.logs ```
(21f16d73-41c8-4ec5-b380-f7f185d115bb) (SelectExecutor): Reading approx. 3 rows with 3 streams
┌─VendorID─┬─VendorName─┬─────────origin_time─┐
│        5 │ test5      │ 2023-07-04 17:00:00 │
└──────────┴────────────┴─────────────────────┘
[9707b547a446] 2023.07.06 08:12:29.766384 [ 46 ] {a96ef527-1285-4916-8752-17be15454922} <Information> executeQuery: Read 3 rows, 27.00 B in 0.037789043 sec., 79 rows/sec., 714.49 B/sec.
[9707b547a446] 2023.07.06 08:12:29.776140 [ 46 ] {a96ef527-1285-4916-8752-17be15454922} <Debug> MemoryTracker: Peak memory usage (for query): 119.72 KiB.
```
From this log, it can be seen that even with the addition of row policy queries, data within 14 days is returned，but it also:
`Reading approx. 3 rows with 3 streams`
So does this mean that even with the addition of row policy, it will still be loaded into the data, even if these data are restricted by the policy(This means that if these data are on s3, there will be retrieval costs incurred)

**Comment by yehaotong** [comment]
> that's is confusing.

The final focus I want to clarify is that after restricting query data through the row policy (with datatime as the condition), restricted users will also load the restricted row data when initiating queries
