### ISSUE TITLE
how to chose a shard for distributed 

### ISSUE THREAD

**Issue by huoarter** [ClickHouse/ClickHouse#51841]
clickhouse-server version: 22.3.2

 When I use clickhouse-local to perform modulo calculation on cityHash64 pre-hashing, the results are different from using cityHash64 on ClickHouse distributed tables. I understand that ClickHouse distributed tables calculate shard modulo using cityHash64(name)%10+1, rather than CAST(cityHash64(name)%10,'Int64')+1. How can I perform the modulo calculation to achieve the same results?

example my table:
CREATE TABLE if not exists default.dist_test_babelx (
name String,
....
)
ENGINE = Distributed('{cluster}', 'default', 'test_babelx', CAST(xxHash64(name),'Int64'))

i have 10 nodes.

table data:
check sql
```
select name,  CAST(xxHash64(name),'Int64')%10,getMacro('shard') as shard from clusterAllReplicas('{cluster}',default.test_babelx) order by shard
┌─name────────┬─modulo(CAST(xxHash64(name), 'Int64'), 10)─┬─shard─┐
│ lilei6_6938 │                                        -3 │ 04    │
└─────────────┴───────────────────────────────────────────┴───────┘
┌─name─────────┬─modulo(CAST(xxHash64(name), 'Int64'), 10)─┬─shard─┐
│ lilei0_87531 │                                         4 │ 05    │
└──────────────┴───────────────────────────────────────────┴───────┘
┌─name─────────┬─modulo(CAST(xxHash64(name), 'Int64'), 10)─┬─shard─┐
│ lilei9_46548 │                                        -2 │ 05    │
└──────────────┴───────────────────────────────────────────┴───────┘
```

when name is “lilei9_46548“, the CAST(xxHash64('lilei9_46548'), 'Int64') equals -2574499495101583472 is a negative value.
So my question is how does the distributed table calculate the shard when the value of sharding_key is negative.
If there is no negative value, there is no problem. I understand that the calculation shard rule is abs(CAST(xxHash64(name),'Int64')%10+1).

Or to change the way of thinking, how can I use java to perform hash calculation on a certain column field, such as name, to obtain the same shard num as distributed hash calculation

**Comment by huoarter** [comment]
cane anyone help me ?

**Comment by UnamedRus** [comment]
```
WITH
    CAST(xxHash64(name), 'Int64') AS key,
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] AS shard_num,
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] AS shard_weights,
    arrayCumSum(shard_weights) AS cum_shard_weights,
    arraySum(shard_weights) AS total_weight
SELECT
    name,
    key,
    key % total_weight AS modulo,
    arrayFirst((x, y, z) -> ((modulo < y) AND (modulo >= z)), shard_num, cum_shard_weights, arrayPopBack(arrayPushFront(cum_shard_weights, 0))) AS _result_shart_num
FROM
(
    SELECT arrayJoin(['lilei6_6938', 'lilei0_87531', 'lilei9_46548']) AS name
)

Query id: 994a1f63-4833-4b15-b815-e38a2d6cade7

┌─name─────────┬──────────────────key─┬─modulo─┬─_result_shart_num─┐
│ lilei6_6938  │ -4777066231024988473 │      3 │                 4 │
│ lilei0_87531 │  5478184676739000754 │      4 │                 5 │
│ lilei9_46548 │ -2574499495101583472 │      4 │                 5 │
└──────────────┴──────────────────────┴────────┴───────────────────┘
```

**Comment by huoarter** [comment]
> WITH
>     CAST(xxHash64(name), 'Int64') AS key,
>     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] AS shard_num,
>     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] AS shard_weights,
>     arrayCumSum(shard_weights) AS cum_shard_weights,
>     arraySum(shard_weights) AS total_weight
> SELECT
>     name,
>     key,
>     key % total_weight AS modulo,
>     arrayFirst((x, y, z) -> ((modulo < y) AND (modulo >= z)), shard_num, cum_shard_weights, arrayPopBack(arrayPushFront(cum_shard_weights, 0))) AS _result_shart_num
> FROM
> (
>     SELECT arrayJoin(['lilei6_6938', 'lilei0_87531', 'lilei9_46548']) AS name
> )

Thank you. You look absolutely handsome!

**Comment by huoarter** [comment]
> ```
> WITH
>     CAST(xxHash64(name), 'Int64') AS key,
>     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] AS shard_num,
>     [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] AS shard_weights,
>     arrayCumSum(shard_weights) AS cum_shard_weights,
>     arraySum(shard_weights) AS total_weight
> SELECT
>     name,
>     key,
>     key % total_weight AS modulo,
>     arrayFirst((x, y, z) -> ((modulo < y) AND (modulo >= z)), shard_num, cum_shard_weights, arrayPopBack(arrayPushFront(cum_shard_weights, 0))) AS _result_shart_num
> FROM
> (
>     SELECT arrayJoin(['lilei6_6938', 'lilei0_87531', 'lilei9_46548']) AS name
> )
> 
> Query id: 994a1f63-4833-4b15-b815-e38a2d6cade7
> 
> ┌─name─────────┬──────────────────key─┬─modulo─┬─_result_shart_num─┐
> │ lilei6_6938  │ -4777066231024988473 │      3 │                 4 │
> │ lilei0_87531 │  5478184676739000754 │      4 │                 5 │
> │ lilei9_46548 │ -2574499495101583472 │      4 │                 5 │
> └──────────────┴──────────────────────┴────────┴───────────────────┘
> ```

```
WITH
    CAST(-2574499495101583472, 'Int64') AS key,
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] AS shard_num,
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] AS shard_weights,
    arrayCumSum(shard_weights) AS cum_shard_weights,
    arraySum(shard_weights) AS total_weight
SELECT
    -2574499495101583472,
    key,
    total_weight,
    key % total_weight AS modulo,
    -2574499495101583472 % 10 AS modulo2
FROM
(
    SELECT arrayJoin(['lilei9_46548']) AS name
)

Query id: 49c65dda-0b4f-447d-92d1-dced1589925d

┌─-2574499495101583472─┬──────────────────key─┬─total_weight─┬─modulo─┬─modulo2─┐
│ -2574499495101583472 │ -2574499495101583472 │           10 │      4 │      -2 │
└──────────────────────┴──────────────────────┴──────────────┴────────┴─────────┘
```
Hi, Sorry again.
I have a place that I don't quite understand. For example, if we calculate modulo with two identical values in this SQL query, why do they produce different results?

**Comment by UnamedRus** [comment]
```
SELECT
    -2574499495101583472 AS key,
    key % CAST('10', 'UInt32') AS uint32,
    key % CAST('10', 'UInt64') AS uint64,
    key % CAST('10', 'Int64') AS int64,
    toTypeName(uint32) AS type_uint32,
    toTypeName(uint64) AS type_uint64,
    toTypeName(int64) AS type_int64

Query id: f0cb79d0-c464-436a-98ce-5dc7b0224a91

┌──────────────────key─┬─uint32─┬─uint64─┬─int64─┬─type_uint32─┬─type_uint64─┬─type_int64─┐
│ -2574499495101583472 │     -2 │      4 │    -2 │ Int64       │ Int64       │ Int64      │
└──────────────────────┴────────┴────────┴───────┴─────────────┴─────────────┴────────────┘
```

Unexpected behavior or bug in ClickHouse, will make issue

**Comment by huoarter** [comment]
If this is the case, there is no Uint64 in java, and I can't get the same result of the same model anyway.
