### ISSUE TITLE
Add ability to calculate hashes from values of UUID type

### ISSUE THREAD

**Issue by a-rodin** [ClickHouse/ClickHouse#5184]
It would be nice to have an ability to quickly calculate hash function from values of UUID type without prior conversion to string.

Right now it is possible to do `cityHash64(toString(uuidValue))`, but it is inefficient because of the need to make conversions to strings.

**Use case**
To make use of UUIDs in sampling expressions or sharding keys more efficient.

**Describe the solution you'd like**
I would like to have ability to calculate `cityHash64` or `intHash64` from values that have UUID type.

**Describe alternatives you've considered**
An alternative would be to make it possible to use values of UUID type as sampling expressions and sharding keys as is, without the need to produce integer hashes from them.

**Comment by alexey-milovidov** [comment]
This is also relevant for Decimal:
```
SELECT cityHash64(generateUUIDv4())
SELECT cityHash64(toDecimal128(0, 10))
```
