### ISSUE TITLE
Use of the same expression for sample and sharding key

### ISSUE THREAD

**Issue by a-rodin** [ClickHouse/ClickHouse#5185]
Is it possible to use the sample expression for `SAMPLE BY` for a table and for sharding key for the distributed table built on top of the table?

If, for example, there are two shards and each shard has two replicas, and also `max_parallel_replicas` set to 2, would a query on the distributed table actually utilize four machines? Or the would be a collision, so that on the first shard all processing would be done only on the first replica and on the second shard all the processing would be done only on the second replica?

**Comment by a-rodin** [comment]
@den-crane Thank you for the reply!

> Distributed table requests 2 replicas and asks for 50% samples from one replica and other 50% from another.
Yes, that's what I'd expect. However, I'm curious about the exact algorithm that is used to get 50% of samples from one replica and 50% from another one and its possible interference with the sharding rule.

So taking inspiration from #5186, let's assume the table is created as
```sql
CREATE TABLE test (
  sequenceId  String,
  id          String,
  dateTime    DateTime('UTC'),
  version     UInt64
) ENGINE ReplicatedReplacingMergeTree('/shard/{shard}', '{replica}', version)
PARTITION BY toYYYYMM(dateTime)
ORDER BY (toDate(dateTime), cityHash64(sequenceId), id)
PRIMARY KEY (toDate(dateTime), cityHash64(sequenceId))
SAMPLE BY cityHash64(sequenceId);

CREATE TABLE IF NOT EXISTS test_d AS test ENGINE = Distributed('test-cluster', 'default', test, cityHash64(sequenceId));
```
There are two shards with two replicas on each other. I assume that the following happens:

* Inserted rows with `cityHash64(sequenceId) % 2 == 0` should go the the first shard and inserted rows `cityHash64(sequenceId) % 2 == 1` should go to the second shard.

* We do the distributed query. On the first shard each replica would try to sample 50% of the data for processing. It uses `cityHash64(sequenceId)` for sampling, so the rows with `cityHash64(sequenceId) % 2 == 0` should be processed on the first replica of the first shard and the rows with `cityHash64(sequenceId) % 2 == 0` should be processed on the second replica of the first shard. However, because of the sharding rule that is in use, all rows on both replicas of the first shard would have `cityHash64(sequenceId) % 2 == 0`. It means that 100% of rows from the first shard would be sampled and processed on the first replica of the first shard and 0 rows would be sampled on the second replica of the first shard.

* The same is would be true for the second shard, where all rows have `cityHash64(sequenceId) % 2 == 1` and thus 100% of rows would be sampled on the second replica of the second replica of the second shard and no rows would be sampled on the first replica of the second shard.

Am I correct above with the assumption that the number of shard/replica used in each case is calculated just as `cityHash64(sequenceId)` modulo 2? Or does some additional hashing/mixing take place, ensuring that sampling is still uniform?

**Comment by alexey-milovidov** [comment]
The rules of sharding and sampling are different.

For sharding, the value of `cityHash64(sequenceId) % 2 = N` will be used.
For sampling, the value of `cityHash64(sequenceId) <= 0xFFFFFFFFFFFFFFFF / K` will be used.

The rule for sampling is made that way to ensure continuous ranges of sampled data if the data is ordered by sample key.
