### ISSUE TITLE
`fread` declaration error

### ISSUE THREAD

**Issue by infdahai** [ClickHouse/ClickHouse#51856]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

WSL2(Ubuntu 22.04)

**Cmake version**

3.26.3

**Ninja version**

1.10.1

**Compiler name and version**

clang-16, clang++-16

**Full cmake and/or ninja output**

I execute `ninja -j16 clickhouse-client clickhouse-server` and get the output down here.

~/Workspace/proj/finish_proj/ClickHouse/build (master) # ninja -j16 clickhouse-client clickhouse-server                                                                                                                                                                                               1 ↵ root@DESKTOP-CO31SAO
[0/2] Re-checking globbed directories...
[96/11352] Building C object base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/glibc-compatibility.c.o
FAILED: base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/glibc-compatibility.c.o 
/usr/local/bin/ccache /usr/bin/clang -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/root/Workspace/proj/finish_proj/ClickHouse/base/glibc-compatibility/libcxxabi -I/root/Workspace/proj/finish_proj/ClickHouse/base/glibc-compatibility/musl/x86_64 -I/root/Workspace/proj/finish_proj/ClickHouse/base/glibc-compatibility/memcpy -isystem /root/Workspace/proj/finish_proj/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /root/Workspace/proj/finish_proj/ClickHouse/contrib/libunwind/include -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion  -gdwarf-aranges -pipe -fasynchronous-unwind-tables -ffile-prefix-map=/root/Workspace/proj/finish_proj/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fomit-frame-pointer -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -std=gnu11   -D OS_LINUX -Werror -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/glibc-compatibility.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/glibc-compatibility.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/glibc-compatibility.c.o -c /root/Workspace/proj/finish_proj/ClickHouse/base/glibc-compatibility/glibc-compatibility.c
/root/Workspace/proj/finish_proj/ClickHouse/base/glibc-compatibility/glibc-compatibility.c:103:8: error: declaration of built-in function 'fread' requires inclusion of the header <stdio.h> [-Werror,-Wbuiltin-requires-header]
size_t fread(void *ptr, size_t size, size_t nmemb, void *stream);
       ^
1 error generated.
[111/11352] Building C object base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/glob.c.o
ninja: build stopped: subcommand failed.

**Comment by alexey-milovidov** [comment]
There is a chance that you are using a compiler other than `clang-16, clang++-16`
You can build the freshest clang from the source: https://github.com/ClickHouse/clickhouse-docs/issues/1384
