### ISSUE TITLE
about summingmergetree Keep the earliest records

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#51875]
create table test (
id int64,
created_time DateTime,
cnt Int64
)ENGINE=ReplicatedSummingMergeTree() order by id 

insert into test (1,'2023-07-05 01:00:00',1)
insert into test (1,'2023-07-05 02:00:00',2)
insert into test (1,'2023-07-05 03:00:00',3)
After data merging
select * from test:
I hope it's the following result
1    '2023-07-05 01:00:00'   6
rather than
1    '2023-07-05 03:00:00'   6

What do I need to do？

**Comment by den-crane** [comment]
```sql
CREATE TABLE test
(
    `id` Int64,
    `created_time` SimpleAggregateFunction(min, DateTime),
    `cnt` Int64
)
ENGINE = SummingMergeTree
ORDER BY id;

insert into test values(1,'2023-07-05 01:00:00',1);
insert into test values(1,'2023-07-05 02:00:00',2);
insert into test values(1,'2023-07-05 03:00:00',3);

optimize table test final;

select * from test;
┌─id─┬────────created_time─┬─cnt─┐
│  1 │ 2023-07-05 01:00:00 │   6 │
└────┴─────────────────────┴─────┘
```

**Comment by yangshike** [comment]
thank you！！


The default seems to be to keep the first inserted line
