### ISSUE TITLE
How to analyze ClickHouse memory usage and release memory without restart server?

### ISSUE THREAD

**Issue by MattMH** [ClickHouse/ClickHouse#51871]
![image](https://github.com/ClickHouse/ClickHouse/assets/16539160/ce7259ee-b88d-4c7f-96b9-70397be32545)
clickhouse used 70G memory.
My question is:
How can I  analyze ClickHouse memory usage , I was doing a 7 days performance testing by continuously insert data per seconds, and the memory usage  increased  from 20G to 70G.  Can I confirm this behavior is normal instead of  a memory leak ?
Because of the disk IO limitation, I disabled merge IO , so here are 170,000 parts in server ( select count(*) from system.parts). Does the amount of parts affect the memory usage？

AND when I RESTART the clickhouse-server the memory reduce to 40G and everything works fine. I want to know how to analyze this phenomenon？

**Comment by cangyin** [comment]
> so here are 170,000 parts in server

It is highly unrecommended to disable merges. the reasonable number of parts per table should be under 1000~10000.

>  Does the amount of parts affect the memory usage？

definitely. ClickHouse stores metadata of parts, primary indexes and caches, etc, in memory.

> when I RESTART the clickhouse-server the memory reduce to 40G and everything works fine

after you restart the server, ClickHouse starts to merge parts.

**Comment by cangyin** [comment]
as for memory analysis, see Altinity Knowledge Base [Who ate my memory](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/)

**Comment by MattMH** [comment]
> > so here are 170,000 parts in server
> 
> It is highly unrecommended to disable merges. the reasonable number of parts per table should be under 1000~10000.
> 
> checkout this [doc](https://clickhouse.com/docs/knowledgebase/exception-too-many-parts)
> 
> > Does the amount of parts affect the memory usage？
> 
> definitely. ClickHouse stores metadata of parts, primary indexes and caches, etc, in memory.
> 
> > when I RESTART the clickhouse-server the memory reduce to 40G and everything works fine
> 
> after you restart the server, ClickHouse starts to merge parts.

I use “max_parts_to_merge_at_once = 1” to limit merge. After I restart the server , the amount of parts not decrease.
So I think the memory usage gap between restart the does not cause by merge, I will do a test about memory usage and the amount of the parts.

Thanks!

**Comment by den-crane** [comment]
select version()

**Comment by den-crane** [comment]
select count() from system.parts_columns
