### ISSUE TITLE
why ROW POPICY and `additional_table_filters` are applied after reading data

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#51872]
That way, the partition keys, primary keys and indexes cannot be used to avoid unnecessary data reads.

Say I have a table like:
```sql
CREATE TABLE sodl.http_log_local
(
    `v` Int32,
    `tenant` LowCardinality(String),
    `insertTimestamp` Int64,
    `vendor` LowCardinality(Nullable(String)),
    `productType` LowCardinality(String)
)
ENGINE = MergeTree
PARTITION BY (productType, toYYYYMMDD(toDate(insertTimestamp)))
ORDER BY (uuId, insertTimestamp)
```
querying with 

```sql
SELECT * FROM sodl.http_log_local WHERE insertTimestamp > (now() - toIntervalMinute(1)) LIMIT 1

2023.07.06 10:23:59.226218 [ 3284 ] {e020f827-137a-43e2-80f1-9e41d244e89b} <Debug> sodl.http_log_local (SelectExecutor): Selected 0/56 parts by partition key, 0 parts by primary key, 0/0 marks by primary key, 0 marks to read from 0 ranges
Ok.

0 rows in set. Elapsed: 0.011 sec.
```
reads nothing

but with `additional_table_filters`
```sql
SELECT * FROM sodl.http_log_local LIMIT 1 SETTINGS additional_table_filters={'sodl.http_log_local': 'insertTimestamp > now() - toIntervalMinute(1)'}

2023.07.06 10:24:55.625679 [ 3284 ] {4a60afee-7514-4224-94e6-f4f632467295} <Debug> sodl.http_log_local (SelectExecutor): Selected 56/56 parts by partition key, 56 parts by primary key, 953/953 marks by primary key, 953 marks to read from 56 ranges
2023.07.06 10:24:55.633177 [ 3284 ] {4a60afee-7514-4224-94e6-f4f632467295} <Debug> sodl.http_log_local (SelectExecutor): Reading approx. 6982793 rows with 4 streams
2023.07.06 10:24:59.421585 [ 3284 ] {4a60afee-7514-4224-94e6-f4f632467295} <Information> executeQuery: Read 6982793 rows, 11.05 GiB in 3.802736 sec., 1836255.0016619614 rows/sec., 2.91 GiB/sec.
Ok.

0 rows in set. Elapsed: 3.803 sec. Processed 6.98 million rows, 11.87 GB (1.84 million rows/s., 3.12 GB/s.)
```
It reads almost all data, applying the filter afterhands.

**Comment by shachakz** [comment]
In my use case, we use `additional_table_filters` to inject query restrictions. We really like this feature because we don't need to parse and modify arbitrary SQL queries. 
We also noticed dramatic performance impact using the `additional_table_filters`, making it almost unusable. 

Is it something you plan to solve?

**Comment by sigxcpu76** [comment]
Is this still a thing? I also need this feature to isolate tenants, but my tests show that indices are engaged when doing outer filtering with `additional_table_filters`

https://fiddle.clickhouse.com/1e0de794-089e-4685-b2fe-3c41bf52fd6c

**Comment by cangyin** [comment]
The `additional_table_filters` should be used on primary keys, as said:

https://github.com/ClickHouse/ClickHouse/blob/78af18ac87e58dd7e81b6161f5e114d8fa34ef67/src/Storages/SelectQueryInfo.h#L189-L190

**Comment by sigxcpu76** [comment]
It is also used for secondary indices.

https://fiddle.clickhouse.com/276a7b39-1fa4-4461-bf5b-8cdf8612c914

**Comment by cangyin** [comment]
We can see from [here](https://github.com/ClickHouse/ClickHouse/blob/059f1abcf6e21569f27531d48c9f423edce9b5c5/src/Processors/QueryPlan/ReadFromMergeTree.cpp#L1386C13-L1386C25),  filters and additional filters can be applied to partition key, primary key, minmax index, virtual columns (`_part` and `_part_offset`), thanks to the refactoring around `buildIndexes()`
