### ISSUE TITLE
 After upgrading ClickHouse, there has been a significant increase in ZooKeeper requests

### ISSUE THREAD

**Issue by cjchengjie** [ClickHouse/ClickHouse#51874]
When upgraded clickhouse from v21.3.10 to v22.12.4, and ZooKeeper requests grew from 2000 to 23000.I found many requests for empty table  and some  parts from a long time ago when collecting ZooKeeper request.It makes stressful for  zookeeper.

Why is that? How to resolve it?

Thanks!

**Comment by cjchengjie** [comment]
ZK Monitoring data
![image](https://github.com/ClickHouse/ClickHouse/assets/95210052/b6a8470a-fb5e-42c9-b70d-6c6253899bb1)

**Comment by den-crane** [comment]
How many Replicated tables do you have? How many CH servers?

see https://github.com/ClickHouse/ClickHouse/issues/43647  https://github.com/ClickHouse/ClickHouse/pull/42878
https://github.com/ClickHouse/ClickHouse/pull/42878#issuecomment-1450520809

https://github.com/ClickHouse/ClickHouse/pull/50107

**Comment by cjchengjie** [comment]
Thanks!
It has 46 Replicated tables. It has 6 shards,and 2 replicas for each.

ClickHouse keeper is better in this case？

**Comment by den-crane** [comment]
removal of old block_numbers from ZK should help https://github.com/ClickHouse/ClickHouse/issues/43647#issuecomment-1327635173
