### ISSUE TITLE
An error is reported when the CSV file is loaded to the clickhouse.

### ISSUE THREAD

**Issue by T-M-L-C** [ClickHouse/ClickHouse#51884]
When data is inserted in batches in the Clickhouse database and a CSV file containing more than 4 million data records is entered, the following error information is displayed:
Password for user (test): Code: 210. DB::NetException: SSL Exception: error:10000076:SSL routines:OPENSSL_internal:BAD_WRITE_RETRY, while writing to socket (127.0.0.1:19870): data for INSERT was parsed from stdin: (in query: INSERT INTO TS.TEST(ID,NAME)
What's the good solution?

**Comment by den-crane** [comment]
Do you have reproducible example?
What Clickhouse version?
