### ISSUE TITLE
Add which Engines and Functions support MaterializedViews

### ISSUE THREAD

**Issue by brunorpinho** [ClickHouse/ClickHouse#51902]
**Describe the issue**

In my experience, MaterializedViews are extremely useful. However, I find that there is a lack of clear, concise, and quick reference in the documentation to identify which table engines, table functions, and database engines integrate with `MaterializedView`.

**Additional context**

I propose we create a table to fill this gap. As an initial suggestion, the table could look something like this:

| Type                | Name                 | Triggers MV | Supports Inserts from MV |
|---------------------|----------------------|-------------------------------------|----------------------------------|
| Table Engine        | NATS                 | Yes                                 | Yes                               |
| Table Function      | postgresql           | No                                 | Yes                              |
| Table Function      | s3                   | No                                  | Yes                              |
| Database Engine     | MaterializedMySQL    | No                                 | Yes                              |

Please note that the above information is illustrative and needs to be confirmed. I feel that having this kind of reference table would greatly enhance the user experience and efficiency when working with MaterializedViews in ClickHouse.

**OR** because `MaterializedView` works as insert trigger. This table could be detailed as of cases that a MV would be triggered in combination with these engines and functions.

**Comment by DanRoscigno** [comment]
@ClickHouse/support-services can you help fill out a table?  I think that this suggestion from @brunorpinho is exactly right.

**Comment by alexey-milovidov** [comment]
This task is abandoned.
