### ISSUE TITLE
unexpected sql sort

### ISSUE THREAD

**Issue by glenmock** [ClickHouse/ClickHouse#51915]
**Describe the unexpected behaviour**
I want to dynamically sort by field based on date, but the sorting doesn't take effect

**How to reproduce**
version:  21.4.6.55

table info:
>  CREATE TABLE default.sort_test (
    `id` UInt64,
    `w1` UInt64,
    `w2` UInt64,
    `w3` UInt64,
    `w4` UInt64,
    `w5` UInt64,
    `w6` UInt64,
    `w7` UInt64,
    `proc_time` DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(proc_time)
PARTITION BY toYYYYMM(proc_time)
ORDER BY (id)
SETTINGS index_granularity = 8192`

data example: 
`  INSERT into default.sort_test values
(1, 2,3,4,5,6,7,8, now())
(2, 4,8,15,3,12,18,15, now())
(3, 5,9,35,13,22,28,75, now())
(4, 7,17,45,23,62,58,45, now())
(5, 8,7,25,23,22,28,25, now())
(6, 3,27,35,53,32,58,15, now())
(7, 44,6,55,13,12,88,95, now());
`

sql:
` 
with (select CONCAT('w', toString(toDayOfWeek(yesterday())))) as sortKey
select 
   w1, w2, w3, w4, w5, w6, w7
from default.sort_test
order by sortKey desc ;
`

I don't know if this counts as a bug, could you please help me fix this?

**Comment by den-crane** [comment]
you sort by a constant `order by yesterday()` What do you expect as a result?

https://fiddle.clickhouse.com/7e4ca477-d128-4575-8785-a29079430a0d

**Comment by glenmock** [comment]
@den-crane  Is there any way to identify columns and sort them by their values?

**Comment by cangyin** [comment]
> with (select CONCAT('w', toString(toDayOfWeek(yesterday())))) as sortKey select  w1, w2, w3, w4, w5, w6, w7 from default.sort_test order by sortKey desc ;

SQL statements cannot be dynamically generated and executed. you should separate it as two steps:

1. generate your "dynamic sorting key"

```sql
SELECT arrayStringConcat(groupArray(name),',') FROM system.columns WHERE database='default' AND table='sort_test';

id,w1,w2,w3,w4,w5,w6,w7,proc_time
```

2. concatenate the columns to make your final SQL statement.

**Comment by glenmock** [comment]
@cangyin 
thanks for you idea, i use below sql is success

`
with (
	select  2  -- toDayOfWeek(yesterday())
) as sortKey
select 
   w1, w2, w3, w4, w5, w6, w7
from default.sort_test
order by multiIf(sortKey = 1, w1, sortKey = 2, w2, sortKey = 3, w3, sortKey = 4, w4, sortKey = 5, w5, sortKey = 6, w6, sortKey = 7, w7, w1) desc;
`

https://fiddle.clickhouse.com/0eed7221-9222-4252-94a7-e828c6f98727
