### ISSUE TITLE
Too many TCP ESTABLISHED

### ISSUE THREAD

**Issue by RunningFaster** [ClickHouse/ClickHouse#51919]
code: 252, message: Too many parts (100003) in all partitions in total. This indicates wrong choice of partition key. The threshold can be modified with 'max_parts_in_total' setting in <merge_tree> element in config.xml or with per-table setting.

When the number of partitions in the clickhouse device exceeds the configuration, and the client fails to enter the database, the initiated TCP disconnection fails, and the TCP connection status is in.

<img width="1233" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/37316282/27a12a73-053b-4b21-9d91-f2db1da961db">
<img width="886" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/37316282/2a83f16c-d6ca-4880-869b-4b2ff3703e3b">

**Comment by cangyin** [comment]
> code: 252, message: Too many parts (100003) in all partitions in total. This indicates wrong choice of partition key. The threshold can be modified with 'max_parts_in_total' setting in <merge_tree> element in config.xml or with per-table setting.

data parts should be around 1000~10000. exceeding the default limit of `max_parts_in_total=100000` means that you are not using ClickHouse correctly.

check out the docs:
- [DB::Exception Too many parts](https://clickhouse.com/docs/knowledgebase/exception-too-many-parts), and
- [Best Practices - Choose a Low Cardinality Partitioning Key](https://clickhouse.com/docs/en/optimize/partitioning-key)

**Comment by cangyin** [comment]
as for the TCP connections, it's normal for a ClickHouse server in cluster to receive hundreds of TCP connections.

your client connections failure message already tells that the table contains too many parts, so refused to accept more inserts.

slow down the insert, do large batched, low frequency inserts. or checkout the [Asynchronous Inserts Feature](https://clickhouse.com/docs/en/cloud/bestpractices/asynchronous-inserts)
