### ISSUE TITLE
Clickhouse failed to start, permission denied

### ISSUE THREAD

**Issue by artasheskhachatryan1991** [ClickHouse/ClickHouse#51927]
Hello：
CentOS Linux release 8
ClickHouse server version 23.6.1.1524 (official build))
yum installed.

when I use command "systemctl start clickhouse-server" to start clickhouse , and Failed to start ,
clickhouse-server.err.log and clickhouse-server.log is empty .

in /var/log/message，is：

clickhouse-server[3932]: 9. DB::Server::run() @ 0x000000000e28453e in /usr/bin/clickhouse
clickhouse-server[3932]: 10. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000017bf2959 in /usr/bin/clickhouse
clickhouse-server[3932]: 11. mainEntryClickHouseServer(int, char**) @ 0x000000000e281506 in /usr/bin/clickhouse
clickhouse-server[3932]: 12. main @ 0x000000000884dccf in /usr/bin/clickhouse
clickhouse-server[3932]: 13. __libc_start_main @ 0x0000000000023493 in /usr/lib64/libc-2.28.so
clickhouse-server[3932]: 14. _start @ 0x0000000007f8802e in /usr/bin/clickhouse
clickhouse-server[3932]: Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build))
systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=233/RUNTIME_DIRECTORY
systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.
systemd[1]: Failed to start ClickHouse Server (analytic DBMS for big data).

journalctl -xe results are

-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit clickhouse-server.service has failed.
--
-- The result is failed.
Jul 07 12:36:57 systemd[1]: clickhouse-server.service: Service RestartSec=30s expired, scheduling restart.
Jul 07 12:36:57 systemd[1]: clickhouse-server.service: Scheduled restart job, restart counter is at 122.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Automatic restarting of the unit clickhouse-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jul 07 12:36:57 systemd[1]: Stopped ClickHouse Server (analytic DBMS for big data).
-- Subject: Unit clickhouse-server.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit clickhouse-server.service has finished shutting down.
Jul 07 12:36:57 systemd[1]: Starting ClickHouse Server (analytic DBMS for big data)...
-- Subject: Unit clickhouse-server.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit clickhouse-server.service has begun starting up.
clickhouse-server[3996]: Processing configuration file '/etc/clickhouse-server/config.xml'.
clickhouse-server[3996]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied >
clickhouse-server[3996]: 0. std::system_error::system_error(std::error_code, String const&) @ 0x000000001a9962b5 in /usr/bin/clickhouse
clickhouse-server[3996]: 1. ? @ 0x000000000e23e0c1 in /usr/bin/clickhouse
clickhouse-server[3996]: 2. ? @ 0x000000001a93aa5a in /usr/bin/clickhouse
clickhouse-server[3996]: 3. ? @ 0x000000001a93e196 in /usr/bin/clickhouse
clickhouse-server[3996]: 4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001a93e891 in /usr/bin/clickhouse
clickhouse-server[3996]: 5. DB::ConfigProcessor::savePreprocessedConfig(DB::ConfigProcessor::LoadedConfig const&, String) @ 0x00000000151f65a9 in /usr/bin/clickhouse
clickhouse-server[3996]: 6. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000e470eb8 in /usr/bin/clickhouse
clickhouse-server[3996]: 7. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e2846e3 in /usr/bin/clickhouse
clickhouse-server[3996]: 8. Poco::Util::Application::run() @ 0x0000000017bdf21a in /usr/bin/clickhouse
clickhouse-server[3996]: 9. DB::Server::run() @ 0x000000000e28453e in /usr/bin/clickhouse
clickhouse-server[3996]: 10. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000017bf2959 in /usr/bin/clickhouse
clickhouse-server[3996]: 11. mainEntryClickHouseServer(int, char**) @ 0x000000000e281506 in /usr/bin/clickhouse
clickhouse-server[3996]: 12. main @ 0x000000000884dccf in /usr/bin/clickhouse
clickhouse-server[3996]: 13. __libc_start_main @ 0x0000000000023493 in /usr/lib64/libc-2.28.so
clickhouse-server[3996]: 14. _start @ 0x0000000007f8802e in /usr/bin/clickhouse
clickhouse-server[3996]: Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build))
systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=233/RUNTIME_DIRECTORY
systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit clickhouse-server.service has entered the 'failed' state with result 'exit-code'.
Jul 07 12:36:57 systemd[1]: Failed to start ClickHouse Server (analytic DBMS for big data).
-- Subject: Unit clickhouse-server.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit clickhouse-server.service has failed.
--
-- The result is failed.

I checked the directory and file permissions

ll /etc/clickhouse-server/

dr-x------ 2 clickhouse clickhouse     6 Jul  5 16:51 config.d
-r-------- 1 clickhouse clickhouse 75440 Jul  7 11:23 config.xml
dr-x------ 2 clickhouse clickhouse     6 Jul  5 16:51 users.d
-r-------- 1 clickhouse clickhouse  5370 Jun 30 15:37 users.xml

ll /data/clickhouse

drwxr-x---  2 clickhouse clickhouse         116 Jul  5 16:51 access
drwxr-x---  5 clickhouse clickhouse          47 Jul  5 17:13 data
drwxr-x---  2 clickhouse clickhouse           6 Jul  5 16:51 dictionaries_lib
drwxr-x---  2 clickhouse clickhouse           6 Jul  5 16:51 flags
drwxr-x---  2 clickhouse clickhouse           6 Jul  5 16:51 format_schemas
drwxr-x---  4 clickhouse clickhouse         212 Jul  5 17:13 metadata
drwxr-x---  2 clickhouse clickhouse           6 Jul  6 20:03 metadata_dropped
drwxr-xr-x  2 clickhouse clickhouse          41 Jul  5 16:51 preprocessed_configs
-rw-r-----  1 clickhouse clickhouse          61 Jul  5 17:12 status
drwxr-x--- 18 clickhouse clickhouse         182 Jul  6 19:56 store
drwxr-x---  2 clickhouse clickhouse           6 Jul  5 16:51 tmp
drwxr-x---  2 clickhouse clickhouse           6 Jul  5 16:51 user_defined
drwxr-x---  2 clickhouse clickhouse           6 Jul  5 16:51 user_files
drwxr-x---  2 clickhouse clickhouse           6 Jul  5 16:51 user_scripts
-rw-r-----  1 clickhouse clickhouse          36 Jul  5 16:51 uuid

running this command sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml

results in error also

Processing configuration file '/etc/clickhouse-server/config.xml'.
std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied ["/data/clickhouse/preprocessed_configs"], Stack trace (when copying this message, always include the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x000000001a9962b5 in /usr/bin/clickhouse
1. ? @ 0x000000000e23e0c1 in /usr/bin/clickhouse
2. ? @ 0x000000001a93aa5a in /usr/bin/clickhouse
3. ? @ 0x000000001a93e196 in /usr/bin/clickhouse
4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001a93e891 in /usr/bin/clickhouse
5. DB::ConfigProcessor::savePreprocessedConfig(DB::ConfigProcessor::LoadedConfig const&, String) @ 0x00000000151f65a9 in /usr/bin/clickhouse
6. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000e470eb8 in /usr/bin/clickhouse
7. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e2846e3 in /usr/bin/clickhouse
8. Poco::Util::Application::run() @ 0x0000000017bdf21a in /usr/bin/clickhouse
9. DB::Server::run() @ 0x000000000e28453e in /usr/bin/clickhouse
10. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000017bf2959 in /usr/bin/clickhouse
11. mainEntryClickHouseServer(int, char**) @ 0x000000000e281506 in /usr/bin/clickhouse
12. main @ 0x000000000884dccf in /usr/bin/clickhouse
13. __libc_start_main @ 0x0000000000023493 in /usr/lib64/libc-2.28.so
14. _start @ 0x0000000007f8802e in /usr/bin/clickhouse

Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build))

Can you take a look for me? Thank you very much.

**Comment by rschu1ze** [comment]
Related: #19223

**Comment by artasheskhachatryan1991** [comment]
> 

I checked the permissions of /etc/clickhouse-server/ folder, but they seems to be correct.

**Comment by artasheskhachatryan1991** [comment]
> I am curious how you installed ClickHouse?
> 
> You could try to (temporarily) disable SELinux? Please also check permissions of folder `/data/clickhouse`.

I installed with instructions from https://clickhouse.com/docs/en/install

sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo

sudo yum install -y clickhouse-server clickhouse-client

Then I changed the data directory path in /etc/clickhouse-server/config.xml to point to /data/clickhouse folder
and I copy all the files form /var/lib/clickhouse/ to /data/clickhouse.

Output of ll -d /data/clickhouse/ 

drwx------ 15 clickhouse clickhouse 333 Jul  6 20:46 /data/clickhouse/

**Comment by artasheskhachatryan1991** [comment]
I found that the problem is with my data directory of clickhouse file. When I change to default /var/lib/clickhouse everything works fine. 

Then I create a new data directory

mkdir /data/clickhouse
chown clickhouse:clickhouse /data/clickhouse

and copy the files.

rsync -avz --progress -H /var/lib/clickhouse/ /data/clickhouse/

Now when i change the data directory in config.xml and restart clickhouse i get permission denied error.

What could be the problem?

**Comment by den-crane** [comment]
try

`sudo -u clickhouse mkdir /data/clickhouse/preprocessed_configs`

**Comment by cnzxc** [comment]
> Hello： CentOS Linux release 8 ClickHouse server version 23.6.1.1524 (official build)) yum installed.
> 
> when I use command "systemctl start clickhouse-server" to start clickhouse , and Failed to start , clickhouse-server.err.log and clickhouse-server.log is empty .
> 
> in /var/log/message，is：
> 
> clickhouse-server[3932]: 9. DB::Server::run() @ 0x000000000e28453e in /usr/bin/clickhouse clickhouse-server[3932]: 10. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000017bf2959 in /usr/bin/clickhouse clickhouse-server[3932]: 11. mainEntryClickHouseServer(int, char**) @ 0x000000000e281506 in /usr/bin/clickhouse clickhouse-server[3932]: 12. main @ 0x000000000884dccf in /usr/bin/clickhouse clickhouse-server[3932]: 13. __libc_start_main @ 0x0000000000023493 in /usr/lib64/libc-2.28.so clickhouse-server[3932]: 14. _start @ 0x0000000007f8802e in /usr/bin/clickhouse clickhouse-server[3932]: Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build)) systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=233/RUNTIME_DIRECTORY systemd[1]: clickhouse-server.service: Failed with result 'exit-code'. systemd[1]: Failed to start ClickHouse Server (analytic DBMS for big data).
> 
> journalctl -xe results are
> 
> ## -- Defined-By: systemd
> -- Support: https://access.redhat.com/support
> ## -- Unit clickhouse-server.service has failed.
> ## -- The result is failed.
> Jul 07 12:36:57 systemd[1]: clickhouse-server.service: Service RestartSec=30s expired, scheduling restart.
> Jul 07 12:36:57 systemd[1]: clickhouse-server.service: Scheduled restart job, restart counter is at 122.
> -- Subject: Automatic restarting of a unit has been scheduled
> -- Defined-By: systemd
> -- Support: https://access.redhat.com/support
> ## -- Automatic restarting of the unit clickhouse-server.service has been scheduled, as the result for
> -- the configured Restart= setting for the unit.
> Jul 07 12:36:57 systemd[1]: Stopped ClickHouse Server (analytic DBMS for big data).
> -- Subject: Unit clickhouse-server.service has finished shutting down
> -- Defined-By: systemd
> -- Support: https://access.redhat.com/support
> ## -- Unit clickhouse-server.service has finished shutting down.
> Jul 07 12:36:57 systemd[1]: Starting ClickHouse Server (analytic DBMS for big data)...
> -- Subject: Unit clickhouse-server.service has begun start-up
> -- Defined-By: systemd
> -- Support: https://access.redhat.com/support
> ## -- Unit clickhouse-server.service has begun starting up.
> clickhouse-server[3996]: Processing configuration file '/etc/clickhouse-server/config.xml'.
> clickhouse-server[3996]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied >
> clickhouse-server[3996]: 0. std::system_error::system_error(std::error_code, String const&) @ 0x000000001a9962b5 in /usr/bin/clickhouse
> clickhouse-server[3996]: 1. ? @ 0x000000000e23e0c1 in /usr/bin/clickhouse
> clickhouse-server[3996]: 2. ? @ 0x000000001a93aa5a in /usr/bin/clickhouse
> clickhouse-server[3996]: 3. ? @ 0x000000001a93e196 in /usr/bin/clickhouse
> clickhouse-server[3996]: 4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001a93e891 in /usr/bin/clickhouse
> clickhouse-server[3996]: 5. DB::ConfigProcessor::savePreprocessedConfig(DB::ConfigProcessor::LoadedConfig const&, String) @ 0x00000000151f65a9 in /usr/bin/clickhouse
> clickhouse-server[3996]: 6. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000e470eb8 in /usr/bin/clickhouse
> clickhouse-server[3996]: 7. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e2846e3 in /usr/bin/clickhouse
> clickhouse-server[3996]: 8. Poco::Util::Application::run() @ 0x0000000017bdf21a in /usr/bin/clickhouse
> clickhouse-server[3996]: 9. DB::Server::run() @ 0x000000000e28453e in /usr/bin/clickhouse
> clickhouse-server[3996]: 10. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000017bf2959 in /usr/bin/clickhouse
> clickhouse-server[3996]: 11. mainEntryClickHouseServer(int, char**) @ 0x000000000e281506 in /usr/bin/clickhouse
> clickhouse-server[3996]: 12. main @ 0x000000000884dccf in /usr/bin/clickhouse
> clickhouse-server[3996]: 13. __libc_start_main @ 0x0000000000023493 in /usr/lib64/libc-2.28.so
> clickhouse-server[3996]: 14. _start @ 0x0000000007f8802e in /usr/bin/clickhouse
> clickhouse-server[3996]: Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build))
> systemd[1]: clickhouse-server.service: Main process exited, code=exited, status=233/RUNTIME_DIRECTORY
> systemd[1]: clickhouse-server.service: Failed with result 'exit-code'.
> -- Subject: Unit failed
> -- Defined-By: systemd
> -- Support: https://access.redhat.com/support
> ## -- The unit clickhouse-server.service has entered the 'failed' state with result 'exit-code'.
> Jul 07 12:36:57 systemd[1]: Failed to start ClickHouse Server (analytic DBMS for big data).
> -- Subject: Unit clickhouse-server.service has failed
> -- Defined-By: systemd
> -- Support: https://access.redhat.com/support
> ## -- Unit clickhouse-server.service has failed.
> -- The result is failed.
> 
> I checked the directory and file permissions
> 
> ll /etc/clickhouse-server/
> 
> dr-x------ 2 clickhouse clickhouse 6 Jul 5 16:51 config.d -r-------- 1 clickhouse clickhouse 75440 Jul 7 11:23 config.xml dr-x------ 2 clickhouse clickhouse 6 Jul 5 16:51 users.d -r-------- 1 clickhouse clickhouse 5370 Jun 30 15:37 users.xml
> 
> ll /data/clickhouse
> 
> drwxr-x--- 2 clickhouse clickhouse 116 Jul 5 16:51 access drwxr-x--- 5 clickhouse clickhouse 47 Jul 5 17:13 data drwxr-x--- 2 clickhouse clickhouse 6 Jul 5 16:51 dictionaries_lib drwxr-x--- 2 clickhouse clickhouse 6 Jul 5 16:51 flags drwxr-x--- 2 clickhouse clickhouse 6 Jul 5 16:51 format_schemas drwxr-x--- 4 clickhouse clickhouse 212 Jul 5 17:13 metadata drwxr-x--- 2 clickhouse clickhouse 6 Jul 6 20:03 metadata_dropped drwxr-xr-x 2 clickhouse clickhouse 41 Jul 5 16:51 preprocessed_configs -rw-r----- 1 clickhouse clickhouse 61 Jul 5 17:12 status drwxr-x--- 18 clickhouse clickhouse 182 Jul 6 19:56 store drwxr-x--- 2 clickhouse clickhouse 6 Jul 5 16:51 tmp drwxr-x--- 2 clickhouse clickhouse 6 Jul 5 16:51 user_defined drwxr-x--- 2 clickhouse clickhouse 6 Jul 5 16:51 user_files drwxr-x--- 2 clickhouse clickhouse 6 Jul 5 16:51 user_scripts -rw-r----- 1 clickhouse clickhouse 36 Jul 5 16:51 uuid
> 
> running this command sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
> 
> results in error also
> 
> Processing configuration file '/etc/clickhouse-server/config.xml'. std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied ["/data/clickhouse/preprocessed_configs"], Stack trace (when copying this message, always include the lines below):
> 
> 0. std::system_error::system_error(std::error_code, String const&) @ 0x000000001a9962b5 in /usr/bin/clickhouse
> 1. ? @ 0x000000000e23e0c1 in /usr/bin/clickhouse
> 2. ? @ 0x000000001a93aa5a in /usr/bin/clickhouse
> 3. ? @ 0x000000001a93e196 in /usr/bin/clickhouse
> 4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001a93e891 in /usr/bin/clickhouse
> 5. DB::ConfigProcessor::savePreprocessedConfig(DB::ConfigProcessor::LoadedConfig const&, String) @ 0x00000000151f65a9 in /usr/bin/clickhouse
> 6. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000e470eb8 in /usr/bin/clickhouse
> 7. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000e2846e3 in /usr/bin/clickhouse
> 8. Poco::Util::Application::run() @ 0x0000000017bdf21a in /usr/bin/clickhouse
> 9. DB::Server::run() @ 0x000000000e28453e in /usr/bin/clickhouse
> 10. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000017bf2959 in /usr/bin/clickhouse
> 11. mainEntryClickHouseServer(int, char**) @ 0x000000000e281506 in /usr/bin/clickhouse
> 12. main @ 0x000000000884dccf in /usr/bin/clickhouse
> 13. __libc_start_main @ 0x0000000000023493 in /usr/lib64/libc-2.28.so
> 14. _start @ 0x0000000007f8802e in /usr/bin/clickhouse
> 
> Cannot print extra info for Poco::Exception (version 23.6.1.1524 (official build))
> 
> Can you take a look for me? Thank you very much.

Hi, How do you solve this problem? I have similar error.

**Comment by cnzxc** [comment]
Hi, How do you solve this problem? I have similar error.

**Comment by WenlYang** [comment]
Hi, How do you solve this problem? I have similar error. my clickhouse version is 24.4.1.2088
