### ISSUE TITLE
[Feature] filter cluase or filter syntax support

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#51930]
SQL:2003 introduced the filter clause as part of the optional feature “Advanced OLAP operations” (T612). pg had impelements.

refer to:
https://modern-sql.com/feature/filter
refer postgresql:
https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES

refer trino:
https://trino.io/docs/current/functions/aggregate.html#

Use case
simple the SQL statement

**Comment by UnamedRus** [comment]
Already exist in ClickHouse

https://github.com/ClickHouse/ClickHouse/issues/26776

Internally being rewritten to -If combinator

```
AVG(xxx) FILTER (WHERE x = 1) is just avgIf(xxx, x=1)
```

**Comment by vkingnew** [comment]
Good ,I found the official doc
[https://clickhouse.com/docs/knowledgebase/filtered-aggregates](url)

**Comment by vkingnew** [comment]
@UnamedRus  do you know From which version support this feature?

**Comment by UnamedRus** [comment]
Old, ~21.9
