### ISSUE TITLE
How to read the binary output from -State in external program/UDF

### ISSUE THREAD

**Issue by srikanthccv** [ClickHouse/ClickHouse#51957]
Hello 👋 ,

I am using [`AggregateFunction `](https://clickhouse.com/docs/en/sql-reference/data-types/aggregatefunction) data type for one of the columns. I have a use case where the output of `-MergeState` will be used in custom UDF and return the result. Example 
```sql
SELECT quantileTDigestWeightedState(0.9)(toFloat64(bound), toUInt64(weight)) AS state
FROM
(
    SELECT
        bound,
        weight
    FROM
    (
        SELECT
            [0, 1, 2, 4, 8, 16, 32, 64] AS bounds,
            [0, 1, 9, 3, 3, 3, 2, 5] AS weights
    )
    ARRAY JOIN
        bounds AS bound,
        weights AS weight
)
```
There don't appear to be any docs around using this correctly. I looked at the source code of `deserialize` for some hints and got some bits working, but I could not get it to work right.  Here is the go code in UDF.

```go
buf := bytes.NewBuffer(input)
size, _ := binary.ReadUvarint(buf)
for i := 0; i < int(size); i++ {
	var bound float64
	var weight uint64
	binary.Read(buf, binary.LittleEndian, &bound)
	binary.Read(buf, binary.LittleEndian, &weight)
}
```

This is reading the input data. However, when I look at the value for bound and weight, they are incorrect and not what I expected. Is that the correct way to read and deserialize the data? I would really appreciate any help with this.

**Comment by alexey-milovidov** [comment]
You can dump the value in hex format and go byte by byte, comparing it with the behavior of your program.
