### ISSUE TITLE
Parallel replicas: wrong block size

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#51960]
![ParalelReplicas](https://github.com/ClickHouse/ClickHouse/assets/18581488/96292a0f-cc9c-4e90-8f7d-40d854e11f04)

```
SET use_hedged_requests = false, max_parallel_replicas = 3, cluster_for_parallel_replicas = 'parallel_replicas', allow_experimental_parallel_reading_from_replicas = 1, parallel_replicas_for_non_replicated_merge_tree = 1;

CREATE TABLE nested (x UInt8) ENGINE = MergeTree ORDER BY ();
INSERT INTO nested VALUES (1);

SELECT 1 FROM nested
GROUP BY 1 WITH ROLLUP
ORDER BY max((SELECT 1 WHERE 0));
```

https://fiddle.clickhouse.com/e340a1e8-5ec2-496e-8fd4-5518199fb16a

**Comment by alexey-milovidov** [comment]
Logical error: https://fiddle.clickhouse.com/30c22627-9083-4519-8634-4f5f36a2c470

**Comment by alexey-milovidov** [comment]
Reproduced on master.

**Comment by Algunenano** [comment]
Seems to be working fine in 23.9. I'll add a test to confirm that parallel replicas test this query.
