### ISSUE TITLE
Different results using "group by" or not with splitByChar function.

### ISSUE THREAD

**Issue by jppo** [ClickHouse/ClickHouse#51997]
Hello,
Using clickhouse client I get different form of result.
1) Without "group by" :
select splitByChar('.',IP_SRC_ADDR,2) as SUBNET from flowsv4 
where OUT_BYTES = 0 
  and IP_SRC_ADDR not like '192.168.1.%'
  and IP_SRC_ADDR not like '192.168.2.%'
limit 4;
Result :
┌─SUBNET────────┐
│ ['192','241'] │
│ ['188','120'] │
│ ['185','191'] │
│ ['194','26']  │
└───────────────┘
Which seems OK.
2) With "group by".
select splitByChar('.',IP_SRC_ADDR,2) as SUBNET from flowsv4 
where OUT_BYTES = 0 
  and IP_SRC_ADDR not like '192.168.1.%'
  and IP_SRC_ADDR not like '192.168.2.%'
group by 1
limit 4;
Result :
┌─SUBNET─────────┐
│ ['2783463875'] │
│ ['99','141']   │
│ ['1023091742'] │
│ ['2807990924'] │
└────────────────┘
That result is a little strange, the splitByChar function gives other values which does not sdeems OK.
3) For information about "raw" data as example :
SELECT IP_SRC_ADDR
FROM flowsv4
WHERE (OUT_BYTES = 0) AND (IP_SRC_ADDR NOT LIKE '192.168.1.%') AND (IP_SRC_ADDR NOT LIKE '192.168.2.%')
LIMIT 4
Result :
┌─IP_SRC_ADDR─────┐
│ 209.126.102.181 │
│ 141.8.132.80    │
│ 141.8.132.80    │
│ 80.82.65.120    │
└─────────────────┘
Data are IP V4 addresses I want to count by Subnet.

Regards

JP P

**Comment by UnamedRus** [comment]
Which version?

**Comment by UnamedRus** [comment]
```
SELECT splitByChar('.', toIPv4('209.126.102.181'), 2)

Query id: 0c11bad2-7e02-4818-a0b6-3724bba4d095


0 rows in set. Elapsed: 0.001 sec.

Received exception:
Code: 43. DB::Exception: Illegal type IPv4 of second argument of function splitByChar. Must be String.: While processing splitByChar('.', toIPv4('209.126.102.181'), 2). (ILLEGAL_TYPE_OF_ARGUMENT)



SELECT splitByChar('.', CAST(toIPv4('209.126.102.181'), 'String'), 2)



┌─splitByChar('.', CAST(toIPv4('209.126.102.181'), 'String'), 2)─┐
│ ['209','126']                                                  │
└────────────────────────────────────────────────────────────────┘
```

Can you check using IPv4NumToString function before splitByChar

**Comment by jppo** [comment]
Hello, 

I forgot the version in the bug : 23.6.2.18, the last one on Debian 11. 

Regards 

JP P 



De: "UnamedRus" ***@***.***> 
À: "ClickHouse/ClickHouse" ***@***.***> 
Cc: "JPPO" ***@***.***>, "Author" ***@***.***> 
Envoyé: Dimanche 9 Juillet 2023 21:41:00 
Objet: Re: [ClickHouse/ClickHouse] Different results using "group by" or not with splitByChar function. (Issue #51997) 





Which version?

**Comment by jppo** [comment]
Hello,
The IP_SRC_ADDR field is described as "string" in the table.
Hope this helps.

Regards
JP P

**Comment by den-crane** [comment]
it's expected behaviour. Queries without `ORDER BY` yield random rows with limit.

**Comment by jppo** [comment]
Hello,

I'll try to try with an "order by" but I'm going on vacation tomorrow ... and
have no access to my virtual systems.This behavior (two values only become one)
seems to me a little "borderline". I know different database systems but I have
never seen that, an error message would certainly be better than displaying
outliers.

Regards

JP P

**Comment by jppo** [comment]
Hello,
I try : 
select splitByChar('.',IP_SRC_ADDR,2) as SUBNET,count(*) from flowsv4 
where OUT_BYTES = 0 
  and IP_SRC_ADDR not like '192.168.1.%'
  and IP_SRC_ADDR not like '192.168.2.%'
group by 1
order by 2 desc
;
┌─[SUBNET─────────┬─count()─┐
│ ['3232236099'] │ 3653473 │
│ ['3232236034'] │ 2017740 │
│ ['3232236053'] │ 1130731 │
│ ['3232235778'] │  619527 │
│ ['3232236112'] │  555927 │
│ ['3232235807'] │  524437 │
.......

**Comment by den-crane** [comment]
> I try :

This looks correct.
