### ISSUE TITLE
Searching for some measuring codes of cpu and caches.

### ISSUE THREAD

**Issue by sunny-vito123456** [ClickHouse/ClickHouse#51994]
Our group is working on a project. One important part is to find the measuring codes of the CPU and cache in Clickhouse and noisepage.(Source code for noisepage：https://github.com/cmu-db/noisepage).The relevant variables in noisepage are very easy to find, because the author directly declared the variables. But I am currently unable to find the measurement function for the relevant variables in Clickhouse.So I will show the variables in noisepage, hoping that someone can help me find the corresponding measurement function in Clickhouse.

noisepage:src/include/common/perf_monitor.h:
    /**
     * Should always be NUM_HW_EVENTS after a read since that's how many counters we have.
     */
    uint64_t num_counters_;

    /**
     * Total cycles. Be wary of what happens during CPU frequency scaling.
     */
    uint64_t cpu_cycles_;
    /**
     * Retired instructions. Be careful, these can be affected by various issues, most notably hardware interrupt
     * counts.
     */
    uint64_t instructions_;
    /**
     * Cache accesses. Usually this indicates Last Level Cache accesses but this may vary depending on your CPU.  This
     * may include prefetches and coherency messages; again this depends on the design of your CPU.
     */
    uint64_t cache_references_;
    /**
     * Cache misses.  Usually this indicates Last Level Cache misses.
     */
    uint64_t cache_misses_;
    // TODO(Matt): there seems to be a bug with enabling these counters along with the cache counters. When enabled,
    // just get 0s out of all of the counters. Eventually we might want them but can't enable them right now.
    // https://lkml.org/lkml/2018/2/13/810
    // uint64_t branch_instructions_;
    // uint64_t branch_misses_;
    /**
     * Bus cycles, which can be different from total cycles.
     *
     * TODO(wz2): Dated Nov 5th, 2020 on dev4. Recording {cycle,instr,cache-ref,cache-miss,bus,ref-cpu} causes all
     * the counters to get zeroed. This counter currently isn't exposed to the rest of the system so it is disabled
     * pending further investigation. Possibly might be related to limited intel performance counters per core.
     */
    // uint64_t bus_cycles_;
    /**
     * Total cycles; not affected by CPU frequency scaling.
     */
    uint64_t ref_cpu_cycles_;
The five variables ‘uint64_t cpu_cycles_;  uint64_t instructions_; uint64_t cache_references_; uint64_t cache_misses_;uint64_t cpu_time_’ are what we want.(cpu_time_ doesn't locate in perf_monitor.h,it locates somewhere else).

The code of cpu_time_ has been found in Clickhouse:src/Common/ProgressIndication.cpp:
UInt64 ProgressIndication::getElapsedNanoseconds() const
{
    /// New server versions send server-side elapsed time, which is preferred for calculations.
    UInt64 server_elapsed_ns = progress.elapsed_ns.load(std::memory_order_relaxed);
    return server_elapsed_ns ? server_elapsed_ns : watch.elapsed();
}
void ProgressIndication::updateThreadEventData(HostToTimesMap & new_hosts_data)
{
    std::lock_guard lock(profile_events_mutex);

    constexpr UInt64 us_to_ns = 1000;

    UInt64 total_cpu_ns = 0;
    for (auto & new_host : new_hosts_data)
    {
        total_cpu_ns += us_to_ns * new_host.second.time();
        hosts_data[new_host.first] = new_host.second;
    }
    cpu_usage_meter.add(getElapsedNanoseconds(), total_cpu_ns);
}
double ProgressIndication::getCPUUsage()
{
    std::lock_guard lock(profile_events_mutex);
    return cpu_usage_meter.rate(getElapsedNanoseconds());
}
However,we still need to test cpu_cycles_,instructions_,cache_references_ and cache_misses_ .They may have different names but the same meanings,for example,cpu_time_ is called total_cpu_ns in Clickhouse.Could you help me find where they are measured?Please show me the codes and their locations.

**Comment by CheSema** [comment]
It looks like you are interesting in `PerfEventsCounters`.
https://github.com/ClickHouse/ClickHouse/blob/4bb95305a477142baee094ec881e9dd0cbf5c2cc/src/Common/ThreadProfileEvents.cpp#L220-L255

There are a set of such counters, please see the list.

You could gather them by default for all queries or just for the one at demand.
See the settings `metrics_perf_events_enabled` and `metrics_perf_events_list`.
https://github.com/ClickHouse/ClickHouse/blob/4bb95305a477142baee094ec881e9dd0cbf5c2cc/src/Core/Settings.h#L335-L336

The result of measurement you can find in tables system.query_log  system.query_thread_log. Check that they are enabled in the config.

```
functional-tests :) SELECT toInt128(number) * number FROM numbers_mt(1000000000) FORMAT Null SETTINGS metrics_perf_events_enabled=1

SELECT toInt128(number) * number
FROM numbers_mt(1000000000)
FORMAT `Null`
SETTINGS metrics_perf_events_enabled = 1

Query id: c9f9694a-5065-4c6c-8789-2a295f5e7b13

Ok.

0 rows in set. Elapsed: 0.694 sec. Processed 1.00 billion rows, 8.00 GB (1.44 billion rows/s., 11.53 GB/s.)

functional-tests :) select ProfileEvents from system.query_log where query_id = 'c9f9694a-5065-4c6c-8789-2a295f5e7b13' and type = 'QueryFinish'

SELECT ProfileEvents
FROM system.query_log
WHERE (query_id = 'c9f9694a-5065-4c6c-8789-2a295f5e7b13') AND (type = 'QueryFinish')

Query id: b9815de0-ebd5-44cc-a255-a0eea945c48f

┌─ProfileEvents──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ {'Query':1,'SelectQuery':1,'QueriesWithSubqueries':1,'SelectQueriesWithSubqueries':1,'FunctionExecute':30578,'TableFunctionExecute':1,'NetworkReceiveElapsedMicroseconds':38,'NetworkSendElapsedMicroseconds':456,'NetworkSendBytes':9059,'SelectedRows':1000000000,'SelectedBytes':8000000000,'ContextLock':23,'RWLockAcquiredReadLocks':1,'RealTimeMicroseconds':12834944,'UserTimeMicroseconds':6262976,'SystemTimeMicroseconds':1292128,'SoftPageFaults':40053,'OSCPUWaitMicroseconds':2837,'OSCPUVirtualTimeMicroseconds':7516623,'OSReadChars':411202,'OSWriteChars':38111,'PerfCpuCycles':16821028832,'PerfInstructions':1132587550680,'PerfCacheReferences':3232172115845,'PerfCacheMisses':6114786285716,'PerfBranchInstructions':6222100064462,'PerfBranchMisses':2936878,'PerfBusCycles':26330615889621,'PerfRefCpuCycles':15480839703,'PerfCpuClock':5878221124,'PerfTaskClock':5879324544,'PerfContextSwitches':1354856616932,'PerfCpuMigrations':912839966729,'PerfMinEnabledTime':5358989111,'PerfMinEnabledRunningTime':5633342109,'PerfDataTLBReferences':18187103704534,'PerfDataTLBMisses':1441982,'PerfInstructionTLBReferences':761605787158,'PerfInstructionTLBMisses':715515,'QueryProfilerRuns':20,'LogTrace':1,'LogDebug':1,'LogWarning':40} │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.003 sec. 
```

The table system.query_thread_log has more detailed information for each thread which participated in query calculation.

**Comment by sunny-vito123456** [comment]
My problem has not been completely solved yet.The above code only reads the relevant variables from the system.Where can I see the code for assignment？Is that CPUInfo?

**Comment by alexey-milovidov** [comment]
Check the pull request where these metrics were added: https://github.com/ClickHouse/ClickHouse/pull/11226
It was a student coursework three years ago.

**Comment by alexey-milovidov** [comment]
@sunny-vito123456, please send a link to your research project when you will finish it.
