### ISSUE TITLE
Query should be much faster when WHERE does not match

### ISSUE THREAD

**Issue by amirvaza** [ClickHouse/ClickHouse#51999]
Hi all,

I'm trying to figure why ClickHouse would read the column 'MyDict' content even when the WHERE is always false.

I thought ClickHouse would read only when the row matches the WHERE.

This makes the query 3 times slower than using another non-dict column

```
SELECT MyDict['Page Title']
FROM myTable
WHERE UserIdHash % 100000000 < 0 -- always false
```

ClickHouse v23.6
Used SET min_bytes_to_use_direct_io=1

Thanks

**Comment by UnamedRus** [comment]
What type of UserIdHash column?

**Comment by den-crane** [comment]
try

```
SELECT MyDict['Page Title']
FROM myTable
PREWHERE UserIdHash % 100000000 < 0 -- always false
```

**Comment by amirvaza** [comment]
> try
> 
> ```
> SELECT MyDict['Page Title']
> FROM myTable
> PREWHERE UserIdHash % 100000000 < 0 -- always false
> ```

Indeed now the speed makes more sense.

Although I'm struggling to guess if I should use PREWHERE or WHERE for a specific filter before running it..

Thanks for the info in Telegram, putting here for whoever finds this thread:
PREWHERE vs WHERE: https://www.perplexity.ai/search/0de1ca71-07db-474f-956a-3fe1c14bd1a5?s=u

Message by: Aliaksandr Valialkin

> As I know, ClickHouse performs the query in the following way:
> 
> 
> 1. It selects data blocks, which can contain the needed data according to the used WHERE filters on columns mentioned in the PARTITION BY, ORDER BY, skip indexes and other index types.
> 2. It reads all the data in the selected blocks across all the columns mentioned in the query, at both SELECT and WHERE clauses. These columns are read in parallel for achieving high performance, so columns data may be read even if it is filtered by WHERE filters later.
> 
> PREWHERE clause adds an intermediate step between steps 1 and 2 above - ClickHouse reads only those columns, which are mentioned inside PREWHERE, then applies filtering to the read rows according to PREWHERE filters, and drops data blocks, which have no any matching rows, from the list of blocks, which need to be read at the next step. If PREWHERE filters out big share of blocks, then this can speed up the query significantly by eliminating the need to read unneeded data in the skipped blocks at the next step.
> 
> This is my naive understanding on how PREWHERE works. It is based on my ClickHouse knowledge from 2016-2017 years, so it may be slightly incorrect.

**Comment by den-crane** [comment]
>Indeed now the speed makes more sense.

The only question why it did not work automatically.

Please provide `show create table myTable` and `select name, value from system.settings where changed`
