### ISSUE TITLE
OPTIMIZE CLEANUP doesn't work on >50GB ReplacingMergeTree tables

### ISSUE THREAD

**Issue by geopet85** [ClickHouse/ClickHouse#52001]
We have a large ReplacingMergeTree table, >50GB in size. 

`│ X   │ 59.81 GiB   │ 1534936461 │ 2023-07-10 07:09:51 │  64217420978 │ ReplicatedReplacingMergeTree │ 2.88 MiB          │
`
and X is created as: 

```
CREATE TABLE X
(
    ...
    `_is_deleted` UInt8,
    `_version` UInt64
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{cluster}/tables/{database}/{name}', '{replica}', _version, _is_deleted)
PRIMARY KEY (...)
ORDER BY (...)
SETTINGS min_age_to_force_merge_seconds = 600, min_age_to_force_merge_on_partition_only = 1, index_granularity = 8192
```

So we are using the deleted column of ReplacingMergeTrees but we have disabled automatic cleanup. 
Besides adding partitions which is in my TODO, as a first step to reduce disk size I executed the following:

`OPTIMIZE TABLE X FINAL CLEANUP`

However this executes within 1sec, and it seems like it's not doing anything. 
Does CLEANUP also have a limit of 50GB as other operations (we use default settings)?

**Comment by den-crane** [comment]
try this to reveal of a reason `OPTIMIZE TABLE X FINAL CLEANUP settings optimize_throw_if_noop=1`
