### ISSUE TITLE
Wrong schema detected while uploading CSV file

### ISSUE THREAD

**Issue by shabir1** [ClickHouse/ClickHouse#52000]
> I have an amount column in a CSV file, which is float but one of its values contains a string value and clickhouse detects it as FLOAT64 type, But when I run a SELECT query, it throws the parsing error.

I upload a CSV file by using the below query:

`CREATE TABLE test ENGINE=File(CSV,  'test.csv')`

**Error**
Error while running the `SELECT * FROM test` query
```
Code: 117. DB::Exception: Expected end of line: (at row 1473)
: 
Row 1472:
Column 0,   name: id,      type: Nullable(Int64),   parsed text: "4268212"
Column 1,   name: Date, type: Nullable(Date),    parsed text: "2022-08-10"
Column 2,   name: mid,      type: Nullable(Int64),   parsed text: "0000012"
Column 3,   name: Amount,    type: Nullable(Float64), parsed text: "14220.0"


Row 1473:
Column 0,   name: id,      type: Nullable(Int64),   parsed text: "3368212"
Column 1,   name: Date, type: Nullable(Date),    parsed text: "2022-08-10"
Column 2,   name: mid,      type: Nullable(Int64),   parsed text: "03319865"
Column 3,   name: Amount,    type: Nullable(Float64), parsed text: "56"
ERROR: garbage after Nullable(Float64): "i40.0<LINE FEED>0000"

: While executing ParallelParsingBlockInputFormat: While executing File. (INCORRECT_DATA) (version 23.6.1.1524 (official build))
```

**How to reproduce**

* Upload a CSV file with a float or int column and put a string value in that column but in the middle or in a random position.
* Check the schema of the table.
* If it is int/float then run the select query, if it detects it as STRING then repeat step 1 till it detects it as numeric.

**Expected behavior**

> Either it detects it as STRING if it contains any STRING value or if it detects it as a numeric column then It should handle SELECT query error.

**Important points**
clickhouse version: 23.6.1.1524
Schema detection is somehow random because sometimes it detects the same column as STRING and sometimes FLOAT.

**Comment by den-crane** [comment]
duplicate of https://github.com/ClickHouse/ClickHouse/issues/52006
