### ISSUE TITLE
When launching queries in multiple threads, they run slower than when running them sequentially

### ISSUE THREAD

**Issue by eblio** [ClickHouse/ClickHouse#52003]
**Unexpected behavior**
I have a set of 10 similar queries. Each one of them run in a few seconds when executed in a single thread (around 5 seconds). However, when launching them in separate threads they individually run much slower (more than 20 seconds). 

**How to reproduce**
* ClickHouse server version : `22.3.12.19` ;
* Cluster specifications : 2 shards with 2 replicas each, 80 cores (Intel(R) Xeon(R) Gold 6148 CPU) and 756 Go RAM per machine ;
* Interface to use : managed to reproduced the issue using `clickhouse-client` CLI and ClickHouse JDBC ;

I first encountered the issue when running the queries in Java, eventually manage to reproduce them in a Bash script to ensure ClickHouse JDBC wasn't the issue.

```bash
function time_request () {
  start=$(date +%s%N)
  clickhouse-client -q "$1"
  end=$(date +%s%N)
  delta=$((end - start))
  echo "$delta" " > " "$2"
}

i=0
while read -r line;
do
  i=$((i + 1))
  time_request "$line" "$i"& # Whithout the "&" to run them sequentially
done < queries.txt
```

All of my queries have a similar structure : they insert data in a freshly created `Memory()` (hence local) table, this data is extracted from a distributed table joined with a local table. Here's the overall look of my query : 

```sql
create table `database`.`local_data_table_1` (
    `c1` Nullable(Float64),
    `c2` Nullable(Float64),
    `datetime` DateTime,
    `ne_extended` Nullable(String),
    `ne`       String
) engine = Memory;

INSERT INTO `database`.`local_data_table_1` (
  `c1`, `c2`,
  `datetime`, `ne_extended`, `ne`
) 
SELECT 
  max(`_509`.`c1`) AS `c1`, 
  max(`_509`.`c2`) AS `c2`, 
  max(`_509`.`datetime`) AS `datetime`, 
  max(`_509`.`ne_extended`) AS `ne_extended`, 
  max(`_509`.`ne`) AS `ne` 
FROM 
  (
    SELECT 
      CAST(max(`distributed_counter_data_1`.`c1`), 'Nullable(Float64)') AS `c1`, 
      CAST(NULL, 'Nullable(Float64)') AS `c2`, 
      CAST(max(`distributed_counter_data_1`.`datetime`), 'Nullable(DateTime)') AS `datetime`, 
      CAST(max(`ne_extended`), 'Nullable(String)') AS `ne_extended`, 
      CAST(max(`distributed_counter_data_1`.`ne`), 'Nullable(String)') AS `ne` 
    FROM 
      `database`.`distributed_counter_data_1` GLOBAL 
      INNER JOIN (
        SELECT 
          CAST(`local_join_table`.`datetime`, 'Nullable(DateTime)') AS `datetime`, 
          CAST(`local_join_table`.`ne_extended`, 'Nullable(String)') AS `ne_extended`, 
          CAST(`local_join_table`.`ne`, 'Nullable(String)') AS `ne` 
        FROM 
          `temp_engine`.`local_join_table`
      ) AS `_439` ON (
        CAST(`distributed_counter_data_1`.`ne`, 'Nullable(String)') = CAST(`_439`.`ne`, 'Nullable(String)') 
        AND 
        CAST(`distributed_counter_data_1`.`datetime`, 'Nullable(DateTime)') = CAST(`_439`.`datetime`, 'Nullable(DateTime)')
      )
    GROUP BY 
      `distributed_counter_data_1`.`ne`, 
      `distributed_counter_data_1`.`datetime` 
    UNION ALL 
    SELECT 
      CAST(NULL, 'Nullable(Float64)') AS `c1`, 
      CAST(max(`distributed_counter_data_1`.`c2`), 'Nullable(Float64)') AS `c2`,
      CAST(max(`distributed_counter_data_1`.`datetime`), 'Nullable(DateTime)') AS `datetime`, 
      CAST(max(`ne_extended`), 'Nullable(String)') AS `ne_extended`, 
      CAST(max(`distributed_counter_data_1`.`ne`), 'Nullable(String)') AS `ne` 
    FROM 
      `database`.`distributed_counter_data_1` GLOBAL 
      INNER JOIN (
        SELECT 
          CAST(`local_join_table`.`datetime`, 'Nullable(DateTime)') AS `datetime`, 
          CAST(`local_join_table`.`ne_extended`, 'Nullable(String)') AS `ne_extended`, 
          CAST(`local_join_table`.`ne`, 'Nullable(String)') AS `ne` 
        FROM 
          `temp_engine`.`local_join_table`
      ) AS `_466` ON (
        CAST(`distributed_counter_data_1`.`ne`, 'Nullable(String)') = CAST(`_466`.`ne`, 'Nullable(String)') 
        AND 
        CAST(`distributed_counter_data_1`.`datetime`, 'Nullable(DateTime)') = CAST(`_466`.`datetime`, 'Nullable(DateTime)')
      ) 
    GROUP BY 
      `distributed_counter_data_1`.`ne`, 
      `distributed_counter_data_1`.`datetime` 
  ) AS `_509` 
GROUP BY 
  `_509`.`ne`, 
  `_509`.`datetime`
```

All other queries are similar except they select a different number of columns, from various `distributed_counter_data_X` tables and insert them into various `local_data_table_X` tables.

I cannot provide a complete way to reproduce the issue at the moment, but I might try in case it's necessary.

The `local_join_table` table contains around 300,000 lines of data. I understand it needs to be copied to shards when running the query, and that's probably the bottleneck of my queries. I believe there is some lock mechanism that prevent my request to run in parallel, but I can't quite get it.

When running the queries in various threads, `clickhouse-client` release all the queries results at the same time, as if the queries were interdependent, while they look independent. 

I tried to modify the queries in various way, with no different outcome. Does anybody have any idea of what could be the issue ?

I remain available in case you need additional information.

**Comment by den-crane** [comment]
that's completely expected, there is a compete for resources which creates cache eviction.

**Comment by eblio** [comment]
Alright.

A few hypothesis on which resources there might be a competition : 
* Reading the local table in order to copy it before joining (`GLOBAL` behavior) : no, as I understand, there is no locking when reading from such table ;
* Writing the local table to the target (still `GLOBAL` behavior) : well, maybe as they are all the same, they share the same name. However, I have been able to test with different tables and obtained the same result, so no, it's not that ;
* CPU for query execution : those servers receive hundreds of request at the same time, they should be able to handle a few more without such a large impact ;
* I/O to send the local table to the replicas (in case all requests share one link) : that's my strongest guess, but I'm not sure ;

I may be missing something obvious. Any insights ?

**Comment by eblio** [comment]
I see. It may not have been obvious in my original message, but each request works on a different distributed table. They also write to a different local table. The only table in common in all my request is the `local_join_table`.

Also, in my original message, the request is written with an `UNION` between twice the same table, which we modified to a single `SELECT` while still seeing a performance drop.

The presented request is a sample of one of the request I execute in parallel of others.

**Comment by den-crane** [comment]
>I see. It may not have been obvious in my original message, but each request works on a different distributed table. 

Why the number of tables matter from competing for cache perspective?

**Comment by eblio** [comment]
Ok, let me re-phrase that to make sure I properly understood what you meant.

When loading data from the multiple distributed table, the result get cached. Which happens for all my request, and eventually triggers cache eviction as the cache gets full. That's why it slows down all of my requests and not only the last ones.

What's bugging me is that I perform similar request (using a combination of `INNER JOIN` and `WHERE IN` instead of one `INNER JOIN`) but, they don't slow down. I understand I'll have to provide more information in order to get help.

**Comment by eblio** [comment]
I'm back with some news. By modifying the way I was generating my requests, I was able to reduce their execution time. From around 40-60 seconds to half a second (when multi-threaded). 

The 3 main improvements are : 
* Don't cast fields in the `JOIN` `ON` condition ;
* Don't perform multiple `UNION` on the same table while you could select all the fields into one `SELECT` ;
* Add a `WHERE` condition, similar to the `JOIN` to filter the data table before performing the `JOIN` ;

Doing so doesn't solve the original problem, the request still run twice slower when in parallel, which is **expected**. These enhancements help to mitigate that though.

Appreciate the help !
