### ISSUE TITLE
Is that necessary to add rebalancing to Clickhouse?

### ISSUE THREAD

**Issue by lingtaolf** [ClickHouse/ClickHouse#52002]
**Use case**  
When adding or removing nodes on Clickhouse cluster, it's a big work for maintainer to rebalance existing data manually. So I think having rebalancing is a good thing for Clickhouse

**Describe the solution you'd like**  

My thoughts are as follows:
1. It should be called by users.
2. It could be table, database and cluster level
  

**Describe alternatives you've considered**  

After executing reblancing, the data between nodes can be average.
  
If you think it' necessary to add this feature, I can try it .

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/6772

>If you think it' necessary to add this feature, I can try it .

Of course feel free.
