### ISSUE TITLE
Access data in Mysql Engine table when Mysql server is dead

### ISSUE THREAD

**Issue by derstiff** [ClickHouse/ClickHouse#52017]
I have a maching table in Mysql and sync this table with CH through the `Mysql Engine`. 
The problem is that Mysql server is not as stable as I wish it would be, so every time Mysql server hangs up or die, any requests in CH throws `mysqlxx::BadQuery: Table 'main.ids_matching' doesn't exist` error.

Is there any way to sync data with Mysql when it's not dead, and still use data from previous successfull sync?

**Comment by UnamedRus** [comment]
You can use 
MySQL Dictionary
MaterializedMySQL engine (but it's kinda unsupported by core team)
Our connector https://github.com/Altinity/clickhouse-sink-connector

**Comment by jzhao20230918** [comment]
When mysql is down, MaterializedMySQL does not work as well. Is it expected?
