### ISSUE TITLE
A huge number of objects and an unexpected increase in the size of the bucket when using Amazon S3 as the default storage

### ISSUE THREAD

**Issue by bessonov87** [ClickHouse/ClickHouse#52015]
We are using Amazon S3 as the default storage on some replicas. To minimize the possibility of data loss, in each cluster we have 2 replicas with a complete copy of all data. If one of them is lost, we can quickly switch to another. Previously, these were 2 identical nodes with EBS storage. Last year we decided to try S3 as a storage (S3 Backed MergeTree) to keep the cost down as S3 is substantially cheaper than EBS. Now we have 6 clusters that have one node with EBS volumes as the default storage and one node with S3 as the default storage. Here is an example of storage configuration from one of replicas:
```
<?xml version="1.0" ?>
<clickhouse>
    <storage_configuration>
        <disks>
            <s3>
                <type>s3</type>
                <endpoint>https://********.s3.amazonaws.com/data/</endpoint>
                <access_key_id>AKIA*********</access_key_id>
                <secret_access_key>******************</secret_access_key>
                <region></region>
                <metadata_path>/var/lib/clickhouse/disks/s3/</metadata_path>
                <cache_enabled>true</cache_enabled>
                <data_cache_enabled>true</data_cache_enabled>
                <cache_path>/var/lib/clickhouse/disks/s3/cache/</cache_path>
                <send_metadata>true</send_metadata>
            </s3>
        </disks>
        <policies>
            <default>
                <volumes>
                    <main>
                        <disk>s3</disk>
                    </main>
                </volumes>
            </default>
        </policies>
    </storage_configuration>
</clickhouse>
```
**Please note:** We didn't find any example of using S3 disk as the default volume. Maybe we did it wrong. We just didn't want to specify a storage_policy while creating tables like `SETTINGS storage_policy = 's3_main'`.

**ClickHouse version is 23.4 on all of our clusters.**

**All tables have the `ReplicatedMergeTree` table engine.**

In general, it works well, but there are several problems:

**1. Constant growth in the number of objects in the bucket in the `/operations` folder.** 
![image](https://github.com/ClickHouse/ClickHouse/assets/8646356/3317a9b9-ac2d-42c5-9056-fe21cfa59218)
Here is an example of the contents of the `/operations` folder:
![image](https://github.com/ClickHouse/ClickHouse/assets/8646356/afb868f1-2b0a-455b-a7fe-a3129fe8e765)
All files are 1 byte in size. I downloaded a few and looked at their contents, there is just the number 0.

**2. Sudden increase in bucket size.** 
This is not a gradual increase, but a periodic sudden increase over several days. For example, in one of the clusters we have about 2.7TB of data, while the bucket size has already grown to 12.5TB in 8 months. The graph clearly shows jumps, when in one day the size grows by hundreds of gigabytes or even several TB in one day. The last time the size grew was about two weeks ago from 8.9TB to 12.5TB.
![image](https://github.com/ClickHouse/ClickHouse/assets/8646356/f680f459-c67f-4649-94e2-7333eaf61b25)

If I run this query on both EBS and S3 nodes I get similar results:
```
select sum(bytes) as total_bytes, formatReadableSize(sum(bytes)) AS total_readable from (select
    table,
    sum(rows) as rows,
    sum(bytes_on_disk) AS bytes,
    formatReadableSize(sum(bytes_on_disk)) AS bytes_readable
from system.parts
group by table
order by bytes desc)
```

EBS backed:
```
┌───total_bytes─┬─total_readable─┐
│ 2975816184006 │ 2.71 TiB       │
└───────────────┴────────────────┘
```

S3 backed:
```
┌───total_bytes─┬─total_readable─┐
│ 2959963247520 │ 2.69 TiB       │
└───────────────┴────────────────┘
```

**3. High RAM consumption during replication to a new replica with S3 as the default storage.**
This is probably the least critical issue, but I would still classify it as unexpected behavior. 
When adding a new replica, when you need to create all the tables on it and replicate all the data, the server constantly consumes all the memory, crashes, and so on until all the data is replicated. Further, everything works stably, new data is replicated without problems.
Here is what it looks like:
![image](https://github.com/ClickHouse/ClickHouse/assets/8646356/d04bf522-19fb-45a1-948d-d00cbc73e338)

**Comment by bessonov87** [comment]
> you need to disable S3 versioning https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html

Bucket versioning is disabled.
![image](https://github.com/ClickHouse/ClickHouse/assets/8646356/d23cd98d-822b-4ce8-9f6d-e7a26490692d)


> > 3. High RAM consumption during replication to a new replica with S3 as the default storage.
> 
> This graph is unreadable with Y-scale and agenda.

This one should be more readable
![image](https://github.com/ClickHouse/ClickHouse/assets/8646356/c44d3962-8e94-488b-b529-46f94a495e32)

This is RAM consumption at the latest replication process. For now, we have only one way of solving the issue. We create a new S3 bucket, then drop all tables on the replica, then stop clickhouse-server, then remove all data from `/var/lib/clickhouse`, change the S3 endpoint to the new one in the config, start clickhouse-server, and create tables. After the initial replication is finished, we have about the same bucket size as on EBS backed instance. On the old bucket, we create a new lifecycle rule to remove all data and then we remove the old bucket itself. Of course, this doesn't solve the issue itself, it just helps us to reduce the cost in AWS for some time. And this requires a lot of manual work.

It started at about 12 pm and finished at 5 pm. While the process was actively going there was at least 10 crashes. It can work up to an hour and then suddenly RAM consumption goes up to 100%. Sometimes this leads to clickhouse-server process restart, sometimes the instance freezes, this can be seen from several empty periods on the chart.

Btw, we tried to reduce `background_fetches_pool_size` even to 1 but this doesn't solve the issue completely and slows down the replication process significantly. The latest process that you can see on the chart was going with `<background_fetches_pool_size>4</background_fetches_pool_size>`.

**Comment by den-crane** [comment]
it could be because of `<send_metadata>true</send_metadata>`  try to disable it
https://github.com/ClickHouse/ClickHouse/issues/40316#issuecomment-1219081788

**Comment by makeavish** [comment]
@den-crane Can you please answer first question?
> 1. Constant growth in the number of objects in the bucket in the /operations folder.

**Comment by den-crane** [comment]
is not reproducible. Outdated
