### ISSUE TITLE
Making insert_deduplication_token work with async_insert

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#52018]
The setting: `insert_deduplication_token` doesn't work when using `async_insert` as specified here: https://github.com/ClickHouse/ClickHouse/blob/e618dd05cc73b7ad38296e7c28f66b6f077343f8/src/Storages/MergeTree/ReplicatedMergeTreeSink.cpp#L469-L471

**Comment by antonio2368** [comment]
`if constexpr (async_insert)` is only true when `async_insert_deduplicate = 1`
Token should be used if `insert_deduplicate` is set to 1 and `replicated_deduplication_window` is not `0`
