### ISSUE TITLE
Can't adjust last granule because it has 8065 rows, but try to subtract 65409 rows.

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#52029]
https://s3.amazonaws.com/clickhouse-test-reports/51696/5f73bec3257d8dd5c0994818e6b8d828cbd8eb8c/fuzzer_astfuzzertsan/report.html

`SELECT sum(length(nested.arr1)), sum(length(nested.arr2)) FROM t_update_empty_nested`
`Changed settings: max_threads = 1, receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, group_by_two_level_threshold = 1, log_queries = true, table_function_remote_max_addresses = 200, max_execution_time = 10., max_memory_usage = 10000000000, send_logs_level = 'fatal', allow_introspection_functions = true, mutations_sync = 2, optimize_monotonous_functions_in_order_by = false, optimize_functions_to_subcolumns = true, allow_deprecated_syntax_for_merge_tree = true, allow_experimental_map_type = true, input_format_defaults_for_omitted_fields = true, output_format_write_statistics = false`

**Comment by guoyuanfangQAQ** [comment]
"We are using ClickHouse version 22.4.5.9, and we've encountered the error 'Can't adjust last granule because it has 8192 rows, but try to subtract 16384 rows: While executing MergeTreeThread. (LOGICAL_ERROR)'. I'd like to know if this issue has been fixed in the latest version 23?" @qoega

**Comment by qoega** [comment]
This issue is open. It means it is not fixed.

**Comment by qoega** [comment]
But 22.4 is really old and your issue can be not related with this failure and may be fixed with update to at least 23.3.8

**Comment by Algunenano** [comment]
Most likely related to `optimize_functions_to_subcolumns`. We have other issues with reproducers (https://github.com/ClickHouse/ClickHouse/issues/57326) so closing this
