### ISSUE TITLE
Can't run RENAME and EXCHANGE queries

### ISSUE THREAD

**Issue by derstiff** [ClickHouse/ClickHouse#52034]
Can't run `RENAME` and `EXCHANGE` queries:

```
Code: 48. DB::Exception: Received from xxxxxxxx.xxx :9000. DB::Exception: RENAME EXCHANGE is not supported. (NOT_IMPLEMENTED)
```

I guess it might be some OS/CH version issue, but I can't find anything about this limitation.

Clickhouse:

```
ClickHouse server version 22.5.1.2079 (official build).
ClickHouse client version 22.5.1.2079 (official build).
```

Server:

```
Operating System: CentOS Linux 7 (Core)
     CPE OS Name: cpe:/o:centos:centos:7
          Kernel: Linux 3.10.0-1160.42.2.el7.x86_64
    Architecture: x86-64
```

**Comment by den-crane** [comment]
filesystem? 
database engine? `show create database mydb` (only Atomic databases support it)

**Comment by Algunenano** [comment]
Even if you are using atomic databases or a newer CH version, the underlying OS call requires Linux [3.15](https://github.com/ClickHouse/ClickHouse/blob/a794177dc3c018530aa5feb86a2070e55e86a41b/src/Common/atomicRename.cpp#L58-L63) so it won't work anyway.
