### ISSUE TITLE
Can kafka engine support isolation level read_uncommitted?

### ISSUE THREAD

**Issue by jianzzz** [ClickHouse/ClickHouse#52033]
I am using Clickhouse for my work. 
However, I find that the kafka engine does not seem to support setting **isolation.level=read_uncommitted**.

https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka

**Comment by genzgd** [comment]
I believe this is just another librdkafka setting that you can include in the general Kafka configuration.

https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka#configuration
https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md

So in your Kafka block, did you try:

```xml
<kafka>
   <isolation_level>read_uncommitted</isolation_level>
  ...
</kafka>
```

**Comment by jianzzz** [comment]
> I believe this is just another librdkafka setting that you can include in the general Kafka configuration.
> 
> https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka#configuration https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md
> 
> So in your Kafka block, did you try:
> 
> ```
> <kafka>
>    <isolation_level>read_uncommitted</isolation_level>
>   ...
> </kafka>
> ```

It works. Thank you for your reply.
