### ISSUE TITLE
Optimize predicate expression with ASOF JOINs leads to incorrect results

### ISSUE THREAD

**Issue by polikutinevgeny** [ClickHouse/ClickHouse#52048]
**Describe what's wrong**

`enable_optimize_predicate_expression=1` is on by default and breaks ASOF JOINs when mixed with subqueries. https://github.com/ClickHouse/ClickHouse/issues/37813 seems to be the same issue that was partially fixed (I only had to change the repro a bit to resemble what I have observed in production)

A link to reproducer: https://fiddle.clickhouse.com/09db0df0-c887-4f32-b6ab-7c427a1da72f

```
enable_optimize_predicate_expression=0
1	20	1	15	b
enable_optimize_predicate_expression=1
1	20	1	15	b
1	30	1	15	b
```

Reproduces in 23.6.2.18 and 23.3.7.5.

**Expected behavior**

The results should not change when enabling/disabling enable_optimize_predicate_expression.

**Comment by SaltTan** [comment]
Fixed in 23.7 https://fiddle.clickhouse.com/2488ae6c-894a-4ec6-8d22-3af87234e2e9

**Comment by polikutinevgeny** [comment]
Yep, that's great

**Comment by den-crane** [comment]
probably fixed by https://github.com/ClickHouse/ClickHouse/pull/51633
