### ISSUE TITLE
Count over Nullable LowCardinality column

### ISSUE THREAD

**Issue by mkabilov** [ClickHouse/ClickHouse#52055]
> You have to provide the following information whenever possible.

**Describe what's wrong**

`count` aggregate function provides incosistent results over the `LowCardinality(Nullable(...))` column

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

yes

**Enable crash reporting**

**How to reproduce**

* Which ClickHouse server version to use
`23.6.1.1362`

* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
```sql
CREATE TABLE default.test
(
    `val` LowCardinality(Nullable(String))
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192;
```
* Sample data for all these tables, use [clickhouse-obfuscator]

```sql
insert into test select number == 3 ? 'some value' : null from numbers(5);
--┌─val────────┐
--│ ᴺᵁᴸᴸ       │
--│ ᴺᵁᴸᴸ       │
--│ ᴺᵁᴸᴸ       │
--│ some value │
--│ ᴺᵁᴸᴸ       │
--└────────────┘
```

* Queries to run that lead to unexpected result
```sql
SELECT count(val)
FROM test

Query id: d2061bd9-b54c-468b-9375-a8b3a591cb64

┌─count(val)─┐
│          5 │
└────────────┘


SELECT
    count(val),
    sum(val IS NOT NULL)
FROM test

Query id: be33b9a7-1afd-41ae-be4b-955babaf39f6

┌─count(val)─┬─sum(isNotNull(val))─┐
│          1 │                   1 │
└────────────┴─────────────────────┘
```

**Expected behavior**

count must return the same value for both of the select queries

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
cc @liuneng1994 probably introduced by
* https://github.com/ClickHouse/ClickHouse/pull/45772

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/d1ae2722-f6ad-441f-8c02-69e12e92b651

**Comment by den-crane** [comment]
ah, No, it's not related to https://github.com/ClickHouse/ClickHouse/pull/45772
It's related to projections https://fiddle.clickhouse.com/de909904-a50a-454a-88c2-fc30433a2d71 
* https://github.com/ClickHouse/ClickHouse/pull/46537
