### ISSUE TITLE
Missing some records after synchronization psql to CH using the engine MaterializedPostgresql

### ISSUE THREAD

**Issue by sc0der** [ClickHouse/ClickHouse#52078]
This problem was discovered:
Created a replication of postgresql to ClickHouse using MaterializedPostgresql engine, after the end of synchronization I noticed that about 20% of records (in random order) are missing (total records are about 80billion). What could be the problem

**Comment by kssenii** [comment]
@sc0der  Please try recent clickhouse server version. Check logs for error messages. If there are none, please make a reproducing example how to reproduce this issue.

**Comment by kssenii** [comment]
No answer provided as to how to reproduce the issue. As there have been no similar problem reported, I will close the issue.
