### ISSUE TITLE
Can we limit bandwidth for s3 disk?

### ISSUE THREAD

**Issue by coulsonm** [ClickHouse/ClickHouse#52079]
Our cluster hava 20 shards and we want to use s3 disks to store cold data. We need to avoid use all bandwidth of the switch. How to limit the bandwidth for s3 disk of each clickhouse node?

**Comment by den-crane** [comment]
v22.7.1.2484-stable.md:* Added options to limit IO operations with remote storage: `max_remote_read_network_bandwidth_for_server` and `max_remote_write_network_bandwidth_for_server`. [#39095](https://github.com/ClickHouse/ClickHouse/pull/39095) ([Sergei Trifonov](https://github.com/serxa)).

v23.4.1.1943-stable.md:* Per-query/per-server throttling for remote IO/local IO/BACKUPs (server settings: `max_remote_read_network_bandwidth_for_server`, `max_remote_write_network_bandwidth_for_server`, `max_local_read_bandwidth_for_server`, `max_local_write_bandwidth_for_server`, `max_backup_bandwidth_for_server`, settings: `max_remote_read_network_bandwidth`, `max_remote_write_network_bandwidth`, `max_local_read_bandwidth`, `max_local_write_bandwidth`, `max_backup_bandwidth`). [#48242](https://github.com/ClickHouse/ClickHouse/pull/48242) ([Azat Khuzhin](https://github.com/azat)).

**Comment by coulsonm** [comment]
thx ^_^

**Comment by coulsonm** [comment]
@den-crane

**Comment by coulsonm** [comment]
Clickhouse version:23.1

**Comment by coulsonm** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/c00a5ca9-2dbc-4ba0-9278-ec96fc001bd6)

**Comment by coulsonm** [comment]
I used TTL to move data to s3 from disks
table schema example:
...
TTL toStartOfDay(parseDateTimeBestEffort(toString(__store_time__))) + toIntervalMinute(607) TO VOLUME 's3_cold_volume'

**Comment by serxa** [comment]
Have you restarted your ClickHouse server?

**Comment by coulsonm** [comment]
Yes,I set this configurationin in default profile. 
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/44cfb670-cfc7-47a0-83ed-dd5b30119c9e)

I used another account to login then searched system.settings  
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/e0b00aaf-a6e1-4ddb-b701-1cd3080697ab)

**Comment by coulsonm** [comment]
Here is the speed for one table moved to S3 disks from local disks  on this configurationin 
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/dadab198-ee9d-4b1c-9fac-264a9aeb4436)
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/e04b3338-12c2-47cf-89db-3d22f8726ded)

**Comment by coulsonm** [comment]
There are 2 nodes in one shard.I am trying s3 zero copy.
table schema example:
...
TTL toStartOfDay(parseDateTimeBestEffort(toString(store_time))) + toIntervalMinute(607) TO VOLUME 's3_cold_volume'

**Comment by serxa** [comment]
If the initial volume is also S3 then throttling is not applied intentionally, because zero copy should not create data traffic from the host, only "control" traffic.

**Comment by serxa** [comment]
But if you are copying from local disks it is interesting. In the recent version, there was a couple of bug fixes https://github.com/ClickHouse/ClickHouse/pull/49797 about throttlers, but I believe they are irrelevant. It might be yet another bug.

**Comment by serxa** [comment]
Maybe for some reason throttlers do not recognize TTL moves to S3 as "remote" traffic. To quickly check if this is a case you could try also set corresponding `max_local_write_bandwidth_for_server`.

Please, also note that `max_remote_write_network_bandwidth_for_server` is now deprecated inside the user profile in favor of server config setting, just inside <clickhouse>.

**Comment by coulsonm** [comment]
My clickhouse version is 23.3.1.  This version not contain this config **max_local_write_bandwidth_for_server** . 
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/33f816d9-3f9d-43aa-981e-172bb948295d)

I tried to set **max_remote_write_network_bandwidth_for_server**  to config.xml ，but not right.
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/9d456a25-08df-41d3-9329-c958a4467a2f)

**Comment by coulsonm** [comment]
I tried to set 
```
<max_remote_read_network_bandwidth_for_server>10485760</max_remote_read_network_bandwidth_for_server> ,<skip_check_for_incorrect_settings>1</skip_check_for_incorrect_settings>
<max_remote_write_network_bandwidth_for_server>10485760</max_remote_write_network_bandwidth_for_server>
```
 in config.xml.This configuration not works.

**Comment by serxa** [comment]
I could see on the chart you shared, that the yellow line is limited by about 80Mb/s, until something happens. Not that `max_remote_read_network_bandwidth_for_server` unfortunately does not limit all the traffic the CH server could generate. For example, if you run a distributed query on top, its traffic would not be classified as "remote".

**Comment by coulsonm** [comment]
Yes. Please check whether this performance is caused by a bug. Should i try the new version after 23.3?

**Comment by serxa** [comment]
I checked and everything seems fine, besides the intentional behavior that I mentioned (not all traffic is limited by this setting).

**Comment by coulsonm** [comment]
Sorry to bother you again, 

> I could see on the chart you shared, that the yellow line is limited by about 80Mb/s, until something happens. Not that `max_remote_{read,write}_network_bandwidth_for_server` unfortunately does not limit all the traffic the CH server could generate. For example, if you run a distributed query on top, its traffic would not be classified as "remote".

**Comment by coulsonm** [comment]
@serxa

**Comment by coulsonm** [comment]
clickhouse version:22.3.1

I tried Mergetree with S3 disks. Data stored in local disks and then moved to s3 by ttl. 
I limited 
`                        <max_remote_read_network_bandwidth_for_server>10485760</max_remote_read_network_bandwidth_for_server>
                     <max_remote_write_network_bandwidth_for_server>10485760</max_remote_write_network_bandwidth_for_server>
                       <max_replicated_fetches_network_bandwidth_for_server>10485760</max_replicated_fetches_network_bandwidth_for_server>
                     <max_replicated_sends_network_bandwidth_for_server>10485760</max_replicated_sends_network_bandwidth_for_server>
<max_network_bandwidth>10485760</max_network_bandwidth>
<max_network_bandwidth_for_all_users>10485760</max_network_bandwidth_for_all_users>`

No people use this cluster except clickhouse ttl moving parts.But the bandwidth more than 10Mb/s
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/ccc205d2-4cb5-45c7-b860-74ea30830ee7)

**Comment by coulsonm** [comment]
@serxa
