### ISSUE TITLE
How can I store some tables in another disk?

### ISSUE THREAD

**Issue by lucasguo** [ClickHouse/ClickHouse#52076]
OS: Ubuntu 22.04
Clickhouse: 22.2.3.1

I have set data path to /data/clickhouse, and all table data stored there. 

Now as the data size increased, the disk is almost full.

So I get a new disk and try to move some tables to the new disk. Here is the step what I have done:

1. create a new database by running `create database extra;`
2. mount the new disk to `/data/clickhouse/data/extra`
3. delete some tables in database `default` and create new ones in database `extra`, and the other tables are still keep in database `default`
4. write data to the new tables in database `extra`

Then I observe the folder `/data/clickhouse/data/extra`, new folders with the table name is created by clickhouse as expected. However the folder is just a symbol link that link to the somewhere like `/data/clickhouse/store/**/*****/`.

Since I just mount the new disk to `/data/clickhouse/data/extra`, so the data in new database `extra` still stored in my old disk, this is not what I want.

So what I want to know is that, is there a way to store some table completely in another disk? Thank you in advance.

**Comment by den-crane** [comment]
Your way is unsupported.


you should define new storage_configuration and assign the new storage_policy to the table.

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-multiple-volumes_configure

https://altinity.com/blog/2019/11/27/amplifying-clickhouse-capacity-with-multi-volume-storage-part-1
