### ISSUE TITLE
Rename system.trace_log on build_id changes

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#52086]
**Describe the issue**

After binary had been changed, traces will likely be incompatible

So it make sense to rename system.trace_log in case of change

**Comment by Algunenano** [comment]
This was implemented in https://github.com/ClickHouse/ClickHouse/pull/63656, but now that means that every minor change will trigger a change in system.trace_log and we might end up with dozens or hundreds of system.trace_log tables that are all identical.

Do we really want this behaviour?

**Comment by Algunenano** [comment]
Makes sense. 

Most of the times system tables are used with TTL, so old tables will become empty after a while. It'd make sense to have a setting to drop those tables. I'll create a different ticket.
