### ISSUE TITLE
Arguments of 'lcm' have incorrect data types: 'negate(sign(c0))' of type 'Int8', 'negate(sign(c0))' of type 'Int8'. (LOGICAL_ERROR)

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#52087]
It should not be LOGICAL_ERROR
```
SELECT (abs ((log ((radians (0)))))) FROM t0 GROUP BY lcm((- ((sign (t0.c0)))),(- (t0.c0)));
```

https://s3.amazonaws.com/clickhouse-test-reports/51692/42a7ec77895c3b3def77192ab7ecb8b3e7692beb/sqlancer__release_.html

**Comment by Algunenano** [comment]
Duplicated -> https://github.com/ClickHouse/ClickHouse/issues/52075
