### ISSUE TITLE
Add more query tree passes to new Analyzer.

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/ClickHouse#52081]
New analyzer is really an exciting feature. Now it is still experimantal, I wanna help to do something. Start by adding some query tree passes to it.

**Describe the situation**
What exactly works slower than expected?

- [x] rewrite uniq to count https://github.com/ClickHouse/ClickHouse/pull/52004
- [x] optimize move functions out of any https://github.com/ClickHouse/ClickHouse/pull/52082
- [x] optimize aggregators of group by keys https://github.com/ClickHouse/ClickHouse/pull/52230
- [x] optimize monotonous functions in order by https://github.com/ClickHouse/ClickHouse/pull/52396

Already done on query plan level
- [x] optimize duplicate order by https://github.com/ClickHouse/ClickHouse/pull/52294
- [x] optimize duplicate distinct https://github.com/ClickHouse/ClickHouse/pull/52304

**Comment by devcrafter** [comment]
Already done on query plan level
> - [ ] optimize duplicate order by https://github.com/ClickHouse/ClickHouse/pull/52294

see https://github.com/ClickHouse/ClickHouse/pull/45567, https://github.com/ClickHouse/ClickHouse/pull/45420

> - [ ] optimize duplicate distinct https://github.com/ClickHouse/ClickHouse/pull/52304

see https://github.com/ClickHouse/ClickHouse/pull/44176

**Comment by JackyWoo** [comment]
@devcrafter got it, thanks.
