### ISSUE TITLE
In local storage, Is it possible to save the *.bin files into hdd when other files into ssd?

### ISSUE THREAD

**Issue by Mum1996** [ClickHouse/ClickHouse#52093]
[S3 file system do this things](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3)

S3 Table Engine have done this things.

But when I have a mixed SSD and HDD **LOCAL**  storage system, Can I sapreated the bin data into HDD to save costs?

Just like S3 storage, the real bin data stored into S3 systems and the local **bin** file only record a hash value whitch can save the local storage (SSD)

**Comment by UnamedRus** [comment]
What the idea of that separation?

Really slow HDD storage for copy/rename operations?

You can check local object storage, but it wasn't meant to be used as production storage layer

https://github.com/ClickHouse/ClickHouse/pull/48791

**Comment by alexey-milovidov** [comment]
No, this option does not exist.

> You can check local object storage

No, local object storage is not a feature for users; it is just internal implementation detail.

**Comment by MattMH** [comment]
@alexey-milovidov  Is there a way to map bin to another disk path ? For cost considerations, we want to store bin files separately on hdd disk ,and use SSD to increase the speed reading metadata such like mrk* etc.

**Comment by UnamedRus** [comment]
You can use cache disk for that purpose.

**Comment by MattMH** [comment]
@UnamedRus  Thank you very much for your answer!  I am facing a completely different application scenario:  Thousands of table in wide mode , so there are 100,000+ small files like mrk* mixed with .bin files in 200T*  disk (16T*N).  So when the capacity is occupied by 75%, the read speed is reduced to random IO. 
I think that storing small files on ssd and mapping large files on hdd can take advantage of the fast random IO speed of ssd.  
what u said '**cache disk**' is the the ability of clickhouse or the function of a third-party software to mixed ssd and hdd？

**Comment by UnamedRus** [comment]
>  Thousands of table in wide mode

Too much for ClickHouse.
may be it make sense to bump index_granularity, increase mark cache.

> the ability of clickhouse 

Yes
https://github.com/ClickHouse/ClickHouse/pull/36171
