### ISSUE TITLE
How to modify values at insertion ?

### ISSUE THREAD

**Issue by George3d6** [ClickHouse/ClickHouse#521]
Is there a way to do this ? At first glance it should be possible with DEFAULT but I can't figure the syntax. Basically what I want to do is have a column that looks like this:

`my_string string DEFAULT operation(my_original_string)`

Without permanently storing "my_original_string" in the table. Is this possible ?

**Comment by alexey-milovidov** [comment]
> Without permanently storing "my_original_string" in the table. Is this possible?

Currently it is not possible.

What syntax do you prefer for implementation?
We are considering possibility to implement something like this:
```
INSERT INTO table (my_string) SELECT operation(my_original_string) FROM input(my_original_string String)
```

**Comment by George3d6** [comment]
Well, the fact that you are considering the implementation is neat, its nice to see the project is very much evolving since I might use it as my storage for an rt~ish analytics infrastructure :)

The way I see it, that kind of INSERT statement would fix this issue. What I was thinking of was more of a column that does it automatically, so you have something like DEFAULT/MATERIALIZE/ALIAS, something like:

my_string string KEYWORD operation(initial) ...much like I wrote above

I guess the option to have a temporary column (or a column where data has ttl) would also fix the issue just as well.

But your solution sounds like it could be more general and in the end you are the database designer here :P 

Also, is there anything you guys might need help from a quite inexperienced C++ developer with ? (e.g. writing functional tests for various modules and edge cases) ... I'd very much like to contribute to this project. I will try to release soon (tm) some benchmarks of clickhous vs mariadb cs and maybe even write a "for dummies" setup guide on DO.

**Comment by alexey-milovidov** [comment]
The `input` table function was implemented.
https://clickhouse.github.io/clickhouse-presentations/meetup30/new_features/#21
