### ISSUE TITLE
A compatibility alias `CURRENT_TIMESTAMP`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#52101]
**Use case**

`SELECT CURRENT_TIMESTAMP()`

**Describe the solution you'd like**

An alias for function `now`, case-insensitive as well.
Add it here: https://clickhouse.com/codebrowser/ClickHouse/src/Functions/now.cpp.html#140

Add `CURRENT_DATE` and `CURDATE` as aliases for `today`.

**Comment by FFFFFFFHHHHHHH** [comment]
I’d like to have a try:)
