### ISSUE TITLE
why set type index should invalid，but the explain shows Selected Granules is less than Initial Granules

### ISSUE THREAD

**Issue by kaetrua** [ClickHouse/ClickHouse#52107]
i have a big data table, there is a column with non-repetitive datas. there is a set type index on this column. the max_rows was set 100.( index_granularity = 8192, and GRANULARITY of the index is 16. so i think the row number is 131072, is bigger than max_rows which be set as 100,  so as the official document said, this index should be invalid )
but where i execute explain indexes = 1, it show, after using this index ,Selected Granules is less than Initial Granules, it shows the index is valid, so im confused about this.

the explain info of this index :
                                          "Type": "Skip",
                                          "Name": "a",
                                          "Description": "set GRANULARITY 16",
                                          "Initial Parts": 8,
                                          "Selected Parts": 8,
                                          "Initial Granules": 41323,
                                          "Selected Granules": 3201

**Comment by cangyin** [comment]
please provide:

```sql
-- output of:
SHOW CREATE the_table;

-- the query SQL

-- the full output of:
EXPLAIN indexes=1 SELECT ... 

-- output of:
SELECT count(),avg(rows) FROM system.parts WHERE active AND table='the_table';
```

**Comment by kaetrua** [comment]
-- output of: SHOW CREATE the_table;
--local table：
CREATE TABLE XX.XXX_20230715_local
(
    `item_sku_id` UInt64,
    `item_id` UInt64,
-- fold one hundred selling data column
    `dt` Date,
    `dt_date` DateTime,
    INDEX a item_sku_id TYPE SET(100) GRANULARITY 16,
    INDEX b item_id TYPE SET(100) GRANULARITY 16
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/XX/{shard}/XXX_20230715_local', '{replica}')
PARTITION BY dt
ORDER BY (sku_data_flag, item_third_cate_cd, oper_dept_id_3, erp, sku_good_comment_ratio, bm_score_rank_rate, sku_d180_deal_sale_qtty, brand_code, sku_long_age_stock_qtty, sku_long_age_stock_amt, sku_over_wh_cost, sku_pv_d30, sku_d30_sale_qtty, sku_d30_deal_amt, item_sku_id)
TTL dt_date + toIntervalDay(10)
SETTINGS enable_mixed_granularity_parts = 1, index_granularity = 8192

-- Distributed table：
show create table XX.XXX_20230715
CREATE TABLE ecodata.app_eco_nirvana_sku_unify_label_out_20230715
(
    `item_sku_id` UInt64,
    `item_id` UInt64,
-- fold one hundred selling data column
    `dt` Date,
    `dt_date` DateTime
)
ENGINE = Distributed('default', 'XX', 'XXX_20230715_local', abs(javaHash(toString(item_sku_id))))

-- the query SQL

 explain indexes = 1, json = 1 select  item_sku_id from ecodata.app_eco_nirvana_sku_unify_label_out_20230715_local where  item_sku_id in ('10076385769241')

-- the full output of EXPLAIN:
[
  {
    "Plan": {
      "Node Type": "Expression",
      "Description": "(Projection + Before ORDER BY)",
      "Plans": [
        {
          "Node Type": "Filter",
          "Description": "WHERE",
          "Plans": [
            {
              "Node Type": "SettingQuotaAndLimits",
              "Description": "Set limits and quota after reading from storage",
              "Plans": [
                {
                  "Node Type": "ReadFromMergeTree",
                  "Indexes": [
                    {
                      "Type": "MinMax",
                      "Condition": "true",
                      "Initial Parts": 13,
                      "Selected Parts": 13,
                      "Initial Granules": 42677,
                      "Selected Granules": 42677
                    },
                    {
                      "Type": "Partition",
                      "Condition": "true",
                      "Initial Parts": 13,
                      "Selected Parts": 13,
                      "Initial Granules": 42677,
                      "Selected Granules": 42677
                    },
                    {
                      "Type": "PrimaryKey",
                      "Keys": ["item_sku_id"],
                      "Condition": "(item_sku_id in 1-element set)",
                      "Initial Parts": 13,
                      "Selected Parts": 13,
                      "Initial Granules": 42677,
                      "Selected Granules": 41870
                    },
                    {
                      "Type": "Skip",
                      "Name": "a",
                      "Description": "set GRANULARITY 16",
                      "Initial Parts": 13,
                      "Selected Parts": 13,
                      "Initial Granules": 41870,
                      "Selected Granules": 3169
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  }
]

-- output of:
SELECT rows FROM system.parts WHERE active AND table='the_table' ORDER BY rows ASC LIMIT 5;
4122144
18477
154519
147846
141372
(because of Distributed table, the rows number may be a little different with EXPLAIN)


--and if i use not in, the EXPLAIN also show less than 10% Granules be skip
 explain indexes = 1, json = 1 select  item_sku_id from ecodata.app_eco_nirvana_sku_unify_label_out_20230715_local where  item_sku_id not in ('10076385769241')
--
[
  {
    "Plan": {
      "Node Type": "Expression",
      "Description": "(Projection + Before ORDER BY)",
      "Plans": [
        {
          "Node Type": "Filter",
          "Description": "WHERE",
          "Plans": [
            {
              "Node Type": "SettingQuotaAndLimits",
              "Description": "Set limits and quota after reading from storage",
              "Plans": [
                {
                  "Node Type": "ReadFromMergeTree",
                  "Indexes": [
                    {
                      "Type": "MinMax",
                      "Condition": "true",
                      "Initial Parts": 1,
                      "Selected Parts": 1,
                      "Initial Granules": 42671,
                      "Selected Granules": 42671
                    },
                    {
                      "Type": "Partition",
                      "Condition": "true",
                      "Initial Parts": 1,
                      "Selected Parts": 1,
                      "Initial Granules": 42671,
                      "Selected Granules": 42671
                    },
                    {
                      "Type": "PrimaryKey",
                      "Keys": ["item_sku_id"],
                      "Condition": "(item_sku_id notIn 1-element set)",
                      "Initial Parts": 1,
                      "Selected Parts": 1,
                      "Initial Granules": 42671,
                      "Selected Granules": 42671
                    },
                    {
                      "Type": "Skip",
                      "Name": "a",
                      "Description": "set GRANULARITY 16",
                      "Initial Parts": 1,
                      "Selected Parts": 1,
                      "Initial Granules": 42671,
                      "Selected Granules": 2667
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  }
]

**Comment by kaetrua** [comment]
BTW, the value of ‘item_sku_id’  is not repeated and is not null

**Comment by cangyin** [comment]
> SELECT rows FROM system.parts WHERE active AND table='the_table' ORDER BY rows ASC LIMIT 5;
> 4122144
> 18477
> 154519
> 147846
> 141372

This looks like faked data.

**Comment by kaetrua** [comment]
These are the real data running on the system. In other words, even if the data is fake, it shows a phenomenon that is not consistent with the official documents.:)

**Comment by wzb5212** [comment]
> These are the real data running on the system. In other words, even if the data is fake, it shows a phenomenon that is not consistent with the official documents.:)

It's a bug,  I also encountered a similar problem.

**Comment by wzb5212** [comment]
It's a bug.
