### ISSUE TITLE
XFS and a very old Linux kernel: clickhouse-server gets stuck and requires reboot

### ISSUE THREAD

**Issue by davidgcameron** [ClickHouse/ClickHouse#52118]
We run a ClickHouse cluster over 6 hosts with 2 shards and 3 replicas on version 23.6.1.1524. We are experiencing issues where clickhouse-server on one host becomes unresponsive and gets into a state where only a reboot of the host can get it working again.

It has happened 7 times in the last month on 3 particular hosts (from different shards and replicas) but never on the other hosts. The hardware of all the hosts is basically identical and they not under heavy load. A keeper cluster runs on 3 separate hosts.

The cause of the problem is not clear, it doesn't seem to be correlated with load or data volume. What happens is that suddenly queries hang, and after a few minutes the simultaneous queries limit is reached. Restarting the service doesn't work and leaves a zombie process behind. At this point the host has to be rebooted.

A dump of system.stack_traces can be found here (taken before the query limit was reached):

https://gist.github.com/davidgcameron/b77bd44ce6e2f6838d3d28476e19a9a8

I'd be happy to hear any ideas of what to do next time it happens or suggestions for further debugging.

**Comment by cangyin** [comment]
We are also experiencing some similar weird problem:

ClickHouse server stucks during starting, just after this log:
`<Warning> Access(local directory): Recovering lists in directory /var/lib/clickhouse/access`

for almost 40 minutes, there is no more logs.


_version: 23.2.4.12-stable_

**Comment by alexey-milovidov** [comment]
If the process remains in `D` state (uninterruptible sleep), it can be related to disks.

**Comment by alexey-milovidov** [comment]
What are the servers, and what disk subsystem do they use?

**Comment by pm5** [comment]
In our case (same project as @davidgcameron) the servers are Linux 4.18, with NVMe disks using XFS.  ClickHouse version is 23.6.1.1524.

**Comment by alexey-milovidov** [comment]
Interesting... the Kernel version is pretty old, and XFS is rarely used with ClickHouse compared to ext4.

**Comment by davidgcameron** [comment]
For the record, we eventually found the source of this problem. The affected hosts had a very high XFS allocation group count due reasons that we don't fully understand. It was set to 26000 compared to 26 for the unaffected hosts. We reformatted the file system on each host to reset it back to a small value and since then we haven't observed any more crashes.
