### ISSUE TITLE
(I have a question) when insert from LowCardinality(String) field into LowCardinality(String) field, inserted data error

### ISSUE THREAD

**Issue by foolfish3** [ClickHouse/ClickHouse#52132]
when insert select from LowCardinality(String) field into LowCardinality(String) field
after insert enough high cardinality data (several billions?) ,will see some mistake value, for example 'A' insert ,but got another exitsting String 'B' inserted. u can use sum(cityHash64(*)) check whether exist error data.

version: 23.3.7.5

**Comment by foolfish3** [comment]
when insert from String to LowCardinality(String), no bug

**Comment by alexey-milovidov** [comment]
How to reproduce?
Do you use the official version of ClickHouse or something else?

**Comment by foolfish3** [comment]
1. i user official docker image, a lot amount error data happens on 23.3.2.37, then i upgrade to 23.3.7.5, bug still exists
2. bug is not very stable reproduce(same data i insert many times, will make diffierent error data,not all same)
3. bug also exists at  insert select from LowCardinality(String) field into LowCardinality(String) field  via remote function in two different server
4. str to LowCardinality(String) is no problem
5. insert enough data will happen( about several billions rows with nearly 100M different values), nearly all table in our company is inconsistent, cost very much to repair data

**Comment by alexey-milovidov** [comment]
Does it reproduce on the latest release 23.6?

**Comment by foolfish3** [comment]
has bug on insert from 23.3.7.5 into 23.7 via remote function

**Comment by alexey-milovidov** [comment]
Send the table definitions, the dataset, and the way to reproduce it to support@clickhouse.com
