### ISSUE TITLE
Support for Unique key in table

### ISSUE THREAD

**Issue by itziklavon** [ClickHouse/ClickHouse#52133]
Hi,
Is there any plan for support "actual" unique table key, so that insert operation won't actually happen, or will replace the row in table.
Pretty much the same as we have in MySQL, 'INSERT IGNORE' / 'REPLACE INTO'.
currently there are some solutions like ReplacingMergeTree/VersionedCollapsingMergeTree....
But in all of this cases insert will still happen.

On our case, issue comes when we want to use MV on some table(inserted row might be inserted twice, and MV will calculate it twice), OR when we want to "upsert" into a table (we need to use FINAL / LIMIT 1 BY on the select query, which slows down the operation).

IMHO, i think this kind of feature will benefit a lot of people.

Currently in order to avoid duplicate values in table, we use 'temp' tables, and filter for values which exists in main table, only after verified values does not exists we merge it to main table, it is pretty heavy process, thought something can be done on DB level (for example like the support for lightweight deletes).

**Comment by nickitat** [comment]
#14230
