### ISSUE TITLE
`urlCluster` function not found in docker image

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#52134]
`clickhouse/clickhouse-server:23.3.8`

```
15935f0c6975 :) select * from system.table_functions where name like '%url%'

SELECT *
FROM system.table_functions
WHERE name LIKE '%url%'

Query id: 4641d8e2-05b4-4205-ba7e-3e2ab7ef75b9

┌─name─┬─description─┬─allow_readonly─┐
│ url  │             │              0 │
└──────┴─────────────┴────────────────┘

1 row in set. Elapsed: 0.002 sec.
```

`s3Cluster` exists so it seems strange that `urlCluster` would be omitted. Maybe that's as simple as a compile flag change.

**Comment by alexey-milovidov** [comment]
23.3 is from March, while the s3Cluster was added in 23.5.

**Comment by alexey-milovidov** [comment]
ClickHouse has a universal, portable, no-dependencies, single-binary installation:
```
curl https://clickhouse.com/ | sh
```

It works on Linux, FreeBSD, Mac, and WSL, including x86_64, AArch64, PowerPC, and RISC-V.
It lets you avoid using Docker.

**Comment by danthegoodman1** [comment]
Oh gosh yeah, I didn't even realize, that was the latest docker image... Need docker containers because I'm using on fly.io, gets run as a VM anyway though but from a docker image.
