### ISSUE TITLE
`Application: Ready for connections` but connecting to server will stuck

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#52150]
**Describe what's wrong**

I see logs below (with irrelavant DNS errors `grep -v` out)
```bash
2023.07.16 19:12:02.311957 [ 1 ] {} <Information> CertificateReloader: One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.
2023.07.16 19:12:03.225691 [ 1 ] {} <Information> Application: Listening for http://0.0.0.0:8123
2023.07.16 19:12:03.225792 [ 1 ] {} <Information> Application: Listening for native protocol (tcp): 0.0.0.0:9000
2023.07.16 19:12:03.225875 [ 1 ] {} <Information> Application: Listening for MySQL compatibility protocol: 0.0.0.0:9004
2023.07.16 19:12:03.225947 [ 1 ] {} <Information> Application: Listening for PostgreSQL compatibility protocol: 0.0.0.0:9005
2023.07.16 19:12:03.226018 [ 1 ] {} <Information> Application: Listening for Prometheus: http://0.0.0.0:8888
2023.07.16 19:12:03.226102 [ 1 ] {} <Information> Application: Listening for replica communication (interserver): http://0.0.0.0:9009
2023.07.16 19:12:03.226118 [ 1 ] {} <Information> Application: Ready for connections.
```
but no more logs appear. Any attempt to connect to the server will get stuck. like:
```
clickhouse@chi-datalake-cluster-4-1-0:/$ clickhouse-client 
ClickHouse client version 23.2.4.16.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 23.2.4 revision 54461.


<-- stuck here
```

`top` command shows clickhouse-server stays in `S` state. Output:
```
top - 19:28:18 up 43 days, 21:59,  0 users,  load average: 3.14, 4.55, 6.14
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.2 us,  1.2 sy,  0.0 ni, 94.7 id,  1.8 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem : 386767.9 total, 326491.4 free,  29513.7 used,  30762.8 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 353720.4 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                  
    1 clickho+  20   0   20.1g   5.5g 138192 S  15.3   1.4  16:50.55 clickhouse-serv                                                                                                                                                                                          
```

clickhouse-server will stay as unresponsive for almost 40 minutes.

**Does it reproduce on recent release?**
No. And neither won't it reproduce in our another cluster.

**Comment by alexey-milovidov** [comment]
This might be a misconfiguration of your machine.
It might need an expert level to figure out what is wrong.

Check the:

```
sudo strace -f -e trace=network -p ...
```

on both the client and server side,
also, check tcpdump.

**Comment by alexey-milovidov** [comment]
Do you use the official build of ClickHouse or something else?
What is `chi-datalake-cluster-4-1-0`?

Please note that anything other than the official build is not supported.

**Comment by alexey-milovidov** [comment]
Version 23.2 is obsolete and not supported anymore.
Upgrade to the latest version as follows:

```
curl https://clickhouse.com/ | sh
```

**Comment by alexey-milovidov** [comment]
I have noticed, that you've configured the server to listen for the IPv4 address space.
While by default, it is listening to both IPv4 and IPv6.

**Comment by alexey-milovidov** [comment]
The process number `[ 1 ]` in the logs indicates that you are running the server in Docker, Kubernetes, or similar.
It can be problematic because it provides a way to mess up your network configuration.
Removing Docker or Kubernetes might solve your problems.

**Comment by cangyin** [comment]
> Do you use the official build of ClickHouse or something else? What is `chi-datalake-cluster-4-1-0`?
> 
> Please note that anything other than the official build is not supported.

The cluster is deployed using clickhouse-operator. A name like `chi-datalake-cluster-4-1-0`, indicates it is the shard 4, replica 1 in cluster named 'datalake'.

**Comment by alexey-milovidov** [comment]
clickhouse-operator is an unofficial project; it can be a source of trouble.

**Comment by cangyin** [comment]
The final reason is we have 350k files inside `access` directory. Loading of all access control files is triggered for the first connections. So it behaves as if 'stuck' for connections before access control is fully loaded.
