### ISSUE TITLE
Allow writing table name as a string literal.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#52178]
Currently, we allow writing table names as an identifier:

```
SELECT * FROM table
```

Identifiers can be quoted in ANSI SQL style way:
```
SELECT * FROM "table"
```

And in MySQL style way:
```
SELECT * FROM `table`
```

Recently we started to recognize files as table names in clickhouse-local automatically:
```
SELECT * FROM "dataset.avro"
```

And clickhouse-local is often used in batch mode:
```
clickhouse-local --query "SELECT * FROM table"
```

But if a query is specified in double quotes, as in the example above, using either double quotes or backticks for table name identifier is inconvenient:

```
clickhouse-local --query "SELECT * FROM \"dataset.avro\""
```

And it will be better to allow table names as string literals:

```
clickhouse-local --query "SELECT * FROM 'dataset.avro'"
```

Although it could make some complications, such as the inability to specify a qualified name with a database name, we can only support a simple, unqualified form initially.

**Comment by pegasas** [comment]
Hi, @alexey-milovidov , @nikitamikhaylov, is this task started?

I am new here who wants to contribute to this project, 
could I take the project?

Would you like to provides some similar pull requests or guideline for helping to know that where layout should I start to develop in this project?
