### ISSUE TITLE
The memory consumed during merge is probably related to what factors

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#52179]
I would like to know what factors are related to the memory consumed during merge?
For example, is it related to the size of the part that needs to be merged? And, if there are six 80G parts that need to be merged, will the memory occupy 6*80G?

**Comment by alexey-milovidov** [comment]
It is not related to the size of the parts. Memory consumption is O(1) related to the part size or the number of records.

**Comment by alexey-milovidov** [comment]
It is related to the number of columns, the maximum value size of the columns, and the maximum size of a dictionary for the LowCardinality data type.

**Comment by alexey-milovidov** [comment]
Typical values for memory consumption during a merge are way below 1 GB.
