### ISSUE TITLE
Bandwidth configration not work for moving data from local disk to s3 by ttl

### ISSUE THREAD

**Issue by coulsonm** [ClickHouse/ClickHouse#52183]
clickhouse version:22.3.1

I tried Mergetree with S3 disks. Data stored in local disks and then moved to s3 by ttl. 
I limited 
`                        <max_remote_read_network_bandwidth_for_server>10485760</max_remote_read_network_bandwidth_for_server>
                     <max_remote_write_network_bandwidth_for_server>10485760</max_remote_write_network_bandwidth_for_server>
                       <max_replicated_fetches_network_bandwidth_for_server>10485760</max_replicated_fetches_network_bandwidth_for_server>
                     <max_replicated_sends_network_bandwidth_for_server>10485760</max_replicated_sends_network_bandwidth_for_server>
<max_network_bandwidth>10485760</max_network_bandwidth>
<max_network_bandwidth_for_all_users>10485760</max_network_bandwidth_for_all_users>`

No people use this cluster except clickhouse ttl moving parts.But the bandwidth more than 10Mb/s
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/ccc205d2-4cb5-45c7-b860-74ea30830ee7)

_Originally posted by @coulsonm in https://github.com/ClickHouse/ClickHouse/issues/52079#issuecomment-1637487505_

**Comment by coulsonm** [comment]
Data moving only occurs during the time indicated by the red box.

**Comment by coulsonm** [comment]
@serxa

**Comment by coulsonm** [comment]
I tried the new version: clickhouse 23.6.2.18

I used Mergetree,not Replicated Mergetree. Data stored in local disks and then moved to s3 by ttl.
I limited
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/9929deab-f97f-4fa7-850f-8b33832cdd7b)

No people use this cluster except clickhouse ttl moving parts.But the bandwidth more than 10Mb/s

![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/e64fd19f-c82e-4fa1-9fde-15c37860f374)
 Data moving only occurs during the time indicated by the red box.

**Comment by serxa** [comment]
What is the duration of this peak violating the limit?

**Comment by coulsonm** [comment]
After that peak, all data has been moved.

**Comment by coulsonm** [comment]
I tried again, data inserted to local disk very slowly. 
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/16fccd9a-77fd-4496-a832-dcbb4bc26bba)

I used command `iftop` to check the speed of data moved to s3.
![image](https://github.com/ClickHouse/ClickHouse/assets/127475879/1d42e3b8-e45a-4086-a5e3-f68bd80cb887)

**Comment by coulsonm** [comment]
@serxa

**Comment by coulsonm** [comment]
I tried many times, this speed keeped for several minutes for each experiment

**Comment by coulsonm** [comment]
@serxa

**Comment by coulsonm** [comment]
I tried max_backup_bandwidth. It still not works. Seems no Throttler was used in MergeTreePartsMover::clonePart?

**Comment by coulsonm** [comment]
Any ideas for this issue？ @serxa
