### ISSUE TITLE
clickhouse  Startup error, unable to allocate memory

### ISSUE THREAD

**Issue by shitianmori** [ClickHouse/ClickHouse#52182]
Execute Command
``` 

sudo clickhouse start

 (version 23.6.1.1524 (official build))
Logging trace to /data/clickhouse/log/clickhouse-server.log
Logging errors to /data/clickhouse/log/clickhouse-server.err.log
Code: 173. DB::ErrnoException: MMappedFileDescriptor: Cannot mmap 30.00 B., errno: 19, strerror: No such device. (CANNOT_ALLOCATE_MEMORY), Stack trace (when copying this message, always include the lines below):

 (version 23.6.1.1524 (official build))
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/d7f2b78c-5a2f-4aab-a4d6-8829e0b1b969)


```[tasklist]
### Tasks
```

**Comment by shitianmori** [comment]
[root@CK_node5 ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[root@CK_node5 ~]#

**Comment by santrancisco** [comment]
@shitianmori  , according to this previous user who [ran into the same issue](https://github.com/ClickHouse/ClickHouse/issues/49786), removing clickhouse.debug file  (`rm -rf /usr/lib/debug/usr/bin/clickhouse.debug`) seems to did the trick. It was identified by [this user](https://github.com/ClickHouse/ClickHouse/issues/42480) as well

**Comment by shitianmori** [comment]
删除了文件，clickhouse可以启动了
The file has been deleted, and clickhouse can be started now

**Comment by guoxiaolongzte** [comment]
It's great. I also encountered similar problems and successfully solved them.

**Comment by beback-code** [comment]
I checked the operating system and did not find the file /usr/lib/debug/usr/bin/clickhouse.debug
