### ISSUE TITLE
Uniq on Cluster

### ISSUE THREAD

**Issue by mathewsp79** [ClickHouse/ClickHouse#522]
I have a billion row table  in a 3 node cluster setup . When I run queries for straight agg functions like sum , count() etc on distributed table it works fast.
But when I run uniq() on dist table , it is much slower than running uniq() on local table on 1 node. One one node uniq() came back within 5 secs. While uniq() in dust table came back within 11 secs.
How do you make it fast?

**Comment by alexey-milovidov** [comment]
In distributed setup, intermediate states of aggregate function need to be serialized and transferred over the network. Performance is depend on size of intermediate data and network speed.

Try to use different aggretate functions. For example, `uniqCombined` have smaller state and it is also usually more precise than `uniq`. But `uniqCombined` is less CPU-efficient.

**Comment by mathewsp79** [comment]
I did try with uniqCombined & yes it did improve the time a little bit but still not as fast as the local table uniq .
I was playing with different query set ups & the closest i have to achieving this is like this given below.

What i did is 

- for uniq used the local table

- for other calcs like Sum (), count() etc , i used the DISTRIBUTED Table

& then used an inner join to connect the two.
It may be overkill but the query returns in almost the same time as single local table...

**Reference Query**

select station_no,ad_product_name,act_hh,vfreach,act_imps,round(act_imps / act_hh, 3) AS act_freq,
	round(act_hh * vfreach) AS proj_reach,
	round(proj_reach*act_freq) as proj_imps from 
(
select  station_no, dictGetString('ad_details_tmp', 'ad_product_name', ad_no_rn) as ad_product_name,  
      uniq(as_hh_no) AS act_hh,
count() AS act_imps
    	from live_tunes_HAST_517_623_803_JAN2016  
  where   station_no IN ( 4621,4930,4992,5558,4622) 
group by  station_no,ad_product_name order by act_imps DESC LIMIT 20
) AS a
**ANY INNER JOIN**
(
select  station_no, dictGetString('ad_details_tmp', 'ad_product_name', ad_no_rn) as ad_product_name,  
     min(universe_vertical_factor) AS vfreach,
    count() AS act_imps
    	from live_tunes_HAST_517_623_803_JAN2016_x3  
  where   station_no IN ( 4621,4930,4992,5558,4622) 
group by  station_no,ad_product_name order by act_imps DESC LIMIT 20)
AS b 
USING (station_no,ad_product_name)

**Comment by alexey-milovidov** [comment]
Also try to define `ad_product_name` dictionary attribute as `<injective>true</injective>`.
(Look at `injective` here: https://clickhouse.yandex/reference_en.html#External%20dictionaries)

In that case, dictionary values will be substituted after GROUP BY.

**Comment by blinkov** [comment]
@mathewsp79 do you need any more help here?
