### ISSUE TITLE
How can I use headers with s3 function

### ISSUE THREAD

**Issue by minguyen-jumptrading** [ClickHouse/ClickHouse#52200]
My gcp is behind a reverse proxy and it requires some header when sending the request,

How can I add the headers when calling s3 function.

I tried, but it doesnt seems to work.
```
select * FROM s3('http://proxy:12345/storage/v1/<path>/data.tsv', 'xxx', 'xxx', 'xxx', xxx', headers('X-Varnish-Host'='storage.googleapis.com', 'X-Varnish-Scheme'='https')) limit 10;

```

**Comment by santrancisco** [comment]
Can you check the version of clickhouse server with `select version()` ? 
From my test with latest clickhouse using clickhouse local, i can see headers  working as expected and I'm pretty sure this has been around for very long time.

I tested the following query against my test server which captures requests and can see the headers (Whatever) being embedded in the request to my server.

```
SELECT *
FROM s3('http://myownserver/testcapture', 'FAKEACCESSKEY', 'FAKESECRETKEY', JSONEachRow, headers('Whatever' = 'TestS3'))
```

![CleanShot 2023-07-18 at 13 46 43@2x](https://github.com/ClickHouse/ClickHouse/assets/3240146/1e6acc55-42bb-4ea4-b6d6-d8d784820b02)

**Comment by minguyen-jumptrading** [comment]
my version is `23.3.1.2226`
