### ISSUE TITLE
Preprocessed config file with hidden/in-memory parts

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#52207]
https://github.com/ClickHouse/ClickHouse/issues/48291 and https://github.com/ClickHouse/ClickHouse/pull/50986 try to avoid plaintext passwords in configuration files. A second angle of attack is the preprocessed XML file which might contains sensitive data (fused from multiple XML/JSON files with varying access rights). We should check if parts of the configuration tree can be marked "hidden" such they are not written into the preprocessed XML file in the first place.

(perhaps it is easier to avoid writing a preprocessed XML file altogether, i.e. rather do both steps of preprocessing and populating the server config from the preprocessed data entirely in-memory)

**Comment by rvasin** [comment]
Please assign me to this task.
