### ISSUE TITLE
can you support chinese?   json path key  contains chinese。it's very import for chinese   

### ISSUE THREAD

**Issue by wanxianbo** [ClickHouse/ClickHouse#52236]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
such  as form.u_中文 like ‘%我是中国人%’

**Comment by melvynator** [comment]
Hello @wanxianbo . Do you mean supporting Chinese characters in JSON object? Could you add a bit more context to your question? An example of ClickHouse failing would be great.

**Comment by wanxianbo** [comment]
ok, for example; 
`create table directory_preDocument
(
    `$json` JSON
)engine = MergeTree ORDER BY tuple()`
`insert into directory_preDocument values('{"id": "a01032e2d2c3c8010bc0", "form": {"purpose": "", "currency": "CNY", "u_审批明细表" : { "u_审批人" : "蔡美满(CMM)"}}}')` 报错DB::Exception: Data in Object has ambiguous paths: 'form.u_审批明细表.u_审批人' and 'form.u_审批明细表.u_创建人'. Paths have prefixes matched by names, but different in structure. (INCOMPATIBLE_COLUMNS) (version 23.6.1.1524 (official build))

**Comment by tavplubix** [comment]
@wanxianbo, it already works:

```
dell9510 :) create table directory_preDocument ( json JSON )engine = MergeTree ORDER BY tuple();

CREATE TABLE directory_preDocument
(
    `json` JSON
)
ENGINE = MergeTree
ORDER BY tuple()

Query id: 851f9af4-a79f-4e65-9b4c-21a664a07eab

Ok.

0 rows in set. Elapsed: 0.026 sec. 

dell9510 :) insert into directory_preDocument values('{"id": "a01032e2d2c3c8010bc0", "form": {"purpose": "", "currency": "CNY", "u_审批明细表" : { "u_审批人" : "蔡美满(CMM)"}}}');

INSERT INTO directory_preDocument FORMAT Values

Query id: 5a156f5f-d5c7-4ed8-8a30-90db25c5ba84

Ok.

1 row in set. Elapsed: 0.043 sec. 

dell9510 :) select * from directory_preDocument

SELECT *
FROM directory_preDocument

Query id: 12d683d8-57b9-41ba-95ec-63e21846912e

┌─json────────────────────────────────────────────────┐
│ (('CNY','',('蔡美满(CMM)')),'a01032e2d2c3c8010bc0') │
└─────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.026 sec. 
```
