### ISSUE TITLE
Insertion stuck on ReplicatedMergeTree when keeper connection lost.

### ISSUE THREAD

**Issue by yexia0** [ClickHouse/ClickHouse#52233]
I setup a cluster with 2 nodes. each node run a clickhouse server as well as an embedded keeper.
If i shut down one node. The keeper node will fail because quorum is 2 and only 1 keeper alive.
In this case, ReplicatedMergeTree tables should be readonly on the remaining node.

But when I do insertion on the table. it never returns and stuck. Is this expected behavior?

**Comment by yexia0** [comment]
Actually it returns read-only after more than 2 minutes. From the log in `ZooKeeperRetriesControl` it tries to connect to zookeeper and retried 20 times. Is there a way to reduce this number? I want it to fail fast and handle the read-only error on our own code.

**Comment by nickitat** [comment]
fyi using 2 nodes for keeper is not recommended
