### ISSUE TITLE
Insert data with nulls from csv to table to not nullable columns but error not raised

### ISSUE THREAD

**Issue by sam-leonid** [ClickHouse/ClickHouse#52257]
I have a table:

```
CREATE TABLE test.test
(
    `f1` String,
    `f2` String,
    `f3` Int8,
    `f4` Float64,
    `f5` DateTime64(3)
)
ENGINE = MergeTree
PRIMARY KEY f1
ORDER BY f1
SETTINGS index_granularity = 8192;
```

And csv file:
```
f1;f2;f3;f4;f5
test;abc;4545;4.5454;1990-03-01 00:00:00
test;abc;4646;4.5454;1990-03-01 00:00:00
test;;;;
```

I try to run insert:

```
INSERT INTO test.test FORMAT CSVWithNames SETTINGS < test.csv
```

And I want to get error (null values are not allowed for table). But I have result:

```
SELECT *
FROM test.test2

┌─f1───┬─f2──┬──f3─┬─────f4─┬──────────────────────f5─┐
│ test │ abc │ -63 │ 4.5454 │ 1990-03-01 00:00:00.000 │
│ test │ abc │  38 │ 4.5454 │ 1990-03-01 00:00:00.000 │
│ test │     │   0 │      0 │ 1970-01-01 03:00:00.000 │
└──────┴─────┴─────┴────────┴─────────────────────────┘
```

I tried some settings **(input_format_csv_empty_as_default=0, input_format_csv_empty_as_default=0, insert_null_as_default=0)**. But it not worked.

Is there a solution for this problem?

**Clickhouse version: 22.8.4.7**

**Comment by den-crane** [comment]
That is expected. Clickhouse does not have Null constraints and converts Nulls to default value automatically.

You can use CHECK constraints  https://clickhouse.com/docs/en/sql-reference/statements/create/table#constraints and forbid dates below than 2000-01-01.
