### ISSUE TITLE
Row-level security in ClickHouse

### ISSUE THREAD

**Issue by lemmsh** [ClickHouse/ClickHouse#523]
# Row-level security

Hi guys.

As far as I understand the only possible way to segregate user access to the data inside ClickHouse is to use 'allowed_databases' section in the user configuration in the users.xml (this is not documented BTW, I accidentally found this in the code). That is we can only segregate users on the database level.

In some use cases, especially in highly regulated businesses, there is a need of a more fine-grained security. Ideally this should be a row-level security mechanism similar to the one PostgreSQL has (https://www.postgresql.org/docs/9.5/static/ddl-rowsecurity.html). I've described below how I see this can be implemented. Please share what you think.

## A quick way

In ClickHouse typical use case the data is usually created without direct human intervention thus it seems perfectly fine to secure the select queries only. This way there will be a some simplest possible row-level security in CH for read-only accounts. We can naturally use the Views for it, but there is currently no per-table permissions.

It looks relatively simple to fix: we can change the
```
bool isAllowedDatabase(const std::string & user_name, const std::string & database_name) const
```
in Users.hpp into something like
```
bool isAllowedTable(const std::string & user_name, const std::string & database_name, const std::string & table_name) const
```
and fill the allowed tables set from the users.xml. What I'm not sure of is whether the  permissions on a View are checked before or after the View is substituted with the subquery expression. I'd bet on the latter actually, and if I'm right we'll need to change that.

## The cool solution

With the views we can achieve both row and column level security to some level but it still will not be fully-featured row-level security of our dream. Specifically when a user makes a query on a restrictive view the aggregated metrics he get will be affected by his lack of permissions to see some secret rows. In most cases of which I'm aware of it's an overkill and we would want the user to see the correct aggregated values if he is not able to derive the secret values from them. I think we can safely assume that if there is more than 'X' values participating in an aggregate we can show it to user and if not we would show something like a warning or NaN's or 'HIDDEN' whatever. This cannot be achieved through the Views and should actually be done somewhere near the place where 'Having' is evaluated

Another side of this problem is that we're not able to mask a subset of columns. Say we only have one truly secret column in the table which we do not like our fellow analysts to see if `secret in (a,lot,of,megasecret,values)`. If a fellow analyst makes a query on anything except the `secret` he will get the filtered set of rows anyway which is bad. The aggregates are distorted in this case as well.

The ideal way of all this to work would be like the following. Suppose have a table with millions of experimental measurements of some world's constants which are averaging to their true value. A fellow analyst is not allowed to see the name of the 'answer to the ultimate question of everything' but he has access to everything else. He should see something like this:
```
:) SELECT name, avg(value) FROM measurements GROUP BY name;

e    2.71
sqrt2    1.4142
pi    3.1415

HIDDEN    42

```
While the hidden dimensions have relatively simple logic, the metrics are more tricky. I think it may not be possible to prevent guessing of the hidden metric value if we allow an aggregate on it, so we should probably sacrifice the aggregated values precision here and just skip such values.

If implemented the feature would blow the minds of people desperate for big data analysis in a regulated businesses :)

Thanks a lot!
I'm actually ready to contribute the code if we agree on how to implement the thing. We probably should start from the quick way as it is still useful despite it's flaws and will make some engineers happy :)

Pavel

**Comment by alexey-milovidov** [comment]
Now we have a demand for row-level security even from our internal users. We will implement it.
But our internal users propose some ad-hoc solutions like specifying user -> table -> where condition in users.xml.

**Comment by alexey-milovidov** [comment]
We have implemented this "unmanageable hell" in #4828

**Comment by lemmsh** [comment]
I don't quite get how... I only see in that commit that libunwind has been moved from contrib

**Comment by alexey-milovidov** [comment]
#4792

**Comment by lemmsh** [comment]
awesome! 

From a quick look on the code I see that only static expression can be in the filter for now. Almost all our use cases require filters like 'where some_id in (select id from allowed_ids where user = '${current_user}')'. But it looks like relatively easy to fix.

Why didn't you make it on AST level? it seems to me that you'd not have 'PREWHERE' limitation in that case...

For us it's still a blocker not to have a way to build a 'plugin' for auth though. Probably UsersManager can evolve into something pluggable with time being

**Comment by alexey-milovidov** [comment]
> Why didn't you make it on AST level?

It's more error-prone to do it on AST level and also more difficult to implement.

> a way to build a 'plugin' for auth though

This is a separate feature, will be addressed after implementation of RBAC.
