### ISSUE TITLE
How can I find this monitoring metric(prometheus) 'query execution time'

### ISSUE THREAD

**Issue by sunshup** [ClickHouse/ClickHouse#52305]
How can I find this monitoring metric 'query execution time'.
I want to watch this metric in grafana, but I can't find it from [localhost:9363/metric](localhost:9363/metric) .
Is there any way to accomplish this？

**Comment by cangyin** [comment]
install this [ClickHouse plugin](https://grafana.com/grafana/plugins/grafana-clickhouse-datasource/)  in grafana.

and visiualize query like:
```sql
SELECT query_duration_ms FROM system.query_log
```

**Comment by alexey-milovidov** [comment]
It is named `QueryTimeMicroseconds`
