### ISSUE TITLE
UDF Python interpreter choice with shebang seems to be working incorrectly

### ISSUE THREAD

**Issue by YuriWerewolf** [ClickHouse/ClickHouse#52319]
Dear all,
have run into the following issue with defining Python interpreter with shebang for UDF.

Old version of python 3.10.6 works fine.
When trying to use link to conda environment installation of Python(3.10.8)  in UDF script it seems it doesn't get picked up.
`#!/usr/bin/env python3

import sys

if __name__ == '__main__':
    for line in sys.stdin:
        print(sys.version)
        sys.stdout.flush()`

Produces output:
test_function_python(222)                        |
-------------------------------------------------+
3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]|

If using link to the miniconda environment I get error:
`#!/home/yuri/miniconda3/bin/python3

import sys

if __name__ == '__main__':
    for line in sys.stdin:
        print(sys.version)
        sys.stdout.flush()` 

> SQL Error [75] [07000]: Code: 75. DB::ErrnoException: Cannot write into pipe, errno: 32, strerror: Broken pipe: While executing TabSeparatedRowOutputFormat: While processing test_function_python(222). (CANNOT_WRITE_TO_FILE_DESCRIPTOR) 

I have added miniconda path to the $PATH so which command seems to indicate 3.10.8 (correct) version should be picked up first

> ~/Python Old Desktop$ which python3
/home/yuri/miniconda3/bin/python3

Default Python interpreter seems to be correct as well:
~$ python3
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

Running code from command line works as  well, ie correct version of python in shebang is getting picked up. 

> ~$ sudo /var/lib/clickhouse/user_scripts/test_function.py
Hello
3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]

**Comment by YuriWerewolf** [comment]
Also when using the link from the shebang that works in Clickhouse i get  correct Python interpreter:

> $ /usr/bin/env python3

> Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] on linux

To get version 3.10.6 that  the link above references I need to use :+1: 

> $ /usr/bin/python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux

So looks like there is discrepancy in picking up the path using shebang in system promt vs when trying to use the script in Clickhouse UDF?

**Comment by cangyin** [comment]
Define this UDF in `/etc/clickhouse-server/env_function.xml`:
```xml
<functions>
    <function>
        <type>executable</type>
        <name>env</name>
        <return_type>String</return_type>
        <format>RawBLOB</format>
        <command>env | grep PATH</command>
        <execute_direct>0</execute_direct>
    </function>
</functions>
```

and in clickhouse-client:
```sql
SYSTEM RELOAD CONFIG;

SELECT env();
```

to check the content of `PATH` variable inside clickhouse-server.

**Comment by YuriWerewolf** [comment]
Yes, PATH from the Clickhouse using your function above is different from what i see in the shell.

> env()                                                                                               |
----------------------------------------------------------------------------------------------------+
PATH=/user/yuri/user_scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin¶|

That's the system PATH from the shell (i have added the path to the required env):

> PATH=/home/yuri/miniconda3/bin:/home/yuri/miniconda3/condabin:/home/yuri/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by cangyin** [comment]
Then re-started clickhouse-server from the shell with Python 3.10.8 (miniconda3) in $PATH
```bash
# like:
clickhouse stop;
clickhouse su clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid;
# this command is copied from file /lib/systemd/system/clickhouse-server.service of RPM installation, version 23.2.4.12
```

or try placing `PATH=/path/to/miniconda3/python:$PATH` into your bash profile (`~/.bashrc`) and reboot.

**Comment by YuriWerewolf** [comment]
So I have put PATH into ~/. bashrc and rebooted , no help.

When I have tried to start clickhouse using your line above I have run into an error and it didn't start.

> <Error> Application: Code: 214. DB::ErrnoException: Could not calculate available disk space (statvfs), errno: 13, strerror: Permission denied. (CANNOT_STATVFS), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/../src/Common/Exception.cpp:77: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0xf4737ba in /usr/bin/clickhouse
1. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>> const&) @ 0xf474593 in /usr/bin/clickhouse
2. ./build_docker/../src/Common/Exception.cpp:0: DB::throwFromErrnoWithPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, int) @ 0xf4748d1 in /usr/bin/clickhouse
3. ./build_docker/../src/Common/filesystemHelpers.cpp:54: DB::getStatVFS(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0xf4afdda in /usr/bin/clickhouse
4. ./build_docker/../contrib/llvm-project/libcxx/include/string:1499: DB::ServerAsynchronousMetrics::updateImpl(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, DB::AsynchronousMetricValue, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, DB::AsynchronousMetricValue>>>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>) @ 0x14d07a51 in /usr/bin/clickhouse
5. ./build_docker/../base/glibc-compatibility/musl/clock_gettime.c:62: DB::AsynchronousMetrics::update(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>) @ 0xf591b4d in /usr/bin/clickhouse
6. ./build_docker/../contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:714: DB::AsynchronousMetrics::start() @ 0xf5833e1 in /usr/bin/clickhouse
7. ./build_docker/../programs/server/Server.cpp:0: DB::Server::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0xf504d20 in /usr/bin/clickhouse
8. ./build_docker/../contrib/poco/Util/src/Application.cpp:0: Poco::Util::Application::run() @ 0x18a870a2 in /usr/bin/clickhouse
9. ./build_docker/../programs/server/Server.cpp:474: DB::Server::run() @ 0xf4f377c in /usr/bin/clickhouse
10. ./build_docker/../contrib/poco/Util/src/ServerApplication.cpp:612: Poco::Util::ServerApplication::run(int, char**) @ 0x18a9b3fa in /usr/bin/clickhouse
11. ./build_docker/../programs/server/Server.cpp:0: mainEntryClickHouseServer(int, char**) @ 0xf4f01de in /usr/bin/clickhouse
12. ./build_docker/../programs/main.cpp:0: main @ 0x8a06c73 in /usr/bin/clickhouse
13. ? @ 0x7ff5cfb37d90 in ?
14. __libc_start_main @ 0x7ff5cfb37e40 in ?
15. _start @ 0x7f57f2e in /usr/bin/clickhouse
 (version 22.13.1.1561 (official build))
2023.07.20 02:19:28.108794 [ 3962 ] {} <Error> Application: DB::ErrnoException: Could not calculate available disk space (statvfs), errno: 13, strerror: Permission denied




I usually start it using sudo clickhouse start:

> $ sudo clickhouse start
 chown -R clickhouse: '/var/run/clickhouse-server/'
Will run sudo -u 'clickhouse' /usr/bin/clickhouse-server --config-file /etc/clickhouse-server/config.xml --pid-file /var/run/clickhouse-server/clickhouse-server.pid --daemon
Waiting for server to start
Waiting for server to start
Server started

but still everything was the same after I started it using:  sudo clickhouse start  from the system promt with correct Python.

**Comment by YuriWerewolf** [comment]
How I can change the path variable that is inside Clickhouse?

I guess another solution is to have python3 link in the default folder redirect to the miniconda environment. But that can break other things in linux.

**Comment by yakov-olkhovskiy** [comment]
@YuriWerewolf your clickhouse server is running under user 'clickhouse' (that `Will run sudo -u 'clickhouse' /usr/bin/clickhouse-server` line says) - so you need to add whatever path you want to 'clickhouse' user's profile...
