### ISSUE TITLE
Build failed in centos7

### ISSUE THREAD

**Issue by Factz563** [ClickHouse/ClickHouse#52330]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
Building in Centos7 - docker
Ubuntu - Host

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**
3.21.1

**Ninja version**
1.10.2

**Compiler name and version**
Clang-16

**Full cmake and/or ninja output**
[ 64%] Built target _sasl2
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/gc-gnulib.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/printf-parse.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/c-ctype.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/float.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/printf-args.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/hmac-sha1.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/itold.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/hmac-md5.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/gc-pbkdf2-sha1.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/md5.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/base64.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/memxor.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gl/sha1.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/openid20/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/openid20/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/openid20/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/anonymous/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/anonymous/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/anonymous/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/saml20/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/saml20/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/saml20/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/scram/parser.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/scram/printer.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/scram/tokens.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/scram/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/scram/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/scram/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/scram/validate.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/free.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/supportp.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/init.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/mechtools.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/error.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/property.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/done.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/callback.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/xstart.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/xfinish.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/version.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/xstep.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/mechname.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/xcode.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/crypto.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/doxygen.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/suggest.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/saslprep.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/listmech.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/register.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/base64.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/src/md5pwd.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/external/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/external/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/external/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/securid/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/securid/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/securid/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/plain/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/plain/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/plain/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/cram-md5/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/cram-md5/challenge.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/cram-md5/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/cram-md5/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/cram-md5/digest.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/digesthmac.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/free.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/getsubopt.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/nonascii.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/parser.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/printer.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/qop.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/session.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/test-parser.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/digest-md5/validate.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/login/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/login/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/login/server.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gssapi/client.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gssapi/mechinfo.c.o
[ 64%] Building C object contrib/libgsasl-cmake/CMakeFiles/_gsasl.dir/__/libgsasl/gssapi/server.c.o
[ 64%] Linking CXX static library lib_gsasl.a
[ 64%] Built target _gsasl
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/crc32c.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdaddr.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdavl.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdbuf.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdcrc32.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rddl.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdfnv1a.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdgz.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdhdrhistogram.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_admin.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_assignment.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_assignor.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_aux.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_background.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_broker.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_buf.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_cert.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_cgrp.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_conf.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_coord.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_error.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_event.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_feature.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_header.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_idempotence.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_interceptor.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_lz4.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_metadata.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_metadata_cache.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_mock.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_mock_cgrp.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_mock_handlers.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_msg.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_msgset_reader.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_msgset_writer.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_offset.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_op.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_partition.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_pattern.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_plugin.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_queue.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_range_assignor.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_request.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_roundrobin_assignor.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_sasl.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_sasl_plain.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_sticky_assignor.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_subscription.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_timer.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_topic.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_transport.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_txnmgr.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_zstd.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdlist.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdlog.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdmap.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdmurmur2.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdports.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdrand.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdregex.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdstring.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdunittest.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdvarint.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdxxhash.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/snappy.c.o
[ 64%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/tinycthread.c.o
[ 65%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/tinycthread_extra.c.o
[ 65%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_ssl.c.o
[ 65%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_sasl_cyrus.c.o
[ 65%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_sasl_scram.c.o
[ 65%] Building C object contrib/librdkafka-cmake/CMakeFiles/_rdkafka.dir/__/librdkafka/src/rdkafka_sasl_oauthbearer.c.o
[ 65%] Linking CXX static library lib_rdkafka.a
[ 65%] Built target _rdkafka
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/asynccb.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/buf.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/comsock.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/conn.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/crypto.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/hash.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/js.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/jsm.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/kv.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/msg.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/nats.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/natstime.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/nkeys.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/nuid.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/opts.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/parser.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/pub.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/srvpool.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/stats.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/status.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/sub.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/timer.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/url.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/util.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/unix/cond.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/unix/mutex.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/unix/sock.c.o
[ 65%] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/unix/thread.c.o
[ 65%] Linking CXX static library lib_nats_io.a
[ 65%] Built target _nats_io
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/crc/crc_base_aliases.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/crc/crc_base.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/crc/crc64_base.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/erasure_code/ec_base.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/erasure_code/ec_base_aliases.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/erasure_code/ec_highlevel_func.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/erasure_code/gen_rs_matrix_limits.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/erasure_code/gf_vect_dot_prod_1tbl.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/adler32_base.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/encode_df.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/flatten_ll.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/generate_custom_hufftables.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/generate_static_inflate.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/huff_codes.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/hufftables_c.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/igzip_base_aliases.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/igzip_base.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/igzip_icf_base.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/igzip_icf_body.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/igzip_inflate.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/igzip/igzip.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/mem/mem_zero_detect_base_aliases.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/mem/mem_zero_detect_base.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/programs/igzip_cli.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/raid/raid_base_aliases.c.o
[ 65%] Building C object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/raid/raid_base.c.o
[ 65%] Building ASM_NASM object contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/crc/crc_multibinary.asm.o
/apt/ClickHouse/contrib/isa-l/crc/crc_multibinary.asm:33: fatal: unable to open include file `reg_sizes.asm'
gmake[2]: *** [contrib/isa-l-cmake/CMakeFiles/_isal.dir/__/isa-l/crc/crc_multibinary.asm.o] Error 1
gmake[1]: *** [contrib/isa-l-cmake/CMakeFiles/_isal.dir/all] Error 2
gmake: *** [all] Error 2
The command '/usr/bin/scl enable devtoolset-9 cmake -DCOMPILER_CACHE=disabled -D UNBUNDLED=1 -S .. -B build &&     cmake --build build' returned a non-zero code: 2

**Comment by alexey-milovidov** [comment]
Build exactly as per instruction https://clickhouse.com/docs/en/development/build/
or as per build logs from the master branch: https://s3.amazonaws.com/clickhouse-test-reports/0/e0059b3dcb31bf72be85a73cb0396881888932ad/clickhouse_build_check/report.html
