### ISSUE TITLE
An error is reported when the JSON type joint table query gets the fields of the joint table

### ISSUE THREAD

**Issue by wanxianbo** [ClickHouse/ClickHouse#52331]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

for example;
```mysql
SET allow_experimental_object_type = 1;
CREATE table table_one
(
    id LowCardinality(String) DEFAULT JSONExtractString(message_raw, 'id'),
    name LowCardinality(String)  DEFAULT JSONExtractString(message_raw, 'name'),
    message     JSON                  DEFAULT message_raw,
    message_raw String EPHEMERAL
) ENGINE = MergeTree ORDER BY (id, name);


SET allow_experimental_object_type = 1;
CREATE table table_two
(
    id LowCardinality(String) DEFAULT JSONExtractString(message_raw, 'id'),
    name LowCardinality(String)  DEFAULT JSONExtractString(message_raw, 'name'),
    message_two     JSON                  DEFAULT message_raw,
    message_raw String EPHEMERAL
) ENGINE = MergeTree ORDER BY (id, name);

insert into table_one (message_raw) values ('{"id":"1", "name":"one"}');
insert into table_two(message_raw) values ('{"id":"1", "name":"two"}');
insert into table_two(message_raw) values ('{"id":"2", "name":"three"}');
```
When querying joint tables, an error occurred when querying the name field in the json of the t2 table
```mysql
select t2.message_two.'name'
from table_one t1 inner join table_two t2 on t1.id = t2.id
where t1.message.'name' = 'one';
```
report error：
 Code: 43. DB::Exception: First argument for function tupleElement must be tuple or array of tuple. Actual Object('json'): While processing tupleElement(message_two, 'name'). (ILLEGAL_TYPE_OF_ARGUMENT) (version 23.6.1.1524 (official build))

Get the fields of the t1 table without reporting an error
```mysql
select t1.message.'name'
from table_one t1 inner join table_two t2 on t1.id = t2.id
where t1.message.'name' = 'one';
```

Version Information：
23.6.2.18

**Comment by alexey-milovidov** [comment]
> SET allow_experimental_object_type = 1;

We don't support it.
