### ISSUE TITLE
Broken AST formatting of select with intersect and union all 

### ISSUE THREAD

**Issue by devilcony** [ClickHouse/ClickHouse#52349]
When i try to create a table in all cluster using a query with [intersect] and [union all], the table is created but the result is not as i expected. It seems like bracket does not work or wrong priority with [intersect] and [union all] in [create table on cluster as]

The select sql :
`select 1 as c
intersect (select 1 as c
            union all 
           select 2 as c
);`
![image](https://github.com/ClickHouse/ClickHouse/assets/3895260/65ef6f0a-19e1-467c-89ed-3ce72aa3bbe0)

use create table like this:
`create table ltv.t1 on cluster cluster_ltv_replacingmergetree engine=MergeTree() order by c as (
select 1 as c
intersect (select 1 as c
            union all 
           select 2 as c
          )
);
`
`select * from ltv.t1;`
result is 1 and 2

![image](https://github.com/ClickHouse/ClickHouse/assets/3895260/6301389a-ba0b-4a43-abe2-6d61e29f5aed)

I have tried two versions:23.6.2.18 ,22.2.2.1

**Comment by devilcony** [comment]
Remove on cluster from the sql, the result is 1
![image](https://github.com/ClickHouse/ClickHouse/assets/3895260/b7e19532-4ed2-4bc3-a209-36f5584b3658)

**Comment by tavplubix** [comment]
It's a bug in query formatting (parenthesis are omitted): https://pastila.nl/?0143ff41/2e2800674b05fa1500f6c42f1e87e7c3

**Comment by alexey-milovidov** [comment]
#60095
