### ISSUE TITLE
The default configuration for clickhouse is always memory overflow on servers with 16g of memory during large writes

### ISSUE THREAD

**Issue by yimogit** [ClickHouse/ClickHouse#52350]
My application scenario requires timely synchronization of mongodb change data to clickhouse，I would like to know how to configure the 8C16G server to achieve optimal performance，Can we achieve better performance without any exceptions by optimizing the following configurations

```
 <max_connections>4096</max_connections>
    <keep_alive_timeout>3</keep_alive_timeout>
    <max_concurrent_queries>100</max_concurrent_queries>
     <max_thread_pool_size>10000</max_thread_pool_size>
    <total_memory_profiler_step>4194304</total_memory_profiler_step>
    <uncompressed_cache_size>8589934592</uncompressed_cache_size>
    <mark_cache_size>5368709120</mark_cache_size>
```

Currently, there will be an exception during the synchronization process: `Memory limit (total) exceeded: would use 13.87 GiB (attempt to allocate chunk of 4196461 bytes), maximum: 13.87 GiB  `

thx

**Comment by den-crane** [comment]
> <uncompressed_cache_size>8589934592</uncompressed_cache_size>

Do you really have uncompressed_cache_size enabled? Because you wasted 8GB of 16G.
Share `select * from system.settings where name like '%uncompressed_cache%';`

**Comment by den-crane** [comment]
Check this queries https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/

Also share `select version()`

**Comment by yimogit** [comment]
> > <uncompressed_cache_size>8589934592</uncompressed_cache_size>
> 
> 您真的启用了uncompressed_cache吗？因为你浪费了8GB的16G。 分享`select * from system.settings where name like '%uncompressed_cache%';`
![image](https://github.com/ClickHouse/ClickHouse/assets/15975059/a20be186-9449-4296-b7cc-6fd5e01bc84f)
![image](https://github.com/ClickHouse/ClickHouse/assets/15975059/55c628e4-5185-49ac-be62-77f07a75f4e0)

clickhouse version is 20.8.18.32
uncompressed_cache_size：0

This is my configuration, so it seems that I may need to modify this value to a smaller value to take effect?
```
<uncompressed_cache_size>8589934592</uncompressed_cache_size>
```

thx

**Comment by yimogit** [comment]
> Check this queries https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/
> 
> Also share `select version()`

Query SQL for memory usage through it

```
SELECT
    type,
    event_time,
    initial_query_id,
    memory_usage,
    formatReadableSize(memory_usage),
    query
FROM system.query_log
WHERE (event_date >= today()) AND (event_time >= (now() - 7200)) 
ORDER BY memory_usage DESC
LIMIT 100;
```

I have found that there are many tables that occupy more than 1GB of memory. I have queried 2 tables through SQL concatenation. Perhaps I should optimize SQL. Do you have any suggestions for this
```
select t1.xx, t1.xx2 from  test1 t1
                            left join t2 on t2.TargetId = t1.Id 
                            left join t3 on t3.SourceId  =t2.Id 
                            where t1.CorpId = 21994
```

**Comment by yimogit** [comment]
Although I did not adjust the configuration, I reduced the memory usage by adjusting the SQL connection queries, and all queries occupied less than 100MB of memory
