### ISSUE TITLE
DateTime64: strange range of values

### ISSUE THREAD

**Issue by vitalyisaev2** [ClickHouse/ClickHouse#52370]
On this [page](https://clickhouse.com/docs/en/sql-reference/data-types/datetime64 ) it is said that `DateTime64` represents `number of ‘ticks’ since epoch start (1970-01-01 00:00:00 UTC) as Int64. `  Also, the mentioned value range for precision `8` is `[1900-01-01 00:00:00, 2299-12-31 23:59:59.99999999]`.

And this is strange, because if we take year 1970 as a midpoint of the number line (zero ticks), the range could have started in year 1641. 

Are there any mistakes in the docs? If no, what is the reason of cropping possible range of values to year 1900?

**Comment by den-crane** [comment]
1970-01-01 https://en.wikipedia.org/wiki/Unix_time

DateTime before  1970-01-01 is stored as negative number of ticks.

This range is because this only this number of ticks fits to 64 bits.

see https://github.com/ClickHouse/ClickHouse/issues/38393
