### ISSUE TITLE
A new parameter to skip checks during mutations (space/parts size)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#5240]
A mutation never finishes for parts with size bigger than max_bytes_to_merge_at_max_space_in_pool

`select * from system.parts where bytes_on_disk > (select toInt64(value) from system.merge_tree_settings where name = 'max_bytes_to_merge_at_max_space_in_pool')`

In my case I had 2 parts with size 201Gb and max_bytes_to_merge_at_max_space_in_pool = 200Gb and mutation (delete) got stuck. The funniest part is that the mutation only needed to clone (hard-link) those parts (without modification).

So proposal: mutation_skip_checks = none / parts_size / free_space / all .

**Comment by alex-zaitsev** [comment]
Mutations should not be subject of max part size at all. Also see #5571 -- it should not be a subject of timeouts.

**Comment by den-crane** [comment]
fixed in https://github.com/ClickHouse/ClickHouse/pull/5659
