### ISSUE TITLE
Distributed engine should support (omit) indexes in [AS TABLE_NAME] syntax

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#5241]
```
CREATE TABLE test1  (A Int64, Index i A TYPE minmax GRANULARITY 3) ENGINE = MergeTree() ORDER BY tuple()

CREATE TABLE test1_d as test1 ENGINE = Distributed(test, currentDatabase(), test1, rand());

```
DB::Exception: Engine Distributed doesn't support PARTITION BY, PRIMARY KEY, ORDER BY or SAMPLE BY clauses and skipping indices. Currently only the MergeTree family of engines supports them.

The same for Merge Engine:
`CREATE TABLE test1_d as test1 ENGINE = MERGE (currentDatabase(),'^test1');`

DB::Exception:Engine MERGE doesn't support PARTITION BY, PRIMARY KEY, ORDER BY or SAMPLE BY clauses and skipping indices. Currently only the MergeTree family of engines supports them.

**Comment by nvartolomei** [comment]
I’d rather move indexes out of the columns definition. Similar to how partitioning, primary key are defined. No?

This is more like a bug and not a feature exception.

**Comment by den-crane** [comment]
> I’d rather move indexes out of the columns definition. Similar to how partitioning, primary key are defined. No?
> 
> This is more like a bug and not a feature request.

I agree and I really don't understand why indexes were placed in columns section and it broke backward compatibility for users with columns named index.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/6968

**Comment by alexey-milovidov** [comment]
@den-crane 
For two reasons:
- for consistency with other SQL dialects (example: https://dev.mysql.com/doc/refman/8.0/en/create-table.html) - they have INDEX and CONSTRAINT near columns;
- because there can be multiple indices.
