### ISSUE TITLE
How to efficiently materialize data into a table when a field is set with default_expression?

### ISSUE THREAD

**Issue by BarryAllen1993** [ClickHouse/ClickHouse#52434]
Our application scenario requires fast updates on a specific column, with data volume ranging from over 30 billion to even hundreds of billions. To achieve fast updates, our current approach involves synchronizing the required data column and associated keys to ClickHouse using Join Engine to create a table.

We then add a new field to the target table and set its default_expression as follows:

ALTER TABLE db.tab_1 ADD COLUMN col_new type DEFAULT joinGet(join_storage_table, `value_column`, join_keys);

After that, we change the field names using the following command:

ALTER TABLE db.tab_1
    RENAME COLUMN col TO col_old,
    RENAME COLUMN col_new TO col,
    DROP COLUMN col_old;

This way, the logical modification is completed almost instantly, and we can use the updated table. However, we are aware that the current value in col is obtained through joinGet from the join_storage_table. If the join_storage_table is deleted, col becomes unusable. Hence, we would like to inquire whether there is a method to efficiently materialize the data of this column into the table, without depending on join_storage_table.

thank

**Comment by den-crane** [comment]
options:

* `alter table  db.tab_1 update col = col where 1`
* `alter table  db.tab_1 materialize column col`

**Comment by BarryAllen1993** [comment]
Thank
