### ISSUE TITLE
Zookeeper time wait metric is too high.

### ISSUE THREAD

**Issue by LuPan92** [ClickHouse/ClickHouse#52447]
# environment
1. ClickHouse cluster infomation
clickhouse version ：22.08.14 LTS
clickhouse nodes：48
clickhouse shards：24
table infomation：3 tables(table engine: ReplicatedMergeTree), each table contains 155 fields, 2 partition fields
materialized view infomation：3 materialized views(ReplicatedSummingMergeTree)，Each materialized view contains 4 fields
, 2 partition fields
total parts：800k+
data size: 200TB

2. Zookeeper cluster infomation 
zookeeper version：3.4.14
zookeeper nodes：3
heap size: 6G
log data and snapshot data are stored separately

3. other  settings
   max_merge_selecting_sleep_ms: 30000
   Data writing using spark streaming

# grafana monitor metrics
![image](https://github.com/ClickHouse/ClickHouse/assets/118737616/1f869156-78aa-493f-916d-5f9b296ba832)
![image](https://github.com/ClickHouse/ClickHouse/assets/118737616/017dfb8d-1d4e-4495-bec8-53e98be22ab0)
![image](https://github.com/ClickHouse/ClickHouse/assets/118737616/eec42f81-56a3-4e3c-9515-7998110fdcd2)

 I read this issue(#43647) carefully. The problem I encountered is very similar to this one. Can I fix this by doing the following
Option One：
   1. Upgrade zookeeper version to 3.6 or use clickhouse keeper(But the clickhouse service needs to be restarted)
   2. Add some optimization to avoid listing block numbers in old/empty partitions when constructing ReplicatedMergeTreeMergePredicate.(Although I don't know exactly how to do it)

Option Two:
   1. Manually remove /table_path_in_zk/temp/abandonable_lock-insert and /table_path_in_zk/temp/abandonable_lock-other nodes from ZooKeeper for each table.

Option Three:
   1. Upgrade the clickhouse version(https://github.com/ClickHouse/ClickHouse/pull/49637 and https://github.com/ClickHouse/ClickHouse/pull/50107), but compatibility issues need to be considered.

**Comment by den-crane** [comment]
>max_merge_selecting_sleep_ms: 30000 

This setting did not exists with 22.08.14 .
Which CH version do you really use? `select version()`

**Comment by den-crane** [comment]
>Zookeeper time wait metric is too high

And what? Why do you bother? How does it really impact you?

**Comment by alexey-milovidov** [comment]
Upgrade ClickHouse to 23.6 and replace ZooKeeper with ClickHouse Keeper.

**Comment by LuPan92** [comment]
> > max_merge_selecting_sleep_ms: 30000
> 
> This setting did not exists with 22.08.14 . Which CH version do you really use? `select version()`
@den-crane  Use the following SQL statement to set
```
alter table xxx settings max_merge_selecting_sleep_ms=30000
```

**Comment by LuPan92** [comment]
> > Zookeeper time wait metric is too high
> 
> And what? Why do you bother? How does it really impact you?
@den-crane The time wait of zk is too high, which may cause replica synchronization failure
