### ISSUE TITLE
Multiple INNER JOIN performance advise needed

### ISSUE THREAD

**Issue by vfilatov** [ClickHouse/ClickHouse#52442]
I'm trying to execute a multiple join query that doesn't perform well.
Is there any recommendations on the tables structure or query itself?

Thanks

PS. Each table contains up to 300M records

```sql
CREATE TABLE t1
(
    `key` FixedString(36),
    `t2_key` FixedString(36),
    `value` FixedString(17)
)
ENGINE = MergeTree
ORDER BY key;

CREATE TABLE t2
(
    `key` FixedString(36),
    `t3_key` FixedString(36),
    `value` FixedString(17)
)
ENGINE = MergeTree
ORDER BY key;

CREATE TABLE t3
(
    `key` FixedString(36),
    `value` FixedString(17)
)
ENGINE = MergeTree
ORDER BY key;

SELECT t1.key, t1.value, t2.value, t3.value
  FROM t1
 INNER JOIN t2 ON t2.key = t1.t2_key
 INNER JOIN t3 ON t3.key = t2.t3_key
 WHERE t1.key IN (<key1>,<key2>,<keyN>) -- Edited!!!
;
Edit: Added `where` clause

**Comment by lampjian** [comment]
Try this if there is no repeated keys:
SELECT t1.key, t1.value, t2.value, t3.value
  FROM t1
 INNER ANY JOIN t2 ON t2.key = t1.t2_key
 INNER ANY JOIN t3 ON t3.key = t2.t3_key
 SETTINGS join_algorithm=parallel_hash
;

**Comment by lampjian** [comment]
Try this if there is no repeated keys:
```SQL
SELECT t1.key, t1.value, t2.value, t3.value
FROM t1
 INNER ANY JOIN t2 ON t2.key = t1.t2_key
 INNER ANY JOIN t3 ON t3.key = t2.t3_key
SETTINGS join_algorithm=parallel_hash
;
```

**Comment by vfilatov** [comment]
`join_algorithm=parallel_hash` makes the return ~2.5 times faster then `hash`, but it is too far away from being "perfect".
Each of individual queries (by key) come back in a split second while even one JOIN takes
```
1 row in set. Elapsed: 20.064 sec. Processed 107.79 million rows, 5.61 GB (5.37 million rows/s., 279.38 MB/s.)
```

**Comment by den-crane** [comment]
>Each of individual queries (by key) comes back in a split second while even one JOIN takes

Try to multiply `split second` to 300M.

**Comment by vfilatov** [comment]
> 

That number (0.01 sec * 300M) would be way bigger than 20 sec.
Of course the full scan is long, I hoped it could be optimized some how because each `key` is unique within the table.

**Comment by den-crane** [comment]
>That number (0.01 sec * 300M) would be way bigger than 20 sec.
>Of course the full scan is long, I hoped it could be optimized some how because each key is unique within the table.

There is possible algorithm which can produce better results in this case -- PureMergeJoin (Clickhouse does not have it), but it will be slightly better if you need only the first rows. If you need the whole result, all 300M rows, then 20 seconds almost the best possible result for a single machine.

**Comment by vfilatov** [comment]
Opps, didn't mention `WHERE` clause, my bad...
The actual query should be like:
```sql
SELECT t1.key, t1.value, t2.value, t3.value
  FROM t1
 INNER JOIN t2 ON t2.key = t1.t2_key
 INNER JOIN t3 ON t3.key = t2.t3_key
WHRE t1.key IN (<key1>,<key2>,<keyN>)
;

**Comment by den-crane** [comment]
```sql
SELECT t1.key, t1.value, t2.value, t3.value
  FROM t1
 INNER JOIN (select * from t2 where t2.key in (select t2_key from t1 where t1.key in (10000000161024441941, 10000000226776097053,10000000436763962859))) t2 ON t2.key = t1.t2_key
 INNER JOIN (select * from t3 where t3.key in (select t3_key from t2 where t2.key in (select t2_key from t1 where t1.key in (10000000161024441941, 10000000226776097053,10000000436763962859)))) t3 ON t3.key = t2.t3_key
where t1.key in (10000000161024441941, 10000000226776097053,10000000436763962859)
;

┌─t1.key───────────────┬─t1.value──┬─t2.value──┬─t3.value──┐
│ 10000000161024441941 │ 81743066  │ 81743066  │ 81743066  │
│ 10000000436763962859 │ 72027082  │ 72027082  │ 72027082  │
│ 10000000226776097053 │ 121305711 │ 121305711 │ 121305711 │
└──────────────────────┴───────────┴───────────┴───────────┘

3 rows in set. Elapsed: 0.026 sec. Processed 712.70 thousand rows, 40.66 MB (27.21 million rows/s., 1.55 GB/s.)
```

**Comment by den-crane** [comment]
@vdimir it seems grace_hash is unable to solve it, even with `grace_hash_join_initial_buckets=512, grace_hash_join_max_buckets=512`

```
set max_memory_usage='30G';

CREATE TABLE t1 (key String, t2_key String, value String)
ENGINE = MergeTree
ORDER BY key as select cityHash64(number), cityHash64(number+1), number
from numbers(300000000);


CREATE TABLE t2(key String, t3_key String, value String)
ENGINE = MergeTree
ORDER BY key as select cityHash64(number+1), cityHash64(number+3), number 
from numbers(300000000);

CREATE TABLE t3(key String, value String)
ENGINE = MergeTree
ORDER BY key as select cityHash64(number+3), number
from numbers(300000000);

SELECT t1.key, t1.value, t2.value, t3.value
  FROM t1
 INNER JOIN t2 ON t2.key = t1.t2_key
 INNER JOIN t3 ON t3.key = t2.t3_key
where t1.key in (10000000161024441941, 10000000226776097053,10000000436763962859);
settings join_algorithm='grace_hash', grace_hash_join_initial_buckets=512, grace_hash_join_max_buckets=512;

DB::Exception: Memory limit (for query) exceeded: would use 30.49 GiB (attempt to allocate chunk of 12887017127 
bytes), maximum: 27.94 GiB.: While executing FillingRightJoinSide. (MEMORY_LIMIT_EXCEEDED) (version 23.6.2.18
```

**Comment by vfilatov** [comment]
@den-crane thank you!
That workaround should work for my case.

**Comment by vdimir** [comment]
We should implement push down optimization for multiple joins like you did manually in the comment above. It's challenging with current implementation of multiple joins. Should be easier with new analyzer though.

**Comment by den-crane** [comment]
> We should implement push down optimization for multiple joins like you did manually in the comment above. It's challenging with current implementation of multiple joins. Should be easier with new analyzer though.
> 
> And also related #50532

It's very hard in general.
For this use-case I would implement NestedLoop (Direct join / pk index access).
