### ISSUE TITLE
DB::NetException: SSL Exception: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN, while reading from socket (192.168.xx.xx:xx). (NETWORK_ERROR)

### ISSUE THREAD

**Issue by hantaoliulinux** [ClickHouse/ClickHouse#52463]
My branch is 23.3.2.37, when I access by jdbc, I set ssl protocol this :

 SSLContext sslContext = SSLContext.getInstance("TLSv1.2");

The server keeps reporting this error：

<Error> ServerErrorHandler [Exception.cpp:193] : Code: 210. DB::NetException: SSL Exception: error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN, while reading from socket (192.168.XX.XX:xx). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(String const&, int) @ 0x15c7e4c0 in /bin/clickhouse
1. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xb457944 in /bin/clickhouse
2. DB::NetException::NetException<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @0x13fdf74c in /bin/clickhouse
3. DB::ReadBufferFromPocoSocket::nextImpl() @ 0x13fdf040 in /bin/clickhouse
4. DB::HTTPServerRequest::readRequest(DB::ReadBuffer&) @ 0x14f1aac8 in /bin/clickhouse
5. DB::HTTPServerRequest::HTTPServerRequest(std::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x14f1a3b8 in /bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x14f19638 in /bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x15b46f98 in /bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x15b47504 in /bin/clickhouse
9. Poco::PooledThread::run() @ 0x15ce0b18 in /bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x15cde5c4 in /bin/clickhouse
11. ? @ 0x87b0 in /usr/lib64/libpthread-2.28.so
12. ? @ 0xd518c in /usr/lib64/libc-2.28.so

**Comment by hantaoliulinux** [comment]
my config.xml about server_ssl like this :
![image](https://github.com/ClickHouse/ClickHouse/assets/39047544/c98620ae-970c-432f-b74e-8a992d4e6975)

The same configuration is in 22.3.2.2，my access is normal.  Maybe 23.3.2.37 is different from 22.3.2.2.

**Comment by alexey-milovidov** [comment]
If you are using a self-signed certificate or a private root CA, it has to be explicitly enabled on the client side.
