### ISSUE TITLE
Got /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found error when running clickhouse19.8.1.1 on Redhat7.4

### ISSUE THREAD

**Issue by kindred77** [ClickHouse/ClickHouse#5250]
I build clickhouse19.8.1.1 using source code on CentOS 7.6, and got error when run it on Redhat 7.4(product env):
./clickhouse_19.8: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./clickhouse_19.8)
./clickhouse_19.8: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./clickhouse_19.8)
./clickhouse_19.8: /lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./clickhouse_19.8)
./clickhouse_19.8: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./clickhouse_19.8)
./clickhouse_19.8: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./clickhouse_19.8)

I build it using Gcc7.3.0, Ninja 1.9.0.
But it runs well in 19.5.1.1 build with Gcc7.3.0 and Make.

In Redhat7.4, I run "strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX", I got:
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

when I runned "strings /usr/lib64/libstdc++.so.6 |  grep CXXABI ", output below:
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1

The same result in CentOS7.6.

Please give me a help.
thanks.

**Comment by alexey-milovidov** [comment]
Linking ClickHouse with shared libraries is discouraged and never can be considered for production usage.

**Comment by kindred77** [comment]
thanks for comment，but how could I close the shared libraries linking？

**Comment by kindred77** [comment]
thanks, I have fixed with CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++"

**Comment by shangshujie365** [comment]
@kindred77 you need change the soft link,  'ln -s libstdc++.so.6.0.24 /usr/lib64/libstdc++.so.6'
the libstdc++.so which centos provide is old.

btw, how you fix this problem? I set 'CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++"', but nothing changed

**Comment by alexey-milovidov** [comment]
If you are using shared linking (that is strongly discouraged), you cannot avoid this issue.
All production builds are made only with static linking.

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/8311
