### ISSUE TITLE
ALTER statement to support settings

### ISSUE THREAD

**Issue by blanklin030** [ClickHouse/ClickHouse#52505]
**How to reproduce**

```
ALTER TABLE db.tb REPLACE PARTITION 20230301 FROM db.tb_tmp SETTINGS lock_acquire_timeout = 86400000
```

**Expected behavior**

> The SETTINGS in the alter statement are not affect

**Error message and/or stacktrace**

> no error message, but settings cannot work

**Additional context**

> no any other context about the problem here.

**Comment by tavplubix** [comment]
It's already supported

**Comment by canhld94** [comment]
@tavplubix in some case ALTER doesn't support settings properly. For example, `ALTER mv MODIFY QUERY SELECT ... SETTINGS ...`, settings will be parsed as a part of SELECT query.

We should allow user to specify alter in the middle of the query as well, e.g. `ALTER DATABASE / TABLE / LIVE VIEW SETTINGS ... MODIFY ...`

**Comment by canhld94** [comment]
Otherwise running `ALTER mv MODIFY QUERY` with `ON CLUSTER` will be a nightmare if `allow_experimental_alter_materialized_view_structure` is not enabled by default.

**Comment by tavplubix** [comment]
> in some case ALTER doesn't support settings properly. For example, ALTER mv MODIFY QUERY SELECT ... SETTINGS ..., settings will be parsed as a part of SELECT query

Settings for `ALTER MODIFY QUERY` are parsed as expected. It is possible to specify settings for ALTER. See https://pastila.nl/?00b49041/b4b1d38a74f968c367aeb541d20f409c

> Otherwise running ALTER mv MODIFY QUERY with ON CLUSTER will be a nightmare if allow_experimental_alter_materialized_view_structure is not enabled by default.

I don't see any nightmares here, it works totally fine even without specifying `allow_experimental_alter_materialized_view_structure` in the ALTER query: https://pastila.nl/?03bc58ed/4b079f785d3f02340011a45eb81904d6
