### ISSUE TITLE
 Elements 'INTELLIGENCE.HASH' and 'INTELLIGENCE.OS' of Nested data structure 'INTELLIGENCE' (Array columns) have different array sizes.: While executing WaitForAsyncInsert. (SIZES_OF_ARRAYS_DONT_MATCH) (version 23.4.2.11 (official build))

### ISSUE THREAD

**Issue by DemoMoon** [ClickHouse/ClickHouse#52531]
The data structure I created

name─────────────────────────┬─type─────────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ id                           │ Int64            │              │                    │         │                  │                │
│ create_time_                 │ DateTime         │              │                    │         │                  │                │
│ update_time_                 │ DateTime         │              │                    │         │                  │                │
│ DETECTED                     │ Nullable(String) │              │                    │         │                  │                │
│ DOMAIN                       │ Array(String)    │              │                    │         │                  │                │
│ FILE_N                       │ Array(String)    │              │                    │         │                  │                │
│ IP                           │ Array(String)    │              │                    │         │                  │                │
│ URL                          │ Array(String)    │              │                    │         │                  │                │
│ VER                          │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.AGING_TIME              │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.MANAGE_TYPE             │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.REC_TIME                │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.REVIEW_STATUS           │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.SRC_TYPE                │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.STATUS                  │ Array(String)    │              │                    │         │                  │                │
│ HEAD.SYS_ID                  │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.TYPE                    │ Nullable(String) │              │                    │         │                  │                │
│ HEAD.UPDATE_TIME             │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.CONFIDENCE      │ Int16            │              │                    │         │                  │                │
│ INTELLIGENCE.DET_INFORMATION │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.FIRST_SEEN      │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.HASH            │ Array(String)    │              │                    │         │                  │                │
│ INTELLIGENCE.HASH_T          │ Array(String)    │              │                    │         │                  │                │
│ INTELLIGENCE.INTEL_TYPE      │ Array(String)    │              │                    │         │                  │                │
│ INTELLIGENCE.IOC             │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.MD5             │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.MOD_TIME        │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.OS              │ Array(String)    │              │                    │         │                  │                │
│ INTELLIGENCE.PERIOD_VALID    │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.SEVERITY        │ Nullable(String) │              │                    │         │                  │                │
│ INTELLIGENCE.SOURCE          │ Array(String)    │              │                    │         │                  │                │
│ INTELLIGENCE.SRC_ID          │ Nullable(String) │              │                    │         │                  │               

I didn't use the nested structure, why would I report this error? Is it the Clickhouse automatic conversion mechanism? How do I do it?

**Comment by DemoMoon** [comment]
{
	"DETECTED": "false",
	"DOMAIN": [],
	"FILE_N": ["e77265b6cbcfee5b3862f6c8f727c049"],
	"HEAD": {
		"AGING_TIME": "2024-07-22 00:02:05",
		"MANAGE_TYPE": "BASIC",
		"REC_TIME": "2023-07-23 00:02:05",
		"REVIEW_STATUS": "3",
		"SRC_TYPE": "SRC_OUT",
		"STATUS": ["1"],
		"SYS_ID": "0b15e3ff8353f6581b9417c4f9e10ee0",
		"TYPE": "THR_HASH",
		"UPDATE_TIME": "2023-07-23 00:02:05"
	},
	"INTELLIGENCE": {
		"CONFIDENCE": 97,
		"DET_INFORMATION": "威胁程度(高)",
		"FIRST_SEEN": "2023-07-23 00:02:05",
		"HASH": ["1"],
		"HASH_T": ["1"],
		"INTEL_TYPE": ["1"],
		"IOC": "e77265b6cbcfee5b3862f6c8f727c049",
		"LAST_SEEN": "2023-07-23 00:02:05",
		"MD5": "e77265b6cbcfee5b3862f6c8f727c049",
		"MOD_TIME": "2023-07-21 07:45:19",
		"OS": [],
		"PERIOD_VALID": 365,
		"SEVERITY": "suspicious",
		"SOURCE": ["1"],
		"SRC_ID": "e77265b6cbcfee5b3862f6c8f727c049"
	},
	"IP": [],
	"URL": [],
	"VER": "1.0"
}

**Comment by den-crane** [comment]
`NTELLIGENCE.HASH` ->>> `NTELLIGENCE_HASH`
