### ISSUE TITLE
Unable to query some tables anymore after a restart of the server/docker

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#52541]
**Describe the unexpected behaviour**
After restarting my Clickhouse instance on docker, two tables of mine (which have daily date partitions) have become unaccessible through normal select queries (even easy ones like select * from table limit 1). At first, when I restarted the docker I had: TOO_MANY_SIMULTANEOUS_QUERIES errors. Then, at the second restart, this error didn't show up (maybe because there was less load on the server, even though it is always pretty stable and high), and just the select on tables was not working. Note that I have tables which have monthly partitions and these have not encountered any problem. And I don't understand why the tables have become unaccessible even if the data is still there.

**How to reproduce**
* Which ClickHouse server version to use
22.6.9.11 (docker, official build)
Single instance, 128 GB RAM CPU

**Expected behavior**
As happened until today, the query should return the select results in approx 500ms. Instead, it goes into timeout (30secs).

**Error message and/or stacktrace**

**Additional context**

**Comment by enzorevo** [comment]
After 3 hours, I tried again to do a select and it worked, both on system.mutations and on the table that wasn't working. I'm pretty sure this is a bug, even though it's not easy to understand. I just want to know that it will not happen in the future because the resolution was... totally random, without doing anything. Has anyone any idea on why all this happened?

**Comment by alexey-milovidov** [comment]
Check the logs.

**Comment by enzorevo** [comment]
> Check the logs.

Hi Alex, I checked those (through: docker logs clickhouse_container) and nothing was showing in particular, both on startup and when I ran the queries (since they were just stuck without giving any error). Is there anything else I should check?
