### ISSUE TITLE
"Unknown identifier" with 2+ JOINs and not aliased column outside of selected list

### ISSUE THREAD

**Issue by koxt** [ClickHouse/ClickHouse#5254]
server version() = 19.5.3.8

**How to reproduce**

Test tables with data
```
CREATE TABLE test1
(
  id bigint,
  code text
)
engine = MergeTree
ORDER BY id
;

CREATE TABLE test2
(
  id bigint,
  code text,
  test1_id bigint,
  test3_id bigint
)
engine = MergeTree
ORDER BY id
;

CREATE TABLE test3
(
  id bigint,
  code text
)
engine = MergeTree
ORDER BY id
;

insert into test1 (id, code)
select top 100000 number, toString(number) FROM system.numbers;

insert into test2 (id, code, test1_id, test3_id)
select top 100000 number, toString(number), number, number FROM system.numbers;

insert into test3 (id, code)
select top 100000 number, toString(number) FROM system.numbers;
```

Test queries:
```
-- ok
select
    test2.id as c0
from
    test1
    join test2 on test2.test1_id = test1.id
--     join test3 on test2.test3_id = test3.id
where
    test1.code in ('1', '2', '3')
order by case when test1.code is null then 1 else 0 end
;

-- ok
select
    test2.id as c0
from
    test1
    join test2 on test2.test1_id = test1.id
    join test3 on test2.test3_id = test3.id
where
    test1.code in ('1', '2', '3')
--     order by case when test1.code is null then 1 else 0 end
;

-- fail
select
    test2.id as c0
from
    test1
    join test2 on test2.test1_id = test1.id
    join test3 on test2.test3_id = test3.id
where
    test1.code in ('1', '2', '3')
order by case when test1.code is null then 1 else 0 end
;
```
Exception message:
```
SELECT test2.id AS c0
FROM test1 
INNER JOIN test2 ON test2.test1_id = test1.id
INNER JOIN test3 ON test2.test3_id = test3.id
WHERE test1.code IN ('1', '2', '3')
ORDER BY multiIf(isNull(test1.code), 1, 0) ASC

Received exception from server (version 19.5.3):
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unknown identifier: test1.code, context: query: 'SELECT c0 FROM (SELECT * FROM test1  INNER JOIN test2 ON `--test2.test1_id` = `--test1.id`)  INNER JOIN test3 ON `--test2.test3_id` = id WHERE `--test1.code` IN ('1', '2', '3') ORDER BY multiIf(isNull(test1.code), 1, 0) ASC' required_names: '--test1.code''test1.code''id''c0''--test2.test3_id' source_tables: 'test3' table_aliases: complex_aliases: masked_columns: array_join_columns: source_columns: '--test1.code' 'c0' '--test2.test3_id' . 

0 rows in set. Elapsed: 0.004 sec. 
```

**Comment by 4ertus2** [comment]
The failed query uses complex function (multiIf(isNull(test1.code), 1, 0)) outside of select list that is not supported yet. You may try to place this statement into selected columns like this

```
SELECT test2.id AS c0, multiIf(isNull(test1.code), 1, 0) AS ord
FROM test1 
INNER JOIN test2 ON test2.test1_id = test1.id
INNER JOIN test3 ON test2.test3_id = test3.id
WHERE test1.code IN ('1', '2', '3')
ORDER BY ord ASC
```
and filter unneeded column 'ord' with external select.

P.S. It's actual not only for ORDER BY sections but for ON or WHERE section too. There's lot of cases where you have to name complex functions explicitly now.

**Comment by koxt** [comment]
It seems, that complex function is not the cause. Usage field name in ORDER BY is not supported either.
Only works with alias.
```
-- fail
select
    test2.id as c0
from
    test1
    join test2 on test2.test1_id = test1.id
    join test3 on test2.test3_id = test3.id
where
    test1.code in ('1', '2', '3')
order by test2.id
;

-- ok
select
    test2.id as c0
from
    test1
    join test2 on test2.test1_id = test1.id
    join test3 on test2.test3_id = test3.id
where
    test1.code in ('1', '2', '3')
order by c0
;
```

**Comment by Dinamitarh** [comment]
I have the same errors with joins

**Comment by Dinamitarh** [comment]
I upgrade cluster to 19.6.2.1 end my problem is fixed.

**Comment by koxt** [comment]
@Dinamitarh I upgraded server version to 19.6.2.1, but have the same failed tests.

**Comment by ocmajortom** [comment]
**I can confirm a problem with joins and alias in version 19.9.3:**

alias not used in group by, but underlying column:

```
SELECT test2.id AS c0
FROM test1 
INNER JOIN test2 ON test2.test1_id = test1.id
INNER JOIN test3 ON test2.test3_id = test3.id
GROUP BY test2.id

```
Received exception from server (version 19.9.3):
Code: 47. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Missing columns: 'test2.id' while processing query: 'SELECT c0 FROM (SELECT * FROM test1  INNER JOIN test2 ON `--test2.test1_id` = `--test1.id`)  INNER JOIN (SELECT * FROM test3 ) AS test3 ON `--test2.test3_id` = id GROUP BY test2.id', required columns: '--test2.test3_id' 'c0' 'test2.id' 'id', source columns: '--test2.test3_id' '--test2.test1_id' 'test2.code' '--test1.id' 'c0' 'code', joined columns: 'id' 'test3.code'. 

0 rows in set. Elapsed: 0.009 sec. 


**It works, when alias "c0" is used in group by:**

`select  test2.id as c0 from   test1  join test2 on test2.test1_id = test1.id  join test3 on test2.test3_id = test3.id  group by c0;`
...
Showed first 10000.

100000 rows in set. Elapsed: 0.298 sec. Processed 300.00 thousand rows, 4.00 MB (1.01 million rows/s., 13.41 MB/s.)
