### ISSUE TITLE
Support for Vector Search HNSW Index 

### ISSUE THREAD

**Issue by pavelnemirovsky** [ClickHouse/ClickHouse#52552]
Can someone clarify what version of Clickhouse is recommended to use HNSW (Hierarchical Navigable Small World) indices?

**Comment by UnamedRus** [comment]
It wasn't merged AFAIK https://github.com/ClickHouse/ClickHouse/pull/37007

**Comment by pavelnemirovsky** [comment]
@UnamedRus thx, any idea why it wasn't merged or just abandoned?

**Comment by rschu1ze** [comment]
> @UnamedRus thx, any idea why it wasn't merged or just abandoned?

It was one of many student projects which tried to integrate Approximate Neighborhood Search indexes into ClickHouse. There was no technical reason to abandon it, the only reason was that the student moved on and the PR got stuck at some point.

Interestingly, as I write this, an attempt to integrate [usearch](https://github.com/unum-cloud/usearch) which also implements HNSW is underway: https://github.com/ClickHouse/ClickHouse/pull/52603 With a bit of luck, we'll have an (experimental) HNWS-index in a few weeks from now.

**Comment by narayanacharya6** [comment]
Can this issue be kept open since #52603 was not merged?

**Comment by rschu1ze** [comment]
Reopened it, assigned myself.

**Comment by pavelnemirovsky** [comment]
@alexey-milovidov your help here is highly appreciated.

**Comment by alexey-milovidov** [comment]
HNSW is questionable because it requires in-memory storage, and its size is similar to the uncompressed data size.
It will require many additional customizations for real datasets (at least tens of billions of vectors).

**Comment by pavelnemirovsky** [comment]
@alexey-milovidov understood, thanks. BTW [Weaviate](https://weaviate.io/developers/weaviate/concepts/vector-index) say:

> HNSW is a very fast and memory efficient approach of similarity search, because only the highest layer (top layer) is kept in cache instead of all the datapoints in the lowest layer. Only the datapoints that are closest to the search query are loaded once they are requested by a higher layer, which means that only a small amount of memory needs to be reserved.

**Comment by rschu1ze** [comment]
> (#52603 was not intended to be merged, its only purpose was to help the usearch team getting started)

Just for reference, the follow-up by the usearch team: https://github.com/rschu1ze/ClickHouse/pull/1

**Comment by ashvardanian** [comment]
The [USearch](https://github.com/unum-cloud/usearch) guy here 😅

Seems like the core functionality is already in a working condition. Still we can always add more features and metrics. @pavelnemirovsky and @narayanacharya6, please don’t hesitate to reach out if you have any specific requests. Myself and @davvard will be happy to look into them 🤗
