### ISSUE TITLE
Error "Child process was stopped by signal 19" in clickhouse-server.err.log

### ISSUE THREAD

**Issue by BrianHu666** [ClickHouse/ClickHouse#52551]
I found that  the clickhouse server was down . Then i check clickhouse-server.err.log and found error 
 "Child process was stopped by signal 19" .
 I checked cpu and memory info of deploy clickhouse  ， it was not abnormal.
 What means of signal 19 ?

**Comment by BrianHu666** [comment]
<img width="644" alt="clickhouse-err" src="https://github.com/ClickHouse/ClickHouse/assets/107393344/f04e0d8e-179d-4c38-b561-5342bba9d784">

**Comment by tavplubix** [comment]
See https://man7.org/linux/man-pages/man7/signal.7.html

Signal 19 is SIGSTOP. It means that someone has sent SIGSTOP to clickhouse-server.

**Comment by BrianHu666** [comment]
> See https://man7.org/linux/man-pages/man7/signal.7.html
> 
> Signal 19 is SIGSTOP. It means that someone has sent SIGSTOP to clickhouse-server.

Got it . Thanks
