### ISSUE TITLE
Spontaneous disconnects from server side when using HTTP interface

### ISSUE THREAD

**Issue by scf37** [ClickHouse/ClickHouse#52571]
**Describe what's wrong**

Sometimes Clickhouse closes HTTP connection when request is in progress.

**Does it reproduce on recent release?**

We have issues on 23.3 and earlier versions for at least a year. Bug reproduction rate is low - we observe it like 20 times a day or like 1/1000 - 1/10_000 requests

**How to reproduce**
I strongly believe there is an issue with clickhouse HTTP Keep-Alive timeout - sometimes connection get closed by Keep-Alive timeout even it is not idle i.e. client is expecting HTTP response and did not receive it yet.

***Evidence***
- Client error always occurs when reading response body and never when writing request body
- We tried two completely different client implementations to the same effect
- https://github.com/ClickHouse/clickhouse-java/issues/290
- TCP dump shows no sign of RST both from the server and the client
- Error disappear when Clickhouse keep_alive_timeout is set to larger value than client Keep-Alive timeout i.e. client always closes connection before server Keep-Alive timeout happens

**Workaround**
Set keep_alive_timeout to 10 seconds and your HTTP client keep-alive timeout to lesser amout e.g. `-Djdk.httpclient.keepalive.timeout=9`

**Comment by den-crane** [comment]
>Sometimes Clickhouse closes HTTP connection when request is in progress.

Are you sure that it's in the middle of a request (fetching query result) ?

**Comment by den-crane** [comment]
I see this problem like this:

Client keepalive.timeout=9  / Server keepalive.timeout=9

1. Client successfully executes some query. 
2. Client http connection is idle for 8.999999 seconds.
3. Client checks "Am i ildle less than 9 seconds?" - I am. `8.999999<9.0`
4. Server closes http because 9 seconds pass.
5. Client sends a new request to Clickhouse server.
6. Server responses with disconnect.

**Comment by scf37** [comment]
a) re error - It is `channel closed` or `connection closed` (java) when reading HTTP response headers
b) re timeout race - we cached this issue when client keepalive.timeout is larger than  server keepalive.timeout, which is usually the case - Clickhouse keepalive timeout is only 10 seconds while clients keep keep-alive connections for much longer

**Comment by nickitat** [comment]
I don't think KA timeout could be seen as a commitment from the server. it is free to normally close connection at any time.

**Comment by scf37** [comment]
It looks like server KA timeout < client KA timeout is always problematic - it creates race condition when client starts to send new HTTP request and server simultaneously closes connection.

Can you consider increasing server KA timeout so less clients will stumble on that issue? For example nginx KA timeout defaults to 75 seconds because typical browser KA timeout is 60 seconds - see http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout

**Comment by alexey-milovidov** [comment]
@nickitat 

To clarify - is it true that the server can close the connection after keep-alive timeout while a query is still run and the client is waiting for the result?

This is not correct. Keep-alive timeout should only apply for the interval when the connection is idle.

**Comment by nickitat** [comment]
> query is still run and the client is waiting for the result

of course I didn't mean that. I was about the case Denny described. personally seen people complaining that connections getting closed before `timeout` seconds elapsed on the client side.

**Comment by nickitat** [comment]
as far as I see it has effect only here: https://github.com/ClickHouse/ClickHouse/blob/b79ead9c847b9cf5077145611a1c13b8c45daa5b/base/poco/Net/src/HTTPServerSession.cpp#L38-L52

and this function is called only in between requests:
https://github.com/ClickHouse/ClickHouse/blob/b79ead9c847b9cf5077145611a1c13b8c45daa5b/base/poco/Net/src/HTTPServerConnection.cpp#L57-L61

https://github.com/ClickHouse/ClickHouse/blob/b79ead9c847b9cf5077145611a1c13b8c45daa5b/src/Server/HTTP/HTTPServerConnection.cpp#L20-L25

as it should be

**Comment by huoarter** [comment]
> 我看到这个问题是这样的：
> 
> 客户端 keepalive.timeout=9 / 服务器 keepalive.timeout=9
> 
> 1. 客户端成功执行一些查询。
> 2. 客户端http连接空闲时间为8.999999秒。
> 3. 客户端检查“我闲置时间是否缺少9秒？” - 我是。`8.999999<9.0`
> 4. 由于9秒过去了，服务器关闭http。
> 5. 客户端向Clickhouse服务器发送新请求。
> 6. 服务器响应断开连接。



> I see this problem like this:
> 
> Client keepalive.timeout=9 / Server keepalive.timeout=9
> 
> 1. Client successfully executes some query.
> 2. Client http connection is idle for 8.999999 seconds.
> 3. Client checks "Am i ildle less than 9 seconds?" - I am. `8.999999<9.0`
> 4. Server closes http because 9 seconds pass.
> 5. Client sends a new request to Clickhouse server.
> 6. Server responses with disconnect.

how to resolve this problem rightly?
