### ISSUE TITLE
How to set PostgreSQL schema in `ExternalDistributed`

### ISSUE THREAD

**Issue by sananguliyev** [ClickHouse/ClickHouse#52573]
I am trying to use `ExternalDistributed` integration which accepts MySQL or PostgreSQL. Since PostgreSQL has schema, how we can define schema when we are using `ExternalDistributed` engine?

**Comment by lampjian** [comment]
Configure the postgresql default search_path settings with your schema is an option.

**Comment by lampjian** [comment]
Configure the postgresql default search_path settings with your schema or use the PostgreSQL table engine.

**Comment by sananguliyev** [comment]
Thanks
