### ISSUE TITLE
How to make the **volume_type** configuration take effect ? 

### ISSUE THREAD

**Issue by MattMH** [ClickHouse/ClickHouse#52570]
ClickHouse Version: 22.1.8.11
Question : 
I have read the docs.
https://clickhouse.com/docs/en/operations/system-tables/storage_policies
![image](https://github.com/ClickHouse/ClickHouse/assets/16539160/604edbae-718d-483c-83d0-1bf5d75a2526)

So I set my config like this:
<yandex>
````
    <storage_configuration>
        <disks>
            <default>
                <keep_free_space_bytes>1024</keep_free_space_bytes>
            </default>
            <disk1>
                <path>/srv/probe1/clickhouse/</path>
            </disk1>
            <disk2>
                <path>/srv/probe2/clickhouse/</path>
            </disk2>
        </disks>

        <policies>
            <test_jbod>
                <volumes>
                    <volume_name>
                        <disk>disk1</disk>
                        <disk>disk2</disk>
                    </volume_name>
                </volumes>
            </test_jbod>
            <test_single>
                <volumes>
                    <volume1>
                        <disk>disk1</disk>
                        <disk>disk2</disk>
                        <max_data_part_size_bytes>1073741824</max_data_part_size_bytes>
                        <volume_type>SINGLE_DISK</volume_type>
                    </volume1>
                </volumes>
            </test_single>
        </policies>
    </storage_configuration>
````
<yandex>

And I did a small test:
![image](https://github.com/ClickHouse/ClickHouse/assets/16539160/73207319-295a-4515-bacf-da13363e99e2)

I want to know how to make the **volume_type** configuration take effect ?

**Comment by UnamedRus** [comment]
It's being set automatically, you can't change it.

If you have >1 disk in volume it's JBOD

**Comment by MattMH** [comment]
> It's being set automatically, you can't change it.
> 
> If you have >1 disk in volume it's JBOD

I want to use only one directory at a time for an insert function.
For Example.
Insert into test_table SELECT * FROM numbers(10000000);
Insert into test_table SELECT * FROM numbers(10000001);

When I use single disk, It will generate 2 file directories with 2 parts
But when I use 2 disks 
Only one insert :
Insert into test_table SELECT * FROM numbers(10000000);
Which will generate 2 file directories in 2 disks.
Does clickhouse support 1 insert function (1 part) only generate 1 file directory, and write 2 directories in a loop when use 2 disks?

**Comment by UnamedRus** [comment]
> I want to use only one directory at a time for 1 insert function.

https://kb.altinity.com/altinity-kb-queries-and-syntax/atomic-insert/#insert-with-adjusted-settings-atomic

**Comment by MattMH** [comment]
Sorry, I made a mistake.
I use **INSERT INTO multTest SELECT * FROM numbers(10000003)**  do the test.
Actually this statement will generate many parts, so polling writes to multiple disks is reasonable and correct.
