### ISSUE TITLE
minmax indices are used to skip over data even if FINAL is used, leading to wrong results

### ISSUE THREAD

**Issue by untitaker** [ClickHouse/ClickHouse#52588]
**Describe the unexpected behaviour**

using `ReplacingMergeTree` in combination with minmax index and FINAL leads to wrong results until minmax index is either deleted, recreated or `OPTIMIZE TABLE` is run.

This is likely not a bug but another undocumented quirk similar to https://github.com/ClickHouse/ClickHouse/issues/23702 

**How to reproduce**

* use `clickhouse-server:21.6.1.6734`, it is probably an issue with other versions
* run following demo script (adjust `chcl` variable to point to correct clickhouse-client command)

```bash
#!/bin/sh

set -e
chcl="docker exec -i sentry_clickhouse clickhouse-client"
index="minmax_group_id group_id TYPE minmax GRANULARITY 1"

echo 'drop table if exists final_bug' | $chcl

echo 'create table final_bug (
    event_id String,
    group_id String,
    INDEX '"$index"'
)
ENGINE = ReplacingMergeTree
ORDER BY event_id
PARTITION BY event_id
SAMPLE BY event_id
' | $chcl

echo "insert into final_bug values ('bbb', 'B');" | $chcl
echo "insert into final_bug values ('aaa', 'A');" | $chcl

# merge B into A
echo "insert into final_bug select event_id, 'A' from final_bug where group_id = 'B';" | $chcl

# Since all rows of B were replaced with A, there should not be any rows with B
echo "vvv Should be 0"
echo "select count() from final_bug final where group_id = 'B';" | $chcl

# we have two ways to fix this inconsistency:

# Option 1: recreate (or just delete) the index
echo "alter table final_bug drop index minmax_group_id" | $chcl
echo "alter table final_bug add index $index" | $chcl

# Option 2: OPTIMIZE FINAL
# echo "optimize table final_bug final" | $chcl

# Now we will observe correct data
echo "vvv Should be 0"
echo "select count() from final_bug final where group_id = 'B';" | $chcl
```

**Expected behavior**

script prints `0` twice

**Error message and/or stacktrace**

script prints `1`, then `0`

**Comment by den-crane** [comment]
Modern versions don't use skip index for queries with FINAL.

There is a setting to control it

**Comment by den-crane** [comment]
And use https://fiddle.clickhouse.com/ please

**Comment by den-crane** [comment]
v22.2.1.2139-prestable.md:* Apply data skipping indexes for queries with FINAL may produce incorrect result. Disable data skipping indexes by default for queries with FINAL (introduce new `use_skip_indexes_if_final` setting and disable it by default). [#34243](https://github.com/ClickHouse/ClickHouse/pull/34243) ([Azat Khuzhin](https://github.com/azat)).

**Comment by AlexKichkailo** [comment]
@den-crane, @azat   Is my understanding correct, that if a skip index is created on a column that is part of the sort key,  then FROM FINAL will never produce incorrect results with `use_skip_indexes_if_final = 1`. If this is correct, then I assume ClickHouse could determine this automatically and only ignore skip indexes for columns that are not part of the sort key.

**Comment by azat** [comment]
Yes, that is correct. But such optimization does not exists yet.
