### ISSUE TITLE
My datetime64(3) has different results when inserting and updating

### ISSUE THREAD

**Issue by xxhZs** [ClickHouse/ClickHouse#52596]
I have a table like (v1Int32 , v2 DateTime64(3)). And I insert nanosecond/6，I can get a true datetime. But i update it, I need use nanosecond/9.
So Why should we set these two to look inconsistent

**Comment by lampjian** [comment]
It's not a good choice to use nanosecond, unix timestamp, "yyyy-MM-dd HH:mm:ss" formated date string or parsed DateTime type is OK.

**Comment by den-crane** [comment]
@xxhZs provide an example

**Comment by xxhZs** [comment]
> @xxhZs provide an example

for example. I create a table 
`create table t1(id Int32 , time DateTime64(9)) ENGINE = MergeTree
PRIMARY KEY (id)`
insert a datetime 
`insert into t1 values(1,1577840523000000000)`
i can get 
` 1 │ 2020-01-01 09:02:03.000000000`
And than I update it
`alter table t1 update time = 1577840523000000000 where id = 1`
I get an error
`DB::Exception: Decimal math overflow: While processing _CAST(if(id = 1, _CAST(1577840523000000000, 'DateTime64(9)'), time), 'DateTime64(9)').`
I think I use same nanosecond. But i get different results.

**Comment by qoega** [comment]
>I think I use same nanosecond

Why you think it is nanosecond? DateTime64 has 1.0 as a second. Nanosecond is 0.000000001.
So you just try to insert too large integer into a DateTime64(it works similar to https://clickhouse.com/docs/en/sql-reference/data-types/decimal). For 9 Decimal64 range is `Decimal64(S) = ( -1 * 10^(18 - S), 1 * 10^(18 - S) )`. Your number is larger
