### ISSUE TITLE
how many do "with clause" will execute times?

### ISSUE THREAD

**Issue by SuperEdison** [ClickHouse/ClickHouse#52595]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

```
with view_1 as (select * from xxx)
,view_2 as (select * from view_1 where ***)
,view_3 as (select * from view_1 where ***)
select * from view_1 global join view_2 on *** global join view_3 on ***
```
how many do "view_1" will execute times?

**Comment by lampjian** [comment]
Obviously, 3 query times I think. Generally CTE tables resident in memory.

**Comment by cangyin** [comment]
@SuperEdison I think optimizing the SQL should be much easier.

**Comment by UnamedRus** [comment]
Related https://github.com/ClickHouse/ClickHouse/issues/21992

There is no MATERIALIZE CTE trait in ClickHouse

**Comment by lampjian** [comment]
> can it optimize the times?

Use less alike CET with self join.
```SQL
WITH view_1 AS (SELECT * FROM xxx)
SELECT * FROM view_1 t1
  GLOBAL JOIN view_1 t2 ON ***
  GLOBAL JOIN view_1 t3 ON ***
WHERE view_2_conditions AND view_3_conditions
```

**Comment by UnamedRus** [comment]
Why not use window functions instead

**Comment by den-crane** [comment]
No materialization for CTE. Somewhere we had FR about it.
