### ISSUE TITLE
NOT() is expanding incorrectly

### ISSUE THREAD

**Issue by bgrgndzz** [ClickHouse/ClickHouse#52642]
Run `SELECT NOT(0) * 0`.

Expected result is 0, while returned result is 1. The query is parsed as `not(multiply(0, 0))`, which is incorrect.

* Which ClickHouse server version to use
23.6.1.1524
* Which interface to use, if matters
clickhouse-client

**Comment by alexey-milovidov** [comment]
NOT is an operator, not a function.
Similarly to AND, OR, it has a lower priority than arithmetic operators.
See it as:

```
NOT (0) * 0
```

But we can introduce function NOT to avoid this ambiguity.

**Comment by alexey-milovidov** [comment]
Changed the category from "potential bug" to "a request for enhancement".

**Comment by alexey-milovidov** [comment]
MySQL also returns 1: https://www.db-fiddle.com/f/jSeaY3JtyDEmvyZcdspgkq/0
Postgres does not work: https://www.db-fiddle.com/f/cnzXexPXn8jYZcgWAv9BJB/0

**Comment by evillique** [comment]
As a workaround, you can always use parentheses like this:
```
SELECT (NOT 0) * 0
```
