### ISSUE TITLE
MaterializedView doesn't support dynamic subcolumns

### ISSUE THREAD

**Issue by jkbitcaster** [ClickHouse/ClickHouse#52649]
I tried to create a materilized view. The view is getting data from kafka and wanted to insert those into a table. 

CREATE TABLE default.users
(
    `_id` String,
    `name` String,
    `updated_at` DateTime64(3),
    `json` String
)
ENGINE = ReplacingMergeTree(updated_at)
PRIMARY KEY _id
ORDER BY _id
SETTINGS index_granularity = 8192;

set allow_experimental_object_type = 1;
CREATE MATERIALIZED VIEW kafka.mv_users TO default.users
(
     `_id` String,
     `name` String,
     `updated_at` DateTime64(3),
     `json` JSON
) AS
    SELECT
    _id,
    name,
    parseDateTime64BestEffort(updated_at) AS updated_at,
    metrics as json
    FROM kafka.topics_users;

 version(): │ 23.3.8.22.altinitystable

Error Message:
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create table with column of type Object, because storage MaterializedView doesn't support dynamic subcolumns. (ILLEGAL_COLUMN)

**Comment by den-crane** [comment]
JSON is experimental and is not supported 

23.3.8.22.altinitystable Altinity builds are not supported.
