### ISSUE TITLE
How can i insert geo Types with nodejs?

### ISSUE THREAD

**Issue by dythbj** [ClickHouse/ClickHouse#52646]
**1).I created a table**
CREATE TABLE IF NOT EXISTS assess_set
                (bId String,  geometry MultiPolygon)
                ENGINE = MergeTree()
                ORDER BY (bId)

**2). I insert a row with Node(@clickhouse/client  0.2.0)**
const { createClient } = require('@clickhouse/client');

const client = createClient({
    host: "http://localhost:8123"
});

client.insert({
		table: 'assess_set',
		values: [
			{
			    "bId" : "1101140070001162002317",
			    "geometry" : {
			        "type" : "Polygon",
			        "coordinates" : [ 
			            [ 
			                [ 
			                    116.380189011524, 
			                    40.0814315330276
			                ], 
			                [ 
			                    116.380178978049, 
			                    40.0814775386023
			                ], 
			                [ 
			                    116.380307230998, 
			                    40.0815015711585
			                ], 
			                [ 
			                    116.380311630621, 
			                    40.0814520260214
			                ], 
			                [ 
			                    116.380319681131, 
			                    40.081452256036
			                ], 
			                [ 
			                    116.380318769004, 
			                    40.0814729652781
			                ], 
			                [ 
			                    116.380354460919, 
			                    40.0814743929548
			                ], 
			                [ 
			                    116.380360051066, 
			                    40.0813635306939
			                ], 
			                [ 
			                    116.38035862339, 
			                    40.0813392601915
			                ], 
			                [ 
			                    116.380291522589, 
			                    40.0813399740299
			                ], 
			                [ 
			                    116.380209431185, 
			                    40.0813264111022
			                ], 
			                [ 
			                    116.380214428053, 
			                    40.0812864361574
			                ], 
			                [ 
			                    116.380155893312, 
			                    40.0812792977742
			                ], 
			                [ 
			                    116.380155787913, 
			                    40.0812799960422
			                ], 
			                [ 
			                    116.380093075541, 
			                    40.0812707317145
			                ], 
			                [ 
			                    116.380088792512, 
			                    40.0813049959531
			                ], 
			                [ 
			                    116.38000955646, 
			                    40.0812964298934
			                ], 
			                [ 
			                    116.380015981005, 
			                    40.0812635933315
			                ], 
			                [ 
			                    116.379958873941, 
			                    40.0812543134336
			                ], 
			                [ 
			                    116.379952449396, 
			                    40.0812892915105
			                ], 
			                [ 
			                    116.379895342332, 
			                    40.081283580804
			                ], 
			                [ 
			                    116.379873213344, 
			                    40.0812928607019
			                ], 
			                [ 
			                    116.379861078093, 
			                    40.0813728105916
			                ], 
			                [ 
			                    116.379987427473, 
			                    40.0813799489748
			                ], 
			                [ 
			                    116.379983054086, 
			                    40.0813996368564
			                ], 
			                [ 
			                    116.380053814435, 
			                    40.0814106440217
			                ], 
			                [ 
			                    116.380056083948, 
			                    40.0813928041218
			                ], 
			                [ 
			                    116.380166132676, 
			                    40.0814064968205
			                ], 
			                [ 
			                    116.380162317857, 
			                    40.0814277761411
			                ], 
			                [ 
			                    116.380189011524, 
			                    40.0814315330276
			                ]
			            ]
			        ]
			    }
			}
		],
		format: 'JSONEachRow'
	});

**3). ClickHouseError: Array does not start with '[' character: (while reading the value of key geometry)**

So, How can i insert geo Types with nodejs?

**Comment by dythbj** [comment]
> You can reference the [clickhouse geo data types](https://clickhouse.com/docs/en/sql-reference/data-types/geo).

Thanks @lampjian ,I have look into it(https://clickhouse.com/docs/en/sql-reference/data-types/geo), but my doubt is - How to organize geodata's structure in nodejs, that clickhouse can convert it to [Tuple](https://clickhouse.com/docs/en/sql-reference/data-types/tuple).
We use geojson as a standard data structure in nodejs, as i mentioned above, ClickHouseError: Array does not start with '[' character: (while reading the value of key geometry), it can't do the conversion directly.
So, What kind of spatial data structure, can clickhouse deal with in nodejs?Thanks again!

**Comment by slvrtrn** [comment]
@dythbj, I just randomly stumbled upon this issue. You can check how it is done in the tests: https://github.com/ClickHouse/clickhouse-js/blob/main/packages/client-common/__tests__/integration/data_types.test.ts#L452-L505
I'll also add Geo examples to the project.
If you have more questions or findings, please open an issue in [the JS client repository](https://github.com/ClickHouse/clickhouse-js/tree/main) so it is more visible.
