### ISSUE TITLE
How to set default P and S for decimal

### ISSUE THREAD

**Issue by sananguliyev** [ClickHouse/ClickHouse#52663]
I am trying to create table as select without defining table columns because it's dynamic functionality. When I execute the SELECT it return normal decimal result, but when I create a table it uses `Decimal(38, 0)` 

Is there any way to set that if it's floating number use e.g. Decimal(38, 8) ?

**Comment by sananguliyev** [comment]
I tested that after I post this question. I'm curious why it's not working automatically since 0 fraction means integer (almost)

**Comment by UnamedRus** [comment]
Because it's kinda according to SQL standard 

https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL

```
without any precision or scale creates an “unconstrained numeric” column in which numeric values of any length can be stored, up to the implementation limits. A column of this kind will not coerce input values to any particular scale, whereas numeric columns with a declared scale will coerce input values to that scale. (The SQL standard requires a default scale of 0, i.e., coercion to integer precision. We find this a bit useless. If you're concerned about portability, always specify the precision and scale explicitly.)
```

**Comment by sananguliyev** [comment]
I got the point why it's 0 when we do not define something specific. What I did not get is it's `create table as`  reads the source table schema, and it specifically has decimal setting. I am not using `create table as` and implemented same functionality manually and set decimal point as it's from source table.
