### ISSUE TITLE
(in foreign language) Kafka ENGINE unexpected behaviour

### ISSUE THREAD

**Issue by padrebolt** [ClickHouse/ClickHouse#52697]
> You have to provide the following information whenever possible.

Топик, **другой**, разработчики заполнили, условно, мусором.
КХ падает по SIGSEGV. По 100-200-300к записей в секунду в эти два, с другими проблем не видел, но не искал специально. На 23.6. пока все лежало с 23.4 перевел, там то же самое, могу подять логи.

 (version 23.6.2.18 (official build))
2023.07.27 17:54:49.744490 [ 1324618 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): Code: 241. DB::Exception: Memory limit (total) exceeded: would use 2.00 EiB (attempt to allocate chunk of 4227072 bytes), maximum: 188.22 GiB.: while parsing Kafka message (topic: ranap, partition: 2, offset: 28471873661)': While executing Kafka. (MEMORY_LIMIT_EXCEEDED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e22b5f5 in /usr/bin/clickhouse
1. ? @ 0x000000000e237eb1 in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x000000000e23799b in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0x000000000e2372e9 in /usr/bin/clickhouse
4. CurrentMemoryTracker::realloc(long, long) @ 0x000000000e1fc1af in /usr/bin/clickhouse
5. Allocator<false, false>::realloc(void*, unsigned long, unsigned long, unsigned long) @ 0x00000000081d54c7 in /usr/bin/clickhouse
6. ? @ 0x0000000008881b0d in /usr/bin/clickhouse
7. DB::ColumnVector<int>::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long) @ 0x000000001400bc37 in /usr/bin/clickhouse
8. DB::StreamingFormatExecutor::execute() @ 0x0000000014cdd023 in /usr/bin/clickhouse
9. DB::KafkaSource::generateImpl() @ 0x00000000144f921f in /usr/bin/clickhouse
10. DB::KafkaSource::generate() @ 0x00000000144fc7ef in /usr/bin/clickhouse
11. DB::ISource::tryGenerate() @ 0x0000000014cbb855 in /usr/bin/clickhouse
12. DB::ISource::work() @ 0x0000000014cbb3a6 in /usr/bin/clickhouse
13. DB::ExecutionThreadContext::executeTask() @ 0x0000000014cd2ba9 in /usr/bin/clickhouse
14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000014cc9870 in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x0000000014cc8d90 in /usr/bin/clickhouse
16. DB::PipelineExecutor::execute(unsigned long) @ 0x0000000014cc8a31 in /usr/bin/clickhouse
17. DB::CompletedPipelineExecutor::execute() @ 0x0000000014cc733d in /usr/bin/clickhouse
18. DB::StorageKafka::streamToViews() @ 0x00000000144ebf2b in /usr/bin/clickhouse
19. DB::StorageKafka::threadFunc(unsigned long) @ 0x00000000144e9f4a in /usr/bin/clickhouse
20. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x00000000129ff2c2 in /usr/bin/clickhouse
21. DB::BackgroundSchedulePool::threadFunction() @ 0x0000000012a027ea in /usr/bin/clickhouse
22. ? @ 0x0000000012a0362e in /usr/bin/clickhouse
23. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e300c74 in /usr/bin/clickhouse
24. ? @ 0x000000000e306481 in /usr/bin/clickhouse
25. start_thread @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
26. __clone @ 0x00000000000feb2d in /usr/lib64/libc-2.17.so
 (version 23.6.2.18 (official build))

> A clear and concise description of what works not as it is supposed to.

Уменьшить аппетиты аллокатора. Ввести прогнозный отказ выделения памяти.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**YES**

Тестовый байт-блок из кафки и schema-registry привести не получится (

**Comment by padrebolt** [comment]
Да, по оффсетам и партициям можно вычитать сообщение, оно нормально парсится. Т.е. проблема именно в мусоре в другом топике.

**Comment by ilejn** [comment]
@padrebolt , the stacktrace probably indicates a memory corruption or something similar.
To find out what happened we need additional information. Data to send and kafka table DDL seem a good start.

**Comment by padrebolt** [comment]
> @padrebolt , the stacktrace probably indicates a memory corruption or something similar. To find out what happened we need additional information. Data to send and kafka table DDL seem a good start.

Unfortunately data can't be provided of cause of regualtions.
I can suggest some things:
1. topic: ranap, partition: 2, offset: 28471873661 was correctly accepted after (or may be in time) the incident
2. the root of problem is trash in another topic
3. some messages were going to accept, but the end was identical - SIGSEGV. 1-2 seconds after main process start
4. have seen shift of strings in messages
My assumption is broken length of string in AVRO, so we can see 2.00 EiB in malloc )))
