### ISSUE TITLE
Timeout exceeded while reading from socket 

### ISSUE THREAD

**Issue by emmanuelm41** [ClickHouse/ClickHouse#52694]
We have a clickhouse custer on k8s with three shards and one replica per shard. After ingesting data for a three days by using a Distributed table, we get a lot of files that need to be sent to their corresponding shard (by using the shading key). The workers start to do it, but in some moment it gets stuck with the following error. I don't really find the reason was the database is actually working (connection between shards is ok).

I am not actually sure if this is a bug or not, but it feels like that. 

```
Code: 209. DB::NetException: Timeout exceeded while reading from socket (10.42.11.186:9000, 300000 ms): while receiving packet from clickhouse-green-shard1-0.clickhouse-green-headless.db-clickhouse-green.svc.cluster.local:9000: While sending /bitnami/clickhouse/data/store/f03/f0348f81-712b-4625-8925-5deb4c063173/shard2_replica1/646521.bin. (SOCKET_TIMEOUT) (version 23.4.2.11 (official build))
```

```
2023.07.27 18:20:00.991041 [ 152 ] {} <Error> mainnet.transactions_canonical.DirectoryMonitor.default: 
Code: 209. DB::NetException: Timeout exceeded while reading from socket (10.42.11.186:9000, 300000 ms): while receiving packet from clickhouse-green-shard1-0.clickhouse-green-headless.db-clickhouse-green.svc.cluster.local:9000: While sending /bitnami/clickhouse/data/store/f03/f0348f81-712b-4625-8925-5deb4c063173/shard2_replica1/646521.bin. (SOCKET_TIMEOUT), 
Stack trace (when copying this message, always include the lines below): 
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /opt/bitnami/clickhouse/bin/clickhouse
1. ? @ 0x139957ed in /opt/bitnami/clickhouse/bin/clickhouse
2. DB::ReadBufferFromPocoSocket::nextImpl() @ 0x139953b1 in /opt/bitnami/clickhouse/bin/clickhouse
3. ? @ 0xe40b113 in /opt/bitnami/clickhouse/bin/clickhouse
4. DB::Connection::receivePacket() @ 0x14bf4c07 in /opt/bitnami/clickhouse/bin/clickhouse
5. DB::RemoteInserter::onFinish() @ 0x1470c6f5 in /opt/bitnami/clickhouse/bin/clickhouse
6. DB::DistributedAsyncInsertDirectoryQueue::processFile(String const&) @ 0x14706f61 in /opt/bitnami/clickhouse/bin/clickhouse
7. DB::DistributedAsyncInsertDirectoryQueue::processFiles() @ 0x14700089 in /opt/bitnami/clickhouse/bin/clickhouse
8. DB::DistributedAsyncInsertDirectoryQueue::run() @ 0x14700638 in /opt/bitnami/clickhouse/bin/clickhouse
9. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12a9d186 in /opt/bitnami/clickhouse/bin/clickhouse
10. DB::BackgroundSchedulePool::threadFunction() @ 0x12aa05ea in /opt/bitnami/clickhouse/bin/clickhouse
11. ? @ 0x12aa142e in /opt/bitnami/clickhouse/bin/clickhouse
12. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe48c2a1 in /opt/bitnami/clickhouse/bin/clickhouse
13. ? @ 0xe491b21 in /opt/bitnami/clickhouse/bin/clickhouse
14. start_thread @ 0x7ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
15. clone @ 0xfba2f in /lib/x86_64-linux-gnu/libc-2.31.so (version 23.4.2.11 (official build))
```

I am happy to share any additional information to solve this.

**Comment by emmanuelm41** [comment]
Just in case other ones find have this issue, we were forced to restart the cluster, and the distribution process started again.

**Comment by emmanuelm41** [comment]
Some time after restarting the cluster, we are again stuck with the same file. 

`
Code: 209. DB::NetException: Timeout exceeded while reading from socket (10.42.11.199:9000, 300000 ms): while receiving packet from clickhouse-green-shard1-0.clickhouse-green-headless.db-clickhouse-green.svc.cluster.local:9000: While sending /bitnami/clickhouse/data/store/f03/f0348f81-712b-4625-8925-5deb4c063173/shard2_replica1/646521.bin. (SOCKET_TIMEOUT) (version 23.4.2.11 (official build))
`

It seems something is wrong with that part, but there is no way to check what is happening.

**Comment by emmanuelm41** [comment]
Apparently, that file is a really bigger than other ones. Shards are on the same DC, really close to each other. Speed should be enough to process it. Is it possible to increase the timeout? 

![image](https://github.com/ClickHouse/ClickHouse/assets/10941036/9fcf3a21-4431-446a-a1a5-6bae03d45fc5)

**Comment by emmanuelm41** [comment]
Any comments? The distribution process is stuck, and now parts are growing and growing. It starts to feel like a bug more than an expected behavior. If this continues, parts to distribute could grow indefinitely.

**Comment by cangyin** [comment]
I found a setting that seems related:
https://clickhouse.com/docs/en/operations/settings/settings#distributed_directory_monitor_split_batch_on_failure

**Comment by emmanuelm41** [comment]
@cangyin thanks for your answer. That flag is enabled. We were not using it on previous iterations, but I enabled it in order to test if the issue would be solved. Unfortunately, it was not. 

```
create table mainnet.transactions_canonical on cluster default
as mainnet.transactions_canonical_local
engine = Distributed('default', 'mainnet', 'transactions_canonical_local', height % 3)
SETTINGS
    monitor_batch_inserts=1,
    monitor_split_batch_on_failure=1;
```

**Comment by cangyin** [comment]
I think there is some little bug here:

https://github.com/ClickHouse/ClickHouse/blob/c3c41253281bd3fb7f9209ac9bb4482db6597d6f/src/Storages/StorageDistributed.cpp#L1653-L1654


the storage settings `monitor_split_batch_on_failure` will always be false, if the sesttings `distributed_directory_monitor_split_batch_on_failure` is unchanged.

so change the settings (in `users.xml`) `distributed_directory_monitor_split_batch_on_failure` directly.

**Comment by emmanuelm41** [comment]
It could be possible. However, the error I reported is bigger than this flag. The process get stuck with individual files too, not just on batch processing.

**Comment by azat** [comment]
Let's close this in favor of https://github.com/ClickHouse/ClickHouse/issues/53236
