### ISSUE TITLE
Inserting data into nested entity

### ISSUE THREAD

**Issue by vinith-reddy25** [ClickHouse/ClickHouse#52715]
I used "flatten_nested" = 0

Then, created a table with below command
```
CREATE TABLE test.testing (
    id Int32,
    
category Nested (
        id Int32,
        name Array(String)
    ),

    name String
) ENGINE = MergeTree ORDER BY id;
```

Then inserting data into clickhouse using 2 below commands:

```
INSERT INTO test.testing (id, category, name)
VALUES (
    1236,
     [(NULL,['string'])],
    'style'
);
```

or

```
INSERT INTO test.testing (id, category, name)
VALUES (
    1236,
     [(,['string'])],
    'style'
);
```

data inserted is:

`
id | 1236
[{"id":0,"name":["string"]}]
style
`

Why is category.id is "0". I want it to be empty.
like

`
id | 1236
[{"name":["string"]}]
style
`

How to do that?

**Comment by cangyin** [comment]
[Nullable](https://clickhouse.com/docs/en/sql-reference/data-types/nullable)

https://fiddle.clickhouse.com/265716dc-200b-4675-a46a-76f8ce617a0c

**Comment by cangyin** [comment]
I think what you need is [Nullable](https://clickhouse.com/docs/en/sql-reference/data-types/nullable)

**Comment by den-crane** [comment]
`name Array(Nullable(String))`
