### ISSUE TITLE
Replication queue ATTACH_PART accumulate overtime

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#52714]
Recently we found the entries in replication queue grow constantly, and most of them are of type `ATTACH_PART`.

I took a look a the code and found the `ReplicatedMergeTree` are using common pool to process `ATTACH_PART` entry.  I think this is kind of unexpected, because `ATTACH_PART` and `GET_PART` are similar, so shouldn't they both use the fetch pool?
cc @nikitamikhaylov 

https://github.com/ClickHouse/ClickHouse/blob/9448d42aea6c5befae09cc923570fd6575a6d6f8/src/Storages/StorageReplicatedMergeTree.cpp#L3314

**Comment by canhld94** [comment]
Also cc @tavplubix

**Comment by canhld94** [comment]
Also related #43816

**Comment by UnamedRus** [comment]
Interesting enough, ATTACH and GET part being checked here together against fetch pool

https://github.com/ClickHouse/ClickHouse/blob/e2bc8b247871d828d1331d4b51cf076d5d9e504c/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp#L1326

It also lead to this nasty issue
https://github.com/ClickHouse/ClickHouse/issues/36322
