### ISSUE TITLE
The logger path is incorrect

### ISSUE THREAD

**Issue by helifu** [ClickHouse/ClickHouse#52722]
There will be two `logs` path for logger if the configuration is relative path.

1. logger configuration:

```
<clickhouse>
  <logger>
    <level>information</level>
    <log>./logs/clickhouse-server.log</log>
    <errorlog_level>error</errorlog_level>
    <errorlog>./logs/clickhouse-server.err.log</errorlog>
    <size>100M</size>
    <count>10</count>
  </logger>
</clickhouse>
```

2.the logger path:

```
hzhelifu@olap-test7:~/clickhouse-install$ ls logs
logs
hzhelifu@olap-test7:~/clickhouse-install$ ls logs/logs
clickhouse-server.err.log  clickhouse-server.log
```

**Comment by helifu** [comment]
Seems the function [replace_filename](https://github.com/ClickHouse/ClickHouse/blob/22e5da914c739f425f70b9247c3c22f96e49de5b/src/Loggers/Loggers.cpp#L44C19-L44C19) triggers this bug.

**Comment by lampjian** [comment]
You needn't add a relative "logs" path again, the root of the log directory already is logs.
