### ISSUE TITLE
MySQL connection password leaked in SHOW CREATE TABLE query

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#52723]
**Describe the unexpected behaviour**

CH masks the user instead of the password.

<img width="990" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/22796953/79eda9b9-42cc-4bb8-b307-afa83130d7f6">

To reproduce:

- Create a MySQL database
- Create a MySQL table inside the MySQL database
- Run SHOW CREATE TABLE

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/45023

**Comment by den-crane** [comment]
AFAIK it was fixed 9 months ago

**Comment by canhld94** [comment]
@den-crane I can reproduce it locally with mariadb and CH 23.6, will reopen this.

<img width="1112" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/22796953/ad0c7961-4f82-4040-98ff-dda5d6e1fc14">
