### ISSUE TITLE
MV & replicated deduplication 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#5274]
When I upload unique rows they are deduplicated because MV query calculates them into the same rows.

```
CREATE TABLE testNull (date Date,id String) ENGINE = Null;

CREATE TABLE testNoAggregate (date Date, id String) ENGINE = MergeTree order by date;
CREATE MATERIALIZED VIEW testNoAggregate_mv TO testNoAggregate AS SELECT date, id FROM testNull;

CREATE TABLE testAggregateNoReplicate (date Date, mcount AggregateFunction(count)) ENGINE = AggregatingMergeTree order by date;
CREATE MATERIALIZED VIEW testAggregateNoReplicate_mv to testAggregateNoReplicate AS SELECT date, countState() mcount FROM testNull GROUP BY date;

CREATE TABLE testAggregateReplicate (date Date, mcount AggregateFunction(count)) 
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/testCH/tables/testAggregateReplicate','1') order by date;
CREATE MATERIALIZED VIEW testAggregateReplicate_mv to testAggregateReplicate AS SELECT date, countState() mcount FROM testNull GROUP BY date;
```

All rows are unique in both files (number & number+2000000)
```
clickhouse-client -q 'select today()+number%3, number from numbers(1000000) format CSV' > test1.csv
clickhouse-client -q 'select today()+number%3, number+2000000 from numbers(1000000) format CSV' > test2.csv
cat test1.csv|clickhouse-client -q 'insert into testNull format CSV'
cat test2.csv|clickhouse-client -q 'insert into testNull format CSV'
```

```
SELECT date, count() FROM testNoAggregate GROUP BY date;
┌───────date─┬─count()─┐
│ 2019-05-14 │  666668 │
│ 2019-05-15 │  666666 │
│ 2019-05-16 │  666666 │
└────────────┴─────────┘
SELECT date, countMerge(mcount) FROM testAggregateNoReplicate GROUP BY date;
┌───────date─┬─countMerge(mcount)─┐
│ 2019-05-14 │             666668 │
│ 2019-05-15 │             666666 │
│ 2019-05-16 │             666666 │
└────────────┴────────────────────┘
SELECT date, countMerge(mcount) FROM testAggregateReplicate GROUP BY date;
┌───────date─┬─countMerge(mcount)─┐
│ 2019-05-14 │             333334 │
│ 2019-05-15 │             333333 │
│ 2019-05-16 │             333333 │
└────────────┴────────────────────┘
```

```
<Information> dw.testAggregateReplicate (Replicated OutputStream): Block with ID 
all_11219202931209068713_6683004147280658859 already exists; ignoring it.
```

I don't know a good general solution for this issue. 
The only idea is to set insert_deduplication=0 during pushing to MV (somewhere internally).

I think we have several opened tickets (puzzles) about this issue (people think that MV looses data or do discrepancy).

**Comment by den-crane** [comment]
CREATE TABLE testAggregateReplicate 
(date Date, mcount AggregateFunction(count), **workaround DateTime**)
ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/testCH/tables/testAggregateReplicate','1') order by date;

CREATE MATERIALIZED VIEW testAggregateReplicate_mv to testAggregateReplicate 
AS SELECT date, countState() mcount, **any(now()) workaround** FROM testNull GROUP BY date;

```

SELECT date, countMerge(mcount) FROM testAggregateReplicate GROUP BY date;
┌───────date─┬─countMerge(mcount)─┐
│ 2019-05-14 │             666668 │
│ 2019-05-15 │             666666 │
│ 2019-05-16 │             666666 │
└────────────┴────────────────────┘
```

**Comment by nupursinghbaghel** [comment]
Amazing this is. Thanks much @den-crane :)

**Comment by den-crane** [comment]
Deduplication blocks can be implemented for all engines (including null) (or even at the INSERT level).
Block's hashes can be stored in-memory (or + in a file near the table).

Then the engine (for example Null) can check that it's a duplicate and reject the block (not propagate that block to MVs).

Then insert_deduplication=0 can be set with for all propagations to MVs.

**Comment by filimonov** [comment]
But also valid scenarios of such deduplucation are possible. Let's say you insert to A, matview copy block to B & C, but fails on D. Client repeats insert expecting indempotency and w/o deduplucation data in B and C will be duplicated.

Real atomic inserts needed (table - all MV)

**Comment by nupursinghbaghel** [comment]
Even I agree, we can't disable insert_deduplication. 
I suppose MV shouldn't be deduplicating inserts on first hand.

**Comment by filimonov** [comment]
#2765

**Comment by den-crane** [comment]
My question is irrelevant 
https://github.com/ClickHouse/ClickHouse/blob/899d0f646a3d241af8b80d59aa84729cae675cc4/docs/en/operations/settings/settings.md#deduplicate_blocks_in_dependent_materialized_views-settings-deduplicate_blocks_in_dependent_materialized_views

**Comment by bbszt** [comment]
meet the same problem

**Comment by hexufeng** [comment]
me too. when i add some new  columns to kafka-stream-table、 local-table 、mv，only kafka-stream-table has new data .
