### ISSUE TITLE
SHOW FUNCTIONS and SHOW FUNCTIONS LIKE

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#52757]
**Use case**

Quickly type it in clickhouse-client.

**Additional context**

It could be identical to:
`SELECT * FROM system.functions` and `SELECT * FROM system.functions WHERE name LIKE '...'`
but please also take a look at how it works in MySQL, Postgres, and SQLite.

**Comment by lingtaolf** [comment]
Could you let me try this?

**Comment by alexey-milovidov** [comment]
Yes, please.

**Comment by nikitamikhaylov** [comment]
@lingtaolf @alexey-milovidov 
Sorry, but this task is already booked.
