### ISSUE TITLE
Unhandled Exception on startup

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/ClickHouse#5275]
Hey all!  While trying to find a workaround for #4970, we decided that if we brought down all the pods and brought them back up, then we wouldn't have an issue because there would be no stale connection pools or dns caches to worry about.  However, when rolling all the servers at once, we ran into this:

```
2019.05.14 20:40:59.207871 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Host not found: counters-0.clickhouse.default.svc.cluster.local (version 19.5.2.6 (official build))
```

Would it make sense to handle this case?  The DNS records are provisioned by kubernetes on startup, so don't resolve right away.

**Comment by filimonov** [comment]
Probably you can try to use kubernetes Services, or just add some dns-ready waiting on entrypoint of clickhouse container before starting of clickhouse-server itself

**Comment by abraithwaite** [comment]
Another replica which hasn't come online yet.  We'll be making that entrypoint script but I'm still a bit surprised that this failure would prevent startup.

**Comment by alexey-milovidov** [comment]
Most likely fixed in https://github.com/ClickHouse/ClickHouse/pull/5924
