### ISSUE TITLE
arrayRotateLeft, arrayRotateRight

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#52755]
**Use case**

With some adjustments, it can be helpful for the canonization of "rings"
(Ring is a data type representing a polygon without holes).

**Describe the solution you'd like**

```
arrayRotateLeft(arr, N)
arrayRotateRight(arr, N)

-- Examples:
arrayRotateLeft([1, 2, 3, 4, 5], 3) = [4, 5, 1, 2, 3]
arrayRotateRight([1, 2, 3, 4, 5], 3) = [3, 4, 5, 1, 2]
```

**Comment by FFFFFFFHHHHHHH** [comment]
I'd like to have a try. Could you please assign to me :)

**Comment by UnamedRus** [comment]
Probably shifting(also quite common case) of arrays can be implemented with rotation https://github.com/ClickHouse/ClickHouse/issues/52895

**Comment by mkmkme** [comment]
@FFFFFFFHHHHHHH are you still working on that?

**Comment by FFFFFFFHHHHHHH** [comment]
> @FFFFFFFHHHHHHH are you still working on that?

Yes, but you could create pr if you finish this function quickly with `arrayShiftLeft/Right`.
