### ISSUE TITLE
Table function `loop`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#52765]
**Use case**

Tests and benchmarks.

```
SELECT ... FROM loop(database, table);
SELECT ... FROM loop(database.table);
SELECT ... FROM loop(table);
SELECT ... FROM loop(other_table_function(...));
```

**Describe the solution you'd like**

Every interface method is forwarded, but for reading, the pipeline is modified to repeat the reading when it is finished,
and writing is not allowed. Trivial count optimization is disabled. Index analysis works in the same way as for the argument's table.

It is unspecified if the function should use the same table snapshot on every reading or different.

**Comment by alexey-milovidov** [comment]
@sarielwxm, thank you! This will be very appreciated.

**Comment by sarielwxm** [comment]
@alexey-milovidov Hi, I have a question to confirm, does the function expect to implement an infinite loop or is there a parameter to control the number of loops?

**Comment by alexey-milovidov** [comment]
Infinite loop.
