### ISSUE TITLE
Inconsistency between `String` and `FixedString` type mapping in MySQL compatibility mode.

### ISSUE THREAD

**Issue by EugeniyPetrov** [ClickHouse/ClickHouse#52777]
**Describe the unexpected behaviour**

When using the `use_mysql_types_in_show_columns` setting, implemented in issue #49577, ClickHouse's `String` datatype is mapped to MySQL's `BLOB` datatype. Unfortunately, the QuickSight tool mentioned in the issue does not support this type of columns (https://docs.aws.amazon.com/quicksight/latest/user/supported-data-types.html). As a result, all `String` columns are skipped when a table is added to the dataset.

Also, there is an inconsistency because the `FixedString` type is mapped to the `TEXT` datatype, but `String` and `FixedString` should be mapped at least to the same mysql datatype as there is no any difference of how bytes of text are stored in the clickhouse.

It's a subject for discussion of what datatype they match better, `BLOB` or `TEXT`, but at least Quicksight tool doesn't support `BLOB` columns (but do support `TEXT`).

```
MySQL [voluum]> SHOW FULL COLUMNS IN test;
+----------+---------+------+---------+---------+-------+-----------+---------+------------+
| field    | type    | null | key     | default | extra | collation | comment | privileges |
+----------+---------+------+---------+---------+-------+-----------+---------+------------+
| fixed    | TEXT    |    0 |         | NULL    |       | NULL      |         |            |
| id       | INTEGER |    0 | PRI SOR | NULL    |       | NULL      |         |            |
| variable | BLOB    |    0 |         | NULL    |       | NULL      |         |            |
+----------+---------+------+---------+---------+-------+-----------+---------+------------+
3 rows in set (0.005 sec)
```

**How to reproduce**

- Which ClickHouse server version to use: 23.7
- Which interface to use, if it matters: MySQL
- Non-default settings, if any:
```
SET use_mysql_types_in_show_columns = 1;
```

* `CREATE TABLE` statements for all tables involved

```
CREATE TABLE test (
    id INT NOT NULL PRIMARY KEY,
    variable String(32) NOT NULL,
    fixed FixedString(32) NOT NULL
) ENGINE=MergeTree;
```
* Queries to run that lead to unexpected result

```
SHOW FULL COLUMNS IN test;
```

**Expected behavior**
- `fixed` and `variable` column types should be the same.
- `String` columns should be mapped to the `TEXT` type in order to be supported by Quicksight.

**Comment by alexey-milovidov** [comment]
Yes, from the default logic, both should map to BLOB (which is more correct),
and we should provide a setting to map them to TEXT.

**Comment by shacuros** [comment]
String to BLOB is definitelly correct, but shouldn't FixedString(16) be mapped to BINARY(16) in MySQL to really simulate the same behaviour?

and add a new setting to map String types to readable text, would then result in String -> Text while FixedString(16) would result in CHAR(16)
