### ISSUE TITLE
Creating view on S3 glob pattern takes unexpectedly long time

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#52771]
**Describe the unexpected behaviour**

When creating a view, I am observing 4 seconds from my laptop in us east to data in us west, when I'd expect it to be instant.

**How to reproduce**
* Which ClickHouse server version to use

`ClickHouse server version 23.7.1 revision 54464`

* Queries to run that lead to unexpected result

```
CREATE VIEW s3_parquet AS
SELECT *
FROM s3('https://s3.us-west-2.amazonaws.com/ookla-open-data/parquet/performance/type=*/year=*/quarter=*/*.parquet', 'Parquet', 'quadkey Nullable(String), tile Nullable(String), avg_d_kbps Nullable(Int64), avg_u_kbps Nullable(Int64), avg_lat_ms Nullable(Int64), tests Nullable(Int64), devices Nullable(Int64)')

Query id: 7eaf74c7-25ba-4748-8dff-6f4accdcdabb

Ok.

0 rows in set. Elapsed: 4.021 sec.

d2e52eb1a093 :) select count() from s3_parquet

SELECT count()
FROM s3_parquet

Query id: a703f818-ac38-40ea-a1fa-8736c28f5bd3

┌───count()─┐
│ 185832935 │
└───────────┘

1 row in set. Elapsed: 40.022 sec. Processed 185.83 million rows, 7.17 GB (4.64 million rows/s., 179.10 MB/s.)
```

Without View (killed to reset cache):
```
SELECT count()
FROM s3('https://s3.us-west-2.amazonaws.com/ookla-open-data/parquet/performance/type=*/year=*/quarter=*/*.parquet', 'Parquet', 'quadkey Nullable(String), tile Nullable(String), avg_d_kbps Nullable(Int64), avg_u_kbps Nullable(Int64), avg_lat_ms Nullable(Int64), tests Nullable(Int64), devices Nullable(Int64)')

Query id: 2f8b2625-9e89-418e-8d58-e5cff0d2e7e2

┌───count()─┐
│ 185832935 │
└───────────┘

1 row in set. Elapsed: 40.336 sec. Processed 185.83 million rows, 7.17 GB (4.61 million rows/s., 177.71 MB/s.)
```

I've specified the schema to remove the possibility that it needs to scan files to determine schema. As you can see creating the view takes 4 seconds, but the count of both queries takes nearly identical time. I am not sure what it is doing when creating the view but from at least this query it does not seem to be helpful.

**Comment by danthegoodman1** [comment]
Based on query time it also seems to be doing more than just listing, otherwise I'd expect the s3 function to take an extra 3-4 seconds.

For example in duckdb:

```
create view test as SELECT * FROM read_parquet('s3://ookla-open-data/parquet/performance/type=*/year=*/quarter=*/*.parquet');

Completed in 933ms
```

**Comment by danthegoodman1** [comment]
This was first observed in https://github.com/ClickHouse/ClickHouse/issues/44246#issue-1497564465

**Comment by alexey-milovidov** [comment]
@danthegoodman1, I've debugged this problem and merged a fix.

The reason was trivial. First of all, it was not related to globs.
It is an attempt to request IMDS service to get credentials, with a few retries and timeouts.

**Comment by alexey-milovidov** [comment]
This fix will appear in version 24.9 (September), but if you want to use it today, install the latest:

```
curl https://clickhouse.com/ | sh
```

Cheers!

**Comment by danthegoodman1** [comment]
awesome!

**Comment by danthegoodman1** [comment]
so to be clear, creating a view does not attempt to ready any files @alexey-milovidov ?

**Comment by alexey-milovidov** [comment]
With the explicit schema, as in this example, it shouldn't read the files.
But you can also create a view without specifying a schema - then it will involve schema inference.
Finally, you can create view AS table_function() instead of AS SELECT, and it will make every work lazy.

Let me check all three cases...

**Comment by alexey-milovidov** [comment]
Example 1:

https://pastila.nl/?024c35f0/7cd40008a9b189c0f90ad94c2a55e67a#5wgqZecUro6y6+iCb6iKPA==

The view is created quickly and does not read files.
It still takes 93 ms just to figure out that the machine is not in the cloud.

The query is quite fast, if we take into account it is my home internet.

**Comment by alexey-milovidov** [comment]
Example 2:

https://pastila.nl/?00a6ccaf/f8656d6eafbbf7feadf9e7b57538d986#4TjQ5RFg4hxP90rjIBkD5g==

This example uses schema inference. It takes time during the view creation. But it is only 1.472 sec.
The SELECT query is fast as well.

**Comment by alexey-milovidov** [comment]
Example 3:

https://pastila.nl/?00c2af8d/89306a06f78f78f1b946b447395458b3#nWUwU95FrQapf/Y689yjLQ==

In this example, we use the `CREATE TABLE ... AS function(...)` syntax, instead of VIEW.
Regardless, it still needs to perform schema inference to figure out the structure of the table.

**Comment by danthegoodman1** [comment]
Is there any way to define without schema, but enable lazy schema lookups?

**Comment by alexey-milovidov** [comment]
Do you want schema inference on every SELECT?

No, it is currently not possible. The reason is:
- a view or a table is a table-like object;
- every table-like object requires schema, and there is no notion of tables without a schema or lazy schema (but I thought about it);

The easiest way is to query directly instead of creating a table-like object.
