### ISSUE TITLE
The replica data is not synchronized. Procedure

### ISSUE THREAD

**Issue by dry125** [ClickHouse/ClickHouse#52789]
ClickHouse-Keeper uses "create database mydatabase on cluster rptcluster" to create a database.
By "use mydatabase;
CREATE TABLE mytable on cluster rptcluster
(
EventDate DateTime,
CounterID UInt32,
UserID UInt32
) ENGINE = ReplicatedMergeTree ()
PARTITION BY toYYYYMM(EventDate)
ORDER BY (CounterID, EventDate, intHash32(UserID))
SAMPLE BY intHash32(UserID);" ;
After passing "insert into mydatabase. mytable values('2020-03-11 12:12:33', 22, 37);
"After inserting the data
The replica data is not synchronized. Procedure

**Comment by cangyin** [comment]
> ENGINE = ReplicatedMergeTree ()

you have to specify  zookeeper path for the replicated table, otherwise the table will have no way to synchronize nothing.

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication

**Comment by den-crane** [comment]
> > ENGINE = ReplicatedMergeTree ()
> 
> you have to specify zookeeper path for the replicated table, otherwise the table will have no way to synchronize nothing.
> 
> https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication

it's not true. `On cluster` specify ZK path using UUID automatically if ZK path is omitted.

```sql
CREATE TABLE mytable ON CLUSTER sr
(
    `EventDate` DateTime,
    `CounterID` UInt32,
    `UserID` UInt32
)
ENGINE = ReplicatedMergeTree
PARTITION BY toYYYYMM(EventDate)
ORDER BY (CounterID, EventDate, intHash32(UserID))
SAMPLE BY intHash32(UserID);

SELECT zookeeper_path FROM system.replicas WHERE table = 'mytable';

┌─zookeeper_path────────────────────────────────────────────┐
│ /clickhouse/tables/c4b94ac9-5af6-4660-967d-50e42917df87/2 │
└───────────────────────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
Check the server logs and the network connectivity between the servers.
