### ISSUE TITLE
S3 parquet queries should be parallelized (and distributed) by row group, not file

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#52790]
Currently, the parallelism of reading parquet files is determined by the number of parquet files being read. Instead, parallelism (single node and cluster) should occur at the row-group level. This will allow for far faster processing of parquet files (especially for single file processing), as the optimal way to handle parquet files is to merge them, not spread them out.

ClickHouse's current processing method is an anti-pattern for processing parquet as it encourages many small files rather than fewer large files, which is exacerbated when reading from S3 and needing to perform lots of listing operations first.

Row groups are analogous to granules inside a part for MergeTree family.

**Comment by Avogar** [comment]
Reading parquet file is already parallelized at row-group level after https://github.com/ClickHouse/ClickHouse/pull/47964
