### ISSUE TITLE
SHOW CREATE TABLE command does not include ON CLUSTER part

### ISSUE THREAD

**Issue by Hubbitus** [ClickHouse/ClickHouse#52803]
> You have to provide the following information whenever possible.

**Describe what's wrong**

`SHOW CREATE TABLE` statement does not return `ON CLUSTER` clause.

**Does it reproduce on recent release?**

Yes, it is reproducible on version 23.3.8.21

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

```sql
CREATE TABLE table_test ON CLUSTER gid (
    value String
)
ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/tables/{table}/{shard}', '{replica}')
PRIMARY KEY value;

SHOW CREATE TABLE table_test;
```

**Expected behavior**

```sql
CREATE TABLE datamart.table_test
(
    `value` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/tables/table_test/{shard}', '{replica}')
PRIMARY KEY value
ORDER BY value
SETTINGS index_granularity = 8192
```

There `ON CLUSTER ...` clause is missing, expected to be:
```sql
CREATE TABLE datamart.table_test ON CLUSTER gid (
    `value` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/{cluster}/tables/table_test/{shard}', '{replica}')
PRIMARY KEY value
ORDER BY value
SETTINGS index_granularity = 8192
```

**Comment by helifu** [comment]
I'm sure that the clause 'on cluster xxx' is used to specify which nodes to execute on, not as part of the table schema. Thus, this is not a issue. :)

**Comment by Hubbitus** [comment]
Hm. But that is part of DDL, is not? Looks inconsistently.

**Comment by tavplubix** [comment]
It works as expected, it should not include `ON CLUSTER` clause

**Comment by Hubbitus** [comment]
@tavplubix, why shouldn't? Even documentation does not state it.

**Comment by enteve** [comment]
at least we need a command to get the **exact** statement when we created the table. otherwise when i try to backup the creation command and do the same thing on other cluster, how i'm supposed to do?

**Comment by vc43** [comment]
I fully support the author. ON CLUSTER should be in the output.

**Comment by lucasfcnunes** [comment]
> It works as expected, it should not include `ON CLUSTER` clause

@tavplubix, is there a technical explanation for this?
