### ISSUE TITLE
Decimal loss of accuracy

### ISSUE THREAD

**Issue by 12frame** [ClickHouse/ClickHouse#52846]
When writing data to a table, some data may lose accuracy, resulting in a loss of 0.01
select toDecimal64(639.30, 2);
select toDecimal64(639.80, 2);
select toDecimal64(128.790, 3);
![image](https://github.com/ClickHouse/ClickHouse/assets/63937733/be9b434f-cb20-41a4-8fc3-3f8150828754)

**Comment by alexey-milovidov** [comment]
Duplicate of #52599.
