### ISSUE TITLE
Error using `WATCH` with datetime `where` clause

### ISSUE THREAD

**Issue by samuelcolvin** [ClickHouse/ClickHouse#52860]
I have the following table:

```sql
create table demo (name String, timestamp DateTime64(6)) ENGINE = MergeTree ORDER BY timestamp
```

I create a live view:

```sql
create live view my_view as select name, timestamp from demo where timestamp>'2023-08-01 11:46:51.096640'
```

(The timestamp in reality is basically now `now()` so we don't get older records)

Then I watch the view with

```sql
watch my_view
```

and insert data with

```sql
insert into demo (name, timestamp) values ('foo', '2023-08-01 11:46:52.2')
```

I the get following error in the watch query:

```
↓ Progress: 21.00 rows, 588.00 B (2.91 rows/s., 81.59 B/s.)                                                                                                                                             (0.0 CPU, 104.66 KB RAM)
30 rows in set. Elapsed: 7.207 sec. 

Received exception from server (version 23.7.1):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::ColumnDecimal<DB::DateTime64> to DB::ColumnString. (LOGICAL_ERROR)
```

What's weird is that the error doesn't generally happen when the first insert happens, but rather on the second or third insert.

---

I'm using version `23.7.1.2470`

**Comment by samuelcolvin** [comment]
I get the same if I use `now()` instead of `'2023-08-01 11:46:51.096640'`.

**Comment by samuelcolvin** [comment]
I also tried changing the `timestamp` field to a `Int64`, but I get the same error or segfault.

**Comment by alexey-milovidov** [comment]
Live view is an experimental feature, and it is currently unsupported.
Most likely it will be removed.

**Comment by Kludex** [comment]
@alexey-milovidov Thanks for the help!

Alexey, since that's the case, would you perhaps have any suggestion on how we can performantly watch changes in ClickHouse? Is polling the best we can do, or is there something else not obvious we can do?

**Comment by alexey-milovidov** [comment]
Polling is ok if queries are lightweight (e.g., requesting by time condition, which uses primary key).
