### ISSUE TITLE
arrayShiftLeft, arrayShiftRight

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#52895]
**Use case**

Shift array values, quite commonly used with combination of arrayMap

**Describe the solution you'd like**

```
arrayShiftLeft(arr, N)
arrayShiftLeft(arr, N, 3)
arrayShiftRight(arr, N)
arrayShiftRight(arr, N, 5)
-- Examples:
arrayShiftLeft([1, 2, 3, 4, 5], 1) = [0, 1, 2, 3, 4]
arrayShiftRight([1, 2, 3, 4, 5], 1, 3) = [2, 3, 4, 5, 3]
```

**Describe alternatives you've considered**

```
arrayPopBack(arrayPushFront(x, 1))`
```

But it makes 2 copies of array

**Comment by alexey-milovidov** [comment]
The examples are non-obvious.

> `arrayShiftLeft([1, 2, 3, 4, 5], 1) = [0, 1, 2, 3, 4]`

Did you mean `arrayShiftRight`, `[0, 1, 2, 3, 4, 5]`?

The logic looks strange... We need to find good semantics and analogies for this.

**Comment by UnamedRus** [comment]
> Did you mean arrayShiftRight

Yes, 

> , [0, 1, 2, 3, 4, 5]?

No, array size stays the same, ie last element is removed from it

My idea for signature was something like

`arrayShiftLeft/Right(array, N, [default_value = 0])`

Where N is by how many elements we want to shift array
And `default_value` is optional argument for value which will take place of shifted values
.

**Comment by alexey-milovidov** [comment]
Ok.

**Comment by FFFFFFFHHHHHHH** [comment]
Is that a little ambiguous with `arrayRotateLeft/Right`?
`arrayRotateLeft` means moving the original array from right to left.
`arrayShiftLeft` means moving the original array from left to right.

**Comment by UnamedRus** [comment]
> Is that a little ambiguous with arrayRotateLeft/Right?

No, it's not.
In case of arrayShift, we don't have ring, so values from end will not appear at beginning

https://clickhouse.com/docs/en/sql-reference/functions/bit-functions#bitshiftlefta-b
https://clickhouse.com/docs/en/sql-reference/functions/bit-functions#bitrotatelefta-b

**Comment by FFFFFFFHHHHHHH** [comment]
> > Is that a little ambiguous with arrayRotateLeft/Right?
> 
> No, it's not. In case of arrayShift, we don't have ring, so values from end will not appear at beginning
> 
> https://clickhouse.com/docs/en/sql-reference/functions/bit-functions#bitshiftlefta-b https://clickhouse.com/docs/en/sql-reference/functions/bit-functions#bitrotatelefta-b

I mean if there's any ambiguity in the direction.

Maybe 
```sql
arrayShiftLeft([1, 2, 3, 4, 5], 1) = [2, 3, 4, 5, 0]
arrayShiftRight([1, 2, 3, 4, 5], 1, 3) = [3, 1, 2, 3, 4]
```

**Comment by alexey-milovidov** [comment]
If it is so non-obvious, maybe we can avoid implementing this feature :smile: 

@UnamedRus or clarify the use-case.

**Comment by UnamedRus** [comment]
Use case

```
arrayPopBack(arrayPushFront(cum_shard_weights, 0))
```

```
WITH
    CAST(xxHash64(name), 'Int64') AS key,
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] AS shard_num,
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] AS shard_weights,
    arrayCumSum(shard_weights) AS cum_shard_weights,
    arraySum(shard_weights) AS total_weight
SELECT
    name,
    key,
    key % total_weight AS modulo,
    arrayFirst((x, y, z) -> ((modulo < y) AND (modulo >= z)), shard_num, cum_shard_weights, arrayPopBack(arrayPushFront(cum_shard_weights, 0))) AS _result_shart_num
FROM
(
    SELECT arrayJoin(['lilei6_6938', 'lilei0_87531', 'lilei9_46548']) AS name
)



┌─name─────────┬──────────────────key─┬─modulo─┬─_result_shart_num─┐
│ lilei6_6938  │ -4777066231024988473 │      3 │                 4 │
│ lilei0_87531 │  5478184676739000754 │      4 │                 5 │
│ lilei9_46548 │ -2574499495101583472 │      4 │                 5 │
└──────────────┴──────────────────────┴────────┴───────────────────┘
```

https://github.com/ClickHouse/ClickHouse/issues/51841#issuecomment-1625092934

**Comment by mkmkme** [comment]
@alexey-milovidov so this is okay to implement? I could take it (as well as `arrayRotateLeft/Right`

**Comment by alexey-milovidov** [comment]
Yes! Thank you!

**Comment by alexey-milovidov** [comment]
```
arrayShiftRight(['H', 'e', 'l', 'l', 'o'], 1) = ['', 'H', 'e', 'l', 'l']
```
