### ISSUE TITLE
When processing select query fields and aliases, it is not consistent with the mysql protocol, and the final behavior is also inconsistent with mysql

### ISSUE THREAD

**Issue by LUAgam** [ClickHouse/ClickHouse#52902]
**Describe the unexpected behaviour**
When processing select query fields and aliases, it is not consistent with the mysql protocol, and the final behavior is also inconsistent with mysql

**How to reproduce**
Very simple, execute SQL like this: select c.id,d.id from test c join test d on c.id = d.id;

**Expected behavior**
The mysql return format is:
```
+----+----+
| id | id |
+----+----+
|  1 |  1 |
+----+----+
```

**Error message and/or stacktrace**
The return format of clickhouse is:
```
+------+------+
| id   | d.id |
+------+------+
|    1 |    1 |
+------+------+
```

**Additional context**
Packet capture analysis found that tables and fields in the mysql protocol are distinguished:
![image](https://github.com/ClickHouse/ClickHouse/assets/17228757/8fa7d4bd-3dad-4705-a95b-696834a9c0ff)
But the mysql protocol package of clickhouse is
![image](https://github.com/ClickHouse/ClickHouse/assets/17228757/631fdb90-9b81-458c-906a-fd5aa1cc98e0)
From this point of view, the mysql protocol package implemented by clickhouse does not meet the specifications.

**Comment by melvynator** [comment]
@LUAgam it seems like a known issue, and there is a workaround: https://github.com/ClickHouse/ClickHouse/issues/34697

**Comment by LUAgam** [comment]
Thanks!
although the problem can be solved by multiple_joins_try_to_keep_original_names, I think it is still an optimizable item, after all, it is inconsistent with mysql/PostgreSQL behavior.

**Comment by melvynator** [comment]
Yes, I fully agree. I'm not closing because it's not something we don't want to do, but because it's a duplicate.

**Comment by melvynator** [comment]
I will also add your comment about the lack of SQL compatibility, into the other github issue
