### ISSUE TITLE
SQLLogicTestRelease rare fails

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#52905]
SQLLogicTestRelease failed a couple of times:

[Case 1](https://github.com/ClickHouse/ClickHouse/pull/52839#issuecomment-1661699293), [job link](https://github.com/ClickHouse/ClickHouse/actions/runs/5726460395/job/15528557113?pr=52839)

[Case 2](https://github.com/ClickHouse/ClickHouse/pull/51985#issuecomment-1627782631), [job link](https://github.com/ClickHouse/ClickHouse/actions/runs/5500479451/job/14891615705)

**Comment by tavplubix** [comment]
These failures can be ignored for now (SQLLogic tests are known to fail sometimes, they are in "always green" mode)
