### ISSUE TITLE
Can grace hash join completely replace sort merge join in CH? 

### ISSUE THREAD

**Issue by Aaaaaaron** [ClickHouse/ClickHouse#52900]
We want to use join with the spill and we found two alg that can spill data when joining, and here we are wondering can grace hash join completely replaces sort merge join in CH?

**Comment by UnamedRus** [comment]
In future, ClickHouse should be able to use table sorting on disk in sort merge join, so it will be much more efficient.

**Comment by melvynator** [comment]
@Aaaaaaron Grace hash join doesn’t require any data sorting and therefore overcomes some of the performance challenges of other join algorithms that spill data to disk like the merge join. I would advise you to look at this series of blog articles to make your decision on which join algorithm to use:

https://clickhouse.com/blog/clickhouse-fully-supports-joins-part1 

As mentioned by @UnamedRus a lot of improvements are coming to join in ClickHouse to make them more efficient like Dynamic JOIN algorithm selection and JOIN rewrite.
