### ISSUE TITLE
[Question] Cannot read all array values

### ISSUE THREAD

**Issue by igor-sh8** [ClickHouse/ClickHouse#5292]
Hello. 
Today I faced with such error: 
`DB::Exception: Cannot read all array values: read just 252055 of 298476: (while reading column NMap.Id): (while reading from part /mnt/clickhouse/data/db1/Table1/20190515_44_44_0/ from mark 0 with max_rows_to_read = 8192`
Such error occurs on the MaterializeView:
`CREATE MATERIALIZED VIEW db1.Table1View TO db1.Table1 ( Date Date,  Id Int32,  `PMap.Id` Array(Int32),  `PMap.Requests` Array(Int64),  `NMap.Id` Array(Int32),  `NMap.Requests` Array(Int64),  `PFMap.Id` Array(Int32),  `PFMap.Requests` Array(Int64),  `SMap.Id` Array(Int32),  `SMap.Requests` Array(Int64),  Reqs Int64,  Views Int64,  Money Decimal(18, 4),   Revenue Decimal(38, 8)) AS SELECT Date, Id, arrayMap(x -> arrayJoin(x), groupArray(PPMap.Id)) AS `PMap.Id`, arrayMap(x -> arrayJoin(x), groupArray(PPMap.Requests)) AS `PMap.Requests`, arrayMap(x -> arrayJoin(x), groupArray(PNMap.Id)) AS `NMap.Id`, arrayMap(x -> arrayJoin(x), groupArray(PNMap.Requests)) AS `NMap.Requests`, arrayMap(x -> arrayJoin(x), groupArray(PPFMap.Id)) AS `PFMap.Id`, arrayMap(x -> arrayJoin(x), groupArray(PPFMap.Requests)) AS `PFMap.Requests`, arrayMap(x -> arrayJoin(x), groupArray(PSMap.Id)) AS `SMap.Id`, arrayMap(x -> arrayJoin(x), groupArray(PSMap.Requests)) AS `SMap.Requests`, SUM(Reqs ) AS Reqs , SUM(Views) AS Views, toDecimal64(SUM(Money), 4) AS Money, SUM(Revenue) AS Revenue FROM db1.PlainTable GROUP BY Id`
Maybe I am doing something wrong ?

**Comment by blinkov** [comment]
@igor-sh8, do you have any further questions?

**Comment by igor-sh8** [comment]
Hi. 
No, on the new versions of the clickhouse, we do not encounter such problems.
So I think the problem is solved.

**Comment by thinhnp-it** [comment]
@igor-sh8 How could you fix it? I got the same error on version 20.3.8.53 (official build)
