### ISSUE TITLE
"Information" vs "notice" logging level

### ISSUE THREAD

**Issue by heyciao** [ClickHouse/ClickHouse#5293]
**Current situation**
On one hand, when I start Clickhouse I see for example these messages:
```
...
2019.05.15 23:39:30.469929 [ 1 ] {} <Information> DatabaseOrdinary (internet22_clk): Total 6 tables.
2019.05.15 23:39:30.663810 [ 1 ] {} <Information> DatabaseOrdinary (internet22_clk): Starting up tables.
2019.05.15 23:39:30.665669 [ 1 ] {} <Information> DatabaseOrdinary (internet23_clk): Total 12 tables.
2019.05.15 23:39:30.870026 [ 1 ] {} <Information> DatabaseOrdinary (internet23_clk): Starting up tables.
2019.05.15 23:39:30.871413 [ 1 ] {} <Information> DatabaseOrdinary (internet24_clk): Total 6 tables.
2019.05.15 23:39:31.137396 [ 1 ] {} <Information> DatabaseOrdinary (internet24_clk): Starting up tables.
2019.05.15 23:39:31.139315 [ 1 ] {} <Information> Application: It looks like the process has no CAP_NET_ADMIN capability, 'taskstats' performance statistics will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_net_admin=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems. It also doesn't work if you run clickhouse-server inside network namespace as it happens in some containers.
2019.05.15 23:39:31.139788 [ 1 ] {} <Information> Application: Listening http://10.0.6.1:8123
2019.05.15 23:39:31.139837 [ 1 ] {} <Information> Application: Listening tcp: 10.0.6.1:9000
2019.05.15 23:39:31.139902 [ 1 ] {} <Information> Application: Listening interserver http: 10.0.6.1:9009
2019.05.15 23:39:31.140350 [ 1 ] {} <Information> Application: Available RAM: 31.35 GiB; physical cores: 6; logical cores: 12.
2019.05.15 23:39:31.140361 [ 1 ] {} <Information> Application: Ready for connections.
```
(the above timestamps are very near to each other because I had all cached in RAM - after a server reboot it usually takes at least ~10 minutes)
These messages are very important to me as they show what the DB engine is doing and when the DB is finally online/available.

On the other hand, when queries are executed I see for example these messages...
```
...
2019.05.15 23:56:38.821205 [ 45 ] {edd80e4e-f272-4a9c-915c-59f7568bb205} <Information> TCPHandler: Processed in 0.025 sec.
2019.05.15 23:56:38.865374 [ 44 ] {b6f4a442-5e57-4f6a-affb-a2a432cfb0c7} <Information> TCPHandler: Processed in 0.043 sec.
2019.05.15 23:56:38.948508 [ 48 ] {e849a042-df49-48fe-81bf-6aa17797c493} <Information> TCPHandler: Processed in 0.007 sec.
2019.05.15 23:56:38.948538 [ 54 ] {1d54c114-24d0-4303-a49c-d8131d0d453e} <Information> TCPHandler: Processed in 0.011 sec.
2019.05.15 23:56:38.954464 [ 48 ] {c7e1751e-d5a8-4f8f-8346-61cb5c883c15} <Information> TCPHandler: Processed in 0.005 sec.
...
```
...and I (personally) don't care at all about them.

**Problem**
If I set the logger level to anything higher than "information" ( https://github.com/pocoproject/poco/blob/develop/Foundation/include/Poco/Logger.h#L105 ) to avoid getting a log-entry for each single query, I don't get anymore the logs related to the start of the DB.

**Question**
Would it be possible to associate the messages related to the start of the DB to a higher log level? (for example "notice")

Cheers & thanks a lot for your fantastic DB! :)

**Comment by filimonov** [comment]
Sounds reasonable.

**Comment by alexey-milovidov** [comment]
How to implement:
- add `LOG_NOTICE` to `logger_useful.h`;
- replace `LOG_INFO` to `LOG_NOTICE` in the appropriate places related to server startup.

**Comment by spanningwings** [comment]
Is this issue still need a fix? It's been a long time. Sounds like something that I can help to get me familiar with the ClickHouse dev process. Please drop me a message.

**Comment by alexey-milovidov** [comment]
Yes, it will be very appreciated.
This task has low priority but users need it.

**Comment by spanningwings** [comment]
Thanks. I will tackle this issue once I set up my environment.

**Comment by spanningwings** [comment]
I create a pull request #15531 for it.

**Comment by alexey-milovidov** [comment]
@heyciao We cannot use notice because it goes to the error log, see the details in #15531
What we can do instead is to lower the level of these messages:
```
<Information> TCPHandler: Processed in 0.025 sec.
```

**Comment by heyciao** [comment]
> @heyciao We cannot use notice because it goes to the error log, see the details in #15531
> What we can do instead is to lower the level of these messages:
> 
> ```
> <Information> TCPHandler: Processed in 0.025 sec.
> ```

Not sure about what you mean with "lowering" - it's for sure ok as long as it separates startup/shutdown messages from others which have a purely informative/non-critical nature.
Cheers
