### ISSUE TITLE
zk always loses copy information, resulting in repeated table creation and deletion of zk information

### ISSUE THREAD

**Issue by DemoMoon** [ClickHouse/ClickHouse#52946]
Clickhouse (version 23.4.2.11 (official build))
zookeeper：apache-zookeeper-3.8.1

desc

Some zk lost copy information appears
Only the frequency of losing zk copies is higher

exception：
2023.08.03 00:16:34.029679 [ 2986785 ] {} <Error> ah_bigdata_cluster_shard_3.ahbd_ultra_alarm_event_rep (15239ebd-cd92-4db5-bd12-e421944dfc77): void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999. Coordination::Exception: Can't get data for node /clickhouse/tables/ahbd_ultra_all_alarm_event_03/ahbd_ultra_alarm_event/replicas/2/log_pointer: node doesn't exist (No node). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe3bb175 in /usr/lib/debug/usr/bin/clickhouse.debug
1. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: Coordination::Exception::Exception(String const&, Coordination::Error, int) @ 0x152af630 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: Coordination::Exception::Exception(String const&, Coordination::Error) @ 0x152af958 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/./src/Common/ZooKeeper/ZooKeeper.cpp:0: zkutil::ZooKeeper::get(String const&, Coordination::Stat*, std::shared_ptr<Poco::Event> const&) @ 0x152b9553 in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::shared_ptr<zkutil::ZooKeeper>, std::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x14ac6928 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:818: DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x143d3094 in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/./base/glibc-compatibility/musl/clock_gettime.c:62: DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x12a9d186 in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::BackgroundSchedulePool::threadFunction() @ 0x12aa05ea in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/./src/Core/BackgroundSchedulePool.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_1&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x12aa142e in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/./base/base/../base/wide_integer_impl.h:789: ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe48c2a1 in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:302: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0xe491b21 in /usr/lib/debug/usr/bin/clickhouse.debug
11. ? @ 0x8fed in /usr/lib64/libpthread-2.28.so
12. clone @ 0xfd18f in /usr/lib64/libc-2.28.so
 (version 23.4.2.11 (official build))

sql script

CREATE TABLE ah_bigdata_cluster_shard_1.ahbd_ultra_alarm_event_rep (
  `id` String,
  `create_time_`  DateTime,
  `update_time_`  DateTime,
  `d_ip` Nullable(String),
  `solu` Nullable(String),
  `rule_name` Nullable(String),
  `origin_company` Nullable(String),
  `time` DateTime,
  `origin_topic` Nullable(String),
  `evt_t` Nullable(String),
  `k_c` Nullable(String),
  `name` Nullable(String),
  `s_port` Nullable(String),
  `s_ip` Nullable(String),
  `e_id` Nullable(String),
  `d_port` Nullable(String),
  `o_times` Nullable(Int32),
  `severity` Nullable(String)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/ahbd_ultra_all_alarm_event_01/ahbd_ultra_alarm_event',
 '1')
PARTITION BY toYYYYMMDD(`time`)
ORDER BY (id,`time`) 
PRIMARY KEY (id);
//在ck002上执行
CREATE TABLE ah_bigdata_cluster_shard_1.ahbd_ultra_alarm_event_rep (
  `id` String,
  `create_time_`  DateTime,
  `update_time_`  DateTime,
  `d_ip` Nullable(String),
  `solu` Nullable(String),
  `rule_name` Nullable(String),
  `origin_company` Nullable(String),
  `time` DateTime,
  `origin_topic` Nullable(String),
  `evt_t` Nullable(String),
  `k_c` Nullable(String),
  `name` Nullable(String),
  `s_port` Nullable(String),
  `s_ip` Nullable(String),
  `e_id` Nullable(String),
  `d_port` Nullable(String),
  `o_times` Nullable(Int32),
  `severity` Nullable(String)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/ahbd_ultra_all_alarm_event_01/ahbd_ultra_alarm_event',
 '2')
PARTITION BY toYYYYMMDD(`time`)
ORDER BY (id,`time`) 
PRIMARY KEY (id);

//在ck002上执行
CREATE TABLE ah_bigdata_cluster_shard_2.ahbd_ultra_alarm_event_rep (
     `id` String,
  `create_time_`  DateTime,
  `update_time_`  DateTime,
  `d_ip` Nullable(String),
  `solu` Nullable(String),
  `rule_name` Nullable(String),
  `origin_company` Nullable(String),
  `time` DateTime,
  `origin_topic` Nullable(String),
  `evt_t` Nullable(String),
  `k_c` Nullable(String),
  `name` Nullable(String),
  `s_port` Nullable(String),
  `s_ip` Nullable(String),
  `e_id` Nullable(String),
  `d_port` Nullable(String),
  `o_times` Nullable(Int32),
  `severity` Nullable(String)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/ahbd_ultra_all_alarm_event_02/ahbd_ultra_alarm_event',
 '1')
PARTITION BY toYYYYMMDD(`time`)
ORDER BY (id,`time`) 
PRIMARY KEY (id);
//在ck003上执行
CREATE TABLE ah_bigdata_cluster_shard_2.ahbd_ultra_alarm_event_rep (
  `id` String,
  `create_time_`  DateTime,
  `update_time_`  DateTime,
  `d_ip` Nullable(String),
  `solu` Nullable(String),
  `rule_name` Nullable(String),
  `origin_company` Nullable(String),
  `time` DateTime,
  `origin_topic` Nullable(String),
  `evt_t` Nullable(String),
  `k_c` Nullable(String),
  `name` Nullable(String),
  `s_port` Nullable(String),
  `s_ip` Nullable(String),
  `e_id` Nullable(String),
  `d_port` Nullable(String),
  `o_times` Nullable(Int32),
  `severity` Nullable(String)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/ahbd_ultra_all_alarm_event_02/ahbd_ultra_alarm_event',
 '2')
PARTITION BY toYYYYMMDD(`time`)
ORDER BY (id,`time`) 
PRIMARY KEY (id);

//在ck003上执行
CREATE TABLE ah_bigdata_cluster_shard_3.ahbd_ultra_alarm_event_rep (
  `id` String,
  `create_time_`  DateTime,
  `update_time_`  DateTime,
  `d_ip` Nullable(String),
  `solu` Nullable(String),
  `rule_name` Nullable(String),
  `origin_company` Nullable(String),
  `time` DateTime,
  `origin_topic` Nullable(String),
  `evt_t` Nullable(String),
  `k_c` Nullable(String),
  `name` Nullable(String),
  `s_port` Nullable(String),
  `s_ip` Nullable(String),
  `e_id` Nullable(String),
  `d_port` Nullable(String),
  `o_times` Nullable(Int32),
  `severity` Nullable(String)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/ahbd_ultra_all_alarm_event_03/ahbd_ultra_alarm_event',
 '1')
PARTITION BY toYYYYMMDD(`time`)
ORDER BY (id,`time`) 
PRIMARY KEY (id);
//在ck001上执行
CREATE TABLE ah_bigdata_cluster_shard_3.ahbd_ultra_alarm_event_rep (
  `id` String,
  `create_time_`  DateTime,
  `update_time_`  DateTime,
  `d_ip` Nullable(String),
  `solu` Nullable(String),
  `rule_name` Nullable(String),
  `origin_company` Nullable(String),
  `time` DateTime,
  `origin_topic` Nullable(String),
  `evt_t` Nullable(String),
  `k_c` Nullable(String),
  `name` Nullable(String),
  `s_port` Nullable(String),
  `s_ip` Nullable(String),
  `e_id` Nullable(String),
  `d_port` Nullable(String),
  `o_times` Nullable(Int32),
  `severity` Nullable(String)
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/ahbd_ultra_all_alarm_event_03/ahbd_ultra_alarm_event',
 '2')
PARTITION BY toYYYYMMDD(`time`)
ORDER BY (id,`time`) 
PRIMARY KEY (id);

CREATE TABLE ahbd_ultra_alarm_event (
  `id` String,
  `create_time_`  DateTime,
  `update_time_`  DateTime,
  `d_ip` Nullable(String),
  `solu` Nullable(String),
  `rule_name` Nullable(String),
  `origin_company` Nullable(String),
  `time` DateTime,
  `origin_topic` Nullable(String),
  `evt_t` Nullable(String),
  `k_c` Nullable(String),
  `name` Nullable(String),
  `s_port` Nullable(String),
  `s_ip` Nullable(String),
  `e_id` Nullable(String),
  `d_port` Nullable(String),
  `o_times` Nullable(Int32),
  `severity` Nullable(String)
)
ENGINE = Distributed('ah_3s2r_cluster',
 '',
 'ahbd_ultra_alarm_event_rep',
 rand());

**Comment by DemoMoon** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/5241098/492e0107-03f9-4f84-92f4-ee15d05cafdc)
![image](https://github.com/ClickHouse/ClickHouse/assets/5241098/45cb98c5-0abc-43bc-94ee-867a0881d6db)
![image](https://github.com/ClickHouse/ClickHouse/assets/5241098/4b1f4fba-6079-407e-913d-3e66406bd54e)

**Comment by alexey-milovidov** [comment]
This means that your ZooKeeper setup is incorrect.
