### ISSUE TITLE
Direct Join has worse performance than joinGet

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#52968]
There's two ways to query multiple columns from a storage join:

- Use multiple `joinGet`, e.g. `SELECT key, joinGet('table_join', 'value1', key), joinGet('table_join',  'value2', key) ... FROM keys`
- Use direct join, .e.g `SELECT key, value1, value2 ... FROM keys LEFT ANY JOIN table_join AS rhs ON key = rhs.key

Theoretically, the first approach will look up hash table multiple times, so it should have worse performance. Some quick test also show that: https://fiddle.clickhouse.com/f169c0ea-c966-40f8-aefa-cd341734ad9b

```sql
SELECT key, joinGet('dict', 'value1', key) AS value1, joinGet('dict', 'value2', key) AS value2 FROM keys FORMAT Null SETTINGS send_logs_level='debug';

<Debug> executeQuery: Read 10000000 rows, 76.29 MiB in 0.246209 sec., 40615899.500018276 rows/sec., 309.87 MiB/sec.
<Debug> MemoryTracker: Peak memory usage (for query): 28.13 MiB.

SELECT keys.key, value1, value2 FROM keys ANY LEFT JOIN dict AS d ON (keys.key = d.key) FORMAT Null SETTINGS send_logs_level='debug';

<Debug> executeQuery: Read 10000000 rows, 76.29 MiB in 0.122637 sec., 81541459.75521255 rows/sec., 622.11 MiB/sec.
<Debug> MemoryTracker: Peak memory usage (for query): 31.05 MiB.
```

But with real queries on big tables on prod, using direct join is actually worse than `joinGet`. I've tested many times and get the same result, so it's not a env fluctuation.

Any possible reason can lead to this?

**Comment by vdimir** [comment]
Have `direct` join actually been used and haven't felt back to hash? You may try with to force `join_algorithm = 'direct'` or check logs for `HashJoin` lines

**Comment by canhld94** [comment]
> Have `direct` join actually been used and haven't felt back to hash? You may try with to force `join_algorithm = 'direct'` or check logs for `HashJoin` lines

It's using hash join.

I upload the diff flamegraph here.

https://www.dropbox.com/scl/fi/xjfqhnh3s7p289bdausdu/diff.svg?rlkey=ymnw1g8cowbjut56cr0ipmb9l&dl=0

**Comment by canhld94** [comment]
<img width="1193" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/22796953/b1a8d0a2-6e42-4b75-ae84-d76e775cbc18">

**Comment by canhld94** [comment]
@vdimir I think I found the issue here.. When getting the `HashJoin` object from `StorageJoin`, it will construct the cloned `HashJoin` object with `getRightSampleBlock()`, which basically include every columns in the storage join except for the key.

https://github.com/ClickHouse/ClickHouse/blob/e71f20891f37e0462f6832c440a63ff70495bbd3/src/Storages/StorageJoin.cpp#L241

So even if we only select 1 columns in the storage join with direct join, the hash join will try to join all columns, which make the cost of `joinRightColumns` much bigger than `joinGet` if we have many columns in the storage join (yes, it's our case...)

Will create a fix PR.
