### ISSUE TITLE
How to imple json_Object function in clickhouse

### ISSUE THREAD

**Issue by RyanOvO** [ClickHouse/ClickHouse#52967]
i had some data like this:
![1](https://github.com/ClickHouse/ClickHouse/assets/31231960/7d56b715-36c2-4561-8356-fe30bc08999c)

and i want input like this:

|id |  infos |
|1  |  {"rid":"111","groupCode":"111","name":"333","jobNumber":"11","studyNumber":"111"}  |
....

the infos is a json type field，store other field value as json.
i use json_object in mysql imple ,but how to imple this function in clickhouse?
this is my mysql sql:
![2](https://github.com/ClickHouse/ClickHouse/assets/31231960/39f8365a-4a78-432d-a987-5115dfd1a616)

so ,how can i do?
thanks!

**Comment by mkmkme** [comment]
Hey @RyanOvO,

One way to do that is to use `toJSONString(map())`, but in this case you'll have to cast all non-string values to strings:

```
mikhails-macbook-pro.local :) select id, toJSONString(map('rid', toString(rid), 'groupCode', toString(groupCode), 'name', name, 'jobNumber', toString(jobNumber),  'studyNumber', toString(studyNumber))) as json from students

SELECT
    id,
    toJSONString(map('rid', toString(rid), 'groupCode', toString(groupCode), 'name', name, 'jobNumber', toString(jobNumber), 'studyNumber', toString(studyNumber))) AS json
FROM students

Query id: a0c9424e-82d2-47e8-916b-e06aa1cc1d04

┌─id─┬─json────────────────────────────────────────────────────────────────────────────────────────┐
│ 96 │ {"rid":"104","groupCode":"1","name":"Foo","jobNumber":"697777","studyNumber":"3643466666"}  │
│ 97 │ {"rid":"105","groupCode":"1","name":"Bar","jobNumber":"697777","studyNumber":"3643466666"}  │
│ 98 │ {"rid":"106","groupCode":"1","name":"Baz","jobNumber":"697777","studyNumber":"3643466666"}  │
│ 99 │ {"rid":"107","groupCode":"1","name":"Quux","jobNumber":"697777","studyNumber":"3643466666"} │
└────┴─────────────────────────────────────────────────────────────────────────────────────────────┘

4 rows in set. Elapsed: 0.184 sec.
```

May I ask what's your use case for such a format?

**Comment by RyanOvO** [comment]
> Hey @RyanOvO,
> 
> One way to do that is to use `toJSONString(map())`, but in this case you'll have to cast all non-string values to strings:
> 
> ```
> mikhails-macbook-pro.local :) select id, toJSONString(map('rid', toString(rid), 'groupCode', toString(groupCode), 'name', name, 'jobNumber', toString(jobNumber),  'studyNumber', toString(studyNumber))) as json from students
> 
> SELECT
>     id,
>     toJSONString(map('rid', toString(rid), 'groupCode', toString(groupCode), 'name', name, 'jobNumber', toString(jobNumber), 'studyNumber', toString(studyNumber))) AS json
> FROM students
> 
> Query id: a0c9424e-82d2-47e8-916b-e06aa1cc1d04
> 
> ┌─id─┬─json────────────────────────────────────────────────────────────────────────────────────────┐
> │ 96 │ {"rid":"104","groupCode":"1","name":"Foo","jobNumber":"697777","studyNumber":"3643466666"}  │
> │ 97 │ {"rid":"105","groupCode":"1","name":"Bar","jobNumber":"697777","studyNumber":"3643466666"}  │
> │ 98 │ {"rid":"106","groupCode":"1","name":"Baz","jobNumber":"697777","studyNumber":"3643466666"}  │
> │ 99 │ {"rid":"107","groupCode":"1","name":"Quux","jobNumber":"697777","studyNumber":"3643466666"} │
> └────┴─────────────────────────────────────────────────────────────────────────────────────────────┘
> 
> 4 rows in set. Elapsed: 0.184 sec.
> ```
> 
> May I ask what's your use case for such a format?

oh, that's what i want.
thanks a lot.

**Comment by mkmkme** [comment]
@RyanOvO I'm glad I could help :) Do you mind closing the issue if this is resolved for you?

**Comment by RyanOvO** [comment]
> @RyanOvO I'm glad I could help :) Do you mind closing the issue if this is resolved for you?

ok，thanks again!
