### ISSUE TITLE
Is it possible to omit user and password when creating a dictionary with current ClickHouse instance as source?

### ISSUE THREAD

**Issue by jptx1234** [ClickHouse/ClickHouse#52972]
When creating a `dictionary` and setting `source` to clickhouse table, `user` and `password` must be specified.
Is it possible to omit user and password when creating a dictionary with current ClickHouse instance as source? 

For example.

```sql
CREATE DICTIONARY dict_states
(
    `name` String,
    `code` String
)
PRIMARY KEY name
SOURCE(CLICKHOUSE(
    -- connect to current clickhouse without user and password
    db 'default'
    table 'my_state'
))
LAYOUT(...)
LIFETIME(...)
;
```

**Comment by UnamedRus** [comment]
>  Is it possible to omit user and password when creating a dictionary with current ClickHouse instance as source?

Only if default user / empty password is not modified. 
BTW, you can look into named collections, they also help with hiding of creds.

**Comment by melvynator** [comment]
Thanks for answering @UnamedRus .
