### ISSUE TITLE
Inserting as pandas dataframe in clickhouse

### ISSUE THREAD

**Issue by Shisir99** [ClickHouse/ClickHouse#52980]
I want to insert data into nested table using pandas df but unable to do so. Please suggest something.
![Screenshot from 2023-08-03 16-15-16](https://github.com/ClickHouse/ClickHouse/assets/43596686/c47e7720-a52d-482d-b522-e9ae8c58c1f5)

**Comment by alexey-milovidov** [comment]
Could you please provide an explanation, and the steps to check, in plaintext?
