### ISSUE TITLE
Error(Part directory doesn't exist) in ClickHouse Service Startup

### ISSUE THREAD

**Issue by kkkaaa2010** [ClickHouse/ClickHouse#52986]
Hello, the version of ClickHouse I am using is 21.8.15.

Previously, the CH service was running fine, but suddenly an exception occurred.

Even after attempting to restart the service, CH keeps crashing and fails to start.

The error log is as follows:

```
Part directory /data0/clickhouse/01/store/0f/0df7521e-9097-479a-8df7-521e9097a79a/20230719_5265_5311_8_5868/ doesn't exist.
Most likely, it is a logical error:
Cannot attach table "geye.hw" from metadata file /data0/clickhouse/01/store/f31/F315f7bI-9b33-43el-b315-f7b19b3383e1/hw.sql
from query ATTACH TABLE geye.hw UUID 'df7521e-9097-479a-8df7-521e9097a79a'
```

However, the directory `20230719_5265_5311_8_5868` does exist in the system. I am not sure about the cause of this problem.

Looking forward to your response!

**Comment by tavplubix** [comment]
Version 21.8 is too old, you should upgrade to a supported version. We had some fixes for "Part directory doesn't exist" a long time ago: https://github.com/ClickHouse/ClickHouse/pull/34876, https://github.com/ClickHouse/ClickHouse/pull/40031

Also, somthing is wrong with paths you shared above:
`.../store/0f/0df7521e...` - should have been `.../store/0df/0df7521e...`
`.../store/f31/F315f7bI...` - there's no way it could contain capital `F` and `I`

**Comment by kkkaaa2010** [comment]
> Version 21.8 is too old, you should upgrade to a supported version. We had some fixes for "Part directory doesn't exist" a long time ago: #34876, #40031
> 
> Also, somthing is wrong with paths you shared above: `.../store/0f/0df7521e...` - should have been `.../store/0df/0df7521e...` `.../store/f31/F315f7bI...` - there's no way it could contain capital `F` and `I`

--- --- ---

@tavplubix 

Apologies for the confusion. I captured the logs by taking screenshots in the internal environments, and then copied them. There might be some errors in the letters. I have checked again and made corrections.

Here is the corrected log:

```
Part directory /data0/clickhouse/01/store/0df/0df752le-9097-479a-8df7-52le9097a79a/20230719_5265_5311_8_5868/ doesn't exist. 
Most likely it is a logical error.: 
Cannot attach table "geye'.'hw' from metadata file /data0/clickhouse/01/store/f31/f315f7b1-9b33-43el-b315-f7b19b3383e1/hw.sql
from query ATTACH TABLE geye.hw UUID '0df752le-9097-479a-8df7-52le9097a79a'
```

Upon reviewing the previous fix history, this error occurs during too slow INSERT or too long merge/mutation.

However, does it impact the startup of ClickHouse and cause the entire service to crash?

Besides upgrading the ClickHouse version(I am aware that my version is too old), but upgrading would require testing certain functionalities, which would incur high costs.

Are there any other ways to resolve this issue, such as manually deleting internal files?

**Comment by kkkaaa2010** [comment]
> The relevant code was rewritten, and the error that you get was removed a long time ago: #38531 You should upgrade.

@tavplubix 

Hello, I didn't see this pull(#38531) in the changelog.

I have decided to upgrade my clickhouse.

Which version do I need to upgrade to at least? Version 22.12, is it okay?

**Comment by tavplubix** [comment]
> Version 22.12, is it okay?

No, 22.12 is obsolete too, it's not supported.

The list of supported versions: https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease

See also https://clickhouse.com/docs/knowledgebase/production and https://clickhouse.com/docs/en/operations/update

**Comment by kkkaaa2010** [comment]
@tavplubix Okay, my friend, I really appreciate your help.
