### ISSUE TITLE
Update Poco to introduce URI support for mongo atlas

### ISSUE THREAD

**Issue by manish53** [ClickHouse/ClickHouse#5298]
I have been working on connecting clickhouse with mongo atlas and i found nothing in documentation, so i dig into the code and found that MongoDictionarySource.cpp in dbms folder there is no configuration for uri. 
On more investigating i came to know that clickhouse is using poco c++ project for database connectivity. In clickhouse  submoduled poco's Connection.cpp there is no constructor with uri support but when i go to https://github.com/pocoproject/poco/blob/develop/MongoDB/src/Connection.cpp , i found that Connection.cpp has constructor that support uri. 
Is this updated poco version can be submoduled with clickhouse so that i can make dictionary in clickhouse with mongo atlas?
OR
Is there any release comming where it can be already provided?

**Comment by manish53** [comment]
I've modified it myself. Able to connect atlas with clickhouse. Added updated poco project in contrib path and added securesocketstream implementation in connection.cpp to support ssl enable connection. 
Also added readPreference functionality. To know more please follow pull request section. Patch files are provided there or go to https://github.com/manish53/ClickHouse

**Comment by TimonKK** [comment]
Hi, can you create merge request for ClickHouse with this path?

**Comment by akuzm** [comment]
Updated Poco to 1.9.3.
