### ISSUE TITLE
Some mess in WHERE/PREWHERE with constants

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#52982]
https://pastila.nl/?01482993/f4a9c3123010298618f5e2cc5754f90f

Stumble on this behavior at first here - https://s3.amazonaws.com/clickhouse-test-reports/52950/638182ef34e64177246a9b2602f883336edd2705/stateless_tests__release__analyzer_.html

As a corner case, the combination of `WHERE`/`PREWHERE` with constants works with `TinyLog` but `TinyLog` doesn't support `PREWHERE`

**Comment by Algunenano** [comment]
AFAICS, the the correct behaviour is the one in the new analyzer:
```
SELECT *
FROM xyz_test
PREWHERE 31
WHERE 65432
```

Here the `WHERE` clause is invalid and it should throw (as it happens without PREWHERE).

**Comment by Algunenano** [comment]
The analyzer is correct
