### ISSUE TITLE
entrypoint.sh support for high availability (HA) setup

### ISSUE THREAD

**Issue by aiqency** [ClickHouse/ClickHouse#53012]
I have a script file named `db.sql` mounted at `/docker-entrypoint-initdb.d/` to create a database on a cluster defined in the `remote_servers` configuration of the `HA.xml` file.

**HA.xml:**
```xml
<clickhouse>
    <listen_host>0.0.0.0</listen_host>
    <remote_servers>
        <foo_cluster>
```

**db.sql:**
```sql
CREATE DATABASE foo ON CLUSTER foo_cluster;
```

However, when running the container, I encountered the following error:
```
Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: <ip>:9181
```

After examining the `entrypoint.sh`, it seems that ZooKeeper is not up when the migration is running.

Is there any specific reason why it is not supported yet?

**Comment by aiqency** [comment]
@tavplubix I marked it as a feature because having high availability (HA) for database provisioning would be nice to have, don't you think?

**Comment by tavplubix** [comment]
We already have support for high availability, and there's nothing to do with `entrypoint.sh`.

Your cluster is misconfigured, you need to configure embedded ClickHouse Keeper, see https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper for details

**Comment by alexey-milovidov** [comment]
You can also use ClickHouse without Docker - it is easier: fewer moving parts, less number of concepts to understand, less chances to misconfigure it.

**Comment by aiqency** [comment]
The configuration is fine, and high availability (HA) works well. I am using Clickhouse Keeper. 
The only issue is that running the script inside `/docker-entrypoint-initdb.d/` fails, while running it when the container is up works without any problems.

Waiting for the container to be up before running the script is not ideal for automating the database deployment process.
