### ISSUE TITLE
wrong parts number that lead to ‘Too many part（18446744073709551615）’

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#53048]
version 22.8

logs
com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Too many parts (18446744073709551615) in all partitions in total. This indicates wrong choice of partition key. The threshold can be modified with 'max_parts_in_total' setting in <merge_tree> element in config.xml or with per-table setting.. Stack trace:
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
2. DB::MergeTreeData::delayInsertOrThrowIfNeeded(Poco::Event*, std::__1::shared_ptr<DB::Context const>) const in /usr/bin/clickhouse
3. DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic<unsigned long>*) in /usr/bin/clickhouse
4. DB::ExceptionKeepingTransform::work() in /usr/bin/clickhouse
5. DB::ExecutionThreadContext::executeTask() in /usr/bin/clickhouse
6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) in /usr/bin/clickhouse
7. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) in /usr/bin/clickhouse
8. DB::PushingPipelineExecutor::start() in /usr/bin/clickhouse
9. DB::TCPHandler::processInsertQuery() in /usr/bin/clickhouse
10. DB::TCPHandler::runImpl() in /usr/bin/clickhouse
11. DB::TCPHandler::run() in /usr/bin/clickhouse
12. Poco::Net::TCPServerConnection::start() in /usr/bin/clickhouse
13. Poco::Net::TCPServerDispatcher::run() in /usr/bin/clickhouse
14. Poco::PooledThread::run() in /usr/bin/clickhouse
15. Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse
16. ? in ?
17. clone in ?

**Comment by alexey-milovidov** [comment]
Do you use the official unmodified version of ClickHouse, or something else?
