### ISSUE TITLE
Error(filesystem error: in file_size: Is a directory) reported when querying the table

### ISSUE THREAD

**Issue by kkkaaa2010** [ClickHouse/ClickHouse#53075]
Hello, my clickhouse is running normally, some table queries are working properly, but one of the tables has failed the query.

Error log:

```
Code: 1001. DB::Exception: Received from localhost:9000. DB::Exception: std::__1::__fs::filesystem::filesystem_error: 
filesystem error: in file_size: Is a directory [/data0/clickhouse/01/store/0df/0df752le-9097-479a-8df7-52le9097a79a/20230719_5265_5311_8_5868/event_dns_tti.mrk2]
```

I checked this mrk2, it is a file, not a folder.

What is the reason for it? Looking forward to your reply.

**Comment by alexey-milovidov** [comment]
This is likely a bug or hardware failure in the underlying filesystem (Linux kernel).
What filesystem do you use, and what is your Linux kernel version?

**Comment by kkkaaa2010** [comment]
> What filesystem do you use, and what is your Linux kernel version?

1. `cat /etc/redhat-release`

```
CentOS Linux release 7.6.1810 (Core)
```

2. `cat /proc/version`

```
Linux version 3.10.0-957.5.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Fri Feb 1 14:54:57 UTC 2019
```

**Comment by alexey-milovidov** [comment]
This Linux Kernel is outdated.
