### ISSUE TITLE
DB::Exception: unKonw query setting type format_custom_field_delimiter

### ISSUE THREAD

**Issue by beep10** [ClickHouse/ClickHouse#53089]
I used clickhouse client to execute:
clickhouse client -h {ip} -u {user} --password {pwd} --port {port} --query "select {columns} from {table} where 1=1 FORMAT CustomSeparated SETTINGS format_custom_field_delimiter='|', format_custom_row_after_delimiter='|\n'"
the result is:
Received exception from server (version 21.8.0):
Code: 0. DB::Exception from .. unKonw query setting type format_custom_field_delimiter

While I got the correct result using JDBC.

**Comment by alexey-milovidov** [comment]
ClickHouse cannot say `unKonw`.
You either have your own modified build of ClickHouse or a bug in your infrastructure.
It is also possible that you have an error while copy-pasting.
By the way, version 21.8 is outdated.

**Comment by alexey-milovidov** [comment]
It is also not possible that ClickHouse gives you `Code: 0.`
You are using a cheap ClickHouse clone instead of our favorite original ClickHouse :(
