### ISSUE TITLE
limit clause not sent with odbc() CH 19.6.2.11 

### ISSUE THREAD

**Issue by Schaefer-Thomas** [ClickHouse/ClickHouse#5309]
Hi,

**limit** clause seems not to be sent over odbc to remote db, for example with:
`select * from odbc('DSN=psql', 'myschema', 'fact_table') limit 2;`

Query takes quite long on big tables and limit clause does not show up in remote db's-statement-log.

**where** clause works and ist fast:
`select * from odbc('DSN=psql', 'myschema', 'fact_table') where sid=248135;`

Cheers!

**Comment by alexey-milovidov** [comment]
Implementation:
`transformQueryForExternalDatabase.h`
`transformQueryForExternalDatabase.cpp`

**Comment by alexey-milovidov** [comment]
The LIMIT clause can be sent to the remote database only in very limited cases.

When query does not have:
- any incompatible functions in WHERE;
- GROUP BY;
- DISTINCT;
- ORDER BY;
- HAVING;
- ARRAY JOIN or arrayJoin function;
- JOIN;
- LIMIT BY;
- WITH TIES / WITH FILL (upcoming feature).

So, if it is just a plain query as in your example, we can sent LIMIT to the remote database.

Now we does not send LIMIT. But if the remote database and its ODBC driver can send query results in a streaming fashion, we will stop after receiving the required amount of rows.

**Comment by alexey-milovidov** [comment]
Note that many DBMS don't support LIMIT clause.
Notable examples are MS SQL Server (that has `SELECT TOP N` instead) and Oracle.

We must check if there is a method in ODBC interface to check the support for LIMIT.

And the SQL standard does not have LIMIT.

https://stackoverflow.com/questions/1528604/how-universal-is-the-limit-statement-in-sql
https://en.wikipedia.org/wiki/Select_(SQL)#Limiting_result_rows

**Comment by alexey-milovidov** [comment]
I cannot find the corresponding method in ODBC interface:
https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function

**Comment by alexey-milovidov** [comment]
We can only make a whitelist of DBMS that have support for LIMIT.

**Comment by ocmajortom** [comment]
Wow, exhaustive answer. 
Thank you, Alexey! :1st_place_medal: 

p.s.
think I should do more research before posting here
