### ISSUE TITLE
Let's make DatabaseFilesystem/S3/HDFS support globs

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#53094]
**Use case**

I can write:
```
SELECT * FROM file('*.jsonl')
```

And I can also use the default overlay Filesystem database in clickhouse-local, but only for single files:
```
SELECT * FROM 'test.jsonl'
```

I want to use it with globs as well:
```
SELECT * FROM '*.jsonl'
```

**Comment by Demilivor** [comment]
Please assign me to this task; I'm going to start working on it soon.

@alexey-milovidov
Could you please clarify the task a bit?
[S3 ](https://clickhouse.com/docs/en/sql-reference/table-functions/s3) already supports globs.
[HDFS](https://clickhouse.com/docs/en/engines/table-engines/integrations/hdfs) also supports globs.

Do I need to change something in clickhouse-local related to S3/HDFS? Or maybe I just need to make this case work?
```sql
SELECT * FROM 'FILE_NAME
```
