### ISSUE TITLE
TRUNCATE DATABASE

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#53093]
**Use case**

I can do DROP DATABASE and CREATE DATABASE, but I don't want any moment of time when there is no database.

```
clickhouse client --host example.us-east-2.aws.clickhouse-staging.com --secure --password --query "SHOW TABLES" | xargs -I{} clickhouse client --host example.us-east-2.aws.clickhouse-staging.com --secure --password --query "DROP TABLE {}" --echo
```

**Describe the solution you'd like**

The statement `TRUNCATE DATABASE` works similarly to `DROP DATABASE`, but it does not remove the database after dropping all the tables.

**Comment by bharatnc** [comment]
Can I take this?

**Comment by alexey-milovidov** [comment]
@bharatnc Yes, thank you!
