### ISSUE TITLE
Array Of Random Numbers (In a Given Range of N , M)

### ISSUE THREAD

**Issue by saifamp** [ClickHouse/ClickHouse#53098]
Can we please add a feature for generating random arrays. 

I was wondering something like: `generateRandomIntArray(N, M, K)` where `N` is start, `M` is end and `K` is the size of the array.  

Additionally, can we also add a random sampler for existing arrays. Something like: `randomSampleFromArray(<Array>, K)` where `K` is the number of samples to get.

**Comment by UnamedRus** [comment]
> Additionally, can we also add a random sampler for existing arrays. Something like: randomSampleFromArray(<Array>, K) where K is the number of samples to get.

There is groupArraySample function, but it's aggregation

Still, you can use it via arrayReduce.

```
SELECT arrayReduce('groupArraySample(3)', range(10))

Query id: 3a7798d7-a465-4f4f-8185-909e5dcd30c5

┌─arrayReduce('groupArraySample(3)', range(10))─┐
│ [9,1,2]                                       │
└───────────────────────────────────────────────┘
```

**Comment by itayisraelov** [comment]
Hey @KochetovNicolai,

`randomSampleFromArray(<Array>, K) `can get an array of arrays?
If yes, what will be the result in this case:

`select randomSampleFromArray([[1,2,3], [5,6], [7,9]], 2);`
[2,5] or [1,2,3] && [7,9]
?

**Comment by itayisraelov** [comment]
I will implement the basic case that the array only contains int32, and if needed, I will extend it in the future.
