### ISSUE TITLE
After trying async insert, spamming log: DB::Exception: No chunk info for async inserts.

### ISSUE THREAD

**Issue by gpa-actirise** [ClickHouse/ClickHouse#53105]
**Describe the unexpected behaviour**

On the LTS 23.3 version, I wanted to test the "async insert" feature on a cluster that was by default in "sync insert" mode. The test did not go as planned, and we encountered several errors in the logs. Therefore, we reverted the cluster back to "sync insert" mode. However, since this test, Clickhouse seems to be endlessly retrying to insert pending data, and it's not working. I keep getting an error in a loop.

**Expected behavior**

How I can clear async insert pipeline to remove spamming log ?

**Error message and/or stacktrace**
```DB::Exception: No chunk info for async inserts. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe1e20b5 in /usr/bin/clickhouse
1. ? @ 0xceeebb6 in /usr/bin/clickhouse
2. DB::ReplicatedMergeTreeSinkImpl<true>::consume(DB::Chunk) @ 0x147ff1f8 in /usr/bin/clickhouse
3. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x14ce3022 in /usr/bin/clickhouse
4. ? @ 0x14c1318b in /usr/bin/clickhouse
5. ? @ 0x14c12ed9 in /usr/bin/clickhouse
6. DB::ExceptionKeepingTransform::work() @ 0x14c127bf in /usr/bin/clickhouse
7. DB::ExecutionThreadContext::executeTask() @ 0x14a2e70a in /usr/bin/clickhouse
8. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14a2377b in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x14a22b68 in /usr/bin/clickhouse
10. DB::TCPHandler::processInsertQuery() @ 0x149d2818 in /usr/bin/clickhouse
11. DB::TCPHandler::runImpl() @ 0x149c9c38 in /usr/bin/clickhouse
12. DB::TCPHandler::run() @ 0x149df159 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0x17919874 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0x1791aa9b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0x17aa2327 in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0x17a9fd5d in /usr/bin/clickhouse
17. ? @ 0x7f225b3fa609 in ?
18. clone @ 0x7f225b31f133 in ?
: While sending /var/lib/clickhouse/store/c7c/c7ca4f6b-fd28-4039-ae84-fe5a62faab21/shard3_all_replicas/1.bin. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe22f215 in /usr/bin/clickhouse
1. ? @ 0xe29209f in /usr/bin/clickhouse
2. DB::Connection::receiveException() const @ 0x149b1985 in /usr/bin/clickhouse
3. DB::Connection::receivePacket() @ 0x149b9c6d in /usr/bin/clickhouse
4. DB::RemoteInserter::onFinish() @ 0x144d91f5 in /usr/bin/clickhouse
5. DB::DistributedAsyncInsertDirectoryQueue::processFile(String const&) @ 0x144d3a95 in /usr/bin/clickhouse
6. DB::DistributedAsyncInsertDirectoryQueue::processFiles() @ 0x144ccc29 in /usr/bin/clickhouse
7. DB::DistributedAsyncInsertDirectoryQueue::run() @ 0x144cd1d8 in /usr/bin/clickhouse
8. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x1288df06 in /usr/bin/clickhouse
9. DB::BackgroundSchedulePool::threadFunction() @ 0x12890dea in /usr/bin/clickhouse
10. ? @ 0x12891c2e in /usr/bin/clickhouse
11. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe2fe553 in /usr/bin/clickhouse
12. ? @ 0xe3041c1 in /usr/bin/clickhouse
13. ? @ 0x7f8b3287d609 in ?
14. __clone @ 0x7f8b327a2133 in ?
 (version 23.3.8.21 (official build))
```

**Comment by tavplubix** [comment]
cc: @hanfei1991

**Comment by hanfei1991** [comment]
1. may I ask what table engine did you use and what are the inserts like? 
2. `we reverted the cluster back to "sync insert" mode` how did you do this?

**Comment by gpa-actirise** [comment]
1. ReplicatedMergThree et ReplicatedSummingMergeThree on cluster.
2. By settings : 

``
      default/async_insert_deduplicate: 1
      default/async_insert: 1
      default/async_insert_threads: 2
      default/wait_for_async_insert: 1

``
3. Just back setting  default/async_insert: 1 to  default/async_insert: 0

**Comment by gpa-actirise** [comment]
> How does your insert query look like?

Not easy to answer... Our actual pipeline are based on logstash plugin https://github.com/funcmike/logstash-output-clickhouse, simply bucket insert of multiple values.

Your fix has been backported to current lts ?

**Comment by hanfei1991** [comment]
> 

Not yet backported. Would you patch this fix or upgrade the server?

**Comment by antonio2368** [comment]
It's not backported as @hanfei1991 said
but it's still interesting because the query is `/?query=INSERT%20INTO%20#{table}%20FORMAT%20JSONEachRow` (based on https://github.com/funcmike/logstash-output-clickhouse/blob/master/lib/logstash/outputs/clickhouse.rb#L76C20-L76C75) and I'm not sure yet if it's connected.

**Comment by gpa-actirise** [comment]
Ok, I'll try upgrading to version 23.7 on the sandbox cluster.

I can confirm that the error has disappeared. ;) I will retry testing async insert with this version.

For production, I'll wait for the next LTS release this month. Thanks a lot.

**Comment by gpa-actirise** [comment]
How, now async insert work in this release on our case ;)

```
2023.08.07 14:36:12.134294 [ 362 ] {} <Information> AsynchronousInsertQueue: Flushed 3 rows, 3971 bytes for query 'INSERT INTO ... FORMAT JSONEachRow'
2023.08.07 14:36:12.155842 [ 372 ] {} <Information> AsynchronousInsertQueue: Flushed 272 rows, 254835 bytes for query 'INSERT INTO ... FORMAT JSONEachRow'
```
