### ISSUE TITLE
DB::Exception: Unexpected packet Data received from client

### ISSUE THREAD

**Issue by wineternity** [ClickHouse/ClickHouse#53114]
> You have to provide the following information whenever possible.

**Describe what's wrong**
Sometimes the sql execute with error : "ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 101, host: [clickhouse.s.qima-inc.com](http://clickhouse.s.qima-inc.com/), port: 80; Code: 101, e.displayText() = DB::Exception: Received from bj5-prod-clickhouse101:9000. DB::Exception: Unexpected packet Data received from client. (version [20.8.18.32](http://20.8.18.32/) (official build))"

The sql is simple :
`select max(version) from ma_crm.generic_crowd_dist where crowd_key = 'cdp_21121_26881_50f931ab-8915-4e18-82a5-d091afbb017b_1691348312371'`

It seems in the logs that tcp start error occurred when execute sub query, why it happened and is there any way to avoid it?

**Does it reproduce on recent release?**
not sure

**How to reproduce**
not sure, it random occurred sometime

* Which ClickHouse server version to use
20.8.18 revision 54438
* Which interface to use, if matters

* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

select correct

**Error message and/or stacktrace**
`
2023.08.07 02:58:35.300302 [ 22077 ] {6f71f386-d5b6-4277-87ad-07087e202f06} <Error> executeQuery: Code: 101, e.displayText() = DB::Exception: Received from bj5-prod-clickhouse101:9000. DB::Exception: Unexpected packet Data received from client. Stack trace:

0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cda190 in /usr/lib/debug/usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:37: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63333d in /usr/lib/debug/usr/bin/clickhouse
2. /build/obj-x86_64-linux-gnu/../src/Common/NetException.h:12: DB::TCPHandler::receiveUnexpectedData() @ 0x163a2519 in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:813: ? @ 0x163a4c11 in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:177: DB::TCPHandler::runImpl() @ 0x163a61cf in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1219: DB::TCPHandler::run() @ 0x163a7070 in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x18bf7e5b in /usr/lib/debug/usr/bin/clickhouse
7. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: Poco::Net::TCPServerDispatcher::run() @ 0x18bf83e8 in /usr/lib/debug/usr/bin/clickhouse
8. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/Mutex_POSIX.h:59: Poco::PooledThread::run() @ 0x18d76ed6 in /usr/lib/debug/usr/bin/clickhouse
9. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/AutoPtr.h:223: Poco::ThreadImpl::runnableEntry(void*) @ 0x18d722d0 in /usr/lib/debug/usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe96d in /usr/lib64/libc-2.17.so
: While executing Remote (version 20.8.18.32 (official build)) (from 10.97.130.60:33172) (in query: select max(version) from ma_crm.generic_crowd_dist where crowd_key = 'cdp_21121_26881_50f931ab-8915-4e18-82a5-d091afbb017b_1691348312371' FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cda190 in /usr/lib/debug/usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:37: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63333d in /usr/lib/debug/usr/bin/clickhouse
2. /build/obj-x86_64-linux-gnu/../src/IO/WriteBufferFromVector.h:70: DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe67298f in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3028: DB::Connection::receiveException() @ 0x1630ca2f in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2587: DB::Connection::getTablesStatus(DB::ConnectionTimeouts const&, DB::TablesStatusRequest const&) @ 0x1630fcad in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/unordered_map:1278: DB::ConnectionPoolWithFailover::tryGetEntry(DB::IConnectionPool&, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::Settings const*, DB::QualifiedTableName const*) @ 0x1632649b in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&), std::__1::allocator<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>::operator()(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x163271ea in /usr/lib/debug/usr/bin/clickhouse
7. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:4081: PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x1632d590 in /usr/lib/debug/usr/bin/clickhouse
8. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1825: DB::ConnectionPoolWithFailover::getManyImpl(DB::Settings const*, DB::PoolMode, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&) @ 0x163275eb in /usr/lib/debug/usr/bin/clickhouse
9. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1825: DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&) @ 0x16327cf3 in /usr/lib/debug/usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe96d in /usr/lib64/libc-2.17.so
: While executing Remote (version 20.8.18.32 (official build)) (from 10.97.130.60:33172) (in query: select max(version) from ma_crm.generic_crowd_dist where crowd_key = 'cdp_21121_26881_50f931ab-8915-4e18-82a5-d091afbb017b_1691348312371' FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):

0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cda190 in /usr/lib/debug/usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:37: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63333d in /usr/lib/debug/usr/bin/clickhouse
2. /build/obj-x86_64-linux-gnu/../src/IO/WriteBufferFromVector.h:70: DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe67298f in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3028: DB::Connection::receiveException() @ 0x1630ca2f in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2587: DB::Connection::getTablesStatus(DB::ConnectionTimeouts const&, DB::TablesStatusRequest const&) @ 0x1630fcad in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/unordered_map:1278: DB::ConnectionPoolWithFailover::tryGetEntry(DB::IConnectionPool&, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::Settings const*, DB::QualifiedTableName const*) @ 0x1632649b in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&), std::__1::allocator<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>::operator()(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x163271ea in /usr/lib/debug/usr/bin/clickhouse
7. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:4081: PoolWithFailoverBase<DB::IConnectionPool>::getMany(unsigned long, unsigned long, unsigned long, unsigned long, bool, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&, std::__1::function<unsigned long (unsigned long)> const&) @ 0x1632d590 in /usr/lib/debug/usr/bin/clickhouse
8. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1825: DB::ConnectionPoolWithFailover::getManyImpl(DB::Settings const*, DB::PoolMode, std::__1::function<PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)> const&) @ 0x163275eb in /usr/lib/debug/usr/bin/clickhouse
9. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1825: DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&) @ 0x16327cf3 in /usr/lib/debug/usr/bin/clickhouse
10. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2134: std::__1::__function::__func<DB::RemoteQueryExecutor::RemoteQueryExecutor(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, DB::Context const&, DB::Settings const*, std::__1::shared_ptr<DB::Throttler> const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::Block, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::Block> > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IStorage>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<DB::IStorage> > > > const&, DB::QueryProcessingStage::Enum)::'lambda'(), std::__1::allocator<DB::RemoteQueryExecutor::RemoteQueryExecutor(std::__1::shared_ptr<DB::ConnectionPoolWithFailover> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Block const&, DB::Context const&, DB::Settings const*, std::__1::shared_ptr<DB::Throttler> const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::Block, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, DB::Block> > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IStorage>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<DB::IStorage> > > > const&, DB::QueryProcessingStage::Enum)::'lambda'()>, std::__1::unique_ptr<DB::MultiplexedConnections, std::__1::default_delete<DB::MultiplexedConnections> > ()>::operator()() @ 0x15577204 in /usr/lib/debug/usr/bin/clickhouse
11. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2608: DB::RemoteQueryExecutor::sendQuery() @ 0x1557a3b8 in /usr/lib/debug/usr/bin/clickhouse
12. /build/obj-x86_64-linux-gnu/../src/Processors/Sources/RemoteSource.cpp:52: DB::RemoteSource::generate() @ 0x16614e91 in /usr/lib/debug/usr/bin/clickhouse
13. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:1003: DB::ISource::work() @ 0x163ed3bb in /usr/lib/debug/usr/bin/clickhouse
14. /build/obj-x86_64-linux-gnu/../src/Processors/Sources/SourceWithProgress.cpp:38: DB::SourceWithProgress::work() @ 0x1661b3b7 in /usr/lib/debug/usr/bin/clickhouse
15. /build/obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:90: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::'lambda'(), std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::'lambda'()>, void ()>::operator()() @ 0x16422b40 in /usr/lib/debug/usr/bin/clickhouse
16. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:180: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) (.constprop.1) @ 0x16426e1d in /usr/lib/debug/usr/bin/clickhouse
17. /build/obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:729: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::'lambda0'()>(DB::PipelineExecutor::executeImpl(unsigned long)::'lambda0'()&&)::'lambda'()::operator()() const @ 0x16427746 in /usr/lib/debug/usr/bin/clickhouse
18. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe660ba7 in /usr/lib/debug/usr/bin/clickhouse
19. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xe65f093 in /usr/lib/debug/usr/bin/clickhouse
20. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
21. clone @ 0xfe96d in /usr/lib64/libc-2.17.so

2023.08.07 02:58:35.302467 [ 22077 ] {6f71f386-d5b6-4277-87ad-07087e202f06} <Error> DynamicQueryHandler: Code: 101, e.displayText() = DB::Exception: Received from bj5-prod-clickhouse101:9000. DB::Exception: Unexpected packet Data received from client. Stack trace:

0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cda190 in /usr/lib/debug/usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:37: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63333d in /usr/lib/debug/usr/bin/clickhouse
2. /build/obj-x86_64-linux-gnu/../src/Common/NetException.h:12: DB::TCPHandler::receiveUnexpectedData() @ 0x163a2519 in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:813: ? @ 0x163a4c11 in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:177: DB::TCPHandler::runImpl() @ 0x163a61cf in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../src/Server/TCPHandler.cpp:1219: DB::TCPHandler::run() @ 0x163a7070 in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x18bf7e5b in /usr/lib/debug/usr/bin/clickhouse
7. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: Poco::Net::TCPServerDispatcher::run() @ 0x18bf83e8 in /usr/lib/debug/usr/bin/clickhouse
8. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/Mutex_POSIX.h:59: Poco::PooledThread::run() @ 0x18d76ed6 in /usr/lib/debug/usr/bin/clickhouse
9. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/include/Poco/AutoPtr.h:223: Poco::ThreadImpl::runnableEntry(void*) @ 0x18d722d0 in /usr/lib/debug/usr/bin/clickhouse
10. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
11. clone @ 0xfe96d in /usr/lib64/libc-2.17.so
: While executing Remote, Stack trace (when copying this message, always include the lines below):

0. /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cda190 in /usr/lib/debug/usr/bin/clickhouse
1. /build/obj-x86_64-linux-gnu/../src/Common/Exception.cpp:37: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63333d in /usr/lib/debug/usr/bin/clickhouse
2. /build/obj-x86_64-linux-gnu/../src/IO/WriteBufferFromVector.h:70: DB::readException(DB::ReadBuffer&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xe67298f in /usr/lib/debug/usr/bin/clickhouse
3. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:3028: DB::Connection::receiveException() @ 0x1630ca2f in /usr/lib/debug/usr/bin/clickhouse
4. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2587: DB::Connection::getTablesStatus(DB::ConnectionTimeouts const&, DB::TablesStatusRequest const&) @ 0x1630fcad in /usr/lib/debug/usr/bin/clickhouse
5. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/unordered_map:1278: DB::ConnectionPoolWithFailover::tryGetEntry(DB::IConnectionPool&, DB::ConnectionTimeouts const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, DB::Settings const*, DB::QualifiedTableName const*) @ 0x1632649b in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&), std::__1::allocator<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>::operator()(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x163271ea in /usr/lib/debug/usr/bin/clickhouse
6. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/functional:1714: std::__1::__function::__func<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&), std::__1::allocator<DB::ConnectionPoolWithFailover::getManyChecked(DB::ConnectionTimeouts const&, DB::Settings const*, DB::PoolMode, DB::QualifiedTableName const&)::'lambda'(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>, PoolWithFailoverBase<DB::IConnectionPool>::TryResult (DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)>::operator()(DB::IConnectionPool&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) @ 0x163271ea in /usr/lib/debug/usr/bin/clickhouseuild/obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:1003: DB::ISource::work() @ 0x163ed3bb in /usr/lib/debug/usr/bin/clickhouse
14. /build/obj-x86_64-linux-gnu/../src/Processors/Sources/SourceWithProgress.cpp:38: DB::SourceWithProgress::work() @ 0x1661b3b7 in /usr/lib/debug/usr/bin/clickhouse
15. /build/obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:90: std::__1::__function::__func<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::'lambda'(), std::__1::allocator<DB::PipelineExecutor::addJob(DB::ExecutingGraph::Node*)::'lambda'()>, void ()>::operator()() @ 0x16422b40 in /usr/lib/debug/usr/bin/clickhouse
16. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/exception:180: DB::PipelineExecutor::executeStepImpl(unsigned long, unsigned long, std::__1::atomic<bool>*) (.constprop.1) @ 0x16426e1d in /usr/lib/debug/usr/bin/clickhouse
17. /build/obj-x86_64-linux-gnu/../src/Processors/Executors/PipelineExecutor.cpp:729: ThreadFromGlobalPool::ThreadFromGlobalPool<DB::PipelineExecutor::executeImpl(unsigned long)::'lambda0'()>(DB::PipelineExecutor::executeImpl(unsigned long)::'lambda0'()&&)::'lambda'()::operator()() const @ 0x16427746 in /usr/lib/debug/usr/bin/clickhouse
18. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/atomic:856: ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe660ba7 in /usr/lib/debug/usr/bin/clickhouse
19. /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/memory:2615: void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()> >(void*) @ 0xe65f093 in /usr/lib/debug/usr/bin/clickhouse
20. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
21. clone @ 0xfe96d in /usr/lib64/libc-2.17.so
 (version 20.8.18.32 (official build))
2023.08.07 02:58:36.066606 [ 17441 ] {54eaff79-40d3-47a3-9931-23816e1a6957} <Warning> ConnectionPoolWithFailover: There is no table `ma_crm`.`component_reach_user_local` on server: bj5-prod-clickhouse101:9000
2023.08.07 02:58:36.211704 [ 17415 ] {16f29016-7c64-4508-a0c7-8f981ecf7234} <Warning> ConnectionPoolWithFailover: There is no table `cdp`.`shop_user_behavior_detail_local` on server: bj5-prod-clickhouse101:9000
2023.08.07 02:58:36.739939 [ 17297 ] {21867c22-7326-45e0-8895-cbccd9111df7} <Warning> ConnectionPoolWithFailover: There is no table `ma_crm`.`component_reach_user_local` on server: bj5-prod-clickhouse101:9000
2023.08.07 02:58:36.743307 [ 4295 ] {21867c22-7326-45e0-8895-cbccd9111df7} <Warning> ConnectionPoolWithFailover: There is no table `ma_crm`.`notice_user_crowd_local` on server: bj5-prod-clickhouse101:9000
2023.08.07 02:58:40.423719 [ 17410 ] {abfdfb3a-aa29-4c4e-85cd-301d171b94d4} <Warning> ConnectionPoolWithFailover: There is no table `ma_crm`.`generic_crowd_local` on server: bj5-prod-clickhouse101:9000
2023.08.07 02:58:45.244273 [ 15336 ] {40c3c77b-2b86-4e4f-9b79-a2837c9db2da} <Warning> ConnectionPoolWithFailover: There is no table `cdp`.`shop_user_attr_realtime_detail_local` on server: bj5-prod-clickhouse101:9000
2023.08.07 02:58:45.570653 [ 28990 ] {ca03b99d-4bf9-469c-b061-d7838b86ec84} <Warning> ConnectionPoolWithFailover: There is no table `ma_crm`.`generic_crowd_local` on server: bj5-prod-clickhouse101:9000
2023.08.07 02:58:46.642593 [ 22195 ] {3a05dd9e-ab8b-43f7-a8b2-25d39c5d8985} <Error> executeQuery: Code: 100, e.displayText() = DB::Exception: Unknown packet 9 from server bj5-prod-clickhouse101:9000: While executing Remote (version 20.8.18.32 (official build)) (from 10.97.130.80:33124) (in query: select max(version) from ma_crm.generic_crowd_dist where crowd_key = 'cdp_21725_27756_9c06ee82-773a-4c91-8b9c-1fa0702ec254_1691348325538' FORMAT TabSeparatedWithNamesAndTypes;), Stack trace (when copying this message, always include the lines below):
`

**Comment by tavplubix** [comment]
> version 20.8.18.32

This version is obsolete. It was released 3 years ago, and we don't support it for 2 years already. You should upgrade.
