### ISSUE TITLE
CH replicas always fetch partition with ATTACH PARTITION 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#5312]
https://clickhouse.yandex/docs/en/query_language/alter/#alter_attach-partition
Documentation states: This query is replicated. 
Each replica checks whether there is data in the detached directory. 
**If the data is in this directory, the query checks the integrity, verifies that it matches the 
data on the server that initiated the query.** If everything is correct, the query adds data 
to the replica. If not, it downloads data from the query requestor replica, or from another replica where the data has already been added.

This is either a documentation bug or a server bug.

create table XXXX on cluster XXXX (A Int64) 
ENGINE = ReplicatedMergeTree ('/clickhouse/{cluster}/tables/XXXX','{replica}')
order by tuple();
insert into XXXX values(1);

alter table XXXX detach partition tuple();
ls -1 /var/lib/clickhouse/data/dw/XXXX/detached/
**all_0_0_0**

alter table XXXX attach partition tuple();
ls -1 /var/lib/clickhouse/data/dw/XXXX/
**all_2_2_0**

REPLICA
ls -1 /var/lib/clickhouse/data/dw/XXXX/**detached**/
**all_0_0_0**

grep XXXX /var/log/clickhouse-server/clickhouse-server.log

```
<Debug> dw.XXXX (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0000000002 - log-0000000002
<Debug> dw.XXXX (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
<Debug> dw.XXXX (StorageReplicatedMergeTree): Fetching part all_2_2_0 from /clickhouse/oCHDWcsp1/tables/XXXX/replicas/MASTER
<Trace> ReadWriteBufferFromHTTP: Sending request to http://chdw1-1.MASTER.mycmdb.net:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2FoCHDWcsp1%2Ftables%2FXXXX%2Freplicas%2FMASTER&part=all_2_2_0&compress=false
<Trace> dw.XXXX (Data): Renaming temporary part tmp_fetch_all_2_2_0 to all_2_2_0.
<Debug> dw.XXXX (StorageReplicatedMergeTree): Fetched part all_2_2_0 from /clickhouse/oCHDWcsp1/tables/XXXX/replicas/MASTER
```

**Comment by den-crane** [comment]
workaround https://t.me/clickhouse_ru/81231

**Comment by abraithwaite** [comment]
I believe we might be seeing this issue when restoring from backups.

Is there any plan to address it?  Also, Google Translate is not working well for the workaround.  Would someone mind translating it for us please?

**Comment by den-crane** [comment]
It's a documentation issue. ATTACH PARTITION works as designed.

I am not sure that workaround is working.

```
CREATE TABLE dw.test123 on cluster zzzz (x String) ENGINE = ReplicatedMergeTree ('/clickhouse/{cluster}/tables/test','{replica}') ORDER BY x;
insert into test123 values ('x');
alter table test123 detach partition tuple();
```
1. create temporary table with the same structure (columns / order by) and attach data
```
CREATE TABLE dw.test123temp on cluster zzzz (x String) ENGINE = MergeTree  ORDER BY x;

server1
mv /var/lib/clickhouse/data/dw/test123/detached/all_0_0_0 /var/lib/clickhouse/data/dw/test123temp/detached/
alter table test123temp attach  partition tuple();

server2
mv /var/lib/clickhouse/data/dw/test123/detached/all_0_0_0 /var/lib/clickhouse/data/dw/test123temp/detached/
alter table test123temp  attach  partition tuple();
```

2. execute ATTACH PARTITION  ... FROM temporary table
```
server1
alter table test123 ATTACH PARTITION tuple() FROM test123temp
```

**Comment by abraithwaite** [comment]
Good to know!  Thanks for sharing!
