### ISSUE TITLE
Parquet ZSTD broken in 23.7

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#53120]
I write a lot of ZSTD-based Parquet files. I have never noticed this before.

```sql 
SELECT
    SITEID,
    *
FROM file('/huge2/data/aberdeen.usa_2019_productinstall/*parquet', 'Parquet')
GROUP BY ALL

```

Code: 33. DB::ParsingException: Error while reading Parquet data: IOError: ZSTD decompression failed: Restored data doesn't match checksum: While executing ParquetBlockInputFormat: While executing File. (CANNOT_READ_ALL_DATA)

Same thing with DuckDB, Python. I am just using clickhouse-client with the ztd option on. And this. --output_format_parquet_string_as_string=1

**Comment by al13n321** [comment]
Known, fix coming soon: https://github.com/ClickHouse/ClickHouse/pull/53064 , meanwhile use `output_format_parquet_use_custom_encoder=0` (when writing the file) as a workaround.
