### ISSUE TITLE
Kerberos support in Native Protocol

### ISSUE THREAD

**Issue by ekpdt** [ClickHouse/ClickHouse#53132]
**Use case**

Use Kerberos as an authentication mechanism for the Native Protocol.
This is useful in environments where Kerberos is used as an SSO solution but the HTTP protocol is not available (e.g. the command line client) or less efficient (e.g. Grafana, python drivers).

**Describe the solution you'd like**

ClickHouse server supports Kerberos as an authentication mechanism for the Native protocol just at it supports GSS-SPNEGO for the HTTP protocol.

**Describe alternatives you've considered**

- Only use the HTTP protocol: This is not always possible considering incomplete tooling support for this protocol.
- Stop using Kerberos: This is not always practical in enterprise environments.
- Only some clients use Kerberos: ClickHouse does not support this. This also undermines an organization's SSO policy.

**Comment by ilejn** [comment]
https://github.com/arenadata/clickhouse-cpp/tree/ADQM-666 might be useful as a starting point.
This is a prototype that actually works.

**Comment by alexey-milovidov** [comment]
No plans for this.
