### ISSUE TITLE
Clickhouse Unknown column when join with view table

### ISSUE THREAD

**Issue by hohaithuy** [ClickHouse/ClickHouse#53141]
I have met this error when join 2 table together.

But when I run each table single, it's still work

Note that view_raw_log is a view of raw_log. If I change from view to source table the query work correctly. Can anyone tell me why?

Query 2 ERROR: DB::Exception: Unknown column: user_name, there are only columns log_time, user_id

~~~~sql
WITH GoldInOut AS (
	SELECT
		`user_id`,
		sum(
			CASE WHEN `action_item` = 'MODIFY'
				AND `item_id` = 'GOLD' THEN
				`quantity`
			ELSE
				0
			END) AS modify_gold
	FROM
		view_raw_item_log
	WHERE
		toDate (`log_time`,
			'Asia/Ho_Chi_Minh') = toDate ('2023-08-05',
			'Asia/Ho_Chi_Minh')
	GROUP BY
		`user_id`
),
LastRow AS (
	SELECT
		toDate (`log_time`) AS `report_date`,
		`user_id`,
		IF(social_type = '',
			(
			CASE substr(`user_name`,
			1,
			3)
		WHEN 'app.' THEN
				'apple'
			WHEN 'fb.' THEN
				'facebook'
			WHEN 'gog.' THEN
				'google'
			ELSE
				'undifined'
			END),
		`social_type`) AS `social_type`,
			`platform_id`,
			`current_gold`,
			`current_g`,
			row_number() OVER (PARTITION BY `user_id` ORDER BY `log_time` DESC) AS rn
		FROM
			view_raw_log
		WHERE
			toDate (`log_time`,
			'Asia/Ho_Chi_Minh') = toDate ('2023-08-05',
		'Asia/Ho_Chi_Minh')
)
SELECT *
FROM (
         SELECT *
         FROM LastRow
         WHERE rn = 1 ) a
         LEFT JOIN GoldInOut ON a.user_id = GoldInOut.user_id
LIMIT 10 

~~~~

**Comment by lampjian** [comment]
The same as #15539 and #11068.

**Comment by lampjian** [comment]
Make sure that your view_raw_log has `user_name` field.

**Comment by hohaithuy** [comment]
As mentioned, running a single table query for either `LastRow` or `GoldInOut` works perfectly fine. The error only occurs when attempting to join these two tables. Additionally, it's important to note that my `view_raw_log` contains `usernames`.

**Comment by hohaithuy** [comment]
As mentioned, running a single table query for either `LastRow` or `GoldInOut` works perfectly fine. The error only occurs when attempting to join these two tables. Additionally, it's important to note that my `view_raw_log` contains `usernames`.

**Comment by lampjian** [comment]
Try to upgrade your clickhouse version or add the database name before views. See also #28687.

**Comment by nikitamikhaylov** [comment]
Please try to upgrade to `24.3` and check your query there. Closing this issue as there is no reproducible example which we can add as a test to our codebase and the linked issue looks relevant and already fixed.
