### ISSUE TITLE
how to set flatten_nested while using java jdbc client.

### ISSUE THREAD

**Issue by GandiYaswanthSai** [ClickHouse/ClickHouse#53158]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

I have used 'flatten_nested' setting in python client and am able to execute queries successfully. But I am unable to execute it in java client. Can someone pitch in and clarify?

**Comment by alexey-milovidov** [comment]
This question should be directed to the repository of the Java client.
