### ISSUE TITLE
Is there a settings that makes all tables not-writable?

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#53153]
I'm seeking a settings/control statements to make all tables in a ClickHouse instance not-writable, so I can mutate  the table structure (like changing partition key online, progressively for each shard), or dump existing data to another shard without disturbing new-coming data.

**Comment by melvynator** [comment]
You can change the type of queries accepted by ClickHouse: https://clickhouse.com/docs/en/operations/settings/permissions-for-queries. You could for instance, disable write queries and keep DDL queries enabled.
