### ISSUE TITLE
Threads do excessive work after LIMIT number of rows were found 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#5315]
When you do `SELECT something FROM bigtable WHERE conditions LIMIT 1`, you can often see that first row is returned really fast while the final result still waits for other threads to finish. 

Probably that can be improved.

**Comment by alexey-milovidov** [comment]
We already do "Stop other threads after LIMIT number of rows were found".

**Comment by alexey-milovidov** [comment]
The time to wait is to correctly finish the threads (wait for the last block to process).
In case of distributed query, we send cancellation to remote servers and wait them to stop the query processing and to response.

**Comment by alexey-milovidov** [comment]
If the query does not finish in a reasonable amount of time after result was sent, it's a bug.

**Comment by filimonov** [comment]
Maybe I've used bad description for that issue.

I know that other threads are stopped, but excessive work done by them (while processing last blocks of data) are clearly visible in lot of cases.

**Comment by MakarovYaroslav** [comment]
+1
I have the same problem.
Query with LIMIT 1 quickly (<1s) returns first string and then it takes a very long time to complete query (about 20s)
