### ISSUE TITLE
What's the indexing recommendation on JSON columns

### ISSUE THREAD

**Issue by zhouning64** [ClickHouse/ClickHouse#53165]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

Understanding JSON column is a experimental feature, but we have use cases to store JSON payload in the table, what's the recommendation and indexing strategy in terms of performing needle in the haystack type of search query into the Json payload values as well as JSON field search queries  aaa.bbb = flah aaa.bbb like '%foo%' etc.

**Comment by alexey-milovidov** [comment]
We don't support JSON columns - it is under development and not ready to use.

> but we have use cases to store JSON payload in the table

You can store it as `String`.
