### ISSUE TITLE
Received signal Segmentation fault while drop table - ClickHouse

### ISSUE THREAD

**Issue by BTJagadeeshKumar** [ClickHouse/ClickHouse#53161]
Hi, I am trying to drop a table which is around 5TB of size and noticing Segmentation Fault alert. Post this issues the clickhouse is not able to allow any new connection and its in hung state. can someone please help us with the solution.  

2023.08.08 18:58:26.015351 [ 13257 ] <Fatal> BaseDaemon: ########################################
2023.08.08 18:58:26.015451 [ 13257 ] <Fatal> BaseDaemon: (version 23.7.1.2470 (official build), build id: 0104977E633649EC423D8834AAAD9B4D76EF6B5C, git hash: a70127baecc451f1f7073bad7b6198f6703441d8) (from thread 49147) (query_id: 5dd24117-4a19-4b09-9671-aa9cf850d4d5) (query: drop table billing.sms_log;) Received signal Segmentation fault (11)
2023.08.08 18:58:26.015492 [ 13257 ] <Fatal> BaseDaemon: Address: 0x46f406800. Access: read. Address not mapped to object.
2023.08.08 18:58:26.015520 [ 13257 ] <Fatal> BaseDaemon: Stack trace: 0x000000000eb4c181 0x00007f36bf047630
2023.08.08 18:58:26.019847 [ 13257 ] <Fatal> BaseDaemon: 0. ? @ 0x000000000eb4c181 in /usr/bin/clickhouse
2023.08.08 18:58:26.026531 [ 13257 ] <Fatal> BaseDaemon: 1. ? @ 0x000000000000f630 in /usr/lib64/libpthread-2.17.so
2023.08.08 18:58:26.268814 [ 13257 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 1B7B164035844DCF382CCE7AD9C49429)
2023.08.08 18:58:26.268914 [ 13257 ] <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2023.08.08 18:58:26.269025 [ 13257 ] <Fatal> BaseDaemon: Changed settings: use_uncompressed_cache = false, load_balancing = 'random', max_memory_usage = 100000000000, date_time_input_format = 'best_effort'

**Comment by evillique** [comment]
Do you still have the logs for this? Is it possible to grep all the mentions of thread 49147 with `grep -F '[ 49147 ]'` before the segfault?
