### ISSUE TITLE
02228_merge_tree_insert_memory_usage times out on S3

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#53172]
https://s3.amazonaws.com/clickhouse-test-reports/52828/8b0f52f4114099b8a3fc0e37caa8b3f9a99cc054/stateless_tests__debug__s3_storage__[1_6].html

The test does two INSERTs that produce 1024 parts each. The server log shows that each part takes ~300ms to write, so the test takes longer than the 10-minute timeout.

**Comment by alexey-milovidov** [comment]
@al13n321, remove it from every run except release.

**Comment by Algunenano** [comment]
Changed in https://github.com/ClickHouse/ClickHouse/pull/64387
