### ISSUE TITLE
Insertion of more than 10 million rows gives the error ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 32, I/O

### ISSUE THREAD

**Issue by kashifjavedaddo** [ClickHouse/ClickHouse#53186]
We are running insert into select command from dbeaver connected to Clickhouse using Clickhouse client driver and have tried to increase following parameters:

connect_timeout_with_failover_ms = 10000
socket_timeout=1000000
use_server_time_zone=false
connect_timeout=1000000
receive_timeout=1000000
send_timeout=1000000
use_time_zone=false

The table in which we are trying to insert is using MergeTree Engine. The one odd thing is that the insert keeps on running in the background even after we receive the below error and row count in target table keeps on increasing until all rows are inserted.
 
"
_[ 2046 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 32, I/O error: Broken pipe, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, String const&) @ 0x0000000017bf211f in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::sendBytes(void const*, int, int) @ 0x0000000017bf32fd in /usr/bin/clickhouse
2. Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) @ 0x0000000017bf79d6 in /usr/bin/clickhouse
3. Poco::Net::HTTPSession::write(char const*, long) @ 0x0000000017bd6fb3 in /usr/bin/clickhouse
4. Poco::Net::HTTPChunkedIOS::~HTTPChunkedIOS() @ 0x0000000017bc4e1a in /usr/bin/clickhouse
5. Poco::Net::HTTPChunkedOutputStream::~HTTPChunkedOutputStream() @ 0x0000000017bc59a2 in /usr/bin/clickhouse
6. DB::HTTPServerConnection::run() @ 0x0000000014c8d8ea in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x0000000017bf8a34 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000017bf9c51 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x0000000017d7c0a7 in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017d79adc in /usr/bin/clickhouse
11. ? @ 0x00007f3f0935f812 in ?
12. ? @ 0x00007f3f092ff450 in ?
 (version 23.6.2.18 (official build))_
"

We have been trying to resolve this issue for last 7 days and have searched through google, slack, etc but have not been able to find a resolution even though similar issue is frequently reported.

We would highly appreciate any help in this regard to understand the underlying issue and permanent resolution.

Looking forward to your generous support.

Regards,

Kashif Javed Rana

**Comment by alexey-milovidov** [comment]
This is a problem with Dbeaver, not ClickHouse.
