### ISSUE TITLE
Missing `TO INNER UUID` syntax in the antlr/ClickHouseParser.g4

### ISSUE THREAD

**Issue by git-hulk** [ClickHouse/ClickHouse#53188]
**Describe the issue**
I saw ClickHouse supports the syntax `TO INNER UUID` in the codebase: [ParserCreateQuery.cpp#L1340C1-L1340C1](https://github.com/ClickHouse/ClickHouse/blob/3ffffb0b5e6ef53dba149cc8aba768dbc7c724cf/src/Parsers/ParserCreateQuery.cpp#L1340C1-L1340C1), but [antlr/ClickHouseParser.g4](https://github.com/ClickHouse/ClickHouse/blob/master/utils/antlr/ClickHouseParser.g4) didn't mention this. Should I submit a PR to fix this?

**Comment by tavplubix** [comment]
`antlr/ClickHouseParser.g4` is stale, it was not updated for a long time, and there are a lot of missing things. Also, `TO INNER UUID` is something internal, it's not intended to be used by a user. So it's better to do nothing about this. Anyway, thanks for paying attention and reporting!

**Comment by git-hulk** [comment]
@tavplubix Thanks for your reply. I want to implement the SQL parser in Go. Does it have another way to see ClickHouse syntax? I looked at the official documentation and it's too simple.

**Comment by tavplubix** [comment]
No, unfortunately, we don't have any up-to-date declarative syntax description, there's only parser's implementation in `src/Parsers`

**Comment by git-hulk** [comment]
@tavplubix Thank you!
