### ISSUE TITLE
Test `test_reverse_dns_query/test.py::test_reverse_dns_query` is broken

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#53194]
https://s3.amazonaws.com/clickhouse-test-reports/0/2a92dc4b700f5484ab293e6c95eece571cbb926a/integration_tests__tsan__[4_6].html
https://s3.amazonaws.com/clickhouse-test-reports/53182/b5273e75bc747e171d87c96f9db53560b76bf9a3/integration_tests__release__[2_4].html
https://s3.amazonaws.com/clickhouse-test-reports/53182/b5273e75bc747e171d87c96f9db53560b76bf9a3/integration_tests__release__[2_4].html
https://s3.amazonaws.com/clickhouse-test-reports/52797/9903c302ac9ce287c5720c11f1b39487d54b54ed/integration_tests__tsan__[4_6].html
https://s3.amazonaws.com/clickhouse-test-reports/53183/2f6e66c8e3809d80bcab0afe7bf5d9d03761640d/integration_tests__asan__analyzer__[4_6].html

The test is bad, it relies on some third-party stuff we cannot control:
https://github.com/ClickHouse/ClickHouse/blob/108071f052290be5280b92e3d1a26db03ddd60c2/tests/integration/test_reverse_dns_query/test.py#L49-L50

It just stopped working at `2023-08-09 00:00:00`: [CI DB link](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X3JldmVyc2VfZG5zX3F1ZXJ5L3Rlc3QucHk6OnRlc3RfcmV2ZXJzZV9kbnNfcXVlcnknIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQpHUk9VUCBCWSBkCk9SREVSIEJZIGQgREVTQwo=)

cc: @arthurpassos

**Comment by tavplubix** [comment]
Disabled it: https://github.com/ClickHouse/ClickHouse/pull/53195

**Comment by arthurpassos** [comment]
Hm... Maybe I can set up a DNS server so we don't need to rely on 3rd party services, what do you think?

**Comment by alexey-milovidov** [comment]
We deleted it.
