### ISSUE TITLE
Code: 473. DB::Exception: READ locking attempt on "default.lineorder_flat" has timed out

### ISSUE THREAD

**Issue by Shiokiri** [ClickHouse/ClickHouse#53196]
Refer to https://clickhouse.com/docs/en/getting-started/example-datasets/star-schema and execute `Converting “star schema” to denormalized “flat schema”` step, an error`DBeaver SQL Error [159] .. Read timed out` ocurred, after which the `default.lineorder_flat` table was dropped.

Now when trying `show tables`, the following error is reported.
```
Code: 473. DB::Exception: READ locking attempt on "default.lineorder_flat" has timed out!
(120000ms) Possible deadlock avoided. Client should retry.: While executing Tables.
(DEADLOCK_AVOIDED) (version 22.3.20.29 (official build))
, server ClickHouseNode [uri=, options={socket_timeout=300000,use_server_time_zone=false,use_time_zone=false}]@-2142436649
```

How to make the tables in the database`default` display normally?

**Comment by alexey-milovidov** [comment]
You are using version 22.3, which is quite old.
