### ISSUE TITLE
No results when quering col > '1969' if table partitioned by that column

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#53190]
**Describe what's wrong**

DateTime condition comparing to the date before starting of the unix epoch stopped to work if the partitioning key uses that column.

**Repro**

https://fiddle.clickhouse.com/66a75ef0-c107-4ae1-83f4-ae608971bc9c

**Does it reproduce on recent release?**

Yes

**How to reproduce**

```sql
DROP TABLE IF EXISTS test_ts;

CREATE TABLE test_ts
(
    `id` UInt64,
    `ts` DateTime
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(ts)
ORDER BY (id, ts);

INSERT INTO test_ts VALUES (1, '2023-08-02 08:02:05');

SELECT 'query 1';

SELECT * FROM test_ts;

SELECT 'query 2';

SELECT * FROM test_ts WHERE ts >= '1969-07-01 00:00:00';
```

That is a regression between 22.3 and 22.4

**Comment by zvonand** [comment]
Was broken by #35334
