### ISSUE TITLE
Add a new backup_log table

### ISSUE THREAD

**Issue by sirvickr** [ClickHouse/ClickHouse#53221]
**Use case**

@e-mars in [this](https://github.com/ClickHouse/ClickHouse/issues/43995) issue put forward an idea of `system.backups` table persistence (and I'm already working on its implementation).

@mlex in the same issue suggested that we might as well add a new `backup_log` table as an _alternative_ to making `system.backups` table persistent.

@UnamedRus please also take a look at this issue.

**Describe the solution you'd like**

My suggestion is to introduce `backup_log` table _along with_ the persistent `system.backups` table (which is yet to be implemented).

This table would apparently be one one of the "system logs" along with `query_log`, `session_log` etc. Those system logs can be conveniently turned on and off in the config file, their engine (e.g. `MergeTree`) and other properties are also configurable and the implementation is next to trivial. Moreover, @chhetripradeep even suggested an adequate solution (yet without a pull request).

So, if a new `backup_log` table would come in handy, I'm ready to implement it and create a pull request if necessary.

Kindly looking forward to any feedback from the community.

**Comment by alexey-milovidov** [comment]
All good, and the structure looks alright. Let's go ahead!

**Comment by melvynator** [comment]
@sirvickr Thank you for doing it.  

The way I see it is that we need the system.backups table to give you information on the current backup table like the system.processes table so it doesn't need to be persisted. The system.backup_log table will have the persisted information similar to the query_log. We will also need a new documentation page for this table.

**Comment by UnamedRus** [comment]
My only concern here is name column.

It looks more like engine_full column, (if we use analogue from system.tables)
And name should include only backup name, but it probably be harder to implement

**Comment by sirvickr** [comment]
> My only concern here is name column.
> 
> It looks more like engine_full column, (if we use analogue from system.tables) And name should include only backup name, but it probably be harder to implement

I took all columns from the existing table `system.backups` (except `event_date` and `event_time`) to keep things consistent.
When I saw the `name` column containing the backup's storage (basically, the `FROM`/`TO` clause of the query) for the first time, it also appeared to me to be somewhat weird:
```sql
SELECT * FROM system.backups;
```
```
┌─id───────────────────────────────────┬─name──────────────────┬─status─────────┬─error─┬──────────start_time─┬────────────end_time─┬─num_files─┬─total_size─┬─num_entries─┬─uncompressed_size─┬─compressed_size─┬─files_read─┬─bytes_read─┐
│ 8209c837-81b1-45e2-99c9-68766fa6ad0d │ Disk('bak', 't1.zip') │ RESTORED       │       │ 2023-08-11 10:41:09 │ 2023-08-11 10:41:18 │        57 │ 4290370807 │          48 │        4290379062 │      4290379062 │         57 │ 4290370807 │
│ db2fc64f-8ca3-4101-af0d-552e14f560bf │ Disk('bak', 't1.zip') │ BACKUP_CREATED │       │ 2023-08-11 10:01:15 │ 2023-08-11 10:04:46 │        57 │ 4290370807 │          48 │        4290379062 │      3525097556 │          0 │          0 │
└──────────────────────────────────────┴───────────────────────┴────────────────┴───────┴─────────────────────┴─────────────────────┴───────────┴────────────┴─────────────┴───────────────────┴─────────────────┴────────────┴────────────┘
```
So, we might decide to reconsider the name of the `name` column now and introduce 'backup_log' with new, more relevant header.
On the other hand, we could do it in a separate issue/pull request later, regarding both tables.
Otherwise it might seem inconsistent that we name the same entity differently in two tables.

**Comment by sirvickr** [comment]
Hello guys, could you please take a look at the [PR](https://github.com/ClickHouse/ClickHouse/pull/53638) I've created?
