### ISSUE TITLE
Clickhouse intergration with Hadoop

### ISSUE THREAD

**Issue by tranvietha** [ClickHouse/ClickHouse#53253]
Hi everybody,

I'm a newbie in Clickhouse. I have some question need your help. I have a clickhouse server and a hadoop server. It's installed in separate machine.

First, I create a table in hadoop by command:

CREATE TABLE `dwh.test_tbl_01`(
  `chatyp` char(1)
  )
ROW FORMAT SERDE 
'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES ( 
'field.delim'=',', 
'serialization.format'=',') 
STORED AS INPUTFORMAT 
'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
'hdfs://bigdatalite.localdomain:9000/user/hive/warehouse/dwh.db/test_tbl_01'
;

Then, I insert data into table above (see result in "hadoop.png")

![hadoop](https://github.com/ClickHouse/ClickHouse/assets/8704117/6d2c8cec-44da-4178-943b-f05eab23f817)

Second, I create table in Clickhouse using HIVE engine by command:

CREATE TABLE test_tbl_01
(
    `chatyp` String
)
ENGINE = Hive('thrift://bigdatalite.localdomain:9083', 'dwh', 'test_tbl_01')
PARTITION BY chatyp

Then, I select table in Clickhouse but it return 0 rows (although table in hadoop have data). See result in "HIVE.png"

![HIVE](https://github.com/ClickHouse/ClickHouse/assets/8704117/331d4994-64c2-4cc3-9d99-616b076abe2e)

Third, I create a query using HDFS in Clickhouse Client by command:

SELECT chatyp
FROM hdfs('hdfs://bigdatalite.localdomain:9000/user/hive/warehouse/dwh.db/cddhis_2021/CDDHIS', 'CSV', 'chatyp String')
LIMIT 2

and result still 0. See result in "HDFS.png"

![HDFS](https://github.com/ClickHouse/ClickHouse/assets/8704117/8aacde22-d690-4d7e-aba4-eb213481776b)

So, I have 2 question:

1. Why result always 0 (although table in Hadoop have data)
2. When use postgreSQL or jdbc..., I must supply username/password but when use HIVE, i don't find anywhere to required it.

Thank in advance!

```[tasklist]
### Tasks
```

**Comment by 723935706** [comment]
I've reproduced this bug again with some differences. I create a hive table with PARTITIONED BY clause:
![image](https://github.com/ClickHouse/ClickHouse/assets/48706738/22f4ef80-55f6-4190-8c78-7328590e09de)
then insert some data in hive;
![image](https://github.com/ClickHouse/ClickHouse/assets/48706738/3fd567b4-648f-4768-a138-bc79c8862d59)
only field in PARTITIONED BY can be shown:
![image](https://github.com/ClickHouse/ClickHouse/assets/48706738/870068d3-de58-4535-bcc4-2f24e76c1381)

**Comment by alexey-milovidov** [comment]
We don't do ClickHouse integration with Hadoop.
