### ISSUE TITLE
Chinese document`ClickHouse主键索引最佳实践` is out of date.

### ISSUE THREAD

**Issue by selfuppen** [ClickHouse/ClickHouse#53254]
**Describe the issue**
1. In the Part [“数据被组织成颗粒以进行并行数据处理"](https://clickhouse.com/docs/zh/guides/best-practices#%E6%95%B0%E6%8D%AE%E8%A2%AB%E7%BB%84%E7%BB%87%E6%88%90%E9%A2%97%E7%B2%92%E4%BB%A5%E8%BF%9B%E8%A1%8C%E5%B9%B6%E8%A1%8C%E6%95%B0%E6%8D%AE%E5%A4%84%E7%90%86), the fourth item of the note  says:
> 我们将主键列(UserID, URL)中的一些列值标记为橙色。
>这些橙色标记的列值是每个颗粒中每个主键列的最小值。这里的例外是最后一个颗粒(上图中的颗粒1082)，最后一个颗粒我们标记的是最大的值。
>正如我们将在下面看到的，这些橙色标记的列值将是表主索引中的条目。

The content , *这些橙色标记的列值是每个颗粒中每个主键列的最小值。这里的例外是最后一个颗粒(上图中的颗粒1082)，最后一个颗粒我们标记的是最大的值*, is not correct from the diagram above. 
In the last granule 1082, the UserId of the marked 8.863.744 row is 4.292.714.039, which is obviousely the minimum value as other granule.
On the other hand, [the English document](https://clickhouse.com/docs/en/optimize/sparse-primary-indexes#data-is-organized-into-granules-for-parallel-data-processing) does not contain such description(maybe, removed?):
>We marked some column values from our primary key columns (UserID, URL) in orange. These orange-marked column values are the primary key column values of each first row of each granule. As we will see below, these orange-marked column values will be the entries in the table's primary index.

2. [通过projections使用联合主键索引](https://clickhouse.com/docs/zh/guides/best-practices#%E9%80%9A%E8%BF%87projections%E4%BD%BF%E7%94%A8%E8%81%94%E5%90%88%E4%B8%BB%E9%94%AE%E7%B4%A2%E5%BC%95) 
    1. Projections is [production ready](https://clickhouse.com/blog/clickhouse-22-2-released) from 22.2 Released，and  `optimize_use_projections` is already [enabled in default](https://clickhouse.com/docs/en/operations/settings/settings#optimize_use_projections).
    2. Therefore, the [English document](https://clickhouse.com/docs/en/optimize/sparse-primary-indexes#option-3-projections) does not contain such content(maybe, removed?)
    3. The NOTE is dated and lost some content from Englsih document,such as  `the hidden table is not listed by the SHOW TABLES query` 
 
3. lags behind the English document by the two parts, `Ordering key columns efficiently` and `Identifying single rows efficiently`.

4. The catalogue 
    the English docuement `Sparse Primary Indexes` is under Best Practice, so should we move it to `最佳实践` so that keep them the same  catalogue structure？
 
**Additional context**
I am willing to submit a PR to fix them!

**Comment by hanfei1991** [comment]
@selfuppen are you interested to contribute? I could help to review!
