### ISSUE TITLE
Segmentation fault during CREATE ROW POLICY

### ISSUE THREAD

**Issue by granescb** [ClickHouse/ClickHouse#53271]
Clickhouse version: 22.3.17.13. 
We are using Clickhouse in k8s, deployed via Clickhouse Operator(0.20.1). Each day Clickhouse is crashing and restarts. 
Stack trace:
`
Aug 8, 2023 @ 20:20:54.185	2023.08.08 16:20:54.185724 [ 3275 ] {} <Fatal> BaseDaemon: (version 22.3.17.13 (official build), build id: 57894EE76F3A74F0) (from thread 3227) (query_id: c2d22d9b-946b-4858-884b-32b917e1451e) (query: CREATE ROW POLICY IF NOT EXISTS report_accounts__im_XXXX_ec1 ON "default".all_report_accounts USING agency_id = XXXX TO im_XXXX_ec1_ro) Received signal Segmentation fault (11)
Aug 8, 2023 @ 20:20:54.185	2023.08.08 16:20:54.185794 [ 3275 ] {} <Fatal> BaseDaemon: Address: 0x7efbb8b72000 Access: read. Attempted access has violated the permissions assigned to the memory area.
Aug 8, 2023 @ 20:20:54.185	2023.08.08 16:20:54.185844 [ 3275 ] {} <Fatal> BaseDaemon: Stack trace: 0x14db908d 0x14dbc6c6 0x14dbdd50 0x14dbdbee 0x14dbe861 0x14d8ed0e 0x14d4627e 0x14d8a1f4 0x14d670d3 0x15e3ff26 0x15e1230f 0x15e0fdb5 0x1678a430 0x16799f79 0x19a63e0f 0x19a66261 0x19c23be9 0x19c20f40 0x7efc656fc609 0x7efc65621133
Aug 8, 2023 @ 20:20:54.188	2023.08.08 16:20:54.188651 [ 3275 ] {} <Fatal> BaseDaemon: 2. DB::RolesOrUsersSet::match(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, boost::container::flat_set<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, std::__1::less<StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> >, void> const&) const @ 0x14db908d in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189442 [ 3275 ] {} <Fatal> BaseDaemon: 3. DB::RowPolicyCache::mixFiltersFor(DB::EnabledRowPolicies&) @ 0x14dbc6c6 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189496 [ 3275 ] {} <Fatal> BaseDaemon: 4. DB::RowPolicyCache::mixFilters() @ 0x14dbdd50 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189542 [ 3275 ] {} <Fatal> BaseDaemon: 5. DB::RowPolicyCache::rowPolicyAddedOrChanged(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::__1::shared_ptr<DB::RowPolicy const> const&) @ 0x14dbdbee in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189592 [ 3275 ] {} <Fatal> BaseDaemon: 6. ? @ 0x14dbe861 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189641 [ 3275 ] {} <Fatal> BaseDaemon: 7. ? @ 0x14d8ed0e in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189689 [ 3275 ] {} <Fatal> BaseDaemon: 8. DB::DiskAccessStorage::insertImpl(std::__1::shared_ptr<DB::IAccessEntity const> const&, bool, bool) @ 0x14d4627e in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189729 [ 3275 ] {} <Fatal> BaseDaemon: 9. DB::MultipleAccessStorage::insertImpl(std::__1::shared_ptr<DB::IAccessEntity const> const&, bool, bool) @ 0x14d8a1f4 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.189	2023.08.08 16:20:54.189777 [ 3275 ] {} <Fatal> BaseDaemon: 10. DB::IAccessStorage::insert(std::__1::vector<std::__1::shared_ptr<DB::IAccessEntity const>, std::__1::allocator<std::__1::shared_ptr<DB::IAccessEntity const> > > const&, bool, bool) @ 0x14d670d3 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190486 [ 3275 ] {} <Fatal> BaseDaemon: 11. DB::InterpreterCreateRowPolicyQuery::execute() @ 0x15e3ff26 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190520 [ 3275 ] {} <Fatal> BaseDaemon: 12. ? @ 0x15e1230f in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190566 [ 3275 ] {} <Fatal> BaseDaemon: 13. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15e0fdb5 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190610 [ 3275 ] {} <Fatal> BaseDaemon: 14. DB::TCPHandler::runImpl() @ 0x1678a430 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190644 [ 3275 ] {} <Fatal> BaseDaemon: 15. DB::TCPHandler::run() @ 0x16799f79 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190688 [ 3275 ] {} <Fatal> BaseDaemon: 16. Poco::Net::TCPServerConnection::start() @ 0x19a63e0f in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190718 [ 3275 ] {} <Fatal> BaseDaemon: 17. Poco::Net::TCPServerDispatcher::run() @ 0x19a66261 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190764 [ 3275 ] {} <Fatal> BaseDaemon: 18. Poco::PooledThread::run() @ 0x19c23be9 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190794 [ 3275 ] {} <Fatal> BaseDaemon: 19. Poco::ThreadImpl::runnableEntry(void*) @ 0x19c20f40 in /usr/bin/clickhouse
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190848 [ 3275 ] {} <Fatal> BaseDaemon: 20. ? @ 0x7efc656fc609 in ?
Aug 8, 2023 @ 20:20:54.190	2023.08.08 16:20:54.190877 [ 3275 ] {} <Fatal> BaseDaemon: 21. clone @ 0x7efc65621133 in ?
Aug 8, 2023 @ 20:20:54.207	2023.08.08 16:20:54.207366 [ 3258 ] {} <Information> TCPHandler: Client has not sent any data.
............
Aug 8, 2023 @ 20:21:16.575	2023.08.08 16:21:16.574727 [ 1 ] {} <Fatal> Application: Child process was terminated by signal 11.
`
Query from stack trace:
`CREATE ROW POLICY IF NOT EXISTS report_accounts__im_XXXX_ec1 ON "default".all_report_accounts USING agency_id = XXXX TO im_XXXX_ec1_ro`

**Comment by tavplubix** [comment]
> version 22.3.17.13

This version is obsolete, we don't support it anymore. You should upgrade
