### ISSUE TITLE
question: failed to move parts manually, raise execution timeout.

### ISSUE THREAD

**Issue by rfyiamcool** [ClickHouse/ClickHouse#53270]
### question

If the partition takes up a lot of space, then failed to move data partition to another disk manually. clickhouse-client returns an operation timeout error.

will the move operation continue in the background?  Or the operation is failed，clickhouse-server drop files of parts than failed to move ?

```
$$ chi-logs-logs:) ALTER TABLE `app_log_local` MOVE PART '202308_1267403_1625577_49' TO DISK 'disk03';

ALTER TABLE app_log_local
    MOVE PART '202308_1267403_1625577_49' TO DISK 'disk03'

Query id: aca23870-0c98-4df3-a1f4-0ab1d140ddde

...

Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
Ok.
Query was cancelled.

0 rows in set. Elapsed: 402.151 sec.
```

**Comment by cangyin** [comment]
> will the move operation continue in the background?

yes. confirm that in [system.moves](https://clickhouse.com/docs/en/operations/system-tables/moves):

> clickhouse-client returns an operation timeout error

use this to make `clickhouse-client` wait longer before raising an error:
```
clickhouse-client --receive_timeout=36000 --alter_sync=2
```
ref 
- https://clickhouse.com/docs/en/operations/settings/settings#connect-timeout-receive-timeout-send-timeout
- https://clickhouse.com/docs/en/operations/settings/settings#alter-sync
