### ISSUE TITLE
Configuration is not reloaded if changed too fast

### ISSUE THREAD

**Issue by mkmkme** [ClickHouse/ClickHouse#53276]
**Describe the issue**
ClickHouse only reloads config file if the modification time changes. This is detected with `FS::getModificationTime`, which only has a resolution of one second. This means ClickHouse may miss changes if they happen within the same seconds as the previous change.

**Comment by cangyin** [comment]
check [SYSTEM RELOAD CONFIG](https://clickhouse.com/docs/en/sql-reference/statements/system#reload-config)

**Comment by mkmkme** [comment]
This might work, but this looks more of a workaround rather than proper solution.

I could craft a PR to fix that. Would you be interested in that?

**Comment by rschu1ze** [comment]
Yepp, fixing this sounds reasonable. You can set me as a reviewer to a potential PR.
