### ISSUE TITLE
How to create an UDF  multiSearchAll

### ISSUE THREAD

**Issue by kaynewu** [ClickHouse/ClickHouse#53301]
Like   multiSearchAny function 
Returns 1, if at least one string needle matches the string haystack and 0 otherwise.

How to create an UDF  multiSearchAll 
Returns 1, if all string needle matches the string haystack and 0 otherwise.

**Comment by cangyin** [comment]
```sql
SELECT arrayAll(arrayMap(x-> x>0, multiSearchAllPositions('Hello, World!', ['Hello', '!', 'World'])));
```

or less intuitively:
```sql
SELECT NOT has(multiSearchAllPositions('Hello, World!', ['Hello', '!', 'World']), 0);
```

see https://fiddle.clickhouse.com/06a1f78d-0756-4890-9fa0-9629d4c9aa84
