### ISSUE TITLE
How to use optimize_on_insert setting in config.xml file of clickhouse-server

### ISSUE THREAD

**Issue by GandiYaswanthSai** [ClickHouse/ClickHouse#53319]
I am using a ReplacingMergetree and I want to update the records based on id. So instead of manually using optimize_on_insert, is there any other way to do this automation using config.xml file settings?

**Comment by UnamedRus** [comment]
It's user level setting, you can set it in user profile.

Plus it enabled by default, why you need to touch it?

**Comment by GandiYaswanthSai** [comment]
I want to set a desired frequency. So if you can provide some xml snippet, it will be helpful.

**Comment by UnamedRus** [comment]
It's not about frequency, its optimize block of data which being inserted, not whole table.
