### ISSUE TITLE
TabSeparated fails to parse with input_format_parallel_parsing enabled

### ISSUE THREAD

**Issue by ewewukek** [ClickHouse/ClickHouse#53320]
`Code: 27. DB::ParsingException: Cannot parse input: expected '\t' at end of stream.: Buffer has gone, cannot extract information about what has been parsed.: While executing ParallelParsingBlockInputFormat: (at row 32735)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED) (version 22.3.20.1)`

have not tested on recent ClickHouse versions. reproducible on 22.3.20.1

```
CREATE TABLE aaaaaaaaa_bbb_ccccc_dddddd
(
    `date` DateTime CODEC(ZSTD(4)),
    `aaaaa` Int64 CODEC(T64, ZSTD(1)),
    `bbbbbbbbb` UInt8 CODEC(T64, ZSTD(1)),
    `cc` UInt32 CODEC(T64, ZSTD(1)),
    `dddd` UInt8 CODEC(T64, ZSTD(1)),
    `eeee` String CODEC(ZSTD(1)),
    `fff` String CODEC(ZSTD(1)),
    `ggg` String CODEC(ZSTD(1)),
    `hhhhhhhhhhh` LowCardinality(String) CODEC(ZSTD(1)),
    `iii` LowCardinality(String) CODEC(ZSTD(1)),
    `jjjjjj` LowCardinality(String) CODEC(ZSTD(1)),
    `kkkkkk` LowCardinality(String) CODEC(ZSTD(1)),
    `llll` LowCardinality(String) CODEC(ZSTD(1)),
    `mmmmmmmm` LowCardinality(String) CODEC(ZSTD(1)),
    `nnnnnnnnnnnn` LowCardinality(String) CODEC(ZSTD(1)),
    `ooooo` LowCardinality(String) CODEC(ZSTD(1)),
    `ppppppp` LowCardinality(String) CODEC(ZSTD(1)),
    `qqqqqqqqqq` LowCardinality(String) CODEC(ZSTD(1)),
    `rrrrrrrrrrr` LowCardinality(String) CODEC(ZSTD(1)),
    `ssssssss` LowCardinality(String) CODEC(ZSTD(1)),
    `ttttt` LowCardinality(String) CODEC(ZSTD(1))
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(date)
ORDER BY date
SETTINGS index_granularity = 8192
```
[obfuscated.bin.gz](https://github.com/ClickHouse/ClickHouse/files/12320279/obfuscated.bin.gz) - http request that produces this error

**Comment by alexey-milovidov** [comment]
I confirm, if parallel parsing isn't used - it inserted successfully, while with parallel parsing it isn't.
Reproduced on master.

**Comment by alexey-milovidov** [comment]
How to reproduce:

1. Uncompress the file.
2. Run `nc localhost 8123 < obfuscated.bin`

**Comment by Avogar** [comment]
The problem was that data contains strings with `\r\n` but only `\n` are escaped. And we didn't process single unescaped `\r` during parallel parsing.
