### ISSUE TITLE
clickhouse-client waiting forever after server restart

### ISSUE THREAD

**Issue by thinkinerp** [ClickHouse/ClickHouse#5338]
Hi :

I met a bug . when the sever restart . the clickhouse-client waiting for response will wait forever . I think it is cool if the client maybe throws connecting failed exception .

And the clickhouse version is 18.14.13.

hope your response. thanks.

**Comment by alexey-milovidov** [comment]
I cannot confirm this issue (need a way to reproduce).
In my experience, when the server is restarted during a query, client will display "broken pipe" message.
