### ISSUE TITLE
Wrong Schema detected by Automatic schema inference from input data.

### ISSUE THREAD

**Issue by shabir1** [ClickHouse/ClickHouse#53384]
# Wrong Schema detected by Automatic schema inference from input data.

## Steps to reproduce
I have a dataset with 1Million rows.
All the rows of column C contain INT values except 1 column, Which contains FLOAT.
The automatic schema inference using the below query detects it as Nullable(INT).
But when I insert the same file it throws the Parse error on that row which contains the FLOAT value.

## Schema Detection Query:
```
DESCRIBE file('file.csv', CSV) SETTINGS input_format_max_rows_to_read_for_schema_inference=100000000
```
## Returned Schema:
```
schema:                 A Nullable(Float64), B Nullable(String), C Nullable(Int64), ...
```

## Check inference Cache
```
SELECT * FROM system.schema_inference_cache FORMAT Vertical
```
```
Row 1:
──────
storage:                File
source:                 /home/shabir/Downloads/file.csv
format:                 CSV
additional_format_info: schema_inference_hints=, max_rows_to_read_for_schema_inference=100000000, max_bytes_to_read_for_schema_inference=100000000, schema_inference_make_columns_nullable=true, try_infer_integers=true, try_infer_dates=true, try_infer_datetimes=true, use_best_effort_in_schema_inference=true, bool_true_representation=true, bool_false_representation=false, null_representation=\N, delimiter=,, tuple_delimiter=,, column_names_for_schema_inference=, try_detect_header=true
registration_time:      2023-08-03 06:16:28
schema:                 A Nullable(Float64), B Nullable(String), C Nullable(Int64), ...

```

Error during insert
```
Row 14373:
Column 0,   name: A,      type: Nullable(Float64),   parsed text: "1123.1"
Column 1,   name: B, type: Nullable(String),    parsed text: "fff"
Column 2,   name: C,    type: Nullable(Int64), parsed text: "56"
ERROR: garbage after Nullable(Int64): ".40"

: While executing ParallelParsingBlockInputFormat:

```

**Comment by Avogar** [comment]
Did you try to increase setting `input_format_max_bytes_to_read_for_schema_inference` ? If your data contains a lot of columns, threashold on bytes could be reached before rows threashold

**Comment by shabir1** [comment]
thanks, @Avogar 
I only set input_format_max_rows_to_read_for_schema_inference=99999999 but it automatically set input_format_max_bytes_to_read_for_schema_inference=99999999.

Now i set input_format_max_rows_to_read_for_schema_inference = 1000000000 and input_format_max_bytes_to_read_for_schema_inference = 10000000000 , then it gives write schema
