### ISSUE TITLE
little memory can not combine data

### ISSUE THREAD

**Issue by unbeatablerabbit** [ClickHouse/ClickHouse#53399]
[About clickhouse to aggreate data from table1，2，3 to tableALL？](https://stackoverflow.com/questions/76897724/about-clickhouse-to-aggreate-data-from-table1-2-3-to-tableall)
0

I have a table in ClickHouse, where the columns of TABLE1 are DT, CUST_ID, and ONE, and TABLE2 has columns DT, CUST_ID, and TWO, and so on. DT represents time partition, CUST_ID serves as the unique primary key, while ONE, TWO, THREE... FIFTY represent numerical values. Currently, I have 50 tables like this, ranging from Table1 to Table50. I would like to aggregate them into one table, with columns DT, CUST_ID, ONE, TWO, THREE... FIFTY. table DDL LIKE THIS: CREATE TABLE TABLE1( 'DT' DATE, 'CUST_ID' STRING, 'ONE', )ENGINE = MERGEETREE(); CREATE TABLE TABLE2( 'DT' DATE, 'CUST_ID' STRING, 'TWO', )ENGINE = MERGEETREE();

I WANDER A TABLE LIKE THIS CREATE TABLE TABLE_ALL( 'DT' DATE, 'CUST_ID' STRING, 'ONE', 'TWO', ... 'FIFTY' )ENGINE = MERGEETREE(); clickhouse version：21.9 and table engine:mergeeTree() and if i use join table.the memory is oversize. if somebody can help me?3Q~

Can somebody give me solution? i use to try chatgpt .but union all and insert step by step is not enough.

**Comment by lampjian** [comment]
For such a mess of tables join situation, I recommend you to use presto or greenplum engine instead. Another feasible method of making wide tables on clickhouse is the step by step join with a reasonable amount tables.

**Comment by unbeatablerabbit** [comment]
> For such a mess of tables join situation, I recommend you to use presto or greenplum engine instead. Another feasible method of making wide tables on clickhouse is the step by step join with a reasonable amount tables.

哈哈，看你是中国人，我就用中文了，只能看到一个table用一列一列慢慢加工了

**Comment by lampjian** [comment]
合并数据打宽的工作应该在写入clickhouse之前就用程序做好了，有hive的话也可以做。 所以用clickhouse的话，在内存有限的情况下就不要想着一步到位了，滚雪球似的方式看起来可行。

**Comment by unbeatablerabbit** [comment]
其实内存是够的，只是用的比较蠢，其实也是巧妇难为无米之炊，上游数据推数，我们这边初加工数据，然后需要和表。所以只能在clickhouse做预聚合的作用，这个提问，就是问问各位老哥有啥关于clickhouse的好方法

**Comment by Algunenano** [comment]
Obsolete version and non reproducible issue
