### ISSUE TITLE
Unknown table function postgresql

### ISSUE THREAD

**Issue by DrivenA** [ClickHouse/ClickHouse#53396]
When I try to insert the data in the postrges database into the student table in clickhouse,
**INSERT INTO test.student SELECT * FROM postgresql('localhost:5432', 'postgres', 'test_table', 'postgres', '1313131','public');**
An error occurred：
Error: Code: 46, e.displayText() = DB::Exception: Unknown table function postgresql (version 20.8.3.18 (official build))
may I know what is the reason? Is it because my clickhouse version is too low?

**Comment by rschu1ze** [comment]
Yes, this is most likely caused by your ancient ClickHouse version. Please try again after [installing a recent version](https://clickhouse.com/docs/en/install).
