### ISSUE TITLE
Error using Catboost

### ISSUE THREAD

**Issue by leo29798** [ClickHouse/ClickHouse#5341]
Hi everyone,
I'm trying to use CatBoost and ClickHouse without Docker. When i use modelEvaluate in this [https://www.altinity.com/blog/2018/1/18/clickhouse-for-machine-learning](url), it has a bug.
Error messages:

> 2019.05.20 15:38:20.089694 [ 41 ] {c94982f5-956b-460e-a500-fb313cf39661} <Debug> executeQuery: (from 127.0.0.1:43680) SELECT      modelEvaluate('amazon',                    RESOURCE,                   MGR_ID,                   ROLE_ROLLUP_1,                   ROLE_ROLLUP_2,                   ROLE_DEPTNAME,                   ROLE_TITLE,                   ROLE_FAMILY_DESC,                   ROLE_FAMILY,                   ROLE_CODE) AS prediction,     1. / (1 + exp(-prediction)) AS probability,      ACTION AS target FROM amazon_train1 LIMIT 10
2019.05.20 15:38:20.124889 [ 46 ] {} <Error> BaseDaemon: ########################################
2019.05.20 15:38:20.125118 [ 46 ] {} <Error> BaseDaemon: (version 19.8.1.1) (from thread 41) Received signal Segmentation fault (11).
2019.05.20 15:38:20.125252 [ 46 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.05.20 15:38:20.125305 [ 46 ] {} <Error> BaseDaemon: Access: read.
2019.05.20 15:38:20.125340 [ 46 ] {} <Error> BaseDaemon: Unknown si_code.
2019.05.20 15:38:20.412861 [ 46 ] {} <Error> BaseDaemon: 0. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_get_use_count() const+0x10) [0xb35727e]
2019.05.20 15:38:20.413009 [ 46 ] {} <Error> BaseDaemon: 1. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::__weak_count<(__gnu_cxx::_Lock_policy)2>::_M_get_use_count() const+0x27) [0xb35b6ff]
2019.05.20 15:38:20.413085 [ 46 ] {} <Error> BaseDaemon: 2. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::__weak_ptr<DB::IExternalLoadable, (__gnu_cxx::_Lock_policy)2>::use_count() const+0x1c) [0x10158950]
2019.05.20 15:38:20.413172 [ 46 ] {} <Error> BaseDaemon: 3. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::__weak_ptr<DB::IExternalLoadable, (__gnu_cxx::_Lock_policy)2>::_M_assign(DB::IExternalLoadable*, std::__shared_count<(__gnu_cxx::_Lock_policy)2> const&)+0x20) [0x10157414]
2019.05.20 15:38:20.413241 [ 46 ] {} <Error> BaseDaemon: 4. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(void std::enable_shared_from_this<DB::IExternalLoadable>::_M_weak_assign<DB::IExternalLoadable>(DB::IExternalLoadable*, std::__shared_count<(__gnu_cxx::_Lock_policy)2> const&) const+0x2b) [0x101553f1]
2019.05.20 15:38:20.413440 [ 46 ] {} <Error> BaseDaemon: 5. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::enable_if<std::__shared_ptr<DB::IExternalLoadable, (__gnu_cxx::_Lock_policy)2>::__has_esft_base<DB::IExternalLoadable, void>::value, void>::type std::__shared_ptr<DB::IExternalLoadable, (__gnu_cxx::_Lock_policy)2>::_M_enable_shared_from_this_with<DB::IExternalLoadable, DB::IExternalLoadable>(DB::IExternalLoadable*)+0x5f) [0x10152027]
2019.05.20 15:38:20.413518 [ 46 ] {} <Error> BaseDaemon: 6. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::__shared_ptr<DB::IExternalLoadable, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<DB::IExternalLoadable, std::default_delete<DB::IExternalLoadable>, void>(std::unique_ptr<DB::IExternalLoadable, std::default_delete<DB::IExternalLoadable> >&&)+0xb2) [0x1014fa00]
2019.05.20 15:38:20.413597 [ 46 ] {} <Error> BaseDaemon: 7. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::shared_ptr<DB::IExternalLoadable>::shared_ptr<DB::IExternalLoadable, std::default_delete<DB::IExternalLoadable>, void>(std::unique_ptr<DB::IExternalLoadable, std::default_delete<DB::IExternalLoadable> >&&)+0x2c) [0x1014ddba]
2019.05.20 15:38:20.413667 [ 46 ] {} <Error> BaseDaemon: 8. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExternalLoader::finishReloadImpl(DB::ExternalLoader::LoadableCreationInfo const&, bool) const+0x63d) [0x1014b33d]
2019.05.20 15:38:20.413770 [ 46 ] {} <Error> BaseDaemon: 9. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExternalLoader::finishAllReloads(bool) const+0xd0) [0x1014ac8a]
2019.05.20 15:38:20.413838 [ 46 ] {} <Error> BaseDaemon: 10. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExternalLoader::reloadFromConfigFiles(bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x33b) [0x10149a6b]
2019.05.20 15:38:20.413906 [ 46 ] {} <Error> BaseDaemon: 11. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExternalLoader::reloadAndUpdate(bool)+0x90) [0x10148732]
2019.05.20 15:38:20.413969 [ 46 ] {} <Error> BaseDaemon: 12. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExternalLoader::initImpl(bool)+0x56) [0x101483f0]
2019.05.20 15:38:20.414034 [ 46 ] {} <Error> BaseDaemon: 13. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(void std::__invoke_impl<void, void (DB::ExternalLoader::*)(bool), DB::ExternalLoader*, bool&>(std::__invoke_memfun_deref, void (DB::ExternalLoader::*&&)(bool), DB::ExternalLoader*&&, bool&)+0x82) [0x1014fef5]
2019.05.20 15:38:20.414117 [ 46 ] {} <Error> BaseDaemon: 14. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::__invoke_result<void (DB::ExternalLoader::*)(bool), DB::ExternalLoader*, bool&>::type std::__invoke<void (DB::ExternalLoader::*)(bool), DB::ExternalLoader*, bool&>(void (DB::ExternalLoader::*&&)(bool), DB::ExternalLoader*&&, bool&)+0x57) [0x1014e320]
2019.05.20 15:38:20.414194 [ 46 ] {} <Error> BaseDaemon: 15. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::call_once<void (DB::ExternalLoader::*)(bool), DB::ExternalLoader*, bool&>(std::once_flag&, void (DB::ExternalLoader::*&&)(bool), DB::ExternalLoader*&&, bool&)::{lambda()#1}::operator()() const+0x52) [0x1014cb90]
2019.05.20 15:38:20.414265 [ 46 ] {} <Error> BaseDaemon: 16. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::call_once<void (DB::ExternalLoader::*)(bool), DB::ExternalLoader*, bool&>(std::once_flag&, void (DB::ExternalLoader::*&&)(bool), DB::ExternalLoader*&&, bool&)::{lambda()#2}::operator()() const+0x1f) [0x1014cbd5]
2019.05.20 15:38:20.414336 [ 46 ] {} <Error> BaseDaemon: 17. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::call_once<void (DB::ExternalLoader::*)(bool), DB::ExternalLoader*, bool&>(std::once_flag&, void (DB::ExternalLoader::*&&)(bool), DB::ExternalLoader*&&, bool&)::{lambda()#2}::_FUN()+0xe) [0x1014cbe6]
2019.05.20 15:38:20.414404 [ 46 ] {} <Error> BaseDaemon: 18. /lib/x86_64-linux-gnu/libpthread.so.0(+0xea99) [0x7f00bbb48a99]
2019.05.20 15:38:20.414499 [ 46 ] {} <Error> BaseDaemon: 19. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse() [0x10147d36]
2019.05.20 15:38:20.414578 [ 46 ] {} <Error> BaseDaemon: 20. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(void std::call_once<void (DB::ExternalLoader::*)(bool), DB::ExternalLoader*, bool&>(std::once_flag&, void (DB::ExternalLoader::*&&)(bool), DB::ExternalLoader*&&, bool&)+0x84) [0x1014cc7b]
2019.05.20 15:38:20.414633 [ 46 ] {} <Error> BaseDaemon: 21. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExternalLoader::init(bool)+0x54) [0x10148382]
2019.05.20 15:38:20.414699 [ 46 ] {} <Error> BaseDaemon: 22. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::Context::getExternalModelsImpl(bool) const+0x17c) [0x100fd186]
2019.05.20 15:38:20.414762 [ 46 ] {} <Error> BaseDaemon: 23. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::Context::getExternalModels() const+0x1d) [0x100fcbd7]
2019.05.20 15:38:20.414825 [ 46 ] {} <Error> BaseDaemon: 24. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::FunctionModelEvaluate::create(DB::Context const&)+0x2b) [0xb9d4ab7]
2019.05.20 15:38:20.414888 [ 46 ] {} <Error> BaseDaemon: 25. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::shared_ptr<DB::IFunctionBuilder> DB::FunctionFactory::createDefaultFunction<DB::FunctionModelEvaluate>(DB::Context const&)+0x33) [0xb9d75c7]
2019.05.20 15:38:20.414962 [ 46 ] {} <Error> BaseDaemon: 26. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::_Function_handler<std::shared_ptr<DB::IFunctionBuilder> (DB::Context const&), std::shared_ptr<DB::IFunctionBuilder> (*)(DB::Context const&)>::_M_invoke(std::_Any_data const&, DB::Context const&)+0x4e) [0xb4b5cac]
2019.05.20 15:38:20.415032 [ 46 ] {} <Error> BaseDaemon: 27. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::function<std::shared_ptr<DB::IFunctionBuilder> (DB::Context const&)>::operator()(DB::Context const&) const+0x60) [0x107c6e3e]
2019.05.20 15:38:20.415111 [ 46 ] {} <Error> BaseDaemon: 28. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::FunctionFactory::tryGet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context const&) const+0xba) [0x107c6992]
2019.05.20 15:38:20.415180 [ 46 ] {} <Error> BaseDaemon: 29. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::FunctionFactory::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context const&) const+0x5d) [0x107c6689]
2019.05.20 15:38:20.415247 [ 46 ] {} <Error> BaseDaemon: 30. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ActionsVisitor::visit(std::shared_ptr<DB::IAST> const&)+0xd85) [0x10b24e99]
2019.05.20 15:38:20.415310 [ 46 ] {} <Error> BaseDaemon: 31. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ActionsVisitor::visit(std::shared_ptr<DB::IAST> const&)+0x2200) [0x10b26314]
2019.05.20 15:38:20.415373 [ 46 ] {} <Error> BaseDaemon: 32. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExpressionAnalyzer::getRootActions(std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ExpressionActions>&, bool)+0x11f) [0x10a090a1]
2019.05.20 15:38:20.415440 [ 46 ] {} <Error> BaseDaemon: 33. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::ExpressionAnalyzer::appendSelect(DB::ExpressionActionsChain&, bool)+0xdd) [0x10a0cae5]
2019.05.20 15:38:20.415504 [ 46 ] {} <Error> BaseDaemon: 34. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::InterpreterSelectQuery::analyzeExpressions(DB::QueryProcessingStage::Enum, bool, std::shared_ptr<DB::FilterInfo> const&)+0xc3c) [0x1018cfa2]
2019.05.20 15:38:20.415571 [ 46 ] {} <Error> BaseDaemon: 35. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x633) [0x1018de05]
2019.05.20 15:38:20.415650 [ 46 ] {} <Error> BaseDaemon: 36. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x1421) [0x1018b3ed]
2019.05.20 15:38:20.415775 [ 46 ] {} <Error> BaseDaemon: 37. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x7b) [0x10189b23]
2019.05.20 15:38:20.415949 [ 46 ] {} <Error> BaseDaemon: 38. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::_MakeUniq<DB::InterpreterSelectQuery>::__single_object std::make_unique<DB::InterpreterSelectQuery, std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&>(std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x82) [0x101c9b13]
2019.05.20 15:38:20.416082 [ 46 ] {} <Error> BaseDaemon: 39. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x858) [0x101c8242]
2019.05.20 15:38:20.416158 [ 46 ] {} <Error> BaseDaemon: 40. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(std::_MakeUniq<DB::InterpreterSelectWithUnionQuery>::__single_object std::make_unique<DB::InterpreterSelectWithUnionQuery, std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions>(std::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&&)+0x8e) [0x1016e866]
2019.05.20 15:38:20.416227 [ 46 ] {} <Error> BaseDaemon: 41. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum)+0x143) [0x1016d7e9]
2019.05.20 15:38:20.416287 [ 46 ] {} <Error> BaseDaemon: 42. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse() [0x103b73f6]
2019.05.20 15:38:20.416379 [ 46 ] {} <Error> BaseDaemon: 43. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0xd5) [0x103b82c0]
2019.05.20 15:38:20.416450 [ 46 ] {} <Error> BaseDaemon: 44. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::TCPHandler::runImpl()+0xafd) [0xb34c3fd]
2019.05.20 15:38:20.416512 [ 46 ] {} <Error> BaseDaemon: 45. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(DB::TCPHandler::run()+0x33) [0xb350cad]
2019.05.20 15:38:20.416574 [ 46 ] {} <Error> BaseDaemon: 46. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(Poco::Net::TCPServerConnection::start()+0x24) [0x112c5294]
2019.05.20 15:38:20.416635 [ 46 ] {} <Error> BaseDaemon: 47. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(Poco::Net::TCPServerDispatcher::run()+0x17e) [0x112c5992]
2019.05.20 15:38:20.416696 [ 46 ] {} <Error> BaseDaemon: 48. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse(Poco::PooledThread::run()+0x98) [0x113e7396]
2019.05.20 15:38:20.416756 [ 46 ] {} <Error> BaseDaemon: 49. /root/ClickHouse/cmake-build-debug-gcc-7/dbms/programs/clickhouse() [0x113e359b]

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

I can't fix this. Can anyone help me?.

**Comment by alexey-milovidov** [comment]
How do you build ClickHouse? Does the issue reproduce if you use the official packages?

**Comment by leo29798** [comment]
I just run the clickhouse-server and execute query by clickhouse-client as release.Then I execute the query in the link and I have a bug when I use modelEvaluate function.

**Comment by alexey-milovidov** [comment]
This part of code (loading of external models) was rewritten since then.
