### ISSUE TITLE
date32 is bigger when using clickhouse-go

### ISSUE THREAD

**Issue by Inasayang** [ClickHouse/ClickHouse#53415]
ddl
```sql
CREATE TABLE test
(
    `a` String,
    `b` Date32
)
ENGINE = MergeTree
ORDER BY a
SETTINGS index_granularity = 8192;
```

```go
func TestDate32(t *testing.T) {
	conn := NewConn()
	batch, err := conn.PrepareBatch(context.Background(), fmt.Sprintf("%s%s", `INSERT INTO `, `test`))
	if err != nil {
		t.Fatal(err)
	}
	if err := batch.Append(
		`aaa`,
		`2000-01-01`,
	); err != nil {
		t.Fatal(err)
	}
	if err := batch.Send(); err != nil {
		t.Fatal(err)
	}
}
```

result
![image](https://github.com/ClickHouse/ClickHouse/assets/30060632/97a5ca5b-5b7b-465b-9a0a-8053a5c333a8)
There's a 45-year difference. I'm not sure what the problem is? I don't think it's the time zone.

But when executed in the terminal, it works fine
![image](https://github.com/ClickHouse/ClickHouse/assets/30060632/80d9f6b8-db96-47aa-8d39-38effe3f511f)

**Comment by lampjian** [comment]
Maybe you can find some details from `system.query_log` table. And try a newer version or insert method of clickhouse-go driver for testing.

**Comment by Inasayang** [comment]
currently replaced DATE32 with DATETIME and it works fine.
But the solution for DATE32 is still unknown.

**Comment by alexey-milovidov** [comment]
You should direct your question to the ClickHouse Go repository.
