### ISSUE TITLE
clickhouse pods restart frequently

### ISSUE THREAD

**Issue by beordie** [ClickHouse/ClickHouse#53435]
we have a clickhouse in kubernetes, it's pods will restart after running for a period of time, although nobody to use it.

**Comment by beordie** [comment]
Some logs are as follows:
`0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb371dfa in /usr/bin/clickhouse
1. DB::Exception::Exception<char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*&&, char const*&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) @ 0xb389e4c in /usr/bin/clickhouse
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb389a44 in /usr/bin/clickhouse
3. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb389469 in /usr/bin/clickhouse
4. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb389469 in /usr/bin/clickhouse
5. DB::Memory<Allocator<false, false> >::alloc() @ 0xb3bedcd in /usr/bin/clickhouse
6. DB::WriteBufferFromFile::WriteBufferFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, int, unsigned int, char*, unsigned long) @ 0xb4aba8e in /usr/bin/clickhouse
7. DB::DiskLocal::writeFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, DB::WriteMode) @ 0x15345977 in /usr/bin/clickhouse
8. DB::MergeTreeDataPartWriterOnDisk::Stream::Stream(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDisk>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, unsigned long) @ 0x1638d8a3 in /usr/bin/clickhouse
9. ? @ 0x16397e72 in /usr/bin/clickhouse
10. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, DB::ISerialization::SubstreamData const&) const @ 0x1520b8f1 in /usr/bin/clickhouse
11. DB::ISerialization::enumerateStreams(DB::ISerialization::SubstreamPath&, std::__1::function<void (DB::ISerialization::SubstreamPath const&)> const&, std::__1::shared_ptr<DB::IDataType const> const&) const @ 0x1520be75 in /usr/bin/clickhouse
12. DB::MergeTreeDataPartWriterWide::addStreams(DB::NameAndTypePair const&, std::__1::shared_ptr<DB::IAST> const&) @ 0x163913cc in /usr/bin/clickhouse
13. DB::MergeTreeDataPartWriterWide::MergeTreeDataPartWriterWide(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) @ 0x163911ea in /usr/bin/clickhouse
14. DB::MergeTreeDataPartWide::getWriter(DB::NamesAndTypesList const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec> const&, DB::MergeTreeWriterSettings const&, DB::MergeTreeIndexGranularity const&) const @ 0x16381902 in /usr/bin/clickhouse
15. DB::MergedBlockOutputStream::MergedBlockOutputStream(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > > const&, std::__1::shared_ptr<DB::ICompressionCodec>, bool, bool) @ 0x1646700c in /usr/bin/clickhouse
16. void std::__1::allocator_traits<std::__1::allocator<DB::MergedBlockOutputStream> >::__construct<DB::MergedBlockOutputStream, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>&, DB::NamesAndTypesList&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > >, std::__1::shared_ptr<DB::ICompressionCodec>&, bool, bool&>(std::__1::integral_constant<bool, true>, std::__1::allocator<DB::MergedBlockOutputStream>&, DB::MergedBlockOutputStream*, std::__1::shared_ptr<DB::IMergeTreeDataPart>&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const>&, DB::NamesAndTypesList&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeIndex const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeIndex const> > >&&, std::__1::shared_ptr<DB::ICompressionCodec>&, bool&&, bool&) @ 0x162cd2de in /usr/bin/clickhouse
17. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::prepare() @ 0x162c22dc in /usr/bin/clickhouse
18. bool std::__1::__function::__policy_invoker<bool ()>::__call_impl<std::__1::__function::__default_alloc_func<DB::MergeTask::ExecuteAndFinalizeHorizontalPart::subtasks::'lambda'(), bool ()> >(std::__1::__function::__policy_storage const*) @ 0x162d0909 in /usr/bin/clickhouse
19. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x162c6e8b in /usr/bin/clickhouse
20. DB::MergeTask::execute() @ 0x162cbdda in /usr/bin/clickhouse
21. DB::MergePlainMergeTreeTask::executeStep() @ 0x162bd70c in /usr/bin/clickhouse
22. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xb3490ab in /usr/bin/clickhouse
23. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xb348cf9 in /usr/bin/clickhouse
24. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb41be8a in /usr/bin/clickhouse
25. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb41e024 in /usr/bin/clickhouse
26. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb419257 in /usr/bin/clickhouse
27. ? @ 0xb41cddd in /usr/bin/clickhouse
28. ? @ 0x7f15ec431609 in ?
29. __clone @ 0x7f15ec356133 in ?
 (version 22.3.7.28 (official build))
2023.08.06 18:35:49.791928 [ 58 ] {} <Debug> MemoryTracker: Peak memory usage Mutate/Merge: 4.07 MiB.
2023.08.06 18:35:49.916488 [ 43 ] {} <Information> Application: Received termination signal (Terminated)
2023.08.06 18:35:49.916626 [ 1 ] {} <Debug> Application: Received termination signal.
2023.08.06 18:35:49.916697 [ 1 ] {} <Debug> Application: Waiting for current connections to close.`

**Comment by cangyin** [comment]
```
2023.08.06 18:35:49.916488 [ 43 ] {} <Information> Application: Received termination signal (Terminated)
```
From the log, I can only tell that clickhouse-server is killed by k8s.

```
2. MemoryTracker::allocImpl(long, bool, MemoryTracker*) @ 0xb389a44 in /usr/bin/clickhouse
```
an possibly because of OOM (Out-Of-Memory)

check  `Reason` in output of
```
kubectl describe pod <you-clickhouse-pod-name> | grep -A4 'Last State'
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 19 Jul 2023 16:14:13 +0800
      Finished:     Thu, 03 Aug 2023 19:03:19 +0800
```

**Comment by alexey-milovidov** [comment]
The problem is related to your configuration of Kubernetes, not to ClickHouse itself.

**Comment by beordie** [comment]
> The problem is related to your configuration of Kubernetes, not to ClickHouse itself.

I'm sorry there was something wrong yesterday. But i can't find any events in my pods, everything looks fine from the outside.
```
kubectl get pod -n clickhouse-2-3
NAME                                        READY   STATUS    RESTARTS   AGE
chi-clickhouse-76ca8277-ch-cluster1-0-0-0   1/1     Running   0          46h
chi-clickhouse-76ca8277-ch-cluster1-0-1-0   1/1     Running   0          46h
chi-clickhouse-76ca8277-ch-cluster1-1-0-0   1/1     Running   0          3h46m
chi-clickhouse-76ca8277-ch-cluster1-1-1-0   1/1     Running   0          3h52m
```
