### ISSUE TITLE
Compile Error: code will never be executed [-Werror,-Wunreachable-code]

### ISSUE THREAD

**Issue by Alima777** [ClickHouse/ClickHouse#53436]
I encountered an error when compiling the `master` branch.

The error message is:
```
ClickHouse/src/Functions/transform.cpp:780:29: error: code will never be executed [-Werror,-Wunreachable-code]
                            dst += sizeof(key) - ref.size;
```
                            
It seems it was introduced by this PR https://github.com/ClickHouse/ClickHouse/pull/53015.

I'm not sure it's a mistake or not.

**Comment by cangyin** [comment]
I suggest compile stable branch. `master` branch is under frequent development and update.

**Comment by Alima777** [comment]
OK, just to point out the problem, if it's a bug, it can be fixed.

**Comment by tavplubix** [comment]
That's expected.

Looks like you use an old compiler like clang-15. You should upgrade to clang-16 or deal with compilation errors on your own.

However, this issue will be fixed by https://github.com/ClickHouse/ClickHouse/pull/53164/commits/368f6d7b1390b98ccac2610eb88a4237abcab439
