### ISSUE TITLE
Allow editing query in clickhouse-client with external `$EDITOR`

### ISSUE THREAD

**Issue by hkrutzer** [ClickHouse/ClickHouse#53469]
**Use case**

Allow easier editing of (possibly long) queries in clickhouse-client,
with editors such as vim, emacs, nano, VS Code etc.

**Describe the solution you'd like**

Various shells like bash and fish allow editing the command you are writing
in an external editor. In bash you can press `<C-x><C-e>` to trigger this.
This works by opening a temp file in the editor.

It would be great if clickhouse-client could also support this; allowing to press
ctrl+e to open the current command in an editor so that complex queries
can be changed more quickly.

**Comment by mkmkme** [comment]
Could you assign it to me please?

**Comment by amosbird** [comment]
Have you tried `Alt-Shift-e` ?

**Comment by hkrutzer** [comment]
Very nice

**Comment by den-crane** [comment]
hm, 
Alt-Shift-e (cmd+shit+e) does not work in iterm, it seems iterm has own binding `show timestamps` for this shortcut, and no way to change it.

**Comment by cangyin** [comment]
> Have you tried `Alt-Shift-e` ?

In MobaXterm:

```
:) <Alt-Shift-e>
:) Bye.
```
It quits.

**Comment by amosbird** [comment]
> it seems iterm has own binding show timestamps for this shortcut, and no way to change it.

Heh. I guess both iterm and clickhouse-client have a secret pact to make you memorize their hotkeys...

**Comment by hkrutzer** [comment]
@den-crane I don't usually use iTerm but when I tried it, it works with cmd+option+e

**Comment by mkmkme** [comment]
@den-crane on macOS, you need to press and release Esc as the Meta modifier.

So on my macOS, on both iTerm and macOS terminal, I have to:
1. Press Esc
2. Release Esc
3. Press Shift + e at the same time

**Comment by den-crane** [comment]
> @den-crane on macOS, you need to press and release Esc as the Meta modifier.
> 
> So on my macOS, on both iTerm and macOS terminal, I have to:
> 
>     1. Press Esc
> 
>     2. Release Esc
> 
>     3. Press Shift + e at the same time

yes, thanks, this works.
