### ISSUE TITLE
about force kill query 

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#53476]
on version of 23.7 ,  max_execution_time  default set 0.
Some queries took a long time to execute（several hours）
I passed the kill query where query_id = 'xx', but it didn't take effect
 :)  select query_id,elapsed from system.processes;

SELECT
    query_id,
    elapsed
FROM system.processes

Query id: a094b32a-c183-4220-8a39-f107b7e88439

┌─query_id─────────────────────────────┬──────elapsed─┐
│ 70ca643c-5ebc-48a6-96e3-dbcb4787c6f7 │ 15645.296853 │
│ e0237b57-e05e-4729-a701-3253c644218b │ 13405.845054 │
│ ff3f6b04-cd0c-46c2-8c66-8194413a0aad │ 13364.020665 │
│ 795e5e71-54c7-464e-9d94-9343397e6d69 │     0.022193 │
│ a094b32a-c183-4220-8a39-f107b7e88439 │     0.000518 │
└──────────────────────────────────────┴──────────────┘

Is there any way to directly close these queries？

**Comment by yangshike** [comment]
kill query

**Comment by lampjian** [comment]
By default, the asynchronous version of killing queries is used (ASYNC), which does not wait for confirmation that queries have stopped.Try sync query kill.[Kill Statements](https://clickhouse.com/docs/zh/sql-reference/statements/kill)

**Comment by yangshike** [comment]
SELECT
    query_id,
    query,
    elapsed
FROM system.processes
WHERE elapsed > 1000

Query id: 99d935e2-d439-44b9-8fa3-2a6d3c7a482a

┌─query_id─────────────────────────────┬─query──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────elapsed─┐
│ 82c3f0b9-7257-4804-89af-88b9750b5d02 │ select name as table_name, database schema_name, metadata_modification_time as create_time, metadata_modification_time as last_ddl_time, '' description,0 as  store_capacity,0 data_bytes,0 index_bytes, '' encoding, '' as collation, 0 num_rows,engine from system.tables where database = 'src_knowledge_wh'  order by 1
FORMAT TabSeparatedWithNamesAndTypes; │ 8114.318887 │
│ 1776c24f-2870-42c4-b6cc-f826beb1e7be │ select name as table_name, database schema_name, metadata_modification_time as create_time, metadata_modification_time as last_ddl_time, '' description,0 as  store_capacity,0 data_bytes,0 index_bytes, '' encoding, '' as collation, 0 num_rows,engine from system.tables where database = 'src_knowledge_wh'  order by 1
FORMAT TabSeparatedWithNamesAndTypes; │ 8112.950318 │

**Comment by yangshike** [comment]
Kill query_ id  async/sync ,I've tried it all before.
When use sync

I waited for a long time before canceling.


Now, these two queries are still being executed..

**Comment by yangshike** [comment]
SELECT query_id, elapsed,is_cancelled FROM system.processes where elapsed > 1000;

SELECT
    query_id,
    elapsed,
    is_cancelled
FROM system.processes
WHERE elapsed > 1000

Query id: 144754d8-b1d7-4238-b3e3-37c70bfb3a94

┌─query_id─────────────────────────────┬─────elapsed─┬─is_cancelled─┐
│ 82c3f0b9-7257-4804-89af-88b9750b5d02 │ 9567.143024 │            1 │
│ 1776c24f-2870-42c4-b6cc-f826beb1e7be │ 9565.774449 │            1 │
└──────────────────────────────────────┴─────────────┴──────────────┘

**Comment by yangshike** [comment]
In order to make this query disappear, I tried the following methods but failed，Query still exists


1. drop database src__ xx

2. prohibiting the connection of the query initiator IP (iptables - I Input - s (this query initiator IP) - p TCP -- dport 8123- j DROP)

**Comment by yangshike** [comment]
The connection to the source IP is no longer visible from the network layer, but this query is still in the process list

[root@clickhouse02 ~]# netstat -an| grep "this query initiator IP"|grep ESTABLISHED|wc -l
0

**Comment by yangshike** [comment]
This process disappeared after 20864795 ms.


I don't know why this value is related to other values, but I didn't see similar values in the configuration

**Comment by alexey-milovidov** [comment]
KILL QUERY instructs the query to stop. But the query could spend a considerable amount of time before checking that it has to stop.
