### ISSUE TITLE
Clickhouse table schema seems impossible to reproduce via SQL vs Parquet

### ISSUE THREAD

**Issue by crodwell** [ClickHouse/ClickHouse#53510]
Cannot create a schema via SQL that matches parquet when field is an Array of items.

I have a parquet file that contains an array of 2 field objects

`############ Column(Provider) ############
name: Provider
path: Identity.list.element.Provider
max_definition_level: 4
max_repetition_level: 1
physical_type: BYTE_ARRAY
logical_type: String
converted_type (legacy): UTF8
compression: SNAPPY (space_saved: -5%)

############ Column(Id) ############
name: Id
path: Identity.list.element.Id
max_definition_level: 4
max_repetition_level: 1
physical_type: BYTE_ARRAY
logical_type: String
converted_type (legacy): UTF8
compression: SNAPPY (space_saved: -5%)`

When I create the schema  via

`CREATE TABLE imported_from_parquet
ENGINE = MergeTree
ORDER BY tuple() AS
SELECT *
FROM file('data.parquet', Parquet)`

The Identity column is created  as a Type `Array(Tuple(Provider Nullable(String), Id Nullable(String)))`

Loading from parquet works.  
If I then dump the schema using `SHOW CREATE TABLE imported_from_parquet`, the Identity column definition is represented in SQL as `Identity Array(Tuple(Provider Nullable(String), Id Nullable(String))),`
Looks correct.
but now if I recreate the table via SQL. The Identity column gets split into
```
Identity.Provider (Array(Nullable(String)))
Identity.Id (Array(Nullable(String)))
```

on the face of it, it may be the same thing, but loading the file via parquet  no longer valid using `INSERT INTO imported_from_parquet
FROM INFILE 'data.parquet' FORMAT Parquet;` 
Now fails because the columns do not match.

There's certain workarounds like 
```               
select
     Identity.1 as `Identity.Provider`,
     Identity.2 as `Identity.Id`,
```

when inserting from parquet, but as I have a large schema it would be must better if I didnt need to maintain this sql when inserting. 

How can I ensure Identity stays as one column when creating via SQL Create Table?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/settings/settings#flatten-nested

flatten_nested=1 for the backward compatibility.


```sql

create table imported_from_parquet ( Identity Array(Tuple(Provider Nullable(String), Id Nullable(String))) ) Engine=Log;

desc imported_from_parquet;
┌─name──────────────┬─type────────────────────┬─
│ Identity.Provider │ Array(Nullable(String)) │
│ Identity.Id       │ Array(Nullable(String)) │
└───────────────────┴─────────────────────────┴─

drop table imported_from_parquet;

set flatten_nested=0;

create table imported_from_parquet ( Identity Array(Tuple(Provider Nullable(String), Id Nullable(String))) ) Engine=Log;

desc imported_from_parquet;
┌─name─────┬─type─────────────────────────────────────────────────────────┬─
│ Identity │ Array(Tuple(Provider Nullable(String), Id Nullable(String))) │
└──────────┴──────────────────────────────────────────────────────────────┴─
```

**Comment by crodwell** [comment]
Thank you @den-crane, I wasted a few days on that.

**Comment by crodwell** [comment]
Hi @den-crane . This doesn't work for me in Clickhouse v23.7.2.25.
