### ISSUE TITLE
Backup to S3 being interrupted & aborted by Rate Limiting

### ISSUE THREAD

**Issue by lazywei** [ClickHouse/ClickHouse#53532]
**Describe what's wrong**

Backup to S3 with server-side copy can be interrupted if encountered AWS rate limiting.

**Does it reproduce on recent release?**

Version 23.6.2.18

**How to reproduce**

* Setting `backup_threads = 400`, `max_backups_io_thread_pool_size=6000`
* Run `BACKUP DATABASE default TO S3('...')`
* Check the backup status and got following
```
BACKUP_FAILED

Code: 499. DB::Exception: Please reduce your request rate. (S3_ERROR) (version 23.6.2.18 (official build))"
, reason: Code: 499. DB::Exception: Please reduce your request rate. (S3_ERROR) (version 23.6.2.18 (official build)
```

**Expected behavior**

ClickHouse should re-try the AWS S3 api call with backoff when encountered the rate limiting the first time.

**Error message and/or stacktrace**

```
Code: 499. DB::Exception: Please reduce your request rate. (S3_ERROR) (version 23.6.2.18 (official build))"
, reason: Code: 499. DB::Exception: Please reduce your request rate. (S3_ERROR) (version 23.6.2.18 (official build)
```

**Additional context**

Our DB size (on S3) is around 70 TiB. We do have continuous ingestion load so not sure if this rate limiting happens on the source bucket or the destination bucket. But either way, it might be a good thing to have CH retry whatever failed for a few times before actually giving up the backup completely.

**Comment by alexey-milovidov** [comment]
I recall it was fixed in https://github.com/ClickHouse/ClickHouse/pull/52441

**Comment by alexey-milovidov** [comment]
Version 23.8 is released, video: https://www.youtube.com/watch?v=d1_pyoWcydk
