### ISSUE TITLE
Left outer join appears not to use PrimaryKey/Order by of Table

### ISSUE THREAD

**Issue by joshbartley** [ClickHouse/ClickHouse#53530]
**Describe the situation**
I have a query like the below where a table is joined to itself using a left outer join. The table is build with a Tenant ID and as the Order By of the ReplicagedMergeTree table.

```sql
CREATE TABLE Records
(
TenantID Int64,
RecordID Int64,
SubRecordID Int64,
LastUpdatedOnUTC DateTime64(3, 'UTC')
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', LastUpdatedOnUTC)
PRIMARY KEY (TenantID , RecordID )
ORDER BY (TenantID , RecordID )
```

Lets assume the Records table has 10,000,000 records in it and Tenant ID 1 only has 20,000 records.

This query will return quickly and the query states show it will read ~20,000 records
`select RecordID from Records where TenantID=1`

This query will return very slowly and query states show it will read ~10,000,000 records which is the entire table.

`select r.RecordID from Records r left outer join Records subs on subs.TenantID=1 and subs.RecordID=r.SubRecordID  where r.TenantID=1`

* Which ClickHouse server version to use
23.7.1.2470

**Expected performance**
I would expected ClickHouse to use the sort order of the table and filter on the TenantId instead of a full table scan of the table to satisfy the join condition. In MS SQL, this would be a nested loop join and would use the Primary Key or an Index (I know these don't really exist the same way here) to make the join faster with less CPU and IO. 

**Additional context**
CPU usage different when the left outer join was dropped.

![image](https://github.com/ClickHouse/ClickHouse/assets/5738532/6d86642a-3e4d-46d5-bb5e-45eb68965893)

**Comment by den-crane** [comment]
1. Clickhouse does not have NestedLoop algorithm.
2.  Clickhouse does not have PureMerge algorithm, does not use indexes and order of rows in joins
3. Clickhouse uses order of rows indirectly in partial hash join algorithm, sort of sorted set is faster.

**Comment by joshbartley** [comment]
So should the docs be updated with @UnamedRus example of how to properly write a join to use the sort order of the table? I think if this isn't something that will ever be on the roadmap it should at least be documented and there is no mention of this performance issue. I'm assuming tools like Metabase also don't write join statements like this.

**Comment by UnamedRus** [comment]
My join doesn't use sort order of table, it just pushdown condition to subquery (so ORDER BY index can be used), which at least something.

> I think if this isn't something that will ever be on the roadmap

It's actually planned to make joins smarter after analyzer will be merged

**Comment by joshbartley** [comment]
Thank you again @UnamedRus  With the issue being closed I thought it wasn't going be addressed and I appreciate the additional information.
