### ISSUE TITLE
Make KeyCondition usable outside *MergeTree when analyzer is enabled

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#53536]
If I'm reading the code correctly:
 * when analyzer is enabled, `SelectQueryInfo::filter_asts` doesn't have sets, and is probably missing some casts,
 * so, KeyCondition shouldn't use it,
 * instead it should use `SelectQueryInfo::filter_actions_dag`,
 * which is assigned only in ReadFromMergeTree::applyFilters().

So, any code using KeyCondition without a merge tree won't work. Currently that's just StorageHive, which uses KeyCondition to skip files based on their min/max statistics. (I didn't test if it's actually broken with analyzer, so maybe I'm misreading the code and it actually works.) And https://github.com/ClickHouse/ClickHouse/pull/52951 added KeyCondition to Parquet reader (to skip row groups), and I'm not sure how to make it work with analyzer.

What's the intended way for this to work? Should `filter_actions_dag` be built by some non-merge-tree code, before IStorage::read() calls? Or should it be built lazily by whoever needs it first? Should everything work completely differently (e.g. non-merge-tree filter pushdowns shouldn't use KeyCondition?)?

**Comment by alexey-milovidov** [comment]
Let's propagate this field for all queries, regardless of the table engine.

**Comment by kitaisreal** [comment]
All engines should use KeyCondition. It is not necessary to have `filter_actions_dag` in `SelectQueryInfo`.
To properly get filters you need use `SourceStepWithFilter`, then filters will be added to this step during `optimizePrimaryKeyCondition` query plan optimization.
For example check how `StorageSystemZooKeeper` read is implemented, this storage requires filters to correctly extract necessary paths to read.
If you need filters in `IStorage` before `read` method is called, for example in `getQueryProcessingStage` then it is required to add your storage here https://github.com/ClickHouse/ClickHouse/pull/52762.

**Comment by Algunenano** [comment]
This would also be useful to do decide on how many parallel replicas to use based on primary key analysis (https://github.com/ClickHouse/ClickHouse/pull/52762/ should help making https://github.com/ClickHouse/ClickHouse/pull/51692 for the analyzer)

**Comment by taiyang-li** [comment]
Closed by https://github.com/ClickHouse/ClickHouse/pull/55330. In which I has a minor refactor on parquet filter push down by replaceing `setQueryInfo` by `setKeyCondition` in , which make it possible to reuse interface `SourceStepWithFilter::applyFilters`

**Comment by taiyang-li** [comment]
fixed by https://github.com/ClickHouse/ClickHouse/pull/55330

**Comment by al13n321** [comment]
> All engines should use KeyCondition. It is not necessary to have filter_actions_dag in SelectQueryInfo.
To properly get filters you need use SourceStepWithFilter, then filters will be added to this step during optimizePrimaryKeyCondition query plan optimization.
For example check how StorageSystemZooKeeper read is implemented, this storage requires filters to correctly extract necessary paths to read.
If you need filters in IStorage before read method is called, for example in getQueryProcessingStage then it is required to add your storage here https://github.com/ClickHouse/ClickHouse/pull/52762.

Not sure how to make that work.

The `ActionDAGNodes` passed to `ReadFromFile::applyFilters()` refers to table columns using `ActionsDAG::Node` of type `INPUT` with `result_name` like `__table1.x` instead of `x`. How can the `IStorage` to know that "`__table1.x`" refers to this table's column `x`? (`StorageFile::read()` gets `column_names` without the `__table1.` prefix.)

`StorageSystemZookeeper` doesn't run into this problem because the `ActionDAGNodes` passed to `ReadFromSystemZooKeeper::applyFilters()` is different for some reason: columns are `ActionsDAG::Node` of type `ALIAS`, pointing to `ActionsDAG::Node` of type `INPUT` with `result_name` like `path` (no "`__table1.`").
