### ISSUE TITLE
Add column `name` to system.clusters as an alias to `cluster`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#53538]
**Use case**

```
SELECT * FROM system.clusters WHERE name = 'default'
```

> maybe you meant: 'shard_num', 'database_replica_name', 'host_name', 'shard_weight', 'user', 'database_shard_name', 'port', 'default_database', 'errors_count', 'is_local', 'host_address', 'slowdowns_count', 'estimated_recovery_time', 'replica_num', 'cluster' or 'is_active'.

**Comment by irenjj** [comment]
I'd like to take this task.

**Comment by techkuz** [comment]
@alexey-milovidov can there be multiple aliases?

**Comment by alexey-milovidov** [comment]
@techkuz, yes, a table can have multiple alias columns, even if they are pointing to the same source.
