### ISSUE TITLE
 Failed to make request to: oss 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#53537]
Error log : 

2023.08.16 08:53:46.321427 [ 40528 ] {} <Error> CertificateReloader: Cannot obtain modification time for key file /etc/clickhouse-server/server.key, skipping update. errno: 2, strerror: No
 such file or directory
2023.08.16 08:53:46.340130 [ 40528 ] {} <Error> CertificateReloader: Poco::Exception. Code: 1000, e.code() = 0, SSL context exception: Error loading private key from file /etc/clickhouse-s
erver/server.key: error:02000002:system library:OPENSSL_internal:No such file or directory (version 23.3.5.9 (official build))
2023.08.16 08:53:47.254277 [ 40528 ] {} <Warning> Context: Table system.session_log is enabled. It's unreliable and may contain garbage. Do not use it for any kind of security monitoring.
2023.08.16 08:54:00.530480 [ 41012 ] {} <Error> AWSClient: Failed to make request to: http://taqu-online-clickhouse.oss-cn-zhangjiakou-internal.aliyuncs.com/ck/disk_oss/wxjsocsxedeayxecyqh
txdsiwfpjizay: Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 100.118.90.245:80, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) @ 0x17919d19 in /usr/bin/clickhouse
1. Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) @ 0x178fead6 in /usr/bin/clickhouse
2. Poco::Net::HTTPClientSession::reconnect() @ 0x178f08c1 in /usr/bin/clickhouse
3. Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) @ 0x178efa63 in /usr/bin/clickhouse
4. DB::S3::PocoHTTPClient::makeRequestInternal(Aws::Http::HttpRequest&, std::shared_ptr<DB::S3::PocoHTTPResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::R
ateLimiterInterface*) const @ 0x1275f1ad in /usr/bin/clickhouse
5. DB::S3::PocoHTTPClient::MakeRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const @
 0x1275d05c in /usr/bin/clickhouse
6. Aws::Client::AWSClient::AttemptOneRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::AmazonWebServiceRequest const&, char const*, char const*, char const*) const @ 0x17aff009
in /usr/bin/clickhouse
7. Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @ 0x17afc172
in /usr/bin/clickhouse
8. Aws::Client::AWSClient::MakeRequestWithUnparsedResponse(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @
 0x17b03b05 in /usr/bin/clickhouse
9. Aws::S3::S3Client::GetObject(Aws::S3::Model::GetObjectRequest const&) const @ 0x17c104d9 in /usr/bin/clickhouse
10. DB::S3::Client::GetObject(DB::S3::ExtendedRequest<Aws::S3::Model::GetObjectRequest> const&) const @ 0x1274351f in /usr/bin/clickhouse
11. DB::ReadBufferFromS3::initialize() @ 0x1277a9b5 in /usr/bin/clickhouse
12. DB::ReadBufferFromS3::nextImpl() @ 0x127784f1 in /usr/bin/clickhouse
13. DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x12c41731 in /usr/bin/clickhouse
14. DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x12c41370 in /usr/bin/clickhouse
15. DB::AsynchronousReadIndirectBufferFromRemoteFS::nextImpl() @ 0x12c43f26 in /usr/bin/clickhouse
16. DB::MergeTreeDataPartCompact::loadIndexGranularityImpl(DB::MergeTreeIndexGranularity&, DB::MergeTreeIndexGranularityInfo const&, unsigned long, DB::IDataPartStorage const&) @ 0x145aa74
e in /usr/bin/clickhouse
17. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x1448429e in /usr/bin/clickhouse
18. DB::MergeTreeData::loadDataPart(DB::MergeTreePartInfo const&, String const&, std::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, std::mutex&) @ 0x145023d5 in /usr/bin/clickh
ouse
19. ? @ 0x1458fb64 in /usr/bin/clickhouse
20. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe2af6c5 in /usr/bin/clickhouse
21. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadF
romGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_stora
ge const*) @ 0xe2b2235 in /usr/bin/clickhouse
22. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe2ab493 in /usr/bin/clickhouse
23. ? @ 0xe2b1101 in /usr/bin/clickhouse
24. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
25. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.3.5.9 (official build))
2023.08.16 08:54:02.942474 [ 41343 ] {} <Error> AWSClient: Failed to make request to: http://taqu-online-clickhouse.oss-cn-zhangjiakou-internal.aliyuncs.com/ck/disk_oss/quiitutpoirehdaottn
dtgpqueaudwdl: Poco::Exception. Code: 1000, e.code() = 0, Timeout: connect timed out: 100.118.90.245:80, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) @ 0x17919d19 in /usr/bin/clickhouse
1. Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) @ 0x178fead6 in /usr/bin/clickhouse
2. Poco::Net::HTTPClientSession::reconnect() @ 0x178f08c1 in /usr/bin/clickhouse
3. Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) @ 0x178efa63 in /usr/bin/clickhouse
4. DB::S3::PocoHTTPClient::makeRequestInternal(Aws::Http::HttpRequest&, std::shared_ptr<DB::S3::PocoHTTPResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::R
ateLimiterInterface*) const @ 0x1275f1ad in /usr/bin/clickhouse
5. DB::S3::PocoHTTPClient::MakeRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const @
 0x1275d05c in /usr/bin/clickhouse
6. Aws::Client::AWSClient::AttemptOneRequest(std::shared_ptr<Aws::Http::HttpRequest> const&, Aws::AmazonWebServiceRequest const&, char const*, char const*, char const*) const @ 0x17aff009
in /usr/bin/clickhouse
7. Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @ 0x17afc172
in /usr/bin/clickhouse
8. Aws::Client::AWSClient::MakeRequestWithUnparsedResponse(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @
 0x17b03b05 in /usr/bin/clickhouse
9. Aws::S3::S3Client::GetObject(Aws::S3::Model::GetObjectRequest const&) const @ 0x17c104d9 in /usr/bin/clickhouse
10. DB::S3::Client::GetObject(DB::S3::ExtendedRequest<Aws::S3::Model::GetObjectRequest> const&) const @ 0x1274351f in /usr/bin/clickhouse
11. DB::ReadBufferFromS3::initialize() @ 0x1277a9b5 in /usr/bin/clickhouse
12. DB::ReadBufferFromS3::nextImpl() @ 0x127784f1 in /usr/bin/clickhouse
13. DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x12c41731 in /usr/bin/clickhouse
14. DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x12c41370 in /usr/bin/clickhouse
15. DB::AsynchronousReadIndirectBufferFromRemoteFS::nextImpl() @ 0x12c43f26 in /usr/bin/clickhouse
16. DB::MergeTreeDataPartWide::loadIndexGranularityImpl(DB::MergeTreeIndexGranularity&, DB::MergeTreeIndexGranularityInfo&, DB::IDataPartStorage const&, String const&) @ 0x145b3f41 in /usr
/bin/clickhouse
17. DB::MergeTreeDataPartWide::loadIndexGranularity() @ 0x145b4919 in /usr/bin/clickhouse
18. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x1448429e in /usr/bin/clickhouse
19. DB::MergeTreeData::loadDataPart(DB::MergeTreePartInfo const&, String const&, std::shared_ptr<DB::IDisk> const&, DB::MergeTreeDataPartState, std::mutex&) @ 0x145023d5 in /usr/bin/clickh
ouse
20. ? @ 0x1458fb64 in /usr/bin/clickhouse
21. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe2af6c5 in /usr/bin/clickhouse
22. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadF
romGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_stora
ge const*) @ 0xe2b2235 in /usr/bin/clickhouse
23. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe2ab493 in /usr/bin/clickhouse
24. ? @ 0xe2b1101 in /usr/bin/clickhouse
25. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
26. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.3.5.9 (official build))

config:

 <disk_oss_click_device>
            <type>s3</type>
            <endpoint>http://taqu-online-clickhouse.oss-cn-zhangjiakou-internal.aliyuncs.com/ck/click_device/</endpoint>
            <access_key_id>******</access_key_id>
            <secret_access_key>*******</secret_access_key>
        </disk_oss_click_device>

 <volume_name_oss_11>
                    <disk>disk_oss_click_device</disk>
                    <max_data_part_size_bytes>1007374182400</max_data_part_size_bytes>
                </volume_name_oss_11>

**Comment by alexey-milovidov** [comment]
ClickHouse correctly shows the error message about the timeout.
You can check your configuration options, check if the server can connect to OSS in other ways, or write to the support of OSS.
