### ISSUE TITLE
Monitoring Clickhouse with grafana

### ISSUE THREAD

**Issue by vinith-reddy25** [ClickHouse/ClickHouse#53541]
Need to monitor clickhouse in grafana using prometheus. We enabled prometheus in config file. Can I get json files or prometheus queries of these dashboards("ClickHouse Overview dashboard",    "ClickHouse Latency dashboard",   "ClickHouse Replica dashboard",    "ClickHouse alerts") in https://grafana.com/blog/2023/05/30/how-to-start-monitoring-your-clickhouse-instance-or-cluster-with-grafana-cloud/

**Comment by qoega** [comment]
If I understand correctly sources of this dashbords are here 
https://github.com/grafana/jsonnet-libs/tree/f3c7be86c7156678ac30369e85eb4face285b14c/clickhouse-mixin/dashboards

**Comment by mshustov** [comment]
Note that [ClickHouse datasource](https://github.com/grafana/clickhouse-datasource#importing-dashboards-for-clickhouse) also comes with built-in monitoring capabilities based on `system` tables.

**Comment by vinith-reddy25** [comment]
Want to use prometheus

> Note that [ClickHouse datasource](https://github.com/grafana/clickhouse-datasource#importing-dashboards-for-clickhouse) also comes with built-in monitoring capabilities based on `system` tables.

Want to use prometheus
