### ISSUE TITLE
replicas parallel query bug

### ISSUE THREAD

**Issue by LuPan92** [ClickHouse/ClickHouse#53540]
clickhouse version: 23.3.8
sql: select count(1) from bsad_traffic_local where toString(sip) = '10.0'
bug desc:
   When SET allow_experimental_parallel_reading_from_replicas = 0, there is no problem with the query. 
    But set allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 2;  query exception. `Received exception from server (version 23.3.8):
Code: 10. DB::Exception: Received from localhost:9001. DB::Exception: Not found column count() in block. There are only columns: . (NOT_FOUND_COLUMN_IN_BLOCK)`

details as follows:
```
[worker@test bin]$ ./clickhouse-client --port 9001 --password 
ClickHouse client version 23.3.8.21 (official build).
Connecting to localhost:9001 as user default.
Connected to ClickHouse server version 23.3.8 revision 54462.

Warnings:
 * Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled

production :) set allow_experimental_parallel_reading_from_replicas = 0;

0 rows in set. Elapsed: 0.001 sec. 

production :) select count(1) from bsad_traffic_local where toString(sip) = '10.0';

┌─count()─┐
│       0 │
└─────────┘

1 row in set. Elapsed: 60.944 sec. Processed 2.28 billion rows, 36.54 GB (37.48 million rows/s., 599.64 MB/s.)

production :) set allow_experimental_parallel_reading_from_replicas = 1, max_parallel_replicas = 2;

production :) select count(1) from bsad_traffic_local where toString(sip) = '10.0';

Received exception from server (version 23.3.8):
Code: 10. DB::Exception: Received from localhost:9001. DB::Exception: Not found column count() in block. There are only columns: . (NOT_FOUND_COLUMN_IN_BLOCK)
```
![image](https://github.com/ClickHouse/ClickHouse/assets/118737616/2ad6bafe-f8f0-4ec2-a152-6ec231bca986)

**Comment by alexey-milovidov** [comment]
Parallel replicas are in development, and it does not make sense to use any versions older than the current master to test it.
