### ISSUE TITLE
Perf test `explain_ast`: Slow on Client

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#53551]
https://s3.amazonaws.com/clickhouse-test-reports/53505/adc73beb933c8c5965eaaf6520b322053b172a79/performance_comparison_[2_4]/report.html#slow-on-client

cc: @Algunenano, @evillique

**Comment by Algunenano** [comment]
Need to check if the test has gotten slower recently or it needs to be simplified. I'm not sure what "slow on client" means yet.

**Comment by tavplubix** [comment]
AFAIR, we measure query execution time on client and on server. The time on client is always longer (because the client does something extra besides waiting for the server) but it should not be much longer

**Comment by Algunenano** [comment]
I've checked and the test doesn't seem to have gotten slower: similar perf for master, 23.6 and 23.3 and 1.5 as fast as 22.8.

Focusing on the error itself:
* Client time: 2.0994654
* Server time: 2.0559616

A client error is determined by:
```
create table slow_on_client_report engine File(TSV, 'report/slow-on-client.tsv')
    as select client, server, round(client/server, 3) p,
        test, query_display_name
    from total_client_time_per_query left join query_display_names using (test, query_index)
    where p > round(1.02, 3) order by p desc;
```

The ratio of those values in this run is 1.021, which is bigger than the 1.02 threshold. In local I get similar values around 1.02 too. In this case it is a large query (200 KB) where we only check parsing time (EXPLAIN AST) which might explain the divergence.


The curious thing is that I have no idea what the client vs server times are meant to be measuring:
* Looking at the code, the server time is measured using `c.last_query.elapsed` which is calculated inside the clickhouse-driver (`Client.execute()`) and doesn't look into any values returned by the server. It's just a timer around the request.
* Client seconds on the other hand is also another wrapper around the calls, but in this case it's outside the loop. 

If the server time was based on timings reported by the server (query_log or headers) then it'd make sense to differentiate between server and client time, but AFAICT the current implementation is just measuring the overhead of the loop (some variable setups, additions and prints). Based on this I fail to see what interest it has having both at all, as it's not giving us any information.

Should we just remove this check?
