### ISSUE TITLE
`|` (pipe) character not escaped for Markdown format

### ISSUE THREAD

**Issue by poundifdef** [ClickHouse/ClickHouse#53555]
When fetching data using `FORMAT Markdown`, the `|` character in a row should be escaped. Today it is not escaped which results in a malformed table.

**How to reproduce**

ClickHouse server version 23.8.1.276

To reproduce, run the following query:

``` sql
select 'a' as a, '|' as b, 'c' as c FORMAT Markdown;
```

This is the output:

```
| a | b | c |
|:-|:-|:-|
| a | | | c |
```

Which is formatted like this: 

| a | b | c |
|:-|:-|:-|
| a | | | c |

**Expected behavior**

The expected output would be for the `|` character in column `b` to be escaped. Either of these would be acceptable:

Escape using `\|`: 

```
| a | b | c |
|:-|:-|:-|
| a | \| | c |
```

| a | b | c |
|:-|:-|:-|
| a | \| | c |

Escape using `&#124;`

```
| a | b | c |
|:-|:-|:-|
| a | &#124; | c |
```
 
| a | b | c |
|:-|:-|:-|
| a | &#124; | c |

Perhaps there could be a format option, or something akin go MarkdownRaw, to avoid breaking any existing code that depends on this.

**Comment by alexey-milovidov** [comment]
Ok. I remember we considered it but decided to do no escaping for simplicity and to allow custom user-defined formatting, such as bold inside table cells.

Now it's time to introduce a setting to enable/disable escaping.

Reference: https://www.markdownguide.org/basic-syntax/#characters-you-can-escape

Note: I've counted 18 characters to escape.

**Comment by alexey-milovidov** [comment]
To implement it, we will need to add a method `serializeTextMarkdown` in `ISerialization`, similarly to `serializeTextXML`, and add a setting `output_format_markdown_escape_special_characters`.

**Comment by irenjj** [comment]
Can I take this? :)

**Comment by alexey-milovidov** [comment]
Yes, it will be very appreciated!
