### ISSUE TITLE
If a cluster is formed by cluster discovery, be aware of unavailable hosts without connecting to them.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#53596]
The cluster discovery mechanism can be used by one of the following features:
- experimental cluster discovery, see https://github.com/ClickHouse/ClickHouse/issues/47176
- experimental Replicated database engine.

A host registers itself in Keeper and holds an ephemeral node, and its status is visible in the `system.clusters` table.
Example:

```
clickhouse-cloud :) SELECT host_name, is_active FROM system.clusters WHERE cluster = 'default'

SELECT
    host_name,
    is_active
FROM system.clusters
WHERE cluster = 'default'

Query id: 489d908c-7b4c-446f-853d-c4818aa11a15

┌─host_name──────────────────────────────────────────────────────────────────────────────────┬─is_active─┐
│ c-coal-gt-61-server-61o23c0-0.c-coal-gt-61-server-headless.ns-coal-gt-61.svc.cluster.local │         1 │
│ c-coal-gt-61-server-7rlgagw-0.c-coal-gt-61-server-headless.ns-coal-gt-61.svc.cluster.local │         0 │
│ c-coal-gt-61-server-x2ebetp-0.c-coal-gt-61-server-headless.ns-coal-gt-61.svc.cluster.local │         0 │
└────────────────────────────────────────────────────────────────────────────────────────────┴───────────┘
```

Here one host is active, and two others are not.

We should not even try to connect to inactive hosts to save time.

**Comment by tavplubix** [comment]
> We should not even try to connect to inactive hosts to save time.

AFAIR, we make a request to ZooKeeper to check what hosts are active. So I doubt it will save time.

**Comment by alexey-milovidov** [comment]
Thank you! When I filed this issue, I thought it is done in the background.
