### ISSUE TITLE
A function `decodeHTMLComponent`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#53598]
**Use case**

You get the content of text nodes from HTML, for example, with my favorite `extractTextFromHTML` function, but you want to convert HTML entities to Unicode characters.

**Describe the solution you'd like**

The function is similar to `decodeXMLComponent`, but HTML has much more named entities compared to XML:

```
SELECT decodeHTMLComponent('C&lscr;&iscr;&cscr;&kscr;&#x1d43b;&#x1d45c;&uscr;&sscr;&#x1d452;')
     = 'C𝓁𝒾𝒸𝓀𝐻𝑜𝓊𝓈𝑒'
```

https://html.spec.whatwg.org/multipage/named-characters.html

You might want to use a perfect hash table for it.
You can generate it with `gperf` and commit the result to the repository.

**Comment by bharatnc** [comment]
Can I take this?

**Comment by alexey-milovidov** [comment]
Yes, that will be wonderful!
