### ISSUE TITLE
Using the SummingMergeTree engine, a negative number appeared in the aggregate field when a large number of high concurrency insertions were performed

### ISSUE THREAD

**Issue by wdongji** [ClickHouse/ClickHouse#53609]
ddl:
`  create table sum_test
  (
	  tenant_id String,
	  dim_project_sk String,
	  dim_month_sk String,
	  labour_num Int8 ,
	  mugong Int8
  )
  ENGINE = SummingMergeTree
  order by (tenant_id,dim_project_sk,dim_month_sk);`

Execute the following sql at high concurrency：
`INSERT into sum_test VALUES('564785','1','2023-03',1,1),('564785','1','2023-03',1,1),('564785','1','2023-03',1,1),('564785','1','2023-03',1,1);`
results are as follows：
![image](https://github.com/ClickHouse/ClickHouse/assets/46468936/51da042b-979b-497b-855a-8b92379b94ef)

clickhouse versions are as follows：
![image](https://github.com/ClickHouse/ClickHouse/assets/46468936/f4390b5e-2b65-4fb2-8518-5d8cbb0fcfb2)

The expected result should not be negative！！！

**Comment by den-crane** [comment]
You should use Int64 instead of Int8.

It's the overflow problem 

```
select cast(133, 'Int8');
┌─CAST(133, 'Int8')─┐
│              -123 │
└───────────────────┘
```

https://en.wikipedia.org/wiki/Integer_overflow
