### ISSUE TITLE
Perf test `encrypt_decrypt_empty_string_slow` is too slow

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#53634]
https://s3.amazonaws.com/clickhouse-test-reports/0/dd1a00b97646c0b0103bf2f0d46c430f03ba91bc/performance_comparison_aarch64_[2_4]/report.html#test-times.encrypt_decrypt_empty_string_slow

@Enmk please take a look

**Comment by alexey-milovidov** [comment]
Remove it.
