### ISSUE TITLE
Adding materialized column on new array columns fails

### ISSUE THREAD

**Issue by dbanda** [ClickHouse/ClickHouse#53652]
Adding materialized column on empty Array columns causes task replication to backlog with errored tasks. We observed this on Clickhouse 21.8 and now our production systems stuck.

Reproducing locally:

```[sql]
-- create a table and add some data

create table test_t (a UInt8) engine = MergeTree order by a
insert into test_t (a) values (1)

-- add new columns
alter table test_t add column b Array(String)
alter table test_t add column c Array(String)

-- add materilized column
alter table test_t add column d String Materialized arrayMap((k,v) -> concat(k,v), b, c)

-- query column fails
select d from test_t

``
Received exception from server (version 21.6.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'c' 'b' while processing query: 'CAST(arrayMap((k, v) -> concat(k, v), b, c), 'String') AS d', required columns: 'b' 'c' 'b' 'c': (while reading from part /var/lib/clickhouse/store/d4d/d4dfc8d1-c1ef-42ae-b7b4-ff88ea09b111/all_2_2_0/): While executing MergeTreeThread. 
``

```

On our distributed setups we would see a backlog of replication task failure in `system.replication_queue` with similar errors.

The issue is resolved after doing `optimize table test_t final`. 

Edit: Issues can be mitigated by doing `concat(toString(k), toString(v))` as well

> A link to reproducer

https://fiddle.clickhouse.com/1dda88f3-aedb-4afc-a05b-29509eda7674

> **Does it reproduce on recent release?**

Doesn't reproduce in Clickhouse 22

**Comment by den-crane** [comment]
21.6 is obsolete after July 2022.

upgrade at least to 23.3.

**Comment by den-crane** [comment]
you can do

```
alter  table test_t update b=b, c=c where 1 settings mutations_sync=2;
```

https://fiddle.clickhouse.com/1a01ac6b-de71-429f-b786-1c5d76755aa3

**Comment by dbanda** [comment]
Interesting. thanks 🙏
