### ISSUE TITLE
windowFunnel with group by function

### ISSUE THREAD

**Issue by Chr1sxu** [ClickHouse/ClickHouse#5365]
id like to use windowFunnel to create funnels grouped by dimensions. how could I accomplish it? 
for instance
below is the sql that Id like to group by exp_version from step1, can anyone help me modify it?  
```sql
SELECT 
    sumIf(count, level >= 1) AS sum1, 
    sumIf(count, level >= 2) AS sum2
FROM 
(
    SELECT 
        level, 
        count() AS count
    FROM 
    (
        SELECT 
            uuid, 
            windowFunnel(86400)(timestamp, (operation = 'hawkeye') AND (biz = 'cf') AND (type = 'user_action') AND ((exp_id = '207') AND (exp_version = '8')), (element_code = 'f09aa09b1d34425dac317adbbf40f663') AND (biz = 'cf') AND (type = 'user_action')) AS level
        FROM all_log_record_5_cluster 
        WHERE (date = '2019-05-20') AND (biz = 'cf') AND (type = 'user_action')
        GROUP BY uuid
    ) 
    GROUP BY level
) 
ORDER BY 
    sum1 DESC, 
    sum2 DESC

```

**Comment by Chr1sxu** [comment]
I tried to modify like this, but it looks wrong for step 2

select exp_version,
sumIf(count, level >= 1) as sum1,
       sumIf(count, level >= 2) as sum2
from (select level,exp_version, 
count() AS count
      from (select uuid,exp_version,
                   windowFunnel(86400)(timestamp,
                                operation = 'hawkeye' AND biz = 'cf' AND type = 'user_action' AND
                                (exp_id = '207'),
                                
                                (element_code = 'f09aa09b1d34425dac317adbbf40f663') AND biz = 'cf' AND
                                type = 'user_action'
                   ) as level
            from all_log_record_5_cluster
            where date='2019-05-20'
              and (biz = 'cf')
              and type = 'user_action'

            group by uuid,exp_version)
      group by level,exp_version
      )
      group by exp_version
order by sum1 DESC, sum2 DESC

**Comment by Chr1sxu** [comment]
I tried to modify like this, but it looks windowFunnel doesn't support to group by one dimension only based on the first step.

"""
select exp_version,
sumIf(count, level >= 1) as sum1,
       sumIf(count, level >= 2) as sum2
from (select level,exp_version, 
count() AS count
      from (select uuid,exp_version,
                   windowFunnel(86400)(toUInt32(substring(compare_timestamp, 1, 10)),
                                operation = 'hawkeye' AND biz = 'cf' AND type = 'user_action' AND
                                (exp_id = '207'),
                                
                                (element_code = 'f09aa09b1d34425dac317adbbf40f663') AND biz = 'cf' AND
                                type = 'user_action'
                   ) as level
            from all_log_record_5_cluster
            where date='2019-05-20'
              and (biz = 'cf')
              and type = 'user_action'

            group by uuid,exp_version)
      group by level,exp_version
      )
      group by exp_version
order by sum1 DESC, sum2 DESC
"""

**Comment by blinkov** [comment]
@Chr1sxu, do you have any further questions?

**Comment by alexey-milovidov** [comment]
CC @ucasFL

**Comment by ucasFL** [comment]
> I tried to modify like this, but it looks windowFunnel doesn't support to group by one dimension only based on the first step.
> 
> ```sql
> SELECT 
>     exp_version, 
>     sumIf(count, level >= 1) AS sum1, 
>     sumIf(count, level >= 2) AS sum2
> FROM 
> (
>     SELECT 
>         level, 
>         exp_version, 
>         count() AS count
>     FROM 
>     (
>         SELECT 
>             uuid, 
>             exp_version, 
>             windowFunnel(86400)(toUInt32(substring(compare_timestamp, 1, 10)), (operation = 'hawkeye') AND (biz = 'cf') AND (type = 'user_action') AND (exp_id = '207'), (element_code = 'f09aa09b1d34425dac317adbbf40f663') AND (biz = 'cf') AND (type = 'user_action')) AS level
>         FROM all_log_record_5_cluster 
>         WHERE (date = '2019-05-20') AND (biz = 'cf') AND (type = 'user_action')
>         GROUP BY 
>             uuid, 
>             exp_version
>     ) 
>     GROUP BY 
>         level, 
>         exp_version
> ) 
> GROUP BY exp_version
> ORDER BY 
>     sum1 DESC, 
>     sum2 DESC
> ```

I cann't find where is wrong about this sql, can you post the error message?

**Comment by melvynator** [comment]
No response from the author. I'm closing
