### ISSUE TITLE
How to use cache disk over a local disk?

### ISSUE THREAD

**Issue by ray-at-github** [ClickHouse/ClickHouse#53670]
Clickhouse v23.7.4.5

Tried to attach a cache layer on top of a local disk, got this error:
```
<Error> Application: DB::Exception: Cannot wrap disk `data` with cache layer `cache`: cached disk is allowed only on top of object storage
```

The storage config is as below:
```
<storage_configuration>
    <disks>
        <data>
            <type>local</type>
            <path>/home/clickhouse_disk/</path>
        </data>
        <cache>
            <type>cache</type>
            <disk>data</disk>
            <path>/mnt/clickhouse_cache/</path>
            <max_size>8192Gi</max_size>
        </cache>
    </disks>
</storage_configuration>
```

According to the documentation (https://clickhouse.com/docs/en/operations/storing-data#using-local-cache), cache is supported on any disk types including "local".
```
For versions >= 22.8 cache is supported for any disk type: S3, Azure, Local, Encrypted, etc.
```

The aim is to use a fast SSD disk cache on top of a slower local disk. How do I make it work?

**Comment by UnamedRus** [comment]
It was removed here https://github.com/ClickHouse/ClickHouse/pull/48791#discussion_r1183515845
