### ISSUE TITLE
clickhouse replication user authentication is not supporting sha256 hashing

### ISSUE THREAD

**Issue by venkip541** [ClickHouse/ClickHouse#53676]
Hi Team,

I am trying to establish a clickhouse cluster with 2 shard and 2 replication, when i have configured my replication with plane password i can able to establish successful connection, the same when i have used sha256 hashing, i am getting password mismatch issues. Need your assistance in fixing the same.

Regards
Venkatesh. P

**Comment by den-crane** [comment]
Provide your config.
Do you mean  interserver_http_credentials ?

https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server-settings-interserver-http-credentials

**Comment by den-crane** [comment]
no info
