### ISSUE TITLE
Support for glob (wildcards) in File and HDFS storages and table functions.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5371]
Current behaviour: `File` and `HDFS` storages expect exact file path.
Proposed behaviour: support for globs in file paths, at least:

`*`
`?`
`{abc,def}` - this is similar to `remote` table function
`{N..M}` - this is similar to `remote` table function

Multiple path components can have globs.

For implementation, directory listing is used.
If the generator or matching expression yields non-existent file, the file is skipped.

The storage will return multiple files as multiple independent streams to support parallel query processing.

**Comment by sundy-li** [comment]
- Single shard to aggregate large data may be the bottleneck, will it have a new Engine like `DistributeHDFS` storage? It will distribute the files to each shard by some scheduling algorithms.

- Index pushed to filter the files, usually we split the HDFS by date, `table_name/dt=YYYYMMDD`.  So the query `select xxx from table_name where dt between 20180701 and 20180801` will only query the matched files to reduce IO cost.

**Comment by zhang2014** [comment]
I have discussed such issues with @sundy-li before, and I'm not sure if this will help this issues. I will describe the process of discussion below : ) 

- First we can support some virtual columns for the HDFS Engine, such as :
``` SQL
CREATE TABLE hdfs(...)ENGINE = HDFS('hdfs://hdfs1:9000/path/dt=YYYYMMDD', 'TSV')
-- Now the hdfs table will have the virtual column dt
```

- Next, virtual column clauses are supported in distributed tables, such as :
``` SQL
CREATE TABLE hdfs_distributed(...)ENGINE = Distributed(cluster_name, default, hdfs, dt) VIRTUAL COLUMNS (dt);
-- Now query distributed tables can be parallel query HDFS Engine.
```

However, there are some problems with this scenario, such as virtual columns that are not writable in ClickHouse. I don't know how to solve the write problem.

**Comment by alex-krash** [comment]
**Syntax-related thoughts**
In terms of data manipulation, sub-directories are partitions.
From my point of view, such tables should have DDL, similar to one created in Hive:

```
CREATE TABLE hdfs_table
(
   id UInt32,
   dt Date,
   country_id UInt32
) ENGINE = HDFS('hdfs://hdfs1:9000/path/')
PARTITION BY (dt, country_id);
```
**Operations related thoughts**
Does not matter, which DDL we choose, It is unclear for me, what happens if we are inserting the data into more than one partition. In order to do it looking so-so "atomic", we need to write a separate file in a temporary HDFS directory, and in the end of insertion process - perform renaming into corresponding destination partitions. But it looks really weird and complicated.

**Comment by alexey-milovidov** [comment]
This is much more simple task than you expect.
Consider if we only have File storage and want to read multiple files.

In this task we will add support for wildcards.
If the path contains wildcards, the table will be readonly.
We can add virtual columns `_path` and `_filename` to filter files in query.

Everything else should be considered as subsequent extensions.
(Example: named substitutions in path that will contain PARTITION BY columns)

**Comment by JackyYangPassion** [comment]
> * Single shard to aggregate large data may be the bottleneck, will it have a new Engine like `DistributeHDFS` storage? It will distribute the files to each shard by some scheduling algorithms.
> * Index pushed to filter the files, usually we split the HDFS file by date, `hdfs://path/table_name/dt=YYYYMMDD`.  So the query `select xxx from table_name where dt between 20180701 and 20180801` will only query the matched files to reduce IO cost.

I think ’DistributeHDFS‘  Engine is necessary;But  this feature like SQL ON Hadoop ,such as 'Presto','Impala' e.g; can this feature  faster than MPP Presto with Clickhouse vector engine and  code generation ?

**Comment by alexey-milovidov** [comment]
Current status:
- wildcards have been implemented;
- there are some weirdness in numeric ranges like `{12..123}` and `{012..123}` (@stavrolia, please clarify);
- virtual columns `_file` and `_path` are not implemented.

**Comment by stavrolia** [comment]
Current status:

    support for wildcards have been implemented;
    numeric ranges work without leading zeros like {12..123} ({012..123} doesn't work at the moment);
    virtual columns _file and _path are implemented in #8489.

**Comment by alexey-milovidov** [comment]
Thank you!

The only remaining part is to implement full support for numeric ranges.

**Comment by stavrolia** [comment]
Full support for ranges done here #9989

**Comment by yehiaelbehery** [comment]
> * Single shard to aggregate large data may be the bottleneck, will it have a new Engine like `DistributeHDFS` storage? It will distribute the files to each shard by some scheduling algorithms.
> * Index pushed to filter the files, usually we split the HDFS file by date, `hdfs://path/table_name/dt=YYYYMMDD`.  So the query `select xxx from table_name where dt between 20180701 and 20180801` will only query the matched files to reduce IO cost.

Hello guys,

I'm using this feature and it's awesome but the virtual column is enriched to every row and merely used for row filtering not "partitioning" as mentioned above, correct?
And if so is there any way I can partition or simulate partitioning hdfs tables (other than creating a new table with the specified partition that is)?

**Comment by sundy-li** [comment]
@yehiaelbehery 
I have partition support for `storage hdfs engine` in my private code.
If you need it, I can speed some time to cherry pick a pr.

**Comment by yehiaelbehery** [comment]
@sundy-li It would be awesome if you can do it. Thanks.
