### ISSUE TITLE
How can I LIMIT high IO on select query?

### ISSUE THREAD

**Issue by MattMH** [ClickHouse/ClickHouse#53712]
I know that clickhouse will use all the performance of the server as much as possible to speed up query processes.
But I still want to know how to constrain the IO consumption of a select query that we can tolerate slow query.

I tried to use **max_threads** to reduce the IO, but it doesn't seem to work

SETTINGS max_threads=1,  select query took 20s  ,  iostat show that IO utils up to 90%
SETTINGS max_threads=2,  select query took 11s  ,  iostat show that IO utils up to 97%
SETTINGS max_threads=8 or 16,  select query took 3s  ,  iostat show that IO utils up to 99% -100%

I want to know if there is a way to constrain the IO consumption of a query and let it return the results slowly and taking up about 30% of the IO?

**Comment by UnamedRus** [comment]
`os_thread_priority` setting

Or https://github.com/ClickHouse/ClickHouse/pull/41840 (not done yet)

**Comment by nikitamikhaylov** [comment]
Please check the presentation from the meetup: https://github.com/ClickHouse/clickhouse-presentations/blob/master/meetup85/Workload%20Scheduling.pdf
