### ISSUE TITLE
Double (()) in dictGet from dictionary with LAYOUT(complex_key_direct())

### ISSUE THREAD

**Issue by ikeniborn** [ClickHouse/ClickHouse#53737]
> You have to provide the following information whenever possible.

I create dictionary

CREATE DICTIONARY dictionary.dict_category on cluster '{cluster}'
(
    `category_id` String,
    `category_name_en` String,
    `category_name_ru` String
)
PRIMARY KEY category_id
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 PASSWORD '******' QUERY 'SELECT \n    category_id as category_id,
 \n    category_name_en as category_name_en,
 \n    category_name_ru as category_name_ru\nFROM\n  snapshot.snap_dim_category \norder by \n  updated_dttm desc\nlimit 1 by category_id'))
LAYOUT(complex_key_direct());

After try get attiribute with select dictGet('dictionary.dict_category','category_name_en','05e7d19a-6d00-2118-deef-70d21ff4226e')

i get error 
SQL Error [62] [07000]: Code: 62. DB::Exception: Syntax error: failed at position 216 ('WHERE') (line 11, col 24): WHERE (`category_id`) IN (('05e7d19a-6d00-2118-deef-70d21ff4226e'));. Expected one of: token, Dot, OR, AND, IS NULL, IS NOT NULL, BETWEEN, NOT BETWEEN, LIKE, ILIKE, NOT LIKE, NOT ILIKE, REGEXP, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, MOD, DIV, alias, AS, Comma, FETCH, LIMIT, SETTINGS, UNION, EXCEPT, INTERSECT, INTO OUTFILE, FORMAT, end of query: While processing dictGet('dictionary.dict_category', 'category_name_en', '05e7d19a-6d00-2118-deef-70d21ff4226e'). (SYNTAX_ERROR) (version 23.7.4.5 (official build))

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
Probably in case of `QUERY` and/or `INVALIDATE_QUERY`/ `UPDATE_FIELD` / `WHERE` a sub-query can be used.

```sq;
select * from
(
    select * from
       (select * 
         from ($QUERY)
       )
    where $WHERE
) 
where $DIRECT_WHERE
```
![image](https://github.com/ClickHouse/ClickHouse/assets/19737682/c8c8b719-6606-417c-8bfd-9a560584b41c)

**Comment by den-crane** [comment]
Though subquery also a workaround https://fiddle.clickhouse.com/918a75e0-bbe4-4d62-9272-e3a4c2248e7f

```sql
create table t(A String, B String)
Engine=Memory as select 'a', 'b';

CREATE DICTIONARY d(A String, B String) PRIMARY KEY A
SOURCE(CLICKHOUSE(QUERY $$
       select * from (SELECT A, B FROM t order by A limit 1 by A)
$$))
LAYOUT(complex_key_direct());

select dictGet('d','B','a');
┌─dictGet('d', 'B', 'a')─┐
│ b                      │
└────────────────────────┘
```

**Comment by ikeniborn** [comment]
Work!!! Thank's

**Comment by UnamedRus** [comment]
{condition} placeholder exist
```
SOURCE(CLICKHOUSE(QUERY $$SELECT A, B FROM t WHERE {condition} order by A limit 1 by A$$))
```

https://fiddle.clickhouse.com/a9c25068-d648-41cc-8f00-8b5fbc8b9f08
