### ISSUE TITLE
The newly inserted data from the client is not being persisted

### ISSUE THREAD

**Issue by KyoUK4n** [ClickHouse/ClickHouse#53731]
* clickhouse-server:  v23.7.4.5 (offical build)
* zookeeper: 3.6.1

Hardware conditions:
* Shard: 2
* Replica: 2
* CPU: 4
* Memory: 16Gb

I'm conducting benchmarking on clickhouse cluster.
While continuously inserting data into 4000+ replicated tables (without TTL) for a few minutes, I observed that the insertion rate remained relatively stable.
However, when I checked the `system.tables`, I noticed that no new rows had been added. And there were no obvious exceptions thrown. This is quite unusual. 

**insertion rate**
![image](https://github.com/ClickHouse/ClickHouse/assets/18624741/8928cc6f-0bcc-4ca7-a531-ba08648b7b51)

Initially, I suspected that the slow merge process was leading to a gradual data growth, but when I halted the insertion, I observed that no new data was being added.

What might be happening?

**Comment by UnamedRus** [comment]
Did you check that?

https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

**Comment by cangyin** [comment]
> no new data was being added

check if tables are in readonly mode.

```sql
SELECT hostname() AS host,database,table,is_session_expired,is_readonly,future_parts,zookeeper_exception,last_queue_update_exception FROM clusterAllReplicas('{cluster}',system.replicas) WHERE is_readonly ORDER BY host
```
also check that your replica path (in zookeeper) is right.

**Comment by den-crane** [comment]
>Shard: 2

Do you insert into a distributed table?

```
select * from system.distribution_queue
```

**Comment by KyoUK4n** [comment]
Thank you for all the replies. I have found the reason. Indeed, it is caused by `Insert Deduplication`. I had set the `LoggerLevel` to `error`, which prevented me from seeing the log message 'Block with ID xxx already exists on other replicas as part...'.

**Comment by KyoUK4n** [comment]
> Did you check that?
> 
> https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

Yes, that's the reason. My log level is set to `error`, so I couldn't see the logs.
