### ISSUE TITLE
USearch HNSW index: code: 1001 Magic header mismatch - the file isn't an index

### ISSUE THREAD

**Issue by skeptrunedev** [ClickHouse/ClickHouse#53767]
**Describe what's wrong**

I attempted to make a table with the `usearch` index and query it via the `cosineDistance` function. This is as specified in the [docs on earch indexes](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/annindexes#usearch) which were merged in https://github.com/ClickHouse/ClickHouse/pull/53447 a couple days ago. 

Querying the index only resulted in `std::exception. Code: 1001, type: std::runtime_error, e.what() = Magic header mismatch - the file isn't an index (version 23.8.1.2501 (official build))` rather than resulting rows.

I am working on this as a part of an effort to switch off of Qdrant for [arguflow.ai](https://arguflow.ai)

The easiest way to reproduce this is to use the [jupyter notebook on this by arguflow.ai](https://github.com/arguflow/clickhouse-vs-qdrant-comparison/blob/ey/attempt-to-use-usearch/qdrant-to-ch.ipynb?short_path=38dc2e3#L313) - the README and first cell of the notebook contain steps to repro.

**Does it reproduce on recent release?**

Yes, `23.8.1.2501`

I enabled crash reporting, so hopefully a Sentry report went through when this failed.

**How to reproduce**

1. Use `23.8.1.2501`
2. Make a table with a `usearch` index like `INDEX usearch_embedding_vector embedding_vector TYPE usearch('cosineDistance') GRANULARITY 100`
3. Attempt to query the table with `cosineDistance` like `SELECT point_id, cosineDistance(embedding_vector, {first_vector}) AS score FROM qdrant_benchmark_10 ORDER BY score ASC  LIMIT 10`
4. Sample data is in the [jupyter notebook on this by arguflow.ai](https://github.com/arguflow/clickhouse-vs-qdrant-comparison/blob/ey/attempt-to-use-usearch/qdrant-to-ch.ipynb)

**Expected behavior**

Rows should get returned

**Error message and/or stacktrace**

`std::exception. Code: 1001, type: std::runtime_error, e.what() = Magic header mismatch - the file isn't an index (version 23.8.1.2501 (official build))`

**Additional context**

I am hopeful that `usearch` is more accurate than `annoy` . I'd be happy to contribute if someone adds a rough outline on what it would take to fix this.  Fwiw, the same error occurs with L2distance as shown in [this notebook](https://github.com/arguflow/clickhouse-vs-qdrant-comparison/blob/ey/attempt-to-use-usearch-l2distance/qdrant-to-ch.ipynb?short_path=38dc2e3).

**Comment by ashvardanian** [comment]
Thank you for the bug report! @davvard, can you please investigate this?

**Comment by davvard** [comment]
@ashvardanian Of course

**Comment by rschu1ze** [comment]
My amateurish attempts to get the Jupyter notebook repro running using the embedded steps in section "Replicating our results" failed with exceptions being thrown from the core Python interpreter. I then tried to reproduce with the [original data](https://aclanthology.org/2020.argmining-1.1/) and after downloading it from mega.nz (which will probably make my employer trigger a background check on me for downloading shady warez), but the embeddings existed only in binary form which was unsuitable for import into ClickHouse.

Chances are that #53876 fixes the issue - it would be great if someone could double-check. Allow me to close the issue, kindly reopen if the problem persists.

**Comment by skeptrunedev** [comment]
> My amateurish attempts to get the Jupyter notebook repro running using the embedded steps in section "Replicating our results" failed with exceptions being thrown from the core Python interpreter. I then tried to reproduce with the [original data](https://aclanthology.org/2020.argmining-1.1/) and after downloading it from mega.nz (which will probably make my employer trigger a background check on me for downloading shady warez), but the embeddings existed only in binary form which was unsuitable for import into ClickHouse.
> 
> Chances are that #53876 fixes the issue - it would be great if someone could double-check. Allow me to close the issue, kindly reopen if the problem persists.

I am double checking it currently. Have to run it natively on the branch which will take me a bit. Hopefully I will be done in the next few hours.
