### ISSUE TITLE
Maps Filter and Merge

### ISSUE THREAD

**Issue by ThomasOrvain** [ClickHouse/ClickHouse#53778]
Hello,
I have a table that contains 2 map columns A and B. Is it possible to merge the 2 maps with the condition to only merge the map values that have matching keys based on map A keys. Here is an example:
| A | B |
| --- | --- |
| {1:["Daniel",99],2:["Francis",57]} | {1:"Teacher",2:"Doctor",3:"Driver",4:"Nurse"} |

As a result, I want to  obtain map C which is map A enriched with map B values for only the matching keys based on map A keys. With the same example, this would result in map C containing map A values with the jobs "Teacher" and "Doctor" that are matching keys 1 and 2 :
| A | B | C |
| --- | --- | -- |
| {1:["Daniel",99],2:["Francis",57]} | {1:"Teacher",2:"Doctor",3:"Driver",4:"Nurse"} | {1:["Daniel",99,"Teacher"],2:["Francis",57,"Doctor"]} | 

Is there any way to perform this transformation with map functions ? Many thanks !

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions#mapapply

```sql
select 
 map (1,('Daniel',99), 2, ('Francis',57)) A,
 map (1,'Teacher',2,'Doctor',3,'Driver',4,'Nurse') B,
 mapApply(k,v-> (k, (v.1, v.2, B[k]) ), A) x

┌─A──────────────────────────────────┬─B─────────────────────────────────────────────┬─x─────────────────────────────────────────────────────┐
│ {1:('Daniel',99),2:('Francis',57)} │ {1:'Teacher',2:'Doctor',3:'Driver',4:'Nurse'} │ {1:('Daniel',99,'Teacher'),2:('Francis',57,'Doctor')} │
└────────────────────────────────────┴───────────────────────────────────────────────┴───────────────────────────────────────────────────────┘
```

https://fiddle.clickhouse.com/261d1682-8ecc-4533-8c75-91d8a7d1bd81

**Comment by ThomasOrvain** [comment]
@den-crane thanks for your answer, here you treat the example by specifying the keys 1, 2. However, is it to possible to generalise the logic without specifying manually the keys of map A? Thxs !

**Comment by ThomasOrvain** [comment]
Many thanks @den-crane you rock ! That's all I needed !!
