### ISSUE TITLE
the precise of Decimal128 

### ISSUE THREAD

**Issue by qmdt** [ClickHouse/ClickHouse#53777]
version 23.3 

`create table test1 
(
id String DEFAULT 'NA',
value  Decimal128(4) DEFAULT -99999999999.9999,
dt String DEFAULT 'NE',
tim Datetime64 DEFAULT now()
)
ENGINE=MergeTree
PARTITION BY dt
order by (id);

insert into test1(id) values('abc');

select * from test1;

┌─id──┬─────────────value─┬─dt─┬─────────────────────tim─┐
│ abc │ -99999999999.9998 │ NE │ 2023-08-24 14:03:08.000 │
└─────┴───────────────────┴────┴─────────────────────────┘

`
the value should be -99999999999.9999, but it is not.

**Comment by UnamedRus** [comment]
```
CREATE TABLE test1
(
    `id` String DEFAULT 'NA',
    `value` Decimal128(4) DEFAULT '-99999999999.9999',
    `dt` String DEFAULT 'NE',
    `tim` Datetime64 DEFAULT now()
)
ENGINE = MergeTree
PARTITION BY dt
ORDER BY id


INSERT INTO test1 (id) FORMAT Values



Ok.

1 row in set. Elapsed: 0.004 sec.

SELECT *
FROM test1

┌─id──┬─────────────value─┬─dt─┬─────────────────────tim─┐
│ abc │ -99999999999.9999 │ NE │ 2023-08-24 13:36:46.000 │
└─────┴───────────────────┴────┴─────────────────────────┘
```

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-queries-and-syntax/literal-decimal-or-float/

https://github.com/ClickHouse/ClickHouse/issues/5690#issuecomment-1362765553

**Comment by den-crane** [comment]
```
desc (select -99999999999.9999 a);

┌─name─┬─type────┬
│ a    │ Float64 │
└──────┴─────────┴


desc (select -99999999999.9999::Decimal128(4) a);
─name─┬─type───────────┬─
 a    │ Decimal(38, 4) │
──────┴────────────────┴─
```

```

**Comment by qmdt** [comment]
> ```
> desc (select -99999999999.9999 a);
> 
> ┌─name─┬─type────┬
> │ a    │ Float64 │
> └──────┴─────────┴
> 
> 
> desc (select -99999999999.9999::Decimal128(4) a);
> ─name─┬─type───────────┬─
>  a    │ Decimal(38, 4) │
> ──────┴────────────────┴─
> ```

> https://kb.altinity.com/altinity-kb-queries-and-syntax/literal-decimal-or-float/
> 
> [#5690 (comment)](https://github.com/ClickHouse/ClickHouse/issues/5690#issuecomment-1362765553)

Thank you for your reply. It's clear now.

**Comment by qmdt** [comment]
> ```
> desc (select -99999999999.9999 a);
> 
> ┌─name─┬─type────┬
> │ a    │ Float64 │
> └──────┴─────────┴
> 
> 
> desc (select -99999999999.9999::Decimal128(4) a);
> ─name─┬─type───────────┬─
>  a    │ Decimal(38, 4) │
> ──────┴────────────────┴─
> ```

Thank you. Can you help to close this ?

**Comment by UnamedRus** [comment]
You should be able to close by yourself 
![image](https://github.com/ClickHouse/ClickHouse/assets/9449405/4e02e78c-2b2d-41d8-9432-adf197c64db6)

**Comment by qmdt** [comment]
> You should be able to close by yourself ![image](https://user-images.githubusercontent.com/9449405/264148620-4e02e78c-2b2d-41d8-9432-adf197c64db6.png)

Thank you ,Let me close it.
