### ISSUE TITLE
Wrong handling of group by when the field name is reused as an alias

### ISSUE THREAD

**Issue by EugeniyPetrov** [ClickHouse/ClickHouse#53793]
> You have to provide the following information whenever possible.

There is an inconsistent behavior when handling the following query:

```
SELECT coalesce(v) AS v
FROM (SELECT TRUE AS v) AS _
GROUP BY coalesce(v);
```

ClickHouse throws an error:

`Code: 215. DB::Exception: Received from localhost:9000. DB::Exception: Column `v` is not under aggregate function and not in GROUP BY. Have columns: ['coalesce(coalesce(v))']: While processing coalesce(v) AS v. (NOT_AN_AGGREGATE)`

An exception is thrown also through the mysql protocol.

The same query in Mysql and Postgres works fine.

At the same time if you change `GROUP BY coalesce(v)` to `GROUP BY coalesce(v) AS v` or `GROUP BY v` or `GROUP BY 1` it works properly.

If you use the `coalesce(v)` in the ORDER BY it also works fine.

```
ip-172-31-20-169.ec2.internal :) SELECT coalesce(v) AS v
FROM (SELECT TRUE AS v) AS _
ORDER BY coalesce(v);


SELECT coalesce(v) AS v
FROM
(
    SELECT true AS v
) AS _
ORDER BY coalesce(v) ASC

Query id: 4fa25121-28b8-4ace-8f73-263ec163db27

┌─v────┐
│ true │
└──────┘

1 row in set. Elapsed: 0.002 sec.
```

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

https://fiddle.clickhouse.com/1c2deb0b-0364-4774-a0e3-532b60ea6c81

* Which ClickHouse server version to use: 23.7.1.2470

> A clear and concise description of what you expected to happen.

The query should be compatible with the Mysql and Postgres. And through the Mysql protocol must be the same

**Comment by EugeniyPetrov** [comment]
One more example. Seems like clickhouse uses the evaluated expression in group by, and MySQL and Postgres gives priority to the table column value (however mysql shows the warning).

ClickHouse
```
ip-172-31-20-169.ec2.internal :) SELECT case when v = 1 then 2 else v end AS v
FROM (SELECT 1 AS v UNION ALL SELECT 2 AS v) AS _
GROUP BY v;

SELECT multiIf(v = 1, 2, v) AS v
FROM
(
    SELECT 1 AS v
    UNION ALL
    SELECT 2 AS v
) AS _
GROUP BY v

Query id: 8606c27e-e004-4d4c-a5b9-295d8fbaf58f

┌─v─┐
│ 2 │
└───┘

1 row in set. Elapsed: 0.004 sec.
```

MySQL
```
MariaDB [test]> SELECT case when v = 1 then 2 else v end AS v
    -> FROM (SELECT 1 AS v UNION ALL SELECT 2 AS v) AS _
    -> GROUP BY v;
+---+
| v |
+---+
| 2 |
| 2 |
+---+
2 rows in set, 1 warning (0.00 sec)

MariaDB [test]> SHOW WARNINGS;
+---------+------+--------------------------------------------+
| Level   | Code | Message                                    |
+---------+------+--------------------------------------------+
| Warning | 1052 | Column 'v' in group statement is ambiguous |
+---------+------+--------------------------------------------+
1 row in set (0.00 sec)
```

Postgres
```
test=# SELECT case when v = 1 then 2 else v end AS v
test-# FROM (SELECT 1 AS v UNION ALL SELECT 2 AS v) AS _
test-# GROUP BY v;
 v
---
 2
 2
(2 rows)
```

**Comment by realyota** [comment]
> One more example. Seems like clickhouse uses the evaluated expression in group by, and MySQL and Postgres gives priority to the table column value (however mysql shows the warning).

You can control this behaviour with `prefer_column_name_to_alias=1` (default off). Then it will give you the exact result as other DBMS:

```sql
SELECT multiIf(v = 1, 2, v) AS v
FROM
(
    SELECT 1 AS v
    UNION ALL
    SELECT 2 AS v
) AS _
GROUP BY v
SETTINGS prefer_column_name_to_alias = 1

Query id: 4724ccaa-fe65-457b-ae3c-89daf864d74a

┌─v─┐
│ 2 │
│ 2 │
└───┘

2 rows in set. Elapsed: 0.004 sec.
```

**Comment by EugeniyPetrov** [comment]
Awesome, thank you!

**Comment by EugeniyPetrov** [comment]
Fixed by prefer_column_name_to_alias = 1

**Comment by den-crane** [comment]
One more option is to use table aliases

https://fiddle.clickhouse.com/6933e79c-6a30-4696-9d73-c31086561986
```sql
SELECT multiIf(v = 1, 2, v) AS v
FROM
(
    SELECT 1 AS v
    UNION ALL
    SELECT 2 AS v
) AS _
GROUP BY _.v
```

**Comment by EugeniyPetrov** [comment]
In my case the query is generated by QuickSight and I can't change it
