### ISSUE TITLE
How can I create a temporary column in a table to insert non-important data?

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#53857]
Hi.
How can I create a temporary column in a table to insert non-important data?

For example, in the insert under the "discarded_col" column, it is not considered.

```sql
CREATE TABLE temp.sample_table 
(
    id Int32,
    clock String,
    value   Nullable(String),
    discarded_col Nothing 
)
ENGINE = MergeTree()
ORDER BY id ;

insert into temp.sample_table (id,clock,value,discarded_col) 
values (1,now(),'hello','Unimportant or ignorable data');


select *
from temp.sample_table ;

```

return result like this:

| id | clock               | value |
|----|---------------------|-------|
| 1  | 2023-01-01 12:00:00 | hello |

**Comment by cangyin** [comment]
document snippets:

> [MATERIALIZED](https://clickhouse.com/docs/en/sql-reference/statements/create/table#materialized)
> 
> Materialized expression. Values of such columns are always calculated, they cannot be specified in INSERT queries.
> 
> Also, **default value columns of this type are not included in the result of SELECT \***.
> 
> [EPHEMERAL](https://clickhouse.com/docs/en/sql-reference/statements/create/table#ephemeral)
> 
> Ephemeral column. Columns of this type are not stored in the table and it is **not possible to SELECT** from them. The only purpose of ephemeral columns is to build default value expressions of other columns from them.
> 
> [ALIAS](https://clickhouse.com/docs/en/sql-reference/statements/create/table#alias)
> 
> When SELECT queries explicitly reference columns of this type, the value is computed at query time from expr. **By default, SELECT * excludes ALIAS columns**.
