### ISSUE TITLE
Support azure blob storage authentication through workload identity

### ISSUE THREAD

**Issue by SmitaRKulkarni** [ClickHouse/ClickHouse#53850]
Currently azure blob storage supports authentication through managed identity & sas. Would be helpful to add support to authenticate using workload identity as well.

Azure sdk now has support for it as well( https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/identity/azure-identity#authenticate-azure-hosted-applications ) 

Proposed solution : 
Add a setting `use_workload_identity_for_azure` , if this is enabled, then we use the workload identity. If this is disabled, then the other methods i.e. managed identity or sas as used based on the function parameters.

**Comment by vinay92-ch** [comment]
Not able to assign to myself for some reason. I will follow up on the issue.

**Comment by saherawat** [comment]
@SmitaRKulkarni @vinay92-ch  Is there any documentation for using azure blob storage authentication through managed identity for click house. I tried to use it by passing a connection string containing SAS token but it did not work.

**Comment by ericmeadows** [comment]
This was completed with no documentation?  Is there a way to do this with GCP, @alexey-milovidov ?

**Comment by alexey-milovidov** [comment]
Documentation: https://clickhouse.com/docs/engines/table-engines/integrations/azureBlobStorage#authentication
