### ISSUE TITLE
DB::Exception: Table system.zookeeper doesn't exist.

### ISSUE THREAD

**Issue by rnrl1215** [ClickHouse/ClickHouse#53868]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

The manual is too unfriendly

I'm building a cluster using Clickhouse Keeper.

but i received message 'Table system.zookeeper doesn't exist.'

my spec
1. ch-server version 23.7.4.5
2. docker 3 instance

and i writer
/etc/clickhouse-server/conf.d 
- macro.xml
- cluster.xml
- zoo.xml

/etc/clickhouse-keeper/conf.d 
- zoo.xml

ch-server-1
   - ch-server
   - ch-keeper 
ch-server-2
   - ch-server
   - ch-keeper
ch-server-3
   - ch-server
   - ch-keeper

server1
vi /etc/clickhouse-keeper/zoo.xml

```
<yandex>
    <listen_host>0.0.0.0</listen_host>
<keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>1</server_id>
    <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
    <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>

    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>warning</raft_logs_level>
    </coordination_settings>

    <raft_configuration>
        <server>
            <id>1</id>
            <hostname>ch-server-1</hostname>
            <port>9234</port>
        </server>
        <server>
            <id>2</id>
            <hostname>ch-server-2</hostname>
            <port>9234</port>
        </server>
        <server>
            <id>3</id>
            <hostname>ch-server-3</hostname>
            <port>9234</port>
        </server>
    </raft_configuration>
    </keeper_server>	
</yandex>
```

vi /etc/clickhouse-server/conf.d/zoo.xml
```
<yandex>
<zookeeper>
        <node>
            <host>ch-server-1</host>
            <port>9181</port>
        </node>
        <node>
            <host>ch-server-2</host>
            <port>9181</port>
        </node>
        <node>
            <host>ch-server-3</host>
            <port>9181</port>
        </node>
    </zookeeper>
</yandex>

```

-------------------------------------------------
keeper test

![image](https://github.com/ClickHouse/ClickHouse/assets/33127270/73ae02b7-a3c2-4d95-8ed9-ecb47e6636d7)
------------------------------------------------
error

![image](https://github.com/ClickHouse/ClickHouse/assets/33127270/8f2d435f-d6e2-432c-8373-ffc349c138b4)

docker
![image](https://github.com/ClickHouse/ClickHouse/assets/33127270/1cbc445e-0836-49d3-8bf8-9db1b847123d)

**Comment by den-crane** [comment]
Check `/var/log/clickhouse-server/clickhouse-server.log`

**Comment by den-crane** [comment]
If there is no other error, then it is simply means that Clickhouse server does not see this file `/etc/clickhouse-server/conf.d/zoo.xml`
Are you sure you mapped it to a container? May be you have mapped `config.d` instead of obsolete `conf.d` ?
