### ISSUE TITLE
Ugly /usr/bin/clang symlinks required to compile from source on ubuntu.

### ISSUE THREAD

**Issue by gl-yziquel** [ClickHouse/ClickHouse#53881]
As of commit cba1d6688253d102103cbc1e737cfee806a99abc, on Ubuntu 22.04.3 LTS, cmake -S . -B build fails to generate the make instructions as clang is not of version above 15. I removed clang 14, but the /usr/bin/clang symlink is then not there anymore. With package clang-16, you do get /usr/bin/clang-16 but not /usr/bin/clang. Prefixing with declarations for CC=/usr/bin/clang-16, CXX=/usr/bin/clang++-16 and ASM=/usr/bin/clang is not enough to do the trick. So the build system seems to me, roughly, broken.

Symlinks do solve the issue, but they kind of hijack the distribution system. So it's not a very clean solution at all.

**Comment by Algunenano** [comment]
>  I removed clang 14, but the /usr/bin/clang symlink is then not there anymore. 


This is not a ClickHouse issue, but an Ubuntu issue. Have a look at the [update-alternatives](https://manpages.ubuntu.com/manpages/jammy/en/man1/update-alternatives.1.html) command.

> Prefixing with declarations for CC=/usr/bin/clang-16, CXX=/usr/bin/clang++-16 and ASM=/usr/bin/clang is not enough to do the trick. 

What fails exactly? If you pass the compiler to CMake it will use that compiler. Are you passing it to a clean build?

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/clickhouse-docs/issues/1384

**Comment by gl-yziquel** [comment]
Acknowledged that a custom build of llvm seems to be required.

However, it does seem that proper symlinking /usr/bin/clang(++)- -> /usr/bin/clang(++)-16 does the trick on ubuntu. (I'm currently at artifact 10733/11633 of the build.) Which seems to indicate that a custom build of llvm is not required, and that an adaptation or correction of the CMake build system would be smarter. My 2 cents.
