### ISSUE TITLE
Incorrect comparison with NULL using "ᴺᵁᴸᴸ':: Nullable(Strinq) is null" expression

### ISSUE THREAD

**Issue by gryumov** [ClickHouse/ClickHouse#53903]
I expect that the expression `"'ᴺᵁᴸᴸ':: Nullable(String) is null` should return `true`, but returns `false`

![Снимок экрана 2023-08-25 в 22 37 29](https://github.com/ClickHouse/ClickHouse/assets/33372067/e9576368-0411-4b4b-bfee-c9bc005b28da)

**Comment by UnamedRus** [comment]
From ClickHouse perspective, you just making string with fancy unicode characters, which ClickHouse use to distinguish "ᴺᵁᴸᴸ" values from NULL or null

```
SELECT
    CAST('ᴺᵁᴸᴸ', 'Nullable(String)') IS NULL AS t1,
    CAST('ᴺᵁᴸᴸ', 'Nullable(String)') AS t2,
    version()

Query id: 419f31b8-77f7-4079-a564-5343bef69232

┌─t1─┬─t2───┬─version()───┐
│  0 │ ᴺᵁᴸᴸ │ 23.4.1.1168 │
└────┴──────┴─────────────┘

SELECT NULL:: Nullable(String) is null as t1, NULL:: Nullable(String) as t2, version();


┌─t1─┬─t2───┬─version()───┐
│  1 │ ᴺᵁᴸᴸ │ 23.4.1.1168 │
└────┴──────┴─────────────┘
```
