### ISSUE TITLE
The avg or avgif function returned unexpected data

### ISSUE THREAD

**Issue by xiaochaoren1** [ClickHouse/ClickHouse#53915]
> You have to provide the following information whenever possible.

**Describe what's wrong**
ClickHouse server version is v22.8.6
![b74fc243-430f-42c2-b544-836a9ee43b6e](https://github.com/ClickHouse/ClickHouse/assets/42240939/e6edacf7-e75b-4d11-b3e8-2cfdab150f18)
This statement returned a piece of false data, which is expected to return no data

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by tavplubix** [comment]
It works as expected. See https://clickhouse.com/docs/en/sql-reference/aggregate-functions/combinators#-ordefault and https://clickhouse.com/docs/en/sql-reference/aggregate-functions/combinators#-ornull
