### ISSUE TITLE
filesystem_prefetch_max_memory_usage can't be zero

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#54008]
`filesystem_prefetch_max_memory_usage` documentation under Settings.h says:

```
    M(UInt64, filesystem_prefetch_max_memory_usage, "1Gi", "Maximum memory usage for prefetches. Zero means unlimited", 0) \
```

But when you try to set it to 0 to allow unlimited memory you get an exception:
```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Setting `filesystem_prefetch_max_memory_usage` must be non-zero. (BAD_ARGUMENTS)
```

This was changed in https://github.com/ClickHouse/ClickHouse/pull/48973 cc @kssenii 

Should 0 be allowed and be unlimited? The code under the condition seems to check if it's or not zero, so it seems like it, but maybe there is a reason this was disallowed when testing random settings.

**Comment by kssenii** [comment]
> Should 0 be allowed and be unlimited? The code under the condition seems to check if it's or not zero, so it seems like it, but maybe there is a reason this was disallowed when testing random settings.

I thought that it is better not to allow that as otherwise it can very easily result in OOM.

**Comment by alexey-milovidov** [comment]
Ok, let's fix the embedded docs then.
