### ISSUE TITLE
use "alter table xxx,add...",except,"Cannot enqueue replicated DDL query for a replicated shard"

### ISSUE THREAD

**Issue by nohunt** [ClickHouse/ClickHouse#5401]
version:18.16.1
table engine : ReplicateMergeTree

i use , “alter table xxx on cluster xxx add column app string after name”; except,

except info:Cannot enqueue replicated DDL query for a replicated shard

**Comment by filimonov** [comment]
Can you show your cluster definition?

**Comment by blinkov** [comment]
@nohunt, do you have any further questions?

**Comment by alexey-milovidov** [comment]
Implemented in https://github.com/ClickHouse/ClickHouse/pull/5757
