### ISSUE TITLE
Inverted Index Query Memory Retention and Limitation Issues

### ISSUE THREAD

**Issue by Ronniexie** [ClickHouse/ClickHouse#54042]
Description
I am using ClickHouse's inverted index for queries, and I've noticed a couple of issues that I'd like to discuss:

Memory Growth: Despite setting max_server_memory_usage to 30G, the memory usage keeps increasing, and it even exceeds the container's memory limit. This issue persists until the Kubernetes environment restarts the ClickHouse instance.

Memory Not Released: After each query, the memory allocated during the query execution doesn't seem to be released. Subsequent queries continue to allocate memory on top of the previously used memory.

Is there a potential bug, or should specific configurations be adjusted to resolve the issue?

Additional Information
![image](https://github.com/ClickHouse/ClickHouse/assets/19404951/3cdda72e-60a4-4de8-86f3-10c3ec638dea)

**Comment by den-crane** [comment]
inverted indexes are experimental and can use ANY amount of memory because of merges mis-design https://github.com/ClickHouse/ClickHouse/issues/47875#issuecomment-1479494381

**Comment by Ronniexie** [comment]
> inverted indexes are experimental and can use ANY amount of memory because of merges mis-design [#47875 (comment)](https://github.com/ClickHouse/ClickHouse/issues/47875#issuecomment-1479494381)

Thanks for your answer @den-crane ，I still have two questions:  

1. Is the increase in memory usage due to merge operations? Why does a LIKE query trigger merge operations?

3. Why is memory not being released? After each query, the memory allocated during query execution doesn't appear to be released. Subsequent queries continue to allocate memory on top of the previously used memory.
