### ISSUE TITLE
[inverted index] metadata causes memory issue in low memory setups

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#54040]
Is this map to be defined as a cache data, or a  lazy-loaded and memory-resident metadata (like primary.bin) ?

https://github.com/ClickHouse/ClickHouse/blob/17f37541935bce25e2b200f061baafa4dadb338e/src/Storages/MergeTree/GinIndexStore.cpp#L470

This line may cause high ratio of memory consumption in low resource cluster setups, which never releases (except when dropping parts) once a query loads it.

So I wanted to known how to define this memory consuming map, just to turn it off or possibly make a LRU cache strategy for it.

**Comment by genzgd** [comment]
This is a community contributed feature -- @HarryLeeIBM has some background?

**Comment by juppylm** [comment]
I do think there is an issue here, even though there is a **remove** method provided. It might be worth considering replacing **unordered_map** with **CacheBase** that can control memory consumption.
https://github.com/ClickHouse/ClickHouse/blob/17f37541935bce25e2b200f061baafa4dadb338e/src/Storages/MergeTree/GinIndexStore.cpp#L477
