### ISSUE TITLE
How to migrate from standalone to cluster（如何迁移单机版到集群版）

### ISSUE THREAD

**Issue by yangshubin2023** [ClickHouse/ClickHouse#54048]
I want to modify the standalone version of the clickhouse to the cluster version. How to smoothly migrate data from the standalone version to the cluster version, or whether the standalone version can become a node of the cluster version through certain configurations? I don't see any corresponding instructions in the document, and I hope to receive a response.

我要将单机版的clickhouse修改为集群版的，数据如何平滑的从单机版迁移到集群版，或者单机版是否可以通过某些配置变为集群版的一个节点，我看文档中没有相应的说明，希望能够得到回复。

**Comment by den-crane** [comment]
Do you mean how to convert MergeTree to Replicated ?
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-converting-mergetree-to-replicated/

**Comment by lampjian** [comment]
It depends on your cluster plan. If you need a backup replica for each shard,  upstairs is the solution, and you must recreate all your tables and polulate them again. Another way is congfiguring your cluster with one replica in each shard, maybe just recreate empty tables with the same uuid on other nodes is sufficient.
