### ISSUE TITLE
DB Exception: Index for Low Cardinality out of range

### ISSUE THREAD

**Issue by srilesh** [ClickHouse/ClickHouse#54050]
Using Python 3.11 Clickhouse_Connect to insert a dataframe into a table with many LowCardinality String & FixedString columns. 
Code 117: DB Exception: Index for LowCardinality out of range. The dictionary size is 2, but found index with value 85: While executing Native. (INCORRECT_DATA) (version 23.5.2.7 (official build))

Can the column for which this exception is generated be identified in the logs or trace?

**Comment by tavplubix** [comment]
How exactly do you insert data? Do you have a reproducible example? 

Also, maybe you should have created this issue in https://github.com/ClickHouse/clickhouse-connect

**Comment by filimonov** [comment]
> Can the column for which this exception is generated be identified in the logs or trace?

I'm afraid you'll need to bisect the data currently.
(yes it would be nice to improve that)
