### ISSUE TITLE
Too large array size: (while reading column key_words)

### ISSUE THREAD

**Issue by jiugem** [ClickHouse/ClickHouse#54053]
The materialized view of the ReplicatedAggregatingMergeTree table engine executes the query as an aggregate function of many columns. When querying the entire range of data or the older data range of the table, the following error will be reported:

Code: 128. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Too large array size: (while reading column key_words): (while reading from part /data/clickhouse/store/7cc/7ccfc106- f02a-4c5a-bccf-c106f02a7c5a/20230601_0_1977061_5116/ from mark 0 with max_rows_to_read = 8192): While executing MergeTreeThread. (TOO_LARGE_ARRAY_SIZE)

The aggregate function corresponding to the key_words column is as follows:
groupArrayMerge(key_words) AS key_words

How to solve this error? The amount of data in my entire table is actually not particularly large, only a few GB.

**Comment by davenger** [comment]
There is an internal limit on how big an array can be. Recently we fixed a bug that allowed saving arrays that cannot be read https://github.com/ClickHouse/ClickHouse/pull/53550

In your case a workaround might be to use groupArrayMerge with maximum length parameter:
```
SELECT groupArrayMerge(10)(key_words)
FROM
(
    SELECT groupArrayState(10)([CAST(number, 'String')]) AS key_words
    FROM numbers(4242)
)

Query id: d18c3815-dd28-4459-91b9-366d6d731460

┌─groupArrayMerge(10)(key_words)────────────────────────────────┐
│ [['0'],['1'],['2'],['3'],['4'],['5'],['6'],['7'],['8'],['9']] │
└───────────────────────────────────────────────────────────────┘
```

https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/grouparray
