### ISSUE TITLE
How to limit fetches for a particular table 

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#54061]
Let's say, I want to limit fetching for a table **(both bandwidth and the total number of fetches)**. This is important, e.g. when I want to replicate a big table from scratch, I don't want:

1. That table uses too much fetching bandwidth (obviously)
2. That table dominates the fetching pool: we usually has a limit fetch pool size, and don't want to change it frequently

We found that there's no way do it now. We've tried some settings:

- `max_replicated_fetches_network_bandwidth` --> this is good and can help to achieve (1)
- `replicated_max_parallel_fetches_for_host `: iiuc, fetches from same endpoint will get connections from a pool, and `replicated_max_parallel_fetches_for_host = 3` means for a particular endpoint there're  maximum 3 fetches per pool. But even we set it to `3`, the table will dominate the fetching pool.

If `replicated_max_parallel_fetches_for_host = 3` but the table currently having 30 fetches (all from 1 replica), what happens with 27 fetches? If they're just waiting for connection, I think CH should account it in `StorageReplicatedMergeTree::canExecute` (the same way that bandwidth throttler is being used).

Appreciate any comments [THANKS]!

cc @den-crane

**Comment by den-crane** [comment]
```
alter table mytable modify setting max_replicated_fetches_network_bandwidth=1000000;
```

**Comment by ivan-tkatchev** [comment]
> ```
> alter table mytable modify setting max_replicated_fetches_network_bandwidth=1000000;
> ```

For those who might be googling this issue, like me - this doesn't actually work. It makes fetches slower, but does not unclog the fetch pool (system.replicated_fetches) from being overwhelmed with old and huge fetches.
