### ISSUE TITLE
any suggestion for clickhouse support more update?

### ISSUE THREAD

**Issue by WeiGangqiang** [ClickHouse/ClickHouse#5409]
ask another question, our service need update about 50 rows with one or several columns value per second, can you give some suggest for clickhouse configuration to support more update。

 @WeiGangqiang
 Author

**Comment by nvartolomei** [comment]
Postgres?

**Comment by WeiGangqiang** [comment]
when i do some update operations one second, why the merge process spend so many time in background?
{
"database": "default",
"table": "entries",
"elapsed": 1151.89503534,
"progress": 0,
"num_parts": "1",
"source_part_names": ["16_1139047_1139047_0"],
"result_part_name": "16_1139047_1139047_0_1162146",
"partition_id": "16",
"is_mutation": 1,
"total_size_bytes_compressed": "19753",
"total_size_marks": "1",
"bytes_read_uncompressed": "0",
"rows_read": "0",
"bytes_written_uncompressed": "0",
"rows_written": "0",
"columns_written": "0",
"memory_usage": "86862937",
"thread_number": "6"
}

**Comment by WeiGangqiang** [comment]
> Postgres?

clickhouse,  our service's main scene is OLAP, but need support update 50 rows one second

**Comment by den-crane** [comment]
@WeiGangqiang https://github.com/yandex/ClickHouse/issues/5125#issuecomment-487599751

**Comment by WeiGangqiang** [comment]
> @WeiGangqiang [#5125 (comment)](https://github.com/yandex/ClickHouse/issues/5125#issuecomment-487599751)

but we has 10 Billion rows, can use same way ?

**Comment by WeiGangqiang** [comment]
> @WeiGangqiang [#5125 (comment)](https://github.com/yandex/ClickHouse/issues/5125#issuecomment-487599751)

Thank you,  this is helpful
