### ISSUE TITLE
Does asynchronous insertion support TCP connections?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#54098]
I have read [doc](https://clickhouse.com/docs/en/optimize/asynchronous-inserts) twice, and I use HTTP successful.
But when I use TCP(9000) to insert data, it does not work, and I can not query any logs in asynchronous_insert_log. What is the reason for this? Does asynchronous insertion support TCP connections?

PS:
I use cpp SDK. ClickHouse version 23.7

Thank you very much!

**Comment by cangyin** [comment]
I think TCP supports that, I did some tests with clickhouse-client (TCP interface) on async insert feature, that works.

I advice that do a test query:
```sql
SELECT getSetting('async_insert');
SELECT getSetting('async_insert') SETTINGS async_insert = 1;
```
to check the 'async_insert' setting is enabled in config file or enabled by the insert query.

**Comment by den-crane** [comment]
TCP protocol supports async inserts. But it is a special type of insert when data is attached to insert text. Client library should support it. 

Please create a feature request here https://github.com/ClickHouse/clickhouse-cpp/issues

**Comment by genzgd** [comment]
Correct, async inserts only work over the TCP native protocol if the data is sent as SQL text.  If you use a client such as `clickhouse-go`, `clickhouse-driver` (Python), or the C++ SDK to manage your native protocol inserts actually using the native data format, async inserts are not available.
