### ISSUE TITLE
Setting database transactions logs for new CH driver

### ISSUE THREAD

**Issue by Onajk** [ClickHouse/ClickHouse#54107]
Hi,
I'm facing a problem of no database transactions logs after upgrading CH driver.
CH version: 22.8.15.25
We were using: `"ru.yandex.clickhouse" % "clickhouse-jdbc" % "0.3.0"`
And logger: `<logger name="ru.yandex.clickhouse.ClickHouseStatementImpl" level="DEBUG"/>` set to debug which gave me a lot of information about queries that were running against CH Database during Integration Tests.
I have switched to: `"com.clickhouse" % "clickhouse-jdbc" % "0.4.6"`
And logger: `<logger name="com.clickhouse.jdbc.internal.ClickHouseStatementImpl" level="DEBUG"/>`
But with this version, this logger gives me no information about queries at all.

I'm running Integration Tests which are querying CH Database. Tests are successful but I have a lot of warnings:
`[c.c.j.i.ClickHouseConnectionImpl] [JDBC Compliant Mode] Transaction is not supported. You may change jdbcCompliant to false to throw SQLException instead.`
I have used 
`<logger name="com.clickhouse.jdbc.internal.ClickHouseConnectionImpl" level="ERROR"/>`
To show only errors from that logger so I can hide all those warnings.
Are those warnings the reason why I can't see any transactions logs from `com.clickhouse.jdbc.internal.ClickHouseStatementImpl`?
Is there something I can do to see those logs the same way as for 0.3.0 driver?

**Comment by den-crane** [comment]
you ask this here https://github.com/ClickHouse/clickhouse-java/issues
