### ISSUE TITLE
Support jsonMerge function  

### ISSUE THREAD

**Issue by ucasfl** [ClickHouse/ClickHouse#54102]
**Use case**

```sql
select jsonMerge(json_doc, json_doc [, json_doc] ...)
```

returns a merged JSON object

**Additional context**

See also https://github.com/ClickHouse/ClickHouse/issues/45068.

**Comment by Joeywzr** [comment]
Can I take this?😏

**Comment by filimonov** [comment]
BTW what with duplicate keys? Especially if the key type differs in different (sub) jsons? Just ignore that and concat the jsons?

I.e.

```
Json_merge('{"a" :1}','{"a":[1]}')
```

**Comment by ucasfl** [comment]
> BTW what with duplicate keys? Especially if the key type differs in different (sub) jsons? Just ignore that and concat the jsons?
> 
> I.e.
> 
> ```
> SELECT jsonMerge('{"a" :1}','{"a":[1]}')
> ```

In MySQL:
```sql
SELECT json_merge('{"a" :1}','{"a":[1]}') as json;

Output:

json
{"a": [1, 1]}
```

**Comment by filimonov** [comment]
> So, for duplicate keys, we can merge their values into a Tuple in ClickHouse.

Does not sound easy now :) 

And what with nested objects?

**Comment by Alex-Cheng** [comment]
For duplicate key, overriding the previous one should be an easy and reasonable solution.
