### ISSUE TITLE
When using the general view created by Distrbuted, the result of querying the aggregation field is not as expected

### ISSUE THREAD

**Issue by anemoptero** [ClickHouse/ClickHouse#54108]
Sorry for my poor English, but I try to describe as much as possible

I create a view, its example is like this

create view database.test_order_view on cluster sharding_rule {
  order_no String,
  order_amt Decimal(18, 5)
} as 
select 
 order_no,
 order_amt
from database.test_order_distributed

When I query using the following syntax

select sum(order_amt) from database.test_order_view

It seems that only local aggregate data can be found...

I am using version 22.3.2.1

thx.

**Comment by den-crane** [comment]
Please provide reproducible example (all steps, create / insert /select, expected results).

22.3 is out of support. Upgrade to 23.7
