### ISSUE TITLE
RFC: DebugBarriers feature for test instrumentation

### ISSUE THREAD

**Issue by stigsb** [ClickHouse/ClickHouse#54105]
Sometimes during testing, it is difficult to recreate certain corner cases, such as race conditions or exceptions from network issues etc. This also means it is very difficult to cover code for handling such cases with tests.

I would like to propose a mechanism called Debug Barriers to address this, with emphasis on integration tests (controlling them from Python).

Debug Barriers are a way of manually instrumenting code in places where it is useful to give integration tests and functional tests control over the execution, for either blocking threads, inserting artificial delays or failure injection. It has to be enabled when building, and is meant for test binaries, not releases.

If this is interesting to folks, I will create a PR with the implementation.

### Execution Barriers

An active execution barrier makes either a single thread or all threads block when reaching the debug barrier. Blocked threads will block until the execution barrier is removed.

This is useful for controlling concurrency between threads, for example to reproduce a tricky race condition.

### Artificial Delays

Artificial delays simply wait a specified number of nanoseconds every time execution reaches the debug barrier.

This is also useful for testing concurrency situations, for example when handling straggler threads that work slower than others, for whatever reason.

### Failure Injection

You can give a probability that an exception is thrown when reaching the barrier, along with an exception code and message.

This is useful for testing error handling for errors that are very hard/time-consuming or downright impossible to reproduce in tests.

### Enabling

Debug barriers are a compile-time option and disabled by default. To enable them, use the `-DENABLE_DEBUG_BARRIERS=ON` cmake option.

### Adding Barriers

In your source code:

```c++
#include <Common/DebugBarriers.h>

...
void YourClass::yourFunc()
{
    ...
    DEBUG_BARRIER("barrier_name");
    ...
}
```

You must use use unique barrier names within a file, and only one barrier per line.

There are also two macros for adding a barrier on just exiting, or on entering and exiting a scope:

```c++
SCOPE_EXIT_DEBUG_BARRIER("name1");
SCOPE_ENTER_EXIT_DEBUG_BARRIER("foo_enter", "foo_exit");
```

Note that if debug barriers are not enabled at compile time, these macros evaluate to nothing, so there is no overhead if disabled.

Debug barriers are collected in `DB::DebugBarrierCatalog` as they are encountered.

### Inspecting Debug Barriers

Debug barriers can be viewed and controlled through the `system.debug_barriers` table. This table interacts with the DebugBarrierCatalog.

```sql
SELECT * FROM system.debug_barriers FORMAT Vertical
```

```
Row 1:
──────
file:               src/Databases/MySQL/MaterializedMySQLSyncThread.cpp
line:               311
thread_id:          264649
name:               readEvent
pretty_function:    void DB::MaterializedMySQLSyncThread::synchronization()
blocked:            0
fault_probability:  0
fault_code:         0
fault_message:
delay_nanoseconds:  0
times_reached:      12435
nanoseconds_waited: 0
threads_blocking:   0
faults_injected:    0

Row 2:
──────
file:               src/Databases/MySQL/MaterializedMySQLSyncThread.cpp
line:               834
thread_id:          264649
name:               flush1
pretty_function:    void DB::MaterializedMySQLSyncThread::flushBuffersData(DB::MaterializedMySQLSyncThread::DatabaseBuffer &, const MySQLReplication::Position &)
blocked:            0
fault_probability:  0
fault_code:         0
fault_message:
delay_nanoseconds:  0
times_reached:      2072
nanoseconds_waited: 0
threads_blocking:   0
faults_injected:    0
```

`file` and `line` are the source file and line number of the barrier location (at compile time).

`thread_id` is 0 for process-wide barriers, and a thread id for thread-specific barriers. If a barrier exists both for one or more threads and process-wide, the thread-specific barrier is handled first, then the process-wide barrier.

`name` is a symbolic name for more easily identifying the barrier from a test (hardcoding file/line is impractical).

`pretty_function` is the signature of the function that contains the barrier.

`blocked` is 1 if the barrier should block execution, or 0 if not.

`fault_probability` is a Float32 between 0.0 and 1.0 describing the likelihood that an exception will be thrown. The exception is always a `DB::Exception` with code/message taken from `fault_code` and `fault_message`.

If `delay_nanoseconds` is greater than 0, the barrier sleeps for at least this long every time it is reached.

`times_reached`, `nanoseconds_waited`, `threads_blocking` and `faults_injected` are metric columns.

### Controlling Barriers From SQL

The `system.debug_barriers` table is implemented to use `tuple(file, name, thread_id)` as a primary key, and inserts are handled as upserts.

This blocks the `flush1` barrier we saw above for thread 264649:

```sql
INSERT INTO system.debug_barriers (file, name, thread_id, blocked)
VALUES('src/Databases/MySQL/MaterializedMySQLSyncThread.cpp', 'flush1', 264649, 1)
```

Inserting a 0 into the `blocked` column will unblock it, and if thread 264649 has reached the barrier, it will resume.

A single barrier can be configured to do both blocking, delay and fault injection. They will be executed in that order.

To clear metric columns (`times_reached`, `nanoseconds_waited` and `threads_blocking`) insert a 0 value in them.

To clear all debug barriers and unblock any blocked threads, run `TRUNCATE TABLE system.debug_barriers` (currently executing delays will finish sleeping). They will be re-populated again like before, but with no actions configured

### Controlling Barriers From Python

Here is what the Python interface could look like:

`tests/integration/helpers/debug_barriers.py` contains a `DebugBarrier` class for interacting with the `system.debug_barriers` table.
`tests/integration/helpers/fixtures.py` contains a function-scoped `debug_barrier` fixture that clears all barriers after each test.

```py
from helpers.fixtures import debug_barriers

def my_test(debug_barriers, clickhouse_node):
    barrier = debug_barriers.get("src/Foo/Bar.cpp", "barrier_name") # will affect any thread
    barrier.block()    # now execution in `my_code()` blocks until the `blocked` column becomes 0 for this barrier
    done = False
    def run_blocking_query():
        clickhouse_node.query("/* do something that executes my_code() - will block! */")
        done = True
    t = threading.Thread(target=run_blocking_query)
    barrier.unblock()
    t.join()
    assert done
```

The `DebugBarrier` class has these methods:

```py
# This is a process-wide barrier (thread id 0):
barrier = DebugBarrier('src/Databases/MySQL/MaterializedMySQLSyncThread.cpp', 'flush1', 0)

# Use the block() and unblock() methods to configure blocking
barrier.block()

# Configure a delay every time the barrier is reached
barrier.set_delay(500 * 1000 * 1000) # 500ms

# Inject a failure with 20% probability
barrier.set_fault_injection(0.2, 209, "socket timeout")

# A DebugBarrier object has the same properties as the system table, in other
# words `file`, `line`, `thread_id`, `name`, `pretty_function`, `blocked`,
# `fault_probability` and so on.
# It is populated by running a SELECT query, and must be explicitly refreshed with current data:
barrier.refresh()

# refresh() returns self, use that when doing asserts:
assert barrier.refresh().times_reached > 0

# use assert_eventually() with a callable to do asserts on asyncronous things
from helpers.test_tools import assert_eventually
barrier.unblock()
assert_eventually(lambda: barrier.threads_blocking == 0)

# reset configuration (blocking, delays, faults)
barrier.reset()

# reset configuration and clear metrics
barrier.clear()

# change multiple barrier features in one operation:
barrier.apply_changes({
    'blocked': 0,
    'delay_nanoseconds': 200000000,
})
```

### Controlling Barriers From C++

```c++
#include <Common/DebugBarriers.h>

/// Listing current barriers
DebugBarrierCatalog & barrier_catalog = DebugBarrierCatalog::instance();
std::vector<DebugBarrier::Snapshot> current_barriers = barrier_catalog.getBarriers();

/// Getting a single barrier as a view object (only for observing state, not manipulating)
DebugBarrier::Snapshot barrier = barrier_catalog.getBarrier({"src/Common/DebugBarriers.cpp", "name"});

/// Modifying a barrier
DebugBarrier::Key key{"src/Foo/Bar.cpp", "name", thread_id};
DebugBarrier::Change change{
    .blocked = 0,
    .delay_nanoseconds = 200000000,
};
barrier_catalog.applyChange(key, change);
```

**Comment by alexey-milovidov** [comment]
Maybe it intersects with failpoints that we've added recently? https://github.com/ClickHouse/ClickHouse/pull/49361

**Comment by stigsb** [comment]
> Maybe it intersects with failpoints that we've added recently? #49361

Ah, I did not notice failpoints until now! Yes, they overlap quite a bit, enough that it does not make sense to have both.
I will update the RFC after redesigning it to extend failpoints instead.
