### ISSUE TITLE
clickhouse replication user authentication is not supporting sha256 hashing

### ISSUE THREAD

**Issue by venkip541** [ClickHouse/ClickHouse#54111]
Hi Team,

I am trying to establish a clickhouse cluster with 2 shard and 2 replication, when i have configured my replication with plane password i can able to establish successful communication between replication instances, the same when i have used sha256 hashing, i am getting password mismatch issues, below is my cluster configuration. Need your assistance in fixing the same.

                <clickhouse>
                        <shard>
                                <internal_replication>true</internal_replication>
                                <replica>
                                        <host>clickhouse-server-1-0.clickhouse-server.clickhouse.svc.cluster.local</host>
                                        <port>9000</port>
                                        <user>posthog</user>
                                        <password_sha256_hex>67e5a3025bc013d09e3a1e6659f2e53efc7d137272ffe72b6dc8344f578461cf</password_sha256_hex>
                                </replica>
                                <replica>
                                        <host>clickhouse-server-2-0.clickhouse-server.clickhouse.svc.cluster.local</host>
                                        <port>9000</port>
                                        <user>posthog</user>
                                        <password_sha256_hex>67e5a3025bc013d09e3a1e6659f2e53efc7d137272ffe72b6dc8344f578461cf</password_sha256_hex>
                                </replica>
                        </shard>
                <clickhouse>

Tried with interserver_http_credentials, but i am not able to find any example with password hasing

https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server-settings-interserver-http-credentials

Regards
Venkatesh. P

**Comment by UnamedRus** [comment]
You can't have hashed password here, it should be clear text.

look into inter server secret


https://docs.altinity.com/operationsguide/security/clickhouse-hardening-guide/network-hardening/#encrypt-cluster-communications

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/44030

**Comment by den-crane** [comment]
Ah, there is a new feature https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/operations/configuration-files.md#encrypting-and-hiding-configuration-encryption

v23.7.1.2470-stable.md:* Implement support of encrypted elements in configuration file Added possibility to use encrypted text in leaf elements of configuration file. The text is encrypted using encryption codecs from <encryption_codecs> section. [#50986](https://github.com/ClickHouse/ClickHouse/pull/50986) ([Roman Vasin](https://github.com/rvasin)).
