### ISSUE TITLE
Replicated table existing only on one cluster

### ISSUE THREAD

**Issue by phyndman** [ClickHouse/ClickHouse#54116]
We're having an issue with our new Clickhouse set up. It appears that one of our replicated tables somehow exists on one replica and not the other. This is causing us issues whereby we cant create or drop any table in the troublesome database where this is an issue

In going though the log, there appears to be a a task that constantly tries and fails to truncate the troublesome table, which it obviously cant find as it doesn't exist on that replica. below is a snippet from the Clickhouse log

```
2023.08.31 09:58:56.693318 [ 470 ] {} <Error> DDLWorker(db_name): Unexpected error, will try to restart main thread: Code: 341. DB::Exception: Unexpected error: Code: 60. DB::Exception: Table db_name.table_name doesn't exist. (UNKNOWN_TABLE) (version 23.5.4.25 (official build)). (UNFINISHED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e347595 in /usr/bin/clickhouse
1. ? @ 0x0000000008b66ee3 in /usr/bin/clickhouse
2. DB::DDLWorker::processTask(DB::DDLTaskBase&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x00000000130b2f0c in /usr/bin/clickhouse
3. DB::DDLWorker::scheduleTasks(bool) @ 0x00000000130b0033 in /usr/bin/clickhouse
4. DB::DDLWorker::runMainThread() @ 0x00000000130a968d in /usr/bin/clickhouse
5. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000130bf9e9 in /usr/bin/clickhouse
6. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e41b3b4 in /usr/bin/clickhouse
7. ? @ 0x000000000e420ba1 in /usr/bin/clickhouse
8. ? @ 0x00007f86381b9609 in ?
9. clone @ 0x00007f86380de133 in ?
 (version 23.5.4.25 (official build))
```

Querying the table system.clusters for this specific database, only one of the 2 indicates is_active=1. For all other databases with the same set up both clusters are active.

What can I do to try and do to address this short of trashing everything and starting again?

**Comment by genzgd** [comment]
Can you simply run the create table statement on the node that doesn't seem to have the table?  It should sync automatically  with the other replicas via Keeper assuming they share the same zookeeper path argument.

**Comment by phyndman** [comment]
Thanks for the info. When I'm trying to explicitly name the UUID and SHARD in creating the table on the replica the table is missing from (using the below) to ensure its the same zookeeper path

```
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/ABCDEF/{shard}',
 'replica1',
 batchid)
ORDER BY (brand,
 unique_id)
```
I'm getting this error

SQL Error [80] [07000]: Code: 80. DB::Exception: Explicit zookeeper_path and replica_name are specified in ReplicatedMergeTree arguments. If you really want to specify it explicitly, then you should use some macros to distinguish different shards and replicas. (INCORRECT_QUERY) (version 23.5.4.25 (official build))

Any ideas what I'm doing wrong?

**Comment by genzgd** [comment]
That's a new one to me, but maybe you you just need a `replica` macro defined instead of the hard coded 'replica1'?

**Comment by genzgd** [comment]
Because the replica is just coming up it has to do a lot of work to synchronize state with the existing replica, so you may just have to wait.  Can you check the `system.replication_queue` on the new node to see if there are exception or other errors as it tries to get data from the existing replica?

**Comment by genzgd** [comment]
I don't think it should be affecting other replication.  Are your ClickHouse settings and hardware consistent across all of your nodes?  It seems like something successfully merged on one replica but you don't have space on a different one.

**Comment by phyndman** [comment]
potentially yeh. have tried freeing up some space on the discs to see if it moves through now

In the below I get that is_active=0 for one of the clusters. Does this mean anything?

SELECT * FROM system.clusters
where cluster = 'db_name';

**Comment by phyndman** [comment]
we are using the Replicated data engine. Do you know where the ddl task queue is if the replicated data engine is being used?

**Comment by genzgd** [comment]
I believe that it's kept in keeper, but if you're using that experimental database engine you shouldn't have needed to create the new ReplicatedMergeTree table manually in the first place, so I'm afraid some things have gotten out of sync.

**Comment by genzgd** [comment]
Also the space from the `system.replication_queue` doesn't necessarily refer to disk space, there's a limited "pool" of space that merges use from the file system, and it's limited so merges just don't eat all of your disk.  If there's only one merge running that pool shouldn't be full, unless it's configured too small by default.

**Comment by phyndman** [comment]
So managed to solve this but it was a bit of a faff 

a) Clearing up some disk space allowed the task/merge stuck in the replication queue to complete.
b) We then went into zookeeper on the failing node and updated the values of "log_ptr" and "digest" to match the node that was working ok
c) restarted the pod/node that seemed to have an issue which then became "active" again

All seems to be ok now

Thanks for the assistance and pointers :-)
