### ISSUE TITLE
Does ReplacingMergeTree have the capability to identify partitions that have changed?

### ISSUE THREAD

**Issue by Chen768959** [ClickHouse/ClickHouse#54127]
I am currently using version 21.8 of `ReplacingMergeTree` frequently. I have noticed that after I insert data, it seems that all partitions undergo automatic merging, even if some partitions do not require merging.
I would like to know if the current version of `ReplacingMergeTree` has the capability to identify `partitions` that have changed, so that only the necessary `partitions` can be automatically merged. If the latest version does not have this functionality, perhaps I can contribute by adding this optimization.
example:
```
CREATE TABLE test_table
(
    `key` UInt64,
    `someCol` String
)
ENGINE = ReplacingMergeTree
PARTITION BY modulo(key, 40) 
PRIMARY KEY key 
ORDER BY key;
```
Then insert a large amount of data into it, covering all partitions from 0 to 39.
Then `optimize table test_table final;`
Afterwards, insert two datas.
```
insert into test_table(key, someCol) values(1, 'test1');
insert into test_table(key, someCol) values(5, 'test5');
```
Would `ReplacingMergeTree` only automatically merge `partition(1)` and `partition(5)` at this point? Or will all `partitions (0-39)` be automatically merged after a certain period of time?

**Comment by den-crane** [comment]
--optimize_skip_merged_partitions arg                                                Skip partitions with one part with level > 0 in optimize final

**Comment by den-crane** [comment]
`optimize table test_table final settings optimize_skip_merged_partitions=1;`

**Comment by Chen768959** [comment]
> --optimize_skip_merged_partitions arg Skip partitions with one part with level > 0 in optimize final

Thank you for your answer
