### ISSUE TITLE
Broken soft links after copying /var/lib/clickhouse/data to other directory

### ISSUE THREAD

**Issue by clorenzmynetwatchman** [ClickHouse/ClickHouse#54130]
Inadvertently left the path in the config.xml to the default data paths when I wanted to point to a different mount.  I then copied the /var/lib/clickhouse/data directory to another directory.  Everything works fine; however, I am seeing red flashing file and directory when exploring the data directory.  

The strange thing is everything works great.  Should we fix the soft links?  Could that cause any issues?  

![image](https://github.com/ClickHouse/ClickHouse/assets/85181569/81a33dc1-9fcc-4dbf-8615-aa68bd87da97)

**Comment by tavplubix** [comment]
ClickHouse does not use these links, they are for introspection purposes only, so you can ignore or remove them. Also, you can create a `force_restore_data` flag and restart `clickhouse-server`, so it will try to fix the symlinks
