### ISSUE TITLE
Too much memory allocating when using ARRAY JOIN (4 TiB)

### ISSUE THREAD

**Issue by Blackmorse** [ClickHouse/ClickHouse#54170]
Clickhouse version: 23.3.10.5

I have a table with a only one column, which is `Array(UInt64)`. Generally each array contains up to 10 elements, but there is one record with 600,000 elements. 
I'm trying to <i>explode</i> this table using <b>ARRAY JOIN</b> in a way that each array of size n will be converted into `n` rows with 2 columns: `<element of the array>, <array itself>`.
When dealing with that 600,000-elements array query is failed with memory exceed error: ` DB::Exception: Memory limit (total) exceeded: would use 4.00 TiB (attempt to allocate chunk of 4398046511208 bytes), maximum: 6.90 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.. (MEMORY_LIMIT_EXCEEDED)`.

Steps for reproducing:

```
CREATE TABLE default.numbers_table
(
    `numbers` Array(UInt64)
)
ENGINE = MergeTree
ORDER BY tuple();

INSERT INTO numbers_table SELECT groupArray(hash_number)
FROM
(
    SELECT toUInt64(cityHash64(number)) AS hash_number
    FROM system.numbers
    WHERE number <= 700000
    LIMIT 700001
);

SELECT
    number,
    numbers
FROM numbers_table
ARRAY JOIN numbers AS number
```
Error:
```
Received exception from server (version 23.3.10):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded: would use 4.00 TiB (attempt to allocate chunk of 4398046511208 bytes), maximum: 6.90 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.. (MEMORY_LIMIT_EXCEEDED)
```

> Fiddle: https://fiddle.clickhouse.com/12252ab6-c636-448d-9a06-276b83268036

**Does it reproduce on recent release?**
Yes (according to the fiddle)

**Comment by filimonov** [comment]
So after explosion you will have 700000 rows.
And every row will have 64bit number AND array with 700000 64bit numbers.

That gives us

700000*700000*8 bytes + 700000*8  = 3.92TB

If you are asking about that 0.08 TB - it caused by the fact that memory is allocated with some reserve (usually rounding up).
