### ISSUE TITLE
No version in docker inspect output for clickhouse-server latest

### ISSUE THREAD

**Issue by 4ertus2** [ClickHouse/ClickHouse#54224]
There should be an easy way to check ClickHouse version of inactive docker image with "latest" tag. I.e. I need to check my installation for update.

**Installation type**

docker

**Source of the ClickHouse**

> docker pull clickhouse/clickhouse-server

**Expected result**

I expected to get actual version info for the "latest" tag in Labels or another section

> docker images
REPOSITORY                     TAG       IMAGE ID       CREATED        SIZE
clickhouse/clickhouse-server   latest    a95a98bbf38f   47 hours ago   1.01GB

> docker inspect a95a98bbf38f
...
"Labels": {
"build-url": "https://github.com/ClickHouse/ClickHouse/actions/runs/6051430721",
**"com.clickhouse.build.version": "23.8.1.2992-lts",**
"com.clickhouse.build.githash": "ebc7d9a9f3b40be89e0b3e738b35d394aabeea3e",
"org.opencontainers.image.ref.name": "ubuntu",
"org.opencontainers.image.version": "20.04"
}

**The actual result**

There're revision and build link. No git tags (LTS info) or ClickHouse version.

"Labels": {
"build-url": "https://github.com/ClickHouse/ClickHouse/actions/runs/6051430721",
"com.clickhouse.build.githash": "ebc7d9a9f3b40be89e0b3e738b35d394aabeea3e",
"org.opencontainers.image.ref.name": "ubuntu",
"org.opencontainers.image.version": "20.04"
 }

**Comment by nikmonkov** [comment]
hi! I can implement this
