### ISSUE TITLE
Cluster environment execute SYSTEM RESTORE REPLICA stat.test_tableON CLUSTER 'test cluster' read time out

### ISSUE THREAD

**Issue by Zhangft-M** [ClickHouse/ClickHouse#54252]
Deploy two click house services respectively, and execute commands to report an error read timeout after successful startup
`SYSTEM RESTORE REPLICA stat.test_tableON CLUSTER 'test cluster'`
Everything works fine with data queries

**Comment by cangyin** [comment]
```bash
clickhouse-client --receive_timeout=36000
```
ref https://clickhouse.com/docs/en/operations/settings/settings#connect-timeout-receive-timeout-send-timeout

**Comment by Zhangft-M** [comment]
Docker network issues
