### ISSUE TITLE
How to group by nested columns in tabular format without using array joins

### ISSUE THREAD

**Issue by nshah14285** [ClickHouse/ClickHouse#5426]
How do I perform a group by within nested columns?

I have nested column items.productName and items.amount and I want to get sum of amounts grouped by each item of productName.

Form the result:
`SELECT items.productName AS name, items.amount AS amt FROM test WHERE transactionID IN ('abcxyz','abcxyzz') GROUP BY name`

┌─name─────────┬─amt─────────┐
│ ['product1','product2'] │ [1895,1800]          │
│ ['product2','product1'] │ [1800,1895]          │
└───────────────────────────┘

to

┌─name─────────┬─amt─────────┐
│ product1                   │  3790                      │
│ product2                   │  3600                      │
└───────────────────────────┘

I am able to achieve this using array join
`SELECT items.productName as name, sum(items.amount) as amt from test array join items
where transactionID in ('abcxyz','abcxyzz') group by items.productName`

But array joins are slow so we cannot use them.

So I tried using sumForEach() but I am not sure how to group the result by individual productName.

`SELECT items.productName as name, sumForEach(items.amount) as amt from test where transactionID in ('abcxyz','abcxyzz') group by name`

Thanks,
Nishit

**Comment by blinkov** [comment]
@nshah14285, do you have any further questions?

**Comment by blinkov** [comment]
Feel free to re-open the issue if it is still relevant.

**Comment by ljluestc** [comment]
```
SELECT
  itemName,
  SUM(itemAmount) AS totalAmount
FROM
(
  SELECT
    transactionID,
    arrayJoin(items) AS flattened
  FROM test
  WHERE transactionID IN ('abcxyz', 'abcxyzz')
) AS subquery
GROUP BY
  itemName;

```

**Comment by melvynator** [comment]
Seems to address the problem. Thanks @ljluestc
