### ISSUE TITLE
isZeroOrNull(null) throws an exception

### ISSUE THREAD

**Issue by VanDarkholme7** [ClickHouse/ClickHouse#54295]
clickhouse version 23.8

According to the annotations in `src/Functions/isZeroOrNull.cpp`, `isZeroOrNull` will return 1 if argument is zero or NULL. But, a simple query like `SELECT isZeroOrNull(NULL)` will throw an exception:

`Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: The argument of function isZeroOrNull must have simple numeric type, possibly Nullable: While processing isZeroOrNull(NULL). (BAD_ARGUMENTS)`

Is this the expected behavior? It will correctly return 1 if the query is `SELECT isZeroOrNull(0)` or `SELECT isZeroOrNull(1=2)`.

**Comment by tavplubix** [comment]
No, I don't think it's expected. The problem is that `NULL` literal has special type `Nullable(Nothing)`, and it's not handled here: https://github.com/ClickHouse/ClickHouse/blob/42b0d444da24347befe7038b0f1c95a5507e5966/src/Functions/isZeroOrNull.cpp#L45-L51
