### ISSUE TITLE
free disk space occupied after delete

### ISSUE THREAD

**Issue by MahRokhK** [ClickHouse/ClickHouse#54292]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by MahRokhK** [comment]
I was running out of disk space on clickhouse server so I tried:
DELETE FROM mytable WHERE *exp (*which almost contains 80% of the records)

the records are deleted and no longer shown in the select statements, but the disk usage is not freed up yet after a day. 
running SELECT COUNT (*) FROM mytable shows a hugely different count than number of rows system.parts shows for this table. 

OPTIMIZE mytable FINAL doesn't solved it neigther.

**Comment by tavplubix** [comment]
`ALTER DELETE` and `DELETE` queries (especially `DELETE`) may increase disk usage. `ALTER DELETE` creates a new version of each data part (see `system.parts`), temporarily duplicating data and increasing disk usage up to 2 times in the worst case. `DELETE` queries write "tombstones" for deleted rows without actually removing anything. 

In both cases, old data will be eventually cleaned up in background. In the second case, cleanup is done by merges, and it also may require up to 2x disk space in the worst case (and exactly 2x for OPTIMIZE FINAL).

Consider using ALTER DROP PARTITION if possible, it does not require extra disk space

**Comment by den-crane** [comment]
>OPTIMIZE mytable FINAL doesn't solved it neigther.

Merge is unable to start in case of lack of disk space.

try `OPTIMIZE table mytable FINAL settings optimize_throw_if_noop =1`
