### ISSUE TITLE
UNKNOWN_IDENTIFIER when using materialized column with join and database name

### ISSUE THREAD

**Issue by tahayk** [ClickHouse/ClickHouse#54317]
Hello everyone, 

Probably this issue is similar to [#41964](https://github.com/ClickHouse/ClickHouse/issues/41964) but with a difference about the database, when you specify database name, it doesn't work. (using `v23.8.2.7`)

Following the example created by @den-crane :
```sql
CREATE DATABASE expl;
USE expl;

CREATE TABLE l (y String)Engine Memory;

CREATE TABLE r (d Date, y String,  ty UInt16 MATERIALIZED toYear(d)) Engine Memory;

select * from l L left join r R on  L.y = R.y  where R.ty >= 2019
DB::Exception: Not found column ty in block. (NOT_FOUND_COLUMN_IN_BLOCK)

select * from l  left join r  on  l.y = r.y  where r.ty >= 2019
OK

select * from expl.l  left join expl.r  on  l.y = r.y  where r.ty >= 2019
DB::Exception: Unknown column: ty, there are only columns d, y. (UNKNOWN_IDENTIFIER
```

**Comment by den-crane** [comment]
works with analyzer https://fiddle.clickhouse.com/1056806f-6c05-42fb-81c2-cda55a8f34d5

**Comment by adamshugar** [comment]
Having the same issue on server version 23.10.3 revision 54466
