### ISSUE TITLE
Stress test: 02835_parallel_replicas_over_distributed.sql

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#54314]
https://s3.amazonaws.com/clickhouse-test-reports/0/de4971c71e5a64cb3dae1bc1761a938a71ccdfae/stress_test__asan_.html

The query over distributed table `test2_d` has failed. `test2_d` is defined on cluster `test_cluster_two_shard_three_replicas_localhost`. But the parallel replicas coordinator is getting `default` cluster in `cluster_for_parallel_replicas` setting, despite it should be set to the distributed table cluster on initiator.

https://pastila.nl/?002927cf/dcd83a99b067bda62ed715b21b333513#KP+vmtpyB8qpdTlsGlkiJQ==

**Comment by devcrafter** [comment]
It actually looks that for the second shard, parallel replica mode wasn't set to `Context::ParallelReplicasMode::READ_TASKS` on initiator. And the initiator has established 3 connections instead of 1 to the second shard (see this [code path](https://github.com/ClickHouse/ClickHouse/blob/9bc8c9cc5640fc4230f6f7c1cb4f941e006a85dc/src/Processors/QueryPlan/ReadFromRemote.cpp#L258-L269)). Think so because it should be one error message from the second shard, but there are 3 of them:
```
<Fatal> : Logical error: 'Shard number is greater than shard count: shard_num=2 shard_count=1 cluster=default'
```
Overall, looks weird or I'm missing something

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/de9662f7a4916a46d25dbb03b16d0220603ae1fb/stress_test__msan_.html

**Comment by alexey-milovidov** [comment]
No recent cases.
