### ISSUE TITLE
log messages "Got 0 commands for part"

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#54323]
23.7.5.30

The volume of `clickhouse-server.log` has increased because of these messages:

```
dw.csp_ad_aggr_insights_by_time (ReplicatedMergeTreeQueue): 
   Got 0 commands for part 1183161-201809-201809_0_0_0_2 (part data version 2, part metadata version 9)
```

I see thousands of them for each SELECT query for some tables. 

What do they mean? How to reduce the number of these messages? What do I need to do with the table?

**Comment by tavplubix** [comment]
Introduced in https://github.com/ClickHouse/ClickHouse/pull/50257, fixed in https://github.com/ClickHouse/ClickHouse/pull/54126
