### ISSUE TITLE
Does ClickHouse dev team plan to implement "colocation join"? 

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#54342]
The "colocation join" has been implemented by Doris, https://doris.apache.org/docs/dev/query-acceleration/join-optimization/colocation-join/. 

Shall we ClickHouse going to implement it, too?

**Comment by canhld94** [comment]
Already have. Shards the distributed tables with same join keys, then use `distributed_perfect_shard = 1`.

The missing one is shuffle join.

**Comment by den-crane** [comment]
>distributed_perfect_shard = 1

There is no such setting.
Do you mean `distributed_product_mode=local` ?
