### ISSUE TITLE
how to set a field without any compression codec, just store raw value

### ISSUE THREAD

**Issue by flyly0755** [ClickHouse/ClickHouse#54341]
I want to store a string field without any compression codec. becasue if use default clickhouse compression codec, every time insert data will be slow with this string field(very long length, 000000000001000000000000000...000000010000000... , may be long up to 1000, most char '0', with several char '1'). Seems with this special string, compression will be cost lots of time.
So I want to store this string as raw value, no need to compress it.
And I take a try with sql as below:
```sql
CREATE TABLE stdfndb.compressionTest2
(
    `FILE_ID` UInt32,
    `str1` String CODEC(LZ4),
    `str2` String CODEC(None),
    `str3` String
)
ENGINE = MergeTree
PRIMARY KEY FILE_ID
ORDER BY FILE_ID
SETTINGS index_granularity = 8192
COMMENT 'compression test2';
```
Raise error **DB::Exception: Unknown codec family: None. (UNKNOWN_CODEC) (version 21.12.3.32 (official build))**
Then how to write the correct sql to create table with string field which stored as raw value?

**Comment by den-crane** [comment]
`CODEC(NONE)`

>21.12.3.32

Obsolete version, upgrade to 23.8.

>Seems with this special string, compression will be cost lots of time.

I think it's not the compression. How do you insert your data? I think the issue is in the your client. Check with clickhouse-client or with curl.
