### ISSUE TITLE
How can I enable query_log again

### ISSUE THREAD

**Issue by chihuodexiatian** [ClickHouse/ClickHouse#54344]
Normally, I don't want to enable query_log, so I commented out the relevant configuration in config.xml. But sometimes I need query_log, so I removed the comments and restarted ClickHouse. However, I found that there is no query_log in the system. How can I enable query_log again?

**Comment by SaltTan** [comment]
There is an easier way to enable/disable logging of queries.
It does not require a restart.
```
$ cat /etc/clickhouse-server/users.d/log_queries.xml
<clickhouse>
    <profiles>
        <default>
            <log_queries>1</log_queries>
        </default>
    </profiles>
</clickhouse>
```
