### ISSUE TITLE
High cpu on ENGINE = NATS

### ISSUE THREAD

**Issue by vahpetr** [ClickHouse/ClickHouse#54353]
When i subscribe in turn in Clickhouse NATS without load, it constantly consumes 100% of the processor.

**How to reproduce**
I am preparing an example project: https://github.com/vahpetr/clickhouse-nats-high-cpu-usage-example

**Expected performance**
I expectation zero cpu consumption.
I dont known how it work in older ClickHouse releases.
On Debian 11 i have some equal problem.

**Additional context**
My system MacBook Pro Apple M1 Max Ventura 13.3.1 (a) (22E772610a)
Docker version 24.0.2-rd, build e63f5fa
Docker Compose version 2.20.2

And

Hatznerm machine CX11(1vCPU, 2RAM):
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
Docker version 24.0.5, build ced0996
Docker Compose version v2.20.2

**Comment by den-crane** [comment]
duplicate
* https://github.com/ClickHouse/ClickHouse/issues/41432

**Comment by bigger-boss** [comment]
> clickhouse/clickhouse-server:23.8.1.2992-alpine
In my server , this problem still in there
why
my clickhouse-server version is 23.10.2.13 (official build).

**Comment by vahpetr** [comment]
hi. my fix was reverted the same way it created other problems
see https://github.com/ClickHouse/ClickHouse/pull/54399#issuecomment-1734696928

**Comment by lesha888** [comment]
This problem is not fixed yet. Verified for 23.10.5.20

**Comment by qgab-flowdesk** [comment]
Any update on this issue?
