### ISSUE TITLE
Custom HTTP handlers with prepared queries

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5436]
Allow to configure handlers (identified by path in URL) for prepared queries.

Both SELECT and INSERT queries should be supported.
SELECT query can be parametrized (see #5331).

Example:

Instead of `http://localhost:8123/?query=INSERT%20INTO%20table%20...` 
the user might want to send data to `http://localhost:8123/my_custom_handler/`

This will allow more easy integration with third-party tools.

**Comment by zhang2014** [comment]
@alexey-milovidov 

We also have similar requirements. The following is my discussion with @TCeason , If you think it is ok, maybe we can try to complete this feature : )

First configure the following in the configuration file:
``` xml
<CustomHttpURLs>
    <CustomHttpURL>
        <URL>xxx/{database_name}/{table_name}<URL>
        <QUERY>SELECT column_name FROM `${database_name}`.`${table_name}` WHERE index_column_name = {id:UInt8}</QUERY>
    </CustomHttpURL>
</CustomHttpURLs>
```

Next, the following two requests are equivalent:
- `http://localhost:8123/xxx/default/table_name?id=1`
- `http://localhost:8123?query=SELECT column_name FROM `default`.`table_name` WHERE index_column_name = 1`

**Comment by alexey-milovidov** [comment]
@zhang2014 

Sorry, I've missed your reply.

It's Ok, but I doubt about substitutions for database and table. It will be inconsistent with existing query parameters, let's postpone them.

**Comment by zhang2014** [comment]
OK, I haven't looked at this part of the code on query parameters, will it support identifier type parameters in the future?

**Comment by alexey-milovidov** [comment]
Probably we can implement it as `{name:Identifier}`.
`Identifier` will be processed as a special case and generate ASTIdentifier instead of ASTLiteral.

**Comment by zhang2014** [comment]
Ok, I will start this task after I finish my [json-typed](https://github.com/zhang2014/ClickHouse/tree/feature/json_data_type) work(which takes about a week or two).

**Comment by alexey-milovidov** [comment]
@ValBaturin will do this task.

**Comment by zhang2014** [comment]
actually we've started this task and we're almost done. 😅

**Comment by alexey-milovidov** [comment]
It's Ok if you finish this task and @ValBaturin will help with code review.
