### ISSUE TITLE
toColumnName function

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#54387]
**Use case**

```
SELECT arrayJoin([* APPLY toColumnName]) FROM ...
```

**Comment by alexey-milovidov** [comment]
Highly questionable because functions should not know about column names.

**Comment by amosbird** [comment]
Instead of function, it's better to implement a new type of column transformer which turns columns into names of constant strings.

**Comment by amosbird** [comment]
If https://github.com/ClickHouse/ClickHouse/pull/54881 gets merged, you can do the following:

```
SELECT arrayJoin(tupleNames(namedTuple(*))) FROM ...
```
