### ISSUE TITLE
Support for `async_insert` for prepared blocks sent over the native protocol.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#54381]
**Use case**

Many clients are concurrently sending data using Distributed tables.

**Describe the solution you'd like**

Deserialize blocks as usual, put them in the queue for async inserts, and squash them.
This is slightly different from how async inserts operate, but in fact, even simpler (no parsing).

**Comment by CurtizJ** [comment]
Do we want to support `INSERT SELECT`?

**Comment by alexey-milovidov** [comment]
> Do we want to support INSERT SELECT?

It's unnecessary - if it has any additional complexity, it is to skip.
