### ISSUE TITLE
Enable to use all compression codecs independently including preparation ones

### ISSUE THREAD

**Issue by tomershafir** [ClickHouse/ClickHouse#54386]
Let users flexibility to use compression codecs independently including preparation ones, giving them the option in this aspect to configure the compression tradeoff between compression ratio and resource overhead themself by needs. For example, a theoretical application where delta encoding alone is good enough and further dictionary coding overhead is not wanted. I can help contribute maybe if you think its useful.

**Comment by UnamedRus** [comment]
>  For example, a theoretical application where delta encoding alone is good enough

Can you explain in a bit more detail what do you mean?
For example some syntax example

**Comment by tomershafir** [comment]
for example, allow use `CODEC(Delta)` alone rather than `CODEC(Delta, LZ4)`:

```
CREATE TABLE example
(
    autonum UInt64 CODEC(Delta),
    ...
)
ENGINE = <Engine>
...
```

**Comment by UnamedRus** [comment]
It already works

```
SET allow_suspicious_codecs = 1

CREATE TABLE example
(
    `autonum` UInt64 CODEC(Delta)
)
ENGINE = MergeTree
ORDER BY autonum

Query id: abf0cdd4-b7ce-4672-85d1-2490bfc6d46f

Ok.

0 rows in set. Elapsed: 0.178 sec.
```

**Comment by tomershafir** [comment]
sorry :( the [docs](https://clickhouse.com/docs/en/sql-reference/statements/create/table#delta) said otherwise

**Comment by tomershafir** [comment]
maybe mention `allow_suspicious_codecs` there
