### ISSUE TITLE
Secure malloc function to securely allocate memory area to hold password, key, etc... 

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#54383]
Impressed by recent MS key breach: https://msrc.microsoft.com/blog/2023/09/results-of-major-technical-investigations-for-storm-0558-key-acquisition/

In short: a system program cashed, and it generated a core dump that contains customer keys. An actor could access the debug environment, thus could examine the core dump and able to retrieve the keys.

Some ideas about a secure malloc:
- In a relatively simple form, a malloc call followed by a MADV_DONTDUMP
- More complex form: a dedicated "secure" arena for secure malloc
- Research papers, e.g. https://www.usenix.org/legacy/publications/library/proceedings/sec03/tech/full_papers/broadwell/broadwell_html/node8.html

**Comment by canhld94** [comment]
> If an actor can access the debug env or the server's disk with core dumps, then you have already lost.

Yes, this kind of attack is unlikely to happen often, but it can happen. For example:

- In many organization, the coredump will not be kept in prod but move to a staging env, or upload to bug-report system (or even worse, developer download them to personal dev machine) for debugging. Any developer with debugging permission now can access the coredump information.
- SaaS product: I provide CH service for user, a crash happens, then the user may let my organization access the core file to debug. A malicious developer now can potentially try to get user secret information in the core file.

**Comment by santrancisco** [comment]
I think we can agree secure heap can only make things more secure, not worse if we have sensitive data we want to protect.. ontop of my head it could be something like the inter-server password, maybe the running query string itself (which may contains external system credentials). 

However, To @tavplubix 's point above, you need to be in position to access the core dump to retrieve these data. Note that ClickHouse is a high performance database so it:
 - generates large coredump file (of course depends on the load at time)
 - contains parts of data in the tables loaded in memory 

For that reason I think the general practice for everyone who deal with ClickHouse coredump is to take extra precautions and only trusted party should handle them. 

If our app is used for sensitive operations like signing (eg Vault, openssl) or protecting credentials(lastpass,  1password, etc) It is no doubt that we must have secure malloc...  mlock+MADV_DONTDUMP all the things! But for ClickHouse I dont think it make sense to secure malloc everything as we need enough information to reproduce crashes and with how often ClickHouse access memory, I would hope GC does a good job at clearing mem. As such i think this is "nice to have" feature for now? 🤔
