### ISSUE TITLE
The tests/ocnfig/config.d/disks.xml does not exist

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#54396]
https://github.com/ClickHouse/ClickHouse/blame/ce8e72e464d85107d0aebfd5cdea0da0276f9648/tests/config/install.sh#L24

The .xml file 'tests/ocnfig/config.d/disks.xml' does not exist and the install.sh script will create an wrong symbolic link.

**Comment by alexey-milovidov** [comment]
You have a typo: `ocnfig` -> `config`

**Comment by alexey-milovidov** [comment]
I see - there is no `disk.xml`. I will remove this line.

**Comment by Alex-Cheng** [comment]
> You have a typo: `ocnfig` -> `config`

Sorry, I made a mistake.
