### ISSUE TITLE
MaterializeMySQL engine Failed to create the library and is no longer supported by the engine?

### ISSUE THREAD

**Issue by Pupti** [ClickHouse/ClickHouse#54398]
**Describe the unexpected behaviour**

I manage several clickouse clusters, deployed on the k8s cluster via operator, and one of the clusters failed to create the MaterializeMySQL engine database,There are six shards on this cluster

The cluster version is 22.6.3.35

`CREATE DATABASE test ENGINE = MaterializeMySQL('xxx:3306', 'xxx', 'xxx', 'xxx')`

There are the following errors

> Code: 501. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create MySQL database, because Code: 48. DB::Exception: The MaterializedMySQL database engine no longer supports Ordinary databases. To re-create the database, delete the old one by executing "rm -rf /var/lib/clickhouse/metadata/xxx/{,.sql}", then re-create the database with the following query: CREATE DATABASE xxx ENGINE = MaterializeMySQL('xxx:3306', 'xxx', 'xxx', 'xxx'). (NOT_IMPLEMENTED),. (CANNOT_CREATE_DATABASE)

The stack error is like this

> 2023.09.07 18:49:39.380624 [ 808 ] {dc84534b-3e66-4d00-b7de-d172135b41f3} <Error> executeQuery: Code: 501. DB::Exception: Cannot create MySQL database, because Code: 48. DB::Exception: The MaterializedMySQL database engine no longer supports Ordinary databases. To re-create the database, delete the old one by executing "rm -rf /var/lib/clickhouse/metadata/xxx/{,.sql}", then re-create the database with the following query: CREATE DATABASE xxx ENGINE = MaterializeMySQL('xxx:3306', 'xxx', 'xxx', 'xxx'). (NOT_IMPLEMENTED), Stack trace (when copying this message, always include the lines below):

> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb8a20fa in /usr/bin/clickhouse

> 2. DB::DatabaseFactory::getImpl(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) @ 0x161cdf00 in /usr/bin/clickhouse
> 3. DB::DatabaseFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) @ 0x161ca1c8 in /usr/bin/clickhouse
> 4. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0x161ae0da in /usr/bin/clickhouse
> 5. DB::InterpreterCreateQuery::execute() @ 0x161c6ab3 in /usr/bin/clickhouse
> 6. ? @ 0x16562276 in /usr/bin/clickhouse
> 7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1655fa95 in /usr/bin/clickhouse
> 8. DB::TCPHandler::runImpl() @ 0x171424fa in /usr/bin/clickhouse
> 9. DB::TCPHandler::run() @ 0x17154ab9 in /usr/bin/clickhouse
> 10. Poco::Net::TCPServerConnection::start() @ 0x19dbd2d3 in /usr/bin/clickhouse
> 11. Poco::Net::TCPServerDispatcher::run() @ 0x19dbe651 in /usr/bin/clickhouse
> 12. Poco::PooledThread::run() @ 0x19f6f91b in /usr/bin/clickhouse
> 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x19f6d020 in /usr/bin/clickhouse
> 14. ? @ 0x7f4076765609 in ?
> 15. __clone @ 0x7f407668a133 in ?
>  (version 22.6.3.35 (official build)). (CANNOT_CREATE_DATABASE) (version 22.6.3.35 (official build)) (from 127.0.0.1:58088) (in query: CREATE DATABASE xxx ENGINE = MaterializeMySQL('xxx:3306', 'xxx', 'xxx', 'xxx')), Stack trace (when copying this message, always include the lines below):
> 1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb8a20fa in /usr/bin/clickhouse
> 2. DB::DatabaseFactory::getImpl(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) @ 0x161cf06e in /usr/bin/clickhouse
> 3. DB::DatabaseFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context const>) @ 0x161ca1c8 in /usr/bin/clickhouse
> 4. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0x161ae0da in /usr/bin/clickhouse
> 5. DB::InterpreterCreateQuery::execute() @ 0x161c6ab3 in /usr/bin/clickhouse
> 6. ? @ 0x16562276 in /usr/bin/clickhouse
> 7. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x1655fa95 in /usr/bin/clickhouse
> 8. DB::TCPHandler::runImpl() @ 0x171424fa in /usr/bin/clickhouse
> 9. DB::TCPHandler::run() @ 0x17154ab9 in /usr/bin/clickhouse
> 10. Poco::Net::TCPServerConnection::start() @ 0x19dbd2d3 in /usr/bin/clickhouse
> 11. Poco::Net::TCPServerDispatcher::run() @ 0x19dbe651 in /usr/bin/clickhouse
> 12. Poco::PooledThread::run() @ 0x19f6f91b in /usr/bin/clickhouse
> 13. Poco::ThreadImpl::runnableEntry(void*) @ 0x19f6d020 in /usr/bin/clickhouse
> 14. ? @ 0x7f4076765609 in ?
> 15. __clone @ 0x7f407668a133 in ?

The weird thing is, when I perform
`CREATE DATABASE xxx on cluster 'cluster' ENGINE = MaterializeMySQL('xxx:3306', 'xxx', 'xxx', 'xxx')
`
It will execute successfully on individual machines and sync to the table data I want

What is this problem causing, please help me

**Comment by tavplubix** [comment]
> version is 22.6.3.35

Version 22.6 is obsolete. We do not support it anymore. You should upgrade.

Also, see the exception message:

>  The MaterializedMySQL database engine no longer supports Ordinary databases. To re-create the database, delete the old one by executing "rm -rf /var/lib/clickhouse/metadata/xxx/{,.sql}", then re-create the database with the following query: CREATE DATABASE xxx ENGINE = MaterializeMySQL('xxx:3306', 'xxx', 'xxx', 'xxx')
