### ISSUE TITLE
Method createColumn() is not implemented for data type Function (23.3 backward incompatibility)

### ISSUE THREAD

**Issue by bvt123** [ClickHouse/ClickHouse#54407]
Using array functions in JOIN ON clause raises an exception for version 23.3

```
select *
from (select [1,2,3] as arr) as t1
JOIN (select 1 as id) as t2
ON arrayMap(a -> a, t1.arr)[1] = t2.id
```

works fine at 22.8 and 23.8, but not for 23.3

https://fiddle.clickhouse.com/d644730b-6191-4efd-bc3e-8464d4d39917

```
Received exception from server (version 23.3.13):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Method createColumn() is not implemented for data type Function(UInt8 -> UInt8). (NOT_IMPLEMENTED)
```

related to https://github.com/ClickHouse/ClickHouse/pull/48998

**Comment by tavplubix** [comment]
@vdimir, should we backport https://github.com/ClickHouse/ClickHouse/pull/48998?

**Comment by vdimir** [comment]
> should we backport https://github.com/ClickHouse/ClickHouse/pull/48998?

Yes, let's do for 23.3, I've set label to that PR
