### ISSUE TITLE
[CH] Optimization #2410 takes large memory consumption

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#54404]
(you don't have to strictly follow this form)

**Describe the situation**

Optimization  #2410 takes large memory consumption. As show by follow, we have a block with 788480 rows, it will generate about 10g intermediate datas.
```
DecodeJSONStringFunction: xxx memory usage: 930.88 MiB - 10.46 GiB. rows:788480, column bytes:264.00 MiB
```

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to slow performance

**Expected performance**
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?

**Additional context**

**Comment by nickitat** [comment]
are you sure it is actually 2410?
