### ISSUE TITLE
Projection issue Block structure mismatch in AggregatingStep stream

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#54406]
worked with 22.8: https://fiddle.clickhouse.com/bba44076-1961-4356-b59c-df7e26362245
fails with 23.3: https://fiddle.clickhouse.com/731c266b-df63-437e-ac64-05a36422ad36

```sql
CREATE TABLE r (
     x String,
     a LowCardinality(String),
     q AggregateFunction(quantilesTiming(0.5, 0.95, 0.99), Int64),
     s Int64,
     PROJECTION p 
         (SELECT a, quantilesTimingMerge(0.5, 0.95, 0.99)(q), sum(s) GROUP BY a)
) Engine=SummingMergeTree order by (x,   a);

insert into r 
select number%100 x,
       'x' a, 
       quantilesTimingState(0.5, 0.95, 0.99)(number::Int64) q, 
       sum(1) s
from numbers(1000)
group by x,a;

SELECT 
       ifNotFinite(quantilesTimingMerge(0.95)(q)[1],0) as d1, 
       ifNotFinite(quantilesTimingMerge(0.99)(q)[1],0) as d2,
       ifNotFinite(quantilesTimingMerge(0.50)(q)[1],0) as d3,
       sum(s)
FROM cluster('test_cluster_two_shards', default, r)
WHERE a = 'x' 
settings prefer_localhost_replica=0
format PrettyCompact;


DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Block structure mismatch in AggregatingStep stream: different types:
quantilesTimingMerge(0.99)(q) 
```

WA: disable projection (`allow_experimental_projection_optimization=0`)
https://fiddle.clickhouse.com/89156fe6-169d-444b-a8ab-4c07781d7d11

**Comment by den-crane** [comment]
Actually quantilesTimingMerge just makes projection unusable by the select, it's not a workaround.
It's a bug related to projections.

**Comment by den-crane** [comment]
cc @amosbird

**Comment by amosbird** [comment]
Works with `query_plan_optimize_projection = 0`. Will investigate in the weekend.

**Comment by den-crane** [comment]
it did not use projection with 22.8

**Comment by den-crane** [comment]
interesting that this is works and can be used as WA https://fiddle.clickhouse.com/c7211ac0-9b1a-460f-b016-76e923f51543

**Comment by den-crane** [comment]
I would backport it at least into 23.8.
People found this issue during testing 23.3.
