### ISSUE TITLE
Insert queries consistently oscillates between high and low latency

### ISSUE THREAD

**Issue by MaheshGPai** [ClickHouse/ClickHouse#54419]
**Describe the situation**
We have an ingestion service which ingests data into clickhouse cluster (12 shards and no replication), using async inserts. We batch around **100K rows in each insert**. Below are the settings used by the java client:
- _async_insert=1_
- _wait_for_async_insert=0_
- _async_insert_max_data_size=10000000_
- _async_insert_busy_timeout_ms=1000_

We see that periodically the insert query average latency increases from **~1.5s to ~8s**. Below is the trend of the query latency and the number of rows inserted. We see the latency increase even though there is no change in the insertion rate or pattern

<img width="863" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/14892092/41159f4a-7ab1-46a7-906c-ceda9c133614">
The same trend is seen throughout irrespective of the load. We do not see any correlating increase in CPU or Memory or any other parameters. Below is the memory usage trend for the same time line
<img width="878" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/14892092/b35863f9-cc19-4d50-9e2e-29f963391e42">

The table is partitioned as `PARTITION BY toStartOfHour(RecordTimestamp)`. So inserts would be occurring within the same partition and there will not be too many partitions created

I ran a ProfileEvents comparision from query_log on the queries that had latency of 1s and 7s and below is the output
<img width="1109" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/14892092/fbef9687-6354-4b1b-a0d3-138002ce51f7">

Can you please help is understanding the behaviour and what can be done to fix this? I'm using the latest version of Clickhouse (**v23.8.1**)

**How to reproduce**
* Run a consistent load of around 700K/s row insertion

**Expected performance**
The query performance should be consistent and should not oscillate like currently seen.

**Additional context**
Note that there is no other activity being performed on the cluster apart from the insertion load.

**Comment by den-crane** [comment]
What is insert latency?

Do you say that you insert a single row using async insert and from the client perspective insert lasts >1.5 sec even thought `async_insert_busy_timeout_ms=1000` ?

**Comment by den-crane** [comment]
>We batch around 100K rows in each insert. 

if you insert 100K rows in each insert, you don't need async_insert, or I misunderstand something.

**Comment by MaheshGPai** [comment]
We are currently creating a batch of 100K rows and then performing an insert. This batch insertion takes 1.5 seconds normally. But periodically it increases a lot. Below is a pseudo code

```
try (ClickHouseClient client = ClickHouseClient.newInstance(server.getProtocol())) {
    String queryId = UUID.randomUUID().toString();
    ClickHouseRequest.Mutation request = client.connect(server).write().table(CLICKHOUSE_TRACE_TABLE, queryId)
            .format(ClickHouseFormat.RowBinary);
    ;
    ;
    // back-pressuring is not supported, you can adjust the first two arguments
    try (ClickHousePipedOutputStream stream = ClickHouseDataStreamFactory.getInstance()
            .createPipedOutputStream(config, (Runnable) null)) {
        // Loop and write the rows
        ;
        ClickHouseResponse response = future.get()
        ;
    }
}
```

**Comment by MaheshGPai** [comment]
Just to rule out async vs sync.  I tested by performing sync inserts using the batch and I see the same pattern in insert query latency.

**Comment by den-crane** [comment]
I would compare this graph with graph of merged rows.

**Comment by MaheshGPai** [comment]
The issue seemed to dissipate away once I added a set of `chproxy` pods in front of the clickhouse cluster. So it seems to be a load balancing issue, but its not very obvious from the metrics. Is there any recommendation for the best way to loadbalance the ingestion load across shards? We are inserting into Mergetable and using distributed table only for queries.

**Comment by den-crane** [comment]
>Is there any recommendation for the best way to loadbalance the ingestion load across shards?

Load equally to all nodes in the cluster in parallel.
