### ISSUE TITLE
clickhouse-client and clickhouse-local behave differently with multiquery statements

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#54428]
Inconsistent behavior (but not a big deal), reported in https://github.com/ClickHouse/ClickHouse/pull/50357#discussion_r1211260100:

```base
/.clickhouse-client  -q "select 1; select 2"
-- Code: 62. DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 9 (end of query): ; select 2. . (SYNTAX_ERROR)

./clickhouse-local   -q "select 1; select 2;"
1
2
```

`clickhouse-local` understands `--multiquery`, so this might be a (minor) bug and not by design. Otherwise, we can just document the behavior.

**Comment by lingtaolf** [comment]
All clickhouse-client and clickhouse-local should throw exception in  the above example ? Because there is no `--multiquery` ?

**Comment by rschu1ze** [comment]
Correct, both should throw an exception.
