### ISSUE TITLE
Orphaned objects in S3 with zero copy replication enabled

### ISSUE THREAD

**Issue by aalexfvk** [ClickHouse/ClickHouse#54426]
We are using zero-copy replication on our cluster. This feature is experimental. We are working to increase its stability.

Periodically, orphaned objects in S3 appear. In this cases, log contains the lines below:
```
2023.09.06 17:42:27.419026 [ 4101454 ] {cbccfeeb-06b1-413a-bf73-cd07d020256a} <Trace> StorageReplicatedMergeTree: Remove zookeeper lock /clickhouse/zero_copy/zero_copy_s3/1966f1d4-6589-4bb0-b19a-f1a631f70b37/20230813_61963_70913_87/cloud_storage_mdbmas2jjul3ct5q39sm_shard4_qyu_gyluvqxhtexdnacroavwnnuxlarly/sas-molt6q9wh794eo68.db.yandex.net for part 20230813_61963_70913_87
2023.09.06 17:42:27.425956 [ 4101454 ] {cbccfeeb-06b1-413a-bf73-cd07d020256a} <Trace> StorageReplicatedMergeTree: No more children left for for /clickhouse/zero_copy/zero_copy_s3/1966f1d4-6589-4bb0-b19a-f1a631f70b37/20230813_61963_70913_87/cloud_storage_mdbmas2jjul3ct5q39sm_shard4_qyu_gyluvqxhtexdnacroavwnnuxlarly, will try to remove the whole node
2023.09.06 17:42:27.429585 [ 4101454 ] {cbccfeeb-06b1-413a-bf73-cd07d020256a} <Trace> StorageReplicatedMergeTree: Node with parent zookeeper lock /clickhouse/zero_copy/zero_copy_s3/1966f1d4-6589-4bb0-b19a-f1a631f70b37/20230813_61963_70913_87/cloud_storage_mdbmas2jjul3ct5q39sm_shard4_qyu_gyluvqxhtexdnacroavwnnuxlarly for part 20230813_61963_70913_87 with id cloud_storage_mdbmas2jjul3ct5q39sm_shard4_qyu_gyluvqxhtexdnacroavwnnuxlarly doesn't exist
2023.09.06 17:42:27.436524 [ 4101454 ] {cbccfeeb-06b1-413a-bf73-cd07d020256a} <Warning> StorageReplicatedMergeTree: Node with parent zookeeper lock /clickhouse/zero_copy/zero_copy_s3/1966f1d4-6589-4bb0-b19a-f1a631f70b37/20230813_61963_70913_87/cloud_storage_mdbmas2jjul3ct5q39sm_shard4_qyu_gyluvqxhtexdnacroavwnnuxlarly for part 20230813_61963_70913_87 doesn't exist (part was unlocked before), refuse to remove blobs
2023.09.06 17:42:27.442431 [ 4101454 ] {cbccfeeb-06b1-413a-bf73-cd07d020256a} <Debug> Unfreezer: Unfreezed part by path /var/lib/clickhouse/disks/object_storage/shadow/mdb26pcbmv6rlilc93dv/data/mdb/mysql_slow_part/20230813_61963_70913_87/, keep shared data: true
```
We use 23.3.9 revision 54462 version.
I have not yet been able to reproduce this problem.

What are cases that can lead to the absent of parent zero-copy lock node and this early return protects us from ? How up-to-date is this code:
https://github.com/ClickHouse/ClickHouse/blob/cf336747384f94a15ec8110d805e6393ca334c44/src/Storages/StorageReplicatedMergeTree.cpp#L9205-L9209
Taking into account this check above on the code (`but we don't have mutation parent, can remove blobs`) :
https://github.com/ClickHouse/ClickHouse/blob/cf336747384f94a15ec8110d805e6393ca334c44/src/Storages/StorageReplicatedMergeTree.cpp#L9134-L9142

**Comment by tavplubix** [comment]
1. Zero-copy replication does not work correctly with FREEZE/UNFREEZE queries. 
2. Zero-copy replication is expected to leave some garbage on S3 that will never be removed. Although the number of orphaned blobs is not expected to be high (comparing to the total number of blobs), non-trivial configuration, unusual workloads, or the use of some features like FREEZE may significantly increase that number
