### ISSUE TITLE
kafka engine is not  correctly working

### ISSUE THREAD

**Issue by rnrl1215** [ClickHouse/ClickHouse#54434]
spec
1. docker
2. clickhouse instance 3 with 1 cluster
3. each instance has clickhouse-keeper
4. cliclkhouse version 23.7.4.5

docker instances 
![test](https://github.com/ClickHouse/ClickHouse/assets/33127270/7e2e28c5-0292-4d60-9bf2-677d7d7f0c15)

i created kafka engine table and MATERIALIZED VIEW

i got error message
meessage: 

2023.09.08 06:24:41.103181 [ 434 ] {} <Error> StorageKafka (consumer_user_log_action): [rdk:FAIL] [thrd:GroupCoordinator]: GroupCoordinator: localhost:29092: Connect to ipv4#127.0.0.1:29092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
2023.09.08 06:24:41.103272 [ 197 ] {} <Error> StorageKafka (consumer_user_log_action): [rdk:ERROR] [thrd:app]: ClickHouse-9963e06ca074-walk_1-consumer_user_log_action#consumer-3: GroupCoordinator: localhost:29092: Connect to ipv4#127.0.0.1:29092 failed: Connection refused (after 0ms in state CONNECT, 4 identical error(s) suppressed)
2023.09.08 06:24:55.495165 [ 103 ] {} <Warning> StorageKafka (consumer_user_log_action): Can't get assignment. Will keep trying.

i created kafka engine table 

`CREATE TABLE test.consumer_table
(
    `regdt_dttm` DateTime COMMENT 'event time'
)
ENGINE =  Kafka('192.168.3.23:29092', 'test', 'group-1')
              SETTINGS kafka_format = 'JSONEachRow';
`

i specified address that is 192.168.3.23:29092' 
but clickhouse try connecting localhost:29092

why? 
i have no idea

**Comment by den-crane** [comment]
>i specified address that is 192.168.3.23:29092'
>but clickhouse try connecting localhost:29092

It's a kafka feature. `advertised.listeners`. Kafka Broker GroupCoordinator forwards clients to the real brokers who holds this topics, using `advertised.listeners`.
https://www.google.com/search?client=firefox-b-d&q=kafka+advertised.listeners
