### ISSUE TITLE
Can S3 Disk support settings that in S3 Table Engine intro doc but not in S3 Disk intro doc?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#54437]
I refer to [this](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree?#table_engine-mergetree-s3), and I use MergeTree with local disk and s3 disk.

Can I use these settings, refer to [this](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#settings):
```text
s3_max_redirects
s3_max_single_part_upload_size
s3_min_upload_part_size
s3_upload_part_size_multiply_factor
s3_upload_part_size_multiply_parts_count_threshold
s3_max_inflight_parts_for_one_file
```

ClickHouse version is 23.6

Thank you very much!

**Comment by melvynator** [comment]
Are you using TTL policies or are you using S3 for different tables? In all cases that should be working.

**Comment by LGDHuaOPER** [comment]
> Are you using TTL policies or are you using S3 for different tables? In all cases that should be working.

Yes, I use TTL policies such as `TTL toDateTime(`local_time`) + INTERVAL 4 WEEK TO DISK 's3', toDateTime(`local_time`) + INTERVAL 2 MONTH DELETE`, and I use S3 for different tables.

So, what do you mean, are these configurations such as `s3_min_upload_part_size` supported by S3 DISK?

**Comment by alexey-milovidov** [comment]
@LGDHuaOPER, yes, all these settings can be specified in the disk configuration, like here:

```
$ sudo cat /etc/clickhouse-server/config.d/clicklakes.yaml
storage_configuration:
    disks:
        example_disk:
            type: s3_plain_rewritable
            s3_strict_upload_part_size: 67108864
            endpoint: 'https://....r2.cloudflarestorage.com/example/'
            region: 'weur'
```
