### ISSUE TITLE
log will endlessly loop and print errors until the storage space is exhausted.

### ISSUE THREAD

**Issue by kidswang** [ClickHouse/ClickHouse#54433]
{"log":"\n","stream":"stderr","time":"2023-09-08T01:17:40.862793991Z"}
{"log":"0. Poco::FileException::FileException(String const\u0026, int) @ 0x17962f69 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862795706Z"}
{"log":"1. Poco::RotateBySizeStrategy::mustRotate(Poco::LogFile*) @ 0x179b10bb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862797717Z"}
{"log":"2. Poco::FileChannel::log(Poco::Message const\u0026) @ 0x1796ba6b in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862799627Z"}
{"log":"3. DB::OwnFormattingChannel::logExtended(DB::ExtendedLogMessage const\u0026) @ 0xe3f1227 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862801523Z"}
{"log":"4. DB::OwnSplitChannel::logSplit(Poco::Message const\u0026) @ 0xe3f5d99 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862803401Z"}
{"log":"5. DB::OwnSplitChannel::tryLogSplit(Poco::Message const\u0026) @ 0xe3f5be2 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.86280529Z"}
{"log":"6. DB::OwnSplitChannel::log(Poco::Message const\u0026) @ 0xe3f5948 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862807198Z"}
{"log":"7. DB::MergeTreeDataSelectExecutor::markRangesFromPKRange(std::shared_ptr\u003cDB::IMergeTreeDataPart const\u003e const\u0026, std::shared_ptr\u003cDB::StorageInMemoryMetadata const\u003e const\u0026, DB::KeyCondition const\u0026, DB::Settings const\u0026, Poco::Logger*) @ 0x144f9f08 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862809058Z"}
{"log":"8. ? @ 0x1450e429 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862811468Z"}
{"log":"9. ? @ 0x14518edb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862814969Z"}
{"log":"10. ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::worker(std::__list_iterator\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e, void*\u003e) @ 0xe260ea5 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862816841Z"}
{"log":"11. void std::__function::__policy_invoker\u003cvoid ()\u003e::__call_impl\u003cstd::__function::__default_alloc_func\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e::ThreadFromGlobalPoolImpl\u003cvoid ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::scheduleImpl\u003cvoid\u003e(std::function\u003cvoid ()\u003e, long, std::optional\u003cunsigned long\u003e, bool)::'lambda0'()\u003e(void\u0026\u0026)::'lambda'(), void ()\u003e\u003e(std::__function::__policy_storage const*) @ 0xe263a15 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862819148Z"}
{"log":"12. ThreadPoolImpl\u003cstd::thread\u003e::worker(std::__list_iterator\u003cstd::thread, void*\u003e) @ 0xe25cc73 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862822194Z"}
{"log":"13. ? @ 0xe2628e1 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862824206Z"}
{"log":"14. ? @ 0x7f969c052b43 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862825978Z"}
{"log":"15. __clone @ 0x7f969c0e3bb4 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862827706Z"}
{"log":" (version 23.3.1.2823 (official build))\n","stream":"stderr","time":"2023-09-08T01:17:40.862830157Z"}
{"log":"Cannot add message to the log: Found continuous range in 7 steps\n","stream":"stderr","time":"2023-09-08T01:17:40.86283193Z"}
{"log":"Poco::Exception. Code: 1000, e.code() = 0, File access error: /var/log/clickhouse-server/clickhouse-server.log, Stack trace (when copying this message, always include the lines below):\n","stream":"stderr","time":"2023-09-08T01:17:40.862833762Z"}
{"log":"\n","stream":"stderr","time":"2023-09-08T01:17:40.862835766Z"}
{"log":"0. Poco::FileException::FileException(String const\u0026, int) @ 0x17962f69 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862837419Z"}
{"log":"1. Poco::RotateBySizeStrategy::mustRotate(Poco::LogFile*) @ 0x179b10bb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862839285Z"}
{"log":"2. Poco::FileChannel::log(Poco::Message const\u0026) @ 0x1796ba6b in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.8628411Z"}
{"log":"3. DB::OwnFormattingChannel::logExtended(DB::ExtendedLogMessage const\u0026) @ 0xe3f1227 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862842999Z"}
{"log":"4. DB::OwnSplitChannel::logSplit(Poco::Message const\u0026) @ 0xe3f5d99 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862844901Z"}
{"log":"5. DB::OwnSplitChannel::tryLogSplit(Poco::Message const\u0026) @ 0xe3f5be2 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862846752Z"}
{"log":"6. DB::OwnSplitChannel::log(Poco::Message const\u0026) @ 0xe3f5948 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862848633Z"}
{"log":"7. DB::MergeTreeDataSelectExecutor::markRangesFromPKRange(std::shared_ptr\u003cDB::IMergeTreeDataPart const\u003e const\u0026, std::shared_ptr\u003cDB::StorageInMemoryMetadata const\u003e const\u0026, DB::KeyCondition const\u0026, DB::Settings const\u0026, Poco::Logger*) @ 0x144fa541 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862850508Z"}
{"log":"8. ? @ 0x1450e429 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862852866Z"}
{"log":"9. ? @ 0x14518edb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862854631Z"}
{"log":"10. ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::worker(std::__list_iterator\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e, void*\u003e) @ 0xe260ea5 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.86285638Z"}
{"log":"11. void std::__function::__policy_invoker\u003cvoid ()\u003e::__call_impl\u003cstd::__function::__default_alloc_func\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e::ThreadFromGlobalPoolImpl\u003cvoid ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::scheduleImpl\u003cvoid\u003e(std::function\u003cvoid ()\u003e, long, std::optional\u003cunsigned long\u003e, bool)::'lambda0'()\u003e(void\u0026\u0026)::'lambda'(), void ()\u003e\u003e(std::__function::__policy_storage const*) @ 0xe263a15 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862860148Z"}
{"log":"12. ThreadPoolImpl\u003cstd::thread\u003e::worker(std::__list_iterator\u003cstd::thread, void*\u003e) @ 0xe25cc73 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862863286Z"}
{"log":"13. ? @ 0xe2628e1 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862865317Z"}
{"log":"14. ? @ 0x7f969c052b43 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862867365Z"}
{"log":"15. __clone @ 0x7f969c0e3bb4 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862869117Z"}
{"log":" (version 23.3.1.2823 (official build))\n","stream":"stderr","time":"2023-09-08T01:17:40.862870902Z"}
{"log":"Cannot add message to the log: Running binary search on index range for part 20230608_944394_944411_4_5275154 (2 marks)\n","stream":"stderr","time":"2023-09-08T01:17:40.86289947Z"}
{"log":"Poco::Exception. Code: 1000, e.code() = 0, File access error: /var/log/clickhouse-server/clickhouse-server.log, Stack trace (when copying this message, always include the lines below):\n","stream":"stderr","time":"2023-09-08T01:17:40.862903222Z"}
{"log":"\n","stream":"stderr","time":"2023-09-08T01:17:40.862905419Z"}
{"log":"0. Poco::FileException::FileException(String const\u0026, int) @ 0x17962f69 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862907169Z"}
{"log":"1. Poco::RotateBySizeStrategy::mustRotate(Poco::LogFile*) @ 0x179b10bb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862909139Z"}
{"log":"2. Poco::FileChannel::log(Poco::Message const\u0026) @ 0x1796ba6b in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862911002Z"}
{"log":"3. DB::OwnFormattingChannel::logExtended(DB::ExtendedLogMessage const\u0026) @ 0xe3f1227 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862912916Z"}
{"log":"4. DB::OwnSplitChannel::logSplit(Poco::Message const\u0026) @ 0xe3f5d99 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862914807Z"}
{"log":"5. DB::OwnSplitChannel::tryLogSplit(Poco::Message const\u0026) @ 0xe3f5be2 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862916705Z"}
{"log":"6. DB::OwnSplitChannel::log(Poco::Message const\u0026) @ 0xe3f5948 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862918599Z"}
{"log":"7. DB::MergeTreeDataSelectExecutor::markRangesFromPKRange(std::shared_ptr\u003cDB::IMergeTreeDataPart const\u003e const\u0026, std::shared_ptr\u003cDB::StorageInMemoryMetadata const\u003e const\u0026, DB::KeyCondition const\u0026, DB::Settings const\u0026, Poco::Logger*) @ 0x144f90d2 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862920523Z"}
{"log":"8. ? @ 0x1450e429 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862922927Z"}
{"log":"9. ? @ 0x14518edb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862924676Z"}
{"log":"10. ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::worker(std::__list_iterator\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e, void*\u003e) @ 0xe260ea5 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862926504Z"}
{"log":"11. void std::__function::__policy_invoker\u003cvoid ()\u003e::__call_impl\u003cstd::__function::__default_alloc_func\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e::ThreadFromGlobalPoolImpl\u003cvoid ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::scheduleImpl\u003cvoid\u003e(std::function\u003cvoid ()\u003e, long, std::optional\u003cunsigned long\u003e, bool)::'lambda0'()\u003e(void\u0026\u0026)::'lambda'(), void ()\u003e\u003e(std::__function::__policy_storage const*) @ 0xe263a15 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862928666Z"}
{"log":"12. ThreadPoolImpl\u003cstd::thread\u003e::worker(std::__list_iterator\u003cstd::thread, void*\u003e) @ 0xe25cc73 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862933754Z"}
{"log":"13. ? @ 0xe2628e1 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862935854Z"}
{"log":"14. ? @ 0x7f969c052b43 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862937811Z"}
{"log":"15. __clone @ 0x7f969c0e3bb4 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862939618Z"}
{"log":" (version 23.3.1.2823 (official build))\n","stream":"stderr","time":"2023-09-08T01:17:40.862941396Z"}
{"log":"Cannot add message to the log: Found (LEFT) boundary mark: 0\n","stream":"stderr","time":"2023-09-08T01:17:40.862951491Z"}
{"log":"Poco::Exception. Code: 1000, e.code() = 0, File access error: /var/log/clickhouse-server/clickhouse-server.log, Stack trace (when copying this message, always include the lines below):\n","stream":"stderr","time":"2023-09-08T01:17:40.862954773Z"}
{"log":"\n","stream":"stderr","time":"2023-09-08T01:17:40.862957118Z"}
{"log":"0. Poco::FileException::FileException(String const\u0026, int) @ 0x17962f69 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862958865Z"}
{"log":"1. Poco::RotateBySizeStrategy::mustRotate(Poco::LogFile*) @ 0x179b10bb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862960811Z"}
{"log":"2. Poco::FileChannel::log(Poco::Message const\u0026) @ 0x1796ba6b in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862962634Z"}
{"log":"3. DB::OwnFormattingChannel::logExtended(DB::ExtendedLogMessage const\u0026) @ 0xe3f1227 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862964527Z"}
{"log":"4. DB::OwnSplitChannel::logSplit(Poco::Message const\u0026) @ 0xe3f5d99 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862966404Z"}
{"log":"5. DB::OwnSplitChannel::tryLogSplit(Poco::Message const\u0026) @ 0xe3f5be2 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862968255Z"}
{"log":"6. DB::OwnSplitChannel::log(Poco::Message const\u0026) @ 0xe3f5948 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862970276Z"}
{"log":"7. DB::MergeTreeDataSelectExecutor::markRangesFromPKRange(std::shared_ptr\u003cDB::IMergeTreeDataPart const\u003e const\u0026, std::shared_ptr\u003cDB::StorageInMemoryMetadata const\u003e const\u0026, DB::KeyCondition const\u0026, DB::Settings const\u0026, Poco::Logger*) @ 0x144f9c19 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862972156Z"}
{"log":"8. ? @ 0x1450e429 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862974532Z"}
{"log":"9. ? @ 0x14518edb in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862976272Z"}
{"log":"10. ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::worker(std::__list_iterator\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e, void*\u003e) @ 0xe260ea5 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862978088Z"}
{"log":"11. void std::__function::__policy_invoker\u003cvoid ()\u003e::__call_impl\u003cstd::__function::__default_alloc_func\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e::ThreadFromGlobalPoolImpl\u003cvoid ThreadPoolImpl\u003cThreadFromGlobalPoolImpl\u003cfalse\u003e\u003e::scheduleImpl\u003cvoid\u003e(std::function\u003cvoid ()\u003e, long, std::optional\u003cunsigned long\u003e, bool)::'lambda0'()\u003e(void\u0026\u0026)::'lambda'(), void ()\u003e\u003e(std::__function::__policy_storage const*) @ 0xe263a15 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862980271Z"}
{"log":"12. ThreadPoolImpl\u003cstd::thread\u003e::worker(std::__list_iterator\u003cstd::thread, void*\u003e) @ 0xe25cc73 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862983297Z"}
{"log":"13. ? @ 0xe2628e1 in /usr/bin/clickhouse\n","stream":"stderr","time":"2023-09-08T01:17:40.862987225Z"}
{"log":"14. ? @ 0x7f969c052b43 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862989075Z"}
{"log":"15. __clone @ 0x7f969c0e3bb4 in ?\n","stream":"stderr","time":"2023-09-08T01:17:40.862990821Z"}
{"log":" (version 23.3.1.2823 (official build))\n","stream":"stderr","time":"2023-09-08T01:17:40.862993233Z"}
{"log":"Cannot add message to the log: Found (RIGHT) boundary mark: 2\n","stream":"stderr","time":"2023-09-08T01:17:40.862994998Z"}
{"log":"Poco::Exception. Code: 1000, e.code() = 0, File access error: /var/log/clickhouse-server/clickhouse-server.log, Stack trace (when copying this message, always include the lines below):\n","stream":"stderr","time":"2023-09-08T01:17:40.86299685Z"}
{"log":"\n","stream":"stderr","time":"2023-09-08T01:17:40.862998907Z"}

**Comment by cangyin** [comment]
> File access error: /var/log/clickhouse-server/clickhouse-server.log

**Comment by den-crane** [comment]
23.3.1.2823 is obsolete.
Upgrade to 23.3.13.6
