### ISSUE TITLE
Add autorelease script with a schedule at most once / X (2? 3?) days to trigger testing/stable builds

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#54440]
Create a workflow for daily execution on working days, that will:

- Search for opened PRs with the label `pr-release` (example in cherry_pick.py)
- Search for existing releases for these branches (I think, the easiest move will be searching for tags)
-  Get commit statuses for all young (from `NOW` to `TAG_CREATION_TIME + X`) commits, and check the workflows for them are finished and statuses a green
- If so, execute `release.py --patch --commit {commit}`

**Comment by alexey-milovidov** [comment]
X = 1 (every day)

**Comment by Felixoid** [comment]
We already have pretty big package repositories, and deploying up to 5 releases daily looks like a stress test to a system.

Once per 3 looks better than 2, and daily releases are a way to bloat up git, docker hub, deb, and rpm repositories. Nobody, especially us, need it to be like that.

**Comment by alexey-milovidov** [comment]
At the same time, not releasing a patch when it is ready - is not good.

**Comment by Felixoid** [comment]
Then we need to consider cleaning up repositories. It's possible to do in many ways, like archiving away inactive release on packages.clickhouse.com

But it's still only one part. Overhead for each release is considerably big. And daily release is something we could do. But it doesn't mean we should.

For example, I'm not sure how it correlates with publishing official docker images. It requires manual reviews. My idea was to make it once a week, so it's a bottleneck. But here I rather speculate yet.

My point, the system is not ready for daily releases on one hand, and my opinion is that they aren't really required.

It's hard to discuss in the issue. What about this Monday's evening sync?

**Comment by Felixoid** [comment]
https://github.com/ClickHouse/ClickHouse/pull/54604
