### ISSUE TITLE
[kafka] increase on memory after upgrade clickhouse from version 23.1 to version 23.8.1.2992

### ISSUE THREAD

**Issue by aol-59** [ClickHouse/ClickHouse#54483]
Describe the unexpected behavior:

After upgrading ClickHouse from version **23.1**. to version **23.8.1.2992**, we have observed a significant increase in memory usage for our queries. The same queries that used to consume **500 MB** amount of memory on the older version are now using **2,27 GB**  amount of memory on the new version.

**Comment by aol-59** [comment]
Is there a recommended solution, or should I revert to the previous version?

**Comment by den-crane** [comment]
Please provide reproducible example

**Comment by aol-59** [comment]
```
create table db.table(
col_1 String,
col_2 Int64,
....
col_40
) Engine = replicatedMergeTree('')
Partition by toYYYYMMDD(TIME)
Primary key col_1
order by (col_1,col_2);

```

```
select * 
from ( 
       select col_1 ,col_2 ,col_3 ,col_4 ,col_5 ,col_6 ,col_7 ,col_8 ,col_9 ,
col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,
col_20,col_21,col_22,col_23,col_24,col_25,col_26,col_27,col_28,col_29

from db.table 
where col_1 in ('value','value','value','value','value' , ... )
and toYYYYMMDD(TIME) between toYYYYMMDD(dataSub(DAY,60 today())) AND toYYYYMMDD(today())
)
where col_20 <= 100
and col_21 <= 100 
and col_22 <= 100 
and col_23 <= 100
and col_24 <= 100
and col_25 <= 100 
and col_26 <= 100
and col_27 <= 100
LIMIT BY col_1 10000;
```



Before Upgrade :

```
select query, memory_usage,
from system.query_log_3
where event_date = today()
and normalized_query_hash = 'query_hash_value'
order by memory_usage desc 
limit 200;
```

- 484.91 MB
- 454.76 MB
- 454.46 MB
- 454.18 MB
- 452.82 MB
- 484.67 MB


After Upgrade : 

```
select query, memory_usage,
from system.query_log
where event_date = today()
and normalized_query_hash = 'query_hash_value'
order by memory_usage desc 
limit 200;
```

- 2.06 GB
- 1.96 GB
- 1.86 GB
- 1.86 GB
- 1.85 GB
- 1.83 GB

![memory_before_upgrade](https://github.com/ClickHouse/ClickHouse/assets/50527487/79760d52-8320-41a8-a723-26289f43a2c6)


![memory_after_upgrade](https://github.com/ClickHouse/ClickHouse/assets/50527487/01a91852-0daa-4508-9e2b-8c743a4cae30)

**Comment by den-crane** [comment]
>toYYYYMMDD(TIME)

type of time?

**Comment by aol-59** [comment]
> > toYYYYMMDD(TIME)
> 
> type of time?

DateTime

**Comment by den-crane** [comment]
>LIMIT BY col_1 10000;

you meant `LIMIT 10000 BY col_1` ?

**Comment by den-crane** [comment]
>  in ('value','value','value','value','value' , ... )

How many items in this list?

**Comment by den-crane** [comment]
I did so far

23.3.8.21
```
clickhouse-client -mn cr.txt
clickhouse-client -mn ins.txt

for i in `seq 1 5000`; do clickhouse-client -mn < sel.txt; done &
for i in `seq 1 5000`; do clickhouse-client -mn < sel.txt; done &
```
memory usage is stable around 1.5GB

[sel.txt](https://github.com/ClickHouse/ClickHouse/files/12580905/sel.txt)
[ins.txt](https://github.com/ClickHouse/ClickHouse/files/12580906/ins.txt)
[cr.txt](https://github.com/ClickHouse/ClickHouse/files/12580907/cr.txt)

**Comment by aol-59** [comment]
> you meant LIMIT 10000 BY col_1 ?

Yes

> How many items in this list?

it could be 1 or 500 it depends 

 

> I did so far
> 23.3.8.21

I'm sorry, I wrote the wrong version number. I meant **23.8.1.2992**, not _23.3_.

today i check the query and the memory usage is still increasing 

> 2.06 GB
1.96 GB
1.86 GB
1.86 GB
1.85 GB
1.83 GB


- 2.08
- 2.07
- 2.07
- 2.02


i used another query in dashboard 

`
select event_time , CurrentMetric_MemoryTracking   
from system.metric_log
 order by event_time desc 
`

![memory_after_upgrade](https://github.com/ClickHouse/ClickHouse/assets/50527487/67d7a59c-21cc-4276-96f7-7c767f7ef353)

**Comment by den-crane** [comment]
>CurrentMetric_MemoryTracking

MemoryTracking is not perfect. Do not look at it. Use CurrentMetric_MemoryResident.

```
SELECT *
FROM system.asynchronous_metrics
WHERE metric ILIKE '%MemoryResident%'

Query id: 4a583e9e-7d39-4394-9359-c1e501c19fb1

┌─metric─────────┬──────value─┬─description─────────────────────────────────────────────────────────┐
│ MemoryResident │ 1124720640 │ The amount of physical memory used by the server process, in bytes. │
└────────────────┴────────────┴─────────────────────────────────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
Can you please share 

```
select name,value from system.settings where changed
```

**Comment by den-crane** [comment]
I've added more data and upgraded my test to 23.8.2.7.
I don't see any issue. Memory usage is stable.

May be the issue is not in the select? But in insert?

**Comment by thomoco** [comment]
Requested by User in Community Slack also, cc'ing @melvynator for PM visibility https://clickhousedb.slack.com/archives/CU478UEQZ/p1694560714491349

**Comment by aol-59** [comment]
Thanks @den-crane  for your support 

> > CurrentMetric_MemoryTracking
> 
> MemoryTracking is not perfect. Do not look at it. Use CurrentMetric_MemoryResident.
> 
> ```
> SELECT *
> FROM system.asynchronous_metrics
> WHERE metric ILIKE '%MemoryResident%'
> 
> Query id: 4a583e9e-7d39-4394-9359-c1e501c19fb1
> 
> ┌─metric─────────┬──────value─┬─description─────────────────────────────────────────────────────────┐
> │ MemoryResident │ 1124720640 │ The amount of physical memory used by the server process, in bytes. │
> └────────────────┴────────────┴─────────────────────────────────────────────────────────────────────┘
> ```
```
SELECT *
FROM system.asynchronous_metrics
WHERE metric ILIKE '%MemoryResident%'


┌─metric─────────┬──────value─┬─description─────────────────────────────────────────────────────────┐
│ MemoryResident │ 27366715392│ The amount of physical memory used by the server process, in bytes. │
└────────────────┴────────────┴─────────────────────────────────────────────────────────────────────┘
```





> Can you please share
> 
> ```
> select name,value from system.settings where changed
> ```
![settings](https://github.com/ClickHouse/ClickHouse/assets/50527487/b2c969f1-d298-4e62-a41e-1e9ed2d0bb5a)

![server_settings](https://github.com/ClickHouse/ClickHouse/assets/50527487/1dd905e9-ebc5-4293-93b2-e047527cfa44)


i changed the query in dashboard to :
`
select event_time , value 
from system.asynchronous_metric_log
where metric ilike '%MemoryResident%'
`


![MemoryResident](https://github.com/ClickHouse/ClickHouse/assets/50527487/ae724e04-5e90-4619-9c24-c604d7fd3075)

As you can see shard 7 is a replica of shard 1 
![after restart](https://github.com/ClickHouse/ClickHouse/assets/50527487/f875f447-6b1f-4558-ac1d-ebcda8dd1928)

**Comment by aol-59** [comment]
> I've added more data and upgraded my test to 23.8.2.7. I don't see any issue. Memory usage is stable.
> 
> May be the issue is not in the select? But in insert?

When I restart ClickHouse, it appears to free up memory. Is there anything that ClickHouse caches?

**Comment by den-crane** [comment]
Do you use the same user for select as you used `select name,value from system.settings where changed` ?

Your server_settings look very suspicious. 
Why did you change them? How many queries do you execute in parallel?

**Comment by den-crane** [comment]
Do you use distributed tables?

**Comment by aol-59** [comment]
> Do you use distributed tables?

No, I don't use it because it crashes after I try to insert data into it. Instead, I insert the data directly into the local table

> Do you use the same user for select as you used `select name,value from system.settings where changed` ?
> 
> Your server_settings look very suspicious. Why did you change them? How many queries do you execute in parallel?

Yes, i did 
There is no result.


> How many queries do you execute in parallel?

I changed it some time ago because I encountered a "max concurrent query" exception. I'm unsure how to calculate the number of parallel queries

**Comment by den-crane** [comment]
>shard 7 is a replica of shard 1
>No, I don't use it because it crashes after I try to insert data into it. Instead, I insert the data directly into the local table

I am asking about SELECTs. How do you query shards? if you don't use distributed tables?

**Comment by aol-59** [comment]
> > shard 7 is a replica of shard 1
> > No, I don't use it because it crashes after I try to insert data into it. Instead, I insert the data directly into the local table
> 
> I am asking about SELECTs. How do you query shards? if you don't use distributed tables?

I query each shard individually

**Comment by den-crane** [comment]
can you share the output of

```
set send_logs_level='trace';

select * 
from ( 
       select col_1 ,col_2 ,col_3 ,col_4 ,col_5 ,col_6 ,col_7 ,col_8 ,col_9 ,
col_10,col_11,col_12,col_13,col_14,col_15,col_16,col_17,col_18,col_19,
col_20,col_21,col_22,col_23,col_24,col_25,col_26,col_27,col_28,col_29

from db.table 
where col_1 in ('value','value','value','value','value' , ... )
and toYYYYMMDD(TIME) between toYYYYMMDD(dataSub(DAY,60 today())) AND toYYYYMMDD(today())
)
where col_20 <= 100
and col_21 <= 100 
and col_22 <= 100 
and col_23 <= 100
and col_24 <= 100
and col_25 <= 100 
and col_26 <= 100
and col_27 <= 100
LIMIT 10000 BY col_1 
format Null;
```

paste to https://pastila.nl/
and paste a created link to here ?

**Comment by den-crane** [comment]
try to disable users settings `move_all_conditions_to_prewhere=0` `enable_multiple_prewhere_read_steps=0`

I see `Peak memory usage: 169.51 MiB.` , but in the first message you reported `are now using 2,27 GB amount of memory on the new version.` ?

**Comment by aol-59** [comment]
> try to disable users settings `move_all_conditions_to_prewhere=0` `enable_multiple_prewhere_read_steps=0`
> 

is this the right way to disable it?
`ALTER USER my_user_name SETTINGS move_all_conditions_to_prewhere=0;`


> I see `Peak memory usage: 169.51 MiB.` , but in the first message you reported `are now using 2,27 GB amount of memory on the new version.` ?




I inspected the query_log using the following query:

`SELECT query, memory_usage
FROM system.query_log
WHERE event_date = today() AND normalized_query_hash = 'query_hash_value'
ORDER BY memory_usage DESC
LIMIT 200;
`

This query sorts the results by memory_usage in descending order.
 **I copied the same query that was reported to consume 2 GB.**
 However, when I executed this query manually, 
its memory usage was only around **200 MB.**


Subsequently, I attempted to downgrade to version 23.1, but encountered the following exception:

`DB:exception memory limit exceeded would use 512 TiB (attempt to allocate chunk of 0 bytes)  maximum: 350 GiB 
while executing aggregating transform. (memory_limit exceeded)
`

After encountering this error, I upgraded back to version 23.8.1.2992. The memory_limit_exception ceased, but memory usage is still on the rise.

Now, I'm in a quandary. Downgrading to the older version, which worked well previously, seems problematic. Moreover, I'm uncertain about the potential repercussions if memory usage continues to escalate and reaches its limit.

Thank you for your efforts and expertise as we navigate this challenge. I truly appreciate you taking the time to help.

**Comment by den-crane** [comment]
>is this the right way to disable it?

put a file like this
```xml
cat /etc/clickhouse-server/users.d/prewhere.xml
<?xml version="1.0" ?>
<clickhouse>
    <profiles>
        <default>
            <move_all_conditions_to_prewhere>0</move_all_conditions_to_prewhere>
            <enable_multiple_prewhere_read_steps>0</enable_multiple_prewhere_read_steps>
        </default>
    </profiles>
</clickhouse>
```

also upgrade to 23.8.2.7

**Comment by Yerkon** [comment]
> also upgrade to 23.8.2.7
@den-crane 
We are recently upgraded to this latest version.
In clickhouse server we just consumed messages from kafka engine to CollapsingMergeTree. 
And memory consumption linearly increased like in picture above. 
Looks like it's also actual for this version 

So, decided to downgrade to 23.1.

**Comment by den-crane** [comment]
>So, decided to downgrade to 23.1.

be careful with downgrade.  23.8 uses compressed marks, primary key, and sparse columns, and 23.1 does not.
check 
* https://github.com/ClickHouse/ClickHouse/issues/55153

**Comment by aol-59** [comment]
> > is this the right way to disable it?
> 
> put a file like this
> 
> ```
> cat /etc/clickhouse-server/users.d/prewhere.xml
> <?xml version="1.0" ?>
> <clickhouse>
>     <profiles>
>         <default>
>             <move_all_conditions_to_prewhere>0</move_all_conditions_to_prewhere>
>             <enable_multiple_prewhere_read_steps>0</enable_multiple_prewhere_read_steps>
>         </default>
>     </profiles>
> </clickhouse>
> ```
> 
> also upgrade to 23.8.2.7

the problem still exists after upgrading

**Comment by den-crane** [comment]
>the problem still exists after upgrading

I understand that. But how to fix it, if don't know where is the issue.
We need a reproducible example. At least we need to narrow down what process causes the leaking, ingestion? querying?, ...

**Comment by den-crane** [comment]
@aol-59 please share the output of `select getOSKernelVersion();`

**Comment by Yerkon** [comment]
> > the problem still exists after upgrading
> 
> I understand that. But how to fix it, if we don't know where is the issue. We need a reproducible example. At least we need to narrow down what process causes the leaking, ingestion? querying?, ...

@den-crane, 
1. In our cases we disabled everything(no queries to clickhouse from client) except consuming messages from Kafka(with MVs to write Mt tables) with kafka engine with settings:
`kafka_format = 'JSONAsString', kafka_skip_broken_messages = 1048576, kafka_num_consumers = 1, kafka_max_block_size = 65536, input_format_import_nested_json = 1, kafka_commit_every_batch = 1`

2. Reading messages to CollapsingMergeTree with simple Mv like:
```
CREATE MATERIALIZED VIEW default.kafkaMv
            TO default.tableReplacingMt
            (
             ...,
             `_topic` String,
             `_offset` UInt64,
             `_partition` String,
             `_timestamp` DateTime
                )
AS
WITH JSONExtract(json,
                 'Tuple(...)) AS jsonParsed
SELECT tupleElement(jsonParsed, '....')  ....,
        ....,    
        _topic,
       _offset,
       _partition,
       _timestamp
FROM default.kafkaIn
```

3. Second MV, which reads messages from **tableReplacingMt** to simple MergeTree Table(History table), 

> Be careful with downgrade.
> 23.8 uses compressed marks, compressed primary key and sparse columns, and 23.1 does not.
> check

Downgraded to 23.1 version with clean install, no data. 
After day monitoring with described case above, **no memory leak** issue found.

**Comment by aol-59** [comment]
> @aol-59 please share the output of `select getOSKernelVersion();`

Linux 3.10.0-1106el7.x86_64

**Comment by aol-59** [comment]
> > > the problem still exists after upgrading
> > 
> > 
> > I understand that. But how to fix it, if we don't know where is the issue. We need a reproducible example. At least we need to narrow down what process causes the leaking, ingestion? querying?, ...
> 
> @den-crane,
> 
> 1. In our cases we disabled everything(no queries to clickhouse from client) except consuming messages from Kafka(with MVs to write Mt tables) 

"When you disable everything except the Kafka engine, does the problem persist? I am also using the Kafka engine.

**Comment by aol-59** [comment]
When will this issue be resolved? I restart the server every week to free up memory.

**Comment by lichenglin** [comment]
same issue at LTS 23.8.4.

yellow line is the memory used metric. after upgade 21 to 23.8.4 . we found a mem leak

and we also use kafka to ingest data  

![image](https://github.com/ClickHouse/ClickHouse/assets/8294900/8dd34e59-bf84-415b-9c7e-7b9b42c5f07f)

**Comment by lichenglin** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/8294900/190942c9-7163-4de8-bcf5-93917370fdb1)
we have some warning log , I'm not sure if it is valueable

**Comment by lichenglin** [comment]
there may be someting wrong with kakfa_table .

we have a clean test enviroment with version 23.8.4.

here is the metric

`
SELECT toHour(event_time),max(metric),max(value)
FROM system.asynchronous_metric_log
WHERE metric ILIKE '%MemoryResident%' and event_date='2023-11-07' and event_time>'2023-11-07 01:00:00'
group by  toHour(event_time);
`

![image](https://github.com/ClickHouse/ClickHouse/assets/8294900/c37dba2f-0313-4cef-a2cf-c294fd7d1ea3)


and here is sql 

drop table if exists amazong_pacvue_test.fead_sb_traffic_v2 on cluster cluster1;
CREATE TABLE amazong_pacvue_test.fead_sb_traffic_v2 on cluster cluster1
(
    idempotency_id String,
    dataset_id String,
    marketplace_id String,
    time_window_start String,
    campaign_id String,
    ad_id String,
    ad_group_id String,
    advertiser_id String,
    keyword_id String,
    keyword_text String,
    keyword_type String,
    placement_type String,
    currency String,
    clicks Int128,
    cost Decimal(18,6),
    impressions Int128,
    viewable_impressions Int128,
    msgId String,
    msg_time DateTime,
    _insert_time DateTime,
    reportDateTimeHour DateTime64(3),
    reportDateTimeHour_utc DateTime
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/{uuid}', '{replica}')
partition by toYYYYMM(reportDateTimeHour)
ORDER BY (reportDateTimeHour,campaign_id,marketplace_id, ad_group_id, ad_id)
TTL toStartOfDay(reportDateTimeHour) + toIntervalDay(45)
SETTINGS index_granularity = 8192;


DROP table if exists  amazong_pacvue_test.fead_sb_traffic_v2_all
    ON CLUSTER cluster1;
CREATE TABLE  amazong_pacvue_test.fead_sb_traffic_v2_all
    ON CLUSTER cluster1 AS amazong_pacvue_test.fead_sb_traffic_v2
    ENGINE =
    Distributed(cluster1,amazong_pacvue_test,fead_sb_traffic_v2,
--分布键,必须是主键的一部分
    murmurHash2_32(campaign_id) );


--kafka

drop table if exists amazong_pacvue_test.kafka_fead_sb_traffic_v2 on cluster cluster1;
CREATE TABLE amazong_pacvue_test.kafka_fead_sb_traffic_v2 on cluster cluster1
(
    idempotency_id String,
    dataset_id String,
    marketplace_id String,
    time_window_start String,
    campaign_id String,
    ad_id String,
    ad_group_id String,
    advertiser_id String,
    keyword_id String,
    keyword_text String,
    keyword_type String,
    placement_type String,
    currency String,
    clicks Int128,
    cost Decimal(18,6),
    impressions Int128,
    viewable_impressions Int128,
    msgId String,
    msg_time String
)
    ENGINE = Kafka('b-1.us-kafka-2.a5kda1.c8.kafka.us-west-2.amazonaws.com:9092,b-3.us-kafka-2.a5kda1.c8.kafka.us-west-2.amazonaws.com:9092,b-2.us-kafka-2.a5kda1.c8.kafka.us-west-2.amazonaws.com:9092',
             'fead-sb-traffic-v2', 'test-ck-1', 'JSONEachRow') settings kafka_num_consumers = 1;

truncate table amazong_pacvue_test.fead_sb_traffic_v2 on cluster cluster1

drop view if exists amazong_pacvue_test.consumer_fead_sb_traffic_v2  on cluster cluster1;
 CREATE MATERIALIZED VIEW amazong_pacvue_test.consumer_fead_sb_traffic_v2  on cluster cluster1
     TO amazong_pacvue_test.fead_sb_traffic_v2_all
 AS
SELECT
    idempotency_id,
    dataset_id,
    marketplace_id,
    time_window_start,
    campaign_id,
    ad_id,
    ad_group_id,
    advertiser_id,
    keyword_id,
    keyword_text,
    keyword_type,
    placement_type,
    currency,
    clicks,
    cost,
    impressions,
    viewable_impressions,
    msgId,
    fromUnixTimestamp64Milli(toInt64(msg_time)) AS msg_time,
    now() as _insert_time,
    parseDateTimeBestEffortOrZero(time_window_start) AS reportDateTimeHour_utc,
    parseDateTime64BestEffortOrZero(substring(time_window_start, 1, 19)) AS reportDateTimeHour
FROM amazong_pacvue_test.kafka_fead_sb_traffic_v2  settings stream_like_engine_allow_direct_select=1;

**Comment by lichenglin** [comment]
I have submited a memory issue before. I'm not sure if they are relate.

[https://github.com/ClickHouse/ClickHouse/issues/36367](url)

**Comment by aol-59** [comment]
@lichenglin Have you upgraded to the latest version, and does the issue still exist?

**Comment by lichenglin** [comment]
> @lichenglin Have you upgraded to the latest version, and does the issue still exist?

23.9.3.12， I have tested , still get a mem leak

**Comment by ilejn** [comment]
Hello @aol-59 , did you manage to apply the setting? Any effect?

**Comment by ilejn** [comment]
> > Hello @aol-59 , did you manage to apply the setting? Any effect?
> 
> Unfortunately, the settings you suggested didn't seem to work as expected. I've applied them as instructed, but the issue still persists.

Many thanks, it is just to ensure that system.kafka_consumers is not the cause of the issue.

**Comment by alexfernandez** [comment]
At my company we are also seeing this issue, in our case not related to Kafka. It seems that the ClickHouse servers that have more data ingested also tend to have a bigger memory leak. ClickHouse version is 23.8.2.7, the same issue appears with 23.10. Below is used memory for a sample server. Any ideas? Thanks!

![image](https://github.com/ClickHouse/ClickHouse/assets/876570/f7d8495e-37ff-40fb-ac16-a4056c6d6552)

**Comment by antaljanosbenjamin** [comment]
So maybe the issue is not related to Kafka, but to insertion in general.

Maybe high insertion rate creates a lot of merges and those merges consume a lot of memory. Could you please check how much memory do the merges use? `SELECT memory_usage FROM system.merges;` and `SELECT sum(memory_usage) FROM system.merges;`.

**Comment by chenglinli0** [comment]
> So maybe the issue is not related to Kafka, but to insertion in general.
> 
> Maybe high insertion rate creates a lot of merges and those merges consume a lot of memory. Could you please check how much memory do the merges use? `SELECT memory_usage FROM system.merges;` and `SELECT sum(memory_usage) FROM system.merges;`.

SELECT formatReadableSize(memory_usage),* FROM system.merges

![image](https://github.com/ClickHouse/ClickHouse/assets/113302886/9d7a0ae2-69ae-4784-a66e-3f5ad36655a3)

**Comment by aol-59** [comment]
> So maybe the issue is not related to Kafka, but to insertion in general.
> 
> Maybe high insertion rate creates a lot of merges and those merges consume a lot of memory. Could you please check how much memory do the merges use? `SELECT memory_usage FROM system.merges;` and `SELECT sum(memory_usage) FROM system.merges;`.

**533 MB**

**Comment by alexfernandez** [comment]
> > SELECT formatReadableSize(memory_usage),* FROM system.merges
> 
> This only shows the memory usage of a single merge, however based on @aol-59's comment, I think the issue is not caused by merges.

In fact we disabled merges experimentally on a single machine to see how it behaved, and the memory continued increasing just as before.

**Comment by alexfernandez** [comment]
> So maybe the issue is not related to Kafka, but to insertion in general.
> 
> Maybe high insertion rate creates a lot of merges and those merges consume a lot of memory. Could you please check how much memory do the merges use? `SELECT memory_usage FROM system.merges;` and `SELECT sum(memory_usage) FROM system.merges;`.

The result of the query:

```
SELECT formatReadableSize(memory_usage),* FROM system.merges
Query id: 31bac837-7a68-441b-bb6d-42677614bb8c
Ok.
0 rows in set. Elapsed: 0.002 sec.
```

At this moment this instance was not doing any merges, it seems.

**Comment by azat** [comment]
>try adjusting kafka.statistics_interval_ms (or set it to 0 to disable new functionality)

It should be related - https://github.com/ClickHouse/ClickHouse/pull/57822

**Comment by azat** [comment]
>At my company we are also seeing this issue, in our case not related to Kafka. It seems that the ClickHouse servers that have more data ingested also tend to have a bigger memory leak. Below is used memory for a sample server with ClickHouse version 23.8.2.7, and the same issue remains with 23.10. After each restart the memory goes down to reasonable levels, and then starts climbing up steadily.

@alexfernandez This can be tons of things, did you look at the memory distribution inside the server, i.e. something like this?

```sql
WITH
    (SELECT sum(value::UInt64) FROM system.metrics WHERE metric = 'MemoryTracking')               AS memory_tracked_,
    (SELECT sum(total_bytes) FROM system.tables WHERE engine IN ('Join','Memory','Buffer','Set')) AS memory_tables_,
    (SELECT sum(value::UInt64) FROM system.asynchronous_metrics WHERE metric LIKE '%CacheBytes')  AS memory_caches_,
    (SELECT sum(memory_usage::UInt64) FROM system.processes)                                      AS memory_processes_,
    (SELECT sum(memory_usage::UInt64) FROM system.merges)                                         AS memory_merges_,
    (SELECT sum(bytes_allocated) FROM system.dictionaries)                                        AS memory_dictionaries_,
    (SELECT sum(primary_key_bytes_in_memory_allocated) FROM system.parts)                         AS memory_primary_keys_
SELECT
    assumeNotNull(memory_tracked_)                           AS memory_tracked,
    assumeNotNull(memory_tables_)                            AS memory_tables,
    assumeNotNull(memory_caches_)                            AS memory_caches,
    assumeNotNull(memory_processes_)                         AS memory_processes,
    assumeNotNull(memory_merges_)                            AS memory_merges,
    assumeNotNull(memory_dictionaries_)                      AS memory_dictionaries,
    assumeNotNull(memory_primary_keys_)                      AS memory_primary_keys
FORMAT Vertical
```

Maybe this will give some hints (you can also obtain some info like `*CacheBytes` from the `system.asynchronous_metric_log` with the history).

Also does this memory issue arises only *after* upgrade to some version?

P.S. I've just copied this query from the tool I wrote - https://github.com/azat/chdig/ (since I'm sick of running the same queries over and over again), maybe it will be useful to you as well

**Comment by azat** [comment]
Ok, it can be two things then: memory fragmentation and some kind of leak, but I doubt that there is direct leak, though I wouldn't exclude possibility of some live leak.

For memory fragmentation you can take a look at:  `select metric, value from system.asynchronous_metrics where metric like '%jemalloc%'`

As for the leaks:
- at first I would ensure that it is not https://github.com/ClickHouse/ClickHouse/pull/57822
- then you can look at the following message in the logs `MemoryTracking: was {}, peak {}, free memory in arenas {}, will set to {} (RSS), difference: {}` if the lag is huge, then it means that ClickHouse does not know about this allocations
  - if the answer to previous question is "lag is huge", then you can try jemalloc profiler - https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling (`MALLOC_CONF=prof:true,lg_prof_sample:21,abort_conf:true,confirm_conf:true`)
  - if the lag is is insignificant, then you can try new memory profiler (see `memory_profiler_sample_min_allocation_size` and `memory_profiler_sample_max_allocation_size`), or jemalloc profiler, it will also work great.

**Comment by aol-59** [comment]
> Ok, it can be two things then: memory fragmentation and some kind of leak, but I doubt that there is direct leak, though I wouldn't exclude possibility of some live leak.
> 
> 
> 
> For memory fragmentation you can take a look at:  `select metric, value from system.asynchronous_metrics where metric like '%jemalloc%'`
> 
> 
> 
> As for the leaks:
> 
> - at first I would ensure that it is not https://github.com/ClickHouse/ClickHouse/pull/57822
> 
> - then you can look at the following message in the logs `MemoryTracking: was {}, peak {}, free memory in arenas {}, will set to {} (RSS), difference: {}` if the lag is huge, then it means that ClickHouse does not know about this allocations
> 
>   - if the answer to previous question is "lag is huge", then you can try jemalloc profiler - https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling (`MALLOC_CONF=prof:true,lg_prof_sample:21,abort_conf:true,confirm_conf:true`)
> 
>   - if the lag is is insignificant, then you can try new memory profiler (see `memory_profiler_sample_min_allocation_size` and `memory_profiler_sample_max_allocation_size`), or jemalloc profiler, it will also work great.

![image](https://github.com/ClickHouse/ClickHouse/assets/50527487/1bca0472-d14e-4c68-bc73-64d064640e0b)

**Comment by aol-59** [comment]
After I disabled **statistics_interval_ms**, I restarted ClickHouse 16 hours ago, and everything seemed fine until now. Additionally, I created a new file in **config.d** named **kafka.xml**  then i restarted Clickhouse. 
```
<yandex>
  <kafka>
        <statistics_interval_ms>0</statistics_interval_ms>
  </kafka>
</yandex>
```
I hope this information can assist you.

**Comment by chenglinli0** [comment]
hello, do we have any PR for this?

**Comment by azat** [comment]
- https://github.com/ClickHouse/ClickHouse/pull/57822
- https://github.com/ClickHouse/ClickHouse/pull/57829
