### ISSUE TITLE
about replacingmergetree data merge order

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#54487]
my clickhouse version 23.7.2.25
Recently ，I have some mergers that did not follow the expected results:
The data inserted later is overwritten by the data inserted earlier
first:
{"op":"c","handle_time":"2023-09-07 02:33:46","job_id":"885","alarm_status":"0","handle_code":"0","id":"57812773"}
later:
{"op":"u","handle_time":"2023-09-07 02:33:46","job_id":"885","alarm_status":"0","handle_code":"200","id":"57812773"}

but final in clickhose is :
{"op":"c","handle_time":"2023-09-07 02:33:46","job_id":"885","alarm_status":"0","handle_code":"0","id":"57812773"}

 select handle_code from xxl_job_log where id = 57812773 format JSONEachRow;

SELECT handle_code
FROM xxl_job_log
WHERE id = 57812773
FORMAT JSONEachRow

Query id: 21a33a55-39a7-488e-91e2-533bfa0634f9

{"handle_code":0}

this is mysql table engine:
CREATE TABLE xxl_job_log
(
    `id` Int64,
     `job_id` Nullable(String),
    `handle_time` Nullable(DateTime),
    `handle_code` Int32,
    `alarm_status` Int8
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY id
SETTINGS storage_policy = 'all_jbod', index_granularity = 8192

To investigate the cause of this issue：
I created a mergetree table like this

CREATE TABLE xxl_job_log_v2
(
    `id` Int64,
    `job_id` Int32,
    `handle_code` Int32,
    `alarm_status` Int8,
    `ts_ms` Int64 comment "Kafka message creation time"
    `op` String,
    `created_time` DateTime64(3) DEFAULT now(),
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY id
SETTINGS storage_policy = 'all_jbod', index_granularity = 8192

ts_ms : Kafka message creation time

clickhous02:) select created_time,ts_ms,handle_code from xxl_job_log_v2 where id = 57812773 format JSONEachRow;

SELECT
    created_time,
    ts_ms,
    handle_code
FROM xxl_job_log_v2
WHERE id = 57812773
FORMAT JSONEachRow

Query id: 015c5de9-0a60-4d0b-bfe5-61962950b370

{"created_time":"2023-09-07 02:33:46.000","ts_ms":"1694025226013","handle_code":0}
{"created_time":"2023-09-07 02:33:46.000","ts_ms":"1694025226092","handle_code":200}

The data synchronization tool I use, vector，
I have already reported the same issue to the vector community
https://github.com/vectordotdev/vector/discussions/18479

**Comment by den-crane** [comment]
Your evidences proofs nothing without reproducible example.

There are a lot of possible reasons:
Insert with `handle_code":"200"` failed with an error.
Insert with `handle_code":"200"` was deduplicated by insert deduplication.
....

**Comment by yangshike** [comment]
1、Insert without errors
2、This record has only 2 messages in Kafka
one is : handle_code 0  ，second is handle_code：200

**Comment by den-crane** [comment]
>1、Insert without errors

Why do you think so?

>2、This record has only 2 messages in Kafka

Why do you think that vectordev did not inserted these 2 rows 16 times?

**Comment by den-crane** [comment]
This issue is not actionable without reproducible example. Even there is a bug in ReplacingMergeTree merges, it's impossible to find without reproducible example.

**Comment by yangshike** [comment]
I was initially worried about the issue with the vector, so I created a separate mergetree table (xxl_job_log_v2) without replacing it. From the v2 table, I saw that only 2 pieces of data were inserted

**Comment by yangshike** [comment]
These two messages are very close in time, and I am currently monitoring the data sent by the vector for sorting anomalies in the clickHouse
