### ISSUE TITLE
clickinghouse-keeper-client The operation is incompatible with zookeeper

### ISSUE THREAD

**Issue by jiugem** [ClickHouse/ClickHouse#54491]
Please help provide an example of clickinghouse-keeper-client login user password, deletion of user password.
It is somewhat different from zookeeper. Tried addauth but it does not take effect.

/ :) auth zku:PassWD_1
Syntax error: failed at position 5 (' '):

auth zku:PassWD_1

Expected end of query

/ :) addauth digest zku:PassWD_1
Syntax error: failed at position 1 ('addauth'):

addauth digest zku:PassWD_1

Expected one of: Keeper client query, cd, create, delete_stale_backups, find_big_family, find_super_nodes, flwc, get, get_stat, help, ls, rm, rmr, set, touch, lgif, csnp, dump, wchp, rqld, wchc, isro, crst, dirs, cons, srst, envi, conf, stat, ruok, srvr, wchs, mntr
/ :) 

There are no cases in official documents

**Comment by jiugem** [comment]
In the new version of clickhouse-client, after logging in from the command line, there is no prompt at the beginning. I am not used to it. Are there any parameters that I can change back?

Love the bracket reminder
ch1 :)
ch1 :)

**Comment by jiugem** [comment]
Ask for guidance

**Comment by jiugem** [comment]
Ask again

**Comment by pufit** [comment]
Hi @jiugem! This operation has not been implemented in keeper-client yet. We will add auth support in the near future!

**Comment by jiugem** [comment]
@pufit Thank you and look forward to that day!
