### ISSUE TITLE
Fuzzer failure `Assertion 'new_head == holder.key.data' failed`

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#54495]
**Describe the bug**
A link to the report https://s3.amazonaws.com/clickhouse-test-reports/54043/03914f2d31da7a3c3384426c425666f6526afa93/fuzzer_astfuzzerdebug/report.html found in #54043 

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

**Comment by tavplubix** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/54352

cc: @KochetovNicolai
