### ISSUE TITLE
 Flaky test_delayed_replica_failover

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#54502]
**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/0/9bbd81ca6c27c3645be0d12ee61f304d1494bbe3/integration_tests__release__[4_4].html

**Error message and/or stacktrace**
```
            # If we forbid stale replicas, the query must fail. But sometimes we must have bigger timeouts.
            for _ in range(20):
                try:
                    instance_with_dist_table.query(
                        """
    SELECT count() FROM distributed SETTINGS
        load_balancing='in_order',
        max_replica_delay_for_distributed_queries=1,
        fallback_to_stale_replicas_for_distributed_queries=0
    """
                    )
                    time.sleep(0.5)
                except:
                    break
            else:
>               raise Exception("Didn't raise when stale replicas are not allowed")
E               Exception: Didn't raise when stale replicas are not allowed

test_delayed_replica_failover/test.py:151: Exception
```

**Comment by qoega** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/fe155c61d439aeb2138a5fa86fc54643e87496c1/integration_tests__release__[4_4].html

**Comment by devcrafter** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/002f7ded74f70e954c48a43e7f13005c6953826e/integration_tests__release__[4_4].html

**Comment by vdimir** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/53404/643fef589d0b1fce9f5312409bebe5b0a0db0117/integration_tests__asan__[6_6].html

https://s3.amazonaws.com/clickhouse-test-reports/53404/643fef589d0b1fce9f5312409bebe5b0a0db0117/integration_tests__release__[4_4].html

(from https://github.com/ClickHouse/ClickHouse/pull/53404)

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/55944/66c4a3bdbce488ae2d43230d5a26ba1e7e8e49a7/integration_tests__release__[4_4].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/56137/373d8bbb2015b3238b1feebf3e35826064e65075/integration_tests__release__[4_4].html

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/56083/ae8d7a557b74ef9f431b63c8333a711c579fe1c0/integration_tests__release__[4_4].html

**Comment by tavplubix** [comment]
Still flaky: https://s3.amazonaws.com/clickhouse-test-reports/56796/a2acb0e9239f4dc5457e3ec9f2d72998f013009a/integration_tests__asan__analyzer__[6_6].html

**Comment by alexey-milovidov** [comment]
It failed: https://s3.amazonaws.com/clickhouse-test-reports/0/3770d5c2bfc778e85bc90fd122a0ed0c7e4bf8ad/integration_tests__release__[4_4].html

**Comment by alexey-milovidov** [comment]
It failed again: https://s3.amazonaws.com/clickhouse-test-reports/0/592f966c2eedfa41c548f8792696a602f0f16743/integration_tests__asan__[4_4].html
