### ISSUE TITLE
Backward compatibility for parseDateTime function

### ISSUE THREAD

**Issue by furkankahvecinsider** [ClickHouse/ClickHouse#54538]
The parseDateTime and parseDateTimeOrNull functions was introduced in version 23.3, can we set it to support 22.8 for backward compatibility if it can be done? 

If there is anything we can do within our cluster, I'd be happy to hear about it.
We're using 22.8.16.32 version in CH.

The case

In version 22.8, I need to check and eliminate date times such as "2023-09-12T00:00:00". I only want to find datetimes that fit the YYYY-MM-DD HH:MM:SS format, if not, I want it to return NULL.

Normally I use the toDateTimeOrNull function, but when I give the datetime in the example to this function, it deletes the T and gives the correct datetime, but I need to make sure it is the correct datetime first.

![image](https://github.com/ClickHouse/ClickHouse/assets/76960252/1f686f8a-01e7-4e76-a3b6-6e0a60263757)

**Comment by furkankahvecinsider** [comment]
yes if it's possible

**Comment by rschu1ze** [comment]
Just noticed that LTS releases like v22.8 are supported [for one year](https://clickhouse.com/docs/en/faq/operations/production#how-to-choose-between-clickhouse-releases). The final release of v22.8 was made two weeks ago - we missed it by a small margin. Would it be possible for you to upgrade to v23.3 (which is also LTS)?

**Comment by furkankahvecinsider** [comment]
It is not necessary for us to upgrade the version just for this problem. If we cannot do backward compatibility with this version, is there any chance of solving this problem with the 22.8 version?

**Comment by rschu1ze** [comment]
As a workaround, you could use regexp matching to check the expected format:

```sql
select match('2023-09-12T00:00:00', '\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d')
```

**Comment by den-crane** [comment]
parseDateTimeBestEffortOrNull exists ?

```
SELECT parseDateTimeBestEffortOrNull('2020-02-02')

Query id: 981af1a2-98bf-4986-8d78-75f8aa0dbe40

┌─parseDateTimeBestEffortOrNull('2020-02-02')─┐
│                         2020-02-02 00:00:00 │
└─────────────────────────────────────────────┘
```

**Comment by furkankahvecinsider** [comment]
@rschu1ze  is there anything I should know about regexp performance?

@den-crane actually, actually, I want date times that do not fit the format to not be parsed.

**Comment by rschu1ze** [comment]
Regexes are evaluated with re2. One-time costs exist for regexp compilation, and for execution (once per row) - in general don't expect `match()` to be superfast. In case of doubt, always measure ;-)

**Comment by furkankahvecinsider** [comment]
So, does the parseDateTime function use regexp? If it is using it, i can check it with regexp until I upgrade the version.

**Comment by rschu1ze** [comment]
None of the parseDateTime*() functions use regexps, I would expect them to be faster than "match()".

**Comment by furkankahvecinsider** [comment]
by the way, i'm gonna use to check this regex for my date times

``^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$``
