### ISSUE TITLE
Sanitizer alert in 00980_shard_aggregation_state_deserialization

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#54539]
Fails in `roaring::Roaring64Map::runOptimize()` called from `AggregateFunctionGroupBitmapData.h`

- https://s3.amazonaws.com/clickhouse-test-reports/54201/4f5d132019c011cdee07faf90a329536c11a7f6f/stateless_tests__tsan__[5_5]/stderr.log (from #54201)

- https://s3.amazonaws.com/clickhouse-test-reports/54514/1d8a1c46fd2dc443773bf0d9c998917c952c63aa/stateless_tests__asan__[4_4]/stderr.log (from #54514)

**Comment by tavplubix** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/54528

cc: @evillique
