### ISSUE TITLE
 Is there a time limit for the merge of ReplicatedAggregatingMergeTree?

### ISSUE THREAD

**Issue by eulery** [ClickHouse/ClickHouse#54586]
I have a ReplicatedAggregatingMergeTree table partition by date.
about 1 month ago I wrote the first data to this partition.
and about 1 week ago I wrote data to this partition again.
there are duplicate order keys in the two data，I expect to merge them using the ReplicatedAggregatingMergeTree，but it does not work.

when I run 
`select *
from system.parts
where table = 'dwd_model_s_WeaStation_1m'
  and partition = '2023-07-28';`

the result is 
| partition | name | uuid | part\_type | active | marks | rows | bytes\_on\_disk | data\_compressed\_bytes | data\_uncompressed\_bytes | marks\_bytes | secondary\_indices\_compressed\_bytes | secondary\_indices\_uncompressed\_bytes | secondary\_indices\_marks\_bytes | modification\_time | remove\_time | refcount | min\_date | max\_date | min\_time | max\_time | partition\_id | min\_block\_number | max\_block\_number | level | data\_version | primary\_key\_bytes\_in\_memory | primary\_key\_bytes\_in\_memory\_allocated | is\_frozen | database | table | engine | disk\_name | path | hash\_of\_all\_files | hash\_of\_uncompressed\_files | uncompressed\_hash\_of\_compressed\_files | delete\_ttl\_info\_min | delete\_ttl\_info\_max | move\_ttl\_info.expression | move\_ttl\_info.min | move\_ttl\_info.max | default\_compression\_codec | recompression\_ttl\_info.expression | recompression\_ttl\_info.min | recompression\_ttl\_info.max | group\_by\_ttl\_info.expression | group\_by\_ttl\_info.min | group\_by\_ttl\_info.max | rows\_where\_ttl\_info.expression | rows\_where\_ttl\_info.min | rows\_where\_ttl\_info.max | projections | visible | creation\_tid | removal\_tid\_lock | removal\_tid | creation\_csn | removal\_csn | has\_lightweight\_delete | last\_removal\_attemp\_time | removal\_state |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2023-07-28 | 20230728\_0\_0\_0\_1 | 00000000-0000-0000-0000-000000000000 | Compact | 1 | 2 | 288 | 6989 | 6166 | 52416 | 688 | 0 | 0 | 0 | 2023-09-06 10:59:20 | 1970-01-01 08:00:00 | 1 | 2023-07-28 | 2023-07-28 | 1970-01-01 08:00:00 | 1970-01-01 08:00:00 | 20230728 | 0 | 0 | 0 | 1 | 62 | 8448 | 0 | hunduncloud | dwd\_model\_s\_WeaStation\_1m | ReplicatedAggregatingMergeTree | default | /data/clickhouse-data/store/e43/e432c57c-dde1-4cdc-9e05-f1f7ebe43d3d/20230728\_0\_0\_0\_1/ | 1f0aa28e220d1252d42e3325616c884a | d1c56463c2a58e1b311e46edbcdeb21c | 0ba38bbe141d1a62c1fc0322d24785ba | 2024-05-23 00:00:00 | 2024-05-23 23:55:00 | \[\] | \[\] | \[\] | LZ4 | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | 1 | \(1,1,'00000000-0000-0000-0000-000000000000'\) | 0 | \(0,0,'00000000-0000-0000-0000-000000000000'\) | 0 | 0 | 0 | 1970-01-01 08:00:00 | Cleanup thread hasn't seen this part yet |
| 2023-07-28 | 20230728\_2\_2\_0 | 00000000-0000-0000-0000-000000000000 | Compact | 1 | 2 | 288 | 4961 | 4138 | 52416 | 688 | 0 | 0 | 0 | 2023-09-06 11:02:25 | 1970-01-01 08:00:00 | 1 | 2023-07-28 | 2023-07-28 | 1970-01-01 08:00:00 | 1970-01-01 08:00:00 | 20230728 | 2 | 2 | 0 | 2 | 62 | 768 | 0 | hunduncloud | dwd\_model\_s\_WeaStation\_1m | ReplicatedAggregatingMergeTree | default | /data/clickhouse-data/store/e43/e432c57c-dde1-4cdc-9e05-f1f7ebe43d3d/20230728\_2\_2\_0/ | 027bb8cc75835438d76c0d711c87ed08 | ce08351afb860395c12205e2e2b4b32e | 12826113b13279b16273d09910c9f6b0 | 2024-05-23 00:00:00 | 2024-05-23 23:55:00 | \[\] | \[\] | \[\] | LZ4 | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | 1 | \(1,1,'00000000-0000-0000-0000-000000000000'\) | 0 | \(0,0,'00000000-0000-0000-0000-000000000000'\) | 0 | 0 | 0 | 1970-01-01 08:00:00 | Cleanup thread hasn't seen this part yet |

It looks like the merge didn't happen，but optimize can merge these parts
| partition | name | uuid | part\_type | active | marks | rows | bytes\_on\_disk | data\_compressed\_bytes | data\_uncompressed\_bytes | marks\_bytes | secondary\_indices\_compressed\_bytes | secondary\_indices\_uncompressed\_bytes | secondary\_indices\_marks\_bytes | modification\_time | remove\_time | refcount | min\_date | max\_date | min\_time | max\_time | partition\_id | min\_block\_number | max\_block\_number | level | data\_version | primary\_key\_bytes\_in\_memory | primary\_key\_bytes\_in\_memory\_allocated | is\_frozen | database | table | engine | disk\_name | path | hash\_of\_all\_files | hash\_of\_uncompressed\_files | uncompressed\_hash\_of\_compressed\_files | delete\_ttl\_info\_min | delete\_ttl\_info\_max | move\_ttl\_info.expression | move\_ttl\_info.min | move\_ttl\_info.max | default\_compression\_codec | recompression\_ttl\_info.expression | recompression\_ttl\_info.min | recompression\_ttl\_info.max | group\_by\_ttl\_info.expression | group\_by\_ttl\_info.min | group\_by\_ttl\_info.max | rows\_where\_ttl\_info.expression | rows\_where\_ttl\_info.min | rows\_where\_ttl\_info.max | projections | visible | creation\_tid | removal\_tid\_lock | removal\_tid | creation\_csn | removal\_csn | has\_lightweight\_delete | last\_removal\_attemp\_time | removal\_state |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2023-07-28 | 20230728\_0\_0\_0\_1 | 00000000-0000-0000-0000-000000000000 | Compact | 0 | 2 | 288 | 6989 | 6166 | 52416 | 688 | 0 | 0 | 0 | 2023-09-06 10:59:20 | 2023-09-13 20:12:10 | 1 | 2023-07-28 | 2023-07-28 | 1970-01-01 08:00:00 | 1970-01-01 08:00:00 | 20230728 | 0 | 0 | 0 | 1 | 62 | 8448 | 0 | hunduncloud | dwd\_model\_s\_WeaStation\_1m | ReplicatedAggregatingMergeTree | default | /data/clickhouse-data/store/e43/e432c57c-dde1-4cdc-9e05-f1f7ebe43d3d/20230728\_0\_0\_0\_1/ | 1f0aa28e220d1252d42e3325616c884a | d1c56463c2a58e1b311e46edbcdeb21c | 0ba38bbe141d1a62c1fc0322d24785ba | 2024-05-23 00:00:00 | 2024-05-23 23:55:00 | \[\] | \[\] | \[\] | LZ4 | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | 0 | \(1,1,'00000000-0000-0000-0000-000000000000'\) | 15317705874040209379 | \(1,1,'00000000-0000-0000-0000-000000000000'\) | 0 | 0 | 0 | 1970-01-01 08:00:00 | Cleanup thread hasn't seen this part yet |
| 2023-07-28 | 20230728\_0\_2\_1\_1 | 00000000-0000-0000-0000-000000000000 | Compact | 1 | 2 | 288 | 7007 | 6184 | 52416 | 688 | 0 | 0 | 0 | 2023-09-13 20:12:10 | 1970-01-01 08:00:00 | 1 | 2023-07-28 | 2023-07-28 | 1970-01-01 08:00:00 | 1970-01-01 08:00:00 | 20230728 | 0 | 2 | 1 | 1 | 62 | 8448 | 0 | hunduncloud | dwd\_model\_s\_WeaStation\_1m | ReplicatedAggregatingMergeTree | default | /data/clickhouse-data/store/e43/e432c57c-dde1-4cdc-9e05-f1f7ebe43d3d/20230728\_0\_2\_1\_1/ | 321c67e8ceb331033273d00954113910 | 084daadb11066f3829c1645a5de790ab | 8de29e4917d52c289cc0400581893454 | 2024-05-23 00:00:00 | 2024-05-23 23:55:00 | \[\] | \[\] | \[\] | LZ4 | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | 1 | \(1,1,'00000000-0000-0000-0000-000000000000'\) | 0 | \(0,0,'00000000-0000-0000-0000-000000000000'\) | 0 | 0 | 0 | 1970-01-01 08:00:00 | Cleanup thread hasn't seen this part yet |
| 2023-07-28 | 20230728\_2\_2\_0 | 00000000-0000-0000-0000-000000000000 | Compact | 0 | 2 | 288 | 4961 | 4138 | 52416 | 688 | 0 | 0 | 0 | 2023-09-06 11:02:25 | 2023-09-13 20:12:10 | 1 | 2023-07-28 | 2023-07-28 | 1970-01-01 08:00:00 | 1970-01-01 08:00:00 | 20230728 | 2 | 2 | 0 | 2 | 62 | 768 | 0 | hunduncloud | dwd\_model\_s\_WeaStation\_1m | ReplicatedAggregatingMergeTree | default | /data/clickhouse-data/store/e43/e432c57c-dde1-4cdc-9e05-f1f7ebe43d3d/20230728\_2\_2\_0/ | 027bb8cc75835438d76c0d711c87ed08 | ce08351afb860395c12205e2e2b4b32e | 12826113b13279b16273d09910c9f6b0 | 2024-05-23 00:00:00 | 2024-05-23 23:55:00 | \[\] | \[\] | \[\] | LZ4 | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | \[\] | 0 | \(1,1,'00000000-0000-0000-0000-000000000000'\) | 15317705874040209379 | \(1,1,'00000000-0000-0000-0000-000000000000'\) | 0 | 0 | 0 | 1970-01-01 08:00:00 | Cleanup thread hasn't seen this part yet |

What I want to ask is， what causes this?

**Comment by nickitat** [comment]
> I expect to merge them using the ReplicatedAggregatingMergeTree

pls check the docs, there is clearly stated that merge will happen in undefined moment in time and users shouldn't rely on it. instead you're supposed to run selects with the `final` modifier.

p.s. in most of the cases partitioning by day is a bad idea.

**Comment by den-crane** [comment]
Merger uses complicated algorithm to balance number of parts. 
Merge has no goal to do the final merge -- to make 1 part because it's not efficient. It has a goal to balance reasonable number of parts with minimal number of merges, to save CPU and DISK IO resources.

You can use https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#min_age_to_force_merge_seconds

**Comment by eulery** [comment]
> > I expect to merge them using the ReplicatedAggregatingMergeTree
> 
> pls check the docs, there is clearly stated that merge will happen in undefined moment in time and users shouldn't rely on it. instead you're supposed to run selects with the `final` modifier.
> 
> p.s. in most of the cases partitioning by day is a bad idea.

Thanks for the suggestion. I will change the partition key.

**Comment by eulery** [comment]
> Merger uses complicated algorithm to balance number of parts. Merge has no goal to do the final merge -- to make 1 part because it's not efficient. It has a goal to balance reasonable number of parts with minimal number of merges, to save CPU and DISK IO resources.
> 
> You can use https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#min_age_to_force_merge_seconds

Thanks for the answer. I'll try this config.

**Comment by eulery** [comment]
> Merger uses complicated algorithm to balance number of parts. Merge has no goal to do the final merge -- to make 1 part because it's not efficient. It has a goal to balance reasonable number of parts with minimal number of merges, to save CPU and DISK IO resources.
> 
> You can use https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#min_age_to_force_merge_seconds

By the way，if i change min_age_to_force_merge_seconds，will it take effect on existing parts?

**Comment by den-crane** [comment]
>By the way，if i change min_age_to_force_merge_seconds，will it take effect on existing parts?

yes

**Comment by smohite03** [comment]
Does it will also affect parts which are already merged??

**Comment by den-crane** [comment]
> Does it will also affect parts which are already merged??

It does not merge partitions with a single part.
