### ISSUE TITLE
ClickHouse server gets killed by OOM when writing and reading from parquet file

### ISSUE THREAD

**Issue by Selfeer** [ClickHouse/ClickHouse#54609]
**Description**
The ClickHouse process gets killed by OOM when the machine hits the memory limit while running queries. No errors appear inside the clickhouse logs. 

The issue appears when running a set of queries with high parallelization, the queries run for a while and at the end errors appear:
`Code: 210. DB::NetException: Connection refused` 

Running `sudo dmesg` indicates that the process was killed by OOM:
```shell
Out of memory: Killed process 3043308 (clickhouse) total-vm:83713188kB, anon-rss:3445832kB, file-rss:286336kB, shmem-rss:0kB, UID:1000 pgtables:151196kB oom_score_adj:0
```

**How to reproduce**

* ClickHouse server version: 23.8.2.7
* Parquet file used: [data_NONE.Parquet](https://github.com/Altinity/clickhouse-regression/blob/main/parquet/data/data_NONE.Parquet)
* `CREATE TABLE` statement:
```sql
CREATE TABLE  table_8d075a9c_4cb1_11ee_8300_910c29c9f0b4 ENGINE = MergeTree ORDER BY tuple() AS SELECT * FROM file('data_NONE.Parquet', Parquet)
```
The issue usually occurs when multiple INSERT FROM INFILE are run in parallel. Below you can see an example script that can reproduce the issue if run after above preconditions are satisfied.

```shell
#!/bin/bash

# Function to execute the command in the background
execute_command() {
  clickhouse client -n -q "INSERT INTO table_8d075a9c_4cb1_11ee_8300_910c29c9f0b4 FROM INFILE 'data_NONE.Parquet' FORMAT Parquet"
}

# Function to clean up when Ctrl+C is pressed
cleanup() {
  echo "Ctrl+C received, cleaning up..."
  pkill -P $$
  wait
  echo "All processes have been terminated."
  exit 1
}

# Set up the trap to catch Ctrl+C and call the cleanup function
trap cleanup SIGINT

# Number of parallel processes you want to run
num_parallel=400

# Read the queries from the input file

for ((i = 0; i < num_parallel; i++)); do
  execute_command "$query" &
done 


# Wait for all background processes to finish
wait
```

**Comment by den-crane** [comment]
22.8 is obsolete. 
Does it crash with 23.8 ?

**Comment by den-crane** [comment]
BTW, your queries read MergeTree `ENGINE = MergeTree ORDER BY tuple() ` 

The issue is not related to parquet.

**Comment by den-crane** [comment]
N*500 parallel queries are expected to use a lot of RAM.

**Comment by vzakaznikov** [comment]
> BTW, your queries read MergeTree `ENGINE = MergeTree ORDER BY tuple() `
> 
> The issue is not related to parquet.

Yes, it is. There are queries like

**Comment by vzakaznikov** [comment]
@Selfeer, can you try running your script without SELECT's which just read from MergeTree to using only 
```
INSERT INTO table_8d075a9c_4cb1_11ee_8300_910c29c9f0b4 FROM INFILE 'data_NONE.Parquet' FORMAT Parquet
````
?

**Comment by Selfeer** [comment]
As @vzakaznikov suggested I've removed queries with SELECT statements and left just ones with INSERT FROM INFILE. I run it on 23.8.2.7 and was able to reproduce the issue following the instructions from the description. 

@den-crane could you please remove the `obsolete-version` label?

**Comment by den-crane** [comment]
I don't understand what is the issue.
Parquet is ingested by a clickhouse-client, it's not related to clickhouse-server.
And clickhouse-client is created 400 times in paralllel. Obviously it uses a lot of RAM.

**Comment by den-crane** [comment]
Clickhouse cannot prevent OOM in this case BTW. It allowed to use 0.9 of RAM, but most of RAM is used by 400 clickhouse-client processes, and clickhouse-server is killed by OOM because it the most heavy process but uses at this moment less than 0.9 RAM.

**Comment by vzakaznikov** [comment]
But isn't the problem that the Arrow library code that handles Parquet read and writes does memory allocations outside of ClickHouse memory pools which causes the OOM? @arthurpassos?

**Comment by den-crane** [comment]
If you execute `INSERT INTO table_8d075a9c_4cb1_11ee_8300_910c29c9f0b4 FROM INFILE 'data_NONE.Parquet' FORMAT Parquet` then in this case clichkouse-client reads parquet, transforms it into Native and propagates Native into Clickhouse-server as long as all other formats. 

You can use curl if you want to parse files by the Clickhouse-server `curl --data-binary @data_NONE.Parquet`

**Comment by Selfeer** [comment]
It seems like the issue is not reproducible when using curl instead of the clickhouse client as @den-crane suggested
