### ISSUE TITLE
When the two conditions of PREWHERE are the same, the query fails.

### ISSUE THREAD

**Issue by lzf575** [ClickHouse/ClickHouse#54617]
**Describe what's wrong**

When the two conditions of PREWHERE are the same, the query fails.

**Does it reproduce on recent release?**

 yes, 23.8.2.7

**Enable crash reporting**

![image](https://github.com/ClickHouse/ClickHouse/assets/44988793/a02c34eb-2246-4a3e-bc95-7052cc63da64)

**How to reproduce**

*  create table test  (a UInt16,b UInt16) engine=MergeTree PRIMARY KEY a   order by a ;
*  insert into test values (1,1);
*  then  select with prewhere failed.   select a from test prewhere (a !=0) and (b !=0 ) and (a !=0) ;
![image](https://github.com/ClickHouse/ClickHouse/assets/44988793/60b54f99-9a31-4133-b711-34a68879639a)
* select with where ok. select a from test where (a !=0) and (b !=0 ) and (a !=0) ;
![image](https://github.com/ClickHouse/ClickHouse/assets/44988793/dca5f102-c6e7-430a-abfa-4a6db7548e2b)

**Comment by tavplubix** [comment]
used to work in 23.6: https://fiddle.clickhouse.com/ca833ead-90a2-48a6-a555-887a4b041412
broken in 23.7: https://fiddle.clickhouse.com/1d405281-2880-4894-886e-03eae39b22a3

**Comment by tavplubix** [comment]
Workaround: `set enable_multiple_prewhere_read_steps=0;`: https://fiddle.clickhouse.com/939e672f-381e-4ace-8be5-6d6b14fa59e1

So it's https://github.com/ClickHouse/ClickHouse/pull/46365

**Comment by den-crane** [comment]
probably duplicate
* https://github.com/ClickHouse/ClickHouse/issues/53237
