### ISSUE TITLE
query_log stopped reporting queries since yesterday

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#54611]
I did an upgrade to expand disk size on kubernetes and query_log no longer logs queries. 

cat clickhouse-server.err.log | grep query_log
2023.09.12 12:13:51.678151 [ 7 ] {} <Warning> ExternalDictionariesLoader: /etc/clickhouse-server/config.d/01-clickhouse-03-query_log.xml: file contains unknown node 'query_log', expected 'dictionary'

here is the content of /etc/clickhouse-server/config.d/01-clickhouse-03-query_log.xml:
```
<yandex>
    <query_log replace="1">
        <database>system</database>
        <table>query_log</table>
        <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + interval 30 day</engine>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_log>
    <query_thread_log remove="1"/>
</yandex>
```

my version for clickhouse is 23.3.2 and have not changed in a while. installation is on eks.

**Comment by alexey-milovidov** [comment]
You don't need any extra configuration to enable `query_log`. It is enabled by default.
But you could mess up something in your Kubernetes - try installing ClickHouse without Kubernetes and it will be alright.
