### ISSUE TITLE
When hadoop.rpc.protection is set to privacy, an error is reported when data is inserted after the HDFS engine is created.

### ISSUE THREAD

**Issue by hantaoliulinux** [ClickHouse/ClickHouse#54620]
I am using v23.3.2.37-lts version

error info

![image](https://github.com/ClickHouse/ClickHouse/assets/39047544/e1e08d74-c1fa-4c1b-9cb9-3aee251c8d5d)

**Comment by alexey-milovidov** [comment]
Hadoop does not matter for us.
