### ISSUE TITLE
No more TGZ build ?

### ISSUE THREAD

**Issue by mcarbonneaux** [ClickHouse/ClickHouse#5464]
why you not build anymore the tgz build in https://repo.yandex.ru/clickhouse/tgz/ ?

**Comment by alesapin** [comment]
We will return it in two next releases.

**Comment by alesapin** [comment]
We have turned them back! First testing version (19.11.0.736) can be downloaded here https://repo.yandex.ru/clickhouse/tgz/. Each next testing/prestable/stable release can be downloaded in the same repo.

**Comment by alexey-milovidov** [comment]
Reopened, because new tgz packages have not tested.
I don't see install script inside.

**Comment by alexey-milovidov** [comment]
`tgz` packages are available and tested.

**Comment by alexey-milovidov** [comment]
The usage example is available on the main website page: https://clickhouse.tech/ (see "Other Linux").
