### ISSUE TITLE
Exception: Function toDecimal128 is not parametric on the ClickHouse latest

### ISSUE THREAD

**Issue by Selfeer** [ClickHouse/ClickHouse#54640]
**Description**

An exception occurs when running the following query on 23.8
```sql
INSERT INTO test VALUES (toDecimal128(38)(1., 38));
```
The error message:
```
Error on processing query: Code: 309. DB::Exception: Function toDecimal128 is not parametric: While processing toDecimal128(38)(1., 38): While executing ValuesBlockInputFormat: data for INSERT was parsed from query. (FUNCTION_CANNOT_HAVE_PARAMETERS) (version 23.8.2.7 (official build))
(query: INSERT INTO test VALUES (toDecimal128(38)(1., 38));)
```

Previous versions provide the generated value without any errors.

**How to reproduce**

* ClickHouse server version to use: 23.8.2.7

* Full query on 23.8.2.7 where error occurs:
https://fiddle.clickhouse.com/c82e39b2-6664-462a-8a46-fe8e613fe819

* The same query output on the 23.7.5.30 without any errors:
https://fiddle.clickhouse.com/fbbf62dd-5354-4413-9add-9e004bc2804b

**Comment by alexey-milovidov** [comment]
It was never the case. But previous versions could mistakenly accept parameters as no-op.
