### ISSUE TITLE
Wrong Materialized View content when combining with Distributed and ReplicatedAggregatingX engines

### ISSUE THREAD

**Issue by jeromefellus-sekoia** [ClickHouse/ClickHouse#54643]
We observed a weird behavior/(bug?) when combining `Distributed` tables pointing to `ReplicatedXXX` tables on which a `MaterializedView` is added. 

Consider the following architecture with a `Distributed` frontal sharding to some `ReplicatedXXX` tables on which a `Materialized View` has been setup to aggregate some columns with, say, basic summing. The picture bellow shows an even simpler layout where the destination table has a `Log` engine and the MV is a simple pass-thru : 

![image](https://github.com/ClickHouse/ClickHouse/assets/112865756/5f5ca086-ca7f-4f9a-80ed-b191b100e223)

* When INSERTing data via the Distributed table (red arrow) the values obtained in the destination Log table are **completely broken**. Yet the `ReplicatedAggregatingMergeTree`’s data is correct
We see the same issue when SELECTing from the Distributed tables : the output from a global SELECT over all nodes via the Distributed is **completely wrong**
* When INSERTing data via a random node’s `ReplicatedAggregatingMergetree` by **bypassing the `Distributed`** table, the counts of all local tables **do match** and a SELECT from the `Distributed` yields correct summed counts ! 🎉. This approach is similar to a setup where a front HAProxy would round-robin the destination node of INSERTS. Note that SELECTs aren’t affected by this problem

Note that the "bug" doesn't show up when either : 
* tables aren't replicated
* replica servers are down during INSERTion (only one "master" per shard remaining up)
* you don't use Distributed for INSERTion, but only for SELECTion

Is such architecture a misuse of the `Distributed`+`Replicated`+`MaterializedView` combination ? Or is it a known bug ? 

**Does it reproduce on recent release?**

It happens at least with current clickhouse:latest-alpine ([23.3.13.6-alpine](https://hub.docker.com/layers/clickhouse/clickhouse-server/23.3.13.6-alpine/images/sha256-09b21a5b0e17e6d3dab9cf37315d522c3eaa6f6d71c0df1b7d70f39d980fd7fe?context=explore)) and older `22.*` releases

**How to reproduce**

We've setup a minimal reproduction repo here : https://github.com/jeromefellus-sekoia/clickhouse-mv-with-distributed-and-replicated-issue

Don't hesitate if more background is needed 

Thank you !

**Comment by den-crane** [comment]
It is expected behaviour. You should use Replicated*MergeTree Engine instead of Log in this case.
Data needs to be replicated, engine Log does not replicate data.
See https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

Also Engine Log cannot be used in MatViews because it does support parallel write, and it cannot be used as persistent storage because it's durable and can lost data due insert failure or Clickhouse restart.

**Comment by den-crane** [comment]
>When INSERTing data via a random node’s ReplicatedAggregatingMergetree by bypassing the Distributed table, the counts of all local tables do match and a SELECT from the Distributed yields correct summed counts ! 🎉. This approach is similar to a setup where a front HAProxy would round-robin the destination node of INSERTS. Note that SELECTs aren’t affected by this problem

It works in this case because you have mis-configured your cluster.
You have missed internal_replication = true
https://clickhouse.com/docs/en/engines/table-engines/special/distributed#distributed-clusters
And Distributed table muliplexes insertion to all replicas.
It's eventually will produce duplicates in your replicated table, because you insert data twice.

**Comment by jeromefellus-sekoia** [comment]
Oh, ok thank you for taking the time to explain ! 
We indeed overlooked this `internal_replication` parameter

**Comment by jeromefellus-sekoia** [comment]
The documentation suggests to write to the local tables rather than to the `Distributed` for better perfs. Do you confirm we'll have easier times, when our cluster will grow very large, by letting our front loadbalancers picking a node for each worker session and write to local tables rather than letting Distributed tables do the job ?

**Comment by jeromefellus-sekoia** [comment]
https://simpl1g.medium.com/clickhouse-internal-replication-setting-b6d8c7c2a9f2
