### ISSUE TITLE
LOGICAL_ERROR from SettingsProfilesInfo::getProfileNames()

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#54656]
An undisclosed customer recently ran into this `LOGICAL_ERROR`:

```
Code: 49. DB::Exception: Unable to get profile name for 834b80a5-c274-88dd-9e7b-8e83274cbf85. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000ead79f7 in /usr/bin/clickhouse
1. ? @ 0x000000000914938d in /usr/bin/clickhouse
2. DB::SettingsProfilesInfo::getProfileNames() const @ 0x0000000013ab69cc in /usr/bin/clickhouse
3. DB::SessionLog::addLoginSuccess(StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag> const&, std::optional<String>, DB::Context const&, std::shared_ptr<DB::User const> const&) @ 0x00000000144bc5fb in /usr/bin/clickhouse
4. DB::Session::makeQueryContextImpl(DB::ClientInfo const*, DB::ClientInfo*) const @ 0x00000000144aff18 in /usr/bin/clickhouse
5. DB::TCPHandler::receiveQuery() @ 0x000000001567a57c in /usr/bin/clickhouse
6. DB::TCPHandler::receivePacket() @ 0x000000001567040e in /usr/bin/clickhouse
7. DB::TCPHandler::runImpl() @ 0x0000000015667890 in /usr/bin/clickhouse
8. DB::TCPHandler::run() @ 0x000000001567ef59 in /usr/bin/clickhouse
9. ? @ 0x000000000eba8dbc in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x0000000018687df4 in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000018689011 in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x0000000018812207 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001880fc3c in /usr/bin/clickhouse
14. ? @ 0x00007f05dc96fb43 in ?
15. ? @ 0x00007f05dca01a00 in ?
```

This is basically old issue #35952 for which supposed fix #42641 was made - the problem was super sporadic even back then, so the fix could not be reproduced/verified.

What happens is that during the creation of a session, `SettingsProfilesInfo::getProfileNames()` is called which eventually finds that its members `profiles` and `names_of_profiles` are out of sync. There was some speculation in #42641 how this could happen. Back then, everyone concluded that the only place which modifies (actually: creates) `SettingsProfilesInfo` is `SettingsProfilesCache::substituteProfiles()`. The locking is good, we can exclude races as cause (see the fancy figure in the other bug), I also quickly confirmed that the locking is still okay. `substituteProfiles()` will also not corrupt `SettingsProfilesInfo` in case of OOM or an exception, we are also safe from this side.

But: As I just see, both callers of `substituteProfiles()`

1. `getSettingsProfileInfo()`:
```cpp
info->profiles.push_back(profile_id);
info->profiles_with_implicit.push_back(profile_id);
substituteProfiles(elements, info->profiles_with_implicit, info->names_of_profiles);
```

2. `mergeSettingsAndConstraintsFor()`
```cpp
info->profiles = merged_settings.toProfileIDs();
substituteProfiles(merged_settings, info->profiles_with_implicit, info->names_of_profiles);
```

store something in `profiles` but they don't store something corresponding in `names_of_profiles`. There is a chance that this step corrupts `SettingsProfilesInfo` when `elements` resp. `merged_settings` is empty (as `substituteProfiles()` becomes a no-op then). Also, tbh., the code in `substituteProfiles()` itself also looks a bit strange (iterate the map while modifying it).

@vitlibar - maybe you like to double check (as author of the code)?

**Comment by vitlibar** [comment]
@rschu1ze Thank you for your investigation, it must help us to finally fix this issue!
