### ISSUE TITLE
Truncate tablle  hang in Shrinkage cluster

### ISSUE THREAD

**Issue by blockwolf** [ClickHouse/ClickHouse#54650]
Truncate tablle  hang in Shrinkage cluster, I stop old ck machine service(stop old replica)，help me!!! why difficulty to use ck?? it too unfriendly to users 
```[tasklist]
### Tasks
- [ ] https://github.com/ClickHouse/ClickHouse/pull/49351
```

**Comment by alexey-milovidov** [comment]
See https://github.com/ClickHouse/ClickHouse/issues/53567
