### ISSUE TITLE
When SELECT has many columns, the join algorithm 'full sorting merge' does not have better performance than 'hash join'

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#54661]
**Describe the situation**
When SELECT has many columns, the join algorithm 'full sorting merge' does not have better performance than 'hash join'

**How to reproduce**
Createt two table A and B with many columns, then run the SQL:
```
select A.*, B.* from A left join B on A.ref = B.id settings join_algorithm='full_sorting_merge'
```

**Additional context**
I think it is caused by merging sorting stage. The many column makes the number of bytes of each row in result rowset is big, the sortig algorithm would involve huge number of the operations of moving data among memory.

**Comment by Alex-Cheng** [comment]
BTW, I like the idea of merging join and hope it is as fast as possible and has better performance than "hash join".

**Comment by den-crane** [comment]
Why `full sorting merge` should have better performance than `hash` ? It needs to resort left table. 
I always expecte 10-100 times worse performance.
