### ISSUE TITLE
cosineDistance for vector Search

### ISSUE THREAD

**Issue by pragalbh-dev** [ClickHouse/ClickHouse#54666]
I was trying to use vector search through normalized embeddings from our model: 
The results seem to be a bit off as per the standard cosineDistance implementation which is  1-cosine_similarity.

Query : 
 res = conn.query_df('''SELECT
        company_id, company_name,
        L2Distance(vector, %s) AS score, vector
        FROM vector_table
        ORDER BY score asc limit 10'''%(json.dumps(embedder.encode_sentences(['query: food'])[0]))).head(10)
        
The output of cosine distance is more than one for some results, what is he function being used since it is different from the standard cosine distance formula.

**Comment by alexey-milovidov** [comment]
But your query uses L2Distance instead of cosineDistance.
See https://clickhouse.com/docs/en/sql-reference/functions/distance-functions#cosinedistance
