### ISSUE TITLE
A function to get HTTP headers from the current client's HTTP request

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#54665]
**Use case**

Obtain the relevant data when some application sends the data directly to ClickHouse without a separate backend.

```
CREATE TABLE test (something String DEFAULT getClientHTTPHeader('X-CloudFlare-WTF')) ...
```

Header names are case-insensitive. The function takes a constant String and returns a String.
Some headers such as X-ClickHouse-Password should be restricted.

**Describe the solution you'd like**

Save the header's map to ClientInfo, and then get it from the function.

**Comment by lingtaolf** [comment]
Could you let me try this ?

**Comment by alexey-milovidov** [comment]
@lingtaolf amazing, thank you!
