### ISSUE TITLE
Not enough privileges. ERROR: View with named collection at 23.8.1.2992

### ISSUE THREAD

**Issue by Ddolphh** [ClickHouse/ClickHouse#54673]
> You have to provide the following information whenever possible.

**Hi, 
We've got problem with named collections at version 23.8.1.2992:**

**What we have:**
4 shards, previous version is 22.3.17.13

**Our steps:**

**1. View creation with named collection on 1 shard** 
 ```
create view test as 
select * from postgresql(test_nc, table = 'test_table') 
where updated_at > ('2023-08-21 07:58:24')
```

**2. Trying to connect to this shard this function remote**

`select * from remote('clickhouse-shard....vc.cluster.local',`default`, test)`

3. **Got mistake**

`DB::Exception: default: Not enough privileges. To execute this query, it's necessary to have the grant NAMED COLLECTION ON test_nc. (ACCESS_DENIED) (version 23.8.1.2992 (official build))`

4. **Creation and checking dictionary above view** 

`create dictionary....on cluster 'default'`

Dictionary doesn't work too and it fells with the same mistake

**Our settings**
**1.**
```
<users>
    ...
    <zeus>
        <password></password> 
        <access_management>1</access_management>
        <named_collection_control>1</named_collection_control>
        <show_named_collections>1</show_named_collections>
        <show_named_collections_secrets>1</show_named_collections_secrets>
    </zeus>
</users>

```

2. **GRANT ALL * TO USER**

**Comment by den-crane** [comment]
> default: Not enough privileges.

user `default` does not have privileges to use named collection, check cluster description `remote_servers`.

The reason is this:
Imagine you have a very limited access to node clickhouse1 using user `u1`.
Now you install your clickhouse myclickhouse with full access and in this clickhouse you can define a cluster with clickhouse1 as a shard with `u1` as user for distributed queries, in this case you still will be able to run only queries which limited by minimal privileges of `u1` and the current user.

**Comment by Ddolphh** [comment]
@den-crane thanks for answer 

**default** is database, we use another new user

**Comment by Ddolphh** [comment]
> > default: Not enough privileges.
> 
> user `default` does not have privileges to use named collection, check cluster description `remote_servers`.
> 
> The reason is this: Imagine you have a very limited access to node clickhouse1 using user `u1`. Now you install your clickhouse myclickhouse with full access and in this clickhouse you can define a cluster with clickhouse1 as a shard with `u1` as user for distributed queries, in this case you still will be able to run only queries which limited by minimal privileges of `u1` and the current user.

Thanks for answer, @den-crane 

default is database, we use another new_user

Also as i've noticed before, we have all grants for new_user:

GRANT ALL ON *.* TO new_user WITH GRANT OPTION

So it didn't solve problem.

**Comment by Ddolphh** [comment]
> > default: Not enough privileges.
> 
> user `default` does not have privileges to use named collection, check cluster description `remote_servers`.
> 
> The reason is this: Imagine you have a very limited access to node clickhouse1 using user `u1`. Now you install your clickhouse myclickhouse with full access and in this clickhouse you can define a cluster with clickhouse1 as a shard with `u1` as user for distributed queries, in this case you still will be able to run only queries which limited by minimal privileges of `u1` and the current user.

@den-crane, thanks for answer

Our query is started by another user, not `default`, but as i see clickhouse tries to connect with `default` user or it's just regular mistake phrase.

One more example:

```
CREATE VIEW db.view_name AS
(
SELECT * FROM postgresql(xxx,
table = 'table_name')
)
```
`
**View that is based on named collection and created on one shard 
   Doesn't work**`

`SELECT * FROM remote('clickhouse-shard1-1...cluster.local',db.view_name )`


CREATE DICTIONARY db.dict_name
(
     `id` UUID,
     `title` String,
     `type` String,
     `is_banned` Bool
)
PRIMARY KEY id
SOURCE(POSTGRESQL(NAME xxx DATABASE 'xxx' TABLE 'table_name'))
LIFETIME(MIN 500 MAX 500)
LAYOUT(COMPLEX_KEY_HASHED());


**Dictionary that is based on named collection and created on one shard 
  Works**

` SELECT * FROM remote('clickhouse-shard1-1....cluster.local', db.dict_name)`

**Comment by den-crane** [comment]
Please share `remote_servers` config

**Comment by Ddolphh** [comment]
> Поделитесь пожалуйста `remote_servers`конфигом

<remote_servers>
    <default>
      <shard>
          <replica>
              <host>clickhouse-shard0-0....cluster.local</host>
              <port>9000</port>
              <user>my-user</user>
              <password>xxxx</password>
          </replica>
          <replica>
              <host>clickhouse-shard0-1...cluster.local</host>
              <port>9000</port>
              <user>my-user</user>
              <password>xxxx</password>
          </replica>
      </shard>
      <shard>
          <replica>
              <host>clickhouse-shard1-0....cluster.local</host>
              <port>9000</port>
              <user>my-user</user>
              <password>xxxx</password>
          </replica>
          <replica>
              <host>clickhouse-shard1-1...cluster.local</host>
              <port>9000</port>
              <user>my-user</user>
              <password>xxxx</password>
          </replica>
      </shard>
    </default>

**Comment by den-crane** [comment]
т.е. например текущий пользователь Вася, а запрос выполняется remote(. .... петя, пароль пети), то права на удаленной стороне будут минимальной комбинацией прав Васи и Пети и оба и Вася и Петя должны обладать
```
      <named_collection_control>1</named_collection_control>
        <show_named_collections>1</show_named_collections>
        <show_named_collections_secrets>1</show_named_collections_secrets>```

**Comment by den-crane** [comment]
все работает как и должно.

>Этот запрос, кстати, работает корректно:
>select * from remote('clickhouse-shard...vc.cluster.local',default.my_view, new_user, password)

ожидаемо. Тут используется new_user для remote и у new_user есть права named_collection_control

>А вот этот - нет:
>select * from remote('clickhouse-shard...vc.cluster.local',default.my_view)

ожидаемо. Тут используется default для remote с пустым паролем и у default нет прав named_collection_control
если вы не передаете, пользователь и пароль в remote функцию, автоматически используется user=default, password=''

>Также при понижении версии до 23.3 проблема с привилегиями уходит

ожидаемо, в версии 23.3 такие права не проверялись, это создавало проблему безопасности, которая была устранена в поздних версиях. https://github.com/ClickHouse/ClickHouse/pull/50625  https://github.com/ClickHouse/ClickHouse/issues/50277

**Comment by Guvanchhojamov** [comment]
Спасибо вам, очень помогли
