### ISSUE TITLE
Tables with hot & cold storage with move factor lead to spike in errors

### ISSUE THREAD

**Issue by Zarathustra2** [ClickHouse/ClickHouse#54694]
**Describe the unexpected behaviour**
(Sorry I could not come up with a better title)

Out of the blue I got the following errors:
```
DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::RoundRobinRuntimeQueue]: Code: 84. DB::Exception: Part directory /var/lib/clickhouse/disks/gcs/store/ef2/ef2025db-520c-4062-82b6-23ccde6221e5/202309_3791729_3792966_30/ already exists. (DIRECTORY_ALREADY_EXISTS) 
```

Some select queries were failing with this error. Retrying the select query then fixed it. 
```
DB::ErrnoException: Cannot open file /clickhouse-data/store/ef2/ef2025db-520c-4062-82b6-23ccde6221e5/202309_3791729_3792966_30/ot_ticker_exe_prj.proj/underlying_symbol.dict.bin, errno: 2, strerror: No such file or directory: (while reading column underlying_symbol): (while reading from part /clickhouse-data/store/ef2/ef2025db-520c-4062-82b6-23ccde6221e5/202309_3791729_3792966_30/ot_ticker_exe_prj.proj/ from mark 12 with max_rows_to_read = 24576): While executing MergeTreeThread. (FILE_DOESNT_EXIST)
```

I sent more logs related to this issue in private to @nellicus . I would appreciate if these raw logs are kept in private at clickhouse and not shared here in public. 

The table had the following definition
```
create table foo (
    ...
    PROJECTION ot_ticker_exe_prj
    (
        SELECT *
        ORDER BY
            underlying_symbol,
            executed_at
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(executed_at)
PRIMARY KEY executed_at
ORDER BY executed_at
TTL toDateTime(executed_at) TO VOLUME 'hot', toDateTime(executed_at) + toIntervalDay(7) TO VOLUME 'cold'
SETTINGS storage_policy = 'gcs_tiered', index_granularity = 8192
```

storage.yaml 
```
<clickhouse>
	<storage_configuration>
		<disks>
			<data1>
				<path>/clickhouse-data/</path>
			</data1>
			<gcs>
				<support_batch_delete>false</support_batch_delete>
				<type>s3</type>
				<endpoint>https://storage.googleapis.com/clickhouse-cold-storage/cold/</endpoint>
				<access_key_id></access_key_id>
				<secret_access_key></secret_access_key>
				<metadata_path>/var/lib/clickhouse/disks/gcs/</metadata_path>
			</gcs>
		</disks>
		<policies>
			<default>
				<volumes>
					<default>
						<disk>default</disk>
					</default>
					<data>
						<disk>data1</disk>
					</data>
				</volumes>
				<move_factor>0.2</move_factor>
			</default>
			<gcs_tiered>
				<volumes>
					<hot>
						<disk>data1</disk>
					</hot>
					<cold>
						<disk>gcs</disk>
					</cold>
				</volumes>
				<move_factor>0.2</move_factor>
			</gcs_tiered>
			<gcs>
				<volumes>
					<main>
						<disk>gcs</disk>
					</main>
				</volumes>
			</gcs>
		</policies>
	</storage_configuration>
</clickhouse>
```

This started to happen once the following happened:
- data1 storages fill up to 80%
- data1 continous to fill up (new rows of tables are written to data1)
- Clickhouse starts to download & sync spikes up because it has to download existing parts from GCS and merge them with the new parts and then upload the new merged part to GCS
- I am assuming the above error might be a rare race condition which only comes up when the syncs between clickhouse & GCS spike super hard

-----------------

I "fixed" it by:
- truncate affected table and reinsert data from another source (I had the same data in a postgres table)
- free up data1 disk or reduce move_factor (I am wondering if I would have done this early if the error would have fixed itself.)

**How to reproduce**
- Create a hot & cold (gcs) storage with move factor of 0.5
- Partition data by month
- Set TTL data to 1 day
- Insert data for current month until move factor reaches 0.5 and the sync to GCS is being forced by move factor
- CH will now download parts from GCS constantly to merge with current inserted parts from local disk and then push to GCS

( I did not test this above but believe this should reproduce the issue )

**Error message and/or stacktrace**
I sent the logs to @nellicus in a private chat.

**Additional context**

![image](https://github.com/ClickHouse/ClickHouse/assets/33396162/5254e722-5e9c-4cb1-947a-1c9f0d6b171c)
![image](https://github.com/ClickHouse/ClickHouse/assets/33396162/e2d29cc2-ac61-48c3-8885-431873876190)
![image](https://github.com/ClickHouse/ClickHouse/assets/33396162/040a1058-f4ba-4e2e-b90c-62f44ca8e815)

**Comment by den-crane** [comment]
>TTL toDateTime(executed_at) TO VOLUME 'hot', toDateTime(executed_at) + toIntervalDay(7) TO VOLUME 'cold'

BTW it should be `TTL toDateTime(executed_at) + toIntervalDay(7) TO VOLUME 'cold'`

**Comment by den-crane** [comment]
>ot_ticker_exe_prj.proj

But this bug has been fixed several months ago in 23.6
ClickHouse version?

**Comment by Zarathustra2** [comment]
I am on `23.2.4.12`, oh damn. Forgot to add to the ticket, will close the ticket then, thanks @den-crane! Have a great day

**Comment by sunny19930321** [comment]
https://github.com/ClickHouse/ClickHouse/issues/82382 I encountered the same problem, which should be caused by projection  @den-crane  May I ask which version it was fixed in? Is there any relevant PR
