### ISSUE TITLE
Remove Woboq Codebrowser

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#54723]
Woboq Codebrowser is an amazing tool, and I would be happy to continue publishing its results, but it is difficult to support because currently, the maximum LLVM version that it can use is 15, while ClickHouse uses 16 and preparing for LLVM 17.

**Comment by Felixoid** [comment]
Here's everything related:

- Hardcoded image from some PR, that can't be reproduced
- Issue about non-working clang 16 https://github.com/ClickHouse/ClickHouse/issues/50077
- The codebrowser "just" got compatibility with clang 16 https://github.com/KDAB/codebrowser/commit/caf31972d6a866f3c16cbde1960862bf9c0e16c1, and it's unknown if it will remain

As a "so-so" solution, we can stick forever to the image [49701-4dcdcf4c11b5604f1c5d3121c9c6fea3e957b605](https://github.com/ClickHouse/ClickHouse/pull/50197/files#diff-a515d3e5637f0e3fa440fdc98dc0088d7d8c0fc94aee04bf56b667b949ebd618R64) and try using it unless it will break forever. Then make another attempt to address the issue, and remove it completely unless it will work out.

Opinions?

**Comment by Felixoid** [comment]
Ok, @rschu1ze removes it in #53831
