### ISSUE TITLE
Adding partition creation time in system.parts table ?

### ISSUE THREAD

**Issue by mcarbonneaux** [ClickHouse/ClickHouse#5472]
major of time partition key are composite and cannote be used simply to purge the table...
system.parts modification time field can be modified by alter delete/update...

to simplify partition purge while by very usefull to have the partition creation time in system.parts table  in that way we can purge partition base on partition creation time.

in that way you can make generic ttl purge base on this field !

**Comment by alexey-milovidov** [comment]
You can use TTL expressions for this task. Look at the docs.

**Comment by mcarbonneaux** [comment]
It what you talk in my previous issue : https://github.com/yandex/ClickHouse/issues/4119#issuecomment-497542042?

**Comment by mcarbonneaux** [comment]
It's work based on partition creation or modification?

**Comment by filimonov** [comment]
What do you mean be part creation time? New part is created after each merge. Merges happen all the time. Probably you expect something different?

**Comment by mcarbonneaux** [comment]
partition are made generaly based on somefing based on time, but not directly on the time...
generaly they whant to remove the oldest created partition (not modified)...

generaly all information insert or merged are related to the time range of the partition key...

in system.parts you store the modification time (merge time y supose) but not the creation time of the partition (who correspond to the time of the first insert in the partition), merge time can be more recent than last insert in the table... but creation time correspond directly to the start of the time range of the partition key (if the partition key is time based)...  in that way they can be used to base the ttl of the partition in very fast way...

**Comment by den-crane** [comment]
There is no such entity like a partition on physical level in CH. It just an abstraction based on parts properties.

**Comment by filimonov** [comment]
@mcarbonneaux  it sounds like you need a column like `creation_time DateTime DEFAULT now()` and TTL based on that column.

**Comment by mcarbonneaux** [comment]
They sound like that... In fact the date of first insert in the partition... Or the first insert in parts.system table of the parts information ... With now() time... 

It's only useful when the partition key are based on time... But it's generally the case... 

OK It's indirect way to remove oldest partition in simply remove the oldest created partition based on this information without parsing table column.... But I think it's more fast than parsing column ...

Ok It's dyrty way to do but I think it's suffisant in most case...
