### ISSUE TITLE
server crash on arm，the reason as follows

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#54722]
<img width="1242" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/45587738/01d295e4-877e-400d-abbc-7dc6d4f448ec">

**Comment by nickitat** [comment]
it that is the only stack you see in logs? would be more interesting to learn the place where this exception cause a termination.

**Comment by alexey-milovidov** [comment]
It is a non-official build. We cannot support non-official ClickHouse builds where you or someone else has added bugs.

**Comment by alexey-milovidov** [comment]
Moreover, you attempted to hide the version number.

**Comment by den-crane** [comment]
anyway version 21.3.2.5 is obsolete, arm was not supported officially that time
