### ISSUE TITLE
S3 multi thread Reading does not work

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#54733]
See https://clickhousedb.slack.com/archives/CU478UEQZ/p1694647285875419

**Describe the situation**
No matter the core count (in the example above), once the number of `max_threads` exceeds the file count of parquet files in S3. queries do not perform better. with ~100-250MB files clickhouse should be able to fetch parts of files concurrently (row group size 112k, a rows in millions for most if not all files IIUC).

For example a 32 core machine with 12.5gbit nic at 128 threads is no faster than a 128 core machine with 170gbit nic reading from S3.

**How to reproduce**
* Which ClickHouse server version to use
any 23.8

**Expected performance**
When I go to 300 threads on a 128 core machine, I'd expect ~1/2 query time.

Also seems to happen with `s3Cluster` (no performance increase even with more cores and more interfaces)

**Comment by danthegoodman1** [comment]
Excerpt from slack:
---

Yeah interesting results. With a **32 core machine [m7a.8xlarge 12.5gbit]** I get

```
SELECT
    count(),
    `Payment Type`
FROM s3('https://s3.us-east-1.amazonaws.com/icedb-test-tangia-staging/chicago_taxis_1m/_data/**/*.parquet')
GROUP BY `Payment Type`
ORDER BY count() DESC
FORMAT `Null`

Query id: 6988363a-98b5-4b1a-8941-e03f19c07fa3

Ok.

0 rows in set. Elapsed: 2.364 sec. Processed 209.51 million rows, 3.54 GB (88.63 million rows/s., 1.50 GB/s.)
Peak memory usage: 316.68 MiB.
```

But if I do it with 128 threads I get

```
SELECT
    count(),
    `Payment Type`
FROM s3('https://s3.us-east-1.amazonaws.com/icedb-test-tangia-staging/chicago_taxis_1m/_data/**/*.parquet')
GROUP BY `Payment Type`
ORDER BY count() DESC
FORMAT `Null`
SETTINGS max_threads = 128

Query id: 9508f8dc-fedc-4638-9e39-d169bc046b74

Ok.

0 rows in set. Elapsed: 1.197 sec. Processed 209.51 million rows, 3.54 GB (175.05 million rows/s., 2.96 GB/s.)
Peak memory usage: 199.05 MiB.
```

Which are all hot runs. Cold run was a LOT slower

```
SELECT
    count(),
    `Payment Type`
FROM s3('https://s3.us-east-1.amazonaws.com/icedb-test-tangia-staging/chicago_taxis_1m/_data/**/*.parquet')
GROUP BY `Payment Type`
ORDER BY count() DESC
FORMAT `Null`

Query id: 1cd0bc1b-b94c-42c8-b0f9-1affc133d2a6

Ok.

0 rows in set. Elapsed: 8.600 sec. Processed 209.51 million rows, 3.54 GB (24.36 million rows/s., 411.96 MB/s.)
Peak memory usage: 321.15 MiB.
```

---

Cold run of **r6in.32xlarge [128 core 170gbit]**
```
SELECT
    count(),
    `Payment Type`
FROM s3('https://s3.us-east-1.amazonaws.com/icedb-test-tangia-staging/chicago_taxis_1m/_data/**/*.parquet')
GROUP BY `Payment Type`
ORDER BY count() DESC
FORMAT `Null`

Query id: 9b7c1985-232e-4e9e-a13a-58ca95796e34

Ok.

0 rows in set. Elapsed: 4.126 sec. Processed 209.51 million rows, 3.54 GB (50.78 million rows/s., 858.80 MB/s.)
Peak memory usage: 453.93 MiB.
```


Hot run:

```
SELECT
    count(),
    `Payment Type`
FROM s3('https://s3.us-east-1.amazonaws.com/icedb-test-tangia-staging/chicago_taxis_1m/_data/**/*.parquet')
GROUP BY `Payment Type`
ORDER BY count() DESC
FORMAT `Null`
SETTINGS max_threads = 128

Query id: 241ba99a-97ca-4ca9-8c68-8fd5b1dd28ed

Ok.

0 rows in set. Elapsed: 1.121 sec. Processed 209.51 million rows, 3.54 GB (186.89 million rows/s., 3.16 GB/s.)
Peak memory usage: 196.08 MiB.
```

Hot with more threads:

```
SELECT
    count(),
    `Payment Type`
FROM s3('https://s3.us-east-1.amazonaws.com/icedb-test-tangia-staging/chicago_taxis_1m/_data/**/*.parquet')
GROUP BY `Payment Type`
ORDER BY count() DESC
FORMAT `Null`
SETTINGS max_threads = 300

Query id: 3899b91b-fc87-4007-9248-2a783a8d0a95

Ok.

0 rows in set. Elapsed: 1.261 sec. Processed 209.51 million rows, 3.54 GB (166.20 million rows/s., 2.81 GB/s.)
Peak memory usage: 203.01 MiB.
```

**Comment by danthegoodman1** [comment]
As you can see 32cpu@128 threads == 128cpu@128 threads == 128cpu@300 threads

The dataset had ~186 files

**Comment by danthegoodman1** [comment]
I'm assuming it was the S3 listing that was killing cold runs

**Comment by danthegoodman1** [comment]
if any contributors want access to the bucket lmk

**Comment by al13n321** [comment]
Huh, parallel-reading from a single S3 file appears to be broken. I'll fix it tomorrow, unless @Avogar fixes it first.

(The difference is much more obvious on one big file, like `hits.parquet`. Reading it with s3() is many times slower than url().)

I also noticed that we don't reuse connections in s3() table function, so the query creates a new connection for each of the 2K reads. But I tried adding connection reuse, and the query didn't get noticeably faster, weird. I'll add it anyway, it's easy, and surely it'll be useful in other situations (especially cross-region).

**Comment by danthegoodman1** [comment]
Can WAIT to see that speed boost!!!

**Comment by danthegoodman1** [comment]
@al13n321 when you do, I would love to see the comparison on the queries we were testing on my chicago taxis data if you still have that set (keys I gave should still work too). I'm happy to test as well.

**Comment by al13n321** [comment]
Adding threads didn't make it any faster on my 32-core m5.8xlarge.

I tried to see how fast these ~2000 small S3 requests can be performed in isolation, in a small standalone program. The fastest was ~450 ms, plateaued for 1000-2000 threads (creating 1000 threads takes 100ms, which starts outweighing the gains from concurrency at some point), with the slowest request taking ~410 ms. The total time is very noisy, spiking to 2x longer every few runs. I guess the total speed is mostly determined by the outlier slow requests, and whether two of them happen to be assigned to the same thread.

Doing this query from tmpfs takes 0.9s. The original query from S3 takes 1.7s. I guess this is all in a reasonable ballpark, there's nothing broken, and no potential easy big improvements.

There's still the question why s3Cluster() doesn't seem to be any faster than s3() on this query. I'll probably look into that.

If you have control over the data encoding, consider using bigger row groups. Re-encoding each file with CH on default settings (output_format_parquet_row_group_size = 1M, output_format_parquet_row_group_size_bytes = 512 MiB) (just `INSERT INTO FUNCTION file(...) SELECT * FROM file(...)`) makes the query 40% faster for me, since it only needs ~540 S3 reads instead of ~2K.

**Comment by danthegoodman1** [comment]
@al13n321 so the latency is on time to first byte, not on first to last byte for a request then? Otherwise I wouldn’t understand how larger row groups would make it faster than smaller row groups with concurrent row group downloads.

why would s3 cluster be any faster if it’s not going to do concurrent single file downloads if the number of threads is exceeding the number of files on the single node?

**Comment by danthegoodman1** [comment]
And you’re saying going above 32 threads didn’t reduce query time for you? That’s different than what I observed

**Comment by al13n321** [comment]
> And you’re saying going above 32 threads didn’t reduce query time for you?

No. 32 -> 128 and 128 -> 184 both reduced query time, but 184 -> 400 didn't (with the fix, i.e. there were actually ~400 concurrent S3 requests).

**Comment by danthegoodman1** [comment]
But url() was faster?

**Comment by al13n321** [comment]
> so the latency is on time to first byte, not on first to last byte for a request then?

Yes:
```
avg wait: 86.136 ms
avg transfer: 3.3326 ms
max wait: 403.04 ms
max transfer: 112.4 ms
max total: 404.79 ms
```

Idk how it takes 86 ms, it's supposed to be in the same region (same datacenter?). Maybe it's on HDDs, and this is seek time, and S3 refuses to cache it? If so, 50 KB average read size is really too small.

(The rest of the output, at 1K threads:
```
total: 94.976 MiB, avg: 50.132 KiB, max: 83.771 KiB
create client: 7.0792 ms
create threads: 129.44 ms
requests: 315.53 ms
destructors: 0.51231 ms
total: 452.56 ms
```
)

> But url() was faster?

Didn't try it. My bucket doesn't have public access enabled, and now I tried to reconfigure it and ran into enough annoying bs AWS hurdles that I'm done with AWS and this task for now.

**Comment by danthegoodman1** [comment]
Thanks for these numbers, really helpful and makes sense. It’s still unclear to me how s3Cluster would be faster in this case? Maybe less time to make threads?

**Comment by al13n321** [comment]
Right, s3Cluster can't be much faster if the bottleneck is really the S3 servers, so maybe there's nothing left to investigate. (The query is still 2-3x slower than the raw S3 requests, and also I haven't tried it on beefier machines to confirm that it's really servers and not the client, but this seems close enough, and I'd like to move on now.)

**Comment by danthegoodman1** [comment]
Also what did you do to get those stats?
