### ISSUE TITLE
Exceeding the maximum limit of memory in ClickHouse

### ISSUE THREAD

**Issue by wang-qijia** [ClickHouse/ClickHouse#54736]
After starting the ClickHouse service, the memory usage gradually increases and eventually surpasses the memory limit, leading to read and write exceptions.

Here is the environment information I have:
* ClickHouse version: 22.8.4.7
* CPU, Memory: 16 cores, 32GB RAM
* ClickHouse cluster mode: 5-node cluster
* Table engine: ReplicatedMergeTree

Please refer to the following link for the monitoring information:

![image](https://github.com/ClickHouse/ClickHouse/assets/34878555/c318a44b-f113-43fc-b950-3b626fdf45d2)

My current solution is to restart the service node after it has been running for more than 20 days, which allows the memory to return to normal.

**Comment by rschu1ze** [comment]
The question is which type of memory allocation (e.g. merges, caches, queries, etc) is causing the memory usage pattern. To find out, you might want to check the server system tables (in particular `system.metrics`/`asynchronous_metrics`/`dictionaries`), see e.g. [here](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/).
