### ISSUE TITLE
Function `byteSwap`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#54734]
**Use case**

If a number was in big-endian instead of little-endian, or vice versa, convert it back.

Example:

Instead of writing:
```
SELECT toIPv4(reinterpretAsUInt32(reverse(reinterpretAsFixedString(3351772109))))
```

I want to write:
```
SELECT toIPv4(byteSwap(3351772109))
```

**Describe the solution you'd like**

Implement this function for integer types.

**Comment by Priyansh121096** [comment]
/assign

Hello, I'd like to work on this feature.

**Comment by alexey-milovidov** [comment]
@Priyansh121096 Thank you, this is very welcomed!

**Comment by Priyansh121096** [comment]
Hello, I've opened #55211 and have posted [some queries of mine](https://github.com/ClickHouse/ClickHouse/pull/55211#issuecomment-1743883195) in there. I would want to get those resolved before adding tests and marking the PR ready for review.

**Comment by Priyansh121096** [comment]
Hello, I've marked #55211 ready for review. Would love for someone to take a look! Hopefully it can be merged before October 31st for so that it gets counted towards my Hacktoberfest contributions. :)
