### ISSUE TITLE
Implement toMillisecond()

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#54746]
Implement a function `toMillisecond()`, similar to existing function `toSecond()` ([docs](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#tosecond)).

**Comment by shabroo** [comment]
I can't assign it to myself for some reason

**Comment by rschu1ze** [comment]
@Blargian The author of #55567 and #55569 decided to close the PRs.

It would be really nice if you would take a stab at this issue (I have assigned you). Feel free to set me as assignee (aka. reviewer) once you pushed a PR. Thanks!

**Comment by Blargian** [comment]
@rschu1ze Thanks for the fixes and your help! Would it be worth adding two additional functions `toMicroseconds`, `toNanoseconds`, or are these not likely to be a common use case?

**Comment by Blargian** [comment]
> These functions may have a low practical relevance but it is still worth to add them for the sake of consistency.

In that case I will add them and open a PR. May I assign you as reviewer when complete?

**Comment by rschu1ze** [comment]
Yes, please so. If you can't assign reviewers directly (perhaps because of permissions, don't know), please ping me.
