### ISSUE TITLE
ClickhHouse Date type error

### ISSUE THREAD

**Issue by akbarali1** [ClickHouse/ClickHouse#54749]
Date at Clickhouse has been supporting adults since 1970. But I also have users born before 1970. When I save to database they are stored as "2143-06-07".

Are there other variants of Date?

**Comment by akbarali1** [comment]
As far as I know Clickhouse does not have Time and Timestep. Or am I wrong?

**Comment by melvynator** [comment]
I will confirm but I think the Date and Date32 should support as low as 1900 now: https://github.com/ClickHouse/ClickHouse/issues/38393

**Comment by melvynator** [comment]
```
CREATE TABLE date_example
(
    `timestamp` Date32,
    `event_id` UInt8
)
ENGINE = MergeTree()
ORDER BY tuple();

INSERT INTO date_example VALUES ('1901-01-01', 1), ('2200-01-01', 2);

SELECT * FROM date_example;
```
```
┌──timestamp─┬─event_id─┐
│ 1901-01-01 │        1 │
│ 2299-01-01 │        2 │
└────────────┴──────────┘

2 rows in set. Elapsed: 0.005 sec.
```
```
INSERT INTO date_example VALUES ('1899-01-01', 3), ('2300-01-01', 4);

SELECT * FROM date_example;
```

```
┌──timestamp─┬─event_id─┐
│ 1900-01-01 │        1 │
│ 2299-12-31 │        2 │
│ 1901-01-01 │        3 │
│ 2299-01-01 │        4 │
└────────────┴──────────┘

4 rows in set. Elapsed: 0.022 sec.
```

Unless I'm missing something @den-crane ? Or misunderstanding the question?

**Comment by den-crane** [comment]
>Unless I'm missing something @den-crane ? Or misunderstanding the question?

IDNK

Date32 is able to fit 4294967296 days, ~11767033 years.

Date is able to fit 65635 days, 65635 / 365 = 179 years.
