### ISSUE TITLE
Comparison error between Float  (passing the cast function) and Float64 (literal defaultly)

### ISSUE THREAD

**Issue by awakeljw** [ClickHouse/ClickHouse#54751]
**Describe the unexpected behaviour**
:) select cast('90.2' as float) = 90.2;

SELECT CAST('90.2', 'float') = 90.2

┌─equals(CAST('90.2', 'float'), 90.2)─┐
│                                   0 │
└─────────────────────────────────────┘

1 row in set. Elapsed: 0.016 sec.

:) select cast('90.2' as double) = 90.2;

SELECT CAST('90.2', 'double') = 90.2

┌─equals(CAST('90.2', 'double'), 90.2)─┐
│                                    1 │
└──────────────────────────────────────┘

1 row in set. Elapsed: 0.018 sec.

**Expected behavior**
Literral is converted to Float64 by default, so when compare Float32 with  Float64 ，it will lost accuracy.

**Comment by tavplubix** [comment]
It's expected. Usually, comparing floats with `=` is an antipattern, consider using smth like `abs(f1 - f2) < eps`
