### ISSUE TITLE
some workarounds for memory limit (for query) exceeded error

### ISSUE THREAD

**Issue by furkankahvecinsider** [ClickHouse/ClickHouse#54752]
I have a query that gives a memory limit exceed error.

`code: 241, message: Memory limit (for query) exceeded: would use 46.57 GiB (attempt to allocate chunk of 4205532 bytes), maximum: 46.57 GiB. OvercommitTracker decision: Memory overcommit isn't used. OvercommitTracker isn't set.: While executing AggregatingTransform`

We are using version 22.8 of Clickhouse.

I saw in [the issue](https://github.com/ClickHouse/ClickHouse/issues/42307) that MemoryTracker is calculating extra memory than it should.

1) Could this problem be happening in version 22.8? 
2) If it does, can I set `max_server_memory_usage_to_ram_ratio` more than 1? If I set this setting this way, will it cause problems for the machine because it will start using extra memory?
3) If this problem is solved, is there any other way other than increasing memory?

**Comment by furkankahvecinsider** [comment]
There are only a few group by, no order by and join.

I don't understand what I'll get if I upgrade to version 23.8.

**Comment by den-crane** [comment]
>I don't understand what I'll get if I upgrade to version 23.8.

community support

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/settings/query-complexity#settings-max_bytes_before_external_group_by

**Comment by furkankahvecinsider** [comment]
what should be the value of this, when the value is 1, will it use less memory?

**Comment by den-crane** [comment]
set max_bytes_before_external_group_by='25G';
