### ISSUE TITLE
Clickhouse server not honoring hot-cold policy 

### ISSUE THREAD

**Issue by thedeceptio** [ClickHouse/ClickHouse#54762]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I am repeatedly seeing the following error in the error logs 
2023.09.18 20:53:19.353221 [ 15247 ] {} <Error> void DB::BackgroundJobsAssignee::threadFunc(): Code: 243. DB::Exception: Not enough space for mutating part ''. (NOT_ENOUGH_SPACE), Stack trace (when copying this message, always include the lines below):

**How to reproduce**
I have a hold cold architecture with a table having the TTL with the following expression  
`TTL createdAt TO VOLUME 'hot_volume', createdAt + toIntervalMonth(1) TO VOLUME 'cold_volume'`
hot volume is my local SSD and cold is an S3 Bucket.  Before today this system was being followed perfectly
I used to check it with the following query 
`SELECT
    disk_name, partition,  sum(bytes) / (1024*1024*1024) as size_in_GB
FROM system.parts
WHERE (table = 'TableName') AND (active = 1)
group by disk_name, partition 
order  by partition`
 
But now I am repeatedly seeing weird errors like above, my inserts are failing occasionally.  and the data which is supposed to be in the HOT volume only is distributed between hot and cold volume in arbitrary manner. 

* Which ClickHouse server version to use  23.5.2.7 
* Non-default settings, if any
* ` <storage_configuration>
        <disks>
            <default>
            </default>
          <s3>
                <type>s3</type>
                <endpoint>S3_URL/</endpoint>
                <access_key_id>SECRET</access_key_id>
                <secret_access_key>SECRET</secret_access_key>
          </s3>
        </disks>
        <policies>
           <hot_cold>
                <volumes>
                    <hot_volume>
                        <disk>default</disk>
                    </hot_volume>
                    <cold_volume>
                        <disk>s3</disk>
                    </cold_volume>
                </volumes>
            </hot_cold>
        </policies>
    </storage_configuration>`
* `CREATE TABLE` statements for all tables involved
* `  CREATE TABLE default.TABLENAME
(
    `id` Int64,
    `col1` String,
    `col2` Int32,
    `col3` String,
    `col4` String,
    `col5` String,
    `col6` String,
    `col7.key` Array(String),
    `col7.value` Array(String),
    `col8` String,
    `col9` String,
    `createdAt` DateTime,
    `updatedAt` DateTime,
    `col10` Int32
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(createdAt)
ORDER BY (createdAt, col2)
TTL createdAt TO VOLUME 'hot_volume', createdAt + toIntervalMonth(3) TO VOLUME 'cold_volume'
SETTINGS storage_policy = 'hot_cold', index_granularity = 8192`

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result - Its not specific to queries being run

**Expected behavior**
I want my TTL expression to be honored 

**Error message and/or stacktrace**
`2023.09.18 20:53:19.353221 [ 15247 ] {} <Error> void DB::BackgroundJobsAssignee::threadFunc(): Code: 243. DB::Exception: Not enough space for mutating part ''. (NOT_ENOUGH_SPACE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e3453d5 in /usr/bin/clickhouse
1. ? @ 0x0000000008b65a23 in /usr/bin/clickhouse
2. DB::CurrentlyMergingPartsTagger::CurrentlyMergingPartsTagger(std::shared_ptr<DB::FutureMergedMutatedPart>, unsigned long, DB::StorageMergeTree&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, bool) @ 0x0000000014b514f4 in /usr/bin/clickhouse
3. DB::StorageMergeTree::selectPartsToMutate(std::shared_ptr<DB::StorageInMemoryMetadata const> const&, String*, std::shared_ptr<DB::RWLockImpl::LockHolderImpl>&, std::unique_lock<std::mutex>&) @ 0x0000000014b5b08e in /usr/bin/clickhouse
4. DB::StorageMergeTree::scheduleDataProcessingJob(DB::BackgroundJobsAssignee&) @ 0x0000000014b5c4e3 in /usr/bin/clickhouse
5. DB::BackgroundJobsAssignee::threadFunc() @ 0x000000001472bca7 in /usr/bin/clickhouse
6. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x0000000012aa3982 in /usr/bin/clickhouse
7. DB::BackgroundSchedulePool::threadFunction() @ 0x0000000012aa6eaa in /usr/bin/clickhouse
8. ? @ 0x0000000012aa7cee in /usr/bin/clickhouse
9. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e4191f4 in /usr/bin/clickhouse
10. ? @ 0x000000000e41e9e1 in /usr/bin/clickhouse
11. start_thread @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
12. clone @ 0x00000000000feb0d in /usr/lib64/libc-2.17.so
 (version 23.5.2.7 (official build))`

**Comment by den-crane** [comment]
>TTL createdAt TO VOLUME 'hot_volume', createdAt + toIntervalMonth(1) TO VOLUME 'cold_volume'

this is incorrect.
use this `TTL createdAt + toIntervalMonth(1) TO VOLUME 'cold_volume'

**Comment by den-crane** [comment]
>NOT_ENOUGH_SPACE
>But now I am repeatedly seeing weird errors like above, my inserts are failing occasionally. and the data which is supposed to be in the HOT volume only is distributed between hot and cold volume in arbitrary manner.

This is expected. If there is no free space at the volume with low priority (see `move_factor` documentation), then inserts and merges are moved to volumes higher priorities.

**Comment by thedeceptio** [comment]
I have not set the move_factor. I was trying to manage storage based on the TTL expression. does the move factor defaults to 0.9 if not set ?

**Comment by den-crane** [comment]
>does the move factor defaults to 0.9 if not set ?

./en/engines/table-engines/mergetree-family/mergetree.md:- `move_factor` — when the amount of available space gets lower than this factor, data automatically starts to move on the next volume if any **(by default, 0.1)**. ClickHouse sorts existing parts by size from largest to smallest (in descending order) and selects parts with the total size that i
