### ISSUE TITLE
Alias is Null

### ISSUE THREAD

**Issue by GanBob** [ClickHouse/ClickHouse#54777]
table Fields
seq_id Int64
date Int64
stat_time Int64
...

sql:select toTimeZone(toDateTime(date/1000),'Asia/Shanghai') as stat_time from table
version:21.10.2.1
the stat_time not null
version:23.6.2.18
the stat_time is null
Howerver,I set the alias 'stat_time' in other which the table‘s fields don’t contain,the result is not null.
What should I do to adapt？please help.

**Comment by rschu1ze** [comment]
Hi @GanBob , please provide a minimal reproducible SQL example, right now it is not clear what the actual problem is.

**Comment by den-crane** [comment]
no info
