### ISSUE TITLE
WHERE-clause with two ORs doesn't evaluate to true

### ISSUE THREAD

**Issue by slanderous-mambo** [ClickHouse/ClickHouse#54779]
**What's wrong**

Hello. We encountered a regression in some of our queries after upgrading Clickhouse from 23.7 to 23.8. Now, inside a WHERE-clause a three-literal or-clause doesn't get evaluated right if two of the clauses are always false and one is sometimes true.

**Does it reproduce on recent release?**

Every release starting with 23.8

**How to reproduce**

```
CREATE TABLE or_bug (column_1 UInt8) ENGINE=MergeTree ORDER BY column_1;

INSERT INTO TABLE or_bug VALUES (0), (1);

SELECT * FROM or_bug WHERE (column_1 = 1) OR false OR false;

Ok.

0 rows in set. Elapsed: 0.001 sec.
```

Same behavior with fiddle (using versions >= 23.8): https://fiddle.clickhouse.com/424f3fbf-58db-4b3a-b1c8-f4a287a9bf05

**Expected behavior**

Clickhouse should (and did with 23.7) instead return

```
┌─column_1─┐
│        1 │
└───────────
```

**Additional context**

Note that this doesn't happen with `ENGINE=Memory` and only happens with two times "OR false", not one or three times "OR false".

**Comment by SaltTan** [comment]
Not fixed in 'head' https://fiddle.clickhouse.com/9345c830-4bd3-401b-87cd-0507ed6e000e

**Comment by slanderous-mambo** [comment]
I came around to bisecting this and the first bad commit seems to be https://github.com/ClickHouse/ClickHouse/commit/68aed0d.

Could someone with better understanding than me take a look?

**Comment by den-crane** [comment]
cc @azat

**Comment by azat** [comment]
> I came around to bisecting this and the first bad commit seems to be https://github.com/ClickHouse/ClickHouse/commit/68aed0d.

Hi @slanderous-mambo, thanks for bisect!

> Could someone with better understanding than me take a look?

Here is a fix - https://github.com/ClickHouse/ClickHouse/pull/55418

P.S. @den-crane thanks for tagging me

P.P.S. BTW you can surely tag commit author by yourself.
