### ISSUE TITLE
string distance functions

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#54784]
I would like standard string distance functions to be implemented.

**DuckDB**  implements the following. If I may selfishly request, I would also love longest common substring. 

Also ngramDistance is great, wondering if it's possible to choose the n in n-grams?

![image](https://github.com/ClickHouse/ClickHouse/assets/8321252/ae833830-ca66-4bbc-a333-0c70c8007da7)

**Comment by raaz252** [comment]
I would like to look into this
