### ISSUE TITLE
the problem submit query in system.process and not in system.query_log

### ISSUE THREAD

**Issue by zzl870123** [ClickHouse/ClickHouse#54782]
I have submit one query (create table) from clickhouse-client. after long time the table dosn‘t created. Then I find this sql in system.process , and I want find sql in query_log how long it takes. But I havn’t query in system.query_log.
Have any one know it ? thx

**Comment by alexey-milovidov** [comment]
`system.query_log` records the query start and finish events, while `system.processes` shows the currently running queries.

**Comment by zzl870123** [comment]
> `system.query_log` records the query start and finish events, while `system.processes` shows the currently running queries.

it means when query doing  just in `system.processes`  not in `system.query_log` ?
but i try another create table statement  when it doing,  also in `system.query_log` but  just have on record that query start.

**Comment by zzl870123** [comment]
> `system.query_log` records the query start and finish events, while `system.processes` shows the currently running queries.

it means when query doing  just in `system.processes`  not in `system.query_log` ?
but i try another create table statement  when it doing,  also in `system.query_log` but  just have on record that query start.
