### ISSUE TITLE
Make toTime accept string argument

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#5481]
```
SELECT toTime('23:59:59')

Received exception from server (version 19.6.2):
Code: 43. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Illegal type String of argument of function toTime. Should be a date or a date with time. 
```
The only supported format for string conversion needed  - is time only (without date part).

Currently you can use something like `toTime(timestamp) <= toTime( toDateTime('2000-01-01 11:59:59') )` but it's unnessecary complex and makes query look wierd (like they engage some strange dates)

**Comment by filimonov** [comment]
Related #979

**Comment by alexey-milovidov** [comment]
This function would be very weird and non intuitive unless we have Time data type.
And we don't have the Time data type.

Maybe `SELECT toTime('1970-01-01 23:59:59')`?
