### ISSUE TITLE
Create projection for MergeTree

### ISSUE THREAD

**Issue by senekis** [ClickHouse/ClickHouse#54814]
**Describe the issue**
Creating projections for a MergeTree table was working well in the version `v23.3.8.21-lts` but now it is returning the error 

```
Sorting key contains nullable columns, but merge tree setting `allow_nullable_key` is disabled
```

**How to reproduce**
```sql
CREATE TABLE sales (
	DATE_SOLD DateTime64(3, 'UTC'),
	PRODUCT_ID Nullable(String),
) 
Engine MergeTree()
PARTITION BY toYYYYMM(DATE_SOLD)
ORDER BY DATE_SOLD
```

then create the projection
```sql
ALTER TABLE sales
    ADD PROJECTION test
    (
        SELECT toInt64(COUNT(*))
        GROUP BY
            PRODUCT_ID,
            DATE_SOLD
    )
```
It should create the projection, but instead is returning an error

* Which ClickHouse server versions are incompatible
Working versions: `23.3.8.21` and `23.5.1`
Broken in the version `23.8.2.7`

**Error message and/or stacktrace**
```
Received exception from server (version 23.8.2):
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Sorting key contains nullable columns, but merge tree setting `allow_nullable_key` is disabled. (ILLEGAL_COLUMN)
```

**Comment by markandrus** [comment]
- [Works in 23.6.3.87](https://fiddle.clickhouse.com/cb9a6573-375b-4a6f-bd48-4da94d0e1462)
- [Fails in 23.7](https://fiddle.clickhouse.com/e5afc13e-b4ef-4d6d-81b7-eefca127e23f)

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/52361  . We can relax the check for projections.
