### ISSUE TITLE
Should be seconds instead of days in the documentation of Date type

### ISSUE THREAD

**Issue by freakynit** [ClickHouse/ClickHouse#54820]
Docs link: https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/data-types/date.md

Instead of `Stored in two bytes as the number of days since`, it should be `Stored in two bytes as the number of seconds since`.

**Comment by UnamedRus** [comment]
Why?

It's 2 byte number, it can't fit number of seconds since epoch, only days

**Comment by freakynit** [comment]
In that case this example given below on same page needs to be updated:
```sql
INSERT INTO dt VALUES (1546300800, 1), ('2019-01-01', 2);
```
`1546300800` is in seconds in this, not days.

**Comment by UnamedRus** [comment]
>1546300800 is in seconds in this, not days.

Because it can do "smart" cast, if it's something big and looks like UnixTimestamp, ClickHouse will reinterpret it as UnixTimestamp

**Comment by freakynit** [comment]
Hmmm... but as someone who has just started with clickhouse, this can cause confusion... We can keep this as-is, but add what you just told me in your comment in doc itself. What you think?

**Comment by den-crane** [comment]
> Hmmm... but as someone who has just started with clickhouse, this can cause confusion... We can keep this as-is, but add what you just told me in your comment in doc itself. What you think?

Such behaviour was implemented to make it easier for newbies because they have struggles with an overflow 

```
 select toDate(toUInt16(1546300800));
┌─toDate(toUInt16(1546300800))─┐
│                   2091-08-10 │
└──────────────────────────────┘
```
