### ISSUE TITLE
Per-column compression block size

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#54821]
> (you don't have to strictly follow this form)

**Use case**

When table has a big string column and we want to explicitly set a big compression block size for that column.

**Describe the solution you'd like**

```
CREATE TABLE t
(
        ...
        big_column String CODEC(ZSTD(1)) COMPRESSION BLOCK (min_block_size, max_block_size)
)
ENGINE = MergeTree ORDER BY tuple();
```

**Describe alternatives you've considered**

Tuning `min_compress_block_size` and `max_compress_block_size` but it's hard to get the optimal compression ratio for the big columns without using big compression block size. E.g.

```
CREATE TABLE t
(
        ... /*all small columns*/
        big_column String CODEC(ZSTD(1)) COMPRESSION BLOCK (min_block_size, max_block_size)
)
ENGINE = MergeTree ORDER BY tuple() SETTINGS min_compress_block_size = 67108864, max _compress_block_size = 67108864;
```
--> good compression ratio, but reading all columns costs too much memory.

```
CREATE TABLE t
(
        ... /*all small columns*/
        big_column String CODEC(ZSTD(1)) COMPRESSION BLOCK (min_block_size, max_block_size)
)
ENGINE = MergeTree ORDER BY tuple() SETTINGS min_compress_block_size = 16384, max _compress_block_size = 67108864;
```
---> compression ratio reduced by 30%

**Additional context**

[Greenplum](https://greenplum.org/10-examples-of-compression-enablement-in-greenplum/) can do it as:

```
CREATE TABLE t 
(
        c1 int ENCODING (compresstype=zstd),
        c2 char ENCODING (compresstype=zlib, blocksize=65536),
        c3 char
) WITH (orientation=column);
```

**Comment by UnamedRus** [comment]
Also, it can make sense to do for other "user-level" settings as well:

https://github.com/ClickHouse/ClickHouse/issues/36428

**Comment by canhld94** [comment]
> Also, it can make sense to do for other "user-level" settings as well

We will need to examine the `MergeTreeSettings`. If there's many settings that make senses to override at column level, then we will need a general framework for this.
