### ISSUE TITLE
OPTIMIZE table ... FORCE TTL command

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#5486]
Motivation: for big table doing FINAL is an overkill, waiting for next check of ttl can take lot of time (if table was created with big recheck interval), it would be nice to have a possibility to make TTL cleanup on demand. 

P.S. Not sure about name. Probably FORCE TTL could be ok

/cc @CurtizJ

**Comment by inv2004** [comment]
We need it.

**Comment by champtar** [comment]
It would also be nice to have a way to update the current TTL of parts, for example TTL was set to 6 month, then ALTERed to 1 year, if I understand correctly right now data created before the ALTER will be deleted after 6 months, which is not what is expected IMO

**Comment by CurtizJ** [comment]
Long time ago query `ALTER TABLE ... MATERIALIZE TTL` was introduced. #8775.
