### ISSUE TITLE
StorageTinyLog compatibility issue: there is no element 'yandex' in object 

### ISSUE THREAD

**Issue by T-M-L-C** [ClickHouse/ClickHouse#54867]
When the ClickHouse database downgrade 22.8.11.1 to 21.8.8.1, the yandex element does not exist in the object. Is there any workaround for this scenario?

**Comment by den-crane** [comment]
22.8.11.1 , 21.8.8.1 both out of support.

StorageTinyLog -- cannot be used as a permanent storage. It's not durable.

**Comment by T-M-L-C** [comment]
Sorry, my description is a little wrong. Actually, the storage engine I'm experiencing is StorageDistributed.In this case, we do not change the database version. How can we solve the current database downgrade problem? [<Error> Application: JSONException: JSON: there is no element 'yandex' in object.]
