### ISSUE TITLE
Cannot convert string 1999-1-1 00:00:00 to type DateTime64(3)

### ISSUE THREAD

**Issue by chenxin57085122** [ClickHouse/ClickHouse#54875]
Hello, I changed `date_time_input_format` to best_effort.

Schema

```
CREATE TABLE default.datetime64_test
(
    `occur_time` DateTime64(3),
)
ENGINE = MergeTree
ORDER BY occur_time
SETTINGS index_granularity = 8192;
```

Inserting data:

```
insert into default.datetime64_test(occur_time) values ('1999-1-1 00:00:00');
```

The failing query :

```
select * from default.datetime64_testwhere occur_time='1999-1-1 00:00:00';
````

Code: 53. DB::Exception: Received from localhost:29010. DB::Exception: Cannot convert string 1999-1-1 00:00:00 to type DateTime64(3): while executing 'FUNCTION equals(occur_time : 0, '1999-1-1 00:00:00' : 1) -> equals(occur_time, '1999-1-1 00:00:00') UInt8 : 2'. (TYPE_MISMATCH)

Expected result - no error (1 row match)

clickhouse version 23.3.14.1

**Comment by den-crane** [comment]
it's expected behaviour.

You should use either `occur_time='1999-01-01 00:00:00'` 
or `occur_time=parseDateTimeBestEffort('1999-1-1 00:00:00')`

**Comment by chenxin57085122** [comment]
thanks!

But why can this data YYYY-M-D HH:mm:ss be written directly, but also need to be converted when it is a query condition
