### ISSUE TITLE
ReplacingDeletingMergeTree

### ISSUE THREAD

**Issue by AliALS9** [ClickHouse/ClickHouse#54880]
**Use case**

Systems where rows are updated/deleted/re-created frequently, Without the need to know existing versions (VersionedCollpasingMergeTree). Specifically even-driven observing-based systems. 

**Describe the solution you'd like**

I would like that a new flavor of the ReplacingMergeTree to be introduced, where the highest version is always respected but also the state of the highest version reflects on itself and the versions older than it. Assuming the column ```is_deleted``` is used, then the difference in behavior to the existing ReplacingMergeTree is during the merge process/final/optimize, the evaluation of the ```is_deleted``` relates not to the state of the row but more to the state of the whole sorting key and older versions.

Example of the requested feature/behavior

```
CREATE Table t
(
userId UInt64,
ver UInt8,
is_deleted Int8
)
ENGINE = ReplacingDeletingMergeTree(ver, is_deleted)
ORDER BY userId;
```
And we do the following inserts

``` 
INSERT INTO t VALUES (1, 3, 0);
INSERT INTO t VALUES (2, 1, 0);
INSERT INTO t VALUES (2, 2, 1);
INSERT INTO t VALUES (1, 4, 0);
INSERT INTO t VALUES (1, 2, 0);
INSERT INTO t VALUES (1, 1, 0);
INSERT INTO t VALUES (3, 1, 0);
INSERT INTO t VALUES (3, 3, 0);
INSERT INTO t VALUES (3, 2, 1);
```

After inserting we query 
```
SELECT * FROM t FINAL; 
```

Returns 
(1, 4, 0)
(3, 3, 0)

**Describe alternatives you've considered**

A Workaround is to use a ReplacingMergeTree with an added column ```deleted```, and for every query do ```WHERE deleted != 1``` and do  ``` DELETE FROM t WHERE deleted = 1``` periodically.  While it works I feel this is not elegant or convenient, since we are adding a flag to every query that has nothing to do with the actual data content, and we are scheduling deletes from the App layer. So we are somewhat managing the DB layer from the App Layer.

**Additional context**

I believe the solution is straightforward, and I'm sure others facing the same situation would appreciate it if it was implemented.

Thank you.

**Comment by UnamedRus** [comment]
Already exist

https://github.com/ClickHouse/ClickHouse/pull/41005
