### ISSUE TITLE
archive data from mysql with MaterializedMySQL

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#54884]
Is it possible to use MaterializedMySQL to only save deleted data from mysql?

case: I archive old data from mysql in batches, usually use tool like pt-archiver, and save archived data into files, but now I want to save these data into clickhouse.

In this case, I want MaterializedMySQL only capture DDL queries and delete query, and use MergeTree engine. if so, it is much faster to archive data than pt-archiver.

**Comment by alexey-milovidov** [comment]
We don't support MaterializedMySQL.
