### ISSUE TITLE
farmhash function should use stable Fingerprint64 not transient Hash64 api

### ISSUE THREAD

**Issue by ygrek** [ClickHouse/ClickHouse#5488]
farmhash has two family of functions - transient Hash* functions without any guarantees on result compatibility between platform/versions/etc and persistent Fingerprint* that are guaranteed to provide same result. Quoting their README : 
```
Our belief is that the typical hash function is mostly used for in-memory hash
tables and similar.  That use case allows hash functions that differ on
different platforms, and that change from time to time.  For this, I recommend
using wrapper functions in a .h file with comments such as, "may change from
time to time, may differ on different platforms, and may change depending on
NDEBUG."

Some projects may also require a forever-fixed, portable hash function.  Again
we recommend using wrapper functions in a .h, but in this case the comments on
them would be very different.
```

I believe clickhouse usecase falls into the second category and [Fingerprint64](https://github.com/google/farmhash/blob/master/src/farmhash.h#L151) should be used, either in place of current implementation or add one more function, please.

**Comment by ygrek** [comment]
btw current farmHash64 function actually (luckily) evaluates to Fingerprint64 because contrib/libfarmhash is not compiled with SSE enabled afaics and libfarmhash uses same implementation for Fingerprint64 and Hash64 so this change will be not noticeable in practice, would be nice to set this in stone and use Fingerprint64 explicitly.

**Comment by JacobHayes** [comment]
This would be great to guarantee (we're starting to generate and load data into clickhouse with fingerprints from other systems). I'll try to add a `farmFingerprint64` like [this one](https://github.com/ClickHouse/ClickHouse/blob/5e29fe3425a6dcb331a7a7abdb2d2973e4685d65/dbms/src/Functions/FunctionsHashing.h#L434-L444) in the next few days if this would be considered.

**Comment by alexey-milovidov** [comment]
@JacobHayes Let's do it.

**Comment by alexey-milovidov** [comment]
@ygrek It's Ok for farmHash64 function in ClickHouse to be non stable between different machines / releases if it will be clearly stated in docs.
