### ISSUE TITLE
assumeNotNull(null) not work after version 22.5

### ISSUE THREAD

**Issue by ltylty** [ClickHouse/ClickHouse#54888]
``` sql
SELECT sum( if( number = 1, 5, assumeNotNull(null) ) ) from numbers(1, 10)
```
this sql is ok on version 22.5 , but not work after version 22.5

![图片](https://github.com/ClickHouse/ClickHouse/assets/7252320/7c993307-bb93-4cf7-9b11-4284993f0978)

![图片](https://github.com/ClickHouse/ClickHouse/assets/7252320/41906c55-d6b2-45d6-bc3d-9b0f09aa2d20)

**Comment by den-crane** [comment]
it never worked correctly. https://fiddle.clickhouse.com/cff3b0d3-8bbe-44a1-b321-0bba8f2bbb3c

You should use `defaultValueOfArgumentType`  https://fiddle.clickhouse.com/77accc27-096a-4271-b5d1-439675d7315d
