### ISSUE TITLE
Exception. Code: 1000, e.code() = 104, Connection reset by peer

### ISSUE THREAD

**Issue by FriskKiddo** [ClickHouse/ClickHouse#54885]
I run the command    "clickhouse-client --host=127.0.0.1 --port=9000 --user=ck --password=ck123" and occur a error below:
ClickHouse client version 23.7.1.2470 (official build).
Connecting to 127.0.0.1:9000 as user ck.
Code: 210. DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000). (NETWORK_ERROR)

I restart the clickhouse process and the command worked. However, the above problem will still occur after a period of time.

And the command "echo "show databases" | curl 'http://localhost:8123/?user=ck&password=ck123' -d @-" can work

**Comment by den-crane** [comment]
upgrade to 23.7.5.30-stable

after that if the error still reproduce then share the output of `curl -vvv http://127.0.0.1:9000`

**Comment by FriskKiddo** [comment]
I'm very sorry to disturb you. I consumed kafka data through clickhouse's kafka engine table, and later found that many records were lost. So I checked the error.log file and found many log like below:
2023.09.21 20:48:30.037990 [ 11901 ] {} <Error> content_csis_local.csi_judge_result_rec_logstore (b5d81be4-62cb-46bd-bd6f-a9bd4c60035a): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::operato
r()(LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 104, Connection reset by peer, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::ConnectionResetException::ConnectionResetException(int) @ 0x00000000181b7949 in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::error(int, String const&) @ 0x00000000181c237f in /usr/bin/clickhouse
2. Poco::Net::SocketImpl::receiveBytes(void*, int, int) @ 0x00000000181c3d92 in /usr/bin/clickhouse
3. Poco::Net::HTTPSession::refill() @ 0x00000000181a796f in /usr/bin/clickhouse
4. Poco::Net::HTTPHeaderStreamBuf::readFromDevice(char*, long) @ 0x00000000181a0b80 in /usr/bin/clickhouse
5. ? @ 0x00000000180a5b88 in /usr/bin/clickhouse
6. std::basic_streambuf<char, std::char_traits<char>>::uflow() @ 0x0000000008f00bea in /usr/bin/clickhouse
7. std::basic_istream<char, std::char_traits<char>>::get() @ 0x0000000008f02219 in /usr/bin/clickhouse
8. Poco::Net::HTTPResponse::read(std::basic_istream<char, std::char_traits<char>>&) @ 0x00000000181a5cef in /usr/bin/clickhouse
9. Poco::Net::HTTPClientSession::receiveResponse(Poco::Net::HTTPResponse&) @ 0x0000000018193b75 in /usr/bin/clickhouse
10. DB::detail::ReadWriteBufferFromHTTPBase<std::shared_ptr<DB::UpdatableSession<DB::PooledSessionFactory>>>::callImpl(std::shared_ptr<DB::UpdatableSession<DB::PooledSessionFactory>>&, Poco::URI, Poco::Net::HTTPResponse&, String const&, bool) @ 0x0000000011489cff
 in /usr/bin/clickhouse
11. DB::detail::ReadWriteBufferFromHTTPBase<std::shared_ptr<DB::UpdatableSession<DB::PooledSessionFactory>>>::call(std::shared_ptr<DB::UpdatableSession<DB::PooledSessionFactory>>&, Poco::Net::HTTPResponse&, String const&, bool, bool) @ 0x000000001148d51d in /usr/
bin/clickhouse
12. DB::detail::ReadWriteBufferFromHTTPBase<std::shared_ptr<DB::UpdatableSession<DB::PooledSessionFactory>>>::initialize() @ 0x000000001148bf0e in /usr/bin/clickhouse
13. DB::detail::ReadWriteBufferFromHTTPBase<std::shared_ptr<DB::UpdatableSession<DB::PooledSessionFactory>>>::ReadWriteBufferFromHTTPBase(std::shared_ptr<DB::UpdatableSession<DB::PooledSessionFactory>>, Poco::URI, Poco::Net::HTTPBasicCredentials const&, String co
nst&, std::function<void (std::basic_ostream<char, std::char_traits<char>>&)>, unsigned long, DB::ReadSettings const&, std::vector<DB::HTTPHeaderEntry, std::allocator<DB::HTTPHeaderEntry>>, DB::RemoteHostFilter const*, bool, bool, bool, std::optional<DB::HTTPFile
Info>) @ 0x000000001148bafd in /usr/bin/clickhouse
14. DB::PooledReadWriteBufferFromHTTP::PooledReadWriteBufferFromHTTP(Poco::URI, String const&, std::function<void (std::basic_ostream<char, std::char_traits<char>>&)>, DB::ConnectionTimeouts const&, Poco::Net::HTTPBasicCredentials const&, unsigned long, unsignedlong, unsigned long) @ 0x00000000114927f0 in /usr/bin/clickhouse
15. DB::DataPartsExchange::Fetcher::fetchSelectedPart(std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::Context const>, String const&, String const&, String const&, String const&, int, DB::ConnectionTimeouts const&, String const&, String const&, String const&, std::shared_ptr<DB::Throttler>, bool, String const&, std::optional<DB::CurrentlySubmergingEmergingTagger>*, bool, std::shared_ptr<DB::IDisk>) @ 0x0000000014c10886 in /usr/bin/clickhouse
16. ? @ 0x0000000014922da3 in /usr/bin/clickhouse
17. DB::StorageReplicatedMergeTree::fetchPart(String const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, String const&, String const&, bool, unsigned long, std::shared_ptr<zkutil::ZooKeeper>, bool) @ 0x0000000014844e9d in /usr/bin/clickhouse
18. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool) @ 0x000000001483500b in /usr/bin/clickhouse
19. DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) @ 0x00000000148212a0 in /usr/bin/clickhouse
20. ? @ 0x00000000149200bf in /usr/bin/clickhouse
21. DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) @ 0x0000000014fc3986 in /usr/bin/clickhouse
22. DB::StorageReplicatedMergeTree::processQueueEntry(std::shared_ptr<DB::ReplicatedMergeTreeQueue::SelectedEntry>) @ 0x0000000014868c7c in /usr/bin/clickhouse
23. ? @ 0x0000000014920c12 in /usr/bin/clickhouse
24. DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x0000000014cc7ae8 in /usr/bin/clickhouse
25. DB::MergeTreeBackgroundExecutor<DB::RoundRobinRuntimeQueue>::threadFunction() @ 0x0000000014cc8d57 in /usr/bin/clickhouse
26. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e98b20f in /usr/bin/clickhouse
27. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e98df5c in /usr/bin/clickhouse
28. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e986b4f in /usr/bin/clickhouse
29. ? @ 0x000000000e98cb41 in /usr/bin/clickhouse
30. start_thread @ 0x0000000000007ea5 in /usr/lib64/libpthread-2.17.so
31. __clone @ 0x00000000000fe8dd in /usr/lib64/libc-2.17.so
 (version 23.7.1.2470 (official build))


Is the above error report the reason for the loss of records?

**Comment by den-crane** [comment]
> 23.7.1.2470 (official build))

upgrade.

Open another issue. These two issues are unrelated.
