### ISSUE TITLE
Redis Table Engine not fetching values from Redis that were set by redis-cli or other clients

### ISSUE THREAD

**Issue by d3brown3** [ClickHouse/ClickHouse#54903]
**Describe the unexpected behaviour**
I'm running latest version of Clickhouse and Redis on Macos Version 13.5.2. I should be able to retrieve any value from Redis via Redis table engine by providing key in where clause, however, it appears I am only able to retrieve keys that were inserted via Clickhouse and not keys that were set via redis-cli or any other client.

**How to reproduce**
redis_version: 7.2.1
clickhouse version: 23.9.1.1263
default settings used

This works:
```
CREATE TABLE default.redis_cache
(
    `key` String,
    `value` String
)
ENGINE = Redis('127.0.0.1:6379')
PRIMARY KEY key;

insert into redis_cache values('test2', 'testing123');

SELECT *
FROM redis_cache
WHERE key = 'test2'
FORMAT Vertical;

Query id: beedaad6-10a1-405b-8588-1216278ac6f8

Row 1:
──────
key:   test2
value: testing123
```

However, if I put a value using redis-cli it can't be retrieved by clickhouse:
```
> SET test testing123
"OK"

> GET test
"testing123"
```
Retrieving via clickhouse:
```
SELECT *
FROM redis_cache
WHERE key = 'test'
FORMAT Vertical

Query id: 61c982ff-1a08-460b-b076-d342b23b703a

Ok.

0 rows in set. Elapsed: 0.002 sec
```

**Expected behavior**
I should be able to retrieve any value from Redis via Redis table engine by providing key in where clause

**Screenshots**
<img width="1306" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/18585846/f03c3a6c-13a6-452b-be86-ed23ca26e6e5">

<img width="1407" alt="269732306-80be1fa0-85dd-4423-8771-2ed6b6a62741" src="https://github.com/ClickHouse/ClickHouse/assets/18585846/d2a02694-57ce-40bc-9c0b-1c447181fa53">

**Comment by jptx1234** [comment]
@JackyWoo I have the same question. Is it an expected behavior that the Redis engine cannot fetch data that is not set by ClickHouse? If so, are there plans to support it?

**Comment by JackyWoo** [comment]
@d3brown3 Please refer to https://github.com/ClickHouse/ClickHouse/issues/54778#issuecomment-1728697501

**Comment by JackyWoo** [comment]
Maybe we should add some documents.
