### ISSUE TITLE
Merges on a table with TTL leave empty partitions

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#5491]
It's possible that after a merge on a table with TTL there will be no more rows in some partitions. It makes sense to drop those partitions.
```
drop table if exists ttl_00933_1;
create table ttl_00933_1 (d Date, a Int) engine = MergeTree order by a partition by toYear(d) ttl d + interval 1 day;
insert into ttl_00933_1 values (toDate('2000-10-10'), 1);
insert into ttl_00933_1 values (toDate('2100-10-10'), 2);
optimize table ttl_00933_1 final;
select partition, name, active, rows from system.parts where table = 'ttl_00933_1' and active

SELECT
    partition,
    name,
    active,
    rows
FROM system.parts
WHERE (table = 'ttl_00933_1') AND active

┌─partition─┬─name───────┬─active─┬─rows─┐
│ 2000      │ 2000_1_1_1 │      1 │    0 │
│ 2100      │ 2100_2_2_0 │      1 │    1 │
└───────────┴────────────┴────────┴──────┘
```

**Comment by thyn** [comment]
any updates here?

**Comment by alexey-milovidov** [comment]
@CurtizJ Please clarify.

**Comment by alexey-milovidov** [comment]
@CurtizJ has clarified that this behaviour is
- expected;
- correct;
- cannot be avoided (otherwise some invariants for coordination of background merges will fail).

**Comment by alexey-milovidov** [comment]
@CurtizJ has found a way to remove parts if whole partition is going to be removed.

**Comment by zlen131313** [comment]
> @CurtizJ has found a way to remove parts in case if whole partition is going to be removed.

That is this way?

**Comment by CurtizJ** [comment]
I meant, that it's possible to remove empty parts, only if they are continious prefix of all parts sorted by block numbers in partition, because we can't remove random part from the middle due to merge algorithm. But it will cover most of cases. BTW, it's not implemented yet.

**Comment by kekekedeng** [comment]
> I meant, that it's possible to remove empty parts, only if they are continious prefix of all parts sorted by block numbers in partition, because we can't remove random part from the middle due to merge algorithm. But it will cover most of cases. BTW, it's not implemented yet.

How is the progress recently?
