### ISSUE TITLE
column is not in group by when using toTypeName

### ISSUE THREAD

**Issue by fancyqlx** [ClickHouse/ClickHouse#54910]
> You have to provide the following information whenever possible.

**Describe what's wrong**

![image](https://github.com/ClickHouse/ClickHouse/assets/6196299/c4ff6ae4-f8da-4d1c-b664-1314ed69ac6d)

**Does it reproduce on recent release?**

it reproduced in 23.7.1

**How to reproduce**

`SELECT
    toTypeName(stat_standard_id) AS stat_standard_id_1,
    count(1) AS value
FROM
(
    SELECT 'string value' AS stat_standard_id
)
GROUP BY stat_standard_id_1
LIMIT 1`

**Comment by nickitat** [comment]
works with analyser
