### ISSUE TITLE
Help needed to understand discrepancy of query result size and storage size of the same results

### ISSUE THREAD

**Issue by filiprd** [ClickHouse/ClickHouse#54930]
Hello, I am new to ClickHouse and I was hoping someone could help me understand what is going on in my example.

I have a huge table on which I perform a simple query: 

```sql
SELECT Date, col1 ,col2 FROM default.my_test_table AS t WHERE (Date IN ('2022-01-01') AND col5 IN (-1,-8) AND testId IN ('test2','test8')) GROUP BY Date, col1, col2
```

The result of the query gives me 250k rows, and if I want to observe the size of the results of this query I read `result_bytes` from the query logs:

```sql
select formatReadableSize(result_bytes) from system.query_log where query_id ='2054f0bc-f930-4433-a49e-81ac7e1cf0bb'
```

The result of this query is 324.86 MiB, so I assume this is the size of the results of my query.

Now, if I want to store the results of my query in another table, epsecially Memory table, I can do this:

```sql
CREATE TABLE my_results ENGINE = Memory() AS 
SELECT Date, col1 ,col2 FROM default.my_test_table AS t WHERE (Date IN ('2022-01-01') AND col5 IN (-1,-8) AND testId IN ('test2','test8')) GROUP BY Date, col1, col2
```

So far so good, and  `my_results` table now has the same 250k rows. But when I want to check the size my new table takes in memory, I run:

```sql
select formatReadableSize(total_bytes) from system.tables where name = 'my_results'
```

and I get 15.38 MiB. 
Now, I would expect this number to be the same or similar as the size of the results of my initial query, but it is many times less. 

However, If instead of querying my table I use `select number as num from numbers(10000000)`, and then store the results in memory table as in the case above, when comparing the size of the query result with the size of the memory table, I get the same number.

I don't quite understand what is going on here and why is this the case, I would appreciate if someone could please help.

Thank you, and have a lovely day.

**Comment by Felixoid** [comment]
According to https://clickhouse.com/docs/en/operations/system-tables/query_log, it's not the size of the result. It's RAM volume spent to store the result.

For example, here is how I filled the table to reproduce your case:

```sql
CREATE TABLE default.my_test_table
(
    `Date` Date,
    `col1` String,
    `col2` String,
    `col5` Int32,
    `testId` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(Date)
ORDER BY (col1, col2);

INSERT INTO default.my_test_table SELECT
    toDate('2022-01-01') + (number % 2) AS Date,
    toString(number + 300) AS col1,
    toString(number - 300) AS col2,
    (number % 8) - 8 AS col5,
    concat('test', toString((number % 7) + 2)) AS testId
FROM system.numbers
LIMIT 10000000;
```

Now, when I query the data from there, it's size depends on the format:

```
> clickhouse-client << EOF | wc
SELECT
    Date,
    col1,
    col2
FROM default.my_test_table AS t
WHERE (Date IN ('2022-01-01')) AND (col5 IN (-1, -8)) AND (testId IN ('test2', 'test8'))
GROUP BY
    Date,
    col1,
    col2
FORMAT RowBinary
EOF
      0       1 6349228

> clickhouse-client << EOF | wc
SELECT
    Date,
    col1,
    col2
FROM default.my_test_table AS t
WHERE (Date IN ('2022-01-01')) AND (col5 IN (-1, -8)) AND (testId IN ('test2', 'test8'))
GROUP BY
    Date,
    col1,
    col2
FORMAT JSONEachRow
EOF
 357143  357143 19920662

> clickhouse-client << EOF | wc
SELECT
    Date,
    col1,
    col2
FROM default.my_test_table AS t
WHERE (Date IN ('2022-01-01')) AND (col5 IN (-1, -8)) AND (testId IN ('test2', 'test8'))
GROUP BY
    Date,
    col1,
    col2
EOF
 357143 1071429 9563515
