### ISSUE TITLE
Any way to alter MergeTree merge_with_ttl_timeout setting

### ISSUE THREAD

**Issue by iameugenejo** [ClickHouse/ClickHouse#5493]
Is there any way to alter MergeTree merge_with_ttl_timeout setting?

TTL expr has been introduced with the latest release, and I'd like to replace my operation script that drops old partition with this feature, and I wonder if there's a way to change merge_with_ttl_timeout on existing tables.

**Comment by alexey-milovidov** [comment]
In recent versions: `ALTER TABLE ... MODIFY SETTING merge_with_ttl_timeout = ...`
