### ISSUE TITLE
Any convenient way to use CH as prometheus exporter for custom metrics

### ISSUE THREAD

**Issue by MikeAmputer** [ClickHouse/ClickHouse#54959]
Here is the CH config part I use to export metrics:
```xml 
<clickhouse>
	<prometheus>
		<endpoint>/metrics</endpoint>
		<port>9363</port>
		<metrics>true</metrics>
		<events>true</events>
		<asynchronous_metrics>true</asynchronous_metrics>
	</prometheus>

	<http_handlers>
		<rule>
			<url>/</url>
			<methods>POST,GET</methods>
			<headers><pragma>no-cache</pragma></headers>
			<handler>
				<type>dynamic_query_handler</type>
				<query_param_name>query</query_param_name>
			</handler>
		</rule>

		<rule>
			<url>/custom_metrics</url>
			<methods>GET</methods>
			<handler>
				<type>predefined_query_handler</type>
				<query>
					(select ...)
					union all
					(select ...)
					format Prometheus
				</query>
			</handler>
		</rule>
	</http_handlers>
</clickhouse>
```
This solution is troublesome due to the following reasons:

- I have to use `union`. Seems like there is no way to use multiple selects.
- I have to provide a metrics consumer with database credentials. There is no option not to use authentication, and I can't find a way to provide particular url access for user (only tables).
- I don't know why but I have an `ExceptionBeforeStart` query_log with handler query, and http interface does not work from outside after server restart until I manually reload the config (I just add a blank line and save the file). Or I have to set `<listen_reuse_port>1</listen_reuse_port>`, which is marked as not recommended, to avoid this situation.
Here is an error between server reload and config reload I got in DBeaver with `listen_reuse_port=0`:
```SQL Error [1002] [07000]: Unexpected end of file from server, server ClickHouseNode```
Here are error logs on server startup:
```
2023.09.24 11:50:26.338153 [ 317 ] {} <Warning> Application: Listen [::]:8123 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.8.21 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2023.09.24 11:50:26.338232 [ 317 ] {} <Warning> Application: Listen [::]:9000 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.8.21 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2023.09.24 11:50:26.338296 [ 317 ] {} <Warning> Application: Listen [::]:9004 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.8.21 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2023.09.24 11:50:26.338351 [ 317 ] {} <Warning> Application: Listen [::]:9005 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.8.21 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2023.09.24 11:50:26.338414 [ 317 ] {} <Warning> Application: Listen [::]:9363 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.8.21 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
2023.09.24 11:50:26.338483 [ 317 ] {} <Warning> Application: Listen [::]:9009 failed: Poco::Exception. Code: 1000, e.code() = 0, DNS error: EAI: Address family for hostname not supported (version 23.3.8.21 (official build)). If it is an IPv6 or IPv4 address and your host has disabled IPv6 or IPv4, then consider to specify not disabled IPv4 or IPv6 address to listen in <listen_host> element of configuration file. Example for disabled IPv6: <listen_host>0.0.0.0</listen_host> . Example for disabled IPv4: <listen_host>::</listen_host>
```

What is the best approach for exporting metrics?

I know there is an option to configure scrape job with query on prometheus side, but it also has the first two problems mentioned above, and in addition, it exposes data model to prometheus owner, which can cause problems after schema migrations. IMO, the best solution would be to add a query array to the `clickhouse.prometheus` config section. So user queries are executed on scrape call and appended as prometheus-formatted lines to system metrics.

**Comment by den-crane** [comment]
check this article https://altinity.com/blog/building-a-diy-prometheus-http-endpoint-in-clickhouse

**Comment by MikeAmputer** [comment]
Oh, thank you, `<defaults/>` fixed that strange issue with http unavailability and i can set `listen_reuse_port` back to 0 now.
But they also use unions and credential exposure. Unions are just a bit annoying, but the thing with the credentials is that it is database credentials, not endpoint ones. So a metrics consumer has at least a readonly access to one or more database tables.

**Comment by UnamedRus** [comment]
> use unions

You can make VIEW which will have unions

> thing with the credentials is that it is database credentials, not endpoint ones.

You meant, that you can't  provide access to specific tables only for database?

**Comment by MikeAmputer** [comment]
> You can make VIEW which will have unions

Views need migrations, which is usually more complicated to deploy than a db config.

>You meant, that you can't provide access to specific tables only for database?

I mean that clickhouse users are database users. You need to provide a metrics consumer with database credentials, though exporter is a web service endpoint. It's impossible to isolate web service access from database access.

**Comment by den-crane** [comment]
>I mean that clickhouse users are database users. You need to provide a metrics consumer with database credentials, though exporter is a web service endpoint. It's impossible to isolate web service access from database access.

You can restrict access to only localhost, so this user will be unable to access clickhouse remotely.

**Comment by MikeAmputer** [comment]
> You can restrict access to only localhost, so this user will be unable to access clickhouse remotely.

Then metrics can only be scraped from the localhost, while Prometheus is installed on a separate host and does not have access to the endpoint.

**Comment by UnamedRus** [comment]
> I mean that clickhouse users are database users. You need to provide a metrics consumer with database credentials, though exporter is a web service endpoint. It's impossible to isolate web service access from database access.

You can make some dummy user, which will have "public creds".
Or you can make an issue, which will allow user-less access to some of custom defined endpoints.
