### ISSUE TITLE
When have two replicate node for one Shard, how upload one replicate node data to S3

### ISSUE THREAD

**Issue by ChaoHsupin** [ClickHouse/ClickHouse#54956]
Hi! Thanks for your work!
Suppose I have two replicate node for one Shard. I use local disk + S3 for hot and warm storage. In other words, hot data is placed on the local disk and cold data is placed on S3.We know that the storage of S3 is reliable, so if both replicate must upload their own data to S3, it will undoubtedly cause waste width and storage waste.Is there any way to upload one replicate of the data?

**Comment by den-crane** [comment]
There is a feature https://clickhouse.com/docs/en/operations/storing-data#zero-copy

```
select* from system.merge_tree_settings where name like 'remote_fs_zero_cop%';

┌─name─────────────────────────────────────┬─value─────────────────┬─changed─┬─description─────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┬─is_obsolete─┐
│ remote_fs_zero_copy_zookeeper_path       │ /clickhouse/zero_copy │       0 │ ZooKeeper path for zero-copy table-independent info.        │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ String │           0 │
│ remote_fs_zero_copy_path_compatible_mode │ 0                     │       0 │ Run zero-copy in compatible mode during conversion process. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool   │           0 │
└──────────────────────────────────────────┴───────────────────────┴─────────┴─────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴────────┴─────────────┘
```
https://clickhouse.com/docs/en/operations/settings/merge-tree-settings

**Comment by ChaoHsupin** [comment]
> There is a feature https://clickhouse.com/docs/en/operations/storing-data#zero-copy
> 
> ```
> select * from system.merge_tree_settings where name like '%remote_fs_zero%';
> 
> ┌─name─────────────────────────────────────┬─value─────────────────┬─changed─┬─description────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┬─is_obsolete─┐
> │ allow_remote_fs_zero_copy_replication    │ 0                     │       0 │ Don't use this setting in production, because it is not ready. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool   │           0 │
> │ remote_fs_zero_copy_zookeeper_path       │ /clickhouse/zero_copy │       0 │ ZooKeeper path for zero-copy table-independent info.           │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ String │           0 │
> │ remote_fs_zero_copy_path_compatible_mode │ 0                     │       0 │ Run zero-copy in compatible mode during conversion process.    │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool   │           0 │
> └──────────────────────────────────────────┴───────────────────────┴─────────┴────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴────────┴─────────────┘
> ```
> 
> https://clickhouse.com/docs/en/operations/settings/merge-tree-settings
thanks！
