### ISSUE TITLE
How to Reduce the number of znodes？

### ISSUE THREAD

**Issue by duhy-max** [ClickHouse/ClickHouse#54968]
Today I received a notification from operation and maintenance, warning that there are too many znodes. I don't know how to solve it. So I looked at the related isuue. But still no answer found.

I found this parameter in the manual: `use_minimalistic_part_header_in_zookeepe`r
Can setting` use_minimalistic_part_header_in_zookeeper=1 `effectively reduce the number of znodes? Will the number of znodes that have been generated decrease simultaneously, or will the speed of generating znodes in the future decrease?

**Comment by UnamedRus** [comment]
If you don't use ancient version of ClickHouse, it already enabled by default use_minimalistic_part_header_in_zookeeper

Which version, how many shards/replicas/replicated tables
Which partitioning schema you use for tables

**Comment by duhy-max** [comment]
> If you don't use ancient version of ClickHouse, it already enabled by default use_minimalistic_part_header_in_zookeeper
> 
> Which version, how many shards/replicas/replicated tables Which partitioning schema you use for tables


@UnamedRus 

my version is ：` 23.3.2.37 `   。 This version was upgraded from version 22.3.9.19 last month.
 
8 shards ，2 replicas ，800 replicated tables

Partition by day。 like this `PARTITION BY (toYYYYMMDD(STAT_DT))`

But the number of znodes is as high as 1.8 million

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/

> 800 replicated tables

too much.

And daily partitioning does mean that every day you create at least 800*8 = 6400 new znodes

Check this article
https://kb.altinity.com/altinity-kb-useful-queries/remove_unneeded_block_numbers/

**Comment by duhy-max** [comment]
Thanks，I will try to delete znode in [this way 。](https://kb.altinity.com/altinity-kb-useful-queries/remove_unneeded_block_numbers/)

**Comment by duhy-max** [comment]
When TTL triggers partition deletion, can the znode be automatically deleted? and, How should it be set? @UnamedRus

**Comment by UnamedRus** [comment]
> can the znode be automatically deleted? 

No, it's exactly the problem

**Comment by duhy-max** [comment]
> https://kb.altinity.com/altinity-kb-schema-design/how-much-is-too-much/
> 
> > 800 replicated tables
> 
> too much.
> 
> And daily partitioning does mean that every day you create at least 800*8 = 6400 new znodes
> 
> Check this article https://kb.altinity.com/altinity-kb-useful-queries/remove_unneeded_block_numbers/

According to the execution result of this SQL, I deleted the znode, and about 1.7 million records were deleted.
But when I try to execute this SQL again I keep getting a timeout and no response.
I started segmenting, and I found the first paragraph

```
SELECT path as block numbers path, name as partition id
FROM system.zookeeper
WHERE path IN (
SELECT concat(zookeeper path, '/block numbers/') as block numbers path
FROM clusterAllReplicas('{cluster}',system.replicas)
)
```

We can't get the results. I can execute the SQL statement after the in subquery alone .

Do you have any ideas to help me？thank You . @UnamedRus  UnamedRus
