### ISSUE TITLE
Segmentation fault in 19.3.5

### ISSUE THREAD

**Issue by sdlcwangsong** [ClickHouse/ClickHouse#5499]
version: 19.3.5

Recently My one node was down in cluster, and I got the follow error. Can you tell me what's wrong with it?

```
2019.05.31 16:08:18.966128 [ 552 ] {} <Error> BaseDaemon: ########################################
2019.05.31 16:08:19.079069 [ 552 ] {} <Error> BaseDaemon: (from thread 65) Received signal Segmentation fault (11).
2019.05.31 16:08:19.079109 [ 552 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.05.31 16:08:19.079121 [ 552 ] {} <Error> BaseDaemon: Access: read.
2019.05.31 16:08:19.079129 [ 552 ] {} <Error> BaseDaemon: Unknown si_code.
2019.05.31 16:08:19.256962 [ 552 ] {} <Error> BaseDaemon: 0. clickhouse-server(DB::MergeTreeDataPart::getColumnSizeImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::IDataType const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*) const+0xab) [0x5bc367b]
2019.05.31 16:08:19.257024 [ 552 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::MergeTreeDataPart::getTotalColumnsSize() const+0xb7) [0x5bc3807]
2019.05.31 16:08:19.257037 [ 552 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::StorageSystemParts::processNextStorage(std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, DB::StorageSystemPartsBase::StoragesInfo const&, bool)+0x912) [0x2e2e9c2]
2019.05.31 16:08:19.257055 [ 552 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::StorageSystemPartsBase::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0xc5) [0x2e66a65]
2019.05.31 16:08:19.257073 [ 552 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x14e9) [0x5e0ae49]
2019.05.31 16:08:19.257084 [ 552 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x3f4) [0x5e0cff4]
2019.05.31 16:08:19.257094 [ 552 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x3c) [0x5e0fbcc]
2019.05.31 16:08:19.257103 [ 552 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x5c) [0x5dc981c]
2019.05.31 16:08:19.257118 [ 552 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x26) [0x5dc9ab6]
2019.05.31 16:08:19.257126 [ 552 ] {} <Error> BaseDaemon: 9. clickhouse-server() [0x58bd2e1]
2019.05.31 16:08:19.257138 [ 552 ] {} <Error> BaseDaemon: 10. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0xd6) [0x58bf326]
2019.05.31 16:08:19.257149 [ 552 ] {} <Error> BaseDaemon: 11. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x3353) [0x2c9da93]
2019.05.31 16:08:19.257160 [ 552 ] {} <Error> BaseDaemon: 12. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3e3) [0x2ca01f3]
2019.05.31 16:08:19.257177 [ 552 ] {} <Error> BaseDaemon: 13. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2fe) [0x644606e]
2019.05.31 16:08:19.257186 [ 552 ] {} <Error> BaseDaemon: 14. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x640958f]
2019.05.31 16:08:19.257195 [ 552 ] {} <Error> BaseDaemon: 15. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x642d0e6]
2019.05.31 16:08:19.257203 [ 552 ] {} <Error> BaseDaemon: 16. clickhouse-server(Poco::PooledThread::run()+0x77) [0x65043a7]
2019.05.31 16:08:19.257212 [ 552 ] {} <Error> BaseDaemon: 17. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x650d6a8]
2019.05.31 16:08:19.257220 [ 552 ] {} <Error> BaseDaemon: 18. clickhouse-server() [0x6c800bf]
2019.05.31 16:08:19.257228 [ 552 ] {} <Error> BaseDaemon: 19. /lib64/libpthread.so.0(+0x7dd5) [0x7f4c9fd09dd5]
```

**Comment by wit** [comment]
Такая версия и есть проблема
`2019.05.31 16:32:11.674826 [ 102 ] {} <Error> BaseDaemon: ########################################
2019.05.31 16:32:11.674908 [ 102 ] {} <Error> BaseDaemon: (from thread 60) Received signal Segmentation fault (11).
2019.05.31 16:32:11.674924 [ 102 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.05.31 16:32:11.674931 [ 102 ] {} <Error> BaseDaemon: Access: read.
2019.05.31 16:32:11.674938 [ 102 ] {} <Error> BaseDaemon: Unknown si_code.
2019.05.31 16:32:11.701518 [ 102 ] {} <Error> BaseDaemon: 0. clickhouse-server(DB::Block::rows() const+0x29) [0x530fee9]
2019.05.31 16:32:11.701586 [ 102 ] {} <Error> BaseDaemon: 1. clickhouse-server(DB::MergeTreeRangeReader::read(unsigned long, std::vector<DB::MarkRange, std::allocator<DB::MarkRange> >&)+0x81d) [0x5a61d5d]
2019.05.31 16:32:11.701603 [ 102 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::MergeTreeBaseSelectBlockInputStream::readFromPart()+0x5f0) [0x5a5b160]
2019.05.31 16:32:11.701616 [ 102 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::MergeTreeBaseSelectBlockInputStream::readImpl()+0xb2) [0x5a5c5a2]
2019.05.31 16:32:11.701638 [ 102 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::IBlockInputStream::read()+0x1f5) [0x5343945]
2019.05.31 16:32:11.701650 [ 102 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::FilterBlockInputStream::readImpl()+0xad) [0x58a024d]
2019.05.31 16:32:11.701659 [ 102 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::IBlockInputStream::read()+0x1f5) [0x5343945]
2019.05.31 16:32:11.701669 [ 102 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x589f48a]
2019.05.31 16:32:11.701677 [ 102 ] {} <Error> BaseDaemon: 8. clickhouse-server(DB::IBlockInputStream::read()+0x1f5) [0x5343945]
2019.05.31 16:32:11.701693 [ 102 ] {} <Error> BaseDaemon: 9. clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long)+0x308) [0x58d60d8]
2019.05.31 16:32:11.701741 [ 102 ] {} <Error> BaseDaemon: 10. clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}>(DB::Paralle
lInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::process()::{lambda()#1}&&)::{lambda()#1}::operator()() const+0x58) [0x58d6638]
2019.05.31 16:32:11.701762 [ 102 ] {} <Error> BaseDaemon: 11. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x199) [0x5da11e9]
2019.05.31 16:32:11.701770 [ 102 ] {} <Error> BaseDaemon: 12. clickhouse-server() [0x65c572f]
2019.05.31 16:32:11.701778 [ 102 ] {} <Error> BaseDaemon: 13. /lib64/libpthread.so.0(+0x7e25) [0x7f3aa823ee25]`

**Comment by filimonov** [comment]
Please check if problem appears after update to 19.7. To debug the problem we need steps to reproduce (table schema, usage scenario, etc).

**Comment by alexey-milovidov** [comment]
Could you please share your table definitions?
