### ISSUE TITLE
On Cluster alter commands are checking for local db

### ISSUE THREAD

**Issue by chiragb1994** [ClickHouse/ClickHouse#55009]
When I run an alter command  with `on cluster` clause for a remote cluster, it gives me the error
```
[2023-09-26 11:47:24] Code: 81. DB::Exception: Database shard does not exist. (UNKNOWN_DATABASE) (version 23.8.2.7 (official build))
```
In the previous version (v22.8), this worked well, even when the current server didn't have the db. In the latest version (v23.8.2.7), this is giving an error.

**How to reproduce**

* Which ClickHouse server version to use: v23.8.2.7
* Lets say we have two servers: server 1 and server 2, same version.
* In server 1, Add a remote cluster (`test_cluster`) to the config (server 2 is in the remote cluster), where server 1 is not a part of the cluster. 
* Create a database (eg `test_db`) on the server 2. Make sure the same db is not in server 1.
* On server 1, run `CREATE TABLE test_db.test_table on cluster 'test_cluster' (id Int64) Engine=MergeTree;`
* On server 1, run `ALTER TABLE test_db.test_table on cluster 'test_cluster' add column id_test Int64;`

**Expected behavior**

The second command should run and add column in table on test_cluster

**Error message and/or stacktrace**
```
[2023-09-26 11:53:35] Code: 81. DB::Exception: Database shard does not exist. (UNKNOWN_DATABASE) (version 23.8.2.7 (official build))
```

**Comment by tavplubix** [comment]
It was accidentally broken in https://github.com/ClickHouse/ClickHouse/pull/48354

**Comment by chiragb1994** [comment]
It is not fixed in the latest version [v23.8.7.24-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v23.8.7.24-lts).

**Comment by evillique** [comment]
I backported this fix, it will be in the next version of 23.8

**Comment by chiragb1994** [comment]
This is still there for the attach table command. Detach is working but attach fails.

**Comment by chiragb1994** [comment]
Will this be backported to v23.8 lts?

**Comment by evillique** [comment]
Backported it to 23.8, it will be included in the next release
