### ISSUE TITLE
Offline install rpm package raises error "Segmentation fault"

### ISSUE THREAD

**Issue by flyly0755** [ClickHouse/ClickHouse#55006]
**Describe what's wrong**
The machine to install clickhouse 23.3.13.6 version can't connect the network, so try to install with offline mode.
I download
clickhouse-client-23.3.13.6.x86_64.rpm
clickhouse-common-static-23.3.13.6.x86_64.rpm
clickhouse-server-23.3.13.6.x86_64.rpm
these 3 rpm package, then put in one dir, 
then execute command **rpm -ivh *.rpm** to install it.
But install failed, raise error:
```shell
Preparing...                          ################################# [100%]
Updating / installing...
   1:clickhouse-common-static-0:23.3.1################################# [ 33%]
   2:clickhouse-client-0:23.3.13.6-1  ################################# [ 67%]
   3:clickhouse-server-0:23.3.13.6-1  ################################# [100%]
/var/tmp/rpm-tmp.SOuJta: line 57: 30002 Segmentation fault      (core dumped) ${CLICKHOUSE_GENERIC_PROGRAM} install --user "${CLICKHOUSE_USER}" --group "${CLICKHOUSE_GROUP}" --pid-path "${CLICKHOUSE_PIDDIR}" --config-path "${CLICKHOUSE_CONFDIR}" --binary-path "${CLICKHOUSE_BINDIR}" --log-path "${CLICKHOUSE_LOGDIR}" --data-path "${CLICKHOUSE_DATADIR}"
warning: %post(clickhouse-server-0:23.3.13.6-1.x86_64) scriptlet failed, exit status 139

```

**Does it reproduce on recent release?**
Can be reporduce  on 2 linux machines

**How to reproduce**
Describe as above

**Expected behavior**

Before i install a old version  21.12.3.32 with some method which can be installed successfully.

**Comment by alexey-milovidov** [comment]
It could be a problem with your servers, such as a broken version of a glibc, or an LD_PRELOAD setting that interferes the operation, or a broken Linux kernel, or a faulty hardware.

Nevertheless, I recommend installing the latest ClickHouse version.

**Comment by flyly0755** [comment]
> It could be a problem with your servers, such as a broken version of a glibc, or an LD_PRELOAD setting that interferes the operation, or a broken Linux kernel, or a faulty hardware.
> 
> Nevertheless, I recommend installing the latest ClickHouse version.

Yes, now i install the newest version v23.3.13.6-lts, but with the error info you can't know where is the exact problem. Then how to debug this issue and try to solve it?

**Comment by den-crane** [comment]
can you share OS and kernel ?

```
 cat /etc/*rel*/

uname -a
```

**Comment by flyly0755** [comment]
> cat /etc/*rel*/
uname -a
Linux xxx 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Comment by alexey-milovidov** [comment]
Oops, that's a very old kernel.
But it should work anyway - we have something not right.

**Comment by refergit** [comment]
was the above issue fixed? I'm still meeting it on this version clickhouse-server-23.10.3.5.x86_64.rpm

**Comment by refergit** [comment]
Is there any update for it?

**Comment by alexey-milovidov** [comment]
Can you share the OS and Kernel version?

```
cat /etc/*rel*/
uname -a
```

**Comment by refergit** [comment]
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
uname -a
Linux linux90102 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alexey-milovidov** [comment]
Linux 3.10 is very old, it likely has a bug.

**Comment by refergit** [comment]
OK, which latest version of clickhouse is supported for Linux3.10?

**Comment by alexey-milovidov** [comment]
I don't have this information, and until recently, I expected that every ClickHouse version would successfully work.
Let me try to find an AMI on AWS to reproduce this issue - maybe it is something easy...

**Comment by refergit** [comment]
OK, thanks a lot. Please let me know if you have any question about reproducing it.
