### ISSUE TITLE
Unknown format Parquet

### ISSUE THREAD

**Issue by AkhtemWays** [ClickHouse/ClickHouse#55014]
Hi,

I'm trying to execute `cat part-00003-e71b7ad6-b31e-45a3-aad0-17ac4f2f5a4e-c000.parquet | clickhouse-client --host myHost --port 9000 --user myUser --password myPassword --query="INSERT INTO myTable FORMAT Parquet"`

And getting error `Code: 73. DB::Exception: Unknown format Parquet`

OS: Ubuntu 20.04
Clickhouse version: 23.1.3.5
clickhouse-client version: 18.16.1

Table creation DDL: tried both
```
create table myTable (
	`sortField` String
)
ENGINE = File(Parquet);

create table myTable (
	`sortField` String
)
ENGINE = MergeTree
PARTITION BY sortField
ORDER BY (sortField)
PRIMARY KEY (sortField);
```

**Comment by UnamedRus** [comment]
> clickhouse-client version: 18.16.1

You need to upgrade your Client version. 
In your case, clickhouse client does parsing of Parquet File
