### ISSUE TITLE
Are direct layout dictionaries supposed to be used with the dictionary functions?

### ISSUE THREAD

**Issue by aidbutlr** [ClickHouse/ClickHouse#55011]
I am testing using a direct dictionary layout with a dictionary that has a postgres source. The reason for this is to keep the the memory consumption on clickhouse low while still being able to access data using the clickhouse dictionary functions. Performing a simple dictGet lookup works fine but if I use the dictionary as part of a query, the entire list of search keys in the form of an or'd predicate appears to be passed to postgres. This eventually prevents the query from completing as the number of keys being searched increases. 

It appears that direct and ssd_cache layouts do not work well with the dictionary functions, so I'm wondering if this is a supported use-case?

A simplified test case can be seen here

```
CREATE DICTIONARY `testdict`
(
    `key label` String,
    `value label` String
)
PRIMARY KEY `key label`
SOURCE(POSTGRESQL(HOST 'postgres' PORT '5432' DB 'pgdb' TABLE 'testable' USER 'postgres' PASSWORD '[HIDDEN]'))
LAYOUT(COMPLEX_KEY_DIRECT())

select dictGet('testdict','value label',key) from (select number as key from numbers(1,100) )
```

On postgres I can see the query execute
`COPY (SELECT "key label", "value label" FROM "testable" WHERE ("key label"='1') OR ("key label"='2') OR ("key label"='3') OR ("key label"='4') OR ("key label"='5') OR ("key label"='6') OR ("key label"='7') OR ("key label"='8') OR ("key label"='9') OR ("key label"='10') OR ("key label"='11') OR ("key label"='12') OR ("key label"='13') OR ("key label"='14') OR ("key label"='15') OR ("key label"='16') OR ("key label"='17') OR ("key label"='18') OR ("key label"='19') OR ("key label"='20') OR ("key label"='21') OR ("key label"='22') OR ("key label"='23') OR ("key label"='24') OR ("key label"='25') OR ("key label"='26') OR ("key label"='27') OR ("key label"='28') OR ("key label"='29') OR ("key label"='30') OR ("key label"='31') OR ("key label"='32') OR ("key label"='33') OR ("key label"='34') OR ("key label"='35') OR ("key label"='36') OR ("key label"='37') OR ("key label"='38') OR ("key label"='39') OR ("key label"='40') OR ("key label"='41') OR ("key label"='42') OR ("key label"='43') OR ("key label"='44') OR ("key label"='45') OR ("key label"='46') OR ("key label"='47') OR ("key label"='48') OR ("key label"='49') OR ("key label"='50') OR ("key label"='51') OR ("key label"='52') OR ("key label"='53') OR ("key label"='54') OR ("key label"='55') OR ("key label"='56') OR ("key label"='57') OR ("key label"='58') OR ("key label"='59') OR ("key label"='60') OR ("key label"='61') OR ("key label"='62') OR ("key label"='63') OR ("key label"='64') OR ("key label"='65') OR ("key label"='66') OR ("key label"='67') OR ("key label"='68') OR ("key label"='69') OR ("key label"='70') OR ("key label"='71') OR ("key label"='72') OR ("key label"='73') OR ("key label"='74') OR ("key label"='75') OR ("key label"='76') OR ("key label"='77') OR ("key label"='78') OR ("key label"='79') OR ("key label"='80') OR ("key label"='81') OR ("key label"='82') OR ("key label"='83') OR ("key label"='84') OR ("key label"='85') OR ("key label"='86') OR ("key label"='87') OR ("key label"='88') OR ("key label"='89') OR ("key label"='90') OR ("key label"='91') OR ("key label"='92') OR ("key label"='93') OR ("key label"='94') OR ("key label"='95') OR ("key label"='96') OR ("key label"='97') OR ("key label"='98') OR ("key label"='99') OR ("key label"='100')) TO STDOUT`

**Comment by aidbutlr** [comment]
I have tried it with an index on the `key label` column. The execution time appears to degrade based on the number of lookup keys that are being passed from clickhouse.  The query appears to degrade in relation to the number of search terms being used 

1 row in set. Elapsed: 0.222 sec. Processed 1.00 thousand rows, 8.00 KB (4.50 thousand rows/s., 36.01 KB/s.)
1 row in set. Elapsed: 2.954 sec. Processed 10.00 thousand rows, 80.00 KB (3.38 thousand rows/s., 27.08 KB/s.)
1 row in set. Elapsed: 7.298 sec. Processed 20.00 thousand rows, 160.00 KB (2.74 thousand rows/s., 21.92 KB/s.)
1 row in set. Elapsed: 16.622 sec. Processed 30.00 thousand rows, 240.00 KB (1.80 thousand rows/s., 14.44 KB/s.)
1 row in set. Elapsed: 24.606 sec. Processed 40.00 thousand rows, 320.00 KB (1.63 thousand rows/s., 13.01 KB/s.)

**Comment by den-crane** [comment]
ah, yes, there is an issue
* https://github.com/ClickHouse/ClickHouse/issues/50662
