### ISSUE TITLE
Default ORDER BY key

### ISSUE THREAD

**Issue by alanpaulkwan** [ClickHouse/ClickHouse#55023]
I found the setting to enable default table engine, but you can only set default engine = MergeTree

therefore, one must always write CREATE TABLE db.table **ORDER BY tuple() a**s  select .. unless one uses the log engine.

I would hope for an option MergeTree ORDER BY tuple() as a default engine, because then the create table statement would look like one in any other SQL language.

**Comment by den-crane** [comment]
IMO OLAP users must educate themselves before shouting "Clickhouse is slow".

**Comment by tavplubix** [comment]
`ORDER BY tuple()` is an antipattern, you should never use that for real usecases, it's suitable only for simple tests. 

Yes, you should always specify an ORDER BY key.

See also https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#primary-keys-and-indexes-in-queries and https://clickhouse.com/docs/en/optimize/sparse-primary-indexes#ordering-key-columns-efficiently

**Comment by UnamedRus** [comment]
Actually, ORDER BY tuple() is useful in real use cases when you don't know which data you are loading, for example you have such scripted pipeline:
1. Import data to staging table from File/other DBMS.
2. Run queries, which return uniq count/ crosstab/min/max values
3. Based on input, script create new table with optimized column types/codecs/order by/partition by and additional columns.
4. INSERT INTO destination_table SELECT * FROM staging

**Comment by alanpaulkwan** [comment]
@den-crane Not to be rude, but I'm really well aware of what ORDER BY tuple() means. But I have 15000 tables, many are tiny and Clickhouse isn't fast at joins anyway, so what's the point of specifying keys for all of them?

**Comment by alanpaulkwan** [comment]
In fact, because Clickhouse is so fast its liberating to not have to think about table schemas unless they really need performance, since the baseline few seconds it takes to even manually specify a key makes it irrelevant.

**Comment by UnamedRus** [comment]
> Maybe we could introduce a setting (disabled by default), but I'm not sure if it's worth adding a setting.

IMO, it's ok, because in order to make ClickHouse compatible with other dbms, a lot of settings were added to ignore specific features, which clickhouse doesn't' support from SQL (FK for example)

**Comment by alanpaulkwan** [comment]
Definitely would improve MySQL compatibility. It has to be disabled explicitly by the user (or by the admin with a global), and I think if you're using SQL and unaware of what a primary key is, you're probably not dealing with huge data anyway where Clickhouse performance begins to degrade.

Another random thought: in many contexts, a key is truly desirable but annoying to specify. One can safely assume that the left-most column is likeliest of all columns is likeliest to be a sorting key, and accordingly, and in early versions Doris / StarRocks defaulted to the left-most key being a sorting key. Maybe that'd be another interesting option?

**Comment by alexey-milovidov** [comment]
I have a few use-cases for tables without a primary key.

1. Staging tables for intermediate stages of data loading.
2. Analytics on smaller static datasets where no natural primary key exists and a full scan is expected.

By the way, today I write `ORDER BY ()`, this is slightly more natural.

Let's introduce a setting `create_table_empty_primary_key_by_default`.

**Comment by alexey-milovidov** [comment]
Introduce a setting `create_table_empty_primary_key_by_default` as Bool.

If it is set to 1 and a table of MergeTree family does not contain ORDER BY and PRIMARY KEY, assume `ORDER BY ()`.

Take care of the case when no table ENGINE is specified and the default table engine is used.
