### ISSUE TITLE
CORRUPTED_DATA in HTTPHandler when read from HTTPChunkedReadBuffer at trySendExceptionToClient

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#55025]
The logs look like that:
https://pastila.nl/?0111d3ac/4a7e2d25bb4a954ba8f19eefab297691#Ki3m+cXZ/ZI9wGWbwDNnfA==

Here I see that 
- the initial error is that CH was unable to read from input HTTPChunkedReadBuffer with SOCKET_TIMEOUT
- after that CH was unable to send the logs with CORRUPTED_DATA
  
It is interesting why the data is marked as corrupted when CH is writing it, not reading. The read has been failed right before with error SOCKET_TIMEOUT.

When CH tries to send logs it also tries to read all the data in the input.
It is here:
https://github.com/ClickHouse/ClickHouse/blob/535b9337f4e25c445ec8d0704de145f57bf70927/src/Server/HTTPHandler.cpp#L923

For me it seems wrong, the input stream is broken, no need to read out from it here. That leads to the wrong scary message CORRUPTED_DATA. Meanwhile it was SOCKET_TIMEOUT on reading from the client.

**Comment by alexey-milovidov** [comment]
Outdated.
