### ISSUE TITLE
Optimization can change column name for group by since 23.5

### ISSUE THREAD

**Issue by Arvamer** [ClickHouse/ClickHouse#55024]
https://fiddle.clickhouse.com/80c8bea6-1952-499b-91bc-6a08d34355cc

```sql
SELECT if(true, null, name) as foo, count(*)
FROM users
GROUP BY foo;
```

Running this query will result in following error;

> Column `name` is not under aggregate function and not in GROUP BY. Have columns: ['NULL','true','count()']

Query works fine in 23.4. This only happens with const condition in `if`. After changing `true` to something that depends on data from table like `name is not null` query will be executed without any errors.

**Expected behavior**

Query is valid and should group by result of `if (true, null, name)`.

**Comment by den-crane** [comment]
you can use `materialize(true)` as a workaround

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/50928#issuecomment-1610017154
