### ISSUE TITLE
RoaringBitmap serialization is not compatible between big-endian and little-endian platforms

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#55045]
**Expected behavior**
The same output for platforms

**Additional context**
https://github.com/RoaringBitmap/CRoaring/issues/423

@HarryLeeIBM Probably, you can be interested in that

**Comment by alexey-milovidov** [comment]
ClickHouse only works on x86_64, AArch64, PowerPC64 LE, and RISC-V, and all of them are little-endian.
