### ISSUE TITLE
Change default way to ini files for odbc engine

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#55050]
I want to use engine ODBC tables with Pervasive SQL database
Pervasive SQL ODBC installed on machine, with non default path (not /etc/), it works with `isql`, but i got error from clickhouse 
`[unixODBC][Driver Manager]Data source name not found and no default driver specified`

is there any way to change default way to odbc\odbcinst files for clickhouse?

**Comment by yakov-olkhovskiy** [comment]
have you tried to setup `ODBCINI` and `ODBC_INI` environment variables? CliskHouse uses `nanodbc` which is a wrapper on ODBC API
