### ISSUE TITLE
Reading a file using the S3 engine, missing columns.

### ISSUE THREAD

**Issue by FengZh61** [ClickHouse/ClickHouse#55052]
![image](https://github.com/ClickHouse/ClickHouse/assets/98309003/bde0eddb-b652-4438-95c3-ca7ee39eb6ef)
This is me using CH to read a file from the object store.

![image](https://github.com/ClickHouse/ClickHouse/assets/98309003/10501b04-1f8d-4552-9038-45908d4e1d36)
But reading this file directly, there is this column

**Comment by Avogar** [comment]
Please, run `DESCRIBE s3(...)`, so we can see the structure of the file and check if there is a missing column there

**Comment by FengZh61** [comment]
> Please, run `DESCRIBE s3(...)`, so we can see the structure of the file and check if there is a missing column there

![image](https://github.com/ClickHouse/ClickHouse/assets/98309003/63e55cc1-a1f6-4dea-b346-c07e8171d142)
Missing localtion field.
At the beginning of the data storage, there is no localtion field, then added this field, in fact, there are 2 kinds of data structure, one has localtion, one does not, but when I query the file that has localtion alone, I can not query the localtion field either!

**Comment by Avogar** [comment]
BTW, you can always specify structure with all required fields manually in `s3` table function like `select ... from s3('s3_url', 'structure', Parquet)`

> At the beginning of the data storage, there is no localtion field, then added this field, in fact, there are 2 kinds of data structure, one has localtion, one does not

If you tried to read files with different data structure using s3 globs, then there is a possibility that we inferred structure from file without localtion field and cached it for all read files.
Try to clear schema cache by using query `system  drop schema cache` or disable it completely by disabling setting `schema_inference_use_cache_for_s3`

**Comment by FengZh61** [comment]
> BTW, you can always specify structure with all required fields manually in `s3` table function like `select ... from s3('s3_url', 'structure', Parquet)`
> 
> > At the beginning of the data storage, there is no localtion field, then added this field, in fact, there are 2 kinds of data structure, one has localtion, one does not
> 
> If you tried to read files with different data structure using s3 globs, then there is a possibility that we inferred structure from file without localtion field and cached it for all read files (because we expect the same structure for all files read in one glob) Try to clear schema cache by using query `system drop schema cache` or disable it completely by disabling setting `schema_inference_use_cache_for_s3`

How do I fill in the 'structure', is he a string or an array, my data structure is __hash__,__name__,__timestamp,env,ident,instance,job,localtion,value!

**Comment by FengZh61** [comment]
> BTW, you can always specify structure with all required fields manually in `s3` table function like `select ... from s3('s3_url', 'structure', Parquet)`
> 
> > At the beginning of the data storage, there is no localtion field, then added this field, in fact, there are 2 kinds of data structure, one has localtion, one does not
> 
> If you tried to read files with different data structure using s3 globs, then there is a possibility that we inferred structure from file without localtion field and cached it for all read files (because we expect the same structure for all files read in one glob) Try to clear schema cache by using query `system drop schema cache` or disable it completely by disabling setting `schema_inference_use_cache_for_s3`


Thanks for the answer, specifying structure, I tried successfully, but the localtion field is still not there, in my initial data structure, it is A,B,C three fields, later, I added another field, the data structure became A,B,C,D, but when I use s3 engine to query, the return result is only A,B,C three fields, when I specify A, B,C,D4 fields, when I specify A,B,C,D4 fields, it will report Missing columns 'D', the effect I expect is to specify A,B,C,D4 when querying, there is no D field in the initial data, then it's null. although this shouldn't be the function that CH should support, but I think the idea is good.

**Comment by Avogar** [comment]
There is an option to skip missing fields in Parquet format by enabling setting `input_format_parquet_allow_missing_columns`, it's disabled by default, that's why you got error `Missing columns 'D'`. When you enable this setting, ClickHouse will insert default values into this column if file doesn't contain it. If the type of column is `Nullable(...)`, it will insert nulls.

**Comment by FengZh61** [comment]
> There is an option to skip missing fields in Parquet format by enabling setting `input_format_parquet_allow_missing_columns`, it's disabled by default, that's why you got error `Missing columns 'D'`. When you enable this setting, ClickHouse will insert default values into this column if file doesn't contain it. If the type of column is `Nullable(...)`, it will insert nulls.

Yes! I made it, thanks for the answer and good luck with CH getting better and better!
