### ISSUE TITLE
CANNOT_STAT: Cannot check modification time for file: ... errno: 2, strerror: No such file or directory

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#55068]
**Describe the unexpected behaviour**
Sometimes, randomly, this problem pops on Clickhouse logs. It's happening only once per day, after i run some mutations. It seems to be related to a specific part of a partition of a table, that is the one that gets mutated. Is it normal?

It has happened like 5 times in the last 5 days, only once per day. Then it happened in the past randomly, but never so frequently.

**How to reproduce**
22.6.9.11 (official build)

**Expected behavior**

**Error message and/or stacktrace**

Cannot check modification time for file: /var/lib/clickhouse/store/ae2/ae23b3fb-405e-4eb8-a249-6a123172e52b/tmp_clone_202309_104257_108203_793_108569/, errno: 2, strerror: No such file or directory

**Comment by tavplubix** [comment]
Version 22.6 is obsolete and not supported anymore for about a year already, you should upgrade. Also, stacktrace for the error message is missing.
