### ISSUE TITLE
StressTestMSan is likely to fail by other reasons

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#55075]
StressTestMSan is likely to fail by other reasons, shown in following screenshot.

<img width="719" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/1518453/e6d7a5d0-cd27-464b-ad5d-fa0a657225cd">

The same issue also exists in AST fuzzer.

<img width="747" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/1518453/2dae9a93-5858-436a-bf47-84d1c2c170ad">

The server log says there is invalid flag defined in config for Keeper. The link is 
https://[s3.amazonaws.com/clickhouse-test-reports/55007/d5d3cf0e9d0eed5af9589b7f7572115eef431e2f/fuzzer_astfuzzerasan/server.log](https://s3.amazonaws.com/clickhouse-test-reports/55007/d5d3cf0e9d0eed5af9589b7f7572115eef431e2f/fuzzer_astfuzzerasan/server.log)

**Comment by alexey-milovidov** [comment]
It indicates an error in your pull request https://github.com/ClickHouse/ClickHouse/pull/55007

**Comment by alexey-milovidov** [comment]
Update it with the master branch.
