### ISSUE TITLE
Lightweight delete on table with JSON column throws `no physical column _row_exists in table` error

### ISSUE THREAD

**Issue by DerekChia** [ClickHouse/ClickHouse#55076]
**Describe the unexpected behaviour**
Lightweight delete does not work with table that has JSON column

**How to reproduce**
* Version 23.3.13.6 (latest supported 23.3 LTS)

```
set allow_experimental_object_type = 1;

CREATE OR REPLACE TABLE tbl (a UInt32, b JSON) ENGINE = MergeTree() ORDER BY a;

INSERT INTO tbl VALUES (1, '{"k": "v"}');

DELETE FROM tbl WHERE a = 1;
```

**Expected behavior**
Row should be deleted as expected

**Error message and/or stacktrace**
```
Received exception from server (version 23.3.13):
Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Exception happened during execution of mutation 'mutation_2.txt' with part 'all_1_1_0' reason: 'Code: 16. DB::Exception: There is no physical column _row_exists in table. (NO_SUCH_COLUMN_IN_TABLE) (version 23.3.13.6 (official build))'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED)
```

**Additional context**
This error is only thrown in 23.3 and 23.4. 23.5 and above works fine.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/49509

**Comment by den-crane** [comment]
v23.5.1.3174-stable.md:* Ignore LWD column in checkPartDynamicColumns [#49737](https://github.com/ClickHouse/ClickHouse/pull/49737) ([Alexander Gololobov](https://github.com/davenger)).
