### ISSUE TITLE
 I want to use replacingMergetree table as a storage table for distributed table engine.

### ISSUE THREAD

**Issue by Ragavendra-Vigneshwaran-R** [ClickHouse/ClickHouse#55082]
I have installed Clickhouse with 3 shards and 2 replicas. I have wanted to migrate data from another clickhouse database. In source clickhouse, the table engine is replacingMergetree Engine. So I want to use replacingMergetree table as a storage table for the distributed table engine. Is it possible to use it like this in Clickhouse?

**Comment by lampjian** [comment]
Probably not. Distributed table is only a cluster view of your *MergeTree table. When configuring more than one replica on each shard, you shall use the ReplicatedReplacingMergeTree engine instead. If you use none replicated table engines, then you may get inconsistency data on distributed tables with a randomly choosed replica for each shard. And your data can be different without auto replication on the same shard.

**Comment by Ragavendra-Vigneshwaran-R** [comment]
Let's assume I created a database as 'app' with the replicated engine. In that database, if I create a table as 'table_storage' with replacingMergeTree engine, it will be created in all 3 shards and 2 replica(i.e, all 6 pods). On top of the 'table_stoarge', if i create table as 'table_distributed' with distributed engine, then the distributed table will created in all 3 shards and 2 replicas and the data will be distributed in all 6 pods and store it in 'table_storage'(which has the replacingMergeTree engine), right? Is this possible in clickhouse?

**Comment by den-crane** [comment]
Yes, it is possible, and probably you want to create ReplicatedReplacingMergeTree, but replication using Replicated engines is optional. You can replicate data using Distributed table (internal_replication=false mode).

https://kb.altinity.com/engines/

**Comment by Ragavendra-Vigneshwaran-R** [comment]
Thanks @den-crane for your answer.
