### ISSUE TITLE
Flaky test test_storage_s3_queue

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#55090]
Stats [here](https://play.clickhouse.com/play?user=play#c2VsZWN0IAp0b1N0YXJ0T2ZIb3VyKGNoZWNrX3N0YXJ0X3RpbWUpIGFzIGQsCmNvdW50KCksICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSwgIGFueShyZXBvcnRfdXJsKQpmcm9tIGNoZWNrcyB3aGVyZSAnMjAyMi0wNi0wMScgPD0gY2hlY2tfc3RhcnRfdGltZSBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3N0b3JhZ2VfczNfcXVldWUvdGVzdC5weTo6dGVzdF9tdWx0aXBsZV90YWJsZXNfc3RyZWFtaW5nX3N5bmNfZGlzdHJpYnV0ZWQlJyBhbmQgdGVzdF9zdGF0dXMgaW4gKCdGQUlMJywgJ0ZMQUtZJykgZ3JvdXAgYnkgZCBvcmRlciBieSBkIGRlc2M=)

Fail on master as an example
https://s3.amazonaws.com/clickhouse-test-reports/0/18acc0c19d0c04186b7c6fe1e72971368ad625eb/integration_tests__release__[4_4]/integration_run_parallel5_0.log

**Comment by helifu** [comment]
> `test_storage_s3_queue/test.py::test_multiple_tables_streaming_sync[ordered]`
> 
> [https://s3.amazonaws.com/clickhouse-test-reports/50702/6cc997c519e075ac75c977cfd1b2866ba3fe3cea/integration_tests__asan__[2_6].html](https://s3.amazonaws.com/clickhouse-test-reports/50702/6cc997c519e075ac75c977cfd1b2866ba3fe3cea/integration_tests__asan__%5B2_6%5D.html)

@tavplubix 
I'm not sure whether this [PR](https://github.com/ClickHouse/ClickHouse/pull/55934) can fix the flake test :(

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/55641/d5ee8635941deb231bf7eedf1783f59f2eed9fdf/integration_tests__asan__[2_6].html

**Comment by kssenii** [comment]
waiting for a failure after https://github.com/ClickHouse/ClickHouse/pull/56011
> [https://s3.amazonaws.com/clickhouse-test-reports/55987/073a6a6f0e8074c1a89f0b6f839e52447f8b8b3e/integration_tests__asan__[2_6].html](https://s3.amazonaws.com/clickhouse-test-reports/55987/073a6a6f0e8074c1a89f0b6f839e52447f8b8b3e/integration_tests__asan__%5B2_6%5D.html)

this one does not yet contain the changes from that PR.

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/56142/5c4915e26457d222746ff6267bc1c2e81d1c36a1/integration_tests__asan__[2_6].html
