### ISSUE TITLE
Keeper load balancing based on availability zones

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#55110]
ClickHouse can detect whether it is interacting with Keeper instead of ZooKeeper. And Keeper is compiled with AWS S3 SDK since it has an ability to offload old logs and snapshots to an object storage. 

Why not to combine these two facts together and implement the load balancing based on AZs? So each ClickHouse Server instance would prefer connecting to a Keeper replica in the same AZ.

The strategy should be as follows: 
- Keeper get the AZ where it is deployed using EC2MetadataClient and expose to a system node (or client may query it via 4LW `gtaz`) 
- ClickHouse performs "handshakes" to each Keeper replica and if it finds one in the same AZ - connects to it. Otherwise falls back to random choice.

**Comment by nikitamikhaylov** [comment]
Check also: https://github.com/ClickHouse/ClickHouse/issues/47837

**Comment by alexey-milovidov** [comment]
Let's implement this: https://github.com/ClickHouse/ClickHouse/issues/5161

**Comment by chhetripradeep** [comment]
I feel this should be already possible with kubernetes's topology aware routing feature: https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/ which should be available in our production k8s clusters.

**Comment by chhetripradeep** [comment]
I feel this should be already possible with kubernetes's topology aware routing feature: https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/

**Comment by incfly** [comment]
Looked a bit on the k8s toplology aware feature, one limitation

> In a three zone cluster, this means 9 or more endpoints. If there are fewer than 3 endpoints per zone, there is a high (≈50%) probability that the EndpointSlice controller will not be able to allocate endpoints evenly and instead will fall back to the default cluster-wide routing approach.

In case where one keeper pod per AZ (3 keeper in total, rather 9 as required), k8s would not do good job for load balancing.

**Comment by chhetripradeep** [comment]
There are certain situation for which I am not sure about how such feature will work for example when people do deployments.

Let say we have the cluster in the ideal condition
- CH<sub>az1</sub> is connected to CK<sub>az1</sub>
- CH<sub>az2</sub> is connected to CK<sub>az2</sub>
- CH<sub>az3</sub> is connected to CK<sub>az3</sub>

where CK = Keeper & CH = Server

Let's say someone does a rolling restart of keeper cluster.

- CK<sub>az3</sub> will go down, when CH<sub>az3</sub> will try and re-connect, it will see only CK<sub>az1</sub> and CK<sub>az2</sub> as healthy so will get connected to any one of those two
- CK<sub>az2</sub> will go down, when CH<sub>az2</sub> will try and re-connect, it will see only CK<sub>az1</sub> and CK<sub>az3</sub> as healthy so will get connected to any one of those two
- CK<sub>az1</sub> will go down, when CH<sub>az1</sub> will try and re-connect, it will see only CK<sub>az2</sub> and CK<sub>az3</sub> as healthy so will get connected to any one of those two

So the setup will go to a state where clickhouse server is connecting to a clickhouse keeper in different AZ.

**Comment by chhetripradeep** [comment]
Nice, i liked the idea of client side force reconnect. thank you for describing @incfly
