### ISSUE TITLE
predicate expression optimization  not work in view

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#5514]
1 clickhouse version 19.7.3.1  
2 I set enable_optimize_predicate_expression=1 in clickhouse client
3.1 create table bill (no String, fee Int64 , date Date) engine = ReplacingMergeTree(date,(no,date),8192)
3.2 create view bill_determine_view as 
select no, any(fee) as fee,any(date) as date from  (
 select * from bill order by date desc
) group by no

4 execute 
select * from bill where date='xxx' 
and 
select * from bill_determine_view where date='xx'

the data in bill will change ,so I use replacing engine, create the view to get the last record

I find the predicate expression optimization  not work here, select from bill_view always is slower much than select from bill

Is there something wrong with the config or the view I create ?

relavated issue [issue](https://github.com/yandex/ClickHouse/issues/863)

**Comment by peaksnail** [comment]
there has  any(date) as date in the view  and I use date='xxx'  as condition , maybe the any(date) is found in WHERE?

**Comment by den-crane** [comment]
> order by date desc

Pushdown disabled for "order by" due https://github.com/yandex/ClickHouse/issues/3885

**Comment by den-crane** [comment]
```
select no, any(fee) as fee,any(date) as date from (
select * from bill order by date desc
) group by no

```

it is the same as `select * from bill FINAL`

another option is `select no, argMax(fee, date) as fee, max(date) as date from bill group by no`

**Comment by peaksnail** [comment]
@den-crane  thanks

 If I create table bill (no String, fee Int64 , updateDate Date ,createdate Date) engine = ReplacingMergeTree(createdate,(no,createdate),8192) with adding a updateDate field, but the updateDate field is not set in the primary key.

and the data in table will be the same except updateDate field,

can I use the sql "select * from bill FINAL" to get the same result?

**Comment by peaksnail** [comment]
I find that when I create view with sql "select * from bill FINAL", the predicate expression pushdown disabled,But it works fine with sql "select no, argMax(fee, date) as fee, max(date) as date from bill group by no"

**Comment by den-crane** [comment]
My idea was that you don't need view because just need to add FINAL. So view is unnecessary.

**Comment by den-crane** [comment]
is not relevant anymore. 

Predicate pushdown works against view with FINAL

```

create table bill (no String, fee Int64 , date Date) engine = ReplacingMergeTree(date,(no,date),8192)

insert into bill select toString(number), number, '2020-01-01' from numbers(1000000);
insert into bill select toString(number), number, '2019-01-01' from numbers(1);


create view bill_determine_view1 as select * from bill FINAL;
SELECT *
FROM bill_determine_view1
WHERE date = '2019-01-01'

┌─no─┬─fee─┬───────date─┐
│ 0  │   0 │ 2019-01-01 │
└────┴─────┴────────────┘

1 rows in set. Elapsed: 0.001 sec.

20.4.1.2722

```
