### ISSUE TITLE
Publish the self-contained binary without a debug info

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#55181]
**Use case**

Someone on the internet pointed out that it is large: https://twitter.com/eatonphil/status/1707783632566292596
The reason for the size is that we include the debug info to have line numbers in stack traces.
Maybe it is not needed - the symbol names will be present anyway.

If we will remove the debug info, it will be well under 100 MB.

CC @eatonphil

**Comment by eatonphil** [comment]
That's awesome to hear! Great work getting it down from a few years ago!

**Comment by brancz** [comment]
FYI it’s not a fully released product yet, but we offer hosted [debuginfod](https://sourceware.org/elfutils/Debuginfod.html) servers as part of Polar Signals Cloud, which lots of our customers are using to upload debuginfos in CI/CD but then still have debuginfos available whenever they want to launch a debugger or profiler (it’s deeply integrated into perf, gdb and more). If this sounds interesting we’d love to sponsor the clickhouse project with this service.

**Comment by l1t1** [comment]
does it mean we needn't uncompress and strip? for example, the file download from
https://builds.clickhouse.com/master/aarch64v80compat/clickhouse  is 606MB. 
after run clickhouse, it became 3454486984 bytes. 
after strip, it became  389703504 bytes. will we get 389MB directly?

**Comment by l1t1** [comment]
I download it (https://builds.clickhouse.com/master/aarch64v80compat/clickhouse), it's 112MB. After running it, it decompressed to 559MB.  Great.

**Comment by alexey-milovidov** [comment]
Only 109 MB as of today :)
