### ISSUE TITLE
When using `async_insert=1, wait_for_async_insert=0` (some?) exceptions are silently discarded

### ISSUE THREAD

**Issue by pkit** [ClickHouse/ClickHouse#55194]
Using a table with the schema `key String, value String`.
Trying to insert using async:
```sql
INSERT INTO `db`.`table` SETTINGS async_insert=1, wait_for_async_insert=0 FORMAT JSONEachRow
{"key":"a","value":1}
{"key":"b","value":"2"}
```
The rows are not inserted, but no errors appear in `system.query_log`.
The exception can be surfaced by either:
- using `wait_for_async_insert=1`
- checking for errors in `clickhouse-server.log` file

The exception is:
```
Code: 26. DB::ParsingException: Cannot parse JSON string: expected opening quote: (while reading the value of key value): While executing WaitForAsyncInsert: (at row 1)
. (CANNOT_PARSE_QUOTED_STRING) (version 23.8.1.2992 (official build))
```

**Comment by CurtizJ** [comment]
It's expected behaviour. You can check errors in `system.asynchronous_insert_log` table ([docs](https://clickhouse.com/docs/en/operations/system-tables/asynchronous_insert_log)).

**Comment by pkit** [comment]
@CurtizJ 
`desc system.asynchronous_insert_log`
Table not found
There's no such table in Clickhouse Cloud?

**Comment by pkit** [comment]
Ah, it's created when the first async insert happens...
Pretty peculiar behavior, considering all other `async*` tables are there...
