### ISSUE TITLE
Insert parquet files using http

### ISSUE THREAD

**Issue by AkhtemWays** [ClickHouse/ClickHouse#55203]
Im trying to load parquet files into clickhouse file by file using http, on the page of http interface documentation I didn't find something similar that was used in clickhouse client documentation - example:
```
clickhouse-client --host myHost --port myPort --user myUser --password myPassword --query="INSERT INTO myTable FORMAT Parquet" < part-5345433.parquet
```
Basically my question is - is there a way or guide of how to do the same for http interface?

**Comment by den-crane** [comment]
But it's exactly the same as

https://clickhouse.com/docs/en/interfaces/http

```
echo -ne '10\n11\n12\n' | curl 'http://localhost:8123/?query=INSERT%20INTO%20t%20FORMAT%20TabSeparated' --data-binary @-
```
