### ISSUE TITLE
Could you please make ClickHouse refresh Kerberos tickets without restart?

### ISSUE THREAD

**Issue by paf91** [ClickHouse/ClickHouse#55200]
When I'm using Kerberos auth for kafka engine with properties in config.xml
```
    <kafka>
        <security_protocol>SASL_SSL</security_protocol>
        <sasl_kerberos_keytab>/etc/clickhouse-server/ssl/some_keytab.keytab</sasl_kerberos_keytab>
        <sasl_kerberos_principal>clickhouse/SOME_HOST_CONTAINER@MYDOMAIN.COM</sasl_kerberos_principal>
        <sasl_mechanism>GSSAPI</sasl_mechanism>
        <sasl_kerberos_service_name>kafka</sasl_kerberos_service_name>
        <ssl_key_location>/etc/clickhouse-server/ssl/some_key.pem</ssl_key_location>
        <ssl_ca_location>/etc/clickhouse-server/ssl/ca.pem</ssl_ca_location>
        <ssl_certificate_location>/etc/clickhouse-server/ssl/kafka_cert.pem</ssl_certificate_location>
    </kafka>
```
Clickhouse won't refresh kerberos ticket unlress restarted
**How to reproduce**

Which ClickHouse server version to use: v23.2.2 revision 54461
Configure clickhouse to use kafka with Kerberos with example config above. Create tables according to Kafka Integration page: https://clickhouse.com/docs/ru/engines/table-engines/integrations/kafka
Wait until kerberos ticket expires. Check cache file: ```klist -c /tmp/krb5cc_<clickhouse-user-id>``` (for clickhouse user id run command `id clickhouse`) as it will show no updates on ticket renewal

**Expected behavior**
Clickhouse succesfully refresh kerberos ticket in cache file ```/tmp/krb5cc_<clickhouse-user-id>```

**Error message and/or stacktrace**
After ticket expiration date clickhouse will not refresh ticket unless restarted and gives following errors:

```
2023.06.02 07:26:26.171723 [ 58647 ] {} <Warning> StorageKafka (mykafkatopic1): Can't get assignment. Will keep trying.
2023.06.02 07:26:26.312404 [ 58648 ] {} <Error> StorageKafka (some_queue): [rdk:ERROR] [thrd:app]: ClickHouse-SOME_HOST_CONTAINER-default-some_queue#consumer-1: GroupCoordinator: SOME_KAFKA_SERVER:9093: Failed to initialize SASL authentication: SASL handshake failed (start (-1)): SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Ticket expired) (after 734ms in state AUTH_REQ, 4 identical error(s) suppressed)
2023.06.02 07:26:26.362596 [ 58648 ] {} <Warning> StorageKafka (some_queue): Can't get assignment. Will keep trying.
2023.06.02 07:26:26.444624 [ 58761 ] {} <Warning> StorageKafka (mykafkatopic2): Can't get assignment. Will keep trying.
2023.06.02 07:26:26.724434 [ 58675 ] {} <Warning> StorageKafka (mykafkatopic1): Can't get assignment. Will keep trying.
--
2023.06.02 07:26:31.889596 [ 58675 ] {} <Warning> StorageKafka (some_queue): Can't get assignment. Will keep trying.
2023.06.02 07:26:32.123469 [ 58739 ] {} <Warning> StorageKafka (mykafkatopic2): Can't get assignment. Will keep trying.
2023.06.02 07:26:32.249493 [ 58736 ] {} <Warning> StorageKafka (mykafkatopic1): Can't get assignment. Will keep trying.
2023.06.02 07:26:32.346971 [ 58858 ] {} <Critical> StorageKafka (mykafkatopic2): [rdk:LIBSASL] [thrd:GroupCoordinator]: GroupCoordinator/1546345936: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Ticket expired)
2023.06.02 07:26:32.422173 [ 58841 ] {} <Notice> StorageKafka (mykafkatopic3): [rdk:LIBSASL] [thrd:GroupCoordinator]: GroupCoordinator/1546345936: GSSAPI client step 1
2023.06.02 07:26:32.442197 [ 58692 ] {} <Warning> StorageKafka (some_queue): Can't get assignment. Will keep trying.
2023.06.02 07:26:32.502312 [ 58854 ] {} <Critical> StorageKafka (mykafkatopic1): [rdk:LIBSASL] [thrd:GroupCoordinator]: GroupCoordinator/1546345936: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Ticket expired)
```

**Comment by filimonov** [comment]
Can you try 

```
<sasl_kerberos_min_time_before_relogin> ... 
```

See sasl.kerberos.min.time.before.relogin in https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md

**Comment by paf91** [comment]
According to source code:

https://clickhouse.com/codebrowser/ClickHouse/src/Storages/Kafka/StorageKafka.cpp.html
if USE_KRB5
--
if (kafka_config.has_property("sasl.kerberos.kinit.cmd"))
LOG_WARNING(log, "sasl.kerberos.kinit.cmd configuration parameter is ignored.");
 
kafka_config.set("sasl.kerberos.kinit.cmd","");
kafka_config.set("sasl.kerberos.min.time.before.relogin","0");


</body>
</html>if USE_KRB5
    if ([kafka_config](https://clickhouse.com/codebrowser/ClickHouse/src/Storages/Kafka/StorageKafka.cpp.html#104kafka_config).[has_property](https://clickhouse.com/codebrowser/ClickHouse/contrib/cppkafka/src/configuration.cpp.html#_ZNK8cppkafka13Configuration12has_propertyERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE)("sasl.kerberos.kinit.cmd"))
        [LOG_WARNING](https://clickhouse.com/codebrowser/ClickHouse/src/Common/logger_useful.h.html#118)([log](https://clickhouse.com/codebrowser/ClickHouse/src/Storages/Kafka/StorageKafka.h.html#DB::StorageKafka::log), "sasl.kerberos.kinit.cmd configuration parameter is ignored.");
    [kafka_config](https://clickhouse.com/codebrowser/ClickHouse/src/Storages/Kafka/StorageKafka.cpp.html#104kafka_config).[set](https://clickhouse.com/codebrowser/ClickHouse/contrib/cppkafka/include/cppkafka/configuration_base.h.html#_ZN8cppkafka17ConfigurationBase3setERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKc)("sasl.kerberos.kinit.cmd","");
    [kafka_config](https://clickhouse.com/codebrowser/ClickHouse/src/Storages/Kafka/StorageKafka.cpp.html#104kafka_config).[set](https://clickhouse.com/codebrowser/ClickHouse/contrib/cppkafka/include/cppkafka/configuration_base.h.html#_ZN8cppkafka17ConfigurationBase3setERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPKc)("sasl.kerberos.min.time.before.relogin","0");

**Comment by Dnnd** [comment]
I can confirm that we have this issue as well. I've tested it with:
- Clickhouse-server version: `23.11.3`
- Kafka version: `7.5.2`

It seems like this PR (https://github.com/ClickHouse/ClickHouse/pull/38105) was supposed to replace `kinit` command with a manual implementation of Kerberos ticket initialization flow (motivation - https://github.com/ClickHouse/ClickHouse/issues/27651), but it also disabled ticket refresh by hardcoding `sasl.kerberos.min.time.before.relogin` to `0`. Ticket refresh in librdkafka also relies on `kinit` command, so I guess it makes sense from the security perspective, but it results in infinite error loop when Kafka engine tries to consume messages while having an expired ticket:

```
2023.12.16 16:27:25.032424 [ 409 ] {} <Critical> StorageKafka (pagerduty_data_kafka_queue): [rdk:LIBSASL] [thrd:GroupCoordinator]: GroupCoordinator/2: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Ticket expired)
2023.12.16 16:27:25.152133 [ 215 ] {} <Warning> StorageKafka (pagerduty_data_kafka_queue): Can't get assignment. Will keep trying.
2023.12.16 16:27:25.193442 [ 174 ] {} <Error> StorageKafka (pagerduty_data_kafka_queue): Consumer error: Local: Authentication failure
2023.12.16 16:27:25.193527 [ 174 ] {} <Error> StorageKafka (pagerduty_data_kafka_queue): There were 1 messages with an error
2023.12.16 16:27:25.193534 [ 174 ] {} <Error> StorageKafka (pagerduty_data_kafka_queue): Only errors left
2023.12.16 16:27:25.352942 [ 101 ] {} <Warning> StorageKafka (pagerduty_data_kafka_queue): Can't get assignment. Will keep trying.
2023.12.16 16:27:25.572002 [ 433 ] {} <Critical> StorageKafka (pagerduty_data_kafka_queue): [rdk:LIBSASL] [thrd:GroupCoordinator]: GroupCoordinator/2: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Ticket expired)
```

An easiest way to reproduce this error is to:
1 - Configure short `ticket_lifetime` and `renew_lifetime` in the KDC server config (e.g. `ticket_lifetime = 60` - 60 seconds)
2 - Start kerberized Kafka and Clickhouse server
3 - Create a Kafka topic (e.g. `kerberos-test`)
4 - Create a Kafka Engine table and a materialized view to consume data from it
5 - Wait until Kerberos ticket is expired
6 - Restart Kafka

Btw there is a workaround - it is still possible to enable `sasl_kerberos_min_time_before_relogin` option on per-topic basis, like this:

```xml
<clickhouse>
    <kafka>
          ....
        <kafka_topic>
            <name>kerberos-test</name>
            <sasl_kerberos_min_time_before_relogin>60</sasl_kerberos_min_time_before_relogin>
        </kafka_topic>
    </kafka>
</clickhouse>
```

**Comment by paf91** [comment]
I am sorry, why is this not planned if it was working until this commit? It's clearly a bug that option sasl_kerberos_min_time_before_relogin couldn't be configured site-wise, and instead only per-topic

**Comment by alexey-milovidov** [comment]
It is not included in our plans, but we are open for contributions.
