### ISSUE TITLE
Cannot write to finalized buffer in GinIndexStore

### ISSUE THREAD

**Issue by Xredys-19** [ClickHouse/ClickHouse#55212]
i'm using clickhouse cluster on ubuntu , the clickhouse version is version 23.6.2.18 (official build), there is three nodes in my cluster, but when creating table the table only created on two nodes and the other node is stuck,  in the error log there is only this error, do I need to add something configuration in config.xml,

the error in clickhouse-server.err.log :

2023.10.03 06:44:42.305115 [ 57699 ] {} <Error> 93658be2-4d2e-435f-be0c-1b87fc9436ba::all_646028_680059_11 (MergeFromLogEntryTask): virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 49. DB::Exception: Cannot write to finalized buffer. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e22b5f5 in /usr/bin/clickhouse
1. ? @ 0x00000000088a7020 in /usr/bin/clickhouse
2. ? @ 0x00000000088a6ed8 in /usr/bin/clickhouse
3. DB::GinIndexStore::writeSegment() @ 0x0000000014726b8f in /usr/bin/clickhouse
4. DB::MergeTreeDataPartWriterOnDisk::finishSkipIndicesSerialization(bool) @ 0x000000001485e6cb in /usr/bin/clickhouse
5. DB::MergedBlockOutputStream::Finalizer::Impl::finish() @ 0x0000000014997095 in /usr/bin/clickhouse
6. DB::MergeTask::MergeProjectionsStage::finalizeProjectionsAndWholeMerge() const @ 0x000000001476a86d in /usr/bin/clickhouse
7. bool std::__function::__policy_invoker<bool ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTask::MergeProjectionsStage::subtasks::'lambda1'(), bool ()>>(std::__function::__policy_storage const*) @ 0x000000001476eb89 in /usr/bin/clickhouse
8. DB::MergeTask::MergeProjectionsStage::execute() @ 0x000000001476ab0b in /usr/bin/clickhouse
9. DB::MergeTask::execute() @ 0x000000001476a4f9 in /usr/bin/clickhouse
10. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x0000000014a20a2f in /usr/bin/clickhouse
11. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x0000000014a1f884 in /usr/bin/clickhouse
12. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x000000001477e367 in /usr/bin/clickhouse
13. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001477ef9a in /usr/bin/clickhouse
14. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e304de3 in /usr/bin/clickhouse
15. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e3075f5 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e300c74 in /usr/bin/clickhouse
17. ? @ 0x000000000e306481 in /usr/bin/clickhouse
18. ? @ 0x00007f0e46dddb43 in ?
19. ? @ 0x00007f0e46e6fa00 in ?
 (version 23.6.2.18 (official build))
2023.10.03 06:44:42.305245 [ 57699 ] {} <Error> void DB::printExceptionWithRespectToAbort(Poco::Logger *): Code: 49. DB::Exception: Cannot write to finalized buffer. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e22b5f5 in /usr/bin/clickhouse
1. ? @ 0x00000000088a7020 in /usr/bin/clickhouse
2. ? @ 0x00000000088a6ed8 in /usr/bin/clickhouse
3. DB::GinIndexStore::writeSegment() @ 0x0000000014726b8f in /usr/bin/clickhouse
4. DB::MergeTreeDataPartWriterOnDisk::finishSkipIndicesSerialization(bool) @ 0x000000001485e6cb in /usr/bin/clickhouse
5. DB::MergedBlockOutputStream::Finalizer::Impl::finish() @ 0x0000000014997095 in /usr/bin/clickhouse
6. DB::MergeTask::MergeProjectionsStage::finalizeProjectionsAndWholeMerge() const @ 0x000000001476a86d in /usr/bin/clickhouse
7. bool std::__function::__policy_invoker<bool ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTask::MergeProjectionsStage::subtasks::'lambda1'(), bool ()>>(std::__function::__policy_storage const*) @ 0x000000001476eb89 in /usr/bin/clickhouse
8. DB::MergeTask::MergeProjectionsStage::execute() @ 0x000000001476ab0b in /usr/bin/clickhouse
9. DB::MergeTask::execute() @ 0x000000001476a4f9 in /usr/bin/clickhouse
10. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x0000000014a20a2f in /usr/bin/clickhouse
11. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x0000000014a1f884 in /usr/bin/clickhouse
12. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x000000001477e367 in /usr/bin/clickhouse
13. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x000000001477ef9a in /usr/bin/clickhouse
14. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e304de3 in /usr/bin/clickhouse
15. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e3075f5 in /usr/bin/clickhouse
16. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e300c74 in /usr/bin/clickhouse
17. ? @ 0x000000000e306481 in /usr/bin/clickhouse
18. ? @ 0x00007f0e46dddb43 in ?
19. ? @ 0x00007f0e46e6fa00 in ?
 (version 23.6.2.18 (official build))

this is my config.xml : 
![image](https://github.com/ClickHouse/ClickHouse/assets/88485337/d2d9e894-e366-4420-a0cc-b9ff2b00764a)

creating table command : 
CREATE TABLE IF NOT EXISTS default.testinsert40 ON CLUSTER chprod01 (id String, created_at DateTime('UTC')) ENGINE = ReplicatedMergeTree PARTITION BY cityHash64(created_at) % 10 PRIMARY KEY id ORDER BY id

![image](https://github.com/ClickHouse/ClickHouse/assets/88485337/aa6658a8-3cc9-4703-83d9-0bcbdb60e623)

**Comment by canhld94** [comment]
The error you posted here isn't related. It's the `DDLWorker` is stuck while executing DDL for `ON CLUSTER`. You can check where the DDL stuck by:

```
# find the tid of DDL worker
ps -eL | grep DDLWorker
gdb -p <ddl worker tid> -ex "bt" -ex "set confirm off" -ex "q"
```

Note: do this while running `ON CLUSTER` query.

**Comment by tavplubix** [comment]
cc: @rschu1ze, @CheSema

**Comment by rschu1ze** [comment]
Dupes #52593, please upgrade to a newer ClickHouse server.
