### ISSUE TITLE
Slow inserts for s3 and s3Cluster table functions while using LIMIT with INSERT INTO .. SELECT FROM

### ISSUE THREAD

**Issue by chhetripradeep** [ClickHouse/ClickHouse#55221]
**Describe what's wrong**

Running following query with LIMIT slows down.
```
INSERT INTO SETTINGS .. SELECT .. FROM s3Cluster(..)
```

- Without LIMIT the query completed in 6.7 seconds

<img width="1474" alt="without-limit" src="https://github.com/ClickHouse/ClickHouse/assets/30620077/4fea3e40-528a-4029-81ff-5a0bbc538bcb">

- With LIMIT query became slow and took around 15.6 seconds

<img width="1476" alt="with-limit" src="https://github.com/ClickHouse/ClickHouse/assets/30620077/3aa7a1f7-46e6-4853-b84c-0501e2d08199">

- `parallel_distributed_insert_select = 2` has nothing to do with slowness since with disabling it, it is still slow

<img width="1472" alt="Screenshot 2023-10-04 at 10 24 13 AM" src="https://github.com/ClickHouse/ClickHouse/assets/30620077/f44bda4c-8ba1-4a69-95ba-1141e6342fe8">

**Does it reproduce on recent release?**

Yes

**Expected behavior**

Adding LIMIT should have actually completed faster than without LIMIT but it became slow.

**Comment by tavplubix** [comment]
Please share queries as text, not as screenshots, so we will be able to copy them.

**Comment by Algunenano** [comment]
Please reopen if you can provide a reproducer
