### ISSUE TITLE
Neighbor function not working properly in array functions

### ISSUE THREAD

**Issue by skiiddie** [ClickHouse/ClickHouse#55223]
**Description**
Using the neighbor function in combination with array functions gives incorrect results.
A link to reproducer in [play.clickhouse.com](https://play.clickhouse.com/play?user=play#U0VMRUNUIG51bWJlciwgYXJyYXlNYXAoeCAtPiBuZWlnaGJvcihudW1iZXIsIHgpLCByYW5nZSgxLCA1KSkgRlJPTSBudW1iZXJzKDEwKTs=).

**Does it reproduce on recent release?**
Yes, at least on 23.9.1.1753 and below.

**How to reproduce**
* Which ClickHouse server version to use: 23.9.1.1753 or below
* Queries to run that lead to unexpected result: `SELECT number, arrayMap(x -> neighbor(number, x), range(1, 5)) FROM numbers(10);`

**Expected behavior**
Query should return next values:
0 | ["1","2","3","4"]
1 | ["2","3","4","5"]
2 | ["3","4","5","6"]
3 | ["4","5","6","7"]
4 | ["5","6","7","8"]
5 | ["6","7","8","9"]
6 | ["7","8","9","0"]
7 | ["8","9","0","0"]
8 | ["9","0","0","0"]
9 | ["0","0","0","0"]

**Comment by den-crane** [comment]
AFAIK arrayMap is not supposed to access other rows in the table.

**Comment by den-crane** [comment]
And it never worked https://fiddle.clickhouse.com/58e8585d-fbe4-4463-97df-383b555224ed

**Comment by den-crane** [comment]
and it's known issue https://github.com/ClickHouse/ClickHouse/issues/17939#issuecomment-782831380
