### ISSUE TITLE
`groupUniqArrayArray` is not documented

### ISSUE THREAD

**Issue by samuelcolvin** [ClickHouse/ClickHouse#55229]
As far as I can tell, `groupUniqArrayArray` is not documented, although it exists and does exactly what I want (I think).

I found it by guessing at it's existence from `groupArrayArray`.

**Comment by samuelcolvin** [comment]
follow up, am I right in assuming `groupUniqArrayArray` is stable and not experimental or liable to be removed?

**Comment by nickitat** [comment]
`-Array` is a [suffix](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/combinators#-array) that could be added to many different functions. I doubt it is possible to list all the possible cases.

**Comment by samuelcolvin** [comment]
I would argue the current documentation is inconsistent and somewhat confusing.

For example, `groupUniqArrayArray` is specifically listed under the documentation for [`SimpleAggregateFunction`](https://clickhouse.com/docs/en/sql-reference/data-types/simpleaggregatefunction).

I think it would be helpful to have a unified list of all functions, with links to the specific documentation if it exists, or just included plain in there's no specific documentation to link to.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/combinators

@samuelcolvin you should understand that combinators allows you to create a new functions on the fly. And it's impossible to document all combinations like `groupUniqIfArrayDistinctIfEachArray`.

**Comment by den-crane** [comment]
all functions is in system.functions, you can check, there is no 

```
select * from system.functions where name = 'groupUniqArrayArray';
0 rows in set.
```
