### ISSUE TITLE
Clickhouse user configuration

### ISSUE THREAD

**Issue by Ragavendra-Vigneshwaran-R** [ClickHouse/ClickHouse#55231]
I have installed Clickhouse with 3 shards and 2 replicas in eks cluster. The user setting are in /etc/clickhouse-server/users.d/ folder in the clickhouse pod. In that folder, I have added the admin users setting. 

Problem description : 

When connected to the clickhouse in local( inside the clickhouse pod) with admin user and credentials, it throws the below exception 

Exception : 
command used --> clickhouse-client -u admin --password '****'
ClickHouse client version 23.7.5.30 (official build).
Connecting to localhost:9000 as user admin.
Code: 516. DB::Exception: Received from localhost:9000. DB::Exception: admin: Authentication failed: password is incorrect, or there is no user with such name.. (AUTHENTICATION_FAILED)

But when I connect to the clickhouse through the service URL as host with admin user credentials, it getting connected to clickhouse.

command used --> clickhouse-client -h clickhouse-clickhouse -u admin --password '****'
ClickHouse client version 23.7.5.30 (official build).
Connecting to clickhouse-clickhouse:9000 as user admin.
Connected to ClickHouse server version 23.7.5 revision 54465.
chi-clickhouse-prod-cluster-shard0-0-0.chi-clickhouse-prod-cluster-shard0-0.clickhouse.svc.cluster.local :)

Does this mean the admin user setting have to be present in under /etc/clickhouse-server/users.d/ folder and also be present in /etc/clickhouse-server/users.xml file in clickhouse?

**Comment by den-crane** [comment]
it means that you misconfigured `<network>` section and disallowed to connect from a localhost.

please share your configs / hide passwords with ****

**Comment by Ragavendra-Vigneshwaran-R** [comment]
Got the issue. I didn't add localhost in the admin user network/ip section. Thanks @den-crane for your answer.
