### ISSUE TITLE
Clickhouse keeps crashes with  Invalid number of rows in Chunk column errors

### ISSUE THREAD

**Issue by michals144** [ClickHouse/ClickHouse#55233]
Hi, i am getting these errors a lot on the log:
And clickhouse keeps crashing.
Any ideas?

**Errors in the log**
 (version 22.5.4.19 (official build))
2023.10.04 12:17:27.970093 [ 60 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 49. DB::Exception: Invalid number of rows in Chunk column Nullable(String) position 4: expected 6286, got 6235: While executing MergeTreeSequentialSource. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb49413a in /usr/bin/clickhouse
1. DB::Chunk::checkNumRowsIsConsistent() @ 0x16cf5eee in /usr/bin/clickhouse
2. DB::MergeTreeSequentialSource::generate() @ 0x1682b751 in /usr/bin/clickhouse
3. DB::ISource::tryGenerate() @ 0x16d04915 in /usr/bin/clickhouse
4. DB::ISource::work() @ 0x16d045ba in /usr/bin/clickhouse
5. DB::SourceWithProgress::work() @ 0x16f4b702 in /usr/bin/clickhouse
6. DB::ExecutionThreadContext::executeTask() @ 0x16d20fc8 in /usr/bin/clickhouse
7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16d14cde in /usr/bin/clickhouse
8. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x16d144e0 in /usr/bin/clickhouse
9. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x16d25bae in /usr/bin/clickhouse
10. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x16d25f0c in /usr/bin/clickhouse
11. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x166ba10b in /usr/bin/clickhouse
12. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x166ba06b in /usr/bin/clickhouse
13. DB::MergeTask::execute() @ 0x166bfa5a in /usr/bin/clickhouse
14. DB::MergePlainMergeTreeTask::executeStep() @ 0x166aee4c in /usr/bin/clickhouse
15. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xb469aa5 in /usr/bin/clickhouse
16. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xb4694ee in /usr/bin/clickhouse
17. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb5438ba in /usr/bin/clickhouse
18. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0xb5458a4 in /usr/bin/clickhouse
19. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb540ce7 in /usr/bin/clickhouse
20. ? @ 0xb54471d in /usr/bin/clickhouse
21. ? @ 0x7f762fbfd609 in ?
22. __clone @ 0x7f762fb22133 in ?

**Comment by michals144** [comment]
We are getting this error when trying to copy the problematic data:
 2023.10.04 13:08:09.627964 [ 269 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2023.10.04 13:08:09.628004 [ 269 ] <Fatal> BaseDaemon: Stack trace: 0x1616cd5f 0x1616b0b7 0x16ff572d 0x16ff42f3 0x16fe8a80 0x16fe988d 0x16fe7c60 0x16d04915 0x16d045ba 0x16f4b702 0x16d20fc8 0x16d14cde 0x16d165a4 0xb540ce7 0xb54471d 0x7fa9452ad609 0x7fa9451d2133
2023.10.04 13:08:09.628075 [ 269 ] <Fatal> BaseDaemon: 2. DB::ColumnArray::filterString(DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 15ul, 16ul> const&, long) const @ 0x1616cd5f in /usr/bin/clickhouse

**Comment by den-crane** [comment]
> 22.5.4.19 

BTW, 22.5 is out of support more than 1 year. Try supported versions, 23.3, 23.9 ?

**Comment by michals144** [comment]
We upgraded to 23.3 and had memory issues (I opened another ticket on this)
So we downgraded back to this version

**Comment by den-crane** [comment]
try 22.8.21.38

**Comment by den-crane** [comment]
or try 22.12.6.22

**Comment by michals144** [comment]
These versions have fixes for the issue we are experiencing?

**Comment by den-crane** [comment]
No idea. I guess that LOGICAL_ERROR could be a consequences of the downgrade.

**Comment by michals144** [comment]
Looks like we keep cleaning corrupted data and it keeps appearing again.
There are segmentation faults before each crash:
`10.04 21:29:14.038339 [ 247 ] {} <Fatal> BaseDaemon: Calculated checksum of the binary: 64810A013BD14FBFD592423F80203DB9. There is no information about the reference checksum.
2023.10.04 21:31:02.891280 [ 245 ] {} <Fatal> BaseDaemon: ########################################
2023.10.04 21:31:02.891343 [ 245 ] {} <Fatal> BaseDaemon: (version 22.5.4.19 (official build), build id: 4B23E5A78914F54C) (from thread 56) (query_id: resource_event_sampling::bd09b7ae9bad8831eb85b94385360d94_1064146_1064422_19) (query: ) Received signal Segmentation fault (11)
2023.10.04 21:31:02.891364 [ 245 ] {} <Fatal> BaseDaemon: Address: 0x7fd1621c9000 Access: write. Attempted access has violated the permissions assigned to the memory area.
2023.10.04 21:31:02.891376 [ 245 ] {} <Fatal> BaseDaemon: Stack trace: 0xb48d22a 0x15284c5c 0x15280e43 0x161c2a3e 0x16f6a58b 0x15f3923b 0x16d20fc8 0x16d14cde 0x16d144e0 0x16d25bae 0x16d25f0c 0x166ba10b 0x166ba06b 0x166bfa5a 0x166aee4c 0xb469aa5 0xb4694ee 0xb5438ba 0xb5458a4 0xb540ce7 0xb54471d 0x7fd1f68f4609 0x7fd1f6819133
2023.10.04 21:31:02.891407 [ 245 ] {} <Fatal> BaseDaemon: 2. memcpy @ 0xb48d22a in /usr/bin/clickhouse
2023.10.04 21:31:02.891429 [ 245 ] {} <Fatal> BaseDaemon: 3. DB::ReverseIndex<unsigned long, DB::ColumnString>::insert(StringRef const&) @ 0x15284c5c in /usr/bin/clickhouse
2023.10.04 21:31:02.891437 [ 245 ] {} <Fatal> BaseDaemon: 4. DB::ColumnUnique<DB::ColumnString>::uniqueInsertData(char const*, unsigned long) @ 0x15280e43 in /usr/bin/clickhouse
2023.10.04 21:31:02.891446 [ 245 ] {} <Fatal> BaseDaemon: 5. DB::ColumnLowCardinality::insertFrom(DB::IColumn const&, unsigned long) @ 0x161c2a3e in /usr/bin/clickhouse
2023.10.04 21:31:02.891457 [ 245 ] {} <Fatal> BaseDaemon: 6. DB::IMergingAlgorithm::Status DB::MergingSortedAlgorithm::mergeImpl<DB::SortingHeap<DB::SortCursor> >(DB::SortingHeap<DB::SortCursor>&) @ 0x16f6a58b in /usr/bin/clickhouse
2023.10.04 21:31:02.891468 [ 245 ] {} <Fatal> BaseDaemon: 7. DB::IMergingTransform<DB::MergingSortedAlgorithm>::work() @ 0x15f3923b in /usr/bin/clickhouse
2023.10.04 21:31:02.891476 [ 245 ] {} <Fatal> BaseDaemon: 8. DB::ExecutionThreadContext::executeTask() @ 0x16d20fc8 in /usr/bin/clickhouse
2023.10.04 21:31:02.891485 [ 245 ] {} <Fatal> BaseDaemon: 9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x16d14cde in /usr/bin/clickhouse
2023.10.04 21:31:02.891492 [ 245 ] {} <Fatal> BaseDaemon: 10. DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x16d144e0 in /usr/bin/clickhouse
2023.10.04 21:31:02.891499 [ 245 ] {} <Fatal> BaseDaemon: 11. DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x16d25bae in /usr/bin/clickhouse
2023.10.04 21:31:02.891505 [ 245 ] {} <Fatal> BaseDaemon: 12. DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x16d25f0c in /usr/bin/clickhouse
2023.10.04 21:31:02.891513 [ 245 ] {} <Fatal> BaseDaemon: 13. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x166ba10b in /usr/bin/clickhouse
2023.10.04 21:31:02.891520 [ 245 ] {} <Fatal> BaseDaemon: 14. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x166ba06b in /usr/bin/clickhouse
2023.10.04 21:31:02.891526 [ 245 ] {} <Fatal> BaseDaemon: 15. DB::MergeTask::execute() @ 0x166bfa5a in /usr/bin/clickhouse
2023.10.04 21:31:02.891533 [ 245 ] {} <Fatal> BaseDaemon: 16. DB::MergePlainMergeTreeTask::executeStep() @ 0x166aee4c in /usr/bin/clickhouse
2023.10.04 21:31:02.891542 [ 245 ] {} <Fatal> BaseDaemon: 17. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xb469aa5 in /usr/bin/clickhouse
2023.10.04 21:31:02.891549 [ 245 ] {} <Fatal> BaseDaemon: 18. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xb4694ee in /usr/bin/clickhouse
2023.10.04 21:31:02.891558 [ 245 ] {} <Fatal> BaseDaemon: 19. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb5438ba in /usr/bin/clickhouse
2023.10.04 21:31:02.891573 [ 245 ] {} <Fatal> BaseDaemon: 20. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'()::operator()() @ 0xb5458a4 in /usr/bin/clickhouse
2023.10.04 21:31:02.891581 [ 245 ] {} <Fatal> BaseDaemon: 21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb540ce7 in /usr/bin/clickhouse
2023.10.04 21:31:02.891587 [ 245 ] {} <Fatal> BaseDaemon: 22. ? @ 0xb54471d in /usr/bin/clickhouse
2023.10.04 21:31:02.891593 [ 245 ] {} <Fatal> BaseDaemon: 23. ? @ 0x7fd1f68f4609 in ?
2023.10.04 21:31:02.891599 [ 245 ] {} <Fatal> BaseDaemon: 24. __clone @ 0x7fd1f6819133 in ?
2023.10.04 21:31:02.907915 [ 246 ] {} <Fatal> BaseDaemon: ########################################
2023.10.04 21:31:02.907983 [ 246 ] {} <Fatal> BaseDaemon: (version 22.5.4.19 (official build), build id: 4B23E5A78914F54C) (from thread 239) (no query) Received signal Segmentation fault (11)
2023.10.04 21:31:02.908023 [ 246 ] {} <Fatal> BaseDaemon: Address: 0x7ff1 Access: read. Address not mapped to object.
`
