### ISSUE TITLE
Uploading parquet files

### ISSUE THREAD

**Issue by AkhtemWays** [ClickHouse/ClickHouse#55230]
This command loads file using http interface and works just fine.
```
cat file.parquet | curl -H 'X-ClickHouse-User: myUser' -H 'X-ClickHouse-Key: myPassword' myHost:8123/?query=INSERT%20INTO%20database.table%20FORMAT%20Parquet' --data-binary @- 
```
Also when I launched this same command with verbose trace and output, I saw this output
```
Warning: -v, --verbose overrides an earlier trace/verbose option
*   Trying ip:8123...
* TCP_NODELAY set
* Connected to hostName (ip) port 8123 (#0)
> POST /?query=INSERT%20INTO%20database.table%20FORMAT%20Parquet HTTP/1.1
> Host: myHost
> User-Agent: curl/7.68.0
> Accept: */*
> X-ClickHouse-User: myUser
> X-ClickHouse-Key: myPassword
> Content-Length: 1445
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 04 Oct 2023 10:18:07 GMT
< Connection: Keep-Alive
< Content-Type: text/plain; charset=UTF-8
< X-ClickHouse-Server-Display-Name: serverName
< Transfer-Encoding: chunked
< X-ClickHouse-Query-Id: 5bdf6002-0c02-4471-99e7-b85e4851a854
< X-ClickHouse-Timezone: Europe/Berlin
< Keep-Alive: timeout=3
< X-ClickHouse-Summary: {"read_rows":"1","read_bytes":"28","written_rows":"1","written_bytes":"28","total_rows_to_read":"0","result_rows":"1","result_bytes":"28"}
```
But I want to use either some scala client - in my case com.squareup.okhttp library to do the same, or use hadoop streaming approach to do it in mapreduce manner.
The problem is that in both cases clickhouse returns the same error `Code: 117. DB::Exception: Not a Parquet file: While executing ParquetBlockInputFormat. (INCORRECT_DATA) (version 23.6.2.18 (official build))`, which I couldn't find anything about and parquet files are actual normally loadable parquet files, which are read by spark engine.

Scala client approach
```
    val client = new OkHttpClient()

    val url = "http://" + clickhouseHost + ":" + clickhousePort + s"/?query=INSERT%20INTO%20$database.$tableName%20FORMAT%20Parquet"
    val file = new File(getClass.getClassLoader.getResource("file.parquet").getFile)
    val requestBody = new MultipartBuilder()
      .addFormDataPart("data-binary", file.getName,
        RequestBody.create(MediaType.parse("text/plain; charset=UTF-8"), file))
      .build()

    val request = new Request.Builder()
      .url(url)
      .post(requestBody)
      .headers(new Headers.Builder()
        .add("X-ClickHouse-User", clickhouseUser)
        .add("X-ClickHouse-Key", clickhousePassword)
        .add("Content-Type", "application/x-www-form-urlencoded")
        .build)
      .build()
      
     val response = client.newCall(request).execute().body()
    println(response.string())
```
For scala client my question is how to configure it to work properly.

For hadoop streaming approach
```
/opt/hadoop/bin/hadoop jar /opt/hadoop/share/hadoop/tools/lib/hadoop-streaming-3.3.5.jar -input fileParquet -output outputDirectory -mapper /bin/cat -reducer "curl -H 'X-ClickHouse-User: myUser' -H 'X-ClickHouse-Key: myPassword' 'hostName:8123/?query=INSERT%20INTO%20database.tableName%20FORMAT%20Parquet' --data-binary @-"
```

**Comment by den-crane** [comment]
First of all the question is not related to Clickhouse anyhow. 
It's about scala, I would ask it at stackoverflow/tags/scala

>getClass.getClassLoader.getResource("file.parquet").getFile

What is this? Why `getResource`? Do you packed the `file.parquet` into a jar ?

**Comment by AkhtemWays** [comment]
> First of all the question is not related to Clickhouse anyhow. It's about scala, I would ask it at stackoverflow/tags/scala
> 
> > getClass.getClassLoader.getResource("file.parquet").getFile
> 
> What is this? Why `getResource`? Do you packed the `file.parquet` into a jar ?

No it's just a parquet file, location of which I decided to omit. Thank you anyways.
Also, could you give some more hint of what could be the issues of when clickhouse really responds with such errors.

**Comment by den-crane** [comment]
I think you are passing a filename itself instead of parquet as a body in the MultipartBuilder.

Also you can use usual http auth instead of plaintext in the headers (X-ClickHouse-*)/
