### ISSUE TITLE
Impossible to build previous versions in Docker

### ISSUE THREAD

**Issue by alezzqz** [ClickHouse/ClickHouse#55242]
Can be reproduced on any Linux distributive, any configuration.
Im trying to build clickhouse branch 23.3 in container using packager script.

`./docker/packager/packager --package-type=binary --output-dir "$output_dir"`

this version expects to be compiled by clang-15 but generated clickhouse/binary-builder image contains clang-17
as a result compilation fails
Im not sure either it's a bug or there is some specific way to build image with specific compiler exists

**Comment by alexey-milovidov** [comment]
Build without Docker.

**Comment by alexey-milovidov** [comment]
Also, you can build it exactly as in the build logs from here: https://github.com/ClickHouse/ClickHouse/pull/48280
(follow every step precisely)

**Comment by alexey-milovidov** [comment]
Check "build log" here: https://s3.amazonaws.com/clickhouse-test-reports/48280/b88f2fb4fc51de8d0dc109d455b413cbeb45af62/clickhouse_build_check/report.html
