### ISSUE TITLE
Explain AST regression in versions >= 23.8 for parameterized views

### ISSUE THREAD

**Issue by maxjustus** [ClickHouse/ClickHouse#55246]
`EXPLAIN AST` throws `DB::Exception: Substitution `whatever_parameter_name` is not set. (UNKNOWN_QUERY_PARAMETER)` when used with any parameterized view in versions >= 23.8. It works in 23.5, 23.6, and 23.7.

23.9: https://fiddle.clickhouse.com/9d71410c-3240-4a77-9992-e73418a0c630
23.8: https://fiddle.clickhouse.com/f733a795-9803-4a56-8e86-f05d9e1207ba
23.7: https://fiddle.clickhouse.com/2e357309-7902-4efb-8e65-c8e42aaff456

**How to reproduce**

run the following query:

```
EXPLAIN AST
CREATE VIEW numbers_pv AS
SELECT *
FROM numbers
LIMIT {amount:UInt8};
```

**Expected result**

```
CreateQuery  numbers_pv (children 2)
 Identifier numbers_pv
 SelectWithUnionQuery (children 1)
  ExpressionList (children 1)
   SelectQuery (children 3)
    ExpressionList (children 1)
     Asterisk
    TablesInSelectQuery (children 1)
     TablesInSelectQueryElement (children 1)
      TableExpression (children 1)
       TableIdentifier numbers
    QueryParameter amount:UInt8
```

**Error message and/or stacktrace**

```
Received exception from server (version 23.9.1):
Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Substitution `amount` is not set. (UNKNOWN_QUERY_PARAMETER)
(query: EXPLAIN AST
CREATE VIEW numbers_pv AS
SELECT *
FROM numbers
LIMIT {amount:UInt8};)
```

**Additional context**

Reproducible with both clickhouse server and clickhouse-local

**Comment by SmitaRKulkarni** [comment]
Fixed in #56004
