### ISSUE TITLE
Segmentation fault on query with "Engine=Merge + ALL INNER JOIN + WHERE with OR"

### ISSUE THREAD

**Issue by floxard** [ClickHouse/ClickHouse#55272]
this query:

SELECT *
FROM merge('system', '^one$') AS one
ALL INNER JOIN
(
    SELECT *
    FROM system.one
) AS subquery ON one.dummy = subquery.dummy
WHERE (one.dummy = 0) OR (one.dummy = 1)

produces segmentation fault of ClickHouse

proof (latest version): https://fiddle.clickhouse.com/5ca1d3c3-de60-48fd-ad5f-2c7316139c60

**Comment by floxard** [comment]
update: bug can be triggered without JOIN: https://fiddle.clickhouse.com/f55800f9-f432-4a4b-a9cf-40f8ba4ddcdf

**Comment by ucasfl** [comment]
It's related to https://github.com/ClickHouse/ClickHouse/pull/42889.

**Comment by saippuakauppias** [comment]
Also, @floxard  found an undocumented feature that allows you to fix it: `optimize_min_equality_disjunction_chain_length`

https://fiddle.clickhouse.com/b068689d-228f-4fc2-a035-9117bb2d7824
