### ISSUE TITLE
NO_REPLICA_HAS_PART on MERGE_PARTS replication task

### ISSUE THREAD

**Issue by allen12921** [ClickHouse/ClickHouse#55285]
**Describe the unexpected behaviour**
we encountered randomly failed replication task

* Which ClickHouse server version to use
23.8.3.48
* `CREATE TABLE` statements for all tables involved
the total size of client_events data files is about 33GB 
 CREATE TABLE mydb.client_events
(
    `id` String,
    `account_id` FixedString(32),
    `ttl_days` UInt16 DEFAULT 181,
    `client_id` String,
    `created_at` DateTime,
    `customer_id` String,
    `customer_name` String,
    `customer_email` String,
    `customer_mobile` String
]
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/mydb/client_events', '{replica}')
ORDER BY (account_id,client_id, created_at)
TTL created_at + toIntervalDay(ttl_days)
SETTINGS index_granularity = 8192

**Expected behavior**
no error in log file

**Error message and/or stacktrace**
2023.10.07 02:34:37.854845 [ 30332 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {ce04e319-bc8c-4231-adbe-d1943bdc0288::all_45595488_45595492_1}: Code: 234. DB::Exception: No active replica has part all_45595488_45595492_1 or covering part (cannot execute queue-0058357345: MERGE_PARTS with virtual parts [all_45595488_45595492_1]). (NO_REPLICA_HAS_PART), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c630397 in /usr/bin/clickhouse
1. DB::Exception::Exception<String&, String&, String>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<String&>::type, std::type_identity<String>::type>, String&, String&, String&&) @ 0x0000000010c1ee2c in /usr/bin/clickhouse
2. DB::StorageReplicatedMergeTree::executeFetch(DB::ReplicatedMergeTreeLogEntry&, bool) @ 0x00000000127981c7 in /usr/bin/clickhouse
3. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x0000000012e76f3b in /usr/bin/clickhouse
4. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000012bcd239 in /usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c70f15e in /usr/bin/clickhouse
6. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c712c1c in /usr/bin/clickhouse
7. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c711464 in /usr/bin/clickhouse
8. start_thread @ 0x000000000000740b in /usr/lib64/libpthread-2.26.so
9. __clone @ 0x00000000000ed40f in /usr/lib64/libc-2.26.so
 (version 23.8.3.48 (official build))

**Comment by canhld94** [comment]
It can happens in some extreme cases, example, in your case:

- Replica 0 executes log entry `queue-0058357345`. That's a `MERGE_PARTS` entry, but it cannot find the source part to merged, so it tried to fetch the merged part instead
- It found part `all_45595488_45595492_1` on replica 1, so it called for fetching
- But before it could fetch, part `all_45595488_45595492_1` was removed from replica 1, for whatever reason (TTL expired, the part is merged and removed, etc...) --> throwing this exception

The most important thing is to check if two replica is synchronized. 

Possible issue is the latency between two replicas is too high or the network bandwidth is not enough to catch up with the amount of data to be replicated.
