### ISSUE TITLE
Internal_replication is set to true or false for replicated database engine.

### ISSUE THREAD

**Issue by Ragavendra-Vigneshwaran-R** [ClickHouse/ClickHouse#55286]
Let's assume I have 3 shards and 2 replicas of clickhouse cluster and also zookeeper with 3 znodes for replication in my eks cluster. In that, I created a database called "app" with the replicated engine in all shards and replicas (i.e., in all 6 pods). After I created a mergeTree table called "num_storage"( which is created in other shards and replicas because of the replicated database engine) for storing the data. On top of it, I have created a distributed table called "num" for inserting and retrieving the data evenly in shards. If I insert some data into the "num" table ( which is a distributed table), the data will distributed in all shards and data will be replicated into the replica respectively. In this case, do I need to set the internal_replication as true or false? Which one will be best case for above scenario?

**Comment by genzgd** [comment]
When using a Replicated*MergeTree or the Replicated database engine, internal replication should always be set to `true` in your cluster definition.

**Comment by Ragavendra-Vigneshwaran-R** [comment]
Thanks @genzgd for your answer
