### ISSUE TITLE
s3 zero copy, some parts can't be removed

### ISSUE THREAD

**Issue by coulsonm** [ClickHouse/ClickHouse#55284]
This is a fixed issue and already merged into master branch.
(https://github.com/ClickHouse/ClickHouse/issues/52753)
(https://github.com/ClickHouse/ClickHouse/pull/53338)
But why not merge into 23.8.*  lts? (23.9 merged it)

**Comment by den-crane** [comment]
> This is a fixed issue and already merged into master branch.
> (#52753)
> (#53338)

this is improvement. Improvements never backported.
