### ISSUE TITLE
Provide fromDaysSinceYearZero()

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#55308]
#54856 (respectively #54796) added function [toDaysSinceYearZero()](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#todayssinceyearzero). The main reason to add this function was to have something similar as MySQL's [TO_DAYS()](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_to-days) in ClickHouse (besides that, there is probably little practical use for the function).

As per https://github.com/ClickHouse/ClickHouse/pull/54856#issuecomment-1751765802, we should provide the opposite function for consistency, i.e. `fromDaysSinceYearZero()`. See related `from*()` [date/time functions](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions) for starting points.

**Comment by bhavuk2002** [comment]
is this issue resolved?

**Comment by bhavuk2002** [comment]
pls assign me this issue

**Comment by bhavuk2002** [comment]
@rschu1ze I checked the code base and understood that a new file for `fromDaysSinceYearZero()` function has to be created, and referred `toDaysSinceYearZero()`, did i have to write code from the scratch, first making the years counting everything, checking leap years and all.

**Comment by bhavuk2002** [comment]
@rschu1ze 

Its kind of seem to much stuff for me to parse, can you tell me how to approach. I can make a logic to convert number of days to year but your guidance will help.

**Comment by rschu1ze** [comment]
@bhavuk2002 Indeed, you would need to create a new file "src/Functions/fromDaysSinceYearZero.cpp". As a template / inspiration, you may look at the implementation of function [makeDate()](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#makedate). It builds a Date from year / month / day integers which is kind of similar to `fromDaysSinceYearZero()`. To understand how things work, I suggest that you step through `FunctionMakeDate::getReturnTypeImpl()` and `FunctionMakeDate::executeImpl()` using a debugger. Functions derive from interface `IFunction` - its API has documentation, in case you wonder what the individual methods do.

`toDaysSinceYearZero()` calculates its result as the sum of a constant offset in days until 1970 + the days since 1970 (based on the input data), see `ToDaysSinceYearZeroImpl` in Functions/DateTimeTransforms.h. A similar calculation could be done for `fromDaysSinceYearZero()` - that way, you would not need to care about leap years.

**Comment by slvrtrn** [comment]
Apparently, this one is a blocker for Tableau Online, see the duplicate issue: https://github.com/ClickHouse/ClickHouse/issues/55992
