### ISSUE TITLE
[MySql Interface] Client compatibility/protocol regressions in 23.9 with returned data types

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#55310]
Version: `23.9.1.1854`

Client libraries:
- [MySqlConnector](https://github.com/mysql-net/MySqlConnector): .NET
- [JDBC Driver for MySQL (Connector/J)](https://www.mysql.com/products/connector/) using [DBeaver](https://github.com/dbeaver/dbeaver/) : Java

Workflow: [Linq To DB](https://github.com/linq2db/linq2db) ORM tests against ClickHouse using mysql, binary and http protocols (.NET)

We already had several issues with pre-23.9 protocol implementation which I reported (see list below) resulting in hundreds of disabled tests, but 23.9 introduced another set of compatibility issues (200+ failing tests) which we cannot workaround as protocol parsing done by database provider library and it rejects/fails to parse invalid/unexpected data.

Reported before issues:
- #39297
- #39056
- #38790
- #37999

I see that most of issues fall into two categories:
- server reports one column type but sends data in another type (usually reports integer-based type and send string) leading to protocol parser to fail due to unexpected inputs
- server sends out-of-range data (in mysql terms) for reported type

In both cases in my opinion server should use suitable mysql type or use string representation (with column type reported as string)

New issues with 23.9:

1. Somehow issue #37999 became worse and fail some queries that worked before
```sql
select true, false
-- type reported as integer, but server sends "true" and "false" string
-- MySqlConnector: fails to parse provided strings as integers
-- DBeaver: shows 101 (no idea what it means) for both values
```

2. datetime64 type with 7+ digits for ticks reported as datetime (was: string) but MySql DateTime type allows only 6 millisecond registers
```sql
SELECT toDateTime64('2020-02-29 17:54:55.1231234', 7)
-- MySqlConnector: fails to parse fractional second part as it expects 6 digits
-- DBeaver: displays NULL
```

Next one is not an issue for us and existed before.
nan/inf values not supported by MySql and libraries doesn't expect them. I've asked MySqlConnector to add support for them, but other libraries probably will fail to parse it, e.g. DBeaver shows parse error for them (but it also fails to parse it using ClickHouse JDBC driver, which is a driver bug in this case)
```sql
select inf::Double
```

It will take some time to go through 200 tests and check reason for failure, so I will update issue if I found more regressions.

**Comment by slvrtrn** [comment]
Hi @MaceWindu, thanks for an excellent overview of the issues! At a glance, all of those seem very fixable. 

Regarding [linq2db](https://github.com/linq2db/linq2db) failing tests, it looks like this could be a good way to verify the MySQL interface implementation correctness. 

To save us some time learning the tool and setting up the environment, is there a TLDR version on how to run that project's tests on Linux with local ClickHouse so we can verify the progress as we fix the listed issues?

**Comment by slvrtrn** [comment]
@MaceWindu,
> I can create separate branch with runnable tests (current code base has them disabled to not fail CI), but it will take several days as I'm currently busy with other stuff

No rush! I think it will be useful.

> Have you noticed I mentioned that nan/inf values rendering failed with clickhouse driver too?

OK, now I see it. Regarding DBeaver + MySQL => CH, I can't even connect with any driver, it keeps complaining about `name`.

**Comment by MaceWindu** [comment]
That's how it works for me
<details>
  <summary>DBeaver Conection</summary>



![image](https://github.com/ClickHouse/ClickHouse/assets/1099238/19b76409-e76a-4496-a1dd-7a32be24775e)

![image](https://github.com/ClickHouse/ClickHouse/assets/1099238/b2be91ab-6180-497b-93d0-035078be4768)

and probably you will need to open driver  settings to download native client (I already have it downloaded)

![image](https://github.com/ClickHouse/ClickHouse/assets/1099238/c8025c59-b78b-4afe-bf46-aa9be91a449d)

</details>

connecting to local docker instance

```sh
docker pull clickhouse/clickhouse-server:latest
docker run -d --name clickhouse --ulimit nofile=262144:262144 -p 8123:8123 -p 9000:9000 -p 9004:9004 -p 9005:9005 -e CLICKHOUSE_USER=testuser -e CLICKHOUSE_PASSWORD=testuser clickhouse/clickhouse-server:latest

docker exec clickhouse sed -i "0,/<\/default>/{s/<\/default>/<join_use_nulls>1<\/join_use_nulls><mutations_sync>1<\/mutations_sync><allow_experimental_object_type>1<\/allow_experimental_object_type><allow_experimental_geo_types>1<\/allow_experimental_geo_types><\/default>/}" /etc/clickhouse-server/users.xml

docker restart clickhouse


```

**Comment by alexey-milovidov** [comment]
No problem with DateTime64:
```
mysql> SELECT toDateTime64('2020-02-29 17:54:55.1231234', 7)
    -> ;
+------------------------------------------------+
| toDateTime64('2020-02-29 17:54:55.1231234', 7) |
+------------------------------------------------+
| 2020-02-29 17:54:55.123123                     |
+------------------------------------------------+
1 row in set (0,01 sec)
```

And all other linked issues are closed.
