### ISSUE TITLE
After insert, select count(*) from distribute engine, returns incomplete data count.

### ISSUE THREAD

**Issue by zaorangyang** [ClickHouse/ClickHouse#55326]
I created a distributed table, and the corresponding data table uses the ReplicatedMergeTree engine. My cluster consists of 3 shards, each with 3 replicas. I used 'INSERT INTO' to insert the Clickbench dataset (99,997,497 rows) into the ClickHouse table. However, after the 'INSERT INTO' operation completes, when I use 'count()' to check if the data is complete, I find that 'count()' initially returns approximately 40 million rows. Over time, the count(*) result gradually increases and eventually reaches 99,997,497 rows.

My question is, is this behavior normal? If it is, what is the reason behind this phenomenon, and can I mitigate it?

**Comment by helifu** [comment]
I guess you write to the distributed table instead of local table,  am i right?

**Comment by zaorangyang** [comment]
@helifu Yes. You are right. Could you please tell me why this is happening?

**Comment by alexey-milovidov** [comment]
See the `insert_distributed_sync` setting.
