### ISSUE TITLE
A setting `force_optimize_projection_name`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#55331]
**Use case**

Similar to `force_optimize_projection`.

**Describe the solution you'd like**

If it is set to a non-empty string, check that this projection is used in the query at least once.

**Additional context**

There could be ambiguity with queries containing multiple tables, possibly with identical projection names.

We should resolve this ambiguity by checking that the reading from at least one table was optimized by using the projection with this name.

Alternatively, we could make the setting value as a map of database.table -> projection_name, but it does not resolve the case of one table being used multiple times when only some cases have to be optimized, and will also be harder to use... while the simple name specification is good enough for a hint.

**Comment by lingtaolf** [comment]
Could you let me try this ?

**Comment by alexey-milovidov** [comment]
@lingtaolf, thank you!

The only tricky part I see is to collect the used projections in a query and check them later (instead of checking immediately as `force_optimize_projection` does).
