### ISSUE TITLE
Backups do too much work to check if the catalog didn't change

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#55358]
**Use case**

Backups check if the set of tables didn't change during the operation, and if it changed, it starts over again.
That's why it couldn't finish if you continuously create and drop tables.

**Describe the solution you'd like**

Remove this logic. The backup command could obtain a set of tables non-atomically.

**Comment by vitlibar** [comment]
It's already implemented, see https://github.com/ClickHouse/ClickHouse/pull/54804
