### ISSUE TITLE
TCPHandler: Code: 1000. DB::Exception: Not found: maxWireVersion

### ISSUE THREAD

**Issue by dungwinve** [ClickHouse/ClickHouse#55376]
We need to sync mongodb to clickhouse, we choose to use the mongodb engine, the statement to create the table is as follows:
> create table if not exists tmp.live_logs (
    \`_id\`                 String,
    \`user_id\`          UInt64,
    \`guest_id\`        String,
    \`loginname\`     String,
    \`create_at\`      Datetime64,
    \`update_at\`     Datetime64,
    \`live_times\`     UInt64
) ENGINE = MongoDB('www.test.com:28003', 'fedb', 'live_logs', 'shardro', 'KYwYoFGT56STRDCV', 'connectTimeoutMS=10000&readPreference=secondary');

When we execute the following statement:
`select * from tmp.live_logs;`

We always get the following exception:

2023.10.07 17:33:53.442954 [ 356623 ] {40cc41c0-b978-4a7f-9eb5-a60e44a75cea} <Error> TCPHandler: Code: 1000. DB::Exception: Not found: maxWireVersion. (POCO_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. Poco::MongoDB::Document::getInteger(String const&) const @ 0x0000000015a05f29 in /usr/bin/clickhouse
1. DB::isMongoDBWireProtocolOld(Poco::MongoDB::Connection&) @ 0x0000000013472d71 in /usr/bin/clickhouse
2. DB::MongoDBSource::MongoDBSource(std::shared_ptr<Poco::MongoDB::Connection>&, String const&, String const&, Poco::MongoDB::Document const&, DB::Block const&, unsigned long) @ 0x00000000134730f9 in /usr/bin/clickhouse
3. DB::StorageMongoDB::read(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x00000000126f280d in /usr/bin/clickhouse
4. DB::IStorage::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x00000000125b88d9 in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x0000000011ed560b in /usr/bin/clickhouse
6. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x0000000011ebce68 in /usr/bin/clickhouse
7. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x0000000011ebc294 in /usr/bin/clickhouse
8. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x0000000011f604f6 in /usr/bin/clickhouse
9. DB::InterpreterSelectWithUnionQuery::execute() @ 0x0000000011f61407 in /usr/bin/clickhouse
10. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000122a6095 in /usr/bin/clickhouse
11. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x00000000122a17f5 in /usr/bin/clickhouse
12. DB::TCPHandler::runImpl() @ 0x000000001310c5b9 in /usr/bin/clickhouse
13. DB::TCPHandler::run() @ 0x000000001311e839 in /usr/bin/clickhouse
14. Poco::Net::TCPServerConnection::start() @ 0x0000000015b104d4 in /usr/bin/clickhouse
15. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015b116d1 in /usr/bin/clickhouse
16. Poco::PooledThread::run() @ 0x0000000015c47f07 in /usr/bin/clickhouse
17. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000015c461dc in /usr/bin/clickhouse
18. ? @ 0x00007f1e0ee94b43 in ?
19. ? @ 0x00007f1e0ef26a00 in ?

How should we resolve it?

**Comment by den-crane** [comment]
What is a version of your mongodb ?

**Comment by dungwinve** [comment]
Thanks for the quick replies, we will verify it with the latest release package.
