### ISSUE TITLE
Percolate Search

### ISSUE THREAD

**Issue by AbstractiveNord** [ClickHouse/ClickHouse#55374]
**Use case**

Since ClickHouse will have stable support full-text search on data, percolate search, also known as reversed search, may be implemented.

**Describe the solution you'd like**

Data ingest into ClickHouse cluster, queries already stored in prepared table, clients may subscribe to stored queries and get result rows as soon as data being processed by ClickHouse. Clients there is not only usual SQL clients, but also storages, such as Apache Kafka, RabbitMQ, NATS Jetstream (WIP), any kind of storage what support for ingest data from ClickHouse.

**Describe alternatives you've considered**
Usage of full-text search engines with percolate search support.

**Additional context**

May be related to [streaming queries RFC](https://github.com/ClickHouse/ClickHouse/issues/42990)

**Comment by alexey-milovidov** [comment]
It sounds like materialized views that we already have.

**Comment by AbstractiveNord** [comment]
> It sounds like materialized views that we already have.

Will there be support for skipping indexes for tables with MQ engines like Kafka?
