### ISSUE TITLE
select from ODBC table (Poco::Exception. Code: 1000, e.code() = 0, Timeout)

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#55388]
clickhouse v.23.8

When i try to select from engine=ODBC table, i got error 
```
:HTTPDriver for host:port returned response code 500)
Poco::Exception. Code: 1000, e.code() = 0, Timeout (version 23.8.2.7 (official build))
```
but i works when i try to select less columns(because of less execution time).
Which setting do I need to update to make a select with many columns?

**Comment by Girgitt** [comment]
Based on https://clickhouse.com/docs/en/operations/utilities/odbc-bridge for ODBC a http bridge is used. 
Try increasing the http_receive_timeout https://clickhouse.com/docs/en/operations/settings/settings#http_receive_timeout
