### ISSUE TITLE
Advanced dashboard: if there is only a single chart, don't show the "maximize" and "drag" buttons.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#55381]
**Use case**

https://play.clickhouse.com/dashboard#eyJob3N0IjoiaHR0cHM6Ly9wbGF5LmNsaWNraG91c2UuY29tIiwidXNlciI6InBsYXkiLCJxdWVyaWVzIjpbeyJ0aXRsZSI6Intkb21haW59IiwicXVlcnkiOiJTRUxFQ1QgZGF0ZTo6RGF0ZVRpbWU6OklOVCBBUyBkLCByb3VuZCgxZTkgKiBhdmcocG93KHJhbmssIC0wLjc1KSkpIEZST00gY2lzY29fdW1icmVsbGEgV0hFUkUgZG9tYWluID0ge2RvbWFpbjpTdHJpbmd9IEdST1VQIEJZIGQgT1JERVIgQlkgZCJ9XSwicGFyYW1zIjp7ImRvbWFpbiI6ImRldi5teXNxbC5jb20ifX0=

**Comment by bhavuk2002** [comment]
i can do this, just tell me where to start.

**Comment by alexey-milovidov** [comment]
@bhavuk2002 programs/server/dashboard.html
