### ISSUE TITLE
Some merge tree settings for replicated tables should be in zookeeper

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#55448]
Difference in these settings can result in different binary content of merged or mutated parts among replica. This can then trigger downloading parts and cause significant high network bandwidth and affect normal replication.

Example of some settings:

```C++
min_compress_block_size,
max_compress_block_size,
merge_max_block_size,
merge_max_block_size_bytes,
vertical_merge_algorithm_min_rows_to_activate,
vertical_merge_algorithm_min_bytes_to_activate,
compress_marks,
compress_primary_key,
marks_compression_codec,
primary_key_compression_codec,
marks_compress_block_size,
primary_key_compress_block_size
```

Not all users are aware of which settings they shouldn't change.

**Comment by tavplubix** [comment]
This is not trivial to implement, and I doubt it's worth it. It's okay that network utilization may be high in case of misconfiguration.
