### ISSUE TITLE
Bad performance with jemalloc prof open

### ISSUE THREAD

**Issue by compasses** [ClickHouse/ClickHouse#55451]
(you don't have to strictly follow this form)

**Describe the situation**
What exactly works slower than expected?
All sql became slow after run clickhouse with ** export MALLOC_CONF="prof:true" **

seems use the llvm libunwind lead to this issue?

#49438

@azat Can you help conform this issue? In some scenarios, we need run with jemalloc prof open.... 

**Additional context**

![image](https://github.com/ClickHouse/ClickHouse/assets/10161171/d222f654-3d1b-473f-9f9c-7ef65109e7a8)

**Comment by nickitat** [comment]
I think it is not unwind itself but the sampling rate. have you tried higher values for `lg_prof_sample` for example?

**Comment by compasses** [comment]
@nickitat thanks for your reply.
Yes we can increase lg_prof_sample, but last version seems no need to adjust the lg_prof_sample. So the libunwind should have some hidden performance issue?

**Comment by nickitat** [comment]
> @nickitat thanks for your reply. Yes we can increase lg_prof_sample, but last version seems no need to adjust the lg_prof_sample. So the libunwind should have some hidden performance issue?

last version of what, sorry? we still use jemalloc from July 2022.
btw when I ran some queries with default `lg_prof_sample` locally I haven't noticed any slowdown.

**Comment by compasses** [comment]
Hi, thanks the reply. @nickitat 
before we switched from https://github.com/libunwind/libunwind to https://github.com/ClickHouse/libunwind, seems the llvm libunwind lead to this performance issue.
BTW, I run some tpch queries, the performance drop dramatically. I need  change the lg_prof_sample  value larger than 30, then the perf stack shown above will disappear.

**Comment by alexey-milovidov** [comment]
It is ok - stack unwinding with DWARF is slow.
About HP's libunwind - it is not suitable for production due to being not async-signal-safe.

**Comment by qshanz373** [comment]
It seems that, hp libunwind can turn off the signal to avoid async-signal issue. See https://lists.nongnu.org/archive/html/libunwind-devel/2009-09/msg00000.html

I am not sure if the signal is blocked by default or not.
