### ISSUE TITLE
Renaming column with dot `.` in column name doesn't work.

### ISSUE THREAD

**Issue by nityanandagohain** [ClickHouse/ClickHouse#55452]
**Describe what's wrong**

When I rename a column 
```
 `attribute_string_key1_k` String MATERIALIZED attributes_string_value[indexOf(attributes_string_key, 'key1.k')] CODEC(ZSTD(1)),
```
```
alter table tablename rename column `attribute_string_key1_k` to `attribute_string_key1.k`
```
It doesn't work

**Error message and/or stacktrace**

```
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Cannot rename column from nested struct to normal column and vice versa. (BAD_ARGUMENTS)
```

**Additional context**

Version  23.7.3.14

**Comment by den-crane** [comment]
You may get weird errors during insertion if you add Array and not Array columns with the same prefix (before dot).
You may the error message about Arrays lengths (all Array should have the same number of elements).

**Comment by ankitnayan** [comment]
> You may get weird errors during insertion if you add Array and not Array columns with the same prefix (before dot). You may the error message about Arrays lengths (all Array should have the same number of elements).

This is very helpful. Thanks!

Feel free to share any more issues you re-collect later. We were planning to use dot annotations heavily by creating materialized columns and we need to figure out the issues before moving ahead.

**Comment by den-crane** [comment]
> We were planning to use dot annotations heavily by creating materialized columns

It's a footgun. It works today, next day with Clickhouse upgrade you will get "cannot read all data", and Clickhouse won't fix it.

Use `$` or `_` instead of `.`.
