### ISSUE TITLE
std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Attempt to convert null to i. (version 23.5.3.24 (official build))

### ISSUE THREAD

**Issue by sarang-pratham** [ClickHouse/ClickHouse#55464]
why do i get the above error 
trying to query a postgres table -- 
select * from postgresql(xxxx, xxxx , xxxx, xxxx, xxxx)

**Comment by nickitat** [comment]
full stack trace plz

**Comment by sarang-pratham** [comment]
2023.10.10 11:51:23.028478 [ 371 ] {6b0c306a-3c9d-4bc2-a55b-a0c4ea9dbd65} <Error> executeQuery: std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = Attempt to convert null to i. (version 23.5.3.24 (official build)) (from 10.16.69.158:9572) (in query: SELECT * FROM postgresql('xxxx', 'xxx', 'xxxx', '[HIDDEN]') LIMIT 1), Stack trace (when copying this message, always include the lines below):

0. pqxx::internal::throw_null_conversion(String const&) @ 0x0000000018b4915e in /opt/bitnami/clickhouse/bin/clickhouse
1. ? @ 0x0000000013104412 in /opt/bitnami/clickhouse/bin/clickhouse
2. DB::PostgreSQLTableStructure DB::fetchPostgreSQLTableStructure<pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)0>>(pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)0>&, String const&, String const&, bool, bool, bool) @ 0x000000001310246d in /opt/bitnami/clickhouse/bin/clickhouse
3. DB::fetchPostgreSQLTableStructure(pqxx::connection&, String const&, String const&, bool) @ 0x000000001310cc96 in /opt/bitnami/clickhouse/bin/clickhouse
4. DB::StoragePostgreSQL::getTableStructureFromData(std::shared_ptr<postgres::PoolWithFailover> const&, String const&, String const&, std::shared_ptr<DB::Context const> const&) @ 0x000000001433a6ce in /opt/bitnami/clickhouse/bin/clickhouse
5. DB::StoragePostgreSQL::StoragePostgreSQL(DB::StorageID const&, std::shared_ptr<postgres::PoolWithFailover>, String const&, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, String const&, std::shared_ptr<DB::Context const>, String const&, String const&) @ 0x000000001433a160 in /opt/bitnami/clickhouse/bin/clickhouse
6. ? @ 0x000000001246e05a in /opt/bitnami/clickhouse/bin/clickhouse
7. DB::TableFunctionPostgreSQL::executeImpl(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription) const @ 0x000000001246cf9f in /opt/bitnami/clickhouse/bin/clickhouse
8. DB::ITableFunction::execute(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription, bool, bool) const @ 0x0000000012808f5c in /opt/bitnami/clickhouse/bin/clickhouse
9. DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, DB::ASTSelectQuery const*) @ 0x000000001303152d in /opt/bitnami/clickhouse/bin/clickhouse
10. DB::JoinedTables::getLeftTableStorage() @ 0x0000000013bfa476 in /opt/bitnami/clickhouse/bin/clickhouse
11. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x0000000013b0e9c1 in /opt/bitnami/clickhouse/bin/clickhouse
12. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000013bb2cc6 in /opt/bitnami/clickhouse/bin/clickhouse
13. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x0000000013bb08d3 in /opt/bitnami/clickhouse/bin/clickhouse
14. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000013aca73e in /opt/bitnami/clickhouse/bin/clickhouse
15. ? @ 0x0000000013edb957 in /opt/bitnami/clickhouse/bin/clickhouse
16. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) @ 0x0000000013ee101f in /opt/bitnami/clickhouse/bin/clickhouse
17. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x0000000014c7ee35 in /opt/bitnami/clickhouse/bin/clickhouse
18. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x0000000014c830c4 in /opt/bitnami/clickhouse/bin/clickhouse
19. DB::HTTPServerConnection::run() @ 0x0000000014cf2bf2 in /opt/bitnami/clickhouse/bin/clickhouse
20. Poco::Net::TCPServerConnection::start() @ 0x0000000017c2fe34 in /opt/bitnami/clickhouse/bin/clickhouse
21. Poco::Net::TCPServerDispatcher::run() @ 0x0000000017c31051 in /opt/bitnami/clickhouse/bin/clickhouse
22. Poco::PooledThread::run() @ 0x0000000017dadd07 in /opt/bitnami/clickhouse/bin/clickhouse
23. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000017dab73c in /opt/bitnami/clickhouse/bin/clickhouse
24. start_thread @ 0x0000000000007ea7 in /lib/x86_64-linux-gnu/libpthread-2.31.so
25. __clone @ 0x00000000000fba2f in /lib/x86_64-linux-gnu/libc-2.31.so

**Comment by nickitat** [comment]
so far I see only this place when we could throw this exception:

https://github.com/ClickHouse/ClickHouse/blob/b143a1a3ebabb9333192fcbbf98bbcff791d1819/src/Databases/PostgreSQL/fetchPostgreSQLTableStructure.cpp#L216-L219

and as I understand the problem could happen if the table is empty - we will not get any result.

any chance that the table you query is empty?

**Comment by nickitat** [comment]
> are there any conversions happening while fetching from postgres via clickhouse ??

as you see.

so far I don't see any other places where it can happen here.
could you provide minimal reproducible example (table definition and data)?

**Comment by den-crane** [comment]
this error is related to empty arrays

repro https://github.com/ClickHouse/ClickHouse/issues/55255

https://github.com/ClickHouse/ClickHouse/issues/53341

**Comment by nickitat** [comment]
indeed this returns empty result

``` sql
create table t2(a integer[], b integer);

insert into t2 values (array[]::integer[], 1);

select array_ndims(a) from t2;
```

thanks @den-crane
