### ISSUE TITLE
Schema inference over multiple files

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#55463]
**Use case**
If you have multiple parquet files and are using schema inference, the inference of the schema will be done only on the first file. 

**Describe the solution you'd like**

ClickHouse should look at all the files and do the union of the different schema.

**Comment by Avogar** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/55428?

**Comment by Avogar** [comment]
I will add it under a setting that will be disabled by default (because there can be thousands of files and reading schema of each will be not efficient at all)

**Comment by melvynator** [comment]
It's a duplicate indeed. Closing.
