### ISSUE TITLE
v23.3.13.6-lts Unexpected behaviour : NOT FOUND COLUMN IN BLOCK exception

### ISSUE THREAD

**Issue by h1k** [ClickHouse/ClickHouse#55466]
**Describe the unexpected behaviour**
I got an unexpected result when executing a query: NOT_FOUND_COLUMN_IN_BLOCK

**How to reproduce**
* Which ClickHouse server version to use
   v23.3.13.6-lts
* `CREATE TABLE` statements for all tables involved
```
create table default.TEST_NOT_FOUND_COLUMN_IN_BLOCK as default.TEST_NOT_FOUND_COLUMN_IN_BLOCK_merge  Engine=Distributed(cluster_test,default,TEST_NOT_FOUND_COLUMN_IN_BLOCK_merge,rand());
create table default.TEST_NOT_FOUND_COLUMN_IN_BLOCK_merge  (ID Nullable(String)) Engine= MergeTree() order by tuple() settings use_metadata_cache=true;
insert into TEST_NOT_FOUND_COLUMN_IN_BLOCK values('a'),('b'),('c')
```
* Queries to run that lead to unexpected result
```
SELECT multiIf( (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR (ID = 'b')), 'a', CAST(NULL, 'Nullable(String)')) = 'c') OR
                (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR (ID = 'b')),'a',CAST(NULL, 'Nullable(String)')) ='b') OR
                (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR  (ID = 'b')), 'a', CAST(NULL, 'Nullable(String)')) = 'd') OR
                (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR (ID = 'b')), 'a', CAST(NULL, 'Nullable(String)')) = 'e'),
               'test', CAST(NULL, 'Nullable(String)')) AS alias,
       AVG(1)                                          AS avg_temp_alias
FROM TEST_NOT_FOUND_COLUMN_IN_BLOCK
GROUP BY alias
```

**Expected behavior**
It should perform properly and produce results.

**Error message and/or stacktrace**
`Code: 10. DB::Exception: Not found column if(in(if(and(isNull(ID), or(equals(ID, 'a'), equals(ID, 'c'), equals(ID, 'b'))), 'a', CAST(NULL, 'Nullable(String)')), ('b', 'c', 'd', 'e')), 'test', CAST(NULL, 'Nullable(String)')) in block avg(1) Float64 Float64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK) (version 23.3.13.1)`

**Additional context**
This is the reproduction SQL statement after my anonymization. It may look strange.
I have tested that the problem cannot be reproduced when multiple shards are specified for a single server. The problem can be reproduced only when more than two servers are sharded.

**Comment by den-crane** [comment]
works with analyzer https://fiddle.clickhouse.com/47c331d8-e8e5-444c-ade0-3443db2b674b

**Comment by h1k** [comment]
> 与分析器配合使用https://fiddle.clickhouse.com/47c331d8-e8e5-444c-ade0-3443db2b674b

**Comment by h1k** [comment]
> 与分析器配合使用https://fiddle.clickhouse.com/47c331d8-e8e5-444c-ade0-3443db2b674b

Thank you for your support, but set allow_experimental_analyzer=1 will affect my other queries. Is there any plan to fix this problem?

**Comment by h1k** [comment]
> 与分析器配合使用https://fiddle.clickhouse.com/47c331d8-e8e5-444c-ade0-3443db2b674b



> **** 描述我在执行查询时得到意外结果的**意外行为：NOT_FOUND_COLUMN_IN_BLOCK**
> 
> **如何重现**
> 
> * 使用哪个 ClickHouse 服务器版本
>   v23.3.13.6-lts
> * `CREATE TABLE`涉及所有表的语句
> 
> ```
> create table default.TEST_NOT_FOUND_COLUMN_IN_BLOCK as default.TEST_NOT_FOUND_COLUMN_IN_BLOCK_merge  Engine=Distributed(cluster_test,default,TEST_NOT_FOUND_COLUMN_IN_BLOCK_merge,rand());
> create table default.TEST_NOT_FOUND_COLUMN_IN_BLOCK_merge  (ID Nullable(String)) Engine= MergeTree() order by tuple() settings use_metadata_cache=true;
> insert into TEST_NOT_FOUND_COLUMN_IN_BLOCK values('a'),('b'),('c')
> ```
> 
> * 运行导致意外结果的查询
> 
> ```
> SELECT multiIf( (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR (ID = 'b')), 'a', CAST(NULL, 'Nullable(String)')) = 'c') OR
>                 (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR (ID = 'b')),'a',CAST(NULL, 'Nullable(String)')) ='b') OR
>                 (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR  (ID = 'b')), 'a', CAST(NULL, 'Nullable(String)')) = 'd') OR
>                 (multiIf((ID is null) AND ((ID = 'a') OR (ID = 'c') OR (ID = 'b')), 'a', CAST(NULL, 'Nullable(String)')) = 'e'),
>                'test', CAST(NULL, 'Nullable(String)')) AS alias,
>        AVG(1)                                          AS avg_temp_alias
> FROM TEST_NOT_FOUND_COLUMN_IN_BLOCK
> GROUP BY alias
> ```
> 
> **预期行为** 它应该正确执行并产生结果。
> 
> **错误消息和/或堆栈跟踪** `Code: 10. DB::Exception: Not found column if(in(if(and(isNull(ID), or(equals(ID, 'a'), equals(ID, 'c'), equals(ID, 'b'))), 'a', CAST(NULL, 'Nullable(String)')), ('b', 'c', 'd', 'e')), 'test', CAST(NULL, 'Nullable(String)')) in block avg(1) Float64 Float64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK) (version 23.3.13.1)`
> 
> **附加上下文** 这是我匿名化后复制的SQL语句。它可能看起来很奇怪。 我测试过，当为单个服务器指定多个分片时，无法重现该问题。只有当两个以上服务器分片时才能重现该问题。



> 与分析器配合使用https://fiddle.clickhouse.com/47c331d8-e8e5-444c-ade0-3443db2b674b



> 与分析器配合使用https://fiddle.clickhouse.com/47c331d8-e8e5-444c-ade0-3443db2b674b

**Comment by h1k** [comment]
> 与分析器配合使用https://fiddle.clickhouse.com/47c331d8-e8e5-444c-ade0-3443db2b674b
