### ISSUE TITLE
Adding an unnecessary `WHERE` clause improves performance of a specific self-join by orders of magnitude 

### ISSUE THREAD

**Issue by jonashaag** [ClickHouse/ClickHouse#55478]
**Describe the situation**

I have a query like this

```sql
SELECT *
FROM       t AS t1
INNER JOIN t AS t2
  ON t1.f = t2.f
  AND ...
WHERE RIGHT(t1.f, 1) = 'x' -- f is never NULL
```

This particular query can be made much much faster by adding a (semantically) useless condition to `t2`:

```sql
AND RIGHT(t2.f, 1) = 'x'
```

**How to reproduce**

Latest ClickHouse release

Unfortunately I don't have a reproducible example but I'm happy to provide more debug information and run ad hoc queries.

**Comment by nickitat** [comment]
check `explain actions=1`

**Comment by jonashaag** [comment]
Thanks, the main difference seems to be that we "unoptimized" version doesn't push down the `RIGHT(...)` filter as a (pre)where filter.

More obvious to see in the short explain output:

```
Expression (Project names + Projection))
  Aggregating
    Expression ((Before GROUP BY + ))
      Join (JOIN FillRightFirst)
        Expression (( + (JOIN actions + Change column names to column identifiers)))
          Expression
            ReadFromMergeTree (default.XXX)
        Expression (( + (JOIN actions + Change column names to column identifiers)))
          Expression  <=== this is missing in the "unoptimized" query
            ReadFromMergeTree (default.XXX)
```

**Comment by nickitat** [comment]
if it doesn't filter anything - it should only slow down the query.
pls check the actual amount of data read in both cases.
btw, what CH do you use?

**Comment by jonashaag** [comment]
> it should only slow down the query

That's what this bug report is about, or am I misunderstanding something?

I use the latest open source version.

I'll check the amount of data read; will have to figure out how to do that

**Comment by jonashaag** [comment]
For some reason I don't have a `system.query_log` table even though the query log setting is on

<img width="886" alt="Screenshot 2023-10-10 at 19 55 53" src="https://github.com/ClickHouse/ClickHouse/assets/175722/4fc9a89e-decb-40cf-8707-3fba4e6ee3ae">

**Comment by nickitat** [comment]
it should be declared in configs too

**Comment by nickitat** [comment]
and it is declared by default https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L996-L1050

maybe `system flush logs` is needed

**Comment by jonashaag** [comment]
Aha

```
Not creating system.query_log since corresponding section 'query_log' is missing from config
```

I'm running `clickhouse server` with default settings, weird that this is missing. It's also not documented, see eg [here](https://clickhouse.com/docs/knowledgebase/find-expensive-queries)

**Comment by nickitat** [comment]
how much data was read is visible in query_log, and it is also reported by `clickhouse-client` when query finishes

**Comment by den-crane** [comment]
I don't really understand why do you surprised if you add filters to the right table like `AND RIGHT(t2.f, 1) = 'x'`

If the right table became smaller, it drastically improves performance.
It actually the most used optimization - manual propagation of the filters from the left table to the right.

**Comment by jonashaag** [comment]
Because here, left table = right table. It's a self-join.

**Comment by den-crane** [comment]
> Because here, left table = right table. It's a self-join.

it's actually does not matter.

**Comment by den-crane** [comment]
The most crazy thing that such manual optimizations improves performance of other databases, like vertica and starrocks.

**Comment by nickitat** [comment]
> I don't really understand why do you surprised if you add filters to the right table like `AND RIGHT(t2.f, 1) = 'x'`
> 
> If the right table became smaller, it drastically improves performance. It actually the most used optimization - manual propagation of the filters from the left table to the right.

I don't understand why you're not surprised ) given that the filter is useless and shouldn't filter anything out i.e. make right table smaller

**Comment by den-crane** [comment]
I think 3d turtle is lying.
In the email I see `!=`, here I see `=`

>WHERE RIGHT(tbl1.col, 7) != '<dummy>' AND RIGHT(tbl2.col, 7) != '<dummy>'

>AND RIGHT(t2.f, 1) = 'x'

**Comment by jonashaag** [comment]
Sorry, I realized that I copy-pasted a wrong example and fixed it afterwards.

**Comment by jonashaag** [comment]
> and shouldn't filter anything out i.e. make right table smaller

It actually does make the right table smaller _before_ the join, but not after the join. That's why I said "semantically useless"

**Comment by den-crane** [comment]
```sql
create table t ( a Int64 ) Engine=MergeTree order by a as select * from numbers(1e8);

select count() from t t1 join t t2 on t1.a=t2.a where t1.a = 42;
┌─count()─┐
│       1 │
└─────────┘
1 row in set. Elapsed: 13.077 sec. Processed 100.01 million rows, 800.07 MB (7.65 million rows/s., 61.18 MB/s.)
Peak memory usage: 8.02 GiB.

select count() from t t1 join t t2 on t1.a=t2.a where t1.a = 42 and t2.a=42;
┌─count()─┐
│       1 │
└─────────┘
1 row in set. Elapsed: 0.003 sec. Processed 16.38 thousand rows, 131.07 KB (6.19 million rows/s., 49.50 MB/s.)
```

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/9733

**Comment by nickitat** [comment]
> > and shouldn't filter anything out i.e. make right table smaller
> 
> It actually does make the right table smaller _before_ the join, but not after the join. That's why I said "semantically useless"

got it. then yes, Denny's explanation is pretty thorough. the later you do filtering - the better. especially for join. we try to do push-down automatically, but not all cases are covered.
it is clear how to implement this particular case, hopefully it will be done soon.

**Comment by jonashaag** [comment]
Thank you both for the fantastic support in debugging this! Looking forward to seeing this improvement :)
