### ISSUE TITLE
how to receive list with table projections?

### ISSUE THREAD

**Issue by dozer111** [ClickHouse/ClickHouse#55488]
Hi, your slack link(https://clickhousedb.slack.com/join/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg#/shared-invite/error) is no longer active

My question is: how to receive table projections?

**Comment by den-crane** [comment]
I guess 

```
SELECT
    database,
    table,
    name,
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.projection_parts
WHERE (table = 'ptest') AND active
GROUP BY
    database,
    table,
    name
ORDER BY size DESC;
```

**Comment by den-crane** [comment]
Also something like

```
select database, table from system.tables where create_table_query ilike '%projection%' and database <> 'system'
```

**Comment by dozer111** [comment]
thank u)

**Comment by Z-LL** [comment]
I think this should be added to the documentation: [https://clickhouse.com/docs/en/sql-reference/statements/alter/projection](url) .

there is no query in the documentation and it's hard to find.

In addition, how to check the progress of MATERIALIZE PROJECTION? I can't find the query sql.
