### ISSUE TITLE
clickhouse hang  system.asynchronous_metric_log): Queue is full for system log

### ISSUE THREAD

**Issue by shitianmori** [ClickHouse/ClickHouse#55494]
2023.10.11 15:39:02.493054 [ 415060 ] {73fbf1f9-b4ff-4d71-8055-75d5eaafc054} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 27. DB::ParsingException: Cannot parse input: expected '\r\n' at end of stream. (CANNOT_PARSE_INPUT_ASSERTION_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb49447a in /usr/bin/clickhouse
1. DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0xb4ecd0d in /usr/bin/clickhouse
2. ? @ 0x16cdc0cc in /usr/bin/clickhouse
3. DB::HTTPHandler::trySendExceptionToClient(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x16a513ad in /usr/bin/clickhouse
4. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x16a53052 in /usr/bin/clickhouse
5. DB::HTTPServerConnection::run() @ 0x16cd91b3 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1b0c5aef in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x1b0c7f41 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x1b28e029 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x1b28b380 in /usr/bin/clickhouse
10. start_thread @ 0x82de in /usr/lib64/libpthread-2.28.so
11. __clone @ 0xfbe83 in /usr/lib64/libc-2.28.so
 (version 22.5.2.53 (official build))
2023.10.11 16:43:05.889842 [ 453195 ] {f7f806e7-a0d0-4fc5-a5ae-12d7644d7c80} <Warning> HedgedConnectionsFactory: Connection failed at try №1, reason: Code: 32. DB::Exception: Attempt to read after eof. (ATTEMPT_TO_READ_AFTER_EOF) (version 22.5.2.53 (official build))
2023.10.11 17:44:05.917540 [ 402756 ] {4ad342bc-1823-4717-a5c7-57eb3ff7aa9a} <Warning> HedgedConnectionsFactory: Connection failed at try №1, reason: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (10.104.84.131:9000). (NETWORK_ERROR) (version 22.5.2.53 (official build))
2023.10.11 18:07:33.004815 [ 392069 ] {} <Error> SystemLog (system.asynchronous_metric_log): Queue is full for system log 'DB::AsynchronousMetricLog' at 8917172

![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/975e33a3-da63-4459-9539-6729825f1e96)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/2b6d8e9b-3a4d-4cba-ac49-2b577cb2808a)

```[tasklist]
### Tasks
```

**Comment by shitianmori** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/a37d657b-5dd7-4525-8528-287b354a565f)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/1537717e-1370-4ec4-aebb-732d7f6db3a4)

**Comment by den-crane** [comment]
22.5.2.53 is out of support. Upgrade to 23.9
