### ISSUE TITLE
Issue when install clickhouse on FreeBSD

### ISSUE THREAD

**Issue by AnhTuanNguyenn** [ClickHouse/ClickHouse#55499]
hello, i want to install clickhouse on my pfsense which has 4GB ram and 250 SSD disk

but when i running this command : curl https://clickhouse.com/ | sh

i have error " Killed" then, 

the logs : 

pid 95700 (clickhouse), jid 0, uid 0, was killed: failed to reclaim memory
pid 402 (php-fpm), jid 0, uid 0, was killed: failed to reclaim memory
pid 96620 (clickhouse), jid 0, uid 0, was killed: failed to reclaim memory
pid 10144 (clickhouse), jid 0, uid 0, was killed: failed to reclaim memory
pid 16004 (clickhouse), jid 0, uid 0, was killed: failed to reclaim memory
pid 15924 (clickhouse), jid 0, uid 0, was killed: failed to reclaim memory
pid 85946 (clickhouse), jid 0, uid 0, was killed: failed to reclaim memory
pid 12763 (unbound), jid 0, uid 59, was killed: failed to reclaim memory

is this problem about the memory ? 

thanks

**Comment by alexey-milovidov** [comment]
Yes, it is about memory.

**Comment by alexey-milovidov** [comment]
4 GB should be enough, but you might need to stop some other processes before installing.
