### ISSUE TITLE
Freebsd support?

### ISSUE THREAD

**Issue by starverdiyev** [ClickHouse/ClickHouse#55496]
Hello,

We are using FreeBSD, and the last Clickhouse version was [22.1.3.7](https://www.freshports.org/databases/clickhouse#history). Can you please give information about future plans, will Clickhouse support Freebsd, will there be new releases, or 22.1.3.7 is the last version on FreeBSD? This is very important for us.

Thank you!

**Comment by Algunenano** [comment]
FreeBSD builds are happening under the Special Build task.

For example this is the last stable build -> https://s3.amazonaws.com/clickhouse-test-reports/0/8f9a227de1f530cdbda52c145d41a6b0f1d29961/clickhouse_special_build_check/report.html

```
curl https://clickhouse.com/ | sh
```

Should be working too

**Comment by starverdiyev** [comment]
> FreeBSD builds are happening under the Special Build task.
> 
> For example this is the last stable build -> https://s3.amazonaws.com/clickhouse-test-reports/0/8f9a227de1f530cdbda52c145d41a6b0f1d29961/clickhouse_special_build_check/report.html
> 
> ```
> curl https://clickhouse.com/ | sh
> ```
> 
> Should be working too

@Algunenano thank you! For the future, it will be available on FreeBSD only with direct download? No support will be on FreeBSD ports?

**Comment by alexey-milovidov** [comment]
We don't support FreeBSD ports, but the binaries work fine, and the compilation process is straightforward.
