### ISSUE TITLE
Many `Structure does not match` in `stateless_tests_flaky_check (asan)`

### ISSUE THREAD

**Issue by hanfei1991** [ClickHouse/ClickHouse#55500]
right now we have lots of `Warning` log `Structure does not match` in the `stateless_tests_flaky_check` . For example https://s3.amazonaws.com/clickhouse-test-reports/55467/bb204ed0bd08203621d12fe92c17e9385b788a6a/stateless_tests_flaky_check__asan_/run.log , the ratio right now is 0.434%, just lower than 1% in our trash log detect test `00002_log_and_exception_messages_formatting`

Why do we have many Structure does not match ? I checked the log:
```
2023.10.11 04:12:15.525576 [ 914 ] {} <Warning> system.asynchronous_metric_log_sender.DirectoryMonitor.default: Structure does not match (remote: pull_request_number UInt32 UInt32(size = 0), commit_sha String String(size = 0), check_start_time DateTime UInt32(size = 0), check_name LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))), instance_type LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))), instance_id String String(size = 0), event_date Date UInt16(size = 0), event_time DateTime UInt32(size = 0), metric LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))), value Float64 Float64(size = 0), local: pull_request_number UInt16 UInt16(size = 0), commit_sha String String(size = 0), check_start_time DateTime('UTC') UInt32(size = 0), check_name String String(size = 0), instance_type String String(size = 0), instance_id String String(size = 0), event_date Date UInt16(size = 0), event_time DateTime UInt32(size = 0), metric LowCardinality(String) ColumnLowCardinality(size = 0, UInt8(size = 0), ColumnUnique(size = 1, String(size = 1))), value Float64 Float64(size = 0)), implicit conversion will be done
```
We create distributed table `asynchronous_metric_log_sender` locally and sync it to remote side. But the local string column `commit_sha` (and other string columns) are of normal `String` type. which are different from the remote server with the type `ColumnLowCardinality` as shown above.

Sometimes it will cause the test of new PR flaky, if we trigger tables **xxx_sender** sync to remote side too many times. For example, in PR https://github.com/ClickHouse/ClickHouse/pull/53240

**Comment by Alex-Cheng** [comment]
I also noticed the flacky test `00002_log_and_exception_messages_formatting`.  https://s3.amazonaws.com/clickhouse-test-reports/55007/ce493b57f001e7742d20db32a510c0d4cdce1f06/stateless_tests__aarch64_.html

Due to the flacky test, I cannot merge my PR which has been approved.
