### ISSUE TITLE
`hilbertEncode`, `hilbertDecode` functions

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#55520]
**Describe the solution you'd like**

Similar to `mortonEncode`, `mortonDecode`, but using Hilbert curve.
Example: https://github.com/spectral3d/hilbert_hpp

**Comment by bhavuk2002** [comment]
what do you expect here?

**Comment by alexey-milovidov** [comment]
This task has some prerequisites to do it - you should find the source code of functions for Morton curves, learn the difference between Morton and Hilbert, and implement the new functions.

**Comment by BoominHutJr** [comment]
I'd like to take a stab at this. Very new to open source but would like to try implementing this feature.

**Comment by alexey-milovidov** [comment]
Thank you! Check this repository: https://github.com/becheran/fast-hilbert/blob/main/src/lib.rs
We will use the same approach (table-based, 2d-only).
We need to rewrite it in C++.

**Comment by BoominHutJr** [comment]
For my own personal understanding, what will this function be applied to. As in what values are going to be encoded/decoded? (IP's, raw data, feature engineering, etc)

**Comment by Ilyua** [comment]
Hi! Can I consider this task as open and contribute on it?

**Comment by alexey-milovidov** [comment]
Yes, it is currently open.

**Comment by alexey-milovidov** [comment]
> For my own personal understanding, what will this function be applied to.

There are two use cases:

1. Indexing.

It will be used to mix together the ordering by two columns that are similar in their distribution. E.g. longitude and latitude; TCP IP address and X-Forwarded-For IP address; call start time and call end time; advertiser ID and advertisement place ID; origin and destination address; URL and Referer hash; sender ID and destination ID.

Quite a lot of use cases when you have two values, but cannot decide which one is more important than the other.

Indexing by the Hilbert curve provides better data locality than by the Morton curve.

2. Visualization.

It will be used when you want to map single-dimensional data into 2D space, like I do in my service https://reversedns.space/ You see the example with IP addresses, but another example includes RAM visualization and machine code visualization.

**Comment by Ilyua** [comment]
> Yes, it is currently open.

Can I ask to assign this task to me? Or it is not necessary and I can try to develop without assigning?

**Comment by Artemmm91** [comment]
> > Yes, it is currently open.
> 
> Can I ask to assign this task to me? Or it is not necessary and I can try to develop without assigning?

I am currently working on this issue as assigned task of InternTask (you can see it here https://github.com/ClickHouse/ClickHouse/issues/58394)
