### ISSUE TITLE
insert_deduplication_token does not work with async insert

### ISSUE THREAD

**Issue by dozer111** [ClickHouse/ClickHouse#55539]
Seems that [insert_deduplication_token](https://clickhouse.com/docs/en/operations/settings/settings#insert_deduplication_token) does not work with async inserts(unlike direct inserts)

Is it bug?

**Comment by den-crane** [comment]
what clickhouse version do you use?
it should work starting from 23.7, 



v23.7.1.2470-stable.md:* Support async_deduplication_token for async insert. [#52136](https://github.com/ClickHouse/ClickHouse/pull/52136) ([Han Fei](https://github.com/hanfei1991)).

* https://github.com/ClickHouse/ClickHouse/issues/52018
* https://github.com/ClickHouse/ClickHouse/pull/52136

**Comment by dozer111** [comment]
23.2, thanks)
