### ISSUE TITLE
The jdbc batch insert is not working as expected

### ISSUE THREAD

**Issue by gaoxingliang** [ClickHouse/ClickHouse#55538]
**Describe the unexpected behaviour**
I used the jdbc client 'com.clickhouse:clickhouse-jdbc:0.4.6' to do batch insert. and I want to a same batch (all contents are same, the sql and the every input paramether in jdbc preparedstatement) is removed duplication automatically.

**How to reproduce**
The sql I used:
```
    public static final String SQL_INSERT_ACCESS_LOG = "INSERT INTO %s " +
            " settings insert_quorum=2,insert_quorum_timeout=30000 " +
            "select timestamp, rawkey, source, target, targetcategory, enterprise, userid, arguments, status, elapse, response " +
            "from input ('" +
            "  timestamp DateTime,\n" +
            "  rawkey String, \n" +
            "  source String, \n" +
            "  target String,\n" +
            "  targetcategory String,\n" +
            "  enterprise String,\n" +
            "  userid Int64,\n" +
            "  arguments String ,\n" +
            "  status String,\n" +
            "  elapse UInt32 ,\n" +
            "  response String')";
```
The error is read timeout .
The rawkey is a kafka offset value, eg `topicXXX-partitionYYY-offsetZZZ`, 
and a batch will contain a continues sequences, eg from 100 to 200.
and when I checked the database, I found all records from 100 to 200 is duplicated even in java code it's in a sql batch.
 
**Expected behavior**
A same batch in sql should be de-duplicated automatically in ReplicatedMergeTree.

** My Questions**
1. do the jdbc batch should keep a batch deduplication automatically? I mean it should generate same BLOCK.
2. the jdbc source code says it's a for-loop. I doubt whether it can de-duplicate automatically.
```
# com.clickhouse.jdbc.internal.ClickHouseStatementImpl
    @Override
    public long[] executeLargeBatch() throws SQLException {
        ensureOpen();
        if (batchStmts.isEmpty()) {
            return ClickHouseValues.EMPTY_LONG_ARRAY;
        }

        boolean continueOnError = getConnection().getJdbcConfig().isContinueBatchOnError();
        long[] results = new long[batchStmts.size()];
        try {
            int i = 0;
            for (ClickHouseSqlStatement s : batchStmts) {
                try (ClickHouseResponse r = executeStatement(s, null, null, null); ResultSet rs = updateResult(s, r)) {
                    if (rs != null && s.isQuery()) {
                        throw SqlExceptionUtils.queryInBatchError(results);
                    }
                    results[i] = currentUpdateCount <= 0L ? 0L : currentUpdateCount;
                } catch (Exception e) {
                    results[i] = EXECUTE_FAILED;
                    if (!continueOnError) {
                        throw SqlExceptionUtils.batchUpdateError(e, results);
                    }
                    log.error("Faled to execute task %d of %d", i + 1, batchStmts.size(), e);
                } finally {
                    i++;
                }
            }
        } finally {
            clearBatch();
        }

        return results;
    }
```

**Error message and/or stacktrace**
![image](https://github.com/ClickHouse/ClickHouse/assets/3148215/ca3c0d46-ef22-4dab-8af0-f858f208e0da)

**Additional context**
I have to avoid this duplicates by using ReplicatedReplacingMergeTree.

**Comment by den-crane** [comment]
ReplicatedMergeTree does not deduplicate rows, only inserts.

https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

https://kb.altinity.com/altinity-kb-schema-design/row-level-deduplication/

to get an answer on question about java, please ask here https://github.com/ClickHouse/clickhouse-java

**Comment by gaoxingliang** [comment]
Hi @den-crane Actually, the clickhouse should remove the same BLOCK automatically.
Here what I expect is: if it's a same batch in jdbc, it SHOULD generate same BLOCK. and then it will automatically remove duplicates. and I used the INSERT sql. 
I created this issue because I think the block level deduplication is not working.
```
(Block level deduplication exists in Replicated tables, and is not the subject of that article).
```

**Comment by den-crane** [comment]
@gaoxingliang see explanation and examples https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

insert deduplication does work, read kb.

**Comment by gaoxingliang** [comment]
For a single insert I understood it's working as expected. but for a batch insert, it occasionally failed when I found the read timeout error.
below code show what I test: (It always generate same batch, so it's removed duplicates automatically MOST of the time. but sometime it fails and cause every record in the batch is duplicated. I don't know it's a jdbc driver issue or something else)
```
        String u = "clickhouse_operator", p = "clickhouse_operator_password";
        String url2 = "jdbc:ch://192.168.102.227:44181,192.168.102.225:44181,192.168.102.224:44181/default?nullAsDefault=2";

        BasicDataSource ds = new BasicDataSource();
        ds.setUsername(u);
        ds.setPassword(p);
        ds.setUrl(url2);
        ds.setDriverClassName(com.clickhouse.jdbc.ClickHouseDriver.class.getCanonicalName());

        //ds.setDriverClassName(com.github.housepower.jdbc.ClickHouseDriver.class.getCanonicalName());
        ds.setDefaultAutoCommit(false);
        try (Connection c = ds.getConnection()) {

            try (PreparedStatement pstmt = c.prepareStatement("INSERT INTO test_log3 settings insert_quorum=2,insert_quorum_timeout=30000 select timestamp, source, target, targetcategory, enterprise, userid, arguments, status, elapse, response " +
                    "from input ('" +
                    "  timestamp DateTime,\n" +
                    "  source String, \n" +
                    "  target String,\n" +
                    "  targetcategory String,\n" +
                    "  enterprise String,\n" +
                    "  userid Int64,\n" +
                    "  arguments String ,\n" +
                    "  status String,\n" +
                    "  elapse UInt32 ,\n" +
                    "  response String') "

            )) {
                int insertBatchSize = 10;

                for (int i = 0; i < insertBatchSize; i++) {
                    pstmt.setObject(1, "2019-11-01 00:00:00");
                    pstmt.setString(2, "1111source" + (i % 10));
                    pstmt.setString(3, "target" + (i % 10));
                    pstmt.setString(4, "cat" + (i % 10));
                    pstmt.setString(5, "ent" + (i % 10));
                    pstmt.setInt(6, i);
                    pstmt.setString(7, "{\"a\": \"helloworld\"}");
                    pstmt.setString(8, "OK");
                    pstmt.setInt(9, 10 + i);
                    pstmt.setString(10, "{}");
                    pstmt.addBatch();
                }
                pstmt.executeBatch();
            }

            c.commit();
        }
```

**Comment by gaoxingliang** [comment]
After I test, a batch insert generates one block . so I think there must be something wrong.

**Comment by den-crane** [comment]
So you do mean that "read timeout" happens on the insert, something or someone repeats the insertion and you expect that the second insert should be deduplicated because the first insert was successful. 
Yes, it should work like this, if 
* table deduplicates inserts (it's replicated, or `non_replicated_deduplication_window` is configured to a MergeTree (not replicated).
* less than deduplication_window inserts happened in between the first and the second retry https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#replicated-deduplication-window
* if the insert is exactly the same at a bit level. No distributed tables with no non-constistent resharding involved.
* the second insert happens in the same shard `192.168.102.227:44181,192.168.102.225:44181,192.168.102.224:44181`
