### ISSUE TITLE
How to use S3 engine to read files with different paths?

### ISSUE THREAD

**Issue by FengZh61** [ClickHouse/ClickHouse#55537]
For example, part of my file is in /A/B/C/*.parquet ,and part is in /A/B/C/D/*.parquet, how can I write s3_url that will allow both CH to read the parquet file?

**Comment by den-crane** [comment]
see  https://clickhouse.com/docs/search?q=globs

`s3( '....{A,B,C,D}/*.parquet', )` -- should work
