### ISSUE TITLE
Missing Documentation of `kafka_max_block_size`

### ISSUE THREAD

**Issue by spyros87** [ClickHouse/ClickHouse#5553]
(you don't have to strictly follow this form)

**Describe the bug**
As #3396 implements `kafka_max_block_size`, there has to be detailed documentation of this feature. One must dig really deep inside the code in order to check if this feature exists and its use.

**Expected behavior**
Users must be able to read and understand the meaning of `kafka_max_block_size` in [here](https://clickhouse.yandex/docs/en/operations/table_engines/kafka/).

**Additional context**
I have stumbled upon this feature by luck viewing issues in GH and still I am unsure if my approach is correct.

**Comment by alexey-milovidov** [comment]
https://clickhouse.tech/docs/en/engines/table-engines/integrations/kafka/#table_engine-kafka-creating-a-table
