### ISSUE TITLE
macOS build segfaults on start if built with Xcode 15.0

### ISSUE THREAD

**Issue by mkmkme** [ClickHouse/ClickHouse#55552]
> You have to provide the following information whenever possible.

I built the current `master` branch on my machine (macOS Sonoma, Apple Silicon), and `clickhouse server` segfaults with the following output:

```
libunwind: stepWithCompactEncoding - invalid compact unwind encoding
2023.10.12 13:52:09.000704 [ 3329714 ] {} <Trace> BaseDaemon: Received signal 6
2023.10.12 13:52:09.000861 [ 3329954 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.10.12 13:52:09.000877 [ 3329954 ] {} <Fatal> BaseDaemon: (version 23.10.1.1, build id: , git hash: fac83efdd25541b42baa6e47b8b71d18f4f47867) (from thread 3329639) Received signal 6
2023.10.12 13:52:09.000891 [ 3329954 ] {} <Fatal> BaseDaemon: Signal description: Abort trap: 6
2023.10.12 13:52:09.000895 [ 3329954 ] {} <Fatal> BaseDaemon:
2023.10.12 13:52:09.000901 [ 3329954 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000018412711c
2023.10.12 13:52:09.000906 [ 3329954 ] {} <Fatal> BaseDaemon: ########################################
2023.10.12 13:52:09.000909 [ 3329954 ] {} <Fatal> BaseDaemon: (version 23.10.1.1, build id: , git hash: fac83efdd25541b42baa6e47b8b71d18f4f47867) (from thread 3329639) (no query) Received signal Abort trap: 6 (6)
2023.10.12 13:52:09.000912 [ 3329954 ] {} <Fatal> BaseDaemon:
2023.10.12 13:52:09.000914 [ 3329954 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000018412711c
2023.10.12 13:52:09.000920 [ 3329954 ] {} <Fatal> BaseDaemon: 0. 0x18412711c
2023.10.12 13:52:09.001008 [ 3329954 ] {} <Fatal> BaseDaemon: This ClickHouse version is not official and should be upgraded to the official build.
[1]    7995 abort      ./build/programs/clickhouse server
```

My colleague reported the same issue on their macbook as well.

**Does it reproduce on recent release?**

No

**Comment by tavplubix** [comment]
You have an alternative build. Have you tried an official package?

**Comment by mkmkme** [comment]
>You have an alternative build. Have you tried an official package?

Yes, this issue can't be reproduced with the version installed via `curl https://clickhouse.com/ | sh`. So far I could only reproduce it with `master` branch.
Do you want me to `git bisect` this issue?

**Comment by tavplubix** [comment]
AFAIR, `curl https://clickhouse.com/ | sh` installs a recent build from master. You can also download it from the CI: https://s3.amazonaws.com/clickhouse-test-reports/0/332a0cfa24d6ca76814dde17a09fa96f58be0003/clickhouse_special_build_check/report.html

So looks like it's a problem with your building environment.

**Comment by mkmkme** [comment]
So far it seems to me that the crash happens on every build for macOS **that was built on macOS**. The official build was made on Ubuntu for macOS.

If you have any macOS machine (preferably on Apple Silicon), could you try to build CH there and tell whether it crashes?

**Comment by rschu1ze** [comment]
Making a macOS build on macOS right now ...

**Comment by rschu1ze** [comment]
Ran into the same error. I have a slight suspicious that mh PR #55147 could be related, doing another build with it reverted right now.

Error `libunwind: stepWithCompactEncoding - invalid compact unwind encoding` occurred in the past when a non-default linker was used: #42470

**Comment by laofan13** [comment]
> Ran into the same error. I have a slight suspicious that my PR #55147 could be related, doing another build with it reverted right now.
> 
> Error `libunwind: stepWithCompactEncoding - invalid compact unwind encoding` occurred in the past when a non-default linker was used: #42470

I also smae error, how to solve ?

**Comment by rschu1ze** [comment]
My PR #55147 is unrelated, and recent PR #55483 (the only one I remember which could be remotely related) is only about ELF. Unless someone has a good idea which other build broke the macOS binary, we need to do bisecting I fear.

**Comment by mkmkme** [comment]
I can help with bisecting, if needed. Sadly I can't tell when exactly did this break, because I've been using Linux VM myself for some time

**Comment by rschu1ze** [comment]
That would be awesome. Suggest to use start from the last release (https://github.com/ClickHouse/ClickHouse/releases/tag/v23.9.1.1854-stable) from 29 Sep. There is a good chance it still worked in this release. If so, then use `git bisect` to find the culprit.

**Comment by mkmkme** [comment]
Will do

**Comment by laofan13** [comment]
Hi, Is there any other way to solve this problem?

**Comment by mkmkme** [comment]
Hey @laofan13,
It seems that the only version that crashes on start is macOS version built on macOS. In order to solve this problem you can:
1. Use the official build (which is built on Ubuntu)
2. Build the macOS version on Ubuntu (you can use clickhouse/binary-builder docker image which is publicly available)

Hope this makes sense.

**Comment by laofan13** [comment]
> Hey @laofan13, It seems that the only version that crashes on start is macOS version built on macOS. In order to solve this problem you can:
> 
> 1. Use the official build (which is built on Ubuntu)
> 2. Build the macOS version on Ubuntu (you can use clickhouse/binary-builder docker image which is publicly available)
> 
> Hope this makes sense.

Hey, the latest version only builds on macOS Sonoma ?

**Comment by mkmkme** [comment]
Sorry, not sure what you mean by that.
If you're asking whether it crashes only on versions built on Sonoma, then the answer is "maybe" :)

If you happen to have a powerful enough Ventura machine to check whether it fails there, please tell, this would be very useful. Otherwise I'm currently trying to check if the fail is caused by macOS version or it was broken somewhere in the code.

**Comment by laofan13** [comment]
> Sorry, not sure what you mean by that. If you're asking whether it crashes only on versions built on Sonoma, then the answer is "maybe" :)
> 
> If you happen to have a powerful enough Ventura machine to check whether it fails there, please tell, this would be very useful. Otherwise I'm currently trying to check if the fail is caused by macOS version or it was broken somewhere in the code.

Thanks

**Comment by jrdi** [comment]
FWIW, this issue is not reproducing in macOS Ventura (previous version)

**Comment by mkmkme** [comment]
@jrdi Thanks a lot for the information! Yeah, it might be due to a `ld` version. Looking into it.

**Comment by mkmkme** [comment]
@jrdi could you tell more about your setup? I've just built CH on Ventura, and it also fails.

**Comment by jrdi** [comment]
I don't have anything crazy. Let me share some versions I'm using in case they're helpful.

clang
```
Homebrew clang version 17.0.1
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

rust
```
rustc 1.72.1 (d5c2e9c34 2023-09-13) (Homebrew)
binary: rustc
commit-hash: d5c2e9c342b358556da91d61ed4133f6f50fc0c3
commit-date: 2023-09-13
host: aarch64-apple-darwin
release: 1.72.1
LLVM version: 16.0.6
```

Anyway, I will recompile everything just in case I did something wrong.

**Comment by mkmkme** [comment]
So @jrdi @laofan13 @rschu1ze, it seems that the bug is not in CH code and not in macOS Sonoma either, but Xcode 15 command-line utils that are used during the build (presumably linker is the one affecting the most). I managed to build `clickhouse` using `Xcode 14.3.1` and it doesn't crash. It is sadly not a surprise, as it's not the first time `Xcode X.0` causes issues.

The problem is that `Xcode 14.3.1` does not support macOS Sonoma so you have to trick it into thinking it does. For that, you have to have Xcode 15 installed on your machine so you can edit a binary `plist` file.

After downloading an Xcode14 `.xip` file and extracting an `.app` from it, you need to:
* Right-click on Xcode.app (14.3.1, the one you downloaded) and click on "Show package contents"
* From there, open file located at `Contents/Info.plist`
* Press Cmd+F and type `CFBundleVersion`
* It'll highlight the "Bundle version" key. Change its value from `21815` to `22265` and save changes via Cmd+S
* Now go back to the directory containing that Xcode.app and try to open it via Right-click -> Open

If it works, you can rename it to `Xcode_14.app` and copy to `/Applications` so it doesn't conflict with Xcode 15 that you have installed.
Then, all you have to do is open a terminal and execute `sudo xcode-select -s /Applications/Xcode_14.app/`. After that, invoke `clang -v` to verify it shows 14.0.3 and not 15.0.0
After this, perform a clean build of CH. It should work fine.

I'll dig into CH's `cmake` directory to see what linkers does it support and whether I can just use some 3rd party linker instead of relying to the system one.

**Comment by mkmkme** [comment]
This issue can be closed as it is not a clickhouse problem per se, it's an Apple bug. And I'll see if I can report it.

**Comment by rschu1ze** [comment]
Thanks for the interesting investigation. Let's keep this issue open as long as it persists. We can link an issue (e.g. with Apple).

**Comment by mkmkme** [comment]
Reported to Apple: https://feedbackassistant.apple.com/feedback/13278308

**Comment by mkmkme** [comment]
For the record: I tested the build with Xcode 15.1 beta. It doesn't crash.

**Comment by mkmkme** [comment]
Also this changelog entry looks relevant:
>Fixed: Binaries using symbols with a weak definition crash at runtime on iOS 14/macOS 12 or older. This impacts primarily C++ projects due to their extensive use of weak symbols. (114813650)

**Comment by santrancisco** [comment]
Thanks for raising this ... I was scratching my head for an hour until i stumbled across this issue.

> For the record: I tested the build with Xcode 15.1 beta. It doesn't crash.

I can also confirm this works for me.

**Comment by laofan13** [comment]
I can also work with Xcode 15.1 beta

**Comment by tbragin** [comment]
Tried building with 15.1-RC released on Dec 5, and it also still works.
