### ISSUE TITLE
DETACH TABLE xyz PERMANENTLY

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#5555]
Let's say I have some table data on the disk. I can do `ATTACH TABLE` to see what's inside. And after that, I want to detach it back.

Currently, DETACH leaves the metadata, and the table will be attached at the next clickhouse start.

So there is no possibility to revert the database to the state before the table was ATTACHed.

**Comment by amosbird** [comment]
It's better to leave the metadata intact while introduce an mechanism to disable loading some tables upon server startup.

**Comment by filimonov** [comment]
Actually the usecase i had initially was more about `ATTACH TABLE x EPHEMERALLY` (so don't create metadata for the table at all), but it seems `DETACH TABLE xyz PERMANENTLY` is also needed, and it would be nice to keep metadata for those tables in place.
