### ISSUE TITLE
Is protobuf format functionality necessary for me if I don't need protobuf user scenario?

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#55585]
I have run the tests on my customized clickhouse codebase, and found the test `00825_protobuf_format_enum_mapping` failed. I don't use protobuf and even I don't know what scenario it should be used. 

I am wondering if I can ignore the failue of test `00825_protobuf_format_enum_mapping` and what user scenarioes does the protobuf impacts?

Thank yo very much.

**Comment by Algunenano** [comment]
> I am wondering if I can ignore the failue of test 00825_protobuf_format_enum_mapping

It's your codebase, so only you can answer that question.

> what user scenarioes does the protobuf impacts?

Protobuf is used to read and write the [protobuf input and output formats](https://clickhouse.com/docs/en/interfaces/formats#protobuf).
