### ISSUE TITLE
MATERIALIZED VIEW subquery

### ISSUE THREAD

**Issue by inv2004** [ClickHouse/ClickHouse#5562]
**Use case**
The only way to aggregate over another aggregated data is to use subquery in CH.
For example, if I would like to deduplicate rows by key inside inserted block and aggregate by toStartOfFiveMinute, I have to do something like
```sql
CREATE MATERIALIZED VIEW mv TO agg_table AS
SELECT key, toStartOfFiveMinute(dt) as d, sumState(val)
FROM (
  SELECT *
  FROM source
  LIMIT 1 BY key, dt   -- or any(val) GROUP BY key, dt
)
GROUP BY key, d
```

But the problem that MV does not support subquery => you cannot build any non-primitive logic in MV.

**Describe the solution you'd like**
Possible limited subquery support in MV. Cannot find any reasons why query in the issue would not work for MV _inside_ block.

**Describe alternatives you've considered**
The alternative solution could be:
- Probably more extended syntax and Map datatypes, for example kdb solution without subquery:
```
select {sum value (distinct x)#x!y}[dt;val] by key from t     / it sums values of one array by uniq values of another array via Map datatype.
select sum val by key from select first val by key, dt from t / with subquery: more clear solution
```
- something like uniqByKey (or by another array). Like in kdb example.
- special syntax for MV, "AS SELECT FROM INNER (SELECT FROM XXX)". It is exactly the same subquery for MV, but helps to point which table(source) triggers MV. The idea is extended in the following @den-crane comments.

**Additional context**
Probably same problem, but from kafka-engine: https://github.com/yandex/ClickHouse/issues/5243

**Comment by den-crane** [comment]
Competing proposal: Introduce another syntax #BUFFER, which explicitly point to a source table (table_name)

CREATE INSERT TRIGGER trigger_name ON table_name TO storage_name
AS SELECT ....... FROM ( SELECT ( ...... FROM **#BUFFER** )))

**Comment by inv2004** [comment]
@den-crane 
If you use another db.table instead of #buffer - will it use full table in the case? In the case it can cover some other cases, but not sure if it is easy to implement.

**Comment by den-crane** [comment]
AS **_TTT** -- I meant a better usability to do not introduce a new keyword #BUFFER.

Sometimes I need this use-case (upsert/insert if not exists) for small tables -- dimensions:

CREATE INSERT TRIGGER trigger_name ON table_name AS _TTT TO storage_name
AS SELECT * FROM _TTT WHERE key not in (SELECT KEY FROM storage_name);

Now I have to use intermediate tables (TINYLOG/MEMORY).

About self joins I meant sometimes it needed to join to enrich inserted data from another(older) rows of source table

CREATE INSERT TRIGGER trigger_name ON table_name AS _TTT TO storage_name
AS SELECT _TTT.*, x.somecolumn FROM _TTT LEFT OUTER JOIN table_name as x

**Comment by inv2004** [comment]
@den-crane 
I suppose you can simulate WHERE key not in (SELECT FROM storage) by creating kv Join engine + mv_to_kv into it +joinGet in trigger_name mv . But it cannot help to solve initial problem mentioned in the issue.

**Comment by den-crane** [comment]
One more idea:

CREATE INSERT TRIGGER trigger_name ON table_name AS _TTT 
**INTO storage_name(a,b,c,d)**
AS SELECT exp1, v, c,d FROM ( SELECT ( ...... FROM _TTT )))

**Comment by knoguchi** [comment]
Now MV supports subqueries.

**Comment by victorbonnet** [comment]
Starting which version we can use subqueries in materialized views?

**Comment by den-crane** [comment]
19.14.3.3 supports subqueries in materialized views

19.16.14.65 supports subqueries in Kafka materialized views

**Comment by phhcer** [comment]
when I select subquery like this
```clickhouse
create materialized view mv2 as 
select
    t1.ds,
    t2.ds
from (
    select
        ds
    from `.inner.mv1`
) t1
left join (
    select
        ds
    from `.inner.mv1`
) t2
ON t1.ds = t2.ds+1
 ```
Will it use full data of mv1 or one batch of mv1?
