### ISSUE TITLE
Deploying Disaster Recovery cluster

### ISSUE THREAD

**Issue by Shankara-git** [ClickHouse/ClickHouse#55630]
We have deployed clickhoue cluster in kubernetes, includes 4 pods(2 shards and 2 replica). Now, we want deploy disaster recovery cluster. We have referred disaster recovery architecture *from a weird website* and tried to deploy it, but getting DNS_ERROR (we deployed both the cluster in two different namespace)

We have gone through backup and restore part https://clickhouse.com/docs/en/operations/backup but in our deployment data is stored at GCS bucket and we want to take backup only metadata part and reuse the data in GCS bucket.

Is there any suggestion for deploying disaster recovery cluster ?

**Comment by alexey-milovidov** [comment]
It's not possible to backup only metadata and reuse the data in object storage.
A full backup is required.
