### ISSUE TITLE
filesystem_error occurs when data is inserted for windows docker desktop maps volumes.

### ISSUE THREAD

**Issue by hanzch** [ClickHouse/ClickHouse#55638]
> You have to provide the following information whenever possible.

**Describe what's wrong**

> filesystem_error occurs when data is inserted
The current error only occurs when windows docker desktop maps volumes.
I suspect it was a configuration issue when clickhouse images was built because the same issue did not occur in the other images, like mysql.

>Error example:
-v C:\clickhouse\data:/var/lib/clickhouse
But when using docker built-in volumes, there are no errors.
For example:
-v ./data:/var/lib/clickhouse
For the complete docker command, see the code below.

**Does it reproduce on recent release?**

>Try to update to the latest image, the problem still occurs
docker pull clickhouse/clickhouse-server:latest      -> version 23.9.1.1854 (official build)

**Enable crash reporting**

> yes

**How to reproduce**

* To install clickhouse using docker desktop for windows, run the following command:
 `docker run -d --restart always --name clickhouse -p 8123:8123 --ulimit nofile=262144:262144 -v C:\clickhouse\data:/var/lib/clickhouse -v C:\clickhouse\logs:/var/log/clickhouse-server -v C:\clickhouse\conf:/etc/clickhouse-server clickhouse/clickhouse-server:23.1.2.9-alpine`
* `docker exec -it clickhouse bash`
* `clickhouse client`
* `create DATABASE if not exists tet`
* `CREATE TABLE if not exists tet.abc
(
    `date` Date,
    `code` String,
    `val` UInt64
)
ENGINE = ReplacingMergeTree
PRIMARY KEY date
ORDER BY (date, code)
SETTINGS index_granularity = 8192)`
* `INSERT INTO tet.abc VALUES ('2009-08-18 09:30:00', '123', 30)`

**Expected behavior**

> Normal insertion?

**Error message and/or stacktrace**

>2023.10.14 16:59:40.995898 [ 292 ] {} <Error> void DB::SystemLog<DB::AsynchronousMetricLogElement>::flushImpl(const std::vector<LogElement> &, uint64_t) [LogElement = DB::AsynchronousMetricLogElement]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: No such file or directory ["/var/lib/clickhouse/store/137/13706a45-3da4-4609-8943-ab0376219710/tmp_insert_202310_185_185_0/"] ["/var/lib/clickhouse/store/137/13706a45-3da4-4609-8943-ab0376219710/202310_185_185_0/"], Stack trace (when copying this message, always include the lines below):

>0. std::system_error::system_error(std::error_code, String const&) @ 0x00000000182722b5 in /usr/bin/clickhouse
>1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:v15000](String const&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code) @ 0x0000000018227aa4 in /usr/bin/clickhouse
>2. void std::__fs::filesystem::__throw_filesystem_error[abi:v15000]<String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x000000001822787d in /usr/bin/clickhouse
>3. std::__fs::filesystem::detail::(anonymous namespace)::ErrorHandler<void>::report(std::error_code const&) const (.llvm.13852873210620881851) @ 0x0000000018229c70 in /usr/bin/clickhouse
>4. std::__fs::filesystem::__rename(std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001822dfbd in /usr/bin/clickhouse
>5. DB::DiskLocal::moveDirectory(String const&, String const&) @ 0x0000000011636989 in /usr/bin/clickhouse
>6. DB::DataPartStorageOnDiskBase::rename(String, String, Poco::Logger*, bool, bool) @ 0x0000000012d41c7c in /usr/bin/clickhouse
>7. DB::IMergeTreeDataPart::renameTo(String const&, bool) @ 0x0000000012d6b126 in /usr/bin/clickhouse
>8. DB::MergeTreeData::renameTempPartAndReplaceImpl(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, DB::DataPartsLock&, std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>*) @ 0x0000000012e21262 in /usr/bin/clickhouse
>9. DB::MergeTreeData::renameTempPartAndAdd(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, DB::DataPartsLock&) @ 0x0000000012e22aa5 in /usr/bin/clickhouse
>10. DB::MergeTreeSink::finishDelayedChunk() @ 0x0000000013178159 in /usr/bin/clickhouse
>11. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x00000000135fdd3c in /usr/bin/clickhouse
>12. DB::ExceptionKeepingTransform::work() @ 0x00000000135fd4ec in /usr/bin/clickhouse
>13. DB::ExecutionThreadContext::executeTask() @ 0x00000000133aac5a in /usr/bin/clickhouse
>14. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000133a1710 in /usr/bin/clickhouse
>15. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000133a0ec8 in /usr/bin/clickhouse
>16. DB::SystemLog<DB::AsynchronousMetricLogElement>::savingThreadFunction() @ 0x00000000122affcc in /usr/bin/clickhouse
>17. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::SystemLogBase<DB::AsynchronousMetricLogElement>::startup()::'lambda'()>(DB::SystemLogBase<DB::AsynchronousMetricLogElement>::startup()::'lambda'()&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c870672 in /usr/bin/clickhouse
>18. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c832d27 in /usr/bin/clickhouse
>19. ? @ 0x00007fb449cef609 in ?
>20. ? @ 0x00007fb449c14133 in ?

>Cannot print extra info for Poco::Exception (version 23.9.1.1854 (official build))

**Additional context**

> Operating system: windows server 2019 standard
Docker version 24.0.6, build ed223bc
Docker desktop 4.24.1 (123237)

**Comment by den-crane** [comment]
>C:\clickhouse\data:/var/lib/clickhouse

WSL problem, use internal ext4 filesystem, mapped volumes `C:\clickhouse\data` are unable to work, because they don't support some ext4 features.

https://github.com/ClickHouse/ClickHouse/issues/46721
https://github.com/ClickHouse/ClickHouse/issues/35036

**Comment by hanzch** [comment]
Thanks.

**Comment by Ancxk** [comment]
> Thanks.

How to solve it?   help

**Comment by Ancxk** [comment]
> > C:\clickhouse\data:/var/lib/clickhouse
> 
> WSL problem. Use internal ext4 filesystem, mapped volumes `C:\clickhouse\data` are unable to work, because they don't support some ext4 features.
> 
> #46721 #35036

Can I only change the version of clickhouse?

**Comment by hanzch** [comment]
> > Thanks. 谢谢.
> 
> How to solve it? help如何解决？帮助

Change the configuration, do not use `C:\clickhouse\data:/var/lib/clickhouse,` can use the built-in mapping volumes, such as: `./clickhouse/data:/var/lib/clickhouse`

**Comment by andyg2** [comment]
> > > Thanks. 谢谢.
> > 
> > 
> > How to solve it? help如何解决？帮助
> 
> Change the configuration, do not use `C:\clickhouse\data:/var/lib/clickhouse,` can use the built-in mapping volumes, such as: `./clickhouse/data:/var/lib/clickhouse`

So your relative paths (`./`) answer is definitely effective but there were some caveats for me - probably some unrelated faux-pas on my part - but I thought I'd post this in case it helps others.

All relative paths failed for me too (`docker: Error response from daemon: create ch_config/config.xml: "ch_config/config.xml" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.`):
```
docker run -d -p 1123:8123 -p9000:9000 \
    -v ./ch_data:/var/lib/clickhouse \
    -v ./ch_logs:/var/log/clickhouse-server \
    -v ./ch_config/config.xml:/etc/clickhouse-server/config.xml \
    --name clickhouse-server --ulimit nofile=262144:262144 \
    clickhouse/clickhouse-server
```

Also all `%cd%` prefixed paths failed (OP's file permission error)
```
docker run -d -p 1123:8123 -p9000:9000 \
    -v %cd%/ch_data:/var/lib/clickhouse \
    -v %cd%/ch_logs:/var/log/clickhouse-server \
    -v %cd%/ch_config/config.xml:/etc/clickhouse-server/config.xml \
    --name clickhouse-server --ulimit nofile=262144:262144 \
    clickhouse/clickhouse-server
```


But this mixed format worked - relative for the main clickhouse directory / data and %cd% prefixed for logs/config
```
docker run -d -p 8123:8123 -p9000:9000 \
    -v ./ch_data:/var/lib/clickhouse \
    -v %cd%/ch_logs:/var/log/clickhouse-server \
    -v %cd%/ch_config/config.xml:/etc/clickhouse-server/config.xml \
    --name clickhouse-server --ulimit nofile=262144:262144 \
    clickhouse/clickhouse-server
```

Thanks for your help :)

**Comment by hanzch** [comment]
> > > > Thanks. 谢谢.
> > > 
> > > 
> > > How to solve it? help如何解决？帮助
> > 
> > 
> > Change the configuration, do not use `C:\clickhouse\data:/var/lib/clickhouse,` can use the built-in mapping volumes, such as: `./clickhouse/data:/var/lib/clickhouse`
> 
> So your relative paths (`./`) answer is definitely effective but there were some caveats for me - probably some unrelated faux-pas on my part - but I thought I'd post this in case it helps others.
> 
> All relative paths failed for me too (`docker: Error response from daemon: create ch_config/config.xml: "ch_config/config.xml" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.`):
> 
> ```
> docker run -d -p 1123:8123 -p9000:9000 \
>     -v ./ch_data:/var/lib/clickhouse \
>     -v ./ch_logs:/var/log/clickhouse-server \
>     -v ./ch_config/config.xml:/etc/clickhouse-server/config.xml \
>     --name clickhouse-server --ulimit nofile=262144:262144 \
>     clickhouse/clickhouse-server
> ```
> 
> Also all `%cd%` prefixed paths failed (OP's file permission error)
> 
> ```
> docker run -d -p 1123:8123 -p9000:9000 \
>     -v %cd%/ch_data:/var/lib/clickhouse \
>     -v %cd%/ch_logs:/var/log/clickhouse-server \
>     -v %cd%/ch_config/config.xml:/etc/clickhouse-server/config.xml \
>     --name clickhouse-server --ulimit nofile=262144:262144 \
>     clickhouse/clickhouse-server
> ```
> 
> But this mixed format worked - relative for the main clickhouse directory / data and %cd% prefixed for logs/config
> 
> ```
> docker run -d -p 8123:8123 -p9000:9000 \
>     -v ./ch_data:/var/lib/clickhouse \
>     -v %cd%/ch_logs:/var/log/clickhouse-server \
>     -v %cd%/ch_config/config.xml:/etc/clickhouse-server/config.xml \
>     --name clickhouse-server --ulimit nofile=262144:262144 \
>     clickhouse/clickhouse-server
> ```
> 
> Thanks for your help :)

Maybe this has something to do with the fact that `./ch_config/config.xml` seems to be recognized as a directory on windows
