### ISSUE TITLE
One node of cluster failed, and cannot be started in PROD enviroment

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#55669]
version: 22.3.6.5

One Clickhouse server in the cluster failed yesterday, because of memory issue. After upgraded the memory, this node cannot be stated with the following issues. How can we fix it? thanks

![image](https://github.com/ClickHouse/ClickHouse/assets/79344970/6e3ea959-68da-44c4-ad46-71740edfd494)

![image](https://github.com/ClickHouse/ClickHouse/assets/79344970/75f77ad2-ef33-44ab-9cf1-9beb9ce648ec)

![image](https://github.com/ClickHouse/ClickHouse/assets/79344970/609978b0-1871-4f2c-89d7-612d2748e01a)

**Comment by den-crane** [comment]
22.3. is out support. Use 23.3 or 23.8
