### ISSUE TITLE
how to recover lightweight deleted data

### ISSUE THREAD

**Issue by wind-rain666** [ClickHouse/ClickHouse#55661]
I delete some data by mistake,  the data is not deleted physically, is there any way to recover?

**Comment by rschu1ze** [comment]
Based on the [lightweight delete documentation](https://clickhouse.com/docs/en/guides/developer/lightweight-delete), you might want to 1. [stop merges](https://clickhouse.com/docs/en/sql-reference/statements/system#stop-merges) on the affected table and 2. run `SELECT * FROM tab WHERE _row_exists = 0`.

**Comment by wind-rain666** [comment]
```
SELECT *
FROM system.merges

Query id: 32eaef59-5417-4d08-ad80-cbf14ffecfaa

Ok.

0 rows in set. Elapsed: 0.002 sec.
```

```
SELECT *
FROM js904.device_datas

Query id: 34a7cffb-fe0d-457d-b88d-987a739406d4

Ok.

0 rows in set. Elapsed: 0.006 sec. Processed 810.28 thousand rows, 810.28 KB (140.10 million rows/s., 140.10 MB/s.)
```
@rschu1ze there is no merge in system.merges table

**Comment by rschu1ze** [comment]
We can to ask @davenger...

**Comment by UnamedRus** [comment]
> does it means the data is deleted physically？

No, there was some chance, that merge didnt happened yet. (for example you don't insert new data in table)

**Comment by den-crane** [comment]
No, `where _row_exists=0` cannot work https://fiddle.clickhouse.com/86e50e4d-9b36-4a15-894b-edbdc2e23985

I think no way without manual interventions into parts

**Comment by UnamedRus** [comment]
https://fiddle.clickhouse.com/6c31bf1f-8d25-4699-9953-c53212662dcc

Actually, you can update _row_exists column via mutation

**Comment by den-crane** [comment]
> https://fiddle.clickhouse.com/6c31bf1f-8d25-4699-9953-c53212662dcc
> 
> Actually, you can update _row_exists column via mutation

wonderful, you are very super-creative :)
