### ISSUE TITLE
Incorrect (possibly) conversion toDateTime()

### ISSUE THREAD

**Issue by pic-Nick** [ClickHouse/ClickHouse#55675]
There is possible incorrect conversion of "zero date" to DateTime.

Version 22.10.7.13.
Example query:
`select timezone() as tz, toDate(0) as date0, toDateTime(toDate(0)) as datetime0`
returns result:
`Europe/Moscow   1970-01-01      1970-01-02 00:00:00`

Also, reproducible on the latest version: [example](https://fiddle.clickhouse.com/7b2a230d-b600-407a-a5f1-6e28a00e471d)

The `datetime0` should be `1970-01-01 00:00:00`.

**Comment by rschu1ze** [comment]
1970-01-01 doesn't play well with time zones: #46713, #42653, #42615.

**Comment by den-crane** [comment]
Date type has no Timezone attribute.

```
desc (select toDate(0, 'Europe/Moscow') x)

x	Date			
```

1970-01-01 Europe/Moscow is impossible date for DateTime type, because it's 3hours before UTC=0. 
DateTime does not support it.

Use DateTime64 https://fiddle.clickhouse.com/2da4f09c-7c85-45f8-98c2-bdb9b3759a89
