### ISSUE TITLE
Async Insert not working

### ISSUE THREAD

**Issue by nnaik25** [ClickHouse/ClickHouse#55677]
Clickhouse version : 22.3

Deployed on Kubernetes using altinity charts

1) Steps performed for enabling async insert:

CREATE USER clickhouse_admin IDENTIFIED BY 'password';
GRANT ALL ON *.* TO admin WITH GRANT OPTION;
ALTER USER clickhouse_admin SETTINGS async_insert = 1;

![image](https://github.com/ClickHouse/ClickHouse/assets/133762209/b9920900-1c46-4c60-95ca-5522868ed2c0)

2) Insert data using clickhouse rest api
https://clickhouse-dev1.ausdsm-01.bmc.com/?query=xxxxxxxxx

Issue:

I dont see data get buffered in asynchronous_inserts table. That means async insert is not working

![image](https://github.com/ClickHouse/ClickHouse/assets/133762209/a07ff251-0cd3-4bb3-81d2-6e95f62a7f92)

Please let me know if I am missing any step

**Comment by rschu1ze** [comment]
That's a very old ClickHouse version, try with a recent version, please.

**Comment by nnaik25** [comment]
Thanks for the response. which is the latest stable version you recommend for clickhouse

**Comment by rschu1ze** [comment]
The last long-term supported version is v23.8.

**Comment by nnaik25** [comment]
Thanks a lot. Will try this out !!

**Comment by den-crane** [comment]
>Insert data using clickhouse rest api
>https://clickhouse-dev1.ausdsm-01.bmc.com/?query=xxxxxxxxx

I doubt that you can make an insert using GET HTTP request. Provide a normal example how you do an insert.
