### ISSUE TITLE
SSL: intermediate certificates did not resolved

### ISSUE THREAD

**Issue by gle4er** [ClickHouse/ClickHouse#5568]
**Describe the bug**
Native ClickHouse client can not working with certificates that intermediate signed.

**How to reproduce**
* ClickHouse client version 19.7.3.1
* Server with openSSL settings:
```
    <openSSL>
        <server>
            <certificateFile>/etc/clickhouse-server/server.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-server/server.key</privateKeyFile>
            <dhParamsFile>/etc/clickhouse-server/dhparam.pem</dhParamsFile>
            <verificationMode>none</verificationMode>
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <caConfig>/etc/clickhouse-server/certs/chain.pem</caConfig>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
        </server>
    </openSSL>
```
* Client without specific options, run cmd:
```
clickhouse client -h click-tls-test.local --port 9440 -s
```
**Expected behavior**
Expected to be connected with secure connection.

**Error message and/or stacktrace**
```
WARNING: Certificate verification failed
----------------------------------------
Issuer Name:  /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
Subject Name: /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA

The certificate yielded the error: self signed certificate in certificate chain

The error occurred in the certificate chain at position 2
Accept the certificate (y,n)?
```

**Additional context**
Certificate is not self signed, signed by DigiCert. Perform HTTP GET via browser or wget/cURL returns OK, browser show green locker and certificate chain looks good.
Output from openSSL:
```
$ openssl s_client -connect click-tls-test.local:8228 -servername click-tls-test.local
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
verify return:1
depth=0 C = RU, ST = Moscow, L = Moscow, O = MyOrg, CN = *.local
verify return:1
---
Certificate chain
 0 s:C = RU, ST = Moscow, L = Moscow, O = MyOrg, CN = *.local
  i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
 1 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
 2 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
subject=C = RU, ST = Moscow, L = Moscow, O = MyOrg, CN = *.local

issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 High Assurance Server CA

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4511 bytes and written 448 bytes
Verification: OK
```
Also, ```trust list``` shows DigiCert High Assurance EV Root CA on server and client sides.

**Comment by filimonov** [comment]
Please check/share client configuration - it's in section: 
```
    <openSSL>
        <client>
           ....
        </client>
    </openSSL>
```
in `/etc/clickhouse-server/config.xml` - for interserver connections (if used) and in `/etc/clickhouse-client/config.xml` - for connections from clickhouse-client. 

In general - client should also be configured to see you root certificates (`<caConfig>`). If you will use `<loadDefaultCAFile>` it should also use root certificates installed in your system, but on some systems it will not work properly without providing path explicitly.

**Comment by gle4er** [comment]
With next client configuration, connect with SSL is works.
```
<openSSL>
    <client>
        <loadDefaultCAFile>true</loadDefaultCAFile>
	<caConfig>/etc/ssl/certs/ca-certificates.crt</caConfig>
        <cacheSessions>true</cacheSessions>
        <disableProtocols>sslv2,sslv3</disableProtocols>
        <preferServerCiphers>true</preferServerCiphers>
        <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
        <invalidCertificateHandler>
            <!-- Use for self-signed: <name>AcceptCertificateHandler</name> -->
            <name>RejectCertificateHandler</name>
        </invalidCertificateHandler>
    </client>
</openSSL>
```
But in configuration below, I specify system certificate manually.
If I remove caConfig line, clickhouse client didn't connect with next error:
```
Code: 210. DB::NetException: SSL Exception: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed
```
Clickhouse version:
```
ClickHouse client version 19.6.2.1
```
Server configuration and environment didn't changed.

**Comment by filimonov** [comment]
Most probably that means that openssl (statically linked in ClickHouse) is looking for default root certificates in bad place... :\ 

May be related to https://github.com/yandex/ClickHouse/pull/4167 and https://github.com/yandex/ClickHouse/issues/3983

**Comment by filimonov** [comment]
https://github.com/pocoproject/poco/blob/5e7d652c7518b3f3e9242f9618ce03ffd309a07a/NetSSL_OpenSSL/src/Context.cpp#L125

https://github.com/pocoproject/poco/blob/5e7d652c7518b3f3e9242f9618ce03ffd309a07a/NetSSL_OpenSSL/src/Context.cpp#L139

https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html

> SSL_CTX_set_default_verify_paths() specifies that the default locations from which CA certificates are loaded should be used. There is one default directory and one default file. The default CA certificates directory is called "certs" in the default OpenSSL directory. Alternatively the SSL_CERT_DIR environment variable can be defined to override this location. The default CA certificates file is called "cert.pem" in the default OpenSSL directory. Alternatively the SSL_CERT_FILE environment variable can be defined to override this location.

**Comment by gle4er** [comment]
> What build do you use?
I use official build:
```
$ clickhouse server -V
ClickHouse server version 19.7.3.9 (official build).
```
Also, this is build from docker registry.

**Comment by filimonov** [comment]
There is no bug here. 

Clickhouse doesn't do anything with certs, it doesn't analyze the cert chain / etc.  All that is done by OpenSSL.

Clickhouse just passes a few parameters to OpenSSL. ClickHouse has OpenSSL packaged in, and it has slightly different defaults (coming from ubuntu), and sometimes paths to default CA can differ on other platforms. 

See https://github.com/ClickHouse/ClickHouse/issues/17803
