### ISSUE TITLE
Slow restart after configuration changed and a huge number of records in metric related table

### ISSUE THREAD

**Issue by gaoxingliang** [ClickHouse/ClickHouse#55698]
**Describe the unexpected behaviour**
I have a three nodes clickhouse cluster with version - 22.10.7.13.
After I adding a backup disk conf and restart the cluster nodes one by one:
```
<clickhouse>
    <storage_configuration>
        <disks>
            <backups>
                <type>local</type>
                <path>/var/lib/clickhouse/tablebackups/</path>
            </backups>
        </disks>
    </storage_configuration>
    <backups>
        <allowed_disk>backups</allowed_disk>
        <allowed_path>/var/lib/clickhouse/tablebackups/</allowed_path>
    </backups>
</clickhouse>
```
The first node need more than 15 minutes to be healthy.  but other nodes restarts successfully in less than 1 minute.
below is the log:
[clickhouse (1).log](https://github.com/ClickHouse/ClickHouse/files/12923168/clickhouse.1.log)
As you can see, the `TableLoader` cost a lot of time. and I also found the `DatabaseAtomic ` also cost a lot of time.

What I found:
1. the first node will receive insert requests during restart. the other nodes will NOT.
2. Even the first node restarts successfully, and I restarted again, it will still need a long time to restart. So it seems the self-check process still requires more than 15 minutes.
3. the io and cpu is low for the node.

**Expected behavior**
It should be started up quickly enough.  As this issue keep persists, any conf I can use to help to figure out what's happening? eg loglevel settings?

**Comment by gaoxingliang** [comment]
I checked this issue: 
https://github.com/ClickHouse/ClickHouse/issues/10087
and found:  the count for system.parts is : 366. and the count for system.parts_columns are 43341.
Will the number of columns cause this problem? but I don't know why other nodes doesn't encounter this.

**Comment by gaoxingliang** [comment]
<img width="332" alt="企业微信截图_16975274395582" src="https://github.com/ClickHouse/ClickHouse/assets/3148215/6c96e2a6-b2e9-4ffb-ae55-0c470f4e6d74">

Why those monitoring table has so many records and not cleaned up automatically?

**Comment by alifirat** [comment]
Hey @gaoxingliang 

About the system tables, I'll recommend to read the following article from [Altinity](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/) about system.tables. 

Personal recommendation: if you have identify some system.tables that are not relevant for you then don't store them because it's both memory and disk consuming.
