### ISSUE TITLE
When query with DateTime64 column, got inconsistent result

### ISSUE THREAD

**Issue by lizhiyong2000** [ClickHouse/ClickHouse#55700]
I have a distributed cluster with 3 shards and 2 replicas on 3 server nodes as below:
![image](https://github.com/ClickHouse/ClickHouse/assets/5274809/b2b3c9c2-6874-4046-b412-acb6809c72fc)

as described in this link: https://zhuanlan.zhihu.com/p/461792873

and a distributed  table 

CREATE TABLE if not exists test_01.viid_face_shard(
    `device_id`                           String,
    `face_id`                           String,
    `record_time`       DateTime64(3)   DEFAULT toDateTime64(now64(), 3)
)
ENGINE=ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard01}/viid_face
', '{replica01}')
PARTITION BY (toYYYYMMDD(record_time))
PRIMARY KEY (device_id, face_id, record_time)
ORDER BY (device_id, face_id, record_time);

CREATE TABLE if not exists test.viid_face_all(
    `device_id`                           String,
    `face_id`                           String,
    `record_time`       DateTime64(3)   DEFAULT toDateTime64(now64(), 3)
)
ENGINE = Distributed('test_cluster', '', 'viid_face_shard', rand());

when query from the distruted table by the column record_time , inconsistent result returned
![image](https://github.com/ClickHouse/ClickHouse/assets/5274809/daa3a759-96b4-4fc9-a990-520246b2393b)

And found that if add the toUnixTimestamp tranform to the column record_time,  the result became consistent.
![image](https://github.com/ClickHouse/ClickHouse/assets/5274809/93309949-5b80-4810-8152-aa9aa3374525)

**Expected behavior**
Expect the query without toUnixTimestamp get consistent result

ClickHouse Version:
22.2.2.1

**Comment by canhld94** [comment]
Should be fixed in  #55682

**Comment by den-crane** [comment]
>22.2.2.1

@canhld94 it cannot be related. https://github.com/ClickHouse/ClickHouse/pull/55682 is only related to 23.9 version

**Comment by den-crane** [comment]
@lizhiyong2000 is it correct if you query it like this `> '2023-10-12 16:00:00.000'`

**Comment by canhld94** [comment]
> @canhld94 it cannot be related. https://github.com/ClickHouse/ClickHouse/pull/55682 is only related to 23.9 version

@den-crane oh yes, I didn't read the description carefully.
