### ISSUE TITLE
version:22.10.2.11,load parquet file, transfer timestamp to date,the result is error

### ISSUE THREAD

**Issue by gf19950913** [ClickHouse/ClickHouse#55719]
I have two version clickhouse, 22.10.2.11 and 20.4.5.36
Now, there is a parque file 
![image](https://github.com/ClickHouse/ClickHouse/assets/16682277/4454fd86-2387-4290-9e74-bf8dea03b253)
![image](https://github.com/ClickHouse/ClickHouse/assets/16682277/73eb7526-0f34-4a59-927c-01e757981947)
![image](https://github.com/ClickHouse/ClickHouse/assets/16682277/8dcf6dd5-54ca-4421-9041-d03e69449c28)

Note: The time fields are all the same

I'm executing in both clickhouse at the same time with the sql 
```select * from file('test.parquet',Parquet,'`r_cut_pay_date` Nullable(DateTime), `最小下单时间` Nullable(DateTime), `最小下单时间111` Nullable(DateTime), `最小下单时间的日期` Nullable(Date), `order_id` Nullable(Int32), `status` Nullable(Int16), `contract_no` Nullable(String)')```

Different results were obtained in the two Clickhouses

22.10.2.11
![image](https://github.com/ClickHouse/ClickHouse/assets/16682277/5b43df8a-9dd7-4727-a9a4-e2bd6f751db0)
The result was wrong and the correct one was "2023-10-1"
When I changed the Date type to DateTime, the result was correct, just like the other time fields

20.4.5.36
![image](https://github.com/ClickHouse/ClickHouse/assets/16682277/98c97afa-8da9-4cd9-8c90-11474ce24b31)
The result is correct

The timezone for both Clickhouses is Asia/Shanghai
The timezone for both docker container is Etc/UTC

When I changed the time zone of docker container to Asia/Shanghai for version 22.10.2.11，the result is same

When I changed the time zone of clickhouse to UTC for version 22.10.2.11, the results were all different by 8h, and the date field values were also "2023-09-30"

When I use the toDate function to process other datetime fields, the result is ""2023-10-1"", which is correct

So I wonder if there is something wrong with the time zone taken when 22.10.2.11 converts the timestamp from parquet to clickhouse date type?

**Comment by Avogar** [comment]
That's because Parquet Timestamp type can be UTC adjusted and most likely it is in your file. It means that file contains timestamp values in UTC timezone. And if you specify type `DateTime` without explicit timezone, we CAST read UTC timestamp into timestamp with local timezone, but when you specify type `Date`, we CAST UTC timestamp into Date, but Date doesn't know anything about the timezone.
So, it's the same as:
```
avogar-dev :) set session_timezone='Asia/Shanghai'

SET session_timezone = 'Asia/Shanghai'

Query id: ea8fd5b0-4cba-4bdb-bc10-d5678a22eefe

Ok.

0 rows in set. Elapsed: 0.001 sec.

avogar-dev :) select CAST(toDateTime(1696094838.000000, 'UTC'), 'DateTime')

SELECT CAST(toDateTime(1696094838., 'UTC'), 'DateTime')

Query id: 42c963f0-4903-4d81-bb10-8d11c06f3142

┌─CAST(toDateTime(1696094838., 'UTC'), 'DateTime')─┐
│                              2023-10-01 01:27:18 │
└──────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.009 sec.

avogar-dev :) select CAST(toDateTime(1696094838.000000, 'UTC'), 'Date')

SELECT CAST(toDateTime(1696094838., 'UTC'), 'Date')

Query id: 9c3f6b66-7531-42d9-a16b-186fcdce71ad

┌─CAST(toDateTime(1696094838., 'UTC'), 'Date')─┐
│                                   2023-09-30 │
└──────────────────────────────────────────────┘

1 row in set. Elapsed: 0.009 sec.
```

If your data contains timestamps in UTC, you should specify `DateTime('UTC')` when you read it to avoid confusion

**Comment by gf19950913** [comment]
@Avogar  

Actually, my question is **why are the two versions of clickhouse handled differently**

Because my logic here is to read the data from parquet and insert it into the table
just like 
``` 
insert into xxx select * from file('test.parquet', Parquet, "`r_cut_pay_date` Nullable(DateTime), `最小下单时间` Nullable(DateTime), `最小下单时间111` Nullable(DateTime), `最小下单时间的日期` Nullable(Date), `order_id` Nullable(Int32), `status` Nullable(Int16), `contract_no` Nullable(String)")
```
If I replace * with specific fields and specify the type, then I can do as you say, but it is a bit complicated for me

Because it is correct to read with DateTime type, and in order to reduce changes, I tried to read parquet fields with DateTime type instead of Date type. 

The insert field is of type Date and the select field is of type DateTime. From the result, the date after the insert is correct

After testing, the result was also correct

**Comment by gf19950913** [comment]
Ok, thank you for your reply
