### ISSUE TITLE
<Error> MaterializedMySQLSyncThread: Code: 49. DB::Exception: GTIDSets updates other: 7881466 invalid successor to 7881467. (LOGICAL_ERROR)

### ISSUE THREAD

**Issue by kulouzhiwu** [ClickHouse/ClickHouse#55733]
<img width="290" alt="MySQL binlog_order_commits settings" src="https://github.com/ClickHouse/ClickHouse/assets/58103094/9fab7497-b2e4-4ca7-aa1b-970ce5c388f0">
<Error> MaterializedMySQLSyncThread: Code: 49. DB::Exception: GTIDSets updates other: 7881466 invalid successor to 7881467. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):
0. ./build_docker/./src/Common/Exception.cpp:98: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c604bf7 in /usr/lib/debug/usr/bin/clickhouse.debug
1. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x00000000071180a7 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/./src/Core/MySQL/MySQLGtid.cpp:0: DB::GTIDSets::update(DB::GTID const&) @ 0x0000000011d04f60 in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/./contrib/llvm-project/libcxx/include/optional:327: DB::MySQLReplication::Position::update(std::shared_ptr<DB::MySQLReplication::EventBase>) @ 0x0000000011d128e2 in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/./src/Core/MySQL/MySQLReplication.cpp:0: DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x0000000011d13769 in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/./src/IO/BufferBase.h:40: DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x0000000011cfbb91 in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/./src/Core/MySQL/PacketEndpoint.cpp:0: DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x0000000011cfc8c9 in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/./src/Core/MySQL/MySQLClient.cpp:175: DB::MaterializedMySQLSyncThread::synchronization() @ 0x0000000011d37ccc in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/./src/Databases/MySQL/MaterializedMySQLSyncThread.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::MaterializedMySQLSyncThread::startSynchronization()::$_0>(DB::MaterializedMySQLSyncThread::startSynchronization()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000011d42e91 in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/./base/base/../base/wide_integer_impl.h:809: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c6e5624 in /usr/lib/debug/usr/bin/clickhouse.debug
10. start_thread @ 0x000000000000744b in /usr/lib64/libpthread-2.26.so
11. clone @ 0x00000000000ed40f in /usr/lib64/libc-2.26.so
 (version 23.8.2.7 (official build))

**Comment by chen1044316902** [comment]
same probem

**Comment by jmerchantmetrics** [comment]
Same Issue

```
2024.08.12 15:46:46.799024 [ 203687 ] {fa802abc-d040-480d-a5e9-eca4973ebe33} <Error> DynamicQueryHandler: Code: 49. DB::Exception: GTIDSets updates other: 1175273 invalid successor to 1175274. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c5c527b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000077960ec
2. DB::Exception::Exception<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000779800b
3. DB::GTIDSets::update(DB::GTID const&) @ 0x000000000fbe3891
4. DB::MySQLReplication::Position::update(std::shared_ptr<DB::MySQLReplication::EventBase>) @ 0x000000000fec810f
5. DB::MySQLReplication::MySQLFlavor::readPayloadImpl(DB::ReadBuffer&) @ 0x000000000fec8e62
6. DB::MySQLProtocol::IMySQLReadPacket::readPayload(DB::ReadBuffer&, unsigned char&) @ 0x000000000feb4303
7. DB::MySQLProtocol::PacketEndpoint::tryReceivePacket(DB::MySQLProtocol::IMySQLReadPacket&, unsigned long) @ 0x000000000feb50ac
8. DB::MaterializedMySQLSyncThread::synchronization() @ 0x000000000fee296c
9. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::MaterializedMySQLSyncThread::startSynchronization()::$_0>(DB::MaterializedMySQLSyncThread::startSynchronization()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000feeee87
10. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, 
Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c677243
11. ? @ 0x00007feadd524ac3
12. ? @ 0x00007feadd5b6850
```
