### ISSUE TITLE
请问有没有中国大陆的微信用户群，可以探讨关于clickhouse的问题

### ISSUE THREAD

**Issue by Etoakor** [ClickHouse/ClickHouse#55762]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

```[tasklist]
### Tasks
```

**Comment by Etoakor** [comment]
/

**Comment by lingtaolf** [comment]
可以拉你一下，查收邮箱

**Comment by xuefeimiaoao** [comment]
> 可以拉你一下，查收邮箱

可以拉一下我吗@lingtaolf，感谢~

**Comment by lingtaolf** [comment]
> > 可以拉你一下，查收邮箱
> 
> 可以拉一下我吗@lingtaolf，感谢~

可以留个邮箱,我发你

**Comment by lingtaolf** [comment]
`guodaxia2999` 可以加一下郭老师的微信,让他拉你们进去,最好备注一下github
