### ISSUE TITLE
create kafka table hang until restar clickhouse

### ISSUE THREAD

**Issue by zzl870123** [ClickHouse/ClickHouse#55763]
I have about 20+ kafka tables in one clikhouse，now i want create new kafka table and i found question. Many times i create kafka table will hang . The create sql just in process and timeout. In errlog i can‘t find the tableName and kafka topic name. Before I have about 10+ kafka tables ,I create table will hang in kinit kafka in clickhouse but now it just have nothing in log.
Is there any limit kafka table aobout one clickouse?  Can i see create step in witch logs?

**Comment by Algunenano** [comment]
Please provide reproducer steps, error messages, CH version or anything that could be useful.

> Is there any limit kafka table aobout one clickouse?

No

> Can i see create step in witch logs?

Check text logs
