### ISSUE TITLE
ClickHouse cannot recognize empty S3 directories

### ISSUE THREAD

**Issue by zidane-wcp** [ClickHouse/ClickHouse#55773]
When I access S3 with ClickHouse, there is an empty directory in my S3 path, which leads to a situation where the path in S3 appears as something like app-logs//2023/01/01, with two consecutive slashes. ClickHouse seems unable to recognize this key and reports an error, 'The specified key does not exist.' Other keys can be accessed normally. How can this be resolved?

**Comment by yariks5s** [comment]
Hello, @zidane-wcp! Sorry, can you provide us more details about your use case and how to reproduce this problem?
