### ISSUE TITLE
DistributedAsyncInsertBatch stuck after improper shutdown

### ISSUE THREAD

**Issue by alexvanolst** [ClickHouse/ClickHouse#55807]
Clickhouse never seems to recover without user intervention when something goes wrong with DistributedAsyncInsertBatch after an improper shutdown. If the shutdown causes a `.bin` file that was expected to not be found, it is retried indefinitely.

I then observe the `ClickHouseMetrics_DistributedFilesToInsert` metric increasing. 

This causes all subsequent async inserts to be blocked and just accumulate on the disk (often filling the disk as this data is not ever merged).

Currently I have to navigate to the directory mentioned in the the log file and remove the missing .bin file from `current_batch.txt` before the DistributedAsyncInsertBatch can continue

**Does it reproduce on recent release?**

I encounter this frequently on `23.7.4.5`

**Expected behavior**

I would expect this missing `.bin` file to skipped so that subsequent distributed inserts function without user intervention.

**Error message and/or stacktrace**

```
{
    "date_time": "1697697014.881620",
    "thread_name": "",
    "thread_id": "217",
    "level": "4",
    "query_id": "",
    "logger_name": "default.redacted_table.DirectoryMonitor.default",
    "message": "File \\/var\\/lib\\/clickhouse\\/data\\/default\\/redacted_table\\/shard1_all_replicas\\/\\/6267792.bin does not exists, likely due abnormal shutdown",
    "source_file": "src\\/Storages\\/Distributed\\/DistributedAsyncInsertBatch.cpp; void DB::DistributedAsyncInsertBatch::sendBatch()",
    "source_line": "208"
}
```

**Additional context**

I run a number of clickhouse nodes on AWS, and this comes up frequently whenever there is some AWS issue that would cause an improper shutdown

**Comment by azat** [comment]
It should be fixed by https://github.com/ClickHouse/ClickHouse/pull/57480

Please reopen if you still experience this issue
