### ISSUE TITLE
parameter max_bytes_to_merge_at_min_space_in_pool doesn't work

### ISSUE THREAD

**Issue by xpleaf** [ClickHouse/ClickHouse#55828]
## ClickHouse Version
```
21.8
```

## question

I had set the parameter `max_bytes_to_merge_at_min_space_in_pool` in `config.xml`:

```
<merge_tree>
    <max_bytes_to_merge_at_min_space_in_pool>5368709120</max_bytes_to_merge_at_min_space_in_pool>
</merge_tree>
```

> 5368709120 bytes, 5GB

To prevent data blocks larger than 5GB from merging, Because there are a lot of data blocks over 5GB to merge, causing an exception (my machine doesn't have that much memory).

![image](https://github.com/ClickHouse/ClickHouse/assets/14944242/8b5dd117-c79e-4805-b74a-7a57344c27ee)

![image](https://github.com/ClickHouse/ClickHouse/assets/14944242/53a66acc-22c9-4c8c-8cf7-7697ea614635)

However, it doesn't work. Is it a bug?

I've noticed @den-crane mention this parameter:
![image](https://github.com/ClickHouse/ClickHouse/assets/14944242/023656d2-2c68-4166-94a1-3e060b66b88a)

It doesn't look that way. 

Who can help answer it, my goal is to prevent large data parts from merging, to avoid exceeding the host memory and throwing exceptions, thank you!

**Comment by den-crane** [comment]
21.8 is out of support

max_bytes_to_merge_at_min_space_in_pool -- is approximate. Not exact limit. Merge estimates the output size, but in after the merge it can be bigger.


>Because there are a lot of data blocks over 5GB to merge, causing an exception (my machine doesn't have that much memory).

What do you mean "causing an exception" ?

**Comment by xpleaf** [comment]
@den-crane Thanks.

> 21.8 is out of support

Well, although I did see this parameter in version 21.8 and it appears that the setting is in effect.

<img width="1174" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/14944242/6fa1e8f0-a2c3-45fd-ab7d-e4b64f8e0f72">

> What do you mean "causing an exception" ?

Meaning, when I look at the table system.merges, I see that the data merge continues to be attempted after the failure, and it continues uninterrupted.

This led to a problem where we found that once the failed merge task started, the server IO would be very high.

**Comment by den-crane** [comment]
How much memory do you have?

What errors do you see is in the clickhouse logs ?

**Comment by xpleaf** [comment]
@den-crane Hi, by the way, are there any plans for the community to support the SharedMergeTree engine in the open source release? At present, the design method of ClickHouse distributed node makes users very confused, and increases the cost of ordinary users to a certain extent.

**Comment by den-crane** [comment]
>Hi, by the way, are there any plans for the community to support the SharedMergeTree engine in the open source release?

I am affiliated to Clickhouse,inc. I have no idea about their plans.

**Comment by xpleaf** [comment]
> How much memory do you have?
> 
> What errors do you see is in the clickhouse logs ?

Errors:
```
6434 2023.10.19 20:04:20.573678 [ 1233 ] {} <Error> db.table (e435e77e-8473-4a94-a435-e77e8473fa94): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQueue::SelectedEntryPtr)::(anonymous class)::opera     tor()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 29.50 GiB (attempt to allocate chunk of 8589913960 bytes), maximum: 27.87 GiB: While ex     ecuting MergingSortedTransform, Stack trace (when copying this message, always include the lines below):
```

Memory：
```
Server Memory: 32GB
Configuration threshold: 0.9
```

**Comment by den-crane** [comment]
Do you store wide/long Strings is in the table ?

**Comment by xpleaf** [comment]
> Do you store wide/long Strings is in the table ?

That's right, we had a brief overlong string write at noon today, which caused the problem. The number of data strips is small, but the volume is large.

![image](https://github.com/ClickHouse/ClickHouse/assets/14944242/e8d99783-78a8-4aba-964b-7cce551e0b3e)

**Comment by xpleaf** [comment]
> The most probably this solved by `merge_max_block_size_bytes`
> 
> v23.5.1.3174-stable.md:* Introduced settings: - `merge_max_block_size_bytes` to limit the amount of memory used for background operations. - `vertical_merge_algorithm_min_bytes_to_activate` to add another condition to activate vertical merges. [#49313](https://github.com/ClickHouse/ClickHouse/pull/49313) ([Nikita Mikhaylov](https://github.com/nikitamikhaylov)).

So is this a solution to prevent very large data blocks from merging? We're working on an update. It would be great if it worked out.

**Comment by xpleaf** [comment]
@den-crane Thanks for your guidance. I'll give it a try.
