### ISSUE TITLE
Aggregate spill to disk leads too many files

### ISSUE THREAD

**Issue by Aaaaaaron** [ClickHouse/ClickHouse#55831]
Hi gays
Recently I was testing aggregating spill with a large amount of data and found that in some scenarios, the amount of data in the spill is very small and the number of files is particularly large and this leads to "too many open files". Here are two ideas about improving aggregate spill:
1. All temporary files are flushed to a certain file or fixed number of files, instead of generating a new file once executing Aggregator::executeOnBlock().
2. Or limit the minimum spill file size (number of lines), if the data is small, we don't spill it

**Comment by nickitat** [comment]
#55281
