### ISSUE TITLE
last_value returns wrong result

### ISSUE THREAD

**Issue by yujiarista** [ClickHouse/ClickHouse#55843]
last_value produces wrong data in some cases

Reproduced on 23.7 and 23.9, not on 23.6 and 23.5
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**How to reproduce**
create database test on cluster default engine Atomic

CREATE TABLE test.test on cluster default
(
    id String,
    time DateTime64(9),
    key Int64,
    value Bool,
)
ENGINE = ReplicatedMergeTree
PARTITION BY toYYYYMM(time)
ORDER BY (key, id, time)

insert into test.test values ('id0', now(), 3, false)

The following query returns true which is wrong.

SELECT
last_value(value) OVER (PARTITION BY id ORDER BY time ASC) as last_value
FROM test.test
WHERE (key = 3)

The right result is returned if 'PARTITION BY id' or WHERE clause is removed

SELECT
last_value(value) OVER (ORDER BY time ASC) as last_value
FROM test.test
WHERE (key = 3)

SELECT
last_value(value) OVER (PARTITION BY id ORDER BY time ASC) as last_value
FROM test.test

**Comment by den-crane** [comment]
any agg. function seems to be affected
https://fiddle.clickhouse.com/6df00a9f-8126-44ec-8954-b84298c7c734

**Comment by den-crane** [comment]
```
set optimize_read_in_window_order=0, optimize_read_in_order=0;
```
helps.

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/2a9a4f53-eda3-4e67-a94f-7e193350d5ab
String size is too big (18446603614377872527), maximum: 2147483647. (TOO_LARGE_STRING_SIZE)

**Comment by den-crane** [comment]
segfault https://fiddle.clickhouse.com/c0a03844-2c25-4cdf-b237-11f5444a2f3d

```
CREATE TABLE test  (time DateTime, value String)
ENGINE = MergeTree
ORDER BY (time) as select 0, '';

SELECT any(value) OVER (ORDER BY time ASC)  FROM test
```

**Comment by yujiarista** [comment]
@den-crane Thanks for the update! We found this issue while validating upgrade from 23.4 to 23.9, and we use window functions a lot. Will the use of 
> set optimize_read_in_window_order=0, optimize_read_in_order=0;

or identity
> PARTITION BY identity(id)

cause a performance regression?

**Comment by yujiarista** [comment]
@den-crane We also found that the issue seems to happen only when the target column of the window function has only the zero value (0 for numeric or bool type, or empty string for string type). The window functions seem to work as expected when the target column has other values. Could you confirm if this is true?
If it is true, then we may be able to proceed with the upgrade while waiting for a fix.

**Comment by antaljanosbenjamin** [comment]
Hi @yujiarista, I am working on finding the root cause of the issue. Without that it is really hard to say anything for sure. Maybe the bug has slightly different behavior on different versions.

**Comment by den-crane** [comment]
> @den-crane We also found that the issue seems to happen only when the target column of the window function has only the zero value (0 for numeric or bool type, or empty string for string type). The window functions seem to work as expected when the target column has other values. Could you confirm if this is true? If it is true, then we may be able to proceed with the upgrade while waiting for a fix.

the issue is related to `optimize_read_in_window_order`

In this case `create table ... ORDER BY (key, id, time)` -> `WHERE (key = 3) PARTITION BY id ORDER BY time` 
`key, id, time` -> `key, id, time`
If you change partition key, for example using a special function `PARTITION BY identity(id)` then clickhouse is unable to use this optimization `read_in_..`.

**Comment by antaljanosbenjamin** [comment]
The issue is also related enabling sparse columns. By using the setting `ratio_of_defaults_for_sparse_serialization = 1` for MergeTree, it works perfectly. Tomorrow I will continue my investigation further.

**Comment by antaljanosbenjamin** [comment]
@yujiarista , now I can confirm that the issue was not incorrect handling of sparse columns in window functions. This means you are safe if the you disable sparse column serialization by setting the `ratio_of_defaults_for_sparse_serialization` MergeTree settings to `1` (or if you are sure the used columns aren't serialized as sparse columns, which means the ratio of default values are less then the mentioned setting. For more details, please check the [docs](https://clickhouse.com/docs/zh/operations/settings/merge-tree-settings#ratio_of_defaults_for_sparse_serialization). 

Thanks for reporting the issue, the [fix is already implemented](https://github.com/ClickHouse/ClickHouse/pull/55895), hopefully it will be backported and released soon.

**Comment by yujiarista** [comment]
Hi @antaljanosbenjamin , thank you very much for the information! 
I experimented with ratio_of_defaults_for_sparse_serialization. It does work, except that existing parts in sparse format seem not affected by changing the setting. Is there any efficient way to transform existing sparse column parts?

**Comment by den-crane** [comment]
@yujiarista you can remerge them. Try to use `optimize in partition` if they are small.

**Comment by antaljanosbenjamin** [comment]
@yujiarista **I couldn't test it yet**, but we assume that after turning off sparse column format (`ratio_of_defaults_for_sparse_serialization = 1`) this query should do the trick: `OPTIMIZE TABLE <table-name> FINAL`. See the [docs](https://clickhouse.com/docs/en/sql-reference/statements/optimize) about `OPTIMIZE`. I can confirm whether this really works or not later today.
