### ISSUE TITLE
Don't use multipart uploads for S3/GCS in the virtual filesystem abstraction.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#55851]
Blocked untill implemented:
- reliable rollback of disk transaction on exceptions
- garbage collection

Requeires implemetation:
- change file apply's serialization in order to save size in file metadata

Multipart uploads are bad for the following reasons:

1. They require two additional requests, CreateMultipartUpload and CompleteMultipartUpload, that cost money.
2. There is a limit on the maximum number of parts, somewhere around 10,000. Combining with fixed-size parts it leads to the inability to have very large merges in ClickHouse.
3. If you want to copy a blob created with multipart uploads, you have to switch to UploadPartCopy instead of CopyObject, which complicates the code.
4. There is such a thing as incomplete multipart uploads, and their cleanup has to be configured on the AWS side.
5. Multipart objects is only a small abstraction on top of parts, not providing any benefits in the internal storage over multiple parts, and we don't need this abstraction from the service anyway because we natively support files represented by multiple objects.
6. Many S3 compatible storages don't support multipart uploads, or have implemented the support lately, or have bugs in their implementation, or have limitations in their implementation, such as supporting only constant size of parts during the upload.
7. Multipart uploads is something, that makes code more complex.
8. GCS does not support multipart copy, making backup and restore inefficient.

The only hypothetical advantage of multipart uploads is the cost of object deletion and the cost of moving the objects between different storage tiers. This does not justify using the multipart uploads, and does not even justify keeping it as an option.

**Comment by CheSema** [comment]
I like the idea to use append mode in clickhosue metadata files more often.
But I like it not as total replacement for multi part upload, but as in combination with it in order to achieve low memory consumption for uploads.

The proposal is simple -- use 5mb buffer to write key as multi part upload, when key is large than 1000parts * 5mb, create and start witting to the next new key, combine all the written keys in metadata file.
Prons -- low memory.
Cons -- more s3 calls, it is more expensive.
But in that case clickhouse would have the ability to tune the whole range of option from the chipper writes with hight memory consumption to the expensive writes with low memory consumption.

**Comment by azat** [comment]
>Prons -- low memory.

Why? AFAICS current memory usage depends on `s3_min_upload_part_size`/`s3_max_upload_part_size`, default is 16MiB, you are proposing 5MiB (though I guess those setting will be respected as well).

**Comment by CheSema** [comment]
> > Prons -- low memory.
> 
> Why? AFAICS current memory usage depends on `s3_min_upload_part_size`/`s3_max_upload_part_size`, default is 16MiB, you are proposing 5MiB (though I guess those setting will be respected as well).

I do not understand the question. But I can add more context to you. May be it is an answer.

16Mb is larger than 5Mb. If s3 responses slowly there are several such buffer inflight.
GCP does not work with variable sizes of parts in mpu, so we uses strict sizes for them.
That all limit the maximum size for one file. Append mode helps to overcome such limitations.

**Comment by azat** [comment]
> 16Mb is larger than 5Mb in more than 3 times.

I mean that even now you can decrease `s3_min_upload_part_size` to 5MiB.

> GCP does not work with variable sizes of parts in MPU

Actually they already fixed this (recently), but for instance R2 (cloudflare) does not support them still, and they are not going to (as far as I'm aware)

> so we uses strict sizes for them

Interesting, I don't see this in the code... (though yes, there is `s3_strict_upload_part_size`)

> That all limit the maximum size for one file. Append mode helps to overcome such limitations.

I'm not sure that I understand why this limits the maximum size of the file, so if I will set `s3_min_upload_part_size=5MiB` then I should have the same memory usage and max size limit, right?

**Comment by CheSema** [comment]
> I'm not sure that I understand why this limits the maximum size of the file, so if I will set s3_min_upload_part_size=5MiB then I should have the same memory usage and max size limit, right?

S3 has the limitation for file size in one put request - 5Gb.
For multipart upload the file size is limited by size of part * parts count, max size of part is 5G, min size of part is 5Mb, max parts count is 1000.

So the max file size with MPU is s3_strict_upload_part_size * 1000.

**Comment by CheSema** [comment]
> I mean that even now you can decrease s3_min_upload_part_size to 5MiB.

if we do that right now, we end up in a situation when we unable to write file larger than 5Gb.

**Comment by alexey-milovidov** [comment]
Ok.
