### ISSUE TITLE
Merge partition always failed

### ISSUE THREAD

**Issue by vichoho** [ClickHouse/ClickHouse#5587]
Hi ,
I usually found some error like below in my different data nodes.
It never stopped except I detached the partition and sometimes it would cause heavy I/O.
![merge](https://user-images.githubusercontent.com/4196866/59321489-ccfc8e80-8d04-11e9-9da5-cddd9bc16fea.jpg)

How can I fix it?

> 2019.06.12 09:55:20.153756 [ 11 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 40, e.displayText() = DB::Exception: Checksum doesn't match: corrupted data. Reference: 2ffc95ac4508447112cde110fc1a6177. Actual: 88c103389eb6433272556218605c4ca9. Size of compressed block: 87711.: (while reading column START_CQI): (while reading from part /data/clickhouse/data/table_trace/archive/20190611-90040_12565_12570_1/ from mark 199 with max_rows_to_read = 8192): Cannot fetch required block. Stream MergeTreeSequentialBlockInputStream, part 5, e.what() = DB::Exception, Stack trace:
> 
> 0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x5e3f7e6]
> 1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2bce50f]
> 2. clickhouse-server(DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&)+0xc43) [0x5e54983]
> 3. clickhouse-server(DB::CompressedReadBufferFromFile::nextImpl()+0x26) [0x5e54e96]
> 4. clickhouse-server() [0x4d20919]
> 5. clickhouse-server(DB::DataTypeString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const+0x2b5) [0x4d25da5]
> 6. clickhouse-server(DB::MergeTreeReader::readData(std::string const&, DB::IDataType const&, DB::IColumn&, unsigned long, bool, unsigned long, bool)+0x29a) [0x53c5fea]
> 7. clickhouse-server(DB::MergeTreeReader::readRows(unsigned long, bool, unsigned long, DB::Block&)+0x32b) [0x53c674b]
> 8. clickhouse-server(DB::MergeTreeSequentialBlockInputStream::readImpl()+0x1ab) [0x50b431b]
> 9. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x21f) [0x4c80fbf]
> 10. clickhouse-server(DB::ColumnGathererStream::fetchNewBlock(DB::ColumnGathererStream::Source&, unsigned long)+0x3d) [0x51c95dd]
> 11. clickhouse-server(void DB::ColumnGathererStream::gather<DB::ColumnString>(DB::ColumnString&)+0x1c2) [0x4f0c822]
> 12. clickhouse-server(DB::ColumnGathererStream::readImpl()+0x3ae) [0x51ca0ee]
> 13. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x21f) [0x4c80fbf]
> 14. clickhouse-server(DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::MergeTreeDataMergerMutator::FuturePart const&, DB::MergeListEntry&, long, DB::DiskSpaceMonitor::Reservation*, bool)+0x36e4) [0x505f6c4]
> 15. clickhouse-server(DB::StorageMergeTree::merge(bool, std::string const&, bool, bool, std::string*)+0x3cc) [0x4f9727c]
> 16. clickhouse-server(DB::StorageMergeTree::backgroundTask()+0xe9) [0x4f9a239]
> 17. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x3d0) [0x500f970]
> 18. clickhouse-server() [0x6a7fa8f]
> 19. /lib64/libpthread.so.0(+0x7e25) [0x7ff3ddaeee25]
> 20. /lib64/libc.so.6(clone+0x6d) [0x7ff3dd30ebad]

**Comment by vichoho** [comment]
This issue still happened and CH always tried to merge the abnormal part and caused the merge process never stopped.
Does anyone know the root cause?

**Comment by blinkov** [comment]
@vichoho, do you have any further questions?

**Comment by filimonov** [comment]
The reason is the data in the file was corrupted (most probably some hardware issue). 

If the problem is on the single replica - detach table, drop folder, attach table. It should download the part from other replica.

**Comment by robot-clickhouse** [comment]
@vichoho, do you have any further questions?

**Comment by alexey-milovidov** [comment]
> If the problem is on the single replica

If the table is replicated, it will recover automatically without any manual actions.
If the table is non-replicated, then broken parts (may appear due to disk bitrot) are impossible to repair.
