### ISSUE TITLE
user memory tracking - wrong numbers

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#55875]
That bash script does async inserts in loop:

```bash
#!/bin/bash

clickhouse-client --query='drop table if exists test_inserts'
clickhouse-client --query='create table test_inserts engine=Null AS system.numbers'

total_iterations=40000
iterations_in_parallel=80

for ((i = 1; i <= $total_iterations; i++)); do
    while true; do
        running_jobs=$(jobs -p | wc -w)
        if [ $running_jobs -lt $iterations_in_parallel ]; then
            break
        fi
        sleep 0.01
    done
    (
        (
        clickhouse-local --query='SELECT * FROM numbers(1000000)' | curl 'http://localhost:8123/?query=INSERT%20INTO%20test_inserts%20FORMAT%20TSV&async_insert=1' --data-binary @-
        # echo "INSERT $i completed"
        clickhouse-client --query="WITH (SELECT formatReadableSize(memory_usage) FROM system.user_processes WHERE user='default') as user_mem, (SELECT formatReadableSize(value) FROM system.metrics WHERE metric='MemoryTracking') AS system_mem SELECT 'User: ' || user_mem || ', system: ' || system_mem"
    ) &)
done

wait
```

It also prints the user memory tracker and system memory tracker.

Run it and keep it running for several minutes. After a while the user memory tracker will start showing numbers much bigger than the system memory tracker:

```
User: 6.45 GiB, system: 1.12 GiB
```

And if you use `max_memory_usage_for_user` it will start returning memory exceptions despite the that that there is plenty of RAM. 

Once you stop doing async inserts the user memory tracker gets back to normal.

**Comment by nickitat** [comment]
I didn't quite understand it yet, but if I set `max_untracked_memory` to a lower value the problem doesn't reproduce.

**Comment by filimonov** [comment]
Update: that seems to be unrelated to async_inserts (when they are disabled it's the same)
