### ISSUE TITLE
How can build on CPU Arch mips64le?

### ISSUE THREAD

**Issue by bj1116** [ClickHouse/ClickHouse#55897]
How can build on CPU Arch mips64le or loongarch64 ?

**Comment by alexey-milovidov** [comment]
MIPS is not officially supported, so you are on your own.
Although it should be easy to add, and I would appreciate it if there would be a pull request.

**Comment by alexey-milovidov** [comment]
You can ship a MIPS server to the address of the company's office: Herengracht 576, 1017 CJ Amsterdam

**Comment by wynemo** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/1314428/aadca6b7-6eee-41fe-b8f4-898ad62bb013)
I have built it successfully on mips64le with tag `v23.3.9.55-lts` with some code changes.  I may open a PR later.

```
root@usm:~/ClickHouse# uname -a
Linux usm.primary.10.113.58.151 4.19.0-loongson-3-server #20211013 SMP PREEMPT Uos 4.19.0-eagle Wed Oct 13 15:36:26 CST 2 mips64 GNU/Linux
root@usm:~/ClickHouse# clang --version
clang version 16.0.6 (https://github.com/llvm/llvm-project.git 7cbf1a2591520c2491aa35339f227775f4d3adf6)
Target: mips64el-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
root@usm:~/ClickHouse# cmake --version
cmake version 3.28.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
root@usm:~/ClickHouse# ninja --version
1.8.2

```

**Comment by alexey-milovidov** [comment]
@wynemo, thank you! Looking forward to a pull request. We can add it to the CI.
