### ISSUE TITLE
How to convert SQL statements that work correctly in MySQL to SQL statements that will also work correctly in ClickHouse?

### ISSUE THREAD

**Issue by vkditcbbjkg77114** [ClickHouse/ClickHouse#55896]
I really like ClickHouse, so I decided to migrate some of MySQL's features to ClickHouse. However, during this process, I encountered some issues, such as lack of support for recursive queries and variable assignment.
For example, I have a table:
```sql
create table file
(
id Int64,
name String,
parent_id Int64
) ENGINE MergeTree() order by id;
```
In MySQL, I can use a CTE or the following SQL to retrieve all child files and directories under the directory with id 6:
```sql
SELECT id, `name`
FROM (SELECT id, parent_id, `name` FROM file where parent_id != 0) a,
(SELECT @pv := 6) b
WHERE (FIND_IN_SET(parent_id, @pv) != 0 AND @pv := concat(@pv, ',', id))
```
Can ClickHouse achieve this type of recursive SQL, or are there plans to implement it? ClickHouse is excellent, but this is the reason preventing me from migrating to ClickHouse.

Thanks !

**Comment by lampjian** [comment]
No. Clickhouse have not implementing recursive query now. You can use a mysql table engine with the recursive query view or just do it in your application.

**Comment by rschu1ze** [comment]
I think recursive CTEs are supported by now: https://clickhouse.com/docs/en/sql-reference/statements/select/with#recursive-queries . Please try again with a recent ClickHouse version.
