### ISSUE TITLE
Distributed Table System issue 

### ISSUE THREAD

**Issue by I-akshay** [ClickHouse/ClickHouse#5589]
1)Distributed Table System:- 
a)Let's say I have a cluster of 3 Server(A, B, C) where A is master/main server now I have created a table with engine=Distributed
in Server A, but the issue is I have to create a blank table structure manually on all other servers.
Because if a blank structure is not present in other servers(B,C) then it is giving me connection error/table not exist errors when I try to retrieve data (SELECT statement)

b)Let's say I create a distributed table on server A there is no control in my hand how much proportion of data I want to 
distribute in remaining two servers (B, C) because by default it is distributing in 50%-50% proportion 

At last thanks for bearing with me :)

**Comment by den-crane** [comment]
3 shards or 3 replicas?

3 shards ? A=30% of data , B=30% , C=30%
3 replicas? A=100% of data === B=100%  === C=100%

**Comment by I-akshay** [comment]
> 3 shards or 3 replicas?
> 
> 3 shards ? A=30% of data , B=30% , C=30%
> 3 replicas? A=100% of data === B=100% === C=100%

There are 3 shards

**Comment by filimonov** [comment]
a) just create tables clusterwise using ON CLUSTER clause and you will have no such problems
b) you can either insert into distributed table which has an sharding key controlling where to put the data (you can use random() to distrinute data equally). Or you can insert directly to underlying tables (usually mergetree family). 

Please read that: https://github.com/yandex/ClickHouse/issues/2161#issuecomment-378197593

**Comment by blinkov** [comment]
@I-akshay, do you have any further questions?
