### ISSUE TITLE
What SETTINGS are supported by the s3 engine table?

### ISSUE THREAD

**Issue by FengZh61** [ClickHouse/ClickHouse#55919]
https://clickhouse.com/docs/en/integrations/s3
I read in the official documentation that the S3 engine table supports SETTINGS, but I didn't find out exactly what parameters are supported, is there any specific documentation on the official website?

**Comment by den-crane** [comment]
any settings.

Full list you can get using `select * from system.settings;`

The documentation provides an examples 

    _Specify the setting s3_create_new_file_on_insert=1. This will cause the creation of new files on each insert. A numeric suffix will be appended to the end of each file that will monotonically increase for each insert operation. For the above example, a subsequent insert would cause the creation of a trips_1.bin file.
    Specify the setting s3_truncate_on_insert=1. This will cause a truncation of the file, i.e. it will only contain the newly inserted rows once complete._
