### ISSUE TITLE
S3 engine table count() stats error!

### ISSUE THREAD

**Issue by FengZh61** [ClickHouse/ClickHouse#55918]
I store files in minio, using the parquet file format, and the data actually exists in more than 5,000 play rows, but when I execute count(), the statistics are wrong, and the values change frequently, sometimes by millions, sometimes by more than 20 million, etc. What is the problem?

**Comment by den-crane** [comment]
Please provide a reproducible example.

**Comment by den-crane** [comment]
What version do use? `select version()` ?

**Comment by FengZh61** [comment]
> What version do use? `select version()` ?

23.8.3.48

**Comment by Avogar** [comment]
Try to disable `optimize_count_from_files` and check if it helps

**Comment by FengZh61** [comment]
> Please provide a reproducible example.

It seems to be an issue with the connection tool, I checked in CH Client and the results are correct, I will keep watching to see if it reproduces. I am very sorry that this is not a CH issue.

**Comment by FengZh61** [comment]
> Try to disable `optimize_count_from_files` and check if it helps

It seems to be an issue with the connection tool, I checked in CH Client and the results are correct, I will keep watching to see if it reproduces. I am very sorry that this is not a CH issue.

**Comment by FengZh61** [comment]
> Try to disable `optimize_count_from_files` and check if it helps

![image](https://github.com/ClickHouse/ClickHouse/assets/98309003/26cd50e5-5ec4-45fd-b04d-1b62ef4b6f8e)

I noticed the incorrect counting again today when I was querying, after setting ```optimize_count_from_files=0```, the count was correct.

**Comment by Avogar** [comment]
Most probably incorrect count was cached when you had problems with the connection tool. Run `SYSTEM DROP SCHEMA CACHE FOR S3`

**Comment by FengZh61** [comment]
> Most probably incorrect count was cached from parquet metadata when you had problems with the connection tool. Run `SYSTEM DROP SCHEMA CACHE FOR S3`

Whether I use the connection tool or the CH client, the query is having problems, right now I'm getting correct results with both, I'll continue to watch and when the wrong count data comes up, execute ```SYSTEM DROP SCHEMA CACHE FOR S3``` and then execute count() to see the results returned.

**Comment by FengZh61** [comment]
> Most probably incorrect count was cached from parquet metadata when you had problems with the connection tool. Run `SYSTEM DROP SCHEMA CACHE FOR S3`

![image](https://github.com/ClickHouse/ClickHouse/assets/98309003/ec60478d-9abd-4129-81ea-f99e1f9b2c1d)

After executing the command, you can count the correct data to be returned.

**Comment by Avogar** [comment]
So yes, incorrect count was cached (you can disable this cache by disabling setting `use_cache_for_count_from_files`).
The questions is, why and when we had incorrect count that was cached.
If you have this problem again, we can see the content of the cache before dropping it, so we can see what files were cached and when. To do it you can use query `select * from system.schema_inference_cache where source='S3' format Vertical`

**Comment by den-crane** [comment]
@FengZh61 do you change parquet files? Append data to them?

**Comment by FengZh61** [comment]
> @FengZh61 do you change parquet files? Append data to them?

Data is written in bulk, first to small files, then periodically the small files are merged into larger ones.

**Comment by FengZh61** [comment]
> So yes, incorrect count was cached (you can disable this cache by disabling setting `use_cache_for_count_from_files`). The questions is, why and when we had incorrect count that was cached. If you have this problem again, we can see the content of the cache before dropping it, so we can see what files were cached and when. To do it you can use query `select * from system.schema_inference_cache where source='S3' format Vertical`

Yes!
I'm not adding my files in a completely positive way, merging large files into smaller ones, and I've looked at S3's cache in schema_inference_cache, and the information in the parquet file isn't equal to what's in my object store.

**Comment by Avogar** [comment]
> the information in the parquet file isn't equal to what's in my object store.

So, there are files in cache with number of rows not equal to the actual number of rows for this object in s3?
Schema inference cache should track last modification time of an object and if it was changed after schema was added to cache, we shouldn't use it and delete from cache.
So, maybe there is a bug in this logic and for some reason we use cached number of rows for objects that were changed.
Maybe you can find a file in cache with incorrect number of rows in `schema_inference_cache `, check it's registration time, compare it with last modification time of an object in s3 and check if count from this particular file returns cached value instead of running count on new data.

**Comment by Avogar** [comment]
It's ok if some files are missing in cache, for files that are not in cache we will count from the file metadata in s3. So, I don't see how cache can result in incorrect count in your case

**Comment by FengZh61** [comment]
> It's ok if some files are missing in cache, for files that are not in cache we will count from the file metadata in s3. So, I don't see how cache can result in incorrect count in your case

I've been busy with other things lately, so after a while, I'll double-check and I'll give feedback.

**Comment by FengZh61** [comment]
> It's ok if some files are missing in cache, for files that are not in cache we will count from the file metadata in s3. So, I don't see how cache can result in incorrect count in your case

I am having a problem with counting errors with the S3 engine table, not that the cache is causing the counting errors.
I checked the issue again, when the count is not accurate, I check the cache information in the ```schema_inference_cache``` table, the value of number_of_rows is equal to the number of file rows in the object store, I think that part is not using the error, at this time, the result of count() is close to the result of adding the value of number_of_rows in ```schema_inference_cache ```The result of count() at this point is close to the result of adding the value of number_of_rows in cache, you mentioned that for files that are not in cache, the counting will be done from the file metadata in s3, I don't think CH did not do this step or there was an exception while doing this step, above is my opinion, welcome to discuss.
