### ISSUE TITLE
LowCardinality is not documented

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#5591]
I checked docs on LowCardinality but cannot find any except some mentions in changelog. So I'm creating this issue to keep track of it.

**Comment by jelharou** [comment]
The Altinity blog is a great place to start:  https://www.altinity.com/blog/2019/3/27/low-cardinality

**Comment by simPod** [comment]
Thanks for the link, already found this one and some others. But documented, it should be ;) I from discussions I found here I understand it's production ready.

**Comment by blind-oracle** [comment]
> From discussions I found here I understand it's production ready.

I wouldn't be so sure.

In some queries (like `SELECT ... FROM ... WHERE low_card_column IN (...a lot of strings...)` I found it to be 100s times slower than normal `String`. I've checked in CH 19.5, maybe it has improved, but I wouldn't count on it.

**Comment by blinkov** [comment]
@simPod, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@BayoNet I cannot find LowCardinality in documentation.
LowCardinality feature is used in production since long time ago.

**Comment by BayoNet** [comment]
Ok. I'll do it ASAP.

**Comment by robot-clickhouse** [comment]
@simPod, do you have any further questions?

**Comment by simPod** [comment]
https://clickhouse.tech/docs/en/sql-reference/data-types/lowcardinality/
