### ISSUE TITLE
When I use S3 or HDFS as clickhouse's storage method, will clickhouse's MergeTree table engine automatically help me complete the MergePart work in the background?

### ISSUE THREAD

**Issue by FriskKiddo** [ClickHouse/ClickHouse#55928]
When I used S3 or HDFS as the storage method of clickhouse,  through the S3 or HDFS console I found that clickhouse created a large number of objects. This number was astonishing and even reached the upper limit of files created in a single folder of HDFS. So I suspect that after using S3 or HDFS as clickhouse's storage method, clickhouse's MergeTree table engine will not assist me in performing the MergePart task.

**Comment by den-crane** [comment]
HDFS as Disk is not production ready. It's a known issue https://github.com/ClickHouse/ClickHouse/issues/43112

**Comment by den-crane** [comment]
S3 is production ready. Merges are fine. Files are sharded to subfolders.
