### ISSUE TITLE
Introduce lzo compression in CH

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#55924]
> (you don't have to strictly follow this form)

**Use case**
lzo compression method is widely used in ORC/Parquet formats.

**Comment by taiyang-li** [comment]
First we need to plant https://github.com/nemequ/lzo to CH contrib.

**Comment by alexey-milovidov** [comment]
LZO is one of the first and the oldest in the family of fast LZ77 compressors. It is widely respected but currently does not make sense in comparison with LZ4. People use it by inertia, or because they don't know alternatives.

**Comment by Algunenano** [comment]
Also, LZO implementations are GPL.
