### ISSUE TITLE
Expose number of centroids or number of samples in T-Digest or other sketches

### ISSUE THREAD

**Issue by yalon** [ClickHouse/ClickHouse#55925]
**Use case**

When aggregating TDIgest data and doing gap fills, I'd like to be able to tell the difference between zeros and no data.

**Describe the solution you'd like**

For lack of a better idea, I'd like to surround a quantileTDigest() call with an `if` that will first check if the aggregated TDigest is empty or not and hopefully not incur a performance penalty of aggregating TDigest twice - once for the if() condition and another for one of the branches.

**Describe alternatives you've considered**

We can't use Nullable for TDigest state columns since aggregating TDIgest states don't return Nulls so we're left w/ an empty TDigest state. The only alternative is to do "heuristics" and consider zero as "null".

**Additional context**

With TDigest and other sketches, it's common to request some sketch "metadata" like min/max/count (or approximations of).

**Comment by UnamedRus** [comment]
> I'd like to be able to tell the difference between zeros and no data.

But it's already different states

```
SELECT
    length(hex(quantileTDigestState(0))) AS result_zeros,
    length(hex(quantileTDigestStateIf(0, 0))) AS result_no_data
FROM numbers(10)

Query id: 843e936f-1daf-46ad-b573-49cb855865b6

┌─result_zeros─┬─result_no_data─┐
│          162 │              2 │
└──────────────┴────────────────┘
```

**Comment by yalon** [comment]
Thanks @UnamedRus ! that's good enough.

**Comment by UnamedRus** [comment]
BTW, somewhat unrelated but you can read state of function as follows. 

https://kb.altinity.com/altinity-kb-functions/how-to-encode-decode-quantiletdigest-state/
