### ISSUE TITLE
DB::Exception: Cannot read all data.Bytes read: 861993. Bytes expected: 10010058

### ISSUE THREAD

**Issue by yedelong** [ClickHouse/ClickHouse#55932]
When a program inserts a batch of data into a cluster, it will frequently encounter 'cannot read all data' errors. How can I solve this problem?
The cluster I am using is three shards and two replicas。
![微信图片_20231023175110](https://github.com/ClickHouse/ClickHouse/assets/75054677/643cff22-1d0e-42a5-8486-63a1b7900ef0)
![微信图片_20231023174952](https://github.com/ClickHouse/ClickHouse/assets/75054677/bce9815e-a193-4abd-bc12-4f62c9a81a09)

**Comment by den-crane** [comment]
22.5 is out of support. Upgrade to 23.9.2.

**Comment by den-crane** [comment]
It seems like the problem is in the client. It sent incomplete/cut input stream.

**Comment by yedelong** [comment]
> 22.5 is out of support. Upgrade to 23.9.2.

May I ask if upgrading the version to the latest version can solve this problem?

**Comment by yedelong** [comment]
> > May I ask if upgrading the version to the latest version can solve this problem?
> 
> I don't know. You should test it in your stage environment.

Ok, thank you
