### ISSUE TITLE
interval comparison apparently ignore units

### ISSUE THREAD

**Issue by samuelcolvin** [ClickHouse/ClickHouse#55942]
Comparison of intervals appear to ignore units, and just compare the numeric values.

Here's what happens (clearly 1 microsecond is not equal to 1 second, and similarly 100us is not greater than 1 second).

```

df3efe7565e7 :) select toIntervalMicrosecond(1) = toIntervalSecond(1)

SELECT toIntervalMicrosecond(1) = toIntervalSecond(1)

Query id: 49f6631d-92c2-42c8-9b2f-99c40b3fae8f

┌─equals(toIntervalMicrosecond(1), toIntervalSecond(1))─┐
│                                                     1 │
└───────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.004 sec. 

df3efe7565e7 :) select toIntervalMicrosecond(100) > toIntervalSecond(1)

SELECT toIntervalMicrosecond(100) > toIntervalSecond(1)

Query id: a4ccf74f-e04c-4ef2-b6c8-6c22002b48aa

┌─greater(toIntervalMicrosecond(100), toIntervalSecond(1))─┐
│                                                        1 │
└──────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

df3efe7565e7 :) select version()

SELECT version()

Query id: 17b10304-ea34-4f8e-9223-788c7d4a4df6

┌─version()───┐
│ 23.8.1.2992 │
└─────────────┘

1 row in set. Elapsed: 0.003 sec. 
```

https://fiddle.clickhouse.com/19443d43-8d8d-4d27-adf9-33a02ec1d6cf

**Comment by samuelcolvin** [comment]
Thanks @melvynator.

As mentioned by @cwurm via email, at the very least an error should be raised if you compare intervals with different units.

But to be clear, our SQL translation logic would be a great deal cleaner if different units were correctly supported across comparison.

**Comment by melvynator** [comment]
Yes, probably an error message when different units are used is the solution. Ideally, automatically converts to a specific unit.

**Comment by alexey-milovidov** [comment]
It is not possible to compare intervals of different types. For example, `INTERVAL 1 MONTH` and `INTERVAL 30 DAY`, or `INTERVAL 1 DAY` and `INTERVAL 24 HOUR`. It should throw an exception.

Currently, it compares the underlying numeric representation of intervals.

**Comment by tbragin** [comment]
Please also note that we recently decided to perform some of these conversions between intervals transparently. More details in this issue: https://github.com/ClickHouse/ClickHouse/issues/64748
