### ISSUE TITLE
There is a big difference in query speed between S3 engine tables and MergeTree tables

### ISSUE THREAD

**Issue by FengZh61** [ClickHouse/ClickHouse#55958]
The data is stored in minio and MergeTree tables, there are 80 million rows, execute select * from {table} where timestamp>{time_a} and where timestamp<{time_b} limit 10, the MergeTree table takes several tens of milliseconds, but using S3 engine table to read, it takes 3-5 seconds, is there any way to optimize the query speed? Is there any way to optimize the query speed? Or is the minio used limiting the query speed?

This is the sql to create the table

MergeTree Table

```sql
 CREATE TABLE logs.es
(

    `log_timestamp` DateTime('Asia/Shanghai'),

    `message` String,

    `source` String,

    `log_devicename` String,

    `log_bussiness_alias` String,

    INDEX inv_idx message TYPE inverted GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(log_timestamp)
ORDER BY log_timestamp
TTL toDateTime(log_timestamp) + toIntervalMonth(7)
SETTINGS index_granularity = 8192;
```

S3 Engine Table

```sql
CREATE TABLE logs.demo1
(

    `log_timestamp` DateTime('Asia/Shanghai'),

    `message` Nullable(String),

    `source` Nullable(String),

    `log_devicename` Nullable(String),

    `log_bussiness_alias` Nullable(String)
)
ENGINE = S3('http://{ip}:{port}/mydev/files/default/logs/vector/*/*/*/*/*.parquet',
 'minioadmin',
 'minioadmin')
PARTITION BY toYYYYMMDD(log_timestamp)
PRIMARY KEY log_timestamp;


```

**Comment by den-crane** [comment]
ENGINE = MergeTree <> ENGINE = S3

Queries against Parquet files are expected to be MUCH slower.

**Comment by den-crane** [comment]
you can put MergeTree on minio and check performance https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-s3-object-storage/s3_cache_example/
