### ISSUE TITLE
Cannot find columns within expression when using window function + limit by

### ISSUE THREAD

**Issue by priera** [ClickHouse/ClickHouse#55965]
The following query works in 22.8 but not in 23.8. Computing arithmetic expressions between columns doesn't seem to work when using window functions in combination with `LIMIT BY`

```
CREATE TABLE error_win_func
(
    `k` String,
    `in` UInt64,
    `out` UInt64
) 
ENGINE = MergeTree
ORDER BY k;

INSERT INTO error_win_func VALUES ('a', 2, 4), ('a', 4, 2), ('a', 6, 3), ('a', 8, 4);

SELECT
    k,
    in / out AS ratio,
    count(*) OVER w AS count_rows_w    
FROM error_win_func
WINDOW
    w AS (ROWS BETWEEN CURRENT ROW AND 3 FOLLOWING)
LIMIT 1 BY
    k;
```

Reports the following error: `Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column in in block k String String(size = 0), divide(in, out) Float64 Float64(size = 0), count() OVER w UInt64 UInt64(size = 0). (NOT_FOUND_COLUMN_IN_BLOCK)`

Replacing `in / out AS ratio,` with just one of the two columns works fine. The query also works when removing the `LIMIT` clause. I would like to confirm this is a regression.

[Fiddle](https://fiddle.clickhouse.com/a9e73243-8890-4da1-aed7-4145066359ee)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/47217
