### ISSUE TITLE
build error in FedoraOS37

### ISSUE THREAD

**Issue by gaowayne** [ClickHouse/ClickHouse#55984]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**
FedoraOS37

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
```
[root@cassiopeia ClickHouse]# uname -a
Linux cassiopeia 6.4.12-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 23 17:49:27 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
[root@cassiopeia ClickHouse]# 
```
**Cmake version**
```
[root@cassiopeia ClickHouse]# cmake --version
cmake version 3.27.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@cassiopeia ClickHouse]# 
```

**Ninja version**

**Compiler name and version**

**Full cmake and/or ninja output**
```
-- Configuring incomplete, errors occurred!
[root@cassiopeia ClickHouse]# export CC=clang-17
[root@cassiopeia ClickHouse]# export CXX=clang++-17
[root@cassiopeia ClickHouse]# cmake -S . -B build
-- Using compiler:
clang version 15.0.7 (Fedora 15.0.7-2.fc37)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
CMake Error at cmake/tools.cmake:33 (message):
  Compilation with Clang version 15.0.7 is unsupported, the minimum required
  version is 16.
Call Stack (most recent call first):
  CMakeLists.txt:18 (include)


-- Configuring incomplete, errors occurred!
[root@cassiopeia ClickHouse]# yum install clang
Last metadata expiration check: 0:01:04 ago on Tue 24 Oct 2023 06:31:51 PM CEST.
Package clang-15.0.7-2.fc37.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@cassiopeia ClickHouse]# 
```

**Comment by Algunenano** [comment]
The error is quite clear and you've already seen it: As of today, you need clang 16 or above to build ClickHouse.

Seeing https://src.fedoraproject.org/rpms/clang it seems that you might need to upgrade to get it. It might also be possible to build it with older clang 15 and some tweaks, but you are on your own.
