### ISSUE TITLE
List of CTEs in IN clause not recognized when used in subquery

### ISSUE THREAD

**Issue by priera** [ClickHouse/ClickHouse#55981]
Issue happens in the latest CH version. When a subquery has an `IN` clause with a list of CTEs in the right hand side, these are not recognized and the query reports an error. 

```sql
CREATE TABLE subquery_cte_in
(
    `date` DateTime64(3),
    `id` UInt32
)
ENGINE = MergeTree
ORDER BY (id, date);

INSERT INTO subquery_cte_in VALUES (toDateTime('2023-10-24 16:13:38'), 6), (toDateTime('2023-10-24 16:00:00'), 10), (toDateTime('2023-10-24 00:00:00'), 6);

SELECT max(date_out)
FROM
(
    WITH
        (
            SELECT max(date)
            FROM subquery_cte_in 
            WHERE (id = 6)
        ) AS cte_1,
        (
            SELECT max(date)
            FROM subquery_cte_in 
            WHERE (id = 10)
        ) AS cte_2
    SELECT date AS date_out
    FROM subquery_cte_in
    WHERE date IN (cte_1, cte_2)
);
```

**Expected behavior**
The query should return a value

**Actual behavior**
Reports the following error: `Code: 36. DB::Exception: Received from clickhouse-01:29000. DB::Exception: Element of set in IN, VALUES, or LIMIT, or aggregate function parameter, or a table function argument is not a constant expression (result column not found): cte_1: While processing id IN (identity(_CAST('0', 'Nullable(DateTime64(3))')) AS cte_1, identity(_CAST('0', 'Nullable(DateTime64(3))')) AS cte_2). (BAD_ARGUMENTS)` [Fiddle](https://fiddle.clickhouse.com/9e4662d1-7391-42c9-b23b-04e5d8de93a7)

This only happens when running the IN clause in a subquery. Running the internal query in isolation works. Also, if just a single CTE is provided to the IN list the query also works.

**Comment by nickitat** [comment]
I cannot find a version when it worked. also tried to do smth similar in PG - also doesn't work.

**Comment by Algunenano** [comment]
It seems it was broken at some point around 23.2:

* Master: KO
* Master with the analyzer: OK

* 22.8: OK
* 22.10: OK
* 22.12: OK
* 23.1.2.9: OK
* 23.2: KO (OK with analyzer)
* 23.3: KO (OK with analyzer)

**Comment by SaltTan** [comment]
No exception in 24.3 https://fiddle.clickhouse.com/8aa65445-9f5f-42e0-873c-0a18c82cd613

**Comment by realyota** [comment]
Simple w/a:

```
SELECT max(date_out)
FROM
(
    WITH
        (
            SELECT max(date) cte_1
            FROM subquery_cte_in 
            WHERE (id = 6) AND (label = 2)
        ) AS cte_1,
        (
            SELECT max(date) cte_2
            FROM subquery_cte_in 
            WHERE (id = 10) AND (label = 2)
        ) AS cte_2
    SELECT date AS date_out
    FROM subquery_cte_in
    WHERE date IN (SELECT arrayJoin([cte_1, cte_2]))
)
```
