### ISSUE TITLE
Does query cache support subquery results caching

### ISSUE THREAD

**Issue by Abdallahj94** [ClickHouse/ClickHouse#56008]
Does clickhouse query cache support caching subquery results? I see it's mentioned here https://github.com/ClickHouse/ClickHouse/issues/34011 but still unchecked, has it been implemented somewhere else? and if not are there any plans to add it in the future?

We're planning on using query cache to cache complex query results and our queries contain subqueries as well, some of these subqueries are shared between different queries and we want to know if it's possible to cache the subquery results between those different queries instead of executing them each time

**Comment by Algunenano** [comment]
Currently not implemented. See https://github.com/ClickHouse/ClickHouse/issues/51656
