### ISSUE TITLE
compile tag branch doubt

### ISSUE THREAD

**Issue by guoxiaolongzte** [ClickHouse/ClickHouse#56001]
https://clickhouse.com/docs/en/development/developer-instruction

If I want to compile this tag with branch v23.3.14.78-lts, If I want to compile this tag, can I use the following command next week?
git clone --**branch v23.3.14.78-lts** **--recursive** **--shallow-submodules**  https://github.com/ClickHouse/ClickHouse.git

I am very concerned about whether my sub modules are correct!

**Comment by cangyin** [comment]
With this command to check submodule status:

```
$ git submodule status
 818c2d8ad96a08a5d20fece7d1e1e8855a2b0860 contrib/AMQP-CPP (v4.1.4-240-g818c2d8)
 b56784be1aec568fb72aff47f281097c017623cb contrib/NuRaft (v1.1.2-238-gb56784b)
 215105818dfde3174fe799600bb0f3cae233d0bf contrib/abseil-cpp (20211102.0)
 f2ac8e7b48f9a9cf676d3b58286e5455aba8e956 contrib/annoy (v1.17.0-69-gf2ac8e7)
 d03245f801f798c63ee9a7d2b8914a9e5c5cd666 contrib/arrow (apache-arrow-1.0.0-3038-gd03245f80)
 7832659ec986075d560f930c288e973c64679552 contrib/avro (heads/master)
 ecccfc026a42b30023289410a67024d561f4bf3e contrib/aws (1.6.0-1783-gecccfc026a)
 30df6c407e2df43bd244e2c34c9b4a4b87372bfb contrib/aws-c-auth (v0.6.19)
 85dd7664b786a389c6fb1a6f031ab4bb2282133d contrib/aws-c-cal (heads/master)
 324fd1d973ccb25c813aa747bf1759cfde5121c5 contrib/aws-c-common (v0.2.1-546-g324fd1d)
 b517b7decd0dac30be2162f5186c250221c53aff contrib/aws-c-compression (v0.2.16)
 39bfa94a14b7126bf0c1330286ef8db452d87e66 contrib/aws-c-event-stream (v0.1.1-59-g39bfa94)
 2c5a2a7d5556600b9782ffa6c9d7e09964df1abc contrib/aws-c-http (v0.6.25)
 5d32c453560d0823df521a686bf7fbacde7f9be3 contrib/aws-c-io (5d32c45)
 ......(more content omitted)
```

If there is no '+' or '-' prefix before each commit SHA, that means submodule status are clean and corresponds to parent repo (ClickHouse) status.


See git [doc](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-status--cached--recursive--ltpathgt82308203).
