### ISSUE TITLE
Faster windowFunnel

### ISSUE THREAD

**Issue by mrAndersen** [ClickHouse/ClickHouse#56016]
```
SELECT
    level,
    count() c
FROM
    (SELECT
         uuid                          identity,
         windowFunnel(86400, 'strict_increase')(datetime, event = 1, event = 2, event = 3) AS level
     FROM
         default.event_distributed
     WHERE
         condition1 = 1
         and date = today()
     GROUP BY identity)
GROUP BY
    level
ORDER BY
    level ASC;
```

Hi! I have following query, which is basically very similar to how funnels are used in documentation. So the more dates I am about to select in subquery, the longer query will run. The question is, can this query be optimized somehow to run faster with some simple techniques?

**Comment by kotik** [comment]
@mrAndersen Hey did you check if the `windowFunnel` is slow or if the underlying query that streams data to `windowFunnel` is slow?
From my experience, the whole thing gets faster if I filter out all unnecessary rows in the `WHERE` clause. Events included.
Needless to say ORDER BY in the table definition must correspond to your `WHERE` clause.
