### ISSUE TITLE
Invalidate query cache results

### ISSUE THREAD

**Issue by Abdallahj94** [ClickHouse/ClickHouse#56012]
Is there a way to invalidate a single query cache result when using query caching?
As mentioned here https://github.com/ClickHouse/ClickHouse/pull/43797 we can use "SYSTEM DROP QUERY CACHE" to clear the whole query result cache, but we need the ability to clear(or re-run) a single query result from cache.

we're adding `SETTINGS use_query_cache = true` with fixed ttl to the queries we want to cache the results for, but we also need the ability to hard refresh(re-run) the query manually when needed and re-populate the cache

**Comment by rschu1ze** [comment]
Same as https://github.com/ClickHouse/ClickHouse/issues/59417
