### ISSUE TITLE
Linker costs a lot of time and memory for RelWithDebInfo build type

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#56018]
Linker costs a lot of time and memory for build type 'RelWithDebInfo'. Please check the attached screenshots.

**Operating system**
Linux Ubuntu 20.04.6 LTS

**Cmake version**
3.25.3

**Ninja version**
1.10.0

**Compiler name and version**
clang-15, clang++-15

**Full cmake and/or ninja output**

<img width="359" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/1518453/9577d9dd-b8ff-46e0-aca3-932741829302">

<img width="978" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/1518453/a05ef15f-0ab1-40ce-ab38-b842c35dff33">

**Comment by tavplubix** [comment]
> Linker costs a lot of time and memory

How much exactly? We use Thin LTO, so it may be expected.

> clang-15, clang++-15

clang-15 is not supported, we use use clang-17

> Please check the attached screenshots.

Please attach text instead of screenshots.

**Comment by Alex-Cheng** [comment]
The output of clang is simple:
```
[0/2] Re-checking globbed directories...
[55/57] Linking CXX executable programs/clickhouse
```
Then it taks long time to complete.

Does upgrading to clang-17 help?

**Comment by Alex-Cheng** [comment]
Please take a look at the issue again, because it impact the work productivity.

**Comment by Algunenano** [comment]
> The output of clang is simple:

That's the output of ninja. You can add -v to see the commands being executed.

> Please take a look at the issue again, because it impact the work productivity.

Again, how much time it takes and how much would you expect it to take? It's a linker generating an optimized multigigabyte binary. If you want faster link times you can try using something like [mold](https://github.com/rui314/mold) and deal with the setup and issues that will come with it. It used to be possible to build CH with dynamic libraries (much faster link time) but that produced quite a bit of build errors that nobody wanted to expend time looking into. See https://github.com/ClickHouse/ClickHouse/pull/44828#issuecomment-1370799719
