### ISSUE TITLE
 DB::Exception: Negative temporary data size: While executing DelayedJoinedBlocksWorkerTransform

### ISSUE THREAD

**Issue by Aaaaaaron** [ClickHouse/ClickHouse#56032]
we use grace hash join and sometimes occurs this error: 
<img width="1033" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/15643702/94a62216-4f6e-42df-b767-0dbb00490471">

after the debug, we found std::atomic needs default initialize, or it's a ub

https://stackoverflow.com/questions/59099401/why-does-default-constructor-of-stdatomic-not-default-initialize-the-underlyin

<img width="427" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/15643702/26e7a5de-98e1-4832-b7da-3387a9e5ddc3">

**Comment by Aaaaaaron** [comment]
https://github.com/ClickHouse/ClickHouse/pull/56034

**Comment by alexey-milovidov** [comment]
The conclusion is incorrect.
Moreover, you are using version 21.8, which is more than two years old.

**Comment by alexey-milovidov** [comment]
And the most significant offense - you are using an unofficial build.
