### ISSUE TITLE
how AggregateFunction (quantities (0.9, 0.95, 0.99) is implemented? Will there be any errors in the results, and will it take up more memory space?

### ISSUE THREAD

**Issue by yuwei43** [ClickHouse/ClickHouse#56065]
Excuse me, I would like to know how AggregateFunction (quantities (0.9, 0.95, 0.99) is implemented, saving all values in one result set? Will there be any errors in the results, and will it take up more memory space?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/quantile

This function applies [reservoir sampling](https://en.wikipedia.org/wiki/Reservoir_sampling) with a reservoir size up to 8192 and a random number generator for sampling. The result is non-deterministic. To get an exact quantile, use the [quantileExact](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/quantileexact#quantileexact) function.

**Comment by den-crane** [comment]
But quantilesExact stores the original data.

```
select length(hex(quantilesExactState(0.9, 0.95, 0.99)(number))) from numbers(1e8);
--
1600000008

select formatReadableSize(1600000008/2);
┌─formatReadableSize(divide(1600000008, 2))─┐
│ 762.94 MiB                                │
└───────────────────────────────────────────┘
```

**Comment by yuwei43** [comment]
> https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/quantile
> 
> This function applies [reservoir sampling](https://en.wikipedia.org/wiki/Reservoir_sampling) with a reservoir size up to 8192 and a random number generator for sampling. The result is non-deterministic. To get an exact quantile, use the [quantileExact](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/quantileexact#quantileexact) function.

---------------
Thanks!, but I still have a small question: If I use AggregatingMergeTree to aggregate query, will each data store 64kb of data? For example, the following statement:
CREATE TABLE pupuolap.pre_owl_entry_analysis_shard ON CLUSTER pupuolap
(
    `service` String,
    `avgQuantiles` AggregateFunction(quantiles(0.9, 0.95, 0.99), UInt64),
......
)
......
Result：
service ｜ avgQuantiles
aaa | [xxxx]
bbb | [xxx]
ccc | [xxx]

Is this to store 64kb * 3 of data？

**Comment by den-crane** [comment]
>Is this to store 64kb * 3 of data？

Right. It will store 64kb * 3.

That's why all other users use `quantilesTDigest`, it stores less than 1.5KB

`avgQuantiles AggregateFunction(quantilesTDigest(0.9, 0.95, 0.99), UInt64),`

https://gist.github.com/den-crane/c4d85bf11035f0844c8bbf6ae191fa22

**Comment by yuwei43** [comment]
> > Is this to store 64kb * 3 of data？
> 
> Right. It will store 64kb * 3.
> 
> That's why all other users use `quantilesTDigest`, it stores less than 1.5KB
> 
> `avgQuantiles AggregateFunction(quantilesTDigest(0.9, 0.95, 0.99), UInt64),`
> 
> https://gist.github.com/den-crane/c4d85bf11035f0844c8bbf6ae191fa22

---------
Thank you, and I would also like to ask if it is the AggregateFunction (avg) - latency of AggregatingMergeTree. Would it save each latency  data of the aggregation? I don't think there is any relevant explanation on the document,

**Comment by den-crane** [comment]
> AggregateFunction (avg) - latency of AggregatingMergeTree

it stores `sum & count`
