### ISSUE TITLE
Multiple arrayJoin functions generate empty results

### ISSUE THREAD

**Issue by AllenADS** [ClickHouse/ClickHouse#56068]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
when select multiple arrayJoin columns when there is empty arrays result will be empty.

**How to reproduce**
CREATE TABLE default.test_array_join
(
    `a` Array(Int32),
    `b` Array(Int32),
    `id` Int32
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192;
insert into test_array_join values ([], [1,2,3], 1);
insert into test_array_join values ([1,2,3], [], 1);

sql 1: 
SELECT
    arrayJoin(a) AS ja,
    arrayJoin(b) AS jb
FROM test_array_join

empty result

sql 2:
SELECT arrayJoin(b) AS jb
FROM test_array_join

Query id: f2d01be8-1590-4a08-94a9-b9178d456a41

result:
┌─jb─┐
│  1 │
│  2 │
│  3 │

**Expected behavior**
multiple array join should act as cross join event if there is empty array.

please help to check where above behavior is as expected

**Comment by den-crane** [comment]
Why multiple?

Single as well 

```
select arrayJoin([]::Array(String)), 'x';
0 rows in set. Elapsed: 0.004 sec.
```

it's expected behaviour. See https://github.com/ClickHouse/ClickHouse/issues/3954

Workaround  emptyArrayToSingle https://fiddle.clickhouse.com/84451d6a-e0de-4528-bfb3-8abc259bcba8

**Comment by den-crane** [comment]
Or may be you wanted array join https://fiddle.clickhouse.com/66c6bb8a-8b9e-44c0-8bd7-0560bb6d3e36

**Comment by AllenADS** [comment]
Got it! Thanks. emptyArrayToSingle function  is what I want.
