### ISSUE TITLE
Clickhouse access to S3 for storing data using IAM role through serviceaccount(Without using access_key_id and secret_access_key)

### ISSUE THREAD

**Issue by Ragavendra-Vigneshwaran-R** [ClickHouse/ClickHouse#56077]
Let assume I have a clickhouse cluster with 3 shards and 2 replicas in my eks cluster. I want to store clickhouse data in S3 without giving my access_key_id and secret_access_key. I want the clickhouse to access S3 using IAM role through serviceaccount to store data. Is it possible? If yes, please give me a sample storage configuration.

**Comment by den-crane** [comment]
it should work by default Clickhouse supports access S3 using IAM role see use_environment_credentials https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#endpoint-settings


Clickhouse does not support STS Assume Roles (AWS Security Token Service)

**Comment by Ragavendra-Vigneshwaran-R** [comment]
Thanks @den-crane for you response. Tried it out and it's worked 👍 :)
