### ISSUE TITLE
ZSTD codec compression with higher levels

### ISSUE THREAD

**Issue by AkhtemWays** [ClickHouse/ClickHouse#56076]
I insert into Clickhouse 25mln rows. There are all types of columns present in the table, and for each of them I use codec compression of ZSTD(4). Once insertion process is done, I see that there are fewer rows in the table than in the source. I tried to do the same backfill with ZSTD(1) codec, and it worked fine. Couldn't find any info about losing data by specifying higher level of ZSTD codec, and to me this seems a little weird.

**Comment by Algunenano** [comment]
Different compression level should no lead to less rows being ingested.

Please check CH version, table definition and logs of the inserts to see if there were any errors. Without a reproducer or some information there isn't a lot anybody can do to investigate.
