### ISSUE TITLE
How is the merged data replicated

### ISSUE THREAD

**Issue by shmily1227** [ClickHouse/ClickHouse#56096]
- Clickhouse version:20.8.3.18
- Table Engine:ReplicatedMergeTree
- note:Using Zookeeper to store basic table information
- Question: There are two nodes in the old cluster and no newly inserted data, and the data has been merged. At this point, I have expanded two nodes and I would like to know how the newly expanded two nodes replicate data from the old nodes。What is the interaction between them and between them and zookeeper.Is the data copying process the same as the copying process after newly inserted data before expansion?

**Comment by den-crane** [comment]
ReplicatedMergeTree engine replicates parts not inserts. If there is no source parts (insterted), then it replicates merged part.
ReplicatedMergeTree stores metadata in the zookeeper. Newly added replica reads from the zookeeper the lists of parts of other replicas, and then fetches that parts directly from the other replicas.
