### ISSUE TITLE
deduplicate by doesn't work with projections

### ISSUE THREAD

**Issue by DenisGee** [ClickHouse/ClickHouse#56097]
Hello everyone, we have a little problem with using projections
Didn't find the same issue here

**Describe the unexpected behaviour**
When I try to make optimize deduplicate by ... on a table with a projection I get an error "Not found column <column> in block"

**How to reproduce**
ClickHouse server version 23.6.3.87
```
CREATE TABLE test.deduplication_test
(
	x Int8,
	y Int8,
	PROJECTION projection_visits_by_user
	(
		SELECT max(y)
	)
) ENGINE = MergeTree
ORDER BY x;

INSERT INTO test.deduplication_test
SELECT 1, 2
UNION ALL
SELECT 1, 2;

OPTIMIZE TABLE test.deduplication_test FINAL DEDUPLICATE BY x;
```

**Expected behavior**
Some settings to avoid deduplication in a projection

Is there a way to avoid this limitation for now?

**Comment by melvynator** [comment]
Seems to be a deduplicate of: https://github.com/ClickHouse/ClickHouse/issues/49790
