### ISSUE TITLE
How to figure out why CPU usage started 99%?

### ISSUE THREAD

**Issue by fridary** [ClickHouse/ClickHouse#56106]
* OS: Ubuntu 20.04.6 LTS
* ClickHouse: 23.7.2.25 (official build)
* Server: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz 72 processes 

1 month clickhouse was working perfect, I was adding data not more then ~10 new bulk inserts per second. Each bulk insert has ~50 inserts (rows). Now in 1 database and 1 table there are 55 millions of rows.
1 week ago I added new database with 1000 tables and total rows there are only some millions. I don't know if it related to the problem.
The problem is yesterday all the time it started to use 99% of all 36 cores. Sometimes it can slow down again back to use around 10% CPU usage only for some minutes, then go back to 80-99%. I don't know why. How can I figure out?

<img width="1370" alt="Снимок экрана 2023-10-29 в 08 13 46" src="https://github.com/ClickHouse/ClickHouse/assets/3791864/5dcd6f7e-37f1-440c-baaa-0b8c105c1c83">

Here is sum up of databases (`system` is main and 2 databases of mine):
<img width="805" alt="Снимок экрана 2023-10-29 в 08 28 02" src="https://github.com/ClickHouse/ClickHouse/assets/3791864/c94a5b5b-2650-4558-aec5-c63c42b6119a">

**Comment by den-crane** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/who-ate-my-cpu/

**Comment by rschu1ze** [comment]
Besides the good links @den-crane posted, you may also use `perf top` to get a "live" view of the current CPU utilization.

**Comment by fridary** [comment]
@den-crane it has been past 2 months, everything was okey, I did not program any new code for my application, and suddenly again clickhouse started to eat all my CPU just on the first screen of topics. I checked this link https://kb.altinity.com/altinity-kb-setup-and-maintenance/who-ate-my-cpu/ and here are results of quires:

<img width="783" alt="Снимок экрана 2023-12-21 в 09 47 31" src="https://github.com/ClickHouse/ClickHouse/assets/3791864/9ebb426b-4a4d-4344-b2ab-2a4d1d3f5601">
<img width="392" alt="Снимок экрана 2023-12-21 в 09 47 47" src="https://github.com/ClickHouse/ClickHouse/assets/3791864/89d19049-2021-4a63-9c91-3a0c3b89526f">
<img width="614" alt="Снимок экрана 2023-12-21 в 09 48 22" src="https://github.com/ClickHouse/ClickHouse/assets/3791864/f8a0a99a-3591-4a70-bba4-8e2625c9a7d3">
<img width="766" alt="Снимок экрана 2023-12-21 в 09 48 35" src="https://github.com/ClickHouse/ClickHouse/assets/3791864/6f313c91-508c-49e9-abd6-09727e873b0b">

Can you help me how to explain this? I see `asynchronous_metric_log` has estimate and elapsed big numbers, but what does it mean, how can I interpret this information to understand why clickhouse eats CPU and fix it?

Also I see these quieres take much time: `SELECT t1.datetime, ... FROM mytable t1 LEFT JOIN mytable2 t2 ON t1.uuid=t2.uuid WHERE t1.uuid='136a5f0b-5b5e-48bf-a92c-4e5dd39694a2' LIMIT 1`, but it is slow just because of high load clickhouse. Quire is written fine.

**Comment by den-crane** [comment]
@fridary No idea.
