### ISSUE TITLE
Integration tests fails due to docker-compose pull timeout

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#56108]
Sometimes, 900 seconds is not enough for docker to pull the images, so:
- maybe there are some problems with http://dockerhub-proxy.dockerhub-proxy-zone:5000/?
- or just with CI infrastructure?
- or maybe it worth to simply increase this timeout? and enable `--debug` mode for `dockerd` (maybe it will have more logs, like on retries on something), but I doubt that this is a good idea, since otherwise the tests will takes even longer.

@Felixoid what do you think?

Examples:
- https://s3.amazonaws.com/clickhouse-test-reports/56030/331f661322ee0b12ec41cec8cba36b9973a6aa5a/integration_tests__asan__analyzer__[1_6].html
- https://s3.amazonaws.com/clickhouse-test-reports/56030/331f661322ee0b12ec41cec8cba36b9973a6aa5a/integration_tests__asan__[6_6].html
- https://s3.amazonaws.com/clickhouse-test-reports/56030/331f661322ee0b12ec41cec8cba36b9973a6aa5a/integration_tests__asan__analyzer__[6_6].html
- https://s3.amazonaws.com/clickhouse-test-reports/56030/331f661322ee0b12ec41cec8cba36b9973a6aa5a/integration_tests_flaky_check__asan_.html

**Comment by Felixoid** [comment]
I don't understand how this is possible in https://s3.amazonaws.com/clickhouse-test-reports/56030/331f661322ee0b12ec41cec8cba36b9973a6aa5a/integration_tests__asan__analyzer__[1_6]/integration_run_parallel3_0.log

```
2023-10-26 21:13:56 [ 538 ] INFO : Got exception pulling images: Command '['docker-compose', '--env-file', '/ClickHouse/tests/integration/test_version_update/_instances_0/.env', '--project-name', 'roottestversionupdate', '--file', '/ClickHouse/tests/integration/test_version_update/_instances_0/node1/docker-compose.yml', '--file', '/ClickHouse/tests/integration/test_version_update/_instances_0/node2/docker-compose.yml', '--file', '/compose/docker_compose_keeper.yml', '--file', '/ClickHouse/tests/integration/test_version_update/_instances_0/node3/docker-compose.yml', '--file', '/ClickHouse/tests/integration/test_version_update/_instances_0/node4/docker-compose.yml', '--file', '/ClickHouse/tests/integration/test_version_update/_instances_0/node5/docker-compose.yml', '--file', '/ClickHouse/tests/integration/test_version_update/_instances_0/node6/docker-compose.yml', 'pull']' timed out after 300 seconds (cluster.py:2668, start)
```

Every image should be ready in the pulling stage https://github.com/ClickHouse/ClickHouse/actions/runs/6657903083/job/18096027453#step:6:102. I think, it's every place like in https://github.com/ClickHouse/ClickHouse/pull/56082

**Comment by qoega** [comment]
Do we run `pull` inside explicitly? I think it checks updated images and pulls them again in this case. If we have prepull enabled we need to disable `docker-compose pull` inside tests

**Comment by Algunenano** [comment]
> If we have prepull enabled we need to disable docker-compose pull inside tests

We currently don't prepull clickhouse-server images, which AFAIK are the ones timing out

**Comment by Felixoid** [comment]
Let's generate a compose file with all used images in tests? Then they will be pre-pulled too.

**Comment by Felixoid** [comment]
I can't find recent failures in this [query](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPiB0b0RhdGUoJzIwMjMtMTAtMjYnKQogICAgQU5EIHBvc2l0aW9uKGNoZWNrX25hbWUsICdJbnRlZ3JhdGlvbicpCiAgICBBTkQgdGVzdF9zdGF0dXMgPSAnRVJST1InCiAgICBBTkQgdGVzdF9kdXJhdGlvbl9tcyA+PSA0MDAwMDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==). But in https://github.com/ClickHouse/ClickHouse/pull/56214 I am adding evidence for failed infrastructure.

**Comment by Felixoid** [comment]
The [query](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPiB0b0RhdGUoJzIwMjMtMTEtMDEnKQogICAgQU5EICggKCBwb3NpdGlvbihjaGVja19uYW1lLCAnSW50ZWdyYXRpb24nKQogICAgQU5EIHRlc3Rfc3RhdHVzID0gJ0VSUk9SJwogICAgQU5EIHRlc3RfZHVyYXRpb25fbXMgPj0gNDAwMDAwICkKICAgIE9SIHRlc3RfbmFtZSA9ICdpbnRlZ3JhdGlvbl9pbmZyYXN0cnVjdHVyZV9mYWlsJyApCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=) I'm monitoring

**Comment by Felixoid** [comment]
I catch some issue, that looks exactly like that. It's on one of the docker proxy

```

**Comment by Felixoid** [comment]
Playing with neither docker container `registry` nor with storage didn't help. Only the host restart did

Now the proxy works again. Next time I'll try to remove it from the balancer and see, what's going on in details

**Comment by Felixoid** [comment]
Everything for [Nov 15](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPSB0b0RhdGUoJzIwMjMtMTEtMTUnKQogICAgQU5EICh0ZXN0X25hbWUgPSAnaW50ZWdyYXRpb25faW5mcmFzdHJ1Y3R1cmVfZmFpbCcgKQpPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIERFU0M=) is cancelled jobs

**Comment by Felixoid** [comment]
Another big [bunch](https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBjaGVja3MgCldIRVJFIDEKICAgIEFORCB0b0RhdGUoY2hlY2tfc3RhcnRfdGltZSkgPiB0b0RhdGUoJzIwMjMtMTEtMTUnKSBBTkQgdG9EYXRlKGNoZWNrX3N0YXJ0X3RpbWUpIDwgdG9EYXRlKCcyMDIzLTExLTE5JykgCiAgICBBTkQgKHRlc3RfbmFtZSA9ICdpbnRlZ3JhdGlvbl9pbmZyYXN0cnVjdHVyZV9mYWlsJyApCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQw==) of failures are related to the same host as on the last time. Now I've detached the failed node, and took a look on different metrics 
![image](https://github.com/ClickHouse/ClickHouse/assets/3025537/c0d6d44d-444e-48dc-96f1-489041526ba9)

It's interesting, we can actually see the problem. Not sure yet, wat's the actual issue, but setting up the notification based on the error rate is the next thing I'll do

**Comment by alexey-milovidov** [comment]
@Felixoid, integrate aggressive timeouts to docker pull. For example, if it doesn't succeed in five minutes, interrupt and start over again with up to five retries. You can use the `timeout` and `for` in `bash`.

**Comment by Felixoid** [comment]
It doesn't make sense to retry from the same host in this case

**Comment by Felixoid** [comment]
So, yesterday I set up the notifications for reset metrics. It's the first thing to do.

Second, this is something striking with long uptime. So this week I'll think about how to identify a safe time to reboot the nodes once a week

**Comment by azat** [comment]
Flaky check does not have pre-pull - https://github.com/ClickHouse/ClickHouse/blob/2150308c2317d9b889b14e167398946042b4035c/tests/integration/ci-runner.py#L849

I guess the reason is that it does not need to pre-pull *all* images, well, there is code that pulls images - https://github.com/ClickHouse/ClickHouse/blob/2150308c2317d9b889b14e167398946042b4035c/tests/ci/integration_test_check.py#L218 (yes, it tries to pull images), but it is done on the host.

Failed CI - https://s3.amazonaws.com/clickhouse-test-reports/42826/b94a7be3b2415643715050322a098f612fb78100/integration_tests_flaky_check__asan_.html

**Comment by Felixoid** [comment]
> it always makes sense to retry

That's why we retry enough. But we've reached the [network bandwidth throttle](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-network-bandwidth.html) on EC2 instances. And retries in this case are useless for 146%. Because there's only one poor weak host behind the load balancer, that does its best at 128Mbps to provide huge integration test images to our runners. And it fails, fails drastically! And it's very sad. So let's not retry even harder, to make it upset even more.

Khm, besides the jokes, there are two moments:

- The instances with the most effective $/bandwidth are used now:  
```
type        b.w.  max  price   
c6gn.medium 1.6   16.0 $0.0432
c7gn.medium 3.125 25.0 $0.0624
```
- I've raised the question to AWS if we can identify the moment when the max bandwidth is throttled, so we can react on it

**Comment by Felixoid** [comment]
Another action I've taken is to set `-e REGISTRY_STORAGE_CACHE=''` as suggested in https://github.com/distribution/distribution/issues/3722#issuecomment-1250032474

It was done 20 minutes ago. Let's see if it will help avoid the blob storage issue.

The issue today on morning was with another big number of resets `sudo tcpdump -ni any 'src port 5000 and tcp[tcpflags] & (tcp-rst) !=0'`

Maybe, I'll take a look eBPF hooks

**Comment by Felixoid** [comment]
I am desperate to try this solution https://github.com/rpardini/docker-registry-proxy/compare/master...coreweave:docker-registry-proxy:coreweave

Looks simple, so could actually work nicely

**Comment by Felixoid** [comment]
Together with support, we narrowed down the issue to the OS. And there are the following lines in the syslog:

```
Dec 7 18:17:07 i-00b68f90e176e90ce CRON[3107]: (root) CMD ( cd / && run-parts --report /etc/cron.hourly)
Dec 7 18:27:39 i-00b68f90e176e90ce kernel: [29603.038581] TCP: out of memory -- consider tuning tcp_mem
Dec 7 18:27:41 i-00b68f90e176e90ce kernel: [29604.715673] TCP: out of memory -- consider tuning tcp_mem
Dec 7 18:27:43 i-00b68f90e176e90ce kernel: [29606.806509] TCP: out of memory -- consider tuning tcp_mem
Dec 7 18:27:43 i-00b68f90e176e90ce kernel: [29607.391224] TCP: out of memory -- consider tuning tcp_mem
```

From the linux manual and some random pages, I try the following configuration to mitigate it:

```
net.core.netdev_max_backlog=2000
net.core.rmem_max=1048576
net.core.wmem_max=1048576
net.ipv4.tcp_max_syn_backlog=1024
net.ipv4.tcp_rmem=4096 131072  16777216
net.ipv4.tcp_wmem=4096 87380   16777216
```
