### ISSUE TITLE
Materialize column overwrites all past value. It should be documented.

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#56119]
https://clickhouse.com/docs/en/sql-reference/statements/alter/column#materialize-column

It does not say an extremely important thing – column materialization will overwrite all past values in the column.

**Comment by den-crane** [comment]
It was meant by `or updates`

**Comment by den-crane** [comment]
But probably it can be improved

**Comment by melvynator** [comment]
https://github.com/ClickHouse/ClickHouse/pull/56136 should resolve the problem.

**Comment by rschu1ze** [comment]
Reopen. Let's first merge a fix (which #56136 isn't) and then close the issue.

**Comment by socketpair** [comment]
@melvynator @rschu1ze Please reopen. We need to fix documentation back again. i.e. add "Since version xxxxx ClickHouse does not rewrite filled values."

**Comment by rschu1ze** [comment]
> @melvynator @rschu1ze Please reopen. We need to fix documentation back again. i.e. add "Since version xxxxx ClickHouse does not rewrite filled values."

Thanks, please see https://github.com/ClickHouse/ClickHouse/pull/60642 for a doc update. Closing this ticket again.
