### ISSUE TITLE
Performance/Load test in clickhouse cluster

### ISSUE THREAD

**Issue by Shankara-git** [ClickHouse/ClickHouse#56115]
We have installed 2 shard and 2 replica clickhouse cluster, now we want to measure performance/load test on clickhouse cluster.
Looks like clickhouse benchmark tool is used to measure performance of clickhouse server. Is there any tool we can use to measure performace/load test on clickhouse cluster ?

Thanks

**Comment by melvynator** [comment]
I've been working on a few users and a framework often used for insert/query load testing is the locust one: https://locust.io/

**Comment by Shankara-git** [comment]
@melvynator can you please share some example of locust with clickhouse ?

**Comment by melvynator** [comment]
@Shankara-git I don't have an example handy.

**Comment by nickitat** [comment]
> clickhouse benchmark tool is used to measure performance of clickhouse server
> Is there any tool we can use to measure performace/load test on clickhouse cluster 

don't quite understand how cluster is different from server

**Comment by Shankara-git** [comment]
@nickitat instead of testing directly on the server wanted to test through the loadbalancer (using altinity operator for deploying the clickhouse cluster, so, default loadbalancer service is deployed and wanted to use for load test also)

**Comment by nickitat** [comment]
you could pass arbitrarily hostname to `clickhouse-benchmark`, including fqdn of your balancer

**Comment by Shankara-git** [comment]
@nickitat yes, I have tried that but clickhouse-benchmark is also part of one of the server and it will also use the server resource. is there any way we can deploy only clickhouse-benchmark for remote cluster load test ?

**Comment by nickitat** [comment]
there is nothing to deploy. you could do it on your laptop or allocate a vm in any public cloud. download ch with `curl https://clickhouse.com/ | sh` and run benchmark.
