### ISSUE TITLE
clickhouse version 23, connect hdfs error

### ISSUE THREAD

**Issue by jdxia** [ClickHouse/ClickHouse#56149]
CREATE TABLE guandata.of0b4be941d9_0(
idNullable(Int32),
customer_nameNullable(String),
commentsNullable(String)
)ENGINE=HDFS('hdfs://nameserver1/guandata-store/of0b4/part-000.snappy.parquet','Parquet')

select * from guandata.of0b4be941d9_0;
When I execute the SQL query, ClickHouse reports an error.

> connection reset by peer: While executing ParquetBlockInputFormat: While exeuting HDFSSource. (NETWORK_ERROR)

The error logs on HDFS are as follows:
![image](https://github.com/ClickHouse/ClickHouse/assets/23069626/b4aba8e7-846a-48c8-97f3-83727d50cbea)

My environment involves connecting ClickHouse to HDFS with Kerberos authentication to query data. I have confirmed that my Kerberos configuration is correct. I can obtain tickets using kinit and verify them with klist.

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
