### ISSUE TITLE
How to select 2 values as 2 rows

### ISSUE THREAD

**Issue by flyly0755** [ClickHouse/ClickHouse#56153]
What i want is select 2 constants as 2 rows.
Usually select 1 can get result of one row: 
1
Now i want to get 2 rows, such as 
read
wrirte

Can achive it with union all
```sql
select 'read' as operation
union all
select 'write' as operation
```
Is there any simpler method?
I take a try with 
select 'read', 'write'
select ['read', 'write']
both results not want i want.

**Comment by nickitat** [comment]
Try arrayJoin. I found it simpler when there are quite a few values
