### ISSUE TITLE
[odbc-bridge] [Oracle] ODBCColumnsInfoHandler catalog.find_tables report Timeout expired

### ISSUE THREAD

**Issue by bibabolynn** [ClickHouse/ClickHouse#56151]
clickhouse version: version 23.5.1.1
external database: oracle 11.2.0.4
installed unixodbc version 2.3.11 

installed oracle instance client:
instantclient-basic-linux.x64-19.20.0.0.0dbru.zip
instantclient-odbc-linux.x64-19.20.0.0.0dbru.zip

driver:  instantclient_19_20/libsqora.so.19.1

odbc.ini
[oracleconn]
DRIVER = /usr/local/oracle/instantclient_19_20/libsqora.so.19.1
USERID = CLICKHOUSE
PASSWORD = clickhouse
DATABASE = ORCL
ServerName = //172.17.0.16:1521/ORCL

172.17.0.16 is oracle docker ip

sql:  SELECT * FROM odbc('DSN=oracleconn', 'CLICKHOUSE', 'TEST_TABLE'), 
when executing catalog.find_tables, it fails immediately, doesn't feel like a timeout.
 clickhouse-odbc-bridge log:
![image](https://github.com/ClickHouse/ClickHouse/assets/22643660/fc5a710d-e8f8-4352-adaa-af2a31fd06eb)

I checked user's privileges, seems like user 'CLICKHOUSE' has all privileges needed.
I executed this grant cmd for oracle user: 
grant connect,resource,dba to CLICKHOUSE

I am rather new to oracle and odbc, please help me, thanks a lot.
Please let me know if you need more informations.

**Comment by rschu1ze** [comment]
v23.5.1.1 is no longer supported, please open a new issue if you still need help.
