### ISSUE TITLE
import hdfs oom

### ISSUE THREAD

**Issue by dingxiancheng** [ClickHouse/ClickHouse#56154]
I want to import file data from HDFS to clickhouse.
HDFS has many small parquet files with the same structure. I will import all of these files into the same table in clickhouse.
1.Create table
CREATE TABLE IF NOT EXISTS of0b4be9122a14958b2a41d9(
`id` Nullable(Int32),
`customer_name` Nullable(String),
`comments` Nullable(String)
)ENGINE = HDFS('hdfs://domain name:8020/guandata-store/table_cache/guanbi/of0b4be9122a14958b2a41d9/part-00000.snappy.parquet', 'Parquet');

2.insert into temp
select * from of0b4be9122a14958b2a41d9;
3. Delete the of0b4be9122a14958b2a41d9 table
4. Repeat steps 1-3 until all files are imported into the temp table.

There is no problem in the operation, but the clickhouse server memory is not released after importing, and it is very large. When there are many files, the memory will overflow. I would like to ask, is there any way to reduce the memory usage of this import method, and try to flush the disk after the import is completed?

![image](https://github.com/ClickHouse/ClickHouse/assets/21054057/65f314b9-9579-4f9b-821e-1b3c9c1b0640)

Every time after executing the import, I will OPTIMIZE TABLE, but the memory still cannot be released. The clickhouse version I use is 22.10.2.11.

error log like:
[message] = ClickHouse exception, code: 241, host: *****, port: 8123; Code: 241, e.displayText() = DB::Exception: Memory limit (total) exceeded: would use 55.58 GiB (attempt to allocate chunk of 4503272 bytes), maximum: 55.58 GiB (version 22.10.2.11 (official build))

**Comment by ucasfl** [comment]
Does your data contain large column? like big string.

**Comment by dingxiancheng** [comment]
> Does your data contain large column? like big string.

No.The number of files is about below 100, with each parquet file  ranging from 10-100M. More than 50G memory are not enough.Memory can not used for other query，only for import data.

**Comment by dingxiancheng** [comment]
Has some params can make memory release as soon as possible! I try some params but not work well!

**Comment by dingxiancheng** [comment]
Related to snappy compress?

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
