### ISSUE TITLE
use clickhouse write HDFS data error

### ISSUE THREAD

**Issue by dingxiancheng** [ClickHouse/ClickHouse#56152]
CREATE TABLE guandata.of0b4be941d9_0(
idNullable(Int32),
customer_nameNullable(String),
commentsNullable(String)
)ENGINE=HDFS('hdfs://nameserver1/guandata-store/of0b4/part-000.snappy.parquet','Parquet')

select * from guandata.of0b4be941d9_0;
When I execute the SQL query, ClickHouse reports an error.

connection reset by peer: While executing ParquetBlockInputFormat: While exeuting HDFSSource. (NETWORK_ERROR)

The error logs on HDFS are as follows:
![image](https://github.com/ClickHouse/ClickHouse/assets/21054057/201eb43c-5dbe-4021-89f4-a6de5e941983)

My environment involves connecting ClickHouse to HDFS with Kerberos authentication to query data. I have confirmed that my Kerberos configuration is correct. I can obtain tickets using kinit and verify them with klist.

Hadoop version is 2.7.0.  Other project not clickhouse can use hdfs correctly using the same configure.

Clickhouse version is 22.10.2.11.

下面3个需要客户的cdh管理员提
hdfs.keytab是一个文件, bi里面有这个文件
hadoop_kerberos_principal 和 hadoop_security_authentication 需要客户提供

```
<hdfs>
    <hadoop_kerberos_keytab>  客户提供类似/var/lib/clickhouse/yarn.keytab  </hadoop_kerberos_keytab>
    <hadoop_kerberos_principal>   客户提供类似yarn/cdh-001@HADOOP.COM   </hadoop_kerberos_principal>
    <hadoop_security_authentication>kerberos</hadoop_security_authentication>

    <libhdfs3_conf>/etc/clickhouse-server/hdfs-site.xml</libhdfs3_conf>
  </hdfs>
```

**Comment by dingxiancheng** [comment]
Spark use TDH.

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
