### ISSUE TITLE
Backwards compatibility of table's ddl

### ISSUE THREAD

**Issue by CMBCKSRL** [ClickHouse/ClickHouse#56157]
We have a lot of very old tables that were created with old synthax like

```
CREATE TABLE my_table 
(
...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/0/my_table', '{replica}', date, time, 8192)
```

are they gonna be compatible all the time or there are plans on removing this compatibility?

I've tried to change table's ddl with a modern one by changing metadata of the table and attaching it but this didn't work. So it seems like the only way to recreate table with the new synthax is to simply INSERT SELECT data. But it is not really suitable for us since we have a lot of these tables and they are very large (like 30 Tb each).

If there are plans on deleting this compatibility then is there gonna appear any mechanism to recreate table's ddl into a modern one. For instance, recreate ddl from above into  new one like this:

```
CREATE TABLE my_table 
(
...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/0/my_table', '{replica}')
PARTITION BY toYYYYMM(date)
ORDER BY time
```

**Comment by den-crane** [comment]
> are they gonna be compatible all the time or there are plans on removing this compatibility?

There is no plans to remove. But a lot of optimizations and features does not work with such tables. I would get rid of them ASAP.

There is an utility https://github.com/ClickHouse/ClickHouse/blob/master/utils/convert-month-partitioned-parts/main.cpp - it converts parts from the old format to the new, but parts! not tables.

Also you can vote https://github.com/ClickHouse/ClickHouse/issues/30821
