### ISSUE TITLE
How to backup user details

### ISSUE THREAD

**Issue by Shankara-git** [ClickHouse/ClickHouse#56174]
Clickhouse version : 23.3.7.5
With backup and restore command we can backup database/table. But in DR scenario, we want to backup user details also, like user and role is created using sql command. How to backup user details ?

Thanks

**Comment by lampjian** [comment]
Backup your SQL commands or configurations in plain text files is a choice, and you can find all of the SQL files in directory access.

**Comment by alexey-milovidov** [comment]
`BACKUP TABLE system.users` and similar.

**Comment by Shankara-git** [comment]
@alexey-milovidov Thanks I will try this command, is there any way I can schedule automated backup (like everyday one incremental backup) ?

**Comment by alexey-milovidov** [comment]
@Shankara-git, it should be triggered by an external system - cron, AWS Lambda, etc.
