### ISSUE TITLE
Adding TTL to local table, error code: 999

### ISSUE THREAD

**Issue by SoaringCode** [ClickHouse/ClickHouse#56188]
Exception information:Received exception from server e (version 22.4.5
Code: 999. DB: Excepribh: Received from localhost: 9000. DB: Exception: Connection loss

The clickhouse service can be written and queried normally, only when updating TTL and reporting errors。

**Comment by den-crane** [comment]
Probably you have a lot of parts in the table, thousands? Check `select count() from system.parts where table = ...`

Then you need to increase `-Djute.maxbuffer=50000000` in the Zookeeper

see https://github.com/ClickHouse/ClickHouse/issues/11933#issuecomment-661310032

**Comment by SoaringCode** [comment]
> 也许你的表中有很多零件，数千个？查看`select count() from system.parts where table = ...`
> 
> 那么就需要`-Djute.maxbuffer=50000000`在Zookeeper中增加
> 
> 请参阅[#11933（评论）](https://github.com/ClickHouse/ClickHouse/issues/11933#issuecomment-661310032)

This is indeed the problem. Thank you very much for your help
