### ISSUE TITLE
'alter_sync = 0' param was deleted

### ISSUE THREAD

**Issue by n-demidov** [ClickHouse/ClickHouse#56187]
Hello,
OPTIMIZE TABLE my_table_1 FINAL SETTINGS alter_sync = 0
not works. Version = 23.5.3.24

It seems that 'alter_sync = 0' param was deleted:
https://github.com/search?q=repo%3AClickHouse%2FClickHouse+alter_sync+language%3AC%2B%2B&type=code

**Comment by tavplubix** [comment]
It does work: https://fiddle.clickhouse.com/30cea019-e48f-4d2a-a697-69990566d005

**Comment by n-demidov** [comment]
I have a very big table. Then I add a column which has Array(UInt64) type. Than I populated this new column with a big arrays. And then I created an index on this new column with "... TYPE bloom_filter GRANULARITY 3".

And then I call OPTIMIZE TABLE my_table_1 FINAL SETTINGS alter_sync = 0 and this query hang on...

**Comment by den-crane** [comment]
but yes `alter_sync` intended to work with the **replicated** tables, need to reflect this fact in the documentation.

```
create table test(a Int64, s String) Engine=ReplicatedMergeTree('/clickhouse/tables/0/test','{replica}')
order by a as select number, number from numbers(5e8);

optimize table test final SETTINGS alter_sync = 0;
0 rows in set. Elapsed: 0.006 sec.

alter table test modify column s Int64 SETTINGS alter_sync = 0;
0 rows in set. Elapsed: 0.011 sec.
```

```
create table test(a Int64, s String) Engine=MergeTree order by a as select number, number from numbers(5e8);

optimize table test final SETTINGS alter_sync = 0;
0 rows in set. Elapsed: 34.736 sec.

alter table test modify column s Int64 SETTINGS alter_sync = 0;
0 rows in set. Elapsed: 20.881 sec.
```

**Comment by n-demidov** [comment]
Thank you
