### ISSUE TITLE
Is it possible to have multiple Clickhouse instances accessing the same disk in S3 (one is read-only)

### ISSUE THREAD

**Issue by user293811** [ClickHouse/ClickHouse#56186]
Hi, 

First of all, thank you for making Clickhouse. This is one of the few times that I've come across software that I absolutely loved. I've been using it for a couple months now and I have nothing but good things to say about it. 

Now onto my question, I have a Linux machine running Clickhouse that's ingesting data and running jobs, etc. I'd like to access the same data, stored in ReplacingMergeTree tables, from the Clickhouse instance on my laptop. Effectively I'd like to share the same data store for the two Clickhouse instances, without storing them as flat files. Is this possible? 

From my readings, it seems like I either have to have Zookeeper state info stored in S3, or that I need to restore from backups. Is this correct?

If I can periodically backup my tables to S3 from my linux machine, and somehow recreate the tables on my laptop, that would be great as well. This post suggests it's possible: https://github.com/ClickHouse/ClickHouse/discussions/45220, but when I tried restoring on my laptop from a backup that I made on my Linux machine, it doesn't let me. It seems like you cannot restore a completely new table from a backup, which doesn't make sense to me if my previous cluster accidentally got deleted. 

Anyhow, is there a way to migrate MergeTree tables between two Clickhouse instances over S3?

**Comment by lampjian** [comment]
Not possible. You can use annother native full backup tool [clickhouse-copier](https://clickhouse.com/docs/en/operations/utilities/clickhouse-copier) to distribute your tables across different instances.

**Comment by alexey-milovidov** [comment]
It's not possible.
