### ISSUE TITLE
Why path of Executable User Defined Functions show two '/'?

### ISSUE THREAD

**Issue by LGDHuaOPER** [ClickHouse/ClickHouse#56183]
My UDF config is below, refer to [this](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#user_scripts_path):

```xml
<?xml version="1.0"?>
<clickhouse>
    <user_defined_executable_functions_config>*_function.*ml</user_defined_executable_functions_config>
    <user_scripts_path>/var/lib/clickhouse/user_scripts/</user_scripts_path>
</clickhouse>
```

python_function.xml is below, refer to [this](https://clickhouse.com/docs/en/sql-reference/functions/udf#executable-user-defined-functions):

```xml
<functions>
    <!-- x-alioth-custom-update-time: 2023-10-27T21:43:00.076069900+08:00 -->
    <function>
        <!-- <type>executable_pool</type> -->
        <type>executable</type>
        <pool_size>8</pool_size>
        <name>udf_py_normalize_user_agent</name>
        <return_type>String</return_type>
        <argument>
            <type>String</type>
            <name>user_agent</name>
        </argument>
        <argument>
            <type>String</type>
            <name>type</name>
        </argument>
        <format>TabSeparated</format>
        <command>python/udf_py_normalize_user_agent.py</command>
        <execute_direct>1</execute_direct>
        <lifetime>0</lifetime>
    </function>
</functions>
```

But when I exec `sudo ps -ef | grep udf_py_normalize_user_agent`, it show below:

![user_scripts](https://github.com/ClickHouse/ClickHouse/assets/22699037/5d2ec641-96ba-4c85-83c0-bddeb61c177a)

It shows two '/', why?

ClickHouse's Version is 23.9.

Thanks!

**Comment by lampjian** [comment]
Try to add relative path python at the end of user_scripts_path or remove the last '/' from it.

**Comment by alexey-milovidov** [comment]
There is no reason to show two `/` instead of one. But it does not matter.
