### ISSUE TITLE
Replica connections health check

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#56189]
We have two replicas for a shard and using `in_order` as load balancing. However, very often we see a secondary query goes to 2nd replica instead of the first one.

I did some investigate and this is what's I observe:  sometimes, establishing connection to first replica fails with `Broken pipe`, the first replica will be marked as error for 60s, during that time, some secondary queries will go to 2nd replica. For more context, we're using hedged request and w/o parallel replicas. I tried to look at hedge request and connection establisher logic but it's quite hard to understand.

My questions:
1. Does replica connections fail with `Broken pipe` indicates a bug in connection establisher, or it indeed relates to network?
2. If it's indeed a network issue, how can we reduce the network rate from CH side?

On the other hand, I think we should have a column `last_error_message` in `system.clusters`

Thanks.
cc @den-crane @Algunenano

**Comment by den-crane** [comment]
Check network by ping 1500k packets `ping -c 20 -s 1500 shard`

>Broken pipe

Can you provide more logs? How fast it fails?

How big is the network latency between initator and in_order shard?
Does it reproduce if you disable  hedged request?
What clickhouse version do you use?

**Comment by canhld94** [comment]
> Check network by ping 1500k packets ping -c 20 -s 1500 shard

Thanks, I will try this

> Can you provide more logs? How fast it fails?

It's something like this:

```
<Warning> HedgedConnectionsFactory: Connection failed at try №1, reason: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket
```

Doesn't happens too frequent, but the problem is once if happens, in 60s the first replica will be marked as error and secondary queries will go to 2nd replica, which is bad for us.
We've consider to reduce the 60s error period, but we want to know exactly why the connection fails first. It can be a network issue, but can also be a bug in connection establishing code.

> How big is the network latency between initator and in_order shard?

Should be very fast. The initial is always 1st replica, and the ping from 1st replica to 2nd replica is sub-milliseconds

> Does it reproduce if you disable hedged request?

I haven't tested yet because we enable hedged request by default.

> What clickhouse version do you use?

Latest stable as always, with our own modification, but pretty sure we didn't touch any logic related to network connection.

**Comment by den-crane** [comment]
It looks like a correct behaviour. Clickhouse was unable to connect to another server. You can increase timeout if the latency is big.

>first replica will be marked as error for 60s,

This is controllable BTW, 

  --distributed_replica_error_half_life arg                                            Time period reduces replica error counter by 2 times.
  --distributed_replica_error_cap arg                                                  Max number of errors per replica, prevents piling up an incredible amount of errors if replica was offline for some time and allows it to be

**Comment by canhld94** [comment]
> It looks like a correct behaviour. Clickhouse was unable to connect to another server.

@den-crane This is what I'm trying to make it clear here. If the network error is something like connection timeout, or refuse, etc.. then it's no doubt that network has problem. But here it's  `Broken pipe`...

**Comment by alexey-milovidov** [comment]
> Does replica connections fail with Broken pipe indicates a bug in connection establisher, or it indeed relates to network?

Yes, it is a network problem. Nothing special about it.
