### ISSUE TITLE
when i upgrade clickhouse to version 22.3.2.1. config new user can't connect to clickhouse.

### ISSUE THREAD

**Issue by 1035358124** [ClickHouse/ClickHouse#56196]
when i upgrade clickhouse to version 22.3.2.1. when i config new user but can't connect to clickhouse normally.
only default user can connect to clickhouse.
When i connect to clickhouse by other new created user hers is the error.
td::exception. Code: 1001, type: std::out_of_range, e.what() = unordered_map::at: key not found (version 22.3.2.1)

**Comment by den-crane** [comment]
Version 22.3 is out of support. Upgrade to one of supported version 23.3, 23.8, 23.9
