### ISSUE TITLE
ALTER TABLE COMMENT COLUMN\MODIFY COMMENT ISSUE

### ISSUE THREAD

**Issue by fasolwbanke** [ClickHouse/ClickHouse#56209]
The problem occurred when upgrading Clickhouse to version 23.9.3.12

It's very big and important problem, in previous task (#55720) i didn't get answer, so i recreate issue 
We still have some problem, and it's Absolutely terrible bug so what we are got:

select version()

23.9.3.12

It occurs only if we want to update the comment to the columns of the table using cluster, executing commands without, on each server separately - everything is OK

Playback Steps:

Create database with Atomic
Create database draft on cluster '{cluster}' engine = Atomic();
Create table
CREATE TABLE draft.testmodify on cluster '{cluster}'
(
    `Kapusta` String,
    `Persik` String
)
ENGINE = ReplicatedMergeTree()
PRIMARY KEY Kapusta
ORDER BY (Kapusta, Persik)
SETTINGS index_granularity = 8192 ;
Alter columns
ALTER TABLE draft.testmodify on cluster '{cluster}' comment column Kapusta 'cabbage';
ALTER TABLE draft.testmodify on cluster '{cluster}' comment column Persik 'peach';
Checks out results on different replicates:
Started replica:
SHOW CREATE TABLE draft.testmodify

Query id: 746368ad-e316-480f-a84f-86a844956d26

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE draft.testmodify
(
    `Kapusta` String COMMENT 'cabbage',
    `Persik` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
PRIMARY KEY Kapusta
ORDER BY (Kapusta, Persik)
SETTINGS index_granularity = 8192 
Second replica:

SHOW CREATE TABLE draft.testmodify

Query id: d634b07d-6315-413f-96b0-5a3f079d9cbc

┌─statement─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE draft.testmodify
(
    `Kapusta` String COMMENT 'cabbage',
    `Persik` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
PRIMARY KEY Kapusta
ORDER BY (Kapusta, Persik)
SETTINGS index_granularity = 8192 
Third replica:

SHOW CREATE TABLE draft.testmodify

Query id: 6527c4c1-0663-405b-9dcb-c9cc6ada20df

┌─statement───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE draft.testmodify
(
    `Kapusta` String,
    `Persik` String COMMENT 'peach'
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
PRIMARY KEY Kapusta
ORDER BY (Kapusta, Persik)
SETTINGS index_granularity = 8192 
If i run alter table like 3-4 in a row, it will add Missing comments on a random replica, but to get each replica to perfection - I need to run alter table without cluster on each individual replica

**Comment by UnamedRus** [comment]
Probably that kind of alter is missing somewhere here

https://github.com/ClickHouse/ClickHouse/blob/6ab509a5c7dc4d73406fd9245cda230c382a5a85/src/Interpreters/DDLWorker.cpp#L726
