### ISSUE TITLE
Projection Query Log Not Record

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#56233]
clickhouse query_log does not record query information
server version：23.3.10.5
```
lf06-ch-000041-clickhouse-0-0 :) SELECT
                                     user_agent
                                 FROM visits
                                 WHERE user_id > 50 AND user_id < 150
                                 GROUP BY user_agent;

SELECT user_agent
FROM visits
WHERE (user_id > 50) AND (user_id < 150)
GROUP BY user_agent

Query id: 7d27c782-5c86-4ba8-843f-2213e18fed61

┌─user_agent─┐
│ IOS        │
│ Android    │
└────────────┘

2 rows in set. Elapsed: 0.004 sec.

lf06-ch-000041-clickhouse-0-0 :) SELECT query, projections FROM system.query_log WHERE query_id='7d27c782-5c86-4ba8-843f-2213e18fed61' \G;

SELECT
    query,
    projections
FROM system.query_log
WHERE query_id = '7d27c782-5c86-4ba8-843f-2213e18fed61'

Query id: 93eafc79-d71f-4010-a638-94ab1caa1415

Row 1:
──────
query:       SELECT
    user_agent
FROM visits
WHERE user_id > 50 AND user_id < 150
GROUP BY user_agent;
projections: []

Row 2:
──────
query:       SELECT
    user_agent
FROM visits
WHERE user_id > 50 AND user_id < 150
GROUP BY user_agent;
projections: []

2 rows in set. Elapsed: 0.143 sec. Processed 16.20 million rows, 613.54 MB (113.50 million rows/s., 4.30 GB/s.)

lf06-ch-000041-clickhouse-0-0 :) Bye.
```

2、projection of the source code is not queried, and the query information is not recorded
![image](https://github.com/ClickHouse/ClickHouse/assets/20608540/fce09443-2b66-44ac-b473-e383150dd51b)

**Comment by Algunenano** [comment]
Was the projection actually used? Try setting `force_optimize_projection` on SELECT to verify.

If the Select doesn't throw (which means the projection was used) please share a reproducible example.

**Comment by melvynator** [comment]
I think it's probably a bug with your version, can you try on latest it should be fix: https://github.com/ClickHouse/ClickHouse/issues/53147#issuecomment-1670327831

**Comment by sunny19930321** [comment]
> I think it's probably a bug with your version, can you try on latest it should be fixed: [#53147 (comment)](https://github.com/ClickHouse/ClickHouse/issues/53147#issuecomment-1670327831)

thanks, whether this fix was merged to the latest version 23.3

**Comment by melvynator** [comment]
I don't know the PR that fixes this issue.

**Comment by den-crane** [comment]
i guess https://github.com/ClickHouse/ClickHouse/pull/52327 and no plans to backport it into 23.3
