### ISSUE TITLE
Alter table XXX Delete Where does not work [The clickhouse kernel is 22.3.2.1]

### ISSUE THREAD

**Issue by T-M-L-C** [ClickHouse/ClickHouse#56231]
> Local table of table struct 

CREATE TABLE test.LOCAL1
(
    `ID` String,
    `URL` Nullable(String),
    `CLICK` Nullable(Decimal(9, 4)),
    `EventTime` Date
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/test/LOCAL1/{shard}', '{replica}')
PARTITION BY EventTime
ORDER BY ID
SETTINGS index_granularity = 8192

> Distributed table of table struct:

CREATE TABLE test.DIS ON CLUSTER test_cluster
AS test.LOCAL1
    ENGINE = Distributed(test_cluster, test, LOCAL1, rand());

> Test data Set

insert into test.DIS WITH 10 AS len SELECT randomPrintableASCII(len), randomPrintableASCII(len), 1.0, '2022-12-26' FROM numbers(100000);

> alter table test.LOCAL1 delete where ID like '%$ONmtuvd%'

> SELECT *
FROM system.settings
WHERE name LIKE '%mutations_sync%'

![image](https://github.com/ClickHouse/ClickHouse/assets/12447886/9f2aa68a-d570-4de6-88d3-5cb6319ab07e)

> SELECT *
FROM system.mutations
WHERE (is_done = 0) AND (database = 'test') AND (table = 'LOCAL1')
![image](https://github.com/ClickHouse/ClickHouse/assets/12447886/391fb7d8-e217-42ff-ad71-ffc1b87e8b97)

**Why Does Deleting a Task Not Take Effect?**

**Comment by alexey-milovidov** [comment]
`alter table test.LOCAL1 delete where xxxx`

What's inside xxxx?

**Comment by T-M-L-C** [comment]
alter table test.LOCAL1 delete where ID like '%$ONmtuvd%'

**Comment by den-crane** [comment]
22.3.2.1 is out of support.

Can you please share results of these **TWO queries**

1)
```
select zoo.p_path as part_zoo, zoo.ctime, zoo.mtime, disk.p_path as part_disk
from
(
  select concat(path,'/',name) as p_path, ctime, mtime
  from system.zookeeper where path in (select concat(replica_path,'/parts') from system.replicas)
) zoo
left join 
(
  select concat(replica_path,'/parts/',name) as p_path
  from system.parts inner join system.replicas using (database, table)
) disk on zoo.p_path = disk.p_path
where part_disk='' and zoo.mtime <= now() - interval 1 hour
order by part_zoo;
```

2)
```
select * from system.parts where table = 'LOCAL1' and name = '20221226_0_0_0'
```

**Comment by T-M-L-C** [comment]
Both the query results are empty. @den-crane

**Comment by den-crane** [comment]
Please share results of

1)
```
SELECT count()
FROM system.mutations
WHERE (is_done = 0);
```

2)
```
  select  database, table, round(elapsed*(1/progress)-elapsed,2) estimate_complete ,
  elapsed, round(progress,2) progress, is_mutation,formatReadableSize(total_size_bytes_compressed) size, formatReadableSize(memory_usage) memory_usage 
  from system.merges order by progress desc 
```

**Comment by T-M-L-C** [comment]
The first SQL statistics result is seven, that is, system.mutations has seven tasks to be processed. The statistical result of the second SQL statement is empty. @den-crane

**Comment by den-crane** [comment]
try `system restart replica test.LOCAL1`

You should upgrade. `Delete` was not production ready 22.3. Upgrade to 23.8.5.16.
