### ISSUE TITLE
MEMORY_LIMIT_EXCEEDED error when reading a file from S3

### ISSUE THREAD

**Issue by FengZh61** [ClickHouse/ClickHouse#56235]
My logs are stored in minio, the file is in parquet format, capacity 3.7GiB, 307 objects, and when I execute sql select * and order by a field, it returns a memory limit error. How can I solve this problem, increase the memory allocation of the machine? Is there any other solution to this problem?

```

Code: 241. DB::Exception: Memory limit (total) exceeded: would use 28.54 GiB (attempt to allocate chunk of 6654572 bytes),  
 maximum:28.13 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.: While executing  
 ParquetBlockInputFormat: While executing S3. (MEMORY_LIMIT_EXCEEDED) (version 23.8.3.48 (official build))

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/settings/query-complexity#settings-max_bytes_before_external_sort

try `set max_bytes_before_external_sort = '10G';`

**Comment by FengZh61** [comment]
> https://clickhouse.com/docs/en/operations/settings/query-complexity#settings-max_bytes_before_external_sort
> 
> try `set max_bytes_before_external_sort = '10G';`

No effect, after I execute this command, I execute sql again, still the same error, he didn't limit the memory to 10G, my version is 23.8LTS, I check `system`. `settings` table and the value in the max_bytes_before_external_sort line did not change!

**Comment by nickitat** [comment]
try set `max_bytes_before_external_sort` to `10GB / max_threads`

**Comment by den-crane** [comment]
>max_bytes_before_external_sort line did not change!

What do you mean? 
`set max_bytes_before_external_sort = '10G';` -- changes the state of the current session.
try to add `settings max_bytes_before_external_sort = '10G'` to the end of your query, probably you execute query using stateless tool.

**Comment by FengZh61** [comment]
> > max_bytes_before_external_sort line did not change!
> 
> What do you mean? `set max_bytes_before_external_sort = '10G';` -- changes the state of the current session. try to add `settings max_bytes_before_external_sort = '10G'` to the end of your query, probably you execute query using stateless tool.

![image](https://github.com/ClickHouse/ClickHouse/assets/98309003/60a52a22-0cdb-4033-846c-bb6aa77735d8)

**Comment by FengZh61** [comment]
> try set `max_bytes_before_external_sort` to `10GB / max_threads`

![image](https://github.com/ClickHouse/ClickHouse/assets/98309003/c88046fd-8153-460e-8bd3-9d6d7e95e62e)
