### ISSUE TITLE
Code: 373 DB:Exception: Session is locked by a concurrent client

### ISSUE THREAD

**Issue by yedelong** [ClickHouse/ClickHouse#56230]
![f1b79eb10a4f466ead00ce5a792c6cf](https://github.com/ClickHouse/ClickHouse/assets/75054677/48296904-faf4-4f8a-9d97-90ff100fe346)
May I ask how to resolve this error?

**Comment by alexey-milovidov** [comment]
There are several problems I can see on the screenshot:
1. Too much dust on the display.
2. Non-uniform backlight.
3. Obsolete ClickHouse version from more than a year ago.
