### ISSUE TITLE
Use Int64 for XID in Keeper

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#56245]
Int32 is currently used in Keeper and our internal client for XIDs which could cause some issues (https://github.com/ClickHouse/ClickHouse/issues/44415)

We can't simply change the type because we can easily lose compatibility with ZooKeeper clients so we should increase the protocol version.

**Comment by zhyhang** [comment]
Is there any plan of this upgrade?

**Comment by amelialin6666** [comment]
I would like to know the status of this issue. Are there any plans for modifications?
