### ISSUE TITLE
when clickhouse-server restarted clickhouse-server,it works fail and a filesystem error were found in the error log

### ISSUE THREAD

**Issue by 123akn** [ClickHouse/ClickHouse#56242]
My clickhouse-version is 22.3.8.39
And the tables was using a storage_configuration whit 24 disks.
One day the clickhouse restart by itseft.When I notice the situation and find an error prompt in the error log that the file cannot be found.
```[tasklist]
### Tasks
```

**Comment by den-crane** [comment]
22.3.8.39 is out of support.

>One day the clickhouse restart by itseft.When I notice the situation and find an error prompt in the error log that the file cannot be found.

Please provide logs.

**Comment by 123akn** [comment]
@den-crane follow is the error log,have you ever encountered the same situation？
2023.07.25 16:18:45.714764 [ 51286 ] {5ad6a3a7-46f0-47ff-8f50-e6a7b4c5d08f::20230711_39471927_39472011_4_40100643} <Error> virtual bool DB::MutatePlainMergeTreeTask::executeStep(): Code: 226. DB::Exception: No columns.txt in part 20230711_39471927_39472011_4_40100643, expected path store/5ad/5ad6a3a7-46f0-47ff-8f50-e6a7b4c5d08f/tmp_clone_20230711_39471927_39472011_4_40100643/columns.txt on drive disk_16. (NO_FILE_IN_DATA_PART), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb37467a in /usr/bin/clickhouse
1. DB::IMergeTreeDataPart::loadColumns(bool) @ 0x1628d9a9 in /usr/bin/clickhouse
2. DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x1628bc4a in /usr/bin/clickhouse
3. DB::MergeTreeData::cloneAndLoadDataPartOnSameDisk(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreePartInfo const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x16344d89 in /usr/bin/clickhouse
4. DB::MutateTask::prepare() @ 0x16481a68 in /usr/bin/clickhouse
5. DB::MutatePlainMergeTreeTask::executeStep() @ 0x1647b663 in /usr/bin/clickhouse
6. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xb34b92b in /usr/bin/clickhouse
7. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xb34b579 in /usr/bin/clickhouse
8. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb41e70a in /usr/bin/clickhouse
9. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb4208a4 in /usr/bin/clickhouse
10. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb41bad7 in /usr/bin/clickhouse
11. ? @ 0xb41f65d in /usr/bin/clickhouse
12. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
13. __clone @ 0xfe96d in /usr/lib64/libc-2.17.so
 (version 22.3.8.39 (official build))
2023.07.25 16:18:45.714772 [ 51166 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in file_size: No such file or directory [/data16/clickhouse/store/4bf/4bfd6eda-5cd5-4a15-a7c5-76c52b113f5b/20230710_646428_658809_3131/timestamp.mrk2], Stack trace (when copying this message, always include the lines below):

**Comment by 123akn** [comment]
@den-crane follow is the error log,have you ever encountered the same situation？
2023.10.25 16:18:45.714764 [ 51286 ] {5ad6a3a7-46f0-47ff-8f50-e6a7b4c5d08f::20230711_39471927_39472011_4_40100643} virtual bool DB::MutatePlainMergeTreeTask::executeStep(): Code: 226. DB::Exception: No columns.txt in part 20230711_39471927_39472011_4_40100643, expected path store/5ad/5ad6a3a7-46f0-47ff-8f50-e6a7b4c5d08f/tmp_clone_20230711_39471927_39472011_4_40100643/columns.txt on drive disk_16. (NO_FILE_IN_DATA_PART), Stack trace (when copying this message, always include the lines below):

DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) @ 0xb37467a in /usr/bin/clickhouse
DB::IMergeTreeDataPart::loadColumns(bool) @ 0x1628d9a9 in /usr/bin/clickhouse
DB::IMergeTreeDataPart::loadColumnsChecksumsIndexes(bool, bool) @ 0x1628bc4a in /usr/bin/clickhouse
DB::MergeTreeData::cloneAndLoadDataPartOnSameDisk(std::__1::shared_ptr<DB::IMergeTreeDataPart const> const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, DB::MergeTreePartInfo const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&) @ 0x16344d89 in /usr/bin/clickhouse
DB::MutateTask::prepare() @ 0x16481a68 in /usr/bin/clickhouse
DB::MutatePlainMergeTreeTask::executeStep() @ 0x1647b663 in /usr/bin/clickhouse
DB::MergeTreeBackgroundExecutorDB::MergeMutateRuntimeQueue::routine(std::__1::shared_ptrDB::TaskRuntimeData) @ 0xb34b92b in /usr/bin/clickhouse
DB::MergeTreeBackgroundExecutorDB::MergeMutateRuntimeQueue::threadFunction() @ 0xb34b579 in /usr/bin/clickhouse
ThreadPoolImpl::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb41e70a in /usr/bin/clickhouse
ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()>(void&&, void ThreadPoolImpl::scheduleImpl(std::__1::function<void ()>, int, std::__1::optional)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb4208a4 in /usr/bin/clickhouse
ThreadPoolImplstd::__1::thread::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb41bad7 in /usr/bin/clickhouse
? @ 0xb41f65d in /usr/bin/clickhouse
start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
__clone @ 0xfe96d in /usr/lib64/libc-2.17.so
(version 22.3.8.39 (official build))
2023.07.25 16:18:45.714772 [ 51166 ] {} void DB::MergeTreeBackgroundExecutorDB::MergeMutateRuntimeQueue::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in file_size: No such file or directory [/data16/clickhouse/store/4bf/4bfd6eda-5cd5-4a15-a7c5-76c52b113f5b/20230710_646428_658809_3131/timestamp.mrk2], Stack trace (when copying this message, always include the lines below):
