### ISSUE TITLE
The unit tests hanged for ASAN in #56214

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#56265]
(you don't have to strictly follow this form)

**Describe the bug**
[run.log](https://s3.amazonaws.com/clickhouse-test-reports/56214/53b3d856565c9c59020aaf80015c90926a57f176/unit_tests__asan_/run.log) of the [report](https://s3.amazonaws.com/clickhouse-test-reports/56214/53b3d856565c9c59020aaf80015c90926a57f176/unit_tests__asan_.html)

**How to reproduce**
Try to reproduce the report and copy the tables and queries involved.

**Error message and/or stacktrace**
A lot, tons of stack traces in the run log

**Comment by tavplubix** [comment]
Looks like it got stuck here:
```
[----------] 2 tests from IOResourceDynamicResourceManager
[ RUN      ] IOResourceDynamicResourceManager.Smoke
[       OK ] IOResourceDynamicResourceManager.Smoke (0 ms)
[ RUN      ] IOResourceDynamicResourceManager.Fairness
```

**Comment by serxa** [comment]
Fixed https://github.com/ClickHouse/ClickHouse/pull/60712
