### ISSUE TITLE
Document `Detach database <db-name>`

### ISSUE THREAD

**Issue by incfly** [ClickHouse/ClickHouse#56279]
**Describe the issue**
We have `system detach database` option, e.g.

https://github.com/ClickHouse/ClickHouse/pull/42807/files#diff-26e0864248c230daf98dafcb024fb977aa2eaac205bc5c797a6a0fb9d2e81a9dR34

but this is not an option in the doc. https://clickhouse.com/docs/en/sql-reference/statements/detach

**Comment by melvynator** [comment]
Should be closed by: https://github.com/ClickHouse/ClickHouse/pull/56280
