### ISSUE TITLE
please add '|| (defined(__powerpc64__) )' to support IBM Power PowerPC64 platform in contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c 

### ISSUE THREAD

**Issue by DBres4Power** [ClickHouse/ClickHouse#56284]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

In **contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c**
#if defined(__i386) || defined(__ARM_EABI__)                                   \
    || (defined(__mips__) && _MIPS_SIM == _ABIO32)                             \
    || (defined(__riscv) && __riscv_xlen == 32)
typedef Elf32_auxv_t elf_aux_entry;
#elif defined(__x86_64) || defined(__aarch64__)                               \
    || (defined(__mips__) && _MIPS_SIM != _ABIO32)                            \
    || (defined(__riscv) && __riscv_xlen == 64) || (defined(__s390x__))  \
    **|| (defined(__powerpc64__) )** 

Please add **|| (defined(__powerpc64__) )** to support IBM Power PowerPC64 platform.

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
Redhat 8.4 ppc64le, Kernel: 4.18.0-305.el8.ppc64le

**Cmake version**
3.20.2

**Ninja version**
1.11.1

**Compiler name and version**
clang 16.0.6

**Full cmake and/or ninja output**
Build Clickhouse on PowerPC64 (OS Redhat 8.4 ppc64le) raise following error:
/home/clickhouse/git/ClickHouse/contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c:399:5: error: use of undeclared identifier 'elf_aux_entry'
    elf_aux_entry one_aux_entry;
    ^
/home/clickhouse/git/ClickHouse/contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c:401:41: error: use of undeclared identifier 'elf_aux_entry'
        read(fd, &one_aux_entry, sizeof(elf_aux_entry)) == sizeof(elf_aux_entry)
                                        ^
/home/clickhouse/git/ClickHouse/contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c:401:19: error: use of undeclared identifier 'one_aux_entry'
        read(fd, &one_aux_entry, sizeof(elf_aux_entry)) == sizeof(elf_aux_entry)
                  ^
/home/clickhouse/git/ClickHouse/contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c:401:67: error: use of undeclared identifier 'elf_aux_entry'
        read(fd, &one_aux_entry, sizeof(elf_aux_entry)) == sizeof(elf_aux_entry)
                                                                  ^
/home/clickhouse/git/ClickHouse/contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c:402:12: error: use of undeclared identifier 'one_aux_entry'
        && one_aux_entry.a_type != AT_NULL) {
           ^
/home/clickhouse/git/ClickHouse/contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c:403:13: error: use of undeclared identifier 'one_aux_entry'
        if (one_aux_entry.a_type == AT_SYSINFO_EHDR) {
            ^
/home/clickhouse/git/ClickHouse/contrib/sentry-native/src/modulefinder/sentry_modulefinder_linux.c:405:28: error: use of undeclared identifier 'one_aux_entry'
            return (void *)one_aux_entry.a_un.a_val;
                           ^
7 errors generated.
[14/4620] Building C object contrib/nats-io-cmake/CMakeFiles/_nats_io.dir/__/nats-io/src/kv.c.o
ninja: build stopped: subcommand failed.

**Comment by alexey-milovidov** [comment]
You can download pre-built binaries for PowerPC as follows:
```
curl https://clickhouse.com/ | sh
```
