### ISSUE TITLE
Some questions about parallel  read replicas， How to ensure correctness In the following scenarios？

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#56283]
1、How to ensure correctness if one replica has merged parts and the other has not?
     For example： replica1  parts：1-1-0    2-2-0
     replica2 parts：1-2-1

2、How to ensure correctness if one replica has new parts and the other no time to synchronize?
     For example： replica1  parts：1-1-0    2-2-0   3-3-0
     replica2 parts：1-1-0    2-2-0

**Comment by Algunenano** [comment]
> How to ensure correctness if one replica has merged parts and the other has not?

There is a step during query announcement where each replica replies with the list of parts available, then the coordinator decides what's going to be read (preferring sets with higher number of replicas owning them IIRC) and assigns the work to the replicas that have those parts.

> > How to ensure correctness if one replica has new parts and the other no time to synchronize?

Same as above, the work of reading those parts will go to the replicas that have those parts only.
