### ISSUE TITLE
Delete query timeout on table that is being optimized atm

### ISSUE THREAD

**Issue by Mad-Melon** [ClickHouse/ClickHouse#56330]
Hi there.
I have java service that is making frequent inserts in the specific table based on ReplacingMergeTree engine. Target table has around 470 millions rows.
Due to the business specific requirements i also have to use delete query following each insert query.
On top of that i'm using scheduled optimize on daily basis at 5.20 am.

The problem i encountered is following:
- due to the table size optimize process takes some significant time meanwhile delete queries execution time also increases drastically. Some times it causes my service to shut down with connection exception: **Connection is not available, request timed out after 30000ms**. There are no exceptions in clickhouse logs when it happens.

Questions are:
- Are there any table locks during optimize process that are slowing down delete queries? May be it is a stupid question, but i see no difference in performance of insert queries during optimize process.
- Are there any workarounds to solve that issue except increasing max timeout?

**Comment by lampjian** [comment]
Try to use a final query, and stop the scheduled optimize task.

**Comment by alexey-milovidov** [comment]
DELETE will wait for the merges already assigned by OPTIMIZE.

About your problem - the OPTIMIZE query is rarely needed, and it is usually a mistake to do it.

**Comment by Mad-Melon** [comment]
> DELETE will wait for the merges already assigned by OPTIMIZE.
> 
> About your problem - the OPTIMIZE query is rarely needed, and it is usually a mistake to do it.

Thanks for such fast response. I'll get rid of scheduled optimize and rely on Clickhouse background merges then.
