### ISSUE TITLE
A warning on a large number of databases, tables, partitions, or parts.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56346]
**Use case**

The server configuration will contain thresholds for the number of databases (1000), tables (5000), partitions (50000), and parts (100000). If the actual number is higher, it will create a warning that will be displayed to the user.

**Describe the solution you'd like**

We already have this mechanism of warnings.
The checks can be located in the asynchronous metrics thread.

**Additional context**

Additionally, implement a warning if the total size of primary keys in memory exceeds half of the memory size.

**Comment by lingtaolf** [comment]
I'd like have a try. Could you please assign this to me ?

**Comment by alexey-milovidov** [comment]
@lingtaolf, Thank you!

**Comment by alexey-milovidov** [comment]
@lingtaolf we will add it as a warning for `clickhouse-client`, which is also shown in the `system.warnings` table, so other tools could pick it up as well.

**Comment by lingtaolf** [comment]
@alexey-milovidov Hi, I met some questions. The create tables should include views, inner views, dictionaries, distributed tables? Because I encountered a situation when I created the materialized view, two table names would appear in the corresponding database, and I was not sure what to do with this situation.

**Comment by melvynator** [comment]
It has been implemented and I updated the KB: https://github.com/ClickHouse/clickhouse-docs/pull/1832

**Comment by melvynator** [comment]
Thank you @lingtaolf !
