### ISSUE TITLE
Npy as an output format

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56345]
**Use case**

Currently it's supported only for input.

**Comment by HowePa** [comment]
I can work on this.

**Comment by alexey-milovidov** [comment]
@HowePa, this will be amazing!

**Comment by HowePa** [comment]
Update:  
The [Npy out format](https://numpy.org/doc/stable/reference/generated/numpy.lib.format.html) maintains a header. For example,

```
�NUMPYv{'descr': '|S8', 'fortran_order': False, 'shape': (2, 3), }
```

Of these, `descr`(data_type) and `shape` are closely related to the data, which leads to two challenges:
1. **Get max_length for type String**. `descr` ends with the length of the data type, so a Column of type `String` or `Array(String)` needs to get the maximun string length.  
2. **Get total num_rows among multiple Blocks**. According to the description of the Npy input format, `shape[0]` is the number of rows.

**Comment by alexey-milovidov** [comment]
It will require buffering the output in memory.
