### ISSUE TITLE
clickhouse-performance-test filename.xml doesn't work as expected.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5635]
It performs all tests from current directory.

**Comment by stavrolia** [comment]
@alexey-milovidov There is an option --input-files to set the list of input-files. clickhouse-performance-test --help shows usage like "clickhouse-performance-test [options]" and it works. Is this issue about changing current api or name of option?

**Comment by alexey-milovidov** [comment]
1. `clickhouse-performance-test filename.xml`

Does it assume that "filename.xml" is a garbage and completely ignores it instead of throwing an exception about unsupported command line parameter?

2. Compare, how easy is to run `clickhouse-test` for specific test case. I expect that `clickhouse-performance-test` should be as easy to run.

**Comment by alexey-milovidov** [comment]
`clickhouse-performance-test` no longer exists.
