### ISSUE TITLE
It doesn't look like either scenario will work properly with parallel reading,  Is that so？

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#56355]
> How to ensure correctness if one replica has merged parts and the other has not?

There is a step during query announcement where each replica replies with the list of parts available, then the coordinator decides what's going to be read (preferring sets with higher number of replicas owning them IIRC) and assigns the work to the replicas that have those parts.

> > How to ensure correctness if one replica has new parts and the other no time to synchronize?

Same as above, the work of reading those parts will go to the replicas that have those parts only.

_Originally posted by @Algunenano in https://github.com/ClickHouse/ClickHouse/issues/56283#issuecomment-1792126205_

**Comment by Sallery-X** [comment]
I looked at the specific functions.  The key word as follows,

                /// We have two or possibly more intersections
                if (intersected_before)
                    return IntersectionResult::REJECT;

                /// We have intersection with part with different name
                /// or with different min or max block
                /// It could happens if we have merged part on one replica
                /// but not on another.
                if (segment != part)
                    return IntersectionResult::REJECT;

                /// We allow only the intersection with the same part as we have
                intersected_before = true;


It doesn't look like either scenario will work properly with parallel reading 

For example： replica1 parts：1-1-0 2-2-0
replica2 parts：1-2-1

For example： replica1 parts：1-1-0 2-2-0 3-3-0
replica2 parts：1-1-0 2-2-0

**Comment by Algunenano** [comment]
Please test it and report a reproducible example if it doesn't work as you expected. Also, keep in mind that this is still an experimental feature
