### ISSUE TITLE
Compatibility Issue with ClickHouse Keeper on Rocky Linux 8.8

### ISSUE THREAD

**Issue by JungChaeMoon** [ClickHouse/ClickHouse#56353]
Hello!
 
I am currently experiencing an issue with ClickHouse Keeper on a virtual machine running Rocky Linux 8.8 and I'm wondering if there are known compatibility issues.

Environment:
* ClickHouse Keeper Version: 23.5.3.24
* OS: Rocky Linux 8.8 (VM setup)

Issue Description:

We have observed intermittent CPU spikes and a consistent CPU I/O wait of around 8~13% which leads to the OS hanging. During these periods, the ClickHouse servers are unable to establish a connection to the ClickHouse Keeper. Interestingly, there are no significant error logs in the OS during these times. The I/O wait issue does not resolve by itself and keeps recurring.

<img width="1374" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/47454661/47d53217-840a-43bd-846c-a901a8dcea97">

To mitigate the issue, we set up three new VMs running “Red Hat Enterprise Linux Server 7.9 (Maipo)” and configured a ClickHouse Keeper cluster there. Since the migration, the cluster has been operating smoothly without any incidents.

Questions/Concerns:
* Is ClickHouse Keeper fully compatible with Rocky Linux, specifically version 8.8?
* Could there be a potential issue with ClickHouse Keeper running on Rocky Linux that we should be aware of?

**Comment by lampjian** [comment]
It should only depends on your CPU architecture and OS. As far as I use near a year, most of the problems are irrational configurations. You need more logs to find some exceptions about clickhouse-keeper.

**Comment by JungChaeMoon** [comment]
Hello! 
I agree with you, but I'm concerned that Rocky 8.8 and clickhouse-keeper may not be fully compatible. 
The CPU usage spiked even though there were no other logs left, which suggests that there may be a problem with the compatibility. 
Can you confirm that Rocky 8.8 OS is supported?

**Comment by lampjian** [comment]
"ClickHouse can run on any Linux, FreeBSD, or macOS with x86-64, ARM, or PowerPC64LE CPU architecture." is the official statement about supported OS. One more thing, you shall deploy your clickhouse-keeper instances on dedicated servers.
