### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by matterumirai** [ClickHouse/ClickHouse#56372]
I have cluster has 4 shards and 4 replicas (Clickhouse 23.9.2)
All replicas has 256 cpu cores and 512 gb RAM
A distributed table on cluster have about 600 billion rows. 
Some memory problems occurs when i select from the table with join and group by clauses.

In order of :

1. memory limit (total) exceed
2. Attempt to read after eof: while receiving packet from otherreplica:9000 
3. cannot read all data

i already set below:
max_server_memory_usage_to_ram_ratio 0.5
max_bytes_before_external_group_by = 250000000000
max_bytes_before_external_sort = 250000000000
distributed_aggregation_memory_efficent=1

is there any configuration that i can try?
or have not i  enough memory to query it?

**Comment by den-crane** [comment]
CH puts the right table into a memory to execute join.

Try to enable another join algorithm

```
join_algorithm = 'grace_hash'
grace_hash_join_initial_buckets=32
grace_hash_join_max_buckets=32
```

https://gist.github.com/den-crane/0c67d37d9ee4fb3e3251ef27cb8a8d4b

**Comment by matterumirai** [comment]
@den-crane  when i tried dictionary option that error occurs:

```
select a,count(*) as counter,dictGet('klist','name',b) as c from mytable  group by a, c

← Progress: 629.38 billion rows, 28.06 TB (699.31 million rows/s., 31.18 GB/s.) ██████████████████████████████████████████████████████████████████████ 99%
0 rows in set. Elapsed: 900.001 sec. Processed 629.38 billion rows, 28.06 TB (699.31 million rows/s., 31.18 GB/s.)
Peak memory usage: 260.36 GiB.
Received exception from server (version 23.9.2):

Code: 210. DB::Exception: Received from localhost:9000. DB::NetException. DB::NetException: Connection reset by peer, while reading from socket (10.10.10.3:9000): while receiving packet from 10.10.10.3:9000: While executing Remote. (NETWORK_ERROR)



```
And another join algoritm option runs very slow and gets stuck in %99

right table  Log Engine : 2 columns, 34000 rows 
join query:  `select a,count(*) as counter,c from mytable mt LEFT JOIN klist kl ON mt.b=kl.d group by a, c`


Did i use dictionary right?

**Comment by den-crane** [comment]
>right table Log Engine : 2 columns, 34000 rows

34k rows? It should use small amount of memory. 

try `max_bytes_before_external_group_by = 100000000000`

**Comment by matterumirai** [comment]
i already set before
`max_bytes_before_external_group_by = 250000000000 (~ half of available system memory)`

i changed it `max_bytes_before_external_group_by = 100000000000` and error hasn't gone.

`Code: 210. DB::Exception: Received from localhost:9000. DB::NetException. DB::NetException: Connection reset by peer, while reading from socket (10.10.10.7:9000): while receiving packet from 10.10.10.7:9000: While executing Remote. (NETWORK_ERROR)`

max_threads is auto(128) i didn't set it. Should i reduce number of  it?

**Comment by matterumirai** [comment]
i think the problem about rows in set. Because i add limit to query it works. 
I checked all replicas err.log and find the error about "timeout exceeded while **writing** to socket"  and tried limit operation.

**Comment by den-crane** [comment]
For how long query executes against replicated table (not distributed)?

**Comment by matterumirai** [comment]
for 20 billion rows in replicated table 
with join 1 billion rows in set.

**Comment by den-crane** [comment]
try `set receive_timeout=1800`
