### ISSUE TITLE
Error adding projection in 23.7+ "ORDER BY cannot be empty"

### ISSUE THREAD

**Issue by strtgbb** [ClickHouse/ClickHouse#56378]
**Describe the issue**
The following alter  table statement returns an error in recent versions
```sql
CREATE TABLE mytable (d DATE, b UInt8, y Int8) ENGINE = MergeTree() PARTITION BY y ORDER BY (b, d) PRIMARY KEY b;
ALTER TABLE mytable ADD PROJECTION myproj (SELECT y);
```

**Error message and/or stacktrace**
```
Received exception from server (version 23.7.6):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: ORDER BY cannot be empty. (BAD_ARGUMENTS)
(query: ALTER TABLE mytable ADD PROJECTION myproj (SELECT y);)
```

**How to reproduce**
* Occurs on 23.7+
* Fiddle for 23.3 https://fiddle.clickhouse.com/2283be41-3a3e-45ed-bc4e-44393b5f0093
* Fiddle for 23.7 https://fiddle.clickhouse.com/7b3d4434-ab01-4cf9-9692-d2b450b07743

**Comment by den-crane** [comment]
>PROJECTION myproj (SELECT y);)

This is not correct.

A projection have to have `ORDER BY` or `GROUP BY`

It should be
```
ALTER TABLE mytable ADD PROJECTION myproj (SELECT y group by y);
```


https://fiddle.clickhouse.com/c01c8dee-bf85-4588-8b1b-725a1820276a
