### ISSUE TITLE
About Adding Replicas to a Cluster？

### ISSUE THREAD

**Issue by yangshike** [ClickHouse/ClickHouse#56400]
hello！
I recently encountered data synchronization issues while adding replicas to the cluster

clickhouse version：23.7.1 ，database engine :Atomic ,Starting with a two replica cluster
replica config：
 <cluster_with_replica>
            <shard>
                <weight>1</weight>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>192.168.1.181</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>192.168.1.179</host>
                    <port>9000</port>
                </replica>
Now 1 new node has been added

：
   <replica>
                    <host>192.168.2.140</host>
                    <port>9000</port>
                </replica>

I copied the creation files of the database and table to the new node,

There is no problem creating a new node database and table, but the data has not been synchronized。
I did not see any new node replica information for the table on Zookeeper either

this is one of table ：
 CREATE TABLE test.test_table
(
    corp_id String ,
    user_id String,
    user_name String 
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY (corp_id, user_id,)
SETTINGS index_granularity = 8192

I tried creating nodes in zookeeper

/clickhouse/tables/910a53d9-8181-8a39-6f10-0e503bcfae22/01/replicas/01-01-3/flags/force_ restore_ data
and
sudo u clickhouse touch/var/lib/clickhouse/flags/force_ restore_ data

But there is no group effect, what else do I need to do！！

**Comment by evillique** [comment]
> I copied the creation files of the database and table to the new node

Did you create all the tables and databases by executing CREATE queries?

Is the macros section correctly filled on the new replica? Are there any errors in the logs?

**Comment by yangshike** [comment]
Can't you manually create a table? Is the manually created table uuid inconsistent
ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}',)

**Comment by yangshike** [comment]
The original table creation is like this

ENGINE=ReplicatedReplacingMergeTree ('/click house/tables/{uuid}/{shard}', '{replica}', gmt_modified)

Do I need to find the uuid for each table, modify the creation statement, and execute it one by one?

There are hundreds of watches, which is a huge workload

**Comment by evillique** [comment]
You can look into backups: https://clickhouse.com/docs/en/operations/backup with `structure_only` parameter enabled.

Or you could try to construct the create statements with the data from `system.tables`.

**Comment by evillique** [comment]
You can also look into Replicated database which solves exactly the problem you are having.

**Comment by yangshike** [comment]
in the system.tables the create_table_query about engine  like this:
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}',
No specific uuid

**Comment by evillique** [comment]
Something like this:
```
SELECT concat('CREATE TABLE `', database, '`.`', table, '` UUID `', toString(uuid), '`', substr(create_table_query, length(database) + length(table) + 15), ';') from system.tables where database not in ['system', 'INFORMATION_SCHEMA', 'information_schema'] and engine != 'View' INTO OUTFILE 'tables.sql'`
```

**Comment by yangshike** [comment]
ok! thanks very much
