### ISSUE TITLE
 Removed ClickHouse nodes still being requested and logged with their shard_num

### ISSUE THREAD

**Issue by huoarter** [ClickHouse/ClickHouse#56402]
clickhouse_version=21.11.5

I have encountered an issue with removed ClickHouse nodes where the existing nodes still request the old nodes and record their shard_num, despite having replaced the IP addresses in the metrika_xml configuration with new IPs. I have verified that the removed IP addresses are not in the updated configuration; however, the logs still show requests being sent to these removed IP addresses by the old nodes, and the shard_num is also detected.

Steps to reproduce:

Remove a node from ClickHouse cluster and update metrika_xml with new IP addresses.
Check if new configuration excludes the removed IP addresses.
Observe the log files on existing nodes.
Expected behavior:

The existing nodes should not request the removed nodes or record their shard_num.

Actual behavior:

The existing nodes still request the removed nodes and record their shard_num, even though they are no longer part of the configuration.

Need assistance in resolving this issue and understanding why the nodes continue to request excluded nodes.

my log:
```
[Warning] [10.67.74.39] [2023.11.06 12:53:57.692405] message:Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (10.67.74.33:9081). (NETWORK_ERROR) (version 21.11.5.33 (official build))
[Warning] [10.67.73.240] [2023.11.06 12:54:00.754018] message:Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (10.67.74.33:9081). (NETWORK_ERROR) (version 21.11.5.33 (official build))
[Warning] [10.67.74.31] [2023.11.06 12:53:59.099414] message:Connection failed at try №1, reason: Code: 210. DB::NetException: Connection refused (10.67.74.44:9081). (NETWORK_ERROR) (version 21.11.5.33 (official build))
```
removed ip: 10.67.74.33,10.67.74.44

Adding more severity to the issue: When the original shard num of this IP was 52, and I had reused this IP and joined the cluster setting its shard num as 50, there are certain nodes that still synchronise the data of shard num 52 to this IP while writing to the distributed table with a specified sharding key. This is unexpected behaviour and it's causing inconsistencies in my dataset. I need help to understand why this is happening and how to correct it.

**Comment by den-crane** [comment]
>my log:
>[Warning] [10.67.74.39] [2023.11.06 12:53:57.692405]

Can you share bigger excerpt? It's unclear which component produced this messages.
Check `system.clusters` on all nodes for the stale information.


21.11.5 - is out of support. You should upgrade. Unfortunately we don't have a capacity to support the old Clickhouse versions.
