### ISSUE TITLE
Bad metadata file name for AWS Athena Iceberg tables

### ISSUE THREAD

**Issue by svdimchenko** [ClickHouse/ClickHouse#56415]
**What's wrong**

Actually when AWS Athena creates Iceberg table we get the following metadata files structure:

```
❯ aws s3 ls s3://bucket-name/dbt/sandbox/test_iceberg_table/metadata/
00000-a7d33b27-090d-4517-bd94-7dadbdd011cd.metadata.json
00001-7d08627e-75b3-4331-a20a-bf165c811119.metadata.json
d36a427a-3235-4eb2-a77b-c39343e0822e-m0.avro
snap-4621040911997064693-1-d36a427a-3235-4eb2-a77b-c39343e0822e.avro
```

This leads to error on clickhouse side
```
Code: 36. DB::Exception: Bad metadata file name: 00000-a7d33b27-090d-4517-bd94-7dadbdd011cd.metadata.json. Expected vN.metadata.json where N is a number. (BAD_ARGUMENTS)
```

**How to reproduce**

* Clickhouse image version 23.10.1.1976-alpine
* Interface does not matter. I've tried clickhouse-client or DBeaver JDBC connection, results are the same.

1. Create iceberg table with athena
```
CREATE TABLE sandbox.test_iceberg_table (
  id int,
  data string,
  category string) 
PARTITIONED BY (category, bucket(16,id)) 
LOCATION 's3://bucket-name/dbt/sandbox/test_iceberg_table' 
TBLPROPERTIES (
  'table_type'='ICEBERG',
  'format'='parquet',
  'write_compression'='snappy',
  'optimize_rewrite_delete_file_threshold'='10'
)
```

2. Insert some data into table
```
INSERT INTO sandbox.test_iceberg_table (id, data, category)
VALUES (1, 'test', 'cat1')
```

3. Try to create table in clickhouse with Iceberg Engine
```
create table test_iceberg ENGINE = Iceberg('https://bucket-name.s3.eu-central-1.amazonaws.com/dbt/sandbox/test_iceberg_table');
```

get the following error
```
SQL Error [36] [07000]: Code: 36. DB::Exception: Bad metadata file name: 00000-a7d33b27-090d-4517-bd94-7dadbdd011cd.metadata.json. Expected vN.metadata.json where N is a number. (BAD_ARGUMENTS) (version 23.10.1.1976 (official build))
```

**Comment by zeddit** [comment]
+1, facing the same issue.

**Comment by Avogar** [comment]
Right now we don't support metadata files that AWS Athena creates, only files in format `vN.metadata.json` like Spark uses. I will add support for format from AWS Athena

**Comment by piobogiwo** [comment]
I have recorded the same issue today.

**Comment by Avogar** [comment]
The fix was not release yet

**Comment by piobogiwo** [comment]
I am still getting "Expected vN.metadata.json where N is a number." on the latest docker. Is this feature already available ?
