### ISSUE TITLE
A limit on the number of projections per table.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56427]
A limit can be configurable by a query-level setting (the setting could be constrained then).

It can be set to 25 by default.

**Comment by jkartseva** [comment]
Could you please elaborate on 'be constrained'?
Should the limitation be in the form of https://clickhouse.com/docs/en/operations/settings/constraints-on-settings or a hardcoded constant?

**Comment by alexey-milovidov** [comment]
Constraints on settings (max), and it will be set in ClickHouse Cloud. Nothing additional here.
