### ISSUE TITLE
RESTORE TABLE ERROR: CANNOT_UNPACK_ARCHIVE

### ISSUE THREAD

**Issue by we1she2** [ClickHouse/ClickHouse#56436]
Hi guys~
When I restore a table, the following issue have occurred:
Code: 643. DB::Exception: Received from localhost:9000. DB::Exception: Couldn't unpack zip archive 'eth_raw_blocks_from_1_to_10000000.zip': Code = -3. (CANNOT_UNPACK_ARCHIVE)

![image](https://github.com/ClickHouse/ClickHouse/assets/122858779/22472cd6-f0e8-4e66-8ed0-783bd10e2296)

**Comment by we1she2** [comment]
I checked the permissions of the file, looks like there's no problem

-rwxr-xr-x 1 clickhouse clickhouse   47337883483 Sep 26 08:47 eth_raw_blocks_from_1_to_10000000.zip

**Comment by nikitamikhaylov** [comment]
Are you able to unpack it with command line utility? How did you get this archive?
