### ISSUE TITLE
`information_schema.tables` lacks field `STATISTICS` (MySQL compatibility)

### ISSUE THREAD

**Issue by larskarbo** [ClickHouse/ClickHouse#56432]
Required for Tableau Online.

When using tableau online, we get this error

```
DB::Exception: Table INFORMATION_SCHEMA.STATISTICS does not exist. (UNKNOWN_TABLE)
```

Similar to https://github.com/ClickHouse/ClickHouse/issues/55182, we need a `STATISTICS` table for MySQL compatibility

This query:

```
SHOW TABLES FROM information_schema;
```

Returns

```
COLUMNS
KEY_COLUMN_USAGE
REFERENTIAL_CONSTRAINTS
SCHEMATA
TABLES
VIEWS
columns
key_column_usage
referential_constraints
schemata
tables
views
```

Notice that there is no `STATISTICS` table

## Expected behaviour

That `INFORMATION_SCHEMA.STATISTICS` exists so that Tableau online works.

## How to reproduce

- Which ClickHouse server version to use: master
- Which interface to use, if matters: MySQL

cc @slvrtrn

**Comment by slvrtrn** [comment]
@larskarbo, PR is up already: https://github.com/ClickHouse/ClickHouse/pull/56425
For testing purposes, what action triggers the error? I don't think I've seen this error before.
