### ISSUE TITLE
Make `query_masking_rules` reloadable without restart of a server

### ISSUE THREAD

**Issue by mkmkme** [ClickHouse/ClickHouse#56449]
**Use case**

Currently, if you want to redact new things, you have to restart the clickhouse server to apply the new masking rules. It would be great to be able to take new redacting rules into use without need to restart the server.

**Additional context**

The change seems to be quite simple, so if you think it's OK to be propagated, I would like to implement it myself (I have been poking into that yesterday and I think code-wise it should be pretty much ready).

**Comment by alexey-milovidov** [comment]
Yes, it will be good to add.
