### ISSUE TITLE
distributed engine inserts exceed memory, even if there is no limit set

### ISSUE THREAD

**Issue by Nikoslav** [ClickHouse/ClickHouse#56454]
Creating new ticket as #50744 is closed and issue is not resolved.

Background inserts into distributed tables started throwing exception:
 DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 4360448 bytes), maximum: 9.31 GiB

Even if i run SYSTEM FLUSH DISTRIBUTED ON CLUSTER cluster default.table, i get the same error.

Inserts on local node work ok. It also works ok with insert_distributed_sync=1. But as i would prefer to use async, i would like to go back to background inserts.

Memory limits are the same on all nodes:
```
┌─name─────────────────────────────┬─default─┬─value─┐
│ max_memory_usage                 │ 0       │ 0     │
│ max_memory_usage_for_user        │ 0       │ 0     │
│ max_memory_usage_for_all_queries │ 0       │ 0     │
└──────────────────────────────────┴─────────┴───────┘
```

system.distribution_queue has 2 entries(1 for each node it is trying to insert to). 
data_compressed_bytes: 9692170902

Each shard has a queue of around 13k files, ~10G in size. Even if i leave just 1 file in the queue, it still throws memory exceeded.
If i remove the first file, i get file not found exception.

How do i tell clickhouse to not use 10G memory limit?

**Comment by den-crane** [comment]
it's because `.bin` file stores settings which were applied during initial insertion and distributed table apply them during propagation.

Here is an example

```
create table T ( A Int64 ) Engine MergeTree partition by A order by A;

create table TD as T Engine Distributed (default, currentDatabase(), T);

set prefer_localhost_replica = 0;
set max_partitions_per_insert_block = 1;

insert into TD select * from numbers(100);

select substr(last_exception,1, 150) from system.distribution_queue format Vertical;

substring(last_exception, 1, 150): Code: 252. DB::Exception: Received from localhost:9000. DB::Exception: Too many partitions for single INSERT block (more than 1).
```

Now TD is unable to re-insert `1.bin` and it's impossible to change `1.bin` to redefine `max_partitions_per_insert_block`. 

you can:

* recreate table TD (drop/create and lost all not inserted data, all .bin files)
* detach table, move bin files to user_files and try to read them

```
:) detach table TD;

# cd /var/lib/clickhouse/data/dw/TD/shard1_replica1/

# mv *.bin /var/lib/clickhouse/user_files/

:) attach table TD;

-- data is accessible using `Distributed` format
:) select * from file('*.bin', Distributed) limit 3
┌─A─┐
│ 0 │
│ 1 │
│ 2 │
└───┘

:) select count() from file('*.bin', Distributed);
┌─count()─┐
│     100 │
└─────────┘

:) insert into T select * from file('*.bin', Distributed);

:) select count() from T;
┌─count()─┐
│     100 │
└─────────┘

# rm /var/lib/clickhouse/user_files/*.bin
```

**Comment by den-crane** [comment]
Also you can do this

```
create table TDNew as TD Engine Distributed (default, currentDatabase(), T);
exchange tables TDNew and TD;
```
then not inserted .bin files will be in TDNew (/var/lib/clickhouse/data/default/TDNew/shard1_replica1/)

**Comment by Nikoslav** [comment]
Thanks a lot! Detach, move files, attach and insert worked perfectly.
