### ISSUE TITLE
Materialized views are based on distributed tables but have no data

### ISSUE THREAD

**Issue by cheungfeifu** [ClickHouse/ClickHouse#56451]
### OS
OS:Ubuntu 20
ck version: ClickHouse client version 23.8.2.7 (official build)
### How to reproduce：

local table

```SQL
CREATE TABLE ods_vm.local_table_test (
    `dt` Date DEFAULT CAST(now(), 'Date'),
    `dt_insert` DateTime DEFAULT now(),
    `hostName` String,
    `xxxx` String,
    `xxxx` Int64,
    `xxxxxxx` String,
    `xxxxxx` String,
    `xxxxxxx` String,
    `xxxxxxx` String,
    `xxxxxxx` String,
    `xxxxxxx` Float64,
    `xxxxxxx` String,
    `xxxxxxx` String,
    `xxxxxxx` String,
    `dogTime` String,
    `objName` String,
    `sca_zone` String
) ENGINE = ReplicatedMergeTree(
    '/clickhouse/tables/{shard}/local_table_test',
    '{replica}'
) PARTITION BY dt
ORDER BY
    (dt, dt_insert, dogTime) TTL dt + toIntervalMonth(4) SETTINGS index_granularity = 8192;
```

Distributed table

```SQL
CREATE TABLE ods_vm.local_table_test_all
(
    `dt` Date DEFAULT CAST(now(), 'Date'),
    `dt_insert` DateTime DEFAULT now(),
    `hostName` String,
    `xxxx` String,
    `xxxx` String,
    `xxxx` Int64,
    `xxxx` String,
    `xxxx` String,
    `xxxx` String,
    `xxxx` String,
    `xxxx` String,
    `xxxx` Float64,
    `xxxx` String,
    `mac_addr` String,
    `action` String,
    `dogTime` String,
    `objName` String
)
ENGINE = Distributed('cluster_3shards_2replicas', 'ods_vm', 'local_table_test', javaHash(podName))  
```

MATERIALIZED VIEW 

```SQL
CREATE MATERIALIZED VIEW dw_vm.local_table_test_15m TO dm_vm.local_table_test_15m
(
    `dt` DateTime('Asia/Shanghai'),
    `zone` String,
    `parentName` String,
    `objName` String,
    `avg_value` AggregateFunction(avg, Float64)
) AS
SELECT
    toStartOfFifteenMinutes(toDateTime(dogTime)) AS dt,
    zone,
    parentName,
    objName,
    avgState(value) AS avg_value
FROM ods_vm.local_table_test_all
GROUP BY
    dt,
    parentName,
    objName,
    zone
ORDER BY
    dt ASC,
    parentName ASC,
    objName ASC ;
```

Based on the local table local_table_test, a materialized view can be generated with data

**but Based on distributed tables, materialized views will not have data**

I query local_table_test_all  have new data insert

**Comment by den-crane** [comment]
If you never insert into `ods_vm.local_table_test_all` then you mat view never get data. Also there is a little sense to create a mat.view over distributed but not a ReplicatedMergeTree table.

see https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by cheungfeifu** [comment]
> If you never insert into `ods_vm.local_table_test_all` then you mat view never get data. Also there is a little sense to create a mat.view over distributed but not a ReplicatedMergeTree table.
> 
> see https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

Understand, you need to **write to a distributed table to cause the materialized view to generate new data**, right?

**Comment by den-crane** [comment]
>Understand, you need to write to a distributed table to cause the materialized view to generate new data, right?

right
