### ISSUE TITLE
Missing bitwise operator (`bitAnd`) support for IPv6 Native Type and IPv6StringToNum not compatible with IPv6 Data Type

### ISSUE THREAD

**Issue by muzammilar** [ClickHouse/ClickHouse#56487]
**Describe the issue**
* [Background/Context] As of ClickHouse 23.1 (https://github.com/ClickHouse/ClickHouse/pull/43221), the IPv6 data type is `UInt128` big-endian data type. In the versions before that (22.X), IPv6 dates not support the IPa type was a `FixedString(16)`. This feature is not listed as backwards-incomaptible in the Release docs.
* The `IPv6StringToNum` function still returns a `FixedString(16)` data type instead of an `IPv6` data type.
* Moreover the `bitAnd` operator does not support the IPv6 Data type anymore (It was supported in previous versions). `bitAnd` operator on IPv6 data type is exceptionally useful when it comes to network masking and other IP-related operations.

**How to reproduce**
* Which ClickHouse server versions are incompatible? 
    * 23.1 onwards [However, I only tested 23.3. and 23.8]

* 
    ```sql
    SELECT bitAnd(toIPv4('1.2.3.4'), 20000000); -- works correctly
    SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0')); -- works correctly
    SELECT bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')); -- does not work
    SELECT bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000'));  -- does not work
    ```

**Error message and/or stacktrace**
* ClickHouse 23.3.9

    ```sql
    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), 20000000);

    SELECT bitAnd(toIPv4('1.2.3.4'), 20000000)

    Query id: 6f2fb352-fe04-43a1-9882-a1d602e2885d

    ┌─bitAnd(toIPv4('1.2.3.4'), 20000000)─┐
    │                            16777472 │
    └─────────────────────────────────────┘

    1 row in set. Elapsed: 0.004 sec. 

    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    Query id: 24f317f1-0d8a-42b4-9d00-686161ed3f03

    ┌─bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))─┐
    │                                              16908288 │
    └───────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.005 sec. 

    myserver :) SELECT bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    SELECT bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    Query id: 3da6dc0d-0672-4d80-bc78-d5813dfc09d5


    0 rows in set. Elapsed: 0.005 sec. 

    Received exception from server (version 23.3.9):
    Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal types IPv6 and IPv6 of arguments of function bitAnd: While processing bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')). (ILLEGAL_TYPE_OF_ARGUMENT)

    myserver :) SELECT bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    SELECT bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000'))

    Query id: 4355c453-ad91-4ef7-a5ad-18aded30bf99


    0 rows in set. Elapsed: 0.005 sec. 

    Received exception from server (version 23.3.9):
    Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal types IPv6 and FixedString(16) of arguments of function bitAnd: While processing bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')). (ILLEGAL_TYPE_OF_ARGUMENT)
    ```

* ClickHouse 22.8.21

    ```sql
    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), 20000000)

    SELECT bitAnd(toIPv4('1.2.3.4'), 20000000)

    Query id: 131967d4-81d6-4304-abe6-a35d88a67115

    ┌─bitAnd(toIPv4('1.2.3.4'), 20000000)─┐
    │                            16777472 │
    └─────────────────────────────────────┘

    1 row in set. Elapsed: 0.001 sec. 

    myserver :) SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    SELECT bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))

    Query id: 91a8c219-3533-421c-9cc7-d49017a2ee01

    ┌─bitAnd(toIPv4('1.2.3.4'), IPv4StringToNum('1.2.0.0'))─┐
    │                                              16908288 │
    └───────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.002 sec. 

    myserver :) SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    Query id: b0a03283-db12-42b5-bab9-57b8ed8c42bb

    ┌─IPv6NumToString(bitAnd(toIPv6('43:AB::'), toIPv6('ffff:ffff:0000:0000:0000:0000:0000:0000')))─┐
    │ 43:ab::                                                                                       │
    └───────────────────────────────────────────────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.004 sec. 

    myserver :) SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    SELECT IPv6NumToString(bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')))

    Query id: a6625b0a-0577-4e87-a773-b34112e46753

    ┌─IPv6NumToString(bitAnd(toIPv6('43:AB::'), IPv6StringToNum('ffff:ffff:0000:0000:0000:0000:0000:0000')))─┐
    │ 43:ab::                                                                                                │
    └────────────────────────────────────────────────────────────────────────────────────────────────────────┘

    1 row in set. Elapsed: 0.003 sec. 

    ```

**Additional context**
N/A

**Comment by den-crane** [comment]
IPv4StringToNum was never intended to be used with IPv4 type.
IPv6StringToNum the same with IPv6 type.

Initially Clickhouse did not have IPv4 & IPv6. Users stored ipv4 and ipv6 addresses using UInt32 and FixedString. And they continue to do it! They use IPv4StringToNum & IPv6StringToNum to convert string representation of ip addresses to UInt32 & FixedString. 
Later Clickhouse got new datatypes IPv4 & IPv6, they has own functions toIPv4, toIPv6 and they produce correct types.

**The fact that IPv4StringToNum & IPv6StringToNum weres compatible with  IPv4 & IPv6 was a pure accident, unexpected behaviour.**

**Comment by den-crane** [comment]
it also sounds like cutIPv6 function

https://clickhouse.com/docs/en/sql-reference/functions/ip-address-functions#cutipv6x-bytestocutforipv6-bytestocutforipv4

**Comment by muzammilar** [comment]
> IPv4StringToNum was never intended to be used with IPv4 type. IPv6StringToNum the same with IPv6 type.
> 
> **The fact that IPv4StringToNum & IPv6StringToNum were compatible with IPv4 & IPv6 was a pure accident, undefined behaviour.**

That actually surprises me since both of those have been mentioned in documentation as [Functions for Working with IPv4 and IPv6 Addresses](https://clickhouse.com/docs/en/sql-reference/functions/ip-address-functions). The domain types/aliases for IPv4/IPv6 did have some nice features that had been added over the years. ClickHouse 22.3 added some decent support for the `OrNull` and the `OrDefault` functions for working with IP data types. 

> it also sounds like cutIPv6 function
> 
> https://clickhouse.com/docs/en/sql-reference/functions/ip-address-functions#cutipv6x-bytestocutforipv6-bytestocutforipv4

The `cutIPv6` function does not provide the same granularity and control for network data analytics that a `bitAnd` function does. The `bitAnd` operator provides a fine grained control in network analytics and operation. The lack of support for the `bitAnd` operator is perhaps the a big limitation for those planning to migrate off of older versions :/
