### ISSUE TITLE
Flaky test test_timezone_config

### ISSUE THREAD

**Issue by SmitaRKulkarni** [ClickHouse/ClickHouse#56495]
Tests in test_timezone_config are flaky

https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIGNoZWNrX3N0YXJ0X3RpbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19uYW1lIExJS0UgJ0ludGVncmF0aW9uJScKICAgIEFORCBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMTAwIEhPVVIKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snIAogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCB0ZXN0X25hbWUgSUxJS0UgJyV0ZXN0X3RpbWV6b25lX2NvbmZpZyUnCk9SREVSIEJZIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgY2hlY2tfc3RhcnRfdGltZQ==

**Comment by Algunenano** [comment]
No failures in over 2 months. Failures look related to docker-compose past problems.
