### ISSUE TITLE
Log entry cleanup stuck and cause log queue to increase unbounded

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#56505]
Znode count increases to over 1 million:
![image](https://github.com/ClickHouse/ClickHouse/assets/50256182/c4428f73-494a-4937-929b-b57ebee09496)

Mostly from the node:
```
[zk: localhost:2181(CONNECTED) 3] stat /clickhouse/tables/http_log_metrics_local/3/log
cZxid = 0x1b4bd2b536
ctime = Sat Oct 08 09:51:11 CST 2022
mZxid = 0x4b1ca9c5a1
mtime = Thu Nov 09 18:43:44 CST 2023
pZxid = 0x4b1ca9c72f
cversion = 15095652
dataVersion = 1734992
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 0
numChildren = 593364  <-- 0.6 million
```
There are two nodes like this, so they sum up to 1 million.

I see debug logs from clickhouse server (`alter table modify setting cleanup_delay_period=1`):
```
2023.11.09 18:53:01.470334 [ 181 ] {} <Debug> metric.`.inner.http_log_metrics_local` (ReplicatedMergeTreeCleanupThread): Removed 400 old log entries: log-0005268929 - log-0007251543
2023.11.09 18:53:09.694098 [ 122 ] {} <Debug> metric.`.inner.http_log_metrics_local` (ReplicatedMergeTreeCleanupThread): Removed 400 old log entries: log-0005268929 - log-0007251543
2023.11.09 18:53:14.028992 [ 212 ] {} <Debug> metric.`.inner.http_log_metrics_local` (ReplicatedMergeTreeCleanupThread): Removed 400 old log entries: log-0005268929 - log-0007251543
2023.11.09 18:53:24.888790 [ 189 ] {} <Debug> metric.`.inner.http_log_metrics_local` (ReplicatedMergeTreeCleanupThread): Removed 400 old log entries: log-0005268929 - log-0007251543
2023.11.09 18:53:30.170591 [ 180 ] {} <Debug> metric.`.inner.http_log_metrics_local` (ReplicatedMergeTreeCleanupThread): Removed 400 old log entries: log-0005268929 - log-0007251543
2023.11.09 18:53:34.001082 [ 209 ] {} <Debug> metric.`.inner.http_log_metrics_local` (ReplicatedMergeTreeCleanupThread): Removed 400 old log entries: log-0005268929 - log-0007251543
2023.11.09 18:53:42.704721 [ 208 ] {} <Debug> metric.`.inner.http_log_metrics_local` (ReplicatedMergeTreeCleanupThread): Removed 400 old log entries: log-0005268929 - log-0007251543
```
Note that all the entry ranges are same. Which indicates that the cleanup thread is stuck at some point between log entries : log-0005268929 - log-0007251543.

Actually, the zookeeper cluster is in inconsistent state:
![image](https://github.com/ClickHouse/ClickHouse/assets/50256182/62e77f04-d100-450c-893d-bca2b0533a2c)

So I guess this line breaks every time it got `Error::ZNONODE` from zookeeper, and thus stuck at log-0005268929:

https://github.com/ClickHouse/ClickHouse/blob/949863872af69d749bb587ae2d5d2fd68ad0329b/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp#L367-L371

**Comment by cangyin** [comment]
Restarting the zookeeper server brought the znodes back to consistency, and helped clickhouse to correctly purge out the cumulative znodes.

**Comment by tavplubix** [comment]
> Actually, the zookeeper cluster is in inconsistent state:

So it's a bug in Apache ZooKeeper, right?
