### ISSUE TITLE
Getting POSTGRESQL_CONNECTION_FAILURE error while running clickhouse query via JMeter with 50 threads (users)

### ISSUE THREAD

**Issue by jaypalsinh-odan** [ClickHouse/ClickHouse#56515]
NodeJS Framework: FeathersJS
ORM: Sequelize
Database: Postgres
Clickhouse server version: 23.10.1.764 (official build)
NodeJS package: @clickhouse/client": "^0.2.5

**Error log**
```
Error: Code: 614. DB::Exception. (POSTGRESQL_CONNECTION_FAILURE) (version 23.10.1.764 (official build))
     at parseError (/path-to-node_modules/packages/client-common/src/error/parse_error.ts:31:35)
     at ClientRequest.onResponse (/path-tonode_modules/packages/client-node/src/connection/node_base_connection.ts:143:28)
     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Clickhouse client configs**
```
const clickhouseClient = createClient({
      host: clickhouseHost,
      username: clickhouseUsername,
      password: clickhousePassword,
      database: clickhouseDBName,
      max_open_connections: 1000,
      clickhouse_settings: {
        postgresql_connection_pool_size: "1000",
        connection_pool_max_wait_ms: 10000,
        postgresql_connection_pool_wait_timeout: "10000",
      },
    });
```

**Sequelize configs**
```
pool: {
      max: 50,
      min: 0,
      acquire: 60000,
      idle: 60000,
    },
```

**Postgres configs:**
max_connections: 1000

**Comment by lampjian** [comment]
It occurrs when I use plain left join to query with more than 5 postgres tables since version 21.9. Maybe it's the limitation of postgres table engine. I think you may meet an alike scenario.

**Comment by rf** [comment]
`postgresql_connection_pool_size` probably cannot be set on client. Try setting this on the server side.

**Comment by lampjian** [comment]
After setting a higher value of `postgresql_connection_pool_size` than default 16, every thing works well. It can be configured in user profiles on server side.
