### ISSUE TITLE
Super type for Enum and String (and FixedString) can be Enum

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#56554]
> (you don't have to strictly follow this form)

**Use case**

Mainly to support writing `has`, `hasAny`, and `hasAll` on `Array(Enum)` without explicitly casting argument to enum type:

```sql
CREATE TABLE IF NOT EXISTS v (values Array(Enum('foo' = 1, 'bar' = 2))) ENGINE = Memory;
INSERT INTO v VALUES (['foo', 'bar']), (['foo']), (['bar']);
SELECT * FROM v WHERE has(values, 'foo'); -- error here
```

**Describe the solution you'd like**

When an array of types has exactly one `Enum` and the rest are either `String` or `FixedString`, the least super type could be `Enum`.

The downside: it may break the invariance that we can always cast a type to its super type. If we want to keep the invariance, we can consider the super type is `Nullable(Enum)` and change casting behaviour so that when a casting `String` to `Nullable(Enum)`, if a string doesn't match any enum values then it will be casted to `NULL`.

**Describe alternatives you've considered**

Using enum index in the SQL, but it makes the query less expressive and takes more efforts to write.

Explicitly cast in SQL. However, some enum types have hundred of values, writing explicit cast is painful.

**Additional context**

Postgres `ANY` can work directly with enum values: https://www.db-fiddle.com/f/nGaCV7iJFe7xYMK1w49QAQ/0

**Comment by alexey-milovidov** [comment]
But it is not a supertype. We don't want a wrong logic in code.

**Comment by canhld94** [comment]
> But it is not a supertype. We don't want wrong logic in code.

@alexey-milovidov then is this possible to have special conversion logic to handle `Enum` and `String` in `has` and `hasAny`?

**Comment by alexey-milovidov** [comment]
Yes, it will be ok to covert constant string to Enum inside the implementation of has/hasAny.

**Comment by UnamedRus** [comment]
> But it is not a supertype.

Do we actually need to have supertype here?

> has, hasAny, and hasAll

It's all matching/equality functions, so if values doesn't match, it always return 0.
So, we need most subtype here.

**Comment by alexey-milovidov** [comment]
You are right, let's use `getMostSubtype`
