### ISSUE TITLE
Projection Metadata is not deleted cleanly

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#56553]
>Metadata is incorrectly deleted from the projection, resulting in a new projection failure, metadata in a shard is not the same as metadata in a replica
![image](https://github.com/ClickHouse/ClickHouse/assets/20608540/c93e8f78-4b4b-49e0-bef6-f580dc032194)
>clickhouse version 22.3.6.5

>Code: 517. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. It means that this replica still not applied some of previous alters. Probably too many alters executing concurrently (highly not recommended). You can retry this error. (CANNOT_ASSIGN_ALTER) (version 22.3.6.5 (official build))

>Is it possible to add a SYSTEM command to correct projection metadata information？

**Comment by alexey-milovidov** [comment]
22.3 is obsolete. Upgrade to 23.10.
