### ISSUE TITLE
Logical error: required source after the first merge is not 0

### ISSUE THREAD

**Issue by 775838893** [ClickHouse/ClickHouse#56562]
2023.11.10 14:23:41.300741 [ 2453 ] {} <Error> MutateFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 49. DB::Exception: Logical error: required source after the first merge is not 0. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0x8e1d808 in /usr/bin/clickhouse
1. DB::MergeTreeDataWriter::mergeBlock(DB::Block const&, DB::SortDescription, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul>*&, DB::MergeTreeData::MergingParams const&) @ 0x125bde80 in /usr/bin/clickhouse
2. DB::MergeTreeDataWriter::writeProjectionPartImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeDataPartType, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder> const&, bool, DB::IMergeTreeDataPart const*, DB::MergeTreeData const&, Poco::Logger*, DB::Block, DB::ProjectionDescription const&) @ 0x125c36a0 in /usr/bin/clickhouse
3. DB::MergeTreeDataWriter::writeTempProjectionPart(DB::MergeTreeData&, Poco::Logger*, DB::Block, DB::ProjectionDescription const&, std::__1::shared_ptr<DB::IDataPartStorageBuilder> const&, DB::IMergeTreeDataPart const*, unsigned long) @ 0x125c4918 in /usr/bin/clickhouse
4. DB::PartMergerWriter::mutateOriginalPartAndPrepareProjections() @ 0x125dfa84 in /usr/bin/clickhouse
5. DB::PartMergerWriter::execute() @ 0x125f2c14 in /usr/bin/clickhouse
6. DB::MutateAllPartColumnsTask::executeStep() @ 0x125f1610 in /usr/bin/clickhouse
7. DB::MutateFromLogEntryTask::executeInnerTask() @ 0x125dbc30 in /usr/bin/clickhouse
8. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x12615424 in /usr/bin/clickhouse
9. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x126147c4 in /usr/bin/clickhouse
10. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0x8df62b8 in /usr/bin/clickhouse
11. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0x8df5ca8 in /usr/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0x8ed23f0 in /usr/bin/clickhouse
13. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0x8ed3ebc in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8ed0070 in /usr/bin/clickhouse
15. ? @ 0x8ed2f64 in /usr/bin/clickhouse
16. ? @ 0x88cc in /usr/lib64/libpthread-2.28.so
17. ? @ 0xda1ec in /usr/lib64/libc-2.28.so
 (version 22.8.8.3 (official build))

Such log happen per min,how to resolve it?

**Comment by den-crane** [comment]
Do you soft delete `delete from ...` ? 

>22.8.8.3

22.8.8.3 is out of support. You have to upgrade. Try 23.8.5.16 or 23.10.2.13.
