### ISSUE TITLE
[Query Performance]Performance Discrepancy in CK Queries with Different Field Selections 

### ISSUE THREAD

**Issue by Ronniexie** [ClickHouse/ClickHouse#56568]
Hello ClickHouse Community,

I'm currently experiencing a performance discrepancy in two similar ClickHouse queries, where the only difference is the number of selected fields. The first query with fewer fields executes significantly faster than the second query with all fields selected. 

The table is structured with PARTITION BY toYYYYMMDD(toDate(timestamp)) and ORDER BY timestamp:

version 23.2.4.10

Surprisingly, the first query scans 2.93 million rows, while the second query scans 5.79 million rows. I expected the number of scanned rows to be the same, given that the WHERE clause is identical, and only the selected fields differ.

Can anyone in the community shed light on why the number of scanned rows would differ between these two queries

Query 1:

```
SELECT timestamp AS timestamp, uuId AS uuId
FROM `business`.`log`
WHERE `ip` LIKE '10.11.%'
  AND (`timestamp` >= 1698940799)
  AND (`timestamp` <= 1699405199)
ORDER BY `timestamp` DESC
LIMIT 20;
--20 rows in set. Elapsed: 0.113 sec. Processed 2.93 million rows, 180.15 MB (25.99 million rows/s., 1.60 GB/s.)
```

Query 2:
```
SELECT *
FROM `business`.`log`
WHERE `ip` LIKE '10.11.%'
  AND (`timestamp` >= 1698940799)
  AND (`timestamp` <= 1699405199)
ORDER BY `timestamp` DESC
LIMIT 20;
--20 rows in set. Elapsed: 3.957 sec. Processed 5.79 million rows, 1.55 GB (1.46 million rows/s., 391.84 MB/s.)
```

**Comment by Ronniexie** [comment]
Additional Information:

Effect of Time Range on Query Performance:

Query 1 only takes effect when the time range is greater than 7 days; for time ranges less than or equal to 7 days, it scans the same data as Query 2.
Impact of Query Method on Scanned Data:

The performance difference occurs only when using a LIKE condition in the query. For other conditions (e.g., '=', etc.), the data scanned is essentially the same.

**Comment by den-crane** [comment]
>version 23.2.4.10 
This version is out support. Also multistage prewhere was implemented later, it might help you. You should upgrade to 23.8.16 or 23.10.2.


This is expected behaviour. 
By many reasons:
* `*` need to read / uncompress more data
* Clickhouse reads all columns for all rows even though need to read them for only 20 rows (LIMIT 20)
* PREWERE seems does not hit with LIKE in your case.

Try 

```
SELECT *
FROM `business`.`log`
PREWHERE 

  `ip` LIKE '10.11.%'
  AND (`timestamp` >= 1698940799)
  AND (`timestamp` <= 1699405199)
ORDER BY `timestamp` DESC
LIMIT 20;
```

```
SELECT *
FROM `business`.`log`
WHERE `ip` LIKE '10.11.%'
  AND (`timestamp` >= 1698940799)
  AND (`timestamp` <= 1699405199)
  and (timestamp , uuId) in (
      SELECT timestamp AS timestamp, uuId AS uuId
      FROM `business`.`log`
      WHERE `ip` LIKE '10.11.%'
        AND (`timestamp` >= 1698940799)
        AND (`timestamp` <= 1699405199)
      ORDER BY `timestamp` DESC
      LIMIT 20)
ORDER BY `timestamp` DESC
LIMIT 20;
```
