### ISSUE TITLE
Backup database on cluster fails with - CANNOT_BACKUP_TABLE

### ISSUE THREAD

**Issue by johnpptz** [ClickHouse/ClickHouse#56566]
### Environment

ClickHouse server version: 23.8.6.16
Cluster: 2 replicas x 2 shards

### Observed behavior

1. There is ClickHouse cluster with name **vcloud-ch**

```
select cluster,shard_num,shard_weight,replica_num,host_name,host_address,is_local  from system.clusters where cluster='vcloud-ch' FORMAT Markdown;
```

| cluster | shard_num | shard_weight | replica_num | host_name | host_address | is_local |
|:-|-:|-:|-:|:-|:-|-:|
| vcloud-ch | 1 | 1 | 1 | chi-vcloud-ch-vcloud-ch-0-0 | 127.0.0.1 | 1 |
| vcloud-ch | 1 | 1 | 2 | chi-vcloud-ch-vcloud-ch-0-1 | 10.3.5.30 | 0 |
| vcloud-ch | 2 | 1 | 1 | chi-vcloud-ch-vcloud-ch-1-0 | 10.3.4.80 | 0 |
| vcloud-ch | 2 | 1 | 2 | chi-vcloud-ch-vcloud-ch-1-1 | 10.3.5.195 | 0 |

2. There is database on cluster **oola_reporting_vcloud** with clustered table **events_shard**

```
show create database oola_reporting_vcloud FORMAT TabSeparated;

CREATE DATABASE oola_reporting_vcloud\nENGINE = Atomic
```

```
show create table oola_reporting_vcloud.events_shard;


 CREATE TABLE oola_reporting_vcloud.events_shard
(
    `user_id` UInt64,
    `entity_id` UInt64,
    `entity_type` String,
    `user_entity_status` String,
    `lesson_score` Float64,
    `learning_path_progress` Float64,
    `timestamp` DateTime64(3),
    `tenant_id` UInt64,
    `target_entity_id` UInt64,
    `target_entity_type` String,
    `event_name` String,
    `rating_score` Float64,
    `rating_total_entries` UInt32,
    `rating_average_score` Float64,
    `started_date` Nullable(DateTime64(3)),
    `required_count` UInt32,
    `completed_count` UInt32,
    `end_date` Nullable(DateTime64(3)),
    `expire_date` Nullable(DateTime64(3)),
    `valid_date` Nullable(DateTime64(3)),
    `achievement_date` Nullable(DateTime64(3))
)
ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/oola_reporting_vcloud/events_shard', '{replica}')
PARTITION BY toYYYYMM(timestamp)
PRIMARY KEY (tenant_id, user_id)
ORDER BY (tenant_id, user_id)
SETTINGS index_granularity = 8192
```

3. Database backup on the cluster fails with the error - CANNOT_BACKUP_TABLE

```
backup database oola_reporting_vcloud ON CLUSTER '{cluster}' TO Disk('backups', 'oola_reporting_vcloud-2023-11-10-0');

Query id: ebc35907-63fb-437d-a10c-42b1807209b6

Received exception from server (version 23.8.6):
Code: 647. DB::Exception: Received from localhost:9000. DB::Exception: Got error from chi%2Dvcloud%2Dch%2Dvcloud%2Dch%2D1%2D1:9000. DB::Exception: Table oola_reporting_vcloud.events_shard on replica chi-vcloud-ch-vcloud-ch-1-0 has part 201603_0_2_3 different from the part on replica chi-vcloud-ch-vcloud-ch-0-0 (checksum '2fb86be5208b5b5223e36600df06dc04' on replica chi-vcloud-ch-vcloud-ch-1-0 != checksum '8eedc42de3bed4506c915d26a38f9a49' on replica chi-vcloud-ch-vcloud-ch-0-0). (CANNOT_BACKUP_TABLE)
```

It is obviously that the replica **chi-vcloud-ch-vcloud-ch-1-0** has part 201603_0_2_3 different from the part on replica **chi-vcloud-ch-vcloud-ch-0-0**. 
This is because **chi-vcloud-ch-vcloud-ch-1-0** and **chi-vcloud-ch-vcloud-ch-0-0** belong to different shards.

```
chi-vcloud-ch-vcloud-ch-0-0 :) 

SELECT partition,name,min_block_number,max_block_number,hash_of_all_files,active FROM system.parts where database='oola_reporting_vcloud' and table='events_shard' limit 5 FORMAT Markdown;
```

| partition | name | min_block_number | max_block_number | hash_of_all_files | active |
|:-|:-|-:|-:|:-|-:|
| 201603 | 201603_0_2_3 | 0 | 2 | 8eedc42de3bed4506c915d26a38f9a49 | 1 |
| 201604 | 201604_0_4_2 | 0 | 4 | e4176bca77250c069719730bfed4119c | 1 |
| 201605 | 201605_0_10_4 | 0 | 10 | dcd5f0992c53db7c197e7deb006d3a54 | 1 |
| 201606 | 201606_0_27_7 | 0 | 27 | 8932508550d74340b17b8528ee3aadf5 | 1 |
| 201607 | 201607_0_2_2 | 0 | 2 | c2fb0f70dfdeb11f35db2163d7d4eeca | 1 |

```
chi-vcloud-ch-vcloud-ch-1-0 :)
SELECT partition,name,min_block_number,max_block_number,hash_of_all_files,active FROM system.parts where database='oola_reporting_vcloud' and table='events_shard' limit 5 FORMAT Markdown;
```

| partition | name | min_block_number | max_block_number | hash_of_all_files | active |
|:-|:-|-:|-:|:-|-:|
| 201603 | 201603_0_2_3 | 0 | 2 | 2fb86be5208b5b5223e36600df06dc04 | 1 |
| 201604 | 201604_0_3_2 | 0 | 3 | 0fd2b5819d777b0cda63b1da631ba825 | 1 |
| 201605 | 201605_0_2_2 | 0 | 2 | a0193ff721bb27c65bd839efb23240fd | 1 |
| 201606 | 201606_0_23_6 | 0 | 23 | c96f39586a4ca715087eba5f228c59b3 | 1 |
| 201608 | 201608_0_26_6 | 0 | 26 | d989729e72e415fe157ea77eae118a56 | 1 |

**Comment by vitlibar** [comment]
This is unexpected. While making a backup ClickHouse checks checksums independently for each `table_shared_id`.
This `table_shared_id` is stored in ZooKeeper at path `<replicated_table_zk_path>/table_shared_id`.

So for your table
`/clickhouse/{installation}/{cluster}/tables/{shard}/oola_reporting_vcloud/events_shard/table_shared_id`
must be diffirent for different shards.

**Comment by johnpptz** [comment]
I've checked Zookeeper and observed the following.

```
get /clickhouse/vcloud-ch/vcloud-ch/tables/0/oola_reporting_vcloud/events_shard/table_shared_id
78c106b9-1023-4419-8b77-3f020d5cb27a
```
 
```
get /clickhouse/vcloud-ch/vcloud-ch/tables/1/oola_reporting_vcloud/events_shard/table_shared_id
78c106b9-1023-4419-8b77-3f020d5cb27a
```


 Is it possible to change the shard ID for existing tables to make them different?

**Comment by vitlibar** [comment]
I've checked that deeper - it seems `table_shared_id` are in fact quite likely to be the same for different shards of the same table. So this check for `table_shared_id` in the code is just not correct. This is a bug and I'll fix it.
