### ISSUE TITLE
Error in `multiSearchAny` function.

### ISSUE THREAD

**Issue by shabir1** [ClickHouse/ClickHouse#56560]
I am getting an error in the `multiSearchAny` function.
When I provided a huge list of more than 250 elements it failed with the below error. 
```
Code: 42. DB::Exception: Number of arguments for function multiSearchAny doesn't match: passed 562, should be at most 255. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH) (version 23.8.3.48 (official build))
```
If there is a limit in the `multiSearchAny`  function then how to increase the limit?

**Comment by cangyin** [comment]
> should be at most 255

This is a hard limit and can not be changed.
