### ISSUE TITLE
Show uncompressed size in `system.tables`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56618]
Add column `total_bytes_uncompressed` showing the uncompressed size of data and indices.

The information can be obtained from data parts' checksums.

**Comment by chenlx0** [comment]
I would like to try to add this :)

**Comment by alexey-milovidov** [comment]
@chenlx0 Thank you! This will be very appreciated!

**Comment by alexey-milovidov** [comment]
This
