### ISSUE TITLE
Materialize views not appending data after deduplicating in dependant table

### ISSUE THREAD

**Issue by jrdi** [ClickHouse/ClickHouse#56642]
This issue is replicated in the stateless test  `02912_ingestion_mv_deduplication`.

Having the following tables:

```sql
CREATE TABLE landing
(
    time DateTime,
    number Int64
)
Engine=ReplicatedReplacingMergeTree('/clickhouse/' || currentDatabase() || '/landing/{shard}/', '{replica}')
PARTITION BY toYYYYMMDD(time)
ORDER BY time;

CREATE MATERIALIZED VIEW mv
ENGINE = ReplicatedSummingMergeTree('/clickhouse/' || currentDatabase() || '/mv/{shard}/', '{replica}')
PARTITION BY toYYYYMMDD(hour) ORDER BY hour
AS SELECT
    toStartOfHour(time) AS hour,
    sum(number) AS sum_amount
FROM landing
GROUP BY hour;
```

If you append to `landing` using the following insert, everything works fine:

```sql
INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42);
```

Then, if you append the same row (duplicated block in partition `20220901`) and another completely new (to a different partition) as in:

```sql
INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42),('2023-09-01 12:23:34', 42);
```

For landing table:
- The first block (partition `20220901`) gets correctly deduplicated and not inserted
- The second block (partition `20230901`) gets inserted

For mv:
- Somehow, both blocks get discarded when the expectation is for both to go through unless deduplication on materialized views is enabled (`deduplicate_blocks_in_dependent_materialized_views = 1`)

**Affected versions**

This bug affected versions from 21.9 and earlier until [this PR](https://github.com/ClickHouse/ClickHouse/pull/34780) was added. Somehow, the changes introduced in that PR mitigated the issue when `max_insert_delayed_streams_for_parallel_write < blocks`.

The bug is still there and could affect S3 setups since `max_insert_delayed_streams_for_parallel_write` should be set as 1000 in those setups.

It also affects setups where `max_insert_delayed_streams_for_parallel_write` is set to big enough values.

**Comment by jrdi** [comment]
I didn't realize it at the beginning but even when setting `deduplicate_blocks_in_dependent_materialized_views = 1` (or 0) the deduplication is working wrong:

- Inserting the same two times gets data once in landing and mv:

```sql
SET deduplicate_blocks_in_dependent_materialized_views = 0, max_insert_delayed_streams_for_parallel_write = 0;

INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42);
INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42);

-- Landing
┌────────────────time─┬─number─┐
│ 2022-09-01 12:23:34 │     42 │
└─────────────────────┴────────┘
-- MV
┌────────────────hour─┬─sum_amount─┐
│ 2022-09-01 12:00:00 │         42 │
└─────────────────────┴────────────┘
```

But when doing and insert with one block duplicated and another not duplicated, then mv receives duplicated data:

```sql
SET deduplicate_blocks_in_dependent_materialized_views = 0, max_insert_delayed_streams_for_parallel_write = 0;

INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42);
INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42),('2023-09-01 12:23:34', 42);

-- Landing
┌────────────────time─┬─number─┐
│ 2022-09-01 12:23:34 │     42 │
│ 2023-09-01 12:23:34 │     42 │
└─────────────────────┴────────┘
-- MV
┌────────────────hour─┬─sum_amount─┐
│ 2022-09-01 12:00:00 │         84 │
│ 2023-09-01 12:00:00 │         42 │
└─────────────────────┴────────────┘
```

I think this is something unexpected also. What do you think?

**Comment by CheSema** [comment]
I think it is fixed now after https://github.com/ClickHouse/ClickHouse/pull/66144.

All that examples in `tests/queries/0_stateless/02912_ingestion_mv_deduplication.sql`  now produces the answer
```
-- Landing
2022-09-01 12:23:34	42
2023-09-01 12:23:34	42
-- MV
2022-09-01 12:00:00	84
2023-09-01 12:00:00	42
```

**Comment by jrdi** [comment]
@CheSema the answer is wrong, isn't it?

```sql
-- Landing
2022-09-01 12:23:34	42
2023-09-01 12:23:34	42
-- MV
2022-09-01 12:00:00	84
2023-09-01 12:00:00	42
```

If some do these inserts:

```
INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42);
INSERT INTO landing VALUES ('2022-09-01 12:23:34', 42),('2023-09-01 12:23:34', 42);
```

I'd expect the same level of deduplication in landing and MVs. In other words, why `('2022-09-01 12:23:34', 42)` gets deduplicated in the landing but inserted in the MV?

**Comment by CheSema** [comment]
Because you do not set 'insert_deduplication_token'. Without 'insert_deduplication_token' it works like that.
landing table does deduplication in each partition by the hash of part. And it does it correct.
MV table does deduplication by the hashed from input block, you have different input data, there is nothing to deduplicate.

**Comment by jrdi** [comment]
Thanks @CheSema. Agree with you, the weirdest thing is in the landing. The purpose of deduplication is deduplicate same inserts and not what's happening due to the partitioning.

If passing the token does the job then it's all good for my use cases.
