### ISSUE TITLE
How to get current queries to max_concurrent_queries？

### ISSUE THREAD

**Issue by Malibu351** [ClickHouse/ClickHouse#56659]
I encountered this error：
```
clickhouse_driver.errors.ServerException: Code: 202.
DB::Exception: Too many simultaneous queries. Maximum: 200. Stack trace:
```

but I have adjusted the max_concurrent_queries from 100 to 200.

I need to know the current number of queries. If it is about to exceed the max_concurrent_queries, the program will no longer search but wait.
But I have looked at the indicators in the system.metrics, system.events, and system.asynchronous_metrics tables and no suitable monitoring indicators were found.

Please help me, I want to achieve the maximum number of searches within the current max_concurrent_queries allowed range of clickhouse.

**Comment by Malibu351** [comment]
I tried monitoring with `SELECT count(*) as cnt FROM system.processes`, but the result never exceeded 20 until the error occurred. Could it be that a certain query momentarily spiked to over 200? Should I use a different method to monitor this, or is there another approach I should consider for tracking query counts more effectively?

**Comment by den-crane** [comment]
try this

```
select * from system.metrics where metric = 'Query';
┌─metric─┬─value─┬─description─────────────────┐
│ Query  │     1 │ Number of executing queries │
└────────┴───────┴─────────────────────────────┘
```

>but the result never exceeded 20 until the error occurred. Could it be that a certain query momentarily spiked to over 200

It looks like Clickhouse server is locked up. What Clickhouse version do you use?

**Comment by Malibu351** [comment]
@den-crane the version is 23.4.2.11. I tryed `select * from system.metrics where metric = 'Query';`,But until the problem occurred, the query results did not exceed 5

**Comment by Malibu351** [comment]
I tryed this: `select * from system.metrics where metric like '%Connection%';`, I found that `Too many simultaneous queries` will occur when `TCPConnection `exceeds 500, but I don’t know what the relationship between the 200 set by `max_concurrent_queries` and `TCPConnection `is. I will use `TCPConnection `to control query congestion for the time being.

**Comment by den-crane** [comment]
Check Clickhouse logs and system.trace_log table and https://kb.altinity.com/altinity-kb-useful-queries/debug-hang/

**Comment by Malibu351** [comment]
> Check Clickhouse logs and system.trace_log table and https://kb.altinity.com/altinity-kb-useful-queries/debug-hang/ https://kb.altinity.com/altinity-kb-queries-and-syntax/trace_log/

I think I have found the problem, because my different scripts will create different classes, and each class will create a new clickhouse connection, causing the TCPconnection to increase. If you use a globally unified clickhosue connection, this problem will not occur, but multiple connections will This will result in more parallel SQL. I have found a way to control it, thank you for your reply
