### ISSUE TITLE
Net Exception: Cannot assign requested address when trying to insert data from the s3 storage

### ISSUE THREAD

**Issue by Selfeer** [ClickHouse/ClickHouse#56678]
**Description**

When I try to insert data into a table from the s3 storage 

```sql
INSERT INTO zero_copy_replication SELECT * FROM s3('https://clickhouse-public-datasets.s3.amazonaws.com/ontime/csv_by_year/{1987..2023}csv.gz', CSVWithNames) SETTINGS max_insert_threads = 40, receive_timeout=600, max_memory_usage=0;
```
I get the exception shown below.  I use globs to set the range of files to get from the s3 bucket and notably this error does not appear when I try to do the same thing on the ClickHouse 23.3

**Error message and/or stacktrace**

```
Code: 499. DB::Exception: Received from localhost:9000. DB::Exception: Message: Poco::Exception. Code: 1000, e.code() = 99, Net Exception: Cannot assign requested address
```
ClickHouse version where the fail occurs: 23.8.5.16
ClickHouse version where the fail does not occur: 23.3.16.7

**Comment by SaltTan** [comment]
What about the latest release? 
Could you provide a link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/)?

**Comment by mateng0915** [comment]
we also facing the same error
here is the stack
2023.11.21 16:32:50.229133 [ 341 ] {0ab40b2d-f2527ab7f2c34c2ebe38122f6fe65061} <Error> AWSClient: Failed to make request to: http://10.180.128.206/sg-regdi-ck-di-metamart-test/data/ldxqxzvekrxtfeboxpeymiccsmjxgwei: Poco::Exception. Code: 1000, e.code() = 99, Net Exception: Cannot assign requested address: 10.180.128.206:80, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15a4c43a in /home/clickhouse/programs/clickhouse
1. Poco::IOException::IOException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x15a56ea9 in /home/clickhouse/programs/clickhouse
2. Poco::Net::NetException::NetException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x1592fc89 in /home/clickhouse/programs/clickhouse
3. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x15939dde in /home/clickhouse/programs/clickhouse
4. Poco::Net::SocketImpl::connect(Poco::Net::SocketAddress const&, Poco::Timespan const&) @ 0x1593a4fd in /home/clickhouse/programs/clickhouse
5. Poco::Net::HTTPSession::connect(Poco::Net::SocketAddress const&) @ 0x15922bf1 in /home/clickhouse/programs/clickhouse
6. Poco::Net::HTTPClientSession::reconnect() @ 0x159180d6 in /home/clickhouse/programs/clickhouse
7. Poco::Net::HTTPClientSession::sendRequest(Poco::Net::HTTPRequest&) @ 0x159176b1 in /home/clickhouse/programs/clickhouse
8. DB::S3::PocoHTTPClient::makeOneRequestAttemptImpl(unsigned int, Aws::Http::HttpRequest&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::shared_ptr<DB::S3::PocoHTTPResponse>&, Poco::Logger*) const @ 0x11f6908f in /home/clickhouse/programs/clickhouse
9. DB::S3::PocoHTTPClient::makeOneRequestAttempt(unsigned int, Aws::Http::HttpRequest&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::shared_ptr<DB::S3::PocoHTTPResponse>&, Poco::Logger*) const @ 0x11f682c3 in /home/clickhouse/programs/clickhouse
10. DB::S3::PocoHTTPClient::makeRequestInternal(Aws::Http::HttpRequest&, std::__1::shared_ptr<DB::S3::PocoHTTPResponse>&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const @ 0x11f67837 in /home/clickhouse/programs/clickhouse
11. DB::S3::PocoHTTPClient::MakeRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::Utils::RateLimits::RateLimiterInterface*, Aws::Utils::RateLimits::RateLimiterInterface*) const @ 0x11f67729 in /home/clickhouse/programs/clickhouse
12. Aws::Client::AWSClient::AttemptOneRequest(std::__1::shared_ptr<Aws::Http::HttpRequest> const&, Aws::AmazonWebServiceRequest const&, char const*, char const*, char const*) const @ 0x15b0993c in /home/clickhouse/programs/clickhouse
13. Aws::Client::AWSClient::AttemptExhaustively(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @ 0x15b0760c in /home/clickhouse/programs/clickhouse
14. Aws::Client::AWSClient::MakeRequestWithUnparsedResponse(Aws::Http::URI const&, Aws::AmazonWebServiceRequest const&, Aws::Http::HttpMethod, char const*, char const*, char const*) const @ 0x15b0cac4 in /home/clickhouse/programs/clickhouse
15. Aws::S3::S3Client::GetObject(Aws::S3::Model::GetObjectRequest const&) const @ 0x15b9b52f in /home/clickhouse/programs/clickhouse
16. DB::ReadBufferFromS3::initialize() @ 0x125a0dd9 in /home/clickhouse/programs/clickhouse
17. DB::ReadBufferFromS3::nextImpl() @ 0x1259ff44 in /home/clickhouse/programs/clickhouse
18. DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x125949b4 in /home/clickhouse/programs/clickhouse
19. DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x125947ef in /home/clickhouse/programs/clickhouse
20. DB::ReadBufferFromRemoteFSGather::readInto(char*, unsigned long, unsigned long, unsigned long) @ 0x1259464f in /home/clickhouse/programs/clickhouse
21. std::__1::__packaged_task_func<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0, std::__1::allocator<DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0>, DB::IAsynchronousReader::Result ()>::operator()() @ 0x12593438 in /home/clickhouse/programs/clickhouse
22. std::__1::packaged_task<DB::IAsynchronousReader::Result ()>::operator()() @ 0x120c780e in /home/clickhouse/programs/clickhouse
23. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa430ada in /home/clickhouse/programs/clickhouse
24. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xa433667 in /home/clickhouse/programs/clickhouse
25. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa42f11a in /home/clickhouse/programs/clickhouse
26. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) @ 0xa431b4e in /home/clickhouse/programs/clickhouse
27. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
28. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so

**Comment by mateng0915** [comment]
> I get the exception shown below. I use globs to set the range of files to get from the s3 bucket and notably this error does not appear when I try to do the same thing on the ClickHouse 23.3

BTW this error can occur in version 22.3.13.1 and 23.3.3.1

**Comment by nickitat** [comment]
pls check `cat /proc/sys/net/ipv4/ip_local_port_range`
