### ISSUE TITLE
`test_ttl_move/test.py::test_alter_with_merge_work` is flaky

### ISSUE THREAD

**Issue by evillique** [ClickHouse/ClickHouse#56686]
https://s3.amazonaws.com/clickhouse-test-reports/56493/4ac3dcc417bb629c9731aa7447d030aabf56b5a3/integration_tests__tsan__[5_6].html

CI DB: [link](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X2FsdGVyX3dpdGhfbWVyZ2Vfd29yaycgQVMgbmFtZV9zdWJzdHIsCiAgICA5MCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

**Comment by tavplubix** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/58520/491df7bf6e7d8321d2694d76c522f1520871326d/integration_tests__tsan__[5_6].html

**Comment by Algunenano** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/65689/cfc004ee6f478716811227eaaf2caba5a81f8561/integration_tests__tsan__[5_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel5_0.log

```
>               assert check_used_disks_with_retry(node1, name, set(["external"]), 100)
E               AssertionError: assert False
E                +  where False = check_used_disks_with_retry(<helpers.cluster.ClickHouseInstance object at 0x7fd6a92b7e20>, 'mt_test_alter_with_merge_work_1719374512', {'external'}, 100)
E                +    where {'external'} = set(['external'])
```

**Comment by alexey-milovidov** [comment]
It failed! https://s3.amazonaws.com/clickhouse-test-reports/66506/43eab9dd66a8b31eec308d106fd0ed920e447494/integration_tests__tsan__[5_6].html
