### ISSUE TITLE
play.clickhouse.com refuses x25519 group for tls connections.

### ISSUE THREAD

**Issue by hodzanassredin** [ClickHouse/ClickHouse#56681]
How to reproduce using openssl client

`openssl s_client -cipher 'ECDHE-RSA-AES128-GCM-SHA256' -tls1_2 -groups x25519 -connect play.clickhouse.com:443
`

RESULT

> CONNECTED(00000003)
> 40E733E9437F0000:error:0A000410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1586:SSL alert number 40
> 

EXPECTED RESULT

Connection without tls alert.

**Comment by alexey-milovidov** [comment]
Why should it work?

**Comment by hodzanassredin** [comment]
this group(x25519) was working in the sandbox(play.clickhouse.com) some time ago, at the moment it has stopped. This group still supported by web servers and used in strong ciphers. Why it was disabled on playground?

**Comment by hodzanassredin** [comment]
Just some clarification. We have an os and language, but doesn't have native ch driver. So we need to use https. Unfortunately we have an outdated implementation of tls v1.2. I've spent some time adding ecdhe and GCM/AEAD and now we can connect to many servers in internet. And only X22519 group is implemented now. It is quite time consuming to add more groups. So I just need to know why it was disabled, by mistake or by some reasons. Could you point me to a group which is more appropriate for ch/playground?

**Comment by hodzanassredin** [comment]
JFYI
malware.news/t/everyone-loves-curves-but-which-elliptic-curve-is-the-most-popular/17657

**Comment by alexey-milovidov** [comment]
Maybe it is related to the Let's Encrypt certificates that we use?

**Comment by hodzanassredin** [comment]
No, tls handshake occurs before certificates exchange. I suppose it depends on web server settings. I've just checked group P-521 and it doesn't work too. But prime256v1 works.
All groups work fine on clickhouse.com(cloudflare).

**Comment by hodzanassredin** [comment]
As far as I can see in clickhouse's source cod, settings suppose that only one group can be selected.  Probably it is better to support several curves at the same time. mta.openssl.org/pipermail/openssl-dev/2017-October/009802.html

**Comment by hodzanassredin** [comment]
Quote of link above. Looks the same as /ClickHouse/base/poco/NetSSL_OpenSSL/src/Context.cpp

> Thanks for the hint.  The problem is fixed.
> 
> Server was setting:
> 
>             if (SSL_CTX_set1_groups_list(ctx, "X25519:P-256") == 0) {
>             //
>             }
> 
> The call succeeds.
> 
> But the old TLS 1.2 code was setting:
> 
>             int nid = NID_X9_62_prime256v1;
>             EC_KEY* ecdh = EC_KEY_new_by_curve_name(nid);
>             if (ecdh == NULL)
>             {
>                //error
>             }
>             SSL_CTX_set_tmp_ecdh(ctx, ecdh);
> 
> After disabling this, the server responds with the right group - X25519.

**Comment by alexey-milovidov** [comment]
https://play.clickhouse.com/ is the Playground that I created and am managing.
While there could be some feature requests for Playground, they are irrelevant to ClickHouse itself.

**Comment by hodzanassredin** [comment]
Main problem: it is not possible to setup more than one group on server. So in some rare cases it could be problematic.
