### ISSUE TITLE
INSERT restrictions for CollapsingMergeTree engines

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#56701]
Collapsing table engines have special column responsible for `Sign` logic. During background merges we collapse rows based on the sign value and strictly check that it's either -1 or +1. However it's not restricted to insert any value into this column, so user can easily break table and have impossible merges. The proposal is to add internal constraint which doesn't allow insert any value into Sign column except -1 and +1.

Also we need to check that it's not allowed to change Sign value with mutations.

**Comment by kevinmingtarja** [comment]
Hi @alesapin, I'd like to contribute to this.

And since this is my first time contributing, do you have any pointers on where to start (which part of the code to look at, etc)? Thanks in advance.

**Comment by alesapin** [comment]
@kevinmingtarja Hi, yes, it's great if you can take it. 
We have basic developer instructions here: https://clickhouse.com/docs/en/development/developer-instruction
Our codebase is quite large, but this change should be relatively small and touch only parts related to storage and implicit constraints.
So we check constraints here https://github.com/ClickHouse/ClickHouse/blob/3e26161eaa48353fb3f1d0f6df0f2e848123f512/src/Interpreters/InterpreterInsertQuery.cpp#L350-L353. 
Implicit constraint can be added somewhere here https://github.com/ClickHouse/ClickHouse/blob/3e26161eaa48353fb3f1d0f6df0f2e848123f512/src/Storages/MergeTree/registerStorageMergeTree.cpp#L601-L605.

Also I recommend to do it with setting which is disabled by default: https://github.com/ClickHouse/ClickHouse/blob/3e26161eaa48353fb3f1d0f6df0f2e848123f512/src/Storages/MergeTree/MergeTreeSettings.h. Something like `add_implicit_sign_column_constraints_for_collapsing_engine`.

**Comment by kevinmingtarja** [comment]
Understood, thank you for the detailed explanation! I will get started.
