### ISSUE TITLE
Bug in ALTER TABLE ... DROP PARTITION ... ON CLUTER

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#5670]
**Describe the bug**
Introduced in https://github.com/yandex/ClickHouse/commit/f47e3292e1c08e3bd24007e8a9b54aa82158860a .
Bug reproduces if the query has been executed on follower replica before leader replica. It seems to me like the main problem is https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/DDLWorker.cpp#L668 because this flag is actually unused https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/DDLWorker.cpp#L743. Logic of this function seems strange and I think the good fix is implementation of separate queue for leader tasks https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/StorageReplicatedMergeTree.cpp#L3946.

**Comment by alesapin** [comment]
Will try to fix here https://github.com/yandex/ClickHouse/pull/5757.

**Comment by shangshujie365** [comment]
@alesapin , In old code, 'drop partition' is send to leader replica, can you give us some example why the old should be changed? Because our ch is a little old(19.5), and we want to add this patch to our ch release in case some bugs occur.

**Comment by alesapin** [comment]
Bug fixed in all versions after 19.9.
