### ISSUE TITLE
`01280_ttl_where_group_by` failed on PRs

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#56719]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

CI test `01280_ttl_where_group_by` failed on several PRs, #53406, #55656, #54662. 

https://s3.amazonaws.com/clickhouse-test-reports/55656/7268c3bdcd90b2fa61a87e4223f951e947410968/stateless_tests__msan__[3_6].html

We cannot reproduce the incorrect results locally. It looks more like that there is something wrong that is not realated to these PRs. 

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by Algunenano** [comment]
Duplicated https://github.com/ClickHouse/ClickHouse/issues/49699
