### ISSUE TITLE
High CPU Load when merge

### ISSUE THREAD

**Issue by liuluo129** [ClickHouse/ClickHouse#5671]
i have 6 server to run clickhouse with same config, usually the load not exceed 5, every few days, one of the server load become very high, sometimes up high to 50, the server has 8 core cpu.
![image](https://user-images.githubusercontent.com/4715279/59690545-2d636280-9214-11e9-9dc0-a10d604c3551.png)
 
when i check the system.merges table, i find one merge had cost 2800 seconds
![image](https://user-images.githubusercontent.com/4715279/59690718-70253a80-9214-11e9-8d8d-ebd35a313a37.png)

the table span_20190611 has not modified for 6 days, how can i avoid this happen

**Comment by den-crane** [comment]
>one of the server load become very high

Do you have the issue with the same one server every time?
CH version
How many columns in your table?

**Comment by liuluo129** [comment]
> > one of the server load become very high
> 
> Do you have the issue with the same one server every time?
> CH version?
> How many columns in your table?

Every time only one server has problem

my CH version is v18.14.10-testing.

there is 16 columns in my table, 
```
CREATE TABLE trace_span.span_20190611 ( 
	date DateTime,  
	partitionDate Int64,  
	id String,  
	traceId String,  
	parentId String,  
	serviceName String,  
	parentServiceName String,  
	ipv4 String,  
	name String,  
	spanStatus Int8,  
	spanKind String,  
	serverKind String,  
	deepId String,  
	duration Int64,  
	timestamp Int64,  
	tags String
) 
ENGINE = MergeTree() PARTITION BY partitionDate ORDER BY (partitionDate, traceId, deepId) SETTINGS index_granularity = 8192;
```
the follow is two server's last 3 days cpu load graph
![image](https://user-images.githubusercontent.com/4715279/59729751-6c280580-9272-11e9-82ef-24937b536a10.png)
![image](https://user-images.githubusercontent.com/4715279/59729751-6c280580-9272-11e9-82ef-24937b536a10.png)

**Comment by alexey-milovidov** [comment]
CPU load is high for two reasons:
- there are only 8 cores on a server;
- data is highly compressable and large amount of CPU load is used for compression and decompression;

To mitigate the first issue you can lower the `background_pool_size` setting for profile `default` in users.xml. Recommended value is 8.

To mitigate the second issue, you should avoid using String fields for categorical data:
```
id String,  
traceId String,  
parentId String,  
ipv4 String,  
spanKind String,  
serverKind String,  
deepId String,
```
Replace these columns to integers.

**Comment by lokeshmandhare** [comment]
Hi @alexey-milovidov, We are running a Clickhouse cluster with version 21.7.4. The setup contains 3 nodes (1 shard & 3 replicas). Intermittently, we would face a similar issue, as mentioned above, during data ingestion. The background merges will consume a lot of CPU and cause the ingestion task to fail. We normally wait for background merges to complete so that the CPU utilized is reduced and we can perform data ingestion. Our setup also includes 3 EC2 instances with 8 cores each.
Does the above solution apply to us as well? I did check for the 'background_pool_size' setting in users.xml located at /etc/clickhouse-server/users.xml but was unable to find it there. Not sure why ? Am I checking the wrong xml ?
Also, we are planning to upgrade to version v23.3.7.5, is this fixed in that version?

**Comment by Ryado** [comment]
From what I see, here are the things you should look at:

* Are you batch enough events ? it’s recommended to use larger batch sizes with Bulk Inserts, or else to use async_insert. Each INSERT statement into ClickHouse will create one part, and our standard recommendation is to use batch sizes of at least 10,000 rows each, and often ideally in the range of 100,000 to 1,000,000 rows per batch (per INSERT statement) and limiting to 1 INSERT per second at maximum: https://clickhouse.com/docs/en/cloud/bestpractices/bulk-inserts

* If your INSERT batches are smaller than this, we do highly recommend using async_insert to allow the ClickHouse service to batch your INSERTs into large parts. Here are a couple of good docs on async_insert: https://clickhouse.com/docs/en/optimize/asynchronous-inserts 
https://clickhouse.com/blog/asynchronous-data-inserts-in-clickhouse

* If the above are not the cause, then it might just mean that 8 CPUs per node is not enough to handle your workload
