### ISSUE TITLE
Troubleshooting the Reason for Exceeding the Maximum Memory Limit

### ISSUE THREAD

**Issue by wang-qijia** [ClickHouse/ClickHouse#56718]
Problem description:
After running for a period of time, the memory usage exceeds 90% of the total memory. I am unsure which components are consuming the memory.

ref : https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/

1. Query asynchronous_metric_log
```
SELECT  metric, max(value) as val, formatReadableSize(val)
FROM system.asynchronous_metric_log 
WHERE event_time > '2023-11-14 08:00:10' and event_time < '2023-11-14 09:00:10' and (metric like '%Cach%' or metric like '%Mem%') and value <> 0 
group by metric  order by metric;

Query result : 
CompiledExpressionCacheBytes | 73728 | 72.00 KiB
-- | -- | --
CompiledExpressionCacheCount | 7 | 7.00 B
HashTableStatsCacheEntries | 10000 | 9.77 KiB
HashTableStatsCacheHits | 19249578 | 18.36 MiB
HashTableStatsCacheMisses | 705805 | 689.26 KiB
MarkCacheBytes | 3917662560 | 3.65 GiB
MarkCacheFiles | 473264 | 462.17 KiB
MemoryCode | 458407936 | 437.17 MiB
MemoryDataAndStack | 109528203264 | 102.01 GiB
MemoryResident | 30235824128 | 28.16 GiB
MemoryShared | 324079616 | 309.07 MiB
MemoryVirtual | 111034527744 | 103.41 GiB
OSMemoryAvailable | 3862511616 | 3.60 GiB
OSMemoryBuffers | 81846272 | 78.05 MiB
OSMemoryCached | 4262305792 | 3.97 GiB
OSMemoryFreePlusCached | 4621737984 | 4.30 GiB
OSMemoryFreeWithoutCached | 2094837760 | 1.95 GiB
OSMemoryTotal | 32841396224 | 30.59 GiB
```

2. Query system.merges
```
SELECT formatReadableSize(sum(memory_usage)) FROM system.merges;

Query result : 
1.95 GiB
```

I would like to know what is consuming the memory and impacting availability. Are there any solutions?

**Comment by cangyin** [comment]
Focusing on these two metrics, they only show that clickhouse is using 28GB out of 30GB available memory.
```
MemoryResident | 30235824128 | 28.16 GiB
OSMemoryTotal | 32841396224 | 30.59 GiB
```
So take a step further, run this query to see which task (merges, mutations, or user queries) is consuming most of your memory:

[retrospection analysis of the RAM usage based on query_log and part_log (shows peaks) ](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/#retrospection-analysis-of-the-ram-usage-based-on-query_log-and-part_log-shows-peaks)

**Comment by justindeguzman** [comment]
Here's the ClickHouse docs on debugging memory usage if it can potentially be helpful: https://clickhouse.com/docs/en/guides/developer/debugging-memory-issues

**Comment by wang-qijia** [comment]
> Focusing on these two metrics, they only show that clickhouse is using 28GB out of 30GB available memory.
> 
> ```
> MemoryResident | 30235824128 | 28.16 GiB
> OSMemoryTotal | 32841396224 | 30.59 GiB
> ```
> 
> So take a step further, run this query to see which task (merges, mutations, or user queries) is consuming most of your memory:
> 
> [retrospection analysis of the RAM usage based on query_log and part_log (shows peaks) ](https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/#retrospection-analysis-of-the-ram-usage-based-on-query_log-and-part_log-shows-peaks)

The query results are as follows, and no particularly abnormal memory usage is observed.
![image](https://github.com/ClickHouse/ClickHouse/assets/34878555/ff822a6e-78d0-4a57-8753-fa375e89ffec)

**Comment by wang-qijia** [comment]
Monitoring data for memory usage over the past month.
![image](https://github.com/ClickHouse/ClickHouse/assets/34878555/05b83544-6c45-4fc5-a4c8-2e644421e8b1)

**Comment by cangyin** [comment]
Weird. Two things to check:

1. the ClickHouse version
2. if using `inverted` index

**Comment by wang-qijia** [comment]
ClickHouse  version : 22.8.4.7
Number of tables: 60
Number of indexes:  10 per table

**Comment by den-crane** [comment]
22.8.4.7 is out of support. You should upgrade. 

Try `23.8.6.16`, there is a new feature which reduces memory impact of merges. 
* https://github.com/ClickHouse/ClickHouse/pull/49313
