### ISSUE TITLE
MOVE PARTITION TO s3 fails with 499 error

### ISSUE THREAD

**Issue by igolka97** [ClickHouse/ClickHouse#56716]
Query `ALTER TABLE table MOVE PARTITION 202309 TO DISK 's3'` fails with 499 error code.
`DB::Exception. (S3_ERROR) (version 23.5.5.92 (official build))`

**How to reproduce**
* 23.5.5.92
* HTTP interface
* `ALTER TABLE table MOVE PARTITION 202309 TO DISK 's3'`
* Dead simple `s3_cold` storage policy config from documentation example
* Background auto move by move_factor is working

**Expected behavior**
Partition moves without error

**Stacktrace:** 
```
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e491175 in /usr/bin/clickhouse
1. ? @ 0x000000001293dc4d in /usr/bin/clickhouse
2. DB::WriteBufferFromS3::createMultipartUpload() @ 0x0000000012ce29ec in /usr/bin/clickhouse
3. DB::WriteBufferFromS3::writeMultipartUpload() @ 0x0000000012cdaefb in /usr/bin/clickhouse
4. DB::WriteBufferFromS3::nextImpl() @ 0x0000000012cd9ef7 in /usr/bin/clickhouse
5. DB::WriteBufferFromFileDecorator::nextImpl() @ 0x00000000129da86f in /usr/bin/clickhouse
6. ? @ 0x000000000896985d in /usr/bin/clickhouse
7. ? @ 0x000000000e50329c in /usr/bin/clickhouse
8. DB::IDisk::copyFile(String const&, DB::IDisk&, String const&, DB::WriteSettings const&) @ 0x000000001313141e in /usr/bin/clickhouse
9. ? @ 0x00000000131352eb in /usr/bin/clickhouse
10. ? @ 0x0000000013166136 in /usr/bin/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000e56c083 in /usr/bin/clickhouse
12. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000e56e875 in /usr/bin/clickhouse
13. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000e567f14 in /usr/bin/clickhouse
14. ? @ 0x000000000e56d701 in /usr/bin/clickhouse
15. ? @ 0x00007f2091953609 in ?
16. clone @ 0x00007f2091878133 in ?
```

**Additional context**
Docker official image
Timeweb S3 storage

**Comment by den-crane** [comment]
23.5.5.92 is out of support. 
Does it reproduce with 23.8.6 ? 23.9, 23.10?

>Timeweb S3 storage

What is 'Timeweb S3 storage' ?

**Comment by den-crane** [comment]
I don't see 499 error in your error message

**Comment by igolka97** [comment]
@den-crane 

> Does it reproduce with 23.8.6 ? 23.9, 23.10?

No. Just tried on latest 23.10 and now it fails with another error: `PART_IS_TEMPORARILY_LOCKED`
I have 3 partitions by month and all of them are locked.

When I set storage policy on 23.5.5.92 it starts uploading latest 202311 part to S3, instead oldest. After CH update uploading stoped. Looks like smth went wrong. But after all some parts of latest partition is on S3, and I even cant move it back with `ALTER TABLE table MOVE PARTITION 202311 TO DISK 'default'`

**Comment by den-crane** [comment]
@igolka97 How I can reproduce it? Please explain the exact steps.

**Comment by tavplubix** [comment]
> fails with 499 error

What was the error message? You posted the stacktrace but no error message

> now it fails with another error: PART_IS_TEMPORARILY_LOCKED

What are the new error message and stacktarce?

**Comment by igolka97** [comment]
@tavplubix thanks you for your participating on my issue.

Error message was
`Code: 499. DB::Exception. (S3_ERROR) (version 23.5.5.92 (official build))`. Thats it.

New error message is
`Code: 384. DB::Exception: Cannot move part '202311_96294_96456_7' because it's participating in background process. (PART_IS_TEMPORARILY_LOCKED) (version 23.10.3.5 (official build))`

Also I discovered that my S3 integration it totally broken on 23.10. Getting smt like this in logs

```
Response status: 500, Internal Server Error
AWSErrorMarshaller: Unable to generate a proper httpResponse from the response stream.   Response code: 500
AWSXmlClient: HTTP response code: 500
If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
Request failed, now waiting 90000 ms before attempting again.
```
May be it matters. There was no any messages like this on 23.5 and integration worked.

But I guess it belongs to AWS client, i created issue ticket on my cloud provider with this issue.

**Comment by alexey-milovidov** [comment]
It is ok for S3 to return an error. In this case, ClickHouse will retry the request.
