### ISSUE TITLE
Is there any metrics that can support user-dimensional ProfileEvents?

### ISSUE THREAD

**Issue by crazyleeyang** [ClickHouse/ClickHouse#56727]
* sometimes  when a cluster have many users, we want some metrics to distinguish ProfileEvents from different initial_user. For example ClickHouseProfileEvents_SelectQuery/ClickHouseProfileEvents_FailedSelectQuery for user

**Comment by Algunenano** [comment]
There isn't, but you can build one on top of system.query_log (all queries logged contain the user and the profile events)
