### ISSUE TITLE
Multiply int128 with float64 fail

### ISSUE THREAD

**Issue by netchose** [ClickHouse/ClickHouse#56726]
Hello,

multiply int128 with float64 fail

**Describe the unexpected behaviour**

Code: 43. DB::Exception: Illegal types Int128 and Float64 of arguments of function multiply: While processing toInt128(5) * 0.001. (ILLEGAL_TYPE_OF_ARGUMENT) 

**How to reproduce**
select toInt128(5)*0.001

* Which ClickHouse server version to use
(version 23.9.1.1854 (official build)
* Which interface to use, if matters
 pycharm CH console

thanks a lot

**Comment by Algunenano** [comment]
This is expected. There isn't a supertype able to handle both Int128 and Float64. If you know the domain you can choose to cast it to whatever is appropriate to make the multiplication.
