### ISSUE TITLE
about clickhouse recover data

### ISSUE THREAD

**Issue by BJPotter** [ClickHouse/ClickHouse#56743]
During the data recovery test, I have a centralized authority of four machines, 2S2R architecture, deploy a single kepper separately, suppose one of the machines is down and cannot be recovered, I add a new server, and copy metadata and data from the replica to the new one, and also create a forcerestoredata on the new machine, there is some data loss, can you give a tutorial on data recovery?
I inserted 30 pieces of data into the distributed table, then deleted the data directory of the clickhouse of cluster1, and then inserted 30 pieces of data into the distributed table on cluster2, and then restored cluster1, at this time, cluster1 lost part of the 30 pieces of data inserted at the beginning.

**Comment by BJPotter** [comment]
It will lose some of the data, it's weird, I want a detailed tutorial on data recovery

**Comment by cangyin** [comment]
If you wanted a tool for data recovery, the native clickhouse-copier or clickhouse-backup are recomended.
If you wanted the replication mechanism of ReplicatedMergeTree to `recover` some of data from the other replica, that you manually deleted from disk, restart the replica server the ClickHouse will find some data inconsistency and download missing parts from other replicas.

ClickHouse is not aware of manually intervention on filesystem during runtime.

**Comment by den-crane** [comment]
Please provide all configs for all servers. Please provide all create table, all inserts, all selects.

>cluster2, and then restored cluster1

Why do you have 2 clusters? you said  'I have a centralized authority of four machines, 2S2R' -- it looks like a single cluster.

**Comment by BJPotter** [comment]
it's mean cluster_2shards_2replicas

**Comment by alexey-milovidov** [comment]
You should create a new, empty replica and add it to the cluster.
No need to copy any data or metadata.
Moreover, if you copied metadata from another machine, it could be a mistake, because the new machine will think that it is the same as another.
