### ISSUE TITLE
Build Docker Images for Tagged Testing Releases

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/ClickHouse#5675]
**Use case**
We would love to run the testing versions of clickhouse to provide feedback!  We use kubernetes, so need the docker image to deploy.

**Describe the solution you'd like**
The dockers are built and published to dockerhub.

**Describe alternatives you've considered**
We've tried building it from source but the build process for a release version requires logging into github and tagging something?  Didn't dig too deep here because we would prefer official builds so that we're all on the same page with the software that is running (and we are testing).

**Comment by alexey-milovidov** [comment]
CC @qoega @alesapin

**Comment by alexey-milovidov** [comment]
> We've tried building it from source but the build process for a release version requires logging into github and tagging something?

No, it does not require tagging something or similar.
Dockerfile simply installs already pre-build ClickHouse:
Simply replace this line: https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/Dockerfile#L3
and that's it.

**Comment by alexey-milovidov** [comment]
I will close as very simple workaround exists.
