### ISSUE TITLE
Configuration details to migrate BigQuery data to ClickHouse

### ISSUE THREAD

**Issue by sdsingh07** [ClickHouse/ClickHouse#56781]
In the [documentation](https://clickhouse.com/docs/en/migrations/bigquery#how-long-will-exporting-data-to-clickhouse-take) concerning the migration from BigQuery to ClickHouse, you discussed the import time in ClickHouse based on the dataset. I'm interested in knowing the specific ClickHouse configuration you used for testing. Additionally, did you configure any core settings before initiating the data ingestion into ClickHouse?

For context, I've exported data from BigQuery with a physical size of around 6.77 GB to a GCS bucket in Parquet files. The GCS bucket size is 28.98 GiB, comprising 2782 files. Despite enabling `parallel_distributed_insert_select`, the ingestion of GCS bucket data into ClickHouse is taking approximately 6-7 hours.

[Here](https://onlinetextsharing.com/untitled-3604) is the ClickHouse configuration file on my local machine.

I tested it on EKS environment with instance type `c3.4xlarge` and it is taking around 53 minutes. What is the best configuration we can set for ClickHouse?

**Comment by justindeguzman** [comment]
Hi @sdsingh07, based on [this blog post](https://clickhouse.com/blog/clickhouse-bigquery-migrating-data-for-realtime-queries), we used a setup with 720 GB of memory and 180 vCPUs. I'm not aware of any other core settings to enable besides `parallel_distributed_insert_select`, but @gingerwizard may have some insight here.
