### ISSUE TITLE
Adaptive wait time for asynchronous INSERTs.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56783]
**Use case**

Don't delay inserts if they are not frequent.
Enable asynchronous inserts by default, but without the degradation of latency in normal scenarios.

**Describe the solution you'd like**

We will use (something like) exponentially smoothed insert rate to choose the wait time in some interval.

There will be settings to control the minimum and maximum wait times: `async_insert_busy_timeout_min_ms` for the minimum and the existing setting `async_insert_busy_timeout_ms` for the maximum. We can set the minimum to something like 50 ms and the maximum to something like 1000 ms. We will also have settings for increase rate (e.g. 2 by default) and decrease rate (e.g. 2 by default).

For every asynchronous insert queue, we will record the time of the previous insert and the previously selected wait time.
The selected wait time is adjusted dynamically between the minimum and maximum wait time.

If the time after the previous insert is more than the maximum wait time, the insert will be processed immediately (synchronously), and the selected wait time will be divided by the decrease rate and clamped to the interval between minimum and maximum wait time.

If the time after the previous insert is less than the maximum wait time, the selected wait time will be multiplied by the increase rate and clamped to the interval between minimum and maximum wait time, and the insert will be put in the queue with the selected wait time.

**What to assume about this algorithm**

If the inserts happen less frequently than the maximum wait time, they will be processed immediately with no delay.
If the same is true with some exceptions (e.g. most of the time, you have less than one insert per second, but occasionally two/tree in a short sequence), they will be delayed, but not much. And if you have many frequent inserts it will collect them in batches during the desired maximum wait time.

It does not use information about how long inserts take. But it looks like we don't need it.

**Comment by qoega** [comment]
Another approach:
You can look at number of concurrent inserts syncronous or async batches. 
If this number is less than `async_insert_max_concurrency=5` your next insert is syncronous.
If your number is larger than you enable waiting and set your window to `async_insert_min_delay_ms=50`.
If you have your current `async_insert_delay_ms=200` and your infly with current delay is more than 5 you increase delay x2. 
If you current infly is `async_insert_max_concurrency=2` or less you /2 your current window size.

PS. Case when all inserts are put in a single batch and we make 1 insert at a time while we are waiting is not the best. 

Example: If we have 1 second latency to write batch and we have 1 second window we make 1 insert at a time with 1.5 expected latency per single insert. We can increase throughput to some extent by allowing more inserts to write in parallel. If we expect that 5 inserts per second is a normal load we can have 200ms window to wait and expected latency 1.1 second.

Based on this example it looks as we need to estimate average insert duration and have window size set at a level of `avg_insert_duration / target_concurrency` with some min/max limits. This computation is trivial using some fixed window of previous insert durations and logic can be easier than 
>If the time after the previous insert is less than the maximum wait time, the selected wait time will be multiplied by the increase rate and clamped to the interval between minimum and maximum wait time, and the insert will be put in the queue with the selected wait time.

**Comment by alexey-milovidov** [comment]
@qoega Your approach is based on the assumption that if we can do inserts quickly enough (say, in 100 ms), we can afford to do more frequent inserts (say, 10 in a second). But it is not necessarily true. I think frequent inserts should be collected in batches because having more transactions to Keeper and operations with storage is still bad (and costs more in object storage). That's why I think it's ok to have some fixed target, e.g., one batch per second, regardless of how many, if more, inserts the server can process.

**Comment by qoega** [comment]
In your case I expect that if you have 5 second window and 1 second insert latency you will require all the inserts to add several seconds of waiting time when nothing is actually happening and you spend more memory to collect this batch instead of writing them and freeing resources. 

If your target is 1rps after one insert you just add a delay for all other inserts for them to hit the next second and wait again.

I am really concerned about users with some fixed infly that will just stuck if average latency will increase.
