### ISSUE TITLE
`clickhouse-disks` usability improvements

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#56791]
`clickhouse-disks` is an awesome tool which allow to interact with any implementation of IDisk in ClickHouse. So if you need to list/read/remove something on remote filesystem you can use this tool in the following way:

`clickhouse-disks --config /etc/clickhouse-server/config.xml --disk s3_disk list data/table_path/detached/part`

However usability of this command is far from perfect. There are list of things to do to improve usability:
1. Tool always tries to load all disks not the disk you actually need to operate. It makes the tool super slow on startup. 
2. If you have cached disks `clickhouse-disk` refuse to start because of lock-file https://github.com/yandex/ch-backup/issues/84#issuecomment-1797996846.
3. When you have typo in command (`rm` instead of `remove` for example) `clickhouse-disk` produce unreadable error message.
4. There is no interactive mode in `clickhouse-disks`, it would be super useful to have. Look at clickhouse-keeper-client implementation.
5. Recursive copy do something strange. If you want to copy directory with nested subdirs like: 
```
all_0_0_0/columns.txt
...
all_0_0_0/projection.proj/columns.txt
...
```
(just try it).
6. For some reason operations are super super slow. It can take tens of seconds to remove a single directory.
7. Tool lack verbose mode. I really want to see what happens when I execute remove recursive.

**Comment by MikhailBurdukov** [comment]
Since the `remove` command is sequential, it can take quite a long time to execute when we are deleting big directory.  Also if object storage disk is used tthe situation becomes even more complicated. 

So maybe make sense to enable parallel execution? For example, with some knob that allows  deleting not in single transaction.
