### ISSUE TITLE
Processing split on disk is not happening in clickhouse

### ISSUE THREAD

**Issue by I-akshay** [ClickHouse/ClickHouse#5679]
Hi Community,
I have a doubt 
basically, i have two tables 1 billion records each i want to perform an inner join every time it is throwing memory limit error.
I want if ram is not available then it should move the processing to disk, unlike green plum and other databases 
Thanks

**Comment by den-crane** [comment]
Currently CH supports only in-memory JOIN, right table goes to in-memory hash table.
100 mil. table able to eat 200GB memory (depends of columns).
And nothing can be done.

**Comment by blinkov** [comment]
@I-akshay, do you have any further questions?

**Comment by I-akshay** [comment]
> @I-akshay, do you have any further questions?

No , thanks for ur support

**Comment by alexey-milovidov** [comment]
Now ClickHouse also support adaptive JOIN algorithm when data is spilled on disk when necessary.

```
SET join_algorithm = 'auto'
```
