### ISSUE TITLE
Select from system tables with cluster

### ISSUE THREAD

**Issue by fasolwbanke** [ClickHouse/ClickHouse#56806]
So we have question about this steps: 

version of clickhouse - 23.10.3.5

And we run that query 
```
SELECT
    hostname() AS replica,
    user_name,
        role_name,
        access_type,
        database,
        table,
        column,
        is_partial_revoke,
        grant_option
FROM clusterAllReplicas('{cluster}', system.grants)
ORDER BY user_name, replica
```
Thats back with error: 

`DB::Exception: default: Not enough privileges. To execute this query, it's necessary to have the grant SHOW USERS, SHOW ROLES ON *.*. (ACCESS_DENIED)`

But i run that query on my own clickhouse account with admin grants: 

```
┌─GRANTS─────────────────────┐
│ GRANT admin TO myuser
```

Thats what we gotten rules with admin role: 
```
┌─GRANTS FOR admin────────────────────────────┐
│ GRANT ALL ON *.* TO admin WITH GRANT OPTION 
```

So what we need to do, to have worked query for system tables with cluster?

**Comment by Algunenano** [comment]
> So what we need to do, to have worked query for system tables with cluster?

The user used to access the replicas is taken from [the settings](https://clickhouse.com/docs/en/sql-reference/table-functions/cluster). Do you have it declared in your cluster config? Does it change if you set `<user>myser</user>` under the cluster declaration?

**Comment by den-crane** [comment]
the user which is used in the cluster definition should have this privileges too.

Try to use `secret` https://clickhouse.com/docs/en/architecture/replication#replication-and-sharding-configuration
In case of `secret` only privileges of the query user `myuser` are used.

```
        <cluster_1S_2R>
            <secret>mysecretphrase</secret>
```
