### ISSUE TITLE
toUUID returns a NullableUUID instead of a UUID

### ISSUE THREAD

**Issue by jzbyers** [ClickHouse/ClickHouse#56812]
**Describe the unexpected behaviour**

`toUUID(x)` returns a `Nullable(UUID)` instead of a `UUID` as the docs suggest

**How to reproduce**

Set up a JDBC bridge to a Postgres database, and install the UUID extension in Postgres:
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
```

Write a simple query that generates a UUID in Postgres, and describe the results in Clickhouse:
```
describe table ( select toUUID(id) as id
                 from jdbc('postgres', "select uuid_generate_v4() as id") );
```

Execute this query using whatever client you wish (I'm using clickhouse-client here):
```
DESCRIBE TABLE
(
    SELECT toUUID(id) AS id
    FROM jdbc('postgres', `select uuid_generate_v4() as id`)
)

Query id: 368ceedd-0aa0-4273-9242-9fa20bb6ff43

┌─name─┬─type───────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ id   │ Nullable(UUID) │              │                    │         │                  │                │
└──────┴────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘

1 row in set. Elapsed: 0.160 sec.
```

**Expected behavior**

I expect a `UUID`, not a `Nullable(UUID)`.

**Comment by den-crane** [comment]
I think the problem is in bridge. https://github.com/ClickHouse/clickhouse-jdbc-bridge/issues/105

**Comment by jzbyers** [comment]
I just realized that this is happening for several other functions as well.

For instance,
```
describe table (
    select ts
    from jdbc('postgres', 'select now() as ts')
);
```
returns a `Nullable(DateTime64(6))` instead of a `DateTime64(6)`.

Even if you pass `ts` through a function that the docs say returns a `DateTime64`, you still get a Nullable type:
```
describe table (
    select toDateTime64(ts, 6) as ts
    from jdbc('postgres', 'select now() as ts')
);
```
returns a `Nullable(DateTime64(6))` too.

**Comment by jzbyers** [comment]
Thanks @den-crane, that makes sense. I'll take a look at the bridge.
