### ISSUE TITLE
Logical error: 'Part 1_3_3_0 remains in ZooKeeper after DROP_RANGE 1_0_29_999999999_999999999'

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#56819]
* Test: 01035_concurrent_move_partition_from_table_zookeeper
* Stress test report: https://s3.amazonaws.com/clickhouse-test-reports/56770/0ab93bf22f0509701aefada9da298e640417f80d/stress_test__asan_.html
* Relevant parts of `clickhouse-server.stress.log`: https://pastila.nl/?cafebabe/e03693dc63b9a88262b31fcb0ba7715d (grepped for the part name and the two relevant threads: thread 3889 did an INSERT that created the znode, thread 2630 did a DROP_RANGE that hit the error)

What appears to happen:
 1. Part 1_3_3_0 is written.
 2. It's merged into 1_3_21_1, and 1_3_3_0 is deleted (on this replica).
 3. An `ALTER TABLE ... MOVE PARTITION` creates a queue entry to drop range 1_0_29_999999999_999999999.
 4. Thread 2630 picks up this log entry, removes all parts in that range, then hesitates...
 5. Meanwhile, thread 3889 does an INSERT, detects that the new part is identical to 1_3_3_0 ("Block with ID ... already exists on other replicas as part 1_3_3_0"), creates part 1_3_3_0.
 6. Thread 2630 paranoidly re-checks that there are no parts in the dropped range, sees 1_3_3_0, throws a logical error.

How should we fix this?
 * The deduplication code path could check for covering parts in a compare-and-swap loop. I.e. `loop { list children; if the new part is covered, break; create znode conditional on the parent znode version; }`, and change all (!) code sites that add parts to also bump the parent znode version.
 * If this is strictly local to one replica, can just add a mutex to make the INSERT wait for the DROP_RANGE in this specific case.

Is there a simpler way? Is there already some mechanism for something similar in ReplicatedMergeTree?

**Comment by Algunenano** [comment]
Duplicated https://github.com/ClickHouse/ClickHouse/issues/56037

**Comment by tavplubix** [comment]
Okay, maybe it's time to remove the optimization...
But I will check why the fix didn't help
