### ISSUE TITLE
The new analyzer has a different behaviour with join/using when join-columns are renamed in the SELECT

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#56814]
https://fiddle.clickhouse.com/8f0a999f-6799-4d4e-b5cb-1d92608bee22

The new behaviour is more SQL-ansi. It uses column names from the tables not from SELECT section.
I have such queries in my production and they don't use a subquery for the left table, because in case of distributed tables it moves join to the initiator. I am going to rewrite all such queries to use `ON` instead of `USING`.

But it maybe unexpected for other users. Maybe such queries should throw an exception? Which can be fixed by the setting?

@vdimir  @kitaisreal

**Comment by vdimir** [comment]
Related to https://github.com/ClickHouse/ClickHouse/pull/56458
Sometimes we even don't have column in left table but only in SELECT list and join by it

**Comment by KochetovNicolai** [comment]
Fixed with `analyzer_compatibility_join_using_top_level_identifier`
https://fiddle.clickhouse.com/14335a47-f73a-4f05-b659-dd3428c6cb9a
