### ISSUE TITLE
bug with subquery

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#5682]
The following 2 queries must be the same result but not , and the query 2 is expected
query1:
select 
co,co2,co3,num
from (
select co,co2,co3,count() as num from (
select 1 as co,2 as co2 ,3 as co3 
) group by cube (co,co2,co3)
) 
where co!=0 
and co2 !=2

query2:
select co,co2,co3,count() as num from (
select 1 as co,2 as co2 ,3 as co3 
) group by cube (co,co2,co3)
having co!=0 
and co2 !=2

**Comment by den-crane** [comment]
set enable_optimize_predicate_expression = 0  & query1 == 2 rows
set enable_optimize_predicate_expression = 1  & query1 == 0 rows

**Comment by onine007** [comment]
thank you @den-crane

**Comment by den-crane** [comment]
in users.xml in default profile

<enable_optimize_predicate_expression>0</enable_optimize_predicate_expression>

please reopen this issue. It's real bug and should be fixed.

**Comment by alexey-milovidov** [comment]
@abyss7 

Have you failed this task?

**Comment by abyss7** [comment]
> @abyss7
> 
> Have you failed this task?

This task is just in the line with Kafka and all other assigned issues.

**Comment by den-crane** [comment]
still broken
