### ISSUE TITLE
Block structure mismatch in (columns with identical name must have identical structure) exception in version 23.3

### ISSUE THREAD

**Issue by Jack1007** [ClickHouse/ClickHouse#56823]
I have a complex view works normally in version 21.8, but it throw exception in 23.3, the exception like this :

Received exception from server (version 23.3.16):
Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) 

I had reviewed all issues and found someone had encountered similar problem, but the problem has not been solved until now in version 23.3.16.7.

This is the link to reproducer: https://fiddle.clickhouse.com/ecfbd4d4-34be-4591-9556-8fe6b6ce6221
The expect result is (yes, it works normally in version 23.8LST): https://fiddle.clickhouse.com/311318a9-1907-4ec7-8a7b-633aeb93053b
These are relevant issues: 
https://github.com/ClickHouse/ClickHouse/issues/47195
https://github.com/ClickHouse/ClickHouse/issues/42553

What can I do to fix it?

**Comment by den-crane** [comment]
I suggest to upgrade to 23.8.6.16

**Comment by mgilbir** [comment]
We just upgraded from having it working on 24.1.2 to 24.2.1 where it fails.
Can reproduce with:
- 24.1.2 -> https://fiddle.clickhouse.com/1f0e1a88-ee31-4a7c-bdac-0b885635dd38
- 24.2.1 -> https://fiddle.clickhouse.com/c2f5677c-c655-47e9-8810-fa7df255d020

**Comment by AntonOvsyannikov** [comment]
Same on  24.2.2.71

```
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;

CREATE TABLE test.foo(to_dttm DateTime) ENGINE = MergeTree() ORDER BY ();

CREATE VIEW test.vfoo AS
SELECT CAST(test.foo.to_dttm AS DateTime64(6))       AS feature,
       toDateTime64('2024-03-26 11:35:03.620846', 6) AS to_dttm
FROM test.foo;

SELECT * FROM test.vfoo WHERE test.vfoo.to_dttm=toDateTime64('2024-03-26 11:35:03.620846', 6);


-- OK

DROP DATABASE IF EXISTS test;
CREATE DATABASE test;

CREATE TABLE test.foo(to_dttm_blaaaaaaaaaaaaaa DateTime) ENGINE = MergeTree() ORDER BY ();

CREATE VIEW test.vfoo AS
SELECT CAST(test.foo.to_dttm_blaaaaaaaaaaaaaa AS DateTime64(6))       AS feature,
       toDateTime64('2024-03-26 11:35:03.620846', 6) AS to_dttm
FROM test.foo;

SELECT * FROM test.vfoo WHERE test.vfoo.to_dttm=toDateTime64('2024-03-26 11:35:03.620846', 6);

```
