### ISSUE TITLE
csv file with multiple delimiter character error expected '\t' at end of stream

### ISSUE THREAD

**Issue by 20orange** [ClickHouse/ClickHouse#56832]
We  import csv file with multiple delimiter character like: https://github.com/ClickHouse/ClickHouse/issues/12744#issuecomment-663738562
![image](https://github.com/ClickHouse/ClickHouse/assets/59687410/86e366a5-cc4c-4317-981e-0a22032cbb23)

![image](https://github.com/ClickHouse/ClickHouse/assets/59687410/f35f6ee1-56cf-4f27-8efe-1e22248004aa)

we use command:
cat xx.csv |clickhouse-client  -q "insert into log.XC FORMAT CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '\$\$', format_custom_result_before_delimiter='name\$\$city\$\$age\n'"

and error with:
![image](https://github.com/ClickHouse/ClickHouse/assets/59687410/020f3595-7bf4-4ca4-a528-6be1607713f4)
Code: 27. DB::ParsingException: Cannot parse input: expected '\t' at end of stream.: While executing CustomSeparatedRowInputFormat: data for INSERT was parsed from query: (in query: insert into log.XC FORMAT CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '$$', format_custom_result_before_delimiter='name$$city$$age\n'). (CANNOT_PARSE_INPUT_ASSERTION_FAILED)

Thanks!

**Comment by den-crane** [comment]
```
create table XC(name String, city String, age Int64) Engine=Memory;

cat xx.csv
name$$city$$age
ss$$hangzhou$$28
dd$$shanghai$$30

cat xx.csv |clickhouse-client -q "insert into XC FORMAT CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '\$\$', format_custom_result_before_delimiter='name\$\$city\$\$age\n'"

Code: 27. DB::ParsingException: Cannot parse input: expected '\t' at end of stream.: (while reading header): 
While executing CustomSeparatedRowInputFormat: data for INSERT was parsed from query: (in query: insert into XC 
FORMAT CustomSeparated SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '$$', format_custom_result_before_delimiter='name$$city$$age\n'). (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
```

**Comment by den-crane** [comment]
Ah, now Clickhouse does not allow `FORMAT.. SETTINGS` should be `SETTINGS...FORMAT`

```
cat xx.csv |clickhouse-client --input_format_parallel_parsing=1 -q "insert into XC SETTINGS format_custom_escaping_rule = 'CSV', format_custom_field_delimiter = '\$\$', format_custom_result_before_delimiter='name\$\$city\$\$age\n' FORMAT CustomSeparated"

select * from XC;
┌─name─┬─city─────┬─age─┐
│ ss   │ hangzhou │  28 │
│ dd   │ shanghai │  30 │
└──────┴──────────┴─────┘
```
```

**Comment by 20orange** [comment]
I tried the new sql and it worked, thank you very much！

**Comment by antaljanosbenjamin** [comment]
@den-crane Nice find, however shouldn't ClickHouse complain when `FORMAT.. SETTINGS` is used instead of `SETTINGS.. FORMAT`? I would say it should either work or raise an error, but do not behave in an unexpected way.

**Comment by den-crane** [comment]
> @den-crane Nice find, however shouldn't ClickHouse complain when `FORMAT.. SETTINGS` is used instead of `SETTINGS.. FORMAT`? I would say it should either work or raise an error, but do not behave in an unexpected way.

That was discussed in that PR, but the problem that everything after `FORMAT CustomSeparated` is a datastream. Parser treats `SETTINGS format_custom_escaping_rule = 'CSV'...` like data.

**Comment by antaljanosbenjamin** [comment]
That is true, thanks for clarifying!
