### ISSUE TITLE
Exception: There is no column **.null   **.size0 in the system.replication_queue

### ISSUE THREAD

**Issue by haiyangcheng** [ClickHouse/ClickHouse#56849]
I has a distributed merge tree table, in the system.replication_queue, there are a lot of  parts_to_merge,  which num_tries reaching 1 million times or more. The exception is: Code: 16. DB::Exception: There is no column baseinfo_publish_time.null in the table. (NO_SUCH_COLUMN_IN_TABLE) (version 22.3.5.20).
In the table structure, baseinfo_publish_time is Nullable(Uint64), I never have add column baseinfo_publish_time.null .

Other tables also have this problem, Code: 16. DB::Exception: There is no column sources.size0 in the table. (NO_SUCH_COLUMN_IN_TABLE) (version 22.3.5.20), where the source is Array(UInt32). 

How is this situation caused?  the baseinfo_publish_time or source column didn't have modifyed after create the table.

**Comment by haiyangcheng** [comment]
and how to limit the num_tries ? make num_tries < 10

**Comment by den-crane** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/36687
You need to upgrade to 22.3.20.29
Though 22.3 is out of support. Better upgrade to the 23.10.
