### ISSUE TITLE
Can't connect zookeeper

### ISSUE THREAD

**Issue by calvin2020** [ClickHouse/ClickHouse#56848]
Hi:

I deployed clickhouse cluster of three nodes ,clickhouse  version is 23.10.3.5, my zookeeper version is 3.4.14,I used below SQL to check whether my clickhouse can connect zookeeper

ck1 :) SELECT * FROM system.zookeeper WHERE path = '/clickhouse';

SELECT *
FROM system.zookeeper
WHERE path = '/clickhouse'

Query id: 2cc89062-023a-43a3-aa8a-bbf105d3dac9

┌─name───────┬─value─┬─path────────┐
│ task_queue │       │ /clickhouse │
└────────────┴───────┴─────────────┘

1 row in set. Elapsed: 0.002 sec. 

Does this result mean clickhouse cluster can't connect zookeeper，I have no idea,please help me to check
thanks

**Comment by den-crane** [comment]
>┌─name───────┬─value─┬─path────────┐
│ task_queue │ │ /clickhouse │
└────────────┴───────┴─────────────┘

It means your Clickhouse have  connected to Zookeeper successfully.

**Comment by 20orange** [comment]
If your clickhouse cluster can't connect zookeeper.
When you use the sql: 

> SELECT * FROM system.zookeeper WHERE path = '/clickhouse';

> Received exception from server (version 23.4.2):
Code: 999. DB::Exception: Received from localhost:9008. Coordination::Exception. Coordination::Exception: Connection loss, path: All connection tries failed while connecting to ZooKeeper. nodes:

**Comment by calvin2020** [comment]
ok,thanks,but I can't get clickhouse cluster info after I deployed according to clickhouse official document,
ck1 :) select * from system.clusters;

SELECT *
FROM system.clusters

Query id: 401f755e-afa2-447b-8520-a258f91e045c

Ok.

0 rows in set. Elapsed: 0.002 sec. 

Would you please check it again,thanks
