### ISSUE TITLE
 Materialized view is not filtering data from the table Clickhouse v23.9

### ISSUE THREAD

**Issue by vladimir-ilnytskyi** [ClickHouse/ClickHouse#56876]
Creating a view with filter does not apply data filtering:

How to reproduce:

```

DROP TABLE EventsTable;
DROP VIEW EventsTable_MV;

CREATE OR REPLACE TABLE EventsTable
(
    Id Int64,
    CreatedAt DateTime64,
    EventName String,
    Data String
)
ENGINE = ReplacingMergeTree(CreatedAt)
ORDER BY Id;

INSERT INTO EventsTable (Id, CreatedAt, EventName, Data) values 
(1, now64() , 'event1', '{}' ),
(2, now64() , 'event2', '{}'  ),
(3, now64() , 'event2', '{}'  ),
(4, now64() , 'event3', '{}'  );

CREATE MATERIALIZED VIEW EventsTable_MV
TO EventsTable
AS
SELECT
    Id,
    EventName,
    CreatedAt,
    Data
FROM EventsTable
WHERE Id > 2;

SELECT * FROM EventsTable_MV;
```

When looking into result i can see all records shown in EventsTable_MV

**Comment by Algunenano** [comment]
You are creating a circular dependency:

```
CREATE MATERIALIZED VIEW EventsTable_MV
TO EventsTable <<<<<<<<<<<<
AS
SELECT
    Id,
    EventName,
    CreatedAt,
    Data
FROM EventsTable <<<<<<
WHERE Id > 2;
```

Are you sure you are doing what you think you are doing?

> `SELECT * FROM EventsTable_MV;`

In your case `EventsTable_MV` does not contain any data, the data is in the `TO table` which in your case it's wrong too.


The way to use MV is:
* Create source table
* Create target table
* Create MV from source to target table (with filter for example)
* Insert into source table
* Query target table.

**Comment by vladimir-ilnytskyi** [comment]
@Algunenano thanks a lot for clarification! 

Docs are not clear unfortunately here =(
https://clickhouse.com/docs/en/guides/developer/cascading-materialized-views

So i do not need to query materialized view, but instead i need to use material view as a sync trigger that automatically will write to another table?

**Comment by Algunenano** [comment]
Yes, materialized views **are** triggers that insert data into a different table. You can technically used them also as storage (if you don't declare the `TO` part and instead declare the engine) but that's discouraged as it complicates maintenance and understanding what's going on.

**Comment by den-crane** [comment]
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
