### ISSUE TITLE
Populating test data with multiple randBernoulli calls 

### ISSUE THREAD

**Issue by d00mw01f** [ClickHouse/ClickHouse#56871]
Hi.

I'm trying to populate test data with multiple `randBernoulli` calls in one query, and inside one row, values are always the same:

Query:
```SQL
select distinct 
  If(randBernoulli(0.5), 'A', 'B') as test1, 
  If(randBernoulli(0.5), 'A', 'B') as test2 
from numbers(1000);
```

Results:
```
┌─test1─┬─test2─┐
│ A     │ A     │
│ B     │ B     │
└───────┴───────┘
```

How to make  `randBernoulli` calls return separate values inside one row (i.e. get combinations of A and B in one row)?

Thanks.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/random-functions

All functions in this section accept zero or one arguments. The only use of the argument (if provided) is to prevent prevent [common subexpression elimination](https://clickhouse.com/docs/en/sql-reference/functions#common-subexpression-elimination) **such that two different execution of the same random function in a query return different random values.**

https://fiddle.clickhouse.com/bf3b5832-11d8-49a0-963a-dfe20f595916

**Comment by d00mw01f** [comment]
@den-crane Thank you!
