### ISSUE TITLE
Not possible to create calculated columns in meterial views? - nonsense

### ISSUE THREAD

**Issue by vladimir-ilnytskyi** [ClickHouse/ClickHouse#56880]
Our goal is to have table with JSON string column (JSON type column in experimental) so we can ingest different type of events.
Based on data that is stored in events we would like to have different material views for different event types, so we dont need to parse json each time and maybe do some aggregations on sessionId etc. but again, sessionId is not a property of all event types, so that is why it cannot be a column.

CREATE OR REPLACE TABLE TableWithJsonString
(
    Id Int64,
    CreatedAt DateTime64,
    EventName String,
    Data String
)
ENGINE = ReplacingMergeTree(CreatedAt)
ORDER BY Id;

-----
INSERT INTO TableWithJsonString (Id, CreatedAt, EventName, Data) values
(1, now64() , 'event1', '{"sessionId": "session1" , "sendoutId": "sendout1"}' ),
(2, now64() , 'event2', '{"sessionId": "session1" , "sendoutId": "sendout1"}'  ),
(3, now64() , 'event1', '{"sessionId": "session2" , "sendoutId": "sendout1"}'  ),
(4, now64() , 'event3', '{"foo": "bar"}'  );

CREATE MATERIALIZED VIEW TableWithJsonString_MV
TO TableWithJsonString
AS
SELECT
    Id,
    EventName,
    CreatedAt,
    JSONExtractString(Data, 'sendoutId') as SendoutId,
    JSONExtractString(Data, 'sessionId') as SessionId
FROM TableWithJsonString
WHERE JSONHas(Data, 'sendoutId') AND JSONHas(Data, 'sessionId');

**Comment by UnamedRus** [comment]
You need to first read about MV in ClickHouse, it's not what you expect:
https://kb.altinity.com/altinity-kb-schema-design/materialized-views/
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
https://www.youtube.com/watch?t=9353&v=ckChUkC3Pns&feature=youtu.be

**Comment by vladimir-ilnytskyi** [comment]
@UnamedRus thanks, i've read only docs on main clickhouse page, and it doesn't feel like it is notes anywhere there =(
https://clickhouse.com/docs/en/guides/developer/cascading-materialized-views

I've also created question regarding issue that my material view does not filter the data on where clause...maybe you could advise as well there? =)

**Comment by UnamedRus** [comment]
> maybe you could advise as well there? =)

Answer, what was given to you was correct, `SELECT ...` thing in MV is evaluated during INSERT statement to source table.
Because you have source table in TO, during read from MV, you effectively doing 
`SELECT * FROM (TO table)` -> `SELECT * FROM source_table` , which has all data

**Comment by vladimir-ilnytskyi** [comment]
@UnamedRus thanks a lot! yeah...most likely i missunderstood that TO <table> is not to which table you attach view but into which you write =) thanks!
