### ISSUE TITLE
Date type range issue extension

### ISSUE THREAD

**Issue by Etoakor** [ClickHouse/ClickHouse#56896]
需要增加clickhouse时间类型范围，现有范围无法将mysql数据库中的时间2999-01-05 12:23:32 导入进去

> It is necessary to increase the clickhouse time type range. The existing range cannot import the time 2999-01-05 12:23:32 in the mysql database.

**Comment by alexey-milovidov** [comment]
You can store timestamps from the distant future as a UNIX timestamp using the UInt64 data type or as a calendar time using the String data type.
