### ISSUE TITLE
bool DB::KeeperStateMachine::preprocess(const KeeperStorage::RequestForSession &): Failed to preprocess stored log, aborting to avoid inconsistent state: Code: 49. DB::Exception: Got new ZXID (24076) smaller or equal to current ZXID (24080). It's a bug. (LOGICAL_ERROR)

### ISSUE THREAD

**Issue by FriskKiddo** [ClickHouse/ClickHouse#56900]
#### kubernetes version:
clientVersion
  buildDate: "2023-04-14T13:21:19Z"
  compiler: gc
  gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
  gitTreeState: clean
  gitVersion: v1.27.1
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-04-14T13:14:42Z"
  compiler: gc
  gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
  gitTreeState: clean
  gitVersion: v1.27.1
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: linux/amd64

then execute `kubectl apply -f https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/clickhouse-keeper/clickhouse-keeper-3-nodes.yaml -n ckns`

when execuete `kubectl get pods -n ckns`
the result is :
clickhouse-keeper-0                   1/1     Running   0               12m
clickhouse-keeper-1                   0/1     Error     7 (5m21s ago)   12m
clickhouse-keeper-2                   1/1     Running   0               12m

when execute `kubectl logs clickhouse-keeper-1 -n ckns`, i found some logs like that:
2023.11.17 07:09:28.218899 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 1 with timeout 30000
2023.11.17 07:09:28.219012 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 2 with timeout 30000
2023.11.17 07:09:28.219128 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 3 with timeout 30000
2023.11.17 07:09:28.219166 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 4 with timeout 30000
2023.11.17 07:09:28.219744 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 5 with timeout 30000
2023.11.17 07:09:28.222175 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 6 with timeout 30000
2023.11.17 07:09:28.261798 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 7 with timeout 30000
2023.11.17 07:09:28.261976 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 8 with timeout 30000
2023.11.17 07:09:28.262016 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 9 with timeout 30000
2023.11.17 07:09:28.262243 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 10 with timeout 30000
2023.11.17 07:09:28.295094 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 11 with timeout 30000
2023.11.17 07:09:28.295169 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 12 with timeout 30000
2023.11.17 07:09:28.295525 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 13 with timeout 30000
2023.11.17 07:09:28.298389 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 14 with timeout 30000
2023.11.17 07:09:28.298496 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 15 with timeout 30000
2023.11.17 07:09:28.298535 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 16 with timeout 30000
2023.11.17 07:09:28.315407 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 17 with timeout 30000
2023.11.17 07:09:28.316903 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 18 with timeout 30000
2023.11.17 07:09:28.317528 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 19 with timeout 30000
2023.11.17 07:09:28.318534 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 20 with timeout 30000
2023.11.17 07:09:28.319009 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 21 with timeout 30000
2023.11.17 07:09:28.319437 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 22 with timeout 30000
2023.11.17 07:09:28.319447 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 23 with timeout 30000
2023.11.17 07:09:28.319484 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 24 with timeout 30000
2023.11.17 07:09:28.320487 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 25 with timeout 30000
2023.11.17 07:09:28.321181 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 26 with timeout 30000
2023.11.17 07:09:28.321307 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 27 with timeout 30000
2023.11.17 07:09:28.338763 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 28 with timeout 30000
2023.11.17 07:09:28.366601 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 29 with timeout 30000
2023.11.17 07:09:28.366658 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 30 with timeout 30000
2023.11.17 07:09:28.366675 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 31 with timeout 30000
2023.11.17 07:09:28.366878 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 32 with timeout 30000
2023.11.17 07:09:28.366916 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 33 with timeout 30000
2023.11.17 07:09:28.366954 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 34 with timeout 30000
2023.11.17 07:09:28.366976 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 35 with timeout 30000
2023.11.17 07:09:28.367410 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 36 with timeout 30000
2023.11.17 07:09:28.367420 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 37 with timeout 30000
2023.11.17 07:09:28.367457 [ 24 ] {} <Debug> KeeperStateMachine: Session ID response 38 with timeout 30000
2023.11.17 07:09:28.369830 [ 24 ] {} <Error> bool DB::KeeperStateMachine::preprocess(const KeeperStorage::RequestForSession &): Failed to preprocess stored log, aborting to avoid inconsistent state: Code: 49. DB::Exception: Got new ZXID (24076) smaller or equal to current ZXID (24080). It's a bug. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x0000000000e4d4db in /usr/bin/clickhouse-keeper
1. DB::Exception::Exception<long&, long&>(int, FormatStringHelperImpl<std::type_identity<long&>::type, std::type_identity<long&>::type>, long&, long&) @ 0x000000000087cda2 in /usr/bin/clickhouse-keeper
2. DB::KeeperStorage::preprocessRequest(std::shared_ptr<Coordination::ZooKeeperRequest> const&, long, long, long, bool, std::optional<DB::KeeperStorage::Digest>, long) @ 0x000000000087edb2 in /usr/bin/clickhouse-keeper
3. DB::KeeperStateMachine::preprocess(DB::KeeperStorage::RequestForSession const&) @ 0x000000000085b8a1 in /usr/bin/clickhouse-keeper
4. DB::KeeperStateMachine::commit(unsigned long, nuraft::buffer&) @ 0x000000000085d1c6 in /usr/bin/clickhouse-keeper
5. nuraft::raft_server::commit_in_bg_exec(unsigned long, bool) @ 0x0000000000c3044a in /usr/bin/clickhouse-keeper
6. nuraft::cb_func::ReturnCode std::__function::__policy_invoker<nuraft::cb_func::ReturnCode (nuraft::cb_func::Type, nuraft::cb_func::Param*)>::__call_impl<std::__function::__default_alloc_func<DB::KeeperServer::launchRaftServer(Poco::Util::AbstractConfiguration const&, bool)::$_0, nuraft::cb_func::ReturnCode (nuraft::cb_func::Type, nuraft::cb_func::Param*)>>(std::__function::__policy_storage const*, nuraft::cb_func::Type, nuraft::cb_func::Param*) @ 0x000000000081a09f in /usr/bin/clickhouse-keeper
7. nuraft::raft_server::handle_append_entries(nuraft::req_msg&) @ 0x0000000000c5a457 in /usr/bin/clickhouse-keeper
8. nuraft::raft_server::process_req(nuraft::req_msg&, nuraft::raft_server::req_ext_params const&) @ 0x0000000000c217ee in /usr/bin/clickhouse-keeper
9. nuraft::rpc_session::read_complete(std::shared_ptr<nuraft::buffer>, std::shared_ptr<nuraft::buffer>) @ 0x0000000000c06c28 in /usr/bin/clickhouse-keeper
10. nuraft::rpc_session::read_log_data(std::shared_ptr<nuraft::buffer>, boost::system::error_code const&, unsigned long) @ 0x0000000000c078ca in /usr/bin/clickhouse-keeper
11. boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::any_io_executor>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, std::__bind<void (nuraft::rpc_session::*)(std::shared_ptr<nuraft::buffer>, boost::system::error_code const&, unsigned long), std::shared_ptr<nuraft::rpc_session> const&, std::shared_ptr<nuraft::buffer>&, std::placeholders::__ph<1> const&, std::placeholders::__ph<2> const&>>::operator()(boost::system::error_code, unsigned long, int) @ 0x0000000000c13593 in /usr/bin/clickhouse-keeper
12. boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::any_io_executor>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, std::__bind<void (nuraft::rpc_session::*)(std::shared_ptr<nuraft::buffer>, boost::system::error_code const&, unsigned long), std::shared_ptr<nuraft::rpc_session> const&, std::shared_ptr<nuraft::buffer>&, std::placeholders::__ph<1> const&, std::placeholders::__ph<2> const&>>, boost::asio::any_io_executor>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) @ 0x0000000000c13eb9 in /usr/bin/clickhouse-keeper
13. boost::asio::detail::scheduler::run(boost::system::error_code&) @ 0x0000000000bc4639 in /usr/bin/clickhouse-keeper
14. nuraft::asio_service_impl::worker_entry() @ 0x0000000000bbd532 in /usr/bin/clickhouse-keeper
15. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, std::__bind<void (nuraft::asio_service_impl::*)(), nuraft::asio_service_impl*>>>(void*) @ 0x0000000000bca19a in /usr/bin/clickhouse-keeper
 (version 23.11.1.722 (official build))
2023.11.17 07:09:28.370727 [ 12 ] {} <Trace> BaseDaemon: Received signal 6
2023.11.17 07:09:28.370855 [ 28 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2023.11.17 07:09:28.370870 [ 28 ] {} <Fatal> BaseDaemon: (version 23.11.1.722 (official build), build id: 38A7577C54603BA5D3A0A44C21A8B7C0348349FC, git hash: 90936aa2c7a197f02cfa1b2c360f5a06e84b2bff) (from thread 24) Received signal 6
2023.11.17 07:09:28.370878 [ 28 ] {} <Fatal> BaseDaemon: Signal description: Aborted
2023.11.17 07:09:28.370882 [ 28 ] {} <Fatal> BaseDaemon:
2023.11.17 07:09:28.370891 [ 28 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000000a52670
2023.11.17 07:09:28.370895 [ 28 ] {} <Fatal> BaseDaemon: ########################################
2023.11.17 07:09:28.370902 [ 28 ] {} <Fatal> BaseDaemon: (version 23.11.1.722 (official build), build id: 38A7577C54603BA5D3A0A44C21A8B7C0348349FC, git hash: 90936aa2c7a197f02cfa1b2c360f5a06e84b2bff) (from thread 24) (no query) Received signal Aborted (6)
2023.11.17 07:09:28.370906 [ 28 ] {} <Fatal> BaseDaemon:
2023.11.17 07:09:28.370910 [ 28 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000000a52670
2023.11.17 07:09:28.370941 [ 28 ] {} <Fatal> BaseDaemon: 0. signalHandler(int, siginfo_t*, void*) @ 0x0000000000a52670 in /usr/bin/clickhouse-keeper
2023.11.17 07:09:28.370955 [ 28 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read.
2023.11.17 07:09:28.370962 [ 28 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
bash: line 33:    11 Aborted                 (core dumped) clickhouse-keeper --config-file=/etc/clickhouse-keeper/keeper_config.xml

How should I troubleshoot this problem?

**Comment by alexey-milovidov** [comment]
Your machine has corrupted data. You should replace it with a new machine, and Keeper will synchronize from the other two.
