### ISSUE TITLE
Memory leak from 23.8, most likely when insert into kafka

### ISSUE THREAD

**Issue by spff** [ClickHouse/ClickHouse#56904]
**Describe what's wrong**
Memory leak

**Does it reproduce on recent release?**
Affected:
- 23.8.1.2992-lts
- 23.8.3.48-lts
- 23.8.4.69-lts
- 23.9.1.1854
- 23.10.1.1976
- 23.10.2.13
- 23.10.3.5

Good:
- 23.6.2.18
- 23.7.6.111

**How to reproduce**
Create a kafka topic & MV and do a lot of insert into (200Mbps), the RAM usage would be increasing at a rate of 500MB/hr.  

**Error message and/or stacktrace**
N/A

**Comment by aol-59** [comment]
I have submitted a memory issue before.

#54483

**Comment by spff** [comment]
> I have submitted a memory issue before.
> 
> #54483

Great! Would you like to also try 23.7.6.111 to see if we're facing the same issue? I have two new clickhouse doing different things, but when they started doing Kafka stuff, memory leak happened.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/57822
