### ISSUE TITLE
about materializemysql  with mysql8

### ISSUE THREAD

**Issue by sszssz113** [ClickHouse/ClickHouse#56902]
mysql version 8.0.18

done: Mysql configuration has been completed. 
          Clickhouse configuration has been completed

          CREATE DATABASE cfg_test ENGINE = MaterializeMySQL('192.168.xxx:3336', 'xxx', 'xxx', 'xxx');

issue:Clickhouse  can not read the Mysql tables.
         use cfg_test;
         show tables;
          return: 0 rows in set.

Is it because of my mysql8?

**Comment by sszssz113** [comment]
clickhouse version : 21.7.4

**Comment by den-crane** [comment]
21.7 is out of support. Upgrade to 23.10
