### ISSUE TITLE
Add support for bloom filter based indexes for `match`/`REGEXP`

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#56939]
- We have bloom-filter-based skip indexes `ngrambf_v1`/`tokenbf_v1`.
- These indexes are supported by many operators/functions, including `like()`/`has()`/`hasToken()`,
see https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#functions-support
- `match()` function has no optimizations related to bloom-filter-based skip indexes

Use case: user specifies a complex regexp in a `match()` predicate and it is not obvious that performance can be improved if user will add additional `has` condition before `match`.

To implement this: get a list of "required" substrings from the regexp, i.e. strings that are present in every matching string (see `OptimizedRegularExpression::analyze()`), then query the skip indexes with these substrings.

**Comment by lingtaolf** [comment]
I'm interesting in this. Could you let me try this ?

**Comment by lingtaolf** [comment]
If it's urgent, you can assign it to someone else. Because I'm still working on another task.
