### ISSUE TITLE
FAIL TO START

### ISSUE THREAD

**Issue by auyang-0626** [ClickHouse/ClickHouse#56933]
(version 22.2.2.1)
error log:
 <Error> Application: DB::Exception: Table default.test_replicated_inner doesn't exist: Cannot attach table `default`.`test_replicated_inner_table` from metadata file /var/lib/clickhouse2/store/888/88840ce3-c4af-49ee-ad1b-780bf56336bb/test_replicated_inner_table.sql from query ATTACH TABLE default.test_replicated_inner_table UUID '38bd3802-9ddf-4669-aa7e-224169c6f319' ENGINE = Distributed('test_3shards_2replicas', 'default', 'test_replicated_inner', rand())
**Describe what's wrong**

describe:

default.test_replicated_inner_table  is Distributed, it dependent  `default`.`test_replicated_inner_table`.
If `default.test_replicated_inner_table` loads first，won't be able to find   `default.test_replicated_inner_table` .

I rename table file use commod : mv test_replicated_inner_table.sql   .test_replicated_inner_table.sql
next, clickhouse Successfully started.
and then ,use commod : mv .test_replicated_inner_table.sql   test_replicated_inner_table.sql
and in sql client: ATTACH TABLE default.test_replicated_inner_table

so,I suspect there is an issue with the loading sequence during startup

**Comment by den-crane** [comment]
22.2 is out of support. Upgrade to 23.10.
