### ISSUE TITLE
The server should communicate changed settings to the client on connection.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#56976]
**Use case**

If a formatting setting (such as `date_time_output_format`) is changed on the server side, it is not effective on the client side.

**Describe the solution you'd like**

A server could send the changed settings in a reply to authentication.
We can introduce a new packet type for this if needed.

The client will apply the settings from the server, and then apply the client-side settings on top of them.

**Additional context**

Keep server settings aside on the client - so the client will not send all of them back as its own.

**Comment by lingtaolf** [comment]
I'd like have a try !

**Comment by alexey-milovidov** [comment]
@lingtaolf Thank you! This will be really helpful!

**Comment by al13n321** [comment]
It seems there's no good way to add things to server Hello message.
* If we add settings to the server Hello message itself then the settings are sent unchunked. This breaks proxies that rely on chunked protocol (if I understand the purpose of chunked protocol correctly).
* If we send settings as a separate packet after client addendum, this adds a rtt of latency to the handshake.

But I see DBMS_PARALLEL_REPLICAS_PROTOCOL_VERSION was added to the addendum after chunked protocol. Doesn't it have the same problem? Did it break proxies? Maybe no proxies exist yet, so it didn't matter?

What should we do here?

---

(In case the above explanation is not clear, here's more words. Feel free to skip if you already understand.)

Current protocol is:
```
client: Hello (unchunked)
server: Hello (unchunked)
client: addendum (unchunked, says whether chunked protocol should be used)
client: Query (chunked if needed)

total: 1.5 rtt
```
AFAIU, chunked protocol exists to make life easier for proxies. Proxies can pass-through chunked messages without parsing them, but have to be able to parse all unchunked messages. If we add things to either of the Hello messages or the addendum, any proxy implementations would need to be updated to expect the added fields.

The alternative is this:
```
client: Hello (unchunked)
server: Hello (unchunked)
client: addendum (unchunked)
server: Settings (chunked if needed)
client: Query (chunked if needed)

total: 2.5 rtt
```
, which adds 1 roundtrip time of latency as the server has to wait for addendum before sending Settings, and the client has to wait for Settings before sending Query.

**Comment by al13n321** [comment]
Current plan: add length-prefixed "extras" part to both Hello messages, breaking proxies once but allowing future changes without this problem. (Could add it to the addendum too, but it seems unnecessary because the client can just send another message immediately after it.)

**Comment by al13n321** [comment]
Oh, there's also no way to add things to client Hello at all. So the client won't be able to decide whether the server should send Settings in Hello reply or not.

Current plan: add length prefixed "extras" part to server Hello message. (Proxies that rely on chunked protocol will need to be updated this time but not for future changes.) Put server Settings in there, unconditionally. If they're big, client won't be able to opt out, but there can be a server setting to send empty Settings.

**Comment by alexey-milovidov** [comment]
No proxies exist as of today, and the chunked protocol was added only recently - ok to break it.

**Comment by alexey-milovidov** [comment]
Why not this logic (I didn't understand):
- Client sends the Hello packed with its version as usual;
- If the client is new enough, the server adds settings to its Hello packet.

**Comment by al13n321** [comment]
Yes, that's the plan. It ended up a simple change not worth the wall of text above, sorry :)

If there were proxies, they would have to be updated because the Hello message is not chunked or length-prefixed or anything. I'll serialize the new data as a length-prefixed blob, so that in future we can add more things into that blob (part of Hello) without breaking proxies.

**Comment by Avogar** [comment]
@yakov-olkhovskiy you may be interested as the author of chunked protocol

**Comment by yakov-olkhovskiy** [comment]
@al13n321 @alexey-milovidov @Avogar 
Handshake ('Hello' sequence) is always not chunked - as a matter of fact negotiation of chunked protocol happens during handshake. So you can add to handshake whatever you want, but you always MUST bump up protocol version and make it backward compatible - i.e. previous version of client should communicate with new version of server just fine and vice versa. Also please notice that starting from some version we have 3 steps handshake which allows proper protocol version negotiation:
Client Hello -> Server Hello -> Client Addendum
so use it to make it backward compatible.
and there is chunked protocol outline (notice handshake is never chunked):
https://github.com/ClickHouse/ClickHouse/blob/master/src/IO/ReadBufferFromPocoSocketChunked.h#L6-L72

**Comment by al13n321** [comment]
(I'll take that to mean that I misunderstood the purpose of chunked protocol and remove the "extras" thing from Hello.)
