### ISSUE TITLE
TOAST values in Postgres

### ISSUE THREAD

**Issue by bykof** [ClickHouse/ClickHouse#57005]
Hello guys, 

I connected my clickhouse database with the `MaterializedPostgreSQL` engine to a postgres database.
There are a few `jsonb` columns that store a lot of data in it.

Are those big inserted columns the reason, why the inserted row reaches the toast level and clickhouse then prints out the following message?

```
2023.11.20 16:32:13.653428 [ 543501 ] {} <Warning> PostgreSQLReplicaConsumer(mydatabase.values_table) Got TOAST value, which is not supported, default value will be used instead.
```

Because of this, the columns get an empty string in clickhouse.

Is it possible to just turn off TOAST messages in postgres at all, so that everything can be synced into clickhouse? 
Performance is really low priority here, it's more important that the data is synced fully into clickhouse?

Thank you!

**Comment by den-crane** [comment]
There is no way to disable TOAST in PG.

_If you only create columns that are too short for toast (like varchar(12) or so), the toast table won't get created._

**Comment by bykof** [comment]
Unfortunately I create jsonb columns @den-crane
