### ISSUE TITLE
PRIMARY KEY with CSV source changes column order

### ISSUE THREAD

**Issue by austinhartzheim** [ClickHouse/ClickHouse#57027]
When creating a dictionary from a CSV source, ClickHouse assumes that the first column in the CSV is the primary key, even when `PRIMARY KEY` is specified.

For example, consider this two column CSV file where the second column is the primary key:
`/tmp/dictionary.csv`
```csv
95,1
85,2
30,3
85,4
95,5
```
Create the dictionary, attempting to name the two columns `a` and `b`. Attempt to use column `b` as the primary key:
```sql
CREATE DICTIONARY example
(
    `a` UInt64,
    `b` UInt64
)
PRIMARY KEY b
SOURCE(FILE(PATH '/tmp/dictionary.csv' FORMAT 'CSV'))
LIFETIME(MIN 3600 MAX 86400)
LAYOUT(HASHED())
```
Unexpected behavior 1: Notice that the column order is reversed and that several records are dropped due to overlapping values on the first column:
```sql
SELECT *
FROM example

┌──b─┬─a─┐
│ 95 │ 1 │
│ 30 │ 3 │
│ 85 │ 2 │
└────┴───┘
```
Unexpected behavior 2: `dictGet`/`dictGetOrDefault` cannot find items based on the second column. Instead, the first column of the CSV file is used as the primary key:
```sql
SELECT dictGetOrDefault('example', 'a', 1, '999999')

┌─dictGetOrDefault('example', 'a', 1, '999999')─┐
│                                        999999 │
└───────────────────────────────────────────────┘
```
```sql
SELECT dictGetOrDefault('example', 'a', 85, '999999')

┌─dictGetOrDefault('example', 'a', 85, '999999')─┐
│                                              2 │
└────────────────────────────────────────────────┘
```

Expected behavior:
- When importing the CSV file, columns should align with the column names specified in SQL.
- The `PRIMARY KEY` option should select which column name is the index of the dictionary. It should not be assumed that the primary key is the first column.

**Comment by Priyansh121096** [comment]
Hello, may I work on this bug fix?

**Comment by den-crane** [comment]
Clickhouse version?

**Comment by den-crane** [comment]
repro https://fiddle.clickhouse.com/124df0b9-9abb-43cb-8b7a-c879a463aaeb

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/45559
