### ISSUE TITLE
Support for a replicated, immediately-consistent, transactional table engine.

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#57060]
Sometimes there is need for immediate consistency and/or transactions for few tables.
Having an integration table engine that supports etcd (or Consul) would be useful.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-engines/special/keeper-map

**Comment by nikitamikhaylov** [comment]
KeeperMap table engine allows to read/write data directly to Keeper/ZooKeeper which respects all the requirements described in the issue.

**Comment by FedericoCeratto** [comment]
Added to https://github.com/ClickHouse/ClickHouse/pull/62033
