### ISSUE TITLE
uniqExact with group by   cube 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#5707]
1. clickhouse version : 19.8.3
2. table ddl : CREATE TABLE coach_news.dw_news_summary_fact_formal (`ymd` Date, `hour` UInt8, `client_id` UInt8, `client_platform` UInt8, `mode` UInt8, `uid` UInt32, `news_type` UInt8, `rq_action` UInt8, `info_id` UInt32, `info_type` UInt8, `entrance` UInt8, `label_id` UInt8) ENGINE = MergeTree() PARTITION BY (ymd, hour) ORDER BY (rq_action, client_id, client_platform, mode, intHash64(uid)) SETTINGS index_granularity = 8192
3. queries:

- query0: SELECT count()
FROM coach_news.dw_news_summary_fact_formal 
WHERE (ymd = '2019-06-20') AND (entrance IN (1, 5)) AND (client_id = 1) AND (rq_action IN (1, 2))

return 140594327

- query1: SELECT 
    rq_action, 
    entrance, 
    count() AS co, 
    uniqExact(uid) AS cd
FROM coach_news.dw_news_summary_fact_formal 
WHERE (ymd = '2019-06-20') AND (entrance IN (1, 5)) AND (client_id = 1) AND (rq_action IN (1, 2))
GROUP BY 
    rq_action, 
    entrance
    WITH CUBE

return 16 rows

- query2: SELECT 
    rq_action, 
    entrance, 
    count() AS co, 
    uniqExact(uid) AS cd
FROM coach_news.dw_news_summary_fact_formal 
WHERE (ymd = '2019-06-20') AND (hour > 16) AND (entrance IN (1, 5)) AND (client_id = 1) AND (rq_action IN (1, 2))
GROUP BY 
    rq_action, 
    entrance
    WITH CUBE

return 9 rows

-----------------

query2 result is right 
and i try to change uniqExact to uniqHLL12 or count then 2 queries return 9 rows

**Comment by onine007** [comment]
select count()
FROM coach_news.dw_news_summary_fact_formal
WHERE (ymd = '2019-06-20') AND (hour > 16) AND (entrance IN (1, 5)) AND (client_id = 1) AND (rq_action IN (1, 2))
return 51072678

**Comment by onine007** [comment]
![91060BD2-6703-4f16-8B43-5D6B1017ECFF](https://user-images.githubusercontent.com/24770345/59914308-b238c100-944c-11e9-9540-6f04ab7eb815.png)
![A6F65F35-4B6D-4c0a-88A2-59ABB5DDEBD8](https://user-images.githubusercontent.com/24770345/59914309-b2d15780-944c-11e9-92ad-3dd6e0b29a4d.png)

**Comment by onine007** [comment]
![6F42EC75-A022-46f4-AB34-CF9C77899D52](https://user-images.githubusercontent.com/24770345/59914439-fcba3d80-944c-11e9-823b-e444aea3b650.png)

**Comment by alexey-milovidov** [comment]
@onine007 Sorry, why is it closed?

**Comment by CurtizJ** [comment]
It should be closed, because it's fixed in #6225.
