### ISSUE TITLE
How does CityHash64 work for integers?

### ISSUE THREAD

**Issue by abionics** [ClickHouse/ClickHouse#57080]
Hi! How does Clickhouse calculate CityHash64 for integers?

I found such lines in docs ["It uses the CityHash algorithm for string parameters and implementation-specific fast non-cryptographic hash function for parameters with other data types"](https://clickhouse.com/docs/en/sql-reference/functions/hash-functions#cityhash64). Where I can found code of this "implementation-specific fast non-cryptographic hash function"?

I need this in order to calculate the same hash using Python backend. I found [clickhouse-cityhash library](https://pypi.org/project/clickhouse-cityhash/) but it doesn't hash integers. By the way, I tried some converts, but they give different results:
```sql
select cityHash64(toUInt8(0)), cityHash64('0'), cityHash64('\0');
--   | 4761183170873013810 | 10408321403207385874 | 603312261738427772 |
```

**Comment by save-my-heart** [comment]
ClickHouse will use `intHash64` for integers instead.
See: 
[fiddle](https://fiddle.clickhouse.com/d23045f6-41b7-4516-9fd5-8f137552a591)

**Comment by abionics** [comment]
@save-my-heart thank you!
