### ISSUE TITLE
Analyzer (experimental feature, not ready for production): Sanitizer: Downcast of address ((DB::ColumnVector<unsigned long>)) which does not point to an object of type 'const DB::ColumnNullable'

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#57086]
Report 1: https://s3.amazonaws.com/clickhouse-test-reports/57052/47abb9e879ef694791f5667fe1eb9b3356346189/fuzzer_astfuzzerubsan/report.html

Query that reproduces it:

```
SELECT
    'limit w/ GROUP BY',
    count(NULL),
    number
FROM remote('127.{1,2}', view(
    SELECT intDiv(number, 2147483647) AS number
    FROM numbers(10)
))
GROUP BY number
    WITH ROLLUP
ORDER BY
    count() ASC,
    number DESC NULLS LAST
SETTINGS limit = 2
```

Works fine without the analyzer.

**Comment by KochetovNicolai** [comment]
https://github.com/ClickHouse/ClickHouse/pull/57098

**Comment by Algunenano** [comment]
* 23.10.1.1976: Fatal error
* 23.11.3.23: OK
* Master: OK

I'll add a test to close the ticket.
