### ISSUE TITLE
Analyzer (experimental feature, not ready for production): crash with LowCardinality + Nullable + Array join

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#57090]
**Describe what's wrong**

Found on CI run: https://s3.amazonaws.com/clickhouse-test-reports/54366/2e2a4021f29c0d4652c0f477d6e45643dcbbcdea/fuzzer_astfuzzerubsan/report.html

**Does it reproduce on recent release?**

Reproduce on latest: https://fiddle.clickhouse.com/7ed33d4a-6dad-41ac-b8e2-09dbaec90dc5

**Comment by canhld94** [comment]
Another CAST issue, also with analyzer in https://s3.amazonaws.com/clickhouse-test-reports/54366/2e2a4021f29c0d4652c0f477d6e45643dcbbcdea/fuzzer_astfuzzertsan/report.html

```
Logical error: 'Bad cast from type DB::ColumnLowCardinality to DB::ColumnVector<long>'.
```

Reproduce: https://fiddle.clickhouse.com/3c4b21da-f278-4ccd-ab98-ce95fb071dfb

**Comment by Algunenano** [comment]
It was fixed in https://github.com/ClickHouse/ClickHouse/pull/57198/
