### ISSUE TITLE
ColumnObject (experimental feature that is going to be removed): nullptr dereference

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#57095]
https://s3.amazonaws.com/clickhouse-test-reports/57073/5cb55d3f8cc767300c95446bac0c74a39bafc401/fuzzer_astfuzzerdebug/report.html

**Comment by Algunenano** [comment]
Closing. It should not appear again since we disable Object('json') from fuzzer and stress tests
