### ISSUE TITLE
defunct ClickHouse process shouldn't prevent clickhouse from restart

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#57093]
**Use case**

ClickHouse tries to start, but sees that there is lock file with PID of previous defunct ClickHouse process and decide not to start.

**Describe the solution you'd like**

ClickHouse will ignore defunct ClickHouse processes during startup.

**Comment by alexey-milovidov** [comment]
It is simple - if the lock file exists, it will not start.
