### ISSUE TITLE
CREATE OR REPLACE materialized view

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#5709]
**Use case**
I'd like to be able to replace the view definition instead of dropping and creating. The whole point is for it to be "transactional". That there is no point in time where the view does not exist.

**Describe the solution you'd like**
Support for standard `CREATE OR REPLACE MATERIALIZED VIEW` would do just fine.

**Comment by nvartolomei** [comment]
Related #1226.

**Comment by Algunenano** [comment]
Addressed by https://github.com/ClickHouse/ClickHouse/pull/57311
