### ISSUE TITLE
"clickhouse-jdbc-bridge is not running. Please, start it manually." occurs 

### ISSUE THREAD

**Issue by wangqinghuan** [ClickHouse/ClickHouse#57092]
**Version**
version 23.7.4.5

**Describe the unexpected behaviour**
We don't have any jdbc table engine.Why clickhouse said "Exception: clickhouse-jdbc-bridge is not running. Please, start it manually. "
> 2023.11.22 10:40:57.176539 [ 276242 ] {f9fab7bf-2a6c-419e-8361-08c268d73628} <Error> executeQuery: Code: 410. DB::Exception: clickhouse-jdbc-bridge is not running. Please, start it manually. (EXTERNAL_SERVER_IS_NOT_RESPONDING) (version 23.7.4.5 (official build)) (from [::ffff:10.65.101.228]:2238) (in query: select concat('jdbc(''', name, ''')') as TABLE_SCHEM, null as TABLE_CATALOG from jdbc('', 'SHOW DATASOURCES') where TABLE_SCHEM like '%' order by name), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000e91fc37 in /usr/bin/clickhouse
> 1. ? @ 0x0000000008f8ffad in /usr/bin/clickhouse
> 2. DB::IBridgeHelper::startBridgeCommand() @ 0x00000000151ed859 in /usr/bin/clickhouse
> 3. DB::IBridgeHelper::startBridgeSync() @ 0x00000000151eaf35 in /usr/bin/clickhouse
> 4. DB::ITableFunctionXDBC::startBridgeIfNot(std::shared_ptr<DB::Context const>) const @ 0x0000000012bcf8f5 in /usr/bin/clickhouse
> 5. DB::ITableFunctionXDBC::executeImpl(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription) const @ 0x0000000012bd0585 in /usr/bin/clickhouse
> 6. DB::ITableFunction::execute(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, String const&, DB::ColumnsDescription, bool, bool) const @ 0x0000000012f95470 in /usr/bin/clickhouse
> 7. DB::Context::executeTableFunction(std::shared_ptr<DB::IAST> const&, DB::ASTSelectQuery const*) @ 0x00000000137d4189 in /usr/bin/clickhouse
> 8. DB::JoinedTables::getLeftTableStorage() @ 0x000000001413b176 in /usr/bin/clickhouse
> 9. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x0000000014042329 in /usr/bin/clickhouse
> 10. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000140f3626 in /usr/bin/clickhouse
> 11. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000140f1233 in /usr/bin/clickhouse
> 12. DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x0000000013ffcd7e in /usr/bin/clickhouse
> 13. ? @ 0x000000001442a8ca in /usr/bin/clickhouse
> 14. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) @ 0x000000001442dd2c in /usr/bin/clickhouse
> 15. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x0000000015224c2d in /usr/bin/clickhouse
> 16. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x0000000015229069 in /usr/bin/clickhouse
> 17. DB::HTTPServerConnection::run() @ 0x00000000152985b2 in /usr/bin/clickhouse
> 18. Poco::Net::TCPServerConnection::start() @ 0x0000000018294134 in /usr/bin/clickhouse
> 19. Poco::Net::TCPServerDispatcher::run() @ 0x0000000018295351 in /usr/bin/clickhouse
> 20. Poco::PooledThread::run() @ 0x000000001841e567 in /usr/bin/clickhouse
> 21. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001841bf9c in /usr/bin/clickhouse
> 22. ? @ 0x00007f9387c51609 in ?
>

**Comment by Algunenano** [comment]
You are using it in the query that you are sending: `select concat('jdbc(''', name, ''')') as TABLE_SCHEM, null as TABLE_CATALOG from jdbc('', 'SHOW DATASOURCES') where TABLE_SCHEM like '%' order by name`

From the [docs](https://clickhouse.com/docs/en/sql-reference/table-functions/jdbc):
```
This table function requires separate [clickhouse-jdbc-bridge](https://github.com/ClickHouse/clickhouse-jdbc-bridge) program to be running. It supports Nullable types (based on DDL of remote table that is queried).
```
