### ISSUE TITLE
Cascaded materialized view sees empty rows of base table for preceding materialized view

### ISSUE THREAD

**Issue by glebinc** [ClickHouse/ClickHouse#57105]
**Describe what's wrong**

I have initial table `users`, intermediate table `users_tmp`, destination table `users_dest` and 2 materialized views transferring data from  `users` to `users_tmp` (`vm_users_tmp`) and from `users_tmp` to `users_dest` (`vm_users_dest`).

The complete thing looks like this: `(users) -vm_users_tmp-> (users_tmp) -vm_users_dest-> (users_dest)`

When running `vm_users_tmp` materialized view can only see the data being inserted and not the full table `users` - EXPECTED

But when running `vm_users_dest` operating on the result of previous materialization appeared in `users_tmp` table - materialized view still cannot see data in `users` (which is not it's base table) table BUT correctly identifies full number of rows it has.

Link to reproducer: https://fiddle.clickhouse.com/dc586ad3-8f18-445f-9ca0-3867dffa3663

**Does it reproduce on recent release?**

Yes

**How to reproduce**

```
CREATE TABLE users (uid Int16, name String, age Int16) ENGINE=MergeTree ORDER BY uid;

INSERT INTO users VALUES (1231, 'John', 33);
INSERT INTO users VALUES (6666, 'Ksenia', 48);
INSERT INTO users VALUES (8888, 'Alice', 50);

-- some calculation on initial table "users" to be reused in materialized views below
create view v_users_collect(uid Int16, state Array(Int16)) as select uid, groupArray(uid) over () state from users;

-- final table that receives correct number of rows but without data
create table users_dest (uid Int16, name String, age Int16, state Array(Int16)) ENGINE=MergeTree ORDER BY uid;
-- temp table that serves as intermediate step
create table users_tmp (uid Int16, name String, age Int16, state Array(Int16)) ENGINE=MergeTree ORDER BY uid;

create materialized view vm_users_tmp TO users_tmp as select u.*, c.state, from users u left join v_users_collect c on u.uid=c.uid;
create materialized view vm_users_dest TO users_dest as select t.* except state, c.state from users_tmp t cross join v_users_collect c;

-- trigger processing
insert into users values (1, 'test', 1);

-- 1 row as expected
select count(*) from users_tmp;
-- 4 rows as expected...
select count(*) from users_dest;
-- ... but without data from "users" table
select * from users_dest;
```

**Expected behavior**

Materialized view `vm_users_dest` should be able to access table `users` with all data it has.

**Error message and/or stacktrace**

![image](https://github.com/ClickHouse/ClickHouse/assets/37399730/3966b5d7-5f1d-40ab-b656-e5ceb92c193a)

**Comment by den-crane** [comment]
1.
Rows in tables related to materialized views appear in random moments in the random order. You cannot rely on it. 
It defined by block squashing  and by settings 
```
min_insert_block_size_rows_for_materialized_views arg                              Like min_insert_block_size_rows, but applied only during pushing to MATERIALIZED VIEW (default: min_insert_block_size_rows)
min_insert_block_size_bytes_for_materialized_views arg                             Like min_insert_block_size_bytes, but applied only during pushing to MATERIALIZED VIEW (default: min_insert_block_size_bytes)
```

2. Alias issue. Columns names in the MatView and in the TO table, have to match: `c.state != state`

https://fiddle.clickhouse.com/573a63d2-621d-47f5-9e1e-eb049de6793d
