### ISSUE TITLE
Has Questions about async_insert

### ISSUE THREAD

**Issue by huoarter** [ClickHouse/ClickHouse#57135]
I have some questions regarding the async insert functionality in ClickHouse and version upgrades. We have multiple clusters running different versions, namely 22.3 and 23.8 LTS. Despite configuring async_insert=1 in the users.xml configuration for both clusters, I haven't observed the async insert feature working in the tables of the 22.3 version. Unlike the 23.8 version, where it is evident.

Therefore, I would like to clarify the following points and raise the following issues:

What is the minimum supported version for async_insert setting?
In version 22.3, async insert does not seem to be effective even though the settings async_insert=1 configuration is added to the tables. Could you explain the possible reasons for this inconsistency compared to version 23.8?
If we want to upgrade from version 22.3 to 23.8, can we perform a rolling upgrade directly? Are there any specific documentation or guidelines available for reference?
Thank you very much for your assistance!

**Comment by melvynator** [comment]
Hey thank you for your question. 

`async_insert` was introduced in 21.11. We have a good documentation page about async_insert: https://clickhouse.com/docs/en/optimize/asynchronous-inserts 

When it comes to rolling upgrades, generally we recommend to upgrade using rolling upgrades for upgrade with less than 1 year difference: https://clickhouse.com/docs/en/operations/update . You should check the changelogs to make sure there is no breaking change that could impact you.

**Comment by huoarter** [comment]
Thank you for your response. 
Although async_insert was introduced in version 21.11 with the expectation of improved performance, it seems that in my testing, the benefits of asynchronous writes are not as significant as in version 23.8 (reduced number of added parts, increased memory usage, and highlighted logs).
