### ISSUE TITLE
How to get latest record in ReplacingMergeTree?

### ISSUE THREAD

**Issue by majinkai** [ClickHouse/ClickHouse#57181]
Here is table create:
```sql
CREATE TABLE adv.test_final
(
    `id` Int32,
    `name` Nullable(String),
    `age` Nullable(Int32),
    `created` DateTime64(3)
)
ENGINE = ReplacingMergeTree(created)
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192
```

and insert values:
```sql
insert into test_final values (1, '1', 1, '2023-11-23');
insert into test_final values (1, '2', 2, '2023-11-24');
insert into test_final values (1, '3', 3, '2023-11-25');
```

query:
```sql
select id, any(name), any(age), any(created), anyLast(created) from test_final group by id;
```

search result:
| id | any(name) | any(age) | any(created) | anyLast(created) |
|  ----  | ----  | ----  | ----  | ----  | 
| 1 | 3| 3 | 2023-11-25 00:00:00.000 | 2023-11-23 00:00:00.000 |

Why `anyLast` is oldest record and `any` is latest record?

**Comment by melvynator** [comment]
I cannot reproduce your exact scenario. Also as mentioned in the documentation the result is not deterministic: 

> Selects the first encountered (non-NULL) value, unless all rows have NULL values in that column. The query can be executed in any order and even in a different order each time, so the result of this function is indeterminate. To get a determinate result, you can use the ‘min’ or ‘max’ function instead of ‘any’.

Also for AnyLast:

> Selects the last value encountered. The result is just as indeterminate as for the [any](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/any) function.
