### ISSUE TITLE
DDL of system.databases

### ISSUE THREAD

**Issue by Jshen6** [ClickHouse/ClickHouse#57184]
execute SQL: select * from system.databases
just find 6 columns: name, engine, data_path, metadata_path, uuid, comment

execute SQL: show create system.databases
the result is:
```sql
CREATE TABLE system.databases
(
    `name` String,
    `engine` String,
    `data_path` String,
    `metadata_path` String,
    `uuid` UUID,
    `comment` String,
    `database` String
)
ENGINE = SystemDatabases
COMMENT 'SYSTEM TABLE is built on the fly.'
```
There's one more column: database

I want to know why

**Comment by jetgm** [comment]
column database is an alias of name.

desc system.databases;

DESCRIBE TABLE system.databases

Query id: 9f500026-06cb-49cc-b5c3-c0ba449992f5

┌─name──────────┬─type───┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ name          │ String │              │                    │         │                  │                │
│ engine        │ String │              │                    │         │                  │                │
│ data_path     │ String │              │                    │         │                  │                │
│ metadata_path │ String │              │                    │         │                  │                │
│ uuid          │ UUID   │              │                    │         │                  │                │
│ engine_full   │ String │              │                    │         │                  │                │
│ comment       │ String │              │                    │         │                  │                │
│ database      │ String │ ALIAS        │ name               │         │                  │                │
└───────────────┴────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
