### ISSUE TITLE
version 19.8.3.8 Cannot schedule a task

### ISSUE THREAD

**Issue by lzy305** [ClickHouse/ClickHouse#5721]
when i run sql in clickhouse-client.  I get error.

[run_sql.txt](https://github.com/yandex/ClickHouse/files/3317512/run_sql.txt)
[err_info.txt](https://github.com/yandex/ClickHouse/files/3317513/err_info.txt)

but i Reduce the amount of data queried .
For example  add filter condition ( and out_buid = 18).
 it run well.

**Comment by alexey-milovidov** [comment]
Could you please provide information:
- what server version do you use;
- a stacktrace (you can get stacktrace if you run clickhouse-client with `--stacktrace` option).

**Comment by lzy305** [comment]
i upgrade clickhouse.  i don't found it.  Please close the quetion.
