### ISSUE TITLE
MaterializedMySQL (Experimental feature) cannot synchronize mysql data

### ISSUE THREAD

**Issue by sKyanfIre** [ClickHouse/ClickHouse#57241]
mysql 
 * version:8.2.0
 * config: 
 ```
server-id=1
log-bin=mysql-bin
binlog_format=ROW

default-authentication-plugin=mysql_native_password
gtid-mode=ON
enforce-gtid-consistency=1
log-slave-updates=1
 
```
After starting mysql and clickhouse using docker and creating table using MaterializedMySQL, the data of mysql table can also be queried, but the modified data of mysql table will not be synchronized to clickhouse table

**Comment by melvynator** [comment]
Do you have any logs on the ClickHouse side?

**Comment by alexey-milovidov** [comment]
We don't support MaterializedMySQL.
