### ISSUE TITLE
_shard_num bug fix 

### ISSUE THREAD

**Issue by ltl0814** [ClickHouse/ClickHouse#57253]
Create a table based on engine PostgreSQL like this 

```
'CREATE TABLE IF NOT EXISTS xxx
(
xxxx
) ENGINE = PostgreSQL(own_pg, table='xxx');'
```
When I exec this sql , it will be transfered like below:
Clickhouse : 
```
SELECT * FROM proxy.sys_nic WHERE  mode !=100 and type=0 and name!='' and _shard_num in (1) ORDER BY _shard_num,name LIMIT 20;
```
Postgres receive:
 ```
SELECT "id", "type", "mode", "state", "name", "nick_name", "description", "speed", "mac", "pci_no", "exist", "create_by", "create_time", "update_by", "update_time" 
 FROM "sys_nic" WHERE ("mode" != 100) AND ("type" = 0) AND 1
```
So, Postgres will report a error :  The argument to AND must be of type boolean, not of type integer,because of  PG can't recognize **and 1**

**Comment by ltl0814** [comment]
could u remove 'AND 1' from this sql , this is redundant

**Comment by ucasfl** [comment]
https://github.com/ClickHouse/ClickHouse/issues/56729#issuecomment-1830137364. Check this.
