### ISSUE TITLE
Is it possible to create MV with Map aggregation functions as MV column to store sum aggregated state of dynamically added keys

### ISSUE THREAD

**Issue by vladimir-ilnytskyi** [ClickHouse/ClickHouse#57264]
Hi! 
I have a generic question about Map aggregations that i think might better fit my case when data is dynamic, considering i have a source table with columns
...
CreatedAt DateTime64,
CreatedBy String,
EventName String,
Data String // metadata of event as JSON string,
....

I have materialized view that aggregates summary per session i need to get session summaries for different types of events, as well as when it was created, when was last activity and the user that created session

For this i use materialized view which seem to work fine, but i'm looking for more dynamic solution here so i don't have to know in advance event Names to know in advance which event names there could be so i have to separate them into their own columns

```
CREATE MATERIALIZED VIEW session_summary_mv
            (
             SessionId String,
             CreatedAt AggregateFunction(min, DateTime64),
             LastActivity AggregateFunction(max, DateTime64),
             CreatedBy AggregateFunction(argMin, Nullable(String), DateTime64),
             Event1Count AggregateFunction(sum, Int32),
             Event2Count AggregateFunction(sum, Int32),
                ...
             EventNCount AggregateFunction(sum, Int32),
                ) ENGINE = AggregatingMergeTree() ORDER BY (SessionId)
AS
SELECT simpleJSONExtractString(e.Data, 'sessionId')                as SessionId,
       minState(e.CreatedAt)                                       as CreatedAt,
       maxState(e.CreatedAt)                                       as LastActivity,
       argMinState(e.CreatedBy, e.CreatedAt)                  as CreatedBy,
       sumState(multiIf(e.EventName = 'Event1', 1, 0))         as Event1Count,
       sumState(multiIf(e.EventName = 'Event2', 1, 0)) as Event2Count
from events e
group by SessionId
;
```

But i would like to consider using Map(String, sumState) to store EventName as a key with value stateSum event counters,
so whenever a new EventName appears in source table i don't need to update the view to have a new column.

I cannot figure out syntax if that is possible to do something like this without intermediate table that has Map<string, int>:

As i understand i will need to have something like 2 nested aggregation functions as 
1. i need to insert entry to Map(string, sumState(and here add 1 for each occurance of event))
2. and at the same time aggregate it with previous aggregation result

```
CREATE MATERIALIZED VIEW session_summary_mv
            (
             SessionId String,
             CreatedAt AggregateFunction(min, DateTime64),
             LastActivity AggregateFunction(max, DateTime64),
             CreatedBy AggregateFunction(argMin, Nullable(String), DateTime64),
             EventCounts AggregateFunction(sumMap, <CANNOT FIGURE OUT WHAT GOES HERE>),
                ) ENGINE = AggregatingMergeTree() ORDER BY (SessionId)
AS
SELECT simpleJSONExtractString(e.Data, 'sessionId')                as SessionId,
       minState(e.CreatedAt)                                       as CreatedAt,
       maxState(e.CreatedAt)                                       as LastActivity,
       argMinState(e.CreatedBy, e.CreatedAt)                  as CreatedBy,
       <CANNOT FIGURE OUT WHAT GOES HERE>    as EventCounts
from events e
group by SessionId
;
```

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/issues/38857#issuecomment-1726731166

>        <CANNOT FIGURE OUT WHAT GOES HERE>    as EventCounts

Just use sumMapState([EventName], [1])

**Comment by vladimir-ilnytskyi** [comment]
@UnamedRus 
view creates successfully but 

```
CREATE MATERIALIZED VIEW session_summaries_mv_2
(
    SessionId String,
    SendoutId String,
    CreatedAt AggregateFunction(min, DateTime64),
    LastActivity AggregateFunction(max, DateTime64),
    CreatedBy AggregateFunction(argMin, Nullable(String), DateTime64),
    EventCounts AggregateFunction(sumMap, Tuple(Array(String), Array(Int32)))
) ENGINE = AggregatingMergeTree() ORDER BY (SendoutId, SessionId)
AS
SELECT 
    simpleJSONExtractString(source.Data, 'sessionId') as SessionId,
    simpleJSONExtractString(source.Data, 'sendoutId') as SendoutId,
    minState(toDateTime64(source.CreatedAt, 3)) as CreatedAt,
    maxState(toDateTime64(source.CreatedAt, 3)) as LastActivity,
    argMinState(CreatedBy, toDateTime64(source.CreatedAt, 3)) as CreatedBy,
    sumMapState([CAST(source.EventName, 'String')], [toInt32(1)]) as EventCounts
FROM TrackingEvents source
GROUP BY SendoutId, SessionId;
```

BUT when i try to insert i get this error:

```
INSERT INTO session_summaries_mv_2
SELECT simpleJSONExtractString(source.Data, 'sessionId') as SessionId,
       simpleJSONExtractString(source.Data, 'sendoutId') as SendoutId,
       minState(toDateTime64(source.CreatedAt, 3)) as CreatedAt,
       maxState(toDateTime64(source.CreatedAt, 3)) as LastActivity,
       argMinState(CreatedBy, toDateTime64(source.CreatedAt, 3)) as CreatedBy,
       sumMapState([CAST(source.EventName, 'String')], [toInt32(1)]) as EventCounts
FROM TrackingEvents source
GROUP BY SessionId, SendoutId;
```
Code: 70. DB::Exception: Conversion from AggregateFunction(1, sumMap, Array(String), Array(Int32)) to AggregateFunction(1, sumMap, Tuple(Array(String), Array(Int32))) is not supported: while converting source column EventCounts to destination column EventCounts. (CANNOT_CONVERT_TYPE) (version 23.9.2.47475 (official build))

This works though:
```
SELECT sumMapState([CAST(source.EventName, 'String')], [1]) as EventCounts
from TrackingEvents source 
limit 1;
```

**Comment by vladimir-ilnytskyi** [comment]
@UnamedRus actually i had error here:
    EventCounts AggregateFunction(sumMap, Tuple(Array(String), Array(Int32)))
    which needed to be changed to:
    EventCounts AggregateFunction(sumMap, Array(String), Array(Int32))
    
    Thanks a lot!
