### ISSUE TITLE
Resolving ClickHouse Database Errors After Disk Replacement

### ISSUE THREAD

**Issue by aol-59** [ClickHouse/ClickHouse#57266]
**Version: 23.8.1.2992**

I have a multi-node cluster, and Node B serves as a replica for Node A. Recently, one of the disks in Node B failed, causing the ClickHouse database on Node B to become non-functional and fail.

Node A, however, is operating without any issues. After four days, we replaced the failed disk in Node B and attempted to start the ClickHouse database. Unfortunately, it failed to start and kept automatically restarting every 30 seconds.

I suspect that the replica on Node B was trying to fetch the missing data parts. To address this, I ran the following command:

`sudo -u clickhouse touch /var/lib/clickhouse/flags/force_restore_data
`

This command resolved some of the errors, but there are still lingering issues. Specifically, we encountered the following error:

 <Error> **_testDB.LocalTable_** : Loading of outdated parts failed. Will terminate to avoid undefined behavior due to an inconsistent set of parts. Exception std::exception. code 1001 type: std::__1::__fs::filesystem::filesystem_error,
e.what() = filesystem error in directory_iterator::directory_iterator(...) : Structure needs cleaning [ "/data/clickhouse/store/055/...."],

**the testDB.LocalTable is only in B node** 

when i tried to access /data/clickhouse/store/055/... and list files 

ls : reading directory .: Structure needs cleaning

**Comment by alyanm** [comment]
@aol-59  -- checking with the core team...

**Comment by alyanm** [comment]
@aol-59 -- The error 'Structure needs cleaning' suggests that your filesystem is corrupted. It's likely causing clickhouse failures, fix this first and then run clickhouse.

If you are not an expert in fixing corrupted FS, try googling `linux file structure needs cleaning`.

**Comment by aol-59** [comment]
> @aol-59 -- The error 'Structure needs cleaning' suggests that your filesystem is corrupted. It's likely causing clickhouse failures, fix this first and then run clickhouse.
> 
> If you are not an expert in fixing corrupted FS, try googling `linux file structure needs cleaning`.

Thank you for your support
