### ISSUE TITLE
ReplicatedMergeTree Lost data

### ISSUE THREAD

**Issue by skywalker2256** [ClickHouse/ClickHouse#57286]
version 23.10.3.5 (official build)
I'm using ClickHouse with two shards and two replicas. When writing data to a distributed table with 200 fields and exceeding 10 million records, a portion of the expected data in the resulting table seems to be lost. What should I do to address this issue?

```[tasklist]
### Tasks
```

**Comment by melvynator** [comment]
@skywalker2256 What version of ClickHouse are you using? Do you have any TTL setup? Do you have any error in the logs? Do you have any reproducible examples?

**Comment by skywalker2256** [comment]
> @skywalker2256 What version of ClickHouse are you using? Do you have any TTL setup? Do you have any error in the logs? Do you have any reproducible examples?

version 23.10.3.5 (official build)
The table doesn't have any TTL settings configured. 
Inserting data into the replica table leads to data loss or missing records.
e.g:
CREATE TABLE test_clsuter_a5 on cluster clickhouse_cluster
(
    `id` String,
    `price` Float64,
    `create_time` DateTime,
  primary key(id)
)
ENGINE = ReplicatedMergeTree;
CREATE TABLE `default`.test_clsuter_5_all on cluster clickhouse_cluster
(
    `id` String,
    `price` Float64,
    `create_time` DateTime
)
ENGINE = Distributed('clickhouse_cluster','default','test_clsuter_a5', rand())
insert into 
default`.test_clsuter_5_all  
select t.id,t.price,d.create_time 
from default`.test_clsuter_4_all  t 
gloab join default`.test_clsuter_3_all  d 
on t.id=d.id
;
If the data volume is small, the results are accurate. However, with larger data volumes or when dealing with 100 columns, data loss occurs, and there are error messages in the logs, as follows:
{} <Error> InterserverIOHTTPHandler: Code: 76. DB::ErrnoException: Cannot open file /var/lib/clickhouse/data/store/0ac/0ac70135-ccec-4476-bcc5-5fd74a81b778/all_1180_1180_0/variable_data_dict_id.cmrk2, errno: 1, strerror: Operation not permitted. (CANNOT_OPEN_FILE), Stack trace (when copying this message, always include the lines below):

What caused this error message?What should I do to address this issue?

**Comment by melvynator** [comment]
It looks like a permission issue or issue with your filesystem.

**Comment by skywalker2256** [comment]
> It looks like a permission issue or issue with your filesystem.
There should be no problem with file permissions. It seems that the file is damaged or the partition file has been deleted due to timeout. There is no problem with writing small amounts of data. However, when the data volume is too large, some partitions may not be able to be opened. The replica node reports an error and the partition does not exist. Is there any recommended configuration? Thank you very much!

**Comment by skywalker2256** [comment]
I've identified the issue. It was caused by the installation of 'McAfee' on the server. Uninstalling it resolved the error. Thank you for your support.
