### ISSUE TITLE
Allow stateful functions for filter push-down in query optimizer

### ISSUE THREAD

**Issue by jaijhala** [ClickHouse/ClickHouse#57287]
Feature request:
Implement more accurate check for stateful functions inside the query optimization.

Best explained with the example below: 

1). Create table: 

```
CREATE TABLE IF NOT EXISTS test
(
signal LowCardinality(String),
deviceelementpath LowCardinality(String),
siteelementpath LowCardinality(String),
intervalutc DateTime64(0, 'UTC'),
value Nullable(Float32)
) ENGINE = MergeTree() ORDER BY (signal, siteelementpath, deviceelementpath, intervalutc);
```

2). Ingest a sample row:

```
INSERT INTO test VALUES
('ENERGY', 'test', 'site01', '2023-10-03 18:00:00', 12.24);
```

3). Create a VIEW:

```
CREATE VIEW successful_view
(
`deviceelementpath` LowCardinality(String),
`siteelementpath` LowCardinality(String),
`signal` LowCardinality(String),
`intervalutc` DateTime64(0, 'UTC'),
`value` Nullable(Float32)
) AS
SELECT
deviceelementpath,
siteelementpath,
signal,
intervalutc,
value
FROM test
WHERE signal = 'ENERGY'
ORDER BY
signal ASC,
siteelementpath ASC,
deviceelementpath ASC,
intervalutc ASC;
```

4). Running an explain:

```
explain indexes=1
SELECT * from successful_view where intervalutc >= '2023-10-03 18:00:00' AND deviceelementpath = 'test';
```

gives me this (using 3 primary keys):

```
PrimaryKey
Keys:
signal
deviceelementpath
intervalutc
```

5).  If I now create a VIEW as:

```
CREATE VIEW failed_view
(
`deviceelementpath` LowCardinality(String),
`siteelementpath` LowCardinality(String),
`signal` LowCardinality(String),
`intervalutc` DateTime64(0, 'UTC'),
`value` Nullable(Float32),
`RDiff` Nullable(Float32)
) AS
SELECT
deviceelementpath,
siteelementpath,
signal,
intervalutc,
value,
if(runningDifference(value) < 0, NULL, runningDifference(value)) AS RDiff
FROM test
WHERE signal = 'ENERGY'
ORDER BY
signal ASC,
siteelementpath ASC,
deviceelementpath ASC,
intervalutc ASC;
```

Stateful function in above is `runningDifference(value)`

6). Explain index now:

```
explain indexes=1
SELECT * from failed_view where intervalutc >= '2023-10-03 18:00:00' AND deviceelementpath = 'test';
```

gives me:

```
PrimaryKey
Keys:
signal
```

Hence only using 1 primary key.

**Comment by jaijhala** [comment]
One note to clarify based on the testing so far: This only seems to happen when you query the VIEW, if you query the table directly it still uses all the primary keys. 

For example: 

```
explain indexes=1
SELECT * from test where intervalutc >= '2023-10-03 18:00:00' AND deviceelementpath = 'test' AND signal = 'ENERGY';
```

gives: 

```

PrimaryKey
--
Keys:
signal
deviceelementpath
intervalutc
```

Whereas: 

```
explain indexes=1
SELECT * from failed_view where intervalutc >= '2023-10-03 18:00:00' AND deviceelementpath = 'test'AND signal = 'ENERGY';
```

gives: 

```
PrimaryKey
--
Keys:
signal
```

**Comment by den-crane** [comment]
You actually misunderstood something. It's not possible to pushdown here, because it will change query result.

**Comment by den-crane** [comment]
it works as expected. You can use https://clickhouse.com/docs/en/sql-reference/statements/create/view#parameterized-view if you OK with a pushdown.

**Comment by nickitat** [comment]
@den-crane Denny, thanks for looking on this. I asked Jai to file this issue to think it over later, 'cause I think there is a room for improvement.
we're not talking about reordering this stateful function calculation with sorting. and if I'm not mistaken now it is calculated after filtering by `signal`. so all I want is to push down the filter by columns irrelevant to this function without touching sub-expression that calculates it.

**Comment by den-crane** [comment]
1. It uses `signal` because there is a filter `WHERE signal = 'ENERGY'` before runningDifference.
2. AFAIK you cannot pushdown anything, thus cannot use indexes. https://fiddle.clickhouse.com/19f8494e-670f-4b5d-a006-4e291f3f9960

**Comment by jumptable** [comment]
OK, thanks @den-crane for the pointer to parameterized views; this is what I was looking for.

**Comment by Algunenano** [comment]
Closed by https://github.com/ClickHouse/ClickHouse/pull/63132
