### ISSUE TITLE
Invalid reference in lambda

### ISSUE THREAD

**Issue by k-morozov** [ClickHouse/ClickHouse#57297]
**Describe the unexpected behaviour**
https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageDistributed.cpp#L897C57-L897C57

There is invalid reference (custom_key_ast) in lambda.

**Comment by Algunenano** [comment]
Where is the problem? `my_custom_key_ast`  receives ownership of `custom_key_ast` which is never used again (its scope finishes right there).

**Comment by k-morozov** [comment]
Althought there is no error, lambda has invalid reference to custom_key_ast. And custom_key_ast is after move.

**Comment by Algunenano** [comment]
I don't understand what you mean. `custom_key_ast` is not used at all in the lambda body.

**Comment by k-morozov** [comment]
then why do we add a reference to custom_key_ast in the lambda?
