### ISSUE TITLE
serialize_flag in AggregateFunctionNullVariadic doesn't using

### ISSUE THREAD

**Issue by k-morozov** [ClickHouse/ClickHouse#57296]
**Describe the unexpected behaviour**
https://github.com/ClickHouse/ClickHouse/blob/master/src/AggregateFunctions/Combinators/AggregateFunctionNull.cpp#L148

We don't use serialize_flag and there are 2 equals results:
```
return std::make_shared<AggregateFunctionNullVariadic<false, true>>(nested_function, arguments, params);
```

**Comment by Algunenano** [comment]
https://github.com/ClickHouse/ClickHouse/pull/56212
