### ISSUE TITLE
Something about HDFS and configurations

### ISSUE THREAD

**Issue by alexryndin** [ClickHouse/ClickHouse#57317]
Шаги к воспроизведению:
1. создать таблицу с движком типа hdfs
2. в hdfs-site.xml добавить строчки следующего вида:
```
<configuration xmlns:xi="http://www.w3.org/2001/XInclude">
<xi:include href="mounttable.xml" />
<!-- тут обычный конфиг от hdfs -->
</configuration>
```
3. Попытаться поселектить из созданной таблицы.

**Does it reproduce on recent release?**
не проверял, крешится на 23.1.3 с ошибкой вида:
```Received exception from server (version 23.1.3):
Code: 210. DB::Exception: Received from localhost:9000. DB::Exception: Unable to create builder to connect to HDFS: hdfs://mycluster/ HdfsBadConfigFoumat: Config cannot parse configure file: "/etc/hadoop/conf/hdfs-site.xml". (NETWORK_ERROR)
```

**Comment by nickitat** [comment]
pls check this part of the docs: https://clickhouse.com/docs/en/operations/configuration-files#substitution

p.s. exception != crash

**Comment by alexryndin** [comment]
@nickitat 
1. it has nothing to do with clickhouse part of server configuration, but with hadoop configuration, which cannot be parsed if it uses xml includes as described here https://en.wikipedia.org/wiki/XInclude
2. clickhouse return exception if hadoop confuguration uses such a config, and therefore I consider this a bug and I think this issue has to be reopened.

**Comment by alexryndin** [comment]
@nickitat 
latest version 23.10.5
```
Received exception from server (version 23.10.5):
Code: 210. DB::Exception: Received from localhost:9000. DB::Exception: Unable to create builder to connect to HDFS: hdfs://appadmin@my_nameservice/ HdfsBadConfigFoumat: Config cannot parse configure file: "/etc/clickhouse-server/hdfs-site.xml". (NETWORK_ERROR)
```
hdfs-site.xml content:
```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration xmlns:xi="http://www.w3.org/2001/XInclude">
<xi:include href="mounttable.xml" />
        <property>
                <name>dfs.ha.namenodes.my_nameservice</name>
                <value>sdfsdf</value>
        </property>
</configuration>
```

**Comment by alexey-milovidov** [comment]
Support for XInclude in HDFS configuration is not our problem.

**Comment by alexey-milovidov** [comment]
Moreover, we don't develop or support HDFS integration.
