### ISSUE TITLE
Address not mapped to object on JOIN ON invalid condition

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#57324]
Report: https://s3.amazonaws.com/clickhouse-test-reports/57075/360d1b075af5d01702dda2cb76279d4b19439810/fuzzer_astfuzzerasan/report.html

```sql
CREATE TABLE t1 (`a` Int64, `b` Int64) ENGINE = MergeTree ORDER BY a;
CREATE TABLE t2 (`key` Int32, `val` Int64) ENGINE = MergeTree ORDER BY key;
insert into t1 Select number, number from numbers(100000);
insert into t2 Select number, number from numbers(100000);


SELECT
    1 * 1000.0001,
    (count(1.) = -2147483647) AND (count(a) = 1.1920928955078125e-7) AND (count(val) = 1048577) AND (sum(val) = ((NULL * 1048576) / -9223372036854775807)) AND (sum(a) = ((9223372036854775806 * 10000000000.) / 1048575))
FROM
(
    SELECT
        a,
        val
    FROM t1
    FULL OUTER JOIN t2 ON (t1.a = t2.key) OR (1 * inf) OR (t1.b = t2.key)
)
GROUP BY '65537'
    WITH CUBE
SETTINGS max_block_size = 100, receive_timeout = 10., receive_data_timeout_ms = 10000, alter_sync = 2, allow_suspicious_low_cardinality_types = 1, log_queries = 1, table_function_remote_max_addresses = 200, join_use_nulls = 1, allow_experimental_analyzer = 1, max_execution_time = 10., max_memory_usage = 10000000000, send_logs_level = 'fatal', allow_introspection_functions = 1, insert_keeper_fault_injection_probability = 0.
```

Notice the `OR (1 * inf)`.

Without the analyzer you get an exception: `Code: 403. DB::Exception: Unsupported JOIN ON conditions. Unexpected '1 * inf': While processing 1 * inf. (INVALID_JOIN_ON_EXPRESSION)`

Msan report with master/HEAD build: https://pastila.nl/?001c9b1c/9666a08a9345cbb717bff2c39477cd28#oKQQ/ZulUSb+6yHio0OgUw==

**Comment by Algunenano** [comment]
Happens also if I replace it with `(1 == 1)` (vs `DB::Exception: Ambiguous columns in expression '1 = 1' in JOIN ON section: While processing 1 = 1. (AMBIGUOUS_COLUMN_NAME)` without the analyzer.

No exceptions or errors if the condition is removed completely.

**Comment by devcrafter** [comment]
It looks like constant expression was handled incorrectly in JOIN ON i.e. `(1 * inf)`.
The whole expression considered to be TRUE, so FULL OUTER JOIN is converted to CROSS JOIN:
https://pastila.nl/?004035ba/42f0b854e7a292fb093ebb31e50c2fee#8eMLBBe08QGOI36SaGU15Q==

There is comment that we handle constants in a special way in ActionDAG in JOINs with analyzer, probably it's related to it - 
https://github.com/ClickHouse/ClickHouse/blob/2ed53e309bdd07e8292d351b801ffdc1509795ec/src/Planner/PlannerJoins.cpp#L406-L412

**Comment by alexey-milovidov** [comment]
Fixed.
