### ISSUE TITLE
AST fuzzer container improvements

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#57338]
We need some help with it since it doesn't mount the working directory into the container. Instead, it's bash to check it out.

The fix would be relatively easy, just remove half of the script [here](https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/fuzzer/run-fuzzer.sh#L16-L126) and [here](https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/fuzzer/run-fuzzer.sh#L354-L446), download binaries in python, and mounting the repository's root into $repo_dir

It would improve the state since now it checks out random staff intentionally.

As well, to prevent future confusion, the info in [line](https://github.com/ClickHouse/ClickHouse/blob/master/docker/test/fuzzer/generate-test-j2.py#L58) should be a to steps: a) `f"File {new_name} is generating... "` and b) `done`

**Comment by Felixoid** [comment]
The issue is highlighted because of merged https://github.com/ClickHouse/ClickHouse/pull/55836

**Comment by alexey-milovidov** [comment]
At least it works perfectly.
