### ISSUE TITLE
Analyzer ignores index expression over aliases of aliases

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#57333]
As per #57220, skip indices can be defined on alias columns.

The PR also introduced a glitch with the analyzer when the index expression is an alias of an alias. (Yes, we merged regardless as the issue is minor.) In this case, the skip index is not used. It is used with `allow_experimental_analyzer = 0` or when the alias points to a non-alias.

Repro in the SQL test of https://github.com/ClickHouse/ClickHouse/pull/57220/files

**Comment by ucasfl** [comment]
Already fixed in #60641.
