### ISSUE TITLE
Issue with Thread Safety during Multiple DELETE mutations

### ISSUE THREAD

**Issue by zhaihao** [ClickHouse/ClickHouse#57341]
I may have encountered a potential thread safety problem related to multiple DELETE mutations in ClickHouse.

```sql
-- Thread 1
ALTER TABLE test_table DELETE WHERE id = 1 AND toYYYYMM(timestamp) BETWEEN 202309 AND 202310;

-- Thread 2
ALTER TABLE test_table DELETE WHERE id = 2 AND toYYYYMM(timestamp) BETWEEN 202309 AND 202310;
```

I observed the potential thread safety problem when executing the above SQL queries simultaneously. It seems that the DELETE mutations on the same table, performed by different threads, may lead to unexpected behavior.

The table is partitioned based on the `toYYYYMM(timestamp)` function.

I know that ClickHouse already has a lightweight deletion feature, but we haven't upgraded to the new version of ClickHouse yet. I would like to know if there are any thread safety issues associated with using lightweight deletion.

**Comment by lampjian** [comment]
You may show the exceptions or something wrong in your perspective that others can give you a hand.

**Comment by alexey-milovidov** [comment]
It is safe to run many mutations in parallel.
