### ISSUE TITLE
(EXTRA *clickhouse.Exception=code: 1000, message: File access error: no space left on device

### ISSUE THREAD

**Issue by shivacr** [ClickHouse/ClickHouse#5735]
*Describe the bug*
We are trying to integrate clickhouse with kafka as part of vFlow project.
When there is continuous data getting inserted in CH we see below commit errors:

2019/06/25 10:45:30 commit err%!(EXTRA *clickhouse.Exception=code: 1000, message: File access error: no space left on device: /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238053_238053_0)
2019/06/25 10:45:30 commit err%!(EXTRA *clickhouse.Exception=code: 1000, message: File access error: no space left on device: /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238048_238048_0)
2019/06/25 10:45:31 commit err%!(EXTRA *clickhouse.Exception=code: 76, message: Cannot open file /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238041_238041_0/tcpMeanRTT.mrk, errno: 28, strerror: No space left on device)
2019/06/25 10:45:31 commit err%!(EXTRA *clickhouse.Exception=code: 76, message: Cannot open file /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238038_238038_0/time.bin, errno: 28, strerror: No space left on device)
2019/06/25 10:45:31 commit err%!(EXTRA *clickhouse.Exception=code: 76, message: Cannot open file /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238035_238035_0/applicationId.mrk, errno: 28, strerror: No space left on device)
2019/06/25 10:45:31 commit err%!(EXTRA *clickhouse.Exception=code: 76, message: Cannot open file /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238030_238030_0/flowEndSysUpTime.bin, errno: 28, strerror: No space left on device)
2019/06/25 10:45:31 commit err%!(EXTRA *clickhouse.Exception=code: 76, message: Cannot open file /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238032_238032_0/ingressVRFID.bin, errno: 28, strerror: No space left on device)
2019/06/25 10:45:31 commit err%!(EXTRA *clickhouse.Exception=code: 76, message: Cannot open file /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238050_238050_0/sourceTransportPort.bin, errno: 28, strerror: No space left on device)
2019/06/25 10:45:31 commit err%!(EXTRA *clickhouse.Exception=code: 76, message: Cannot open file /var/lib/clickhouse/data/vflow/netflowv9/tmp_insert_20190625_238034_238034_0/tcpConnectionSetupTime.mrk, errno: 28, strerror: No space left on device)

root@rdserv-1:~/go/src/vflow/consumers/clickhouse# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            6.9G     0  6.9G   0% /dev
tmpfs           1.4G   30M  1.4G   3% /run
/dev/sda5        92G   28G   60G  32% /
/dev/sdb5        92G  5.7G   81G   7% /usr
tmpfs           6.9G     0  6.9G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           6.9G     0  6.9G   0% /sys/fs/cgroup
/dev/sda1        19G   81M   18G   1% /boot
/dev/sdb6        55G  439M   52G   1% /tmp
/dev/sdb1       733G   42G  654G   7% /home
tmpfs           1.4G   32K  1.4G   1% /run/user/116
tmpfs           1.4G   44K  1.4G   1% /run/user/1000
tmpfs           1.4G     0  1.4G   0% /run/user/0

But there is a lot of memory available.

**How to reproduce**
Keep sending contiuous  Netflow traffic to vFlow which will produce to kafka and CH will consume from kafka.

* ClickHouse server version to use
ClickHouse server version 19.8.3 revision 54420

**Expected behavior**
It is expected to work without any errors

**Additional context**
Please let me know if there is any workaround available.

**Comment by den-crane** [comment]
>/dev/sda5 92G 28G 60G 32% /

free only 28GB. It could be eaten in a second by inactive parts.

**Comment by shivacr** [comment]
-------
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5        92G  28G   60G 32% /
-------
Available is 60G not 28G. What should be the ideal free space for clickhouse to run ?

There are insertions going on now, so the space seems bigger:
root@rdserv-1:~# df -h /var/lib/clickhouse/ 
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5        92G  7.1G   80G   9% /
root@rdserv-1:~#

**Comment by den-crane** [comment]
>What should be the ideal free space for clickhouse to run ?
Depends of you requirements and environment.
You can move DB to /home from /var using symlinks or using CH settings

```
    <!-- Path to data directory, with trailing slash. -->
    <path>/var/lib/clickhouse/</path>
    <!-- Path to temporary data for processing hard queries. -->
    <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
```

**Comment by alexey-milovidov** [comment]
`no space left on device` has one of the possible reasons:
- there is literally no space left on device;
- the filesystem cannot allocate more inodes (probably not the reason, because it should be thrown on `open` not `write`);
- some other limits on space have been configured and exceeded.
