### ISSUE TITLE
Cannot create a MaterializedMySQL database

### ISSUE THREAD

**Issue by iseehell** [ClickHouse/ClickHouse#57351]
when I ceate a MaterializedMySQL databse  ch produces a error log
**Code: 336. DB::Exception: MaterializedMySQL is an experimental database engine. Enable allow_experimental_database_materialized_mysql to use it. (UNKNOWN_DATABASE_ENGINE) (version 23.9.2.56 (official build))**
**the value of allow_experimental_database_materialized_mysql has been set 1**
Query:
CREATE DATABASE test22
ENGINE = MaterializedMySQL(
  '172.16.1.215:3306',
  'test22',
  'clickhouse',
  'clickhouse'
);

**Comment by Baojia-Yang** [comment]
You can put this variable in the users.xml file, which is in the same directory as config.xml.
![Screenshot from 2023-12-02 23-09-57](https://github.com/ClickHouse/ClickHouse/assets/35793101/48c54f77-62e6-40c2-988b-55ed6f97afc9)

**Comment by iseehell** [comment]
> You can put this variable in the users.xml file, which is in the same directory as config.xml. ![Screenshot from 2023-12-02 23-09-57](https://private-user-images.githubusercontent.com/35793101/287456217-48c54f77-62e6-40c2-988b-55ed6f97afc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5OTc2OTQsIm5iZiI6MTcwMTk5NzM5NCwicGF0aCI6Ii8zNTc5MzEwMS8yODc0NTYyMTctNDhjNTRmNzctNjJlNi00MGMyLTk4OGItNTVlZDZmOTdhZmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAxMDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ODA0NWYzZTY4YzQyZmNhZTdkNDYzMzA1ODdkOTEyNzAzZTU1MzA2ZGM2OWE3Y2VlNjNhNDY3MDQ1ZDI3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V5_sg5QucZSJ2ClqMnpz9ImxMOfyFSE_wkpWmCpYrKA)

thanks it works
