### ISSUE TITLE
wrong size0 result for Array column when column name contains dot

### ISSUE THREAD

**Issue by zeromem** [ClickHouse/ClickHouse#57356]
**How to reproduce**
* install a brand-new clickhouse `curl https://clickhouse.com/ | sh`
* table schema:
```sql
CREATE TABLE tdot
(
    `k` Int32,
    `a.b` Array(String)
)
ENGINE = MergeTree
ORDER BY k
SETTINGS min_bytes_for_wide_part = 0
```
here the Array column `a.b` contains a dot which lead to the bug.
* select size0
```sql
SELECT `a.b`.size0 FROM tdot;
```
* the result is wrong
```sql
SELECT `a.b`.size0
FROM tdot

Query id: c5e85952-c990-4798-aee3-171b2c5a5380

Ok.

0 rows in set. Elapsed: 0.001 sec.
```

**Expected behavior**

> A clear and concise description of what you expected to happen.
the result of the above sql should be `1`. 

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**
it get a wrong file name [here]( https://github.com/ClickHouse/ClickHouse/blob/4c0efb026234961d977c3100c48adb7afe346bc0/src/DataTypes/Serializations/ISerialization.cpp#L203C12-L203C12)

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/52069
