### ISSUE TITLE
SummingMergeTree inconsistent result set using 'final'

### ISSUE THREAD

**Issue by MikeAmputer** [ClickHouse/ClickHouse#57368]
The SELECT statement from the SummingMergeTree table using the 'final' keyword returns a different set of rows depending on whether the summed column is included in the query.

`ClickHouse client version 23.10.5.20 (official build).`
`Connected to ClickHouse server version 23.10.5 revision 54466.`

```sql
create table sum_test (
  id       Int32,
  value    Int32
)
engine = SummingMergeTree(value)
order by id
primary key id

insert into sum_test (id, value) values (1, 1), (2, 1)
insert into sum_test (id, value) values (1, -1)
```

```sql
select * from sum_test final

┌─id─┬─value─┐
│  2 │     1 │
└────┴───────┘
```

```sql
select id from sum_test final

┌─id─┐
│  2 │
└────┘
┌─id─┐
│  1 │
└────┘
```

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/46534
