### ISSUE TITLE
Group By with IF expression produces error

### ISSUE THREAD

**Issue by olegkv** [ClickHouse/ClickHouse#57365]
**Unexpected behavior, getting error:**

To reproduce, run this query:
_select
	if(1 = 0, number, 0) as Num,
	1 as Const
from numbers(10)
group by
	Num,
	Const_
	
Workaround to avoid error is to make sure column is present in both cases for IF expression:
_select
	if(1 = 0, number, number * 0) as Num,
	1 as Const
from numbers(10)
Group by
	Num,
	Const_
	
**Expected behavior: I'd expect that first query should run with no errors**

**Comment by ucasfl** [comment]
Duplicate with #56772.
