### ISSUE TITLE
experimental flag and JSON column type not working 

### ISSUE THREAD

**Issue by 3goats** [ClickHouse/ClickHouse#57371]
I'm using ClickHouse `23.10.5.20` and following the example in this blog https://clickhouse.com/docs/en/integrations/data-formats/json.

As per the instruction I'm setting the experimental flag using the the following SQL. 
```
DROP TABLE IF EXISTS github_json;

SET allow_experimental_object_type=1;

CREATE table github_json(event JSON) ENGINE = MergeTree ORDER BY tuple()
```

However this returns the following error: 

```
SQL Error [44] [07000]: Code: 44. DB::Exception: Cannot create table with column 'event' which type is 'Object('json')' because experimental Object type is not allowed. Set setting allow_experimental_object_type = 1 in order to allow it. (ILLEGAL_COLUMN) (version 23.10.5.20 (official build))
```

I've tried this from DBeaver and the Play web UI. Same result in both. 

Am I missing something

**Comment by Algunenano** [comment]
This looks like a problem in the clients using different sessions for the different queries: the setting is set in a session, the create query is sent in a different session.

You can try passing the setting in the query itself:
```
CREATE table github_json(event JSON) ENGINE = MergeTree ORDER BY tuple() AS Select '' LIMIT 0 SETTINGS allow_experimental_object_type=1;
```

**Comment by TimaevAlexandr** [comment]
While running the Ansible playbook, that creates tables, this 'trick' is not working.
