### ISSUE TITLE
[JSON] Missing columns when doing query

### ISSUE THREAD

**Issue by wzjjack** [ClickHouse/ClickHouse#57376]
Clickhouse version: 23.5.4.25

I'm running some tests for data type JSON

my test table:
```
set allow_experimental_object_type = 1;
create table t_map_test (
                            `user_id` String,
                            `time` Int64,
                            `event_name` String,
                            `payload` JSON
) engine = MergeTree order by `time`;

```

Some data will insert to the table

- Record A: `insert into t_map_test values ('test', 123123123, 'test', '{"keyword1": "test"}');`
- Record B: `insert into t_map_test values ('test', 123123123, 'test', '{"keyword1": "test", "keyword2": "test2"}');`

and the `payload` is dynamic, maybe there is more the `keyword1` and `keyword2`. 

If I do querying: `select * from t_map_test where payload.keyword1 like '%abc% or payload.keyword2 like '%abc%'` before `Record B` insert to the table, then clickhouse will throw `Missing columns: payload.keyword2`. I don't know how to deal with this.

Should I set a static `payload` object and make sure all of `keyword*` is in `payload` object?

**Comment by wzjjack** [comment]
@den-crane

**Comment by franz101** [comment]
Same here
