### ISSUE TITLE
Speedup greatCircleDistance function with the code from Andrey Aksenov

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5739]
[1_Самый_лучший_GEODIST_к_западу.pdf](https://github.com/yandex/ClickHouse/files/3324740/1_._._GEODIST_._.pdf)

https://github.com/sphinxsearch/sphinx/blob/409f2c2b5b2ff70b04e38f92b6b1a890326bad65/src/sphinxexpr.cpp#L3950

Obtain permission to use this code fragment with Apache 2 or MIT or BSD license.
Add performance test.

**Comment by shodanium** [comment]
As the original author, I hereby grant the permission to use all the GEODIST() implementation related functions under the MIT license.

Let me know if you need anything even more official :)
