### ISSUE TITLE
Link time is very long comparing to CH2022

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#57409]
From my feeling, the link time become longer, comparing to CH2022. I don't have exact number but now link time is 10 minute long that is very abnormal. The build type is `CMAKE_BUILD_TYPE=RelWithDebInfo`

**Operating system**
Ubuntu 20.04.6 LTS

**Cmake version**
cmake version 3.25.3

**Ninja version**
1.10.0

**Compiler name and version**
Clang-17

**Full cmake and/or ninja output**
<img width="551" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/1518453/68785acb-98ea-48f8-94ae-2423dd6101c5">

**Comment by Algunenano** [comment]
Duplicate from https://github.com/ClickHouse/ClickHouse/issues/56018
