### ISSUE TITLE
 TOO_LARGE_STRING_SIZE calculates about 5 799 864 072  Gb - too much.

### ISSUE THREAD

**Issue by alexeik** [ClickHouse/ClickHouse#57410]
**Describe what's wrong**
`Too large string size: 5799864072056097232. The maximum is: 1073741824`
i have no such large string in http post request. 
5799864072 056 097 232 bytes = its about 5 799 864 072  Gb 
my query about 200 mb of  unzipped  data and 10-15 mb zipped.

> A clear and concise description of what works not as it is supposed to.
Error reporting from clickhouse seems to be broken for TOO_LARGE_STRING_SIZE.

**How to reproduce**

dont know

**Expected behavior**
Needs human readable and acceptable error text

**Error message and/or stacktrace**

2023.12.01 05:52:50.698857 [ 6934 ] {7f69ed6e-81c6-4220-9636-727a10f0a2c8} <Error> DynamicQueryHandler: Code: 131. DB::Exception: Too large string size: 5799864072056097232. The maximum is: 1073741824. To increase the maximum, use setting format_binary_max_string_size: (at row 7355)
: While executing BinaryRowInputFormat. (TOO_LARGE_STRING_SIZE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe18d895 in /usr/bin/clickhouse
1. ? @ 0x96b4618 in /usr/bin/clickhouse
2. DB::SerializationString::deserializeBinary(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x12a5b0ac in /usr/bin/clickhouse
3. DB::BinaryFormatReader::readField(DB::IColumn&, std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::ISerialization const> const&, bool, String const&) @ 0x149d2276 in /usr/bin/clickhouse
4. DB::RowInputFormatWithNamesAndTypes::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x149d52d8 in /usr/bin/clickhouse
5. DB::IRowInputFormat::generate() @ 0x149b08ae in /usr/bin/clickhouse
6. DB::ISource::tryGenerate() @ 0x14933695 in /usr/bin/clickhouse
7. DB::ISource::work() @ 0x14933206 in /usr/bin/clickhouse
8. DB::ExecutionThreadContext::executeTask() @ 0x1494ce0a in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14941e7b in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14940fd1 in /usr/bin/clickhouse
11. DB::PipelineExecutor::execute(unsigned long) @ 0x14940c71 in /usr/bin/clickhouse
12. DB::CompletedPipelineExecutor::execute() @ 0x1493f1dd in /usr/bin/clickhouse
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) @ 0x13b1f3d1 in /usr/bin/clickhouse
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x14893413 in /usr/bin/clickhouse
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1489772e in /usr/bin/clickhouse
16. DB::HTTPServerConnection::run() @ 0x1490617d in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x17838054 in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x1783927b in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x179c0b07 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x179be53d in /usr/bin/clickhouse
21. start_thread @ 0x81da in /usr/lib64/libpthread-2.28.so
22. __clone @ 0x39e73 in /usr/lib64/libc-2.28.so
 (version 23.3.1.2823 (official build))

**Additional context**

**Comment by alexeik** [comment]
more 

2023.12.01 05:50:05.070656 [ 10223 ] {291a144e-7fb1-4523-8fe3-77403f32c812} <Error> DynamicQueryHandler: Code: 131. DB::Exception: Too large string size: 4296709472344877082. The maximum is: 1073741824. To increase the maximum, use setting format_binary_max_string_size: (at row 18909)
: While executing BinaryRowInputFormat. (TOO_LARGE_STRING_SIZE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe18d895 in /usr/bin/clickhouse
1. ? @ 0x96b4618 in /usr/bin/clickhouse
2. DB::SerializationString::deserializeBinary(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x12a5b0ac in /usr/bin/clickhouse
3. DB::BinaryFormatReader::readField(DB::IColumn&, std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::ISerialization const> const&, bool, String const&) @ 0x149d2276 in /usr/bin/clickhouse
4. DB::RowInputFormatWithNamesAndTypes::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x149d52d8 in /usr/bin/clickhouse
5. DB::IRowInputFormat::generate() @ 0x149b08ae in /usr/bin/clickhouse
6. DB::ISource::tryGenerate() @ 0x14933695 in /usr/bin/clickhouse
7. DB::ISource::work() @ 0x14933206 in /usr/bin/clickhouse
8. DB::ExecutionThreadContext::executeTask() @ 0x1494ce0a in /usr/bin/clickhouse
9. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14941e7b in /usr/bin/clickhouse
10. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14940fd1 in /usr/bin/clickhouse
11. DB::PipelineExecutor::execute(unsigned long) @ 0x14940c71 in /usr/bin/clickhouse
12. DB::CompletedPipelineExecutor::execute() @ 0x1493f1dd in /usr/bin/clickhouse
13. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) @ 0x13b1f3d1 in /usr/bin/clickhouse
14. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x14893413 in /usr/bin/clickhouse
15. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x1489772e in /usr/bin/clickhouse
16. DB::HTTPServerConnection::run() @ 0x1490617d in /usr/bin/clickhouse
17. Poco::Net::TCPServerConnection::start() @ 0x17838054 in /usr/bin/clickhouse
18. Poco::Net::TCPServerDispatcher::run() @ 0x1783927b in /usr/bin/clickhouse
19. Poco::PooledThread::run() @ 0x179c0b07 in /usr/bin/clickhouse
20. Poco::ThreadImpl::runnableEntry(void*) @ 0x179be53d in /usr/bin/clickhouse
21. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
22. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 23.3.1.2823 (official build))

**Comment by Algunenano** [comment]
What are you sending to ClickHouse? Do you have a reproducer?

The error is not related to the size of the input of the query, but to the format. It's deserializing a binary value (for a string) and the serialized length is too big, most likely due to a problem in the input itself.

**Comment by den-crane** [comment]
@alexeik 
23.3.1.2823 is out of support

upgrade to 23.3.18.15

**Comment by alexeik** [comment]
thanks 
will try to look into input data
