### ISSUE TITLE
Arithmetic operation on DateTime doesn't save time zone.

### ISSUE THREAD

**Issue by radya100** [ClickHouse/ClickHouse#5743]
toStartOfInterval function does not work correctly.
SELECT
     toStartOfInterval (now (), toIntervalHour (12), 'UTC') - (3600 * 3) AS t1,
     toStartOfInterval (now (), toIntervalHour (12), 'UTC') AS t2
version 19.6.2.11

**Comment by alexey-milovidov** [comment]
I've changed the title of this bug accordingly:

```
SELECT
     toStartOfInterval (now (), toIntervalHour (12), 'UTC') - (3600 * 3) AS t1, toTypeName(t1),
     toStartOfInterval (now (), toIntervalHour (12), 'UTC') AS t2, toTypeName(t2)
```
