### ISSUE TITLE
Freeze partition by id doesn't work since above v19.4.4.33

### ISSUE THREAD

**Issue by AlexAkulov** [ClickHouse/ClickHouse#5744]
Перестал работать фриз партиций по ID с версии выше чем v19.4.4.33.
Вот к примеру 19.5.3.8
```
ALTER TABLE testdb.table1 FREEZE PARTITION ID '201810'
Received exception from server (version 19.5.3):
Code: 368. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: std::bad_typeid. 

0 rows in set. Elapsed: 0.003 sec. 
```
Пример таблички:
```
SELECT
    create_table_query,
    partition_key,
    primary_key
FROM system.tables
WHERE (database = 'project') AND (name = 'test')

Row 1:
──────
create_table_query: CREATE TABLE project.test (`event_time` DateTime, `event_date` Date DEFAULT toDate(event_time), `uuid` String) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test', '{replica}', event_date, event_date, 8192)
partition_key:      toYYYYMM(event_date)
primary_key:        event_date

```

Как теперь правильно фризить партиции по ID?

**Comment by filimonov** [comment]
Хм. А раньше работало?

`toYYYYMM(event_date)` возвращает число в формате 201906, которое нужно указывать без кавычек.

**Comment by AlexAkulov** [comment]
До версии v19.4.4.33 включительно, всё работало.
Пробовал указать число или toYYYYMM('201810'), тоже не работет.
```
09724b9d69a8 :) ALTER TABLE testdb.table1 FREEZE PARTITION ID '201810'

ALTER TABLE testdb.table1
    FREEZE PARTITION ID '201810'


Received exception from server (version 19.9.2):
Code: 368. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: std::bad_typeid. 

0 rows in set. Elapsed: 0.067 sec. 

09724b9d69a8 :) ALTER TABLE testdb.table1 FREEZE PARTITION ID 201810

Syntax error: failed at position 47:

ALTER TABLE testdb.table1 FREEZE PARTITION ID 201810

Expected string literal

09724b9d69a8 :) ALTER TABLE testdb.table1 FREEZE PARTITION ID toYYYYMM('201810')

Syntax error: failed at position 47:

ALTER TABLE testdb.table1 FREEZE PARTITION ID toYYYYMM('201810')

Expected string literal

09724b9d69a8 :) ALTER TABLE testdb.table1 FREEZE PARTITION ID 'toYYYYMM(\'201810\')'

ALTER TABLE testdb.table1
    FREEZE PARTITION ID 'toYYYYMM(\'201810\')'


Received exception from server (version 19.9.2):
Code: 368. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: std::bad_typeid. 

0 rows in set. Elapsed: 0.003 sec. 

09724b9d69a8 :)

```

**Comment by den-crane** [comment]
19.10.1.669

create table foo(D Date, S String) engine=MergeTree partition by toYYYYMM(D) order by S

ALTER TABLE foo
    FREEZE PARTITION ID '201810'
Ok.

**Comment by AlexAkulov** [comment]
@den-crane 
У меня таблицы созданы старым способом.

**Comment by filimonov** [comment]
А откуда вообще взялось это `ID` в команде?

Кажется стандартный синтаксис и документация используют единственный способ указания партиций - без всяких ID: `ALTER TABLE testdb.table1 FREEZE PARTITION 201810`.  Или я что-то пропустил?

**Comment by AlexAkulov** [comment]
Ну, как все знают в документации КХ многих вещей не написано)
Я вначале пробовал без ID по имени, там вообще всё очень неочевидно работает, особенно при восстановлении. Невозможно понять, что востановилось, а что нет.

**Comment by AntonVozdvizhenskiy** [comment]
> А откуда вообще взялось это ID в команде?
В документации есть. 

https://clickhouse.yandex/docs/ru/query_language/alter/#alter-how-to-specify-part-expr
Строковый идентификатор партиции. Идентификатор партиции используется для именования кусков партиции на файловой системе и в ZooKeeper. В запросах ALTER идентификатор партиции нужно указывать в секции PARTITION ID, в одинарных кавычках. Например, ALTER TABLE visits DETACH PARTITION ID '201901'.

И для нас проблема весьма актуальна:
Например из-за таких партиций.
```
┌─partition────────┬─partition_id─┐
│ ('2019-09-02',1) │ 20190902-1   │
│ ('2019-09-02',2) │ 20190902-2   │
```
```
$ PART=$(clickhouse-client -q "select partition from system.parts where table = 'sometable' limit 1;")
$ echo $PART
(\'2019-09-02\',0)
$ clickhouse-client -q "alter table somebase.sometable freeze partition $PART";
Code: 62. DB::Exception: Syntax error: failed at position 49: \'2019-09-02\',0). Unrecognized token
```

**Comment by nvartolomei** [comment]
@AntonVozdvizhenskiy just unescape returned before running freeze partition. In your case you just need to drop backslashes.

**Comment by den-crane** [comment]
@AntonVozdvizhenskiy 
```

create table Z1(A Int64, B Date) Engine=MergeTree Partition by (B,A) order by A;
insert into Z1 values (1,today());

 select partition, name,partition_id from system.parts where table='Z1';
┌─partition────────┬─name─────────────┬─partition_id─┐
│ ('2019-12-12',1) │ 20191212-1_1_1_0 │ 20191212-1   │
└──────────────────┴──────────────────┴──────────────┘

ALTER TABLE Z1
    FREEZE PARTITION ID '20191212-1'


Ok.
```
