### ISSUE TITLE
Does mysql_native_password is equal to double_sha1_password?

### ISSUE THREAD

**Issue by wbxsGithub** [ClickHouse/ClickHouse#57441]
Q:
Does mysql_native_password is equal to double_sha1_password?

Now i want to use a client demo to access clickhouse  with mysql_native_password plugin through mysql_port.
Because i didn't see any information about the mysql_native_password in the doc.

**Comment by wbxsGithub** [comment]
I tried to create a user using double_sha1_password to validate mysql_native_password. That's ok.
But I'm not sure if it's fully compatible.

**Comment by lampjian** [comment]
The mysql_native_password client authentication plugin hashes the password before sending it to the server.([document about the plugin](https://mariadb.com/kb/en/authentication-plugin-mysql_native_password/)) So the double_sha1_password is fully compatible with mysql clients typically.

**Comment by wbxsGithub** [comment]
thanks for your reply!
