### ISSUE TITLE
create a non exists table in show tables, then Code: 57 DB:Exception : Table xxx already exists. (TABLE_ALREADY_EXISTS)

### ISSUE THREAD

**Issue by pioneerjxf** [ClickHouse/ClickHouse#57456]
In clickhouse console, I created a distributed table, which was not exists in show tables result, And then it showed error message TABLE_ALREADY_EXISTS.
create table sql example 
`
create table db_4525.test
(
  `name` String
)
Engine = Distributed('cluster_c', '', 'db_4525_test_replica', rand())
`
the 4525 in 'db_4525' is a random id, every time is different. but the it showed error message:

> Code: 57. DB::Exception: Received from xx.xx.xx.xx. DB::Exception: Table db_4525.test already exists. (TABLE_ALREADY_EXISTS)

**Comment by lampjian** [comment]
`show tables` only display current server tables. You shall check all your servers one by one.
