### ISSUE TITLE
position function behaves incorrectly when used with arrayFold

### ISSUE THREAD

**Issue by arvindpunk** [ClickHouse/ClickHouse#57458]
**Describe what's wrong**

`position` function behaves incorrectly when used with `arrayFold` - fails to search string. I've verified all other intermediate states of `arrayFold` and other functions used are correct.

https://fiddle.clickhouse.com/80adfdb5-f671-4d8a-bb27-49d6fdfdada7

`position` function seems to fail string search and return 0 (substring not found).

**Does it reproduce on recent release?**

Confirmed on 23.10.3.1 on server as well as clickhouse-local

**How to reproduce**

refer to clickhouse fiddle - has a minimal reproducible setup

**Expected behavior**

It should return the correct position of the substring.

**Additional context**

I am using the nix version of clickhouse but seeing it's also reproducible on fiddle, I don't think that's relevant to the issue.

---
*offtopic: I spent multiple hours figuring out why it isn't working. If you're wondering how I found this bug, I was trying to solve this years' advent of code with clickhouse - helps to learn a lot of the cool functions ClickHouse offers! (also I'm slightly deranged).*

**Comment by rschu1ze** [comment]
Simpler repro: https://fiddle.clickhouse.com/1b5a7741-b441-4a8f-819d-1ea62e79ce38

@Lirikl There is a problem with `arrayFold()`, added with #49794, maybe you like to have a look?
