### ISSUE TITLE
partition name became negative when used %

### ISSUE THREAD

**Issue by chenk818** [ClickHouse/ClickHouse#57462]
step1：CREATE TABLE 
CREATE TABLE testlong
(
    `item_id` Int64,
    `dt` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/xx/xx/testlong/{shard}', '{replica}')
PARTITION BY item_id % 150
ORDER BY item_id

step2: insert 
insert into testlong values (12245704481,'dt1');
12245704481%150 = 131;

step3:
select partition from system.parts where table in ('testlong');
expected   (131) but the result is (-125)

**Comment by den-crane** [comment]
It's impossible to change because of backward compatibility.

You have to use `item_id % toInt64(150)` https://fiddle.clickhouse.com/d70b02fe-0e3e-4e0a-91c7-314447f761b8


```
SELECT toInt64(-12245704481) % toInt64(150);
-131


SELECT toInt64(-12245704481) % toUInt64(150);
35
```
