### ISSUE TITLE
MaterializedMySQL engine data query failed

### ISSUE THREAD

**Issue by haozxuan** [ClickHouse/ClickHouse#57460]
Problem Description:
When using the MaterializedMySQL engine to synchronize MySQL data, if MySQL encounters an SQL statement that CH cannot resolve, all data synchronized from MySQL in CH, including related database and table data, cannot be queried.

Reproduction Steps:
1. Suppose you have a MySQL 5.7 or 8.X, and then create a database 'demo' and a table 'demo.test' for synchronization to CH using MaterializedMySQL. Everything works perfectly and all queries are normal.
2. When another SQL statement is executed in MySQL, you will not be able to query the data that has been synchronized to CH. The steps are as follows: Create a new database 'bad' and a table 'bad.anything' in MySQL. You will find that everything is normal in MySQL.
3. In MySQL, you can view the related table creation statements through 'show create table demo.test' and 'show create table bad.anything'. In fact, you will find that MySQL has ignored the pk_id field, but the worst thing has happened.
4. The 'demo.test' that could be queried normally in CH can no longer be queried. I have tested this exception in CH versions 22.8 and 23.8; anyway, I am very grateful to the CH maintenance team for providing such a great service, please feel free to ask if there is anything I can assist with.

In Mysql server:

```
create database demo;
create table demo.test
(
	id int unsigned auto_increment
	 primary key,
	 other varchar(255) not null
)

create database bad;
create table bad.anything
(
	id int unsigned auto_increment,
	other varchar(255) not null,
	primary key `pk_id`(id)
)
```

Expected Effect:
Even if CH receives unrecognizable or erroneous SQL statements, it can silently ignore them, without affecting the data subsequently synchronized to CH, and without affecting the data already synchronized to CH.

```[tasklist]
### Tasks
```

**Comment by alexey-milovidov** [comment]
We don't support MaterializedMySQL.
