### ISSUE TITLE
Kerberos support for ZK and HDFS

### ISSUE THREAD

**Issue by kindred77** [ClickHouse/ClickHouse#5747]
Does CK support kerberos authorized for ZK and HDFS?

Since we are using HDFS and ZK with kerberos.

**Comment by alesapin** [comment]
No, currently CH doesn't support kerberos. But we have plans to add it.

**Comment by kainever7** [comment]
@blinkov Kerberos support for ZK and HDFS on 28 Jun  ---- Which version？

**Comment by blinkov** [comment]
@kainever7 as far as I remember it's still missing

**Comment by amitsudharshan** [comment]
Does this feature mean using Kerberos for authentication for all ClickHouse ACLs, or is this somehow specific to Zk/hdfs. I’m very interested in Kerberos for all.

Thanks!

**Comment by akonyaev90** [comment]
We finally started working on this issue.

Now we have this priority.

If anyone has ideas or advice, write here.

**Comment by afedotov89** [comment]
@akonyaev90 Hello! when can this feature be released? Thanks

**Comment by glader** [comment]
@alexey-milovidov do you have any plans to implement this functionality?

**Comment by alexey-milovidov** [comment]
My team is not working on this feature, we hope it will be implemented by community (maybe by Altinity or ArenaData, but I'm not sure).

**Comment by alexey-milovidov** [comment]
Kerberos for HDFS: #16621
Kerberos for Kafka: #12771
Kerberos for ClickHouse own auth: #14995

Kerberos for ZK: not currently in progress.

**Comment by ys-zhaoyh** [comment]
How do I use kerberos authorized HDFS engine in HA mode?@alexey-milovidov

**Comment by alexey-milovidov** [comment]
@ys-zhaoyh The example is located here https://github.com/ClickHouse/ClickHouse/pull/16621/files in tests
Look at the files in `test_storage_kerberized_hdfs` directory.

**Comment by alexey-milovidov** [comment]
As far as I know, there is no ongoing work for adding Kerberos support for ZooKeeper.
