### ISSUE TITLE
Is there a way to access index without querying the column?

### ISSUE THREAD

**Issue by cw9** [ClickHouse/ClickHouse#57484]
Hi ClickHouse friends,

ClickHouse supports creating data skipping index and can make use of the indexes directly when the column is queried, I could not find any documentation or functions to check the indexes directly without querying the underlying query. 

Here is an example to explain what I mean:

```
create table mt( 
  a Int64, 
  b String, 
  INDEX index_b b TYPE ngrambf_v1(4, 32768, 8, 0) GRANULARITY 1,
  b_substring String,
) Engine=MergeTree order by (a)
```
```
insert into mt select 1, repeat(toString(number), 10), substring(toString(number), 2, 6) from numbers(10000000)
```

In this example, `b` is representing a big string column with `ngrambf` index built already, and `b_substring` is a substring of b.

```
EXPLAIN indexes = 1
SELECT count()
FROM mt
WHERE b LIKE '%123456%'

┌─explain───────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))       │
│   Aggregating                                     │
│     Expression (Before GROUP BY)                  │
│       Filter (WHERE)                              │
│         ReadFromMergeTree (chao_test.mt)          │
│         Indexes:                                  │
│           PrimaryKey                              │
│             Condition: true                       │
│             Parts: 5/5                            │
│             Granules: 1221/1221                   │
│           Skip                                    │
│             Name: index_b                         │
│             Description: ngrambf_v1 GRANULARITY 1 │
│             Parts: 5/5                            │
│             Granules: 803/1221                    │
└───────────────────────────────────────────────────┘
```
Filtering on b can benefit from the index and skip 400+ granules.

meanwhile querying `b_substring` can not benefit of the index.
```
EXPLAIN indexes = 1
SELECT count()
FROM mt
WHERE b_substring = '123456'

┌─explain─────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY)) │
│   Aggregating                               │
│     Expression (Before GROUP BY)            │
│       Filter (WHERE)                        │
│         ReadFromMergeTree (chao_test.mt)    │
│         Indexes:                            │
│           PrimaryKey                        │
│             Condition: true                 │
│             Parts: 5/5                      │
│             Granules: 1221/1221             │
└─────────────────────────────────────────────┘
```

Is there a way for me to check the `index_b`, without actually scanning `b`? 
Potentially something like below to skip some granules.
```
SELECT count() FROM mt WHERE b_substring = '123456' AND **index_check**(index_b, '%123456%')
```

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/other-functions#indexhint

index points to a granule, granule stores a lot of rows, without reading the column we just know that granule may contain this value, basically using index we can establish that these 8192000 rows may contain this value.

**Comment by cw9** [comment]
great! This does exactly what I want, thanks @den-crane !

```EXPLAIN indexes = 1
SELECT count()
FROM mt
WHERE (b_substring = '123456') AND indexHint(b LIKE '%123456%')


Connecting to database chao_test at localhost:9000 as user default.
Connected to ClickHouse server version 23.8.3 revision 54465.

┌─explain───────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))       │
│   Aggregating                                     │
│     Expression (Before GROUP BY)                  │
│       Filter (WHERE)                              │
│         ReadFromMergeTree (chao_test.mt)          │
│         Indexes:                                  │
│           PrimaryKey                              │
│             Condition: true                       │
│             Parts: 5/5                            │
│             Granules: 1221/1221                   │
│           Skip                                    │
│             Name: index_b                         │
│             Description: ngrambf_v1 GRANULARITY 1 │
│             Parts: 5/5                            │
│             Granules: 803/1221                    │
└───────────────────────────────────────────────────┘
```

**Comment by cw9** [comment]
Hi @den-crane turns out the `indexHint` function is doing something unexpected, it is still scanning the column expressed in it, can we reopen this issue?

For example, this query does not use `indexHint()` and scans 148MB data in total.
```
SELECT count()
FROM mt
WHERE b_substring LIKE '%'
┌──count()─┐
│ 10000000 │
└──────────┘

1 row in set. Elapsed: 0.053 sec. Processed 10.00 million rows, 148.89 MB (190.24 million rows/s., 2.83 GB/s.)
```

This query use `indexHint()` which does not impact the query result but scans 927MB data in total.
```
SELECT count()
FROM mt
WHERE (b_substring LIKE '%') AND indexHint(b LIKE '%')
┌──count()─┐
│ 10000000 │
└──────────┘

1 row in set. Elapsed: 0.092 sec. Processed 10.00 million rows, 927.78 MB (108.83 million rows/s., 10.10 GB/s.)
```

The scanning behavior is not consistent though, there are some cases the `indexHint` does what I was expecting which is only checking the index and not scanning the data in the column, but sometimes it scans the column data unexpectedly. Is there anyway to force it to only check the index?

**Comment by SuzyWangIBMer** [comment]
Hi, @alexey-milovidov, this seems like an issue that would bring down our performance vastly in some cases. Any thoughts on how to resolve this?

**Comment by alexey-milovidov** [comment]
The `indexHint` function does not inhibit reading. However, it wasn't designed to do it.
If you want to make the optimization so that the columns under `indexHint` are not read unless required in other places, it will be welcomed.

**Comment by SuzyWangIBMer** [comment]
I can spend some time here to explore the options. Any suggestion/guide in mind where I can start?

**Comment by alexey-milovidov** [comment]
Somewhere in Analyzer where we collect columns needed for reading.

**Comment by cw9** [comment]
hi, is this being fixed in the latest version?

**Comment by alexey-milovidov** [comment]
No, we closed it as the question was answered. There is no implementation for this.
