### ISSUE TITLE
When out of disk space Kafka engine will drop messages

### ISSUE THREAD

**Issue by mvanderkroon** [ClickHouse/ClickHouse#5749]
**Describe the bug**
Under certain circumstances the Kafka engine will commit message offsets without persisting the corresponding messages. In our case this happened when the Clickhouse cluster ran out of disk space: messages are still being pulled from Kafka, failed to store to disk but then offsets are committed anyway. This may cause message loss.

**How to reproduce**
* Clickhouse version: v19.1.14
* Set up a table with Kafka engine (`ENGINE = Kafka()`), listening to a Kafka topic
* Feed data into the Kafka topic
* Ensure there is no more space left on the device where Clickhouse stores its data

**Expected behavior**
I would expect the Clickhouse Kafka engine to not commit offsets for messages that were failed to persist to disk. This would allow the sysadmin to fix the underlying issues (insufficient disk space in our case) and after which Clickhouse would start 'backfilling' data from where it left off.

**Comment by alexey-milovidov** [comment]
@filimonov Please validate that now we are doing commit only after successful write.

**Comment by filimonov** [comment]
We are. 

But error handling is still very poor in Kafka (in case of error it just leave the consumer group to join it back after 5 sec, creating 2 rebalances per one error :) ) , i think i know how to improve that, i will try to do it next week and also create some test for that issue.
