### ISSUE TITLE
How to use query cache as the best practice for a ClickHouse cluster based on nginx as load balancing

### ISSUE THREAD

**Issue by xiaolei565** [ClickHouse/ClickHouse#57499]
Hello ClickHouse Community, 

Our clickhouse cluster uses nginx as SLB .When querying, we query distributed tables, and nginx selects a clickhouse machine as the query node randomly . 
now, we want to install new version clickhouse to use the new feature query cache, but we find only query node can store the query cache（cache distributed table）. **Once nginx selects other nodes ，it need to cache the same query again** 

So，we want to know what is best practice for this case about query cache
![结果缓存-23 11](https://github.com/ClickHouse/ClickHouse/assets/12630533/f6389916-439b-4c90-8cae-fd397cef54db)

**Comment by den-crane** [comment]
I doubt that it's possible to configure with nginx.
Have you considered chproxy https://www.chproxy.org/ ? Chproxy has query cache and able to share own cache among multiple chproxy servers.
