### ISSUE TITLE
Change contrib library from git submodule to Github download zip ?

### ISSUE THREAD

**Issue by qhsong** [ClickHouse/ClickHouse#57524]
Clickhouse current use `git submodule` to manage third-party library, but it need checkout too much git history but not use.
So maybe we can consider change `git module` to github download zip。

Github support download any commit zip by URL such as:
`https://codeload.github.com/ClickHouse/llvm-project/zip/refs/heads/${COMMIT_ID}`

CMake also support Download and extra content like this:
```
file(DOWNLOAD ${URL})
file(ARCHIVE_EXTRACT xxx)
```

Compare `git clone llvm-project` need checkout 1.8G content,
Download zip only need 230MB zip file and unzip to 1.5GB files, not to mention we need checkout extra submodule in submodule.

Just wonder whether it works, If it works maybe I will try to do it.

**Comment by Algunenano** [comment]
You seem to be proposing to use a package manager without a package manager. That doesn't seem like a good idea.

**Comment by qhsong** [comment]
Yes, it works just like a simple package manager. Just inspire from Bazel…
So maybe need consider a package manager like vcpkg or conan?

I think Downloading web zip package by cmake is an easy way to change
current project.

**Comment by Algunenano** [comment]
> I think Downloading web zip package by cmake is an easy way to change current project.

And then how do you deal with updates in the submodules? Or local changes? Or test a new branch in a submodule? Doing that in cmake seems like a quick way to madness.

Submodules aren't great, but anything that wants to replace it must be better. If downloading large git repos is your main worry, check if shallow cloning them makes it better.

**Comment by rschu1ze** [comment]
Btw., we provide script `contrib/update-submodules.sh` which does a shallow and sparse checkout of submodules, please see the [docs](https://clickhouse.com/docs/en/development/developer-instruction#cloning-a-repository-to-your-development-machine) for more information.

**Comment by qhsong** [comment]
> Btw., we provide script `contrib/update-submodules.sh` which does a shallow and sparse checkout of submodules, please see the [docs](https://clickhouse.com/docs/en/development/developer-instruction#cloning-a-repository-to-your-development-machine) for more information.

Yeah, I already known sparse checkout. 
Thanks for your advice.
