### ISSUE TITLE
query was cancelled error

### ISSUE THREAD

**Issue by rkozlo** [ClickHouse/ClickHouse#57527]
Hi lately upgraded from 22.8 to 23.8.  Unexpectedly number of errors increased.  Code: 394 QUERY_WAS_CANCELLED.
I dig deeper and found it is caused because of
`[clickhouse-4] 2023.12.05 12:52:53.708765 [ 8099 ] {03044acc-60a4-46b2-b53d-0e69e8197744} <Trace> StorageDistributed (distributed_table): (clickhouse-12:9000) Cancelling query because enough data has been read` 
It is query on a bit big table. Pasting explain pipeline 
```
┌─explain──────────────────────────────────────┐
│ (Expression)                                 │
│ ExpressionTransform × 16                     │
│   (Aggregating)                              │
│   Resize 54 → 16                             │
│     AggregatingTransform × 54                │
│       StrictResize 54 → 54                   │
│         (Expression)                         │
│         ExpressionTransform × 54             │
│           (Filter)                           │
│           FilterTransform × 54               │
│             (Join)                           │
│             JoiningTransform × 54 2 → 1      │
│               (Expression)                   │
│               ExpressionTransform × 54       │
│                 (ReadFromMerge)              │
│               (Expression)                   │
│               Resize 1 → 54                  │
│                 FillingRightJoinSide         │
│                   Resize 54 → 1              │
│                     ExpressionTransform × 54 │
│                       (ReadFromMerge)        │
└──────────────────────────────────────────────┘
```
On top of that is Merge table, then 3 distributed and then replicated merge tree. Initial query ends with code 0, but some subqueries ends with error

**Comment by Algunenano** [comment]
This is most likely expected. Do you have LIMIT where reading from the distributed table or something similar?

The main query is reading in parallel from all shards, so if it reaches a point where it has enough rows (for example you request 1M rows and one shard provides them), then it will cancel all other queries so they don't waste their time.

**Comment by rkozlo** [comment]
I do not have any limit in query
```
SELECT
a,
uniq(uID) AS uniq,
count() AS total
FROM
(
  SELECT
  uID,
  tID AS tIDa,                                                                                                                                                                                                                                                                aID AS aIDa,
  timestamp AS ta,                                                                                                                                                                                                                                                              action
  FROM db.merge
  WHERE (aID = '...') AND (tID IN ((...))
  ) AS sub
ANY INNER JOIN
(
  SELECT
  uID,
  tID AS tIDc,
  aID AS aIDc,
  timestamp AS tc
  FROM db.merge
  WHERE (aID = '...')  AND (tID IN (...))
  ) AS sub2 USING (uID)
WHERE ta <= tc
GROUP BY a
```
that's why i don't understand why clickhouse says it 'has enough data'
otherwise, if it interrupted query because has enough data there shouldn't be any error in query_log neither system.errors

**Comment by den-crane** [comment]
use_hedged_requests=0 ?

**Comment by rkozlo** [comment]
> use_hedged_requests=0 ?

the same with disabled

**Comment by jaigopinathmalempati** [comment]
Hello @rkozlo ,

Want to know your insights(problems, challenges) of upgrading  clickhouse server version from 22.8. to 23.8 . We are planning the same just want use experience.

Can you please share

**Comment by rkozlo** [comment]
@jaigopinathmalempati a bit weird it is but can see some performance degradation in some cases. Servers throws more frequent weird errors like in this case. JDBC also started throwing some errors so good to update it before cluster upgrade.
Big issue is with replication. Missmatch between versions. Old and new replica can't talk with each other properly so you have to update second replica ASAP. Depends how many inserts you have but it quickly reaches max parts per partition threshold. In my case it was like 1-2 minutes. With cross-replication it is easy to reach that limit
