### ISSUE TITLE
MemoryTracker disappeared in debug logs

### ISSUE THREAD

**Issue by antip00** [ClickHouse/ClickHouse#57522]
Starting clickhouse 23.8 send_logs_level="debug" does not show MemoryTracker logs, don't see it in changelog
![Screenshot from 2023-12-05 15-32-28](https://github.com/ClickHouse/ClickHouse/assets/44409195/6cc89f7a-bc14-4782-bc1c-2c56088af13f)
![Screenshot from 2023-12-05 15-30-06](https://github.com/ClickHouse/ClickHouse/assets/44409195/20b0da85-5568-49ee-8c19-2918bb493d3a)

**Comment by nickitat** [comment]
it is still there, but the message won't be printed if the amount is too small

https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/MemoryTracker.cpp#L151-L160
