### ISSUE TITLE
add support DROP TABLE to MaterializedMySQL 

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#57543]
**Use case**

Need to drop or replace exists table externally,
Internally there is *MergeTree table
Let's allow ATTACH PART , DROP TABLE

of course it require implements more management SHOW|SYSTEM START/STOP MYSQL REPLICATION db.table command 

**Describe the solution you'd like**

just allow DROP TABLE and ATTACH PART works inside MaterializedMySQL

**Additional context**

Currently, i got error
```
error can't drop table `ch_mysql_repl`.`t1`: code: 48, message: There was an error on [127.0.0.1:9000]: Code: 48. DB::Exception: MaterializedMySQL database does not support DROP TABLE. (NOT_IMPLEMENTED) (version 23.10.5.20 (official build))
```

**Comment by alexey-milovidov** [comment]
We don't support MaterializedMySQL.
