### ISSUE TITLE
`partial_merge` should use multiple cores for sorting

### ISSUE THREAD

**Issue by jonashaag** [ClickHouse/ClickHouse#57559]
**Describe the situation**

I have a query that looks like this. Unfortunately I can't share the data or query. I'm working on a reproducer that I can share.

```sql
SELECT
 t1.c1
 , t2.c2
 ...
 , MIN(t1.c10)
 , MIN(t1.c11)
 ...
 , MIN(t2.c20)
 , MIN(t2.c21)
 ...
FROM tbl AS t1
INNER JOIN tbl AS t2  -- (self-join)
 ON t1.c1 = t2.c1
 AND ...
GROUP BY
 t1.c1
 , t2.c2
 , ...
```

LHS is 2 B rows (15 GB as Parquet), RHS is 0.1 B rows.

On a 128 GB, 8 core machine:

- On a 10% subset ClickHouse takes 60 s while DuckDB (from Parquet) takes 30 s.
- On 100%, DuckDB takes 5 min and ClickHouse takes at least 30 minutes (I haven't waited until completion)

Things I've tried:

- Default join settings: OOM, even with external sort/groupby settings correctly set.
- `grace_hash`: same
- `partial_merge`: Takes at least 30 min. Most of that time is spent sorting RHS on a single core, at 1 M rows/s. Memory usage is relatively low during sorting.

**How to reproduce**

- CH 23.11 (local deployment)
- clickhouse-local

**Comment by jonashaag** [comment]
NB: What I don't understand is why ClickHouse doesn't do the entire query partition wise and process a single partition at a time. It's obvious from the query that ClickHouse can safely partition by `tbl.c1`. It could use 10 partitions a 60 s, so finish the entire thing in 10 minutes.

**Comment by sb230132** [comment]
> sounds like you're limited by the speed of merging sorted streams in the end of sorting (it is single-threaded). you could verify by building [processors profile](https://clickhouse.com/docs/en/operations/system-tables/processors_profile_log). it is a known problem that we want to fix one day. but it might be something else ('cause sorting of 100M rows shouldn't take this long). processors profile and `explain pipeline` will help us to understand.
> 
> regarding grace join, have you tried different values for `max_bytes_in_join` and `grace_hash_join_initial_buckets`?

Is it only through trial and error we can get a proper value for
