### ISSUE TITLE
Whether the clickhouse-server would to delete data when ttl is expired when cold volumn's prefer_not_to_merge be setted true.

### ISSUE THREAD

**Issue by intfish123** [ClickHouse/ClickHouse#57558]
clickhouse-server version: `21.8`

Whether the clickhouse-server would to delete data when ttl is expired when one volumn's prefer_not_to_merge be setted true.

I have some problems with storage policy in my production environment, the data on my cold disk not to be deleted when ttl is expired.
How to resolve it?

**Comment by alexey-milovidov** [comment]
Moreover, the setting `prefer_not_to_merge` is not intended for general usage, and I advise not using it.

**Comment by intfish123** [comment]
@alexey-milovidov  what's about of version v23.8?
