### ISSUE TITLE
Clickhouse-keeper disk utilization high usage (23.9.1.1854)

### ISSUE THREAD

**Issue by BlackMetalz** [ClickHouse/ClickHouse#57552]
**Describe the issue**
Clickhouse-keeper disk utilization high usage

**How to reproduce**
* Which ClickHouse server version to use: `23.9.1.1854`
* Which interface to use, if matters
* Clickhouse-server config: https://gist.github.com/BlackMetalz/30e27d2c448aa0e691754ec0fb4315a3

**Expected behavior**
High disk utilization on SSD in clickhouse-keeper
![image](https://github.com/ClickHouse/ClickHouse/assets/3434274/ad1c2bb6-a468-4c4c-a9f5-f954a4eb4988)

While clickhouse-server is pretty low. What was wrong?
![image](https://github.com/ClickHouse/ClickHouse/assets/3434274/7d5e8150-a2b8-4e43-9c6f-eb3dfcb43f47)

Other query metrics
![image](https://github.com/ClickHouse/ClickHouse/assets/3434274/48468c3f-cf47-4a14-b710-4859fd6c3a05)

So only issue in the clickhouse-keeper node with disk IO utilization

**Comment by alexey-milovidov** [comment]
How does it correspond to the number of IO operations on that disk and the number of write requests performed to the Keeper? Does it apply to all three Keeper servers?

**Comment by BlackMetalz** [comment]
> How does it correspond to the number of IO operations on that disk and the number of write requests performed to the Keeper? Does it apply to all three Keeper servers?

![image](https://github.com/ClickHouse/ClickHouse/assets/3434274/6f127593-7434-440f-91bd-b34add85e936)

Node 1: 

![image](https://github.com/ClickHouse/ClickHouse/assets/3434274/a07f43a2-f3e4-49bd-9bbe-424447de5cd9)


Node 2:
![image](https://github.com/ClickHouse/ClickHouse/assets/3434274/784c4c86-3c00-45b8-96ea-01f02fd46704)


Node 3:
![image](https://github.com/ClickHouse/ClickHouse/assets/3434274/2d4f02e9-701c-4602-9f3e-353c5d8150a1)


Node 3 is low duo `can_become_leader` is false and priority=0 ( this is 0.5 in 2.5 DC mode )

**Comment by den-crane** [comment]
[iostat -x and sar -d output shows incorrect high %util values for nvme SSD disks] (https://access.redhat.com/solutions/3901291)

**Comment by BlackMetalz** [comment]
> @BlackMetalz Have you resolved this issue? I also encountered the same problem, where the IOPS of the disk where Keeper's storage directory is located is about 230% ![image](https://private-user-images.githubusercontent.com/90592525/338954995-8bc2b2d8-755a-4f11-ba40-2dda6a169e20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTM1NTYsIm5iZiI6MTcxODE5MzI1NiwicGF0aCI6Ii85MDU5MjUyNS8zMzg5NTQ5OTUtOGJjMmIyZDgtNzU1YS00ZjExLWJhNDAtMmRkYTZhMTY5ZTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDExNTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YmRjM2QxZWZkYWUyMzlmM2I0NjE0ZTUxMjkzNDYwYTVmZDYyNTM4NTcwNzhmOTFkNTUzOTc2OGMyYWQyMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wdVgyHx4eLylQgTTcRSOrDgpyF9HXV7i7bUCkTAh48E)

Honestly, no. I ignored the warning for disk io of the keeper node. And cluster still seems fine, but if i have a chance i would try with zookeeper instead of clickhouse-keeper

**Comment by marksmansj** [comment]
I also came across this issue . hope to find any solutions? or just ignore it ?

**Comment by magichuang77** [comment]
> I also came across this issue . hope to find any solutions? or just ignore it ?

This is not a problem with Clickhouse-keeper, it's the same with zookeeper because it has to write consistency logs in real time. It's recommended that zookeeper or Clickhouse-keeper use a separate data disk, or an SSD if there's only one disk.Because HDD iops are only a few hundred, whereas SSD iops can be huge.

**Comment by marksmansj** [comment]
> > I also came across this issue . hope to find any solutions? or just ignore it ?
> 
> This is not a problem with Clickhouse-keeper, it's the same with zookeeper because it has to write consistency logs in real time. It's recommended that zookeeper or Clickhouse-keeper use a separate data disk, or an SSD if there's only one disk.Because HDD iops are only a few hundred, whereas SSD iops can be huge.

Got it . I really appreciate it
