### ISSUE TITLE
Logical error: 'Function equals with Null argument and default implementation for Nulls is expected to return Nullable result, got UInt8'

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#57566]
https://s3.amazonaws.com/clickhouse-test-reports/57541/e7f1c84cdb4de9e6fe43c356fccc652f6d994028/fuzzer_astfuzzerubsan/report.html

``` sql
SELECT sum(range(-9223372036854775808, NULL)) IGNORE NULLS = count() IGNORE NULLS, sum(upper(materialize('AAAA\0AAAAAAAAAA012345789,.!AAA\0') AS str) = str) IGNORE NULLS = count(range(NULL, NULL, 3)) FROM system.one ARRAY JOIN range(100) AS n
```

**Comment by kssenii** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/59001/d22fc3a224ac29857f3dc3eb60ff872221829006/fuzzer_astfuzzerubsan/report.html=

**Comment by Avogar** [comment]
Doesn't reproduce on master, seems like it's fixed
