### ISSUE TITLE
Add SHA512_224 and SHA512_256 as SQL functions

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#57591]
**Use case**

Someone on the internet needs it.

**Describe the solution you'd like**

BoringSSL already exposes these functions, so adding them will be trivial; you can do it by analogy to SHA512.

**Comment by bharatnc** [comment]
Can I take this one?

**Comment by alexey-milovidov** [comment]
@bharatnc, sure, and it will be amazing!

**Comment by bharatnc** [comment]
@alexey-milovidov Thank you!
> BoringSSL already exposes these functions, so adding them will be trivial; you can do it by analogy to SHA512.

So, it looks like Boring SSL does expose API to compute `SHA512_256`  via `SHA512_256_Update` . 

However, there doesn't seem to be a similar direct API for `SHA512_224`  from having looked at the  [BoringSSL source](https://github.com/google/boringssl/blob/master/include/openssl/sha.h). But there is one `SHA512_224_Update` under [openssl](https://github.com/openssl/openssl/blob/master/crypto/evp/legacy_sha.c#L52) only  (seems to be legacy code). 

Maybe I'm missing something here, but is `SHA512_224_Update` (with 28 bit digest size) is something that's used and available widely under BoringSSL?

**Comment by alexey-milovidov** [comment]
@bharatnc let's skip the 512-224 variant and add only what's available.
