### ISSUE TITLE
randUniform generates same value across arrayMap on 1 mln range sample

### ISSUE THREAD

**Issue by nikitazavadsky** [ClickHouse/ClickHouse#57605]
**Describe the unexpected behaviour**
The following code contain randUniform in arrayMap to generate test data:

```
with test_data as (
    select arrayMap(x -> (
                                if(randUniform(0, 1) > 0.5, 'VALUE_1', 'VALUE_2'),
                                toDate('2023-01-01') + interval x hour,
                                if(randUniform(0, 1) > 0.3, 'SUCCESS', 'ALERT')
    ),
                          range(1000000)) as data,
        data.1 as values,
        data.3 as statuses
)
    select arrayDistinct(values) as uq_values,
           arrayDistinct(statuses) as uq_statuses
    from test_data
```

I expect it to generate both 'VALUE_1' and 'VALUE_2' on the first position in the tuple, as well as statuses 'SUCCESS' and 'ALERT'
So, resulted columns `uq_values` and `uq_statuses` expected to contain both values according to statistics

but result is always static (same value and status across all rows). 
Query was executed more than 20 times

**How to reproduce**
* CH version: 23.10.5.20 (tested on the latest version on https://fiddle.clickhouse.com/ as well)
* No non-default settings, client doesn't matter

**Expected behavior**

I expect `uq_values` and `uq_statuses` to contain uniformely distributed values according to the statistics

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/aed2d27f-705c-4a73-8e02-c084e36e0688

https://clickhouse.com/docs/en/sql-reference/functions/random-functions

All functions in this section accept zero or one arguments. The only use of the argument (if provided) is to prevent [common subexpression elimination](https://clickhouse.com/docs/en/sql-reference/functions#common-subexpression-elimination) such that two different executions within a row of the same random function return different random values.
