### ISSUE TITLE
(ReplicatedMergeTreeQueue) Not executing log entry for part xxxx because merges and mutations are cancelled now

### ISSUE THREAD

**Issue by qinzl1** [ClickHouse/ClickHouse#5762]
it to this merges  for a few days cannot stop .
well cause the node can not select or insert data
this is the error:
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query. 
![image](https://user-images.githubusercontent.com/20242930/60313531-12ba8780-9992-11e9-8919-7ac7b7846569.png)

i think is loop execute this

**Comment by filimonov** [comment]
Can you find what exactly happended before it started? Didn't you call something like `system stop merges`?

**Comment by den-crane** [comment]
it could be mutations canceled by max_execution_time

**Comment by alexey-milovidov** [comment]
This issue may happen due to ALTER queries that prevent merges to execute.
ALTER queries may be locked by other (INSERT, SELECT) queries, look at SHOW PROCESSLIST.

The issue has been fixed in recent release (version 20.3), because now ALTERs don't block merges.
