### ISSUE TITLE
addMonths(last day of month,-1)

### ISSUE THREAD

**Issue by guomoyuxi** [ClickHouse/ClickHouse#57649]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
i use addMonths(toDate('2023-11-30'),-1),  however  get day is '2023-10-30'.  i think that is '2023-10-31'

**Comment by lampjian** [comment]
`addMonths` doesn't consider the last day of this month. You can deal with it by additional boundary conditions.
 `select toStartOfMonth(toDate('2023-11-30'))-1 as endoflastmonth;`

**Comment by guomoyuxi** [comment]
i want to get month on month ratio ,using ${date} or now()

**Comment by rschu1ze** [comment]
See https://github.com/ClickHouse/ClickHouse/discussions/36288
