### ISSUE TITLE
`ALTER LIVE VIEW xxxxx REFRESH` has no effect in v23.8.7?

### ISSUE THREAD

**Issue by lzf575** [ClickHouse/ClickHouse#57644]
I found `ALTER LIVE VIEW xxxxx REFRESH` statement has no effect when executed in v23.8.7, but it is still normal in v22.8 version
It may be caused by: [Remove ALTER of LIVE VIEW](https://github.com/ClickHouse/ClickHouse/pull/51287)?

- I would like to ask, will the `ALTER LIVE VIEW xxxxx REFRESH` statement be supported in the future?
- Let me ask again, when configuring LIVE VIEW 'WITH REFRESH xxx', every time REFRESH is triggered, the live view is queried at the same time, the query at this time is slow. Can it be optimized?

**Comment by alexey-milovidov** [comment]
LIVE VIEWs are not supported - no plans to add any features for them in the future.

**Comment by lzf575** [comment]
> LIVE VIEWs are not supported - no plans to add any features for them in the future.

ok, thx.
