### ISSUE TITLE
Flaky unit test `AsyncLoader.DynamicPools`

### ISSUE THREAD

**Issue by kssenii** [ClickHouse/ClickHouse#57689]
https://s3.amazonaws.com/clickhouse-test-reports/57076/ea63819c76b5884f63573a408720a1a862999759/unit_tests__msan_.html
```
src/Common/tests/gtest_async_loader.cpp:959
Expected equality of these values:
  boosted
    Which is: 0
  concurrency > 2
    Which is: true

```

cc @serxa

**Comment by serxa** [comment]
fixed by https://github.com/ClickHouse/ClickHouse/pull/57950
