### ISSUE TITLE
Slower replica: non-efficient execution of replication_queue (since 22.7)

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#57702]
## Situation:

1) One replica out of 3 was working slower than usual (due to the extra load) and was not able to sort out the replication queue at the usual speed. 
2) The other 2 replicas were working as normal, accepting inserts and doing merges.
3) inserts are relatively small so clickhouse always merges the insert with all the previous parts, leading to a sequence of `merge` tasks like `all_0_1_1`, `all_0_2_2`, `all_0_3_3`, `...` 
4) after the problematic replica gets back to a healthy state it starts to sort out the replication queue. 
    Here clickhouse version 22.6 (and older) was printing message

    ```
    Will fetch part all_0_996_193 instead of all_0_14_3
    ```

    And then execute the whole replication_queue by a single cheap FETCH (less than a second).

    Newer versions of ClickHouse execute the queue in that situation sequentially, one operation at a time, and very slow, slower than new merge tasks can be added, leading to the constantly growing replication queue).

## The test:

```sql
DROP TABLE IF EXISTS test_r1 SYNC;
DROP TABLE IF EXISTS test_r2 SYNC;
DROP TABLE IF EXISTS test_r3 SYNC;

CREATE TABLE test_r1
(
    `x` UInt64,
    `ts` DateTime64(6)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', 'r1')
ORDER BY tuple()
SETTINGS parts_to_delay_insert=1000, parts_to_throw_insert=2000;

CREATE TABLE test_r2
(
    `x` UInt64,
    `ts` DateTime64(6)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', 'r2')
ORDER BY tuple()
SETTINGS parts_to_delay_insert=1000, parts_to_throw_insert=2000;


CREATE TABLE test_r3
(
    `x` UInt64,
    `ts` DateTime64(6)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', 'r3')
ORDER BY tuple()
SETTINGS parts_to_delay_insert=1000, parts_to_throw_insert=2000;

-- let's mimic that the replica 3 has some temporary problem with executing merges (pools is overloaded or other temporal issues)
SYSTEM STOP MERGES test_r3;

-- inserts (small & frequent) keep coming into the table
INSERT INTO test_r1 SELECT rand64(), now64(6) FROM numbers(1000) SETTINGS max_block_size = 1, min_insert_block_size_rows = 1, min_insert_block_size_bytes = 1, insert_quorum = 3;

-- there are quete a few of unprocessed merges in queue now 
select new_part_name, is_currently_executing, postpone_reason from system.replication_queue where type = 'MERGE_PARTS';

-- here the problem on r3 stopped
SYSTEM START MERGES test_r3;

SELECT sleep(1);

select new_part_name, is_currently_executing, postpone_reason from system.replication_queue where type = 'MERGE_PARTS';

-- let's check how long it will take to execute the replication queue
SYSTEM SYNC REPLICA test_r3; -- that line took less than 2 seconds on older version and more than 100 seconds on newer versions

select new_part_name, is_currently_executing, postpone_reason from system.replication_queue where type = 'MERGE_PARTS';

select event_time_microseconds, event_type, part_name, duration_ms  from system.part_log where table = 'test_r3' ORDER BY event_time_microseconds;
```

Maybe related https://github.com/ClickHouse/ClickHouse/pull/37822

**Comment by filimonov** [comment]
Seems like  prefer_fetch_merged_part_time_threshold, prefer_fetch_merged_part_size_threshold, always_fetch_merged_part, background_merges_mutations_scheduling_policy don't help.

**Comment by tavplubix** [comment]
> And then execute the whole replication_queue by a single cheap FETCH (less than a second).

> Newer versions of ClickHouse execute the queue in that situation sequentially, one operation at a time

That's not true, see the logs: https://pastila.nl/?003a1144/1418a97ba6ec977ed35608127f8c3260#sNhxjn/bVUwOBKtpaZjIrw==

Actually it quickly fetches the biggest part too. But then it takes a while to skip other entries. 

It's interesting that when you select from system.replication_queue you never see entries that are currently executing: https://pastila.nl/?0004017e/ba117ae7c9563bb718965a259f4dc911#lFIulbHC0glcwxh7uke8jw== 

So I guess it's due to some backoff in `MergeTreeBackgroundExecutor` 

Also there's something interesting in `StorageReplicatedMergeTree::executeLogEntry`:
https://github.com/ClickHouse/ClickHouse/blob/100b36e8a912b090e79a3181058149afc1ddf47a/src/Storages/StorageReplicatedMergeTree.cpp#L1943-L1947
but:
https://github.com/ClickHouse/ClickHouse/blob/100b36e8a912b090e79a3181058149afc1ddf47a/src/Storages/StorageReplicatedMergeTree.cpp#L2008-L2011

**Comment by tavplubix** [comment]
See also https://github.com/ClickHouse/ClickHouse/pull/39737 (it was reverted)

**Comment by filimonov** [comment]
> That's not true, see the logs
> Actually it quickly fetches the biggest part too. But then it takes a while to skip other entries.

OK, but in part_log it looks like the merges were actually executed :)

part_log on 23.11
https://pastila.nl/?000e74fd/843bd99471e3235b0b418a8e794ca903#DkDS+eCkSNL/cHYUdBQhGA==

part_log on 22.6
https://pastila.nl/?000660cd/3020f9171ba1ab69175788a77ce26e64#r2JFvAUgFuE2GTNnHJ0c5w==

> But then it takes a while to skip other entries.

Nevertheless the effect is still very poor, and it's as slow as it would be executing the merges. 

22.6 - skipping all those tasks took ~3 seconds:
https://pastila.nl/?00060ec4/31b74cf0a4f33a136b5133892b1c6997#VDk0aqsTdl3kwUTyeuZT0Q==

And on 23.11 - several minutes - why? 
https://pastila.nl/?00000c03/a8b33c53ac243536d11ef33f083020a7#dipxYcFX4Xwl3egUnBFtlg==

> It's interesting that when you select from system.replication_queue you never see entries that are currently executing: 

I've also seen that. That's confusing. Also records in part_log looks confusing for me.
Also if you will check system.merges during that you will see information on the merges "running" (while it's actually skipping)

**Comment by Jack1007** [comment]
> ## Situation:
> 
>     1. One replica out of 3 was working slower than usual (due to the extra load) and was not able to sort out the replication queue at the usual speed.
> 
>     2. The other 2 replicas were working as normal, accepting inserts and doing merges.
> 
>     3. inserts are relatively small so clickhouse always merges the insert with all the previous parts, leading to a sequence of `merge` tasks like `all_0_1_1`, `all_0_2_2`, `all_0_3_3`, `...`
> 
>     4. after the problematic replica gets back to a healthy state it starts to sort out the replication queue.
>        Here clickhouse version 22.6 (and older) was printing message
>        ```
>        Will fetch part all_0_996_193 instead of all_0_14_3
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        And then execute the whole replication_queue by a single cheap FETCH (less than a second).
>        Newer versions of ClickHouse execute the queue in that situation sequentially, one operation at a time, and very slow, slower than new merge tasks can be added, leading to the constantly growing replication queue).
> 
> 
> ## The test:
> 
> ```sql
> DROP TABLE IF EXISTS test_r1 SYNC;
> DROP TABLE IF EXISTS test_r2 SYNC;
> DROP TABLE IF EXISTS test_r3 SYNC;
> 
> CREATE TABLE test_r1
> (
>     `x` UInt64,
>     `ts` DateTime64(6)
> )
> ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', 'r1')
> ORDER BY tuple()
> SETTINGS parts_to_delay_insert=1000, parts_to_throw_insert=2000;
> 
> CREATE TABLE test_r2
> (
>     `x` UInt64,
>     `ts` DateTime64(6)
> )
> ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', 'r2')
> ORDER BY tuple()
> SETTINGS parts_to_delay_insert=1000, parts_to_throw_insert=2000;
> 
> 
> CREATE TABLE test_r3
> (
>     `x` UInt64,
>     `ts` DateTime64(6)
> )
> ENGINE = ReplicatedMergeTree('/clickhouse/tables/test', 'r3')
> ORDER BY tuple()
> SETTINGS parts_to_delay_insert=1000, parts_to_throw_insert=2000;
> 
> -- let's mimic that the replica 3 has some temporary problem with executing merges (pools is overloaded or other temporal issues)
> SYSTEM STOP MERGES test_r3;
> 
> -- inserts (small & frequent) keep coming into the table
> INSERT INTO test_r1 SELECT rand64(), now64(6) FROM numbers(1000) SETTINGS max_block_size = 1, min_insert_block_size_rows = 1, min_insert_block_size_bytes = 1, insert_quorum = 3;
> 
> -- there are quete a few of unprocessed merges in queue now 
> select new_part_name, is_currently_executing, postpone_reason from system.replication_queue where type = 'MERGE_PARTS';
> 
> -- here the problem on r3 stopped
> SYSTEM START MERGES test_r3;
> 
> SELECT sleep(1);
> 
> select new_part_name, is_currently_executing, postpone_reason from system.replication_queue where type = 'MERGE_PARTS';
> 
> -- let's check how long it will take to execute the replication queue
> SYSTEM SYNC REPLICA test_r3; -- that line took less than 2 seconds on older version and more than 100 seconds on newer versions
> 
> select new_part_name, is_currently_executing, postpone_reason from system.replication_queue where type = 'MERGE_PARTS';
> 
> select event_time_microseconds, event_type, part_name, duration_ms  from system.part_log where table = 'test_r3' ORDER BY event_time_microseconds;
> ```
> 
> Maybe related #37822

I have tested with your sql code and encountered this issue too, It's too inefficient to merge parts, and throw "Too many parts" exceptions frequently.
How did you solve it?
