### ISSUE TITLE
Alter table update nested column requires backticks

### ISSUE THREAD

**Issue by mraasvel** [ClickHouse/ClickHouse#57740]
```
clickhouse :) alter table test_table update nested.c1 = arrayMap(x -> x, array('default')) where true;

Syntax error: failed at position 67 ('.'):

alter table test_table update nested.c1 = arrayMap(x -> x, array('default')) where true;

Expected one of: token, Equals
```

This requires wrapping the nested column in backticks:

```
alter table test_table update `nested.c1` = ArrayMap(x -> x, array('default')) where true;
```

Is this expected behavior? I could not find much on this in the documentation.

https://clickhouse.com/docs/en/sql-reference/data-types/nested-data-structures/nested

**Comment by melvynator** [comment]
As far as I know, this is an expected behavior: https://clickhouse.com/docs/en/sql-reference/syntax#identifiers
