### ISSUE TITLE
Modified User Defined Functions aren't updated in VIEWs

### ISSUE THREAD

**Issue by vschule** [ClickHouse/ClickHouse#57748]
**Describe the unexpected behaviour**
Part of the point of using Functions is to be able to have one point of reference to what it does. It's unexpected that changing the function wouldn't update a view's behavior

**How to reproduce**
* Which ClickHouse server version to use 23.5.5.92
Create a SQL User Defined Function
Create a View that uses it
Replace UDF with a new implementation
Expected : View uses the new implementation
Actual behavior : View keeps the previous implementation

CREATE OR REPLACE FUNCTION testFunction  on cluster '{cluster}' AS x-> x+3;
CREATE OR REPLACE VIEW testView on cluster '{cluster}' as select testFunction(1) as y;
select * from testView; -- expected 4
CREATE OR REPLACE FUNCTION testFunction  on cluster '{cluster}' AS x-> x+1;
select * from testView; -- expected 2, get 4

**Expected behavior**
View uses the new function implementation

**Comment by den-crane** [comment]
by design.

* v22.12.1.1752-stable.md:* Substitute UDFs in `CREATE` query to avoid failures during loading at the startup. Additionally, UDFs can now be used as `DEFAULT` expressions for columns. [#43539](https://github.com/ClickHouse/ClickHouse/pull/43539) ([Antonio Andelic](https://github.com/antonio2368)).

**Comment by vschule** [comment]
Doesn't this only mean that to fix a bug another was implemented? This is still unexpected user facing behaviour..

**Comment by pkit** [comment]
@vschule views need to be re-created each time something they reference changes. For example: `SELECT * FROM t` will implicitly hardcode existing table schema into the view. And if table schema changes, view will not reflect it.
That's how ClickHouse works.
