### ISSUE TITLE
Concurrent lightweight delete and drop partition causes 'Exception: Cancelled mutating parts'

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#57750]
I have a test for lightweight delete, I perform concurrent lightweight delete in loop for ten partitions and drop one partition.
I create MergeTree table, insert data into it, then concurrently:

1. I perform lightweight delete for each partition in loop: delete odd rows.
2. I perform drop one partition.

Then I check that data was deleted from every partition.

Very rarely it can cause this exception:
`
Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Exception happened during execution of mutation 'mutation_20.txt' with part '6_7_7_0_19' reason: 'Code: 236. DB::Exception: Cancelled mutating parts. (ABORTED) '. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED)
`
Tested on 23.8

Manually it is very hard to catch this fail.

**Comment by den-crane** [comment]
```
create table test ( A Int64, B Int64 ) Engine MergeTree partition by B order by tuple();

for i in `seq 1 5000`; do clickhouse-client -mnq 'alter table test drop partition 1' ; done &

for i in `seq 1 5000`; do echo $i; clickhouse-client -mnq 'delete from test where A % 2 = 1; insert into test select number, intDiv(number,2) from numbers(20);' ; done
1
Received exception from server (version 23.11.1):
Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Exception happened during execution of mutation 'mutation_1982.txt' with part '4_1976_1976_0' reason: 'Code: 236. DB::Exception: Cancelled mutating parts. (ABORTED) (version 23.11.1.166)'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED)
(query: delete from test where A % 2 = 1;)
2
Received exception from server (version 23.11.1):
Code: 341. DB::Exception: Received from localhost:9000. DB::Exception: Exception happened during execution of mutation 'mutation_1983.txt' with part '7_8_1957_34_1971' reason: 'Code: 236. DB::Exception: Cancelled mutating parts. (ABORTED) (version 23.11.1.166)'. This error maybe retryable or not. In case of unretryable error, mutation can be killed with KILL MUTATION query. (UNFINISHED)
(query: delete from test where A % 2 = 1;)
3
Received exception from server (version 23.11.1):
```

It's expected behaviour unfortunately now.
