### ISSUE TITLE
Obfuscator generates invalid date strings

### ISSUE THREAD

**Issue by jonashaag** [ClickHouse/ClickHouse#57759]
I generated some data with the latest version of the obfuscator with a column `--structure 'mydate DATE, ...'`.

The output CSV has date strings like `YYYY-MM-DD-XX-YY-ZZ` and `YYYY-MM-DD-XX-YY`. This is unexpected because date strings should be `YYYY-MM-DD`.

The input data does not contain any data in the invalid format.

**Comment by jonashaag** [comment]
It also seems to ignore `N` in `CHAR(N)`, happily generating strings that are larger than `N`

**Comment by alexey-milovidov** [comment]
Does not reproduce:

```
clickhouse-local --query "SELECT * FROM generateRandom('d Date') LIMIT 1000000" > test && clickhouse-obfuscator --structure 'd Date' --input-format TSV --output-format TSV --seed 1 < test 2>/dev/null | clickhouse-local --input-format LineAsString --query "SELECT DISTINCT length(line) FROM table"
10
```

**Comment by alexey-milovidov** [comment]
It is possible if you have another field that was treated as String, not Date.

**Comment by alexey-milovidov** [comment]
For strings of fixed size in bytes, you can use the `FixedString(N)` instead of `CHAR(N)`, which is a compatibility alias for MySQL where it is not of fixed size in bytes, but rather in charset dependent code points.

**Comment by jonashaag** [comment]
> It is possible if you have another field that was treated as String, not Date.

Can you please elaborate? I don't understand what you mean

**Comment by jonashaag** [comment]
> For strings of fixed size in bytes, you can use the `FixedString(N)` instead of `CHAR(N)`, which is a compatibility alias for MySQL where it is not of fixed size in bytes, but rather in charset dependent code points.

In my case the strings at all-ASCII so it should be identical right?

**Comment by alexey-milovidov** [comment]
> In my case the strings at all-ASCII so it should be identical right?

Yes. Specify `FixedString(N)` and it will work as expected.

> Can you please elaborate? I don't understand what you mean

The case for the `Date` data type works as expected - I didn't find any reason it could produce longer output.
But if you specified another data type, e.g. `String` or `DateTime` you will get the output longer than for `Date`.

**Comment by jonashaag** [comment]
But why would `CHAR(N)` legitimately allow for strings longer than `N` if all characters in the strings are ASCII? What does it have to do with encoding?

I'll try to reproduce both bugs with the latest version of clickhouse-obfuscator.

**Comment by alexey-milovidov** [comment]
It is just a difference in how the parameter N is interpreted.

Let's say you have `CHAR(1) CHARACTER SET utf8mb4` in MySQL, then you can write `好` into it, but if it is `CHAR(1) CHARSET latin1`, it will not fit.

But in ClickHouse, you don't specify a charset for columns - you can use UTF-8 everywhere, and it will be handled transparently. The behavior is specified on a function level, e.g., we have functions `length` and `lengthUTF8`.

This implementation is much better than what you have in:
- MySQL
- Python
- JavaScript
- Windows
who chose to designate binary and Unicode instead of using https://utf8everywhere.org/

https://www.db-fiddle.com/f/ghcYj524yqG57Q48Bva4rj/0

**Comment by jonashaag** [comment]
Thank you! Understood. However I'm surprised that Obfuscator doesn't take into account the actual observed maximum string length. Let's say the column is something funny like `VARCHAR(255)` or `CHAR(255)` for whatever reason, but the longest string in the actual data is 3 ASCII characters long. Why would Obfuscator ever generate longer strings?
