### ISSUE TITLE
Data loss with ALTER TABLE MOVE PARTITION

### ISSUE THREAD

**Issue by ivan-tkatchev** [ClickHouse/ClickHouse#57775]
These three commands in succession lead to loss of data:

```
CREATE TABLE data_rpl_tmp ON CLUSTER ssd AS data_rpl ENGINE = ReplicatedMergeTree(...)
ALTER TABLE data_rpl ON CLUSTER ssd MOVE PARTITION '2023-12-12' TO TABLE data_rpl_tmp
ALTER TABLE data_rpl_tmp ON CLUSTER ssd MOVE PARTITION '2023-12-12' TO TABLE data_rpl 
```

After these commands some (but not all) servers in cluster managed to completely lose the data in the partition. (Nothing in detached parts, both tables now have an empty partition.) Nothing relevant in logs or system.errors.

We have distributed_ddl.pool_size = 16. This might be relevant. Possibly a race condition bug.

Clickhouse version 23.3.2.1.

**Comment by Algunenano** [comment]
> We have distributed_ddl.pool_size = 16. This might be relevant. Possibly a race condition bug.

100% relevant I'd say. Anything different from 1 is uncharted territory and should never be used in production. @alesapin was working on [something ](https://github.com/ClickHouse/ClickHouse/issues/56690) to try to parallelize tasks and he kept finding problems.

**Comment by ivan-tkatchev** [comment]
Point taken, but it is expected that ALTER TABLE MOVE PARTITION commands should be idempotent and should never lose data.

I am guessing the same bug can be triggered if you just do several ALTER TABLE MOVE PARTITION manually, and there is nothing specifically related to distributed DDL queries here.

**Comment by tavplubix** [comment]
> We have distributed_ddl.pool_size = 16

Yes, that's the reason. The queries were executed in parallel, so they dropped the partition from both tables. It should not be used in production:

https://github.com/ClickHouse/ClickHouse/blob/296afceed8df1f3c40eea8bf2fc89e1d260bc2bf/src/Interpreters/DDLWorker.cpp#L93-L98

**Comment by ivan-tkatchev** [comment]
Please clarify your answer.
Are data loss possible if parallel ALTER TABLE queries are run with a different method? For example, with the HTTP interface?
If a hypothetical script runs this command sequence in parallel by making HTTP requests to Clickhouse, will I lose data?

If yes, this needs to be fixed or at least very clearly documented.

**Comment by Algunenano** [comment]
> Is data loss possible if parallel ALTER TABLE queries are run with a different method? For example, with the HTTP interface?
> If a hypothetical script runs this command sequence in parallel by making HTTP requests to Clickhouse, will I lose data?

No. Parallel alter tables are fine because they will always be executed sequentially (unless you are using `distributed_ddl.pool_size>1`)

**Comment by tavplubix** [comment]
`ALTER TABLE A MOVE PARTITION ... TO TABLE B` copies data from A to B and drops data from A
`ALTER TABLE B MOVE PARTITION ... TO TABLE A` copies data from B to A and drops data from B

If you run them in parallel, then of course they can drop data from both A and B

**Comment by ivan-tkatchev** [comment]
I had naively assumed this operation is more or less atomic. (Implemented as something like a series of rename() system calls for part directories under the hood.)

Perhaps this should be documented better.
