### ISSUE TITLE
RFC: Parquet part format for MergeTree

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#57799]
**Use case**

Parquet file format is quite similar to the Compact / StripeLog. 
ClickHouse already has quite a good Parquet reader/writer but only for import/export. 
MergeTree tables can already have Compact & Wide (and obsolete Memory) formats. 

Maybe we can try to create a Parquet-based part format for MergeTree. That will most probably require creating some extra files aside (or columns inside the Parquet file) to store the sparse index (primary.idx), marks etc.

It can support only a limited subset of the MergeTree features & ClickHouse datatypes. 

That will allow us to read the ClickHouse data also by external tools, and allow us to avoid proprietary formats. 

The idea is to offload/archive some parts/partitions to Parquet format to some network drive or datalake, making it an 'online backup', accessible for other tools.

**Describe the solution you'd like**

On disk: something similar to Compact parts, but with Parquet file as the main storage.

```
./2020_1_1_0/primary.idx
./2020_1_1_0/columns.txt
./2020_1_1_0/data.parquet
```
etc

Maybe some settings to force using that file format on a particular drive or by some conditions.

**Describe alternatives you've considered**

Import/export via file / s3 table engines/functions - requires to use of different queries, and does not allow to use of the whole power of ClickHouse (with indexes etc.).

**Comment by aadant** [comment]
@tbragin FYI, we discussed this

**Comment by filimonov** [comment]
Cross-posting comments from the internal discussion:

Q. BTW: one important notice here. If clickhouse will use Parquet part format & will be doing merges there etc. - you can have duplicate data when reading Parquet files from clickhouse folder (due to inactive parts). That can be a problem (edited) 

A. it seems that freeze does not give you the inactive parts, so we can FREEZE them. 
I.e. you run FREEZE, and clickhouse create in /var/lib/clickhouse/shadow/ a folder with hardlinks to all parts which are active currently. Creating hardlinks is relatively cheap. And you process them as needed, and later remove the folder or do unfreeze

Q. Perhaps there could be some other file-based metadata indicating which Parquet files currently represent the active set? Either something like a simple JSON file, or maybe a symlink farm

A. That's problematic from MVCC point of view :neutral_face: The parts are immutable before the moment of deletion, and putting some extra files there breaks that invariant. Problem is that inactive parts can become active again after some hard restart or other failure (when the new merged part becomes broken)

**Comment by UnamedRus** [comment]
> It can support only a limited subset of the MergeTree features & ClickHouse datatypes.

All columns, which are not native types of parquet, can be stored as binaries, even if only ClickHouse can read them, it's fine.

> Perhaps there could be some other file-based metadata indicating which Parquet files currently represent the active set? 

It's like iceberg is working
<img width="624" alt="iceberg-metadata" src="https://github.com/ClickHouse/ClickHouse/assets/9449405/46938a65-fd78-4996-8de3-56a47955922f">

**Comment by aadant** [comment]
@alexey-milovidov this is the RFC we mentioned at FOSDEM. It does consider unsupported data types in @UnamedRus's comment above.

**Comment by alexey-milovidov** [comment]
It is a troublesome idea, similar to implementing yet another data lake format.
It might sound tempting, but I feel against supporting it.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/111122
