### ISSUE TITLE
retention aggregate function has distinct behavior on 22.8(and older) and newer releases

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#57794]
```sql
CREATE TABLE t (a Nullable(Int8)) engine=Memory;

INSERT INTO t VALUES (127), (-128), (NULL), (-58), (57), (4), (-73), (72), (-77), (93);

SELECT retention(a = 0, a = 1) FROM t;
```

I get different results on 22.8(and older) and newer versions (23.10, for example).

22.8:
```[1,0]```

23.10:
```[0,0]```

**Comment by Algunenano** [comment]
Probably related to https://github.com/ClickHouse/ClickHouse/pull/41595. NULL is NULL, and 0 is 0.
