### ISSUE TITLE
system.users / show create user show the password hashes

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#57805]
**Use case**

1) The server admin needs to check if some users still use compromised / weak password(s).
2) when migrating users from one server to another we need to dump CREATE USER statements with user credentials

**Describe the solution you'd like**

Special grant allowing to see auth data in system.users and in show create user

**Describe alternatives you've considered**

As a root he can access sql files in /var/lib/clickhouse/access but it is not handy / bad for automation / require some knowledge about clickhouse internals.

**Additional context**

In Postgres: SELECT rolpassword FROM pg_authid  (https://www.postgresql.org/docs/8.3/catalog-pg-authid.html)
In MySQL: information_schema.users & SHOW CREATE USER have it https://dev.mysql.com/doc/refman/8.0/en/show-create-user.html 
Also related setting: [print_identified_with_as_hex](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_print_identified_with_as_hex)

ClickHouse in system.users only have some details about kerberos / ldap / ssl_cert
https://github.com/ClickHouse/ClickHouse/blob/6abe4b113ac82e2260ee09f3bf02bed5507a42ec/src/Storages/System/StorageSystemUsers.cpp#L110-L112

SHOW CREATE only can print NO PASSWORD auth type:
https://github.com/ClickHouse/ClickHouse/blob/6abe4b113ac82e2260ee09f3bf02bed5507a42ec/src/Interpreters/Access/InterpreterShowCreateAccessEntityQuery.cpp#L66

**Comment by den-crane** [comment]
it exists https://clickhouse.com/docs/en/sql-reference/statements/grant#grant-display-secrets

**Comment by den-crane** [comment]
```
grep display_secrets_in_show_and_select *
zook.xml:	   <display_secrets_in_show_and_select>1</display_secrets_in_show_and_select>

# clickhouse-client --format_display_secrets_in_show_and_select=1

show create user foo
┌─CREATE USER foo───────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE USER foo IDENTIFIED WITH sha256_hash BY '2D711642B726B04401627CA9FBAC32F5C8530FB1903CC4DB02258717921A4881' │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by den-crane** [comment]
```
clickhouse-client --format_display_secrets_in_show_and_select=1 -u foo --password=x

SHOW CREATE USER foo

┌─CREATE USER foo─────────────────────────────────┐
│ CREATE USER foo IDENTIFIED WITH sha256_password │
└─────────────────────────────────────────────────┘
```

```
grant displaySecretsInShowAndSelect on *.*  to foo;

clickhouse-client --format_display_secrets_in_show_and_select=1 -u foo --password=x

SHOW CREATE USER foo

Query id: 112f759b-dcbc-4054-80d7-5326ad8d8dc6

┌─CREATE USER foo───────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE USER foo IDENTIFIED WITH sha256_hash BY '2D711642B726B04401627CA9FBAC32F5C8530FB1903CC4DB02258717921A4881' │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
