### ISSUE TITLE
retention aggregate function with NULL

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#57801]
I perform this query on 22.8 (anything less that 23):
```sql
SELECT retentionState(x=1,x=NULL) FROM values('x Nullable(UInt8), w Nullable(UInt8)', (NULL,NULL))
```
I get this error:
```Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type Nothing of argument 1 of aggregate function retention, must be UInt8. (ILLEGAL_TYPE_OF_ARGUMENT)```

For 23 and newer it doesn't throw an exception. 

And the retention without -State combinator works fine on 22.8.
```sql
SELECT retention(x=1,x=NULL) FROM values('x Nullable(UInt8), w Nullable(UInt8)', (NULL,NULL))
```

**Comment by Algunenano** [comment]
Please explain what you expect / think it's wrong.

AFAICS, this is working as documented.

**Comment by alsugiliazova** [comment]
I expect to see no exception when I'm trying to get state of the function.

**Comment by Algunenano** [comment]
What query are you running?

```
SELECT retentionState(x = 1, x = NULL)
FROM values('x Nullable(UInt8), w Nullable(UInt8)', (NULL, NULL))

Query id: 1ba0b621-8c74-421d-9378-1c3a98dd80c1

┌─retentionState(equals(x, 1), equals(x, NULL))─┐
│ ᴺᵁᴸᴸ                                          │
└───────────────────────────────────────────────┘
```

This works fine in any supported release. Are you complaining about 22.8?

**Comment by alsugiliazova** [comment]
Yes, my problem is on 22.8

**Comment by Algunenano** [comment]
22.8 is out of support. You should upgrade

**Comment by alsugiliazova** [comment]
Ok, thank you
