### ISSUE TITLE
Sorted by serial number of selected fields isn't work.

### ISSUE THREAD

**Issue by deliangyang** [ClickHouse/ClickHouse#57807]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

SELECT
  path,
                           count(1) AS x
                       FROM request
                       WHERE logTime > toDateTime64('2023-12-13 17:00:00', 6)
                       GROUP BY path
                       ORDER BY `2` DESC
                       LIMIT 10;

The above SQL is works in MySQL, but it's not work in ClickHouse. The serial number 2 means `x`.
In MySQL query, `ORDER BY 2 DESC`  equals to `ORDER BY x DESC`.

**Comment by den-crane** [comment]
you need to upgrade. It was implemented a long time ago https://fiddle.clickhouse.com/5d84c92d-4a06-4a6f-af7d-245f7b1ad97e

v21.10.1.8013-prestable.md:* Allow positional arguments under setting `enable_positional_arguments`. Closes [#2592](https://github.com/ClickHouse/ClickHouse/issues/2592). [#27530](https://github.com/ClickHouse/ClickHouse/pull/27530) ([Kseniia Sumarokova](https://github.com/kssenii)).
