### ISSUE TITLE
Row with default values returned when aggregating no data

### ISSUE THREAD

**Issue by AntoineSebert** [ClickHouse/ClickHouse#57812]
**Describe the unexpected behaviour**
A non-aggregating `SELECT` query with a `WHERE` clause that excludes all values from a column will produce no rows:
```sh
:) SELECT * FROM table WHERE column = 'an absent value'
Ok.

0 rows in set.
```
An aggregating `SELECT` query with a `WHERE` clause that excludes all values from a column will produce a row with default values:
```sh
SELECT argMax(column_0, column_1) FROM table WHERE column_2 = 'an absent value'
┌─argMax(column_0, column_1)─┐
│                            │
└────────────────────────────┘

1 row in set.
```

**How to reproduce**
* clickhouse-server: 23.8.4.69
* ClickHouse client: 23.8.4.69
* table:
```sh
CREATE TABLE database_name.table_name
(
    `column_2` String,
    `column_0` String,
    `column_1` DateTime CODEC(DoubleDelta)
)
ENGINE = Distributed('production',
 'database_name_local',
 'table_name',
 xxHash64(column_2));
```
* Sample data for all these tables:
```md
|   | column_2 | column_0        | column_1            |
|---|----------|-----------------|---------------------|
| 1 | 00000000 | AA00000AA000000 | 1970-01-01 00:00:00 |
```
* Queries to run that lead to unexpected result: `SELECT argMax(column_0, column_1) FROM table WHERE column_2 = 'an absent value'`

**Expected behavior**
```sh
:) SELECT argMax(column_0, column_1) FROM table WHERE column_2 = 'an absent value'
Ok.

0 rows in set.
```
**Additional context**
I skimmed through the docs for quite a while, but maybe I missed something.
If this behaviour is actually intended for any reason whatsoever, is there a setting to disable it ?

**Comment by melvynator** [comment]
As far as I know it has been added to follow SQL standard: https://github.com/ClickHouse/ClickHouse/issues/1965

**Comment by AntoineSebert** [comment]
> As far as I know it has been added to follow SQL standard: #1965

Some set operations like `COUNT` and `SUM` should return 0 on an empty set because it makes more sense, but other set operations work differently from what I can remember.
What I meant is that `argMax` returning a default value (an empty string in my example) on an empty seems a bit counter-intuitive.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/operations/settings/settings#aggregate_functions_null_for_empty

```
SELECT argMax(column_0, column_1) FROM (select 1 column_0, 1 column_1)WHERE 0;
┌─argMax(column_0, column_1)─┐
│                          0 │
└────────────────────────────┘

SELECT argMax(column_0, column_1) FROM (select 1 column_0, 1 column_1)WHERE 0 settings aggregate_functions_null_for_empty=1;
┌─argMaxOrNull(column_0, column_1)─┐
│                             ᴺᵁᴸᴸ │
└──────────────────────────────────┘
```
