### ISSUE TITLE
OPTIMIZE ... DEDUPLICATE does not work?

### ISSUE THREAD

**Issue by ivan-tkatchev** [ClickHouse/ClickHouse#57813]
The command

```
OPTIMIZE TABLE data_slim FINAL DEDUPLICATE SETTINGS optimize_throw_if_noop = 1
```

raises an exception:

```
Code: 388. DB::Exception: Received from localhost:9000. DB::Exception: Cannot select parts for optimization: Part all_81574178_82904081_154_82864826 has already been assigned a merge into all_81574178_82931927_155_82864826 (in partition all). (CANNOT_ASSIGN_OPTIMIZE)
```

Which I interpret as that deduplication is impossible, because the table is currently merging. (And since the table is always merging, deduplication is thus never possible.)

I would expect that deduplication work like any other mutation. Am I wrong in my assumptions?

**Comment by melvynator** [comment]
`DEDUPLICATION FINAL` works by merging and removing rows with the same values on all columns. 

You can monitor ongoing merge using the `system.merges` table

**Comment by ivan-tkatchev** [comment]
I understand the mechanism. Problem is that the merges never start, because replication queue is always full with regular replicated table merges.

**Comment by den-crane** [comment]
You can stop insertion. Wait while merges are finished, then run optimize. I understand that is ridicules workaround, but the problem is that  `OPTIMIZE TABLE` is a special admin command, which cannot be used on a daily bases and it requires. special admin actions
