### ISSUE TITLE
`filesystem_caches_path` in the configuration should be defined by default

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#57825]
1. Allow relative paths for the value of `filesystem_caches_path`. It should be relative to `path`.
2. Set it to `cache` by default in clickhouse-server's configuration to avoid a minor vulnerability with creating tables with dynamic disks.
3. Make sure it applies to dynamic disks, but statically configured paths are still allowed to point anywhere.
4. Make sure clickhouse-local still allows dynamic disks to have paths point anywhere.
5. Update the code of ClickBench, related to `clickhouse-web`.

**Comment by kssenii** [comment]
As `filesystem_caches_path` affects not only dynamic disks, but all disks, I'd rather not set it in default config, but do this https://github.com/ClickHouse/ClickHouse/pull/58869 (See PR description).
