### ISSUE TITLE
Include date/datetime metadata in parquet

### ISSUE THREAD

**Issue by rjoelnorgren** [ClickHouse/ClickHouse#57833]
ClickHouse writes dates/datetimes to parquet without the metadata needed for other parquet readers to naturally read them as dates. Other clients just see an integer and must cast it first use it as a date.

If we coud include the type metadata for dates/datetime that would make exports from ClickHouse more easy to integrate with other parquet readers.

**Comment by den-crane** [comment]
```
# clickhouse-local --output_format_parquet_compression_method=snappy -q 'select today() d, now() t, now64(6) t64 format Parquet' > test.Parquet

# pip install parquet-cli

# parq test.Parquet --schema

 # Schema
 <pyarrow._parquet.ParquetSchema object at 0xffff6fc245c0>
required group field_id=-1 schema {
  required int32 field_id=-1 d (Int(bitWidth=16, isSigned=false));
  required int32 field_id=-1 t (Int(bitWidth=32, isSigned=false));
  required int64 field_id=-1 t64 (Timestamp(isAdjustedToUTC=true, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
}


# ./duckdb

select * from 'test.Parquet';
┌────────┬────────────┬──────────────────────────────┐
│   d    │     t      │             t64              │
│ uint16 │   uint32   │   timestamp with time zone   │
├────────┼────────────┼──────────────────────────────┤
│  19705 │ 1702584780 │ 2023-12-14 20:13:00.01502+00 │
└────────┴────────────┴──────────────────────────────┘
```

**Comment by den-crane** [comment]
So, Parquet has date 32 bits == Clickhouse Date32 and datetime 64 bits == Clickhouse DateTime64.
There is no way hint Parquet that Int16 is date. 
You need to convert Date to Date32 and DateTime to DateTime64 explicitly.

**Comment by rjoelnorgren** [comment]
Thank you @den-crane

**Comment by UnamedRus** [comment]
Starting from 25.1, CH export dates/datetimes as dates/time in parquet
https://github.com/ClickHouse/ClickHouse/pull/70950
