### ISSUE TITLE
ClickHouse-21.8.8.29 using engine = File(Arrow) throw ParsingException，maybe a bug or something else？

### ISSUE THREAD

**Issue by sgfeng001** [ClickHouse/ClickHouse#57859]
1 create a test table:
create table  test.other_arrow ("SID" Int64,"GROUPID" Int32, "IMSI" String, "ROAMING_TYPE" Int8) engine = File(Arrow);
2 insert data to table:
INSERT INTO  test.other_arrow ("SID", "GROUPID", "IMSI", "ROAMING_TYPE") VALUES (65535, 1000, 'I am IMSI', 100);
then get feedback "ok"， check the table data,has data.csv in dirctory other_arrow
3 but when I query this table：
select * from test.other_arrow;
get exception
DB::Exception: Error while reading batch of Arrow data: Invalid: Unexpected empty message in IPC file format: While executing File, Stack trace:

Maybe a bug？

BTW，my compile config is： 
cmake .. -DUSE_ARROW=1 -DUSE_INTERNAL_BOOST_LIBRARY=1 -DENABLE_CURL=0 -DENABLE_S3=0 -DUSE_SENTRY=0 -DUSE_INTERNAL_AWS_S3_LIBRARY=OFF -DENABLE_READLINE=1 -DCMAKE_BUILD_TYPE=Release -DENABLE_MYSQL=0 -DENABLE_DATA_SQLITE=0 -DPOCO_ENABLE_SQL_SQLITE=0 -DENABLE_JEMALLOC=ON -DENABLE_EMBEDDED_COMPILER=1  -DENABLE_PARQUET=1  -DENABLE_ORC=1 -DENABLE_PROTOBUF=1 -DENABLE_ODBC=0 -DENABLE_SSL=1  -DNO_WERROR=1 -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc

**Comment by Algunenano** [comment]
Please test it with an official supported build.

You can get it by: `curl https://clickhouse.com/ | sh`

**Comment by sgfeng001** [comment]
But what's wrong about my build.  Lack of some config?

**Comment by Algunenano** [comment]
We don't support neither old versions (bugs might have been fixed already and spending time there has little return if it's already fixed), nor custom builds (there are millions of combinations, and it has zero value for anybody except you). If you still do it you are on your own, basically.
