### ISSUE TITLE
Return arrayFold back

### ISSUE THREAD

**Issue by Strate** [ClickHouse/ClickHouse#57852]
In this PR arrayFold completely removed. https://github.com/ClickHouse/ClickHouse/pull/57836

I was already using this function, and removing would be significant break for existing code.

This function is pretty usable, allowing to make great things, which are not possible with other ways (for example, this function helps to greatly increase performance query, allowing to make only one iteration over array instead of multiple arrayFilter/arrayMap functions).

Please consider to not remove it.

**Comment by den-crane** [comment]
not actionable. Use PR comments

**Comment by rschu1ze** [comment]
https://github.com/ClickHouse/ClickHouse/pull/57879
