### ISSUE TITLE
Question on query with joins / aggregation on distributed table

### ISSUE THREAD

**Issue by njcstreet** [ClickHouse/ClickHouse#57865]
Hi,

We are evaluating ClickHouse for our Data Warehousing project. So far performance has been excellent, but we are struggling a bit with distributed queries. Wondering if someone can kindly offer some advice.

•	We have a star schema with dimensions describing business attributes and fact tables containing numerical values and keys linking to dimensions. I know the recommendation is to de-normaize as far as possible, but we update dimensions frequently and need to keep this flexibility. 
•	We are testing on a three node cluster. The fact table is distributed and the dimension tables are replicated merge tree. 
•	Queries are typically select from Fact table filtering on a set of attributes (most common of which we put in the primary key), joining onto dimensions to retrieve additional attributes or apply filters, and SUM and Group by the results. With this design in theory we should be able to execute the full query on each shard and combine the end results at the initiator node (since dimensions are replicated). 

So far we’ve found the most optimal way to write the query like below (full schema reproduction at the bottom), where initial filter is done in a sub-query, and the joins done after initial filter / group by. The issue we have is that when we execute the query against Node 1, only the sub query is pushed down to the shards and the join onto the dimensions is performed on the initiator node. This is sub optimal because sometimes dimensions can have a lot of rows and ideally we want to execute the full query on each shard and return only the final result to combine at the initiator. 

Taking the query below for example, using the reproduction at the bottom, the actual query only returns one record, but looking at node 2 it has returned 9 records to the initiator because only the sub-query has been pushed down. This is heavily simplified, sometimes we are seeing ~100K records being returned to the initiator and it causes a network bottleneck between the nodes. Is there a way to re-write the query such that the filtering / join / aggregation are done on each node? We’ve tried playing around with distributed_group_by_no_merge and distributed_product_mode but can’t seem to get it to influence the behaviour. 

```
SELECT 
       p.product_category,
       o.region,
       SUM(t.sales_value) as sales_value
FROM
(
       SELECT date_key, product_key, org_key, sum(sales_value) as sales_value
       FROM dw.fact_sales f
       WHERE f.date_key IN (20231130,20231129,20231128)
       AND f.product_key IN
       (
              SELECT product_key
              FROM dw.dim_product
              WHERE product_name IN ('Product 1', 'Product 2')
       )
       
       GROUP BY date_key, product_key, org_key
) t
INNER JOIN
(
       SELECT product_category, product_key
       FROM dw.dim_product
       WHERE product_name IN('Product 1', 'Product 2')
) p
ON p.product_key= t.product_key

INNER JOIN 
(
	SELECT org_key, region
	from dw.dim_org o
) o on o.org_key = t.org_key

GROUP BY p.product_category,
       o.region
```

As a side note, we’ve noticed that if we heavily simplify the query like below, we get the result we want (although it executes slower than applying the filtering in a sub query), however as soon as we add a second join table, the shards seem to send back all of the raw un-aggregated data. 
 
```
-- Returns 1 record from Node 2 to the initiator as expected
SELECT 
p.product_category,
SUM(sales_value) as sales_value
FROM dw.fact_sales f
INNER JOIN
(
       SELECT product_category, product_key
       FROM dw.dim_product
       WHERE product_name IN('Product 1', 'Product 2')
) p
ON p.product_key= f.product_key
WHERE f.date_key IN (20231130,20231129,20231128)
AND f.product_key IN
(
       SELECT product_key
       FROM dw.dim_product
       WHERE product_name IN ('Product 1', 'Product 2')
)

GROUP BY p.product_category
```

-- After adding a second join, returns all of the raw data from node 2 to the shard with no aggregation applied
```
SELECT 
p.product_category,
o.region,
SUM(sales_value) as sales_value
FROM dw.fact_sales f
INNER JOIN
(
       SELECT product_category, product_key
       FROM dw.dim_product
       WHERE product_name IN('Product 1', 'Product 2')
) p
ON p.product_key= f.product_key
INNER JOIN dw.dim_org o
ON o.org_key = f.org_key
WHERE f.date_key IN (20231130,20231129,20231128)
AND f.product_key IN
(
       SELECT product_key
       FROM dw.dim_product
       WHERE product_name IN ('Product 1', 'Product 2')
)

GROUP BY p.product_category, o.region
```

Full reproduction:
```

-- 1st Dimension
DROP TABLE IF EXISTS dw.dim_product ON CLUSTER colossus_full_rep_cluster;
CREATE TABLE dw.dim_product ON CLUSTER colossus_full_rep_cluster(
product_key Int32,
product_name String,
product_category String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/dw/dim_product', '{replica}')
PRIMARY KEY(product_key);
INSERT INTO dw.dim_product
VALUES(1, 'Product 1', 'Category'), (2, 'Product 2', 'Category'),(3, 'Product 3', 'Category')


-- 2nd Dimension
DROP TABLE IF EXISTS dw.dim_org ON CLUSTER colossus_full_rep_cluster;
CREATE TABLE dw.dim_org ON CLUSTER colossus_full_rep_cluster(
org_key Int32,
region String,
country String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}/dw/dim_org', '{replica}')
PRIMARY KEY(org_key);
INSERT INTO dw.dim_org
VALUES(1, 'EMEA', 'UK'), (2, 'EMEA', 'Germany'), (3, 'EMEA', 'France') (4, 'EMEA', 'Ireland' ), (5, 'EMEA', 'Sweden' ), (6, 'EMEA', 'Portugal' )


-- Fact table
DROP TABLE IF EXISTS dw.fact_sales ON CLUSTER colossus_cluster;
DROP TABLE IF EXISTS dw.fact_sales_local ON CLUSTER colossus_cluster;
CREATE TABLE dw.fact_sales ON CLUSTER colossus_cluster
(
date_key Int32,
product_key Int32,
org_key Int32,
sales_value Float64
)
ENGINE= Distributed('colossus_cluster', 'dw', fact_sales_local, rand());
CREATE TABLE dw.fact_sales_local ON CLUSTER colossus_cluster
(
date_key Int32,
product_key Int32,
org_key Int32,
sales_value Float64
)
ENGINE= MergeTree()
PRIMARY KEY(date_key, product_key,org_key);
INSERT INTO dw.fact_sales VALUES(20231130, 1,1, 10);
INSERT INTO dw.fact_sales VALUES(20231130, 1,1, 20);
INSERT INTO dw.fact_sales VALUES(20231130, 1,1, 30);
INSERT INTO dw.fact_sales VALUES(20231130, 2,1, 40);
INSERT INTO dw.fact_sales VALUES(20231130, 2,1, 50);
INSERT INTO dw.fact_sales VALUES(20231130, 2,1, 60);
INSERT INTO dw.fact_sales VALUES(20231129, 1,2, 10);
INSERT INTO dw.fact_sales VALUES(20231129, 1,2, 20);
INSERT INTO dw.fact_sales VALUES(20231129, 1,2, 30);
INSERT INTO dw.fact_sales VALUES(20231129, 2,2, 40);
INSERT INTO dw.fact_sales VALUES(20231129, 2,2, 50);
INSERT INTO dw.fact_sales VALUES(20231129, 2,2, 60);
INSERT INTO dw.fact_sales VALUES(20231128, 1,3, 10);
INSERT INTO dw.fact_sales VALUES(20231128, 1,3, 20);
INSERT INTO dw.fact_sales VALUES(20231128, 1,3, 30);
INSERT INTO dw.fact_sales VALUES(20231128, 2,3, 40);
INSERT INTO dw.fact_sales VALUES(20231128, 2,3, 50);
INSERT INTO dw.fact_sales VALUES(20231128, 2,3, 60);
INSERT INTO dw.fact_sales VALUES(20231128, 1,4, 10);
INSERT INTO dw.fact_sales VALUES(20231128, 1,4, 20);
INSERT INTO dw.fact_sales VALUES(20231128, 1,4, 30);
INSERT INTO dw.fact_sales VALUES(20231128, 2,4, 40);
INSERT INTO dw.fact_sales VALUES(20231128, 2,4, 50);
INSERT INTO dw.fact_sales VALUES(20231128, 2,4, 60);
INSERT INTO dw.fact_sales VALUES(20231128, 1,5, 10);
INSERT INTO dw.fact_sales VALUES(20231128, 1,5, 20);
INSERT INTO dw.fact_sales VALUES(20231128, 1,5, 30);
INSERT INTO dw.fact_sales VALUES(20231128, 2,5, 40);
INSERT INTO dw.fact_sales VALUES(20231128, 2,5, 50);
INSERT INTO dw.fact_sales VALUES(20231128, 2,5, 60);
INSERT INTO dw.fact_sales VALUES(20231128, 1,6, 10);
INSERT INTO dw.fact_sales VALUES(20231128, 1,6, 20);
INSERT INTO dw.fact_sales VALUES(20231128, 1,6, 30);
INSERT INTO dw.fact_sales VALUES(20231128, 2,6, 40);
INSERT INTO dw.fact_sales VALUES(20231128, 2,6, 50);
INSERT INTO dw.fact_sales VALUES(20231128, 2,6, 60);

```

**Comment by UnamedRus** [comment]
> The issue we have is that when we execute the query against Node 1, only the sub query is pushed down to the shards and the join onto the dimensions is performed on the initiator node. This is sub optimal because sometimes dimensions can have a lot of rows and ideally we want to execute the full query on each shard and return only the final result to combine at the initiator.

Check this article section

https://kb.altinity.com/altinity-kb-queries-and-syntax/group-by/tricks/#shard-your-data-by-one-of-common-high-cardinal-group-by-key

**Comment by den-crane** [comment]
it will be much simple and faster with external dictionaries

**Comment by njcstreet** [comment]
Thanks for your comments / suggestions. We did try dictionaries but found them to be not as fast as the template we used above (although they do solve the issue with the query being pushed down).

in the end  allow_experimental_analyzer = 1 solved the issue with the joins not being pushed down to the shards.
