### ISSUE TITLE
version:23.10.4.25, join one table and order by,

### ISSUE THREAD

**Issue by luxfafa** [ClickHouse/ClickHouse#57884]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
![image](https://github.com/ClickHouse/ClickHouse/assets/38524497/78df9454-f245-4300-9258-26b79ea45a4e)
Single table query is very fast, but after "joining" a small table with hundreds of data, it can be returned in less than one second without "order by CreateTime desc". After adding it, the full table scan takes more than 20 seconds.

**Comment by puthx** [comment]
join了个小表 并且按照大表的createtime order by desc limit 1 扫描了整个表 结果为:
1 row in set. Elapsed: 50.711 sec. Processed 236.96 million rows, 83.03 GB (4.67 million rows/s., 1.64 GB/s.)
Peak memory usage: 49.84 MiB.


如果不加 “createtime order by desc” 保留limit 1,结果为:
1 row in set. Elapsed: 0.192 sec. Processed 1.68 million rows, 326.25 MB (8.76 million rows/s., 1.70 GB/s.)
Peak memory usage: 30.35 MiB.

**Comment by puthx** [comment]
此外 这个语句在20.xx版本是可以在一秒内返回的, 在新搭建的23.10.4.25版本,就成了全表扫描 这两个版本关于这个的表结构没有任何变化,表引擎均为mergetree 新的版本搭建了切片集群 2个切片

**Comment by Algunenano** [comment]
Needs reproduction steps

**Comment by Algunenano** [comment]
Lacks details to reproduce. Please share them.
