### ISSUE TITLE
arrayFold performance for real tasks

### ISSUE THREAD

**Issue by Strate** [ClickHouse/ClickHouse#57880]
I'm trying to use arrayFold for some array processing. Result expected to be tuples of arrays, with sizes close to input array.

I realized that arrayFold slower than native functions, even in very simple case:

```
SELECT arrayReverse(input) AS reversed
FROM
(
    SELECT groupArray(number) AS input
    FROM numbers(10000)
)

1 row in set. Elapsed: 0.010 sec.
```

```
SELECT arrayFold((acc, item) -> arrayPushFront(acc, item), input, CAST([], 'Array(UInt64)')) AS reversed
FROM
(
    SELECT groupArray(number) AS input
    FROM numbers(10000)
)

1 row in set. Elapsed: 0.108 sec.
```

As you can see arrayFold implementation of reversing array is x10 slower than native.

Of course I don't want to just reverse array, but want to build some other array with copmlex rules applied. However, performance is not great, and I think that it related to arrayFold and processing accumulator state

Looks like `arrayPushFront` (and other array/map updating related functions) uses immutable structures and make full copy when you want to just add/update an element.

Could this use-case be faster?

**Comment by UnamedRus** [comment]
> Looks like arrayPushFront (and other array/map updating related functions) uses immutable structures and make full copy when you want to just add/update an element.

It's actually understandable and reasonable, as column data in memory can be used multiple times in query, so it should be immutable.

There is also particular issue with memory allocation for array functions, which use lambda functions.
https://kb.altinity.com/altinity-kb-functions/array-like-memory-usage/

It can be improved, like done for https://github.com/ClickHouse/ClickHouse/pull/54664

> As you can see arrayFold implementation of reversing array is x10 slower than native.

IMO, 10 times isn't that bad, if we take in account ^
