### ISSUE TITLE
MergeFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 49

### ISSUE THREAD

**Issue by kernel288** [ClickHouse/ClickHouse#57900]
i create 6 node cluster , when i comsuer kafka message , The error file is bollow .
I check the table system.mutations , i cancel all mutations . but the erro is not cancel . I want to fix it , Can u get me some idea?
Thank U so mush.
====
2023.12.06 16:20:15.416313 [ 106795 ] {} <Error> MergeFromLogEntryTask: virtual bool DB::ReplicatedMergeMutateTaskBase::executeStep(): Code: 49. DB::Exception: Incomplete granules are not allowed while blocks are granules size. Mark number 12 (rows 8192), rows written in last mark 0, rows to write in last mark from block 1 (from row 8192), total marks currently 13. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa4dde1a in /usr/bin/clickhouse
1. DB::Exception::Exception<unsigned long&, unsigned long, unsigned long&, unsigned long&, unsigned long&, unsigned long>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&, unsigned long&&, unsigned long&, unsigned long&, unsigned long&, unsigned long&&) @ 0x14f1eedc in /usr/bin/clickhouse
2. DB::MergeTreeDataPartWriterWide::shiftCurrentMark(std::__1::vector<DB::Granule, std::__1::allocator<DB::Granule> > const&) @ 0x14f1edd2 in /usr/bin/clickhouse
3. DB::MergeTreeDataPartWriterWide::write(DB::Block const&, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 15ul, 16ul> const*) @ 0x14f1f842 in /usr/bin/clickhouse
4. DB::MergedBlockOutputStream::write(DB::Block const&) @ 0x14ff4960 in /usr/bin/clickhouse
5. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x14e54809 in /usr/bin/clickhouse
6. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x14e5450b in /usr/bin/clickhouse
7. DB::MergeTask::execute() @ 0x14e5945a in /usr/bin/clickhouse
8. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x150349b4 in /usr/bin/clickhouse
9. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x15033cc2 in /usr/bin/clickhouse
10. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(std::__1::shared_ptr<DB::TaskRuntimeData>) @ 0xa4c3aab in /usr/bin/clickhouse
11. DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::threadFunction() @ 0xa4c36f9 in /usr/bin/clickhouse
12. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa5878ca in /usr/bin/clickhouse
13. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xa589a64 in /usr/bin/clickhouse
14. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa584c97 in /usr/bin/clickhouse
15. ? @ 0xa58881d in /usr/bin/clickhouse
16. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
17. __clone @ 0xfe96d in /usr/lib64/libc-2.17.so
 (version 22.3.2.1)

**Comment by Algunenano** [comment]
Please update to a supported release and provide reproduction steps if it happens again

**Comment by kernel288** [comment]
Mysql clickhosue version 
ClickHouse server version 22.5.1 revision 54455

**Comment by kernel288** [comment]
I  update version unitl 23.3.17.13 fix the bug
Thank U so much
