### ISSUE TITLE
Mark every setting in ServerSettings as hot-reloadable or not. 

### ISSUE THREAD

**Issue by nikitamikhaylov** [ClickHouse/ClickHouse#57902]
**Use case**

In order not to restart the server each time for setting change ClickHouse support dynamic reload of the configuration. 
But unfortunately not all the changes there can be applied at runtime. To make it more convenient for database operators let's expose the information whether a setting can be changed without restart or not to `system.server_settings` table. 

**Describe the solution you'd like**

Introduce additional column in `system.server_settings` named `runtime_reload` with type Enum.
Possible values: 
- `FULL` - the setting maybe changed to any value. 
- `ONLY_INCREASE` - the setting maybe only increased (for example for settings like `background_pool_size`, `background_fetches_pool_size`)
- `NO` - the setting can't be changed without restart.

**Comment by skyoct** [comment]
@nikitamikhaylov Hi, I would like to try this issue, but I have some questions that I would like to ask for advice. How to distinguish the runtime_reload type corresponding to the parameters?

**Comment by rschu1ze** [comment]
@pufit who implemented system table `system.server_settings` a while ago (#46550)

**Comment by rschu1ze** [comment]
@skyoct The best approach will be to extend each server setting in Core/ServerSettings.h by a (immutable) runtime-reloadable field. The system view can then just display this information.
