### ISSUE TITLE
notEquals(x, 1) AND notEquals(x, 2) AND notEquals(x, 3) chain rewrite to x NOT IN (1, 2, 3)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#57937]
**Use case**

Optimization for long chain of `AND notEquals` condition, analogue for already existing `OR equals` optimization.

**Comment by kevinmingtarja** [comment]
Hi, I'm interested in contributing to this feature.

**Comment by UnamedRus** [comment]
Hi,

You can take a look into: 
https://github.com/ClickHouse/ClickHouse/blob/84e5870b71c3771828a1c5ea7d71b330d9b75889/src/Analyzer/Passes/LogicalExpressionOptimizerPass.cpp#L336C10-L336C39

Which implements similar optimization for `OR equals`. Null literals should be ignored, AFAIK.

**Comment by kevinmingtarja** [comment]
Got it, thank you for the reference.
