### ISSUE TITLE
Suspected memory leak in 23.8

### ISSUE THREAD

**Issue by alexfernandez** [ClickHouse/ClickHouse#57931]
Migrated from https://github.com/ClickHouse/ClickHouse/issues/54483 as a separate issue, since we are not using Kafka.

**Describe the unexpected behaviour**

Using ClickHouse 23.8.2.7. Memory increases with database usage, apparently a memory leak. After restarting memory is reduced drastically, then starts climbing up again at around 300 MB / day.

![image](https://github.com/ClickHouse/ClickHouse/assets/876570/80481310-be85-4ddd-b879-cfadd91bbd48)

**How to reproduce**
* Which ClickHouse server version to use: ClickHouse 23.8.2.7
* One particular database has a somewhat non-standard usage: it receives a lot of inserts but they usually last for less than a minute, it is a sort of internal cache. There we see memory usage raising at around 700 MB / day. But we see the same effect in other ClickHouse servers with the same version, less pronounced (300 MB / day). Memory is always released upon restart.

**Expected behavior**

Since no new data is being stored we would expect that the database should recycle memory internally without having to restart it.

**Additional context**

All queries run on a particular instance that is using ~19 GB right now. Merges, as requested by @antaljanosbenjamin:
```
SELECT
    formatReadableSize(memory_usage),
    *
FROM system.merges

Ok.

0 rows in set. Elapsed: 0.001 sec. 
```

Memory stats, as requested by @azat:
```
WITH
    (
        SELECT sum(CAST(value, 'UInt64'))
        FROM system.metrics
        WHERE metric = 'MemoryTracking'
    ) AS memory_tracked_,
    (
        SELECT sum(total_bytes)
        FROM system.tables
        WHERE engine IN ('Join', 'Memory', 'Buffer', 'Set')
    ) AS memory_tables_,
    (
        SELECT sum(CAST(value, 'UInt64'))
        FROM system.asynchronous_metrics
        WHERE metric LIKE '%CacheBytes'
    ) AS memory_caches_,
    (
        SELECT sum(CAST(memory_usage, 'UInt64'))
        FROM system.processes
    ) AS memory_processes_,
    (
        SELECT sum(CAST(memory_usage, 'UInt64'))
        FROM system.merges
    ) AS memory_merges_,
    (
        SELECT sum(bytes_allocated)
        FROM system.dictionaries
    ) AS memory_dictionaries_,
    (
        SELECT sum(primary_key_bytes_in_memory_allocated)
        FROM system.parts
    ) AS memory_primary_keys_
SELECT
    assumeNotNull(memory_tracked_) AS memory_tracked,
    assumeNotNull(memory_tables_) AS memory_tables,
    assumeNotNull(memory_caches_) AS memory_caches,
    assumeNotNull(memory_processes_) AS memory_processes,
    assumeNotNull(memory_merges_) AS memory_merges,
    assumeNotNull(memory_dictionaries_) AS memory_dictionaries,
    assumeNotNull(memory_primary_keys_) AS memory_primary_keys
FORMAT Vertical

Row 1:
──────
memory_tracked:      19684595772
memory_tables:       0
memory_caches:       4538334048
memory_processes:    175800
memory_merges:       0
memory_dictionaries: 0
memory_primary_keys: 2427744
```

and more:
```
SELECT
    metric,
    value
FROM system.asynchronous_metrics
WHERE metric LIKE '%jemalloc%'

┌─metric───────────────────────────────────┬────────value─┐
│ jemalloc.epoch                           │      1507330 │
│ jemalloc.arenas.all.pactive              │      4466147 │
│ jemalloc.background_thread.num_runs      │            0 │
│ jemalloc.active                          │  18293338112 │
│ jemalloc.retained                        │ 286359556096 │
│ jemalloc.arenas.all.pmuzzy               │         3687 │
│ jemalloc.allocated                       │  18102287104 │
│ jemalloc.background_thread.num_threads   │            0 │
│ jemalloc.metadata_thp                    │            0 │
│ jemalloc.arenas.all.muzzy_purged         │   6963334478 │
│ jemalloc.arenas.all.dirty_purged         │  11647316965 │
│ jemalloc.mapped                          │  19758575616 │
│ jemalloc.metadata                        │   1241636848 │
│ jemalloc.resident                        │  19578085376 │
│ jemalloc.background_thread.run_intervals │            0 │
│ jemalloc.arenas.all.pdirty               │        14069 │
└──────────────────────────────────────────┴──────────────┘
```

Memory allocated:

```
SELECT
    *,
    allocations - deallocations AS active_allocations,
    size * active_allocations AS allocated_bytes
FROM system.jemalloc_bins
WHERE allocated_bytes > 0
ORDER BY allocated_bytes DESC

┌─index─┬─large─┬──────size─┬─allocations─┬─deallocations─┬─active_allocations─┬─allocated_bytes─┐
│    12 │     0 │       256 │  1964164752 │    1934402605 │           29762147 │      7619109632 │
│     4 │     0 │        64 │  8765929776 │    8725048938 │           40880838 │      2616373632 │
│     5 │     0 │        80 │  2965546952 │    2933024532 │           32522420 │      2601793600 │
│    11 │     0 │       224 │   850928924 │     839491604 │           11437320 │      2561959680 │
│     2 │     0 │        32 │  7006726704 │    6965106953 │           41619751 │      1331832032 │
│    91 │     1 │ 234881024 │           1 │             0 │                  1 │       234881024 │
│     6 │     0 │        96 │  5682488087 │    5680410878 │            2077209 │       199412064 │
│     7 │     0 │       112 │  1402413732 │    1401220491 │            1193241 │       133642992 │
[...]
```

Please let us know what else we can do to diagnose the issue. Thanks!

**Comment by den-crane** [comment]
23.8.2.7 is obsolete. Upgrade to 23.8.8.20.

1 What protocol do you use for inserts and for selects? 
2 What format do you use? 
3 Does it stops to grow if you disable inserts? selects?
4 Do you use mutations? How do you delete data?
5 Do you use Engine=Buffer?
6 Do you use insertion into Distributed tables?
7 Do you use query cache?
8 Provide
```
select name, value from system.server_settings where changed;

select name, value from system.merge_tree_settings where changed;

select name, value from system.settings where changed;

select distinct type,  compression_codec from system.columns where database not in ('system','INFORMATION_SCHEMA','information_schema') ;
```

**Comment by den-crane** [comment]
9 What are the engines of the tables?

**Comment by azat** [comment]
You are on 23.8, so you don't have https://github.com/ClickHouse/ClickHouse/pull/52792, than you also need to provide `MMappedAllocs` and `MMappedAllocBytes` metrics (`system.metrics`)

Also please provide the previous version of ClickHouse.

**Comment by azat** [comment]
Also please provide the following:
- RSS/VIRT of process (`grep Vm /proc/$(pgrep clickhouse-serv)/status`)
- and cgroup stats (`cat /sys/fs/cgroup/$(cut -d: -f3 /proc/$(pgrep clickhouse-serv)/cgroup)/memory.stat`) _I'm assuming that you do have running server via systemd, then you will have separate cgroup_

**Comment by alexfernandez** [comment]
> You are on 23.8, so you don't have #52792, than you also need to provide `MMappedAllocs` and `MMappedAllocBytes` metrics (`system.metrics`)

There you go:

```
SELECT *
FROM system.metrics
WHERE metric LIKE 'MMap%'

┌─metric────────────┬─────value─┬─description─────────────────────────┐
│ MMappedFiles      │         1 │ Total number of mmapped files.      │
│ MMappedFileBytes  │ 519114224 │ Sum size of mmapped file regions.   │
│ MMappedAllocs     │         0 │ Total number of mmapped allocations │
│ MMappedAllocBytes │         0 │ Sum bytes of mmapped allocations    │
└───────────────────┴───────────┴─────────────────────────────────────┘
```

> Also please provide the previous version of ClickHouse.

I don't understand, what previous version? We are running 23.8.2.7:

```
SELECT *
FROM system.metrics
WHERE metric LIKE '%Version%'
FORMAT Vertical

Row 1:
──────
metric:      VersionInteger
value:       23008002
```

**Comment by alexfernandez** [comment]
> Also please provide the following:

Sure!
 
> * RSS/VIRT of process (`grep Vm /proc/$(pgrep clickhouse-serv)/status`)

```
$ grep Vm /proc/$(pgrep clickhouse-serv)/status
VmPeak:	346043060 kB
VmSize:	346043060 kB
VmLck:	  291852 kB
VmPin:	       0 kB
VmHWM:	21179412 kB
VmRSS:	20843156 kB
VmData:	345133216 kB
VmStk:	     132 kB
VmExe:	  291852 kB
VmLib:	    2320 kB
VmPTE:	  614420 kB
VmSwap:	       0 kB
```

> * and cgroup stats (`cat /sys/fs/cgroup/$(cut -d: -f3 /proc/$(pgrep clickhouse-serv)/cgroup)/memory.stat`) _I'm assuming that you do have running server via systemd, then you will have separate cgroup_

Indeed:

```
$ cat /sys/fs/cgroup/$(cut -d: -f3 /proc/$(pgrep clickhouse-serv)/cgroup)/memory.stat
anon 21035593728
file 6102999040
kernel 1793294336
kernel_stack 8339456
pagetables 629751808
sec_pagetables 0
percpu 192
sock 4096
vmalloc 0
shmem 4096
zswap 0
zswapped 0
file_mapped 9252864
file_dirty 7569408
file_writeback 0
swapcached 0
anon_thp 0
file_thp 0
shmem_thp 0
inactive_anon 18534170624
active_anon 1193799680
inactive_file 5584982016
active_file 1825579008
unevictable 0
slab_reclaimable 1150291392
slab_unreclaimable 4869232
slab 1155160624
workingset_refault_anon 0
workingset_refault_file 4517315
workingset_activate_anon 0
workingset_activate_file 1278646
workingset_restore_anon 0
workingset_restore_file 143066
workingset_nodereclaim 0
pgscan 26988711
pgsteal 24160345
pgscan_kswapd 26978814
pgscan_direct 9897
pgscan_khugepaged 0
pgsteal_kswapd 24150448
pgsteal_direct 9897
pgsteal_khugepaged 0
pgfault 2720763532
pgmajfault 791
pgrefill 3463429
pgactivate 23117682
pgdeactivate 2373233
pglazyfree 2574598934
pglazyfreed 744
zswpin 0
zswpout 0
thp_fault_alloc 0
thp_collapse_alloc 0
```

Hope you can see anything there because to me this output is a big mess :sweat_smile:

**Comment by azat** [comment]
>I don't understand, what previous version? We are running 23.8.2.7:

You sad that this issue pops up after upgrade, so the question is, what version you had prio upgrade?

**Comment by alexfernandez** [comment]
> 23.8.2.7 is obsolete. Upgrade to 23.8.8.20.

This is not possible right now. We have seen the same behavior with 23.10.3.5, is that version OK? We will upgrade to 23.10.3.5 as soon as we can.

> 1 What protocol do you use for inserts and for selects?

We use HTTP for both.

> 2 What format do you use for Inserts, for Selects? JSON/TSV/CSV ?

We use row binary for inserts, JSON for selects.

> 3 Does it stops to grow if you pause inserts? selects?

We have not tried because it would mean pausing the instances for several days.

> 4 Do you use mutations? TTL? How do you delete data?

We use no mutations or TTL on this instance. We delete data using `drop table`.

> 5 Do you use Engine=Buffer?

No.

> 6 Do you use insertion into Distributed tables?>

No.

 7 Do you use query cache?

No.

> 8 Provide
> 
> select name, value from system.server_settings where changed;

```
SELECT
    name,
    value
FROM system.server_settings
WHERE changed

┌─name─────────────────────────────────┬─value──────┐
│ shutdown_wait_unfinished_queries     │ 1          │
│ max_connections                      │ 4096       │
│ default_database                     │ default    │
│ max_server_memory_usage_to_ram_ratio │ 0.9        │
│ max_concurrent_queries               │ 100        │
│ uncompressed_cache_size              │ 8589934592 │
│ mark_cache_size                      │ 5368709120 │
│ background_pool_size                 │ 16         │
│ background_fetches_pool_size         │ 8          │
└──────────────────────────────────────┴────────────┘
```

> select name, value from system.merge_tree_settings where changed;

```
SELECT
    name,
    value
FROM system.merge_tree_settings
WHERE changed

┌─name─────────────────────────────────────────────┬─value───────┐
│ ratio_of_defaults_for_sparse_serialization       │ 1           │
│ max_bytes_to_merge_at_max_space_in_pool          │ 53687091200 │
│ max_suspicious_broken_parts                      │ 100         │
│ initialization_retry_period                      │ 10          │
│ wait_for_unique_parts_send_before_shutdown_ms    │ 10000       │
│ materialize_ttl_recalculate_only                 │ 1           │
│ allow_vertical_merges_from_compact_to_wide_parts │ 0           │
│ compress_marks                                   │ 0           │
│ compress_primary_key                             │ 0           │
└──────────────────────────────────────────────────┴─────────────┘
```
> 
> select name, value from system.settings where changed;

```
SELECT
    name,
    value
FROM system.settings
WHERE changed

┌─name──────────────────────────────────────────┬─value──────────────┐
│ max_threads                                   │ 16                 │
│ use_uncompressed_cache                        │ 0                  │
│ move_all_conditions_to_prewhere               │ 0                  │
│ enable_multiple_prewhere_read_steps           │ 0                  │
│ move_primary_key_columns_to_end_of_prewhere   │ 0                  │
│ compile_expressions                           │ 0                  │
│ compile_aggregate_expressions                 │ 0                  │
│ cluster_for_parallel_replicas                 │ xxx │
│ insert_deduplicate                            │ 1                  │
│ http_wait_end_of_query                        │ 1                  │
│ http_response_buffer_size                     │ 104857600          │
│ joined_subquery_requires_alias                │ 0                  │
│ max_bytes_before_external_group_by            │ 1442450940         │
│ max_execution_time                            │ 0                  │
│ max_expanded_ast_elements                     │ 50000              │
│ join_algorithm                                │ hash               │
│ max_memory_usage                              │ 31000000000        │
│ memory_usage_overcommit_max_wait_microseconds │ 50000              │
│ log_query_threads                             │ 0                  │
│ max_partitions_per_insert_block               │ 100                │
│ enable_lightweight_delete                     │ 0                  │
│ allow_experimental_lightweight_delete         │ 0                  │
│ optimize_monotonous_functions_in_order_by     │ 0                  │
│ enable_global_with_statement                  │ 0                  │
│ optimize_rewrite_sum_if_to_count_if           │ 0                  │
│ distributed_ddl_entry_format_version          │ 3                  │
│ insert_keeper_max_retries                     │ 15                 │
│ insert_keeper_retry_initial_backoff_ms        │ 100                │
│ insert_keeper_retry_max_backoff_ms            │ 2000               │
│ input_format_null_as_default                  │ 0                  │
└───────────────────────────────────────────────┴────────────────────┘
```
> 
> select distinct type,  compression_codec from system.columns where database not in ('system','INFORMATION_SCHEMA','information_schema') ;

```
SELECT DISTINCT
    type,
    compression_codec
FROM system.columns
WHERE database NOT IN ('system', 'INFORMATION_SCHEMA', 'information_schema')

┌─type───────────────────┬─compression_codec─┐
│ String                 │                   │
│ Nullable(String)       │                   │
│ Int64                  │                   │
│ UInt8                  │                   │
│ DateTime               │                   │
│ Nullable(Float32)      │                   │
│ Array(String)          │                   │
│ LowCardinality(String) │                   │
│ UUID                   │                   │
│ Int32                  │                   │
│ UInt64                 │                   │
│ UInt32                 │                   │
│ Int8                   │                   │
│ UInt16                 │                   │
│ Date                   │                   │
│ Float32                │                   │
│ Nullable(Int16)        │                   │
│ Float64                │                   │
│ Int16                  │                   │
│ Nullable(Int8)         │                   │
│ Nullable(DateTime)     │                   │
│ Nullable(Int32)        │                   │
│ DateTime64(3)          │                   │
└────────────────────────┴───────────────────┘
```

From another message:
> 9 What are the engines of the tables?

They are all `MergeTree`.

Hope this helps!

**Comment by alexfernandez** [comment]
> > I don't understand, what previous version? We are running 23.8.2.7:
> 
> You sad that this issue pops up after upgrade, so the question is, what version you had prio upgrade?

We had 22.8 where there was no memory growth, the issue pops up with 23.8 and 23.10.

**Comment by den-crane** [comment]
>But we do know that we see the same memory growth in the instance where we insert than on the read replica.
>We use no mutations or TTL on this instance. We delete data using drop table.

So we can suspect that the leak due to insertion of RowBinary+HTTP or due to multiple create/drop table?
What API / language do you use for insertion? Are they reuse HTTP/TCP connection for multiple inserts?
How many tables do you create/drop per day?

**Comment by aol-59** [comment]
After I disabled statistics_interval_ms, I restarted ClickHouse 16 hours ago, and everything seemed fine until now. Additionally, I created a new file in **config.d** named **kafka.xml** then i restarted Clickhouse.

```
<yandex>
  <kafka>
        <statistics_interval_ms>0</statistics_interval_ms>
  </kafka>
</yandex>
```

I hope this information can assist you.

**Comment by alexfernandez** [comment]
> After I disabled statistics_interval_ms, I restarted ClickHouse 16 hours ago, and everything seemed fine until now. Additionally, I created a new file in **config.d** named **kafka.xml** then i restarted Clickhouse.
> 
> ```
> <yandex>
>   <kafka>
>         <statistics_interval_ms>0</statistics_interval_ms>
>   </kafka>
> </yandex>
> ```
> 
> I hope this information can assist you. @alexfernandez

But we are not using Kafka on this particular server, do you think it is worth trying anyway?

**Comment by aol-59** [comment]
> > After I disabled statistics_interval_ms, I restarted ClickHouse 16 hours ago, and everything seemed fine until now. Additionally, I created a new file in **config.d** named **kafka.xml** then i restarted Clickhouse.
> 
> > 
> 
> > ```
> 
> > <yandex>
> 
> >   <kafka>
> 
> >         <statistics_interval_ms>0</statistics_interval_ms>
> 
> >   </kafka>
> 
> > </yandex>
> 
> > ```
> 
> > 
> 
> > I hope this information can assist you. @alexfernandez
> 
> 
> 
> Thanks @aol-59 ! But we are not using Kafka on this particular server, do you think it is worth trying anyway?

I believe it is enabled by default.

**Comment by alexfernandez** [comment]
@den-crane I have been collecting the answers, there you go:

> So we can suspect that the leak is due to the insertion of RowBinary+HTTP or due to multiple create/drop table?

We suspect insertion because it seems to correlate with the leak but we are not sure.

> What API / language do you use for insertion?

Python and HTTP API (aiohttp).

> Are they reuse HTTP/TCP connection for multiple inserts? Yes

> Do you use compression for HTTP? content-encoding compression or CH compression? No

> How many tables do you create/drop per day (ballpark)?

Around 30k tables created and dropped per day.

Thanks!

**Comment by azat** [comment]
@alexfernandez this (https://github.com/ClickHouse/ClickHouse/issues/57931#issuecomment-1858875438) information you need to look/post here when you think that the server eats too much RAM (i.e. it does not correlate with the query from the description), and the more difference the better.

And also you may try the memory profiling that I suggested here - https://github.com/ClickHouse/ClickHouse/issues/54483#issuecomment-1855869079

**Comment by alexfernandez** [comment]
Hi @azat ,

> @alexfernandez this ([#57931 (comment)](https://github.com/ClickHouse/ClickHouse/issues/57931#issuecomment-1858875438)) information you need to look/post here when you think that the server eats too much RAM (i.e. it does not correlate with the query from the description), and the more difference the better.

Already sent [here](https://github.com/ClickHouse/ClickHouse/issues/57931#issuecomment-1859785429).

> And also you may try the memory profiling that I suggested here - [#54483 (comment)](https://github.com/ClickHouse/ClickHouse/issues/54483#issuecomment-1855869079)

I see no `MemoryTracking` entries in the log :thinking: Also I'm wary of using the profiler since this is a pretty heavy duty server. Any other info I may provide?

**Comment by Jack1007** [comment]
I encounter memory leak too.
How to analyse clickhosue process memory liked Java VM dump? I had checked all metrics table about Memory, but everything looks fine.So I want to dump memory from clickhouse process,is there any way to do it?

**Comment by azat** [comment]
@Jack1007 see https://github.com/ClickHouse/ClickHouse/issues/54483#issuecomment-1855869079 (there is also an ongoing work of moving this into system table - https://github.com/ClickHouse/ClickHouse/issues/57703)

**Comment by fishday53** [comment]
Hi! I faced with Memory Leak after upgrade ClickHouse to 23.8 version too.

Current version: 23.8.9.54
Shards: 1
Replicas: 2
Using kafka engine: No

I have 2 replicas (node1 and node2) and there is no client queries to node2 at all.
But after the upgrading to 23.8 version, the both nodes started to leak memory similarly.
Memory leak is going slow, but inevitable: after 30 days the memory on a node is over.

This is memory consumption on the node2 (with no client queries):
<img width="1831" alt="clickhouse" src="https://github.com/ClickHouse/ClickHouse/assets/41431053/00b81375-c719-4b5c-8e90-2c09297f28fe">

Please, tell me what additional information may I provide you about the issue :pray

**Comment by jrdi** [comment]
@ fishday53, can you share the version you used before the upgrade? Also, how many create (or drop) table statements do you run per day? We've observed that some memory leak is happening in every create statement, but we had no luck finding the culprit of it.

**Comment by fishday53** [comment]
@jrdi, Hi! 
Previous version was: 22.2.2.1

Here results for create and drop tables:
```
SELECT
    event_date,
    count(*)
FROM query_log
WHERE query LIKE '%CREATE TABLE%'
GROUP BY event_date

Query id: 2ac4d3aa-10e0-4fb5-8d08-27677a93516a

┌─event_date─┬─count()─┐
│ 2023-12-13 │   37863 │
│ 2023-12-14 │   38296 │
│ 2023-12-15 │   39576 │
│ 2023-12-16 │   39592 │
│ 2023-12-17 │   39432 │
│ 2023-12-18 │   38872 │
│ 2023-12-19 │   39432 │
│ 2023-12-20 │   38304 │
│ 2023-12-21 │   39224 │
│ 2023-12-22 │   39352 │
│ 2023-12-23 │   39784 │
│ 2023-12-24 │   39544 │
│ 2023-12-25 │   39232 │
│ 2023-12-26 │   38832 │
│ 2023-12-27 │   39112 │
│ 2023-12-28 │   39424 │
│ 2023-12-29 │   39288 │
│ 2023-12-30 │   39568 │
│ 2023-12-31 │   39272 │
│ 2024-01-01 │   39120 │
│ 2024-01-02 │   38960 │
│ 2024-01-03 │   35300 │
│ 2024-01-04 │   39600 │
│ 2024-01-05 │   39664 │
│ 2024-01-06 │   39672 │
│ 2024-01-07 │   39104 │
│ 2024-01-08 │   39032 │
│ 2024-01-09 │   38640 │
│ 2024-01-10 │   39216 │
│ 2024-01-11 │   19058 │
└────────────┴─────────┘

SELECT
    event_date,
    count(*)
FROM query_log
WHERE query LIKE '%DROP TABLE%'
GROUP BY event_date

Query id: 18e4f2e2-c36a-460a-b454-bb213e7f4cc9

┌─event_date─┬─count()─┐
│ 2023-12-13 │   64280 │
│ 2023-12-14 │   65375 │
│ 2023-12-15 │   67920 │
│ 2023-12-16 │   67944 │
│ 2023-12-17 │   67620 │
│ 2023-12-18 │   66584 │
│ 2023-12-19 │   67656 │
│ 2023-12-20 │   65680 │
│ 2023-12-21 │   67244 │
│ 2023-12-22 │   67476 │
│ 2023-12-23 │   68280 │
│ 2023-12-24 │   67872 │
│ 2023-12-25 │   67220 │
│ 2023-12-26 │   66292 │
│ 2023-12-27 │   66936 │
│ 2023-12-28 │   67616 │
│ 2023-12-29 │   67224 │
│ 2023-12-30 │   67852 │
│ 2023-12-31 │   67376 │
│ 2024-01-01 │   67188 │
│ 2024-01-02 │   66776 │
│ 2024-01-03 │   59456 │
│ 2024-01-04 │   67968 │
│ 2024-01-05 │   68076 │
│ 2024-01-06 │   68096 │
│ 2024-01-07 │   66952 │
│ 2024-01-08 │   66764 │
│ 2024-01-09 │   65924 │
│ 2024-01-10 │   67176 │
│ 2024-01-11 │   32554 │
└────────────┴─────────┘
```

**Comment by jrdi** [comment]
Thanks, @fishday53! Looks like it could be related to what we have observed. Let's see if we can find the culprit.
