### ISSUE TITLE
Remove `OPTIMIZE CLEANUP` and `is_deleted`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#57930]
Sorry, you might not like this proposal, but this feature is working incorrectly, and we have no other choice than to remove it. We didn't want or welcome this feature either.

**Comment by filimonov** [comment]
@youennL-cs

**Comment by SaltTan** [comment]
The feature was introduced in https://github.com/ClickHouse/ClickHouse/pull/41005

**Comment by alexey-milovidov** [comment]
Clarification - it is removed due to the possibility of data corruption, including irreparable data loss and security vulnerabilities.

**Comment by alexey-milovidov** [comment]
If you have used this feature, please contact support@clickhouse.com

**Comment by filimonov** [comment]
The similar behavior to is_deleted can be mimicked this way:

```
CREATE TABLE test
(
    `uid` String,
    `version` UInt32,
    `is_deleted` UInt8
)
ENGINE = ReplacingMergeTree(version)
ORDER BY uid;

set additional_table_filters={'test' : 'is_deleted = 0'};
```

Seems to work ok, bt a bit inconvenient to modify settings for every table
