### ISSUE TITLE
It is not work when using file() to read files in the NFS in clickhouse-server-23.11.2.11 

### ISSUE THREAD

**Issue by babu1801** [ClickHouse/ClickHouse#57949]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

when selecting data through file() function,  the query failed, and get the exception:
**Code: 291   File  `...` is not inside  '/home/clickhouse/ckhome/user_files/'  (DATABASE_ACCESS_DENIED)**   

the files  are saved in a NFS  path, which is mounted on the clickhouse host.
I create a soft link under the  path defined in <user_files_path>. 

**Before 23.11.1 and 23.11.2, this method is work**. I can load data in the files on the NFS through file().
Begin from 23.11.1，it is not worked any more.

**How to reproduce**
mount a NFS filesystem in the Clickhouse server,  for example : /data/RawData

and create a soft link under the user file path defined in the  <user_files_path>/home/clickhouse/ckhome/user_files/</user_fiels_path>

        ln -s /data/RawData /home/clickhouse/ckhome/user_files/RawData

after that,  query data:
select * from file('RawData/*.csv', 'CSVWithNames');

it will get results before 23.11.1 , and get error message since 23.11.1

* Which ClickHouse server version to use
    clickhouse-server-23.11.2.11 

* Which interface to use, if matters
 clickhouse-client , or  DataGrip through JDBC

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
select * from file('RawData/*.csv', 'CSVWithNames');

**Expected behavior**
the data in the csv will be returned

**Error message and/or stacktrace**
![image](https://github.com/ClickHouse/ClickHouse/assets/19375576/38aa2aec-0fa4-47db-bfc2-8e2ca50a494b)

![image](https://github.com/ClickHouse/ClickHouse/assets/19375576/a85ae834-d053-46db-9c87-c02ded4c0bf0)

**Additional context**

**Comment by den-crane** [comment]
> ln -s /data/RawData /home/clickhouse/ckhome/user_files/RawData

You read not from `RawData` but from `RawTradeData`. You need to rename folder or change symlink
