### ISSUE TITLE
Mutations with delete where queryies

### ISSUE THREAD

**Issue by fasolwbanke** [ClickHouse/ClickHouse#57982]
Is this normal clickhaus operation? 
When reloading one of the replicas, on other replicas we execute a DELETE FROM WHERE query and get an error: 
Code: 341. DB::Exception: Mutation is not finished because some replicas are inactive right now: clickhouse Mutation will be done asynchronously. (UNFINISHED) (version 23.11.1.2711 (official build))
Ideally, after the replica is loaded, the mutation will be pulled up, but I'm not quite clear what the error is - is it informational?

**Comment by den-crane** [comment]
>is it informational?

Yes, is it informational
