### ISSUE TITLE
ReplicatedSummingMergeTree does not insert row with missing columns that gets summed but the result of insert is successful.

### ISSUE THREAD

**Issue by grzegorz-liter-getindata** [ClickHouse/ClickHouse#58033]
**Describe what's wrong**

Inserting a row to  ReplicatedSummingMergeTree that have missing value in columns that get summed up is successful but inserts no rows.

**Does it reproduce on recent release?**

Yes, tested on `select version() -- 23.11.2.11`

**Enable crash reporting**

N/A

**How to reproduce**

```sql
select version() -- 23.11.2.11

CREATE DATABASE test ON CLUSTER '{cluster}' ENGINE = Atomic()

CREATE TABLE test.test1 ON CLUSTER '{cluster}' (
	col1 String,
	col2 String,
	col3 UInt32
) ENGINE ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/test/test1', '{replica}', (col3))
    ORDER BY (col1)
    PRIMARY KEY (col1);
    
CREATE OR REPLACE TABLE test.test1_d ON CLUSTER '{cluster}' AS test.test1
ENGINE = Distributed('{cluster}', 'test', test1, cityHash64(`col1`));

insert into test.test1_d (col1, col2, col3)
values ('aa', 'bb', 123);
-- insert successful, 1 row inserted

select * from test.test1_d where col1 = 'aa';
-- returns 1 row <- OK

insert into test.test1_d (col3)
values (456)
-- insert successful, 1 row inserted

select * from test.test1_d
where col3 = 456
-- return 1 row <- OK, col1, and col2 were inserted with default values

insert into test.test1_d (col1)
values ('bb');
-- insert succesful, updated rows 2 <- this is strange

select * from test.test1_d where col1 = 'bb';
-- returns 0 rows <- NOK this is a bug
```

**Expected behavior**

Inserting a row without passing values for summed up columns should ether failed with proper exception or insert row with default value.

**Error message and/or stacktrace**

No error message

**Additional context**

**Comment by den-crane** [comment]
summingmergetree does not store rows with with zeros in metrics columns 

See example https://fiddle.clickhouse.com/49b59460-3351-4cd2-908c-29608a1a4b90


https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/summingmergetree

_If the values were 0 in all of the columns for summation, the row is deleted._

You can use SimpleAggregateFunction instead https://fiddle.clickhouse.com/dd39ad53-875e-49f1-b0ad-dfe80c4cfc74
