### ISSUE TITLE
PostgreSQL table function feature: allow custom selection query that will run in postgres

### ISSUE THREAD

**Issue by mraasvel** [ClickHouse/ClickHouse#58034]
**Use case**

Allows efficient usage of postgres indexes and run queries in postgres based on arguments of the clickhouse query.

For example, say I have a large table in postgres with an efficient index. It would be more efficient to filter this in postgres, where the indexes are already set up, than to import all the data into clickhouse first.

**Describe the solution you'd like**

Customizability of the query that is ran in postgres in order to retrieve the data.

Something similar to the duckdb `postgres_query` would be ideal:
https://github.com/duckdb/postgres_scanner?tab=readme-ov-file#running-sql-queries-in-postgres-with-postgres_query

`postgresql('database', 'SELECT * FROM cards WHERE color = 'blue' LIMIT 3')`

> A clear and concise description of any alternative solutions or features you've considered.

- Running the query in clickhouse after importing all data from the postgres table.
- Use the clickhouse `url` table function, calling a service around the postgres database which then streams the data based on the query params.

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/19320

**Comment by canhld94** [comment]
Have you tried `PostgreSQL` engine and `postgresql` table function https://clickhouse.com/docs/en/engines/table-engines/integrations/postgresql ?

It should work as your expectation when query is not too complex.

> SELECT queries on PostgreSQL side run as COPY (SELECT ...) TO STDOUT inside read-only PostgreSQL transaction with commit after each SELECT query.
> Simple WHERE clauses such as =, !=, >, >=, <, <=, and IN are executed on the PostgreSQL server.
> All joins, aggregations, sorting, IN [ array ] conditions and the LIMIT sampling constraint are executed in ClickHouse only after the query to PostgreSQL finishes.

**Comment by mraasvel** [comment]
Yeah, I make use of some postgres JSON operators
