### ISSUE TITLE
license validity period

### ISSUE THREAD

**Issue by LiyuTzyAge** [ClickHouse/ClickHouse#58059]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

Hi, I noticed that the expiration date in the license file is set to 2023. Will there be any changes to the license after this date?

![image](https://github.com/ClickHouse/ClickHouse/assets/48547917/02284173-83ba-47d4-aac6-1b11252cb2ef)

**Comment by alexey-milovidov** [comment]
It isn't the expiration date; it is the date of publishing.
Read the license, e.g. "Contributor hereby grants to You a perpetual..."

**Comment by alexey-milovidov** [comment]
@LiyuTzyAge, see https://github.com/ClickHouse/ClickHouse/commit/885db35f9d743602e128b829fe04bcf75de6094c
