### ISSUE TITLE
Allows ALIAS columns in S3 engine

### ISSUE THREAD

**Issue by panthony** [ClickHouse/ClickHouse#58064]
For tiny datasets, using the S3 engine to directly read data from parquet files is really practical.

But in my situation those parquet files usually only stores raw data (ex: url) and not data that can be derived (ex: url_path).

Being able to create ALIAS column with S3 engines would allows to have something like:

```sql
CREATE TABLE my_table
(
    url String,
    url_path String ALIAS path(url)
)
ENGINE = S3(
 'https://path/to/s3/*.parquet',
 Parquet
)
```

It would allows to expose the same schema whether the S3 engine is used or a more typical MergeTree for bigger datasets (with the column being indexed).

In this exemple the expression is really simple but it can be much more complex.

I tracked down the change to this commit but there was not much context:

https://github.com/ClickHouse/ClickHouse/commit/3e08800cb5b21a3caa04125a0fecbeab772f2cde

I can understand why `MATERIALIZED` column could be problematic, but I'm not seeing why "ALIAS" column in a read-only context would not be possible:

https://clickhouse.com/docs/en/sql-reference/statements/create/table#alias

**Comment by UnamedRus** [comment]
Instead of table with ENGINE = S3() you can use view with s3 table function, and have any preprocessed column in it

**Comment by panthony** [comment]
Hi @UnamedRus 

Interesting alternative, it was possible to create such a view:

```sql
CREATE VIEW my_view AS
SELECT
    url,
    path(url) as url_path
FROM s3(
 'https://path/to/s3/*.parquet',
 Parquet
)
```

It looks like it behave differently in some scenarios.


For exemple with a simple count (select count() from table):

1) Using table

> 1 row in set. Elapsed: 0.151 sec. Processed 877.20 thousand rows, 126.00 B (5.79 million rows/s., 832.24 B/s.)
Peak memory usage: 56.00 KiB.

```
┌─explain─────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY)) │
│   Aggregating                               │
│     Expression (Before GROUP BY)            │
│       ReadFromStorage (S3)                  │
└─────────────────────────────────────────────┘
```


1) Using view


> 1 row in set. Elapsed: 1.115 sec. Processed 877.20 thousand rows, 13.80 MB (786.65 thousand rows/s., 12.38 MB/s.)
Peak memory usage: 2.52 MiB.

☝🏻 that is the full dataset

```
┌─explain────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))                                                                                                                                │
│   Aggregating                                                                                                                                                              │
│     Expression ((Before GROUP BY + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Projection + Before ORDER BY))))) │
│       ReadFromStorage (S3)                                                                                                                                                 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Or when I read a field in the 10 first entries (select url from table limit 10)

1) Using table

> 10 rows in set. Elapsed: 1.140 sec. Processed 8.19 thousand rows, 128.89 KB (7.19 thousand rows/s., 113.10 KB/s.)
Peak memory usage: 1.38 MiB.

```
┌─explain──────────────────────────────────────┐
│ Expression ((Projection + Before ORDER BY))  │
│   Limit (preliminary LIMIT (without OFFSET)) │
│     ReadFromStorage (S3)                     │
└──────────────────────────────────────────────┘
```


2) Using view

> 10 rows in set. Elapsed: 1.224 sec. Processed 16.38 thousand rows, 257.79 KB (13.38 thousand rows/s., 210.54 KB/s.)
Peak memory usage: 1.37 MiB.


```
┌─explain───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Expression ((Projection + (Before ORDER BY + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Projection + Before ORDER BY)))))) │
│   Limit (preliminary LIMIT (without OFFSET))                                                                                                                                          │
│     ReadFromStorage (S3)                                                                                                                                                              │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```


Tried other queries, it looks like it read always twice as much data (but twice as fast too), wonder what is happening here 🤔

**Comment by panthony** [comment]
For the count being sub-optimal I could reproduce it simply by doing:

```sql
select count() FROM (select * from s3(...))
```

Which is the way the view is described as [working](https://clickhouse.com/docs/en/sql-reference/statements/create/view#normal-view)

Can be easily reproduced by:

```sql
select count() from (select 1 from s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/uk-house-prices/parquet/house_prices_all.parquet'))
```

```sql
select count() from s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/uk-house-prices/parquet/house_prices_all.parquet')
```

**Comment by UnamedRus** [comment]
> Tried other queries, it looks like it read always twice as much data (but twice as fast too), wonder what is happening here 🤔

Most likely something wrong with counting of metrics.

**Comment by panthony** [comment]
Ok, not not how to confirm this but I have the exact same query tree (`explain query tree`) in both cases so it may be right.

The "issue" with count() that is as optimal as it could be is another matter.

I believe it could do the trick, I'll close this issue, thanks for your help!

**Comment by UnamedRus** [comment]
Actually, i think that issue should be open and fixed.
Because, it's stupid to have disabled ALIAS column, it prevent a lot of people from upgrade.

**Comment by panthony** [comment]
@UnamedRus I won't say no to that :)

Would it make this possible too?

```sql
SELECT url, url_path FROM s3('', Parquet, 'url String, url_path String ALIAS path(url)')
```

The idea would be to make the rest of the query agnostic from what the source is:

- a MergeTree with all the columns
- a query directly to a file on GCS
