### ISSUE TITLE
Flush query cache for new/renamed users

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#58067]
At the moment, we do not flush the cache or discard cache result when user switch roles or when their permission is updated on the fly, as such, the previous cached result (before permission being updated) will be shown until it expires. Not great from a security perspective, so we should change that.

@santrancisco added a note to the docs for now: #58053

**Comment by Algunenano** [comment]
Duplicated by https://github.com/ClickHouse/ClickHouse/issues/58054
