### ISSUE TITLE
`dotProduct` is not optimized for vector Similarity

### ISSUE THREAD

**Issue by javiabellan** [ClickHouse/ClickHouse#58096]
## Background

Vector similarity is very popular right now, and ClickHouse has a few tutorials about this  [Source](https://clickhouse.com/blog/approximate-nearest-neighbour-ann-with-sql-powered-local-sensitive-hashing-lsh-random-projections). Regarding distances between vectors, they mention the most common ones:

- Euclidean distance
- Cosine distance

![Captura de pantalla 2023-12-20 a las 21 01 10](https://github.com/ClickHouse/ClickHouse/assets/31625296/2b361182-490c-417d-a232-fcbd275cce37)

But in my opinion dotProduct is a better replacement for cosineDistance because **is the same but faster**, let me explain...

## cosineDistance == dotProduct of L2 normalized vectors

`dotProduct` has a much cheaper computation than `cosineDistance`. But they produce different things.

![download](https://github.com/ClickHouse/ClickHouse/assets/31625296/4b046243-b4aa-4806-b64a-e86c9b65c217)

However, **the dotProduct of the L2-normalized vectors** is mathematically the same that cosineDistance, but computationally cheaper because only the norm of the query verctor is computed at search time. The following formula illustrate this:

![Captura de pantalla 2023-12-20 a las 21 30 29](https://github.com/ClickHouse/ClickHouse/assets/31625296/eff51b1e-1dca-4887-b458-bbf6c9eca552)

>  L2 normalization is dividing (element-wise) the vector by its L2Norm. This produces the unit vector (vector lenght = 1) pointing to the same direction of the original vector.

## Poor performance of `dotProduct` in clickhouse now

Both `cosineDistance` and `dotProduct` exist in clickhouse. `dotProduct` should be faster, but currently is (~16x) slower .

```sql
WITH cosineDistance(img_emb, <query_emb>) AS score
SELECT id, score, caption
FROM laion
ORDER BY score DESC
LIMIT 3
# 3 rows in set. Elapsed: 0.535 sec. Processed 1.00 million rows, 2.13 GB (1.87 million rows/s., 3.98 GB/s.) Peak memory usage: 164.25 MiB.

WITH dotProduct(img_emb, <query_emb>) AS score
SELECT id, score, caption
FROM laion
ORDER BY score DESC
LIMIT 3
# 3 rows in set. Elapsed: 8.385 sec. Processed 1.00 million rows, 2.13 GB (119.31 thousand rows/s., 254.04 MB/s.) Peak memory usage: 420.67 MiB.
```

## Possible solution

I know projects like [SimSIMD](https://github.com/ashvardanian/SimSIMD) could help with this optimization.

**Comment by canhld94** [comment]
Can you provide a reproducible example, or describe more detail about your test case?
In my testing with array as input, `cosineDistance` is only slightly faster than `dotProduct`. And their underlying implement is almost identical.

**Comment by alexey-milovidov** [comment]
I'm checking with the following script:

```
CREATE TABLE vectors
(
    v Array(Float32)
) ENGINE = Memory;

SET max_block_size = 16;
INSERT INTO vectors SELECT arrayMap(x -> randUniform(0, 1, x), range(1024)) FROM numbers(1e6);

WITH arrayMap(x -> randUniform(0, 1, x), range(1024)) AS target
SELECT count() FROM vectors WHERE NOT ignore(dotProduct(v, target));
```

I see that `cosineDistance` is faster, but only marginally.

**Comment by javiabellan** [comment]
# Reproduce example

## Hardware & Software 
- Machine: Macbook Air M1 cpu (2020)
- Software: Clickhouse from [quick start guide](https://clickhouse.com/docs/en/getting-started/quick-start)
  - ClickHouse client version 23.12.1.711 (official build).
  - Connected to ClickHouse server version 23.12.1.

## Data
1M from laion400M (part: 0)
```bash
wget --tries=100 https://deploy.laion.ai/8f83b608504d46bb81708ec86e912220/embeddings/img_emb/img_emb_0.npy          # download image embedding
wget --tries=100 https://deploy.laion.ai/8f83b608504d46bb81708ec86e912220/embeddings/metadata/metadata_0.parquet    # download metadata
````

## Create table

```sql
CREATE TABLE laion
ENGINE = MergeTree
ORDER BY key
AS
(
  SELECT * EXCEPT (row_num1, row_num2)
  FROM
  (
      SELECT *, rowNumberInAllBlocks() as row_num1
      FROM file('/Users/javi/Desktop/clickhouse/user_files/laion400M/metadata_0.parquet', 'Parquet', 'key UInt32, width UInt32, height UInt32, url String, caption String, NSFW String, similarity Float32')
  ) AS laion_metadata,
  (
      SELECT *, rowNumberInAllBlocks() as row_num2
      FROM file('/Users/javi/Desktop/clickhouse/user_files/laion400M/img_emb_0.npy', 'Npy', 'img_emb Array(Float32)' )
  ) AS laion_img_emb
  WHERE row_num1 = row_num2
)
# 0 rows in set. Elapsed: 25.233 sec. Processed 2.00 million rows, 1.18 GB (79.30 thousand rows/s., 46.74 MB/s.)
# Peak memory usage: 3.41 GiB.

# Chech number of rows
SELECT count(*)
FROM laion
# ┌─count()─┐
# │ 1000448 │
# └─────────┘
```

## Query
```sql
# Manually copy the 1st embedding. (This will be the emb_query)
SELECT img_emb
FROM laion
LIMIT 1


WITH dotProduct(img_emb, [-0.01651,0.0160217,...emb_query...,-0.0291748,-0.0173035]) AS score
SELECT key, score, caption
FROM laion
ORDER BY score DESC
LIMIT 3
FORMAT Vertical
# 3 rows in set. Elapsed: 0.447 sec. Processed 1.00 million rows, 2.13 GB (2.24 million rows/s., 4.77 GB/s.)
# Peak memory usage: 164.05 MiB.

WITH cosineDistance(img_emb, [-0.01651,0.0160217,...emb_query...,-0.0291748,-0.0173035]) AS score
SELECT key, score, caption
FROM laion
ORDER BY score DESC
LIMIT 3
FORMAT Vertical
# 3 rows in set. Elapsed: 8.603 sec. Processed 1.00 million rows, 2.13 GB (116.29 thousand rows/s., 247.61 MB/s.)
# Peak memory usage: 420.01 MiB.
```

**Comment by javiabellan** [comment]
Inspired from SIMDSim project, maybe a SIMD version (AVX2 or AVX512) of dot product can be implemented.

```c
#include <immintrin.h>

// Function to calculate dot product using AVX2 for float vectors
float avx2_dot_product_float(const float* vector1, const float* vector2, const int size)
{
    __m256 sum = _mm256_setzero_ps(); // Initialize the sum to zero (.0, .0, .0, .0, .0, .0, .0, .0)

    // Perform the dot product in increments of 8 floats at a time
    for (int i = 0; i < size; i += 8) {
        __m256 vec1 = _mm256_loadu_ps(vector1+i); // Load 8 floats from vector1 ( also &vector1[i] )
        __m256 vec2 = _mm256_loadu_ps(vector2+i]); // Load 8 floats from vector2 ( also &vector2[i] )
        __m256 product = _mm256_mul_ps(vec1, vec2); // Multiply corresponding floats
        sum = _mm256_add_ps(sum, product); // Accumulate the dot product into sum
    }
    return sum_8_floats(sum);
}


// https://stackoverflow.com/a/13222410
float sum_8_floats(__m256 x) // x = ( x7, x6, x5, x4, x3, x2, x1, x0 )
{
    const __m128 hiQuad = _mm256_extractf128_ps(x, 1);       // hiQuad = ( x7, x6, x5, x4 )
    const __m128 loQuad = _mm256_castps256_ps128(x);         // loQuad = ( x3, x2, x1, x0 )
    const __m128 sumQuad = _mm_add_ps(loQuad, hiQuad);       // sumQuad = ( x3+x7, x2+x6, x1+x5, x0+x4 )
    const __m128 loDual = sumQuad;                           // loDual = ( -, -, x1+x5, x0+x4 )
    const __m128 hiDual = _mm_movehl_ps(sumQuad, sumQuad);   // hiDual = ( -, -, x3+x7, x2+x6 )
    const __m128 sumDual = _mm_add_ps(loDual, hiDual);       // sumDual = ( -, -, x1+x3+x5+x7, x0+x2+x4+x6 )
    const __m128 lo = sumDual;                               // lo = ( -, -, -, x0+x2+x4+x6 )
    const __m128 hi = _mm_shuffle_ps(sumDual, sumDual, 0x1); // hi = ( -, -, -, x1+x3+x5+x7 )
    const __m128 sum = _mm_add_ss(lo, hi);                   // sum = ( -, -, -, x0+x1+x2+x3+x4+x5+x6+x7 )
    return _mm_cvtss_f32(sum);
}
```

**Comment by rschu1ze** [comment]
I implemented vectorization without knowing about this issue. My implementation and the one in SimSIMD is almost the same (which is a good sign, I guess).
