### ISSUE TITLE
Issue with using Custom Functions in SELECT Clause

### ISSUE THREAD

**Issue by joaozandonadatacosmos** [ClickHouse/ClickHouse#58093]
**Describe the unexpected behaviour**

I'm having difficulties using custom functions in a SELECT clause in ClickHouse. The functions were created to perform specific calculations, but when incorporating them into a SELECT query, I encounter the following error: "DB::Exception: Missing columns"

**How to reproduce**

ClickHouse server version 23.10.5.20.
I can reproduce the error on ClickHouse Fiddle: https://fiddle.clickhouse.com/e9ac82ad-f981-4260-aa33-ad8a1c2e057f
OBS: The case below is just an example that I can't pass the data from the SELECT to the function; my final function is different.

```SQL
CREATE TABLE teste (
  uid Int16, 
  `DT_INICIO` Nullable(DateTime64(3)),
  `DT_FIM` Nullable(DateTime64(3))
) ENGINE=Memory;

INSERT INTO teste VALUES (1,'2023-12-19 15:00:00','2023-12-20 15:00:00');

CREATE FUNCTION f_teste AS (dt_inicio, dt_fim) -> (
  SELECT toDateTime(dt_fim) - toDateTime(dt_inicio)
);

SELECT f_teste('2023-12-19 15:00:00', '2023-12-20 15:00:00'); --works

SELECT f_teste(t.DT_INICIO, t.DT_FIM) FROM teste t; -- error
```

**Comment by UnamedRus** [comment]
Having SELECT in function is wrong

```
CREATE FUNCTION f_teste AS (dt_inicio, dt_fim) -> (
  toDateTime(dt_fim) - toDateTime(dt_inicio)
);
```

https://fiddle.clickhouse.com/c0545114-6d8c-49df-9650-7d227e145c84

**Comment by joaozandonadatacosmos** [comment]
But what if, in a function, I need some data that comes from the SELECT source? Is it not possible to use the SELECT inside the function?

**Comment by alexey-milovidov** [comment]
Currently, we don't support non-scalar subqueries in UDF.
Actually, we didn't plan to support them at this moment in time, and if we want - we have to implement the support for correlated queries first.

Although it should show an error straight ahead at the moment of UDF creation.

The current status is "won't fix," or, more optimistically, "hold".
