### ISSUE TITLE
Why the merge result one part has many partitions?

### ISSUE THREAD

**Issue by aispringli** [ClickHouse/ClickHouse#58103]
we have a merge tree table, after some times find the merge result is one part has many  partitions not  one part one partitions.
the table PARTITION BY toYYYYMM(time), the system.parts like this, who can tell me why ?

![image](https://github.com/ClickHouse/ClickHouse/assets/25081167/543b666d-1336-4a9f-a09a-d361f68fe643)

**Comment by justindeguzman** [comment]
A partition can contain multiple parts.

ClickHouse merges the parts in a partition gradually–it does not merge all of them at once. This gradual merging allows efficient operation for continuously inserted data, so the complexity of merges remains n * log(n).

**Comment by aispringli** [comment]
> A partition can contain multiple parts.
> 
> ClickHouse merges the parts in a partition gradually–it does not merge all of them at once. This gradual merging allows efficient operation for continuously inserted data, so the complexity of merges remains n * log(n).

When will the remaining partitions be merged? Will  never merge again, even if manually OPTIMIZE TABLE  xxx  partition 202306
