### ISSUE TITLE
Cluster port parsed incorrectly

### ISSUE THREAD

**Issue by kreuzerkrieg** [ClickHouse/ClickHouse#5810]
Looks like if I run latest CH as server with `-- --tcp_port=XXXX` the cluster instance totally disregards it

```
Cluster::Address::Address(const Poco::Util::AbstractConfiguration & config, const String & config_prefix)
{
    UInt16 clickhouse_port = static_cast<UInt16>(config.getInt("tcp_port", 0));
...
}
```
It will read the value from config file instead of using actual port.

**Comment by alexey-milovidov** [comment]
@kreuzerkrieg `-- --tcp_port=XXXX` is pushed into config and available in runtime through config object.
