### ISSUE TITLE
don't we support empty Arrays in file table function?

### ISSUE THREAD

**Issue by awakeljw** [ClickHouse/ClickHouse#58117]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

I encountered a question as follows: 

DB::Exception: Cannot determine type for column 'group_id_list' by first 1 rows of data, most likely this column contains only Nulls or empty Arrays/Maps. You can specify the type for this column using setting schema_inference_hints. If your data contains complex JSON objects, try enabling one of the settings allow_experimental_object_type/input_format_json_read_objects_as_strings: Cannot extract table structure from JSONEachRow format file. You can specify the structure manually. (ONLY_NULLS_WHILE_READING_SCHEMA)

the real data is "group_id_list: []"
sql is 

`select * from file('/xxx/xx.json', JSONEachRow) settings input_format_json_read_objects_as_strings=1, allow_experimental_object_type=1;`

don't we support empty Arrays in file table function?

**Comment by Algunenano** [comment]
Since all arrays are empty it can't infer its type. Will it be Array(UInt64), Array(String), Array(something_else)? You can provide the schema with the complete type

**Comment by awakeljw** [comment]
> Since all arrays are empty it can't infer its type. Will it be Array(UInt64), Array(String), Array(something_else)? You can provide the schema with the complete type

can we treat '[]' as strings or Array(Strings) as default  When settings input_format_json_read_objects_as_strings=1.
