### ISSUE TITLE
Add ProfileEvent `InitialQuery`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#58127]
**Use case**

Similar to `Query` but only counts initial queries (see `is_initial_query`).

**Comment by Unalian** [comment]
Hi @alexey-milovidov I would like to work on this issue

**Comment by alexey-milovidov** [comment]
@Unalian, This will be very appreciated!

**Comment by ucasfl** [comment]
Closes in https://github.com/ClickHouse/ClickHouse/pull/58195.
