### ISSUE TITLE
ReadOnly replica as a leader.

### ISSUE THREAD

**Issue by karolcienkosz** [ClickHouse/ClickHouse#58124]
Hello.
Is it expected behaviour that when replica from some reason is marked as readonly it still a leader for a shard? I know that multiple leaders are default approach but what about ReadOnly replicas.

```
database:                    stats_s4
table:                       invoicing
engine:                      ReplicatedSummingMergeTree
is_leader:                   1
can_become_leader:           1
is_readonly:                 1
is_session_expired:          0
future_parts:                0
```

Version:23.8.7

**Comment by alexey-milovidov** [comment]
In the recent ClickHouse versions (for the last three years), there is no leader election, and every replica is always a leader.
