### ISSUE TITLE
BACKUP ALL DATABASES

### ISSUE THREAD

**Issue by VladislavePolyakov** [ClickHouse/ClickHouse#58143]
As described in [Docs](https://clickhouse.com/docs/en/operations/backup) from version 23.4 ALL posible for BACKUP

When run command BACKUP ALL DATABASES TO Disk('backups', 'all_dbs.zip') got error:
 
```
Syntax error: failed at position 12 ('DATABASES'):
 
BACKUP ALL DATABASES TO Disk('backups', 'all_dbs.zip')
```

Could some one comment about this functional and how to do backup all databases at once.

**Comment by y-serg** [comment]
I was able to run backup of all databases by omitting the word `DATABASE`. This should work:
```
BACKUP ALL TO Disk('backups', 'all_dbs.zip')
```
it looks like there is an inaccuracy in the documentation.
