### ISSUE TITLE
StorageS3*: client is recreated each time

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#58160]
It happens here 
https://github.com/ClickHouse/ClickHouse/blob/c6fe84d3fe7408c14fe899cdbc8e4eed118fe085/src/Storages/S3Queue/StorageS3Queue.cpp#L382

`static_configuration: 0` no matter is there was `NOSIGN` or not.

The `StorageS3::Configuration:` has
`no_sign_request: 1` when `NOSIGN` or `no_sign_request: 0` otherwise.

`s3_settings.auth_settings` from context has `no_sign_request: null`.

it is clear with `no_sign_request`. It is a bug.
But I do not still understand why `static_configuration` is `0` even when `NOSIGN` is explicitly set

**Comment by kssenii** [comment]
But this issue will be with StorageS3 as well, isn't it?

**Comment by kssenii** [comment]
> But I do not still understand why static_configuration is 0 even when NOSIGN is explicitly set

It should be, but `static_configuration` flag was added before `NOSIGN` feature was implemented, and when it was - the behaviour was not adjusted.

**Comment by CheSema** [comment]
I put label `bug` because this adds latency on each `s3` function and `s3queue` call.
