### ISSUE TITLE
BUILD ERROR----contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:33:9: error: unknown type name '__u_char'

### ISSUE THREAD

**Issue by batispa** [ClickHouse/ClickHouse#58184]
Hi, some fatal ERRORS always occure when I built from source codes. And I tried re-make several time, but no idea to resolve the problem.
Build commands:
cd ClickHouse-23.11.2.11-stable-src/
rm -rf build && mkdir build && cmake -S . -B build && cmake --build build

One of errors like this:
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:33:9: error: unknown type name '__u_char'
typedef __u_char u_char;
        ^
In my system, however,  grep "__u_char" /usr/include/bits/types.h  returns  "typedef unsigned char __u_char; ", that is good.
Source code bug? Plz check the shot below , thanks.
![image](https://github.com/ClickHouse/ClickHouse/assets/154484833/01f53a1b-2af5-4b0b-9af9-b908f6d063cb)

# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.3 (Plow)

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
# uname -a
Linux tip5builder 5.15.0-200.131.27.el9uek.x86_64 #2 SMP Wed Oct 4 22:09:54 PDT 2023 x86_64 x86_64 x86_   64 GNU/Linux

**Cmake version**
# cmake --version
cmake version 3.20.2

**Ninja version**
# ninja --version
1.11.1

**Compiler name and version**
# clang --version
clang version 16.0.6 (Red Hat 16.0.6-1.0.1.el9)
Target: x86_64-redhat-linux-gnu

**Full cmake and/or ninja output**
-- Building sub-tree with OFF compile jobs and 2 linker jobs (system: 1 cores, 7474 MB RAM, 'OFF' means    the native core count).
-- Configuring done
-- Generating done
-- Build files have been written to: /data/tip/ClickHouse-23.11.2.11-stable-src/build
[0/2] Re-checking globbed directories...
[1907/12543] Building CXX object contrib/thrift-cma...rift/lib/cpp/src/thrift/TApplicationException.cpp.o
FAILED: contrib/thrift-cmake/CMakeFiles/_thrift.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o
/usr/bin/ccache /usr/lib64/ccache/clang++ --target=x86_64-linux-gnu --sysroot=/data/tip/ClickHouse-23.11.2.11-stable-src/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DBOOST_TIMER_ENABLE_DEPRECATED=1 -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I../base/glibc-compatibility/memcpy -isystem contrib/thrift-cmake -isystem ../contrib/thrift/lib/cpp/src -isystem ../contrib/llvm-project/libcxx/include -isystem ../contrib/llvm-project/libcxxabi/include -isystem ../contrib/libunwind/include -isystem ../contrib/boringssl/include -isystem ../contrib/boost --gcc-toolchain=/data/tip/ClickHouse-23.11.2.11-stable-src/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/data/tip/ClickHouse-23.11.2.11-stable-src=. -falign-functions=32 -mbranches-within-32B-boundaries  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3 -g  -fno-pie   -D OS_LINUX -nostdinc++ -std=c++2b -MD -MT contrib/thrift-cmake/CMakeFiles/_thrift.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o -MF contrib/thrift-cmake/CMakeFiles/_thrift.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o.d -o contrib/thrift-cmake/CMakeFiles/_thrift.dir/__/thrift/lib/cpp/src/thrift/TApplicationException.cpp.o -c ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.cpp
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.h:23:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:25:
In file included from ../contrib/thrift/lib/cpp/src/thrift/thrift-config.h:23:
/data/tip/ClickHouse-23.11.2.11-stable-src/build/contrib/thrift-cmake/thrift/config.h:1:1: error: cannot use dot operator on a type
../../../thrift/build/cmake/config.h.in
^
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.cpp:20:
In file included from ../contrib/thrift/lib/cpp/src/thrift/TApplicationException.h:23:
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:30:
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:33:9: error: unknown type name '__u_char'
typedef __u_char u_char;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:34:9: error: unknown type name '__u_short'
typedef __u_short u_short;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:35:9: error: unknown type name '__u_int'
typedef __u_int u_int;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:36:9: error: unknown type name '__u_long'
typedef __u_long u_long;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:37:9: error: unknown type name '__quad_t'
typedef __quad_t quad_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:38:9: error: unknown type name '__u_quad_t'
typedef __u_quad_t u_quad_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:39:9: error: unknown type name '__fsid_t'
typedef __fsid_t fsid_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:44:9: error: unknown type name '__loff_t'
typedef __loff_t loff_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:48:9: error: unknown type name '__ino_t'
typedef __ino_t ino_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:55:9: error: unknown type name '__ino64_t'
typedef __ino64_t ino64_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:60:9: error: unknown type name '__dev_t'
typedef __dev_t dev_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:65:9: error: unknown type name '__gid_t'
typedef __gid_t gid_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:70:9: error: unknown type name '__mode_t'
typedef __mode_t mode_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:75:9: error: unknown type name '__nlink_t'
typedef __nlink_t nlink_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:80:9: error: unknown type name '__uid_t'
typedef __uid_t uid_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:98:9: error: unknown type name '__pid_t'
typedef __pid_t pid_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:104:9: error: unknown type name '__id_t'
typedef __id_t id_t;
        ^
/data/tip/ClickHouse-23.11.2.11-stable-src/contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/include/x86_64-linux-gnu/sys/types.h:115:9: error: unknown type name '__daddr_t'
typedef __daddr_t daddr_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by alexey-milovidov** [comment]
You should install Clang from the official source instead of using RedHat's one.
ClickHouse source code should be unmodified.
The build steps should be exactly as here: https://clickhouse.com/docs/en/development/build

**Comment by alexey-milovidov** [comment]
Consult the build logs from our CI: https://s3.amazonaws.com/clickhouse-test-reports/58179/1c26bae241b31952dd2d3e6e01416419fc2f0c81/clickhouse_build_check/report.html

**Comment by batispa** [comment]
> You should install Clang from the official source instead of using RedHat's one. ClickHouse source code should be unmodified. The build steps should be exactly as here: https://clickhouse.com/docs/en/development/build

Oh, fast replies,  thanks.
Yes, I installed Clang by command yum install clang clang-devel.  And I did not modify any source codes.
Compiler must be Clang 17+ ?

**Comment by alexey-milovidov** [comment]
Let's try clang-17. Do not install it from yum (the reason - they can have arbitrary patches in the compiler).
Use the official source https://clang.llvm.org/, or build it from sources.
