### ISSUE TITLE
Error on insert NULL result of nullIf('string', 'string') function to Nullable Enum

### ISSUE THREAD

**Issue by millin** [ClickHouse/ClickHouse#5818]
* ClickHouse server version 19.9.2 revision 54421

**How to reproduce**
```
CREATE TABLE test (n Nullable(Enum8('N'=0, 'Y'=1))) ENGINE=Log;`
INSERT INTO test SELECT nullIf('str', 'str') AS n;
```

**Expected behavior**
NULL value in table

**Error message and/or stacktrace**

> Received exception from server (version 19.9.2):
> Code: 49. DB::Exception: Received from 192.168.50.161:9000. DB::Exception: Unknown element '' for type Enum8('N' = 0, 'Y' = 1): while converting source column n to destination column n.

**Additional**

1. `nullIf` fuction itself works as expected
```
SELECT nullIf('str', 'str')

┌─nullIf('A', 'A')─┐
│ ᴺᵁᴸᴸ             │
└──────────────────┘
```
2. Inserting NULL works also
```
INSERT INTO test SELECT NULL

Ok.
```
3. Insert result of nullIf with int values works as expected
```
INSERT INTO test SELECT nullIf(10, 10)

Ok.
```
4. WIth Nullable(String) column works also
```
CREATE TABLE test2 (n Nullable(String)) ENGINE=Log;

INSERT INTO test2 SELECT nullIf('str', 'str')

Ok.
```

**Comment by millin** [comment]
@abyss7 I think it is easy to fix. Can you check?

**Comment by millin** [comment]
Pls keep

**Comment by alexey-milovidov** [comment]
Minimal illustrating example:
```
SELECT CAST(CAST(NULL AS Nullable(String)) AS Nullable(Enum8('Hello' = 1)))
```
