### ISSUE TITLE
Insert data column count does not match column names on client.insert()

### ISSUE THREAD

**Issue by cosinus90** [ClickHouse/ClickHouse#58199]
**Python 3.10.12**

**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

I have row to insert. And I'd like to have it as a dict in order to avoid columns confuse

```
import clickhouse_connect
client = clickhouse_connect.get_client(**ch_connect)

        print (row)
        print (len(list(row.values())), len(list(row.keys())))
        ret = client.insert(table, list(row.values()), column_names=list(row.keys()))
```
     

Printout:

{'user_token': 'NULL', 'partner_user_id': 'NULL', 'phone': '79600176034', 'web_id': 82, 'agrement_time': 'NULL', 'timezone': 'Europe/Moscow', 'timezone_offset': -3, 'uagent': 'Mozilla/5.0 (Linux; Android 9; SM-J330F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Mobile Safari/537.36', 'ip': '10###6.24', 'click_id': '39977712', 'first_name': 'Анна', 'last_name': 'Ми####а', 'patronymic': 'Але###вна', 'birthdate': datetime.date(1975, 8, 29), 'email': 'gjh####ail.ru', 'passport_series': 'NULL', 'passport_number': 'NULL', 'passport_code_departament': 'NULL', 'passport_date_issue': 'NULL', 'passport_issued_by': 'NULL', 'birthplace': 'NULL', 'region_live': 'Липецкая обл', 'city_live': 'NULL', 'region_live_code': 48, 'city_live_code': '4800000100000', 'status_card_bank': '1', 'solvency': 'NULL', 'registration_city': 'NULL', 'registration_street': 'NULL', 'registration_house': 'NULL', 'registration_frame': 'NULL', 'registration_structure': 'NULL', 'registration_apartment': 'NULL', 'registration_city_code': 'NULL', 'date_added': datetime.datetime(2023, 10, 17, 12, 58, 34), 'date_last_updated': datetime.datetime(2023, 10, 17, 13, 0, 7), 'site_id': 7, 'loan_sum': '35000', 'gender': 'NULL', 'sub1': 'NULL', 'sub2': 'NULL', 'sub3': 'NULL', 'sub4': 'NULL', 'sub5': 'NULL', 'sub6': 'NULL', 'user_id': 4795023, 'source_id': 1}
47 47
Traceback (most recent call last):
  File "/root/sync/dbsync.py", line 76, in <module>
    ret = client.insert(table, list(row.values()), column_names=list(row.keys()))
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_connect/driver/client.py", line 553, in insert
    context.data = data
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_connect/driver/insert.py", line 94, in data
    raise ProgrammingError('Insert data column count does not match column names')
clickhouse_connect.driver.exceptions.ProgrammingError: Insert data column count does not match column names

I printed len of both lists and as you can see they are equal.

Actually I want to insert Null values, not strings, but then there were None instead of 'NULL' I got error
    ret = client.insert(table, list(row.values()), column_names=list(row.keys()))
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_connect/driver/client.py", line 553, in insert
    context.data = data
  File "/usr/local/lib/python3.10/dist-packages/clickhouse_connect/driver/insert.py", line 91, in data
    self.column_count = len(data[0])
TypeError: object of type 'NoneType' has no len()

So my another question is - How to insert NULL values?

**Comment by Lilneo786** [comment]
```
import clickhouse_connect

# Sample row with some values set to None for NULL insertion
row = {
    'user_token': None,
    'partner_user_id': None,
    'phone': '79600176034',
    # ...
}

# Establish a connection to ClickHouse
client = clickhouse_connect.get_client(**ch_connect)

# Convert None values to 'NULL' for insertion
for key, value in row.items():
    if value is None:
        row[key] = 'NULL'

# Insert the row into the ClickHouse table
table = 'your_table_name'
ret = client.insert(table, list(row.values()), column_names=list(row.keys()))
```
In this code, we initially assign None to certain values in the row dictionary to indicate NULL values. Subsequently, prior to inserting the row into the ClickHouse database, we iterate through the dictionary and transform the None values into the string 'NULL' to align with the expected data type in ClickHouse.

By doing so, you will be able to insert NULL values into the database without experiencing the ProgrammingError you mentioned.

**Comment by den-crane** [comment]
wrong place to ask such questions.

Ask it here https://github.com/ClickHouse/clickhouse-connect
