### ISSUE TITLE
LIVE VIEW WITH PERIODIC REFRESH

### ISSUE THREAD

**Issue by VladislavePolyakov** [ClickHouse/ClickHouse#58219]
##### Start condition and rules ######

CH version 23.12
PG version 16
Both running in docker container

DDL

PG:
```
create table t1(id bigint,created_at date);
```
Every query did after 60 sec of sleep

##### case 1 #######
CH:
```
create table default.t1_pg
(
id Integer,
created_at Date
)
ENGINE = PostgreSQL('localhost', 'postgres', 't1', 'postgres', '123', 'public');
```
```
create LIVE VIEW default.t1 WITH PERIODIC REFRESH 30 AS
select * from default.t1_pg;
```

PG: 
```
insert into t1 values (1,now())
```
Sleep 60

Log record request to PG. No auto refresh

###### case2 ######
Create table in CH and create LIVE VIEW on it. 
Expected auto refresh when data inserted to table.

```
CREATE TABLE default.t2_ch
(
    `id` Integer,
    `created_at` Date
)
ENGINE = MergeTree
ORDER BY id
```
```
create LIVE VIEW default.t2 WITH PERIODIC REFRESH 30 AS
select * from default.t2_ch;
```
```
insert into t2_ch values (1,now())
```
```
SELECT *
FROM t2
```
Ok.
1 rows in set. Elapsed: 0.020 sec.

Didnt see in log auto refresh

##### case3 #######
Insert into PG lot of data
Expected auto refresh when data inserted to table.

PG: 
```
insert into t1 select generate_series(1,100000000),now();
```

```
SELECT count()
FROM t1
```
1 row in set. Elapsed: 21.014 sec. Processed 101.00 million rows, 1.41 GB (4.81 million rows/s., 67.29 MB/s.)
```
SELECT count()
FROM t1
```
1 row in set. Elapsed: 0.006 sec. Processed 101.00 million rows, 1.41 GB (17.75 billion rows/s., 248.46 GB/s.)

PG: 
```
insert into t1 select generate_series(1,100000000),now();
```
```
\dt+ t1
                                   List of relations
 Schema | Name | Type  |  Owner   | Persistence | Access method |  Size   | Description 
--------+------+-------+----------+-------------+---------------+---------+-------------
 public | t1   | table | postgres | permanent   | heap          | 8491 MB | 
```

```
SELECT count()
FROM t1
```
1 row in set. Elapsed: 35.367 sec. Processed 201.00 million rows, 2.81 GB (5.68 million rows/s., 79.57 MB/s.)

```
SELECT count()
FROM t1
```
[1]   Killed                  ./clickhouse server

```
SELECT count()
FROM t1
```
1 row in set. Elapsed: 35.367 sec. Processed 201.00 million rows, 2.81 GB (5.68 million rows/s., 79.57 MB/s.)
Peak memory usage: 4.74 GiB.

In log we didnt see automatic update count() for t1_cnt
Got speedup only on second run query in short time, while data in memory as I am suggesting.

##### case 4 ######
Create LIVE VIEW as aggregated count of records
Insert into PG lot of data
Expected auto refresh when data inserted to table.

```
create LIVE VIEW default.t1_cnt WITH PERIODIC REFRESH 30 AS
select count() from default.t1_pg;
```
PG: 
```
insert into t1 select generate_series(1,100),now();
```

```
SELECT *
FROM default.t1_cnt
```
1 row in set. Elapsed: 27.377 sec. 

```
SELECT *
FROM default.t1_cnt
```
1 row in set. Elapsed: 0.009 sec. 

PG: ```insert into t1 select generate_series(1,100),now();```

```
SELECT *
FROM default.t1_cnt
```
1 row in set. Elapsed: 27.349 sec.
2023.12.25 13:45:26.114424 [ 49550 ] {b4b3963d-1491-4ca4-ae48-8dd9a2f2ed52} <Debug> executeQuery: (from 127.0.0.1:52740) select * from default.t1_cnt (stage: Complete)
2023.12.25 13:45:26.115490 [ 49550 ] {b4b3963d-1491-4ca4-ae48-8dd9a2f2ed52} <Trace> ContextAccess (default): Access granted: SELECT(`count()`) ON default.t1_cnt
2023.12.25 13:45:26.116074 [ 49550 ] {b4b3963d-1491-4ca4-ae48-8dd9a2f2ed52} <Trace> StoragePostgreSQL (t1_pg): Query: SELECT "created_at" FROM "public"."t1"
2023.12.25 13:45:26.116321 [ 49550 ] {b4b3963d-1491-4ca4-ae48-8dd9a2f2ed52} <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState

```
SELECT *
FROM default.t1_cnt
```
1 row in set. Elapsed: 0.010 sec.
2023.12.25 13:49:21.888167 [ 49550 ] {2539e0c8-31eb-435b-94db-2e2e49dca68f} <Debug> executeQuery: (from 127.0.0.1:52740) select * from default.t1_cnt (stage: Complete)
2023.12.25 13:49:21.891453 [ 49550 ] {2539e0c8-31eb-435b-94db-2e2e49dca68f} <Trace> ContextAccess (default): Access granted: SELECT(`count()`) ON default.t1_cnt
2023.12.25 13:49:21.891734 [ 49550 ] {2539e0c8-31eb-435b-94db-2e2e49dca68f} <Trace> InterpreterSelectQuery: FetchColumns -> Complete

In log we didnt see automatic update count() for t1_cnt
Got speedup only on second run query in short time, while data in memory as I am suggesting.

#### case 5 ######
Generate log of data in CH table
Create LIVE VIEW wich count function of CH table
Expected auto refresh when data inserted to table.

```
insert into t2_ch SELECT *,now() FROM numbers(10000000)
```

```
select * from t2_cnt
```
1 row in set. Elapsed: 0.018 sec. 
```
┌──count()─┐
│ 11000011 │
└──────────┘
```

Look like fast result, but it gives internals of CH and column storage

#### Question #####

How could I reproduce work of LIVE VEIW WHITH REFRESH ?

PS
Also tried wich JDBC Engine, also didnt work.

**Comment by vzakaznikov** [comment]
Most likely related to https://github.com/ClickHouse/ClickHouse/issues/57644. Try v22.8 or below.
