### ISSUE TITLE
Write speed to NVME disk degrade after some time of active Clickhouse work

### ISSUE THREAD

**Issue by igor-shk** [ClickHouse/ClickHouse#58229]
Hi)
I have a fairly general question, but maybe someone already had similar issue.
I have few servers with 20 nvme micron 7450 pro 15 TB disks on each. On all servers I created raid 0 using mdadm software (ubuntu 22 system). Then I configured an xfs filesystem for this raid and mounted as a working folder for ClickHouse. After a few days, I noticed that ClickHouse began responding to the client with timeouts. I started to test the system and found that it could be because of the disk write speed. I checked with fio disks write speed after booting up the server and I can get ~80 GB per second write speed. But after some time of active ClickHouse work, write speed drops and for example after a day I can get maximum 2-6 GB per second write speed. Remounting filesystem does not change this behavior and neither does fstrim, but if I restart server - I can get again ~80 GB per second write speed for some time. I tried to use different parameters for raid chunk size, different parameters for filesystem (like noatime, discard, sunit, swidth and so on), different parameters for the kernel like dirty pages but non of this helped. Same behavior on all servers(

I'm not sure at what level this problem exists: nvme, mdadm RAID, xfs filesystem (I also tested ext4), kernel, and I'm still investigating this. But maybe someone had experience with the similar problem and have any advise why it could be and how to configure the system correctly (raid, filesystem, kernel parameters)? I understand that I can't get ~80 GB write speed all the time, but why is it so low 2-6, how to stop degrading it and why restart helps for some time? 
I checked the performance recommendations from the ClickHouse and implemented them (I know that ideally I should not have such a big servers, but there should be a lot of small servers, but this is what I have):
https://clickhouse.com/docs/en/operations/tips

Thanks in advance)

**Comment by den-crane** [comment]
Make sure fstrim is enabled.
It's can be configured differently for SystemD and SystemV

```
systemctl status fstrim

grep fstrim /etc/cron*  -R
```

**Comment by den-crane** [comment]
Make sure that you increased logbufs for XFS, mount with options: `logbufs=8,logbsize=256k`

**Comment by nickitat** [comment]
it makes sense to measure disk throughput by an external tool at the time of good and bad perf to see if the problem is in CH

**Comment by igor-shk** [comment]
Fstrim is enabled and also even if I run it manually it does not help. Using different mount options for XFS - also did not help.

I'm almost sure that the problem is not with ClickHouse directly (if I stop it I still can't get high write speed). And I tested write speed with fio.

So I think the main question is how to prepare the server for a such setup. Like what parameters are best to use when creating mdadm raid, what filesystem to use and what parameters are best to use when mounting. Perhaps some kernel parameters or not using some kernel versions.
If I can get high write speed after botting up the server and it degrade over time I think something should be with configuration. It really look like it's something with trim, but I tested fstrim directly, as a service, discard option at mount time. I checked `lsblk --discard ` command - it seems trim works, but it does not help.

**Comment by chhetripradeep** [comment]
I am curious about the issue & I am interested to know more about the RAID type and configuration you used. Some raid has write amplification issues specially those which use parity. Does destroying the raid and creating a fresh new raid, restores the write speed as before.

**Comment by igor-shk** [comment]
After re-creating the raid, the recording speed remained low.
Over the past few weeks we have also tested several other options: lvm raid, btrfs filesystem, zfs filesystem. And according to our results, zfs showed the best results. It has quite stable write/read speeds (but I was not able to achieve maximum speed).
