### ISSUE TITLE
Can I replicate multiple databases from Mysql into one dabase in Clickhouse with MaterializedMySQL?

### ISSUE THREAD

**Issue by jzhao20230918** [ClickHouse/ClickHouse#58222]
hello,

Per the doc:

CREATE DATABASE db1_mysql
ENGINE = MaterializedMySQL(
  'mysql-host.domain.com:3306',
  'db1',
  'clickhouse_user',
  'ClickHouse_123'
);

It looks like the db in clickhouse and mysql is 1:1. How can I replicate more than one dabases in Mysql into one dabase in Clickhouse? Thanks a lot.

**Comment by alexey-milovidov** [comment]
It is not possible.
