### ISSUE TITLE
BACKUP_LOG table

### ISSUE THREAD

**Issue by VladislavePolyakov** [ClickHouse/ClickHouse#58233]
CH version: 23.12.1

As described in [documentation](https://clickhouse.com/docs/en/operations/system-tables/backup_log) history of backup in table sysem.backup_log

But select from this table returned error

```
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table system.backup_log does not exist. Maybe you meant system.backups?. (UNKNOWN_TABLE)
```

Could you explain how to get data from this table?

**Comment by bharatnc** [comment]
Did you add the correct server settings for the backup_log table as shown in the example [here](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#backup_log)?

**Comment by VladislavePolyakov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/a0fccb04989467edf8f8f0665125b079547d0e32/docs/en/operations/server-configuration-parameters/settings.md?plain=1#L2274

Also found settings for backup_log and look like we have to create table backup_log via config.

Am I right?

**Comment by bharatnc** [comment]
> https://github.com/ClickHouse/ClickHouse/blob/a0fccb04989467edf8f8f0665125b079547d0e32/docs/en/operations/server-configuration-parameters/settings.md?plain=1#L2274
> 
> Also found settings for backup_log and look like we have to create table backup_log via config.
> 
> Am I right?

The config creates that table, you should be able to get it to work by following the example [here](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#backup_log).

**Comment by chhetripradeep** [comment]
Any `system.*_log` table  only gets created when there is an insert operation to that table. Hence `backup_log` table only gets created when you trigger a backup which inturn will trigger an insert operation to `backup_log`  table, which will create that table. From https://github.com/ClickHouse/ClickHouse/pull/55081 this table is enabled by default.

**Comment by tavplubix** [comment]
You can also enforce `system.*_log` tables creation with `SYSTEM FLUSH LOGS`
