### ISSUE TITLE
Hidden dangers in `if(a, b, null)`

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#58235]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

Recently, we found that the null values from `if(a, b, null)` may have different values in the nested column. This can cause problems if you use an nested value directly somewhere without being careful enough to handle null values. Usually someone will assume that the nested value of null value is the default value.

`multiIf` doesn't have this problem.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by Algunenano** [comment]
> Recently, we found that the null values from if(a, b, null) may have different values in the nested column.

How are you accessing those values? If it doesn't need to, CH won't modify the underlying value when adding a NULL mask but using it via [`assumeNotNull`](https://clickhouse.com/docs/en/sql-reference/functions/functions-for-nulls#assumenotnull) is undefined (and documented as such).

**Comment by lgbo-ustc** [comment]
Maybe some new functions to access these values

**Comment by Algunenano** [comment]
What do you mean by "access these values"? You have a NULL value which CH will give to you, and `assumeNotNull` will give you whatever was stored as the underlying value without checking the NULL mask.

**Comment by lgbo-ustc** [comment]
For example, I am developing a new `IFunction`.  If the null values have the same nested values, we may could  speed up the calculation process, execute on the nested values direclty. But if the null values could have different nested values, we have to check each value, and introduce branches in a loop.

**Comment by lgbo-ustc** [comment]
And if some don't notice this, will meet  unexpected behavior and it's hard to find the cause source of the problem

**Comment by Algunenano** [comment]
Yes, if the underlying values were always the same there are some corner cases where you could get away with reading them ignoring the NULL mask. OTOH, assuming you can ignore the NULL mask is the same as jumping over the fence that says "Beware of dog" and finding a dog in the other side.

Since there is data stored with the assumption that you won't ignore the NULL mask, and changing this would mean either rewriting all stored data (impossible) or rewriting it in the fly when reading (expensive for performance), this is not going to change. Proposals that overcome those limitations are welcome though.

**Comment by lgbo-ustc** [comment]
I don't mean to change `if` or any other function. It's easy to cause improper use without keeping `beware of dog` in mind.

In `ColumnNullable`, `getBool` and `get64`  have different behavor. `getBool` checks the null mask and return default value, but `get64` dosn't. If we don't check this method carefully, may also think that `get64` will alse return default when the null mask is set.
