### ISSUE TITLE
RELOAD privilege for MaterializedMySQL 

### ISSUE THREAD

**Issue by dsirotkin-finstek** [ClickHouse/ClickHouse#58248]
I want to use MaterializedMySQL engine for my database but face the next issue:
2023.12.27 13:16:55.783596 [ 1933 ] {} <Error> MaterializedMySQLSyncThread: Code: 556. DB::Exception: MySQL SYNC USER ACCESS ERR: mysql sync user needs at least GLOBAL PRIVILEGES:'RELOAD, REPLICATION SLAVE, REPLICATION CLIENT' and SELECT PRIVILEGE on MySQL Database.But the SYNC USER grant query is: GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO `gmi_rms_staging_clickhouse`@`%`; . (SYNC_MYSQL_USER_ACCESS_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c4fd597 in /usr/bin/clickhouse
1. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x00000000071e9eae in /usr/bin/clickhouse
2. DB::MaterializeMetadata::startReplication(mysqlxx::Pool::Entry&, String const&, bool&, std::unordered_map<String, String, std::hash<String>, std::equal_to<String>, std::allocator<std::pair<String const, String>>>&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>&) @ 0x0000000010d83d89 in /usr/bin/clickhouse
3. DB::MaterializedMySQLSyncThread::synchronization() @ 0x0000000010d64c17 in /usr/bin/clickhouse
4. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::MaterializedMySQLSyncThread::startSynchronization()::$_0>(DB::MaterializedMySQLSyncThread::startSynchronization()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000010d71771 in /usr/bin/clickhouse
5. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c5e45d3 in /usr/bin/clickhouse
6. ? @ 0x00007f014db7fac3 in ?
7. ? @ 0x00007f014dc11660 in ?
 (version 23.11.2.11 (official build))

Due to the fact that MySQL server is provided by Oracle Cloud as a service to us, we are not able to grant RELOAD privilege to the user.
Is it possible to use MaterializedMySQL without it? Why is it required to have this permission?
Thanks!

**Comment by alexey-milovidov** [comment]
Most likely not.

**Comment by josemlbq** [comment]
I'm using the latest docker image which is 22.1.3 and get the same error:

`Received exception from server (version 22.1.3):
Code: 501. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create MySQL database, because Code: 115. DB::Exception: Unknown setting materialized_mysql_tables_list: for database MaterializedMySQL. (UNKNOWN_SETTING),. (CANNOT_CREATE_DATABASE)`
