### ISSUE TITLE
parallel joins are giving unexpected results

### ISSUE THREAD

**Issue by chandrsoni** [ClickHouse/ClickHouse#58276]
i am testing clickhouse on 2 replicated nodes with version 23.12.1.1336 and have a distributed table that is sampled by a column hash. my join is getting processed in distributed manner with allow_experimental_parallel_reading_from_replicas = 0 and on a single node with allow_experimental_parallel_reading_from_replicas = 1 or 2

my default setttings are:
max_parallel_replicas = 100
prefer_localhost_replica = 0
distributed_product_mode = 'local'

<img width="1035" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/45240695/38a33ad7-0a23-4e70-b8ba-6b332e9720f9">

tried recreating in fiddle but the test clusters are no longer there https://fiddle.clickhouse.com/c912aeec-1f7b-442f-8ca9-37b08f4c80c8

**Comment by chandrsoni** [comment]
also, joins on distributed tables with allow_experimental_parallel_reading_from_replicas = 1 are taking twice(4 times with parallel join on 2 replicas).

**Comment by den-crane** [comment]
I don't see what is unexpected here.

There is `default` cluster. https://fiddle.clickhouse.com/0966c6b7-950a-48ed-8f17-1c0305793160

Provide better description of the issue.

**Comment by chandrsoni** [comment]
The test clusters for multiple replicas are no longer there in fiddle so i cant reproduce a replicated table feature. Regardless, the main issue of distributed joins taking 4 times the overall time with parallel replicas is still not addressed.
