### ISSUE TITLE
Inconsistent Query Results with Distributed Materialized Views in ClickHouse

### ISSUE THREAD

**Issue by qianjiangchao1992** [ClickHouse/ClickHouse#58280]
-- local table
create table if not exists test.topn_count on cluster perftest_3shards_2replicas
(
    id           String,
    report_date  String,
    company_id   String,
    view_count Int64,
    update_time  DateTime
) engine = MergeTree() PARTITION BY report_date ORDER BY (report_date,id) SETTINGS index_granularity = 8192,storage_policy = 'multiple_disk';
-- local table all
CREATE TABLE  test.topn_count_all on cluster perftest_3shards_2replicas
as   test.topn_count ENGINE = Distributed(perftest_3shards_2replicas, test, topn_count , rand());
-- local table mv
CREATE MATERIALIZED VIEW if not exists test.topn_count _mv
on cluster perftest_3shards_2replicas ENGINE = AggregatingMergeTree()
PARTITION BY report_date
ORDER BY(report_date,id,company_id)
as
select
    id,
    report_date,
    company_id,
    sumState(view_count ) as view_count ,
    maxState(update_time) as update_time
from  test.topn_count
group by report_date,id,company_id;
-- local table mv all
CREATE TABLE test.topn_count_mv_all on cluster perftest_3shards_2replicas
as test.topn_count_mv ENGINE = Distributed(perftest_3shards_2replicas, test, topn_count_mv , rand());
-- query view
CREATE VIEW if not exists test.topn_count_v on cluster perftest_3shards_2replicas AS
select
    id,
    report_date,
    company_id,
    sumMerge(view_count ) as view_count ,
    maxMerge(update_time) as update_time
from test.topn_count_mv_all
group by report_date,id,company_id;

I have a Flink job that reads from Kafka in real-time, performs some business processing, and then writes to the ClickHouse table test.topn_count. But i stop this job,query  test.topn_count_v get different data ,i need help

**Comment by den-crane** [comment]
>MergeTree() 
>ENGINE = AggregatingMergeTree()
>perftest_3shards_2replicas

You have to use Replicated engines ReplicatedAggregatingMergeTreem  ReplicatedMergeTree

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
