### ISSUE TITLE
Can CH make lightweight delete asynchronous in some cases, e.g. S3 remote storage?

### ISSUE THREAD

**Issue by zhangjmruc** [ClickHouse/ClickHouse#58281]
Description:
PR #44718 made lightweight delete always synchronous. The reason is mentioned in comment https://github.com/ClickHouse/ClickHouse/pull/44718#issuecomment-1377138102:

> The purpose of this change is change is to prevent accumulating a big queue of delete mutations and to provide more natural behavior: when the delete command is finished it will mean that the mutation is not just enqueued but is already finished and the deleted rows are not visible to the next query.

In our test case with S3, there are many pure lightweight delete commands committed by multiple sessions. Current behavior causes poor QPS, while async LWD will be better.

The original intention is good. But the cost of one lightweight delete mutation may be high when we use remote storage like S3, where the read of columns in where clause and write of new _row_exists column from S3 are costly than local storage.

In some cases, user can accept the delay delete, they only care about the lightweight delete. Is it possible that CH can allow async lightweight delete? 
@davenger would you mind providing some opinions?

**Comment by zhangjmruc** [comment]
@davenger @tavplubix Would you mind providing some comments on asynchronous lightweight deletion when remote storage is used?

**Comment by tavplubix** [comment]
Since we have `number_of_mutations_to_delay` and `number_of_mutations_to_throw`, it may be okay to allow async LWDs, but I'm not sure

**Comment by zhangjmruc** [comment]
https://github.com/ClickHouse/ClickHouse/pull/62195
