### ISSUE TITLE
internal_replication: why is the worse value default?

### ISSUE THREAD

**Issue by superxor** [ClickHouse/ClickHouse#5829]
https://clickhouse.yandex/docs/en/operations/table_engines/distributed/

> If it is set to 'false' (the default), data is written to all replicas. In essence, this means that the Distributed table replicates data itself. This is worse than using replicated tables, because the consistency of replicas is not checked, and over time they will contain slightly different data.

Why in heaven is such potential disaster making setting the default?

**Comment by alexey-milovidov** [comment]
This default value was introduced before `Replicated` tables started to exist. Now we cannot simply change default value. It's way better to implement autodetect behaviour.

**Comment by blinkov** [comment]
@superxor, do you have any further questions?

**Comment by alexey-milovidov** [comment]
> It's way better to implement autodetect behaviour.

https://clickhouse.tech/docs/ru/whats_new/extended_roadmap/#internal-replication-auto

**Comment by alexey-milovidov** [comment]
See #14178
