### ISSUE TITLE
Clickhouse Keeper invalid four letter command ydld

### ISSUE THREAD

**Issue by eqinox76** [ClickHouse/ClickHouse#58291]
**Describe the issue**
Following the [documentation](https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper#four-letter-word-commands) the four letter command `ydld` should yield the leader position. But the log shows:
```
 2023.12.28 11:51:23.999657 [ 48 ] {} <Warning> KeeperTCPHandler: invalid four letter command ydld
``` 

**Additional context**
We use `clickhouse/clickhouse-server:23.8` as container image

I think its not parsed as its not defined [here](https://github.com/ClickHouse/ClickHouse/blob/master/programs/keeper-client/KeeperClient.h). But i can also not see the definition of `ftfl` which works fine.

**Comment by den-crane** [comment]
it was added into 23.11

v23.11.1.2711-stable.md:* Add 4-letter command for yielding/resigning leadership (https://github.com/ClickHouse/ClickHouse/issues/56352). [#56354](https://github.com/ClickHouse/ClickHouse/pull/56354) ([Pradeep Chhetri](https://github.com/chhetripradeep)).

**Comment by eqinox76** [comment]
Ah yes, many thanks!
