### ISSUE TITLE
system.parts not available for clickhouse local

### ISSUE THREAD

**Issue by tekjar** [ClickHouse/ClickHouse#58312]
Expected system.parts to be available but it disabled for clickhouse local. Why is system.parts not enabled for clickhouse-local?

https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/System/attachSystemTables.cpp#L178-L181

**Comment by lampjian** [comment]
No. You even do not have a server for creating parts. Local mode is just a command tool.

**Comment by lampjian** [comment]
You even do not have a server for creating parts. Local mode is just a command without a running server.

**Comment by UnamedRus** [comment]
You can create table with MergeTree engine in local mode, so having system.parts make sense

**Comment by alexey-milovidov** [comment]
I didn't find a reason. https://github.com/ClickHouse/ClickHouse/pull/58359

**Comment by tekjar** [comment]
Thanks @alexey-milovidov
