### ISSUE TITLE
toDateTime64() improperly parsing integers

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#58313]
https://clickhouse.com/docs/en/sql-reference/data-types/datetime64

> When inserting datetime as an integer, it is treated as an appropriately scaled Unix Timestamp (UTC). 1546300800000 (with precision 3) represents '2019-01-01 00:00:00' UTC. However, as timestamp column has Asia/Istanbul (UTC+3) timezone specified, when outputting as a string the value will be shown as '2019-01-01 03:00:00'. Inserting datetime as a decimal will treat it similarly as an integer, except the value before the decimal point is the Unix Timestamp up to and including the seconds, and after the decimal point will be treated as the precision.

<img width="408" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/17806508/88cea6c2-06df-4b65-913a-90c99bfc2028">

It seems to only behave with the unix timestamp (seconds) integer version, ignoring the precision if not a float. Doing a `toInt64(1546300800000)` does not fix the improper parsing. Changing to `1546300800.000` behaves as expected for the float processing.

**Comment by den-crane** [comment]
by design https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#todatetime64

https://fiddle.clickhouse.com/26dbab02-7e56-4ebc-b024-675c291ce5c5
