### ISSUE TITLE
json data type doesn't work when table with alias

### ISSUE THREAD

**Issue by zengqiyan** [ClickHouse/ClickHouse#58339]
select event_name,event.event_info_obj.vid
from an.user_event_distributed event
where event.appkey = 'GTGN50BF8RRPR8VP5BTN5K5D'
  AND event.event_time_zero between '2023-12-27 00:00:00' and '2023-12-29 23:59:59'
  and event.event_info_obj.vid = '1'
  
it will :

 Code: 47. DB::Exception: There's no column 'event.event_info_obj.vid' in table 'event': While processing event.event_info_obj.vid: While processing SELECT formatDateTime(event.event_time_zero, '%Y-%m-%d') AS group_25016681, event_info_obj.vid AS group_62480884, count(if(event_name = 'showfinish_mediation2sdk', 1, NULL)) AS metric_55839839, sum(if(event_name = 'max_impression_revenue', CAST(event_info_obj.Revenue, 'Float64'), NULL)) AS metric_11571870, countDistinct(if(1 = 1, if(unique_id IN (NULL, 'null', ''), idfv, unique_id), NULL)) AS metric_65666308 FROM an.user_event_distributed AS event INNER JOIN (SELECT appkey, unique_id, argMax(register_time, update_time) AS register_time FROM an.dim_base_user WHERE appkey IN ('GTGN50BF8RRPR8VP5BTN5K5D') GROUP BY appkey, unique_id) AS user ON (event.appkey = user.appkey) AND (event.unique_id = user.unique_id) WHERE ((appkey IN ('GTGN50BF8RRPR8VP5BTN5K5D')) AND ((event_time_zero >= '2023-12-27 00:00:00') AND (event_time_zero <= '2023-12-29 23:59:59')) AND (if(dateDiff('day', register_time, event_time_zero) = 0, true, false) = 1)) AND (event.event_info_obj.vid = '1') GROUP BY group_25016681, group_62480884. (UNKNOWN_IDENTIFIER) (version 23.10.5.20 (official build))
[2023-12-29 15:16:08] , server ClickHouseNode [uri=http://10.127.32.36:8123/default, options={socket_timeout=30000000,session_id=DataGrip_f45b51a3-a62f-4b91-ba7d-2534b361f628}]@1400204904

**Comment by zengqiyan** [comment]
-- auto-generated definition
create table user_event
(
    event_time_zero      DateTime,
    event_info_obj       json
)
    engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
        PARTITION BY toYYYYMM(event_time_zero)
        PRIMARY KEY (appkey, event_name, unique_id, request_id)
        ORDER BY (appkey, event_name, unique_id, request_id, event_time_zero)
        SETTINGS index_granularity = 8192;

**Comment by Algunenano** [comment]
JSON object is an experimental feature that's going to be removed

**Comment by zengqiyan** [comment]
已收到，谢谢

**Comment by zengqiyan** [comment]
Why JSON object is going to be removed ? We need JSON object, This is a very useful feature ==
