### ISSUE TITLE
A disk similar to `s3_plain` that allows directory rename.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#58347]
**Use case**

Store non-replicated MergeTree tables on S3 without any extra metadata other than what's on S3.
Only for simple cases like system tables.

**Describe the solution you'd like**

Let's assume that we only do rename/move operations on directories but never on files.
Let's also forbid ALTERs and mutations for the tables on this disk, so we never do hard link operations.

Let the disk store each directory as a pseudorandom static prefix in S3,
each file in a directory will be stored under its usual name,
and additionally we will have an extra object near every prefix named `prefix.path`

When a directory is renamed, we write new content to this `prefix.path` file.
The logical directory structure is kept in memory and reconstructed at startup by listing all the .path objects.

**Additional context**

Will it work?

**Comment by jkartseva** [comment]
Which metadata storage type (or types) should be compatible with the new disk?
`local` (MetadataStorageFromDisk) ? 
`plain` (MetadataStorageFromPlainObjectStorage) ?

**Comment by jkartseva** [comment]
I'm proceeding with the assumption that the disk should be constructed with the `plain` metadata storage (as it done for the `s3_plain` disk). Also adding transaction commit / rollback support for `plain` metadata storage as it is not implemented yet.
