### ISSUE TITLE
EXPLAIN ESTIMATE does not take LIMIT into account

### ISSUE THREAD

**Issue by Androidown** [ClickHouse/ClickHouse#58340]
I'm using EXPLAIN ESTIMATE in ClickHouse 22.8, but it seems that the result rows are always near the same as the row count of table, but not the query.

Here is a minimal reproducible example:

```shell
$ curl http://*********/ -d 'EXPLAIN ESTIMATE select * from system.query_log'
system  query_log       15      1815205 305

$ curl http://*********/ -d 'EXPLAIN ESTIMATE select * from system.query_log where type=1'
system  query_log       17      1815247 307

$ curl http://*********/ -d 'select count(*) from system.query_log where type=1'
898944
```

Is 'EXPLAIN ESTIMATE' supposed to produce the above result? Or am I using it wrong?

**Comment by Algunenano** [comment]
Estimate returns the amount of rows that CH is going to read. count() returns the number of rows that match the clause.

**Comment by Androidown** [comment]
> Estimate returns the amount of rows that CH is going to read. count() returns the number of rows that match the clause.

Yeah I know that. But if an index is used (or any limit is added), CH should be able to read less rows than a full table scan.
Take following result as example:

```shell
$ curl 'http://*********/' -d  'explain estimate select count() from (select * from system.query_log limit 100) x'
system  query_log       16      1824132 308

$ curl http://*********/' -d  'select count() from (select * from system.query_log limit 100) x'
100
```

Even though I added a hard limit 100 to my query, the result of 'EXPLAIN ESTIMATE' still shows that CH will read all rows of table. Which sounds unreasonable to me.

**Comment by Algunenano** [comment]
You should provide better examples when reporting tickets. Otherwise it's impossible to understand them

**Comment by alexey-milovidov** [comment]
The estimate is just an estimate.
