### ISSUE TITLE
Automatically disable ANSI escape sequences in Pretty formats if the output is not a terminal.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#58363]
**Use case**

Writing `PrettyCompactNoEscapes` is cumbersome.

**Describe the solution you'd like**

Add a setting `output_format_pretty_color` with values 0, 1, 'auto'. The default value will be `auto`.

If it is set to 0, the Pretty formats will not use ANSI escape sequences.
If it is set to 1, the Pretty formats will use ANSI escape sequences, except in cases when it is one of Pretty\*NoEscapes formats - they never use escape sequences.
If it is set to auto, the Pretty formats (except Pretty\*NoEscapes) will use ANSI escape sequences if stdout is a terminal.

**Additional context**

For example, Pretty formats over HTTP protocol with the value of `output_format_pretty_color` set to `auto` will not use escape sequences.

**Comment by Blargian** [comment]
I'd like to work on this if possible. Could someone point me in the direction more or less where to start looking in the code base?

**Comment by alexey-milovidov** [comment]
@Blargian Look at the implementation of Pretty and PrettyNoEscapes formats. Look at Settings.h and its usage. Also, look at the `isatty` function.

**Comment by Blargian** [comment]
### (Notes for self)

**Pretty** and **PrettyNoEscapes** formats are implemented using the Factory pattern - `FormatFactory`. 

In `Client.cpp` we call `registerFormats()` which is found in `registerFormats.cpp`, this function calls for pretty, amongst other formats, these functions: 

```c++
registerOutputFormatPretty(factory);
registerOutputFormatPrettyCompact(factory);
registerOutputFormatPrettySpace(factory);
```
The functions above are found, respectively, in `src/Processors/Formats/Impl/PrettyBlockOutputFormat.cpp`,`src/Processors/Formats/Impl/PrettyCompactBlockOutputFormat.cpp`,`src/Processors/Formats/Impl/PrettySpaceBlockOutputFormat.cpp`

but each of these are just wrappers for a function `registerPrettyFormatWithNoEscapesAndMonoBlock`, in which the name passed to the function varies. Eg) `Pretty`, `PrettySpace` or `PrettyCompact`

`registerPrettyFormatWithNoEscapesAndMonoBlock` is defined in `src/Processors/Formats/Impl/PrettyBlockOutputFormat.h`

```c++
template <class OutputFormat>
void registerPrettyFormatWithNoEscapesAndMonoBlock(FormatFactory & factory, const String & base_name)
{
    auto creator = [&](FormatFactory & fact, const String & name, bool no_escapes, bool mono_block)
    {
        fact.registerOutputFormat(name, [no_escapes, mono_block](
            WriteBuffer & buf,
            const Block & sample,
            const FormatSettings & format_settings)
        {
            if (no_escapes)
            {
                FormatSettings changed_settings = format_settings;
                changed_settings.pretty.color = false;
                return std::make_shared<OutputFormat>(buf, sample, changed_settings, mono_block);
            }
            return std::make_shared<OutputFormat>(buf, sample, format_settings, mono_block);
        });
        if (!mono_block)
            factory.markOutputFormatSupportsParallelFormatting(name);
    };
    creator(factory, base_name, false, false);
    creator(factory, base_name + "NoEscapes", true, false);
    creator(factory, base_name + "MonoBlock", false, true);
    creator(factory, base_name + "NoEscapesMonoBlock", true, true);
}
```
The templated function above makes a number of `creator`s where `creator` is the lambda function: `[&](FormatFactory& fact, const String & name, bool no_escapes, bool mono_block)`... essentially we're making different variations of a Pretty Format here which varies in if there are escapes and if it is a mono block.

For each call of `creator()` such as `creator(factory, base_name,false,false)` or `creator(factory, base_name + "NoEscapes",true,false` etc:

- a lambda function is passed as a parameter to `registerOutputFormat` which is a method on the factory that essentially stores this function in a dictionary with key set to the name `base_name` 
- If this particular `creator` has `mono_block = false` then it supports parallel formatting, calling a method of factory called `markOutputFormatSupportsParallelFormatting(name)`

Looking at the lambda function mentioned above, what it does is:
- check if `no_escapes` is true and if so makes a copy of the format_settings
- returns a shared_pointer of the templated type OutputFormat

The `format_settings` mentioned above is found in `src/Formats/FormatSettings.h` here:

```c++
 struct Pretty
    {
        UInt64 max_rows = 10000;
        UInt64 max_column_pad_width = 250;
        UInt64 max_value_width = 10000;
        bool color = true;

        bool output_format_pretty_row_numbers = false;

        enum class Charset
        {
            UTF8,
            ASCII,
        };

        Charset charset = Charset::UTF8;
    } pretty;
```

**Comment by Blargian** [comment]
@alexey-milovidov Just to check I'm on the right track still. I see there is already a setting called `output_format_pretty_color` in `Core/Settings.h` which is a boolean value that sets `pretty.color` in `FormatSettings.h` (used in the pretty format implementations to turn on or off ANSI escapes). Is the intention to modify this so that it can be set 0,1 or auto or are you wanting an entirely new setting added?

**Comment by alexey-milovidov** [comment]
@Blargian, yes - use this setting, add the `auto` option.

**Comment by Blargian** [comment]
PR #58614 merged for this issue
