### ISSUE TITLE
insert Array(String) field value error

### ISSUE THREAD

**Issue by CharellKing** [ClickHouse/ClickHouse#58403]
1. create a table with an Array(String) field
 CREATE TABLE arrays_test2
(
   arr Array(String)
 ) ENGINE = Memory;

2. insert a row into the table
insert into arrays_test2 values ((['a', 'b']));

3. Code: 62. DB::Exception: Cannot parse expression of type String here: (['a', 'b'])): While executing ValuesBlockInputFormat. (SYNTAX_ERROR)

**Comment by Algunenano** [comment]
> insert into arrays_test2 values ((['a', 'b']));

The extra set of parenthesis makes it a tuple. It should be `insert into arrays_test2 values (['a', 'b'])`
