### ISSUE TITLE
Allow compression level for file-like storage engines and table functions

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#58406]
> (you don't have to strictly follow this form)

**Use case**

Writing to a file but with a custom compression level (e.g. trade-off between speed and size)

**Describe the solution you'd like**

```
INSERT INTO FUNCTION file[hdfs/url](name, path, schema, compression, compression_level) 
```

**Describe alternatives you've considered**

Currently AFAIK there's no way to do this.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by UnamedRus** [comment]
Or do that via setting: `output_format_compression_level`

**Comment by alexey-milovidov** [comment]
+1, let's do it with a setting.

**Comment by canhld94** [comment]
Then I think it also makes sense to add `output_format_compression_zstd_window_log` for zstd long-range mode. @UnamedRus @alexey-milovidov wdyt?

**Comment by alexey-milovidov** [comment]
Good, we can have it...
