### ISSUE TITLE
Usability: use multi-query mode in clickhouse-client by default.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#58436]
**Use case**

It's natural to copy-paste more than a single query in clickhouse-client.

**Describe the solution you'd like**

Make multi-query by default. But there are caveats; see below.

Initially, the multi-query mode was designed only for running tests, not for general usage.

We also have support for arbitrary formats in INSERT queries.
The insert query may specify an arbitrary format - the data will be parsed by a fast streaming parser instead of the SQL parser.
This is very convenient because you can pass the data in TSV, CSV, JSON, etc., instead of VALUES - this is a novel and important invention of ClickHouse.

But for this reason, we cannot easily split the input stream containing something after the INSERT query.

The proposal is to:
1. If an INSERT uses VALUES format, find the end of the query by parsing it with the SQL parser.
2. If an INSERT uses any other format, parse it until an empty line.
3. The multi-query mode will not support data containing empty lines, such as TSV with a single String column with an empty value.

**Comment by lingtaolf** [comment]
Let me have a try !

**Comment by alexey-milovidov** [comment]
@lingtaolf, thank you! This will be amazing.
Just in case the issue requires attention to small details, it can be finicky.

**Comment by alexey-milovidov** [comment]
This task is open.

**Comment by alexey-milovidov** [comment]
This will be amazing! Currently, no one is working on it.
