### ISSUE TITLE
02944_dynamically_change_filesystem_cache_size and 02933_change_cache_setting_without_restart are flaky

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#58474]
Both tests are failing consistently in master and they both seem to be doing something they shouldn't, at all, in the stateless tests. They are a) modifying the config files dynamically and assuming where the config files are (which is ok in CI, not in local environment).

Sample failure: https://s3.amazonaws.com/clickhouse-test-reports/0/eb930efebbb59a17011fb5be993dc0f68294999e/stateless_tests__release__analyzer_.html

Changes like that should be done in integration tests, where the whole environment is controlled.

**Comment by evillique** [comment]
The flakiness of both of these tests was fixed in https://github.com/ClickHouse/ClickHouse/pull/58445, but maybe they may be improved
