### ISSUE TITLE
MergeTree: some parts are broken after successful insertion

### ISSUE THREAD

**Issue by dmitryikh** [ClickHouse/ClickHouse#5847]
**Describe the bug**

Rarely, some blocks, after successful insertions, appeared to be broken (see logs):

**How to reproduce**
* version 19.6.2.11 (official build)

**Expected behavior**
All blocks are replicated and merged OK

**Error message and/or stacktrace**

Here is grep of some lines, related to the problem:
```
2019.06.30 21:29:16.712300 [ 31 ] {} <Error> x.deals (ReplicatedMergeTreePartCheckThread): Part bb98c46de6189682197845022e935af8_3031_3031_0 looks broken. Removing it and queueing a fetch.
2019.06.30 21:29:16.712754 [ 54 ] {} <Error> InterserverIOHTTPHandler: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Assertion violation: std::char_traits<char>::length(rPath.data()) == rPath.size() in file "../contrib/poco/Foundation/src/File.cpp", line 46 (version 19.6.2.11 (official build))
2019.06.30 21:29:16.713703 [ 31 ] {} <Error> x.deals (ReplicatedMergeTreePartCheckThread): void DB::ReplicatedMergeTreePartCheckThread::run(): std::exception. Code: 1001, type: std::bad_cast, e.what() = std::bad_cast, version = 19.6.2.11 (official build)
2019.06.30 21:29:21.713935 [ 22 ] {} <Warning> x.deals (ReplicatedMergeTreePartCheckThread): Checking part bb98c46de6189682197845022e935af8_3031_3031_0


2019.06.30 21:34:19.679034 [ 25 ] {} <Warning> x.deals (StorageReplicatedMergeTree): Part bb98c46de6189682197845022e935af8_3031_3031_0 (that was selected for merge) with age 303 seconds exists locally but not in ZooKeeper. Won't do merge with that part and will check it.
2019.06.30 21:34:19.679099 [ 26 ] {} <Warning> x.deals (ReplicatedMergeTreePartCheckThread): Checking part bb98c46de6189682197845022e935af8_3031_3031_0
2019.06.30 21:34:19.679401 [ 26 ] {} <Error> x.deals (ReplicatedMergeTreePartCheckThread): Unexpected part bb98c46de6189682197845022e935af8_3031_3031_0 in filesystem. Removing.
2019.06.30 21:34:19.679415 [ 26 ] {} <Information> x.deals (Data): Renaming bb98c46de6189682197845022e935af8_3031_3031_0 to unexpected_bb98c46de6189682197845022e935af8_3031_3031_0 and forgiving it.


2019.06.30 22:14:28.205959 [ 28 ] {} <Warning> x.deals (ReplicatedMergeTreePartCheckThread): Checking part bb98c46de6189682197845022e935af8_3031_3031_0
2019.06.30 22:14:28.209214 [ 28 ] {} <Error> x.deals (ReplicatedMergeTreePartCheckThread): No replica has part covering bb98c46de6189682197845022e935af8_3031_3031_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2019.06.30 22:14:28.222811 [ 28 ] {} <Error> x.deals (ReplicatedMergeTreePartCheckThread): Part bb98c46de6189682197845022e935af8_3031_3031_0 is lost forever.
```

**Additional context**
I investigated broken part, it seems, that file checksums.txt (version 4, compressed by lz4) is broken. **After removing checksums.txt, the part is attached successfully**.

Broken checksums.txt lead to the fact that after reading it, one column name is `\00ontract_size` (zero first byte) instead of `contract_size`: (https://github.com/yandex/ClickHouse/blob/master/dbms/src/Storages/MergeTree/MergeTreeDataPartChecksum.cpp#L177). This is why assert fires from `poco::File`: 
```
File::File(const std::string& rPath): FileImpl(rPath)
{
	poco_assert(std::char_traits<char>::length(rPath.data()) == rPath.size());
}
```

Unfortunately I can't reproduce the case of writing bad checksums.txt locally.

**Comment by alexey-milovidov** [comment]
It looks strange, we need to collect as much info as possible about similar cases.
How often does it reproduce, how many servers do you have in fleet and is it poossible to segment servers where it reproduces? Does it relate to specific table properties?

**Comment by dmitryikh** [comment]
Yes, we see this issue only on this particular table, here is DDL:
[clickhouse_create_table.txt](https://github.com/yandex/ClickHouse/files/3354655/clickhouse_create_table.txt)
The table is populated by official  jdbc clickhouse driver from java (HTTP API) ~10 records per minute.

We have 3 nodes for data replication (no shards). So far, there are 4 cases of "broken parts" in 5 days (3 on node1 and 1 on node2).

For two of them I have broken parts in  `detached/unexpected_*` folder. Here is [checksums.broken.txt](https://github.com/yandex/ClickHouse/files/3354690/checksums.broken.txt) (original file) and [checksums.txt](https://github.com/yandex/ClickHouse/files/3354688/checksums.txt)
 (after deleting the original file and let clickhouse to generate new one after manual `..attach part..`)

**Comment by den-crane** [comment]
could be because of Delta
Date   CODEC(Delta, 
UInt32   CODEC(Delta, 
https://github.com/yandex/ClickHouse/issues/5756#issuecomment-506649391

**Comment by alexey-milovidov** [comment]
@den-crane It only relates to (U)Int8 and (U)Int16 data types.

**Comment by den-crane** [comment]
> @den-crane It only relates to (U)Int8 and (U)Int16 data types.

OK. Got it. 
Date CODEC(Delta,

**Comment by alexey-milovidov** [comment]
> Date CODEC(Delta,

Yes, this can be the reason.

**Comment by alexey-milovidov** [comment]
@dmitryikh

Does the issue vanish if you install version 19.11?

**Comment by dmitryikh** [comment]
> @dmitryikh
> 
> Does the issue vanish if you install version 19.11?

We are not going to update the version in production to check this case. But what I plan to do is to remove `CODEC(Delta,...)` from `date` column and check if the fail will be repeating. I will report about results.

By the way, so far I have 7 `broken blocks` and all of them has 10 rows. It seems that number of rows equals to 10 somehow leads to the bug..

**Comment by perez1987** [comment]
We have the same problem. What data do you need?

**Comment by filimonov** [comment]
Old ticket.

Most possible reason mentioned in that comment:
 https://github.com/ClickHouse/ClickHouse/issues/5847#issuecomment-508250600

If if will be reproduced on newer versions - please feel free to open new one.
