### ISSUE TITLE
clickhouse can't startup Cannot mmap 4.00 KiB., errno: 19, strerror: No such device

### ISSUE THREAD

**Issue by beback-code** [ClickHouse/ClickHouse#58473]
After installing ClickHouse for the first time, I encountered the following error upon startup
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/listen.xml'.
Logging trace to /data/clickhouse/log/clickhouse-server.log
Logging errors to /data/clickhouse/log/clickhouse-server.err.log
Code: 173. DB::ErrnoException: MMappedFileDescriptor: Cannot mmap 4.00 KiB., errno: 19, strerror: No such device. (CANNOT_ALLOCATE_MEMORY), Stack trace (when copying this message, always include the lines below):

 (version 21.11.11.1 (official build))

according to this previous user who https://github.com/ClickHouse/ClickHouse/issues/49786, removing clickhouse.debug file (rm -rf /usr/lib/debug/usr/bin/clickhouse.debug)  But the file does not exist.

**Comment by Algunenano** [comment]
(version 21.11.11.1 (official build))

Please upgrade to a supported release.
