### ISSUE TITLE
Use 64bit floats for geoDistance calculation

### ISSUE THREAD

**Issue by dadebue** [ClickHouse/ClickHouse#58476]
**Describe the unexpected behaviour**
- The `geoDistance` function (and the other geographical distance functions) only uses `Float32` values for the calculation
- This doesn't provide a high enough precision for high precision positioning systems (like [RTK GPS](https://en.wikipedia.org/wiki/Real-time_kinematic_positioning)) which are able to determine the position up to ±1cm precision
- When using the `geoDistance` function with close enough positions the result is always 0, which is incorrect

**How to reproduce**
- most recent Clickhouse version
- `SELECT geoDistance(8.623000, 49.355000, 8.6230001, 49.3550001);` returns `0`
- The exact distance is `0.01327m` [(link to online calculation)](https://www.movable-type.co.uk/scripts/latlong.html)
   - Latitude 1: `49.3550001`
   - Latitude 2: `49.3550000`
   - Longitude 1: `8.6230001`
   - Longitude 1: `8.6230000`
- The exact distance can be calculated with Clickhouse too when using the full `haversine` formula manually (returns `0.01327037431348616`):
````
SELECT (2*atan2(sqrt((sin((49.3550001-49.3550000)*pi()/360)*sin((49.3550001-49.3550000)*pi()/360))+(cos(49.3550001*pi()/180)*cos(49.3550000*pi()/180)*sin((8.6230001-8.6230000)*pi()/360)*sin((8.6230001-8.6230000)*pi()/360))),sqrt(1-(sin((49.3550001-49.3550000)*pi()/360)*sin((49.3550001-49.3550000)*pi()/360))+(cos(49.3550001*pi()/180)*cos(49.3550000*pi()/180)*sin((8.6230001-8.6230000)*pi()/360)*sin((8.6230001-8.6230000)*pi()/360)))))*6371000 distance;
````

**Expected behavior**
- The geoDistance function should use `Float64` values for calculation to support high precision position values
- `SELECT geoDistance(8.623000, 49.355000, 8.6230001, 49.3550001);` should return `0.01327`

**Additional context**
- Changes were introduced in #37524
- I'm no c++ expert but I suppose [those lines in src/Functions/greatCircleDistance.cpp](https://github.com/ClickHouse/ClickHouse/blob/6b6f395cc7fd944f345a0ac088a6822ed05bca37/src/Functions/greatCircleDistance.cpp#L283C9-L286C83) need to be changed

**Comment by alexey-milovidov** [comment]
Let's switch to Float64 and check if there will be any noticeable difference in performance.
I thought there would be no difference.

**Comment by dadebue** [comment]
BTW this chart clearly shows the difference between the `geoDistance` and `manual haversine formula`

`![Screenshot_2024-01-04_11-24-16](https://github.com/ClickHouse/ClickHouse/assets/81422785/6e6edb68-e660-4a95-bf57-ab9981dd8948)

**Comment by geetptl** [comment]
I'd like to work on this.

**Comment by alexey-milovidov** [comment]
@geetptl, thank you! This will be very helpful.

**Comment by Uzair-90** [comment]
I'm interested in working on this issue. It aligns well with my skills and interests. I've reviewed the problem, and I believe I can contribute a solution.

**Comment by alexey-milovidov** [comment]
@Uzair-90, @geetptl, I don't know who will propose a working solution first, but I'd appreciate your work!

**Comment by geetptl** [comment]
Unsure how to link this PR here, but here's the link to it:

https://github.com/ClickHouse/ClickHouse/pull/58847

**Comment by Uzair-90** [comment]
@alexey-milovidov Thank you for the opportunity I will give it a try and highly appreciate it.

**Comment by dadebue** [comment]
@alexey-milovidov What do you think about the PR from geetptl #58847?

**Comment by alexey-milovidov** [comment]
@dadebue, it is unfinished - there is performance degradation.

**Comment by alexey-milovidov** [comment]
#61848

**Comment by alexey-milovidov** [comment]
@dadebue, @Uzair-90, @geetptl, I've reimplemented it. As a result, the performance increased instead of being degraded as expected before. Also, I've managed to make it 100% compatible and even allow the user to control the behavior.

**Comment by geetptl** [comment]
@alexey-milovidov It was vacation when I was working on this issue, but student life caught up to me, along with my inexperience in C++. But thank you for your guidance in the now closed PR!

**Comment by alexey-milovidov** [comment]
Thank you, and it is actually your contribution :) I will add you as a co-author.
