### ISSUE TITLE
multiple values of true in view after alter

### ISSUE THREAD

**Issue by djosephsen** [ClickHouse/ClickHouse#58483]
> Please make sure that the version you're using is still supported:

Problem observed on clickhouse 23.8 - 23.12

> You have to provide the following information whenever possible.

**Describe what's wrong**
SummingMergeTree table returns multiple values for boolean `true`; eg:

```
SELECT DISTINCT bool1
FROM view_1m

┌─bool1─┐
│ false │
│ true  │
│ true  │
└───────┘
```

> A clear and concise description of what works not as it is supposed to.

summingMergeTree table returns multiple values of boolean true.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

This issue only reproduces on summingMergeTree tables after being altered to add a boolean. 

**Does it reproduce on recent release?**
yes. 

We tested on 23.8, 23.10, 23.12

**How to reproduce**
```
-- create a base table with a boolean
CREATE table base (
    `string1` String,
    `bool1`   Bool,
    `string2` String,
    `val`     UInt64)
  ENGINE = MergeTree
  PRIMARY KEY (string1, bool1, string2)
  ORDER BY (string1, bool1, string2);

-- create a view-holding table without the bool
CREATE table view_1m (
    `string1` String,
    `string2` String,
    `val`     UInt64)
ENGINE = SummingMergeTree
PRIMARY KEY (string1, string2)
ORDER BY (string1, string2);

-- create the view to populate view_1m, omitting the bool
CREATE MATERIALIZED VIEW view_1m_mv TO view_1m AS
SELECT
    string1,
    string2,
    sum (val) as val
FROM base
GROUP BY string1, string2;

-- insert 1k rows of data 50% duplicated
-- (see shell-script below)

-- check the base table has twice the entries of the view
select count() from base;
select count() from view_1m;

-- extend the view table to add the bool
alter table view_1m ADD COLUMN bool1 Bool AFTER string1;

-- drop the materalized view
drop table view_1m_mv SYNC;

-- re-create the materalized view with the bool
CREATE MATERIALIZED VIEW view_1m_mv TO view_1m AS
SELECT
    string1,
    bool1,
    string2,
    sum (val) as val
FROM base
GROUP BY string1, bool1, string2;

-- insert 1k rows of data 50% duplicated
-- (see shell-script below)

-- observe multiple values of true in the dataset
select distinct(bool1) from view_1m;

```

Shell script for creating test-data: 

```
#!/usr/bin/env bash

STR1=$(echo ${RANDOM} | md5sum | sed -e 's/^\(.\{4\}\).*/\1/')
STR2=$(echo ${RANDOM} | md5sum | sed -e 's/^\(.\{4\}\).*/\1/')
BOOL="false"
B=0
B=$((${RANDOM}%2))
if [ "${B}" -eq 1 ]
then
    BOOL="true"
fi
VAL=${RANDOM}

# return duplicate inserts so summing-mergetree has something to reduce.
echo "INSERT INTO base (*) VALUES ('${STR1}',${BOOL},'${STR2}',${VAL});"
echo "INSERT INTO base (*) VALUES ('${STR1}',${BOOL},'${STR2}',${VAL});"

```

* Which ClickHouse server version to use  
23.12

* Which interface to use, if matters  
n/a

* Non-default settings, if any 
n/a

* `CREATE TABLE` statements for all tables involved
see `steps to reproduce` above

* Sample data for all these tables, use [clickhouse-obfuscator]
see `steps to reproduce` above

* Queries to run that lead to unexpected result
see `steps to reproduce` above

**Expected behavior**

> A clear and concise description of what you expected to happen.

A single value for boolean true, eg..
```
SELECT DISTINCT bool1
FROM view_1m

┌─bool1─┐
│ false │
│ true  │
└───────┘
```

**Comment by UnamedRus** [comment]
Bool is using (U)Int8 underneath. so most likely it get summed (just like other Integers) in SummingMergeTree, which results in distinct rows for DISTINCT operator.

**Comment by djosephsen** [comment]
That would explain it.  Could we use min(bool1) in the select statement of our materialized view instead?

**Comment by UnamedRus** [comment]
> That would explain it. Could we use min(bool1) in the select statement of our materialized view instead?

No, addition happens in SummingMergeTree merges.

You need to use correct aggregate function with SimpleAggregateFunction based data type

**Comment by djosephsen** [comment]
thanks

**Comment by UnamedRus** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/39965
