### ISSUE TITLE
wrong parts number that lead to ‘Too many part（100155）’

### ISSUE THREAD

**Issue by yedelong** [ClickHouse/ClickHouse#58501]
[version 22.5.4.19

logs
com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Too many parts (18446744073709551615) in all partitions in total. This indicates wrong choice of partition key. The threshold can be modified with 'max_parts_in_total' setting in <merge_tree> element in config.xml or with per-table setting.. Stack trace:
0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int) in /usr/bin/clickhouse

DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&, int, bool) in /usr/bin/clickhouse
DB::MergeTreeData::delayInsertOrThrowIfNeeded(Poco::Event*, std::__1::shared_ptr<DB::Context const>) const in /usr/bin/clickhouse
DB::runStep(std::__1::function<void ()>, DB::ThreadStatus*, std::__1::atomic*) in /usr/bin/clickhouse
DB::ExceptionKeepingTransform::work() in /usr/bin/clickhouse
DB::ExecutionThreadContext::executeTask() in /usr/bin/clickhouse
DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic*) in /usr/bin/clickhouse
DB::PipelineExecutor::executeStep(std::__1::atomic*) in /usr/bin/clickhouse
DB::PushingPipelineExecutor::start() in /usr/bin/clickhouse
DB::TCPHandler::processInsertQuery() in /usr/bin/clickhouse
DB::TCPHandler::runImpl() in /usr/bin/clickhouse
DB::TCPHandler::run() in /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start() in /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run() in /usr/bin/clickhouse
Poco::PooledThread::run() in /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse
? in ?
clone in ?](https://github.com/ClickHouse/ClickHouse/issues/53048#issue-1836598096)

May I ask how to solve this problem? My table engine uses ReplicatedReplacingMergetree

**Comment by rkozlo** [comment]
Answer is in this log message `max_parts_in_total` setting. 
Other thing is very obsolete clickhouse version. Release 1.5 year ago and not even lts. 
And you should look which table has so many parts and what partition key there is

**Comment by yedelong** [comment]
> Answer is in this log message `max_parts_in_total` setting. Other thing is very obsolete clickhouse version. Release 1.5 year ago and not even lts. And you should look which table has so many parts and what partition key there is




I set 'max' through prompts_ Parts_ In_ The value of 'total' has no effect, and I have also checked that the number of zones has not reached this quantity

**Comment by yedelong** [comment]
> Answer is in this log message `max_parts_in_total` setting. Other thing is very obsolete clickhouse version. Release 1.5 year ago and not even lts. And you should look which table has so many parts and what partition key there is

I set the value of this property through prompts, but it didn't work and the error still occurred. I also checked that the number of partitions did not reach this quantity

**Comment by rkozlo** [comment]
It may be some bug. Update this old clickhouse server
