### ISSUE TITLE
Clickhouse for monitoring network routers

### ISSUE THREAD

**Issue by balioune** [ClickHouse/ClickHouse#58532]
Hi all,
I would like to use Clickhouse as Grafana data source to monitor my network routers.
I already store netflow data into Clickhouse but I wonder how to write a query to get throughput per router over the time 

You can see below the structure of my table.

BR,

```
CREATE TABLE netflow.flows
(
    `timestamp_start` DateTime,
    `date` ALIAS toDate(timestamp_start),
    `time` DateTime CODEC(DoubleDelta, LZ4),
    `timestamp_end` DateTime,
    `as_src` UInt32,
    `as_dst` UInt32,
    `iface_in` UInt64,
    `iface_out` UInt64,
    `ip_src` IPv4,
    `net_src` IPv4,
    `ip_dst` IPv4,
    `net_dst` IPv4,
    `peer_ip_src` IPv4,
    `port_src` UInt16,
    `port_dst` UInt32,
    `ip_proto` String,
    `packets` UInt64,
    `bytes` UInt64,
    `app` String,
    `router` String,
    `mask_src` UInt32,
    `mask_dst` UInt32
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(time)
ORDER BY timestamp_start
```

```
CREATE TABLE netflow.flows_queue
(
    `timestamp_start` DateTime,
    `date` ALIAS toDate(timestamp_start),
    `time` DateTime CODEC(DoubleDelta, LZ4),
    `timestamp_end` DateTime,
    `as_src` UInt32,
    `as_dst` UInt32,
    `iface_in` UInt64,
    `iface_out` UInt64,
    `ip_src` IPv4,
    `net_src` IPv4,
    `ip_dst` IPv4,
    `net_dst` IPv4,
    `peer_ip_src` IPv4,
    `port_src` UInt16,
    `port_dst` UInt32,
    `ip_proto` String,
    `packets` UInt64,
    `bytes` UInt64,
    `app` String,
    `router` String,
    `mask_src` UInt32,
    `mask_dst` UInt32
)
ENGINE = Kafka
SETTINGS kafka_broker_list = '10.70.172.18:9092', kafka_topic_list = 'enriched_flow', kafka_group_name = 'netflow_consumer_group1', kafka_format = 'JSONEachRow'
```

```
CREATE MATERIALIZED VIEW netflow.flows_view
ENGINE = Memory AS
SELECT *
FROM netflow.flows_queue
SETTINGS stream_like_engine_allow_direct_select = 1
```

**Comment by UnamedRus** [comment]
> CREATE MATERIALIZED VIEW netflow.flows_view
ENGINE = Memory AS

This is wrong.

MV in ClickHouse is basically insert trigger.
You can check presentations from here
https://kb.altinity.com/altinity-kb-schema-design/materialized-views/#materialized-views

There is quite a few ClickHouse based netflow analysis tools exist, you can use them as inspiration for your schema/queries.

https://github.com/akvorado/akvorado
https://github.com/monogon-dev/NetMeta

**Comment by balioune** [comment]
@UnamedRus Thanks for these suggestions.
The correct definition should be  the following ?
```
CREATE MATERIALIZED VIEW netflow.flows_view AS SELECT * FROM  netflow.flows SETTINGS stream_like_engine_allow_direct_select = 1;
```

**Comment by chhetripradeep** [comment]
@balioune Your requirements look a lot like what this does https://github.com/cloudflare/goflow That project is forked and maintained https://github.com/netsampler/goflow2 There is a docker-compose based setup available as part of the project https://github.com/netsampler/goflow2/tree/main/compose/kcg which you can easily bring up to get a look-and-feel.

**Comment by UnamedRus** [comment]
```
CREATE MATERIALIZED VIEW netflow.flows_view TO netflow.flows AS SELECT * FROM netflow.flows_queue;
```

**Comment by balioune** [comment]
Thanks all for your support, it works!

I join the grafana traffic throughput dashboard in the attached picture .

I would like to have a smooth curve to avoid variations, how can I update the query below  to get average throughput every 5 min ?


```
SELECT
    $__timeInterval(timestamp_start) as time,
    (sum(bytes) / $__interval_s) AS Value
FROM netflow.flows_view
WHERE $__timeFilter(timestamp_start)
AND $__conditionalAll((router = ('$router')), $router)
GROUP BY time
ORDER BY time
```

<img width="462" alt="router_throughput" src="https://github.com/ClickHouse/ClickHouse/assets/8656924/26c53e2d-19a9-4d3b-acc9-73547c691d64">

**Comment by balioune** [comment]
solved!
