### ISSUE TITLE
Qualified dynamic column selection does not work

### ISSUE THREAD

**Issue by lpelecq** [ClickHouse/ClickHouse#58551]
Using `COLUMNS()` while specifying a table name or alias does not work :

```sql
CREATE TABLE test_table (
    id UInt64,
    value String
) ENGINE=TinyLog;
-- 0 rows in set. Elapsed: 0.001 sec.

INSERT INTO test_table VALUES (0, 'Value');
-- 1 row in set. Elapsed: 0.010 sec.

SELECT COLUMNS('i'), COLUMNS('v') FROM test_table;
-- ┌─id─┬─value─┐
-- │  0 │ Value │
-- └────┴───────┘
-- 1 row in set. Elapsed: 0.006 sec. 

-- but 
SELECT test_table.COLUMNS('i'), test_table.COLUMNS('v') FROM test_table;
-- Elapsed: 0.008 sec. 
-- 
-- Received exception:
-- Code: 47. DB::Exception: Missing columns: 'test_table' while processing query: 'SELECT test_table.COLUMNS('i'), test_table.COLUMNS('v') FROM test_table', required columns: 'test_table'. (UNKNOWN_IDENTIFIER)
```

This syntax is not explicitly listed in the documentation but the comments in the code of *src/Analyzer/MatcherNode.h* and the tests in *tests/queries/0_stateless/02339_analyzer_matcher_basic.sql* (where I got these example queries from) suggest that both SELECT should give the same result. 

See : https://fiddle.clickhouse.com/66c0c9e8-c2b0-482f-a206-4d75da9c8d95

Tested on version 23.12.1.1368

**Comment by UnamedRus** [comment]
Because, it's only implemented for new analyzer, which is disabled for now.

```
SELECT 'with analyzer'
SELECT test_table.COLUMNS('i'), test_table.COLUMNS('v') FROM test_table SETTINGS allow_experimental_analyzer=1;

with analyzer
0	Value
```

https://fiddle.clickhouse.com/31192895-c63d-42e3-a142-dc6c3cbb43bf

**Comment by lpelecq** [comment]
oh I didn't know this was still experimental, thanks !
