### ISSUE TITLE
Issue with cluster setup

### ISSUE THREAD

**Issue by Slind14** [ClickHouse/ClickHouse#5856]
Hi there,

we are having difficulties getting the cluster setup to work. The cluster does not show up on the system.clusters table.

Preprocessed config: https://gist.github.com/Slind14/d52c0ee891e234d85cab703860fa3baa
Log: https://gist.github.com/Slind14/01bca0974d9dddf3fe5b18abf6335cab

Is there something wrong with the configuration? We are not getting any errors related to this.

**Comment by Slind14** [comment]
looks like the include isn't working

**Comment by filimonov** [comment]
`include` looks for corresponding section in substitutions file ( by default `/etc/metrika.xml`)

**Comment by Slind14** [comment]
hmm, what is the reason behind this? I'm wondering because if I use the same xml key (not the include) it works fine no matter the file name in config.d

**Comment by den-crane** [comment]
xml files in config.d / conf.d / user.d automatically included into config.
Just put your cluster description into any file. 
For example into  conf.d/clusters.xml
Or into several conf.d/clusterX.xml conf.d/clusterY.xml

incl for multipal repetitions of like password https://gist.github.com/den-crane/d6e0f1c7849a0bc44c27eab2de51c911
