### ISSUE TITLE
Ghost parts in node Clickhouse

### ISSUE THREAD

**Issue by lucasenabit** [ClickHouse/ClickHouse#58562]
I have a problem with one of the clickhouse nodes. When I perform a DDL on cluster operation on a given table, a mutation remains pending because it tries to apply the changes to a table that apparently does not exist in certain "Parts". However, this only happens on two nodes in my cluster, as I have a cluster with 4 nodes, 2 shards and 2 replicas. In one pair of nodes it really does not exist and mutations occur, but in the other the part is not found and the operation remains in the queue to be executed.

Creating the table solves the problem, but I need to solve this problem so as not to need the environment to make this adjustment.

**Last week this happened in another table that also needs to be corrected!**

![image (1)](https://github.com/ClickHouse/ClickHouse/assets/108435054/90e2aa36-3d7d-42b7-81d8-afcb9cc314d8)

**Comment by UnamedRus** [comment]
Most likely this partition already removed by ttl.

So you can run

ALTER TABLR XXX DROP PARTITION ID 'XXXXXX'

If there is no parts from this partition in your table

**Comment by lucasenabit** [comment]
Yes, I've done this before. Message that these parts do not exist! But when I make any changes such as updating or adding new fields using on cluster, the problem continues. It seems that there is some metadata in the cluster that triggers the change for these partitions that in this case do not exist on 2 nodes.

**Comment by tavplubix** [comment]
Please also check `system.replication_queue` (maybe this part was not replicated yet for some reason)

**Comment by tavplubix** [comment]
Also, it makes sense to grep the part name in logs

**Comment by lucasenabit** [comment]
This record actually exists in the replication queue. However, it is not eliminated and the following error persists:


Code: 60. DB::Exception: Table bam.transaction_liquidacao2 doesn't exist. (UNKNOWN_TABLE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe2c3055 in /usr/bin/clickhouse
1. ? @ 0x8ac8644 in /usr/bin/clickhouse
2. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x12fbade3 in /usr/bin/clickhouse
3. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x12fc1aaa in /usr/bin/clickhouse
4. DB::JoinedTables::getLeftTableStorage() @ 0x13abadf4 in /usr/bin/clickhouse
5. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x139d7556 in /usr/bin/clickhouse
6. DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::shared_ptr<DB::IAST> const&, std::vector<String, std::allocator<String>> const&) @ 0x13a76462 in /usr/bin/clickhouse
7. DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&) @ 0x13a740d3 in /usr/bin/clickhouse
8. DB::interpretSubquery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const>, std::vector<String, std::allocator<String>> const&, DB::SelectQueryOptions const&) @ 0x13dc1fad in /usr/bin/clickhouse
9. DB::ExpressionAnalyzer::tryMakeSetForIndexFromSubquery(std::shared_ptr<DB::IAST> const&, DB::SelectQueryOptions const&) @ 0x13029b81 in /usr/bin/clickhouse
10. DB::SelectQueryExpressionAnalyzer::makeSetsForIndex(std::shared_ptr<DB::IAST> const&) @ 0x1302a83b in /usr/bin/clickhouse
11. DB::SelectQueryExpressionAnalyzer::makeSetsForIndex(std::shared_ptr<DB::IAST> const&) @ 0x1302a83b in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::getSampleBlockImpl() @ 0x139e6ffa in /usr/bin/clickhouse
13. ? @ 0x139dfa79 in /usr/bin/clickhouse
14. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x139d9f8c in /usr/bin/clickhouse
15. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::Pipe>, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::shared_ptr<DB::PreparedSets>) @ 0x139d6a74 in /usr/bin/clickhouse
16. DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, std::shared_ptr<DB::Context const> const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::SelectQueryOptions const&) @ 0x139dc0a8 in /usr/bin/clickhouse
17. DB::isStorageTouchedByMutations(DB::MergeTreeData&, std::shared_ptr<DB::IMergeTreeDataPart const>, std::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::vector<DB::MutationCommand, std::allocator<DB::MutationCommand>> const&, std::shared_ptr<DB::Context const>) @ 0x13ae4d00 in /usr/bin/clickhouse
18. DB::MutateTask::prepare() @ 0x148c1c1f in /usr/bin/clickhouse
19. DB::MutateTask::execute() @ 0x148c115a in /usr/bin/clickhouse
20. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x1492c86c in /usr/bin/clickhouse
21. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x1492b734 in /usr/bin/clickhouse
22. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x8ab088c in /usr/bin/clickhouse
23. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x8ab050a in /usr/bin/clickhouse
24. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xe396445 in /usr/bin/clickhouse
25. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xe398fb5 in /usr/bin/clickhouse
26. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe392213 in /usr/bin/clickhouse
27. ? @ 0xe397e81 in /usr/bin/clickhouse
28. ? @ 0x7f3271505609 in ?
29. __clone @ 0x7f327142a133 in ?
 (version 23.3.13.7.altinitystable (altinity build))


but this table transaction_liquidacao_ori2, but the problem is the transaction_liquidacao_ori table. transaction_liquidacao_ori2 does not exist in the environment

**Comment by tavplubix** [comment]
> This record actually exists in the replication queue

That's why you see this part in system.mutations. It's not a ghost, it's a real part that has to be mutated, but cannot due to the error above

Let me guess: The entry type is `MUTATE_PART`, and there was a mutation with a subquery from another table (`transaction_liquidacao_ori2`), and that table was dropped before the mutation finished, right? The mutations with subquery from the dropped table will never finish, you have to kill it.

See https://clickhouse.com/docs/en/sql-reference/statements/kill#kill-mutation

> version 23.3.13.7.altinitystable (altinity build)

We do not support custom builds. Please use an official build from https://packages.clickhouse.com, see https://clickhouse.com/docs/en/install#available-installation-options

**Comment by lucasenabit** [comment]
The problem is that even killing the mutation, any change I make to the transaction_liquidacao_ori table returns the same error saying that this part does not exist! However, one table has nothing to do with the other, including this ori_2 does not exist, but whenever I run an update on cluster or add a column to the transaction_liquidacao_ori table, this same problem happens again. It's been like this since 2023-11-03


<img width="1457" alt="Screenshot 2024-01-08 at 19 34 13" src="https://github.com/ClickHouse/ClickHouse/assets/108435054/40d58e64-6c8b-47f9-8eb2-a08fd8456af3">

<img width="1474" alt="Screenshot 2024-01-08 at 19 35 06" src="https://github.com/ClickHouse/ClickHouse/assets/108435054/10b3073e-e486-4547-b2a1-5bb59179df05">
