### ISSUE TITLE
Memory statistics are incorrect. As a result, memory application fails.

### ISSUE THREAD

**Issue by 2585888388** [ClickHouse/ClickHouse#58605]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).
clickhouse 23.8.2.7 
> You have to provide the following information whenever possible.

When the time changes or the system time is changed, memory statistics are incorrect. As a result, memory application fails.

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

v23.8.2.7-lts | 2023-09-04

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
NA
> A clear and concise description of what you expected to happen.

Before and after the system time is changed, check the MemoryTracking. field in the system table system.metrics. It is found that the memory allocation task in the system fails.

> If applicable, add screenshots to help explain your problem.

![image](https://github.com/ClickHouse/ClickHouse/assets/56569335/41ee0d1f-6a72-47fd-82f1-390814eaa46a)

> Add any other context about the problem here.

**Comment by alexey-milovidov** [comment]
This could be fixed by upgrading to the latest release.
