### ISSUE TITLE
When a large number of SQL statements are queried, the memory usage keeps increasing. As a result, the container OOM occurs.

### ISSUE THREAD

**Issue by 2585888388** [ClickHouse/ClickHouse#58606]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).
clickhouse 23.8.2.7	

> You have to provide the following information whenever possible.

When a large number of SQL statements are queried, the memory usage keeps increasing. As a result, the container OOM occurs.

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

v23.8.2.7-lts | 2023-09-04

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
NA

> A clear and concise description of what you expected to happen.
When a large number of SQL statements are used for query and a large number of LEFT JOIN and INNER JOIN are used for combined query, the memory usage increases rapidly until the container reaches the OOM state.

> If applicable, add screenshots to help explain your problem.

> Add any other context about the problem here.

**Comment by Algunenano** [comment]
What are the reproduction steps?

**Comment by Algunenano** [comment]
No repro. No details
