### ISSUE TITLE
support image search function

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/ClickHouse#5861]
ref https://github.com/postgrespro/imgsmlr

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexey-milovidov** [comment]
We have another experimental task that will be implemented before:
- semi-duplicate text search with locality sensitive hashing (simhash/minhash).

PS. No one is going to store images in ClickHouse, but storage of short fingerprints along with image metadata is considered Ok.

**Comment by cmdares** [comment]
You're right image binary external save，vector internal save。

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
