### ISSUE TITLE
Add support for nice single quotes in Lexer

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#58634]
**Use case**

A user on Mac first writes a query using a text editor for documents, then copy-pastes it to `clickhouse-client`, and the query looks like this:

```
SELECT ‘Hello, world’
```

**Describe the solution you'd like**

Make it work.

**Comment by chrisxu333** [comment]
Hello @alexey-milovidov , can I work on this?

**Comment by alexey-milovidov** [comment]
@chrisxu333, thank you! This will be very appreciated!

**Comment by alexey-milovidov** [comment]
`“identifier”` for identifiers as well.
