### ISSUE TITLE
Not-ready Set is passed as the second argument for function 'in' error in subquery

### ISSUE THREAD

**Issue by AviSarmani** [ClickHouse/ClickHouse#58641]
We get the following error with subqueries
SQL Error [49] [07000]: Code: 49. DB::Exception: Not-ready Set is passed as the second argument for function 'in': while executing 'FUNCTION in(name :: 0, _subquery18 :: 1) -> in(name, _subquery18) UInt8 : 2'. (LOGICAL_ERROR) (version 23.12.2.59 (official build))
, server ClickHouseNode [uri=***********, options={sslmode=STRICT,use_server_time_zone=false,sslkey=*,sslcert=,use_time_zone=false,sslrootcert=}]

Reproduces on the latest version ( 23.12.2.59 ) :
```
CREATE TABLE test_not_ready_bug
(
    `table_name` String,
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192
```
```
SELECT *
FROM system.tables WHERE 
name IN (
SELECT
	table_name
FROM
	test_not_ready_bug )
```
Doesn't happen in 23.7.1.2470 if that helps.

Thanks in advance!

**Comment by Shlomixg** [comment]
Same error here

**Comment by vdimir** [comment]
Probably the same as https://github.com/ClickHouse/ClickHouse/issues/52991
