### ISSUE TITLE
How Do You Perform Efficient AI Model Inference on GPUs within ClickHouse?

### ISSUE THREAD

**Issue by onefanwu** [ClickHouse/ClickHouse#58646]
Hello ClickHouse community,

I'm exploring ways to perform efficient AI model inference within ClickHouse, specifically for tasks like text summarization using models like BART. My goal is to apply these models to document data stored in the database and leverage GPUs for the inference to take advantage of their processing power.

Right now, it seems that my only option is to use Python UDFs (User-Defined Functions) to implement the inference logic, but I'm curious if there are more direct or efficient methods available. I'm looking for any insights or experiences you might have with running AI models, particularly on GPUs, directly within ClickHouse.

Has anyone successfully integrated GPU-based inference within ClickHouse? If so, could you share your approach or any tips on how to set this up? Are there any best practices or tools that facilitate this process?

Any advice or pointers to relevant resources would be greatly appreciated!

Thank you in advance!

**Comment by Wachynaky** [comment]
Hi, it might not be exactly what you're looking for, but [this describes how to implement a GPT2 in SQL](https://explainextended.com/2023/12/31/happy-new-year-15/) (and [Github repository](https://github.com/quassnoi/explain-extended-2024?tab=readme-ov-file)). You just need to download the GPT-2 parameters.

**Comment by zhanglistar** [comment]
That's not Clickhouse good at. You should try other plan.

**Comment by alexey-milovidov** [comment]
Please disregard two answers above.

Using Python UDFs is the right approach.
It will be as fast as the inference works on PyTorch or a similar library that you'll use.
