### ISSUE TITLE
huge node to node traffic

### ISSUE THREAD

**Issue by nathanatimu** [ClickHouse/ClickHouse#58651]
we have a HA clickhouse cluster running in AWS. the design looks like this:

3 x clickhouse server
3 x clickhouse keeper
1 x EFS

Our data set at the moment is very small (1.2 Gb) However we are observing that node to node traffic is huge, where each node has 30 - 40 mb ingress and 60 - 80 egress traffic.

This node to node traffic has us worries as it seems to be not on par with the small dataset we have at the moment and makes us wonder if our implementation is correct or not. 

Is there some kind of relation between the data in clickhouse in the traffic generated by clickhouse in a cluster setup.

at the moment we are assuming an issue, but we are not 100% sure about this.
Would love to get fead back on this.

edit: we disabled logging in clickhouse sometime back, as it would write to the EFS constantly.

**Comment by zhanglistar** [comment]
What's SQL? Maybe you are using join.

**Comment by nathanatimu** [comment]
> What's SQL? Maybe you are using join.

thanks for the reply, we are not using joins, subquery's we do use.

**Comment by nathanatimu** [comment]
so we determind that around 80 to 90 % of the traffic is caused by insert query's. Here is the kicker, there only 2000 inserts per hour....
we are using as our engine in Clickhouse:
ReplicatedMergeTree &
ReplicatedCollapsingMergeTree
does this seem correct compared to our setup?

**Comment by nathanatimu** [comment]
we changed the EFS to EBS for now, and we see sharp decrease in traffic as expected. how ever out initial assesment wasn't correct. the traffic seems to not be node to node, but node to EFS. We found this during testing
