### ISSUE TITLE
Clickhouse Cloud: Connect with PDO " SQLSTATE[HY000] [2006] MySQL server has gone away"

### ISSUE THREAD

**Issue by jul3z** [ClickHouse/ClickHouse#58671]
> Please make sure that the version you're using is still supported
Fresh Clickhouse Cloud: v23.9

Connect with PDO " SQLSTATE[HY000] [2006] MySQL server has gone away"

**Does it reproduce on recent release?**
Yes

**How to reproduce**

Create a Clickhouse Cloud Server: v23.9

`$pdo = new PDO("mysql:host=id.eu-central-1.aws.clickhouse.cloud;port=3306;dbname=default", 'mysql123', 'password');
$unbufferedResult = $pdo->query("SELECT 1");`

PDOException: " SQLSTATE[HY000] [2006] MySQL server has gone away"

**Expected behavior**

Should return 1

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

It works in the Terminal with: `mysql -h id.eu-central-1.aws.clickhouse.cloud -u mysql123 -P 3306 --password`

**Comment by slvrtrn** [comment]
@jul3z, this works:

```php
<?php
  $options = array(
    PDO::MYSQL_ATTR_SSL_CA => './isrgrootx1.pem',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false
  );
  $dsn = 'mysql:host=...aws.clickhouse.cloud;port=3306;dbname=default';
  $username = 'mysql4...';
  $password = '...';
  $pdo = new PDO($dsn, $username, $password, $options); 
  foreach ($pdo->query("SELECT number FROM system.numbers LIMIT 5") as $row) {
    var_dump($row['number']);
  }
?>
```

You'll need to download the [Let's Encrypt root certificate](https://letsencrypt.org/certs/isrgrootx1.pem).
