### ISSUE TITLE
Resutls of `SELECT sleep(n)` should not be cached by Query Cache

### ISSUE THREAD

**Issue by vitaliyf** [ClickHouse/ClickHouse#58699]
**Describe the unexpected behaviour**

Results of `SELECT sleep(1) SETTINGS use_query_cache = 1` should not be cached by query cache.

**How to reproduce**

```
SELECT sleep(1) SETTINGS use_query_cache = 1;

┌─sleep(1)─┐
│        0 │
└──────────┘

1 row in set. Elapsed: 1.001 sec.
```

immediately followed by:

```
SELECT sleep(1) SETTINGS use_query_cache = 1;

┌─sleep(1)─┐
│        0 │
└──────────┘

1 row in set. Elapsed: 0.001 sec.
```

* Which ClickHouse server version to use
23.8.8

**Expected behavior**

Query Cache already knows how to ignore some "non-deterministic" functions as described here: https://clickhouse.com/docs/en/operations/query-cache#related-content

I think `sleep()` (and perhaps `sleepEachRow()`) should be marked with `bool isDeterministic() const override { return false; }`. Not sure if they also should have isDeterministicInScopeOfQuery.

**Comment by rschu1ze** [comment]
`sleep()` and its variants are deterministic, the same input produces the same output. Don't really want to add a special hack just for `sleep()`.

The function is rarely used in practice though, so perhaps this is an edge case.

**Comment by Slach** [comment]
just use `SETTINGS use_query_cache = 0;`
