### ISSUE TITLE
Install/upgrade clickhouse-keeper

### ISSUE THREAD

**Issue by boldakovds** [ClickHouse/ClickHouse#58709]
Hello!
1) What the best practice to install clickhouse-keeper - on the same hosts as DB or on separate hosts? What i need to pay attention if i will install cickhouse-keeper on the same host as DB?
2) What plan for upgrade clickhouse-keeper: on the same DB hosts and on separate hosts? 
3) Can i make downgrade clickhouse-keeper safetly?

**Comment by antonio2368** [comment]
> What the best practice to install clickhouse-keeper - on the same hosts as DB or on separate hosts? What i need to pay attention if i will install cickhouse-keeper on the same host as DB?

It's okay to install clickhouse-keeper on same host, just be careful that configuration from server and Keeper don't get mixed up and that each of them use correct data folders/configs.

> What plan for upgrade clickhouse-keeper: on the same DB hosts and on separate hosts?

Not sure I understand this question. All Keeper version were backwards compatible until now. If there will be a change in the future it will be emphasized.

> Can i make downgrade clickhouse-keeper safely?

Keeper tries to keep compatibility in such cases so downgrades should be okay, maybe if the version difference is too large there could be some problems.

**Comment by boldakovds** [comment]
About upgrade clickhouse-keeper:
Is it ok if cluster of clickhouse-keeper will be work on different versions (in upgrade process)? 
Plan for upgrade the same as DB - turn off 1 instance, upgrade to new version, turn on (wait until everything started on logs) and the same for next instances of cluster?

**Comment by antonio2368** [comment]
@boldakovds yes, absolutely
