### ISSUE TITLE
According to the 'time' field, the results obtained from an 'order by' descending query are not the most recent. The time format is 2024-01-09 15:53:46.

### ISSUE THREAD

**Issue by dxygit1** [ClickHouse/ClickHouse#58713]
According to the 'time' field, the results obtained from an 'order by' descending query are not the most recent. The time format is 2024-01-09 15:53:46.
According to the timestamp format field, it is normal.

clickhouse version:   22.8.16.32

**Comment by dxygit1** [comment]
For example: When querying based on a timestamp, data at 7:00 is retrievable, but using the format 2024-01-09 15:53:46, only data at 6:55 can be queried.

**Comment by UnamedRus** [comment]
You need to make an example on https://fiddle.clickhouse.com/

**Comment by Algunenano** [comment]
Please provide reproduction steps and verify a supported version
