### ISSUE TITLE
Initial inserts to tables with materialized views are not persisted

### ISSUE THREAD

**Issue by imny94** [ClickHouse/ClickHouse#58736]
**Describe what's wrong**

When using the official clickhouse docker image and providing a `/docker-entrypoint-initdb.d` file to initialise the required table, the first time that a table is queried using the official golang library, the query returns no results. Subsequent queries return the correct results.

This is reproduced [here](https://github.com/imny94/clickhouse-docker-mv-bug-repro)

**How to reproduce**

* Refer to sample repo for reproduction steps

**Expected behavior**

Queries after initial insert to table should include data from previous insert

**Comment by Algunenano** [comment]
Can you please simplify the reproducer to simple SQL or https://fiddle.clickhouse.com/?

**Comment by UnamedRus** [comment]
BTW, `/docker-entrypoint-initdb.d` does mean, that your node will start twice, one for running initdb, second for actually serving queries.

So you slowdown your node startup in 2 times, it can be problematic for big databases (ie 5min -> 10min)
