### ISSUE TITLE
MaterializedMySQL - remove partitioning from a table

### ISSUE THREAD

**Issue by dsirotkin-finstek** [ClickHouse/ClickHouse#58742]
I'm using MaterializedMySQL to grab the data from my server and analyze it.
When I query "SHOW CREATE TABLE my_table_name" I see that the table is created with inefficient PARTITION BY expression.
However, I don't need partitioning at all for my table.
I would like to override the table as it is described here:
https://clickhouse.com/docs/en/engines/database-engines/materialized-mysql#table-overrides
But it's not clear for me how to remove partitioning from the table using table overrides.
Could you please advise how I can achieve that? Thanks!

**Comment by alexey-milovidov** [comment]
We don't support MaterializedMySQL.
