### ISSUE TITLE
sumMapFiltered aggregate function wrong result starting from 23.11

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#58741]
```sql
SELECT sumMapFiltered([6.7])([x],[y]) FROM values('x Float64, y Float64', (0, 1), (1, 2.3), (nan,inf), (6.7,3), (4,4), (5, 1))
```

Before 23.11:
``` 
([6.7],[3])
````

Starting from 23.11:
```
 ([nan],[inf])
````

**Comment by Algunenano** [comment]
This was introduced in https://github.com/ClickHouse/ClickHouse/pull/56350.

std::set<Field> does not work

**Comment by Algunenano** [comment]
Correction: `std::set<DB::Field>` does not work as expected because it does not deal with `NaN` correctly.
* 5.0 < NaN: False
* NaN < 5.0 : False
* Conclusion: 5 == 'NaN'

**Comment by davenger** [comment]
@Algunenano do we have the same problem here wit `std::map<Field, ...>` https://github.com/ClickHouse/ClickHouse/pull/56350/files#diff-92770a5665f326e3531a4118ff65c99e9c75524e0fad44060835794ebfce168dR40 ?

**Comment by Algunenano** [comment]
> do we have the same problem here wit std::map<Field, ...>

Nice question. And yes, but in this case the bug was already present before the the refactor (since forever, or at least since 20.8 which is the oldest I have around):

```
SELECT sumMap([x], [y])
FROM values('x Float64, y Float64', (4, 1), (1, 2.3), (nan, inf), (6.7, 3), (4, 4), (5, 1))

Query id: 34f31c01-cd59-45d1-a7d0-a8cc93e70f8e

┌─sumMap(array(x), array(y))─┐
│ ([1,4,5,6.7],[inf,5,1,3])  │
└────────────────────────────┘

1 row in set. Elapsed: 0.002 sec.
```

I have zero trust in this function TBH
