### ISSUE TITLE
Fixes to ClickBench task

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#58744]
You have added the timeout in an inappropriate place.

It should be in https://github.com/ClickHouse/ClickHouse/pull/57712/files#diff-50ce4c0891f4c52bb0a90b064b447f582d3187727c178c0fa39cdef8c8932abcR176

Then we can use [process.timeout_exceeded](https://github.com/ClickHouse/ClickHouse/blob/1d70c9464e6e23dde1e5a9370bb9ae1d57bec9c9/tests/ci/tee_popen.py#L38C3-L38C3) to report the proper [TestResult.create_check_timeout_expired](https://github.com/ClickHouse/ClickHouse/blob/1d70c9464e6e23dde1e5a9370bb9ae1d57bec9c9/tests/ci/report.py#L253).

Now it's hidden inside of the docker, and will be hidden forever.

_Originally posted by @Felixoid in https://github.com/ClickHouse/ClickHouse/issues/57712#issuecomment-1854549146_

**Comment by Felixoid** [comment]
@alexey-milovidov I hoped you'll consider fixing it

**Comment by alexey-milovidov** [comment]
No issues since December.
