### ISSUE TITLE
HTTP chunked transfer encoding semantics 

### ISSUE THREAD

**Issue by ivan-tkatchev** [ClickHouse/ClickHouse#58784]
Does Clickhouse support chunked transfer encoding for inserts with the HTTP interface?

Documentation doesn't give a clear answer.

To implement batching on the client side, Clickhouse should collect all chunks from one HTTP session and insert them as one part, but only if the client acknowledges the transfer correctly by sending a zero-size chunk.

(Unfinished transfer sessions should be ignored and not inserted.)

Can you confirm that this works as expected?

**Comment by alexey-milovidov** [comment]
> Does Clickhouse support chunked transfer encoding for inserts with the HTTP interface?

Yes.

> To implement batching on the client side, Clickhouse should collect all chunks from one HTTP session and insert them as one part, but only if the client acknowledges the transfer correctly by sending a zero-size chunk.

ClickHouse server will parse and accumulate the data up to `max_insert_block_size` rows and do the insertion of every batch in an atomic way. If the amount of data is less than the `max_insert_block_size` it will be a single atomic insertion after the stream of data is consumed.
