### ISSUE TITLE
Improvements for `web` disks

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#58793]
### If the data does not exist, the disk silently works as empty.

We should check the existence of the `.index` file in the root directory and throw an exception if there is no such file.

### It loads all the metadata eagerly.

Instead, it should load the metadata lazily, when a path is requested.
It should check the topmost ascending path that was loaded, and then either load the child paths or find out that the path does not exist.

**Comment by kssenii** [comment]
> We should check the existence of the .index file in the root directory and throw an exception if there is no such file.

It is not necessary to have index file at root directory, only on table level, e.g. `https://clickhouse-public-datasets.s3.amazonaws.com/web/store/uuid_prefix/uuid/.index` and in all its child directories recursively.
So there is no way to handle disk web with empty data.

**Comment by kssenii** [comment]
> It loads all the metadata eagerly.

It does not actually load ALL metadata. It loads only metadata for currently requested path + all subdirectories of this requested path, but on server startup we do not iterate from root, we iterate from table level, e.g. `store/uuid_prefix/uuid/` is the first iterated level and the first requested file will lead to loading of `store/uuid_prefix/uuid/.index`. So it eagerly loads only all data parts for a single table. But on server startup clickhouse anyway iterates over all data parts of all tables, to load primary index at least, so we will anyway load almost everything, so I do not think this improvement will be noticeable. Though here it is https://github.com/ClickHouse/ClickHouse/pull/58874.
