### ISSUE TITLE
Is there a setting or a method that the output result of a query is limited only to finalized partitions?

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#58796]
Is there a setting or a method that the output result of a query is limited only to finalized partitions?

like this : 

```sql
select *
from test.agg_table
SETTINGS query_on_finalize_partition=TRUE;
```

Another question is, is there a setting that finalizes only the result of a search instead of finalizing the entire data of a partition?

**Comment by UnamedRus** [comment]
`final` setting, it's basically apply `FINAL` clause for all legitimate tables in query.

It's should work pretty decently, but will work even better in 24.1+ version.

**Comment by alexey-milovidov** [comment]
> setting or a method that the output result of a query is limited only to finalized partitions

To clarify - skip any partitions with more than a single data part. 
No, there is no setting for that.
