### ISSUE TITLE
When  i change clickhuouse-server/config.xml's  tcp_port，the clickhouse docker image started failed 

### ISSUE THREAD

**Issue by fanqinwen** [ClickHouse/ClickHouse#58807]
**Describe the issue**
When I modify the TCP port in the clickhouse server/config.xml of the clickhouse image to 9123, the clickhouse image will report an error DB:: NetException: Connection reused (127.0.0.1:9000). (NETWORK ERROR)

**How i fix this problem**
* Which ClickHouse server version to use
 docker.io/clickhouse/clickhouse-server:23.9.5-alpine
* What i do
I have modified the clickhouseclient=(clickhouse client multi query host "127.0.0.1" - u "$CLICKHOUSE USER" -- password "$CLICKHOUSE PASSWORD") in the entrypoint. sh of the clickhouse image to
TCP_ PORT="$(clickhouse extract from configuration -- config file" $CLICKHOUSE-CONFIG "-- key=tcd_port -- try)"
clickhouseclient=(clickhouse client -- multiquery -- host "127.0.0.1" -- port "$TCP_PORT" - u "$CLICKHOUSE.USER" -- password "$CLICKHOUSE.PASSWORD"), this method solves this problem

**Additional context**
Is the 9000 port read by the clickhouse client hard coded into the code? Modifying the configuration does not change the 9000 port number used by the clickhouse client to connect to the client

**Comment by Algunenano** [comment]
> Is the 9000 port read by the clickhouse client hard coded into the code?

Port 9000 is the default port. If your CH instance is running in a different port you need to change it, as you did.

> Modifying the configuration does not change the 9000 port number used by the clickhouse client to connect to the client

Client and server config are different files. You can change the clickhouse client configuration either via command line (as you did), `clickhouse-client.xml` file, `~/.clickhouse-client/config.xml` or `/etc/clickhouse-client/config.xml` (`.yaml"` or `.yml` are also valid).

**Comment by fanqinwen** [comment]
However, in fact, even after I changed the 9000 port in the~/. clickhouse client/config.xml and/etc/clickhouse client/config.xml files to 9123, the code logic in the entrypoint.sh file will still attempt to connect to the 9000 port
