### ISSUE TITLE
MySQL compatibility: support CAST AS SIGNED

### ISSUE THREAD

**Issue by slvrtrn** [ClickHouse/ClickHouse#58822]
**Use case**

Certain queries generated by Looker Studio do the following:

```sql
SELECT CAST(DATE_FORMAT(CAST(DATE_FORMAT(time, '%Y-%m-%d %H:%i:%s') AS DATETIME), '%w') AS SIGNED) AS qt_duv6kvlmdd,
       COUNT(1)                                                                                    AS qt_jxd1bulmdd,
       author
FROM commits
GROUP BY qt_duv6kvlmdd, author;
```

This example uses the [commits](https://clickhouse.com/docs/en/getting-started/example-datasets/github) dataset.

As of 23.12, the result is an error:

```
Code: 50. DB::Exception: Received from localhost:9000. 
DB::Exception: Unknown data type family: SIGNED: 
While processing CAST(DATE_FORMAT(CAST(DATE_FORMAT(time, '%Y-%m-%d %H:%i:%s'), 'DATETIME'), '%w'), 'SIGNED') AS qt_duv6kvlmdd. 
(UNKNOWN_TYPE)
```

**Describe the solution you'd like**

No errors; `CAST x AS SIGNED` produces an Int64, `CAST x AS UNSIGNED` produces a UInt64.
See https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast for more details.

**Comment by Algunenano** [comment]
The solution is to add an type aliases. Similar ones exists (like `INTEGER UNSIGNED`

**Comment by slvrtrn** [comment]
@Algunenano, thanks, I will look into it 👍
