### ISSUE TITLE
empty array in system.query_log.used_dictionaries 

### ISSUE THREAD

**Issue by yurylabko** [ClickHouse/ClickHouse#58843]
**Describe what's wrong**

When using the dictGet function in a subquery, the used_dictionaries column in table system.query_log will return an empty array.

**Does it reproduce on recent release?**
Yes

**How to reproduce**

```
create or replace dictionary test (id UInt64, name String)
PRIMARY KEY id
SOURCE(CLICKHOUSE(QUERY 'select number as id, ''#'' || toString(id) as name from numbers(10)'))
LIFETIME(0)
LAYOUT(HASHED);


select number, val
  from(
select number, dictGet('test', 'name', number) as val
  from numbers(10)) t;

SYSTEM FLUSH LOGS;

select used_dictionaries, used_functions, query, type
  from system.query_log

used_dictionaries: []
used_functions:    ['dictGet']
query:             select number, val
  from(
select number, dictGet('test', 'name', number) as val
  from numbers(10)) t
type:              QueryFinish
```
* Which ClickHouse server version to use
   23.12.2.59

**Expected behavior**
    column used_dictionaries returns array of canonical names of dictionaries, which were used during query execution

**Comment by Algunenano** [comment]
Still an issue in master. The dictionary is not reported as accessed in system.query_log
