### ISSUE TITLE
No result while selecting from tables with toYYYYMMDD(DateTime) partition filtered by any timepoint < '1970-01-01 00:00:00' 

### ISSUE THREAD

**Issue by KobeBryant-24** [ClickHouse/ClickHouse#58853]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).
v23.8.2.7-lts

> You have to provide the following information whenever possible.

simply reproduce by:
`create table if not exists foo (time DateTime)  engine = MergeTree() PARTITION BY toYYYYMMDD(time) order by time;`
`insert into foo values (now());`
`select count() from foo;`
`select count() from foo where time > '1969-01-01 00:00:00'; ` -> expected to be 1

![image](https://github.com/ClickHouse/ClickHouse/assets/45556573/1781f516-2e4b-4d02-a365-c41ab29438a9)

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).
https://fiddle.clickhouse.com/f0c3c353-c19a-4bc1-8a23-b1e5e38fffb3

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

With results run in the fiddle, the problem seemed resolved by 23.12, and only exists in versions between 22~23:
23.12
https://fiddle.clickhouse.com/744b1cc0-0c7e-42cb-afd9-8559df14623c
23.11.4.24
https://fiddle.clickhouse.com/a0e21f42-302e-4600-abac-41409dca293b
22
https://fiddle.clickhouse.com/0b5d4ccb-bef0-47d0-a765-84eb5acd26cd
21.12.4.1
https://fiddle.clickhouse.com/493104a8-56cc-49e6-ad7c-1d4c37096225

can someone please help figure out what changes introduced and resolved the problem? tq

p.s.
partition without toYYYYMMDD:
`create table if not exists foo (time DateTime)  engine = MergeTree() PARTITION BY time order by time;`
or query using toDateTime:
`select count() from foo where time > toDateTime('1969-01-01 00:00:00'); ` 
does not reproduce the problem.

**Comment by alexey-milovidov** [comment]
> the problem seemed resolved by 23.12

Ok.

**Comment by KobeBryant-24** [comment]
> > the problem seemed resolved by 23.12
> 
> Ok.

😮uh, will there be any plan for backporting to earlier versions? @alexey-milovidov

**Comment by alexey-milovidov** [comment]
No plans to do a backport - it is risky as it can break customers' queries on the LTS version.
Only security and reliability fixes should be backported.

**Comment by KobeBryant-24** [comment]
> No plans to do a backport - it is risky as it can break customers' queries on the LTS version. Only security and reliability fixes should be backported.
I get it though, can someone kindly point out what changes or commits may cause or solve this problem? As 23.8 or 23.11 is still an LTS version and we are not likely to upgrade, and we do have such scenarios that query with DateTime filter before 1970.
