### ISSUE TITLE
Cannot read Parquet file from archive with max_threads > 1

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#58870]
Example:

```
$ clickhouse-local -q "select * from numbers(200000000) format Parquet" > data.parquet
$ zip archive.zip data.parquet
$ clickhouse local -q "select * from file('archive.zip :: data', Parquet) format Null settings max_threads=4"
Code: 643. DB::Exception: Couldn't unpack zip archive '/home/avogar/tmp/data/archive.zip': Code = CRCERROR: (in file/uri data): While executing ParquetBlockInputFormat: While executing File. (CANNOT_UNPACK_ARCHIVE)
```

@al13n321 probably something is wrong with parallel reading from Parquet when we work with read buffers from archive

**Comment by al13n321** [comment]
Separately from this issue, weird that the parquet file compresses so much: 818 MB -> 57 MB (4.3 -> 0.29 bytes/row). It's supposed to already be compressed! With `output_format_parquet_compression_method='gzip'`, the parquet file is 354 MB, and `gzip`ping this file decreases its size to 57 MB!
