### ISSUE TITLE
The asynchronous_metric_log table occupies a significant portion of disk IO

### ISSUE THREAD

**Issue by SoaringCode** [ClickHouse/ClickHouse#58897]
The asynchronous_metric_log table occupies a significant portion of disk IO, resulting in particularly poor write and read performance. Can I stop writing to this log

**Comment by UnamedRus** [comment]
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/#you-can-disable-all--any-of-them

You can also make frequency of metric collection lower

```
<asynchronous_metrics_update_period_s>
    60
</asynchronous_metrics_update_period_s>
<asynchronous_metric_log>
    <flush_interval_milliseconds>
        60000
    </flush_interval_milliseconds>
</asynchronous_metric_log>
```

**Comment by SoaringCode** [comment]
> https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/#you-can-disable-all--any-of-them
> 
> 您还可以降低指标收集的频率
> 
> ```
> <asynchronous_metrics_update_period_s>
>     60
> </asynchronous_metrics_update_period_s>
> <asynchronous_metric_log>
>     <flush_interval_milliseconds>
>         60000
>     </flush_interval_milliseconds>
> </asynchronous_metric_log>
> ```
What works is asynchronous_metrics_update_period_s or flush_interval_milliseconds, I don't quite understand the role of these two

**Comment by UnamedRus** [comment]
> flush_interval_milliseconds

Dump data to table, before that it's being kept in memory

> asynchronous_metrics_update_period_s

Metric collection interval
