### ISSUE TITLE
Replicated table do not show real uuid value in replica_path

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#58905]
version: 23.3.7.5-lts with zookeeper

settings as below:
<default_replica_path>/clickhouse/{cluster}/tables/{uuid}/{shard}</default_replica_path>
<default_replica_name>{replica}</default_replica_name>

how to produce：
```sql
CREATE TABLE t1 on cluster '{cluster}'
(
    `id` UInt64
)
ENGINE = ReplicatedReplacingMergeTree()
ORDER BY (id);

show create table t1\G
```
the result show as below, the macro uuid do not show the real value, any way to show it?
```
CREATE TABLE t1
(
    `id` UInt64
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{cluster}/tables/{uuid}/{shard}', '{replica}')
ORDER BY id
SETTINGS index_granularity = 8192;
```

version 22.3.8.39-lts show the uuid value normally:
```
CREATE TABLE t1
(
    `id` UInt64
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{cluster}/tables/2dd320ee-9153-4376-949d-d904ad837c6f/{shard}', '{replica}')
ORDER BY id
SETTINGS index_granularity = 8192;
```

**Comment by tavplubix** [comment]
It is expected behavior, see https://github.com/ClickHouse/ClickHouse/pull/36200
See also https://clickhouse.com/docs/en/operations/settings/settings#show_table_uuid_in_table_create_query_if_not_nil
