### ISSUE TITLE
toTimeZone function to use timezone held as column value

### ISSUE THREAD

**Issue by Deshawnz** [ClickHouse/ClickHouse#58915]
Are there any plans to enhance the toTimeZone function to use non-constant values that are held as a column string value such as 'America/Los_Angeles', or any value from table system.time_zones?

The sql example below referencing system.time_zones displays the issue of toTimeZone not picking up the time_zone value when it is referenced from the column, or specified in the multiIf statement (non-constant value), but shows toTimeZone working with a constant timezone value (see tz_la).

The field aliased "toString_explicit" shows the only solution I've found online (only 3 timezones have been coded for).  This isn't a feasible solution to hardcode all 596 values held in system.time_zones.

![image](https://github.com/ClickHouse/ClickHouse/assets/56083719/25ed5a37-a37a-411f-86ef-4368df3a3c55)

![image](https://github.com/ClickHouse/ClickHouse/assets/56083719/ab3ca43c-c771-4ae5-99ad-63fd7ac34334)

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/issues/30415

**Comment by alexey-milovidov** [comment]
This is possible with the `toString` or `formatDateTime` functions. Example:

```
SELECT toString(now(), arrayJoin(['Europe/Amsterdam', 'America/Los_Angeles']))
```

Here, we use a non-constant time zone argument.

**Comment by Deshawnz** [comment]
Illegal type of argument :-/

![image](https://github.com/ClickHouse/ClickHouse/assets/56083719/6e19db7e-d6f7-4fa2-8505-885ad12f246b)

toString returning a timezone on now() only seems to work for me when stating explicitly the timeszone value as a string argument.  I've tried placing the column value argument from system.time_zones, and I get the same illegal type of argument exception.

**Comment by UnamedRus** [comment]
non const value only support starting from 23.9.

**Comment by HarisBinSaif** [comment]
I had 25.x version and non const value still raises an error. This was my workaround:
`select toString(date_time_column,time_zone_column) from your_table`
Works like a charm
