### ISSUE TITLE
Implement `SYSTEM` query to drop old partition nodes from ZooKeeper

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#58925]
In ReplicatedMergeTree we have a special nodes to allocate block numbers in each partition. These nodes are never removed since creation because it can lead to race condition with INSERT queries in the following way:
```
r1 (memory): 202210_0_777_99
r2 (memory): 202210_0_777_99
zookeeper: /blocks/202210 -> cversion = 778
Now someone start looong SELECT query from r1. 
Now someone run ALTER TABLE r2 DROP PARTITION 202210
r1 (memory): 202210_0_777_99 -- cannot remove part, because someone reading from it
r2 (memory): nothing -- last part was dropped
zookeeper: /blocks/_nothing_, we removed partition because last part was removed
Now someone INSERT new data part to r2
r1 (memory): 202210_0_777_99 -- cannot remove part, because someone reading from it
r2 (memory): 202210_0_0_0 new data part 
zookeeper: /blocks/202210 -> cversion = 1 freshly recreated node with new cversion
Now r1 pulls new state into memory and see
202210_0_0_0 intersects old part 202210_0_777_99 (someone still read from it)
```

The idea is to implement `SYSTEM` query which will cleanup old nodes from `blocks/partition`. When client will be sure that no new INSERT may appear in the old partition it's safe to execute this command. Syntax:
`SYSTEM DROP PARTITION NODE table partition` (suggestions are welcome).

**Comment by filimonov** [comment]
Relying on the user who should know that and remember to do that is not so nice.

It would be better to clean them automatically (for example in the ReplicatedMergeTreeCleanupThread) 

I think it can be considered safe if 
1) partition is empty 
2) block number for that partition was last modified more than X hours / days before (i guess about a week or two should be safe).

Not sure if it safe to rely on the timestamp of the znode modification, but probably yes.  

Since we don't need to run that operation too frequent we can also make run not with every run of CleanupThread, but for example once a day (may that can be configurable).

**Comment by tavplubix** [comment]
> block number for that partition was last modified more than X hours / days before

Relying on this is not really better than relying on the user

**Comment by ucasfl** [comment]
> > block number for that partition was last modified more than X hours / days before
> 
> Relying on this is not really better than relying on the user

But if user can control it by a setting, and the setting is disabled by default, I think it's will be good.

**Comment by alesapin** [comment]
Let's do both, query and disabled by default background thread?

**Comment by filimonov** [comment]
> disabled by default background thread?

probably nobody will enable that this way :) So not sure if really needed. Maybe some very big threshold? Like a month? 

Actually for that check it would be even better / safer to know the time of the drop partition... But i think there is no good way to find it currently?

**Comment by ucasfl** [comment]
> probably nobody will enable that this way :) 

I don't think so, because the feature is mainly for experienced user, so they will understand what does the feature did and when they should enable it. For other user, it's better not enabled by default.
