### ISSUE TITLE
Different result of largestTriangleThreeBuckets on 23.11 and 23.12

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#58944]
```sql
select largestTriangleThreeBuckets(4)(number-5,number+10) FROM numbers(1, 10)
```

23.11.4 result:
```[(-4,11),(-2,13),(0,15),(5,20)]```

23.12.2 result:
```[(-4,11),(-3,12),(1,16),(5,20)]```

**Comment by alsugiliazova** [comment]
One more exmaple:
```sql
select largestTriangleThreeBuckets(4)(y,x) from values('x Int8, y Float64', (0,0.1), (1,0.34), (2,.88), (3,-1.23), (4,-3.3), (5,5.4))
```
23.11.4 result:
```[(-3.3,4),(-1.23,3),(0.1,0),(5.4,5)]```

23.12.2 result:
```[(-3.3,4),(0.1,0),(0.88,2),(5.4,5)]```

**Comment by Algunenano** [comment]
Most likely related to https://github.com/ClickHouse/ClickHouse/pull/57003. The question is not if it's different or not, the question is which output is more correct out of the 2.

**Comment by UnamedRus** [comment]
23.12 seems matching timescaleDB implementation
https://fiddle.clickhouse.com/d6e1c465-5f8f-4af3-bb81-3cfea13c612a

https://docs.timescale.com/api/latest/hyperfunctions/downsampling/
