### ISSUE TITLE
ILLEGAL_DIVISION 

### ISSUE THREAD

**Issue by zhanglistar** [ClickHouse/ClickHouse#58969]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
For SQL:
`select x from (select intDiv(1023, number) as x from numbers(2) where number != 0 ) where x > 1`
We get :
```
Received exception from server (version 24.1.1):
Code: 153. DB::Exception: Received from localhost:9000. DB::Exception: Division by zero: while executing 'FUNCTION intDiv(1023 :: 2, number :: 0) -> intDiv(1023, number) UInt16 : 1'. (ILLEGAL_DIVISION)
```

But if delete `x>1`, we are good.
<img width="669" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/985418/e0063803-7c3a-4ba1-af52-4d0f2d30aef7">

* Which ClickHouse server version to use
 ClickHouse server version 24.1.1 revision 54466

**Expected behavior**
No exception.

**Comment by alexey-milovidov** [comment]
After condition pushdown, WHERE starts to process AND operator eagerly, without the short-circuit evaluation.

Let's check why this query does not evaluate AND with short-circuit:
```
SELECT intDiv(1023, number) AS x
FROM numbers(2)
WHERE (number != 0) AND (x > 1)
```

**Comment by lgbo-ustc** [comment]
It's the rule that if a column will be used later, this column would not be executed lazily

**Comment by Avogar** [comment]
To make the initial query work you can disable setting `enable_optimize_predicate_expression`.
Not sure if we actually can execute `x` lazily in the query
```
SELECT intDiv(1023, number) AS x
FROM numbers(2)
WHERE (number != 0) AND (x > 1)
```

**Comment by alexey-milovidov** [comment]
@Avogar But in this query, everything is alright:
```
SELECT * FROM numbers(10) WHERE number != 0 AND throwIf(number = 0)
```

And this is ok as well:
```
SELECT * FROM numbers(10) WHERE number != 0 AND (1 DIV number) = 1
```

**Comment by Avogar** [comment]
But here we have different case:
```
SELECT throwIf(number = 0) FROM numbers(10) WHERE number != 0 AND throwIf(number = 0)
```

And in this case expression `throwIf(number = 0)` will not be executed lazily. The reason is that this expression is used both in the result of the query and in the where condition, and we execute this expression once. Afaiu we will filter the result of the `throwIf(number = 0)` after it's execution and to filter it we need the full result.

**Comment by Avogar** [comment]
I don't think we will be able to execute `expression` lazily in queries like:
```
SELECT expression FROM ... WHERE condition AND some_func(expression)
```

Original issue is that optimization `enable_optimize_predicate_expression` led to query that doesn't work. If you want initial query to work, disable this optimization. I don't think we will disable it by default because in most cases this optimization improves query performance.

**Comment by zhanglistar** [comment]
@Avogar  Why cannot execute expresstion lazily when the expression used in result?

**Comment by zhanglistar** [comment]
Besides, this query is still not work 
`SELECT intDiv(1023, number) AS x
FROM numbers(2)
WHERE (number != 0) AND (x > 1)`, this is not related to `enable_optimize_predicate_expression`.

**Comment by zhanglistar** [comment]
While I think it is a rule confict, since 
1) `and(expr1, expr2...)` add the rule that expr2 should exeucted after expr1, lazily
2) `expr` used in result add another rule that it can not be exeucted lazily.
There should be a rule to solve this conflict.

**Comment by Avogar** [comment]
> Why cannot execute expresstion lazily when the expression used in result?

If we allow lazy expressions in the result, we will have 2 major problems:
- The same expression will be executed twice (once during `and/or/if/multiIf` execution, second when calculating query result), so the query time will increase. Imagine case when we have `SELECT expression FROM ... WHERE always_true_condition AND expression`, we will execute expression twice on the same data.
- Lazy expression is stored as `ColumnFunction` with corresponding function and arguments, if we allow query to return such result, we will have to support `ColumnFunction` in thousands of places in the code - it's just impossible to do properly.

> Besides, this query is still not work
SELECT intDiv(1023, number) AS x FROM numbers(2) WHERE (number != 0) AND (x > 1), this is not related to enable_optimize_predicate_expression.

Yes, but it's quite a strange usecase, and as I described, it will be really hard to make this query work out of box. Also, you can just rewrite this to
```
SELECT x from (SELECT intDiv(1023, number) AS x FROM numbers(2) WHERE (number != 0)) WHERE x > 1 settings enable_optimize_predicate_expression=0
```

And it's actually even better then allowing lazy exressions in the query result, as in this query `intDiv(1023, number)` will be executed once.
