### ISSUE TITLE
Join engine usage issues

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#58972]
Join engine, whether the size of data stored in RAM and disk is the same？
（1）on disk size 55GB
![企业微信截图_3e2b2fab-69e1-4290-b25f-a3063a9b3cae](https://github.com/ClickHouse/ClickHouse/assets/20608540/4ccd6358-380e-4e3c-be09-39b542f01508)

（2）on ram size 8GB
<img width="423" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/20608540/d5a470d5-c9e3-414a-8972-fb0f786a13b7">

**Comment by UnamedRus** [comment]
> Join engine, whether the size of data stored in RAM and disk is the same？

Check amount of binary files in Join table, engine.

ClickHouse does not merge them/deduplicate. 
So if you did multiple inserts in JOIN table, it's expected

**Comment by sunny19930321** [comment]
> > Join engine, whether the size of data stored in RAM and disk is the same？
> 
> Check amount of binary files in Join table, engine.
> 
> ClickHouse does not merge them/deduplicate. So if you did multiple inserts in JOIN table, it's expected

tks，when there are a lot of files, the startup load file is very slow, resulting in slow ck service startup. I can add a configuration to turn off this startup load mode(the default is enabled), and use system reload, like a dictionary table.
