### ISSUE TITLE
Inserted value UInt64 into Int32 column without complaining and unexpected value

### ISSUE THREAD

**Issue by alexon1234** [ClickHouse/ClickHouse#58980]
**Describe the unexpected behaviour**

We tried to insert a value above the Int32 supported range. I would expect the insert to fail as the value is out of range.

```sql
CREATE TABLE deleteme
(
    `a` Int32
)
ENGINE = MergeTree
PARTITION BY a
ORDER BY a;

INSERT INTO deleteme VALUES (18446744073709552111);

SELECT * FROM deleteme;

SELECT toInt32(18446744073709552111);
```

```
» cat script.sql | clickhouse-local -mn --echo                                                                                         
CREATE TABLE deleteme
(
    `a` Int32
)
ENGINE = MergeTree
PARTITION BY a
ORDER BY a;
INSERT INTO deleteme VALUES (18446744073709552111);
SELECT * FROM deleteme;
495
SELECT toInt32(18446744073709552111);
-2147483648
```

Also, I don't understand why we are inserting `495` when doing the casting manually returns  `-2147483648`

Tested on ClickHouse local version 23.12.2.59 (official build). and ClickHouse server version 23.12.2.

This is the same behavior for CH 21.9 and 22.8, but I don't think this behavior is the expected one

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/41100

**Comment by alexon1234** [comment]
Thanks @UnamedRus for pointing to that issue

**Comment by Algunenano** [comment]
> Also, I don't understand why we are inserting 495 when doing the casting manually returns -2147483648

Different rules for VALUES / SQL.

Values is treating it as a string:
```
SELECT
    '18446744073709552111' AS t,
    toTypeName(t),
    toInt32(t)

Query id: c58b8417-158a-427c-8fd6-f4f8c601c7b5

Row 1:
──────
t:                                  18446744073709552111
toTypeName('18446744073709552111'): String
toInt32('18446744073709552111'):    495

1 row in set. Elapsed: 0.000 sec. 
```

The query is treating it as a Float64:
```
SELECT
    18446744073709552000. AS t,
    toTypeName(t),
    toInt32(t)

Query id: b19241b8-5c7c-408b-b1dc-ca009e64b10f

Row 1:
──────
t:                                 18446744073709552000
toTypeName(18446744073709552000.): Float64
toInt32(18446744073709552000.):    -2147483648

1 row in set. Elapsed: 0.001 sec. 
```


Closing as duplicate

**Comment by alexon1234** [comment]
Thanks for the explanation @Algunenano
