### ISSUE TITLE
A function `clamp`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59019]
**Use case**

`clamp(x, min, max)`

is equivalent to

`least(greatest(x, min), max)`

**Comment by D0zee** [comment]
I'd like to do it on this weekend, but I'm beginner in the project and think that it can take some time

**Comment by alexey-milovidov** [comment]
@D0zee, thank you! It will be very nice!

**Comment by D0zee** [comment]
@alexey-milovidov If there are some entry points or places what should I look first, please let me know. It will really reduce time that I'm going to spent.

**Comment by alexey-milovidov** [comment]
Start working with the codebase: https://clickhouse.com/docs/en/development/developer-instruction/
ClickHouse architecture: https://clickhouse.com/docs/en/development/architecture/
Example of adding a function: https://github.com/ClickHouse/ClickHouse/pull/57442
Good video: https://youtu.be/tNzdrw1L1Xk

**Comment by D0zee** [comment]
@alexey-milovidov Do I correctly understand that if we have the table with ages (for example 10, 20, 30, 40), then after executing `SELECT clamp(age, 10, 29) FROM people` we should get 2 rows of output or 4 rows with values (10, 20, 29, 29)? I'm just trying to get use cases of `clamp` function.

In documentation it is stated that the ordinary function doesn't change count of rows. 
Could I ask you via Slack channel if it is more convenient for you?

**Comment by alexey-milovidov** [comment]
The function, similarly to all ordinary functions, should not change the number of rows. It clamps every row. So, the output will be `(10, 20, 29, 29)`.

**Comment by Blargian** [comment]
I'll work on this if D0zee is not working on it anymore.

**Comment by sarielwxm** [comment]
@alexey-milovidov  Hi, I want to try this task.
