### ISSUE TITLE
The `UTF8::computeWidth` function should skip ANSI escape sequences

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59020]
**Use case**

See the picture. There is one unpleasant detail: the width of a field is calculated incorrectly:

![Screenshot_20240120_105734](https://github.com/ClickHouse/ClickHouse/assets/18581488/62fc7f26-7476-4f15-9211-a2865e33e10b)

**Describe the solution you'd like**

Ignore the symbols inside https://en.wikipedia.org/wiki/ANSI_escape_code#CSIsection in width calculation.

Test:

```
:) SELECT format('\x1b[38;2;{0};{1};{2}m█\x1b[0m', 255, 128, 0) AS x

┌─x────────────────────┐
│ █ │
└──────────────────────┘
```

Should be:

```
:) SELECT format('\x1b[38;2;{0};{1};{2}m█\x1b[0m', 255, 128, 0) AS x

┌─x─┐
│ █ │
└───┘
```

PS. The original query is

`SELECT id, max(score) AS s, max(descendants), argMax(title, update_time), arrayStringConcat(arrayMap(x -> format('\x1b[38;2;{0};{1};{2}m█\x1b[0m', least(greatest(sqrt(x / 10) * 255, 0), 255)::UInt8::String, least(greatest(sqrt((x - 10) / 50) * 255, 0), 255)::UInt8::String, least(greatest(sqrt((x - 50) / 250) * 255, 0), 255)::UInt8::String), arrayDifference(arrayFill(x -> x != 0, maxResample(now() - INTERVAL 2 DAY, now(), 3600)(score, update_time))))) AS bar FROM hackernews_changes_items WHERE id IN (SELECT arrayJoin(ids) FROM (SELECT ids FROM hackernews_top WHERE type = 'top' ORDER BY update_time DESC LIMIT 1)) GROUP BY id ORDER BY s DESC`

**Comment by hoangtran080204** [comment]
Hi, I'm a first-time contributor and would like to take on this task.

**Comment by alexey-milovidov** [comment]
@hoangtran080204, how is it going?

**Comment by Blargian** [comment]
@alexey-milovidov I can pick this up if it's not still in progress, I worked on an issue with ANSI escapes before.

**Comment by alexey-milovidov** [comment]
@Blargian this will be very appreciated!

**Comment by alexey-milovidov** [comment]
Not done.
