### ISSUE TITLE
Parallel replicas don't work correctly with LIMIT BY

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59031]
https://pastila.nl/?00060fdd/74ae4b40844316f89a77e40aaa31032e#b3evo2mRGH1eCIDL4mXbbw==

**Comment by devcrafter** [comment]
Something with `LIMIT`
https://pastila.nl/?024053ae/421c78a162d2efcef68ee97c9d8b12f9#NeMBwdyRYc8e406Sxe6gkw==
