### ISSUE TITLE
DESCRIBE TABLE output in Native format includes unexpected new lines for "named" Tuple column types

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#59034]
**Describe what's wrong**

When executing a `DESCRIBE TABLE` command against the latest master version (24.1.1.1455), the response returned via HTTP using Native Format includes unexpected newlines in the `type` column for a "named" Tuple.

**How to reproduce**

Using version 24.1.1.1455:

Create the following table:  

```
CREATE TABLE tuple_test
(
    `tup` Tuple(u1 UInt64, ip2 IPv4)
)
ENGINE = MergeTree
ORDER BY tuple()
```

Using curl, export the `DESCRIBE TABLE` command over HTTP using Native format.

```
curl "http://localhost:8423?query=DESCRIBE%20TABLE%20tuple_test%20FORMAT%20Native" | xxd 

00000000: 0701 046e 616d 6506 5374 7269 6e67 0374  ...name.String.t
00000010: 7570 0474 7970 6506 5374 7269 6e67 2354  up.type.String#T
00000020: 7570 6c65 280a 2020 2020 7531 2055 496e  uple(.    u1 UIn
00000030: 7436 342c 0a20 2020 2069 7032 2049 5076  t64,.    ip2 IPv
00000040: 3429 0c64 6566 6175 6c74 5f74 7970 6506  4).default_type.
00000050: 5374 7269 6e67 0012 6465 6661 756c 745f  String..default_
00000060: 6578 7072 6573 7369 6f6e 0653 7472 696e  expression.Strin
00000070: 6700 0763 6f6d 6d65 6e74 0653 7472 696e  g..comment.Strin
00000080: 6700 1063 6f64 6563 5f65 7870 7265 7373  g..codec_express
00000090: 696f 6e06 5374 7269 6e67 000e 7474 6c5f  ion.String..ttl_
000000a0: 6578 7072 6573 7369 6f6e 0653 7472 696e  expression.Strin
000000b0: 6700                                     g.
```

Note the extra four bytes `0a 20 20 20` before the `u1 UInt64` and `ip2 IPv4` Tuple elements in the response.  These currently break `clickhouse-connect` column type parsing used for inserts.

**Expected behavior**

No whitespace should appear before the Tuple field names when returned from a DESCRIBE TABLE query over HTTP using Native Format.

Note -- clients can adapt to the unexpected whitespace but there is no apparent reason for the breaking behavior.

**Comment by Avogar** [comment]
It's not a bug, there was a backward incompatible change: https://github.com/ClickHouse/ClickHouse/pull/57726
So, if you want to have old behaviour, you should set `print_pretty_type_names=0` or `compatibility = '23.12'`.
