### ISSUE TITLE
Clickhouse merges is stuck

### ISSUE THREAD

**Issue by lingtaolf** [ClickHouse/ClickHouse#59044]
**Describe the unexpected behaviour**
Clickhouse server warned high memory usage, so I checked and found some merges were stuck. 
Then I tried to execute `system stop merge <table_name>`, but it didn't work, merges are still stuck.
<img width="1405" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/87509571/012cf5e1-df44-41cf-ae55-1109bc2c3c0e">

**How to reproduce**
* Which ClickHouse server version to use
Clickhouse Version: **22.8.14.1**

**Expected behavior**
Merges can finish normally.
Or we can stop it manually.

**Error message and/or stacktrace**
This is the trace from `stack_trace ` table with stuck merge thread id.
<img width="1753" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/87509571/20cb8e7c-49b6-4f63-8ab6-3705757f1cbf">

**Comment by Algunenano** [comment]
> Clickhouse Version: 22.8.14.1

Please update to a supported version.
