### ISSUE TITLE
INSERT INTO SELECT * -- performance declines over time

### ISSUE THREAD

**Issue by hypersousage** [ClickHouse/ClickHouse#59069]
I am trying to copy an 8 TB table (110 bil rows) from one machine to another that are connected by a gigabit network. The copy speed drops significantly over time. What are my options to troubleshoot this?

Server specs:
32 CPU, 126 GB RAM, disk: TOSHIBA_MG08ACA16TEY

ClickhouseVersion:
ClickHouse server version 23.12.2.59 (official build).

I am using INSERT INTO SELECT * query with  following params:
SETTINGS max_threads = 16, max_insert_threads = 16, min_insert_block_size_bytes = 2000000000

I also see that io is 100% utilized by kworker. iotop:
203431 be/4 root 0.00 B/s 0.00 B/s 0.00 % 99.99 % [kworker/u64:2+flush-8:0]

I have clickhouse metrics that export to prometheus, I can share some of them if needed.

**Comment by Algunenano** [comment]
> I also see that io is 100% utilized by kworker. iotop:

Is this in the target server or the source server. If it's the target server then it's likely that it has started merging parts created during the insert, which then leads to more IO usage which impacts the insert.

Check if there are merges / other background processes triggered or try disabling them in the target server until the insert finishes and see if that has any impact.

**Comment by hypersousage** [comment]
Stopped merges using `SYSTEM STOP MERGES ...`.  The problem's gone. Thank you, @Algunenano!
