### ISSUE TITLE
When doing trivial INSERT SELECT without WHERE, GROUP BY, etc, set max_threads to 1 automatically.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#5907]
Example:

```
INSERT INTO default.metrika_searches_07_zstd SELECT * FROM default.metrika_searches_07
```

This query works better if you `SET max_threads = 1` upfront.

**Comment by alexey-milovidov** [comment]
Note: allowing parallel INSERT on INSERT SELECT is another related task.

**Comment by alexey-milovidov** [comment]
SET max_threads = 1, max_block_size = min_insert_block_size_rows.

**Comment by nicelulu** [comment]
https://github.com/ClickHouse/ClickHouse/blob/7a822ad815f725f275202f57f15b541d9f73e8ac/dbms/src/Interpreters/InterpreterSelectQuery.cpp#L1498-L1499
Is this a similar optimization?

**Comment by alexey-milovidov** [comment]
@nicelulu It is similar but for different case: when SELECT has small limit and will read small amount of data.
