### ISSUE TITLE
Query cache must know which system tables are deterministic and which ones are not

### ISSUE THREAD

**Issue by vitlibar** [ClickHouse/ClickHouse#59071]
**How to reproduce**

```
SET use_query_cache=true;

SELECT * FROM system.processes; -- (A)

SELECT * FROM system.processes; -- (B) Note that this SELECT shows the same information as (A) -
                                -- for example query id and so on - instead of the actual information
                                -- about processes
```

The issue happens because the first result of the query `SELECT * FROM system.processes` is cached in the query cache and then used the second time. The issue was found in https://github.com/ClickHouse/ClickHouse/pull/59041.

So we need to make the code understand that any select from `system.processes` must not be cached. And for other system tables which are known to non-deterministic it's the same.

**Comment by vitlibar** [comment]
Currently we have function [isDeterministic()](https://github.com/ClickHouse/ClickHouse/blob/0791c75315f6ac50ec38f3f884f32ad1157f4f8f/src/Functions/IFunction.h#L228) only for functions, and not for storages. To handle this case correctly we need to give a function like `isDeterministic()` to storages too. Some storages are known to be deterministic (`system.one`, `system.numbers`, `system.build_options`, etc.), and some storages are either known to be non-deterministic (`system.settings`, `system.tables`, etc.), and for some storages it's unknown. If it's unknow we can tread such storages as non-deterministic too.

So if only deterministic storages are used in a query, then it's ok to store the query in the query cache.
If at least one non-deterministic storage is used in a query, then we need to check a setting like `query_cache_nondeterministic_function_handling` but for storages to decide what to do.

**Comment by rschu1ze** [comment]
The surprising behavior is at least [documented](https://clickhouse.com/docs/en/operations/query-cache):

> "[...]It is also possible to enable caching at user or profile level (e.g. via SET use_query_cache = true) but one should keep in mind that all SELECT queries including monitoring or debugging queries to system tables may return cached results then. [...]"

but you are right that a distinction between deterministic/non-deterministic storages would be better.
