### ISSUE TITLE
S3 request with non existing URL hanging forever

### ISSUE THREAD

**Issue by jrdi** [ClickHouse/ClickHouse#59084]
When running a `INSERT INTO FUNCTION s3` and passing a URL that doesn't exist, for example, using a wrong AWS region like in the following examples:

```sql
INSERT INTO FUNCTION s3('https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz', 'a', '', 'CSV') SELECT 1
```

or

```sql
BACKUP TABLE test TO S3('https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz', '', '')
```

The queries hang forever. See a comparison between 23.3 and 24.1 (master)

23.3.1.2823

```
$ time ./23.3.1.2823/clickhouse local --query "INSERT INTO FUNCTION s3('https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz', 'a', '', 'CSV') SELECT 1"
Code: 499. DB::Exception: Could not list objects in bucket 'my-bucket' with key 'export_1234.csv.gz', S3 exception: ``, message: 'Code: 198. DB::Exception: Not found address of host: my-bucket.s3.fake-region.amazonaws.com. (DNS_ERROR) (version 23.3.1.2823 (official build))'. (S3_ERROR)

real	25.751
user	0.100
sys	0.029
```

24.1.1.1536 (master)

```
$ time ./master/clickhouse local --query "INSERT INTO FUNCTION s3('https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz', 'a', '', 'CSV') SELECT 1"
^C^C
real	4:11.52
user	1.172
sys	0.030
```

(I have stopped the query after 4 minutes)

You can see the following logs when running the same query on a server. The request keeps returning timeout and gets retried forever due to a DNS error (expected since the URL shouldn't exist)

```

2024.01.22 19:30:02.237088 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: Request failed, now waiting 1600 ms before attempting again.
2024.01.22 19:30:03.872648 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Warning> DNSResolver: Cannot resolve host (my-bucket.s3.fake-region.amazonaws.com), error 0: Host not found.
2024.01.22 19:30:03.924270 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: Failed to make request to: https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz: Code: 198. DB::Exception: Not found address of host: my-bucket.s3.fake-region.amazonaws.com. (DNS_ERROR), Stack trace (when copying this message, always include the lines below):

<Empty trace>
 (version 24.1.1.1536 (official build))
2024.01.22 19:30:03.924385 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: AWSXmlClient: HTTP response code: -1
Resolved remote host IP address: my-bucket.s3.fake-region.amazonaws.com:443
Request ID:
Exception name:
Error message: Code: 198. DB::Exception: Not found address of host: my-bucket.s3.fake-region.amazonaws.com. (DNS_ERROR) (version 24.1.1.1536 (official build))
0 response headers:
2024.01.22 19:30:03.924413 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2024.01.22 19:30:03.924425 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: Request failed, now waiting 3200 ms before attempting again.
2024.01.22 19:30:07.157947 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Warning> DNSResolver: Cannot resolve host (my-bucket.s3.fake-region.amazonaws.com), error 0: Host not found.
2024.01.22 19:30:07.208666 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: Failed to make request to: https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz: Code: 198. DB::Exception: Not found address of host: my-bucket.s3.fake-region.amazonaws.com. (DNS_ERROR), Stack trace (when copying this message, always include the lines below):

<Empty trace>
 (version 24.1.1.1536 (official build))
2024.01.22 19:30:07.208774 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: AWSXmlClient: HTTP response code: -1
Resolved remote host IP address: my-bucket.s3.fake-region.amazonaws.com:443
Request ID:
Exception name:
Error message: Code: 198. DB::Exception: Not found address of host: my-bucket.s3.fake-region.amazonaws.com. (DNS_ERROR) (version 24.1.1.1536 (official build))
0 response headers:
2024.01.22 19:30:07.208803 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2024.01.22 19:30:07.208827 [ 148244 ] {59d7d287-5379-482d-9437-ccf6ecb2ca65} <Information> AWSClient: Request failed, now waiting 6400 ms before attempting again.
```

**Comment by jrdi** [comment]
Note that `max_execution_time` is not honored while retrying, even in version 23.3.

After trying with different versions It looks like this was introduced between 23.9 and 23.10:

```
time ./23.9.1.1854/clickhouse local --query "INSERT INTO FUNCTION s3('https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz', 'a', '', 'CSV') SELECT 1"
Code: 499. DB::Exception: Failed to check existence of key export_1234.csv.gz in bucket my-bucket: Code: 198. DB::Exception: Not found address of host: my-bucket.s3.fake-region.amazonaws.com. (DNS_ERROR) (version 23.9.1.1854 (official build)). (S3_ERROR)

real	33.604
user	1.493
sys	0.099
```

```

time ./23.10.3.5/clickhouse local --query "INSERT INTO FUNCTION s3('https://my-bucket.s3.fake-region.amazonaws.com/export_1234.csv.gz', 'a', '', 'CSV') SELECT 1"
^C^C
real	1:34.33
user	1.275
sys	0.037
```

(I have stopped the query after 1.5 minutes)

**Comment by CheSema** [comment]
This is the explanation of a root cause.
https://github.com/ClickHouse/ClickHouse/issues/58479

**Comment by LGDHuaOPER** [comment]
I also encountered the same problem, and even though I used the settings [`s3_retry_attempts`](https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/Settings.h#L108) and [`s3_request_timeout_ms`](https://github.com/ClickHouse/ClickHouse/blob/master/src/Core/Settings.h#L109), I couldn't change the result of the hanging forever.

**Comment by tb-fjurado** [comment]
Encountered the same problem, also when trying to kill the query it was not possible to do so. Example:

```
INSERT INTO FUNCTION s3('https://wrong-bucket-name.s3.eu-west-1.amazonaws.com/my/prefix_{_partition_id}.parquet', '[REDACTED]', '[HIDDEN]', 'Parquet') PARTITION BY formatDateTime(_timestamp, '%Y%m%d') SELECT * FROM my_table
```

This got stuck running for 1+ hour. Both the CPU & network egress of the instance indicated that no work was being done.

Then attempted to kill the query:
```
`KILL QUERY WHERE query_id = '<query_id>' SYNC`
```
And the kill command ran for 30 mins until I cancelled it.

Settings & ProfileEvents of the query, in case they can be of any help:
```
```
ProfileEvents:        {'Query':1,'InsertQuery':1,'QueriesWithSubqueries':2,'SelectQueriesWithSubqueries':2,'FileOpen':30,'Seek':331,'ReadBufferFromFileDescriptorRead':5742,'ReadBufferFromFileDescriptorReadBytes':422457131,'ReadCompressedBytes':418568217,'CompressedReadBufferBlocks':14389,'CompressedReadBufferBytes':2712880794,'OpenedFileCacheHits':135,'OpenedFileCacheMisses':30,'OpenedFileCacheMicroseconds':185,'IOBufferAllocs':349,'IOBufferAllocBytes':101202094,'ArenaAllocChunks':1,'ArenaAllocBytes':4096,'FunctionExecute':119879,'TableFunctionExecute':1,'MarkCacheHits':165,'CreatedReadBufferOrdinary':165,'DiskReadElapsedMicroseconds':1204000,'InsertedRows':1001041,'InsertedBytes':1606991912,'SelectedParts':12,'SelectedRanges':12,'SelectedMarks':131750,'SelectedRows':186715274,'SelectedBytes':2705608396,'WaitMarksLoadMicroseconds':804,'ContextLock':74,'RWLockAcquiredReadLocks':4,'PartsLockHoldMicroseconds':140,'RealTimeMicroseconds':16730689612,'UserTimeMicroseconds':3066783,'SystemTimeMicroseconds':1731194,'SoftPageFaults':1008493,'HardPageFaults':1,'OSIOWaitMicroseconds':970598,'OSCPUWaitMicroseconds':640,'OSCPUVirtualTimeMicroseconds':4797840,'OSReadBytes':375730176,'OSReadChars':422455296,'CreatedHTTPConnections':1,'S3WriteMicroseconds':137364,'S3WriteRequestsCount':1,'S3WriteRequestsErrors':1,'S3CreateMultipartUpload':1,'WriteBufferFromS3Microseconds':140915,'WriteBufferFromS3RequestsErrors':1,'LogInfo':5}
Settings:             {'max_threads':'16','s3_create_new_file_on_insert':'1','use_uncompressed_cache':'0','move_all_conditions_to_prewhere':'0','enable_multiple_prewhere_read_steps':'0','move_primary_key_columns_to_end_of_prewhere':'0','compile_expressions':'0','compile_aggregate_expressions':'1','cluster_for_parallel_replicas':'thn','insert_deduplicate':'1','http_wait_end_of_query':'1','http_write_exception_in_output_format':'0','http_response_buffer_size':'104857600','optimize_throw_if_noop':'1','joined_subquery_requires_alias':'0','max_bytes_before_external_group_by':'45442450940','max_result_bytes':'104857600','max_execution_time':'14400','max_expanded_ast_elements':'50000','readonly':'2','join_algorithm':'auto','max_memory_usage':'70032385536','memory_usage_overcommit_max_wait_microseconds':'50000','log_query_threads':'0','max_partitions_per_insert_block':'100','enable_lightweight_delete':'0','optimize_monotonous_functions_in_order_by':'0','allow_nondeterministic_mutations':'1','enable_global_with_statement':'0','optimize_rewrite_sum_if_to_count_if':'0','distributed_ddl_entry_format_version':'3','local_filesystem_read_method':'pread','read_from_filesystem_cache_if_exists_otherwise_bypass_cache':'1','insert_keeper_max_retries':'15','insert_keeper_retry_initial_backoff_ms':'100','insert_keeper_retry_max_backoff_ms':'2000','input_format_null_as_default':'0','output_format_json_quote_64bit_integers':'0'}
```

**Comment by panthony** [comment]
I had a similar issue but it was with a misconfigured SSL certificate on the clickhouse server, it failed to properly connect to S3 and the query hang and was unkillable.

**Comment by vmihailenco** [comment]
Can confirm that ClickHouse database becomes unresponsive when S3 endpoint becomes unavailable.

**Comment by Algunenano** [comment]
Same issue being detected in the stress tests: https://s3.amazonaws.com/clickhouse-test-reports/63778/937b7323cb4505185fb0cd83e35fc5c85356d616/stress_test__tsan_/hung_check.log Reading from s3 does not respect `max_execution_time`

**Comment by thiskevinwang** [comment]
@tb-fjurado @vmihailenco How were you able to kill either of these queries? [^1]

Either the hanging `SELECT` or the handing `KILL query`

[^1]: https://github.com/ClickHouse/ClickHouse/issues/59084#issuecomment-1921454865
