### ISSUE TITLE
In ClickHouse, the valid range for Date type is from 1970-01-01 to 2149-06-06

### ISSUE THREAD

**Issue by kingorpirates** [ClickHouse/ClickHouse#59096]
I need this sentinel value, but since it is not supported, I need to perform various logical conversions. Can this support a longer time range

**Comment by rschu1ze** [comment]
Use [Date32](https://clickhouse.com/docs/en/sql-reference/data-types/date32) instead, its range is 1900-01-01 - 2299-12-31
