### ISSUE TITLE
Clickhouse query

### ISSUE THREAD

**Issue by sabinajvdva** [ClickHouse/ClickHouse#59113]
Hi!

I need advise on how to calculate sum of the amount of the last 90 days by each day of month. Example, I need to see total amount of the last 90 days of '2023-12-05' , next total amount of the last 90 days of '2023-12-04' and so on. 

Table: dt, amount

thank you in advance

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/window-functions#moving--sliding-average-per-10-days

**Comment by sabinajvdva** [comment]
no, this takes data BETWEEN 90 PRECEDING AND CURRENT ROW, but I need 90 preceding and the first row of each day. 
example: 
sum(amount) for the last 90 days for '2023-12-05,
sum(amount) for the last 90 days for '2023-12-04,
sum(amount) for the last 90 days for '2023-12-03,
sum(amount) for the last 90 days for '2023-12-02,
....

**Comment by den-crane** [comment]
>90 preceding and the first row

90 preceding rows? days?

>and the first row

What is the first row  of each day? Which row is the first?

Can you please provide a data example using https://fiddle.clickhouse.com/

**Comment by sabinajvdva** [comment]
Sure, here is an example of a table. Let's take not 90 days, but 3 to make it simple. 
<img width="900" alt="Снимок экрана 2024-01-25 в 10 44 33" src="https://github.com/ClickHouse/ClickHouse/assets/61385978/32e26ca9-eeca-4b4a-8152-554e2053ac92">

https://fiddle.clickhouse.com/7b794722-272e-4244-8734-c3505a982689 

For example 2023-11-30 the total count for the last  3 days (last 3 days specifically for this date)  is 2+1+4 = 7
For 2023-11-29 the total count for the last  3 days is 1+4+2 = 7
For  2023-11-28 the total count for the last 3 days is 4+2+3 = 9
--- and so on 

I need to see for each date this total cnt 
At the end final output should look like this 

dt                     cnt_last_3_days_active
2023-11-30     7
2023-11-29     7
2023-11-28     9
--- 
---

**Comment by sabinajvdva** [comment]
@den-crane hey, any ideas?

**Comment by allegrinisante** [comment]
Hi @sabinajvdva ,

As @den-crane suggested, `window functions` are usually an excellent approach to addressing your needs. 
Please note that if you want to use `PRECEDING` and `CURRENT ROW,` you must ensure there are no gaps in your dates. If this is the case the window function will get the 90 preceding rows without considering a 90 days difference between the current row and the preceding rows. 

I can suggest a more general approach that uses a self-join. 
This approach though is not necessarily the most performant.

This is the original table:
```sql
SELECT *
FROM test_running
ORDER BY dt DESC
┌─────────dt─┬─cnt─┐
│ 2023-11-30 │   2 │
│ 2023-11-29 │   1 │
│ 2023-11-28 │   4 │
│ 2023-11-27 │   2 │
│ 2023-11-26 │   3 │
│ 2023-11-25 │   1 │
│ 2023-11-24 │   2 │
│ 2023-11-23 │   5 │
│ 2023-11-22 │   2 │
│ 2023-11-21 │   2 │
└────────────┴─────┘
```

This is the query to get the `running sum` over the past three days.
```sql
SELECT
    t1.dt,
    max(t1.cnt) AS cnt,
    sum(t2.cnt) AS running_sum
FROM test_running AS t1, test_running AS t2
WHERE (dateDiff('day', t1.dt, t2.dt) <= 0) AND (dateDiff('day', t1.dt, t2.dt) >= -2)
GROUP BY t1.dt
ORDER BY t1.dt DESC

┌─────────dt─┬─cnt─┬─running_sum─┐
│ 2023-11-30 │   2 │           7 │
│ 2023-11-29 │   1 │           7 │
│ 2023-11-28 │   4 │           9 │
│ 2023-11-27 │   2 │           6 │
│ 2023-11-26 │   3 │           6 │
│ 2023-11-25 │   1 │           8 │
│ 2023-11-24 │   2 │           9 │
│ 2023-11-23 │   5 │           9 │
│ 2023-11-22 │   2 │           4 │
│ 2023-11-21 │   2 │           2 │
└────────────┴─────┴─────────────┘
```

I hope this helps.
