### ISSUE TITLE
[RFC] Bulk importing to EmbeddedRocksDB tables

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#59128]
> (you don't have to strictly follow this form)

**Use case**

In our case, EmbeddedRocksDB tables are usually used as dictionaries: we write a large amount of data once, then read many times, and only write again after a few days (or even weeks). I think many others are also using EmbeddedRocksDB this way.

We've faced multiple issues when running a long `INSERT SELECT` to EmbeddedRocksDB tables. Some worth mentioning:

1. ClickHouse cannot track insert query memory properly

Insertions first go to memtables. When a memtable is full, it becomes immutable and a rocksdb thread will flush immutable memtables to disk later. This means memtables are created and allocated memory by a ClickHouse thread, but then destroyed by a rocksdb thread --> memory tracker cannot track deallocation --> for a long insertion, ClickHouse memory tracker keeps growing and the query will be OOM. The issue can be reproduced easily by a long insertion (e.g. 1B rows) to any EmbeddedRocksDB table.

2. Write stalls

Inserting is fast at first, but then becomes slower due to write stalls (flush/compaction cannot keep up). Parallel insertion also doesn't increase the insert query speed because write stalls. Although we can tune rocksdb options, TBH I think it's not trivial for normal users.

**Describe the solution you'd like**

Propose to have a new sink type: `EmbeddedRocksDBBulkSink`. It will not directly write to rocksdb but will convert the incoming chunk to an SST file in a temporary directory, and then import the file to rocksdb. The advantages:

- Completely bypass memtables --> less overhead, more control over memory usage
- With a big enough insertion block size, we don't need to worry about write stalls
- Parallel insertion can scale linearly

Bulk loading can be enabled/disabled by a query setting.

**Describe alternatives you've considered**

Tune rocksdb options, but I think bulk loading will benefit more people. Rocksdb also recommends this approach for bulk loading (https://rocksdb.org/blog/2017/02/17/bulkoad-ingest-sst-file.html).

**Additional context**

1. I have an implementation and it works well, can see a visible gain in long-running `INSERT SELECT`
2. This is a warm-up task for a bigger objective: to make `EmbeddedRocksDB` not just a wrap-around of rocksdb API but can control SST files and compactions. Then we can have `ReplicatedEmbeddedRocksDB`.

Appreciate for comments @sundy-li @hanfei1991 @azat

**Comment by azat** [comment]
Yes, bulk loading makes total sense to me. Since you already have implementation, maybe you also have some numbers that you can share?

**Comment by sundy-li** [comment]
How to deal with conflict keys in concurrent inserts?

**Comment by canhld94** [comment]
> Yes, bulk loading makes total sense to me. Since you already have implementation, maybe you also have some numbers that you can share?

@azat yes. I tested with inserting 100M rows, no rocksdb options running.
Currently the implementation uses a table setting `optimize_for_bulk_insert` instead of query setting.

Without bulk loading (notice the memory usage as well, query may not use that much memory but memory tracker cannot properly track rocksdb deallocation when destroying memtables). Insert speed is fast up until 20M rows, after that due to write stalls, it get slower and slower.
```sql
CREATE TABLE rocksdb_dict_normal_load
(
    `key` UInt64,
    `v1` FixedString(30)
)
ENGINE = EmbeddedRocksDB
PRIMARY KEY key SETTINGS optimize_for_bulk_insert = 0;

INSERT INTO rocksdb_dict_normal_load SELECT
    rand(number),
    randomPrintableASCII(30)
FROM numbers(100000000);

Query id: fe94ad28-63d4-49de-ad05-51af68189317

Ok.

0 rows in set. Elapsed: 422.163 sec. Processed 100.00 million rows, 800.00 MB (236.88 thousand rows/s., 1.90 MB/s.)
Peak memory usage: 6.32 GiB.
```
With bulk loading
```sql
CREATE TABLE rocksdb_dict_bulk_load
(
    `key` UInt64,
    `v1` FixedString(30)
)
ENGINE = EmbeddedRocksDB
PRIMARY KEY key SETTINGS optimize_for_bulk_insert = 1;

INSERT INTO rocksdb_dict_bulk_load SELECT
    rand(number),
    randomPrintableASCII(30)
FROM numbers(100000000)

Query id: 25a7ca7d-d8dd-4450-bcf8-b66f9ac750e7

Ok.

0 rows in set. Elapsed: 114.672 sec. Processed 100.00 million rows, 800.00 MB (872.05 thousand rows/s., 6.98 MB/s.)
Peak memory usage: 178.62 MiB.
```

**Comment by canhld94** [comment]
> How to deal with conflict keys in concurrent inserts?

@sundy-li  As far as I understand, different SST files may have duplicated keys. So it's ok to have concurrent bulk inserts.

If there're bulk insert and normal insert running concurrently, conflict keys will be resolved by rocksdb when calling `DB::IngestExternalFile()`. As ref (https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files#what-happens-when-you-ingest-a-file):

```
When you call DB::IngestExternalFile() We will

- Copy or link the file into the DB directory
- Block (not skip) writes to the DB because we have to keep a consistent db state so we have to make sure we can safely assign the right sequence number to all the keys in the file we are going to ingest
- If file key range overlap with memtable key range, flush memtable
- Assign the file to the best level possible in the LSM-tree
- Assign the file a global sequence number
- Resume writes to the DB
```

**Comment by azat** [comment]
@canhld94 it will be interesting to see how it will work with `max_insert_threads`.

**Comment by azat** [comment]
>As far as I understand, different SST files may have duplicated keys

Overlaps are allowed on L0 level, so I guess everything should work (besides I guess such API will not be provided without proper gurantees)

**Comment by canhld94** [comment]
> I thought that (2) is done by rocksdb, so you cannot overlap (1) and (2) then.

(2) is also done by CH, I submitted the PR.

> Actually if max_insert_threads does not scale throughput linear, I guess that the overhead of IngestExternalFile is, at least, noticeable.

To be fair, it's linear when `max_insert_threads` is relatively small:

```
1 threads - Elapsed: 114.672 sec.
2 threads - Elapsed: 62.654 sec.
3 threads - Elapsed: 49.223 sec.
4 threads - Elapsed: 33.493 sec.
...
16 threads -  Elapsed: 12.292 sec.
```

Possible that when we have high concurrent calls to `IngestExternalFile` it will incur noticeable overhead.
