### ISSUE TITLE
skip_unavailable_shards=0 is not working as expected

### ISSUE THREAD

**Issue by kazhou2024** [ClickHouse/ClickHouse#59144]
I set skip_unavailable_shards=0, One shard of clickhouse is not ready, but the distributed query only returns partial result from 2 shards instead of throwing error. 

The Cluster has 3 shards, from the initial clickhouse instance(shard0) I saw below errors of all instance of shard2, but the query succeeded with partial result from shard0 and shard1, not throw exception.

Question: we want to forbidden such partial result, we perfer clickhouse throw exception instead, what kind setting should we set or any solutions? 

	Line   19968: 2024.01.19 00:07:57.709558 [ 237 ] {} <Error> DNSResolver: Cannot resolve host (chi-bi-2-1-0.chi-bi-2-1.clickhouse.svc.cluster.local), error 0: chi-bi-2-1-0.chi-bi-2-1.clickhouse.svc.cluster.local.
	Line   19969: 2024.01.19 00:07:57.709707 [ 237 ] {} <Error> bool DB::DNSResolver::updateCacheImpl(UpdateF &&, ElemsT &&, const DB::String &) [UpdateF = bool (DB::DNSResolver::*)(const std::string &), ElemsT = std::unordered_set<std::string> &]: Code: 198. DB::Exception: Not found address of host: chi-bi-2-1-0.chi-bi-2-1.clickhouse.svc.cluster.local. (DNS_ERROR), Stack trace (when copying this message, always include the lines below):
	L

**Comment by kazhou2024** [comment]
Our Clickhouse version is 22.3

**Comment by alexey-milovidov** [comment]
No - partial result should not be returned.
