### ISSUE TITLE
performance issue with grouping over sub-query

### ISSUE THREAD

**Issue by cluelessss** [ClickHouse/ClickHouse#5918]
Hi, 

While trying to benchmark clickhouse using SSB, I stumbled upon this 2 performance issues.
Lets Assume the following query A:
```sql
select sum(LO_REVENUE), toYear(LO_ORDERDATE), P_BRAND
    from 
    (   select LO_REVENUE, LO_ORDERDATE, LO_PARTKEY, LO_SUPPKEY
        from lineorder
        where LO_PARTKEY in 
        (
            select P_PARTKEY
            from ssb.part
            where P_CATEGORY = 'MFGR#12'
        ) and LO_SUPPKEY in 
        (
            select S_SUPPKEY
            from ssb.supplier
            where S_REGION = 'AMERICA'
        ) 
    )
    INNER JOIN 
    (
        select P_PARTKEY AS PARTKEY1, P_BRAND
        from ssb.part where P_CATEGORY = 'MFGR#12'
    )
    ON LO_PARTKEY = PARTKEY1
    group by toYear(LO_ORDERDATE), P_BRAND
    order by toYear(LO_ORDERDATE), P_BRAND;
```
This query (A) run for 30 seconds on a one terabyte DB. but if Im running its sub-query A1 Wrapped up with count(*) like this:
```sql
SELECT COUNT(*) from (select LO_REVENUE, LO_ORDERDATE, LO_PARTKEY, LO_SUPPKEY
        from lineorder
        where LO_PARTKEY in 
        (
            select P_PARTKEY
            from ssb.p
            where P_CATEGORY = 'MFGR#12'
        ) and LO_SUPPKEY in 
        (
            select S_SUPPKEY
            from ssb.supplier
            where S_REGION = 'AMERICA'
        ) 
    )
    INNER JOIN 
    (
        select P_PARTKEY AS PARTKEY1, P_BRAND
        from ssb.part where P_CATEGORY = 'MFGR#12'
    )
    ON LO_PARTKEY = PARTKEY1
```

Then this A1 runs for only 7 seconds. the count of this A1 is 41 million rows. So it means that Click preform the grouping and aggregation on 41 million rows for more than 20 seconds while querying over the fact (lineorder) and joining it took 7 seconds. Its seems like a very slow grouping. 
Just to be on the safe side I have inserted A1 into temporary table (T1) and run the group by and aggregation over it. This query run for less than 1 second :
```sql
SELECT sum(LO_REVENUE), toYear(LO_ORDERDATE), P_BRAND from T1 
group by toYear(LO_ORDERDATE), P_BRAND
    order by toYear(LO_ORDERDATE), P_BRAND;
```
I get another puzzling performance result when running A1 sub-query A2 (wrapped with  count(*) ):
```sql
SELECT COUNT(*) from ( select LO_REVENUE, LO_ORDERDATE, LO_PARTKEY, LO_SUPPKEY
        from lineorder
        where LO_PARTKEY in 
        (
            select P_PARTKEY
            from ssb.part
            where P_CATEGORY = 'MFGR#12'
        ) and LO_SUPPKEY in 
        (
            select S_SUPPKEY
            from ssb.supplier
            where S_REGION = 'AMERICA'
        ) 
    )
```
As you can see A2 suppose to run faster since its omitting the join preformed in A1. But it runs slower. The join itself dose not change to row count since it was already done in the "In select" statement in the filter of A2.
Can you advise?

Some general information about the queries and the cluster:
SSB:
I'm using a variation of the Star Schema Benchmark . 
In order for the benchmark queries to run they've been rewritten to overcome the lack of support for implicit joins and multiple joins, into nested subqueries, the original query from which I rewrite A is:
```sql
select sum(lo_revenue), d_year, p_brand
from lineorder, date, part, supplier
 where lo_orderdate = d_datekey
 and lo_partkey = p_partkey
 and lo_suppkey = s_suppkey
 and p_category = 'MFGR#12'
 and s_region = 'AMERICA'
 group by d_year, p_brand
 order by d_year, p_brand;
```
As you can see, in Addition, I've dropped the Date dimension table, add a date column to the fact table and use date-time functions.

Cluster:
I  used 2 node cluster each node has 16 cores and 32G memory (c5d.4xlarge of amazon). The queries run on a distribute fact table but local dimension tables present in full on each node of the cluster.

P.S. This issue might be duplicate of issue #5722. In not sure though , since in #5722 it seems like a join related issue, while in my case the join statement is not slowing the query it (strangely) speeding it up.

**Comment by 4ertus2** [comment]
Hi,

For the A->A1 part it's possible to omit reading P_BRAND and LO_ORDERDATE columns in A1. ClickHouse tries not not read unused columns. I think it's the answer for the A->A1 issue.

A1 -> A2 is quite strange. But it the right table is small it could be some performance fluctuation. What is your right joined table size and what is the difference in median time of A1 and A2?
