### ISSUE TITLE
How do I insert into a table with an Array of Nested type?

### ISSUE THREAD

**Issue by linqingping** [ClickHouse/ClickHouse#59209]
Can I create a table in the following format and how would I write the insert statement?

CREATE TABLE test(
   `id` Int32,
    `test` Array(
        Nested(
           `test` String
        )
    )
) ENGINE = MergeTree
ORDER BY (id);

**Comment by linqingping** [comment]
INSERT INTO test (`id`, `test.test`) 
VALUES 
(1, [['name1']]), 
(2, [['name2'], ['name3']]);

SQL 错误 [16]: ClickHouse exception, code: 16, host: 192.168.70.221, port: 8123; Code: 16. DB::Exception: No such column test.test in table default.test (02daee17-45df-40a7-a35a-8b352994615d). (NO_SUCH_COLUMN_IN_TABLE) (version 23.12.2.59 (official build))

**Comment by Algunenano** [comment]
Seems you are missing some parenthesis:

```
CREATE TABLE test
(
    `id` Int32,
    `test` Array(Nested(test String))
)
ENGINE = MergeTree
ORDER BY id
```

```
insert into test values (0, [[('name')]]), (1, [[('name2'), ('name3')]]);
```

```
SELECT *
FROM test

Row 1:
──────
id:   0
test: [[('name')]]

Row 2:
──────
id:   1
test: [[('name2'),('name3')]]

2 rows in set. Elapsed: 0.001 sec. 
```
