### ISSUE TITLE
is it possible to get tuple constant witn named fields, for example: SELECT (1 AS first_number, 2 AS second_number) as t, t.1, t.first_number 

### ISSUE THREAD

**Issue by zav379** [ClickHouse/ClickHouse#59210]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by Algunenano** [comment]
You need a named tuple to do this:

```
SELECT
    CAST((1 AS first_number, 2 AS second_number), 'Tuple(first_number UInt64, second_number UInt64)') AS t,
    t.1 AS f,
    tupleElement(t, 'second_number') AS s

Query id: ecd89709-fb81-4b11-9e75-2d6c7f2f5f00

┌─t─────┬─f─┬─s─┐
│ (1,2) │ 1 │ 2 │
└───────┴───┴───┘
```

**Comment by vpanfilov** [comment]
Related to https://github.com/ClickHouse/ClickHouse/issues/54921
