### ISSUE TITLE
Lightweight deletes are blocking and extremely slow (over 3 minutes) even for non existent rows

### ISSUE THREAD

**Issue by martinfdr** [ClickHouse/ClickHouse#59225]
**Describe the unexpected behaviour**

I have issue with lightweight deletes on cluster. mutations_sync=0 is Globally set. Python client and clickhouse-client though waits for the response and it waits for several minutes. I expected that lightweight deletes are finished immediately and processed later. Another issue is that even lightweight delete on row that does not exist takes more than 3 minutes with resulting message that no rows were found. Below are 3 queries with results that shows exactly the issue

```
Most important unexpected behaviors are these:

- Lightweight delete with simple where condition that finds **no rows** also takes over 3 minutes, while select with the same conditions takes 0.23s
- Client is waiting for the delete
- ON CLUSTER or on single Node, Delete takes same time
``````
Another strange thing is that mutations are resolved one per node

![image](https://github.com/ClickHouse/ClickHouse/assets/142501267/79db034c-d049-48d6-a2b6-22bad5a90cc7)

And the resolution time is crazy

![image](https://github.com/ClickHouse/ClickHouse/assets/142501267/1ae46a2e-08c3-41fb-b5a9-7b1d40d9ea46)

**How to reproduce**

Very large sharded database + simple lightweight delete with condition on few hundreds rows or actually where condition that does not satisfy any row

* Which ClickHouse server version to use

23.8.2

* Which interface to use, if matters

Doesnt matter, but these were used
python client or clickhouse client

* Non-default settings, if any

allowed lightweight deletes + mutations_sync=0(probably default)

* Queries to run that lead to unexpected result

**3 queries that proves very strange behaviour**

```sql
|||||||||||| QUERY 1:  ON CLUSTER - ddl timeout 


SERVER:) DELETE FROM "default".table_local  ON CLUSTER cc
                WHERE databaseId = 'customer-1' AND userId = '5f9650ff-cd2a-44a3-b5af-9fe735cef580'
                SETTINGS mutations_sync=0
DELETE FROM default.table_local ON CLUSTER cc WHERE (databaseId = 'customer-1') AND (userId = '5f9650ff-cd2a-44a3-b5af-9fe735cef580')
SETTINGS mutations_sync = 0
Query id: 56f4d2a1-3824-4700-8bef-1651c080aa71
:arrow_upper_left: Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
--------> 0 rows in set. Elapsed: 180.250 sec. 

Received exception from server (version 23.8.2):
Code: 159. DB::Exception: Received from localhost:9000. DB::Exception: Watching task /clickhouse/task_queue/ddl/query-0000009198 is executing longer than distributed_ddl_task_timeout (=180) seconds. There are 6 unfinished hosts (0 of them are currently active), they are going to execute the query in background. (TIMEOUT_EXCEEDED)

```

------------------------------------------------------------------------------------------------------------------------

```sql
||||||||||| QUERY 2: Single node - 211s, no row found 


SERVER:) DELETE FROM "default".table_local
                WHERE databaseId = 'customer-1' AND userId = '5f9650ff-cd2a-44a3-b5af-9fe735cef580'
                SETTINGS mutations_sync=0
DELETE FROM default.table_local WHERE (databaseId = 'customer-1') AND (userId = '5f9650ff-cd2a-44a3-b5af-9fe735cef580')
SETTINGS mutations_sync = 0
Query id: d1a8e7b9-e1e9-49a9-94f4-ff887895ef21
Ok.
-----------> 0 rows in set. Elapsed: 211.956 sec. 

```
----------------------------------------------------------------------------------------

```sql
||||||||||| QUERY 3: SELECT - under 1 s


SERVER :) select * from default.table_local
                WHERE databaseId = 'customer-1' AND userId = '5f9650ff-cd2a-44a3-b5af-9fe735cef580'
SELECT *
FROM default.table
WHERE (databaseId = 'customer-1') AND (userId = '5f9650ff-cd2a-44a3-b5af-9fe735cef580')
Query id: 5d1f3aa8-8b62-4312-a406-5fad80144bf5
Ok.
------> 0 rows in set. Elapsed: 0.233 sec. Processed 900.31 thousand rows, 40.09 MB (3.86 million rows/s., 171.95 MB/s.)
Peak memory usage: 15.57 MiB.

``````

**Expected behavior**

Expected that clickhouse-client would send lightweight delete to background immediately. And the speed would be little slower than select (meaning the clickhouse-client would not block for +3 minutes). Obviously I do not expect the delete itself to take short time, but atleast marking the _row_exists to be much much faster

**Table creation**

local table
```sql
...
    INDEX `userId_index` `userId` TYPE bloom_filter(0.001000) GRANULARITY 1,
...(not involved columns)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/promisc/{shard}/table_local', '{replica}') PARTITION BY (databaseId, toYYYYMM(`timestamp`)) ORDER BY (databaseId, timestamp) TTL timestamp + INTERVAL 3 MONTH  SETTINGS index_granularity=8192

``````

**Comment by UnamedRus** [comment]
How many parts/partitions you have in that table?

**Comment by martinfdr** [comment]
> How many parts/partitions you have in that table?

There are around 55000 parts per node and each node has around 10500 unique partitions

**Comment by UnamedRus** [comment]
It may work, if you will do mutation in partition

Alter table xxx UPDATE _row_exists =0 IN PARTITION ID 'xxxx' WHERE ....

**Comment by martinfdr** [comment]
> It may work, if you will do mutation in partition
> 
> Alter table xxx UPDATE _row_exists =0 IN PARTITION ID 'xxxx' WHERE ....

So problem is too many parts and parttions and solution is to bypass lightweight delete and do standard delete on specific partitions? I thought that where condition would do that automatically (finding the partitions)

**Comment by UnamedRus** [comment]
Its not standard delete, its still LWD, check that i  did UPDATE mutation over _row_exists column

**Comment by martinfdr** [comment]
> Its not standard delete, its still LWD, check that i did UPDATE mutation over _row_exists column

Your advice partially works, and possibly revealed the issue. As far as I do this command on local table without ON CLUSTER statement, its done immediately. If I do it like this on all nodes, its the same. However, If I do it on any node with ON CLUSTER statement, it is again stuck on ddl timeout.

I am now not quite sure about causality of the issue. Should I alter table for each node separately to solve the issue, or use this approach with ON CLUSTER statement after I fix the ddl timeout in order to avoid the issue in the future?

**Comment by guoxiaolongzte** [comment]
Alter table xxx UPDATE _row_exists =0 IN PARTITION ID 'xxxx' WHERE ....? Is this plan feasible?

**Comment by eqinox76** [comment]
We see a similar behavior. Queries are really fast 100ms but a LWD takes 10m (2 node replicatedMergeTree, 500gb Table, partitioned by year, biggest part 50gb, clickhouse 23.12).
In addition i see the LWD are exectuted one by one. As far as i understand that is because they are executed via `system.distributed_ddl_queue`. This makes several small LWD surprisingly slow as i would expect the queries to run in parrallel.

As far as i can figure out this behavior seems to be cpu bound as the big parts are scanned by one thread (as documented). But as these LWD are executed one after another we see only one cpu being used for a surprisingly long time when using LWD. I dont see any plans to make the ddl_queue or LWD process in parrallel.

Any hints on how to debug this further? The scan time seems surprisingly high compared with a simple select.

**Comment by 0xgeert** [comment]
@eqinox76 Fwiw just today asked the same on Slack, and after a detour found the above mentioned `Alter table xxx Update _row_exists =0 IN PARTITION ID 'xxxx' WHERE ....` which does seem to improve things. Don't forget to append `SETTINGS mutations_sync=1` (or 2 if you care for all nodes to be synced)

**Comment by eqinox76** [comment]
The workaround by doing `UPDATE ... IN PARTITION` is certainly something we will do together with reducing the size of our parts a bit. 
But i think thats brittle as the LWD implementation may change and would be very much interessted in understanding why the LWD takes so much longer than a simple search as @martinfdr observed.

**Comment by wingdagger** [comment]
I am also seeing this issue where "Lightweight" Deletes are taking tens of seconds or even minutes once I get up to about 20 million rows of data in a single wide table.  Trying to "lightweight" delete even a single row using its PK takes tens of seconds.  Using the workaround of ALTER TABLE to delete one or many rows brings the request down to < 100ms.   Is there a fix planned to address this?

**Comment by den-crane** [comment]
>ALTER TABLE to delete one or many rows brings the request down to < 100ms. 

`ALTER TABLE ... settings mutations_sync=1;`
or `ALTER TABLE ... settings mutations_sync=0;` ?

**Comment by wingdagger** [comment]
> > ALTER TABLE to delete one or many rows brings the request down to < 100ms.
> 
> `ALTER TABLE ... settings mutations_sync=1;` or `ALTER TABLE ... settings mutations_sync=0;` ?

With mutations_sync=0, ALTER TABLE approach took an average of 89ms.  With mutations_sync=1, it took an average of 115ms.  This was averaged over 5 separate request for each setting, deleting 1000 rows each time.   I am using a single partition (no PARTITION definition specified in the schema definition).

**Comment by martinfdr** [comment]
> It may work, if you will do mutation in partition
> 
> Alter table xxx UPDATE _row_exists =0 IN PARTITION ID 'xxxx' WHERE ....

I tried what @UnamedRus recommended and it worked quite well, meaning it was much faster. However, I came to conclusion that using any kind of deletes, even lightweight deletes that deletes directly in partition is not only viable solution, it is dangerous.

Using this kind of deletes caused that ddl_distributed_queue got stuck with almost million unfinished deletes. Therefore any ON CLUSTER statements got stuck on top of this queue and thus making cluster management quite impossible. Only solution to fix stucked ddl_distributed_queue was to manipulate with zookeeper.

As far as deleting is concerned, we ended up using ReplacingMergeTree with `is_deleted` flag so deleting is basically reinserting same rows. Its not perfect but does not cause any damage

**Comment by d3ce1t** [comment]
In case it might help somebody. I was hitting this issue with lightweight deletes (LWD) as well. In my case, it affected only one table and the culprit was some pending mutations that never got completed (1 month old). After removing them, it started working again.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/67805
