### ISSUE TITLE
Clickhouse high Virtual Memory Size demand

### ISSUE THREAD

**Issue by sati-max** [ClickHouse/ClickHouse#59220]
Hi

We are using clickhouse in kubernetes setup (it's part of SigNoz solution for gathering logs+metrics from our servers) and I've noticed that the clickhouse pod has very high Virtual Memory Size demand, even if the pod itself isn't on any load.

The top command inside the pod:
1/ 
Mem: 11699536K used, 4604560K free, 9820K shrd, 844328K buff, 5943656K cached
CPU:   1% usr   1% sys   0% nic  95% idle   0% io   0% irq   1% sirq
Load average: 0.54 0.61 0.63 2/2278 887
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    7     1 root     S    **39.2g 235%**   4   1% /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
    1     0 root     S     394m   2%   4   0% {clckhouse-watch} clickhouse-watchdog        --config-file=/etc/clickhouse-server/config.xml
  886   880 root     S     2660   0%   2   0% /bin/bash

The same command inside other 2 separate environments that we are using (we have a total of 3 running SigNoz, so 3 running clickhouse databases pods we can compare):
2/ 
Mem: 13825272K used, 2481380K free, 9800K shrd, 284840K buff, 4332348K cached
CPU:   5% usr   1% sys   0% nic  90% idle   0% io   0% irq   1% sirq
Load average: 2.34 2.96 2.65 2/4267 1354
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    7     1 root     S    **44.2g 266%**   0   2% /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
    1     0 root     S     394m   2%   4   0% {clckhouse-watch} clickhouse-watchdog        --config-file=/etc/clickhouse-server/config.xml
 1353  1346 root     S     2660   0%   4   0% /bin/bash
 
3/ 
Mem: 13667532K used, 2639120K free, 9804K shrd, 284972K buff, 4376376K cached
CPU:   5% usr   1% sys   0% nic  91% idle   0% io   0% irq   1% sirq
Load average: 3.87 3.30 2.78 2/4269 2741
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    7     1 root     S    **48.6g 292%**   1   1% /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
    1     0 root     S     394m   2%   2   0% {clckhouse-watch} clickhouse-watchdog        --config-file=/etc/clickhouse-server/config.xml
 2630  2624 root     S     2660   0%   2   0% /bin/bash
 
The demand on VSZ is rather similar. And as you can notice "CPU and load average" on 1/ is low, where 2/ and 3/ have some load going on. 

All pods have pretty much default values when it comes to clickhouse settings (from what I read in SigNoz values.yaml file regarding clickhouse setup), the only thing we changed are timeouts (we doubled them - connect_timeout 10 -> 20; receive_timeout 300 -> 600, send_timeout 300->600). We also don't limit resources on pods as we are currently gathering info on cpu/ram usage and how we can scale this/how much resources we need as we are learning how things work (both SigNoz and K8s).

I can say that the 1/ pod gets almost no regular data as it's only used to verify if changes to our configuration (fluentbit, opentelemetry, parser, etc.) are correct before being applied to the other 2 environments (that receive logs and metrics on constant intervals from our servers so we weren't suspicious about their Virtual Memory Size being some sort of an "anomaly"). 

Is this situation "normal"? Is there a way to reduce the amount of Virtual Memory Size? (from Hyper-V it shows that k8s workers have sometimes around 200-300% RAM demand, even if their current usage is at about 50-60%):
![image](https://github.com/ClickHouse/ClickHouse/assets/47517196/5bcaaebb-c3ca-4a66-ac2c-d091d8e63c2c)

Thank you

clickhouse version in SigNoz is "clickhouse/clickhouse-server:23.11.1-alpine" (from SigNoz " SigNoz is not always tested with latest version of ClickHouse." so we aren't using :latest tags). 
I don't know if I need to provide any other informations. 

Or I should direct this to SigNoz development team if they aren't constantly running tasks from other pods that create such VSZ demand?

**Comment by alexey-milovidov** [comment]
It is ok to have a large virtual memory space. It should not be limited.
An attempt to limit the virtual memory size is either misconfiguration or misunderstanding.
