### ISSUE TITLE
Signal description: Segmentation fault

### ISSUE THREAD

**Issue by 12frame** [ClickHouse/ClickHouse#59246]
hello.
As long as the SQL is sorted and the order by new_mac_num is used, he will crash. if the order by new_mac_num is deleted, it can run normally.Another phenomenon is that if the partition key is changed to toYYYYMM, he can also run normally. The total amount of data added up to only 200000 data.

At present, I have not found a reproduction method in local tests. How to solve or avoid the same problem. I don't think executing SQL should cause the clickhouse service to crash directly.

```
select version();
23.7.4.5
```

sql:
```
SELECT report_date,
             openid,
             new_mac_num,
             active_mac_num,
             tow_retain_num,
             seven_retain_num,
             fifteen_retain_num,
             thirty_retain_num,
             new_user_num,
             active_user_num,
             amount
      FROM test.ads_dt
      WHERE report_date BETWEEN '2023-01-01' AND '2023-05-12'
ORDER BY new_mac_num DESC
LIMIT 2500,100
```

```
CREATE TABLE test.ads_dt
(
    `report_date` Date ,
    `openid` Int32 ,
    `new_mac_num` UInt32,
    `active_mac_num` UInt32 ,
    `tow_retain_num` UInt32 ,
    `seven_retain_num` UInt32 ,
    `fifteen_retain_num` UInt32,
    `thirty_retain_num` UInt32,
    `new_user_num` UInt32 ,
    `active_user_num` UInt32,
    `amount` UInt32
)
ENGINE = ReplicatedMergeTree()
    PARTITION BY toYYYYMM(report_date)
ORDER BY (report_date, openid);
```

2024.01.25 16:34:25.553100 [ 530 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.01.25 16:34:25.553148 [ 530 ] {} <Fatal> BaseDaemon: (version 23.7.4.5 (official build), build id: 48387A17E92306CEDAF0563064B4627E469728E7, git hash: bd2fcd445534e57cc5aa8c170cc25b7479b79c1c) (from thread 355) Received signal 11
2024.01.25 16:34:25.553184 [ 530 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.01.25 16:34:25.553196 [ 530 ] {} <Fatal> BaseDaemon: Address: 0x788000000b. Access: read. Address not mapped to object.
2024.01.25 16:34:25.553212 [ 530 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000001457cbe2 0x00000000155372d0 0x00000000114b3b30 0x00000000152c4532 0x00000000152de41a 0x00000000152d4f90 0x00000000152d6123 0x000000000ea0b78f 0x000000000ea0e4dc 0x000000000ea070cf 0x000000000ea0d0c1 0x00007fcbdd534609 0x00007fcbdd459133
2024.01.25 16:34:25.553223 [ 530 ] {} <Fatal> BaseDaemon: ########################################
2024.01.25 16:34:25.553237 [ 530 ] {} <Fatal> BaseDaemon: (version 23.7.4.5 (official build), build id: 48387A17E92306CEDAF0563064B4627E469728E7, git hash: bd2fcd445534e57cc5aa8c170cc25b7479b79c1c) (from thread 355) (query_id: 2b1d37cc-cbbf-4269-90d3-b2da4d03684b) (query: SELECT report_date,
             openid,
             new_mac_num,
             active_mac_num,
             tow_retain_num,
             seven_retain_num,
             fifteen_retain_num,
             thirty_retain_num,
             new_user_num,
             active_user_num,
             amount
      FROM test.ads_dt
      WHERE report_date BETWEEN '2023-01-01' AND '2023-05-12'
ORDER BY new_mac_num DESC
LIMIT 2500,100
FORMAT TabSeparatedWithNamesAndTypes;) Received signal Segmentation fault (11)
2024.01.25 16:34:25.553251 [ 530 ] {} <Fatal> BaseDaemon: Address: 0x788000000b. Access: read. Address not mapped to object.
2024.01.25 16:34:25.553260 [ 530 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000001457cbe2 0x00000000155372d0 0x00000000114b3b30 0x00000000152c4532 0x00000000152de41a 0x00000000152d4f90 0x00000000152d6123 0x000000000ea0b78f 0x000000000ea0e4dc 0x000000000ea070cf 0x000000000ea0d0c1 0x00007fcbdd534609 0x00007fcbdd459133
2024.01.25 16:34:25.553329 [ 530 ] {} <Fatal> BaseDaemon: 2. DB::ColumnSparse::compareColumn(DB::IColumn const&, unsigned long, DB::PODArray<unsigned long, 4096ul, Allocator<false, false>, 63ul, 64ul>*, DB::PODArray<signed char, 4096ul, Allocator<false, false>, 63ul, 64ul>&, int, int) const @ 0x000000001457cbe2 in /usr/bin/clickhouse
2024.01.25 16:34:25.553349 [ 530 ] {} <Fatal> BaseDaemon: 3. DB::PartialSortingTransform::transform(DB::Chunk&) @ 0x00000000155372d0 in /usr/bin/clickhouse
2024.01.25 16:34:25.553364 [ 530 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00000000114b3b30 in /usr/bin/clickhouse
2024.01.25 16:34:25.553379 [ 530 ] {} <Fatal> BaseDaemon: 5. DB::ISimpleTransform::work() @ 0x00000000152c4532 in /usr/bin/clickhouse
2024.01.25 16:34:25.553394 [ 530 ] {} <Fatal> BaseDaemon: 6. DB::ExecutionThreadContext::executeTask() @ 0x00000000152de41a in /usr/bin/clickhouse
2024.01.25 16:34:25.553408 [ 530 ] {} <Fatal> BaseDaemon: 7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000152d4f90 in /usr/bin/clickhouse
2024.01.25 16:34:25.553420 [ 530 ] {} <Fatal> BaseDaemon: 8. ? @ 0x00000000152d6123 in /usr/bin/clickhouse
2024.01.25 16:34:25.553437 [ 530 ] {} <Fatal> BaseDaemon: 9. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000ea0b78f in /usr/bin/clickhouse
2024.01.25 16:34:25.553468 [ 530 ] {} <Fatal> BaseDaemon: 10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000ea0e4dc in /usr/bin/clickhouse
2024.01.25 16:34:25.553490 [ 530 ] {} <Fatal> BaseDaemon: 11. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0x000000000ea070cf in /usr/bin/clickhouse
2024.01.25 16:34:25.553500 [ 530 ] {} <Fatal> BaseDaemon: 12. ? @ 0x000000000ea0d0c1 in /usr/bin/clickhouse
2024.01.25 16:34:25.553511 [ 530 ] {} <Fatal> BaseDaemon: 13. ? @ 0x00007fcbdd534609 in ?
2024.01.25 16:34:25.553529 [ 530 ] {} <Fatal> BaseDaemon: 14. clone @ 0x00007fcbdd459133 in ?
2024.01.25 16:34:25.734484 [ 530 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: CB35B33DE84FF1DE2248511132C190D7)
2024.01.25 16:34:25.734629 [ 530 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues

**Comment by antonio2368** [comment]
I cannot seem to reproduce the issue.
Also, the version is not supported so it would be good to update to a newer supported version.
