### ISSUE TITLE
23.3.5.9  null pointer

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#59249]
2024.01.26 10:41:01.508012 [ 70355 ] {} <Fatal> BaseDaemon: ########################################
2024.01.26 10:41:01.508110 [ 70355 ] {} <Fatal> BaseDaemon: (version 23.3.5.9 (official build), build id: 7CA499FE9E570E0D2AFBEFEF4DBAB9795D29687A) (from thread 69952) (no query) Received signal Segmentation fault (11)
2024.01.26 10:41:01.508146 [ 70355 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.01.26 10:41:01.508177 [ 70355 ] {} <Fatal> BaseDaemon: Stack trace: 0xe1c3cba 0xe1c36b7 0x183bfb46 0x183ccb4e 0x183cbb27 0x183ca903 0xe1c32b8 0xe1c2f6e 0xe1aebe2 0x1514aa3e 0x151482fb 0x12607a64 0x1263301a 0x1253e47e 0x139e8e3a 0x149cbbf5 0x149c3c6f 0x149da139 0x17920034 0x1792125b 0x17aa8ae7 0x17aa651d 0x7fc995c41b43 0x7fc995cd2bb4
2024.01.26 10:41:01.508234 [ 70355 ] {} <Fatal> BaseDaemon: 2. ? @ 0xe1c3cba in /usr/bin/clickhouse
2024.01.26 10:41:01.508253 [ 70355 ] {} <Fatal> BaseDaemon: 3. ? @ 0xe1c36b7 in /usr/bin/clickhouse
2024.01.26 10:41:01.508271 [ 70355 ] {} <Fatal> BaseDaemon: 4. ? @ 0x183bfb46 in /usr/bin/clickhouse
2024.01.26 10:41:01.508288 [ 70355 ] {} <Fatal> BaseDaemon: 5. ? @ 0x183ccb4e in /usr/bin/clickhouse
2024.01.26 10:41:01.508305 [ 70355 ] {} <Fatal> BaseDaemon: 6. ? @ 0x183cbb27 in /usr/bin/clickhouse
2024.01.26 10:41:01.508321 [ 70355 ] {} <Fatal> BaseDaemon: 7. ? @ 0x183ca903 in /usr/bin/clickhouse
2024.01.26 10:41:01.508355 [ 70355 ] {} <Fatal> BaseDaemon: 8. DB::CaresPTRResolver::wait_and_process() @ 0xe1c32b8 in /usr/bin/clickhouse
2024.01.26 10:41:01.508381 [ 70355 ] {} <Fatal> BaseDaemon: 9. DB::CaresPTRResolver::resolve(String const&) @ 0xe1c2f6e in /usr/bin/clickhouse
2024.01.26 10:41:01.508400 [ 70355 ] {} <Fatal> BaseDaemon: 10. ? @ 0xe1aebe2 in /usr/bin/clickhouse
2024.01.26 10:41:01.508420 [ 70355 ] {} <Fatal> BaseDaemon: 11. ? @ 0x1514aa3e in /usr/bin/clickhouse
2024.01.26 10:41:01.508437 [ 70355 ] {} <Fatal> BaseDaemon: 12. DB::AllowedClientHosts::contains(Poco::Net::IPAddress const&) const @ 0x151482fb in /usr/bin/clickhouse
2024.01.26 10:41:01.508459 [ 70355 ] {} <Fatal> BaseDaemon: 13. DB::IAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x12607a64 in /usr/bin/clickhouse
2024.01.26 10:41:01.508486 [ 70355 ] {} <Fatal> BaseDaemon: 14. DB::MultipleAccessStorage::authenticateImpl(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ExternalAuthenticators const&, bool, bool, bool) const @ 0x1263301a in /usr/bin/clickhouse
2024.01.26 10:41:01.508525 [ 70355 ] {} <Fatal> BaseDaemon: 15. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&) const @ 0x1253e47e in /usr/bin/clickhouse
2024.01.26 10:41:01.508562 [ 70355 ] {} <Fatal> BaseDaemon: 16. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x139e8e3a in /usr/bin/clickhouse
2024.01.26 10:41:01.508587 [ 70355 ] {} <Fatal> BaseDaemon: 17. DB::TCPHandler::receiveHello() @ 0x149cbbf5 in /usr/bin/clickhouse
2024.01.26 10:41:01.508602 [ 70355 ] {} <Fatal> BaseDaemon: 18. DB::TCPHandler::runImpl() @ 0x149c3c6f in /usr/bin/clickhouse
2024.01.26 10:41:01.508618 [ 70355 ] {} <Fatal> BaseDaemon: 19. DB::TCPHandler::run() @ 0x149da139 in /usr/bin/clickhouse
2024.01.26 10:41:01.508637 [ 70355 ] {} <Fatal> BaseDaemon: 20. Poco::Net::TCPServerConnection::start() @ 0x17920034 in /usr/bin/clickhouse
2024.01.26 10:41:01.508661 [ 70355 ] {} <Fatal> BaseDaemon: 21. Poco::Net::TCPServerDispatcher::run() @ 0x1792125b in /usr/bin/clickhouse
2024.01.26 10:41:01.508679 [ 70355 ] {} <Fatal> BaseDaemon: 22. Poco::PooledThread::run() @ 0x17aa8ae7 in /usr/bin/clickhouse
2024.01.26 10:41:01.508696 [ 70355 ] {} <Fatal> BaseDaemon: 23. Poco::ThreadImpl::runnableEntry(void*) @ 0x17aa651d in /usr/bin/clickhouse
2024.01.26 10:41:01.508716 [ 70355 ] {} <Fatal> BaseDaemon: 24. ? @ 0x7fc995c41b43 in ?
2024.01.26 10:41:01.508732 [ 70355 ] {} <Fatal> BaseDaemon: 25. __clone @ 0x7fc995cd2bb4 in ?
2024.01.26 10:41:01.703968 [ 70355 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 249E8ED50934123C2CAB9D96C5619C42)
2024.01.26 10:41:01.704218 [ 70355 ] {} <Information> SentryWriter: Not sending crash report

**Comment by Algunenano** [comment]
Duplicate from https://github.com/ClickHouse/ClickHouse/issues/53500. Please update
