### ISSUE TITLE
Can I only grant privilege to VIEW tables but not to DISTRIBUTED/MERGETREE tables

### ISSUE THREAD

**Issue by caoyang10** [ClickHouse/ClickHouse#59250]
Example:
create table tb (id String) engine = MergeTree() partition by tuple() order by tuple();
create view tb_view as select * from tb;
create user test_user;
grant select on tb_view to test_user;
------- use test_user to login ------
 select * from tb_view
------- exceptions -------
Received exception from server (version 23.12.2):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: test_user: Not enough privileges. To execute this query, it's necessary to have the grant SELECT(id) ON default.tb. (ACCESS_DENIED)

I want to create an user which can select from tb_view and can't from tb.
What can I do on this situation?

**Comment by UnamedRus** [comment]
It's called DEFINERS https://github.com/ClickHouse/ClickHouse/issues/49849

**Comment by caoyang10** [comment]
> It's called DEFINERS #49849

Thank you! Hope it can work recently.
