### ISSUE TITLE
Port is not opened on keepers only using composable protocols

### ISSUE THREAD

**Issue by ilyatrefilov** [ClickHouse/ClickHouse#59251]
**Description**
When using the composable protocols configuration for serving prometheus metrics with tls, clickhouse server with only keeper configuration does not open specified port.

**How to reproduce**
* Clickhouse version 23.3.19.32

To reproduce the issue two nodes should be deployed, one as "data" node and the other one as a keeper.
Example config:
```xml
<remote_servers>
<example>
  <shard>
    <internal_replication>true</internal_replication>
    <replica>
      <host>data-node.example.com</host>
      <port>9000</port>
      <secure>true</secure>
    </replica>
  </shard>
</example>
</remote_servers>

<keeper_server>
  <server_id>1</server_id>
  <tcp_port_secure>2181</tcp_port_secure>
  <raft_configuration>
      <secure>true</secure>

      <server>
          <id>1</id>
          <hostname>keeper-node.example.com</hostname>
          <port>2182</port>
      </server>
  </raft_configuration>
</keeper_server>


```

In both configs I do specify prometheus metrics endpoint using composable protocols following explanation given in this issue #49003:
```xml
<prometheus>
  <endpoint>/metrics</endpoint>
  <metrics>true</metrics>
  <events>true</events>
  <asynchronous_metrics>true</asynchronous_metrics>
</prometheus>

<protocols>
  <prometheus_protocol>
      <type>prometheus</type>
      <description>prometheus protocol</description>
  </prometheus_protocol>

  <prometheus_secure>
      <type>tls</type>
      <impl>prometheus_protocol</impl>
      <port>9999</port>
      <description>prometheus over tls</description>
  </prometheus_secure>
</protocols>

```

**Expected behavior**
Port 9999 is opened on both "data" node and keeper node and is under TLS.

**Actual behavior**
Port 9999 is only opened on the "data" and not the keeper node.

**Logs**
There were no messages in log with a mention of this prometheus configuration, checked it on trace level.

**Comment by antonio2368** [comment]
Keeper currently doesn't support composable protocols so the "old" way should be used of specifying `<port>` under `<prometheus>`.

**Comment by ilyatrefilov** [comment]
@antonio2368 Thank you for the clarification on this point.
Is there any chance of composable protocols support on keepers in near future or it's better to look for workaround in long term?
Seems like there is no out-of-box solutions left to collect metrics in secure way.

**Comment by antonio2368** [comment]
@ilyatrefilov I can't promise you anything specific but I think it should be done in the near future along with some small changes to Keeper prometheus metrics (send only Keeper specific data).

I'll close this issue for now and ping you when there is update for it.
