### ISSUE TITLE
Replicas are not recognised as local leading to failing ddl queries

### ISSUE THREAD

**Issue by pomo-mondreganto** [ClickHouse/ClickHouse#59279]
We're using `ClickHouse server version 23.8.2.7 (official build)` on a cluster of 5 nodes. The cluster is set up in config.xml the following way:

```xml
        <jaeger>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>jaeger</default_database>
                    <host>3d-dm-db1</host>

                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>jaeger</default_database>
                    <host>3d-dm-db2</host>

                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>jaeger</default_database>
                    <host>3d-dm-db3</host>

                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>jaeger</default_database>
                    <host>3d-dm-db4</host>

                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>jaeger</default_database>
                    <host>3d-dm-db5</host>

                    <port>9000</port>
                </replica>
            </shard>
        </jaeger>
```

`/etc/hosts` has the following line (on `3d-dm-db1`):
```
127.0.1.1 3d-dm-db1
```

However, the `3d-dm-db1` shard of `jaeger` cluster is not recognised as local, so ddl queries don't work:
```
SELECT
    cluster,
    shard_num,
    host_name,
    host_address,
    is_local
FROM system.clusters
WHERE cluster = 'jaeger'

Query id: da1f03d0-2282-4145-8f24-e16384c24984

┌─cluster─┬─shard_num─┬─host_name─┬─host_address──┬─is_local─┐
│ jaeger  │         1 │ 3d-dm-db1 │ 127.0.1.1     │        0 │
│ jaeger  │         2 │ 3d-dm-db2 │ 192.168.42.40 │        0 │
│ jaeger  │         3 │ 3d-dm-db3 │ 192.168.42.41 │        0 │
│ jaeger  │         4 │ 3d-dm-db4 │ 192.168.42.42 │        0 │
│ jaeger  │         5 │ 3d-dm-db5 │ 192.168.42.43 │        0 │
└─────────┴───────────┴───────────┴───────────────┴──────────┘
```

I've seen a (fixed, but nevertheless) issue when 127.0.1.1 is not recognised as the local address, so I've tried replacing 127.0.1.1 with the external IP of the host (`192.168.42.39`), but got the same result. After changing `/etc/hosts` I restart the `clickhouse-server` service.

**Comment by pomo-mondreganto** [comment]
The DDL fails with the classic "There are N unfinished hosts (0 of them are currently active)", so I'm following the troubleshoot guide from here: https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-ddlworker/there-are-n-unfinished-hosts-0-of-them-are-currently-active/

The very first reason (Clickhouse node can’t recognize itself) happens to be my case.

**Comment by pomo-mondreganto** [comment]
Got a hint that the default_database shouldn't be set for the replica to be recognised as local. Removing default_database fixed the issue for me.

**Comment by 1212mohamedtaha** [comment]
I have the same issue and I have the first reason as this link also https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-ddlworker/there-are-n-unfinished-hosts-0-of-them-are-currently-active/
But the issue wasn't solved. I also didn't setup default databases for replicas.
How did you solve this?
