### ISSUE TITLE
Support accept_invalid_certificate in client's config

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#59278]
**Describe the issue**

`clickhouse-client` has `--accept-invalid-certificate`, but you cannot specify it in config, there you have to write complex things - https://github.com/ClickHouse/ClickHouse/blob/6c5057c4f2bd7400eb9a6dbc9e072d208fdf4ad3/programs/client/Client.cpp#L1179-L1180

It will be nice to support `accept_invalid_certificate` shortcut there as well.

Also it will be good to support it on a per-connection basis - `connections_credentials` (https://github.com/ClickHouse/ClickHouse/pull/55949).

That way you can specify it for some development hosts and do not set it globally.

Cc: @chhetripradeep

**Comment by peacewalker122** [comment]
Hi @azat. Would love to give my first contribution.

**Comment by azat** [comment]
Sure, please do!

**Comment by peacewalker122** [comment]
HI @azat, since i'm newbie with the codebase and during the development process i got difficulties to start my first contribution and so by that, could you give me some guide to starting the development. Thanks

**Comment by azat** [comment]
Right now there is already option `--accept-invalid-certificate`:

https://github.com/ClickHouse/ClickHouse/blob/6c5057c4f2bd7400eb9a6dbc9e072d208fdf4ad3/programs/client/Client.cpp#L1034

https://github.com/ClickHouse/ClickHouse/blob/6c5057c4f2bd7400eb9a6dbc9e072d208fdf4ad3/programs/client/Client.cpp#L1177-L1181

But you cannot specify it in config

It should be enough to write something like this instead:

```c
    if (options.count("accept-invalid-certificate") || config().has("accept-invalid-certificate"))
    {
        config().setString("openSSL.client.invalidCertificateHandler.name", "AcceptCertificateHandler");
        config().setString("openSSL.client.verificationMode", "none");
    }
```

And also don't forget to write a test, you can take a look at as an example - `tests/queries/0_stateless/01889_clickhouse_client_config_format.sh`

This is the first part of the issue.

The second part is to handle `accept-invalid-certificate` on a per-credential basis, here - https://github.com/ClickHouse/ClickHouse/blob/6c5057c4f2bd7400eb9a6dbc9e072d208fdf4ad3/programs/client/Client.cpp#L132

After please add a test case to `tests/queries/0_stateless/02550_client_connections_credentials.sh`
