### ISSUE TITLE
dictGet*: dict_name & attr_name have not to be a constants

### ISSUE THREAD

**Issue by temoon** [ClickHouse/ClickHouse#5931]
Functions for external dictionaries like dictGet* accepts constants as 1st and 2nd argument. And there is no way to build, for example, dictionary name from value of query field.

Example:
```
SELECT DISTINCT dictGetUInt64(concat('mydict_', toString(application_id)), 'myid', tuple(user_id))
FROM events 

Received exception from server (version 19.9.2):
Code: 44. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Argument at index 0 for function dictGetUInt64 must be constant.
```

I have a huge dictionary and splitted it by application_id to few smaller dicts.

**Comment by alexey-milovidov** [comment]
That's not easy to fix. These arguments are expected to be constants to call dictionary functions in a batch fashion.

Instead of using multiple dictionaries sharded by `application_id`, I recommend to use single dictionary with `application_id` as the first column of complex key.
