### ISSUE TITLE
On Redhat 7.5 not able to start Clickhouse as a service.

### ISSUE THREAD

**Issue by projectsbird123** [ClickHouse/ClickHouse#5932]
Hi,
I have tried starting the clickhouse-server as a service on the Redhat OS 7.5, but it is not started.

Used commands to start:
service clickhouse-server start

After this command there is no error. When checked the status using the below command:
systemctl status clickhouse-server

it displays as:
systemctl status clickhouse-server
clickhouse-server.service - ClickHouse Server (analytic DBMS for big data)
Loaded: loaded (/etc/systemd/system/clickhouse-server.service; disabled; vendor preset: disabled)
Active: failed (Result: exit-code) since Mon 2019-07-08 19:36:24 +08; 54min ago
Process: 23939 ExecStart=/etc/init.d/clickhouse-server --config=/etc/clickhouse-server/config.xml (code=exited, status=2)
Main PID: 23939 (code=exited, status=2)

Jul 08 19:35:12 Redhat systemd[1]: Started ClickHouse Server (analytic DBMS for big data).
Jul 08 19:35:12 Redhat systemd[1]: Starting ClickHouse Server (analytic DBMS for big data)...
Jul 08 19:35:12 Redhat clickhouse-server[23146]: Usage: /etc/init.d/clickhouse-server {start|stop|status|restart|forcestop|forcerestart...initdb}
Jul 08 19:35:12 Redhat systemd[1]: clickhouse-server.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 08 19:35:12 Redhat systemd[1]: Unit clickhouse-server.service entered failed state.
Jul 08 19:35:12 Redhat systemd[1]: clickhouse-server.service failed

**Comment by projectsbird123** [comment]
I'm able to run the ClickHouse using the below command but not as a service.

Command used to run the clickhouse:
clickhouse-server --config-file=/etc/clickhouse-server/config.xml

**Comment by filimonov** [comment]
After an unsuccessful run attempt can you see any errors/warnings at the end of `/var/log/clickhouse-server/clickhouse-server.log`?

**Comment by projectsbird123** [comment]
When we started the clickhouse as a service we found this error.
ERROR:
<Error> Application: DNS error: EAI: -9
After this we have the updated the config.xml, by commenting "" and un-commented  <listen_host>0.0.0.0</listen_host>. 

Again started the clickhouse-server as a service, but there are no logs generated.

**Comment by champtar** [comment]
@projectsbird123 is IPv6 disable on your RHEL 7.5 ?

**Comment by filimonov** [comment]
> Again started the clickhouse-server as a service and clickhouse not started, also there are no logs generated. 

Nothing at all? /var/log/clickhouse-server/clickhouse-server.log should speak a lot unless you disable logging in config.xml. 

Does the clickhouse appears in processlist?

**Comment by projectsbird123** [comment]
@filimonov Nothing is printed on the logs.

**Comment by filimonov** [comment]
Not enough information here to diagnose, seems related to very old version or some local issues. 

Clickhouse just works on Centos / RedHat, and there is official repo with rpm packages.
