### ISSUE TITLE
Is `IO prefertch` the typo error in metrics.md and CurrentMetrics.cpp

### ISSUE THREAD

**Issue by CzyerChen** [ClickHouse/ClickHouse#59320]
When I learning system metrics about ClickHouse in `ClickHouse/src/Common
/CurrentMetrics.cpp` and `docs/en/operations/system-tables/metrics.md`,  the desc of the metric `IOPrefetchThreads, "Number of threads in the IO prefertch thread pool."`, Is `prefertch` a typo error?

`M(IOPrefetchThreads, "Number of threads in the IO prefertch thread pool.") \`
`### IOPrefetchThreads
Number of threads in the IO prefertch thread pool.`

**Comment by Algunenano** [comment]
Yes it is
