### ISSUE TITLE
Set timeout at query or client level for `INSERT` queries

### ISSUE THREAD

**Issue by mkaze** [ClickHouse/ClickHouse#59323]
Is there any way to set a timeout for `INSERT` queries, such that there would be a guarantee that the data has not been inserted if the timeout passes?

I looked for this in the documentation and came across settings like `receive_timeout` or `max_execution_time`, however it was not clear if these settings would imply that the insertion has not happened.

**Comment by Algunenano** [comment]
> Is there any way to set a timeout for INSERT queries, such that there would be a guarantee that the data has not been inserted if the timeout passes?

No there isn't. You can set `max_execution_time` but the data that has already been inserted when the timeout is reached won't be discarded.

**Comment by mkaze** [comment]
Thanks @Algunenano. Is `max_execution_time` enforced for `INSERT` queries? Because the documentation is not clear about this:

https://clickhouse.com/docs/en/operations/settings/query-complexity

> Restrictions on query complexity are part of the settings. They are used to provide safer execution from the user interface. **Almost all the restrictions only apply to SELECT.**

**Comment by Algunenano** [comment]
Yes, it is enforced (with the same limitations as SELECT, where timeouts are only checked between blocks, they aren't hard limits).

```
CREATE TABLE t
(
    `a` Int64
)
ENGINE = MergeTree
ORDER BY a

Query id: 5434829a-6f6a-415c-88da-cd0cea976cb4

Ok.

0 rows in set. Elapsed: 0.079 sec. 

:) insert into t Select sleepEachRow(0.1) from numbers(10) settings max_execution_time=0.5;

INSERT INTO t
SETTINGS max_execution_time = 0.5
SELECT sleepEachRow(0.1)
FROM numbers(10)
SETTINGS max_execution_time = 0.5

Query id: e4406bd2-2b04-4817-848f-61e0ac4d1a58

→ Progress: 10.00 rows, 80.00 B (99.28 rows/s., 794.22 B/s.)  99%
Elapsed: 1.012 sec. 

Received exception:
Code: 159. DB::Exception: Timeout exceeded: elapsed 1.003158852 seconds, maximum: 0.5. (TIMEOUT_EXCEEDED)
```
