### ISSUE TITLE
Cannot extract table structure from Parquet format file when sepcifying compression without `output_format_parquet_compression_method`

### ISSUE THREAD

**Issue by Selfeer** [ClickHouse/ClickHouse#59330]
Whenever I create a parquet file from a ClickHouse table via `INTO OUTFILE`, if I specify a `COMPRESSION` value I'm not able to read from the created file and I get the following error:

```
Code: 636. DB::Exception: Cannot extract table structure from Parquet format file. Error: std::exception. Code: 1001, type: parquet::ParquetInvalidOrCorruptedFileException, e.what() = Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file. (version 24.1.1.1343 (official build)). You can specify the structure manually 
```
**Steps to reproduce**

1. Create a table in ClickHouse and populate it with some values
```sql
CREATE TABLE users (uid Int16, name String, age Int16) ENGINE=Memory;

INSERT INTO users VALUES (1231, 'John', 33);
INSERT INTO users VALUES (6666, 'Ksenia', 48);
INSERT INTO users VALUES (8888, 'Alice', 50);
```
2. Create a parquet file from the given table

```sql
SELECT * FROM users INTO OUTFILE 'file_with_lz4_compression.Parquet' COMPRESSION 'lz4'  FORMAT Parquet
``` 
3. Try to select data from this file

```sql
SELECT * FROM file('file_with_lz4_compression.Parquet')
```

**Expected Result**
Selected data from the file is displayed correctly, no errors are shown.

**Actual Result**
The error is shown:

```
Code: 636. DB::Exception: Cannot extract table structure from Parquet format file. Error: std::exception. Code: 1001, type: parquet::ParquetInvalidOrCorruptedFileException, e.what() = Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file. (version 24.1.1.1343 (official build)). You can specify the structure manually 
```

**Additional context**
I do understand that there is a specific `output_format_parquet_compression_method` setting and we can specify the compression like

```sql
SELECT * FROM users INTO OUTFILE 'file_with_lz4_compression_setting.Parquet' FORMAT Parquet SETTINGS output_format_parquet_compression_method='lz4'
```
But in the documentation it seems unclear that usage of `COMPRESSION` will result in an error: https://clickhouse.com/docs/en/integrations/data-formats/parquet#exporting-to-parquet-format

> To export any table or query result to the Parquet file, we can use an INTO OUTFILE clause:
> 
> ```sql
> SELECT *
> FROM sometable
> INTO OUTFILE 'export.parquet'
> FORMAT Parquet
> ```
> This will create the export.parquet file in a working directory.

**Comment by alexey-milovidov** [comment]
When applying an external compression on top of a parquet file, it should be named `.parquet.lz4`
