### ISSUE TITLE
Not possible to delete data from "MATERIALIZED VIEW" if an UPDATE has previously been made.

### ISSUE THREAD

**Issue by ghostiam** [ClickHouse/ClickHouse#59346]
> A clear and concise description of what works not as it is supposed to.

If you try to update data in MV by table name, nothing will happen (unlike updating by UUID, where an error will be thrown).
However, this will break the ability to delete data from MV using `ALTER TABLE DELETE`

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

With update:
https://fiddle.clickhouse.com/b7483127-7f03-48b1-a191-224f5ee24286

Without:
https://fiddle.clickhouse.com/4c9aaa5f-4e73-46ac-90da-a46b23a59090

**Does it reproduce on recent release?**

Yes.

```
# clickhouse-server --version
ClickHouse server version 23.12.2.59 (official build).
```

**How to reproduce**

<details><summary>Details</summary>
<p>

Create tables and insert test data.

```sql
CREATE TABLE prices (
    timestamp DateTime,
    price_id  UInt32
)
    ENGINE = MergeTree()
        PARTITION BY toYYYYMM(timestamp)
        ORDER BY (timestamp, price_id);


CREATE MATERIALIZED VIEW IF NOT EXISTS prices_ids UUID 'a9b6cfc8-7145-4dfb-ad61-4bfd7393583b'
            ENGINE = AggregatingMergeTree()
                PARTITION BY toYYYYMM(timestamp_hour)
                ORDER BY (timestamp_hour, price_id)
AS
SELECT toStartOfInterval(timestamp, INTERVAL 1 HOUR) AS timestamp_hour
     , price_id
FROM prices
GROUP BY timestamp_hour, price_id;

INSERT
INTO prices (timestamp, price_id)
VALUES ('2020-01-01 00:00:00', 1);

INSERT
INTO prices (timestamp, price_id)
VALUES ('2020-01-01 00:00:00', 2);

INSERT
INTO prices (timestamp, price_id)
VALUES ('2020-01-01 00:00:00', 3);
```

Try update (no error will be thrown, but the row will not be updated)

```sql
ALTER
TABLE
prices_ids
UPDATE price_id = 1
WHERE price_id = 3;

-- Check
SELECT price_id, count()
FROM prices_ids
GROUP BY price_id
ORDER BY price_id;
```

Try delete (even if you skip the UPDATE, you will still need 2 queries to delete the data)

```sql
ALTER
TABLE
prices_ids
DELETE
WHERE price_id = 3;

ALTER
TABLE
`.inner_id.a9b6cfc8-7145-4dfb-ad61-4bfd7393583b`
DELETE
WHERE price_id = 3;

-- Check
SELECT price_id, count()
FROM prices_ids
GROUP BY price_id
ORDER BY price_id;
```

</p>
</details> 

**Expected behavior**

Error when calling UPDATE on the MV name (as done with UUID) and the ability to delete using one DELETE statement, rather than two with different table names.

**Additional context**

There may even be 2 bugs in one, since deleting from an MV can only be done if you complete 2 deletion queries by MV name and UUID.
If you do only one query, the deletion will not occur.

https://fiddle.clickhouse.com/4c9aaa5f-4e73-46ac-90da-a46b23a59090

**Comment by tavplubix** [comment]
It's because the ALTER UPDATE query is wrong: 
```Code: 420. DB::Exception: Cannot UPDATE key column `price_id`. (CANNOT_UPDATE_COLUMN)```
https://fiddle.clickhouse.com/f957a7e4-9c88-41a6-bc7b-4582d5c5a3ef
Also, updates and deletes are asynchronous, see `mutations_sync` setting

**Comment by ghostiam** [comment]
@tavplubix, I understand that the query is not valid, but it breaks the deletion and doesn't output any error.
Also, when querying via UUID, we immediately get an error, but in the case of a request by name, there is no error.

And how to get out of this case? 
Now if we try to update a record, it won’t be possible to delete it even after a few hours and you just have to recreate the view, which may not be possible when there is a lot of data in it.

I understand that changing data in Clickhouse is a bad idea and this was revealed in a dev environment, but someone can run this in production.

**Comment by tavplubix** [comment]
@ghostiam see `mutations_sync` setting and `KILL MUTATION` query.
