### ISSUE TITLE
Refreshable  views can fail with a FATAL error that crashes server

### ISSUE THREAD

**Issue by acmeguy** [ClickHouse/ClickHouse#59369]
**Describe the unexpected behaviour**
Refreshable views will fail with a fatal error if not correctly created.

**How to reproduce**
Create an invalid refreshable view with nothing after the "AS" keyword. 
(This is at least what I think happened, accidentally)

* 23.12-alpine

**Expected behavior**
cron jobs need to be run in a sandbox without the ability for them to take down the server.
Syntax checking should have failed

**Error message and/or stacktrace**
Please help!
I was trying out the refresh views on my server and now it crashes as soon as it's up. (CREATE MATERIALIZED VIEW IF NOT EXISTS x ON CLUSTER default REFRESH EVERY 1 MINUTE TO y AS)
I find nothing active in the system.mutations table and I do not know how to stop this.
These are the only log entries that may possibly related to this:
<Fatal> BaseDaemon: ########## Short fault info ############
<Fatal> BaseDaemon: (version 23.12.2.59 (official build), build id: 7F4C1A822F9C67A4D137A58F9A95BD4B0F1B6A8A, git hash: 17ab210e76170917215be8cc3ae07d465a341d42) (from thread 858) Received signal 11
<Fatal> BaseDaemon: Signal description: Segmentation fault
<Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
<Fatal> BaseDaemon: Stack trace: 0x00007f8a61cd8941 0x0000000016eacf24 0x0000000016eca40d 0x000000000c9786e8 0x0000000012de0bb3 0x0000000012e083e7 0x0000000012eb2a92 0x00000000109cab4d 0x00000000109dd644 0x00000000109e1117 0x00000000109d847e 0x00000000109ef28c 0x000000000c7c00d8 0x00007f8a61eb0609 0x00007f8a61dd5353
<Fatal> BaseDaemon: ########################################
<Fatal> BaseDaemon: (version 23.12.2.59 (official build), build id: 7F4C1A822F9C67A4D137A58F9A95BD4B0F1B6A8A, git hash: 17ab210e76170917215be8cc3ae07d465a341d42) (from thread 858) (no query) Received signal Segmentation fault (11)
Tue, Jan 30 2024 7:44:17 am
<Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
<Fatal> BaseDaemon: Stack trace: 0x00007f8a61cd8941 0x0000000016eacf24 0x0000000016eca40d 0x000000000c9786e8 0x0000000012de0bb3 0x0000000012e083e7 0x0000000012eb2a92 0x00000000109cab4d 0x00000000109dd644 0x00000000109e1117 0x00000000109d847e 0x00000000109ef28c 0x000000000c7c00d8 0x00007f8a61eb0609 0x00007f8a61dd5353
<Fatal> BaseDaemon: 2. ? @ 0x00007f8a61cd8941 in ?
<Fatal> BaseDaemon: 3. ? @ 0x0000000016eacf24 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 4. ? @ 0x0000000016eca40d in /usr/bin/clickhouse
<Fatal> BaseDaemon: 5. DB::IAST::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x000000000c9786e8 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 6. DB::ASTCreateQuery::formatQueryImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x0000000012de0bb3 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 7. DB::ASTQueryWithOutput::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x0000000012e083e7 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 8. DB::serializeAST(DB::IAST const&) @ 0x0000000012eb2a92 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 9. DB::DDLTaskBase::formatRewrittenQuery(std::shared_ptr<DB::Context const>) @ 0x00000000109cab4d in /usr/bin/clickhouse
<Fatal> BaseDaemon: 10. DB::DDLWorker::initAndCheckTask(String const&, String&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x00000000109dd644 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 11. DB::DDLWorker::scheduleTasks(bool) @ 0x00000000109e1117 in /usr/bin/clickhouse
<Fatal> BaseDaemon: 12. DB::DDLWorker::runMainThread() @ 0x00000000109d847e in /usr/bin/clickhouse
<Fatal> BaseDaemon: 13. void std::__function::__policy_invok (edited)

**Comment by evillique** [comment]
Query fails on 23.12-alpine with SYNTAX_ERROR as expected: https://fiddle.clickhouse.com/84d4c256-9359-42e1-b3aa-e1984fc9be5d.

Are you sure this is the query it tries to execute in DDLWorker? If it is possible the exact query it tries to execute (you can look at the task task in ZooKeeper even without starting ClickHouse) would be very helpful.

**Comment by eheu** [comment]
We ran into this problem last week.

It can happen if you create a refreshable materialized view using replicated database or table engines.
You can connect your (zoo)keeper client and try remove the faulty statement in `/clickhouse/task_queue/ddl/...`. Alternatively, you can downgrade Clickhouse to 23.11.

With https://github.com/ClickHouse/ClickHouse/pull/58934, ClickHouse will handle this by preventing the creation on replicated database or table engines.

**Comment by al13n321** [comment]
CREATE was supposed to refuse creating refreshable MVs in Replicated databases, but this check was broken and allowed it, sorry. Fix in https://github.com/ClickHouse/ClickHouse/pull/58934 or https://github.com/ClickHouse/ClickHouse/pull/59743 , actual support for Replicated databases coming soon.

**Comment by nikitamikhaylov** [comment]
For now it no longer possible to create a Refreshable MV in the Replicated database. The proper support for this engine will come soon, stay tuned.
