### ISSUE TITLE
Hash functions used in BloomFilter are not independent

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#59378]
As per wikipedia for [bloom filter](https://en.wikipedia.org/wiki/Bloom_filter#:~:text=The%20requirement%20of%20designing%20k%20different%20independent%20hash%20functions%20can%20be%20prohibitive%20for%20large%20k) says (emphasis on me):

> The requirement of designing k different **independent** hash functions can be prohibitive for large k. For a good hash function with a wide output, there should be little if any correlation between different bit-fields of such a hash, so this type of hash can be used to generate multiple "different" hash functions by slicing its output into multiple bit fields. **Alternatively, one can pass k different initial values (such as 0, 1, ..., k − 1) to a hash function that takes an initial value; or add (or append) these values to the key**. For larger m and/or k, independence among the hash functions can be relaxed with negligible increase in false positive rate.[[3]](https://en.wikipedia.org/wiki/Bloom_filter#cite_note-3) (Specifically, [Dillinger & Manolios (2004b)](https://en.wikipedia.org/wiki/Bloom_filter#CITEREFDillingerManolios2004b) show the effectiveness of deriving the k indices using [enhanced double hashing](https://en.wikipedia.org/wiki/Double_hashing#Enhanced_double_hashing) and [triple hashing](https://en.wikipedia.org/wiki/Double_hashing#triple_hashing), variants of [double hashing](https://en.wikipedia.org/wiki/Double_hashing) that are effectively simple random number generators seeded with the two or three hash values.)

The set of hash functions used for bloom filter should be different. But [here](https://github.com/ClickHouse/ClickHouse/blob/fd959f0bd213a8c5ad8a3779e49407d06f2cf218/src/Interpreters/BloomFilter.cpp#L69-L79) the third hash function and later ones are linearly related to the first and second hash value:
![image](https://github.com/ClickHouse/ClickHouse/assets/50256182/aa74ca68-cf75-4c67-b4ec-144a362e6912)

Thus, I think, increasing the number of hash functions more than 2 may not reduce the false positive rate of the BloomFilter.

**Comment by UnamedRus** [comment]
On a minor topic, but ClickHouse version of CityHash64, can be not that good option, as it have higher chance of correlation than it should have for 64 bit function.

**Comment by cangyin** [comment]
I found this [Kirsch-Mitzenmacher-Optimization](https://www.eecs.harvard.edu/~michaelm/postscripts/tr-02-05.pdf)
