### ISSUE TITLE
The merge function doesn't work with a subquery.

### ISSUE THREAD

**Issue by alps99w** [ClickHouse/ClickHouse#59401]
CH version 23.8-LTS

1. create a local table on 7 servers. 
`CREATE TABLE default.test_local
(
    `name` String,
    `date` Date,
    `sign` Int8
)
ENGINE = CollapsingMergeTree(sign)
PARTITION BY date
ORDER BY name
SETTINGS index_granularity = 8192`

2. create a distributed table on sc-ch-301. 
` CREATE TABLE default.test_distributed
(
    `name` String,
    `date` Date,
    `sign` Int8
)
ENGINE = Distributed('ranking_shard', 'default', 'test_local', rand64()) `

3. insert dummy data (11 records in total)
      `SELECT
          *,
          hostName()
      FROM default.test_distributed
      Query id: a0079deb-8bf6-428a-9ac6-de39d67e3aea
      
      ┌─name─┬───────date─┬─sign─┬─hostName()─┐
      │ 11   │ 2024-01-11 │    1 │ sc-ch-307 │
      │ 3    │ 2024-01-03 │    1 │ sc-ch-305 │
      │ 8    │ 2024-01-08 │    1 │ sc-ch-304 │
      │ 2    │ 2024-01-02 │    1 │ sc-ch-306 │
      │ 10   │ 2024-01-10 │    1 │ sc-ch-301 │
      │ 5    │ 2024-01-05 │    1 │ sc-ch-303 │
      │ 4    │ 2024-01-04 │    1 │ sc-ch-304 │
      │ 6    │ 2024-01-06 │    1 │ sc-ch-305 │
      │ 7    │ 2024-01-07 │    1 │ sc-ch-306 │
      │ 1    │ 2024-01-01 │    1 │ sc-ch-307 │
      │ 9    │ 2024-01-09 │    1 │ sc-ch-307 │
      └──────┴────────────┴──────┴────────────┘
      11 rows in set. Elapsed: 0.057 sec. `

4. We get the correct results when executing the query below.
`SELECT count()
FROM default.test_distributed
WHERE name GLOBAL IN (
    SELECT name
    FROM default.test_distributed
)

Query id: a7c24d60-ba27-4f08-8a0a-5a8b3a38d272

┌─count()─┐
│      11 │
└─────────┘`

but if we change the table name to use the merge function, it shows an incorrect result. 
`SELECT count()
FROM merge('default', '^test_distributed$')
WHERE name GLOBAL IN (
    SELECT name
    FROM default.test_distributed
)

Query id: 36f23bdc-b4ab-4bac-8db8-9494bc010732

┌─count()─┐
│      10 │
└─────────┘`

**Comment by Avogar** [comment]
Looks similar to https://github.com/ClickHouse/ClickHouse/issues/56790. What exact version are you using?

**Comment by alps99w** [comment]
> Looks similar to #56790. What exact version are you using?

Maybe only a part of the issue got fixed, but when using a merge function, the problem still persists.

**Comment by alps99w** [comment]
change to prewhere fixed the issue.  so it could be related to https://github.com/ClickHouse/ClickHouse/issues/51846

**Comment by alsugiliazova** [comment]
I reproduced this example, it works correctly on versions prior to 23.6 and on 24.2 (I have checked versions from 23.1 to 24.2). From 23.6 to 24.1 it shows an incorrect result (described in this [comment](https://github.com/ClickHouse/ClickHouse/issues/59401#issuecomment-1917769778)). I used official Clickhouse builds.

**Comment by filimonov** [comment]
I also have a repro:

```
DROP TABLE IF EXISTS default.test_local ON CLUSTER '{cluster}';
DROP TABLE IF EXISTS default.test_distributed ON CLUSTER '{cluster}';

CREATE TABLE default.test_local ON CLUSTER '{cluster}' 
( name String,date Date,sign Int8 ) 
ENGINE = ReplicatedCollapsingMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}', sign)
PARTITION BY date
ORDER BY name
SETTINGS index_granularity = 8192;

CREATE TABLE default.test_distributed ON CLUSTER '{cluster}' ( name String, date Date, sign Int8 ) 
ENGINE = Distributed('{cluster}', 'default', 'test_local', rand64());

SET insert_distributed_sync = 1;

INSERT INTO default.test_distributed (name, date, sign) VALUES ('1', '2024-01-01', 1),('2', '2024-01-02', 1),('3', '2024-01-03', 1),('4', '2024-01-04', 1),('5', '2024-01-05', 1),('6', '2024-01-06', 1),('7', '2024-01-07', 1),('8', '2024-01-08', 1),('9', '2024-01-09', 1),('10', '2024-01-10', 1),('11', '2024-01-11', 1);

SYSTEM SYNC REPLICA ON CLUSTER '{cluster}' default.test_local;

SELECT hostName(), * FROM clusterAllReplicas('{cluster}', 'default', 'test_local') ORDER BY date FORMAT PrettyCompactMonoBlock;

SELECT count() FROM default.test_distributed WHERE name GLOBAL IN ( SELECT name FROM default.test_distributed );

SET prefer_localhost_replica = 1;

SELECT count() FROM merge('default', '^test_distributed$') WHERE name GLOBAL IN ( SELECT name FROM default.test_distributed );
SELECT count() FROM merge('default', '^test_distributed$') PREWHERE name GLOBAL IN ( SELECT name FROM default.test_distributed );

SET prefer_localhost_replica = 0;

SELECT count() FROM merge('default', '^test_distributed$') WHERE name GLOBAL IN ( SELECT name FROM default.test_distributed );
SELECT count() FROM merge('default', '^test_distributed$') PREWHERE name GLOBAL IN ( SELECT name FROM default.test_distributed );
```

prefer_localhost_replica = 0 - allows to workaround the issue. 

On version 23.11 or custom build which includes #54905 using PREWHERE also allows to workaround the issue.

On version 24.2 PREWHERE stopped to work on the top of enging=Merge (#61064)

**Comment by filimonov** [comment]
```
clickhouse1 :) explain plan SELECT count() FROM merge('default', '^test_distributed$') WHERE name GLOBAL IN ( SELECT name FROM default.test_distributed );

EXPLAIN
SELECT count()
FROM merge('default', '^test_distributed$')
WHERE name GLOBAL IN (
    SELECT name
    FROM default.test_distributed
)

Query id: 23531c89-8ac6-4d87-94a0-3d968e76d931

┌─explain──────────────────────────────────────────────────┐
│ CreatingSets (Create sets before main query execution)   │
│   Expression ((Projection + Before ORDER BY))            │
│     MergingAggregated                                    │
│       ReadFromMerge                                      │
│         Union                                            │
│           DelayedCreatingSets                            │
│             Aggregating                                  │
│               Expression (Before GROUP BY)               │
│                 Filter (WHERE)                           │
│                   ReadFromMergeTree (default.test_local) │
│           ReadFromRemote (Read from remote replica)      │
│   CreatingSet (Create set for subquery)                  │
│     Union                                                │
│       Expression ((Projection + Before ORDER BY))        │
│         ReadFromMergeTree (default.test_local)           │
│       ReadFromRemote (Read from remote replica)          │
└──────────────────────────────────────────────────────────┘

16 rows in set. Elapsed: 0.004 sec. 

clickhouse1 :) set prefer_localhost_replica=0;

SET prefer_localhost_replica = 0

Query id: d96ffc16-7004-46cc-aa51-297c3badc26e

Ok.

0 rows in set. Elapsed: 0.001 sec. 

clickhouse1 :) explain plan SELECT count() FROM merge('default', '^test_distributed$') WHERE name GLOBAL IN ( SELECT name FROM default.test_distributed );

EXPLAIN
SELECT count()
FROM merge('default', '^test_distributed$')
WHERE name GLOBAL IN (
    SELECT name
    FROM default.test_distributed
)

Query id: 8a8f5492-ee1e-439e-92c7-e132e1908021

┌─explain────────────────────────────────────────────────┐
│ CreatingSets (Create sets before main query execution) │
│   Expression ((Projection + Before ORDER BY))          │
│     MergingAggregated                                  │
│       ReadFromMerge                                    │
│         ReadFromRemote (Read from remote replica)      │
│   CreatingSet (Create set for subquery)                │
│     ReadFromRemote (Read from remote replica)          │
└────────────────────────────────────────────────────────┘

7 rows in set. Elapsed: 0.004 sec. 
```

**Comment by alexey-milovidov** [comment]
> altinitystable

This is a mistake. We don't support alternative, third-party builds.
I strongly do not recommend "altinity" builds.

Read https://clickhouse.com/docs/knowledgebase/difference_between_official_builds_and_3rd_party

**Comment by alexey-milovidov** [comment]
@alsugiliazova, you can file an issue with no traces of 3rd-party builds.

**Comment by SaltTan** [comment]
https://github.com/ClickHouse/ClickHouse/issues/64211
