### ISSUE TITLE
'Cassandra'MergeTree table-engine

### ISSUE THREAD

**Issue by shahargv** [ClickHouse/ClickHouse#59406]
**Goal**

Allow creating tables that works similar to Cassandra/ScyllaDB on merges: for rows with equal ORDER BY values, data in the columns will be updated to the most-recent version, while keeping the data in un-touched columns the same. Here, the ORDER BY columns are similar to Cassandra's primary-key.

**Example**
```
CREATE TALBE test1 (
    DateCreated Datetime,
    K1 String,
    K2 String,
    Col1 String,
    Col2 Int32,
    Col3 String
) Engine=[Replicated*]CassandraMergeTree(DateCreated) --DateCreated is the version column
PARTITION BY K1
ORDER BY K1, K2

INSERT INTO test1(DateCreated, K1, K2, Col1, Col2, Col3) VALUES('2024-01-01', 'k1-1', 'k2-1', 'c1', 1, 'c2') -- row is created
INSERT INTO test1(DateCreated, K1, K2, Col1, Col2, Col3) VALUES('2024-01-02', 'k1-1', 'k2-1', 'c2', 2, 'c3') -- the values are all updated
INSERT INTO test1(DateCreated, K1, K2, Col1, Col2, Col3) VALUES('2022-01-02', 'k1-1', 'k2-1', 'aaa', 2, 'aaa') -- no update is made, since this row is with lower version (the time is in 2022)
INSERT INTO test1(DateCreated, K1, K2, Col1, Col2, Col3) VALUES('2024-01-03', 'k1-1', 'k2-1', 'c3') -- The value of Col1 is now c3, but Col2 and Col3 remains '2' and 'c3' because they were not touched

)
```

**Use-case**
This will allow a simpler data-modeling for tables that describes an entity with information learned about it over-time. It'll allow to save space by having one row (or at least: less rows, depends on the merges of course) describing the entity, without the need to always fetch the most up-to-date information about the entity before writing the new row.

**Alternatives**
Data-modeling like this example can be implemented right now using AggregatingMergeTree and argMaxState and argMaxMerge. But having such table-engine would make the usage simpler and more 'clean'.

Thanks.

**Comment by UnamedRus** [comment]
Duplicate,  https://github.com/ClickHouse/ClickHouse/issues/57240
