### ISSUE TITLE
Why lightweight deletion cannot be performed based on partition parts, but rather a full table scan？

### ISSUE THREAD

**Issue by guoxiaolongzte** [ClickHouse/ClickHouse#59409]
### table info:
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/risk/t_antifraud_hit_rule_trend_index_avg/{shard}', '{replica}')
**PARTITION BY scene_no**
ORDER BY (scene_no, minutes_point, rule_no, day)
TTL create_time + toIntervalDay(31)
SETTINGS index_granularity = 8192, storage_policy = 'jbod_policies', use_minimalistic_part_header_in_zookeeper = 1

### part info:
SELECT
    partition,
    count(),
    max(path)
FROM system.parts
WHERE (table = 't_antifraud_hit_rule_trend_index_avg') AND **(partition = 'SCENE_ACUG4hgtAO')** AND active
GROUP BY partition

Query id: fe673d86-2523-47b1-b01b-c0817d30f2b9

┌─partition────────┬─count()─┬─max(path)──────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ SCENE_ACUG4hgtAO │       1 │ /data7/ckdata/store/704/70417b83-b6d5-495f-b49d-69ccca622669/72d607d7ef8a19f424973553f9f2ec12_0_6202_11_43116/ │

SELECT count()
FROM system.parts
WHERE (table = 't_antifraud_hit_rule_trend_index_avg') AND active

Query id: 4d7f66e9-6b1c-462c-9891-c8206ecee4be

┌─count()─┐
│      **83** │
└─────────┘

###  lightweight deletion:
delete from risk.t_antifraud_hit_rule_trend_index_avg
                                                          where **scene_no in( 'SCENE_ACUG4hgtAO')**
                                                                    and rule_no = 'RULE_11mxcbs488ao'
                                                                    and minutes_point = 28444468
                                                                    and day = 3
                                                            and diversion_nos = 'DIVERSION_default'
                                                  ;

SELECT *
FROM system.mutations
WHERE is_done = 0
ORDER BY create_time DESC
LIMIT 10

**parts_to_do:                83
is_done:                    0**

### clickhouse version:

SELECT version()

Query id: ad95b338-74b5-4658-81af-4fb276de385c

┌─version()──┐
│ 22.8.10.29 │
└────────────┘

### question:
Why lightweight deletion cannot be performed based on partition parts, but rather a full table scan？
SCENE_ACUG4hgtAO is a partition, The expected result is that I should just lightweight delete in a part, instead of 83 partitions.

**Comment by UnamedRus** [comment]
> Why lightweight deletion cannot be performed based on partition parts, but rather a full table scan？

Wasn't implemented.
There is 2 part of this implementation:
1. Add IN PARTITION OPTION to DELETE statement, just like for ALTER TABLE UPDATE/DELETE ()
2. Make ClickHouse smart enough to guess needed partitions automatically, without IN PARTITION statement

https://github.com/ClickHouse/ClickHouse/issues/59225#issuecomment-1911782012

**Comment by guoxiaolongzte** [comment]
Alter table xxx UPDATE _row_exists =0 IN PARTITION 'xxxx' WHERE ....? Is this plan feasible?

**Comment by UnamedRus** [comment]
Yes, for now it works.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/67805
