### ISSUE TITLE
optimize_arithmetic_operations_in_aggregate_functions breaks column aliases

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/ClickHouse#59414]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

Columns involving certain arithmetic expressions are not given the name I assign to them.

```
6f7bc8975d05 :) select sum(number + 1) as b from system.numbers where number <= 5;

SELECT sum(number + 1) AS b
FROM system.numbers
WHERE number <= 5

Query id: 019e7a7d-bb1a-4918-bb71-ac6a90583a70

┌─plus(sum(number), multiply(1, count(number)))─┐
│                                            21 │
└───────────────────────────────────────────────┘

1 row in set. Elapsed: 0.002 sec.
```

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

https://fiddle.clickhouse.com/9b3eb9c2-5ba0-4c5a-92df-50e9ef31a1b9

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

```
6f7bc8975d05 :) select version();

SELECT version()

Query id: 003ff2e5-b70c-409c-9266-958d54dac6f6

┌─version()───┐
│ 24.1.1.2048 │
└─────────────┘

1 row in set. Elapsed: 0.001 sec.
```

**How to reproduce**

* Which ClickHouse server version to use

See above

* Which interface to use, if matters

It shouldn't matter

* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

See above

**Expected behavior**

> A clear and concise description of what you expected to happen.

I expect to see a column named `b` in the output.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by tavplubix** [comment]
```
localhost.localdomain :) set optimize_arithmetic_operations_in_aggregate_functions=0

SET optimize_arithmetic_operations_in_aggregate_functions = 0

Query id: 06cd7f1d-b2fd-4f09-a573-3a820d6dc8c2

Ok.

0 rows in set. Elapsed: 0.001 sec. 

localhost.localdomain :) select sum(number + 1) as b from system.numbers where number <= 5;

SELECT sum(number + 1) AS b
FROM system.numbers
WHERE number <= 5

Query id: c21b562d-860d-412d-baf1-c198d6fec389

┌──b─┐
│ 21 │
└────┘

1 row in set. Elapsed: 0.016 sec.
```

Introduced in https://github.com/ClickHouse/ClickHouse/pull/57853

cc: @jiebinn, @novikd

**Comment by novikd** [comment]
Works with enabled `allow_experimental_analyzer`.

**Comment by tavplubix** [comment]
> st-wontfix

Should we at least automatically disable `optimize_arithmetic_operations_in_aggregate_functions` if the new analyzer is disabled?

**Comment by cpcloud** [comment]
Just so I understand correctly: the ability to select columns from a subquery where said columns contain undocumented types of arithmetic expressions that can be optimized, is a `wontfix`?

This seems likely to break a large number of existing queries.

**Comment by cpcloud** [comment]
Hopefully I didn't sound too curmudgeonly, appreciate all of your work here!

**Comment by jiebinn** [comment]
Thank you to report the issue and Sorry for the late reply as the Chinese New Year holiday.
