### ISSUE TITLE
numbers(xx) read more rows, than it was before

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#59418]
**Describe the situation**
Just not to forget.
https://github.com/ClickHouse/ClickHouse/pull/50909#issuecomment-1869094989

**How to reproduce**
https://fiddle.clickhouse.com/87861a7b-30c4-45c2-862e-07cdfb63588d
23.11
```
	"rows_before_limit_at_least": 65409,

	"statistics":
	{
		"elapsed": 0.002581122,
		"rows_read": 65409,
		"bytes_read": 523272
	}
```
https://fiddle.clickhouse.com/29e9744f-0726-4f2c-97c7-4a8362eac102

23.10
```
	"rows_before_limit_at_least": 3,

	"statistics":
	{
		"elapsed": 0.002170152,
		"rows_read": 3,
		"bytes_read": 24
	}
```

**Comment by JackyWoo** [comment]
We can simplify the query to 
```
SELECT  toString(number) as a
  FROM numbers(3)
  WHERE a = '1' format JSON
```
