### ISSUE TITLE
Fuzzer assertion `Logical error: 'Invalid move to PREWHERE optimization. Cannot find column k in output'.`

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#59437]
(you don't have to strictly follow this form)

**Describe the bug**
A link to the report https://s3.amazonaws.com/clickhouse-test-reports/59337/74aa3d638ef54c40c5fa617abe22413eda323c8e/ast_fuzzer__asan_/report.html

**How to reproduce**
Found in https://github.com/ClickHouse/ClickHouse/pull/59337

**Comment by tavplubix** [comment]
cc: @kitaisreal
