### ISSUE TITLE
Memory limit exceptions

### ISSUE THREAD

**Issue by jaumecastell** [ClickHouse/ClickHouse#59472]
I'm facing an issue with latest version of clickhouse of 2023, the 23.12.

I'm having a lot of memory limit exceptions, that never recover, until I restart the clickhouse-server service. 
This are my memory user.xml configurations: 

<max_memory_usage>160000000000</max_memory_usage>         <max_memory_usage_for_user>200000000000</max_memory_usage_for_user>

and my server memory specs:

# free -b
total
Mem:      270209937408

This has started when I updated the clickhouse version from 23.5 to 23.12.

Can you help me to understand whats happening?

Thanks

**Comment by jaumecastell** [comment]
Also, checking the system.metrics table on clickhouse, for MemoryTracking metric, I see that it never surpasses thr 40Gb of usage.

**Comment by seandhaynes** [comment]
Possibly looks like this to me: https://github.com/ClickHouse/ClickHouse/issues/55875

Though maybe not given you say you're running v23.12 can you send the specific version of ClickHouse you're using that you see this in? Also do you use packages or builds from ClickHouse? Just trying to rule out the possibility you build ClickHouse from a fork and don't have that patch.

**Comment by jaumecastell** [comment]
Hi @seandhaynes , I tested out v24.1.1.2048, and still getting memory limit errors. I'm monitoring system memory usage and user memory usage, and I can see that user memory is more or less 50% higher than system memory usage. Can you guide me on how to solve this?

@filimonov your help would be also appreciated.

**Comment by seandhaynes** [comment]
@jaumecastell thanks for trying 24.1. 

There's been a couple of issues in >= 23.8 that I'm aware of, though the one I shared above  (https://github.com/ClickHouse/ClickHouse/issues/55875) is the only one that aligns with the the systems you're seeing.

The others just for reference are https://github.com/ClickHouse/ClickHouse/issues/54483 and https://github.com/ClickHouse/ClickHouse/issues/57931

Could you share a bit more about the tables you have, and your usage patterns? For example:
 * Tables and table engines in use.
 * Number of tables
 * Query patterns, i.e number of inserts and select queries per second.

Some queries that would be useful for providing some more insight into memory usage:

```
WITH
    (SELECT sum(value::UInt64) FROM system.metrics WHERE metric = 'MemoryTracking')               AS memory_tracked_,
    (SELECT sum(total_bytes) FROM system.tables WHERE engine IN ('Join','Memory','Buffer','Set')) AS memory_tables_,
    (SELECT sum(value::UInt64) FROM system.asynchronous_metrics WHERE metric LIKE '%CacheBytes')  AS memory_caches_,
    (SELECT sum(memory_usage::UInt64) FROM system.processes)                                      AS memory_processes_,
    (SELECT sum(memory_usage::UInt64) FROM system.merges)                                         AS memory_merges_,
    (SELECT sum(bytes_allocated) FROM system.dictionaries)                                        AS memory_dictionaries_,
    (SELECT sum(primary_key_bytes_in_memory_allocated) FROM system.parts)                         AS memory_primary_keys_
SELECT
    assumeNotNull(memory_tracked_)                           AS memory_tracked,
    assumeNotNull(memory_tables_)                            AS memory_tables,
    assumeNotNull(memory_caches_)                            AS memory_caches,
    assumeNotNull(memory_processes_)                         AS memory_processes,
    assumeNotNull(memory_merges_)                            AS memory_merges,
    assumeNotNull(memory_dictionaries_)                      AS memory_dictionaries,
    assumeNotNull(memory_primary_keys_)                      AS memory_primary_keys
FORMAT Vertical
```

and (for memory fragmentation, although it doesn't look like what you're seeing):
```
select metric, value from system.asynchronous_metrics where metric like '%jemalloc%'
```

**Comment by jaumecastell** [comment]
@seandhaynes I'm using only one table with ReplacingMergeTree engine. 

Here is the result of some of the queries you asked, as of now:

`WITH
    (
        SELECT sum(CAST(value, 'UInt64'))
        FROM system.metrics
        WHERE metric = 'MemoryTracking'
    ) AS memory_tracked_,
    (
        SELECT sum(total_bytes)
        FROM system.tables
        WHERE engine IN ('Join', 'Memory', 'Buffer', 'Set')
    ) AS memory_tables_,
    (
        SELECT sum(CAST(value, 'UInt64'))
        FROM system.asynchronous_metrics
        WHERE metric LIKE '%CacheBytes'
    ) AS memory_caches_,
    (
        SELECT sum(CAST(memory_usage, 'UInt64'))
        FROM system.processes
    ) AS memory_processes_,
    (
        SELECT sum(CAST(memory_usage, 'UInt64'))
        FROM system.user_processes
        WHERE user = 'default'
    ) AS user_memory_,
    (
        SELECT sum(CAST(memory_usage, 'UInt64'))
        FROM system.merges
    ) AS memory_merges_,
    (
        SELECT sum(bytes_allocated)
        FROM system.dictionaries
    ) AS memory_dictionaries_,
    (
        SELECT sum(primary_key_bytes_in_memory_allocated)
        FROM system.parts
    ) AS memory_primary_keys_
SELECT
    assumeNotNull(formatReadableSize(memory_tracked_)) AS memory_tracked,
    assumeNotNull(formatReadableSize(memory_tables_)) AS memory_tables,
    assumeNotNull(formatReadableSize(memory_caches_)) AS memory_caches,
    assumeNotNull(formatReadableSize(memory_processes_)) AS memory_processes,
    assumeNotNull(formatReadableSize(user_memory_)) AS memory_user,
    assumeNotNull(formatReadableSize(memory_merges_)) AS memory_merges,
    assumeNotNull(formatReadableSize(memory_dictionaries_)) AS memory_dictionaries,
    assumeNotNull(formatReadableSize(memory_primary_keys_)) AS memory_primary_keys
FORMAT Vertical

Query id: 4851e313-12df-47f7-be0d-728f33d096ba

Row 1:
──────
memory_tracked:      27.96 GiB
memory_tables:       0.00 B
memory_caches:       8.32 GiB
memory_processes:    134.29 MiB
memory_user:         2.58 GiB
memory_merges:       2.00 GiB
memory_dictionaries: 5.27 GiB
memory_primary_keys: 3.98 GiB`

`SELECT
    query_kind,
    count() AS count,
    count / dateDiff('minute', today(), now()) AS q_per_minute
FROM system.query_log
WHERE (event_time >= today()) AND (type = 'QueryFinish')
GROUP BY query_kind
ORDER BY count DESC

Query id: 3c604829-8895-44ec-b6ec-3d009513933e

┌─query_kind─┬─count─┬──────────q_per_minute─┐
│ Select     │ 64706 │      67.5427974947808 │
│ Insert     │  4997 │       5.2160751565762 │
│ Show       │     2 │ 0.0020876826722338203 │
└────────────┴───────┴───────────────────────┘
`
`SELECT
    metric,
    value
FROM system.asynchronous_metrics
WHERE metric LIKE '%jemalloc%'

Query id: 5a895762-57a7-4dc4-90b6-da8a0a8aa0f2

┌─metric───────────────────────────────────┬────────value─┐
│ jemalloc.arenas.all.pdirty               │      2929890 │
│ jemalloc.mapped                          │  51886784512 │
│ jemalloc.metadata                        │   1395971136 │
│ jemalloc.background_thread.num_runs      │            0 │
│ jemalloc.arenas.all.pactive              │      7990809 │
│ jemalloc.background_thread.num_threads   │            0 │
│ jemalloc.metadata_thp                    │            0 │
│ jemalloc.background_thread.run_intervals │            0 │
│ jemalloc.arenas.all.pmuzzy               │      1304093 │
│ jemalloc.active                          │  32730353664 │
│ jemalloc.resident                        │  46076731392 │
│ jemalloc.retained                        │ 414234083328 │
│ jemalloc.epoch                           │         2046 │
│ jemalloc.allocated                       │  31617882080 │
│ jemalloc.arenas.all.muzzy_purged         │   1103523275 │
│ jemalloc.arenas.all.dirty_purged         │   1290083112 │
└──────────────────────────────────────────┴──────────────┘

`

**Comment by jaumecastell** [comment]
@seandhaynes I paste here some charts for MemoryTracking and User memory usage (memory_usage from system.user_processes):

![image](https://github.com/ClickHouse/ClickHouse/assets/24633685/ee80dc24-57de-4d95-a2bf-6f734bc6c14f)

![image](https://github.com/ClickHouse/ClickHouse/assets/24633685/512a5245-0a0f-42d4-bd74-be94a354d308)

As you can see, the behavior of the user memory usage is really weird...

**Comment by jaumecastell** [comment]
Hi @seandhaynes , any update or comments on this?

**Comment by seandhaynes** [comment]
Hey @jaumecastell ,

Apologies for the delay, I've been unwell and afk for a bit.

Can I ask you share the `MemoryResident` metric instead of `memoryTracking` please? As that should help provide a more accurate picture of actual memory usage, especially graphed over time.

Can I also ask that you share the below:

* A copy of the exception messages you receive in your clients before restarting ClickHouse server.
* The size of your tables and data volumes being queried.
* A copy of your table definitions (`SHOW CREATE TABLE`) and preferably some sample data and queries that you are running so we can try and reproduce it.
* A copy of settings in your environment. (select * from system.settings where changed`)

One last question I have: how long does it take for the issue to materalize after you have restarted ClickHouse?

**Comment by seandhaynes** [comment]
@jaumecastell There's nothing I can think of in Ubuntu 22.04 or a newer kernel that would change anything related to memory management or make replicas hit memory limits. Pleased it works, that said.
