### ISSUE TITLE
Supbase not connecting with local clickhouse server

### ISSUE THREAD

**Issue by kashifali11** [ClickHouse/ClickHouse#59481]
Used laest official docker image and as well as installed the latest server locally

**Describe what's wrong**
Supabase throws following error when trying to query clickhouse table through it using fdw
```ERROR: HV000: Connections error: `Input/output error: `Connection refused (os error 111)```

**Does it reproduce on recent release?**
Yes

**How to reproduce**

* start latest clickhouse server locally
* connect it with supabase and try to query any table

**Expected behavior**

Should return queried result
**ERROR: HV000: Connections error: `Input/output error: `Connection refused (os error 111)**

**Additional context**
Tried changing listen_host in config file but it also did not help. Used the default connection string as mentioned in supabase [docs](https://supabase.com/docs/guides/database/extensions/wrappers/clickhouse#connecting-to-clickhouse)

**Comment by alexey-milovidov** [comment]
1. `clickhouse-server` should be configured to listen to connections from the internet, e.g., `listen_host: '::'`
2. You should configure a user with connections allowed from the internet or a particular set of hosts related to Supabase. The user should be protected with a strong password.
3. The host-based firewall (like `iptables`) should be configured to accept these connections.
4. Cloud service providers or data center firewalls (like "security groups" in AWS) should be configured to accept these connections.

In case of trouble, you can check the connections from another host - to see if at least clickhouse-client can connect to your server.
