### ISSUE TITLE
Analyzer: Aggregation after DISTINCT producing unexpected results

### ISSUE THREAD

**Issue by jrdi** [ClickHouse/ClickHouse#59518]
When running the following query you get different results if using the analyzer.

```sql
SELECT
    product_id,
    count()
FROM
(
    SELECT DISTINCT
        product_id,
        section_id
    FROM
    (
        SELECT
            concat('product_', number % 2) AS product_id,
            concat('section_', number % 3) AS section_id
        FROM numbers(10)
    )
)
GROUP BY product_id
```

**24.2.1.230 + analyzer**

```
┌─product_id─┬─count()─┐
│ product_1  │       1 │
│ product_0  │       1 │
└────────────┴─────────┘
```

**24.2.1.230 + without the analyzer**

```
┌─product_id─┬─count()─┐
│ product_1  │       3 │
│ product_0  │       3 │
└────────────┴─────────┘
```

I'm assuming the issue happens when you do an aggregation to a subquery that contains a distinct because if you replace the `DISTINCT` by a `GROUP BY ALL` the query works as expected:

```sql
SELECT
    product_id,
    count()
FROM
(
    SELECT
        product_id,
        section_id
    FROM
    (
        SELECT
            concat('product_', number % 2) AS product_id,
            concat('section_', number % 3) AS section_id
        FROM numbers(10)
    )
    GROUP BY ALL
)
GROUP BY product_id
SETTINGS allow_experimental_analyzer = 1

┌─product_id─┬─count()─┐
│ product_1  │       3 │
│ product_0  │       3 │
└────────────┴─────────┘
```

**Comment by devcrafter** [comment]
The reason is `RemoveUnusedProjectionColumnsPass` pass. It mistakenly removes the `section_id` column.
The `EXPLAIN QUERY TREE` with (1)/ without (2) `RemoveUnusedProjectionColumnsPass`:
(1) https://pastila.nl/?000d1ac5/6effb6dee216686113fc9447278bfb46#YcRSPVAz2tRwU1DHWGEa+w==
(2) https://pastila.nl/?0027d864/5135a198217d4734f4e65ec63249018b#2NT8L6TVKkvCKpNspo/miA==
