### ISSUE TITLE
In MaterializedPostgreSQL How to connect to a db which require SSL connection

### ISSUE THREAD

**Issue by routayush1** [ClickHouse/ClickHouse#59519]
https://clickhouse.com/docs/en/engines/database-engines/materialized-postgresql

how can i connect to a db which require SSL connection 

```
CREATE DATABASE postgres_db
ENGINE = MaterializedPostgreSQL('postgres1:5432', 'postgres_database', 'postgres_user', 'postgres_password');
```

**Comment by CamiloSierraH** [comment]
Hi @routayush1 , the code today does not allow the usage of SSL, you can see all the connection info details here:
https://github.com/ClickHouse/ClickHouse/blob/30148972ed4422f579030e745a835996b66fcc30/src/Core/PostgreSQL/Utils.h#L21

We have an open issue for this. Please subscribe to receive updates when it gets added to our roadmap or is released.
https://github.com/ClickHouse/ClickHouse/issues/60130
