### ISSUE TITLE
Change the defaults of Parquet output

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59522]
**Use case**

I saw some people use it and have a subpar experience.

**Describe the solution you'd like**

- output String as UTF-8 String by default, even despite the fact that the strings can be binary;
- output Date and DateTime as Date and DateTime in Parquet, even despite the fact that the Parquet types don't always fit;
- change the default compression method from `lz4` to `zstd`, to satisfy some crappy tools that don't support `lz4`.

**Comment by gaby** [comment]
👍 Having an option to set default compression method and level would be fenomenal!

**Comment by ucasfl** [comment]
@alexey-milovidov But parquet does not have `Date` and `DateTime` types: https://parquet.apache.org/docs/file-format/types/

**Comment by mxwell** [comment]
> @alexey-milovidov But parquet does not have `Date` and `DateTime` types: https://parquet.apache.org/docs/file-format/types/

Seems the page about Logical Types is broken on the website. You can find the right link in the comments: https://github.com/apache/parquet-site/pull/38

But there's no DateTime indeed, the closest thing is TIMESTAMP annotation for int64.

**Comment by den-crane** [comment]
@ucasfl Parquet has hints like Timestamp

```
# clickhouse-local --output_format_parquet_compression_method=snappy -q 'select today() d, now() t, now64(6) t64 format Parquet' > test.Parquet

# pip install parquet-cli

# parq test.Parquet --schema

 # Schema
 <pyarrow._parquet.ParquetSchema object at 0xffff6fc245c0>
required group field_id=-1 schema {
  required int32 field_id=-1 d (Int(bitWidth=16, isSigned=false));
  required int32 field_id=-1 t (Int(bitWidth=32, isSigned=false));
  required int64 field_id=-1 t64 (Timestamp(isAdjustedToUTC=true, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
}


# ./duckdb

select * from 'test.Parquet';
┌────────┬────────────┬──────────────────────────────┐
│   d    │     t      │             t64              │
│ uint16 │   uint32   │   timestamp with time zone   │
├────────┼────────────┼──────────────────────────────┤
│  19705 │ 1702584780 │ 2023-12-14 20:13:00.01502+00 │
└────────┴────────────┴──────────────────────────────┘
```

So Clickhouse can save DateTime into  Parquet int64 / Timestamp the same way as DateTime64.
The same for Date, Clickhouse can save Date the same way as Date32. And use 32 bits with Date hint.

**Comment by alexey-milovidov** [comment]
#61817

**Comment by eclbg** [comment]
Do I understand well that this issue can be closed as #61817 has been merged?

**Comment by alexey-milovidov** [comment]
@eclbg, No, only 2 of 3 items are implemented.

**Comment by eclbg** [comment]
Thanks for clarifying and apologies for missing it.
