### ISSUE TITLE
Lack of short-circuiting with enable_optimize_predicate_expression

### ISSUE THREAD

**Issue by zlobober** [ClickHouse/ClickHouse#5952]
Consider a select query of form:

```
SELECT * FROM (SELECT * FROM someTable WHERE PredX) WHERE PredY
```

Suppose that PredX looks like isNotNull(smth) and PredY uses smth under assumption that smth is not null; for example, PredY may rely on toDateTime(smth). 

In this situation enable_optimize_predicate_expression will push the outer predicate into the inner select query, which will result in error during query evaluation as there is no short-circuiting and PredX will not prevent PredY from failing.

**Comment by alexey-milovidov** [comment]
#12587

**Comment by alexey-milovidov** [comment]
I don't think it's obsolete.
Nevertheless, the logic of `enable_optimize_predicate_expression` is unlikely to be improved.
