### ISSUE TITLE
Consider making all format names case insensitive.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59526]
**Use case**

Let's just give up and accept if a user writes Tsv, or TSV, or tsv, or even rowbinary.

**Comment by HowePa** [comment]
@alexey-milovidov I'm interested in this issue. Could it be assigned to me? Thank you!

**Comment by alexey-milovidov** [comment]
@HowePa Sure.

**Comment by HowePa** [comment]
Since there is no standardized macro definition for format names, I tried to add a keyword map to make all format names case insensitive. #59560
