### ISSUE TITLE
Random Load Balance Policy returns Inconsistent Results on Select

### ISSUE THREAD

**Issue by abraithwaite** [ClickHouse/ClickHouse#5955]
**Describe the bug**
The default `load_balancing` policy, `random`, returns inconsistent results for subsequent queries for a distributed table pointing to a 6-node 6-shard 2-replica cluster of materialized view tables.

Switching the `load_balancing` setting to `in_order` (mostly) resolves the issue.  `in_order` still breaks during restarts (doesn't seem to query the other healthy replica for the shard).

**How to reproduce**
* Version: 19.9.2 revision 54421
* Configure a cluster with 2-way replication sharing nodes. (e.g. 2 nodes, 2 shards, 2-way replication)
* Create a raw data table and insert some data on all servers.
* Create a MV table with the ReplicatedAggregatingMergeTree engine on the raw table.
* Create a distributed table on top of that MV.
* Set load_balancing to random
* Query table and observe inconsistent results.

We will work on putting together an example to try and reproduce the bug.

**Comment by den-crane** [comment]
You mean the result is inconsistent because of replication lag?

**Comment by abraithwaite** [comment]
That was my first assumption, however that was not the case.  I checked each shard and replica individually.  The replicas in each shard were identical. 

Should have called this out in the initial report.

I should also note that subsequent queries would sometimes return lower counts than the real totals and sometimes return higher counts than the real totals, suggesting that for some shards both replicas are being counted somehow.

**Comment by den-crane** [comment]
try to add hostName() to your query to check that you see data from the same shard twice

**Comment by nvartolomei** [comment]
> Switching the load_balancing setting to in_order (mostly) resolves the issue. in_order still breaks during restarts (doesn't seem to query the other healthy replica for the shard).

Sounds like you might have a misconfigured cluster. Table metadata + macros config for each node + cluster config would be helpful to rule that out.

**Comment by abraithwaite** [comment]
> try to add hostName() to your query to check that you see data from the same shard twice

This only returned to me the hostname that I ran the query on.  Not sure how it plays into a simple select query (even against a distributed table, the docs suggest it won't be the remote table unless processing aside from fetching is done there?).

> Sounds like you might have a misconfigured cluster. Tables metadata (replicated+distributed) + macros config for each node + cluster config would be helpful to rule that out.

Trying to put together a reproducible example today.  Barring that I'll obfuscate our config and upload it.
