### ISSUE TITLE
Input format `Form` to read/write a single record in the `application/x-www-form-urlencoded` format

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59557]
**Use case**

Open this website, open the browser console, then check the "beacon" request:

`curl 'https://beacon.basicrum.com/beacon/catcher.php' -X POST -H 'User-Agent: ...' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: https://www.basicrum.com' -H 'Connection: keep-alive' -H 'Referer: https://www.basicrum.com/' -H 'Cookie: RT="z=1&dm=basicrum.com&si=dd0c542f-7adf-4310-830a-6c0a3d157c90&ss=ls7wkmzy&sl=4&tt=22l&bcn=https%3A%2F%2Fbeacon.basicrum.com%2Fbeacon%2Fcatcher.php&ld=uy1r"' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: no-cors' -H 'Sec-Fetch-Site: same-site' -H 'TE: trailers' --data-raw 'c.e=ls7xfkpm&c.tti.m=raf&rt.start=navigation&rt.bmr=390%2C11%2C10&rt.tstart=1707076768666&rt.bstart=1707076769091&rt.blstart=1707076769056&rt.end=1707076769078&t_resp=296&t_page=116&t_done=412&t_other=boomerang%7C6%2Cboomr_fb%7C425%2Cboomr_ld%7C390%2Cboomr_lat%7C35&rt.tt=2685&rt.obo=0&pt.fcp=407&nt_nav_st=1707076768666&nt_dns_st=1707076768683&nt_dns_end=1707076768684&nt_con_st=1707076768684&nt_con_end=1707076768850&nt_req_st=1707076768850&nt_res_st=1707076768962&nt_res_end=1707076768962&nt_domloading=1707076769040&nt_domint=1707076769066&nt_domcontloaded_st=1707076769067&nt_domcontloaded_end=1707076769068&nt_domcomp=1707076769069&nt_load_st=1707076769069&nt_load_end=1707076769078&nt_unload_st=1707076769040&nt_unload_end=1707076769041&nt_ssl_st=1707076768788&nt_enc_size=3209&nt_dec_size=10093&nt_trn_size=3940&nt_protocol=h2&nt_red_cnt=0&nt_nav_type=1&restiming=%7B%22https%3A%2F%2Fwww.basicrum.com%2F%22%3A%7B%22publications%2F%22%3A%226%2C88%2C88%2C54%2C54%2C3e%2Ci%2Ci%2Ch*12h5%2Ckb%2C5b8%22%2C%22assets%2Fjs%2F%22%3A%7B%22just-the-docs.js%22%3A%223am%2Ce%2Ce*12pc%2C_%2C8oj*20%22%2C%22boomerang-1.737.60.cutting-edge.min.js%22%3A%222au%2Cb%2Ca*1pu3%2C_%2C1m19*21*42%22%2C%22vendor%2Flunr.min.js%22%3A%223am%2Cd%2C8*16t2%2C_%2Cfym*20%22%7D%7D%7D&u=https%3A%2F%2Fwww.basicrum.com%2Fpublications%2F&r=https%3A%2F%2Fwww.basicrum.com%2Fcost-analyses%2F&v=1.737.60&sv=14&sm=p&rt.si=dd0c542f-7adf-4310-830a-6c0a3d157c90-s8cjr1&rt.ss=1707075325294&rt.sl=4&vis.st=visible&ua.plt=Linux%20x86_64&ua.vnd=&pid=8fftz949&n=1&c.t.fps=07*4*65*j*61&c.t.busy=2*4*0034&c.tti.vr=408&c.tti=408&c.b=2&c.f=60&c.f.d=2511&c.f.m=1&c.f.s=ls7xfl1h&dom.res=5&dom.doms=1&mem.lsln=0&mem.ssln=0&mem.lssz=2&mem.sssz=2&scr.xy=1920x1200&scr.bpp=24%2F24&scr.orn=0%2Flandscape-primary&cpu.cnc=16&dom.ln=114&dom.sz=10438&dom.ck=157&dom.img=0&dom.script=6&dom.script.ext=3&dom.iframe=0&dom.link=4&dom.link.css=1&sb=1'`

![Screenshot_20240204_210312](https://github.com/ClickHouse/ClickHouse/assets/18581488/923cf4fb-c37e-40e0-b9d8-23f2e56592c2)

The format is just a set of URL-encoded key-value pairs.
We should parse it as a single record with the corresponding columns.

**Additional context**

See https://github.com/akamai/boomerang

We should also implement an output format to send forms easily with the URL engine.

**Comment by Blargian** [comment]
@alexey-milovidov I'll gladly pick this up - I want to tackle the Npy output format issue but this might be a nice easy introduction to doing a new format. baby steps...

**Comment by alexey-milovidov** [comment]
@Blargian, thank you! This will be really nice, appreciate your help!

**Comment by Blargian** [comment]
@alexey-milovidov as I understand we are interested in parsing the form-data (or `--data-raw` with curl above) where key-value pair will map to column-name and field?
![Screenshot from 2024-02-08 13-21-36](https://github.com/ClickHouse/ClickHouse/assets/41984034/323c61e0-3b33-40d0-913e-bb88bd46809d)

I have a question how input to ClickHouse will look in the use case. I'm familiar with formats which read in data from a file such as `Npy` or `TSV` but this format operates in a web context so in which way does CH ingest the data? Does it get piped into CH client? I'm fairly new to CH contributions so if you could provide a hypothetical example usage query it would be helpful. :)

Also, could you tell me if there are any formats which have aspects in common with this problem that I could use for reference? I think implementation will inherit from `IRowInputFormat` for a start.

**Comment by alexey-milovidov** [comment]
ClickHouse accepts HTTP POST data for insertion.

Example:

`curl http://localhost:8123/?query=INSERT%20INTO%20table%20FORMAT%20TSV --data-binary @- < data.tsv`

In the same way, it will be expected to work with the new Form format:

`curl http://localhost:8123/?query=INSERT%20INTO%20table%20FORMAT%20Form --data-binary @- < data`

Insertion from `clickhouse-client`, and selects from `file` will also work, although the main use-case will be - inserts over HTTP.

> if there are any formats which have aspects in common

`TSKV`, `JSONEachRow` will be similar. Yes, inheriting from `IRowInputFormat` makes sense.

**Comment by Blargian** [comment]
@alexey-milovidov another question - should URL escaped sequences such as `%20` be handled when reading in the data or does a value like `390%2C11%2C10` simply get stored as String? For instance in TSKV format `tryInferDataTypeByEscapingRule` is used in the schema to infer data type. I couldn't find any URL escaping rules in the code base, does something already exist that I missed or could I add a new Escaping Rule for URL encoded strings?

**Comment by alexey-milovidov** [comment]
@Blargian They should be handled (decoded).
Then, the serialization is "raw" (without further escaping).

For example, we have the following input:
```
s=Hello%5Cn%25world
```

We decode the URL-encoding of the value and get:
```
Hello\n%world
```

The sequence of `\n` is not interpreted because we will use the "raw" deserialization method instead of "escaped" or "quoted", so the resulting string will contain a backslash and n, instead of a new line.

**Comment by Blargian** [comment]
@alexey-milovidov at the moment I am working on parsing names with '.' to Nested datatype, example

`c.t.fps=07*4*65*j*61` would have structure 

```
c Nested
(
    t Nested
    (
        fps String
    ),
),
```

However I noticed in the request data that there are a few instances where both parent and child have values provided for the key:

```
c.tti (Int64) --> parent which is child of c
c.tti.vr (Int64)  --> child of tti 
c.tti.m (String)  --> child of tti 

c.f (Int64) --> parent which is child of c
c.f.d (Int64) --> child of f
c.f.m (Int64) --> child of f
c.f.s (String) --> child of f

dom.link Nullable (Int64) --> parent which is child of dom 
dom.link.css (Int64) --> child of link

dom.script (Int64) --> parent which is child of dom
dom.script.ext (Int64) --> child of script
```

For instance when children are `c.tti.vr `, `c.tti.m `, then we cannot say that `c.tti` is type `Nested` because there is data associated with this field already (Integer in this case). 

Possible solutions I have thought of:
- store the value of the parent which has a type as a new child under `Nested` of the same name. example:

```
c.tti (Int64) 
c.tti.vr (Int64)  
c.tti.m (String)  
```
becomes

```
c Nested
(
    tti Nested
    (
        tti_value Int64,
        vr Int64,
        m String,
    )
)
```
Maybe you have some better suggestion or insight?

**Comment by alexey-milovidov** [comment]
Do it in exactly the same way as JSONEachRow or TSKV.
