### ISSUE TITLE
Prevent deletes / drop / truncate

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#59556]
Hi, is there any preferred best-practice to prevent the use of: DELETE, ALTER DELETE, UPDATE, DROP, TRUNCATE of data in some tables? I would just like to allow INSERT queries, and add an extra layer of protection to potentially disruptive actions.

Thanks!

**Comment by tbragin** [comment]
It's possible to set max size of table or partition to drop, if it helps, but it is a global setting. https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#max-table-size-to-drop

**Comment by enzorevo** [comment]
Thanks. But for example that would not prevent someone from doing: ALTER TABLE table DELETE where date=x

how to prevent such single deletes?

**Comment by timfursov** [comment]
Hey!
There is a [set of different grants ](https://clickhouse.com/docs/en/sql-reference/statements/grant#privileges) :)

Would the following code sample work for you?

```
CREATE TABLE db.table ...
CREATE USER insert_only_user
GRANT INSERT ON db.table TO insert_only_user
```

This way `insert_only_user` will only be able to do inserts into the `db.table`

**Comment by enzorevo** [comment]
Yeah, that's really interesting. Thanks!
