### ISSUE TITLE
clickhouse can not restart

### ISSUE THREAD

**Issue by xiedeyantu** [ClickHouse/ClickHouse#59561]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

2024.02.05 14:42:38.063837 [ 7160 ] {} <Error> Application: Caught exception while loading metadata: std::exception. Code: 1001, type: std::length_error, e.what() = basic_string, Stack trace (when copying this message, always include the lines below):

0. std::logic_error::logic_error(char const*) @ 0x1c49fdad in ?
1. ? @ 0xb378869 in /usr/bin/clickhouse
2. ? @ 0xb378820 in /usr/bin/clickhouse
3. ? @ 0x1c4a016b in ?
4. DB::Field::operator=(std::__1::basic_string_view<char, std::__1::char_traits<char> > const&) @ 0x15d18215 in /usr/bin/clickhouse
5. DB::ColumnString::get(unsigned long, DB::Field&) const @ 0x15e48e72 in /usr/bin/clickhouse
6. DB::MergeTreePartition::create(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, DB::Block, unsigned long, std::__1::shared_ptr<DB::Context const>) @ 0x16404437 in /usr/bin/clickhouse
7. DB::MergeTreeWriteAheadLog::restore(std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::Context const>) @ 0x1645ef97 in /usr/bin/clickhouse
8. ? @ 0x1635b3a4 in /usr/bin/clickhouse
9. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xb41b7ca in /usr/bin/clickhouse
10. ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()&&...)::'lambda'()::operator()() @ 0xb41d964 in /usr/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xb418b97 in /usr/bin/clickhouse
12. ? @ 0xb41c71d in /usr/bin/clickhouse
13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
14. __clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.3.6.5 (official build))

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by Algunenano** [comment]
22.3 is out of support. Please upgrade.
