### ISSUE TITLE
Cast to decimal fails on overflow unconditionally 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#5956]
```
set decimal_check_overflow=0; select CAST(toUInt64(10000000000), 'Decimal(9,1)');

Received exception from server (version 19.11.0):
Code: 407. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Decimal convert overflow. 
```

That is not consistent with all other types where overflow is never checked:
```
SELECT CAST(toUInt64(10000000000), 'UInt16')

┌─CAST(toUInt64(10000000000), 'UInt16')─┐
│                                 58368 │
└───────────────────────────────────────┘

1 rows in set. Elapsed: 0.002 sec. 
```

And the existence of flag `decimal_check_overflow` gives the impression that check can be turned off.

**Comment by alexey-milovidov** [comment]
This behaviour is better, because there will be no benefits for overflow.
The settings `decimal_check_overflow` only applied on calculations on decimals, not for parsing.
Please add the relevant info to the documentation.
