### ISSUE TITLE
The document of `max_concurrent_queries_for_user` unnecessarily refer to MergeTree tables.

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#59571]
In the document, https://clickhouse.com/docs/en/operations/settings/settings#max-concurrent-queries-for-user, it says "The maximum number of simultaneously processed queries related to MergeTree table per user.".

From the source code I didn't find the relationship between this setting and MergeTree table engine. 

Is it correct?

**Comment by CurtizJ** [comment]
It's incorrect, this setting is not related to `MergeTree` tables. Its description was copy-pasted from `MergeTree` setting `max_concurrent_queries` in commit https://github.com/ClickHouse/ClickHouse/pull/30533/commits/a5325a2303652d032c1901f17e61419a83a05ebb by mistake.

**Comment by Alex-Cheng** [comment]
I have correct it in my pr #60343.  So close it.
