### ISSUE TITLE
cosineDistance: Logical error: 'Bad cast from type DB::ColumnNothing to DB::ColumnVector<double>'

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#59596]
https://s3.amazonaws.com/clickhouse-test-reports/59533/8581bdbe58bdeea57c33f1e499624111ad26d09b/ast_fuzzer__tsan_/report.html

more simple query is
`SELECT cosineDistance((1, 1), (toNullable(0.5), 0.1))`

**Comment by tavplubix** [comment]
cc: @FArthur-cmd, @rschu1ze
