### ISSUE TITLE
user_defined directory is getting created in my user home directory

### ISSUE THREAD

**Issue by bunkiedc** [ClickHouse/ClickHouse#59597]
I updated our clickhouse-server container a few weeks ago. I use clickhouse-client on a physical server through some scripts, and It started complaining about not having permission somewhere, but I wasn't able to determine where it was having a problem, as the message was pretty cryptic.  I ran clickhouse-client in the script as sudo, and it worked as expected.  I was now able to run this anytime afterward without using sudo.  The problem is now clickhouse-client (I think) is creating the directory, user_defined, in my home directory.  If I delete the directory, it is recreated the next time the scripts run.  Is this some sort of configuration issue?  I'm not sure if this is the result of updating the clickhouse-server container, or if clickhouse-client is the problem (which is on a physical server and updates regularly via apt upgrade).

This is now occurring in both our dev and production environments.

We are running on Ubuntu 20.04:
ClickHouse client version 24.1.2.5 (official build)
ClickHouse server version 23.9.2

The error that was being thrown (less the record) before running clickhouse-client as sudo:

Code: 83. DB::Exception: Couldn't create directory /user_defined/ reason: 'Permission denied': While executing ValuesBlockInputFormat: data for INSERT was parsed from query: (in query: insert into XXX values(XXX). (DIRECTORY_DOESNT_EXIST)

We aren't using any user_defined things, so I'm not quite sure how to fix this.
thanks,
          david

**Comment by tavplubix** [comment]
>  Is this some sort of configuration issue? 

Yes, please check `path` in the config

**Comment by bunkiedc** [comment]
We're been running the same config for over two years, so not sure how that could have changed, unless the update changes something. We're not doing any user defined things, as I mentioned, so there is not a function.xml
The path in the config, should be default, is:  
<path>/var/lib/clickhouse/</path>  
<tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
<user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
I don't see anything else, especially anything related to "user_defined".
I'm going to run through the process again this morning to see if I can get any more incite into what's going on, but I'm certainly open to suggestions.

**Comment by tavplubix** [comment]
> The path in the config, should be default, is:
> /var/lib/clickhouse/

Is it explicitly specified in the config? Like `<path>/var/lib/clickhouse/</path>`? I guess `path` is not configured, so it uses current directory

**Comment by tavplubix** [comment]
> But are you saying that entry should be in the clickhouse-client config.xml?

Yes. 

However, it should use `/var/lib/clickhouse/` if `path` is not specified in the config. And it does, except for a few places, including loading of executable UDFs

**Comment by bunkiedc** [comment]
I'm sorry, I'm a little confused.  That path doesn't exist on my physical server, which clickhouse-client is running, it only exists in the clickhouse-server container.  And you're also stating that clickhouse-client "should" be using that path, /var/lib/clickhouse, if one is not specified in the clickhouse-client config.xml file... correct?

Should I add that to the clickhouse-client config.xml file then??

**Comment by tavplubix** [comment]
Ah, sorry, no, I've mistakenly read "clickhouse-client config.xml" as "clickhouse-server config.xml". No, clickhouse-client should not create any directories at all. You should add `<path>/var/lib/clickhouse/</path>` to the server's config

**Comment by bunkiedc** [comment]
Okay good.  As I stated above, that path **does** exist in my clickhouse-server config.xml file.

**Comment by tavplubix** [comment]
Then there's no way it could create the directory at another location. Are you sure you run clickhouse-server with the same config.xml that does contain `path`? Do you have some overrides in config.d? Or do you have `<user_defined_path>` in the config or overrides? It makes sense to check `preprocessed_configs/config.xml` as well

**Comment by bunkiedc** [comment]
As I mentioned above, I've not changed any of my configurations, only updated the programs.
All of my configs reside in the config.d directory.

I don't see any configs for anything called user_defined*
grep -R "user_defined" *
config.d/config.xml:    <user_defined_executable_functions_config>*_function.xml</user_defined_executable_functions_config>
config.xml:    <user_defined_executable_functions_config>*_function.*ml</user_defined_executable_functions_config>
config.xml:    

I don't have anything called "preprocessed_config" that I can find.

**Comment by tavplubix** [comment]
> I don't have anything called "preprocessed_config"

It's impossible. It must be in `/var/lib/clickhouse/` (or where `path` is set to)

**Comment by SaltTan** [comment]
maybe related? https://github.com/ClickHouse/ClickHouse/pull/58975

**Comment by bunkiedc** [comment]
Sorry, I misunderstood you as that being under config.d.
grep "user_defined" /var/lib/clickhouse/preprocessed_configs/config.xml 
    <user_defined_executable_functions_config>*_function.xml</user_defined_executable_functions_config>
    

I also tried to rollback to the previous version, and it now refuses to run with this error below.  Going back to the initial version starts up and runs okay again.  I don't know if this could be of any help:

Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]:  (version 22.8.16.32 (official build))
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 2024.02.06 16:56:45.266835 [ 130 ] {} <Error> My_DB.My_Table (39c86b2e-55f5-49ac-a3d7-4210835ad9d5): Detaching broken part /var/lib/clickhouse/store/39c/39c86b2e-55f5-49ac-a3d7-4210835ad9d5/2024_7792_8260_146 (size: 225.32 KiB). If it happened after update, it is likely because of backward incompatibility. You need to resolve this manually
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 2024.02.06 16:56:45.270444 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 231. DB::Exception: Suspiciously many (15 parts, 5.10 MiB in total) broken parts to remove while maximum allowed broken parts count is 10. You can change the maximum value with merge tree setting 'max_suspicious_broken_parts' in <merge_tree> configuration section or in table settings in .sql file (don't forget to return setting back to default value): Cannot attach table `MY_DB`.`My_Table` from metadata file /var/lib/clickhouse/store/8ee/8ee1b480-209b-4f75-9022-9d70000d60bc/My_Table.sql from query ATTACH TABLE My_DB.My_Table UUID '39c86b2e-55f5-49ac-a3d7-4210835ad9d5' (`entity` String CODEC(ZSTD(1)), `host` String CODEC(ZSTD(1)), `item` String CODEC(ZSTD(1)), `measurement` String CODEC(ZSTD(1)), `m_interval` UInt32 CODEC(ZSTD(1)), `m_timestamp` DateTime CODEC(Delta(4), ZSTD(1)), `val1` Nullable(Float64) CODEC(Delta(8), ZSTD(6)), `val2` Nullable(Float64) CODEC(Delta(8), ZSTD(6)), `val3` Nullable(Float64) CODEC(Delta(8), ZSTD(6)), `val4` Nullable(Float64) CODEC(Delta(8), ZSTD(6))) ENGINE = MergeTree PARTITION BY toYear(m_timestamp) ORDER BY (measurement, item, host, m_timestamp) SETTINGS index_granularity = 32768, min_merge_bytes_to_use_direct_io = 999999999999999999. (TOO_MANY_UNEXPECTED_DATA_PARTS), Stack trace (when copying this message, always include the lines below):
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa40285a in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 1. DB::Exception::Exception<unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SettingFieldNumber<unsigned long> const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<unsigned long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<DB::SettingFieldNumber<unsigned long> const&>::type>, unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, DB::SettingFieldNumber<unsigned long> const&) @ 0x1588e310 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 2. DB::MergeTreeData::loadDataPartsFromDisk(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >&, ThreadPoolImpl<ThreadFromGlobalPool>&, unsigned long, std::__1::queue<std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> > > >, std::__1::deque<std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> > > >, std::__1::allocator<std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> > > > > > >&, bool, std::__1::shared_ptr<DB::MergeTreeSettings const> const&) @ 0x1588d629 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 3. DB::MergeTreeData::loadDataParts(bool) @ 0x15890623 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 4. DB::StorageMergeTree::StorageMergeTree(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, bool, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x156278a8 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 5. ? @ 0x15b21f20 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 6. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15455703 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 7. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x14288e95 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 8. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) @ 0x14336e89 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 9. ? @ 0x14566eea in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 10. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa4c6ae6 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa4c8437 in /usr/bin/clickhouseFeb  6 08:56:45 3 3 server 313281e4d8e0[3746799]:  (version 22.8.16.32 (official build))
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 2024.02.06 16:56:45.266835 [ 130 ] {} <Error> My_DB.My_Table (39c86b2e-55f5-49ac-a3d7-4210835ad9d5): Detaching broken part /var/lib/clickhouse/store/39c/39c86b2e-55f5-49ac-a3d7-4210835ad9d5/2024_7792_8260_146 (size: 225.32 KiB). If it happened after update, it is likely because of backward incompatibility. You need to resolve this manually
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 2024.02.06 16:56:45.270444 [ 1 ] {} <Error> Application: Caught exception while loading metadata: Code: 231. DB::Exception: Suspiciously many (15 parts, 5.10 MiB in total) broken parts to remove while maximum allowed broken parts count is 10. You can change the maximum value with merge tree setting 'max_suspicious_broken_parts' in <merge_tree> configuration section or in table settings in .sql file (don't forget to return setting back to default value): Cannot attach table `MY_DB`.`My_Table` from metadata file /var/lib/clickhouse/store/8ee/8ee1b480-209b-4f75-9022-9d70000d60bc/My_Table.sql from query ATTACH TABLE My_DB.My_Table UUID '39c86b2e-55f5-49ac-a3d7-4210835ad9d5' (`entity` String CODEC(ZSTD(1)), `host` String CODEC(ZSTD(1)), `item` String CODEC(ZSTD(1)), `measurement` String CODEC(ZSTD(1)), `m_interval` UInt32 CODEC(ZSTD(1)), `m_timestamp` DateTime CODEC(Delta(4), ZSTD(1)), `val1` Nullable(Float64) CODEC(Delta(8), ZSTD(6)), `val2` Nullable(Float64) CODEC(Delta(8), ZSTD(6)), `val3` Nullable(Float64) CODEC(Delta(8), ZSTD(6)), `val4` Nullable(Float64) CODEC(Delta(8), ZSTD(6))) ENGINE = MergeTree PARTITION BY toYear(m_timestamp) ORDER BY (measurement, item, host, m_timestamp) SETTINGS index_granularity = 32768, min_merge_bytes_to_use_direct_io = 999999999999999999. (TOO_MANY_UNEXPECTED_DATA_PARTS), Stack trace (when copying this message, always include the lines below):
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa40285a in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 1. DB::Exception::Exception<unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, DB::SettingFieldNumber<unsigned long> const&>(int, fmt::v8::basic_format_string<char, fmt::v8::type_identity<unsigned long&>::type, fmt::v8::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::type, fmt::v8::type_identity<DB::SettingFieldNumber<unsigned long> const&>::type>, unsigned long&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, DB::SettingFieldNumber<unsigned long> const&) @ 0x1588e310 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 2. DB::MergeTreeData::loadDataPartsFromDisk(std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >&, std::__1::vector<std::__1::shared_ptr<DB::IMergeTreeDataPart const>, std::__1::allocator<std::__1::shared_ptr<DB::IMergeTreeDataPart const> > >&, ThreadPoolImpl<ThreadFromGlobalPool>&, unsigned long, std::__1::queue<std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> > > >, std::__1::deque<std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> > > >, std::__1::allocator<std::__1::vector<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<DB::IDisk> > > > > > >&, bool, std::__1::shared_ptr<DB::MergeTreeSettings const> const&) @ 0x1588d629 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 3. DB::MergeTreeData::loadDataParts(bool) @ 0x15890623 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 4. DB::StorageMergeTree::StorageMergeTree(DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, bool, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool) @ 0x156278a8 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 5. ? @ 0x15b21f20 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 6. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const @ 0x15455703 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 7. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) @ 0x14288e95 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 8. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) @ 0x14336e89 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 9. ? @ 0x14566eea in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 10. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) @ 0xa4c6ae6 in /usr/bin/clickhouse
Feb  6 08:56:45 3 3 server 313281e4d8e0[3746799]: 11. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) @ 0xa4c8437 in /usr/bin/clickhouse

**Comment by bunkiedc** [comment]
I see these are unrelated issues.  I fixed the issue above, and was able to rollback successfully now.
I again attempted the insert and the directory is again created.

**Comment by bunkiedc** [comment]
well, I guess I didn't fix the problem.  When I rolled back to the previous configuration, it errors out.  When I go back to the initial container version, it runs, but it wipes out the table completely.  I restored the table and tried it again, and it again wipes out the entire table.  What would one do in this situation?

**Comment by bunkiedc** [comment]
no further responses?

**Comment by bunkiedc** [comment]
I reset the environment and when through my process again.  The original issue is now back, where clickhouse doesn't think it has permission to write the directory.  If I run my script with sudo, it will pass, but will start writing the "user_defined" directory in my home directory.

Code: 83. DB::Exception: Couldn't create directory /user_defined/ reason: 'Permission denied': While executing ValuesBlockInputFormat: data for INSERT was parsed from query: (in query: insert into My_Table values(X). (DIRECTORY_DOESNT_EXIST)

Any ideas how to fix this??

**Comment by bunkiedc** [comment]
Not sure if this helps or not. I turned on trace for logging.  It looks like it's showing that the clickhouse-client is terminating the query.  Would clickhouse-client be looking for the user_defined directory?

Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.455339 [ 48 ] {} <Debug> TCPHandler: Connected ClickHouse client version 24.1.0, revision: 54466, database: My_DB, user: default.
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.456360 [ 48 ] {} <Debug> TCP-Session: 5f524ff4-36ac-4f24-86b5-8872ed7a35bc Authenticating user 'default' from 10.0.0.6:38342
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.457097 [ 48 ] {} <Debug> TCP-Session: 5f524ff4-36ac-4f24-86b5-8872ed7a35bc Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.457621 [ 48 ] {} <Debug> TCP-Session: 5f524ff4-36ac-4f24-86b5-8872ed7a35bc Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.494296 [ 48 ] {} <Trace> TCP-Session: 5f524ff4-36ac-4f24-86b5-8872ed7a35bc Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.496465 [ 48 ] {5d2440e8-e4c8-4bcf-bb23-9a817cfa1626} <Debug> executeQuery: (from 10.0.0.6:38342) insert into My_Table values (stage: Complete)
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.497281 [ 48 ] {5d2440e8-e4c8-4bcf-bb23-9a817cfa1626} <Trace> ContextAccess (default): Access granted: INSERT(MY_DATA) ON My_DB.My_Table
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.505539 [ 48 ] {5d2440e8-e4c8-4bcf-bb23-9a817cfa1626} <Information> TCPHandler: Change cancellation status from NOT_CANCELLED to FULLY_CANCELLED. Log message: Received 'Cancel' packet from the client, canceling the query.
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.521520 [ 48 ] {5d2440e8-e4c8-4bcf-bb23-9a817cfa1626} <Information> executeQuery: Code: 394. DB::Exception: Query was cancelled or a client has unexpectedly dropped the connection. (**QUERY_WAS_CANCELLED**) (version 23.12.2.59 (official build)) (from 10.0.0.6:38342) (in query: insert into My_Table values)
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.522424 [ 48 ] {5d2440e8-e4c8-4bcf-bb23-9a817cfa1626} <Debug> TCPHandler: Processed in 0.029306216 sec.
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.524586 [ 48 ] {} <Debug> TCPHandler: Done processing connection.
Feb 12 09:28:32 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:32.524954 [ 48 ] {} <Debug> TCP-Session: 5f524ff4-36ac-4f24-86b5-8872ed7a35bc Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
Feb 12 09:28:33 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:33.721600 [ 731 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 7 entries to flush up to offset 447
Feb 12 09:28:33 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:33.748358 [ 731 ] {} <Trace> system.metric_log (71864658-8943-47a6-adf5-35ade28b33ba): Trying to reserve 1.00 MiB using storage policy from min volume index 0
Feb 12 09:28:33 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:33.748511 [ 731 ] {} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 16.02 GiB.
Feb 12 09:28:33 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:33.763067 [ 731 ] {} <Trace> MergedBlockOutputStream: filled checksums 202402_59_59_0 (state Temporary)
Feb 12 09:28:33 3 3 node4 2ae9822fa3d7[1150]: 2024.02.12 17:28:33.774339 [ 731 ] {} <Trace> system.metric_log (71864658-8943-47a6-adf5-35ade28b33ba): Renaming temporary part tmp_insert_202402_59_59_0 to 202402_59_59_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).

**Comment by bunkiedc** [comment]
I don't think this closes this.  My configuration always had the correct path in the configuration file.

**Comment by SaltTan** [comment]
It seems to me that if there is no `user_defined_path` in config.xml then ClickHouse uses the current directory
https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/UserDefined/createUserDefinedSQLObjectsStorage.cpp#L40

The default value is supposed to be `<user_defined_path>/var/lib/clickhouse/user_defined/</user_defined_path>` but it is NOT present in the default config.xml.

As a workaround you could put this parameter into an override file in config.d

**Comment by SaltTan** [comment]
This PR might be related https://github.com/ClickHouse/ClickHouse/pull/57752

**Comment by bunkiedc** [comment]
@SaltTan Thanks for your response!  I run all my config's from config.d.  I have the general file config.xml located there, as well as macros.xml, docker_related_config.xml, and then depending on which servers we're talking about, there may also be clusters.xml as well.  I was told (above) that the path has to be present in the config.xml, but I validated the preprocessed_configs/config.xml (see above) and the line for clickhouse is there, as well as in my config.d/config.xml.  
I'm happy to test an alternate override file. To which override file can I add the path <user_defined_path>/var/lib/clickhouse/user_defined/</user_defined_path> ?

**Comment by SaltTan** [comment]
You can put it to any file.
Just check that it got merged into `/var/lib/clickhouse/preprocessed_configs/config.xml`

**Comment by bunkiedc** [comment]
The problem still exists.
I added it to the clusters.xml file like below:

```
<yandex>
    <remote_servers>
        ....removed....
    </remote_servers>
    <!-- Path to data directory, with trailing slash. -->
    <path>/var/lib/clickhouse/</path>
</yandex>
```

I only see it listed once in the /var/lib/clickhouse/preprocessed_configs/config.xml
around line 572.

```
   <validate_tcp_client_information>false</validate_tcp_client_information>

    <!-- Path to data directory, with trailing slash. -->
    <path>/var/lib/clickhouse/</path>

    <!-- Multi-disk configuration example: -->
   
    <storage_configuration>
```

**Comment by SaltTan** [comment]
You need to add this: `<user_defined_path>/var/lib/clickhouse/user_defined/</user_defined_path> `

**Comment by bunkiedc** [comment]
This may not matter, but just to remind you, these are in a containers. The path in the container is valid (/var/lib/clickhouse), and it's mapped outside the container to /var/lib/docker/volumes/clickhouse/_data.  The data looks consistent from both locations.

Container: drwxrwxrwx 18 clickhouse clickhouse 4096 Feb 27 11:34 /var/lib/clickhouse/
        Host: drwx-----x      3 root           root            4096 Feb  8  09:11 /var/lib/docker/volumes/clickhouse

**Comment by bunkiedc** [comment]
Oh crap... that path does **NOT** exist in my config.xml.  Let me add it and get back.

**Comment by bunkiedc** [comment]
Added it to the config.xml file, and it does now show up in /var/lib/clickhouse/preprocessed_configs/config.xml.
around line 2757:
`    <user_defined_path>/var/lib/clickhouse/user_defined/</user_defined_path>`

It still creates the directory, user_defined, in my home directory when doing an insert.

**Comment by aaron276h** [comment]
Seeing the same problem, is there a workaround for this?

**Comment by bunkiedc** [comment]
No, there's not been any work-around provided, or actually much activity.

**Comment by alexey-milovidov** [comment]
It reproduces:

```
milovidov@milovidov-pc:~$ clickhouse-client 
ClickHouse client version 24.4.1.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.4.1.

milovidov-pc :) CREATE TABLE test (x String) ENGINE = Memory

CREATE TABLE test
(
    `x` String
)
ENGINE = Memory

Query id: b440b6aa-0d8d-4529-9e65-d2bd3f007648

Ok.

0 rows in set. Elapsed: 0.006 sec. 

milovidov-pc :) Bye.

milovidov@milovidov-pc:~$ clickhouse-client --query "INSERT INTO test VALUES (xyz('abc'))"
Code: 46. DB::Exception: Unknown function xyz: While processing xyz('abc'): While executing ValuesBlockInputFormat: data for INSERT was parsed from query: (in query: INSERT INTO test VALUES (xyz('abc'))). (UNKNOWN_FUNCTION)

milovidov@milovidov-pc:~$ ls -ld user_defined
drwxrwxr-x 2 milovidov milovidov 4096 apr  6 21:34 user_defined
```
