### ISSUE TITLE
Did something change about the way merges are scheduled in 24.x?

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#59602]
Upon upgrading to 24.1 (from 23.11), we noticed a lot of merges getting stuck - never progressing no matter how much we waited. Eventually this filled up all the available slots for merges and they stopped happening at all.

Unfortunately I was not able to troubleshoot further as this is a production system - so we rolled back to 23.11 after confirming that the merge behavior persisted even across reboots.

Is there something significant that was changed in 24.x in the way merges are performed?

**Comment by CurtizJ** [comment]
Are merges hung with no progress during execution (it can be checked in `system.merges` table) or new merges are not being assigned?

Could you share the table definition of involved tables or at least used table engines if you cannot share the schema?

Please also share changed settings if any:
```sql
SELECT name, value FROM system.server_settings WHERE changed;

SELECT name, value FROM system.merge_tree_settings WHERE changed;
```

**Comment by andrea-s** [comment]
Merges hung indefinitely (we initially noticed the issue because the number of inodes was spiraling out of control, so checking the status of merges was the first idea).

As far as I could tell, it was not happening only on specific tables - in all cases though it was just regular MergeTree tables with monthly partitioning and default engine settings.


No changed settings from the merge_tree_settings_table.

Thank you

**Comment by CurtizJ** [comment]
Did you have any errors in log?

**Comment by andrea-s** [comment]
Nothing that seems to be relevant, unfortunately. I understand I'm giving out very sparse information here, due to the fact that we experienced this on a production system we needed to roll back very quickly, just wanted to put it out there in case something specific came to mind. Apologies for the vagueness otherwise.

**Comment by SaltTan** [comment]
related to https://github.com/ClickHouse/ClickHouse/pull/59812?

**Comment by andrea-s** [comment]
In my case we do have a value of 10485760 for merge_max_block_size_bytes, and we do have wide tables (~300 columns with many strings) - would that fit?

**Comment by alexey-milovidov** [comment]
@SaltTan, yes, this is it.

**Comment by andrea-s** [comment]
I can confirm that upgrading to 24.1.5.6 fixed the "infinite merge" issue - but it seems that drop and rename commands on the same tables are now stuck forever. 

Again there's hardly anything we can use in the logs, we just see that for instance a "drop" command on one of the tables which used to be stuck in the merge, just never completes. We need to delete files from disk to actually make the table disappear.

Is there some other known problem?

**Comment by andrea-s** [comment]
P.S. if it helps, even after rolling back to 23.11.1.2711, the tables that exhibit this "forever stuck" behavior cannot be dropped.
