### ISSUE TITLE
arrayReduce: Logical error: 'Bad cast from type DB::ColumnVector<double> to DB::ColumnNullable'.

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#59600]
Report: https://s3.amazonaws.com/clickhouse-test-reports/59564/69794833f5d75be4a8097b6c70b335187103a989/ast_fuzzer__ubsan_/report.html

```
SELECT arrayReduce(toNullable('stddevSampOrNull'), [1])
```

**Comment by Algunenano** [comment]
Another one from https://s3.amazonaws.com/clickhouse-test-reports/0/a122857b6eed413e5a9bc985fe0155252847bef6/ast_fuzzer__ubsan_/report.html

```sql
SELECT arrayReduce(toNullable('median'), [toDecimal32OrNull(toFixedString('1', 1), 2), 8])
```

**Comment by Algunenano** [comment]
Another one:
```
SELECT toFixedString('--- Int Empty ---', toLowCardinality(17)), arrayReduce(toNullable('avgOrNull'), [1])
```

**Comment by davenger** [comment]
`SELECT materialize(1), arrayReduce(toNullable('avgOrNull'), [1])`
https://s3.amazonaws.com/clickhouse-test-reports/59854/309db427e76aea295ffb3b5e6e787fa6fc0bdf2c/ast_fuzzer__debug_.html
