### ISSUE TITLE
Projection is not used

### ISSUE THREAD

**Issue by vad0** [ClickHouse/ClickHouse#59611]
ClickHouse server version 23.12.2

I have a table:
```
CREATE TABLE IF NOT EXISTS dijkstra.stats
(
    name LowCardinality(String),
    timestamp DateTime64(9, 'UTC'),
    payload Array(Float64)
)
ENGINE = ReplacingMergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (name, timestamp)
```

And a projection:
```
ALTER TABLE stats
    ADD PROJECTION names (SELECT name
                          GROUP BY name);
ALTER TABLE stats
    MATERIALIZE PROJECTION names;
```

Projection is not used for this query:
```
SELECT DISTINCT name
FROM stats;
```

But it is used for this query:
```
SELECT name
FROM stats
GROUP BY name;
```
These are identical queries. Projection should be used for both of them.

P.S.
The ClickHouse rejects the following projection query, although is it identical to the aforementioned one:
```
ALTER TABLE stats
    ADD PROJECTION names (SELECT DISTINCT name);
```

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/33615
