### ISSUE TITLE
 Read beyond last offset While executing ParallelParsingBlockInputFormat: While executing S3.

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#59615]
**Describe what's wrong**

Issue with parallel parsing of CSV

**Does it reproduce on recent release?**

Yes, 23.11

**Enable crash reporting**

```
SELECT count(DISTINCT toInt64(value))
FROM s3('https://storage.googleapis.com/file.csv*',
'<REDACTED>', '<REDACTED>', 'CSVWithNames',
'value String')

DB::Exception: Read beyond last offset (17825792 > 16996325, info: ): While executing ParallelParsingBlockInputFormat: While executing S3. (LOGICAL_ERROR) (version 23.11.4.24 (official build))
```

**Expected behavior**

Query works

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by UnamedRus** [comment]
Doesn't work even with non parallel parsing
.... SETTINGS input_format_parallel_parsing = 0;
Code: 49. DB::Exception: Read beyond last offset (2097152 > 1049005, info: ): While executing CSVRowInputFormat:

**Comment by UnamedRus** [comment]
SETTINGS max_read_buffer_size_remote_fs = 10485760

Make query run, but return wrong result: 97407 

SETTINGS  remote_filesystem_read_method='read'

Result 219785 

Something wrong with async thread pools which lead to ~silent corruption of imported data

**Comment by alexey-milovidov** [comment]
Does it reproduce on the most recent release?

**Comment by UnamedRus** [comment]
```
SETTINGS remote_filesystem_read_method='read' (even with input_format_parallel_parsing = 0)
```

Code: 6. DB::Exception: Cannot parse string '312321321\\rVALUE' as Int64: syntax error at position 9 (parsed just '312321321'). Note: there are toInt64OrZero and toInt64OrNull functions, which returns zero/NULL instead of throwing exception.: while executing 'FUNCTION toInt64(VALUE :: 0) -> toInt64(VALUE) Int64 : 1'. (CANNOT_PARSE_TEXT)


value (312321321) occurs at line 968,427 of 4,677,477 rows in the single-column file

**Comment by alexey-milovidov** [comment]
How to reproduce?

**Comment by UnamedRus** [comment]
> SETTINGS remote_filesystem_read_method = 'read', remote_filesystem_read_prefetch=0;

Looks like doesn't trigger parsing issue. 

> How to reproduce?

I'll check if we can share dataset in any form.

**Comment by UnamedRus** [comment]
> SETTINGS remote_filesystem_read_method='read'
> Cannot parse string '312321321\rVALUE'

CSVWithNames + input_format_csv_detect_header=1(default value); Error 

CSVWithNames + input_format_csv_detect_header=0; OK

CSV + input_format_csv_detect_header=1(default value); OK

Seems, there is double detection of header happens for CSVWithNames  and enabled `input_format_csv_detect_header`

Plus, CSV file use \r\n as line terminator

**Comment by alexey-milovidov** [comment]
No info.
