### ISSUE TITLE
Is it wrong in `joinRightColumnsSwitchNullability` ?

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#59625]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

In `joinRightColumnsSwitchNullability`
```C++
template <JoinKind KIND, JoinStrictness STRICTNESS, typename KeyGetter, typename Map>
size_t joinRightColumnsSwitchNullability(
    std::vector<KeyGetter> && key_getter_vector,
    const std::vector<const Map *> & mapv,
    AddedColumns & added_columns,
    JoinStuff::JoinUsedFlags & used_flags)
{
    if (added_columns.need_filter)
    {
        return joinRightColumnsSwitchMultipleDisjuncts<KIND, STRICTNESS, KeyGetter, Map, true>(std::forward<std::vector<KeyGetter>>(key_getter_vector), mapv, added_columns, used_flags);
    }
    else
    {
        return joinRightColumnsSwitchMultipleDisjuncts<KIND, STRICTNESS, KeyGetter, Map, true>(std::forward<std::vector<KeyGetter>>(key_getter_vector), mapv, added_columns, used_flags);
    }
}
```

The two branches are the same, is it something wrong?

**Comment by alexey-milovidov** [comment]
@lgbo-ustc, could you please send a pull request?

**Comment by lgbo-ustc** [comment]
> @lgbo-ustc, could you please send a pull request?

OK
