### ISSUE TITLE
A setting `http_response_headers`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59620]
**Use case**

Often times ClickHouse is queried directly from the browser.
Let's allow to set up headers for caching in the browser, to change the content-type of the response, or set a cookie.

**Describe the solution you'd like**

A setting `http_response_headers` which is a `Map(String, String)`.
The headers are either added to the response or override the response.
The headers should be checked for the allowed set of characters.
Some headers cannot be overridden.

**Caveats?**

The expected scenario is when you configure this setting inside a view or parameterized view or on a user level, and keep it readonly. But I don't see any caveats even if it is controlled by a client.

**Comment by GSokol** [comment]
In further versions of the implementation for dynamic handlers maybe useful to set headers from query result (somehow).

**Comment by alexey-milovidov** [comment]
Ok, but I thought about making it also a query-level setting.

```
SELECT screenshot FROM table FORMAT Raw
SETTINGS http_response_headers = [('Content-Type', 'image/png')]
```

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/pull/65254

**Comment by alexey-milovidov** [comment]
@GSokol, thank you, this will be wonderful!

@den-crane, the linked PR looks very ad-hoc compared to this feature request.
For example, I want `image/png` for RawBLOB.

**Comment by den-crane** [comment]
> @den-crane, the linked PR looks very ad-hoc compared to this feature request.
> For example, I want `image/png` for RawBLOB.

I just don't like that Clickhouse has two ways to define Content-Type

**Comment by alexey-milovidov** [comment]
This feature is relevant and we need it!

**Comment by alexey-milovidov** [comment]
I need this.
