### ISSUE TITLE
Structured Logging: see `"level": "4"` instead of `"level": "warning"`

### ISSUE THREAD

**Issue by luluz66** [ClickHouse/ClickHouse#59685]
**Describe the unexpected behaviour**
With structured logging, I'm expecting the log entry has a string value for the field `level`, e.g. `"level": "warning"`, but instead I see `"level": "4"` 

**How to reproduce**
* Which ClickHouse server version to use: 23.8 
Enable structured logging with
```
<logger> 
  <formatting>
     <type>json</type>
  </formating>
</logger>
```

**Expected behavior**
The log entries have `"level": "warning"` in the json payload

**Additional context**
I would like to see structured logging in Google Cloud Logging. I was planning to translate "level" to severity, and Google Cloud Logging should be able to recognize it, according to "https://cloud.google.com/logging/docs/agent/logging/configuration#timestamp-processing"

**Comment by alexey-milovidov** [comment]
Only major bug fixes are ported to previous versions.
