### ISSUE TITLE
tryPrepareSetIndex segfault 

### ISSUE THREAD

**Issue by kondratspb** [ClickHouse/ClickHouse#5969]
We ha the issue when run SELECT query with some subqueries
```
Trace:
2019.07.10 13:23:57.251907 [ 65 ] {} <Error> BaseDaemon: ########################################
2019.07.10 13:23:57.251952 [ 65 ] {} <Error> BaseDaemon: (version 19.8.3.8 (official build)) (from thread 55) Received signal Segmentation fault (11).
2019.07.10 13:23:57.251970 [ 65 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.07.10 13:23:57.251980 [ 65 ] {} <Error> BaseDaemon: Access: read.
2019.07.10 13:23:57.251990 [ 65 ] {} <Error> BaseDaemon: Address not mapped to object.
2019.07.10 13:23:57.323787 [ 65 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(DB::sortBlock(DB::Block&, std::vector<DB::SortColumnDescription, std::allocator<DB::SortColumnDescription> > const&, unsigned long)+0xb6b) [0x6e4afcb]
2019.07.10 13:23:57.323828 [ 65 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::MergeTreeSetIndex::MergeTreeSetIndex(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > const&, std::vector<DB::MergeTreeSetIndex::KeyTuplePositionMapping, std::allocator<DB::MergeTreeSetIndex::KeyTuplePositionMapping> >&&)+0x3fb) [0x6deeccb]
2019.07.10 13:23:57.323845 [ 65 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::KeyCondition::tryPrepareSetIndex(std::vector<std::shared_ptr<DB::IAST>, std::allocator<std::shared_ptr<DB::IAST> > > const&, DB::Context const&, DB::KeyCondition::RPNElement&, unsigned long&)+0x433) [0x6fc3ec3]
2019.07.10 13:23:57.323860 [ 65 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::KeyCondition::atomFromAST(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::Block&, DB::KeyCondition::RPNElement&)+0x156) [0x6fc5516]
2019.07.10 13:23:57.323879 [ 65 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::KeyCondition::traverseAST(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::Block&)+0x157) [0x6fc8b77]
2019.07.10 13:23:57.323893 [ 65 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::KeyCondition::traverseAST(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::Block&)+0x10a) [0x6fc8b2a]
2019.07.10 13:23:57.323910 [ 65 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::KeyCondition::KeyCondition(DB::SelectQueryInfo const&, DB::Context const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<DB::ExpressionActions> const&)+0x474) [0x6fc90e4]
2019.07.10 13:23:57.323941 [ 65 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::MergeTreeDataSelectExecutor::readFromParts(std::vector<std::shared_ptr<DB::MergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::MergeTreeDataPart const> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, long> > > const*) const+0x562) [0x702d462]
2019.07.10 13:23:57.323964 [ 65 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::MergeTreeDataSelectExecutor::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, long> > > const*) const+0x77) [0x7030e87]
2019.07.10 13:23:57.323979 [ 65 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::read(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0x36d) [0x6f637cd]
2019.07.10 13:23:57.323993 [ 65 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x202a) [0x6d3838a]
2019.07.10 13:23:57.324005 [ 65 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x6f7) [0x6d3b9e7]
2019.07.10 13:23:57.324020 [ 65 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x4f) [0x6d3e54f]
2019.07.10 13:23:57.324033 [ 65 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x6c) [0x6d49a8c]
2019.07.10 13:23:57.324044 [ 65 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x38) [0x6d4a328]
2019.07.10 13:23:57.324054 [ 65 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server() [0x6e4368f]
2019.07.10 13:23:57.324066 [ 65 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool)+0x74) [0x6e45224]
2019.07.10 13:23:57.324077 [ 65 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x730) [0x3a18d70]
2019.07.10 13:23:57.324088 [ 65 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3a193bb]
2019.07.10 13:23:57.324098 [ 65 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x79ee7df]
2019.07.10 13:23:57.324109 [ 65 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x79eef19]
2019.07.10 13:23:57.324119 [ 65 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7a9fb91]
2019.07.10 13:23:57.324130 [ 65 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x7a9bf98]
2019.07.10 13:23:57.324140 [ 65 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server() [0xb79aaef]
2019.07.10 13:23:57.324150 [ 65 ] {} <Error> BaseDaemon: 24. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fde6677b6ba]
```
Query:
```
SELECT
    mac,
    uniqExact(localDateTime) AS sessCnt,
    min(localDateTime) AS minDateTime,
    max(localDateTime) AS maxDateTime
FROM ...
WHERE ((localDateTime >= '2019-07-01 00:00:00') AND (localDateTime <= '2019-07-10 03:59:59')) AND ((mac, zone) IN
(
    SELECT (mac, zone)
    FROM
    (
        SELECT
            mac,
            zone,
            uniqExact(localDate) AS dCnt
        FROM ...
        WHERE (zone = 6741) AND ((localDateTime >= '2019-07-01 00:00:00') AND (localDateTime <= '2019-07-10 03:59:59'))
        GROUP BY
            mac,
            zone
    ) AS z
    WHERE z.dCnt >= 2
))
GROUP BY mac
```
ClickHouse server version 19.9.3 revision 54421
```
CREATE TABLE ... (
    `localDate` Date DEFAULT toDate(localDateTime),
    `localDateTime` DateTime,
    `timestamp` UInt32,
    `id` String,
    `mac` String,
    `zone` Int32,
    `assoc` Int8,
    `radio` String,
    `rssi` Float64,
    `freq` Float64,
    `vendor` Int64
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/.../...', '{replica},{replica2}') 
PARTITION BY toYYYYMM(localDateTime)
ORDER BY (id, localDateTime, mac, zone, vendor)
SETTINGS index_granularity = 8192
```

**Comment by filimonov** [comment]
>  2019.07.10 13:23:57.251952 [ 65 ] {} BaseDaemon: (version *19.8.3.8* (official build)) (from thread 55) Received signal Segmentation fault (11). 
> ... 

It looks like 19.8.3 not 19.9

**Comment by kondratspb** [comment]
Yes, sorry. I got log before upgarde. Here is the trace after upgrade:
2019.07.10 14:20:07.191449 [ 64 ] {} <Error> BaseDaemon: ########################################
2019.07.10 14:20:07.191687 [ 64 ] {} <Error> BaseDaemon: (version 19.9.3.31 (official build)) (from thread 43) Received signal Segmentation fault (11).
2019.07.10 14:20:07.191764 [ 64 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.07.10 14:20:07.191807 [ 64 ] {} <Error> BaseDaemon: Access: read.
2019.07.10 14:20:07.191830 [ 64 ] {} <Error> BaseDaemon: Address not mapped to object.
2019.07.10 14:20:07.372489 [ 64 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(DB::sortBlock(DB::Block&, std::vector<DB::SortColumnDescription, std::allocator<D
B::SortColumnDescription> > const&, unsigned long)+0xb6b) [0x67f1b0b]
2019.07.10 14:20:07.372620 [ 64 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(DB::MergeTreeSetIndex::MergeTreeSetIndex(std::vector<COW<DB::IColumn>::immutable_
ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > > const&, std::vector<DB::MergeTreeSetIndex::KeyTuplePositionMapping, std::allocator<DB:
:MergeTreeSetIndex::KeyTuplePositionMapping> >&&)+0x3fb) [0x67957fb]
2019.07.10 14:20:07.372672 [ 64 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::KeyCondition::tryPrepareSetIndex(std::vector<std::shared_ptr<DB::IAST>, std::
allocator<std::shared_ptr<DB::IAST> > > const&, DB::Context const&, DB::KeyCondition::RPNElement&, unsigned long&)+0x433) [0x6969b13]
2019.07.10 14:20:07.372717 [ 64 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::KeyCondition::atomFromAST(std::shared_ptr<DB::IAST> const&, DB::Context const
&, DB::Block&, DB::KeyCondition::RPNElement&)+0x156) [0x696b166]
2019.07.10 14:20:07.372756 [ 64 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::KeyCondition::traverseAST(std::shared_ptr<DB::IAST> const&, DB::Context const
&, DB::Block&)+0x157) [0x696e7c7]
2019.07.10 14:20:07.372796 [ 64 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::KeyCondition::traverseAST(std::shared_ptr<DB::IAST> const&, DB::Context const
&, DB::Block&)+0x10a) [0x696e77a]
2019.07.10 14:20:07.372855 [ 64 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::KeyCondition::KeyCondition(DB::SelectQueryInfo const&, DB::Context const&, st
d::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::
allocator<char> > > > const&, std::shared_ptr<DB::ExpressionActions> const&)+0x474) [0x696ed34]
2019.07.10 14:20:07.372971 [ 64 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::MergeTreeDataSelectExecutor::readFromParts(std::vector<std::shared_ptr<DB::Me
rgeTreeDataPart const>, std::allocator<std::shared_ptr<DB::MergeTreeDataPart const> > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::alloc
ator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQueryInfo const&, DB::Context const&,
 unsigned long, unsigned int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long, std::hash<std::__cxx11::basic_st
ring<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::alloc
ator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, long> > > const*) const+0x562) [0x69d2fc2]
2019.07.10 14:20:07.373067 [ 64 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::MergeTreeDataSelectExecutor::read(std::vector<std::__cxx11::basic_string<char
, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQ
ueryInfo const&, DB::Context const&, unsigned long, unsigned int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, lo
ng, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, long> > > const*) const+0x77)
[0x69d69e7]
2019.07.10 14:20:07.373138 [ 64 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::StorageReplicatedMergeTree::read(std::vector<std::__cxx11::basic_string<char,
 std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, DB::SelectQu
eryInfo const&, DB::Context const&, DB::QueryProcessingStage::Enum, unsigned long, unsigned int)+0x36d) [0x69094ed]
2019.07.10 14:20:07.373227 [ 64 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum,
DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha
r> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x202a) [0x66def4a]
2019.07.10 14:20:07.373289 [ 64 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, s
td::shared_ptr<DB::IBlockInputStream> const&, bool)+0x6f7) [0x66e25d7]
2019.07.10 14:20:07.373328 [ 64 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x4f) [0x66e513f]
2019.07.10 14:20:07.373366 [ 64 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x6c) [0x66f06
9c]
2019.07.10 14:20:07.373408 [ 64 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum,
DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::PrewhereInfo> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha
r> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x731) [0x66dd651]
2019.07.10 14:20:07.373447 [ 64 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, s
td::shared_ptr<DB::IBlockInputStream> const&, bool)+0x6f7) [0x66e25d7]
2019.07.10 14:20:07.373498 [ 64 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::InterpreterSelectQuery::executeWithMultipleStreams()+0x4f) [0x66e513f]
2019.07.10 14:20:07.373557 [ 64 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::executeWithMultipleStreams()+0x6c) [0x66f06
9c]
2019.07.10 14:20:07.373611 [ 64 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::InterpreterSelectWithUnionQuery::execute()+0x38) [0x66f0f38]
2019.07.10 14:20:07.373662 [ 64 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server() [0x67ea1bf]
2019.07.10 14:20:07.373718 [ 64 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::fun
ction<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::function<void (std::__cxx11::basic_string<char, std::char_tra
its<char>, std::allocator<char> > const&)>)+0x134) [0x67ebfe4]
2019.07.10 14:20:07.373798 [ 64 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Ne
t::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x1902) [0x39be172]
2019.07.10 14:20:07.373876 [ 64 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPSer
verResponse&)+0x3f1) [0x39c0c81]
2019.07.10 14:20:07.373944 [ 64 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x32c) [0x739a87c]
2019.07.10 14:20:07.373995 [ 64 ] {} <Error> BaseDaemon: 24. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x739579f]
2019.07.10 14:20:07.374030 [ 64 ] {} <Error> BaseDaemon: 25. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x7395ed9]
2019.07.10 14:20:07.374064 [ 64 ] {} <Error> BaseDaemon: 26. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x7446b51]
2019.07.10 14:20:07.374099 [ 64 ] {} <Error> BaseDaemon: 27. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x7442f58]
2019.07.10 14:20:07.374130 [ 64 ] {} <Error> BaseDaemon: 28. /usr/bin/clickhouse-server() [0xb1a369f]
2019.07.10 14:20:07.374156 [ 64 ] {} <Error> BaseDaemon: 29. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f87617fd6ba]

**Comment by kondratspb** [comment]
If I change schema to this (remove some columns from ORDER BY index):
CREATE TABLE ... (localDate Date DEFAULT toDate(localDateTime), localDateTime DateTime, timestamp UInt32, id String, mac String, zone Int32, assoc Int8, radio String, rssi Float64, freq Float64, vendor Int64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/.../...', '{replica},{replica2}') PARTITION BY toYYYYMM(localDateTime) ORDER BY (id, localDateTime) SETTINGS index_granularity = 8192
Everything is working fine

**Comment by 4ertus2** [comment]
Does it depend on data inserted? Could you make a reproducible sample that does not need special data?

**Comment by kondratspb** [comment]
> 
> 
> Does it depend on data inserted? Could you make a reproducible sample that does not need special data?

No, it doesn't depend. It repeats if no data in table

**Comment by alexey-milovidov** [comment]
Looks like something is wrong in 
`(tuple) IN (subquery)` when tuple contains columns from PK.

This issue is most likely not fixed yet... But it will help if you will reproduce it in version 19.13 and post a stack trace here.

Also please install `clickhouse-common-static-dbg` package before reproducing.
