### ISSUE TITLE
Choosing between DROP PARTITION and DELETE IN PARTITION

### ISSUE THREAD

**Issue by tzaretskaya** [ClickHouse/ClickHouse#59704]
I need to reload data for a time period (about 1-3 hours) within a single day -- it's a rare fallback operation. If I drop a partition and insert the data it takes about 4-6 hours. My goal is lowest execution time. What about `DELETE IN PARTITION`? Is it more efficient than `DROP PARTITION` coupled with insertion?

_Originally posted by @tzaretskaya in https://github.com/ClickHouse/ClickHouse/issues/7192#issuecomment-1931773818_

**Comment by UnamedRus** [comment]
Table engine, partition key

amount of updated rows per single day

**Comment by tzaretskaya** [comment]
Column event_date has type `Date`
```
engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/...', '{replica}')
PARTITION BY toYYYYMMDD(event_date)
ORDER BY (event_date, x_id, y_id)
SETTINGS index_granularity = 8192;
```
Peak day statistics:
- amount of rows: 290M
- amount of rows that I want to reload: 20M


There is a second table which is a bit different:
```
engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/...', '{replica}')
PARTITION BY toYYYYMMDD(event_date)
ORDER BY event_date
SETTINGS index_granularity = 8192;
```
Peak day statistics:
- amount of rows: 420M
- amount of rows that I want to reload: 25M

**Comment by UnamedRus** [comment]
Delete in partition looks a bit cheaper.

You also can do that in separate tmp table

1. ALTER TABLE tmp ATTACH PARTITION ID xxx FROM  prod (cheap, doesn't write anything on disk)
2. ALTER TABLE tmp DELETE .....
3. INSERT INTO tmp ....
4. ALTER TABLE prod REPLICA PARTITION ID 'xxx' FROM tmp

**Comment by tzaretskaya** [comment]
Thank you very much!
Did you mean REPLACE PARTITION instead of REPLICA PARTITION at step 4? I can find no such entry in Clickhouse docs.

**Comment by UnamedRus** [comment]
Yes, it should be REPLACE PARTITION ID
