### ISSUE TITLE
Clickhouse server memory usage goes over max_server_memory_usage

### ISSUE THREAD

**Issue by yujiarista** [ClickHouse/ClickHouse#59744]
We are running a 3 node Clickhouse cluster on version 23.10.4.25. Each node is configured with 220G memory. max_server_memory_usage and max_server_memory_usage_to_ram_ratio is set to default so we are expecting memory usage to be below 198G. 
However, we recently observed (from kubernetes container metric) a sudden memory increase from 135G to 215G in 10 minutes on one node. It decreased slowly afterward but was above 198G for several hours. During the time, server load is normal and stable, and ClickHouseMetrics_MemoryTracking and ClickHouseAsyncMetrics_MemoryResident are only around 10G.

I would like to ask
What are ClickHouseMetrics_MemoryTracking and ClickHouseAsyncMetrics_MemoryResident actually reflecting?
Are there more reliable ways to limit memory usage?

Thank you!

**Comment by nickitat** [comment]
first of all let's verify what are the actual setting values:

``` sql
select getSetting('max_memory_usage'), getSetting('max_memory_usage_for_user');

select name, value from system.server_settings where name like '%max_server_memory_usage%';
```

https://github.com/ClickHouse/ClickHouse/blob/f663f13a35a9c5ac5a2169d9676ad1d11b463a51/src/Common/CurrentMetrics.cpp#L55

https://github.com/ClickHouse/ClickHouse/blob/f663f13a35a9c5ac5a2169d9676ad1d11b463a51/src/Common/AsynchronousMetrics.cpp#L622

**Comment by yujiarista** [comment]
select getSetting('max_memory_usage'), getSetting('max_memory_usage_for_user');
returns 0,0

select name, value from system.server_settings where name like '%max_server_memory_usage%';
returns
max_server_memory_usage, 212600881152
max_server_memory_usage_to_ram_ratio, 0.9

**Comment by yujiarista** [comment]
Turns out there was some misunderstanding about the kubernetes container metric.
