### ISSUE TITLE
when select data, occur memory exceed exception

### ISSUE THREAD

**Issue by rnrl1215** [ClickHouse/ClickHouse#59742]
Click House has 2 billion  data with cluster

The table was created with the following query:

CREATE TABLE test.user_log
(
created_at DateTime,
user_id UInt64,
age UInt64,
sex String,
event_name String,
action_name String,
keys Array(String),
values Array(String)
)
ENGINE = MergeTree
ORDER BY (created_at, event_name, action_name);

When performing a query occuer excceed memory exception

used memory: 18.84
max memory: 18.64

select * from 
created_at >= '2024-02-08 00:00:00'
created_at <= '2024-02-08 23:59:59'

Memory config
server1, 2, 3: max memory: 18.64

config: 
     - max_server_memory: 20
     - max_server_memory_usage_to_ram_ratio: 1.2

**Comment by alexey-milovidov** [comment]
Often, it means that you don't have enough memory on the machines, and you should scale them up.

But you can also configure your query for lower memory usage by using these two settings:
- `max_threads`: lower the number of query processing threads, and it will lower the memory usage proportionally in the expense of speed;
- `max_block_size`: lower it a few times from the default value, and it will also lower the memory usage proportionally in some expense of speed;
