### ISSUE TITLE
arrayFold: Logical error: 'Cannot capture column 3 because it has incompatible type: got Int64, but LowCardinality(Int64) is expected.'

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#59809]
Report: https://s3.amazonaws.com/clickhouse-test-reports/0/548cc2577b41f04a93494205a54e8506ff2b230c/ast_fuzzer__debug_.html

```sql
SELECT arrayFold((acc, x) -> (acc + (x * 2)), [1, 2, 3, 4], toInt64(toLowCardinality(3)))
```

2024.02.09 15:55:03.320496 [ 358270 ] {48e9a48c-0c6b-4bbf-8a10-14cb03de7b4e} <Fatal> : Logical error: 'Cannot capture column 3 because it has incompatible type: got Int64, but LowCardinality(Int64) is expected.'.

**Comment by azat** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/59531/1253a73a4556c86d98c782c5764e5aa8acddd748/ast_fuzzer__asan_.html
