### ISSUE TITLE
Can't run the UDF based on the documentation example https://clickhouse.com/docs/en/sql-reference/functions/udf 

### ISSUE THREAD

**Issue by jiaqimeng** [ClickHouse/ClickHouse#59829]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.
Version 24.1

I pulled docker image, followed the instructions https://clickhouse.com/docs/en/sql-reference/functions/udf to 
1. SSH into the container
2. Add the test_function.xml (checked the log that it is correctly loaded)
3. Add test_function.py in /var/lib/clickhouse/user_scripts and chmod 777
4. Restart the docker container
5. SELECT test_function_python(1) 

I get 
Code: 302. DB::Exception: Received from localhost:9000. DB::Exception: Child process was exited with return code 88: While processing test_function_python('1'). (CHILD_WAS_NOT_EXITED_NORMALLY)

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by ivanov17andrey** [comment]
Why did you close it? Were you able to make it work? @jiaqimeng
