### ISSUE TITLE
Comparison between IPv4 and IPv6

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#59849]
**Use case**

`SELECT toIPv4('127.0.0.1') = toIPv6('::ffff::127.0.0.1')`

**Comment by Blargian** [comment]
Hey @logancol, I noticed that you wrote some code for this issue already. It looks to me like you opened a PR for it on your own fork of ClickHouse. You'll need to open the PR on ClickHouse/ClickHouse repo to get it merged. 

I wouldn't want your work already to go unnoticed - feel free to give me a shout if you have any issues with opening the PR on the ClickHouse repo. :)

**Comment by sarielwxm** [comment]
I want to work on this task if logancol is not working on it anymore.

**Comment by sarielwxm** [comment]
Is the aim of this work to implement two functions? But I notice that toIPv6 seems to exist now.

**Comment by Beetelbrox** [comment]
Hallo! I've opened a PR with an implementation proposal here: #64292
