### ISSUE TITLE
Customizable query block for distributed engine.

### ISSUE THREAD

**Issue by kindred77** [ClickHouse/ClickHouse#5986]
We got a query, it will take several seconds, but I think it can be faster:

-- query 1
select consume_grade,count(1) cnt
from (
    -- query 2
    select multiIf( total_trans_amt < 50 ,1,
        total_trans_amt >= 50 and total_trans_amt < 100 ,
        2,
        total_trans_amt >= 100 and total_trans_amt < 500 ,
        3,
        total_trans_amt >= 500 and total_trans_amt < 1000 ,
        4,
        total_trans_amt >= 1000 and total_trans_amt < 5000 ,
        5,
        total_trans_amt >= 5000,
        6,
        0) as consume_grade
    from
    (
        -- query 3
        select customer_id, sum(trans_amt) total_trans_amt
        from trans_detail
        group by customer_id
    ) t
) tt
group by consume_grade;

The trans_detail is a distributed table and the shard key is customer_id.

It seams only the query using distributed engine directly(query 3) will be distributed to all shards.
After execution of query 3, the result will be sent to the initial server for query 2, this is unefficient, since there's still a large resultset will be transformed by network.

In this scene, even the query 1 could be distributed to all shards, because the shard key is customer_id, and after this only 6 records in each shard will be sent to the initial server.
I can put a additional sum to get the final result like this:
select consume_grade,sum(cnt)
from (
    -- query 1
);

So it will be great if clickhouse can support me setting the distributed query block.

**Comment by alexey-milovidov** [comment]
CC @azat 

Yes, it makes sense. If we apply GROUP BY sharding key, we can process it independently.
(if the setting to trust sharding key is enabled)

AFAIK it is already implemented, but I'm not sure if it works with subqueries.

**Comment by azat** [comment]
>AFAIK it is already implemented

Indeed, @kindred77 can you check the same query with `optimize_skip_unused_shards=1` and `optimize_distributed_group_by_sharding_key=1` (added in #10341 and #10373, v20.9.2.20-stable+) ?

Also if this will not work for you, can you please share the query execution log (`set send_logs_level=trace` and execute the query with those settings)

*Note, that even if those settings are available since 20.9, it will be great if you can check it using last stable, or something near it*

> but I'm not sure if it works with subqueries.

IIUC it should.
