### ISSUE TITLE
NATS Engine input format error

### ISSUE THREAD

**Issue by benmutlu** [ClickHouse/ClickHouse#59871]
I am trying to ship my logs to Clickhouse with using FluentBit and trying to get it with using NATS ENGINE.

First of all https://docs.fluentbit.io/manual/pipeline/outputs/nats  depends on this documentation, FluentBit sending logs with following format ; 

`Data format
For every set of records flushed to a NATS Server, Fluent Bit uses the following JSON format:
[
  [UNIX_TIMESTAMP, JSON_MAP_1],
  [UNIX_TIMESTAMP, JSON_MAP_2],
  [UNIX_TIMESTAMP, JSON_MAP_N],
]
Each record is an individual entity represented in a JSON array that contains a UNIX_TIMESTAMP and a JSON map with a set of key/values. A summarized output of the CPU input plugin will looks as this:
[
  [1457108504,{"tag":"fluentbit","cpu_p":1.500000,"user_p":1,"system_p":0.500000}],
  [1457108505,{"tag":"fluentbit","cpu_p":4.500000,"user_p":3,"system_p":1.500000}],
  [1457108506,{"tag":"fluentbit","cpu_p":6.500000,"user_p":4.500000,"system_p":2}]
]`

And when I try to create TABLE with following ;
```

CREATE TABLE fluentbit_stream (
    timestamp DateTime,
    tag String,
    cpu_p Float64,
    user_p Float64,
    system_p Float64
) ENGINE = NATS SETTINGS
    nats_url = 'nats://192.168.1.1:4222',
    nats_subjects = 'fluentbit_logs',
    nats_format = 'JSONEachRow',
    nats_num_consumers = 2,
    nats_queue_group = 'fluentbit_group',
    nats_max_reconnect = 10,
    nats_reconnect_wait = 2000;

```

Its giving parser error, Code: 27. DB::Exception: Cannot parse input: expected '{' before: '[1707730992.786222,{\"tag

How can I resolve or any suggestion regarding this format problem ?

**Comment by melvynator** [comment]
`[ [1457108504,{"tag":"fluentbit","cpu_p":1.500000,"user_p":1,"system_p":0.500000}], [1457108505,{"tag":"fluentbit","cpu_p":4.500000,"user_p":3,"system_p":1.500000}], [1457108506,{"tag":"fluentbit","cpu_p":6.500000,"user_p":4.500000,"system_p":2}] ]`

This is not JSON format. If you are not streaming the data in a common format you can process it at ingest time.

**Comment by benmutlu** [comment]
Hello looks like its because of FluentBit NATS output plugin, its sending with this format only and looks like not possible to change, I have solved changing FluentBit with Vector, vector output sending in JSON format and its suitable for ingest. 

Thank you so much for reply.

**Comment by melvynator** [comment]
Perfect! Thanks for letting us know your workaround.
