### ISSUE TITLE
Any way to record system.query_log into files?

### ISSUE THREAD

**Issue by CzyerChen** [ClickHouse/ClickHouse#59893]
In order to analysis executed SQLs by popular tools like fluentd, is there any way to record system.query_log into files rather than executing sqls? Thanks~

**Comment by alexey-milovidov** [comment]
It is possible by using a materialized view pushing to a table with the `File` engine.

**Comment by CzyerChen** [comment]
> It is possible by using a materialized view pushing to a table with the `File` engine.

Is it possible to support table to files in the future, or `using a materialized view pushing to a table with the File engine.` may be the best practice.

**Comment by CzyerChen** [comment]
> > It is possible by using a materialized view pushing to a table with the `File` engine.
> 
> Is it possible to support table to files in the future, or `using a materialized view pushing to a table with the File engine.` may be the best practice.

@alexey-milovidov  cloud you reply it?

**Comment by alexey-milovidov** [comment]
You can specify the table engine `File` in the configuration, and it will write directly to a file.

**Comment by CzyerChen** [comment]
> You can specify the table engine `File` in the configuration, and it will write directly to a file.

Yes, I have tried the way you said, that works.
But now actually bring in additional manual works because not support by configs.
