### ISSUE TITLE
Column of type Uint128 is an invalid sharding key 

### ISSUE THREAD

**Issue by AntonOyung** [ClickHouse/ClickHouse#59904]
**Describe the unexpected behaviour**
I'm trying to create a distributed table that is sharded on a UInt128 column, but the db is giving me an exception. Is a UInt128 a valid sharding key?  

**How to reproduce**
I create these tables 
```
CREATE TABLE IF NOT EXISTS replicatedTable ON CLUSTER metrics (
  metric String,
  my_id UInt128,
  ) ENGINE = ReplicatedReplacingMergeTree PRIMARY KEY (metric, my_id);

CREATE TABLE distributedTable ON CLUSTER metrics AS replicatedTable
ENGINE = Distributed(metrics, default, replicatedTable, my_id)
```

I try to insert into the distributed table and it fails with: 
```
insert into distributedTable values ('dummy', 123456)

Received exception from server (version 23.12.1):
Code: 53. DB::Exception: Received from localhost:9002. DB::Exception: Sharding key expression does not evaluate to an integer type. (TYPE_MISMATCH)
```

**Comment by melvynator** [comment]
The solution mentioned by @UnamedRus is generally the way to go, with regard to the right sharding keys types: 

https://github.com/ClickHouse/ClickHouse/blob/f48c5973ccec7fd71c71ca7a30c61af01725fd64/src/Storages/StorageDistributed.cpp#L1540C1-L1555C1
