### ISSUE TITLE
Inconsistent results when GROUP BY a Map() column when key is missing.

### ISSUE THREAD

**Issue by brookemckim** [ClickHouse/ClickHouse#59900]
When performing a `GROUP BY` on a specific key of a map column I am getting both unexpected and inconsistent behavior when the key is missing.

```
SELECT COUNT(*), tags['not_here'], tags['also_not_here'] FROM test GROUP BY tags['not_here'], tags['also_not_here']
``` 

<img width="1514" alt="Screenshot 2024-02-12 at 11 55 00 AM" src="https://github.com/ClickHouse/ClickHouse/assets/245680/8ddefc93-e20e-4b37-9b03-47521e1b5048">

```
SELECT COUNT(*), tags['also_not_here'] FROM test GROUP BY tags['also_not_here']
``` 
<img width="1509" alt="Screenshot 2024-02-12 at 11 55 25 AM" src="https://github.com/ClickHouse/ClickHouse/assets/245680/856bcff4-0634-4273-adb5-de0a6951ac83">

Version: 24.0.2.54390

```
CREATE TABLE test (
    `id` UUID DEFAULT generateUUIDv4(),
    `tags` Map(String, String)
) ENGINE = MergeTree PRIMARY KEY id;
```

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/59402

**Comment by brookemckim** [comment]
@den-crane thank you. I could not find anything 😓
