### ISSUE TITLE
parallel replicas are not used when custom key is set with prefer_localhost_replica = 1

### ISSUE THREAD

**Issue by chandrsoni** [ClickHouse/ClickHouse#59917]
query: select *. hostName() as h from test_db.test_table group by h settings prefer_localhost_replica = 1, parallel_replicas_custom_key = 'cityHash64(column)'

returns result from localhost and doesn't use any of the remote replicas

root cause: https://github.com/ClickHouse/ClickHouse/blob/025d82f47eb5951f7dba72295b6d5f1285e772d1/src/Interpreters/Context.cpp#L5129 checks for read_tasks and should also check for custom_key.

**Comment by devcrafter** [comment]
`CUSTOM_KEY` and `READ_TASKS` are two different modes. They are 2 independent implementations.
