### ISSUE TITLE
`LOGICAL_ERROR` using the new analyzer

### ISSUE THREAD

**Issue by antaljanosbenjamin** [ClickHouse/ClickHouse#59912]
**Describe what's wrong**

I got `LOGICAL_ERROR` when using new analyzer.

**Does it reproduce on the most recent release?**

I caught it on master https://s3.amazonaws.com/clickhouse-test-reports/59896/b094ab9763120ed03015e27eeb2f13247330a017/ast_fuzzer__asan_.html

**Enable crash reporting**

**How to reproduce**

```
SELECT toFixedString(materialize(toLowCardinality('=')), toLowCardinality(1))
GROUP BY toLowCardinality(1)
SETTINGS allow_experimental_analyzer = 1
```

**Expected behavior**

`LOGICAL_ERROR` is not thrown.

**Error message and/or stacktrace**

`Code: 49. DB::Exception: Expected single dictionary argument for function. (LOGICAL_ERROR)`

**Comment by azat** [comment]
Looks like duplicate of https://github.com/ClickHouse/ClickHouse/issues/58979

**Comment by antaljanosbenjamin** [comment]
> Looks like duplicate of https://github.com/ClickHouse/ClickHouse/issues/58979

Yes, somehow I didn't manage to find that one.
