### ISSUE TITLE
DB::Exception: Empty query 

### ISSUE THREAD

**Issue by lzy305** [ClickHouse/ClickHouse#5995]
version: 19.11.0.830
[DDL-SQL.txt](https://github.com/yandex/ClickHouse/files/3386989/DDL-SQL.txt)

I run a sql. Return an error message
Code: 62, e.displayText() = DB::Exception: Empty query (version 19.11.0.830 (official build))

[err_message.txt](https://github.com/yandex/ClickHouse/files/3386992/err_message.txt)

**Comment by alexey-milovidov** [comment]
Does not reproduce in master.
Does not reproduce in 19.11 either:

```
docker run --network host yandex/clickhouse-server:19.11

clickhouse-client -n < 01548_lzy305.sql
```
