### ISSUE TITLE
Clickhouse server no longer initializes default database

### ISSUE THREAD

**Issue by jktng** [ClickHouse/ClickHouse#59989]
Hey folks, as of this morning's [v24.1.4.20](https://github.com/ClickHouse/ClickHouse/releases/tag/v24.1.4.20-stable) release it looks like the database initialization step is erroneously skipped. 

I have a Github test workflow that launches a Clickhouse container from the latest image, and as of <5 hours ago the default database is no longer being created on container start. This corresponds with when we began pulling the 24.1.4.20 image.

At a glance, https://github.com/ClickHouse/ClickHouse/pull/59808 looks relevant. Is [this](https://github.com/AlexNik/ClickHouse/blob/68df20114508c838cff0dbc7bc0d7f81025a6bdf/docker/server/entrypoint.sh#L133) check supposed to be inverted?

**Comment by th0th** [comment]
I am not sure if it is the same issue, but when running in docker `CLICKHOUSE_DB` environment variable seems to ignored, and instead a database with name `default` is created. I noticed when my tests start to fail 😅

**Comment by littlebtc** [comment]
We also hit it in `23.12.x` branch. After seeing [comment](https://github.com/ClickHouse/ClickHouse/pull/59991#issuecomment-1979151309) and looking for source code, it seems that the following version had #59808 backported but not have this (#59991) backported:

* 23.3
* 23.8
* 23.12 (also 23)
* 24.1

Using Docker with the version listed about will still hit this issue. If you need any workaround to continue using those versions, see the referenced pull requests in #59808.
