### ISSUE TITLE
Request WHERE toHour(stamp, 'America/NewYork')  is not consistent with the result of toHour(stamp) 

### ISSUE THREAD

**Issue by tkanos** [ClickHouse/ClickHouse#59992]
Hello guys,

Using CH (23.9.2.56)

I have a really weird behavior on my ReplicatedMergeTree table (requested through a distributed table).
So I have a table like Table (stamp DateTime('UTC'), clicks UInt64),
And when I :
```
SELECT toHour(stamp, 'America/New_York'), sum(clicks)
FROM mytable
WHERE toDate(stamp, 'America/New_York') = '2024-02-01'
GROUP BY ALL;
```
I get something like (the numbers are made up, but it is a huge traffic table)

|  stamp(America/NewYork) | clicks  |
|---|---|
|  0 |  34   |
|  1 |   45  |
|  2 |  60  |
|  ... |   ... |
|  7 |   207 |
|  8 |   213 |

At 7AM (NY time) for example I get : sum(clicks) => 207.

But when I do a more precise request like just adding  AND toHour(stamp, 'America/NewYork') = 7:
```
SELECT toHour(stamp, 'America/New_York'), sum(clicks)
FROM mytable
WHERE toDate(stamp, 'America/New_York') = '2024-02-01'
AND toHour(stamp, 'America/New_York') = 7 
GROUP BY ALL;
```

I Have a different result like sum(clicks) => 93 :

|  stamp(America/NewYork) | clicks  |
|---|---|
|  7 |  93   |

But If I remove the 'America/New_York' and do the request in UTC time (7AM = 12 PM) the result stay consistent.

```
SELECT toHour(stamp, 'America/New_York'), sum(clicks)
FROM mytable
WHERE toDate(stamp, 'America/New_York') = '2024-02-01'
AND toHour(stamp) = 12 
GROUP BY ALL;
```

**How to reproduce**

Using Using CH (23.9.2.56)

- CREATE TABLE db.table_local ON CLUSTER '{cluster}'
(
    `stamp` DateTime('UTC'),
    ..... a lot of others column ....
    `clicks` UInt64 
)
ENGINE = ReplicatedMergeTree
PARTITION BY toDate(stamp)

-  CREATE TABLE db.table_local ON CLUSTER '{cluster}'
(
    `stamp` DateTime('UTC'),
    ..... a lot of others column ....
    `clicks` UInt64 
)
ENGINE = Distributed('db', 'db', 'table', rand())

- send a lot of request (some millions)
- then request playing on the where with the toHour function

**Expected behavior**

The data should be consistent using toHour(stamp, 'someplace') and without the someplace

**Comment by tkanos** [comment]
Just for more information, as workaround I now do :

```
SELECT toHour(stamp, 'America/New_York'), sum(clicks)
FROM mytable
WHERE toDate(stamp, 'America/New_York') = '2024-02-01'
AND toHour(toDateTime(stamp, 'America/Montreal')) = 7 
GROUP BY ALL;
```

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/be66ddb3-6ae6-433e-9285-0129402d6ef0

```sql

CREATE TABLE test
( stamp DateTime('UTC'))
ENGINE = MergeTree
PARTITION BY toDate(stamp)
order by tuple() as select toDateTime('2020-01-01')+number from numbers(1e6);


SELECT  countIf( toHour(toDateTime(stamp, 'America/Montreal')) = 7  ) result
FROM test
format Pretty;

+--------+
| result |
+--------+
|  43200 |
+--------+

SELECT  countIf( toHour(stamp, 'America/Montreal') = 7  ) result
FROM test
format Pretty;
+--------+
| result |
+--------+
|  43200 |
+--------+

SELECT  count() result
FROM test
WHERE toHour(toDateTime(stamp, 'America/Montreal')) = 7 
format Pretty;
+--------+
| result |
+--------+
|  43200 |
+--------+

SELECT  count() result
FROM test
WHERE toHour(identity(stamp), 'America/Montreal') = 7 
format Pretty;
+--------+
|  43200 |
+--------+

SELECT  count() result
FROM test
WHERE toHour(stamp, 'America/Montreal') = 7 
format Pretty;
+--------+
| result |
+--------+
|      0 |
+--------+
```

@amosbird

**Comment by amosbird** [comment]
The code to get monotonicity range of `toHour` is incorrect. https://github.com/ClickHouse/ClickHouse/pull/39037 only fixes cases when timezone info is attached to type. We should also check timezone in argument.
