### ISSUE TITLE
Clickhouse server consumes a little of CPU with zero load

### ISSUE THREAD

**Issue by doom369** [ClickHouse/ClickHouse#60016]
We have multiple low-end severs 1 vCPU and 1-2 GB RAM for testing purposes. All of the servers have 0 load (only periodic `SELECT timezone()` requests are executed via the connection pool to make sure connections are alive).

Server version **23.11.1.2711**:

![screenshot-cloud digitalocean com-2024 02 15-10_40_58](https://github.com/ClickHouse/ClickHouse/assets/1536494/f1b4bfcf-33de-4baf-b0f2-c9a6e165307b)

Server version **23.2.4.12**:
![screenshot-cloud digitalocean com-2024 02 15-10_42_29](https://github.com/ClickHouse/ClickHouse/assets/1536494/059f6876-a2c2-4566-8b74-786123360472)

Server version **23.1.3.5**:
![screenshot-cloud digitalocean com-2024 02 15-10_48_21](https://github.com/ClickHouse/ClickHouse/assets/1536494/9684947a-04f2-4cb3-a93b-612f314071d1)

Server version **22.2.2.1**:

![screenshot-cloud digitalocean com-2024 02 15-10_45_31](https://github.com/ClickHouse/ClickHouse/assets/1536494/7041f704-8497-46de-8242-f2683a78fc31)

All servers are Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
Installed via default inscruction - https://clickhouse.com/docs/en/install
No changes to the default config
Servers have only CH installed. There are no other processes that consume CPU, only CH server.

**Comment by rschu1ze** [comment]
Could you please check system tables `system.merges`, `system.mutations` (both will likely show nothing interesting if you insert/mutate nothing), as well as `system.processes`? To double-check which queries actually arrive, please also check `system.query_log`.

You could also run 'perf top` on the side to get insights into CPU-intensive activities inside ClickHouse.

**Comment by doom369** [comment]
@rschu1ze perf top:

```
   4.80%  clickhouse                [.] _ZNSt3__116__variant_detail12__visitation6__base12__dispatcherIJLm25EEE10__dispatchB6v15000IONS1_9__variant15__value_visitorIRZN2DB22MergingSortedAlgorithm5mergeEvE3$
   3.68%  clickhouse                [.] DB::ColumnLowCardinality::insertFrom
   3.44%  clickhouse                [.] DB::ReverseIndex<unsigned long, DB::ColumnString>::insert
   2.07%  clickhouse                [.] DB::ColumnVector<char8_t>::getUInt
   1.92%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::uniqueInsertFrom
   1.88%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::allocatedBytes
   1.79%  clickhouse                [.] memcpy
   1.57%  clickhouse                [.] DB::ColumnLowCardinality::allocatedBytes
   1.38%  [kernel]                  [k] finish_task_switch.isra.0
   1.27%  clickhouse                [.] DB::ColumnString::compareAt
   1.25%  clickhouse                [.] DB::ColumnVector<double>::insertFrom
   1.24%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::getNestedColumn
   1.24%  [kernel]                  [k] __lock_text_start
   1.20%  clickhouse                [.] DB::ColumnVector<char8_t>::insert
   1.08%  clickhouse                [.] DB::ColumnLowCardinality::Index::getSizeOfIndexType
```

**Comment by rschu1ze** [comment]
Depending on the batch size of the inserted data, a certain CPU consumption seems reasonable on a 1 vCPU system but you mentioned the inserts are small.

I'd probably watch `perf top` over the course of 2-3 minutes and check the top-3 hottest functions. (the output in https://github.com/ClickHouse/ClickHouse/issues/60016#issuecomment-1945703942 does not explain a sustained CPU consumption of at least 25%).

**Comment by doom369** [comment]
No changes after 5 minutes:

 ```
  6.52%  clickhouse                [.] _ZNSt3__116__variant_detail12__visitation6__base12__dispatcherIJLm25EEE10__dispatchB6v15000IONS1_9__variant15__value_visitorIRZN2DB22MergingSortedAlgorithm5mergeEvE3$
   4.20%  clickhouse                [.] DB::ColumnLowCardinality::insertFrom
   3.92%  clickhouse                [.] DB::ReverseIndex<unsigned long, DB::ColumnString>::insert
   2.52%  clickhouse                [.] DB::ColumnVector<char8_t>::getUInt
   2.26%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::uniqueInsertFrom
   2.04%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::allocatedBytes
   2.03%  clickhouse                [.] DB::ColumnLowCardinality::allocatedBytes
   1.77%  clickhouse                [.] memcpy
   1.62%  clickhouse                [.] DB::ColumnVector<double>::insertFrom
   1.56%  clickhouse                [.] DB::ColumnString::compareAt
   1.40%  clickhouse                [.] DB::ColumnVector<char8_t>::insert
   1.34%  clickhouse                [.] DB::ColumnLowCardinality::compareAt
   1.26%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::getNestedColumn
   1.20%  clickhouse                [.] DB::ColumnString::allocatedBytes
   1.18%  clickhouse                [.] DB::ColumnLowCardinality::Index::getSizeOfIndexType
   1.16%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::uniqueInsertData
   1.11%  clickhouse                [.] DB::ColumnVector<unsigned short>::compareAt
   1.08%  [kernel]                  [k] __lock_text_start
   1.08%  clickhouse                [.] ZSTD_compressBlock_doubleFast
   1.06%  clickhouse                [.] DB::ColumnVector<unsigned int>::compareAt
   1.02%  clickhouse                [.] DB::ColumnVector<unsigned short>::insertFrom
   0.97%  clickhouse                [.] sallocx
   0.96%  clickhouse                [.] DB::ColumnUnique<DB::ColumnString>::compareAt
   0.94%  [kernel]                  [k] finish_task_switch.isra.0
   0.90%  clickhouse                [.] DB::ColumnVector<char8_t>::allocatedBytes
   0.88%  clickhouse                [.] ZSTD_decompressSequences_bmi2
   0.87%  libc.so.6                 [.] 0x00000000001a104a
   0.85%  clickhouse                [.] DB::ColumnVector<unsigned int>::insertFrom
   0.80%  clickhouse                [.] DB::ColumnString::getDataAt
   0.71%  clickhouse                [.] operator delete
   0.70%  clickhouse                [.] operator new
   0.69%  clickhouse                [.] DB::NamesAndTypesList::tryGetByName
   0.65%  clickhouse                [.] DB::ColumnLowCardinality::Index::checkSizeOfType
   0.61%  clickhouse                [.] malloc
   0.59%  [kernel]                  [k] syscall_enter_from_user_mode
   0.59%  clickhouse                [.] DB::Field::~Field
   0.57%  [kernel]                  [k] __softirqentry_text_start
   0.57%  clickhouse                [.] libunwind::LocalAddressSpace::getEncodedP
   0.57%  clickhouse                [.] tcache_bin_flush_small
   0.52%  clickhouse                [.] CityHash_v1_0_2::CityHash128WithSeed
   0.52%  perf                      [.] dso__find_symbol
   0.52%  clickhouse                [.] ZSTD_decompress
   0.48%  clickhouse                [.] DB::ColumnVector<double>::allocatedBytes
   0.45%  perf                      [.] rb_next
   0.43%  clickhouse                [.] DB::ColumnVector<unsigned int>::allocatedBytes
   0.40%  [kernel]                  [k] exit_to_user_mode_loop
```

**Comment by rschu1ze** [comment]
The top function with 6.5% runtime looks like it is either applying FINAL in SELECT queries or somehow used in merges. Maybe you want to double check `system.query_log` and `sytem.part_log` (e.g. use `event_type = MergeParts`)

**Comment by doom369** [comment]
@rschu1ze why close? I haven't chance to dig more into it.

**Comment by den-crane** [comment]
@doom369 

try

1) 
```
cat /etc/clickhouse-server/config.d/asynchronous_metrics_update_period_s.xml
<clickhouse>
    <asynchronous_metrics_update_period_s>60</asynchronous_metrics_update_period_s>
</clickhouse>
```

if does not help then try

```
cat /etc/clickhouse-server/config.d/z_log_disable.xml
<?xml version="1.0"?>
<clickhouse>
    <asynchronous_metric_log remove="1"/>
    <metric_log remove="1"/>
    <query_thread_log remove="1" />  
    <query_log remove="1" />
    <query_views_log remove="1" />
    <part_log remove="1"/>
    <session_log remove="1"/>
    <text_log remove="1" />
    <trace_log remove="1"/>
    <crash_log remove="1"/>
    <opentelemetry_span_log remove="1"/>
    <zookeeper_log remove="1"/>
</clickhouse>
```

**Comment by den-crane** [comment]
>We have multiple low-end severs 1 vCPU and 1-2 GB RAM for testing purposes
>Please don't tell me it's a normal thing :).

By default Clickhouse is tuned for beefy machines not  low-end severs.

**Comment by doom369** [comment]
Thanks. I'll try your advices. For now I fully isolated the VM, we'll see in a few hours if it helps.

> By default Clickhouse is tuned for beefy machines not low-end severs.

Sure, but why would I need beefy machines for 0 load? Would you personally use 32 vCPU + 128 GB for 0 load? I doubt that.

**Comment by den-crane** [comment]
>Sure, but why would I need beefy machines for 0 load? Would you personally use 32 vCPU + 128 GB for 0 load? I doubt that.

I use 96CPU / 128 GB as test machines. I don't care that they use 1% cpu for internal telemetry.

**Comment by den-crane** [comment]
I also have my own opinion about internal telemetry; I advise those who do not use it to turn it off.

**Comment by doom369** [comment]
> I don't care that they use 1% cpu for internal telemetry.

I don't think that's an internal telemetry issue, telemtry usually is a pain when you have a high load, it seems like a bug. You can check the 22.2.2.1 vs 23.1.3.5 there was some degradation.

**Comment by doom369** [comment]
Ok. So I fully turned off external connections (with binding to localhost), the situation improved a bit, but still CPU is wasted:

![screenshot-cloud digitalocean com-2024 02 20-09_16_09](https://github.com/ClickHouse/ClickHouse/assets/1536494/1b151185-78d8-46d7-aeb0-7424ca871f4d)

Now, I'll check @den-crane proposals.

**Comment by doom369** [comment]
Seems like @den-crane recommendations work (I used both at a time):

![screenshot-cloud digitalocean com-2024 02 20-10_15_43](https://github.com/ClickHouse/ClickHouse/assets/1536494/fa8e74de-dabc-4de0-8761-87c993b46ac0)

Still not sure if that's normal that some metrics consume so much CPU, still looks like a bug to me, however, it's up to maintainers to decide if it's worth fixing. Closing.

**Comment by joebnb** [comment]
also want to decrease cpu consumption

**Comment by den-crane** [comment]
With modern CH processors_profile_log contributes a lot as well

```
    <processors_profile_log remove="1"/>
```

I update the list here https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/

**Comment by EricDuminil** [comment]
Even after disabling every log with

```
<clickhouse>
    <asynchronous_metric_log remove="1"/>
    <backup_log remove="1"/>
    <error_log remove="1"/>
    <metric_log remove="1"/>
    <query_metric_log remove="1"/>
    <query_thread_log remove="1" />  
    <query_log remove="1" />
    <query_views_log remove="1" />
    <part_log remove="1"/>
    <session_log remove="1"/>
    <text_log remove="1" />
    <trace_log remove="1"/>
    <crash_log remove="1"/>
    <opentelemetry_span_log remove="1"/>
    <zookeeper_log remove="1"/>
    <processors_profile_log remove="1"/>
    <latency_log remove="1"/>
</clickhouse>
```

Clickhouse kept on using 10% CPU all day long on my relatively powerful server, even before any analytics was added.

Is there really no way for Clickhouse to be completely idle when there's apparently nothing to do?

**Comment by den-crane** [comment]
@EricDuminil 

There are more system tables in new versions.

```
    <background_schedule_pool_log remove="1"/>
    <aggregated_zookeeper_log remove="1"/>
    <zookeeper_connection_log remove="1"/>
```

I did:
```
cat /etc/clickhouse-server/config.d/z_log_disable.xml
<clickhouse>
    <asynchronous_metric_log remove="1"/>
    <backup_log remove="1"/>
    <error_log remove="1"/>
    <metric_log remove="1"/>
    <query_metric_log remove="1"/>
    <query_thread_log remove="1" />
    <query_log remove="1" />
    <query_views_log remove="1" />
    <part_log remove="1"/>
    <session_log remove="1"/>
    <text_log remove="1" />
    <trace_log remove="1"/>
    <crash_log remove="1"/>
    <opentelemetry_span_log remove="1"/>
    <zookeeper_log remove="1"/>
    <processors_profile_log remove="1"/>
    <latency_log remove="1"/>
    <background_schedule_pool_log remove="1"/>
    <aggregated_zookeeper_log remove="1"/>
    <zookeeper_connection_log remove="1"/>
</clickhouse>
```

```
 systemctl restart clickhouse-server;
drop table system.query_log;
drop table system.part_log;
...
```

Checked that there is no more mergeTree tables:
```
SELECT
    database,
    `table`,
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.parts
WHERE (active = 1) AND (database LIKE '%') AND (`table` LIKE '%')
GROUP BY
    database,
    `table`
ORDER BY size DESC

0 rows in set. Elapsed: 0.004 sec.
```

Checked that there is zero activity in clickhouse-server.log with trace log level.
```
tail -f -n 0 /var/log/clickhouse-server/clickhouse-server.log
```

Clickhouse server uses ~0.5% CPU (4 arm cpu system)

**Comment by doom369** [comment]
@EricDuminil what top command show with "threads" view?

**Comment by EricDuminil** [comment]
@doom369 :

With normal "top", I only see `clickhouse-server --config-file=/etc/clickhouse-server/config.xml` at about 8%.

With `docker exec plausible-events-db top -H -b -n 1`, I see more than 650 threads: https://pastebin.com/73qidu4E , which I find suspiciously high.

**Comment by ironbelly** [comment]
Coming to express graititude for this.. 40-70% cpu usage down to 1.3 - 1.7% after implementing the configs above.  thank you

**Comment by bendtherules** [comment]
Went down from ~15% to 3%. Huge thanks.
