### ISSUE TITLE
CLICKHOUSE_DB env variable is not respected after upgrade from 23.8 to 24.1 docker image

### ISSUE THREAD

**Issue by ribtoks** [ClickHouse/ClickHouse#60020]
**Describe the unexpected behaviour**
Default database is not created anymore when using 24.1 docker image and setting environment variable `CLICKHOUSE_DB`.

**How to reproduce**

Run clickhouse-server using this command:

```
docker run -d --rm \
    -p 8123:8123 \
    -p 9000:9000 \
    --ulimit nofile=262144:262144 \
    -e CLICKHOUSE_DB=mytestdb \
    clickhouse/clickhouse-server:23.8-alpine
```

After upgrading to 24.1, database `mytestdb` is not created anymore.

> NOTE: alpine image was selected just for size, same behavior is when using just `:23.8` image (without `-alpine`)

**Expected behavior**

24.1 is backwards-compatible with `CLICKHOUSE_DB` behavior.

**Comment by darwin67** [comment]
FYI
24.1.3 works, and it started breaking from 24.1.4. You can still upgrade to 24.1.x if you lock it to 24.1.3

related: https://github.com/ClickHouse/ClickHouse/issues/60025

**Comment by Algunenano** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/59991
