### ISSUE TITLE
how to avoid  duplicate data when using distributed engine

### ISSUE THREAD

**Issue by lordk911** [ClickHouse/ClickHouse#6002]
when I insert into a local table with PRIMARY KEY defined , I will only succeed to insert  one row in it , but if I insert into a distributed table I will got duplicate data , how to avoid  it?

**Comment by nvartolomei** [comment]
Not sure I understood your question.

By local you mean Replicated*MergeTree table? If yes: https://clickhouse.yandex/docs/en/operations/table_engines/distributed/ see `internal_replication` setting, it should be true.

**Comment by den-crane** [comment]
Check sharding key at distributed table. With rand() every time a row goes to a random shard. You need to set some expression like cityHash64(user_id),
