### ISSUE TITLE
Broken cluster queries with functions

### ISSUE THREAD

**Issue by jrdi** [ClickHouse/ClickHouse#60039]
2 replicas running master (24.2.1.1) with allow_experimental_analyzer = true

Trying to get errors from each replica with the following query:

```sql
SELECT
      shardNum() as server_shard,
      version() as version,
      name
  FROM clusterAllReplicas('tinybird', system.errors)
  ORDER BY server_shard, name
```

When there are no errors in both instances:

```
Ok.

0 rows in set. Elapsed: 0.004 sec.
```

When there are errors in the replica you are connected to:

```
┌─server_shard─┬─version──┬─name────────────────────────┐
│            1 │ 24.2.1.1 │ ALL_CONNECTION_TRIES_FAILED │
│            1 │ 24.2.1.1 │ NO_REMOTE_SHARD_AVAILABLE   │
└──────────────┴──────────┴─────────────────────────────┘
```

When there are errors in the other replica:

```
Received exception from server (version 24.2.1):
Code: 10. DB::Exception: Received from localhost:29000. DB::Exception: Not found column version() in block. There are only columns: shardNum(), __table1.name, '24.2.1.1'_String: While executing Remote. (NOT_FOUND_COLUMN_IN_BLOCK)
```

I have been checking different ways to make the query work, just in case it helps:

- Removing the `ORDER BY` the query WORKS:

```sql
SELECT
      shardNum() as server_shard,
      version() as version,
      name
  FROM clusterAllReplicas('tinybird', system.errors)
  --ORDER BY name
```

- Removing the `version()` function WORKS:

```sql
SELECT
      shardNum() as server_shard,
      --version() as version,
      name
  FROM clusterAllReplicas('tinybird', system.errors)
  ORDER BY name
``` 

- Removing the `shardNum()` function FAILS:

```sql
SELECT
      --shardNum() as server_shard,
      version() as version,
      name
  FROM clusterAllReplicas('tinybird', system.errors)
  ORDER BY name

Received exception from server (version 24.2.1):
Code: 10. DB::Exception: Received from localhost:29000. DB::Exception: Not found column version() in block. There are only columns: __table1.name, '24.2.1.1'_String: While executing Remote. (NOT_FOUND_COLUMN_IN_BLOCK)
``` 

By those tests, it looks like the `version()` function somehow resolves earlier in the path, and the `ORDER BY` forces to process the data in the initiator, making the query to fail.

**Comment by novikd** [comment]
Thank you for a good description! I noticed a similar problem with other functions. The problem is that constant-folding takes place on shards and it changes the header. I'm trying to address it in #59813.

**Comment by jrdi** [comment]
This is working fine in master already.

**Comment by novikd** [comment]
@jrdi @Algunenano I was keeping this issue opened because I want to add a test.

**Comment by alexey-milovidov** [comment]
@novikd, reopen if you still want to add a test.
