### ISSUE TITLE
`intDiv` of large UInt64 values and floats produces wrong results 

### ISSUE THREAD

**Issue by knl** [ClickHouse/ClickHouse#60056]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

I'm trying to convert StratusVOS jiffies (there are 65536 jiffies in a second) to nanoseconds and vice-versa. In python, I can do the following:

```py
JIFFIES_IN_ONE_SECOND = 65536
1391332687909454210//(1e9/JIFFIES_IN_ONE_SECOND)
```
and will get the correct result `91182379034833`. However, this query in clickhouse produces the wrong result:

```sql
SELECT
    ts,
    toUInt64(intDiv(ts, 1000000000. / 65536)) AS j,
    toUInt64(j * (1000000000. / 65536)) AS rb,
    ts - rb AS diff
FROM values('ts UInt64', 1391332687909301889, 1391332687909454210, 1391332687909591535)
```

```
Query id: 060f81cc-ffc8-4df5-a2a3-c03f92a22221

┌──────────────────ts─┬──────────────j─┬──────────────────rb─┬──diff─┐
│ 1391332687909301889 │ 91182379034824 │ 1391332687909301760 │   129 │
│ 1391332687909454210 │ 91182379034834 │ 1391332687909454336 │  -126 │
│ 1391332687909591535 │ 91182379034842 │ 1391332687909576448 │ 15087 │
└─────────────────────┴────────────────┴─────────────────────┴───────┘

3 rows in set. Elapsed: 0.001 sec.
```

As you can see, the jiffy in the second row is `91182379034834`, not `91182379034833`. `diff` column shows that the nanosecond value of that jiffy is higher than the starting jiffy, meaning that `intDiv` did not return the integral part of the division, but rounded the result.

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

Ran on:

```
ClickHouse client version 24.1.5.6 (official build).
```

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

```[tasklist]
### Tasks
```

**Comment by rschu1ze** [comment]
@yariks5s FYI (since you were recently working on `intDiv`)

**Comment by KochetovNicolai** [comment]
We can use UInt128 for more precise calculation
```
SELECT
    ts,
    intDiv(bitShiftLeft(toUInt128(ts), 16), 1000000000) AS j,
    bitShiftRight(j * 1000000000, 16) AS rb,
    ts - rb AS diff
FROM values('ts UInt64', 1391332687909301889, 1391332687909454210, 1391332687909591535)

Query id: f9dc8f9f-e93a-4187-b32c-c14e4eaa7f30

┌──────────────────ts─┬──────────────j─┬──────────────────rb─┬──diff─┐
│ 1391332687909301889 │ 91182379034824 │ 1391332687909301757 │   132 │
│ 1391332687909454210 │ 91182379034833 │ 1391332687909439086 │ 15124 │
│ 1391332687909591535 │ 91182379034842 │ 1391332687909576416 │ 15119 │
└─────────────────────┴────────────────┴─────────────────────┴───────┘
```

Not sure which result is expected, but now the second row is 91182379034833
