### ISSUE TITLE
Skip useless columns in primary key in memory.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#60091]
**Use case**

If the primary key is (prefix..., suffix...), but the value of the prefix is unique, do not keep the suffix columns in memory.

**Comment by JackyWoo** [comment]
hi @alexey-milovidov, I have a question that how can we identify a column is unique for ClickHouse does not hava unique constraint right now.

**Comment by alexey-milovidov** [comment]
I've implemented this in https://github.com/ClickHouse/ClickHouse/issues/11191
The implementation does not check if the column has all unique values, instead, it checks the threshold on the number of sequential changes of the prefix columns. If it changes frequently - we don't store the suffix in memory. This is done on a per-part level.
