### ISSUE TITLE
The performance of order by in query statements is poor.

### ISSUE THREAD

**Issue by cnzxc** [ClickHouse/ClickHouse#60104]
I have a clickhouse cluster with two shards and two replicas. In the table building statement, the **ORDER BY** keyword is `(happen_time, event_id)`, When I query a distributed table, if I include `order by happen_time` in the query statement, the query speed will become very slow. However, if I remove `order by happen_time`, it will be very fast

**Comment by cnzxc** [comment]
My sql statement is: 
`select event_id
from dwd_detail_vsoc_model_event
where happen_time between '2024-02-17 00:00:00' and '2024-02-18 23:59:59'
and event_type in ('xxx') and asset_name in ('xxx')
order by happen_time desc
limit 0,10;`

**Comment by alexey-milovidov** [comment]
No info was provided.
