### ISSUE TITLE
The performance of order by in query statements is poor.

### ISSUE THREAD

**Issue by cnzxc** [ClickHouse/ClickHouse#60116]
My local table is :
`CREATE TABLE default.dwd_detail_vsoc_model_event_sig on cluster cluster_2shards_2replicas
(
	`event_id` Nullable(String),
	`event_type` Nullable(String),
	`asset_name` Nullable(String),
        `happen_time` DateTime
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/dwd_detail_vsoc_model_event_sig',
 '{replica}')
PARTITION BY toDate(happen_time)
ORDER BY (happen_time,
 event_id)
SETTINGS index_granularity = 8129;`

and my distributed table is : 
`CREATE TABLE default.dwd_detail_vsoc_model_event on cluster cluster_2shards_2replicas
as dwd_detail_vsoc_model_event_sig 
ENGINE = Distributed('cluster_2shards_2replicas',
 'default',
 'dwd_detail_vsoc_model_event_sig',
 rand());`

At present, the data volume is approximately 2 billion, and the following SQL queries will be very slow : 
`select event_id
from dwd_detail_vsoc_model_event
where happen_time between '2024-02-18 00:00:00' and '2024-02-19 23:59:59'
and event_type in ('xxx') and asset_name in ('xxx')
order by happen_time desc
limit 0,10`

But when I remove the where condition or remove the happen_time sorting, the query will be very fast, but it cannot be removed in my actual business. How can I optimize it?

**Comment by nickitat** [comment]
since we already have table sorted by `happen_time` sorting should by reduced to merging sorted streams. also since you have `limit`, initiator will merge only ~number_of_shards*10 rows.
maybe local merging is slow because of `PARTITION BY toDate(happen_time)`. pls provide `explain pipeline` for your query.

**Comment by Algunenano** [comment]
No info was provided. Feel free to reopen if there is anything to investigate
