### ISSUE TITLE
Duplicate rows when using buffer tables and replication

### ISSUE THREAD

**Issue by gaelmuller** [ClickHouse/ClickHouse#60137]
**Describe the unexpected behaviour**

In an AggregatingMergeTree table (doing a sum on `count`), I am inserting a single row with a specific count.

After a few seconds, this count appears doubled inside the table.

I think this is related to the use of buffer tables and replication, but I don't understand why this is happening.

**Note**: This is only occurring when a continuous load of other inserts are happening at the same time.

**How to reproduce**

The full reproduction setup can be found here: https://github.com/gaelmuller/clickhouse-duplication-issue

I am running a ClickHouse cluster with 2 shards and 2 replicas for each. `internal_replication` is set to `true`.

The table setup is: DISTRIBUTED TABLE -> BUFFER TABLE -> ReplicatedAggregatingMergeTree:

```
CREATE TABLE test.counts_local ON CLUSTER test_cluster
    (
        `uuid` UUID,
        `count` SimpleAggregateFunction(sum, UInt64),
        `created_at` DateTime
    )
    ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/test/counts_local', '{replica}')
    ORDER BY (
        uuid,
        created_at
    )

CREATE TABLE test.counts_buffer ON CLUSTER test_cluster (
        `uuid` UUID,
        `count` SimpleAggregateFunction(sum, UInt64),
        `created_at` DateTime
    )
    ENGINE = Buffer('test', 'counts_local', 1, 1, 1, 0, 500000, 0, 100000000)

CREATE TABLE test.counts ON CLUSTER test_cluster (
        `uuid` UUID,
        `count` SimpleAggregateFunction(sum, UInt64),
        `created_at` DateTime
    )
    ENGINE = Distributed('test_cluster', 'test', 'counts_buffer', rand())
```

**Expected behavior**

The count should not be duplicated.

**Additional context**

When removing the buffer table, this works as expected.

I have seen the following quote [in the documentation](https://clickhouse.com/docs/en/engines/table-engines/special/buffer):

> If the destination table is replicated, some expected characteristics of replicated tables are lost when writing to a Buffer table. The random changes to the order of rows and sizes of data parts cause data deduplication to quit working, which means it is not possible to have a reliable ‘exactly once’ write to replicated tables.

My client is not performing any retry though, so I thought this was fine. Is this the expected behavior ? Would I have the same issue with `async_insert` ?

**Comment by den-crane** [comment]
You defined internal_replication at the incorrect `<replica>` level. It should be at the shard.

your config
```
    <remote_servers>
        <test_cluster>
            <shard>
                <replica>
                    <user>interserver</user>
                    <internal_replication>true</internal_replication>
```

```
    <remote_servers>
        <test_cluster>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
```

**Comment by gaelmuller** [comment]
Wow :man_facepalming: You are right, this now makes sense and I am able to fix the issue. Thank you :pray: 

Do you know if there is any query to see the actual active value of `internal_replication` to check if it is correctly taken into account ?

**Comment by den-crane** [comment]
v23.10.1.1976-stable.md:* Add internal_replication to system.clusters. [#55377](https://github.com/ClickHouse/ClickHouse/pull/55377) ([Konstantin Morozov](https://github.com/k-morozov)).
