### ISSUE TITLE
clickhouse-client broken when using with readonly user and queries file

### ISSUE THREAD

**Issue by kamilHipsz** [ClickHouse/ClickHouse#60133]
After upgrade of clickhouse-server and clickhouse-client to newest version (24.1.5.6), I encountered a BC break:

**Received exception from server (version 24.1.5):
Code: 164. DB::Exception: Received from xxx:9000. DB::Exception: Cannot modify 'log_comment' setting in readonly mode. (READONLY)**

It's impossible to use readonly user with queries file in clichouse-client:

`clickhouse-client -h host -u readonly_user --password pass --database database --queries-file /tmp/some_file_with_query.txt`

Probably introduced in https://github.com/ClickHouse/ClickHouse/pull/57191.

**Comment by kamilHipsz** [comment]
Issue still reproducible with latest clickhouse-client 24.8.1.2684.

**Comment by kamilHipsz** [comment]
Workaround by adding `--log_comment ''` parameter.

**Comment by azat** [comment]
Yes, you found correct culprit, thank you for the report.

Should be fixed by https://github.com/ClickHouse/ClickHouse/pull/69175 - for now it simply reverts it, but maybe later it will be introduced without breaking readonly users
