### ISSUE TITLE
Extract UUIDv1 timestamp from uuid column

### ISSUE THREAD

**Issue by kokizzu** [ClickHouse/ClickHouse#60148]
**Use case**

after importing data from Cassandra, it have uuid-v1 column that i need to have the timestamp value

**Describe the solution you'd like**

```
SELECT datetimeOfUuidV1(ts_uuid) FROM ...
```

**Describe alternatives you've considered**

I have no idea to extract this information for quick workaround

**Additional context**

https://stackoverflow.com/questions/73248705/how-to-get-information-about-exact-value-did-generateuuidv4-from-clickhouse-en

**Comment by den-crane** [comment]
UUIDv4 does not have timestamp value, it has only random numbers

https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by den-crane** [comment]
May be you mean V1 ? https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/uuid_type_r.html

**Comment by kokizzu** [comment]
temporary solution :3
https://kokizzu.blogspot.com/2024/02/writing-udf-for-clickhouse-using-golang.html

**Comment by den-crane** [comment]
clickhouse has bitand and bitshift so you can do it with pure SQL

**Comment by alexey-milovidov** [comment]
I think SQL UDF (CREATE FUNCTION) is a good workaround (and a reason to not implement this feature).
