### ISSUE TITLE
Redis dictionary reload problem with CANNOT_PARSE_ESCAPE_SEQUENCE error

### ISSUE THREAD

**Issue by mkocztorz** [ClickHouse/ClickHouse#60147]
We have REDIS dictionary with 9 million records. While reloading it or trying any query, I get:
```Code: 25. DB::Exception: Cannot parse escape sequence: While executing Redis. (CANNOT_PARSE_ESCAPE_SEQUENCE) (version 22.8.11.15 (official build))```

How can we get more logs about that?

**Comment by CamiloSierraH** [comment]
Hi @mkocztorz , I do not have enough information to try to reproduce, but have you seen the PR that was merged, fixing a similar issue in the latest versions? https://github.com/ClickHouse/ClickHouse/pull/61883 

Another option is to check in the text_log system table for the exception and then use the time and hostname to filter and review what happened before this exception was triggered.
```
SELECT
    hostname(),
    event_time,
    message
FROM clusterAllReplicas(xxxx, system.text_log)
WHERE (message ILIKE '%CANNOT_PARSE_ESCAPE_SEQUENCE%')
```
