### ISSUE TITLE
Implement PostgreSQL `get_byte` function

### ISSUE THREAD

**Issue by kokizzu** [ClickHouse/ClickHouse#60152]
**Use case**

trying to make UDF of UUIDv1 parser, there's some [solution](https://stackoverflow.com/questions/24178485/cast-or-extract-timestamp-from-v1-uuid-in-postgresql) that uses postgre's [get_byte](https://www.postgresql.org/docs/9.0/functions-binarystring.html), and I believe it would be quite useful

**Describe the solution you'd like**

implement `get_byte(string, position)` just like Postgres'

**Describe alternatives you've considered**

writing the UDF in golang or something

**Comment by rschu1ze** [comment]
While at it, we should also implement `get_bit`, plus the respective `set_*` functions.

**Comment by rogeryk** [comment]
Hi, I want to try this task.

**Comment by rogeryk** [comment]
The calculation of index in Posgres is a bit strange
> get_bit and set_bit number bits from the right within each byte; for example bit 0 is the least significant bit of the first byte, and bit 15 is the most significant bit of the second byte.

In Clickhouse, the indexe of bitTest and bitSlice are calculated from the left. 
Should we all follow the clickhous approach?

**Comment by rschu1ze** [comment]
I was not aware of functions `bitTest` and `bitSlice`. Actually, passing `length = 8` to `bitSlice` will achieve the desired result. We can ignore for this issue that `bitTest` exists. `bitSlice` counts starting from the most significant bit, i.e. left-to-right.


What we should do is add `byteSlice` as a convenience function: it will be similar to `bitSlice` but return N bytes, counting from the M-th most significant bit left-to-right. That way, we'll stay consistent with the existing functions in ClickHouse.

**Comment by rogeryk** [comment]
@kokizzu `bitSlice` should have met your requirements, I did a test below.
```sql
select '448f2c3c-d602-11ee-a506-0242ac120002' as uuid,
       UUIDStringToNum(uuid, 1)               as bytes,
       reinterpretAsInt64(reverse(bitSlice(bytes, 1, 32))) +
       reinterpretAsInt64(reverse(bitSlice(bytes, 33, 16))) * pow(2, 32) +
       bitAnd(reinterpretAsInt64(reverse(bitSlice(bytes, 49, 16))), 0xfff) * pow(2, 48) as ut,
       toDateTime((ut - 122192928000000000)/10000000)
```
```txt
448f2c3c-d602-11ee-a506-0242ac120002,"D�,<��B�",139283943723576384,2024-02-28 06:26:12

```

**Comment by rogeryk** [comment]
@rschu1ze `byteSlice`  doesn’t seem to be needed either. Clickhouse already have `substring`. Or just add an alias
