### ISSUE TITLE
Column names with Spaces and keywords causing filters to not work in cloud console

### ISSUE THREAD

**Issue by Abhishek-KB01** [ClickHouse/ClickHouse#60187]
I have uploaded a json file with a column "Product Group". it got uploaded successfully. When trying to use the filter on the Web Console for this column it creates the query without double quotes around the column name causing the query to crash.
Additionally when I renamed the columns the same changes are not reflected in the filter, so after renaming all the columns I essentially cannot use filters in the UI.

**Comment by CamiloSierraH** [comment]
Hello @Abhishek-KB01 , I work as a support engineer at ClickHouse. I conducted a search but couldn't find your email to find the related service in our system. Could you please open a support case using the following link: https://clickhouse.cloud/support

Thank you, and please keep us posted on any updates.

**Comment by Abhishek-KB01** [comment]
Thanks, I have created a support case for it.
