### ISSUE TITLE
(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 198. DB::Exception: Not found address of host

### ISSUE THREAD

**Issue by guoxiaolongzte** [ClickHouse/ClickHouse#60193]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

I have a question. The host name is AAA. I started a clickhouse service and changed the host name to BBB midway. However, the service did not restart. I found that the copy of zk's table,/test/1/replicas/1s-2p/host, is still AAA. Have you encountered this before? What is the solution?

Error message when starting service：
 (591a2e6a-70a7-4fd6-aa51-ab3b322b9ea1): auto DB::StorageReplicatedMergeTree::processQueueEntry(ReplicatedMergeTreeQ
ueue::SelectedEntryPtr)::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Code: 198. DB::Exception: Not found address of host: AAA. (DN
S_ERROR), Stack trace (when copying this message, always include the lines below):

Avoidance methods:
<interserver_http_host>BBB</interserver_http_host>

The current version: 22.8 LTS

**Comment by avinzhang** [comment]
Changing the hostname of a ClickHouse server can sometimes lead to issues, especially if the new hostname is not properly configured or recognized by the system. The error "DB::Exception: Not found address of host" typically indicates that ClickHouse is unable to resolve the new hostname to an IP address.

Update the ClickHouse server configuration to recognize the new hostname. This involves updating the config.xml file and possibly the users.xml file.

```
<!-- Update remote servers configuration if necessary -->
<remote_servers>
    <your_cluster_name>
        <shard>
            <replica>
                <host>new-hostname</host>
                <port>9000</port>
            </replica>
        </shard>
    </your_cluster_name>
</remote_servers>
```
