### ISSUE TITLE
24.1.4+ CLICKHOUSE_DB environment var not working creating database

### ISSUE THREAD

**Issue by kclonts** [ClickHouse/ClickHouse#60200]
**Describe what's wrong**

Creating a new container with the official dockerhub container, setting the environment variable CLICKHOUSE_DB=mydb, then connecting with the js client; mydb does not exist

**Does it reproduce on the most recent release?**

Started happening on 24.1.4 and also happens on 24.1.5

**Enable crash reporting**

No _crash_ to report

**How to reproduce**

* Which ClickHouse server version to use
docker tag 24.1.4

* Which interface to use, if it matters
docker run -e 'CLICKHOUSE_DB=mydb' clickhous
e/clickhouse-server:24.1.4

**Expected behavior**

connecting with js client, the database is already created and a connecting using that database succeeds

**Error message and/or stacktrace**

24.1.4 stdout when entering container
`ClickHouse Database directory appears to contain a database; Skipping initialization`

No log files created

**Additional context**

**Comment by astudnev** [comment]
Same issue exists in 24 release with scripts in docker /docker-entrypoint-initdb.d

ClickHouse Database directory appears to contain a database; Skipping initialization

 ClickHouse server version 24.1.5.

**Comment by astudnev** [comment]
It looks as incorrect fix of this problem: https://github.com/ClickHouse/ClickHouse/pull/59991

**Comment by AlexNik** [comment]
@astudnev No, this fix was correct.
`-n` is right.

**Comment by AlexNik** [comment]
@kclonts There is the bug in 24.1.4.
The head is correct.

Try
`docker run -it --rm -e 'CLICKHOUSE_DB=mydb' -p 8123:8123 clickhouse/clickhouse-server:head`

@alexey-milovidov The bug was in my PR #59808
This PR fixed it #59991

@kclonts Need to wait for the next release with the fix...

**Comment by Algunenano** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/59991
