### ISSUE TITLE
Actual query time is more than query execution time in query log

### ISSUE THREAD

**Issue by chiragb1994** [ClickHouse/ClickHouse#60207]
Hi, I have a cluster with distributed tables. I have a query taking join on 20 tables, using inner queries:

```
with (SELECT a1, b1, c1
      FROM table1
          PREWHERE a1 = 'xyz'
      ORDER BY b1 DESC, c1 desc
      LIMIT 1) as book, (SELECT a2, b2, c2
                         FROM table2
                             PREWHERE a2 = 'xyz'
                         ORDER BY b1 DESC, c1 desc
                         LIMIT 1) as pay
SELECT * FROM (
         SELECT tupleElement(book, 1) as booking_id,
                tupleElement(book, 2) as hotel_id,
                tupleElement(pay, 1)  as product_transaction_id
         ) as bookTable
         LEFT JOIN (
    SELECT a3, b3, c3, d3
    from table3 FINAL
        PREWHERE created_date >= subtractHours(tupleElement(pay, 3), 6)
        and created_date <= addHours(tupleElement(pay, 3), 6)
    WHERE product_transaction_id = tupleElement(pay, 1)
      and transaction_detail__start_time >= subtractHours(tupleElement(pay, 3), 6)
    ) as payment_request
                   ON payment_request.product_transaction_id = bookTable.product_transaction_id
   LEFT JOIN ... (total 18 joins)
```

The queries I see on shards:
| type | event_time_microseconds | query_start_time_microseconds | query_duration_ms | read_rows | read_bytes | result_rows | result_bytes | memory_usage | Settings | query |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_result_rows': '1', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|SELECT a1, b1, c1 FROM table1 PREWHERE a1 = 'xyz' ORDER BY b1 DESC, c1 desc LIMIT 1 |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_result_rows': '1', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book` SELECT a2, b2, c2 FROM table2 PREWHERE a2 = 'xyz' ORDER BY b1 DESC, c1 desc LIMIT 1 |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:04.123792|2024-02-20 09:56:02.891731|3|0|0|0|0|28560|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_result_rows': '1', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|SELECT a1, b1, c1 FROM table1 PREWHERE a1 = 'xyz' ORDER BY b1 DESC, c1 desc LIMIT 1 |
| QueryFinish|2024-02-20 09:56:04.133194|2024-02-20 09:56:02.891731|3|0|0|0|0|30224|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_result_rows': '1', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book` SELECT a2, b2, c2 FROM table2 PREWHERE a2 = 'xyz' ORDER BY b1 DESC, c1 desc LIMIT 1 |
| QueryFinish|2024-02-20 09:56:05.589696|2024-02-20 09:56:02.891731|8|808|808|0|0|1135470|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.599842|2024-02-20 09:56:02.891731|6|3323|3323|0|0|1061476|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.615776|2024-02-20 09:56:02.891731|8|3144|3144|0|0|1346456|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.623224|2024-02-20 09:56:02.891731|1|0|0|0|0|5648|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.626805|2024-02-20 09:56:02.891731|1|0|0|0|0|5648|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.630028|2024-02-20 09:56:02.891731|1|0|0|0|0|25576|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.633622|2024-02-20 09:56:02.891731|1|0|0|0|0|5840|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.636689|2024-02-20 09:56:02.891731|1|0|0|0|0|5840|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.640613|2024-02-20 09:56:02.891731|2|0|0|0|0|5968|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.652293|2024-02-20 09:56:02.891731|9|73921|147408|0|0|3129438|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.661915|2024-02-20 09:56:02.891731|1|0|0|0|0|5648|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.685191|2024-02-20 09:56:02.891731|1|0|0|0|0|5712|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.691808|2024-02-20 09:56:02.891731|4|124195|496780|0|0|1359922|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.698594|2024-02-20 09:56:02.891731|2|1882|7528|0|0|116722|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.703929|2024-02-20 09:56:02.891731|2|17359|69436|0|0|287234|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.707443|2024-02-20 09:56:02.891731|1|0|0|0|0|5648|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.710800|2024-02-20 09:56:02.891731|1|0|0|0|0|5648|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |
| QueryFinish|2024-02-20 09:56:05.746576|2024-02-20 09:56:02.891731|34|24482|1737661|0|0|49768624|{'receive_timeout': '600', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'}|WITH __getScalar('7408414651523862215_1189082663845015781') AS `book`, __getScalar('17353423637597688303_6582210121859106692') AS `pay` SELECT ... |

Even though individual query time is around 4ms with one query taking around 35ms, the overall query time comes to around 3 seconds:

| type | event_time_microseconds | query_start_time_microseconds | query_duration_ms | read_rows | read_bytes | result_rows | result_bytes | memory_usage | Settings |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| QueryStart|2024-02-20 09:56:02.891731|2024-02-20 09:56:02.891731|0|0|0|0|0|0|{'receive_timeout': '600', 'use_uncompressed_cache': '0', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'} |
| QueryFinish|2024-02-20 09:56:05.766360|2024-02-20 09:56:02.891731|2874|1411787|12901986|1|25084|70289405|{'receive_timeout': '600', 'use_uncompressed_cache': '0', 'load_balancing': 'first_or_random', 'max_execution_time': '1800', 'max_memory_usage': '20000000000', 'prefer_localhost_replica': '0', 'max_partitions_per_insert_block': '0'} |

Cluster details:

5 shard nodes and a separate node having distributed tables for read queries. Version: `23.8.9.54` on all nodes

**Comment by alexey-milovidov** [comment]
It is normal if a distributed query takes more time than the maximum of queries on each shard - it can spend time for some work on the initiator node that cannot be spread out.

You can check query metrics in the ProfileEvents column in the query log.
Also, you can use distributed tracing: https://clickhouse.com/docs/en/operations/opentelemetry
Also, you can use the real-time sampling query profiler: https://clickhouse.com/docs/en/operations/optimizing-performance/sampling-query-profiler

**Comment by chiragb1994** [comment]
I checked ProfileEvents but I couldn't figure out where is this time going. I'll try sampling query profiler as suggested. 

```{'Query': '1', 'SelectQuery': '1', 'QueriesWithSubqueries': '283', 'SelectQueriesWithSubqueries': '283', 'ReadCompressedBytes': '20798', 'CompressedReadBufferBlocks': '206', 'CompressedReadBufferBytes': '24818', 'IOBufferAllocs': '204', 'IOBufferAllocBytes': '109093369', 'ArenaAllocChunks': '326', 'ArenaAllocBytes': '1335296', 'FunctionExecute': '2459', 'NetworkReceiveElapsedMicroseconds': '75608', 'NetworkSendElapsedMicroseconds': '3892', 'NetworkReceiveBytes': '259846', 'NetworkSendBytes': '193932', 'DistributedConnectionTries': '100', 'DistributedConnectionUsable': '100', 'SuspendSendingQueryToShard': '100', 'SelectedRows': '1411787', 'SelectedBytes': '12901986', 'ContextLock': '26070', 'ContextLockWaitMicroseconds': '13339', 'RWLockAcquiredReadLocks': '1681', 'RealTimeMicroseconds': '4099811', 'UserTimeMicroseconds': '2700447', 'SystemTimeMicroseconds': '103827', 'SoftPageFaults': '23301', 'OSCPUWaitMicroseconds': '21157', 'OSCPUVirtualTimeMicroseconds': '2804221', 'OSWriteChars': '15360', 'QueryProfilerRuns': '8', 'ScalarSubqueriesGlobalCacheHit': '65', 'ScalarSubqueriesCacheMiss': '1344'}```
