### ISSUE TITLE
Behaviour of lightweight delete and partitioned tables

### ISSUE THREAD

**Issue by MSchutt** [ClickHouse/ClickHouse#60218]
When you want to delete data from a specific partition in a ClickHouse table, you can use the ALTER TABLE ... DELETE syntax, specifying the partition with the command: `ALTER TABLE testtable DELETE IN PARTITION 'xy' WHERE <condition>`. This method allows for targeted deletion within a specified partition, as detailed in the ClickHouse documentation (https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#delete-in-partition).

However, when it comes to the newer feature of "lightweight deletes" in ClickHouse, which is designed to be more efficient by marking rows for deletion without immediately removing them (the actual deletion occurs during the next merge operation), there seems to be a limitation. Specifically, the lightweight delete syntax does not appear to support partition targeting directly. A syntax like `DELETE IN PARTITION 'xy' FROM testtable WHERE <condition>` is invalid, and the official documentation (https://clickhouse.com/docs/en/guides/developer/lightweight-delete) does not mention any method for applying lightweight deletes to specific partitions.

This raises a few questions:

1. How do lightweight deletes work internally, especially in relation to partitions? If you were to use the partition key in the WHERE clause of a lightweight delete command, does ClickHouse optimize the operation to only affect the specified partition, or does it scan and potentially mark rows for deletion across the entire table?
2. Why does the IN PARTITION clause exist? Specifically, is using the partition clause more efficient for operations that are intended to affect only a single partition, and if so, why is this option not available for lightweight deletes?
3. Efficiency considerations for targeting a single partition: If specifying a partition for deletion operations is indeed more efficient, what are the implications for lightweight deletes? Can similar efficiency be achieved by filtering on the partition key, or does this approach not offer the same level of optimization?

Thanks!

**Comment by den-crane** [comment]
Important: There is data and there is metadata. 

1

`lightweight deletes` are lightweight in terms of DATA. They don't remove DATA, don't process DATA, they just update a small column `_row_exists` (DATA) in RELATED parts (accordingly) to `where` section. So DATA is processed in the limited number of parts.
But `lightweight delete` processes all METADATA, it recreates all parts (METADATA).

2 

`IN PARTITION` it's a silly attempt of 3d-party developer to overcome MergeTree design limitations and process less METADATA. It should not exists. It was never implemented for `lightweight delete`.

3

Optimization of processing less METADATA was never a goal for neither for `lightweight deletes` nor `alter update/delete`

**Comment by UnamedRus** [comment]
You can make kind of LWD with IN PARTITION clause, for now it's working

https://github.com/ClickHouse/ClickHouse/issues/59409#issuecomment-1918855066
https://github.com/ClickHouse/ClickHouse/issues/59225#issuecomment-1911782012

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/67805
