### ISSUE TITLE
Flaky test `test_replicated_table_attach/test.py::test_startup_with_small_bg_pool_partitioned`

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#60217]
Recent [fails](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA4LTI3JyBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X3N0YXJ0dXBfd2l0aF9zbWFsbF9iZ19wb29sX3BhcnRpdGlvbmVkJScgYW5kIHN0YXR1cyA9PSAnRkFJTCcKb3JkZXIgYnkgY2hlY2tfc3RhcnRfdGltZSBkZXNj)

Sample [report](https://s3.amazonaws.com/clickhouse-test-reports/0/392081256c7d3d34ca824189370293e4610ee1ef/integration_tests__asan__analyzer_.html)

**Comment by alexey-milovidov** [comment]
https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMyBNT05USAogICAgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgKHRlc3Rfc3RhdHVzIExJS0UgJ0YlJyBPUiB0ZXN0X3N0YXR1cyBMSUtFICdFJScpIAogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBwb3NpdGlvbih0ZXN0X25hbWUsICd0ZXN0X3JlcGxpY2F0ZWRfdGFibGVfYXR0YWNoJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=

**Comment by antonio2368** [comment]
I'll add it to `parallel_skip.json` same as other tests using iptables rules.
There is something else strange where table was readonly even after connections were restored so I'll check that first.
