### ISSUE TITLE
Incorrect results when query uses 2 hasToken() conditions in WHERE clause depending on the order 

### ISSUE THREAD

**Issue by TroyCoombs** [ClickHouse/ClickHouse#60223]
I’m encountering the following issue which appears to be a bug.

Discovered when running version 24, including 24.1.5.6.  It is not an issue on version 23.8.8

I have these 2 queries (which are based on test cases we have),

> SELECT payload_id
> FROM searchable_payloads
> WHERE hasToken(headers['user-agent'], 'bulk') AND hasToken(headers['user-agent'], 'tests') AND (team_id = 'tm_XyNGEKw')

and

> SELECT payload_id
> FROM searchable_payloads
> WHERE hasToken(headers['user-agent'], 'tests') AND hasToken(headers['user-agent'], 'bulk') AND (team_id = 'tm_XyNGEKw')

The first query returns 1 row, the 2nd query returns 2 rows.  2 rows is correct.  The only difference in the queries is the order of the hasToken() conditions.

Here are the 2 rows that are expected to be selected.

> Row 1:
> ──────
> team_id:    tm_XyNGEKw
> payload_id: zffHFgplZ3xNYCK8p1Sl
> req_evt_id: jirytqTeZhdzSyYOrKWq
> ttl:        2024-03-21 16:38:53.380
> terms:      bulk.test.ts text/plain bulk-tests ?test2=true /test2
> headers:    {'content-type':'text/plain','user-agent':'bulk-tests'}
> body:       {'body':'bulk.test.ts'}
> query:      {'test2':'true'}
> path:       /test2
> created_at: 2024-02-20 16:38:53.378000
> 
> Row 2:
> ──────
> team_id:    tm_XyNGEKw
> payload_id: VGpWcLMq8FXkJLdIjIid
> req_evt_id: FVbNjkI63IusONCIn1ee
> ttl:        2024-03-21 16:38:53.338
> terms:      bulk.test.ts application/json bulk-tests ?test=true /test
> headers:    {'content-type':'application/json','user-agent':'bulk-tests'}
> body:       {'source':'bulk.test.ts'}
> query:      {'test':'true'}
> path:       /test
> created_at: 2024-02-20 16:38:53.332000

zffHFgplZ3xNYCK8p1Sl is the id that is returned in both queries.

Here's the CREATE TABLE statement,
```
CREATE TABLE searchable_payloads
(
    `team_id` String,
    `payload_id` String,
    `req_evt_id` String,
    `ttl` DateTime64(3),
    `terms` String,
    `headers` Map(String, String),
    `body` Map(String, String),
    `query` Map(String, String),
    `path` String,
    `created_at` Nullable(DateTime64(6)),
    INDEX sp_path_bloom path TYPE ngrambf_v1(1, 64, 2, 0) GRANULARITY 1,
    INDEX sp_headers_keys_bloom mapKeys(headers) TYPE tokenbf_v1(15000, 5, 3) GRANULARITY 2,
    INDEX sp_headers_values_bloom mapValues(headers) TYPE tokenbf_v1(37000, 5, 3) GRANULARITY 2,
    INDEX sp_query_keys_bloom mapKeys(query) TYPE tokenbf_v1(7000, 5, 3) GRANULARITY 2,
    INDEX sp_query_values_bloom mapValues(query) TYPE tokenbf_v1(15000, 5, 3) GRANULARITY 2,
    INDEX sp_terms_bloom_n terms TYPE tokenbf_v1(135000, 5, 0) GRANULARITY 2,
    INDEX sp_bloom_body_values mapValues(body) TYPE tokenbf_v1(37000, 5, 3) GRANULARITY 2,
    INDEX sp_bloom_body_keys mapKeys(body) TYPE tokenbf_v1(15000, 5, 3) GRANULARITY 2
)
ENGINE = MergeTree
ORDER BY (team_id, ttl, req_evt_id)
TTL toDateTime(ttl)
SETTINGS index_granularity = 4096 
```

```[tasklist]
### Tasks
```

**Comment by den-crane** [comment]
hm.

24.1.2 random result https://fiddle.clickhouse.com/356ca171-67d0-4ef5-9207-606c8e19d4d2
24.1.5 correct result https://fiddle.clickhouse.com/9fa653a0-acbf-4607-af66-5465a4b657db

**Comment by Algunenano** [comment]
Probably https://github.com/ClickHouse/ClickHouse/pull/59594

**Comment by den-crane** [comment]
@TroyCoombs  double check 24.1.5.6, provide evidences if possible.
