### ISSUE TITLE
AggregatingMergeTree - Partition field is aggregatable

### ISSUE THREAD

**Issue by Hulumulula** [ClickHouse/ClickHouse#60237]
Hello everyone!
I have a table of this form:

```sql
CREATE TABLE dw_ttest
(
    name String,
    partition_id SimpleAggregateFunction(max, UInt32),
    balance SimpleAggregateFunction(sum, UInt64)
)
    ENGINE = AggregatingMergeTree
    PARTITION BY partition_id
    ORDER BY name
```

I need to aggregate by a partition field. 
That is, to aggregate across all rows of the table, not just within a partition.
I need the partition itself for convenient search among the data, because there is a lot of data (over a billion rows).
How can I save partitions and still aggregate data by this field?

I can query the table using 
`GROUP BY field WITH TOTALS`.
but the table itself is not updated

**Comment by den-crane** [comment]
you cannot. That is not possible by design. Just don't use partitioning. Clickhouse can work without partitions (with a single partition).

**Comment by Hulumulula** [comment]
> вы не можете. Это невозможно по замыслу. Просто не используйте разделение. Clickhouse может работать без разделов (с одним разделом).

Как мне тогда ускорить поиск по данным без партиций?
Skip индекс мне не подходит, потому что сортировка выполненна по имени, а имена все уникальные (после агрегации)

**Comment by den-crane** [comment]
В лоб никак не ускорить.

* Перекладывать готовый результат в другую таблицу отсортированную по partition_id по крону
* Завалить железом
* Взять другую базу данных

**Comment by Hulumulula** [comment]
Очень жаль(
Попробую как-нибудь ещё пошаманить, спасибо за помощь!
