### ISSUE TITLE
Usability improvement for Pretty format: print human readable number in the case of a single value

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#60296]
```
clickhouse-cloud :) SELECT count() FROM merge(default, '^trace_log_')

SELECT count()
FROM merge(default, '^trace_log_')

Query id: 5bc2e90c-2c69-4152-bfdc-fc3c39b0ab30

┌──────count()─┐
│ 233765663884 │
└──────────────┘
```

If a block consists of a single numeric value, and it exceeds one million, we should print:

```
┌──────count()─┐
│ 233765663884 │ -- 233.77 billion
└──────────────┘
```

This addition should be displayed in gray color, if the output is a terminal.

**Comment by Alexfilus** [comment]
How to get such formated string as a result of a query? There is some function?

**Comment by den-crane** [comment]
@Alexfilus https://clickhouse.com/docs/en/sql-reference/functions/other-functions#formatreadablequantityx
