### ISSUE TITLE
Legacy version picked by tgz installation script

### ISSUE THREAD

**Issue by demurgos** [ClickHouse/ClickHouse#60318]
There is an issue with the [Install | From Tgz Archives](https://clickhouse.com/docs/en/install#from-tgz-archives) section.

The install script currently starts with the following bash code to find the latest version:

```bash
LATEST_VERSION=$(curl -s https://packages.clickhouse.com/tgz/stable/ | \
    grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | sort -V -r | head -n 1)
export LATEST_VERSION
```

The problem is that it assumes that package list fits in a single page, this is not true as the package list is paginated. Today, this script selects the version `23.12.4.15`. This is wrong: the latest stable version is actually `24.1.5.6`. The documentation script should be updated to handle pagination, or the registration should offer a single-page index of available versions.

**Comment by Algunenano** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/61151
