### ISSUE TITLE
allow custom headers to be passed in s3 functions

### ISSUE THREAD

**Issue by gingerwizard** [ClickHouse/ClickHouse#60311]
**Use case**

I want to be able to send `request-payer:requester` header so i can query s3 buckets where the charges have to paid for by the requester.

**Describe the solution you'd like**

Ability to specify this as a param in s3 function.

**Comment by gingerwizard** [comment]
Need via function

**Comment by Avogar** [comment]
Table function URL supports headers in function: https://clickhouse.com/docs/en/sql-reference/table-functions/url
As I can see from the code, S3 function also should support it, you can try.

**Comment by gingerwizard** [comment]
Supproted in s3 as well e.g.

`FROM s3Cluster('default', 'https://coiled-datasets-rp.s3.us-east-1.amazonaws.com/1trc/measurements-10*.parquet', 'KEY', 'SECRET', headers('x-amz-request-payer' = 'requester'))`
