### ISSUE TITLE
Bad query performance while working with Distributed engine table

### ISSUE THREAD

**Issue by bentzimor** [ClickHouse/ClickHouse#6034]
**Describe the bug**
We have a cluster with 16 shards, no replicas.
Total table rows = 450M rows, each shard contains ~ 28M rows
total columns = 530

Running aggregation, no joins
on each shard the execution is 600ms while querying the distributed table we get 7 seconds,

* Which ClickHouse server version to use
version 19.8.3 revision 54420

**Expected behavior**
Expect to get execution time of ~ 1 second

![image](https://user-images.githubusercontent.com/3490724/61372326-80761700-a89f-11e9-9e71-62fea984523f.png)

**Additional context**
How do we get the slowest step in the execution plan?

**Comment by den-crane** [comment]
The reason is excessive final aggregation at an initiator.
distributed_group_by_no_merge =1 gives 900ms and correct result https://t.me/clickhouse_en/13176

**Comment by alexey-milovidov** [comment]
Need info on query and dataset.
(Dataset can be prepared with `clickhouse-obfuscator`)

What is the query result size?
How the execution time changes if you enable `distributed_aggregation_memory_efficient`?

**Comment by alexey-milovidov** [comment]
The `distributed_aggregation_memory_efficient` can speed up this class of queries.
