### ISSUE TITLE
toStartOfInterval returns wrong result when interval is in miliseconds

### ISSUE THREAD

**Issue by yujiarista** [ClickHouse/ClickHouse#60366]
The following two queries return different values with Clickhouse server 24.1
`select toStartOfInterval(toDateTime64('2015-01-01 00:01:34', 9), interval 100000 MILLISECONDS)`
`select toStartOfInterval(toDateTime64('2015-01-01 00:01:34', 9), interval 100 second)`

https://fiddle.clickhouse.com/00959742-a277-4ff9-9c37-28315f3fbc53

The second version is correct.

This issue doesn't exist with 23.12 or prior version.

**Comment by wxybear** [comment]
https://clickhouse.com/docs/en/whats-new/changelog/2021#backward-incompatible-change-7

**Comment by alexey-milovidov** [comment]
@zvonand, PTAL.

**Comment by yujiarista** [comment]
Any findings on this issue?

**Comment by alexey-milovidov** [comment]
It is probably one of the inaccurate changes by @zvonand or @Enmk.

@zvonand, @Enmk, please at least explain this behavior and add tests.

**Comment by zvonand** [comment]
> It is probably one of the inaccurate changes by @zvonand or @Enmk.

Havent touched this for ages, at least since 23.12 
The issue only appeared in 24.1

**Comment by alexey-milovidov** [comment]
Check this: https://github.com/ClickHouse/ClickHouse/pull/58557

**Comment by zvonand** [comment]
> Check this: https://github.com/ClickHouse/ClickHouse/pull/58557

Looks like a related one, tnx

**Comment by alexey-milovidov** [comment]
@zvonand, could you please fix it and add a test?

**Comment by zvonand** [comment]
> @zvonand, could you please fix it and add a test?

I'll take a look on Monday

**Comment by zvonand** [comment]
Yes, it was broken by #58557. Looking into it now.
CC @yariks5s
