### ISSUE TITLE
null pointer

### ISSUE THREAD

**Issue by tori-sallery** [ClickHouse/ClickHouse#60395]
version: 22.8.20.11

2024.02.24 12:48:26.674826 [ 126420 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.02.24 12:48:26.674852 [ 126420 ] {} <Fatal> BaseDaemon: Stack trace: 0xfdcac62 0xfdca6fb 0x1809ad11 0x180a5c2e 0x180a4c67 0x180a5730 0x180a3c43 0xfdca46e 0xfdca2b0 0xfdc2548 0xfdc3d0a 0xfdc4cdc 0xfdc35af 0x14643783 0x13f82528 0x13f840fc 0x13f8472c 0xfe69b0e 0xfe6bd4e 0x7f6280fc2609 0x7f6280ee7133
2024.02.24 12:48:26.674932 [ 126420 ] {} <Fatal> BaseDaemon: 3. std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*>*>, bool> std::__1::__hash_table<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >::__emplace_unique_key_args<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&) in /usr/bin/clickhouse
2024.02.24 12:48:26.674985 [ 126420 ] {} <Fatal> BaseDaemon: 4. DB::callback(void*, int, int, hostent*) in /usr/bin/clickhouse
2024.02.24 12:48:26.675004 [ 126420 ] {} <Fatal> BaseDaemon: 5. addr_callback in /usr/bin/clickhouse
2024.02.24 12:48:26.675020 [ 126420 ] {} <Fatal> BaseDaemon: 6. qcallback in /usr/bin/clickhouse
2024.02.24 12:48:26.675032 [ 126420 ] {} <Fatal> BaseDaemon: 7. end_query in /usr/bin/clickhouse
2024.02.24 12:48:26.675047 [ 126420 ] {} <Fatal> BaseDaemon: 8. process_answer in /usr/bin/clickhouse
2024.02.24 12:48:26.675059 [ 126420 ] {} <Fatal> BaseDaemon: 9. processfds in /usr/bin/clickhouse
2024.02.24 12:48:26.675076 [ 126420 ] {} <Fatal> BaseDaemon: 10. DB::CaresPTRResolver::wait_and_process() in /usr/bin/clickhouse
2024.02.24 12:48:26.675093 [ 126420 ] {} <Fatal> BaseDaemon: 11. DB::CaresPTRResolver::resolve(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in /usr/bin/clickhouse
2024.02.24 12:48:26.675108 [ 126420 ] {} <Fatal> BaseDaemon: 12. DB::reverseResolveImpl(Poco::Net::IPAddress const&) in /usr/bin/clickhouse
2024.02.24 12:48:26.675122 [ 126420 ] {} <Fatal> BaseDaemon: 13. DB::DNSResolver::updateAddress(Poco::Net::IPAddress const&) in /usr/bin/clickhouse
2024.02.24 12:48:26.675170 [ 126420 ] {} <Fatal> BaseDaemon: 14. bool DB::DNSResolver::updateCacheImpl<bool (DB::DNSResolver::*)(Poco::Net::IPAddress const&), std::__1::unordered_map<Poco::Net::IPAddress, unsigned int, std::__1::hash<Poco::Net::IPAddress>, std::__1::equal_to<Poco::Net::IPAddress>, std::__1::allocator<std::__1::pair<Poco::Net::IPAddress const, unsigned int> > >&>(bool (DB::DNSResolver::*&&)(Poco::Net::IPAddress const&), std::__1::unordered_map<Poco::Net::IPAddress, unsigned int, std::__1::hash<Poco::Net::IPAddress>, std::__1::equal_to<Poco::Net::IPAddress>, std::__1::allocator<std::__1::pair<Poco::Net::IPAddress const, unsigned int> > >&, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in /usr/bin/clickhouse
2024.02.24 12:48:26.675196 [ 126420 ] {} <Fatal> BaseDaemon: 15. DB::DNSResolver::updateCache(unsigned int) in /usr/bin/clickhouse
2024.02.24 12:48:26.675214 [ 126420 ] {} <Fatal> BaseDaemon: 16. DB::DNSCacheUpdater::run() in /usr/bin/clickhouse
2024.02.24 12:48:26.675234 [ 126420 ] {} <Fatal> BaseDaemon: 17. DB::BackgroundSchedulePoolTaskInfo::execute() in /usr/bin/clickhouse
2024.02.24 12:48:26.675248 [ 126420 ] {} <Fatal> BaseDaemon: 18. DB::BackgroundSchedulePool::threadFunction() in /usr/bin/clickhouse
2024.02.24 12:48:26.675276 [ 126420 ] {} <Fatal> BaseDaemon: 19. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, unsigned long, char const*)::$_1&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) in /usr/bin/clickhouse
2024.02.24 12:48:26.675300 [ 126420 ] {} <Fatal> BaseDaemon: 20. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
2024.02.24 12:48:26.675321 [ 126420 ] {} <Fatal> BaseDaemon: 21. void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()> >(void*) in /usr/bin/clickhouse
2024.02.24 12:48:26.675337 [ 126420 ] {} <Fatal> BaseDaemon: 22. ? in ?
2024.02.24 12:48:26.675351 [ 126420 ] {} <Fatal> BaseDaemon: 23. __clone in ?
2024.02.24 12:48:26.801149 [ 126420 ] {} <Fatal> BaseDaemon: Integrity check of the executable skipped because the reference checksum could not be read. (calculated checksum: C61047FCD9867D8EC9343478C608A32C)

**Comment by UnamedRus** [comment]
It was backported to 22.8.21, upgrade to this version
 https://github.com/ClickHouse/ClickHouse/pull/52634
