### ISSUE TITLE
quantilesExact(percentile) defined in the WITH clause cannot be utilized in the subsequent query in version 23.10.2.13

### ISSUE THREAD

**Issue by ztyntix** [ClickHouse/ClickHouse#60403]
**Describe the unexpected behaviour**
The query functions correctly in version 23.1.2.9 but encounters issues in version 23.10.2.13.

```
WITH tmp AS (
  SELECT 1 AS col
  UNION ALL
  SELECT 2
),

(SELECT 1.0 / count(0) FROM tmp) AS percentile,
t1 AS (SELECT quantilesExact(percentile)(col) FROM tmp)
SELECT * FROM t1
```

**How to reproduce**
ClickHouse Version: 23.10.2.13

**Error message and/or stacktrace**
clickhouse error: Orig exception: Code: 134. DB::Exception: Parameters to aggregate functions must be literals. Got parameter 'identity(_CAST(0., 'Nullable(Float64)')) AS percentile'. (PARAMETERS_TO_AGGREGATE_FUNCTIONS_MUST_BE_LITERALS) (version 23.10.2.13 (official build))

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/59154
