### ISSUE TITLE
Question about determining is query deduplicated or not

### ISSUE THREAD

**Issue by romesful** [ClickHouse/ClickHouse#60423]
What are the ways to determine is query was deduplicated?
There is no info about this in `query_log` or `query_thread_log`

I know that in log files you can grep by `Block with ID A already exists locally as part B; ignoring it.` or by `Deduplication path already exists: deduplication_path=smth`

Is there any way to determine is query was deduplicated or not by response(cpp client)?

**Comment by Algunenano** [comment]
> Is there any way to determine is query was deduplicated or not by response(cpp client)?

By response, no. If using a native client you can request the logs to be sent `send_logs_level`, or you can check query_logs for the `DuplicatedInsertedBlocks` profile event.

**Comment by SaltTan** [comment]
> What are the ways to determine is query was deduplicated?
> There is no info about this in `query_log` or `query_thread_log`

You can find this info in `part_log`

**Comment by den-crane** [comment]
>Is there any way to determine is query was deduplicated or not by response(cpp client)?

An insert can be deduplicated partially (if it create several blocks), it's unclear how to report it properly in HTTP headers(?).
Like `X-ClickHouse-Summary: {"created_blocks":33, "deduplicated_blocks":3}`

**Comment by romesful** [comment]
> > Is there any way to determine is query was deduplicated or not by response(cpp client)?
> 
> An insert can be deduplicated partially (if it created several blocks), it's unclear how to report it properly in HTTP headers(?). Like `X-ClickHouse-Summary: {"created_blocks":33, "deduplicated_blocks":3}`

I'm using cpp client, inserting blocks in specified shard at specified host
