### ISSUE TITLE
Data inserted on wrong shard

### ISSUE THREAD

**Issue by cpg314** [ClickHouse/ClickHouse#60446]
**Describe the unexpected behaviour**

I have a 2-shard (1 replica each) cluster, with a distributed table fronting a `ReplacingMergeTree` on each shard. 

The `sharding_key` is a simple `id: UInt64` field. 

After inserting a large amount of data, I realized that **roughly 6% of rows ended up on the other shard than expected:**
```sql
SELECT
    shard,
    mod2,
    count(id)
FROM distributed
GROUP BY (_shard_num AS shard, id % 2 AS mod2)
```

```
┌─shard─┬─mod2─┬─count(id)─┐
│     2 │    0 │   3978965 │
│     1 │    0 │    250200 │ abnormal
│     2 │    1 │    250201 │ abnormal
│     1 │    1 │   3978965 │
└───────┴──────┴───────────┘
```

The same behaviour could be observed on another distributed table, also sharded by `id`
```
┌─shard─┬─mod2─┬─count(id)──────────┐
│     2 │    0 │           78600775 │
│     1 │    0 │            2049242 │
│     2 │    1 │            2022513 │
│     1 │    1 │           78730944 │
└───────┴──────┴────────────────────┘
```
On a third such table, the rows were distributed as expected
```
┌─shard─┬─mod2─┬─count(scenario_id)─┐
│     2 │    0 │           11644928 │
│     1 │    1 │           11642068 │
└───────┴──────┴────────────────────┘
```

**How to reproduce**
This uses Clickhouse 24.1.5.6 with default settings.

The cluster configuration on both shards is
```xml
        <cluster>
            <shard>
                <internal_replication>False</internal_replication>
                <replica>
                    <host>chi-main-cluster-0-0</host>
                    <port>9000</port>
                    <secure>0</secure>
                </replica>
            </shard>
            <shard>
                <internal_replication>False</internal_replication>
                <replica>
                    <host>chi-main-cluster-1-0</host>
                    <port>9000</port>
                    <secure>0</secure>
                </replica>
            </shard>
        </cluster>
```

The configuration did not change during the insert.

What did happen however are the segfaults described on #60219 on both of the shards, manifesting as an error during the insert.
The incorrectly sharded IDs are in two sequences, which would match with when a shard went down.

This should not cause the inserts to be redirected to the other shard as long as the cluster configuration is not changed, correct?

**Expected behavior**
The rows should be distributed according to the sharding key.

It is important to have consistent assignment with respect to the sharding key in particular for distributed JOINs (https://clickhouse.com/docs/en/sql-reference/statements/select/join#distributed-join).

**Comment by den-crane** [comment]
>chi

Altinity operator changes cluster configuration during some events. It removes servers from cluster, it's a problem for you because you don't have replicas. You need to upgrade operator, afaik this issue was solved for single replica shards.

**Comment by cpg314** [comment]
Thanks for your reply. This would make sense, especially because the incorrect ids are sequential (in 2 chunks, which would corresponds to 2 shard restarts).

I'm using cilckhouse operator 0.23.1 (0.23.2 was released two weeks ago; I don't see a change between 0.23.1 and 0.23.2 that would affect single replica shards).

I tried forcefully stopping one of the shards, but I don't see any changes happening in `/etc/clickhouse-server/config.d/chop-generated-remote_servers.xml` of the healthy shard, so I'm not entirely sure the hypothesis is correct. 
Is there another way the operator would be signalling that a shard is down to Clickhouse?

**Comment by den-crane** [comment]
you need to open an issue https://github.com/Altinity/clickhouse-operator it's not related to Clickhouse.

**Comment by alexey-milovidov** [comment]
We don't support "Altinity" operators, and they are not recommended for usage with ClickHouse.

**Comment by cpg314** [comment]
If that helps anyone who would find this issue:

The problem was indeed that the operator seemed to remove the shard from the `remote_servers` when the pod restarted (even though I was not able to observe the `xml` file changing, which is what originally led me to think this was Clickhouse-related).

As long as the cluster configuration does not change, a workaround is to manually set
```xml
<clickhouse>
  <remote_servers>
    <mycluster replace="1">
        [contents from chop-generated-remote_servers.xml]
    </mycluster>
  </remote_serves>
</clickhouse>
```
in `config.d/custom.xml`.

When a shard temporarily fails, requests will fail rather than inserts being directed to the remaining shards.

I'll report this on Altinity's repository.
