### ISSUE TITLE
.clang-tidy

### ISSUE THREAD

**Issue by kreuzerkrieg** [ClickHouse/ClickHouse#6044]
Having any `.clang-tidy` is better than having none.
https://gist.github.com/kreuzerkrieg/51b73216e18f13cb412eaab519233fa6
Please consider adding this, or any other .clang-tidy to the project. the one above is not too noisy

**Comment by alexey-milovidov** [comment]
Now it's enabled only for .cpp files.

If we write
```
HeaderFilterRegex: 'dbms|base'
```
more issues will be found.

**Comment by alexey-milovidov** [comment]
Enough for now.
