### ISSUE TITLE
Query Incorrectly Returns Zero Values for Some Data

### ISSUE THREAD

**Issue by tc252617228** [ClickHouse/ClickHouse#60440]
> Please make sure that the version you're using is still supported (you can find the list [here]

The version I'm using is 23.3.18.15

> You have to provide the following information whenever possible.

In ClickHouse, I created two tables as follows:
-- `default`.openplant definition

CREATE TABLE default.openplant
(
    `ID` Int32,
    `GN` String,
    `TM` DateTime,
    `DS` Int16,
    `AV` Float64
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(TM)
ORDER BY (GN, ID, TM)
SETTINGS index_granularity = 8192;

-- `default`.opReqPoint definition

CREATE TABLE default.opReqPoint
(
    `companyName` String,
    `plantName` String,
    `projectName` String,
    `electricalName` String,
    `windName` String,
    `pointClassifyName` String,
    `point` String
)
ENGINE = ReplacingMergeTree
ORDER BY point
SETTINGS index_granularity = 8192;

Then, I executed the following SQL query:

SELECT
    req.companyName AS companyName,
    req.plantName AS plantName,
    req.projectName AS projectName,
    req.electricalName AS electricalName,
    req.windName AS windName,
    toStartOfDay(min(op.TM)) AS CurrentDate,
    op.GN AS GN,
    max(op.TM) AS MaxTM,
    min(op.TM) AS MinTM,
    max(op.AV) AS MaxAV,
    min(op.AV) AS MinAV,
    max(op.AV) - min(op.AV) AS AV_Difference,
    now() AS Version
FROM default.openplant AS op
INNER JOIN default.opReqPoint AS req ON op.GN = req.point
WHERE op.GN IN (
    SELECT point
    FROM default.opReqPoint
    WHERE pointClassifyName = '总发电量'
) 
AND op.TM >= toStartOfDay(now()) - INTERVAL 1 DAY -- Starting from 00:00 yesterday
AND op.TM <= toStartOfDay(now()) -- Up to 00:00 today
GROUP BY
    companyName,
    plantName,
    projectName,
    electricalName,
    windName,
    GN

> A clear and concise description of what works not as it is supposed to.

After running this query, I found that some data had MaxAV values of 0. So, I went back to the openplant table to check the value for this historical moment and found that the value was indeed not 0 and had valid data. What could be causing this discrepancy?

![image](https://github.com/ClickHouse/ClickHouse/assets/49756213/b7e5ab0f-29cd-4257-ae85-09993f6ba7d5)
![image](https://github.com/ClickHouse/ClickHouse/assets/49756213/36d62527-23fb-4a57-930f-16cc58e1bc5f)

**Comment by Algunenano** [comment]
Please share a minimal reproducible example. This can't be investigated as is.

Also note that the row that has the minimum `min(op.TM) AS MinTM` is not necessarily the same that has the minimum `min(op.AV) AS MinAV,`.

**Comment by Algunenano** [comment]
No repro was provided
