### ISSUE TITLE
Backward incompatibility of neighbor and rowNumberInBlock functions

### ISSUE THREAD

**Issue by glushkovds** [ClickHouse/ClickHouse#60441]
**Describe the issue**
In ClickHouse version 22, in any queries on any of our data sets, the `rowNumberInBlock` function produce the correct linear sequence of numbers from 0 to N, and the `neighbor` correctly produces values from adjacent rows.
After upgrading ClickHouse to versions 23 and 24, the above functions began to produce incorrect values on the same data sets. Namely, the `rowNumberInBlock` produces 0 (sometimes, by accident, from request to request it produces 1, 2, maximum 3 and resets to zero).
I read the documentation https://clickhouse.com/docs/en/sql-reference/functions/other-functions#neighbor, I understand that these functions “see” data only in the current block.
But we have hundreds of dashboards in Grafana that use this functions, it is not possible to rewrite them into similar `lagInFrame` functions.
I can't find the setting responsible for this behavior.
Is there any possibility in version 24 to return the ClickHouse behavior as before?

**How to reproduce**
SQL query, for example:
```sql
SELECT app_version_first,
  rowNumberInBlock() as rn,
  COUNT(device_id) AS fo,
  neighbor(fo,-1) as fo1
FROM full_devices fd FINAL
WHERE created_at >= today() - 60
GROUP BY app_version_first
HAVING fo > 1000 AND app_version_first != ''
ORDER BY app_version_first DESC
```
Expected result (22 version):
| app\_version\_first | rn | fo | fo1 |
| :--- | :--- | :--- | :--- |
| 002001000 | 0 | 38093 | 0 |
| 002000001 | 1 | 136308 | 38093 |
| 001092004 | 2 | 1087 | 136308 |
| 001092000 | 3 | 182051 | 1087 |
| 001091002 | 4 | 6591 | 182051 |
| 001091000 | 5 | 135144 | 6591 |
| 001090005 | 6 | 86452 | 135144 |
| 001090003 | 7 | 130676 | 86452 |
| 001090001 | 8 | 1255 | 130676 |
| 001089001 | 9 | 15615 | 1255 |
| 001088000 | 10 | 2315 | 15615 |
| 001086069 | 11 | 1528 | 2315 |
| 001074004 | 12 | 1108 | 1528 |

Unexpected result (24 version):
| app\_version\_first | rn | fo | fo1 |
| :--- | :--- | :--- | :--- |
| 002001000 | 0 | 38081 | 0 |
| 002000001 | 0 | 136307 | 0 |
| 001092004 | 1 | 1087 | 136307 |
| 001092000 | 0 | 182050 | 0 |
| 001091002 | 0 | 6590 | 0 |
| 001091000 | 0 | 135144 | 0 |
| 001090005 | 0 | 86452 | 0 |
| 001090003 | 0 | 130676 | 0 |
| 001090001 | 1 | 1255 | 130676 |
| 001089001 | 2 | 15615 | 1255 |
| 001088000 | 0 | 2314 | 0 |
| 001086069 | 0 | 1528 | 0 |
| 001074004 | 0 | 1108 | 0 |

**Additional context**
Both installations are stock, settings is default.

**Comment by UnamedRus** [comment]
Can you check: `max_final_threads=1;`

**Comment by glushkovds** [comment]
@UnamedRus Thank you! 

It works, both, with `max_final_threads=1` or `settings with split_parts_ranges_into_intersecting_and_non_intersecting_final=0, split_intersecting_parts_ranges_into_layers_final=0`

But if I remove FINAL clause, the result fails again, with applied settings.

**Comment by UnamedRus** [comment]
>But if I remove FINAL clause, the result fails again, with applied settings.

It's expected.

There is no guarantee on ordering of data.
So, you can use neighbor/rowNumberInBlock only if you have ORDER BY in subquery. 

Anyway, it's better to start rewriting your system to use WINDOW functions as they provide stable result.

**Comment by glushkovds** [comment]
The same unexpected behavior, removed `FINAL`, `ORDER BY` in subquery and `SETTINGS max_final_threads=1`:
```sql
SELECT app_version_first,
  rowNumberInBlock() as rn,
  fo,
  neighbor(fo,-1) as fo1
FROM (
    SELECT app_version_first,
      COUNT(device_id) AS fo
    FROM full_devices fd
    WHERE created_at >= today() - 60
    GROUP BY app_version_first
    HAVING fo > 1000 AND app_version_first != ''
    ORDER BY app_version_first DESC
)
ORDER BY app_version_first DESC
SETTINGS max_final_threads=1
```
| app\_version\_first | rn | fo | fo1 |
| :--- | :--- | :--- | :--- |
| 002001000 | 0 | 39360 | 0 |
| 002000001 | 0 | 136514 | 0 |
| 001092004 | 1 | 1099 | 136514 |
| 001092000 | 0 | 182060 | 0 |
| 001091002 | 0 | 6622 | 0 |

**Comment by UnamedRus** [comment]
> https://github.com/ClickHouse/ClickHouse/blob/e13a90e641b8ab05e582ba9e3c2ce9d120a32ffe/docs/en/sql-reference/functions/other-functions.md?plain=1#L550

It just old documentation, which was here even before WINDOW functions

```
SELECT neighbor(number) OVER (ORDER BY number ASC)
FROM numbers(10)

Code: 63. DB::Exception: Unknown aggregate function neighbor. There is an ordinary function with the same name, but aggregate function is expected here. (UNKNOWN_AGGREGATE_FUNCTION)
```

**Comment by glushkovds** [comment]
@den-crane 
Function `rowNumberInAllBlocks` solves only one problem.
Main problem is `neighbor`. 
I'm looking for a way do not rewrite hundreds of queries, but to solve the problem easier and faster by changing the behavior of the CickHouse, changing some setting.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/49494#issuecomment-1535449871

**Comment by glushkovds** [comment]
@den-crane
I see, thank you!
Is there no solution without changing sql queries?

**Comment by den-crane** [comment]
No solution.

**Comment by Algunenano** [comment]
Closed by https://github.com/ClickHouse/ClickHouse/pull/63132
