### ISSUE TITLE
cpu usage less than 90% even with dozens of parallel queries

### ISSUE THREAD

**Issue by etah000** [ClickHouse/ClickHouse#6046]
I was doing a performance test.

When I use one thread for testing, the average query time is less then 2 seconds. When I tried 8 parallel queries,  the average query time is more than 3.5 seconds, but the cpu usage for each cluster node are all less then 85%.   I then tried 16 parallel queries, the cpu usage is the same. Are there any settings which can push cpu usage to more than 95%?

I also tried "use_uncompressed_cache" and adusted "uncompressed_cache_size from 8G to 30G, but the overall performance has no obvious change.

I am almost sure that the disk is not the bottleneck because I selected all related data into memory by issuing the queries  which cover all the data time range several times.

**Comment by filimonov** [comment]
That is very uncommon: usually CH is using whole cpu power even on single query :) 

Most probably you're testing something that can't be efficiently parallelized, or you reached some I/O limitation, or something similar. You can try to monitor system during queries using standard tools like `dstat`, or try some debugging tools to find the part of code there most of the time is wasted (like `perf top`). 

To repeat query lot of times (also in parallel) you can use `clickhouse-benchmark` tool (distributed together with client).

**Comment by etah000** [comment]
It is actually queries related. When tried some other queries,  the cpu usage for some nodes reached more then 95%. Any tips for locating the bottleneck for a query?

why  the adjustment  of "uncompressed_cache_size"  has no effect for the query performance?

**Comment by blinkov** [comment]
@etah000, do you have any further questions?
