### ISSUE TITLE
How much performance will decrease when fsync_after_insert writing is turned on?

### ISSUE THREAD

**Issue by zbtzbtzbt** [ClickHouse/ClickHouse#60473]
Hi！@alexey-milovidov
We are heavy users of Clickhouse and use it to store and analyze some business data.

But we found a problem, when the machine is restarted, the linux server may have a page cache that has not time to flush cached data to the disk, **may resulting in empty parts and data loss**.

We plan to turn on the **fsync_after_insert** setting to solve this problem, force flush data into the disk.

Do you have any test data to show how much impact it has on writing performance after turning on fsync? 

Thanks！

**Comment by Algunenano** [comment]
> Do you have any test data to show how much impact it has on writing performance after turning on fsync?

It's impossible to determine and it will depend on exactly the read pattern that you have. The best (and probably only good way) of knowing is to turn it on in a server and measure

**Comment by alexey-milovidov** [comment]
It is likely to have zero performance drop if you use locally attached SSDs.

**Comment by amosbird** [comment]
Disk: INTEL SSDPE2KX040T8 3.5T

Poor man's test:
```
create table test(num Int32) engine MergeTree order by () settings fsync_after_insert = 0;

insert into test select * from numbers(1000000000);

0 rows in set. Elapsed: 9.424 sec. Processed 1.00 billion rows, 8.00 GB (106.11 million rows/s., 848.89 MB/s.)

create table test(num Int32) engine MergeTree order by () settings fsync_after_insert = 1;

insert into test select * from numbers(1000000000);

0 rows in set. Elapsed: 13.259 sec. Processed 1.00 billion rows, 8.00 GB (75.42 million rows/s., 603.37 MB/s.)
```

The throughput decreases by around 29% when fsync_after_insert = 1.
