### ISSUE TITLE
Feature: Logging format in JSON

### ISSUE THREAD

**Issue by bzon** [ClickHouse/ClickHouse#6049]
**Use case**

A structured log in JSON format can be automatically indexed by logging systems like Elasticsearch and Stackdriver.

**Describe the solution you'd like**
An option to configure the logger format in JSON.

**Comment by alexey-milovidov** [comment]
In recent ClickHouse version it's possible to configure.

You can enable `text_log` in configuration file and then create a MATERIALIZED VIEW on top of it with `File` engine:

```
CREATE MATERIALIZED VIEW system.text_log_json ENGINE = File(JSONEachRow) AS SELECT * FROM system.text_log
```

Data will be available at `data/system/%2Einner%2Etext_log_json/data.JSONEachRow`.

**Comment by nezed** [comment]
@alexey-milovidov I think its potentially dangerous way.
The main point of remote collected logs is to spot problems in real time with tools like alerts, while `CREATE MATERIALIZED VIEW ..` will not produce any logs in case if DBMS is failed to start or disk becomes read-only (eg. there is no space left).

**Comment by alexey-milovidov** [comment]
@nezed That's right and you have to resolve to ordinary logs in this case...

**Comment by DrissiReda** [comment]
@alexey-milovidov 

> In recent ClickHouse version it's possible to configure.
> 
> You can enable `text_log` in configuration file and then create a MATERIALIZED VIEW on top of it with `File` engine:
> 
> ```
> CREATE MATERIALIZED VIEW system.text_log_json ENGINE = File(JSONEachRow) AS SELECT * FROM system.text_log
> ```
> 
> Data will be available at `data/system/%2Einner%2Etext_log_json/data.JSONEachRow`.

I tried this and it works, but I'd like a simple way to obtain the file on disk, it's located on `data/store/f8f/..../data.JSONEachROW` any simple way of retrieving that path?
