### ISSUE TITLE
prql crash

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#60511]
Link: https://s3.amazonaws.com/clickhouse-test-reports/0/d93d5c2a0028944e8f17f8fa5257bb1e0de44e1f/ast_fuzzer__asan_.html

```
SET dialect = 'prql';
SELECT id FROM distributed_test_table GROUP BY x -> concat(concat(materialize(toNullable(NULL)))) LIMIT 3;
```

**Comment by Algunenano** [comment]
2 things here:
* prql is broken cc @antaljanosbenjamin 
* catching rust's panic does not work cc @azat

**Comment by Algunenano** [comment]
Tested prql 0.11.3 and it fails too.

**Comment by alexey-milovidov** [comment]
Let's remove PRQL.

**Comment by alexey-milovidov** [comment]
Although let's give it a change, e.g. one week.

**Comment by max-sixty** [comment]
> Let's remove PRQL.
> Although let's give it a change, e.g. one week.

Just saw this. We're obv big fans of ClickHouse and keen to stay in.

I'd previously asked how bad panics were and asked whether we should work harder to protect against them. Just got a response at https://github.com/PRQL/prql/issues/4280.

If we can fix this case quickly, does that give you some confidence PRQL will be well-behaved?

Then we're also happy to add fuzzing to track more cases down. While I expect it will take a bit of time before we can be really confident that we can't panic, I'd be happy to take this on.

**Comment by alexey-milovidov** [comment]
Yes, no worries. Actually, we already have confidence!

**Comment by max-sixty** [comment]
OK cheers!

(you may too much confidence in the panics atm! but I appreciate the confidence in the project. We'll endeavor to fix the panics...)

**Comment by max-sixty** [comment]
To update this thread — #4280 no longer panics, and I'm looking at the protection from panics in CH so that it's at least isolated (also on that issue atm)

**Comment by antaljanosbenjamin** [comment]
I think you meant https://github.com/PRQL/prql/issues/4280, right?

**Comment by max-sixty** [comment]
And I think https://github.com/ClickHouse/ClickHouse/pull/60615 fixes the panic handler; though would like to test it, and need to run CI

**Comment by Algunenano** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/60615
