### ISSUE TITLE
Flaky `test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree`

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#60539]
[cidb query](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIHRydWUgYXMgb25seV9tYXN0ZXIKU0VMRUNUICoKRlJPTSAoClNFTEVDVAogICAgcHVsbF9yZXF1ZXN0X251bWJlciBhcyBwcm51bSwKLS0gICAgY291bnQoKSBvdmVyIChQQVJUSVRJT04gQlkgKGNvbW1pdF9zaGEsIGNoZWNrX25hbWUsIGNoZWNrX3N0YXJ0X3RpbWUpKSBhcyBydW5fZmFpbHMsIAogICAgc3Vic3RyKGNvbW1pdF9zaGEsIDEsOSkgYXMgc2hhLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwopCldIRVJFIHRlc3RfbmFtZSBsaWtlICcldGVzdF9mYWlsZWRfbXV0YXRpb25zJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVNDLCBjaGVja19uYW1lLCB0ZXN0X25hbWUK)

<details>
<summary>cidb query result</summary>

| prnum | sha | check_start_time | ago | check_name | test_name | report_url |
|-:|:-|-:|:-|:-|:-|:-|
| 0 | 2e4de1f5e | 2024-02-28 17:19:17 | 16 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/2e4de1f5e83dbe3d937b2c018f1fc2220b4a6642/integration_tests__tsan__[2_6].html |
| 0 | f1b2dbaeb | 2024-02-28 13:25:00 | 20 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/f1b2dbaeb51cccc77899b2ab2efc266eb4886d97/integration_tests__tsan__[2_6].html |
| 0 | d15da9c74 | 2024-02-27 22:46:59 | 1 day and 10 hours | Integration tests (asan) [4/4] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/d15da9c7490c2a87790c43cc85a828c4ac76266d/integration_tests__asan__[4_4].html |
| 0 | 9ea7ff231 | 2024-02-27 22:36:36 | 1 day and 10 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/9ea7ff231bedb72423898bae12d4eedaa88e7ccb/integration_tests__tsan__[2_6].html |
| 0 | f8ff15a02 | 2024-02-27 18:57:17 | 1 day and 14 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/f8ff15a023fcfc8dc85b75658901c30a77a9d5a6/integration_tests__tsan__[2_6].html |
| 0 | 466cf93ee | 2024-02-27 16:59:06 | 1 day and 16 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/466cf93ee24884089f77461ad310f5f1964119ac/integration_tests__tsan__[2_6].html |
| 0 | 0f6bec784 | 2024-02-27 16:34:29 | 1 day and 16 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/0f6bec7842cd1f63c41fcbea7c66857646260b8c/integration_tests__tsan__[2_6].html |
| 0 | f69bfa452 | 2024-02-27 01:05:52 | 2 days and 8 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/f69bfa452633d2fcc2052a258f7202666053c787/integration_tests__tsan__[2_6].html |
| 0 | 9dff4e833 | 2024-02-26 23:22:31 | 2 days and 10 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/9dff4e833162c67772b523a5ca65463e9033c674/integration_tests__tsan__[2_6].html |
| 0 | 47734fbbe | 2024-02-26 23:08:39 | 2 days and 10 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/47734fbbe2d1ba62050e4b956bf5d379f7a1c6a0/integration_tests__tsan__[2_6].html |
| 0 | 710cdeb76 | 2024-02-26 22:09:45 | 2 days and 11 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/710cdeb76aace9eb5e15bee3185640cb398a541f/integration_tests__tsan__[2_6].html |
| 0 | ad99bb95a | 2024-02-26 21:10:36 | 2 days and 12 hours | Integration tests (asan, analyzer) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/ad99bb95a3b77707cfda92ffee4e53d8cf62bdf1/integration_tests__asan__analyzer__[2_6].html |
| 0 | b71ae80fa | 2024-02-26 19:18:15 | 2 days and 14 hours | Integration tests (asan, analyzer) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/b71ae80fa9c277be6ae13525caf42deb283a0e4f/integration_tests__asan__analyzer__[2_6].html |
| 0 | 814cd5391 | 2024-02-26 18:03:47 | 2 days and 15 hours | Integration tests (asan, analyzer) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/814cd53918af41053f0e0b19828c78325a4b3ca3/integration_tests__asan__analyzer__[2_6].html |
| 0 | 2b9889fb8 | 2024-02-26 17:33:57 | 2 days and 15 hours | Integration tests (asan) [4/4] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/2b9889fb84ad4029b2fabffdf8e9b50db6e85b1a/integration_tests__asan__[4_4].html |
| 0 | 2b9889fb8 | 2024-02-26 17:31:29 | 2 days and 15 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/2b9889fb84ad4029b2fabffdf8e9b50db6e85b1a/integration_tests__tsan__[2_6].html |
| 0 | 1a9ee8c31 | 2024-02-26 13:08:53 | 2 days and 20 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/1a9ee8c31886e5501b54fc853aaa6e065b221b6a/integration_tests__tsan__[2_6].html |
| 0 | ffe1872e2 | 2024-02-26 08:46:54 | 3 days | Integration tests (asan, analyzer) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/ffe1872e23723fc7221b9b1f89238aacdf016fb1/integration_tests__asan__analyzer__[2_6].html |
| 0 | 30d31d4d9 | 2024-02-24 23:14:29 | 4 days and 10 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/30d31d4d9bfd740f4a7935702f2761ad8134207b/integration_tests__tsan__[2_6].html |
| 0 | ef3b19167 | 2024-02-23 18:54:14 | 5 days and 14 hours | Integration tests (tsan) [2/6] | test_failed_mutations/test.py::test_exponential_backoff_with_merge_tree[node0-True] | https://s3.amazonaws.com/clickhouse-test-reports/0/ef3b19167fb94d4db107de066350479d47d68b29/integration_tests__tsan__[2_6].html |

</details>

**Comment by antaljanosbenjamin** [comment]
@alexey-milovidov made the test less flaky, but I think we can improve the test to catch obvious errors without backoff while not making the test flaky.
