### ISSUE TITLE
Batch insertion takes too long

### ISSUE THREAD

**Issue by wang-qijia** [ClickHouse/ClickHouse#60549]
The write operation is taking too long. Please help analyze where the bottleneck is. Below are the performance metrics retrieved from the query log.

`{ "ArenaAllocBytes": 126976, "ArenaAllocChunks": 31, "CompressedReadBufferBlocks": 2176, "CompressedReadBufferBytes": 17815761, "ContextLock": 60, "DiskWriteElapsedMicroseconds": 2681, "FileOpen": 64, "FunctionExecute": 94, "IOBufferAllocBytes": 63885215, "IOBufferAllocs": 225, "InsertQueriesWithSubqueries": 1, "InsertQuery": 1, "InsertedBytes": 24195115, "InsertedCompactParts": 2, "InsertedRows": 67051, "LogDebug": 4, "MergeTreeDataWriterBlocks": 2, "MergeTreeDataWriterCompressedBytes": 1253311, "MergeTreeDataWriterRows": 17051, "MergeTreeDataWriterUncompressedBytes": 6634678, "NetworkReceiveBytes": 7627819, "NetworkReceiveElapsedMicroseconds": 35833, "OSCPUVirtualTimeMicroseconds": 13031916, "OSCPUWaitMicroseconds": 635865, "OSIOWaitMicroseconds": 54, "OSWriteBytes": 5435392, "OSWriteChars": 5213184, "PartsLockHoldMicroseconds": 293, "QueriesWithSubqueries": 2, "Query": 1, "QueryProfilerRuns": 27, "RWLockAcquiredReadLocks": 8, "ReadCompressedBytes": 7639440, "RealTimeMicroseconds": 13807003, "SelectQueriesWithSubqueries": 1, "SelectedBytes": 30054964, "SelectedRows": 83376, "SoftPageFaults": 25196, "SystemTimeMicroseconds": 71505, "UserTimeMicroseconds": 12964321, "WriteBufferFromFileDescriptorWrite": 67, "WriteBufferFromFileDescriptorWriteBytes": 5195426, "ZooKeeperCreate": 1, "ZooKeeperMulti": 3, "ZooKeeperTransactions": 4 }`

**Comment by wang-qijia** [comment]
The problematic version 23.8.6.16 has been rolled back to 22.8.4.7, which resolved the issue of excessive write time.

**Comment by ygrzjh** [comment]
You can try setting the parameter `optimize_on_insert=0`
