### ISSUE TITLE
Insert into map does not respect key names and relies on positions

### ISSUE THREAD

**Issue by saitonakamura** [ClickHouse/ClickHouse#60571]
**Describe the unexpected behaviour**
Insert into map relies on positions instead of keys. If you mix keys ordering insert will result in values inserted into wrong keys. It may be by design but I could not find information about it in the docs

**How to reproduce**
* Which ClickHouse server version to use: 23.12.2.59
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE table_map (a Map(String, UInt64)) ENGINE=Memory;
INSERT INTO table_map VALUES ({'key2':1, 'key1':10}), ({'key1':2,'key2':20}), ({'key1':3,'key2':30});
```

* Queries to run that lead to unexpected result
```
SELECT * FROM table_map;
```

| key2 | key1 |
|--------|--------|
| 1 | 10 |
| 2 | 20 | 
| 3 | 30 |

**Expected behavior**
I would expect that keys will be respected and data will correspond to the insert query
| key2 | key1 |
|--------|--------|
| 1 | 10 |
| 20 | 2 | 
| 30 | 3 |

**Error message and/or stacktrace**
![image](https://github.com/ClickHouse/ClickHouse/assets/1552189/3bd66167-30b8-4ad1-9d6b-b7133230d428)

**Comment by den-crane** [comment]
It's a problem inside Dbeaver. It shows map datatype incorrectly.
It's not related to Clickhouse anyhow https://fiddle.clickhouse.com/7b1e36de-d170-4c68-a90c-a49303a84ff9

**Comment by saitonakamura** [comment]
Yeah, my bad, thanks for investigation

**Comment by saitonakamura** [comment]
Reported https://github.com/dbeaver/dbeaver/issues/23022, leaving here for posterity
