### ISSUE TITLE
WITH should work with UNION ALL

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6060]
This query is expected to work:
```
WITH 1 AS x SELECT x UNION ALL SELECT x
```

**Comment by amosbird** [comment]
I'll take this one after https://github.com/ClickHouse/ClickHouse/pull/14771

**Comment by alexey-milovidov** [comment]
@amosbird 

It works under `enable_global_with_statement`.
This task is considered "almost fixed".

The only thing left is maybe - to interpret WITH before first SELECT in UNION ALL chain as applied to all SELECTs in the chain.

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/15451
