### ISSUE TITLE
settings max_execution_time not working

### ISSUE THREAD

**Issue by akenO8** [ClickHouse/ClickHouse#60619]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

clickhouse version : 21.11.10.1

```
SELECT
    event_time,
    query_duration_ms,
    initial_user,
    query sql,
    if(exception_code = 0,'success',exception) exception,
    Settings
FROM clusterAllReplicas('ck', 'system.query_log')
WHERE event_time>='2024-02-29 14:39:00'
AND event_time<'2024-02-29 14:40:00'
AND query_duration_ms>600000
ORDER BY event_time DESC limit 10;\G
```
```
event_time:        2024-02-29 14:39:11
query_duration_ms: 822838
initial_user: trino
sql:               select name as TABLE_CAT from system.databases order by name settings max_execution_time=20
exception:         success
Settings:          {'max_threads':'6','use_hedged_requests':'0','queue_max_wait_ms':'120000','use_uncompressed_cache':'0','background_fetches_pool_size':'26','background_schedule_pool_size':'256','load_balancing':'random','log_queries':'1','max_concurrent_queries_for_user':'100','send_progress_in_http_headers':'1','join_use_nulls':'1','max_replica_delay_for_distributed_queries':'1','distributed_ddl_task_timeout':'360','max_execution_time':'20','timeout_before_checking_execution_speed':'60','max_memory_usage':'50000000000','max_memory_usage_for_user':'50000000000','enable_global_with_statement':'1','date_time_input_format':'best_effort','insert_distributed_one_random_shard':'1'}
```

1. Why does `settings max_execution_time=20` in sql not take effect?
2. `show create user trino` get `max_execution_time = 600`, This setting does not take effect either.

**Comment by Algunenano** [comment]
`21.11.10.1` is obsolete. Since then there have been many improvements to execution time limits. Please update
