### ISSUE TITLE
 High Clickhouse Server CPU Usage During Idle Periods

### ISSUE THREAD

**Issue by sunwoosf** [ClickHouse/ClickHouse#60618]
**Subject: High Clickhouse Server CPU Usage During Idle Periods**

**Observations:**
- Multiple "Clickhouse-serv" processes are consistently consuming over 40% of CPU time, even when there are no active Clickhouse activities or jobs running.
- This CPU usage pattern appears to be cyclical, as evidenced by the attached screenshot.
FYI, I also include Clickhouse server config.xml and users.xml.
![image(https://github.com/ClickHouse/ClickHouse/assets/9337035/02406fff-ea50-480f-98a5-190fe53feee7)

**Questions:**

**Q1: Reason for High CPU Usage?** 
Why does the Clickhouse server require such significant CPU resources during idle time? Is it performing any internal tasks, such as periodic or continuous indexing, that could explain this behavior?

**Q2: Optimization Strategies?** 
What can be done to optimize Clickhouse performance and minimize CPU usage by "Clickhouse-serv" processes during idle periods?

**System Info**
- OS :    Ubuntu 22.04.4 LTS
- CPU:   Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
- RAM:  131,560,740 kB
- ClickHouse server version:  24.1.5.6 (official build).

**Comment by sunwoosf** [comment]
Here is a screenshot.
![screen_shot](https://github.com/ClickHouse/ClickHouse/assets/9337035/e01feb81-8028-42db-986b-c08526aea346)

**Comment by Algunenano** [comment]
I would suggest checking the logs around those times. This by itself doesn't say anything, it could be anything from merges to asynchronous metrics collection.

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/issues/60016#issuecomment-1952936978
