### ISSUE TITLE
Query with FINAL doesn't return the last inserted row on duplicates

### ISSUE THREAD

**Issue by Uriyah3** [ClickHouse/ClickHouse#60620]
**Description**

After replacing the last value in a day with a different value, the last_value aggregation function will randomly return the second to last value instead, ignoring the replaced value at the end of the day. Using a daily window.
https://fiddle.clickhouse.com/298fe29c-156b-41ba-bee9-d391c03be67f
Tested on version 24.2.1.2248. On version 23.8 it always returns the correct value (1000 in the fiddle).

**Additional context**
- When running a ReplacingMergeTree without the is_deleted column it works correctly, i.e., always returns the value 1000 in the case of the fiddle. This applies to either using or not using an explicit version column.
- The problem happens even when no data is being marked as deleted with the is_deleted column.
- The fiddle should be run multiple times to see how it randomly returns either 1000 (correct value), 54.27 (second to last value) or 54.51 (third to last value).
- The SELECT queries are using FINAL.
- From my testing in the fiddle, the problem happens from version 24.1 onwards.

**Expected behavior**

It should always return the last value of each window.

**Comment by Uriyah3** [comment]
Then both the changelog and documentation are not clear. In the changelog of both versions 23.12 and 24.1 only say that the clean_deleted_rows setting was deprecated, not the whole is_deleted feature.

**Comment by Algunenano** [comment]
It seems it's unrelated

**Comment by Algunenano** [comment]
This reproduces without is_deleted too:

```
CREATE TABLE muestra (
    sensor_id UInt32,
    valor Float64,
    fecha DateTime,
    _version UInt8 DEFAULT 0
)
ENGINE = ReplacingMergeTree(_version)
PARTITION BY toYYYYMM(fecha)
ORDER BY (sensor_id, fecha);

insert into muestra (sensor_id, valor, fecha) values (3, 57.06, '2022-10-25 03:53:47');
insert into muestra (sensor_id, valor, fecha) values (3, 56.93, '2022-10-25 07:54:03');
insert into muestra (sensor_id, valor, fecha) values (3, 56.82, '2022-10-25 11:54:19');
insert into muestra (sensor_id, valor, fecha) values (3, 56.65, '2022-10-25 15:54:35');
insert into muestra (sensor_id, valor, fecha) values (3, 56.29, '2022-10-25 19:54:50');
insert into muestra (sensor_id, valor, fecha) values (3, 56.04, '2022-10-25 23:55:06');
insert into muestra (sensor_id, valor, fecha) values (3, 55.9, '2022-10-26 03:55:21');
insert into muestra (sensor_id, valor, fecha) values (3, 55.79, '2022-10-26 07:55:37');
insert into muestra (sensor_id, valor, fecha) values (3, 55.71, '2022-10-26 11:55:53');
insert into muestra (sensor_id, valor, fecha) values (3, 55.44, '2022-10-26 15:56:08');
insert into muestra (sensor_id, valor, fecha) values (3, 55.13, '2022-10-26 19:56:23');
insert into muestra (sensor_id, valor, fecha) values (3, 54.96, '2022-10-26 23:56:39');
insert into muestra (sensor_id, valor, fecha) values (3, 54.86, '2022-10-27 03:56:54');
insert into muestra (sensor_id, valor, fecha) values (3, 54.81, '2022-10-27 07:57:10');
insert into muestra (sensor_id, valor, fecha) values (3, 54.75, '2022-10-27 11:57:26');
insert into muestra (sensor_id, valor, fecha) values (3, 54.51, '2022-10-27 15:57:41');
insert into muestra (sensor_id, valor, fecha) values (3, 54.27, '2022-10-27 19:57:56');
insert into muestra (sensor_id, valor, fecha) values (3, 54.15, '2022-10-27 23:58:12');

SELECT 'Expected agreggated data';
SELECT 
  toStartOfDay(fecha) as day_aggr,
  last_value(valor),
  first_value(valor)
FROM muestra FINAL
WHERE sensor_id = 3 
GROUP BY day_aggr ORDER BY day_aggr asc;

insert into muestra (sensor_id, valor, fecha) values (3, 1000, '2022-10-27 23:58:12');

SELECT '';
SELECT 'Data after replacing the last value of the day 2022-10-27 with 1000';
SELECT 
  toStartOfDay(fecha) as day_aggr,
  last_value(valor),
  first_value(valor)
FROM muestra FINAL
WHERE sensor_id = 3 
GROUP BY day_aggr ORDER BY day_aggr asc;
```

Sometimes it returns the correct value and sometimes it doesn't. It's more flaky in slow builds (in debug I get way more failures locally).

Seems to work fine with `max_final_threads=0`. Maybe the behaviour to select last inserted row has changed with the recent changes to parallel final? cc @KochetovNicolai @kitaisreal

**Comment by SaltTan** [comment]
A shorter test https://fiddle.clickhouse.com/beef693b-af85-49e0-a3d4-e8d2959d6c7d
Related to https://github.com/ClickHouse/ClickHouse/pull/58506?

**Comment by canhld94** [comment]
Hi @Uriyah3 @Algunenano @SaltTan , I think this is not a bug. The query is "failing" because it uses `last_value` and `first_value` and relies on an assumption that queries with FINAL modifier return rows in `ORDER BY` key order. This assumption is not true anymore and was mentioned in 24.1 changelog:

> More efficient implementation of the `FINAL` modifier no longer guarantees preserving the order even if `max_threads = 1`. If you counted on the previous behavior, set `enable_vertical_final` to 0 or `compatibility` to `23.12`.

**Comment by Algunenano** [comment]
You are right @canhld94, the proper way to do it is to use argMax / argMin, not last_value / first_value which don't guarantee any order:

```sql
SELECT 
  toStartOfDay(fecha) as day_aggr,
  argMax(valor,fecha),
  argMin(valor, fecha)
FROM muestra FINAL
WHERE sensor_id = 3
GROUP BY day_aggr
ORDER BY day_aggr asc;
```

The other way would be to add `ORDER BY` after `FINAL` and hope that won't be optimized away in future CH versions:
```sql
SELECT 
  toStartOfDay(fecha) as day_aggr,
  last_value(valor),
  first_value(valor)
FROM
(SELECT * FROM muestra FINAL ORDER BY fecha)
WHERE sensor_id = 3 
GROUP BY day_aggr
ORDER BY day_aggr asc;
```
