### ISSUE TITLE
Typo in doc about system table query_log

### ISSUE THREAD

**Issue by mrxotey** [ClickHouse/ClickHouse#60626]
https://clickhouse.com/docs/en/operations/system-tables/query_log
Description of event_time/event_time_microseconds:
event_date ([Date](https://clickhouse.com/docs/en/sql-reference/data-types/date)) — Query starting date.
event_time ([DateTime](https://clickhouse.com/docs/en/sql-reference/data-types/datetime)) — Query starting time.
event_time_microseconds ([DateTime64](https://clickhouse.com/docs/en/sql-reference/data-types/datetime64)) — Query starting time with microseconds precision.

https://clickhouse.com/docs/en/operations/system-tables/query_thread_log
Descrpition of event_time/event_time_microseconds:
event_date — The date when the thread has finished execution of the query.
event_time — The date and time when the thread has finished execution of the query.
event_time_microsec**i**nds  — The date and time when the thread has finished execution of the query with microseconds precision.
(also typo in field name: event_time_microsec-i-nds)

```
$ grep 'elem.query_duration_ms =' Interpreters/executeQuery.cpp
                elem.query_duration_ms = 1000 * (elem.event_time - elem.query_start_time);
```

So it seems in https://clickhouse.com/docs/en/operations/system-tables/query_log there are typo issues in description of fields event_date/event_time/event_time_microseconds

**Comment by Algunenano** [comment]
It was fixed in https://github.com/ClickHouse/ClickHouse/pull/60551
