### ISSUE TITLE
How to drop database based on MySQL Engine

### ISSUE THREAD

**Issue by rangez** [ClickHouse/ClickHouse#6063]
This problem occurs when I delete the database based on the MySQL storage engine.

This is My Create database stament:
`SHOW CREATE DATABASE mydb;
CREATE DATABASE mydb ENGINE = MySQL('localhost:3306', 'docker', 'docker', 'docker')`

This is Exception when I try to drop database:
`Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: MySQL database engine does not support remove table..`

**Comment by alexey-milovidov** [comment]
CC @zhang2014

**Comment by zhang2014** [comment]
I'll try to fix it.

**Comment by rangez** [comment]
thank you very much @zhang2014

**Comment by tonal** [comment]
Also mysql db don`t drop if not connect to it:
```
host2 :) CREATE DATABASE mysql_db ENGINE = MySQL('yandex.ru:3306', 'test_db', 'yandex_admin', '1234');

CREATE DATABASE mysql_db
ENGINE = MySQL('yandex.ru:3306', 'test_db', 'yandex_admin', '1234')

Ok
0 rows in set. Elapsed: 0.064 sec. 

host2 :) show databases;

SHOW DATABASES

┌─name─────┐
│ default  │
│ mysql_db │
│ system   │
└──────────┘

4 rows in set. Elapsed: 0.001 sec. 

host2 :) drop database mysql_db;

DROP DATABASE mysql_db

Received exception from server (version 19.13.3):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: MySQL database engine does not support remove table.. 

0 rows in set. Elapsed: 0.313 sec. 
```

**Comment by zhang2014** [comment]
This is a feature that hasn't been implemented for some reason, and I will implement them as soon as possible.

**Comment by jigetage** [comment]
detach database test-db

**Comment by blinkov** [comment]
@rangez, do you have any further questions?

**Comment by robot-clickhouse** [comment]
@rangez, do you have any further questions?

**Comment by alexey-milovidov** [comment]
I have to mention that silly automatic comments from "robot-clickhouse" and from "blinkov" is just a personal idea of one of our friends and we strongly discourage this idea.

**Comment by zhang2014** [comment]
maybe we can close this issue ?

**Comment by gempir** [comment]
`DETACH DATABASE my_db` just loads forever for me, same with `DROP`

```
Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
```

The database in question was firewalled and I do not get a response, I think ClickHouse is trying to wait for a response from that server. 

Is there a way to remove the db without having to remove some magic files?
