### ISSUE TITLE
PostgreSQL table engine: Postgres 11 not supported as of 23.12 release

### ISSUE THREAD

**Issue by natalyjazzviolin** [ClickHouse/ClickHouse#60651]
**Describe the issue**
When using the PostgreSQL table engine with Postgres 11 on ClickHouse v23.12 or above, the database cannot be accessed.

**How to reproduce**
* Which ClickHouse server versions are incompatible: 23.12 and up
* Which interface to use, if matters: N/A
* Queries to run that lead to unexpected result: `SELECT * FROM postgresql(postgres_creds, table='table1');` using a PostgreSQL 11 database.

**Error message and/or stacktrace**
```
Code: 36. DB::Exception: Error: ERROR: column "attgenerated" does not exist LINE 1: ... atttypid as type_id, atttypmod as type_modifier, attgenerat... ^ (in query: SELECT attname AS name, format_type(atttypid, atttypmod) AS type, attnotnull AS not_null, attndims AS dims, atttypid as type_id, atttypmod as type_modifier, attgenerated as generated FROM pg_attribute WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'dim_companies' AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'analytics')) AND NOT attisdropped AND attnum > 0 ORDER BY attnum ASC). (BAD_ARGUMENTS) (version 24.0.2.54390 (official build))
```
**Additional context**
My hypothesis is that the issue is related to this PR which adds support for generated columns which do not yet exist in Postgres 11: https://github.com/ClickHouse/ClickHouse/pull/57568.

I have only tested the table engine in Cloud so far, this likely also affects other engines that use the `fetchPostgreSQLTableStructure` function.

**Comment by jsc0218** [comment]
I think we don't need to support pg11 as it is a too old version. I saw you [pr](https://github.com/ClickHouse/ClickHouse/pull/60608) here, does the issue still exist at version 12?

**Comment by Algunenano** [comment]
PG itself doesn't support PG11

**Comment by donge** [comment]
> PG itself doesn't support PG11

our case the connection is not PG11, but PG11 compatible database, vote to support it
