### ISSUE TITLE
Why was leader_expiry removed in CoordinationSettings

### ISSUE THREAD

**Issue by Brokenice0415** [ClickHouse/ClickHouse#60688]
The parameter `leader_expiry` is used to make leader check if it still has majority in NuRaft, and it can avoid multiple leaders if it is set smaller than `election_timeout_lower_bound`. [NuRaft Doc](https://github.com/eBay/NuRaft/blob/master/docs/leadership_expiration.md#if-you-want-to-avoid-multiple-leaders)

Only when there is no leadership ovlapping, a KeeperServer can guarantee it is leader by `isLeader()` since this function only checks the local state instead of starting a new round of heartbeat to check there is no other leader. 

If not, the invalid leader, which does not know that itself has lost the majority, will still accept clients' requests until it receives the real leader's heart beat. This may break the lineariability.

Although the leader expiry can not completely achieve lineariable read because of the clock skewness, I think the customization is nice.

I noticed that this parameter was provided in this pr #38200. Why was it removed later?

**Comment by antonio2368** [comment]
The entire PR was reverted because of the negative performance impact on nonlinearizable reads.
I don't have any argument against adding the setting back, are you maybe interested in doing it?
It should be a straightforward couple of lines of change.

**Comment by Brokenice0415** [comment]
@antonio2368  Sure, I'm glad to do this.
