### ISSUE TITLE
'INSERT .. SELECT WHERE' not inserting rows, but the same SELECT selects them

### ISSUE THREAD

**Issue by fillest** [ClickHouse/ClickHouse#60687]
I'm performing `INSERT .. SELECT WHERE` with some filter, but it inserts nothing. But if I copy-paste the same SELECT, it shows that the rows exist. I was able to work around this bug by moving the filter expression to a WITH clause, so it probably looks like a parser/interpreter bug to me.

I'm failing to reproduce it with synthetic tables so I'm posting the real expressions with changed names.

```sql
insert into db.tbl_hourly__shard (ev_time_hour, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a1, a2, a3, a4)
select toStartOfHour(ev_time) as ev_time_hour, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a1, a2, a3, a4
from db.tbl__shard where ev_time >= '2024-02-01 00:00:00' and ev_time <= '2024-02-03 00:00:00'
```

Changing the operators to > and < behaves the same.
If I left only the `ev_time <= '2024-02-03 00:00:00'` expression, it inserts something.

If I move one of the filtering expressions or both of them into a WITH, it works correctly:

```sql
insert into db.tbl_hourly__shard (ev_time_hour, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a1, a2, a3, a4)
with ev_time >= '2024-02-01 00:00:00' as time_step
select toStartOfHour(ev_time) as ev_time_hour, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, a1, a2, a3, a4
from db.tbl__shard where time_step and ev_time <= '2024-02-03 00:00:00'
```

The tables:

```sql
CREATE TABLE db.tbl__shard (
    ev_time                 DateTime DEFAULT now(),
    -- a, b, c .. column types probably doesn't matter?
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/db.tbl', '{replica}')
ORDER BY (ev_time, one_of_columns)
PARTITION BY toStartOfWeek(ev_time);

CREATE TABLE db.tbl_hourly__shard (
    event_count             Int64 DEFAULT 1,
    ev_time_hour            DateTime DEFAULT toStartOfHour(ev_time),
    ev_time                 DateTime DEFAULT toStartOfHour(now()) TTL ev_time_hour + INTERVAL 1 MINUTE,
    -- the same a, b, c .. columns
) ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/db.tbl_hourly', '{replica}', (some, of, columns))
PARTITION BY toStartOfWeek(ev_time_hour)
ORDER BY (ev_time_hour, most, of, the, columns);
```

The server and client are both 23.3.8.22.altinitystable (23.3.8.21-lts with a couple of backported fixes):
```
ClickHouse client version 23.3.8.22.altinitystable (altinity build).
Connected to ClickHouse server version 23.3.8 revision 54462.
```

This _doesn't_ reproduce it for me:
```sql
sudo podman run -it --rm docker.io/clickhouse/clickhouse-server:23.3.8.21 clickhouse-local
CREATE TABLE test1 (t DateTime, s String) Engine=Memory;-- order by (t);
CREATE TABLE test2 (g DateTime, t DateTime, s String) Engine=Memory ;-- order by (g);
insert into test1 (s, t) values ('test1', now());
insert into test1 (s, t) values ('test2', now());
insert into test2 (s, g) select s, t from test1 where t > '2024-03-02 02:36:10' and t < '2024-03-02 03:36:30';
select * from test1
select * from test2
```

**Comment by UnamedRus** [comment]
Can you check query with setting `insert_deduplicate=0`


https://kb.altinity.com/altinity-kb-schema-design/insert_deduplication/

**Comment by fillest** [comment]
1) It happens on a fresh shard on which I didn't perform any such inserts.
2) `WITH`-trick results in the insert working
But I will try to test it later, OK..

**Comment by filimonov** [comment]
Any luck? Also - do you remember that the SummingMergeTree have a logic removing the row if the sum is 0?

**Comment by den-crane** [comment]
DBeaver ?

--max_result_rows arg                                                                Limit on result size in rows. The query will stop after processing a block of data if the threshold is met, but it will not cut the last block of the result, therefore the result size can be larger than the threshold.

--result_overflow_mode arg                                                           What to do when the limit is exceeded.

**Comment by alexey-milovidov** [comment]
> ClickHouse client version 23.3.8.22.altinitystable (altinity build).

We don't support third-party builds.
