### ISSUE TITLE
Dictionary with MongoDB as source configuration working in 22.8.3.13 and stopped working in 23.8.2

### ISSUE THREAD

**Issue by PyCht** [ClickHouse/ClickHouse#60698]
This is the MongoDB config we were using:
`
SOURCE(MONGODB( 
    host 'mongo'
    port 27017
    user ''
    password ''
    db 'Main'
    collection 'Users'
))
`
which was working good in clickhouse 22.8.3.13 but after upgrading to version 23.8.2 any query we tried to run against this dictionary returned the following error: `Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: Timeout: connect timed out: IP_ADDRESS:27017. (POCO_EXCEPTION)`

After some debugging and trying few options we found out that adding the following to the source config fixed the issue:
`options 'connectTimeoutMS=10000'`

I would like to know what was the root cause and what was connectTimeoutMS default value in both versions?

Thanks

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/55232

**Comment by rpstw** [comment]
I'm facing this issue using 23.8.14. It seems https://github.com/ClickHouse/ClickHouse/pull/55419 does not solve the timeout problem?
