### ISSUE TITLE
antlr4 files CTE Support improvement

### ISSUE THREAD

**Issue by piyushdatazip** [ClickHouse/ClickHouse#60722]
**Use case**

Currently ANTLR4 Grammar successfully parses 
```
with 
t0 AS (select 1),
t1 AS (select 2)
select * from t0, t1
```
But fails to parse 
```
Select * from (
with 
t0 AS (select 1),
t1 AS (select 2)
select * from t0, t1
)
```

**Describe the solution you'd like**

Would like to get this syntax parsing to be supported
https://github.com/ClickHouse/ClickHouse/blob/master/utils/antlr/ClickHouseLexer.g4
https://github.com/ClickHouse/ClickHouse/blob/master/utils/antlr/ClickHouseParser.g4

**Describe alternatives you've considered**

**Additional context**

Current Error
```
3:6 no viable alternative at input 'Select*from(witht0AS('
```

**Comment by alexey-milovidov** [comment]
We don't support these files. So either someone else will update them, or we just close this.

**Comment by Algunenano** [comment]
Nobody updated them
