### ISSUE TITLE
"Data Synchronization Issue and Query Management When a Read-Only Replica Exists in a Shard"

### ISSUE THREAD

**Issue by huoarter** [ClickHouse/ClickHouse#60739]
Hello,

I encountered a situation while using ClickHouse where a replica within a shard is in read-only mode. In this case, I can write data to another node through a local table as usual. However, it seems that the read-only replica is not receiving any data leading to a failure in synchronizing.

What's more troubling is when querying a distributed table, it randomly queries these two replicas, one of which is in a read-only state. This could lead to inconsistent query results which is not expected.

Additionally, even though I can promptly eliminate the faulty nodes, there's inevitably a delay between the time the nodes become unserviceable and my response to it. My key concern is how to prevent queries from being directed to nodes that hold incomplete data during this interim period.

Ideally, there should be a mechanism to detect a node failure or changes to read-only state, and instantly exclude it from the pool of queryable nodes until it's fully back in sync with other replicas within the same shard. This could help to ensure data integrity and consistency for all queries.

Steps to reproduce:

Set a replica in a shard to read-only.
Write data to another node in the shard.
Attempt to query the distributed table while the problematic node still exists.
Expected Result:

The query to the distributed tables should not include the read-only replica, or there should be some fail-safe mechanism to uphold the consistency of the results.

Actual Result:

Data is not synchronized to the read-only replica, and during the query, it considers the not-yet-synchronized read-only replica, leading to inconsistent results.

I would greatly appreciate your advice and any guidance on mitigating this issue. Many thanks in advance for your help!

**Comment by alyanm** [comment]
@huoarter - I have forwarded your question on to our data plane team.

**Comment by alyanm** [comment]
@huoarter -- 
`I encountered a situation while using ClickHouse where a replica within a shard is in read-only mode. In this case, I can write data to another node through a local table as usual. However, it seems that the read-only replica is not receiving any data leading to a failure in synchronizing.`
Isn't it expected that readonly replica doesn't get new data?
`Set a replica in a shard to read-only.`
How do you switch it to readonly mode? There's no way to do it without breaking something (like removing some metadata from ZooKeeper, or disconnecting the replica from ZooKeeper)
`The query to the distributed tables should not include the read-only replica`
This is questionable. The replica is not unavailable, it's readonly, so why not to read from it? We only guarantee eventual consistency anyway.

**Comment by huoarter** [comment]
Yes, you might be right, ClickHouse guarantees eventual consistency. For instance, if a disk on a node becomes read-only at a certain moment, during this time one replica of the shard is writable while the other is not, and there might be differences in data during the fault period. Is there any method that can make the distributed table aware that one of the replicas in this shard has incomplete data, so that when querying through the distributed table, the faulty replica is not accessed? I know that if writing through the distributed table, when one replica fails to write data, an error_count is automatically inserted into the system.replication_queue, and the distributed table will choose the replica with the lower error_count for queries. But what if writing occurs through a local table, is there a way to avoid querying the bad replica in this case?
