### ISSUE TITLE
Consider removal of clickhouse-copier

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#60734]
It is hard to use, and it is hardly supported.

**Comment by yujiarista** [comment]
Any replacement?

**Comment by alexey-milovidov** [comment]
Copier is run as a standalone tool, so we can publish the latest version for download, and it will continue to work as before for existing users.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/copier

**Comment by it-forever** [comment]
This is the best tool for transferring and resharding data. We use a packaged config in helm chart and it works as a universal tool for data transfer.
Should helm chart be added to your repository?

**Comment by alexey-milovidov** [comment]
Yes, let's add the helm chart to the new repository.

**Comment by VicoWu** [comment]
> It is hard to use, and it is hardly supported.

Why is it hard to use? 
What's the reason that it is hardly supported?
