### ISSUE TITLE
Is Prometheus metrics data just for one instance in Cluster Mode?

### ISSUE THREAD

**Issue by CzyerChen** [ClickHouse/ClickHouse#60732]
Now I had a Cluster with several Node, I want to fetch  metrics through prometheus endpoint.
Do I have to receive metrics from each node and sum up, or just fetch data from one node is ok?

Doc: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#prometheus

**Comment by alexey-milovidov** [comment]
Yes, it is per server. For a cluster, you should collect it from every server.

**Comment by CzyerChen** [comment]
For more about the metrics, I found  the monitor data always `0`, any ideas?

ClickHouseMetrics_KeeperAliveConnections, when I having tcp/http connections, it always `0`.
ClickHouseMetrics_PartMutation, when I executing `ALTER DELETE/UPDATE`, recording actions in table `system.mutations` but not changing the metric. 

@alexey-milovidov  can you help?
