### ISSUE TITLE
How to reduce memory consumption in a low-memory system

### ISSUE THREAD

**Issue by mvgreen** [ClickHouse/ClickHouse#60744]
Hi! We're observing a strange memory consumption in our testing environments. Clickhouse server in this environment is given 150m cpu and 1500mb in kubernetes config. In this environment, a bunch of automated tests are executed in parallel, totaling in about 300-450 concurrent selects with complicated structure (most of them have 2-3 nested selects in depth) on ~300 rows in the table. We also have about 25 materialized views for that table but they are not used in the tests.

The tests break quite frequently because of clickhouse throwing errors like these
```
Code: 241. DB::Exception: Memory limit (total) exceeded: would use 1.32 GiB (attempt to allocate chunk of 0 bytes), maximum: 1.32 GiB. OvercommitTracker decision: Memory overcommit has freed not enough memory.: While executing AggregatingTransform. (MEMORY_LIMIT_EXCEEDED) (version 23.8.8.20 (official build))
```

I looked into stats generated by clickhouse and found that after selects are executed it does not clear all of the used memory and when memory limit is exceeded it kills new queries. 
Here's an example of what is going on with memory when the problem occurs:

<img width="870" alt="overcommit_memory" src="https://github.com/ClickHouse/ClickHouse/assets/12169039/816e5e9d-ae6c-48dc-ba34-f29147cb49cc">
<img width="869" alt="overcommit_rate" src="https://github.com/ClickHouse/ClickHouse/assets/12169039/2c6c4ab7-5f4f-4c13-9f07-da5451de41e5">
<img width="868" alt="overcommit_count" src="https://github.com/ClickHouse/ClickHouse/assets/12169039/61b190aa-b0be-4582-8003-9b83a02b4d47">

I tried adding another gb of memory, disabling merges, disabling every cache I found in documentation, but the only time I managed to significantly lower memory consumption was when I ran the tests consecutivelly (but you can see the memory is still steadily rising after each restart of the tests)

<img width="780" alt="lowered_memory" src="https://github.com/ClickHouse/ClickHouse/assets/12169039/0de80bfc-2c16-43ce-a7e4-c7b18a34a5a8">
<img width="780" alt="lowered_rate" src="https://github.com/ClickHouse/ClickHouse/assets/12169039/997b4b24-b99d-494d-bd5c-244fc77faa47">
<img width="780" alt="lowered_count" src="https://github.com/ClickHouse/ClickHouse/assets/12169039/85fad0d0-22c8-47ca-9cc8-c588e8c44a4b">

What causes clickhouse to keep that memory and how to make clickhouse release it? Since we create a lot of instances of our testing environment every day and only a small portion of them needs to interact with clickhouse, I want to find a solution that prioritizes low memory requirements.

**Comment by rschu1ze** [comment]
@mvgreen Could you check related issue https://github.com/ClickHouse/ClickHouse/issues/60016?

**Comment by mvgreen** [comment]
@rschu1ze I tried the following config, but it didn't help at all, this time clickhouse even stopped responding to any requests (but didn't seem to crash).
In config.d/extra.xml
```
<clickhouse>
  <max_io_thread_pool_size replace="replace">16</max_io_thread_pool_size>
  <index_mark_cache_size replace="replace">0</index_mark_cache_size>
  <index_uncompressed_cache_size replace="replace">0</index_uncompressed_cache_size>
  <mark_cache_size replace="replace">1000</mark_cache_size>
  <uncompressed_cache_size replace="replace">0</uncompressed_cache_size>
  <query_cache>
    <max_size_in_bytes>0</max_size_in_bytes>
  </query_cache>
  <cache_size_to_ram_max_ratio replace="replace">0</cache_size_to_ram_max_ratio>
  <logger>
    <level>warning</level>
    <console>true</console>
  </logger>
  <query_thread_log remove="remove"/>
  <query_log remove="remove"/>
  <query_views_log remove="1" />
  <text_log remove="remove"/>
  <trace_log remove="remove"/>
  <metric_log remove="remove"/>
  <asynchronous_metric_log remove="remove"/>
  <session_log remove="remove"/>
  <part_log remove="remove"/>
  <opentelemetry_span_log remove="1"/>
  <zookeeper_log remove="1"/>
</clickhouse>
```
In user.d/extrauser.xml:
```
<clickhouse>
  <profiles>
    <default>
      <enable_filesystem_cache replace="replace">0</enable_filesystem_cache>
      <log_queries>0</log_queries>
      <log_query_threads>0</log_query_threads>
    </default>
  </profiles>
</clickhouse>
```

**Comment by rschu1ze** [comment]
Thanks. The problem is that ClickHouse currently does not have a good way to debug / break down its total current memory consumption into groups of memory consumers (e.g. cache A, cache B, SELECT query C, merge D) - at least none which I am aware of. What is possible is to check how much memory individual caches / queries / background operations consume (see [here](https://clickhouse.com/docs/en/guides/developer/debugging-memory-issues)). But as I understand, the problem is that memory isn't getting released after SELECT queries, so the existing memory introspection tools are not be too helpful when one doesn't know where some "residual" memory is going.

In general, exceptions

```
Code: 241. DB::Exception: Memory limit (total) exceeded: would use 1.32 GiB (attempt to allocate chunk of 0 bytes), maximum: 1.32 GiB. OvercommitTracker decision: Memory overcommit has freed not enough memory.: While executing AggregatingTransform. (MEMORY_LIMIT_EXCEEDED) (version 23.8.8.20 (official build))
```

are kind of expected on a tiny system with 1.5 GB of DRAM (the [usage recommendation](https://clickhouse.com/docs/en/operations/tips#ram) is 32 GB). (Attempting to allocate a chunk of *0* bytes is weird).

What you may also try is to reduce the degree of parallelism in SELECT queries (setting `max_threads`) - this also reduces memory consumption. There are also many settings to force memory-efficient external aggregation/joins ([here](https://clickhouse.com/docs/en/operations/settings/query-complexity)) if your queries do that.

**Comment by mvgreen** [comment]
I tried setting `max_threads` to `1` and to `8` + enabling `optimize_aggregation_in_order`, but it didn't help either. Seems like the only option for us is to run the tests sequentially.

But just to clarify my understanding of these settings, I want to ask a few more questions. 
Does `max_threads` limit the pool size for all queries, or does it limit amount of threads each query can use? 
By default, it is already set to `auto(1)` (I assume it's because kubernetes limits CPU to 150m?)
Also, is there a way to verify that a user config file is applied? I tried `select getSetting('max_threads')` under credentials of our server, but it looks like it returns the system-wide value

**Comment by mvgreen** [comment]
`m` in this context is a 'milliCPU', so it's less than 1 core. 
`auto(1)` also looked weird to me, but to my understanding, it might be some kind of built-in indicator that this value is set automatically by clickhouse.

> See system table system.settings
This table also doesn't return the user-specific configuration

**Comment by rschu1ze** [comment]
Re caches: The biggest one is typically the mark cache but there are a few others (see [here](https://clickhouse.com/docs/en/operations/caches) if you don't know this page already). You could search for `_cache_size` in https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings and set them to 0. (Besides that, I don't have good ideas anymore.)

**Comment by rschu1ze** [comment]
Please re-open if more information is available.

**Comment by T100D** [comment]
There are some options we bumped into:

   <max_server_memory_usage_to_ram_ratio>0.75</max_server_memory_usage_to_ram_ratio>


and:

   <mark_cache_size>5368709120</mark_cache_size> >> to
   <mark_cache_size>2684354560</mark_cache_size>

and

  <max_thread_pool_size>10000</max_thread_pool_size>  >> to
 <max_thread_pool_size>5000</max_thread_pool_size>


There is a good article here on it:
https://kb.altinity.com/altinity-kb-setup-and-maintenance/configure_clickhouse_for_low_mem_envs/
