### ISSUE TITLE
Asia/Almaty timezone has been changed

### ISSUE THREAD

**Issue by andrey87** [ClickHouse/ClickHouse#60750]
Hi 
From the 1 of March 2024 most of the cities in Kazakhstan have been changed time to new TZ +05:00, previously +06:00
https://mm.icann.org/pipermail/tz-announce/2024-February/000081.html

Clickhouse works works on RHEL 7 and 8 version, in OS has been installed new TZ fpackage tzdata-2024a-1.el8.noarch, tzdata-2024a-1.el7.noarch
After the 1st of March, Clickhouse did not move to a new time zone.
Could you say, how Clickhouse gonna know about new TZ, it will be released in new version or new hotfix ?

**Comment by rschu1ze** [comment]
I did not check deeper but what I can tell is that:
- as per https://github.com/ClickHouse/ClickHouse/pull/10425 ClickHouse bundles the cctz library
- file contrib/cctz-cmake/TimeZones.generated.cpp (generated at build time) does include time zone Asia/Almaty.

**Comment by Algunenano** [comment]
We need to update the submodule.

**Comment by UnamedRus** [comment]
I think, system tzdata should have preference over buildin
