### ISSUE TITLE
Allow to CREATE another replica of ReplicatedMergeTree table without specifying its structure.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6079]
**Use case**
`CREATE TABLE t ENGINE = ReplicatedMergeTree(...)`
instead of
`CREATE TABLE t (structure) ENGINE = ReplicatedMergeTree(...)`

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/30671

Done in https://github.com/ClickHouse/ClickHouse/pull/32455
