### ISSUE TITLE
Configurable shifting parameter (lag) for partial dictionary update instead of hardcoded 1s. 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#6084]
Currently CH uses hardcoded (-1 sec) lag.

https://github.com/yandex/ClickHouse/blob/master/dbms/src/Dictionaries/HTTPDictionarySource.cpp#L58
>time_t hr_time = std::chrono::system_clock::to_time_t(tmp_time) - 1;

This is unusable for many users (they need 5 or 15 min. instead of 1sec.)
That's why they use different workarounds 

` <update_field>date_add(updated_date, interval 15 minute)</update_field>`
`<update_field>updated_at + interval '5 minute'</update_field>` 
This is inconvenient and breaks index search by indexed updated_date (fullscan)

So my proposal to introduce an attribute `lag` (time_shift) for dictionary config `<update_field "lag"=300>updated_at</update_field>`

**Comment by astudnev** [comment]
Why it takes local update time instead of the last update time of the dictionary data? That would remove the nessesity of any lag. Lag is hard to control, especially when dictionary read from db slave

**Comment by den-crane** [comment]
For example it's the only solution for us.

1.
T0: Transaction1 makes an insert (updated_at=T0)
T1: Transaction2 makes an insert (updated_at=T1)
T2: Transaction2 commits
T3: Dictionary gets updates and sees max updated_at = T1.
T4: Transaction1 commits -- changes lost forever.

2. We have a dictionary which is updated ONLY ONCE per day at unknown time every day (daily prices), it is gets 10k new rows with the same time updated_at. We reload this dictionary every 5 minutes with a -15 minutes shift, so we load the same 10k rows only 3 times.

**Comment by alexey-milovidov** [comment]
Makes sense and is easy to implement.
