### ISSUE TITLE
Skim fuzzy search clutters terminal (a bug in Rust library)

### ISSUE THREAD

**Issue by larry-cdn77** [ClickHouse/ClickHouse#60909]
The Skim fuzzy search introduced through #44239 in version 23.1 (I believe) somehow started working for me on macOS at version 24.3

So I have had a quick go with it and found a number of reasons to stick to regular shell-like search (appreciate leaving in Ctrl+T as a fallback) that I wanted to share as a bit of a command line power user:

1. I find tapping up and down arrows to select a suggestion unsuitable for real work, one continuously refined suggestion is all I need
2. twenty suggestions jump around crazily as I type additional characters making me feel rather disoriented although that may be something one eventually gets used to
3. most queries don't fit so are clipped on one or both sides rendering the suggestion worthless; being presented with five identically looking lines makes refining the search harder not easier
4. mouse is hijacked, presumably to aid the up/down arrow issue but that is not what mouse is for in a terminal session (I need to be able to select text to copy at any time)
5. worst of all, exiting the search does a hard clear of the console scrollback; for me the scrollback is the most valuable thing in my terminal session, an easily accessible record of what I have done most recently, and one I hate to lose every time I search

Aside from sharing this feedback I also wanted to suggest the fuzzy search be enabled with a CLI argument rather than a distinct keyboard shortcut, either `--fuzzy-search` to enable Skim (default on) or `--classic-search` to disable it (default off)

Ideally, adding fuzzy search and altering the search user interface are two different things; in practice, they may be difficult to separate, I appreciate

As a matter of search philosophy, maybe someone could help me ponder the usefulness of fuzzy search in the CLI. I have learnt so well that typing 'E T' gets me a recent 'CREATE TABLE' statement that I see no value in being able to type 'CRE TAB'. I know what 'E T' will return whereas I will not be able to guess reliaby what 'CRE TAB' will return. So what good is it if it leads to additional attempts?

All in all, I am glad to see an improvement albeit still in its' UI infancy! 👍

**Comment by Algunenano** [comment]
> mouse is hijacked, presumably to aid the up/down arrow issue but that is not what mouse is for in a terminal session (I need to be able to select text to copy at any time)

This seems odd. It doesn't happen in Linux with konsole, so it might be related to OSX or OSX's Terminal.

> worst of all, exiting the search does a hard clear of the console scrollback; for me the scrollback is the most valuable thing in my terminal session, an easily accessible record of what I have done most recently, and one I hate to lose every time I search

Agree. This is "suboptimal" UX. Other programs don't clear the screen to handle this.

> Ideally, adding fuzzy search and altering the search user interface are two different things; in practice, they may be difficult to separate, I appreciate

> As a matter of search philosophy, maybe someone could help me ponder the usefulness of fuzzy search in the CL

It's extremely useful to me. I sometimes remember only parts of a query (like the table name and a condition or a column), so being able to just input those and getting results it's nice. But I also use this kind of search in bash via `fzf`, so I'm used to it.

To begin with let's add `--interactive-history` / `--no-interactive-history` (enabled by default) for those that don't want to have fuzzy search and interactive history. The old code and behaviour is there if you don't build the necessary libraries, so it's a matter of adding a setting.

**Comment by larry-cdn77** [comment]
Thanks for the response

Indeed, the mouse is less of an issue than the loss of context when my screen is cleared

A flag for interactive history sounds perfect

I might be able to look into preparing a PR for this depending on how much effort it is to get the build going with the Rust toolchain as well

**Comment by larry-cdn77** [comment]
I believe https://github.com/ClickHouse/ClickHouse/pull/63261 addressed this
