### ISSUE TITLE
groupArraySorted needs parameter in example

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#60923]
https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/grouparraysorted 

```sql
SELECT groupArraySorted(str) FROM (SELECT toString(number) as str FROM numbers(5));
```
This example needs parameter to see the output like in docs.
Otherwise:
```

Received exception from server (version 24.2.1):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Parameter for aggregate function groupArraySorted should have limit argument. (BAD_ARGUMENTS)
(query: SELECT groupArraySorted(str) FROM (SELECT toString(number) as str FROM numbers(5));)
```

It might have been intended for inclusion in the documentation without specifying concrete parameters; however, it is still advisable to report it for clarity.

**Comment by Algunenano** [comment]
It seems like an oversight. This function was initially introduced with the parameter being optional, but in the final implementation that's currently available it's mandatory. I'll update the docs for now, although we could consider introducing a default value (similar to topK).
