### ISSUE TITLE
DB::Exception: couldn't allocate 7 bytes when parsing JSON  clickhouse, CANNOT_ALLOCATE_MEMORY

### ISSUE THREAD

**Issue by whitekoolz** [ClickHouse/ClickHouse#60988]
system Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020

clickhouse version : 24.2.1.2248

all clickhouse config is default ,and the system has enough memory

when Execute this simple SQL:  select JSONExtractString('{"a","123"}','a'),  the error comes:  DB::Exception: couldn't allocate 11 bytes when parsing JSON  clickhouse, CANNOT_ALLOCATE_MEMORY

witch god can tell me how to resolve this problem?

**Comment by alexey-milovidov** [comment]
Do you use QEMU?

**Comment by whitekoolz** [comment]
> Do you use QEMU?

yes

**Comment by whitekoolz** [comment]
> Do you use QEMU?

do you mean clickhouse may have compatibility problems on QEMU?

**Comment by presto78** [comment]
Hello! We have a similar problem after upgrade to 24.2.2.71.

**Comment by alexey-milovidov** [comment]
@whitekoolz Yes, certain virtualization mechanisms don't work with the simdjson library, check https://github.com/ClickHouse/ClickHouse/issues/60661

**Comment by zzmark** [comment]
> Hello! We have a similar problem after upgrade from 23.11.2.11 to 24.2.2.71. We don't use QEMU - use CH in k8s (baremetal).

check your /proc/cpuinfo 

has not avx ?

**Comment by Algunenano** [comment]
Same as https://github.com/ClickHouse/ClickHouse/issues/60661
