### ISSUE TITLE
Ambiguous column error reported when fully qualifying columns from a table that appears multiple times in the FROM clause

### ISSUE THREAD

**Issue by lukaseder** [ClickHouse/ClickHouse#61014]
**Describe what's wrong**

When repeating the same table multiple times in the `FROM` clause (with and without alias), then fully qualified columns are reported as ambiguous, when they really aren't.

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

* Which ClickHouse server version to use: 24.2.1.2248
* Which interface to use, if it matters: JDBC (but it doesn't matter)
* Non-default settings, if any: N/A

```sql
create table a (i int) engine = Log();

select 
  default.a.i
from 
  default.a,
  default.a as x;
```

**Expected behavior**

The query should work

**Error message and/or stacktrace**

> Received exception from server (version 24.2.1):
> Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Ambiguous column 'default.a.i': While processing default.a.i. (AMBIGUOUS_COLUMN_NAME)
> (query: select 
>   default.a.i
> from 
>   default.a,
>   default.a as x;)

**Workaround**

Omit full qualification:

```sql
create table a (i int) engine = Log();

select 
  a.i
from 
  default.a,
  default.a as x;
```

**Comment by den-crane** [comment]
works with analyzer

https://fiddle.clickhouse.com/dde012e9-cab0-4832-a1f7-500235e616f9

**Comment by lukaseder** [comment]
This no longer reproduces with 24.3.1.2672

**Comment by den-crane** [comment]
New analyzer is enabled by default with 24.3.

**Comment by lukaseder** [comment]
Good to know, thanks
