### ISSUE TITLE
Performance issues in multi-dimensional deduplication scenarios with multiple deduplication fields

### ISSUE THREAD

**Issue by ongbo** [ClickHouse/ClickHouse#61023]
In a multi-dimensional deduplication scenario, if there is only one field to be deduplicated, this field can be hashed and imported into clickhouse. But if there are multiple fields to be deduplicated, the non-hashkey fields will need to be fully aggregated. I have tried to store all the deduplicated fields in the intermediate state of bitmapState. When querying, they are first aggregated locally, and then the coordinator performs merge. However, the effect does not seem to be very good. The bitmap fields in these intermediate states are very large.
The amount of data per day is 600 million.
The query period is 30 days, 60 days or one year.
Then it is possible to roll up in any dimension to remove duplicates.
Are there any good algorithms and optimization methods?

**Comment by nickitat** [comment]
could you pls provide a specific example, including DDL, and what you're trying to achieve.

**Comment by ongbo** [comment]
> could you pls provide a specific example, including DDL, and what you're trying to achieve.

TABLE: The amount of data per day is 600 million.
The query period is 30 days, 60 days or one year.

There are a total of 32 machines, with dimensions A, B, C, D, and E, and deduplication key1, key2, key3, and key4.
query SQL：
select
   count(distinct key1),
  count(distinct key2),
  count(distinct key3)
...
from TABLE
group by A,B

But the query performance is very poor
