### ISSUE TITLE
Don't leave behind an empty znode when dropping ReplicatedMergeTree

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#61065]
When dropping ReplicatedMergeTree in Replicated databse, we remove znode "/clickhouse/tables/{uuid}/{shard}" (default_replica_path), but keep the parent znode "/clickhouse/tables/{uuid}". If lots of tables are created and dropped, lots of empty znodes are left.

This will become more noticeable with refreshable materialized views, which create+drop a table on each refresh.

A possible solution is to make ReplicatedMergeTree delete parent znode too, if it became empty. The two znodes should probably be deleted in one transaction, otherwise there's a race with createAncestors(). If the double-delete transaction failed with ZNOTEMPTY, retry it with just one znode.

**Comment by filimonov** [comment]
Recently we also observed the case when the (temporary) tables were created in the root path of zookeeper i.e. 

```
CREATE TABLE temp_table_20240630_115600_deadbeef ON CLUSTER ... (...) ReplicatedMergeTree('/{table}/{shard}' )
....
DROP TABLE temp_table_20240630_115600_deadbeef ON CLUSTER ...;
```

Leading to surprising side-effect - the zookeeper monitoring stop to work properly (zookeeper consider every top path as namespace and have some set of metrics per namespace), so number of metrics start to explode leading to timeouts and issues with prometheus.
