### ISSUE TITLE
Making a query through http to a table, attached to Kafka Engine, crushes server

### ISSUE THREAD

**Issue by kayanme** [ClickHouse/ClickHouse#61060]
I have a table with null engine attached via materialized view to a kafka engine table (being a producer here).
So the goal is to insert into the first table and transfer data to the kafka in a transparent way.

Here is a reproducible example.
```SQL
create table default.insertlocal  (num UInt32) Engine=Null();

create table default.insertlocal2 as   default.insertlocal Engine=Memory();
create or replace table KafkaSend  as  default.insertlocal ENGINE = Kafka ('kafka:29092', 'topic', 'clickhouse') SETTINGS kafka_format = 'JSONEachRow';

create materialized view  default.KafkaLink to default.KafkaSend as select * from default.insertlocal;

insert into insertlocal2 select arrayJoin(range(100));
```

And the query below goes fine through the cli, but crashes from Clickhouse Client immediately, leading to corrupted messages to Kafka and, eventually, can break down the server and other tables, which have nothing in common with those ones (complaining on some "bad metadata").

`insert into  default.insertlocal select * from default.insertlocal2`

I know, that it could be an issue with the client realization, but it could be a possible vulnerability.

P.S. The insertion could be straight to insertlocal from the client side, i.e. `insert into insertlocal values (1),(2)` The example shows, that it does not matter which data came from client, it is just the query itself which break.
If we put one value - we will have one good message to Kafka. If there are two or more - we have one good message, one corrupted and the error.

Version is 24.3.1.282 (revision: 54484, git hash: a1d1f76f67ab29c759374cf5a51b2e1fecf933f8, build id: 6FECFF7A9785B8EFE1F500762D6EB7190AEA4B73

And it seems working in 23.8 at least.

I am using C# Clickhouse Client 7.1.1.

Error 1 stack:

<Error> TCPHandler: Code: 1001. DB::Exception: std::length_error: basic_string. (STD_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. std::length_error::length_error[abi:v15000](char const*) @ 0x00000000076a3189
1. std::__throw_length_error[abi:v15000](char const*) @ 0x00000000076a3140
2. ? @ 0x00000000076a30eb
3. ? @ 0x00000000174f4e67
4. DB::WriteBufferFromVector<String>::finalizeImpl() @ 0x00000000076ba2af
5. DB::WriteBuffer::finalize() @ 0x00000000076b2c08
6. DB::MessageQueueSink::consume(DB::Chunk) @ 0x0000000011b5c4fd
7. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x0000000012b6a022
8. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x0000000012a9a54b
9. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000012a9a25c
10. DB::ExceptionKeepingTransform::work() @ 0x0000000012a99933
11. DB::ExecutionThreadContext::executeTask() @ 0x000000001282e09a
12. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000012824af0
13. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000128242a8
14. DB::TCPHandler::runImpl() @ 0x00000000127bdbf7
15. DB::TCPHandler::run() @ 0x00000000127cdfb9
16. Poco::Net::TCPServerConnection::start() @ 0x00000000150ae1b2
17. Poco::Net::TCPServerDispatcher::run() @ 0x00000000150aefb1
18. Poco::PooledThread::run() @ 0x00000000151a7647
19. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000151a5c7d
20. ? @ 0x00007f3a9d2cb609
21. ? @ 0x00007f3a9d1f0353

Error 2 stack:

{5a3ffd45-4f7e-4e16-aa70-a471501874af} <Error> executeQuery: std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Broker: Message size too large (version 24.3.1.282 (official build)) (from 10.112.208.27:44160) (in query: INSERT INTO skipped this  VALUES), Stack trace (when copying this message, always include the lines below):

0. cppkafka::Producer::produce(cppkafka::MessageBuilder const&) @ 0x0000000014d9dad9
1. DB::KafkaProducer::produce(String const&, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) @ 0x000000000fd5738b
2. DB::MessageQueueSink::consume(DB::Chunk) @ 0x0000000011b5c518
3. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x0000000012b6a022
4. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x0000000012a9a54b
5. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000012a9a25c
6. DB::ExceptionKeepingTransform::work() @ 0x0000000012a99933
7. DB::ExecutionThreadContext::executeTask() @ 0x000000001282e09a
8. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000012824af0
9. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x00000000128242a8
10. DB::TCPHandler::runImpl() @ 0x00000000127bdbf7
11. DB::TCPHandler::run() @ 0x00000000127cdfb9
12. Poco::Net::TCPServerConnection::start() @ 0x00000000150ae1b2
13. Poco::Net::TCPServerDispatcher::run() @ 0x00000000150aefb1
14. Poco::PooledThread::run() @ 0x00000000151a7647
15. Poco::ThreadImpl::runnableEntry(void*) @ 0x00000000151a5c7d
16. ? @ 0x00007f6660db9609
17. ? @ 0x00007f6660cde353

**Comment by kayanme** [comment]
Concluding the results - here the reproducible example.
```SQL
create table default.insertlocal  (num UInt32) Engine=Null();

create table default.insertlocal2 as   default.insertlocal Engine=Memory();
create or replace table KafkaSend  as  default.insertlocal ENGINE = Kafka ('kafka:29092', 'topic', 'clickhouse') SETTINGS kafka_format = 'JSONEachRow';

create materialized view  default.KafkaLink to default.KafkaSend as select * from default.insertlocal;

insert into insertlocal2 select arrayJoin(range(100));
```

And this goes fine from the server, but crashes from Clickhouse Client 
`insert into  default.insertlocal select * from default.insertlocal2`

I know, that it could be the problem of the client realization, but it could be possible vulnerability, because it breaks down the server eventually.

**Comment by antaljanosbenjamin** [comment]
> And the query below goes fine through the cli, but crashes from Clickhouse Client immediately

What do you mean by CLI and ClickHouse Client? Also the title says `Making a query through http to a table`, could you please clarify the reproduction steps?

**Comment by dvcong-vnm** [comment]
Hi @kayanme,  You have solved this problem? I face this issue when upgrade clickhouse from 23.2.4.12 to 24.3.4.147.

**Comment by paulyurlov** [comment]
@antaljanosbenjamin 
Hi! I am facing the same problem on clickhouse 24.4.1.2088

Insertion into table with kafka engine works using clickhouse-client (cli), but for clickhouse-connect==0.6.23 (Python 3.9) fails with:

 SQL Error [1002]: ClickHouse exception, code: 1002, host: xxxxxxxxx, port: 8123; std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Broker: Message size too large (version 24.4.1.2088 (official build))
 
 nothing special in my query:
 
main query:
 ```SQL
INSERT INTO default.my_table_k
SELECT
    f_1,
    dt,
    f_2,
    f_3
FROM default.my_table FINAL
WHERE upd_dt >= now() - toIntervalHour(48)
```

ddls:
```SQL
CREATE TABLE default.my_table_k
(

    f_1 String,

    dt DateTime,

    f_2 String,

    f_3 Float64
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'xxxxxxx:9092',
kafka_topic_list = 'tmp_test',
kafka_group_name = 'tmp_test',
kafka_format = 'JSONEachRow'

CREATE TABLE default.my_table
(

    f_1 String,

    dt DateTime,

    f_2 String,

    f_3 Float64,

    upd_dt DateTime
)
ENGINE = ReplacingMergeTree
ORDER BY f_1
SETTINGS index_granularity = 8192
```

**Comment by antaljanosbenjamin** [comment]
@paulyurlov Thanks for the detailed reproduction steps. How many data do you have in `default.my_table`? I will try to reproduce it either today or early next week.

**Comment by dvcong-vnm** [comment]
Hi @antaljanosbenjamin , I tested with script bellow: 

step 1: 
`CREATE TABLE rvse_sfa.my_table_k
(

    f_1 String,
    dt DateTime,
    f_2 String,
    f_3 Float64
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'xxx:9092',
kafka_topic_list = 'tmp_test',
kafka_group_name = 'tmp_test',
kafka_format = 'JSONEachRow'`

step 2: 
`INSERT INTO rvse_sfa.my_table_k
(f_1, dt, f_2, f_3)
VALUES('', '2024-01-01 00:00:00', '', 0),
('', '2024-01-01 00:00:00', '', 0),
('', '2024-01-01 00:00:00', '', 0),
('', '2024-01-01 00:00:00', '', 0),
('', '2024-01-01 00:00:00', '', 0),
('', '2024-01-01 00:00:00', '', 0),
('', '2024-01-01 00:00:00', '', 0);
`

error: SQL Error [1002] [07000]: std::exception. Code: 1001, type: cppkafka::HandleException, e.what() = Broker: Message size too large (version 24.3.5.46 (official build))

`0. cppkafka::Producer::do_produce(cppkafka::MessageBuilder const&, cppkafka::HeaderList<cppkafka::Header<cppkafka::Buffer>>&&) @ 0x00000000149a200d
1. DB::KafkaProducer::produce(String const&, unsigned long, std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn>>> const&, unsigned long) @ 0x000000000f94bcad
2. DB::MessageQueueSink::consume(DB::Chunk) @ 0x000000001168fcd8
3. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x000000001272d182
4. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x0000000012659bab
5. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x00000000126598bc
6. DB::ExceptionKeepingTransform::work() @ 0x0000000012658f93
7. DB::ExecutionThreadContext::executeTask() @ 0x00000000123ea0da
8. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000123de630
9. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000123ddaa1
10. DB::CompletedPipelineExecutor::execute() @ 0x00000000123dc232
11. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x0000000011283b28
12. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001230ce35
13. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000123118f4
14. DB::HTTPServerConnection::run() @ 0x0000000012390e9a
15. Poco::Net::TCPServerConnection::start() @ 0x0000000014cba3f2
16. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014cbb239
17. Poco::PooledThread::run() @ 0x0000000014db39a1
18. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014db1f3d
19. ? @ 0x00007dc01bb93609
20. ? @ 0x00007dc01bab8353
`

**Comment by antaljanosbenjamin** [comment]
I could succesfully reproduce the issue, thanks @dvcong-vnm ! I am working on fixing it right now.
