### ISSUE TITLE
Add "from" parameter to toStartOfInterval()

### ISSUE THREAD

**Issue by vitlibar** [ClickHouse/ClickHouse#61079]
The problem with `toStartInterval()` is that it rounds down the time to the beginning of an interval but it doesn't allow to specify when exactly the beginning of the interval should be. For simple cases like `INTERVAL 1 DAY` it's defined that `toStartOfInterval(time, INTERVAL 1 DAY)` means the same as `toStartOfDay(time)`. However for other cases like `INTERVAL 23 HOUR` (or even `INTERVAL 24 HOUR` or `INTERVAL 1440 MINUTE`) the function `toStartOfInterval()` uses some heuristics to find the beginning of that interval. And those heuristics are not necessarily good.

I suggest adding a new optional parameter "base" or "from" to this function (like the clause `WITH FILL FROM` after `GROUP BY`):
```
toStartOfInterval(time, interval, from, timezone)
```
so the result will be `from + intDiv(time - from, interval) * interval`.

Also it seems we can ban `toStartOfInterval()` without the new parameter "from" if the interval is not well known (I mean `toStartOfInterval(time, INTERVAL 24 HOUR)` must throw an exception until the new parameter "from" is specified because it's unknown from which point should we count 24 hours). Probably it's better to add a setting to control that ban.

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/55619 https://github.com/ClickHouse/ClickHouse/pull/56738

**Comment by den-crane** [comment]
implemented
* https://github.com/ClickHouse/ClickHouse/pull/56738
