### ISSUE TITLE
I found memcpySmallAllowReadWriteOverflow15Impl will call built-in memcpy  because of clang loop-idiom optimization. It is as expected, or an issue? 

### ISSUE THREAD

**Issue by taiyang-li** [ClickHouse/ClickHouse#61074]
![dc4d586ae2a041a2e992185fc004747](https://github.com/ClickHouse/ClickHouse/assets/8181003/a62fe533-303f-4067-9e28-5f811809fd24)

 https://godbolt.org/z/YxM3rc7Eh

**Comment by alexey-milovidov** [comment]
Not expected. We already noticed this behavior in GCC a long time ago, but not in Clang:
https://presentations.clickhouse.com/zero_cost_conf/memcpy/#11

**Comment by nickitat** [comment]
it is known 
https://github.com/llvm/llvm-project/issues/56467

**Comment by alexey-milovidov** [comment]
@taiyang-li, let's use `[[clang::no_builtin("memcpy")]]` to better express the intent.

**Comment by taiyang-li** [comment]
> @taiyang-li, let's use `[[clang::no_builtin("memcpy")]]` to better express the intent.

i tried before, but the function won't be inlined, which is slow. if i add always inline attribute, the compiler will compain with an error.

**Comment by alexey-milovidov** [comment]
Ok, then your approach will suffice.
