### ISSUE TITLE
groupUniqArrayArrayMap for SimpleAggregateFunction

### ISSUE THREAD

**Issue by ltylty** [ClickHouse/ClickHouse#61078]
in this document.  groupUniqArrayArray suport SimpleAggregateFunction, maxMap suport SimpleAggregateFunction.
https://clickhouse.com/docs/en/sql-reference/data-types/simpleaggregatefunction

can groupUniqArrayArrayMap suport SimpleAggregateFunction ?

**Comment by ltylty** [comment]
SimpleAggregateFunction(groupUniqArrayArray , Array(Map(String, UInt32)))

perhaps this solved

**Comment by UnamedRus** [comment]
Duplicate
https://github.com/ClickHouse/ClickHouse/issues/15085
https://github.com/ClickHouse/ClickHouse/issues/41690
