### ISSUE TITLE
User with dot

### ISSUE THREAD

**Issue by kalagur** [ClickHouse/ClickHouse#6111]
I can't create user with dot in username.
users.xml:
<v.ivanov>
...
</v.ivanov>
It doesn't work.
How I can resolve this problem?

**Comment by alexey-milovidov** [comment]
It's not possible to have user names with dot characters for now.
But it isn't a fundamental issue, it can be fixed.

**Comment by blinkov** [comment]
@kalagur, do you have any further questions?

**Comment by alexey-milovidov** [comment]
This issue is fixed after introducing user control with SQL queries.
It is available since version 20.4-prestable in experimental stage.

Documentation is added here: https://github.com/ClickHouse/ClickHouse/pull/9983
