### ISSUE TITLE
Assertion \'max_log_ptr_at_creation || our_log_ptr\' in DatabaseReplicated::recoverLostReplica()

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickHouse#61134]
(you don't have to strictly follow this form)

**Describe the bug**
https://s3.amazonaws.com/clickhouse-test-reports/61052/e9b0852a974ef1defef4f502bed91828b6dffd32/stress_test__asan_.html

https://s3.amazonaws.com/clickhouse-test-reports/61052/e9b0852a974ef1defef4f502bed91828b6dffd32/stress_test__asan_/fatal_messages.txt

**Comment by kssenii** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/62715/8971509176241f5fe129426957f43485ef7e6d2e/stress_test__tsan_.html
