### ISSUE TITLE
Same sql, new version will report an error

### ISSUE THREAD

**Issue by xiaochaoren1** [ClickHouse/ClickHouse#61146]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**
![image](https://github.com/ClickHouse/ClickHouse/assets/42240939/537d07cb-4809-4a03-949d-3d7e1e96a2bc)
span_kind type is Nullable (UInt8)

![image](https://github.com/ClickHouse/ClickHouse/assets/42240939/692c83b5-d1fd-426b-a301-4186ac42905b)
When the version is 23.8.7, sql is normal and no error is reported

![image](https://github.com/ClickHouse/ClickHouse/assets/42240939/1c607396-6578-4928-8048-4ebac055e5fc)
When the version is 24.2.1, SQL reports an error
> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by alexey-milovidov** [comment]
Please provide the information.

**Comment by xiaochaoren1** [comment]
> Please provide the information.

Is the screenshot above not enough? What other information do you need?

**Comment by alexey-milovidov** [comment]
No screenshots plz.
