### ISSUE TITLE
Alternative to create schemas - Database Dessign

### ISSUE THREAD

**Issue by masosky** [ClickHouse/ClickHouse#6115]
Hi guys,

First of all, I really love your technology it is really fast and efficient.
I do have a design question. Currently, I am working with Postgres and for each client that I have, I create a new schema.
For instance imagine that I have two clients: c1 and c2
The schema for c1: table1, table2...
The schema for c2: table 1, table2...

Nowadays we are planning to migrate that to Clickhouse due to its performance and scalability.
I would like to know which could be the best approach when facing Clickhouse.

Create a database for each client? (Requires a new connection for client)
Create specific tables for each client? (Maybe it is a problem when creating a lot of tables)
More ideas?

Thanks a lot!!

**Comment by den-crane** [comment]
1. Do you need user access isolation? CH does not have table level grants only database level grants.
2. How many clients do you have?
3. Do you plan to use replicated tables (CH replicated engine has some resource overhead for each replicated table).

**Comment by masosky** [comment]
Hi,
1. we don't need it
2. Currently, less than 10 but it seems that it will increase rapidly.
3. Yes, we will implement it for clients who have massive data

**Comment by den-crane** [comment]
CH replicated tables have some CPU/Zookeeper overhead and recommended  to keep number of replicated tables less than 1000.

**Comment by blinkov** [comment]
@masosky, do you have any further questions?
