### ISSUE TITLE
timeZoneOffset doesn't appear to reflect daylight saving time

### ISSUE THREAD

**Issue by jakeknigge** [ClickHouse/ClickHouse#61175]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

We're using version `23.10.5.20`; however, this issue persists on `latest`, as shown in the reproducer environment.

**Describe what's wrong**

The `timeZoneOffset` function does not appear to adjust for daylight savings time, which is unexpected and runs contrary to the (function documentation)[https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#timezoneoffset], which states
>The function [daylight saving time](https://en.wikipedia.org/wiki/Daylight_saving_time) and historical timezone changes at the specified date and time into account.

**Does it reproduce on the most recent release?**

Yes, it does: https://fiddle.clickhouse.com/36f5e681-16e9-471e-a6ec-e3a841b82eec.

Here's the same result using `23.10.5.20`: https://fiddle.clickhouse.com/18b4587e-5c03-4838-a78c-22b43b848c10.

**How to reproduce**

* Queries to run that lead to an unexpected result

```
SELECT
    toTimeZone(toStartOfFifteenMinutes(now()), 'America/New_York') AS now_edt,
    toStartOfFifteenMinutes(now()) AS now_utc,
    toIntervalSecond(timeZoneOffset(toTime(toStartOfFifteenMinutes(now())), 'America/New_York')) AS delta

Query id: 8af415b6-abcf-454a-a895-350a8371a061

┌─────────────now_edt─┬─────────────now_utc─┬──delta─┐
│ 2024-03-11 13:45:00 │ 2024-03-11 17:45:00 │ -18000 │
└─────────────────────┴─────────────────────┴────────┘
```

**Expected behavior**

The difference between Eastern Daylight Time and Coordinated Universal Time should be four hours or `-14400` seconds, not `-18000` seconds (as shown in the snippet above).

**Comment by den-crane** [comment]
* toTimeZone does not change time value, time value is always the unix timespamp in UTC timezone.
* your delta calculates something weird.


you cannot calculate such delta without conversion into String:

https://fiddle.clickhouse.com/fed3b2c3-93f9-4c1d-8d3b-cf7852d92815

```sql
SELECT
    toString((now()), 'America/New_York') AS now_edt,
    toDateTime(now_edt) - now() delta
format Pretty
+---------------------+--------+
| now_edt             |  delta |
+---------------------+--------+
| 2024-03-11 14:14:10 | -14400 |
+---------------------+--------+
```

**Comment by jakeknigge** [comment]
thanks for the prompt response, @den-crane. it looks like the inner `toTime()` call is the source of the weird behavior.

**Comment by jakeknigge** [comment]
I'll close the issue.
