### ISSUE TITLE
After the start, the Clickhouse server uses memory in proportion to the amount of accumulated data on the disks. 

### ISSUE THREAD

**Issue by alexeyrusnak** [ClickHouse/ClickHouse#61212]
There are 2 groups of servers. Each server has 512 GB of RAM.
The first group of servers has accumulated 570 TB of data on each server.
The second server group has accumulated 390 TB of data on each server

After the start, the Clickhouse uses RAM:
The first group has 290 GB on each server.
The second group has 190 GB on each server.

The servers do not do anything. No reports are requested. No data is inserted.

I conclude that memory consumption is directly proportional to the amount of accumulated data on the disks. 

Is this a bug or a feature? Is this a problem in the settings?

What will happen when the amount of stored data doubles?

Our ClickHouse server version is 23.4.2 revision 54462

**Comment by alexey-milovidov** [comment]
Yes, memory consumption is expected to be proportional to the total data volume (although the ratio of this proportion is very small) because it is used for tables' sparse primary keys.

You can install the latest version 24.2, which introduced lazy primary keys loading: https://presentations.clickhouse.com/release_24.2/#17 Video: https://www.youtube.com/watch?v=iN2y-TK8f3A

**Comment by alexeyrusnak** [comment]
> Yes, memory consumption is expected to be proportional to the total data volume (although the ratio of this proportion is very small) because it is used for tables' sparse primary keys.
> 
> You can install the latest version 24.2, which introduced lazy primary keys loading: https://presentations.clickhouse.com/release_24.2/#17 Video: https://www.youtube.com/watch?v=iN2y-TK8f3A

Guys! It really works! 

We have updated all nodes to 24.2.2.71. Now after DB started we have 31G of memory usage (290G were before update).

Thank you!
