### ISSUE TITLE
query s3 with select and aws credentials

### ISSUE THREAD

**Issue by aser86** [ClickHouse/ClickHouse#61230]
**Describe the unexpected behaviour**

After I select an s3 bucket with usings the option access_key_id, secret_access_key, session_token I get an error message.

Select-Comand:
`
SELECT *
FROM s3(
	'https://123-bucketname-test.s3.eu-central-1.amazonaws.com/prefix/prefix/prefix/5014bb6a-263e-425c-98c0-97615db3fe3e.csv'
	, 'access_key_id'
	, 'secret_access_key'
	, 'session_token '
)
`

Error:
`
SQL-Fehler [499] [07000]: Code: 499. DB::Exception: The AWS Access Key Id you provided does not exist in our records.: while reading key: prefix/prefix/prefix/5014bb6a-263e-425c-98c0-97615db3fe3e.csv, from bucket: 123-bucketname-test: The data format cannot be detected by the contents of the files. You can specify the format manually: (S3_ERROR) (version 24.2.1.2248 (official build))
, server ClickHouseNode [uri=http://localhost:8123/default, options={use_server_time_zone=false,use_time_zone=false}]@-1974819624
`

If I use in the cmd the aws command it works:
aws s3 ls s3://123-bucketname-test.s3.eu-central-1.amazonaws.com/prefix/prefix/prefix/

**Additional context**
I use an aws role.
I use clickhouse in an docker container

**Comment by UnamedRus** [comment]
Second fix https://github.com/ClickHouse/ClickHouse/pull/61362

**Comment by iamKunalGupta** [comment]
Hi @UnamedRus when can we expect the changes to land on a stable version? I see a stable release was just made a few hours ago.

**Comment by alexey-milovidov** [comment]
@iamKunalGupta, 24.3 will be released on Mar 27, 2024.

**Comment by iamKunalGupta** [comment]
> @iamKunalGupta, 24.3 will be released on Mar 27, 2024.

Any chances it can be backported to older clickhouse versions which support session token,? Without this fix it makes the feature useless.

**Comment by alexey-milovidov** [comment]
This is a complex feature, we don't want to risk the stability of previous versions by backporting it.
