### ISSUE TITLE
replaceRegexpAll not support '\u'

### ISSUE THREAD

**Issue by shuai-xu** [ClickHouse/ClickHouse#61271]
**Describe what's wrong**

> when run `SELECT replaceRegexpAll('abc', '[^0-9a-zA-Z\\u4e00-\\u9fa5]',' ');`, it throws exception:
<img width="1433" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/20960838/136b7a75-890a-4910-a638-d946ecd4f5b3">

**Does it reproduce on the most recent release?**

Yes

**Comment by alexey-milovidov** [comment]
There is no such feature. Neither re2 nor ClickHouse supports this escape sequence.

**Comment by shuai-xu** [comment]
> There is no such feature. Neither re2 nor ClickHouse supports this escape sequence.

Clickhouse 21.10 seems to support it.
