### ISSUE TITLE
Is there a possibility of conflict in `hash128`?

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#61273]
In `HashJoin::chooseMethod`, when there are multiple join keys and there is at least one key which is not fixed. method `hashed` is choosen. The corresponding hash method is `ColumnsHashing::HashMethodHashed`.
```c++
template <typename Value, typename Mapped> struct KeyGetterForTypeImpl<HashJoin::Type::hashed, Value, Mapped>
{
    using Type = ColumnsHashing::HashMethodHashed<Value, Mapped, false, use_offset>;
};
```

And `ColumnsHashing::HashMethodHashed` will transform the keys into a `UInt128` and it's token as the key of `HashTable`.
```c++
/// Hash a set of keys into a UInt128 value.
static inline UInt128 ALWAYS_INLINE hash128( /// NOLINT
    size_t i, size_t keys_size, const ColumnRawPtrs & key_columns)
{
    SipHash hash;
    for (size_t j = 0; j < keys_size; ++j)
        key_columns[j]->updateHashWithValue(i, hash);

    return hash.get128();
}
```

So my question is, Is there a possibility of conflict in `hash128`?

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/9506#issuecomment-594583621

**Comment by lgbo-ustc** [comment]
By the way, why is `HashMethodSerialized` used in aggregation instead of `HashMethodHashed ` ? It seems `HashMethodHashed`  is faster then `HashMethodSerialized`.

**Comment by alexey-milovidov** [comment]
The serialized method is typically faster than hashed, but not always. It is not faster if strings have a long common prefix or if the strings are mostly long.
