### ISSUE TITLE
Release tarball build

### ISSUE THREAD

**Issue by knusbaum** [ClickHouse/ClickHouse#6128]
Building from the release tarballs (https://github.com/yandex/ClickHouse/releases) is difficult.
The build with cmake does not work out of the box because of missing dependencies, and since the git history is not included in the archive, `git submodule update --init --recursive` does not work.

I am able to mostly work around this by installing various libs through the system package manager, but certain submodules, for example [contrib/ssl](https://github.com/ClickHouse-Extras/ssl), aren't as simple to get, and there aren't clear version requirements.

Is there a better way to build a specific release of ClickHouse?

**Comment by millin** [comment]
Why you need to build it?
All testing releases are available https://repo.yandex.ru/clickhouse/deb/testing/main/

**Comment by alexey-milovidov** [comment]
Better to do full recursive checkout from GitHub, then pack everything in tarball. Then you can build ClickHouse from this tarball.

> I am able to mostly work around this by installing various libs through the system package manager

Don't do it. With libraries from OS packages ClickHouse will work in a slightly different, possibly wrong way. This is intended only as a "demo" version for official Debian/Ubuntu repo.

**Comment by knusbaum** [comment]
@millin I want to build for a linux other than debian. It's helpful to have a tarball for a release with a full set of sources, to create reproducible builds. 

https://repo.yandex.ru/clickhouse/deb/testing/main/ looks like it had something similar to what I want, except there aren't any tarballs beyond 18.6.0.

**Comment by alexey-milovidov** [comment]
@den-crane We have tarball releases but they don't contain installation script.
Will reopen.

**Comment by alesapin** [comment]
https://github.com/ClickHouse/ClickHouse/pull/8591

**Comment by qoega** [comment]
Is everything done in this issue?

**Comment by alexey-milovidov** [comment]
Yes.
