### ISSUE TITLE
group by count with null values in the grouping key returns hard to understand result

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/ClickHouse#61313]
**Describe the unexpected behaviour**

I'm having trouble understanding how nulls are handled when used as grouping keys. I can't tell if there's something I'm missing here, or if this is a bug in ClickHouse.

**How to reproduce**

ClickHouse server version:

```
bce519d15486 :) select version();

SELECT version()

Query id: ef482266-bbdb-4b62-ad14-3838c14c66cb

┌─version()──┐
│ 23.12.4.15 │
└────────────┘

1 row in set. Elapsed: 0.001 sec.
```

Example:

```
bce519d15486 :) CREATE OR REPLACE TABLE ibis_testing.topk (x Nullable(Int64)) ENGINE = Memory;

CREATE OR REPLACE TABLE ibis_testing.topk
(
    `x` Nullable(Int64)
)
ENGINE = Memory

Query id: 76f08dbb-380e-4336-b156-f71b992ca09e

Ok.

0 rows in set. Elapsed: 0.006 sec.

bce519d15486 :) INSERT INTO ibis_testing.topk VALUES (1), (1), (NULL);

INSERT INTO ibis_testing.topk FORMAT Values

Query id: fec175db-566c-4019-8752-b36dcfc95f2c

Ok.

3 rows in set. Elapsed: 0.002 sec.

bce519d15486 :) select x, count(*), count(1), count(), countIf(x is null) from topk group by x;

SELECT
    x,
    count(*),
    count(1),
    count(),
    countIf(x IS NULL)
FROM topk
GROUP BY x

Query id: df3b4079-c6df-455f-ad2b-259612b42df6

┌────x─┬─count()─┬─count()─┬─count()─┬─countIf(isNull(x))─┐
│ ᴺᵁᴸᴸ │       0 │       0 │       0 │                  0 │
│    1 │       3 │       3 │       3 │                  1 │
└──────┴─────────┴─────────┴─────────┴────────────────────┘

2 rows in set. Elapsed: 0.002 sec.
```

**Expected behavior**

I would expect the `count()` aggregations to return 1 for `NULL` and `2` for `1`, and the `countIf` aggregation to return `1` for `NULL` and `0` for `1`.

**Comment by Algunenano** [comment]
https://clickhouse.com/docs/en/sql-reference/aggregate-functions#null-processing

```
During aggregation, all NULLs are skipped. If the aggregation has several parameters it will ignore any row in which one or more of the parameters are NULL.
```

It's by design.

**Comment by cpcloud** [comment]
Regardless of null skipping it seems incorrect to state that there three rows with the value `1` when that's simply not true.

I'm not sure I understand what specifically in these results indicate that null skipping is by design, but maybe it's just me.

**Comment by cpcloud** [comment]
> it will ignore any row in which one or more of the parameters are NULL.

E.g., if this is true, then I would expect `null` to aggregate to 0 and `1` to aggregate to 2.

**Comment by Algunenano** [comment]
> E.g., if this is true, then I would expect null to aggregate to 0 and 1 to aggregate to 2 when using count.

Yes, the documentation is lacking. There are some special cases, like `ANY RESPECT NULLS` where NULLs are used. But the default case is that any NULL argument is ignored.

In CH, count(), count(1), count(*) are all equivalent and return the count of all rows (doesn't check whether they are NULL or not). count(column) will only count where the column is not NULL since the NULLs will be ignored.

HTH

**Comment by den-crane** [comment]
WOW

>During aggregation, all NULLs are skipped. If the aggregation has several parameters it will ignore any row in which one or more of the parameters are NULL.


@Algunenano this is about an aggregate function not about group by key.

PSQL:

```
CREATE  TABLE topk(x int);
INSERT INTO topk VALUES (1), (1), (NULL);



SELECT
   x,
   count(*),
   count(1),
   count(*) filter (where x IS NULL)
FROM topk
GROUP BY x

 x | count | count | count
---+-------+-------+-------
   |     1 |     1 |     1
 1 |     2 |     2 |     0
```

CH 22.8  https://fiddle.clickhouse.com/b1cee4e5-b254-4da2-bc31-51d8c3d3e698

```
+------+---------+---------+-----------------------+
|    x | count() | count() | countIf(x, isNull(x)) |
+------+---------+---------+-----------------------+
|    1 |       2 |       2 |                     0 |
+------+---------+---------+-----------------------+
| NULL |       1 |       1 |                     0 |
+------+---------+---------+-----------------------+
```

CH 23.8 https://fiddle.clickhouse.com/f08342c7-40b8-4bba-899c-cf0425bacb16

```
+------+---------+---------+-----------------------+
|    x | count() | count() | countIf(x, isNull(x)) |
+------+---------+---------+-----------------------+
| NULL |       1 |       1 |                     0 |
+------+---------+---------+-----------------------+
|    1 |       2 |       2 |                     0 |
+------+---------+---------+-----------------------+
```

CH 24.2 https://fiddle.clickhouse.com/4fa0e06f-2be9-48a4-9dea-2252488f0dfd

```
+------+---------+---------+-----------------------+
|    x | count() | count() | countIf(x, isNull(x)) |
+------+---------+---------+-----------------------+
| NULL |       0 |       0 |                     0 |
+------+---------+---------+-----------------------+
|    1 |       3 |       3 |                     0 |
+------+---------+---------+-----------------------+
```

**Comment by cpcloud** [comment]
@den-crane Thanks for figuring that out! I suppose we'll just pin that version of clickhouse for now in our CI.

**Comment by Algunenano** [comment]
Seems it was broken in https://github.com/ClickHouse/ClickHouse/pull/57872 as removing the call to `addBatchSinglePlace` fixes it. cc @CurtizJ

**Comment by Algunenano** [comment]
It seems this is related to an optimization to use a faster aggregation method when we find only one key in the block, as we are ignoring NULLs. It does not happen if the block has more than 1 non NULL value.
