### ISSUE TITLE
MaxIf() does not return nulls like Avg(), AvgIf() and max()

### ISSUE THREAD

**Issue by CAspeling** [ClickHouse/ClickHouse#6134]
Here is a comparison:

**Current:**
avg(null) = null or "empty string" as it is called in the documentation
avgIf(null, id == 1) = null or "empty string"

max(null) = null or "empty string"
maxIf(null, id == 1) = 0

**Expected:**
maxIf(null, id == 1) = null or "empty string"

---
![image](https://user-images.githubusercontent.com/44218267/61770265-f864b400-ae40-11e9-8cc8-1c73a4ba9e31.png)

---

We believe the bug lies with maxIf(), it should not return default 0, it should return default "empty string" so that it works consistently like avg(), avgIf(), and max().

Here is an example straight from our database for your perusal. At any point in time, we will query on a time frame, where a result for a specific ID may or may not occur. maxIf() is not behaving correctly when no result comes back, while avgIf() returns null/ nothing, not even NAN.

I have tried copying the empty value out to see what it contains, whether it is infact a nan or null or something, but it's just empty, which on our end comes through as a null. This is perfect for avg because we can carry previous values forward if they did not report a state/value change in the db. Max however, is broken because it does not.

``` sql
select
  SiteId,Value,Time,
  avgIf(Value, SiteId == 562) as average,
  maxIf(Value, SiteId == 562) as maximum
from
  temp.temptable
where
  Time > '2019-05-25 16:00:00' and Time < '2019-05-31 20:11:46'
group by
  SiteId, Value, Time
limit 10
```
Results:
```
┌─SiteId─┬─Value─┬─Time────────────────┬─average─┬─maximum─┐
|    618 |  1000 | 2019-05-26 18:32:42 |         |       0 |
|    620 |     1 | 2019-05-29 15:09:56 |         |       0 |
|    562 |     9 | 2019-05-26 08:53:24 |       9 |       9 |
|    566 |     4 | 2019-05-30 19:27:59 |         |       0 |
|    585 |   8.2 | 2019-05-29 07:40:48 |         |       0 |
|    598 |    52 | 2019-05-28 11:01:25 |         |       0 |
|   1410 |  12.4 | 2019-05-26 16:03:09 |         |       0 |
|   1507 |     2 | 2019-05-26 10:29:08 |         |       0 |
|    619 |  1000 | 2019-05-29 09:58:02 |         |       0 |
|    617 |   111 | 2019-05-27 16:33:52 |         |       0 |
└────────┴───────┴─────────────────────┴─────────┴─────────┘
```

**Comment by akuzm** [comment]
What version do you use?
On 19.11, I get maxIf(null, 1) = null, as expected.

```
:) select maxIf(null, 1);
┌─maxIf(NULL, 1)─┐
│ ᴺᵁᴸᴸ           │
└────────────────┘ 
```

**Comment by akuzm** [comment]
```
:) select maxIf(null, 0);

┌─maxIf(NULL, 0)─┐
│ ᴺᵁᴸᴸ           │
└────────────────┘
```

On the other hand, this looks incorrect, because the condition is False, so maxIf shouldn't see the Null and should return a default value.

**Comment by CAspeling** [comment]
ClickHouse 19.5.3.8

**Comment by CAspeling** [comment]
Here is a tester query you can use:

```
select 
    id, maxIf(value, id == 1) as max
from (
select
  number as id,
  number * 2 as value
from
  numbers(5)
) group by id
```

**Comment by alexey-milovidov** [comment]
Follow-up: https://github.com/ClickHouse/ClickHouse/issues/10273

**Comment by alexey-milovidov** [comment]
@CAspeling `maxIf` on empty matching rows returns:
- NULL if the data type of the argument is Nullable;
- 0 if the data type is numeric;
- empty string if the data type is String.

The functions `sum` and `avg` cannot work on String types and cannot return empty strings.
The function `avg` returns nan on empty set if the argument is not Nullable and NULL if the argument is Nullable.
The function `sum` returns zero on empty set if the argument is not Nullable and NULL if the argument.

You can also use `-OrNull` modifier to get Nullable results for any data type.

The behaviour is 100% consistent.
