### ISSUE TITLE
memory leakage debugging

### ISSUE THREAD

**Issue by captainswingad2112** [ClickHouse/ClickHouse#61355]
version -> 23.11.1.2711
64 gb 16 core machine
<img width="1487" alt="Screenshot 2024-03-14 at 1 36 05 PM" src="https://github.com/ClickHouse/ClickHouse/assets/159880985/5d9d1238-65a9-406e-b42f-7b6eedd86fbf">

I have been observing constant increase in memory usage indicating some leakages

this is the part info -----
<img width="1492" alt="Screenshot 2024-03-14 at 1 34 36 PM" src="https://github.com/ClickHouse/ClickHouse/assets/159880985/d71a6c52-dbce-426c-b36a-bd2ff167b334">

MemoryResident hovers around ~20 - 30 gb

we don't have any in memory data structures like dictionary.(only disk based tables)

data is mainly inserted using kafka engine.

I was also not able to find any issue through trace logs.

We maintain an entry-data node cluster so queries are not creating this issue.

**Can someone help in how to dig deeper in this ?** 

this are the jemalloc metric
<img width="736" alt="Screenshot 2024-03-14 at 1 44 28 PM" src="https://github.com/ClickHouse/ClickHouse/assets/159880985/73412155-c8af-4833-8a51-165a6b0403b8">

**Comment by Algunenano** [comment]
Might be related to the problem fixed in https://github.com/ClickHouse/ClickHouse/pull/58831 and https://github.com/ClickHouse/ClickHouse/pull/59273. Please update to 24.1+ and verify

**Comment by captainswingad2112** [comment]
It's been resolved after upgrade.
