### ISSUE TITLE
Create User with Clickhouse Mode Replicate but not SYNC

### ISSUE THREAD

**Issue by quoctuan2311** [ClickHouse/ClickHouse#61350]
I have setup my-self Clickhouse Server with mode Replicate. 

This server have:

- Two node clickhouse
- A load balance router to 2 node clickhouse with mode round robin.

But when create/grand_permission user with load balance, it only create user to a node. At different node not yet this user.
Have solution to sync data for user between 2 node? Or create/grand_permission user on 2 node?

**Comment by UnamedRus** [comment]
> Have solution to sync data for user between 2 node? Or create/grand_permission user on 2 node?

https://github.com/ClickHouse/ClickHouse/pull/27426

**Comment by quoctuan2311** [comment]
> > Have solution to sync data for user between 2 node? Or create/grand_permission user on 2 node?
> 
> #27426

It work, thanks for solution
