### ISSUE TITLE
Test other itoa's implementations

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#61407]
After looking into itoa for large ints in https://github.com/ClickHouse/ClickHouse/pull/61100 (which I think has room for further improvements) I realized that our current implementation for native integers, while fast, might not be necessarily be the fastest. We should have the fastest :D

A quick look around Github shows that there seems to be better implementations out there. For example https://github.com/jeaiii/itoa appears to be 10-15% faster printing UInt64 in my tests than the one we are currently using (https://github.com/amdn/itoa).

**Comment by yakov-olkhovskiy** [comment]
maybe it makes sense to test all of them separately in dedicated test rather than in-situ - it will make cleaner evaluation?

**Comment by alexey-milovidov** [comment]
Make sure to use only real datasets for performance testing.

Most library writers tend not to go further than testing on random numbers, that's why we have to use, e.g. patched version of Dragonbox for parsing instead of the original.
