### ISSUE TITLE
Is there any better way to migrate table data to the same local database?

### ISSUE THREAD

**Issue by prospelynn** [ClickHouse/ClickHouse#61417]
I have two tables(200+ columns) with the same structure, the only difference is that the primary key(order by) are inconsistent.
now,I want to migrate the data of the old table to a table with a new primary key.
I have tried 3 ways.
1. Using clickhouse_copier.
2. Exporting csv and then using clickhouse-client to import the file.
3. Using insert into xx select xx from table.
However, I feel that their efficiency is very low and they cannot copy a large amount of data in a short time,and When I use clickhouse_copier I set max_workers to 30 but it doesn't seem to take effect.
![image](https://github.com/ClickHouse/ClickHouse/assets/57206362/56085692-d94d-44f8-bade-5aab0201a2ff)

Are there any other ways to achieve this?
Thanks

**Comment by davenger** [comment]
Are these tables distributed? It yes, you should try INSERT-SELECT with `parallel_distributed_insert_select` setting enabled https://clickhouse.com/docs/en/operations/settings/settings#parallel_distributed_insert_select

**Comment by prospelynn** [comment]
> Are these tables distributed? It yes, you should try INSERT-SELECT with `parallel_distributed_insert_select` setting enabled https://clickhouse.com/docs/en/operations/settings/settings#parallel_distributed_insert_select

No, it's a standalone device

**Comment by davenger** [comment]
How many cores do you have and what is the approximate data size in the table? Did you try setting `max_insert_threads` and `max_threads` to the number of available cores when doing INSERT-SELECT?

**Comment by prospelynn** [comment]
> How many cores do you have and what is the approximate data size in the table? Did you try setting `max_insert_threads` and `max_threads` to the number of available cores when doing INSERT-SELECT?

48 cores and clickhouse runs on docker and is limited to about 30 cores and 180G mem，so I set both max_insert_threads and max_threads to 30 cores.
The original table has a total of 800 million data, and the data size before uncompression is about 7T.
i tried this bash `seq 1 $page | xargs -P 30 -I {} bash -c 'execute_task {}'` to execute task and INSERT-SELECT 50000 items each time,but the mem usage rate is not high, the average is only 7G.
Only about 17 million can be processed in 20 minutes

**Comment by Algunenano** [comment]
Use INSERT-SELECT. Probably you should do it by part, not with LIMIT.

Changing primary key means resorting everything, so as @davenger mentioned, check `max_threads` and `max_insert_threads`.
