### ISSUE TITLE
why toDecimal64(324.46, 2)  is  324.45?

### ISSUE THREAD

**Issue by glenmock** [ClickHouse/ClickHouse#61427]
version:  23.8.2.7
 SQL:   SELECT toDecimal64(424.46, 2), toDecimal64(124.46, 2),toDecimal64(324.46, 2); 
result:  
![mmexport1710491162589](https://github.com/ClickHouse/ClickHouse/assets/138589524/99caa370-5ed2-4384-83df-ec30c20f2e3a)

**Comment by genzgd** [comment]
A number with a decimal point is first interpreted by ClickHouse as an IEE-754 Float64 value.  324.46 can't be exactly represented as a 64 bit float, so the conversion from the Float64 to Decimal truncates down to 324.45.  To see this in another context:

```
SELECT toInt64(324.46 * 100000)

┌─toInt64(multiply(324.46, 100000))─┐
│                          32445999 │
└───────────────────────────────────┘
```

To avoid the intermediate, implicit cast to a Float64, you tell ClickHouse to interpret the string as a Decimal first before passing it to any other functions:

```
SELECT 324.46::Decimal(64,2) as dec, toTypeName(dec);

SELECT
    CAST('324.46', 'Decimal(64, 2)') AS dec,
    toTypeName(dec)

┌────dec─┬─toTypeName(CAST('324.46', 'Decimal(64, 2)'))─┐
│ 324.46 │ Decimal(64, 2)                               │
└────────┴──────────────────────────────────────────────┘
```

or just pass the string directly to the toDecimal64 function:

```
SELECT toDecimal64('324.46', 2)

┌─toDecimal64('324.46', 2)─┐
│                   324.46 │
└──────────────────────────┘
```
