### ISSUE TITLE
Flaky 00857_global_joinsavel_table_alias

### ISSUE THREAD

**Issue by novikd** [ClickHouse/ClickHouse#61432]
https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBNT05USAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzIExJS0UgJ0YlJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBwb3NpdGlvbih0ZXN0X25hbWUsICcwMDg1N19nbG9iYWxfam9pbnNhdmVsX3RhYmxlX2FsaWFzJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=

**Comment by vdimir** [comment]
https://github.com/ClickHouse/ClickHouse/pull/61047/files#r1665833817
