### ISSUE TITLE
Memory leak regression between versions 23.11.1.2711 и 24.1.6.52

### ISSUE THREAD

**Issue by ivan-tkatchev** [ClickHouse/ClickHouse#61496]
Upgrading from version 23.11.1.2711 to 24.1.6.52 results in memory leaks and OOM killers on our production servers.

Is this a known issue?

Sadly, I can provide few additional details. The leaking memory is not registered in any metrics (https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-who-ate-my-memory/).

A trace of page faults shows that faults come from generic `ThreadPool` threads, from `DB::IColumn::getName` calls. Can this be caused by the asynchronous insert functionality?

**Comment by ivan-tkatchev** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/650601/4ae6cf38-6e1f-4a62-a47c-47659012fe36)

**Comment by alexey-milovidov** [comment]
Do you use Kafka? We have one instance of known memory leak related to Apache rdkafka library.

**Comment by ivan-tkatchev** [comment]
> Do you use Kafka? We have one instance of known memory leak related to Apache rdkafka library.

No, no Kafka. Only TSV-formatted inserts, in regular synchronous manner and async mode.

**Comment by alexey-milovidov** [comment]
Not enough info.
