### ISSUE TITLE
`INSERT INTO FUNCTION s3(...)` overwrites existing objects regardless of configuration when using `PARTITION BY`

### ISSUE THREAD

**Issue by Beetelbrox** [ClickHouse/ClickHouse#61492]
## Description

`INSERT INTO FUNCTION s3(...) PARTITION BY` queries replace any existing objects regardless of the value of `s3_truncate_on_insert`. This is inconsistent with both the documentation and the behaviour when `PARTITION BY` is not used, which throws an exception if an object already exists in the write destination path.

**How to reproduce**
Truncate on insert is disabled on the cluster:
```
SELECT * FROM system.settings WHERE name = 's3_truncate_on_insert'

Query id: c58a7291-14b2-4587-9b8d-4b7d1e07b1dc

┌─name──────────────────┬─value─┬─changed─┬─description─────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type─┬─default─┬─alias_for─┬─is_obsolete─┐
│ s3_truncate_on_insert │ 0     │       0 │ Enables or disables truncate before insert in s3 engine tables. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ Bool │ 0       │           │           0 │
└───────────────────────┴───────┴─────────┴─────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴──────┴─────────┴───────────┴─────────────┘
```

Write an object to S3:
```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/1/data.csv', 'admin', 'password') SELECT * FROM generateRandom('dt Datetime') LIMIT 1000
```

Overwrite it using PARTITION BY:
```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/{_partition_id}/data.csv', 'admin', 'password') PARTITION BY 1 SELECT * FROM numbers(1000)

Query id: 8f61c70b-cb14-48fc-bb96-6c0410531ce1

Ok.
```

`blob_storage_log` shows that the file was successfully uploaded:
```
SELECT * FROM system.blob_storage_log WHERE query_id = '8f61c70b-cb14-48fc-bb96-6c0410531ce1' FORMAT Vertical

Row 1:
──────
event_date:              2024-03-16
event_time:              2024-03-16 15:56:18
event_time_microseconds: 2024-03-16 15:56:18.632598
event_type:              Upload
query_id:                8f61c70b-cb14-48fc-bb96-6c0410531ce1
thread_id:               5192
thread_name:             S3ParallelWrite
disk_name:
bucket:                  my-bucket
remote_path:             partition-overwrite/1/data.csv
local_path:
data_size:               3890
error:

1 row in set. Elapsed: 0.031 sec. Processed 614.35 thousand rows, 18.28 MB (19.55 million rows/s., 581.80 MB/s.)
Peak memory usage: 11.65 MiB.
```
And the file exists in minio with the new size and the new timestamp:
<img width="1187" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/9376816/e6d6539e-af4d-497f-8771-88c9feb50eaf">

If we try to overwrite the file without the `PARTITION BY` it fails:
```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/1/data.csv', 'admin', 'password') SELECT *
FROM numbers(20)

Received exception from server (version 24.1.7):
Code: 36. DB::Exception: Received from localhost:9000. DB::Exception: Object in bucket my-bucket with key partition-overwrite/1/data.csv already exists. If you want to overwrite it, enable setting s3_truncate_on_insert, if you want to create a new file on each insert, enable setting s3_create_new_file_on_insert. (BAD_ARGUMENTS)
```

It also happens when inserting from a table and calculating partition basing on one of the table's fields

**Does it reproduce on the most recent release?**
Yes, tested in 24.2.2.71 and 4.1.7

**Expected behavior**

When `s3_truncate_on_insert` is disabled `INSERT INTO FUNCTION s3(...) PARTITION BY` queries fail if any existing object would be overwritten, as it happen when `PARTITION BY` is not used.

**Error message and/or stacktrace**

N/A

**Additional context**

N/A

**Comment by alexey-milovidov** [comment]
@excitoon PTAL ^

**Comment by Beetelbrox** [comment]
I reckon I have the issue located, if you validate this is undesired behaviour/a bug I can open a PR with a fix candidate

**Comment by alexey-milovidov** [comment]
@Beetelbrox, thank you! Yes, the behavior should be the same as for INSERT without PARTITION BY.
