### ISSUE TITLE
Inconsistent error message on `INSERT INTO s3(...)` queries with globs between using `PARTITION BY` and not using it

### ISSUE THREAD

**Issue by Beetelbrox** [ClickHouse/ClickHouse#61493]
**Describe what's wrong**

A `CANNOT_PARSE_TEXT` is raised when running an `INSERT INTO s3(...) PARTITION BY` query and using a glob in the write path. When `PARTITION BY` is not used we get an appropriate error explaining that globs are read only and not allowed in `INSERT INTO` queries.

**Does it reproduce on the most recent release?**

Yes

```
SELECT version()

Query id: 161ff215-f7c2-4306-a5e0-51a62164901e

┌─version()─┐
│ 24.2.2.71 │
└───────────┘
```

**How to reproduce**

```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/*/{_partition_id}/data.csv', 'admin', 'password') PARTITION BY 1 SELECT *
FROM generateRandom('uuid UUID, context Text, dt Datetime')

Query id: 806ab490-f4ec-4c7f-99a9-2dc92c8d8475


0 rows in set. Elapsed: 0.178 sec.

Received exception from server (version 24.2.2):
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Illegal character '\x2a' in partition id starting with 'partition-overwrite/'. (CANNOT_PARSE_TEXT)
```

If we don't use `PARTITION BY` we get a more explanatory error:
```
INSERT INTO FUNCTION s3('http://minio:6000/my-bucket/partition-overwrite/*/data.csv', 'admin', 'password') SELECT *
FROM generateRandom('uuid UUID, context Text, dt Datetime')

Query id: 6832863c-4061-4ff7-8f26-fb1ca14967a1


0 rows in set. Elapsed: 0.086 sec.

Received exception from server (version 24.2.2):
Code: 291. DB::Exception: Received from localhost:9000. DB::Exception: S3 key 'partition-overwrite/*/data.csv' contains globs, so the table is in readonly mode. (DATABASE_ACCESS_DENIED)
```

**Expected behavior**

A `DATABASE_ACCESS_DENIED` error with the proper explanation of globs being only allowed on read-only tables is thrown when using globs in `PARTITION BY` tables.

**Error message and/or stacktrace**

```
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c332a08
1. DB::Exception::Exception<unsigned int&, String>(int, FormatStringHelperImpl<std::type_identity<unsigned int&>::type, std::type_identity<String>::type>, unsigned int&, String&&) @ 0x0000000010da4f98
2. DB::PartitionedSink::validatePartitionKey(String const&, bool) @ 0x0000000010da4ec4
3. DB::PartitionedStorageS3Sink::createSinkForPartition(String const&) @ 0x000000001101ec08
4. DB::PartitionedSink::consume(DB::Chunk) @ 0x0000000010da439c
5. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x0000000011b490ec
6. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x0000000011a96c4c
7. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000011a96944
8. DB::ExceptionKeepingTransform::work() @ 0x0000000011a960a8
9. DB::ExecutionThreadContext::executeTask() @ 0x00000000118660ec
10. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001185e234
11. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x000000001185d808
12. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::CompletedPipelineExecutor::execute()::$_0>(DB::CompletedPipelineExecutor::execute()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000001185c824
13. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c3c5d88
14. start_thread @ 0x0000000000007624
15. ? @ 0x00000000000d162c
```

**Additional context**

I reckon [this validation](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageS3.cpp#L1273-L1275) should be moved to before the check for partitioned sink

**Comment by Beetelbrox** [comment]
I've been checking out the code and it the error is thrown [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/StorageS3.cpp#L988) while creating the `StorageS3Sink` for each one of the partitions key values. If the path contains `*` or `?` characters outside the wildcard this is wasteful as we already know that the path will be invalid before creating the `PartitionedStorageS3Sink` in the first place so we could fail early and not compute the partition key values.

I'm working on an MR with a change proposal to address this.

**Comment by Avogar** [comment]
> 'm working on an MR with a change proposal to address this

@Beetelbrox are you still working on it?
I can create a fix for it quickly, so, if you don't have time, no problem

**Comment by Beetelbrox** [comment]
> > 'm working on an MR with a change proposal to address this
> 
> @Beetelbrox I see you didn't created a MR, so I will do it. Thank you for the report

Hallo @Avogar! I started working on it but then I found out #61492 and started working on that one as they were acting on the same part of the code.

Thanks for the fix!
