### ISSUE TITLE
Import Data. got issue: cannot allocate number in zookeeper: coordination:: Exception: connection loss

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#61512]
Import 200 tables data, got the following issues:

error can't attached partitions for table 'dwd_mkt_bond': code: 999, message: cannot allocate block number in zookeeper: Coordination: Exception: Connection loss

Just import this table without others, success. What the reason for this issue? how to fix?

ClickHouse： 22.3.6.5
Use ClickHouse-Keeper

**Comment by Algunenano** [comment]
> What the reason for this issue?

The reason is a connection loss with keeper. There might be more information in logs before this error was thrown.

> how to fix?

Depends on the reason, but start by updating to a supported CH release. Recent versions have keeper retries that would help.
