### ISSUE TITLE
toString(decimal) Inconsistent results between high and low version kernels

### ISSUE THREAD

**Issue by Lambert-zw** [ClickHouse/ClickHouse#61514]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**
CREATE TABLE IF NOT EXISTS decimal
(
    id Int64,
    c1 UInt64,
    c2 Decimal128(18),
    c3 Decimal128(18)
) Engine = MergeTree() order by id;

INSERT INTO decimal VALUES (1, 1,1,1), (2, 1,1,2), (3, 1,1,3), (4, 1,1,4);

select toString(c2) from decimal;

ClickHouse server version 21.3.12 revision 54447 

SELECT toString(c2)
FROM decimal

Query id: 4d5e423c-0757-4724-8a6a-70286d66e5ad

┌─toString(c2)─────────┐
│ 1.000000000000000000 │
│ 1.000000000000000000 │
│ 1.000000000000000000 │
│ 1.000000000000000000 │
└──────────────────────┘

4 rows in set. Elapsed: 0.018 sec.

ClickHouse server version 23.8.2 revision 54465

SELECT toString(c2)
FROM decimal

Query id: 4966f9c2-2079-4ed3-b17c-d0870b21bf8d

┌─toString(c2)─┐
│ 1            │
│ 1            │
│ 1            │
│ 1            │
└──────────────┘

4 rows in set. Elapsed: 0.013 sec.

23.8.2 The result accuracy is incorrect after the toString function is executed.

**Expected behavior**
SELECT toString(c2)
FROM decimal

Query id: 4d5e423c-0757-4724-8a6a-70286d66e5ad

┌─toString(c2)─────────┐
│ 1.000000000000000000 │
│ 1.000000000000000000 │
│ 1.000000000000000000 │
│ 1.000000000000000000 │
└──────────────────────┘

4 rows in set. Elapsed: 0.018 sec.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#todecimalstring


--output_format_decimal_trailing_zeros arg                                           Output trailing zeros when printing Decimal values. E.g. 1.230000 instead of 1.23.


* https://github.com/ClickHouse/ClickHouse/pull/27680
* https://github.com/ClickHouse/ClickHouse/issues/30934
