### ISSUE TITLE
can`t build clickhouse with gcc-12

### ISSUE THREAD

**Issue by RaoZhiRou-Z** [ClickHouse/ClickHouse#61516]
compiler command: 
      cmake -DCMAKE_C_COMPILER=/opt/compiler/gcc-12/bin/gcc -DCMAKE_CXX_COMPILER=/opt/compiler/gcc-12/bin/g++ .......
errors:
      CMake Error at cmake/tools.cmake:8 (message):
      Compiler GNU is not supported
      Call Stack (most recent call first):
      CMakeLists.txt:18 (include)

**Comment by Tiaonmmn** [comment]
Please check the [doc](https://clickhouse.com/docs/en/development/build),ClickHouse doesn't support gcc.

**Comment by Algunenano** [comment]
Only clang is supported (and it must be a recent release too)

**Comment by RaoZhiRou-Z** [comment]
> Please check the [doc](https://clickhouse.com/docs/en/development/build),ClickHouse doesn't support gcc.

got it

**Comment by RaoZhiRou-Z** [comment]
> Only clang is supported (and it must be a recent release too)

got it
