### ISSUE TITLE
Add `fromReadableSize` function

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#61548]
**Use case**

Inverse `formatReadableSize` to simpler input large sizes.

**Describe the solution you'd like**

For integer numbers and unit name convert it to corresponding number. 

```
SELECT fromReadableSize('10MB')
10000000
SELECT fromReadableSize('10mb')
10000000
SELECT fromReadableSize('10MiB')
1048576
```

**Comment by mistryiam** [comment]
hello can i work on this issue?

**Comment by h12567** [comment]
@rschu1ze May I check if I can still work on this function?

**Comment by rschu1ze** [comment]
@h12567 Appreciated, please go ahead.

**Comment by Beetelbrox** [comment]
Hallo! I have a proposal PR for this issue [here](https://github.com/ClickHouse/ClickHouse/pull/64386), I saw that no other PR had been produced in a month so I gave it a shot.

If any of the assigned folks has a proposal in the works I'm fine with discarding mine in favour of theirs.
Thanks!
