### ISSUE TITLE
error: undefined symbol: DB::createFunctionBaseCast

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#61558]
> Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.com/docs/en/development/build/

**Operating system**

> OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**Cmake version**

**Ninja version**

**Compiler name and version**

**Full cmake and/or ninja output**

links:
https://s3.amazonaws.com/clickhouse-test-reports/61211/43eea86ec507e1da7c3b42d8e2bb177150873a89/clickhouse_special_build_check/report.html

https://s3.amazonaws.com/clickhouse-builds/PRs/61211/43eea86ec507e1da7c3b42d8e2bb177150873a89/binary_tidy/build_log.log

error
```
Mar 18 13:28:44 ld.lld-17: error: undefined symbol: DB::createFunctionBaseCast(std::__1::shared_ptr<DB::Context const>, char const*, std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::optional<DB::CastDiagnostic>, DB::CastType)
Mar 18 13:28:44 >>> referenced by CastOverloadResolver.cpp:84 (/build/src/Functions/CastOverloadResolver.cpp:84)
Mar 18 13:28:44 >>>               CastOverloadResolver.cpp.o:(DB::CastOverloadResolverImpl::buildImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&) const) in archive src/libdbmsd.a
Mar 18 13:28:44 clang++-17: error: linker command failed with exit code 1 (use -v to see invocation)
Mar 18 13:28:44 [12702/13041] Building CXX object src/CMakeFiles/unit_tests_dbms.dir/Common/tests/gtest_dns_reverse_resolve.cpp.o
Mar 18 13:28:44 [12703/13041] Linking CXX executable utils/check-marks/check-marks
Mar 18 13:28:44 FAILED: utils/check-marks/check-marks 
```

**Comment by antonio2368** [comment]
Fixed with https://github.com/ClickHouse/ClickHouse/pull/61519
