### ISSUE TITLE
ClickHouse with a huge data size

### ISSUE THREAD

**Issue by ashraf-4** [ClickHouse/ClickHouse#61566]
I am planning to use clickhouse data base with a huge size of data let suppose it around 700 TB . 
so 100% i should use a clustering. 
but my question is how many nodes should be there and what is the size for each node. 
also what is the best architecture for this scenario. 

pleas if someone has a good ideas let's share with each others . 

Thanks

**Comment by davenger** [comment]
The configuration depends a lot on what kind of data you are going to store and what workloads you are going to run: how much data is ingested, how much of it read by the queries, what kind computation the queries will be doing etc.
You can find some considerations here https://clickhouse.com/docs/en/guides/sizing-and-hardware-recommendations
as well as some examples:
https://clickhouse.com/docs/en/guides/sizing-and-hardware-recommendations#example-configurations-for-large-workloads
