### ISSUE TITLE
Rows are not getting inserted after a delete in ClickHouse Cloud

### ISSUE THREAD

**Issue by kurtApiit** [ClickHouse/ClickHouse#61565]
**Describe the unexpected behaviour**
No rows are inserted after performing a lightweight delete on rows with the exact same values.

**How to reproduce**
* Which ClickHouse server version to use: 24.1.2.10866
* Which interface to use, if matters: JDBC, shouldn't matter
* Non-default settings, if any: N/A
* `CREATE TABLE` statements for all tables involved

```sql
CREATE TABLE lw_delete_test
(
  some_key    UInt64,
  some_value  UInt64
) ORDER BY some_key;
```

* Sample data for all these tables:

```sql
INSERT INTO lw_delete_test
SELECT number, 
       number * 2 
FROM numbers(1000000);
```

* Queries to run that lead to unexpected result

```sql
DELETE FROM lw_delete_test WHERE some_key % 2 = 0;

INSERT INTO lw_delete_test
SELECT number, 
       number * 2 
FROM numbers(1000000)
WHERE number % 2 = 0;
```

After running the above queries a couple of times, one will reach a point where the INSERT statement does not insert anything into the table.

NOTE: I have v24.3.1.1 installed in my local system, but i cannot reproduce the same behaviour with it.

**Expected behavior**
Data should be inserted regardless of whether they were previously deleted.

**Comment by Algunenano** [comment]
ClickHouse deduplicates duplicated inserts by default, so that if you insert the same block N times it will only insert it once.

If you want to insert the same block multiple times you can:
* Set `insert_deduplicate` to false.
* Use a different `insert_deduplication_token` setting for each insert.
