### ISSUE TITLE
S3 cache and encrypted disk

### ISSUE THREAD

**Issue by teckatlipoka** [ClickHouse/ClickHouse#61598]
I'm unable to create cache disk over S3 encrypted disk. Alexey Milovidov mentioned in [youtube presentation](https://youtu.be/rK2BsaaaOCA?t=3485) that cache and encrypted disk should work. But I got error: _cached disk is allowed only on top of object storage_ 

**How to reproduce**
I want to create S3 disk to keep encrypted parts on it with local cache. So I have `s3_disk_encrypted` of type `encrypted` over `s3_disk`. I added disk `s3_cache_encrypted` of type `cache` over `s3_disk_encrypted`:

```
      <s3_disk>
        <type>s3</type>
        <endpoint>https://.../clickhouse3/</endpoint>
        <access_key_id>1111</access_key_id>
        <secret_access_key>1111</secret_access_key>
      </s3_disk>
      <s3_cache>
        <type>cache</type>
        <path>/var/lib/clickhouse/disks/s3_cache/</path>
        <max_size>120Mi</max_size>
        <disk>s3_disk</disk>
      </s3_cache>
      <s3_disk_encrypted>
        <type>encrypted</type>
        <disk>s3_disk</disk>
        <algorithm>AES_128_CTR</algorithm>
        <key_hex id="0">11111111111111111111</key_hex>
        <current_key_id>0</current_key_id>
      </s3_disk_encrypted>
      <s3_cache_encrypted>
        <type>cache</type>
        <path>/var/lib/clickhouse/disks/s3_cache_encrypted/</path>
        <max_size>1Mi</max_size>
        <disk>s3_disk_encrypted</disk>
      </s3_cache_encrypted>
	  
    <policies>
      <s3_encrypted>
        <volumes>
          <encrypted_volume>
            <disk>s3_cache_encrypted</disk>
          </encrypted_volume>
        </volumes>
      </s3_encrypted>
   </policies>
```

After settings midified cannot start Clickhouse with error  `Application: DB::Exception: Cannot wrap disk s3_disk_encrypted with cache layer s3_cache_encrypted: cached disk is allowed only on top of object storage: Cannot attach table system.query_log_0` 

How to properly configure caching on an encrypted disk, particularly for S3?

Clickhouse version 23.8

**Comment by kssenii** [comment]
This should work:
```
<disks>
    <s3_disk>
        <type>s3</type>
        <endpoint>https://.../clickhouse3/</endpoint>
        <access_key_id>1111</access_key_id>
        <secret_access_key>1111</secret_access_key>
      </s3_disk>
      <s3_cache>
        <type>cache</type>
        <path>/var/lib/clickhouse/disks/s3_cache/</path>
        <max_size>120Mi</max_size>
        <disk>s3_disk</disk>
      </s3_cache>
      <s3_cache_encrypted>
        <type>encrypted</type>
        <disk>s3_cache</disk>
        <algorithm>AES_128_CTR</algorithm>
        <key_hex id="0">11111111111111111111</key_hex>
        <current_key_id>0</current_key_id>
      </s3_cache_encrypted>
 </disks>
 <policies>
     <s3_encrypted>
        <volumes>
          <encrypted_volume>
            <disk>s3_cache_encrypted</disk>
          </encrypted_volume>
        </volumes>
    </s3_encrypted>
</policies>
```

**Comment by teckatlipoka** [comment]
It works, thanks.

Will it provide S3 data encryption? These settings define encrypted cache but not S3 encryption. How to check that S3 data in encrypted beyond file `format_version.txt`?

If I use local disk `default` for hot data and S3 for cold and I want to encrypt all data local+S3 how to setup full encryption? Is it correct:
```
 <policies>
     <hot_cold_s3_encrypted>
        <volumes>
          <encrypted_volume>
            <disk>default</disk>
          </encrypted_volume>
          <encrypted_volume>
            <disk>s3_cache_encrypted</disk>
          </encrypted_volume>
        </volumes>
    </s3_encrypted>
</policies>
```

**Comment by kssenii** [comment]
> Will it provide S3 data encryption? These settings define encrypted cache but not S3 encryption.

The configuration I attached provides both encrypted cache AND encrypted S3 storage.

> If I use local disk default for hot data and S3 for cold and I want to encrypt all data local+S3 how to setup full encryption? 

Absolutely the same way. 

> <disk>default</disk>

here disk `default` is not decrypted, you should create an encrypted disk the same way you did for `s3_cache_encrypted`.
