### ISSUE TITLE
How to update the clickhouse cluster version correctly?

### ISSUE THREAD

**Issue by mxsavchenko** [ClickHouse/ClickHouse#61595]
My cluster size is 2 nodes, with engine tables ReplicatedMergeTree, there are also tables whose data are on s3 with `allow_remote_fs_zero_copy_replication`.  Current version is 23.9, i plan to update by 24.1.
How to do it correctly? upgrade each node sequentially or shutdown all at once, upgrade and run?

**Comment by nickitat** [comment]
You could update one node at a time to not cause complete downtime
