### ISSUE TITLE
Update and delete

### ISSUE THREAD

**Issue by Sundarcj** [ClickHouse/ClickHouse#6159]
Hi,
   I am having a use case of processing trillions of records. where I can't predict what type of data we are about to process .. kind of data cleaning tool.so can I go with the distributed engine to utilize the parallel query processing.? or with single node?. I have the update operation also, for that I created another table that have two columns ```Unique_Id``` and boolean ```modified state``` so for delete operation I just mark relative unique id to false.  assume I have a ```unique_id ``` for rows. do join querys for following fetch request. Is that idea okay??

**Comment by blinkov** [comment]
@Sundarcj, do you have any further questions?

**Comment by robot-clickhouse** [comment]
@Sundarcj, is this question still relevant?

**Comment by ljluestc** [comment]
This is a design question which probably shouldn't be asked here, but just FYI
```
#include <clickhouse/client.h>
struct Record {
    std::string uniqueId;
};

int main() {
    client.execute("CREATE TABLE IF NOT EXISTS distributed_table (uniqueId String, ...) ENGINE = Distributed('<cluster-name>', '<database-name>', '<table-name>', rand())");
    client.execute("INSERT INTO distributed_table SELECT * FROM <data-source>");
    client.execute("CREATE TABLE IF NOT EXISTS cleaned_table AS SELECT uniqueId, ... FROM distributed_table WHERE ...");
    client.execute("CREATE TABLE IF NOT EXISTS filtered_table AS SELECT * FROM cleaned_table WHERE ...");
    client.execute("CREATE TABLE IF NOT EXISTS modifications (uniqueId String, modified UInt8)");
    client.execute("INSERT INTO modifications SELECT uniqueId, 1 FROM distributed_table WHERE ...");
    client.execute("INSERT INTO modifications SELECT uniqueId, 0 FROM distributed_table WHERE ...");
    client.execute("INSERT INTO <output-table> SELECT * FROM filtered_table");
    client.execute("INSERT INTO <updated-table> SELECT * FROM cleaned_table WHERE uniqueId IN (SELECT uniqueId FROM modifications WHERE modified = 1)");
    client.execute("INSERT INTO <deleted-table> SELECT * FROM cleaned_table WHERE uniqueId IN (SELECT uniqueId FROM modifications WHERE modified = 0)");
    return 0;
}
```

**Comment by melvynator** [comment]
I don't recommend to do updates at that scale. You should instead use the replacingMergeTree table engine. You could also use lightweight delete operation, but it still an heavy operation at scale.
