### ISSUE TITLE
Prepare to use Memory Sanitizer in CI.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6161]
Background: we already have Address, Thread and Undefined Behaviour sanitizers in CI, but no Memory sanitizer.

Usage example:
https://github.com/yandex/ClickHouse/blob/master/dbms/tests/instructions/sanitizers.md#how-to-use-memory-sanitizer

We need to make all functional tests pass. There are remaining issues. For example, `ngramDistance` function has legal usage of initialized memory and requires annotations.

Note: there is no need to disable every library, they are disabled just in case. We need to enable as many libraries as possible (and report bugs, make patches and add annotations to them).

**Comment by akuzm** [comment]
For the reference, some related changes:

https://github.com/ClickHouse/ClickHouse/pull/6925

https://github.com/ClickHouse/ClickHouse/pull/7062

**Comment by akuzm** [comment]
New failure with Null fields: Null is converted to Int64 with get<>, giving an uninitialized result.
This is different from the earlier failure where UInt8 was converted to UInt64 (6960b893fdd0a3147ead7e0125e213988e0916b9)

The test results:
https://clickhouse-test-reports.s3.yandex.net/7231/2e81ad7f335a26ad0949e8a3dda12eeb43531afc/functional_stateless_tests_(memory).html

**Comment by akuzm** [comment]
Something new in FunctionArrayMapped on stateful tests:

https://clickhouse-test-reports.s3.yandex.net/0/f0409348a1daa04a79e898a0db68147db4425077/functional_stateful_tests_(memory)/stderr.log
