### ISSUE TITLE
(Analyzer - not, still in development, but close) AST Fuzzer (tsan): Logical error: 'Function tuple(123 * countIf(NOT ((__table1.number % 2) = 0)) IGNORE NULLS) expects 1 argument to have Nullable(UInt64) type but receives UInt64 after running SumIfToCountIf pass'.

### ISSUE THREAD

**Issue by serxa** [ClickHouse/ClickHouse#61624]
https://s3.amazonaws.com/clickhouse-test-reports/61545/4f30ac72a1ef01f7c783c192639933e32d2f0397/ast_fuzzer__tsan_.html

https://github.com/ClickHouse/ClickHouse/pull/61545

**Comment by antonio2368** [comment]
Oh no seems like this fix didn't help https://github.com/ClickHouse/ClickHouse/pull/61389
:scream:
