### ISSUE TITLE
`first_value()` returns unexpected nulls under some circumstances

### ISSUE THREAD

**Issue by bmvi-kinver** [ClickHouse/ClickHouse#61640]
On the latest version of ClickHouse (24.2.2.71 as of writing), `first_value()`  does not seem to ignore nulls under some circumstances. Specifically, running this query (which can also be found at https://fiddle.clickhouse.com/37695c23-f606-4d16-ad6e-ff3897b0eea0)
```sql
CREATE TABLE test_data
(
    a Date32,
    b Nullable(String),
    id Integer,
)
ENGINE = Memory;

INSERT INTO test_data (a, b, id) Values ('2023-11-01', null, 1), ('2023-11-01', null, 1), ('2023-11-02', 'not null', 1);

select id, a, b, first_value(b) over (partition by id order by a) from test_data;
```
returns the rows
|id|a|b|any(b) OVER (PARTITION BY id ORDER BY a ASC)|
|--|-|-|--------------------------------------------|
|1|2023-11-01|||
|1|2023-11-01|||
|1|2023-11-02|not null|not null|

while I expect to see

|id|a|b|any(b) OVER (PARTITION BY id ORDER BY a ASC)|
|--|-|-|--------------------------------------------|
|1|2023-11-01||not null|
|1|2023-11-01||not null|
|1|2023-11-02|not null|not null|

Adding `ignore nulls` after the `first_value()` call seems to have no effect. I'm not sure if this is an actual bug or if there's a misunderstanding on my part, though.

**Comment by den-crane** [comment]
You misunderstood window function frame 

https://fiddle.clickhouse.com/55a1cdec-0194-4c78-94fa-134e0b60bb8c

```
select id, a, b, 
   first_value(b) over (partition by id order by a 
    Rows BETWEEN  UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) _first,
   any(b) over (partition by id order by a 
    Rows BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) _any
from test_data
order by id, a
format Pretty;

+----+------------+----------+----------+----------+
| id |          a | b        | _first   | _any     |
+----+------------+----------+----------+----------+
|  1 | 2023-11-01 | NULL     | not null | not null |
+----+------------+----------+----------+----------+
|  1 | 2023-11-01 | NULL     | not null | not null |
+----+------------+----------+----------+----------+
|  1 | 2023-11-02 | not null | not null | not null |
+----+------------+----------+----------+----------+
```
