### ISSUE TITLE
How to mimic upsert for only few columns of a table

### ISSUE THREAD

**Issue by jiayeZhu** [ClickHouse/ClickHouse#61660]
Hi,

I know clickhouse doesn't suppor upsert like other RDBMS at the moment. and we are already using replacing merge tree to kindof mimic upsert. 
our current workflow is:

1. put the new data in a small table with same schema as the target table but much less data (520 columns but no more than 10K rows) it has data for the sorting by columns and few columns we want to update (<20 columns) other columns are all null.
2. join the small table with the target table (520 columns, very large even after partition and sharding. for large partition can have more than 100M rows) on the sorting keys(the unique sorting by we are using in the replacing merge tree)
3. select coalesce all the columns pick from the small table first or else fallback to the data from target table
4. insert back the result into the target table (replacing merge tree) with a new now64() as timestamp

so after some time or after manulally do optimize table query several times it will be deduped in the end. but the performance for large partitions is not acceptable when we need to do this frequently (run the whole workflow every 5-10 seconds with 10K new rows.

Is there a better way to do upsert for only few columns?
if not, will adding more shards help? or any way to improve? unfortunately we are using self hosted clickhouse cluster so we cannot try lightweight update....

**Comment by den-crane** [comment]
AggregateFunction can mimic it. https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794

**Comment by jiayeZhu** [comment]
@den-crane thanks this looks good. only one small issue we noticed after switching to the aggregatingMergeTree:

although the table already has 500+ non-PK columns, and more than 2million rows in each part files, it still choose to merge using horizontal merge instead of vertical merge. the horizontal merge eat too much memory...
we attach the same partition to a merge tree table and we don't see this issue.

here are the settings:
```
SELECT
    name,
    value
FROM system.merge_tree_settings
WHERE name LIKE '%vert%'

Query id: b694169c-2304-406f-a684-939a1248ce7d

┌─name─────────────────────────────────────────────┬─value──┐
│ enable_vertical_merge_algorithm                  │ 1      │
│ vertical_merge_algorithm_min_rows_to_activate    │ 131072 │
│ vertical_merge_algorithm_min_bytes_to_activate   │ 0      │
│ vertical_merge_algorithm_min_columns_to_activate │ 11     │
│ allow_vertical_merges_from_compact_to_wide_parts │ 1      │
└──────────────────────────────────────────────────┴────────┘

SELECT version()

Query id: 29bd3bca-a070-4925-a1cb-c42bb6edcd03

┌─version()──┐
│ 23.12.2.59 │
└────────────┘

related parts (sensitive information masked):

SELECT
    name,
    part_type,
    rows
FROM system.parts
WHERE (name IN ('......')) AND (table = 'xxxxxx')

Query id: 11e48d75-d63d-4e85-85e9-22ce032907fd

┌─name────────────────┬─part_type─┬─────rows─┐
│ .........._49_49_3  │ Wide      │ 11742422 │
│ .........._50_50_3  │ Wide      │ 11701792 │
│ .........._51_51_3  │ Wide      │ 11789362 │
│ .........._52_52_3  │ Wide      │ 11747259 │
│ .........._53_53_2  │ Wide      │  2353192 │
│ .........._54_54_2  │ Wide      │  2353181 │
│ .........._55_60_2  │ Wide      │  2347963 │
│ .........._61_65_2  │ Wide      │  1952398 │
│ .........._66_106_1 │ Wide      │  2674902 │
└─────────────────────┴───────────┴──────────┘

SELECT *
FROM system.merges
LIMIT 1

Query id: c8c117f9-eb3d-42f4-8f8e-671f7cc568b7

Row 1:
──────
database:                      ..........
table:                         ..........
elapsed:                       10173.84425087
progress:                      0.4125672783200694
num_parts:                     9
source_part_names:             ['.........._49_49_3','.........._50_50_3','.........._51_51_3','.........._52_52_3','.........._53_53_2','.........._54_54_2','.........._55_60_2','.........._61_65_2','.........._66_106_1']
result_part_name:              .........._49_106_4
source_part_paths:             ..........
result_part_path:              ..........
partition_id:                  ..........
partition:                     ..........
is_mutation:                   0
total_size_bytes_compressed:   2606947255
total_size_bytes_uncompressed: 268270930616
total_size_marks:              25267
bytes_read_uncompressed:       110890254247
rows_read:                     24202216
bytes_written_uncompressed:    222296047616
rows_written:                  24169971
columns_written:               0
memory_usage:                  4198764624
thread_id:                     3415
merge_type:                    Regular
merge_algorithm:               Horizontal
```

do you have any idea why this could happen? any way to force use vertical merge? thanks!
