### ISSUE TITLE
Add ability to truncate all tables in the DB

### ISSUE THREAD

**Issue by doom369** [ClickHouse/ClickHouse#61686]
Currently, it's possible to truncate a single table with command:

`TRUNCATE TABLE {table_name}`

It's also, possible to remove all tables from the DB with:

`TRUNCATE DATABASE {db_name}`

However, there is no option to truncate all tables in the DB (without table removal). It would be very convenient to use something like:

`TRUNCATE ALL TABLES {db_name}`

or something similar.

**Comment by den-crane** [comment]
Done: 

v23.8.1.2992-lts.md:* Support `TRUNCATE DATABASE` operation. [#53261](https://github.com/ClickHouse/ClickHouse/pull/53261) ([Bharat Nallan](https://github.com/bharatnc)).

**Comment by doom369** [comment]
@yariks5s thanks!
