### ISSUE TITLE
JSONEachRow format incorrect when use Int64 type

### ISSUE THREAD

**Issue by freedomDR** [ClickHouse/ClickHouse#61693]
**Describe the unexpected behaviour**
when use JSONEachRow formatter, it can't give me required of format.

**How to reproduce**
create table test_dr (dt String, val Int64) engine = Memory();
select * from test_dr format JSONEachRow;
<img width="469" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/11146756/82080915-4110-4ede-8114-1a10dc69f8b9">

**expect behaviour**
{"dt":"20240101","val":101}

**Comment by freedomDR** [comment]
Version: 24.3.1.1823

**Comment by den-crane** [comment]
Completely expected behaviour. Javascript does not supports Uint64 numbers.

there is a setting ` --output_format_json_quote_64bit_integers Controls quoting of 64-bit integers in JSON output format.`

```
select 1::Int64 as A format JSONEachRow;
{"A":"1"}

select 1::Int64 as A settings output_format_json_quote_64bit_integers=0 format JSONEachRow;
{"A":1}
```
