### ISSUE TITLE
(Analyzer: this feature is not ready, hold tight) `WITH CUBE` crashes with `group_by_use_nulls`

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#61697]
Example:
```sql
SELECT 'a' AS key, 'b' as value GROUP BY key WITH CUBE SETTINGS group_by_use_nulls = 1, allow_experimental_analyzer = 1;
```

https://s3.amazonaws.com/clickhouse-test-reports/0/293f2fda4e67fc50a60ac644aaa78aade288f49f/stress_test__asan_.html

Reverting this PR helps https://github.com/ClickHouse/ClickHouse/pull/59986

The problem seems the type for CUBE which remains nonnullable even though the header is nullable.

cc @novikd @azat

**Comment by novikd** [comment]
I suspect the fix would be quite simple. I think we need to convert the column to nullable if needed.

**Comment by serxa** [comment]
Another repro
https://s3.amazonaws.com/clickhouse-test-reports/61545/34e3eb223e7eb830ed44469700ad35f0b794f978/stress_test__tsan_.html
