### ISSUE TITLE
Steampipe (PostgreSQL) Integration with ClickHouse Data

### ISSUE THREAD

**Issue by linontano** [ClickHouse/ClickHouse#61721]
Hi everyone, I have the following scenario:

I am using [Steampipe](https://steampipe.io/) as a data enrichment tool. It works pretending to be a PostgreSQL database but behind it it makes queries via API to the technology of the [plugin](https://hub.steampipe.io/) that we are using. I have the information to be enriched stored in a table in ClickHouse. Using the ClickHouse-PostgreSQL integration I have been able to represent the Steampipe tables in the ClickHouse database. The problem occurs in being able to use the information stored in ClickHouse as input for the Steampipe table. For some plugins, it is necessary to have an INPUT in the WHERE condition since that is what Steampipe is based on: Performing a query to an API (table of your choice) about some element in question (WHERE Condition field='...'). As an example we have the following:
```sql
SELECT
  repository_full_name,
  number,
  title,
  state,
  author_login,
  assignees_total_count
FROM
  steampipe_remote.github_issue -- steampipe table
WHERE
  state = 'OPEN'
  AND repository_full_name IN (
      SELECT
         full_name
      FROM default.users_repo_company -- clickhouse table
      WHERE department = 45
  )
```
In this case, the PostgreSQL server receives the query only with the condition of `state='OPEN'` and it is understandable according to what the [documentation](https://clickhouse.com/docs/en/engines/table-engines/integrations/postgresql#implementation-details) indicates :

> **Implementation Details**
...
Simple WHERE clauses such as =, !=, >, >=, <, <=, and IN are executed on the PostgreSQL server.

The `repository_full_name IN ( <CH query>)` condition, not being a "Simple WHERE clause", is not sent in the query since it is dependent on a ClickHouse query. And it will be executed when the PostgreSQL server query finishes executing, which is not desired here since it is necessary for the PostgreSQL query to have the values of `repository_full_name`.

The big question: isn't there a way (at that query level) to send the ClickHouse information first so that the PostgreSQL query can then be executed? I have tried with parameterized views, CTEs, dictionaries and I have not succeeded, or is it already something uncontrollable?

**Comment by pmusa** [comment]
Hi @linontano, can you please share the `steampipe_remote` definition and the `EXPLAIN` output?

**Comment by linontano** [comment]
Hi @pmusa, 

**steampipe_remote definition:**
```
SHOW CREATE DATABASE steampipe_remote

Query id: 912c0781-bd68-4c52-8b08-1ff4aa9aee30

┌─statement───────────────────────────────────────┐
│ CREATE DATABASE steampipe_remote
ENGINE = Atomic │
└─────────────────────────────────────────────────┘
```
**steampipe_remote.github_issue definition:**

```
SHOW CREATE TABLE steampipe_remote.github_issue

Query id: 7d93dd3a-0df9-45a0-9d97-53a50da0c7d2

┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ CREATE TABLE steampipe_remote.github_issue
(
    `state` Nullable(String),
    `repository_full_name` Nullable(String),
    -- a lot of columns --
)
ENGINE = PostgreSQL('XXX.XXX.XX.XX:XXX', 'steampipe', 'github_issue', user_steampipe', '[HIDDEN]', 'github_issue') │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
**EXPLAIN output:**
```
EXPLAIN
SELECT
    repository_full_name,
    number,
    title,
    state,
    author_login,
    assignees_total_count
FROM steampipe_remote.github_issue
WHERE (state = 'OPEN') AND (repository_full_name IN (
    SELECT full_name
    FROM default.users_repo_company
    WHERE department = 45
))
Query id: 0c93771d-963b-45df-8721-1b211f764958

┌─explain────────────────────────────────────────────────┐
│ CreatingSets (Create sets before main query execution) │
│   Expression ((Projection + Before ORDER BY))          │
│     Filter (WHERE)                                     │
│       ReadFromStorage (PostgreSQL)                     │
│   CreatingSet (Create set for subquery)                │
│     Expression ((Projection + Before ORDER BY))        │
│       Limit (preliminary LIMIT (without OFFSET))       │
│         ReadFromMergeTree (default.users_repo_company) │
└────────────────────────────────────────────────────────┘
```

**Comment by pmusa** [comment]
A similar example is working for me just fine. And based on your output, I would say it is working on your side as well. I am not sure what is the issue that are facing.

**Comment by den-crane** [comment]
>  AND repository_full_name IN (
      SELECT
         full_name
      FROM default.users_repo_company -- clickhouse table
      WHERE department = 45
  )

It's expected that clickhouse fetches data from `steampipe_remote.github_issue` without passing `repository_full_name IN ` predicate into postgreSQL and filters locally in Clickhouse. This was implemented in such way because in general the `IN SELECT full_name` set can have any numbers of elements, for example 50 millions, and it's not possible in general to pass such set using SQL into foreign database. 
There is no setting to change this behaviour.
