### ISSUE TITLE
Wrong behavior of startsWith() in WHERE

### ISSUE THREAD

**Issue by hczhcz** [ClickHouse/ClickHouse#61743]
**Describe what's wrong**

`select count() from <table> where startsWith(<key>, <prefix>)` returns a smaller count than it should be.

**How to reproduce**

ClickHouse server version 23.1.2 accessed from its native client.

The table is a very large table with multiple partitions. It looks like:

```
create table <table>
(
    A Int,
    B FixedString,
    C FixedString,
    <some other columns>
)
engine = MergeTree
partition by A
order by (A, B, C)
```

(I can not provide the real SQL due to confidentiality regulations)

The query `select count() from <table> where startsWith(C, <prefix>)` returns significantly less data (< 1%) than `select count() from <table> where startsWith(C, <prefix>) or rand() = 1234567`. The latter one is likely correct.

The behavior can be reproduced on several tables with similar structure and on another machine.

**Comment by alexey-milovidov** [comment]
23.1 is an old version.

Install the proper ClickHouse version as follows:
```
curl https://clickhouse.com/ | sh
```

Never use old or unofficial ClickHouse builds.
