### ISSUE TITLE
Rust does not work without Internet

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#61741]
If you do `cmake` without internet access, it will print something like `Couldn't resolve host: index.crates.io` which is ridiculous.
Workaround: `cmake -D ENABLE_RUST=0`

**Comment by azat** [comment]
This is the intended behavior. What are you suggesting?

**Comment by alexey-milovidov** [comment]
Either build from source or cache pre-built packages in submodules.

**Comment by azat** [comment]
There are tons of dependencies (see `Cargo.lock`) - 165 as of now, adding all of this as a submodule does not looks like it worth it, Rust is not the primary feature of ClickHouse, and doing this is a significant amount of work that also should be kept in sync.

Note, that right now CI do not download everything every time, since there is cache - https://github.com/ClickHouse/ClickHouse/pull/52865

**Comment by alexey-milovidov** [comment]
Ok. Let's make a message to explain how to disable Rust, if it is unavailable:
```
cmake -D ENABLE_RUST=0
```

**Comment by alexey-milovidov** [comment]
@azat No, I've meant a message that CMake will print. So when you run CMake without Internet, it will tell what to do.

**Comment by azat** [comment]
I thought about this, but did not want to introduce any extra code for this, but I found pretty easy way to do this, so here it is https://github.com/ClickHouse/ClickHouse/pull/61938

**Comment by Algunenano** [comment]
My internet is down. I can’t build CH with all the features.

Let’s consider using something like cargo vendor to pull all the dependencies into a submodule so we don’t depend on crates.io or whatever.

**Comment by azat** [comment]
>My internet is down. I can’t build CH with all the features.

And what is the error?

>Let’s consider using something like cargo vendor to pull all the dependencies into a submodule so we don’t depend on crates.io or whatever.

This is done for CI, but putting a cargo vendor to the submodule is an interesting idea I guess...

**Comment by Algunenano** [comment]
You get something like this:

```
CMake Error at rust/CMakeLists.txt:112 (message):
  Rust
  (/home/raul/.rustup/toolchains/nightly-2023-07-04-x86_64-unknown-linux-gnu/bin/cargo)
  support is not available (likely there is no internet connectivity):

      Updating git repository `https://github.com/azat-rust/tuikit.git`
      Updating crates.io index

  warning: spurious network error (3 tries remaining): [6] Couldn't resolve
  host name (Could not resolve host: index.crates.io)

  warning: spurious network error (2 tries remaining): [6] Couldn't resolve
  host name (Could not resolve host: index.crates.io)

  warning: spurious network error (1 tries remaining): [6] Couldn't resolve
  host name (Could not resolve host: index.crates.io)

  error: failed to get `cxx` as a dependency of package `_ch_rust_skim_rust
  v0.1.0 (/mnt/ch/ClickHouse/build_nointernet/rust/skim)`



  Caused by:

    failed to query replaced source registry `crates-io`

  

  Caused by:

    download of config.json failed

  

  Caused by:

    failed to download from `https://index.crates.io/config.json`

  

  Caused by:

    [6] Couldn't resolve host name (Could not resolve host: index.crates.io)

  

  You can disable Rust support with -DENABLE_RUST=OFF
Call Stack (most recent call first):
  rust/CMakeLists.txt:129 (add_rust_subdirectory)


-- Configuring incomplete, errors occurred!
```

**Comment by azat** [comment]
And this works like it was planned in https://github.com/ClickHouse/ClickHouse/pull/61938

```
  You can disable Rust support with -DENABLE_RUST=OFF
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Call Stack (most recent call first):
  rust/CMakeLists.txt:129 (add_rust_subdirectory)
```

**Comment by alexey-milovidov** [comment]
Yes, let's "vendor" all Rust sources into a submodule. We can open another issue for that.
