### ISSUE TITLE
Aggregate function groupUniqArray(_distinct_id) is found inside another aggregate function in query:

### ISSUE THREAD

**Issue by zhangmingchao** [ClickHouse/ClickHouse#61755]
### Exception: Aggregate function groupUniqArray(_distinct_id) is found inside another aggregate function in query: While processing groupUniqArray(_distinct_id) AS line.

I have a requirement to calculate the distinct_id of a user's retention. It can be divided into initial event distinct_ID and return event. The initial event distinct_id of the same user is equal to the account_id of a return event for the same user.
My idea is to use the groupUniqArray(_distinct_id) function, aggregate the user's _distinct_id function into an array, and then use the has() function in retention, starting with index 2. Determines whether the account_id for the callback event is in groupUniqArray(_distinct_id), but the sql execution returns an error.

> select d_events._user_id                                                                                    as `user_id`,
       groupUniqArray(_distinct_id)                                                                         as line,
       retention(
           toDate(d_events._event_time) = '2024-03-14' and _event_name = '_appStart',
                 toDate(_event_time) = '2024-03-14' and _event_name = '_appEnd' and has(line, _account_id),
                 toDate(_event_time) = '2024-03-15' and _event_name = '_appEnd' and has(line, _account_id),
                 toDate(_event_time) = '2024-03-16' and _event_name = '_appEnd' and has(line, _account_id),
                 toDate(_event_time) = '2024-03-17' and _event_name = '_appEnd' and
                 has(line, _account_id)
           )                                                                    as `2024-03-14`
from (
         select _account_id, _event_name, _appkey, _user_id, _distinct_id, _event_time, _distinct_index
         from d_events
         where _prokey = 'p1'
           and _event_time >= toTimeZone(toDateTime64('2024-03-01 00:00:00.000', 3, 'Etc/GMT-8'), 'Etc/GMT-8')
           and _event_time <= toTimeZone(toDateTime64('2024-03-17 23:59:59.999', 3, 'Etc/GMT-8'), 'Etc/GMT-8')
           and (_event_name = '_appStart' or _event_name = '_appEnd')
         ) d_events
where 1 = 1
  and d_events._user_id is not null
  and _appkey is not null
group by `user_id`
order by `user_id` asc;

-- Aggregate function groupUniqArray(_distinct_id) is found inside another aggregate function in query:

How can I fix this error or implement this requirement? Thank you.

**Comment by den-crane** [comment]
You cannot use aggregate function `groupUniqArray` inside another aggregate function `retention`

Try to re-write query to SELECT retention.... FROM SELECT groupUniqArray ... FROM. ..
