### ISSUE TITLE
I hope throw a exption， when use query like select * from table where date =‘2024-2-31’；

### ISSUE THREAD

**Issue by tori-sallery** [ClickHouse/ClickHouse#61758]
version：23.3 LTS
select * from table where dt='2023-02-29'

return 2023-03-01 

I except a error， not wrong anwser

![image](https://github.com/ClickHouse/ClickHouse/assets/150269087/38c26757-5325-47fd-af58-d91a1a03a361)

**Comment by den-crane** [comment]
behaviour of parsing incorrect dates is implementation specific.
Returning zero date, throwing an exception or doing "natural" overflow - all are conforming.

* https://github.com/ClickHouse/ClickHouse/issues/1744
