### ISSUE TITLE
Violation of settings constraints is not logged in the query_log

### ISSUE THREAD

**Issue by alifirat** [ClickHouse/ClickHouse#61762]
# Describe the unexpected behaviour
When Clickhouse is query with a setting that is not allowed regarding the `readonly` settings, Clickhouse only log the error in the logs but it's not available in the `system.query_log`. 

# How to reproduce
- Clickhouse version: 23.12.4.15

For a user having the settings `readonlymode` set to 1, do a HTTP request that override for instance `enable_http_compression`, the query must fails but it's not available in `system.query_log`. 

**Expected behavior**
- A query that violates constraints settings and failed must be available in the `system.query_log` for tracability / debut purposes.

**Error message and/or stacktrace**

```sql
024.03.20 13:00:18.077960 [ 9685 ] {} <Error> DynamicQueryHandler: Code: 164. DB::Exception: Cannot modify 'enable_http_compression' setting in readonly mode. (READONLY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c6d1c3b in /usr/bin/clickhouse
1. DB::Exception::Exception(PreformattedMessage const&, int) @ 0x000000000f95550c in /usr/bin/clickhouse
2. DB::SettingsConstraints::Checker::check(DB::SettingChange&, DB::Field const&, DB::SettingsConstraints::ReactionOnViolation, DB::SettingSource) const @ 0x00000000101f4781 in /usr/bin/clickhouse
3. DB::SettingsConstraints::checkImpl(DB::Settings const&, DB::SettingChange&, DB::SettingsConstraints::ReactionOnViolation, DB::SettingSource) const @ 0x00000000101f3c2c in /usr/bin/clickhouse
4. DB::SettingsConstraints::check(DB::Settings const&, DB::SettingsChanges&, DB::SettingSource) const @ 0x00000000101f3fa3 in /usr/bin/clickhouse
5. DB::Context::checkSettingsConstraints(DB::SettingsChanges&, DB::SettingSource) const @ 0x000000001094b16f in /usr/bin/clickhouse
6. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x0000000012615fce in /usr/bin/clickhouse
7. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x000000001261b5f6 in /usr/bin/clickhouse
8. DB::HTTPServerConnection::run() @ 0x0000000012696452 in /usr/bin/clickhouse
```

**Additional context**

**Comment by alexey-milovidov** [comment]
> is not log in the query_log

You meant "is not logged"

> For a user having the settings readonlymode set to 1

There is no such setting, `readonlymode`. There is a `readonly` setting.

> for tracability / debut purposes

You meant "debug", not "debut".

**Comment by alexey-milovidov** [comment]
The settings constraints are checked on a user level before attempting to run a query.
If it is violated, the query does not even start to run and there is nothing to put into the query_log.
