### ISSUE TITLE
query_log providing inconsistent (empty) results

### ISSUE THREAD

**Issue by reinert** [ClickHouse/ClickHouse#61761]
I'm polling the query_log to listen for query finished (as suggested in other threads) but I'm getting inconsistent results: sometimes I get the log rows as expected but most of the times I get nothing. I'm using clickhouse cloud. It happens both via nodejs http client and via clickhouse web console. How can I consistently get results when querying the query_log?
```
select * from system.query_log WHERE query_id = '${query_id}'
```

**Comment by alifirat** [comment]
hey @reinert 

Since Clickhouse is a single-shard architecture with multiple replicas, you can maybe try to query the query_log from all the replicas. 
```sql
select * from clusterAllReplicas('{cluster_name}', system.query_log) WHERE query_id = '${query_id}'
```

**Comment by reinert** [comment]
@alifirat works like a charm. thank you!

tip for others: default cluster is 'default' indeed
