### ISSUE TITLE
INSERT INTO default.datalake SELECT * FROM daily_db.daily_table not working.

### ISSUE THREAD

**Issue by testingmic** [ClickHouse/ClickHouse#61760]
I have a node script set to run at regular intervals, executing the following statement:

"The INSERT INTO default.datalake SELECT * FROM day_db.daily_table" command.

Initially, this operation functioned smoothly without any problems. However, it has now ceased to work altogether. Even when executed directly in the ClickHouse console, it returns a success message stating "INSERT succeeded." but when i count the rows in the datalake table it returns zero.

The situation is perplexing because dropping the datalake table and recreating it allows the same query to execute successfully.

**Comment by alifirat** [comment]
Did you check the `system.query_log` table and especially the following columns: 
- type 
- read_rows
- written_rows
- exception

**Comment by testingmic** [comment]
<img width="1014" alt="Screenshot 2024-03-22 at 11 04 07 AM" src="https://github.com/ClickHouse/ClickHouse/assets/42424404/de24ff60-6d13-424d-9a8b-0503e93faa7c">

The exception column is empty.

**Comment by alifirat** [comment]
Are you sure it's the insert query?

**Comment by testingmic** [comment]
Affirmative. It is the insert query, it occured yesterday, i had to drop the table and rerun for all previous days and it worked only for it to reoccur today.

**Comment by Algunenano** [comment]
Are you using replicated tables? It's possible that the insert is being deduplicated (on by default in replicates). It would appear in the query's profile events column in query_log as `DuplicatedInsertedBlocks`.

**Comment by Algunenano** [comment]
Can you please share the full output of system.query_log? And also check the text logs for that query to see if there is anything suspicious.

**Comment by testingmic** [comment]
Sure on it.

**Comment by testingmic** [comment]
[unexpected_behaviour.csv](https://github.com/ClickHouse/ClickHouse/files/14722062/unexpected_behaviour.csv)

I couldn't get to load the entire system.query_log for the query i executed. It sometimes shows empty, other times showed results. Besides the main table has 0 rows.

**Comment by Algunenano** [comment]
> I couldn't get to load the entire system.query_log for the query i executed. It sometimes shows empty, other times showed results. Besides the main table has 0 rows.

You seem to be using ClickHouse cloud, where there are multiple replicas so it's possible that the server that processed the insert is different from the one you are querying system.query_log. Use `FROM clusterAllReplicas(default, system.query_log)` to search in all the replicas of the service.

Also please consider opening a support ticket so the team can look into the issue with more information.

**Comment by e-mars** [comment]
@testingmic yes, if using ClickHouse Cloud, please submit a support case here and we can take a deeper look.
https://clickhouse.cloud/support
Help-->Support-->New Case

**Comment by testingmic** [comment]
Apparantly there is the option "SETTINGS insert_deduplicate = 0" which can be added to the insert query and that solved the issue.
Thank you @e-mars @Algunenano @alifirat for the support
