### ISSUE TITLE
How to get the server_settings like max_server_memory_usage_to_ram_ratio in the client ( clickhose server release 22.7.1.2484) 

### ISSUE THREAD

**Issue by dingyalin** [ClickHouse/ClickHouse#61772]
SELECT * FROM system.server_settings WHERE changed AND name='max_thread_pool_size'

 Code: 60. DB::Exception: Table system.server_settings doesn't exist. (UNKNOWN_TABLE) (version 22.7.1.2484 (official build))
, server ClickHouseNode

**Comment by Algunenano** [comment]
You are using an old release (` 22.7.1.2484`). Please update to a supported version

**Comment by dingyalin** [comment]
How to get the server_settings like max_server_memory_usage_to_ram_ratio  in the client  ( clickhose server release 22.7.1.2484)
