### ISSUE TITLE
`heap-buffer-overflow` in `usearch`

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#61780]
UBSan crashed because of memory corruption
https://s3.amazonaws.com/clickhouse-test-reports/0/b8b977e99fefcedcd55900b3198f5a317c7f5090/ast_fuzzer__ubsan_.html

It's easily reproducible with ASAN build:

```sql
SET allow_experimental_usearch_index = 1;

CREATE TABLE tab_usearch__fuzz_9 (`id` UInt256, `vec` Tuple(Float32, Float32), INDEX idx vec TYPE usearch('cosineDistance', 'f64') GRANULARITY 2) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 3;

INSERT INTO tab_usearch__fuzz_9 FORMAT Values (0, (4.6, 2.3)), (1, (2.0, 3.2)), (2, (4.2, 3.4)), (3, (5.3, 2.9)), (4, (2.4, 5.2)), (5, (5.3, 2.3)), (6, (1.0, 9.3)), (7, (5.5, 4.7)), (8, (6.4, 3.5)), (9, (5.3, 2.5)), (10, (6.4, 3.4)), (11, (6.4, 3.2));

WITH  coalesce(255, toNullable(2)), (0., 2.) AS reference_vec SELECT coalesce(toFixedString('val', 3), 3, 3, toNullable(3), 3, 3, 3, 24, 13), id, vec, cosineDistance(vec, reference_vec) FROM tab_usearch__fuzz_9 PREWHERE coalesce(13, toUInt128(510), toLowCardinality(toNullable('- Annoy: WHERE-type')), toNullable(19), 19, 13) ORDER BY cosineDistance(vec, reference_vec) ASC NULLS LAST LIMIT 9223372036854775806 SETTINGS allow_experimental_analyzer = true, allow_experimental_annoy_index = true, allow_experimental_usearch_index = true, max_limit_for_ann_queries = 9223372036854775806;
```

ASAN report
https://pastila.nl/?000ff419/74f4be307caddd1a7e92e4423047849b#/Td8ZXUHS/7Y5MtLTPEBgA==

**Comment by Algunenano** [comment]
As this was reference in a recent usearch releases as "might be fixed", I've done a quick check with usearch `2.11.6` . It's still present: https://pastila.nl/?00058ab2/3fb7f3791d00bf5f720bc264a26b9107#OY0wxYr8/3krLp9vGNEZxw==

**Comment by ashvardanian** [comment]
Hi @Algunenano and @al13n321!

I've tried to replicate and debug the error, but I'm having a hard time even compiling the ClickHouse codebase. I've just added a couple of other safeguards/asserts to catch the error in debug builds. Any chance we can re-run debug build with a recent version and see if any of the checks fire up?

I also had a hypothesis, that if the fuzzer produces some weird config/state, I can replicate all kinds of weird configs as part of the `test.cpp` in USearch to locate the issue. As of now, about 500,000 configs are checked just in this section and everything seems to work fine:

https://github.com/unum-cloud/usearch/blob/aa94e1524206ef27d287b05ab1a2e3d951e0908e/cpp/test.cpp#L571-L580

We can sync up over a zoom call to trace the issue together 🤗

**Comment by antonio2368** [comment]
@ashvardanian the problem is here
https://github.com/unum-cloud/usearch/blob/main/include/usearch/index_plugins.hpp#L580

for `9223372036854775806` it returns `0`, probably an overflow.

Quickfix that worked for me was something like:
```cpp
if (length > length_bytes)
    return nullptr;
```

**Comment by ashvardanian** [comment]
Superb, @antonio2368! Will merge your patch soon 🤗
