### ISSUE TITLE
Not enough privileges. To execute this query, it's necessary to have the grant CLUSTER ON

### ISSUE THREAD

**Issue by galvo** [ClickHouse/ClickHouse#61781]
**Describe the issue**
On Clickhouse 24.2.2 and 24.1.5.6 i am unable to use a new created user to create a database table. I believe i tested this on Clickhouse 23.x and it worked.

**How to reproduce**

```
CREATE DATABASE IF NOT EXISTS test_access ON CLUSTER `default` ENGINE = Atomic;

CREATE USER 'test_access_user' ON CLUSTER `default` IDENTIFIED BY 'test_access';

CREATE ROLE test_access_role ON CLUSTER `default`;

GRANT ALL PRIVILEGES ON test_access.* TO test_access_role ON CLUSTER `default`;

GRANT test_access_role TO test_access_user ON CLUSTER `default`;
```

Then login with `test_access_user` and execute any create table such as 

```
create table if not exists `test_access`.`table1` ON CLUSTER `default`
(
    workspace VARCHAR(255)
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{uuid}', '{replica}-{shard}')
```

**Error message and/or stacktrace**

I receive the following error stating that i must give wildcard permission to all tables.. but i don't want to do this.. i want to restrict the user to a specific database on the cluster

```
Code: 497. DB::Exception: test_access_user: Not enough privileges. To execute this query, it's necessary to have the grant CLUSTER ON *.*. (ACCESS_DENIED) (version 24.2.2.71 (official build))
```

**Comment by nikitamikhaylov** [comment]
This is intentional, please take a look here: https://github.com/ClickHouse/ClickHouse/pull/58584
The old behaviour can be returned back by disabling `on_cluster_queries_require_cluster_grant`

**Comment by davispuh** [comment]
> This is intentional

yes but I couldn't find it anywhere documented how to make it work?

With some trial I found it is
```
GRANT CLUSTER ON *.* TO test_access_user
```

Also nothing else as `*.*` won't work:
> Code: 509. DB::Exception: CLUSTER cannot be granted on the database level. (INVALID_GRANT)
> Code: 509. DB::Exception: CLUSTER cannot be granted on the table level. (INVALID_GRANT)
