### ISSUE TITLE
`logger` server settings section missing `formatting` key

### ISSUE THREAD

**Issue by danthegoodman1** [ClickHouse/ClickHouse#61804]
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#logger missing info, see examples at https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L62-L90 and https://kb.altinity.com/altinity-kb-setup-and-maintenance/ch-logs-2-json-vectordev/

**Comment by tylerhannan** [comment]
Thanks @danthegoodman1 - You ok If I open this as an issue in [clickhouse-docs ](https://github.com/ClickHouse/clickhouse-docs) instead?

**Comment by danthegoodman1** [comment]
Sure go for it

**Comment by justindeguzman** [comment]
Thanks @danthegoodman1! Info about the `formatting` key is added in this PR: https://github.com/ClickHouse/ClickHouse/pull/62015
