### ISSUE TITLE
Should it be deleted /table_path_in_zk/temp/abandonable_lock-insert and /table_path_in_zk/temp/abandonable_lock-other

### ISSUE THREAD

**Issue by hjun881** [ClickHouse/ClickHouse#61805]
> After using version 22.12.6, it resulted in a high ClickHouseAsyncMetrics RepelicasSumQueueSize, so I downgraded it to 22.3.2.2. Do I want to delete /table_path_in_zk/temp/abandonable_lock-insert and /table_path_in_zk/temp/abandonable_lock-other? What is their purpose? Is manual deletion risky?

**Comment by alexey-milovidov** [comment]
Do not delete anything from ZooKeeper. Don't even look there.

**Comment by alexey-milovidov** [comment]
> Is manual deletion risky?

Yes, it is not just risky but totally forbidden.
