### ISSUE TITLE
Does ClickHouse support recursive CTE?

### ISSUE THREAD

**Issue by hueiyuan** [ClickHouse/ClickHouse#61850]
### Description
Because we want to execute trace query like jaeger to show dependency graph on grafana (like below image), and it seems that need to use `Recursive CTE` to achieve it, we refer to [timescale](https://www.timescale.com/blog/learn-opentelemetry-tracing-with-this-lightweight-microservices-demo/) can achieve similar objective, But we are not sure current ClickHouse is support this? 

Hope someone can assist to give some suggestion or answer, we will be appreciated it, thank you.

* Jaeger Dependency Graph
![jaeger-graph-example](https://github.com/ClickHouse/ClickHouse/assets/49678319/de36442f-78a5-4fcb-bcc9-01485212b112)

**Comment by alexey-milovidov** [comment]
No, as of 2024-03-25, ClickHouse does not support recursive CTE.
A workaround could be using a temporary table and a loop.

**Comment by rschu1ze** [comment]
https://github.com/ClickHouse/ClickHouse/pull/62074
