### ISSUE TITLE
clickhouse-keeper config

### ISSUE THREAD

**Issue by dxygit1** [ClickHouse/ClickHouse#61904]
The parameters shown in the documentation are the only ones available in clickhouse-keeper, right? Is there a parameter to control log cleanup? Where can I find a more comprehensive list of configuration parameters

**Comment by antonio2368** [comment]
Some coordination settings are missing, you can check them here
https://github.com/ClickHouse/ClickHouse/blob/master/src/Coordination/CoordinationSettings.h#L22

> Is there a parameter to control log cleanup? 

What would you like to control for log cleanup?

**Comment by dxygit1** [comment]
For example, configuring how many logs to retain or how many days to retain them, similar to snapshot retention policies, is it possible?

**Comment by dxygit1** [comment]
Is the parameter 'reserved_log_items' used to specify the number of reserved log items?

**Comment by antonio2368** [comment]
Log retention is controlled with `reserved_log_items`. When a snapshot is created, all logs up to `snapshot_idx - reserverd_log_items` index will be removed.
So if you want higher retention you would need to increase that setting

**Comment by dxygit1** [comment]
I understand. Thank you very much
