### ISSUE TITLE
源码安装clickhouse 失败

### ISSUE THREAD

**Issue by zhangmingchao** [ClickHouse/ClickHouse#61913]
I tried to install clickhouse source code, but the recursive command "git submodule update --init --recursive" kept coming back and forth. For example, "failed to clone 'contrib/aws'", how did you solve that?

![ck](https://github.com/ClickHouse/ClickHouse/assets/42715943/f80a7ab0-d41c-4de9-9f88-5974502e3b7b)

**Comment by alexey-milovidov** [comment]
It isn't possible to do on Windows.
Only Unix systems are supported for ClickHouse development, such as Linux, FreeBSD, macOS, Illumos, etc.

**Comment by zhangmingchao** [comment]
I just download the source code on windows, and then initialize the submodule, and then install it in docker, and now the initialization submodule keeps getting errors,
