### ISSUE TITLE
Is ClickHouse suitable for use as a real-time data warehouse?

### ISSUE THREAD

**Issue by fankuneee** [ClickHouse/ClickHouse#61921]
For example, using Flink to synchronize data from Oracle to ClickHouse, where a small amount of data (under 100 rows) is generated every second, will this cause frequent merging in ClickHouse? Are there any configurations that can optimize this?
 
 my local tables' (ReplicatedReplacingMergeTree) settings is here:
 ```
SETTINGS index_granularity = 8192,
    parts_to_delay_insert = 2000,
    parts_to_throw_insert = 2000,
    max_delay_to_insert = 10,
    max_suspicious_broken_parts = 5,
    replicated_deduplication_window = 1000,
    execute_merges_on_single_replica_time_threshold = 1,
    replicated_deduplication_window_seconds = 604800
```

**Comment by alexey-milovidov** [comment]
Yes, you can insert data every second and more frequently. You can query the data at the same time, as it is instantly available. This is a perfect use case for ClickHouse.

> SETTINGS index_granularity = 8192,
   parts_to_delay_insert = 2000,
   parts_to_throw_insert = 2000,
   max_delay_to_insert = 10,
   max_suspicious_broken_parts = 5,
   replicated_deduplication_window = 1000,
   execute_merges_on_single_replica_time_threshold = 1,
   replicated_deduplication_window_seconds = 604800

No, you should not complicate this. Remove all the settings.
