### ISSUE TITLE
Is there a method or a pattern to iterate on the (k,v) tuples that compose a Map and obtain an updated Map in return?

### ISSUE THREAD

**Issue by andrea-s** [ClickHouse/ClickHouse#61983]
Use case would be to avoid casting a certain Map to an array just to be able to use arrayMap to iterate through the values.

We have mapFilter and arrayMap, and we do have mapFilter but not "mapMap" (as ugly as it sounds).

Am I missing some method?

Thank you very much

**Comment by CurtizJ** [comment]
The function is called `mapApply` instead of `mapMap`: https://clickhouse.com/docs/en/sql-reference/functions/tuple-map-functions#mapapply

**Comment by andrea-s** [comment]
Thank you for the quick response!
