### ISSUE TITLE
Highlighting numbers does not work for Nullable

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#61993]

**Comment by pheepa** [comment]
Hi, can you please provide more description?

**Comment by den-crane** [comment]
@pheepa If you execute

```
select toUInt64(-1) format PrettyCompact;
```
you see the output with Highlighted thousands

But not in case of Nullable type

```
select toNullable(toUInt64(-1)) format PrettyCompact;
```
<img width="625" alt="Screenshot 2024-04-03 at 5 09 27 PM" src="https://github.com/ClickHouse/ClickHouse/assets/19737682/e6f9ff39-be15-41eb-991b-91a999e22ebf">

**Comment by skyoct** [comment]
@alexey-milovidov Hi, I want to try it.

**Comment by alexey-milovidov** [comment]
@skyoct Try it!
