### ISSUE TITLE
add projection to table after MaterializedMySQL datebase created

### ISSUE THREAD

**Issue by jzhao20230918** [ClickHouse/ClickHouse#62017]
hello,

Accrodign to the docs that we can add projection to table when creating MaterializedMySQL datebase:

CREATE DATABASE db_name ENGINE = MaterializedMySQL(...)
[SETTINGS ...]
[TABLE OVERRIDE table_name (
    [COLUMNS (
        [col_name [datatype] [ALIAS expr] [CODEC(...)] [TTL expr], ...]
        [INDEX index_name expr TYPE indextype[(...)] GRANULARITY val, ...]
        [PROJECTION projection_name (SELECT <COLUMN LIST EXPR> [GROUP BY] [ORDER BY]), ...]
    )]
    [ORDER BY expr]
    [PRIMARY KEY expr]
    [PARTITION BY expr]
    [SAMPLE BY expr]
    [TTL expr]
), ...]

Is there any way I can add projections to a table after the MaterializedMySQL table is created? I tried to do so by using 'Alter table' but got a error says ‘MaterializedMySQL database does not support ALTER TABLE’. Your help would be appreciated.

**Comment by alexey-milovidov** [comment]
It is not possible.
