### ISSUE TITLE
add pcpu% to system.stack_trace 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#62032]
**Use case**

i see (using `top -H`) that certain thread in clickhouse uses a lot of cpu. To check what it's doing i need to check the system.stack_trace. 

**Describe the solution you'd like**

SELECT ... FROM system.stack_trace ORDER BY pcpu DESC;

**Additional context**

that can be extracted from /proc/clickhouse_pid/task/thread_id/ stat.

Challenge is is the fact that it may require 2 reads from that, to see which thread burn the most of cpu between those 2 reads. 

Maybe we can extract that from thread status, or just expose the raw times instead of calculating pcpu.

P.S. the thread here was out of the queries scope, so query_log etc did not help.

**Comment by alexey-milovidov** [comment]
Not easy - CPU metrics are calculated at certain points in time in the thread, and doing it asynchronously will be harder.
