### ISSUE TITLE
Array join not working on distributed tables

### ISSUE THREAD

**Issue by AndreasSchwalb** [ClickHouse/ClickHouse#62043]
Since version 24.3.1.2672 it is not possible anymore to join an array on a distributed table.

**How to reproduce**
```
CREATE TABLE IF NOT EXISTS default.arrays_test on cluster datascience_cluster
(
    s String,
    arr Array(UInt8)
) 
ENGINE =ReplicatedMergeTree('/clickhouse-final/tables/{shard}/{database}/{table}/{uuid}', '{replica}')
ORDER BY (s)
SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS default.arrays_test_distributed ON CLUSTER datascience_cluster
    AS default.arrays_test
ENGINE = Distributed('datascience_cluster', 'default', 'arrays_test', rand());


INSERT INTO default.arrays_test_distributed
VALUES ('Hello', [1,2]), ('World', [3,4,5]), ('Goodbye', []);


SELECT s, arr, a
FROM default.arrays_test_distributed
ARRAY JOIN arr AS a
WHERE a < 3;
```

* Which ClickHouse server version to use
24.3.1.2672

**Expected behavior**

I would expect to get following result, as I get I from the same query on a cluster with version 24.2.2.71

|s |arr   | a |
|------|------|------|
|Hello   |  [1,2] | 1  |
|Hello   |  [1,2]	| 2 |

**Error message and/or stacktrace**
```
SQL Error [179] [07000]: Code: 179. DB::Exception: ARRAY JOIN expression __table2.arr AS a with duplicate alias a. In scope SELECT __table2.s AS s, __table2.arr AS arr, a AS a FROM default.arrays_test AS __table2 ARRAY JOIN __table2.arr AS a WHERE a < 3. (MULTIPLE_EXPRESSIONS_FOR_ALIAS) (version 24.3.1.2672 (official build))
, server ClickHouseNode [uri=http://xxxxxxxxxxxxxxx:8123/default, options={socket_timeout=300000,use_server_time_zone=false,connect_timeout=50000,use_time_zone=false}]@1152851345
```

**Additional context**
The same query is working on an clickhouse instance with version 24.2.2.71

**Comment by stufently** [comment]
Any news?

**Comment by UnamedRus** [comment]
Works without experimental analyzer 

```
SET allow_experimental_analyzer=0;
```

https://fiddle.clickhouse.com/b0ccd3f6-f0ec-4a38-80d4-9ea10a6f5d73

**Comment by AndreasSchwalb** [comment]
I still get the same failure with version 24.5.1.1763.
I did the same as I discriped in the initial post.

With which version will the bugfix be available?
