### ISSUE TITLE
02115_rewrite_local_join_right_distribute_table is flaky (under analyzer)

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#62063]
CI DB: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSB0ZXN0X25hbWUgTElLRSAnJTAyMTE1X3Jld3JpdGVfbG9jYWxfam9pbl9yaWdodF9kaXN0cmlidXRlX3RhYmxlJScKICAgIEFORCBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgNyBkYXkKLy8gICAgQU5EIHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwpPUkRFUiBCWSBjaGVja19uYW1lLCB0ZXN0X25hbWUsIGNoZWNrX3N0YXJ0X3RpbWU=

CI: https://s3.amazonaws.com/clickhouse-test-reports/61973/a900946fe1b6e41f3756a1fd2091ed4d378d0fd6/stateless_tests__release_.html

**Comment by vdimir** [comment]
Probably related https://s3.amazonaws.com/clickhouse-test-reports/63530/a08a07723bbac42e980e5ff836958e070c69cf4c/stateless_tests__release_.html

Root cause is the bug in `SimpleSquashingChunksTransform` , I'll fix it
