### ISSUE TITLE
ClickHouse process was killed, one node failed

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#62084]
I submit an issue, but it was closed without any suggestion. https://github.com/ClickHouse/ClickHouse/issues/62080

ClickHouse process was killed, one node failed. After execute "clickhouse start", work fine.

This issue occurred twice.  Any suggestion? How to fix it? Any caused reason? Thanks!

ClickHouse Version: 22.3.6.5

![image](https://github.com/ClickHouse/ClickHouse/assets/79344970/ddcf677b-b8b1-4c9a-947d-49e9d199237f)

![image](https://github.com/ClickHouse/ClickHouse/assets/79344970/edc1c42e-d326-4fc3-a69c-7039f2c824b6)

**Comment by den-crane** [comment]
> Any suggestion? 
>22.3.6.5

You have to upgrade. 22.3 is out of support. Supported versions are 23.8, 24.1, 24.2, 24.3.

**Comment by alexey-milovidov** [comment]
@taotaizhu-pw To fix the problem, run:
```
curl https://clickhouse.com/ | sh
sudo ./clickhouse install
```
