### ISSUE TITLE
Something on the photo of my computer screen (obsolete version)

### ISSUE THREAD

**Issue by taotaizhu-pw** [ClickHouse/ClickHouse#62080]
ClickHouse process was killed, one node failed. After execute "clickhouse start", work fine.

This issue occurred twice. 

ClickHouse Version: 22.3.6.5

![image](https://github.com/ClickHouse/ClickHouse/assets/79344970/49a8de6c-846e-4f5a-9b80-e4d06fa66262)

![image](https://github.com/ClickHouse/ClickHouse/assets/79344970/96b870e5-ec82-4797-a54b-2ca6c762b9ee)

**Comment by taotaizhu-pw** [comment]
Any suggestoin? how to fix it?

**Comment by den-crane** [comment]
You have to upgrade. 22.3 is out of support. Supported versions are 23.8, 24.1, 24.2, 24.3.
