### ISSUE TITLE
Memory optimization for GROUP BY x in a MergeTree ordered by x

### ISSUE THREAD

**Issue by guillaumematheron** [ClickHouse/ClickHouse#62093]
**Describe the situation**
In a MergeTree table, grouping by fields that match the table sort order uses more memory than necessary.

**How to reproduce**

In a de-duplication scenario, we may have a table that looks like:
```
CREATE TABLE consumption
(
    `customer_id` Int32,
    `start_date` DateTime,
    `value` Float32
)
ENGINE = MergeTree
ORDER BY (customer_id, start_date)
```

We can then populate it with some data including duplicates:
```
insert into consumption (customer_id, start_date, value)
select
    customer.number AS customer_id,
    toDateTime('2023-01-01')
        + interval (days.number + floor(randUniform(1,5))) DAYS AS start_date,
    randNormal(100,5) AS value
from numbers(10000) customer
cross join numbers(10000) AS days;
```

Intuitively, it should be fairly easy to retrieve de-duplicated data from this table, since duplicates are always stored next to each other:
```
select customer_id, start_date, any(value)
from consumption
group by customer_id, start_date
```

However, this query consumes an unexpectedly large amount of RAM (I could not quite get it to crash in our MWE with 100M rows, but in our production environment with 10B rows similar queries runs out of memory very quickly).

Some side-effects are that even with a `limit` statement the full table must be read.

This can also be verified using a query that returns less data:

```
select n, count(*)
from (
    select count(*) AS n
    from consumption
    group by customer_id, start_date
) group by n;
```
> Elapsed: 17.438s Read: 168,365,268 rows (2.44 GB)
> RAM usage peaked at around 4 GiB

A workaround is to use window functions to detect duplicates without performing a group by:

```
select * from (
    select 
        customer_id,
        start_date,
        count(*) over (partition by customer_id, start_date) AS n,
        row_number() over (partition by customer_id, start_date) AS rn
    from consumption
    order by customer_id, start_date
)
where rn = 1
```
> Elapsed: 7.997s Read: 100,000,000 rows (800.00 MB)
> RAM usage peaked at about 4 MiB

* The MWE above was run on clickhouse cloud v24.1
* All default settings

**Comment by nickitat** [comment]
https://clickhouse.com/docs/en/operations/settings/settings#optimize_aggregation_in_order
