### ISSUE TITLE
Boolean values are broken with the http interface

### ISSUE THREAD

**Issue by cpcloud** [ClickHouse/ClickHouse#62108]
**Describe what's wrong**

Boolean values aren't usable via the http interface anymore.

**Does it reproduce on the most recent release?**

Yes.

**How to reproduce**

* Which ClickHouse server version to use

```
❯ clickhouse client --query='select version()'
24.3.1.2672
```

* Which interface to use, if it matters

The http interface.

* Queries to run that lead to an unexpected result: see below

Here's a script that fails:

```bash
#!/usr/bin/env bash

set -euxo pipefail

clickhouse client --query='select true' > data.csv

curl -F 't=@data.csv' 'http://localhost:8123/?query=SELECT+*+FROM+t&t_structure=a+Bool&t_format=CSV'
```

**Expected behavior**

I would expect the output to be `true`.

**Error message and/or stacktrace**

```
Code: 378. DB::Exception: Data type Bool cannot have arguments. (DATA_TYPE_CANNOT_HAVE_ARGUMENTS) (version 24.3.1.2672 (official build))
```

**Comment by alexey-milovidov** [comment]
@canhld94, PTAL
