### ISSUE TITLE
Clickhouse playground fails with Code: 307. `DB::Exception`

### ISSUE THREAD

**Issue by romiras** [ClickHouse/ClickHouse#62110]
I was trying to play with ClickHouse using https://play.clickhouse.com/play?user=play
Querying with simple query fails with code 307 after waiting a while.

## Expected behavior

Just return 5 records.

## Error message and/or stacktrace

A query was:
```sql
SELECT * FROM github_events order by file_time DESC limit 5
```

Response was:
```
Code: 307. DB::Exception: Limit for rows or bytes to read exceeded, max bytes: 931.32 GiB, current bytes: 931.48 GiB: While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (TOO_MANY_BYTES) (version 24.3.1.266 (official build))
```

> version 24.3.1.266 (official build)

Another query that fails with almost same error (due to different number of bytes) also:
```sql
SELECT * FROM github_events order by created_at DESC limit 5
```

![image](https://github.com/ClickHouse/ClickHouse/assets/298544/3998f3ff-423b-45c9-b9c8-f6a59d77a9cf)

Works well with query:
```sql
SELECT * FROM github_events LIMIT 5
```

![image](https://github.com/ClickHouse/ClickHouse/assets/298544/410d42c5-a463-42da-9e11-52c8a5fe0722)

**Comment by alexey-milovidov** [comment]
This is normal behavior: the public user has restrictions set up: https://clickhouse.com/docs/knowledgebase/about-quotas-and-query-complexity

This is needed to provide the Playground publicly without authentication.

**Comment by alexey-milovidov** [comment]
This question is irrelevant to the ClickHouse database because you can configure it with arbitrary users, authentication, and access control, with or without any restrictions on query complexity, workload isolation, and resource quotas.

**Comment by romiras** [comment]
@alexey-milovidov
> This question is irrelevant to the ClickHouse database

I wonder how did you came to this conclusion?
Error message was thrown:
> ... (TOO_MANY_BYTES) (version 24.3.1.266 (official build))

I can see clearly a latest tag [v24.3.1.2672-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v24.3.1.2672-lts) in list of tags.

> because you can configure it with arbitrary users, authentication, and access control, with or without any restrictions on query complexity, workload isolation, and resource quotas.

Though it still might be a misconfiguration issue. But still, not a very pleasant kind of error to show to newcomers. Especially when no clear hint what user did wrong.

**Comment by alexey-milovidov** [comment]
You are confusing the open-source ClickHouse DBMS with the repository https://github.com/ClickHouse/ClickHouse/
and ClickHouse Playground, which is one of hundreds of thousands of services made with it.

**Comment by alexey-milovidov** [comment]
ClickHouse Playground is configured in a way that prevents you from running queries that will scan more than 1 TiB of data. It is a good demonstration of features that you can configure in ClickHouse to make it refuse your queries.

**Comment by romiras** [comment]
@alexey-milovidov
a query looks quite innocent:
```sql
SELECT * FROM github_events order by file_time DESC limit 5
```
I wonder why CH, even configured for playground , should ever scan 1 TiB of data. Maybe I miss something about architecture/design. Could you share?

**Comment by alexey-milovidov** [comment]
If `file_time` is not the table's ORDER BY key, it will have to read the file_time column, partially sort it to find the latest five records, and read other columns.

**Comment by alexey-milovidov** [comment]
You can replace with the following query:
```
SELECT * FROM github_events WHERE file_time = (SELECT max(file_time) FROM github_events) LIMIT 5
```

And it takes two seconds: https://play.clickhouse.com/play?user=play#U0VMRUNUICogRlJPTSBnaXRodWJfZXZlbnRzIFdIRVJFIGZpbGVfdGltZSA9IChTRUxFQ1QgbWF4KGZpbGVfdGltZSkgRlJPTSBnaXRodWJfZXZlbnRzKSBMSU1JVCA1

It is not a direct equivalent because it assumes that there are at least five records in the latest file.

**Comment by alexey-milovidov** [comment]
@romiras If you are interested, you can explore another public playground, which I created a few days ago on another dataset - it is very nice to explore, and can scan way more data: https://adsb.exposed/
