### ISSUE TITLE
Cannot run unit test on MacBook M1 Pro.

### ISSUE THREAD

**Issue by RinChanNOWWW** [ClickHouse/ClickHouse#62128]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

Run unit test failed on MacBook M1 Pro.

```
$ build/src/unit_tests_dbms --help          
libc++abi: terminating due to uncaught exception of type Poco::SystemException: System exception
[1]    24401 abort      build/src/unit_tests_dbms --help
```

**How to reproduce**

* Which ClickHouse server version to use

23.8.9.54

Build `unit_tests_dbms` target and run.

**Comment by thevar1able** [comment]
https://pastila.nl/?00c2a140/ebc724e1c066cded9ca6eb60474c530f#gWWGD9xzuRpoVMlXVkiIyQ==

@RinChanNOWWW does building with `-DENABLE_JEMALLOC=0` works for you?

**Comment by RinChanNOWWW** [comment]
No.

It throws an exception in *base/poco/Foundation/include/Poco/Mutex_POSIX.h*:

```cpp
inline void MutexImpl::lockImpl()
{
    if (pthread_mutex_lock(&_mutex))
        throw SystemException("cannot lock mutex");
}
```
