### ISSUE TITLE
FileCache: Cannot fit <> in cache, but collection of eviction candidates succeeded with no candidates (in SLRU eviction policy)

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#62145]
Report: https://s3.amazonaws.com/clickhouse-test-reports/62135/b2e764f63326e22d3cb306bd0009108b1a955934/stress_test__tsan_.html

Full log line:
```
2024.04.01 16:05:11.580910 [ 3188 ] {} <Fatal> : Logical error: 'Cannot fit 1048576 in cache, but collection of eviction candidates succeeded with no candidates. This is a bug. Queue entry type: SLRU_Probationary. Cache info: total size 66790794/67108864, elements 127/10000000, probationary queue size 46902549/46976205, elements 102/7000000, protected queue size 19888245/20132659, elements 25/3000000'.
```

I don't see any other errors from this specific thread.

cc @kssenii I see it was also notified in the PR (https://github.com/ClickHouse/ClickHouse/pull/61163#discussion_r15446511809) but better to have some ticket to point and reference in case we need it

**Comment by kssenii** [comment]
Do not understand the reason yet, added more logging https://github.com/ClickHouse/ClickHouse/pull/62160.
