### ISSUE TITLE
Strange behavior with 2 equal aliases. May be bug or may be fixed earlier bug )

### ISSUE THREAD

**Issue by alexeyrusnak** [ClickHouse/ClickHouse#62148]
Strange behavior with 2 equal aliases. May be bug or may be fixed earlier bug )

`select * from (select 'test' some_col, 'test' some_col)`

After 24.2.2.71 version gives two column result
https://fiddle.clickhouse.com/d84fe165-8e44-46fe-8d20-da3084c2777d

Before 24.2.2.71 version gives one column result
https://fiddle.clickhouse.com/8a9b3b0e-cb6e-47f7-bab3-2de1ed514a72

**Comment by nikitamikhaylov** [comment]
Yes, it was a wrong behaviour which got fixed with a new Analyzer. Now ClickHouse behaves similarly to Postgres.

https://www.db-fiddle.com/f/w9G2aMg9fazZcHX4ErfrAP/0
