### ISSUE TITLE
UNKNOWN_IDENTIFIER: Using identifier cannot be resolved from left table expression if left column is alias

### ISSUE THREAD

**Issue by alexeyrusnak** [ClickHouse/ClickHouse#62140]
Hi

`
CREATE TABLE test_1 (col_1 String) ENGINE=Memory;
CREATE TABLE test_2 (col_2 String) ENGINE=Memory;

select col_1 as col_2 from test_1 all left join test_2 using col_2;
`

When col_2 is alias on left table we have error UNKNOWN_IDENTIFIER. It reproduces on all versions after 24.2.2.71

Latest version - error
https://fiddle.clickhouse.com/9611fa2c-356a-46b0-88c6-2ed1a033a749

24.2.2.71 - ok
https://fiddle.clickhouse.com/a621210c-f350-43ae-8b24-fbfb3aae92d3

**Comment by SaltTan** [comment]
related 
* #56814

**Comment by den-crane** [comment]
We discussed it, the new behaviour is correct. `Join` "works" before `Select` section. 

It should be like this 

```
select * from (
select col_1 as col_2 
  from test_1 ) as t
  all left join test_2 using col_2;
```

**Comment by SaltTan** [comment]
I found a setting for this: `analyzer_compatibility_join_using_top_level_identifier`
https://fiddle.clickhouse.com/e1441d87-08fc-4aa2-8dba-f7a1fe21a3ba
```
name        | analyzer_compatibility_join_using_top_level_identifier                                                                                                                                           
description | Force to resolve identifier in JOIN USING from projection (for example, in `SELECT a + 1 AS b FROM t1 JOIN t2 USING (b)` join will be performed by `t1.a + 1 = t2.b`, rather then `t1.b = t2.b`).
```

**Comment by Algunenano** [comment]
As @den-crane says, the current behaviour is the proper one. `analyzer_compatibility_join_using_top_level_identifier` can be used as a workaround, but it's recommended to write more standard SQL
