### ISSUE TITLE
sumMap for record but not aggregate

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#6215]
Hi
  I have a table named test,the data like below
```
id payMode.code  payMode.fee name ...
1  [100,100,200]  [10,20,30] name1 ...
2  [100,200,100]  [10,20,30] name2 ...
```
now I want get the result 
```
id payMode.code  payMode.fee name ...
1  [100,200]  [30,30] name1 ...
2  [100,200]  [40,20] name2 ...
```

I want to sumMap the payMode.code for every record using 
```
select summap(payMode.code,payMode.fee) as payMode,id,name,... from test
```
but it get the exception id,name is not in aggregate, is there any way sumMap for every record but not aggregate.
I know I can use sumMap and group by to complete it ,but it's more complicated

**Comment by filimonov** [comment]
Alternaitve is smth like that:
```
select ..., arrayReduce( 'sumMap', [payMode.code],[payMode.fee] ), ... 
```

Will work properly on real table, but please be careful - i've found that there is some bug in processing constant parameters for that type of function call combination (see #6242).

**Comment by peaksnail** [comment]
👍

**Comment by peaksnail** [comment]
Hi
I find that when payMode.fee equals [0], it will get the empty array

sql like
```
select arrayReduce('sumMap', array([100]), array([0])) 
```
return 
```
([],[]) 
```

I I want get the result 
```
([100],[0]) 
```

**Comment by blinkov** [comment]
@peaksnail, do you have any further questions?
