### ISSUE TITLE
Bug loading | pipe separated file.

### ISSUE THREAD

**Issue by ryanhamilton** [ClickHouse/ClickHouse#62174]
Selecting CustomSeparatedWithNames with | pipe separate does NOT work as expected only one column returned.

```
head a.psv
b|c
10|ppp
11|ddd
$ head a.csv
b,c
10,ppp
11,ddd>SELECT * FROM file('/home/rayman/clickhouse/user_files/a.csv', CSV);
2 rows returned - This WORKS
>
SET format_custom_escaping_rule  = 'Raw';
SET format_custom_field_delimiter = '|';
SELECT * FROM file('/home/rayman/clickhouse/user_files/a.psv', CustomSeparatedWithNames);
2 rows returned. THis only returns one column.????? The delimiter isn't working
```

Version: Starting ClickHouse 24.4.1.174 (revision: 54485, git hash: 6b9b597051636
Client: https://www.timestored.com/qstudio/

![image](https://github.com/ClickHouse/ClickHouse/assets/7273208/ddbe4bca-d1aa-440c-bce5-a0023453cbf4)

This works:

```
SELECT * FROM file('a.psv', CSVWithNames) SETTINGS format_csv_delimiter = '|', format_custom_escaping_rule = 'Raw'
```

This does NOT work:

```
SELECT * FROM file('a.psv', CustomSeparatedWithNames) SETTINGS format_csv_delimiter = '|', format_custom_escaping_rule = 'Raw'
```

**Comment by Avogar** [comment]
It's not a bug, it's expected, because `Raw` escaping rule (the same as `Escaped`) expect the value to end with `\t` or `\n` (just likt in `TSV/TSVRaw`). You can use CSV:
```
avogar-dev :) SELECT * FROM file('a.psv', CustomSeparated) settings format_custom_field_delimiter='|', format_custom_escaping_rule='CSV'

SELECT *
FROM file('a.psv', CustomSeparated)
SETTINGS format_custom_field_delimiter = '|', format_custom_escaping_rule = 'CSV'

Query id: 08cb61fb-139e-425b-8b5c-60a2ab0b5c3e

   ┌──b─┬─c───┐
1. │ 10 │ ppp │
2. │ 11 │ ddd │
   └────┴─────┘
```

This behaviour may be confusing, but for now for escaping rules `Raw` and `Escaped` we cannot parse value until custom delimiter (it may be improved in future as it's done for CSV).
