### ISSUE TITLE
Flaky statefull tests with `read_split_ranges_..._injection_probability`

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#62252]
[flaky](https://play.clickhouse.com/play?user=play#CgoKU0VMRUNUCiAgICBjb3VudCgpIG92ZXIgKFBBUlRJVElPTiBCWSAoY29tbWl0X3NoYSwgY2hlY2tfbmFtZSwgY2hlY2tfc3RhcnRfdGltZSkpIGFzIGMsIAogICAgc3Vic3RyKGNvbW1pdF9zaGEsIDEsOSkgYXMgc2hhLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDcgREFZCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyBMSUtFICdGJScKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgdGVzdF9uYW1lIGxpa2UgJyVsb3lhbHR5JScKT1JERVIgQlkgY2hlY2tfbmFtZSwgY2hlY2tfc3RhcnRfdGltZSwgdGVzdF9uYW1l) `00062_loyalty` / `00063_loyalty_joins` / `00065_loyalty_with_storage_join`

Flaky with both new and old analyzer. 
Reproduced with set `merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0.5, max_threads = 13`

**Comment by vdimir** [comment]
Ref https://github.com/ClickHouse/ClickHouse/pull/62268

**Comment by nickitat** [comment]
loyalty* tests are not fixed unfortunately by my PRs. right now I'm able to reliably reproduce failures with the following settings: `set max_threads=1,allow_prefetched_read_pool_for_remote_filesystem=0;` with and without settings randomisation.

**Comment by vdimir** [comment]
Ok, it works with `max_threads=1` and require `max_threads = 13` to fail, so perhaps root cause it different..

**Comment by nickitat** [comment]
same for 00171_grouping_aggregated_transform_bug

**Comment by nickitat** [comment]
@vdimir are looking at this problem already?

**Comment by tavplubix** [comment]
> same for 00171_grouping_aggregated_transform_bug with `set max_threads=1,allow_prefetched_read_pool_for_remote_filesystem=0;` and `--no-random-settings` fails in 100% cases

Also `00060_move_to_prewhere_and_sets`: https://github.com/ClickHouse/ClickHouse/issues/62460

**Comment by vdimir** [comment]
> @vdimir are looking at this problem already?

No, not at the moment. Let me know if you would like me to investigate it further.

**Comment by nickitat** [comment]
> > @vdimir are looking at this problem already?
> 
> No at the moment. Let me know if you would like me to investigate it further.

I started looking at it and just didn't want to step on your toes

**Comment by nickitat** [comment]
guilty PR is #61551
