### ISSUE TITLE
Incorrectly see the error: "There is no supertype for types AggregateFunction(max, Nullable(IPv6)), String", caused by UNION.

### ISSUE THREAD

**Issue by blaird1923** [ClickHouse/ClickHouse#62269]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
We're not able to aggregate while using this union.

**How to reproduce**
Instructions included.
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
There are samples which should all succeed.
The last sample fails.
It appears that Clickhouse is confused about where to get
this srcip_state column from.
It's complaining that because of the union, it might be a String.

[repro_instructions.txt](https://github.com/ClickHouse/ClickHouse/files/14859358/repro_instructions.txt)
[repro_logfile.log](https://github.com/ClickHouse/ClickHouse/files/14859359/repro_logfile.log)

**Error message and/or stacktrace**

**Additional context**

**Comment by Algunenano** [comment]
ClickHouse (following SQL standard) matches the columns of UNION queries in order, not by name.

What you need is something like:

```
SELECT
    id,
    maxMerge(srcip_state) AS srcip
FROM
(
    SELECT
        id,
        '' AS virus,
        srcip_state
    FROM
    (
        SELECT *
        FROM
        (
            SELECT *
            FROM test_a
        ) AS t
    ) AS t
    UNION ALL
    SELECT *
    FROM
    (
        SELECT *
        FROM test_b
    ) AS t
) AS t
GROUP BY
    id;
```

I remember there were some other databases that had an extra modified `UNION $SOMETHING` that instead matched by name and not by order, but I can't find it right now and CH doesn't have it.

**Comment by Algunenano** [comment]
BTW, the union by name in other databases that I was looking for is [`UNION CORRESPONDING`](https://blog.jooq.org/a-rarely-seen-but-useful-sql-feature-corresponding/)
