### ISSUE TITLE
MaterializedPostgreSQL replicates only one table

### ISSUE THREAD

**Issue by erwannbst** [ClickHouse/ClickHouse#62279]
**Describe what's wrong**
Hello, I have a postgresql database I want to replicate with :

```
SET allow_experimental_database_materialized_postgresql=1;
CREATE DATABASE IF NOT EXISTS database_materialized
ENGINE = MaterializedPostgreSQL('localhost:6666', 'user', 'postgres', 'passwd')
SETTINGS materialized_postgresql_tables_list = 'table1,table2,table3,table4'
```

it works well for one of the table which has 150 000 000 rows:

```
$ clickhouse client -q "SHOW TABLES from database_materialized"
$ table2
```

But the other tables doesnt show up, here is what I have in the logs :

> 2024.04.04 09:55:47.007363 [ 187198 ] {} <Debug> PostgreSQLConnection: New connection to localhost:6666
> 2024.04.04 09:55:47.014707 [ 187198 ] {} <Debug> PostgreSQLReplicationHandler: Publication exists: true, is attach: true
> 2024.04.04 09:55:47.040453 [ 187198 ] {} <Trace> DatabaseMaterializedPostgreSQL (database_materialized): Loaded 4 tables. Starting synchronization
> 2024.04.04 09:55:47.112788 [ 187198 ] {} <Debug> PostgreSQLConnection: New connection to localhost:6666
> 2024.04.04 09:55:47.120427 [ 187198 ] {} <Debug> PostgreSQLReplicationHandler: Using existing publication (database_ch_publication) version
> 2024.04.04 09:55:47.129768 [ 187198 ] {} <Debug> PostgreSQLReplicationHandler: Replication slot database already exists (active: false). Restart lsn position: 8E3B/CB259268, confirmed flush lsn: 8E3B/CB2592A0
> 2024.04.04 09:55:47.161398 [ 187198 ] {} <Error> void DB::PostgreSQLReplicationHandler::startSynchronization(bool): Code: 60. DB::Exception: Table database_materialized.table1 does not exist. Maybe you meant database_materialized.table2?: while loading table database.table1. (UNKNOWN_TABLE), Stack trace (when copying this message, always include the lines below)
> 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbcedbb
> 1. DB::Exception::Exception<String, String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&, String&&) @ 0x000000000770b3a1
> 2. DB::IDatabase::getTable(String const&, std::shared_ptr<DB::Context const>) const @ 0x0000000010207041
> 3. DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::shared_ptr<DB::Context const>, std::optional<DB::Exception>*) const @ 0x0000000010553dd6
> 4. DB::DatabaseCatalog::getTable(DB::StorageID const&, std::shared_ptr<DB::Context const>) const @ 0x000000001055d2c9
> 5. DB::StorageMaterializedPostgreSQL::getNested() const @ 0x000000001027038c
> 6. DB::PostgreSQLReplicationHandler::startSynchronization(bool) @ 0x000000001025746e
> 7. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::DatabaseMaterializedPostgreSQL::DatabaseMaterializedPostgreSQL(std::shared_ptr<DB::Context const>, String const&, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, bool, String const&, String const&, postgres::ConnectionInfo const&, std::unique_ptr<DB::MaterializedPostgreSQLSettings, std::default_delete<DB::MaterializedPostgreSQLSettings>>)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001024cb31
> 8. DB::BackgroundSchedulePool::threadFunction() @ 0x000000000fd9f367
> 9. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0>(DB::BackgroundSchedulePool::BackgroundSchedulePool(unsigned long, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, StrongTypedef<unsigned long, CurrentMetrics::MetricTag>, char const*)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000fda04d3
> 10. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000cc7d9ed
> 11. ? @ 0x00007f20f5722ac3
> 12. ? @ 0x00007f20f57b4850
>  (version 24.3.2.23 (official build))

Here are the column types of the Postgresql table1 :

> integer
>  timestamp with time zone
>  character varying
>  text
>  integer
>  boolean
>  ARRAY
>  jsonb
>  double precision

I also tried to manually attach the table :
`clickhouse client -q "ATTACH TABLE database_materialized.table1"`
 
But I get this error :
> 2024.04.04 11:04:29.020784 [ 186881 ] {6d7ccac3-cdf3-413e-ad24-17f7232d5bb1} <Debug> executeQuery: (from 127.0.0.1:44784) ATTACH TABLE database_materialized.table1 (stage: Complete)
> 2024.04.04 11:04:29.020849 [ 186881 ] {6d7ccac3-cdf3-413e-ad24-17f7232d5bb1} <Trace> ContextAccess (default): Access granted: CREATE TABLE ON database_materialized.table1
> 2024.04.04 11:04:29.085042 [ 186881 ] {6d7ccac3-cdf3-413e-ad24-17f7232d5bb1} <Debug> PostgreSQLConnection: New connection to localhost:6666
> 2024.04.04 11:04:29.120887 [ 186881 ] {6d7ccac3-cdf3-413e-ad24-17f7232d5bb1} <Debug> database_materialized.table1 (0e9f42c1-44ee-44df-8c7b-ab58c76e6ea0): Loading data parts
> 2024.04.04 11:04:29.121410 [ 186881 ] {6d7ccac3-cdf3-413e-ad24-17f7232d5bb1} <Debug> database_materialized.table1 (0e9f42c1-44ee-44df-8c7b-ab58c76e6ea0): There are no data parts
> 2024.04.04 11:04:29.128601 [ 186881 ] {6d7ccac3-cdf3-413e-ad24-17f7232d5bb1} <Error> executeQuery: Code: 620. DB::Exception: PostgreSQL replication initialization did not finish successfully. Please check logs for error messages. (QUERY_NOT_ALLOWED) (version 24.3.2.23 (official build)) (from 127.0.0.1:44784) (in query: ATTACH TABLE database_materialized.table1), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbcedbb
> 1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x0000000007668f23
> 2. DB::PostgreSQLReplicationHandler::addTableToReplication(DB::StorageMaterializedPostgreSQL*, String const&) @ 0x0000000010268562
> 3. DB::DatabaseMaterializedPostgreSQL::attachTable(std::shared_ptr<DB::Context const>, String const&, std::shared_ptr<DB::IStorage> const&, String const&) @ 0x0000000010249bc6
> 4. DB::DatabaseMaterializedPostgreSQL::createTable(std::shared_ptr<DB::Context const>, String const&, std::shared_ptr<DB::IStorage> const&, std::shared_ptr<DB::IAST> const&) @ 0x0000000010248e40
> 5. DB::InterpreterCreateQuery::doCreateTable(DB::ASTCreateQuery&, DB::InterpreterCreateQuery::TableProperties const&, std::unique_ptr<DB::DDLGuard, std::default_delete<DB::DDLGuard>>&) @ 0x0000000010b7e6e5
> 6. DB::InterpreterCreateQuery::createTable(DB::ASTCreateQuery&) @ 0x0000000010b73603
> 7. DB::InterpreterCreateQuery::execute() @ 0x0000000010b842cf
> 8. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x00000000112705c2
> 9. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x000000001126bf9a
> 10. DB::TCPHandler::runImpl() @ 0x0000000012351d84
> 11. DB::TCPHandler::run() @ 0x000000001236d099
> 12. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9bef2
> 13. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9cd39
> 14. Poco::PooledThread::run() @ 0x0000000014d954a1
> 15. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d93a3d
> 16. ? @ 0x00007f20f5722ac3
> 17. ? @ 0x00007f20f57b4850

**Expected behavior**

I should have all 4 tables replicated

Clickhouse version :

> clickhouse-client/unknown,now 24.3.2.23 amd64 [installed]
> clickhouse-common-static-dbg/unknown 24.3.2.23 amd64
> clickhouse-common-static/unknown,now 24.3.2.23 amd64 [installed,automatic]
> clickhouse-keeper-dbg/unknown 24.3.2.23 amd64
> clickhouse-keeper/unknown 24.3.2.23 amd64
> clickhouse-server/unknown,now 24.3.2.23 amd64 [installed]
> python3-clickhouse-driver-doc/jammy 0.2.3-1ubuntu1 all
> python3-clickhouse-driver/jammy 0.2.3-1ubuntu1 amd64

**Comment by erwannbst** [comment]
Hello @kssenii, I noticed it's still open and wanted to see if there's anything I can do to help move it along or provide additional information. Please let me know if there's anything I can assist with to speed up the process.

**Comment by kssenii** [comment]
> void DB::PostgreSQLReplicationHandler::startSynchronization(bool): Code: 60. DB::Exception: Table database_materialized.table1 does not exist. Maybe you meant database_materialized.table2?: while loading table database.table1. (UNKNOWN_TABLE)

Is there the same exception message with `table3` and `table4`?
