### ISSUE TITLE
Ability to remove CODEC from a column (DDL).

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#6227]
alter table XXX modify column YYYY ... no codec;

or alter table XXX modify column YYYY ... codec();

**Comment by CurtizJ** [comment]
You can set `CODEC(NONE)` for column and data will be stored without compression. Is it actually what do you want?

**Comment by den-crane** [comment]
I want to remove CODEC from the column and use default compression from config.xml

**Comment by orloffv** [comment]
I would also like to be able to reset to default

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/14049 ALTER TABLE compress_table MODIFY COLUMN value3 CODEC(Default);
