### ISSUE TITLE
max_execution_speed setting does not work if SAMPLE is used

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6228]
CC @zhang2014 

```
example.yandex.ru :) SET max_execution_speed = 1000000

SET max_execution_speed = 1000000

Ok.

0 rows in set. Elapsed: 0.001 sec. 

example.yandex.ru :) SELECT ...

1 rows in set. Elapsed: 10.360 sec. Processed 318.26 million rows, 57.65 GB (30.72 million rows/s., 5.56 GB/s.)
```

**Comment by alexey-milovidov** [comment]
Though it works perfectly for system.numbers.
But I have complex Merge table of MergeTree tables.

**Comment by alexey-milovidov** [comment]
It doesn't work if SAMPLE is specified.

**Comment by alexey-milovidov** [comment]
There is no upper bound on sleep time. I think it should be no more than one second.
Otherwise it's too easy to hang a query with `SET max_execution_speed = 1`.

**Comment by nvartolomei** [comment]
On first look this almost the same as #5732, speed is throttled only for queries that read QueryProcessingStage::Complete.

I have a branch somewhere which defines new setting `leaf_max ...`. However I'd propose to change the meaning of current settings and apply them always.

https://github.com/ClickHouse/ClickHouse/blob/2133492598d46650937c706f90204d7ef57dc9b2/dbms/src/Interpreters/InterpreterSelectQuery.cpp#L1781-L1788

Another idiosyncrasy is that behaviour also changes when distributed_group_by_no_merge is set, 🤦‍♂ .

**Comment by alexey-milovidov** [comment]
I checked that it works perfectly:

```
SET max_execution_speed = 1000000, timeout_before_checking_execution_speed = 0.001;
SELECT count() FROM test.hits SAMPLE 1/2

SELECT count()
FROM test.hits
SAMPLE 1 / 2

┌─count()─┐
│ 4392010 │
└─────────┘

1 rows in set. Elapsed: 8.234 sec. Processed 8.23 million rows, 138.90 MB (999.14 thousand rows/s., 16.87 MB/s.)
```

**Comment by alexey-milovidov** [comment]
For merge tables as well:

```
SELECT count() FROM merge(test, '^hits$') SAMPLE 1/2
```

**Comment by alexey-milovidov** [comment]
I have added a test in #11296
