### ISSUE TITLE
Replace partition when tables have the different storage policy is not documented

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#62283]
As of version 24.3, it is possible to replace a partition when the source and destination tables have different storage policies. However, this information is not documented.
https://clickhouse.com/docs/en/sql-reference/statements/alter/partition#replace-partition

**Comment by alsugiliazova** [comment]
@nikitamikhaylov, was that intended? [Here](https://github.com/ClickHouse/ClickHouse/pull/60112), only `attach partition` is mentioned. Perhaps allowing `replace` with different storage policies was a side effect of this PR because `attach partition` and `replace partition` partially share the same code. I am asking because I didn't see anything about `replace partition` in changelog. No problem about documenting it.

**Comment by tavplubix** [comment]
The feature has been reverted: https://github.com/ClickHouse/ClickHouse/pull/62549

**Comment by Unalian** [comment]
Replace partitions when tables have different storage policies are not allowed now. However, attaching parts from different disks is permitted through this pr: https://github.com/ClickHouse/ClickHouse/pull/63087.
