### ISSUE TITLE
Allow querying Distributed/Merge tables that have supertype columns of underlying tables

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#6229]
## Example 1:

```sql
CREATE TABLE m
(
    `v` UInt8
)
ENGINE = MergeTree()
PARTITION BY tuple()
ORDER BY v;

CREATE TABLE d
(
    `v` UInt16
)
ENGINE = Distributed('dev', '', m, rand());

SELECT * FROM d; -- this should work, at the moment it throws an exception
-- Code: 171. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Block structure mismatch in UNION stream: different types:
-- v UInt16 UInt16(size = 0)
-- v UInt8 UInt8(size = 0).
```

## Example 2:

```sql
CREATE TABLE m
(
    `v` Enum8('a' = 1, 'b' = 2)
)
ENGINE = MergeTree()
PARTITION BY tuple()
ORDER BY v;

CREATE TABLE d
(
    `v` Enum8('a' = 1)
)
ENGINE = Distributed('dev', '', m, rand());

SELECT * FROM d; -- this should work, throws an exception at the moment
-- Code: 171. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Block structure mismatch in UNION stream: different types:
-- v Enum8('a' = 1) Int8(size = 0)
-- v Enum8('a' = 1, 'b' = 2) Int8(size = 0).

-- ^ enums are unusable in production because of this
```

**Comment by richardartoul** [comment]
Is there any documentation on how supertypes work? What are they currently used for? My understanding was that they exist only to resolve situations like this so I'm confused as to why this would not be supported.

If these columns were part of the same table would it work then?

**Comment by alexey-milovidov** [comment]
@KochetovNicolai forgot about this task but it is fixed nevertheless.

**Comment by alexey-milovidov** [comment]
@richardartoul 
> My understanding was that they exist only to resolve situations like this

You're absolutely right. Supertype is used when we have to convert values of multiple types to one common type.

**Comment by nvartolomei** [comment]
@alexey-milovidov I see `SELECT v FROM d ORDER BY v; -- { clientError 36 }` in the test and this issue closed, are you saying that enum's work as expected and that you are not planning to change their behaviour? Do you have suggestions for workarounds on how to make 0-downtime ALTERs in this case?
