### ISSUE TITLE
Usage of a dynamic `LIMIT` results in query throwing

### ISSUE THREAD

**Issue by kothiga** [ClickHouse/ClickHouse#62294]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

I would like to preface this as I am unsure if the current behavior in 24.3 is intentional. When executing a query where the `LIMIT` is dynamic (i.e., found from a subquery) we get an error thrown which had previously not occurred.

Inspecting the regions of the code where this occurs and recent pull requests from the last month, I had not encountered anything that would suggest to me an intentional change to restrict this behavior. With this said, the error that gets thrown seems related to me enough that this may be intentional, however, I thought it was worth asking before digging deeper.

> A clear and concise description of what works not as it is supposed to.

I have a query that looks like

``` sql
SELECT *
FROM Customers
ORDER BY Age DESC NULLS LAST
LIMIT (
    SELECT tuple(*)
    FROM
    (
        SELECT count() AS Count
        FROM
        (
            SELECT *
            FROM Customers
            WHERE Age = 33
        )
    )
    LIMIT 1
).1;
```

Which on previous versions of CH ([24.3.1](https://fiddle.clickhouse.com/973e1785-f962-49a4-9df5-fe2e5ed053a6)) execute, however, on newer versions ([24.3.1.2672](https://fiddle.clickhouse.com/a7e9f85c-0a3c-4105-8c25-ae7b8e32147d), [24.3.2.23](https://fiddle.clickhouse.com/3bcbc895-79d8-4f31-b3df-4c5d3b68ad5b)) throws with

```
Received exception from server (version 24.3.2):
Code: 440. DB::Exception: Received from localhost:9000. DB::Exception: LIMIT expression must be constant with numeric type. Actual (SELECT tuple(*) FROM (SELECT count() AS Count FROM (SELECT * FROM Customers WHERE Age = 33)) LIMIT 1).1. In scope SELECT * FROM Customers ORDER BY Age DESC NULLS LAST LIMIT (SELECT tuple(*) FROM (SELECT count() AS Count FROM (SELECT * FROM Customers WHERE Age = 33)) LIMIT 1).1. (INVALID_LIMIT_EXPRESSION)
(query: SELECT *
FROM Customers
ORDER BY Age DESC NULLS LAST
LIMIT (
    SELECT tuple(*)
    FROM
    (
        SELECT count() AS Count
        FROM
        (
            SELECT *
            FROM Customers
            WHERE Age = 33
        )
    )
    LIMIT 1
).1;)
```

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

https://fiddle.clickhouse.com/973e1785-f962-49a4-9df5-fe2e5ed053a6
https://fiddle.clickhouse.com/a7e9f85c-0a3c-4105-8c25-ae7b8e32147d
https://fiddle.clickhouse.com/3bcbc895-79d8-4f31-b3df-4c5d3b68ad5b

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

Yes.

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

n/a

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

Reproduction in Fiddle.

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by SaltTan** [comment]
It's because the new analyzer is enabled by default in 24.3
https://fiddle.clickhouse.com/799ec6b7-1ecf-4423-bf21-cce6fcc198a8

**Comment by larryluogit** [comment]
> It's because the new analyzer is enabled by default in 24.3 https://fiddle.clickhouse.com/799ec6b7-1ecf-4423-bf21-cce6fcc198a8
Is this an issue of the new analyzer? or this backward incompatible feature is intentional?
