### ISSUE TITLE
Send original IP in HTTP Authentication

### ISSUE THREAD

**Issue by Yuruh** [ClickHouse/ClickHouse#62351]
When authenticating users via [HTTP](https://clickhouse.com/docs/en/operations/external-authenticators/http) to a clickhouse server behind a proxy, the original IP is not transmitted to the HTTP server

**Use case**

I want to restrict IP of users authenticated through HTTP, using my own HTTP authenticator.

**The solution I'd like**

The original user IP could be set in the "X-Forwarded-For" header, in the "Forwarded" header, or in the request body.

**Alternative I've considered**

Configure users using https://clickhouse.com/docs/en/sql-reference/statements/create/user#user-host, but I need allowed IPs to be dynamic, to support multiple host and CIDR notations

**Comment by arthurpassos** [comment]
> but I need allowed IPs to be dynamic, to support multiple host and CIDR notations

Doesn't https://github.com/ClickHouse/ClickHouse/pull/37827 cover multiple and dynamic hosts?

**Comment by yakov-olkhovskiy** [comment]
@Yuruh you need to enable `auth_use_forwarded_address` in config - example:
https://github.com/ClickHouse/ClickHouse/pull/44135/commits/9092134544a9c153621b72ba08d9a13b5e67a4b1#diff-cbe34b29b29ee72927afd255440c69624b6609f7ff5b34db1a6d1c6dbea7bafc

>using my own HTTP authenticator

not sure what you mean by this?

**Comment by Yuruh** [comment]
Thank you, could not find doc for `auth_use_forwarded_address`, it does fit my need. I wanted my HTTP service to validate IP, but I can make do with `HOST`
