### ISSUE TITLE
[Regression][24.3] : Function isNotDistinctFrom can be used only in the JOIN ON section

### ISSUE THREAD

**Issue by MaceWindu** [ClickHouse/ClickHouse#62358]
**Describe what's wrong**

Following query stopped to work in 24.3 version: https://fiddle.clickhouse.com/8c3a5ec2-a07e-49a8-b452-8eb6a784fcac

with following error : `Function isNotDistinctFrom can be used only in the JOIN ON section. `

**Does it reproduce on the most recent release?**

 Yep

**How to reproduce**

Use link to fiddle above

**Expected behavior**

No error or at least error that tells what's wrong with query if it is not correct

**Error message and/or stacktrace**

`Function isNotDistinctFrom can be used only in the JOIN ON section. `

**Additional context**

Nope

**Comment by SaltTan** [comment]
Workaround: `settings allow_experimental_analyzer=0`
https://fiddle.clickhouse.com/1b2d5045-223c-4411-abdb-3bc208998205
