### ISSUE TITLE
Working with geobases (embedded dictionaries)

### ISSUE THREAD

**Issue by Blargian** [ClickHouse/ClickHouse#62363]
Is the documentation for working with geobases still up to date? I am following the guide [here](https://clickhouse.com/docs/en/sql-reference/dictionaries#embedded-dictionaries) to try and set up a geobase, but I can't seem to load the geobase properly following the documentation guidelines. 

- I created two tab seperated (without header) data files `regions_hierarchy_nl.txt` and `regions_names_nl.txt` for cities in the Netherlands. 
- copied these files to `opt/geo`
- Added the following line to `etc/clickhouse-server/config.xml` : `<path_to_regions_hierarchy_file>/opt/geo/regions_hierarchy_nl.txt</path_to_regions_hierarchy_file>`
- Launched the server with `sudo service clickhouse-server start`
- Launched client with `clickhouse-client`

```
SELECT * FROM system.dictionaries LIMIT 1 FORMAT Vertical;
```
Returns 

```response
Ok.

0 rows in set. Elapsed: 0.003 sec.
```

Indicating to me that the geobase has not been loaded. Documentation [here](https://clickhouse.com/docs/en/sql-reference/functions/ym-dict-functions#multiple-geobases) also states

> The dictionaries are loaded at the first call of any of these functions

However exception is thrown if I try to run one of the functions:

```
SELECT regionToCountry(5, 'nl');
```

Returning

```
Received exception from server (version 24.3.2):
Code: 156. DB::Exception: Received from localhost:9000. DB::Exception: Embedded dictionaries were not loaded. You need to check configuration file.. (DICTIONARIES_WAS_NOT_LOADED)

```
What did I do wrong?

[regions_hierarchy_nl.txt](https://github.com/ClickHouse/ClickHouse/files/14894213/regions_hierarchy_nl.txt)
[regions_names_nl.txt](https://github.com/ClickHouse/ClickHouse/files/14894214/regions_names_nl.txt)

**Comment by alexey-milovidov** [comment]
They are covered by tests, and the example files could be found at `tests/config`
