### ISSUE TITLE
Absolute paths with the file function

### ISSUE THREAD

**Issue by Blargian** [ClickHouse/ClickHouse#62360]
**Use case**

I might download some data file and want to take a quick look at it. With the `file` function the path should be relative. It would be nice if there was a way to enter the absolute path without the need to copy the file to my `user_files_path` or figure out where it is relative to that path.

**Describe the solution you'd like**

Ability to use an absolute path with the `file` function. Example, I download a data file and I can write: 

```
SELECT * FROM file('home/downloads/file.csv','CSVWithNames')
```

Perhaps there is a good reason why the path should be relative that I'm not aware of.

**Comment by alexey-milovidov** [comment]
On the server-side, you can only use files inside the `user_files` directory, and this is done for security reasons. You can create a symlink from that directory to your home, and then you can reference them with a relative path.

On the client-side, such as when using `clickhouse-local`, you can use any paths, including absolute. For example, this works:
```
ch --query "SELECT * FROM '/etc/passwd'"
```

**Comment by Blargian** [comment]
@alexey-milovidov thanks for the explanation!
