### ISSUE TITLE
MaterializedMySQL sync tinyint(1) to int8

### ISSUE THREAD

**Issue by jzhao20230918** [ClickHouse/ClickHouse#62369]
hello,

I'm using the latest ClickHouse MaterializedMySQL to sync Mysql(8.0.36) and find out the column with datatype tinyint(1), whch is bool, would be turned to int8 with MaterializedMySQL. But I'm sure in some previous version of ClickHouse, the synced column's datatype is Bool as I still have some old data in ClickHouse. 
Is there any way that the tinyint(1) still be synced as Bool with MaterializedMySQL? Thanks a lot.

**Comment by pmusa** [comment]
Hi @jzhao20230918, I looked back into the docs and there is no mention to TINY being Bool (it was always UInt8). Also, in ClickHouse "Type bool is internally stored as UInt8. Possible values are true (1), false (0)." (from [docs](https://clickhouse.com/docs/en/sql-reference/data-types/boolean)). Maybe you can share what are you trying to do and why this is an issue.
