### ISSUE TITLE
Log: Part doesn't have metadata version on disk, setting it to 0. It's okay if the part was created by an old version of ClickHouse

### ISSUE THREAD

**Issue by richardsteinbrecht** [ClickHouse/ClickHouse#62391]
Hey,

I have just updated my Clickhouse servers from 23.3.2.37 to 24.3.2.23.

I am now seeing many log entries that look like this:
<pre>
<Warning> <TABLE_NAME> (7cd47efe-9d72-4433-ab7f-99f692195d25): Part 202403_0_1402_380 doesn't have metadata version on disk, setting it to 0. It's okay if the part was created by an old version of ClickHouse
</pre>

I think the parts were created before the update, though I cannot check it for all tables by hand. What do these log entries exactly mean? Does it have any impact? Will it self-heal, or will it disappear once I drop the partition that contains the parts (happens regualery to delete old data). Or is there anything that can be done, or is it safe to ignore?

Thanks in advance.

**Comment by tavplubix** [comment]
It's expected after upgrading, safe to ignore. It will disappear once old parts get merged or removed
