### ISSUE TITLE
Test `02581_share_big_sets_between_mutation_tasks` times out

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#62395]
[cidb](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKICAgIApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDcgREFZCiAgICBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwIE9SIG5vdCBvbmx5X21hc3RlcikKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKKQpXSEVSRSB0ZXN0X25hbWUgbGlrZSAnJTAyNTgxX3NoYXJlX2JpZ19zZXRzX2JldHdlZW5fbXV0YXRpb25fdGFza3MnCk9SREVSIEJZIGR1ciBERVND)

**Comment by alesapin** [comment]
Duplicated https://github.com/ClickHouse/ClickHouse/issues/66907
