### ISSUE TITLE
Can we set `allow_experimental_refreshable_materialized_view = 1` at `config.xml` ?

### ISSUE THREAD

**Issue by ww7** [ClickHouse/ClickHouse#62414]
ClickHouse server version 24.3.2.23 (official build)

Every ClickHouse restarting killing the table, and we wonder how to enable `allow_experimental_refreshable_materialized_view` as persistent.

**Comment by nikitamikhaylov** [comment]
You can enable this setting for a default profile in `users.xml`. Use this file as an example: https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/users.xml
