### ISSUE TITLE
final stopped working after 23.12 for ReplacingMergeTree  tables with a lot of partitions and records

### ISSUE THREAD

**Issue by urtho** [ClickHouse/ClickHouse#62426]
Getting duplicate records for ReplacingMergeTree for queries with final modifier. 
Setting compatibility = '23.12' restores proper behavior.

Test case for 24.3 : https://fiddle.clickhouse.com/399466fd-51fa-45a1-a183-c13b5a0e41d5

Seems like it needs a lot of partitions and records.

**Comment by urtho** [comment]
hmm, seems like `index_granularity_bytes = 0;` causes this.

**Comment by canhld94** [comment]
I tried check if it's the problem with vertical final, but found that it's actually part splitter issue. Try to fix in #62432 , cc @kitaisreal

**Comment by kitaisreal** [comment]
@canhld94 agreed. I also checked it and come up with same solution as you did. Great job!
