### ISSUE TITLE
A new function, `serial`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#62485]
A new function, `serial`, which takes a constant string argument - a series identifier.
On every block, it goes to Keeper and atomically increments the counter with the corresponding name by the block size, then it generates and returns sequential numbers starting from the previous counter value.

The server can be configured with a keeper path - a prefix for these counter nodes, and with a limit on the total number of distinct counters (e.g., 100,000).

The usage of `serial` function will be controlled by a separate access right.

There should be a shortcut syntax for a table definition: if you specify `AUTO_INCREMENT`, it is equivalent to `DEFAULT serial('table_uuid')` or `serial('table_path_in_keeper')`. We can also support `SERIAL` for compatibility with Postgres.

As a result, it will provide a monotonic but not necessarily continuous counter. The discontinuity will appear for rejected or deduplicated INSERTs.

Alternatively, Replicated tables can store the counter inside their path in Keeper, and interpret `AUTO_INCREMENT` directly.

Caveats: special support is needed for BACKUP and RESTORE.

_Originally posted by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/issues/56228#issuecomment-1789933636_

**Comment by tchaton** [comment]
to be posted cc @tchaton

**Comment by keltia** [comment]
Having a `serial` is one thing, having proper SQL SEQUENCE would be even better.  These are part of SQL92 anyway if I'm not mistaken.

**Comment by alexey-milovidov** [comment]
@keltia `SQL SEQUENCE` can be implemented on top of the new function, and it will be a separate task.
