### ISSUE TITLE
How to expand a single-node ClickHouse keeper to a 3-node cluster

### ISSUE THREAD

**Issue by zcw5116** [ClickHouse/ClickHouse#62505]
I have a ClickHouse cluster, and the ClickHouse Keeper currently has only a single node that has been running for some time. Due to performance limitations, I plan to expand the ClickHouse Keeper to a 3-node cluster. The expansion approach is to modify the configuration files, add two new nodes, and then start the clickhouse-keeper service on each node.However, after the expansion, the existing ClickHouse Keeper node remains in the standalone state, while the newly added Keeper nodes are in the follower and leader states, respectively. It appears that the existing ClickHouse Keeper node is still operating independently and has not joined the cluster.My question is: How can I properly expand the ClickHouse Keeper nodes? The official documentation does not provide a clear description of this process. Could you please suggest a solution? Thank you very much.

**Here is the configuration before expansion:**

  <keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>3</server_id> 
    <log_storage_path>/data/clickhouse-23.3.2.37/data/coordination/log</log_storage_path>
    <snapshot_storage_path>/data/clickhouse-23.3.2.37/data/coordination/snapshots</snapshot_storage_path>
    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>warning</raft_logs_level>
    </coordination_settings>
 
    <raft_configuration>
        <server>
            <id>3</id> 
            <hostname>JXDX-YCLL-CH02</hostname>
            <host>172.161.5.24</host>
            <port>9444</port>
        </server>
    </raft_configuration>
  </keeper_server>

**The configuration for expanding to 3 nodes is as follows:
Node 1 (the original single node):**

  <keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>3</server_id> 
    <log_storage_path>/data/clickhouse-23.3.2.37/data/coordination/log</log_storage_path>
    <snapshot_storage_path>/data/clickhouse-23.3.2.37/data/coordination/snapshots</snapshot_storage_path>
    
    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>warning</raft_logs_level>
    </coordination_settings>
 
    <raft_configuration>
        <server>
            <id>3</id> 
            <hostname>JXDX-YCLL-CH02</hostname>
            <host>172.161.5.24</host>
            <port>9444</port>
        </server>
        <server>
            <id>5</id>
            <hostname>JXDX-YCLL-FLAL06</hostname>
            <host>172.161.5.21</host>
            <port>9444</port>
        </server>
        <server>
            <id>6</id>
            <hostname>JXDX-YCLL-FLAL07</hostname>
            <host>172.161.5.22</host>
            <port>9444</port>
        </server>
    </raft_configuration>
  </keeper_server>

**Node 2：**
  <keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>5</server_id> 
    <log_storage_path>/data/clickhouse-23.3.2.37/data/coordination/log</log_storage_path>
    <snapshot_storage_path>/data/clickhouse-23.3.2.37/data/coordination/snapshots</snapshot_storage_path>
    
    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>warning</raft_logs_level>
    </coordination_settings>
 
    <raft_configuration>
        <server>
            <id>3</id>
            <hostname>JXDX-YCLL-CH02</hostname>
            <host>172.161.5.24</host>
            <port>9444</port>
        </server>
        <server>
            <id>5</id>
            <hostname>JXDX-YCLL-FLAL06</hostname>
            <host>172.161.5.21</host>
            <port>9444</port>
        </server>
        <server>
            <id>6</id>
            <hostname>JXDX-YCLL-FLAL07</hostname>
            <host>172.161.5.22</host>
            <port>9444</port>
        </server>
    </raft_configuration>
  </keeper_server>

**Node 3：**
  <keeper_server>
    <tcp_port>9181</tcp_port>
    <server_id>6</server_id> 
    <log_storage_path>/data/clickhouse-23.3.2.37/data/coordination/log</log_storage_path>
    <snapshot_storage_path>/data/clickhouse-23.3.2.37/data/coordination/snapshots</snapshot_storage_path>
    
    <coordination_settings>
        <operation_timeout_ms>10000</operation_timeout_ms>
        <session_timeout_ms>30000</session_timeout_ms>
        <raft_logs_level>warning</raft_logs_level>
    </coordination_settings>
 
    <raft_configuration>
        <server>
            <id>3</id>
            <hostname>JXDX-YCLL-CH02</hostname>
            <host>172.161.5.24</host>
            <port>9444</port>
        </server>
        <server>
            <id>5</id>
            <hostname>JXDX-YCLL-FLAL06</hostname>
            <host>172.161.5.21</host>
            <port>9444</port>
        </server>
        <server>
            <id>6</id>
            <hostname>JXDX-YCLL-FLAL07</hostname>
            <host>172.161.5.22</host>
            <port>9444</port>
        </server>
    </raft_configuration>
  </keeper_server>

**after starting the keeper service, the stat output is as follows:
Node 1 (the original standalone node):**
/ :) stat
ClickHouse Keeper version: v23.3.2.37-stable-1b144bcd101ddf23466ba67e4fa0fd27afb9c060
Clients:
172.161.5.24:39568(recved=74,sent=74)
172.161.5.24:39646(recved=0,sent=0)
172.161.5.22:46392(recved=104,sent=104)
172.161.5.21:49860(recved=105,sent=105)
172.161.5.24:39538(recved=2799,sent=2799)

Latency min/avg/max: 0/0/139
Received: 3082
Sent: 3082
Connections: 4
Outstanding: 0
Zxid: 1691
Mode: standalone
Node count: 149

**Node 2：**
/ :) stat
ClickHouse Keeper version: v23.3.2.37-stable-1b144bcd101ddf23466ba67e4fa0fd27afb9c060
Clients:
172.161.5.21:39922(recved=0,sent=0)
172.161.5.21:39338(recved=77,sent=77)

Latency min/avg/max: 0/0/0
Received: 77
Sent: 77
Connections: 1
Outstanding: 0
Zxid: 364
Mode: follower
Node count: 6

**Node 3：**
/ :) stat
ClickHouse Keeper version: v23.3.2.37-stable-1b144bcd101ddf23466ba67e4fa0fd27afb9c060
Clients:
172.161.5.22:43848(recved=0,sent=0)
172.161.5.22:41736(recved=78,sent=78)

Latency min/avg/max: 0/0/0
Received: 78
Sent: 78
Connections: 1
Outstanding: 0
Zxid: 368
Mode: leader
Node count: 6

**Comment by antonio2368** [comment]
>  Due to performance limitations, I plan to expand the ClickHouse Keeper to a 3-node cluster. 

FYI more nodes in Keeper's case only increases reliability and has negative impact on the performance.

Expanding from 1 node to 3 nodes is tricky and you shouldn't start all 2 new nodes at the same time exactly because of the case you got (split brain). New nodes will achieve quorum with no logs and potentially overwrite all the logs from the old Keeper.
It's hard to say what's going on without logs, for a node to be added to cluster it needs to establish connection to other nodes. Are you sure new nodes are available from the old node?
Providing logs would help.

**Comment by Felixoid** [comment]
I've done it once back in 2019 with ZK, when made a mistake and deployed CH cluster on top of a single node.

I'll try to repeat that experience with keeper and, probably, will make a repository + update a documentation

**Comment by Felixoid** [comment]
Here's the repository to play with the keeper extension https://github.com/Felixoid/keeper-cluster

I'll add it to the documentation, and most probably will move the repository to ClickHouse organization

**Comment by Felixoid** [comment]
@antonio2368 I went through https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper#reconfiguration and it looks very outdated.

E.g. `/keeper/config` is not present in the keeper 24.4. And it looks like there's no replacement for it.

The syntax of `reconfig` is changes, I'll update it. But I don't know how to get the cluster members. Nothing in the flwc gives neither IP nor hostnames

`four_letter_word_allow_list=jmst,jmfp,jmep,jmdp,conf,cons,crst,envi,ruok,srst,srvr,stat,wchs,dirs,mntr,isro,rcvr,apiv,csnp,lgif,rqld,rclc,clrs,ftfl,ydld,pfev`

Could it be that `/keeper/config` is removed, but nothing another was added?

**Comment by antonio2368** [comment]
@Felixoid there is `/keeper/config`

```sh
clickhouse-keeper-client -q "get /keeper/config"
server.1=localhost:9234;participant;1
```

**Comment by Felixoid** [comment]
Oh, it's a "virtual" node?

Cool, thanks a lot!

**Comment by antonio2368** [comment]
Yes, it's a virtual node. Everything under `/keeper` are system nodes and they can play by different rules.

**Comment by Felixoid** [comment]
I slightly rephrased the statement to not confuse the reader then https://github.com/ClickHouse/clickhouse-docs/pull/2311/files#diff-a3037a0357709df221a285b2b5ca2df68b3f7d95e795f7409c594be469daf8a0R1139

Maybe you'd like to review the docs?
