### ISSUE TITLE
Stateless test `00143_transform_non_const_default` is flaky

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#62537]
https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDI0LTAxLTAxJyBhbmQgdGVzdF9uYW1lIGxpa2UgJyUwMDE0M190cmFuc2Zvcm1fbm9uX2NvbnN0X2RlZmF1bHQlJyBhbmQgc3RhdHVzID09ICdGQUlMJwpvcmRlciBieSBjaGVja19zdGFydF90aW1lIGRlc2M=

```
2024-04-10 13:54:09  Google	498635
2024-04-10 13:54:09  Яндекс	229872
2024-04-10 13:54:09 -utf-8	103187
2024-04-10 13:54:09 -	1284
2024-04-10 13:54:09 -koi8-u	1
2024-04-10 13:54:09 +utf-8	104104
2024-04-10 13:54:09 +	366
2024-04-10 13:54:09 +koi8-u	2
2024-04-10 13:54:09 
```

https://s3.amazonaws.com/clickhouse-test-reports/0/4a8c1bf6a33ec5b86c0cf6ebd1f087edb020a9ca/stateful_tests__debug__parallelreplicas_.html

**Comment by Algunenano** [comment]
Broken by PartsSplitter it seems https://github.com/ClickHouse/ClickHouse/pull/60041

**Comment by nickitat** [comment]
no actual failures since april
