### ISSUE TITLE
argMin returns not the first row with min value from 24.3

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#62561]
```sql
CREATE TABLE t (one Float64, two String) engine=MergeTree order by (one, two);
INSERT INTO t VALUES (-1.7976909999999999e308, ''), (0, '');
SELECT argMin(one, two) from t;
```
On 24.3 I get:
```
0
```

On 24.2 (and some other versions <24.3) I get:
```
-1.7976909999999999e308
```

The documentation states: "If there are several different values of arg for minimum values of val, returns the first of these values encountered." Based on this, one might expect that the row associated with the first minimum value would be consistently returned across versions. Is that correct?

**Comment by Algunenano** [comment]
The documentation is wrong. The order in ties was never guaranteed and any value could be returned. Will fix the docs
