### ISSUE TITLE
Aggregate function sum(totalb) is found in WHERE in query: While processing sum(totalb) AS totalb

### ISSUE THREAD

**Issue by fiend19961** [ClickHouse/ClickHouse#62582]
Sql parser could be smarter
1. create table and add some data
```sql
DROP TABLE IF EXISTS test1;
CREATE TABLE IF NOT EXISTS test1
(
    `ts` DateTime,
    `name` String,
    `totalb` UInt64
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(ts)
ORDER BY ts;
INSERT into test1 values 
(now(),'aa',3),
(now(),'wd',44),
(now(),'q',2),
(now(),'cca',2);
```
2. execute sql
```sql
select sum(totalb) as totalb from test1 where totalb=2;
```

**Describe the unexpected behaviour**
throw some error,but the grammar is ok in postgresql
if I want use alias as a filter ,I will use 'group by xx having sum(totalb) xxx'
```text
Aggregate function sum(totalb) is found in WHERE in query: While processing sum(totalb) AS totalb
```
* Which ClickHouse server version to use
clickhouse version:23.8.2.7 (official build)

**Expected behavior**
behavior same as these sqls
```sql
select sum(totalb) as totalb from test1 where test1.totalb=2;
select sum(totalb) as totalb_alias from test1 where totalb=2;
```

**Comment by Algunenano** [comment]
ClickHouse allows you to declare and use aliases everywhere by default, so in the first query `where totalb=2;` is understood as referencing the alias created in the column section (`sum(totalb) as totalb`) which isn't a valid SQL (if would be in the case it wasn't an aggregation for example).

You can change this behaviour by changing the setting `prefer_column_name_to_alias`.
