### ISSUE TITLE
Views very slow since upgrading to 24.3

### ISSUE THREAD

**Issue by dbs5** [ClickHouse/ClickHouse#62594]
(you don't have to strictly follow this form)

**Describe the situation**
We have several views which only point to a table.
`CREATE VIEW v AS SELECT * FROM myTable`
We don't want our visualization tool (metabase) to directly access tables, in case we need to change something without changing the structure.

Since 24.3 the performance of those views is very bad.
With version 24.2 running queries on the tables directly or the view was basically the same performance.
Now, in 24.3, the views are several times slower.
From what I could tell by checking things like htop during queries, the views now seem to load the entire table into RAM before doing anything.
RAM and CPU spike massively during the query. 

**How to reproduce**
* **Which ClickHouse server version to use** 
24.3
* **Which interface to use, if matters**
Doesn't matter. I could reproduce it with clickhouse-client and HTTP interface. Did not try other, but most likely same problem.
* **Non-default settings, if any**
None
* **`CREATE TABLE` statements for all tables involved**
I was able to reproduce the problem with your sample dataset _UK property prices_
https://clickhouse.com/docs/en/getting-started/example-datasets/uk-price-paid
* **Sample data for all these tables, use [clickhouse-obfuscator]**
Data from the sample.
* **Queries to run that lead to slow performance**
`SELECT max(price) FROM uk_price_paid`
This takes around 15ms on my machine
`CREATE VIEW priceView AS SELECT * FROM uk_price_paid`
`SELECT max(price) FROM priceView`
This takes roughly 100ms on my machine with 24.3.
With 24.2 same performance as direct query on the table.
The bigger the table, the bigger the performance difference between view and table.
Most likely due loading it all first.

**Expected performance**
View and table should have same performance as it has been the case in 24.2 and earlier.

**Comment by UnamedRus** [comment]
Can you test with

`set allow_experimental_analyzer=0`

**Comment by nickitat** [comment]
pls compare `explain pipeline` for both versions

**Comment by dbs5** [comment]
> Can you test with
> 
> `set allow_experimental_analyzer=0`

This does it. Very times on the view are back to 24.2 values



> pls compare `explain pipeline` for both versions

**24.2**

- Expression ((Projection + Before ORDER BY))                                                                                                                               
- Aggregating                                                                                                                                                             
- Expression ((Before GROUP BY + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Projection + Before ORDER BY)))))
- ReadFromMergeTree (test.uk_price_paid)                                                                                                                              

**24.3**

- Expression ((Project names + Projection))
- Aggregating
- Expression ((Before GROUP BY + (Change column names to column identifiers + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Project names + (Projection + Change column names to column identifiers)))))))
- ReadFromMergeTree (test.uk_price_paid)

**Comment by nickitat** [comment]
> > Can you test with
> > `set allow_experimental_analyzer=0`
> 
> This does it. Very times on the view are back to 24.2 values
> 
> > pls compare `explain pipeline` for both versions
> 
> **24.2**
> 
> * Expression ((Projection + Before ORDER BY))
> * Aggregating
> * Expression ((Before GROUP BY + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Projection + Before ORDER BY)))))
> * ReadFromMergeTree (test.uk_price_paid)
> 
> **24.3**
> 
> * Expression ((Project names + Projection))
> * Aggregating
> * Expression ((Before GROUP BY + (Change column names to column identifiers + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Project names + (Projection + Change column names to column identifiers)))))))
> * ReadFromMergeTree (test.uk_price_paid)

it is not the exact `explain pipeline` output, right. in particular it doesn't show the number of transforms for each step.

**Comment by dbs5** [comment]
Sorry, I only did `explain` not `explain pipeline`.

This should be correct now
24.2
![Screenshot 2024-04-15 at 10 29 31](https://github.com/ClickHouse/ClickHouse/assets/24433671/60170963-f21b-450c-8a56-d45a24757a52)


24.3
![Screenshot 2024-04-15 at 10 26 45](https://github.com/ClickHouse/ClickHouse/assets/24433671/7b169467-a36c-451c-8203-7e3ee7df1659)

**Comment by nickitat** [comment]
``` sql
EXPLAIN header = 1
SELECT max(price)
FROM uk_price_paid_view
SETTINGS allow_experimental_analyzer = 0

   ┌─explain────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
1. │ Expression ((Projection + Before ORDER BY))                                                                                                                                │
2. │ Header: max(price) UInt32                                                                                                                                                  │
3. │   Aggregating                                                                                                                                                              │
4. │   Header: max(price) UInt32                                                                                                                                                │
5. │     Expression ((Before GROUP BY + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Projection + Before ORDER BY))))) │
6. │     Header: price UInt32                                                                                                                                                   │
7. │       ReadFromMergeTree (default.uk_price_paid)                                                                                                                            │
8. │       Header: price UInt32                                                                                                                                                 │
   └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

``` sql
EXPLAIN header = 1
SELECT max(price)
FROM uk_price_paid_view
SETTINGS allow_experimental_analyzer = 1

    ┌─explain────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
 1. │ Expression ((Project names + Projection))                                                                                                                                                                                                                  │
 2. │ Header: max(price) UInt32                                                                                                                                                                                                                                  │
 3. │   Aggregating                                                                                                                                                                                                                                              │
 4. │   Header: max(__table1.price) UInt32                                                                                                                                                                                                                       │
 5. │     Expression ((Before GROUP BY + (Change column names to column identifiers + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Project names + (Projection + Change column names to column identifiers))))))) │
 6. │     Header: __table1.price UInt32                                                                                                                                                                                                                          │
 7. │       ReadFromMergeTree (default.uk_price_paid)                                                                                                                                                                                                            │
 8. │       Header: price UInt32                                                                                                                                                                                                                                 │
 9. │               date Date                                                                                                                                                                                                                                    │
10. │               postcode1 LowCardinality(String)                                                                                                                                                                                                             │
11. │               postcode2 LowCardinality(String)                                                                                                                                                                                                             │
12. │               type Enum8('other' = 0, 'terraced' = 1, 'semi-detached' = 2, 'detached' = 3, 'flat' = 4)                                                                                                                                                     │
13. │               is_new UInt8                                                                                                                                                                                                                                 │
14. │               duration Enum8('unknown' = 0, 'freehold' = 1, 'leasehold' = 2)                                                                                                                                                                               │
15. │               addr1 String                                                                                                                                                                                                                                 │
16. │               addr2 String                                                                                                                                                                                                                                 │
17. │               street LowCardinality(String)                                                                                                                                                                                                                │
18. │               locality LowCardinality(String)                                                                                                                                                                                                              │
19. │               town LowCardinality(String)                                                                                                                                                                                                                  │
20. │               district LowCardinality(String)                                                                                                                                                                                                              │
21. │               county LowCardinality(String)                                                                                                                                                                                                                │
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

we read unneeded columns

**Comment by nickitat** [comment]
@novikd could you pls take a look. maybe all the needed code is already in place and it is easy to fix

**Comment by buyology** [comment]
For us the new analyzer is unusable — most probably due to this. Server consumes all CPU and memory after upgrading and `allow_experimental_analyzer = 1`.
