### ISSUE TITLE
Types of array and 2nd argument of function has must be identical up to nullability

### ISSUE THREAD

**Issue by khrisanfov** [ClickHouse/ClickHouse#626]
I have table with column of Array(Enum8(...)). When I am trying SELECT with "has" function like this: uniqIf(column1, has(column2, 'MyEnumValue')) ClickHouse returns error "Types of array and 2nd argument of function has must be identical up to nullability". It works only I call has with particular number like 2 instead of 'MyEnumValue'. Should I use number instead of Enum value or this is a bug?

**Comment by alexey-milovidov** [comment]
This is missing functionality: `has` and `indexOf` functions are just not implemented yet for Enum types.

**Comment by khrisanfov** [comment]
But CREATE table works fine and has (column2, 2) looks like returns reasonable result

**Comment by alexey-milovidov** [comment]
It means, that `has` works with Array of Enums only if you pass numeric value.

**Comment by khrisanfov** [comment]
Ok, Is there a plan to implement it? If you want I can try it, but I am not sure how much time it will take :)

**Comment by alexey-milovidov** [comment]
Yes, we have it in plans.

It would be nice if you will try to implement it! We very appreciate any contribution.
And don't worry if it will be successful or not...

**Comment by khrisanfov** [comment]
@alexey-milovidov Hi, I have updated ClickHouse to the latest version and now 'has' does not work with Array of Enums even I pass numeric value. It worked about a year ago, I do not remember the version number :(.

I use it like this:

has(column, 1)

I got an error like this:

> Types of array and 2nd argument of function has must be identical up to nullability. Passed: Array(Enum8(...)) and UInt8.. 

So, I pass UInt8 and it does not work.
