### ISSUE TITLE
clickhouse process is killed

### ISSUE THREAD

**Issue by yczstone** [ClickHouse/ClickHouse#6260]
### When you query a large table multiple times,clickhouse process is killed.
The clickhouse version is 1.1.54318.
Two servers were deployed.
The server configuration is as follows  :  8C16G200G
The query statement is：

SELECT visit_id,carrier,class_name,line_number,uuid,method_name, customer_name,mem_available,region_id,os_id,device_id,app_version_id,threads,file_name,mobile_app_name, cpu,memory,hard_disk,is_symbol,visit_start_time,crash_time from crash WHERE uuid GLOBAL IN ( SELECT uuid from crash WHERE ch_start_date BETWEEN ? AND ? AND (timestamp >= ? AND timestamp < ?) AND crash_type = ? AND app_id = ? ORDER BY crash_time DESC LIMIT ?, ? ) ORDER BY crash_time DESC

There are about 1.6 million data in this crash table。

System logs are as follows：
Aug  5 09:30:27 clickhouse02 kernel: Out of memory: Kill process 16959 (AsyncBlockInput) score 947 or sacrifice child
Aug  5 09:30:27 clickhouse02 kernel: Killed process 19079 (clickhouse-serv) total-vm:40090428kB, anon-rss:15314964kB, file-rss:0kB, shmem-rss:0kB
Aug  5 09:30:27 clickhouse02 systemd-logind: New session 4753 of user root.
Aug  5 09:30:29 clickhouse02 systemd: Started Session 4753 of user root.
Aug  5 09:30:29 clickhouse02 systemd: Starting Session 4753 of user root.

**If anyone can answer that, thank you very much**

**Comment by filimonov** [comment]
Oomkiller most probably. Please check `dmesg`

**Comment by sasha-moiseenko** [comment]
if somebody is running into this error I found cause of this issue in syslog (ubuntu 20.04), but not in dmesg:
kernel: [  123.578583] Out of memory: Killed process 4211 (clickhouse-clie) total-vm:23408928kB, anon-rss:14246608kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:28752kB oom_score_adj:0
