### ISSUE TITLE
unhex hexstring with 0x prefix

### ISSUE THREAD

**Issue by YadominJinta** [ClickHouse/ClickHouse#62618]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

`unhex` a hexstring with `0x` prefix returns a different result compared to without `0x` prefix, it insert 'FF' at the begining.

It seems that `unhex` doesn't validate input and it returns `FF` when contains invalid character like `x`.

Since clickhouse support hex literals with `0x` prefix as number, I think `unhex` should also support `0x` prefix hexstrings.

```
> SELECT hex(unhex('0x1234'))

   ┌─hex(unhex('0x1234'))─┐
1. │ FF1234               │
   └──────────────────────┘

> SELECT hex(unhex('1234'))

   ┌─hex(unhex('1234'))─┐
1. │ 1234               │
   └────────────────────┘

> SELECT hex(unhex('x'))

   ┌─hex(unhex('x'))─┐
1. │ FF              │
   └─────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

**Comment by cangyin** [comment]
The `unhex` function does not accept characters other than `A`-`F` (case insensitive). Result of illegal input is implementation defined.

> Supports both uppercase and lowercase letters A-F. The number of hexadecimal digits does not have to be even. If it is odd, the last digit is interpreted as the least significant half of the 00-0F byte. If the argument string contains anything other than hexadecimal digits, some implementation-defined result is returned (an exception isn’t thrown).

https://clickhouse.com/docs/en/sql-reference/functions/encoding-functions#unhex

To ensure the input does not contain '0x' prefix, `replaceRegexp*` can be used.
```sql
SELECT hex(unhex(replaceRegexpOne('0x123456','^0x',''))) AS a,
    hex(unhex(replaceRegexpOne('123456','^0x',''))) AS b,
    a == b;

+-a------+-b------+-equals(a, b)-+
| 123456 | 123456 |            1 |
+--------+--------+--------------+
```
