### ISSUE TITLE
Please provide installer for Windows without WSL 

### ISSUE THREAD

**Issue by MohammadShojaeinia** [ClickHouse/ClickHouse#62626]
Hi.
An Exe installer for clickhouse is really needed, because installing it on WSL has different problems:

1. It does not run as a service(not like mongodb or SQL Server installed on Windows)
2. On WSL2, on every restart IP changes and you should change the target in your code every time you run your computer.
3. For those computers without internet, there is no way to install(not only cllickhouse, but also WSL)

Also, Docker is not a good solution for Windows, due to the problems that yandex/clickhouse image has.

Thanks

**Comment by Algunenano** [comment]
Supporting Windows without WSL is a massive undertaking, which is extremely unlikely to ever happen. If anybody is willing to contribute and support it, PRs are welcome.
