### ISSUE TITLE
Server crashes after insert into a table with GCD codec (v24.4.1.497)

### ISSUE THREAD

**Issue by NoromTin** [ClickHouse/ClickHouse#62629]
(win10, wsl, v24.4.1.497)
this request is almost guaranteed to crash my server, somewhere starting from 5 million

CREATE TABLE test_gcd
(
    `test_col` UInt32 CODEC(GCD, LZ4)
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192, index_granularity_bytes = 1024

INSERT INTO test_gcd SELECT floor(randUniform(1, 3)) FROM numbers(15000000)
OPTIMIZE TABLE test_gcd FINAL

**Comment by nickitat** [comment]
please share the stack trace of the crash

**Comment by NoromTin** [comment]
[stack_trace_202404151315.csv](https://github.com/ClickHouse/ClickHouse/files/14977513/stack_trace_202404151315.csv)
[clickhouse-server.err.log](https://github.com/ClickHouse/ClickHouse/files/14977543/clickhouse-server.err.log)

**Comment by nickitat** [comment]
It easily reproduces (without wsl), need to debug

**Comment by nickitat** [comment]
turned out it works with compact parts disabled.
without this pr #61535 problem doesn't reproduce

**Comment by CurtizJ** [comment]
I reproduced it with wide parts on build with asan from as well. So, the problem is in the gcd codec.

repro:

```sql
CREATE TABLE test_gcd
(
    `test_col` UInt32 CODEC(GCD, LZ4)
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192, index_granularity_bytes = 1024, min_bytes_for_wide_part = 0, max_compress_block_size = 1024, min_compress_block_size = 1024

 INSERT INTO test_gcd SELECT floor(randUniform(1, 3)) FROM numbers(15000000);
```

[stacktrace](https://pastila.nl/?001b10c6/473312457eab4e4f4bfc7c6bc28fa762#RumgNPWVXwTAokjUmzY7Vg==).
