### ISSUE TITLE
Как в clickhouse сохранить таблицу в временный csv файл

### ISSUE THREAD

**Issue by KatRRina** [ClickHouse/ClickHouse#62630]
Необходимо сохранить данные из таблицы  clickhouse  в временный csv файл. Пробовала запрос 
{select_expression} INTO OUTFILE '{file_path}' FORMAT CSV 
Получаю ошибку

 File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 361, in _error_handler
    raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://172.18.108.116:8123 returned response code 400)
 Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 905 (line 22, col 2): FORMAT Native. Expected SETTINGS (version 20.5.3.27 (official build))
 
 как исправить?

**Comment by nickitat** [comment]
CH complains that there is a syntax error, most likely we need to see the actual `select_expression` to spot it

**Comment by UnamedRus** [comment]
> {select_expression} INTO OUTFILE '{file_path}' FORMAT CSV


INTO OUTFILE is feature of **clickhouse-client**, not clickhouse-server


> clickhouse_connect.driver.exceptions.DatabaseError: :HTTP

You are using python http driver

**Comment by KatRRina** [comment]
> CH жалуется, что произошла синтаксическая ошибка, скорее всего, нам нужно увидеть факт, `select_expression`чтобы ее обнаружить.

here is the request itself
select * from events_data INTO OUTFILE '/tmp/tmpollnbkss' FORMAT CSV
the request itself is working

**Comment by KatRRina** [comment]
> > {select_expression} INTO OUTFILE '{file_path}' FORMAT CSV
> 
> INTO OUTFILE is feature of **clickhouse-client**, not clickhouse-server
> 
> > clickhouse_connect.driver.exceptions.DatabaseError: :HTTP
> 
> You are using python http driver

is there any way in python to save data from clickhouse to a temporary csv file through a query?

**Comment by UnamedRus** [comment]
> is there any way in python to save data from clickhouse to a temporary csv file through a query?

You need to write python code to write data to file

**Comment by slvrtrn** [comment]
Since you are using [clickhouse-connect](https://github.com/ClickHouse/clickhouse-connect), and if it is ok to save the file on the application side (and not on the CH server), then something like this will work:

```python
import clickhouse_connect

if __name__ == '__main__':
    client = clickhouse_connect.get_client()
    query = 'SELECT number, toString(number) AS number_as_str FROM system.numbers LIMIT 5'
    fmt = 'CSVWithNames'  # or CSV, or CSVWithNamesAndTypes
    stream = client.raw_stream(query=query, fmt=fmt)
    with open("output.txt", "wb") as f:
        for chunk in stream:
            f.write(chunk)
```

Yields `output.txt`:

```
"number","number_as_str"
0,"0"
1,"1"
2,"2"
3,"3"
4,"4"
```

**Comment by slvrtrn** [comment]
File streaming examples will be added to the Python client docs: https://github.com/ClickHouse/clickhouse-docs/pull/2233.

If you have further questions, please feel free to open an issue in the client's repository (https://github.com/ClickHouse/clickhouse-connect/issues)

**Comment by den-crane** [comment]
BTW jdbc supports INFILE and OUTFILE. Python-connect could too.

* https://github.com/ClickHouse/clickhouse-java/pull/1291

**Comment by slvrtrn** [comment]
cc @genzgd ^
