### ISSUE TITLE
How to save a table in a temporary csv file in clickhouse

### ISSUE THREAD

**Issue by KatRRina** [ClickHouse/ClickHouse#62631]
I need to save the data from the clickhouse table to a temporary csv file. I tried the request
{select_expression} INTO OUTFILE '{file_path}' FORMAT CSV
I get an error

File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_connect/driver/httpclient.py", line 361, in _error_handler
raise OperationalError(err_str) if retried else DatabaseError(err_str) from None
clickhouse_connect.driver.exceptions.DatabaseError: :HTTP Driver for http://172.18.108.116:8123 returned response code 400)
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 905 (line 22, col2): FORMAT Native. Expected SETTINGS (version 20.5.3.27 (official build))

how to fix it?

**Comment by nickitat** [comment]
duplicate #62630
