### ISSUE TITLE
Async insert in HTTP interface outputs empty block of data when `wait_for_async_insert=1`

### ISSUE THREAD

**Issue by Avogar** [ClickHouse/ClickHouse#62644]
```
avogar@avogar-dev:~$ echo '{"a" : 42}' | curl -X POST 'http://localhost:8123/?query=insert%20into%20test%20format%20JSONAsString&async_insert=1&stacktrace=1' -H "X-Clickhouse-Format: XML" --data-binary @-
<?xml version='1.0' encoding='UTF-8' ?>
<result>
	<meta>
		<columns>
		</columns>
	</meta>
	<data>
	</data>
	<rows>0</rows>
	<statistics>
		<elapsed>0.005665209</elapsed>
		<rows_read>0</rows_read>
		<bytes_read>0</bytes_read>
	</statistics>
</result>
```

Also it fails if the user specifies format that is not suitable for output:
```
echo '{"a" : 42}' | curl -X POST 'http://localhost:8123/?query=insert%20into%20test%20format%20JSONAsString&async_insert=1' -H "X-Clickhouse-Format: JSONAsString" --data-binary @-
Code: 399. DB::Exception: Format JSONAsString is not suitable for output. (FORMAT_IS_NOT_SUITABLE_FOR_OUTPUT) (version 24.4.1.1)
```

It should not try to output anything as in the simple `INSERT` query.

It happens because we create `WaitForAsyncInsertSource` and pull it during query execution.
Here we create the source:
https://github.com/ClickHouse/ClickHouse/blob/54871f0d9c5ac8c7b664c81eaccadd1c6a081941/src/Interpreters/executeQuery.cpp#L1045-L1050
Here we check if we hape pulling pipeling and create output format:
https://github.com/ClickHouse/ClickHouse/blob/54871f0d9c5ac8c7b664c81eaccadd1c6a081941/src/Interpreters/executeQuery.cpp#L1521-L1575

Need to think how to avoid it.

**Comment by mzitnik** [comment]
Do we have an estimation for solving the issue?
