### ISSUE TITLE
max_suspicious_broken_parts_bytes Not changed

### ISSUE THREAD

**Issue by aol-59** [ClickHouse/ClickHouse#62662]
Hi 
I got this error when i try to start Clickhouse
Suspiciously big size (16 parts, 1.60 GiB in total ) of all broken parts to remove while maximum allowed broken parts is 1.00 GiB 
Cannot attach table mytbl feom metadata fole path/mytbl.sql
I tried to add this settings max_suspicious_broken_parts_bytes in config. But nothings changed 
What should i do ?

Should i move this file to temp folder then start clickhouse and return it again?

I tried to run this command but nothing changed 
sudo -u clickhouse touch /var/lib/clickhouse/flags/force_restore_data

The table is replicated merge tree and i am using clickhouse keeper.

Version 23.8

**Comment by den-crane** [comment]
Have you restarted Clickhouse? `force_restore_data` works during restart.

>I tried to add this settings max_suspicious_broken_parts_bytes in config. 

Share your config. This parameter also requires a restart.

**Comment by aol-59** [comment]
> Have you restarted Clickhouse? `force_restore_data` works during restart.
> 
> 
> 
> >I tried to add this settings max_suspicious_broken_parts_bytes in config. 
> 
> 
> 
> Share your config. This parameter also requires a restart.
> 
> 


The ClickHouse database has stopped. I attempted to start it 
```
systemctl start clickhouse-server 
```, 
but the error persists. Here is the configuration.

<clickhouse>
<max_suspicious_broken_parts>200</max_suspicious_broken_parts>
<max_suspicious_broken_parts_bytes>2000000000</max_suspicious_broken_parts_bytes>

</clickhouse>

**Comment by den-crane** [comment]
It should be inside mergetree section


```
<clickhouse>
     <merge_tree>
         <max_suspicious_broken_parts>200</max_suspicious_broken_parts>
         <max_suspicious_broken_parts_bytes>3000000000</max_suspicious_broken_parts_bytes>
     </merge_tree>
<clickhouse>

**Comment by aol-59** [comment]
thank you so much 👍
