### ISSUE TITLE
Function path not returning an empty string if we send a path to the function

### ISSUE THREAD

**Issue by YiuRULE** [ClickHouse/ClickHouse#6268]
Hi CH team,

I currently have a small feature request coming from my company where I can possibly work on, but I wanted to have first the opinion of CH team before doing a potential PR. I didn't know too much if I needed to write as a question tag or a PR tag, but here we are. :)

It's for the `path` and `pathFull`, they would like to accept function call similar to this `SELECT path('/path/for/download/file.exe')`, instead of doing something like `SELECT if(some_code_to_check_is_a_path(url),  url, path('/path/for/download/file.exe'))`.

I understand than in general, all URL related function need to receive a valid URL, but I can also understand the problem on the user side than if we send path, it should also possibly return the same path.

So what would be the opinion of Yandex concerning this question ?

1/ Doing the data check on the request side.
2/ Modifying the `path` and `pathFull` function for accept this behaviour.
3/ Create an alternative of this function with accepting this behaviour for not impacting performance of current user.

Many thanks !

**Comment by alexey-milovidov** [comment]
I'm happy to say that we have implemented the desired behaviour together:
```
milovidov-desktop :) SELECT path('/path/for/download/file.exe')

SELECT path('/path/for/download/file.exe')

┌─path('/path/for/download/file.exe')─┐
│ /path/for/download/file.exe         │
└─────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec. 

milovidov-desktop :) SELECT pathFull('/path/for/download/file.exe')

SELECT pathFull('/path/for/download/file.exe')

┌─pathFull('/path/for/download/file.exe')─┐
│ /path/for/download/file.exe             │
└─────────────────────────────────────────┘
```
