### ISSUE TITLE
ALTER UPDATE/ALTER DELETE statements must use only deterministic functions. Function 'joinGet' is non-deterministic.

### ISSUE THREAD

**Issue by p-pekala** [ClickHouse/ClickHouse#62687]
**Describe what's wrong**

I'm trying to use alter table update together with Join table as described here:
https://clickhouse.com/blog/handling-updates-and-deletes-in-clickhouse

I'm getting error:

`SQL Error [36] [07000]: Code: 36. DB::Exception: ALTER UPDATE/ALTER DELETE statements must use only deterministic functions. Function 'joinGet' is non-deterministic. (BAD_ARGUMENTS) (version 23.8.8.20 (official build))`

**How to reproduce**

`CREATE TABLE tests.test_join ON CLUSTER '{cluster}' (
	id                 String,
	new_value		   String
) Engine = Join(ANY, LEFT, id);

CREATE TABLE tests.updatable_test ON CLUSTER '{cluster}' (
	id               String,
	value		     String
) Engine = ReplicatedMergeTree('/clickhouse/tables/{shard}/dema/updatable_test2', '{replica}')
ORDER BY (id);

insert into  tests.test_join values
('id1', 'new_value');

insert into  tests.updatable_test values
('id1', 'old_value');

select * from tests.updatable_test;

alter table tests.updatable_test UPDATE value = joinGet('tests.test_join', 'new_value', id) where 1=1
`

**Expected behavior**

Data should be updated.

**Error message and/or stacktrace**

`SQL Error [36] [07000]: Code: 36. DB::Exception: ALTER UPDATE/ALTER DELETE statements must use only deterministic functions. Function 'joinGet' is non-deterministic. (BAD_ARGUMENTS) (version 23.8.8.20 (official build))`

**Comment by Algunenano** [comment]
The error is clear and correct. joinGet is not deterministic as the associated table might change at any time, so the update won't necessarily be consistent across different parts or replicas.

If you are ok with having this inconsistent behaviour you can enable the `allow_nondeterministic_mutations`

**Comment by p-pekala** [comment]
I think the problem is connected to a Replicated table that is being updated. Is it not possible to update a replicated table with joinGet?

**Comment by Algunenano** [comment]
It is if you enable `allow_nondeterministic_mutations` setting.
