### ISSUE TITLE
UNKNOWN_QUERY_PARAMETER in WITH FILL clause in v24.3+

### ISSUE THREAD

**Issue by kamilkisiela** [ClickHouse/ClickHouse#62698]
**Describe what's wrong**

Query parameters no longer work within `WITH FILL` clause.

> Received exception from server (version 24.3.1):
Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Query parameter `a1` was not set. (UNKNOWN_QUERY_PARAMETER)

**ERROR in versions v24.3+**

`24.3.1.2672` - https://fiddle.clickhouse.com/53aee6cf-7d0c-43e9-ab06-0c9a4a7ba6e9

**OK in versions prior to v24.3**

`24.2.1.2248` - https://fiddle.clickhouse.com/29cffcbd-78a8-443b-a392-c7e4b43e413f
`24.1.2.5` - https://fiddle.clickhouse.com/60663267-4628-4cba-b99b-63151c4a451a
`23.12.6.19` - https://fiddle.clickhouse.com/d755cab1-d8c6-4a9e-837c-e1ea376caa06

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

1. Use ClickHouse v24.3.X
2. Execute:

```sql
set param_a1 = '2024-04-15 00:00:00'; 
set param_a2 = '2024-04-17 23:59:59';

select uid, timestamp FROM users
  ORDER BY timestamp ASC
  WITH FILL
    FROM toDateTime({a1: String}, 'UTC')
    TO toDateTime({a2: String}, 'UTC')
    STEP INTERVAL 12 HOUR
```

3. You get `UNKNOWN_QUERY_PARAMETER`

All parameters should be available.

**Error message and/or stacktrace**

```
Received exception from server (version 24.3.1):
Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Query parameter `a1` was not set. (UNKNOWN_QUERY_PARAMETER)
(query: select uid, timestamp FROM users
  ORDER BY timestamp ASC
  WITH FILL
			FROM toDateTime({a1: String}, 'UTC')
			TO toDateTime({a2: String}, 'UTC')
			STEP INTERVAL 12 HOUR
  ;)

```

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/62113
fixed https://github.com/ClickHouse/ClickHouse/pull/62186

**Comment by kamilkisiela** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/62113
