### ISSUE TITLE
ClickHouse build for Mac does not include ODBC Bridge

### ISSUE THREAD

**Issue by Carmageddon** [ClickHouse/ClickHouse#62703]
**I have tried the following solutions**: https://clickhouse.com/docs/en/faq/troubleshooting/#troubleshooting-installation-errors

**Installation type**

Packages, docker, single binary, curl?
I have started using the quick start binary for Mac, figured out Clickhouse-ODBC bridge is missing, I tried installing via the recommended brew cask, and the bridge is not there.

**Source of the ClickHouse**

I have also tried to build from sources, but its complicated, the recursive command was interrupted overnight and didnt download everything, I tried resuming `git submodule update --init --recursive` but that didnt do it still having build errors about missing stuff, I am going to retry when I get home from scratch, but I dont have high hopes that building will be straightforward without further compiler configuration issues.

I have NOT tried going down the rabbit hole of modifying the Clickhouse docker image, to add ODBC driver to it, and configure it to work through the bridge (assuming the docker image has the bridge)

**Expected result**

I need to pull data from Azure MS SQL server in order to evaluate clickhouse on our data.

**The actual result**

Cant get the bridge running

**How to reproduce**

on MacOS, follow the guide to either get binary via curl or brew install - everything seem to work except the is no bridge component available.

A lot of details are documented also on: https://stackoverflow.com/questions/78332323/clickhouse-on-macos-using-odbc-bridge-to-microsoft-sql-server as well as on the Slack thread https://clickhousedb.slack.com/archives/CU478UEQZ/p1713236727606229 where we tried different things to no avail.

**Comment by Felixoid** [comment]
Besides that, `clickhouse-odbc-bridge` is included in the docker image, so you can try it

```
> docker run -it clickhouse/clickhouse-server ls /usr/bin/clickhouse-odbc-bridge -l
-rwxr-xr-x 1 clickhouse-bridge clickhouse-bridge 172486504 Apr  2 22:03 /usr/bin/clickhouse-odbc-bridge
```

**Comment by Carmageddon** [comment]
Thank you @Felixoid , I tried your suggestion and now I have setup docker container running ClickHouse, added the same ODBC drive and configuration, and same thing as on host mac - isql only works with hardcoded user/pass, but it works.
Now when I try to use it through clickhouse (using SQL client), I get the following error in logs:

2024.04.16 19:43:55.705469 [ 47 ] {20d90873-15c5-4458-b39d-8d207305cd84} <Debug> executeQuery: (from 192.168.65.1:63975) SELECT * FROM odbc( 'DSN=ProdDWH;Uid=username;Pwd=password;', 'ProdDWHSqlDB', 'some-table' ); (stage: Complete)
2024.04.16 19:43:55.707742 [ 47 ] {20d90873-15c5-4458-b39d-8d207305cd84} <Trace> ContextAccess (default): Access granted: CREATE TEMPORARY TABLE, ODBC ON *.*
2024.04.16 19:43:55.734300 [ 47 ] {20d90873-15c5-4458-b39d-8d207305cd84} <Information> ReadWriteBufferFromHTTP: Failed to make request to `http://127.0.0.1:9018/columns_info?use_connection_pooling=1&version=1&connection_string=DSN%3DProdDWH%3BUid%3Dusername%3BPwd%3Dpassword%3B&schema=ProdDWHSqlDB&table=some-table&external_table_functions_use_nulls=1`. Error: DB::HTTPException: Received error from remote server http://127.0.0.1:9018/columns_info?use_connection_pooling=1&version=1&connection_string=DSN%3DProdDWH%3BUid%3Dusername%3BPwd%3Dpassword%3B&schema=ProdDWHSqlDB&table=some-table&external_table_functions_use_nulls=1. HTTP status code: 500 Internal Server Error, body: Error getting columns from ODBC 'std::exception. Code: 1001, type: nanodbc::database_error, e.what() = contrib/nanodbc/nanodbc/nanodbc.cpp:1046: IM00: [unixODBC][Driver Manager]Data source name not found and no default driver specified  (version 24.3.2.23 (official build))'
. Failed at try 2/10. Will retry with current backoff wait is 100/1600 ms.
How to investigate the cause? I assume this means the bridge is working correctly?

**Comment by Felixoid** [comment]
I think the questions regarding setting up the ODBC bridge are discussed in the Slack thread RN. Let's keep the issue related to the binary building for MacOS.
