### ISSUE TITLE
Return HTTP API errors in JSON format with "Accept: application/json" header

### ISSUE THREAD

**Issue by ghost** [ClickHouse/ClickHouse#6272]
Currently HTTP API returns errors as plain text:

```sh
$ curl -i 'localhost:8123/?query=SELECT%20*%20FROM%20not_existing'
HTTP/1.1 404 Not Found
Date: Thu, 01 Aug 2019 13:48:40 GMT
Connection: Keep-Alive
Content-Type: text/plain; charset=UTF-8
X-ClickHouse-Server-Display-Name: 6a1d1ae7d34a
Transfer-Encoding: chunked
Keep-Alive: timeout=3
X-ClickHouse-Summary: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}

Code: 60, e.displayText() = DB::Exception: Table default.not_existing doesn't exist. (version 19.11.4.24 (official build))
```

The format of the errors can't be changed neither by adding `Accept` header nor by using `FORMAT` clause in the query.

It would be nice to have an ability to get errors in a more machine-readable format, such as JSON, by sending `Accept: application/json` HTTP header.

For example,

```sh
curl 'localhost:8123/?query=SELECT%20*%20FROM%20not_existing' -H 'Accept: application/json'
```

could have returned

```json
{                       
  "error": {                       
    "code": 60,                       
    "text": "Table default.not_existing doesn't exist",                       
    "version": "19.11.4.24 (official build)"                       
  }                       
}                       
```

An alternative would be to use `FORMAT` clause for specifying errors format too, but in that case it would not be possible to specify format for errors in `INSERT` queries.

**Comment by filimonov** [comment]
@a-rodin and what do you think about bit more universal approach of multiplexing HTTP data streams with Server-Sent Events?

See #6294

**Comment by filimonov** [comment]
See also #4971

**Comment by a-rodin** [comment]
@filimonov In this issue I'm mostly concerned about JSON formatting of the errors, but it can be combined with multiplexing of the data.

I like the idea of HTTP headers from #4971. Issue #902 is mostly the same as this one.

Currently I'm trying to add formatting options to [getCurrentExceptionMessage](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/Exception.cpp#L71) function, so that it would return the error either in the default format or as a JSON object.

**Comment by a-rodin** [comment]
@filimonov I've just noticed that implementations of server-sent events in browsers [don't support HTTP methods other than `GET`](https://stackoverflow.com/a/34285526). So for `POST` requests, such as `INSERT` queries, some other mechanism of reporting errors still might be useful.
