### ISSUE TITLE
final only on "dirty" partitions

### ISSUE THREAD

**Issue by jesse-triplewhale** [ClickHouse/ClickHouse#62736]
We have a large table with many partitions. We use the `final` modifier to perform dedup at query time, with `do_not_merge_across_partitions_select_final`. It seems it would improve performance without compromising correctness if there were a way to only run `final` on partitions with > 1 part. In our case, most of the partitions have only 1 part because we partition by date and primarily update recent dates. Does this make sense?

**Comment by den-crane** [comment]
already implemented

v23.12.1.1368-stable.md:* Extract non intersecting parts ranges from MergeTree table during FINAL processing. That way we can avoid additional FINAL logic for this non intersecting parts ranges. In case when amount of duplicate values with same primary key is low, performance will be almost the same as without FINAL. Improve reading performance for MergeTree FINAL when `do_not_merge_across_partitions_select_final` setting is set. [#58120](https://github.com/ClickHouse/ClickHouse/pull/58120) ([Maksim Kita](https://github.com/kitaisreal)).
