### ISSUE TITLE
Clickhouse v20.2.1.2120 Unable to find installation package

### ISSUE THREAD

**Issue by 15611006693** [ClickHouse/ClickHouse#62744]
Hello
  may I ask why I can't find clickhouse version 20.2.1.2120 on the official website? It's like this because we have an environment on 
 site that is this version. I would like to download this version from the official website and install it for testing in the testing environment. 
 Thank you

**Comment by Algunenano** [comment]
https://packages.clickhouse.com/repo-archive/tgz/

**Comment by 15611006693** [comment]
> https://packages.clickhouse.com/repo-archive/tgz/

Thanks

**Comment by 15611006693** [comment]
clickhouse-common-static-20.2.1.2120.tgz cannot be downloaded, and the page will become garbled after clicking on download

**Comment by 15611006693** [comment]
clickhouse-common-static-dbg-20.2.1.2120.tgz installation package is the same and cannot be downloaded

**Comment by Algunenano** [comment]
```bash
wget https://packages.clickhouse.com/repo-archive/tgz/clickhouse-common-static-20.2.1.2120.tgz
```
