### ISSUE TITLE
multi sql exec with user defined function will stuch in cluster

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/ClickHouse#62778]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).
 24.4.1.173 (official build)

> You have to provide the following information whenever possible.

**Describe what's wrong**

![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/232f0ebe-c653-470b-8f74-21a9c4c776f8)

ParallelParsingInputFormat: Parallel parsing is used  
stuck sql exec 

![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/6e7fc136-4511-478e-945e-495bf1931710)

but i exec one time is ok，in multi processes , in clusters，exec sql,  many user define function， is stuck
use 23.12.1 version ，one clickhouse instance is ok

**Comment by Algunenano** [comment]
Please provide a reproducible example and explanation of the problem

**Comment by a819721810** [comment]
my ck cluster config:
`<yandex>
    <remote_servers>
        <cb_cluster>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <priority>1</priority>
                    <host>ck1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <priority>3</priority>
                    <host>ck8</host>
                    <port>9001</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <priority>1</priority>
                    <host>ck3</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <priority>3</priority>
                    <host>ck6</host>
                    <port>9001</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <priority>1</priority>
                    <host>ck5</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <priority>3</priority>
                    <host>ck4</host>
                    <port>9001</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <priority>1</priority>
                    <host>ck7</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <priority>3</priority>
                    <host>ck2</host>
                    <port>9001</port>
                </replica>
            </shard>
        </cb_cluster>
    </remote_servers>


    <zookeeper>
        <node>
            <host>10.10.0.170</host>
            <port>2181</port>
        </node>
        <node>
            <host>10.10.0.171</host>
            <port>2181</port>
        </node>
        <node>
            <host>10.10.0.172</host>
            <port>2181</port>
        </node>
    </zookeeper>

<macros>
    <shard>01</shard>
    <replica>ck1</replica>
</macros> 

</yandex>
`


my clickhouse start script:
`
sudo --preserve-env -u 'clickhouse' /usr/bin/clickhouse-server --config-file /data/ck_master/conf/config.xml --pid-file /data/ck_master/run/clickhouse-server.pid --daemon


sudo --preserve-env -u 'clickhouse' /usr/bin/clickhouse-server --config-file /data/ck_slaver/conf/config.xml --pid-file /data/ck_slaver/run/clickhouse-server.pid --daemon
`

my Tit.py:
`
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/729f57b1-3dd4-4bc8-b64a-19d078657cb6)

`

my python client :
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/f1642053-9f31-4439-bcfc-f9450bbd2840)


![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/f1b06605-8866-4a6e-ade6-ec29d8e18c7b)



i use python client to exec  : 
`
cb_client = CHDBClientCluster(address="xxx", username=f"xxx",password="xxx")
cb_client.exec("select * from xxx where time > Tit('09:25:00')") 
`
xxx  is a table( or  distributed table)
then in single instance , is ok
in cluster one  thread , is ok
in cluster 30 thread , stuck by Tit.py  

@Algunenano

**Comment by Algunenano** [comment]
Pasting does not constitute a valid reproducible case, sorry.

You can try sharing your UDF (declaration and Python code) in a format that can be copied; and the same for the schema and queries to reproduce it, but it's clear that

**Comment by a819721810** [comment]
Tit_function.xml:
```
(base) root@ruogu:/data/ck_master/conf# cat Tit_function.xml 
<functions>
    <function>
        <type>executable</type>
        <name>Tit</name>
        <return_type>String</return_type>
        <argument>
            <type>String</type>
            <name>value</name>
        </argument>
        <format>TabSeparated</format>
        <command>Tit.py</command>
    </function>
</functions>

```


Tit.py:
```
(base) root@ruogu:/data/ck_slaver/ck_data/user_scripts# cat Tit.py 
#!/usr/bin/python3
import re
import sys


def extract_time_and_replace(text):
    time_pattern = r'\b(\d{1,2}):(\d{2}):(\d{2})(?:\.(\d{3}))?\b'
    matches = re.finditer(time_pattern, text)
    new_text = text
    for match in matches:
        hours = int(match.group(1))
        minutes = int(match.group(2))
        seconds = int(match.group(3))
        milliseconds = int(match.group(4) or 0)
        total_milliseconds = (hours * 3600 + minutes * 60 + seconds) * 1000 + milliseconds
        new_text = new_text.replace(match.group(0), str(total_milliseconds))
    return new_text


if __name__ == '__main__':
    # input_text = "The time is 9:34:56.789 or 23:45:01"
    for line in sys.stdin:
        # print(line)
        print(extract_time_and_replace(line), end="")
        sys.stdout.flush()
```

**Comment by a819721810** [comment]
python test.py:
```
import ray
import pandas as pd
import numpy as np
from ruogu import get_chdb_cluster
chdb_c = get_chdb_cluster()
ray.init(runtime_env=runtime_env,address="xxx")
@ray.remote
class TestTit(Factor):

    def __init__(self):
        super().__init__()

    def calc(self, date: str):
        print(date)
        check_table_dates('stock_base.zb', date, date)
        # sql = f'''
          
        # '''
        for i in range(100):
            sql = f'''
        SELECT * FROM
        (
            SELECT code,date,SUM(price*volume) AS factor_value FROM stock_base.zb 
            WHERE exg == 1 AND trade_flag == 'F' AND time_int < save_Tit('09:30:00') AND date == '{date}' GROUP BY code,date
            UNION ALL
            SELECT code,date,SUM(price*volume) AS factor_value FROM stock_base.zb 
            WHERE exg == 2 AND trade_flag == 'N' AND time_int < save_Tit('09:30:00') AND date == '{date}' GROUP BY code,date
        )
        '''
        # sql =f" select * from stock_base.tzb where t"
            df1 = chdb_c.command_get_df(sql)
        # print(date,len(df1))
        # self.upload_df(df1)
dates = trade_cal.range_date_list('2019-01-01', '2019-01-31', check_open=False)
dates_list = split_list_into_n_parts(dates, 3) 
for dates in dates_list:
    futures = [TestTit.remote().calc.remote(date) for date in dates]
    ray.get(futures)

```

run this， then stuck, always has this:
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/93223254-28c6-4ad8-91a7-227643307822)
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/6de50b8f-5ac4-4923-920c-464ee118357e)


but i run use one sql, is ok:
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/d4f8b5e1-d8b2-4907-ae7d-290d71592750)

**Comment by Algunenano** [comment]
Still not reproducible. Please try following your own steps and information (without any prior setup) to see if the steps are complete, which they aren't.

**Comment by a819721810** [comment]
> Still not reproducible. Please try following your own steps and information (without any prior setup) to see if the steps are complete, which they aren't.

are you use  24.4.1.173  version ?

**Comment by Algunenano** [comment]
> are you use 24.4.1.173 version ?

I'm using master/HEAD, but that's irrelevant. You are not providing data, nor which queries to execute and how (just a random script without any explanation).

With simple data like:
```sql
Select * from numbers_mt(1000000000) WHERE save_Tit('09:30:' || number) = ''
```
It does not fail or get stuck.

Which is why you should try to follow your own steps to verify if they are even possible to be executed by somebody else

**Comment by Algunenano** [comment]
Not reproducible
