### ISSUE TITLE
cgroups v2 detection fails in containerized environment

### ISSUE THREAD

**Issue by mouchar** [ClickHouse/ClickHouse#62788]
This is a follow-up issue based on late discussion in #59435

**Describe the unexpected behaviour**
New cgroups v2 detection introduced in ad13a57b doesn't work when clickouse runs in container. 

**How to reproduce**
* ClickHouse local version 24.3.2.23 (official build).
* Start in docker on a system with cgroups v2 and memory limit set.
```
docker run -it --rm --ulimit nofile=262144:262144  -m 2g clickhouse/clickhouse-server:24.3.2.23-alpine
```

**Expected behavior**
`CgroupsMemoryUsageObserver` properly detects cgroups v2 and sets max memory based on `memory.max` cgroup setting.

**Error message and/or stacktrace**
```
2024.04.19 08:46:53.884176 [ 42 ] {} <Error> Application: Disabling cgroup memory observer because of an error during initialization: Code: 107. DB::Exception: Cannot find cgroups v1 or v2 current memory file. (FILE_DOESNT_EXIST), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbcedbb
1. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x0000000007668f23
2. DB::CgroupsMemoryUsageObserver::CgroupsMemoryUsageObserver(std::chrono::duration<long long, std::ratio<1l, 1l>>) @ 0x000000000cceadce
3. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000cd5cb5d
...
```

**Additional context**
The problem is in detection of enabled controllers for cgroup hierarchies, when it is checked within container. The `/sys/fs/cgroup/cgroup.subtree_control` is empty and therefore the check `cgroupsV2MemoryControllerEnabled()` returns false.

Example:
```
# on physical host:
$ head /sys/fs/cgroup/cgroup.controllers /sys/fs/cgroup/cgroup.subtree_control
==> /sys/fs/cgroup/cgroup.controllers <==
cpuset cpu io memory hugetlb pids rdma misc

==> /sys/fs/cgroup/cgroup.subtree_control <==
cpuset cpu io memory hugetlb pids rdma misc

# in container:
docker run   --rm -m 100m alpine:3.10 head /sys/fs/cgroup/cgroup.controllers /sys/fs/cgroup/cgroup.subtree_control
==> /sys/fs/cgroup/cgroup.controllers <==
cpuset cpu io memory hugetlb pids rdma misc

==> /sys/fs/cgroup/cgroup.subtree_control <==

```

cc: @rschu1ze @Stanislav-Vlasov

**Comment by rschu1ze** [comment]
I made [a fix](https://github.com/ClickHouse/ClickHouse/pull/62900) but then realized something.

The [cgroups v2 docs](https://www.kernel.org/doc/Documentation/admin-guide/cgroup-v2.rst) say

```
Top-down Constraint
~~~~~~~~~~~~~~~~~~~

Resources are distributed top-down and a cgroup can further distribute
a resource only if the resource has been distributed to it from the
parent.  This means that all non-root "cgroup.subtree_control" files
can only contain controllers which are enabled in the parent's
"cgroup.subtree_control" file.  A controller can be enabled only if
the parent has the controller enabled and a controller can't be
disabled if one or more children have it enabled.
```

In other words, if like here the top-level `cgroups.subtree_control` file (`/sys/fs/cgroup/cgroup.subtree_control`) is empty, then all child `cgroups.subtree_control` files will be empty too. So while my fix (which checks the existence of "memory" recursively ascending, starting from the bottom-most file) is generally useful, it won't help with this issue. I suspect there is a configuration error with Docker - because why else should *all* cgroups controllers be disabled?
