### ISSUE TITLE
<Warning> CgroupsMemoryUsageObserver: Exceeded sort memory limit

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/ClickHouse#62783]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/fa73a5b0-6411-4fac-b4e6-c3e177711a74)

what is mean for CgroupsMemoryUsageObserver: Exceeded sort memory limit

**Comment by rschu1ze** [comment]
[Here](https://github.com/ClickHouse/ClickHouse/blob/9b9f409805acb2f3d8c4427537bac91168d7f33c/src/Common/CgroupsMemoryUsageObserver.h#L9) is what the soft limit means:

<img width="913" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/100446237/b74a088d-bb46-41dd-a50e-ab4722ff193e">

**Comment by rschu1ze** [comment]
@a819721810 CgroupsMemoryUsageObserver has nothing to do with the (disk) size of tables or table partitions. 

CgroupsMemoryUsageObserver compares
- the memory consumption of the ClickHouse server process according to ClickHouse's internal memory tracker with
- the memory consumption of the ClickHouse server process according to Linux cgroups.

The purpose of CgroupsMemoryUsageObserver is to counter-balance possible tracking inaccuracies of the internal memory tracking. The exact thresholds for when that happens are configurable via server settings [cgroup_memory_watcher_hard_limit_ratio](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#cgroup_memory_watcher_hard_limit_ratio) and [cgroup_memory_watcher_soft_limit_ratio](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#cgroup_memory_watcher_soft_limit_ratio).

You generally might want to ignore the log message, it is of information purpose only.
