### ISSUE TITLE
Aggregation function `max` produces wrong answer(another aggregation functions have the same issue)

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#62780]
**Describe what's wrong**

Aggregation function `max` produces wrong answer(another aggregation functions have the same issue)

It is clear if you look at the sample SQL.
```
create table Nullable_Event (ID UInt64, val Nullable(UInt64), seq Nullable(UInt64), key1 Nullable(UInt64), key2 Nullable(UInt64)) engine = MergeTree() order by ID;
insert into Nullable_Event values (1, null, 1, 1, null)(2, null, 2, 1, null)(3, 300, 3, 1, null)(4, 400, 4, 1, 2)(5, 500, 5, null, 2)(6, 600, 6, null, 2)(7, null, 7, 2, null);
select '-- the key2:2 group produces a wrong result NULL';
select key2, max(seq) from Nullable_Event  group by key2;
select '-- if apply a filter to only aggregate key2:2 group, it produces right anwser';
select key2, max(seq) from Nullable_Event where key2=2 group by key2;
select 'another aggregation functions have the same issue';
select key2, avg(seq) from Nullable_Event  group by key2;
```

https://fiddle.clickhouse.com/9b42e5fd-4587-46e6-b0d2-c54f2d6eab23

**Does it reproduce on the most recent release?**
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)
v24.2.2.71

**Comment by Alex-Cheng** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/1518453/e0477659-2d7d-4987-807b-a58bff87ea01)

I think this issue may be high priority.

**Comment by Algunenano** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/61393

**Comment by Alex-Cheng** [comment]
> Fixed in #61393

It was ported into 24.2 at pr #61845 , but the tag `v24.2.2.71-stable` does not contain the bug fixing. Is `v24.2.2.71-stable` a stable one?

**Comment by den-crane** [comment]
```
cd clickhouse/docs/changelogs/
grep 61393 *

v23.12.6.19-stable.md:* Fix consecutive keys optimization for nullable keys [#61393](https://github.com/ClickHouse/ClickHouse/pull/61393) ([Anton Popov](https://github.com/CurtizJ)).
v24.1.8.22-stable.md:* Fix consecutive keys optimization for nullable keys [#61393](https://github.com/ClickHouse/ClickHouse/pull/61393) ([Anton Popov](https://github.com/CurtizJ)).
v24.3.1.2672-lts.md:* Fix consecutive keys optimization for nullable keys [#61393](https://github.com/ClickHouse/ClickHouse/pull/61393) ([Anton Popov](https://github.com/CurtizJ)).
```

**Comment by den-crane** [comment]
v24.2.2.71 was released before that. It will be in 24.2.3

**Comment by Alex-Cheng** [comment]
> v24.2.2.71 was released before that. It will be in 24.2.3

Yes. I found the branch `24.2` has the bug fixing, so I am wondering that if I should merge a "stable" branch rather than stable tag when I upgrade my customization version to mainstream of CH. In other words, what is the more stable code to which I should upgrade?

**Comment by Alex-Cheng** [comment]
BTW, I am a little bit confused about the suffix of tag "stable" and "lts". I know "lts" is "long term support". But it is a tag and the tag will not update anymore, however a branch will be updated for long time.
