### ISSUE TITLE
Materialized view dependencies not being set correctly

### ISSUE THREAD

**Issue by arvindbr95** [ClickHouse/ClickHouse#62782]
I am trying to create a materialized view with the following structure:

```sql
CREATE MATERIALIZED VIEW mv (`id` String,
`updated` DateTime('UTC'),
`Name` String) ENGINE = ReplacingMergeTree(updated) 
PRIMARY KEY id
ORDER BY id AS
SELECT
	a.id AS id,
	a.updated AS updated,
        t2.Name AS Name
FROM
	table_1 AS a
LEFT JOIN table_2 AS t2 ON
	a.`t2id` = t2.id
```

However when i query the dependencies of `mv`, using the following query:

`SELECT name, dependencies_table, create_table_query FROM system.tables;`

I see that only `table_1` lists `mv` as a dependency.

The expected behaviour is that I should see 2 tables:

`table_1`
`table_2`

list the table `mv` as a dependency since it is formed out of a JOIN of these 2 tables. Please check why this is happening.

(This is a repeat of [this issue](https://github.com/ClickHouse/ClickHouse/issues/62635) with a simplified example)

**Comment by nvartolomei** [comment]
Dependencies table are a list of materializing views/queries that are to be evaluated upon insertion.

> The answer is emphatically yes. This blog article shows how. If you are looking for a quick answer, here it is: materialized views trigger off the left-most table of the join.  The materialized view will pull values from right-side tables in the join but will not trigger if those tables change.
> —https://altinity.com/blog/2020-07-14-joins-in-clickhouse-materialized-views

**Comment by arvindbr95** [comment]
Hi @nvartolomei - In this case since table_2 is evaluated upon insertion, shouldn't it be part of the Materialized view's dependencies?

**Comment by arvindbr95** [comment]
Reading the article, I see
>  If the query in the materialized view definition includes joins, the source table is the left-side table in the join.

So it does seem to be intentional and isn't a bug. Can you shed light on why there is only a single source table for a materialized view? How can we get around this if we want multiple tables to act as source tables for a MV?

**Comment by den-crane** [comment]
@arvindbr95 

>What is the recommended approach if we want multiple tables to act as source tables for a MV?

multiple mat view https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf
refreshable mat view https://clickhouse.com/docs/en/sql-reference/statements/create/view#refreshable-materialized-view
