### ISSUE TITLE
How to use AggregateMergeTree for argMax

### ISSUE THREAD

**Issue by gner56** [ClickHouse/ClickHouse#62790]
https://fiddle.clickhouse.com/cc2db840-551e-435a-8f90-c41ee99f134c

In this fiddle here, I have a materialized view that aims to capture the latest row in a "5 minute grouping".

To elaborate, given a table with three columns (id: String, ts: datetime, price: float),
i want to identify the row that has the latest value of ts in a 5min group.

For example, in a 5min group identified by "2024-04-19 00:15:00", we can consider "00:10, 00:11, 00:12, 00:13, 00:14". We take the latest of these rows and return it.

# Trial Data
INSERT INTO test_append_only (id, ts, price) 
VALUES 
('A', '2024-04-19 00:00:00', 1), 
('A', '2024-04-19 00:01:00', 2), 
('A', '2024-04-19 00:02:00', 3),
('A', '2024-04-19 00:03:00', 4), 
('A', '2024-04-19 00:04:00', 5), 
('A', '2024-04-19 00:05:00', 6), 
('A', '2024-04-19 00:06:00', 7), 

# Expected Result
A	2024-04-19 00:00:00.000	5 -- because toStartOfInterval(... 00:04,) == 00:00
A	2024-04-19 00:05:00.000	7 -- because toStartOfInterval(... 00:06) == 00:05

# Actual result (in the fiddle)
A	2024-04-19 00:00:00.000	1
A	2024-04-19 00:05:00.000	6

Question: Why is the argMax state not being captured? Shouldn't it resolve correctly to the latest value in the 5 minute group?

Thank you in advance

**Comment by den-crane** [comment]
>toStartOfInterval(ts - toIntervalMinute(1),  toIntervalMinute(5)) + toIntervalMinute(5) AS ts, 

????

**Comment by gner56** [comment]
@den-crane

Sorry, that is just a business requirement but I've updated the fiddle and the issue description to simplify that part so that its easier to understand

**Comment by den-crane** [comment]
You pass rounded ts instead of real ts https://fiddle.clickhouse.com/dee2c899-3d01-48d2-9005-f06424985a40

**Comment by gner56** [comment]
Very helpful tips @den-crane, thanks alot!
