### ISSUE TITLE
24.2 different result of `largestTriangleThreeBuckets` on x86 and arm64

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#62803]
https://fiddle.clickhouse.com/1c945490-a6f4-4b9d-8bc0-61b065fb9857
version: 24.2.2.71 
```
x86:
{"largestTriangleThreeBuckets(4)(col1, col2)":[[-1.7976909999999999e308,0],[-1.4671934308482398e307,201],[0,0],[1.7976909999999999e308,255]]}

arm64:
{"largestTriangleThreeBuckets(4)(col1, col2)":[[-1.7976909999999999e308,0],[-1.4671934308482398e307,201],[-1.5778850368104598e49,163],[1.7976909999999999e308,255]]}
```

**Comment by alexey-milovidov** [comment]
Let's delete this function.

**Comment by wxybear** [comment]
@alexey-milovidov hi, please assign this issue to me, I have fixed a bug of this function before, but I didn't have an arm dev machine before, so I didn't test it fully. I will check it this week

**Comment by wxybear** [comment]
I added some test logs and found that some of the data in the test data set was too large, so some of the intermediate results were **inf** or **nan**. When calculating -inf - (-inf), the result on x86 was **nan**(IEEE 754 standard?) , and the result of running the code arm cross-compilation is **inf**. 

Will other functions or codes encounter similar problems and how to solve them?

**Comment by alexey-milovidov** [comment]
Thank you! This is a normal behavior.
