### ISSUE TITLE
Auto Increment?

### ISSUE THREAD

**Issue by tchaton** [ClickHouse/ClickHouse#62825]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

Hey there,

I am using clickhouse to ingest metrics with gorm. I am keeping an incrementing counter integer for each entry and using to sub-sampling the metrics based on the number of rows and modulo.

I wondered if there were a special directives to make sub-sampling faster ?

**Comment by alexey-milovidov** [comment]
You can also use `rand()` for sampling.
