### ISSUE TITLE
build failed : ld.lld: error: duplicate symbol: DB::registerFunctionHas

### ISSUE THREAD

**Issue by h1k** [ClickHouse/ClickHouse#62831]
**ClickHouse version:**
v24.3.2.23-lts

**Operating system**
> CentOS7 Linux  3.10.0-1160.11.1.el7.x86_64 x86_64 GNU/Linux

**Cmake version**
cmake version 3.20.6
**Ninja version**
ninja 1.10.0
**Compiler name and version**
clang-18
**Full cmake and/or ninja output**
```
ld.lld: error: duplicate symbol: DB::registerFunctionHas(DB::FunctionFactory&)
>>> defined at has.cpp:11 (./build/../src/Functions/array/has.cpp:11)
>>>            has.cpp.o:(DB::registerFunctionHas(DB::FunctionFactory&)) in archive src/libdbms.a
>>> defined at has.cpp
>>>            src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./has.cpp.o:(.text+0x0)

ld.lld: error: duplicate symbol: DB::createInternalFunctionHasOverloadResolver()
>>> defined at has.cpp:14 (./build/../src/Functions/array/has.cpp:14)
>>>            has.cpp.o:(DB::createInternalFunctionHasOverloadResolver()) in archive src/libdbms.a
>>> defined at has.cpp
>>>            src/Functions/array/CMakeFiles/clickhouse_functions_array.dir/./has.cpp.o:(.text+0x80)
clang-18: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Algunenano** [comment]
Please share how you build CH. What flags are you passing to cmake?

**Comment by h1k** [comment]
> Please share how you build CH. What flags are you passing to cmake?
The simplest command is
cmake -DCMAKE_INSTALL_PREFIX=/my_dir/local  ../
ninja -j 80

**Comment by alexey-milovidov** [comment]
Does it reproduce if you build it exactly as in our CI?
You can find CI logs at checks of every commit.

**Comment by h1k** [comment]
> Does it reproduce if you build it exactly as in our CI? You can find CI logs at checks of every commit.

Sorry, I don't know how to find the build command in the CI log. I tried all these parameters and it didn't work
-DCMAKE_MAKE_PROGRAM=ninja   -DCMAKE_C_COMPILER=/usr/local/bin/clang-18 -DCMAKE_ASM_COMPILER=/usr/local/bin/clang-18 -DCMAKE_CXX_COMPILER=/usr/local/bin/clang-18  -DENABLE_TESTS=1 -DENABLE_EXAMPLES=1 -DENABLE_UTILS=1 -DENABLE_BUILD_PROFILING=1  ../

**Comment by Algunenano** [comment]
It seems + Functions/CMakeLists.txt` is incorrect, but I can't reproduce the failure in my local machine

Could you test a change like this, please?

```patch
$ git diff
diff --git a/src/Functions/CMakeLists.txt b/src/Functions/CMakeLists.txt
index 11bcc948288..0f3b5bfe19b 100644
--- a/src/Functions/CMakeLists.txt
+++ b/src/Functions/CMakeLists.txt
@@ -13,7 +13,6 @@ extract_into_parent_list(clickhouse_functions_sources dbms_sources
     multiIf.cpp
     multiMatchAny.cpp
     checkHyperscanRegexp.cpp
-    array/has.cpp
     CastOverloadResolver.cpp
 )
 extract_into_parent_list(clickhouse_functions_headers dbms_headers
diff --git a/src/Functions/array/CMakeLists.txt b/src/Functions/array/CMakeLists.txt
index 2800b5b4e28..a1ea5704198 100644
--- a/src/Functions/array/CMakeLists.txt
+++ b/src/Functions/array/CMakeLists.txt
@@ -1,5 +1,7 @@
 include("${ClickHouse_SOURCE_DIR}/cmake/dbms_glob_sources.cmake")
 add_headers_and_sources(clickhouse_functions_array .)
+extract_into_parent_list(clickhouse_functions_array_sources dbms_sources has.cpp)
+
 add_library(clickhouse_functions_array OBJECT ${clickhouse_functions_array_sources} ${clickhouse_functions_array_headers})
 target_link_libraries(clickhouse_functions_array PRIVATE dbms clickhouse_functions_gatherutils)
 
```

**Comment by h1k** [comment]
> 看来 + Functions/CMakeLists.txt` 不正确，但我无法在本地计算机中重现该故障
> 
> 您能测试一下这样的改变吗？
> 
> ```diff
> $ git diff
> diff --git a/src/Functions/CMakeLists.txt b/src/Functions/CMakeLists.txt
> index 11bcc948288..0f3b5bfe19b 100644
> --- a/src/Functions/CMakeLists.txt
> +++ b/src/Functions/CMakeLists.txt
> @@ -13,7 +13,6 @@ extract_into_parent_list(clickhouse_functions_sources dbms_sources
>      multiIf.cpp
>      multiMatchAny.cpp
>      checkHyperscanRegexp.cpp
> -    array/has.cpp
>      CastOverloadResolver.cpp
>  )
>  extract_into_parent_list(clickhouse_functions_headers dbms_headers
> diff --git a/src/Functions/array/CMakeLists.txt b/src/Functions/array/CMakeLists.txt
> index 2800b5b4e28..a1ea5704198 100644
> --- a/src/Functions/array/CMakeLists.txt
> +++ b/src/Functions/array/CMakeLists.txt
> @@ -1,5 +1,7 @@
>  include("${ClickHouse_SOURCE_DIR}/cmake/dbms_glob_sources.cmake")
>  add_headers_and_sources(clickhouse_functions_array .)
> +extract_into_parent_list(clickhouse_functions_array_sources dbms_sources has.cpp)
> +
>  add_library(clickhouse_functions_array OBJECT ${clickhouse_functions_array_sources} ${clickhouse_functions_array_headers})
>  target_link_libraries(clickhouse_functions_array PRIVATE dbms clickhouse_functions_gatherutils)
>  
> ```

Thank you for your support. I changed my local file as you did and the build still has the error: 
```
ld.lld: error: undefined symbol: DB::createInternalFunctionHasOverloadResolver()
>>> referenced by ArrayExistsToHasPass.cpp:87 (./build/../src/Analyzer/Passes/ArrayExistsToHasPass.cpp:87)
>>>               ArrayExistsToHasPass.cpp.o:(DB::InDepthQueryTreeVisitorWithContext<DB::(anonymous namespace)::RewriteArrayExistsToHasVisitor>::visit(std::__1::shared_ptr<DB::IQueryTreeNode>&)) in archive src/libdbms.a
```

**Comment by Algunenano** [comment]
I'm sorry, but debugging this remotely without a reproducer is extremely cumbersome.

It seems that your setup (distro, compiler, implicit flags, whatever) is somewhat different from the default and it's detecting problems that we don't detect neither in CI or the dev machines. You can either try fixing it by yourself and sending a PR or download the prebuilt binaries that we provide.
