### ISSUE TITLE
column_data_compressed_bytes is always zero in system.parts_columns

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#62847]
Columns `column_data_compressed_bytes` and `column_data_uncompressed_bytes` in table `system.parts_columns` are always `0`. However there is not empty table on the instance.
Repro: https://fiddle.clickhouse.com/906332f8-e944-45c1-8614-a008c617cb91

**Comment by den-crane** [comment]
expected for compact parts? All columns are stored in a single data.bin file.

https://fiddle.clickhouse.com/cb919e70-22f4-427e-ae46-206d98e06700

**Comment by michaelritsema** [comment]
@CheSema filed this based on my issue. I can confirm that the  index_granularity_bytes=0 solved this problem for me.

**Comment by michaelritsema** [comment]
@den-crane I understand, thanks for the clarification
