### ISSUE TITLE
Consider Adding Adding Software Bill of Materials (SBoM)

### ISSUE THREAD

**Issue by franchb** [ClickHouse/ClickHouse#62864]
# Consider Adding Software Bill of Materials (SBoM) for ClickHouse Release Binaries

## Summary

There is currently a lack of visibility into the third-party code and its vulnerabilities within ClickHouse, which is a substantial C++ project with numerous imported git submodules. This can present challenges for users in managing security and compliance.

In an effort to enhance the security posture and provide transparency to end-users, it would be beneficial to consider the generation and publication of Software Bill of Materials (SBoM) for the release binaries of ClickHouse.

## Benefits of SBoM:

An SBoM would provide a comprehensive inventory of all components, libraries, and modules included in the ClickHouse binaries. This can greatly assist in:

- **Vulnerability Tracking**: Quickly identifying if any components are affected by newly discovered vulnerabilities.
- **License Compliance**: Ensuring all open-source licenses are complied with and clearly documented.
- **Supply Chain Security**: Providing visibility into the software supply chain, enabling users to assess risk and respond to threats more effectively.

## Use case

As a security researcher, I require detailed knowledge of the software versions and components used within the ClickHouse project. The availability of a Software Bill of Materials (SBoM) would enable me to:

- **Assess Security Risks**: Quickly evaluate the security posture of the ClickHouse binaries by having accurate details of the third-party components and their versions.
- **Conduct Audits**: Efficiently perform audits and compliance checks against known vulnerability databases to ensure that any security implications are proactively addressed.

## Describe the solution you'd like

 I understand that generating an SBoM for a complex project such as ClickHouse may be challenging due to the numerous submodules and dependencies. However, there are tools and standards available that can aid in this process, such as:

- **SPDX**: Adoption of the Software Package Data Exchange (SPDX) standard to list all the components within the ClickHouse build environment.
- **CycloneDX**: Utilization of CycloneDX which is a lightweight SBoM specification designed for use in application security contexts and supply chain component analysis.

[SBoM Benchmark ](https://sbombenchmark.dev/)  is a collection of SBoM examples in CycloneDX and SPDX formats. These examples are generated for common open source repositories and container images using open-source SBoM tools.

Additionally, the examples included above have been evaluated against the SBoM Quality Score. You can use these SBoM samples to improve your understanding of how SBoMs work in practice and common pitfalls with SBoM.

## Describe alternatives you've considered

Consider using [Syft](https://github.com/anchore/syft/tree/main), and possibly later integrating with [Grype](https://github.com/anchore/grype) for vuln scanning.

## Additional context

Adding SBoM artifacts to the ClickHouse release process could significantly improve the ability of users to manage security risks associated with third-party dependencies. I would be interested to hear the maintainers' thoughts on this proposition and whether this is something that could be implemented in the future.

Thank you for considering this enhancement.

## Links

- [What is an SBOM (software bill of materials)?](https://edu.chainguard.dev/open-source/sbom/what-is-an-sbom/) at chainguard.dev Academy.

**Comment by alexey-milovidov** [comment]
Request it at https://trust.clickhouse.com/
