### ISSUE TITLE
select  from system.dictionaries

### ISSUE THREAD

**Issue by baslo2** [ClickHouse/ClickHouse#62865]
ClickHouse version 23.12.2.59

create test dictionary with schema

```
CREATE DICTIONARY default.dict1
(
    `LocationID` UInt16 DEFAULT 0, 
    `Borough` String, 
    `Zone` String, 
    `service_zone` String
) 
PRIMARY KEY LocationID 
SOURCE(HTTP(URL 'https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/taxi_zone_lookup.csv' FORMAT 'CSVWithNames')) 
LIFETIME(MIN 0 MAX 100) 
LAYOUT(HASHED())
```

make quary in db lower

```
select 
	database,
	name,
	source,
	lifetime_min,
	lifetime_max 
from system.dictionaries
```

db return that

![image](https://github.com/ClickHouse/ClickHouse/assets/84476539/dc1a0cf7-505e-4029-b8dc-c127aa2aae68)

i think fields source, lifetime_min, lifetime_max will not be blank. and aslo i didn't find field wich must store information about option LAYOUT.

**Comment by SaltTan** [comment]
It's because the dictionary has not been loaded yet.
By default dictionaries are loaded during the first request (dictionaries_lazy_load)
