### ISSUE TITLE
Select DateTime less Date doesn't work

### ISSUE THREAD

**Issue by dkhodorchenko** [ClickHouse/ClickHouse#6287]
Comparison DateTime and Date in SELECT doesn't work
When I limit DateTime from below it works normally. But limit on top - doesn't work
![Select](https://user-images.githubusercontent.com/51990161/62343237-31251d00-b514-11e9-826a-e8e79ed0b303.png)

**Comment by den-crane** [comment]
```
SELECT now() > (today() - 1)

┌─greater(now(), minus(today(), 1))─┐
│                                 1 │
└───────────────────────────────────┘

SELECT now() < (today() + 1)

┌─less(now(), plus(today(), 1))─┐
│                             1 │
└───────────────────────────────┘
```

probably index related issue. 

@dkhodorchenko please check a result of 
select count()
from radacct
where identity(acctstarttime) < ....

**Comment by dkhodorchenko** [comment]
![identity](https://user-images.githubusercontent.com/51990161/62434417-645ceb80-b762-11e9-9416-550efc9212ba.png)

With identity it works

**Comment by den-crane** [comment]
@dkhodorchenko can you show radacct DDL ? partition / orderby section.
I suspect this is a duplicate for https://github.com/yandex/ClickHouse/issues/5131

**Comment by den-crane** [comment]
STR:

```
create table radacct (acctstarttime DateTime) Engine=MergeTree order by acctstarttime;
insert into radacct select now() + number%545 from numbers(10000);
insert into radacct select '2019-09-01 00:01:01';

select count() from radacct 
where acctstarttime between toDate('2019-09-01') and toDate('2019-09-02');

Ok.
0 rows in set. Elapsed: 0.002 sec.


select count() from radacct 
where acctstarttime between toDateTime(toDate('2019-09-01')) and toDateTime(toDate('2019-09-02'));
┌─count()─┐
│       1 │
└─────────┘


select count() from radacct 
where identity(acctstarttime) between toDate('2019-09-01') and toDate('2019-09-02');
┌─count()─┐
│       1 │
└─────────┘

```

19.13.1.1010 (official build)

related https://github.com/yandex/ClickHouse/issues/6248

**Comment by dkhodorchenko** [comment]
`ENGINE = MergeTree
 PARTITION BY toYYYYMM(acctstarttime)
 ORDER BY (acctstarttime)
  `

**Comment by den-crane** [comment]
still relevant.  Still wrong query result.

**Comment by alexey-milovidov** [comment]
@CurtizJ This issue is still relevant.
