### ISSUE TITLE
Fix elapsed column in system.processes (10x error) - 2

### ISSUE THREAD

**Issue by berlicon** [ClickHouse/ClickHouse#62882]
It seems that system.processes.elapsed column shows value 10x bigger than expected.
I checked that and it shows 100 for query which is running for 10 seconds.
Please check and fix code or spec:
https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/operations/system-tables/processes.md

The bug may be introduced in this MR: https://github.com/ClickHouse/ClickHouse/pull/46047

**Comment by Algunenano** [comment]
I can't reproduce it. What query are you executing and what CH version?

**Comment by berlicon** [comment]
Any long query: 
SELECT *, generateUUIDv4() from t1 --40m rows
or
insert into t2(v) SELECT v from t2 --40m rows

Clickhouse | 23.1.2.9

**Comment by Algunenano** [comment]
Please upgrade
