### ISSUE TITLE
Clickhouse Play browser limiting the display of rows to a random value after 1000 for a query(which returns 1900 rows) and we are also unable to unable to set max_result_rows and max_result_bytes parameter to change this limit. Please let us know a fix for this

### ISSUE THREAD

**Issue by Sindhujareddy998** [ClickHouse/ClickHouse#62883]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
Play web ui limiting the no if rows to some threshold value but if we connect via jdbc it is returning results as expected. The parameters max_result_rows and max_result_bytes if we set to higher value they are not reflecting in system.settings tables neither query is performing as expected to the values that are set

expected number of rows- 1900
displaying random number each time: 1200,1500 etc

**Comment by alexey-milovidov** [comment]
ClickHouse Playground is configured this way. You cannot change the settings for it.
