### ISSUE TITLE
I took a screenshot of a `sumIf` function for you

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/ClickHouse#62890]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).
24.4.1.173 

distributed table: stock_base.new_ozw
**Describe what's wrong**
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/e2724912-64b1-447f-93fc-b3beb0db7190)
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/defd67c9-dd67-4b53-bae7-d99dfb6dba1b)

 24.3.1.1034 is ok
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/cd830931-0058-4df5-af27-cb98bcedc165)
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/d45f3305-fc51-4ffc-870c-410713628065)

**Comment by a819721810** [comment]
schema:
```
CREATE TABLE stock_base.new_ozw
(

    `date` Date,

    `code` String ,

    `date_tims` DateTime64(3,
 'Asia/Shanghai') ,

    `tims_int` Int32 ,

    `date_time` DateTime('Asia/Shanghai') ,

    `time_int` Int32 ,

    `exg` UInt8 ,

    `price` Nullable(Float64) ,

    `volume` Nullable(Int64) ,

    `type` String ,

    `ix` Int32,

    `zbp1` Nullable(Float64),

    `zbv1` Nullable(Int64),

    `zbav2` Nullable(Int64),

    `zbbv2` Nullable(Int64),

    `pclose` Nullable(Float64),

    `ztprice` Nullable(Float64),

    `dtprice` Nullable(Float64)
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMM(date)
PRIMARY KEY (date,
 code)
ORDER BY (date,
 code,
 exg,
 ix,
 tims_int)
SETTINGS index_granularity = 8192
```

**Comment by Algunenano** [comment]
Please provide a reproducible example, not screenshots. Also, explain what you expect and what you get.

**Comment by a819721810** [comment]
in 24.4.1.173 distributed table: stock_base.new_ozw:
```
with
    '2024-01-04' as date_,
    t1 as (select *,
                  if(type == '2B', volume, 0) as vol
           from stock_base.new_ozw
           where and(date == date_, tims_int >= Tit('09:24:59.700'))
           order by ix),

    d1 as (select date,
                  code,
                  sum(CASE
                          WHEN type == '2B' THEN volume
                          ELSE 0
                      END)                                                 as b_case,
                  sum(if(type == '2B',volume, 0))                          as b_if,
                  sumIf(volume, type == '2B')                              as b_if2,
                  sum(vol)                                                 as b_vol
           from t1
           group by code, date

           )
select * from d1 where code == '002140'
```
b_if is NULL，

```
with
    '2024-01-04' as date_,
    t1 as (select *,
                  if(type == '2B', volume, 0) as vol
           from stock_base.new_ozw
           where and(date == date_, tims_int >= Tit('09:24:59.700'))
           order by ix),

    d1 as (select date,
                  code,
                  sum(CASE
                          WHEN type == '2B' THEN volume
                          ELSE 0
                      END)                                                 as b_case,
                  sum(if(type == '2B',volume, 2))                          as b_if,
                  sumIf(volume, type == '2B')                              as b_if2,
                  sum(vol)                                                 as b_vol
           from t1
           group by code, date

           )
select * from d1 where code == '002140'
```
b_if is 4

**Comment by Algunenano** [comment]
Yeah, similar problem again. Without data it's impossible to reproduce anything without spending precious time trying to understand it.

You can either provide a minimum reproducible example that somebody can actually execute (I'd recommend using https://fiddle.clickhouse.com/) or wait until somebody else does.

**Comment by a819721810** [comment]
> Yeah, similar problem again. Without data it's impossible to reproduce anything without spending precious time trying to understand it.
> 
> You can either provide a minimum reproducible example that somebody can actually execute (I'd recommend using https://fiddle.clickhouse.com/) or wait until somebody else does.


https://fiddle.clickhouse.com/723feab7-3453-4e92-b5c9-2ff62e532747

https://fiddle.clickhouse.com/96762781-5e3a-40a6-938b-9650b317f51b

**Comment by Algunenano** [comment]
Thank you. It's much simpler to see now.

It seems to be a problem with the new analyzer. `SETTINGS allow_experimental_analyzer = false;` fixes it (temporarily)

**Comment by den-crane** [comment]
shorter example https://fiddle.clickhouse.com/83c56f9f-abdb-43dd-89f4-75a959392771

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/85220163-ca09-43b5-9f5b-45c17759d5ee

**Comment by den-crane** [comment]
And sumIf worked always like this https://fiddle.clickhouse.com/ece2dab5-51e8-4a5d-94ca-f3544bbaffd0
which is not expected for me.

**Comment by den-crane** [comment]
The problem is in `optimize_rewrite_aggregate_function_with_if`.
In case of Nullable type it's not valid to rewrite `sum(if(` to `sumIf`.
https://fiddle.clickhouse.com/337b3656-b5f3-41d0-83fe-b98e49c533a0

I would disable `optimize_rewrite_aggregate_function_with_if` by default.

**Comment by Algunenano** [comment]
> I would disable optimize_rewrite_aggregate_function_with_if by default.

That's a really bad idea. It should either be fixed or removed completely. Otherwise we keep maintaining broken passes forever.

**Comment by Algunenano** [comment]
> I meant as a quick fix.

:+1: Yes, temporarily until the next minor release it's ok to disable only `optimize_rewrite_aggregate_function_with_if`.

It only affects the analyzer because it was never introduced in the old infrastructure (thankfully).
