### ISSUE TITLE
Как в clickhouse получить значения, уникальные по части столбцов

### ISSUE THREAD

**Issue by KatRRina** [ClickHouse/ClickHouse#62894]
У меня старая версия clickhouse и DISTINCT ON не доступен. Допустим, у меня есть 5 столбцов и мне надо получить уникальные значения по 3-м из них. Как это сделать?
Как получить значения без дубликатов по части стобцов, а если дубликаты есть, то взять первое значение после сортировки по уникальным стобцам

**Comment by UnamedRus** [comment]
```
SELECT key_a, key_b, any(value), any(value_2) FROM table GROUP BY key_a, key_b

SELECT * FROM table LIMIT 1 BY key_a, key_b
```

**Comment by KatRRina** [comment]
> ```
> SELECT key_a, key_b, any(value), any(value_2) FROM table GROUP BY key_a, key_b
> 
> SELECT * FROM table LIMIT 1 BY key_a, key_b
> ```

Использование any даёт взятие любого значения из группы. А мне надо при началичии дубликатов по части стобцов брать первую строку после сортировки по уникальным столбцам.

**Comment by UnamedRus** [comment]
> А мне надо при началичии дубликатов по части стобцов брать первую строку после сортировки по уникальным столбцам.

Define первую

Пример таблицы и нужного результата
