### ISSUE TITLE
clickhouse  получения уникальынх значение по части столбцов

### ISSUE THREAD

**Issue by KatRRina** [ClickHouse/ClickHouse#62895]
У меня старая версия clickhouse и DISTINCT ON не доступен. Допустим, у меня есть 5 столбцов и мне надо получить уникальные значения по 3-м из них. Как это сделать?
Как получить значения без дубликатов по части стобцов, а если дубликаты есть, то взять первое значение после сортировки по уникальным стобцам

версия clickhouse 20.5.3.27

**Comment by Algunenano** [comment]
This is duplicated and an obsolete version. Please upgrade to a supported release
