### ISSUE TITLE
the inverted text index(column) and final modifiers are not effective when used together

### ISSUE THREAD

**Issue by myBigbug** [ClickHouse/ClickHouse#62902]
> (you don't have to strictly follow this form)

**Use case**

### 1、when my sql statement without final
```sql
explain indexes = 1
select count(1) from my_table where word like '%phone%'
```
output
```
Indexes:
    Skip                                                     
              Name: idx_word                                         
              Description: inverted GRANULARITY 2                    
              Parts: 45/51                                           
              Granules: 736/745 
```
### 2、when my sql statement with final 
```sql
explain indexes = 1
select count(1) from my_table final where word like '%phone%'
```
output
```
No secondary index
```

**Comment by Algunenano** [comment]
What's the schema of the table?

Also, keep in mind that it's not always possible to apply many optimizations or indexes when using FINAL because the index belongs to the source parts, not the parts merged after final. It might be possible to implement some optimizations in the CH side at some point though

**Comment by myBigbug** [comment]
CREATE TABLE my_table
(
id Int64,
`words` String,
INDEX idx_word words TYPE inverted(2) GRANULARITY 2,
)ENGINE = ReplacingMergeTree(xxx) 
@Algunenano  this my schema

**Comment by Algunenano** [comment]
I'm guessing it's `ORDER BY id` right?

In this case the problem is that `FINAL` must be applied before the index, as otherwise you might skip a newer result in the index but keep the old one. This means that the table changes, making the index useless.

**Comment by myBigbug** [comment]
@Algunenano  yes，ORDER BY id  right.
clickhouse Can this situation be optimized?  for example first filter data then merge data

**Comment by Algunenano** [comment]
No, you can't filter before merging as that will lead to incorrect results.

**Comment by myBigbug** [comment]
thank you @Algunenano
