### ISSUE TITLE
Support "SET GLOBAL" to configure settings

### ISSUE THREAD

**Issue by baolinhuang** [ClickHouse/ClickHouse#62915]
> (you don't have to strictly follow this form)

In the community version of ClickHouse.  If you want to persist parameters, you can only manually write them into the XML configuration file, and then choose whether to restart based on the situation. 

This kind of modification of the configuration file can only be done by the administrator of clickhouse (like DBA).
Users have no way to configure and persist global parameters.

In order to simplify the process and allow the ClickHouse kernel to also provide operations on persistent parameters, we suggest to adds the `SET GLOBAL` syntax.

On the one hand, the parameters are applied to all new connections; on the other hand, the parameters are persisted to the user configuration file. xml, similar to the combination of MySQL's SET GLOBAL and SET PERSIST.

**Comment by alexey-milovidov** [comment]
`ALTER USER default SETTINGS ...`

**Comment by baolinhuang** [comment]
Thanks for the reply.

I have tested `ALTER USER default SETTINGS`,  it seems work for us.

1. It can be persisted across instance restart.
2. It can be combined with on default cluster to take effect on all nodes.
