### ISSUE TITLE
[RFC] Disk tracking hardlinks for Zero-copy (VFSDisk)

### ISSUE THREAD

**Issue by aalexfvk** [ClickHouse/ClickHouse#62936]
## Motivation
1. Implement more reliable hardlink tracking on disk level for zero-copy replication.
2. Refactor out engine-level zero-copy code to get rid of trying to track hardlinks.
3. Orphaned objects in the object storage are acceptable as a result of various crashes or abnormal situations.
But there should be no premature deletions. Minimize possibility to get unexpected `DB::Exception: The specified key does not exist` error.
5. FREEZE PARTITION should be supported

## Bird's-eye view
![main](https://gist.githubusercontent.com/aalexfvk/e2c038dd09430756a8a4520f31f482c8/raw/38a329ff4c19fd0de58fe950349d90b88e934971/WAL.png)

|Step|Description|
|--|--|
|1|Write a BLOB to the object storage|Orphaned objects
|2|Write a link record to the WAL.<br>Can be different FSYNC policies: no sync, timed sync, sync on every record<br>Checksum for every record.<br>Every record has an increasing pointer(index)|
|3|Write local metadata file|
|4-5|Log writer(thread on replica) takes a batch of WAL records and push it to the ZooKeeper queue.<br>Remove it from WAL after that.<br>Retry of sending are acceptable
|6| Garbage collector(thread on replica) reads a batch of records from the ZK queue.
|7| Merge the batch of records with the snapshot file (snapshot is sorted) with creating of a new snapshot file.<br>Update active snapshot in the special node in ZK in **one transaction*** with **checking of its version** (optimistic locking) and **removing** processed batch from ZK queue.
|*|Seemingly, deletion log records in the transaction is too strong guarantee here. Because handling of log is idempotent due to each record has an index. Pushing records to ZK itself can be optional, we may handle local WAL and update snapshot directly. Updating of active snapshot name in ZK node with checking of version is still necessary. Ephemeral ZK lock can also be helpful to reduce possibility of clashing between replicas, but do not rely on it.
|8| Write snapshot to S3(actually done on step 7) and remove all objects unlinked by all replicas, on which it was previously linked.

## Files replication between replicas
![replication](https://gist.githubusercontent.com/aalexfvk/e2c038dd09430756a8a4520f31f482c8/raw/fec743b667efe4c540f825132d1d823f40f13078/Replication.png)
|Step|Description|
|--|--|
|1|Request to write file to disk|
|2|Write link record to the WAL|
|3|GET_PART replication command.<br>Announce new part(files) through external channel (in terms of WAL)|
|4|Fetch file(for part)<br>Send current Replica2 WAL pointer within this request.
|5|Write link record to the WAL of Replica1 for Replica2<br>In order to prevent premature deletion file by Replica1.
|6|Send file from Replica1 to Replica2<br>Send current Replica1 WAL pointer within this response.
|7|Request to insert fetched metadata|
|8|Write links records to the WAL of Replica2 for Replica1 and itself<br>In order to prevent premature deletion file by Replica2.

## Example of snapshot record
Snapshot in object storage contains an array of records sorted by `remote_path`:
```
{
  "remote_path": s3://...,
  "replicas": {
    "vla-oo2p1jk7qrvpbcq8.db.yandex.net": {
      "files": [{
        "local_path": "/path/to/file",
        "status": "linked",
        "source": "vla-oo2p1jk7qrvpbcq8.db.yandex.net",  # This record was updated from WAL from this replica
        "last_update_timestamp": "Mon, 08 Apr 2024 16:03:43 GMT",
        "last_update_wal_pointer": <64bit number>  # Records with less wal_pointer must be ignored for triplet (remote_path, local_path, replica)
        "wal_uuid": <uuid>  # To track recreating of WAL (TODO: investigate this case)
        },
        # ...
      ]
    },
    "vla-sdf54sd5f4s5dsf.db.yandex.net": {
      "files": [{
        "local_path": "/path/to/file",
        # Means that file was removed from this replica. We keep remove records until file is deleted from all replicas, to handle case when 
        # link record for this replica from other one is coming, but this file(link) was already deleted by the replica.
        # Actually, we don't have to do that, we can remove possible "dangling" on-behalf-on(with other source) records by TTL or introduce other policy (TODO: investigate this case).
        "status": "unlinked", 
        "source": "vla-sdf54sd5f4s5dsf.db.yandex.net",
        "last_update_timestamp": "Mon, 08 Apr 2024 16:03:43 GMT",
        "last_update_wal_pointer": <64bit number>
        "wal_uuid": <uuid>
        },
        # ...
      ]
    },
  },
}
```

**Comment by gregakinman** [comment]
This is marked as done, but are there links to PRs or is it detailed what versions contain this improvement? It looks like https://github.com/ClickHouse/ClickHouse/pull/65704 was closed?
