### ISSUE TITLE
Building on Ubuntu instructions missing `rustc` and `cargo` prerequisite and installing the latest clang version is not safe.

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#62934]
**Describe the issue**
https://clickhouse.com/docs/en/development/build#building-on-ubuntu missing `rustc` and `cargo` prerequisite.

```
sudo apt-get update
sudo apt-get install git cmake ccache python3 ninja-build nasm yasm gawk lsb-release wget software-properties-common gnupg
```

should include `rustc` and `cargo` package installation. For example,

```
sudo apt-get update
sudo apt-get install git cmake ccache python3 ninja-build nasm yasm gawk lsb-release wget software-properties-common gnupg rustc cargo
```

Otherwise, you'll get a warning when trying to build ClickHouse:

```
-- Adding contrib module corrosion (configuring with corrosion-cmake)
CMake Warning at contrib/corrosion/cmake/FindRust.cmake:25 (message):
  `rustc` not found in PATH or `/home/user/.cargo/bin`.

  Hint: Check if `rustc` is in PATH or manually specify the location by
  setting `Rust_COMPILER` to the path to `rustc`.
Call Stack (most recent call first):
  contrib/corrosion/cmake/FindRust.cmake:240 (_findrust_failed)
  contrib/corrosion-cmake/CMakeLists.txt:5 (find_package)
```

**Comment by vzakaznikov** [comment]
Another issue is that

```
sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
```

will install the latest clang version. Right now it is `clang-18` which is not supported by the source code.
It needs `clang-17`.

**Comment by vzakaznikov** [comment]
Better to include isntructions how to specify the exact version of clang:

```
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 17
```

**Comment by Algunenano** [comment]
> https://clickhouse.com/docs/en/development/build#building-on-ubuntu missing rustc and cargo prerequisite.

It’s literally in the same page and under the Ubuntu header: https://clickhouse.com/docs/en/development/build#install-rust-compiler

> Right now it is clang-18 which is not supported by the source code.

It is supported but no in CI (yet)

> Better to include instructions on how to specify the exact version of clang:

Could you please send a PR with the suggested changes? Thanks

**Comment by Algunenano** [comment]
> However, rustup is not available by default on Ubuntu so it needs to be installed before those instructions can be followed. I thought that you might as well install the rustc and cargo packages provided by the Ubuntu distribution.

You are not reading the documentation. It says: `First follow the steps in the official [rust documentation](https://www.rust-lang.org/tools/install) to install rustup.`

This is because the recommended way of installing Rust is not through apt so it's better to refer to their docs rather than suggesting downloading a url that might change in the future. In fact, if you install rustc from apt you will get whatever random version your Ubuntu has in the repos, which is highly likely to not be able to build CH at all.

> The clang version is not only about CI not supporting it. Right now, you litterally can't build ClickHouse with clang-18 until the PR that fixes issues when using it is merged. I will be happy to create a PR.

It is already fixed.

**Comment by vzakaznikov** [comment]
Thanks. Makes sense.
