### ISSUE TITLE
If I run clickhouse-local a couple million times, the filesystem exhausts inodes in `/tmp`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#62941]
Because it creates a unique directory every time.

**Comment by alexey-milovidov** [comment]
Which is nice, but we should do something else.

**Comment by Algunenano** [comment]
We should probably delete the temp folder at exit, specially if it's just empty folders (or maybe always):

```
$ tree /tmp/clickhouse-local-309950-1714054654-428021066442219455
/tmp/clickhouse-local-309950-1714054654-428021066442219455
├── data
├── metadata
├── metadata_dropped
├── tmp
├── user_defined
└── user_scripts

7 directories, 0 files

```

**Comment by alexey-milovidov** [comment]
Indeed, the code was written to delete these files, but it was written incorrectly.

**Comment by jaumecastell** [comment]
Hi @alexey-milovidov , I'm facing some issues related to this issue when upgrading to 24.3 clickhouse version. When it's expected for this fix to be released? Thanks in advance.

**Comment by Algunenano** [comment]
> When it's expected for this fix to be released?

Once it's ready. You can follow https://github.com/ClickHouse/ClickHouse/pull/63074
