### ISSUE TITLE
Thread safety concern with static initialization of `REGISTER_FUNCTION`

### ISSUE THREAD

**Issue by PuPuHX** [ClickHouse/ClickHouse#62948]
I am currently exploring the use of the REGISTER_FUNCTION macro.  I have a concern about the thread safety of static initialization when registering functions using this macro.

The macro REGISTER_FUNCTION triggers the dynamic initialization of a non-local static variable (static ::DB::FunctionRegister register_name(#fn, func_name);). This static variable, in turn, registers a function pointer by invoking FunctionRegisterMap::instance().emplace(std::move(name), func_ptr);.

My concern arises with the thread safety of such initialization. Specifically, I am questioning whether the initialization of these static instances and their registration in the FunctionRegisterMap::instance() is thread-safe.

**Comment by PuPuHX** [comment]
Given these discussions: [Q1](https://stackoverflow.com/questions/29775826/does-the-c-standard-require-that-dynamic-initialization-of-static-variables-be) and [Q2](https://stackoverflow.com/questions/18542804/global-static-initialization-threading/18543786#18543786), it appears there is no explicit guarantee that the initialization process is thread-safe.

**Comment by canhld94** [comment]
cc @liyinsg

**Comment by liyinsg** [comment]
The initialization happens before main() is called. Only concern for such operation is order of different static variables are not guaranteed by the C++ standard.

**Comment by Algunenano** [comment]
I'm not sure if it's guaranteed by the standard that global static variables will be initialized before main, but it seems to be the case for clang and the supported architectures.

The order of initialization doesn't seem to be important in this case.

Let's revisit if we have tangible proof of it being an issue
