### ISSUE TITLE
what is mean for executeQuery: Code: 33. DB::Exception: Unexpected EOF,

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/ClickHouse#62952]
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/7dbac792-11ef-435a-afcf-95bda59f19f2)

<Error> executeQuery: Code: 33. DB::Exception: Unexpected EOF, got 4294967294 of 6342563658 bytes: While executing ArrowBlockInputFormat. (CANNOT_READ_ALL_DATA) (version 24.4.1.173 (official build)) (from 10.10.0.4:58901) (in query: INSERT INTO stock_base.zb_mm (`code`, `date`, `date_time`, `exg`, `time_int`, `price`, `volume`, `side`, `type`, `trade_flag`, `chno`, `bidno`, `askno`, `ordno`, `seqno`) FORMAT Arrow ), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c8acb9b
1. DB::Exception::Exception<unsigned long&, unsigned long const&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long const&>::type>, unsigned long&, unsigned long const&) @ 0x00000000081d8a98
2. DB::LimitReadBuffer::nextImpl() @ 0x000000000ca8f946
3. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
4. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
5. DB::ConcatReadBuffer::nextImpl() @ 0x000000001014ec06
6. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
7. DB::ConcatReadBuffer::nextImpl() @ 0x000000001014ec06
8. DB::(anonymous namespace)::copyDataImpl(DB::ReadBuffer&, DB::WriteBuffer&, bool, unsigned long, std::atomic<int> const*, std::shared_ptr<DB::Throttler>) (.llvm.11379089755201849936) @ 0x000000000c930d06
9. DB::asArrowFileLoadIntoMemory(DB::ReadBuffer&, std::atomic<int>&, String const&, String const&) @ 0x0000000012414967
10. DB::createFileReader(DB::ReadBuffer&, DB::FormatSettings const&, std::atomic<int>&) @ 0x00000000123f6b57
11. DB::ArrowBlockInputFormat::prepareReader() @ 0x00000000123f5bca
12. DB::ArrowBlockInputFormat::read() @ 0x00000000123f5339
13. DB::IInputFormat::generate() @ 0x00000000123ec636
14. DB::ISource::tryGenerate() @ 0x00000000123c8015
15. DB::ISource::work() @ 0x00000000123c7aa2
16. DB::ExecutionThreadContext::executeTask() @ 0x00000000123e2cda
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000123d7230
18. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000123d66a1
19. DB::CompletedPipelineExecutor::execute() @ 0x00000000123d4e32
20. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001127fcfb
21. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012305a55
22. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001230a514
23. DB::HTTPServerConnection::run() @ 0x0000000012389aba
24. Poco::Net::TCPServerConnection::start() @ 0x0000000014caedb2
25. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014cafbf9
26. Poco::PooledThread::run() @ 0x0000000014da8361
27. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014da68fd
28. ? @ 0x00007f405cea6ac3
29. ? @ 0x00007f405cf38850

2024.04.25 15:37:42.130519 [ 131951 ] {a9c77135-8900-435e-bb73-e9aab677f1bf} <Error> DynamicQueryHandler: Code: 33. DB::Exception: Unexpected EOF, got 4294967294 of 6342563658 bytes: While executing ArrowBlockInputFormat. (CANNOT_READ_ALL_DATA), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c8acb9b
1. DB::Exception::Exception<unsigned long&, unsigned long const&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long const&>::type>, unsigned long&, unsigned long const&) @ 0x00000000081d8a98
2. DB::LimitReadBuffer::nextImpl() @ 0x000000000ca8f946
3. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
4. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
5. DB::ConcatReadBuffer::nextImpl() @ 0x000000001014ec06
6. DB::(anonymous namespace)::ReadBufferWrapper<std::nullptr_t>::nextImpl() (.3a27af6be19a0553989b6b5ce4ae753b) @ 0x000000000fa5becc
7. DB::ConcatReadBuffer::nextImpl() @ 0x000000001014ec06
8. DB::(anonymous namespace)::copyDataImpl(DB::ReadBuffer&, DB::WriteBuffer&, bool, unsigned long, std::atomic<int> const*, std::shared_ptr<DB::Throttler>) (.llvm.11379089755201849936) @ 0x000000000c930d06
9. DB::asArrowFileLoadIntoMemory(DB::ReadBuffer&, std::atomic<int>&, String const&, String const&) @ 0x0000000012414967
10. DB::createFileReader(DB::ReadBuffer&, DB::FormatSettings const&, std::atomic<int>&) @ 0x00000000123f6b57
11. DB::ArrowBlockInputFormat::prepareReader() @ 0x00000000123f5bca
12. DB::ArrowBlockInputFormat::read() @ 0x00000000123f5339
13. DB::IInputFormat::generate() @ 0x00000000123ec636
14. DB::ISource::tryGenerate() @ 0x00000000123c8015
15. DB::ISource::work() @ 0x00000000123c7aa2
16. DB::ExecutionThreadContext::executeTask() @ 0x00000000123e2cda
17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000123d7230
18. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000123d66a1
19. DB::CompletedPipelineExecutor::execute() @ 0x00000000123d4e32
20. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001127fcfb
21. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012305a55
22. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x000000001230a514
23. DB::HTTPServerConnection::run() @ 0x0000000012389aba
24. Poco::Net::TCPServerConnection::start() @ 0x0000000014caedb2
25. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014cafbf9
26. Poco::PooledThread::run() @ 0x0000000014da8361
27. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014da68fd
28. ? @ 0x00007f405cea6ac3
29. ? @ 0x00007f405cf38850
 (version 24.4.1.173 (official build))

how can i fix it

**Comment by a819721810** [comment]
i use insert in cluster , insert into  distributed table

**Comment by kssenii** [comment]
Please check if the data can be read at all? May be table structure is not consistent with what you are inserting
