### ISSUE TITLE
Clickhouse keeper is yielding leadership when clients are timing out

### ISSUE THREAD

**Issue by tmada** [ClickHouse/ClickHouse#62986]
**Describe the unexpected behaviour**
Happening almost daily, it appears that couple of nodes in our cluster are taking a long time in responding to our current CH leader which is leading to the CH Keeper Leader yielding its leadership and ultimately blocking writes because of read-only mode. It appears the keeper is functioning properly.  

**How to reproduce**
Unclear at the moment, seems to be load causing the zookeeper forced reelection. 

Setup:
4 virtual nodes, 8G RAM, 4 Cores
2 shards w/ 2 replicas; node 1 + node 3, node 2 + node 4
4 nodes participating in the zookeeper setup (correct me if I'm wrong, there is no split brain with RAFT) 
```
      <operation_timeout_ms>1000000</operation_timeout_ms>
      <session_timeout_ms>3000000</session_timeout_ms>
```
Note it really always seems to be node 1 and 3 "taking too long".

* Which ClickHouse server version to use
22.2.2.1-2

* Queries to run that lead to unexpected result
Appears to be triggered around some INSERTS
![image](https://github.com/ClickHouse/ClickHouse/assets/8443811/8a7fe44b-b49d-4439-b5e9-73a5037c49bd)

**Expected behavior**
A leader doesn't yield its ownership when others nodes are slow to respond?

**Error message and/or stacktrace**
```
2024.04.16 23:10:38.917566 [ 14531 ] {} <Warning> RaftInstance: skipped sending msg to 3 too long time, last msg sent 7171 ms ago
2024.04.16 23:10:39.416906 [ 14531 ] {} <Warning> RaftInstance: skipped sending msg to 1 too long time, last msg sent 7670 ms ago
2024.04.16 23:10:39.417673 [ 14531 ] {} <Warning> RaftInstance: skipped sending msg to 3 too long time, last msg sent 7671 ms ago
2024.04.16 23:10:39.916992 [ 14531 ] {} <Warning> RaftInstance: skipped sending msg to 1 too long time, last msg sent 8170 ms ago
2024.04.16 23:10:39.917780 [ 14531 ] {} <Warning> RaftInstance: skipped sending msg to 3 too long time, last msg sent 8171 ms ago
2024.04.16 23:10:40.401990 [ 14533 ] {} <Warning> RaftInstance: skipped sending msg to 3 too long time, last msg sent 8655 ms ago
2024.04.16 23:10:40.402069 [ 14533 ] {} <Warning> RaftInstance: skipped sending msg to 1 too long time, last msg sent 8655 ms ago
2024.04.16 23:10:40.417057 [ 14531 ] {} <Warning> RaftInstance: long pause warning to 1 is too verbose, will suppress it from now
2024.04.16 23:10:40.417861 [ 14531 ] {} <Warning> RaftInstance: long pause warning to 3 is too verbose, will suppress it from now
2024.04.16 23:10:41.417177 [ 14531 ] {} <Error> RaftInstance: 2 nodes (out of 4, 4 including learners) are not responding longer than 10000 ms, at least 140071768424451 nodes (including leader) should be alive to proceed commit
2024.04.16 23:10:41.417203 [ 14531 ] {} <Error> RaftInstance: will yield the leadership of this node
```

**Additional context**
None

**Comment by tmada** [comment]
Or am I comprehending the order of operations wrong. 
Here is another log event:
```
2024.04.25 08:11:44.427431 [ 1292 ] {} <Warning> RaftInstance: long pause warning to 1 is too verbose, will suppress it from now
2024.04.25 08:11:44.427504 [ 1293 ] {} <Warning> RaftInstance: long pause warning to 3 is too verbose, will suppress it from now
2024.04.25 08:11:44.927513 [ 1290 ] {} <Error> RaftInstance: 2 nodes (out of 4, 4 including learners) are not responding longer than 10000 ms, at least 140647294042115 nodes (including leader) should be alive to pr
oceed commit
2024.04.25 08:11:44.927564 [ 1290 ] {} <Error> RaftInstance: will yield the leadership of this node
2024.04.25 08:11:44.927570 [ 1290 ] {} <Information> RaftInstance: got immediate re-elect request, resign now
2024.04.25 08:11:44.927577 [ 1290 ] {} <Warning> RaftInstance: cancelled non-blocking client request 55747371
2024.04.25 08:11:44.927646 [ 1290 ] {} <Warning> RaftInstance: cancelled non-blocking client request 55747372
2024.04.25 08:11:44.927678 [ 1290 ] {} <Warning> RaftInstance: cancelled non-blocking client request 55747373
2024.04.25 08:11:44.927730 [ 1287 ] {} <Information> RaftInstance: return null as leader does not exist in the current group
2024.04.25 08:11:44.927731 [ 1292 ] {} <Error> RaftInstance: 2 nodes (out of 4, 4 including learners) are not responding longer than 10000 ms, at least 140647294042115 nodes (including leader) should be alive to pr
oceed commit
2024.04.25 08:11:44.927757 [ 1292 ] {} <Error> RaftInstance: will yield the leadership of this node
2024.04.25 08:11:44.927854 [ 1293 ] {} <Error> RaftInstance: 2 nodes (out of 4, 4 including learners) are not responding longer than 10000 ms, at least 140647294042115 nodes (including leader) should be alive to pr
oceed commit
2024.04.25 08:11:44.927863 [ 1293 ] {} <Error> RaftInstance: will yield the leadership of this node
2024.04.25 08:11:44.927972 [ 1360 ] {} <Error> ZooKeeperClient: Code: 999. Coordination::Exception: Received error in heartbeat response: Connection loss (Run time inconsistency). (KEEPER_EXCEPTION), Stack trace (w
hen copying this message, always include the lines below):
```
Maybe I'm just observing the logging in too literal of a sequence? i.e. the leader actually receives a re-election request from a follower.

If that is the case I might look into increasing some of the timeouts as this is a staging env and revert back. 
```
operation_timeout_ms — Timeout for a single client operation (ms) (default: 10000).
min_session_timeout_ms — Min timeout for client session (ms) (default: 10000).
session_timeout_ms — Max timeout for client session (ms) (default: 100000).
dead_session_check_period_ms — How often ClickHouse Keeper checks for dead sessions and removes them (ms) (default: 500).
heart_beat_interval_ms — How often a ClickHouse Keeper leader will send heartbeats to followers (ms) (default: 500).
election_timeout_lower_bound_ms — If the follower does not receive a heartbeat from the leader in this interval, then it can initiate leader election (default: 1000). Must be less than or equal to election_timeout_upper_bound_ms. Ideally they shouldn't be equal.
election_timeout_upper_bound_ms — If the follower does not receive a heartbeat from the leader in this interval, then it must initiate leader election (default: 2000).
```

**Comment by SaltTan** [comment]
It seems that you run Keeper on the same servers with ClickHouse. You should not do this.

https://clickhouse.com/docs/en/operations/tips#zookeeper
> You can run ClickHouse Keeper on the same server as ClickHouse in test environments, or in environments with low ingestion rate. For production environments we suggest to use separate servers for ClickHouse and ZooKeeper/Keeper, or place ClickHouse files and Keeper files on to separate disks. Because ZooKeeper/Keeper are very sensitive for disk latency and ClickHouse may utilize all available system resources.

> Which ClickHouse server version to use
22.2.2.1-2

 Also, you should upgrade

**Comment by tmada** [comment]
> It seems that you run Keeper on the same servers with ClickHouse. You should not do this.
> 
> https://clickhouse.com/docs/en/operations/tips#zookeeper
> 
> > You can run ClickHouse Keeper on the same server as ClickHouse in test environments, or in environments with low ingestion rate. For production environments we suggest to use separate servers for ClickHouse and ZooKeeper/Keeper, or place ClickHouse files and Keeper files on to separate disks. Because ZooKeeper/Keeper are very sensitive for disk latency and ClickHouse may utilize all available system resources.
> 
> > Which ClickHouse server version to use
> > 22.2.2.1-2
> 
> Also, you should upgrade

Forgot to state this is a test environment.
