### ISSUE TITLE
Unable to Configure CLI with YAML Files

### ISSUE THREAD

**Issue by xyu** [ClickHouse/ClickHouse#62988]
Howdy!

The [current CLI docs](https://clickhouse.com/docs/en/interfaces/cli#configuration_files) indicates that it should be possible to configure `clickhouse-client` with YAML as well as XML:

> Or the same config in a YAML format:
> ```
> user: username
> password: 'password'
> secure: true
> openSSL:
>   client:
>     caConfig: '/etc/ssl/cert.pem'
> ```

However this does not seem to work because the YAML parser transforms the config into XML before merging and it always appends a `clickhouse` root element:

https://github.com/ClickHouse/ClickHouse/blob/0038f322e813050f8306762c42be200aaf7c9aed/src/Common/Config/YAMLParser.cpp#L164-L166

Which does not match the requisite `config` root element that the CLI configs normally use resulting in errors like:
> Merging bypassed - configuration file '/etc/clickhouse-client/config.d/xyu.yaml' doesn't belong to configuration '/etc/clickhouse-client/config.xml' - merging root node name 'clickhouse' doesn't match 'config'

When starting up the CLI with trace logging (`clickhouse-client --log-level trace`).

**Comment by nikitamikhaylov** [comment]
This is working now: 

```
~/test                                                                                                                                                                                took 12s at 01:15:05
❯ cat clickhouse-client.yaml
user: non-existent
password: 'password'
secure: true
~/test                                                                                                                                                                                         at 01:15:09
❯ clickhouse-client --log-level test
Processing configuration file './clickhouse-client.yaml'.
ClickHouse client version 24.10.1.1562 (official build).
Connecting to localhost:9440 as user non-existent.
Connecting. Database: (not specified). User: non-existent. Secure. Uncompressed
Code: 210. DB::NetException: Connection refused (localhost:9440). (NETWORK_ERROR)

Uninitializing subsystem: Logging Subsystem
Shutting down named sessions
Shutting down database catalog
Shutting down system databases
Shutting down DDLWorker
Shutting down caches
Shutting down AccessControl
```
