### ISSUE TITLE
How to query data with incremental update?

### ISSUE THREAD

**Issue by Jack012a** [ClickHouse/ClickHouse#6300]
Assume that I insert row data into ClickHouseDB with an increasing timestamp.

Question> Does ClickHouseDB offer a function so I can query the newly inserted rows?

Use case:

1> DB has 10 rows of data
2> Client connects to DB, query the DB and get all 10 rows of data
3> insert 5 more rows to DB
4> Client was notified or Client makes another query, the DB ONLY returns the 5 newly inserted data.

Thank you

**Comment by blinkov** [comment]
@q0987, do you have any further questions?

**Comment by blinkov** [comment]
Feel free to re-open the issue if it is still relevant.

**Comment by DrissiReda** [comment]
Any updates on this?

**Comment by melvynator** [comment]
Hello. I would say the closest that we have from what you are describing is probably: https://clickhouse.com/docs/en/sql-reference/statements/create/view#live-view-experimental 

But what you are describing should be easily done on the client side.
