### ISSUE TITLE
Memory grows slowly ClickHouse client version 19.15.7.30

### ISSUE THREAD

**Issue by cheungfeifu** [ClickHouse/ClickHouse#63017]
The memory of my clickhouse database slowly increased. After restarting clickhouse, the memory increased after a period of time.
![image](https://github.com/ClickHouse/ClickHouse/assets/40728359/6e1a832f-e903-4485-8d3b-a74a5e1c3bfe)
![image](https://github.com/ClickHouse/ClickHouse/assets/40728359/f21cb0d1-7d8a-4dbb-82b9-8700eb88def5)
![image](https://github.com/ClickHouse/ClickHouse/assets/40728359/3c49b25e-b240-4fd1-bb2d-a9ff8b1b6d7e)

**Comment by Algunenano** [comment]
This versions is unsupported. Please upgrade to a supported release
