### ISSUE TITLE
ReplacingMergeTree does not collapse duplicates，even if I manually optimize it

### ISSUE THREAD

**Issue by traceless** [ClickHouse/ClickHouse#63010]
**Describe the unexpected behaviour**

As stated in the title, there are several pieces of data in my database that cannot be collapse duplicates，even if I manually execute optimize command:
```
OPTIMIZE TABLE dc_amazon_orders FINAL CLEANUP

```

1、after optimize table ..., it still has duplicate data:

![WX20240426-110339@2x](https://github.com/ClickHouse/ClickHouse/assets/4156885/36479ec0-95e9-400b-a6c5-a5b3b0a27465)

2、table  structure

<img width="961" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/f8f3ed0c-defc-4bfe-9455-9f57f90feaf2">

order by id, seller_id, marketplace_id，but all three values are the same. so why not collapse duplicates the 2 row ? It's been three days already.

**Several ways I have tried, but it still not work as expected behaviour**
 - Try to restart clickhouse, and optimize table again.
 - I tried to disconnect all connections to it, and optimize table again.
 

Setup:
configuration information: 1 shards w/ 1 replicas; 

**How to reproduce**
* Which ClickHouse server version to use
  23.8.10.43 
 

**Expected behavior**
I hope it can collapse duplicates

**Error message and/or stacktrace**
None

**Additional context**
None

**Comment by den-crane** [comment]
Merges happen only within partition. `toYYYYMM(created_date`) - if your rows are in different months then merges never happen for them.

**Comment by traceless** [comment]
> Merges happen only within partition. `toYYYYMM(created_date)` - if your rows are in different months then they never be collapsed.
> 
> https://fiddle.clickhouse.com/65cff341-5773-487a-9b3c-ac72ecc49dee
> 
> ```sql
> CREATE TABLE users (uid Int16, create_date DateTime, s String)
> ENGINE=ReplacingMergeTree
> Partition by toYYYYMM(create_date)
> order by uid;
> 
> INSERT INTO users VALUES (1231, '2020-01-01', 's1');
> INSERT INTO users VALUES (1231, '2022-01-01', 's2');
> 
> SELECT * FROM users final format PrettyCompactMonoBlock; 
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2022-01-01 00:00:00 | s2 | -- SELECT FINAL merges rows across partitions
>    +------+---------------------+----+ 
> 
> optimize table users final;
> 
> SELECT * FROM users format PrettyCompactMonoBlock;
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2020-01-01 00:00:00 | s1 | -- optimize FINAL does not merge rows across partitions
> 2. | 1231 | 2022-01-01 00:00:00 | s2 | -- optimize FINAL does not merge rows across partitions
>    +------+---------------------+----+
> ```

 I have verified your statement and you are right, thinks!

**Comment by traceless** [comment]
> > Merges happen only within partition. `toYYYYMM(created_date)` - if your rows are in different months then they never be collapsed.
> > https://fiddle.clickhouse.com/65cff341-5773-487a-9b3c-ac72ecc49dee
> > ```sql
> > CREATE TABLE users (uid Int16, create_date DateTime, s String)
> > ENGINE=ReplacingMergeTree
> > Partition by toYYYYMM(create_date)
> > order by uid;
> > 
> > INSERT INTO users VALUES (1231, '2020-01-01', 's1');
> > INSERT INTO users VALUES (1231, '2022-01-01', 's2');
> > 
> > SELECT * FROM users final format PrettyCompactMonoBlock; 
> > 
> >    +--uid-+---------create_date-+-s--+
> > 1. | 1231 | 2022-01-01 00:00:00 | s2 | -- SELECT FINAL merges rows across partitions
> >    +------+---------------------+----+ 
> > 
> > optimize table users final;
> > 
> > SELECT * FROM users format PrettyCompactMonoBlock;
> > 
> >    +--uid-+---------create_date-+-s--+
> > 1. | 1231 | 2020-01-01 00:00:00 | s1 | -- optimize FINAL does not merge rows across partitions
> > 2. | 1231 | 2022-01-01 00:00:00 | s2 | -- optimize FINAL does not merge rows across partitions
> >    +------+---------------------+----+
> > ```
> 
> I have verified your statement and you are right, thinks!

i‘m sorry ，I didn't carefully check your year (create_date) , here my order data:

<img width="782" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/6443a669-7eaa-4c8b-9aaa-b8e5c1ca7679">

<img width="783" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/280f2fc5-05d7-4b83-8e80-45134735df87">

﻿
The year, month, and day of created_time are all the same, but they are still not merged.

**Comment by traceless** [comment]
> Merges happen only within partition. `toYYYYMM(created_date)` - if your rows are in different months then they never be collapsed.
> 
> https://fiddle.clickhouse.com/65cff341-5773-487a-9b3c-ac72ecc49dee
> 
> ```sql
> CREATE TABLE users (uid Int16, create_date DateTime, s String)
> ENGINE=ReplacingMergeTree
> Partition by toYYYYMM(create_date)
> order by uid;
> 
> INSERT INTO users VALUES (1231, '2020-01-01', 's1');
> INSERT INTO users VALUES (1231, '2022-01-01', 's2');
> 
> SELECT * FROM users final format PrettyCompactMonoBlock; 
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2022-01-01 00:00:00 | s2 | -- SELECT FINAL merges rows across partitions
>    +------+---------------------+----+ 
> 
> optimize table users final;
> 
> SELECT * FROM users format PrettyCompactMonoBlock;
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2020-01-01 00:00:00 | s1 | -- optimize FINAL does not merge rows across partitions
> 2. | 1231 | 2022-01-01 00:00:00 | s2 | -- optimize FINAL does not merge rows across partitions
>    +------+---------------------+----+
> ```

i'm sorry, I didn't take a closer look at your year (create_date), here is my order data:
 
<img width="829" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/dd8a0d73-35b9-49d7-a46f-ea4427545dd4">

<img width="795" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/692b859c-a3b0-45a5-851e-4d92faf78fa4">

<img width="826" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/5bc0d77d-3385-4570-a6cf-496fab4efdc6">

<h4> My doubt </h4>
The year, month, and day of creation are all the same, event the time, minute, and second are the same, but they are still not merged.

**Comment by traceless** [comment]
> Merges happen only within partition. `toYYYYMM(created_date)` - if your rows are in different months then they never be collapsed.
> 
> https://fiddle.clickhouse.com/65cff341-5773-487a-9b3c-ac72ecc49dee
> 
> ```sql
> CREATE TABLE users (uid Int16, create_date DateTime, s String)
> ENGINE=ReplacingMergeTree
> Partition by toYYYYMM(create_date)
> order by uid;
> 
> INSERT INTO users VALUES (1231, '2020-01-01', 's1');
> INSERT INTO users VALUES (1231, '2022-01-01', 's2');
> 
> SELECT * FROM users final format PrettyCompactMonoBlock; 
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2022-01-01 00:00:00 | s2 | -- SELECT FINAL merges rows across partitions
>    +------+---------------------+----+ 
> 
> optimize table users final;
> 
> SELECT * FROM users format PrettyCompactMonoBlock;
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2020-01-01 00:00:00 | s1 | -- optimize FINAL does not merge rows across partitions
> 2. | 1231 | 2022-01-01 00:00:00 | s2 | -- optimize FINAL does not merge rows across partitions
>    +------+---------------------+----+
> ```

i’m sorry, I didn't take a closer look at your year (create_date) , here is my order data:

<img width="803" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/db5eaf72-1673-4fde-a1a4-b62adca49849">

<img width="801" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/7dc2432f-ee07-417a-9f07-234e67da548a">

<img width="796" alt="图片" src="https://github.com/ClickHouse/ClickHouse/assets/4156885/e7de887e-f236-40dd-b20f-8ce8b9c6aad5">
 
<h4>My doubt</h4>
The year, month, and day of creation are all the same, event the time, minute, and second are the same, but they are still not merged.

**Comment by traceless** [comment]
> Merges happen only within partition. `toYYYYMM(created_date)` - if your rows are in different months then they never be collapsed.
> 
> https://fiddle.clickhouse.com/65cff341-5773-487a-9b3c-ac72ecc49dee
> 
> ```sql
> CREATE TABLE users (uid Int16, create_date DateTime, s String)
> ENGINE=ReplacingMergeTree
> Partition by toYYYYMM(create_date)
> order by uid;
> 
> INSERT INTO users VALUES (1231, '2020-01-01', 's1');
> INSERT INTO users VALUES (1231, '2022-01-01', 's2');
> 
> SELECT * FROM users final format PrettyCompactMonoBlock; 
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2022-01-01 00:00:00 | s2 | -- SELECT FINAL merges rows across partitions
>    +------+---------------------+----+ 
> 
> optimize table users final;
> 
> SELECT * FROM users format PrettyCompactMonoBlock;
> 
>    +--uid-+---------create_date-+-s--+
> 1. | 1231 | 2020-01-01 00:00:00 | s1 | -- optimize FINAL does not merge rows across partitions
> 2. | 1231 | 2022-01-01 00:00:00 | s2 | -- optimize FINAL does not merge rows across partitions
>    +------+---------------------+----+
> ```

Hello ,i get the error log.

```
(version 23.8.10.43 (official build)) │ {'FileOpen':20,'Seek':2,'ReadBufferFromFileDescriptorRead':25,'ReadBufferFromFileDescriptorReadBytes':2443738,'WriteBufferFromFileDescriptorWrite':1,'WriteBufferFromFileDescriptorWriteBytes':1049,'ReadCompressedBytes':2443687,'CompressedReadBufferBlocks':89,'CompressedReadBufferBytes':9365655,'OpenedFileCacheMisses':6,'OpenedFileCacheMicroseconds':13,'IOBufferAllocs':66,'IOBufferAllocBytes':17263188,'CreatedReadBufferOrdinary':6,'DiskReadElapsedMicroseconds':575,'DiskWriteElapsedMicroseconds':31,'ExternalProcessingFilesTotal':1,'WaitMarksLoadMicroseconds':1,'Merge':33,'MergedRows':228091,'MergedUncompressedBytes':13015111,'MergesTimeMilliseconds':80,'ContextLock':20,'RWLockAcquiredReadLocks':1,'PartsLockHoldMicroseconds':17,'CannotWriteToWriteBufferDiscard':9,'QueryProfilerRuns':1,'LogTrace':3,'LogDebug':4} │
│          │ MergeParts │ RegularMerge │ Vertical        │ 2024-03-24 │ 2024-03-24 11:23:22 │ 2024-03-24 11:23:22.958153 │         130 │ real_renpho_dc │ dc_amazon_orders │ 5039ee91-9a3d-4860-b8a6-0c94c40e906a │ 202403_0_737533_10509  │ 202403       │           │ Unknown   │           │                                                                                            │ 228033 │             0 │ ['202403_0_737475_10508','202403_737476_737533_11']                                                                                                     │           17909760 │    228091 │   13015111 │          22700598 │    49 │ Code: 49. DB::Exception: Number of rows in source parts (228091) excluding filtered rows (0) differs from number of bytes written to rows_sources file (228077). It is a bug. (LOGICAL_ERROR), Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./src/Common/Exception.cpp:98: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c621337 in /usr/lib/debug/usr/bin/clickhouse.debug
1. ./build_docker/./contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception<unsigned long&, unsigned long&, unsigned long&>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long&>::type>, unsigned long&, unsigned long&, unsigned long&) @ 0x000000000f392454 in /usr/lib/debug/usr/bin/clickhouse.debug
2. ./build_docker/./src/Storages/MergeTree/MergeTask.cpp:502: DB::MergeTask::VerticalMergeStage::prepareVerticalMergeForAllColumns() const @ 0x0000000012bb566f in /usr/lib/debug/usr/bin/clickhouse.debug
3. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716: bool std::__function::__policy_invoker<bool ()>::__call_impl<std::__function::__default_alloc_func<DB::MergeTask::VerticalMergeStage::subtasks::'lambda'(), bool ()>>(std::__function::__policy_storage const*) @ 0x0000000012bbe169 in /usr/lib/debug/usr/bin/clickhouse.debug
4. ./build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848: DB::MergeTask::VerticalMergeStage::execute() @ 0x0000000012bba34b in /usr/lib/debug/usr/bin/clickhouse.debug
5. ./build_docker/./src/Storages/MergeTree/MergeTask.cpp:0: DB::MergeTask::execute() @ 0x0000000012bb9d79 in /usr/lib/debug/usr/bin/clickhouse.debug
6. ./build_docker/./src/Storages/MergeTree/ReplicatedMergeMutateTaskBase.cpp:0: DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x0000000012e7692e in /usr/lib/debug/usr/bin/clickhouse.debug
7. ./build_docker/./src/Storages/MergeTree/MergeTreeBackgroundExecutor.cpp:273: DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x0000000012bcb679 in /usr/lib/debug/usr/bin/clickhouse.debug
8. ./build_docker/./base/base/../base/wide_integer_impl.h:809: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c6ffe9e in /usr/lib/debug/usr/bin/clickhouse.debug
9. ./build_docker/./src/Common/ThreadPool.cpp:0: void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c70395c in /usr/lib/debug/usr/bin/clickhouse.debug
10. ./build_docker/./base/base/../base/wide_integer_impl.h:809: void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c7021a4 in /usr/lib/debug/usr/bin/clickhouse.debug
11. start_thread @ 0x000000000000744b in /usr/lib64/libpthread-2.26.so
12. __clone @ 0x00000000000ef52f in /usr/lib64/libc-2.26.so

```

I can't figure out the reason for this exception.

**Comment by nickitat** [comment]
usage of `final cleanup` is [discouraged](https://clickhouse.com/docs/en/whats-new/changelog/cloud#reliability-changes). to remove duplicates simple `final` is enough.

**Comment by traceless** [comment]
> usage of `final cleanup` is [discouraged](https://clickhouse.com/docs/en/whats-new/changelog/cloud#reliability-changes). to remove duplicates simple `final` is enough.

emm，I have tried many times as you said, but it not collapse duplicates. Do you have any opinion on these exception logs.

**Comment by traceless** [comment]
> usage of `final cleanup` is [discouraged](https://clickhouse.com/docs/en/whats-new/changelog/cloud#reliability-changes). to remove duplicates simple `final` is enough.

But I have tried many times as you said, but it not collapse duplicates. Do you have any opinion on these exception logs.

**Comment by traceless** [comment]
I have transferred this issue here, this issue is a bug.

https://github.com/ClickHouse/ClickHouse/issues/63098
