### ISSUE TITLE
Add upsert for EmbeddedRocksDB via (Simple)AggregateFunction 

### ISSUE THREAD

**Issue by darkleaf** [ClickHouse/ClickHouse#63021]
I need to upsert some data into a KV table.
I suggest to implement it via (Simple)AggregateFunction types. 

```sql
CREATE TABLE test (
  uid Int16, 
  val SimpleAggregateFunction(sum, Double) 
) ENGINE=EmbeddedRocksDB() -- or AggregatingEmbeddedRocksDB()
PRIMARY KEY(uid);

insert into test values (1, 1); 
insert into test values (1, 2); 

select * from test;

-- now returns
1 2
-- will return
1 3
```

Also, it opens door for implementing replicated rocksdb engine.

@Algunenano, @Lloyd-Pottiger, @antonio2368  what do you think?
```[tasklist]
### Tasks
```

**Comment by den-crane** [comment]
SimpleAggregateFunction is calculated during MergeTree merges. 

You need to ask Facebook to implement merges and SimpleAggregateFunction in RocksDB.
