### ISSUE TITLE
Not able to read CSV file from S3 bucket from clickhouse client.

### ISSUE THREAD

**Issue by venkip541** [ClickHouse/ClickHouse#63034]
Hi Team,

I am trying to read CSV object from one of our S3 buckets from clickhouse client, but unfortunately i am facing below error while trying to read the csv with below query.

select * from s3('https://{bucket-name}.s3.ap-south-1.amazonaws.com/test.csv','CSV')

DB::Exception: Access Denied: Cannot extract table structure from CSV format file. You can specify the structure manually. (S3_ERROR)

I have created below S3 policy for accessing s3 objects.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::{bucket_name}",
                "arn:aws:s3:::{bucket_name}/*"            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::{bucket-name}/*"
            ]
        }
    ]
}

I can able to read the object using aws cli, but when i am tyring to do the same by connecting to db using clickhouse-client, i am facing access denied error.

Clickhouse Version: 22.7.7

Need your assistance in fixing the same.

BR
Venkatesh. P

**Comment by Algunenano** [comment]
22.7 is out of support. Update to a newer version.

**Comment by den-crane** [comment]
>Clickhouse Version: 22.7.7

version 22.7.7 is obsolete.

You read data using clickhouse-server, not clickhouse-client.

>I can able to read the object using aws cli,

It does not mean that clickhouse-SERVER has access to the data. You can pass `access_key_id`, `secret_access_key` to `s3` function.

**Comment by venkip541** [comment]
Sorry for the typo, we were actually trying from clickhouse command line. 

I have tested this against public s3 bucket where we were able to read the data stored, below is fyr.

Followed the below link.

https://clickhouse.com/docs/en/integrations/s3#using-clickhouse-local

select * from s3('https://datasets-documentation.s3.eu-west-3.amazonaws.com/nyc-taxi/trips_*.gz','TabSeparatedWithNames') limit 10;

**Comment by den-crane** [comment]
>>>> You can pass access_key_id, secret_access_key to s3 function <<<<<
> s3(path, [aws_access_key_id, aws_secret_access_key,] format, [compression])

With clickhouse-local 22.7.7 you need to enable use_environment_credentials https://clickhouse.com/docs/en/integrations/s3#managing-credentials Which is disabled by default.

But:

v**23.4.1.1943**-stable.md:* Enable `use_environment_credentials` for S3 by default, so the entire provider chain is constructed by default. [#47397](https://github.com/ClickHouse/ClickHouse/pull/47397) ([Antonio Andelic](https://github.com/antonio2368)).
