### ISSUE TITLE
DNS error when connecting through host.docker.internal

### ISSUE THREAD

**Issue by fabiokr** [ClickHouse/ClickHouse#63044]
I'm running clickhouse/clickhouse-server:24-alpine locally through docker version 26.0.1. I can connect to the running clickhouse server when running from my localhost.

Now, I'm trying to connect to the server from another container, which is executed like this:

```
docker run --add-host=host.docker.internal:host-gateway ...
```

From within that container, I can successfully ping `host.docker.internal`. But, when trying to connect with the clickhouse client, I get this error:

```
ClickHouse client version 24.4.1.1568 (official build).
Cannot resolve host (host.docker.internal), error 0: Host not found.
Code: 198. DB::NetException: Not found address of host: host.docker.internal. (DNS_ERROR)
```

What am I missing?

**Comment by den-crane** [comment]
MacOS ?

Isn't it easier to use the same docker-network for both containers?

**Comment by fabiokr** [comment]
> MacOS ?
> 
> Isn't it easier to use the same docker-network for both containers?

I'm running it on Linux. Using a docker-network indeed fixed the issue for me. I'm wondering why it was failing with host.docker.internal though. I had other services and clients (postgres, mysql) and they were working with `host.docker.internal`, only the clickhouse client was not.

**Comment by den-crane** [comment]
By default Clickhouse listens only localhost, by security reasons.

see https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#listen_host

```
<?xml version="1.0"?>
<clickhouse>
    <listen_host>::</listen_host>
...
```
