### ISSUE TITLE
Issue for -Array combinator

### ISSUE THREAD

**Issue by yangguang760** [ClickHouse/ClickHouse#63075]
This one works fine:

select groupArray(number) as numberArr,
arrayMax(numberArr) as maxNumber
from (
select * from numbers(5)
)

And this one raise error (Code: 184. DB::Exception: Aggregate function groupArray(number) is found inside another aggregate function in query: While processing groupArray(number) AS numberArr. (ILLEGAL_AGGREGATION) (version 24.4.1.491 (official build))):

select groupArray(number) as numberArr,
maxArray(numberArr) as maxNumber2
from (
select * from numbers(5)
)

In my humble opinion, the behavior of maxArray is supposed to be same with arrayMax.

**Comment by cangyin** [comment]
`arrayMax` is regular function, while `maxArray` is an aggregate function. Aggregate functions can't be nested in a single `SELECT` query.

> the behavior of maxArray is supposed to be same with arrayMax.

Yes, but they are meant to be used in different ways. In this case, it should be written as:
```sql
SELECT maxArray(numberArr) AS maxNumber2
FROM
(
    SELECT groupArray(number) AS numberArr
    FROM
    (
        SELECT *
        FROM numbers(5)
    )
)
```

**Comment by yangguang760** [comment]
inspired by #65560, use arrayReduce instead

select groupArray(number) as numberArr,
arrayReduce('max',numberArr) as maxNumber2
from (
select * from numbers(5)
)
