### ISSUE TITLE
Memory grows slowly ClickHouse server version 23.2.5.46

### ISSUE THREAD

**Issue by heimaoxia** [ClickHouse/ClickHouse#63084]
The memory of my clickhouse database slowly increased. After restarting clickhouse, the memory increased after a period of time.
![内存设置](https://github.com/ClickHouse/ClickHouse/assets/110767069/5c7cc66d-9837-4ff0-bb0b-678230ab6d97)
![内存使用量](https://github.com/ClickHouse/ClickHouse/assets/110767069/af584b60-ac30-4f7a-82f4-016efab0d5e9)
![Snipaste_2024-04-28_15-02-37](https://github.com/ClickHouse/ClickHouse/assets/110767069/e2b566c0-b6e2-4b5d-ae97-1c7d356c4ef8)
![系统内存](https://github.com/ClickHouse/ClickHouse/assets/110767069/356bc387-a4e7-4e33-9ce7-d2818001da24)

**Comment by heimaoxia** [comment]
not use kafka engine,   the table engine used is ReplicatedMergeTree,mysql,hdfs,hive

**Comment by Algunenano** [comment]
Please start by upgrading to a supported release
