### ISSUE TITLE
Engine doesn not support  "ORDER BY TIME DESC" ???

### ISSUE THREAD

**Issue by yxtwl94** [ClickHouse/ClickHouse#63085]
HI

I was really confused recently about how to property order my data by time!

we have a very large table(about 10billion rows)，every day will insert some data with timestamp.

our each query should get the latest data such as

`select * from ql_result where name like '%dad% order by time desc limit 10'`

but the problem is MergeTree Engine does not support ORDER BY DESC to create the table，so I must use the following:
`create table default.ql_result
(
    name Nullable(String),
    time        DateTime,
    id             UUID
)
    engine = MergeTree ORDER BY time
        SETTINGS index_granularity = 8192;
`
which could cause query the latest data really really slow! 

I also tried to change order by column to some other id,  but it will cause the full table scan because engine must find all data to sort, also very slow, I only need the lastest 10 data

**POSSIBLE SOLUTION:**
**I plan to use an additional column named time_desc which calculate the difference from 2099-12-01 to now, so this column may sorted desc, and I can directly use ORDER BY time_desc to create the table

but I think inserting data will be slower with the data grows,**

**ANYONE some IDEAS???? THKS!!!!**

**Comment by cangyin** [comment]
> I plan to use an additional column named time_desc which calculate the difference from 2099-12-01 to now

It's fine. The ingestion performance is not related to data volume.

**Comment by alexey-milovidov** [comment]
You can also use `-time::Int64`
