### ISSUE TITLE
clickhouse-local generats hundreds of thousands of directories in /tmp

### ISSUE THREAD

**Issue by jaumecastell** [ClickHouse/ClickHouse#63103]
After upgrading to the latest available clickhouse version (24.3), when inserting data using clickhouse-local command, hundreds of thousands of directories are created in /tmp directory. 

`clickhouse-local-1000-1713901625-16440521750061099670
clickhouse-local-100000-1713857644-16634073391541837949
clickhouse-local-100005-1713983333-15739537138146521532
clickhouse-local-10001-1713855728-9139165870536115084
clickhouse-local-10004-1713855728-3960280704403572412
clickhouse-local-100044-1714165172-7266065558036267841
clickhouse-local-100046-1713863266-14924399832452416727
clickhouse-local-100046-1714367162-473514863176041919
clickhouse-local-100047-1714367162-18444960897281923687
clickhouse-local-100049-1714096980-6657054296464238776
clickhouse-local-10005-1714060615-7843764312068745160
...`

This is not happening with version 24.2.

Why is this happening? Is there a way to disable it?

**Comment by Algunenano** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/62941
