### ISSUE TITLE
DROP PARTITION HANGS on 18.14.18

### ISSUE THREAD

**Issue by zxc111** [ClickHouse/ClickHouse#6312]
**Describe the bug**
`alter table drop partition` will hang when query the same table .
And kill this query is not work.
When I try to kill the select query or drop partition by sync, the kill action also hang.
What can I do to solve this?
![image](https://user-images.githubusercontent.com/2883637/62408224-cd742000-b5f7-11e9-8e48-754f9ce63504.png)

**How to reproduce**
env:
ClickHouse client version 18.14.18.
Connected to ClickHouse server version 18.14.18 revision 54409.
We insert new data to ssd, move old data to hdd raid and ln -s old data from hdd to ssd .

1. alter table target_table drop partition
2. select from target_table
3.then drop partition or select can not be killed

**Comment by orofarne** [comment]
19.14 (Yandex.Cloud Managed Service)
alter table drop partition + insert → same problem

**Comment by alexey-milovidov** [comment]
The bug in 18.14 is related to https://github.com/ClickHouse/ClickHouse/pull/6764 (fixed)

But I don't know what is the bug in 19.14.
@orofarne Is it specific to ON CLUSTER queries?

**Comment by orofarne** [comment]
@alexey-milovidov, single node configuration,
one `ALTER TABLE "..." DROP PARTITION ID '...'` query (via tcp)
and more then one `INSERT INTO "..." FORMAT JSONEachRow` queries in parallel (via http)
= deadlock

**Comment by alexey-milovidov** [comment]
ALTER will wait for all INSERT queries to finish. But should not continue to hang after INSERT queries will finish. 

What is the state of SHOW PROCESSLIST when the queries hang?

Could you please also ask Yandex.Cloud support with all the details? They will give these details to us and we will investigate further.

**Comment by orofarne** [comment]
typical situation:
https://gist.github.com/orofarne/bf0c64ccdc76d715e439ff74022663d9

**Comment by orofarne** [comment]
@alexey-milovidov, ticket #157356245795793

**Comment by iameugenejo** [comment]
@alexey-milovidov which version, commit or PR fixes this issue? I have `19.14.10.16` running and just encountered this issue, and I'd like to upgrade to the one that fixes this issue.

**Comment by iameugenejo** [comment]
I just had the same issue with `20.3.12.112`
