### ISSUE TITLE
What does 'double replication' mean in docs

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#63137]
Hello. I' m reading docs [here](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication)

> You can have any number of replicas of the same data. Based on our experiences, a relatively reliable and convenient solution could use **double replication** in production, with each server using RAID-5 or RAID-6 (and RAID-10 in some cases).

Does the **double replication** mean 3 replicas (each shard) or 2 replicas ?

Thks.

**Comment by alexey-milovidov** [comment]
It means two replicas in total (not three).
