### ISSUE TITLE
23.5.2 version cannot migrate parts to S3

### ISSUE THREAD

**Issue by hjun881** [ClickHouse/ClickHouse#63150]
### 23.5.2 version cannot migrate parts to S3

> Two replicas on the same chip are simultaneously migrating the same part and both migrations have failed. The error messages for both replicas are as follows:

* node1
```
2024.04.30 11:09:15.201837 [ 85235 ] {} <Warning> zkutil::Lock: Lock is lost, because session was expired. Path: /clickhouse/zero_copy/zero_copy_s3/b26f155d-9282-4b9e-8de3-4d6887293cdb/de9934e005f31f87df52f983e5a95ec1_24307_34995_6/part_exclusive_lock, message: 10.208.67.204
```

* node2
```
2024.04.30 10:11:02.463103 [ 93831 ] {} <Warning> MergeTreePartsMover: Path /data01/clickhouse/s3_metadata2/store/b26/b26f155d-9282-4b9e-8de3-4d6887293cdb/moving/de9934e005f31f87df52f983e5a95ec1_24307_34995_6 already exists. Will remove it and clone again.
```

### May I ask how to avoid this problem? Is it because this part is too large? Is there any parameter to solve this problem?

**Comment by melvynator** [comment]
@hjun881 This is an old version, does it reproduce on more recent version?

**Comment by Algunenano** [comment]
Not active
