### ISSUE TITLE
CREATE TABLE AS with SETTINGS should recognize settings for the corresponding ENGINE

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#63154]
**Describe the issue**

```
CREATE TABLE hits2 AS hits SETTINGS enable_block_number_column = 1, enable_block_offset_column = 1;
```

Without an explicit ENGINE specification it does not recognize that the settings belong to the MergeTree engine.

**Comment by v01dXYZ** [comment]
Hi,
It would need a reverse index between settings and engines to support all engines. 

Let's take the specific case of `MergeTree` to understand how a setting is registered,  a `Settings` trait is created using a macro invocation that registers all the settings (type, name, description, default value). It is used when creating `MergeTreeSettings` as an argument to the `BaseSettings` class template. `MergeTreeSettings` is used for the member `storage_settings` of `MergeTreeData`.

The small difficulties:

* There is no `getSettings` method in `IStorage` that allows to get the settings for a given `StoragePtr`. Maybe we should add it or add a class with such a method ?
* I don't know where exactly we should push the info to the reverse map, maybe when we register the storage from `create`. Furthermore where to add this reverse map as a member ?

The easier solution is to only support `MergeTree` and to infer this Engine whenever a `MergeTree` setting is encountered. It is sort of already done by suggestions as `system.merge_tree_settings` is the sole of its kind.

**Comment by cangyin** [comment]
It would be nice to have a `system.table_settings` for each table.

**Comment by nikhelk** [comment]
@alexey-milovidov Would love to take a crack at this as my first contribution if you would still like progress on it.
