### ISSUE TITLE
<Error> xxx.xxx (ReplicatedMergeTreePartCheckThread) Part xxx is lost forever

### ISSUE THREAD

**Issue by kernel288** [ClickHouse/ClickHouse#63188]
Hi 

Clickhouse has reported that the shard is missing
Yesterday I upgraded the ck version
from 23.8 to 24.3 
一、Upgrade ch version.
二、2024.04.30  restart zk server

, It's report some part is lost 

```python

SELECT *
FROM system.zookeeper
WHERE (path = '/clickhouse/ztmdb/tables/01/xxx/replicas/SHPL007176028/parts') AND (name NOT IN (
    SELECT name
    FROM system.parts
    WHERE `table` = 'xxx'
))

Query id: 97744565-4fc2-4cce-9f64-a2d3a83f285d

Ok.

0 rows in set. Elapsed: 30.778 sec. Processed 865.22 thousand rows, 166.39 MB (28.11 thousand rows/s., 5.41 MB/s.)
Peak memory usage: 678.01 MiB.



SHPL007176028 :) 



2024.04.30 21:26:57.282054 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Part 8961b463a8a1b23b4b067c2f906a9435_5035_5035_0 is lost forever.
2024.04.30 21:27:04.487347 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): No replica has part covering 145b0f7c8fc8ab58a80756ca2be99edd_5035_5035_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2024.04.30 21:27:32.896659 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Part 145b0f7c8fc8ab58a80756ca2be99edd_5035_5035_0 is lost forever.
2024.04.30 21:27:39.452207 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): No replica has part covering 45d69de61b4b5410b060ea0b1c27864a_5005_5005_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2024.04.30 21:28:12.043104 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Part 45d69de61b4b5410b060ea0b1c27864a_5005_5005_0 is lost forever.
2024.04.30 21:28:17.973080 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): No replica has part covering a83ea711c968702b4af2c58aab7b02c2_4997_4997_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2024.04.30 21:28:42.121497 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Part a83ea711c968702b4af2c58aab7b02c2_4997_4997_0 is lost forever.
2024.04.30 21:28:47.694082 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): No replica has part covering aa8c8a9277b8bfa0caffd653598c0cbc_5006_5006_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2024.04.30 21:29:10.345579 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Part aa8c8a9277b8bfa0caffd653598c0cbc_5006_5006_0 is lost forever.
2024.04.30 21:29:17.607424 [ 192313 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): No replica has part covering 75e23eddb8755bee28906b58f5ee0ba5_5371_5371_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.

```

**Comment by kernel288** [comment]
replicate second  report error 

```python
2024.04.30 22:06:56.345939 [ 44136 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Part 122d0e21fa7985ec7c01236682df3717_5344_5344_0 is lost forever.
2024.04.30 22:06:57.256266 [ 44136 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): No replica has part covering 122d0e21fa7985ec7c01236682df3717_5335_5335_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2024.04.30 22:06:57.740168 [ 44136 ] {} <Error> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Part 122d0e21fa7985ec7c01236682df3717_5335_5335_0 is lost forever.

```

**Comment by tavplubix** [comment]
Please share all logs containing the part name from all replicas.

**Comment by kernel288** [comment]
> Please share all logs containing the part name from all replicas.

This is one replicate  error log file.
[clickhouse-server.err.log.zip](https://github.com/ClickHouse/ClickHouse/files/15166972/clickhouse-server.err.log.zip)

**Comment by kernel288** [comment]
> Please share all logs containing the part name from all replicas.

That one 

122d0e21fa7985ec7c01236682df3717_5444_5444_0

```python
/var/log/clickhouse-server/clickhouse-server.log.1.gz:2024.04.30 13:10:32.462746 [ 29374 ] {} <Trace> ztmdb.ZTO_SCAN_DISP_LOCAL (9bc152c0-2545-42cc-a623-e73e98ccd144): Enqueued fetches after mimic:

``` 
The log file is big . I upload the pic 
<img width="1027" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/11566386/5a1c51de-a6e9-43c6-9c26-a429ad6f010f">

**Comment by kernel288** [comment]
> Please share all logs containing the part name from all replicas.

[clickhouse-server.err.log.zip](https://github.com/ClickHouse/ClickHouse/files/15167389/clickhouse-server.err.log.zip)

This is node one error log file.

**Comment by kernel288** [comment]
This second replicate 

```python
[root@SHPL007176028 ~]# grep 122d0e21fa7985ec7c01236682df3717_5444_5444_0 /var/log/clickhouse-server/clickhouse-server.err.log
[root@SHPL007176028 ~]# zgrep 122d0e21fa7985ec7c01236682df3717_5444_5444_0 /var/log/clickhouse-server/clickhouse-server.log*.gz
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 08:00:59.665526 [ 166559 ] {} <Trace> ztmdb.xxx (ReplicatedMergeTreeQueue): Insert entry queue-0002796997 to queue with type GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 09:28:15.600523 [ 168344 ] {} <Trace> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Enqueueing 122d0e21fa7985ec7c01236682df3717_5444_5444_0 for check after 0s
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 09:28:15.600619 [ 168344 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 10:19:31.118041 [ 166945 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 10:55:39.302463 [ 168421 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:09:03.313962 [ 166975 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:33:28.193031 [ 167183 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:58:56.044823 [ 166942 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:15:48.247565 [ 167194 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:33:42.446144 [ 166946 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:56:53.675019 [ 166944 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 13:18:54.174976 [ 168402 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 13:43:06.297254 [ 166910 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
[root@SHPL007176028 ~]#
```

**Comment by tavplubix** [comment]
> I upload the pic

Please never share logs as screenshots. It's impossible to search and hard to read.

> [clickhouse-server.err.log.zip](https://github.com/ClickHouse/ClickHouse/files/15167389/clickhouse-server.err.log.zip)
> This is node one error log file.

This is only Error logs from only one replica. We cannot help without Trace logs from all replicas.

**Comment by kernel288** [comment]
> ```python
> [root@SHPL007176028 ~]# grep 122d0e21fa7985ec7c01236682df3717_5444_5444_0 /var/log/clickhouse-server/clickhouse-server.err.log
> [root@SHPL007176028 ~]# zgrep 122d0e21fa7985ec7c01236682df3717_5444_5444_0 /var/log/clickhouse-server/clickhouse-server.log*.gz
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 08:00:59.665526 [ 166559 ] {} <Trace> ztmdb.xxx (ReplicatedMergeTreeQueue): Insert entry queue-0002796997 to queue with type GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 09:28:15.600523 [ 168344 ] {} <Trace> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Enqueueing 122d0e21fa7985ec7c01236682df3717_5444_5444_0 for check after 0s
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 09:28:15.600619 [ 168344 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 10:19:31.118041 [ 166945 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 10:55:39.302463 [ 168421 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:09:03.313962 [ 166975 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:33:28.193031 [ 167183 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:58:56.044823 [ 166942 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:15:48.247565 [ 167194 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:33:42.446144 [ 166946 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:56:53.675019 [ 166944 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 13:18:54.174976 [ 168402 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> /var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 13:43:06.297254 [ 166910 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
> [root@SHPL007176028 ~]#
> ```

second replicate error log 

[root@SHPL007176028 ~]# grep 122d0e21fa7985ec7c01236682df3717_5444_5444_0 /var/log/clickhouse-server/clickhouse-server.err.log
[root@SHPL007176028 ~]# zgrep 122d0e21fa7985ec7c01236682df3717_5444_5444_0 /var/log/clickhouse-server/clickhouse-server.log*.gz
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 08:00:59.665526 [ 166559 ] {} <Trace> ztmdb.xxx (ReplicatedMergeTreeQueue): Insert entry queue-0002796997 to queue with type GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 09:28:15.600523 [ 168344 ] {} <Trace> ztmdb.xxx (ReplicatedMergeTreePartCheckThread): Enqueueing 122d0e21fa7985ec7c01236682df3717_5444_5444_0 for check after 0s
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 09:28:15.600619 [ 168344 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 10:19:31.118041 [ 166945 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 10:55:39.302463 [ 168421 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:09:03.313962 [ 166975 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:33:28.193031 [ 167183 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 11:58:56.044823 [ 166942 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:15:48.247565 [ 167194 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:33:42.446144 [ 166946 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 12:56:53.675019 [ 166944 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 13:18:54.174976 [ 168402 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
/var/log/clickhouse-server/clickhouse-server.log.0.gz:2024.04.30 13:43:06.297254 [ 166910 ] {} <Information> ztmdb.xxx (759c66c6-ba9a-47d2-b3b2-53381e355e02): Code: 234. DB::Exception: No active replica has part 122d0e21fa7985ec7c01236682df3717_5444_5444_0 or covering part (cannot execute queue-0002796997: GET_PART with virtual parts [122d0e21fa7985ec7c01236682df3717_5444_5444_0]). (NO_REPLICA_HAS_PART)
[root@SHPL007176028 ~]#

**Comment by kernel288** [comment]
HI 

I'm guessing it's auto-recovered


```python
SELECT
    count(*),
    type,
    `table`
FROM system.replication_queue
GROUP BY
    type,
    `table`

Query id: 7bee48a5-426d-4b49-9a05-bee74fcf43fc

   ┌─count()─┬─type────────┬─table───────────────┐
1. │   41077 │ GET_PART    │ xxx │
2. │   17187 │ MERGE_PARTS │ xxx │
3. │   13907 │ DROP_PART   │ xxx │
   └─────────┴─────────────┴─────────────────────┘

```

**Comment by tavplubix** [comment]
1. It cannot auto-recover, "lost forever" means that it's lost forever
2. Having 70k entries in replication queue is not okay

**Comment by kernel288** [comment]
> 1. It cannot auto-recover, "lost forever" means that it's lost forever
> 2. Having 70k entries in replication queue is not okay

Thank u so much . 
I drop one replicate to fix it

**Comment by tbragin** [comment]
Question appears answered, closing.
