### ISSUE TITLE
Support memory only mode for StorageJoin

### ISSUE THREAD

**Issue by zombiemonkey** [ClickHouse/ClickHouse#6318]
Is it possible to add a memory only mode or temporary table option for StorageJoin?

Background - I'm using StorageJoin in a soon to be released Open Source project and the performance is excellent for constructing matrices and vectors of identical length as arrays and use them as temporary inputs into real tables. If I can avoid the overhead of writing to disk for StorageJoin I could save some IO.

Thanks,

Z

**Comment by alexey-milovidov** [comment]
Yes, it is very easy to implement with table settings.

**Comment by zombiemonkey** [comment]
Thanks Alexey,

Thinking about this more it would probably have to be Memory vs temporary as I would need to access the same data from multiple sessions (as well as perform parallel operations).

Thanks again!
