### ISSUE TITLE
RFC: DNS cache respect TTL from DNS server

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#63229]
ClickHouse utilizes a DNS cache with several management options. Currently, you can:

1) Toggle the DNS cache on or off using the `disable_internal_dns_cache` setting.
2) Set the frequency at which ClickHouse checks for changes in DNS records with the `dns_cache_update_period` and `dns_max_consecutive_failures` settings.
3) Manually clear the DNS cache using the `SYSTEM DROP DNS CACHE` command.
4) Inspect the contents of the DNS cache via the `system.dns_cache` table.

However, in dynamic environments, frequently re-resolving all DNS names can present challenges due to numerous DNS entries, slow DNS servers, etc.

DNS servers typically provide a TTL (Time To Live) with each response, which administrators can use to control the lifespan of each DNS record. Consequently, for highly dynamic entries, the TTL is usually set very short, while for static ones, it is longer. Frequent re-resolution of static names is inefficient, and extending the caching of dynamic DNS names beyond their TTL can result in using outdated IPs.

To optimize that, we could leverage the TTL information provided by DNS servers to determine the lifespan of entries in the DNS cache.

**Comment by arthurpassos** [comment]
I have briefly looked into this and there are a few considerations:

1. Should we implement TTL logic for reverse queries as well?
2. For regular queries, ClickHouse relies on Poco, which relies on system getaddrinfo. This query does not bring in any TTL info. Not sure if any sort of TTL or caching mechanism is implemented on system side. We could start using ares_getaddrinfo, this version instead returns the TTL info.
3. The ares_gethostbyaddr used to perform reverse queries does not return any ttl info. Maybe ares_getaddrinfo could be called for every host returned by the former.

**Comment by alexey-milovidov** [comment]
I'd prefer not to have this feature.

**Comment by filimonov** [comment]
> Mainly to avoid problems with long TTL

Well, the logic of periodic updates for records with a large TTL can be maintained.

My primary concern, however, is the growth in complexity. 
1) The cache, which is currently quite simple, will require additional logic.
2) Standard library methods used by Poco do not provide information about TTL. Reimplementing DNS resolution with c-ares might also necessitate adding support for features normally handled by libc, such as /etc/hosts, HOSTALIASES, RES_OPTIONS, and possibly nsswitch.conf (I'm wondering if musl supports all of these).

Thus, the ratio of 'extra complexity' to 'benefits' seems quite unfavorable, and it might indeed be better to keep everything as it is for now.

**Comment by alexey-milovidov** [comment]
Yes, let's keep everything as is.
