### ISSUE TITLE
Issue Reading Parquet Files GZIP from Pandas(Python)

### ISSUE THREAD

**Issue by hockey331** [ClickHouse/ClickHouse#63240]
When inserting S3 Files that have been written as a GZIP parquet there seems to be some type of driver issue (see error below). 

`{ "meta": [ ], "data": [ ], "rows": 0, "exception": "Code: 354. DB::Exception: inflate failed: data error: While reading from: XXX.gzip: (in file XXX.gzip): While executing ParquetBlockInputFormat: While executing S3. (ZLIB_INFLATE_FAILED) (version 24.2.2.16100 (official build))" }`

When trying a CSV file that had been compressed as a GZIP, a regular parquet file there were no issues. 

> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
There is a compression inside Parquet, it has no relation to a file compression.
It seems you are trying to load Parquet having internal compression and name it .gzip.
It should have normal name `XXX.parquet` not `XXX.gzip`.

**Comment by Algunenano** [comment]
Needs info an a reproducer

**Comment by Algunenano** [comment]
No info, no reproducer.
