### ISSUE TITLE
Since 24.04, clickhouse-odbc-bridge and clickhouse-library-bridge are missing on packages.clickhouse.com

### ISSUE THREAD

**Issue by herver** [ClickHouse/ClickHouse#63262]
**Installation type**

Packages (rpms from `packages.clickhouse.com`)

**Describe the issue**
With #62114 merge, I understand that `clickhouse-odbc-bridge` and `clickhouse-library-bridge` have been moved to their own packages, they were last part of `clickhouse-common-static` with `24.3.3` as far as I can tell: 

```shell
[...]
# dnf provides '*/clickhouse-odbc-bridge'
clickhouse-common-static-24.3.3.102-1.x86_64 : Common files for ClickHouse
Repo        : clickhouse
Matched from:
Filename    : /usr/bin/clickhouse-odbc-bridge
```

Unfortunately, it looks like the corresponding packages (`clickhouse-odbc-bridge` and `clickhouse-library-bridge`) are missing from the repositories at `packages.clickhouse.com`:

```shell
# dnf repoquery clickhouse-odbc-bridge
Last metadata expiration check: 0:09:53 ago on Thu 02 May 2024 09:56:36 AM CEST.
# 
```

Could you please update the publishing process so that these packages are also pushed on the `packages.clickhouse.com` repositories ?

Thank you !

**Comment by Felixoid** [comment]
Thanks for rising it. It should be fixed for the release and followings.
