### ISSUE TITLE
Add support for DEFAULT keyword for INSERT statement 

### ISSUE THREAD

**Issue by BoseSean** [ClickHouse/ClickHouse#6331]
**Use case**
```
create table table1
(
    field1 Int32,
    field2 Int32,
    field3 Int32 default CAST(1337, 'Int32'),
    field4 Int32 default CAST(1337, 'Int32')
)engine = MergeTree() PARTITION BY field1 
ORDER BY (field1, field2) 
SETTINGS index_granularity = 8192;

insert into table1 (field1, field3) values (5, DEFAULT)
insert into table1 values (5, DEFAULT, 10, DEFAULT)
```
Result:

| field1 | field2 | field3 | field4 |
|--------|--------|--------|--------|
| 5      | 0      | 1337   | 1337   |
| 5      | 0      | 10     | 1337   |

**Additional context**
With the `DEFAULT` keyword, insertion of data would have a bit more flexibility. And, let data with some missing values utilize bulk loading.

**Comment by filimonov** [comment]
Sounds reasonable, supported by most of popular DBMS (including MySQL, Postgres, MsSQL etc)

**Comment by tavplubix** [comment]
After #7215 `NULL` keyword can be used as `DEFAULT` if `input_format_null_as_default=1` and column type is not `Nullable`

**Comment by alexey-milovidov** [comment]
It can be implemented quite easily.

**Comment by 1over** [comment]
I would like to try this. @alexey-milovidov

**Comment by alexey-milovidov** [comment]
@1over Do you have any troubles implementing it? Do you need help?

**Comment by 1over** [comment]
@alexey-milovidov no troubles yet, I was occupied with other things. I plan to finish it in the coming days
