### ISSUE TITLE
Add support of a JOIN condition (t1.a IS NULL AND t2.a IS NULL)

### ISSUE THREAD

**Issue by konsta-danyliuk** [ClickHouse/ClickHouse#63318]
**Describe the unexpected behaviour**

- At the moment ClickHouse doesn't support JOIN condition `(t1.a IS NULL AND t2.a IS NULL)`.

**How to reproduce**
* Queries to run that lead to unexpected result

```
SELECT
*
FROM
t1
LEFT JOIN t2 ON (
(
(t1.a = t2.a) AND (t1.a IS NOT NULL) AND (t2.a IS NOT NULL)
)
OR ( (t1.a IS NULL) AND (t2.a IS NULL))
);
```

**Expected behavior**

- The mentioned JOIN query should not return the error.

**Error message and/or stacktrace**

```
Cannot get JOIN keys from JOIN ON section
```
**Additional context**
- Related internal escalation https://github.com/ClickHouse/support-escalation/issues/1950.

**Comment by janwillemvd** [comment]
Any news on this one, @konsta-danyliuk?

**Comment by vdimir** [comment]
One more case:

```sql
SELECT
*
FROM
t1
LEFT JOIN t2 ON (
(
(t1.a = t2.a) AND (t1.a IS NOT NULL) AND (t2.a IS NOT NULL)
)
OR ( (t1.a != t2.a) (t1.a IS NULL) AND (t2.a IS NULL))
);

```
