### ISSUE TITLE
Error in ClickHouse query: Multiple expressions for alias.

### ISSUE THREAD

**Issue by nkdanta1** [ClickHouse/ClickHouse#63320]
When executing the following query in ClickHouse version 24.4.1.2088:
```
SELECT toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc,
sum(impressions) AS Impressions,
sum(clicks) AS Clicks,
sum(revenue) AS Revenue
FROM test_table
WHERE time_stamp_utc >= toDateTime('2024-04-25 00:00:00')
AND time_stamp_utc < toDateTime('2024-05-02 00:00:00')
GROUP BY toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc
ORDER BY Impressions DESC
LIMIT 1000;
```

I encountered the following error:
```
Code: 179. DB::Exception: Received from localhost:9000. DB::Exception: 
Multiple expressions toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc and toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc for alias time_stamp_utc.
In scope SELECT toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc, sum(impressions) AS Impressions, sum(clicks) AS Clicks, sum(revenue) AS Revenue FROM test_table WHERE (time_stamp_utc >= toDateTime('2024-04-25 00:00:00')) AND (time_stamp_utc < toDateTime('2024-05-02 00:00:00')) GROUP BY time_stamp_utc ORDER BY Impressions DESC LIMIT 1000. 
(MULTIPLE_EXPRESSIONS_FOR_ALIAS)
```

### Additional Information
- This query works as expected in ClickHouse version 24.2.3.70 but fails with the described error in version 24.4.1.2088.

### Table Schema
```
CREATE TABLE test_table(
    time_stamp_utc DateTime,
    impressions UInt32,
    clicks UInt32,
    revenue Float32,
) ENGINE = MergeTree
ORDER BY time_stamp_utc;
```

**Comment by Algunenano** [comment]
Can you please post a reproducer, with table schema, so we don't have to guess? Thank you

**Comment by Algunenano** [comment]
This is a behaviour change in the new analyzer, but I don't know if it's a bug or not.

There are 2 identical aliases, and it's not clear to me what the behaviour of the second alias (`GROUP BY toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc`) should be as it uses the aliased column `time_stamp_utc`: Does it reference `test_table.time_stamp_utc` or does it reference the alias declared in the select projection (`SELECT toStartOfDay(toDateTime(time_stamp_utc)) AS time_stamp_utc,`).

Maybe @KochetovNicolai or somebody else from the team can answer

**Comment by Algunenano** [comment]
BTW, in the meantime you can disable the new analyzer (`allow_experimental_analyzer = 0`)

**Comment by KochetovNicolai** [comment]
```
select number % 2 as number, count() from numbers(10) where number != 0 group by number % 2 as number
```
