### ISSUE TITLE
Clear mark cache for a part as soon as the part becomes inactive

### ISSUE THREAD

**Issue by romaincointepas** [ClickHouse/ClickHouse#63322]
This would help decrease useless memory usage when `mark_cache_size` is set to a high value to always fit all marks in cache, and new entries being added to the cache do not automatically clear the mark cache for inactive parts.

**Comment by alexey-milovidov** [comment]
This makes sense, but it is hard to implement and might not be worth it. Mark cache entries don't have a reference back to a table. The same is true for every other cache. For example, when a table is deleted, the data can still be present in the filesystem cache but will be evicted as soon as needed. I'd prefer to not implement this optimization.
