### ISSUE TITLE
Why I was able to DROP SETTINGS PROFILE ON CLUSTER on 24.3 only with ACCESS MANAGEMENT, and I am not able to do so on 24.4?

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#63339]
```
echo -e "CREATE USER OR REPLACE user_privileges_granted_via_role10" | clickhouse client -n
echo -e "CREATE ROLE OR REPLACE role_privileges_granted_via_role10" | clickhouse client -n
echo -e  "GRANT role_privileges_granted_via_role10 TO user_privileges_granted_via_role10" | clickhouse client -n
echo -e "CREATE SETTINGS PROFILE drop_row_policy_DROP_SETTINGS_PROFILE_on_cluster10 ON CLUSTER sharded_cluster" | clickhouse client -n
echo -e "GRANT ACCESS MANAGEMENT ON *.* TO role_privileges_granted_via_role10" | clickhouse client -n
echo -e "DROP SETTINGS PROFILE drop_row_policy_DROP_SETTINGS_PROFILE_on_cluster10 ON CLUSTER sharded_cluster" | clickhouse client -n --user "user_privileges_granted_via_role10"
```
On 24.3 (24.3.3.102) I am able to `DROP SETTINGS PROFILE` on cluster only with `ACCESS MANAGEMENT` privilege.
On 24.4 I get
```
Received exception from server (version 24.4.1):
Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: user_privileges_granted_via_role10: Not enough privileges. To execute this query, it's necessary to have the grant CLUSTER ON *.*. (ACCESS_DENIED)
(query: DROP SETTINGS PROFILE drop_row_policy_DROP_SETTINGS_PROFILE_on_cluster10 ON CLUSTER sharded_cluster
)
```
It looks like a fix, but I couldn't find related pr in changelog.

**Comment by den-crane** [comment]
>To execute this query, it's necessary to have the **grant CLUSTER ON *.*.** (ACCESS_DENIED)


https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#-clickhouse-release-241-2024-01-30

Enable various changes to improve the access control in the configuration file. These changes affect the behavior, and you check the config.xml in the access_control_improvements section. In case you are not confident, keep the values in the configuration file as they were in the previous version. https://github.com/ClickHouse/ClickHouse/pull/58584 ([Alexey Milovidov](https://github.com/alexey-milovidov)).


https://github.com/ClickHouse/ClickHouse/pull/58584/files

`<on_cluster_queries_require_cluster_grant>true</on_cluster_queries_require_cluster_grant>`

**Comment by alsugiliazova** [comment]
Thank you
