### ISSUE TITLE
OPTIMIZE TABLE: When to use it?

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#63356]
Hi guys, is there any best practice on using “OPTIMIZE TABLE partition x” on partitions that won’t be touched anymore with new INSERTs for some time, but can be queried often for SELECTs? Does it always make sense to optimize them? Speaking about a simple mergetree (without deduplication)

thanks in advance

**Comment by den-crane** [comment]
No such best practice. Each user has own preferences.
Clickhouse works perfectly without using `optimize`. 
Clickhouse has very sophisticated merge planner which has a goal to reduce a number of merges and keep reasonable number parts the same time. This approach allows to save disk and CPU resources for queries.

One of my database has partitions with a final size 100MB, another database has partitions with a final size 15TB. It will be insane mistake to try to optimize fully in the second case.

Check also [min_age_to_force_merge_seconds](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#min_age_to_force_merge_seconds). But it basically the same as optimize+crond, the same concerns.

**Comment by enzorevo** [comment]
> No such best practice. Each user has own preferences. Clickhouse works perfectly without using `optimize`. Clickhouse has very sophisticated merge planner which has a goal to reduce a number of merges and keep reasonable number parts the same time. This approach allows to save disk and CPU resources for queries.
> 
> One of my database has partitions with a final size 100MB, another database has partitions with a final size 15TB. It will be an insane mistake to try to optimize fully in the second case.
> 
> Check also [min_age_to_force_merge_seconds](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#min_age_to_force_merge_seconds). But it basically the same as optimize+crond, the same concerns.

Thanks for the reply. Why you say it would be an insane mistake for the second table to be OPTIMIZEd? In what terms?

**Comment by den-crane** [comment]
What is OPTIMIZE does? It calls the unplanned merge. 

What the sense to call it? To merge parts to max size (150GB)?
It's a waste of resources to merge 2 parts, one part with size 130GB and another with a size 10KB, if you have more parts with 150GB in the same partition, or just more parts.

**Comment by enzorevo** [comment]
> What is OPTIMIZE does? It calls the unplanned merge.
> 
> What the sense to call it? To merge parts to max size (150GB)? It's a waste of resources to merge 2 parts, one part with size 130GB and another with a size 10KB, if you have more parts with 150GB in the same partition, or just more parts.

Ok so the idea is to rely on the result that the automatic merges get normally out, if we have big-size partitions?

**Comment by den-crane** [comment]
Think about OPTIMIZE like it debug/admin command. Basically you should never use it, never need. 
I guess it was introduced for Clickhouse CI (for Clickhouse development), to force merges within CI checks.

**Comment by enzorevo** [comment]
Ok, with this explanation it makes more sense. Thanks!
