### ISSUE TITLE
Clickhouse Kafka consuming performance

### ISSUE THREAD

**Issue by igor-sh8** [ClickHouse/ClickHouse#6336]
Hello. 
I am trying to connect Clickhouse as a consumer to Kafka. But faced with the next situation. 
Schema1:
Single server Kafka (1 topic with 6 partitions) -> 1 Clickhouse Table with Kafka Engine (6 consumers) ->1 MatView ->1 PlainTable.
On such schema Сlickhouse can not read the data in the real-time and the lag is growing all the time.
Schema2:
Single server Kafka (6 topic with 1 partition in each topic) -> 6 Clickhouse Tables with Kafka Engine (1 consumers) -> 6 MatViews -> -> 1 PlainTable.
Such schema works properly, but architecturally wrong.
Is it a real bug or is it a specific realization of a Clickhouse consumer ?

**Comment by filimonov** [comment]
There are several important bugs in Kafka engine currently. :\

**Comment by bopohaa** [comment]
This is possible when partitions are not filled evenly. Because all consumers for one math view read in one stream sequentially

**Comment by igor-sh8** [comment]
Hi. 
All partitions are filled evenly and I see that lag increased on all partitions in the topic.
And on the producer side it is random partitioner.

**Comment by bopohaa** [comment]
In your case, when reading in 6 threads, everything is fine, and when reading in one thread, there is a lack. It can be assumed that there is not enough performance for 6 consumers to work on one processor core. See how the load on the processor cores is distributed.

**Comment by igor-sh8** [comment]
So, in any case 1 topic - it is 1 thread on Clickhouse regardless of the number of partitions in the topic?
Is it possible to configure a few threads on the same topic (maybe one thread per consumer) ?

**Comment by bopohaa** [comment]
Right, but if you make several CH shards, each of which will be a consumer of a topic with several partitions, then we will get good scalability.

**Comment by igor-sh8** [comment]
In this case we will have too small load on the one shard (in our logic schema we have only a few topics) and we will get the overhead in Clickhouse shards. 
In our situation we would like to increase the load on the one shard.
Is there some way to set a thread per partition or maybe a few threads on a topic ?

**Comment by bopohaa** [comment]
1. Change the message format to reduce the cost of deserialization (protobuf, csv, native)
2. Several view on the same topic, one consumer for each view

**Comment by bopohaa** [comment]
We use protobuff as a format and have an insertion rate from one consumer (thread) of more than 100,000 messages per second (the kafka server is located in another city)

**Comment by igor-sh8** [comment]
We use Native format in our schema.
And also for now we use a few MatViews per table. 
Ideally we just wanted to make the whole architecture more evident. 
In case with MatViews, when we will add a few more tables, we will need to create a whole set of MatViews for each table. It is a bit uncomfortable. 
But in any case, I understood how Clickhouse works with Kafka
So thanks for the explanation and help.

**Comment by igor-sh8** [comment]
We created our own service that reads data from Kafka and inserts it into the Clickhouse table with Null Engine. And in such schema Clickhouse works more efficiently (it can process much more data than table with Kafka Engine). 
So maybe like a feature it is possible to add for example setting to Kafka Engine table where can set how many threads Kafka Engine table will use.

**Comment by leoluk** [comment]
Any update on this? Is it true that CH Kafka ingestion is single-threaded on a single shard regardless of partition count?

**Comment by filimonov** [comment]
Still true.
Regarding performance - you can create several Kafka tables to consume in parallel, and increasing kafka_max_block_size to values like 512-1024k usually solves the problem.
