### ISSUE TITLE
Support for `<`, `<=`, `>`, `>=` operator with ASOF join.

### ISSUE THREAD

**Issue by MetalRex101** [ClickHouse/ClickHouse#6337]
It would be useful, for example, if we want to join previous entity state to current state.

```
CREATE TABLE states (
    entity_id UUID
    state INT8
    timestamp DateTime
)
```

```
SELECT state AS cur_state, prev_state FROM states ASOF JOIN states AS prev_states ON states.entity_id = prev_states.entity_id AND states.timestamp > prev_states.timestamp ORDER BY timestamp DESC LIMIT 10;
```

**Comment by Tri0L** [comment]
+1. Need this functionality.

**Comment by 4ertus2** [comment]
How to implement:
1. Add less and greater logic here https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/CollectJoinOnKeysVisitor.cpp#L72
2. Save kind of comparison it is here https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/CollectJoinOnKeysVisitor.cpp#L81
3. Passthrough the kind of comparison into AnalyzedJoin (it would be avaliable in Join class as field)
4. Change hardcoded ```>=``` logic depending on saved comparison type here https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/RowRefs.cpp#L75
5. Make tests for corner cases.

At the point 4 upper_bound is ```>=```, lower_bound would be equal to ```<=```. For strict comparison we need "upper_bound/lower_bound but not equal" logic.

**Comment by 4ertus2** [comment]
#7282
