### ISSUE TITLE
'Block with ID ... already exists; ignoring it' after ALTER .. DELETE 

### ISSUE THREAD

**Issue by showsmall** [ClickHouse/ClickHouse#6339]
os versions and soft version：
ClickHouse server version 19.9.2.4 (official build).
zookeeper-3.4.8
Ubuntu 18.10 (GNU/Linux 4.18.0-25-generic x86_64)
ClickHouse python-driver version 18.10.0, revision: 54406

Configuration instructions：
Three nodes, three copies，Three nodes for zookeeper.Table is partitioned by datetime

A、run：alter table detail delete where id < 1000000000000000000000;
      run done. not error.
B、Write the same data as the part just deleted.Found that the client did not report an error, but there is no data in the clickhouse.
C、clickhouse logs：
2019.08.05 15:11:28.760904 [ 62 ] {d5fb048a-c3af-4360-bfee-f7530c43fdba} <Debug> bi.detail (Replicated OutputStream): Wrote block with ID '201612_12551805212758245937_16168821858107728373', 5000 rows
2019.08.05 15:11:28.765536 [ 62 ] {d5fb048a-c3af-4360-bfee-f7530c43fdba} <Information> bi.detail (Replicated OutputStream): Block with ID 201612_12551805212758245937_16168821858107728373 already exists; ignoring it.
2019.08.05 15:11:28.767004 [ 62 ] {d5fb048a-c3af-4360-bfee-f7530c43fdba} <Debug> MemoryTracker: Peak memory usage (for query): 60.09 MiB.
2019.08.05 15:11:28.767099 [ 62 ] {d5fb048a-c3af-4360-bfee-f7530c43fdba} <Debug> MemoryTracker: Peak memory usage (total): 60.09 MiB.
2019.08.05 15:11:28.767155 [ 62 ] {d5fb048a-c3af-4360-bfee-f7530c43fdba} <Information> TCPHandler: Processed in 0.830 sec.
2019.08.05 15:11:28.767590 [ 62 ] {} <Information> TCPHandler: Done processing connection.

D、zookeeper logs：
2019-08-05 07:11:28,743 [myid:3] - INFO  [ProcessThread(sid:3 cport:-1)::PrepRequestProcessor@598] - Got user-level KeeperException when processing sessionid:0x16badbb909a000a type:multi cxid:0x1b5f5 zxid:0x1016d868a txntype:-1 reqpath:n/a aborting remaining multi ops. Error Path:/clickhouse/tables/01-01/detail/blocks/201612_12551805212758245937_16168821858107728373 Error:KeeperErrorCode = NodeExists for /clickhouse/tables/01-01/detail/blocks/201612_12551805212758245937_16168821858107728373

There are no other error logs except C and D above.
I also found that after deleting sql again, the table folder partition will repeat the same prefix.

The following is the partition folder after running the first SQL:
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 197001_0_19_2_22/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201611_0_20_5_27/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201612_0_28_5_35/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201701_0_15_2_22/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201702_0_14_2_21/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201703_0_16_3_23/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201704_0_16_3_23/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201705_0_14_2_21/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201706_0_14_2_21/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201707_0_557_18_564/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201708_0_112_10_119/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201709_0_9_2_16/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201710_0_6_2_13/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201711_0_28_5_35/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201712_0_949_21_956/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201801_0_4861_22_4868/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201802_0_2074_21_2081/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201803_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201804_0_689_21_696/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201805_0_1172_21_1179/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201806_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201807_0_104_20_111/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201808_0_32_7_39/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201809_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201810_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201811_0_3_1_10/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201812_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201901_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201902_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201903_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201904_0_20_5_27/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201905_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201906_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201907_0_484_19_491/
drwxr-x---  2 clickhouse clickhouse  4096 Jul 26 17:43 detached/
-rw-r-----  1 clickhouse clickhouse     1 Jul 26 17:43 format_version.txt

The following is the partition folder after running the second SQL:

drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 197001_0_19_2_22/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 197001_0_19_2_23/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201611_0_20_5_27/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201611_0_20_5_28/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201612_0_28_5_35/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201612_0_28_5_36/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201701_0_15_2_22/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201701_0_15_2_23/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201702_0_14_2_21/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201702_0_14_2_22/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201703_0_16_3_23/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201703_0_16_3_24/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201704_0_16_3_23/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201704_0_16_3_24/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201705_0_14_2_21/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201705_0_14_2_22/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201706_0_14_2_21/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201706_0_14_2_22/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201707_0_557_18_564/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201707_0_557_18_565/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201708_0_112_10_119/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201708_0_112_10_120/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201709_0_9_2_16/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201709_0_9_2_17/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201710_0_6_2_13/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201710_0_6_2_14/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201711_0_28_5_35/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201711_0_28_5_36/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201712_0_949_21_956/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201712_0_949_21_957/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201801_0_4861_22_4868/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201801_0_4861_22_4869/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201802_0_2074_21_2081/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201802_0_2074_21_2082/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201803_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201803_0_1_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201804_0_689_21_696/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201804_0_689_21_697/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201805_0_1172_21_1179/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201805_0_1172_21_1180/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201806_0_2_1_10/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201806_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201807_0_104_20_111/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201807_0_104_20_112/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201808_0_32_7_39/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201808_0_32_7_40/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201809_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201809_0_1_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201810_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201810_0_1_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201811_0_3_1_10/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201811_0_3_1_11/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201812_0_2_1_10/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201812_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201901_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201901_0_1_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201902_0_2_1_10/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201902_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201903_0_2_1_10/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201903_0_2_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201904_0_20_5_27/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201904_0_20_5_28/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201905_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201905_0_1_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201906_0_1_1_8/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201906_0_1_1_9/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 16:07 201907_0_484_19_491/
drwxr-x---  2 clickhouse clickhouse  4096 Aug  5 18:48 201907_0_484_19_492/
drwxr-x---  2 clickhouse clickhouse  4096 Jul 26 17:43 detached/
-rw-r-----  1 clickhouse clickhouse     1 Jul 26 17:43 format_version.txt

other information:
system.mutations：
│bi  │detail    │ 0000000016  │ DELETE WHERE id < 1e21                   │ 2019-08-05 14:55:40 │ ['197001','201611','201612','201701','201702','201703','201704','201705','201706','201707','201708','201709','201710','201711','201712','201801','201802','201803','201804','201805','201806','201807','201808','201809','201810','201811','201812','201901','201902','201903','201904','201905','201906','201907'] │ [20,25,33,20,19,21,21,19,19,562,117,14,11,33,954,4866,2079,6,694,1177,7,109,37,6,6,8,7,6,7,7,25,6,6,489] │           0 │       1 │                    │ 0000-00-00 00:00:00 │                    │

database:                  bi
table:                      detail
mutation_id:                0000000016
command:                    DELETE WHERE id < 1e21
create_time:                2019-08-05 14:55:40
block_numbers.partition_id: ['197001','201611','201612','201701','201702','201703','201704','201705','201706','201707','201708','201709','201710','201711','201712','201801','201802','201803','201804','201805','201806','201807','201808','201809','201810','201811','201812','201901','201902','201903','201904','201905','201906','201907']
block_numbers.number:       [20,25,33,20,19,21,21,19,19,562,117,14,11,33,954,4866,2079,6,694,1177,7,109,37,6,6,8,7,6,7,7,25,6,6,489]
parts_to_do:                0
is_done:                    1
latest_failed_part:         
latest_fail_time:           0000-00-00 00:00:00
latest_fail_reason:         

system.parts :
partition:                             201702
name:                                  201702_0_14_2_20
active:                                1
marks:                                 0
rows:                                  0
bytes_on_disk:                         5
data_compressed_bytes:                 0
data_uncompressed_bytes:               0
marks_bytes:                           0
modification_time:                     2019-08-05 15:37:42
remove_time:                           0000-00-00 00:00:00
refcount:                              1
min_date:                              0000-00-00
max_date:                              0000-00-00
min_time:                              0000-00-00 00:00:00
max_time:                              0000-00-00 00:00:00
partition_id:                          201702
min_block_number:                      0
max_block_number:                      14
level:                                 2
data_version:                          20
primary_key_bytes_in_memory:           0
primary_key_bytes_in_memory_allocated: 96
is_frozen:                             1
database:                              bi
table:                                 detail
engine:                                ReplicatedMergeTree
path:                                  /Data/clickhouse-server/clickhouse-data/data/bi/detail/201702_0_14_2_20/

The size of the field file in the partition folder is empty,but this files not null to checksums.txt and columns.txt

**Comment by filimonov** [comment]
Please check: 
https://github.com/yandex/ClickHouse/issues/5256
https://github.com/yandex/ClickHouse/issues/3526
https://github.com/yandex/ClickHouse/issues/3388

**Comment by den-crane** [comment]
Not a bug. Expected behavior. Insert deduplication.
