### ISSUE TITLE
Missing past releases Documentation

### ISSUE THREAD

**Issue by YenchangChan** [ClickHouse/ClickHouse#63399]
(you don't have to strictly follow this form)

**Describe the issue**
I'm using clickhouse version `21.8.13.6` on my production environment and I'm having some issues, but when I try to look for the root cause through the system table, some of the fields that are outdated no longer make sense and the official documentation, which is already up to date, is no longer available.
I would like to be able to provide documentation that corresponds to the different versions, as I know this is the practice of many open source docs, such as Logstash.
![image](https://github.com/ClickHouse/ClickHouse/assets/43897067/76b4accb-f0be-491c-9145-8b83e4e8a3c2)

**Comment by Algunenano** [comment]
It might happen in the future. In the meantime, since the documentation is part of the repo, you can checkout whatever tag you want and decide.

In any case, if you have issues when you are 25 releases behind, the recommendation you are going to get is to upgrade
