### ISSUE TITLE
how to download clickhouse  a single stable binary

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/ClickHouse#63393]
in install  [clichouse ](https://clickhouse.com/docs/en/install),  i can know how to install test single stable binary by :
```
curl https://clickhouse.com/ | sh
```

or install by official pre-compiled deb packages:
```
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | sudo gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list
sudo apt-get update
```

but how to download clickhouse  a single stable binary to install in cluster .  for example, i want to install lastest stable version's binary (24.4.1.2088)
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/b8e702db-1658-4e61-828c-8858ce8c175f)

**Comment by rschu1ze** [comment]
I am not sure if I understand your question.

The [install page](https://clickhouse.com/docs/en/install#available-installation-options) includes four different ways to install the latest stable version. You perhaps meant where to get a "standalone" installation script (i.e. an installation not via a package manager). There is no such thing in ClickHouse, the binaries can be run on arbitrary Linux systems. So if you like to get the latest stable version, you can simply do `curl https://clickhouse.com/ | sh` and copy the binaries into your cluster.

**Comment by a819721810** [comment]
> curl https://clickhouse.com/ | sh
thanks for reply , but 
![image](https://github.com/ClickHouse/ClickHouse/assets/10041362/d4216d43-0fe9-4358-b7f1-1a884ca35681)


curl https://clickhouse.com/ | sh  is not latest stable version, is test version, i want latest stable version "standalone" installation  binary

**Comment by rschu1ze** [comment]
These builds are indeed from the `master` development branch, okay.

To get build of specific versions, you could look here: https://github.com/ClickHouse/ClickHouse/releases
