### ISSUE TITLE
Function initCap treats an apostrophe as a word separator

### ISSUE THREAD

**Issue by ivkhokhlachev** [ClickHouse/ClickHouse#63419]
**How to reproduce**
Version 24.2.2, reproduced on the latest 24.4.1 in Clickhouse Playground

Run the query:
`SELECT initCap('miley cyrus'' "mother''s daughter"')`

**Current result**

> Miley Cyrus' "Mother'S Daughter"

**Expected result**

> Miley Cyrus' "Mother's Daughter"

**Comment by den-crane** [comment]
```
psql (15.3 (Debian 15.3-0+deb12u1), server 9.6.24)

psql> SELECT initCap('miley cyrus'' "mother''s daughter"');
             initcap
----------------------------------
 Miley Cyrus' "Mother'S Daughter"
```
