### ISSUE TITLE
Replacing-AggregatingMergeTree?

### ISSUE THREAD

**Issue by lordvidex** [ClickHouse/ClickHouse#63422]
Is there currently a clickhouse table ENGINE that offers aggregation for some columns and deduplication for other columns not in the `ORDER BY` such that it is possible to get sum aggregated values for a column and most recent value for another column after merge?

An example table is shown below:
```sql
CREATE TABLE traffic_stats (
date Date,
user_uuid String,
user_status LowCardinality(String),
events_sum SimpleAggregateFunction(sum, UInt64)
) ENGINE = AggregatingMergeTree
ORDER BY (date, user_uuid);
```

**Ideas**
1. Using `AggregateFunction(argMax(user_status, date), String)` for `user_status` column: This will work for example if the dates are different, but if on the same day, the values are different, the user_status value will not give accurate result.

**Comment by den-crane** [comment]
you can use an additional column `inserted_at DateTime64(9) default now(9)` for AggregateFunction

or you can use `anyLast` (`aggregateFunction(anyLast(user_status)`) it does not guarantee 100% accuracy, but mostly it will be the last value.

**Comment by lordvidex** [comment]
Thanks for answering quickly. Follow up questions:

> you can use an additional column inserted_at DateTime64(9) default now(9) for AggregateFunction:
Does this mean that an `inserted_at` column won't be lost during merge if the field is not in the ORDER BY tuple? I ask because adding `inserted_at` in the ORDER BY tuple will bloat the table size and prevent aggregations anyway.

> you can use anyLast (aggregateFunction(anyLast(user_status)) it does not guarantee 100% accuracy, but mostly it will be the last value.

Thanks, I will fallback to this variant if the first isn't workable.

**Comment by lordvidex** [comment]
For my usecase, this does solves the problem. Thanks. I'll close this as solved.
