### ISSUE TITLE
Clickhouse return database not exist(error code 81)

### ISSUE THREAD

**Issue by livingston0318** [ClickHouse/ClickHouse#63446]
here is the sql I queried,
`WITH
test_sub AS (
       SELECT
       distinct(base3.Id) AS Id
FROM
       test_table_1 AS base3
WHERE base3.Id = 12345678
)
select 
       base2.Name as Name
from 
       test_table_2 as base2
where
       base2.Id global in (test_sub.Id)
limit 10`
And it returns 
`Code: 81. DB::Exception: Database test_sub doesn't exist: While processing Id GLOBAL IN (_data_5036057499189014357_6172205886434892455). (UNKNOWN_DATABASE)`

but if I change the sql to 
`WITH
test_sub AS (
       SELECT
       distinct(base3.Id) AS Id
FROM
       test_table_1 AS base3
WHERE base3.Id = 12345678
)
select 
       base2.Name as Name
from 
       test_table_2 as base2
where
       base2.Id global in (test_sub)
limit 10`
it succeed, I did some google search, didn't get the answer

**Comment by neel-bp** [comment]
we are having the same problem, it only started happening after we updated clickhouse to 24.4.1 revision 54467

**Comment by Algunenano** [comment]
Issues are simpler to investigate if you provide reproducible examples -> https://fiddle.clickhouse.com/

**Comment by neel-bp** [comment]
also just checked this problem is only happening with distributed tables, i tried running the same query on the local table and it is working fine.

**Comment by livingston0318** [comment]
> Issues are simpler to investigate if you provide reproducible examples -> https://fiddle.clickhouse.com/

CREATE TABLE users (uid Int16, name String, age Int16) ENGINE=Memory;

INSERT INTO users VALUES (1231, 'John', 33);
INSERT INTO users VALUES (6666, 'Ksenia', 48);
INSERT INTO users VALUES (8888, 'Alice', 50);

with test AS (
  select uid from users
  where age > 40
)
select 
  uid,
  name,
  age
from 
  users
where 
  uid in (test.uid);

**Comment by livingston0318** [comment]
it can reproduce with the sql I just posted.

**Comment by den-crane** [comment]
@livingston0318 you can use subquery as workaround 

```
with test AS ( select uid from users where age > 40 )
  select uid,name, age
  from users
  where uid in (select uid from test);
```

https://fiddle.clickhouse.com/67c86990-4d3f-400b-ab8b-6ca5cbeb59e7

-------

```
with test AS ( select uid from users where age > 40 )
  select uid,name, age
  from users
  where uid in (test.uid);
```

Such syntax is not supported by other databases, PG, Mysql. It was undefined behaviour that it worked before.
I think it's good that it does not work anymore.
The issue should be closed after adding positive and negative tests.

**Comment by den-crane** [comment]
Ah, I see, it never worked at all. https://fiddle.clickhouse.com/749eb4c7-5b07-4da9-a640-da57e89a2b6e

**Comment by livingston0318** [comment]
@den-crane thanks bro, this issue can be closed.
