### ISSUE TITLE
The dictionary converts the return value to LowCardinality if the parameter is LowCardinality

### ISSUE THREAD

**Issue by handgunman** [ClickHouse/ClickHouse#63458]
In the dictionary the field is of type Int32. 
But if the input of the function is LowCardinality the result will be LowCardinality

Is this a mistake or is it intended that way?

create table t (SKU String, Art Int32) ENGINE = MergeTree() order by SKU;

insert into t values ('12_2',122);

CREATE DICTIONARY t_d
(
    SKU String,
    Art Int32
)
PRIMARY KEY SKU
SOURCE(CLICKHOUSE(QUERY `SELECT SKU, Art FROM t WHERE notEmpty(SKU) LIMIT 1 BY SKU` 
INVALIDATE_QUERY `select max(modification_time) from system.parts where table='t'`))
LAYOUT(HASHED())
LIFETIME(MIN 300 MAX 3000);

SELECT dictGet('t_d','Art','12_2') as a, toTypeName(a) as type;

SELECT dictGet('t_d','Art',toLowCardinality('12_2')) as a, toTypeName(a) as type;

https://fiddle.clickhouse.com/e46cd9fb-61c0-4ab8-8c6a-f8db568a8fae

**Comment by UnamedRus** [comment]
It's "OK"

It's how LowCardinality behave, it apply function on dictionary and return another dictionary:
![image](https://github.com/ClickHouse/ClickHouse/assets/9449405/8541a6b1-523a-4b2a-8001-6aab8d98655d)

**Comment by handgunman** [comment]
But just then an error is thrown about what is not recommended to do LowCardinality(Int32)

**Comment by UnamedRus** [comment]
https://github.com/ClickHouse/ClickHouse/issues/27863

**Comment by handgunman** [comment]
Yes, the same
When I do a view the result is
DB::Exception: Creating columns of type LowCardinality(Int32) is prohibited by default due to expected negative impact on performance. It can be enabled with the "allow_suspicious_low_cardinality_types" setting.. (SUSPICIOUS_TYPE_FOR_LOW_CARDINALITY)

**Comment by handgunman** [comment]
> #27863

finally I do dictGet('dict','field',item::String)
