### ISSUE TITLE
ODBC bridge timeout since 24.4

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#63472]
**Describe what's wrong**

We're using ODBC dictionary. It was working till v24.3. Since v24.4. it gives timeouts.

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

v24.4
PG ODBC

I'm using official docker image:

```dockerfile
ARG CLICKHOUSE_VERSION=24.4

FROM clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        odbc-postgresql \
        && \
    rm -rf /var/lib/apt/lists/*

COPY odbc.ini /etc/odbc.ini

RUN odbcinst -j
RUN cat /etc/odbc.ini
```

```sql
CREATE DICTIONARY IF NOT EXISTS pg__dict
(
    `name` String,
    `id` UUID
)
PRIMARY KEY name_slug
SOURCE(ODBC(CONNECTION_STRING 'DSN=mydns;Database=___tests__cd9c23d1' TABLE 'pgtable'))
LIFETIME(MIN 300 MAX 360)
LAYOUT(COMPLEX_KEY_HASHED())
```

```
select * from pg__dict;
```

**Expected behavior**

ODBC connection successful.

**Error message and/or stacktrace**

```
Elapsed: 115.083 sec.

Received exception from server (version 24.4.1):
Code: 410. DB::Exception: Received from localhost:9000. DB::Exception: BridgeHelper: clickhouse-odbc-bridge is not responding. (EXTERNAL_SERVER_IS_NOT_RESPONDING)
```

**Additional context**

When I repeat the procedure with `ARG CLICKHOUSE_VERSION=24.3` it works as expected.

I guess it has something to do with https://github.com/ClickHouse/ClickHouse/pull/62114

**Comment by nikitamikhaylov** [comment]
Maybe that's because we removed these bridges from the deb package: https://github.com/ClickHouse/ClickHouse/pull/62114

**Comment by simPod** [comment]
Is there a recommended way to install those with official docker image?

**Comment by alexey-milovidov** [comment]
```
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        odbc-postgresql \
```

Add
```
        clickhouse-odbc-bridge odbc-postgresql \
```
