### ISSUE TITLE
clickhouse truncate table  drop table 报错 连接超时

### ISSUE THREAD

**Issue by moxuan12138** [ClickHouse/ClickHouse#63476]
![c067de612d4e8f64e801a14e1ee0203](https://github.com/ClickHouse/ClickHouse/assets/66153678/adaf468e-66d5-4f37-8414-dad1e77ef6a6)
如果并发太多 ，使用truncate table  drop table  就会报 连接超时， 多节点之间同步有问题。

**Comment by Algunenano** [comment]
Update to a supported release

**Comment by moxuan12138** [comment]
那么请问哪个版本支持这种语法呢

**Comment by Algunenano** [comment]
It's not a matter of syntax, it's a matter of support. We won't investigate any issues in unsupported releases.

**Comment by moxuan12138** [comment]
请问哪个clickhouse版本解决了以上问题呢？能推荐一下版本号吗

**Comment by Algunenano** [comment]
Use latest.

Latest build:
```
curl https://clickhouse.com/ | sh
```

For other checkout https://github.com/ClickHouse/ClickHouse/tags

**Comment by moxuan12138** [comment]
你好，我能再问一下，他任务同时执行的太多的话是不是这种场景报错的呢，不是因为truncate的引起的？我看网上说是因为clickhouse 执行ddl语句是同步执行的  难道是这样导致180s超时的吗
