### ISSUE TITLE
Compression is not autodetected from an output file name in clickhouse-local

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#63496]
**Use case**

```
$ clickhouse-local --query "SELECT 1" > test.native
$ clickhouse-local --query "SELECT 1" > test.native.zst
```

The second variant does not produce zstd compressed data.

**Comment by v01dXYZ** [comment]
Hello,
I'm working on this issue . I think I would like to add some code to `Client/ClientBase.cpp` to take care of that. There is already existing code to get the filepath/filename from the file descriptor in `FormatFactor.cpp` (for Linux/MacOS only though). Where should I put this sort of OS generic code ?

**Comment by Avogar** [comment]
Hi! Thank you for working on it!
You can create a new function `std::optional<std::string> tryGetFileNameByFileDescriptor(int fd)` (the code will be almost the same as in `FormatFactory::tryGetFormatFromFileDescriptor`) and place it in a separate file in `src/Common/tryGetFileNameByFileDescriptor.h/cpp`. And then this function can be used both in `FormatFactory::tryGetFormatFromFileDescriptor` and in `ClientBase` for choosing the compression method.

About the implementation, I think we should add new field `CompressionMethod default_output_compression_method` in `ClientBase` class similar to `default_output_format` and set it accordingly to the file name here after we set `default_output_format` (we can use our new function `tryGetFormatFromFileDescriptor`):
https://github.com/ClickHouse/ClickHouse/blob/6247f6a2b0650c093e66d77599bbe34005ce0a56/src/Client/ClientBase.cpp#L755-L762

And then here when we create output buffer we can check the `default_output_compression_method` and create corresponding buffer:
https://github.com/ClickHouse/ClickHouse/blob/6247f6a2b0650c093e66d77599bbe34005ce0a56/src/Client/ClientBase.cpp#L623

It will look smth like:
```c++
}
else if (default_output_compression_method != CompressionMethod::None)
{
    out_file_buf = wrapWriteBufferWithCompressionMethod(out_buf, default_output_compression_method, 3);
}
```

(but I am not 100% sure it will work, maybe something else is needed, need to test).
