### ISSUE TITLE
Error message in clickhouse whih the object storage

### ISSUE THREAD

**Issue by FriskKiddo** [ClickHouse/ClickHouse#63499]
s3 config in xml
`<yandex>
            <storage_configuration>
                <disks>
                    <s3_disk>
                        <type>s3</type>
                        <endpoint>http://xxxxx/CK_CLUSTER_NAME/data/</endpoint>
                        <access_key_id>xxx</access_key_id>
                        <secret_access_key>xxx</secret_access_key>
                        <connect_timeout_ms>40000</connect_timeout_ms>
                        <request_timeout_ms>20000</request_timeout_ms>
                        <metadata_path>/var/lib/clickhouse/s3</metadata_path>
                    </s3_disk>
                </disks>
                <policies>
                    <s3_policy>
                        <volumes>
                            <s3_volume>
                                <disk>s3_disk</disk>
                            </s3_volume>
                        </volumes>
                   </s3_policy>
                </policies>
            </storage_configuration>
        </yandex>`
       
clickhouse digest data by kakfa table, and store data  in object storage(ceph).

the mergetree table ddl is:
CREATE TABLE content_csis_local.csis_ruler_stat_logstore
(
    `msg` String COMMENT 'USER COLUMN',
    `event_rpc_id` String COMMENT 'USER COLUMN',
    `metaq_msg_id` String COMMENT 'USER COLUMN',
    `rt` UInt32 COMMENT 'USER COLUMN',
    `data` String COMMENT 'USER COLUMN',
    `logger` String COMMENT 'USER COLUMN',
    `err_code` String COMMENT 'USER COLUMN',
    `mtee_biz_code` String COMMENT 'USER COLUMN',
    `uuid` String COMMENT 'USER COLUMN',
    `csi_obj_md5` String COMMENT 'USER COLUMN',
    `event_code` String COMMENT 'USER COLUMN',
    `metaq_msg_key` String COMMENT 'USER COLUMN',
    `metaq_msg_delay` UInt32 COMMENT 'USER COLUMN',
    `metaq_msg_tag` String COMMENT 'USER COLUMN',
    `app` String COMMENT 'USER COLUMN',
    `business_name` String COMMENT 'USER COLUMN',
    `trace_id` String COMMENT 'USER COLUMN',
    `src_id` String COMMENT 'USER COLUMN',
    `level` String COMMENT 'USER COLUMN',
    `accepted` String COMMENT 'USER COLUMN',
    `thread` String COMMENT 'USER COLUMN',
    `first_product_name` String COMMENT 'USER COLUMN',
    `version` String COMMENT 'USER COLUMN',
    `data_source` String COMMENT 'USER COLUMN',
    `event_id` String COMMENT 'USER COLUMN',
    `identify_source` String COMMENT 'USER COLUMN',
    `user_id` String COMMENT 'USER COLUMN',
    `v` String COMMENT 'USER COLUMN',
    `msg_type` String COMMENT 'USER COLUMN',
    `data_str` String COMMENT 'USER COLUMN',
    `time` String COMMENT 'USER COLUMN',
    `punish_server` String COMMENT 'USER COLUMN',
    `metaq_topic` String COMMENT 'USER COLUMN',
    `__project__` LowCardinality(String),
    `__dt__` DateTime64(3) CODEC(DoubleDelta, LZ4),
    `__file__` LowCardinality(String),
    `__host__` LowCardinality(String),
    `__level__` LowCardinality(String),
    INDEX idx_msg msg TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_event_rpc_id event_rpc_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_metaq_msg_id metaq_msg_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_data data TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_logger logger TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_err_code err_code TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_mtee_biz_code mtee_biz_code TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_uuid uuid TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_csi_obj_md5 csi_obj_md5 TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_event_code event_code TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_metaq_msg_key metaq_msg_key TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_metaq_msg_tag metaq_msg_tag TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_app app TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_business_name business_name TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_trace_id trace_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_src_id src_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_level level TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_accepted accepted TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_thread thread TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_first_product_name first_product_name TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_version version TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_data_source data_source TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_event_id event_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_identify_source identify_source TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_user_id user_id TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_v v TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_msg_type msg_type TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_data_str data_str TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_time time TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_punish_server punish_server TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_metaq_topic metaq_topic TYPE bloom_filter(0.01) GRANULARITY 1,
    INDEX idx_rt rt TYPE minmax GRANULARITY 1,
    INDEX idx_metaq_msg_delay metaq_msg_delay TYPE minmax GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(__dt__)
ORDER BY __dt__
TTL toDateTime(__dt__) TO VOLUME 's3_volume', toDateTime(__dt__) + toIntervalDay(7)
SETTINGS storage_policy = 's3_policy', ttl_only_drop_parts = 1, merge_with_ttl_timeout = 86400, index_granularity = 8192

The following error log appears frequently：
2024.05.08 14:03:31.599522 [ 622 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {73abf669-452a-4a73-98c2-286e8191558d::20240508_1994_3172_4}: Code: 499. DB::Exception: while reading key: data/pjm/fljgasanlupwwzkirkuskbzbhnwqh, from bucket: ckcsis: (while reading column data): (while reading from part /var/lib/clickhouse/s3/store/73a/73abf669-452a-4a73-98c2-286e8191558d/20240508_2446_2478_2/ in table content_csis_local.csis_ruler_stat_logstore (73abf669-452a-4a73-98c2-286e8191558d) located on disk s3_disk of type s3, from mark 221 with max_rows_to_read = 1819): While executing MergeTreeSequentialSource. (S3_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbcedbb
1. DB::S3Exception::S3Exception(String const&, Aws::S3::S3Errors) @ 0x000000000f9caacd
2. DB::ReadBufferFromS3::sendRequest(unsigned long, unsigned long, std::optional<unsigned long>) const @ 0x000000000f9c9708
3. DB::ReadBufferFromS3::nextImpl() @ 0x000000000f9c6359
4. DB::ReadBufferFromRemoteFSGather::readImpl() @ 0x000000000fa3e190
5. DB::ReadBufferFromRemoteFSGather::nextImpl() @ 0x000000000fa3d858
6. DB::ThreadPoolRemoteFSReader::execute(DB::IAsynchronousReader::Request, bool) @ 0x000000000f8b3c2e
7. std::__packaged_task_func<std::function<std::future<DB::IAsynchronousReader::Result> (DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&&, Priority)> DB::threadPoolCallbackRunner<DB::IAsynchronousReader::Result, DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, String const&)::'lambda'(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&&, Priority)::operator()(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&&, Priority)::'lambda'(), std::allocator<std::function<std::future<DB::IAsynchronousReader::Result> (DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&&, Priority)> DB::threadPoolCallbackRunner<DB::IAsynchronousReader::Result, DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, String const&)::'lambda'(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&&, Priority)::operator()(DB::ThreadPoolRemoteFSReader::submit(DB::IAsynchronousReader::Request)::$_0&&, Priority)::'lambda'()>, DB::IAsynchronousReader::Result ()>::operator()() (.e1ac63d5e1a7b716f3a0f426b500941f) @ 0x000000000f8b5650
8. std::packaged_task<DB::IAsynchronousReader::Result ()>::operator()() @ 0x000000000f8b5821
9. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000cc7b379
10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000cc7ebda
11. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000cc7d9ed
12. ? @ 0x00007f624e2e1609
13. ? @ 0x00007f624e206353
 (version 24.3.2.23 (official build))

**Comment by den-crane** [comment]
Do you use zero replication?

ceph is not supported officially, does it reproduce with AWS S3 or with minio ?

**Comment by FriskKiddo** [comment]
yes, i used MergeTree not ReplicatedMergeTree.

**Comment by alexey-milovidov** [comment]
Object storage is a complex distributed system, and it is expected that it returns errors sometimes. These errors are retried transparently. You should not worry about seeing them in logs.
