### ISSUE TITLE
How to setup inter data center replication for Kubernetes clusters

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#63503]
Private IPs and DNS names of ClickHouse servers inside one Kubernetes cluster are not accessible from another. So how to setup the inter-Kubenetes-cluster replication ?

So far I found that [Submariner](https://submariner.io/) helps to achieve inter-cluster communication via private IPs.

Are there any other choices ?

Thks.

**Comment by UnamedRus** [comment]
BTW, nice article on this topic

https://innovation.ebayinc.com/tech/engineering/ou-online-analytical-processing/

**Comment by alexey-milovidov** [comment]
We don't have the answer to this topic. The easiest way will be to do it without Kubernetes.
