### ISSUE TITLE
window function PARTITION BY does not work when used FINAL

### ISSUE THREAD

**Issue by buqiyong** [ClickHouse/ClickHouse#63553]
SQL:
`SELECT
*
FROM 
(
SELECT
gid,
event_date,
COUNT() OVER (PARTITION BY gid)
FROM
sv_ob_jp.inner_01_gid_login final
)
WHERE gid = '1000353793'
`

you can see the result, a gid have two different results:
![image](https://github.com/ClickHouse/ClickHouse/assets/46669069/9829360b-fef9-4218-988d-8d61676fbea9)

sql without final:
`SELECT
*
FROM 
(
SELECT
gid,
event_date,
COUNT() OVER (PARTITION BY gid)
FROM
sv_ob_jp.inner_01_gid_login
)
WHERE gid = '1000353793'
`

you can see the result, PARTITION BY working fine:
![image](https://github.com/ClickHouse/ClickHouse/assets/46669069/1797aadf-a34b-4fa3-9302-1f3b1cbb0b94)

It should be noted，sv_ob_jp.inner_01_gid_login is a MATERIALIZED VIEW by ReplacingMergeTree

```[tasklist]
### Tasks
```

**Comment by Algunenano** [comment]
Please provide a reproducer (schema, data, queries, CH version tested), not random screenshots.
