### ISSUE TITLE
What are the default values of SQL SECURITY and DEFINER when creating materialized view?

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#63564]
In the [docs](https://clickhouse.com/docs/en/sql-reference/statements/create/view#sql_security) stated:
________________________________________________________________________________
If DEFINER/SQL SECURITY aren't specified, the default values are used:
SQL SECURITY: INVOKER for normal views and **DEFINER for materialized views** ([configurable by settings](https://clickhouse.com/docs/en/operations/settings/settings#default_normal_view_sql_security))
DEFINER: **CURRENT_USER** ([configurable by settings](https://clickhouse.com/docs/en/operations/settings/settings#default_view_definer))
________________________________________________________________________________

So if I create mv with default user without specifying SQL SECURITY and DEFINER:
```sql
CREATE MATERIALIZED VIEW view TO mv_table AS SELECT * FROM table
```
I expect to be able to select from this mv with user that has only `SELECT` privilege on view? But I am not able to do so.
```
DB::Exception: user: Not enough privileges. To execute this query, it's necessary to have the grant SELECT(x) ON default.table. (ACCESS_DENIED)
```
What am I missing?

If I specify one of SQL SECURITY to default or DEFINER to DEFINER, the other one will use default value as stated in docs. And I am able to select from mv with user that has only `SELECT` grant on view.

**Comment by alsugiliazova** [comment]
The privileges in docs table should be corrected: 
_______________________________________________________
alice must have a SELECT grant for the view's source table and an SELECT **_(not INSERT)_** grant for the view's target table.
_______________________________________________________

But I believe it is a known issue.

**Comment by alsugiliazova** [comment]
I changed default_view_definer in users.xml to some other user and tried to create mv. 
```sql
 SELECT name, changed, value from system.settings WHERE name='default_view_definer'
```
```
default_view_definer	1	user_one_4ad9c097_0e06_11ef_9e86_397ee92ffec9
```
```sql
CREATE MATERIALIZED VIEW view_4e6c7f96_0e06_11ef_9e86_397ee92ffec9 TO mv_table_one_4ad9c0b1_0e06_11ef_9e86_397ee92ffec9 SQL SECURITY DEFINER AS SELECT * FROM table_4ad9c0a1_0e06_11ef_9e86_397ee92ffec9
```
```sql
SHOW CREATE TABLE view_4e6c7f96_0e06_11ef_9e86_397ee92ffec9" 
```
```
CREATE MATERIALIZED VIEW default.view_4e6c7f96_0e06_11ef_9e86_397ee92ffec9 TO default.mv_table_one_4ad9c0b1_0e06_11ef_9e86_397ee92ffec9\n(\n    `x` UInt32\n)\nDEFINER = default SQL SECURITY DEFINER\nAS SELECT *\nFROM default.table_4ad9c0a1_0e06_11ef_9e86_397ee92ffec9
```
Default value was changed but wasn't used.

**Comment by alsugiliazova** [comment]
```sql
CREATE VIEW view DEFINER = default AS SELECT * FROM table
```
SQL SECURITY was not specified, I expect it to be INVOKER, but DEFINER was used.

```sql
SHOW CREATE VIEW view
```
```
CREATE VIEW default.view\n(\n    `x` UInt32\n)\nDEFINER = default SQL SECURITY DEFINER\nAS SELECT *\nFROM default.table_one
```

**Comment by pufit** [comment]
> SQL SECURITY was not specified, I expect it to be INVOKER, but DEFINER was used.

If you specify a definer in the CREATE query, the SQL SECURITY DEFINER will be used automatically.

> Default value was changed but wasn't used.

Yes, this is a little bit tricky. Currently, defaults work only if no SQL SECURITY statement is specified. When you create a view with `SQL SECURITY DEFINER` but without any definer specified, it automatically transforms to `DEFINER = CURRENT_USER SQL SECURITY DEFINER` on the client side.

> alice must have a SELECT grant for the view's source table and an SELECT (not INSERT) grant for the view's target table.

Yes, SELECT for selects and INSERT for insets.

**Comment by alsugiliazova** [comment]
@pufit What about the main question in the issue (in case when both DEFINER and SQL SECURITY were not specified). What should I expect then? Will default values (DEFINER for SQL security and CURRENT_USER for definer) be used?

**Comment by pufit** [comment]
> @pufit What about the main question in the issue (in case when both DEFINER and SQL SECURITY were not specified). What should I expect then? Will default values (DEFINER for SQL security and CURRENT_USER for definer) be used?

If no SQL SECURITY or DEFINER sections were specified, the behavior will depend on the `ignore_empty_sql_security_in_create_view_query` setting. Right now, it is `true` by default, so the newly created views without SQL security will behave like they did before. In the next release, we will turn it off by default and will make it obsolete in future releases. If this setting is set to `false`, the defaults are used from `default_normal_view_sql_security`, `default_materialized_view_sql_security`, and `default_view_definer`.

**Comment by alsugiliazova** [comment]
Thank you. Now it is clear for me.
