### ISSUE TITLE
Projections do not work when select used view

### ISSUE THREAD

**Issue by handgunman** [ClickHouse/ClickHouse#63561]
CREATE TABLE t (id Int16, val Int32, dt Date) ENGINE=MergeTree Order by dt;

ALTER TABLE t
ADD PROJECTION prj_group
(
SELECT sum(val) 
GROUP BY dt
);

insert into t values (1,10,'2024-05-01'),(2,20,'2024-05-01'),(3,30,'2024-05-01'),(4,40,'2024-05-01'),(5,50,'2024-05-01');

explain indexes = 1 select sum(val) from t;

create view v as select * from t;

explain indexes = 1 select sum(val) from v group by dt;

https://fiddle.clickhouse.com/720713cd-39b6-402d-a51a-60f3183e965a

**Comment by Algunenano** [comment]
Duplicate  https://github.com/ClickHouse/ClickHouse/issues/32753
