### ISSUE TITLE
Any roadmaps for improving distributed infrastructure?

### ISSUE THREAD

**Issue by yingfeng** [ClickHouse/ClickHouse#6357]
Compared with the excellent performance of Clickhouse on single machine, the distributed infrastructure could be improved as well due to these issues:

### Availability
Although ReplicationMergetree provides the mechanism for high availability, it has some shortcomings: The burden of Zookeeper is too heavy, and could become the bottleneck if the write throughput is high, because too much data is written through ZK. Could such mechanism as replication state machine be used for replica management?

### Rebalance
Clickhouse does not support auto rebalance right now, which makes it inconvenient for cluster's scaling up or scaling down, or fault tolerance, this is not friendly to operations. A simple idea is to have data partition managed by a seperate component to be able to be transfered across nodes automatically, just like Apache Doris, EventQL, or some NewSQL database as TiDB, Cockcroach have done.

### Transactions
Guarantee ACID is unnecessary for OLAP, however, there exist many situations where data durability is required, such as the so called `exactly once computing`. For example, if we need exactly once semantic exist within the ETL job which sinks data to Clickhouse, the transactional API is very useful to `end-to-end exactly once`, working together with such components as Flink or Kafka Transactional API. Similar OLAP solutions as Apache Doris has already supported such issue in its `stream load` feature.

### Resource Isolation
Corresponding feature could be seen at [Doris' site](https://doris.apache.org/).

It seems that if the pros of both Clickhouse and Doris could be combined, then there would be a `perfect` OLAP solution. Does there exist any roadmap for such evolution?

**Comment by filimonov** [comment]
Thank you for the feedback, it's very valuable.

There are plans addressing most of listed problems.
Some of plans are long-term and not very concrete, others (like resource pools) we expect to be delivered still in 2019.

Here is the list of short-term plans: https://github.com/yandex/ClickHouse/issues/4785

More long term - please check the concept: https://clickhouse.yandex/blog/en/concept-cloud-mergetree-tables  which partially covers the problems you mentioned.

**Comment by den-crane** [comment]
And CH needs a Warp drive as well.

**Comment by yingfeng** [comment]
Both Doris and Kudu have implemented a state replication machine based infrastructure to resolve distributed issues---through either Paxos or Raft. The solution of Kudu's might be more valuable since it has provided a Raft concensus library in C++ which has also been used by some other distributed OLTP solutions as [Yugabyte](https://github.com/yugabyte/yugabyte-db) while Doris chooses Java to provide a Paxos replication state machine. Additionally, there are some other standalone production ready Raft solutions, such as [braft](https://github.com/brpc/braft), corresponding multi-raft to be applied to database could be seen in [BaikalDB](https://github.com/baidu/BaikalDB), or [Dragonboat](https://github.com/lni/dragonboat), which itself has already been a production ready multi-raft library with ultra high throughput through highly optimized pipelining and batching technologies. If one of these solution could be used to improve the current ReplicationMergeTree, it could be a substitution for the current infrastructure.

**Comment by yingfeng** [comment]
Our proposal has been raised and tracked in issue [6772](https://github.com/yandex/ClickHouse/issues/6772).

**Comment by arsis1** [comment]
May I ask, the plan described here (https://clickhouse.yandex/blog/en/concept-cloud-mergetree-tables) has some progress ? or just on todo-list ? Current distributed engine is not the one, and we need auto-rebalancing when add node.

**Comment by filimonov** [comment]
AFAIK, no progress for now, issue is in backlog. The story is huge, some other big things need to be finished before taking that.

**Comment by alexey-milovidov** [comment]
Nothing was done in four years - closing.
