### ISSUE TITLE
Segfault with Variant when writing to `ColumnNullable`

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#63572]
Reproducible with
```sql
SELECT x, arrayJoin(['a', NULL, 'b']) AS z
FROM system.one 
ARRAY JOIN [1, NULL, 3] AS x, [(NULL, ''), ['str_1', toNullable(5), 5, 5], (123, 'Hello'), (456, NULL)] AS y 
ORDER BY x ASC, y DESC, z ASC NULLS FIRST 
SETTINGS allow_experimental_variant_type = 1, use_variant_as_common_type = 1;
```

There is also a related TSAN report https://s3.amazonaws.com/clickhouse-test-reports/0/35d96f98f47c29e1694d29850a7ee419f0b24d27/ast_fuzzer__tsan_/stderr.log

It was triggered because there was an attempt to write to global `empty_pod_array` inside `PODArray::push_back`.
`c_end` somehow becomes 1 less than `c_end_of_storage`.

cc @Avogar

**Comment by Avogar** [comment]
According to stacktrace probably it's the same as https://github.com/ClickHouse/ClickHouse/issues/63582, I will check

**Comment by Avogar** [comment]
Yes, it's the same
