### ISSUE TITLE
Confusing error message with dynamic column selection

### ISSUE THREAD

**Issue by strtgbb** [ClickHouse/ClickHouse#63576]
**Describe what's wrong**

The error message references a projection that was not created by the user.

https://fiddle.clickhouse.com/cc99e6e1-9c5d-4d36-99ed-02c3cc65a7dc

**Does it reproduce on the most recent release?**

yes

**Enable crash reporting**

n/a

**How to reproduce**

```sql
SELECT COLUMNS('idontexist') FROM users SETTINGS allow_experimental_analyzer=1;
```

**Expected behavior**

A less confusing error message.

**Error message and/or stacktrace**

```sql
Received exception from server (version 24.4.1):
Code: 51. DB::Exception: Received from localhost:9000. DB::Exception: Empty list of columns in projection. In scope SELECT COLUMNS('idontexist') FROM users SETTINGS allow_experimental_analyzer = 1. (EMPTY_LIST_OF_COLUMNS_QUERIED)
(query: SELECT COLUMNS('idontexist') FROM users SETTINGS allow_experimental_analyzer=1;)
```

**Comment by nikitamikhaylov** [comment]
The error mentions projection from [**relational algebra**](https://en.wikipedia.org/wiki/Projection_(relational_algebra)), not a "data projection" you mean.

**Comment by UnamedRus** [comment]
Do user need to know about relation algebra projections for understanding error messages?
