### ISSUE TITLE
Cannot assign requested address when trying to insert data to the s3 storage

### ISSUE THREAD

**Issue by Carryme-hu** [ClickHouse/ClickHouse#63585]
clickhouse version is 23.8.8.20
config is 
 <storage_configuration>
        <disks>
            <s3>
                <type>s3</type>
                <endpoint>endpoint</endpoint>
                <access_key_id>ak</access_key_id>
                <secret_access_key>sk</secret_access_key>
            </s3>
			<s3_cache>
                <type>cache</type>
                <disk>s3</disk>
                <path>/var/lib/clickhouse/disks/s3_cache/</path>
                <max_size>100Gi</max_size>
            </s3_cache>
        </disks>

        <policies>
            <s3_main>
                <volumes>
                    <main>
                        <disk>s3</disk>
                    </main>
                </volumes>
            </s3_main>
        </policies>
</storage_configuration>

error Net Exception: Cannot assign requested address
S3_ERROR
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c646337 in /usr/bin/clickhouse
1. DB::S3Exception::S3Exception<String const&, String const&, String const&, unsigned long&>(Aws::S3::S3Errors, fmt::v8::basic_format_string<char, fmt::v8::type_identity<String const&>::type, fmt::v8::type_identity<String const&>::type, fmt::v8::type_identity<String const&>::type, fmt::v8::type_identity<unsigned long&>::type>, String const&, String const&, String const&, unsigned long&) @ 0x00000000110848d7 in /usr/bin/clickhouse
2. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::WriteBufferFromS3::makeSinglepartUpload(DB::WriteBufferFromS3::PartData&&)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x0000000011097f84 in /usr/bin/clickhouse
3. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::WriteBufferFromS3::TaskTracker::add(std::function<void ()>&&)::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x000000001109d536 in /usr/bin/clickhouse
4. std::__packaged_task_func<std::function<std::future<void> (std::function<void ()>&&, Priority)> DB::threadPoolCallbackRunner<void, std::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, String const&)::'lambda'(std::function<void ()>&&, Priority)::operator()(std::function<void ()>&&, Priority)::'lambda'(), std::allocator<std::function<std::future<void> (std::function<void ()>&&, Priority)> DB::threadPoolCallbackRunner<void, std::function<void ()>>(ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>&, String const&)::'lambda'(std::function<void ()>&&, Priority)::operator()(std::function<void ()>&&, Priority)::'lambda'()>, void ()>::operator()() @ 0x000000001107207a in /usr/bin/clickhouse
5. std::packaged_task<void ()>::operator()() @ 0x0000000010b3470f in /usr/bin/clickhouse
6. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c7250fe in /usr/bin/clickhouse
7. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c728bbc in /usr/bin/clickhouse
8. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c727404 in /usr/bin/clickhouse
9. ? @ 0x00007fe4cd8a9609 in ?
10. ? @ 0x00007fe4cd7ce163 in ?
 (version 23.8.8.20 (official build))

**Comment by Algunenano** [comment]
Does it fail occasionally or always?

If it's something that happens occasionally you should try upgrading. There were multiple improvements to s3 connections (keepalives and reuse) in more recent versions that might help.

If it's always happening then something's up with your setup. Check that the hostname of the machine can be resolved, DNS is fine, etc.
