### ISSUE TITLE
ClickHouse server exposing user/password for remote_servers in the log

### ISSUE THREAD

**Issue by PhantomPhreak** [ClickHouse/ClickHouse#6358]
There are 'feature' of ClickHouse to make subdirectories for `Distributed` tables, contaning username and password, configured in `remote_servers` section.

Example:
```
<yandex>
        <test>
            <shard>
                <replica>
                    <host>host</host>
                    <port>port</port>
                    <user>username</user>
                    <password>password</password>
                </replica>
            </shard>
        </test>
    </remote_servers>
</yandex>
```
Following directories will be created for Distributed tables
```
<data_path>/data/<database>/<table>/username:password@host:port
```
Here username and password exposed in plaintext.

In some cases (when some data considered as broken for example), ClickHouse server writing following to the logs:
```
<ts> [ 319 ] {} <Error> <db>.Distributed.DirectoryMonitor: Renamed `<data_path>/data/<database>/<table>/username:password@host:port/1321.bin` to `<data_path>/data/<database>/<table>/username:password@host:port/broken/1321.bin`
```
Also, after manual broken data deletion, CH will log something like 
```<data_path>/data/<database>/<table>/username:password@host:port/broken/1321.bin not found```

So, username and password exposed in a logs in plaintext, and can be found by anyone having read permissions for a logs.
Exposing credentials for a user (especially for user having write permissions) in a log it's a security issue.

Is it possible to avoid making directories with username and password, and/or writing username/password to the log?

Thanks

**Comment by filimonov** [comment]
Related: 
https://github.com/yandex/ClickHouse/issues/3311 
https://github.com/yandex/ClickHouse/issues/5527
https://github.com/yandex/ClickHouse/pull/6240

**Comment by PhantomPhreak** [comment]
Any activity here?

**Comment by alexey-milovidov** [comment]
It is wrong that we have credentials in directory name.
Better to put cluster name, shard number and (optional) replica number instead.
It can be automatically unambiguated from current format.

This task is not in progress right now.

**Comment by alexey-milovidov** [comment]
Let's encode it as
```
shard1
```
to send data to any replica of this shard
or
```
shard1_replica1
```
to send data to specific replica of this shard.

**Comment by filimonov** [comment]
> to send data to any replica of specific shard

Corner case here is when new shards added  - shard numbering can be shifted.

**Comment by alexey-milovidov** [comment]
@filimonov Yes, I'm aware of this issue and decided that it's Ok.
If shards were added in the middle, stale data will be sent to another shards. And this is perfectly fine.

**Comment by alexey-milovidov** [comment]
It's not too common to add shards in the middle of the list.
And if it happened, the behaviour is easy understandable and explainable.
