### ISSUE TITLE
Clickhouse 23.12.6.19 randomly turned to readonly

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#63629]
Hi, we are using Clickhouse 23.12.6.19 on a single instance (NO cluster). All of sudden, it turns to readonly and the inserts give error. Restarting the service or the machine doesn’t solve the issue. There is no specific event occurring before it turns to readonly. How can we prevent this, and why is this happening? And how can we restart it in write mode?

2024.05.10 14:00:02.528445 [ 3914 ] {cb8a1a2b-b452-4c68-bcbd-f3191d9101e7} <Error> DynamicQueryHandler: Code: 164. DB::Exception: pttable_staging: Cannot execute query in readonly mode. (READONLY), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c6d4e1b in /usr/bin/clickhouse
1. DB::Exception::Exception<String>(int, FormatStringHelperImpl<std::type_identity<String>::type>, String&&) @ 0x0000000007169fcd in /usr/bin/clickhouse
2. bool DB::ContextAccess::checkAccessImplHelper<true, false, std::basic_string_view<char, std::char_traits<char>>, std::basic_string_view<char, std::char_traits<char>>, std::vector<String, std::allocator<String>>>(DB::AccessFlags, std::basic_string_view<char, std::char_traits<char>> const&, std::basic_string_view<char, std::char_traits<char>> const&, std::vector<String, std::allocator<String>> const&) const @ 0x00000000101459bb in /usr/bin/clickhouse
3. DB::Context::checkAccess(DB::AccessFlags const&, DB::StorageID const&, std::vector<String, std::allocator<String>> const&) const @ 0x0000000010947f35 in /usr/bin/clickhouse
4. DB::InterpreterInsertQuery::execute() @ 0x00000000112d8206 in /usr/bin/clickhouse
5. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x000000001174c682 in /usr/bin/clickhouse
6. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&)>) @ 0x000000001174f16a in /usr/bin/clickhouse
7. DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) @ 0x000000001263e88d in /usr/bin/clickhouse
8. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) @ 0x00000000126436b6 in /usr/bin/clickhouse
9. DB::HTTPServerConnection::run() @ 0x00000000126be512 in /usr/bin/clickhouse
10. Poco::Net::TCPServerConnection::start() @ 0x000000001511f532 in /usr/bin/clickhouse
11. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015120331 in /usr/bin/clickhouse
12. Poco::PooledThread::run() @ 0x0000000015217a87 in /usr/bin/clickhouse
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001521607c in /usr/bin/clickhouse
14. ? @ 0x00007f75f7e24812 in ?
15. ? @ 0x00007f75f7dc4450 in ?
 (version 23.12.6.19 (official build))

**Comment by alexey-milovidov** [comment]
HTTP GET requests only allow readonly queries, such as SELECT, while POST requests allow any queries.
Also, the readonly mode could be forced with an URL parameter `readonly=1`.

I doubt that it happened randomly. More likely, some of your requests use the GET method, and some use POST.

**Comment by enzorevo** [comment]
> HTTP GET requests only allow readonly queries, such as SELECT, while POST requests allow any queries. Also, the readonly mode could be forced with an URL parameter `readonly=1`.
> 
> I doubt that it happened randomly. More likely, some of your requests use the GET method, and some use POST.

Hi, note that this has been running correctly for months without changing anything. There is no such GET/POST issue. The queries have been executed exactly as always, but the tables are giving problems for inserts suddenly.

**Comment by alexey-milovidov** [comment]
It is possible that a table is in a readonly mode. It happens on temporary connection loss with Keeper and it is resolved automatically as soon as the connection is re-established.

But in these cases, you will get another error message, something around "Table is in a read-only mode."

**Comment by den-crane** [comment]
>We do not have Keeper / cluster setup

@enzorevo this exact error "Cannot execute query in readonly mode" is related to Replicated tables. So you do have zookeeper or keeper

please share

```
select count() from system.replicas where is_readonly;

select * from system.replicas where is_readonly limit 1 format Vertical;

**Comment by alexey-milovidov** [comment]
@den-crane, according to the provided error message and stack trace, the error does not correspond to replication, but corresponds to table grants, user's readonly setting, or running a query over HTTP GET.

@enzorevo, there is a chance that it is related to some non-anticipated changes. For example, someone revoked a grant from a table. Or re-configured your client app. Or updated it without noticing...

**Comment by enzorevo** [comment]
@den-crane those queries give 0 and an empty result set.

@alexey-milovidov how can i check for that specific permission grant?

**Comment by den-crane** [comment]
@enzorevo Yes, my mistake, it's not related to Replicated tables, I looked into the wrong place.

**Comment by enzorevo** [comment]
@alexey-milovidov these are the grants:

:) SHOW GRANTS FOR 'db_staging'@'%';

SHOW GRANTS FOR db_staging

Query id: 9c630bd8-50f1-4eb4-8b46-792aba40ead6

┌─GRANTS FOR db_staging───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ GRANT CREATE TEMPORARY TABLE, FILE ON *.* TO db_staging                                                                                                                                                                                             │
│ GRANT SHOW, SELECT, INSERT, ALTER, CREATE DATABASE, CREATE TABLE, CREATE VIEW, CREATE DICTIONARY, DROP DATABASE, DROP TABLE, DROP VIEW, DROP DICTIONARY, UNDROP TABLE, TRUNCATE, OPTIMIZE, BACKUP, CREATE ROW POLICY, ALTER ROW POLICY, DROP ROW POLICY, SHOW ROW POLICIES, SYSTEM MERGES, SYSTEM TTL MERGES, SYSTEM FETCHES, SYSTEM MOVES, SYSTEM PULLING REPLICATION LOG, SYSTEM CLEANUP, SYSTEM VIEWS, SYSTEM SENDS, SYSTEM REPLICATION QUEUES, SYSTEM DROP REPLICA, SYSTEM SYNC REPLICA, SYSTEM RESTART REPLICA, SYSTEM RESTORE REPLICA, SYSTEM WAIT LOADING PARTS, SYSTEM SYNC DATABASE REPLICA, SYSTEM FLUSH DISTRIBUTED, dictGet ON db_staging.* TO db_staging │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.001 sec.

**Comment by den-crane** [comment]
it's not related to grants, with grants you will get `DB::Exception: foo: Not enough privileges.`
it's related to the readonly setting (profile). https://clickhouse.com/docs/en/operations/settings/permissions-for-queries#readonly

Check `/etc/clickhouse-server` 

```
    <profiles>
 ... 
           <readonly>2</readonly>
```

**Comment by enzorevo** [comment]
@den-crane this is users.xml (standard):

`<clickhouse>
    

    
    <profiles>
        
        <default>
        </default>

        
        <readonly>
            <readonly>1</readonly>
        </readonly>
    </profiles>

    
    <users>
        
        <default>
            
            <password></password>

            
            <networks>
                <ip>::/0</ip>
            </networks>

            
            <profile>default</profile>

            
            <quota>default</quota>

            
            <access_management>1</access_management>

            
            <named_collection_control>1</named_collection_control>

            
            
        </default>
    </users>

    
    <quotas>
        
        <default>
            
            <interval>
                
                <duration>3600</duration>

                
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>
                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>
</clickhouse> `

for the queries:

`clickhouse-db-net.db.net :) show profiles;


SHOW SETTINGS PROFILES

Query id: cbe31263-14a1-4067-9ca9-dc37ebfc18b0

┌─name─────┐
│ default  │
│ readonly │
└──────────┘

2 rows in set. Elapsed: 0.001 sec. 

clickhouse-db-net.db.net :) show create profiles;



SHOW CREATE SETTINGS PROFILES

Query id: 0de6f376-7e6f-4a1d-9e8b-b2bd19cdf0ec

┌─CREATE SETTINGS PROFILES────────────────────────────────────────────────────────────────┐
│ CREATE SETTINGS PROFILE default SETTINGS log_queries = false, log_query_threads = false │
│ CREATE SETTINGS PROFILE readonly SETTINGS readonly = 1                                  │
└─────────────────────────────────────────────────────────────────────────────────────────┘

2 rows in set. Elapsed: 0.001 sec. 

clickhouse-db-net..net :)  `

And our user is in the default profile. So how was this setting changed at runtime without having touched anything? And how does this stay like this even after rebooting?

**Comment by den-crane** [comment]
Check using this user and clickhouse-client  --user ... --password ...  & `create table t (a Int64) Engine=Memory`

**Comment by enzorevo** [comment]
> Check using this user and clickhouse-client --user ... --password ... & `create table t (a Int64) Engine=Memory`

It works, and I can also insert into that table some data.

**Comment by den-crane** [comment]
> > Check using this user and clickhouse-client --user ... --password ... & `create table t (a Int64) Engine=Memory`
> 
> It works, and I can also insert into that table some data.

Then the only explanation is GET instead of POST.

**Comment by den-crane** [comment]
Ah, and also check `system.query_log` it has more information. At least http_method & Settings.

**Comment by enzorevo** [comment]
> > > Check using this user and clickhouse-client --user ... --password ... & `create table t (a Int64) Engine=Memory`
> > 
> > 
> > It works, and I can also insert into that table some data.
> 
> Then the only explanation is HTTP GET instead of POST.

How can this happen? We use the main official PHP client, and have a job that runs since months always doing the same insert query repeatedly.
We didn’t change anything… that’s what scares me.

**Comment by alexey-milovidov** [comment]
It is likely that something was changed in the configuration of your servers or client applications, but unnoticed.
