### ISSUE TITLE
`02362_part_log_merge_algorithm` is flaky

### ISSUE THREAD

**Issue by mstetsyuk** [ClickHouse/ClickHouse#63633]
`02362_part_log_merge_algorithm` is flaky: [one](https://s3.amazonaws.com/clickhouse-test-reports/0/1b43c58489acffdb85b58cd4d4cdde037656ffbd/stateless_tests__tsan__%5B1_5%5D.html), [two](https://s3.amazonaws.com/clickhouse-test-reports/0/8ed245677d447c0e55a7a9fa84739aa4b670db78/stateless_tests__debug__[1_5].html), [three](https://s3.amazonaws.com/clickhouse-test-reports/0/78af18ac87e58dd7e81b6161f5e114d8fa34ef67/stateless_tests__debug__[1_5].html), [four](https://s3.amazonaws.com/clickhouse-test-reports/0/3ac5853fe83aba193da4f994414fcb5294f56647/stateless_tests__tsan__s3_storage__[1_5].html).

After two `INSERT`s followed by an `OPTIMIZE`, the test expects the part log to only have the following events:
```
NewPart
NewPart
MergeParts
```

However, because the test has a race condition with [`ReplicatedMergeTreeCleanupThread`](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp#L142) removing stale parts, the part log also includes `RemovePart` events.

The test can be fixed by adding `WHERE event_type IN ('NewPart', 'MergeParts')` to filter out stale parts removals (as well as any other potential background events). Alternatively, we can do `WHERE event_type != 'RemovePart'` to only filter out removals, and still fail if other background events happen.

**Comment by tavplubix** [comment]
Well done @mstetsyuk, thanks! However, one thing is not clear:

> However, because the test has a race condition with [ReplicatedMergeTreeCleanupThread](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/ReplicatedMergeTreeCleanupThread.cpp#L142) removing stale parts, the part log also includes RemovePart events. 

There's an `old_parts_lifetime` setting (8 minutes by default) which delays the removal of stale parts. How is the race condition possible if the test execution time is about 30-40 seconds, and it's much less than 8 minutes? Do we have a bug that causes premature removal of data parts?

**Comment by mstetsyuk** [comment]
> There's an `old_parts_lifetime` setting (8 minutes by default) which delays the removal of stale parts. How is the race condition possible if the test execution time is about 30-40 seconds, and it's much less than 8 minutes?

The value of `old_parts_lifetime` is [randomized](https://github.com/ClickHouse/ClickHouse/blob/master/tests/clickhouse-test#L911). In fact, in all the examples that I listed, `old_parts_lifetime` is set to 10, making it possible for the race condition to manifest itself.
