### ISSUE TITLE
Antlr g4 file insertStmt cant parser SQL  correctly.

### ISSUE THREAD

**Issue by zzyReal666** [ClickHouse/ClickHouse#63657]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

rule `insertStmt` and `dataClause` end of 'VALUES',This will not parse the inserted data correctly,example:
<img width="1470" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/34822229/a9e6aefd-be0d-4939-8a2f-ee039471926d">

![image](https://github.com/ClickHouse/ClickHouse/assets/34822229/0ed74adb-e959-4861-bf3b-277b89a67db9)

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by den-crane** [comment]
Antlr g4 is not supported by Clickhouse core team. It's not used by Clickhouse itself. 
It just a file stored in the github repo. You can make a pull request to fix it.

**Comment by Algunenano** [comment]
What Denny says. This file is kept for example purposes, and in case somebody from the community want to expend and improve it, but it's not used directly in the server
