### ISSUE TITLE
Clickhouse remote table function returns incomplete results

### ISSUE THREAD

**Issue by MSalehG** [ClickHouse/ClickHouse#63660]
I have two distinct clusters of Clickhouse. Let's say cluster "ca" and "cb".
I have a table of logs in cb as follows:

CREATE TABLE tmp_dev.logs on cluster cb
(
    `column_a` String,
    `column_b` UInt64,
    `column_c` LowCardinality(String),
    `updated_at` DateTime,
    `created_date` Date
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{cluster}/tmp_dev/logs', '{replica}', updated_at)
PARTITION BY toYYYYMM(created_date)
PRIMARY KEY (column_a)
ORDER BY (column_a, column_b) 

and also a view on it  (also in cb) as follows:
CREATE VIEW tmp_dev.logs_view  on cluster cb
(
    `column_a` String,
    `column_b` UInt64,
    `column_c` LowCardinality(String),
    `updated_at` DateTime,
    `created_date` Date
) AS
SELECT *
FROM tmp_dev.logs
FINAL

Last but not least I have a view in ca on which uses a remote table function to query the data of tmp_dev.logs_view view in cb. The view  DDL (in ca) is as follows:

CREATE VIEW tmp_dev.logs_view  on cluster ca
(
    `column_a` String,
    `column_b` UInt64,
    `column_c` LowCardinality(String),
    `updated_at` DateTime,
    `created_date` Date
) AS
SELECT *
FROM remote('ip:9000', 'tmp_dev.logs_view', 'remote_user', 'password').

The issue is I am running a query on the view in ca to see how many records I have per created_date. The query being:
SELECT count(*), created_date 
FROM  tmp_dev.logs_view 
GROUP BY created_date
ORDER BY created_date desc;

This gives me an incomplete result:
![image](https://github.com/ClickHouse/ClickHouse/assets/48171981/4d455feb-5252-4c7d-a1b6-cff016bd2c46)

And also each time I run the query I get a different result.
(This is weird but always the sum of the counts returned are less than or equal the number of 2 granules which would be 16384)

Wheres when I define my view in ca as:
CREATE VIEW tmp_dev.logs_view  on cluster ca
(
    `column_a` String,
    `column_b` UInt64,
    `column_c` LowCardinality(String),
    `updated_at` DateTime,
    `created_date` Date
) AS
SELECT *
FROM (SELECT * FROM 
remote('ip:9000', 'tmp_dev.logs_view', 'remote_user', 'password')) remote_view

when I run the aggregate query I get a complete result as:
![image](https://github.com/ClickHouse/ClickHouse/assets/48171981/ffbf5d50-bb65-4d5b-ac7d-e9fbf336b67b)

The version for cb is 24.1.8.22 and the version for ca is 22.3.15.33.

Where does this behavior come from

**Comment by den-crane** [comment]
Please share `select name,value from system.settings where changed`

**Comment by MSalehG** [comment]
This is the result for ca:
![image](https://github.com/ClickHouse/ClickHouse/assets/48171981/2e814cb4-08d3-4a62-9ba0-e904bc50a484)

And this is for cb:
![image](https://github.com/ClickHouse/ClickHouse/assets/48171981/3a097643-43c3-4da3-9cd8-b88498506a94)

**Comment by den-crane** [comment]
It's because Dbeaver messes with your settings. It sets `max_result_rows=200, result_overflow_mode=break`
You need to update Dbeaver and remove 200, set fetch_size to 0.

<img width="925" alt="Screenshot 2024-05-11 at 1 56 59 PM" src="https://github.com/ClickHouse/ClickHouse/assets/19737682/1d429403-09f6-40f3-9a7c-38432e2cd76c">

**Comment by MSalehG** [comment]
Thanks a lot the issue is resolved
