### ISSUE TITLE
Add what database a query occurred on in the query_log

### ISSUE THREAD

**Issue by alexs131** [ClickHouse/ClickHouse#6367]
Hello, I am trying to use the query_log to get some metrics about queries that occurred on a particular database. However, the query_log doesn't contain this information. Parsing it out of the query seems the only way to get this information but fails when no database is specified. Thanks.

**Comment by filimonov** [comment]
What about queries across few databases, like 
```
select ... from db1.table1 left join db2.table2 left join db3.table3 where value in (select * from db4.table4)
```

**Comment by alexey-milovidov** [comment]
We can add info about default database at the time of query execution.

**Comment by amosbird** [comment]
Closed in https://github.com/ClickHouse/ClickHouse/pull/12652
