### ISSUE TITLE
XZ

### ISSUE THREAD

**Issue by natl-set** [ClickHouse/ClickHouse#63680]
As you may know xz suffers from the supply chain attack, ClickHouse seems to use xz as well as part of the build. However, xz submodule seems to link to https://github.com/xz-mirror/xz where the mirror itself has been archived since 2023 and it seems to include some checkins from the attackers. I wonder whether we should switch to a different mirror?

This link seems to be the up-to-date version of xz: https://github.com/tukaani-project/xz/releases

**Comment by nikitamikhaylov** [comment]
Please read this: https://github.com/ClickHouse/ClickHouse/issues/62112
