### ISSUE TITLE
Expose `SimpleMergeSelector` settings via `MergeTreeSettings` 

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#63686]
SimpleMergeSelector is an algorithm which ClickHouse use to choose parts for merges. This algorithm is not trivial and has multiple parameters (settings): https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/SimpleMergeSelector.h#L91-L153. These parameters are carefully selected to fit 99.99% of possible ingestion workload and have balance between write amplification and SELECT queries performance. However there are still some possibilities when very experienced users may decide to tune them. Also it can be useful for experiments. 

So the idea is to expose these settings as MergeTreeSettings. We definitely should have clear description near each setting, that they are "expert-level" and may completely mess merges assignment and lead to "too many parts" or crazy write amplification.

**Comment by Algunenano** [comment]
Old related issue: https://github.com/ClickHouse/ClickHouse/issues/34813

**Comment by Algunenano** [comment]
This was done over multiple PRs. Check `merge_selector_*` MergeTree settings

**Comment by azat** [comment]
I doubt that it could ever have been anyone's intention :)
