### ISSUE TITLE
Support retention policy for general MergeTree engine

### ISSUE THREAD

**Issue by BoseSean** [ClickHouse/ClickHouse#6369]
Though it is presented as a general RDBMS, ClickHouse looks very promising for timeseries data. Do you have plans to support Retention policy for other storage engines,  which is very necessary for a timeseries? I know it is well supported for GraphiteMergeTree, however, it would provide more possibilities if support for other engines is provided.

**Comment by den-crane** [comment]
TTL for Columns and Tables -- Determines the lifetime of values.
https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#table_engine-mergetree-ttl
