### ISSUE TITLE
Does chproxy of clickhouse support vector data ingestion?

### ISSUE THREAD

**Issue by hueiyuan** [ClickHouse/ClickHouse#63737]
Hi, all

Now we apply [vector](https://vector.dev/docs/) to ingest data to clickhouse. And we found that corresponding clickhouse sink does not support [chproxy](https://github.com/ContentSquare/chproxy) so that can not ingest data to clickhouse.

But we have confirmed our chproxy setting is fine, another way can write data to clickhouse with it. But if we specify chproxy endpoint on vector setting, which can not write data to clickhouse and shows 400 bad requests.

So we want to check whether do not support chproxy on vector? thank you.

**Comment by nikitamikhaylov** [comment]
As it is written in the **chproxy** README: 
> It is an open-source community project and not an official ClickHouse project.

It is not maintained by us and we have no influence on that project. Please fill an issue in its repo and ask the question there.
