### ISSUE TITLE
Does ClickHouse support local node execution switching?

### ISSUE THREAD

**Issue by 0xfei** [ClickHouse/ClickHouse#63736]
Does ClickHouse support local node execution switching  on distributed query execution? This would prevent a slow query on one node from slowing down the entire query, just like `use_hedged_requests`

**Comment by nikitamikhaylov** [comment]
No. ClickHouse can't change the number of nodes dynamically during query execution. It is either fully local of fully distributed with the number of nodes based on the statically defined cluster topology.
