### ISSUE TITLE
Using MV for filtering data with SELECT from context table

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#6373]
```sql
CREATE MATERIALIZED VIEW filtered ENGINE = Memory
AS
SELECT *
FROM all
WHERE id IN (SELECT id FROM desired_ids)
```

I tested this query and it works, it filters data inserted to `all` table using `desired_ids` table. 

I intend to have `desired_ids`'s engine as VersionedCollapsingMergeTree so I can update it without dropping.

The `filtered` table would be typical MergeTree

Are there any caveats with this approach? Thanks!

**Comment by blinkov** [comment]
@simPod, do you have any further questions?
