### ISSUE TITLE
generateULID() is too slow because ulid library is initialized every time the function is called.

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#63795]
Clickhouse latest (24.4.1 and all version before)

https://github.com/ClickHouse/ClickHouse/blob/master/src/Functions/generateULID.cpp#L65

```c++
    ColumnPtr executeImpl(const ColumnsWithTypeAndName & /*arguments*/, const DataTypePtr &, size_t input_rows_count) const override
    {
        auto col_res = ColumnFixedString::create(ULID_LENGTH);
        auto & vec_res = col_res->getChars();

        vec_res.resize(input_rows_count * ULID_LENGTH);

        ulid_generator generator;
        ulid_generator_init(&generator, 0); // <==============================

        for (size_t offset = 0, size = vec_res.size(); offset < size; offset += ULID_LENGTH)
            ulid_generate(&generator, reinterpret_cast<char *>(&vec_res[offset]));

        return col_res;
    }
```

Fix proposal:
1. initialize the library once (something like singleton in CH process, initialized on demand). Under global mutex to prevent parallel initialization.
2. generate ULIDs under the same mutex. ULID generation involves state change, so it's not thread safe.

I did not do benchmarks, but I'm sure that even with a lock, a massive insert() will be faster than current implementation that calls `SYS_getrandom()` every time + some math around.

If introducing a lock is a performance problem, then I would advise something like percpu structure (like a pool of initialized ulid generators).

P.S.
I would always pass `ULID_PARANOID` instead of zero in `ulid_generator_init()` call

**Comment by Algunenano** [comment]
> Fix proposal:

> initialize the library once (something like singleton in CH process, initialized on demand). Under global mutex to prevent parallel initialization.
> generate ULIDs under the same mutex. ULID generation involves state change, so it's not thread safe.

I'd expect this to have the opposite results. Instead of having N threads generating ULID's you would have only one at a time.

> I did not do benchmarks, but I'm sure that even with a lock, a massive insert() will be faster than current implementation that calls SYS_getrandom() every time + some math around.

Please do and let's analyze the results in a multi-threaded environment. Do you really expect a call to random() and a small loop to be that expensive per block?

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/pull/63577#discussion_r1597491928
https://github.com/ClickHouse/ClickHouse/pull/62852/files#diff-1437cd250b6dfcc59c09582025ad6c0b37a8d0bfd35da3bfe5f426e8d2e8893dR220

**Comment by Algunenano** [comment]
Here is the perf of running generateUUID **on a single thread** (`Select generateULID() from numbers(1000000000) format Null`).

```
+   97.51%    13.09%  QueryPullP  clickhouse  [.] ulid_generate
+   75.83%    75.82%  QueryPullP  clickhouse  [.] ulid_encode
     0.07%     0.07%  QueryPullP  clickhouse  [.] ulid_generator_init
```


0.07% of the time is spent in ulid_generator_init. 97.51% in ulid_generate.

**Comment by socketpair** [comment]
I confirm this.

```SQL
CREATE TABLE syslog.qwe
(
    `id` FixedString(26) DEFAULT generateULID() CODEC(ZSTD(3)),
    `x` Int32
)
ENGINE = MergeTree
ORDER BY id;

insert into qwe(x) select number from numbers(10000);
```

`strace -ff -p $(pidof clickhouse-server) -e getrandom`  shows only few calls to getrandom. It means `ulid_generator_init()` is not called every time ULID is generated.

**Comment by Algunenano** [comment]
That's what the `input_rows_count` argument is for

**Comment by den-crane** [comment]
@socketpair `arrayMap( x-> generateULID(x), range(1000))`

https://github.com/ClickHouse/ulid-c/blob/c433b6783cf918b8f996dacd014cb2b68c7de419/src/ulid.c#L261-L263

**Comment by socketpair** [comment]
@den-crane I did not catch what you want to ephasize, but getting corse time on 64-bit platforms is exceptionally fast. And in fact, it's performance is enough (for me).

**Comment by Algunenano** [comment]
> This calls getrandom() 8 times.
> select generateULID(1), generateULID(2),generateULID(3), generateULID(4), generateULID(5), generateULID(6), generateULID(7), generateULID(8);

The explanation is that in this case the argument is used to prevent [the functions to be eliminated](https://clickhouse.com/docs/en/sql-reference/functions#common-subexpression-elimination), so they are treated as 8 different functions. 

> This calls getrandom() 4 times.
> select groupArray(generateULID(number)) from numbers(1000) format Null

I'm curious about why. I would expect one call to getrandom() to happen in the dry-run check (when CH internally checks the function output types and so on) and one per each block (1 call to ulid_generator_init, 1000 calls to ulid_generate). So in this case just 2 getrandom() calls. I'm probably missing something

One way you could do to check the impact of using blocks is to run something like `select groupArray(generateULID(number)) from numbers(1000) format Null SETTINGS max_block_size=1`). This will generate blocks of just 1 row, with each calling execute() (so 1 call to ulid_generator_init + 1 call to ulid_generate).
