### ISSUE TITLE
ReplacingMergeTree Indexes ignored when FINAL is in query

### ISSUE THREAD

**Issue by tvorogme** [ClickHouse/ClickHouse#63820]
**Describe the unexpected behaviour**

I'm using `ReplacingMergeTree` with several indexes.

```
CREATE TABLE test 
  (a Int32, b Int64, c Int128) 
ENGINE=ReplacingMergeTree()
ORDER BY a;

ALTER TABLE test ADD INDEX test_index b TYPE minmax GRANULARITY 5;
INSERT into test VALUES (1,2,3);
ALTER TABLE test MATERIALIZE INDEX test_index;
```

However, when I `SELECT` results with `FINAL` indexes ignored:

```
explain indexes=1 select * from test final WHERE b = 1;

Expression ((Project names + Projection))
  Filter ((WHERE + Change column names to column identifiers))
    ReadFromMergeTree (default.test)
    Indexes:
      PrimaryKey
        Condition: true
        Parts: 3/3
        Granules: 3/3
```

If I remove `FINAL` from queries indexes are used and data query fast:

```
explain indexes=1 select b from test WHERE b = 1;

Expression ((Project names + Projection))
  Filter ((WHERE + Change column names to column identifiers))
    ReadFromMergeTree (default.test)
    Indexes:
      PrimaryKey
        Condition: true
        Parts: 3/3
        Granules: 3/3
      Skip
        Name: test_index
        Description: minmax GRANULARITY 5
        Parts: 1/3
        Granules: 1/3
```

**How to reproduce**

Fiddle: https://fiddle.clickhouse.com/d4930d09-abb9-45f3-8e1f-2c2807f87005

* Which ClickHouse server version to use

`24.4`

**Expected behavior**
Query with `FINAL` use indexes and works fast.

---

If this is by design, it will be cool to provide documentation on this and show some examples how to query records with indexes fast and not use `FINAL`.

**Comment by nickitat** [comment]
pls read about setting `use_skip_indexes_if_final`
