### ISSUE TITLE
bug to update date_time_input_format from basic to best_effort

### ISSUE THREAD

**Issue by pushpenderjindal** [ClickHouse/ClickHouse#63830]
****Describe what's wrong**
I have edit users.xml directly and update date_time_input_format to best_effort 
post restarting clickhouse service changes get refelected as checked by login clickhouse cli**.

`**clickhouse :) SELECT name, value, changed FROM system.settings WHERE name LIKE 'date_time%'

SELECT
    name,
    value,
    changed
FROM system.settings
WHERE name LIKE 'date_time%'

Query id: 8acd3e3b-7f9d-43e8-ba0f-43bf3671f09c

   ┌─name────────────────────────┬─value───────┬─changed─┐
1. │ date_time_input_format      │ best_effort │       1 │
2. │ date_time_output_format     │ simple      │       0 │
3. │ date_time_overflow_behavior │ ignore      │       0 │
   └─────────────────────────────┴─────────────┴─────────┘`**

**post that inserted the query below and getting execption.**

`clickhouse :) INSERT INTO newtable3 FORMAT JSONEachRow {"file":"/example/path.log","timestamp":"2024-05-14T06:24:40.682561117Z","kubernetes_container_id":"example_id","stream":"stdout"}

INSERT INTO newtable3 FORMAT JSONEachRow

Query id: 1d92d3d0-3a8f-4bcb-b233-82536368b548

Ok.
Exception on client:
Code: 27. DB::Exception: Cannot parse input: expected '"' before: 'Z","kubernetes_container_id":"example_id","stream":"stdout"}': (while reading the value of key timestamp): (at row 1)
: While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)`

**but in other hand if i use SET command then insert query was working.**

`clickhouse :) SET date_time_input_format = 'best_effort'

SET date_time_input_format = 'best_effort'

Query id: 9bcf274d-df7d-45b7-a3d2-033bf5eec56b

Ok.

0 rows in set. Elapsed: 0.001 sec.

clickhouse :) INSERT INTO newtable3 FORMAT JSONEachRow {"file":"/example/path.log","timestamp":"2024-05-14T06:24:40.682561117Z","kubernetes_container_id":"example_id","stream":"stdout"}

INSERT INTO newtable3 FORMAT JSONEachRow

Query id: d86e31d2-f32e-4c0c-95a7-eee57a56c31f

Ok.

1 row in set. Elapsed: 0.003 sec.`

**attaching my table DDL and  result for both the cases.**

`CREATE TABLE kube_stg.newtable3
(
    `file` String,
    `timestamp` DateTime64(3),
    `kubernetes_container_id` LowCardinality(String),
    `kubernetes_container_image` LowCardinality(String),
    `kubernetes_container_name` LowCardinality(String),
    `kubernetes_namespace_labels` Map(LowCardinality(String), String),
    `kubernetes_pod_annotations` Map(LowCardinality(String), String),
    `kubernetes_pod_ip` IPv4,
    `kubernetes_pod_ips` Array(IPv4),
    `kubernetes_pod_labels` Map(LowCardinality(String), String),
    `kubernetes_pod_name` LowCardinality(String),
    `kubernetes_pod_namespace` LowCardinality(String),
    `kubernetes_pod_node_name` LowCardinality(String),
    `kubernetes_pod_owner` LowCardinality(String),
    `kubernetes_pod_uid` LowCardinality(String),
    `message` String,
    `source_type` LowCardinality(String),
    `stream` Enum8('stdout' = 1, 'stderr' = 2)
)
ENGINE = MergeTree
ORDER BY (kubernetes_container_name, timestamp)`

`clickhouse :) SELECT name, value, changed FROM system.settings WHERE name LIKE 'date_time%'

SELECT
    name,
    value,
    changed
FROM system.settings
WHERE name LIKE 'date_time%'

Query id: a79e9470-74a4-426a-bac7-57236f4411a7

   ┌─name────────────────────────┬─value───────┬─changed─┐
1. │ date_time_input_format      │ best_effort │       1 │
2. │ date_time_output_format     │ simple      │       0 │
3. │ date_time_overflow_behavior │ ignore      │       0 │
   └─────────────────────────────┴─────────────┴─────────┘

3 rows in set. Elapsed: 0.002 sec. Processed 1.01 thousand rows, 222.85 KB (590.47 thousand rows/s., 130.28 MB/s.)
Peak memory usage: 0.00 B.

clickhouse :) INSERT INTO newtable3 FORMAT JSONEachRow {"file":"/example/path.log","timestamp":"2024-05-14T06:24:40.682561117Z","kubernetes_container_id":"example_id","stream":"stdout"}

INSERT INTO newtable3 FORMAT JSONEachRow

Query id: 1d92d3d0-3a8f-4bcb-b233-82536368b548

Ok.
Exception on client:
Code: 27. DB::Exception: Cannot parse input: expected '"' before: 'Z","kubernetes_container_id":"example_id","stream":"stdout"}': (while reading the value of key timestamp): (at row 1)
: While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)

clickhouse :) SET date_time_input_format = 'best_effort'

SET date_time_input_format = 'best_effort'

Query id: 9bcf274d-df7d-45b7-a3d2-033bf5eec56b

Ok.

0 rows in set. Elapsed: 0.001 sec.

clickhouse :) INSERT INTO newtable3 FORMAT JSONEachRow {"file":"/example/path.log","timestamp":"2024-05-14T06:24:40.682561117Z","kubernetes_container_id":"example_id","stream":"stdout"}

INSERT INTO newtable3 FORMAT JSONEachRow

Query id: d86e31d2-f32e-4c0c-95a7-eee57a56c31f

Ok.

1 row in set. Elapsed: 0.003 sec.`

**Comment by Algunenano** [comment]
This is expected. The client is doing the parsing and has different settings.

Related https://github.com/ClickHouse/ClickHouse/issues/56976

**Comment by pushpenderjindal** [comment]
what the solutions in that case. how can we fixed that?

**Comment by pushpenderjindal** [comment]
its working if i remove Z from time stamp timestamp":"2024-05-14T06:24:40.682561117**Z**

**Comment by Algunenano** [comment]
https://clickhouse.com/docs/en/interfaces/cli#interfaces_cli_configuration

**Comment by den-crane** [comment]
Actually it should work for vector.dev
Because vector works over HTTP and profile setting date_time_input_format will be applied.

Anyway there is various methods to set this setting in vector.dev config.
You can simply use `endpoint = "http://localhost:8123?date_time_input_format=best_effort"`
OR  `encoding.timestamp_format = "unix"` https://vector.dev/docs/reference/configuration/sinks/websocket/#encoding.timestamp_format
