### ISSUE TITLE
Wrong result in left join

### ISSUE THREAD

**Issue by fhh-coder** [ClickHouse/ClickHouse#63929]
When I execute the following SQL statement, I expect the result of field b to be null, but the result is 0.
```sql
select l.*, r.* from 
( select 'a' as a ) l
left join 
( select '1' as a, 1 as b ) r 
on l.a = r.a;
```
![image](https://github.com/ClickHouse/ClickHouse/assets/57700093/3d8a5cd2-4e97-4746-a4f7-dfe6a95efce1)

My version is 23.8.2.1

![image](https://github.com/ClickHouse/ClickHouse/assets/57700093/619f1e68-296f-4f10-9841-75955d2c3fc0)

**Comment by kitaisreal** [comment]
By default, ClickHouse does not make non joined columns for LEFT, RIGHT, FULL join Nullable, so it uses default values for non joined rows.
This behaviour can be controlled with setting https://clickhouse.com/docs/en/operations/settings/settings#join_use_nulls.
```
select l.*, r.* from
( select 'a' as a ) l
left join
( select '1' as a, 1 as b ) r
on l.a = r.a SETTINGS join_use_nulls = 1;

   ┌─a─┬─r.a──┬────b─┐
1. │ a │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │
   └───┴──────┴──────┘
```

**Comment by fhh-coder** [comment]
get it!
