### ISSUE TITLE
query with view is slower

### ISSUE THREAD

**Issue by jesse-triplewhale** [ClickHouse/ClickHouse#63931]
Version: 24.4.1.2088
Self-hosted

We are seeing a significant (~10x) performance degradation when running a certain query using a view, vs. running the equivalent query without the view (using a subquery instead). The query plan shows a difference. Below is an example with a simplified schema that shows a similar difference in query plan to what we're seeing.

I've also attached actual flame graphs from our 2 queries

```
> create table test (date Date, n UInt16) engine = MergeTree
order by
    date;
```

```
> create view test_view as
select
    *
from
    test
where
    date >= '1971-01-01';
```

```
> explain
select
    count(*)
from
    test_view
where
    n > 10000;
==============================
Expression ((Project names + Projection))
  Aggregating
    Expression (Before GROUP BY)
      Filter ((WHERE + (Change column names to column identifiers + (Convert VIEW subquery result to VIEW table structure + (Materialize constants after VIEW subquery + (Project names + Projection))))))
        Expression
          ReadFromMergeTree (default.test)
```

```
> explain
select
    count(*)
from
    (
        select
            *
        from
            test
        where
            date >= '1971-01-01'
    )
where
     n > 10000 FORMAT TSV;
==============================
Expression ((Project names + Projection))
  Aggregating
    Expression (Before GROUP BY)
      Filter ((WHERE + (Change column names to column identifiers + (Project names + Projection))))
        Expression
          ReadFromMergeTree (default.test)
```
View:
![flamegraph view cpu](https://github.com/ClickHouse/ClickHouse/assets/123306247/5b094072-70e7-422a-9ab0-5028a9af69aa)

Subquery:
![flamegraph subquery cpu](https://github.com/ClickHouse/ClickHouse/assets/123306247/9554707a-8ac6-4efe-927e-8ca7e9bcc923)

**Comment by den-crane** [comment]
by design https://github.com/ClickHouse/ClickHouse/issues/32753#issuecomment-993670877

**Comment by UnamedRus** [comment]
Which ClickHouse version

**Comment by jesse-triplewhale** [comment]
> Which ClickHouse version

24.4.1.2088 self-hosted - adding to the original message as well

**Comment by nickitat** [comment]
check if this is the same as #62594

**Comment by nickitat** [comment]
pls reopen if it is not the case
