### ISSUE TITLE
cross-version query : Not found column ip in block

### ISSUE THREAD

**Issue by amudong** [ClickHouse/ClickHouse#63940]
Hello, we are encountering some cross-version query issues.

query node version : 24.1.5.6  / 24.3.2.23
data node version:  24.1.5.6  / 24.3.2.23 / 20.3.18.10
The distributed table test.test243_241_all contains two versions in the data cluster, namely 24.3 and 24.1.
![image](https://github.com/ClickHouse/ClickHouse/assets/40730519/dd0ec717-77a9-4b37-b194-68d08aba9d03)

case1:
query node  version: 24.1.5.6  or  24.3.2.23   sql:
```
select ip,count() from test.test243_241_all
where timestamp > now()-25*3600
group by ip
limit 10
```
or
```
select ip,count() from test.test243_203_all
where timestamp > now()-25*3600
group by ip
limit 10
```

got error:
`500: { “meta”: [ { “name”: “ip”, “type”: “String” }, { “name”: “count()“, “type”: “UInt64" } ], “data”: [ ], “rows”: 0, “exception”: “Code: 10. DB::Exception: Not found column ip in block. There are only columns: __table1.ip, count(): While executing Remote. (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.1.5.6 (official build))” }
`
case2:
query node  version: 24.1.5.6   sql:
```
select ip,count() from test.test203_241_all
where timestamp > now()-25*3600
group by ip limit 10
```
success.

case3:
`select count() from test.test243_241_all where timestamp > now()-25*3600 limit 1`
success.

May I ask why 24.3 and 24.1 are incompatible during group by query? How to solve this problem? Ultimately we hope that 24.3 and 20.3 can be query compatible, because 24.1 and 20.3 can do it.

**Comment by amudong** [comment]
CREATE TABLE test.test
(
    `timestamp` DateTime,
    `x` Int64,
    `xx` String,
    `xxx` String,
    `xxx` String,
    `ip` String
)
ENGINE = ReplicatedMergeTree(‘/clickhouse/tables/{shard}/test’, ‘{replica}’)
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp)

**Comment by Algunenano** [comment]
24.1 and 24.3 have different default value for `allow_experimental_analyzer` (and they don't work well with one another). Try setting it in the query explicitly to either 0 or 1.

**Comment by amudong** [comment]
@Algunenano settings allow_experimental_analyzer = 0 works.

**Comment by Algunenano** [comment]
> settings allow_experimental_analyzer = 0 works.

Then it's the expected behaviour. The new analyzer has some necessary differences in how they deal with block headers (simplifying: column names) which generates some incompatibilities.

For this case the solution would be to explicitly add aliases to all involved columns, in other cases an upgrade might be necessary (once the old analyzer is removed)
