### ISSUE TITLE
Unexpected exception when using final modifier with non MergeTree table

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#63960]
https://fiddle.clickhouse.com/2f3e3b06-468c-43d2-abc9-d92dbc990d05
```sql
CREATE TABLE users (uid Int16, name String, age Int16) ENGINE=Log;

CREATE TABLE IF NOT EXISTS distributed_table as users ENGINE = Distributed(default, currentDatabase(), users);

insert into distributed_table (age) values (1), (2), (3);

set final=1;
select count() from users;
select count() from distributed_table;
```
```
3

Received exception from server (version 24.3.3):
Code: 181. DB::Exception: Received from localhost:9000. DB::Exception: Storage Log doesn't support FINAL. (ILLEGAL_FINAL)
(query: select count() from distributed_table;)
```
Exception looks really misleading to me, I can actually use FINAL with log storage.  Exception only appears when analyzer is on. 
Seems like FINAL should be ignored when it is not applicable. 

I know that FINAL modifier can be used only for a SELECT from ReplacingMergeTree, SummingMergeTree, AggregatingMergeTree, CollapsingMergeTree and VersionedCollapsingMergeTree tables.

**Comment by melvynator** [comment]
Given it does not reproduce without the Analyzer:

https://fiddle.clickhouse.com/0264258e-207a-4793-b1d8-41fed7826d7f

I added the analyzer label @KochetovNicolai
