### ISSUE TITLE
Freebsd + Mysql compiling error

### ISSUE THREAD

**Issue by iamsens** [ClickHouse/ClickHouse#64004]
**FreeBSD**

**cmake version 3.28.3**

**Ninja version 1.11.1**

**clang 1.11.1**

**Full cmake and/or ninja output**

`
cmake -S . -B build -DPARALLEL_COMPILE_JOBS=50 -DENABLE_BCRYPT=OFF -DENABLE_LDAP=OFF -DENABLE_MYSQL=ON && cmake --build build --target clickhouse

  [0/2] Re-checking globbed directories...
[3740/9629] Building C object contrib/mariadb-connector-c-cmake/CMakeFiles/_mariadbclient.dir/__/mariadb-connector-c/plugins/pvio/pvio_socket.c.o
FAILED: contrib/mariadb-connector-c-cmake/CMakeFiles/_mariadbclient.dir/__/mariadb-connector-c/plugins/pvio/pvio_socket.c.o 
/usr/local/bin/ccache /usr/bin/cc -DHAVE_OPENSSL -DHAVE_TLS -DLIBICONV_PLUG -DMARIADB_MACHINE_TYPE=\"amd64\" -DMARIADB_SYSTEM_TYPE=\"FreeBSD\" -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/usr/work/git/ClickHouse/build/contrib/mariadb-connector-c-cmake/include-private -isystem /usr/work/git/ClickHouse/build/contrib/mariadb-connector-c-cmake/include-public -isystem /usr/work/git/ClickHouse/contrib/mariadb-connector-c/include -isystem /usr/work/git/ClickHouse/contrib/mariadb-connector-c/libmariadb -isystem /usr/work/git/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /usr/work/git/ClickHouse/contrib/libunwind/include -isystem /usr/work/git/ClickHouse/contrib/zlib-ng -isystem /usr/work/git/ClickHouse/build/contrib/zlib-ng-cmake -isystem /usr/work/git/ClickHouse/contrib/openssl-cmake/linux_x86_64/include -isystem /usr/work/git/ClickHouse/contrib/openssl/include -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/usr/work/git/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -w -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3 -g  -std=gnu11   -D OS_FREEBSD -D HAVE_COMPRESS -D LIBMARIADB -D THREAD -Werror -Wno-deprecated-declarations -Wno-poison-system-directories -MD -MT contrib/mariadb-connector-c-cmake/CMakeFiles/_mariadbclient.dir/__/mariadb-connector-c/plugins/pvio/pvio_socket.c.o -MF contrib/mariadb-connector-c-cmake/CMakeFiles/_mariadbclient.dir/__/mariadb-connector-c/plugins/pvio/pvio_socket.c.o.d -o contrib/mariadb-connector-c-cmake/CMakeFiles/_mariadbclient.dir/__/mariadb-connector-c/plugins/pvio/pvio_socket.c.o -c /usr/work/git/ClickHouse/contrib/mariadb-connector-c/plugins/pvio/pvio_socket.c
In file included from /usr/work/git/ClickHouse/contrib/mariadb-connector-c/plugins/pvio/pvio_socket.c:27:
/usr/work/git/ClickHouse/contrib/mariadb-connector-c/include/ma_global.h:202:10: fatal error: 'alloca.h' file not found
  202 | #include <alloca.h>
      |          ^~~~~~~~~~
1 error generated.
[3780/9629] Building CXX object contrib/grpc-cmake/CMakeFiles/grpc++.dir/__/grpc/src/cpp/server/external_connection_acceptor_impl.cc.o^C
ninja: build stopped: interrupted by user.
`

if  comment line 202 in file /usr/work/git/ClickHouse/contrib/mariadb-connector-c/include/ma_global.h
#include <alloca.h>

everyting works fine

**Comment by wxybear** [comment]
This is may because of this line in contrib/mariadb-connector-c-cmake/CMakeLists.txt
> set(HAVE_ALLOCA_H 1)

The original usage is
> CHECK_INCLUDE_FILES (alloca.h HAVE_ALLOCA_H)

I haven't a Freebsd dev machine to test whether this is the real cause. :)

**Comment by iamsens** [comment]
thank you @Algunenano 
everytihin OK

`uname -a
FreeBSD clickhouse2 13.3-RELEASE FreeBSD 13.3-RELEASE releng/13.3-n257428-80d2b634ddf0 GENERIC amd64


setenv CC clang17
setenv CC clang17

git clone https://github.com/ClickHouse/ClickHouse.git
git submodule update --init


diff --git a/contrib/mariadb-connector-c-cmake/CMakeLists.txt b/contrib/mariadb-connector-c-cmake/CMakeLists.txt
index 4257828890f..9840009b628 100644
--- a/contrib/mariadb-connector-c-cmake/CMakeLists.txt
+++ b/contrib/mariadb-connector-c-cmake/CMakeLists.txt
@@ -50,7 +50,11 @@ if(NOT MARIADB_UNIX_ADDR)
   set(MARIADB_UNIX_ADDR "/tmp/mysql.sock")
 endif()

-set(HAVE_ALLOCA_H 1)
+if (OS_FREEBSD)
+  set(HAVE_ALLOCA_H 0)
+else()
+  set(HAVE_ALLOCA_H 1)
+endif()
 set(HAVE_ARPA_INET_H 1)
 set(HAVE_DLFCN_H 1)
 set(HAVE_FCNTL_H 1)


cmake -S . -B build \
 -DPARALLEL_COMPILE_JOBS=56 \
 -DENABLE_BCRYPT=OFF \
 -DENABLE_MYSQL=ON \
 -DENABLE_CASSANDRA=OFF \
 -DENABLE_LDAP=OFF \
 -DENABLE_ROCKSDB=OFF \
 -DENABLE_BLAKE3=OFF \
 -DENABLE_SSH=OFF \
 -DENABLE_KAFKA=OFF \
 -DENABLE_PROTOBUF=OFF \
 -DENABLE_GRPC=OFF \
 -DENABLE_KRB5=OFF \
 -DENABLE_SQLITE=OFF \
 -DENABLE_TESTS=OFF

cmake --build build --target clickhouse


build/programs/clickhouse -V
ClickHouse local version 24.9.1.1.`
