### ISSUE TITLE
ClickHouse Zookeeper API automatically optimize `multi` to `mutiRead`

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#64021]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**

`ZooKeeper::multi` implementation:

```
void ZooKeeper::multi(
    std::span<const RequestPtr> requests,
    MultiCallback callback)
{
    ZooKeeperMultiRequest request(requests, default_acls);

    if (request.getOpNum() == OpNum::MultiRead && !isFeatureEnabled(KeeperFeatureFlag::MULTI_READ))
            throw Exception::fromMessage(Error::ZBADARGUMENTS, "MultiRead request type cannot be used because it's not supported by the server");

    RequestInfo request_info;
    request_info.request = std::make_shared<ZooKeeperMultiRequest>(std::move(request));
    request_info.callback = [callback](const Response & response) { callback(dynamic_cast<const MultiResponse &>(response)); };

    pushRequest(std::move(request_info));
    ProfileEvents::increment(ProfileEvents::ZooKeeperMulti);
}
```

So if requests only contain `READ`, `getOpNum()` will return `OpNum::MultiRead` and this calls may fail on Zookeeper. However, this is a generic API and should work regardless of underlying Zookeeper type.

May be we should add a flag to ZooKeeperMultiRequest so `getOpNum()` only return `MultiRead` if `isFeatureEnabled(KeeperFeatureFlag::MULTI_READ) == true`.

@antonio2368 wdyt?

**Comment by antonio2368** [comment]
If you try to use multiRead with ZooKeeper, it will not work in any case.
What should we return for `isFeatureEnabled(KeeperFeatureFlag::MULTI_READ) == false`?

**Comment by canhld94** [comment]
> If you try to use multiRead with ZooKeeper, it will not work in any case.
> What should we return for `isFeatureEnabled(KeeperFeatureFlag::MULTI_READ) == false`?

So you mean we can have `multi` with ZooKeeper, but if all operations in the requests are READ then ZooKeeper will not work?

I saw `multi` is used in many places for replicated merge tree, and it should work with both ZooKeeper and Keeper.

**Comment by antonio2368** [comment]
@canhld94 yes, but multi is used with Write requests only in Replicated merge tree and all features available.
If someone uses `multi` with READ requests without checking if it's supported, it's a bug.
A generic options are function overloads accepting vector of paths, e.g. `get(std::vector<std::string> paths)` which will correctly fallback to separate requests if MultiRead is not supported.

**Comment by canhld94** [comment]
> @canhld94 yes, but multi is used with Write requests only in ReplicatedMergeTree and all features available.
> If someone uses `multi` with READ requests without checking if it's supported, it's a bug.
> A generic options are function overloads accepting vector of paths, e.g. `get(std::vector<std::string> paths)` which will correctly fallback to separate requests if MultiRead is not supported.

I see, thanks for explaining!
