### ISSUE TITLE
All connection tries failed. There is no table DEFAULT.test_local

### ISSUE THREAD

**Issue by qietingfengling** [ClickHouse/ClickHouse#6405]
我在一台服务器上使用两个clickhouse实例。使用9000和9001端口；监听的host都是配置了<listen_host>0.0.0.0</listen_host>，metrika文件如下：

```xml
<clickhouse_remote_servers>
    <cluster_one>
        <shard>
            <internal_replication>true</internal_replication>
            <weight>1</weight>
            <replica>
                <host>db1</host>
                <port>9000</port>
            </replica>
            <replica>
                <host>db2</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <internal_replication>true</internal_replication>
            <weight>1</weight>
            <replica>
                <host>db1</host>
                <port>9001</port>
            </replica>
            <replica>
                <host>db2</host>
                <port>9001</port>
            </replica>
        </shard>
    </cluster_one >
</clickhouse_remote_servers>
```
clusters表如下：

|  cluster   | shard_num | shard_weight  | replica_num  | host_name   | port | is_local   | user |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  |
| cluster_one  | 1 | 1  | 1 | db1  | 9000 | 0  | default |
| cluster_one  | 1 | 1  | 2 | db2  | 9000 | 0  | default |
| cluster_one  | 2 | 1  | 1 | db1  | 9001 | 1  | default |
| cluster_one | 2 | 1  | 2 | db2  | 9001 | 1  | default |
| test_cluster_two_shards_localhost | 1 | 1  | 1 | 127.0.0.1  | 9000 | 0  | default |
| test_cluster_two_shards_localhost | 2 | 1  | 1 | 127.0.0.1  | 9000 | 0  | default |
| test_shard_localhost  | 1 | 1  | 1 | 127.0.0.1  | 9000 | 0  | default |
| test_shard_localhost_secure  | 1 | 1  | 1 | 127.0.0.1  | 9440 | 0  | default |
| test_unavailable_shard | 1 | 1  | 1 | 127.0.0.1  | 9000 | 0  | default |
| test_unavailable_shard  | 2 | 1  | 1 | 127.0.0.1  | 1 | 0  | default |

Then I built the table as follows:
CREATE TABLE default.test_local (
	date Date,
	timestamp UInt64
) ENGINE = ReplicatedMergeTree('/clickhouse/replica_{replica_group}/default/test_local', '{replica}’) PARTITION BY toYYYYMMDD(date) ORDER BY (timestamp)  TTL date + INTERVAL 1 HOUR;

CREATE TABLE default.test (
	date Date,
	timestamp UInt64,
) ENGINE = Distributed(cluster_one, default, test_local, rand());

Finally I received the following error：

 select * from default.test

SELECT *
FROM default.test

→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.11.5):
Code: 279. DB::Exception: Received from localhost:9001. DB::NetException. DB::NetException: All connection tries failed. Log: 

There is no table DEFAULT.test_local on server: db2:9000
There is no table DEFAULT.test_local on server: db1:9000

**Comment by filimonov** [comment]
> There is no table DEFAULT.test_local on server: db2:9000

Are you sure you have such a table there?

**Comment by filimonov** [comment]
Also it's quite strange that you have DEFAULT in capital letters. ClickHouse is case-sensitive.

**Comment by 4ertus2** [comment]
Try to check default_database in your config files. It most probable than it was chenged to ```DEFAULT```.

**Comment by qietingfengling** [comment]
yes ,the DEFAULT database ,I use my database not this problem

**Comment by blinkov** [comment]
@qietingfengling, do you have any further questions?
