### ISSUE TITLE
Windows file path json extract fail

### ISSUE THREAD

**Issue by huuns** [ClickHouse/ClickHouse#64119]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

I have installed 24.4.1.2088 new release version.

> You have to provide the following information whenever possible.

**Describe what's wrong**
WITH '{ "action_type": "DETECT", "bit_contain_mng": "UNKNOWN", "bit_contain_prvc": "CONTENTS", "bit_data_type": "PRIVACY", "client_time": {"$date": "2024-05-17T06:44:00.803Z"}, "computer_name": "DESKTOP-K9GQJGV", "data_uuid": "7090d67a-9a2b-4b02-8864-946ea5bcd616-WINDOWS", "department": "", "detail_leakage": { }, "detail_log": { "prvc_ptn_cnt": "", "prvc_total_cnt": 30 }, "drive_type": "FIXED", "drm_type": "NONE", "file_name": "경고.txt", "file_path": "C:\\Users\\김자영\\Desktop", "ip": "192.168.189.198", "leakage_type": "PRINTER_DETECT", "leakage_user": "ahn", "login_id": "ahn", "mac": "00-0c-29-c6-e6-f0", "node_id": 2674, "process": "Notepad.exe", "process_type": "ETC", "rating": "WARNING", "tz_offset": 9, "user_name": "" }' AS data

SELECT JSONExtractString(data, 'file_path')
 
Query id: e5048081-6378-43dd-ab7e-bd7fb7564d70
 
   ┌─JSONExtractString(data, 'file_path')─┐

1. │                                      │

   └──────────────────────────────────────┘

WITH '{ "action_type": "DETECT", "bit_contain_mng": "UNKNOWN", "bit_contain_prvc": "CONTENTS", "bit_data_type": "PRIVACY", "client_time": {"$date": "2024-05-17T06:44:00.803Z"}, "computer_name": "DESKTOP-K9GQJGV", "data_uuid": "7090d67a-9a2b-4b02-8864-946ea5bcd616-WINDOWS", "department": "", "detail_leakage": { }, "detail_log": { "prvc_ptn_cnt": "", "prvc_total_cnt": 30 }, "drive_type": "FIXED", "drm_type": "NONE", "file_name": "경고.txt", "file_path": "C:\\Users\\김자영\\Desktop", "ip": "192.168.189.198", "leakage_type": "PRINTER_DETECT", "leakage_user": "ahn", "login_id": "ahn", "mac": "00-0c-29-c6-e6-f0", "node_id": 2674, "process": "Notepad.exe", "process_type": "ETC", "rating": "WARNING", "tz_offset": 9, "user_name": "" }' AS data

SELECT JSONExtractString(data, 'action_type')

SETTINGS input_format_json_throw_on_bad_escape_sequence = 0
 
Query id: 53ed4d78-878b-4f91-8593-562a3c117089
 
   ┌─JSONExtractString(data, 'action_type')─┐

1. │                                        │

   └────────────────────────────────────────┘

When there is an escape character in the JSON like "file_path": "C:\Users\김자영\Desktop", the entire JSON fails to parse, not just the file_path. This issue causes all data extraction to fail with both JSONExtractString and JSON_VALUE. Disabling input_format_json_throw_on_bad_escape_sequence does not resolve the issue either. The JSON only parses correctly if backslashes are escaped with four backslashes (\\). I have confirmed that this issue persists in the latest version, and it can be easily reproduced.

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by alexey-milovidov** [comment]
Windows path can contain backslashes. Example: `C:\SYSTEM32\WINDOWS.DLL`
If you put it into JSON, it requires escaping. Example: `{"path":"C:\\SYSTEM32\\WINDOWS.DLL"}`
If you put this JSON into a string literal, it requires escaping. Example: `SELECT '{"path":"C:\\\\SYSTEM32\\\\WINDOWS.DLL"}'`
You can also use PostgreSQL-style heredoc literals for strings, which don't need escaping. Example: `SELECT $${"path":"C:\\SYSTEM32\\WINDOWS.DLL"}$$`
