### ISSUE TITLE
Getting cannot read all data having too many marks in file.

### ISSUE THREAD

**Issue by jaddu123** [ClickHouse/ClickHouse#64115]
Getting this error, what can be the possible reason for this:

SQL Error [33] [07000]: Code: 33. DB::Exception: Too many marks in file payload%2Ecompany%2Edomain%2Egeo_domain%2Ecreated_at.cmrk2, marks expected 5 (bytes size 120): (while reading column payload): (while reading from part /datadir2/store/2ce/2ce0da9e-dee7-4ec6-9f93-f1060e9a680f/all_367294_367294_6231/ in table test_db.log_events (2ce0da9e-dee7-4ec6-9f93-f1060e9a680f) located on disk default2 of type local, from mark 0 with max_rows_to_read = 6444): While executing MergeTreeThread. (CANNOT_READ_ALL_DATA) (version 23.7.4.5 (official build))

**Comment by den-crane** [comment]
23.7 is out of support. You should upgrade to a supported version: https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease

**Comment by den-crane** [comment]
Do you have skip (secondary) indexes https://github.com/ClickHouse/ClickHouse/issues/52433 ?

v23.7.6.111-stable.md:* Fix recalculation of skip indexes and projections in `ALTER DELETE` queries [#52530](https://github.com/ClickHouse/ClickHouse/pull/52530) ([Anton Popov](https://github.com/CurtizJ)).
v23.8.1.2992-lts.md:* Fix recalculation of skip indexes and projections in `ALTER DELETE` queries [#52530](https://github.com/ClickHouse/ClickHouse/pull/52530) ([Anton Popov](https://github.com/CurtizJ)).

**Comment by jaddu123** [comment]
I don't have any secondary index.

This is my create table syntax:

CREATE TABLE test_db.log_events
(
    `id` UUID DEFAULT generateUUIDv4(),
    `created_at` Nullable(DateTime) CODEC(DoubleDelta, ZSTD(1)),
    `updated_at` Nullable(DateTime) CODEC(DoubleDelta, ZSTD(1)),
    `version` UInt32 CODEC(Delta(4), ZSTD(1)),
    `payload` Object('json')
)
ENGINE = MergeTree
ORDER BY tuple()
SETTINGS index_granularity = 8192

**Comment by den-crane** [comment]
it's because of `payload Object('json')`

`Object('json')` is experimental is not supported and obsolete.

https://clickhouse.com/docs/en/sql-reference/data-types/json **The JSON data type is an obsolete feature. Do not use it. **
