### ISSUE TITLE
dynamic table name assignment

### ISSUE THREAD

**Issue by abhijat-github** [ClickHouse/ClickHouse#64129]
**feature** - dynamic assignment of table name

I understand we have a way to use variable for entire object name . 
For example :
_SET param_db_temp = 'db_temp';
SET param_it = 'mytable_first';
select * from {db_temp : Identifier}.{it: Identifier}_

**Describe the solution you'd like**
> I am wondering if we can solve the below two problems to achieve the same result : 

**Problem 1**
_SET param_db_temp = 'db_temp';
SET param_it = 'mytable';
SET param_var = 'first';
select * from {db_temp : Identifier}.{it: Identifier}_{var: Identifier}_

**Problem 2**
_SET param_db_temp = 'db_temp';
SET param_var = 'first';
select * from {db_temp : Identifier}.my_table_{var: Identifier}_

**Describe alternatives you've considered**

> So far I have been not found an alternative.

**Additional context**

> This feature will allow users to invoke the same function from multiple places and the interim tables created by the function wont overlap with each other .

**Comment by alexey-milovidov** [comment]
Making expressions with identifiers, such as concatenation, is not supported.

**Comment by alexey-milovidov** [comment]
This is a valid feature request, but I have to close it because there is no clear and good way of implementing it.
