### ISSUE TITLE
Hive odbc driver

### ISSUE THREAD

**Issue by frankegoesdown** [ClickHouse/ClickHouse#6412]
After udpdated to CH 19.11.4.24 from 18.x version 

CH raise exception when I use query through odbc
```
 Code: 86, e.displayText() = DB::Exception: Received error from remote server /identifier_quote?connection_string=DSN%3DHWX_SSL. HTTP status code: 500 Internal Server Error, body: Error getting identifier quote style from ODBC 'Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Connection attempt failed: Connection:Not applicable
Server:HWX_SSL
===========================
ODBC Diagnostic record #1:
===========================
SQLSTATE = HY000
Native Error Code = 11560
[Cloudera][ODBC] (11560) Unable to locate SQLGetPrivateProfileString function.
```

It telegram channel Denny Crane said that is because CH request call for discover quotes `"` or ```

**Comment by alexey-milovidov** [comment]
> It telegram channel Denny Crane said that is because CH request call for discover quotes " or ```

That's right. And HIVE driver returned "not applicable". Probably it means that we should send queries without quoting of identifiers. That's quite easy to do.

**Comment by alexey-milovidov** [comment]
PS. I remember, that Hive has multiple ODBC drivers with different levels of quality.

**Comment by frankegoesdown** [comment]
@alexey-milovidov I tried with Cloudera Hive ODBC driver: https://downloads.cloudera.com/connectors/hive_odbc_2.6.1.1001/Linux/ClouderaHiveODBC-2.6.1.1001-1.x86_64.rpm

and Mapr driver http://package.mapr.com/tools/MapR-ODBC/MapR_Hive/MapRHive_odbc_2.6.1.1001/ 

In Mapr documentation they says: 
https://mapr.com/docs/52/Hive/Hive-ODBC-Connector.html
```
Quoted Identifiers: When quoting identifiers, HiveQL uses back quotes (`), while SQL uses double quotes ("). Even when a driver reports the back quote as the quote character, some applications still generate double-quoted identifiers.
```
But CH raised same error

**Comment by alexey-milovidov** [comment]
@kssenii It's very easy to fix - just catch an exception about unsupported method and return that identifiers should be double quotes.
