### ISSUE TITLE
Views or dictionaries should not count towards AttachedTable events

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#64137]
Currently we warn if a server has too many tables (`The number of attached tables is more than 5000`).

The default limit is a recommendation based on the resource usage that tables would have in the system, which is some kind of obscure value but it's much better than not having anything.

The problem is that we are counting everything as a table. For example:

```
SELECT
FROM system.metrics
WHERE name = 'AttachedTable'

   ┌─metric────────┬─value─┬─description─────────────────────────────────────────┐
1. │ AttachedTable │  5646 │ Active table, used by current and upcoming SELECTs. │
   └───────────────┴───────┴─────────────────────────────────────────────────────┘

SELECT
    engine,
    count()
FROM system.tables
WHERE database NOT IN ('system', 'information_schema', 'INFORMATION_SCHEMA')
GROUP BY ALL
    WITH TOTALS
ORDER BY count() ASC

   ┌─engine─────────────────────┬─count()─┐
1. │ SharedReplacingMergeTree   │       1 │
2. │ SharedAggregatingMergeTree │      12 │
3. │ MaterializedView           │      15 │
4. │ SharedMergeTree            │    1053 │
5. │ View                       │    4392 │
   └────────────────────────────┴─────────┘
```

We should treat and count views (and I think dictionaries) differently as the expected resource usage is completely different than a replicated table, for example. They should have a different count and message if necessary

**Comment by Beetelbrox** [comment]
Hallo! I'd like to give this issue a shot, would it be possible? Thanks!

**Comment by Algunenano** [comment]
Implemented in https://github.com/ClickHouse/ClickHouse/pull/64180
