### ISSUE TITLE
Speed up `set` index by adding comparison with min-max values

### ISSUE THREAD

**Issue by nickitat** [ClickHouse/ClickHouse#64134]
> BTW, once I noticed that `set` is 4 times slower than `minmax` with the same data.
> 
> ```sql
> set max_threads=1;
> 
> create table ind_minmax(A Int64, B Int64, index x1 B type minmax granularity 1) 
> Engine MergeTree order by A as select number, cityHash64(number)%111111=1 from numbers(1e8);
> optimize table ind_minmax final;
> 
> create table ind_set(A Int64, B Int64, index x1 B type set(2) granularity 1) 
> Engine MergeTree order by A as select number, cityHash64(number)%111111=1 from numbers(1e8);
> optimize table ind_set final;
> 
> select count() from ind_minmax where B = 1;
> Elapsed: 0.015 sec. Processed 7.26 million rows
> 
> select count() from ind_set where B = 1;
> Elapsed: 0.060 sec. Processed 7.26 million rows
> 
> drop table ind_set;
> drop table ind_minmax;
> ```
> 
> 0.015 sec vs 0.060 sec

because we check predicate against all set elements. it is known sub-optimality (lack of min-max for set)

_Originally posted by @nickitat in https://github.com/ClickHouse/ClickHouse/issues/64098#issuecomment-2119280590_

**Comment by AntiTopQuark** [comment]
Hi @nickitat ,I am interested in this problem. Could you assign the issue to me?

**Comment by AntiTopQuark** [comment]
Hi @nickitat , I have completed the task, please review my PR #65676 
thanks

**Comment by AntiTopQuark** [comment]
Effect of optimization:

![image](https://github.com/ClickHouse/ClickHouse/assets/32798045/c145db6f-530e-42bb-981a-f9f660649c2b)
