### ISSUE TITLE
After upgrade to 24.4.1, started getting "Not found column __table2.userid in block"

### ISSUE THREAD

**Issue by tluchowski** [ClickHouse/ClickHouse#64131]
**Describe what's wrong**

After upgrade from 24.3.3 to 24.4.1, I started getting this error:

Received exception from server (version 24.4.1):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: **Not found column __table2.userid in block. There are only columns: __table1.FinalizedDateString, __table1.ForegroundSeconds, __table1.UserID, __table1.FinalizedTime, _CAST(__table1.UserID, 'UInt64'_String). (NOT_FOUND_COLUMN_IN_BLOCK)**

This is caused by the following query:

select u.department,FinalizedDateString,sum(ForegroundSeconds) as ForegroundSecondsSum,count(distinct UserID) as UsersCount from report join user_dict u on UserID = u.userid where toDayOfWeek(FinalizedTime) < 6  group by u.department,FinalizedDateString order by u.department;

If I change the WHERE section of this query a bit - change "toDayOfWeek(FinalizedTime) < 6" to "1 < 6", it works just fine:

select u.department,FinalizedDateString,sum(ForegroundSeconds) as ForegroundSecondsSum,count(distinct UserID) as UsersCount from report join user_dict u on UserID = u.userid where 1 < 6  group by u.department,FinalizedDateString order by u.department;

In case it's relevant, "user_dict" is a dictionary, loaded via ODBC.

This happened in two independent environments, and quite different ones - one running Red Hat, the other being based on Ubuntu.

In both cases, downgrading to previous version of Clickhouse resolved the issue

**Does it reproduce on the most recent release?**
Yes
[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/63228
already fixed
@tluchowski  downgrade and wait for the 24.2 release

**Comment by tluchowski** [comment]
Thank you Denny! I'll try to be patient then :)

**Comment by tluchowski** [comment]
I'll wait for 24.4.2
