### ISSUE TITLE
SYSTEM RELOAD DICTIONARY ... ON CLUSTER ... 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#6418]
add support for ON CLUSTER for SYSTEM RELOAD DICTIONARY.

May be some other SYSTEM queries can be executed on cluster (not sure about all of them)

**Comment by den-crane** [comment]
probably it will be useful for at least for
SYSTEM DROP DNS CACHE;
SYSTEM DROP MARKS CACHE;
SYSTEM RELOAD CONFIG;
