### ISSUE TITLE
Do not materialize indexes during inserts

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#64201]
**Use case**

User wants to have fast inserts and there are many indexes.
Level0 parts are small vs the whole data in table so reading it without indexes can be possible.

**Describe the solution you'd like**

A setting `materialize_index_on_insert`. Enabled by default as today. By disabling index will not be materialized on insert, but will appear during merge.

**Comment by UnamedRus** [comment]
Same for projections

**Comment by rschu1ze** [comment]
Quoting @CurtizJ :-) `No, for projections it won’t work because we don’t recalculate projections on merges.`

**Comment by den-crane** [comment]
Interesting, I did not know that it works this way.

Parts have different number of projections: 0 in part 'all_2_2_0' and 1 in part 'all_3_3_0'. Cannot select parts for optimization. (CANNOT_ASSIGN_OPTIMIZE)

https://fiddle.clickhouse.com/9b184f13-270f-46df-a195-df5d71a231e7

**Comment by cangyin** [comment]
> Quoting @CurtizJ :-) `No, for projections it won’t work because we don’t recalculate projections on merges.`

This can be solved by #62364 .
