### ISSUE TITLE
Code: 59. DB::Exception: Illegal type Float64 of column 0

### ISSUE THREAD

**Issue by Young0516** [ClickHouse/ClickHouse#64213]
my table :
<img width="929" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/35856569/d94b6bef-3e64-4346-ad54-9dfaccb0dbd5">

error sql:  SELECT  * from test_database.number_cloumn_0_test where 0

when select a table which contains column named '0',   the filter of  'where 0' didn't work. 

Error details：Code: 59. DB::Exception: Illegal type Float64 of column 0 for filter. Must be UInt8 or Nullable(UInt8). (ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER) (version 23.3.1.2823 (official build))

**Comment by Algunenano** [comment]
Please update to a supported release: `curl https://clickhouse.com/ | sh`

If that doesn't work, provide a reproducer (https://fiddle.clickhouse.com/), not a screenshot, and reopen, please.
