### ISSUE TITLE
After using asynchronous writing, the memory usage becomes very unstable

### ISSUE THREAD

**Issue by biuboombiuboom** [ClickHouse/ClickHouse#64215]
ClickHouse server version 22.9.2 revision 54460
asyn  config
```
async_insert_max_data_size=2147483648 //2gb
async_insert_busy_timeout_ms=60000
```

![image](https://github.com/ClickHouse/ClickHouse/assets/7258606/7322e397-8a80-40e6-ade2-35db991ba489)

**Comment by genzgd** [comment]
Please use a more recent version.  There have been many changes to async inserts since 22.9

**Comment by CamiloSierraH** [comment]
@biuboombiuboom even the [asynchronous_insert_log](https://clickhouse.com/docs/en/operations/system-tables/asynchronous_insert_log) system table was added on the version [22.10](https://clickhouse.com/docs/en/whats-new/changelog/2022#-clickhouse-release-2210-2022-10-25), so you're pretty much flying blind with this feature on 22.9.

If you upgrade to one of the latest version, we have a great blog post about how troubleshooting async inserts https://clickhouse.com/blog/monitoring-asynchronous-data-inserts-in-clickhouse
