### ISSUE TITLE
cluster_secure_connection option ignored while creating Replicated database?

### ISSUE THREAD

**Issue by basbk** [ClickHouse/ClickHouse#64216]
Hello everyone,

I have a task to migrate our ClickHouse cluster to use TLS connections and sunset nonTLS ports.

When I tried to disable nonTLS ports I've got errors related to cluster communication created by Replicated database. I've checked the system.clusters table and indeed it is still defined 9000 port for communication.
That time we used 23.3 version and I found this [fix](https://github.com/ClickHouse/ClickHouse/pull/56486) which should help us with the migration. So I upgraded the cluster to 24.3.3.102-lts but looks like the issue still in place.

This is what my configuration looks like:
config.xml
```xml
<named_collections>
        <super_test_3s_1r_collection>
            <cluster_username>super_test</cluster_username>
            <cluster_secure_connection>true</cluster_secure_connection>
        </super_test_3s_1r_collection>
</named_collections>
```
Then I restarted the node so the collection can take effect
Then I created replicated database this way:
```sql
CREATE DATABASE super_test_storage ENGINE = Replicated('/clickhouse/super_test_storage/', 'super-test-03', '{super_test_replica}') SETTINGS collection_name='super_test_3s_1r_collection'
```
But if I check system.clusters table after that it still uses 9000 nonTLS port:
```
   ┌─cluster────────────────────────┬─shard_num─┬─shard_weight─┬─internal_replication─┬─replica_num─┬─host_name────┬─host_address──┬─port─┬─is_local─┬─user─────────────┬─default_database─┬─errors_count─┬─slowdowns_count─┬─estimated_recovery_time─┬─database_shard_name─┬─database_replica_name───┬─is_active─┐
1. │ super_test_storage │         1 │            1 │                    0 │           1 │ clickhouse-3 │ 127.0.0.1 │ 9000 │        0 │ super_test │                  │            0 │               0 │                       0 │ super-test-03       │ super-test-clickhouse-3 │         1 │
   └────────────────────────────────┴───────────┴──────────────┴──────────────────────┴─────────────┴──────────────┴───────────────┴──────┴──────────┴──────────────────┴──────────────────┴──────────────┴─────────────────┴─────────────────────────┴─────────────────────┴─────────────────────────┴───────────┘

```

But at the same time cluster_username variable scanned and used correctly.
Am I missing something in the configuration or is it a bug?

**Comment by melvynator** [comment]
How did you configure your cluster? Can you add the openssl part too? 

Did you look at this guide to configure SSL-TLS: https://clickhouse.com/docs/en/guides/sre/configuring-ssl ?

**Comment by basbk** [comment]
@melvynator 
I use ZooKeeper for cluster coordination (not TLS enforced at the moment)
zookeeper.xml:
```xml
<zookeeper>
        <node>
            <host>ip1</host>
            <port>2181</port>
        </node>
        <node>
            <host>ip2</host>
            <port>2181</port>
        </node>
        <node>
            <host>ip3</host>
            <port>2181</port>
        </node>
</zookeeper>
```
ssl.xml:
```xml
<openSSL>
        <server> <!-- Used for https server AND secure tcp port -->
            <certificateFile>/etc/clickhouse-server/ssl/clickhouse.crt</certificateFile>
            <privateKeyFile>/etc/clickhouse-server/ssl/clickhouse.key</privateKeyFile>
            <verificationMode>relaxed</verificationMode>
            <caConfig>/etc/clickhouse-server/ssl/ca.crt</caConfig>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
        </server>

        <client> <!-- Used for connecting to https dictionary source -->
            <loadDefaultCAFile>true</loadDefaultCAFile>
            <caConfig>/etc/clickhouse-server/ssl/ca.crt</caConfig>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            <!-- Use for self-signed: <verificationMode>none</verificationMode> -->
            <verificationMode>relaxed</verificationMode>
            <invalidCertificateHandler>
                <!-- Use for self-signed: <name>AcceptCertificateHandler</name> -->
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
</openSSL>
```
and ports defined like that:
```xml
<http_port>8123</http_port>
<https_port>8443</https_port>
<tcp_port>9000</tcp_port>
<tcp_port_secure>9440</tcp_port_secure>

<interserver_http_port remove="true">9004</interserver_http_port>
<interserver_https_port>9010</interserver_https_port>
```

**Comment by basbk** [comment]
@melvynator I've checked your link and it would be great if I can use remote_servers section to define other nodes' endpoints. But when I create replicated database new cluster entity created and it is not controlled via this config file (remote_severs section). 

> The system.clusters system table contains a cluster named like the replicated database, which consists of all replicas of the database. This cluster is updated automatically when creating/deleting replicas, and it can be used for Distributed tables.

Using this page as a reference: https://clickhouse.com/docs/en/engines/database-engines/replicated

**Comment by melvynator** [comment]
@evillique @tavplubix I have never seen this setting 'cluster_secure_connection' and I can't find any documentation about it do you happened to know the issue?

**Comment by tavplubix** [comment]
Looks like Replicated databases always use TCP port when creating a cluster. We can fix that, but you will have to re-create databases or manually update metadata in ZooKeeper here:
```
localhost.localdomain :) select * from system.zookeeper where path='/database_path/replicas'

SELECT *
FROM system.zookeeper
WHERE path = '/database_path/replicas'

   ┌─name─┬─value─────────────────────────────────────────────────────────────┬─path──────────────────────┐
1. │ 1|1  │ localhost%2Elocaldomain:9000:37c5d4d7-06d6-44cc-918b-5497d2a104a5 │ /database_path/replicas │
   └──────┴───────────────────────────────────────────────────────────────────┴───────────────────────────┘
```
Btw, looks like manually updating the port in ZooKeeper is a possible workaround

**Comment by basbk** [comment]
@tavplubix many thanks for looking into it. I was also thinking about updating data in ZooKeeper directly but it looks as wrong way of doing things since there is no guarantee (at least at the documentation) that the metadata wouldn't be overwritten because of new replica joining or anything that triggers changes in replica set. I guess the most safe way is to wait for the proper fix to be sure that everything is under control?

So once fixed `cluster_secure_connection` variable will be used to control this, right?

**Comment by tavplubix** [comment]
According to the implementation, updating it manually in ZK will work, but yes, new replicas will be added with TCP port.

The fix (https://github.com/ClickHouse/ClickHouse/pull/65054) automatically updates the port number in ZK, so it will not require manual intervention
