### ISSUE TITLE
The precision returned by  uniqCombined is too low

### ISSUE THREAD

**Issue by crazyleeyang** [ClickHouse/ClickHouse#64248]
when use uniqCombined, The precision is less than 50%, but if use like uniqCombined(2, xx) or with other number as the first param, the precision is ok, is there someone encountered this problem?

colum type: string
version: 22.3.2.1

**Comment by serxa** [comment]
It is quite unusual. Could you provide more information about your dataset? How many strings, what is the average length, high or low cardinality? Also, it would be interesting to see the results of queries comparing how `uniqExact`, `uniq`, `uniqCombined`, and `uniqCombined64` behave on your dataset.

**Comment by nickitat** [comment]
any specific example when the problem reproduces?
have you tried changing `HLL_precision` parameter?

**Comment by den-crane** [comment]
uniqCombined is for int32 numbers and strings. Try `uniqCombined64`  instead.

>uniqCombined(2, xx)

Haha, in this case you pass a `tuple(2,xx)` and it starts to behave as uniqCombined64. Just use uniqCombined64.

* https://github.com/ClickHouse/ClickHouse/issues/63066

**Comment by den-crane** [comment]
@nickitat Maybe uniqCombined should throw an error if not 32 bit argument passed and show an explanation with a suggestion to use uniqCombined64? And the setting allow_unsafe_uniqCombined=false for the backward compatibility in queries and states saved with materialized views and projections.

**Comment by crazyleeyang** [comment]
> It is quite unusual. Could you provide more information about your dataset? How many strings, what is the average length, high or low cardinality? Also, it would be interesting to see the results of queries comparing how `uniqExact`, `uniq`, `uniqCombined`, and `uniqCombined64` behave on your dataset.



> It is quite unusual. Could you provide more information about your dataset? How many strings, what is the average length, high or low cardinality? Also, it would be interesting to see the results of queries comparing how `uniqExact`, `uniq`, `uniqCombined`, and `uniqCombined64` behave on your dataset.

The statistics of column length arre as follows

> 
```
┌─col_len─┬──count()─┐
│       8 │        2 │
│      11 │       13 │
│      13 │       48 │
│      14 │     1078 │
│      15 │    14925 │
│      16 │  2017052 │
│      17 │        2 │
│      19 │        1 │
│      24 │        5 │
│      32 │  8241286 │
│      33 │        1 │
│      34 │       22 │
│      35 │      407 │
│      36 │  7784682 │
│      40 │        1 │
│      42 │        2 │
│      50 │        7 │
│      64 │ 10931446 │
│      65 │        2 │
│      71 │        7 │
│      82 │      245 │
│     116 │        2 │
│     146 │       76 │
└─────────┴──────────┘
```

**Comment by crazyleeyang** [comment]
> any specific example when the problem reproduces? have you tried changing `HLL_precision` parameter?

i have test with HLL_precision, it works ok
