### ISSUE TITLE
Execute statement  optimize final Exception

### ISSUE THREAD

**Issue by deriveKnowledge** [ClickHouse/ClickHouse#64247]
clickhouse version 21.11.5.33
partition data size: 1G
data row count: 766978
Execute statement : optimize table t_posts  partition '202311' final;
clickhouse loop create file mutation_*.txt, but the program does not end and finally times out. 
restart clickhouse reexecute sql, The problem still exists

**Comment by Algunenano** [comment]
Please upgrade to a supported release
