### ISSUE TITLE
The memory usage keeps increasing.

### ISSUE THREAD

**Issue by dxygit1** [ClickHouse/ClickHouse#64260]
clickhouse version： 21.12.3.32
I've noticed that the memory usage keeps increasing every day during usage.

There aren't many SQL queries currently running, but I don't understand why so much memory is being used.

![image](https://github.com/ClickHouse/ClickHouse/assets/57128304/ee97d942-8805-402a-92bb-3e758745f7a0)

![image](https://github.com/ClickHouse/ClickHouse/assets/57128304/2c033f1a-375a-4c4c-bd74-adbf1e63dd23)
![image](https://github.com/ClickHouse/ClickHouse/assets/57128304/7f1316c7-1e67-4b09-a0db-2acb20fbfa59)

**Comment by dxygit1** [comment]
After restarting ClickHouse, the memory usage returns to normal, but after some time, the memory usage increases again.

**Comment by dxygit1** [comment]
Approximately 1GB of incremental memory usage per day.

![image](https://github.com/ClickHouse/ClickHouse/assets/57128304/312b8023-6511-4101-89ac-b232eb34f03c)

**Comment by Algunenano** [comment]
Unsupported version. Please update: `curl https://clickhouse.com/ | sh`
