### ISSUE TITLE
 Error while reading Parquet data: IOError: Couldn't deserialize thrift: TProtocolException: Invalid data Deserializing page header failed. : While executing ParquetBlockInputFormat: While executing S3. (CANNOT_READ_ALL_DATA) (version 22.3.6.5)

### ISSUE THREAD

**Issue by Gushiyu** [ClickHouse/ClickHouse#64280]
> Make sure to check documentation https://clickhouse.com/docs/en/ first. If the question is concise and probably has a short answer, asking it in [community Slack](https://join.slack.com/t/clickhousedb/shared_invite/zt-1gh9ds7f4-PgDhJAaF8ad5RbWBAAjzFg) is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

> If you still prefer GitHub issues, remove all this text and ask your question here.

I've a parquet file in S3, and I create a external table in clickhouse. 
`CREATE TABLE ods.test_0523 (     `type_name` Nullable(String),     `type_value` Nullable(String),     `normal_order_id` Decimal(20, 0),     `order_no` Nullable(String),     `complete_time` Nullable(String),     `total_price` Nullable(Decimal(24, 4)),     `real_price` Nullable(Decimal(24, 4)),     `coupon_pay` Nullable(Decimal(24, 4)),     `point_pay` Nullable(Decimal(24, 4)),     `money_pay` Nullable(Decimal(24, 4)),     `member_id` Nullable(String),     `goods_receive_time` Nullable(DateTime('UTC')),     `ext_transaction_no` Nullable(String),     `order_status` Nullable(String),     `transaction_time` Nullable(String),     `product_count` Nullable(Int64),     `store_code` Nullable(String),     `store_name` Nullable(String),     `merchant_id` Nullable(String),     `channel_name` Nullable(String),     `shop_id` Nullable(String),     `pos_id` Nullable(String),     `operator_id` Nullable(String),     `receiver_name` Nullable(String),     `receiver_province` Nullable(String),     `receiver_city` Nullable(String),     `receiver_county` Nullable(String),     `receiver_address` Nullable(String),     `receiver_mobile` Nullable(String),     `nick_name` Nullable(String),     `goods_shipped_out_time` Nullable(DateTime('UTC')),     `add_time` Nullable(DateTime('UTC')),     `create_time` Nullable(DateTime('UTC')),     `last_change_time` Nullable(DateTime('UTC')),     `pre_sales` Nullable(String),     `parent_order_no` Nullable(String),     `is_exchange_order` Nullable(String),     `point_issuance_status` Nullable(String),     `dl_batch_date` Nullable(String),     `dl_load_time` Nullable(DateTime('UTC')) ) ENGINE = S3('https://s3.cn-northwest-1.amazonaws.com.cn/mys3bucket_demo/temp/a_d_dl_crm_normal_order_000.parquet', 'Parquet')`

when I try to scan the whole table, it failed with error _Couldn't deserialize thrift:_ Anyone met this issue before? 

`insert into ods.new_table select * from ods.test_0523`
_ClickHouse exception, code: 1002, host: store-1, port: 8123; Code: 33. DB::ParsingException: Error while reading Parquet data: IOError: Couldn't deserialize thrift: TProtocolException: Invalid data
Deserializing page header failed.
: While executing ParquetBlockInputFormat: While executing S3. (CANNOT_READ_ALL_DATA) (version 22.3.6.5)_

This file was unload from AWS Redshift. It can be load back to redshift and can be read by python.
```
import pyarrow.parquet as pq
table = pq.read_table('/Users/XXXXX/Downloads/a_d_dl_crm_normal_order_000.parquet')
df=table.to_pandas()
print(df)
```

**Comment by Algunenano** [comment]
> 22.3.6.5

Please update to a supported release
