### ISSUE TITLE
Research: thread per core model

### ISSUE THREAD

**Issue by tomershafir** [ClickHouse/ClickHouse#64295]
I wonder, did you ever consider/research a thread-per-core/shard-per-core model for Clickhouse, like [ScyllaDB seastar](https://github.com/scylladb/seastar)?

**Comment by nikitamikhaylov** [comment]
I would say yes, but we didn't proceed further with this initiative as it will require us to rewrite the whole codebase. 
What we did so far is: 
- Implemented custom background jobs (merges, mutations) execution mechanism which allows us to suspend and resume their execution, but only in pre-defined places e.g. after executing a block. 
- Implemented a custom pipeline executor and introduced a task abstraction called IProcessor which allow us to better control the concurrency and the overall execution process.
- We do use boost coroutines in some places (for distributed query execution).

**Comment by alexey-milovidov** [comment]
Thread per core model requires userspace context switching and scheduling, which is painful to use and support.
OS threads are good enough.
