### ISSUE TITLE
Equal function produces LowCardinality(UInt8) instead of UInt8

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#6432]
```
DESCRIBE TABLE
(
    SELECT toLowCardinality('a') = 'a'
)

┌─name─┬─type──────────────────┬
│ x    │ LowCardinality(UInt8) │
└──────┴───────────────────────┴
```

Expected 
```

 ┌─name─┬─type──┬
 │ x    │ UInt8 │
 └──────┴───────┴
```

**Comment by alexey-milovidov** [comment]
That's exactly as it was designed.

**Comment by den-crane** [comment]
OK. But as I remember LowCardinality(UInt8) is always worse than UInt8?

**Comment by alexey-milovidov** [comment]
It is worse in storage but it may give advantages in calculations.

For example, we can write something like:
`low_cardinality = 'a' ? 'Hello' : 'World'`

and we will get `LowCardinality(String)` and it will be much better than `String`, because Strings Hello and World will be stored just once in a dictionary.

**Comment by filimonov** [comment]
@alexey-milovidov @den-crane 

I don't see any logic behind current behavior, explanations above don't clarify anything.

```
SELECT toTypeName(if(toLowCardinality('a') LIKE 'a', 1, 2))

┌─toTypeName(if(like(toLowCardinality('a'), 'a'), 1, 2))─┐
│ LowCardinality(UInt8)                                  │
└────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 0.004 sec. 

SELECT toTypeName(if('a' LIKE 'a', 1, 2))

┌─toTypeName(if(like('a', 'a'), 1, 2))─┐
│ UInt8                                │
└──────────────────────────────────────┘

1 rows in set. Elapsed: 0.004 sec. 
```
Questions:

1) Why type of condition argument affects the result of if? 

2) why do we wrap with LowCardinality uint8? (it is forbidden by allow_suspicious_low_cardinality_types):

```
CREATE VIEW abc AS
SELECT if(toLowCardinality(toString(number % 30)) LIKE '2', 1, 2)
FROM numbers(10)

Received exception from server (version 20.4.1):
Code: 455. DB::Exception: Received from localhost:9000. DB::Exception: Creating columns of type LowCardinality(UInt8) is prohibited by default due to expected negative impact on performance. It can be enabled with the "allow_suspicious_low_cardinality_types" setting.. 

0 rows in set. Elapsed: 0.006 sec. 
```
3) looking at your explanations above I came to conclusion that desired behavior is - for conditions when both branches return constant string expected result is `LowCardinality(String)` (And that's completely ok, and should not depend on condition type).

**Comment by alexey-milovidov** [comment]
@filimonov That's correct, we should make `if` with constant branches return LowCardinality.

**Comment by alexey-milovidov** [comment]
Model example:

```
clickhouse-benchmark <<< "SELECT count() FROM datasets.hits_v1 WHERE NOT ignore(SHA256(toString(SHA256(rand() % 2 ? 'hello' : 'world'))))"
```
0.116 sec.

```
clickhouse-benchmark <<< "SELECT count() FROM datasets.hits_v1 WHERE NOT ignore(SHA256(toString(SHA256(toLowCardinality(rand() % 2) ? 'hello' : 'world'))))"
```
0.022 sec.

It means that `LowCardinality(UInt8)` makes sense for computations.

**Comment by alexey-milovidov** [comment]
But we must eliminate all induced issues in usability.

**Comment by filimonov** [comment]
> It means that LowCardinality(UInt8) makes sense for computations.

It means that LowCardinality(String) makes sense for result of if, and that currently there is a wierd logic when type of result is deducted from type of condition instead a types of branches

**Comment by filimonov** [comment]
Check that:
```
set allow_suspicious_low_cardinality_types=1;
drop table if exists test_lc_cond;
create table test_lc_cond ( a LowCardinality(UInt8), b UInt8 ) engine=Memory;
insert into test_lc_cond select rand()%2 as a, a as b from zeros(1000000000);
```
Speed of checking `LowCardinality(UInt8)` vs `UInt8`:
``
SELECT count() FROM test_lc_cond WHERE NOT ignore(a)

┌────count()─┐
│ 1000000000 │
└────────────┘

1 rows in set. Elapsed: 0.439 sec. Processed 1.00 billion rows, 1.00 GB (2.28 billion rows/s., 2.28 GB/s.) 

SELECT count() FROM test_lc_cond WHERE NOT ignore(b)

┌────count()─┐
│ 1000000000 │
└────────────┘

1 rows in set. Elapsed: 0.010 sec. Processed 1.00 billion rows, 1.00 GB (102.73 billion rows/s., 102.73 GB/s.) 
```

Wierd type deduction:
```
SELECT toTypeName(if(a, 5, 10)) FROM test_lc_cond LIMIT 1

┌─toTypeName(if(a, 5, 10))─┐
│ LowCardinality(UInt8)    │
└──────────────────────────┘

SELECT toTypeName(if(b, 5, 10)) FROM test_lc_cond LIMIT 1

┌─toTypeName(if(b, 5, 10))─┐
│ UInt8                    │
└──────────────────────────┘

 SELECT toTypeName( if(a, 1.0, 7.0) ) FROM test_lc_cond limit 1;

┌─toTypeName(if(a, 1., 7.))─┐
│ LowCardinality(Float64)   │
└───────────────────────────┘
```

Indeed there is an issue with strings:
```
SELECT count() FROM test_lc_cond WHERE NOT ignore(if(b, 'Hello', 'World'))

┌────count()─┐
│ 1000000000 │
└────────────┘

1 rows in set. Elapsed: 1.846 sec. Processed 1.00 billion rows, 1.00 GB (541.83 million rows/s., 541.83 MB/s.) 

SELECT count() FROM test_lc_cond WHERE NOT ignore(if(a, 'Hello', 'World'))

┌────count()─┐
│ 1000000000 │
└────────────┘

1 rows in set. Elapsed: 0.517 sec. Processed 1.00 billion rows, 1.00 GB (1.93 billion rows/s., 1.93 GB/s.) 
```
But that should be solved another way (as described above), and it should be even faster if the condition would be plain UInt8 instead of LowCardinality(UInt8).

**Comment by alexey-milovidov** [comment]
This task makes sense, but it's better to avoid doing it.
