### ISSUE TITLE
primary key constraint violated in new added order-by column condition

### ISSUE THREAD

**Issue by myshzzx** [ClickHouse/ClickHouse#64396]
version 23.8.10.43-lts

```sql
create table if not exists meeting_ops_agg.test_local_3 on cluster "default_cluster"
(
    ts Int64 ,
    _ver Int64,
    k1        String default '',
    k2        String default '' ,
    v1        Nullable(Int64) ,
    v2        Nullable(Float64)
) engine = ReplicatedReplacingMergeTree('/clickhouse/tables/{database}/{table}/{shard}-{uuid}', '{replica}', _ver)
  PARTITION BY intDiv(ts, 86400000)
  ORDER BY (`ts`, "k1", "k2")
  TTL toDateTime(`ts`/1000) + toIntervalDay(30)
  SETTINGS index_granularity = 8192;

alter table meeting_ops_agg.test_local_3  on cluster "default_cluster"
    add column k3 String ,
    MODIFY ORDER BY  (`ts`, "k1", "k2", k3);

create table if not exists meeting_ops_agg.test on cluster "default_cluster"
as meeting_ops_agg. test_local_3 ENGINE = Distributed("default_cluster", meeting_ops_agg,  test_local_3, intDiv(ts, 86400000));

```

- now the table's primary key remains (ts, k1, k2) as I can see in `show create table meeting_ops_agg.test_local_3`

- insert data like this:
![image](https://github.com/ClickHouse/ClickHouse/assets/2025090/7673a737-d200-40a6-b276-f2432e9567af)

- then `select * from meeting_ops_agg.test final` , and I got the same return.

Isn't primary key constraint violated?
Is it a  feature or a bug? will it changed in new clickhouse version?

**Comment by den-crane** [comment]
>Isn't primary key constraint violated?

Feature. Clickhouse does not have primary key constraints,  and Clickhouse does not have primary keys (in terms of RDBMS). Clickhouse's `primary key` is more a primary index. Clickhouse's `order by` key is a sort key and an instruction how to merge (collapse) rows.

https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree
_Data deduplication occurs only during a merge. Merging occurs in the background at an unknown time, so you can’t plan for it. Some of the data may remain unprocessed._

**Comment by den-crane** [comment]
>now the table's primary key remains (ts, k1, k2) as I can see in show create table meeting_ops_agg.test_local_3

It's expected. PrimaryKey ( Primary index ) is impossible to change. This alter changes ORDERBY section.

> (`ts`, "k1", "k2", k3);

There is no duplicates on the picture. k3 is different.

**Comment by myshzzx** [comment]
thks
