### ISSUE TITLE
When I use hdfs engine with kerberos，Exception as follows

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#64429]
version：23.8
Unable to connect hdfs：hdfsrpcexception： got protocol mismatch： RPC channel cannot find pending call：id = -33... (NETWORK_ERROR)

**Comment by Sallery-X** [comment]
hdfs-site.xml contain

dfs.data.transfer.protection  value is authentication,privacy

**Comment by den-crane** [comment]
@Sallery-X you already asked this question https://github.com/ClickHouse/ClickHouse/issues/64088
It has no sense to create more issue. It will change nothing.
