### ISSUE TITLE
The kafka engine is not synching after the with "part spans partitions"

### ISSUE THREAD

**Issue by amchakra789** [ClickHouse/ClickHouse#6443]
2019.08.11 23:27:27.531166 [ 51 ] {} <Error> void DB::StorageKafka::streamThread(): Code: 49, e.displayText() = DB::Exception: Logical error: part spans more than one month.: while pushing to view BBYFlow.consumer_mia1, e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cf456]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x2cf7632]
2. clickhouse-server(DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&)+0x11f8) [0x53727d8]
3. clickhouse-server(DB::MergeTreeBlockOutputStream::write(DB::Block const&)+0xc9) [0x5314b09]
4. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0x51) [0x5508921]
5. clickhouse-server(DB::PushingToViewsBlockOutputStream::process(DB::Block const&, unsigned long)+0x401) [0x55080c1]
6. clickhouse-server(DB::PushingToViewsBlockOutputStream::write(DB::Block const&)+0xbe) [0x550898e]
7. clickhouse-server(DB::SquashingBlockOutputStream::write(DB::Block const&)+0x4ad) [0x5511e4d]
8. clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x89) [0x548e089]
9. clickhouse-server(DB::CountingBlockOutputStream::write(DB::Block const&)+0x2c) [0x54af77c]
10. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0xc1) [0x4f5b611]
11. clickhouse-server(DB::StorageKafka::streamToViews()+0x630) [0x65a1200]
12. clickhouse-server(DB::StorageKafka::streamThread()+0x1a8) [0x65a1898]
13. clickhouse-server(DB::BackgroundSchedulePool::TaskInfo::execute()+0xef) [0x54888ff]
14. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0xba) [0x54896ca]
15. clickhouse-server() [0x6ee922f]
16. /lib64/libpthread.so.0(+0x7dd5) [0x7f380f18bdd5]
17. /lib64/libc.so.6(clone+0x6d) [0x7f380e9aaf6d]

**Comment by abyss7** [comment]
What is CH version?

**Comment by alexey-milovidov** [comment]
#9973

**Comment by alexey-milovidov** [comment]
It is caused by wrong data improted into table.
Kafka engine is trying to import it again and again, it cannot skip this data.
