### ISSUE TITLE
ClickHouse Keeper cannot start since v24.4 

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#64436]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Describe what's wrong**

> A clear and concise description of what works not as it is supposed to.

When running Keeper as standalone process, it hang and cannot accept connection. I believe the issue had started since #62196. The PR attempts to replace threads in `NuRaft` with ClickHouse `ThreadFromGlobalPool`, however the global thread pool created by Keeper by default has very limited resource. I've checked and found that many raft-related worker cannot start.

```
    GlobalThreadPool::initialize(
        config().getUInt("max_thread_pool_size", 100),
        config().getUInt("max_thread_pool_free_size", 1000),
        config().getUInt("thread_pool_queue_size", 10000)
    );
```

I believe we need more than 100 threads to run all `NuRaft` workers.

cc @antonio2368 @alesapin

**Comment by antonio2368** [comment]
the problem is that we create asio threads equal to the amount of cores
I guess 1000 is enough for now...
