### ISSUE TITLE
ODBC driver and MergeTree

### ISSUE THREAD

**Issue by gusevartemasd** [ClickHouse/ClickHouse#6445]
I have data dublication, when I use ODBC clickhouse driver with MergeTree table, driver send two same request each time when frequency = 1 sec and one request when frequency = 10 sec.
It is normall clickhouse ODBC driver behavior?
Earlier I use it just with ReplicatedMergeTree, which have deduplication function and everything looks fine

logs 1sec:
2019.08.08 06:27:14.428711 [ 63 ] {20fcc7b2-49e0-4ba6-8aa1-1c7f891e6617} <Debug> executeQuery: (from 172.17.2.11:51334) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:27:14.453038 [ 46 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51335, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:27:14.499450 [ 46 ] {8a95d4db-2a35-4c80-8e1c-4ef8502fc761} <Debug> executeQuery: (from 172.17.2.11:51335) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:27:15.428637 [ 46 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51335, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:27:15.455491 [ 46 ] {83c6505b-3995-401c-a276-b6a3da386a64} <Debug> executeQuery: (from 172.17.2.11:51335) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:27:15.456527 [ 80 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51336, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:27:15.520938 [ 80 ] {d05f0895-a5d1-43a3-ade3-dbb060d8165b} <Debug> executeQuery: (from 172.17.2.11:51336) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:27:16.425922 [ 80 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51336, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:27:16.429651 [ 80 ] {082ea93e-0520-46b5-9067-198c848dca12} <Debug> executeQuery: (from 172.17.2.11:51336) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:27:16.456446 [ 49 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51337, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:27:16.502012 [ 49 ] {8c7e5915-dc9d-4e43-b55e-ef5b11cbf394} <Debug> executeQuery: (from 172.17.2.11:51337) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES

log 10sec:

2019.08.08 06:17:46.684331 [ 80 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51159, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:17:46.805788 [ 80 ] {18765988-d9cb-45f2-a26d-2a1fe4492342} <Debug> executeQuery: (from 172.17.2.11:51159) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:17:56.700456 [ 63 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51160, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:17:56.820901 [ 63 ] {fee6439a-2715-40f4-a1a4-eccb260ebe40} <Debug> executeQuery: (from 172.17.2.11:51160) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:18:09.675780 [ 80 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51161, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:18:09.793659 [ 80 ] {cee8619c-5982-4465-b3b8-67ea3625408b} <Debug> executeQuery: (from 172.17.2.11:51161) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:18:16.708601 [ 63 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51168, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:18:16.826917 [ 63 ] {6936d22c-08ae-44dd-930d-f83180fef878} <Debug> executeQuery: (from 172.17.2.11:51168) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:18:29.676363 [ 71 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51171, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:18:29.809223 [ 71 ] {c63080ef-5c6c-411b-b1f4-47eb90fb7176} <Debug> executeQuery: (from 172.17.2.11:51171) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:18:36.698432 [ 74 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51172, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:18:36.817992 [ 74 ] {85b41a2e-fe42-4d51-8c7b-06c303c5eb32} <Debug> executeQuery: (from 172.17.2.11:51172) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:18:49.679583 [ 74 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51179, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:18:49.797407 [ 74 ] {b8d56ef8-81db-4363-99ee-0964a4d55500} <Debug> executeQuery: (from 172.17.2.11:51179) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES
2019.08.08 06:18:56.699081 [ 49 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 172.17.2.11:51180, User-Agent: clickhouse-odbc/1.0.0.20190         611 (windows) UNICODE, Content Type: , Transfer Encoding: chunked
2019.08.08 06:18:56.818011 [ 49 ] {f4e51e33-5f2f-4f14-8fb6-4c62b5b0437e} <Debug> executeQuery: (from 172.17.2.11:51180) INSERT INTO param_values_history (param_value, param_value_qualit         y, time, param_id, msec) VALUES

**Comment by gusevartemasd** [comment]
No one used ODBC driver with non replicated tables?

**Comment by alex-zaitsev** [comment]
@gusevartemasd , ODBC driver is widely used. What you see does not seem to be related to the driver, but looks like your application. 'param_values_history' is your table, how do you insert into it from the driver?

**Comment by gusevartemasd** [comment]
> @gusevartemasd , ODBC driver is widely used. What you see does not seem to be related to the driver, but looks like your application. 'param_values_history' is your table, how do you insert into it from the driver?

We do not control the process from the driver to the table.

**Comment by alex-zaitsev** [comment]
Do you control your collector?

**Comment by gusevartemasd** [comment]
> Do you control your collector?

ofc
and i'm sure that it send just one query to ODBC clickhouse driver

**Comment by blinkov** [comment]
@gusevartemasd, do you have any further questions?

**Comment by alexey-milovidov** [comment]
I don't see how it can be related to ODBC driver because it doesn't have retries with 1 and 10 seconds for sending data. BTW, HTTP POST queries that ODBC driver is using should not be retried at all.

It may happen due to some logic on application side or in some proxy.
