### ISSUE TITLE
System sync replica behavior

### ISSUE THREAD

**Issue by EvanLai0819** [ClickHouse/ClickHouse#64454]
My Clickhouse version is 23.3 and I have setup a cluster as below.

Cluster : TechnicalCluster
Replicas: R1, R2, R3
Table: test_table

If I just shutdown R1 , then I run the `system sync replica table test_table` , the response is quick and success. 
But if I shutdown the R1 server,  then I run the `system sync replica table test_table` , the result is failure and return timeout error. 

Anything I miss here ?

**Comment by den-crane** [comment]
kubernetes ? Can you please share the copy/paste of the error?

**Comment by den-crane** [comment]
Or do you mean you shutdown R1 server without shutdown R1 ?

**Comment by EvanLai0819** [comment]
Hi @den-crane ,
I just deployed on GCE. 
Yes, I shutdown the R1 directly, because I need to simulate site failure case. 
The error message is `connect timed out read timeout is set to 3600000ms on R1:9000 read timeout is set to 3600000ms on R1:9000`

**Comment by den-crane** [comment]
The difference is because graceful shutdown VS abnormal shutdown. 
With the abnormal shutdown some parts stay unreplicated for other replicas and other replicas have unfinished replication tasks and it makes `system sync replica` hang. 
This is the expected behaviour.
