### ISSUE TITLE
What caused a change in behavior of `AS RESTRICTIVE` when creating ROW POLICY between 23.12 and 24.1?

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#64486]
https://fiddle.clickhouse.com/97521279-37b3-4a8d-b9dc-8f0517e89916

Seems like AS RESTRICTIVE was working wrong before 24.1. 

```sql
CREATE TABLE table_or_replace (d DATE, a String, b UInt8, x String, y Int8) ENGINE = MergeTree PARTITION BY y ORDER BY (b, d);

CREATE ROW POLICY pol_or_replace ON table_or_replace AS RESTRICTIVE 
FOR SELECT USING 1 TO default;

INSERT INTO table_or_replace (y) VALUES (1);

SELECT * FROM table_or_replace FORMAT TabSeparated;
```
23.12:
Zero rows in output.

Since 24:
```
1970-01-01		0		1
```

Which pr fixed that? I couldn't find one.

**Comment by den-crane** [comment]
hmm? The same PR as I pointed before 

* https://github.com/ClickHouse/ClickHouse/pull/58584/files `<users_without_row_policies_can_read_rows>true</users_without_row_policies_can_read_rows>`

**Comment by alsugiliazova** [comment]
Oh, thank you

**Comment by alsugiliazova** [comment]
No, that is not the case. The default user has a policy on the table that allows him to read all the rows:
```
CREATE ROW POLICY pol_or_replace ON table_or_replace AS RESTRICTIVE 
FOR SELECT USING 1 TO default;
```
The restrictive policy  (USING 1) by itself does not limit access to rows. Where am I wrong?

**Comment by den-crane** [comment]
It seems like you misunderstand what is RESTRICTIVE policy means. Check https://clickhouse.com/docs/en/sql-reference/statements/create/row-policy#as-clause

**Comment by alsugiliazova** [comment]
Thank you again
