### ISSUE TITLE
 After upgrading clickhouse to 23.9.6.20, the memory keeps growing

### ISSUE THREAD

**Issue by stereon** [ClickHouse/ClickHouse#64495]
clickhouse version：
23.9.6.20

memory monitor metric：
![WechatIMG164](https://github.com/ClickHouse/ClickHouse/assets/52196865/4e9340e2-6089-4860-875d-3c317a240d5a)

After restarting, the memory recovers, and after a while the memory grows again

**Comment by Algunenano** [comment]
Please upgrade to a supported release and verify if this still happens

**Comment by stereon** [comment]
Please upgrade to which version?

**Comment by Algunenano** [comment]
A supported one. Check https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions.

**Comment by liubo-it** [comment]
Does the upgrade work? @stereon

**Comment by stereon** [comment]
Nothing works

**Comment by stereon** [comment]
> Does the upgrade work? @stereon

Nothing works
