### ISSUE TITLE
Running style check locally produces shows error /process_style_check_result.py not found

### ISSUE THREAD

**Issue by rvasin** [ClickHouse/ClickHouse#64493]
**Describe the unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
Recent `master`.

`cd` to ClickHouse root.

Execute commands as they are given in the documentation:

```bash
mkdir -p /tmp/test_output
# running all checks
docker run --rm --volume=.:/ClickHouse --volume=/tmp/test_output:/test_output -u $(id -u ${USER}):$(id -g ${USER}) --cap-add=SYS_PTRACE clickhouse/style-test
```

**Expected behavior**
Style check should work locally from instructions in official documentation.

**Error message and/or stacktrace**

The output is:

```
/run.sh: line 27: /process_style_check_result.py: No such file or directory
```

**Additional context**
About 3 years ago @tavplubix removed from docker/test/style/Dockerfile the line:

```
COPY process_style_check_result.py /
```

Maybe it's worth to add it back.

**Possible solution**

Use `--volume=./utils/check-style/process_style_check_result.py:/process_style_check_result.py`. Thus run it with:

```bash
mkdir -p /tmp/test_output
# running all checks
docker run --rm --volume=.:/ClickHouse --volume=./utils/check-style/process_style_check_result.py:/process_style_check_result.py --volume=/tmp/test_output:/test_output -u $(id -u ${USER}):$(id -g ${USER}) --cap-add=SYS_PTRACE clickhouse/style-test
```

**Comment by rvasin** [comment]
Another probably solution could be in `docker/test/style/run.sh`

Instead of:

```
/process_style_check_result.py || echo -e "failure\tCannot parse results" > /test_output/check_status.tsv
```
 
Use

```
./utils/check-style//process_style_check_result.py || echo -e "failure\tCannot parse results" > /test_output/check_status.tsv
```

or other variants like `/ClickHouse/utils/check-style//process_style_check_result.py`

Right not it's not clear how the style check works in GitHub ClickHouse without these workaround solutions.

CC @Felixoid

**Comment by Felixoid** [comment]
I think a way to run it should be a simple `python tests/ci/style_check.py --no-push`

We can add arguments to limit to only specific checks, like python, shell, or
