### ISSUE TITLE
Analyzer compatibilty issue when HAVING was rewritten to WHERE

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#64505]
There is an old behaviour that allowed to write `WHERE` condition in `HAVING` part and it worked. 

Although behaviour is not correct, it can break user queries. I found this one in playbench cell towers:
```
SELECT radio, MAX(samples) FROM cell_towers GROUP BY radio having created > 2017-01-01
``` 

Simplified:
```
SELECT
    number % 2 AS n,
    max(number)
FROM numbers(10)
GROUP BY n
HAVING number > 5
SETTINGS allow_experimental_analyzer = 1

Query id: 95582583-75a5-4b1a-83ee-ceca518a4aba


Elapsed: 0.226 sec.

Received exception from server (version 24.2.2):
Code: 215. DB::Exception: Received from lws5yuwz96.us-east-2.aws.clickhouse-staging.com:9440. DB::Exception: Column number is not under aggregate function and not in GROUP BY keys. In query SELECT number % 2 AS n, max(number) FROM numbers(10) GROUP BY n HAVING number > 5 SETTINGS allow_experimental_analyzer = 1. (NOT_AN_AGGREGATE)

clickhouse-cloud :) SELECT number%2 as n, max(number) FROM numbers(10) GROUP BY n HAVING number > 5 SETTINGS allow_experimental_analyzer =0

SELECT
    number % 2 AS n,
    max(number)
FROM numbers(10)
GROUP BY n
HAVING number > 5
SETTINGS allow_experimental_analyzer = 0

Query id: cce36730-0bc1-41a2-a792-df8147684ee6

   ┌─n─┬─max(number)─┐
1. │ 0 │           8 │
2. │ 1 │           9 │
   └───┴─────────────┘

2 rows in set. Elapsed: 0.003 sec.
```

We may need to allow such behaviour with compatibility flag that will be disabled in master by default, but set to enabled in previous compatibility versions. So switching analyzer on in future will not break queries.

cc: @Algunenano

**Comment by qoega** [comment]
Same for `SELECT MAX(COUNT(cell)) FROM cell_towers WHERE lat BETWEEN 54 AND 56 AND lon BETWEEN 54 AND 56 GROUP BY cell`

**Comment by Algunenano** [comment]
This might be one of the cases where we don't want to spend time to fix something that's not broken and we can request users to fix their queries.

I'm not sure it's reasonable to supporting the old  behaviour, which was broken and unexpected, requires some effort to both implement it now and then support it forever.

cc @KochetovNicolai 


> Same for SELECT MAX(COUNT(cell)) FROM cell_towers WHERE lat BETWEEN 54 AND 56 AND lon BETWEEN 54 AND 56 GROUP BY cell

This one doesn't have `HAVING`. Is it a different issue?

**Comment by qoega** [comment]
>Is it a different issue?

Yep.. https://github.com/ClickHouse/ClickHouse/issues/64510

**Comment by novikd** [comment]
The new analyzer doesn't allow execution of invalid queries.  The query you provided aggregates by `number % 2` and tries to filter by `number` after that, so it's an invalid query. 

I also should mention that analyzer supports moving filter from `HAVING` for valid queries. The following query works:
```sql
SELECT
    number % 2 AS n
FROM numbers(10)
HAVING number > 5
```

**Comment by novikd** [comment]
I am adding info about it into the documentation #64643.
