### ISSUE TITLE
Incorrect grant prompt on data engine errors

### ISSUE THREAD

**Issue by fusiyuan2010** [ClickHouse/ClickHouse#64552]
The Clickhouse error shows "Not enough privileges. To execute this query, it's necessary to have the grant TABLE ENGINE ON Distributed" when I am creating a distributed table, despite I already have "GRANT TABLE ENGINE ON Distributed".  The actual missing grant is "GRANT REMOTE ON"

**How to reproduce**
The issue exists after I upgraded to 24.4.

**Expected behavior**
It should remind me to grant remote, as I don't even have TableEnginesRequireGrant be ON.

**Error message and/or stacktrace**
SQL: CREATE TABLE IF NOT EXISTS otel."logs_myapi" ON CLUSTER main
    AS otel."logs_myapi_local" ENGINE = Distributed('main', 'logs', 'logs_myapi_local', rand())
Response(500): Code: 497. DB::Exception: writer: Not enough privileges. To execute this query, it's necessary to have the grant TABLE ENGINE ON Distributed. (ACCESS_DENIED) (version 24.4.1.2088 (official build))

While:
SHOW GRANTS FOR this_user

Query id: 138a2e27-b801-4eaa-bfba-52f1a1d6ada5

   ┌─GRANTS FOR this_user───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
1. │ GRANT KILL QUERY, CLUSTER ON *.* TO this_user                                                                                                                                                      │
2. │ GRANT TABLE ENGINE ON Distributed TO this_user                                                                                                                                                     │
3. │ GRANT SHOW, SELECT, INSERT, ALTER, CREATE DATABASE, CREATE TABLE, CREATE VIEW, CREATE DICTIONARY, DROP DATABASE, DROP TABLE, DROP VIEW, DROP DICTIONARY, TRUNCATE, OPTIMIZE ON logs.* TO this_user │
4. │ GRANT ALTER ON system.* TO this_user                                                                                                                                                               │
   └───────────────────────────────────────────────────────────────────────────────────────────

**Additional context**
I figured out the fix of adding "GRANT REMOTE" by reading the implementation at https://github.com/ClickHouse/ClickHouse/pull/60117/files#diff-3869c849e10b17978935ead7b631cfaff4a3a88c3d8fb801ca7ddb95d0f5c817R248

**Comment by pkit** [comment]
Spent 2 hours on that one. Nice!

**Comment by anvaari** [comment]
I have same issue on `25.8.10.7`. Seems not fixed yet
