### ISSUE TITLE
Clickhouse Compile package too large

### ISSUE THREAD

**Issue by XiaoqiMa** [ClickHouse/ClickHouse#64576]
**Describe the issue**
Platform: AARCH64
Linux: CentOS

When I follow the offical build guide(https://clickhouse.com/docs/en/development/build), I have successfully compiled the "clickhouse" package, but it is too large comparing with package that can be downloaded from github release or the `https://clickhouse.com/` script

**How to reproduce**

Compiling the source code with the following steps:
```
sudo yum update
sudo yum --nogpg install git cmake make clang python3 ccache lld nasm yasm gawk
git clone --recursive https://github.com/ClickHouse/ClickHouse.git
mkdir build
cmake -S . -B build
cmake --build build
```
I have compiled the packages under ./Clickhouse/build/programs with 2.2G:
![image](https://github.com/ClickHouse/ClickHouse/assets/19272762/6ecbad48-df00-47f7-8542-5a14c6b14f86)

**Expected behavior**
If I download pacakge from command `curl https://clickhouse.com/ | sh`, the pacakges about 476MB
![image](https://github.com/ClickHouse/ClickHouse/assets/19272762/8e7d86b4-9dce-4c2c-9ea0-63085e080ca4)

So, my question is 
1. how can we get the smaller package, just like downloading through the script(https://github.com/ClickHouse/ClickHouse/blob/master/docs/_includes/install/universal.sh) 
2. If I have compile the source code, how can I get the RPM or TAR version of clickhouse, just like github release (https://github.com/ClickHouse/ClickHouse/releases)

**Comment by Algunenano** [comment]
> how can we get the smaller package, just like downloading through the script

Those files are self-extracting (they are compressed and decompress themselves the first time you run them): `-DENABLE_CLICKHOUSE_SELF_EXTRACTING=1` to cmake.

> If I have compile the source code, how can I get the RPM or TAR version of clickhouse, just like github release (https://github.com/ClickHouse/ClickHouse/releases)

Check https://github.com/ClickHouse/ClickHouse/blob/b58a2387ef12e5b18c10b22827063412b0df56e5/packages/build and the build logs of any commit

**Comment by mazhaonan** [comment]
> **Describe the issue** Platform: AARCH64 Linux: CentOS
> 
> When I follow the offical build guide(https://clickhouse.com/docs/en/development/build), I have successfully compiled the "clickhouse" package, but it is too large comparing with package that can be downloaded from github release or the `https://clickhouse.com/` script
> 
> **How to reproduce**
> 
> Compiling the source code with the following steps:
> 
> ```
> sudo yum update
> sudo yum --nogpg install git cmake make clang python3 ccache lld nasm yasm gawk
> git clone --recursive https://github.com/ClickHouse/ClickHouse.git
> mkdir build
> cmake -S . -B build
> cmake --build build
> ```
> 
> I have compiled the packages under ./Clickhouse/build/programs with 2.2G: ![image](https://private-user-images.githubusercontent.com/19272762/334787002-6ecbad48-df00-47f7-8542-5a14c6b14f86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE2MjIsIm5iZiI6MTcxNzc0MTMyMiwicGF0aCI6Ii8xOTI3Mjc2Mi8zMzQ3ODcwMDItNmVjYmFkNDgtZGYwMC00N2Y3LTg1NDItNWExNGM2YjE0Zjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZTFhYmI2ZjA1ZGQ2MTczNjdiNTc1ZGFjMWY2NGRhN2E2MGZmODEyMThhZmFiYzE2ZGUxNjQ0Y2Y0Yzc3MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XkKxF3mCgpEO-yCw8683cGgsF3e9VM_Y5wixcIIPZFI)
> 
> **Expected behavior** If I download pacakge from command `curl https://clickhouse.com/ | sh`, the pacakges about 476MB ![image](https://private-user-images.githubusercontent.com/19272762/334788267-8e7d86b4-9dce-4c2c-9ea0-63085e080ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE2MjIsIm5iZiI6MTcxNzc0MTMyMiwicGF0aCI6Ii8xOTI3Mjc2Mi8zMzQ3ODgyNjctOGU3ZDg2YjQtOWRjZS00YzJjLTllYTAtNjMwODVlMDgwY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMGE4MmQzYWRjMTU3NjU1NWFhOTg3NjRkMDMzZDgzYzU0OTYzNDM0NjFlY2Y2ZTZkODBjNTdjY2MxYzc3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PNxneD56F0of7jksi-CgfEYI7T7Anuh-ND09NUMqTQI)
> 
> So, my question is
> 
> 1. how can we get the smaller package, just like downloading through the script(https://github.com/ClickHouse/ClickHouse/blob/master/docs/_includes/install/universal.sh)
> 2. If I have compile the source code, how can I get the RPM or TAR version of clickhouse, just like github release (https://github.com/ClickHouse/ClickHouse/releases)



> > how can we get the smaller package, just like downloading through the script
> 
> Those files are self-extracting (they are compressed and decompress themselves the first time you run them): `-DENABLE_CLICKHOUSE_SELF_EXTRACTING=1` to cmake.
> 
> > If I have compile the source code, how can I get the RPM or TAR version of clickhouse, just like github release (https://github.com/ClickHouse/ClickHouse/releases)
> 
> Check https://github.com/ClickHouse/ClickHouse/blob/b58a2387ef12e5b18c10b22827063412b0df56e5/packages/build and the build logs of any commit



> **Describe the issue** Platform: AARCH64 Linux: CentOS
> 
> When I follow the offical build guide(https://clickhouse.com/docs/en/development/build), I have successfully compiled the "clickhouse" package, but it is too large comparing with package that can be downloaded from github release or the `https://clickhouse.com/` script
> 
> **How to reproduce**
> 
> Compiling the source code with the following steps:
> 
> ```
> sudo yum update
> sudo yum --nogpg install git cmake make clang python3 ccache lld nasm yasm gawk
> git clone --recursive https://github.com/ClickHouse/ClickHouse.git
> mkdir build
> cmake -S . -B build
> cmake --build build
> ```
> 
> I have compiled the packages under ./Clickhouse/build/programs with 2.2G: ![image](https://private-user-images.githubusercontent.com/19272762/334787002-6ecbad48-df00-47f7-8542-5a14c6b14f86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE2MjIsIm5iZiI6MTcxNzc0MTMyMiwicGF0aCI6Ii8xOTI3Mjc2Mi8zMzQ3ODcwMDItNmVjYmFkNDgtZGYwMC00N2Y3LTg1NDItNWExNGM2YjE0Zjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZTFhYmI2ZjA1ZGQ2MTczNjdiNTc1ZGFjMWY2NGRhN2E2MGZmODEyMThhZmFiYzE2ZGUxNjQ0Y2Y0Yzc3MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XkKxF3mCgpEO-yCw8683cGgsF3e9VM_Y5wixcIIPZFI)
> 
> **Expected behavior** If I download pacakge from command `curl https://clickhouse.com/ | sh`, the pacakges about 476MB ![image](https://private-user-images.githubusercontent.com/19272762/334788267-8e7d86b4-9dce-4c2c-9ea0-63085e080ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE2MjIsIm5iZiI6MTcxNzc0MTMyMiwicGF0aCI6Ii8xOTI3Mjc2Mi8zMzQ3ODgyNjctOGU3ZDg2YjQtOWRjZS00YzJjLTllYTAtNjMwODVlMDgwY2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMGE4MmQzYWRjMTU3NjU1NWFhOTg3NjRkMDMzZDgzYzU0OTYzNDM0NjFlY2Y2ZTZkODBjNTdjY2MxYzc3OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PNxneD56F0of7jksi-CgfEYI7T7Anuh-ND09NUMqTQI)
> 
> So, my question is
> 
> 1. how can we get the smaller package, just like downloading through the script(https://github.com/ClickHouse/ClickHouse/blob/master/docs/_includes/install/universal.sh)
> 2. If I have compile the source code, how can I get the RPM or TAR version of clickhouse, just like github release (https://github.com/ClickHouse/ClickHouse/releases)

Did you get the RPM or TAR version of clickhouse, just like github release (https://github.com/ClickHouse/ClickHouse/releases)？

**Comment by mazhaonan** [comment]
Did you get the RPM or TAR version of clickhouse, just like github release (https://github.com/ClickHouse/ClickHouse/releases)？
