### ISSUE TITLE
MaterializedPostgreSQL replication does not work with upper case letters in database name

### ISSUE THREAD

**Issue by nicetomeetnode** [ClickHouse/ClickHouse#64615]
When my PostgreSQL database name contains both uppercase and lowercase letters, Materialized PostgreSQL synchronization will fail and database synchronization cannot proceed properly

**Comment by kssenii** [comment]
Yes, probably you get this exception: https://github.com/ClickHouse/ClickHouse/blob/6af3b9ac129be9fb928689a7ed21dba43482e282/src/Storages/PostgreSQL/PostgreSQLReplicationHandler.cpp#L80-L83
somewhere in logs. 
You can try to use a setting `materialized_postgresql_use_unique_replication_consumer_identifier = true` to resolve this.

**Comment by nicetomeetnode** [comment]
Based on your suggestion, configure `Materialized_postgresql_use_unique_replication_consumer_identifier=true` to synchronize data with uppercase database names. However, when the stock data of a table is synchronized, the newly added data in the table will not continue to be synchronized, indicating a bug.

**Comment by nicetomeetnode** [comment]
@alexey-milovidov @kssenii @mindreframer @bretthoerner Could you please help me take a look? Thank you

**Comment by kssenii** [comment]
Please check logs for error messages.

**Comment by nicetomeetnode** [comment]
My database name is ```test_djfw``` ,Based on your suggestion, configure Materialized_postgresql_use_unique_replication_consumer_identifier=true to synchronize data with uppercase database names. However, when the stock data of a table is synchronized, the newly added data in the table will not continue to be synchronized.The error message is as follows.Could you please help me take a look? Thank you.
```
<Error> bool DB::MaterializedPostgreSQLConsumer::consume(): std::exception. Code: 1001, type: pqxx::sql_error, e.what() = Failure during '[END COPY]': ERROR:  publication "test_djfw_ch_publication" does not exist
CONTEXT:  slot "5fc174d2_7afa_44a7_a77e_53ea6476a0bb", output plugin "pgoutput", in the change callback, associated LSN 0/DE93FC48
, Stack trace (when copying this message, always include the lines below):
```
@kssenii
