### ISSUE TITLE
TTL not dropping data

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#6462]
I think I have TTL properly configured

```sql
ENGINE = MergeTree 
    PARTITION BY toDate(received_at) 
    ORDER BY received_at 
    TTL received_at + toIntervalDay(1)
```

However my table already contains 13 days of data. 

```
merge_with_ttl_timeout	86400
```

Am I doing something wrong?

Version 19.13.1.11

**Comment by den-crane** [comment]
Is it new table or altered (to add TTL) ?

TTL works only for new parts after alter.

**Comment by simPod** [comment]
It’s altered but like month ago. Still had to delete them manually. So I created the table from scratch with TTL set on creation. It’s not dropping old parts anyway 🤔

**Comment by volfco** [comment]
I've noticed that `ALTER TABLE ... DELETE WHERE ...` seems to have stopped working sometime between 19.8 and19.13

**Comment by simPod** [comment]
I don't think that's related at all.

**Comment by volfco** [comment]
It could be if the internal mechanism used to delete data has broken.

**Comment by simPod** [comment]
The delete works for me.

**Comment by alexey-milovidov** [comment]
The mechanics of ALTER DELETE and TTLs is different.

**Comment by santonuk** [comment]
Hello! I can confirm the bug for ClickHouse server version 19.11.3.

**Scenario to reproduce the problem (current ts is 2019-08-26 14:45:00) :**
`CREATE TABLE default.ttl_test10 (`ts` DateTime, `param` UInt32) ENGINE = MergeTree() PARTITION BY toYYYYMM(ts) ORDER BY ts TTL ts + toIntervalDay(2) ;

INSERT INTO default.ttl_test10 SELECT NOW() - INTERVAL number HOUR, rand() FROM numbers(1000);
OPTIMIZE TABLE default.ttl_test10;

SELECT ts FROM default.ttl_test10 ORDER BY ts ASC; `

**Actual result:** Select returns 433 rows in set (records for a period more than 1 month, records from 2019-07-15  till 2019-07-31 and records from 2019-08-24 till 2019-08-26). Records partially deleted (deleted period starts from 2019-08-01 till 2019-08-23).

**Expected result:** Select returns only records from 2019-08-24 till 2019-08-26. Period till 2019-08-23 should be deleted.

I've repeated the test several times and some time everyting works correctly.

**Comment by filimonov** [comment]
@santonuk your testcase is incorrect. You need to use 
```sql
OPTIMIZE TABLE default.ttl_test10 FINAL;
```
instead of
```sql
OPTIMIZE TABLE default.ttl_test10;
```

**Comment by filimonov** [comment]
> It’s altered but like month ago. Still had to delete them manually. So I created the table from scratch with TTL set on creation. It’s not dropping old parts anyway thinking

merge_with_ttl_timeout  - that says how often cleanups happen. Did you wait such amount of time?

**Comment by filimonov** [comment]
BTW: this feature can be helpful for that too: https://github.com/yandex/ClickHouse/issues/5486

**Comment by simPod** [comment]
> Did you wait such amount of time?

🤔 Yes, it's 86400 (I suppose seconds, 1 day). 

Still deleting data from time to time by hand (script) now.

**Comment by santonuk** [comment]
> @santonuk your testcase is incorrect. You need to use
> 
> ```sql
> OPTIMIZE TABLE default.ttl_test10 FINAL;
> ```
> 
> instead of
> 
> ```sql
> OPTIMIZE TABLE default.ttl_test10;
> ```

Thank you. I agree, OPTIMIZE with FINAL keyword deletes the records. 

The problem persists also for another huge test table: I didn't try OPTIMIZE FINAL, but OPTIMIZE and waiting several days merge_with_ttl_timeout = 86400) but nothing happens. I'll try to simplify it as a test scenario.

**Comment by simPod** [comment]
.

**Comment by ghuname** [comment]
I can confirm that partitions are not dropped in:
ClickHouse client version 19.16.3.6.
Connected to ClickHouse server version 19.16.3 revision 54427.

When you look at system.parts table, you can see a lot of old partitions (before 2020-01-09) that doesn't have any rows, but they remain in system.parts table as well as on file system (daily directory is of size 28k).
Looks like TTL empties old partitions but doesn't delete them (all partition prior 2020-01-09 should be dropped).

optimize table ... final is not helping.

![image](https://user-images.githubusercontent.com/15207713/72140484-2c04ad80-3391-11ea-9ff2-d61e134eb185.png)

Why TTL doesn't drop old partitions?

**Comment by toddyocum** [comment]
I'm also seeing not dropped partitions.

ClickHouse server version 19.14.7 revision 54425.

Here is the Engine part of the output from the 'show create table' command for the table in question

CREATE TABLE default.annotated_flow_local (`timestamp` DateTime,
<snip>
 ENGINE = MergeTree() PARTITION BY toStartOfHour(timestamp) ORDER BY (intHash64(timestamp), timestamp) SAMPLE BY intHash64(timestamp) TTL timestamp + toIntervalHour(24) SETTINGS index_granularity = 8192 │

And 

```
SELECT 
    partition, 
    sum(rows) AS rows
FROM system.parts
WHERE active AND (database = currentDatabase()) AND (table = 'annotated_flow_local')
GROUP BY 
    database, 
    table, 
    partition
ORDER BY 
    database ASC, 
    table ASC, 
    partition ASC

┌─partition───────────┬──────rows─┐
│ 2020-01-10 17:00:00 │         0 │
│ 2020-01-10 18:00:00 │ 198384510 │
│ 2020-01-10 19:00:00 │ 195576430 │
│ 2020-01-10 20:00:00 │ 198362850 │
│ 2020-01-10 21:00:00 │ 197716732 │
│ 2020-01-10 22:00:00 │ 198377670 │
│ 2020-01-10 23:00:00 │ 198362280 │
│ 2020-01-11 00:00:00 │ 198361140 │
│ 2020-01-11 01:00:00 │ 194946786 │
│ 2020-01-11 02:00:00 │ 198377100 │
│ 2020-01-11 03:00:00 │ 198361710 │
│ 2020-01-11 04:00:00 │ 198361710 │
│ 2020-01-11 05:00:00 │ 198362280 │
│ 2020-01-11 06:00:00 │ 198377670 │
│ 2020-01-11 07:00:00 │ 198362280 │
│ 2020-01-11 08:00:00 │ 198361710 │
│ 2020-01-11 09:00:00 │ 198361710 │
│ 2020-01-11 10:00:00 │ 198378240 │
│ 2020-01-11 11:00:00 │ 198361140 │
│ 2020-01-11 12:00:00 │ 198361710 │
│ 2020-01-11 13:00:00 │ 198362280 │
│ 2020-01-11 14:00:00 │ 197343120 │
│ 2020-01-11 15:00:00 │ 198302430 │
│ 2020-01-11 16:00:00 │ 198361710 │
│ 2020-01-11 17:00:00 │ 198361140 │
│ 2020-01-11 18:00:00 │ 198378810 │
│ 2020-01-11 19:00:00 │ 198361710 │
│ 2020-01-11 20:00:00 │ 198362280 │
│ 2020-01-11 21:00:00 │ 198362280 │
│ 2020-01-11 22:00:00 │ 198377670 │
│ 2020-01-11 23:00:00 │ 198361710 │
│ 2020-01-12 00:00:00 │ 198362850 │
│ 2020-01-12 01:00:00 │ 198361140 │
│ 2020-01-12 02:00:00 │ 198378240 │
│ 2020-01-12 03:00:00 │ 198362280 │
│ 2020-01-12 04:00:00 │ 198362280 │
│ 2020-01-12 05:00:00 │ 198361140 │
│ 2020-01-12 06:00:00 │ 198385080 │
│ 2020-01-12 07:00:00 │ 198361140 │
│ 2020-01-12 08:00:00 │ 198362280 │
│ 2020-01-12 09:00:00 │ 198361710 │
│ 2020-01-12 10:00:00 │ 198378240 │
│ 2020-01-12 11:00:00 │ 198362280 │
│ 2020-01-12 12:00:00 │ 198361710 │
│ 2020-01-12 13:00:00 │ 198361710 │
│ 2020-01-12 14:00:00 │ 198378240 │
│ 2020-01-12 15:00:00 │ 198361710 │
│ 2020-01-12 16:00:00 │ 198361710 │
│ 2020-01-12 17:00:00 │ 198362280 │
│ 2020-01-12 18:00:00 │ 198378240 │
│ 2020-01-12 19:00:00 │ 198361140 │
│ 2020-01-12 20:00:00 │ 198361710 │
│ 2020-01-12 21:00:00 │ 198362850 │
│ 2020-01-12 22:00:00 │ 198377100 │
│ 2020-01-12 23:00:00 │ 198362280 │
│ 2020-01-13 00:00:00 │  48690382 │
└─────────────────────┴───────────┘

56 rows in set. Elapsed: 0.243 sec. 
```

**Comment by champtar** [comment]
Hello,

Upgraded a test cluster from 19.7.3.9 (with some data) to 19.14.10.16-lts, then added some more data in existing partitions.
Here is what I tried to use the TTL feature:
- `ALTER TABLE analytics.vme1_shard ON CLUSTER analytics_cluster MODIFY TTL date + INTERVAL 1 DAY;`
- set merge_with_ttl_timeout to 60 in the config file, restart everything
- `OPTIMIZE TABLE analytics.vme1_shard ON CLUSTER analytics_cluster FINAL;` number of part goes to 1 per partition but expired partitions are still not deleted
- `SYSTEM START TTL MERGES`
- `OPTIMIZE TABLE analytics.vme1_shard ON CLUSTER analytics_cluster FINAL;` 
- tried to alter the table again

```
SHOW CREATE TABLE analytics.vme1_shard
CREATE TABLE analytics.vme1_shard (`date` Date, `datetime` DateTime, ........ ENGINE = ReplicatedMergeTree('/clickhouse/tables/{database}/{shard}/{table}', '{replica}') PARTITION BY date ORDER BY (date, toStartOfMinute(datetime), request_file, clientip) TTL date + toIntervalDay(1) SETTINGS index_granularity = 8192
```

```
SELECT 
    table, 
    partition, 
    formatReadableSize(sum(bytes)) AS size, 
    sum(rows) AS nbrows, 
    formatReadableSize(sum(bytes) / sum(rows)) AS SizePerRow, 
    count(*)
FROM system.parts
WHERE active
GROUP BY 
    table, 
    partition
ORDER BY partition ASC

┌─table──────┬─partition──┬─size───────┬────nbrows─┬─SizePerRow─┬─count()─┐
│ vme1_shard │ 2020-01-26 │ 1.00 GiB   │ 192532594 │ 5.59 B     │       1 │
│ vme1_shard │ 2020-01-27 │ 600.59 MiB │  94576631 │ 6.66 B     │       1 │
│ vme1_shard │ 2020-01-28 │ 1.78 GiB   │ 281076422 │ 6.79 B     │       1 │
└────────────┴────────────┴────────────┴───────────┴────────────┴─────────┘
```
We are the 30 so all partition are expired

@den-crane when you say it only works for new parts, should OPTIMIZE FINAL work (it doesn't)?
Or does it only work for new partition ?
Also If I set my TTL to 6 month but then instruction change and I need to keep the data for 1 year, will the partition created when the setting was 6 months be deleted after 6 months even if I altered the table TTL to 1 year in time ?
ie is the TTL expression copied and stored with each part ?

**Comment by champtar** [comment]
```
# cat ./20200126_5946_5946_0/ttl.txt
ttl format version: 1
{"table":{"min":1580083200,"max":1580083200}}
```
So what we would need is a query to update the TTL of existing parts/partitions

**Comment by sunchanglong1991** [comment]
I also encountered the same problem. I modified the ttl of the original table to shorten it, and then used OPTIMIZE FINAL, but the expired data was not deleted

**Comment by DaiDaDao** [comment]
> I also encountered the same problem. I modified the ttl of the original table to shorten it, and then used OPTIMIZE FINAL, but the expired data was not deleted

So do I ,  how about make friend In weixin or QQ, then we can talk about this problem

**Comment by weiyongyuan** [comment]
The same problem!I modified the ttl os the system.trace_log,but the auto ttl doesn't work.
>Here is the table sql:CREATE TABLE system.trace_log (`event_date` Date, `event_time` DateTime, `revision` UInt32, `timer_type` Enum8('Real' = 0, 'CPU' = 1), `thread_number` UInt32, `query_id` String, `trace` Array(UInt64)) ENGINE = MergeTree PARTITION BY toYYYYMM(event_date) ORDER BY (event_date, event_time) TTL event_time + toIntervalDay(2) SETTINGS index_granularity = 8192 
>I modify the ttl of this table about a month ago.BUt it doesn't work.Here is the query result.
┌─toDate(event_time)─┬─toDateTime(min(event_time))─┬─toDateTime(max(event_time))─┬─count()─┐
│         2020-04-02 │         2020-04-02 11:57:05 │         2020-04-02 23:14:12 │  161523 │
│         2020-04-03 │         2020-04-03 09:17:36 │         2020-04-03 15:13:56 │     347 │
│         2020-04-07 │         2020-04-07 09:51:08 │         2020-04-07 23:40:08 │    2024 │
│         2020-04-08 │         2020-04-08 00:10:26 │         2020-04-08 21:29:30 │   91262 │
│         2020-04-09 │         2020-04-09 09:13:45 │         2020-04-09 20:59:21 │   21031 │
│         2020-04-10 │         2020-04-10 12:01:10 │         2020-04-10 21:26:50 │    3400 │
│         2020-04-13 │         2020-04-13 09:36:45 │         2020-04-13 23:59:56 │   18708 │
│         2020-04-14 │         2020-04-14 00:00:01 │         2020-04-14 19:47:53 │   74414 │
│         2020-04-15 │         2020-04-15 09:44:49 │         2020-04-15 23:37:08 │   30432 │
│         2020-04-16 │         2020-04-16 07:50:36 │         2020-04-16 19:33:15 │   24227 │
│         2020-04-17 │         2020-04-17 09:40:24 │         2020-04-17 23:59:01 │   13642 │
│         2020-04-18 │         2020-04-18 00:56:01 │         2020-04-18 23:37:01 │      93 │
│         2020-04-19 │         2020-04-19 00:10:01 │         2020-04-19 23:19:01 │      91 │
│         2020-04-20 │         2020-04-20 01:01:01 │         2020-04-20 23:59:01 │   42440 │
│         2020-04-21 │         2020-04-21 01:00:01 │         2020-04-21 23:59:59 │  357155 │
│         2020-04-22 │         2020-04-22 00:00:00 │         2020-04-22 23:59:02 │   79868 │
│         2020-04-23 │         2020-04-23 00:09:01 │         2020-04-23 23:59:59 │  314007 │
│         2020-04-24 │         2020-04-24 00:00:00 │         2020-04-24 23:59:02 │   94668 │
│         2020-04-25 │         2020-04-25 00:07:01 │         2020-04-25 23:59:02 │    2127 │
│         2020-04-26 │         2020-04-26 00:27:01 │         2020-04-26 23:59:03 │   22282 │
│         2020-04-27 │         2020-04-27 00:01:01 │         2020-04-27 23:59:04 │   73480 │
│         2020-04-28 │         2020-04-28 00:01:01 │         2020-04-28 23:59:01 │   46510 │
│         2020-04-29 │         2020-04-29 00:11:01 │         2020-04-29 23:59:02 │   35240 │
│         2020-04-30 │         2020-04-30 00:06:01 │         2020-04-30 23:59:02 │  204211 │
│         2020-05-18 │         2020-05-18 09:48:01 │         2020-05-18 23:59:01 │   35029 │
│         2020-05-19 │         2020-05-19 00:03:01 │         2020-05-19 09:25:01 │     811 │
└────────────────────┴─────────────────────────────┴─────────────────────────────┴─────────┘

**Comment by guoshuai2016** [comment]
we also have the same issue. what's more, we find that optimize table final after detach and attach the overdue partition, the ttl works. 

BTW, we use the version v19.14.7.15, does upgrade help?

**Comment by alexey-milovidov** [comment]
> BTW, we use the version v19.14.7.15, and does upgrade help?

Calculation of TTL for old data after MODIFY TTL will be available in version 20.5 (that is currently in testing).

**Comment by turningme** [comment]
> > I also encountered the same problem. I modified the ttl of the original table to shorten it, and then used OPTIMIZE FINAL, but the expired data was not deleted
> 
> So do I , how about make friend In weixin or QQ, then we can talk about this problem

Have you solved it ?

**Comment by NikolayPraydkin** [comment]
Создал таблицу как в примере, только интервал удаления через минуту
CREATE TABLE example_table
(
    d DateTime,
    a Int TTL d + INTERVAL 1 minute,
    b Int TTL d + INTERVAL 1 minute,
    c String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(d)
ORDER BY d;

вставил пару строк
insert into example_table values ('2021-01-18 13:12:00', 666,666, 'some');
insert into example_table values ('2021-01-18 13:13:00', 666,666, 'some');
insert into example_table values ('2021-01-18 13:14:00', 666,666, 'some');

данные не удалились!

несколько раз запрос 
optimize table example_table final;
данные не удалились.
версия сервера 20.12.5.14

**Comment by alesapin** [comment]
```
:) CREATE TABLE example_table                                                                                                                                                                     
(                                                                                                                                                                                              
    `d` DateTime,                                                                                                                                                                              
    `a` Int TTL d + toIntervalMinute(1),                                                                                                                                                       
    `b` Int TTL d + toIntervalMinute(1),                                                                                                                                                       
    `c` String                                                                                                                                                                                 
)                                                                                                                                                                                              
ENGINE = MergeTree                                                                                                                                                                             
PARTITION BY toYYYYMM(d)                                                                                                                                                                       
ORDER BY d;
                                                                                                                                                                                   :
:)  insert into example_table values ('2021-01-18 13:12:00', 666,666, 'some');                                                                                                                                                                                                                                            

:)  insert into example_table values ('2021-01-18 13:13:00', 666,666, 'some');                                                                               

:)  insert into example_table values ('2021-01-18 13:14:00', 666,666, 'some');

:)  optimize table example_table final;
               
 :) select * from example_table

┌───────────────────d─┬─a─┬─b─┬─c────┐
│ 2021-01-18 13:12:00 │ 0 │ 0 │ some │
│ 2021-01-18 13:13:00 │ 0 │ 0 │ some │
│ 2021-01-18 13:14:00 │ 0 │ 0 │ some │ 
└─────────────────────┴───┴───┴──────┘
                                                                                                                                                             
```
При поколоночном TTL данные не удаляются, а заменяются на дефолт-выражение (ноль для чисел по умолчанию). Если хотите, чтобы удалялись строки нужно добавить табличный TTL.

**Comment by NikolayPraydkin** [comment]
> select * from example_table

не сбрасывается даже на дефолтное значение.

**Comment by NikolayPraydkin** [comment]
> > select * from example_table
> 
> не сбрасывается даже на дефолтное значение.

 вопрос снимается! создание и запрос optimize делал через DBeaver(вы я так понимаю делали через clickhouse-client.)
Ошибки  не было, но как только указал перед названием таблицы название базы, запрос отработал как ожидалось и значения стали по 0.
