### ISSUE TITLE
Create materialized view from AggregatingMergeTree table 

### ISSUE THREAD

**Issue by yuwei43** [ClickHouse/ClickHouse#64667]
I want to ask you a question：

These are my two tables. I want to use the materialized view from AggregatingMergeTree table   to calculate my totalCount, but the statements written in this way result in a totalCount of 0

DDL:
CREATE TABLE pre_owl_entry_analysis_result_shard_v2 ON CLUSTER qa_apm
(
    `service` LowCardinality(String) CODEC(ZSTD(1)),
    `spanName` LowCardinality(String) CODEC(ZSTD(1)),
    `component` LowCardinality(String) CODEC(ZSTD(1)),
    `spanType` LowCardinality(String) CODEC(ZSTD(1)),
    `analysisTime` DateTime DEFAULT toStartOfFiveMinute(now()) CODEC(Delta(4), ZSTD(1)),
    `maxLatency` AggregateFunction(max, UInt64) CODEC(ZSTD(1)),
    `avgLatency` AggregateFunction(avg, Float64) CODEC(ZSTD(1)),
    `avgQuantiles` AggregateFunction(quantilesTDigest(0.9, 0.95, 0.99), UInt64) CODEC(ZSTD(1)),
    `errorCount` AggregateFunction(sum, UInt64) CODEC(ZSTD(1)),
    `warnCount` AggregateFunction(sum, UInt64) CODEC(ZSTD(1)),
    `slowCount` AggregateFunction(sum, UInt64) CODEC(ZSTD(1)),
    `totalCount` AggregateFunction(count, UInt64) CODEC(ZSTD(1)),
    `time_date` Date DEFAULT today() CODEC(Delta(2), ZSTD(1)),
    `time_date_hour` DateTime DEFAULT toStartOfHour(now())  CODEC(Delta(4), ZSTD(1))
)
ENGINE = AggregatingMergeTree
PARTITION BY (time_date)
ORDER BY (service, component, spanType, time_date_hour, analysisTime, spanName)
TTL time_date + toIntervalDay(14)
SETTINGS index_granularity = 8192;

-- dailyTable
CREATE TABLE pre_owl_entry_analysis_result_daily_shard_v2 ON CLUSTER qa_apm
(
    `service` LowCardinality(String) CODEC(ZSTD(1)),
    `spanName` LowCardinality(String) CODEC(ZSTD(1)),
    `component` LowCardinality(String) CODEC(ZSTD(1)),
    `totalCount` AggregateFunction(count, UInt64) CODEC(ZSTD(1)),
    `time_date` Date DEFAULT today() CODEC(Delta(2), ZSTD(1))
)
ENGINE = AggregatingMergeTree
PARTITION BY (time_date)
ORDER BY (service, component, spanName)
TTL time_date + toIntervalDay(210)
SETTINGS index_granularity = 8192;

CREATE TABLE pre_owl_entry_analysis_result_daily_distributed_v2 ON CLUSTER qa_apm
(
    `service` LowCardinality(String),
    `spanName` LowCardinality(String),
    `component` LowCardinality(String),
    `totalCount` AggregateFunction(count, UInt64) CODEC(ZSTD(1)),
    `time_date` Date DEFAULT today() CODEC(Delta(2), ZSTD(1))
)
ENGINE = Distributed('qa_apm', 'test_apm', 'pre_owl_entry_analysis_result_daily_shard_v2', rand());

--this is MATERIALIZED VIEW 
CREATE MATERIALIZED VIEW pre_owl_entry_analysis_view_daily_v2 ON CLUSTER qa_apm
TO pupuolap.pre_owl_entry_analysis_result_daily_shard_v2
AS
SELECT
    time_date,
    service,
    component,
    spanName,
    countMerge(totalCount) as totalCount
FROM pupuolap.pre_owl_entry_analysis_result_distributed_v2
GROUP BY
    time_date,
    service,
    component,
    spanName;

error:SQL 错误 [70] [07000]: Code: 70. DB::Exception: Conversion from UInt64 to AggregateFunction(count, UInt64) is not supported: while converting source column totalCount to destination column totalCount. (CANNOT_CONVERT_TYPE) (version 23.8.8.20 (official build))

**Comment by den-crane** [comment]
```sql
CREATE MATERIALIZED VIEW pre_owl_entry_analysis_view_daily_v2 ON CLUSTER qa_apm
TO pupuolap.pre_owl_entry_analysis_result_daily_shard_v2 AS
SELECT
   time_date,
   service,
   component,
   spanName,
   countMergeState(totalCount) as totalCount   ----<<<<-----  countMergeState (but actually it's much easier with sum( ) and simpleAggregateFunction
FROM pupuolap.pre_owl_entry_analysis_result_shard_v2  ---<<<<<--
GROUP BY
   time_date,
   service,
   component,
   spanName;
```

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by yuwei43** [comment]
> ```sql
> CREATE MATERIALIZED VIEW pre_owl_entry_analysis_view_daily_v2 ON CLUSTER qa_apm
> TO pupuolap.pre_owl_entry_analysis_result_daily_shard_v2 AS
> SELECT
>    time_date,
>    service,
>    component,
>    spanName,
>    countMergeState(totalCount) as totalCount   ----<<<<-----  countMergeState (but actually it's much easier with sum( ) and simpleAggregateFunction
> FROM pupuolap.pre_owl_entry_analysis_result_shard_v2  ---<<<<<-- shard !!!
> GROUP BY
>    time_date,
>    service,
>    component,
>    spanName;
> ```
> 
> https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf



I really feel it and thank you for your suggestion. I switched to SummingMergeTree to handle it
