### ISSUE TITLE
ANN usearch

### ISSUE THREAD

**Issue by raulcarlomagno** [ClickHouse/ClickHouse#64702]
I am testing usearch ANN provider in ClickHouse
But I would to know if it is possible to upload the records, and then somehow start usearch index creation
to avoid vectors index creation when i am uploading records

@ashvardanian 

thank you so much

**Comment by rschu1ze** [comment]
With standard ClickHouse, any skipping index (including usearch indexes) will be created on newly created and on merged parts.

To disable creation on newly inserted parts, you could [try this PR](https://github.com/ClickHouse/ClickHouse/pull/64391).
