### ISSUE TITLE
HTTP external authenticator not work

### ISSUE THREAD

**Issue by futurexiong** [ClickHouse/ClickHouse#64707]
[https://clickhouse.com/docs/en/operations/external-authenticators/http#enabling-http-auth-in-users-xml](https://clickhouse.com/docs/en/operations/external-authenticators/http#enabling-http-auth-in-users-xml) 
Follow the doc guide, but still can't enable http extenal authentication.
I want to know whether this feature is already in the latest release?

**Comment by yariks5s** [comment]
Hi, @futurexiong! HTTP authentication was done in #55199, we don't document features that we haven't made🙂. Could you provide more context about your issue?
