### ISSUE TITLE
How to get the clickhouse source code for the official build?

### ISSUE THREAD

**Issue by XiaoqiMa** [ClickHouse/ClickHouse#64717]
If I download pacakge from command `curl https://clickhouse.com/ | sh`, I get official build: 24.6.1.2462 on AARCH64 platform
![image](https://github.com/ClickHouse/ClickHouse/assets/19272762/11017021-9a59-402e-8af9-dd7d6549e05e)

But I can only find latest tag on Github for Clickhouse is 24.5.1:
![image](https://github.com/ClickHouse/ClickHouse/assets/19272762/345d330d-d475-4e7a-ae53-b906023d821f)

Secondly, I have tried to compile from source code (tag: v24.3.3.102-lts) on AARCH64 platform, and I have executed some performance tests on Star Schema Benchmar, which is less efficient comparing with the official build (24.6.1.2462). In general, I have executed performance tests on both 24.6.1 version and 24.3.3 versoin, I got huge performance difference (above 10%)

So I have two qeestions: 
1. Where can I find the source code for the official build (24.6.1.2462). Does it comes from `master` branch?
2. I am wondering why there is such a big difference between version 24.3 and 24.6. So, my question is how to compile the offcial build (`compile machine, clang version, compile flags, source code` and etc.) ?

**Comment by XiaoqiMa** [comment]
@Algunenano Could you please help me to clarify a bit?

**Comment by alexey-milovidov** [comment]
```
$ ch -q "SELECT * FROM system.build_options WHERE name = 'GIT_HASH'"
GIT_HASH        997c1963f6096e74ba257a91fcaca52153caeea9
```

997c1963f6096e74ba257a91fcaca52153caeea9

**Comment by XiaoqiMa** [comment]
> SELECT * FROM system.build_options WHERE name = 'GIT_HASH'

Ok, I understand how to find the build version. 

Still, another question still bothers me. I just want to know what's the specific compile machine, clang versionm, compile flags for the official build?

In my case:

[root@master /]# clang --version
clang version 18.1.6
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

Compile commands (I have to disable rust, otherwise it occurs error):
cmake -DENABLE_RUST=OFF -DENABLE_CLICKHOUSE_SELF_EXTRACTING=1 -S . -B build

**Comment by Algunenano** [comment]
All the infrastructure and build details are in the repo itself and in the build logs. You can check https://s3.amazonaws.com/clickhouse-test-reports/0/997c1963f6096e74ba257a91fcaca52153caeea9/clickhouse_build_check/report.html for that specific commit and see which docker image was used, which compiler, which command, etc.

**Comment by XiaoqiMa** [comment]
@Algunenano 

I have checked the build options through command: `select * from system.build_options`. And I found the differences in CMAKE_CXX_FLAGS and CMAKE_C_FLAGS are `-flto=thin -fwhole-program-vtables` I assume these two flags can cause performance difference. 

I have tried to add those two compile flags in CMakeLists.txt just as follows:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -flto=thin -fwhole-program-vtables")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -flto=thin -fwhole-program-vtables")

But the compile process gets stuck just because those two compile flags. How to handle this situation? Do you have any advice?

**Comment by Algunenano** [comment]
The whole build system is scripted and uses docker images. You can simply replicate that if you want to match exactly how the official image is built.
