### ISSUE TITLE
Performance degradation 19.13 comparing to 19.9 

### ISSUE THREAD

**Issue by astudnev** [ClickHouse/ClickHouse#6471]
Most cluster machines are on 19.9.2.4, and 2 of them were migrated to 19.13

The query speed significantly differ ( in 4 times ) 
The same query takes 245.019 sec versus 45.357 on 19.9

I can not replicate the problem, as the servers were downgraded back to 19.9

select sum(value) from ethereum.transfers_from where transfer_from_bin IN (SELECT transfer_to_bin FROM ethereum.transfers_to WHERE value>1e18)

SELECT sum(value)
FROM ethereum.transfers_from
WHERE transfer_from_bin IN
(
SELECT transfer_to_bin
FROM ethereum.transfers_to
WHERE value > 1000000000000000000.
)

┌───────────sum(value)─┐
│ 9.100993546206673e81 │
└──────────────────────┘

1 rows in set. Elapsed: 45.357 sec. Processed 589.67 million rows, 21.82 GB (13.00 million rows/s., 481.02 MB/s.)

ph22/23:
select sum(value) from ethereum.transfers_from where transfer_from_bin IN (SELECT transfer_to_bin FROM ethereum.transfers_to WHERE value>1e18)

SELECT sum(value)
FROM ethereum.transfers_from
WHERE transfer_from_bin IN
(
SELECT transfer_to_bin
FROM ethereum.transfers_to
WHERE value > 1000000000000000000.
)

┌──────────sum(value)─┐
│ 9.10099354620688e81 │
└─────────────────────┘

1 rows in set. Elapsed: 245.019 sec. Processed 589.63 million rows, 21.82 GB (2.41 million rows/s., 89.04 MB/s.)

89 MB/s versus 481 Mb/s

**Comment by den-crane** [comment]
? Column types of  
transfers_from value , transfer_from_bin
transfers_to value, transfer_to_bin

PARTITION BY / ORDER BY of:  transfers_from, transfers_to

**Comment by astudnev** [comment]
CREATE TABLE IF NOT EXISTS ethereum.transfers_from_storage ON CLUSTER all_sharded
(
  tx_date Date,
  tx_time DateTime,

  blockchain_id UInt32,
  block UInt32,

  tx_hash_bin String,
  tx_from_bin String,
  tx_to_bin String,
  transfer_from_bin String,
  transfer_to_bin String,

  currency_id UInt32,
  entity_id UInt64,

  gas_used UInt32,
  gas_price Float32,
  gas_value Float32,

  value Float64,
  external UInt32,
  internal UInt32

) ENGINE = ReplicatedMergeTree('/clickhouse/all_sharded/tables/ethereum/transfers_from_storage/{shard}', '{sharded-replica}')
    PARTITION BY toStartOfMonth(tx_date)
    ORDER BY (transfer_from_bin,tx_date)
    SETTINGS index_granularity=1024;


CREATE TABLE ethereum.transfers_from ON CLUSTER archive_servers
  AS ethereum.transfers_from_storage
    ENGINE = Distributed( 'all_sharded', ethereum, transfers_from_storage, toUInt64(tx_date) );

CREATE TABLE IF NOT EXISTS ethereum.transfers_to_storage ON CLUSTER all_sharded
(
  tx_date Date,
  tx_time DateTime,

  blockchain_id UInt32,
  block UInt32,

  tx_hash_bin String,
  tx_from_bin String,
  tx_to_bin String,
  transfer_from_bin String,
  transfer_to_bin String,

  currency_id UInt32,
  entity_id UInt64,

  gas_used UInt32,
  gas_price Float32,
  gas_value Float32,

  value Float64,
  external UInt32,
  internal UInt32

) ENGINE = ReplicatedMergeTree('/clickhouse/all_sharded/tables/ethereum/transfers_to_storage/{shard}', '{sharded-replica}')
    PARTITION BY toStartOfMonth(tx_date)
    ORDER BY (transfer_to_bin,tx_date)
    SETTINGS index_granularity=1024;

CREATE TABLE ethereum.transfers_to ON CLUSTER archive_servers
  AS ethereum.transfers_to_storage
    ENGINE = Distributed( 'all_sharded', ethereum, transfers_to_storage, toUInt64(tx_date) );

**Comment by 4ertus2** [comment]
What if set optimize_read_in_order=0 ?

**Comment by astudnev** [comment]
> What if set optimize_read_in_order=0 ?

I already downgraded the servers, can not test.

**Comment by den-crane** [comment]
No repro. Stale. I am closing it.
