### ISSUE TITLE
Wrong setting name in 24.5.1 release notes - allow_deprecated_functions doesn't exist, was renamed to allow_deprecated_error_prone_window_functions

### ISSUE THREAD

**Issue by chriscomeau79** [ClickHouse/ClickHouse#64719]
In 24.5.1, after setting allow_deprecated_functions in default profile, server wouldn't start due to presence of invalid setting. 
I removed it, checked available settings and the name is allow_deprecated_error_prone_window_functions.

> <Error> Application: Code: 115. DB::Exception: Setting allow_deprecated_functions is neither a builtin setting nor started with the prefix 'SQL_' registered for user-defined settings: while parsing profile 'default' in users configuration file

```xml
<allow_deprecated_functions>1</allow_deprecated_functions> <!-- according to patch notes-->
<allow_deprecated_error_prone_window_functions>1</allow_deprecated_error_prone_window_functions> <!-- works-->
```

This is outdated in the release notes - setting was renamed here.
https://github.com/ClickHouse/ClickHouse/pull/64358

From https://clickhouse.com/docs/en/whats-new/changelog#-clickhouse-release-245-2024-05-30
> To enable them back, set allow_deprecated_functions = 1 or set compatibility = '24.4' or lower

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/64730
