### ISSUE TITLE
`Timeout exceeded while writing to socket` when pausing reading from socket for more than 30 seconds

### ISSUE THREAD

**Issue by DaanDD** [ClickHouse/ClickHouse#64731]
**Describe what's wrong**

I have a script that performs a long `SELECT` query through the HTTP interface. Every now and then I stop reading from the socket while I keep it open so I can process data. Whenever this time exceeds 30 seconds ClickHouse will throw this error:

```
Code: 209. DB::Exception: Timeout exceeded while writing to socket ([::ffff:x.x.x.x]:12817, 30000 ms): While executing ParallelFormattingOutputFormat. (SOCKET_TIMEOUT) (version 24.4.1.2088 (official build))
```

I have tried increasing every single timeout parameter but this timeout seems to be hardcoded. The only workaround that currently works for me is setting `max_network_bandwidth` to a low enough value.

**Does it reproduce on the most recent release?**

Yes, I am using `version 24.4.1.2088`

**How to reproduce**

Create a users table and fill it up with random data:

```sql
CREATE DATABASE test;

CREATE TABLE test.users (
  `name` String
)
ENGINE = ReplacingMergeTree()
PRIMARY KEY (name)
ORDER BY (name);

INSERT INTO test.users SELECT * FROM generateRandom('name String', 1, 10, 2) LIMIT 100000000;
``` 

Run below Rust code. I also made a repo here: https://github.com/DaanDD/clickhouse-bug
This code will trigger the exception but any code that stops reading from the socket for more than 30 seconds will trigger it.

```rust
use clickhouse::{Client, Row};
use serde::Deserialize;

#[derive(Row, Deserialize, Debug)]
struct User {
    name: String,
}

#[tokio::main]
async fn main() {
    let client = Client::default()
        .with_url("http://localhost:8123")
        .with_database("test")
        .with_user("default")
        .with_password("default");
    // The settings are there to demonstrate that increasing timeout settings doesn't change anything
    let query = client.query("SELECT * FROM users SETTINGS http_receive_timeout=3600, receive_timeout=3600, http_send_timeout=3600, send_timeout=3600");
    let mut cursor = query.fetch::<User>().unwrap();
    while let Some(row) = cursor.next().await.unwrap() {
        println!("{:#?}", row);
        // Stop reading from the socket for 60 seconds, which will trigger `ExceptionWhileProcessing` after 30 seconds
        tokio::time::sleep(std::time::Duration::from_secs(60)).await;
    }
}
```

After 30 seconds `system.query_log` will show that the query crashed.

**Expected behavior**

I would expect ClickHouse to respect the `receive_timeout` and/or `http_receive_timeout` and not throw a timeout after 30 seconds as long as the socket stays open.

**Error message and/or stacktrace**

```sql
SELECT * FROM system.query_log ORDER BY event_time_microseconds DESC LIMIT 100;
```

will contain following information:

```
Code: 209. DB::Exception: Timeout exceeded while writing to socket (x.x.x.x:63688, 30000 ms): While executing ParallelFormattingOutputFormat. (SOCKET_TIMEOUT) (version 24.4.1.2088 (official build))
```

```
0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c9a449b
1. DB::NetException::NetException<String, long>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<long>::type>, String&&, long&&) @ 0x000000000caed62c
2. DB::WriteBufferFromPocoSocket::socketSendBytes(char const*, unsigned long) @ 0x000000000caed2c8
3. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x00000000122d3255
4. DB::WriteBuffer::write(char const*, unsigned long) @ 0x000000000781e52d
5. DB::CompressedWriteBuffer::nextImpl() @ 0x000000000fe424cd
6. DB::ParallelFormattingOutputFormat::collectorThreadFunction(std::shared_ptr<DB::ThreadGroup> const&) @ 0x00000000124acea5
7. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()>(DB::ParallelFormattingOutputFormat::ParallelFormattingOutputFormat(DB::ParallelFormattingOutputFormat::Params)::'lambda'()&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000122e2291
8. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000ca5e62d
9. ? @ 0x00007fe925155609
10. ? @ 0x00007fe925070353
```

**Comment by den-crane** [comment]
system.query_log has `settings` columns, check that this column for settings. 

>SETTINGS http_receive_timeout=3600, receive_timeout=3600, http_send_timeout=3600, send_timeout=3600

It could be that it's possible to set this settings using query SETTINGS, because query contexts is created much earlier.
So you try to pass settings with a client `let client = Client::default()`

**Comment by DaanDD** [comment]
@den-crane How can I do this through the HTTP interface? I tried adding a unique `session_id` parameter to every HTTP request, then I did a `SET http_send_timeout=3600` query with that session id, and finally I tried performing the `SELECT * from users` query. The issue still persists, and the `settings` column from `system.query_log` doesn't contain any timeout settings.

**Comment by den-crane** [comment]
You misunderstood me. There is a way to set settings without a session:

`http://localhost:8123/?http_send_timeout=3600&query=....`

Also you can define settings it in users profiles.

**Comment by den-crane** [comment]
try

```
        .with_url("http://localhost:8123?http_send_timeout=3600")
```

**Comment by den-crane** [comment]
Check does this help or not:

```
cat /etc/clickhouse-server/users.d/http_send_timeout.xml
<?xml version="1.0" ?>
<clickhouse>
    <profiles>
        <default>
            <http_send_timeout>3600</http_send_timeout>
        </default>
    </profiles>
</clickhouse>
```

**Comment by DaanDD** [comment]
@den-crane Tried that already, also doesn't work

**Comment by den-crane** [comment]
> @den-crane Tried that already, also doesn't work

is the error the same? `Timeout exceeded while writing to socket (x.x.x.x:63688, 30000 ms)` ?

**Comment by DaanDD** [comment]
@den-crane Yes it is always the same error message, no matter what I tried

**Comment by den-crane** [comment]
Default's profile setting works me, but only after ClickHouse server restart.

**Comment by DaanDD** [comment]
@den-crane I figured it out, I had added the setting to the user instead of the profile. It works now, thanks a lot!

To be honest, I wish it was more clear which settings are actually doing anything and which aren't. Because adding that parameter to the query settings, the query URL or user settings all gave no errors yet in reality it didn't get applied at all. I was going by [this page](https://clickhouse.com/docs/en/operations/settings/settings) which contains a list of available parameters but it's never mentioned where they should be applied exactly.

**Comment by DaanDD** [comment]
@den-crane That worked, thanks a lot! I accidentally put the setting in the user config instead of the profile. Is there some way to change this timeout only for a session? Because currently I can add this to the query settings, session settings or user settings and it will not show an error but in reality the setting will just not be applied. I was going by [this page](https://clickhouse.com/docs/en/operations/settings/settings), which gives a good overview of all settings but doesn't actually say which settings can be applied where.

**Comment by den-crane** [comment]
I will document that http_send_timeout can be changed only with clickhouse-server restart.

**Comment by TimonSP** [comment]
Yep, you are right, thanks for so fast response.

Will try to find how to update default profile for my Managed Service for ClickHouse

**Comment by hdhoang** [comment]
Hope this helps somebody: We also needed to fix a 30s-time-out `Insert` on CH 23.8, and needed to set `http_send_timeout` because #56035 wasn't backported.

Our error is:

```text
Code: 209.
DB::NetException: Timeout exceeded while reading from socket ($addr, 30000 ms): While executing ParallelParsingBlockInputFormat. (SOCKET_TIMEOUT) (version 23.8.16.1)
```

(input/insert affected by `send` timeout is truly fun)

**Comment by SteZe85** [comment]
@DaanDD I am stuck with the exact same error message: #77005 

Could you help me out by specifiying where you altered the http_send_timeout setting exactly?  I've set http_send_timeout in the settings_profile for my user. I can see the change in `select * from system.settings where changed  -- shows 3600 `  But the error still persists.

**Comment by heartdance** [comment]
> [@TimonSP](https://github.com/TimonSP) it's very minor issue,not relevant to 99.99999999% users. Other 0.0000000001% of users still can tune it.
> 
> Disclaimer: I want to clarify that I am just an ordinary person on the Internet. I have no connection or association with Clickhouse, Inc. or its development team. It is important to note that my opinion holds no value and should not be considered.

This is actually a common problem encountered, such as queries including **regular queries** and **data exports**. 
Regular queries can be configured globally (30 seconds). 
Data exports need to be set to a larger value at the session level, because it may need to wait for data to be written out to other databases (maybe slower).
