### ISSUE TITLE
the annoy index not work

### ISSUE THREAD

**Issue by fresher1chen** [ClickHouse/ClickHouse#64740]
the ann index not work
0,ck version 
     24.4.1
1,creata table 
        CREATE TABLE test.image_search_feature_annoy_v2_local
        (
        `intpc_id` String DEFAULT '' ,
        `feature_mean` Array(Float32) DEFAULT []  ,
        INDEX idx_feature_mean feature_mean TYPE annoy('L2Distance') GRANULARITY 1000000
        )
        ENGINE = MergeTree
        ORDER BY intpc_id ;
2. data 
     insert data the embedding is 512 dim
     insert data quantity 1000000 records
3,sql 
     explain indexes=1 select intpc_id from test.image_search_feature_annoy_v2_local where cosineDistance([...],feature_mean)<0.7;
4,ouput
       ┌─explain─────────────────────────────────────────────────────────────────────┐
    1. │ Expression ((Project names + Projection))                                   │
    2. │   Expression                                                                │
    3. │     ReadFromMergeTree (test.image_search_feature_annoy_v2_local) │
    4. │     Indexes:                                                                │
    5. │       PrimaryKey                                                            │
    6. │         Condition: true                                                     │
    7. │         Parts: 7/7                                                          │
    8. │         Granules: 202/202                                                   │
       └─────────────────────────────────────────────────────────────────────────────┘
    
![image](https://github.com/ClickHouse/ClickHouse/assets/44836806/4cc4a2aa-0155-4aa5-951a-ec7b8549433f)

I'm not sure if the skip index is effective.

I believe that if the index is effective, the EXPLAIN result should be as shown below.
![image](https://github.com/ClickHouse/ClickHouse/assets/44836806/fc0f607e-c8c2-4dbc-b9a2-6074e01cf788)
Are my CREATE TABLE statement or query statement correct?
can you show me how to use the annoy(usearch) index?
Looking forward to your response.

**Comment by CurtizJ** [comment]
The distance function should be the same in index and in `WHERE` condition. You have `annoy('L2Distance')` but `WHERE cosineDistance([...],feature_mean)`.
