### ISSUE TITLE
Different result of `largestTriangleThreeBuckets` between 24.3 and 24.4

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#64745]
https://fiddle.clickhouse.com/2d40e005-e8b2-420b-a022-d5abbd79bbee
```sql
SELECT largestTriangleThreeBuckets(4)(x, y) FROM values('x Float64, y Float64', (0, 1), (1, 2.3), (inf,nan), (6.7,3), (4,4), (5, 1))
```
24.3:
```
[(0,1),(1,2.3),(5,0),(inf,4)]
```
24.4:
```
[(0,1),(1,2.3),(5,1),(6.7,3)]
```

**Comment by nikitamikhaylov** [comment]
The behaviour was changed in this PR https://github.com/ClickHouse/ClickHouse/pull/62646
It aligns the behaviour with some other statistical functions and technically correct. If you have NaNs in the series then theoretically it might be not even sortable.

**Comment by alsugiliazova** [comment]
Thank you for explanation.
