### ISSUE TITLE
Common type and conversion for Interval data types

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#64748]
**Use case**

`(INTERVAL 1 MINUTE) > (INTERVAL 50 SECOND)`

**Describe the solution you'd like**

For Interval types that are one hour or less, implement the `getLeastSuperType` function, which will use the largest Interval type, and implement type conversion functions, which will treat one hour as 60 minutes, one minute as 60 seconds, and milli/micro/nanoseconds accordingly.

We cannot do it for DAY and greater intervals.

**Comment by samuelcolvin** [comment]
Why not ever interval unit less than or equal to a week? They're all strictly multiples of a second/nanosecond (unlike month and year etc).

**Comment by alexey-milovidov** [comment]
A day can be 86400 seconds, but sometimes it is 90000, sometimes 82800 seconds. In some places in Australia, it can be 88200 or 84600 seconds. In Antarctica, it could be even 108000 or 64800 seconds. Other numbers are also recorded in the history.

```
clickhouse-cloud :) WITH toStartOfYear(now()) AS begin, begin + INTERVAL number DAY AS t SELECT DISTINCT dateDiff('SECOND', t, t + INTERVAL 1 DAY, 'Europe/London') FROM numbers(365)

WITH
    toStartOfYear(now()) AS begin,
    begin + toIntervalDay(number) AS t
SELECT DISTINCT dateDiff('SECOND', t, t + toIntervalDay(1), 'Europe/London')
FROM numbers(365)

Query id: 41f28a05-0f1f-40c5-9e74-1a88595bc692

   ┌─dateDiff('SECOND', t, plus(t, toIntervalDay(1)), 'Europe/London')─┐
1. │                                                             86400 │
2. │                                                             82800 │
3. │                                                             90000 │
   └───────────────────────────────────────────────────────────────────┘

3 rows in set. Elapsed: 0.002 sec.
```

**Comment by v01dXYZ** [comment]
@yariks5s Hello, do you still work on this issue ? I would like to take a look at it as it is a fresh `easy-task`.

**Comment by yariks5s** [comment]
@v01dXYZ Hi! Now I have some other tasks in progress so you can try to do this task!🙂
