### ISSUE TITLE
How do you rotate disk encryption key?

### ISSUE THREAD

**Issue by yukha-dw** [ClickHouse/ClickHouse#64743]
Suppose I am using disk configuration below:

```XML
<disks>
  <disk1>
    <type>local</type>
    <path>/path1/</path>
  </disk1>
  <disk2>
    <type>encrypted</type>
    <disk>disk1</disk>
    <path>path2/</path>
    <algorithm>AES_128_CTR</algorithm>
    <key_hex id="0">00112233445566778899aabbccddeeff</key_hex>
    <key_hex id="1">ffeeddccbbaa99887766554433221100</key_hex>
    <current_key_id>0</current_key_id>
  </disk2>
</disks>
```
As my understanding, we just need to add more `key` to the configuration and rotate using `current_key_id` parameter. But, is my old data will be re-encrypted automatically using new `key`? Or I have to keep bunch of old `key` on the configuration?

My concern is if the old data won't be re-encrypted, there is a chance of losing them when losing the old key.

Docs: https://clickhouse.com/docs/en/operations/storing-data#encrypted-virtual-file-system

**Comment by cangyin** [comment]
The `key_id` is save in header of data files, so

> I have to keep bunch of old key on the configuration

Yes!

**Comment by yukha-dw** [comment]
> The `key_id` is saved in header of data files, so
> 
> > I have to keep bunch of old key on the configuration
> 
> Yes!

Woah ok, thank you! Is there any builtin function to re-encrypt them?

**Comment by alexey-milovidov** [comment]
You can do OPTIMIZE FINAL to re-encrypt data with the latest key.
You still cannot remove the old keys because metadata files will continue using them.
