### ISSUE TITLE
Recursive CTE view creation exception.

### ISSUE THREAD

**Issue by Ragaga** [ClickHouse/ClickHouse#64754]
When creating a view with recursive CTE, it give an exception wiht: Unknown table expression identifier....

**Does it reproduce on the most recent release?**
We are using version 24.4.1.2088
But testing with version 24.5.1 gives the same error

**How to reproduce**
Take the recursive CTE example from documentation and wrap it in the view:

```CREATE VIEW test_table_v 
  as 
WITH RECURSIVE test_table AS (
SELECT 1 AS number
 UNION ALL
SELECT number + 1 
  FROM test_table WHERE number < 100
)
SELECT sum(number) 
  FROM test_table
  ```

The same example can be tested here: https://fiddle.clickhouse.com/6e2c3c6b-ece9-466e-b2a4-a44caed06a9a

**Error message and/or stacktrace**

```Received exception from server (version 24.4.1):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table expression identifier 'default.test_table' in scope SELECT number + 1 FROM default.test_table WHERE number < 100. (UNKNOWN_TABLE)
(query: CREATE VIEW test_table_v 
  as 
WITH RECURSIVE test_table AS (
SELECT 1 AS number
 UNION ALL
SELECT number + 1 
  FROM test_table WHERE number < 100
)
SELECT sum(number) 
  FROM test_table)
```

The 'default.test_table' is not a table in `default` schema - it is a CTE and should not have any problems with creating a view.

**Comment by agorobets** [comment]
Any updates on this issue? Got same bug, when I tried create view with dbt.
