### ISSUE TITLE
Missing CSV header with INSERT INTO FUNCTION and CSVWithNames

### ISSUE THREAD

**Issue by panthony** [ClickHouse/ClickHouse#64753]
**Describe what's wrong**

When using `INSERT INTO FUNCTION`, the CSV header is lost when using `CSVWithNames`.

**Does it reproduce on the most recent release?**

Reproduced with:

```
   ┌─version()───┐
1. │ 24.5.1.1763 │
   └─────────────┘
```

**How to reproduce**

* Which ClickHouse server version to use

Reproduced with 24.2, 24.4 and 24.5

* Queries to run that lead to an unexpected result

```sql
INSERT INTO FUNCTION file('taxi_fare.csv') 
SELECT trip_id, trip_distance 
FROM gcs('https://storage.googleapis.com/clickhouse-public-datasets/nyc-taxi/trips_0.gz', 'TabSeparatedWithNames') 
LIMIT 5 
FORMAT CSVWithNames
```

Got as output:

```csv
1199999902,"2.59"
1199999919,"2.4"
1199999944,"5.13"
1199999969,"1.2"
1199999990,"2.17"
```

**Expected behavior**

Expected to have:

```csv
"trip_id","trip_distance"
1199999902,"2.59"
1199999919,"2.4"
1199999944,"5.13"
1199999969,"1.2"
1199999990,"2.17"
```

Same as the output when `INSERT INTO FUNCTION` is not used.

The fact that the header is missing make the output unusable, If I do:

```sql
INSERT INTO FUNCTION file('fare_2.csv') 
SELECT COLUMNS('trip_.*')
FROM gcs('https://storage.googleapis.com/clickhouse-public-datasets/nyc-taxi/trips_0.gz', 'TabSeparatedWithNames')
LIMIT 5
FORMAT CSVWithNames
```

I have no idea what's the output is about.

**Comment by panthony** [comment]
Ok my apologies, trying to dig the documentation further I noticed that we could pass an explicit format & columns:

https://clickhouse.com/docs/en/sql-reference/table-functions/file#write-to-a-tsv-file

I was under the impression that it "inherited" somehow the format @ SELECT clause.

**Comment by den-crane** [comment]
Right, 

```
INSERT INTO FUNCTION
...FORMAT CSVWithNames
```

Format in this context defines the format of the response INSERT query which is sent to the client (initiator of the query).

**Comment by panthony** [comment]
@den-crane Thanks for the precision !
