### ISSUE TITLE
Nested values from kafka using the clickhouse connector

### ISSUE THREAD

**Issue by DavidKranc-TW** [ClickHouse/ClickHouse#64782]
Im Trying to implement the connector, but some of my tables in clickhouse have a nested column.
I saw in the Column.java file that an exception is thrown when encountering this type.
Is there a way to convert the value i recieve or maybe change the format in order to insert the values from the nested object?

**Comment by den-crane** [comment]
there is another github repo for this https://github.com/ClickHouse/clickhouse-kafka-connect/issues

* https://github.com/ClickHouse/clickhouse-kafka-connect/issues/399
