### ISSUE TITLE
clickhouse-keeper-converter Unknown option specified: zookeeper-logs-dir

### ISSUE THREAD

**Issue by kernel288** [ClickHouse/ClickHouse#64780]
Hi 
I used a new version (clickhouse-keeper-converter) and now I am reporting this error.
My zookeeper version 

/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /usr/local/zookeeper/bin/../conf/zoo.cfg
Apache ZooKeeper, version 3.8.4 2024-02-12 22:16 UTC

ClickHouse keeper version 24.3.1.2672 (official build).

Error is 
**I Can't converter to zookeeper snapshot to clickhouse-keeper snapshot** 
===========
`[root@SHPL007 version-2]# clickhouse-keeper-converter --zookeeper-logs-dir /data/zookeeper/data/version-2 --zookeeper-snapshots-dir /data/zookeeper/data/version-2 --output-dir /tmp
Unknown option specified: zookeeper-logs-dir
[root@SHPL007 version-2]# clickhouse-keeper-converter --help
usage: 
clickhouse-keeper-converter [OPTION] [-- [ARG]...]
clickhouse-keeper-converter client [OPTION]
positional arguments can be used to rewrite config.xml properties, for 
example, --http_port=8010

-h, --help                         show help and exit
-V, --version                      show version and exit
-force-recovery, --force-recovery  Force recovery mode allowing Keeper to 
                                   overwrite cluster configuration without 
                                   quorum
-C<file>, --config-file=<file>     load configuration from a given file
-L<file>, --log-file=<file>        use given log file
-E<file>, --errorlog-file=<file>   use given log file for errors only
-P<file>, --pid-file=<file>        use given pidfile
--daemon                           Run application as a daemon.
--umask=mask                       Set the daemon's umask (octal, e.g. 027).
--pidfile=path                     Write the process ID of the application to 
                                   given file.`

**Comment by antonio2368** [comment]
the problem is that the standalone Keeper build doesn't have converter, the help output is for Keeper itself
try downloading the full ClickHouse binary
```sh
curl https://clickhouse.com/ | sh
```
and then run `clickhouse keeper-converter`.

**Comment by kernel288** [comment]
> the problem is that the standalone Keeper build doesn't have converter, the help output is for Keeper itself try downloading the full ClickHouse binary
> 
> ```shell
> curl https://clickhouse.com/ | sh
> ```
> 
> and then run `clickhouse keeper-converter`.

thank u so mush .It's work

**Comment by SaltTan** [comment]
> the problem is that the standalone Keeper build doesn't have converter, the help output is for Keeper itself try downloading the full ClickHouse binary
> 
> ```shell
> curl https://clickhouse.com/ | sh
> ```
> 
> and then run `clickhouse keeper-converter`.

why does the standalone build exist if we need to install the full binary anyway?
https://github.com/ClickHouse/ClickHouse/issues/56477

**Comment by antonio2368** [comment]
The point of standalone build as its name suggests is Keeper only build with everything else stripped away to minimize the size.
But in general standalone gave as more trouble so it will most likely be removed and replaced with full binary.

>  if we need to install the full binary anyway

who said you need to install anything? Binary can be downloaded and used as is.
