### ISSUE TITLE
Support dropping all tables within a database

### ISSUE THREAD

**Issue by devurandom** [ClickHouse/ClickHouse#64799]
**Use case**

Empty a database from all its tables.

**Describe the solution you'd like**

Something like `DROP TABLE dbname.*`

**Describe alternatives you've considered**

* `SHOW TABLES IN dbname` and then `DROP TABLE dbname.tablename` for each
  - Cumbersome and prone to race conditions
* `DROP DATABASE dbname` followed by `CREATE DATABASE dbname`
  - User might lack permissions

**Additional context**

Dropping multiple tables is already possible: https://github.com/ClickHouse/ClickHouse/issues/50572
This might be the next step.

**Comment by Algunenano** [comment]
CH has (`TRUNCATE DATABASE`](https://clickhouse.com/docs/en/sql-reference/statements/truncate#truncate-database) for this exact case.

**Comment by devurandom** [comment]
> CH has [`TRUNCATE DATABASE`](https://clickhouse.com/docs/en/sql-reference/statements/truncate#truncate-database) for this exact case.

Thanks for your quick response!

`TRUNCATE DATABASE` appears to need `DROP DATABASE` permission, while I would expect `DROP TABLE` permission to be enough since I only drop tables, but not actually the whole database:
```
Not enough privileges. To execute this query, it's necessary to have the grant DROP DATABASE ON default.*. (ACCESS_DENIED)
```

**Comment by devurandom** [comment]
> Would it be possible to reopen this issue under the new scope of reducing the privilege requirement for `TRUNCATE DATABASE` to not require `DROP DATABASE db` but only `DROP TABLE db.*`?

Since I received no response here, I opened a new issue: https://github.com/ClickHouse/ClickHouse/issues/68903
