### ISSUE TITLE
Incorrect date format can be incorrectly parsed in comparison condition.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6481]
Example: 
```
SELECT count() FROM merge.hits_v2 WHERE EventDate > '07-08-2019'
```

This query attempts to process all records in a table.

**Comment by erikdubbelboer** [comment]
This is very dangerous. I just did an `ALTER TABLE table DELETE WHERE a = 'b' AND date >= '18-08-2020';` which delete much more data than expected. I know that for parsing speed wrong dates don't throw errors but it would be so much better if for constants in queries it did throw an error. Here speed doesn't matter as a query doesn't contain millions of constants. Especially for `ALTER TABLE` queries a wrongly formatted date should really throw an error!
