### ISSUE TITLE
pqxx: Can not parse numeric value: `-1.738338951958751e-308`

### ISSUE THREAD

**Issue by Nican** [ClickHouse/ClickHouse#64851]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

Version 24.5.1.1763

> You have to provide the following information whenever possible.

**Company or project name**
Personal project.

> Put your company name or project description here

**Describe what's wrong**

Run this code in Postgres:
```sql
create table my_table(
a float8
);

insert into my_table VALUES(-1.738338951958751e-308);
```

Run this code in Clickhouse
```sql
create table my_table(
  a Float64
) Engine=MergeTree
order by a;

insert into my_table
SELECT * from postgresql('postgres:5432', 'postgres', 'my_table',  'admin', 'password')
```

I get the following error: 
```
SQL Error [1002] [07000]: std::exception. Code: 1001, type: pqxx::conversion_error, e.what() = 
Could not convert string to numeric value: '-1.738338951958751e-308'. (version 24.5.1.1763 (official build))
```

> A clear and concise description of what works not as it is supposed to.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

Latest version on docker.

**Expected behavior**

To import the data into ClickHouse. 

**Additional information**

I am having a hard time reproducing the behavior. 

The PQXX source code: https://github.com/jtv/libpqxx/blob/master/src/strconv.cxx#L531 
The sample C++ Code: https://godbolt.org/z/eWeMMPbcf  https://godbolt.org/z/5aca9bM8a

**Comment by Nican** [comment]
Upon further investigation- it loos like that the compiler flag `-stdlib=libc++` does it.

**Comment by Nican** [comment]
My current work-around is to use a SQL view on the postgres side that uses the `ROUND` function to get all values to the nearest 1E-300 value.

**Comment by jsc0218** [comment]
It is not a bug in CH. Actually the number you give is also out of range in Postgres, even though it shows correctly but risky, see explanation [here](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-FLOAT).

**Comment by Nican** [comment]
@jsc0218 
The postgres documentation is not exactly precise. The limits just seem to be "around" those values: `range of around 1E-307 to 1E+308`. It is unclear what is supposed to mean. 

There exists a valid IEEE754 64-bit binary representation for that value: https://www.binaryconvert.com/result_double.html?hexadecimal=800C800000000000 - so I personally do not see anything wrong with the value itself.

The pqxx source code is pretty straight forward, and the problem seems to be rooted in the way that stdc++ library parses the value. I would imagine that other parts of Clickhouse that use `std::stringstream` would also have a problem parsing that particular number.

I am unsure how to proceed with this issue though.

**Comment by Nican** [comment]
I did some searching around and I got nothing. 

I guess I could try blaming Pqxx, but that would just be blaming stdc++, since they are using that to parse the number.

I have a work around that works for me.
