### ISSUE TITLE
Questions about data durability on insert and background merging process.

### ISSUE THREAD

**Issue by rcrestey** [ClickHouse/ClickHouse#64906]
**Question**

Hello,

I have some questions concerning the data durability of clickhouse:

1) On data insertion system:

As I understood (and please correct me if I’m wrong),  without “async_insert” enabled, each batch insert is directly written as a ‘part’ to the file system, not yet physically on disk but on system cache.

Once written on file system (system cache), ack is sent confirming the data has been written.

But at this moment, before flushing system cache to physical disk, if a crash or power loss happen, then we lose the data that was remaining in system cache, not yet flushed to disk, from the insert we received the ack for ?

I saw that [`fsync_after_insert`](https://clickhouse.com/docs/en/engines/table-engines/special/distributed#fsync_after_insert) could force the system to ‘flush’ the inserted data on disk but of course, reduce the performance.

If using `fsync_after_insert` is the ack sent after the `fsync_after_insert` operation, meaning is ack sent only when data is physically written to disk (to ensure accurate durability of the data inserted) ?

it is stated `fsync_after_insert:  do the fsync for the file data after background insert to Distributed. Guarantees that the OS flushed the whole inserted data to a file on the initiator node disk.` but I don’t understand the ‘Distributed’ meaning: is it working only for clustered clickhouse nodes, or is it also working for insert on a single node ?

More generally, what is the correct setup to ensure no data loss nor data corruption for an insert on a single node ?

2) On merging system and in-memory/wal:

2.1 On wal:
I’ve seen some external article talking about clickhouse WAL ( [example](https://medium.com/@ShivIyer/how-prefetching-works-during-wal-recovery-in-clickhouse-129519f41a4c) )
And seen it on [release notes](https://clickhouse.com/docs/en/whats-new/changelog/2020#improvement-12) too, stating a `in_memory_parts_enable_wal` parameter.

Is this still in used today ? If not using `async_insert`, parts are not wrote in memory(except system cache) correct ?

Is there is WAL like system used on the parts merging process and Is there a way data could be corrupted or loss during this background merging process on a default clickhouse configuration ?

2.2 On merging system:

As I understood from the ([`old-parts-lifetime` docs](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#old-parts-lifetime)), background merging system will merge parts and store them in filesystem without `fsync` call, so until the system itself flush its system cache to disk, the new parts will stay in system cache, which can lead in data loss if the inactive parts are deleted before, correct ?

As said in [`old-parts-lifetime` docs](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#old-parts-lifetime):
`The default dirty_expire_centisecs value (a Linux kernel setting) is 30 seconds (the maximum time that written data is stored only in RAM), but under heavy loads on the disk system data can be written much later. Experimentally, a value of 480 seconds was chosen for old_parts_lifetime, during which a new part is guaranteed to be written to disk.`

When I see `under heavy loads on the disk system data can be written much later.` I wonder if there is a limit to this time ? How did you get the default `480 seconds`, and is this configuration can "guarantee" no data loss on heavy loads, or is there any other time to set for `old-parts-lifetime` that would guarantee no data loss, even on important heavy loads ?

Thanks a lot for your time and consideration.

**Comment by CurtizJ** [comment]
> As I understood (and please correct me if I’m wrong), without “async_insert” enabled, each batch insert is directly written as a ‘part’ to the file system, not yet physically on disk but on system cache.

Yes.

> But at this moment, before flushing system cache to physical disk, if a crash or power loss happen, then we lose the data that was remaining in system cache, not yet flushed to disk, from the insert we received the ack for ?

Yes. For non-replicated `MergeTree` table and if data has not been replicated yet, it may be lost.

> If using fsync_after_insert is the ack sent after the fsync_after_insert operation, meaning is ack sent only when data is physically written to disk (to ensure accurate durability of the data inserted) ?

Yes.

> it is stated fsync_after_insert:  do the fsync for the file data after background insert to Distributed. Guarantees that the OS flushed the whole inserted data to a file on the initiator node disk. but I don’t understand the ‘Distributed’ meaning: is it working only for clustered clickhouse nodes, or is it also working for insert on a single node ?

`fsync_after_insert` is a table engine setting. It can be applied to both `MergeTree` and `Distributed` tables. Unfortunetly it looks like it is not documented in the [section](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/mergetree#settings) of `MergeTree `settings.

> More generally, what is the correct setup to ensure no data loss nor data corruption for an insert on a single node ?

You can set `fsync_after_insert` for `MergeTree` tables.

> I’ve seen some external article talking about clickhouse WAL ( [example](https://medium.com/@ShivIyer/how-prefetching-works-during-wal-recovery-in-clickhouse-129519f41a4c) )

This article is apparently generated by GPT model and has nothing common with reality. As well as all publication about ClickHouse by Shiv Iyer and ChistaDATA. There was a WAL for in-memory data parts in ClickHouse, but this feature is deprecated and removed from recent releases. So there is no WAL now.

> so until the system itself flush its system cache to disk, the new parts will stay in system cache, which can lead in data loss if the inactive parts are deleted before, correct ?

Yes.

> I wonder if there is a limit to this time?

I think no. It really depends on disk specification and current load. 

> How did you get the default 480 seconds

I think it is chosen from the experience of operation of ClickHouse. With this setting the data loss never happened under some high load in production or in benchmark. Theoretically, there is no guarantee.  

If you really want to ensure durability after merges you can tune settings `min_rows_to_fsync_after_merge` and `min_compressed_bytes_to_fsync_after_merge` of `MergeTree` tables. You need to set them to non 0 values because 0 means "disabled".

Note that all fsync settings may negatively impact the performance and you have to test them on your usecase.

**Comment by den-crane** [comment]
About merges, now big merges write directly to the disk (it does not provide a full guarantee)

min_merge_bytes_to_use_direct_io      10737418240 Minimal amount of bytes to enable O_DIRECT in merge (0 - disabled).

**Comment by rcrestey** [comment]
Hi,

Thanks for the detailed response and the reactivity.

@CurtizJ about `min_rows_to_fsync_after_merge` and `min_compressed_bytes_to_fsync_after_merge`:
If I well understood, when a background merge happen, it generates new parts, and only the new parts who have more than `min_rows_to_fsync_after_merge` rows or bigger than `min_compressed_bytes_to_fsync_after_merge` are fsync to disk ? Is the fsync_after_merge is guarantee despite heavy loads or "external factors" ?

In `min_compressed_bytes_to_fsync_after_merge` what `compressed_bytes` stand for exactly ? Why not `min_bytes_to_fsync_after_merge` for example ? When does the "uncompressed_bytes" to "compressed_bytes" happen ?


@den-crane about `min_merge_bytes_to_use_direct_io`:
So a set of parts merged into a new part bigger than `min_merge_bytes_to_use_direct_io` will lead clickhouse to use O_DIRECT to write this new part ?
What is the difference between O_DIRECT writing and fsync writing ? From what I've found, it seems that writing with O_DIRECT allows storage device to use their internal storage cache where fsync forces to write on true physical disk ? 
Is it the reason why you've said that "it does not provide a full guarantee" ?

Let's say `min_rows_to_fsync_after_merge` and `min_merge_bytes_to_use_direct_io` are activated and a new part validate both ( bigger than `min_merge_bytes_to_use_direct_io` and contain more rows than `min_rows_to_fsync_after_merge` ), what happen in this case, is this two setting enabled in the same time can cause problems / useless io interactions ?

Thanks a lot !!

**Comment by CurtizJ** [comment]
> it generates new parts, and only the new parts who have more than min_rows_to_fsync_after_merge rows or bigger than min_compressed_bytes_to_fsync_after_merge are fsync to disk ? Is the fsync_after_merge is guarantee despite heavy loads or "external factors" ?

Yes.

> In min_compressed_bytes_to_fsync_after_merge what compressed_bytes stand for exactly ? Why not min_bytes_to_fsync_after_merge for example ? When does the "uncompressed_bytes" to "compressed_bytes" happen ?

Compressed bytes - amount of bytes written to disk after compression. Uncompressed bytes - amount of bytes after decompression in memory. The setting is named with prefix "compressed" to disambiguate, it doesn't make a lot of sense. For example in `system.parts` table there are two columns:  `data_compressed_bytes` and `data_uncompressed_bytes`.

**Comment by rcrestey** [comment]
Thanks @CurtizJ !

I don't currently understand the process of uncompressed/compressed bytes lifecycle and I want to be sure that using `min_compressed_bytes_to_fsync_after_merge` will be applied to what I think:


My current understanding: only the original parts, created to store data from insert, contains uncompressed bytes; the compression happens on the merging of the originals parts to new parts, each new part resulting not from an insert but from a merge contains only compressed bytes, so `min_compressed_bytes_to_fsync_after_merge` count the bytes of each part resulting from a merge ?


> amount of bytes written to disk after compression

Is there some possible amount of bytes written to filesystem uncompressed ? 
Can a part, resulting from a merge, contains uncompressed bytes, and so not taken into account by `min_compressed_bytes_to_fsync_after_merge` ?



> Uncompressed bytes - amount of bytes after decompression in memory


I see in the [docs](https://clickhouse.com/docs/en/operations/system-tables/parts_columns) : 
`
data_uncompressed_bytes (UInt64) — Total size of uncompressed data in the data part.
`
I'm not sure to understand: `after decompression in memory`: Does this means that uncompressed data can be stored only in filesystem(system cache), in memory, but not on filesystem(disk) ? Or else all data are compressed when written to filesystem and are uncompressed only on read, but then it invalidates `data_uncompressed_bytes` as no part would contain uncompressed_bytes ? 

Thanks for the clarification.

**Comment by rcrestey** [comment]
Other points on replication:


1 -  About `min_compressed_bytes_to_fsync_after_fetch`:

Stated as ` Minimal number of compressed bytes to do fsync for part after fetch`.

Please correct me if I'm wrong:

Let `node1` and `node2`, two clickhouse replicas, 
When `node1` fetches parts from `node2`:
-  `node1` fsync all received parts from current fetch who are bigger or equal `min_compressed_bytes_to_fsync_after_fetch` 
- all fetched parts smaller than `min_compressed_bytes_to_fsync_after_fetch` are stored in `node1` filesystem, the data in those parts will be fsync to `node1` disk when the new parts resulting from the merging of those fetched parts will equal or exceed`min_compressed_bytes_to_fsync_after_merge`  ?


Have you any recommendation on settting `min_compressed_bytes_to_fsync_after_merge` and `min_compressed_bytes_to_fsync_after_fetch` to guarantee true durability on `node1` and `node2` ? (ex: If we set these two settings with the same value, does it reduce probability of error, improve reliability, lead to smoother internal work, etc ?)

2 - `fsync_directories`:

`do the fsync for directories. Guarantees that the OS refreshed directory metadata after operations related to background inserts on Distributed table (after insert, after sending the data to shard, etc.).`

`background inserts` -> when fetching parts already inserted in another replica, in the example when `node1` fetches an insert done in `node2` it is called a `background inserts` ?

What are the `directories` stated in `fsync_directories` description that will be fsync ? On which replica ?

If an insertion happens in `node2` and `fsync_directories` is enabled, then what `fsync_directories` do exactly in `node1` / `node2` ?


3. Fetch lifecycle:

When fetches between replicas happen ?
Do they happen only when another replica has done an insert / update/delete, 
or also when another replica has done an internal merge ?


Thanks a lot.
