### ISSUE TITLE
ZK Outstanding_requests

### ISSUE THREAD

**Issue by yyfyfyang** [ClickHouse/ClickHouse#64902]
### Question

My ck uses zk underneath，zk has always had about 200 outstanding requests，But zk's cpu usage is low and the underlying metrics are healthy
this is zk cpu util
![WechatIMG7387](https://github.com/ClickHouse/ClickHouse/assets/96812658/35f72746-1597-4995-b7c8-3b5073463950)
this is outstanding requests
<img width="480" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/96812658/482441e3-139c-401d-9860-992d7011b175">
I want to know where the bottleneck of my zk is

**Comment by Algunenano** [comment]
You can check the ZK info with the `reqs` or `dump` 4 letter word commands and see what the requests are.

**Comment by den-crane** [comment]
from my experience Outstanding_requests is absolutely worthless metric in ApacheZookeeper.

One of my production  Zookeeper: 
<img width="1375" alt="Screenshot 2024-06-06 at 1 16 49 PM" src="https://github.com/ClickHouse/ClickHouse/assets/19737682/1073047b-54cf-4d02-89bb-4b371c269332">

How does this affect users or Clickhouse? It doesn’t affect at all. Why it has changed? A hoster replaced a network router firmware, it reduced the latency from 1ms to 0.5ms.
