### ISSUE TITLE
Changed behaviour for MV with incorrect select between old and new analyzer

### ISSUE THREAD

**Issue by fm4v** [ClickHouse/ClickHouse#64917]
**Describe the unexpected behaviour**
The new analyzer behavior immediately informs the user when they do something wrong during MV creation. However, in terms of ClickHouse version upgrades, this is going to be a real pain because of incorrect configurations.

Example: 
Create an MV with an unsupported argument (DateTime) in the function `JSONExtract(data, 'test', 'DateTime64(3)')`
With the analyzer disabled, the MV will be created but will throw an error on insert.
With the analyzer enabled, the MV will not be created.

**How to reproduce**
https://fiddle.clickhouse.com/4f50ff9a-08c7-49d5-9507-68b1e4ede7e1

```
create table source (data String) ENGINE=MergeTree order by tuple();
set allow_experimental_analyzer=0;
select 'disabled - MV is created but insert fail';
create materialized view source_view ENGINE=MergeTree() order by tuple() as select JSONExtract(data, 'test', 'DateTime64(3)') from source;

-- serverError  insert into source values ('1'); 

set allow_experimental_analyzer=1;
select 'enabled - fail on create';
create materialized view source_view2 ENGINE=MergeTree() order by tuple() as select JSONExtract(data, 'test', 'DateTime64(3)') from source;

/* Result:
Received exception from server (version 24.4.1):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Function JSONExtract doesn't support the return type schema: DateTime64(3). (ILLEGAL_TYPE_OF_ARGUMENT)
(query: create materialized view source_view2 ENGINE=MergeTree() order by tuple() as select JSONExtract(data, 'test', 'DateTime64(3)') from source;)
*/
```

Version 24.2+

**Comment by novikd** [comment]
The new analyzer forbids invalid queries. See PR with documentation: #64643.

**Comment by Algunenano** [comment]
I'm doing some tests to ensure that things are compatible in the following corner cases:
* Create a bad MV without the analyzer. Restart with the analyzer. Works fine.
* Create a bad MV on cluster (replicatedmergetree, atomic databases) (analyzer on in both, off in both, on vs off, off vs on)
* Create a bad MV on replicated database (analyzer on in both, off in both, on vs off, off vs on)

Basically verify that independently on the settings (as long as analyzer is set to some value), things will be consistent (fail everywhere or work everywhere).

**Comment by Algunenano** [comment]
1. Worked fine. The server starts without problems.
2. If you attempt to create the MV ON CLUSTER in the server where the analyzer in on, you get `ILLEGAL_TYPE_OF_ARGUMENT` and the view is not created anywhere. If you attempt to create it in the server with the analyzer is off, it's created in both servers (no matter if the other server has it on or off).
3. Same behavior with the Replicated database engine. Analyzer=0 allows the creation (and it will propagate correctly), while analyzer=1 will prevent it.

So everything is working as expected.
