### ISSUE TITLE
Unable to attach clickhouse table back

### ISSUE THREAD

**Issue by shobhit-zepto** [ClickHouse/ClickHouse#64920]
### Question

I modified the table in clickhouse and detached it. Now unable to attach it back as the default value for a column which depends on another column was dropped.

ClickHouse server version: 23.8.14.6

**How to reproduce**

* Created new column `ALTER TABLE impressions ADD COLUMN bid_value_su Nullable(Float64) DEFAULT bid_value * 100`
* Renamed to original `ALTER TABLE impressions
    RENAME COLUMN bid_value TO bid_value_old,
    RENAME COLUMN bid_value_su TO bid_value,
    DROP COLUMN bid_value_old;`
* Detached the table by mistake `DETACH table impressions`

Fixes tried
* Attaching back throws error `Missing columns: 'bid_value_old' while processing query:`
* Attaching the table with modified contract and uuid gives error `Mapping for table with UUID={UUID} already exists.`

How can I keep my data and table intact and get it back? This is a ReplacingReplicatedMergeTree.

**Comment by CurtizJ** [comment]
> Attaching back throws error Missing columns: 'bid_value_old' while processing query:

Please show the query and full stacktrace.
