### ISSUE TITLE
DROP TABLE wait/hangs indefinitely when executed on a cluster

### ISSUE THREAD

**Issue by joelwurtz** [ClickHouse/ClickHouse#64921]
After creating JOIN table, we try to drop them but it hangs up indefinitely (it's not always the case), we got the following error (not sure if this is really helpful) : 

```
2024.06.06 16:40:08.299208 [ 3745702 ] {b0ff61e6-7aa1-437a-a338-9570911c3742} <Error> executeQuery: Code: 159. DB::Exception: Distributed DDL task /clickhouse/task_queue/ddl/query-0000002610 is not finished on 1 of 2 hosts (0 of them are currently executing the task, 0 are inactive). They are going to execute the query in background. Was waiting for 180.286476573 seconds, which is longer than distributed_ddl_task_timeout. (TIMEOUT_EXCEEDED) (version 24.5.1.1763 (official build)) (from 127.0.0.1:41402) (in query: DROP TABLE IF EXISTS table_name ON CLUSTER `{cluster}`;), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c5c4fbb
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000077960ec
2. DB::Exception::Exception<String&, unsigned long&, unsigned long, unsigned long&, unsigned long, double, char const*>(int, FormatStringHelperImpl<std::type_identity<String&>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type, std::type_identity<unsigned long&>::type, std::type_identity<unsigned long>::type, std::type_identity<double>::type, std::type_identity<char const*>::type>, String>
3. DB::DDLQueryStatusSource::generate() @ 0x0000000010e1b762
4. DB::ISource::tryGenerate() @ 0x0000000011ef8415
5. DB::ISource::work() @ 0x0000000011ef7ea2
6. DB::ExecutionThreadContext::executeTask() @ 0x0000000011f11d27
7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x0000000011f06610
8. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x0000000011f05aa2
9. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000011f1584a
10. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c676f83
11. ? @ 0x00007f544c189134
12. ? @ 0x00007f544c2097dc
```

**How to reproduce**

* Versions of clickhouse and keeper:
 * Server : ClickHouse client version 24.5.1.1763
 * Keeper : ClickHouse keeper version 24.5.1.1763

**Complete process from create table to drop table**

Create table is done with the following statements : 

```sql
CREATE TABLE IF NOT EXISTS table_name ON CLUSTER `{cluster}`
(
    `url` String,
    `count` UInt32
)
ENGINE = Join(ANY, LEFT, url)
SETTINGS join_use_nulls = 1;
```

Then there may be insert or not (but does not change anything) as it hang on both cases.

In our case the table is empty : 

![image](https://github.com/ClickHouse/ClickHouse/assets/90466/297bcf97-d2bb-4b90-9c1b-13c8ac408d74)

After this insert we use those data to update data in another table, by doing the following statement: 

```sql
ALTER TABLE another_table ON CLUSTER `{cluster}`
UPDATE logCount = joinGet(table_name, 'count', url)
WHERE
     projectId = toUUID(:projectId)
     AND crawlId = toUUID(:crawlId)
     AND logCount IS NOT NULL
     AND joinGet(table_name, 'count', url) IS NOT NULL
SETTINGS allow_nondeterministic_mutations = 1, mutations_sync = 2;
```

We allow this query, because at this point we are 100% sure there will be no write on this table anymore.

Then we drop this table (normally it's not a problem since we use sync in this case so data has been updated)

```sql
DROP TABLE IF EXISTS table_name ON CLUSTER `{cluster}`;
```

**Error message and/or stacktrace**

When trying to do it on the clickhouse-client, it hangs on this step :

![image](https://github.com/ClickHouse/ClickHouse/assets/90466/0eb7c0e3-dc4b-4505-9902-f8584138bfef)

**Additional context**

FYI it works if we drop the table without doing it on the cluster `DROP TABLE IF EXISTS table_name;`, is there some risks doing this ?

**Comment by Algunenano** [comment]
> When trying to do it on the clickhouse-client, it hangs on this step :

It's waiting for the other replica to drop the table, which apparently is not currently active.

> FYI it works if we drop the table without doing it on the cluster DROP TABLE IF EXISTS table_name;, is there some risks doing this ?

The table will only be dropped in the replica that receives the query.

**Comment by joelwurtz** [comment]
In fact it appears it was a ddl issue, some task was hanging due to something bad on our side, was a bit difficult to debug but we resolved this issue, will close this as i don't think this is relevant anymore.
