### ISSUE TITLE
The NETWORK_ERROR occurs frequently

### ISSUE THREAD

**Issue by YYXXYYZZ** [ClickHouse/ClickHouse#64954]
Hello, community friends:

After upgrading our cluster to version 24.3.3.102, we began to experience NETWORK_ERROR very frequently. This problem is exacerbated when there are large queries. I can be certain that there is no issue with the network between our clusters, as this has been confirmed through various monitoring tools. When the NETWORK_ERROR occurs, it is not just one replica in the cluster that errs but multiple ones. Any suggestions?

logs:

> 2024-06-06-203232 | 2024-06-06T12:32:32.096790623Z stderr F 2024.06.06 12:32:32.096698 [ 6011 ] {7fcd3c0b-8ed4-4d2c-8301-f1e6bb3c5613} <Information> HedgedConnectionsFactory: Connection failed at try №1, reason: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (xxx:47088 -> yyy:9000). (NETWORK_ERROR) (version 24.3.3.102 (official build)) 
>  2024-06-06-203121 | 2024-06-06T12:31:21.354966108Z stderr F 2024.06.06 12:31:21.354860 [ 6034 ] {670ac06d-e112-4e5a-9ab0-a814e994a7ea} <Information> HedgedConnectionsFactory: Connection failed at try №1, reason: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (zzzz:48928 -> qqqq:9000). (NETWORK_ERROR) (version 24.3.3.102 (official build)) 
> 2024-06-06-203117 | 2024-06-06T12:31:17.160913009Z stderr F 2024.06.06 12:31:17.160822 [ 6552 ] {} <Error> ServerErrorHandler: Code: 210. DB::NetException: Connection reset by peer, while reading from socket ([::ffff:???????]:54298). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):
> 2024-06-06T12:31:17.160965982Z stderr F  (version 24.3.3.102 (official build))
> 2024-06-06T12:31:17.16096345Z stderr F 10. ? @ 0x00007f39c626b353
> 2024-06-06T12:31:17.160960789Z stderr F 9. ? @ 0x00007f39c6346609
> 2024-06-06T12:31:17.160957963Z stderr F 8. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d9341d
> 2024-06-06T12:31:17.160955813Z stderr F 7. Poco::PooledThread::run() @ 0x0000000014d94e81
> 2024-06-06T12:31:17.160953524Z stderr F 6. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9c719
> 2024-06-06T12:31:17.160951296Z stderr F 5. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9b8d2
> 2024-06-06T12:31:17.160949102Z stderr F 4. DB::TCPHandler::run() @ 0x0000000012369e79
> 2024-06-06T12:31:17.160946546Z stderr F 3. DB::TCPHandler::runImpl() @ 0x000000001234e1aa
> 2024-06-06T12:31:17.160944335Z stderr F 2. DB::ReadBufferFromPocoSocket::nextImpl() @ 0x000000000cd00c69
> 2024-06-06T12:31:17.160941485Z stderr F 1. DB::NetException::NetException<String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&) @ 0x000000000cd0103d
> 2024-06-06T12:31:17.160938633Z stderr F 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cbc851b
> 2024-06-06T12:31:17.160934962Z stderr F

<br class="Apple-interchange-newline">

**Comment by mbrother2** [comment]
Same issue, network works well.

```
2024.06.12 16:13:22.312857 [ 1704 ] {6727235c-fabe-4c10-9edf-47e2da3e69a6} <Error> DynamicQueryHandler: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (1.1.1.1:8123 -> 2.2.2.2:35262): While executing Native. (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c8aeddb
1. DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000c9e8ee1
2. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x000000000c9e987e
3. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x000000001237fa84
4. DB::IOutputFormat::flush() @ 0x00000000123ddffe
5. DB::IOutputFormat::work() @ 0x00000000123ddeab
6. DB::ExecutionThreadContext::executeTask() @ 0x00000000123d1c9a
7. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000123c61f0
8. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::PipelineExecutor::spawnThreads()::$_0, void ()>>(std::__function::__policy_storage const*) @ 0x00000000123c7918
9. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0x000000000c95b399
10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000c95ebfa
11. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c95da0d
12. start_thread @ 0x0000000000007ea7
13. ? @ 0x00000000000fba6f
 (version 24.3.1.2672 (official build))
 
 
 
2024.06.12 16:13:22.313268 [ 1704 ] {6727235c-fabe-4c10-9edf-47e2da3e69a6} <Error> DynamicQueryHandler: Cannot send exception to client: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (1.1.1.1:8123 -> 2.2.2.2:35262). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c8aeddb
1. DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000c9e8ee1
2. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x000000000c9e987e
3. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x000000001237fa84
4. DB::HTTPHandler::trySendExceptionToClient(String const&, int, DB::HTTPServerRequest&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&) @ 0x00000000122f7631
5. DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000122faabb
6. DB::HTTPServerConnection::run() @ 0x0000000012378a9a
7. Poco::Net::TCPServerConnection::start() @ 0x0000000014c9d672
8. Poco::Net::TCPServerDispatcher::run() @ 0x0000000014c9e4b9
9. Poco::PooledThread::run() @ 0x0000000014d96c21
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000014d951bd
11. start_thread @ 0x0000000000007ea7
12. ? @ 0x00000000000fba6f
 (version 24.3.1.2672 (official build))

```

**Comment by YYXXYYZZ** [comment]
Update：
this phenomenon occurred where a query consumed a significant amount of resources, triggering numerous NETWORK_ERROR and NO_REPLICA_HAS_PART errors. The system quickly recovered after the query finished. The write latency at the time of errors also increased.

**Comment by YYXXYYZZ** [comment]
This is likely a potential bug. Please assist in investigating. Thank you very much.
@alexey-milovidov  @den-crane

**Comment by MyBlog9587** [comment]
24.3.7.30 The same problem occurs, often resulting in query timeout and no response

**Comment by vpotap** [comment]
We're encountering a similar issue with version 23.8, where we're experiencing 'broken pipe' errors even when using just one replica.

<Warning> HedgedConnectionsFactory: Connection failed on attempt #1, reason: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (127.0.0.1:35942 -> 127.0.0.1:9000). (NETWORK_ERROR) (version 23.8.16.16 (official build))
<Warning> HedgedConnectionsFactory: Connection failed on attempt #1, reason: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (127.0.0.1:37744 -> 127.0.0.1:9000). (NETWORK_ERROR) (version 23.8.16.16 (official build))
<Warning> HedgedConnectionsFactory: Connection failed on attempt #1, reason: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (127.0.0.1:45266 -> 127.0.0.1:9000). (NETWORK_ERROR) (version 23.8.16.16 (official build))

**Comment by vpotapepic** [comment]
**Update:**

 After updating some timeout settings (version 23.8), we no longer encounter the 'broken pipe' error. To verify the current settings, you can run the following query: 

`SELECT name, value FROM system.settings`

We applied the following settings (the previous settings are included in the comment block for reference):
```
<yandex>
    <profiles>
        <default>
            <!-- Previous settings: -->
            <!-- connect_timeout: 10 -->
            <!-- connect_timeout_with_failover_ms: 1000 -->
            <!-- connect_timeout_with_failover_secure_ms: 1000 -->
            <!-- receive_timeout: 300 -->
            <!-- send_timeout: 300 -->
            <!-- tcp_keep_alive_timeout: 290 -->
            <!-- hedged_connection_timeout_ms: 50 -->

            <!-- Updated settings: -->
            <connect_timeout>100</connect_timeout>
            <connect_timeout_with_failover_ms>3000</connect_timeout_with_failover_ms>
            <connect_timeout_with_failover_secure_ms>3000</connect_timeout_with_failover_secure_ms>
            <receive_timeout>600</receive_timeout>
            <send_timeout>600</send_timeout>
            <tcp_keep_alive_timeout>600</tcp_keep_alive_timeout>
            <hedged_connection_timeout_ms>300</hedged_connection_timeout_ms>
        </default>
    </profiles>
</yandex>
```
These adjustments have resolved the issue.
@YYXXYYZZ @mbrother2

**Comment by vpotap** [comment]
**Update:**
After updating some timeout settings (version 23.8), we no longer encounter the 'broken pipe' error. To verify the current settings, you can run the following query:

`SELECT name, value FROM system.settings;`

We applied the following settings (the previous settings are included in the comment block for reference):
```
<yandex>
    <profiles>
        <default>
            <!-- Previous settings: -->
            <!-- connect_timeout: 10 -->
            <!-- connect_timeout_with_failover_ms: 1000 -->
            <!-- connect_timeout_with_failover_secure_ms: 1000 -->
            <!-- receive_timeout: 300 -->
            <!-- send_timeout: 300 -->
            <!-- tcp_keep_alive_timeout: 290 -->
            <!-- hedged_connection_timeout_ms: 50 -->

            <!-- Updated settings: -->
            <connect_timeout>100</connect_timeout>
            <connect_timeout_with_failover_ms>3000</connect_timeout_with_failover_ms>
            <connect_timeout_with_failover_secure_ms>3000</connect_timeout_with_failover_secure_ms>
            <receive_timeout>600</receive_timeout>
            <send_timeout>600</send_timeout>
            <tcp_keep_alive_timeout>600</tcp_keep_alive_timeout>
            <hedged_connection_timeout_ms>300</hedged_connection_timeout_ms>
        </default>
    </profiles>
</yandex>
```
These adjustments have resolved the issue.
@YYXXYYZZ @mbrother2

**Comment by mbrother2** [comment]
@vpotap 

Sounds good! We will try with theses option.

**Comment by mbrother2** [comment]
@vpotap ,

The issue is continuing...
```
2024.09.16 13:59:35.180939 [ 104470 ] {} <Error> ServerErrorHandler: Code: 210. DB::NetException: I/O error: Broken pipe, while writing to socket (x.x.x.x:8123 -> y.y.y.y:38182). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cfc7c1b
1. DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000d10995e
2. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x000000000d10b789
3. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x0000000012aa9ae4
4. DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000012aaa0cf
5. DB::WriteBuffer::finalize() @ 0x00000000078d5a46
6. DB::StaticRequestHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012a781c1
7. DB::HTTPServerConnection::run() @ 0x0000000012aa3683
8. Poco::Net::TCPServerConnection::start() @ 0x0000000015374bc7
9. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015375059
10. Poco::PooledThread::run() @ 0x0000000015341d61
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001534031d
12. start_thread @ 0x0000000000007ea7
13. ? @ 0x00000000000fba6f
 (version 24.6.1.4423 (official build))
2024.09.16 14:00:15.196082 [ 104443 ] {} <Error> ServerErrorHandler: Code: 210. DB::NetException: Connection reset by peer, while writing to socket (x.x.x.x:8123 -> y.y.y.y:34072). (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cfc7c1b
1. DB::NetException::NetException<String, String, String>(int, FormatStringHelperImpl<std::type_identity<String>::type, std::type_identity<String>::type, std::type_identity<String>::type>, String&&, String&&, String&&) @ 0x000000000d10995e
2. DB::WriteBufferFromPocoSocket::nextImpl() @ 0x000000000d10b5c7
3. DB::WriteBufferFromHTTPServerResponse::nextImpl() @ 0x0000000012aa9ae4
4. DB::WriteBufferFromHTTPServerResponse::finalizeImpl() @ 0x0000000012aaa0cf
5. DB::WriteBuffer::finalize() @ 0x00000000078d5a46
6. DB::StaticRequestHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x0000000012a781c1
7. DB::HTTPServerConnection::run() @ 0x0000000012aa3683
8. Poco::Net::TCPServerConnection::start() @ 0x0000000015374bc7
9. Poco::Net::TCPServerDispatcher::run() @ 0x0000000015375059
10. Poco::PooledThread::run() @ 0x0000000015341d61
11. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001534031d
12. start_thread @ 0x0000000000007ea7
13. ? @ 0x00000000000fba6f
 (version 24.6.1.4423 (official build))```

**Comment by alexey-milovidov** [comment]
The diagnostic in the logs is correct. The error messages are correct.

**Comment by jayjain123** [comment]
@alexey-milovidov @mbrother2 @vpotap 
How is this resolved?

**Comment by alexey-milovidov** [comment]
@jayjain123, network errors are related to your network and should be investigated accordingly.
