### ISSUE TITLE
build problem in building clickhouse on ubuntu

### ISSUE THREAD

**Issue by codeeeeeeeeeeeee** [ClickHouse/ClickHouse#64958]
**Operating system**
Ubuntu 22.04 WSL
**Cmake version**
3.26.3
**Ninja version**
1.10.1
**Compiler name and version**
clang-18
**Full cmake and/or ninja output**
FAILED: contrib/openldap-cmake/lber-version.c /home/clickhouse/clickhouse_new/clickhouse_new/build/contrib/openldap-cmake/lber-version.c
cd /home/clickhouse/clickhouse_new/clickhouse_new/contrib/openldap && /usr/local/bin/cmake -E env bash -c "/home/clickhouse/clickhouse_new/clickhouse_new/contrib/openldap/build/mkversion -v '2.5.X' liblber.la > \"/home/clickhouse/clickhouse_new/clickhouse_new/build/contrib/openldap-cmake/lber-version.c\""
bash: line 1: /home/clickhouse/clickhouse_new/clickhouse_new/contrib/openldap/build/mkversion: Permission denied
[6/10714] Building CXX object contrib/grpc-cmake/CMakeFiles/gpr.dir/__/grpc/src/core/lib/config/config_vars.cc.o
ninja: build stopped: subcommand failed.

FAILED: contrib/google-protobuf-cmake/protoc
: && /usr/bin/clang++-18 --target=x86_64-linux-gnu --sysroot=/home/clickhouse/clickhouse_new/clickhouse_new/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc --gcc-toolchain=/home/clickhouse/clickhouse_new/clickhouse_new/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -fsized-deallocation  -gdwarf-aranges -pipe -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/home/clickhouse/clickhouse_new/clickhouse_new=. -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -w -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3 -g  -fno-pie --gcc-toolchain=/home/clickhouse/clickhouse_new/clickhouse_new/cmake/linux/../../contrib/sysroot/linux-x86_64 --ld-path=/usr/bin/ld.lld-18 -Wl,--no-export-dynamic -Wl,--gc-sections -Wl,--gdb-index -Wl,--build-id=sha1 -no-pie -Wl,-no-pie    -Xlinker --no-undefined contrib/google-protobuf-cmake/CMakeFiles/protoc.dir/__/google-protobuf/src/google/protobuf/compiler/main.cc.o -o contrib/google-protobuf-cmake/protoc  contrib/google-protobuf-cmake/lib_libprotoc.a  contrib/google-protobuf-cmake/lib_libprotobuf.a  -lpthread  contrib/google-protobuf-cmake/libutf8_validity.a  contrib/abseil-cpp-cmake/libabsl_base.a  contrib/abseil-cpp-cmake/libabsl_cord.a  contrib/abseil-cpp-cmake/libabsl_die_if_null.a  contrib/abseil-cpp-cmake/libabsl_flags.a  contrib/abseil-cpp-cmake/libabsl_hash.a  contrib/abseil-cpp-cmake/libabsl_log_initialize.a  contrib/abseil-cpp-cmake/libabsl_log_severity.a  contrib/abseil-cpp-cmake/libabsl_status.a  contrib/abseil-cpp-cmake/libabsl_statusor.a  contrib/abseil-cpp-cmake/libabsl_strings.a  contrib/abseil-cpp-cmake/libabsl_synchronization.a  contrib/abseil-cpp-cmake/libabsl_time.a  contrib/zlib-ng-cmake/lib_zlib.a  contrib/abseil-cpp-cmake/libabsl_log_internal_check_op.a  contrib/abseil-cpp-cmake/libabsl_leak_check.a  contrib/abseil-cpp-cmake/libabsl_log_internal_conditions.a  contrib/abseil-cpp-cmake/libabsl_log_internal_message.a  contrib/abseil-cpp-cmake/libabsl_log_internal_nullguard.a  contrib/abseil-cpp-cmake/libabsl_examine_stack.a  contrib/abseil-cpp-cmake/libabsl_log_internal_format.a  contrib/abseil-cpp-cmake/libabsl_log_internal_proto.a  contrib/abseil-cpp-cmake/libabsl_log_internal_log_sink_set.a  contrib/abseil-cpp-cmake/libabsl_log_sink.a  contrib/abseil-cpp-cmake/libabsl_log_entry.a  contrib/abseil-cpp-cmake/libabsl_flags_internal.a  contrib/abseil-cpp-cmake/libabsl_flags_marshalling.a  contrib/abseil-cpp-cmake/libabsl_flags_reflection.a  contrib/abseil-cpp-cmake/libabsl_flags_config.a  contrib/abseil-cpp-cmake/libabsl_flags_program_name.a  contrib/abseil-cpp-cmake/libabsl_flags_private_handle_accessor.a  contrib/abseil-cpp-cmake/libabsl_flags_commandlineflag.a  contrib/abseil-cpp-cmake/libabsl_flags_commandlineflag_internal.a  contrib/abseil-cpp-cmake/libabsl_log_globals.a  contrib/abseil-cpp-cmake/libabsl_log_internal_globals.a  contrib/abseil-cpp-cmake/libabsl_raw_hash_set.a  contrib/abseil-cpp-cmake/libabsl_hash.a  contrib/abseil-cpp-cmake/libabsl_city.a  contrib/abseil-cpp-cmake/libabsl_low_level_hash.a  contrib/abseil-cpp-cmake/libabsl_hashtablez_sampler.a  contrib/abseil-cpp-cmake/libabsl_status.a  contrib/abseil-cpp-cmake/libabsl_cord.a  contrib/abseil-cpp-cmake/libabsl_cordz_info.a  contrib/abseil-cpp-cmake/libabsl_cord_internal.a  contrib/abseil-cpp-cmake/libabsl_cordz_functions.a  contrib/abseil-cpp-cmake/libabsl_exponential_biased.a  contrib/abseil-cpp-cmake/libabsl_cordz_handle.a  contrib/abseil-cpp-cmake/libabsl_crc_cord_state.a  contrib/abseil-cpp-cmake/libabsl_crc32c.a  contrib/abseil-cpp-cmake/libabsl_crc_internal.a  contrib/abseil-cpp-cmake/libabsl_crc_cpu_detect.a  contrib/abseil-cpp-cmake/libabsl_bad_optional_access.a  contrib/abseil-cpp-cmake/libabsl_strerror.a  contrib/abseil-cpp-cmake/libabsl_str_format_internal.a  contrib/abseil-cpp-cmake/libabsl_synchronization.a  contrib/abseil-cpp-cmake/libabsl_stacktrace.a  contrib/abseil-cpp-cmake/libabsl_symbolize.a  contrib/abseil-cpp-cmake/libabsl_debugging_internal.a  contrib/abseil-cpp-cmake/libabsl_demangle_internal.a  contrib/abseil-cpp-cmake/libabsl_graphcycles_internal.a  contrib/abseil-cpp-cmake/libabsl_kernel_timeout_internal.a  contrib/abseil-cpp-cmake/libabsl_malloc_internal.a  contrib/abseil-cpp-cmake/libabsl_time.a  contrib/abseil-cpp-cmake/libabsl_strings.a  contrib/abseil-cpp-cmake/libabsl_strings_internal.a  contrib/abseil-cpp-cmake/libabsl_string_view.a  contrib/abseil-cpp-cmake/libabsl_base.a  contrib/abseil-cpp-cmake/libabsl_spinlock_wait.a  contrib/abseil-cpp-cmake/libabsl_throw_delegate.a  contrib/abseil-cpp-cmake/libabsl_int128.a  contrib/abseil-cpp-cmake/libabsl_civil_time.a  contrib/abseil-cpp-cmake/libabsl_time_zone.a  contrib/abseil-cpp-cmake/libabsl_bad_variant_access.a  contrib/abseil-cpp-cmake/libabsl_raw_logging_internal.a  contrib/abseil-cpp-cmake/libabsl_log_severity.a  -Wl,--start-group  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  contrib/libunwind-cmake/libunwind.a  base/glibc-compatibility/libglibc-compatibility.a  base/glibc-compatibility/memcpy/libmemcpy.a  -Wl,--end-group  -nodefaultlibs /usr/lib/llvm-18/lib/clang/18/lib/linux/libclang_rt.builtins-x86_64.a   -lc -lm -lrt -lpthread -ldl && :
ld.lld-18: error: /home/clickhouse/clickhouse_new/clickhouse_new/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64/libpthread.so:1: unexpected EOF
>>> ../../lib64/libpthread.so.0
>>> ^
clang++-18: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Algunenano** [comment]
Check that you have enough memory and free disk space and that you've cloned all submodules correctly (no errors or missing files)

**Comment by codeeeeeeeeeeeee** [comment]
how can i check i've cloned all submodules correctly?

**Comment by Algunenano** [comment]
`git status` should show an empty list.

You can try `git submodule sync && git submodule update --init --recursive -f` to force them to be reloaded.

In fact, seeing the error `bash: line 1: /home/clickhouse/clickhouse_new/clickhouse_new/contrib/openldap/build/mkversion: Permission denied` from above it seems there is definitely something wrong with your submodules. Maybe you cloned them with a different OS user?

**Comment by codeeeeeeeeeeeee** [comment]
yeah,i cloned this program from windows,is that the problem?

**Comment by Algunenano** [comment]
Probably, but I have zero experience with windows. Clone it directly with WSL

**Comment by codeeeeeeeeeeeee** [comment]
ok.i'll try,thank u very much!

**Comment by wbkxjh** [comment]
@codeeeeeeeeeeeee Have you solved this problem?
