### ISSUE TITLE
DatabaseReplicated

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6496]
Database engine that stores tables metadata (.sql files) and modification log (DDL operations) in ZooKeeper. Replicas will replicate changes in metadata.

Questionable.

**Comment by filimonov** [comment]
Currently the main problem with that (also for schema migration tools) is lack of possibility to use same queries on every replica.

I.e. if you will do create + alter on one replica you can't use same create + alter on another. You need to extract /recreate proper create table statement from 1st replica and execute it directly on another.

That makes schema migration tools (like liquibase, flyway, dbdeploy, migrate, etc) useless in clickhouse case.

I think it would be cool to create smth like embedded schema migration tool for clickhouse (or create some toolset which will allow to use standard tools usually used for that).

**Comment by alexey-milovidov** [comment]
@ValBaturin
