### ISSUE TITLE
Errors when outputting and inputting Protobuf for Nested Data Type

### ISSUE THREAD

**Issue by InsidersByte** [ClickHouse/ClickHouse#6497]
**Describe the bug**
Outputting and Inputting Protobuf doesn't work for nested if one of the fields is the default value.

**How to reproduce**
* Which ClickHouse server version to use
`19.13.1.11`
* Which interface to use, if matters
Data is seeded with `Values`, outputted as `Protobuf` and finally read back in `Protobuf`
* Non-default settings, if any
`N/A`
* `CREATE TABLE` statements for all tables involved
```proto
syntax = "proto3";

message Repeated {
  string foo = 1;
  int64 bar = 2;
}

message Message {
  repeated Repeated messages = 1;
};
```

```sql
CREATE TABLE foobar (
  messages Nested (
    foo String,
    bar Int64
  )
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY tuple()
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
```sql
INSERT INTO foobar FORMAT Values
  (['1'], [0])
;

select *
from foobar
INTO OUTFILE '/tmp/output.protobuf'
FORMAT Protobuf
SETTINGS format_schema = 'nested:Message';
```

```bash
cat /tmp/output.protobuf | /usr/bin/clickhouse-client --query="INSERT INTO foobar FORMAT Protobuf SETTINGS format_schema = 'nested:Message'"
```

**Expected behavior**
Able to export and import nested data.

**Error message and/or stacktrace**
```
$ cat /tmp/output.protobuf | /usr/bin/clickhouse-client --query="INSERT INTO foobar FORMAT Protobuf SETTINGS format_schema = 'nested:Message'"
Received exception from server (version 19.13.1):
Code: 190. DB::Exception: Received from clickhouse-server:9000. DB::Exception: Elements 'messages.foo' and 'messages.bar' of Nested data structure 'messages' (Array columns) have different array sizes..
```

**Additional context**
Works if both the fields are the default or non-default.

**Comment by InsidersByte** [comment]
Actually, there is a bigger bug here than the import exporting erroring. 

If the length after filtering out the defaults is valid then it will succeed to import the data but create the incorrect number of rows.

```sql
INSERT INTO foobar FORMAT Values
  (['1', ''], [0, 1])
;

select *
from foobar
INTO OUTFILE '/tmp/output.protobuf'
FORMAT Protobuf
SETTINGS format_schema = 'nested:Message';
```

```bash
cat /tmp/output.protobuf | /usr/bin/clickhouse-client --query="INSERT INTO foobar FORMAT Protobuf SETTINGS format_schema = 'nested:Message'"
```

```sql
SELECT *
FROM foobar
FORMAT PrettyCompactMonoBlock

┌─messages.foo─┬─messages.bar─┐
│ ['1']        │ [1]          │
│ ['1','']     │ [0,1]        │
└──────────────┴──────────────┘

2 rows in set. Elapsed: 0.004 sec. 
```

**Comment by vitlibar** [comment]
Fixed, the example turned into the test `00825_protobuf_format_nested_optional`.
