### ISSUE TITLE
`arrayShingles` works wrong for the string arrays

### ISSUE THREAD

**Issue by mehanizm** [ClickHouse/ClickHouse#65027]
### Describe what's wrong

`arrayShingles` works as expected for the int arrays:

```sql
select
    arrayShingles([1, 2, 3], 2);
```

```
[[1, 2], [2, 3]]
```

but works wrong for ther string arrays:

```sql
select
    arrayShingles(['a', 'b', 'c'], 2);
```

```
[['b', 'c'], ['b', 'c']]
```

### Does it reproduce on the most recent release?

Yes, on version `24.5.1.1763`

### Expected behavior

Result for the string array should be:
```sql
select
    arrayShingles(['a', 'b', 'c'], 2);
```

```
[['a', 'b'], ['b', 'c']]
```

And it works like this on version `24.4`

**Comment by alexey-milovidov** [comment]
Not reproduced on master:

```
milovidov@milovidov-pc:~$ ch
ClickHouse local version 24.6.1.1.

milovidov-pc :) select
    arrayShingles(['a', 'b', 'c'], 2);

SELECT arrayShingles(['a', 'b', 'c'], 2)

Query id: d480a402-4fca-4537-9a19-4ec85861f9f6

   ┌─arrayShingles(['a', 'b', 'c'], 2)─┐
1. │ [['a','b'],['b','c']]             │
   └───────────────────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

**Comment by alexey-milovidov** [comment]
Not reproduced on 24.5, 24.4:

https://fiddle.clickhouse.com/cbdd11d3-de2a-4a3c-9c4b-0f88a8934f6a
https://fiddle.clickhouse.com/e5fd07f4-c8ee-4d9b-995f-8c666851e4f8

**Comment by mehanizm** [comment]
@alexey-milovidov, thx for the quick response.

Ouch, it’s strange. 
I’ve tried it from the clickhouse-client and it works! 
<img width="450" alt="Screenshot 2024-06-10 at 21 57 55" src="https://github.com/ClickHouse/ClickHouse/assets/16045633/92b9202a-ca90-45a6-9976-982e73550058">

But from DataGrip, it still provides the wrong result…
<img width="450" alt="Screenshot 2024-06-10 at 21 57 46" src="https://github.com/ClickHouse/ClickHouse/assets/16045633/503730c4-daff-459d-8a98-efca12c2cc3c">

**Comment by alexey-milovidov** [comment]
It might be a bug in DataGrip. If you `SELECT [['a, b'], ['b', 'c']]` directly, what does it show? And if you do `SELECT materialize([['a, b'], ['b', 'c']])`?

**Comment by mehanizm** [comment]
@alexey-milovidov ,
`[['b', 'c'], ['b', 'c']]` in both cases.
you're right, it's datagrip, I think the issue should be closed.

**Comment by slvrtrn** [comment]
@mehanizm, could you share the versions used for DataGrip/JDBC? In my case, the result matches the CLI client in WebStorm 23.3 with the JDBC driver 0.6.0-patch5.

**Comment by mehanizm** [comment]
@slvrtrn , of course
DataGrip 2023.3.2 for Mac
Clickhouse driver in Datagrip 0.4.0

I've updated to DataGrip 2024.1.4 and it's the same

**Comment by slvrtrn** [comment]
> Clickhouse driver in Datagrip 0.4.0

Is it the same with 0.6.0-patch5 (if you update it in the connection settings?)

**Comment by mehanizm** [comment]
@slvrtrn , thank you. 

I've updated to the latest 0.6.0 version of the Clickhouse JDBC driver in DataGrip and it work as expected.
