### ISSUE TITLE
Unable to Insert Data into activity_log Table Using INSERT INTO ... SELECT Query

### ISSUE THREAD

**Issue by TahaDgn** [ClickHouse/ClickHouse#65029]
Description:
I am encountering an issue while attempting to insert data into the activity_log table using an INSERT INTO ... SELECT query. Despite the query executing without errors, no data is being inserted into the table.

Steps to Reproduce:

1. Create a table activity_log with the following schema:
```sql
CREATE TABLE activity_log (
  memberId String,
  gymId String,
  activityType String,
  platform String,
  createdAt DateTime,
  exerciseId String,
  exerciseName String
) ENGINE = MergeTree()
ORDER BY (memberId);
```
2. Ensure the exercises table exists with relevant columns:

```sql
CREATE TABLE exercises (
  exerciseId String,
  exerciseName String,
  platform String,
  tags Nested (name String, type String, isCritical UInt8)
) ENGINE = MergeTree()
ORDER BY (exerciseId);

```

3. Execute the following INSERT INTO ... SELECT query:

```sql
INSERT INTO activity_log (
  memberId, 
  gymId, 
  activityType, 
  platform, 
  createdAt, 
  exerciseId, 
  exerciseName
)
SELECT
  'member123',
  'gym123',
  'WORKOUT',
  'GYM_APP',
  toDateTime('2024-06-09T17:01:16'),
  COALESCE(exerciseId, ''),
  COALESCE(exerciseName, 'DefaultExercise')
FROM exercises
WHERE exerciseId = '' AND platform = 'GYM_APP';

```

Expected Behavior:
The query should insert a new row into the activity_log table with the provided data and the selected data from the exercises table.

Actual Behavior:
The query executes without any errors, but no data is inserted into the activity_log table.

Additional Information:

Running the subquery independently returns the expected data.
A simple insert into the activity_log table works correctly.
Query execution environment: ClickHouse version 24.4.1.2088 Ubuntu docker image

Possible Solution:
N/A

Please let me know if additional information is required. Thank you for your assistance.

**Comment by sigxcpu76** [comment]
There is no data in exercises that matches the WHERE clause.
After adding some data, it works as expected (adding aliases to the columns on insert, too).
https://fiddle.clickhouse.com/74eaa7bd-cf79-4390-91a5-249677d4e9c9

**Comment by den-crane** [comment]
Clickhouse aliases behaves slightly different with vanilla sql

```
INSERT ...
SELECT ....
  'GYM_APP' as platform,
....
FROM exercises
WHERE 
  AND platform = 'GYM_APP';  --- here `platform` refers `platform` in the SELECT section, not the column in `exercises`
```

You can use table name or table alias to refer the table's column.

```sql
INSERT ...
SELECT ....
  'GYM_APP' as platform,
....
FROM exercises as X
WHERE 
  AND X.platform = 'GYM_APP';
```

Or you can use a setting `prefer_column_name_to_alias --  Prefer using column names instead of aliases if possible.`

```
INSERT ...
SELECT ....
  'GYM_APP' as platform,
....
FROM exercises 
WHERE 
  AND platform = 'GYM_APP'
SETTING prefer_column_name_to_alias=1;
```
