### ISSUE TITLE
LEAST/GREATEST return null if present

### ISSUE THREAD

**Issue by melvynator** [ClickHouse/ClickHouse#65039]
**Describe the unexpected behaviour**
Should return 1 for `SELECT LEAST(1, 2, null);` 

**How to reproduce**
`SELECT LEAST(1, 2, null);` 

* Which ClickHouse server version to use:
24.5

* Queries to run that lead to unexpected result
`SELECT LEAST(1, 2, null);` 
`SELECT greatest(1, 2, null)`

**Expected behavior**
Should return 1 or 2 like PostgreSQL/DuckBD

**Comment by KevinyhZou** [comment]
Hello,  this problem also happens in our gluten case, and I submit a pr to fix it. @melvynator
