### ISSUE TITLE
HDFS file use parquet format,when I query clickhouse make error 

### ISSUE THREAD

**Issue by jetliu1711** [ClickHouse/ClickHouse#6504]
my hive table stored as parquet format.clickhouse table like this:
CREATE  TABLE IF NOT EXISTS test(
 pay_time String ,
 cust_id String 
 )ENGINE=HDFS('hdfs://10.5.120.12:9000/user/hive/warehouse/dw_tmp.db/test/trans_date=2019-08-01/000000_0', 'Parquet');

but I exxcute this sql "select * from test limit 10;" have a error:
Received exception from server (version 19.13.1):
Code: 210. DB::Exception: Received from bi.dt.27:9000. DB::Exception: Fail to read HDFS file: hdfs://master:9000/user/hive/warehouse/dw_tmp.db/test/trans_date=2019-08-01/000000_0 HdfsIOException: InputStreamImpl: cannot read file: /user/hive/warehouse/dw_tmp.db/test/trans_date=2019-08-01/000000_0, from position 0, size: 1048576.   Caused by: HdfsIOException: InputStreamImpl: all nodes have been tried and no valid replica can be read for Block: [block pool ID: BP-1966204390-10.10.6.227-1469108237793 block ID 3469728620_2406979839].         Caused by: HdfsIOException: RemoteBlockReader does not support CRC32 checksum, Block: [block pool ID: BP-1966204390-10.10.6.227-1469108237793 block ID 3469728620_2406979839], from Datanode: h30151(10.10.6.227).

**Comment by filimonov** [comment]
That sounds like hdfs related exception. Did you check existence and avaliability of the mentioned file on hdfs?

**Comment by filimonov** [comment]
Or maybe not: https://github.com/apache/hawq/blob/4156a8760787894ef351de73df3c38287bbba41d/depends/libhdfs3/src/client/RemoteBlockReader.cpp#L148

**Comment by jetliu1711** [comment]
> Client library doesn't support that particular checksums?
> https://github.com/apache/hawq/blob/4156a8760787894ef351de73df3c38287bbba41d/depends/libhdfs3/src/client/RemoteBlockReader.cpp#L148

At first ,I use hdfs table engine to linset data to clickhouse.when I query in clickhouse make error.I think hawq's libhdfs3 is not support .Right?Is only support hawq's hdfs?

**Comment by blinkov** [comment]
@jetliu1711, do you have any further questions?

**Comment by alexey-milovidov** [comment]
Yes, we will need to either patch this library or to switch to another library (which one?)

**Comment by alexey-milovidov** [comment]
We don't support HDFS.
