### ISSUE TITLE
Stress tests failed with `Initiator received more initial requests than there are replicas`

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#65043]
Bunch of failures [cidb](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKICAgIApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+PSBub3coKSAtIElOVEVSVkFMIDcgREFZCiAgICBBTkQgdGVzdF9jb250ZXh0X3JhdyBsaWtlICclSW5pdGlhdG9yIHJlY2VpdmVkIG1vcmUgaW5pdGlhbCByZXF1ZXN0cyB0aGFuIHRoZXJlIGFyZSByZXBsaWNhcyUnCiAgICBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgPSAwIE9SIG5vdCBvbmx5X21hc3RlcikKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyBMSUtFICdGJScKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCikKV0hFUkUgdGVzdF9uYW1lIGxpa2UgJyVGYXRhbCBtZXNzYWdlIGluIGNsaWNraG91c2Utc2VydmVyJScKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZSBERVNDLCBjaGVja19uYW1lLCB0ZXN0X25hbWU=)

<details>
<summary>Details</summary>

| prnum | sha | dur | check_start_time | ago | check_name | test_name | report_url |
|-:|:-|-:|-:|:-|:-|:-|:-|
| 64989 | a53ce5637 | 0 | 2024-06-07 20:29:46 | 2 days and 13 hours | Stress test (debug) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64989/a53ce5637e2e6ce7fd5bd33f04b0d0e3d9b2dac0/stress_test__debug_.html |
| 64607 | 35bf0f971 | 0 | 2024-06-07 19:04:40 | 2 days and 14 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64607/35bf0f971b6ca01f83ce3b284505d86af46f3853/stress_test__tsan_.html |
| 63314 | 48de60077 | 0 | 2024-06-07 18:47:33 | 2 days and 15 hours | Stress test (msan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/63314/48de600770aa5ad08720c365d8a705b48375a647/stress_test__msan_.html |
| 0 | b1d6c7320 | 0 | 2024-06-07 17:12:44 | 2 days and 16 hours | Stress test (azure, tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/b1d6c732089b0ae2d8d3869a6e7d4ff408f7f8e3/stress_test__azure__tsan_.html |
| 0 | b1d6c7320 | 0 | 2024-06-07 17:12:42 | 2 days and 16 hours | Stress test (azure, msan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/b1d6c732089b0ae2d8d3869a6e7d4ff408f7f8e3/stress_test__azure__msan_.html |
| 0 | a96b7781c | 0 | 2024-06-07 15:59:02 | 2 days and 17 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/a96b7781c3681f4cc28e078f91ec3e7bead65e27/stress_test__tsan_.html |
| 64924 | 1881107f0 | 0 | 2024-06-06 19:46:38 | 3 days and 14 hours | Stress test (debug) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64924/1881107f0773d4aa0e195ef5cd6bb8f8a17b8cc3/stress_test__debug_.html |
| 0 | a197a530d | 0 | 2024-06-06 08:09:23 | 4 days and 1 hour | Stress test (azure, tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/a197a530d67d175e4cf128b88a6308c81da64ce4/stress_test__azure__tsan_.html |
| 0 | cb2c08553 | 0 | 2024-06-06 04:56:40 | 4 days and 4 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/cb2c0855353c9e0a78c92a9a62a691cdcca8f1bc/stress_test__tsan_.html |
| 0 | cb2c08553 | 0 | 2024-06-06 04:55:41 | 4 days and 4 hours | Stress test (azure, tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/cb2c0855353c9e0a78c92a9a62a691cdcca8f1bc/stress_test__azure__tsan_.html |
| 64844 | 5e9a41bd9 | 0 | 2024-06-05 16:21:46 | 4 days and 17 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64844/5e9a41bd9f0642513a11a67cd0cb3a21e5697775/stress_test__tsan_.html |
| 0 | 9b7944e3a | 0 | 2024-06-05 14:13:40 | 4 days and 19 hours | Stress test (asan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/9b7944e3a504e60e3579eb8142ba04429be49e4c/stress_test__asan_.html |
| 0 | ec3b82ba6 | 0 | 2024-06-05 09:15:40 | 5 days | Stress test (azure, tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/ec3b82ba63ce645afefdbd419dac51c28d804c93/stress_test__azure__tsan_.html |
| 0 | 5a5bdd87c | 0 | 2024-06-05 00:11:55 | 5 days and 9 hours | Stress test (azure, tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/5a5bdd87cbc1f0a66923a9ba17938745e386e9cf/stress_test__azure__tsan_.html |
| 0 | 5a5bdd87c | 0 | 2024-06-05 00:11:51 | 5 days and 9 hours | Stress test (azure, msan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/5a5bdd87cbc1f0a66923a9ba17938745e386e9cf/stress_test__azure__msan_.html |
| 0 | 46434f904 | 0 | 2024-06-04 20:59:41 | 5 days and 12 hours | Stress test (azure, msan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/46434f9040a4de2fa12a7efe7b9bf4a389093f25/stress_test__azure__msan_.html |
| 0 | 9f49c8313 | 0 | 2024-06-04 15:12:25 | 5 days and 18 hours | Stress test (debug) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/9f49c83130af0bb4f269cd9bd9048503c6956738/stress_test__debug_.html |
| 0 | 6d7c6a47c | 0 | 2024-06-04 12:26:35 | 5 days and 21 hours | Stress test (azure, tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/0/6d7c6a47cc5285ff02ec6925210ef2ed6ece6054/stress_test__azure__tsan_.html |
| 64781 | 506929856 | 0 | 2024-06-04 11:59:41 | 5 days and 21 hours | Stress test (debug) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64781/506929856af2873952d99b79a2ccb658129f674c/stress_test__debug_.html |
| 64776 | 2c581ecc4 | 0 | 2024-06-04 05:21:17 | 6 days and 4 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64776/2c581ecc461a219a05d59f8c56fac077279bc60b/stress_test__tsan_.html |
| 64582 | 869134eaa | 0 | 2024-06-03 14:42:38 | 6 days and 19 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64582/869134eaacc1ac113ba87aba23c5f69577fe62f6/stress_test__tsan_.html |
| 63781 | 1cda4596a | 0 | 2024-06-03 14:25:53 | 6 days and 19 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/63781/1cda4596adfc9ca384a28da80a91159641952e36/stress_test__tsan_.html |
| 64742 | ebf3bbe67 | 0 | 2024-06-03 14:16:38 | 6 days and 19 hours | Stress test (tsan) | Fatal message in clickhouse-server.log (see fatal_messages.txt) | https://s3.amazonaws.com/clickhouse-test-reports/64742/ebf3bbe67af3b5af7885bd47a1b41137fb24b67f/stress_test__tsan_.html |

</details>

**Comment by Algunenano** [comment]
Fuzz report: https://s3.amazonaws.com/clickhouse-test-reports/65207/1172b324e5ef3dcdbb751b066a546f4f0a81564d/ast_fuzzer__msan_.html

**Comment by Algunenano** [comment]
@nickitat another repro from the last fuzzer:

```
CREATE TABLE ids (id UUID, whatever String) Engine=MergeTree ORDER BY tuple();
INSERT INTO ids VALUES ('a1451105-722e-4fe7-bfaa-65ad2ae249c2', 'whatever');

CREATE TABLE data (id UUID, event_time DateTime, status String) Engine=MergeTree ORDER BY tuple();
INSERT INTO data VALUES ('a1451105-722e-4fe7-bfaa-65ad2ae249c2', '2000-01-01', 'CREATED');

CREATE TABLE data2 (id UUID, event_time DateTime, status String) Engine=MergeTree ORDER BY tuple();
INSERT INTO data2 VALUES ('a1451105-722e-4fe7-bfaa-65ad2ae249c2', '2000-01-02', 'CREATED');

SELECT
    id,
    whatever
FROM ids AS l
INNER JOIN view(
    SELECT *
    FROM merge(currentDatabase(), 'data*')
) AS s ON l.id = s.id
WHERE status IN ['CREATED', 'CREATING']
ORDER BY event_time DESC
SETTINGS allow_experimental_analyzer = 1, cluster_for_parallel_replicas = 'parallel_replicas', max_parallel_replicas = 3, allow_experimental_parallel_reading_from_replicas = 1, parallel_replicas_for_non_replicated_merge_tree = 1, max_threads = 1;
```
