### ISSUE TITLE
Inconsistent query formatting with equals function in type argument

### ISSUE THREAD

**Issue by antaljanosbenjamin** [ClickHouse/ClickHouse#65055]
**Describe what's wrong**

Parsing of type arguments is not consistent with formatting. Operator functions (e.g.: `equals`) can be parsed as types, because `Decimal(12,10)` is the same as `equals(1,2)` from the parser perspective. However when outputting the AST, `ASTFunction` outputs `1 = 2` instead of `equals(1,2)`, which cannot be parsed as a type. Thus `formatQuery(formatQuery(<query with equals(1,2) as type>))` fails to parse the result of the inner `formatQuery`.

```
ip-10-2-3-206.eu-west-1.compute.internal :) SELECT formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))')

SELECT formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))')

Query id: 9455f2f0-5533-4c56-b48a-ef1ac05ea1ac

   ┌─formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))')─┐
1. │ ALTER TABLE src
    (MODIFY COLUMN `B` Nullable('test6' = toNullable(5)))                     │
   └──────────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.019 sec. 

ip-10-2-3-206.eu-west-1.compute.internal :) SELECT formatQuery(formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))'))

SELECT formatQuery(formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))'))

Query id: 7a57b554-4c82-4f28-a40d-d31aff95441d


Elapsed: 0.025 sec. 

Received exception:
Code: 62. DB::Exception: Syntax error: failed at position 59 ('toNullable') (line 2, col 43): toNullable(5))). Expected one of: literal, NULL, NULL, number, Bool, TRUE, FALSE, string literal: In scope SELECT formatQuery(formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))')). (SYNTAX_ERROR)

ip-10-2-3-206.eu-west-1.compute.internal :) 

```

Found by [fuzzer](https://s3.amazonaws.com/clickhouse-test-reports/64888/15317b5b507aae95194f0cdb7d9678ce43a3784f/ast_fuzzer__debug_.html).

**How to reproduce**

[Fiddle](https://fiddle.clickhouse.com/2e032925-86d2-4d0c-8034-2b7259d5e564):

```
SELECT formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))');

SELECT formatQuery(formatQuery('ALTER TABLE src (MODIFY COLUMN `B` Nullable(equals(\'test6\',toNullable(5))))'));
```

**Expected behavior**

If the original query can be parsed, then the formatted query can also be parsed.

**Comment by antaljanosbenjamin** [comment]
I tried the followings:
1. Enforce using the `operator_name(args)` form by introducing a new field to `IAST::FormatSettings`, but then we have to take care of all the places where we parse types to flip that flag in formatting. This is very invasive and easy to forget.
2. Try to parse expressions in `ParserDataType` in order to be able to parse `1 + 2` as a funny type (`equals(1,2)`), but that is very hackish. We only extend our parser to be able to parse invalid expressions because of our formatting. Furthermore it might have other consequences that I don't see.
3. I checked if it possible to prevent some functions to be parsed as types, but this is also easy to mess it up. E.g.: we should have a central place of the list of functions we format as operators, but maintaining that list requires extra effort.

At this point I am not sure how to solve the issue.

**Comment by kssenii** [comment]
Similar https://s3.amazonaws.com/clickhouse-test-reports/64412/ef8810a60d3615c0fe8ad40459a8afc98c83e76c/ast_fuzzer__debug_.html

**Comment by Algunenano** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/65188/b74f910aaf9b1a05fd909923afb7714d4070532d/ast_fuzzer__debug_/fatal.log

The query is obviously wrong when you interpret it, not sure if we need to accept functions and which at parse level in this case.

**Comment by antaljanosbenjamin** [comment]
> The query is obviously wrong when you interpret it, not sure if we need to accept functions and which at parse level in this case.

AFAIK we don't have a list of types in parsing time, thus we cannot restrict the types we parse. I talked about this with @KochetovNicolai and maybe the best solution is to force the "long" version of operator formatting (e.g.: `plus(1,2)` instead of `1 + 2`) when we know we have type definitions (e.g.: `ColumnDescription`). We don't have a perfect solution yet though.

**Comment by antaljanosbenjamin** [comment]
Duplace of #61611
