### ISSUE TITLE
How to use the clickhouse-odbc-brigde 

### ISSUE THREAD

**Issue by roycyz** [ClickHouse/ClickHouse#65065]
### Question

Just start the server and run clickhouse-odbc-bridge --http-port 9018 --daemon.
Then curl the bridge like 'curl -d "query=SELECT id,name FROM test" --data-urlencode "connection_string=DSN=mysqlconn;DATABASE=test" --data-urlencode "sample_block=columns format version: 2 columns: \`id\` int \`name\` string" "http://182.168.12.184:9018/"'.
It's return No 'columns' in request URL

**Comment by davenger** [comment]
Please try the following command. Note that there are new lines, value of `1` for `column format version`, escaping for back-ticks and capital letters in Int and String
```
curl -d "query=SELECT id,name FROM test" --data-urlencode "connection_string=DSN=mysqlconn;DATABASE=test" --data-urlencode "sample_block=columns format version: 1
2 columns:
\`id\` Int
\`name\` String
" "http://182.168.12.184:9018/"
```

**Comment by davenger** [comment]
You might be using an old version of clickhouse-odbc-bridge - I cannot find error message "No 'columns' in request URL" in the current source code. Please try using the newer version. Also in you command there are missing newlines, escaping. Please try the following command

```
curl -d "query=SELECT id,name FROM test" --data-urlencode "connection_string=DSN=mysqlconn;DATABASE=test" --data-urlencode "sample_block=columns format version: 1
2 columns:
\`id\` Int
\`name\` String
" "http://182.168.12.184:9018/"
```
