### ISSUE TITLE
Passive option for replication

### ISSUE THREAD

**Issue by astudnev** [ClickHouse/ClickHouse#6506]
There are cases where the current P2P replication mechanism in CH is not reliable and can lead to the corruption of replicated tables:

1) when some servers holding replicas are given to untrusted party and he can modify the data, effectively changing the main table. 

2) when upgrading CH version on a part of servers in the system can corrupt the database: https://github.com/yandex/ClickHouse/issues/6472

What is asked is to configure the replication as "slave" as the option for the table.

What this option does is that disables any reading from this server from others during replication. Data modification in this replica by client is also disabled.

Option can be turned on/off by ALTER TABLE as well

**Comment by filimonov** [comment]
Sounds like forced `is_readonly`.

**Comment by astudnev** [comment]
No, this is not readonly. Others must NOT read from this replica

**Comment by filimonov** [comment]
Hm. Even if master is dead and need to be recovered?

As a workaround: i think that if you will forbid inserts to the table (by using readonly profile for users), close the access to 9009 port from outside, and set  `replicated_can_become_leader` to 0.

**Comment by den-crane** [comment]
Also https://github.com/yandex/ClickHouse/issues/2642#issuecomment-460037222

**Comment by astudnev** [comment]
I did not find any documentation on how to set replicated_can_become_leader and what it does

**Comment by den-crane** [comment]
```
# cat /etc/clickhouse-server/conf.d/config_substitutes_no_leader.xml
<?xml version="1.0"?>
<yandex>
    <merge_tree>
        <replicated_can_become_leader>0</replicated_can_become_leader>
    </merge_tree>
</yandex>
```

It means this node will not became the leader -- replication / merges coordinator.

**Comment by astudnev** [comment]
Thanks, @den-crane this is probably what i meant. Not sure what "leader" means, however 
Does it mean nobody will read data for replicas from this server?

**Comment by den-crane** [comment]
>Does it mean nobody will read data for replicas from this server?
No, it does not. 
It's impossible to implement on 100% with replicated tables and internal_replication. Only with replication using Distributed (internal_replication=false).

**Comment by alexey-milovidov** [comment]
It can be implemented simply by closing replication port (`interserver_http_port`) or removing it from config and disallowing INSERT queries on that replica.

Then replica will download data from other replicas but no other replicas will be able to download data from that replica.
