### ISSUE TITLE
Buffer tables, created with currentDatabase(), lose their database assigment after restarting clickhouse server

### ISSUE THREAD

**Issue by RiderALT** [ClickHouse/ClickHouse#6508]
**Describe the bug**
Buffer tables lose information about their database when the clickhouse server restarts.

**How to reproduce**
* Which ClickHouse server version to use
19.13.2.19
* `CREATE TABLE` statements for all tables involved

CREATE TABLE Test (
        uuid            UUID,
        pkghash         UInt64
) 
ENGINE = MergeTree
ORDER BY (uuid, pkghash) PRIMARY KEY (uuid);

CREATE TABLE Test_buffer AS Test
ENGINE = Buffer(currentDatabase(), Test, 16, 10, 200, 10000, 1000000, 10000000, 1000000000);

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

insert into Test_buffer SELECT generateUUIDv4(),rand64()

* Queries to run that lead to unexpected result

`# systemctl restart clickhouse-server`
`# clickhouse-client -n -d test_buff -q 'INSERT INTO Test_buffer SELECT generateUUIDv4(),rand64();'
Received exception from server (version 19.13.2):
Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Default database is not selected.
`

**Expected behavior**

Insert without error

**Error message and/or stacktrace**

INSERT INTO Test_buffer SELECT 
    generateUUIDv4(), 
    rand64()

. Received exception from server (version 19.13.2):
Code: 81. DB::Exception: Received from localhost:9000. DB::Exception: Default database is not selected.

**Additional context**

**Comment by filimonov** [comment]
Related #6104
