### ISSUE TITLE
Explicit use-after-dtor logic in `HashTable.h`

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#65098]
https://github.com/ClickHouse/ClickHouse/blob/6f513de0011e087ed25edc49236abcc94cea018b/src/Common/HashTable/HashTable.h#L660-L670

`it.ptr->~Cell()` explicitly destroyed the member key, but is it used in `operator++` of the iterator `it`:

https://github.com/ClickHouse/ClickHouse/blob/6f513de0011e087ed25edc49236abcc94cea018b/src/Common/HashTable/HashTable.h#L704-L708

where `ZeroTraits::check` has a general template implementation which copies the destroyed key:

https://github.com/ClickHouse/ClickHouse/blob/6f513de0011e087ed25edc49236abcc94cea018b/src/Common/HashTable/HashTable.h#L71-L75

**Comment by cangyin** [comment]
8b356ba

**Comment by alexey-milovidov** [comment]
Yes, it makes sense to calculate ++it before destroying the element.
