### ISSUE TITLE
Dual password support

### ISSUE THREAD

**Issue by arthurpassos** [ClickHouse/ClickHouse#65136]
**Describe the solution you'd like**

> Add support to dual password to make it easier to rotate passwords. Similar to MySQL 8 implementation: https://www.percona.com/blog/using-mysql-8-dual-passwords/.

Something like mysql impl:

`ALTER USER user1 IDENTIFIED WITH plaintext_password BY 'new_password' RETAIN CURRENT PASSWORD;`
`ALTER USER user1 DISCARD OLD PASSWORD;`

I am willing to spend some time implementing this, but would like to get feedback / ideas first.

**Comment by alexey-milovidov** [comment]
I also need this feature.

However, it should not be limited only to passwords.
Let's allow more than one authentication method for a user.
Each method should allow its settings, such as expiration time for a password.

The alter commands could be: - reset all authentication methods to the new; - add a new authentication method;

**Comment by arthurpassos** [comment]
> I also need this feature.
> 
> However, it should not be limited only to passwords. Let's allow more than one authentication method for a user. Each method should allow its settings, such as expiration time for a password.
> 
> The alter commands could be: - reset all authentication methods to the new; - add a new authentication method.
> 
> The main use-case is setting up short-living secondary passwords and tokens.

Would it always reset to the newest auth method? If so, how would that help with short-living secondary passwords?

**Comment by arthurpassos** [comment]
> Yes, being able to rotate keys with temporary overlap is quite nice. It could also be useful to log which authentication method was used, to help with tracking down forgotten services which didn't update their authentication yet. This would require a way to identify one... maybe generate a ULID, or more simply, store and use the timestamp when the credential was last created/modified. That would let us have a column like authentication_method_timestamp in query log and query by age of the credentials used to find stale ones.

Having a way to uniquely identify credentials would also allow to nitpick which credentials you want to keep instead of only latest, but the question is how to identify it. Perhaps we could keep it simple for now and add this as future work, hopefully without breaking changes

**Comment by arthurpassos** [comment]
@alexey-milovidov Do you think we should accept multiple authentication methods in a single SQL statement? Something like `ALTER USER xyz ADD NEW AUTHENTICATION METHOD IDENTIFIED WITH plaintext_password by 'abc' ADD NEW AUTHENTICATION METHOD IDENTIFIED WITH sha256_password by 'def' ...`.

Looks lengthy to me.

Asking this because since the user can now have multiple authentication methods, `show create user` query should probably print all of those. In order to print all of those, the `authentication_method` field must be turned into a vector. If it is a vector, it is natural that we support setting multiple.

**Comment by arthurpassos** [comment]
There is another question:

Nowadays, if one wants to modify a password, one can do: `ALTER USER user1 IDENTIFIED WITH plaintext_password BY 'abc'`. If we support several authentication methods and the user issues such command, which authentication method will be modified? What is the intended behavior in this case

**Comment by alexey-milovidov** [comment]
> Do you think we should accept multiple authentication methods in a single SQL statement?

Yes, let's do that.

> Nowadays, if one wants to modify a password, one can do: ALTER USER user1 IDENTIFIED WITH plaintext_password BY 'abc'.

It looks like a rewrite of all existing authentication methods into a single new one.
It means, all previous authentication methods are dropped after this command.
