### ISSUE TITLE
Skip Index `set` is not used with IN operator

### ISSUE THREAD

**Issue by DerekChia** [ClickHouse/ClickHouse#65141]
**Describe the unexpected behaviour**

Skip Index `set` is not used with IN operator, but works when using OR. 

**How to reproduce**
* Which ClickHouse server version to use
24.3 (LTS) and 24.5 (stable). This issue started appearing in 24.1. 23.12 still working as expected. 

This does not work:
```
CREATE OR REPLACE TABLE skip_table
(
  my_key UInt64,
  my_value UInt64,
  INDEX vix my_value type set(100) granularity 1
)
ENGINE MergeTree 
primary key my_key
SETTINGS index_granularity=8192;

INSERT INTO skip_table SELECT number, intDiv(number,4096) FROM numbers(1_000_000);

SELECT * FROM skip_table WHERE my_value IN (125, 700) SETTINGS force_data_skipping_indices = 'vix' format Null;

Received exception from server (version 24.5.1):
Code: 277. DB::Exception: Received from localhost:9000. DB::Exception: Index `vix` is not used and setting 'force_data_skipping_indices' contains it. (INDEX_NOT_USED)
```

However, this works:
```
SELECT * FROM skip_table WHERE my_value = 125 or my_value = 700 SETTINGS force_data_skipping_indices = 'vix' format Null;

0 rows in set. Elapsed: 0.006 sec. Processed 8.19 thousand rows, 131.07 KB (1.47 million rows/s., 23.49 MB/s.)
Peak memory usage: 71.23 KiB.
```

**Expected behavior**
Skip index should be used, as illustrated here - https://clickhouse.com/docs/en/optimize/skipping-indexes#basic-operation

**Additional context**
- [24.5 - not working] - https://fiddle.clickhouse.com/f79213a5-79db-4cca-a9a5-dad751edfcd9
- [24.3 - not working] - https://fiddle.clickhouse.com/250be5e8-762d-4234-9eec-5a41acb4ff73
- [24.1 - not working] - https://fiddle.clickhouse.com/a24648d1-1050-42c9-b8b5-f3e4b3621c5e
- [23.1 - working] - https://fiddle.clickhouse.com/dc375df4-9f09-477e-b29a-13d66ea47879
- also to add that `type minmax` is not affected

**Comment by SaltTan** [comment]
works in 24.6 https://fiddle.clickhouse.com/a144f482-9a58-4b63-92a2-42adc671c34f
 * https://github.com/ClickHouse/ClickHouse/pull/62083
