### ISSUE TITLE
Crash in index analysis with tuple

### ISSUE THREAD

**Issue by canhld94** [ClickHouse/ClickHouse#65143]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

> Put your company name or project description here

**Describe what's wrong**

TSAN fuzzer reports data-race: https://s3.amazonaws.com/clickhouse-test-reports/64783/26e82457b9b5f206b7d11ca982f7c8f60ef82d26/ast_fuzzer__tsan_/fatal.log

Can reproduce crash in HEAD https://fiddle.clickhouse.com/ad45f559-876b-4c25-b816-abb1558c3636

```
DROP TABLE IF EXISTS t;
CREATE TABLE t (k1 UInt64, k2 UInt64, v UInt64) ENGINE = ReplacingMergeTree() ORDER BY (k1, k2);
SET optimize_on_insert = 0;
INSERT INTO t VALUES (1, 2, 3) (1, 2, 4) (2, 3, 4), (2, 3, 5);
SELECT (1, k2, v), arrayJoin([tuple((toNullable(1024) * toLowCardinality(toUInt256(1024))) < ((materialize(1024) * 1024) * 200))]) AS row, row.1 AS k FROM t WHERE (k1 != 3) AND (k = 3) ORDER BY 3 ASC, row ASC NULLS FIRST;
```

**Comment by alexey-milovidov** [comment]
Also on 24.5: https://fiddle.clickhouse.com/0ccfa5c2-0fd8-4c36-92ea-86b0cae35fcf

**Comment by alexey-milovidov** [comment]
Also on 24.8.

**Comment by al13n321** [comment]
Minimized a little:
```
DROP TABLE IF EXISTS t;
CREATE TABLE t (x Int8) ENGINE MergeTree ORDER BY x;
INSERT INTO t VALUES (1);
SELECT arrayJoin([tuple((toNullable(10) * toLowCardinality(20)) < materialize(30))]) AS row FROM t WHERE row.1 = 40;
```
