### ISSUE TITLE
weird memory usage/out of memory when inserting

### ISSUE THREAD

**Issue by fancyqlx** [ClickHouse/ClickHouse#6515]
Hi,
Recent, we upgrade our clickhouse from 18.x.x to 19.5.x (may be there are some deferences but it is no problem after double check.) The memory consumption is very weird compared to old version. The following pictures show that the new version of clickhouse did not release the memory after inserting, and it ran out of memory eventually.

![image](https://user-images.githubusercontent.com/6196299/63138890-ad3c5c00-c00e-11e9-8e8f-df5a505df678.png)
old version of inserting

![image](https://user-images.githubusercontent.com/6196299/63138883-a7df1180-c00e-11e9-96cf-deebb2c75194.png)
new version of inserting

After checking code for two days, we found
1. The memory usage behavior is same if we did not renameAndAdd parts after inserting
2. the memory will decrease after merge
3. the memory usage behaves as normal after I enable ASan

Do you any suggestions/ides for this?

**Comment by akuzm** [comment]
Could you check whether this happens on the latest stable release `v19.13.2.19-stable`? If it does, it would be helpful to have the table definition (`show create table`) and some sample data, so that we can try to reproduce this locally.

**Comment by fancyqlx** [comment]
The memory usage became normal after I used FreeThreadPool in AsynchronousBlockInputStream instead of GlobalThreadPool. I guess this kind of thread pool may hold memory in an unexpected way.

**Comment by filimonov** [comment]
@fancyqlx you mean you changed that:
https://github.com/ClickHouse/ClickHouse/blob/2ad4df1d6aa2fbd7d3a030b0e9e4fff9dde8600e/dbms/src/DataStreams/AsynchronousBlockInputStream.h#L99
?

**Comment by blinkov** [comment]
@fancyqlx, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@fancyqlx 

> The memory usage became normal after I used FreeThreadPool in AsynchronousBlockInputStream instead of GlobalThreadPool. I guess this kind of thread pool may hold memory in an unexpected way.

Yes, it may happen due to combination of usage of ThreadPool and specific behaviour of jemalloc.
If the thread does not exit and continues to live, the thread local cache of freed memory is not release to OS by jemalloc.

But this behaviour is actually normal. Users may experience slightly higher memory usage but the memory usage is still bounded. And it should be not much higher.

> the memory usage behaves as normal after I enable ASan

Because jemalloc is disabled under ASan and dynamically linked glibc allocator is used.
