### ISSUE TITLE
The data retrieved with the same query conditions fluctuates up and down, sometimes more and sometimes less!

### ISSUE THREAD

**Issue by xlvchao** [ClickHouse/ClickHouse#65189]
### Company or project name

Honor Terminal Co., Ltd

### Question

I encountered a problem that I'm not sure if you have come across. It's that when there is a sudden surge of traffic and then starts writing to CK very frantically, the query result become unstable. The data retrieved with the same query conditions fluctuates up and down, sometimes more and sometimes less. It takes a while for the query result become stable!

Have you encountered this situation?

**Comment by alifirat** [comment]
I think you have to give more context to your issue with the table engines used for instance, your cluster topology and many more that will clarify your question.

**Comment by den-crane** [comment]
The replication in Clickhouse is eventual consistent. https://clickhouse.com/docs/knowledgebase/read_consistency

**Comment by xlvchao** [comment]
> I think you have to give more context to your issue with the table engines used for instance, your cluster topology and many more that will clarify your question.

cluster size: 10shard, 2replica. engine: ReplicatedMergeTree + Distributed

**Comment by xlvchao** [comment]
> The replication in Clickhouse is eventual consistent. https://clickhouse.com/docs/knowledgebase/read_consistency

Thanks, my big bro!

**Comment by alifirat** [comment]
Did you monitor the replication queue during the specific window of time?

**Comment by Algunenano** [comment]
Please explain exactly what's going on, what queries are you running, what are you seeing and what are you expecting.

**Comment by xlvchao** [comment]
> Did you monitor the replication queue during the specific window of time?

No! How to compare two replicas' replication queue? If the monitoring results are the same, does it mean that we can get stable results by querying again at this time?

**Comment by xlvchao** [comment]
> Did you monitor the replication queue during the specific window of time?

I got it, thanks bro!

**Comment by Algunenano** [comment]
Please explain exactly what's going on, what queries are you running, what are you seeing and what are you expecting.
