### ISSUE TITLE
clickhouse-client: progress bar overflow percentage

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#6519]
![image](https://user-images.githubusercontent.com/327717/63166766-a114c680-c02f-11e9-9ef2-81c2f18cca94.png)

The query progress is on 99 % or 100 % but it is not visible as progress bar overflows it.

Last symbols when copied are `███████%`

**Comment by alexey-milovidov** [comment]
What terminal emulator do you use?
Possible reason: the terminal emulator reports wrong window size.

**Comment by alexey-milovidov** [comment]
Also please run
`echo $COLUMNS`
in bash and verify that the value is correct.

**Comment by simPod** [comment]
I use iTerm2 with zsh and ohmyzsh. `echo $COLUMNS` says 238 on my 13" mac and 272 on my 15" mac. If that's issue only on my PC just feel free to close this, I thought it might be more general issue.
