### ISSUE TITLE
Logical error: Queries with distributed_group_by_no_merge=1 should be processed to Complete stage

### ISSUE THREAD

**Issue by tavplubix** [ClickHouse/ClickHouse#65205]
https://s3.amazonaws.com/clickhouse-test-reports/65184/bf04aebc948b078ba2f00dcb601e89158367422c/ast_fuzzer__ubsan_.html

```
4965721:2024.06.13 01:49:09.427779 [ 161 ] {b2175080-7296-4079-8822-3e16ea8831c8} <Debug> executeQuery: (from [::ffff:127.0.0.1]:49124) (comment: /workspace/ch/tests/queries/0_stateless/02899_distributed_limit_by.gen.sql) EXPLAIN SYNTAX SELECT 'dict_db_01224', 13, toUInt128(13), 13 FROM remote('127.{1,1}') WHERE (dummy + dummy) >= 0 LIMIT 10 BY (dummy + dummy) + materialize(toNullable(0)) AS l SETTINGS prefer_localhost_replica = 1, distributed_group_by_no_merge = 3, distributed_push_down_limit = 255 (stage: Complete)
4965722:2024.06.13 01:49:09.428569 [ 161 ] {b2175080-7296-4079-8822-3e16ea8831c8} <Fatal> : Logical error: 'Queries with distributed_group_by_no_merge=1 should be processed to Complete stage'.
```

cc: @azat

**Comment by azat** [comment]
Interesting.

First of all this query simply cannot fail with this error, since EXPLAIN SYNTAX does not even create interpreter, so the query_id is wrong, I hope that it could be fixed by https://github.com/ClickHouse/ClickHouse/pull/65206

So I've tried to reproduce it somehow, but without luck for now:

```
$ tac server.log | grep -a -o 'executeQuery: (from.*' | grep /workspace/ch/tests/queries/0_stateless/02899_distributed_limit_by.gen.sql | grep -v 'Used settings' | grep -v initial_query_id | sed -E 's#.*sql\) (.*) \(stage:.*#\1;#g' | clickhouse-client --echo --ignore-error -nm |& grep LOGICAL_ERROR
$ tac server.log | grep -a -o 'executeQuery: (from.*' | grep distributed_group_by_no_merge | grep -v 'Used settings' | grep -v initial_query_id | sed -E 's#.*sql\) (.*) \(stage:.*#\1;#g' | clickhouse-client --echo --ignore-error -nm |& grep LOGICAL_ERROR
```

**Comment by alexey-milovidov** [comment]
Also here: https://s3.amazonaws.com/clickhouse-test-reports/67324/7a53a14940ae1be299305548f0d024de7f279fe3/ast_fuzzer__tsan_.html

**Comment by alexey-milovidov** [comment]
`01244_optimize_distributed_group_by_sharding_key.sql`:

`EXPLAIN SYNTAX SELECT 'Get hierarchy', toNullable(13), count() IGNORE NULLS FROM dist_01247 GROUP BY number WITH CUBE SETTINGS distributed_group_by_no_merge = 3`

```
SET prefer_localhost_replica = 0;
SET max_parallel_replicas = 3, cluster_for_parallel_replicas = 'test_cluster_one_shard_three_replicas_localhost', parallel_replicas_for_non_replicated_merge_tree = true;
SET optimize_distributed_group_by_sharding_key = 1;
SET optimize_skip_unused_shards = 1;
SET max_distributed_connections = 1;
SET enable_positional_arguments = 0;
```

**Comment by KochetovNicolai** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/c945209427e759dccfaff5a6af11f2e18c100390/ast_fuzzer__ubsan_.html

**Comment by Avogar** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/71182/f73ff65edb2824a744462dbb4dc760fe22ee3648/ast_fuzzer__debug_.html

**Comment by Avogar** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/73390/bae0e18ef7765fccc1df3fa35df5d1b52689c7cf/ast_fuzzer__debug_.html

**Comment by zhanglistar** [comment]
[Queries with distributed_group_by_no_merge=1 should be processed to Complete stage](https://s3.amazonaws.com/clickhouse-test-reports/71983/ffec230fd75341fca9559e3b67db6276190c2277/ast_fuzzer__debug_.html)

**Comment by zhanglistar** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/71983/ffec230fd75341fca9559e3b67db6276190c2277/ast_fuzzer__debug_.html

**Comment by novikd** [comment]
Repro: https://fiddle.clickhouse.com/3c721798-36d3-4dae-bb54-30b393b2da89

The issue is related to `allow_statistics_optimize` setting and was introduced in #53240 by @hanfei1991 

https://github.com/ClickHouse/ClickHouse/blob/660feb566e4f4052aee4c95dc4a2c30c0d46ca32/src/Interpreters/InterpreterExplainQuery.cpp#L78-L80

`EXPLAIN SYNTAX` tries to interpret (not analyze) query until `FetchColumns` with `allow_statistics_optimize` is enabled.
