### ISSUE TITLE
Engine merge errors after CH restart

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#6526]
1. virtual column **_table String,**  in show create table x_merge
2. virtual column **_table String,**  does not work after CH restart

19.13.1.1066

create table x (z Int64) Engine= MergeTree order by tuple();
CREATE TABLE x_merge as x ENGINE = Merge(default, '^x');
alter table x add column u String;
alter table x_merge add column u String;
show create table x_merge
CREATE TABLE default.x_merge (`z` Int64, **_table String,** u String) ENGINE = Merge(default, '^x')

select count(), _table from x_merge group by _table
ok

/etc/init.d/clickhouse-server restart

select count(), _table from x_merge group by _table
DB::Exception: There is no column with name `_table` in table x. There are columns: z, u.

**Comment by SaltTan** [comment]
Another example:
```
CREATE TABLE x_merge as system.settings ENGINE = Merge(system, '^x');
CREATE TABLE x_memory as x_merge ENGINE = Memory;
show create table x_memory

CREATE TABLE x_memory 
(
  `name`          String,
  `value`         String,
  `changed`       UInt8,
  `description`   String,
  `_table`        String
)
ENGINE = Memory;

```

**Comment by MrBuddyCasino** [comment]
Virtual column handling was changed in those commits, can't spot an obvious error though:
https://github.com/ClickHouse/ClickHouse/commit/cf39c4cc473487650c5848004f2ab41aaacd5fc7#diff-e07f6e9213f722fdd54782f5934373aa
https://github.com/ClickHouse/ClickHouse/commit/7b6c78402d058544905225e2c23c496344d8baf2#diff-e07f6e9213f722fdd54782f5934373aa

**Comment by filimonov** [comment]
19.11.8 is also affected. 

Instead of restart DETACH/ATTACH can be used to make the column disappear.

**Comment by alexey-milovidov** [comment]
Fixed.

**Comment by boqu** [comment]
@alexey-milovidov Could you please share some details about the fix(e.g. commit, release)? Thanks!

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/7183

**Comment by boqu** [comment]
@alexey-milovidov Thank you for your reply! One more question, is there any plan to backport the fix to 19.11 or any old version?

**Comment by alexey-milovidov** [comment]
Only to 19.15 and 19.14.

**Comment by boqu** [comment]
@alexey-milovidov Thank you!
