### ISSUE TITLE
[RFC] Freezing python packages

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#65274]
There is a discussion here and there about "Let's pin all the Python packages in Dockerfile" in the belief that it would solve something. 

And here's my point: It's useless unless we execute `pip freeze` and somehow store the result in between. cc @alexey-milovidov and @Algunenano 

```
> pip freeze --help

Usage:
  pip freeze [options]

Description:
  Output installed packages in requirements format.

  packages are listed in a case-insensitive sorted order.
```

1. The `pip freeze` must be invoked simultaneously when we're sure that the state is 100% correct. Then, it must be stored in the repository to be copied to the image on the later builds.
2. It must be, obviously, architecture dependent.
3. Pinning every package is a nice placebo because it doesn't prevent dependencies from being updated; see the https://github.com/ClickHouse/ClickHouse/pull/65183

**Comment by Algunenano** [comment]
The common way to do it with Python is to generate a lock file and install using that lock file. Since Python has 200 (maybe 201 today) package managers, there are multiple different ways to do it. I'd rather choose one of the existing ones (Pipfile for example) rather than trying to create the 202nd tool with pip freeze.

**Comment by Felixoid** [comment]
I don't have any preference here, but `pip install` is 100% of the way we install packages in Dockerfiles

```
> git grep pip3 docker
docker/test/fasttest/Dockerfile:RUN pip3 install numpy==1.26.3 scipy==1.12.0 pandas==1.5.3 Jinja2==3.1.3
docker/test/fuzzer/Dockerfile:RUN pip3 install Jinja2
docker/test/integration/base/Dockerfile:RUN pip3 install pycurl
docker/test/libfuzzer/Dockerfile:RUN pip3 install Jinja2
docker/test/performance-comparison/Dockerfile:    && pip3 --no-cache-dir install 'clickhouse-driver==0.2.1' scipy \
docker/test/sqllogic/Dockerfile:RUN pip3 install \
docker/test/sqltest/Dockerfile:RUN pip3 install \
docker/test/stateless/Dockerfile:RUN pip3 install numpy==1.26.3 scipy==1.12.0 pandas==1.5.3 Jinja2==3.1.3 pyarrow==15.0.0
docker/test/style/Dockerfile:RUN pip3 install \
```

The main issue is how to update it, because we have `docker/test/stateless/Dockerfile` that installs something, and then we have `docker/test/integration/base/Dockerfile` that uses the latter, and also have installing the packages.

And both need to be non-conflicting, but better combined.

**Comment by alexey-milovidov** [comment]
> The main issue is how to update it

Don't update it at all unless needed. Or at least don't think about it in advance. Pinning dependencies in tests is more important than updating.

**Comment by Felixoid** [comment]
I am afraid you completely missing the point. It's impossible to export anything from the image into the repo.

**Comment by alexey-milovidov** [comment]
Yes, I didn't get the point.

The packages that are used today are of some version. We should pin this version so it does not change.

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/66070
