### ISSUE TITLE
Inserting into a table does not work if the material view that looks at this table is not deleted

### ISSUE THREAD

**Issue by Ddolphh** [ClickHouse/ClickHouse#65293]
We had a material view that looked at one of the tables. When we deleted the destination table, we were no longer able to insert data into the source table until we deleted the materialized view. Not sure if this is expected behavior

**version:** 23.8.1.2992 
**table-source:** ReplacingReplicatedMergeTree - Table staging.transactions
**table-destination:** ReplicatedMergeTree - Table summary_staging.unfinished_hourly 

**mistake that we gained:** DB::Exception: Table summary_staging.unfinished_hourly does not exist. 
**table-source where we coundn't make inserting:** Table staging.transactions

```
CREATE MATERIALIZED VIEW summary_view TO summary_staging.unfinished_hourly
(
    `id` String,
    `company_id` UUID,
    `amount` Decimal(76, 30)
) AS
WITH rn AS
    (
        SELECT
            t.id,
            t.company_id,
            t.amount,
            updated_at_int,
        FROM staging.transactions AS t
        WHERE (updated_at >= '2024-04-08 01:00:00') 
    )
SELECT
    r.id,
    r.company_id,
    r.amount,
    now() AS load_date
FROM rn 

```

**Comment by Algunenano** [comment]
It is expected. You can enable `check_referential_table_dependencies` if you want to disallow this happening again, as it will throw when you try to drop the target table. For example:

```
create table source (a Int64) ENGINE = Log();
create table target (a Int64) ENGINE = Log();
create materialized view mv to target As Select * from source;
set check_referential_table_dependencies=1
drop table target;
```

```
Code: 630. DB::Exception: Cannot drop or rename default.target, because some tables depend on it: default.mv. (HAVE_DEPENDENT_OBJECTS)
```

OTOH, if you want to ignore errors that happen when inserting into the MV, you can instead enable `materialized_views_ignore_errors`, but I'd recommend the first setting instead.

**Comment by Ddolphh** [comment]
@Algunenano Thanks.
But we got mistakes when we tried to insert at table source. And mv looked at it and existed, but table target was dropped. Is it expected too?

**Comment by Algunenano** [comment]
Yes, by default if the MV fails for any reason you will get an error in the INSERT query (but the data on the first table will be inserted)

**Comment by Ddolphh** [comment]
First table you mean source table or what? because we get mistake when trying to insert data there

**Comment by Algunenano** [comment]
Yes, the source table. You get an error on the query.

Keep in mind that the query involves all the insertion, not just the insertion to the source table. The insertion to the target of the materialized view is also part of the query, and if there were chained MV following that first landing table those insertions would also be part of the query. Thus, an error in the execution of any MV is reported as an error in the query.

**Comment by Ddolphh** [comment]
@Algunenano Thank you!
