### ISSUE TITLE
Replica table stuck in read-only (after I manually edited files on disk)

### ISSUE THREAD

**Issue by clcc2019** [ClickHouse/ClickHouse#65317]
env: version 23.8.2.7
After moving my data directory the tables are read only after restart,delete the directory and restart can't solve it

```yaml
2024.06.15 18:53:18.609127 [ 147 ] {} <Error> `507594128159150081`.`.inner.log_mv_api_trace_hours` (ReplicatedMergeTreeRestartingThread): Failed to restart the table. Will try again: Code: 84. DB::Exception: Directory /var/lib/clickhouse/data/507594128159150081/%2Einner%2Elog_mv_api_trace_hours/detached/covered-by-broken_20240615_0_3876_949_try9 already exists and is not empty. (DIRECTORY_ALREADY_EXISTS), Stack trace (when copying this message, always include the lines below):
```

**Comment by SaltTan** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/58126
The workaround: https://github.com/ClickHouse/ClickHouse/issues/58126#issuecomment-1866588458

**Comment by clcc2019** [comment]
> duplicate #58126 The workaround: [#58126 (comment)](https://github.com/ClickHouse/ClickHouse/issues/58126#issuecomment-1866588458)

I didn't do anything, and after restarting, reading and writing were restored
