### ISSUE TITLE
Tests are using table names that are not supported

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#65322]
https://github.com/ClickHouse/ClickHouse/blob/master/tests/queries/0_stateless/01802_rank_corr_mann_whitney_over_window.sql

This test creates table `01802_empsalary`

However, according to docs

> Non-quoted identifiers must match the regex ^[a-zA-Z_][0-9a-zA-Z_]*$.

Is the docs outdated or tests just unconventional? Thanks.

[More context](https://youtrack.jetbrains.com/issue/DBE-16105)

**Comment by alexey-milovidov** [comment]
Support for table names starting with digits was introduced in the MaterlializedMySQL engine for MySQL compatibility.
I wholeheartedly dislike it - for this reason, it is not going to be documented and could be removed.
