### ISSUE TITLE
pagination/streaming support in Clickhouse Grafana plugin

### ISSUE THREAD

**Issue by Alexul** [ClickHouse/ClickHouse#65334]
**Problem**
When visualizing data from CH in Grafana (for example time-series graph with count per 1 minute) plugin waits till CH responds with complete answer. On big timeframes response time from CH can reach minutes, making the interface/user experience slow/bad

**Proposal**
Use pagination to stream response from CH to Grafana in click-house plugin. Graph should start loading in chunks, starting from now() resulting in better user experience. Especially true in scenarios with different storage tiers

**Additional info**
Not clear how to not break alerting queries with that feature. Maybe we need to ask Grafana to add a clear differentiation between alert and user query. That can also be useful to define different users/endpoints in CH grafana plugin for alerts/user queries (typically alerting user need to have more strict query limits)

WDYT?

**Comment by den-crane** [comment]
check https://github.com/trickstercache/trickster

**Comment by SpencerTorres** [comment]
Hey @Alexul , I'm a maintainer for the Grafana plugin and am looking into this suggestion.

If you get a chance, can you move this issue to the Grafana ClickHouse datasource board?
https://github.com/grafana/clickhouse-datasource/issues

This way we'll get more eyes on it from the Grafana team+contributors. Feel free to close this issue after

**Comment by Alexul** [comment]
Hey @SpencerTorres created https://github.com/grafana/clickhouse-datasource/discussions/866
