### ISSUE TITLE
system stop/start consume kafka {kafka_engine_table}

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#6533]
detach/attach MV does not solve a problem of not missing/loosing messages in case of multiple MV.

**Comment by arruzk** [comment]
@den-crane Potential workaround is just dropping a table with `Engine = Kafka`. It will stop consumers. In this case `MVs` will continue exists and you will be able to insert data manually\change offsets\... . After recreating a source table (`Engine = Kafka`) `MVs` will continue consuming data.

**Comment by filimonov** [comment]
> detach/attach MV does not solve a problem of not missing/loosing messages in case of multiple MV.

Detach/attach table with engine=Kafka is the best workaround / without described side effects.

**Comment by fedorkosilov** [comment]
> > detach/attach MV does not solve a problem of not missing/loosing messages in case of multiple MV.
> 
> Detach/attach table with engine=Kafka is the best workaround / without described side effects.

This should be added to the docs

**Comment by den-crane** [comment]
>This should be added to the docs

This the poor workaround, because it's impossible to re-create MV when Kafka engine table is detached.
No sense to add it to the documentation.

**Comment by fedorkosilov** [comment]
Is there a working solution?

**Comment by den-crane** [comment]
```
                                                  ----> matView1
                                                /
kafka --> matView_dummy -> dummy_engine_null ---------> matView2 
                                                \
                                                  ---> matView3                                                
                                              
```

**Comment by fedorkosilov** [comment]
@den-crane Thx!
