### ISSUE TITLE
a problem was happened when i run the clickhouse-test

### ISSUE THREAD

**Issue by codeeeeeeeeeeeee** [ClickHouse/ClickHouse#65363]
### Question

Tag is v22.12.6.22-stable, when i run the clickhouse-test ,an error was happened,message is below:
<Error> TCPHandler: Code: 60. DB::Exception: Table system.query_log doesn't exist. (UNKNOWN_TABLE), Stack trace (when copying this message, always include the lines below):

0. ./build/./contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x18f8bd93 in /usr/local/bin/clickhouse
1. ./build/./src/Common/Exception.cpp:77: DB::Exception::Exception(DB::Exception::MessageMasked const&, int, bool) @ 0x1092b0ba in /usr/local/bin/clickhouse
2. ./build/./contrib/llvm-project/libcxx/include/string:1499: DB::Exception& std::__1::optional<DB::Exception>::emplace[abi:v15000]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int const&, void>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, int const&) @ 0x153806eb in /usr/local/bin/clickhouse
3. ./build/./contrib/llvm-project/libcxx/include/string:1499: DB::DatabaseCatalog::getTableImpl(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>, std::__1::optional<DB::Exception>*) const @ 0x153d9332 in /usr/local/bin/clickhouse
4. ./build/./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:801: DB::DatabaseCatalog::getTable(DB::StorageID const&, std::__1::shared_ptr<DB::Context const>) const @ 0x153dd4a7 in /usr/local/bin/clickhouse
5. ./build/./src/Interpreters/JoinedTables.cpp:0: DB::JoinedTables::getLeftTableStorage() @ 0x15c93a97 in /usr/local/bin/clickhouse
6. ./build/./contrib/llvm-project/libcxx/include/__utility/swap.h:37: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, std::__1::optional<DB::Pipe>, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&, std::__1::shared_ptr<DB::StorageInMemoryMetadata const> const&, std::__1::shared_ptr<DB::PreparedSets>) @ 0x15bdcd2c in /usr/local/bin/clickhouse
7. ./build/./contrib/llvm-project/libcxx/include/optional:260: DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x15bdbe31 in /usr/local/bin/clickhouse
8. ./build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:251: DB::InterpreterSelectWithUnionQuery::buildCurrentChildInterpreter(std::__1::shared_ptr<DB::IAST> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x15c5fd3a in /usr/local/bin/clickhouse
9. ./build/./src/Interpreters/InterpreterSelectWithUnionQuery.cpp:150: DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) @ 0x15c5dd7d in /usr/local/bin/clickhouse
10. ./build/./contrib/llvm-project/libcxx/include/vector:434: std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique[abi:v15000]<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&>(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>&, DB::SelectQueryOptions const&) @ 0x15ba92b3 in /usr/local/bin/clickhouse
11. ./build/./src/Interpreters/InterpreterFactory.cpp:0: DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, std::__1::shared_ptr<DB::Context>, DB::SelectQueryOptions const&) @ 0x15ba8615 in /usr/local/bin/clickhouse
12. ./build/./src/Interpreters/executeQuery.cpp:0: DB::executeQueryImpl(char const*, char const*, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum, DB::ReadBuffer*) @ 0x15ef18d8 in /usr/local/bin/clickhouse
13. ./build/./src/Interpreters/executeQuery.cpp:1087: DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15eef8b6 in /usr/local/bin/clickhouse
14. ./build/./src/Server/TCPHandler.cpp:0: DB::TCPHandler::runImpl() @ 0x16a4e7c4 in /usr/local/bin/clickhouse
15. ./build/./src/Server/TCPHandler.cpp:1940: DB::TCPHandler::run() @ 0x16a5d779 in /usr/local/bin/clickhouse
16. ./build/./contrib/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x18e792e7 in /usr/local/bin/clickhouse
17. ./build/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x18e797cd in /usr/local/bin/clickhouse
18. ./build/./contrib/poco/Foundation/src/ThreadPool.cpp:213: Poco::PooledThread::run() @ 0x18fea107 in /usr/local/bin/clickhouse
19. ./build/./contrib/poco/Foundation/include/Poco/SharedPtr.h:156: Poco::ThreadImpl::runnableEntry(void*) @ 0x18fe7ce3 in /usr/local/bin/clickhouse
20. ? @ 0x7fa43d0d9ac3 in ?
21. ? @ 0x7fa43d16b850 in ?

It look like a table i have not download,pls tell me how can i download this ,thx!

**Comment by cangyin** [comment]
The system.query_log should be configured as per https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server_configuration_parameters-query-log.

It is enabled by default if clickhouse-server is installed.

**Comment by codeeeeeeeeeeeee** [comment]
![Snipaste_2024-06-18_09-20-38](https://github.com/ClickHouse/ClickHouse/assets/46215784/19ddd2d6-b6dc-480b-86cf-4b13767b0fe4)
The query_log doesn't have been created.pls tell me why

**Comment by codeeeeeeeeeeeee** [comment]
and another question is does clickhouse has some test cases without python？pls tell me where i can find these,thank you

**Comment by Algunenano** [comment]
* You need to setup CH config properly.
* You should use a supported release
* There are many tests that don't use python: https://clickhouse.com/docs/en/development/adding_test_queries
