### ISSUE TITLE
Definition of "Injective" for Dictionaries incorrect

### ISSUE THREAD

**Issue by JRoper18** [ClickHouse/ClickHouse#65360]
**Describe the issue**
In the documentation for dictionary in-memory representations (seen [here](https://clickhouse.com/docs/en/sql-reference/dictionaries#storing-dictionaries-in-memory)), it states that:

```
An attribute is called injective if different attribute values correspond to different keys. So when GROUP BY uses a function that fetches an attribute value by the key, this function is automatically taken out of GROUP BY.
```

This is not [the definition of injective](https://en.wikipedia.org/wiki/Injective_function). For example, a dictionary that maps from natural numbers to a tag "EVEN" or "ODD" will map 2 and 4 to "EVEN", which is not injective. However, this dictionary would fit your definition of injective.

Currently, I have a dictionary that fits your definition of injective but not the canonical "mathematical" definition. I'm not sure if I can safely enable the flag for my dictionary or not. Is the in-site definition wrong or does "injectiveness" just mean something else within Clickhouse?

**Comment by den-crane** [comment]
example https://fiddle.clickhouse.com/eb10ab93-f0e7-4b79-98d1-d353d77a2f8f

**Comment by JRoper18** [comment]
I see -- it makes the results of the group by injective, but it's not related to the injective-ness of the underlying dictionary. Thanks!
