### ISSUE TITLE
clickhouse replica reduce from 2 to 1

### ISSUE THREAD

**Issue by qiyuxin** [ClickHouse/ClickHouse#65383]
### Question

In a 3-node clickhouse cluster, how can I change the number of shard replica from 2 to 1? I try to modify the shard configuration in metrika.xml locally like below and restart clickhouse, but the configuration does not take effect
![image](https://github.com/ClickHouse/ClickHouse/assets/29060026/26b511ed-96bf-4087-a76b-ce6dd97662cb)

**Comment by den-crane** [comment]
>locally like below and restart clickhouse, but the configuration does not take effect

What do you mean "does not take effect" ?
Are you aware that replication is loosly related to `<remote_servers>` (distributed) tables? You need to drop replicated tables at a replica as well (or use `system drop replica`).

**Comment by qiyuxin** [comment]
Does not take effect because the test table new created  still keep  2 replica;
drop replicated tables , do you mean deleting one of the original two replicated configurations on the same node ?

**Comment by den-crane** [comment]
it's confusing

>clickhouse replica reduce from 2 to 1
>number of shard replica from 2 to 1?

Shard <> replica
