### ISSUE TITLE
What's the issue with `sumDistinct` ?

### ISSUE THREAD

**Issue by George3d6** [ClickHouse/ClickHouse#6539]
I'm trying to do a query along the lines of:

`SELECT SUM(DISTINCT( (gb_val, weight).2 )) FROM my_table`

But I get exception:
`DB::Exception: Unknown function SUMDistinct. `

However, the same logic works perfectly well with:

`arraySum(arrayMap(lambda(tuple(x), tupleElement(x, 2)), groupUniqArray(tuple(gb_val, weight))))` ... which is slow as ****, presumably due to all the array creation and appending that's going on.

Why is `sumDistinct` not a valid function in this case ? And is there a fundamental issue that would stop it from being implemented ? Is there a more efficient way to go about this problem ?

In my case the same `gb_val` always has the same `weight`, so the distinct is only needed on the `gb_val` column, `ANY` could be applied to weight... but I think that's besides the point.

**Comment by 4ertus2** [comment]
There's only count(distinct ) that replaces with uniqExact() (accordint to count_distinct_implementation setting). You may try to make sum over subselect with group by.

**Comment by George3d6** [comment]
@4ertus2 That's the approach I ended up using since it was fastest (SUM over a sub select with group by), but I feel like implementing sumDistinct, even with the same performance, might feel more coherent. Then again, maybe it's harder than I imagine to do something like this.

If I ever have the time I'll try looking into how that could be implemented...
