### ISSUE TITLE
skip index is invalid

### ISSUE THREAD

**Issue by dimingchan** [ClickHouse/ClickHouse#65399]
### Question

I am testing ClickHouse's hop index:
Step 1, first create the table: 
CREATE TABLE skip_table(
    my_key UInt64,
    my_value UInt64
)
ENGINE MergeTree primary key my_key
SETTINGS index_granularity=8192;
Step 2: Insert one hundred million data: 
    INSERT INTO skip_table SELECT number, intDiv(number,4096) FROM numbers(100000000);
Step 3, add a basic hop count index: 
    ALTER TABLE skip_table ADD INDEX vix  my_value TYPE set(100) GRANULARITY 2;
Step 4, to make existing data effective, execute: 
    ALTER TABLE skip_table MATERIALIZE INDEX vix my_value;
Step 5: Execute the query: 
    SELECT * FROM skip_table WHERE my_value IN (125, 700);
Results:
8,192 rows returned. Elapsed: 0.265 seconds. Processed 100.00 million rows, 800.10 MB (376.67 million rows/s., 3.01 GB/s.).
Peak memory usage: 328.45 KiB.
Scanned 100 million records.

skip index is invalid, what is the reason?

**Comment by den-crane** [comment]
>Scanned 100 million records.

```
SELECT count() FROM skip_table WHERE my_value = 125 or my_value = 700;
Processed 32.77 thousand rows, 262.14 KB
```

Because `IN` does not utilize `set` index.

* https://github.com/ClickHouse/ClickHouse/issues/65141

**Comment by den-crane** [comment]
ah, It's fixed in master

```
SELECT count() FROM skip_table WHERE my_value = 125 or my_value = 700;
   ┌─count()─┐
1. │    8192 │
   └─────────┘

1 row in set. Elapsed: 0.053 sec.


┌─explain────────────────────────────────────────────────────────────┐
│ Expression ((Project names + Projection))                          │
│   Aggregating                                                      │
│     Expression (Before GROUP BY)                                   │
│       Filter ((WHERE + Change column names to column identifiers)) │
│         ReadFromMergeTree (default.skip_table)                     │
│         Indexes:                                                   │
│           PrimaryKey                                               │
│             Condition: true                                        │
│             Parts: 6/6                                             │
│             Granules: 12209/12209                                  │
│           Skip                                                     │
│             Name: vix                                              │
│             Description: set GRANULARITY 1                         │
│             Parts: 1/6                                             │
│             Granules: 2/12209                                      │
└────────────────────────────────────────────────────────────────────┘
```
