### ISSUE TITLE
Restrict a clickhouse user with limited permission to execute queries on system database

### ISSUE THREAD

**Issue by nnaik25** [ClickHouse/ClickHouse#65392]
### Company or project name

Self

### Question

Question : How to restrict a clickhouse user with limited permission to execute queries on tables under system database

Steps:
1) Create a clickhouse db : 
    CREATE DATABASE IF NOT EXISTS <db> ON CLUSTER <cluster>
2) Create a clickhouse db user with limited permission :  
    CREATE USER IF NOT EXISTS <username> ON CLUSTER <cluster> IDENTIFIED BY '$password'
    GRANT SELECT ON <database>.* TO <username>

With above configuration, the user is still table to query data from tables under system database e.g. select version() , select * from system.settings

**Comment by den-crane** [comment]
it's impossible to restrict an access to `select version()` , `system.settings` because they are needed for clients libraries, and they don't expose sensitive information.

**Comment by nnaik25** [comment]
Thanks for your prompt response

**Comment by nnaik25** [comment]
Thanks for your prompt response
