### ISSUE TITLE
Columns of parameterized views don't show up in system.columns after upgrade to 24.2

### ISSUE THREAD

**Issue by Gerrit-K** [ClickHouse/ClickHouse#65402]
**Describe what's wrong**

When querying `system.columns`, there are no rows for parameterized views anymore. This was the case on 24.1.* and is still the case for regular views on all versions.

To reproduce, use this sql (fiddle for [24.1](https://fiddle.clickhouse.com/0e355e50-779c-460e-a185-e56d6f0d147f) and [24.2](https://fiddle.clickhouse.com/fb57b99d-50c6-4990-9e57-026705aff484)):
```sql
CREATE VIEW delete_me_view AS SELECT * FROM system.clusters;
CREATE VIEW delete_me_param_view AS SELECT * FROM system.clusters WHERE cluster = {cluster:String};

select version(), t.name, t.engine, c.name column
from system.tables t
left join system.columns c on c.database = t.database and c.table = t.name
where engine = 'View' and t.name like 'delete%'
order by column desc;
```

On 24.1, this will print all columns twice, once for each view. On 24.2+, there will just be one row with an empty column (due to the left join), which indicates that `system.columns` doesn't have any entries for the parameterized view.

**Affected versions**

As far as we could tell, everything from 24.2 until latest.

**Comment by max-vostrikov** [comment]
Still can be reproduced on latest.
I've tried to check if selecting from the view for the first time adds the columns, but no, still `system.columns` contain nothing from parameterized view.
works on [24.1.8.22](https://fiddle.clickhouse.com/d147cd2c-d7a0-4007-a2b2-c1f2887ec7ce), but `select c.name from system.columns c where c.table like 'param_view';` returns nothing when switching to 24.2+ or  latest

**Comment by Gerrit-K** [comment]
We ran into yet another issue, which likely has the same root cause. We're running Metabase to query ClickHouse and the introspection fails there with the following error:
```
Code: 51. DB::Exception: Empty list of columns in SELECT query. (EMPTY_LIST_OF_COLUMNS_QUERIED) (version 24.5.4.49 (official build))
```
You can reproduce it with this:
```sql
CREATE VIEW delete_me_view AS SELECT * FROM system.clusters;
CREATE VIEW delete_me_param_view AS SELECT * FROM system.clusters WHERE cluster = {cluster:String};

select * from delete_me_param_view where 1<>1 limit 0;
```
Pre-24.2 ([fiddle here](https://fiddle.clickhouse.com/a8e4d78e-f9ca-4cba-8f4b-3faf64b815fc)) this resulted in:
```
Received exception from server (version 24.1.8):
Code: 456. DB::Exception: Received from localhost:9000. DB::Exception: Query parameter `cluster` was not set. (UNKNOWN_QUERY_PARAMETER)
(query: select * from delete_me_param_view where 1<>1 limit 0;)
```
Post-24.2 ([fiddle here](https://fiddle.clickhouse.com/30f5fd18-abde-49d8-bf76-3e029d14680b)) it now throws:
```
Received exception from server (version 24.2.3):
Code: 51. DB::Exception: Received from localhost:9000. DB::Exception: Empty list of columns in SELECT query. (EMPTY_LIST_OF_COLUMNS_QUERIED)
(query: select * from delete_me_param_view where 1<>1 limit 0;)
```

**Comment by novikd** [comment]
Related to #54211

**Comment by novikd** [comment]
Parameterized views don't have a specific schema because it depends on the provided parameters. `DESCRIBE param_view` without arguments can be supported if https://github.com/ClickHouse/ClickHouse/issues/56571 is implemented, but it still would not make sense to add this information into `system.columns` table. Imagine view defined as follows:

```sql
CREATE VIEW v as SELECT CAST(dummy, {t:String});
```

The result type depends on the query parameter.
