### ISSUE TITLE
Backup Formats/Compression Method Allowed

### ISSUE THREAD

**Issue by RickyBoyd** [ClickHouse/ClickHouse#65429]
### Question

Hi,

I'm looking to get some clarity on what all the options are for storage formats and compression method available when using the BACKUP command. The current documentation can be found here: https://clickhouse.com/docs/en/operations/backup. It does list some examples of the various different file extensions that can be used to create a tar but it seems like there's definitely some missing information. I'd like to know exactly:
1. What compression methods can I use?
2. What happens when I use certain file extension names?
3. What are all the options in terms of file extension names and what exactly do they do?
4. If I use certain file extension names, is the compression method ignored?

## Background
I've been experimenting with creating backups recently and I'm basically trying to figure what is the fastest way possible that I can carry out a backup. I've found some of the options to be very slow compared to others. For example doing something like the below is very fast but I'm not too sure if I'm supposed to be even using it or if it's even doing what I expect it should. It seems like it just creates a directory full of data, presumably because all the data is already compressed with lz4 it just does nothing.
```
BACKUP ... SETTINGS compression_method='lz4'
```

Some clarity on this would be really appreciated.

Thanks.

**Comment by nikitamikhaylov** [comment]
I briefly looked into the code and `compression_method` is only used when ClickHouse writes a backup in an archive. Moreover, data is already compressed well (columnar format, etc), so I'm not sure if it can improve things significantly. 

> What are all the options in terms of file extension names and what exactly do they do?

They are used to determine which archive algorithm to use. The whole list of possible extensions can be found here: https://github.com/ClickHouse/ClickHouse/blob/fe92c92ce64a19ce37f24fc51d3167cf9050c1fc/src/IO/Archives/createArchiveWriter.cpp#L29-L30

**Comment by RickyBoyd** [comment]
Thanks for taking a look at this for me.

So if I understand correctly, I can either make a tar, a zip or neither.

If I create a tar then I can compress with various different methods, based on the file extensions the options are:
* zstandard
* lzma
* xz
* bzip2
* gunzip

Then we can also compress when archiving into a zip but what compression methods are supported? Should I assume the same as with when creating a tar?

**Comment by nikitamikhaylov** [comment]
> Should I assume the same as with when creating a tar?

https://github.com/ClickHouse/ClickHouse/blob/fe92c92ce64a19ce37f24fc51d3167cf9050c1fc/src/IO/Archives/TarArchiveWriter.cpp#L11-L18

> Then we can also compress when archiving into a zip but what compression methods are supported?

https://github.com/ClickHouse/ClickHouse/blob/fe92c92ce64a19ce37f24fc51d3167cf9050c1fc/src/IO/Archives/ZipArchiveWriter.cpp#L344-L362

You can read the code located in [this](https://github.com/ClickHouse/ClickHouse/tree/master/src/IO/Archives) folder yourself :) There are not so many lines written there. 

So, you can either determine the compression method by a file extension or force the archive "algorithm" to use a specific codec internally if it is supported.
