### ISSUE TITLE
Table is in readonly mode. TABLE_IS_READ_ONLY. May I ask what the reason is?

### ISSUE THREAD

**Issue by guoxiaolongzte** [ClickHouse/ClickHouse#65424]
### Question
keeper version:23.8.8.20
server version:22.8.10.29

keeper log:
2024.06.18 21:51:23.102727 [ 4143 ] {} <Information> RaftInstance: creating a snapshot for index 12680100000
2024.06.18 21:51:23.102742 [ 4143 ] {} <Information> RaftInstance: create snapshot idx 12680100000 log_term 1
2024.06.18 21:51:23.102747 [ 4143 ] {} <Debug> KeeperStateMachine: Creating snapshot 12680100000
2024.06.18 21:51:23.102769 [ 4143 ] {} <Debug> KeeperStateMachine: In memory snapshot 12680100000 created, queueing task to flush to disk
2024.06.18 21:51:23.102781 [ 4143 ] {} <Information> RaftInstance: create snapshot idx 12680100000 log_term 1 done: 34 us elapsed
2024.06.18 21:51:23.590836 [ 37342 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #120
2024.06.18 21:51:24.538495 [ 4076 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 12680100000 with path /var/lib/clickhouse/coordination/snapshots/snapshot_12680100000.bin.zstd
2024.06.18 21:51:24.538515 [ 4076 ] {} <Trace> KeeperStateMachine: Clearing garbage after snapshot
2024.06.18 21:51:24.539185 [ 4076 ] {} <Trace> KeeperStateMachine: Cleared garbage after snapshot
2024.06.18 21:51:24.539203 [ 4076 ] {} <Information> RaftInstance: snapshot idx 12680100000 log_term 1 created, compact the log store if needed
2024.06.18 21:51:24.539211 [ 4076 ] {} <Information> RaftInstance: log_store_ compact upto 12680000000
2024.06.18 21:51:24.539216 [ 4076 ] {} <Information> KeeperLogStore: Compact logs up to log index 12680000000, our max log id is 12680102261
2024.06.18 21:51:24.539220 [ 4076 ] {} <Information> KeeperLogStore: Removing changelog /var/lib/clickhouse/coordination/logs/changelog_12679900001_12680000000.bin.zstd because of compaction
2024.06.18 21:51:24.539966 [ 4077 ] {} <Information> KeeperLogStore: Removed changelog /var/lib/clickhouse/coordination/logs/changelog_12679900001_12680000000.bin.zstd because of compaction.
2024.06.18 21:51:24.611793 [ 4076 ] {} <Information> KeeperLogStore: Compaction up to 12680000000 finished new min index 12680000001, new max index 12680102261
2024.06.18 21:51:24.614369 [ 4143 ] {} <Debug> KeeperStateMachine: Session ID response 531 with timeout 90000
2024.06.18 21:51:26.234537 [ 49197 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #527
2024.06.18 21:51:26.648092 [ 37342 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #120
2024.06.18 21:51:29.163172 [ 22580 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 127.0.0.1:37842
2024.06.18 21:51:29.163258 [ 22580 ] {} <Debug> KeeperTCPHandler: Receive four letter command srvr
2024.06.18 21:51:29.176872 [ 22580 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 127.0.0.1:37844
2024.06.18 21:51:29.176918 [ 22580 ] {} <Debug> KeeperTCPHandler: Receive four letter command mntr
2024.06.18 21:51:29.965293 [ 37342 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #120
2024.06.18 21:51:31.166423 [ 44922 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #522
2024.06.18 21:51:33.112749 [ 37342 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #120
2024.06.18 21:51:36.200073 [ 37342 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #120
2024.06.18 21:51:37.975494 [ 15604 ] {} <Trace> KeeperTCPHandler: Received heartbeat for session #524
2024.06.18 21:51:39.201392 [ 22580 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 127.0.0.1:37864
2024.06.18 21:51:39.201477 [ 22580 ] {} <Debug> KeeperTCPHandler: Receive four letter command srvr
2024.06.18 21:51:39.214796 [ 22580 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 127.0.0.1:37866

server log:
2024.06.18 21:51:23.962466 [ 18801 ] {} <Warning> risk.ods_risk_event_hourly_log (ReplicatedMergeTreePartCheckThread): Cannot create empty part 604bfc0236198a5651fc8163438f94d8_449_1799_4 instead of lost. Will retry later
2024.06.18 21:51:24.194419 [ 18655 ] {} <Error> risk.ods_risk_event_ads_hourly_log (4732b1ec-b2d4-48f1-b3b3-73967fe8a820): void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999. Coordination::Exception: XID overflow (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3f891a in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x16198136 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x161983bc in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x161e70a2 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
4. Coordination::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::GetResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x161e7549 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
5. zkutil::ZooKeeper::asyncGet(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x161ad5f9 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
6. DB::ReplicatedMergeTreeQueue::pullLogsToQueue(std::__1::shared_ptr<zkutil::ZooKeeper>, std::__1::function<void (Coordination::WatchResponse const&)>, DB::ReplicatedMergeTreeQueue::PullLogsReason) @ 0x15a792e3 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
7. DB::StorageReplicatedMergeTree::queueUpdatingTask() @ 0x155582b0 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
8. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x13f16198 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
9. DB::BackgroundSchedulePool::threadFunction() @ 0x13f18a76 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
10. ? @ 0x13f197ac in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
11. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xa4ba468 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
12. ? @ 0xa4bd67d in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
13. start_thread @ 0x7e25 in /usr/lib64/libpthread-2.17.so
14. clone @ 0xf834d in /usr/lib64/libc-2.17.so
 (version 22.8.10.29 (official build))
2024.06.18 21:51:24.194738 [ 18655 ] {} <Error> risk.ods_risk_event_ads_hourly_log (4732b1ec-b2d4-48f1-b3b3-73967fe8a820): void DB::StorageReplicatedMergeTree::queueUpdatingTask(): Code: 999. Coordination::Exception: XID overflow (Session expired). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3f891a in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) @ 0x16198136 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) @ 0x161983bc in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
3. Coordination::ZooKeeper::pushRequest(Coordination::ZooKeeper::RequestInfo&&) @ 0x161e70a2 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse
4. Coordination::ZooKeeper::get(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void (Coordination::GetResponse const&)>, std::__1::function<void (Coordination::WatchResponse const&)>) @ 0x161e7549 in /usr/hdp/3.1.4.0-315/clickhouse/bin/clickhouse

**Comment by Algunenano** [comment]
The reason is in the error message: `Coordination::Exception: XID overflow`. It is normal and CH should recover

**Comment by guoxiaolongzte** [comment]
> 原因在错误信息中：`Coordination::Exception: XID overflow`。这是正常的，CH 应该会恢复

So how can I solve it? I don't want any errors or restarts in my real-time Flink task.

**Comment by Algunenano** [comment]
Errors are expected in a distributed system and they are fine as long as they don't affect the service. You shouldn't need to restart and CH should recover from this error automatically. You should update to a supported version though
