### ISSUE TITLE
RAM memory keeps growing with 23.12.6.19

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#65425]
Hi guys, we have a server onto which we have a single Clickhouse-Server installation, with 100GB of RAM and several CPU cores. While CPU usage is always constantly depending on the workload, and it doesn't go over some threshold of usage, the RAM keeps growing indefinitely. We do not use distributed, replicated tables, and never used Kafka (which I see normally is correlated with this problems). We have no metrics / async metrics log active for performance / space reasons.

In one week, without any change in the typical workload and not very much more inserted data, we had an increase from 16 GB to 26 GB of used RAM. 

Note: We do often some ALTER DELETE in partitions.

Thanks in advance!

**Comment by Algunenano** [comment]
23.12 is unsupported. Please check with a supported release

**Comment by enzorevo** [comment]
> 23.12 is unsupported. Please check with a supported release

Hi, it is one of the latest stable. Unfortunately, we cannot upgrade it at the moment. Is it a known problem / pattern that was addressed with new versions?
