### ISSUE TITLE
 57/10000 实时翻译 划译 Adding 'aaa' as column after the query statement results in where condition: column='aaa' not working

### ISSUE THREAD

**Issue by zhangyukun230** [ClickHouse/ClickHouse#65422]
Correct select statement：
SELECT 
    '客户数' as index_name, 
    'cust000' as index_code,
     val_main as compute_logic ,
FROM 
    lhm_ofl_customer_mgt 
WHERE 
    target_code = 'cust000' 
    AND date_type = 'month' 
    AND dim_type = 'mgtSign' 
    AND province_name = '江苏省区' 
    AND dept_name = '快递快运事业部' 

The result just one result
Joined  '江苏省区' as province_name,    later changed to： 
SELECT 
    '客户数' as index_name, 
    'cust000' as index_code,
     val_main as compute_logic ,
   '江苏省区' as province_name,
FROM 
    lhm_ofl_customer_mgt 
WHERE 
    target_code = 'cust000' 
    AND date_type = 'month' 
    AND dim_type = 'mgtSign' 
    AND province_name = '江苏省区' 
    AND dept_name = '快递快运事业部' 
the result have. more result.

Troubleshooting findings
Adding ' '江苏省区' as province_name causes   AND province_name = '江苏省区' to become invalid in the 'where' statement

**Comment by Algunenano** [comment]
In CH you can use aliased columns in subsequent columns or the `WHERE` clause.

So if you do:
```
   SELECT 1 AS a
   FROM t
   WHERE a = 1
```

It will always be true, since `1 as a` with take precedence over `t.a`.

You can change this behaviour by setting `prefer_column_name_to_alias`  to ` true`

**Comment by zhangyukun230** [comment]
I think this is unreasonable. In theory, it is to first execute where a=1, and then execute: select 1 AS a  @Algunenano

**Comment by zhangyukun230** [comment]
`SELECT 1 AS a，count(*) as cnt
   FROM t
   WHERE a = 1`
针对这个sql查询，正常来看，应该是先执行where条件 ： a=1  再执行 1 as a, count(*)。 这样会cnt只会 a=1的数量。

**Comment by zhangyukun230** [comment]
SELECT 1 AS a，count(*) as cnt FROM t WHERE a = 1
针对这个sql查询，正常来看，应该是先执行where条件 ： a=1 再执行 1 as a, count(*)。 这样会cnt只会 a=1的数量。

**Comment by zhangyukun230** [comment]
`SELECT 1 AS a，count(*) as cnt FROM t WHERE a = 1`
For this SQL query, normally, it should be executed first under the condition where: a=1 and then 1 as a, count (*). This will only result in a quantity of a=1 for cnt.
However, in reality, he first executes 1 as a, and then executes a=1 This will result in the invalidation of where condition a=1, so cnt is the quantity of all data in table t。 
Is this reasonable？ @Algunenano
