### ISSUE TITLE
Relax "Too many parts" threshold.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6551]
If the server has huge disk shelves, the number of data parts can be large, because the maximum size of a single data part is just 150 GB. Example: a server has 150 TB of storage and there are 1000 data parts in a single partition of 150 GB each.

Proposal: delay inserts or throw an exception only if there are too many parts and their average size is less than a specified threshold (e.g. max_part_size / 10).

**Comment by DenisIsaev** [comment]
@alexey-milovidov can you assign the issue to me?

**Comment by alexey-milovidov** [comment]
@DenisIsaev Ok.
