### ISSUE TITLE
DEFAULT_MARK_CACHE_MAX_SIZE = 5368_MiB

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#65536]
DEFAULT_MARK_CACHE_MAX_SIZE is defined as  `5368_MiB` (which is odd number in general = 5.2GB)

https://github.com/ClickHouse/ClickHouse/blob/932e4bf98242ffc882fe76bde761a8678adf6d7f/src/Core/Defines.h#L93

But in the config it's defined as 5368709120

https://github.com/ClickHouse/ClickHouse/blob/932e4bf98242ffc882fe76bde761a8678adf6d7f/programs/server/config.xml#L413

as a result

```
select name, value, default, changed from system.server_settings where name like 'mark_cache_size';
┌─name────────────┬─value──────┬─default────┬─changed─┐
│ mark_cache_size │ 5368709120 │ 5628755968 │       1 │
└─────────────────┴────────────┴────────────┴─────────┘
```

5368709120 / 1024/1024/1024 = 5
5628755968 / 1024/1024/1024 = 5.2

I suggest to change `DEFAULT_MARK_CACHE_MAX_SIZE` `5120_MiB` (5*1024)
And remove its definition config.xml

@rschu1ze

**Comment by alexey-milovidov** [comment]
That's a good point; let's make a pull request.
