### ISSUE TITLE
Error reading BINARY(16) from mysql

### ISSUE THREAD

**Issue by kimmom** [ClickHouse/ClickHouse#6556]
I have a table in MariaDB having a column where UUIDs are stored as BINARY(16).

When trying to read this in Clickhouse (select transaction_id from mysql('host:3306'...) I get error "Received exception from server (version 19.13.2):
Code: 50. DB::Exception: Received from localhost:9000. DB::Exception: Unsupported type FixedString(16)."

However creating tables with FixedString(16) works fine. Reading all other columns from mysql works too.

ClickHouse client version 19.13.2.19, CentOS 7.

**Comment by Slach** [comment]
still reproduced on Clickhouse 19.17.4

**Comment by filimonov** [comment]
Workaround: create table with Engine=MySQL where that field will be listed as String instead of FixedString.

**Comment by Tiantiandas** [comment]
> Workaround: create table with Engine=MySQL where that field will be listed as String instead of FixedString.

This works for me.

MySQL table:

```
create table t (
`uuid` binary(16),
...
)
```
Clickhouse:

```sql
create table t (
`uuid` String, /* String type */
...
) ENGINE=MYSQL(....);
```
