### ISSUE TITLE
how to convert -array aggregation functions into regular function?

### ISSUE THREAD

**Issue by yangguang760** [ClickHouse/ClickHouse#65560]
I'm trying to calculate cumulative stddev of a array. But the query is invalid.

select  arrayFold(acc,x->[
    arrayConcat(acc[1],[x]),
     arrayConcat(acc[2],[stddevSampArray(acc[1]) ])],
                  num,
                  [emptyArrayInt32(),emptyArrayFloat32()]
        ) from (
                  select [1,2,3,4,5] as num
              );

**Comment by den-crane** [comment]
it should be like this  https://fiddle.clickhouse.com/ed7c1756-efa1-4772-92a3-03554f32953b

```sql
select arrayFold(acc,x->[
arrayConcat(acc[1],[x]),
arrayConcat(acc[2],[arrayReduce('stddevSamp', acc[1]) ])],
num,
[emptyArrayInt32(),emptyArrayFloat32()]
) from (
  select [1,2,3,4,5] as num
);
```

You need to calculate stddevSamp for a row not for a rowset. See the difference https://fiddle.clickhouse.com/27b33b65-e573-4b56-bff4-5efdada0cf48 stddevSampArray -- still is aggregate function.

https://clickhouse.com/docs/en/sql-reference/functions/array-functions#arrayreduce

**Comment by yangguang760** [comment]
@den-crane Thank you so much for your helpful response on GitHub. It was exactly what I needed!
