### ISSUE TITLE
Insert error for materialized views with multiple CTEs

### ISSUE THREAD

**Issue by MalkmusT** [ClickHouse/ClickHouse#65598]
**Describe what's wrong**

We recently update from CH version ClickHouse 24.4.1.2088 to ClickHouse 24.5.3.5 and figured out the inserts on source tables with attached materialized view with multiple CTEs  result in an ' Not found column' error

We expect that the insert is accepted without errer as in the pervious version.

**How to reproduce**

You can reproduce the error via:
```
 CREATE TABLE mv_test
(
    `id` UInt64,
    `ref_id` UInt64,
    `final_id` Nullable(UInt64),
    `display` String
)
ENGINE = Log;

CREATE TABLE mv_test_target
(
    `id` UInt64,
    `ref_id` UInt64,
    `final_id` Nullable(UInt64),
    `display` String
)
ENGINE = Log;

CREATE MATERIALIZED VIEW mv_test_mv TO mv_test_target
(
    `id` UInt64,
    `ref_id` UInt64,
    `final_id` Nullable(UInt64),
    `display` String
)
AS WITH
    tester AS
    (
        SELECT
            id,
            ref_id,
            final_id,
            display
        FROM mv_test
    ),
    id_set AS
    (
        SELECT
            display,
            max(id) AS max_id
        FROM mv_test
        GROUP BY display
    )
SELECT *
FROM tester
WHERE id IN (
    SELECT max_id
    FROM id_set
);

insert into mv_test ( id, ref_id, display) values ( 1, 2, 'test');
```

On my test system this results in an 
```
Code: 10. DB::Exception: Not found column __table1.max_id: in block : while pushing to view default.mv_test_mv (eb544596-a97b-4c95-89af-4d8c6fc2c77a). (NOT_FOUND_COLUMN_IN_BLOCK) (version 24.5.3.5 (official build)
```

**Does it reproduce on the most recent release?**
Tested in version ClickHouse 24.5.3.5

**Comment by den-crane** [comment]
@KochetovNicolai  https://fiddle.clickhouse.com/20383894-5baf-4848-84ab-faa6c3c2678f worked in 24.4, works without experimental_analyzer

**Comment by MalkmusT** [comment]
@den-crane thanks for the hint about the experimental analyzer.
Unfortunatly this is not an option for us. Hence we wait for a future fix.

**Comment by novikd** [comment]
It also reproduces when CTEs are inlined into the `SELECT` query.

**Comment by maxjustus** [comment]
I've tested a number of variations on MV queries to try and isolate this failure in the new analyzer and it seems to happen specifically when a column being used in the subquery passed to a `where in` clause comes from a CTE _and_ the selected column(s) in the `where in` subquery include any aliases. Here's a simple demonstration:

### this does not work:

https://fiddle.clickhouse.com/2fe95db6-600e-4712-a39d-d24769e10e3c

```sql
create or replace table test_table engine=MergeTree order by tuple() as select 1 as col1;

drop view if exists test_mv;
create materialized view test_mv engine=MergeTree order by tuple() as
with
    subquery_on_source as (select col1 as aliased from test_table),
    output as (select * from test_table where col1 in (select aliased from subquery_on_source))
select * from output;

insert into test_table values (2);
```

### this works:

https://fiddle.clickhouse.com/3d65365f-4f37-4c4f-b0ec-0cafd40a2e9e

```sql
create or replace table test_table engine=MergeTree order by tuple() as select 1 as col1;

drop view if exists test_mv;
create materialized view test_mv engine=MergeTree order by tuple() as
with
    subquery_on_source as (select col1 from test_table),
    output as (select * from test_table where col1 in (select col1 from subquery_on_source))
select * from output;

insert into test_table values (2);
```

**Comment by filimonov** [comment]
There some similar scenarios broken: https://fiddle.clickhouse.com/0cb2c3ed-d9f4-456a-b0d2-89c1d4bc8b8d
