### ISSUE TITLE
Code: 100. DB::Exception: Unknown packet 227213735 from server clickhouse-node3:9000: While executing Remote. (UNKNOWN_PACKET_FROM_SERVER) (version 24.1.2.5 (official build))

### ISSUE THREAD

**Issue by qw4285632q** [ClickHouse/ClickHouse#65603]
### Question

**version :24.1.2.5** 
**sql:** 
select
	clientid as companyid,
	count(DISTINCT if(businesstype = 6, projectid, null)) as pubCountTB2,
	count(DISTINCT if(businesstype = 6 and dealstatus = 1, projectid, null)) as dealCountTB2,
	count(DISTINCT if(businesstype = 6 and dealstatus = 1, projectid, null)) as dealCountALL2
from
	yzc_dw.t_yzcwideproject
where
	expstatus = 0
group by
	clientid

 **yzc_dw.t_yzcwideproject table ddl :**
CREATE TABLE yzc_dw.t_yzcwideproject
(
    `id` String,
    `projectid` String,
    `businesstype` Nullable(Int8),
    `expstatus` Nullable(Int8),
    `clientid` Nullable(String),
)
ENGINE = Distributed('bigdata_3shards_2replicas',
 'yzc_dw',
 't_yzcwideproject_local',
 rand())

**t_yzcwideproject_local ddl:**
CREATE TABLE yzc_dw.t_yzcwideproject
(
    `id` String,
    `projectid` String,
    `businesstype` Nullable(Int8),
    `expstatus` Nullable(Int8),
    `clientid` Nullable(String),
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/{uuid}',
 '{replica}')
PRIMARY KEY id
ORDER BY id
SETTINGS index_granularity = 8192

My clickhouse cluster is a 3-shard 1-replica cluster, with a total of 6 servers. Every time I execute the above sql, four nodes do not report an error, and two nodes report an error. When I change the count(DISTINCT if(businesstype = 6, projectid, null)) as pubCountTB2 condition to count(DISTINCT if(businesstype = 6, projectid, '')) as pubCountTB2, there will be no error.

**Comment by Algunenano** [comment]
Please upgrade to a supported release and, if possible, provide a reproducer and the full stacktace.
