### ISSUE TITLE
Unexpected result of query with enabled experimental analyzer

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#65609]
ClickHouse v.24.5.3.5

The same code returns different results with and without the `allow_experimental_analyzer` setting

**allow_experimental_analyzer = 0 return 1 record**
```
SELECT 1
FROM (select toDate('2024-06-24') as dt)
WHERE dt IN
      (toDateTime('2024-06-23 00:00:00'), toDateTime('2024-06-24 00:00:00'))
settings allow_experimental_analyzer = 0;
```

**allow_experimental_analyzer = 1 return nothing**
```
SELECT 1
FROM (select toDate('2024-06-24') as dt)
WHERE dt IN
      (toDateTime('2024-06-23 00:00:00'), toDateTime('2024-06-24 00:00:00'))
settings allow_experimental_analyzer = 1;
```

**Comment by Algunenano** [comment]
Looks fixed in master. Need to confirm what fixed it and add a test if necessary
