### ISSUE TITLE
G++ 9 crashes during clickhouse compilation

### ISSUE THREAD

**Issue by rafaeldtinoco** [ClickHouse/ClickHouse#6560]
Reference:
Ubuntu Bug LP: #1840511
https://bugs.launchpad.net/ubuntu/+source/bareos/+bug/1840485/

Operating system
Ubuntu Eoan (in development, to be frozen Aug 22)

Cmake version
3.13.4

Ninja version
1.9.0

Compiler name and version

gcc (Ubuntu 9.2.0-1ubuntu1) 9.2.0
and
gcc-8 (Ubuntu 8.3.0-19ubuntu1) 8.3.0

Full cmake and/or ninja output

Clickhouse build output:
https://launchpadlibrarian.net/429654087/buildlog_ubuntu-eoan-amd64.clickhouse_18.16.1+ds-4build1_BUILDING.txt.gz

G++ 9 crash output:
Check attached file out in upstream bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91493#add_comment

**Comment by alexey-milovidov** [comment]
We are using gcc 9.1.0 for production builds right now:
https://clickhouse-builds.s3.yandex.net/6550/9e2537a7d09ebee108ea2e68a6d6b2f282f528f1/build_log_490262189_1566238254.txt

**Comment by rafaeldtinoco** [comment]
It could be related to the architecture intrinsic as I'm currently using an old AMD CPU:

model name      : AMD FX(tm)-8350 Eight-Core Processor
stepping        : 0
microcode       : 0x6000852

But I'll let upstream to investigate as I can simply mitigate this using:

[PATCH] G++ 9 crashes returning exception using ? true : false syntax

The following function:

std::string toString(const ColumnDefaultKind kind)
{
    static const std::unordered_map<ColumnDefaultKind, std::string> map{
        { ColumnDefaultKind::Default, AliasNames::DEFAULT },
        { ColumnDefaultKind::Materialized, AliasNames::MATERIALIZED },
        { ColumnDefaultKind::Alias, AliasNames::ALIAS }
    };

    const auto it = map.find(kind);

    return it != std::end(map) ? it->second : throw Exception{"Invalid ColumnDefaultKind", ErrorCodes::LOGICAL_ERROR};
}

causes gcc9 to crash while other similar function (in related syntax):

ColumnDefaultKind columnDefaultKindFromString(const std::string & str)
{
    static const std::unordered_map<std::string, ColumnDefaultKind> map{
        { AliasNames::DEFAULT, ColumnDefaultKind::Default },
        { AliasNames::MATERIALIZED, ColumnDefaultKind::Materialized },
        { AliasNames::ALIAS, ColumnDefaultKind::Alias }
    };

    const auto it = map.find(str);

    return it != std::end(map) ? it->second : throw Exception{"Unknown column default specifier: " + str, ErrorCodes::LOGICAL_ERROR};
}

does not. Changing the syntax to:

std::string toString(const ColumnDefaultKind kind)
{
    static const std::unordered_map<ColumnDefaultKind, std::string> map{
        { ColumnDefaultKind::Default, AliasNames::DEFAULT },
        { ColumnDefaultKind::Materialized, AliasNames::MATERIALIZED },
        { ColumnDefaultKind::Alias, AliasNames::ALIAS }
    };

    const auto it = map.find(kind);

    if (it == std::end(map))
        throw Exception{"Invalid ColumnDefaultKind", ErrorCodes::LOGICAL_ERROR};

    return it->second;
}

fixes the issue.

Upstream bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91493
---
 dbms/src/Storages/ColumnDefault.cpp | 12 ++++++++++--
 1 file changed, 10 insertions(+), 2 deletions(-)

diff --git a/dbms/src/Storages/ColumnDefault.cpp b/dbms/src/Storages/ColumnDefault.cpp
index 19ba69c..27b8eb0 100644
--- a/dbms/src/Storages/ColumnDefault.cpp
+++ b/dbms/src/Storages/ColumnDefault.cpp
@@ -31,7 +31,11 @@ ColumnDefaultKind columnDefaultKindFromString(const std::string & str)
     };

     const auto it = map.find(str);
-    return it != std::end(map) ? it->second : throw Exception{"Unknown column default specifier: " + str, ErrorCodes::LOGICAL_ERROR};
+
+    if (it == std::end(map))
+        throw Exception{"Unknown column default specifier: " + str, ErrorCodes::LOGICAL_ERROR};
+
+    return it->second;
 }


@@ -44,7 +48,11 @@ std::string toString(const ColumnDefaultKind kind)
     };

     const auto it = map.find(kind);
-    return it != std::end(map) ? it->second : throw Exception{"Invalid ColumnDefaultKind", ErrorCodes::LOGICAL_ERROR};
+
+    if (it == std::end(map))
+        throw Exception{"Invalid ColumnDefaultKind", ErrorCodes::LOGICAL_ERROR};
+
+   return it->second;
 }


--
2.20.1

**Comment by rafaeldtinoco** [comment]
I just opened this issue to track it for the future (for you). 
I'll probably include a mitigation now for our build servers.

**Comment by rafaeldtinoco** [comment]
This has also been opened by clickhouse Debian maintainer:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91500

**Comment by alexey-milovidov** [comment]
Minor, because you can use gcc-8 or clang (versions 7, 8, 9 are Ok).
Compiler bugs are quite common.
