### ISSUE TITLE
How to fix the leading space in prompt?

### ISSUE THREAD

**Issue by Jack012a** [ClickHouse/ClickHouse#65623]
### Question

```
ClickHouse client version 24.3.2.23 (official build).
Connecting to 127.0.0.1:9000 as user default.
Connected to ClickHouse server version 24.3.2.

Warnings:
 * Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.

hostname :)         select
```

I expected to see the following:
`hostname :) select`

Question> There is a leading space in front of each query statement on the prompt. Is there a way to fix this problem?

Thank you

**Comment by melvynator** [comment]
I think the closes you will be able to get it, is by following this: https://clickhouse.com/docs/knowledgebase/change-the-prompt-in-clickhouse-client 

But not sure you can completely remove the space.

**Comment by Jack012a** [comment]
I saw that config and tried. but it doesn't work.

It is a new issue on my end. It used to be good.
The issue is that the system will automatically insert a TAB? in front of the query. Very annoying.

Thank you

**Comment by melvynator** [comment]
> I saw that config and tried. but it doesn't work.

You mean it doesn't solve the issue on your end or it just doesn't work as it should?

**Comment by Algunenano** [comment]
It does not reproduce here:
```
$ /mnt/ch/official_binaries/clickhouse-common-static-24.3.2.23/usr/bin/clickhouse client
ClickHouse client version 24.3.2.23 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.7.1.

ClickHouse client version is older than ClickHouse server. It may lack support for new features.

Warnings:
 * Effective user of the process (raul) does not match the owner of the data (root).
 * Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled
 * Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.

Mordor :) Select 1

SELECT 1

Query id: 572f0122-ba10-4be9-b7bc-27c3a19da08b

   ┌─1─┐
1. │ 1 │
   └───┘

1 row in set. Elapsed: 0.001 sec. 

Mordor :)
```

* What OS are you using?
* Can you check if it happens with a different shell?
* And with a different terminal?

**Comment by Jack012a** [comment]
Oracle Linux Server release 8.9

It does happen with a different shell and terminal.

What happens is that the terminal will insert a Tab? before it allows me to enter a new query.

Thank you

**Comment by Algunenano** [comment]
This is odd. I assume Oracle Linux packages should be pretty much the same as other Linux distributions, so I don't know what's going on.

Could you check:
* A more recent build / Different versions?
* Connecting to a different server?
* What happens if you run `clickhouse local` instead? Do you also get the extra spaces after the prompt?
