### ISSUE TITLE
Why merge process took exactly that amount of time on *GraphiteMergeTree ?

### ISSUE THREAD

**Issue by MetikovVadim** [ClickHouse/ClickHouse#6562]
Hello there.

In our cluster we have two identical tables:
CREATE TABLE graphite_day
(
    Path String,
    Value Float64,
    Time UInt32 CODEC(LZ4),
    Date Date,
    Timestamp UInt32 CODEC(LZ4)
)
ENGINE = ReplicatedGraphiteMergeTree('/clickhouse/tables/{shard}/graphite_day', '{replica}', 'graphite_rollup')
PARTITION BY Date
ORDER BY (Path, Time)
SETTINGS index_granularity = 8192

and 

CREATE TABLE graphite_reverse
(
    Path String,
    Value Float64,
    Time UInt32,
    Date Date,
    Timestamp UInt32
)
ENGINE = ReplicatedGraphiteMergeTree('/clickhouse/tables/{shard}/graphite_reverse', '{replica}', 'graphite_rollup_null')
PARTITION BY Date
ORDER BY (Path, Time)
SETTINGS index_granularity = 8192

We write identical data in both tables (reversed metric Path to second table).

The problem is that merges on first tabes runs much longer and most of time we can see such situation:

SELECT 
    table, 
    floor(elapsed, 2) AS elapse, 
    floor(progress, 2) AS progres, 
    floor((elapsed / progress) * (1 - progress), 2) AS estimate, 
    result_part_name
FROM system.merges 
ORDER BY estimate ASC

┌─table──────┬──elapse─┬─progres─┬─estimate─┬─result_part_name─┐
│ graphite_day     │   25.66 │     0.9 │     2.58 │ 20190820_26556_26563_1 │
│ graphite_day     │   18.03 │    0.49 │    18.03 │ 20190820_26564_26569_1 │
│ graphite_day     │    1.62 │    0.05 │    29.19 │ 20190820_26577_26583_1 │
│ graphite_day     │     9.1 │    0.19 │    37.32 │ 20190820_26570_26576_1 │
│ graphite_reverse │  187.78 │    0.77 │    53.42 │ 20190820_25847_26431_4 │
│ graphite_day     │   69.96 │    0.49 │    72.25 │ 20190820_26465_26503_2 │
│ graphite_day     │  162.52 │    0.68 │    74.24 │ 20190820_26101_26346_3 │
│ graphite_day     │   23.98 │    0.11 │   177.33 │ 20190820_26504_26542_2 │
│ graphite_day     │ 1428.69 │    0.76 │   447.75 │ 20190820_20869_25387_5 │

SELECT 
    table, 
    floor(elapsed, 2) AS elapse, 
    floor(progress, 2) AS progres, 
    floor((elapsed / progress) * (1 - progress), 2) AS estimate, 
    result_part_name
FROM system.merges 
ORDER BY estimate ASC

┌─table──────┬elapse┬progres┬estimate─┬─result_part_name─┐
│ graphite_day     │   25.66 │     0.9 │     2.58 │ 20190820_26556_26563_1 │
│ graphite_day     │   18.03 │    0.49 │    18.03 │ 20190820_26564_26569_1 │
│ graphite_day     │    1.62 │    0.05 │    29.19 │ 20190820_26577_26583_1 │
│ graphite_day     │     9.1 │    0.19 │    37.32 │ 20190820_26570_26576_1 │
│ graphite_reverse │  187.78 │    0.77 │    53.42 │ 20190820_25847_26431_4 │
│ graphite_day     │   69.96 │    0.49 │    72.25 │ 20190820_26465_26503_2 │
│ graphite_day     │  162.52 │    0.68 │    74.24 │ 20190820_26101_26346_3 │
│ graphite_day     │   23.98 │    0.11 │   177.33 │ 20190820_26504_26542_2 │
│ graphite_day     │ 1428.69 │    0.76 │   447.75 │ 20190820_20869_25387_5 │
│ graphite_reverse │  2431.5 │    0.79 │   634.71 │ 20190820_16303_24638_6 │
│ graphite_day     │ 7136.08 │    0.91 │   658.77 │ 20190820_0_20868_56    │
└──────────┴──────┴─────┴──────┴─────────────────┘

The difference is only one: first table uses 255 rules for rollup while second table have no rules.
We have removed all rules with age from 0 to 86400. We wanted to get equal merge time. But we have avarage ratio 1:4 1:5 between tables on all three replicas.

Why merger look into rollup RE when there is no rules for today's inserts ?

**Comment by 4ertus2** [comment]
> We write identical data in both tables (reversed metric Path to second table).

Could you check the time of 'insert-select + optimize final' for tables with one column Path and reserved Path? Just to be sure it's not the reason of difference.

**Comment by MetikovVadim** [comment]
Thank you for your answer. I will try it soon.

**Comment by MetikovVadim** [comment]
When i attached backuped 1 partition of both tables on staging and run OPTIMIZE table ... PARTITION '2019-08-22' i get the same results:
SELECT 
    table, 
    floor(elapsed, 2) AS elapsed1, 
    floor(progress, 2) AS progress1, 
    floor((elapsed / progress) * (1 - progress), 2) AS estimated, 
    result_part_name
FROM system.merges 
ORDER BY estimated ASC

┌─table──────────────────┬─elapsed1─┬─progress1─┬─estimated─┬─result_part_name──┐
│ graphite_day_test1     │    56.31 │         0 │  22632.01 │ 20190822_1_11_115 │
│ graphite_reverse_test2 │    36.12 │         0 │  23627.35 │ 20190822_1_15_96  │
└────────────────────────┴──────────┴───────────┴───────────┴───────────────────┘

2 rows in set. Elapsed: 0.003 sec.

**Comment by MetikovVadim** [comment]
Now i try to count the  INSERT ... SELECT ... for both tables command time.

**Comment by MetikovVadim** [comment]
I created a reduced table with only two columns(Date Date , Path String). After merging i will try to insert into new tables and optimize them and record consumed time.

**Comment by MetikovVadim** [comment]
I run INSERT ... SELECT ...
Both of requests are completed less than 1% and i get 1 running merge :
SELECT 
    table, 
    floor(elapsed, 2) AS elapsed1, 
    floor(progress, 2) AS progress1, 
    floor((elapsed / progress) * (1 - progress), 2) AS estimated, 
    result_part_name
FROM system.merges 
ORDER BY estimated ASC

┌─table────────┬─elapsed1─┬─progress1─┬─estimated─┬─result_part_name─────┐
│ graphite_day │     7.54 │      0.56 │      5.73 │ 20190827_3691_3961_5 │
└──────────────┴──────────┴───────────┴───────────┴──────────────────────┘
But most of time when i request i get zero rows in result.

**Comment by MetikovVadim** [comment]
On 5% I catched one merge on non-rollup table:
┌─table───────┬elapsed1┬progress1┬estimated┬result_part_name──────┐
│ graphite_reverse │        3.7 │      0.85   │      0.64   │ 20190827_4177_4193_2 │
└───────────┴──────┴──────┴───────┴────────────────┘

**Comment by MetikovVadim** [comment]
The experiment was interrupted with message:
Code: 252. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Too many parts (3000). Merges are processing significantly slower than inserts.. 
in both cases. Why CH does not merge inserted data ?

**Comment by MetikovVadim** [comment]
That is the root of error:
OPTIMIZE TABLE graphite_day_test2 PARTITION '2019-08-22'

Received exception from server (version 19.5.4):
Code: 10. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Not found column Time in block. There are only columns: Date, Path.

**Comment by MetikovVadim** [comment]
I have recreated tables with all columns. During INSERT(5% of both tables) i get very short merge:
┌─table──────────┬─elapsed1┬progress1┬estimated─┬─result_part_name─┐
│ graphite_day_test2     │     0.13 │      0.07 │      1.64 │ 20190822_2668_2803_27 │
│ graphite_reverse_test3 │     0.04 │      0.01 │      2.22 │ 20190822_2607_2797_38 │
└───────────┴──────────┴───────┴────────┴─────────────┘

**Comment by MetikovVadim** [comment]
On 10% we could see the different merge duration:
┌─table──────────┬elapsed1┬progress1┬estimated┬─result_part_name─┐
│ graphite_reverse_test3 │     0.41 │      0.24 │      1.27 │ 20190822_4971_5132_30 │
│ graphite_day_test2     │     3.15 │      0.63 │      1.79 │ 20190822_4968_5120_30 │

**Comment by MetikovVadim** [comment]
After INSERT I run OPTIMIZE TABLE ... PARTITION ... 
on both tables. I get :
┌─table─────────┬─elapsed1┬progress1┬estimated┬result_part_name─┐
│ graphite_reverse_test3 │     6.88 │       0.6 │      4.49 │ 20190822_1_48245_104 │
│ graphite_day_test2     │     4.54 │      0.02 │    211.24 │ 20190822_1_48243_82  │
└───────────────┴─────┴─────┴──────┴─────────────────┘

**Comment by MetikovVadim** [comment]
Insertion took the same time:
0 rows in set. Elapsed: 48626.413 sec. Processed 50.60 billion rows, 6.06 TB (1.04 million rows/s., 124.68 MB/s.)
and
0 rows in set. Elapsed: 48974.664 sec. Processed 50.60 billion rows, 6.06 TB (1.03 million rows/s., 123.79 MB/s.)

After INSERT I run OPTIMIZE TABLE ... PARTITION ... 
on both tables. I get :
┌─table─────────┬─elapsed1┬progress1┬estimated┬result_part_name─┐
│ graphite_reverse_test3 │     6.88 │       0.6 │      4.49 │ 20190822_1_48245_104 │
│ graphite_day_test2     │     4.54 │      0.02 │    211.24 │ 20190822_1_48243_82  │
└───────────────┴─────┴─────┴──────┴─────────────────┘

**Comment by MetikovVadim** [comment]
I have reduced rollup rules from 255 to 15 and get only 1-3 parralel merge process. Also amount of active parts reduced from 100+ to 30-40.
Im closing the ticket.
