### ISSUE TITLE
There is a bug in decimal data comparison

### ISSUE THREAD

**Issue by y-shine** [ClickHouse/ClickHouse#65645]
Version:
ClickHouse server version 24.5.1.1763 (official build).

data script:
create table test_float2
     (lonlat Decimal(15,2))
ENGINE = MergeTree
ORDER BY (lonlat)
SETTINGS index_granularity = 8192 

insert into test_float2 values(1124068.80);
insert into test_float2 values(1111066.90);
insert into test_float2 values(1121068.75);

select * from test_float2 where lonlat in(1124068.8,1111066.9,1121068.75);

test result:
test.novalocal :) select * from test_float2;

SELECT *
FROM test_float2

Query id: 2ade7308-9fdc-495c-944e-f3b82605b5c2

   ┌────lonlat─┐
1. │ 1111066.9 │ -- 1.11 million
   └───────────┘
   ┌────lonlat─┐
2. │ 1124068.8 │ -- 1.12 million
   └───────────┘
   ┌─────lonlat─┐
3. │ 1121068.75 │ -- 1.12 million
   └────────────┘

3 rows in set. Elapsed: 0.006 sec. 

test.novalocal :) select * from test_float2 where lonlat in(1124068.8,1111066.9,1121068.75);

SELECT *
FROM test_float2
WHERE lonlat IN (1124068.8, 1111066.9, 1121068.75)

Query id: 78292b53-7bbd-4cd9-a268-a904e6b68f14

   ┌─────lonlat─┐
1. │ 1121068.75 │ -- 1.12 million
   └────────────┘
   ┌────lonlat─┐
2. │ 1124068.8 │ -- 1.12 million
   └───────────┘

2 rows in set. Elapsed: 0.005 sec.

test.novalocal :) select * from test_float2 where  lonlat=1111066.9;

SELECT *
FROM test_float2
WHERE lonlat = 1111066.9

Query id: 4871261f-e1d9-464d-82d2-72bcd9fcf148

   ┌────lonlat─┐
1. │ 1111066.9 │ -- 1.11 million
   └───────────┘

1 row in set. Elapsed: 0.005 sec.

Problem description:
Obviously, the lonlat=1111066.9 record is missing when the in operator is used

**Comment by nickitat** [comment]
values contained in the set are not Decimals, likely it is the reason: https://fiddle.clickhouse.com/eb1834a6-048e-44f7-9bb2-8f2811aad8fc

**Comment by nickitat** [comment]
related discussion happened here: https://github.com/ClickHouse/ClickHouse/issues/5690

I personally think it would be a good usability improvement. juts don't convert to floats straight away, use more precise type.
e.g. postgres seems to use `numeric` which is `user-specified precision, exact`

```
 Seq Scan on test_float2  (cost=0.00..34.34 rows=27 width=18)
   Filter: (lonlat = ANY ('{1124068.8,1111066.9,1121068.75}'::numeric[]))
```
