### ISSUE TITLE
Unable to restore backups of tables with Object('json') column

### ISSUE THREAD

**Issue by faisal00813** [ClickHouse/ClickHouse#65653]
* Which ClickHouse server version to use

 ClickHouse version `23.10.4`

Client `DBEAVER`

DDL
```
CREATE TABLE default.vista_app_events
(


    `sid` Nullable(String),

    `ownerType` Nullable(String),

    `project` Nullable(String),

    `version` Nullable(String),

    `tags` Array(Nullable(String)),

    `actionType` Nullable(String),

    `payload` Object('json'),

    `environment` Nullable(String),

)
ENGINE = MergeTree
PRIMARY KEY (sid)
ORDER BY (sid)
SETTINGS allow_nullable_key = 1,
 index_granularity = 8192;
```

I used following commands to backup and restore.
Backup was successful  but restore failed.
```
BACKUP TABLE vista_app_events_v2 TO S3('https://buckets3.us-east-2.amazonaws.com/test2/', 'KEY', 'SECRET') 

SET allow_experimental_object_type = 1;
RESTORE TABLE vista_app_events_v2 as vista_app_events_backup FROM S3('https://buckets3.us-east-2.amazonaws.com/test2/', 'KEY', 'SECRET') 


```

**Expected behavior**

Restore should work with `allow_experimental_object_type = 1`

**Error message and/or stacktrace**

`SQL Error [44] [07000]: Code: 44. DB::Exception: Cannot create table with column 'payload' which type is 'Object('json')' because experimental Object type is not allowed. Set setting allow_experimental_object_type = 1 in order to allow it: While creating table default.vista_app_events_backup. (ILLEGAL_COLUMN) (version 23.10.4.25 (official build))`

**Additional context**

> Add any other context about the problem here.

I also tried updating clickhouse config.xml in order to avoid setting the flag in query but was not successful.

```
<clickhouse>
    <listen_host>0.0.0.0</listen_host>
    <http_port>8123</http_port>
    <tcp_port>9000</tcp_port>
    <allow_experimental_object_type>1</allow_experimental_object_type>
</clickhouse>
```

**Comment by Algunenano** [comment]
23.10 is out of support
`allow_experimental_object_type` is unsupported and it needs to be declared in the user profiles (users.xml), not in config.

**Comment by faisal00813** [comment]
Thank you @Algunenano !

For others who might land here in search of a solution.

It worked after I added `<allow_experimental_object_type>1</allow_experimental_object_type>`  to users.xml

```
<clickhouse replace="true">
    <profiles>
        <default>
            <max_memory_usage>10000000000</max_memory_usage>
            <use_uncompressed_cache>0</use_uncompressed_cache>
            <load_balancing>in_order</load_balancing>
            <log_queries>1</log_queries>
            <allow_experimental_s3queue>1</allow_experimental_s3queue>
            <allow_experimental_object_type>1</allow_experimental_object_type>
        </default>
    </profiles>
</clickhouse replace>
```
Then `RESTORE TABLE vista_app_events_v2 as vista_app_events_backup FROM S3('https://buckets3.us-east-2.amazonaws.com/test2/', 'KEY', 'SECRET') ` command worked as expected.
