### ISSUE TITLE
Wrong downcast from 'const DB::ColumnVector<UInt64>' to 'DB::ColumnLowCardinality'

### ISSUE THREAD

**Issue by divanik** [ClickHouse/ClickHouse#65666]
> A clear and concise description of what works not as it is supposed to.
Fuzzer check failed with Ubsan.
https://s3.amazonaws.com/clickhouse-test-reports/63665/46408647437fb618543e1a0bf9051ac94f2588df/ast_fuzzer__ubsan_.html

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).
Reproducer of this bug requires Ubsan, and I do not know how to do it in fiddle

**How to reproduce**

* Which ClickHouse server version to use
Ubsan binary from this report: https://s3.amazonaws.com/clickhouse-test-reports/63665/46408647437fb618543e1a0bf9051ac94f2588df/clickhouse_build_check/report.html
* Which interface to use, if it matters
click house-client
* Non-default settings, if any
max_block_size = 11, receive_timeout = 10., receive_data_timeout_ms = 10000, allow_suspicious_low_cardinality_types = true, log_queries = true, table_function_remote_max_addresses = 200, allow_experimental_analyzer = true, max_execution_time = 10., join_algorithm = 'direct', max_memory_usage = 10000000000, log_comment = '/workspace/ch/tests/queries/0_stateless/02241_join_rocksdb_bs.gen.sql', send_logs_level = 'fatal', allow_introspection_functions = true, short_circuit_function_evaluation = 'force_enable'
* `CREATE TABLE` statements for all tables involved
CREATE TABLE rdb_10 (key UInt64, value String) ENGINE = EmbeddedRocksDB PRIMARY KEY (key);
* Sample data for all these tables, use [clickhouse-obfuscator]
   INSERT INTO rdb_10
    SELECT (sipHash64(number) % 10) as key, ('val' || toString(key)) AS value
    FROM numbers_mt(10);
* Queries to run that lead to an unexpected result
SELECT _table = 'd2', materialize(toLowCardinality(2)), 2, 2, 2, 2, materialize(2), 2, 2, 2, 2, 2, 2, 2, materialize(2), 2, 2, toLowCardinality(2), 2, 2, 2, 2, 2, 'd2', 2 FROM (SELECT _table = 'd2', 2, 2, toLowCardinality(toUInt128(2)), 2, 2, toUInt128(2), 2, 2, 2, 2, 2, toUInt256(2), 2, 2, 2, 2, toLowCardinality(toNullable(2)), materialize(2), 2, 2, 2, toLowCardinality(2), number AS k FROM numbers_mt(9)) AS t1 LEFT JOIN rdb_10 AS rdb ON rdb.key = t1.k

**Error message and/or stacktrace**

`
    #0 0x564fe1ee49ec in DB::ColumnVector<unsigned long> const& assert_cast<DB::ColumnVector<unsigned long> const&, DB::IColumn const&>(DB::IColumn const&) build_docker/./src/Common/assert_cast.h:50:12
    #1 0x564fe1ee49ec in DB::ColumnVector<unsigned long>::compareAt(unsigned long, unsigned long, DB::IColumn const&, int) const build_docker/./src/Columns/ColumnVector.h:147:51
    #2 0x564fcae5b227 in DB::GenericComparisonImpl<DB::EqualsOp<int, int>>::vectorConstant(DB::IColumn const&, DB::IColumn const&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul>&) (/workspace/clickhouse+0x1b221227) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #3 0x564fcaca5ec4 in DB::FunctionComparison<DB::EqualsOp, DB::NameEquals>::executeGenericIdenticalTypes(DB::IColumn const*, DB::IColumn const*) const (/workspace/clickhouse+0x1b06bec4) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #4 0x564fcac8643e in DB::FunctionComparison<DB::EqualsOp, DB::NameEquals>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x1b04c43e) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #5 0x564fcaca5766 in DB::FunctionComparison<DB::EqualsOp, DB::NameEquals>::executeWithConstString(std::__1::shared_ptr<DB::IDataType const> const&, DB::IColumn const*, DB::IColumn const*, std::__1::shared_ptr<DB::IDataType const> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x1b06b766) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #6 0x564fcac8556b in DB::FunctionComparison<DB::EqualsOp, DB::NameEquals>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x1b04b56b) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #7 0x564fc94d8878 in DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const (/workspace/clickhouse+0x1989e878) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #8 0x564fde3d0bce in DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x2e796bce) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #9 0x564fde3d286b in DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x2e79886b) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #10 0x564fde3d3f38 in DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName>> const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const (/workspace/clickhouse+0x2e799f38) (BuildId: 50650c423c81d7dabe51463ac65fbdee5742a291)
    #11 0x564fdff5c5e8 in DB::executeAction(DB::ExpressionActions::Action const&, DB::(anonymous namespace)::ExecutionContext&, bool, bool) build_docker/./src/Interpreters/ExpressionActions.cpp:616:60
    #12 0x564fdff59e26 in DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const build_docker/./src/Interpreters/ExpressionActions.cpp:750:13
    #13 0x564fe3c36a7d in DB::ExpressionTransform::transform(DB::Chunk&) build_docker/./src/Processors/Transforms/ExpressionTransform.cpp:23:17
    #14 0x564fd8a1e4c4 in DB::ISimpleTransform::transform(DB::Chunk&, DB::Chunk&) build_docker/./src/Processors/ISimpleTransform.h:32:9
    #15 0x564fe3627e89 in DB::ISimpleTransform::work() build_docker/./src/Processors/ISimpleTransform.cpp:89:9
    #16 0x564fe365861f in DB::executeJob(DB::ExecutingGraph::Node*, DB::ReadProgressCallback*) build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:47:26
    #17 0x564fe365861f in DB::ExecutionThreadContext::executeTask() build_docker/./src/Processors/Executors/ExecutionThreadContext.cpp:96:9
    #18 0x564fe3646382 in DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:272:26
    #19 0x564fe36454f5 in DB::PipelineExecutor::executeSingleThread(unsigned long) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:238:5
    #20 0x564fe36454f5 in DB::PipelineExecutor::executeImpl(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:410:9
    #21 0x564fe3645109 in DB::PipelineExecutor::execute(unsigned long, bool) build_docker/./src/Processors/Executors/PipelineExecutor.cpp:110:9
    #22 0x564fe365dd2b in DB::threadFunction(DB::PullingAsyncPipelineExecutor::Data&, std::__1::shared_ptr<DB::ThreadGroup>, unsigned long, bool) build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:83:24
    #23 0x564fe365dd2b in DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0::operator()() const build_docker/./src/Processors/Executors/PullingAsyncPipelineExecutor.cpp:109:13
    #24 0x564fe365dd2b in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>()()) std::__1::__invoke[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #25 0x564fe365dd2b in decltype(auto) std::__1::__apply_tuple_impl[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/tuple:1789:1
    #26 0x564fe365dd2b in decltype(auto) std::__1::apply[abi:v15000]<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&, std::__1::tuple<>&) build_docker/./contrib/llvm-project/libcxx/include/tuple:1798:1
    #27 0x564fe365dd2b in ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()::operator()() build_docker/./src/Common/ThreadPool.h:251:13
    #28 0x564fe365dd2b in decltype(std::declval<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>()()) std::__1::__invoke[abi:v15000]<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #29 0x564fe365dd2b in void std::__1::__invoke_void_return_wrapper<void, true>::__call<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&>(ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'()&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:479:9
    #30 0x564fe365dd2b in std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>::operator()[abi:v15000]() build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:235:12
    #31 0x564fe365dd2b in void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__1::__function::__policy_storage const*) build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:716:16
    #32 0x564fd40a1777 in std::__1::__function::__policy_func<void ()>::operator()[abi:v15000]() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:848:16
    #33 0x564fd40a1777 in std::__1::function<void ()>::operator()() const build_docker/./contrib/llvm-project/libcxx/include/__functional/function.h:1187:12
    #34 0x564fd40a1777 in ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) build_docker/./src/Common/ThreadPool.cpp:462:13
    #35 0x564fd40a68e9 in void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()::operator()() const build_docker/./src/Common/ThreadPool.cpp:219:73
    #36 0x564fd40a68e9 in decltype(std::declval<void>()()) std::__1::__invoke[abi:v15000]<void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(void&&) build_docker/./contrib/llvm-project/libcxx/include/__functional/invoke.h:394:23
    #37 0x564fd40a68e9 in void std::__1::__thread_execute[abi:v15000]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>(std::__1::tuple<void, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>&, std::__1::__tuple_indices<...>) build_docker/./contrib/llvm-project/libcxx/include/thread:284:5
    #38 0x564fd40a68e9 in void* std::__1::__thread_proxy[abi:v15000]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void ThreadPoolImpl<std::__1::thread>::scheduleImpl<void>(std::__1::function<void ()>, Priority, std::__1::optional<unsigned long>, bool)::'lambda0'()>>(void*) build_docker/./contrib/llvm-project/libcxx/include/thread:295:5
    #39 0x7f62bdef8ac2 in start_thread nptl/pthread_create.c:442:8
    #40 0x7f62bdf8a84f  misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
`

**Comment by Algunenano** [comment]
The fact that that PR introduces changes to `_table` is extremely suspicious. Does the failure reproduce without the PR? I get a query failure

**Comment by Algunenano** [comment]
Closing as the PR should not be merged without the fuzzer being investigated and addressed
