### ISSUE TITLE
If the configuration file is not `.xml`, `.yml` or `.yaml`, autodetect its format.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#65698]
If the file begins with `<` it might be XML, otherwise it might be YAML.

**Comment by YashKumarVerma** [comment]
Could someone share the code section that handles this? I'm looking as well, will post my findings

**Comment by HowePa** [comment]
> Could someone share the code section that handles this? I'm looking as well, will post my findings
> 
> update1: I've found a starting point named `getClientConfigPath`, going through the code involved in configuration parsing
> 
> update2: discovered the section of code that processes configurations
> 
> ```c++
>  if (config_path.has_value())
>         {
>             ConfigProcessor config_processor(*config_path);
>             auto loaded_config = config_processor.loadConfig();
>             config().add(loaded_config.configuration);
>         }
> ```

`ConfigProcessor::processConfig`(src/Common/Config/ConfigProcessor.cpp) is the entrypoint of config parsing.
It supports configuration files with different file extensions. Formatting autodetect can be extended here.

**Comment by sakulali** [comment]
Hi @YashKumarVerma, are you still working on this, if not I'd like to try it.

**Comment by alexey-milovidov** [comment]
@sakulali, thank you! It will be very appreciated!
