### ISSUE TITLE
allow configuring ssh_key in declarative users and roles settings

### ISSUE THREAD

**Issue by ibotty** [ClickHouse/ClickHouse#65700]
I'd like to authenticate with ssh keys and declaratively configure clickhouse users.

[The official documentation](https://clickhouse.com/docs/en/operations/settings/settings-users) says that clickhouse does not allow setting the ssh key there.

Can this be supported?

**Comment by nikitamikhaylov** [comment]
It is supported, please take a look at the test: https://github.com/InfJoker/ClickHouse/blob/5c6e9416eaf2db41daf10536c9c3f05923ce807d/tests/integration/test_ssh_keys_authentication/configs/users.xml

Adding this to documentation is highly appreciated, you can make a PR.
