### ISSUE TITLE
Support redirect (307) in URL engine

### ISSUE THREAD

**Issue by maqroll** [ClickHouse/ClickHouse#6574]
URL engine fails to follow 307 response (redirect).
```
Code: 86. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Received error from remote server /test.parq?op=OPEN&delegation=myticket. HTTP status code: 307 TEMPORARY_REDIRECT, body: .
```

**Nice to have!!**

**Comment by alexey-milovidov** [comment]
It has some security implications.

If the user has access to the `url` function, it can do server-side requests.
For example, put data to memcached in your company network.

To avoid this issue you have to set `readonly` for malicious users - it will disallow usage of table functions.

Further option to prevent it is to add a white-list of allowed hosts. But support for redirects may make this protection ineffective.

For example, you have an application server with strictly limited subset of queries that the user can execute and give access for the user to this application server. And you have support for queries that will read data from some remote urls and the user cannot change that URL. But if the user has control of the server at that URL, it can install redirect and do server-side requests.

Current status: we just keep in mind that the `url` function is dangerous to use and the lack of support for redirects isn't bad. We can add an option to allow redirects.

**Comment by maqroll** [comment]
#6914
