### ISSUE TITLE
Bad metadata file name for Iceberg Table in GCS Bucket

### ISSUE THREAD

**Issue by jackson-burke** [ClickHouse/ClickHouse#65741]
**Describe the unexpected behaviour**

I'm sinking data from RisingWave into an S3-compatible GCS bucket as an Iceberg Table. Then, I'm attempting to read this data into ClickHouse using the Iceberg Table Engine. However, when I attempt to create the table, ClickHouse throws `DB::Exception: Bad metadata file name`.

This issue is similar to issue #56415, though the fix doesn't seem to address the file name formats in my metadata folder.

The very first metadata file is structured as `00000-uuid.uuid4().metadata.json` and I believe it wouldn't be caught by the exception in [IcebergMetadata.cpp](https://github.com/ClickHouse/ClickHouse/blob/c8a2490be7a63ea4073af2638505a395fd463ca2/src/Storages/ObjectStorage/DataLakes/IcebergMetadata.cpp) given the leading digits, but all subsequent metadata files are structured simply as `uuid.uuid4().metadata.json` without the leading digits, causing this Exception to be raised.

**How to reproduce**

1. Sink data from [RisingWave](https://docs.risingwave.com/docs/current/sink-to-iceberg/) into Iceberg Table in GCS Bucket.
```sql
CREATE SINK IF NOT EXISTS snk_public
FROM stg_public  
WITH (
    connector = 'iceberg',
    type = 'append-only',
    force_append_only = 'true',
    s3.region = 'europe-west2',
    warehouse.path = 's3a://bucket/',
    s3.endpoint = 'https://storage.googleapis.com',
    s3.access.key = [],
    s3.secret.key = [],
    catalog.name = 'default',
    catalog.url = 'postgresql://test:test@host:port/test',
    table.name = 'snk_public'
);
```

2. Create a table in ClickHouse from the GCS Bucket.
```sql
CREATE TABLE iceberg_public.src_public 
    ENGINE = Iceberg('https://storage.googleapis.com/bucket/snk_public/, [key], [secret]);
```

**Error message and/or stacktrace**
```
SQL Error [36] [07000]: Code: 36. DB::Exception: Bad metadata file name: 00eb5535-d5d4-436f-aa2b-4b68d5957af2.metadata.json. Expected vN.metadata.json where N is a number. (BAD_ARGUMENTS) (version 24.2.2.71 (official build))
, server ClickHouseNode [uri=https://clickhouse.[removed], options={sslmode=STRICT,use_server_time_zone=false,sslkey=*,sslcert=,use_time_zone=false,sslrootcert=}]@1863777762
```

**Additional context**
- Using ClickHouse version 24.2.2.71

**Comment by Littlehhao** [comment]
How did you solve it? I was also troubled by this problem. I tried 24.8 and 24.12 but they didn't work.
