### ISSUE TITLE
00900_long_parquet fails with timeout

### ISSUE THREAD

**Issue by novikd** [ClickHouse/ClickHouse#65754]
https://s3.amazonaws.com/clickhouse-test-reports/65186/0383d3cf5c7f066f532def3e862ef10a07e50957/stateless_tests__debug__[1_4].html

https://s3.amazonaws.com/clickhouse-test-reports/65190/7a5734749c6d4de64ffed1eaa2e8290103aafb27/stateless_tests__debug__[5_5].html

https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBXRUVLCi0tICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EIHRlc3Rfc3RhdHVzIExJS0UgJ0YlJwogICAgQU5EIGNoZWNrX3N0YXR1cyAhPSAnc3VjY2VzcycKICAgIEFORCBwb3NpdGlvbih0ZXN0X25hbWUsICcwMDkwMF9sb25nX3BhcnF1ZXQnKSA+IDAKT1JERVIgQlkgY2hlY2tfc3RhcnRfdGltZQ==

**Comment by al13n321** [comment]
I think it's the same thing that happened to refreshable MV test: each clickhouse-client process was taking ~7 seconds to start for some reason, and the test calls clickhouse-client >100 times. For that test, I just split it in two. This time maybe I'll try harder to reproduce and investigate why it's so slow with this build build mode + settings + ?.
