### ISSUE TITLE
clickhouse-local got `Multi-statements are not allowed` on version 

### ISSUE THREAD

**Issue by liunaijie** [ClickHouse/ClickHouse#65757]
**Describe the issue**

I follow the `clickhouse-local` guide, but got exception. 

https://clickhouse.com/docs/en/operations/utilities/clickhouse-local

![image](https://github.com/ClickHouse/ClickHouse/assets/28497357/d748e179-a26f-45f6-84d3-3dcc79ac49f7)

<img width="1471" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/28497357/257dc424-4aab-4bea-920f-1c67fa73e8ae">

docker image version: `clickhouse/clickhouse-server:24.5.3`

if the query only has 1 query, it can works.

**Comment by yariks5s** [comment]
Hello @liunaijie! To execute multi-statements, you must write `clickhouse-local -n --query`. Thank you for noticing the issue, I will add this `-n` parameter to the docs shortly🙂
