### ISSUE TITLE
zk/keeper restarts cause zk watch to be unbalanced

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#65750]
### Company or project name

Company：Tencent

### Question

Discussion: 
Restart  zk/keeper will lead to the imbalance of zk watch, which will cause high pressure on the single node, resulting in long writing and merge time. Could you increase SYSTEM to force the reconnection of zk/keeper.

<img width="315" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/20608540/ff2ca654-0c6b-4a73-bfe0-604b719b7ad2">

**Comment by jetgm** [comment]
Which version did you use?

**Comment by Felixoid** [comment]
Version 23.8 should support [fallback_session_lifetime](https://github.com/ClickHouse/ClickHouse/pull/50424/files#diff-931e534c85510eceee4152e8bddad77b0edb1416e50e1c0f350a1df1c4e9e139R5) parameter to rebalance the ZK connections.

This is improved even more in [24.7](https://github.com/ClickHouse/ClickHouse/pull/65570)

Aside from that, you can restart the clickhouse cluster after the keeper/zk restart.
