### ISSUE TITLE
Tests `test_ldap_external_user_directory` occasionally flaky

### ISSUE THREAD

**Issue by zvonand** [ClickHouse/ClickHouse#65762]
Integration tests `test_ldap_external_user_directory` are [flaky](https://play.clickhouse.com/play?user=play#c2VsZWN0IHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMgYXMgc3RhdHVzLCByZXBvcnRfdXJsCmZyb20gY2hlY2tzCndoZXJlIHRvRGF0ZShjaGVja19zdGFydF90aW1lKSA+ICcyMDIzLTA3LTI4JyBhbmQgdGVzdF9uYW1lIGxpa2UgJyV0ZXN0X2xkYXBfZXh0ZXJuYWxfdXNlcl9kaXJlY3RvcnklJyBhbmQgc3RhdHVzIGluICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpCm9yZGVyIGJ5IGNoZWNrX3N0YXJ0X3RpbWUgZGVzYw==)

Example [report](https://s3.amazonaws.com/clickhouse-test-reports/63206/bf93c3807014f4323960afb953565a48e3c26109/integration_tests__aarch64__[4_6].html)

It is interesting that it has not failed for months, and now it only fails in aarch64.

```
=================================== FAILURES ===================================
___________________________ test_authentication_pass ___________________________
[gw3] linux -- Python 3.10.12 /usr/bin/python3

    def test_authentication_pass():
>       assert instance.query(
            "select currentUser()", user="janedoe", password="qwerty"
        ) == TSV([["janedoe"]])

test_ldap_external_user_directory/test.py:52: 

.........................................................................
.........................................................................

E           helpers.client.QueryRuntimeException: Client failed! Return code: 4, stderr: Code: 516. DB::Exception: Received from 172.16.9.3:9000. DB::Exception: janedoe: Authentication failed: password is incorrect, or there is no user with such name.. Stack trace:
E           
E           0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c343e08
E           1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007b9f21c
E           2. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, String const&) const @ 0x000000000f10cce4
E           3. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&) @ 0x000000001024ff20
E           4. DB::TCPHandler::receiveHello() @ 0x00000000112643b4
E           5. DB::TCPHandler::runImpl() @ 0x000000001125ab4c
E           6. DB::TCPHandler::run() @ 0x0000000011273048
E           7. Poco::Net::TCPServerConnection::start() @ 0x00000000135ae698
E           8. Poco::Net::TCPServerDispatcher::run() @ 0x00000000135aeb74
E           9. Poco::PooledThread::run() @ 0x0000000013579574
E           10. Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000013577950
E           11. ? @ 0x000000000007d5c8
E           12. ? @ 0x00000000000e5edc
E           . (AUTHENTICATION_FAILED)

helpers/client.py:239: QueryRuntimeException
------------------------------ Captured log call -------------------------------
2024-06-26 04:06:01 [ 517 ] DEBUG : Executing query select currentUser() on instance (cluster.py:3449, query)
```

**Comment by zvonand** [comment]
@alexey-milovidov let's keep the further discussion (or investigation) of this issue here.  
Me or my colleagues will try to fix this

**Comment by alexey-milovidov** [comment]
@zvonand, it didn't help, and it prevents @AVMusorin to merge his PR: https://github.com/ClickHouse/ClickHouse/pull/66457

**Comment by zvonand** [comment]
Hmm, looks like the reason is the same: CH makes a query to LDAP at `2024.07.22 23:54:21.786576`, but LDAP setup is finished at `23:54:21.85` slapd is started at `23:54:21.89`

Looking into it, probably we still need a better healthcheck

**Comment by alexey-milovidov** [comment]
It failed!!!

**Comment by antaljanosbenjamin** [comment]
https://github.com/ClickHouse/ClickHouse/pull/68355 didn't fix this

**Comment by zvonand** [comment]
Hmm
Well, not really surprising :(

I briefly looked at logs - it is still the same, looks like CH queries LDAP server moments before it is finally ready despite we have several healthchecks for LDAP

**Comment by zvonand** [comment]
@jmaicher maybe, as the author of the test itself, could also take a look?

**Comment by jmaicher** [comment]
I'll take a closer look, but from a quick check I saw that compose health checks against localhost have been added (in addition to the custom health checks in the runner via docker exec), and the last time the tests failed it was actually dns race condition [#56544](https://github.com/ClickHouse/ClickHouse/pull/56544), so it might be related to that again (available via localhost, but not yet via external hostname).

**Comment by jmaicher** [comment]
The problem is in the entrypoint of the OpenLDAP image, which briefly starts and stops the LDAP server as part of the initialization/seeding process. So there is a brief moment when the LDAP server appears to be ready, and then it becomes unavailable shortly thereafter.

I have posted the issue here https://github.com/bitnami/containers/issues/73310 and created https://github.com/ClickHouse/ClickHouse/pull/70755 as a workaround that should fix the problem.
