### ISSUE TITLE
Repm install, yum install, or start clickhouse-server error Segmentation fault

### ISSUE THREAD

**Issue by tangrui96** [ClickHouse/ClickHouse#65780]
Running transaction
  Installing : clickhouse-server-22.8.17.17-1.x86_64                                                                                                                                                                      2/2/var/tmp/rpm-tmp.obryEO: line 59: 31324 Segmentation fault      ${CLICKHOUSE_GENERIC_PROGRAM} install --user "${CLICKHOUSE_USER}" --group "${CLICKHOUSE_GROUP}" --pid-path "${CLICKHOUSE_PIDDIR}" --config-path "${CLICKHOUSE_CONFDIR}" --binary-path "${CLICKHOUSE_BINDIR}" --log-path "${CLICKHOUSE_LOGDIR}" --data-path "${CLICKHOUSE_DATADIR}"
warning: %post(clickhouse-server-0:22.8.17.17-1.x86_64) scriptlet failed, exit status 139

**Comment by Algunenano** [comment]
22.8 is not supported anymore. Please verify with a supported release

**Comment by tangrui96** [comment]
Running transaction
  Installing : clickhouse-server-24.5.3.5-1.x86_64                                                                                                                                                                        2/3/var/tmp/rpm-tmp.B21kcU: line 78: 21897 Segmentation fault      ${CLICKHOUSE_GENERIC_PROGRAM} install --user "${CLICKHOUSE_USER}" --group "${CLICKHOUSE_GROUP}" --pid-path "${CLICKHOUSE_PIDDIR}" --config-path "${CLICKHOUSE_CONFDIR}" --binary-path "${CLICKHOUSE_BINDIR}" --log-path "${CLICKHOUSE_LOGDIR}" --data-path "${CLICKHOUSE_DATADIR}"
warning: %post(clickhouse-server-0:24.5.3.5-1.x86_64) scriptlet failed, exit status 139
Non-fatal POSTIN scriptlet failure in rpm package clickhouse-server-24.5.3.5-1.x86_64
Installing a new version will still cause issues
