### ISSUE TITLE
Feature request: evaluate and prune constant expressions before columns' scanning

### ISSUE THREAD

**Issue by valyala** [ClickHouse/ClickHouse#658]
### The issue

Suppose the following table exists:

```sql
CREATE TABLE events (
    EventDate Date,
    ClientID UInt32
) Engine = MergeTree(EventDate, (EventDate, ClientID), 8192);
```

We use the following query template for counting the number of events for the given client on the given date:

```sql
SELECT count(*) FROM events
WHERE EventDate = <EventDate> AND (ClientID = <ClientID> OR -1 = <ClientID>)
```

The `-1 = <ClientID>` part is used for selecting the total number of events for the given `EventDate`. `<ClientID>` is substituted by `-1` in this case.

Unfortunately, this part disables `(EventDate, ClientID)` key usage, so the `clickhouse` scans all the rows for the given `EventDate` even if `ClientID` isn't equal to `-1`.

### The solution

It would be great if `clickhouse` could evaluate and prune constant expressions before columns' scanning.

For instance, for `EventDate = '2017-04-01'` and `ClientID = 42` the query becomes:
```sql
SELECT count(*) FROM events
WHERE EventDate = '2017-04-01' AND (ClientID = 42 OR -1 = 42)
```
The `-1 = 42` constant part is always evaluated to `false`, so it could be safely pruned. Then the query transforms to:
```sql
SELECT count(*) FROM events
WHERE EventDate = '2017-04-01' AND ClientID = 42
```
This query successfully uses `(EventDate, ClientID)` key.

For `ClientID = -1` the query looks like:
```sql
SELECT count(*) FROM events
WHERE EventDate = '2017-04-01' AND (ClientID = -1 OR -1 = -1)
```
The `-1 = -1` part is always evaluated to `true`, so the `ClientID = -1` part could be safely pruned. Then the query transforms to:
```sql
SELECT count(*) FROM events
WHERE EventDate = '2017-04-01'
```

It would be great if the constant expression evaluation would work for `IN` operators too, so the following construction could be optimized:

`(ClientID IN (<ClientIDs>) OR -1 IN (<ClientIDs>))`

### Possible workaround

- To use distinct query templates depending on whether the `ClientID` is selected or not. Unfortunately, this doesn't work for `grafana` templates when using [clickhouse-grafana](https://github.com/Vertamedia/clickhouse-grafana).

**Comment by ludv1x** [comment]
Thank you for your suggestions.
We are updating our expression analyzer, it will enable to introduce more optimizations (including more powerful constants pruning).

Currently `if(const, expr1, expr2)` function supports it, you could try to rewrite the queries using `if`.

**Comment by hagen1778** [comment]
I did some tests and can confirm that `if` statement helps

**Comment by alexey-milovidov** [comment]
> The -1 = <ClientID> part is used for selecting the total number of events for the given EventDate. <ClientID> is substituted by -1 in this case.

> Unfortunately, this part disables (EventDate, ClientID) key usage, so the clickhouse scans all the rows for the given EventDate even if ClientID isn't equal to -1.

This is just not true. The index works (and already worked) for arbitrary expressions involving comparisons (including IN, LIKE), and logical operations AND, OR, NOT and also some partially monotonic functions.

```
mtlog-perftest03j.yandex.ru :) SELECT count() FROM test.hits WHERE EventDate = '2014-03-18'

SELECT count()
FROM test.hits 
WHERE EventDate = '2014-03-18'

┌─count()─┐
│ 1383658 │
└─────────┘

1 rows in set. Elapsed: 0.014 sec. Processed 6.65 million rows, 13.31 MB (474.18 million rows/s., 948.36 MB/s.) 

mtlog-perftest03j.yandex.ru :) SELECT count() FROM test.hits WHERE EventDate = '2014-03-18' AND CounterID = 154850

SELECT count()
FROM test.hits 
WHERE (EventDate = '2014-03-18') AND (CounterID = 154850)

┌─count()─┐
│     127 │
└─────────┘

1 rows in set. Elapsed: 0.008 sec. Processed 16.38 thousand rows, 98.30 KB (2.01 million rows/s., 12.06 MB/s.) 

mtlog-perftest03j.yandex.ru :) SELECT count() FROM test.hits WHERE EventDate = '2014-03-18' AND (CounterID = 154850 OR CounterID = -1)

SELECT count()
FROM test.hits 
WHERE (EventDate = '2014-03-18') AND ((CounterID = 154850) OR (CounterID = -1))

┌─count()─┐
│     127 │
└─────────┘

1 rows in set. Elapsed: 0.010 sec. Processed 16.38 thousand rows, 98.30 KB (1.68 million rows/s., 10.08 MB/s.) 

mtlog-perftest03j.yandex.ru :) SELECT count() FROM test.hits WHERE EventDate = '2014-03-18' AND (CounterID = 154850 OR CounterID = 111)

SELECT count()
FROM test.hits 
WHERE (EventDate = '2014-03-18') AND ((CounterID = 154850) OR (CounterID = 111))

┌─count()─┐
│     127 │
└─────────┘

1 rows in set. Elapsed: 0.010 sec. Processed 32.77 thousand rows, 196.61 KB (3.44 million rows/s., 20.63 MB/s.)
```

You see, that `6.65 million rows` have scanned for condition `EventDate = '2014-03-18'`
but just `32.77 thousand rows` have scanned for condition `EventDate = '2014-03-18' AND (CounterID = 154850 OR CounterID = 111)`.

**Comment by alexey-milovidov** [comment]
But the task remains.

**Comment by nvartolomei** [comment]
`if` optimization doesn't work anymore?

```sql
ClickHouse client version 19.1.0.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.16.1 revision 54412.

c156b88712ed :) DROP TABLE IF EXISTS constCondOptimization;

DROP TABLE IF EXISTS constCondOptimization

Ok.

0 rows in set. Elapsed: 0.015 sec.

c156b88712ed :) CREATE TABLE constCondOptimization (d Date DEFAULT today(), n Int64) ENGINE = MergeTree(d, n, 1);

CREATE TABLE constCondOptimization
(
    d Date DEFAULT today(),
    n Int64
)
ENGINE = MergeTree(d, n, 1)

Ok.

0 rows in set. Elapsed: 0.009 sec.

c156b88712ed :) INSERT INTO constCondOptimization(n) SELECT number from system.numbers LIMIT 1000000;

INSERT INTO constCondOptimization (n) SELECT number
FROM system.numbers
LIMIT 1000000

→ Progress: 1.05 million rows, 8.39 MB (10.17 million rows/s., 81.36 MB/s.) SELECT n from constCondOptimization WHERE if(0, 1, n = 1000);
SELECT n from constCondOptimization WHERE n = 1000;
Ok.

0 rows in set. Elapsed: 0.727 sec. Processed 1.05 million rows, 8.39 MB (1.44 million rows/s., 11.53 MB/s.)

c156b88712ed :) SELECT n from constCondOptimization WHERE if(0, 1, n = 1000);

SELECT n
FROM constCondOptimization
WHERE if(0, 1, n = 1000)

┌────n─┐
│ 1000 │
└──────┘

1 rows in set. Elapsed: 0.027 sec. Processed 1.00 million rows, 8.00 MB (36.97 million rows/s., 295.75 MB/s.)

c156b88712ed :) SELECT n from constCondOptimization WHERE n = 1000;

SELECT n
FROM constCondOptimization
WHERE n = 1000

┌────n─┐
│ 1000 │
└──────┘

1 rows in set. Elapsed: 0.005 sec.
```

**Comment by alexey-milovidov** [comment]
Artem @4ertus2 is currently doing a similar task: transitive constant propagation from WHERE via JOIN ON for pushdown.

**Comment by alexey-milovidov** [comment]
> It would be great if the constant expression evaluation would work for IN operators too

I checked, and it works:

```
milovidov-desktop :) SELECT count() FROM hits WHERE CounterID = 117796 OR -1 IN (1, 2, 3)

SELECT count()
FROM hits
WHERE (CounterID = 117796) OR (-1 IN (1, 2, 3))

Query id: ab170d56-c773-48f9-b3b7-5dbf505b0a1d

┌─count()─┐
│    2592 │
└─────────┘

1 row in set. Elapsed: 0.004 sec. Processed 8.19 thousand rows, 32.77 KB (1.98 million rows/s., 7.93 MB/s.)

milovidov-desktop :) SELECT count() FROM hits WHERE CounterID IN (117796, 71172) OR -1 IN (1, 2, 3)

SELECT count()
FROM hits
WHERE (CounterID IN (117796, 71172)) OR (-1 IN (1, 2, 3))

Query id: baf6848d-9f78-40ec-8ecb-d4a48809c93f

┌─count()─┐
│    5167 │
└─────────┘

1 row in set. Elapsed: 0.004 sec. Processed 24.58 thousand rows, 98.30 KB (6.00 million rows/s., 24.00 MB/s.)
```
