### ISSUE TITLE
TTL TO VOlUME 'XXX' Unexpected behaviour

### ISSUE THREAD

**Issue by WellJay** [ClickHouse/ClickHouse#65806]
**Describe the unexpected behaviour**
My Table SET `TTL toDateTime(dt) + toIntervalDay(15), toDateTime(dt) + toIntervalDay(3) TO VOLUME 'cold'` 
the config.xml is （every SSD 700G， JuiceFS_DISK is s3,like MinIO）
      
       <storage_configuration>
        <disks>
          <ssd_disk_1>
              <path>/data1/clickhouse/</path>
              <keep_free_space_bytes>107374182400</keep_free_space_bytes> 
          </ssd_disk_1>
          <ssd_disk_2>
              <path>/data2/clickhouse/</path>
              <keep_free_space_bytes>107374182400</keep_free_space_bytes> 
          </ssd_disk_2>
          <ssd_disk_3>
              <path>/data3/clickhouse/</path>
              <keep_free_space_bytes>107374182400</keep_free_space_bytes> 
          </ssd_disk_3>
          <ssd_disk_4>
              <path>/data4/clickhouse/</path>
              <keep_free_space_bytes>107374182400</keep_free_space_bytes> 
          </ssd_disk_4>
          <ssd_disk_5>
              <path>/data5/clickhouse/</path>
              <keep_free_space_bytes>107374182400</keep_free_space_bytes> 
          </ssd_disk_5>
          <jfs_disk_1>
              <path>/jfs/clickhouse/</path>
          </jfs_disk_1>
        </disks>
        <policies>
          <moving_from_ssd_to_jfs>
            <volumes>
                <hot>
                    <disk>ssd_disk_1</disk>
                    <disk>ssd_disk_2</disk>
                    <disk>ssd_disk_3</disk>
                    <disk>ssd_disk_4</disk>
                    <disk>ssd_disk_5</disk>
                </hot>
                <cold>
                    <disk>jfs_disk_1</disk>
                </cold>
            </volumes>
            <move_factor>0.2</move_factor>
          </moving_from_ssd_to_jfs>
        </policies>
    </storage_configuration>

**How to reproduce**
* version is 24.2.2.71
* 
### table ddl
CREATE TABLE log.unified_log
(
    `dt` DateTime64(3) CODEC(DoubleDelta, LZ4),
     xxxxxx,
    INDEX idx_string_values `string.values` TYPE tokenbf_v1(4096, 2, 0) GRANULARITY 4,
    INDEX idx_rawLog rawLog TYPE tokenbf_v1(20480, 2, 0) GRANULARITY 1,
    PROJECTION p_projects_usually
    (
        SELECT 
            project,
            count(),
            min(dt),
            max(dt),
            groupUniqArrayArray(string.keys),
            groupUniqArrayArray(number.keys),
            groupUniqArrayArray(unIndex.keys)
        GROUP BY project
    )
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(dt)
ORDER BY (project, dt)
TTL toDateTime(dt) + toIntervalDay(15), toDateTime(dt) + toIntervalDay(3) TO VOLUME 'cold'
SETTINGS storage_policy = 'moving_from_ssd_to_jfs', index_granularity = 8192, max_bytes_to_merge_at_max_space_in_pool = 21474836480

**Expected behavior**
today is 2024.06.28, but the 27 26 **some partitions**（not all） have been moved to cold volumn

![image](https://github.com/ClickHouse/ClickHouse/assets/7018973/cd12b505-c812-4c07-a0ce-3daaa525797b)

**Comment by WellJay** [comment]
![image](https://github.com/ClickHouse/ClickHouse/assets/7018973/0a741238-488c-4f11-93cb-97eb2ade4329)

**Comment by den-crane** [comment]
you need to monitor unreserved space on ssd_disk_*

```
select name, path, unreserved_space from system.disks
```

The most probably a merge or mutation reserved all free disk space on one of the ssd disk and data was moved to the cold prematurely. 
I would use `mdraid` raid0 and combined all ssd disks to a single device then combined free space will allow to avoid it.

**Comment by WellJay** [comment]
> you need to monitor unreserved space on ssd_disk_*
> 
> ```
> select name, path, unreserved_space from system.disks
> ```
> 
> The most probably a merge or mutation reserved all free disk space on one of the ssd disk and data was moved to the cold prematurely. I would use `mdraid` raid0 to combine all ssd disks to a single device then combined free space will allow to avoid it.

<img width="745" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/7018973/b972a83a-42b5-40c6-89f4-909e17ed3099">

**Comment by WellJay** [comment]
> you need to monitor unreserved space on ssd_disk_*
> 
> ```
> select name, path, unreserved_space from system.disks
> ```
> 
> The most probably a merge or mutation reserved all free disk space on one of the ssd disk and data was moved to the cold prematurely. I would use `mdraid` raid0 to combine all ssd disks to a single device then combined free space will allow to avoid it.

<img width="853" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/7018973/a8476256-5936-4025-b1e6-35d918fab87f">

**Comment by den-crane** [comment]
Merges reserve double space, so it's around +300GB

**Comment by WellJay** [comment]
thks， the reason is ck and juicefs share disk space.

Total 600G, configure move_factor 0.2,120G will trigger the move, but the actual data did not reach 600-120=480G, only about 400G, probably because ttl move includes the disk part of JuiceFS (just set 80G cache)
