### ISSUE TITLE
TTL wrap up around minimal date 

### ISSUE THREAD

**Issue by Khatskevich** [ClickHouse/ClickHouse#65815]
**What's wrong**
TTL `timestamp - toIntervalYear(30)` supposed to delete all records smaller then `2054`, but for some reason records smaller then `2000` preserve.

It looks like there is a wrap up around the minimal date, when the calculated value `timestamp - toIntervalYear(30)` is smaller then the minimal date `1970` and those values are considered to be the largest date.

**How to reproduce**
This reproduces on the latest clickhouse in the Fiddle, **but I could not reproduce in in a docker container for some reason**
https://fiddle.clickhouse.com/1c32153b-4d3f-434c-ac6f-04b10ed3c564

```
CREATE TABLE test2 (timestamp Date) ENGINE = ReplicatedMergeTree ORDER BY timestamp TTL timestamp - toIntervalYear(30)
insert into test2 values ('1970-01-01'), ('1980-01-01'), ('1990-01-01'), ('2000-01-01'), ('2010-01-01'), ('2020-01-01'), ('2030-01-01'), ('2040-01-01'), ('2050-01-01'), ('2060-01-01')
OPTIMIZE TABLE test2 FINAL
select * from test2
------
output:
1970-01-01
1980-01-01
1990-01-01
2000-01-01
2060-01-01

```

**Expected behavior**
Expected output
```
2060-01-01`
``

**Comment by den-crane** [comment]
0 - 1970 is used to indicate that there is no TTL information.

you can use greatest  - ` TTL greatest(toDate(1), timestamp - toIntervalYear(30))`

https://fiddle.clickhouse.com/c816a135-3ddc-417e-9299-705b445a71c1

**Comment by den-crane** [comment]
technically this is expected behavior. And it’s unlikely that anyone will find it in real life.
