### ISSUE TITLE
Fuzzer: Convert plans into remote plans

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#65836]
We can greatly increase our coverage of distributed/remote plans by transforming `table` into `remote('127.0.0.{1,1}', 'table')`:

```
SELECT *
FROM system.one
```

```
SELECT *
FROM remote('127.0.0.{1,1}', 'system.one')
```

**Comment by CurtizJ** [comment]
Duplicate #64663.

**Comment by Algunenano** [comment]
I only wanted to add it to the fuzzer to find crashes and logical errors (we've had and currently have multiple of them).

It seems https://github.com/ClickHouse/ClickHouse/issues/64663 is more complete, which also means it will require a lot more effort.
