### ISSUE TITLE
ClickHouse Cannot execute replicated DDL query, maximum retries exceeded

### ISSUE THREAD

**Issue by shitianmori** [ClickHouse/ClickHouse#65856]
### Company or project name

optimize table Error:ClickHouse Cannot execute replicated DDL query, maximum retries exceeded    

### Question

![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/ef8792de-eaa0-43e3-9fc3-8cb4be18fbaa)
![2ea8f2b3f7adeac62b97ce3a8736f59](https://github.com/ClickHouse/ClickHouse/assets/49182894/9e134882-8f37-46b5-9d0b-c0e7cdc5f7b3)
clusters config
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/144cdb56-30d7-4413-b10c-3b6dbc8db70b)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/d97fae47-ce37-4cae-87e5-3b89d4b4419d)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/a26a74a5-7e54-4a82-925f-5a48aa9b53cc)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/0e5c0d81-b311-4c1f-a817-c567fbc927c6)
macros config
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/1244f7ae-9d8d-44a6-a143-668989819263)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/8568dccd-7524-43bd-a88b-4c33188aeeb6)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/8a3f8d33-c877-4011-96cd-cf4de3ffb40e)
clickhouse version 23.9.4.11
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/2c7b620b-a363-44dc-b6ab-c59affe60fb0)

**Comment by shitianmori** [comment]
clickhouse-server.err.log
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/cc2d6af2-3b2a-49f5-9564-fbfbe8f5e533)
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/58038263-4f2a-4645-81bd-aca026fd596f)
clickhoiuse-server.log
![image](https://github.com/ClickHouse/ClickHouse/assets/49182894/6e2eb3f3-ba6e-4e80-9591-49e5449ba50e)

**Comment by hanfei1991** [comment]
Hi, I would suggest execute `optimize table` without `on cluster`. Then the merge will propagate properly
