### ISSUE TITLE
Clickhouse OOM & big replication_queue size, it's something wrong or bug?

### ISSUE THREAD

**Issue by vzzy** [ClickHouse/ClickHouse#65854]
hi,  
Clickhouse OOM & big replication_queue size, it's something wrong or bug?
version:  22.3.8.39
PC:  36C 100G
We have two issues:
1. Since deployed,about 6 months, the memory is constantly growing, and now 60% memory is used.
    Reboot the clickhouse is no use. 
    Is it something are resident in memory? 
    How do I analyze what files are resident in memory？
    We use ReplicatedMergeTree + ReplicatedAggregatingMergeTree.
![ckmem](https://github.com/ClickHouse/ClickHouse/assets/8855685/9798ea72-65e9-4644-ba71-ebd0fde4eb5a)

2. Big replication_queue size，about last three weeks.  
    We have change background_fetches_pool_size to 128, but the effect is not significant. 
    What can i do to solve it?
    > select count(1) from system.replication_queue;
    2783797
   postpone_reason: Not executing fetch of part 20240628_572_572_0 because 128 fetches already executing, max 128.
![image](https://github.com/ClickHouse/ClickHouse/assets/8855685/ee6f648c-5087-4e9f-9ee9-2bc52d1cab92)
![image](https://github.com/ClickHouse/ClickHouse/assets/8855685/eeb1507e-df69-4800-88b1-d242a8d4c6d4)

Thanks!

**Comment by Algunenano** [comment]
22.8 is out of support.

> We have change background_fetches_pool_size to 128, but the effect is not significant.

Maybe you should look into why you are reaching 128 fetches concurrently. Most likely you are inserting too many parts or your network connection is too slow. Try identifying why you have so many parts and reduce them

**Comment by vzzy** [comment]
You are right，Thanks.
Too many insert SQL was executed, then ZK nodes rising,performance of replication reduced.
and then the replication_queue become big and big, and memory become big and big.
To control the number of insert SQL,solve the problem.
