### ISSUE TITLE
Repm install, yum install, or start clickhouse-server error Segmentation fault

### ISSUE THREAD

**Issue by tangrui96** [ClickHouse/ClickHouse#65864]
yum install clickhouse-server-24.5.3.5-1.x86_64
Running transaction
Installing : clickhouse-server-24.5.3.5-1.x86_64 2/3/var/tmp/rpm-tmp.B21kcU: line 78: 21897 Segmentation fault ${CLICKHOUSE_GENERIC_PROGRAM} install --user "${CLICKHOUSE_USER}" --group "${CLICKHOUSE_GROUP}" --pid-path "${CLICKHOUSE_PIDDIR}" --config-path "${CLICKHOUSE_CONFDIR}" --binary-path "${CLICKHOUSE_BINDIR}" --log-path "${CLICKHOUSE_LOGDIR}" --data-path "${CLICKHOUSE_DATADIR}"
warning: %post(clickhouse-server-0:24.5.3.5-1.x86_64) scriptlet failed, exit status 139
Non-fatal POSTIN scriptlet failure in rpm package clickhouse-server-24.5.3.5-1.x86_64
Installing a new version will still cause issues

**Comment by alexey-milovidov** [comment]
You can install ClickHouse as follows:

```
curl https://clickhouse.com/ | sh
```
