### ISSUE TITLE
Add a changelog entry for users to skip upgrading to version 22.12

### ISSUE THREAD

**Issue by Thunderbottom** [ClickHouse/ClickHouse#65862]
**Describe the issue**
Last night, we upgraded our long standing clickhouse instance from `22.3.17.13` to `22.12.4.76`. We planned on upgrading to the latest version on `24.x`, but did minor version upgrades to ensure nothing breaks during the process.

After the upgrade happened, we realised some things went wrong during which we were unable to access the instance, and clickhouse started malfunctioning. After a good while of debugging, turns out, there was an issue in the version `22.12` systemd configuration which caused `/run/systemd` in particular to be `chown`'d by `clickhouse:clickhouse`. (ref: https://github.com/ClickHouse/ClickHouse/issues/48285, fixed in: https://github.com/ClickHouse/ClickHouse/pull/47105) But since `22.12` was over according to the developers, this critical change wasn't backported to the `22.12` version, and the package is still broken.

I believe we should add a changelog entry to the `22.12` version, asking people to skip upgrading to that version so that their systems do not break and this issue can be avoided. This will prevent a lot of people from spending time debugging their broken system because of this clickhouse upgrade.

**How to reproduce**
* Install any Clickhouse release prior to `22.12`.
* Upgrade to the latest `22.12` version, `22.12.4.76`.
* Restart the clickhouse-server systemd service.
* See that `/run/systemd` is owned by `clickhouse:clickhouse`, and a few other folders from the comment in the clickhouse-server systemd file are created.

**Expected behavior**
Clickhouse should not be owning `/run/systemd`, which is due to a faulty comment in the `22.12` version's systemd entry.

A changelog entry should be added asking people to avoid upgrading to these affected versions.

**Error message and/or stacktrace**
Ref: https://github.com/ClickHouse/ClickHouse/issues/48285

**Comment by alexey-milovidov** [comment]
Send a pull request.
