### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#6587]
Is it possible to add format YYYYMMDD for dates and times?
select * from table where date >'20190726'

It speeds up sql writing.

Is it possible to support for datetime queries like?

select * from table where date >'2019-07-26'

It also speeds up sql writing

**Comment by alexey-milovidov** [comment]
> select * from table where date >'2019-07-26'

It's already supported.

**Comment by thyn** [comment]
I've updated YYYYMMDD is ok, but "YYYY-MM-DD" not. It's strange

select top 100 createdon from table where createdon>'2019-07-24'

Code: 41, e.displayText() = DB::Exception: Cannot parse datetime 2019-07-24 (version 19.13.2.19)

**Comment by thyn** [comment]
also 

select top 100 createdon from tables where createdon>'20190724'

results contains 2019-07-15 00:00:00
