### ISSUE TITLE
epm install, yum install, or start clickhouse-server error Segmentation fault

### ISSUE THREAD

**Issue by tangrui96** [ClickHouse/ClickHouse#65878]
[root@node1 ~]# curl https://clickhouse.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2822    0  2822    0     0   1660      0 --:--:--  0:00:01 --:--:--  1660

Will download https://builds.clickhouse.com/master/amd64/clickhouse into clickhouse

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  110M  100  110M    0     0  6919k      0  0:00:16  0:00:16 --:--:-- 7335k

Successfully downloaded the ClickHouse binary, you can run it as:
    ./clickhouse

You can also install it:
    sudo ./clickhouse install
[root@node1 ~]# sudo ./clickhouse install
Decompressing the binary....
Segmentation fault

**Comment by Algunenano** [comment]
The fact that everything crashes in your system:
* https://github.com/ClickHouse/ClickHouse/issues/65780
* https://github.com/ClickHouse/ClickHouse/issues/65864
* https://github.com/ClickHouse/ClickHouse/issues/65878

Makes me suspect there is something special in your system that's unexpected to CH. What's special about it?

**Comment by tangrui96** [comment]
Normal use, but suddenly unable to use, abnormal startup and reinstallation. Did the system's environment variables and other information be used

**Comment by tangrui96** [comment]
How can I erase all traces of clickhouse and reinstall it
