### ISSUE TITLE
A setting `query_cache_tag`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#65872]
An arbitrary string to separate entries in the query cache.
Queries with different values of this setting are considered different.

**Use case**

Save the result of a query into a unique cache entry for subsequent access, but don't mix it with identical queries.

**Comment by UnamedRus** [comment]
In chproxy, it's named cache_namespace, which is seems also commonly used name for that feature. 

> Optional cache namespace may be passed in query string as cache_namespace=aaaa.

**Comment by alexey-milovidov** [comment]
It cannot be named `cache_namespace`, at least it should be `query_cache_namespace`.

**Comment by sakulali** [comment]
Hi @alexey-milovidov, I'd like to try this issue, thanks!

**Comment by alexey-milovidov** [comment]
@sakulali thank you, this will be very appreciated!
