### ISSUE TITLE
Nested Parameterized view

### ISSUE THREAD

**Issue by kazhou2024** [ClickHouse/ClickHouse#65889]
### Question

How to create a Nested Parameterized view, which reference another Parameterized view inside? Use below sample, I got below error. 

Parameterized view1:
 CREATE OR REPLACE VIEW v AS SELECT 1::UInt32 x WHERE x IN ({xx:Array(UInt32)});

Parameterized view2:

CREATE OR REPLACE VIEW v2 AS SELECT * from v(xx=[ {xxx : Array(UInt32)} ]);
or
CREATE OR REPLACE VIEW v2 AS SELECT * from v(xx= {xxx : Array(UInt32)} );

Error:
Code: 456. DB::Exception: Substitution `xx` is not set. (UNKNOWN_QUERY_PARAMETER) (version 23.3.19.32 (official build))

**Comment by kazhou2024** [comment]
Please consider we have many Parameterized views need to reference Parameterized view "v", we can't expand the defination of "v" to each Parameterized views

**Comment by CurtizJ** [comment]
It works since version 24.2: https://fiddle.clickhouse.com/e12ca85e-d41c-400a-a0a5-52634f4ce390. Please upgrade.

**Comment by kazhou2024** [comment]
> It works since version 24.2: https://fiddle.clickhouse.com/e12ca85e-d41c-400a-a0a5-52634f4ce390. Please upgrade.

Great, thanks
