### ISSUE TITLE
Join of 2 Distributed tables

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#6589]
We have 2 shards and one distributed table table1. '
Data is distributed properly between shards for table1. 
We have another table table2 which need to JOIN with the table1.
We need all records in the table2 duplicated across both shards. 

Is there a way to achieve this?

**Comment by 4ertus2** [comment]
You need distributed subqueries: https://clickhouse.yandex/docs/en/query_language/select/#select-distributed-subqueries

In example you may try:
````
SELECT * FROM table1 GLOBAL ANY LEFT JOIN table2
``
or place table2 on each shard and run
```
SELECT * FROM table1 ANY LEFT JOIN table2 SETTINGS distributed_product_mode=LOCAL
```

**Comment by filimonov** [comment]
Sharding schema is not need to be global. You can use different sharding (or replication) schema from each table. 

So for example you can create `table2_local` as replicated across all shards (just don't add `{shard}` macro in zookeeper path for ReplicatedMergeTree).

Additionally you can also configure one more cluster where all clickhouse nodes will be listed as replicas, and create create distributed table using that extra 'cluster'.

**Comment by den-crane** [comment]
@4ertus2 BTW distributed_product_mode affect only subqueries.

<del>SELECT * FROM table1 ANY LEFT JOIN table2 SETTINGS distributed_product_mode=LOCAL<del>

SELECT * FROM table1 ANY LEFT JOIN (select * from table2) SETTINGS distributed_product_mode=LOCAL

local — Replaces the database and table **in the subquery** with local ones for the destination server (shard), leaving the normal IN/JOIN.

And this is kinda unexpected behaviour.

**Comment by 4ertus2** [comment]
> BTW distributed_product_mode affects only on subqueries.

OK. Any case, there's a hask that rewrites table into subselect for push down into join. It's possible to remove this restriction if really needed.

**Comment by blinkov** [comment]
@Crazylearner30, do you have any further questions?

**Comment by blinkov** [comment]
Feel free to re-open the issue if it is still relevant.
