### ISSUE TITLE
S3 table function structured approach doesn't work as described

### ISSUE THREAD

**Issue by absorbb** [ClickHouse/ClickHouse#65922]
**Company or project name**

Jitsu Labs inc.

**Describe what's wrong**

Structured approach described in https://clickhouse.com/docs/en/integrations/data-formats/json#structured-approach
doesn't work:

https://fiddle.clickhouse.com/cfbeeb10-a9e4-4473-a2ff-9b93916d299b

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

ClickHouse Server: 24.6.1.4423
ClickHouse Cloud: 24.2

Try to pass structure to s3 table function extracting field values from nested object as it described in docs:
https://clickhouse.com/docs/en/integrations/data-formats/json#structured-approach

having ndjson:
```json
{"id": 1, "nested": {"id": 1, "name": "nested", "level2": {"prop1": "value1"}}}
{"id": 2, "nested": {"id": 2, "name": "nested", "level2": {"prop1": "value2"}}}
```

```sql
SELECT * FROM s3('https://jitsu-example.s3.amazonaws.com/nested.ndjson', 'NOSIGN','JSONEachRow',
        'id Int, `nested.id` Int, `nested.name` String, `nested.level2.prop1` String');
```

Getting results:

| id | nested.id | nested.name | nested.level2.prop1 |
|-:|-:|:-|:-|
| 1 | 0 |  |  |
| 2 | 0 |  |  |

**Expected behavior**

| id | nested.id | nested.name | nested.level2.prop1 |
|-:|-:|:-|:-|
| 1 | 1 | nested | value1 |
| 2 | 2 | nested | value2 |

**Additional context**

It is getting weirder because it is possible to kind of workaround that by running the following query:

```sql
SELECT id, nested.id, nested.name, nested.level2.prop1
FROM s3('https://jitsu-example.s3.amazonaws.com/nested.ndjson','NOSIGN', 'JSONEachRow');
```

it gives **expected** result.

But nonetheless it is not possible to use this query as a source of successful Insert from Select. E.g.:

Lets create table:

```sql
create table test_nested
(
    id Int,
    `nested.id` Int,
    `nested.name` String,
    `nested.level2.prop1` String
) ENGINE = MergeTree() ORDER BY id;
```

and then run insert:

```sql
insert into test_nested
SELECT id, `nested.id`, `nested.name`, `nested.level2.prop1`
FROM s3('https://jitsu-example.s3.amazonaws.com/nested.ndjson','NOSIGN', 'JSONEachRow');
```

then select:

```sql
select * from test_nested;
```

it still gives:

| id | nested.id | nested.name | nested.level2.prop1 |
|-:|-:|:-|:-|
| 1 | 0 |  |  |
| 2 | 0 |  |  |

**Comment by max-vostrikov** [comment]
There is a special setting for nested json [input_format_import_nested_json](https://clickhouse.com/docs/en/operations/settings/formats#input_format_import_nested_json)
It seems like it works correct in your case:
https://fiddle.clickhouse.com/c77ee18d-625c-469b-9412-fc91f015bc3e
```
SELECT *
FROM s3('https://jitsu-example.s3.amazonaws.com/nested.ndjson', 'NOSIGN','JSONEachRow',
        'id Int, `nested.id` Int, `nested.name` String, `nested.level2.prop1` String') SETTINGS input_format_import_nested_json = 1;
```
returns expected result
