### ISSUE TITLE
Add setting to stop INSERTs when disk space is close to 100%

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#65951]
**Use Case**

When ClickHouse fills the disk to 100%, it creates several negative side effects: inability to perform certain SELECT queries (which require temporary data), potential file corruption, inability to write logs, and other cascading issues that complicate recovery. It's preferable to stop writes slightly earlier to avoid these problems.

The same logic as `parts_to_throw_insert` can be applied here. Eventually, writes will fail as the disk becomes full; it's better if they fail slightly earlier to prevent cascading problems.

**Describe the solution you'd like**

Introduce user-level settings: `min_free_diskspace_bytes_to_throw_insert ` (default 10GB) and `min_free_diskspace_ratio_to_throw_insert ` (default 0.02, i.e., 2%). When these settings are non-zero, during an INSERT operation, ClickHouse will ensure that the storage policy of the target table has at least `min_free_diskspace_bytes_to_throw_insert` bytes or `min_free_diskspace_ratio_to_throw_insert` free space available. If not, it will throw an exception.

**Describe alternatives you've considered**

Relying on user discipline, monitoring, and alerting has proven to be ineffective.

**Additional context**

Throttling / delaying / slowing down the inserts in that conditions is more controversial, so I don't think it's really needed.

May be we can also make the logic a bit more complex - by checking if the default drive have that amount of free disks space AND there is at least one disk in storage policy of the table with that amount of the free disk space.

**Comment by alexey-milovidov** [comment]
> potential file corruption

This is probably just a speculation and should not be possible.

**Comment by filimonov** [comment]
I saw that few times on practice (several months ago last time, so have no extra info currently, if will see again - will try to collect more details if it will be possible).

I'm not 100% sure about the exact mechanics there, but i suspect it caused by lack of fsync 

AFAIK normally the `write` should take into the account both real free space & size of dirty pages, but i'm not sure if's true for all the cases / filesystems / kernels.

Reason for reflection: ENOSPC is a valid error code for fsync... See [man](https://man7.org/linux/man-pages/man2/fsync.2.html), some relevant [discussions](https://stackoverflow.com/questions/42434872/writing-programs-to-cope-with-i-o-errors-causing-lost-writes-on-linux).

**Comment by seandhaynes** [comment]
@filimonov I've actually been looking at this too - thanks for raising it.

Are you already aware of `keep_free_space`?
https://clickhouse.com/docs/en/operations/system-tables/disks

This is a value in bytes on the disk storage policy that somewhat achieves this and results in INSERTs being rejected if you configure it to keep say 2% of disk space free.

Though one behaviour that I'm less sure about and don't really like is that it affects internal operations like merges, as this setting is evaluated as part of getting free space when scheduling merges.

I'm curious what your thoughts are on this setting.

**Comment by filimonov** [comment]
Indeed, may be we can achieve similar effect with that keep_free_space_bytes...

That requires the user / dba to remember to configure that on every disk (not so handy), and may give a bit confusing error messages, and will impact all attemps to reserve space on that disk (not only inserts).

**Comment by filimonov** [comment]
Also of it will be a user level setting users eill be able to temporary relax it,. Or even different limits can be used for different users,

**Comment by seandhaynes** [comment]
@filimonov @alexey-milovidov any objections to me taking this and making a PR? 

We have an intern interested in working with ClickHouse, and would like to work on this with them.
