### ISSUE TITLE
lagInFrame and leadInFrame functions missing offset argument.

### ISSUE THREAD

**Issue by jwoodhead** [ClickHouse/ClickHouse#65952]
**Company or project name**
n/a

**Describe the issue**
The `lagInFrame` and `leadInFrame` functions as listed in https://clickhouse.com/docs/en/sql-reference/window-functions#functions do not indicate that that they support an `offset` argument. This differs from what is shown for the `nth_value` function.

**Additional context**
n/a

**Comment by den-crane** [comment]
@jwoodhead 
You can contribute to the documentation by yourself, just press `Edit this page` in the end of the page and make a PR [Edit this page](https://github.com/ClickHouse/ClickHouse/tree/master/docs/en/sql-reference/window-functions/index.md)
