### ISSUE TITLE
Column alias confusion

### ISSUE THREAD

**Issue by chspanda** [ClickHouse/ClickHouse#65964]
I had an instance of ClickHouse 24.1.1.2408 and recently founded another instance 24.3.2.23 for transferring, found difference behavior processing column alias of aggregation, I was wondering if i made any mistake or is there any feature changed?

Here is the sample table:
create table t (code varchar(10), val int) engine=Memory;
insert into t values ('a', 10);
insert into t values ('a', 20);
insert into t values ('a', 30);
insert into t values ('b', 11);

In version 24.1.1.2048
SELECT code, sum(val) as val, val / count(1) as avg from t group by code;
code	val	avg
b	11	11
a	60	20

Another style may causes aggregation re-caculating, so it gave me an error, this seems meanful.
SELECT code, sum(val) as val, sum(val) / count(1) as avg from t group by code;
> Code: 184. DB::Exception: Aggregate function sum(val) is found inside another aggregate function in query: While processing sum(val) AS val. (ILLEGAL_AGGREGATION) (version 24.1.1.2048 (official build))

In version 24.3.2.23
SELECT code, sum(val) as val, val / count(1) as avg from t group by code;
> 215 - Code: 215. DB::Exception: Column dt.t.val is not under aggregate function and not in GROUP BY keys. In query SELECT code, sum(val) AS val, val / count(1) AS avg FROM t GROUP BY code. (NOT_AN_AGGREGATE) (version 24.3.2.23 (official build))

SELECT code, sum(val) as val, sum(val) / count(1) as avg from t group by code;
code	val	avg
b	11	11
a	60	20

**Comment by chspanda** [comment]
seems 24.6.1 has fixed the problem, close

**Comment by chspanda** [comment]
Tested in 24.6.1.4423 got same result in 24.3.2.23

**Comment by Algunenano** [comment]
I can't reproduce it: https://fiddle.clickhouse.com/8a948531-048b-4ead-99e5-f07e3702b4fa

It seems likely that you are using some different settings from default (`prefer_column_name_to_alias`)? If so, then it makes sense that query fails as it does.

**Comment by chspanda** [comment]
> I can't reproduce it: https://fiddle.clickhouse.com/8a948531-048b-4ead-99e5-f07e3702b4fa
> 
> It seems likely that you are using some different settings from default (`prefer_column_name_to_alias`)? If so, then it makes sense that query fails as it does.

So it is! thanks!
