### ISSUE TITLE
Incorrect optimization when left join postgresql engine with null condition

### ISSUE THREAD

**Issue by com-exem-route7** [ClickHouse/ClickHouse#65969]
**Describe what's wrong**

If you do left join a MergeTree Engine table and a PostgreSQL Engine table and add a condition (is null) for the PostgreSQL Engine table to the WHERE condition, the WHERE condition is applied before joining.

**How to reproduce**

> ch version: 24.5.1.1763
> pg version: 12.6

pg table
```
create table public.pg_table
(
    id int,
    name varchar(10)
);

insert into public.pg_table values (1, 'name 1'), (2, 'name 2'), (3, 'name 3');
```

ch tables
```
-- pg_table (PostgreSQL Engine)
create table default.pg_table 
(
    id Int32,
    name String
)
ENGINE = PostgreSQL(PG_NAMED_COLLECTION, table = 'pg_table');

-- ch_table
create table default.ch_table 
(
    id Int32,
    pg_id Int32
)
engine = MergeTree
order by id;

insert into default.ch_table values (1, 1), (2, 2), (3, 3), (4, 1), (5, 2);
```

query
```
select
    t1.id,
    t1.pg_id,
    t2.id AS id_of_pg_table,
    t2.name AS name_of_pg_table
from default.ch_table t1
left outer join default.pg_table t2
on t1.pg_id = t2.id
where name_of_pg_table is null;
```

**Expected behavior**

return nothing.

**Error message and/or stacktrace**

![image](https://github.com/ClickHouse/ClickHouse/assets/144005614/b089222b-eef6-441f-adc4-c6954ed0895d)

**Additional context**

https://clickhousedb.slack.com/archives/CU478UEQZ/p1719802361432549

**Comment by nickitat** [comment]
@vdimir could you pls help me to understand if this pr https://github.com/ClickHouse/ClickHouse/pull/65835 will cover this problem too?

**Comment by vdimir** [comment]
> could you pls help me to understand if this pr https://github.com/ClickHouse/ClickHouse/pull/65835 will cover the given problem too?

I'm afraid it won't, this looks more like incorrect query is sent to postgress.

@com-exem-route7 Temporary workaround is to disable analyzer with `SET allow_experimental_analyzer=0`, I'll try to fix the issue asap.

Thanks for reporting.
