### ISSUE TITLE
Add ability to set machine_id in `generateSnowflakeID`

### ISSUE THREAD

**Issue by simpl1g** [ClickHouse/ClickHouse#66010]
**Use case**

Snowflake ID (introduced [here](https://github.com/ClickHouse/ClickHouse/pull/63577)) contain bits for the machine ID. These can be used to guarantee uniqueness between nodes, the current implementation simply uses 10 bits of the server UUID as the machine ID. With big clusters, there is a high chance that machine IDs collide. We should introduce a way to set the machine ID explicitly..

**Describe the solution you'd like**

This can be an argument of `generateSnowflakeID()` or server level configuration.

**Comment by rschu1ze** [comment]
Adding another optional parameter to `generateSnowflakeID` seems like the best approach. Volunteers welcome (adding the easy-task label).

**Comment by den-crane** [comment]
>With big clusters, there is a high chance that machine IDs collide.

How come? 
Only if you copy `/var/lib/clickhouse/uuid` from one server to another, and you should not do it. Because other CH components rely on its uniqueness.

>Adding another optional parameter to generateSnowflakeID seems like the best approach. 

But it already has one optional parameter. It will be `generateSnowflakeID('dummy', machine_id )` ?

**Comment by Slach** [comment]
@den-crane 

why not?
why just not add machine_id as secondary optional parameter?

why not extract machine_id from snowflake id `extractMachineIdFromSnowflake`

**Comment by simpl1g** [comment]
> How come?
We take only 10 bits from Server UUID, only 1024 unique values. So for 100 servers probability of `machine_id` collision will be around 99%.

**Comment by den-crane** [comment]
> @den-crane
> 
> why not? why just not add machine_id as secondary optional parameter?

because `generateSnowflakeID('dummy', machine_id )` looks inconsistent with other generators.
It should be another function `generateSnowflakeIDMachineId(machine_id, [dummy])`.

**Comment by rschu1ze** [comment]
Yet another function `generateSnowflakeIDMachineId` seems overkill, tbh.

If it is visually more pleasing, we could have the machine ID as first argument of `generateSnowflakeId`, i.e. `generateSnowflakeID([machine_id[, 'dummy']])`. That would be more or less compatible with existing usage (<-- which I suppose there is little of), while we no longer need another function.

**Comment by Zawa-ll** [comment]
Hi! I could take a look at this issue if its still open!

**Comment by Zawa-ll** [comment]
Hi! I could take a look at this issue if it is still open!

**Comment by Slach** [comment]
@Zawa-ll yes of course it still open, please make PR + tests

**Comment by Zawa-ll** [comment]
@Slach Sure, thank you! You can assign that to me! Some changes is on the way!
