### ISSUE TITLE
Caused by: java.sql.SQLException: <html> <head><title>405 Not Allowed</title></head>

### ISSUE THREAD

**Issue by z-one-one** [ClickHouse/ClickHouse#66077]
### Company or project name

clickhouse-jdbc

### Question

when  i update clickhouse-jdbc from ru.yandex.xxx to 0.6.0 ,it occured that  :
clickhouse - Exception during pool initialization.

java.sql.SQLException: <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

i also use a sslrootcert. how to resolve it?please

**Comment by Algunenano** [comment]
Please consider reporting issues with clickhouse-jdbc to the [clickhouse-jdbc repository](https://github.com/ClickHouse/clickhouse-java)
