### ISSUE TITLE
Query `SYSTEM LOAD PRIMARY KEY`

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#66074]
**Use case**

There is a query `SYSTEM UNLOAD PRIMARY KEY`, why not to have `SYSTEM LOAD PRIMARY KEY`. Probably may be useful for benchmarks to be sure that index is loaded for all parts and loading index doesn't give extra latency.

**Describe the solution you'd like**

Primary index is loaded for all parts of table.

**Comment by Zawa-ll** [comment]
Hi! I will take a look at this issue :)

**Comment by Zawa-ll** [comment]
A rebase version is created, since I found it too hard to revolve all the conflict manually using rebase (too many unrelated conflicts), can someone please add a 'can be test' tag in my new PR please? Thank you!

**Comment by alexey-milovidov** [comment]
@CurtizJ I'm not sure that we need this feature. Every new system command is something we have to support. Is there real need for that?
