### ISSUE TITLE
table ttl  slowly

### ISSUE THREAD

**Issue by yhcloud123** [ClickHouse/ClickHouse#66081]
### Question

![f25a1f14beea096c3ef757a21ed4708](https://github.com/ClickHouse/ClickHouse/assets/110751250/4ce0f0f6-c96e-4c47-a0cb-2a38b4687f5a)
![aa6c066f1e79fc21e0666383914ff04](https://github.com/ClickHouse/ClickHouse/assets/110751250/6578e56e-2168-4faa-999c-d1ffffd2bf46)
Problem: After a period of time, comparing the amount of partition data per day, it is found that a small part of the data is deleted, but it is not completely deleted.
I want to ask if it's because of the large amount of data or if there are any parameters such as merge queues that can be tuned, the desired effect is that TTL is deleted at one time, not a small part of the data that was partitioned 10 days ago at random

**Comment by yhcloud123** [comment]
How do I locate the problem, something like a queue backlog or a timeout?

**Comment by UnamedRus** [comment]
Use ttl_only_drop_parts merge tree setting

**Comment by yhcloud123** [comment]
> 使用ttl_only_drop_parts合并树设置

程序建表的，可以在已经存在的表上设置这个参数吗
按道理ttl比对删除的是最老的，实际最老的那几天数据一直没变化，都是进10几天的有在慢慢删除

**Comment by den-crane** [comment]
> > 使用ttl_only_drop_parts合并树设置
> 
> 程序建表的，可以在已经存在的表上设置这个参数吗 按道理ttl到期删除的是时间最老的，实际最老的那几天数据一直没变化，都是进10几天的有在慢慢删除 我有两套一摸一样的配置的服务对比，区别就是数据量小的ttl就会完全遵守ttl，只保留3天，数据量大这套的才会慢慢删，哪里可以看得到瓶颈呢

`alter table ttt modify setting ttl_only_drop_parts = 1`
