### ISSUE TITLE
 Bad URI syntax. (STD_EXCEPTION)

### ISSUE THREAD

**Issue by AlanZQ** [ClickHouse/ClickHouse#66080]
### Question

hdfs 路径在hdfs()中无法识别
SELECT * FROM
hdfs('hdfs://hadoop-ha/20240701/partition_col_0=ANDROID-�%08�/*', 'Parquet');
<img width="645" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/39894284/cdc8f31c-a094-4e27-9625-ded6c173e3d0">
在hdfs上浏览此目录时，是可以查看的。我的hdfs路径中，的确会存在乱码相关的路径

**Comment by konsta-danyliuk** [comment]
Hello @AlanZQ.
As far as I can see, you have HDFS HA enabled at the cluster. I'm curious if you still get the STD_EXCEPTION if you use the active NameNode address with the port instead of the cluster alias.

**Comment by AlanZQ** [comment]
> Hello @AlanZQ. As far as I can see, you have HDFS HA enabled at the cluster. I'm curious if you still get the STD_EXCEPTION if you use the active NameNode address with the port instead of the cluster alias.

Using host + port still results in this error.
