### ISSUE TITLE
Not UTC timezone given when connection is etablished

### ISSUE THREAD

**Issue by lohmag** [ClickHouse/ClickHouse#6608]
In newer versions > 19.11 Clickhouse sends non standart timezone and go app in docker image without tzdata fails:  
```
{"level":"info","ts":1566471707.4000757,"msg":"Connection to clickHouse is open"}
panic: Unable to build connClickhouse ||: Unable to ping clickHouse connection: could not load time location: unknown time zone Etc/UTC
```
GO sources - https://golang.org/src/time/zoneinfo.go?s=7575:7624#L265  
GO driver fo CH - https://github.com/kshvakov/clickhouse/blob/master/lib/data/server_info.go#L38

**Comment by den-crane** [comment]
It's not a bug. The reason of that tzdata2019.1.

```
SELECT timezone()

┌─timezone()─┐
│ Etc/UTC    │
└────────────┘

vi  /etc/default/clickhouse

export TZ=UTC

/etc/init.d/clickhouse-server restart
SELECT timezone()

┌─timezone()─┐
│ UTC        │
└────────────┘
```

**Comment by filimonov** [comment]
Most probably relates to #5828 and #5922 
Now clickhouse resolves symlinks during default timezone detection. 

/cc @alexey-milovidov
