### ISSUE TITLE
What is the Synchronous insert behavior when Zookeeper error?  Insert failed wiht ZK error, but the data is searchable 

### ISSUE THREAD

**Issue by kazhou2024** [ClickHouse/ClickHouse#66114]
### Question

What is the Synchronous insert behavior when Zookeeper error? 

1 Asynchronously Insert the data(replicated merge tree)
2024-06-06 20:06:08.8879470:  Insert to the table, but get below zookeeper error
2024-06-06 20:06:09.5837313  : Code: 244. DB::Exception: Insert failed due to zookeeper error. Please retry. Reason: Connection loss. (UNEXPECTED_ZOOKEEPER_ERROR) (version 23.3.19.32 (official build))

2. retry the same replica: query the table, if no, insert again.
2024-06-06 20:06:11.9583835,  select count() from tableA where xxx, and the rowCount >0, from our log.

But later, the data is not exsiting any more, the data is not searchable eventually

**Comment by den-crane** [comment]
It's normal behaviour. 

Sometimes it takes 10 minutes to remove a part inserted with an error. While this time data is available for selects.

```
14:25:36  960f5f93-e440-4459-9a1d-6b7c69a6b50a   Renaming temporary part tmp_insert_88709600-202312_3309680_3309680_0 to 88709600-202312_37300_37300_0
14:25:36  960f5f93-e440-4459-9a1d-6b7c69a6b50a   Session expired, path: XID overflow


14:25:38 Part 88709600-202312_37300_37300_0 in zookeeper: false, locally: true
14:25:38 Young part 88709600-202312_37300_37300_0 with age 2 seconds hasn't been added to ZooKeeper yet. It's ok.


14:34:50 There is no part 88709600-202312_37300_37300_0 in ZooKeeper, it was only in filesystem
14:34:50 Removing 8 parts from filesystem (serially): Parts: [..., 88709600-202312_37300_37300_0 ...]
```

**Comment by kazhou2024** [comment]
> It's normal behaviour.
> 
> Sometimes it takes 10 minutes to remove a part inserted with an error. While this time "failed" data is available for selects.
> 
> ```
> 14:25:36  960f5f93-e440-4459-9a1d-6b7c69a6b50a   Renaming temporary part tmp_insert_88709600-202312_3309680_3309680_0 to 88709600-202312_37300_37300_0
> 14:25:36  960f5f93-e440-4459-9a1d-6b7c69a6b50a   Session expired, path: XID overflow
> 
> 
> 14:25:38 Part 88709600-202312_37300_37300_0 in zookeeper: false, locally: true
> 14:25:38 Young part 88709600-202312_37300_37300_0 with age 2 seconds hasn't been added to ZooKeeper yet. It's ok.
> 
> 
> 14:34:50 There is no part 88709600-202312_37300_37300_0 in ZooKeeper, it was only in filesystem
> 14:34:50 Removing 8 parts from filesystem (serially): Parts: [..., 88709600-202312_37300_37300_0 ...]
> ```

Thanks Den, 
  So currently our insert logic is like 1. check exsiting , 2 insert. And we have loop retry logic to handle failure. But based on this behaviour, seems out insert logic is not correct. So any suggestion to turning our insert logic?

**Comment by den-crane** [comment]
>Upgrade to a more recent version for 2 reasons:

My log is from pretty recent version 24... something.

>Use deduplication so you can retry immediately, without needing to check if the data exists

No like that. Data will be doubled for period of time. Deduplication won't work because no information in ZK about this block.

**Comment by den-crane** [comment]
Probably re-tries on error and temporal data duplication is better solution.

**Comment by Algunenano** [comment]
> My log is from pretty recent version 24... something.

Sorry, I was replying to the original poster. You should probably tweak the retries to see why `960f5f93-e440-4459-9a1d-6b7c69a6b50a` did not recover from the ZK "failure".

> And it's even worse if deduplication will work. Because eventually this part will be detached and you will lost data the same way as of topic-starter.

This should not possible (with the current RMT code). The part will be detached only when we confirm that the data is not in keeper. If the data is not in keeper, neither should be the deduplication token, so deduplication will not happen.

**Comment by den-crane** [comment]
BTW, it can be better

1) Renaming temporary part tmp_insert_.... to 88709600-...
2) Commit ZK
3) Make part visible (active)

if 2 fails, then part stays invisible and will be detached later.
