### ISSUE TITLE
Get DEFAULT value instead NULL for LEFT JOIN

### ISSUE THREAD

**Issue by gnomeby** [ClickHouse/ClickHouse#66110]
Query:
```
SELECT *
    FROM (SELECT 'qwerty' as user, 10 as value1) as a
    LEFT JOIN (SELECT 'asda' as user, 20 as value2) as b USING user
```

returns:
```
qwerty,10,0
```

CH version: 23.8.14.6

Expected as in PostgreSQL:
```
qwerty,10,NULL
```

**Comment by den-crane** [comment]
--join_use_nulls arg                                                                               Use NULLs for non-joined rows of outer JOINs for types that can be inside Nullable. If false, use default value of corresponding

https://clickhouse.com/docs/en/operations/settings/settings#join_use_nulls

https://fiddle.clickhouse.com/24ed99d6-08bf-4690-b809-86b44facacd5

**Comment by gnomeby** [comment]
Thanks.
