### ISSUE TITLE
Logical error:  isUniqTypes()

### ISSUE THREAD

**Issue by CheSema** [ClickHouse/ClickHouse#66122]
Logical error:  isUniqTypes()
https://s3.amazonaws.com/clickhouse-test-reports/66093/78a2139f2a43752196a029995b6965ada359c954/stress_test__tsan_.html

_Originally posted by @CheSema in https://github.com/ClickHouse/ClickHouse/issues/66093#issuecomment-2210597734_

**Comment by CheSema** [comment]
If I did not figure it today, I revert https://github.com/ClickHouse/ClickHouse/pull/61601.

**Comment by CheSema** [comment]
Logical error: \'aggr_chunk\'. ---
https://s3.amazonaws.com/clickhouse-test-reports/0/0a5ee12f0b9b86e89086fc008ba9e76a60f641f4/stress_test__msan_.html

**Comment by CheSema** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/65871/37dd7756434c4a2fa780fc187505c67e92be6f45/stress_test__tsan_.html

**Comment by antaljanosbenjamin** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/66599/e25fbb6d478cc36af44d6ea60d35c28309bcb603/stress_test__debug_.html Happened in #66599

**Comment by CheSema** [comment]
I made a sensitive test.
https://github.com/ClickHouse/ClickHouse/pull/66722
