### ISSUE TITLE
Allow to provide exact value instead of "rows_before_limit_at_least"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6613]
**Describe the solution you'd like**
A setting `exact_rows_before_limit` = 0|1. When enabled, `LimitBlockInputStream` will `always_read_till_end_` (we already have this feature in code) and the field `rows_before_limit_at_least` will have precise value.

**Comment by lwolters** [comment]
Hi Alexey,

What's the status of this feature? We noted that when running limited queries with joins, the 'rows_before_limit_at_least' outputs a correct value. However, whenever running 'simple' queries on a single table the 'rows_before_limit_at_least' outputs a wrong number (smaller than the 'exact' value).

It looks like this feature will fix this. Could you tell me whenever you plan to implement this?

**Comment by alexey-milovidov** [comment]
This feature can be easily implemented, but I don't have it in plans for my team.

**Comment by MaxWk** [comment]
i want try this

**Comment by alexey-milovidov** [comment]
@MaxWk Thank you, this will be very appreciated!

**Comment by MaxWk** [comment]
> Hi Alexey,
> 
> What's the status of this feature? We noted that when running limited queries with joins, the 'rows_before_limit_at_least' outputs a correct value. However, whenever running 'simple' queries on a single table the 'rows_before_limit_at_least' outputs a wrong number (smaller than the 'exact' value).
> 
> It looks like this feature will fix this. Could you tell me whenever you plan to implement this?

Hi lwolters ,can you give me some example to reproduce this
