### ISSUE TITLE
Quickly evaluate conditions with empty IN subquery and empty INNER/RIGHT JOIN.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6615]
**Use case**
`SELECT count() FROM system.numbers WHERE number IN (SELECT toUInt64(1) WHERE 0)`
`SELECT count() FROM system.numbers INNER JOIN (SELECT toUInt64(1) AS x WHERE 0) ON system.numbers.number = x`

These queries should return zero quickly. Now they don't finish.

**Comment by 4ertus2** [comment]
It's not easy in general.
```
SELECT count() FROM system.numbers WHERE number IN (SELECT abs(x) WHERE x < 0)
```

**Comment by alexey-milovidov** [comment]
You can start executing a query and return quickly from CreatingSetsBlockInputStream after realizing that the set is empty if it's IN or INNER/RIGHT JOIN. This is one-line change.

**Comment by alexey-milovidov** [comment]
Assigned to @millb

**Comment by nicelulu** [comment]
> Assigned to @millb

Sorry, I didn't see it when I was doing it.

**Comment by alexey-milovidov** [comment]
> Sorry, I didn't see it when I was doing it.

That's all right. The only thing that matters is that the task is done :)

**Comment by alexey-milovidov** [comment]
But it isn't quite done.

**Comment by alexey-milovidov** [comment]
@nicelulu And now it's assigned to you.
