### ISSUE TITLE
insert into select dateAdd

### ISSUE THREAD

**Issue by PENGCHENGLIN007** [ClickHouse/ClickHouse#66170]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

> Put your company name or project description here

**Describe what's wrong**

>select  data_id,
dateAdd(capture_time,interval 5 day) as capture_time
from dsg.db_sql li where formatDateTime(capture_time,'%Y%m%d') = '20240531';
it has result in partition  '20240531',but  no result in this query  when i use dateAdd function.
clickhouse version is 23.4.2.11

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by alexey-milovidov** [comment]
How to reproduce?

**Comment by den-crane** [comment]
>dateAdd(capture_time,interval 5 day) as capture_time
>= '20240531';
>it has result in partition '20240531',but no result in this query when i use dateAdd function.

Why it should have a result? Logically 20240531 - 5 = **20240526**, and it's not necessarily because partitions may not match columns data because of timezones.

**Comment by PENGCHENGLIN007** [comment]
I actually want to copy the data from the current partition to a new partition, so I used the dataAdd function to calculate the time field of the new partition, but it was not successful

> > dateAdd(capture_time,interval 5 day) as capture_time
> > = '20240531';
> > it has result in partition '20240531',but no result in this query when i use dateAdd function.
> 
> Why it should have a result? Logically 20240531 - 5 = **20240526**, and it's not necessarily because partitions may not match column's data because of timezones.

I actually want to copy the data from the current partition to a new partition, so I used the dataAdd function to calculate the time field of the new partition, but it was not successful
