### ISSUE TITLE
Typo on metric `ClickHouseMetrics_KeeperOutstandingRequets`

### ISSUE THREAD

**Issue by yukha-dw** [ClickHouse/ClickHouse#66179]
**Describe what's wrong**

There is typo on metric `ClickHouseMetrics_KeeperOutstandingRequets` -> `ClickHouseMetrics_KeeperOutstandingRequests`. 

Note: Fixing this typo will introduce breaking change

Location: https://github.com/search?q=repo%3AClickHouse%2FClickHouse+KeeperOutstandingRequets&type=code

**Comment by rschu1ze** [comment]
Metrics and profile events are technically not part of ClickHouse's public interface (unlike SQL syntax), changing them is not a breaking change.
