### ISSUE TITLE
RAM memory usage for ALTER DELETE IN PARTITION 23.12.6.19

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#66177]
### Question

Hi, I've a question about RAM memory usage. I've constantly an usage of 30 GB of RAM on my Clickhouse server. Occasionally, I have to clean some data in a partition (to then re-insert it possibly in the future). It happens with a query like:
ALTER TABLE x in PARTITION '202407' WHERE ...

To make the query run faster, by having to analyze only one partition for the mutation (which I execute as synchronous).

What I noticed is that the RAM increases of like 10 GB while performing this operation, and then goes back normal. How can this huge usage of RAM be lowered? I do have spare RAM, but I'm a bit worried when things will grow.

Thanks in advance!

**Comment by den-crane** [comment]
try to reduce the mutation parallelism by increasing! of merge_tree setting `number_of_free_entries_in_pool_to_execute_mutation` https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#number-of-free-entries-in-pool-to-execute-mutation

**Comment by enzorevo** [comment]
Hi, thanks. How would this lower the RAM peak during that operation? From what I saw, this setting would not allow mutations to go through in such situations, throwing an error, right? But I need those frequent DELETEs, as otherwise my data would be not accurate.

**Comment by enzorevo** [comment]
I checked during a mutation and what i saw is this:

While there is a "IN PARTITION" keyword, it's still checking for parts which are not belonging to it, even though the partitioning key is toYYYYMM(date). How is that possible?

`table_name,mutation_257629.txt,DELETE IN PARTITION '202407' WHERE (date = '2024-07-07') AND (site_id IN (634, 1598)) AND (imported = ''),2024-07-07 12:02:07.000,[''],[257629],['202407_257583_257583_0_257628','202407_257573_257580_2_257628','202407_257237_257572_104_257628','202407_256068_257236_96_257628','202407_251415_256067_319_257628','202407_245831_251153_266_257628','202407_233305_245607_233_257628','202407_223952_233304_171_257628','202406_223947_223947_0_257628','202406_223712_223736_6_257628','202406_221939_223711_53_257628','202406_221410_221915_35_257628','202406_221114_221409_17_257628','202406_216042_221113_110_257628','202406_210356_216041_139_257628','202406_206203_210355_91_257628','202406_195416_206202_187_257628','202406_30279_195326_186_257628','202406_846_30278_163_257628','202405_185853_185853_0_257628','202405_185851_185851_0_257628','202405_185849_185849_0_257628','202405_185847_185847_0_257628','202405_690_690_0_257628','202405_689_689_0_257628','202405_15_686_2_257628','202404_660_660_0_257628','202404_60_655_2_257628','202404_10_52_1_257628','202403_585_683_1_257628','202403_485_567_1_257628','202403_374_478_1_257628','202403_289_359_1_257628','202403_208_286_1_257628','202403_121_197_1_257628','202403_16_106_1_257628','202402_698_698_0_257628','202402_554_687_1_257628','202402_9_534_2_257628','202401_664_699_1_257628'],40,0,0,,1970-01-01 00:00:00.000,

`

**Comment by den-crane** [comment]
1)

>I checked system.mutations during a mutation and what i saw in one row is this:

`system.mutations` does not matter. See `system.merges` - number of parallel merges.

2) Is it replicated table?

3) >(see the long array is the "parts_to_do_names")

Display minor issue. It shows all parts in this list but it mutates only parts related to `in partition`. https://github.com/ClickHouse/ClickHouse/pull/48941#issuecomment-1579071236

**Comment by enzorevo** [comment]
1) The table is always empty, merges are so fast I cannot catch them there, so there's no bottleneck on those.
2) No, it's not.
3) How can I ensure they do not get analyzed? Since I saw this RAM increase after some of the old partitions (the ones that shouldn't be mutated) were OPTIMIZEd, as they had lot of parts. It all suggests that it loads stuff related to old partitions which it doesn't need while mutating '202407' partition. Also, is it maybe a syntax problem? IN PARTITION '202407' is what I use. Would it be different to use IN PARTITION 202407 (without quotes) or IN PARTITION ID '202407'?

**Comment by den-crane** [comment]
1. see `system.part_log`

2. `in partition` works only with replicated tables. For plain merge_tree tables it's not implemented.

**Comment by enzorevo** [comment]
> 2. `in partition` works only with replicated tables. For plain merge_tree tables it's not implemented.

Where is it written in the docs? As I never found it. So isn't there any way to perform a IN PARTITION delete on a plain MergeTree table? Is there a specific reason?

**Comment by den-crane** [comment]
>    Where is it written in the docs?  As I never found it. 

IDNK.

>So isn't there any way to perform a IN PARTITION delete on a plain MergeTree table? 

No. No way.

>Is there a specific reason?

It's a long story. It was implemented initially, then it was implemented, then it was reverted because the implementation has critical issues. Then it came that it's nearly impossible make it perfectly correct even from a design perspective.

https://github.com/ClickHouse/ClickHouse/pull/40589
https://github.com/ClickHouse/ClickHouse/pull/41344
https://github.com/ClickHouse/ClickHouse/pull/48941

----

Disclaimer: I want to clarify that I am just an ordinary person on the Internet.
I have no connection or association with Clickhouse, Inc. or its development team.
It is important to note that my opinion holds no value and should not be considered.

**Comment by enzorevo** [comment]
Thanks for the explanation! I hope it will be implemented for normal MergeTree too!
