### ISSUE TITLE
Flaky 02480_s3_support_wildcard in debug, s3 storage

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#66180]
[cidb](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwopCldIRVJFIHRlc3RfbmFtZSBsaWtlICclMDI0ODBfczNfc3VwcG9ydF93aWxkY2FyZCUnCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQywgY2hlY2tfbmFtZSwgdGVzdF9uYW1l)

<details>
<summary>Recent Failures</summary>

| prnum | sha | dur | check_start_time | ago | check_name | test_name | report_url |
|-:|:-|-:|-:|:-|:-|:-|:-|
| 66174 | c195537a1 | 5.53 | 2024-07-06 19:17:37 | 11 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/66174/c195537a1883e153c32971c5180ad30f9aba402a/stateless_tests__debug__s3_storage__[4_6].html |
| 65267 | 1f0c60615 | 5.07 | 2024-07-05 22:38:45 | 1 day and 8 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/65267/1f0c6061556cd64225a58933177df0228b4c185a/stateless_tests__debug__s3_storage__[4_6].html |
| 66145 | d2d72794a | 5.24 | 2024-07-05 18:05:39 | 1 day and 12 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/66145/d2d72794a14459e60be1c3a88d39440af1f7a8f9/stateless_tests__debug__s3_storage__[4_6].html |
| 0 | 0a5ee12f0 | 7.65 | 2024-07-04 22:21:47 | 2 days and 8 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/0/0a5ee12f0b9b86e89086fc008ba9e76a60f641f4/stateless_tests__debug__s3_storage__[4_6].html |
| 66093 | 78a2139f2 | 5.03 | 2024-07-04 21:39:19 | 2 days and 8 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/66093/78a2139f2a43752196a029995b6965ada359c954/stateless_tests__debug__s3_storage__[4_6].html |
| 0 | af4844b28 | 5.47 | 2024-07-03 23:35:29 | 3 days and 7 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/0/af4844b284d4e8b3a7980d15b85153c4e2441bc3/stateless_tests__debug__s3_storage__[4_6].html |
| 66050 | d688d4114 | 4 | 2024-07-03 22:15:56 | 3 days and 8 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/66050/d688d4114c6ac915aeb584587b985006a39c9f15/stateless_tests__debug__s3_storage__[4_6].html |
| 0 | e3beff45c | 7 | 2024-07-03 08:22:37 | 3 days and 22 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/0/e3beff45c17f63ad991ccf57b1762f352e6f0f32/stateless_tests__debug__s3_storage__[4_6].html |
| 65977 | ee0c4093d | 3.64 | 2024-07-02 12:24:12 | 4 days and 18 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/65977/ee0c4093d461233cfb920a4a224292ea9529393b/stateless_tests__debug__s3_storage__[4_6].html |
| 65972 | dc8a8d971 | 5.6 | 2024-07-02 11:43:58 | 4 days and 18 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/65972/dc8a8d9719dada68e3f582d7479d3055238adeae/stateless_tests__debug__s3_storage__[4_6].html |
| 65941 | ef24f5178 | 10.65 | 2024-07-01 22:59:50 | 5 days and 7 hours | Stateless tests (debug, s3 storage) [4/6] | 02480_s3_support_wildcard | https://s3.amazonaws.com/clickhouse-test-reports/65941/ef24f517892891b3b298dc33cbb27493fa4ba668/stateless_tests__debug__s3_storage__[4_6].html |

</details>

**Comment by alexkats** [comment]
I looked through the failures, it looks ok from all the logs, but sometimes a key is not found in minio during listing with wildcard prefix. I see no more failures after minio upgrade, most likely it was an issue with the old version.
