### ISSUE TITLE
Incremental backup size suddenly high 23.12.6.19

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#66208]
Hi, I have a MergeTree table which gets back-upped some times over the day, with an incremental backup over a single partition as the data grows. I noticed that one day the size of one incremental backup was as high as the size of a full backup would be. In fact, checking **system.backups**, the **total_size** for that is mostly equal to **uncompressed_size**. For the other incremental backups, instead, the sizes are lower (as expected), as they're incrementing from the starting point.

Any idea on why it happens so randomly? Thanks!

**Comment by den-crane** [comment]
I guess it's because of mutations. If you mutate a table you need to backup whole table again.

**Comment by enzorevo** [comment]
> I guess it's because of mutations. If you mutate a table you need to backup the whole table again.

I think it’s not: on this table, no mutation have ever run.

**Comment by den-crane** [comment]
If a table has only partition and partition is merged constantly then it needs to backup the whole table each time.

**Comment by enzorevo** [comment]
> If a table has only partition and partition is merged constantly then it needs to backup the whole table each time.

The backup is related to a partition in which we constantly do INSERTs, so it surely gets a lot of merges, but the point of incremental backups should be that it can be used in this circumstance to avoid doing every time the full backup, right?

Just to give you an idea, out of a total of 2.00 GB of data, the incremental backup list looks like this:
1) 200 MB (base)
2) 200 MB
3) 250 MB
4) 200 MB
5) 350 MB
6) 100 MB
7) 2 GB
8) 150 MB

So that the 7-th incremental backup is strangely bigger than the others, as it had to re-backup the whole table.  So indeed it normally works as expect, apart from that specific iteration in which the increment is bigger than expected.

**Comment by den-crane** [comment]
That is expected behaviour.
Backup works against parts, merge creates new parts, new files, need to backup them all over again.


```
CREATE TABLE default.test(A Date,B String) ENGINE = MergeTree PARTITION BY A ORDER BY B;
insert into test select today(), generateUUIDv4() from numbers(1e7);

BACKUP TABLE test TO Disk('backups', 'test.zip');
BACKUP TABLE test TO Disk('backups', 'test1.zip') SETTINGS base_backup = Disk('backups', 'test.zip');

insert into test select today(), generateUUIDv4() from numbers(1);

BACKUP TABLE test TO Disk('backups', 'test2.zip') SETTINGS base_backup = Disk('backups', 'test1.zip');

optimize table test final;

BACKUP TABLE test TO Disk('backups', 'test3.zip') SETTINGS base_backup = Disk('backups', 'test2.zip');


select start_time, id, name, compressed_size from system.backups order by start_time;

┌──────────start_time─┬─id───────────────────────────────────┬─name─────────────────────────┬─compressed_size─┐
│ 2024-07-08 19:50:09 │ f7265033-7614-40cd-99eb-fdfe07eef711 │ Disk('backups', 'test.zip')  │       207985854 │
│ 2024-07-08 19:50:26 │ ad9d58f9-3278-4319-9e5e-4e7aa6754821 │ Disk('backups', 'test1.zip') │            1702 │
│ 2024-07-08 19:50:50 │ 3d10e853-e642-4ca1-93db-074afe0ec121 │ Disk('backups', 'test2.zip') │            3986 │ insert of 1 row
│ 2024-07-08 19:51:01 │ 8746b086-64ed-417e-a4f2-e72cf0f1cc69 │ Disk('backups', 'test3.zip') │       205988000 │ merge that one row
└─────────────────────┴──────────────────────────────────────┴──────────────────────────────┴─────────────────┘
```

**Comment by enzorevo** [comment]
Thanks for the explanation! So it means that some huge merge involving a lot of parts of that partition was performed, and therefore the incremental backup had to "restart" from scratch, and weights as a full backup? This means that the low size of the increments I normally see in 90% of the cases is "random" and that could be potentially always as high as a full backup (as it happened in your example)? 

If so, what is the purpose of incremental backups on MergeTrees? Since in the partitions, if they get new inserts they always get some merges, and in some cases the increments will be as heavy as a full backup (in the worst case, always)

**Comment by den-crane** [comment]
>If so, what is the purpose of incremental backups on MergeTrees?

Most of users need to backup only recent partition. For example my database stores data since 2015 with monthly partitioning. And incremental backup has size < 1 % of a base backup, because I backup only recent month.

**Comment by enzorevo** [comment]
> > If so, what is the purpose of incremental backups on MergeTrees?
> 
> Most of users need to backup only recent partition. For example my database stores data since 2015 with monthly partitioning. And incremental backup has size < 1 % of a base backup, because I backup only recent month.

Makes sense, but in that case in general wouldn’t it be better to use the PARTITION-wise backup option if you need only the recent month?

**Comment by den-crane** [comment]
>Makes sense, but in that case in general wouldn’t it be better to use the PARTITION-wise backup option if you need only the recent month?

Backup is much smarter than this approach. And uses files and checksums, so in case of a mutation if files are not changed, backup does not backup them.

**Comment by enzorevo** [comment]
Clear. Thanks!
