### ISSUE TITLE
How to parse DateTime/Date value BEFORE Unix epoch date?

### ISSUE THREAD

**Issue by w3bstate** [ClickHouse/ClickHouse#66203]
### Question

Hi!

I am trying to convert an integer value like this: 196508 into a DateTime/Date data type.

So far I have tried these approaches:

```sql
SELECT parseDateTimeBestEffort(toString(196508));
```

```sql
SELECT parseDateTime(toString(196508), '%Y%m');
```

In fact, any function that I have tried so far (_toDateTime_, _parseDateTime_, _parseDateTimeBestEffort_,_toDate_), for converting the value to a DateTime/Date data type doesn't work properly with any date before the Unix epoch date.

**Comment by alexsubota** [comment]
Hi, you need parseDateTime32\parseDateTime64 functions
