### ISSUE TITLE
Exception after upgrade to 24.6 (Block structure mismatch in ...)

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#66209]
Clickhouse v.24.6.2.17

Error occurs when selecting from a view that depends on another view with an updated column type (this functionality worked before version 24.6).

How to reproduce:
```
create or replace table test_table engine MergeTree() order by id as
select 1 as id, '2024-05-02' as date;

create or replace view test_view_t as
select * from test_table;

create or replace view test_view as
select id, toDateTime(date) as date from test_view_t;

select * from test_view where date='2024-05-02';
```

Expected behavior:
Return 1 row

Error message and/or stacktrace:
` Block structure mismatch in (columns with identical name must have identical structure) stream: different types: materialize(date) String String(size = 0) materialize(date) DateTime UInt32(size = 0). (AMBIGUOUS_COLUMN_NAME) (version 24.6.2.17 (official build))`

**Comment by wei-jiang-dns53** [comment]
version 24.7.1.422 also sees this.

**Comment by wei-jiang-dns53** [comment]
workaround:
```
select id, toDateTime(date) as date_date from test_view_t;

select * from test_view where date_date='2024-05-02';
```

use different names in test_view & test_view_t

**Comment by oleg-savko** [comment]
Also have this issue and cant upgrade ch with it :(

**Comment by alexsubota** [comment]
Any news here? @nickitat @alexey-milovidov

**Comment by alexsubota** [comment]
Hi, @Algunenano should we expect a fix in 24.9\10?

**Comment by Shlomixg** [comment]
Version 24.8.3.59 is also affected

**Comment by Algunenano** [comment]
Bisected the issue to https://github.com/ClickHouse/ClickHouse/pull/64793

**Comment by KochetovNicolai** [comment]
Simplified example
```
select * from view(select id, toDateTime(date) as date from view(select 1 as id, '2024-05-02' as date)) where date='2024-05-02';

Code: 352. DB::Exception: Received from localhost:9000. DB::Exception: Block structure mismatch in (columns with identical name must have identical structure) stream: different types:
materialize(date) String String(size = 0)
materialize(date) DateTime UInt32(size = 0). (AMBIGUOUS_COLUMN_NAME)
```
