### ISSUE TITLE
 23.8-tls version memory increases suddenly from time to time

### ISSUE THREAD

**Issue by stereon** [ClickHouse/ClickHouse#66201]
### Question

linux platform ：20.04.1-Ubuntu
clickhouse version: 23.8.15.35

 23.8-tls version memory increases suddenly from time to time

<img width="1478" alt="image" src="https://github.com/ClickHouse/ClickHouse/assets/52196865/c61e4b9f-dc7e-43ba-8550-61ebd9390b6d">

**Comment by Algunenano** [comment]
Check the logs to see what the system was doing at that time. It could be anything from queries, merges...
