### ISSUE TITLE
How delete row in cluster

### ISSUE THREAD

**Issue by rnrl1215** [ClickHouse/ClickHouse#66200]
### Question

clickhouse version: 23.2.4.12
server-1, server-2, server-3

i want to deleting row in cluster 

ex)
DELETE FROM table WHERE seq = 1

Should I connect to 3 servers and delete them?
Otherwise, is there any other easy way?

**Comment by Algunenano** [comment]
> Should I connect to 3 servers and delete them?

If the table is Replicated no, just sending the query to one is enough
