### ISSUE TITLE
How to request the clickhouse-odbc-bridge via HTTP protocol

### ISSUE THREAD

**Issue by roycyz** [ClickHouse/ClickHouse#66207]
### Question

How to request the clickhouse-odbc-bridge via HTTP protocol
The version used is 24.6.1
Start the bridge
![1](https://github.com/ClickHouse/ClickHouse/assets/20429904/92fb6802-46ce-48b3-a4bd-1975c8acf771)
Send a curl request
![2](https://github.com/ClickHouse/ClickHouse/assets/20429904/19c50383-2a90-4a2b-9882-ba44e1d4b403)
Error reported: Server and library-bridge have different versions: '0' vs. '1'
Perform ODBC testing from the client side
![3](https://github.com/ClickHouse/ClickHouse/assets/20429904/eee92dde-0119-46f3-a95e-df44c51648d9)
The test runs normally, and the corresponding bridge is also started
![4](https://github.com/ClickHouse/ClickHouse/assets/20429904/ad4fa8eb-2a31-432f-8ef5-7d8a3e0561c6)
How can I achieve accessing and receiving a response from the odbc-bridge in HTTP mode, using the method described in the webpage at https://www.bookstack.cn/read/clickhouse-21.9-zh/036805ef6ca9033c.md.

**Comment by davenger** [comment]
The problem might be that you curl command doesn't have newlines in `--data-urlencode` parameter
It should look like this
```
$ curl -d "query=SELECT PageID, ImpID, AdType FROM Keys ORDER BY PageID, ImpID" --data-urlencode "connection_string=DSN=ClickHouse;DATABASE=stat" --data-urlencode "sample_block=columns format version: 1
3 columns:
\`PageID\` String
\`ImpID\` String
\`AdType\` String
"  "http://localhost:9018/" > result.txt
``` 
as shown in example here https://clickhouse.com/docs/en/operations/utilities/odbc-bridge#example

PS. screenshots are a bad way to ask a question

**Comment by vladimir-golovchenko** [comment]
Try to define the `version` explicitly in URL:

```
curl -d "query=.." --data-urlencode "connection_string=DSN=ClickHouse;DATABASE=stat" --data-urlencode "sample_block=columns format version: 1
2 columns:
\`col1\` String
\`col2\` String
"  "http://localhost:9018/?version=1" > result.txt
```
