### ISSUE TITLE
Benchmark for vector search

### ISSUE THREAD

**Issue by jiebinn** [ClickHouse/ClickHouse#66202]
### Question

Hi all, do we have a suggested benchmark for vector search? I have tried the dataset from laion.ai and calculate `L2Distance`.

**Comment by rschu1ze** [comment]
Yes, [LAION](https://clickhouse.com/docs/en/getting-started/example-datasets/laion) would be a good benchmark.

**Comment by jiebinn** [comment]
@rschu1ze Thanks. BTW, do we have a slack channel for discussion?

**Comment by rschu1ze** [comment]
https://clickhousedb.slack.com

**Comment by jiebinn** [comment]
> https://clickhousedb.slack.com

Tried to login and it said there isn't an account on ClickHouse tied to this email address. It seems need the invitation before join the channel?

**Comment by rschu1ze** [comment]
https://clickhouse.com/slack

**Comment by jiebinn** [comment]
Hi @rschu1ze @alexey-milovidov , I'm trying to find some optimization opportunities for vector search in ClickHouse. But I still have some questions while build the performance test in local server.
1. Besides `L2Distance`, is there any other function we care?
2. The total data set of laion is too large. Is that fine to pick up several sub-datasets for performance test?
3. For the ANN index scenarios, ClickHouse use [usearch](https://github.com/unum-cloud/usearch) currently. We have found that the [Faiss](https://github.com/facebookresearch/faiss) is much more popular. I wonder why we choose usearch and is there any plan to use other lib if better performance?

**Comment by rschu1ze** [comment]
1. Most vector search implementations use the L2 distance, the cosine distance, or the dot product.

2. Of course, smaller sub-sets are fine. E.g., the [LAION import tutorial](https://clickhouse.com/docs/en/getting-started/example-datasets/laion) says `if you like to work with a smaller subset of the data, simply adjust the limits, e.g. seq 0 9 | ....`

3. In general, there exist many different approximate nearest neighbor search techniques (see [here](https://arxiv.org/pdf/2310.14021)), but HNSW with quantization seems to have emerged as the current state of the art, at least for in-memory vector search. Faiss and usearch both provide HNSW. Faiss is arguable more popular and more feature-rich but usearch prides itself in having a faster HNSW implementation, see the benchmarks on their [homepage](https://github.com/unum-cloud/usearch).

**Comment by jiebinn** [comment]
> 1. Most vector search implementations use the L2 distance, the cosine distance, or the dot product.
> 2. Of course, smaller sub-sets are fine. E.g., the [LAION import tutorial](https://clickhouse.com/docs/en/getting-started/example-datasets/laion) says `if you like to work with a smaller subset of the data, simply adjust the limits, e.g. seq 0 9 | ....`
> 3. In general, there exist many different approximate nearest neighbor search techniques (see [here](https://arxiv.org/pdf/2310.14021)), but HNSW with quantization seems to have emerged as the current state of the art, at least for in-memory vector search. Faiss and usearch both provide HNSW. Faiss is arguable more popular and more feature-rich but usearch prides itself in having a faster HNSW implementation, see the benchmarks on their [homepage](https://github.com/unum-cloud/usearch).

Thanks for your kind and quick answer.
