### ISSUE TITLE
max_query_size setting not used

### ISSUE THREAD

**Issue by jesse-triplewhale** [ClickHouse/ClickHouse#66215]
version: 24.5.3.5
self-hosted

The `max_query_size` setting does **not** work when it is set either via
1. settings in users.xml
2. SETTINGS clause in query

It **does** work when set via
3. `set max_query_size=...` in a session

Here is a repro that demonstrates cases 2 and 3

```
:) set max_query_size=1

SET max_query_size = 1

Query id: 758b48e0-a66d-4b4d-af5a-1540ef62d10f

Ok.

0 rows in set. Elapsed: 0.001 sec. 
```
```
:) select now()

Syntax error: failed at position 1 ('select'):

select now()

Max query size exceeded: 'select'
```
```
:) select now() settings max_query_size=10000

Syntax error: failed at position 1 ('select'):

select now() settings max_query_size=10000

Max query size exceeded: 'select'
```

**Comment by den-crane** [comment]
Chicken-egg problem.
Clickhouse needs to put SQL into a buffer with a size max_query_size. 
How to get `settings max_query_size=10000` from a buffer with size 10000 if buffer is not created yet?

**Comment by jesse-triplewhale** [comment]
So what is the purpose of the server and query settings?

**Comment by Algunenano** [comment]
> but what about the server settings?

It's a user setting. You can modify it in users.xml or in a previous query in the same session.

**Comment by jesse-triplewhale** [comment]
> > but what about the server settings?
> 
> It's a user setting. You can modify it in users.xml or in a previous query in the same session.

The server setting has no effect for me

**Comment by Algunenano** [comment]
> The server setting has no effect for me

Set it into users.xml and open a new session
