### ISSUE TITLE
error 420 cannot update column

### ISSUE THREAD

**Issue by nortar86** [ClickHouse/ClickHouse#66254]
version 23.3
The documentation says "Updating columns that are used in the calculation of the primary or the partition key is not supported."

There is a table with a primary key field1, with a date partition, ORDER BY(field1)

executed the following request
ALTER TABLE table ADD COLUMN field2 UInt32, MODIFY ORDER BY (field1, field2)

when trying to update
ALTER TABLE table UPDATE field2=5
 WHERE field1=50
 AND field2=0
an error appears with code 420 and the text that field2 has not been updated

**Comment by Algunenano** [comment]
You've added `field2` to the order by key in `ALTER TABLE table ADD COLUMN field2 UInt32, MODIFY ORDER BY (field1, field2)`. So you can't modify it and that's why you get the error `Cannot UPDATE key column `field2`.`
