### ISSUE TITLE
data is incorrect where i use a no date-based string as partition

### ISSUE THREAD

**Issue by sc750531323** [ClickHouse/ClickHouse#6626]
when i use  ReplicatedMergeTree as the table engine,my data flow is hive->buffer table->distributed table->ReplicatedMergeTree table, and the tool is waterdrop: https://github.com/InterestingLab/waterdrop . when i use a date(such as day,month) as partition,the data is correct,and when i search the system.parts table,the result is :
SELECT 
    partition, 
    name, 
    active
FROM system.parts
WHERE (table = 'test') AND (active = 1)

┌─partition──┬─name───────────────┬─active─┐
│ 2019-08-23 │ 20190823_0_39_2    │      1 │
│ 2019-08-23 │ 20190823_40_77_2   │      1 │
│ 2019-08-23 │ 20190823_78_118_2  │      1 │
│ 2019-08-23 │ 20190823_119_151_2 │      1 │
│ 2019-08-23 │ 20190823_152_152_0 │      1 │
└────────────┴────────────────────┴────────┘
but when i use a word as the partition, such as username.the system.parts is :
SELECT 
    partition, 
    name, 
    active
FROM system.parts
WHERE (table = 'test1') AND (active = 1)

┌─partition─┬─name───────────────────────────────────────┬─active─┐
│ jim    │ 6ddc380cc759664fdcff17a88564c6eb_0_72_5    │      1 │
│ jim    │ 6ddc380cc759664fdcff17a88564c6eb_73_108_5  │      1 │
│ jim    │ 6ddc380cc759664fdcff17a88564c6eb_109_114_1 │      1 │
│ lilei      │ 974bca8b8e2f969170e1dcf23a11869a_0_141_13  │      1 │
│ lilei      │ 974bca8b8e2f969170e1dcf23a11869a_142_152_2 │      1 │
│ lilei      │ 974bca8b8e2f969170e1dcf23a11869a_153_153_0 │      1 │
│ john     │ a438c7272e0d547d092cd00507b0daa4_0_5_1     │      1 │
│ john     │ a438c7272e0d547d092cd00507b0daa4_6_13_1    │      1 │
│ john     │ a438c7272e0d547d092cd00507b0daa4_14_14_0   │      1 │
│ john     │ a438c7272e0d547d092cd00507b0daa4_15_53_6   │      1 │
│ john     │ a438c7272e0d547d092cd00507b0daa4_54_70_4   │      1 │
│ john     │ a438c7272e0d547d092cd00507b0daa4_71_74_1   │      1 │
└───────────┴────────────────────────────────────────────┴────────┘
and when i use no date-based partition,the data is more then normal.I want to know why this Situation happen？ and why the column 'name' in  system.parts  change to 32charactor when i use a word-based parition ,but it seems that 'name' not change when i use date-based partition.

**Comment by 4ertus2** [comment]
It's implementations specific. Datatypes that have problems with fixed string representation are hached.

**Comment by sc750531323** [comment]
> It's implementations specific. Datatypes that have problems with fixed string representation are hached.

Thank you for your reply，i want to know if the string be hached cause the row number of the table incorrect. such as when i use a date type as the partition,the row number is 1000,this number is correct, but it become 1300 when i used string type as partition.

**Comment by 4ertus2** [comment]
Could you show the queries that return 1000 and 1300? Are all the partitions active?
