### ISSUE TITLE
Unexpected work of table engine grant

### ISSUE THREAD

**Issue by alexsubota** [ClickHouse/ClickHouse#66278]
v.24.5.4.49

**How to reproduce:**
```
create user test_user;
revoke TABLE ENGINE ON Memory from test_user;

grant CREATE TABLE ON test_schema.* TO test_user;
grant insert ON test_schema.* TO test_user;


--login as test_user
create table test_schema.test_table engine Memory as
    select 1 as id;
```

Despite revoking the right to use the Memory engine, the test_user can still create a table with this engine. Why is this happening? Am I doing something wrong?

**Comment by alexsubota** [comment]
My bad, its must be "Unexpected behaviour" instead of "feature" label

**Comment by den-crane** [comment]
```
/etc/clickhouse-server/config.xml

   <access_control_improvements>
        <!-- By default, for backward compatibility creating table with a specific table engine ignores grant,
             however you can change this behaviour by setting this to true -->
.....
        <table_engines_require_grant>false</table_engines_require_grant>
    </access_control_improvements>
```

**Comment by jsc0218** [comment]
Did you turn on table engine grant in config file?

**Comment by alexsubota** [comment]
> ```
> /etc/clickhouse-server/config.xml
> .....
>    <access_control_improvements>
> .....
>         
>         <table_engines_require_grant>false</table_engines_require_grant>
>     </access_control_improvements>
> ```

Thanks, it helped
