### ISSUE TITLE
part_log is enabled by default

### ISSUE THREAD

**Issue by idlira** [ClickHouse/ClickHouse#66319]
**Describe the issue**
The `part_log` in enabled by default.
The file mentions to uncomment the block if needed, but the comment-finish tag is wrongly place.
https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L1135

**How to reproduce**
* Which ClickHouse server version to use: latest

**Expected behavior**
Proper setting to disable part_log.

**Comment by Algunenano** [comment]
I think this is intended (https://github.com/ClickHouse/ClickHouse/pull/27631) and the comment should be updated to remove the `Uncomment if use part log.` part

**Comment by idlira** [comment]
OK, but than how can I properly disable it? Haven't found any setting like `<log_processors_profiles>0</log_processors_profiles>` to disable the profiles processor.

**Comment by den-crane** [comment]
@idlira 

```
cat /etc/clickhouse-server/config.d/z_log_disable.xml
<?xml version="1.0"?>
<clickhouse>
    <part_log remove="1"/>
</clickhouse>
```

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-system-tables-eat-my-disk/
