### ISSUE TITLE
Add "max_simultaneous_queries_for_all_users" settings.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6636]
**Use case**
To set the limit on total number of queries. That limit can be overriden. For example, it can be set to 99 for all users and dba can set it to 100 for itself to run queries even when the server is overloaded.

**Describe alternatives you've considered**
There is global `max_connections` and `max_concurrent_queries` parameters in config. When the server is overloaded, it's impossible to connect and run queries for investigation.

**Comment by nvartolomei** [comment]
Maybe instead add a option to skip max_concurrent_queries check? Use cases include not just dba, but also metrics exporters (prometheus exporter) that need to query system tables.

At the moment if the limit is hit you lose visibility into ClickHouse metrics which is not ideal.

**Comment by nvartolomei** [comment]
Or, make this part of resource pools feature, which ideally would be hierarchical. One pool for critical queries with say limit of 10 concurrent requests. Another pool for production workload with say limit of 100, with nested pools to split up this production workload between services if necessary.

**Comment by alexey-milovidov** [comment]
> Maybe instead add a option to skip max_concurrent_queries check?

The user will be able to set this limit to zero, that means unlimited.

> Or, make this part of resource pools feature, which ideally would be hierarchical.

This task has more narrow scope and should be as simple as possible.
