### ISSUE TITLE
When changing session timezone, where clause uses the wrong timezone 

### ISSUE THREAD

**Issue by Alima777** [ClickHouse/ClickHouse#66372]
I tried the latest version and 24.6 version.

When changing session timezone, the string literal in where clause is supposed to use current session timezone, but it doesn't.

Please see the test:

![image](https://github.com/ClickHouse/ClickHouse/assets/34242296/87af6659-02b1-4ea9-9e68-d70a4afd85de)

```sql
-- UTC+3
set session_timezone='Europe/Moscow';
SELECT timezone(), serverTimezone();
CREATE TABLE test_timezone (d DateTime) Engine=Memory;
-- When inserted, the current time zone of the session is resolved
INSERT INTO test_timezone VALUES ('2000-01-01 01:00:00');
-- The filter in the where condition also uses the time zone of the session, it's right.
SELECT d FROM test_timezone where d='2000-01-01 01:00:00';
SELECT '---------------------';

-- UTC+8
set session_timezone='Asia/Shanghai';
SELECT timezone(), serverTimezone();
-- After changing the session time zone, d will use the current session time zone display, it's right.
SELECT * FROM test_timezone;
-- But here the where condition is supposed to use the time zone of Shanghai, there should be no result. But finally it use the time zone of Moscow to filter, and showing the result of Shanghai, it's strange
SELECT * FROM test_timezone where d = '2000-01-01 01:00:00';
```

**Comment by Alima777** [comment]
@zvonand Hi, can you help check this? Thanks

**Comment by zvonand** [comment]
AFAIR, this behavior is correct.

The string in `WHERE` clause is being implicitly converted to the type of the column it is being compared to, not to some external type. The column type is defined on table creation, and changing `session_timezone` later does not change the existing column type. 

I already seen such behavior in some other issues, but don't remember the exact ones. I can try to find it if needed.

**Comment by Alima777** [comment]
@zvonand Hi, thanks for your response.

If the implicit timezone of column will be used, then the insert operation is weird.

For example, when I insert time literal value into this dateTime column, it will use the `session_timezone` rather than the column timezone.

![image](https://github.com/ClickHouse/ClickHouse/assets/34242296/f6a43cf3-41a5-439d-bb23-c237b1ae542e)


```sql
-- UTC+3
set session_timezone='Europe/Moscow';
SELECT timezone(), serverTimezone();
-- I suppose d will be timezone of Europe/Moscow' or UTC
-- At least it will not be Shanghai
CREATE TABLE test_timezone (d DateTime) Engine=Memory;

-- UTC+8
set session_timezone='Asia/Shanghai';
SELECT timezone(), serverTimezone();
-- But when I insert time literal values, it will use Shanghai, current session_timezone
INSERT INTO test_timezone VALUES ('2000-01-01 08:00:00');
SELECT * FROM test_timezone;

set session_timezone='UTC';
SELECT * FROM test_timezone;

```

**Comment by den-crane** [comment]
Wow https://fiddle.clickhouse.com/1a300f1c-72a9-4ef4-a07f-c22d00c02c7a

**Comment by zvonand** [comment]
> Wow https://fiddle.clickhouse.com/1a300f1c-72a9-4ef4-a07f-c22d00c02c7a

Looks like it has the same nature as INSERT behavior

**Comment by Alima777** [comment]
Hi, @den-crane @zvonand So there is a problem with INSERT?

**Comment by den-crane** [comment]
@filimonov @zvonand 

I don't understand why it is https://fiddle.clickhouse.com/1f8ac587-9793-411d-a8be-6a956c3b11b8

```
SELECT count() FROM test_timezone where d = '2000-01-01 01:00:00';
--
1

detach table test_timezone; attach table test_timezone;

SELECT count() FROM test_timezone where d = '2000-01-01 01:00:00';
--
0
```

Why detach/attach table table changes the query result.

Or this https://fiddle.clickhouse.com/edcef33c-ef1b-46fb-a4ac-1b85933e1696

**Comment by zvonand** [comment]
> Why detach/attach table table changes the query's result.

At the first glance, it looks like the table columns data only stores the columns type exactly as it was declared on table creation, i.e.:
* `CREATE TABLE test_timezone (d DateTime) ...` -> `DateTime`
* `CREATE TABLE test_timezone (d DateTime('UTC') ...` -> `DateTime('UTC')`

And, when attaching, CH has no idea which timezone this data already uses, and implicit TZ is applied.    
If you specify DateTime timezone explicitly on table creation, attach/detach work as expected.

I will look into this soon, maybe it is a good idea to store TZ in table data even if it was not declared explicitely. @alexey-milovidov I think the issue shall be reopened, as this is a  weird behavior.

**Comment by Alima777** [comment]
@zvonand So what about the INSERT behavior?

As you said, when create table without explicit timezone,  implicit TZ is applied. Then in this case, 'Europe/Moscow' will be used, right? Why it uses 'Shanghai'?

```sql
-- UTC+3
set session_timezone='Europe/Moscow';
SELECT timezone(), serverTimezone();
**-- I suppose d will be timezone of Europe/Moscow'**
CREATE TABLE test_timezone (d DateTime) Engine=Memory;

-- UTC+8
set session_timezone='Asia/Shanghai';
SELECT timezone(), serverTimezone();
**-- But when I insert time literal values, it will use Shanghai, current session_timezone**
INSERT INTO test_timezone VALUES ('2000-01-01 08:00:00');
SELECT * FROM test_timezone;

set session_timezone='UTC';
SELECT * FROM test_timezone;
```

**Comment by zvonand** [comment]
> As you said, when create table without explicit timezone,  implicit TZ is applied.

Yes, but it is not applied to the table itself. I'll take a look

**Comment by den-crane** [comment]
it looks like session_timezone impacts `attach table` and it's minor problem.

The biggest issue from my POV is https://fiddle.clickhouse.com/edcef33c-ef1b-46fb-a4ac-1b85933e1696

**Comment by zvonand** [comment]
> I understand why it's works this way, and it's awful.

Why? It looks like it is perfectly understandable.  
However, my opinion may be biased :)

**Comment by den-crane** [comment]
Because it looks like 

1=1   -> true
1+1=2 -> false

and this is highly unexpeted.

**Comment by den-crane** [comment]
```
CREATE TABLE test_timezone (d DateTime) Engine=Memory
  as select '2000-01-01 00:00:00';

set session_timezone='Europe/Moscow';

SELECT d,  
       d =            '2000-01-01 00:00:00' eq1,
       d = toDateTime('2000-01-01 00:00:00') eq2,
       toDateTime(d)= '2000-01-01 00:00:00' eq3
FROM test_timezone
format PrettyCompactMonoBlock
```

it totally breaks expectations, it someone adds a setting for example in existing BI system to get reports in the specific timezone.

**Comment by den-crane** [comment]
Ah, session_timezone impacts `create table` as well as `attach table`. And it's weird because other sessions may not use session_timezone but session_timezone will impact their inserts.

**Comment by zvonand** [comment]
@den-crane what is the best thing you think that can be done? I don't think that changing the way CH converts values internally is a good idea

**Comment by den-crane** [comment]
https://fiddle.clickhouse.com/3cfa54bb-842c-4f50-816e-9c1b220188bb

```
CREATE TABLE t1(dtkey DateTime) ENGINE = MergeTree
PARTITION BY (toStartOfDay(dtkey)) ORDER BY tuple();
 
set session_timezone='America/New_York';

CREATE TABLE t2(dtkey DateTime) ENGINE = MergeTree
PARTITION BY (toStartOfDay(dtkey)) ORDER BY tuple();

insert into t1 VALUES (1756857600);
insert into t2 VALUES (1756857600);

select table, partition, partition_id,  from system.parts
where database = 'default';

   +-table-+-partition-----------+-partition_id-+
1. | t1    | 2025-09-03 00:00:00 | 1756857600   |
2. | t2    | 2025-09-02 00:00:00 | 1756785600   |
   +-------+---------------------+--------------+

select dtkey, toInt32(dtkey), _partition_id from t1;
   +---------------dtkey-+-toInt32(dtkey)-+-_partition_id-+
1. | 2025-09-02 20:00:00 |     1756857600 | 1756857600    |
   +---------------------+----------------+---------------+

select dtkey, toInt32(dtkey), _partition_id from t2;
   +---------------dtkey-+-toInt32(dtkey)-+-_partition_id-+
1. | 2025-09-02 20:00:00 |     1756857600 | 1756785600    |  1756857600 <> 1756857600
   +---------------------+----------------+---------------+
```
