### ISSUE TITLE
example in clickhouse document has error

### ISSUE THREAD

**Issue by Justontheway** [ClickHouse/ClickHouse#66371]
**Describe the unexpected behaviour**
query in [clickhouse document](https://clickhouse.com/docs/en/sql-reference/window-functions#aggregation-functions) can't be run, 
```
SELECT player, salary, team,
       avg(salary) OVER (PARTITION BY team) AS teamAvg,
       salary - teamAvg AS diff
FROM salaries;
```

it throws an exception as the following
```
Received exception from server (version 21.8.5):
Code: 47. DB::Exception: Received from 127.0.0.1:9002. DB::Exception: Unknown identifier: avg(salary) OVER (PARTITION BY team); there are columns: team, player, salary: While processing player, salary, team, avg(salary) OVER (PARTITION BY team) AS teamAvg, salary - teamAvg AS diff. (UNKNOWN_IDENTIFIER)
```

**How to reproduce**
following the example in clickhouse document
step1. prepare data
```
CREATE TABLE salaries
(
    `team` String,
    `player` String,
    `salary` UInt32,
    `position` String
)
Engine = Memory;

INSERT INTO salaries FORMAT Values
    ('Port Elizabeth Barbarians', 'Gary Chen', 195000, 'F'),
    ('New Coreystad Archdukes', 'Charles Juarez', 190000, 'F'),
    ('Port Elizabeth Barbarians', 'Michael Stanley', 150000, 'D'),
    ('New Coreystad Archdukes', 'Scott Harrison', 150000, 'D'),
    ('Port Elizabeth Barbarians', 'Robert George', 195000, 'M');
```
step2. run the following query
```
SELECT player, salary, team,
       avg(salary) OVER (PARTITION BY team) AS teamAvg,
       salary - teamAvg AS diff
FROM salaries;
```

* Which ClickHouse server version to use
* 21.8.5

* Which interface to use, if matters
```clickhouse-client ```

* Non-default settings, if any
```SETTINGS allow_experimental_window_functions = 1```

* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by den-crane** [comment]
See
https://github.com/ClickHouse/ClickHouse/issues/41607#issuecomment-1253762946

**Comment by Justontheway** [comment]
thank you.
if the docs support different version or annotated with something like "since 22.7" will be better.
like doc in spark https://spark.apache.org/docs/2.4.0/api/sql/index.html#months_between
