### ISSUE TITLE
It is always slow to migrate parts to s3_disk through TTL

### ISSUE THREAD

**Issue by hjun881** [ClickHouse/ClickHouse#66377]
### When migrating parts to s3_disk through TTL, it is always slow, and the same part will be migrated multiple times without success. The log shows the following information:
<Warning> zkutil::Lock: Lock is lost, because session was expired. Path: /clickhouse/zero_copy/zero_copy_s3/7dae0084-f3d2-4b58-a82e-
ef467182c398/a62f2398a3c56f2eb0a8208932f366d4_7578_11205_5/part_exclusive_lock, message: 10.208.65.139

**Comment by alexey-milovidov** [comment]
You have enabled "zero_copy_replication" which is a not supported feature.
You should have read the comment in the configuration file, discouraging from using this feature, and a runtime warning informing you of the complications.
