### ISSUE TITLE
Stateless test `02956_rocksdb_bulk_sink` is flaky

### ISSUE THREAD

**Issue by chloro-pn** [ClickHouse/ClickHouse#66419]
https://s3.amazonaws.com/clickhouse-test-reports/66344/3ba0344b98e513a82d371c07923a86afd82273d2/stateless_tests__aarch64_.html

```
2024-07-11 15:29:41 Reason: result differs with reference:  
2024-07-11 15:29:41 --- /usr/share/clickhouse-test/queries/0_stateless/02956_rocksdb_bulk_sink.reference	2024-07-11 15:16:29.309674097 +0200
2024-07-11 15:29:41 +++ /tmp/clickhouse-test/0_stateless/02956_rocksdb_bulk_sink.stdout	2024-07-11 15:29:41.282839144 +0200
2024-07-11 15:29:41 @@ -3,7 +3,7 @@
2024-07-11 15:29:41  1000
2024-07-11 15:29:41  1
2024-07-11 15:29:41  1000
2024-07-11 15:29:41 -2
2024-07-11 15:29:41 +1
2024-07-11 15:29:41  1000000
2024-07-11 15:29:41  1000
2024-07-11 15:29:41  0	999001
2024-07-11 15:29:41 
2024-07-11 15:29:41 
2024-07-11 15:29:41 
2024-07-11 15:29:41 Database: test_o1fnce19
```

**Comment by azat** [comment]
https://github.com/ClickHouse/ClickHouse/pull/66107

**Comment by alesapin** [comment]
Still reproduces https://s3.amazonaws.com/clickhouse-test-reports/0/e1ad5c765268fca75258b83c9c701c387033eca7/stateless_tests__aarch64_.html

**Comment by hanfei1991** [comment]
@alesapin the report runs with the server two weeks ago, the fix was merged one week ago. This test should have been fixed.

**Comment by hanfei1991** [comment]
I checked the failed test in the last week, all the failed pr did not contain the fix commit. this test has been resolved
https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcwMjk1Nl9yb2Nrc2RiX2J1bGtfc2luaycgQVMgbmFtZV9zdWJzdHIsCiAgICAyMCBBUyBpbnRlcnZhbF9kYXlzLAogICAgKCdTdGF0ZWxlc3MgdGVzdHMgKGFzYW4pJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcyknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzLCBhY3Rpb25zKScsICdJbnRlZ3JhdGlvbiB0ZXN0cyAoYXNhbikgWzEvM10nLCAnU3RhdGVsZXNzIHRlc3RzICh0c2FuKSBbMS8zXScpIEFTIGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcwpTRUxFQ1QKICAgIHRvU3RhcnRPZkRheShjaGVja19zdGFydF90aW1lKSBBUyBkLAogICAgY291bnQoKSwKICAgIGdyb3VwVW5pcUFycmF5KHB1bGxfcmVxdWVzdF9udW1iZXIpIEFTIHBycywKICAgIGFueShyZXBvcnRfdXJsKQpGUk9NIGNoZWNrcwpXSEVSRSAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyIE5PVCBJTiAoCiAgICBTRUxFQ1QgcHVsbF9yZXF1ZXN0X251bWJlciBBUyBwcm4KICAgIEZST00gY2hlY2tzCiAgICBXSEVSRSAocHJuICE9IDApIEFORCAoKG5vdygpIC0gdG9JbnRlcnZhbERheShpbnRlcnZhbF9kYXlzKSkgPD0gY2hlY2tfc3RhcnRfdGltZSkgQU5EIChjaGVja19uYW1lIElOIChiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MpKQopKSBBTkQgKHBvc2l0aW9uKHRlc3RfbmFtZSwgbmFtZV9zdWJzdHIpID4gMCkgQU5EICh0ZXN0X3N0YXR1cyBJTiAoJ0ZBSUwnLCAnRVJST1InLCAnRkxBS1knKSkKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK
