### ISSUE TITLE
Kakfa engine support format settings

### ISSUE THREAD

**Issue by freedomDR** [ClickHouse/ClickHouse#66431]
**Use case**

Kakfa engine support format settings 
```
create table test_kafka_tbl2 (dtm String, v1 Int64, v2 String, v3 Int32, v4 Int16)
engine = Kafka
SETTINGS kafka_broker_list = 'xxx',
kafka_topic_list = 'xxx',
kafka_group_name = 'xxx',
kafka_format = 'JSONEachRow',
kafka_format_settings = 'xx=xx,xx=xx';
```
when write or read, it is useful.

**Comment by UnamedRus** [comment]
You already can have them, so you can specify any format related settings in kafka engine definition 

https://github.com/ClickHouse/ClickHouse/blob/2ff09bdf18b344885aae7355c36f1a9cea765b40/src/Storages/Kafka/KafkaSettings.h#L52
