### ISSUE TITLE
correct way to upgrade clickhouse in docker

### ISSUE THREAD

**Issue by zav379** [ClickHouse/ClickHouse#66434]
### Company or project name

Firebird Tours

### Question

is it correctly  to upgrade clickhouse server using a simple replacement image version in docker-compose.yml from 22.1.3.7 to 23.8.3

`version: "2"

services:
  server:
    image: clickhouse/clickhouse-server:22.1.3.7
    restart: always
    volumes:
      - /tabletau/docker/clickhouse/data:/var/lib/clickhouse
      - /tabletau/docker/clickhouse/log:/var/log/
      - /tabletau/docker/clickhouse/ssl:/etc/ssl/clickhouse/
      - /tabletau/docker/clickhouse/conf/server/users.xml:/etc/clickhouse-server/users.xml
      - /tabletau/docker/clickhouse/conf/server/config.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8123:8123
      - 8443:8443
      - 9000:9000
      - 9440:9440
`

**Comment by ArctypeZach** [comment]
Yes, but it is also recommended to backup your table data before running the upgrade.

**Comment by den-crane** [comment]
>- /tabletau/docker/clickhouse/conf/server/users.xml:/etc/clickhouse-server/users.xml
>- /tabletau/docker/clickhouse/conf/server/config.xml:/etc/clickhouse-server/config.xml

This is not the best idea to replace vendor configs with own configs. It's better to use config.d and users.d folders and put own changes there. The problem that new version of Clickhouse may have mandatory elements in configs. And some settings is impossible to set using config.xml and users.xml.

https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-server-config-files/

**Comment by zav379** [comment]
Thanks

**Comment by alexey-milovidov** [comment]
Running ClickHouse in Docker is almost the same as running it without Docker.
Docker makes everything just a bit more complicated.

Upgrade procedures are described here: https://clickhouse.com/docs/en/manage/updates

**Comment by alexey-milovidov** [comment]
> "ClickHouse without Docker is like ClickHouse with Docker, but without Docker."

### Explanation

> This rephrased statement maintains the same structure and humor as the original phrase, highlighting the idea that the core functionality and identity of ClickHouse as a database management system remain the same, regardless of whether it is deployed with Docker. The emphasis is on the fact that Docker is a tool for deployment and containerization, but it does not change the inherent nature of ClickHouse itself.
