### ISSUE TITLE
CREATE USER in a cluster setup is not creating user in all nodes.

### ISSUE THREAD

**Issue by GandiYaswanthSai** [ClickHouse/ClickHouse#66464]
### Company or project name

Analytics Project with Apache Superset

### Question

I am using clickhouse cluster setup. I have few tenants and I need to isolate the data access before providing it to client. So I am creating read_only user for specific clients but they are not replicating in all the nodes. The user is created only on the node I connected to but tables are being replicated in all the nodes. Is this expected behaviour or need to configure any additional setting?

Clickhouse version : 23.12.4.15

**Comment by GandiYaswanthSai** [comment]
Found the root cause. I am not using ON CLUSTER xxxxxx in my query. Thank you.

**Comment by GandiYaswanthSai** [comment]
Found the root cause. I am not using ON CLUSTER xxxxxx in my query. Thank you.

**Comment by den-crane** [comment]
BTW you can store users in ZK, then all servers in the cluster will be in sync. And you don't need to use on_cluster.


```
    <user_directories replace="replace">
        <users_xml>
            <path>/etc/clickhouse-server/users.xml</path>
        </users_xml>
        <replicated>
            <zookeeper_path>clickhouse/mycluster/access/</zookeeper_path>
        </replicated>
    </user_directories>
```
