### ISSUE TITLE
Function "repeat"

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#6648]
**Use case**
`repeat('abc', 3) = 'abcabcabc'`
For testing purposes (generation of test cases).

**Alternatives**
`SELECT replaceRegexpOne('abc', '.+', '\\0\\0\\0')`
Not an alternative because it supports only a constant number of repetitions.

**Comment by filimonov** [comment]
Related / similar #5318

**Comment by ucasFL** [comment]
Is the two arguments of this function fixed as a string and an integer? Or it can be a Column?

**Comment by ucasFL** [comment]
@alexey-milovidov

**Comment by alexey-milovidov** [comment]
The first argument can be String, FixedString or Array. The second argument should be integer.
Both arguments can be constant / non-constant.

**Comment by alexey-milovidov** [comment]
If you will have any difficulties, it's Ok to support only String data type for the first argument.

**Comment by ahmeturun** [comment]
is there an equivalent of this with arrays, something that would populate the array with given value and given repeat times arguments?

**Comment by alexey-milovidov** [comment]
You can do the following:

```
WITH [1, 2, 3] AS arr
SELECT arrayMap(i -> (arr[1 + (i % length(arr))]), range(length(arr) * 5))

┌─arrayMap(lambda(tuple(i), arrayElement(arr, plus(1, modulo(i, length(arr))))), range(multiply(length(arr), 5)))─┐
│ [1,2,3,1,2,3,1,2,3,1,2,3,1,2,3]                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
