### ISSUE TITLE
Compile clang/llvm from sources

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#66493]
There are multiple reasons to do this:
- unable to pin compiler to specific version, since apt.llvm.org contains only latest minor version for each major
- `--target` mismatch - if `--target` does not match `LLVM_DEFAULT_TARGET_TRIPLE` then clang will not find runtime sanitizers libraries (but right now there is a workaround in docker build images)
- _patching_

Refs:
- https://github.com/llvm/llvm-project/pull/97802
- https://github.com/ClickHouse/ClickHouse/issues/66049

Cc: @alesapin

**Comment by alexey-milovidov** [comment]
Yes, and this is easy - let's do it directly in Docker.

**Comment by alexey-milovidov** [comment]
Here is how: https://github.com/ClickHouse/ClickHouse/pull/31398/commits/a517d9d65fcd6646944d45d295284edf3c87cf99#diff-cc10102f8b1db393176bb4ef3536718e0d91ca8b6c086e088953b0d951732c9bR47

**Comment by alexey-milovidov** [comment]
But checkout a fixed commit instead.

**Comment by alexey-milovidov** [comment]
Reference: https://github.com/llvm/llvm-project/issues/99453
