### ISSUE TITLE
Full table scan for engine Merge table after upgrade to 24.3.5.46

### ISSUE THREAD

**Issue by timmy21** [ClickHouse/ClickHouse#66492]
when i run below select in 24.3.5.46 after upgrade
```
SELECT count(toInt64(1)) AS `count(*)`
FROM test.m
WHERE `timestamp` >= toDateTime64('2024-07-14 00:48:17', 9, 'UTC')
  AND `timestamp` < toDateTime64('2024-07-14 01:03:17', 9, 'UTC')
SETTINGS profile = 'internal', skip_unavailable_shards = 1
```
Elapsed: 42.245 sec, read 82.43 billion rows, 659.46 GB

but the same query in clickhouse 23.8.15.35，the result is:
Elapsed: 0.706 sec, read 528.59 million rows, 4.23 GB.

test.m total rows: 82432400209

the query scan all rows in 24.3.5.46, not use order by key 'timestamp'?

all MergeTree table behind test.m has order by timestamp first
```
CREATE TABLE t_1 (
    ....
)
ENGINE = MergeTree
PARTITION BY formatDateTime(toStartOfMinute(timestamp), '%Y%m%d%H', 'UTC')
ORDER BY (timestamp, a, b)
SETTINGS max_bytes_to_merge_at_max_space_in_pool = 1073741824, index_granularity = 8192
```

**How to reproduce**
```
CREATE DATABASE test;

CREATE TABLE test.t_1
(
    timestamp DateTime64(9),
    a String,
    b String
)
ENGINE = MergeTree
PARTITION BY formatDateTime(toStartOfMinute(timestamp), '%Y%m%d%H', 'UTC')
ORDER BY (timestamp, a, b);

CREATE TABLE test.t_2
(
    timestamp DateTime64(9),
    a String,
    b String
)
ENGINE = MergeTree
PARTITION BY formatDateTime(toStartOfMinute(timestamp), '%Y%m%d%H', 'UTC')
ORDER BY (timestamp, a, b);

CREATE TABLE test.dist_t_1 (timestamp DateTime64(9), a String, b String) ENGINE = Distributed('default', 'test', 't_1');

CREATE TABLE test.dist_t_2 (timestamp DateTime64(9), a String, b String) ENGINE = Distributed('default', 'test', 't_2');

CREATE TABLE test.m ENGINE = Merge('test', '^dist_');

INSERT INTO test.t_1 (timestamp, a, b)
select
    addMinutes(toDateTime64('2024-07-13 22:00:00', 9, 'UTC'), number),
    randomString(5),
    randomString(5)
from numbers(30);

INSERT INTO test.t_1 (timestamp, a, b)
select
    addMinutes(toDateTime64('2024-07-13 23:00:00', 9, 'UTC'), number),
    randomString(5),
    randomString(5)
from numbers(30);

INSERT INTO test.t_1 (timestamp, a, b)
select
    addMinutes(toDateTime64('2024-07-14 00:00:00', 9, 'UTC'), number),
    randomString(5),
    randomString(5)
from numbers(100);


INSERT INTO test.t_2 (timestamp, a, b)
select
    addMinutes(toDateTime64('2024-07-13 22:00:00', 9, 'UTC'), number),
    randomString(5),
    randomString(5)
from numbers(30);

INSERT INTO test.t_2 (timestamp, a, b)
select
    addMinutes(toDateTime64('2024-07-13 23:00:00', 9, 'UTC'), number),
    randomString(5),
    randomString(5)
from numbers(30);

INSERT INTO test.t_2 (timestamp, a, b)
select
    addMinutes(toDateTime64('2024-07-14 00:00:00', 9, 'UTC'), number),
    randomString(5),
    randomString(5)
from numbers(100);

SELECT count(toInt64(1)) AS `count(*)`
FROM test.m
WHERE
    `timestamp` >= toDateTime64('2024-07-14 00:48:17', 9, 'UTC')
    AND `timestamp` < toDateTime64('2024-07-14 01:03:17', 9, 'UTC');
```
Elapsed: 0.019 sec, read 320 rows, 2.56 KB

but same query in clickhouse 23.8.15.35，the result is:
Elapsed: 0.027 sec, read 200 rows, 1.60 KB.

what happen？the filter not pushdown?

**Comment by den-crane** [comment]
it works 24.6.2.17 https://fiddle.clickhouse.com/8737039f-9dae-4ffa-9f71-fffafbcad7a1 Parts: 2/4

**Comment by timmy21** [comment]
> it works 24.6.2.17 https://fiddle.clickhouse.com/8737039f-9dae-4ffa-9f71-fffafbcad7a1 Parts: 2/4

ok, is this the issue? https://github.com/ClickHouse/ClickHouse/pull/62398

by the way, the "explain indexes=1" is work well in v24 for merge engine

**Comment by timmy21** [comment]
> it works 24.6.2.17 https://fiddle.clickhouse.com/8737039f-9dae-4ffa-9f71-fffafbcad7a1 Parts: 2/4

thanks, is this issue? https://github.com/ClickHouse/ClickHouse/pull/62398

by the way, clickhouse was very slow for a short time after the upgrade。what is the reason？

**Comment by timmy21** [comment]
> it works 24.6.2.17 https://fiddle.clickhouse.com/8737039f-9dae-4ffa-9f71-fffafbcad7a1 Parts: 2/4

"explain indexes=1" works well in 24.6.2.17 for merge engine 🎉

**Comment by timmy21** [comment]
but, i got another issue

```
SELECT '91138316-5127-45ac-9c25-4ad8779777b4',
  count()
FROM test.m
WHERE
    `timestamp` >= toDateTime64('2024-07-14 00:48:17', 9, 'UTC')
    AND `timestamp` < toDateTime64('2024-07-14 01:03:17', 9, 'UTC');
```

this select is failed

"exception": "Code: 44. DB::Exception: Cannot convert column `'ee5d14e8-0347-48f7-8fda-d657a3af5605'` because it is non constant in source stream but must be constant in result. (ILLEGAL_COLUMN) (version 24.6.2.17 (official build))"
