### ISSUE TITLE
Support the same type of globs in S3 and hdfs

### ISSUE THREAD

**Issue by knl** [ClickHouse/ClickHouse#66517]
**Use case**

Currently, `hdfs` supports the following [globs](https://clickhouse.com/docs/en/sql-reference/table-functions/hdfs):

> The relative URI to the file in HDFS. Path to file support following globs in readonly mode: *, ?, {abc,def} and {N..M} where N, M — numbers, `'abc', 'def' — strings. 

While `s3` [supports](https://clickhouse.com/docs/en/sql-reference/table-functions/s3):

> Bucket url with path to file. Supports following wildcards in readonly mode: *, **, ?, {abc,def} and {N..M} where N, M — numbers, 'abc', 'def' — strings. For more information see [here](https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#wildcards-in-path).

The main difference is `**`, which is allows recursion. It would be great if hdfs would also support `**`. The main reason is when one adds more (hive) partitions in hdfs, then the queries need to be modified, sometimes needlessly (when one reads all data from a particular base path).

**Comment by zvonand** [comment]
Actually it also works for `hdfs` now. I will add it do docs.

**Comment by knl** [comment]
@zvonand when was this feature implemented?

I'm getting:

```
$ clickhouse-client
ClickHouse client version 24.3.5.46 (official build).
Connecting to localhost:9000 as user default.
Password for user (default):
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 24.3.5.

Warnings:
 * Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled

hxxxx :) select count(*)
from hdfs('hdfs://nameservice1/parquet/data/perf/ctm/date_id=20240722/**/*.parquet', 'Parquet')

SELECT COUNT(*)
FROM hdfs('hdfs://nameservice1/parquet/data/perf/ctm/date_id=20240722/**/*.parquet', 'Parquet')

Query id: 3ab4f293-9243-4451-82d9-eec409183665


Elapsed: 0.010 sec.

Received exception from server (version 24.3.5):
Code: 636. DB::Exception: Received from localhost:9000. DB::Exception: The table structure cannot be extracted from a Parquet format file, because there are no files in HDFS with provided path. You can specify table structure manually. (CANNOT_EXTRACT_TABLE_STRUCTURE)

hxxxx :) select count(*)
from hdfs('hdfs://nameservice1/parquet/data/perf/ctm/date_id=20240722/stream_id=*/symbol=*/*.parquet', 'Parquet')

SELECT count(*)
FROM hdfs('hdfs://nameservice1/parquet/data/perf/ctm/date_id=20240722/stream_id=*/symbol=*/*.parquet', 'Parquet')

Query id: 7ab17b2a-c84b-47fb-8083-83139b077ee8

   ┌──count()─┐
1. │ 43491803 │ -- 43.49 million
   └──────────┘

1 row in set. Elapsed: 0.583 sec. Processed 43.49 million rows, 19.30 KB (74.57 million rows/s., 33.09 KB/s.)
Peak memory usage: 131.04 MiB.

hxxxx :)
```

**Comment by zvonand** [comment]
I think it was not implemented, but it was refactored and reused :)


IIRC, @kssenii was doing a major refactor of object storage a couple of months ago, and it was included in .6 or .7 version

**Comment by knl** [comment]
I got an access to 24.6 instance, seems to be working there. Maybe it would be useful to list in the docs the version in which the feature became available.
