### ISSUE TITLE
clickhouse23.12.6.19   frequently restartin

### ISSUE THREAD

**Issue by hert525** [ClickHouse/ClickHouse#66568]
Issue Description
Our ClickHouse service in the production environment is frequently restarting, and the logs show segmentation fault errors.
ClickHouse Version: 23.12.6.19
![image](https://github.com/user-attachments/assets/1264e436-b7ae-4b2a-8bf5-817559882e72)

**Comment by Algunenano** [comment]
23.12 is not supported. Please verify with a [supported release](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#security-change-log-and-support) and provide full Fatal logs instead of a screenshot.
