### ISSUE TITLE
"Unknown identifier" while creating view using joins with table aliases

### ISSUE THREAD

**Issue by samz406** [ClickHouse/ClickHouse#6657]
hello,  I have a statistic  need  to join 5 more tables , I want to create view as  new big table, and use the table to query,I use query as create view  result. it's error.
there is sample  create sql,
```
CREATE VIEW test  AS  
SELECT B.COM_ID  FROM ITEM_DPT_MONTH A
LEFT join DC_CUST B ON A.COM_ID=B.COM_ID
```

**error info**

 `DB::Exception: Unknown identifier: B.COM_ID, context: query: 'SELECT B.COM_ID FROM ITEM_DPT_MONTH  LEFT JOIN DC_CUST ON A.COM_ID = B.COM_ID' required_names: 'A.COM_ID''B.COM_ID' source_tables: 'DC_ITEM_DPT_MONTH' 'DC_CUST' table_aliases: complex_aliases: masked_columns: array_join_columns: source_columns
`

can you give some suggest? tks!

**Comment by filimonov** [comment]
Does it work like that?
```CREATE VIEW test  AS  
SELECT B.COM_ID  FROM ITEM_DPT_MONTH
LEFT join DC_CUST USING (COM_ID)
```

**Comment by samz406** [comment]
SELECT B.COM_ID  FROM ITEM_DPT_MONTH
LEFT join DC_CUST USING (COM_ID)
this is ok,but I want to use more than 4 table join it's not work

![image](https://user-images.githubusercontent.com/3055810/63692025-5707be00-c843-11e9-8a11-50beff5f8df7.png)

**Comment by filimonov** [comment]
Can you please update ClickHouse version to 19.11 and retry?

**Comment by 4ertus2** [comment]
The error message is straightforward. There's an USING keyword into your multiple JOIN that is not supported. You are able to rewrite it with ON.

**Comment by 4ertus2** [comment]
Cannot reproduce on current master build.
```
CREATE VIEW test AS SELECT A.dummy FROM system.one A LEFT join system.one B ON A.dummy=B.dummy

CREATE VIEW test AS
SELECT A.dummy
FROM system.one AS A
LEFT JOIN system.one AS B ON A.dummy = B.dummy

Ok.
```

**Comment by samz406** [comment]
I updated ck, it's only execute select sql  is ok ,but   create view it's not work.
![image](https://user-images.githubusercontent.com/3055810/63776126-55a5c680-c913-11e9-8fec-a58a25a7ef0a.png)
