### ISSUE TITLE
When DROPing the replicated table - remove all parent paths from keeper (if empty)

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#66624]
`default_replica_path=/clickhouse/tables/{uuid}/{shard}`

When table is created the whole path in zookeeper will be created recursively, i.e. smth like 

```
/clickhouse/tables/3ce934a2-9b09-4efd-b331-30a1e1f1f6c4/1/ ...
```

But then the table is dropped clickhouse will drop only the deepmost entry in the keeper i.e. it will remove 

```
/clickhouse/tables/3ce934a2-9b09-4efd-b331-30a1e1f1f6c4/1
```

but wlll keep 

```
/clickhouse/tables/3ce934a2-9b09-4efd-b331-30a1e1f1f6c4
```

If the tables are created and removed often the list of elements in /clickhouse/tables/ can become huge, and impact negatively the performance of the keeper (more data to snapshot etc). 

It would be great to remove the parent folders also (if they are empty).

**Comment by helifu** [comment]
Duplicated with [61065](https://github.com/ClickHouse/ClickHouse/issues/61065)
