### ISSUE TITLE
javaHash sharding algorithm implementation

### ISSUE THREAD

**Issue by lpy148145** [ClickHouse/ClickHouse#66701]
### Question

What is the implementation of javaHash(id) in distributed tables

**Comment by yariks5s** [comment]
Hi, @lpy148145! The `javaHash()` function is located in the code here: [link](https://github.com/ClickHouse/ClickHouse/blob/fba71903e53eea873022cc4cb711e5e1af435987/src/Functions/FunctionsHashing.h#L491-L536). Here is the implementation of algorithm:


**For 64-bit integers (int64_t):**
	•	Split the integer into two 32-bit parts.
	•	XOR the two parts together.
**For 8-bit, 16-bit, and 32-bit signed integers:**
	•	Return the integer as is.
**For other types:**
	•	If the type is unsigned, throw an exception.
	•	Treat the bytes of the type as a string and hash it using a method similar to Java’s String.hashCode().
**Hashing string-like data:**
	•	Initialize the hash value to 0.
	•	For each byte, update the hash value as h = 31 * h + byte_value.

**Comment by lpy148145** [comment]
Thanks, If I create a distributed table and set policy_name to javaHash(id), what is the logic for writing to the shard
