### ISSUE TITLE
Matching SELECT CityHash64(1) Behavior in C, Java, or Python.

### ISSUE THREAD

**Issue by Amri91** [ClickHouse/ClickHouse#66777]
### Question

Hi everyone.

I'm trying to match ClickHouse's `cityHash64` function in Python using `clickhouse-cityhash`.

- `SELECT cityHash64('1')` returns `11413460447292444913`, matching `CityHash64("1")` in Python.
- `SELECT cityHash64(1)` returns `10577349846663553072`, but `CityHash64(struct.pack('<Q', 1))` in Python gives `10143279697293281662`.

How does ClickHouse handle integer hashing with `cityHash64`? How should I preprocess integers in Python to match ClickHouse's output?

I am using this ClickHouse tool to run cityHash64 queries: https://play.clickhouse.com/

I’ve looked into the following:

- https://github.com/ClickHouse/ClickHouse/issues/8354, specifically the commit made by alexey. I understand I should not rely on CityHash consistency, but it is too late now.
- https://github.com/ClickHouse/ClickHouse/issues/48869: I used the referenced code here: https://github.com/dpoluyanov/achord/blob/master/src/main/java/com/github/mangelion/achord/CityHash_v1_0_2.java. Again, strings are OK, but integers are not.
- I built an older version of google/cityhash, same issue. String match, but integers do not.

```c
std::string num_str = "1";
std::cout << "CityHash64('1') as string = " 
          << CityHash64(num_str.c_str(), num_str.length()) << std::endl;
```

There are many other related issues, nothing seemed to work for me.

Would you kindly share a test case that works with integers in Java, C, or Python?

Thank you.

**Comment by den-crane** [comment]
```
SELECT cityHash64(reinterpret(1, 'FixedString(8)'))

10143279697293281662

```

**Comment by Amri91** [comment]
> ```
> SELECT cityHash64(reinterpret(1, 'FixedString(8)'))
> 
> 10143279697293281662
> ```

Thank you @den-crane for your quick reply. Changing the query does indeed produce the same result as Python. However, I cannot change the ClickHouse query. It is already in production. I need to change my code (C, Java, or Python) to match it.

**Comment by den-crane** [comment]
BTW have look at https://pypi.org/project/clickhouse-cityhash/

**Comment by Amri91** [comment]
> BTW have you looked at https://pypi.org/project/clickhouse-cityhash/ ? ( https://github.com/xzkostyan/clickhouse-cityhash )

@den-crane Yes, I have. The initial results I posted are from that library.

Here are more details on how I used it:

```python
from clickhouse_cityhash.cityhash import CityHash64

CityHash64(struct.pack('<Q', 1)) # 10143279697293281662

import numpy as np

CityHash64(np.uint64(1).tobytes()) # 10143279697293281662
```

**Comment by alexey-milovidov** [comment]
cityHash64 for integers falls back to intHash64:

```
:) SELECT cityHash64(1)

SELECT cityHash64(1)

Query id: 4e515c96-9616-473d-bfe1-85bf03b4ebbd

   ┌────────cityHash64(1)─┐
1. │ 10577349846663553072 │ -- 10.58 quintillion
   └──────────────────────┘

1 row in set. Elapsed: 0.001 sec. 

:) SELECT intHash64(1)

SELECT intHash64(1)

Query id: cbebb9c7-99b5-4646-ba6b-ac294573d260

   ┌─────────intHash64(1)─┐
1. │ 10577349846663553072 │ -- 10.58 quintillion
   └──────────────────────┘

1 row in set. Elapsed: 0.001 sec.
```

**Comment by Amri91** [comment]
Thank you @alexey-milovidov for taking the time to look into this question.

It is good to know that cityHash64 falls back on intHash64 for integers. However, I am still trying to reproduce the results.

Looking into ClickHouse code, I found this function under src/Common/HashTable/Hash.h

```C
inline UInt64 intHash64(UInt64 x)
{
    x ^= x >> 33;
    x *= 0xff51afd7ed558ccdULL;
    x ^= x >> 33;
    x *= 0xc4ceb9fe1a85ec53ULL;
    x ^= x >> 33;

    return x;
}
```

I copied it in C and reproduced it in Python, both give me 12994781566227106604 instead of 10577349846663553072.

Here is the code I used.

```C
#include <iostream>
#include <cstdint>

inline uint64_t intHash64(uint64_t x)
{
    x ^= x >> 33;
    x *= 0xff51afd7ed558ccdULL;
    x ^= x >> 33;
    x *= 0xc4ceb9fe1a85ec53ULL;
    x ^= x >> 33;

    return x;
}

int main() {
    uint64_t test_value = 1ULL;
    uint64_t result = intHash64(test_value);
    std::cout << result << std::endl;
    return 0;
}
```

```Python
import numpy as np

def int_hash_64(x: np.uint64) -> np.uint64:
    x = np.uint64(x)
    with np.errstate(over='ignore'):
        x ^= x >> np.uint64(33)
        x = np.uint64(x * np.uint64(0xff51afd7ed558ccd))
        x ^= x >> np.uint64(33)
        x = np.uint64(x * np.uint64(0xc4ceb9fe1a85ec53))
        x ^= x >> np.uint64(33)
    return x

print(int_hash_64(np.uint64(1)))
```

Can you provide pointers on what else I should do, or am I incorrectly using the function?

Thank you again.

**Comment by alexey-milovidov** [comment]
To prevent interference with hash tables*, the SQL function also applies xor to its argument:

```
intHash64(x ^ 0x4CF2D2BAAE6DA887ULL);
```

\* it's well-known problem: if you put values into a hash table, and they are filtered by the value of the same hash functions that the hash table internally using, it leads to performance degradation.
