### ISSUE TITLE
 with (select 1) as x select toTypeName(x); returns Nullable(UInt8), should be UInt8.

### ISSUE THREAD

**Issue by spff** [ClickHouse/ClickHouse#66799]
And
```
with
   (select 1) as x,
   (select assumeNotNull(x)) as y,
   (select toInt64(assumeNotNull(y))) as z
select toTypeName(x), toTypeName(y), toTypeName(z), toTypeName(assumeNotNull(z));
```
returns `Nullable(UInt8)	Nullable(UInt8)	Nullable(Int64)	Int64`

https://fiddle.clickhouse.com/addb1cca-56ff-4ff9-9e0b-1e9d6820c5b8

With this behavior, I'd need to do `assumeNotNull` everywhere I'm using the constants declared with the WITH CLAUSE as a workaround.

**Comment by alexey-milovidov** [comment]
This is expected: scalar subqueries always return a Nullable type.
It is needed to allow subqueries to return empty results.

**Comment by spff** [comment]
Is there any settings to let the results become non-nullable and fallback to the default values?

**Comment by alexey-milovidov** [comment]
No.

**Comment by spff** [comment]
Ok. I put some note here, the behavior happens after 21.9
https://github.com/ClickHouse/ClickHouse/issues/50213#issuecomment-1562184462
