### ISSUE TITLE
insert [,,,] to column Array(Nullable(UInt8)) ; select get [0,0,0]

### ISSUE THREAD

**Issue by PauliKarl** [ClickHouse/ClickHouse#66800]
### Question

insert [,,,] to column Array(Nullable(UInt8)) ; select get [0,0,0]

why not get [null,null,null]

clickhouse 23.8.9.54

**Comment by alexey-milovidov** [comment]
To insert an array with three NULLs, write `[NULL, NULL, NULL]`.

**Comment by alexey-milovidov** [comment]
Explanation here: https://clickhouse.com/docs/en/interfaces/formats#tabseparated-data-formatting

> Integer numbers are written in decimal form. Numbers can contain an extra “+” character at the beginning (ignored when parsing, and not recorded when formatting). Non-negative numbers can’t contain the negative sign. When reading, it is allowed to parse an empty string as a zero, or (for signed types) a string consisting of just a minus sign as a zero. Numbers that do not fit into the corresponding data type may be parsed as a different number, without an error message.
