### ISSUE TITLE
docker release tagging (ability to fetch image w/o build number)

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#6682]
Sometimes you need to use particular patch version. Like compare bahavior of 19.11.6 vs 19.11.7.

Currently you need to know build number to fetch particular patch version:
```
docker run --rm  yandex/clickhouse-server:19.11.8
Unable to find image 'yandex/clickhouse-server:19.11.8' locally
docker: Error response from daemon: manifest for yandex/clickhouse-server:19.11.8 not found: manifest unknown: manifest unknown.

docker run --rm  yandex/clickhouse-server:19.11.8.46
# works ok
```

**Comment by alesapin** [comment]
Fixed in CI, but we have to check in the next release.

**Comment by alesapin** [comment]
It works
![image](https://user-images.githubusercontent.com/3684697/88552045-44d26900-d02c-11ea-973b-488e9fa7b15f.png)
