### ISSUE TITLE
Storage MergeTree requires 3 to 4 parameters

### ISSUE THREAD

**Issue by PlatonB** [ClickHouse/ClickHouse#6688]
ClickHouse client version 19.13.3.26 (official build).
ClickHouse server version 19.13.3 revision 54425.

В [документации](https://clickhouse.yandex/docs/ru/operations/table_engines/mergetree/) сказано:
> ENGINE — имя и параметры движка. ENGINE = MergeTree(). MergeTree не имеет параметров.

На деле же параметры требуются:
```
<...>
DB::Exception: Storage MergeTree requires 3 to 4 parameters: 
name of column with date,
[sampling element of primary key],
primary key expression,
index granularity
<...>
```

Код:
```
from clickhouse_driver import Client
client = Client('localhost')
client.execute('CREATE DATABASE test')
client.execute('USE test')
client.execute('''CREATE TABLE table
                  (col1 String, col2 Decimal(38, 5), col3 Int64)
                  ENGINE = MergeTree()''')
```

**Comment by alexey-milovidov** [comment]
Параметры в MergeTree не требуются, но при этом обязательным является указание ORDER BY (ключа сортировки).

**Comment by PlatonB** [comment]
Но он же в документации в квадратных скобках:

> CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
> (
>     name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
>     name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
>     ...
>     INDEX index_name1 expr1 TYPE type1(...) GRANULARITY value1,
>     INDEX index_name2 expr2 TYPE type2(...) GRANULARITY value2
> ) ENGINE = MergeTree()
> [PARTITION BY expr]
> [ORDER BY expr]
> [PRIMARY KEY expr]
> [SAMPLE BY expr]
> [TTL expr]
> [SETTINGS name=value, ...]

**Comment by alexey-milovidov** [comment]
@BayoNet Требуется пояснение.
Если используется актуальный способ задания свойств MergeTree, то ORDER BY является обязательным.

**Comment by alesapin** [comment]
Сообщение, которое выкидывается при неправильном указании параметров движка, очень страшное. Особенно в данном примере, когда не указаны ни параметры, ни `ORDER BY...` показывается именно старый вариант:
```
Examples:

MergeTree(EventDate, (CounterID, EventDate), 8192)

MergeTree(EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)

CollapsingMergeTree(StartDate, intHash32(UserID), (CounterID, StartDate, intHash32(UserID), VisitID), 8192, Sign)

SummingMergeTree(EventDate, (OrderID, EventDate, BannerID, PhraseID, ContextType, RegionID, PageID, IsFlat, TypeID, ResourceNo), 8192)

SummingMergeTree(EventDate, (OrderID, EventDate, BannerID, PhraseID, ContextType, RegionID, PageID, IsFlat, TypeID, ResourceNo), 8192, (Shows, Clicks, Cost, CostCur, ShowsSumPosition, ClicksSumPosition, SessionNum, SessionLen, SessionCost, GoalsNum, SessionDepth))

ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/hits', '{replica}', EventDate, intHash32(UserID), (CounterID, EventDate, intHash32(UserID), EventTime), 8192)

For further info please read the documentation: https://clickhouse.yandex/
.
```

**Comment by alexey-milovidov** [comment]
Давай переделаем в этом сообщении на актуальный синтаксис. Наверное @BayoNet сможет закоммитить?

**Comment by BayoNet** [comment]
Сделаю.

**Comment by alexey-milovidov** [comment]
@BayoNet has failed.
