### ISSUE TITLE
Flaky `test_runtime_configurable_cache_size`

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#66887]
https://s3.amazonaws.com/clickhouse-test-reports/66850/1be54641c16569e7ee3398fe0770a9b532342643/integration_tests__asan__old_analyzer__[1_6].html

It doesn't fail often but it did fail couple of times.

**Comment by rschu1ze** [comment]
https://github.com/ClickHouse/ClickHouse/pull/66903

**Comment by antonio2368** [comment]
I think I understand the problem
When there is not enough space (i.e. we have too many entries), TTLCachePolicy cleans ALL stale entries not just 1.
https://github.com/ClickHouse/ClickHouse/blob/master/src/Common/TTLCachePolicy.h#L185

So we have a timing issue if too much time passes between query executions.
E.g. let's take the logs from the failure I linked:
```
$ rg -Fa node/logs/clickhouse-server.log -e "Stored query result of query"
365:2024.07.22 11:31:51.702712 [ 13 ] {f333f073-8e8b-4322-91de-e24c941d18ca} <Trace> QueryCache: Stored query result of query "SELECT 1 SETTINGS use_query_cache = 1, query_cache_ttl = 1"
381:2024.07.22 11:31:51.926215 [ 13 ] {3f41be4c-fd7a-4f01-a659-d8468f7856ea} <Trace> QueryCache: Stored query result of query "SELECT 2 SETTINGS use_query_cache = 1, query_cache_ttl = 1"
399:2024.07.22 11:31:53.207477 [ 13 ] {6573c0d8-27ed-4112-aaf9-9082411937e0} <Trace> QueryCache: Stored query result of query "SELECT 3 SETTINGS use_query_cache = 1, query_cache_ttl = 1"
```

You see how more than 1 second passed between second and third query, so both first and second query are stale at that point.

**Comment by rschu1ze** [comment]
That makes sense, thanks! I'll make a fix.
