### ISSUE TITLE
I use lightweight delete Statement to delete history data，how to recovery the deleted data？

### ISSUE THREAD

**Issue by JianboDM** [ClickHouse/ClickHouse#66914]
### Question

I have a table rawlog，
create table rawlog（
    first_category, 
    log_date，
    occur_time
）order by occur_time
1、delete from rawlog where log_date=‘2024-03-22’ and first_category=1 to delete history date
2、After deletion, no merge has occurred. data still exists on disk，and marked delete

how can I recovery the deleted history data？

**Comment by JianboDM** [comment]
clickhouse-version：23.3.1.2823

**Comment by cangyin** [comment]
Please check #55661

TLDR example: https://fiddle.clickhouse.com/6c31bf1f-8d25-4699-9953-c53212662dcc
