### ISSUE TITLE
clickhouse restart

### ISSUE THREAD

**Issue by hert525** [ClickHouse/ClickHouse#66919]
![image](https://github.com/user-attachments/assets/b7d1290e-c0f2-4356-846d-a1d613297da6)  
After upgrading from version 22.6 to 23.12 of ClickHouse, there were two restarts within two days. Last week, another cluster also experienced the same issue

**Comment by Algunenano** [comment]
Looks the same as https://github.com/ClickHouse/ClickHouse/issues/66740

**Comment by hert525** [comment]
![image](https://github.com/user-attachments/assets/14110f12-0ed5-4663-8459-972cb6bcef7b)

**Comment by code-with-amitk** [comment]
@hert525 please provide complete stack trace, so that all frames are visible (maybe provide as txt file).
In present image only upto 3 stack frames are visible.

**Comment by hert525** [comment]
> @hert525 please provide complete stack trace, so that all frames are visible (maybe provide as txt file). In present image only upto 3 stack frames are visible. 
I have already pasted the entire stack. Please help me take a look. Thanks.

**Comment by hert525** [comment]
> @hert525 please provide complete stack trace, so that all frames are visible (maybe provide as txt file). In present image only upto 3 stack frames are visible.

I have already pasted the entire stack. Please help me take a look. Thanks.

**Comment by Algunenano** [comment]
Probably fixed by https://github.com/ClickHouse/ClickHouse/pull/67219. Please reopen if it happens in a supported version that includes that fix
