### ISSUE TITLE
Cannot schedule a task: cannot allocate thread

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#66910]
version:23.8

 executeQuery.cpp:207 Code: 439. DB::Exception: Cannot schedule a task: cannot allocate thread (threads=12, jobs=12). (CANNOT_SCHEDULE_TASK) (version 23.8.2.1) (from 10.0.0.12:4474) (in query: SELECT offset,tag_value as ls00001117 from value.value_ls_subject_offset_ls00001117 where offset=1235700 FORMAT TabSeparatedWithNamesAndTypes), Stack trace (when copying this message, always include the lines below):

0. ./build-arm64/base/poco/Foundation/./base/poco/Foundation/src/Exception.cpp:28: Poco::Exception::Exception(String const&, int) in /usr/bin/clickhouse
1. ./build-arm64/src/./src/Common/Exception.cpp:98: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) in /usr/bin/clickhouse
2. ./build-arm64/src/./contrib/llvm-project/libcxx/include/string:1499: DB::Exception::Exception<String const&, unsigned long, unsigned long&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<unsigned long>::type, std::type_identity<unsigned long&>::type>, String const&, unsigned long&&, unsigned long&) in /usr/bin/clickhouse
3. ./build-arm64/src/./src/Common/ThreadPool.cpp:137: void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda'(String const&)::operator()(String const&) const in /usr/bin/clickhouse
4. ./build-arm64/src/./src/Common/ThreadPool.cpp:0: void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool) in /usr/bin/clickhouse
5. ./build-arm64/src/./contrib/llvm-project/libcxx/include/__functional/function.h:818: ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleOrThrowOnError(std::function<void ()>, Priority) in /usr/bin/clickhouse
6. ./build-arm64/src/./contrib/llvm-project/libcxx/include/__functional/function.h:818: DB::PipelineExecutor::spawnThreads() in /usr/bin/clickhouse
7. ./build-arm64/src/./src/Processors/Executors/PipelineExecutor.cpp:371: DB::PipelineExecutor::executeImpl(unsigned long, bool) in /usr/bin/clickhouse
8. ./build-arm64/src/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:274: DB::PipelineExecutor::execute(unsigned long, bool) in /usr/bin/clickhouse
9. ./build-arm64/src/./src/Processors/Executors/CompletedPipelineExecutor.cpp:111: DB::CompletedPipelineExecutor::execute() in /usr/bin/clickhouse
10. ./build-arm64/src/./src/Interpreters/executeQuery.cpp:1423: DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, std::optional<DB::FormatSettings> const&) in /usr/bin/clickhouse
11. ./build-arm64/src/./contrib/llvm-project/libcxx/include/optional:260: DB::HTTPHandler::processQuery(DB::HTTPServerRequest&, DB::HTMLForm&, DB::HTTPServerResponse&, DB::HTTPHandler::Output&, std::optional<DB::CurrentThread::QueryScope>&) in /usr/bin/clickhouse
12. ./build-arm64/src/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:290: DB::HTTPHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&) in /usr/bin/clickhouse
13. ./build-arm64/src/./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() in /usr/bin/clickhouse
14. ./build-arm64/base/poco/Net/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() in /usr/bin/clickhouse
15. ./build-arm64/base/poco/Net/./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() in /usr/bin/clickhouse
16. ./build-arm64/base/poco/Foundation/./base/poco/Foundation/src/ThreadPool.cpp:202: Poco::PooledThread::run() in /usr/bin/clickhouse
17. ./build-arm64/base/poco/Foundation/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse
18. ? in /usr/lib64/libpthread-2.28.so
19. ? in /usr/lib64/libc-2.28.so

**Comment by alexey-milovidov** [comment]
This is unofficial build.

**Comment by UnamedRus** [comment]
Usually this kind of errors happens, when you have high CPU core count & high number of parallel queries.

Try to set `max_threads` in default profie to lower value like 24 or even less
