### ISSUE TITLE
crash when I set max_thread_pool_size to 100000

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#66913]
version:23.8

2024.07.23 13:16:33.611561 [ 39 ] {} <Error> ServerErrorHandler: Exception.cpp:235 std::exception. Code: 1001, type: NSt3__112system_errorE (demangling status: -1), e.what() = thread constructor failed: Resource temporarily unavailable, Stack trace (when copying this message, always include the lines below):

0. ./build-arm64/contrib/libcxx-cmake/./contrib/llvm-project/libcxx/src/support/runtime/stdexcept_default.ipp:33: _ZNSt13runtime_errorC2ERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE in /usr/bin/clickhouse
1. ./build-arm64/contrib/libcxx-cmake/./contrib/llvm-project/libcxx/include/string:1499: std::system_error::system_error(std::error_code, char const*) in /usr/bin/clickhouse
2. ./build-arm64/contrib/libcxx-cmake/./contrib/llvm-project/libcxx/src/system_error.cpp:290: std::__throw_system_error(int, char const*) in /usr/bin/clickhouse
3. ./build-arm64/src/Daemon/./contrib/llvm-project/libcxx/include/thread:0: std::thread::thread<SignalListener::run()::'lambda'(), void>(SignalListener::run()::'lambda'()&&) in /usr/bin/clickhouse
4. ./build-arm64/src/Daemon/./src/Daemon/BaseDaemon.cpp:274: SignalListener::run() in /usr/bin/clickhouse
5. ./build-arm64/base/poco/Foundation/./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) in /usr/bin/clickhouse
6. ? in /usr/lib64/libpthread-2.28.so
7. ? in /usr/lib64/libc-2.28.so
 (version 23.8.2.1)

**Comment by alexey-milovidov** [comment]
The operating system does not allow you to create 100,000 threads on your server configuration.

**Comment by alexey-milovidov** [comment]
By the way, this is an unofficial build, and we don't support custom modifications to ClickHouse.
