### ISSUE TITLE
mysql engine on_duplicate_clause usage

### ISSUE THREAD

**Issue by 12frame** [ClickHouse/ClickHouse#66925]
### Question

Hi, I would like to ask why there are errors when using the MySQL engine to update data. I hope to receive your help

```
select version();
23.7.4.5
```
```
CREATE NAMED COLLECTION mysql_test on cluster ck_cluster AS
        host = 'xxx',
        port = xxxx,
        database = 'xxx',
        user = 'xxx',
        password = 'xxx' ,
replace_query = 0,
on_duplicate_clause = 1;
```

```
CREATE TABLE test.test_01
(
    id UInt64 ,
  package_name   Nullable(String) ,
  app_name   Nullable(String) ,
  source_app_name   Nullable(String) ,
  update_time   Nullable(DateTime) ,
  modify_time  Nullable(DateTime) 
) ENGINE = MySQL(mysql_test ,  table='cz_game_package_mapping')';
```

```
insert into test.test_01(id, package_name, app_name, source_app_name, update_time, modify_time)
values( 775285052,'test_00',null, 'test_01', null,null) 
ON DUPLICATE KEY UPDATE source_app_name = source_app_name;
```
error message:
`Code: 27. DB::ParsingException: Cannot parse input: expected '(' before: 'ON DUPLICATE KEY UPDATE source_app_name = source_app_name;':  at row 1: While executing ValuesBlockInputFormat: data for INSERT was parsed from query. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)`

**Comment by pmusa** [comment]
Hey @12frame, it seems there is a bug when creating a table using named collections. When I try to create the table with `on_duplicate_clause=1`, clickhouse raises an error.

```
CREATE TABLE test_mysql3 (
    id Int32,
    name String
) ENGINE = MySQL('localhost:3306', 'test', 'test', 'root', '', 0, 1);

Received exception:
Code: 36. DB::Exception: Argument 'on_duplicate_clause' must be a literal with type String, got UInt64. (BAD_ARGUMENTS)
 ```

But indeed, if I do the same thing with named collections, no errors are raised.
 
The docs are not clear IMHO, but you need to define it as `on_duplicate_clause=UPDATE source_app_name = source_app_name`. And then, not pass anything when doing the insert: `insert into ... values ...;`

BTW, your duplicate syntax didn't work as expected for me. You might need to look into MySQL correct syntax to update with the new value. It worked with a fixed string though: `on_duplicate_clause = 'UPDATE name=\'duplicate\''`.

**Comment by 12frame** [comment]
Thank you very much. You can now work normally
The description in the document is indeed very vague, and there are no relevant cases to describe it. I hope you can supplement and explain it to him. Thank you
