### ISSUE TITLE
Setting default storage policy to external S3, makes queries extremely slow

### ISSUE THREAD

**Issue by ddorian** [ClickHouse/ClickHouse#66942]
**Describe what's wrong**

Create a new clean cluster (no initdb yet) with a S3 disk, and set it as the default one like in the config below.

**Does it reproduce on the most recent release?**

24.6.2.17-alpine

**How to reproduce**

* Which ClickHouse server version to use
24.6.2.17-alpine

* Non-default settings, if any

```xml
<!-- Multi-disk configuration example: -->
<clickhouse>
    <storage_configuration>
        <disks>
            <s3>
                <type>s3</type>
                <endpoint>private</endpoint>
                <region>private</region>
                <use_environment_credentials>1</use_environment_credentials>
            </s3>
            <s3_cache>
                <type>cache</type>
                <disk>s3</disk>
                <path>/ch_s3_cache/</path>
                <max_size>10Gi</max_size>
                <cache_on_write_operations>1</cache_on_write_operations>
            </s3_cache>
        </disks>

        <policies>
            <s3_main>
                <volumes>
                    <main>
                        <disk>s3_cache</disk>
                    </main>
                </volumes>
            </s3_main>
        </policies>
    </storage_configuration>

    <merge_tree>
        <storage_policy>s3_main</storage_policy>
    </merge_tree>

</clickhouse>
```

* `CREATE TABLE` statements for all tables involved

```sql
CREATE TABLE IF NOT EXISTS t2 (x Int32) ENGINE = MergeTree ORDER BY x SETTINGS storage_policy = 's3_main';
INSERT INTO t2 VALUES (88);
```
* Queries to run that lead to an unexpected result
```sql
-- run it multiple times to see that it's not caching
-- it should be 0.005ms speed with normal caching
SELECT * FROM t2;
```

**Expected behavior**

The query to be fast. Even doing `\d` is very slow compared to not having that default. I tested by just commenting the default storage policy to be `s3_main` or not.

**Comment by nickitat** [comment]
pls share profile events for your query

**Comment by ddorian** [comment]
@nickitat 
Can you link to docs on how to do it?

**Comment by nickitat** [comment]
``` sql
WITH arrayJoin(arrayZip(ProfileEvents.keys, ProfileEvents.values)) AS t
SELECT
    t.1 AS k,
    t.2 AS v
FROM system.query_log
WHERE query_id = '<query_id>'
ORDER BY k ASC
FORMAT PrettyCompactMonoBlock
```

**Comment by ddorian** [comment]
It's slow when:

1. Use a remote filesystem for /var/lib/clickhouse (efs, nfs, etc)
2. Set default tables to s3 like in the config above. 

Removing the default-storage-policy config but still keeping remote efs/nfs for data, it's fast. ONLY when you set the default storage policy to be S3, it's again very slow. The end result underneath for metadata in all cases is remote efs/nfs.

A simple create table should take a few seconds normally but here takes 60s:

```sql
990dc14b2fab :) CREATE TABLE IF NOT EXISTS tbs2 (x Int32) ENGINE = MergeTree ORDER BY x;

CREATE TABLE IF NOT EXISTS tbs2
(
    `x` Int32
)
ENGINE = MergeTree
ORDER BY x

Query id: 370c2375-7c4c-4663-9565-95a45227a95d

Ok.

0 rows in set. Elapsed: 69.988 sec. 

```

And the events:
```sql
990dc14b2fab :) WITH arrayJoin(arrayZip(ProfileEvents.keys, ProfileEvents.values)) AS t
SELECT
    t.1 AS k,
    t.2 AS v
FROM system.query_log
WHERE query_id = '370c2375-7c4c-4663-9565-95a45227a95d'
ORDER BY k ASC
FORMAT PrettyCompactMonoBlock;

WITH arrayJoin(arrayZip(ProfileEvents.keys, ProfileEvents.values)) AS t
SELECT
    t.1 AS k,
    t.2 AS v
FROM system.query_log
WHERE query_id = '370c2375-7c4c-4663-9565-95a45227a95d'
ORDER BY k ASC
FORMAT PrettyCompactMonoBlock

Query id: 4f2b172d-1fc6-451f-8aec-2df5b8a39ee4

    ┌─k───────────────────────────────────────┬────────v─┐
 1. │ ContextLock                             │       47 │
 2. │ DiskConnectionsCreated                  │        1 │
 3. │ DiskConnectionsElapsedMicroseconds      │    83349 │
 4. │ DiskConnectionsExpired                  │        1 │
 5. │ DiskConnectionsPreserved                │        1 │
 6. │ DiskS3PutObject                         │        1 │
 7. │ DiskS3WriteMicroseconds                 │   376964 │
 8. │ DiskS3WriteRequestsCount                │        1 │
 9. │ DiskWriteElapsedMicroseconds            │      408 │
10. │ FileOpen                                │        2 │
11. │ FileSync                                │        1 │
12. │ FileSyncElapsedMicroseconds             │  2860225 │
13. │ IOBufferAllocBytes                      │  3146121 │
14. │ IOBufferAllocs                          │        4 │
15. │ InitialQuery                            │        1 │
16. │ LogDebug                                │        7 │
17. │ LogTrace                                │        4 │
18. │ OSCPUVirtualTimeMicroseconds            │    22165 │
19. │ OSCPUWaitMicroseconds                   │     1535 │
20. │ OSReadChars                             │     5034 │
21. │ OSWriteBytes                            │     4096 │
22. │ OSWriteChars                            │    22251 │
23. │ PartsLockHoldMicroseconds               │      125 │
24. │ QueriesWithSubqueries                   │        1 │
25. │ Query                                   │        1 │
26. │ QueryProfilerRuns                       │       69 │
27. │ QueryProfilerSignalOverruns             │        3 │
28. │ RWLockAcquiredReadLocks                 │        1 │
29. │ RealTimeMicroseconds                    │ 70654824 │
30. │ S3PutObject                             │        1 │
31. │ S3WriteMicroseconds                     │   376964 │
32. │ S3WriteRequestsCount                    │        1 │
33. │ SoftPageFaults                          │        5 │
34. │ UserTimeMicroseconds                    │    22167 │
35. │ WriteBufferFromFileDescriptorWrite      │        2 │
36. │ WriteBufferFromFileDescriptorWriteBytes │      187 │
37. │ WriteBufferFromS3Bytes                  │        1 │
38. │ WriteBufferFromS3Microseconds           │   461178 │
    └─────────────────────────────────────────┴──────────┘

38 rows in set. Elapsed: 100.445 sec. 

990dc14b2fab :) 

```

**Comment by nickitat** [comment]
unfortunately it is still not clear.
could you please set `send_logs_level='test'`, run the same query and share the output.
also creates prob not very well introspected. so could you pls do the same for `SELECT * FROM t2;` query and share its profile events and logs too.
btw, what s3 implementation do you use? what is rtt between you and your s3 servers?

**Comment by ddorian** [comment]
> btw, what s3 implementation do you use?

I'm using R2 for data, and backblaze for metadata (juicefs). 

> what is rtt between you and your s3 servers?

For the metadata it varies 40-120ms.

See attached file 
[query_with_logs.txt](https://github.com/user-attachments/files/16376941/query_with_logs.txt)

**Comment by ddorian** [comment]
@nickitat do you have any idea? 

I suspect changing the default setting changes the storage of system tables too to the remote-s3, slowing everything down. Is that true?

**Comment by ddorian** [comment]
See new logs 
[query_with_logs2.txt](https://github.com/user-attachments/files/16444563/query_with_logs2.txt)

**Comment by nickitat** [comment]
> See new logs [query_with_logs2.txt](https://github.com/user-attachments/files/16444563/query_with_logs2.txt)

the correct sequence:
1. do the read query (`select * from tbs2`). it writes some logs, but they're not yet flushed
2. run `system flush logs`
3. run the query over `system.query_log` to collect profile events

**Comment by ddorian** [comment]
I ran it twice:

[query_with_logs3.txt](https://github.com/user-attachments/files/16445746/query_with_logs3.txt)
[query_with_logs4.txt](https://github.com/user-attachments/files/16445747/query_with_logs4.txt)

**Comment by nickitat** [comment]
yep, it is still not clear. i'd suggest to rule out moving parts and see what happens. 
1. put metadata on normal local drive and check perf
2. use default storage policy for the server and specify new policy only for the specific table (`create table t ... settings storage_policy='s3'`) and check perf

**Comment by ddorian** [comment]
> put metadata on normal local drive and check perf

This works as expected.

> use default storage policy for the server and specify new policy only for the specific table (create table t ... settings storage_policy='s3') and check perf

Also works as expected. (even though internally the system tables still go to s3)

----

The slowdown is ONLY when setting default table to s3_main AND using juicefs for the datadir. It's not when using juicefs for datadir and removing default storage policy (all tables & system tables are still on external s3). So it's probably on juicefs end (probably not caching reads and not making async writes somehow)
