### ISSUE TITLE
Integration test `test_storage_azure_blob_storage/test.py` is flaky

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#66959]
Looks like sometimes azurite doesn't start: https://s3.amazonaws.com/clickhouse-test-reports/0/d61dd473c68c68de53b3d5a540b6a655a04d9a2d/integration_tests__release__[3_4].html

**Comment by KochetovNicolai** [comment]
Can you please check this failure? It was on Jul 28, after the fix #67019 was merged on Jul 24

https://s3.amazonaws.com/clickhouse-test-reports/0/aabf7a576ce42ef03456bf846784adfd1635ccaa/integration_tests__release__[3_4].html

**Comment by Avogar** [comment]
The report @KochetovNicolai attached is actually known issue:
```
E               ERROR: for rootteststorageazureblobstorage_azurite1_1  Cannot start service azurite1: driver failed programming external connectivity on endpoint rootteststorageazureblobstorage_azurite1_1 (9f4c03f05ee5c4f679afb91d6bf41bbc23e7c22044c79a6dace70acf0e207e03): Bind for 0.0.0.0:64893 failed: port is already allocated
```

We have a speparate issue for it: https://github.com/ClickHouse/ClickHouse/issues/67333

**Comment by Avogar** [comment]
So seems like https://github.com/ClickHouse/ClickHouse/pull/67019 actually worked for the original problem. I think we can close it in faivor of https://github.com/ClickHouse/ClickHouse/issues/67333
