### ISSUE TITLE
Clickhouse client uses only first resolved ip from localhost

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#6698]
```
# clickhouse-client -h localhost
Code: 210. DB::NetException: Connection refused (localhost:9000)

# clickhouse-client -h ::1
Code: 210. DB::NetException: Connection refused (::1:9000)

# clickhouse-client -h 127.0.0.1
Connected to ClickHouse server version 19.11.3 revision 54423.

# getent ahosts localhost 
::1             STREAM localhost
::1             DGRAM  
::1             RAW    
127.0.0.1       STREAM 
127.0.0.1       DGRAM  
127.0.0.1       RAW    

# getent hosts localhost 
::1             localhost localhost.localdomain localhost6 localhost6.localdoman6


# ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.024 ms
```

Probably same issue is possible for other connection types (for example intercluster server 2  server).

**Comment by inv2004** [comment]
```
$ getent ahosts localhost
::1             STREAM localhost
::1             DGRAM
::1             RAW
127.0.0.1       STREAM
127.0.0.1       DGRAM
127.0.0.1       RAW
$ getent hosts localhost
::1             localhost localhost.localdomain localhost6 localhost6.localdomain6
```

clickhouse-client // ok
clickhouse-client --host localhost // refused 
clickhouse-client --host 127.0.0.1 // ok
clickhouse performance-test // refused
clickhouse performance-test --host localhost // refused
clickhouse performance-test --host 127.0.0.1 // ok

**Comment by alexey-milovidov** [comment]
Confirmed. This is known issue: only single DNS record is used. The issue exists from the beginning.

**Comment by inv2004** [comment]
@alexey-milovidov 
Ситуация ещё заключается в том, что у clickhouse-client и clickhouse performance-test разный выбор значения по-умолчанию.

**Comment by alexey-milovidov** [comment]
@inv2004 А вот это не представляю, почему.

**Comment by alexey-milovidov** [comment]
Also need to allow specifying multiple addresses for clickhouse-client for failover.

**Comment by alexey-milovidov** [comment]
@inv2004 The tool `clickhouse performance-test` was removed.
