### ISSUE TITLE
cast with `AS` backticks raise an error

### ISSUE THREAD

**Issue by philippevezina** [ClickHouse/ClickHouse#66988]
Using cast with a bracket in the type will raise a syntax error since version 24.5:

```
Code: 62. DB::Exception: Syntax error: failed at position 44 (')'): ). Expected one of: AS, token, Comma, OpeningRoundBracket, type name. (SYNTAX_ERROR)
```

Here is an [example](https://fiddle.clickhouse.com/89a65cb7-2400-4e3d-be29-aa25ddb5fff3).

You can see this was working in 24.4: https://fiddle.clickhouse.com/8bf98abb-abdd-43af-84dd-0d18496c756c

**Expected behavior**

Brackets should be allowed in the type definition using `AS` when the type is surrounded by backticks.

**Comment by alexey-milovidov** [comment]
When you put `DateTime64(0)` into backticks it becomes an identifier, not an expression.
