### ISSUE TITLE
ClickHouse cannot start after being shut down; the port cannot be opened.

### ISSUE THREAD

**Issue by hert525** [ClickHouse/ClickHouse#67036]
error log：
Part {part_id} doesn't have metadata version on disk, setting it to 0. It's okay if the part was created by an old version of ClickHouse

The error log is continuously printing the content shown in the image and there are no other error messages.

**Comment by den-crane** [comment]
It's not an error. It's harmless warning. It cannot prevent start.
Share the full log (attach log file).

**Comment by Algunenano** [comment]
Please don't reopen issues when the previous one was closes asking you to use a supported release ans share fatal logs.
