### ISSUE TITLE
Introduce camelCase aliases for dense_rank, percent_rank

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#67042]
These window functions are defined in SQL:2003 with underscores but in CH function names follow camelCase.

Introduce aliases:
* dense_rank -> denseRank
* percent_rank -> percentRank

**Comment by UnamedRus** [comment]
They already exist?

```
SELECT DENSE_RANK(1) OVER ()

Query id: a38308cb-5968-4961-9ca2-4b6b886948a4

┌─dense_rank(1) OVER ()─┐
│                     1 │
└───────────────────────┘

**Comment by PavlockBlaine03** [comment]
I have forked and will get to it.

**Comment by GrigoriyNovitskiy** [comment]
Hi! I would like to pick this issue, could you give me some more information about it if it's possible?

**Comment by petern48** [comment]
I'm on it. I did some searching around the repo and I'm pretty sure I know how to do this. I just need time to test the code and get my environment setup since this would be my first contribution.
