### ISSUE TITLE
Multiquery support via HTTP

### ISSUE THREAD

**Issue by jcdang** [ClickHouse/ClickHouse#6707]
**Use case**
Currently the clickhouse-client supports multiquery.  The same uses would be beneficial if they were available via the HTTP interface.

**Describe the solution you'd like**
I have a bunch of queries I want to run sequentially on ClickHouse.  I would like to submit them in one HTTP request because of network latency.

**Describe alternatives you've considered**
Submitting queries in separate requests works, but it would be faster to make one request especially when you don't care about the output of the query.

**Comment by filimonov** [comment]
I think that it will create more problems than benefits. (See comments in PR). 

Did you consider HTTP Keep-Alive instead?

**Comment by jcdang** [comment]
We are already using Keep-Alive.

@filimonov I hope you change your mind :) 

I for one will find it dramatically beneficial.

**Comment by filimonov** [comment]
Since you already have the code - can you do benchmark to illustrate the difference and Performance improvement?

Let's say 100 queries sequence 1) w/o keepalive, 2) with keepalive, and 3) in batch/multiquery mode?

**Comment by filimonov** [comment]
Also (since you don't care about the result and want to decrease the roundtrip time) - please use `format Null` for your queries

**Comment by jcdang** [comment]
This is without the format null

https://gist.github.com/jcdang/8a9242c6f4980d1e048f046651bb7146
➜  perf time ./keepalive.sh
./keepalive.sh  0.64s user 0.58s system 15% cpu 7.938 total
➜  perf time ./nokeepalive.sh
./nokeepalive.sh  0.64s user 0.58s system 14% cpu 8.202 total
➜  perf time ./multiquery.sh
./multiquery.sh  0.01s user 0.01s system 0% cpu 4.189 total

**Comment by filimonov** [comment]
That test is wrong. You don't use keealive, as curl is called for each query separately.

**Comment by jcdang** [comment]
You're right... I wrote it in python this time. 
https://gist.github.com/jcdang/b9a42a4976c389b2259202f8af264095
➜  perf time python3 keepalive.py
python3 keepalive.py  0.99s user 0.07s system 6% cpu 16.180 total
➜  perf time ./nokeepalive.sh
./nokeepalive.sh  1.93s user 1.79s system 18% cpu 20.595 total
➜  perf time ./multiquery.sh
./multiquery.sh  0.01s user 0.01s system 0% cpu 1.968 total

**Comment by filimonov** [comment]
I've fixed your test to use keepelive (in bash / curl it's a bit tricky, but doable).
https://gist.github.com/filimonov/9b7a9d3d39e0446c9b4ad8db8dab6d29

I was checking localhost, and get the following results
```
> time bash nokeepalive.sh 
real	0m2.482s
user	0m0.693s
sys	0m0.679s

>time bash keepalive.sh
real	0m0.575s
user	0m0.009s
sys	0m0.094s

> time bash multiquery.sh 
real	0m0.500s
user	0m0.010s
sys	0m0.012s
```

That's exactly what I was expecting. 

Surprisingly it's even faster than native client.
```
> time bash -c 'cat test.sql | clickhouse-client -n'
real	0m1.156s
user	0m0.096s
sys	0m0.109s
``` 

Can you check the same in your env? With slower network the difference can be a bit more visible, but I don't think that it's like dozens of times of smth like that

**Comment by filimonov** [comment]
> You're right... I wrote it in python this time.

Still not fair. You're should rewrite all 3 to python in that case.

**Comment by jcdang** [comment]
That's just my shell setup showing the folder name.  Sorry for the confusion.

Here is the results with your updates running across data centers with ClickHouse on a bigger box:
```
➜  perfmod time bash keepalive.sh
bash keepalive.sh  0.03s user 0.03s system 1% cpu 4.278 total
➜  perfmod time bash nokeepalive.sh
bash nokeepalive.sh  0.53s user 0.48s system 17% cpu 5.772 total
➜  perfmod time bash multiquery.sh
bash multiquery.sh  0.01s user 0.01s system 2% cpu 0.585 total
```

**Comment by filimonov** [comment]
OK. Now let's get back to the question: do we really need such a feature?

I understand that it's quite handy, and actually i like the idea (for example it's cool for tests), and for me the concept of "garbage in / garbage out" is clean. But I almost sure that if it will be available the users will misuse that, and then complain that something went wrong.

Can you describe the usecase? Why don't you use clickhouse-client? Why you don't care of results? I didn't look on the code in details but I think it will stop on first error, leaving the system in some dirty state - how do you plan to deal with that?

May be we can give for that feature less attractive name to emphasize that it not a good idea to use it anywhere except of tests?

**Comment by jcdang** [comment]
We have someone in our company that absolutely loves ClickHouse performance and uses clickhouse-client extensively.  He has written planning code in SQL that operates sequentially on the data.  It's come up several times -- he asks why is our application not as fast as when he runs it with clickhouse-client locally.  We'd like to be able to scale our application horizontally and not be required to have our application reside on the same virtual instance as one of the ClickHouses.

We only actually care about the end result of the aggregate table(s) we've constructed.  All the queries in sequential batch are used to produce the final table that will be queried.

In order to do clean up, we suffix the memory tables with a unique id so that we can query from system.tables and drop them as needed.

**Comment by filimonov** [comment]
And what if (just for example) the sequence will fail at the very end, when table already exists, some data is already there but it's not full? Or you create final table in single (last) step?

**Comment by jcdang** [comment]
If any of the steps fail we regard the entire run as a failure and just do the cleanup.

**Comment by filimonov** [comment]
The question is: how you will understand that some step failed if you ignore http output?

**Comment by jcdang** [comment]
The HTTP protocol will send a non 200 code.  The status code could vary but it's usually a 404 or a 500.  For example, if you want curl to report a failure on the exit code you can add `-f`.

**Comment by filimonov** [comment]
And now you will have a lot of queries. First 100 was successful, and output was started, "200 ok" header was already sent and some responce body too. And query number 101 fails (and we can't modify the status which was already sent)? How can we let you know about the problem?

**Comment by jcdang** [comment]
Is there a certain header you're passing to clickhouse?  When I test, the body is always flushed at the end.
https://github.com/yandex/ClickHouse/blob/efd9bf2d3fac03df66c8d8cca337665d4024728a/dbms/programs/server/HTTPHandler.cpp#L669

**Comment by filimonov** [comment]
Comment one line above says "if the data was not sent to client".

Check docs / code regarding  `send_progress_in_http_headers`, `buffer_size` and `wait_end_of_query`

**Comment by jcdang** [comment]
`send_progress_in_http_headers` This is headers and doesn't send a body.
`wait_end_of_query ` This is if exceeding the buffer_size will store to file.
`buffer_size` This doesn't trigger a flush to out outputstream if exceeded.

Once you send the response body, you're not allowed to send headers anymore.  But what you're getting at is a hypothetical scenario where the body is flushed early.  The answer is yes, it will break things but not only multiquery.  As far as I can tell, the ClickHouse HTTP Server only flushes early for headers.

**Comment by filimonov** [comment]
Http status is first line of http responce. If you sent at least one header that means you already sent a status.

**Comment by jcdang** [comment]
So back to your question but modified slightly... What happens half way through the progress something fails and we can't modify the status which was already sent?  Are you telling me I should grep for an error in the response body?

**Comment by filimonov** [comment]
Yes. That's one of the thing which is done bad (IMHO) in current http protocol implementation. And that multiquery will make even more mess there... 

Please check other http related issues,  lot of them mention that problem
https://github.com/yandex/ClickHouse/labels/comp-http

So IMHO we first need to work on that tech. dept. For example - implement that https://github.com/yandex/ClickHouse/issues/6294l first

**Comment by filimonov** [comment]
To consider merging such a feature in current form - we at least need to check / confirm how it will  should be tested to ensure that it works with other logic which already exists.

At least those scenarios should be tested:
1) multiquery + send_progress_in_http_headers
2) multiquery + query which will start streaming (i.e. result bigger than buffer_size) + query with errors afterwards.
3) multiquery: Summary header should give some proper / deterministic stats  ( https://github.com/yandex/ClickHouse/pull/5116 )
4) Miltiquery + queryid header (which queryid will be send?) 
5) multiquery + inserts with VALUES 

Maybe certain flag combinations can just be documented as non-supported and forbidden to avoid problems.

Also as multiqueries can contain some long-running queries we need to think about possibility to stop whole batch, so extra scenarios appear:
1) KILL QUERY
2) http timeout / disconnect in the middle of the batch
3) cancel_http_readonly_queries_on_client_close (see https://github.com/yandex/ClickHouse/pull/4213 )

**Comment by jcdang** [comment]
1. Is send_progress_in_http_headers even something that's wanted if server-sent-events gets implemented?
2. I'm thinking that if a query goes over the buffer size, it should fail the multiquery call.  Is this unreasonable?
4. I saw this being sent but it was repeating with the same value.

**Comment by filimonov** [comment]
1. With server-sent-events - all that extra metadata should be send in events, not in headers. And it should be much easier to implement multiquery / final stats / progress and other messages etc. It's possible that binary formats will be send less efficiently in that case (all newlines should be replaced to `\ndata: `) but rather is not a big issue.
2. With server-sent-events  you can just stream the data after buffer is full, and it should just work. It will be easy to check where exactly exception happened - it's enough to add some 'final' event after each processed query. And it the query was not successful - send exception code and stop execution (in future we can add the error skipping mode if it will be needed)
3. Yes, that's what i meant when was saying about mess in headers...
