### ISSUE TITLE
Function tuple() is gone from on the system.functions table

### ISSUE THREAD

**Issue by max-vostrikov** [ClickHouse/ClickHouse#67074]
After https://github.com/ClickHouse/ClickHouse/pull/54881 function `tuple()` is not in the table `system.functions`:

[current head](https://fiddle.clickhouse.com/d0660c6d-a38b-4fb3-ae09-490e078ab2c4)
[24.6](https://fiddle.clickhouse.com/ce003e09-4217-49cd-9caf-e0f5a71ffe7f) works as expected

**Comment by Algunenano** [comment]
```
SELECT *
FROM system.functions
WHERE (NOT is_aggregate) AND (origin = 'System') AND (alias_to = '') AND (length(description) < 10) AND (name = 'tuple')
ORDER BY name ASC
FORMAT TSVWithNames
```

You are removing it yourself in the query: `(length(description) < 10)`. It just got a better description in 24.7
