### ISSUE TITLE
`changeDate*` functions non-standard result for out-of-bounds value

### ISSUE THREAD

**Issue by fm4v** [ClickHouse/ClickHouse#67071]
The `changeDate*` function is returning boundary dates '1970-01-01'/'2149-06-06'/others for date type for out-of-bounds second argument values instead of throwing an error. This behavior is unexpected and could lead to silent errors in data processing.
PR https://github.com/ClickHouse/ClickHouse/pull/63186

Example for changeYear() which is applied to all `change*` functions.
```
SELECT changeYear(toDate('2000-01-01'), 1800); -- out-of-bounds
-- 1970-01-01
SELECT changeYear(toDate('2000-01-01'), -5000); -- out-of-bounds
-- 1970-01-01
SELECT changeYear(toDate('2000-01-01'), 2500); -- out-of-bounds
-- 2149-06-06
```

Expected: exception is raised. 

Python result for example:
https://www.online-python.com/2oAXMFKkQ1

**Comment by rschu1ze** [comment]
The [tests](https://github.com/ClickHouse/ClickHouse/pull/63186/files#diff-00454ab3237313d22ca1f72f2166ede26b8b39a639a02d51d4bc28fa592dc0b0) in the PR which introduced `change*` (#63186) check aforementioned out-of-bounds cases, and they do so quite systematically. Results are not completely random in out-of-bounds cases but the minimum or maximum date or datetime value is returned.

I could not find a general convention in ClickHouse how such cases are handled.

Let's look at four functions that create date or date time values:

Example 1:
- `SELECT makeDate(500, 9, 21)` (underflow) returns `1970-01-01` (which is the same behavior as `change*` but the [documentation](https://clickhouse.com/docs/en/sql-reference/functions/date-time-functions#makedate) leaves the exact behavior open.
- `SELECT makeDate(5000, 9, 21)` (overflow) also returns `1970-01-01` which is really unexpected.

Example 2:
- `SELECT toDate('500-12-30')` (underflow) throws `Cannot parse date: value is too short`
- `SELECT toDate('5000-12-30')` returns `2149-06-06` (the maximum possible date)
- `toDate` comes with variants `OrZero`, `OrNull`, and `OrDefault` which suggestes that the original function should either throw or have undefined behavior for invalid (including out-of-bounds) inputs.

Example 3:
- `SELECT addDate(toDate('2018-01-01'), INTERVAL 700 YEAR)` (overflow) produces `2120-07-26` which seems completely random (it is not the maximum possible date)
- `SELECT subDate(toDateTime64('2018-01-01', 3), INTERVAL 1000 YEAR)` (underflow) returns `1900-01-01 00:00:00.000` which is the smallest possible DateTime64.

Example 4:
- `SELECT parseDateTime('5000-01-04+23:00:00', '%Y-%m-%d+%H:%i:%s')` (overflow) throws an exception.

Based on my experience at ClickHouse, I would say SQL functions usually go with a "garbage in - garbage out" approach, i.e. require the user to know what he/she is doing. The motivation is to minimize the amount of (costly) error checking.
