### ISSUE TITLE
HTTP client does not timeout when keeper unavailable

### ISSUE THREAD

**Issue by andrewjstone** [ClickHouse/ClickHouse#67087]
**Company or project name**
Oxide Computer Company

**Describe the unexpected behaviour**
Hi all, 

I'm currently testing replicated clickhouse setups for a future deployment. I've written a little tool called [clickward]( https://github.com/oxidecomputer/clickward) to generate clusters and am using it in a test. We have our own HTTP client in rust in which we initially did not set a client timeout. The purpose of the test is to validate some functionality about clickhouse and get us used to using it. We require dynamic reconfiguration capability from both clickhouse servers and keepers. I have implemented this functionality in `clickward` and we utilize it in the following manner:

We write data to a clickhouse server that we know is available, and then we add replicas and ensure the data gets appropriately copied. We also remove replicas and make sure things still work. This all works fine. The next phase of the test is to see what happens when we start removing keeper nodes, starting, and stopping them. This is where the problem arises. In our test we perform the following: 

* Start with a 3 node keeper cluster
* Remove one node dynamically (we also change the configurations at the other nodes and clickhouse nodes). The configurations get reloaded and this all works fine.
* We attempt to read and write data and see it get replicated. This works as expected because we have 2 nodes with a quorum of 2.
* We then stop another keeper. We should lose quorum here, and we do.
* We successfully query our existing data as expected.
* We then go to insert new data, expecting this to fail eventually - we don't have quorum. This is where the problem lies. In some cases we see a timeout after 180 seconds as we expected. In other cases no timeout ever occurs and the test continues to run. I have let it run for 2+ hours on one occasion. This non-determinism is concerning.

I have since started using client side timeouts (which was always the intention), and which indeed allows the test to proceed. From what I can tell in the logs, the client connection termination is detected and http session gets cleaned up correctly, which is good news. Yet it still seems like there is a bug on the server side of clickhouse that causes a client wihout a timeout to hang sometimes on insert when there is no keeper quorum.

Here is a copy of the [working test](https://github.com/oxidecomputer/omicron/blob/c3f9bd5b48329b15800ce0a5fbdbf3082b2fbc0f/oximeter/db/tests/integration_test.rs), that includes a 15 second client timeout. On [line 221](https://github.com/oxidecomputer/omicron/blob/c3f9bd5b48329b15800ce0a5fbdbf3082b2fbc0f/oximeter/db/tests/integration_test.rs#L221-L224) of the test is where it hangs sometime without a client timeout. I would expect it to timeout after 180 seconds, as seems to be the default. Our corresponding [test schema](https://github.com/oxidecomputer/omicron/blob/c3f9bd5b48329b15800ce0a5fbdbf3082b2fbc0f/oximeter/db/schema/replicated/db-init-test.sql) is here.

**How to reproduce**
We are running ClickHouse server version 23.8.7.1 on illumos and using the HTTP interface. The test is linked above along with the test schema and library to setup clusters. You'd typically run the test by some [setup of the clickhouse](https://github.com/oxidecomputer/omicron/blob/main/docs/how-to-run.adoc#prerequisite-software) included in our `omicron` repository. This would run on a [helios](https://github.com/oxidecomputer/helios) distribution of illumos on commodity hardware. Then you could attempt to run the test I linked to above utilizing the following [PR](https://github.com/oxidecomputer/omicron/pull/6131) which contains everything else that is needed. I don't actually expect you to do this, as I think the test should be fairly able to reproduce on your own in another manner. I can also help guide and troubleshoot as needed.

**Expected behavior**
I would expect that every insert request would eventually timeout if keeper wasn't available.

**Error message and/or stacktrace**
I don't have any of this available right now as I have moved on to using a client timeout. I can almost certainly reproduce at will though given some time. What I'd like to know before I do so though, is whether my expected behavior matches yours.

**Additional context**
We use our own query language, but largely I"m just querying all the samples put into the database and ensuring the total amount read back matches what was inserted.

Here is the config for our first clickhouse server at the end of a successful test run. You can see that keeper 2 (at port 20002) was removed and keeper 4 (at port 20004) was added.

```xml
<clickhouse>

    <logger>
        <level>trace</level>
        <log>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/clickhouse-1/logs/clickhouse.log</log>
        <errorlog>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/clickhouse-1/logs/clickhouse.err.log</errorlog>
        <size>100M</size>
        <count>1</count>
    </logger>

    <path>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/clickhouse-1/data</path>

    <profiles>
        <default>
            <load_balancing>random</load_balancing>
        </default>

    </profiles>

    <users>
        <default>
            <password></password>
            <networks>
                <ip>::/0</ip>
            </networks>
            <profile>default</profile>
            <quota>default</quota>
        </default>
    </users>

    <quotas>
        <default>
            <interval>
                <duration>3600</duration>
                <queries>0</queries>
                <errors>0</errors>
                <result_rows>0</result_rows>
                <read_rows>0</read_rows>:w

                <execution_time>0</execution_time>
            </interval>
        </default>
    </quotas>

    <user_files_path>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/clickhouse-1/data/user_files</user_files_path>
    <default_profile>default</default_profile>
    <format_schema_path>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/clickhouse-1/data/format_schemas</format_schema_path>
    <display_name>oximeter_cluster-1</display_name>
    <listen_host>::1</listen_host>
    <http_port>23001</http_port>
    <tcp_port>22001</tcp_port>
    <interserver_http_port>24001</interserver_http_port>
    <interserver_http_host>::1</interserver_http_host>
    <distributed_ddl>
        <!-- Cleanup settings (active tasks will not be removed) -->

        <!-- Controls task TTL (default 1 week) -->
        <task_max_lifetime>604800</task_max_lifetime>

        <!-- Controls how often cleanup should be performed (in seconds) -->
        <cleanup_delay_period>60</cleanup_delay_period>

        <!-- Controls how many tasks could be in the queue -->
        <max_tasks_in_queue>1000</max_tasks_in_queue>
     </distributed_ddl>

    <macros>
        <shard>1</shard>
        <replica>1</replica>
        <cluster>oximeter_cluster</cluster>
    </macros>

    <remote_servers replace="true">
        <oximeter_cluster>
            <secret>some-unique-value</secret>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>::1</host>
                    <port>22001</port>
                </replica>
                <replica>
                    <host>::1</host>
                    <port>22002</port>
                </replica>
                <replica>
                    <host>::1</host>
                    <port>22003</port>
                </replica>
            </shard>
        </oximeter_cluster>
    </remote_servers>

    <zookeeper>
        <node>
            <host>[::1]</host>
            <port>20001</port>
        </node>
        <node>
            <host>[::1]</host>
            <port>20003</port>
        </node>
        <node>
            <host>[::1]</host>
            <port>20004</port>
        </node>
    </zookeeper>

</clickhouse>
```

Here is an  config for our first keeper at the end of a successful test run

```xml
<clickhouse>

    <logger>
        <level>trace</level>
        <log>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/keeper-1/logs/clickhouse-keeper.log</log>
        <errorlog>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/keeper-1/logs/clickhouse-keeper.err.log</errorlog>
        <size>100M</size>
        <count>1</count>
    </logger>

    <listen_host>::1</listen_host>
    <keeper_server>
        <enable_reconfiguration>false</enable_reconfiguration>
        <tcp_port>20001</tcp_port>
        <server_id>1</server_id>
        <log_storage_path>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/keeper-1/coordination/log</log_storage_path>
        <snapshot_storage_path>/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/keeper-1/coordination/snapshots</snapshot_storage_path>
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>trace</raft_logs_level>
        </coordination_settings>
        <raft_configuration>

            <server>
                <id>1</id>
                <hostname>::1</hostname>
                <port>21001</port>
            </server>

            <server>
                <id>3</id>
                <hostname>::1</hostname>
                <port>21003</port>
            </server>

            <server>
                <id>4</id>
                <hostname>::1</hostname>
                <port>21004</port>
            </server>

        </raft_configuration>
    </keeper_server>

</clickhouse>
```

The rest of the nodes look as expected. All timing related parameters are identical.

**Comment by Algunenano** [comment]
Some questions:
* Which table is being inserted to? The code just says `insert_samples` but I see multiple tables, some Replicated, some Distributed, and those are completely different code paths.
* What are the settings used on the query?

Some recommendations:
* Everything is much easier on CH side if you reproduce it with a simple HTTP request (such a curl command). It removes the need to validate the client.
* Please share CH error messages, specially what you get when you receive a timeout.
* Check CH logs for the operation. For replicated tables, CH is setup by default to do retries (settings `insert_keeper_max_retries`, `insert_keeper_retry_initial_backoff_ms`, `insert_keeper_retry_max_backoff_ms`) when keeper has issues. You can filter by the query_id in `/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/clickhouse-1/logs/clickhouse.log`.

**Comment by andrewjstone** [comment]
HI @Algunenano,
Thanks for getting back to me so quickly. Apologies for my late reply. I went on vacation immediately after posting the issue and just got back to it today. I have worked with my colleague @bnaecker and we were able to reproduce the issue with and without curl. Before I answer your questions below and provide more details I'd like to give you a brief overview of what we found.

In our test, before we get to our failure mode we have 2 keepers in the keeper cluster, and then I stop 1 keeper so there is no quorum. Sending an insert to a *distributed* table at clickhouse server 1, we do see retries occurring in the clickhouse logs, with the defaults for backoffs (max 10s and 20 retries). These retries do occur, but they do not occur at the retry timeout. What happens is that some of them take *much* longer to start the retry attempt: anywhere from 1 minute up to ~30 minutes. I noticed that this was occurring while watching the logs, and in one run I waited until all the retries were exhausted. In that case, the test did in fact pass, but not until nearly 2 hours of runtime. I just  never waited long enough in prior runs. Sometimes however, the test does pass after the 20 retries in ~200s, which is what I would expect. Therefore, between retries, something is occurring that takes a long time, and then eventually the retry attempt is made again. We actually see this in the log fragments below for the latest test run with curl:

```
➜  omicron git:(main) ✗ cat /tmp/integration_test-bc08e79b2924fc1d-test_cluster.17341.1-oximeter-clickward-test/clickhouse-1/logs/clickhouse.log | grep -E "(Execution|retry_count)"
2024.08.05 22:35:21.926434 [ 137 ] {} <Trace> oximeter.version (ReplicatedMergeTreeRestartingThread): Execution took 30005 ms.
2024.08.05 22:36:21.926495 [ 137 ] {} <Trace> oximeter.version (ReplicatedMergeTreeRestartingThread): Execution took 59899 ms.
2024.08.05 22:37:21.930133 [ 137 ] {} <Trace> oximeter.version (ReplicatedMergeTreeRestartingThread): Execution took 59703 ms.
2024.08.05 22:38:21.933847 [ 137 ] {} <Trace> oximeter.version (ReplicatedMergeTreeRestartingThread): Execution took 59403 ms.
2024.08.05 22:39:21.937541 [ 137 ] {} <Trace> oximeter.version (ReplicatedMergeTreeRestartingThread): Execution took 59003 ms.
2024.08.05 22:40:21.941103 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 330018 ms.
2024.08.05 22:40:21.942858 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=1 timeout=100ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:41:21.944802 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 59903 ms.
2024.08.05 22:41:21.944979 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=2 timeout=200ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:41:22.145242 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=3 timeout=400ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:42:21.948265 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 59703 ms.
2024.08.05 22:42:21.948438 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=4 timeout=800ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:43:21.952033 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 59403 ms.
2024.08.05 22:43:21.952208 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=5 timeout=1600ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:44:21.955692 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 59003 ms.
2024.08.05 22:44:21.955875 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=6 timeout=3200ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:45:21.959127 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 58503 ms.
2024.08.05 22:45:21.959303 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=7 timeout=6400ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:46:21.962526 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 57903 ms.
2024.08.05 22:46:21.962703 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=8 timeout=10000ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:47:21.965803 [ 148 ] {} <Trace> oximeter.fields_i64_local (ReplicatedMergeTreeRestartingThread): Execution took 57203 ms.
2024.08.05 22:47:21.965976 [ 5 ] {b44723ba-149d-452c-a20c-bfa8de752599} <Debug> oximeter.fields_i64_local (6c6de9bb-7278-4ea9-9be9-aee7442e4e2d) (Replicated OutputStream): ZooKeeperRetriesControl: ReplicatedMergeTreeSink::consume/commitPart: will retry due to error: retry_count=9 timeout=10000ms error=242 message=Table is in readonly mode: replica_path=/clickhouse/tables/1/fields_i64_local/replicas/1
2024.08.05 22:48:21.969122 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 810043 ms.
2024.08.05 22:49:21.972459 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 59903 ms.
2024.08.05 22:50:21.975826 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 59703 ms.
2024.08.05 22:51:21.979123 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 59403 ms.
2024.08.05 22:52:21.982301 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 59002 ms.
2024.08.05 22:53:21.985607 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 58503 ms.
2024.08.05 22:54:21.988921 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 57903 ms.
2024.08.05 22:55:21.992165 [ 125 ] {} <Trace> oximeter.measurements_cumulativef64_local (ReplicatedMergeTreeRestartingThread): Execution took 57203 ms.
2024.08.05 22:56:21.995471 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 1290068 ms.
2024.08.05 22:57:21.998684 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 59903 ms.
2024.08.05 22:58:22.002074 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 59703 ms.
2024.08.05 22:59:22.005540 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 59403 ms.
2024.08.05 23:00:22.009029 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 59003 ms.
2024.08.05 23:01:22.012477 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 58503 ms.
2024.08.05 23:02:22.015829 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 57903 ms.
2024.08.05 23:03:22.019166 [ 131 ] {} <Trace> oximeter.timeseries_schema_local (ReplicatedMergeTreeRestartingThread): Execution took 57203 ms.
2024.08.05 23:04:22.022733 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 1770094 ms.
2024.08.05 23:05:22.026243 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 59903 ms.
2024.08.05 23:06:22.029836 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 59703 ms.
2024.08.05 23:07:22.033386 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 59403 ms.
2024.08.05 23:08:22.036808 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 59003 ms.
2024.08.05 23:09:22.040201 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 58503 ms.
2024.08.05 23:10:22.043841 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 57903 ms.
2024.08.05 23:11:22.047307 [ 151 ] {} <Trace> oximeter.fields_uuid_local (ReplicatedMergeTreeRestartingThread): Execution took 57203 ms.
2024.08.05 23:13:22.054136 [ 137 ] {} <Trace> oximeter.version (ReplicatedMergeTreeRestartingThread): Execution took 2038609 ms.
2024.08.05 23:14:22.057628 [ 137 ] {} <Trace> oximeter.version (ReplicatedMergeTreeRestartingThread): Execution took 57903 ms.
```

The full clickhouse and keeper logs are attached, but those are the relevant bits we noticed. The Execution time seems to correlate directly with how long before retries we wait. There is a line `Execution took 330018 ms` before the first `retry_count` line shows up, which correlates with how long we waited to see that line. You can also see the large gaps between the `retry_count` lines and how they occur right after the a similarly timestamped `Execution took <_ms>` line. They correlate directly.

We don't believe this has anything to do with the choice of client, because all of these retry and execution operations are occurring within clickhouse itself, and we have reproduced with both our rust HTTP client and `curl`.

We believe you should be able to reproduce this without running our tests, but instead by spinning up a 2 node clickhouse cluster and a keeper cluster configured with a database using replicated tables and distributed tables pointing to those replicated tables. And then you just stop enough keeper nodes to break quorum, and immediately try to insert. You can try to run our omicron test as well, by checking out the [repo](https://github.com/oxidecomputer/omicron/), [installing prerequisites](https://github.com/oxidecomputer/omicron/blob/main/docs/how-to-run-simulated.adoc#installing-prerequisites) and running the test: `cargo nextest run -p oximeter-db test_cluster --nocapture`. However, you may run into problems that are hard to debug asynchronously, especially if you are new to rust.

Now, onto your questions!

> Some questions:
> 
> * Which table is being inserted to? The code just says `insert_samples` but I see multiple tables, some Replicated, some Distributed, and those are completely different code paths.

Since I filed this issue the test has been merged. The minimum set of tables as used by the test exist in [db-init-1.sql](https://github.com/oxidecomputer/omicron/blob/main/oximeter/db/schema/replicated/db-init-1.sql).

In particular, the failing insert is to the *distributed* table, `oximeter.fields_i64`. I created a file that we used with curl for the particular insert query, reproduced below:

```
 omicron git:(clickhouse-67087) ✗ cat ~/clickward/insert_fields.sql
INSERT INTO oximeter.fields_i64 FORMAT JSONEachRow {"timeseries_name":"virtual_machine:cpu_busy","timeseries_key":2233331266580998121,"field_name":"cpu_id","field_value":0}{"timeseries_name":"virtual_machine:cpu_busy","timeseries_key":17747162226569891725,"field_name":"cpu_id","field_value":1}
```

I put up a [Draft PR](https://github.com/oxidecomputer/omicron/pull/6228) with the curl insert that triggers the delayed retries on [line 350 of integration_test.rs](https://github.com/oxidecomputer/omicron/pull/6228/files#diff-47b7e4344dcb98910f6648aa767b163bdcccd65e1cbef416098e224ad6509835R350).


> * What are the settings used on the query?
> 
The settings used on the query are `output_format_json_quote_64bit_integers=0` and `wait_end_of_query=1` as shown in the [previous link](https://github.com/oxidecomputer/omicron/pull/6228/files#diff-47b7e4344dcb98910f6648aa767b163bdcccd65e1cbef416098e224ad6509835R350) to the curl command in the test. The file used with the curl command is exactly as I printed out above.

> Some recommendations:
> 
> * Everything is much easier on CH side if you reproduce it with a simple HTTP request (such a curl command). It removes the need to validate the client.
Thank you for the recommendation. I did just that and it seemed to have the same result. It was easiest to automate and get similar timing by launching the curl command from the test itself.


> * Please share CH error messages, specially what you get when you receive a timeout.

I've attached the entire logs, and what seemed a particularly useful grep above.

> * Check CH logs for the operation. For replicated tables, CH is setup by default to do retries (settings `insert_keeper_max_retries`, `insert_keeper_retry_initial_backoff_ms`, `insert_keeper_retry_max_backoff_ms`) when keeper has issues. You can filter by the query_id in `/tmp/integration_test-c7b7a2d201a75a69-test_cluster.5132.1-oximeter-clickward-test/deployment/clickhouse-1/logs/clickhouse.log`.

Thanks, these settings are the defaults as you should see in the attached logs. Note that for this run of the test with curl I did not wait for the full 20 retries.

[clickhouse-67087-logs-and-config.tar.gz](https://github.com/user-attachments/files/16503677/clickhouse-67087-logs-and-config.tar.gz)

**Comment by Algunenano** [comment]
It seems quite a coincidence, but it looks similar to https://github.com/ClickHouse/ClickHouse/issues/67302 but I need to confirm. It's not expected that the retries wait for the restarting thread, and certainly not for `Execution took 1770094` ms to then wait for the set time.

**Comment by andrewjstone** [comment]
Ah, it does seem similar to #67302. Thanks for looking into that.

We also weren't sure the restarting thread wasn't more than a coincidence, or symptom of a similar issue. It was just the only other thing in the log that stood out.

**Comment by andrewjstone** [comment]
> Ah, it does seem similar to #67302. Thanks for looking into that.
> 
> We also weren't sure the restarting thread wasn't more than a coincidence, or symptom of a similar issue. It was just the only other thing in the log that stood out.

Will do when I get a chance. Thank you @Algunenano!
