### ISSUE TITLE
[Suggestion] Use git rebase to keep git log clean

### ISSUE THREAD

**Issue by xleoken** [ClickHouse/ClickHouse#67088]
This git log is not clear for developers compared to other projects, developers just need to know the submission history and do not need to expose any merge information.

![image](https://github.com/user-attachments/assets/0b8c4a2c-a0a3-4a45-8406-23e3e7517b64)

We can use `squash and merge` or `rebase and merge`  to merge the pull request.

![326248747-88fcda26-5700-4d27-b80d-56ba20ce37aa](https://github.com/user-attachments/assets/9a9d1216-fbfb-4aae-b004-8852bb8c57e7)

**Comment by xleoken** [comment]
hi @alexey-milovidov, what do you think?

**Comment by canhld94** [comment]
I believe it was discussed long time ago and the conclusion was keeping `git log` clean is not a priority.

**Comment by amosbird** [comment]
`git log --first-parent --oneline`

**Comment by alexey-milovidov** [comment]
We prefer not to use `git rebase` or `squash` for several reasons:

The local history of modifications is lost.

When you do `rebase`, the hashes of commits change, and it is no longer easy to find commits in your development branches by their hash.

When you do `rebase`, the hashes of commits change, and if you do it differently in more than one branch and then merge them, identical commits will appear duplicated.

When you search across branches, you will find identical commits with different hashes.

Merging and conflict resolution becomes more difficult and error-prone. There is a higher chance of losing changes accidentally.

When you do rebase or squash, it is a history rewrite, and you have to use the `--force` flag. But using this flag always feels nervous, and it is an advanced usage of git.

If you do squash, the number of commits in the repository is less, and the history is less detailed, and may not represent your work if large features appear in a single commit.

Git is naturally designed for branches and merges, and using rebase or squash kind of defeats its purpose.

Our automated tools, such as synchronization of private and public repositories, cannot automatically resolve rebases and force pushes while it works with merges.

The proposed motivation of `git rebase` or `squash` is to have a neat linear history, but we don't care about a neat linear history at all. We are not fanatics of git - we use it as a tool, which we don't like or dislike, we just use git and tolerate it.

**Comment by xleoken** [comment]
> We prefer not to use `git rebase` or `squash` for several reasons:
> 
> The local history of modifications is lost.
> 
> When you do `rebase`, the hashes of commits change, and it is no longer easy to find commits in your development branches by their hash.
> 
> When you do `rebase`, the hashes of commits change, and if you do it differently in more than one branch and then merge them, identical commits will appear duplicated.
> 
> When you search across branches, you will find identical commits with different hashes.
> 
> Merging and conflict resolution becomes more difficult and error-prone. There is a higher chance of losing changes accidentally.
> 
> When you do rebase or squash, it is a history rewrite, and you have to use the `--force` flag. But using this flag always feels nervous, and it is an advanced usage of git.
> 
> If you do squash, the number of commits in the repository is less, and the history is less detailed, and may not represent your work if large features appear in a single commit.
> 
> Git is naturally designed for branches and merges, and using rebase or squash kind of defeats its purpose.
> 
> Our automated tools, such as synchronization of private and public repositories, cannot automatically resolve rebases and force pushes while it works with merges.
> 
> The proposed motivation of `git rebase` or `squash` is to have a neat linear history, but we don't care about a neat linear history at all. We are not fanatics of git - we use it as a tool, which we don't like or dislike, we just use git and tolerate it.

ok, i see.
