### ISSUE TITLE
"ClickHouse encountered an unexpected restart."

### ISSUE THREAD

**Issue by hert525** [ClickHouse/ClickHouse#67095]
clickhouse-version  23.12
After upgrading ClickHouse to version 23.12, it has restarted multiple times. Attached are the error logs from today's restart

[clickhouse-server.err.log.zip](https://github.com/user-attachments/files/16372180/clickhouse-server.err.log.zip)

"I would like to confirm if upgrading to the support version will resolve this issue."

**Comment by Algunenano** [comment]
> "I would like to confirm if upgrading to the support version will resolve this issue."

No guarantees, but if you update to 24.6 and it fails feel free to blame it, share a reproducer and I'll investigate and fix it.
