### ISSUE TITLE
"Main PID: 22599 (code=exited, status=203/EXEC)"Clickhouse HA Clustering using clickhouse keeper for my 3 ubuntu servers

### ISSUE THREAD

**Issue by Saif2406** [ClickHouse/ClickHouse#67094]
Gama Security

IPSP Integration

I have tried the following solutions: https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper#summary

**Installation type**

wget https://github.com/ClickHouse/ClickHouse/releases/download/v24.6.2.17-stable/clickhouse-client_24.6.2.17_amd64.deb

Source of the ClickHouse

sudo nano /etc/systemd/system/clickhouse-server.service

[Unit]
Description=ClickHouse Server (analytic DBMS for big data)
Documentation=https://clickhouse.com
After=network.target

[Service]
Type=simple
User=clickhouse
Group=clickhouse
ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RuntimeDirectory=clickhouse-server
RuntimeDirectoryMode=0755
LimitNOFILE=1048576
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target

Expected result

SHOW clusters;
cluster───────┐
│ cluster_2S_1R │

The actual result

Loaded: loaded (/etc/systemd/system/clickhouse-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-07-24 10:34:17 UTC; 59s ago
       Docs: https://clickhouse.com
    Process: 22599 ExecStart=/usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml --pid-file=/run/clickhouse-server/clickhouse-server.pid (code=exited>
   Main PID: 22599 (code=exited, status=203/EXEC)

![WhatsApp Image 2024-07-24 at 14 20 13](https://github.com/user-attachments/assets/1bb367ae-79d8-4c1c-9f0b-c2cc75a5c893)

![WhatsApp Image 2024-07-24 at 14 19 02](https://github.com/user-attachments/assets/5775a300-64e4-4220-bfcc-3844450d40cf)

![image](https://github.com/user-attachments/assets/80268a26-d4e5-41a0-8941-8d21b2f6e64b)

If somebody has the documentation to setup clickhouse DB cluster kindly share with me i need a help from clickhouse community

**Comment by Algunenano** [comment]
Review your config file `/etc/clickhouse-server/config.xml` and the logs generated by the process to look for the error.

**Comment by Saif2406** [comment]
@Algunenano Log file has been created the same path as config.xml kindly find the attached image

![image](https://github.com/user-attachments/assets/0443e8c3-4504-4a7c-ac2c-d18accc0368f)

After pushing this command "sudo systemctl status clickhouse-server" for a logs

![image](https://github.com/user-attachments/assets/ae699e1a-e26b-404e-9184-2b144591b6be)

**Comment by Algunenano** [comment]
Please note how a screenshot of `ls` is worthless to any investigation. You should read clickhouse-server.log and check for errors.

**Comment by Saif2406** [comment]
my bad man i thought you were asking for file is there or not 

Below attachment showing the logs i don't find any error in the logs

![image](https://github.com/user-attachments/assets/26e41cbe-2e5e-4739-86f3-99fef2bd1912)

**Comment by Algunenano** [comment]
Please stop pasting screenshots of partial data, they are almost worthless.

You should do 2 things:
* Read, **youself**, the clickhouse-server.log and look for `<Error>` and `<Fatal>` tags to understand what's going on.
* Share the full log.

BTW, signal 15 is normal shutdown not an error. So I would check what systemctl is doing or run manully without a service to verify

**Comment by den-crane** [comment]
your  /etc/systemd/system/clickhouse-server.service is incorrect. Remove it (`rm  /etc/systemd/system/clickhouse-server.service` ) There is correect `/lib/systemd/system/clickhouse-server.service`

Your `clickhouse-server.service ` is missing CapabilityBoundingSet, AmbientCapabilities

https://github.com/ClickHouse/ClickHouse/blob/master/packages/clickhouse-server.service#L38-L39
