### ISSUE TITLE
what should I do?  when the log exeeced 2^32: ls /clickhouse/tables/behaviordev-3/local_user_sequence_event_common/log [log-2147483638, log-2147483639, log-2147483640, log-2147483641, log-2147483642, log-2147483643, log-2147483644, log-2147483645, log-2147483646, log-2147483647]

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#67100]
### Question

Code: 244, e.displayText() = DB::Exception: Unexpected logical error while adding block 310544 with ID 'fea8fcfc3011db74a4cc02b5c2530e92_17367404135463801809_16930384392499062634': Node exists, path /clickhouse/tables/behaviordev-4/local_user_sequence_event_common/log/log- (version 20.8.11.17 (official build))

**Comment by Sallery-X** [comment]
Look like limit by zookeeper

**Comment by Algunenano** [comment]
20.8 has been out of support for several years. Please update to a [supported release](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md)
