### ISSUE TITLE
create MATERIALIZED VIEW failed

### ISSUE THREAD

**Issue by caoyang10** [ClickHouse/ClickHouse#67112]
reproduce:
CREATE TABLE a
(
    a_id String
)
ENGINE = MergeTree
PARTITION BY tuple() order by tuple();

CREATE TABLE b
(
    b_id AggregateFunction(uniq, Nullable(String))
)
ENGINE = AggregatingMergeTree
PARTITION BY tuple() order by tuple();

CREATE MATERIALIZED VIEW mv TO b
(
    b_id AggregateFunction(uniq, Nullable(String))
) AS
SELECT
    uniqState(if(a_id != '', a_id, NULL)) as b_id
FROM a;

Received exception:
Code: 70. DB::Exception: Conversion from AggregateFunction(uniq, String) to AggregateFunction(uniq, Nullable(String)) is not supported: while converting source column b_id to destination column b_id. (CANNOT_CONVERT_TYPE)

It can work on earlier version like 23.11.x

**Comment by den-crane** [comment]
related to experimental analyzer  https://fiddle.clickhouse.com/143a8dac-c2be-41b8-8ef9-64090ba0a171

you can disable analyzer 

```
cat /etc/clickhouse-server/users.d/allow_experimental_analyzer.xml
<?xml version="1.0" ?>
<clickhouse>
    <profiles>
        <default>
            <allow_experimental_analyzer>0</allow_experimental_analyzer>
        </default>
    </profiles>
</clickhouse>
```

or use `uniqState(toNullable(if(a_id != '', a_id, NULL))) as b_id`

BTW, Nullable has little sense here, you can use `uniqStateIf(a_id, a_id != '')`

**Comment by caoyang10** [comment]
> related to experimental analyzer https://fiddle.clickhouse.com/143a8dac-c2be-41b8-8ef9-64090ba0a171
> 
> you can disable analyzer
> 
> ```
> cat /etc/clickhouse-server/users.d/allow_experimental_analyzer.xml
> <?xml version="1.0" ?>
> <clickhouse>
>     <profiles>
>         <default>
>             <allow_experimental_analyzer>0</allow_experimental_analyzer>
>         </default>
>     </profiles>
> </clickhouse>
> ```
> 
> or use `uniqState(toNullable(if(a_id != '', a_id, NULL))) as b_id`
> 
> BTW, Nullable has little sense here, you can use `uniqStateIf(a_id, a_id != '')`
uniqStateIf(a_id, a_id != '') is not work if not setting allow_experimental_analyzer=0
I'm still a little confused that:
SELECT toTypeName(if(a_id != '', a_id, NULL))
FROM a
it return **Nullable(String)**
why should I use **toNullable** function to convert **Nullable(String)** type ?

**Comment by den-crane** [comment]
@caoyang10 

Just use 

```
cat /etc/clickhouse-server/users.d/allow_experimental_analyzer.xml
<?xml version="1.0" ?>
<clickhouse>
    <profiles>
        <default>
            <allow_experimental_analyzer>0</allow_experimental_analyzer>
        </default>
    </profiles>
</clickhouse>
```

------

>why should I use toNullable function 
see https://fiddle.clickhouse.com/ecf4b482-0495-4fe6-8469-1c42b9e6ed21

**Comment by den-crane** [comment]
@alexey-milovidov https://fiddle.clickhouse.com/143a8dac-c2be-41b8-8ef9-64090ba0a171

**Comment by caoyang10** [comment]
yeah, set allow_experimental_analyzer = 0 can solve my problem.
But I think whatever allow_experimental_analyzer is,
if(a_id != '', a_id, NULL) return Nullable(String) type,
uniqState(if(a_id != '', a_id, NULL)) should return AggregateFunction(uniq, Nullable(String)) type, but not AggregateFunction(uniq, String)
that makes me confused. @den-crane @alexey-milovidov 
https://fiddle.clickhouse.com/e85eafcf-1721-4e7f-a90f-4116937c8647

**Comment by KochetovNicolai** [comment]
This is because of `optimize_rewrite_aggregate_function_with_if` optimization.
```
SELECT toTypeName(uniqStateIf(toNullable(number), number > 0))
FROM numbers(2)
SETTINGS allow_experimental_analyzer = 0

Query id: 4ca82c5c-30f1-4b6a-8f8f-075fa73f7b9f

   ┌─toTypeName(uniqStateIf(toNullable(number), greater(number, 0)))─┐
1. │ AggregateFunction(uniq, UInt64)                                 │
   └─────────────────────────────────────────────────────────────────┘


SELECT toTypeName(uniqState(toNullable(number)))
FROM numbers(2)
SETTINGS allow_experimental_analyzer = 0

Query id: 4716ac8d-cf57-465f-844d-930e2fbcc937

   ┌─toTypeName(uniqState(toNullable(number)))─┐
1. │ AggregateFunction(uniq, Nullable(UInt64)) │
   └───────────────────────────────────────────┘

```

It is strange that `If` changes the return type. But I suppose it is too late to fix it: it would be backward incompatible. (Also, we can't cast `AggregateFunction(uniq, UInt64)` to `AggregateFunction(uniq, Nullable(UInt64))` ).

I am about to disable this case for `uniq`.

**Comment by den-crane** [comment]
So it was always like this for all uniq functions with -if combinator. 
I would fix it with a setting for backward compatibility (like `uniq_functions_if_combinator_return_nullalble=true`) because it's very inconsistent now.
