### ISSUE TITLE
problem with default http-client in jdbc-driver

### ISSUE THREAD

**Issue by vpvha** [ClickHouse/ClickHouse#67128]
Clickhouse JDBC Driver 0.6.1.

We migrate data from Greenplum to Clickhouse by PXF (jdbc clickhouse 0.6.1 with default http-client)

**How to reproduce**

This error appears, when we try to insert a lot of data from Greenplum to CH by External table (PXF) 390 millions rows. 
There are about Greenplum segments 190+ and about 190+ connections.

This error was in pxf-logs from Greenplum segments, but no errors from Clickhouse logs.

**Error writing request body to server\n\njava.sql.BatchUpdateException: Error writing request body to server\n\tat com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:107) ~[clickhouse-jdbc-0.6.1-http.jar:clickhouse-jdbc 0.6.1 (revision: 5be856e)]\n\tat com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:154) ~[clickhouse-jdbc-0.6.1-http.jar:clickhouse-jdbc 0.6.1 (revision: 5be856e)]\n\tat com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85) ~[clickhouse-jdbc-0.6.1-http.jar:clickhouse-jdbc 0.6.1 (revision: 5be856e)]\n\tat com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:770) ~[clickhouse-jdbc-0.6.1-http.jar:clickhouse-jdbc 0.6.1 (revision: 5be856e)]\n\tat com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.5.jar!/:?]\n\tat**

Then we try to use apache-http client and there is`nt some errors and insert finished correctly.

**Comment by Algunenano** [comment]
Could please report issues with the jbdc-driver to [its repository](https://github.com/ClickHouse/clickhouse-java)?
