### ISSUE TITLE
Oracle ODBC Timeout Expired | clickhouse-odbc-bridge and ODBC driver 21.15

### ISSUE THREAD

**Issue by MarcoTach** [ClickHouse/ClickHouse#67132]
### Question

Trying to "select col1 from odbc('DSN=Oracle;UID=admin;PWD=secret', 'admin', 'test1')" produces this error:

<Error> ODBCConnection: ODBC query failed with error: contrib/nanodbc/nanodbc/nanodbc.cpp:4813: HYT0: [Oracle][ODBC]Timeout expired.

Logs of the clickhouse-odbc-bridge:

2024.07.25 16:41:33.436585 [ 3432 ] {} <Trace> ODBCRequestHandlerFactory-factory: Request URI: /columns_info?use_connection_pooling=1&version=1&connection_string=DSN%3DOracle%3BUID%3Dadmin%3BPWD%3Dsecret&schema=admin&table=test1&external_table_functions_use_nulls=1
2024.07.25 16:41:33.436653 [ 3432 ] {} <Trace> ODBCColumnsInfoHandler: Request URI: /columns_info?use_connection_pooling=1&version=1&connection_string=DSN%3DOracle%3BUID%3Dadmin%3BPWD%3Dsecret&schema=admin&table=test1&external_table_functions_use_nulls=1
2024.07.25 16:41:33.436669 [ 3432 ] {} <Trace> ODBCColumnsInfoHandler: Got connection str 'DSN=Oracle;UID=admin;PWD=secret'
2024.07.25 16:41:33.436986 [ 3432 ] {} <Error> ODBCConnection: ODBC query failed with error: contrib/nanodbc/nanodbc/nanodbc.cpp:4813: HYT0: [Oracle][ODBC]Timeout expired.                               , state: HYT0, native code: 0
2024.07.25 16:41:33.437125 [ 3432 ] {} <Warning> ODBCColumnsInfoHandler: Error getting columns from ODBC 'std::exception. Code: 1001, type: nanodbc::database_error, e.what() = contrib/nanodbc/nanodbc/nanodbc.cpp:4813: HYT0: [Oracle][ODBC]Timeout expired.                                (version 24.6.2.17 (official build))'
2024.07.25 16:41:33.437167 [ 3432 ] {} <Error> ODBCColumnsInfoHandler: std::exception. Code: 1001, type: nanodbc::database_error, e.what() = contrib/nanodbc/nanodbc/nanodbc.cpp:4813: HYT0: [Oracle][ODBC]Timeout expired.                               , Stack trace (when copying this message, always include the lines below):

0. ./build_docker/./contrib/nanodbc/nanodbc/nanodbc.cpp:483: nanodbc::database_error::database_error(void*, short, String const&) @ 0x0000000005bfeb2b
1. ./build_docker/./contrib/nanodbc/nanodbc/nanodbc.cpp:0: nanodbc::catalog::find_tables(String const&, String const&, String const&, String const&) @ 0x0000000005c011f9
2. ./contrib/llvm-project/libcxx/include/string:1499: nanodbc::catalog::columns std::__function::__policy_invoker<nanodbc::catalog::columns (nanodbc::connection&)>::__call_impl<std::__function::__default_alloc_func<DB::ODBCColumnsInfoHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&)::$_2, nanodbc::catalog::columns (nanodbc::connection&)>>(std::__function::__policy_storage const*, nanodbc::connection&) @ 0x00000000037aee78
3. ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:701: DB::ODBCColumnsInfoHandler::handleRequest(DB::HTTPServerRequest&, DB::HTTPServerResponse&, StrongTypedef<unsigned long, ProfileEvents::EventTag> const&) @ 0x00000000037a6bb6
4. ./base/poco/Foundation/include/Poco/AutoPtr.h:205: DB::HTTPServerConnection::run() @ 0x00000000059ef4a3
5. ./build_docker/./base/poco/Net/src/TCPServerConnection.cpp:57: Poco::Net::TCPServerConnection::start() @ 0x0000000007b388c7
6. ./contrib/llvm-project/libcxx/include/__memory/unique_ptr.h:48: Poco::Net::TCPServerDispatcher::run() @ 0x0000000007b38d59
7. ./build_docker/./base/poco/Foundation/src/ThreadPool.cpp:219: Poco::PooledThread::run() @ 0x0000000007b079c1
8. ./base/poco/Foundation/include/Poco/SharedPtr.h:231: Poco::ThreadImpl::runnableEntry(void*) @ 0x0000000007b0619d
9. ? @ 0x000070eb89e94ac3
10. ? @ 0x000070eb89f26850
 (version 24.6.2.17 (official build))

etc/odbcinst.ini:

[Oracle 21 ODBC driver]
Description     = Oracle ODBC driver for Oracle 21
Driver          = /lib/libsqora.so.21.1
Setup           =
FileUsage       =
CPTimeout       = 30
CPReuse         =

etc/odbc.ini:

[Oracle]
Driver = Oracle 21 ODBC driver
UserID=admin
Password=secret
ConnectionTimeout = 60
QueryTimeout = 60
ServerName = (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=x.x.x.x)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=freepdb1)))
AggregateSQLType = FLOAT
Application Attributes = T
Attributes = W
BatchAutocommitMode = IfAllSuccessful
BindAsFLOAT = F
CacheBufferSize = 20
ConnectionTimeout = 30
CloseCursor = F
DisableDPM = F
DisableMTS = T
DisableRULEHint = T
EXECSchemaOpt =
EXECSyntax = T
Failover = T

I can use the odbc source with both isql and sqlplus.

**Comment by MarcoTach** [comment]
@den-crane can you help me?

**Comment by thegausiantheory** [comment]
Hey Marco did you manage to solve this issue? I am getting the same error.

**Comment by m-mit** [comment]
This happens to me too.

**Comment by endraceni** [comment]
@MarcoTach @m-mit @thegausiantheory hi, I am having the same error, did any of you solve it?
