### ISSUE TITLE
CI: A way for PR to run tests but prevent merging

### ISSUE THREAD

**Issue by al13n321** [ClickHouse/ClickHouse#67155]
To prevent things like https://github.com/ClickHouse/ClickHouse/pull/67152 . Or is there already a way?

If PR adds substring "@nocommit" to the code, refuse to merge the PR, but still run tests (i.e. it can't just be in the style check). 

I guess the implementation is to add a "late style check" check that depends on all the other checks except CheckReadyForMerge. Make style_check.py take a boolean parameter for whether it's the late or the early check, and do different subsets of checks depending on that. Add util/check-style/check_nocommit.sh.

**Comment by nickitat** [comment]
Looks like creating a draft pr should do the trick?

**Comment by al13n321** [comment]
Yeah, maybe I should just have a rule to look at the code before un-drafting.

(In this case the PR was a draft for 2 different reasons. When un-drafting I was thinking of one of these reasons and forgot about the other.)
