### ISSUE TITLE
Tests for Kafka cannot run due to port conflict

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67162]
`ERROR: for schema-registry-auth  Cannot start service schema-registry-auth: driver failed programming external connectivity on endpoint roottestkafkabadmessages_schema-registry-auth_1 (e45ab19f6776ab82e5156733b5104764c12365ca31d859b262b55c012e7b3a84): Bind for 0.0.0.0:44355 failed: port is already allocated`

https://s3.amazonaws.com/clickhouse-test-reports/0/3f598f6825f9ad7bc437f2f40790eb33b45f9717/integration_tests__release__[4_4].html

**Comment by antaljanosbenjamin** [comment]
The issue is the same as before: there is no way to reliably get a free port. Sometimes they will collide and this happens.

**Comment by alexey-milovidov** [comment]
Everything about Kafka has failed: https://s3.amazonaws.com/clickhouse-test-reports/66506/4bc79f2ce1ba4cf693681df8f3d189678dba9d7b/integration_tests__asan__old_analyzer__[6_6].html
