### ISSUE TITLE
How to use the g4 file provided under antlr to generate a Java parser? 

### ISSUE THREAD

**Issue by openai0229** [ClickHouse/ClickHouse#67183]
### Company or project name

https://github.com/chat2db/Chat2DB

### Question

I modified the following part
![image](https://github.com/user-attachments/assets/e32efc5e-23ab-45cc-a7ba-fec32ffb6b9a)
![image](https://github.com/user-attachments/assets/97711c3c-8712-4dce-8102-4269e7ea6f89)
But there are still problems, the problems are as follows
![image](https://github.com/user-attachments/assets/7bb7b73d-2e27-45e0-b516-109791f7d26a)

**Comment by Algunenano** [comment]
The g4 file is unofficial and not used by the database. It's there as an example and just in case somebody wants to use and support it.
