### ISSUE TITLE
Inserting into different tables (with identical table structures) results in varying amounts of data read and memory usage

### ISSUE THREAD

**Issue by Dong-GuoSheng** [ClickHouse/ClickHouse#67180]
### Question

clickhouse-server 22.8.4.7

Same table structure, same data file, different memory usage and number of rows read reported during insert in (-- send_rog-level=debug).Original file 85000 lines。
相同的表结构，相同的数据文件，insert into时（--send_log_level=trace）报告使用的内存和读取的行数不同。原始文件85000行。

The detailed log：
详见日志：

[root@hdp49 ]# clickhouse-client  --send_logs_level=debug --input_format_allow_errors_num=100000 --input_format_allow_errors_ratio=0.8 --host=10.1.13.31 --port 19000 --user default --password '' --query="INSERT INTO test.XXX_local FORMAT TabSeparated" < /tmp/KAFKA-JZ_RESOURCE_MEE-XXX-20240726-1721978041081-22-8815166523004652.bcp
[hdp31] 2024.07.26 16:53:13.307853 [ 6141 ] {6e384ec9-7cb4-41af-a19c-2628e0f0631c} <Debug> executeQuery: (from 10.1.13.49:58744) INSERT INTO test.XXX_local FORMAT TabSeparated (stage: Complete)
[hdp31] 2024.07.26 16:53:14.919811 [ 6141 ] {6e384ec9-7cb4-41af-a19c-2628e0f0631c} <Debug> DiskLocal: Reserving 274.76 MiB on disk `data6`, having unreserved 2.07 TiB.
[hdp31] 2024.07.26 16:53:17.546891 [ 6141 ] {6e384ec9-7cb4-41af-a19c-2628e0f0631c} <Debug> DiskLocal: Reserving 256.14 MiB on disk `data10`, having unreserved 2.03 TiB.
[hdp31] 2024.07.26 16:53:18.737472 [ 6141 ] {6e384ec9-7cb4-41af-a19c-2628e0f0631c} <Debug> DiskLocal: Reserving 2.74 MiB on disk `data9`, having unreserved 2.22 TiB.
[hdp31] 2024.07.26 16:53:18.750338 [ 6141 ] {6e384ec9-7cb4-41af-a19c-2628e0f0631c} <Information> executeQuery: Read 850000 rows, 533.64 MiB in 5.442433043 sec., 156180 rows/sec., 98.05 MiB/sec.
[hdp31] 2024.07.26 16:53:18.750688 [ 6141 ] {6e384ec9-7cb4-41af-a19c-2628e0f0631c} <Debug> MemoryTracker: Peak memory usage (for query): 747.94 MiB.
[hdp31] 2024.07.26 16:53:18.751774 [ 6141 ] {6e384ec9-7cb4-41af-a19c-2628e0f0631c} <Debug> TCPHandler: Processed in 5.444125722 sec.

[root@hdp49 ]# clickhouse-client  --send_logs_level=debug --input_format_allow_errors_num=100000 --input_format_allow_errors_ratio=0.8 --host=10.1.13.31 --port 19000 --user default --password '' --query="INSERT INTO jz.XXX_local FORMAT TabSeparated" < /tmp/KAFKA-JZ_RESOURCE_MEE-XXX-20240726-1721978041081-22-8815166523004652.bcp
[hdp31] 2024.07.26 16:53:37.218155 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> executeQuery: (from 10.1.13.49:59126) INSERT INTO jz.XXX_local FORMAT TabSeparated (stage: Complete)
[hdp31] 2024.07.26 16:53:37.219276 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "notEmpty(geohash5)" moved to PREWHERE
[hdp31] 2024.07.26 16:53:37.219924 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "notEmpty(msisdn_1)" moved to PREWHERE
[hdp31] 2024.07.26 16:53:37.222535 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(geohash6 != '') AND (geohash6 IS NOT NULL)" moved to PREWHERE
[hdp31] 2024.07.26 16:53:38.874103 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 274.76 MiB on disk `data9`, having unreserved 2.22 TiB.
[hdp31] 2024.07.26 16:53:41.441319 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 256.14 MiB on disk `data7`, having unreserved 1.50 TiB.
[hdp31] 2024.07.26 16:53:43.458503 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> AggregatingTransform: Aggregated. 436423 to 415787 rows (from 80.00 MiB) in 0.469102874 sec. (930335.379 rows/sec., 170.53 MiB/sec.)
[hdp31] 2024.07.26 16:53:52.299407 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> AggregatingTransform: Aggregated. 436808 to 28498 rows (from 20.41 MiB) in 8.396804386 sec. (52020.743 rows/sec., 2.43 MiB/sec.)
[hdp31] 2024.07.26 16:53:52.675145 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 274.76 MiB on disk `data10`, having unreserved 2.03 TiB.
[hdp31] 2024.07.26 16:53:54.148655 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 91.96 MiB on disk `data8`, having unreserved 2.52 TiB.
[hdp31] 2024.07.26 16:53:54.391904 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 92.15 MiB on disk `data7`, having unreserved 1.50 TiB.
[hdp31] 2024.07.26 16:53:54.634470 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 90.64 MiB on disk `data6`, having unreserved 2.07 TiB.
[hdp31] 2024.07.26 16:53:54.882351 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 2.74 MiB on disk `data7`, having unreserved 1.50 TiB.
[hdp31] 2024.07.26 16:53:55.703688 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> AggregatingTransform: Aggregated. 407252 to 354137 rows (from 74.25 MiB) in 0.433981626 sec. (938408.392 rows/sec., 171.09 MiB/sec.)
[hdp31] 2024.07.26 16:53:58.854287 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> MemoryTracker: Current memory usage (for query): 2.03 GiB.
[hdp31] 2024.07.26 16:53:59.614627 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 420.91 MiB on disk `data6`, having unreserved 2.07 TiB.
[hdp31] 2024.07.26 16:54:08.126766 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> AggregatingTransform: Aggregated. 408887 to 60723 rows (from 19.11 MiB) in 7.89894389 sec. (51764.768 rows/sec., 2.42 MiB/sec.)
[hdp31] 2024.07.26 16:54:08.540312 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 256.14 MiB on disk `data7`, having unreserved 1.50 TiB.
[hdp31] 2024.07.26 16:54:09.860180 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 85.19 MiB on disk `default`, having unreserved 606.67 GiB.
[hdp31] 2024.07.26 16:54:10.087491 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 88.23 MiB on disk `data10`, having unreserved 2.03 TiB.
[hdp31] 2024.07.26 16:54:10.322108 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 82.72 MiB on disk `data9`, having unreserved 2.22 TiB.
[hdp31] 2024.07.26 16:54:10.564110 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> AggregatingTransform: Aggregated. 4305 to 4266 rows (from 814.11 KiB) in 0.009936125 sec. (433267.496 rows/sec., 80.01 MiB/sec.)
[hdp31] 2024.07.26 16:54:10.683525 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> AggregatingTransform: Aggregated. 4305 to 260 rows (from 206.00 KiB) in 0.087700082 sec. (49087.753 rows/sec., 2.29 MiB/sec.)
[hdp31] 2024.07.26 16:54:10.897565 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 19.35 MiB on disk `data10`, having unreserved 2.03 TiB.
[hdp31] 2024.07.26 16:54:11.809071 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 16.45 MiB on disk `data9`, having unreserved 2.22 TiB.
[hdp31] 2024.07.26 16:54:12.453870 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 19.27 MiB on disk `data8`, having unreserved 2.52 TiB.
[hdp31] 2024.07.26 16:54:12.946999 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 19.04 MiB on disk `data7`, having unreserved 1.50 TiB.
[hdp31] 2024.07.26 16:54:13.746681 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 21.29 MiB on disk `default`, having unreserved 606.66 GiB.
[hdp31] 2024.07.26 16:54:13.853884 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 3.04 MiB on disk `data10`, having unreserved 2.03 TiB.
[hdp31] 2024.07.26 16:54:14.036284 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 36.86 MiB on disk `data9`, having unreserved 2.22 TiB.
[hdp31] 2024.07.26 16:54:14.246900 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 2.74 MiB on disk `data8`, having unreserved 2.52 TiB.
[hdp31] 2024.07.26 16:54:14.264471 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 926.55 KiB on disk `data8`, having unreserved 2.52 TiB.
[hdp31] 2024.07.26 16:54:14.267460 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 927.30 KiB on disk `data7`, having unreserved 1.50 TiB.
[hdp31] 2024.07.26 16:54:14.270247 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> DiskLocal: Reserving 950.21 KiB on disk `data6`, having unreserved 2.07 TiB.
[hdp31] 2024.07.26 16:54:14.273658 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Information> executeQuery: Read 8500000 rows, 1.89 GiB in 37.055395572 sec., 229386 rows/sec., 52.31 MiB/sec.
[hdp31] 2024.07.26 16:54:14.277702 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> MemoryTracker: Peak memory usage (for query): 2.13 GiB.
[hdp31] 2024.07.26 16:54:14.277721 [ 35091 ] {1d5ae6c3-1caa-4961-a35d-7a8c2bc111de} <Debug> TCPHandler: Processed in 37.059763657 sec.

Table Structure：
表结构：
CREATE TABLE test.XXX_local
(
    `capture_time` Int64,
    `md_id` String,
 ……
    INDEX idx_geohash6_XXX geohash6 TYPE minmax GRANULARITY 4,
    INDEX idx_lac_ci_XXX lac_1 TYPE minmax GRANULARITY 4,
    INDEX XXX_msimsi_11 msimsi_1 TYPE SET(0) GRANULARITY 10,
    INDEX min_max_dt_XXX dt TYPE minmax GRANULARITY 8
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(toDateTime(capture_time))
PRIMARY KEY (x1, x2, x3, geohash6, geohash, aa1, aa2, aa3, aa4, aa5, aa6, dt, capture_time)
ORDER BY (x1, x2, x3,, geohash6, geohash, aa1, aa2, aa3, aa4, aa5, aa6, dt, capture_time)
TTL toDateTime(capture_time) + toIntervalDay(1095)
SETTINGS index_granularity = 8192, max_suspicious_broken_parts = 1000, max_suspicious_broken_parts_bytes = 102400000000000

**Comment by Algunenano** [comment]
22.8 is unsupported. Please verify a supported release
