### ISSUE TITLE
`test_executable_user_defined_function/test.py::test_executable_function_slow_python` is flaky

### ISSUE THREAD

**Issue by evillique** [ClickHouse/ClickHouse#67210]
Example: https://s3.amazonaws.com/clickhouse-test-reports/67154/47c2d8b9df4bb9894325b26da4ac0fbb9f4564e9/integration_tests__aarch64__[4_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel0_0.log

CI DB: [link](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICd0ZXN0X2V4ZWN1dGFibGVfZnVuY3Rpb25fc2xvd19weXRob24nIEFTIG5hbWVfc3Vic3RyLAogICAgOTAgQVMgaW50ZXJ2YWxfZGF5cywKICAgICgnU3RhdGVsZXNzIHRlc3RzIChhc2FuKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MpJywgJ1N0YXRlbGVzcyB0ZXN0cyAoYWRkcmVzcywgYWN0aW9ucyknKSBBUyBiYWNrcG9ydF9hbmRfcmVsZWFzZV9zcGVjaWZpY19jaGVja3MKU0VMRUNUCiAgICB0b1N0YXJ0T2ZEYXkoY2hlY2tfc3RhcnRfdGltZSkgQVMgZCwKICAgIGNvdW50KCksCiAgICBncm91cFVuaXFBcnJheShwdWxsX3JlcXVlc3RfbnVtYmVyKSBBUyBwcnMsCiAgICBhbnkocmVwb3J0X3VybCkKRlJPTSBjaGVja3MKV0hFUkUgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAocHVsbF9yZXF1ZXN0X251bWJlciBOT1QgSU4gKAogICAgU0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIgQVMgcHJuCiAgICBGUk9NIGNoZWNrcwogICAgV0hFUkUgKHBybiAhPSAwKSBBTkQgKChub3coKSAtIHRvSW50ZXJ2YWxEYXkoaW50ZXJ2YWxfZGF5cykpIDw9IGNoZWNrX3N0YXJ0X3RpbWUpIEFORCAoY2hlY2tfbmFtZSBJTiAoYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzKSkKKSkgQU5EIChwb3NpdGlvbih0ZXN0X25hbWUsIG5hbWVfc3Vic3RyKSA+IDApIEFORCAodGVzdF9zdGF0dXMgSU4gKCdGQUlMJywgJ0VSUk9SJywgJ0ZMQUtZJykpCkdST1VQIEJZIGQKT1JERVIgQlkgZCBERVNDCg==)

**Comment by alexey-milovidov** [comment]
It is still failing! https://s3.amazonaws.com/clickhouse-test-reports/0/6ea1412f957cbe9519324593aa17d8f9e5021d3e/integration_tests__aarch64__[5_6].html

**Comment by nickitat** [comment]
I bet it should be the same problem as in #67002

**Comment by nickitat** [comment]
no repro-s since Aug 9th
