### ISSUE TITLE
Group by help in query

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#6726]
Hi 

Query:  I have three different records as mentioned below in the table 

Status Code: 0,1,2

In the result i want to pick 1,
if 1 is not present pick 0,
at last if 0 is not present pick 2.

Example Query :

SELECT status_code as lstatus,max(c.id) as locid,concat(max(c.id),'_',topic) as uniqueId, lower(c.domain) as domain,max(company_name) as company,state_province_code as state, city_name as city , topic topic, max(rank) intensity, max(cmsa) as msa , CONCAT(max(naics_dec), '-', max(naics4_dec)) AS industry, max(id) locationid ,max(status_code) locationstatus, max(street_address1) as address, max(postal_code) as zip, country_code as country,max(created_date) as intentdate from company_****** c where 1=1  AND c.country_code = 'US' AND topic IN ('Cloud','Computing') AND rank > 0 AND status_code IN (1,2)  GROUP BY domain,country,state,city,status_code,topic  ORDER  BY intensity DESC, domain, company  LIMIT  10 offset 0  

The above query will always return 2 as we have used max in the select, and have done a group  by on status code.

Is there any best way to handle this in query. if yes please provide an example.

Thanks !

**Comment by den-crane** [comment]
```
create table XX (A Int64, B String, Status UInt8) Engine = Memory;
insert into XX values(1, 'Status=1', 1), (2, 'Status=0', 0), (2, 'Status=2', 2), (3, 'Status=2', 2);
select * from XX
┌─A─┬─B────────┬─Status─┐
│ 1 │ Status=1 │      1 │
│ 2 │ Status=0 │      0 │
│ 2 │ Status=2 │      2 │
│ 3 │ Status=2 │      2 │
└───┴──────────┴────────┘

select * from XX order by A, multiIf(Status=1,0,Status=0,1,Status) limit 1 by A
┌─A─┬─B────────┬─Status─┐
│ 1 │ Status=1 │      1 │
│ 2 │ Status=0 │      0 │
│ 3 │ Status=2 │      2 │
└───┴──────────┴────────┘
```
