### ISSUE TITLE
Test `02435_rollback_cancelled_queries` has failed

### ISSUE THREAD

**Issue by thevar1able** [ClickHouse/ClickHouse#67271]
https://s3.amazonaws.com/clickhouse-test-reports/0/ac514a5103823571168ce21c387d7604c740ae58/stateless_tests__asan__[2_2].html
https://s3.amazonaws.com/clickhouse-test-reports/0/3c93091bd819059550be3290ce85257268575f41/stateless_tests__debug__s3_storage__[2_2].html
https://s3.amazonaws.com/clickhouse-test-reports/0/530ce95d623ec9f298979692be47aad78b0efc77/stateless_tests__tsan__s3_storage__[3_5].html
https://s3.amazonaws.com/clickhouse-test-reports/67174/f276be829bebd8e704e33565127034f3e258cc31/stateless_tests__tsan__[2_4].html

**Comment by nikitamikhaylov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/67137
