### ISSUE TITLE
A test `02490_benchmark_max_consecutive_errors` has failed.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67280]
https://s3.amazonaws.com/clickhouse-test-reports/67260/91a3fbc0f6d43d1fbec76f150bb3e44e75035141/stateless_tests__tsan__s3_storage__[2_4].html

CC @azat

**Comment by alexey-milovidov** [comment]
Two failures yesterday: https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSBjaGVja19zdGFydF90aW1lID49IG5vdygpIC0gSU5URVJWQUwgMSBZRUFSCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCAodGVzdF9zdGF0dXMgTElLRSAnRiUnIE9SIHRlc3Rfc3RhdHVzIExJS0UgJ0UlJykgCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHBvc2l0aW9uKHRlc3RfbmFtZSwgJzAyNDkwX2JlbmNobWFya19tYXhfY29uc2VjdXRpdmVfZXJyb3JzJykgPiAwCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=

**Comment by pufit** [comment]
Not reproducing. Please reopen the issue if it fails again.
