### ISSUE TITLE
MaterializedView from Kafka Engine with Native format 

### ISSUE THREAD

**Issue by igor-sh8** [ClickHouse/ClickHouse#6731]
Hello. 
I have the next schema:
Kakfa -> Table with Kafka Engine and Native format -> Materialized View to table -> Table with MergeTree Engine.

On Clickhouse version 19.9.2 such schema works, but on version 19.13.3 it stopped working. Got such error:
```
2019.08.29 16:02:22.127282 [ 70 ] {} <Error> void DB::StorageKafka::streamThread(): Code: 9, e.displayText() = DB::Exception: Sizes of columns doesn't match, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7f6b5f0]
1. /usr/bin/clickhouse-server() [0x3944050]
2. /usr/bin/clickhouse-server(DB::SquashingTransform::add(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&&)+0x2c) [0x6c2e18c]
3. /usr/bin/clickhouse-server(DB::SquashingBlockOutputStream::write(DB::Block const&)+0x2ab) [0x7363f3b]
4. /usr/bin/clickhouse-server(DB::AddingDefaultBlockOutputStream::write(DB::Block const&)+0x8f) [0x72f057f]
5. /usr/bin/clickhouse-server(DB::CountingBlockOutputStream::write(DB::Block const&)+0x2c) [0x730ce3c]
6. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x105) [0x6c2e4b5]
7. /usr/bin/clickhouse-server(DB::StorageKafka::streamToViews()+0x616) [0x729c6c6]
8. /usr/bin/clickhouse-server(DB::StorageKafka::streamThread()+0x1d7) [0x729cd97]
9. /usr/bin/clickhouse-server(DB::BackgroundSchedulePoolTaskInfo::execute()+0xf9) [0x72bd329]
10. /usr/bin/clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0x6a) [0x72bdb7a]
11. /usr/bin/clickhouse-server() [0x72bdbfa]
12. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1a6) [0x3c760f6]
13. /usr/bin/clickhouse-server() [0xba3e1a0]
14. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3) [0x7f4868fcafa3]
15. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f4868d734cf]
 (version 19.13.3.26 (official build))
```
Also need to say that select query from table with Kafka Engine at the same time working properly. And `insert into select` query also working properly.

Tables metadata:

`create table db.testnativekafka (Date Date, Id Int32, Name String) ENGINE = Kafka() SETTINGS kafka_broker_list = 'kafka.example.com:9092', kafka_topic_list = 'testnative', kafka_group_name = 'testnative', kafka_format = 'Native', kafka_num_consumers = 1, kafka_skip_broken_messages = 1`

`create table db.testnativetable (Date Date, Id Int32, Name String) ENGINE = MergeTree() Partition by (Date) Order By (Date)`

`create materialized view db.testnativemv to db.testnativetable (Date Date, Id Int32, Name String) as select Date, Id, Name from db.testnativekafka`

**Comment by filimonov** [comment]
So you put a messages in Native format in the Kafka? How many rows at once?

Can you check if names & order of columns you put in the Kafka Native stream matches exactly the create statement of Kafka table?

**Comment by igor-sh8** [comment]
Yes, from our custom service we insert data in Native format to the Kafka. In single message we have 3 rows (our tests).

For generating insert order we get metadata from the end table `db.testnativetable`  in which order is the same as order in table with Kafka Engine. We get order of columns from such query (Insert into adms2.testnativetable(Date, Id, Name) VALUES) via tcp protocol.

**Comment by filimonov** [comment]
And do column names also match (inserted stream = Kafka table definition = MV definition) ?

**Comment by igor-sh8** [comment]
Yes. All column names are identical. 
We checked simple MV and MV to Table - result the same. 
If we run select query (select part from creating MV query) from table with Kafka Engine - all works.

**Comment by filimonov** [comment]
Reproduced, was broken after introducing virtual columns.
https://github.com/ClickHouse/ClickHouse/pull/5382/

Will address that soon.
