### ISSUE TITLE
Jepsen test failed with status `COMPLETED`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67318]
https://play.clickhouse.com/play?user=play#U0VMRUNUIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3Rfc3RhdHVzLCB0ZXN0X25hbWUsIHJlcG9ydF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCAxIFlFQVIKICAgIEFORCBwdWxsX3JlcXVlc3RfbnVtYmVyID0gMAogICAgQU5EIHRlc3Rfc3RhdHVzICE9ICdTS0lQUEVEJwogICAgQU5EICh0ZXN0X3N0YXR1cyBMSUtFICdGJScgT1IgdGVzdF9zdGF0dXMgTElLRSAnRSUnKSAKICAgIEFORCBjaGVja19zdGF0dXMgIT0gJ3N1Y2Nlc3MnCiAgICBBTkQgY2hlY2tfbmFtZSA9ICdDbGlja0hvdXNlIEtlZXBlciBKZXBzZW4nCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWU=

**Comment by antonio2368** [comment]
@maxknv it fails because of missing binary

**Comment by maxknv** [comment]
> Jepsen test failed with status COMPLETED

It's COMPLETED with status FAIL

**Comment by maxknv** [comment]
issue is fixed in #67004
