### ISSUE TITLE
Lambda function returns "Resolve identifier ... from parent scope only supported for constants and CTE"

### ISSUE THREAD

**Issue by heyciao** [ClickHouse/ClickHouse#67322]
### Company or project name

"Hobby" of creating a search engine, using Clickhouse to perform text-search.

### Question

**Background info:**
I want to extract "in a single shot" multiple bytes at specific positions of a string-column (the table's string-column might contain pure binary data), and then to use the result in a comparison of a where-clause.

Right now I'm using clauses that create an array of the output of multiple "substring"-functions e.g....
`where array(substring(my_string_col,1,1),substring(my_string_col,2,1),substring(my_string_col,3,1)) = [unhex('68'),unhex('65'),unhex('72')]`
...but that's not so great for multiple reasons (the SQL becomes a mess if there are many positions, the same string is reprocessed multiple times by the same function).
(yup, I could probably concatenate the outputs of the substrings to then use just "... = unhex('686572')", I'm just not yet that far with my optimizations)

I didn't find any existing function that allows me to extract bytes at multiple locations at once and return them concatenated or as an array (something like "substringMany(my_string_col, ([1,1]), [2,1], [3,1])").

I saw that there is a fuction called "extract" ( https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions#extract ) but I'm extremely bad with regex so I'd prefer not to use it (I tried anyway, but I didn't understand how to extract chars/bytes at specific positions with regex).

**Problem:**
I therefore tried to write my own Lambda function...
```
create or replace function mycustfn_extract_bytes_from_string as (s_orig_string, u_pos_array) ->
(
	select groupArray(sub2)
	from
	(
		select substring(s_orig_string, sub1, 1) AS sub2
		from
		(
			select arrayJoin(u_pos_array) AS sub1
		)
	)
)
```
...which compiles successfully.

On the one hand if I test it with e.g. ...
`select mycustfn_extract_bytes_from_string('one_two_three', [10,3,11])`
...it works perfectly fine returning the array "`['h','e','r']`".

On the other hand if I try to use the above function with a real table or with the following query...
```
select COL, mycustfn_extract_bytes_from_string(COL, [10,3,11])
from
(
select 'one_two_three' as COL
)
```
...I get the following error:

> SQL Error [1]: ClickHouse exception, code: 1, host: vmdbcharidx, port: 8123; Code: 1. DB::Exception: Resolve identifier 's_orig_string' from parent scope only supported for constants and CTE. Actual COL node type COLUMN. In scope SELECT substring(s_orig_string, sub1, 1) AS sub2 FROM (SELECT arrayJoin(u_pos_array) AS sub1). (UNSUPPORTED_METHOD) (version 24.6.2.17 (official build))

I don't get it: if the function works for the first (simple/direct) query, then it should work as well for the second query and for table-columns, or?
What am I doing wrong?

Clickhouse v24.6.2.17 (just upgraded, I was previously getting the same errmsg with a v24.4.x)
p.s.:
I saw this ( https://github.com/ClickHouse/ClickHouse/issues/58994 ), and I tested by disabling/enabling the parameters "allow_experimental_analyzer" and "join_use_nulls" but I still had the same problem.

Thanks for reading this :)

**Comment by heyciao** [comment]
So, concerning my "need"/usecase...
> I want to extract "in a single shot" multiple bytes at specific positions of a string-column (the table's string-column might contain pure binary data), and then to use the result in a comparison of a where-clause.

...I _**think**_ that I was able to write a UDF that does that - it returns an array hex'd bytes (hex-values displayed as string-elements of the array):
```
create or replace function mycustfn_extract_hexedbytes_from_string as (s_orig_string, u_array_of_byte_positions) ->
(
	arrayFold(    (acc, v) -> arrayPushBack(acc, hex(reinterpretAsUInt8(substring(s_orig_string,v,1)))   ),      u_array_of_byte_positions, emptyArrayString())
)
```
The description of the fn "arrayFold" wasn't super-clear for me, I had to experiment for some hours with it to understand how it works (especially when involving multiple parameters/arrays) - by being pedantic I would mention that docs could be improved 😛😎

In the end, "arrayFold" loops through each element of "u_array_of_byte_positions" and the parameters of the function ("_(acc, v)_") are for me (as a classical programmer) special as they seem to be only internal:
"acc" is the "accumulator" of the final result and "v" relies on the one extra parameter provided to arrayFold being in this case "_u_array_of_byte_positions_" (extra parms can be provided, e.g. "(acc,v,x)" would therefore need something like "u_array_of_byte_positions, some_additional_array", but then both parms are expected to be arrays and with the same size and their single elements would be provided step-by-step to "_v,x_").
"arrayPushBack" just appends each single result, which is expected to be an "array of strings" because of "emptyArrayString()".
I hope that this alternative explanation/hints can be somehow understood by others and it's helpful 😄.

**Tests:**
1-
`select mycustfn_extract_bytes_from_string('one_two_three' as chunk_lower, [10,3,11])`
Returns "['68','65','72']" - they're the hex of the chars 'h' (68) + 'e' (65) + 'r' (72)

2-
```
select COL, mycustfn_extract_bytes_from_string(COL, [10,3,11])
from
(
select 'one_two_three' as COL
)
```
Same as first test.

3-
Same as first test.

**Alternatives:**
I found yesterday a much easier potential solution which involved using "groupArray()", but as soon as the optimizer sees it (even if used only inside a UDF) then it requires the calling SQL to be grouped by the other listed columns => bad as the main SQL(s) need to be changed (and that the change does not make sense as long as the "grouping" is done only inside a function).

**Conclusion:**
I think that this is it for my usecase (**_hoping_** that I didn't overlook something).
I still think that compared to all other DBs this is too much of a struggle (extraction of multiple bytes from strings + conversions between string/arrays & char/bytes are both a bloodbath in CH compared to many other DBs), so I think that I'll open 2 improvements requests before closing this.

**Comment by heyciao** [comment]
So, I opened following tickets:
* "arrayFold()" documentation improvements: https://github.com/ClickHouse/ClickHouse/issues/67561
* Extraction of multiple bytes from a string: https://github.com/ClickHouse/ClickHouse/issues/67562
* Conversions: https://github.com/ClickHouse/ClickHouse/issues/67563
Up to you if you want to implement them.

Thanks a lot for your DB! CH rocks!!! 😁👍
Closing this issue as my workaround seems to work (hopefully 😛).
Cheers

**Comment by lucasfcnunes** [comment]
Can you reopen this one? I'm having the same issue.

https://fiddle.clickhouse.com/5bc80860-18e7-4c93-910d-e06ef5e99342
```sql
Received exception from server (version 24.10.2):
Code: 1. DB::Exception: Received from localhost:9000. DB::Exception: Resolve identifier 'a.b' from parent scope only supported for constants and CTE. Actual b node type COLUMN. In scope (SELECT b.c FROM b WHERE b.b = a.b). (UNSUPPORTED_METHOD)
(query: with
    a as (
        select 1 a, 1 b
    ),
    b as (
        select 1 b, 1 c
    ),
    c as (
        select 1 c, 1 d
    )
select a.a, c.d
from a
left join c on c.c in (
    select b.c
    from b
    where b.b = a.b
)
settings 
  allow_experimental_analyzer=1
;)
```
