### ISSUE TITLE
Ports collision in integrations tests

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67333]
https://s3.amazonaws.com/clickhouse-test-reports/0/aabf7a576ce42ef03456bf846784adfd1635ccaa/integration_tests__release__[3_4].html

**Comment by zvonand** [comment]
```
E               ERROR: for azurite1  Cannot start service azurite1: driver failed programming external connectivity on endpoint rootteststorageazureblobstorage_azurite1_1 (9f4c03f05ee5c4f679afb91d6bf41bbc23e7c22044c79a6dace70acf0e207e03): Bind for 0.0.0.0:64893 failed: port is already allocated
E               compose.cli.main.exit_with_metrics: Encountered errors while bringing up the project.
```

**Comment by ilejn** [comment]
I've tried to resolve this issue https://github.com/ClickHouse/ClickHouse/pull/55055
while the approach was considered too hackish (which is true).

Currently exercising another way to assign ports reliably.

**Comment by fm4v** [comment]
Fix it in https://github.com/ClickHouse/ClickHouse/pull/67672:
- Allocate a pool of 50 free unique ports to each pytest-xdist worker
- In each process, sequentially allocate these ports from the pool
