### ISSUE TITLE
regex match() wrong result when using (?-s) flag

### ISSUE THREAD

**Issue by nikolastojkoski** [ClickHouse/ClickHouse#67344]
Context: https://clickhouse.com/docs/en/sql-reference/functions/string-search-functions#match
> Unlike re2's default behavior, `.` matches line breaks. To disable this, prepend the pattern with `(?-s)`.

**Describe what's wrong**
Prepending the pattern with `(?-s)` to disable `.` matching line breaks will lead to wrong results, all select queries in this fiddle should output `1`:
https://fiddle.clickhouse.com/abdfcd96-12bf-4c6b-a6ff-61db29301f86

It can be reproduced in most, but not all versions after `22.12.6.22-alpine` (it starts to not work as expected in version `23`). It can be reproduced on the most recent release as well.

**A clear and concise description of what works not as it is supposed to.**
`SELECT match('bob', '(?s)bob')` should output 1 but instead it outputs 0
`SELECT match('bob', '(?-s)bob')` should output 1 but instead it outputs 0

**Workaround**
I found a way around it by additionally providing the case-insensitive re2 flag to the query:
- case sensitive match `SELECT match('bob', '(?-is)bob')` will output 1 as expected
- case insensitive match `SELECT match('bOb', '(?i-s)bob')` will output 1 as expected

**Comment by rschu1ze** [comment]
Evaluation happens in function `vectorVector` in src/Functions/MatchImpl.h.

The code does

```cpp
regexp = cache.getOrSet<is_like, /*no_capture*/ true, case_insensitive>(needle);
regexp->getAnalyzeResult(required_substr, is_trivial, required_substring_is_prefix); /// (*)
```

`getOrSet` (in src/Functions/Regexps.h) does

```cpp
bucket = {pattern, std::make_shared<OptimizedRegularExpression>(createRegexp<like, no_capture, case_insensitive>(pattern))};
```

and `OptimizedRegularExpression` does some preprocessing in its constructor.

For `SELECT match('bob', '(?s)bob');`, function `OptimizedRegularExpression::getAnalyzeResult` returns the preprocessed regexp with `required_substr` this: `sbob`. Then, a substring search for `sbob` runs, finds no match, and concludes that `bob` does not match the regexp.

The workaround to add flag `i` yields required substring `''` (empty string), a normal regular expression matching runs, and it finds a result.

`OptimizedRegularExpression` was last "optimized" 😆 here #47218.

@hanfei1991 You like to take a look? I guess you know the code best.
