### ISSUE TITLE
Why deleting two rows from the database takes a long time?

### ISSUE THREAD

**Issue by wolfaherd** [ClickHouse/ClickHouse#67342]
### Question

Background:
- I have a table of 200GB size.
- This table's DateTime column defined by DateTime('Asia/Shanghai').
- This table used MergeTree Engine and partitioned by toYear(DateTime).  

Operations:

```
SELECT * FROM test.StockDataL1 WHERE DateTime = (SELECT MAX(`DateTime`) FROM test.StockDataL1);
```
![83b4e5a4-14a3-4ba9-a9af-76030bef2944](https://github.com/user-attachments/assets/5ef8695a-3183-49f9-9fc8-2e94ea242cfc)

```
SELECT COUNT(*) FROM test.StockDataL1 WHERE `DateTime` >= '2106-01-01 00:00:00';
```
![24ac3d6b-25cd-493c-b909-effb9d544551](https://github.com/user-attachments/assets/2012bc5c-3c8f-4825-b403-28a85b973fc4)

```
DELETE FROM test.StockDataL1 WHERE `DateTime` = (SELECT MAX(`DateTime`) FROM test.StockDataL1 );
```
![2c18f7a2-b1a6-4a45-831d-7f1fbdf8b709](https://github.com/user-attachments/assets/cad474e3-d710-414d-a072-d09b12a69083)

I want to understand: 
- Why deleting two rows taked a long time? 
- What happend when the DELETE executing? As I understand it, isn't it only affecting one partition?

**Comment by Algunenano** [comment]
From the [docs](https://clickhouse.com/docs/en/sql-reference/statements/alter/delete) you can see `Deletes data matching the specified filtering expression. Implemented as a mutation.`. And if you check the docs about [mutations](https://clickhouse.com/docs/en/sql-reference/statements/alter#mutations), you'll get more information.

That should answer both questions.

**Comment by wolfaherd** [comment]
Thanks very much. I go have a look.
