### ISSUE TITLE
Unique aggregated functions results mismatch in materialized view

### ISSUE THREAD

**Issue by Narzhan** [ClickHouse/ClickHouse#67356]
**Describe the unexpected behaviour**
I've tried to create a materialized view which would compute the aggregated statistics from a table over period of 6 hours. The problem is that some of the values in the mv don't match to the source table data. In particular the issue is with the unique values which are computed in the mv. The value in the mv differs in the range of 20% - 30% to the source table. Here is an example of the tables used in my scenario. The names of the tables and some attributes were changed for this issue.

Source table
```
CREATE TABLE IF NOT EXISTS sales
(
    timestamp           DateTime64(6, 'UTC') CODEC(Delta, ZSTD(1)),
    client_id           LowCardinality(String) CODEC(ZSTD(1)),
    product_name        String CODEC(ZSTD(1)),
    category_id         String CODEC(ZSTD(1))
)
ENGINE = MergeTree()
PARTITION BY toDate(timestamp)
PRIMARY KEY (client_id, toUnixTimestamp(timestamp))
ORDER BY (client_id, toUnixTimestamp(timestamp))
TTL toDateTime(timestamp) + toIntervalDay(50)
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
```

MV
```
CREATE MATERIALIZED VIEW IF NOT EXISTS sales_aggregated_mv TO sales_aggregated_table
(
    `timestamp` DateTime,
    `product_name` String,
    `unique_client_ids` AggregateFunction(uniqCombined, String),
    `unique_category_ids` AggregateFunction(uniqCombined, String),
    `sum_sales` AggregateFunction(count)
) AS
SELECT
    toStartOfInterval(timestamp, toIntervalHour(6)) AS timestamp,
    product_name,
    uniqCombinedState(client_id) AS unique_client_ids,
    uniqCombinedState(category_id) AS unique_category_ids,
    countState() AS sum_sales
FROM sales
GROUP BY
    product_name,
    timestamp;
```

MV source table
```
CREATE TABLE IF NOT EXISTS sales_aggregated_table
(
    `timestamp` DateTime CODEC(Delta(4), ZSTD(1)),
    `product_name` String CODEC(ZSTD(1)),
    `unique_client_ids` AggregateFunction(uniqCombined, String) CODEC(ZSTD(1)),
    `unique_category_ids` AggregateFunction(uniqCombined, String) CODEC(ZSTD(1)),
    `sum_sales` AggregateFunction(count) CODEC(ZSTD(1))
)
ENGINE = AggregatingMergeTree()
PARTITION BY toDate(timestamp)
PRIMARY KEY (toUnixTimestamp(timestamp), product_name)
ORDER BY (toUnixTimestamp(timestamp), product_name)
TTL timestamp + toIntervalDay(8)
SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
```

The clickhouse version we are using is 23.9.4.

**Expected behavior**
The aggregated results match the source table data.

**Comment by den-crane** [comment]
Which values? All measurements? unique_client_ids/ unique_category_ids/ sum_sales ?

Provide SELECTs queries, that you use to compare the data.

**Comment by Narzhan** [comment]
Both `unique_client_ids `and `unique_category_ids` are the ones with the incorrect values.

To get the data from source table:
`select toStartOfInterval(timestamp, toIntervalHour(6)) AS timestamp, product_name,  uniqCombined(source_ip), uniqCombined(client_id), count() from sales where product_name = 'product_name' group by timestamp, product_name order by timestamp`

To get the data from the mv:
`select timestamp, product_name, uniqCombinedMerge(unique_client_ids), uniqCombinedMerge(unique_category_ids), countMerge(sum_sales) from sales_aggregated_table where product_name = 'product_name' group by timestamp, product_name order by timestamp`

**Comment by den-crane** [comment]
try to use uniqCombined64 instead. 

AggregateFunction(uniqCombined64, String),
uniqCombined64State
uniqCombined64Merge

**Comment by Narzhan** [comment]
Unfortunately that did not help. The values are still not correct. From my observation it has to be something with the time aggregation part `toStartOfInterval(timestamp, toIntervalHour(6)) AS timestamp`. When I've tried to to use just a hour interval (`toStartOfHour(timestamp) AS timestamp`) instead of the 6 hour intervals everything worked fine.

**Comment by den-crane** [comment]
Can you please share a result of `select timezone()`?

**Comment by Narzhan** [comment]
Here it is:

```
┌─timezone()─┐
│ UTC        │
└────────────┘
```

**Comment by den-crane** [comment]
I don't see any problems and cannot reproduce the issue https://fiddle.clickhouse.com/1b9a5207-1af9-4794-9439-ca548bcd9158


The only issue is different column order in select and source_id instead of category:

```
uniqCombined(source_ip),                               uniqCombined(client_id)

uniqCombinedMerge(unique_client_ids),       uniqCombinedMerge(unique_category_ids)
```
