### ISSUE TITLE
DDSketch Quantiles

### ISSUE THREAD

**Issue by MrBuddyCasino** [ClickHouse/ClickHouse#6739]
(you don't have to strictly follow this form)

**Use case**
We are currently using two `QuantilesTimingWeighted` columns, one for values up to 30sec and one scaled by 100 for larger values. We'd like to be able to use just one column to gain speed, but t-digest is slower overall. 

**Describe the solution you'd like**
DDSketch has just been released, but it is described as being very fast. Our hope is that we can use DDSketch with a single `QuantilesTiming` column with decent precision and gain speed.

**Additional context**
HN thread: https://news.ycombinator.com/item?id=20829404

**Comment by alexey-milovidov** [comment]
I have some initial thoughts, and this algorithm looks easy to implement. It may look like adaptive variant of QuantileTiming.

**Comment by alexey-milovidov** [comment]
Also take a look at #16641.

**Comment by yandooo** [comment]
are there any plans to get ddsketch/uddsketch native support in clickhouse? Today, the only option is to go UDF way.

**Comment by UnamedRus** [comment]
PR https://github.com/ClickHouse/ClickHouse/pull/46635

**Comment by srikanthccv** [comment]
Please take a look https://github.com/ClickHouse/ClickHouse/pull/55305. Can you point me to some docs on how to add tests?
