### ISSUE TITLE
what affects the partitioning of query_log && metric_log?

### ISSUE THREAD

**Issue by Mrmanbanpai** [ClickHouse/ClickHouse#67427]
### Question

hello! 
      I recently encountered the problem of metric_log and query_log too many parts. The version used is 21.3.18.4.
We write files using the process of writing storage files and attaching them to clickhouse-server, and of course, we also use aggregate tables. So now I don’t know how to deal with these system tables, or whether there are any situations that will prevent them from merging partitions? Or how to control their growth rate. I read the official FAQ and github issues. Most of the scenarios are different from ours. Do query_log or mertric require additional settings?

It seems that we did not intervene in the query_log and metric_log tables. What prevents them from merging?

**Comment by alexey-milovidov** [comment]
No additional settings are needed for these tables.
They should work well by default.

If they cannot merge and you see a "too many parts" message, you don't have to do anything.

You have to upgrade your ClickHouse server to the latest version.
