### ISSUE TITLE
MemorySanitizer: use-of-uninitialized-value in DatabaseReplicated / DDLWorker / DatabaseReplicatedDDLWorker 

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#67468]
https://s3.amazonaws.com/clickhouse-test-reports/0/fc458509c72ce3345437a882d117615ed449fbc3/stateless_tests__msan__[2_4].html

**Comment by ucasfl** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/67262?

**Comment by KochetovNicolai** [comment]
Yes, I think so
