### ISSUE TITLE
clickhouse  DDL语句报错超时180s

### ISSUE THREAD

**Issue by moxuan12138** [ClickHouse/ClickHouse#67486]
### Question

你好，任务同时执行的太多的话是不是这种场景报错的呢，不是因为truncate的引起的？我看网上说是因为clickhouse 执行ddl语句是同步执行的 难道是这样导致180s超时的吗

**Comment by cangyin** [comment]
DDL 语句的 180 秒超时只是客户端的表现，实际上该 DDL 已经被放到 ZooKeeper 队列中，所有 ClickHouse 服务器在看到这个 DDL 之后都会执行它。可以给客户端设置超时参数 distributed_ddl_task_timeout=3600。

**Comment by cangyin** [comment]
要查看某个 ClickHouse 实例上尚未完成的 DDL，可以执行：
```sql
SELECT entry,query_create_time,query FROM system.distributed_ddl_queue WHERE status!='Finished' ORDER BY query_create_time ASC
```

**Comment by rschu1ze** [comment]
Please raise issues in English language, thanks!
