### ISSUE TITLE
LEFT SEMI JOIN doesn't work with tuple(NULL) = tuple(NULL)

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#67493]
**Describe what's wrong**

Difference in behavior with new analyzer + SEMI JOIN + tuple(NULL) = tuple(NULL)

```
SELECT '============WRONG';

SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT SEMI JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON tuple(a.key) = tuple(b.key) SETTINGS allow_experimental_analyzer=1;

┌─key─┐
│ 1   │
└─────┘

SELECT '============CORRECT WITH IS NOT DISTINCT FROM';

SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT SEMI JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON a.key IS NOT DISTINCT FROM b.key  SETTINGS allow_experimental_analyzer=1;

┌─key──┐
│ ᴺᵁᴸᴸ │
└──────┘
┌─key─┐
│ 1   │
└─────┘

SELECT '============CORRECT WITHOUT ANALYZER';
SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT SEMI JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON tuple(a.key) = tuple(b.key) SETTINGS allow_experimental_analyzer=0;

┌─key──┐
│ ᴺᵁᴸᴸ │
└──────┘
┌─key─┐
│ 1   │
└─────┘

SELECT '============CORRECT WITH LEFT ANY JOIN';
SELECT a.key FROM (SELECT NULL AS key UNION ALL SELECT '1' as key) as a LEFT ANY JOIN (SELECT NULL AS key UNION ALL SELECT '1' as key) as b ON tuple(a.key) = tuple(b.key) SETTINGS allow_experimental_analyzer=1;

┌─key──┐
│ ᴺᵁᴸᴸ │
└──────┘
┌─key─┐
│ 1   │
└─────┘
```
https://fiddle.clickhouse.com/eb997e30-f01c-4035-99dd-c8f91a3503e8

**Does it reproduce on the most recent release?**

Yes

@vdimir, do you have any idea? AFAIK behavior should match as isNotDistinctFrom is implemented via tuples
https://github.com/ClickHouse/ClickHouse/pull/53755#issuecomment-1717623464

**Comment by vdimir** [comment]
It's because of tuple comparison elimination. In analyzer expression `(a, b) = (c, d)` can be rewritten to `a = c AND b = d`. Actually, it can be confusing that `SELECT tuple(NULL,1) == tuple(NULL, 1)` return `NULL`, while join algorithms can join on such value. Also, for arrays `SELECT [NULL,1] == [NULL, 1]` is `true`.

Let's keep such behavior and do not apply tuple comparison elimination for `JOIN ON` section. https://github.com/ClickHouse/ClickHouse/pull/67538

**Comment by UnamedRus** [comment]
> In analyzer expression (a, b) = (c, d) can be rewritten to a = c AND b = d.

Theoretically, it looks like great optimization to have enabled, but i'm not aware about people who use tuples in such way for JOIN.

Only reason why we used this strange way of writing tuples here, is just to mimic IS NOT DISTINCT FROM behavior for older CH version.

So, hope that no one will be affected by disable of this optimization.
