### ISSUE TITLE
Replace partition atomicity

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#6749]
Is replace partition atomic operation?

Problem. I need to rebuild partitions because data is changing. Simple solution was to delete partition and insert new data. Problem is that data disappearing and then it appears partially until insert is completed. As I understand replace partition will resolve that problem.

**Comment by den-crane** [comment]
I am also wondering.

I think it is not atomical.

https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Storages/StorageMergeTree.cpp#L1160

Anything could happened and partitions will stay not removed.

**Comment by blinkov** [comment]
@thyn, do you have any further questions?

**Comment by baibaichen** [comment]
@den-crane  see https://github.com/ClickHouse/ClickHouse/pull/2217, looks  replace is atomicity
