### ISSUE TITLE
Preload MergeTree table data into memory to reduce disk IO

### ISSUE THREAD

**Issue by Alex-Cheng** [ClickHouse/ClickHouse#67548]
> (you don't have to strictly follow this form)

**Company or project name**

Prothentic, Inc.

**Use case**

To enhance performance and reduce disk IO, it would be beneficial to have a feature that allows MergeTree table data to be preloaded into memory. This would enable faster data access and improve overall query performance by minimizing the need for frequent disk reads.

Additionally, when memory is under pressure, ClickHouse should be able to automatically release the preloaded data from memory to ensure there is enough available memory for other operations.

Furthermore, the feature should intelligently avoid preloading columns that contain a large amount of data to prevent out-of-memory issues. It would be even more advantageous if ClickHouse could smartly preload frequently used columns while avoiding the preloading of rarely used columns. This selective preloading would optimize memory usage and improve query performance effectively.

**Describe the solution you'd like**

I could have a command or setting, to indicate which tables should be reloaded for improving performance. When a table is set to be "preload for accelerating", ClickHouse could manage the preload data in memroy and release them if memory is under pressure, or access to the preloaded data is becoming rare.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

We have a system built on ClickHosue and we were proud of the perfomance. However a competitor product that is built based on Spark, has better performance in some cases, to our surprise. We investigated the reason and discovered that Spark is an in-memory database, and through experiments, we found that loading data into memory (by creating Memory engine tables) can greatly improve performance(five times faster in our experiment).

So I think it would be a good feature.

**Comment by UnamedRus** [comment]
Did you look into uncompressed cache? 
It may be not that smart about preload of specific columns but can be still useful

**Comment by Alex-Cheng** [comment]
> Did you look into uncompressed cache? It may be not that smart about preload of specific columns but can be still useful

Thank you very much. 
In our system's main table, there is one particularly large column that occupies 95% of the entire table. I would like this column not to be preloaded into memory, as it would otherwise cause OOM.

**Comment by Alex-Cheng** [comment]
@UnamedRus  Thank you. Your suggestion works well. The performacne is 1 times faster.
