### ISSUE TITLE
Regression in `executable` table function using new analyzer

### ISSUE THREAD

**Issue by antaljanosbenjamin** [ClickHouse/ClickHouse#67547]
**Describe the issue**
The `executable` can receive an argument that depends on a subquery without using the new analyzer. With the new analyzer it throws an error.

```
CREATE TABLE t (args String) ENGINE=MergeTree() ORDER BY args;
INSERT INTO t VALUES ('aaa'), ('bbb');


SELECT * FROM executable( (select 'bash '|| args FROM t LIMIT 1 ), TabSeparated, 't text' ) SETTINGS allow_experimental_analyzer = 1;
``` 
[Reproduction](https://fiddle.clickhouse.com/a0790efa-747d-4640-ab7a-5a820f5a63ee). Fiddle complains about `bash` doesn't exist inside user files, but that is kind of expected on fiddle. I assume if it existed, it would execute it.

**Error message and/or stacktrace**

```
Received exception from server (version 24.6.2):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal type of argument 'script_name' for table function 'executable': must be an identifier or string literal. (ILLEGAL_TYPE_OF_ARGUMENT)
(query: SELECT * FROM executable( (select 'bash '|| args FROM t LIMIT 1 ), TabSeparated, 't text' ) SETTINGS allow_experimental_analyzer = 1;)
```

**Additional context**
The issue was [raised](https://clickhousedb.slack.com/archives/CU478UEQZ/p1722434524104699) in community slack the reasoning behind the neccesity of this is the following:

> Since the “script_name” field does support passing arguments to a script, it is vitally important that functions and subqueries are made to work again for that argument.

**Comment by novikd** [comment]
@kceventus It should be supported in #69292
