### ISSUE TITLE
[Performance Regression]  Exception: Memory limit (total) exceeded.  Clickhouse version upgrade from 22.3 to 24.5 

### ISSUE THREAD

**Issue by kazhou2024** [ClickHouse/ClickHouse#67588]
### Question

Hello experts, 
  we recently upgrade Clickhouse from 22.3 to 24.5 for security ask. But our regular functional tests failed with bellow error, so is there any performance Regression and any plan to fix?

ClickHouse.Client.ClickHouseServerException (0x000000F1): Code: 241. DB::Exception: Memory limit (total) exceeded: would use 45.54 GiB (attempt to allocate chunk of 4249160 bytes), maximum: 43.20 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.: (while reading column xxx): (while reading from part /var/lib/clickhouse/store/943/94312879-371a-41eb-8f57-89576626f4f8/202404_18065_31079_2303/ in table xxx (94312879-371a-41eb-8f57-89576626f4f8) located on disk default of type local, from mark 0 with max_rows_to_read = 2933): While executing MergeTreeSelect(pool: ReadPool, algorithm: Thread). (MEMORY_LIMIT_EXCEEDED) (version 24.5.1.1763 (official build))

**Comment by Algunenano** [comment]
No repro provided. The exception is just saying that CH is reaching the memory limit when reading data from disk.

Please, if you find what you believe is a regression provide reproduction steps so different versions can be compared.

**Comment by SaltTan** [comment]
There is also an issue in 24.5 that might affect usage calculation
* https://github.com/ClickHouse/ClickHouse/issues/64652
