### ISSUE TITLE
The problem of simultaneous use of the "with" and "final" query statements

### ISSUE THREAD

**Issue by myBigbug** [ClickHouse/ClickHouse#67585]
clickhouse version 2024.3

when we use below statement 
```sql
  select id,yn
  from my_db.my_table final
  where
    yn = 1
    and user_name in ('aa')
```
result 0 row

when we use below statement 
```sql
with sub_query as (
  select id,yn
  from my_db.my_table final
  where
    yn = 1
    and user_name in ('aa')
)
select
  count(t.id)
from
  sub_query t
where
  t.yn = 1
```
count result 119

**Comment by myBigbug** [comment]
#### After my tests, the "final" is invalid

**Comment by Algunenano** [comment]
Please share a complete reproducer. It [might have been addressed already](https://github.com/ClickHouse/ClickHouse/pull/62811)
