### ISSUE TITLE
Refreshable view: replication is broken for a target table

### ISSUE THREAD

**Issue by vsuraev-godaddy** [ClickHouse/ClickHouse#67638]
ClickHouse local version 24.8.1.346 (official build)

A possible bug:
1. a replicated table is created as `CREATE TABLE db1.table1 ON CLUSTER cluster_1S_2R(id UInt64, column1 String)ENGINE = ReplicatedMergeTree() ORDER BY id`
2. A table with TableEngine 'Redis' is created: `CREATE TABLE redis(id UInt64, column1 String)Engine=Redis('localhost:6379') PRIMARY KEY (id)`
3. A refreshable materialized view is created: ```
SET allow_experimental_refreshable_materialized_view = 1
CREATE MATERIALIZED VIEW from_redis2 REFRESH EVERY 1 MINUTE TO from_redis AS SELECT redis.id AS id, redis.column1 as column1 from redis
4. A key is added to the Redis KVS, seen in 'redis' table, seen in 'from_redis' MV and seen int 'table1' but not replicated. Adding entries directly to the replicated table does not result in replication either (and worked before the MV has been created)
```
If I create an incremental MV instead of refreshable, all entries added to 'redis' table (not to Redis KVS itself) are replicated.
The only way to restore table1 replication is to delete the refreshable MV and recreate table1

**Comment by al13n321** [comment]
Before clickhouse 24.10, refreshable materialized views didn't support replicated tables.

In 24.10+ (not released yet, https://github.com/ClickHouse/ClickHouse/pull/60669), refreshable MV supports replicated tables only in Replicated databases (https://clickhouse.com/docs/en/engines/database-engines/replicated). Example:
```
create database re engine Replicated(...); -- on each replica
create table re.target (x DateTime) engine ReplicatedMergeTree order by x;
create materialized view re.refresher refresh every 1 minute to re.target as select now() as x settings allow_experimental_refreshable_materialized_view=1;
select * from re2.target;
```
