### ISSUE TITLE
Flaky `test_zookeeper_config_load_balancing` test

### ISSUE THREAD

**Issue by serxa** [ClickHouse/ClickHouse#67666]
It became flaky recently, and the race was already fixed here https://github.com/ClickHouse/ClickHouse/issues/67163, but it is still flaky now for some other reason. report from today: https://s3.amazonaws.com/clickhouse-test-reports/0/18f1ec57cb33b439bc06bad8c580f6b25631153a/integration_tests__tsan__[5_6].html

**Comment by Algunenano** [comment]
Fixed in https://github.com/ClickHouse/ClickHouse/pull/67590. That run does not contain the fix:
```
                            "lsof -a -i4 -i6 -itcp -w | grep 'testzookeeperconfigloadbalancing_zoo1_1.*testzookeeperconfigloadbalancing_default:2181' | grep ESTABLISHED | wc -l",
```
