### ISSUE TITLE
full text search very slow

### ISSUE THREAD

**Issue by dongjicheng** [ClickHouse/ClickHouse#67693]
### Company or project name

my dataset has 1 billion records。

i use like  and full text index, When the number of likes is often very slow, and I just want to do a count operation, it seems that decompressing the data wastes a lot of time. In fact, there is no need to decompress, only count, thank you!

### Question

my dataset has 1 billion records。

i use like  and full text index, When the number of likes is often very slow, and I just want to do a count operation, it seems that decompressing the data wastes a lot of time. In fact, there is no need to decompress, only count, thank you!

**Comment by alexey-milovidov** [comment]
ClickHouse does not have full text indices in production.
