### ISSUE TITLE
Dashboard: time should be in UTC

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67697]

**Comment by alexey-milovidov** [comment]
Needed for #67698

**Comment by azat** [comment]
@alexey-milovidov why it should be in UTC? It looks useful to see the times in local timezone to me

**Comment by alexey-milovidov** [comment]
Yes, when I run tests and look at the dashboard, I often like to see the local time, because I know when I ran these tests.
But another case (which I see more often) is to look at the dashboards and read the logs at the same time. And logs have time in UTC, typically.

**Comment by alexey-milovidov** [comment]
The best option will be to use server time. But unfortunately, the `uPlot` library requires conversion into unix timestamp, and then displays by the browser's local time.
