### ISSUE TITLE
Issue with CI Check Failing Due to ec2_admin IAM Role

### ISSUE THREAD

**Issue by Zawa-ll** [ClickHouse/ClickHouse#67735]
### Question

I encountered an issue in my pull request (PR) #66478  where a check is failing due to an error related to ec2_admin IAM role. Below is the information I have:

```
INFO:botocore.credentials:Found credentials from IAM Role: ec2_admin
Check if rerun for name: [Stateless tests (msan)], extended name [Stateless tests (msan) [1/3]]
Commit status or Build Report is already present - job will be skipped with status: [failure]
{}
Error: Process completed with exit code 
```

detailed log can be seen In this page: 
https://github.com/ClickHouse/ClickHouse/actions/runs/10010962549/job/27689932037?pr=66478

The error message indicates that the process completed with an exit code but does not specify which code it was.
It seems that the job is skipped with a failure status because a build report or commit status is already present.

Please help me out! Any response will be appreciated!

**Comment by alexey-milovidov** [comment]
It means that tests have failed.

**Comment by Zawa-ll** [comment]
> It means that tests have failed.

Thank you for tour response, I will check it again
