### ISSUE TITLE
Best Method to Delete Data from ReplicatedMergeTree Tables in a Cluster

### ISSUE THREAD

**Issue by aol-59** [ClickHouse/ClickHouse#67745]
My cluster has 12 nodes: 6 primary and 6 replicas. Each node’s size exceeds 80%, and the total data size is 8 petabytes. There are 3 tables from which I want to delete the first 6 months of data. The table engine is ReplicatedMergeTree. Should I use ALTER TABLE and add a TTL clause to delete only the first 6 months, or should I use the DELETE clause?
Version:23.8.1.2992

**Comment by den-crane** [comment]
Preferably "alter table drop partition" or properly configured TTL (aligned with partition expression or with ttl_only_drop_parts) -- very light process, just removes files, without reading/writing.

`alter table delete` -- less preferable, processes rows (can read and write your petabytes)
`delete from ....` -- least preferable (it does not remove data, just marks rows as deleted using tombstones.

>Version:23.8.1.2992

You should upgrade, there is: 23.8.16.40.
