### ISSUE TITLE
Logical error: 'Statistics 'tdigest' does not support estimating value of type String'.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67742]
https://s3.amazonaws.com/clickhouse-test-reports/67727/fc651cc0c61feb37e9cf104612cc0ac0cd7448e9/ast_fuzzer__ubsan_.html

Revert this: https://github.com/ClickHouse/ClickHouse/pull/59357

**Comment by JackyWoo** [comment]
Will be fixed in #67013

**Comment by hanfei1991** [comment]
Will be also fixed by https://github.com/ClickHouse/ClickHouse/pull/67858
