### ISSUE TITLE
Dictionary snapshots to disk to allow faster restarts

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#6774]
**Use case**
For some use cases we have large dictionaries (10GB+, 10s millions entries) backed by ODBC source. Everything is nice until you have to restart ClickHouse. Due to the amount of data needed to be transferred and backend database performance it may take more than 10 minutes to load dictionaries.

**Describe the solution you'd like**
Snapshot dictionaries to local filesystem to allow faster restarts.

One alternative would be to run a performant caching proxy in between CH and database backend.

**Comment by alexey-milovidov** [comment]
@nikvas0 is currently developing different but related task named "key-value dictionaries on local SSD".

**Comment by nvartolomei** [comment]
ssd cache dictionary seems close enough, #11947
