### ISSUE TITLE
Stateless test `test_disk_over_web_server/test.py::test_page_cache` is flaky

### ISSUE THREAD

**Issue by azat** [ClickHouse/ClickHouse#67753]
CI: https://s3.amazonaws.com/clickhouse-test-reports/65978/39e9f5dcde5d9a86f36c46974c7b0d47beb60259/integration_tests__asan__old_analyzer__[5_6].html

Cc: @al13n321

**Comment by azat** [comment]
One more https://s3.amazonaws.com/clickhouse-test-reports/64955/6c495863667c78a2ac54564fc941b70b2dc61177/stateless_tests__tsan__s3_storage__%5B3_5%5D.html

**Comment by KochetovNicolai** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/0/34ddcdcc641546685c141c1bab5e48e8cd85ab43/integration_tests__asan__old_analyzer__[5_6].html

**Comment by pamarcos** [comment]
https://s3.amazonaws.com/clickhouse-test-reports/67733/98ccca99f2e25883c9f18d5711ce5c61a2432ecd/integration_tests__asan__old_analyzer__[6_6]//home/ubuntu/actions-runner/_work/_temp/test/output_dir/integration_run_parallel0_0.log
