### ISSUE TITLE
`CHECK GRANT` query

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67772]
**Use case**

Let's suppose I want to add a save/load feature to the advanced dashboard. It will be invaluable.
I will save the dashboards in the `dashboards` table, which the user will have to pre-create on the server.

However, the advanced dashboard should work on any server, including readonly servers. So, I will have to check if the dashboard table exists and is accessible.

I can use a simple SELECT query for that to check if it does not throw an exception. But it looks unnatural, and it can pollute server logs with unnecessary queries.

**Describe the solution you'd like**

Similar to GRANT and REVOKE queries, implement the `CHECK GRANT` query, which will return 0 and 1.
```
CHECK GRANT SELECT (column1) ON database.table
```

**Comment by Unalian** [comment]
Hi @alexey-milovidov I would like to work on this issue.

**Comment by alexey-milovidov** [comment]
@Unalian, thank you! This will be amazing!

**Comment by Unalian** [comment]
The `Grant`  does not seem to judge whether the table exists. The User can grant AccessRightsElements to others if the User has grants for them. If I only use a method similar to the `GRANT` query to query whether the user has certain permissions on the table, I cannot determine whether the table exists. 
```SQL
VM :) grant select(xx) on unexist_table to mark

GRANT SELECT(xx) ON unexist_table TO mark

Query id: 11666d59-cc10-4e20-926e-c6ba05962684

Ok.

0 rows in set. Elapsed: 0.001 sec. 

VM :) show grants for mark

SHOW GRANTS FOR mark

Query id: cc495175-d760-4c62-ab0b-409cc6dea2dd

   ┌─GRANTS FOR mark───────────────────────────────────┐
1. │ GRANT SELECT(name) ON database.`table` TO mark    │
2. │ GRANT SELECT(xx) ON default.unexist_table TO mark │
3. │ GRANT SELECT(name) ON system.users TO mark        │
   └───────────────────────────────────────────────────┘

3 rows in set. Elapsed: 0.001 sec. 

VM :) check grant select(xx) on default.unexist_table

CHECK GRANT SELECT(xx) ON default.unexist_table

Query id: d1b2bc77-ed18-4b9a-9556-7b5e91aecfa1

   ┌─1─┐
1. │ 1 │
   └───┘

1 row in set. Elapsed: 0.002 sec. 


```
Therefore, could you please confirm which of the following effects you want `Check Grant` to have:
1. Check whether a table exists and whether the user has certain permissions on the table,
2. Just want to check whether the user has certain permissions on the table

**Comment by Unalian** [comment]
@alexey-milovidov  Please take a look at this question.

> The `Grant` does not seem to judge whether the table exists. The User can grant AccessRightsElements to others if the User has been granted AccessRightsElements. If I only use a method similar to the `GRANT` query to query whether the user has certain permissions on the table, I cannot determine whether the table exists.
> 
> ```sql
> VM :) grant select(xx) on unexist_table to mark
> 
> GRANT SELECT(xx) ON unexist_table TO mark
> 
> Query id: 11666d59-cc10-4e20-926e-c6ba05962684
> 
> Ok.
> 
> 0 rows in set. Elapsed: 0.001 sec. 
> 
> VM :) show grants for mark
> 
> SHOW GRANTS FOR mark
> 
> Query id: cc495175-d760-4c62-ab0b-409cc6dea2dd
> 
>    ┌─GRANTS FOR mark───────────────────────────────────┐
> 1. │ GRANT SELECT(name) ON database.`table` TO mark    │
> 2. │ GRANT SELECT(xx) ON default.unexist_table TO mark │
> 3. │ GRANT SELECT(name) ON system.users TO mark        │
>    └───────────────────────────────────────────────────┘
> 
> 3 rows in set. Elapsed: 0.001 sec. 
> 
> VM :) check grant select(xx) on default.unexist_table
> 
> CHECK GRANT SELECT(xx) ON default.unexist_table
> 
> Query id: d1b2bc77-ed18-4b9a-9556-7b5e91aecfa1
> 
>    ┌─1─┐
> 1. │ 1 │
>    └───┘
> 
> 1 row in set. Elapsed: 0.002 sec. 
> ```
> 
> Therefore, could you please confirm which of the following effects you want `Check Grant` to have:
> 
> 1. Check whether a table exists and whether the user has certain permissions on the table,
> 2. Just want to check whether the user has certain permissions on the table
