### ISSUE TITLE
Abort a merge caused by OPTIMIZE TABLE xxx FINAL DEDUPLICATE

### ISSUE THREAD

**Issue by anche71** [ClickHouse/ClickHouse#67773]
### Question

Hello,

CH version 23.4.2.1, the table in question is a ReplicatedMergeTree table. There are two replicas, Zookeeper is used for managing the replicas.

The following commands were issued on one of the replicas:
`OPTIMIZE TABLE somedb.sometable PARTITION '202406' FINAL DEDUPLICATE BY date, * EXCEPT ( somecolumns)`
`OPTIMIZE TABLE somedb.sometable PARTITION '202407' FINAL DEDUPLICATE BY date, * EXCEPT ( somecolumns)`

The table structure: partition key: toYYYYMM(date), sorting: "date" and some more columns, primary key: "date" and some more columns. The partitions being merged are large: 28Gb  and 50Gb (as per system.parts bytes_on_disk)

The two merges have been running for a couple of days and none is able to finish. They just start over. I hoped to find the reason for abort or failure in system.part_log. The query with filter: table, partition_id, event_date, merged_from, and error > 0 indeed returned two results with identical error 236, and identical exception:

> Code: 236. DB::Exception: Cancelled merging parts. (ABORTED), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xce87095 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 1. ? @ 0x8630176 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 2. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::executeImpl() @ 0x13048da8 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 3. DB::MergeTask::ExecuteAndFinalizeHorizontalPart::execute() @ 0x1304876b in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 4. DB::MergeTask::execute() @ 0x1304d85a in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 5. DB::ReplicatedMergeMutateTaskBase::executeImpl() @ 0x132eb8ef in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 6. DB::ReplicatedMergeMutateTaskBase::executeStep() @ 0x132ea774 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 7. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::routine(std::shared_ptr<DB::TaskRuntimeData>) @ 0x78b4fac in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 8. DB::MergeTreeBackgroundExecutor<DB::DynamicRuntimeQueue>::threadFunction() @ 0x78b4c2a in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 9. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false>, void*>) @ 0xcf5c2f5 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 10. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false>>::scheduleImpl<void>(std::function<void ()>, long, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0xcf5eb35 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 11. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xcf58121 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 12. ? @ 0xcf5d9a1 in /home/releases/clickhouse-rhel/23.4.2.1/clickhouse/bin/clickhouse
> 13. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
> 14. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
>  (version 23.4.2.1)

It is not immediately clear what the reason for "Cancelled merging parts. (ABORTED)," is. Could you please advise?

If I assess the situation correctly I need either to help CH to finish the merges by giving it more resources (unclear which exactly), or somehow about these merges.

Is it possible to abort them? Restarting CH did not help as the merges start again. Issuing the command
`SYSTEM STOP MERGES somedb.sometable` does not help either- the merges just start again after I issue
`SYSTEM START MERGES somedb.sometable`

Thanks in advance, I hope you can help.

**Comment by Algunenano** [comment]
Alternative builds are not supported and old releases are also not supported. You should use a [supported release](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md).

> It is not immediately clear what the reason for "Cancelled merging parts. (ABORTED)," is. Could you please advise?

Check the logs before this message to see what the server was doing.

> Is it possible to abort them? Restarting CH did not help as the merges start again. Issuing the command

MergeTree's need to merge parts to maintain good performance. If you don't want large parts being merged you can [tweak the settings](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#max-bytes-to-merge-at-max-space-in-pool).
