### ISSUE TITLE
Access denied from Minio in tests

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67823]
`01171_mv_select_insert_isolation_long`

https://s3.amazonaws.com/clickhouse-test-reports/67555/576e0952b51b5e0a0f2925baddb342689b771cb8/stateless_tests__debug__s3_storage__[1_2].html

**Comment by tavplubix** [comment]
Minio indeed has replied with 403, but I have no idea why:
```
rg -Faz "nrnowtbezifzzmjnbutmlfmldhkkv" minio.log.zst
813071:2024-08-05T02:23:08:000 [403 Forbidden] s3.PutObject localhost:11111/test/jqe-first-random-part/new-style-prefix/non/nrnowtbezifzzmjnbutmlfmldhkkv 127.0.0.1         16.402ms     ↑ 172 B ↓ 738 B
```

```
random-part/new-style-prefix/non/nrnowtbezifzzmjnbutmlfmldhkkv 127.0.0.1         16.402ms     ↑ 172 B ↓ 738 B
2990824:2024.08.05 02:23:08.162966 [ 2099 ] {b20488ab-8e5e-4657-b4ad-a8c624265d62} <Information> AWSClient: AWSXmlClient: HTTP response code: 403
2990825-Resolved remote host IP address: 127.0.0.1:11111
2990826-Request ID: 17E8AA033094BF20
2990827-Exception name: AccessDenied
2990828-Error message: Access Denied.
2990829-11 response headers:
2990830-accept-ranges : bytes
2990831-content-length : 415
2990832-content-security-policy : block-all-mixed-content
2990833-content-type : application/xml
2990834-date : Sun, 04 Aug 2024 23:23:08 GMT
2990835-server : MinIO
2990836-strict-transport-security : max-age=31536000; includeSubDomains
2990837-vary : Accept-Encoding
2990838-x-amz-request-id : 17E8AA033094BF20
2990839-x-content-type-options : nosniff
2990840-x-xss-protection : 1; mode=block
2990841-2024.08.05 02:23:08.163136 [ 2099 ] {b20488ab-8e5e-4657-b4ad-a8c624265d62} <Information> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2990842-2024.08.05 02:23:08.163143 [ 237576 ] {} <Trace> TCP-Session: f586cce9-f489-4984-bd53-0322ec695094 Creating query context from session context, user_id: 94309d50-4f52-5250-31bd-74fecac179db, parent context user: default
2990843-2024.08.05 02:23:08.163310 [ 2099 ] {b20488ab-8e5e-4657-b4ad-a8c624265d62} <Error> WriteBufferFromS3: S3Exception name AccessDenied, Message: Access Denied., bucket test, key jqe-first-random-part/new-style-prefix/non/nrnowtbezifzzmjnbutmlfmldhkkv, object size 10
...
```

The interesting thing is
```
2024-08-05T02:23:08:000 [403 Forbidden]

2024.08.05 02:23:08 ...
-date : Sun, 04 Aug 2024 23:23:08 GMT
2024.08.05 02:23:08.163136 [ 2099 ] {b20488ab-8e5e-4657-b4ad-a8c624265d62} <Information> AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
```

The time in logs should be in UTC, and both clickhouse-server and minio have the same time in logs, but for some reason, minio mixed up timezones for this request

According to the [CI DB](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcnIEFTIG5hbWVfc3Vic3RyLAogICAgMzY1IEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQphbmQgdGVzdF9jb250ZXh0X3JhdyBsaWtlICclQWNjZXNzIERlbmllZC4sIGJ1Y2tldCB0ZXN0JScKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK), it happens in random tests 3 times in a month (a very rare failure)

**Comment by tavplubix** [comment]
Also, after `If the signature check failed ...` there should have been another message, but I don't see it. Maybe we have insufficient logging level for AWSClient: https://github.com/ClickHouse/aws-sdk-cpp/blob/aff9a9aa3d13683e607eea56177610d8c0cd11c4/src/aws-cpp-sdk-core/source/client/AWSClient.cpp#L212-L222

**Comment by CheSema** [comment]
It looks strange here:

case: https://d1k2gkhrlfqv31.cloudfront.net/clickhouse-test-reports-private/0/eb845094dc565f2d7fb7247e946c203bb3eb256c/stateless_tests__release__s3_storage__%5B1_2%5D.html
key: `tea-first-random-part/s3-disk/new-style-prefix/etk/zdrbyxtkzifydieexuzycxuwsajap`
ch date from log: `2024.08.06 14:58:46.430079`
date header in responce: `Tue, 06 Aug 2024 09:13:46 GMT`

case: https://d1k2gkhrlfqv31.cloudfront.net/clickhouse-test-reports-private/0/6c81fba9cf2b799e7929246ac13b11aebc438f16/stateless_tests__debug__s3_storage__%5B1_2%5D.html
key: `isa-first-random-part/s3-disk/new-style-prefix/eoe/ubhgyhybaemyltjiuellzekzjgfhn`
ch date from log: `2024.08.05 21:16:39.949492`
date header in responce: `Tue, 06 Aug 2024 03:16:39 GMT`

case: https://d1k2gkhrlfqv31.cloudfront.net/clickhouse-test-reports-private/0/45ba4403312219325c9f1ed42eab45c31d8fa3bd/stateless_tests__debug__s3_storage__%5B1_2%5D.html
key: `vcv-first-random-part/s3-disk/new-style-prefix/gjm/biszrdfmyoaqzenkhuhiscjakawax`
ch date from log: `2024.08.06 07:42:39.820959`
date header in responce: `Tue, 06 Aug 2024 02:42:39 GMT`

case https://s3.amazonaws.com/clickhouse-test-reports/67555/576e0952b51b5e0a0f2925baddb342689b771cb8/stateless_tests__debug__s3_storage__%5B1_2%5D.html
key: `jqe-first-random-part/new-style-prefix/non/nrnowtbezifzzmjnbutmlfmldhkkv`
ch date from log: `2024.08.05 02:23:08.162966`
date header in responce: `Sun, 04 Aug 2024 23:23:08 GMT`

header date comes from the minio server. Why it come from future and from the past as well?
CEST is 2 hours ahead of GMT.

**Comment by tavplubix** [comment]
> diff (ch - mino): 3h, 45m и 0.430079s . minio answered from the past.
```
2024.08.06 14:20:01.903732 [ 993 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Kathmandu'.
```
Asia/Kathmandu is UTC+5:45 (CEST+3:45)

> diff (ch - mino) -- 7h, 59m, 59.050508s, minio answered from the future.
```
2024.08.05 20:35:14.444015 [ 965 ] {} <Trace> Application: Initialized DateLUT with time zone 'America/Belize'.
```
America/Belize is UTC-6 (CEST-8)

> diff (ch - mino) 3h, 0m, 0.820959s, minio answered from the past.
```
2024.08.06 06:59:00.826257 [ 957 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Atyrau'.
```
Asia/Atyrau is UTC+5 (CEST+3)

**Comment by tavplubix** [comment]
> ch date from log: 2024.08.06 14:58:46.430079
> date header in responce: Tue, 06 Aug 2024 09:13:46 GMT
> diff (ch - mino): 3h, 45m и 0.430079s . minio answered from the past.

Hm, how did you get 3:45? The difference is 5:45, and it's exactly the offset from UTC. Same for other cases

**Comment by tavplubix** [comment]
I'm not sure if it's a minio issue, it's possible that ClickHouse sends wrong time in `x-amz-date` header. But still I have no idea why it happens sporadically and so rarely

**Comment by CheSema** [comment]
> > ch date from log: 2024.08.06 14:58:46.430079
> > date header in responce: Tue, 06 Aug 2024 09:13:46 GMT
> > diff (ch - mino): 3h, 45m и 0.430079s . minio answered from the past.
> 
> Hm, how did you get 3:45? The difference is 5:45, and it's exactly the offset from UTC. Same for other cases

I considered time in logs as CEST, but I thing that is wrong.

**Comment by tavplubix** [comment]
We randomize timezone globally, and we do it before running minio: https://github.com/ClickHouse/ClickHouse/blob/ebc05f53c3a282325fc6f621cdf2d918277b5d57/docker/test/stateless/run.sh#L15-L50

I guess there are two paths in the code (a normal one and another one for a corner case), and they handle time differently, and the corner-case-path performs extra conversion. I've checked aws client (`AWSAuth[EventStream]V4Signer::SignRequest`, `AWSAuthSigner::GetSigningTimestamp`, `DateTime::ToGmtString`, `DateTime::ConvertTimestampToGmtStruct`) and didn't find anything suspicious. Time to read the minio code?

**Comment by antonio2368** [comment]
It's strange how we get the generic `Exception name` and `Error message`. Specific errors should have a descriptive message so it should eliminate a lot of cases from minio code.
Also, the release is 2 years old so we should update it in any case.

**Comment by antonio2368** [comment]
I'll try adding minio audit logs webhook and store it inside ClickHouse instance

**Comment by antonio2368** [comment]
Didn't happen for almost [3 months](https://play.clickhouse.com/play?user=play#CldJVEgKICAgICcnIEFTIG5hbWVfc3Vic3RyLAogICAgMzY1IEFTIGludGVydmFsX2RheXMsCiAgICAoJ1N0YXRlbGVzcyB0ZXN0cyAoYXNhbiknLCAnU3RhdGVsZXNzIHRlc3RzIChhZGRyZXNzKScsICdTdGF0ZWxlc3MgdGVzdHMgKGFkZHJlc3MsIGFjdGlvbnMpJykgQVMgYmFja3BvcnRfYW5kX3JlbGVhc2Vfc3BlY2lmaWNfY2hlY2tzClNFTEVDVAogICAgdG9TdGFydE9mRGF5KGNoZWNrX3N0YXJ0X3RpbWUpIEFTIGQsCiAgICBjb3VudCgpLAogICAgZ3JvdXBVbmlxQXJyYXkocHVsbF9yZXF1ZXN0X251bWJlcikgQVMgcHJzLAogICAgYW55KHJlcG9ydF91cmwpCkZST00gY2hlY2tzCldIRVJFICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKHB1bGxfcmVxdWVzdF9udW1iZXIgTk9UIElOICgKICAgIFNFTEVDVCBwdWxsX3JlcXVlc3RfbnVtYmVyIEFTIHBybgogICAgRlJPTSBjaGVja3MKICAgIFdIRVJFIChwcm4gIT0gMCkgQU5EICgobm93KCkgLSB0b0ludGVydmFsRGF5KGludGVydmFsX2RheXMpKSA8PSBjaGVja19zdGFydF90aW1lKSBBTkQgKGNoZWNrX25hbWUgSU4gKGJhY2twb3J0X2FuZF9yZWxlYXNlX3NwZWNpZmljX2NoZWNrcykpCikpIEFORCAocG9zaXRpb24odGVzdF9uYW1lLCBuYW1lX3N1YnN0cikgPiAwKSBBTkQgKHRlc3Rfc3RhdHVzIElOICgnRkFJTCcsICdFUlJPUicsICdGTEFLWScpKQphbmQgdGVzdF9jb250ZXh0X3JhdyBsaWtlICclQWNjZXNzIERlbmllZC4sIGJ1Y2tldCB0ZXN0JScKR1JPVVAgQlkgZApPUkRFUiBCWSBkIERFU0MK)

Maybe update was enough
