### ISSUE TITLE
Segmentation fault Address: NULL pointer. Access: read. Unknown si_code.

### ISSUE THREAD

**Issue by SeayaWang985** [ClickHouse/ClickHouse#67890]
`2024.08.06 08:06:12.254879 [ 100260 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.08.06 08:06:12.254956 [ 100260 ] {} <Fatal> BaseDaemon: (version 24.1.5.6 (official build), build id: 214D08DCC9FBDDA4FF41FCB4C79044390694EB0B, git hash: 7f67181ff319e47c534edfa707f10ff0231b4183) (from thread 81082) Received signal 11
2024.08.06 08:06:12.255611 [ 100260 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.08.06 08:06:12.255641 [ 100260 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.08.06 08:06:12.255655 [ 100260 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000007212287 0x000000000c7e3d0d 0x0000000010ab3b2b 0x0000000010a82a01 0x0000000010a8f1b3 0x000000000c8e777e 0x000079f95ee94ac3 0x000079f95ef26850
2024.08.06 08:06:12.255665 [ 100260 ] {} <Fatal> BaseDaemon: ########################################
2024.08.06 08:06:12.255694 [ 100260 ] {} <Fatal> BaseDaemon: (version 24.1.5.6 (official build), build id: 214D08DCC9FBDDA4FF41FCB4C79044390694EB0B, git hash: 7f67181ff319e47c534edfa707f10ff0231b4183) (from thread 81082) (no query) Received sig
nal Segmentation fault (11)
2024.08.06 08:06:12.255727 [ 100260 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.08.06 08:06:12.255736 [ 100260 ] {} <Fatal> BaseDaemon: Stack trace: 0x0000000007212287 0x000000000c7e3d0d 0x0000000010ab3b2b 0x0000000010a82a01 0x0000000010a8f1b3 0x000000000c8e777e 0x000079f95ee94ac3 0x000079f95ef26850
2024.08.06 08:06:12.262284 [ 100260 ] {} <Fatal> BaseDaemon: 2. std::__murmur2_or_cityhash<unsigned long, 64ul>::operator()(void const*, unsigned long) @ 0x0000000007212287 in /usr/bin/clickhouse
2024.08.06 08:06:12.264530 [ 100260 ] {} <Fatal> BaseDaemon: 3. std::__hash_const_iterator<std::__hash_node<String, void*>*> std::__hash_table<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>::find<String>(String const&
) const @ 0x000000000c7e3d0d in /usr/bin/clickhouse
2024.08.06 08:06:12.266942 [ 100260 ] {} <Fatal> BaseDaemon: 4. DB::MySQLReplication::BinlogFromDispatcher::tryReadEvent(std::shared_ptr<DB::MySQLReplication::EventBase>&, unsigned long) @ 0x0000000010ab3b2b in /usr/bin/clickhouse
2024.08.06 08:06:12.267968 [ 100260 ] {} <Fatal> BaseDaemon: 5. DB::MaterializedMySQLSyncThread::synchronization() @ 0x0000000010a82a01 in /usr/bin/clickhouse
2024.08.06 08:06:12.271797 [ 100260 ] {} <Fatal> BaseDaemon: 6. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true>::ThreadFromGlobalPoolImpl<DB::MaterializedMySQLSyn
cThread::startSynchronization()::$_0>(DB::MaterializedMySQLSyncThread::startSynchronization()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000010a8f1b3 in /usr/bin/clickhouse
2024.08.06 08:06:12.272539 [ 100260 ] {} <Fatal> BaseDaemon: 7. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<vo
id>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000c8e777e in /usr/bin/clickhouse
2024.08.06 08:06:12.272561 [ 100260 ] {} <Fatal> BaseDaemon: 8. ? @ 0x000079f95ee94ac3
2024.08.06 08:06:12.272572 [ 100260 ] {} <Fatal> BaseDaemon: 9. ? @ 0x000079f95ef26850
2024.08.06 08:06:12.393357 [ 100260 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 4ACCCA9126B1079A8C964C8FACDB46D8)
2024.08.06 08:06:12.395569 [ 100260 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues`

**Comment by SeayaWang985** [comment]
@alexey-milovidov there are 20 restarts within two days, help me please, urgent

**Comment by Algunenano** [comment]
`24.1.5.6` is unsupported. You should upgrade to a supported release.

Also, you are using experimental features, so it'd help debugging this issue if you provided a reproducer (in a supported release)

**Comment by SeayaWang985** [comment]
@Algunenano Thanks for reply. What does a supported release mean？Which release I should upgrade to？

**Comment by Algunenano** [comment]
Supported means that they receive updates. If a version doesn't receive updates anymore it's highly unlikely that anybody would investigate any issues related to it unless it reproduces in a more recent version too. For experimental features, it's not just unlikely, it's pretty much 0%.

You can see the list of currently supported releases in https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/67949

**Comment by SeayaWang985** [comment]
Hi guys, thanks for your reply. I have upgraded to 24.7.2.13, and this issue appears again. 
ERROR LOGS：
` (version 24.7.2.13 (official build))
2024.08.07 01:53:07.839860 [ 166377 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.08.07 01:53:07.839944 [ 166377 ] {} <Fatal> BaseDaemon: (version 24.7.2.13 (official build), build id: 0F20207DBD896478C583762006592A5293673485, git hash: 6e41f601b2f025b0741da55d13287922eb28cf37) (from thread 147309) Received signal 11
2024.08.07 01:53:07.839960 [ 166377 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.08.07 01:53:07.839976 [ 166377 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.08.07 01:53:07.839990 [ 166377 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000d8b4ef2 0x00007bb1d1c42520 0x00000000079f508e 0x000000000d5dd4ed 0x0000000010de1cd4 0x0000000010dc0a94 0x000000000d6b30a3 0x00007bb1d1c94ac3 0x00007bb1d1d26850
2024.08.07 01:53:07.840000 [ 166377 ] {} <Fatal> BaseDaemon: ########################################
2024.08.07 01:53:07.840011 [ 166377 ] {} <Fatal> BaseDaemon: (version 24.7.2.13 (official build), build id: 0F20207DBD896478C583762006592A5293673485, git hash: 6e41f601b2f025b0741da55d13287922eb28cf37) (from thread 147309) (no query) Received signal Segmentation fault (
11)
2024.08.07 01:53:07.840026 [ 166377 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.08.07 01:53:07.840034 [ 166377 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000d8b4ef2 0x00007bb1d1c42520 0x00000000079f508e 0x000000000d5dd4ed 0x0000000010de1cd4 0x0000000010dc0a94 0x000000000d6b30a3 0x00007bb1d1c94ac3 0x00007bb1d1d26850
2024.08.07 01:53:07.840093 [ 166377 ] {} <Fatal> BaseDaemon: 0. signalHandler(int, siginfo_t*, void*) @ 0x000000000d8b4ef2
2024.08.07 01:53:07.840108 [ 166377 ] {} <Fatal> BaseDaemon: 1. ? @ 0x00007bb1d1c42520
2024.08.07 01:53:07.840129 [ 166377 ] {} <Fatal> BaseDaemon: 2. std::__murmur2_or_cityhash<unsigned long, 64ul>::operator()(void const*, unsigned long) @ 0x00000000079f508e
2024.08.07 01:53:07.841052 [ 166377 ] {} <Fatal> BaseDaemon: 3. std::__hash_const_iterator<std::__hash_node<String, void*>*> std::__hash_table<String, std::hash<String>, std::equal_to<String>, std::allocator<String>>::find<String>(String const&) const @ 0x000000000d5dd4
ed
2024.08.07 01:53:07.841944 [ 166377 ] {} <Fatal> BaseDaemon: 4. DB::MySQLReplication::BinlogFromDispatcher::tryReadEvent(std::shared_ptr<DB::MySQLReplication::EventBase>&, unsigned long) @ 0x0000000010de1cd4
2024.08.07 01:53:07.841975 [ 166377 ] {} <Fatal> BaseDaemon: 5. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::MaterializedMySQLSyncThread::startSynchr
onization()::$_0>(DB::MaterializedMySQLSyncThread::startSynchronization()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000010dc0a94
2024.08.07 01:53:07.841996 [ 166377 ] {} <Fatal> BaseDaemon: 6. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>
, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000d6b30a3
2024.08.07 01:53:07.842005 [ 166377 ] {} <Fatal> BaseDaemon: 7. ? @ 0x00007bb1d1c94ac3
2024.08.07 01:53:07.842011 [ 166377 ] {} <Fatal> BaseDaemon: 8. ? @ 0x00007bb1d1d26850
2024.08.07 01:53:07.966480 [ 166377 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 27B324E0F1926788FF4EE03DBFC3C184)
2024.08.07 01:53:07.966705 [ 166377 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2024.08.07 01:53:09.011517 [ 147533 ] {} <Error> MaterializedMySQLSyncThread: Code: 210. DB::Exception: Could not create: Wrong executed_gtid_set: 381c830b-9361-3e53-971f-9bf83e6705d3:5073-45150:793152-809046:1414174-285036295,8cea63a0-6579-3eee-9bb4-876f543927da:53018-
165949,901277fa-a2ca-3fb6-a896-d81ac0be3019:21540263-21785298,a3263595-97f4-11ee-b497-0242ac130002:1-139494 -> 381c830b-9361-3e53-971f-9bf83e6705d3:5073-45150:793152-809046:1414174-285036295,8cea63a0-6579-3eee-9bb4-876f543927da:53018-165949,901277fa-a2ca-3fb6-a896-d81ac0be3019:21540263-21785298,a3263595-97f4-11ee-b497-0242ac130002:1-139494. (NETWORK_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d5f551b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x00000000079f706c
2. DB::Exception::Exception<String const&, String>(int, FormatStringHelperImpl<std::type_identity<String const&>::type, std::type_identity<String>::type>, String const&, String&&) @ 0x00000000083d6b0b
3. DB::MySQLReplication::BinlogFromSocketFactory::createBinlog(String const&) @ 0x0000000010dda1d3
4. DB::MySQLReplication::BinlogClient::createBinlog(String const&, String const&, std::unordered_set<String, std::hash<String>, std::equal_to<String>, std::allocator<String>> const&, unsigned long, unsigned long) @ 0x0000000010dd3dc2
5. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<DB::MaterializedMySQLSyncThread::startSynchronization()::$_0>(DB::MaterializedMySQLSyncThread::startSynchronization()::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x0000000010dbfef2
6. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000d6b30a3
7. ? @ 0x00007bb1d1c94ac3
8. ? @ 0x00007bb1d1d26850
 (version 24.7.2.13 (official build))
2024.08.07 01:53:19.196967 [ 146631 ] {} <Fatal> Application: Child process was terminated by signal 11.
2024.08.07 01:53:49.345894 [ 166396 ] {} <Warning> Context: Delay accounting is not enabled, OSIOWaitMicroseconds will not be gathered. You can enable it using `echo 1 > /proc/sys/kernel/task_delayacct` or by using sysctl.`

**Comment by alexey-milovidov** [comment]
It isn't possible to help, because ClickHouse does not support MaterializedMySQL.

**Comment by SeayaWang985** [comment]
> It isn't possible to help, because ClickHouse does not support MaterializedMySQL.

Thanks anyway
