### ISSUE TITLE
Wrong query result with `query_plan_remove_redundant_sorting`

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#67906]
https://fiddle.clickhouse.com/e96a52c8-9b56-42f9-98de-b5b46dfc3289

**Comment by GrahamCampbell** [comment]
It looks like a bug in the optimizer that's removing sorting in subqueries when OFFSET is present and set to a value other than 0, which is not a safe optimization to apply.

**Comment by GrahamCampbell** [comment]
I believe https://github.com/ClickHouse/ClickHouse/pull/68071 may fix the issue.
