### ISSUE TITLE
Stateless test `03008_deduplication_mv_generates_several_blocks` is flaky (Timeout)

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#67903]
Examples:
https://s3.amazonaws.com/clickhouse-test-reports/0/3621b35591fb9a5769f27b27b11939aea5525060/stateless_tests__azure__asan__[2_4].html
https://s3.amazonaws.com/clickhouse-test-reports/0/59607413a03007a86a16ae18f9dac62cb350aba6/stateless_tests__azure__asan__[2_4].html
https://s3.amazonaws.com/clickhouse-test-reports/0/59607413a03007a86a16ae18f9dac62cb350aba6/stateless_tests__azure__asan__[1_4].html

[CI DB](https://play.clickhouse.com/play?user=play#U0VMRUNUIHB1bGxfcmVxdWVzdF9udW1iZXIsIGNoZWNrX3N0YXJ0X3RpbWUsIGNoZWNrX25hbWUsIHRlc3RfbmFtZSwgdGVzdF9zdGF0dXMsIGNoZWNrX3N0YXR1cywgcmVwb3J0X3VybApGUk9NIGNoZWNrcwpXSEVSRSAxCiAgICBBTkQgcHVsbF9yZXF1ZXN0X251bWJlciA9IDAKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnU0tJUFBFRCcKICAgIEFORCB0ZXN0X3N0YXR1cyAhPSAnT0snCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfbmFtZSBsaWtlICclMDMwMDhfZGVkdXBsaWNhdGlvbl9tdiUnCiAgICBBTkQgY2hlY2tfc3RhcnRfdGltZSA+IG5vdygpIC0gaW50ZXJ2YWwgMiBtb250aApPUkRFUiBCWSBjaGVja19zdGFydF90aW1lIGRlc2MsIGNoZWNrX25hbWUsIHRlc3RfbmFtZQ==)

**Comment by KochetovNicolai** [comment]
Old one

**Comment by CheSema** [comment]
That tests are heavy, this is why they are marked as `no-azure-blob-storage`.
That examples are old.
