### ISSUE TITLE
Some JOIN result changed between 24.6 and 24.7

### ISSUE THREAD

**Issue by eguinane** [ClickHouse/ClickHouse#67915]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

> Put your company name or project description here

**Describe what's wrong**

Some query result changed between version 24.6.2.17  and 24.7.2.13 ( after playing with your fiddle, it seems it changed between 24.6.2.17 and 24.6.3.47 ).

24.7.2.13
https://fiddle.clickhouse.com/9bb8f15a-81fd-4222-abff-946df87f3276

24.6.3.47
https://fiddle.clickhouse.com/36f2093d-10ea-40d5-b806-72736849cfdf

24.6.2.17
https://fiddle.clickhouse.com/4736c90a-6b8f-4f00-b8af-48f14d5e230b

**Does it reproduce on the most recent release?**

It reproduce on 24.7.2.13.

**Enable crash reporting**

Not a crash

* Which ClickHouse server version to use : 24.6.2.17 and 24.7.2.13
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

```sql
-- CREATE TABLE statements for all tables involved
CREATE TABLE default.table_a (
    pk_a UInt32,
    fk_a UInt32,
    qualifier_a Nullable(String)
) ENGINE=MergeTree()
ORDER BY ( pk_a );

CREATE TABLE default.table_b (
    pk_b UInt32,
    ressource_b Nullable(String)
) ENGINE=MergeTree()
ORDER BY ( pk_b );

-- Sample data for all these tables
INSERT INTO table_a VALUES (30, 200, NULL);
INSERT INTO table_b VALUES (200, 'FOOBIX');

-- Queries to run that lead to an unexpected result
SELECT
a.pk_a,
a.fk_a,
a.qualifier_a,
b.pk_b,
b.ressource_b
FROM default.table_a a
JOIN default.table_b b ON table_b.pk_b = table_a.fk_a AND NOT ( a.qualifier_a = 'FOOBAR' AND a.qualifier_a IS NOT NULL);

-- ON version 24.6.2.17
-- ┌─pk_a─┬─fk_a─┬─qualifier_a─┬─pk_b─┬─ressource_b─┐
-- │   30 │  200 │ ᴺᵁᴸᴸ        │  200 │ FOOBIX      │
-- └──────┴──────┴─────────────┴──────┴─────────────┘
-- 1 row in set. Elapsed: 0.003 sec.

-- ON version 24.7.2.13
-- Ok.
--
-- 0 rows in set. Elapsed: 0.003 sec.
```

**Expected behavior**

To have the same result between versions.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by sigxcpu76** [comment]
Looks like it is working again in `latest`: https://fiddle.clickhouse.com/f3ae16c3-bd58-4da4-a893-e9506bac1d12

**Comment by Algunenano** [comment]
@vdimir Seems related to the latest changes to joinOnNulls. Works fine with the old analyzer and if you disable `LogicalExpressionOptimizerPass` in code.
