### ISSUE TITLE
Cannot find exact size of array in rowbinary format.

### ISSUE THREAD

**Issue by justmark0** [ClickHouse/ClickHouse#67929]
**Company or project name**

I want to write [rowbinary](https://clickhouse.com/docs/en/interfaces/formats#rowbinary) to structure mapping in [Julia](https://julialang.org/).

**Describe the unexpected behaviour**
When selecting `SELECT [1, 2, 3]::Array(Int32)` to rowbinary length (first bytes) can be various sizes like int8, int16... . So you cannot identify the end of the length "header" and start of data.

**How to reproduce**
ClickHouse server version: `22.1.3.7`
Here is code to reproduce:
```
import requests

headers = {
    "X-ClickHouse-Format": "RowBinary",
    "X-ClickHouse-Database": "default",
    "X-ClickHouse-User": "default",
    "X-ClickHouse-Key": "",
    "Content-Type": "text/plain; charset=UTF-8",
}

def req(query):
    return requests.post(
        "http://127.0.0.1:8123",
        headers=headers,
        params={"query": query}
    ).content

query = f"SELECT {str([-1] * 1)}::Array(Int32)"  # 'SELECT [-1]::Array(Int32)'
print(f"bytes: {req(query)}")  # bytes: b'\x01\xff\xff\xff\xff'

query = f"SELECT {str([0] * 5)}::Array(Int32)"  # 'SELECT [0, 0, 0, 0, 0]::Array(Int32)'
print(f"bytes: {req(query)}")  # bytes: b'\x05\x00\x00\x00\x00\x00\x00...'
#                                           ^ length is int8

query = f"SELECT {str([0] * 1024)}::Array(Int32)"
print(f"bytes: {req(query)}")  # bytes: b'\x80\x08\x00\x00\x00\x00\x00...'
#                                           ^----^ length is int16
```

**Expected behavior**
I've expected to see at least int32, int64 of length or some other solution to determine amount of elements in array.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/interfaces/formats#rowbinary

LEB128 https://en.wikipedia.org/wiki/LEB128
