### ISSUE TITLE
Support `ALTER USER x ADD SETTINGS PROFILE abc` syntax

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#67948]
We have syntax
``` sql
CREATE SETTINGS PROFILE abc SETTING readonly=1 TO my_user
```
It is convenient to create a setting profile and append it to user configuration.
When we want to add the same setting profile to another user there is no convenient way and we need to run ALTER USER with all the setting profile that already exist for this user to not drop existing configuration. It is not so convenient for most common use case so subj.

**Comment by nikitamikhaylov** [comment]
We already have a PR for it: https://github.com/ClickHouse/ClickHouse/pull/57421
