### ISSUE TITLE
Consider removing `MaterializedMySQL`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#67949]
The code has low quality, the contributor disappeared, and it has not been supported for years. It didn't go out of the experimental status.

**Comment by dragon-wzl** [comment]
oh，no

**Comment by alexey-milovidov** [comment]
@dragon-wzl, what will you do to save `MaterializedMySQL`?
Maybe you have friends who are C++ engineers, and they can fix a null pointer dereference?

**Comment by cemelo** [comment]
@alexey-milovidov I'm assuming this wouldn't apply to MySQL?

My two cents: I think it is a good idea to remove it. I've been experimenting for a while with MaterializedMySQL and an RDS instance, and it hasn't been a smooth sail.

**Comment by alexey-milovidov** [comment]
Yes, only MaterializedMySQL is under concern.

MySQL engine, table function, and even the MySQL wire protocol are fine.
