### ISSUE TITLE
Materialized View doesnot get REFRESHED on insertion into SECOND table in the MV JOIN

### ISSUE THREAD

**Issue by raghukn** [ClickHouse/ClickHouse#67967]
(you don't have to strictly follow this form)

**Company or project name**
Project Rebase

**Describe the unexpected behaviour**
I have a MV created on a JOIN between 2 tables. Rows insert into the SECOND table in the JOIN do not trigger REFRESH of the MV. Only when ROW for FIRST Table is inserted, REFRESH of MV happens

**How to reproduce**
https://fiddle.clickhouse.com/75f74af8-41f0-4320-88c1-bb16c1bc1a06

**Expected behavior**
The MV should get populated when either of the Tables in the Join changes.

**Error message and/or stacktrace**
NA

**Additional context**
 If this is NOT supported, then the result of the overall MV can go Stale if other tables in the JOIN change

**Comment by alsugiliazova** [comment]
MV searches for the first real table in the From section and triggers on inserts into this table only.

From this doc: https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by raghukn** [comment]
@alsugiliazova , thanks! 

Your document is very useful
