### ISSUE TITLE
Nullptr dereference in FindOriginalNodeForOutputName

### ISSUE THREAD

**Issue by DimasKovas** [ClickHouse/ClickHouse#68001]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

Yandex

**Describe what's wrong**

ClickHouse crashes on following query:

23.8: https://fiddle.clickhouse.com/7df5d296-fc77-4317-b5b4-e35bc3712a8f
24.4: https://fiddle.clickhouse.com/d8af19d1-84ad-480e-973f-43834111c608

**Does it reproduce on the most recent release?**

No. These versions are affected:

- 23.8 LTS (still supported)
- 24.4 (not supported)

**Comment by Algunenano** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/64767 but the backports are incomplete.

**Comment by devcrafter** [comment]
> Fixed by #64767 but the backports are incomplete.

Thanks for the reminder. The backport is done - https://github.com/ClickHouse/ClickHouse/pull/64997
