### ISSUE TITLE
When deploying clickhouse using the official docker image, it fails to start on the arm64 architecture starting from version 23.5

### ISSUE THREAD

**Issue by llody55** [ClickHouse/ClickHouse#68029]
### Company or project name

When deploying clickhouse using the official docker image, it fails to start on the arm64 architecture starting from version 23.5

### system structure
`root@mysql:~/clickhouse-stable# uname -a
Linux mysql 5.15.0-117-generic #127-Ubuntu SMP Mon Jul 8 13:10:05 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`

### 23.4 Startup Normally
`root@mysql:~/clickhouse-stable# docker run -it --rm  --name clickhouse-server -p 8123:8123 -p 9009:9009 -p 9091:9000 --ulimit nofile=262144:262144 --volume=/data/clickhouse/data:/var/lib/clickhouse --volume=/data/clickhouse/logs:/var/log/clickhouse-server --volume=/etc/clickhouse-server/config.xml:/etc/clickhouse-server/config.xml --volume=/etc/clickhouse-server/users.xml:/etc/clickhouse-server/users.xml --volume=/etc/localtime:/etc/localtime  clickhouse/clickhouse-server:23.4
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
2024.08.08 08:40:20.978062 [ 1 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2024.08.08 08:40:21.046507 [ 1 ] {} <Information> Application: Starting ClickHouse 23.4.6.25 (revision: 54473, git hash: a06848b17707538e31013bfd795809a37b096a8a, build id: 7887AFECC97FF8F7C0CAC0256FA6F9229133F00A), PID 1
2024.08.08 08:40:21.046726 [ 1 ] {} <Information> Application: starting up
2024.08.08 08:40:21.046762 [ 1 ] {} <Information> Application: OS name: Linux, version: 5.15.0-117-generic, architecture: aarch64
2024.08.08 08:40:21.053523 [ 1 ] {} <Information> Application: Available RAM: 125.64 GiB; physical cores: 32; logical cores: 32.
2024.08.08 08:40:21.053657 [ 1 ] {} <Warning> Context: Linux is not using a fast clock source. Performance can be degraded. Check /sys/devices/system/clocksource/clocksource0/current_clocksource
`
### 23.5 Startup Failure
`root@mysql:~/clickhouse-stable# docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@mysql:~/clickhouse-stable# docker run -it --rm  --name clickhouse-server -p 8123:8123 -p 9009:9009 -p 9091:9000 --ulimit nofile=262144:262144 --volume=/data/clickhouse/data:/var/lib/clickhouse --volume=/data/clickhouse/logs:/var/log/clickhouse-server --volume=/etc/clickhouse-server/config.xml:/etc/clickhouse-server/config.xml --volume=/etc/clickhouse-server/users.xml:/etc/clickhouse-server/users.xml --volume=/etc/localtime:/etc/localtime  clickhouse/clickhouse-server:23.5
Unable to find image 'clickhouse/clickhouse-server:23.5' locally
23.5: Pulling from clickhouse/clickhouse-server
82d728d38b98: Already exists 
76c04f07236f: Pull complete 
79761bf4600e: Pull complete 
4f4fb700ef54: Pull complete 
1f21f802806d: Pull complete 
a3876cac8d37: Pull complete 
4494409728e3: Pull complete 
7b0d85ac5b9e: Pull complete 
b816ca5aecc6: Pull complete 
Digest: sha256:faec412b736b5ee9e4d7430dc93e7b7ecaf9d98acf623cfd945881c9727dc8ee
Status: Downloaded newer image for clickhouse/clickhouse-server:23.5
/entrypoint.sh: line 40:    23 Illegal instruction     (core dumped) clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key='storage_configuration.disks.*.path'
/entrypoint.sh: line 41:    25 Illegal instruction     (core dumped) clickhouse extract-from-config --config-file "$CLICKHOUSE_CONFIG" --key='storage_configuration.disks.*.metadata_path'
root@mysql:~/clickhouse-stable# docker ps -a`

**Comment by den-crane** [comment]
Check 

```
cat /proc/cpuinfo |grep Features|uniq
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```

Do you see `lrcpc` there or not?

--------

https://github.com/ClickHouse/ClickHouse/issues/49814#issuecomment-1546781571

https://github.com/ClickHouse/ClickHouse/issues/54911

https://github.com/ClickHouse/ClickHouse/issues/53820#issuecomment-1697419011

**Comment by llody55** [comment]
@den-crane There is indeed no **lrcpc** instruction set
```
root@mysql:~/clickhouse-stable# cat /proc/cpuinfo |grep Features|uniq
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
```
Can you explain why 23.3~23.4 can run on ARM CPU without lrcpc function, but 23.5 and above cannot?

**Comment by rschu1ze** [comment]
I don't find the PR that introduced the lrcpc dependency right now, but this flag was added for performance reasons somewhen last year. It is optional in ARM v8.2, and mandatory in ARM v8.3.

Btw., https://hub.docker.com/r/clickhouse/clickhouse-server/ says:

```
Compatibility

    The amd64 image requires support for [SSE3 instructions⁠](https://en.wikipedia.org/wiki/SSE3)

. Virtually all x86 CPUs after 2005 support SSE3.
The arm64 image requires support for the [ARMv8.2-A architecture⁠](https://en.wikipedia.org/wiki/AArch64#ARMv8.2-A)
. Most ARM CPUs after 2017 support ARMv8.2-A. A notable exception is Raspberry Pi 4 from 2019 whose CPU only supports ARMv8.0-A.
```

To download and run a version of ClickHouse that requires only ARM v8.0 (which is quite ancient), run `curl https://clickhouse.com/ | sh`.

**Comment by llody55** [comment]
@den-crane @rschu1ze Is there any way to use the new version of ClickHouse in an older ARM64 version? Or can I temporarily turn off or not use the lrcpc instruction set?

**Comment by rschu1ze** [comment]
> @den-crane @rschu1ze Is there any way to use the new version of ClickHouse in an older ARM64 version? Or can I temporarily turn off or not use the lrcpc instruction set?

To download and run a version of ClickHouse that requires only ARM v8.0 (which is quite ancient), run curl https://clickhouse.com/ | sh.

**Comment by jordanfung** [comment]
> To download and run a version of ClickHouse that requires only ARM v8.0 (which is quite ancient), run curl https://clickhouse.com/ | sh.

Hi rschu1ze, do you know where can I download a LTS version of ClickHouse that requires only ARM v8.0 pls?

**Comment by rschu1ze** [comment]
As far as I know, ARM v8.0 builds are only provided for the `master` branch.

It is really simple to compile the ClickHouse code by yourself. [Here](https://clickhouse.com/docs/en/development/developer-instruction) is a tutorial. Just make sure to check out v24.8 (the last LTS version) and pass `-DNO_ARMV81_OR_HIGHER=1` to CMake.
