### ISSUE TITLE
Please add more instructions about how to specify the HNSW parameters when building and querying the usearch ANN index

### ISSUE THREAD

**Issue by nkg114mc** [ClickHouse/ClickHouse#68059]
**Company or project name**
Put your company name or project description here

**Describe the issue**

I am trying to follow this readme document (https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/engines/table-engines/mergetree-family/annindexes.md) to create ANN index for my embedding table. I am not sure if it is because document is incomplete or the implementation is incomplete. Would you mind to help on the following questions?

When creating a usearch type index, whose underlying algorithm is HNSW:
1) How to specify the indexing building parameters like `M` or `efConstruction`? I see there are only two parameters accepted: `Distance` and `ScalarKind`. Are they specified in some global setting variables that need to be set with `SET` statement. If so, what are the variable names? Can you add more examples to the document?

(Note that in unsearch, they have those two parameters in their constructor. See this two line in the python example: https://github.com/unum-cloud/usearch/tree/main/python  See the `connectivity` and `expansion_add`)

2) What is the variable of query parameter that need to specify in the SETTING statement? In HNSW, user can specify `efSearch` parameter for the query. This can obviously be set in the SETTING statement of each query (For example, when using type Annoy, the query parameter name is `annoy_index_search_k_nodes`).

So, if I use usearch, what's the variable name should be set in the SETTING statement? 
```
SELECT *
FROM my_table_name
ORDER BY L2Distance(vectors, [1, 2, 3])
LIMIT N
SETTINGS <efsearch_parameter_variable_name?>=100;
```

Can you add these information into that readme file?

**Comment by alexey-milovidov** [comment]
But we don't support HNSW.

**Comment by nkg114mc** [comment]
You do support **usearch**, right? Usearch implemented the HNSW algorithm. I got this information from this github issue: 
https://github.com/ClickHouse/ClickHouse/issues/66202

See these two comments:
https://github.com/ClickHouse/ClickHouse/issues/66202#issuecomment-2244145952
https://github.com/ClickHouse/ClickHouse/issues/66202#issuecomment-2244673825

Relevant documentation and PR: 
https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/engines/table-engines/mergetree-family/annindexes.md
https://github.com/ClickHouse/ClickHouse/pull/53447

@rschu1ze  @jiebin Would you mind to confirm that, is clickhouse still support "USearch"?

> But we don't support HNSW.

**Comment by rschu1ze** [comment]
Annoy and usearch indexes in ClickHouse don't support specifying HNSW-parameters.

The successor implementation will, see [here](https://github.com/ClickHouse/ClickHouse/pull/63675), in particular [this commit](https://github.com/ClickHouse/ClickHouse/pull/63675/commits/5c3532428f3c220397a36d9f92ccc8ba5ad4cdc1).

**Comment by nkg114mc** [comment]
Thank you so much for your reply, @rschu1ze Looking forward for the new implementation!

BTW, would you mind to take a look at my another issue as well (https://github.com/ClickHouse/ClickHouse/issues/68070) ? I think it is probably also related to your rework on vector similarity search?

If you know the reason (for example, feature flag was turned-off, etc.), please comment and close that issue. Thanks in advance!

**Comment by alexey-milovidov** [comment]
@nkg114mc, these features are under development, and it does not make sense to use them for now (too early).

**Comment by nkg114mc** [comment]
> @nkg114mc, these features are under development, and it does not make sense to use them for now (too early).

Got it. Thank you very much for the explanation.
