### ISSUE TITLE
Automatically handle IPv4 mapped IPv6 in ip_trie dict

### ISSUE THREAD

**Issue by champtar** [ClickHouse/ClickHouse#6806]
**Use case**
With current ip_trie,
1) `8.8.8.8` match `8.8.8.8/32`
2) `::ffff:8.8.8.8` match `::ffff:8.8.8.8/128`
3) `8.8.8.8` doesn't match `::ffff:8.8.8.8/128`
4) `::ffff:8.8.8.8` doesn't match `8.8.8.8/32`

To simplify my schema and queries, I store all IPs as IPv6, but it would be great to support case 4)
to be able to have a dict like
```
prefix,name
"8.8.8.8/32","google dns"
```
But do queries like
```
SELECT dictGetString('hub', 'name', tuple(myipv6)) ...
```
where `myipv6` is an `IPv6` or `FixedString(16)`

**Describe the solution you'd like**
When building the ip_trie, automatically convert IPv4 mapped IPv6 subnet to IPv4 subnet
(`::ffff:8.8.8.8/128` -> `8.8.8.8/32`)
When querying (dictGetT), automatically convert IPv4 mapped IPv6
(`::ffff:8.8.8.8` -> `8.8.8.8`)

**Current workaround**
Put IPv6 ranges instead of IPv4 ranges in the dict, ie
`::ffff:8.8.8.8/128` instead of `8.8.8.8/32`

**Comment by alexey-milovidov** [comment]
Fixed by @vdimir in #16804, starting from version 20.13-testing.
