### ISSUE TITLE
cmake could not find llvm

### ISSUE THREAD

**Issue by mkabilov** [ClickHouse/ClickHouse#6807]
For some reason cmake could not find llvm, despite the fact I have it installed on my system:
```
$ llvm-config --version
7.1.0
```

**Operating system**
Gentoo Base System release 2.6

**Cmake version**
cmake version 3.14.6

**Ninja version**
1.8.2

**Compiler name and version**
gcc 8.3.0

**Full cmake and/or ninja output**
[cmake.out.txt](https://github.com/yandex/ClickHouse/files/3571787/cmake.out.txt)

clickhouse master branch, commit 843f8303b019b3cb7d04ec20d4d0387a1e9f601a

**Comment by proller** [comment]
Do you really need llvm for your build?
Actual problem is:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CYRUS_SASL_SHARED_LIB (ADVANCED)
    linked by target "orc" in directory /home/murat.kabilov/ClickHouse/contrib/orc/c++/src

**Comment by ildus** [comment]
Yeah, problem with SASL is there, but still, it could not find LLVM.

**Comment by proller** [comment]
fixed here - https://github.com/yandex/ClickHouse/commit/54a5b801b708701b1ddbda95887465b9f7ae5740#diff-4f3f04aa07e7cdba3c4a995ef7e5c85dR22

**Comment by alexey-milovidov** [comment]
We don't depend on system LLVM anymore: https://github.com/ClickHouse/ClickHouse/pull/8258
