### ISSUE TITLE
Keep getting error `Only literals can be skip index arguments` when creating a table with vector search index

### ISSUE THREAD

**Issue by nkg114mc** [ClickHouse/ClickHouse#68070]
### Question

Hi, 

I am trying to create a table with an Array column and an index for that column. I use the following SQL statement:
```
CREATE TABLE items (id UInt32, embedding Array(Float32), INDEX `myindex` embedding TYPE usearch(cosineDistance, f32)) ENGINE = MergeTree ORDER BY id;
```
But somehow the client keep reporting the following error:
```
Received exception from server (version 24.8.1):
Code: 80. DB::Exception: Received from localhost:9000. DB::Exception: Only literals can be skip index arguments. (INCORRECT_QUERY)
```
The error remain the same even I switched to another type of index: annoy. What's exact wrong with my SQL statement? What does exception message actually mean?

**Comment by alexey-milovidov** [comment]
Vector search indices are not implemented and not supported.

**Comment by nkg114mc** [comment]
> Vector search indices are not implemented and not supported.

I am confused. They have been introduced in the official site blogs, aren't they?
https://clickhouse.com/blog/vector-search-clickhouse-p1
https://clickhouse.com/blog/vector-search-clickhouse-p2

The second blog use one subsection to introduce "Approximate Nearest Neighbour (Annoy)". I know it is experimental, but at least it was not under a "not implemented and not supported" status, is it?

**Comment by alexey-milovidov** [comment]
We don't support experimental features.

**Comment by rschu1ze** [comment]
I added support for above syntax in this [commit](https://github.com/ClickHouse/ClickHouse/pull/63675/commits/09fdba640fa29303838c51e0fbf30b2d560751c1) (part of the new [vector similarity index](https://github.com/ClickHouse/ClickHouse/pull/63675)).

**Comment by nkg114mc** [comment]
> I added support for above syntax in this [commit](https://github.com/ClickHouse/ClickHouse/pull/63675/commits/09fdba640fa29303838c51e0fbf30b2d560751c1) (part of the new [vector similarity index](https://github.com/ClickHouse/ClickHouse/pull/63675)).

Thanks for your reply! Has this commit been merged?

**Comment by rschu1ze** [comment]
Sure. It will be merged once the PR is merged. As a workaround, you can use quoting:

```sql
CREATE TABLE items (id UInt32, embedding Array(Float32), INDEX `myindex` embedding TYPE usearch(`cosineDistance`, `f32`)) ENGINE = MergeTree ORDER BY id;
```
