### ISSUE TITLE
After upgrading from version 22.3 to 22.7, an error occurred during the query：:Exception: Unknown codec family code: 1: (while reading column ss_data_source): While executing MergeTreeInOrder. (UNKNOWN_CODEC) (version 22.7.7.24 (official build))

### ISSUE THREAD

**Issue by SoaringCode** [ClickHouse/ClickHouse#68083]
### Cause: java.sql.BatchUpdateException: Code: 432. DB::Exception: Unknown codec family code: 1: (while reading column ss_data_source): While executing MergeTreeInOrder. (UNKNOWN_CODEC) (version 22.7.7.24 (official build))
, server ClickHouseNode [uri=http://192.168.50.61:8123/astrolabe, options={socket_timeout=300000,connection_timeout=300000,maxPoolSize=50,dataTransferTimeout=300000}]@1060129081
; bad SQL grammar []; nested exception is java.sql.BatchUpdateException: Code: 432. DB::Exception: Unknown codec family code: 1: (while reading column ss_data_source): While executing MergeTreeInOrder. (UNKNOWN_CODEC) (version 22.7.7.24 (official build))
, server ClickHouseNode [uri=http://192.168.50.61:8123/astrolabe, options={socket_timeout=300000,connection_timeout=300000,maxPoolSize=50,dataTransferTimeout=300000}]@1060129081

**Comment by alexey-milovidov** [comment]
Upgrade to the latest version 24.7 and check without using the Java library.

**Comment by SoaringCode** [comment]
Still reporting errors while executing on the command line：
0 rows in set. Elapsed: 0.010 sec. 

Received exception from server (version 22.7.7):
Code: 432. DB::Exception: Received from 192.168.50.61:9000. DB::Exception: Unknown codec family code: 1: (while reading column ss_data_source): While executing MergeTreeThread. (UNKNOWN_CODEC)

**Comment by SoaringCode** [comment]
> Upgrade to the latest version 24.7 and check without using the Java library.

Still reporting errors while executing on the command line：
0 rows in set. Elapsed: 0.010 sec.

Received exception from server (version 22.7.7):
Code: 432. DB::Exception: Received from 192.168.50.61:9000. DB::Exception: Unknown codec family code: 1: (while reading column ss_data_source): While executing MergeTreeThread. (UNKNOWN_CODEC)

**Comment by alexey-milovidov** [comment]
This is 22.7, not 24.7.
