### ISSUE TITLE
Concurrent queries performance degradation

### ISSUE THREAD

**Issue by qietingfengling** [ClickHouse/ClickHouse#6809]
Is the clickhouse query serial? I have 10 nodes, and the two queries are sent to different nodes. It is found that the execution time of one query is greatly affected by the execution time of another query. The distributed table engine is used. For example, the A query needs to be searched for 100ms separately, and the B query needs to be searched for 3s. When the B query is triggered, the A query is triggered at the same time, and the query time of the A query is slowed down a lot.

**Comment by filimonov** [comment]
It is expected. ClickHouse uses server resources very efficiently. When you run single query - it uses 100% of your server resources. If you run 2 queries in parallel - each query can get about 50%, and will be ~ twice slower.

**Comment by qietingfengling** [comment]
I have 16 cores per server. I observed that when running a query, there is often only a single cpu usage rate higher. Isn't clickhouse useful of all cpu resources?

**Comment by den-crane** [comment]
It could be bounded by disk IO (check `sar -d 1 100` or network check `iftop`

**Comment by amberjain22** [comment]
i am observing the same issue
