### ISSUE TITLE
read exception

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#68101]
version: 20.8.11.17

2024.08.09 14:55:10.698898 [ 54494 ] {88ec3672-c603-401d-9aaa-391c6a5593ff} <Error> executeQuery: Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 60692. Bytes expected: 204924.: while receiving packet from chi-ck-bq0jawlys4-3-1:9000: While executing Remote (version 20.8.11.17 (official build)) (from 10.207.32.100:44400) (in query: select  ,,,,,,,,,,,,,,,,,,;), Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18cd2050 in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe63232d in /usr/bin/clickhouse
2. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0xe67656f in /usr/bin/clickhouse
3. DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&) @ 0x1550b1c0 in /usr/bin/clickhouse
4. DB::CompressedReadBuffer::nextImpl() @ 0x1550954e in /usr/bin/clickhouse
5. DB::ReadBuffer::readStrict(char*, unsigned long) @ 0xe6765f5 in /usr/bin/clickhouse
6. ? @ 0x15644d8e in /usr/bin/clickhouse
7. DB::DataTypeString::deserializeBinaryBulk(DB::IColumn&, DB::ReadBuffer&, unsigned long, double) const @ 0x156476a5 in /usr/bin/clickhouse
8. DB::NativeBlockInputStream::readData(DB::IDataType const&, DB::IColumn&, DB::ReadBuffer&, unsigned long, double) @ 0x15bcabd8 in /usr/bin/clickhouse
9. DB::NativeBlockInputStream::readImpl() @ 0x15bcb93f in /usr/bin/clickhouse
10. DB::IBlockInputStream::read() @ 0x155611cd in /usr/bin/clickhouse
11. DB::Connection::receiveDataImpl(std::__1::shared_ptr<DB::IBlockInputStream>&) @ 0x1630c88e in /usr/bin/clickhouse
12. DB::Connection::receivePacket() @ 0x16310654 in /usr/bin/clickhouse
13. DB::MultiplexedConnections::receivePacket() @ 0x1632cf7a in /usr/bin/clickhouse
14. DB::RemoteQueryExecutor::read() @ 0x155798a4 in /usr/bin/clickhouse
15. DB::RemoteSource::generate() @ 0x1660f5c4 in /usr/bin/clickhouse
16. DB::ISource::work() @ 0x163e821b in /usr/bin/clickhouse
17. DB::SourceWithProgress::work() @ 0x16615de7 in /usr/bin/clickhouse
18. ? @ 0x1641d9a0 in /usr/bin/clickhouse
19. ? @ 0x16421c7d in /usr/bin/clickhouse
20. ? @ 0x164225a6 in /usr/bin/clickhouse
21. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0xe65fba7 in /usr/bin/clickhouse
22. ? @ 0xe65e093 in /usr/bin/clickhouse
23. start_thread @ 0x9609 in /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
24. clone @ 0x122293 in /usr/lib/x86_64-linux-gnu/libc-2.31.so

**Comment by alexey-milovidov** [comment]
This is normal when a network connection is interrupted.

PS. You are using a 4-year old version and also trying to hide the query.
