### ISSUE TITLE
Polygon is not valid: Geometry has spikes

### ISSUE THREAD

**Issue by zhongyuankai** [ClickHouse/ClickHouse#68100]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
In the following test, the query was normal before version v21.12.4.1, but after version v22.1, will throw an exception.
```
DB::Exception: Received from localhost:9000. DB::Exception: Polygon is not valid: Geometry has spikes. A spike point was found with apex at (113.886, 23.0326)
```

**How to reproduce**
Before v21.12.4.1:
https://fiddle.clickhouse.com/21e207b5-870f-4211-8d38-1fd244833555

After v22.1:
https://fiddle.clickhouse.com/2477d0e7-d98e-4719-8ec3-e4b9c6b5ee6c

**Comment by den-crane** [comment]
[set validate_polygons=0;](https://fiddle.clickhouse.com/363ff4c3-8f5d-4f68-9a13-80715780aeaf)

* https://github.com/ClickHouse/ClickHouse/pull/26113

**Comment by alexey-milovidov** [comment]
It was modified specifically to prevent spikes.
