### ISSUE TITLE
Materialized view are not aggregating properly

### ISSUE THREAD

**Issue by AdvaithD** [ClickHouse/ClickHouse#68111]
**Describe the unexpected behaviour**
Materialized view on top of the following root table
```
CREATE TABLE IF NOT EXISTS trades (
    dex LowCardinality(String),
    trader String,
    from_token String,
    to_token String,
    amount_in UInt128,
    amount_out UInt128,
    slot UInt64,
    tx_signature String,
    timestamp UInt64,
    base_token_address Nullable(String),
    base_token_liquidity Nullable(UInt128),
    quote_token_address Nullable(String),
    quote_token_liquidity Nullable(UInt128),
    pool_base_vault Nullable(String),
    pool_quote_vault Nullable(String),
    pool_address String
)
ENGINE = ReplacingMergeTree()
PRIMARY KEY (pool_address, timestamp, tx_signature)
```

Views:
```
CREATE TABLE IF NOT EXISTS trades_5m_mv
(
    dex LowCardinality(String),
    pool_address String,
    token_address String,
    time_bucket DateTime,
    total_vol_in_sol AggregateFunction(sum, Float64),
    total_trades AggregateFunction(count),
    number_of_buys AggregateFunction(sum, UInt8),
    number_of_sells AggregateFunction(sum, UInt8),
    unique_traders AggregateFunction(uniq, String),
    last_from_token AggregateFunction(argMax, String, Tuple(UInt64, UInt64)),
    last_to_token AggregateFunction(argMax, String, Tuple(UInt64, UInt64)),
    last_amount_in AggregateFunction(argMax, UInt128, Tuple(UInt64, UInt64)),
    last_amount_out AggregateFunction(argMax, UInt128, Tuple(UInt64, UInt64))
)
ENGINE = AggregatingMergeTree()
ORDER BY (dex, pool_address, token_address, time_bucket)
PARTITION BY toYYYYMMDD(time_bucket);

CREATE MATERIALIZED VIEW IF NOT EXISTS trades_5m_mv_view
TO trades_5m_mv
AS
WITH
    'So11111111111111111111111111111111111111112' AS sol_address
SELECT
    dex,
    pool_address,
    if(from_token = sol_address, to_token, from_token) AS token_address,
    toStartOfInterval(fromUnixTimestamp64Milli(timestamp * 1000), INTERVAL 5 MINUTE) AS time_bucket,
    sumState(if(from_token = sol_address OR to_token = sol_address, toFloat64(if(from_token = sol_address, amount_in, amount_out)) / 1e9, 0)) AS total_vol_in_sol,
    countState() AS total_trades,
    sumState(toUInt8(from_token = sol_address)) AS number_of_buys,
    sumState(toUInt8(to_token = sol_address)) AS number_of_sells,
    uniqState(trader) AS unique_traders,
    argMaxState(from_token, (timestamp, slot)) AS last_from_token,
    argMaxState(to_token, (timestamp, slot)) AS last_to_token,
    argMaxState(amount_in, (timestamp, slot)) AS last_amount_in,
    argMaxState(amount_out, (timestamp, slot)) AS last_amount_out
FROM prod_hermaus_svm_trades_v2
WHERE
    (from_token = sol_address OR to_token = sol_address)
    AND pool_address != 'h'
    AND from_token NOT IN ('x', 'y', 'z', 'a', 'b')
    AND to_token NOT IN ('x', 'y', 'z', 'a', 'b')
GROUP BY
    dex,
    pool_address,
    token_address,
    time_bucket;
    
# Insert enough data for the 5min to load up
INSERT INTO prod_hermaus_svm_trades_5m_mv
SELECT *
FROM prod_hermaus_svm_trades_5m_mv_view
WHERE time_bucket >= now() - INTERVAL 10 MINUTE;
```

- Throws off calculations by a huge margin (more than often overshooting by a lot). 
- The volumes are overstated by a huge margin, if vol is 500 shows 2x-3x that
- Note that there are no duplicates being inserted.

**How to reproduce**
* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
- Sum of the volume for every latest 5min
- Percentage comparisons on volume to the previous 5 mins
- Getting the last trade in previous period (token in, token out, amount in, amount out) for the previous period
- Getting the latest trade in previous period (token in, token out, amount in, amount out) for the current period
- Goal is to nail the query for one timeframe, and then create mv's for different timeframes that give fast views (5m 30m 1h 4h 6h 12h 24h etc)

Additionally, one more question I had was how to use views to get stats on these trades (mentioned above), and make it so we're always using `now() - x min` as latest period and `now() - 2 * x min` to `now() - x min` as previous period for volume and price comparisons.

**Error message and/or stacktrace**

**Additional context**
- Inserts into the replacing merge tree take place about every 1-2 seconds and are batched.

**Comment by den-crane** [comment]
>ENGINE = ReplacingMergeTree()

Your materialized View doesn't see "replaces" which are happening in your trades table. It's because of a nature of Materialized Views -- they are insert triggers.

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf `The most tricky part is that an MV never reads its source table`

Check: https://clickhouse.com/docs/en/materialized-view/refreshable-materialized-view

**Comment by AdvaithD** [comment]
@den-crane Agreed, I'm aware of that, but am sure that we don't have replaces taking place. More so, similar table with lesser # of insert frequency (vs 500-1k every few seconds here) works fine.

**Comment by AdvaithD** [comment]
Resolved this.
