### ISSUE TITLE
Is there some option to enable CREATE TABLE IF NOT EXISTS as default?

### ISSUE THREAD

**Issue by robinpecha** [ClickHouse/ClickHouse#68110]
### Question

Hi, is there any way to enable CREATE TABLE IF NOT EXISTS by default? I am trying to export data from vector.dev and it should create a table for each monitored server. The table name should be generated automatically, like indicies in elasticsearch. 
Thank you, Robin

**Comment by alexey-milovidov** [comment]
Currently, there is no such option, but it is a good feature request.
It can be implemented by adding a `create_if_not_exists` setting.
If the setting is enabled, every CREATE query is interpreted as if it contains IF NOT EXISTS.

**Comment by alexey-milovidov** [comment]
I also wanted automatic table creation with some name pattern on INSERT into a non-existent table, utilizing schema inference.

**Comment by petern48** [comment]
Hi @alexey-milovidov, I addressed the first feature, but I think it would be best to propose your second request as a separate issue to keep things organized.

**Comment by alexey-milovidov** [comment]
Yes, this will be perfect!

**Comment by robinpecha** [comment]
Wow, that was really fast :1st_place_medal: 

Im using Clikchouse Cloud. It will probably take a long time to propagate there.
If I wanted to use it sooner, I would have to host it myself, right?

**Comment by alexey-milovidov** [comment]
We likely to merge this PR soon, so the feature will be in the 24.9 release in September, and at the same time it will be available in the Fast Channel in ClickHouse Cloud (it is an option on a service level), and after some time required for compatibility and gradual production layout it will also be available in the regular release channel in ClickHouse Cloud.

**Comment by petern48** [comment]
this can be closed now. PR has been merged.

**Comment by robinpecha** [comment]
> I also wanted automatic table creation with some name pattern on INSERT into a non-existent table, utilizing schema inference.

Hello, are there some plans to implement something like this? My initial question was about autocreating index/table on first INSERT.

**Comment by alexey-milovidov** [comment]
@robinpecha, this is not in the main plans but in the secondary list of experimental features: https://github.com/ClickHouse/ClickHouse/issues/71175 under the name "Streaming inserts and routed inserts"
