### ISSUE TITLE
function to convert string to integer as sharding key

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#6811]
We tried to create the table in clickhouse cluster by converting string into integer for auto distribution of data across all the shards, using the below create table statements:

CREATE TABLE database.company_testing (...UInt32,...UInt32,....,....,....,...) ENGINE = MergeTree PARTITION BY state_name ORDER BY domain SETTINGS index_granularity = 8192
  
CREATE TABLE company_shard_test AS app_company_testing ENGINE = Distributed(clickHouseCluster, database, app_company_testing, murmurHash3_64(domain))

Sharding Key: murmurHash3_64(domain))

Table got created without errors , and we tried to upload 10 sample records into the **company_testing**  table and it was successful, but when i tried to query the 
**company_testing** from SHARD 2 i got **0** result.

But all 10 records are in sharded table  **company_shard_test**.

Another few questions :

 1. Is it true that sharding key can't be anything other than a constant value or a column of table?
 2. When data distibutes with a shading key, can we predict which shard the data is insert? 
 3. If each shard has the same weight, how should we set the sharding key for equal distribution of    each shard? 

Kindly help us with the solution to handle this.

Thanks.

**Comment by alexey-milovidov** [comment]
> Is it true that sharding key can't be anything other than a constant value or a column of table?

No, you can use arbitrary expressions as a sharding key. Your example is perfectly valid.

> When data distibutes with a shading key, can we predict which shard the data is insert?

Yes. Data will be placed by the remainder of division of the sharding key expression to the sum of shard weights.

> If each shard has the same weight, how should we set the sharding key for equal distribution of each shard?

Your example is totally right. Please check the values of `murmurHash3_64(domain)`, check the remainders of division on your ten records. Then check if the data is sent to remote servers successfully.
