### ISSUE TITLE
Add `RIPEMD160` function

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#68176]
**Use case**

For bitcoin.

**Describe the solution you'd like**

Add it similarly to the existing cryptographic hash functions.

**Comment by m7kss1** [comment]
Hi @alexey-milovidov. I would like to work on this task

**Comment by m7kss1** [comment]
#68639

**Comment by rschu1ze** [comment]
@m7kss1 We had to [revert your PR](https://github.com/ClickHouse/ClickHouse/pull/70005) on short notice, sorry. The necessary changes are not too big ... perhaps you like to push a new PR?

Thanks!

**Comment by m7kss1** [comment]
Yeah, I will open a new PR with the changes made asap. Thanks!

**Comment by rschu1ze** [comment]
Re-submit: https://github.com/ClickHouse/ClickHouse/pull/70087
