### ISSUE TITLE
Clickhouse JDBC connection via jmeter gives authentication failure

### ISSUE THREAD

**Issue by ksaminat** [ClickHouse/ClickHouse#68194]
### Question

Hi Team,

I have installed Clickhouse using altinity clickhouse operator as a kubernetes instance.
I am trying to connect the clickhouse through jmeter using JDBC.

But when we execute the Jmeter testcases its not connecting to the clickhouse instance, failing with Authentication failure
I am giving proper username and password, still I see the failure. Request for any help of guidance here?

Note: I am able to do port-forward the service and able to connect via
http://127.0.0.1:8100/play - with the same username (default)  and password

Below is the query I ran using Curl which is failing,

**bash-5.1# curl -u default "http://chi-pv-log-deployment-pv-0-0.fni.svc.cluster.local:8123/?query=select%20*%20from%20example_table"**
Enter host password for user 'default':
Code: 516. DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. (AUTHENTICATION_FAILED) (version 24.6.2.17 (official build))

**Comment by ksaminat** [comment]
More information,
I am trying to execute this curl command from the jmeter pod, which is deployed in the same kubernetes cluster.
The curl as well as Jmeter connection give the same Authentication failure error.

**Comment by Felixoid** [comment]
Sorry, but there's zero information to debug. There is no `users.xml`, for example.

Under Kubernetes, this could be any level of network mess, so first, check the clickhouse-server.log for the auth errors and compare the network to see if it's allowed for the user.

Another step is to check `SELECT * FROM system.users \G` if the user is configured correctly.

**Comment by Felixoid** [comment]
Feel free to reopen on the additional info
