### ISSUE TITLE
Kill running queries

### ISSUE THREAD

**Issue by caoyang10** [ClickHouse/ClickHouse#68193]
### Question

Can I kill or stop a query without using KILL statement?
I am using JDBC to send SELECT queries, and when I closed the connection because of some reason like it running too slow, the server is still processing the query.

Example:
curl 'http://localhost:8123/' -d 'SELECT number, sleepEachRow(1) FROM system.numbers LIMIT 60 settings function_sleep_max_microseconds_per_block = 60000000'

And then execute ctrl+c cmd to disconnect the session, it's still running.
select * from system.processes;

I know I can use KILL statement to kill this query, but it's a little complexed for me.I need to find query_id and then execute KILL cmd. Also TCP client support ctrl+c way to kill query immediately. Is there any simple way like disconnect the session to stop a running query using JDBC or HTTP ?

**Comment by Felixoid** [comment]
There are a couple of settings you can try:

[cancel_http_readonly_queries_on_client_close](https://clickhouse.com/docs/en/operations/settings/settings#cancel-http-readonly-queries-on-client-close) - `Cancels HTTP read-only queries (e.g. SELECT) when a client closes the connection without waiting for the response.`

[partial_result_on_first_cancel](https://clickhouse.com/docs/en/operations/settings/settings#partial_result_on_first_cancel) - looks less relevant, but maybe would work too
