### ISSUE TITLE
Why does the response times so very different in 2 versions of the same query

### ISSUE THREAD

**Issue by raghukn** [ClickHouse/ClickHouse#68204]
**Company or project name**
Project Rebase

**Describe the situation**
Query1 is more than 10 times faster than Query2

**How to reproduce**
```
Query1: 
Select a.user_id, name
from 
nb_user_mv_tbl as a,
hs_accounts_summary_mv_tbl as b 
where 
a.user_id = b.user_id
and lead_type_grouping = 1 and user_id_grouping = 0 and user_id is not null and  max_last_updated_on > '2024-07-01'
limit 20;
```
**20 rows in set. Elapsed: 0.765 sec. Processed 3.60 million rows, 176.20 MB (4.71 million rows/s., 230.41 MB/s.)**

```
Query2:
Select user_id, name
from 
nb_user_mv_tbl as user inner join hs_accounts_summary_mv as hs_acc final on user.user_id = hs_acc.user_id 
where 
lead_type_grouping = 1 and user_id_grouping = 0 and user_id is not null and  max_last_updated_on > '2024-07-01'
limit 20;
```
**20 rows in set. Elapsed: 9.267 sec. Processed 39.79 million rows, 2.64 GB (4.29 million rows/s., 284.85 MB/s.)**

**Expected performance**
The 2 queries expected to returrn same results with same performance

**Comment by raghukn** [comment]
It seems like Query1 was not looking at unmerged parts. Is it possible that the Query style has this behavior?

**Comment by Algunenano** [comment]
They are completely different queries (`hs_accounts_summary_mv` vs `hs_accounts_summary_mv_tbl`.), so it's impossible to know. The second query is processing 10x more data.

Check that your queries are doing the same over the same data
