### ISSUE TITLE
I can't execute the following SQL, is there a better way to write it?

### ISSUE THREAD

**Issue by JavenJin** [ClickHouse/ClickHouse#68201]
### Question

Version: 22.1.3.7

`FIRST_VALUE` returns different and incorrect values for different records within same group.

Quoted the question: https://github.com/ClickHouse/ClickHouse/issues/37950

Test data:

```sql
create table Position(Group Int32, Order Int32, Id Nullable(Int32)) ENGINE = Memory();

insert into Position values
(7, 10, 5),
(7, 20, 6),
(7, 30, NULL),
(7, 40, NULL);
```

failing query:

```sql
SELECT
    	p.Id,
    	FIRST_VALUE(p.Id) OVER(ORDER BY p.Order DESC)
    FROM
    	Position p
    WHERE
    	p.Group = 7
```

Workaround: `FIRST_VALUE(tuple(x))`

When I use this Workaround, it returns a tuple, not the data I need:

sql:

```sql
SELECT
	p.Id,
	(FIRST_VALUE(tuple(p.Id)) OVER(ORDER BY p.Order desc))
FROM
	Position p
WHERE
	p.Group = 7
```

result:

![image](https://github.com/user-attachments/assets/e52a6149-5525-4f24-a759-30779846cf86)

I am trying to use the following SQL:

```sql
SELECT
	p.Id,
	tupleElement(
		(FIRST_VALUE(tuple(p.Id)) OVER(ORDER BY p.Order desc)),
		1
	)
FROM
	Position p
WHERE
	p.Group = 7
```

But it reported an error:

![image](https://github.com/user-attachments/assets/cda4d321-28dc-4a39-b009-0e808fe1f743)

When I add one more layer it works fine as below SQL:

```sql
SELECT
	a.Id,
	tupleElement(a.value, 1)
FROM
	(
		SELECT
			p.Id,
			(FIRST_VALUE(tuple(p.Id)) OVER(ORDER BY p.Order desc)) value
		FROM
			Position p
		WHERE
			p.Group = 7
	) a
```

![image](https://github.com/user-attachments/assets/a0c03015-ba26-47bd-82d8-e2ee17b47f27)

But currently I can't do more than one level of nesting, is it possible to modify the following SQL to make it work?

```sql
SELECT
	p.Id,
	tupleElement(
		(FIRST_VALUE(tuple(p.Id)) OVER(ORDER BY p.Order desc)),
		1
	)
FROM
	Position p
WHERE
	p.Group = 7
```

**Comment by lgbo-ustc** [comment]
What do you mean about failure in 
```sql
SELECT
    	p.Id,
    	FIRST_VALUE(p.Id) OVER(ORDER BY p.Order DESC)
    FROM
    	Position p
    WHERE
    	p.Group = 7
```

You may refer to `first_value(p.Id) respect nulls`

**Comment by JavenJin** [comment]
The data in the database are as follows:

| Group | Order | Id |
| -- | -- | -- |
| 7 | 10 | 5 |
| 7 | 20 | 6 |
| 7 | 30 | NULL |
| 7 | 40 | NULL |

Execute the following SQL:

```sql
SELECT
	p.Id,
	FIRST_VALUE(p.Id) OVER(ORDER BY p.Order DESC)
FROM
	Position p
WHERE
	p.Group = 7
```

Results:

| Id | FIRST_VALUE(Id) OVER (ORDER BY Order DESC) |
| -- | -- |
| NULL | NULL |
| NULL | NULL |
| 6 | 6 |
| 5 | 6 |

Expected:

| Id | FIRST_VALUE(Id) OVER (ORDER BY Order DESC) |
| -- | -- |
| NULL | NULL |
| NULL | NULL |
| 6 | NULL |
| 5 | NULL |

I get errors with respect nulls on version 22.1.3.7, which does not yet support the respect nulls syntax.

```sql
SELECT
	p.Id,
	FIRST_VALUE(p.Id) respect nulls OVER(ORDER BY p.Order DESC)
FROM
	Position p
WHERE
	p.Group = 7
```

![image](https://github.com/user-attachments/assets/ddd042b1-7198-4e9f-abec-981dbcc33154)

**Comment by lgbo-ustc** [comment]
```sql
f2386dc7dd0d :) SELECT
    ^Ip.Id,
    ^IFIRST_VALUE(p.Id) respect nulls OVER(ORDER BY p.Order DESC)
    FROM
    ^IPosition p
    WHERE
    ^Ip.Group = 7

SELECT
    p.Id,
    FIRST_VALUE(p.Id) RESPECT NULLS OVER (ORDER BY p.Order DESC)
FROM Position AS p
WHERE p.Group = 7

Query id: 23a6b6f9-f3d1-47e0-b40a-dc2ec45db6f5

   ┌───Id─┬─FIRST_VALUE(Id) OVER (ORDER BY Order DESC)─┐
1. │ ᴺᵁᴸᴸ │                                       ᴺᵁᴸᴸ │
2. │ ᴺᵁᴸᴸ │                                       ᴺᵁᴸᴸ │
3. │    6 │                                       ᴺᵁᴸᴸ │
4. │    5 │                                       ᴺᵁᴸᴸ │
   └──────┴────────────────────────────────────────────┘
```

**Comment by JavenJin** [comment]
RESPECT NULLS is only supported in newer versions, the version of ClickHouse I'm using doesn't support the syntax.

The results of my query using Dbeaver:

![image](https://github.com/user-attachments/assets/ebeac8c2-1079-4d4e-a2d0-c8beb411b636)

**Comment by Algunenano** [comment]
> RESPECT NULLS is only supported in newer versions, the version of ClickHouse I'm using doesn't support the syntax.

The fix is to upgrade to a supported version
