### ISSUE TITLE
How to insert customized datetime string values

### ISSUE THREAD

**Issue by q0987** [ClickHouse/ClickHouse#6822]
create table default.Hello (
   date Date DEFAULT toDate(intDiv(timestamp, 1000000000)),
   timestamp UInt64,
   current_date DateTime
 ) ENGINE = MergeTree PARTITION BY date
 ORDER BY (timestamp) SETTINGS index_granularity = 8192
 ;;

$ cat hello.csv
1567514581483926001, '2018/07/03ABC08:48:01'

$cat hello.csv  | clickhouse-client --query="INSERT INTO default.Hello(timestamp,current_date) format CSV" --host=127.0.0.1 --user=user --password=password

> Code: 27. DB::Exception: Cannot parse input: expected \' before: 01\'\n: (at row 1)

**Question**> Is there a way that I can specify the DateTime string input format?

Thank you

**Comment by den-crane** [comment]
ABC ?

select parseDateTimeBestEffort( '2018/07/03T08:48:01')
┌─parseDateTimeBestEffort('2018/07/03T08:48:01')─┐
│                            2018-07-03 08:48:01 │
└────────────────────────────────────────────────┘

https://clickhouse.yandex/docs/en/operations/settings/settings/#settings-date_time_input_format

**Comment by q0987** [comment]
Hello den-crane,

I use ABC to specify a different format than the standard one. It seems that clickhouse doesn't allow to specify the input format.

Thank you

**Comment by den-crane** [comment]
https://clickhouse.yandex/docs/en/operations/settings/settings/#settings-date_time_input_format

**date_time_input_format='best_effort'**



```
create table Hello_null (
timestamp UInt64,
current_date_str String
) ENGINE = Null;

create table Hello (
timestamp UInt64,
current_date DateTime 
) ENGINE = MergeTree PARTITION BY toDate(intDiv(timestamp, 1000000000))
ORDER BY intDiv(timestamp, 1000000000*3600) SETTINGS index_granularity = 8192;


create materialized view Hello_null_mv to  Hello
as select timestamp, 
          parseDateTimeBestEffort(replace(current_date_str, 'ABC', 'T')) current_date
from  Hello_null ;

insert into Hello_null format CSV 1567514581483926001, '2018/07/03ABC08:48:01'


select * from Hello;

┌───────────timestamp─┬────────current_date─┐
│ 1567514581483926001 │ 2018-07-03 08:48:01 │
└─────────────────────┴─────────────────────┘
```

**Comment by q0987** [comment]
very helpful.

Thank you!
