### ISSUE TITLE
SAMPLE n (n is integer) doesn't work

### ISSUE THREAD

**Issue by Siarhei-Hanchuk** [ClickHouse/ClickHouse#68239]
**Describe what's wrong**

SAMPLE n (Here n is a sufficiently large integer) doesn't work

I can't use reproducer because SAMPLE n works only with huge number of rows (100k+)

**Does it reproduce on the most recent release?**

Yes, including head build at the moment of creating this issue

**How to reproduce**

* clickhouse version is 24.6 or 24.7
* Non-default settings - no
* `CREATE TABLE` statement:
```
    CREATE TABLE IF NOT EXISTS table_name
    (
        id UInt64
    )
    ENGINE = MergeTree()
    ORDER BY cityHash64(id)
    SAMPLE BY cityHash64(id);
```

* Insert 10M records with random id (random is mandatory)
* Queries to run that lead to an unexpected result:
```
SELECT count() FROM (
	SELECT * FROM table_name SAMPLE 1_000_000
)
```
It returns 10,000,000, but should approximately 1,000,000

**Expected behavior**

According to the docs: The query is executed on a sample of at least n rows (but not significantly more than this)
It should return not significantly more than this 1,000,000

**Additional context**

On version 23.5 and below it works As I expected
SAMPLE k (k is between 0 and 1) - works the same way as before

**Comment by max-vostrikov** [comment]
I've reproduced it on [fiddle latest version](https://fiddle.clickhouse.com/102031f7-00ed-4597-b4e3-da8e9237d1f7). 
Seems to be independent from analyzer and selecting `count()` on the column, not full result.
For reference. - working correctly on [23.5.5](https://fiddle.clickhouse.com/eff14693-84de-4c55-a562-a0c798caeba5)

**Comment by macobo** [comment]
@alexey-milovidov @hanfei1991I think it would make sense to back-port this to LTS versions. Seen two companies get bit by this and it causing an incident upgrading to 24.8.
