### ISSUE TITLE
Drop query cache entries with certain tag.

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#68244]
`SYSTEM DROP QUERY CACHE` drops all query cache entries.

As per #65872 / #68235, a tagging mechanism for cache entries was introduced. We could extend the drop cache statement to drop only results with certain cache, e.g. `SYSTEM DROP QUERY CACHE TAG 'some_tag'`. Actually, selective cache dropping is occasionally requested, so this is not a useless exercise.

**Comment by pinsvin00** [comment]
I will try to deal with this.

**Comment by rschu1ze** [comment]
Nice, please ping me once you have a PR or I can be of help.

**Comment by pinsvin00** [comment]
@rschu1ze, I don't know really how I should write tests for it. I got some stuff working like the query you've just described, and the mechanism for deleting the cache. I will try to make a PR, around the Friday evening or at Sunday/Saturday.

**Comment by rschu1ze** [comment]
That's great. Re testing, you may want to get some inspiration from existing tests `tests/queries/0_stateless/02494_query_cache_*.sql` and see [here](https://clickhouse.com/docs/en/development/tests) about testing in general.
