### ISSUE TITLE
embedding a UDF in a view

### ISSUE THREAD

**Issue by zav379** [ClickHouse/ClickHouse#68285]
I often use functions in views,
in version 22.1.3.7 when compiling a view, the function name remains in its body
when switching to version 23.8.3.48, this has changed. 
Now the whole body of the function is embedded in the body of the view.
How can I fix this?

**Comment by SaltTan** [comment]
Duplicate
* https://github.com/ClickHouse/ClickHouse/issues/44590
* https://github.com/ClickHouse/ClickHouse/issues/57748

ClickHouse Docs AI:

> ClickHouse started replacing User-Defined Functions (UDFs) with their body in DDL during the release of version 22.12 on 2022-12-15. This change was implemented to avoid failures during loading at startup. Additionally, UDFs can now be used as `DEFAULT` expressions for columns.

Here is the extract from the changelog:
> Substitute UDFs in `CREATE` query to avoid failures during loading at startup. Additionally, UDFs can now be used as `DEFAULT` expressions for columns.

You can find more details in the [official changelog](https://clickhouse.com/docs/en/whats-new/changelog/2022#improvement).
