### ISSUE TITLE
Need out of the frame lag values

### ISSUE THREAD

**Issue by nagababu9652** [ClickHouse/ClickHouse#68319]
### Company or project name

IOT Engine Analytics

### Question

Currently we are working in a analytics project where we need lag values for the fields. i tried many approaches but every time i was getting lag within the frame but required lag for the id on whole data

query :
CREATE MATERIALIZED VIEW viewignitionlagparameters  to tblignitionlagparameters as select deviceid, uniqueid,   ignitionstatus, speed, tenantgroupname, devicetypename, parsername,     latitude,    longitude,  devicedatetime, insertdatetime, vehicleid,
 any(ignitionstatus) over win as  lagignition, 
lagInFrame(latitude) over win as laglatitude, 
first_value(longitude) over win as laglongitude,
 lagInFrame(speed) over win as lagspeed from tbltrackerdata  window win as (partition by deviceid order by insertdatetime ASC ROWS BETWEEN unbounded PRECEDING AND unbounded following) 

server version:  (version 24.7.3)

i have tried different combinations of these : ROWS BETWEEN unbounded PRECEDING AND unbounded following , but no luck. Please suggest

**Comment by den-crane** [comment]
Materialized Views -- they are insert triggers.

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf The most tricky part is that an MV never reads its source table

It's not possible to use Window Functions with usual Materialized Views.

Check: https://clickhouse.com/docs/en/materialized-view/refreshable-materialized-view

**Comment by nagababu9652** [comment]
Thanks @den-crane now i understand why it was behaving like that. Now i was trying with refreshable as an work around.

But i was encountered by an issue here 

While before testing refresable meterialized view, i was just inserting the data from table tbltrackerdata to tbltrackerlagdata for inserting initial data

insert into tbltrackerlagdata select deviceid, uniqueid,   ignitionstatus, speed, tenantgroupname, devicetypename, parsername,     latitude,    longitude,  devicedatetime, insertdatetime, vehicleid, lagInFrame (ignitionstatus) over win as  lagignition, lagInFrame(latitude) over win as laglatitude, lagInFrame (longitude) over win as laglongitude, lagInFrame(speed) over win as lagspeed from tbltrackerdata  window win as (partition by deviceid order by devicedatetime)

![image](https://github.com/user-attachments/assets/7ecf0293-8f6b-44ff-b7e9-5f2b97df637f)

Could you please suggest on it.

**Comment by den-crane** [comment]
> But i was encountered by an issue here

Do you mean that the source table `tbltrackerdata`  has only 3.67 million rows and you expect a new table `tbltrackerlagdata` to have the same number of rows after this insert ?

```
INSERT INTO tbltrackerlagdata SELECT
    deviceid,
    uniqueid,
    ignitionstatus,
    speed,
    tenantgroupname,
    devicetypename,
    parsername,
    latitude,
    longitude,
    devicedatetime,
    insertdatetime,
    vehicleid,
    lagInFrame(ignitionstatus) OVER win AS lagignition,
    lagInFrame(latitude) OVER win AS laglatitude,
    lagInFrame(longitude) OVER win AS laglongitude,
    lagInFrame(speed) OVER win AS lagspeed
FROM tbltrackerdata
WINDOW win AS (PARTITION BY deviceid ORDER BY devicedatetime ASC)
```
