### ISSUE TITLE
Code:341.DB::Exception : Log entry log-0000000002 is not precessed on local replica, most likely because the replica was shut down

### ISSUE THREAD

**Issue by zgb0106** [ClickHouse/ClickHouse#68314]
### Question

![20240814100129](https://github.com/user-attachments/assets/2c75ac79-da40-4077-8e43-49e1dff650b1)

**Comment by alexey-milovidov** [comment]
The message is correct.

**Comment by alexey-milovidov** [comment]
You can consult server logs to check why exactly the table is read-only.

**Comment by zgb0106** [comment]
I have resolved the error that the table is read-only, but this error still exists: Log entry log-0000000002 is not processed on local replica, most likely because the replica was shut down.
