### ISSUE TITLE
execute sql lose data,sql=INSERT INTO final_all SELECT FROM tmp_all 

### ISSUE THREAD

**Issue by florida-hehe** [ClickHouse/ClickHouse#6834]
**Describe the bug or unexpected behaviour**
We use flink to write kafka data to clickhouse, first to the temporary table (this step does not lose data problems).then The temporary table written to the final table (tmp, final table are all ReplicatedMergeMergeTree and Distributed engine), but this step often loses data, and the java code in flink finds no errors and exceptions. Clickhouse's log also found no problem. The sql statement is as follows: INSERT INTO final_all(checkpoint_id,checkpoint_timestamp) SELECT checkpoint_id,checkpoint_timestamp FROM tmp_all WHERE checkpoint_id = %s AND checkpoint_timestamp = %s. Can you see it? Thank

**How to reproduce**
* tmp,final table are all ReplicatedMergeTree and Distributed engine
* write to tmp table.  sql= INSERT INTO tmp_all VALUES %s ,this step does not lose data problems
* write tmp table to final. sql=INSERT INTO final_all SELECT FROM tmp_all , usually lose data
* tmp_all and final_all are Distributed table
* Write the final table immediately after writing the TMP table

**Comment by den-crane** [comment]
https://clickhouse.yandex/docs/en/operations/table_engines/replication/

Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application doesn't know if the data was written to the DB, so the INSERT query can simply be repeated. It doesn't matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by merge_tree server settings.

**Comment by florida-hehe** [comment]
@den-crane no this reason, tmp_all and final_all table  is not the same table

**Comment by abyss7** [comment]
Can you provide the numbers of lost rows against total rows? And sample queries on how you compare both tables?

**Comment by den-crane** [comment]
> @den-crane no this reason, tmp_all and final_all table is not the same table

Please, show the output ` grep "already exists; ignoring it" /var/log/clickhouse-server/clickhouse-server.log`
