### ISSUE TITLE
Non-existent columns are returned on joins

### ISSUE THREAD

**Issue by a-rodin** [ClickHouse/ClickHouse#6836]
I'm trying to run the following query on ClickHouse server version 19.13.3 revision 54425:

```sql
SELECT l.a, l.c FROM (
    SELECT 1 AS a, 2 AS b
) AS l join (
    SELECT 2 AS b, 3 AS c
) AS r
USING b
```

I expect to get an error `Missing columns: 'c' while processing query`. However, instead of this error the server returns

```
┌─a─┬─c─┐
│ 1 │ 3 │
└───┴───┘
```

**Comment by 4ertus2** [comment]
Need to ckeck columns in subselect results. Related #4567
