### ISSUE TITLE
Adding "use 'initial_user' option" to user specification in cluster definition

### ISSUE THREAD

**Issue by 243f6a8885a308d313198a2e037** [ClickHouse/ClickHouse#6843]
**Use case**
We use `max_memory_usage_for_user` option to limit the memory usage in order not to allow a single user to occupy a large amount of memory (to maintain availability).
However, the cluster uses another user, defined in cluster definition, instead of query `initial_user`, therefore the memory limitation only works for the initial server.

https://clickhouse.yandex/docs/en/operations/table_engines/distributed/

**Describe the solution you'd like**
One solution to this problem is to add a boolean option, `use_initial_user_if_possible` under cluster name, which means "use `initial_user` to connect to other shards if possible."
It can be something like:

```xml
 <remote_servers>
     <logs>
+        <!-- Optional. Use initial_user (if possible) instead of user specified here. Default: false (use specified user) -->
+        <use_initial_user_if_possible>true</use_initial_user_if_possible>
         <shard>
             <!-- Optional. Shard weight when writing data. Default: 1. -->
             <weight>1</weight>
 ...
```

pros:
- can be used with little change in configuration

cons:
- how can clickhouse-server know the password for `initial_user`? (it may be hashed in `users.xml`)
  - simply "use specified user/pass" when the password of initial_user is hashed in users.xml, otherwise use initial_user with its password, can be possible.

**Describe alternatives you've considered**
I have no better ideas.
(Writing down the "if-else" statements that determine which user to use in XML can be also possible, which seems much more complex.)

**Additional context**
Many batch processes access to our ClickHouse cluster.
We want to reject any memory-consuming (>32GiB) operations/users because such query can damage the availability of other users/batches.
However, we currently can only limit the memory_usage on the initial server, and usage on other shards are not limited (unless that user also connects to it directly).

**Comment by alexey-milovidov** [comment]
Maybe better to always use initial_user to calculate per-user limits?

**Comment by alexey-milovidov** [comment]
BTW, initial_user can be easily fabricated by client.

**Comment by 243f6a8885a308d313198a2e037** [comment]
> Maybe better to always use initial_user to calculate per-user limits?

Yeah, this can solve our current problem. However...

> BTW, initial_user can be easily fabricated by client.

If my understanding is correct, limiting the memory usage for initial_user ( `max_memory_usage_for_initial_user` ?) might be unexpected in some situation (such as meta-cluster or relay client).

Hmm...

**Comment by azat** [comment]
>BTW, initial_user can be easily fabricated by client.

This can be fixed by overwriting it before sending distributed query

>Maybe better to always use initial_user to calculate per-user limits?

I was thinking about applying limits for both users, "default"+initiator (by using this syntax, i.e. user1+user2, like in emails), but this sounds complex and I doubt that this will be useful.

You suggestion sounds simpler (and hence - better), `initial_user` can be used if `.user` is empty (most of the setups I guess)

>how can clickhouse-server know the password for initial_user?

`users.xml` looks ok

**Comment by filimonov** [comment]
Alternative option #9751

**Comment by 243f6a8885a308d313198a2e037** [comment]
#9751 sounds enough to me!
