### ISSUE TITLE
`--copy` mode for `clickhouse-local`

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#68503]
**Use case**

A shortcut for formats conversion.

**Describe the solution you'd like**

The `--copy` option can be specified instead of a `--query`
and works in the same way as `--query "SELECT * FROM table"`

For example,

```
clickhouse-local --copy < input.json > output.csv
```

is the same as

```
clickhouse-local --query "SELECT * FROM table" < input.json > output.csv
```

**Comment by cmagapu** [comment]
@alexey-milovidov I'm new to open source and would like to contribute. Can I work on this?

**Comment by alexey-milovidov** [comment]
@cmagapu you can take a look at https://github.com/ClickHouse/ClickHouse/pull/68583 and review it.

**Comment by cmagapu** [comment]
@alexey-milovidov I see that there is an existing PR, but it's failing some stateless tests. The job now is to make sure those tests pass, correct?
