### ISSUE TITLE
Many problems with build on ubuntu 

### ISSUE THREAD

**Issue by Lalaluleylo** [ClickHouse/ClickHouse#68501]
**Company or project name**

> I have no company,  for education purposes only

**Operating system**

>  Ubuntu 22.04.4 ,  on bare OS  without VMs

**Cmake version**
  3.28

**Ninja version**
 1.10.1

**Compiler name and version**
Clang  17

**Full cmake and/or ninja output** 
[logCH.txt](https://github.com/user-attachments/files/16646698/logCH.txt)

```[tasklist]
### Tasks
```

**Comment by alexey-milovidov** [comment]
Your source code is modified, as CMake shows.

**Comment by alexey-milovidov** [comment]
I recommend removing the working directory and starting over, step by step, as in the instructions.

**Comment by Lalaluleylo** [comment]
in case of : 
> git clone --recursive --shallow-submodules https://github.com/ClickHouse/ClickHouse.git
Cloning into 'ClickHouse'...
remote: Enumerating objects: 1492640, done.
remote: Counting objects: 100% (950/950), done.
remote: Compressing objects: 100% (632/632), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 4891 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet/s
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
 >

**git submodule update --init**  
 is right solution?

**Comment by Lalaluleylo** [comment]
Thanks alexey , your advice is helped!
