### ISSUE TITLE
Build Failure: Ninja Stops Due to Previous Errors in ClickHouse Build Process

### ISSUE THREAD

**Issue by Zawa-ll** [ClickHouse/ClickHouse#68506]
### Question

During a recent build in my PR #66478, the process was halted when Ninja failed to make progress due to previous errors. The following traceback was encountered:

Aug 17 09:15:41 [13545/14076] Building CXX object src/Functions/CMakeFiles/clickhouse_functions_obj.dir/FunctionsConversion.cpp.o
Aug 17 09:15:41 ninja: build stopped: cannot make progress due to previous errors.
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/docker/packager/./packager", line 559, in <module>
    main()
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/docker/packager/./packager", line 546, in main
    run_docker_image_with_env(
  File "/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse/docker/packager/./packager", line 115, in run_docker_image_with_env
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker run --network=host --user=1000:1000 --rm  --volume=/home/ubuntu/actions-runner/_work/_temp/build_check/binary_tidy:/output --volume=/home/ubuntu/actions-runner/_work/ClickHouse/ClickHouse:/build  -e OUTPUT_DIR=/output -e DEB_ARCH=amd64 -e CC=clang-18 -e CXX=clang++-18 -e BUILD_TYPE=Debug -e SCCACHE_BUCKET=clickhouse-builds -e SCCACHE_S3_KEY_PREFIX=ccache/sccache -e CTCACHE_S3_BUCKET=clickhouse-builds -e CTCACHE_S3_FOLDER=ccache/clang-tidy-cache -e NINJA_FLAGS=-k0 -e VERSION_STRING='24.9.1.641' -e CMAKE_FLAGS="$CMAKE_FLAGS -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18 -DCOMPILER_CACHE=sccache -DENABLE_CLANG_TIDY=1 -DENABLE_TESTS=1 -DENABLE_EXAMPLES=1 -DENABLE_UTILS=1 -DENABLE_BUILD_PROFILING=1" -e BUILD_TARGET='all' --volume=/home/ubuntu/.cargo/registry:/rust/cargo/registry  clickhouse/binary-builder:dcea8e9650fa' returned non-zero exit status 1.

Please help me out! Any guidances or instructions would be appreciated!

**Comment by Zawa-ll** [comment]
I have double checked all the failing stuff in the pipeline, none of them points to the existing fast check or my code changes, so I wasn't sure if it's caused by my code changes, please help me out!

**Comment by ucasfl** [comment]
Search the build log with `Werror`:
```
conversion -Wno-unsafe-buffer-usage -Wno-switch-default -g -Og -g  -D_LIBCPP_DEBUG=0 -std=c++23   -D OS_LINUX -Werror -Wno-deprecated-declarations -Wno-poison-system-directories -nostdinc++ -MD -MT src/CMakeFiles/clickhouse_common_io.dir/Common/AsynchronousMetrics.cpp.o -MF src/CMakeFiles/clickhouse_common_io.dir/Common/AsynchronousMetrics.cpp.o.d -o src/CMakeFiles/clickhouse_common_io.dir/Common/AsynchronousMetrics.cpp.o -c /build/src/Common/AsynchronousMetrics.cpp
Aug 17 07:20:14 /build/src/Common/AsynchronousMetrics.cpp:10:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
Aug 17 07:20:14     9 | #include <IO/ReadHelpers.h>
Aug 17 07:20:14       |                            
Aug 17 07:20:14    10 | #include <IO/UncompressedCache.h>
Aug 17 07:20:14       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 17 07:20:14 /build/src/Common/AsynchronousMetrics.cpp:16:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
Aug 17 07:20:14    15 | #include <sys/resource.h>
Aug 17 07:20:14       |                          
Aug 17 07:20:14    16 | #include <Common/CurrentMetrics.h>
Aug 17 07:20:14       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 17 07:20:14 /build/src/Common/AsynchronousMetrics.cpp:17:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
Aug 17 07:20:14    16 | #include <Common/CurrentMetrics.h>
Aug 17 07:20:14       |                                   
Aug 17 07:20:14    17 | #include <Common/Exception.h>
Aug 17 07:20:14       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 17 07:20:14 /build/src/Common/AsynchronousMetrics.cpp:18:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
Aug 17 07:20:14    17 | #include <Common/Exception.h>
Aug 17 07:20:14       |                              
Aug 17 07:20:14    18 | #include <Common/filesystemHelpers.h>
Aug 17 07:20:14       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 17 07:20:14 /build/src/Common/AsynchronousMetrics.cpp:20:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
Aug 17 07:20:14    19 | #include <Common/formatReadable.h>
Aug 17 07:20:14       |                                   
Aug 17 07:20:14    20 | #include <Common/logger_useful.h>
Aug 17 07:20:14       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 17 07:20:14 /build/src/Common/AsynchronousMetrics.cpp:21:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
Aug 17 07:20:14    20 | #include <Common/logger_useful.h>
Aug 17 07:20:14       |                                  
Aug 17 07:20:14    21 | #include <Common/setThreadName.h>
Aug 17 07:20:14       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 17 07:20:14 23734 warnings generated.
Aug 17 07:20:14 Suppressed 24030 warnings (23728 in non-user code, 302 NOLINT).
Aug 17 07:20:14 Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Aug 17 07:20:14 6 warnings treated as errors
```
```
Wno-weak-vtables -Wno-thread-safety-negative -Wno-enum-constexpr-conversion -Wno-unsafe-buffer-usage -Wno-switch-default -g -Og -g  -D_LIBCPP_DEBUG=0 -std=c++23   -D OS_LINUX -Werror -Wno-deprecated-declarations -Wno-poison-system-directories -nostdinc++ -MD -MT src/CMakeFiles/dbms.dir/QueryPipeline/RemoteQueryExecutor.cpp.o -MF src/CMakeFiles/dbms.dir/QueryPipeline/RemoteQueryExecutor.cpp.o.d -o src/CMakeFiles/dbms.dir/QueryPipeline/RemoteQueryExecutor.cpp.o -c /build/src/QueryPipeline/RemoteQueryExecutor.cpp
Aug 17 07:36:35 /build/src/QueryPipeline/RemoteQueryExecutor.cpp:9:1: error: duplicate include [readability-duplicate-include,-warnings-as-errors]
Aug 17 07:36:35     8 | #include <Core/Settings.h>
Aug 17 07:36:35       |                           
Aug 17 07:36:35     9 | #include <Core/Settings.h>
Aug 17 07:36:35       | ^~~~~~~~~~~~~~~~~~~~~~~~~~
Aug 17 07:36:35 53523 warnings generated.
Aug 17 07:36:35 Suppressed 54126 warnings (53522 in non-user code, 604 NOLINT).
Aug 17 07:36:35 Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Aug 17 07:36:35 1 warning treated as error
```

**Comment by Zawa-ll** [comment]
Thank you for your response! This really help!

**Comment by arunppsg** [comment]
I have a similar issue. I was following the developer instructions from [here](https://clickhouse.com/docs/en/development/developer-instruction) and I am facing the following error (from CMakeFiles/CMakeError.log):

```
/home/code/ClickHouse/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: 'malloc/malloc.h' file not found
    1 | #include <malloc/malloc.h>
      |          ^~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.


```

I am on Ubuntu 22.04 and have installed libc6-dev but not sure what I am missing here to build clickhouse.
