### ISSUE TITLE
[mannWhitneyUTest] The implementation of the class ConcatenatedSamples might not be correct.

### ISSUE THREAD

**Issue by jixxiong** [ClickHouse/ClickHouse#68519]
I can see no reason to use '%' instead of '-' in the operator[] of ConcatenatedSamples. Particularly when the size of second sample is larger than the first one, the output of this function appears to be a random number.

https://github.com/ClickHouse/ClickHouse/blame/285f99f7196d364288362908c24af8b398ee43aa/src/AggregateFunctions/AggregateFunctionMannWhitney.cpp#L117

<img width="913" alt="image" src="https://github.com/user-attachments/assets/50a55a7a-27e5-4777-b120-f027005b194e">

**Comment by hanfei1991** [comment]
Yes, I have confirmed it's bug.
