### ISSUE TITLE
Unable to access show tables or system.detached_parts table

### ISSUE THREAD

**Issue by karthik-thiyagarajan** [ClickHouse/ClickHouse#68524]
We are running ClickHouse 24.6 and recently upgraded and we have deployed the clickhouse  with 3 shards and 3 replicas.

We are seeing the below issue in one of the pods and we have multiple databases in this cluster and we see issue only in one of the databases and in only in one of the pods. and we are not able to access even system.detached_parts table also and we see the below error.  Same error happens when i do "show tables from db_name" for that specific databse in that pod. I've replaced my table name and db name with some dummy names for obvious reasons. 

chi-clickhouse-server-my-programcluster-01-0-2-0.chi-clickhouse-server-my-programcluster-01-0-2.clickhouse.svc.cluster.local :) show tables from my_db_name_here. 

SHOW TABLES FROM my_db_name_here

Query id: 1ac4e541-2dc1-49b7-9923-8a5bc3baa497

Elapsed: 0.002 sec. 

Received exception from server (version 24.6.3):
Code: 722. DB::Exception: Received from localhost:9001. DB::Exception: Waited job failed: Code: 696. DB::Exception: Load job 'startup table my_db_name_here.my_table_name_here' -> Code: 695. DB::Exception: Load job 'load table my_db_name_here.my_table_name_here' failed: Code: 231. DB::Exception: Suspiciously many (214 parts, 0.00 B in total) broken parts to remove while maximum allowed broken parts count is 100. You can change the maximum value with merge tree setting 'max_suspicious_broken_parts' in <merge_tree> configuration section or in table settings in .sql file (don't forget to return setting back to default value): Cannot attach table `my_db_name_here`.`my_table_name_here` from metadata file /var/lib/clickhouse/store/756/75699675-7c7e-41b8-98ab-9c00081aad6f/my_table_name_here.sql from query ATTACH TABLE my_db_name_here.my_table_name_here UUID '1ba15dd3-3cfb-4466-ba12-f1f42398ce94' (`updated_at` DateTime64(3),  ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/my_db_name_here/my_dist_table_name', '{replica}') PARTITION BY toYYYYMMDD(updated_at) ORDER BY (col1,col2,col3,col4) TTL toDateTime(updated_at) + toIntervalDay(7) SETTINGS index_granularity = 8192. (TOO_MANY_UNEXPECTED_DATA_PARTS),. (ASYNC_LOAD_WAIT_FAILED)

chi-clickhouse-server-my-programcluster-01-0-2-0.chi-clickhouse-server-my-programcluster-01-0-2.clickhouse.svc.cluster.local :) 

chi-clickhouse-server-my-programcluster-01-0-2-0.chi-clickhouse-server-my-programcluster-01-0-2.clickhouse.svc.cluster.local :) select * from system.detached_parts limit 1

SELECT *
FROM system.detached_parts
LIMIT 1

Query id: aae2b051-3338-41a7-bc47-8e937fd0ab47

Elapsed: 0.002 sec. 

Received exception from server (version 24.6.3):
Code: 722. DB::Exception: Received from localhost:9001. DB::Exception: Waited job failed: Code: 696. DB::Exception: Load job 'startup table my_db_name_here.my_table_name_here' -> Code: 695. DB::Exception: Load job 'load table my_db_name_here.my_table_name_here' failed: Code: 231. DB::Exception: Suspiciously many (214 parts, 0.00 B in total) broken parts to remove while maximum allowed broken parts count is 100. You can change the maximum value with merge tree setting 'max_suspicious_broken_parts' in <merge_tree> configuration section or in table settings in .sql file (don't forget to return setting back to default value): Cannot attach table `my_db_name_here`.`my_table_name_here` from metadata file /var/lib/clickhouse/store/756/75699675-7c7e-41b8-98ab-9c00081aad6f/my_table_name_here.sql from query ATTACH TABLE my_db_name_here.my_table_name_here UUID '1ba15dd3-3cfb-4466-ba12-f1f42398ce94' (`updated_at` DateTime64(3), ) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/{shard}/my_db_name_here/my_dist_table_name', '{replica}') PARTITION BY toYYYYMMDD(updated_at) ORDER BY (col1,col2,col3,col4) TTL toDateTime(updated_at) + toIntervalDay(7) SETTINGS index_granularity = 8192. (TOO_MANY_UNEXPECTED_DATA_PARTS),. (ASYNC_LOAD_WAIT_FAILED)

chi-clickhouse-server-my-programcluster-01-0-2-0.chi-clickhouse-server-my-programcluster-01-0-2.clickhouse.svc.cluster.local :)

**Comment by karthik-thiyagarajan** [comment]
I did touch "/var/lib/clickhouse/flags/force_restore_data" and restarted clickhouse, and i see this issue resolved. However, i did not expect that even the system.detached_parts table be inaccessible and "show tables from my_db" be inaccessible and throwing error.

**Comment by nickitat** [comment]
it is unclear how we could display the set of detached parts or existing tables until all tables are loaded
