### ISSUE TITLE
WHERE EXISTS ( ... subquery ...) not supported and error message is confusing

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#6852]
https://www.w3schools.com/sql/sql_exists.asp
ClickHouse doesn't support such a queries and thinks that 'exists' is a column name:
```
select * from system.one where exists (select 1);

Expected one of: LIKE, GLOBAL NOT IN, AS, IS, OR, QuestionMark, BETWEEN, NOT LIKE, AND, Comma, alias, IN, Dot, NOT, Arrow, token, NOT IN, GLOBAL IN

select * from system.one where exists;

Received exception from server (version 19.14.1):
Code: 47. DB::Exception: Received from localhost:9000. DB::Exception: Missing columns: 'exists' while processing query: 'SELECT dummy FROM system.one WHERE exists', required columns: 'dummy' 'exists', source columns: 'dummy'. 

0 rows in set. Elapsed: 0.011 sec. 
```

PS. Not important, issue is just to document that behaviour.

**Comment by templarzq** [comment]
up

**Comment by Jefferson111** [comment]
Yea, they should at least document it under [here](https://clickhouse.tech/docs/en/sql-reference/statements/select/where/). That current syntax reference link is as good as not existing at all... Honestly all it takes is just a few minutes for someone familiar with Clickhouse to update it with some examples and explanation.
