### ISSUE TITLE
Can the sharding key of the clickhouse distributed engine table achieve constant fixed sharding?

### ISSUE THREAD

**Issue by hecheng64** [ClickHouse/ClickHouse#68549]
### Question

Can the sharding key of the clickhouse distributed engine table achieve constant fixed sharding? If possible, could you give an example? Also, there is a question about Distributed ('ruby_3S_1R ',
'database1','table1',hiveHash(ajbh));  The ruby_3S_1R cluster has 3 nodes, but I take different ajbh values, such as A20240819174436564, A20240819174220337 with different values, but they all fall on the same node. Why?

**Comment by hanfei1991** [comment]
hi, what is `constant fixed shared`? can you give me a example?

**Comment by hecheng64** [comment]
可能我描述不准确吧： 我是在网络上看到介绍的：                                                                                                                       
1） random随机分片：写入数据会被随机分发到分布式集群中的某个节点上。
2） constant固定分片：写入数据会被分发到固定一个节点上。 -------------------------------constant fixed sharding
3） column value分片：按照某一列的值进行hash分片。
4） 自定义表达式分片：指定任意合法表达式，根据表达式被计算后的值进行hash分片。

或者你不管我描述constant fixed sharding。

**Comment by hecheng64** [comment]
Also, there is a question about Distributed ('ruby_3S_1R ',
'database1','table1',hiveHash(ajbh)); The ruby_3S_1R cluster has 3 nodes, but I take different ajbh values, such as A20240819174436564, A20240819174220337 with different values, but they all fall on the same node. Why? @hanfei1991

**Comment by hanfei1991** [comment]
```
Also, there is a question about Distributed ('ruby_3S_1R ',
'database1','table1',hiveHash(ajbh)); The ruby_3S_1R cluster has 3 nodes, but I take different ajbh values, such as A20240819174436564, A20240819174220337 with different values, but they all fall on the same node.
```

What is the config of your cluster `ruby_3S_1R` ?

**Comment by hecheng64** [comment]
![Uploading QQ截图20240821085850.jpg…]()

**Comment by hecheng64** [comment]
cluster   |shard_num|shard_weight|
----------+---------+------------+
ruby_3S_1R|        1|           1|
ruby_3S_1R|        2|           1|
ruby_3S_1R|        3|           1|
