### ISSUE TITLE
 how using distributed engine table 

### ISSUE THREAD

**Issue by hecheng64** [ClickHouse/ClickHouse#68550]
### Question

I have a requirement: clickhouse distributed engine table, with 5 nodes. Randomly select an idle node (can it be determined through SQL statements), and then insert data into this node. How to implement it? Can the shard key be implemented with a fixed key?

**Comment by hanfei1991** [comment]
maybe you can select node from `system.clusters`

**Comment by hecheng64** [comment]
system.clusters  反应不出节点是否处于空闲或者忙碌状态 @hanfei1991

**Comment by hanfei1991** [comment]
then we have `system.metrics` showing the workload of this server.
