### ISSUE TITLE
Data race in `ActionsVisitor` (on `unique_column_name`) by `00712_prewhere_with_sampling.sql`

### ISSUE THREAD

**Issue by KochetovNicolai** [ClickHouse/ClickHouse#68569]
https://s3.amazonaws.com/clickhouse-test-reports/0/443a676b5b9edb58ee10b03e9cd544a3dc754295/stress_test__azure__tsan_.html

https://s3.amazonaws.com/clickhouse-test-reports/0/443a676b5b9edb58ee10b03e9cd544a3dc754295/stress_test__azure__tsan_/stderr.log

What can be wrong with `const_cast`?

https://github.com/ClickHouse/ClickHouse/blob/5c6bfd9f4d1ca25cd949ba6f5ad364e542247721/src/Interpreters/ActionsVisitor.cpp#L1350-L1378

**Comment by KochetovNicolai** [comment]
basically, we can clone AST here
https://github.com/ClickHouse/ClickHouse/blob/bc00f274aa6d33a2417f84c8be14f240910bb9fd/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L431

or somewhere above

**Comment by yariks5s** [comment]
Fixed by https://github.com/ClickHouse/ClickHouse/pull/68321
