### ISSUE TITLE
Add a BTree family engine

### ISSUE THREAD

**Issue by a-rodin** [ClickHouse/ClickHouse#6856]
It might be beneficial to add a BTree family engine that would support workloads usually handled by RDBMS such as MySQL or PostgreSQL.

I think this could be implemented on top of SQLite3 in [WAL mode](https://www.sqlite.org/wal.html). Replicated version of such engine can use primary/secondary approach with automatic primary election.

This would make it possible for many applications to use ClickHouse for both analytics-like workloads and as the main application database, thus simplifying overall setup.

I'm not sure though are there some general architectural limitations that would make such engine not feasible.

**Comment by alexey-milovidov** [comment]
Closed by https://github.com/ClickHouse/ClickHouse/pull/15073
But:
- strictly speaking it's not a btree;
- point update/delete can be implemented on top of this engine but currently it's not done.
