### ISSUE TITLE
Docker Image mount point for data not properly documented?

### ISSUE THREAD

**Issue by christo-ph** [ClickHouse/ClickHouse#68596]
### Question

According to the docker image documentation, I have to mount

`/var/lib/clickhouse/ - main folder where ClickHouse stores the data`

for persistence. This doesnt work. After a restart, the data is gone.

Inspecting the container, I can find the `/data` folder with the expected data, but contents are symlinked to `/store`.

So from my understanding, `/data`, `/store` and `/var/lib/clickhouse` have to be mounted somehow?

Is that correct? I would like to get some background about this, as when I start clickhouse server locally, everything is being stored in the current folder.

**Comment by antaljanosbenjamin** [comment]
Both `data` and `store` directories should be inside `/var/lib/clickhouse`:
```
ls -la ch_data/
total 64
drwxr-xr-x 14 systemd-resolve systemd-journal 4096 Aug 20 10:03 .
drwxrwxr-x 22 ubuntu          ubuntu          4096 Aug 20 10:00 ..
drwxr-x---  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 access
drwxr-x---  4 systemd-resolve systemd-journal 4096 Aug 20 10:00 data
drwxr-x---  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 dictionaries_lib
drwxr-x---  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 flags
drwxr-xr-x  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 format_schemas
drwxr-x---  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 metadata
drwxr-x---  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 metadata_dropped
drwxr-x---  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 preprocessed_configs
-rw-r-----  1 systemd-resolve systemd-journal   55 Aug 20 10:03 status
drwxr-x--- 11 systemd-resolve systemd-journal 4096 Aug 20 10:02 store
drwxr-xr-x  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 tmp
drwxr-xr-x  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 user_files
drwxr-x---  2 systemd-resolve systemd-journal 4096 Aug 20 10:00 user_scripts
-rw-r-----  1 systemd-resolve systemd-journal   36 Aug 20 10:00 uuid
```

I tried to reproduce your issue by running command from the docker image readme and it works for me.

Which commands did you use?

**Comment by christo-ph** [comment]
Hi thanks for your answer.

I think the default config.xml was causing this storage behavior. It had a lot of sample configuration inside, as well as a splitter storage example which was active.

When I mount my config.xml properly:

```
volumes:
      - ./config/config.xml:/etc/clickhouse-server/cofig.xml
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
```

it works as you have shown in your example!
