### ISSUE TITLE
Is there any better way to do join bitmap？

### ISSUE THREAD

**Issue by ycli12** [ClickHouse/ClickHouse#68598]
### Question

I have a SQL like below. It get results by bitmap. `a` is has million of rows，which is quite big. While `bms` has little rows, but has bitmap column which takes 1M storage or so. Both `a` and `bms` is local table. After `a INNER JOIN bms`, the immediate result is quite big, which takes 100G memory. We assume the immediate result has millions of bitmap which makes it consume lots of memory. Actually we don't need bitmap after join, because we just need bitmap to filter some row. But ClickHouse can't have bitmapContains in join condition.
Copy the right table columns is not very reasonable(maybe reference is fine), and maybe this was solve by this [Improve all join performance by append RowRefList or RowRef to AddedColumns for lazy output](https://github.com/ClickHouse/ClickHouse/pull/63677)

> SELECT 
   *,
   multiIf(bitmapContains(bms.hit_sid_exp_bm, a.sid), 1, bitmapContains(bms.hit_sid_control_bm, a.sid), 0, -1) AS group_id FROM a INNER JOIN bms 
ON (a.ds = bms.ds) 
WHERE (group_id >=0) AND (bitmapContains(bms.drilled_hit_uuid_exp_bm, a.uid) OR bitmapContains(bms.drilled_hit_uuid_control_bm, a.uid))

So far we use option like below to use partial merge join but hash join, which seems to have lots of bitmaps in memory. But this is not fast enough.
> join_algorithm='partial_merge', max_bytes_before_external_sort = 50000000000

Is there any better way to rewrite this sql or use other options to get better performance？Thanks all.

**Comment by ycli12** [comment]
I found dict table maybe the solution

**Comment by ycli12** [comment]
dict not support bitmap

**Comment by yariks5s** [comment]
Hi @ycli12!
1.  One of the key ways to optimize joins, especially in large datasets, is to reduce the volume of data being joined as much as possible beforehand. You can do this by filtering rows in subqueries before the join happens:

``` SQL
SELECT 
    *,
    multiIf(bitmapContains(bms.hit_sid_exp_bm, a.sid), 1, bitmapContains(bms.hit_sid_control_bm, a.sid), 0, -1) AS group_id 
FROM 
    (SELECT * FROM a WHERE ds = today() /* and other possible filters */) AS filtered_a
INNER JOIN 
    (SELECT * FROM bms WHERE ds = today() /* and other possible filters */) AS filtered_bms
ON 
    filtered_a.ds = filtered_bms.ds
WHERE 
    group_id >=0 AND 
    (bitmapContains(filtered_bms.drilled_hit_uuid_exp_bm, filtered_a.uid) OR 
     bitmapContains(filtered_bms.drilled_hit_uuid_control_bm, filtered_a.uid))
```

2. Reconsider join conditions

Adjusting the join condition to be more selective or using techniques that can pre-compute parts of the join can help. For instance, if the group_id calculation can be precomputed and stored as a materialized view or column, it could reduce the computation needed during the join.

3. Adjust join and query settings

You’ve mentioned using `partial_merge` join, which is generally more memory efficient than hash join for large datasets. However, consider tuning the following settings further:

	•	`max_bytes_before_external_sort`: While you’ve set this to 50 GB, ensure that it aligns well with your system’s memory capacity. Overly large settings can cause excessive memory use.
	•	`enable_lazy_execution`: If available, this setting can optimize the processing by delaying the execution of certain operations until their results are actually required.
	•	`any_join_distinct_right_table_keys`: This setting can reduce the size of the right table in memory if duplicate keys are not necessary for the join logic.
	
	
Also, you can try splitting your query:
``` SQL
CREATE TEMPORARY TABLE intermediate_result AS
SELECT 
    a.*, 
    bms.hit_sid_exp_bm, 
    bms.hit_sid_control_bm,
    bms.drilled_hit_uuid_exp_bm, 
    bms.drilled_hit_uuid_control_bm
FROM 
    a 
INNER JOIN 
    bms ON a.ds = bms.ds;

SELECT 
    *,
    multiIf(bitmapContains(hit_sid_exp_bm, sid), 1, bitmapContains(hit_sid_control_bm, sid), 0, -1) AS group_id 
FROM 
    intermediate_result
WHERE 
    group_id >= 0 AND 
    (bitmapContains(drilled_hit_uuid_exp_bm, uid) OR 
     bitmapContains(drilled_hit_uuid_control_bm, uid));
```

**Comment by ycli12** [comment]
@yariks5s Thank you so much! I will try more filters before join.

**Comment by yariks5s** [comment]
Please let me know if you have any further questions

**Comment by ycli12** [comment]
@yariks5s thans a lot! Finanlly, I found a way to deal with the case by expand the bitmap using arrayJoin(bitmapToArray(bm)). Then we can use hash join very fast. But also pay attention to the cost of arrayJoin(bitmapToArray(bm)), which may take 10s+ in 10 millions dataset. However, I save the time by optimize other section of the SQL. So the final SQL is very fast and uses less memory.
