### ISSUE TITLE
GROUPING function casue error when input is ALIAS on distribured table

### ISSUE THREAD

**Issue by YishayM** [ClickHouse/ClickHouse#68602]
Describe what's wrong

GROUPING function doesn't recognize ALIAS column and throw an error on distribured table 
When I use `allow_experimental_analyzer=0` it working without errors

Does it reproduce on the most recent release?

Yes, on latest 
https://fiddle.clickhouse.com/49d59283-0fc2-4be1-91c0-a3882c31a0a5

How to reproduce
```
CREATE TABLE users (name String, score UInt8, user_level String ALIAS multiIf(score <= 3, 'LOW', score <= 6, 'MEDIUM', 'HIGH') ) ENGINE=Memory;

INSERT INTO users VALUES ('a',1);
INSERT INTO users VALUES ('b',2);
INSERT INTO users VALUES ( 'c', 50);

SELECT  user_level as level_alias,uniq(name) as name_alias, grouping (level_alias) as _totals 
FROM remote('127.0.0.{1,2}', default, users)
GROUP BY
	GROUPING SETS ((level_alias),
	())
```

Expected behavior

The GROUPING should recongize the alias column and retured results

**Comment by Sigma711** [comment]
I want to join it. @YishayM @max-vostrikov

**Comment by vdimir** [comment]
Different issue with similar query, but without `ALIAS` columns and with `group_by_use_nulls`

```sql
DROP TABLE IF EXISTS users;
CREATE TABLE users (name String, score UInt8 ) ENGINE=Memory;

INSERT INTO users VALUES ('a',1), ('b',2), ( 'c', 50);

SET group_by_use_nulls = 1;

SELECT name as level_alias, sum(score), grouping (level_alias)
FROM users
GROUP BY GROUPING SETS ((level_alias), ())
;
```
