### ISSUE TITLE
Create Function for Rename Column

### ISSUE THREAD

**Issue by picinato** [ClickHouse/ClickHouse#6861]
How can I create a clickhouse function similar to this?
```
function renameColumn(tableName,currentColumn,newColumn,currentColumnType) returns boolean 

begin
	alter table tableName add column newColumn currentColumnType;
	alter table tableName update newColumn=currentColumn where 1=1;
	alter table tableName drop column currentColumn;

	return true;
end
```

Today i make this in command sql and work very well

I would like call this function and rename column

**Comment by alexey-milovidov** [comment]
That's not so simple.

ADD and DROP column operations are out of replication queue and may be reordered with UPDATE that is handled with replication queue. Care should be taken (you have to wait for every operation before running next operation).

That's why we don't implement RENAME COLUMN operation right now. It requires to rework ADD/DROP column. This task is in our schedule and @alesapin will do.

**Comment by picinato** [comment]
I couldn't create functions, correct?  
Sometimes I miss some functions like RANK and DENSE_RANK and ROW_NUMBER

To create something like the example above, it doesn't work for everyone but in my context it would work.

This works for me because I don't use identical tables on other servers. Each server has a task in my server park, so for my work there is no need to change and replicate on other servers.

--------------- x ------------------
I inform you that I also modified my JDBC to accept the default update commands from other databases.

update table set column = value where filter
translate to
alter table nametable update column = value where filter

delete from table
translate to
alter table nametable delete where 1 = 1

delete from table where filter
translate to
alter table nametable delete where filter

Since I needed to use my ETL tools, I am translating JDBC client level commands myself

I am still implementing the part of table creation which will change everything that comes as varchar (size) to String and the other types.

So we don't have to exchange all our existing tools.

I have really enjoyed the clickhouse and I am implementing in the company I work for.
--------------- x ------------------

**Comment by den-crane** [comment]
@picinato alter  update  / delete works asynchronously. They could work for hours.
You should check the result of  the update using `select * from system.mutations where parts_todo >0;` before dropping the original column.

**Comment by picinato** [comment]
So I need to create a function or stored procedure that waits for processes to finish. Or loop it to see if the parts_to_do column is filled and then drop the previous column.

But explain one thing to me if I use the IDE for example DBeaver and launch separate commands when dbeaver returns to me that finished means the process ended correctly? Or is it running in the backgroud?

**Comment by den-crane** [comment]
https://clickhouse.yandex/docs/en/query_language/alter/#alter-mutations

_A mutation query returns immediately after the mutation entry is added (in case of replicated tables to ZooKeeper, for nonreplicated tables - to the filesystem). The mutation itself executes asynchronously using the system profile settings. To track the progress of mutations you can use the system.mutations table. A mutation that was successfully submitted will continue to execute even if ClickHouse servers are restarted._

**Comment by picinato** [comment]
This really is a problem that makes an ETL process flow impossible. I thought the update command would return me successfully only if everything was already updated in the database.
If so, I can't use the updated column right after returning the update command in ETL.

**Comment by filimonov** [comment]
Related: #146 #3243

BTW, maybe doable in a way similar to proposal https://github.com/yandex/ClickHouse/issues/6787 ?

**Comment by alexey-milovidov** [comment]
> maybe doable in a way similar to proposal #6787

It's doable but more cumbersome.

**Comment by picinato** [comment]
I created new because another is very old. If i not use replicated servers, i can use this method for rename column without problem ?

Update work assichronous in only one server?  I send update for my IDE and she reply terminated really finishrd or running in background.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by alexey-milovidov** [comment]
Not stale.

**Comment by picinato** [comment]
I'm waiting is an important feature.

**Comment by alexey-milovidov** [comment]
This task is in the queue. It will be possible to implement only after converting ALTER of columns to mutations mechanics.

**Comment by inv2004** [comment]
Is it possible to add something like
ALTER TABLE t1 UPDATE .... **FINISH**

Because it is very hard to write migration scripts mixing sync and async commands.
This "FINISH" would not fix initial problem, but could be useful in many cases.

**Comment by alexey-milovidov** [comment]
It's good idea!
I'm not sure how easy is to add it. Let's ask @alesapin, he is currently working on ALTERs and mutations.

**Comment by alesapin** [comment]
> Is it possible to add something like
> ALTER TABLE t1 UPDATE .... **FINISH**
> to wait until the mutation is complete.
> 
> Because it is very hard to write migration scripts mixing sync and async commands.
> This "FINISH" would not fix initial problem, but could be useful in many cases.

We already have setting for this, https://github.com/ClickHouse/ClickHouse/pull/8237.

**Comment by filimonov** [comment]
Normal column renames were delivered in  #9948 

Sync mutations in #8237.
