### ISSUE TITLE
Ability to bootstrap with variable random seed.

### ISSUE THREAD

**Issue by linhgiang24** [ClickHouse/ClickHouse#68625]
**Company or project name**

Ability to bootstrap with variable random seed.

**Use case**

User has a collection of data that needs to be bootstrapped several times.  They need to create B bootstraps of N elements from an initial sample of M elements (M > N); as well as to be able to easily make N and B variate.  Ideally, they would like to use rand64().
 
Current state:
In this very simple example, user  bootstraps it 2 times, taking 2 samples each time.  With a fixed seed, you get twice the same results. If seed is removed, it's the same. 
 
They tried using rand64() but groupArraySample does only accept literals, and passing x as a second argument of groupArraySample also raises an error, saying there is no x column.
 
```
WITH to_bootstrap AS (
SELECT number AS data FROM numbers(1, 10)
)
SELECT
arrayMap(
x -> groupArraySample(2, 363633)(data),
array(1,2)) AS bootstraps
FROM to_bootstrap
```

<img width="458" alt="Screenshot 2024-08-20 at 9 50 02 AM" src="https://github.com/user-attachments/assets/f58b0d74-a2fb-4c47-b468-7337552f5e9e">

<img width="930" alt="Screenshot 2024-08-20 at 9 44 28 AM" src="https://github.com/user-attachments/assets/fada0802-cc51-46e0-85de-653cb435839f">

**Describe the solution you'd like**

Using the example provided above, user would like:

- each sub-arrays to be different of each other for a given execution
- to be able to use rand64()

**Describe alternatives you've considered**
Here are a couple potential workarounds but looking for a more simplified solution.  
https://fiddle.clickhouse.com/cd5b0a7a-7cf2-460d-ac01-4c4975fee5b8
https://fiddle.clickhouse.com/9cf0ff1f-1bfb-482c-b60c-7a1ff19efc6e

**Comment by linhgiang24** [comment]
One simple/potential workaround:
https://fiddle.clickhouse.com/cd5b0a7a-7cf2-460d-ac01-4c4975fee5b8

```
clickhouse-cloud :) with to_bootstrap as (select rand() as rand from system.numbers limit 4)
select
    arrayMap(x -> x%10, arraySlice(groupArray(rand), 1, 4)) as arr,
    arrayMap((x,y) -> (x,y), arraySlice(arr,1,2) , arraySlice(arr,3,4)) as bootstraps
from to_bootstrap;

WITH to_bootstrap AS
    (
        SELECT rand() AS rand
        FROM system.numbers
        LIMIT 4
    )
SELECT
    arrayMap(x -> (x % 10), arraySlice(groupArray(rand), 1, 4)) AS arr,
    arrayMap((x, y) -> (x, y), arraySlice(arr, 1, 2), arraySlice(arr, 3, 4)) AS bootstraps
FROM to_bootstrap

Query id: d6234901-5e62-492e-89cd-37b593bc5b85

   ┌─arr───────┬─bootstraps────┐
1. │ [8,5,7,0] │ [(8,7),(5,0)] │
   └───────────┴───────────────┘

1 row in set. Elapsed: 0.003 sec.
```

**Comment by DerekChia** [comment]
A simpler solution

```
WITH
    3 AS N,
    5 AS M,
    5 AS MIN_RANGE,
    20 AS MAX_RANGE,
    arr AS
    (
        SELECT arrayMap(x -> ((x % ((MAX_RANGE - MIN_RANGE) + 1)) + MIN_RANGE), range(1, N + 1) * rand()) AS x
        FROM system.numbers
        LIMIT M
    )
SELECT groupArray(x) AS bootstrap
FROM arr

   ┌─bootstrap───────────────────────────────────────────┐
1. │ [[8,11,14],[18,15,12],[13,5,13],[20,19,18],[6,7,8]] │
   └─────────────────────────────────────────────────────┘
```

**Comment by linhgiang24** [comment]
A simplified code could be:
```
WITH
    2 as N,
    5 as M,
    3 as B,
    5 as MIN_RANGE, -- inclusive
    20 as MAX_RANGE -- inclusive
SELECT 
    initial_sample,
    arrayFlatten(arrayMap(x -> arrayResize([1], N, 0), range(0, B))) as split_rules,
    arraySplit((x, y) -> y, initial_sample, split_rules) AS bootstrap
FROM (
    SELECT
        groupArray(data) AS initial_sample
    FROM (
        SELECT  
            (rand()%(MAX_RANGE-MIN_RANGE+1)) + MIN_RANGE as data
        FROM system.numbers 
        LIMIT N*B
    )
)
```

However in this case, it does not bootstrap the original data again. It's taken consecutively. What would be great would be to have something like:
```
arraySelect([1, 2, 3, 4, 5], [[1,1,0,0,0], [0,0,1,1,0], [1,0,0,0,1]]) that returns [[1, 2], [3,4], [1,5]] 
arraySelect([1, 2, 3, 4, 5], [[0,1,0,0,1], [1,1,0,0,0], [0,0,1,1,0]]) that returns [[2, 5], [1, 2], [3, 4]]
```

Also tried: https://clickhouse.com/docs/en/sql-reference/functions/array-functions#arrayrandomsample instead of initial `groupArraySample`
 
But the result is the same, and there is no possibility to pass any seed. 

```
WITH
    2 as N,
    5 as M,
    3 as B,
    5 as MIN_RANGE, -- inclusive
    20 as MAX_RANGE -- inclusive
SELECT 
    initial_sample,
    arrayMap(x -> arrayRandomSample(initial_sample, N), range(0, B)) AS bootstrap
FROM (
    SELECT
        groupArray(data) AS initial_sample
    FROM (
        SELECT  
            (rand()%(MAX_RANGE-MIN_RANGE+1)) + MIN_RANGE as data
        FROM system.numbers 
        LIMIT N*B
    )
)
```

**Comment by linhgiang24** [comment]
Here is the simple example:

```
WITH range(10) AS arr, number AS s
SELECT arraySlice(arraySort(x -> sipHash64(x, s), arr), 1, 5)
FROM numbers(7)
```

In this example, we take 7 deterministic random samples of 5 elements from the given array of 10 elements.

To make a deterministic pseudorandom permutation, we sort by `sipHash64` of array's values.
To make different permutations seeded by a certain value, we provide a second argument for `sipHash64`.

You can also use array indices for hashing instead of array values:

```
WITH range(10) AS arr, number AS s
SELECT arraySlice(arraySort((x, i) -> sipHash64(i, s), arr, arrayEnumerate(arr)), 1, 5)
FROM numbers(7)
```
