### ISSUE TITLE
Allow parallel REPLACE PARTITION to replace multiple partitions at once

### ISSUE THREAD

**Issue by italodamato** [ClickHouse/ClickHouse#68624]
**Use case**

In case many partitions need to be replaced, I'd like to be able to copy multiple partitions from table A to table B at the same time.

**Describe the solution you'd like**

I'd like to be able to run `ALTER TABLE table2 [ON CLUSTER cluster] REPLACE PARTITION 'part1', 'part2', 'part3' FROM table1` with the replacement happening in parallel.

It's fine if the individual partition swaps are atomical instead of the whole statement.

**Describe alternatives you've considered**

I've tried to run multiple statements one after the other but I think they get queued up instead of running in parallel (I'm not sure if there's a setting to prevent this).

**Comment by ne1r0n** [comment]
Does that work for you?

```
ALTER TABLE table2 [ON CLUSTER cluster]
    REPLACE PARTITION 'part1' FROM table1,
    REPLACE PARTITION 'part2' FROM table1,
    REPLACE PARTITION 'part3' FROM table1;
```
