### ISSUE TITLE
ATTACH TABLE: DB::Exception: Cannot parse input: expected 'eof' before: '33f1'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#68649]
https://fiddle.clickhouse.com/bb05bf1a-208d-4a37-abf6-3c60fb0ea3a6

```sql
ATTACH TABLE table2 UUID 'c0e6b2d4_5fb5_11ef_a9be_3bfb79a233f1' (a Int16) ENGINE=MergeTree ORDER BY ();
SHOW CREATE TABLE table2;
```
Head(24.9.1.955):
```
Code: 27. DB::Exception: Cannot parse input: expected 'eof' before: '33f1'. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)
```

24.7:
```
CREATE TABLE default.table2\n(\n    `a` Int16\n)\nENGINE = MergeTree\nORDER BY tuple()\nSETTINGS index_granularity = 8192
```

**Comment by nikitamikhaylov** [comment]
Previously we may mess up the UUID while creating a table with `_` as delimiter: https://fiddle.clickhouse.com/f106b9e9-4dc0-4677-83a3-63d6e2ae6b34

The actual change which caused this is: https://github.com/ClickHouse/ClickHouse/pull/52503 , I will mark it as a `backward-imcompatible`.

**Comment by alsugiliazova** [comment]
Thank you for explanation.
