### ISSUE TITLE
Cast as Nullable parser error

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#68648]
**Company or project name**

Clickhouse employee :smile: 

**Describe what's wrong**

Run:
```sql
SELECT CAST(1 AS `Nullable(Int)`);
```
gives:
```
Syntax error: failed at position 33 (')')
```
I would expect it to run successfully as 
```sql
SELECT CAST(1 AS `Int`); --1, no error
```

**Does it reproduce on the most recent release?**

Yes, https://fiddle.clickhouse.com/bd5302ab-42b8-40fa-925c-8f6382f95f66

**Expected behavior**

The cast shouldn't give a parser error.

**Comment by den-crane** [comment]
This is unexpected:

```
SELECT CAST(1 AS `Int`);  OK

SELECT CAST(1 AS "Int"); OK
```

psql

```
psql> SELECT CAST(1 AS "Int");
ERROR:  type "Int" does not exist
LINE 1: SELECT CAST(1 AS "Int");
          
               ^
psql> SELECT CAST(1 AS 'Int');
ERROR:  syntax error at or near "'Int'"
LINE 1: SELECT CAST(1 AS 'Int');
                         ^

MariaDB [dw]> SELECT CAST(1 AS "Int");
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"Int")' at line 1

MariaDB [dw]> SELECT CAST(1 AS `Int`);
ERROR 4161 (HY000): Unknown data type: 'Int'
```

**Comment by alexey-milovidov** [comment]
The behavior is correct.

There is no data type with the name `Nullable(Int)`. But there is a parameterized data type, Nullable, which accepts another data type in parameters.

You can provide the whole expression as a string literal or directly.
However, providing it as an identifier is incorrect.

**Comment by PedroTadim** [comment]
However strangely for the new JSON type, this works:

```sql
SELECT json.a.:`Nullable(Int)` FROM test;
```
but this does not

```sql
SELECT json.a::`Nullable(Int)` FROM test; --Syntax error: failed at position 34 ('FROM'):
```

**Comment by alexey-milovidov** [comment]
@Avogar already explained it to me. The reason is that `.:` isn't a casting operator but a subcolumn selection.
