### ISSUE TITLE
Additional metric to Prometheus endpoint

### ISSUE THREAD

**Issue by zurikus** [ClickHouse/ClickHouse#68655]
### Company or project name

NeoGroup

### Question

Is it possible to add additional metrics to Prometheus monitoring endpoints both for Clickhouse and Keeper, to check if Clickhouse and Keeper processes itself are running? 

Something like 
ch_up - 1 | 0 ( boolean ) 
keeper_up - 1 | 0 ( boolean ) 

Thank you in advance.

**Comment by nikitamikhaylov** [comment]
There is an asynchronous metric for Server called Uptime. But if you want an additional one - please create a PR.
