### ISSUE TITLE
Attempt to use column N in a filter condition results in column N-1 being used instead

### ISSUE THREAD

**Issue by jvnuw** [ClickHouse/ClickHouse#68691]
**Company or project name**

Upollo Pty Ltd

**Describe the unexpected behaviour**
Specifying constant data for a column twice can result in a filter condition which tries to use column N instead using column N-1.

**How to reproduce**
Clickhouse Cloud version 24.5.1.22957

```
with users as (
  select
    'bob1' as id,
    'bob' as name,
    'bob' as name,
    toDateTime64('2024-01-02 03:45:67', 6) as ts,
    false as is_deleted
  union all
  select
    'bob2' as id,
    'bob' as name,
    'bob' as name,
    toDateTime64('2024-01-02 03:45:67', 6) as ts,
    false as is_deleted
)
select id, is_deleted from users where is_deleted
```

**Expected behavior**
Either an error because the same column is given two values (despite them being identical), or for the query to execute successfully and return no results.

**Error message and/or stacktrace**
{ "meta": [ ], "data": [ ], "rows": 0, "exception": "Code: 59. DB::Exception: Illegal type DateTime64 of column for constant filter. Must be UInt8 or Nullable(UInt8). (ILLEGAL_TYPE_OF_COLUMN_FOR_FILTER) (version 24.5.1.22957 (official build))" }

**Additional context**
The DateTime64 type the error is complaining about appears to come from the ts columns, despite the filter referencing the is_deleted column.

**Comment by hanfei1991** [comment]
it can work in master, please update

```
fei-XPS :) with users as (
  select
    'bob1' as id,
    'bob' as name,
    'bob' as name,
    toDateTime64('2024-01-02 03:45:67', 6) as ts,
    false as is_deleted
  union all
  select
    'bob2' as id,
    'bob' as name,
    'bob' as name,
    toDateTime64('2024-01-02 03:45:67', 6) as ts,
    false as is_deleted
)
select id, is_deleted from users where is_deleted;

WITH users AS
    (
        SELECT
            'bob1' AS id,
            'bob' AS name,
            name,
            toDateTime64('2024-01-02 03:45:67', 6) AS ts,
            false AS is_deleted
        UNION ALL
        SELECT
            'bob2' AS id,
            'bob' AS name,
            name,
            toDateTime64('2024-01-02 03:45:67', 6) AS ts,
            false AS is_deleted
    )
SELECT
    id,
    is_deleted
FROM users
WHERE is_deleted

Query id: e1591a71-adc1-4d6b-8238-b69c9150a63a

Ok.

0 rows in set. Elapsed: 0.004 sec. 
```
