### ISSUE TITLE
CANNOT_PARSE_DATETIME exception while using toDateTime64(0,1) in condotion on distributed table 

### ISSUE THREAD

**Issue by YishayM** [ClickHouse/ClickHouse#68714]
Describe what's wrong

When running` IF(start_time IN (toDateTime64(0,1)), 0,1) ` on distributed table error thrown
Unknown enum value: 0

Does it reproduce on the most recent release?

Yes, on latest https://fiddle.clickhouse.com/02bf69fd-b35f-4038-b826-77d673e38c9c

How to reproduce

CREATE TABLE users (start_time  DateTime64) ENGINE=Memory;

SELECT IF(start_time IN (toDateTime64(0,1)), 0,1)  
FROM remote('127.0.0.{1,2}', default, users)

Expected behavior

Return response without error

**Comment by Avogar** [comment]
Was fixed in https://github.com/ClickHouse/ClickHouse/pull/68323
