### ISSUE TITLE
-OrDefault get NULL return

### ISSUE THREAD

**Issue by myshzzx** [ClickHouse/ClickHouse#68773]
clickhouse 24.6

```sql
select n, sumOrDefault(s) sd
from (select number n, NULL s from numbers(2))
group by n
```
![image](https://github.com/user-attachments/assets/f4a9d441-e6da-426f-802b-dcfa6a0d21a6)

here I get NULL in sd column, even if s colmnm type is Nullable(Int64).
what I expect is 0 in sd column.

**Comment by UnamedRus** [comment]
default value for Nullable data type is Null.

```
SELECT
    n,
    sumOrNull(s) AS sd,
    sumOrNullIf(s, 0)
FROM
(
    SELECT
        number AS n,
        0 AS s
    FROM numbers(2)
)
GROUP BY n AS res


┌─n─┬─sd─┬─sumOrNullIf(s, 0)─┐
│ 0 │  0 │              ᴺᵁᴸᴸ │
│ 1 │  0 │              ᴺᵁᴸᴸ │
└───┴────┴───────────────────┘
```

**Comment by myshzzx** [comment]
> default value for Nullable data type is Null.

but a non Nullable data type doesn't need a DEFAULT value, right?  use sumOrDefaultIf on a non nullable type doesn't make sense, that's counterintuitive.

**Comment by den-crane** [comment]
> > default value for Nullable data type is Null.
> 
> but a non Nullable data type doesn't need a DEFAULT value, right? use sumOrDefaultIf on a non nullable type doesn't make sense, that's counterintuitive.


It is needed to be ANSI compatible.

```
psql 
\pset null '<null>'

 select sum(x) from (select 1 x where 1=0) t;
  sum
--------
 <null>
(1 row)
```

```
select sum(x) from (select 1 x where 1=0) t;
┌─sum(x)─┐
│      0 │
└────────┘

select sumOrNull(x) from (select 1 x where 1=0) t;
┌─sumOrNull(x)─┐
│         ᴺᵁᴸᴸ │
└──────────────┘
```
