### ISSUE TITLE
Slow performance for bitmap functions

### ISSUE THREAD

**Issue by yingfeng** [ClickHouse/ClickHouse#6880]
`cdp_tags` is a table where bitmap intermediate state is stored as a column:

```
CREATE TABLE cdp_tags ( \
    tag_id String, \
    mid_seqs AggregateFunction(groupBitmap, UInt32), \
    cardinality UInt32 \
) engine=ReplacingMergeTree() \
ORDER BY (tag_id) SETTINGS index_granularity=1;
```
There are altogether over 3000 records over this table:

```
SELECT count(*)
FROM cdp_tags

┌─count()─┐
│    3752 │
└─────────┘

1 rows in set. Elapsed: 0.012 sec. Processed 3.75 thousand rows, 15.01 KB (315.92 thousand rows/s., 1.26 MB/s.)
```

`index_granularity` is set to `1` because each record within this table is pretty large, without this config by default, the time elapsed to select single record requires 4.5s, as show below: 
```
SELECT count(*)
FROM
(
    SELECT mid_seqs
    FROM cdp_tags
    WHERE tag_id = 'first_buy_market_NA'
)

┌─count()─┐
│       1 │
└─────────┘

1 rows in set. Elapsed: 4.514 sec.
```
While after `index_granularity` is set to `1`, the time is reduced to trivial:
```
SELECT count(*)
FROM
(
    SELECT mid_seqs
    FROM cdp_tags
    WHERE tag_id = 'first_buy_market_NA'
)

┌─count()─┐
│       1 │
└─────────┘

1 rows in set. Elapsed: 0.161 sec.
```

Let us see the performance of bitmap functions, the first SQL contains single subquery:
```

SELECT bitmapCardinality(
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'first_buy_market_NA'
    ))

┌─bitmapCardinality(_subquery9)─┐
│                       6440561 │
└───────────────────────────────┘

1 rows in set. Elapsed: 1.291 sec.
```

The second SQL contains two subqueries:
```
SELECT bitmapAnd(
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'first_buy_market_NA'
    ),
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'first_buy_province_广东省'
    ))

┌─bitmapAnd(_subquery10, _subquery11)─┐
│                                     │
└─────────────────────────────────────┘

1 rows in set. Elapsed: 3.324 sec.
```

The third SQL contains four subqueries:
```
SELECT bitmapAndCardinality(bitmapAnd(bitmapAnd(
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'first_buy_market_NA'
    ),
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'first_buy_province_广东省'
    )),
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'member_origin_channel_NA'
    )),
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'mobile_province_NA'
    ))

┌─bitmapAndCardinality(bitmapAnd(bitmapAnd(_subquery12, _subquery13), _subquery14), _subquery15)─┐
│                                                                                              0 │
└────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 19.888 sec.
```

We could see that the more number of subqueries, the larger time required---but much larger than linearly increased according to the amount of subqueries. 

We think the major query overhead happens during the SQL pipeline itself, because if we execute following query which also contains 4 bitmaps, it's much faster:
```
SELECT groupBitmapMerge(mid_seqs)
FROM cdp_tags
WHERE has(['first_buy_market_NA', 'first_buy_province_广东省', 'member_origin_channel_NA', 'mobile_province_NA'], tag_id)

┌─groupBitmapMerge(mid_seqs)─┐
│                   48850537 │
└────────────────────────────┘

1 rows in set. Elapsed: 1.826 sec. Processed 3.75 thousand rows, 269.21 KB (2.05 thousand rows/s., 147.41 KB/s.)
```

Additionally, the flag of `SET experimental_use_processors = 1` does not help, it could even increase the overall query time for the above situations.

What's the reason for the performance issue? And how could I improve the query performance such that the overall time is increased just linearly according to the number of bitmap records? 

The version of Clickhouse used: `v19.13.2.19-stable`

**Comment by yingfeng** [comment]
The output of `callgrind` is attached.
[callgrind.out.2454.zip](https://github.com/yandex/ClickHouse/files/3594444/callgrind.out.2454.zip)

It has contained the overhead for bootstrapping, together with several queries.
We could see that the serialization/deserialization have occupied dominant percentage:

<img width="1495"  src="https://user-images.githubusercontent.com/7248/64595573-cef9ea80-d3e4-11e9-9a10-ae169a0f2ed7.png">

<img width="1416" src="https://user-images.githubusercontent.com/7248/64595925-8262df00-d3e5-11e9-98cf-4a23af1d4112.png">

**Comment by filimonov** [comment]
Scalar subqueries are quite specific as executed on query parsing stage. 
But in should still give linear increase:
```
SELECT concat(
    (
        SELECT toString(min(rand()))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(1)))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(2)))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(3)))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(4)))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(5)))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(6)))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(7)))
        FROM numbers(50000000)
    ))

┌─concat(_subquery51, _subquery52, _subquery53, _subquery54, _subquery55, _subquery56, _subquery57, _subquery58)─┐
│ 371036413415712156                                                                                             │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 14.511 sec. 

SELECT concat(
    (
        SELECT toString(min(rand()))
        FROM numbers(50000000)
    ), 
    (
        SELECT toString(min(rand(1)))
        FROM numbers(50000000)
    ))

┌─concat(_subquery59, _subquery60)─┐
│ 413319                           │
└──────────────────────────────────┘

1 rows in set. Elapsed: 3.622 sec. 

SELECT 14.5 / 3.6

┌─divide(14.5, 3.6)─┐
│ 4.027777777777778 │
└───────────────────┘

1 rows in set. Elapsed: 0.072 sec. 
```

So scalar subqueries itself should not be an issue.

**Comment by filimonov** [comment]
BTW: does it help if you will add partitioning, for example by xxHash32(tag_id) % 512 or similar?

**Comment by yingfeng** [comment]
@filimonov 
It does not help when adding partitioning, the performance is even a little worse.

We have found the serialization/deserialization for `RoaringBitmapWithSmallSet` is not the same with the original one from `CRoaring`, we have change it into the [original implementation from `CRoaring`](https://github.com/yandex/ClickHouse/files/3598270/croaring.patch.zip), and the performance is improved a lot:

```
Query 1:
SELECT bitmapCardinality((SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_market_NA'))
Query 2:
SELECT count(*) FROM (SELECT bitmapCardinality((SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_market_NA')))
Query 3:
SELECT count(*) FROM(SELECT bitmapAnd((SELECT mid_seqs FROM cdp_tags WHERE tag_id='member_origin_channel_NA'),(SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_province_广东省')))
Query 4:
SELECT bitmapCardinality(bitmapAnd((SELECT mid_seqs FROM cdp_tags WHERE tag_id='member_origin_channel_NA'),(SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_province_广东省')))
Query 5:
SELECT bitmapCardinality(bitmapAnd((SELECT mid_seqs FROM cdp_tags WHERE tag_id='member_origin_channel_NA'),bitmapBuild([1,2,3,12345678])))
Query 6:
SELECT bitmapAndCardinality(bitmapAnd(bitmapAnd((SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_market_NA'), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_province_广东省')), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='member_origin_channel_NA')), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='mobile_province_NA') );
```
The performance comparison is list below:
```
Before vs After
Query 1: 1.27s vs 0.57s
Query 2: 2.1s vs 0.77s
Query 3: 15.2s vs 6.55s
Query 4: 9.7s vs 4.45s
Query 5: 7.667s vs 3.78s
Query 6: 22.55s vs 8.57s
```

However, it's still far from satisfying, given Query 6, the time spent on bitmap and operation itself is less than 1 second, and the more scalar sub queries there exist, the slower performance. (we have experimented similar CRoaring plugins on PostgreSQL and GreenPlum, similar query will take less than 1 second even with a much less sub queries).




PS, the attached patch will be sent as a PR later.

**Comment by yuzhichang** [comment]
PR is #6908.

**Comment by andyyzh** [comment]
@yingfeng 
The test at that time was slow to use croaring serialization/deserialization, 
and later, change to use clickhouse's own serialization/deserialization.

**Comment by alexey-milovidov** [comment]
@andyyzh @yingfeng You should add a performance test, so we can control it in CI.

**Comment by andyyzh** [comment]
@yingfeng  please add my Weixin: yangzhaohui168
Discuss a lot of this.

**Comment by yingfeng** [comment]
Update:

We've implemented bitmap aggregate functions such that some bitmapAnd and bitmapOr could be replaced with aggregate functions. PR will be submitted later, just like the only existing one:`groupBitmapMerge`. The performance is improved a lot, around tens of times faster for huge bitmaps.

For example:
```
SELECT bitmapAndCardinality(bitmapAnd(bitmapAnd((SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_market_NA'), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_province_广东省')), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='member_origin_channel_NA')), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='mobile_province_NA') );

```
Such query will take above 8.5s, while using aggregate functions will only take 0.25s.

However, if some non-aggregated bitmap functions have to be used together with the aggregated ones, the serialization overhead is remarkably high.  
For example:
```
SELECT bitmapCardinality(
    (
        SELECT groupBitmapMergeState(mid_seqs)
        FROM cdp_tags
        WHERE has(['first_buy_market_NA', 'mobile_province_NA', 'member_origin_channel_NA'], tag_id)
    ))

┌─bitmapCardinality(_subquery3)─┐
│                      48850537 │
└───────────────────────────────┘

1 rows in set. Elapsed: 4.209 sec.
```
While given a small set using `And` semantic, the latency is reduced a lot:
```
SELECT bitmapCardinality(
    (
        SELECT aggBitmapAndMergeState(mid_seqs)
        FROM cdp_tags
        WHERE has(['first_buy_market_NA', 'mobile_province_NA', 'member_origin_channel_NA'], tag_id)
    ))

┌─bitmapCardinality(_subquery2)─┐
│                       2528904 │
└───────────────────────────────┘
1 rows in set. Elapsed: 0.394 sec.
```
Where `aggBitmapAndMergeState` is the newly added bitmap aggregate function to be submitted later.

Through the result of `callgrind` could we see that the major overhead comes from the serialization. 

<img width="1019" src="https://user-images.githubusercontent.com/7248/65235011-5a236080-db08-11e9-86c0-1606c19b7baf.png">

`writeAnyEscapedString` has taken around 50% of the query overhead, which has also been mentioned in PR [6773](https://github.com/yandex/ClickHouse/pull/6773).  If somebody could help to resolve this issue, it could be much helpful, since it's not reasonable to have the binary data of bitmap state re-formatted using escaped string.
@alexey-milovidov 


The `callgrind` file is attached [here](https://github.com/yandex/ClickHouse/files/3630555/callgrind.out.43839.zip).

**Comment by yingfeng** [comment]
Update

PR [7109](https://github.com/ClickHouse/ClickHouse/pull/7109) has been submitted, which introduces aggregation families to bitmap functions. In cases that aggregate bitmap functions could replace non-aggregate bitmap ones, the performance could be improved remarkably, because of the overhead of serialization of the later one, for example:

```
SELECT bitmapAndCardinality(bitmapAnd(bitmapAnd((SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_market_NA'), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='first_buy_province_广东省')), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='member_origin_channel_NA')), (SELECT mid_seqs FROM cdp_tags WHERE tag_id='mobile_province_NA') );

1 rows in set. Elapsed: 22.532 sec.

 SELECT aggBitmapAndMerge(mid_seqs)
        FROM cdp_tags
        WHERE has(['first_buy_market_NA', 'mobile_province_NA', 'member_origin_channel_NA','first_buy_province_广东省''], tag_id)
    )

1 rows in set. Elapsed: 0.494 sec.
```

It means a remarkably performance improvements whenever conversion from non-aggregation to aggregation is feasible. 

This issue has been relieved a lot by PR [7109](https://github.com/ClickHouse/ClickHouse/pull/7109), and might be closed if issue [6956](https://github.com/ClickHouse/ClickHouse/issues/6956) would be resolved.

**Comment by andyyzh** [comment]
nice!

**Comment by yingfeng** [comment]
Could be worked around through turning scalar subqueries into non-scalar ones. Two approaches are feasible:

1.  Using JOIN
```
SELECT bitmapAndCardinality(bitmapAnd(bm1,bm2),bm3)
FROM 
(
  SELECT 1 AS join_id1, groupBitmapAndState(mid_seqs) AS bm1
  FROM cdp_tags
  WHERE has(['tag1', 'tag2'], tag_id)
)
INNER JOIN
(
  SELECT 1 AS join_id2, groupBitmapAndState(mid_seqs) AS bm2
  FROM cdp_tags
  WHERE has(['tag2', 'tag3'], tag_id)
) ON join_id1=join_id2
INNER JOIN
(
  SELECT 1 AS join_id3, groupBitmapAndState(mid_seqs) AS bm3
  FROM cdp_tags
  WHERE has(['tag4', 'tag5'], tag_id)
) ON join_id2=join_id3
```
Such kinds of working  arounds are suitable if we only need to query on bitmap tables. Many thanks to @andyyzh .


2. Introducing temporary JOIN table, where const columns are used to bypass scalar subqueries, improved by PR [7359](https://github.com/ClickHouse/ClickHouse/pull/7359). This is could be used when aggregating tables according to bitmaps from other tables.
