### ISSUE TITLE
<Error> Application: Code: 139. DB::Exception: Keeper configuration (<keeper_server> section) not found in config. (NO_ELEMENTS_IN_CONFIG), Stack trace (when copying this message, always include the lines below):

### ISSUE THREAD

**Issue by erzichengzhou** [ClickHouse/ClickHouse#68838]
### Company or project name

![image](https://github.com/user-attachments/assets/51684fb5-f1f6-490c-8386-d5dc5a34f8a4)
![image](https://github.com/user-attachments/assets/f6679f49-735d-4dd2-bfdf-91949df7f1eb)
![image](https://github.com/user-attachments/assets/49e2d5a9-f3c2-4550-8dc8-dd2c0aad30cd)

### Question

I read in the documentation that Keeper can be deployed separately, so I deployed a separate Keeper cluster and integrated it with ClickHouse Server. However, when I tried to start the server, I got an error saying that the `keeper_server` configuration section was missing. Why is the server trying to start the Keeper process instead of using the configured external Keeper cluster? Thanks.

**Comment by OneDOTA2Player** [comment]
How do you deal with this problem, I encountered the same problem？

**Comment by quanbeisheng** [comment]
您好，我用二进制方式部署三台主机（3shard\2replica）clickhouse服务时，启动第一台主机上的两个实例时，config1.xml配置文件里存在<keeper_server>标签正常启动，config2.xml配置文件里无<keeper_server>标签，也是提示如上错误，进程无法启动，请问如何解决？ 感激不尽

**Comment by limingqihust** [comment]
I meet the same error. How do you fix it?
