### ISSUE TITLE
Test `03228_virtual_column_merge_dist` has failed

### ISSUE THREAD

**Issue by thevar1able** [ClickHouse/ClickHouse#68880]
https://s3.amazonaws.com/clickhouse-test-reports/68639/8cc5d766b5d70f22646e6dc2832f806736c76311/stateless_tests__release__old_analyzer__s3__databasereplicated__[2_2].html

**Comment by nikitamikhaylov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/68841
