### ISSUE TITLE
DB::Exception: Not found column Attributes.keys in block NOT_FOUND_COLUMN_IN_BLOCK

### ISSUE THREAD

**Issue by MacNale** [ClickHouse/ClickHouse#68904]
**Describe the unexpected behaviour**
I am using clickhouse (24.9.1).  It looks like the latest release broke the materialized view which used to work fine in 24.3 release.
"DB::Exception: Not found column Attributes.keys in block"

**How to reproduce**
```
CREATE TABLE mydb.rawtable
(
  `Id` UInt64 CODEC(Delta(8), ZSTD(1)),
  `Attributes` Map(LowCardinality(String), String) CODEC(ZSTD(1)),
  `MetricName` LowCardinality(String) CODEC(ZSTD(1)),
  `TimeUnix` DateTime CODEC(Delta(8), ZSTD(1))
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(TimeUnix)
ORDER BY (MetricName, Attributes, toUnixTimestamp(TimeUnix))

CREATE MATERIALIZED VIEW mydb.raw_to_attributes_mv TO mydb.attributes
(
  `Id` UInt64,
  `MetricName` LowCardinality(String),
  `TimeUnix` DateTime,
  `AttributeKeys` Array(LowCardinality(String)),
  `AttributeValues` Array(String)
)
AS SELECT
  Id,
  MetricName,
  toStartOfDay(TimeUnix) AS TimeUnix,
  mapKeys(Attributes) AS AttributeKeys,
  mapValues(Attributes) AS AttributeValues
FROM mydb.rawtable

CREATE TABLE mydb.attributes
(
  `Id` UInt64 CODEC(Delta(8), ZSTD(1)),
  `MetricName` LowCardinality(String) CODEC(ZSTD(1)),
  `TimeUnix` DateTime CODEC(Delta(8), ZSTD(1)),
  `AttributeKeys` Array(LowCardinality(String)) CODEC(ZSTD(1)),
  `AttributeValues` Array(String) CODEC(ZSTD(1))
)
ENGINE = ReplacingMergeTree
PARTITION BY toYYYYMMDD(TimeUnix)
ORDER BY (MetricName, Id, TimeUnix) 
```

* Which ClickHouse server version to use
24.9.1

* Queries to run that lead to unexpected result

insert into rawtable values (1, {'key1': 'value1', 'key2': 'value2'}, 'm1', now())

**Expected behavior**
This used to work in 24.5. 

**Error message and/or stacktrace**
DB::Exception: Not found column Attributes.keys in block. There are only columns: Id, Attributes, MetricName, TimeUnix: while pushing to view mydb.raw_to_attributes_mv. (NOT_FOUND_COLUMN_IN_BLOCK)

**Comment by nikitamikhaylov** [comment]
Looks like a regression between `24.7` and `24.8`: 
- `24.8` and current version: https://fiddle.clickhouse.com/b4524f16-f23c-4a29-9e5a-758f3aa7c3cd
- `24.7` and previous versions work fine: https://fiddle.clickhouse.com/74ce2051-0619-4f7d-8370-9f040284321b

**Comment by max-vostrikov** [comment]
Found the reason, it is `optimize_functions_to_subcolumns`.
It got enabled by default in https://github.com/ClickHouse/ClickHouse/pull/68053
[SET optimize_functions_to_subcolumns = false;](https://fiddle.clickhouse.com/04974f4b-07c0-4f07-86b0-f643921b1510) removes the error
