### ISSUE TITLE
WHERE pushdown does not work with the production analyzer, join and non-equivalent expression

### ISSUE THREAD

**Issue by BorisTyshkevich** [ClickHouse/ClickHouse#68913]
On the latest version, the query:
```
select * from (
    SELECT    p_date, b.bucket_id
    FROM       example a
    JOIN         buckets b
    ON            a.bucket_id=b.bucket_id 
    where       score >= b.score  
)
WHERE p_date between '2024-08-20' and '2024-08-21'
SETTINGS allow_experimental_analyzer = 1;
```
 gets a full table scan; PK is not used.

Full example with data:
https://fiddle.clickhouse.com/9c705620-5391-4b78-bd46-245d5416da7b

With the old analyzer, ASOF JOIN or manual pushdown PK filer works fine.

**Comment by SaltTan** [comment]
Another test https://fiddle.clickhouse.com/647ef5c5-9941-4a30-8101-a74ec3c44c5c

**Comment by KochetovNicolai** [comment]
Should be fixed aftefr https://github.com/ClickHouse/ClickHouse/pull/71964
