### ISSUE TITLE
When using a third-party Kubernetes operator, which is not supported at all: Follower keepers have significant higher znode count than the leader keeper node

### ISSUE THREAD

**Issue by boqu** [ClickHouse/ClickHouse#69059]
### Question

We run a self-managed Clickhouse cluster with Altinity Clickhouse Operator in EKS. We upgrade both clickhouse-keeper and clickhouse server from 24.4 to 24.6. There are 3 keepers node and 1 shard with 2 replicas. The upgrade was not smooth. It caused some replicated tables turning into readonly mode. We used forcerestore and even had to re-create a few tables to get the cluster stablized. Now we are having a new abnormal behaviour with keepers.  2 follower keeper nodes have a significant higher znode count than leader keeper node. That leads to a higher snapshots files size/disk usage on those 2 follower keeper nodes. The znode count should be quite consistent across all keeper node in my understanding.

Leader node:
```
clickhouse-keeper-0:/# echo mntr | nc 127.0.0.1 2181
zk_version	v24.6.3.95-stable-8325c920d1102360c91b756da2eb32ae832fae8d
zk_avg_latency	0
zk_max_latency	2171
zk_min_latency	0
zk_packets_received	7795744986
zk_packets_sent	7808150518
zk_num_alive_connections	4
zk_outstanding_requests	0
zk_server_state	leader
zk_znode_count	34712
zk_watch_count	68
zk_ephemerals_count	28
zk_approximate_data_size	11691545
zk_key_arena_size	0
zk_latest_snapshot_size	1630958
zk_open_file_descriptor_count	61
zk_max_file_descriptor_count	1048576
zk_followers	2
zk_synced_followers	2
```

Follower node:
```
clickhouse-keeper-2:/# echo mntr | nc 127.0.0.1 2181
zk_version	v24.6.3.95-stable-8325c920d1102360c91b756da2eb32ae832fae8d
zk_avg_latency	0
zk_max_latency	0
zk_min_latency	0
zk_packets_received	0
zk_packets_sent	0
zk_num_alive_connections	0
zk_outstanding_requests	0
zk_server_state	follower
zk_znode_count	11354194
zk_watch_count	0
zk_ephemerals_count	2218422
zk_approximate_data_size	4830106237
zk_key_arena_size	0
zk_latest_snapshot_size	442782461
zk_open_file_descriptor_count	41
zk_max_file_descriptor_count	1048576
```

Is there any good way(without lost any data) we can re-sync the follower with leader to have a consistent znode count?

**Comment by hodgesrm** [comment]
This looks at first glance like a problem with Keeper itself though it may have been triggered by Kubernetes, which would be helpful to understand in order to reproduce the problem. How are you running Keeper? Is it based on one of the StatefulSet yaml files in the operator project on GitHub?

p.s., I work on the Altinity operator (or more accurately with the operator maintainers).

**Comment by boqu** [comment]
Hi @hodgesrm , we are running Keeper as a statefulset. The configuration we use are similar to those on https://github.com/Altinity/clickhouse-operator/tree/release-0.23.0/deploy/clickhouse-keeper/clickhouse-keeper-manually overall, but not exactly same. E.g. we don't use configmap to contain start script/liveness probe script etc.

**Comment by ondrej-smola** [comment]
Hi @boqu could you please contact me on ClickHouse or Altinity Slack (Ondrej Smola) so we can try to debug it and post solution here?

**Comment by boqu** [comment]
Hi @ondrej-smola, I guess I need an invitation from ClickHouse community or Altinity Slack channel. Any idea how I can join the slack workspace for either of those two?

**Comment by ondrej-smola** [comment]
Both are public so you should be able to join using shared invite link
[Altinity](https://altinitydbworkspace.slack.com/join/shared_invite/zt-2n4mabbv7-GIqBUa4SmM~K~~Akb5mPJQ#/shared-invite/email)
[ClickHouse](https://clickhousedb.slack.com/join/shared_invite/zt-2o3tld9i9-o33lbnM0RRyaj8VgG5Nejw#/shared-invite/email)
