### ISSUE TITLE
clickhouse 并发度过高经常5分钟或者3分钟超时？timed out

### ISSUE THREAD

**Issue by moxuan12138** [ClickHouse/ClickHouse#69057]
### Question

并发任务过高？导致的180s 或者300s超时？请问这种问题是啥问题，并且这种问题该咋解决 ？ck数据库版本22.11.1.1360
![2bf1ae1f4232080ea209d7e8b43ec21](https://github.com/user-attachments/assets/1e56a047-8945-43a1-8866-ce86a0cc62c5)
![efa0382bd78ee48332aa22c07dc8c9e](https://github.com/user-attachments/assets/42a8e612-c543-4698-9fad-eb9df7efc23a)
![fb3c321397fb65d5267df8a052a9b44](https://github.com/user-attachments/assets/59b383de-ef0e-47c7-bac7-cc851dbba962)

**Comment by Algunenano** [comment]
22.11.1.1360 is unsupported. Upgrade to a supported release which will have better handling of ZooKeeper exceptions
