### ISSUE TITLE
column not found in live view .

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#69064]
Hi.

column not found in live view if remove alias from query!

clickhouse version : [v24.8.2.3-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v24.8.2.3-lts)
this query not work !
```sql
CREATE LIVE VIEW ahe.lv_meter_monitor (`schedule_time` DateTime ('Asia/Tehran'), `cnt` UInt64) AS
SELECT
  clock AS schedule_time,
  count() AS cnt
FROM
  ahe.mdm_log ml
WHERE
  (clock > addMinutes (now ('Asia/Tehran'), -3)) AND
  (log_type = 'Meters') AND
  (status = 'Success')
GROUP BY
  clock SETTINGS allow_experimental_live_view = 1;
```

and this query not work successfully.
```sql
CREATE LIVE VIEW ahe.lv_meter_monitor (`schedule_time` DateTime ('Asia/Tehran'), `cnt` UInt64) AS
SELECT
  ml.clock AS schedule_time,
  count() AS cnt
FROM
  ahe.mdm_log ml
WHERE
  (ml.clock > addMinutes (now ('Asia/Tehran'), -3)) AND
  (ml.log_type = 'Meters') AND
  (ml.status = 'Success')
GROUP BY
  ml.clock SETTINGS allow_experimental_live_view = 1;
```

**Comment by max-vostrikov** [comment]
@mbtolou Could you provide a bit more details on how to reproduce this issue?
How do you create `ahe.mdm_log`, what is the data there, and what result you are receiving and expect to receive?

**Comment by mbtolou** [comment]
-- Active: 1724923494589@@10.118.144.156@8123@ahe
```
select version();
--24.8.2.3

create database test;

-- Active: 1643176518807@@192.168.160.22@8123@temp
CREATE TABLE test.commands_bus (
    `id` String DEFAULT generateUUIDv4 (),
    `create_time` DateTime('Asia/Tehran'),
    `sub_system` LowCardinality (String) COMMENT 'sub system ',
    `command` LowCardinality (String) COMMENT 'command name'
) ENGINE = ReplacingMergeTree
PARTITION BY
    toYYYYMMDD (create_time)
ORDER BY (id, create_time, command) SETTINGS index_granularity = 8192,
    merge_with_ttl_timeout = 10;

CREATE LIVE VIEW test.lv_commands_bus (
    `create_time` DateTime('Asia/Tehran'),
    `cnt` UInt64
) AS
SELECT
    create_time AS schedule_time,
    count() AS cnt
FROM test.commands_bus
WHERE
    create_time > addMinutes (now('Asia/Tehran'), -60)
GROUP BY
    create_time
ORDER BY
    create_time ASC SETTINGS allow_experimental_live_view = 1;

insert into
    test.commands_bus
values (
        1,
        now(),
        'test_subsystem',
        'reload info'
    );

select * from test.lv_commands_bus;
```

**Comment by mbtolou** [comment]
Thank you for your kindness; my issue has been resolved. Do I need to keep the issue open until the error is completely fixed?

**Comment by max-vostrikov** [comment]
I do not see an issue here

**Comment by mbtolou** [comment]
Despite your positive changes to the script, the issue is still there. I can't generate a script for the error, but the problem persists!

**Comment by max-vostrikov** [comment]
@mbtolou could you provide a bit more details on your problem? Wha is the issue now?

**Comment by mbtolou** [comment]
> @mbtolou It works for me with minor changes: https://fiddle.clickhouse.com/3d73465b-8932-4f0f-87ce-3189452e92e6 or https://fiddle.clickhouse.com/2539d52e-67f5-4c81-8cc5-fc13eb6f30af I've removed `AS schedule_time` in live view definition. Because the error specifically told that live view can't find `create_time`. Or use the new name `schedule_time` for the column. It is consistent with any other SQL syntax.
> 
> Does it solve your issue?

I made these changes in the code, and with the script I provided you, there's no more issue. However, when I try to monitor the table data through the watch function, I encounter an error saying the specified column couldn't be found. Apparently, in the new versions, "Live view" has problems with columns that use the alias!

**Comment by mbtolou** [comment]
Hi.

I made some changes to the query code. The code itself doesn’t cause any issues. It also doesn’t create any problems when we’re not using the "watch" command in clickhouse-client. However, when we try to monitor the "LIVE VIEW" via HTTP, and after inserting data into the commands_bus table through the HTTP Interface, we run into the following error:

`DB::Exception: Not found column success.null in block.`

I guess this might be related to the new analyzer.


```sql

select version();
--24.8.2.3

create database test;

--{EchoOn}}
CREATE TABLE test.commands_bus (
    `id` String DEFAULT generateUUIDv4 (),
    `create_time` DateTime('Asia/Tehran'),
    `sub_system` LowCardinality (String) COMMENT 'sub system ',
    `command` LowCardinality (String) COMMENT 'command name',
    `success` Nullable(UInt8)
) ENGINE = ReplacingMergeTree
PARTITION BY
    toYYYYMMDD (create_time)
ORDER BY (id, create_time, command) SETTINGS index_granularity = 8192,
    merge_with_ttl_timeout = 10;

CREATE LIVE VIEW test.lv_commands_bus (
    `schedule_time` DateTime('Asia/Tehran'),
    `cnt` UInt64
) AS
SELECT
    create_time AS schedule_time,
    count() AS cnt
FROM test.commands_bus
WHERE
    schedule_time > addMinutes (now('Asia/Tehran'), -60) and
    **success is null**
GROUP BY
    create_time
ORDER BY
    create_time ASC SETTINGS allow_experimental_live_view = 1;

insert into
    test.commands_bus
values (
        1,
        now(),
        'test_subsystem',
        'reload info',
        NULL
    );

select * from test.lv_commands_bus;



```

**Comment by mbtolou** [comment]
fixed by :

https://github.com/ClickHouse/ClickHouse/issues/65389#issuecomment-2176079899

```
cat /etc/clickhouse-server/users.d/allow_experimental_analyzer.xml
<?xml version="1.0" ?>
<clickhouse>
    <profiles>
        <default>
            <allow_experimental_analyzer>0</allow_experimental_analyzer>
        </default>
    </profiles>
</clickhouse>
```
