### ISSUE TITLE
Clickhouse v20.4.9.110 Unable to find installation package

### ISSUE THREAD

**Issue by Le6688** [ClickHouse/ClickHouse#69062]
### Company or project name

Hello
may I ask why I can't find clickhouse version 20.4.9.110 on the official website? It's like this because we have an environment on
site that is this version. I would like to download this version from the official website and install it for testing in the testing environment.
Thank you

### Question

Hello
may I ask why I can't find clickhouse version 20.4.9.110 on the official website? It's like this because we have an environment on
site that is this version. I would like to download this version from the official website and install it for testing in the testing environment.
Thank you

**Comment by Algunenano** [comment]
It's a 4+ year old release, so totally unsupported, but you can find it in https://packages.clickhouse.com/repo-archive/
