### ISSUE TITLE
clean up all the Replicated*MergeTree table information for a node in ZooKeeper

### ISSUE THREAD

**Issue by honobi** [ClickHouse/ClickHouse#69089]
### Question

Is there a way to clean up all the Replicated*MergeTree table information for a node in ZooKeeper?
I have used SYSTEM DROP REPLICA, but it didn't work. I also tried SYSTEM DROP REPLICA FROM ZKPATH, which was effective, but it only allows me to delete the replica information for a single table at a time.

**Comment by antonio2368** [comment]
`SYSTEM DROP REPLICA` should drop the replica along with all the Keeper info related to it.
Can you tell me why you think the nodes are not being cleaned after `DROP REPLICA` was called?
Each replicated table will create a single Keeper node which will act as a root table node. Under it (as a child of `replicas` node), all replicas will create their nodes. And those nodes are deleted when the replica is dropped.
