### ISSUE TITLE
`have_compressed` is not copied in `HashJoin::reusedJoinedData`

### ISSUE THREAD

**Issue by lgbo-ustc** [ClickHouse/ClickHouse#69135]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).

> You have to provide the following information whenever possible.

**Company or project name**

> Put your company name or project description here

**Describe what's wrong**

`have_compressed` is introduced in #65243. This field is not synchronized to the new `HashJoin` in `HashJoin::reusedJoinedData`. This could cause problem in `HashJoin::joinBlockImplCross` if the `have_compressed` is true
in the old `HashJoin`.

```c++
        for (const Block & block_right : data->blocks)
        {
            ++block_number;
            if (block_number < start_right_block)
                continue;

            /// The following statement cannot be substituted with `process_right_block(!have_compressed ? block_right : block_right.decompress())`
            /// because it will lead to copying of `block_right` even if its branch is taken (because common type of `block_right` and `block_right.decompress()` is `Block`).
            if (!have_compressed)
                process_right_block(block_right);
            else
                process_right_block(block_right.decompress());

            if (rows_added > max_joined_block_rows)
            {
                break;
            }
        }
```

**Does it reproduce on the most recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> Change "enabled" to true in "send_crash_reports" section in `config.xml`:
```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if it matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to an unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by lgbo-ustc** [comment]
@nickitat Could you look at this ?

**Comment by nickitat** [comment]
looks like you're right. and it should be reproducible. would you like to submit a fix?

**Comment by lgbo-ustc** [comment]
> looks like you're right. and it should be reproducible. would you like to submit a fix?

OK
