### ISSUE TITLE
Unexpected query result with MergeTree and order by

### ISSUE THREAD

**Issue by KobeBryant-24** [ClickHouse/ClickHouse#69133]
### Question

1. with multiple independent insert data whose primary key is identical, 'order by XX asc' or 'order by XX desc' returns the same result, which is unexpected.
2. while optimized with final (which means data merged in the background), 'order by' works as sorting by the insert order.
3. with single inserts with multiple data whose primary key is identical, same as 2, which is expected.

example:
https://fiddle.clickhouse.com/729bdf47-ba18-47e3-982d-d315f67608b5

as far as I know, MergeTree engine does not support selecting with final, how do we ensure the result is in its correct order?

**Comment by ucasfl** [comment]
> with multiple independent insert data whose primary key is identical, 'order by XX asc' or 'order by XX desc' returns the same result, which is unexpected.
Why it's unexpected?

**Comment by ucasfl** [comment]
> > Your `ORDER BY` key is identital, why it's unexpected?
> 
> let me ask in another way, what are the expected results with 'order by asc' and with 'order by desc' if the keys are identical? and why the result of 1 differs from 2&3 while the data is totally the same?

Uncertain, it just guarantee the order of order by key.
