### ISSUE TITLE
Backup concurrency

### ISSUE THREAD

**Issue by italodamato** [ClickHouse/ClickHouse#69163]
Does `BACKUP ALL` (or passing multiple values) back up the elements sequentially or in parallel? It's not specified in the documentation. https://clickhouse.com/docs/en/operations/backup

**Comment by davenger** [comment]
If you not doing backup into a single file (e.g. `BACKUP ... TO Disk('backups', 'a.zip')`) the processing is done in parallel.
Here are the settings that control this parallelism
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#backup_threads
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#backups_io_thread_pool_queue_size

**Comment by italodamato** [comment]
Thank you. To confirm, the process is parallelized within a single BACKUP command, e.g. by using `BACKUP ALL` or `BACKUP DATABASE`.

**Comment by davenger** [comment]
> the process is parallelized within a single BACKUP command, e.g. by using BACKUP ALL or BACKUP DATABASE, correct?

Yes
