### ISSUE TITLE
Clickhouse-server can't restart succesfully until manual kill of clickhouse-odbc-bridge process

### ISSUE THREAD

**Issue by fessmage** [ClickHouse/ClickHouse#6921]
**Describe the bug or unexpected behaviour**
Clickhouse-server can't restart succesfully until manual kill of clickhouse-odbc-bridge process.

**How to reproduce**
Run clickhouse-server with odbc dictionaries. Then try `systemctl restart clickhouse-server` - it will hang. Clickhouse-server process stopped, but clickhouse-odbc-bridge process stays running. Kill that process manually - and then restart of clickhouse-server continues succesfully.

**Which ClickHouse server version to use**
19.13.3.26

**Expected behavior**
Restart of clickhouse-server service must itself stop odbc-bridge, not requiring manually interaction.

**Comment by alesapin** [comment]
Any steps to reproduce? We have tests for it https://github.com/ClickHouse/ClickHouse/blob/fix_mutation_commands_escaping/tests/integration/test_odbc_interaction/test.py#L307-L342.

**Comment by alexey-milovidov** [comment]
No info provided.
