### ISSUE TITLE
    ClickHouse/docs/ru/sql-reference/data-types/date32.md invalid start point

### ISSUE THREAD

**Issue by OlegGalizin** [ClickHouse/ClickHouse#69265]
Эпоха начинаестя с 1970 года а не с 1900. То есть 4 байтное число это количестов дней с 1января 1970 года а не 1900.

**Comment by den-crane** [comment]
https://clickhouse.com/docs/ru/sql-reference/data-types/date32

0 === 1970
до 1970 как отрицательное число

```
SELECT
    toDate32('1970-01-01') AS epoch,
    CAST(epoch, 'Int32') AS e_int32,
    toDate32('1969-12-31') AS befor_epoch,
    CAST(befor_epoch, 'Int32') AS b_e_int32,
    toDate32('1900-01-01') AS y1900,
    CAST(y1900, 'Int32') AS y_int32

Query id: 29455361-304b-402e-b23e-b474a0e50fab

   ┌──────epoch─┬─e_int32─┬─befor_epoch─┬─b_e_int32─┬──────y1900─┬─y_int32─┐
1. │ 1970-01-01 │       0 │  1969-12-31 │        -1 │ 1900-01-01 │  -25567 │
   └────────────┴─────────┴─────────────┴───────────┴────────────┴─────────┘
```

https://fiddle.clickhouse.com/0357220d-edc9-42ff-b761-10d38ff5f123

**Comment by OlegGalizin** [comment]
Извиняюсь. Вероятно я невнятно написал. В документации написано

Значение хранится в четырех байтах и соответствует числу дней с 1900-01-01 по 2299-12-31.

Значение соотвествует числу дней с начала эпохи 1970-01-01

**Comment by den-crane** [comment]
поменял, https://github.com/ClickHouse/ClickHouse/pull/69825/files#diff-e347a1231ca6a99e419bfbdab5191e006e7fecad5bc40780c252243d435b63a9

Кстати кто угодно может исправлять документацию (я тоже такой кто угодно).

**Comment by OlegGalizin** [comment]
так нужно поддерживать параллельно русскую и английскую.
