### ISSUE TITLE
 ttl not working

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#69262]
version：ClickHouse client version 22.3.10.22 (official build).

opt_time same as day; the opt_time column is define as opt_time Date DEFAULT now(),
partition: PARTITION BY (day, pt)
ttl： TTL opt_time + toIntervalDay(180)

but get ttl info  about 30 days； and optimize table not working

![image](https://github.com/user-attachments/assets/a8742131-8348-4eab-8f08-2299d82606df)

**Comment by Sallery-X** [comment]
opt_time same as day

**Comment by Felixoid** [comment]
Hi. Unfortunately, 22.3 is not supported. The first thing you should try is launching the supported version, at least 24.3
