### ISSUE TITLE
async_insert seems not take effect

### ISSUE THREAD

**Issue by mofei920** [ClickHouse/ClickHouse#69281]
version: 24.8.2.3-lts
insert methods: clickhouse jdbc

async insert settings in system.query_log:
```
'async_insert':'1','wait_for_async_insert':'1','async_insert_max_data_size':'10485760','async_insert_busy_timeout_max_ms':'200'
```

stats from asynchronous_insert_log:
```sql
select 
  event_time_microseconds,
  flush_time_microseconds,
  dateDiff('ms', event_time_microseconds, flush_time_microseconds) as diff_ms,
  `database`,
  table, 
  bytes,
  status,
  exception,
  query
from system.`asynchronous_insert_log`
where `event_date`=today()
order by event_time_microseconds desc
limit 10;
```

<img width="1966" alt="image" src="https://github.com/user-attachments/assets/145ef903-efea-4156-ad75-a65f06e78b93">

async_insert_busy_timeout_max_ms is 200ms， but async insert elapsed 58ms~69ms, less than 200ms, it seems async_insert not take effect? or http async insert have any changes?

**Comment by antonio2368** [comment]
the timeout is adaptive by default (controlled by `async_insert_use_adaptive_busy_timeout` setting)
The timeout is adapted based on the insert pattern.
If inserts are done rarely, it will prefer responsivness and flush after `async_insert_busy_timeout_min_ms`.
If inserts become more frequent, the timeout should ramp up until it reaches `async_insert_busy_timeout_max_ms`.
To verify you can try setting `async_insert_use_adaptive_busy_timeout` to `false`

**Comment by mofei920** [comment]
yes, async_insert_use_adaptive_busy_timeout default is 0 in doc, but it is 1 actually.
