### ISSUE TITLE
query_log configuration does not take effect

### ISSUE THREAD

**Issue by zxl-wangwang** [ClickHouse/ClickHouse#69283]
### Question

I have made the following configuration in my config.xml file:
`
<query_log>
        <database>system</database>
        <table>query_log</table>
        <partition_by>toYYYYMM(event_date)</partition_by>
        <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
        <flush_interval_milliseconds>7500</flush_interval_milliseconds>
    </query_log>
`
However, after I restarted ck and checked the table structure of the system table query_log, its TTL setting did not seem to take effect.

![image](https://github.com/user-attachments/assets/a6feea92-b1db-4f37-9edf-4f42ff503109)

clickhouse version：21.8.14.5、21.3.19.1

**Comment by davenger** [comment]
Versions 21.8 and 21.3 are very old and are no longer supported.
I checked with a fresh build and I see that `query_log` definition gets updated when I add ttl in config:

```
...
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_date)
ORDER BY (event_date, event_time)
TTL event_date + toIntervalDay(30)
SETTINGS index_granularity = 8192
```

**Comment by Felixoid** [comment]
Older versions don't recreate the tables. So unless the table is renamed, the config won't affect the existing one. Here's the reproduce:

```
> cat query_ttl.xml
<yandex>
  <query_log>
    <database>system</database>
    <table>query_log</table>
    <partition_by>toYYYYMM(event_date)</partition_by>
    <ttl>event_date + INTERVAL 30 DAY DELETE</ttl>
    <flush_interval_milliseconds>7500</flush_interval_milliseconds>
  </query_log>
</yandex>

# First run, to create the table
> docker run -it --name=clickhouse-query-log --rm -v clickhouse-query-log:/var/lib/clickhouse clickhouse/clickhouse-server:21.8.14.5 &>/dev/null
^C
# Second run, with a config
> docker run --name=clickhouse-query-log -it --rm -v clickhouse-query-log:/var/lib/clickhouse -v $(pwd):/etc/clickhouse-server/config.d clickhouse/clickhouse-server:21.8.14.5 &>/dev/null
```

In another terminal:

```
> docker exec -it clickhouse-query-log clickhouse-client -q 'SHOW CREATE TABLE system.query_log' | grep TTL
# nothing
# So, let's rename it
> docker exec -it clickhouse-query-log clickhouse-client -q 'RENAME TABLE system.query_log TO system.query_log_old'
# After that, we need to restart the server, so I do in the first terminal
> docker exec -it clickhouse-query-log clickhouse-client -q 'SHOW CREATE TABLE system.query_log' | grep -o 'TTL event_date'
TTL event_date
```

You need to manually drop/rename existing table. Or edit the metadata.

And update the server, for sure =)

**Comment by zxl-wangwang** [comment]
Thanks for taking the time to answer, I'll test it this way.
