### ISSUE TITLE
[20.8.18.32] ck query_log or query_thread_log configuration does not take effect 

### ISSUE THREAD

**Issue by zxl-wangwang** [ClickHouse/ClickHouse#69313]
### Question

my question:

I used the solution from issue #69283，The query_log table and query_thread_log table were renamed, and then ClickHouse was restarted, but the TTL configured for the newly generated query_log table and query_thread_log table still did not take effect.

![image](https://github.com/user-attachments/assets/fea5d17f-f7ce-4e67-8b41-ed98670a9a84)

![image](https://github.com/user-attachments/assets/a3561970-bf02-4c90-ade1-4b3f9dfb515d)

ck version: 20.8.18.32

Issue #69283 provides solutions for versions 21.8 and 21.3. Is there any effective solution for 20.8.18.32?

**Comment by Felixoid** [comment]
> Versions 21.8 and 21.3 are very old and are no longer supported.

Version older than 24.3 is not supported.

**Comment by zxl-wangwang** [comment]
The problem can be solved in versions 21.3 and 21.8 by changing the table name and restarting the CK service. Can't the problem be solved in this way in version 20.8 (it failed my test)?Do you have any good suggestions?

**Comment by Felixoid** [comment]
It's 4 years old, and `clickhouse/clickhouse-server:20.8` doesn't even exist on the docker hub to test.

I don't know what to suggest besides updating.

**Comment by zxl-wangwang** [comment]
OK, thank you.

**Comment by Felixoid** [comment]
you can checkout the https://github.com/ClickHouse/ClickHouse/tree/v20.8.18.32-lts/docs and trying find there if ttl even supported. Maybe not

**Comment by den-crane** [comment]
you can only use alter table modify TTL in 20.8


v21.1.1.5646-prestable.md:* Allow specifying [TTL](https://clickhouse.tech/docs/en/engines/table-engines/mergetree-family/mergetree/#mergetree-table-ttl) to remove old entries from [system log tables](https://clickhouse.tech/docs/en/operations/system-tables/), using the `<ttl>` attribute in `config.xml`. [#17438](https://github.com/ClickHouse/ClickHouse/pull/17438) ([Du Chuan](https://github.com/spongedu)).
