### ISSUE TITLE
Functionality question

### ISSUE THREAD

**Issue by picinato** [ClickHouse/ClickHouse#6932]
I have a question is here which post?

How can I create a subquery in clickhouse?
I need to check if there was another registration 45 days ago for a given customer.

select q.name,
	(
	select count(1)
	from tb t2
	where t2.name=t1.name
	) as total
from tb t1

**Comment by picinato** [comment]
Clickhouse has everything to be one of the most used databases in the future. But today it is not yet possible to be used, only for data already processed and only use simple select and simple queries.

It really is an incredibly fast bank, but it lacks features much used in other banks, such as subselect. With subselect we can use almost everything without relying on its own functions (UDF). Without both functions its use is complicated.

I will try to work Clickhouse together as MonetDB and post here if the result was good.

**Comment by vpanfilov** [comment]
> Clickhouse have search before Record? This help me for this problema, return date my before line. And calculada date difference

You can try to use ASOF JOIN to calculate time differences.

**Comment by picinato** [comment]
You can explain me this? One example ASOF JOIN?

**Comment by blinkov** [comment]
@picinato, do you have any further questions?

**Comment by picinato** [comment]
I couldn't use this sorry. In my applications I use a lot of subquery to get information based on some parameters. As there is no use of user-defined functions, I left the clickhouse a little aside. I am studying some other solutions at the moment. I was really excited about the clickhouse but I still lack essential things

**Comment by blinkov** [comment]
@picinato sad to hear that. Correlated subqueries are indeed just another syntax to implicitly do JOINs, that's why they never were a high priority.

**Comment by picinato** [comment]
@blinkov How would you do this? I didn't understand how to use asof join for solution

I need to pass several parameters, how would this be?

select q.*,
(
select count(1)-1
from tb qi
where qi.dt_open>=addDays(cast(q.dt_open as date),-45) and qi.dt_open<=q.dt_open
and qi.city=q.city and qi.cd_number=q.cd_number
and qi.vision=q.vision
) amount
from tb q

**Comment by blinkov** [comment]
@picinato it probably won't be immediately working because I don't have tables to debug it against, but your query looks to be similar to this one for ClickHouse:
``` sql
select q.*, qi.amount amount
from tb q left join (
  select count() - 1 amount, dt_open, city, cd_number, vision
  from (
    select dt_open + arrayJoin(range(0,45) dt_open, city, cd_number, vision
    from tb
  )
  group by dt_open, city, cd_number, vision
) qi
on qi.city=q.city and qi.cd_number=q.cd_number
and qi.vision=q.vision and qi.dt_open = qt.dt_open
```

In modern SQL standard revisions this could be expressed more naturally via window functions. They are also missing in ClickHouse at the moment, but unlike correlated subqueries they provide additional useful functionality and thus have a relatively high priority on a long-term roadmap.

**Comment by alexey-milovidov** [comment]
Window functions have been implemented and are available in the recent ClickHouse versions.
