### ISSUE TITLE
Using optional fields in protobuf nested messages

### ISSUE THREAD

**Issue by LizardWizzard** [ClickHouse/ClickHouse#6936]
Hello! First of all thank you for the great product :)

I'm using kafka engine with protobuf format and my message contains nested messages with optional values.
In kafka table and in target table for materialized view I use Nested column type.

In case when proto message doesnt have a value for field in nested message arrays in nested columns become of different length. Because null values are not inserted into them.
So when I use INSERT SELECT or MATERIALIZED VIEW I receive this error: ```Elements nestedcol.a and nestedcol.b of Nested data structure nestedcol (Array columns) have different array sizes.```

Is there any possible workaround for that? I've tried to use default values in nested columns but this didnt do the trick for me. 

I use version `19.9.5.36`

May be it is related to #6497

**Comment by blinkov** [comment]
@LizardWizzard, is this question still relevant?

**Comment by LizardWizzard** [comment]
I think actually this is a bug, since there are no way to workaround errors I've described. Except to change processing logic on the producer side. May be it is better to put a "bug" label. 

I think this bug is related to [this](https://clickhouse.tech/docs/ru/whats-new/extended-roadmap/#razobratsia-s-deserializatsiei-massivov-so-znacheniiami-po-umolchaniiu-v-protobuf-formate-v-sluchae-protobuf-3) roadmap issue (sorry for link to Russian version, English one returns 404). But in my case there is a combination of both protobuf versions

**Comment by alexey-milovidov** [comment]
I don't understand how it can be fixed if Protobuf simply omits default values.
But @vitlibar said that he will continue to work on this issue.

**Comment by LizardWizzard** [comment]
If I understand Protobuf logic correctly default value can be fetched from entity schema, and because of that protocol doesnt have to supply known default value in transmitted data.

**Comment by alexey-milovidov** [comment]
If we have two arrays
[1, default, 2]
and
[default, 1, default]

How they are encoded?
Is default values omitted completely?
[1, 2]
[1]

In that case, how we can get positions of default values?

**Comment by LizardWizzard** [comment]
Sorry, my statement was not complete. Protobuf can omit default
values where it is possible to unambiguously infer them from schema 
without introducing situations like one you pointed to.

May be this explanation turned out to be too verbose and contains extra info but for the sake of completeness let it all be here (May be it'll help future readers)

So, consider an example message:
```protobuf
syntax = "proto2";
message MessageWithRepeatedString {
  optional string optional_string = 1;
  repeated string some_string_array = 2;
}
```
I'll describe an example with protobuf python library
```python
msg = MessageWithRepeatedString()
print(msg.optional_string == '')
# True
print(msg.some_string_array)
# []
print(msg.SerializeToString() == b'')
# True
```
In this case message default fields values can be reconstructed from schema.
```python
msg.some_string_array.append('')
print(msg.SerializeToString())
# b'\x12\x00' 
```
1 is a field sequence number from schema, 2 is "Length-delimited" wire type from [here](
https://developers.google.com/protocol-buffers/docs/encoding#structure) and zero is a varint encoded string length
```python
msg.some_string_array.append('some')
print(msg.SerializeToString())
# b'\x12\x00\x12\x04some'
```
same as above
```python
msg.some_string_array.append('')
print(msg.SerializeToString())
# b'\x12\x00\x12\x04some\x12\x00'
```
So in case with array of primitive type protobuf cannot omit default value.
But for array of messages it can omit all fields of inner messages if they have default values,
so only zero length placeholders are left in wire form representation.

```protobuf
syntax = "proto2";
message MessageInner {
  optional string string_1 = 1;
  optional string string_2 = 2;
}
message MessageOuterWithRepeated {
  repeated MessageInner inner = 1;
}
```
```python
msg = MessageOuterWithRepeated(
    inner=[
        MessageInner(),
        MessageInner(),
    ]
)
print(msg.SerializeToString())
# b'\n\x00\n\x00'
```


This also works for non repeated nested messages. 
But in that case placeholder is not needed and field is not presented in wire form.
```protobuf
syntax = "proto2";
message MessageInner {
  optional string string_1 = 1;
  optional string string_2 = 2;
}

message MessageOuter {
  optional MessageInner inner = 1;
}
```
```python
outer_message = MessageOuter()
outer_message.optional_string = 'some'
print(outer_message.SerializeToString())
# b'\n\x04some'
```
But when accessing the field on deserialized message entity will result in default value for this type.
```python
print(outer_message.inner.string_1 == '') 
# True
```

There is a difference in behaviour with proto3.
In proto2 if default value is explicitly set then it is added to the wire form: 
```python
outer_message.inner.string_1 = ''
print('Proto2', outer_message.SerializeToString())
# Proto2 b'\n\x04some\x12\x02\n\x00'
```
Using equivalent message structure in proto3
```python
outer_message = MessageOuterProto3()
outer_message.optional_string = 'some'
outer_message.inner.string_1 = ''
print('Proto3', outer_message.SerializeToString())
# Proto3 b'\n\x04some\x12\x00'
```
So for proto3 there is no extra field identifier.
This behaviour is specified [here](https://developers.google.com/protocol-buffers/docs/proto3#default)
in particular 
> Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all"

and
> Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.

Actually explicitly setting default value is the way I've workarounded the issue.
In my case needed entity was defined with proto2, 
and after manually setting nested fields default value ClickHouse started filling needed field in table.
Error that I'm referencing in issue comes when protobuf repeated nested messages have optional fields
and in the input data stream sometimes come messages when several fields are not filled and when field is not presented in the wire representation
ClickHouse is not inserting default value for missing field and arrays holding Nested ClickHouse type fields diverge.

Unfortunately I have no knowledge of C++, but I can help with adding integrational tests for this feature.
