### ISSUE TITLE
RFC: Min-max indexes and bloom filter indexes by default?

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#69363]
Bloom filters and min-max indexes are of negligible size, cheap to maintain, and they help a lot with filtering. Should we create them for new columns by default?

**Comment by nikitamikhaylov** [comment]
Yes, we should calculate them for all columns (not only for key ones).

**Comment by den-crane** [comment]
Try with Clickhouse benchmark, I bet bloom indexes make insertion 100 times slower and queries 10 times slower.

**Comment by rschu1ze** [comment]
Dupes https://github.com/ClickHouse/ClickHouse/issues/70605
