### ISSUE TITLE
Use supported version of Node.js in Dockerfile

### ISSUE THREAD

**Issue by trivikr** [ClickHouse/ClickHouse#69365]
### Is your proposal related to a problem?

The Dockerfile in ClickHouse uses Node.js 16.x which was end-of-life on 2023-09-11
https://github.com/ClickHouse/ClickHouse/blob/47c91ffa70d0ca9dd58d8df30c59ba384f1d9f6b/docker/docs/builder/Dockerfile#L3

### Describe the solution you'd like

Use supported version of Node.js in Superset WebSocket Server Dockerfile.
The latest LTS version at the time of comment is Node.js 20.x

**Comment by alexey-milovidov** [comment]
Maybe migrate to PHP 5 instead?

**Comment by trivikr** [comment]
Close as "not planned"?

**Comment by Algunenano** [comment]
This was done at some point. Currently using `FROM node:20-bookworm-slim`
