### ISSUE TITLE
i can't run clickhouse 

### ISSUE THREAD

**Issue by aol-59** [ClickHouse/ClickHouse#69375]
I attempted to restart ClickHouse using systemctl restart clickhouse-server, but it took a long time to start. When I tried to start ClickHouse again, the same issue occurred. I restarted all other nodes in the cluster, and they are working fine. There are no errors in the logs, except for the following warning: db.tbl1: `part 12233232 doesn't have metadata version on disk, setting it to 0. This is acceptable if the part was created by an older version of ClickHouse.`
Version: 23.8.1.2992.

**Comment by den-crane** [comment]
>part 12233232 doesn't have metadata version on disk, setting it to 0. This is acceptable if the part was created by an older version of ClickHouse.

It's expected after upgrading, safe to ignore. It will disappear once old parts get merged or removed

>i can't run clickhouse 

Please share full log. 

Show the output of 

```
sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
```

**Comment by aol-59** [comment]
> ```
> sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
> ```

` sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/cluster.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/kafka.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/macros.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/metric_log.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/prometheus.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/server_config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/user_files_path.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/zookeeper.xml'.
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
2024.09.08 17:42:42.901485 [ 296968 ] {} <Information> SentryWriter: Sending crash reports is disabled
2024.09.08 17:42:42.901542 [ 296968 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2024.09.08 17:42:43.020949 [ 296968 ] {} <Information> Application: Starting ClickHouse 23.8.1.2992 (revision: 54477, git hash: ebc7d9a9f3b40be89e0b3e738b35d394aabeea3e, build id: FAFE345D268E9085074AB714A77D4F02DE6BC615), PID 296968
2024.09.08 17:42:43.021070 [ 296968 ] {} <Information> Application: starting up
2024.09.08 17:42:43.021086 [ 296968 ] {} <Information> Application: OS name: Linux, version: 3.10.0-1160.el7.x86_64, architecture: x86_64
2024.09.08 17:42:43.027763 [ 296968 ] {} <Information> Application: Available RAM: 376.34 GiB; physical cores: 48; logical cores: 96.
2024.09.08 17:42:43.029029 [ 296968 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/thermal
2024.09.08 17:42:43.029069 [ 296968 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2024.09.08 17:42:43.029300 [ 296968 ] {} <Trace> AsynchronousMetrics: Scanning /sys/devices/system/edac
2024.09.08 17:42:43.029449 [ 296968 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2024.09.08 17:42:43.227793 [ 296968 ] {} <Information> Application: Integrity check of the executable successfully passed (checksum: 8914E950702309FB3ACA91C7B869A2F6)
2024.09.08 17:42:43.227860 [ 296968 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2024.09.08 17:42:43.227948 [ 296968 ] {} <Information> StatusFile: Status file /data/clickhouse/status already exists - unclean restart. Contents:
PID: 295828
Started at: 2024-09-08 17:38:37
Revision: 54477

2024.09.08 17:42:43.228608 [ 296968 ] {} <Trace> Context: Shutting down named sessions
2024.09.08 17:42:43.228636 [ 296968 ] {} <Trace> Context: Shutting down database catalog
2024.09.08 17:42:43.228654 [ 296968 ] {} <Trace> DatabaseCatalog: Shutting down system databases
2024.09.08 17:42:43.228663 [ 296968 ] {} <Trace> Context: Shutting down DDLWorker
2024.09.08 17:42:43.228670 [ 296968 ] {} <Trace> Context: Shutting down caches
2024.09.08 17:42:43.228872 [ 296968 ] {} <Error> Application: Code: 76. DB::Exception: Cannot lock file /data/clickhouse/status. Another server instance in same directory is already running. (CANNOT_OPEN_FILE), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c604e57 in /usr/bin/clickhouse
1. DB::Exception::Exception<String const&>(int, FormatStringHelperImpl<std::type_identity<String const&>::type>, String const&) @ 0x000000000748f46d in /usr/bin/clickhouse
2. DB::StatusFile::StatusFile(String, std::function<void (DB::WriteBuffer&)>) @ 0x000000000c72d55f in /usr/bin/clickhouse
3. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000c69395f in /usr/bin/clickhouse
4. Poco::Util::Application::run() @ 0x0000000015b1e5a6 in /usr/bin/clickhouse
5. DB::Server::run() @ 0x000000000c68bf1e in /usr/bin/clickhouse
6. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000015b2d6b9 in /usr/bin/clickhouse
7. mainEntryClickHouseServer(int, char**) @ 0x000000000c688cea in /usr/bin/clickhouse
8. main @ 0x00000000071121cf in /usr/bin/clickhouse
9. __libc_start_main @ 0x0000000000022555 in /usr/lib64/libc-2.17.so
10. _start @ 0x000000000634772e in /usr/bin/clickhouse
 (version 23.8.1.2992 (official build))
2024.09.08 17:42:43.228976 [ 296968 ] {} <Error> Application: DB::Exception: Cannot lock file /data/clickhouse/status. Another server instance in same directory is already running.
2024.09.08 17:42:43.228992 [ 296968 ] {} <Information> Application: shutting down
2024.09.08 17:42:43.229000 [ 296968 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2024.09.08 17:42:43.229063 [ 296969 ] {} <Trace> BaseDaemon: Received signal -2
2024.09.08 17:42:43.229134 [ 296969 ] {} <Information> BaseDaemon: Stop SignalListener thread
`
Thank you, Denny, for your usual help.
I ran this command: `ps -ef | grep clickhouse`
Then, I killed the process.
After that, I ran the following command:
`sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
`
The result is the same as in the clickhouse-server.log with <Trace> and <Debug> logs, but no errors, and it’s still not working.
Do you need any additional information?
I

**Comment by den-crane** [comment]
>After that, I ran the following command:
sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml 
The result is the same as in the clickhouse-server.log with and tags, but no errors, and it’s still not working.
Do you need any additional information?

What was printed by `sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml ` ? Can you share the last lines?

**Comment by aol-59** [comment]
> > After that, I ran the following command:
> > sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
> > The result is the same as in the clickhouse-server.log with and tags, but no errors, and it’s still not working.
> > Do you need any additional information?
> 
> What was printed by `sudo -u clickhouse /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml ` ? Can you share the last lines?


![image](https://github.com/user-attachments/assets/7ea72960-160f-4d09-a6e3-fa3c2cf395d6)

`2024.09.08 19:16:57.892059 [ 312966 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part cac077e07158858825a2f52a4403017b4_426_426_0 on disk default
2024.09.08 19:16:57.893430 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part 269395446598622b69f6771c70bec171e32f_1270_1270_0 on disk default
2024.09.08 19:16:57.893654 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part b0101fb4c1d8a6659b8715e6723b7c9a_2123_2123_0 on disk default
2024.09.08 19:16:57.893832 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part c28944529f40d982b93b0dc433f63360_2914_2914_0 on disk default
2024.09.08 19:16:57.894000 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part 773db1fb82d5c4395d2c3e0655f8473a_3361_3361_0 on disk default
2024.09.08 19:16:57.894177 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part b24a7e1e82ed48319d0b924336633c98_1209_1209_0 on disk default
2024.09.08 19:16:57.894349 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part c6b59343a90993a4b0ce5646408d6d09_1724_1724_0 on disk default
2024.09.08 19:16:57.894517 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part p77d74dce5494b5f93d2c3f5f9d8473a_3367_3367_0 on disk default
2024.09.08 19:16:57.894697 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part 77dd74ce5494b59d2c3d5f9d8473a_3367_3367_0 on disk default
2024.09.08 19:16:57.894870 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part 11236af34f5d4531bb4d906c4569f676_3467_3467_0 on disk default
2024.09.08 19:16:57.895048 [ 312967 ] {} <Trace> .inner_id.04406422-c064-4a14-94bb-44055d6a6ad9 (f2968e36-570c-44dc-8d4f-9f41eed256ac): Finished loading Active part p77d74dce5494b5f93d2c3f5f9d8473a_3361_3361_0 on disk default
2024.09.08 19:16:57.895230 [ 312967 ] {} <Trace> db.tbl1 (750ea158-d18b-4715-bb4c-01732e8061e6): Loaded data parts (4036 items)
2024.09.08 19:16:57.895435 [ 312967 ] {} <Information> db.tbl1 (750ea158-d18b-4715-bb4c-01732e8061e6): Table will be in readonly mode until initialization is finished
2024.09.08 19:16:57.963160 [ 312994 ] {} <Debug> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 8
2024.09.08 19:16:57.963316 [ 312994 ] {} <Debug> SystemLog (system.metric_log): Will use existing table system.metric_log for MetricLog
2024.09.08 19:16:57.963337 [ 312944 ] {} <Trace> system.metric_log (27b7d093-44c5-4953-9956-eb0cc3650368): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2024.09.08 19:16:57.963357 [ 312944 ] {} <Trace> MergedBlockOutputStream: will sync files on local disk 'default', having unreserved 30.39 TiB
2024.09.08 19:16:58.045937 [ 312944 ] {} <Trace> MergedBlockOutputStream: calculated checksum 202409_1_0_0 (state Temporary)
2024.09.08 19:16:58.046612 [ 312944 ] {} <Trace> system.metric_log (27b7d093-44c5-4953-9956-eb0cc3650368): Renaming temporary part tmp_insert_202409_1_0 to 202409_4128712_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000)
2024.09.08 19:17:08.866536 [ 312944 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 16
2024.09.08 19:17:08.866679 [ 312944 ] {} <Trace> DNSResolver: Updating DNS cache
2024.09.08 19:17:08.866696 [ 312944 ] {} <Trace> DNSResolver: Updated DNS cache
2024.09.08 19:17:08.866724 [ 312944 ] {} <Debug> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 16
2024.09.08 19:17:08.866770 [ 312944 ] {} <Trace> Diaklocal: Reserved 1.00 MiB using storage policy from min volume index 0
2024.09.08 19:17:08.866788 [ 312944 ] {} <Trace> MergedBlockOutputStream: will sync files on local disk 'default', having unreserved 30.39 TiB
2024.09.08 19:17:08.893000 [ 312944 ] {} <Trace> MergedBlockOutputStream: calculated checksum 202409_1_2_0 (state Temporary)
2024.09.08 19:17:08.893067 [ 312944 ] {} <Trace> system.metric_log (27b7d093-44c5-4953-9956-eb0cc3650368): Renaming temporary part tmp_insert_202409_2_2_0 to 202409_4128713_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000)
2024.09.08 19:17:08.403091 [ 312944 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 16
2024.09.08 19:17:08.861297 [ 312676 ] {} <Trace> BaseDaemon: Received signal 2
2024.09.08 19:17:08.861437 [ 312676 ] {} <Information> Application: Received termination signal (Interrupt)
`

The logs continue to generate and only stop when I press` Ctrl + C.`

**Comment by den-crane** [comment]
it looks fine.

Can you share ` sudo journalctl -u clickhouse-server`

**Comment by aol-59** [comment]
I ran systemctl start clickhouse-server at 19:24 PM, and after 4 hours, ClickHouse started running, but I’m not sure how or why.

`Can you share  sudo journalctl -u clickhouse-server`
the output is : 

`Sep 08 19:24:34 node-4 clickhouse-server[314057]: Merging configuration file '/etc/clickhouse-server/config.d/metric_log.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Merging configuration file '/etc/clickhouse-server/config.d/prometheus.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Merging configuration file '/etc/clickhouse-server/config.d/server_config.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Merging configuration file '/etc/clickhouse-server/config.d/user_files_path.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Merging configuration file '/etc/clickhouse-server/config.d/zookeeper.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Saved preprocessed configuration to '/data/clickhouse/preprocessed_configs/config.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Processing configuration file '/etc/clickhouse-server/users.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Merging configuration file '/etc/clickhouse-server/users.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Merging configuration file '/etc/clickhouse-server/users.d/default-password.xml'.

Sep 08 19:24:34 node-4 clickhouse-server[314057]: Saved preprocessed configuration to '/data/clickhouse/preprocessed_configs/users.xml'.

Sep 08 23:48:22 node-4 systemd[1]: 1 ClickHouse Server (analytic DBMS for big data).`

check the time 
![output](https://github.com/user-attachments/assets/51ff4128-c0e9-4f42-88a4-555a36feef77)

**Comment by den-crane** [comment]
check `select count() from system.tables`  `select count() from system.parts` 
if you have a big number of tables / parts Clickhouse may start for a long time.

**Comment by aol-59** [comment]
> check `select count() from system.tables` `select count() from system.parts` if you have a big number of tables / parts Clickhouse may start for a long time.

you are right 
I have 3 tables, and each table contains 20,000 parts.


`CREATE TABLE test.tbl1
(
    FILE_DATE Date,
    FILENAME String,
    AVG_INGEST_DELAY AggregateFunction(avg, UInt64),
    AVG_PROCESS_DELAY AggregateFunction(avg, UInt64),
    AVG_TOTAL_DELAY AggregateFunction(avg, UInt64),
    INSERTION_DATE DateTime DEFAULT now()
)
ENGINE = AggregatingMergeTree
PARTITION BY FILE_DATE
ORDER BY (FILENAME, FILE_DATE)
TTL INSERTION_DATE + toIntervalDay(7)
SETTINGS index_granularity = 8192;

CREATE TABLE test.tbl2
(
    FILE_DATE Date,
    FILENAME String,
    TIME DateTime,
    FILE_INSERTION_TIME DateTime,
    PROCESS_TRANSACTION_TIME DateTime,
    PROCESS_PROCESS_TIME DateTime,
    PROCESS_DELAY UInt64,
    TOTAL_DELAY UInt64,
    INSERTION_DATE DateTime DEFAULT now()
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(FILE_DATE)
PRIMARY KEY (FILENAME, FILE_DATE)
ORDER BY FILENAME
TTL INSERTION_DATE + toIntervalDay(7)
SETTINGS index_granularity = 8192;

CREATE TABLE test.tbl3
(
    FILE_DATE Date,
    FILENAME String,
    TIME DateTime,
    FILE_INSERTION_TIME DateTime,
    PROCESS_TRANSACTION_TIME DateTime,
    PROCESS_PROCESS_TIME DateTime,
    PROCESS_DELAY UInt64,
    TOTAL_DELAY UInt64,
    INSERTION_DATE DateTime DEFAULT now()
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(FILE_DATE)
PRIMARY KEY FILENAME
ORDER BY FILENAME
TTL INSERTION_DATE + toIntervalDay(7)
SETTINGS index_granularity = 8192;
`

**Comment by den-crane** [comment]
check / share

```
select database, table, active, count(), uniq(partition_id), max(max_date), min(min_date) 
from system.parts group by  database, table, active;
```

>TTL INSERTION_DATE + toIntervalDay(7)

It's Better to use `toStartOfDay(INSERTION_DATE) + toIntervalDay(7)` to decrease number of TTL jobs.

**Comment by aol-59** [comment]
> check / share
> 
> ```
> select database, table, active, count(), uniq(partition_id), max(max_date), min(min_date) 
> from system.parts group by  database, table, active;
> ```
> 
> > TTL INSERTION_DATE + toIntervalDay(7)
> 
> It's Better to use `toStartOfDay(INSERTION_DATE) + toIntervalDay(7)` to decrease number of TTL jobs.


![image](https://github.com/user-attachments/assets/cd35d42a-263d-4e11-832b-7e139eba259a)

**Comment by den-crane** [comment]
23000 inactive parts, your inserts are very frequent. It's ~50 inserts per second into this table only. But you have more than one table.

4011 active partitions, it's too many.

So everything is expected here. 

1. Inserts are too small and too frequent.
2. Wrong partitioning
3. 23.8.1 is out of support

**Comment by aol-59** [comment]
> 23000 inactive parts, your inserts are very frequent. It's ~50 inserts per second into this table only. But you have more than one table.
> 
> 
> 
> tbl4 - 4011  partitions, it's too many.
> 
> 
> 
> So everything is expected here. 
> 
> 
> 
> 1. Inserts are too small and too frequent.
> 
> 2. Wrong partitioning
> 
> 3. 23.8.1 is out of support
Thanks 
Do you recommend any table engine for small and frequent inserts. 
Or should I use different database like singleStore or Postgres?

**Comment by den-crane** [comment]
https://clickhouse.com/docs/en/engines/table-engines/special/buffer

https://clickhouse.com/docs/en/optimize/asynchronous-inserts

**Comment by aol-59** [comment]
Thank you so much @den-crane
