### ISSUE TITLE
Upper case `INFORMATION_SCHEMA` database looks redudant

### ISSUE THREAD

**Issue by lampjian** [ClickHouse/ClickHouse#69372]
**Describe the issue**
Deleting the clickhouse/metadata/INFORMATION_SCHEMA.sql file can not remove the upper case `INFORMATION_SCHEMA` database. It is recreated after restart the server.
**How to reproduce**
* Which ClickHouse server version to use
LTS Version: 24.8.4.13

**Expected behavior**
The upper case `INFORMATION_SCHEMA` database disappears as expected. An alternative lower case database already exists.

**Additional context**
All databases and tables are lower case by default is more pretty to me.

**Comment by Algunenano** [comment]
That database is there for compatibility with the ANSI standard, mostly to allow tools connecting via the MySQL or  PosgreSQL protocol to work correctly. You can ignore them.
