### ISSUE TITLE
Can not start Clickhouse server

### ISSUE THREAD

**Issue by onex-koustav** [ClickHouse/ClickHouse#69409]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
I have downloaded the Clickhouse binary using the command curl https://clickhouse.com/ | sh.
When i try to start the server using the command ./clickhouse server, I get the following error. The server version is 24.9.1.2255

**Error message and/or stacktrace**
2024.09.10 12:15:52.054886 [ 27695 ] {} <Error> Application: Caught exception while loading metadata: std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Not a directory ["./store/"], Stack trace (when copying this message, always include the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x0000000018289055
1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:v15007](String const&, std::__fs::filesystem::path const&, std::error_code) @ 0x000000000dc2b141
2. void std::__fs::filesystem::__throw_filesystem_error[abi:v15007]<String&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x000000001823fcda
3. std::__fs::filesystem::detail::(anonymous namespace)::ErrorHandler<bool>::report(std::error_code const&) const (.llvm.6656863861799227920) @ 0x0000000018243100
4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x00000000182439ff
5. DB::DatabaseOnDisk::DatabaseOnDisk(String const&, String const&, String const&, String const&, std::shared_ptr<DB::Context const>) @ 0x0000000011342055
6. DB::DatabaseOrdinary::DatabaseOrdinary(String const&, String const&, String const&, String const&, std::shared_ptr<DB::Context const>) @ 0x000000001136491b
7. DB::DatabaseAtomic::DatabaseAtomic(String, String, StrongTypedef<wide::integer<128ul, unsigned int>, DB::UUIDTag>, String const&, std::shared_ptr<DB::Context const>) @ 0x000000001135371f
8. std::shared_ptr<DB::IDatabase> std::__function::__policy_invoker<std::shared_ptr<DB::IDatabase> (DB::DatabaseFactory::Arguments const&)>::__call_impl<std::__function::__default_alloc_func<DB::registerDatabaseAtomic(DB::DatabaseFactory&)::$_0, std::shared_ptr<DB::IDatabase> (DB::DatabaseFactory::Arguments const&)>>(std::__function::__policy_storage const*, 3DB::DatabaseFactory::Arguments const&) (.llvm.8575206920354987470) @ 0x0000000011362fed
9. DB::DatabaseFactory::get(DB::ASTCreateQuery const&, String const&, std::shared_ptr<DB::Context const>) @ 0x000000001132ffdb
10. DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) @ 0x0000000011ae5378
11. DB::InterpreterCreateQuery::execute() @ 0x0000000011b08eb1
12. DB::executeCreateQuery(String const&, std::shared_ptr<DB::Context>, String const&, String const&, bool, bool) @ 0x0000000011f715fb
13. DB::loadSystemDatabaseImpl(std::shared_ptr<DB::Context>, String const&, String const&) @ 0x0000000011f709c1
14. DB::loadMetadataSystem(std::shared_ptr<DB::Context>) @ 0x0000000011f6f68b
15. DB::Server::main(std::vector<String, std::allocator<String>> const&) @ 0x000000000dd9a44a
16. Poco::Util::Application::run() @ 0x0000000015f4e266
17. DB::Server::run() @ 0x000000000dd87d30
18. Poco::Util::ServerApplication::run(int, char**) @ 0x0000000015f570a7
19. mainEntryClickHouseServer(int, char**) @ 0x000000000dd84f78
20. main @ 0x0000000007e8684e
21. ? @ 0x000071e29bc29d90
22. ? @ 0x000071e29bc29e40
23. _start @ 0x00000000062c002e

**Comment by Algunenano** [comment]
CH needs to create directories to work. By default, if no config is passed to `clickhouse server` it creates them in the directory you are running the binary, but most likely you already have files there and they conflict. Try running it somewhere else.

**Comment by onex-koustav** [comment]
Thank you, that works.
