### ISSUE TITLE
Set subqueries not possible inside window function clauses

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#69428]
**Company or project name**

Clickhouse employee :smile: 

**Describe what's wrong**

Set subqueries don't work inside `PARTITION BY` and `ORDER BY` clauses inside window functions.

https://fiddle.clickhouse.com/13d5932f-a66e-4ec3-8323-923f8f0fc9de

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

Run the query on the Fiddle above.

**Expected behavior**

The query should be successful.

**Error message and/or stacktrace**

```
Received exception from server (version 24.8.4):
Code: 36. DB::Exception: Received from localhost:9000.
DB::Exception: UNION mode UNION_DEFAULT must be normalized. (BAD_ARGUMENTS)
(query: SELECT rank() OVER (ORDER BY ((SELECT 1) EXCEPT (SELECT 1)));)
```

**Comment by den-crane** [comment]
it's not a bug. It was never implemented (and never intended).
