### ISSUE TITLE
Increased memory consumption after upgrading from 24.5 to 24.8

### ISSUE THREAD

**Issue by Shlomixg** [ClickHouse/ClickHouse#69435]
**Describe the situation**
Recently, we encountered a significant increase in memory consumption during query inserts involving joins.
After upgrading to version 24.8, the same queries now utilize 10x more memory or even more, occasionally resulting in failures.
This situation has forced us to apply special settings (join_algorithm='partial_merge'), which unfortunately causes the queries to run much slower.

The issue seems to be particularly pronounced when joining tables with columns containing long JSON Strings (usually 200+ characters). Interestingly, the source tables themselves are small in terms of storage size — kilobytes!

The read and result stats are exactly the same before/after the upgrade:
* read_bytes: 3057073
* read_rows: 17005
* result_bytes: 658
* result_rows: 4

Here is the memory usage comparison:

Memory usage before upgrade: 361,705,119
Memory usage after upgrading: 39,020,451,116 (with the setting join_algorithm='partial_merge'; without this setting, the query fails due to a memory exception)

other default settings:
* allow_experimental_analyzer: 0
* max_bytes_before_external_group_by: 8000000000
* max_bytes_before_external_sort: 8000000000
* max_memory_usage: 55000000000

Example to relevant query:
```sql
select
    rt1."id" as "id",
    rt1."data_source_id" as "data_source_id",
    rt1."table_name" as "table_name",
    rt1."source" as "source",
    rt1."created_timestamp" as "created_timestamp",
    -- Column consists long JSON Strings
    lt2.raw_data as raw_data
from rt1	-- ~ 1 MB
join lt2	-- ~ 500 KB
    on rt1.id = lt2.id
```

* ClickHouse version: 24.8.3.59
* Prevouis ClickHouse version:  24.5.3.5

**Expected performance**
Use the same amount of memory

**Comment by Algunenano** [comment]
Looks very similar to https://github.com/ClickHouse/ClickHouse/issues/69415
