### ISSUE TITLE
ANOM_ABEND from BgSchPool

### ISSUE THREAD

**Issue by cangyin** [ClickHouse/ClickHouse#69431]
These are all we observed:

From container status:
```
Exit code 139.
```
From journalctl:
```
audit[1291629]: ANOM_ABEND auid=4294967295 uid=101 gid=101 ses=4294967295 pid=1291629 comm="BgSchPool" exe="/usr/bin/clickhouse" sig=11 res=1
```

No fatal logs or coredump file.

Version: 23.2.4.12-stable
Arch: aarch64

**Comment by Algunenano** [comment]
23.2.4.12-stable is unsupported. Please update to a supported release and share fatal logs / stacktrace
