### ISSUE TITLE
How to export prometheus-format metrics?

### ISSUE THREAD

**Issue by chenlujjj** [ClickHouse/ClickHouse#69482]
### Question

1. The link: https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server_configuration_parameters-prometheus from the [monitoring](https://clickhouse.com/docs/en/operations/monitoring) has no content related to prometheus at all.

2. The [Prometheus Integration](https://clickhouse.com/docs/en/integrations/prometheus) doc only describes the way to monitor ClickHouse Cloud, not the self-host ClickHouse.

3. I used the clickhouse-operator to deploy ClickHouse in k8s and I found there is a piece of config related to prometheus in the `/etc/clickhosue-server/config.xml` file:
<img width="713" alt="WeChatWorkScreenshot_05d332b3-8fd0-4d6c-933d-10f0958f025f" src="https://github.com/user-attachments/assets/46aa7951-8187-4165-b1a9-65093cd99f8a">

But it seems not work, there is no service at `9363` port.

**Comment by cangyin** [comment]
```xml
    <prometheus>
        <endpoint>/metrics</endpoint>
        <port>9363</port>

        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
        <status_info>true</status_info>
    </prometheus>
    -->
```
The XML section of prometheus config is commented out by default. Please uncomment to make it work.

**Comment by chenlujjj** [comment]
@cangyin Thanks for pointing that out, just overlooked the comment..

**Comment by Algunenano** [comment]
Extra info and docs in https://clickhouse.com/docs/en/interfaces/prometheus
