### ISSUE TITLE
Support for non-constant timezone argument for DateTime functions

### ISSUE THREAD

**Issue by imiskolee** [ClickHouse/ClickHouse#6948]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
	19.13.3.26
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

```sql
SELECT
    created_at,
    time_zone,
    toTimeZone(created_at, time_zone)
FROM stores
WHERE id = 22693
LIMIT 1
```
```sh
┌──────────created_at─┬─time_zone──────┬─toTimeZone(created_at, time_zone)─┐
│ 2017-08-09 10:15:01 │ Asia/Hong_Kong │               2017-08-09 10:15:01 │
└─────────────────────┴────────────────┴───────────────────────────────────┘
```

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by filimonov** [comment]
It is known issue / limitation, but maybe it should be fixed someday.

**Comment by alexey-milovidov** [comment]
@filimonov It cannot be fixed, because time zone is characteristic of data type, not value.
The value is stored as unix timestamp and independent of time zone. Time zone affects operations on DateTime components and converson to and from string.

**Comment by filimonov** [comment]
There are a lot of cases then it's not a type issue: toDate, toString, toStartOfDay, toHour etc.

Typical usecase - timestamp (usual unixtime) of event and separate client timezone field. And we need to get hours when users are the most active (in their tz)

**Comment by alexey-milovidov** [comment]
> storing TZ in string form in that case is suboptimal

Probably the best way is to provide predefined Enum with stable identifiers for every time zone.

> And currently the best workaround i can imagine - is to store current utc offset instead of timezone

Yes, it is viable solution if you store UTC offset at the specified moment of time.

> How metrika solves that task? Or tz is set up per account, not per visitor?

We have primary `EventTime` field. It is recorded by server time in unix timestamp. The owner can choose timezone to display their data in reports. We have `EventDate` field that is calculated from `EventTime` using this timezone.

In addition we also have `ClientEventTime` field that stores unix timestamp on website visitor machine (from JavaScript code). And also we have `ClientTimeZone` that store UTC offset on user machine at this moment of time. These fields are not widely used: we cannot trust JavaScript code running in visitor's browser. But Yandex.Metrica user can use these fields for custom reports.

Also the difference in `ClientEventTime` is used for correcting of `EventTime` of events buffered in web browser that will be sent later.

**Comment by filimonov** [comment]
@imiskolee can you please descibe your usecase? The best workaround in Common case is to store offset in minutes in separate field.
I.e.
```
create table x (
time_utc DateTime, 
tz_offset Int32) engine=Log;

Insert into x values (now(), 3600), (now() + 1, -7200):

Select toString(time_utc + tz_offset) from x;

```

**Comment by imiskolee** [comment]
@filimonov I using a string timezone field like "HongKong/Asia". but we also can be try using offset,but need migrate. thanks!
