### ISSUE TITLE
Создание БД в произвольной папке

### ISSUE THREAD

**Issue by PlatonB** [ClickHouse/ClickHouse#6949]
Есть ли способ создавать базы данных не в /var/lib/clickhouse/data/, а в любой другой папке? Где-нибудь в /home, например. Крайне желательно, чтобы это работало без правки конфигов.

**Comment by den-crane** [comment]
Нет такой возможности.
Только с правкой конфигов https://clickhouse.yandex/docs/ru/operations/server_settings/settings/#server_settings-path

**Comment by PlatonB** [comment]
Ну тогда пусть в качестве фичреквеста будет инструкция `SET path = any_path`. Пригодится для лёгкого создания и изменения портативных баз данных.

**Comment by filimonov** [comment]
В произвольной папке без изменения конфигов - не будет никогда, потому что безопасность и в произвольные места файловой системы без явного приглашения нельзя.  

С изменениями конфигов - можно сейчас выбрать один главный каталог. Можно перенести из него любую папку в любое место и сделать symlink. 

С версии 19.15 будет фичер с несколькими дисками, можно тестировать из testing
https://github.com/yandex/ClickHouse/pull/6489/files?file-filters%5B%5D=.md#diff-c4411f3a221073e0dac56b9e95698b83

**Comment by PlatonB** [comment]
Пример очень удобных портативных баз:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/
По ссылке - набор громоздких таблиц и сгенерированных для каждой из них [специальной программой](http://www.htslib.org/doc/tabix.html) индекс-файлов (*.tbi). Было бы прекрасно иметь возможность создавать такие околофайловые базы с помощью ClickHouse.

**Comment by PlatonB** [comment]
Пример очень удобных портативных БД-подобных структур:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/GRCh38_positions/

По ссылке - набор громоздких таблиц и сгенерированных для каждой из них специальной программой индекс-файлов (*.tbi). Было бы прекрасно иметь возможность создавать такие околофайловые сателлиты с помощью ClickHouse. Реализации идеи мешает только отсутствие настройки смены папки на время текущей сессии.

**Comment by proller** [comment]
Любые настройки можно передать серверу при запуске через -- :
clickhouse-server -- --path=/my/home/dir

**Comment by PlatonB** [comment]
Интересное решение. Но при работе через клиентские библиотеки настройки удобно менять с помощью SET.

**Comment by filimonov** [comment]
Сделайте отдельный маленький сервис который будет делать симлинки по требованию клиента. 

Добавление такого фичера в код КХ, мягко говоря, не безопасно. Злоумышленник сможет нанести слишком много "пользы" с помощью этого фичера.
