### ISSUE TITLE
Cast `toTimeZone` to `timestamp` strips timezone

### ISSUE THREAD

**Issue by devanbenz** [ClickHouse/ClickHouse#69512]
**Describe the unexpected behaviour**
Casting to a timestamp strips the timezone.

```
:) SELECT toTimeZone('2024-09-10 11:45:19'::timestamp, 'America/Denver');

SELECT toTimeZone(CAST('2024-09-10 11:45:19', 'timestamp'), 'America/Denver')

Query id: 96cf0a60-238e-4efe-b04a-05ebfb72fbb1

   ┌─toTimeZone(CAST('2024-09-10 11:45:19', 'timestamp'), 'America/Denver')─┐
1. │                                                    2024-09-10 10:45:19 │
   └────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.008 sec.

:) SELECT toTimeZone('2024-09-10 11:45:19'::timestamp, 'America/Denver')::timestamp;

SELECT CAST(toTimeZone(CAST('2024-09-10 11:45:19', 'timestamp'), 'America/Denver'), 'timestamp')

Query id: b774671d-a8e3-495f-acec-5907363cca95

   ┌─CAST(toTimeZone(CAST('2024-09-10 11:45:19', 'timestamp'), 'America/Denver'), 'timestamp')─┐
1. │                                                                       2024-09-10 11:45:19 │
   └───────────────────────────────────────────────────────────────────────────────────────────┘

1 row in set. Elapsed: 0.002 sec.
```

I would expect this to work similarily to postgres and other SQL database engines. 

Postgres:
```

postgres=# SELECT ('2024-09-10 11:45:19' AT TIME ZONE 'America/Denver');

      timezone

---------------------

 2024-09-10 10:45:19

(1 row)

  

postgres=# SELECT ('2024-09-10 11:45:19' AT TIME ZONE 'America/Denver')::timestamp;

      timezone

---------------------

 2024-09-10 10:45:19

(1 row)
```

MariaDB:

```
MariaDB [(none)]> SELECT TIMESTAMP(CONVERT_TZ('2024-09-10 11:45:19', '-5:00', '-6:00'));

+----------------------------------------------------------------+

| TIMESTAMP(CONVERT_TZ('2024-09-10 11:45:19', '-5:00', '-6:00')) |

+----------------------------------------------------------------+

| 2024-09-10 10:45:19                                            |

+----------------------------------------------------------------+

1 row in set (0.001 sec)
```

**How to reproduce**
* Version: 24.9.1.2317
* Using clickhouse-local as a fresh install with no adjustments
* Use queries shown above

**Additional context**
There is a similar issue happening that I'm investigating in Datafusion. I believe this may be part of the Arrow spec and am looking in to why that is the case. I am raising here to get more developers eyes on the issue as I work towards a proposal to either 1. Change the arrow spec or 2. Keep the arrow spec the same and do nothing.

I believe that this is a discrepancy between how "traditional" SQL RDBMs' and Arrow based OLAP systems operate on casts for timestamps, for purposes of DevEx this should function the same.

**Comment by den-crane** [comment]
duplicate
* https://github.com/ClickHouse/ClickHouse/issues/55072

**Comment by devanbenz** [comment]
> duplicate
> 
> * [CAST to DateTime or DateTime64 without a timezone should keep the timezone of its argument #55072](https://github.com/ClickHouse/ClickHouse/issues/55072)

Oh great I was looking for an issue similar to this but couldn't find it! Thanks :)

**Comment by den-crane** [comment]
To clarify: the current behaviour the types `DateTime` <> `DateTime('America/Denver')`. It's not stripping, it kinda cast to another type.

```
desc (SELECT toTimeZone('2024-09-10 11:45:19'::timestamp, 'America/Denver')::timestamp a);
┌─name─┬─type─────┬
│ a    │ DateTime │
└──────┴──────────┴

desc (SELECT toTimeZone('2024-09-10 11:45:19'::timestamp, 'America/Denver')::timestamp('America/Los_Angeles') a);
┌─name─┬─type────────────────────────────┬
│ a    │ DateTime('America/Los_Angeles') │
└──────┴─────────────────────────────────┴
```

**Comment by devanbenz** [comment]
Oh okay I see. I'm wondering why it's built that way instead of adhering to how SQL engines do it though? Was expecting it to function similar.
