### ISSUE TITLE
Data race in `WriteBufferFromHTTPServerResponse`

### ISSUE THREAD

**Issue by antonio2368** [ClickHouse/ClickHouse#69520]
https://s3.amazonaws.com/clickhouse-test-reports/69332/55d6672bc43579dad3edaa1e8c5d595025d50fc8/stateless_tests__tsan__[3_4]/stderr.log
 
This function can be called while the query is running and writing to the output buffer:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/HTTP/WriteBufferFromHTTPServerResponse.cpp#L21
It's called in `onProgress` which acquires the mutex but `ParallelFormattingOutputFormat` ends up calling `offset` directly on the write buffer so no mutex is acquired.

**Comment by thevar1able** [comment]
Repro:

```
curl -vsS "http://localhost:8123/?send_progress_in_http_headers=1&enable_http_compression=1&wait_end_of_query=0&output_format_parallel_formatting=0&input_format_parallel_parsing=1" -o /dev/null -H 'Accept-Encoding: zstd' --compressed --data-binary @- <<< "select distinct sleep(.1),name from generateRandom('name String',1,1000,2) limit 100009 format TSV"
```

**Comment by yakov-olkhovskiy** [comment]
besides bug in `WriteBufferFromHTTPServerResponse` where access to buffer should be locked by existing dedicated mutex, the race condition in the example is a different story and an awful one - it's consequences of having intrusive buffers - compression wrapper is not aware of any concurrency of writing into underlying buffer and access its guts directly... apparently we need to make compression wrappers aware of need of locking underlying buffer too...
