### ISSUE TITLE
Error consulting for the merge and readAndMerge methods of UniquesHashSet

### ISSUE THREAD

**Issue by LeisureGjm** [ClickHouse/ClickHouse#69541]
### Question

Implement the UniquesHashSet structure using go language, insert 100 million pieces of data into the user table of clickhouse, where the id is unique, split the uniqstat data into two temporary memory tables, Decode multiple Uniqueshashsets using merge and get the result around 150000000, while readAndMerge gets the result around 100251741. What's the difference between the two methods?

**Comment by Algunenano** [comment]
> Implement the UniquesHashSet structure using go language

It seems this lost most of its relevance right away, it would be much better to review over the existing code not an external implementation. 

> Decode multiple Uniqueshashsets using merge and get the result around 150000000, while readAndMerge gets the result around 100251741. What's the difference between the two methods?

I think it's worrisome that readAndMerge is never called in the code (just implemented) so it's most likely buggy. Let's just remove it and forget it ever existed.
