### ISSUE TITLE
enable_optimize_predicate_expression not working correctly for distributed table

### ISSUE THREAD

**Issue by Vjeks88** [ClickHouse/ClickHouse#69544]
Version 24.3.3.102

So predicate are not pushdown to main query as it should be when you have enable_optimize_predicate_expression setting turned on. But it is not not applied only when querying distributed table while on local table works as it should be. 

Query example for distributed:
SELECT
  COUNT( `id`) FROM (
    SELECT
      *
    FROM
      (
        SELECT
           *
        FROM
          db.table1_distributed
      )WHERE `id` IN ('0', '565640')
  )

Query example for local table:
SELECT
  COUNT( `id`) FROM (
    SELECT
      *
    FROM
      (
        SELECT
           *
        FROM
          db.table1_local
      )WHERE `id` IN ('0', '565640')
  )

What we find out that when we SET allow_experimental_analyzer = 0 querry for distributed works properly also. 

Times of executions for both options:

allow_experimental_analyzer=1     
Query on local table 	execution: 158 ms
Query on distributed	execution: 5 s 148 ms

allow_experimental_analyzer =0
Query on local table        execution: 143 ms
Query on distributed	execution: 2 s 63 ms

**Comment by SaltTan** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/69472?

**Comment by Vjeks88** [comment]
Duplicate
