### ISSUE TITLE
RBAC Policy hide data for admin user

### ISSUE THREAD

**Issue by abhishekgahlot2** [ClickHouse/ClickHouse#69565]
When I run sql query, the data is available only for the role `uuid_role`, 

```
CREATE ROW POLICY allow_org_rows ON `db`.`table`
FOR SELECT
USING org= 'uuid'
TO 'uuid_role';
```

Admin user specified in users.xml is not able to access the data and only when this policy is removed i am able to see the data.

Version: 24.1.5.6

**Comment by den-crane** [comment]
see * https://github.com/ClickHouse/ClickHouse/issues/64486

**Comment by abhishekgahlot2** [comment]
@den-crane Ah thank you! this config helps.
