### ISSUE TITLE
Table function credentials are not properly masked in analyzer

### ISSUE THREAD

**Issue by alexkats** [ClickHouse/ClickHouse#69571]
There is a masking for functions in analyzer: https://github.com/ClickHouse/ClickHouse/blob/8610a01745a459459159b109b7193a5ab1a2d52e/src/Analyzer/Resolve/QueryAnalyzer.cpp#L2812-L2829

But it's not working for table functions (`s3`, `azureBlobStorage`, ...)

**Comment by alexkats** [comment]
cc @yakov-olkhovskiy @novikd

**Comment by vitlibar** [comment]
I wrote a test for hiding table functions' credentials in analyzer:
https://github.com/ClickHouse/ClickHouse/pull/69667/files

**Comment by yakov-olkhovskiy** [comment]
should be solved by #69615

**Comment by alexkats** [comment]
> should be solved by #69615

Not really, it solved the future issue when we miss some functions for analyzer. But in this case masking only works from `resolveFunction` in `QueryAnalyzer`, but it's not invoked for table functions, there's a different path for them
