### ISSUE TITLE
RBAC permission not application on http port

### ISSUE THREAD

**Issue by abhishekgahlot2** [ClickHouse/ClickHouse#69610]
Hi, 

I am seeing a problem where a user rbac policy is applied on native port (when i access it via port 9000 i can see the data) but when I access clickhouse with http port. I see permission denied. 

Is there a setting that control rbac policy only applicable to native port.

i am able to see other data, just i created a view that is outside the user permitted database. for that database i added a rbac policy via column

The view created is in org1 and user and password is org1 too.

```
CREATE ROW POLICY allow_org_rows ON `analytics`.`table`
FOR SELECT
USING after.organisation = 'org1'
TO 'org1';
```

```
CREATE VIEW IF NOT EXISTS analytics_table1 AS
SELECT
    coalesce(after.organisation, before.organisation) AS organisation,
    toUInt64(toUnixTimestamp(now())) AS _version,
    CAST(multiIf(op = 'd', -1, op IN ('c', 'r', 'u'), 1, 0) AS Int8) AS sign
FROM `analytics`.`table`
WHERE op IN ('c', 'r', 'u', 'd')
  AND after.organisation = 'org1';
```

I use tableplus which uses native port, i am able to see data for that readonly user org1, but on http port which is used by most BI tools i see permission denied error (the same error before applying row based policy).

Error for query

```
 select * from analytics_table1
 
 
 exception": "Code: 497. DB::Exception: org1: Not enough privileges. To execute this query, it's necessary to have the grant SELECT
```

**Comment by den-crane** [comment]
please share `select version()`

**Comment by abhishekgahlot2** [comment]
Sorry, i forgot its 
```
24.1.5.6
```

**Comment by abhishekgahlot2** [comment]
One crucial thing i missed the main table from where i am creating view is distributed database/table. Its ReplicatedMergeTree

I tried doing this on just one node.
