### ISSUE TITLE
Antlr g4 file cannot parse sql while using some keywords as alias

### ISSUE THREAD

**Issue by onlyacat** [ClickHouse/ClickHouse#69613]
**Describe what's wrong**

The following sql can be executed in clickhouse-client.
```sql
SELECT ALIAS.ALIAS AS ALIAS
FROM
(
    SELECT 1 AS ALIAS
) AS ALIAS

Query id: 69deee0d-0693-454f-82f6-7ca6baf32528

┌─ALIAS─┐
│     1 │
└───────┘

```
But for antlr, it cannot parse it correctly. 

The reason it that in `ClickhouseParser.g4` it lacks most of keywords in `keywordForAlias` field. 

I understand that Antlr is not used in ClickHouse itself. Just found some problems during processing some other projects and would like to make the file more clear.

**Comment by onlyacat** [comment]
The following keywords cannot be placed in the alias identifier since this would cause ambiguous behaviours. 
Thus, I include the rest of the keywords.

```
ALL | AND | ANTI | ANY | ARRAY | AS | ASOF | BETWEEN | CROSS | DISTINCT | FINAL | FORMAT | FROM | FULL 
| GLOBAL | GROUP | HAVING | ILIKE | IN | INNER | INTO | IS | JOIN | LEFT | LIKE | LIMIT | NOT | OFFSET | ON 
| OR | ORDER | PREWHERE | RIGHT | SAMPLE | SEMI | SETTINGS | TOP | UNION | USING | WHERE | WINDOW | WITH
```

**Comment by Algunenano** [comment]
The Antlr syntax is unsupported. Feel free to send PRs to update it
