### ISSUE TITLE
union_default_mode setting does not work correctly in queries, aggregating UNION CTE data

### ISSUE THREAD

**Issue by ivaniv10** [ClickHouse/ClickHouse#69633]
**ClickHouse version:** 24.3.11.7

**How to reproduce:** 

```
-- Create table
CREATE TABLE test_table
(
    a Int64,
    country_code String,
    b String,
    amount Int64,
    version_sign Int8 DEFAULT 1,
    version_date DateTime64(9) DEFAULT now64(9)
)
ENGINE = ReplacingMergeTree(version_date)
PRIMARY KEY (a, country_code, b)
ORDER BY (a, country_code, b);


-- Insert data
INSERT INTO test_table
(a, country_code, b, amount, version_sign, version_date)
VALUES(1, 'US', 'NETFLIX', 63, 1, now64(9)), (2, 'US', 'NETFLIX', 63, 1, now64(9));


-- Query data
WITH CTE 
AS 
(
	SELECT 
		a,
	 	country_code,
	 	b,
	 	amount,
	 	toDate(version_date) AS ver_dt
	FROM test_table
	
		UNION
		
	SELECT 
		a,
	 	country_code,
	 	b,
	 	amount,
	 	toDate(version_date) AS ver_dt
	FROM test_table
	WHERE a = 100
)
SELECT 
	country_code,
	b,
	ver_dt,
	SUM(amount) AS amt
FROM CTE 
GROUP BY 1,2,3
SETTINGS union_default_mode = 'DISTINCT';
```
This SELECT statement returns wrong result (amount = 63, but it should be amount=126). But if you use explicitly UNION DISTINCT in the query (and don't rely on the SETTING) - it returns correct results.

**Comment by max-vostrikov** [comment]
I was not able to reproduce this - https://fiddle.clickhouse.com/4850c41c-3d59-4c61-8255-48855988f4e6:
```
24.3.11.7
US	NETFLIX	2024-09-18	126
```
Maybe you have some other settings in your configs which affects results?

**Comment by ivaniv10** [comment]
Yes, `allow_experimental_analyzer` is disabled, because it caused some other issues. Try to run it with `SETTINGS union_default_mode = 'DISTINCT', allow_experimental_analyzer = 0;`

**Comment by max-vostrikov** [comment]
Yes, reproducible without allow_experimental_analyzer on latest version  https://fiddle.clickhouse.com/200f22ac-12b7-43db-a269-fe8ee95e5532
