### ISSUE TITLE
Casting a tuple to a specific type results in all 0 values

### ISSUE THREAD

**Issue by jcrist** [ClickHouse/ClickHouse#69649]
**Company or project name**

[ibis](https://github.com/ibis-project/ibis).

**Describe what's wrong**

Casting a `tuple` to a specific tuple type results in all 0 values. 

**How to Reproduce**

See https://fiddle.clickhouse.com/bbf9e6d3-36af-47df-809b-f02bcde9b257.

```
CREATE TABLE test (a Int32, b Int32) ENGINE=Memory;

INSERT INTO test VALUES (1, 2), (3, 4), (5, 6);

SELECT CAST((a, b) AS Tuple(x Int32, y Int32)) FROM test;
```

Output:

```
(0,0)
(0,0)
(0,0)
```

Oddly if you include a scalar value in the cast, then the data does show up. See https://fiddle.clickhouse.com/4ed71ba4-67e1-4dd4-a232-9e90464e6392.

**Does it reproduce on the most recent release?**

Yes, tested on 24.8.4.13.

**Comment by max-vostrikov** [comment]
Degraded in 24.7 (works in [24.6](https://fiddle.clickhouse.com/401c88ba-c03c-4fa4-b51a-6a2fa9b55cf2)).

Can it be related with https://github.com/ClickHouse/ClickHouse/pull/54881? @vitlibar ?
