### ISSUE TITLE
Unable to read the yandex metrics data

### ISSUE THREAD

**Issue by anirudhkm** [ClickHouse/ClickHouse#6967]
**Unable to read the yandex metrics data**

Trying to read the yandex metrics data using Python, but facing encoding errors when using the utf-8. Tried to follow steps under **Obtaining Tables from Compressed tsv-file**
 in https://clickhouse.yandex/docs/en/getting_started/example_datasets/metrica/

But, was able to read the data using encoding ISO-8859-1, now not able to insert the data into the created table as per the schema prescribed in the same documentation. For example, clientIP6 column, it is prescribed as FixedString(16), but with the encoding done, it's more than 16 characters.

Guide, us on where exactly I should be triaging this issue. Is it an encoding problem or a schema problem? Please, update the documentation with respect to these things, since that would be great.

**Additional context**

Running on a Mac OS, Python 3 anaconda env.

**Comment by alexey-milovidov** [comment]
> Trying to read the yandex metrics data using Python, but facing encoding errors when using the utf-8.

The data is neither in UTF-8 nor in ISO-8859-1 or ASCII.
You should treat this data as binary.

After you read this data, you can tread separate string fields like URL, SearchPhrase as UTF-8, but not ClientIP6 field nor all file as a whole.
