### ISSUE TITLE
Data written because of max_bytes_before_external_*

### ISSUE THREAD

**Issue by Tri0L** [ClickHouse/ClickHouse#6973]
Hello.

Is it possible to see how much data was written to disk during query because of max_bytes_before_external_* ?

**Comment by KochetovNicolai** [comment]
Hi. This information you can find in `system.query_log` table (you need to enable query_log in config and set `log_queries=1`). Then if you know query id, run query like
```
SELECT 
    ProfileEvents.Names, 
    ProfileEvents.Values
FROM system.query_log
ARRAY JOIN ProfileEvents
WHERE query_id = '<query_id>' and ProfileEvents.Names = '<event_name>'
```

For external aggregation `<event_name>` is `ExternalAggregationCompressedBytes` or `ExternalAggregationUncompressedBytes`.
For external sorting there is no special event, but you can use `WriteBufferFromFileDescriptorWriteBytes` to get the number of written bytes in total for query.

**Comment by blinkov** [comment]
@Tri0L do you have any further questions?

**Comment by Tri0L** [comment]
Nope, thanks a lot!
