### ISSUE TITLE
DB::Exception: Conversion from AggregateFunction(uniq, Tuple(city String, name String))

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#69732]
24.6.6.6 https://fiddle.clickhouse.com/3a334edc-0f5e-49c0-9870-9a5f1c9b29b6

```
---- users:
1	London	John
2	Paris	Alice
1	Berlin	Ksenia
---- users2:
1	2
2	1

```

24.7.6.8 https://fiddle.clickhouse.com/bfbeec0c-3c7b-4170-9e29-3e1388ba8ffe

```
 DB::Exception: Conversion from AggregateFunction(uniq, Tuple(city String, name String)) to
 AggregateFunction(uniq, Tuple(String, String)) is not supported: while converting source 
column city_name_uniq to destination column city_name_uniq. (CANNOT_CONVERT_TYPE)
```

https://github.com/ClickHouse/ClickHouse/pull/54881

**Comment by Algunenano** [comment]
The issue should be investigated, but as a workaround you can disable by setting `enable_named_columns_in_function_tuple=0`

**Comment by alexey-milovidov** [comment]
That will be easy to fix - we should declare AggregateFunction types different only by names of tuple arguments as equivalent.
