### ISSUE TITLE
Logical error: 'QueryPlan was not initialized'.

### ISSUE THREAD

**Issue by evillique** [ClickHouse/ClickHouse#69754]
Report: https://s3.amazonaws.com/clickhouse-test-reports/69751/14823f789bcdd4296c2baa23546fa0c244aea532/ast_fuzzer__ubsan_.html

**Comment by al13n321** [comment]
Easy repro (took me forever to figure out because from fuzzer log it seemed that the table is nonempty, but actually it needs to be empty):
```sql
create table t (x Int8) engine MergeTree order by x;
select * from loop(t);
```
