### ISSUE TITLE
Can not build without downloaded submodules

### ISSUE THREAD

**Issue by proller** [ClickHouse/ClickHouse#6981]
**Operating system**
any

**Cmake version**
any

**Ninja version**
any

**Compiler name and version**
any

**Full cmake and/or ninja output**

```
-- Configuring done
CMake Error at contrib/capnproto-cmake/CMakeLists.txt:52 (add_library):
  Cannot find source file:

    /build/clickhouse-19.15.1/contrib/capnproto/c++/src/capnp/c++.capnp.c++

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at contrib/capnproto-cmake/CMakeLists.txt:30 (add_library):
  Cannot find source file:

    /build/clickhouse-19.15.1/contrib/capnproto/c++/src/kj/array.c++ 

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at contrib/capnproto-cmake/CMakeLists.txt:68 (add_library):
  Cannot find source file:

    /build/clickhouse-19.15.1/contrib/capnproto/c++/src/capnp/compiler/type-id.c++

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

```

Broken in https://github.com/yandex/ClickHouse/commit/b4339f266df17c0cd873ef10249647409e66f229

**Comment by abyss7** [comment]
It's a normal situation, that you can't build code with CMake that you don't have on a filesystem - run `git submodule update --init` before running CMake.

**Comment by filimonov** [comment]
Yep. I think @proller was just expecting to see that user-friendly warning:
https://github.com/yandex/ClickHouse/blob/06ea75f9fd5581fdeb10ab264ed73f159ab3797e/cmake/find_capnp.cmake#L20

**Comment by proller** [comment]
No. its not normal.
Its worked before https://github.com/yandex/ClickHouse/commit/b4339f266df17c0cd873ef10249647409e66f229

git submodule update --init cant run on sources downloaded without git.

If cmake see no code on filesystem - this code bcome disabled and skipped from build.

Please just repair what you broke.

**Comment by abyss7** [comment]
@alexey-milovidov mentioned for reference.

**Comment by alexey-milovidov** [comment]
> git submodule update --init cant run on sources downloaded without git.

We should provide source tarballs that are ready to build.

> implicit switch from internal libraries to external ones is a very bad thing. If you want to build without submodules, then explicitly specify `-DUNBUNDLED=ON`

True. One explicit option should be enough to activate alternative build.
But it should not be enabled implicitly.

**Comment by proller** [comment]
> We should provide source tarballs that are ready to build.

Beforre https://github.com/ClickHouse/ClickHouse/commit/b4339f266df17c0cd873ef10249647409e66f229  github's .zip without submodules with <10M size was enough for build.
If you  want include contrib to src - it will be not used for packaging and src size will be ~300M
Also many libs from contrib buildable only on linux/x86_64

> True. One explicit option should be enough to activate alternative build.
But it should not be enabled implicitly.

Without MISSING_ logic to build without submodules tens of options should be explicitly specified. Again old `configure` times!

**Comment by alexey-milovidov** [comment]
> If you want include contrib to src - it will be not used for packaging and src size will be ~300M

But it is the only right way, because production version of ClickHouse can be build only with specific versions of specific libraries.

**Comment by proller** [comment]
> We can use single UNBUNDLED option.
cmake -D UNBUNDLED=1 ..

Its broken. Now you should manually disable USE_SNAPPY and soon all libs not installed in system.
For minimal build you should specify ~30 options.

**Comment by proller** [comment]
> But it is the only right way, because production version of ClickHouse can be build only with specific versions of specific libraries.

... In specific ubuntu 18.04 x86_64, but there are dozens of operating systems and architectures in the world

**Comment by alexey-milovidov** [comment]
> Its broken

It needs to be fixed.

> In specific ubuntu 18.04 x86_64, but there are dozens of operating systems and architectures in the world

@abyss7 will add cross-compile for Mac OS, FreeBSD, then Linux Aarch64 and Linux Power.

**Comment by alexey-milovidov** [comment]
We should never allow to do build without submodules by default, but it's possible to introduce a flag like `-D TROUBLE=1` that the user can set for its own trouble.

**Comment by blinkov** [comment]
@proller, do you have any further questions?
