### ISSUE TITLE
Wrong result of `NOT IN` with hash partitioning(?)

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#69829]
```sql
create table t1(id UInt64) Engine=MergeTree 
PARTITION BY id % 100 ORDER BY (id)
as select number from numbers(1e4);

create table t2(id UInt64) Engine=MergeTree 
PARTITION BY id % 100 ORDER BY tuple()
as select number  from numbers(1e3);

select count() from t1 where id not in (select id from t2);
-- 
0  -- expected 9000

select count() from t1 where identity(id) not in (select id from t2)
--
9000
```

https://fiddle.clickhouse.com/d7fc300e-dc62-4133-9cbd-884e8878ef91

started in 24.7

probably 
* https://github.com/ClickHouse/ClickHouse/pull/66261
or
* https://github.com/ClickHouse/ClickHouse/pull/65676

-----

smaller:

https://fiddle.clickhouse.com/613fac1c-5676-4a9e-8a88-bd2a0a02c3ec

```sql
create table t1(id UInt64) Engine=MergeTree  PARTITION BY id % 2 ORDER BY (id)
as select number from numbers(10);

select count() from t1 where id not in (select 1);
--
5

select count() from t1 where identity(id) not in (select 1)
--
9
```

**Comment by den-crane** [comment]
@KochetovNicolai

**Comment by den-crane** [comment]
One example https://fiddle.clickhouse.com/566b73b5-1542-43f3-b4a6-6522467d00b2

https://t.me/clickhouse_ru/401614

**Comment by lartie** [comment]
Have same problem

**Comment by fm4v** [comment]
Regression after https://github.com/ClickHouse/ClickHouse/pull/65335
Let's revert/fix
@korowa @alexkats
