### ISSUE TITLE
Configuring Clickhouse Keeper to listen to all IPv4 traffic

### ISSUE THREAD

**Issue by tcrykken** [ClickHouse/ClickHouse#69836]
### Company or project name

Building ClickHouse Keeper to provide replication of DB on a 3 node AWS auto scaling group cluster

### Question

**Describe what's wrong**
I can't get clickhouse keeper to listen on IPv4:

sh-4.2$ sudo netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      9656/clickhouse-ser
tcp        0      0 0.0.0.0:9004            0.0.0.0:*               LISTEN      9656/clickhouse-ser
tcp        0      0 0.0.0.0:9005            0.0.0.0:*               LISTEN      9656/clickhouse-ser
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      3120/rpcbind
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      9656/clickhouse-ser
tcp        0      0 0.0.0.0:9009            0.0.0.0:*               LISTEN      9656/clickhouse-ser
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4305/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      3909/master
tcp        0      0 127.0.0.1:9181          0.0.0.0:*               LISTEN      10392/clickhouse-ke
tcp        0      0 127.0.0.1:35491         0.0.0.0:*               LISTEN      3752/containerd
tcp6       0      0 :::111                  :::*                    LISTEN      3120/rpcbind
tcp6       0      0 :::9234                 :::*                    LISTEN      10392/clickhouse-ke
tcp6       0      0 :::22                   :::*                    LISTEN      4305/sshd
tcp6       0      0 ::1:9181                :::*                    LISTEN      10392/clickhouse-ke

**what works not as it is supposed to.**

the configuration element, clickhouse.listen_host while set to either :: or 0.0.0.0 configures a clickhouse instance that appears to be bound to the loopback IPv6 and IPv4 though it may accept any traffic on port 9181. 

The AWS security group for these nodes supports IPv4 and IPv6 traffic to our ports.

**Does it reproduce on recent release?**

yes, its running version ClickHouse server version 24.8.4, .  Keeper hasn't been run on other versions (first implementation)

**Enable crash reporting**

clickhouse.logger.level set to debug.  It isn't crashing but reporting:
<Error> virtual bool DB::DDLWorker::initializeMainThread(): Code: 999. Coordination::Exception: All connection tries failed while connecting to ZooKeeper. nodes: 172.31.84.67:9181, 172.31.34.157:9181

**How to reproduce**

last thing first: I am removing /var/lib/clickhouse/coordination each deployment and considering if that is necessary for /etc/hosts as well (notes on my hosts behavior below)

config .xml's (/etc/clickhouse-server/config.xml has been stripped of remote_servers, macros, zookeeper, listen_host and openSSL elements, otherwise standard aside from http_port changed to 80 from 8123):

/etc/clickhouse-server/config.d/add_keeper_config.xml: (I am substituting private IP addresses and node number is 1, 2, 3 for availability zone a, b, c, respectively) 
<clickhouse>
    <listen_try>1</listen_try>
    <listen_host>0.0.0.0</listen_host> (I have used :: with same result)
    <listen_host>127.0.0.1</listen_host> (I have tested without this element without effect)
    <interserver_http_port>9009</interserver_http_port>
    <interserver_listen_host>0.0.0.0</interserver_listen_host>
    <tcp_port>9000</tcp_port>
    <display_name>production</display_name>

    <zookeeper>
        <node index="1">
            <host>$IPpriv_1a</host>
            <port>9181</port>
        </node>
        <node index="2">
            <host>$IPpriv_1b</host>
            <port>9181</port>
        </node>
        <node index="3">
            <host>$IPpriv_1c</host>
            <port>9181</port>
        </node>
    </zookeeper>

    <macros>
        <shard>1</shard>
        <replica>replica_$node_num</replica>
        <cluster>default</cluster>
    </macros>

    <remote_servers replace="true">
        <default>
        <secret>mysecretphrase</secret>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>$IPpriv_1a</host>
                    <port>9000</port>
                    <user>default</user>
                    <password>thisisntasecurepassword</password>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>$IPpriv_1b</host>
                    <port>9000</port>
                    <user>default</user>
                    <password>thisisntasecurepassword</password>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <host>$IPpriv_1c</host>
                    <port>9000</port>
                    <user>default</user>
                    <password>thisisntasecurepassword</password>
                </replica>
            </shard>
        </default>
    </remote_servers>

</clickhouse>

/etc/clickhouse-keeper/keeper_config.xml (
<clickhouse>
    
    <logger>
        
            <level>debug</level>
            <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        
            <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
            <size>1000M</size>
            <count>3</count>
         
    </logger>
    
    <keeper_server>
        <enable_ipv6>true</enable_ipv6> (I have tried set to false)
        <tcp_port>9181</tcp_port>
        <server_id>$node_num</server_id>
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        <enable_reconfiguration>true</enable_reconfiguration>
        
        <coordination_settings>
            <operation_timeout_ms>10000</operation_timeout_ms>
            <min_session_timeout_ms>10000</min_session_timeout_ms>
            <session_timeout_ms>30000</session_timeout_ms>
            <raft_logs_level>trace</raft_logs_level>
            <compress_logs>false</compress_logs>
            
        </coordination_settings>
  
        
        <hostname_checks_enabled>true</hostname_checks_enabled>
        <raft_configuration>
            <server>
                <id>1</id>
                <hostname>$IPpriv_1a</hostname>
                <port>9234</port>
                <can_become_leader>true</can_become_leader>
                <start_as_follower>true</start_as_follower>
            </server>
            <server>
                <id>2</id>
                <hostname>$IPpriv_1b</hostname>
                <port>9234</port>
                <can_become_leader>true</can_become_leader>
                <start_as_follower>true</start_as_follower>
            </server>
            <server>
                <id>3</id>
                <hostname>$IPpriv_1c</hostname>
                <port>9234</port>
                <can_become_leader>true</can_become_leader>
                <start_as_follower>false</start_as_follower>
            </server>
        </raft_configuration>
    </keeper_server>
</clickhouse>

Expected behavior

I am expecting ClickHouse Keeper to listen to the other nodes on IPprivate:9181 but it is listening on ::1:9181

Error message and/or stacktrace

[clickhouse-server.log.202409201928.txt](https://github.com/user-attachments/files/17080645/clickhouse-server.log.202409201928.txt)

Additional context

and /etc/hosts for all nodes is:
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost6 localhost6.localdomain6
127.0.0.1 clickhouse-keeper-us-east-1b
I know that doesn't look correct.

**Comment by tcrykken** [comment]
@alexanderyoung fyi

**Comment by alexey-milovidov** [comment]
```
echo "
listen_host: '::'
" > /etc/clickhouse-keeper/config.d/listen.yaml
```

**Comment by tcrykken** [comment]
Thanks @alexey-milovidov, I added :: as the listen_host element in /etc/clickhouse-keeper/config XML and that opened the port to IPv6 traffic from the clickhouse keeper clients.  I was not aware it was a valid element in clickhouse keeper's configuration.
