### ISSUE TITLE
Can we ignore the problematic nodes in the remote function?

### ISSUE THREAD

**Issue by heartdance** [ClickHouse/ClickHouse#69840]
### Question

There are 2 clickhouse instances with IP addresses of 192.168.3.1 and 192.168.3.2.

192.168.3.1 has a table named `test` but 192.168.3.2 does not.

SQL:
```sql
SELECT * FROM remote('192.168.3.1:9000,192.168.3.2:9000', 'default', 'test', 'default', '');
```
response error:
```txt
Code: 60. DB::Exception: Table default.test does not exist, server ClickHouseNode [uri=http://192.168.3.2:18123/default
```

Can we ignore the problematic nodes(192.168.3.2) in the remote function?

**Comment by den-crane** [comment]
Have you try `skip_unavailable_shards` ?

```
SELECT * FROM remote('192.168.3.1:9000,192.168.3.2:9000', 'default', 'test', 'default', '')
settings skip_unavailable_shards=1;

**Comment by heartdance** [comment]
> Have you try `skip_unavailable_shards` ?
> 
> ```
> SELECT * FROM remote('192.168.3.1:9000,192.168.3.2:9000', 'default', 'test', 'default', '')
> settings skip_unavailable_shards=1;
> ```

That's rigth! Thank you very much!
