### ISSUE TITLE
Unable to write to local 19.13+ table through distributed 19.11 table.

### ISSUE THREAD

**Issue by JTCunning** [ClickHouse/ClickHouse#6985]
**Describe the bug or unexpected behaviour**
Unable to perform distributed write when shard is on 19.3+ and distributed table is on 19.11.

**Error message and/or stacktrace**
2019.09.19 00:47:53.330687 [ 148 ] {5b106eb2-ac94-4ead-ba43-6da46c872766} <Error> HTTPHandler: Code: 102, e.displayText() = DB::NetException: Unexpected packet from server (expected Data or Exception, got TableColumns): Insertion status:
Wrote 0 blocks and 0 rows on shard 0 replica 0, *************:9000 (average 1 ms per block)
, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x30) [0x7d257f0]
1. clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x25) [0x3bb81d5]
2. clickhouse-server() [0x39b62e3]
3. clickhouse-server() [0x6eb0406]
4. clickhouse-server(ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::_List_iterator<ThreadFromGlobalPool>)+0x1a7) [0x76858b7]
5. clickhouse-server(ThreadFromGlobalPool::ThreadFromGlobalPool<ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}>(ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::function<void ()>, int, std::optional<unsigned long>)::{lambda()#3}&&)::{lambda()#1}::operator()() const+0x3e) [0x7685e9e]
6. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1a6) [0x76833c6]
7. clickhouse-server() [0xb7f7a80]
8. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f6727dba184]
9. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f67275dd03d]
 (version 19.11.5.28 (official build))

**Additional context**
Attempted with both 19.13 and 19.14 (latest released debian)

Writing via HTTP with `'insert_distributed_sync': 1` and `'insert_allow_materialized_columns': 1`.

It would be nice to not have to pause writes during a rolling upgrade, but if this is a wild ask, I understand.

**Comment by alexey-milovidov** [comment]
It's about https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#backward-incompatible-change-3

**Comment by JTCunning** [comment]
I somehow missed this in the changelog. Thanks!
