### ISSUE TITLE
max_bytes_before_external_group_by  only for group by ?

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#6986]
hi team,
  is the setting max_bytes_before_external_group_by only for group by not for all sql?

**Comment by KochetovNicolai** [comment]
Yes, this setting is only for aggregation phase. Setting `max_bytes_before_external_sort` is only for sorting at `ORDER BY`.

**Comment by blinkov** [comment]
@peaksnail do you have any further questions?
