### ISSUE TITLE
view+distribute is very slow slow slow

### ISSUE THREAD

**Issue by Data-bytes305** [ClickHouse/ClickHouse#69873]
distribute table is 4 shards 1 replication.
 CREATE TABLE biads.ads_ration_dc_goods_day_local on cluster cluser_1shard4repl
(
    stat_day date,
    out_buid UInt8,
    out_shop_id String,
    in_shop_id String,
    goodsid String ,
     day_t Tuple(UInt64,UInt64),
    `rt_qty` Decimal(20, 6),
    `rt_boxes` Decimal(20, 6),
    `rt_cost` Decimal(20, 6),
    `rt_taxcost` Decimal(20, 6),
    `cc_rt_qty` Decimal(20, 6),
    `cc_rt_boxes` Decimal(20, 6),
    `cc_rt_cost` Decimal(20, 6),
    `cc_rt_taxcost` Decimal(20, 6),
    `zt_rt_qty` Decimal(20, 6),
    `zt_rt_boxes` Decimal(20, 6),
    `zt_rt_cost` Decimal(20, 6),
    `zt_rt_taxcost` Decimal(20, 6),

     week_t Tuple(UInt64,UInt64),
    `rt_qty_wtd` Decimal(20, 6),
    `rt_boxes_wtd` Decimal(20, 6),
    `rt_cost_wtd` Decimal(20, 6),
    `rt_taxcost_wtd` Decimal(20, 6),
    `cc_rt_qty_wtd` Decimal(20, 6),
    `cc_rt_boxes_wtd` Decimal(20, 6),
    `cc_rt_cost_wtd` Decimal(20, 6),
    `cc_rt_taxcost_wtd` Decimal(20, 6),
    `zt_rt_qty_wtd` Decimal(20, 6),
    `zt_rt_boxes_wtd` Decimal(20, 6),
    `zt_rt_cost_wtd` Decimal(20, 6),
    `zt_rt_taxcost_wtd` Decimal(20, 6),

     month_t Tuple(UInt64,UInt64),
    `rt_qty_mtd` Decimal(20, 6),
    `rt_boxes_mtd` Decimal(20, 6),
    `rt_cost_mtd` Decimal(20, 6),
    `rt_taxcost_mtd` Decimal(20, 6),
    `cc_rt_qty_mtd` Decimal(20, 6),
    `cc_rt_boxes_mtd` Decimal(20, 6),
    `cc_rt_cost_mtd` Decimal(20, 6),
    `cc_rt_taxcost_mtd` Decimal(20, 6),
    `zt_rt_qty_mtd` Decimal(20, 6),
    `zt_rt_boxes_mtd` Decimal(20, 6),
    `zt_rt_cost_mtd` Decimal(20, 6),
    `zt_rt_taxcost_mtd` Decimal(20, 6),

    year_t Tuple(UInt64,UInt64),
    `rt_qty_ytd` Decimal(20, 6),
    `rt_boxes_ytd` Decimal(20, 6),
    `rt_cost_ytd` Decimal(20, 6),
    `rt_taxcost_ytd` Decimal(20, 6),
    `cc_rt_qty_ytd` Decimal(20, 6),
    `cc_rt_boxes_ytd` Decimal(20, 6),
    `cc_rt_cost_ytd` Decimal(20, 6),
    `cc_rt_taxcost_ytd` Decimal(20, 6),
    `zt_rt_qty_ytd` Decimal(20, 6),
    `zt_rt_boxes_ytd` Decimal(20, 6),
    `zt_rt_cost_ytd` Decimal(20, 6),
    `zt_rt_taxcost_ytd` Decimal(20, 6)

)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/biads/ads_ration_dc_goods_day_local/{logic_cluster1_key}/{logic_cluster1_shard}', '{replica}')
PARTITION BY toYYYYMM(stat_day)
ORDER BY (stat_day, out_shop_id)
SETTINGS index_granularity = 8192 ;

view: 
create or replace view biads.v_ads_ration_dc_goods_day on cluster cluser_4shard1repl as
select stat_day,
       out_buid,
       out_shop_id as dc_id,
       in_shop_id,
       goodsid,
       day_t,
       rt_qty,
       rt_boxes,
       rt_cost,
       rt_taxcost,
       cc_rt_qty,
       cc_rt_boxes,
       cc_rt_cost,
       cc_rt_taxcost,
       zt_rt_qty,
       zt_rt_boxes,
       zt_rt_cost,
       zt_rt_taxcost,
       week_t,
       rt_qty_wtd,
       rt_boxes_wtd,
       rt_cost_wtd,
       rt_taxcost_wtd,
       cc_rt_qty_wtd,
       cc_rt_boxes_wtd,
       cc_rt_cost_wtd,
       cc_rt_taxcost_wtd,
       zt_rt_qty_wtd,
       zt_rt_boxes_wtd,
       zt_rt_cost_wtd,
       zt_rt_taxcost_wtd,
       month_t,
       rt_qty_mtd,
       rt_boxes_mtd,
       rt_cost_mtd,
       rt_taxcost_mtd,
       cc_rt_qty_mtd,
       cc_rt_boxes_mtd,
       cc_rt_cost_mtd,
       cc_rt_taxcost_mtd,
       zt_rt_qty_mtd,
       zt_rt_boxes_mtd,
       zt_rt_cost_mtd,
       zt_rt_taxcost_mtd,
       year_t,
       rt_qty_ytd,
       rt_boxes_ytd,
       rt_cost_ytd,
       rt_taxcost_ytd,
       cc_rt_qty_ytd,
       cc_rt_boxes_ytd,
       cc_rt_cost_ytd,
       cc_rt_taxcost_ytd,
       zt_rt_qty_ytd,
       zt_rt_boxes_ytd,
       zt_rt_cost_ytd,
       zt_rt_taxcost_ytd
from biads.ads_ration_dc_goods_day ;

run next two queries:
**--  53 rows in set. Elapsed: 0.048 sec. Processed 18.66 million rows, 290.92 MB (387.56 million rows/s., 6.04 GB/s.)**
 SELECT
    out_shop_id,
    count() AS logs
FROM biads.ads_ration_dc_goods_day AS tt
WHERE stat_day = toDate('2023-12-31')
GROUP BY out_shop_id ;
[explain_by_distribute.txt](https://github.com/user-attachments/files/17100562/explain_by_distribute.txt)

**--  53 rows in set. Elapsed: 15.260 sec. Processed 2.69 billion rows, 42.36 GB (176.07 million rows/s., 2.78 GB/s.)**
SELECT
    dc_id,
    count() AS logs
FROM biads.v_ads_ration_dc_goods_day
WHERE stat_day = toDate('2023-12-31')
GROUP BY dc_id ;
[explain_by_view.txt](https://github.com/user-attachments/files/17100584/explain_by_view.txt)

**Comment by nickitat** [comment]
difference comes from the amount of data read. prob we don't do push-down to remote nodes.
first of all:
1. what version you are using?
2. does anything changes if you disable new analyzer?

**Comment by SaltTan** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/69472?

**Comment by nickitat** [comment]
> duplicate #69472?

probably, thanks.

@Data-bytes305 pls verify by setting `allow_experimental_analyzer=0`. if doesn't work pls reopen

**Comment by Data-bytes305** [comment]
@nickitat  thanks ,  will the next version fix the isssue ?
