### ISSUE TITLE
Images functions support

### ISSUE THREAD

**Issue by pufit** [ClickHouse/ClickHouse#69888]
ClickHouse is probably not the best solution for storing images... But if you are brave enough, you can do it, and we can probably add some functions for this case.

**Use case**

If you have images stored in a table in a blob (String) format, you may want to do:

- Analytics: load width, height, metadata, color distribution, perceptual hashing, etc
- TTL rollover: lover resolution after some time to save some disk space
- ML: image models take only standardized-size images (224x224 in CLIP, for example). We can utilize ClickHouse's vectorized CPU operations for preprocessing before passing it to the Python UDF with GIL.

**Describe the solution you'd like**

Add [Magick++](https://imagemagick.org/script/magick++.php) to the contrib and implement some basic functions.
The simplest solution I see is to add a new type `Image('type')`, which is actually a `Tupple(String, Enum)` of data and image type (jpg, png, ..., default: auto).

**Comment by pufit** [comment]
@alexey-milovidov wdyt?

cc @nikitamikhaylov

**Comment by alexey-milovidov** [comment]
Good idea, but I'm afraid it could be too specific,
plus, libraries like imagemagik have a very large footprint of vulnerabilities
(they represent a collection of data formats, many of which are obscure and not well-tested).

I'd like it if we make a prototype with UDFs first. The drawback is copying the image data around.

**Comment by alexey-milovidov** [comment]
Image resampling is an extremely complex problem.

1. Conversion of color spaces with gamma. 2. Various downsampling algorithms. 3. Avoiding clipping and loss of precision.

Either we avoid doing that, or implement a minimal solution, which is wrong, or bury too deep into this topic.
