### ISSUE TITLE
中文TTL文档中示例SQL代码错误

### ISSUE THREAD

**Issue by sultra** [ClickHouse/ClickHouse#69889]
**中文版TTL 说明文档*
文档： https://github.com/ClickHouse/ClickHouse/blob/master/docs/zh/sql-reference/statements/alter/ttl.md

**多了 ;  符号 **
``` sql
CREATE TABLE table_with_ttl
......
ORDER BY tuple()
TTL event_time + INTERVAL 3 MONTH;
SETTINGS min_bytes_for_wide_part = 0;
```
MONTH 后面不应该有符号

**Comment by nickitat** [comment]
good catch!
