### ISSUE TITLE
Are Memory tables dropped right away without using SYNC?

### ISSUE THREAD

**Issue by italodamato** [ClickHouse/ClickHouse#69909]
I'd like to confirm whether tables created with `ENGINE = Memory` are dropped immediately or if they also need the `SYNC` modifier as MergeTree tables. I'd also like to know if the behaviour is different when using `CREATE OR REPLACE TABLE`.

**Comment by CurtizJ** [comment]
In-memory tables are dropped immediately and you don't need the `SYNC` modifier. The behaviour is the same when using `CREATE OR REPLACE TABLE`.
