### ISSUE TITLE
How can a single-node user configured with user.xml be upgraded to a cluster user

### ISSUE THREAD

**Issue by XSWClevo** [ClickHouse/ClickHouse#69926]
### Question

I created a single-node user in user.d/myuser.xml and now I need to change it to a cluster user. How do I change it? I use `ALTER USER myuser IDENTIFIED BY 'xxxxxxx' ON CLUSTER 'parallel_replicas';` DB::Exception: Cannot update user 'myuser' in users.xml because this storage is readonly. Below is a screenshot of my myuser.xml configuration.
![image](https://github.com/user-attachments/assets/df04abfd-288a-48c9-9d32-b736889b02bd)

**Comment by CurtizJ** [comment]
You cannot alter the user created in config. You have to either create a user via [sql](https://clickhouse.com/docs/en/sql-reference/statements/create/user) or modify the config.
