### ISSUE TITLE
There is no log rotation for stderr.log

### ISSUE THREAD

**Issue by VOkunev** [ClickHouse/ClickHouse#69933]
The log file is constantly being updated with lines like:
```
Saved preprocessed configuration to...
Processing configuration file...
Merging configuration file...
```
And it has no rotation, so it can grow to 14 Gb or more.

**Comment by alexey-milovidov** [comment]
This is ok. stderr is only used for diagnostics around loading configuration files.

Not doing anything to rotate it on the server side is reasonable.
14 GB is not a lot.

If it is a concern, take a look inside this file and delete it.
