### ISSUE TITLE
Help: ODBC not able to connect

### ISSUE THREAD

**Issue by thegausiantheory** [ClickHouse/ClickHouse#69932]
**Describe the unexpected behaviour**
Cannot connect to an ODBC (Oracle data source) from Clickhouse, Native ODBC connectivity was tested and works. 

**How to reproduce**
* Clickhouse Server, Client, and clickhouse-odbc-bridge 24.8.4.13 LTS all of the same version were installed 
* Tested the ODBC connectivity to the Remote Oracle database from the Clickhouse server e.g. "isql -v OracleDB" gives a connected response, and queries returned the correct response.
* Also, all required instant client driver files are present in the /opt/oracle/instantclient_23_5 directory.
* However, when I try a "SELECT count() FROM odbc('DSN=OracleDB', schema, table)" I am getting an error.
```
Received exception from server (version 24.8.4):
Code: 86. DB::Exception: Received from localhost:9000. DB::HTTPException. DB::HTTPException: Received error from remote server http://127.0.0.1:9018/columns_info?use_connection_pooling=1&version=1&connection_string=DSN%3DOracleDB&schema=IRIS_MGR&table=PERSON&external_table_functions_use_nulls=1. HTTP status code: 500 Internal Server Error, body: Error getting columns from ODBC 'std::exception. Code: 1001, type: nanodbc::database_error, e.what() = contrib/nanodbc/nanodbc/nanodbc.cpp:1046: 0100: [unixODBC][Driver Manager]Can't open lib '/opt/oracle/instantclient_23_5/libsqora.so.23.1' : file not found  (version 24.8.4.13 (official build))'
. (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER)
```
* Hint: I was getting this error with the native odbc connectivity too, but I had to set the LD_LIBRARY_PATH to my oracle directory, in my case it's /opt/oracle/instantclient_23_5, and it worked. However I tried both setting and unsetting the LD_LIBRARY_PATH but in Clickhouse I get the same error.

**Comment by MclellandG** [comment]
I was also having issues with ODBC connections after upgrading to the latest version `24.9.2.42`.   Noticed that it does not contain the clickhouse-odbc-bridge in `usr/bin' whereas the version where it works `24.7.4.51` the clickhouse-odbc-bridge is present in 'usr/bin`

**Comment by alexey-milovidov** [comment]
You can copy the .so to a system-wide library path, such as `/usr/lib/`
