### ISSUE TITLE
Why results are empty when data is present ? 

### ISSUE THREAD

**Issue by ichintanjoshi** [ClickHouse/ClickHouse#69990]
### Company or project name

iLearn, we use clickhouse as a part of Analytics which is offered by Cairn (tutor). 

### Question

Hello, 

So I created my table this monring, in this manner 

`select * from mysql(Params)`

Results were being shown

Then created table 

`Create Table user (Params) Engine = MySQL(params) `

Then did 

`select * from user` 

Results were being fetched, 

Now after connecting it to Superset It was working well, after a while , it came as blank 

I go to clickhouse and check 

`select * from user` 

0 Rows returned 

So I drop the table, `drop table user` 

and create again, and do select *, It's empty 

But if I create it in this manner 

Create table user1 (params) Engine=MySQL(params)

and do a `select *` it'll work again and show me the results 

If I rename it to user again 

Like `rename table user1 to user` 

It'll be blank again 

and if I drop everything and create again, it'll be empty 

but if I do `rename table user to user1` 

It'll start showing results again. 

I've tried removing all cache by System drop .... cache commands 
I've tried attach and detach table 
I've tried new database 

everytihng

**Comment by den-crane** [comment]
Can you please share `select version()`, `select name, value from system.settings where changed`

**Comment by ichintanjoshi** [comment]
Sure @den-crane  

`select version()` 

Output :- 

```
┌─version()─┐
│ 22.1.3.7  │
└───────────┘
```


`select name, value from system.settings where changed`

Output 

```
┌─name─────────────┬─value───────┐
│ load_balancing   │ random      │
│ max_memory_usage │ 10000000000 │
└──────────────────┴─────────────┘
```


I wiped entire DB, did setup from scratch and it worked, but the problem started again.

**Comment by Algunenano** [comment]
Please upgrade to a supported release. 22.1 is way out of support.

**Comment by ichintanjoshi** [comment]
@Algunenano  will you open this again if I reproduce this in latest version ?

**Comment by Algunenano** [comment]
Absolutely
