### ISSUE TITLE
Any other access control settings can't be specified with `grants`: while parsing user 'admin' in users configuration file

### ISSUE THREAD

**Issue by Dnivd** [ClickHouse/ClickHouse#70012]
### Question

Privet! Stolknulsya s problemoy Pri popytke ukazat' v konfiguratsionnom fayle pol'zovatelya users.d/admin.xml (kak primer) kakuyu rol' ispol'zovat' cherez blok ***grants /grants*** Pri resrarte clickhouse (systemctl restart clickhouse-server.service) Poluchayu oshibku: _<Error> Application: Code: 36. DB::Exception: Any other access control settings can't be specified with `grants`: while parsing user 'admin' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below)_ Pri etom takaya vozmozhnost' opisana v dokumentatsii po puti: https://clickhouse.com/docs/en/operations/settings/settings-users YA tak ponimayu chto dannyy funktsional isklyuchen? Ili ya chto to ne tak delayu Pomogite pozhaluysta
Ещё
815 / 5 000
Hello!
I encountered a problem
When trying to specify in the user configuration file users.d/admin.xml (as an example) which role to use via the ***grants /grants*** block
When restarting clickhouse (systemctl restart clickhouse-server.service)
I get an error:
_<Error> Application: Code: 36. DB::Exception: Any other access control settings can't be specified with `grants`: while parsing user 'admin' in users configuration file: while loading configuration file '/etc/clickhouse-server/users.xml'. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below)_

This feature is described in the documentation at the following path:

https://clickhouse.com/docs/en/operations/settings/settings-users

I understand that this functionality has been excluded? Or am I doing something wrong

Please help
Отправить отзыв

**Comment by SLoeuillet** [comment]
This setting can't be specified at the same time with dictionaries, access_management, named_collection_control, show_named_collections_secrets and allow_databases settings.

**Comment by Dnivd** [comment]
Thank you for your reply

**Comment by asad-awadia** [comment]
@SLoeuillet why not? how to give both?
