### ISSUE TITLE
24.7 broke some queries using `tuple()` and NULLs

### ISSUE THREAD

**Issue by lpelecq** [ClickHouse/ClickHouse#70022]
The change in behavior of the `tuple()` function in 24.7 (https://github.com/ClickHouse/ClickHouse/pull/54881) seems to break some INSERT SELECT requests with two similar tuples in different columns. 

I found one case (using `tuple()`, NULLs, grouping and array) where a query :

- crashes since 24.7 : https://fiddle.clickhouse.com/7446614a-4743-4729-958c-b3142a29e89c
- works in 24.6.6.6 : https://fiddle.clickhouse.com/22c57812-2a36-44e1-a61f-83283d03256b

And one simpler case (using `tuple()` and NULLs) where the result between the INSERT SELECT and the SELECT
- is different since 24.7 : https://fiddle.clickhouse.com/22ee195e-7151-4be9-bdac-e87432a64407 
- was the same in 24.6.6.6 : https://fiddle.clickhouse.com/5f9727fe-c602-4f2f-b4b5-7c58a698d224

From the error message it looks like the names of the elements from the two Tuple columns are being mixed up.

**Expected behavior**

The behavior of 24.6.6.6 was correct

**Error message and/or stacktrace**

```
Received exception from server (version 24.8.4):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: Cannot capture column 2 because it has incompatible type: got Tuple(col_a Nullable(String), type String), but Tuple(col_b Nullable(String), type String) is expected.. (LOGICAL_ERROR)
```

**Additional context**

For the crashing case :

- When removing the `arraySort()` the query works in 24.7 and latest but the result is different than in 24.6.6.6 (and wrong).
- Using `NULL` instead of `nullIf(data, '')` gives the same error.
- Using `data` instead of `nullIf(data, '')` gives the same behavior as when removing the `arraySort()`

In my original use case the two `nullIf(data, '')` are two different templeted JSON extraction function, sometimes at `NULL` based on our workflow.

I hope there is enough context to identify what is causing this bug.

EDIT : added link to fiddles in the last working version

**Comment by lpelecq** [comment]
If additional information can help, this seem to happen when the expressions in the tuples are the same but with different alias names. 
- with different expressions : https://fiddle.clickhouse.com/530d0caa-ff62-4ec5-95a6-22a690f0bd3b
- with the same expression : https://fiddle.clickhouse.com/82b44709-165b-4e93-ade9-f67ab75ee443

**Comment by Algunenano** [comment]
The issue should be investigated, but as a workaround you can disable by setting `enable_named_columns_in_function_tuple=0`
