### ISSUE TITLE
clickhouse MaterializedMySQL cannot be resolved mysql XA rollback Causing replication failure

### ISSUE THREAD

**Issue by a469420517** [ClickHouse/ClickHouse#70055]
### Question

MySQL version 5.7 uses the Materialized MySQL engine to synchronize MySQL data. When MySQL enables XA transactions, the timing for writing binlog to XA transactions in MySQL version 5.7 becomes two stages. The pre stage will write binlog once, and the commit/rollback stage will write binlog once. When XA transactions commit normally, Materialized MySQL synchronizes normally. When XA transactions roll back abnormally, there will be XA ROLLback X'31302e3134382e302e31312e746d3137323735353535353533237333735 ', X'31302e3134382e302e31312e746d746d in the binlog log. The statement 3534373438', 1096044365 cannot be recognized by MaterializedMySQL, resulting in replication failure

**Comment by a469420517** [comment]
MySQL XA transactions will commit a binlog once in the pre stage and once in the commit/rollback stage, and the GTIDs of the two binlogs are not consistent. Clickhouse does not support transactions. Is it possible that this situation cannot be recognized? But only rollback will fail to replicate, while commit is normal. Is it because commit is ignored directly, while rollback cannot be ignored? Clickhouse does not support transactions and cannot perform rollback? Clickhouse version 22.1.22, specific error message:
Code: 49. DB::Exception: ParseQueryEvent: Unsupported query event:XA ROLLBACK X'31302e3134382e302e31312e746d313732373437343437393636373034353534',X'31302e3134382e302e31312e746d39313036',1096044365. (LOGICAL_ERROR) (version 22.1.2.2 (official build))

**Comment by Felixoid** [comment]
Both mysql 5.7 and clickhouse 22.1 are far from the supported times.

I am afraid you need to try it with a newer ClickHouse version, at least.
