### ISSUE TITLE
Clickhouse-keeper - mntr - This instance is not currently serving requests

### ISSUE THREAD

**Issue by Dnivd** [ClickHouse/ClickHouse#70092]
Hello
I'm trying to set up clickhouse-keeper
Set up 3 servers on virtualbox

I'm using the documentation https://clickhouse.com/docs/en/architecture/replication

But when checking the functionality, a problem occurs

**echo mntr | nc localhost 9181**

This instance is not currently serving requests

**Checking the log file there is a lot of spam like:**
2024.09.28 12:28:28.640124 [ 2077 ] {} <Information> KeeperDispatcher: Server still not initialized, will not apply configuration until initialization finished
2024.09.28 12:28:30.902209 [ 2038 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 192.168.50.253:55098
2024.09.28 12:28:30.902343 [ 2038 ] {} <Warning> KeeperTCPHandler: Ignoring user request, because the server is not active yet
2024.09.28 12:28:30.908486 [ 2038 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 192.168.50.253:55112
2024.09.28 12:28:30.908577 [ 2038 ] {} <Warning> KeeperTCPHandler: Ignoring user request, because the server is not active yet
2024.09.28 12:28:30.913645 [ 2038 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 192.168.50.253:55124
2024.09.28 12:28:30.913736 [ 2038 ] {} <Warning> KeeperTCPHandler: Ignoring user request, because the server is not active yet
2024.09.28 12:28:31.896825 [ 2038 ] {} <Trace> KeeperTCPHandlerFactory: Keeper request. Address: 192.168.50.54:46224
2024.09.28 12:28:31.896936 [ 2038 ] {} <Warning> KeeperTCPHandler: Ignoring user request, because the server is not active yet

_Address: 192.168.50.54 and Address: 192.168.50.253 these are servers clickhouse_

Found a previously solved https://github.com/ClickHouse/ClickHouse/issues/55832
But even tried to use the configuration from https://github.com/ClickHouse/ClickHouse/issues/55832#issuecomment-1782630694

Didn't bring any results, in the end I returned as specified in the documentation https://clickhouse.com/docs/en/architecture/replication

Please tell me where and what I configured wrong :(

**Аttaching log files and settings from my 3 servers:**
[clickhouse-keeper3_clickhouse-keeper.err.log](https://github.com/user-attachments/files/17172901/clickhouse-keeper3_clickhouse-keeper.err.log)
[clickhouse-keeper2_clickhouse-keeper.err.log](https://github.com/user-attachments/files/17172902/clickhouse-keeper2_clickhouse-keeper.err.log)
[clickhouse-keeper3_clickhouse-keeper.log](https://github.com/user-attachments/files/17172903/clickhouse-keeper3_clickhouse-keeper.log)
[clickhouse-keeper2_clickhouse-keeper.log](https://github.com/user-attachments/files/17172904/clickhouse-keeper2_clickhouse-keeper.log)
[clickhouse-keeper1_clickhouse-keeper.err.log](https://github.com/user-attachments/files/17172905/clickhouse-keeper1_clickhouse-keeper.err.log)
[clickhouse-keeper1_clickhouse-keeper.log](https://github.com/user-attachments/files/17172906/clickhouse-keeper1_clickhouse-keeper.log)
[keeper_config.zip](https://github.com/user-attachments/files/17172910/keeper_config.zip)

**Comment by antonio2368** [comment]
Can you try deleting `/var/lib/clickhouse-keeper/coordination/state` from all keeper nodes?

**Comment by Dnivd** [comment]
[antonio2368](https://github.com/antonio2368)
Thanks for the solution, but the problem was solved

Forgot to unsubscribe a bit earlier

I solved the problem by running
**echo rcvr | nc localhost 9181**
![изображение](https://github.com/user-attachments/assets/0f06e179-1b83-46f5-95f2-991894d12114)

I just still don't understand why it was necessary to put the servers into recovery mode

For those who need it, here's the topic
https://clickhouse.com/docs/en/guides/sre/keeper/clickhouse-keeper

--
Who should I contact now so that the topic above is indicated in https://clickhouse.com/docs/en/architecture/replication

**Comment by antonio2368** [comment]
Something was incorrectly configured, and the problem would've been probably solved with just deleting the `state` file from Keepers (this solution is only okay if the Keepers are fresh without any data stored.

Not sure how they ended up in such a state, but it can happen if all nodes have `start_as_follower` set to `true`.
