### ISSUE TITLE
EXISTS <table> requires unexpected privileges

### ISSUE THREAD

**Issue by vitlibar** [ClickHouse/ClickHouse#70094]
Command `EXISTS <table>` requires unexpected privileges in the following scenario:

```
CREATE USER u1;
GRANT SELECT ON *.* TO u1;
REVOKE SELECT ON system.zookeeper FROM u1;
```

(login as u1)

```
EXISTS system.zoo;

   ┌─result─┐
1. │      0 │
   └────────┘
```

```
EXISTS system.zookeeper;

Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: u1: Not enough privileges. To execute this query, it's necessary to have the grant SHOW TABLES ON system.zookeeper. (ACCESS_DENIED)
```

```
EXISTS system.zookeeper_info;

Code: 497. DB::Exception: Received from localhost:9000. DB::Exception: u1: Not enough privileges. To execute this query, it's necessary to have the grant SHOW TABLES ON system.zookeeper_info. (ACCESS_DENIED)
```

That's not correct - `REVOKE SELECT ON system.zookeeper FROM u1` should remove only the privilege on `system.zookeeper`, and not on other tables.

**Comment by vitlibar** [comment]
Broken in PR https://github.com/ClickHouse/ClickHouse/pull/65311

**Comment by pufit** [comment]
Yes, this is a bug with implicit grants because `SELECT * FROM system.zookeeper_info` works

**Comment by vitlibar** [comment]
@pufit Could you please fix it?
Also it would be helpful to have a command to show implicit grants, something like `SHOW GRANTS WITH IMPLICIT`.
