### ISSUE TITLE
should skipping index of type set with too low max_size lead to incorrect query results?

### ISSUE THREAD

**Issue by pakud** [ClickHouse/ClickHouse#70108]
**Describe the unexpected behaviour**

take attached go.sql and execute it. i'd expect below two queries to return identical result, yet the first one returns 0 rows (which is incorrect), 2nd - some rows (correct).

```
SELECT * FROM tmp0 WHERE c1 = 'dedenk1d4q' SETTINGS use_skip_indexes=1;    
SELECT * FROM tmp0 WHERE c1 = 'dedenk1d4q' SETTINGS use_skip_indexes=0; 
```

**How to reproduce**
* Clickhouse 24.9.1.3278 installed from official .deb package
* Clickhouse client 24.9.1 - cat go.sql|clickhouse-client -h127.0.0.1 --multiline --multiquery ; 
* i'm using clean installation on Debian 12, with default settings. 

**Expected behavior**
i'd expect above SELECT statements to return the same result regardless of _use_skip_indexes_ setting.

[go.zip](https://github.com/user-attachments/files/17179534/go.zip)

thx!

**Comment by den-crane** [comment]
@Algunenano major bug, reproducible with earlier versions, at east with 24.7

**Comment by den-crane** [comment]
* https://github.com/ClickHouse/ClickHouse/pull/64098
