### ISSUE TITLE
Seeking Advice on Using ClickHouse on FreeBSD 

### ISSUE THREAD

**Issue by Huseyn-Ahmadli** [ClickHouse/ClickHouse#70116]
Hello 

I’m considering using ClickHouse on FreeBSD and would like to know about any potential disadvantages or issues. Are there any performance disadvantages in FreeBSD compared to Linux? What platform do you prefer most for running ClickHouse, and why?

Could anyone share their experiences or provide recommendations on this matter?

**Comment by Algunenano** [comment]
There are multiple features that aren't implemented or available under FreeBSD, like (AFAICS) rust libraries, Parquet, introspection functions (addressToSymbol) etc.

> What platform do you prefer most for running ClickHouse, and why?

Linux with a recent kernel. Because that's what everyone, including the CI, uses so it's the best if you want to avoid surprises.
