### ISSUE TITLE
Unable to Add a New Column with Values from S3 Using joinGet in a ReplicatedMergeTree Table

### ISSUE THREAD

**Issue by minQZ** [ClickHouse/ClickHouse#70125]
### Question

Hello,

I want to add a new column to an existing table. The values for this new column are stored in an S3 bucket as pairs of primary keys and values, in a format that can be parsed as JSON (although it's not a very standard format). The values do not follow a specific rule and are not all unique nor all the same.

I tested using a temporary table with the Join engine and joinGet on a MergeTree table, and it worked. However, when I attempt this approach on a table using the ReplicatedMergeTree engine, the SQL statement fails with the following error:

> The source storage is replicated so ALTER UPDATE/ALTER DELETE statements must use only deterministic functions. Function 'joinGet' is non-deterministic.

Is there an alternative method to achieve this? Any advice would be greatly appreciated.

Thank you!

**Comment by canhld94** [comment]
```
M(Bool, allow_nondeterministic_mutations, false, "Allow non-deterministic functions in ALTER UPDATE/ALTER DELETE statements", 0) \
```
