### ISSUE TITLE
Queries not parallelizing with enough CPU

### ISSUE THREAD

**Issue by gabrielmcg44** [ClickHouse/ClickHouse#70150]
**Describe the situation**
I am trying to run multiple heavy queries concurrently to simulate someone opening a dashboard. But the queries are not parallelizing as I would expect. And the CPU resource usage did not pass 50%.

I am using a single server
      cpu:     92
      memory:  340G

This is what it takes to run one single query:

<img width="873" alt="Screenshot 2024-09-30 at 22 11 27" src="https://github.com/user-attachments/assets/6fb35917-a91b-4ce9-9c37-d893eeb4625a">

Looking at clickhouse's resources dashboard I see:

<img width="1430" alt="Screenshot 2024-09-30 at 22 14 26" src="https://github.com/user-attachments/assets/d4ac0a65-06e5-4137-863f-ad5dcd385d7f">

So it takes 4 seconds and uses only 2.6 CPUs

When I run 4 queries (repeated) at the same time, I got:

<img width="818" alt="Screenshot 2024-09-30 at 22 41 31" src="https://github.com/user-attachments/assets/5fea0b8e-6dde-46f7-84c2-3ab440d508bb">

And the dashboard:

<img width="1432" alt="Screenshot 2024-09-30 at 22 20 35" src="https://github.com/user-attachments/assets/109b66a1-aaaf-466c-8028-06d2a2f5b5f8">

The 2 tests can also be seen in Google Kubernetes Engine chart below:

<img width="801" alt="Screenshot 2024-09-30 at 22 32 37" src="https://github.com/user-attachments/assets/6fc6a158-3a24-4750-8495-c8480304adff">

So it is close to 4 times the single query time, what do you think might be causing it? 

I recently did an experiment with a concurrent ingestion of multiple parquets, each parquet took around 8 seconds and when ingesting multiple at the same time, it did parallelize well.

But I also notice that if I pass a greater number of queries, for example 100, only 13 appears when I look at system.processes. Is there a limit of concurrency? 

**Expected performance**
I would expect that running 4 queries concurrently would take the same time as 1 if the CPU limit was not reached

**Comment by Algunenano** [comment]
You are assuming the bottleneck is the CPU, which is not necessarily true. Without knowing the query and what the bottleneck is it's impossible to know why 4 concurrent queries take 3x more than 1 standalone query by itself.

You can check disk / network usage and queries ProfileEvents to try to get more information about what's going on

**Comment by gabrielmcg44** [comment]
Checking ProfileEvents I got:

<img width="722" alt="Screenshot 2024-10-01 at 09 16 42" src="https://github.com/user-attachments/assets/378da6f5-63a3-4e0a-9912-df9e69222a16">

Summing the systemCPU and userCPU times for standalone (130 + 12) I got 142. Dividing it by 3 seconds (time it took) it looks like it is using around 47 CPUs (for some reason it does not appear on the dashboards). Which actually matches what I got with

SHOW SETTINGS LIKE 'max_threads'; 

Which shows 48 (which is odd since the server machine has 90 CPUs)

Does it make sense to sum systemCPU and userCPU? Do you think CPU can still not be the bottleneck?

About disk / network. The metrics seems low:

<img width="717" alt="Screenshot 2024-10-01 at 09 30 33" src="https://github.com/user-attachments/assets/02f318fd-4259-43e7-b5b9-88bdbee78747">
<img width="715" alt="Screenshot 2024-10-01 at 09 30 40" src="https://github.com/user-attachments/assets/b07795bc-4beb-46c4-b88d-0310670ed7c3">

**Comment by gabrielmcg44** [comment]
Actually, it did hit the bound, only now I understood that these charts round per minute. So when rounding per second, I could see it hitting 90 CPU. Thank you for the hints!

<img width="1428" alt="Screenshot 2024-10-01 at 09 44 18" src="https://github.com/user-attachments/assets/01400d0a-27f5-4a0b-b43c-7cca30f5552c">
