### ISSUE TITLE
LOGICAL_ERROR: Table expression {} data must be initialized.

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/ClickHouse#70177]
https://s3.amazonaws.com/clickhouse-test-reports/70127/a7eb7a9208cd9a471cc2f6a363636ac53fc7bfa9/ast_fuzzer__msan_.html

Repro:

```sql
SELECT count()
FROM format(TSVRaw, (
    SELECT CAST(arrayStringConcat(groupArray('some long string'), '\n'), 'LowCardinality(String)')
    FROM numbers(10000)
    PREWHERE where_qualified__fuzz_19
))
FORMAT TSVRaw
```

It's an invalid query. In the old analyzer it throws `UNKNOWN_IDENTIFIER`

**Comment by al13n321** [comment]
Another query with the same error, but maybe different cause:
```sql
WITH a AS (SELECT 1) SELECT a.* FROM (SELECT 1 FROM a);
```

**Comment by novikd** [comment]
Duplicate of #69343
