### ISSUE TITLE
If a command-line argument has no value, and it is a setting with Bool type, assume it has value true.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#70291]
```
clickhouse-client --optimize_aggregation_in_order --query "SELECT ..."
```

**Comment by davidtsuk** [comment]
Hi, I'd like to work on this issue

**Comment by alexey-milovidov** [comment]
@davidtsuk, this is amazing, looking forward to seeing a pull request!

**Comment by davidtsuk** [comment]
I have a quick question, should this apply only to settings specified in [Settings.cpp](https://github.com/ClickHouse/ClickHouse/blob/8e5781e68b226debdb1c624d9b8ca7125cec6b28/src/Core/Settings.cpp#L54) or should settings such as `--highlight` also behave this way?

**Comment by alexey-milovidov** [comment]
In the scope of this task it is enough to only apply to settings from Settings.cpp.
