### ISSUE TITLE
Unsaved Queries on Cloud Console are Lost Across Browsers; Suggest Auto-Save on Logout or Instance Stop

### ISSUE THREAD

**Issue by 10manjunath** [ClickHouse/ClickHouse#70302]
**Title**: Unsaved Queries Are Lost Across Browsers in ClickHouse Cloud; Suggest Auto-Save on Logout or Instance Stop

**Description**:
I was working in the **[ClickHouse Cloud SQL Console](https://console.clickhouse.cloud)** on **Google Chrome**. After running a query, I forgot to save it. I stopped the instance and logged out. Later, I logged back into my ClickHouse Cloud using **Google Chrome** and restarted the instance; I noticed that my unsaved query was still present in the SQL Console.

However, when I logged into my ClickHouse Cloud from **Firefox**, the same unsaved query was missing.

This suggests that unsaved queries are stored in **browser-specific local storage** rather than being persisted server-side. As a result, the queries are only available in the original browser where they were created, causing data loss when switching between browsers or devices.

### Steps to Reproduce:
1. Open the ClickHouse Cloud SQL Console in **Google Chrome**.
2. Write and execute a query without saving it.
3. Stop the instance and log out of ClickHouse Cloud.
4. Log back into ClickHouse Cloud using **Google Chrome** and restart the instance: the unsaved query is still present.
5. Log into ClickHouse Cloud using **Firefox**: the unsaved query is missing.

### Expected Behavior:
Unsaved queries should either:
1. Be persisted on the server-side or within the user account session, allowing them to be accessible across different browsers and devices.
2. Provide a clear indication that unsaved queries are stored only locally in the browser and will not persist across sessions or browsers.
3. **Automatically save all unsaved queries when logging out or stopping the instance**, ensuring no data is lost.

### Actual Behavior:
Unsaved queries are stored only in the **local browser’s storage** (likely **local storage**), making them unavailable when switching to another browser (e.g., Firefox) or device.

### Environment:
- **Browsers**: Google Chrome, Firefox
- **ClickHouse Cloud**
- **OS**: Mac

It would be helpful if the SQL Console could either synchronize unsaved queries to the backend or provide a clearer warning that they are stored locally and not accessible in other browsers. Alternatively, it would be useful to automatically **save all unsaved queries upon logout or stopping the instance**. Also, Where is the source code for loading the saved query scripts into upon cloud instance initialization?

**Comment by ArctypeZach** [comment]
Hey @10manjunath! 

We're working towards this, albeit from a slightly different angle.  Soon, we'll have autosave everything in the SQL console (similar behavior to GDocs), but there are a still a couple of pre-requisites that we need to complete.

SQL console is also maintained independently from ClickHouseDB in a private repo, so I'm going to go ahead and close this issue, but I've flagged your feedback for our team.  If you'd like to discuss further, please shoot me an email: zach at clickhouse dot com.
