### ISSUE TITLE
String vs Array(UInt8) for storing binary data

### ISSUE THREAD

**Issue by Kirillstrelbitskiy** [ClickHouse/ClickHouse#70375]
### Question

I want to store binary data of varying size and try to understand the differences between using
- `String`
- `Array(UInt8)`

for this purpose. I don't need to do per-byte manipulations. 
Are there any significant optimizations or drawbacks for each option?

**Comment by Algunenano** [comment]
In general I don't think there are any major differences except on supported functions. There might be some small optimisations that are only specialised for strings because they are more common, but I wouldn't expect it to have any impact for you if you are not doing much with the data.
