### ISSUE TITLE
Querying Materialized View and underlying ReplicatedSummingMergeTree returns slightly different results

### ISSUE THREAD

**Issue by saraiva132** [ClickHouse/ClickHouse#70417]
**Company or project name**

I am running a simple summing merge tree project with reasonably high-volume (50M rows/day after merging) aggregating on 1 min and a MV that aggregates on a 15 min resolution (6M rows/day)

**Describe the unexpected behaviour**

The aggregated data in the historical data MV is not the same as the source table. There is a slight % difference. Often around 0-1% but we found a particular day where it was around 20/30% one time, that lasted for a few hours.

**How to reproduce. Table DDL**

```
#Local table
CREATE TABLE IF NOT EXISTS historical_data_local ON CLUSTER '{cluster}'
(
    id        Int32,
    timestamp         DateTime('UTC'),
    size              UInt64,
    count             UInt64,
    labels            Map(LowCardinality(String), String)
    ) ENGINE =  ReplicatedSummingMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}',
                                           '{replica}',(size, count))
    PRIMARY KEY (id, toStartOfMinute(timestamp))
    ORDER BY (id,  toStartOfMinute(timestamp), labels)
    PARTITION BY toYYYYMMDD(timestamp)
    TTL timestamp + interval 31 DAY;

#Distributed table
CREATE TABLE IF NOT EXISTS historical_data
    ON CLUSTER '{cluster}' AS historical_data_local
    ENGINE = Distributed('{cluster}', default, historical_data_local, farmHash64(id));

# MV Local table
create table fast_historical_data_local on cluster '{cluster}'
(
    id Int32,
    timestamp DateTime('UTC'),
    labels Map(LowCardinality(String), String),
    size SimpleAggregateFunction(sum, UInt64)
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}-2', '{replica}')
    PRIMARY KEY (id, timestamp)
    ORDER BY (id, timestamp, labels)
    PARTITION BY toYYYYMMDD(timestamp)
    TTL timestamp + INTERVAL 12 MONTH;
  
# MV distributed table    
CREATE TABLE fast_historical_data on cluster '{cluster}' as fast_historical_data_local
    ENGINE = Distributed('{cluster}', 'default', 'fast_historical_data_local', farmHash64(id)); 

# MV. Aggregates values on 15 min. Source table has 1 min granularity
CREATE MATERIALIZED VIEW historical_data_mv
    ON CLUSTER '{cluster}'
    TO fast_historical_data_local
AS
SELECT
    du.id,
    toStartOfInterval(du.timestamp, INTERVAL 15 MINUTE) as timestamp,
    mapSort(du.labels) as labels,
    sumSimpleState(du.size) as size
FROM historical_data_local du
GROUP BY timestamp,
    du.id,
    labels
ORDER BY du.id, timestamp;       
```

**Expected behavior**
I was expecting 100% match between MV aggregations and source table.

**Issue example. Concrete query and values**

I am querying reasonably old data.

Read from source data distributed table
```
SELECT date, formatReadableSize(sum(size) as size)
                            FROM historical_data
                            WHERE timestamp >= parseDateTimeBestEffort('30/09/2024 00:00:00', 'UTC') AND
                                  timestamp < parseDateTimeBestEffort('01/10/2024 00:00:00', 'UTC') AND
                                  id = 123456
                            GROUP BY toStartOfDay(timestamp) as date
                            ORDER BY date DESC;
```
<img width="563" alt="image" src="https://github.com/user-attachments/assets/b29dd5de-ed3b-424c-9770-766b84fb1db5">
```

Read from MV distributed table
```
SELECT date, formatReadableSize(sum(size) as size)
                            FROM fast_historical_data
                            WHERE timestamp >= parseDateTimeBestEffort('30/09/2024 00:00:00', 'UTC') AND
                                  timestamp < parseDateTimeBestEffort('01/10/2024 00:00:00', 'UTC') AND
                                  id = 123456
                            GROUP BY toStartOfDay(timestamp) as date
                            ORDER BY date DESC;
```
<img width="638" alt="image" src="https://github.com/user-attachments/assets/b65b4310-62ea-4686-9551-ca6b1847574d">


Any advice?

**Comment by den-crane** [comment]
Clickhouse does not guarantee consistency between a MatView and a source table, first of all because of lack of transactions and insert atomicity.
You need to implement re-tryable and repetable insertion.

see https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication
_Data blocks are deduplicated. For multiple writes of the same data block (data blocks of the same size containing the same rows in the same order), the block is only written once. The reason for this is in case of network failures when the client application does not know if the data was written to the DB, so the INSERT query can simply be repeated. It does not matter which replica INSERTs were sent to with identical data. INSERTs are idempotent. Deduplication parameters are controlled by [merge_tree](https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#merge_tree) server settings._

So if the first insert failed to insert into MatView the next re-try will be omitted for the source table but populate MatView.

**Comment by saraiva132** [comment]
Thanks for the quick reply @den-crane ! I did have the impression clickhouse inserts were not atomic. I am not too experienced with it yet. 

> You need to implement re-tryable and repetable insertion.
It is not too clear to me what I need to do exactly to achieve this. Are both achievable by tweaking the server settings ?

I reckon repeatable insertions is based on tweaking the `Deduplication parameter` ?

**Comment by den-crane** [comment]
By default, insert de-duplication is enabled for Replicated tables.

What Clickhouse version do you use? Recently MaterializedView dedup was completely re-implemented 

https://github.com/ClickHouse/ClickHouse/pull/66144

https://github.com/ClickHouse/clickhouse-docs/pull/2394/files

**Comment by saraiva132** [comment]
I am currently using version `23.4.2.11`

What about implementing re-tryable ?

**Comment by den-crane** [comment]
Can you please share the output of `select timezone()`.

>I am currently using version 23.4.2.11

too old. it's out of support.

>What about implementing re-tryable ?

it's not about re-tryable, it's about how insert deduplication works. It's your responsibility to implement proper retries.

>EDIT: Got it, it is using insert_deduplication_token

insert_deduplication_token brings nothing by itself, insert deduplication work with and without  insert_deduplication_token.

>I am not sure if this is really the way to go because we are capturing and logging client errors and I see none. I thought this would be an internal mechanism in CH

You need to investigate it by yourself. Insert deduplication / failed insert is only one possible cause. Try to drill down and compare what is missing in MV.

**Comment by saraiva132** [comment]
> Can you please share the output of select timezone().

UTC

> too old. it's out of support.

👍 

>You need to investigate it by yourself. Insert deduplication / failed insert is only one possible cause. Try to drill down and compare what is missing in MV.

Yeah I have trying to understand but it seems quite arbitrary :( 

Do you mind explaining why, in the case the insert is successful but the MV propagation is not, why would the client receive an error ? I assumed the client to INSERT only in the source table and the MV propagation to happen asynchronously.

**Comment by saraiva132** [comment]
Updating version to `24.9.2.42` fixed this issue
