### ISSUE TITLE
Decimal rounding uses different rounding mode

### ISSUE THREAD

**Issue by SergeyMirvoda** [ClickHouse/ClickHouse#7044]
**Describe the bug or unexpected behaviour**
This [help page](https://clickhouse.yandex/docs/en/query_language/functions/rounding_functions/#rounding_functions-round) precisely states that round function uses Banker's rounding.
But this statement doesn't holds for decimal type. We believe (did not checked the sources), that decimal rounding uses IEEE 754 away from zero mode.

**How to reproduce**
* Which ClickHouse server version to use
19.11.3.11

* Which interface to use, if matters
doesn't matter (SQL query in DataGrip)
* Non-default settings, if any
no
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/yandex/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result
![изображение](https://user-images.githubusercontent.com/286948/65387064-ae268300-dd5c-11e9-8501-4cc80beb38a4.png)
```sql
select 3.5 as v, round(toDecimal32(v,2)) as round_dec, round(v) as round_float
    union all
select 2.5 as v, round(toDecimal32(v,2)), round(v)
    union all
select 1.5 as v, round(toDecimal32(v,2)), round(v)
    union all
select 0.5 as v, round(toDecimal32(v,2)), round(v)
union all
select -0.5 as v, round(toDecimal32(v,2)), round(v)
order by 1 descending
```

**Expected behavior**
Actually the decimal behavior is what we need, we only want to sure is it bug in documentation or bug in decimal code?

**Additional context**
Is it good to have two different rounding schemes?
Can we have some arguments in `round` function?  
see also #1211

**Comment by den-crane** [comment]
not a bug, but a documentation issue:

> Denny Crane (I don't work at Yandex (never did)), [Sep 20, 2019 at 9:38:35 AM]:
> decimal-ы и float-ы округляются (round) по разному, первый математически, второй по-банковски
> отразить в доке или создать bug на decimal ?
> 
> Alexey Milovidov, [Sep 20, 2019 at 10:11:17 AM]:
> В документацию. (Ещё то же самое для int-ов).


https://t.me/c/1425947904/2922

**Comment by SergeyMirvoda** [comment]
Отлично!
