### ISSUE TITLE
Can't connect to Clickhouse cloud through MySQL Connector

### ISSUE THREAD

**Issue by conork92** [ClickHouse/ClickHouse#70443]
**Company or project name**

BGL

**Describe the unexpected behaviour**
We can no longer connect to Tableau through either of our instances, it was working fine a couple of weeks ago then unexpectedly stopped 

**How to reproduce**
* Which ClickHouse server version to use: Version 24.6
* Which interface to use, if matters: Tableau 2024.2 MySQL Connector

**Expected behavior**
The MySQL connector does not work for either of our instance despite it working a few weeks ago,
The clickhouse connector and ClickHouse JDBC by Analytika plus both work so it doesn't seem to be a user issue
We need to use the MySQL one as we have to publish the source to tableau cloud

**Error message and/or stacktrace**
<img width="492" alt="Screenshot 2024-10-07 at 11 50 43 AM" src="https://github.com/user-attachments/assets/3337f47e-bba2-474c-a65e-7a289960909c">

**Additional context**
- Using a user with mysql4 prefix
- Using port: 3306
- Using  the isrgrootx1.pem recommended here: https://clickhouse.com/docs/en/integrations/tableau-online#connecting-tableau-online-to-clickhouse-cloud-or-on-premise-setup-with-ssl

**Comment by incfly** [comment]
We troubleshoot and fixed it. and in case anyone else find they hitting the similar issue:

you need to create mysql user with double sha1 hash for password rather than sha256.

**Comment by andrewzolotukhin** [comment]
Hi all! We're still Having the same error message for Tableau Cloud when trying to connect to Clickhouse Cloude via MySQL interface.
Our Clickhouse Cloude instance is running Clickhouse v. 24.10 and I'm able to connect to it via CLI mysql client from my computer.
The user was created like:
```sql
CREATE USER mysql4cekwjssond_tableau IDENTIFIED WITH double_sha1_password BY 'qwerty123';
GRANT SELECT ON some_database.some_table TO mysql4cekwjssond_tableau;
```

Maybe there are any additional steps required to fix that?

**Comment by conork92** [comment]
@andrewzolotukhin I think it was the type of password hash in the end that was the issue was the password type try sha256_password and see if that works,

I think mysql doesn't support sha1 decryption

**Comment by andrewzolotukhin** [comment]
Hi @conork92 , unfortunately it didn't help. The error is still the same:
```
Can’t connect to MySQL
Detailed Error Message
[MySQL][ODBC 8.0(w) Driver]Lost connection to MySQL server at 'reading authorization packet', system error: 0
```

I created user like:
```sql
CREATE USER mysql4cekwjssond_tableau2 IDENTIFIED WITH SHA256_PASSWORD BY 'qwerty123';
GRANT SELECT ON some_database.some_table TO mysql4cekwjssond_tableau2;
```

After that I can't log in even with `mysql` CLI client:
```
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading final connect information', system error: 0
```

**Comment by conork92** [comment]
So I double checked and it was  double_sha1_password we used, Are you also using the isrgrootx1.pem file, As think the password was the only thing casusing this issue. We also have to build the tables in Tableau desktop and publish them to clickhouse cloud rather than starting the connection from the cloud.

There does seem to be new support for Clickhouse through bridge support but we haven't been able to find any guides on how to set this up, please let us know if you have any luck with that:
https://www.tableau.com/products/new-features#item-103261
