### ISSUE TITLE
Increased Memory Consumption after Updating from 24.5. to 24.8

### ISSUE THREAD

**Issue by CodingDoni** [ClickHouse/ClickHouse#70447]
Hey there :) We recently upgraded from ClickHouse version 24.5 to 24.8, and now some of our queries have significantly higher memory consumption, causing some of them to fail due to exceeding available memory.
            

`INSERT INTO tmp.T_ReviewNgram
            WITH
                ReviewSubset as (
                    SELECT *    
                    FROM dwhbil.T_ReviewsTopicSentiment trsr
                    WHERE
                        A_Id = %(a_id)s
                        AND AE_ID = %(ae_id)s
                        AND trsr.ReviewTimestamp >= COALESCE((SELECT DateFrom FROM dwhcor.T_ATimePeriod WHERE A_Id = %(a_id)s AND AE_ID = %(ae_id)s), fromUnixTimestamp(0))
                 )
            select
                ReviewSubset.*,
                tr.PosType,
                tr.NgramLevel,
                arrayFilter(x -> NOT match(x, '^[ㅤ%%\$=\-#\?\+\(\)\[\]|\+,:\.!\\n ]+$'), arrayMap(x -> lower(x), tr.Ngram)) AS Ngram,
                arrayFilter(x -> NOT match(x, '^[ㅤ%%\$=\-#\?\+\(\)\[\]|\+,:\.!\\n ]+$'), arrayMap(x -> lower(x), tr.NgramToken)) AS NgramToken
            FROM
            (
                SELECT
                    ReviewId,
                    UpdateTimestamp,
                    SourceId,
                    TranslationLanguage,
                    PosType,
                    Ngram,
                    NgramToken,
                    NgramLevel
                FROM dwhraw.T_ReviewNgrams
                ARRAY JOIN [Ngram1,Ngram2,Ngram3] as Ngram, [NgramToken1,NgramToken2,NgramToken3] as NgramToken, arrayEnumerate([1,2,3]) as NgramLevel
                WHERE
                    ReviewId IN (SELECT ReviewId from ReviewSubset)
                    AND length(Ngram1) > 0 AND length(Ngram) > 0
            ) tr
            INNER JOIN ReviewSubset rs using(ReviewId, UpdateTimestamp,SourceId,TranslationLanguage)
            WHERE length(Ngram) > 0
                AND rs.AE_ID IN (SELECT AE_ID FROM dwhcor.T_AE WHERE AEType='Local')`

This is one of the queries that are failing due to high memory consumption. When we downgrade back to version 24.5, we observe that during the execution of these queries, our server (with 128GB of RAM) uses a maximum of approximately 80GB. We cannot explain this behavior; however, we noticed that some users have reported similar issues:
:link: [GitHub Issue #69435](https://github.com/ClickHouse/ClickHouse/issues/69435)
We also saw that in the newest version, 24.9, an improvement has been deployed that reduces memory consumption when squashing data. We tried running this query on version 24.9, but we encountered the same memory issues as with 24.8.
These are our settings:
        <default>
            <max_query_size>10000000</max_query_size>
            <output_format_json_quote_64bit_integers>0</output_format_json_quote_64bit_integers>
            <allow_experimental_object_type>1</allow_experimental_object_type>
            <allow_experimental_inverted_index>1</allow_experimental_inverted_index>
            <output_format_parquet_string_as_string>1</output_format_parquet_string_as_string>
            <allow_experimental_annoy_index>1</allow_experimental_annoy_index>
            <allow_experimental_analyzer>0</allow_experimental_analyzer>
            <log_formatted_queries>1</log_formatted_queries>
        </default>

Is there anything that i am missing with the new updates that i need to configure?

**Comment by alexkowsik** [comment]
+1

**Comment by antonio2368** [comment]
With 24.8+ version you can run:
```
SYSTEM JEMALLOC ENABLE PROFILE
```
Start the query and when the memory usage is high while the query is running you can run:
```
SYSTEM JEMALLOC FLUSH PROFILE
```
It will generate a profile in `/tmp/jemalloc_clickhouse._pid_._seqnum_.heap`. You can send the profile for analyzing.
