### ISSUE TITLE
Why does the query's progress show with a big lag if I use skip indexes?

### ISSUE THREAD

**Issue by vmarkovtsev** [ClickHouse/ClickHouse#7046]
I've got a table with 24 billion rows, 500GB. I add a "bloom_filter()" index to a string column, say, `value`. Then I run `select count(*) from my_table where value='whatever';`. My index is used, however, the nice progress bar in `clickhouse-client` appears ~20 seconds after launching the query. In detail,

1. I type `select count(*) from my_table where value='whatever';` and press Enter.
2. I see 
```
SELECT count(*)
FROM my_table
WHERE value = 'whatever'
```
3. Nothing happens for ~20 seconds.
4. I see the progress bar
```
┌─count()─┐
│  504380 │
└─────────┘

1 rows in set. Elapsed: 25.288 sec. Processed 344.33 million rows, 6.57 GB (13.62 million rows/s., 259.85 MB/s.)
```

So the progress bar increments for ~5 seconds.

The second run took me 21 seconds, the third and all the subsequent runs - 19 seconds.

The same query without the index takes ~40 seconds, and the progress bar shows immediately.

Hence my questions are:

1. Is it normal to see the progress bar with such a delay?
2. What is happening under the hood during the first 20 seconds?
3. If that is the time to load the index into memory or something similar, can I speed it up?

**Comment by alexey-milovidov** [comment]
Most likely the index is analyzed slowly and we have potential for improvement.

**Comment by zhang2014** [comment]
Because current index scans are single-thread, they are very efficient on indexes like `minmax`, but slow on row-level indexes like `bloomfilter`.

BTW: the progress information is built after the index scan.

**Comment by blinkov** [comment]
@vmarkovtsev, do you have any further questions?

**Comment by vmarkovtsev** [comment]
Sorry :)
