### ISSUE TITLE
 Clickhouse cannot access the HDFS cluster with  kerberos

### ISSUE THREAD

**Issue by ASiegeLion** [ClickHouse/ClickHouse#70469]
### Question

I rewrote    ./src/IO/examples/read_buffer_from_hdfs.cpp , add  kerberos conf.
![image](https://github.com/user-attachments/assets/7d102e97-8f26-44fa-97d5-dff4ca047f50)
Executing read_buffer_from_hdfs.cpp throws the following exception
![image](https://github.com/user-attachments/assets/5083376d-936a-4d93-bdc0-efe3c7734a67)

hadoop version: 3.1.1
hadoop SecurityAuth.audit  log ：
![image](https://github.com/user-attachments/assets/0fa7230f-e960-44b5-a3b3-ff115c550ddc)

**Comment by den-crane** [comment]
AFAIK ClickHouse does not support kerberos with HDFS and have no plans to support it. https://github.com/ClickHouse/ClickHouse/issues/56152#issuecomment-2080325741

https://github.com/ClickHouse/ClickHouse/issues?q=is%3Aissue+hdfs++kerberos+is%3Aclosed
