### ISSUE TITLE
Force ignore the free space check in OPTIMIZE TABLE

### ISSUE THREAD

**Issue by vmarkovtsev** [ClickHouse/ClickHouse#7047]
**Use case**
I've got a 500GB table on a 1.5TB volume. It has 20 partitions. I ran `OPTIMIZE TABLE my_table;` and it returned immediately, doing nothing. I looked at the server logs and saw
```
2019.09.22 12:23:45.806477 [ 46 ] {1cc990c7-d63c-4083-9484-b65c7d02b223} <Warning> default.my_table (MergerMutator): Won't merge parts from all_1_1731343_30_13288166 to all_13288146_13288161_4_13288166 because not enough free space: 963.64 GiB free and unreserved (0.00 B reserved in 0 chunks), 512.15 GiB required now (+100% on overhead); suppressing similar warnings for the next hour
```
I know that the merge op needs exactly 2x of the space occupied (I tried with smaller DB sizes and monitored `df`), so it is perfectly safe for me to execute it.

**Describe the solution you'd like**
Add a configuration option to disable the hardcoded `+100% overhead` check - at least, temporarily. Something like "I've been warned and I know what I am doing, please OPTIMIZE you coward".

**Describe alternatives you've considered**
Add a configuration option to point to an extra volume to be used during the merge.

**Comment by alexey-milovidov** [comment]
Ok.

JFYI, let me explain why it requires 2x reservation.
It's not the reservation for the single merge operation.
It's needed to allow other merges to run. For example, first merge will eat 1/2 of free space. Then we can run second merge and it will be able to eat 1/4 of free space. Third merge will be able to eat 1/8 of free space and so forth. So, one big merge will not prevent smaller merges to run.

**Comment by alexey-milovidov** [comment]
Looks trivial to fix. Just move `DISK_USAGE_COEFFICIENT_TO_SELECT` to `MergeTreeSettings`.

**Comment by alexey-milovidov** [comment]
This task is trivial to implement.

**Comment by alexey-milovidov** [comment]
This task is trivial but no one is interested.
