### ISSUE TITLE
24.8 LTS some bugs

### ISSUE THREAD

**Issue by Ivan-Dyncan** [ClickHouse/ClickHouse#70486]
Hi, i found few bugs

1. Not working
SELECT arrayMin(x -> (-x), [1, 2, 4]) AS res 

2. group by doesnt group 
I cant write script, based on random data, so show only screanshot
![image](https://github.com/user-attachments/assets/3301da6e-46c2-416c-b222-b170aa867b80)

3. using in in multiIf throw error
Also couldn't repeat it on raw data
![image](https://github.com/user-attachments/assets/9b8f2b06-7133-4139-8074-79b55c5cbda9)

I suspect the problem may be with my clickhouse settings, because the problem does not repeat on raw data

**Comment by den-crane** [comment]
duplicate 
* https://github.com/ClickHouse/ClickHouse/issues/69600

fixed in master https://fiddle.clickhouse.com/fa3a5442-b24b-4f80-8dcd-55e0ed0181da

**Comment by den-crane** [comment]
>using in in multiIf throw error

you have 2 different versions of Clickhouse? use `allow_experimental_analyzer=0;` or upgrade all Clickhouse nodes to 24.8

**Comment by Algunenano** [comment]
> fixed in master https://fiddle.clickhouse.com/fa3a5442-b24b-4f80-8dcd-55e0ed0181da

It's also backported and there is already a patch release of 24.8 with the fix ([v24.8.5.115-lts](https://github.com/ClickHouse/ClickHouse/releases/tag/v24.8.5.115-lts)).

**Comment by max-vostrikov** [comment]
@Ivan-Dyncan for the future issues, it is better to create separate tickets for separate issues.

About the second one `group by doesnt group`. It doesn't look right, but I can't reproducible on some random data.
Can you provide some additional info on this problem?
What is the definition of your table?
Can you provide example of the data, or the queries to generate it?

I assume there could be several cases when GROUP BY gives several groups - it could converted from different types for example. Can you provide reproduction scenario using [fiddle](https://fiddle.clickhouse.com/51470c2c-aeab-4761-9808-477df311dcc0)?

**Comment by Ivan-Dyncan** [comment]
> What is the definition of your table?
Can you provide example of the data, or the queries to generate it?

Unfortunately i dont know that details(

> Can you provide reproduction scenario using [fiddle](https://fiddle.clickhouse.com/51470c2c-aeab-4761-9808-477df311dcc0)?

I tried and it didn't work, so, i hope, this bug will be autofixed when we update ch
