### ISSUE TITLE
Cyclic query when experimental analyzer disabled

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#70507]
**Describe the bug**
A "cyclic aliases" is thrown when the experimental analyzer is disabled.

**How to reproduce**
Run this Fiddle:
https://fiddle.clickhouse.com/1eab320b-c5cf-4928-b78c-7636ed114e2e

**Comment by Algunenano** [comment]
No plans to change how the old analyzer resolves aliases (it's one of the reason why the new analyzer was introduced)
