### ISSUE TITLE
Exception deducing Object('json') type from remote table function

### ISSUE THREAD

**Issue by RinSer** [ClickHouse/ClickHouse#70525]
Hi!
I am facing an issue trying to select data from remote server table using the `remote` table function:
```
Code: 717. DB::Exception: Least common type for object can be deduced only from tuples, but Object('json') given. (EXPERIMENTAL_FEATURE_ERROR) (version 24.3.11.7 (official build))
```
The exception raises only for tables with `Object('json')` deprecated data type columns.
I have tried to use setting `allow_experimental_object_type=1`, but it did not help.
Is it possible to fix this error without data type change?

**Comment by Avogar** [comment]
I am not sure it's a compatibility issue. This exception comes from the implementation of `Object` column and means that we didn't finalize `ColumnObject` I believe. Let's ask @CurtizJ.
If it's a bug in the implementation, it won't be fixed as the type is deprecated

**Comment by RinSer** [comment]
@CurtizJ, hi!
Could you please clarify this issue? Is it possible to fix it?
