### ISSUE TITLE
 Attempted access has violated the permissions assigned to the memory area.

### ISSUE THREAD

**Issue by li-bit** [ClickHouse/ClickHouse#7053]
2019.09.23 17:17:07.263877 [ 24 ] {} <Error> BaseDaemon: ########################################
2019.09.23 17:17:07.263954 [ 24 ] {} <Error> BaseDaemon: (version 19.13.5.44 (official build)) (from thread 13) Received signal Segmentation fault (11).
2019.09.23 17:17:07.263985 [ 24 ] {} <Error> BaseDaemon: Address: 0x7faf9cbfb000 Access: read. Attempted access has violated the permissions assigned to the memory area.
2019.09.23 17:17:07.319933 [ 24 ] {} <Error> BaseDaemon: 0. clickhouse-server(StackTrace::StackTrace(ucontext_t const&)+0x31) [0x7f169f1]
1. clickhouse-server() [0x3dafc5e]
2. /lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7fb0294c3330]
3. clickhouse-server(DB::GraphiteRollupSortedBlockInputStream::merge(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::priority_queue<DB::SortCursor, std::vector<DB::SortCursor, std::allocator<DB::SortCursor> >, std::less<DB::SortCursor> >&)+0xe6) [0x7346326]
4. clickhouse-server(DB::GraphiteRollupSortedBlockInputStream::readImpl()+0xeb) [0x7346f8b]
5. clickhouse-server(DB::IBlockInputStream::read()+0x187) [0x6c2cbe7]
6. clickhouse-server(DB::MergeTreeDataMergerMutator::mergePartsToTemporaryPart(DB::FutureMergedMutatedPart const&, DB::MergeListEntry&, DB::TableStructureReadLockHolder&, long, DB::DiskSpaceMonitor::Reservation*, bool)+0x238b) [0x7082fbb]
7. clickhouse-server(DB::StorageMergeTree::merge(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)+0x534) [0x6fb5b84]
8. clickhouse-server(DB::StorageMergeTree::backgroundTask()+0x195) [0x6fb9c55]
9. clickhouse-server(DB::BackgroundProcessingPool::threadFunction()+0x544) [0x703d874]
10. clickhouse-server() [0x703e1ea]
11. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1a6) [0x3c84a36]
12. clickhouse-server() [0xba5b6e0]
13. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7fb0294bb184]
14. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fb028cde03d]

**Comment by alesapin** [comment]
Can you provide any data/queries to reproduce the issue?
