### ISSUE TITLE
some part doesn't delete by TTL

### ISSUE THREAD

**Issue by qianniaoliu** [ClickHouse/ClickHouse#70566]
### Question

There is a part in system.parts that should have been removed in 2024-10 by TTL.
part_name - 17_0_14127_527_15525
delete_ttl_info_min - 2024-10-09 09:23:37.
In system.replication_queue I found:

num_postponed:          5318
postpone_reason:        Not executing log entry queue-0000433353 for part 17_0_14127_528_15525 because 2 merges with TTL already executing, maximum 2.

**Comment by den-crane** [comment]
Can you please share PARTITION BY and TTL sections of your table?

>entry queue-0000433353 for part 17_0_14127_528_15525 because 2 merges with TTL already executing, maximum 2.

It is defined by these merge_tree settings:

https://clickhouse.com/docs/en/operations/settings/merge-tree-settings
```
max_number_of_merges_with_ttl_in_pool                          │ 2       │       0 │ When there is more than specified number of merges with TTL entries in pool, do not assign new merge with TTL. This is to leave free threads for regular merges and avoid "Too many parts"

merge_with_ttl_timeout                                         │ 14400   │       0 │ Minimal time in seconds, when merge with delete TTL can be repeated.

select * from system.merge_tree_settings where name like '%ttl%';
```

you can do 

```xml
<merge_tree>
    <max_number_of_merges_with_ttl_in_pool>10</max_number_of_merges_with_ttl_in_pool>
</merge_tree>
```
