### ISSUE TITLE
Wrong query result for pagination queries

### ISSUE THREAD

**Issue by FrankChen021** [ClickHouse/ClickHouse#70580]
**Describe what's wrong**

When using `ORDER BY xxx LIMIT yyy OFFSET zzz` to do pagination queries, sometimes query returns same record in different pages.

**Does it reproduce on the most recent release?**

We found it on 23.3, but this can be reproduced on the master too.

**How to reproduce**

Here is the reproduciable link: https://fiddle.clickhouse.com/97924a7e-6293-4dc9-94e2-b3460d7cf0e8
and a step by step description is as follows:

1. First create a simple table

```sql
CREATE TABLE table (unique_id String, archive_days Int64) ENGINE=MergeTree order by unique_id;
```

2. Insert some data into this table. Note that for archive_days, there will be some same values for different `unique_id`. This is the key to reproduce this problem.

3. select first 50 records from the table 
```sql
   SELECT unique_id FROM table order by archive_days desc 
   limit 50 offset 0
```

4. select next 50 records from the table
```sql
   SELECT unique_id FROM table order by archive_days desc 
   limit 50
   offset 50 -- offset changes to 50 to skip the first 50 rows 
```

We can see that the result set in step 4 contains some result set in step 3. 

**Expected behavior**

Since the table contains unique values for each record, the query result in different pages MUST be different.

**Analysis**

The problem is due to the sorting and limit processing inside the `PartialSortingTransform`.
For `LIMIT 50 OFFSET 0` and `LIMIT 50 OFFSET 50`, the difference in query plan is shown as the following:
![image](https://github.com/user-attachments/assets/9ee28876-29c2-47d9-a8da-7fcffcfcde5d)

The query plan has no problem, for the latter one, it limits internal rows to 100 and then drop the first 50 rows. 
However, sorting result of `LIMIT 50` and `LIMIT 100` is different, which leads to this problem, we can see the difference from the following query.

```sql
   SELECT unique_id FROM table order by archive_days desc 
   limit 50 offset 0

   SELECT unique_id FROM table order by archive_days desc 
   limit 100 offset 0
```

By further investigation, the inconsistent sorting result is caused by 'Unstable' parameter passing to internal sorting, which was introduced by https://github.com/ClickHouse/ClickHouse/pull/50697

![image](https://github.com/user-attachments/assets/f6971de6-d76e-44fb-aceb-29a0e54addbc)

**How to fix**

The simplest way is to use Stable for sorting if limit is given. Let me know if you have any concerns @kitaisreal 

```cpp
void sortBlock(Block & block, const SortDescription & description, UInt64 limit)
{
    IColumn::Permutation permutation;
    getBlockSortPermutationImpl(block, description, limit ? IColumn::PermutationSortStability::Stable : IColumn::PermutationSortStability::Unstable, limit, permutation);
```

**Comment by alexey-milovidov** [comment]
SQL does not guarantee a deterministic ordering of the records with identical values of ORDER BY.
The behavior is legitimate.

You can add another column to ORDER BY as a workaround: `order by archive_days, unique_id`
