### ISSUE TITLE
Read data replica consistency

### ISSUE THREAD

**Issue by easymanlo** [ClickHouse/ClickHouse#70586]
### Question

The ClickHouse version is 21.9.3.30. Currently, when writing data, the write operation succeeds, but the data read is incomplete. We can only add the insert_quorum=2 parameter to wait until all replicas finish writing before reading the complete data. This approach is not ideal for our scenario. In the latest version of ClickHouse, how is this problem resolved? Specifically, how does the latest version ensure that after data is written, it can read complete data instead of reading from replicas that haven't finished syncing?

**Comment by den-crane** [comment]
Do you read from Replicated table or from Distributed 

Have you try select_sequential_consistency https://clickhouse.com/docs/en/integrations/postgresql/postgres-vs-clickhouse#sequential-consistency https://clickhouse.com/docs/en/operations/settings/settings#select_sequential_consistency

**Comment by easymanlo** [comment]
Thank you for your response. I will look into the two solutions you provided to see if they can address our issues. Currently, we are using the ReplicatedMergeTree table engine in a storage-compute integrated setup.
