### ISSUE TITLE
Allow base58Encode to take a FixedString(n) 

### ISSUE THREAD

**Issue by thesuzerain** [ClickHouse/ClickHouse#70594]
**Describe the issue**
A clear and concise description of what works not as it is supposed to.
There doesn't seem to be a concise way to go from UInt256 to a base58 encoded string, despite functions like `base58Encode` existing, due to reinterpretAsString and other similar functions dropping null bytes at the end.

**How to reproduce**

`base58Encode(reinterpretAsString(byteSwap(toUInt256('256')))) AS verfied_address`

I expect this to produce the string: `1111111111111111111111111111115R`, but it produces `1111111111111111111111111111112`.

This can be replicated for any UInt256 that doesn't satisfy `x % 256 == 0`. This is because the `reinterpretAsString` function drops the last null byte (which is documented). This is fine- the dropped byte is documented in `reinterpretAsString`, but this byte is very relevant for this use case and there doesn't seem to be a way to prevent it from doing so, or to fill it onto the end nicely.

Reinterpreting as a FixedString (or converting to one) does seem to work, but `base58Encode` does not allow a FixedString to be taken directly. Unfortunately, when we use `toString(...)` or `CAST(x as String)` on the FixedString, the byte gets dropped again.

. For example, while `reinterpret(byteSwap(toUInt256('256')), 'FixedString(32)'))` correctly shows a null byte at the end, doing `toString(...)` on that removes it. Similarly, some manual solutions to just `rightPad` with null bytes on the end still just end up removing the null bytes.

A correct solution I eventually found is: `base58Encode(unbin(bin(reinterpret(byteSwap(toUInt256('256')), 'FixedString(32)'))))`. `unbin(bin(...))` seems to be able to change from a FixedString to a String without losing the added-on null bytes, by going through binary, but converting to binary and back because the normal conversion intentionally drops information (and there not seeming to be a way to keep that information) feels very hacky and is an unintuitive workaround to allow string manipulation with null bytes. 

**Expected behavior**

Three possible ways to better resolve this would be:

- allow base58Encode to take a FixedString directly (in which it would include any ending null bytes as part of the string, which are relevant characters for base58 encoding). This would be consistent with `hex` encoding that is already supported by clickhouse.
- allow some way to reinterpretAsString without losing the terminating null bytes (either as a different function, or an optional field, etc)
- a way to convert from FixedString to String without losing the null byte (this behaviour surprised me, as the [documentation for FixedString](https://clickhouse.com/docs/en/sql-reference/data-types/fixedstring) did seem to imply the null byte was 'real', and [toString documentation](https://clickhouse.com/docs/en/sql-reference/functions/type-conversion-functions#tostring) does not mention removal of null bytes in the way reinterpretAsString does)

**Additional context**

Obviously this is a niche issue that has a workaround, so not very pressing. I would also be happy to take this up as a PR if one of the propposed solutions seems OK.

It's possible I just missed some niche String function that does some chunk of this process correctly, or does allow for conversion (or reinterpretation) in this manner with null bytes, but I couldn't find it. If so, my apologies. 

EDIT: I'm on Clickhouse version 24.5.3.5

**Comment by wxybear** [comment]
how about `select base58Encode(concat(reinterpretAsString(byteSwap(toUInt256('256'))), CHAR(0))) AS verfied_address`
https://fiddle.clickhouse.com/7a8ce28b-15f1-43e4-a032-13d5d2a16ecf
