### ISSUE TITLE
ClickHouse distributed JOIN vs common JOIN

### ISSUE THREAD

**Issue by wlzywang** [ClickHouse/ClickHouse#70599]
### Question

1. Set up

ClickHouse cluster with 2 shards, 1 replica on each shard
Local table testjoin on each replica
```
CREATE TABLE testjoin
(
    `user` String,
    `type` String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/testjoin', '{replica}')
PARTITION BY type
ORDER BY type
```
Distributed table testall
```
CREATE TABLE testall
(
    `user` String,
    `type` String
)
ENGINE = Distributed('cluster', 'default', 'testjoin', rand())
```
Shard 1 Replica 1 has the following data
SELECT *
FROM testjoin
┌─user──┬─type──┐
│ user1     │ type1     │
└─────┴──────┘
Shard 2 Replica 1 has the following data
SELECT *
FROM testjoin
┌─user──┬─type──┐
│ user1     │ type2 │
└──────┴─────┘

2. Query with INNER JOIN and GLOBAL INNER JOIN yields the same result. distributed_product_mode = 'allow' or  'local' or 'deny' makes no difference either. Is this expected behavior?

WITH
    t1 AS
    (
        SELECT *
        FROM testall
        WHERE type = 'type1'
    ),
    t2 AS
    (
        SELECT *
        FROM testall
        WHERE type = 'type2'
    )
SELECT *
FROM t1
INNER JOIN t2 ON t1.user = t2.user

┌─user──┬─type──┬─t2.user─┬─t2.type─┐
│ user1 │ type1 │ user1   │ type2   │
└───────┴───────┴─────────┴─────────┘

WITH
    t1 AS
    (
        SELECT *
        FROM testall
        WHERE type = 'type1'
    ),
    t2 AS
    (
        SELECT *
        FROM testall
        WHERE type = 'type2'
    )
SELECT *
FROM t1
GLOBAL INNER JOIN t2 ON t1.user = t2.user

┌─user──┬─type──┬─t2.user─┬─t2.type─┐
│ user1 │ type1 │ user1   │ type2   │
└───────┴───────┴─────────┴─────────┘

**Comment by alexey-milovidov** [comment]
When JOINing subqueries, including those from CTEs (rather than regular tables), JOIN is fully performed on the initiating node, and does not depend on the mode (local or global).

**Comment by wlzywang** [comment]
Hi Alexey-Milovidov

Even if I do not use WITH, the result is the same

```
SELECT *
FROM
(
    SELECT *
    FROM testall
    WHERE type = 'type1'
) AS t1
INNER JOIN
(
    SELECT *
    FROM testall
    WHERE type = 'type2'
) AS t2 ON t1.user = t2.user
```

┌─user──┬─type──┬─t2.user─┬─t2.type─┐
│ user1 │ type1 │ user1   │ type2   │
└───────┴───────┴─────────┴─────────┘
Could you please explain a bit more?

**Comment by wlzywang** [comment]
I see. Now I feel safe in my usage. Thank you for confirming, Alexey-Milovidov.
