### ISSUE TITLE
New Analyzer cannot identify properly alias of CTE expression in distributed query.

### ISSUE THREAD

**Issue by nadberezny** [ClickHouse/ClickHouse#70633]
**Company or project name**
dema.ai

**Describe what's wrong**
New Analyzer cannot identify properly alias of CTE expression, when alias is used in some aggregate function and distributed table with ReplicatedMergeTree is queried.

> A link to reproducer in [https://fiddle.clickhouse.com/](https://fiddle.clickhouse.com/).
N/A since it's impossible to create a ReplicatedMergeTreeTable

**Does it reproduce on the most recent release?**
yes

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)
ClickHouse 24.8.5.115
ClickHouse 24.10.1.1564

**How to reproduce**
-- 1. create RMT table
CREATE TABLE default.customers ON CLUSTER '{cluster}'(`customerId` String)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/default/customers', '{replica}')
ORDER BY customerId;

-- 2. create distributed table
CREATE TABLE default.customers_d on cluster '{cluster}' AS default.customers
ENGINE = Distributed('default','default','customers', cityHash64(customerId));

-- 3. query distributed table
WITH toUInt8(0) as "someValue"
SELECT groupUniqArray((customerId, "someValue"))
FROM default.customers_d
SETTINGS enable_analyzer = 1;

-- the result is DB:Exception
-- the same will happen when querying through cluster clause, ie. FROM ('my-cluster', default.customers)

* Which ClickHouse server version to use
24.8 or 24.10

**Error message and/or stacktrace**
```
 DB::Exception: Conversion from AggregateFunction(groupUniqArray, Tuple(String, UInt8)) to AggregateFunction(groupUniqArray, Tuple(customerId String, someValue UInt8)) is not supported: while converting source column `groupUniqArray(tuple(__table1.customerId, _CAST(0_UInt8, 'UInt8'_String)))` to destination column `groupUniqArray(tuple(__table1.customerId, _CAST(0_UInt8, 'UInt8'_String)))`. (CANNOT_CONVERT_TYPE) (version 24.10.1.1564 (official build))
```

**Comment by SaltTan** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/69732
