### ISSUE TITLE
clickhouse-keeper memory data size increase fast

### ISSUE THREAD

**Issue by ly123-liu** [ClickHouse/ClickHouse#70668]
**Describe the situation**
we use clickhouse + clickhouse keeper as log storage components, we have 6 clickhouse-server + 3 clickhouse-keeper , and we notice keeper memory data size increase fast , and keeper memory usage is getting higer, is this as expected or memory leak?

comparison with clickhouse-keeper and zookeeper, clickhouse-keeper znode and datasize is over two times more than zookeeper's:
- zookeeper : datasize is 150M, znode is 1000000+
- clickhouse keeper:  datasize is 900M+, znode is 2000000+

**How to reproduce**
we have 3 shards  and one replicated_server, there are 6k partitions. 
keeper memory data size is 900M+, memory usage up to 1.7G

* Which ClickHouse server version to use
clickhouse-server version: 24.8

clickhouse-keeper:
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/dba754f2-c50c-438b-ba73-628605a04d9b">

compare zookeeper:
<img width="995" alt="image" src="https://github.com/user-attachments/assets/b5bd3355-a922-4b5c-a2dc-ca1efbeaeda9">

clickhouse-server:
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/38419f79-1677-466e-b4ea-0246c8f0bc54">

**Comment by den-crane** [comment]
What do you mean by "memory data size"? Snapshot size? RSS? RES? VSS?

**Comment by ly123-liu** [comment]
keeper snapshot datasize is increase fast and not reach peak, as with znode count， keeper server memory rss up to 2G now, and still increase

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/98df3409-47b7-4ce3-b819-23d1a200f26d">
<img width="797" alt="image" src="https://github.com/user-attachments/assets/d0d3d9b3-a95b-48c0-ae66-bca3b07a26fa">


but we use zookeeper , snapshot datasize is 153MB
<img width="1003" alt="image" src="https://github.com/user-attachments/assets/01c1cfbc-67c4-49fe-8c17-539e4d117b0d">

is there something wrong with clickhouse-keeper ?

> What do you mean by "memory data size"? Snapshot size? RSS? RES? VSS?

**Comment by Algunenano** [comment]
In the first cluster you are constantly increasing znode count, so it's normal that snapshot size and memory usage increases. In the second one you aren't, so snapshot size doesn't grow. Memory size and snapshot size are proportional to znode count.

You should look into why the znode count is increasing

**Comment by ly123-liu** [comment]
> In the first cluster you are constantly increasing znode count, so it's normal that snapshot size and memory usage increases. In the second one you aren't, so snapshot size doesn't grow. Memory size and snapshot size are proportional to znode count.
> 
> You should look into why the znode count is increasing

this has resoved，too man queue node saved in keeper, clickhouse replicated server default use hostname to connect another server and cannot connect
