### ISSUE TITLE
ClickHouse Support Authenticate faillock

### ISSUE THREAD

**Issue by unknown-no** [ClickHouse/ClickHouse#70670]
**Use case**

To enhanced security, can ClickHouse support Authenticate faillock to prevent brute force attacks?

**Describe the solution you'd like**

Mybe we can bring [linux-pam](https://github.com/linux-pam/linux-pam) into ClickHouse

**Comment by alexey-milovidov** [comment]
See the `failed_sequential_authentications` quota.
