### ISSUE TITLE
Do not trigger the limit on number of rows to read if it's a trivial query with LIMIT.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7071]
```
milovidov-Pro-P30 :) SET max_rows_to_read = 1000000

SET max_rows_to_read = 1000000

Ok.

0 rows in set. Elapsed: 0.007 sec. 

milovidov-Pro-P30 :) SELECT number FROM numbers(1000000000) LIMIT 1

SELECT number
FROM numbers(1000000000)
LIMIT 1

→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.15.1):
Code: 158. DB::Exception: Received from localhost:9000. DB::Exception: Limit for rows to read exceeded: 1000000000 rows read (or to read), maximum: 1000000.
```

**Comment by alexey-milovidov** [comment]
It's not trivial. The table may require implicit filtering and will read more rows.
The only way is to analyze limit inside IStorage::read (for MergeTree and Numbers storages) and adapt the predicted number of rows to read.

**Comment by hanfei1991** [comment]
Some insights:

###Why this kind of query fails in advance?

before we actually run a query, we will compare the row limit and approx row number. It's not always accurate, especially for a simple `limit`-only query. We will overestimate the row number to read.

###How can we get accurate estimated row numbers?

Always being accurate is not possible, especially when **limit** meets **where**. But in this case, we can adjust the estimated when we find there is a simple `limit`-only query.

We need to add a `limit` field to `SelectQueryInfo` and set it iff the interperter finds it is a `limit-only` query. In the IStorage::read function we check the `limit` to ajust the approx total rows.

###What is the usage of estimated row numbers and what is the risk?

AFAIK, the estimation is only for restricting rows to read and showing the process, so adjusting it is not risky.

The only effect is making query_info more fat and making check logic more complex.

@KochetovNicolai PTAL

**Comment by KochetovNicolai** [comment]
Maybe we can do it in a very simple way?
If a query with trivial limit cannot contain where, prewhere, array join and other stuff, we can:
1. Check if `limit` < `max_rows_to_read`
2.  Just change [OwerflowMode](https://github.com/ClickHouse/ClickHouse/blob/984fe4f05889c60266acd1290d2644ebff7fee1e/src/QueryPipeline/SizeLimits.h#L13) from THROW to BREAK and newer throw `Limit for rows to read exceeded`.

If query has where or prewhere, it would be really very hard to limit well. Especially if we read from storage in-parallel (basically, it would not make sense).

**Comment by KochetovNicolai** [comment]
Another one funny implementation idea is to cut chunk up to `max_rows_to_read - read_rows` size instead of throwing `Limit for rows to read exceeded` exception. Then, put into pipeline this shorter chunk, and then exception. Exception will be re-thrown if more then `max_rows_to_read` are actually needed.

This idea is bad because:
* Still, does not make a lot of sense with parallel execution.
* Does not support prewhere
* Difficult to implement

**Comment by alexey-milovidov** [comment]
> If a query with trivial limit cannot contain where, prewhere, array join and other stuff, we can

Maybe this variant will also require checking for row policies?

> We need to add a limit field to SelectQueryInfo and set it iff the interperter finds it is a limit-only query. In the IStorage::read function we check the limit to ajust the approx total rows.

This is a good variant because the progress bar will be also adjusted.

**Comment by hanfei1991** [comment]
@KochetovNicolai I'm afraid this method cannot work out. There are two reasons:

1. When querying with MergeTree, we do size limit check at [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Storages/MergeTree/MergeTreeDataSelectExecutor.cpp#L1064), which set `overflow mode` by settings
2. Actually we append two "LocalLimits" in Interpreter. The first one is at [here](https://github.com/ClickHouse/ClickHouse/blob/master/src/Interpreters/InterpreterSelectWithUnionQuery.cpp#L287), which cannot be modified according to limit value.

The second point doesn't make sense to me. Why do we set limit check at this place? Is it redundant?

According to these two points, I think we can use my solution adding a field in query_info.
