### ISSUE TITLE
How to mount plain_rewritable as read-only ?

### ISSUE THREAD

**Issue by arnaudbriche** [ClickHouse/ClickHouse#70724]
### Company or project name

Agnostic

### Question

Hi,

I have a use-case where I want to put a mergetree on s3 with a single-writer and multiple-readers.
My question is : how to ensure a "reader" will not try to write (by merging) on the table.

Currently, reader (which have a read-only policy on s3) fail to attach the table because these try to issue delete object queries.

**Comment by alexey-milovidov** [comment]
You add the `readonly = true` to the disk configuration.
Example:

```
CREATE TABLE hackernews_history UUID '66491946-56e3-4790-a112-d2dc3963e68a'
(
    `update_time` DateTime DEFAULT now(),
    `id` UInt32,
    `deleted` UInt8,
    `type` Enum8('story' = 1, 'comment' = 2, 'poll' = 3, 'pollopt' = 4, 'job' = 5),
    `by` LowCardinality(String),
    `time` DateTime,
    `text` String,
    `dead` UInt8,
    `parent` UInt32,
    `poll` UInt32,
    `kids` Array(UInt32),
    `url` String,
    `score` Int32,
    `title` String,
    `parts` Array(UInt32),
    `descendants` Int32
)
ENGINE = ReplacingMergeTree(update_time)
ORDER BY id
SETTINGS disk = disk(readonly = true, type = 's3_plain_rewritable', endpoint = 'https://clicklake-test-2.s3.eu-central-1.amazonaws.com/', use_environment_credentials = false);
```

**Comment by alexey-milovidov** [comment]
Caveat: We have not finished working on this scenario. There are several limitations:

1. The reader does not update information about data parts of the table. As data parts are constantly merged and older data parts are deleted, it will stop being usable after `old_parts_lifetime` specified in the MergeTree table settings, default 8 minutes. For the example above, I set it to 24 hours on the writer side.
2. It does not refresh to see the new parts. I plan to add a background refresh method, but currently the only way is to re-attach the table, which also can take considerable time (seconds to minutes) for large tables.

**Comment by arnaudbriche** [comment]
Hi @alexey-milovidov ,

Thx a lot for the prompt answer. This is working perfectly.

Regarding the limitations you mentioned, they make sense and I came to infer them from the documented mergetree behaviour.
I have an open issue related to these limitations where I will point to your answer above.

Happy to hear that you are working on improving this.

**Comment by arnaudbriche** [comment]
> Caveat: We have not finished working on this scenario. There are several limitations:
> 
> 1. The reader does not update information about data parts of the table. As data parts are constantly merged and older data parts are deleted, it will stop being usable after `old_parts_lifetime` specified in the MergeTree table settings, default 8 minutes. For the example above, I set it to 24 hours on the writer side.
> 2. It does not refresh to see the new parts. I plan to add a background refresh method, but currently the only way is to re-attach the table, which also can take considerable time (seconds to minutes) for large tables.

Is there any ETA for 2. ? Would really be a game changer for use-cases like mine.

**Comment by alexey-milovidov** [comment]
No ETA because it's not planned. Currently, it's considered something to implement in spare time. The optimistic part is that I really want to do it :)
