### ISSUE TITLE
A hidden build error on Mac OSX 15

### ISSUE THREAD

**Issue by yl-lisen** [ClickHouse/ClickHouse#70726]
**Company or project name**

https://github.com/timeplus-io

**Operating system**

(macOS Sequoia 15.0.1) `OS name: Darwin, version: 24.0.0, architecture: arm64`

**Cmake version**
**Ninja version**
**Compiler name and version**

Compiler `clang++`
```
Homebrew clang version 18.1.8
Target: arm64-apple-darwin24.0.0
Thread model: posix
```

**Full cmake and/or ninja output**
When use `offsetof()` in our project included contrib/llvm-project, i got a build error. The simpler reproduce steps as follows:
```zsh
build % clang++ -std=c++23 -isystem clickhouse/contrib/llvm-project/libcxx/include test.cpp -o test 

test.cpp:11:28: error: 'A' does not refer to a value
   11 |     auto offset = offsetof(A, a);
      |                            ^
test.cpp:4:8: note: declared here
    4 | struct A
      |        ^
test.cpp:11:31: error: use of undeclared identifier 'a'
   11 |     auto offset = offsetof(A, a);
      |                               ^
2 errors generated.
```
it's a <test.cpp>
```c++
#include <sys/types.h>
#include <cstddef>

struct A
{
    int a;
};

int main()
{
    auto offset = offsetof(A, a);
    return 0;
}
```

And i noticed that [this commit](https://github.com/llvm/llvm-project/commit/2950283dddab03c183c1be2d7de9d4999cc86131) in the original llvm project fixed this problem. Hopefully this problem can be solved in clickhouse's own llvm-project repo as well.

**Comment by nickitat** [comment]
https://github.com/ClickHouse/ClickHouse/pull/70671
