### ISSUE TITLE
Improving writeAnyEscapedString for scalar subqueries

### ISSUE THREAD

**Issue by yingfeng** [ClickHouse/ClickHouse#7077]
As mentioned in PR [6773](https://github.com/ClickHouse/ClickHouse/pull/6773), the overhead introduced by string escaping for serialization/deserialization is not negligible.

What's more, according to the experiments mentioned in issue [6880](https://github.com/ClickHouse/ClickHouse/issues/6880) and [6956](https://github.com/ClickHouse/ClickHouse/issues/6956), the overhead of string escaping could even be dominant if the bitmap intermediate results are huge, say tens of millions of ids contained. 

Here are the performance comparison for using a tiny patch(patch1) :

```
@@ -130,7 +130,9 @@ String FieldVisitorToString::operator() (const DecimalField<Decimal128> & x) con
 String FieldVisitorToString::operator() (const UInt128 & x) const { return formatQuoted(UUID(x)); }
 String FieldVisitorToString::operator() (const AggregateFunctionStateData & x) const
 {
-    return formatQuoted(x.data);
+    return x.data;
 }
```

The query is:
```
WITH
    (
        SELECT mid_seqs
        FROM cdp_tags
        WHERE tag_id = 'mobile_province_NA'
        LIMIT 1
    ) AS bm
SELECT count(cab_type_id)
FROM trips
WHERE bitmapContains(bm, toUInt32(id));

CREATE TABLE cdp_tags ( \
    tag_id String, \
    mid_seqs AggregateFunction(groupBitmap, UInt32), \
    cardinality UInt32 \
) engine=ReplacingMergeTree() \
ORDER BY (tag_id);
```
Table `trips` is just the same got from [New York Taxi Data](https://clickhouse.yandex/docs/en/getting_started/example_datasets/nyc_taxi/), while `SELECT mid_seqs FROM cdp_tags WHERE tag_id = 'mobile_province_NA' LIMIT 1` will return a bitmap containing over 40M ids.

The original time takes around 19s, while after the modification, the query time is reduced to around 7s, and we could see ` String FieldVisitorToString::operator() (const AggregateFunctionStateData & x) const` has been called over 22 times during the query.  

However, `patch1` could not be applied because it will lead to deserialization error under distributed queries, just as PR [6773](https://github.com/ClickHouse/ClickHouse/pull/6773) has fixed. 

Therefore we made an extra experiments with as fewer change as possible(patch2):
```
--- a/dbms/src/IO/WriteHelpers.h
+++ b/dbms/src/IO/WriteHelpers.h
@@ -267,7 +267,7 @@ void writeAnyEscapedString(const char * begin, const char * end, WriteBuffer & b
     while (true)
     {
         /// On purpose we will escape more characters than minimally necessary.
-        const char * next_pos = find_first_symbols<'\b', '\f', '\n', '\r', '\t', '\0', '\\', quote_character>(pos, end);
+        const char * next_pos = find_first_symbols<'\\', quote_character>(pos, end);

         if (next_pos == end)
         {
```

Within `patch2`, ` String FieldVisitorToString::operator() (const AggregateFunctionStateData & x) const` is left unchanged, while only `writeAnyEscapedString` is adjusted such that as few string find operation happened as possible during string escaping. Given this patch, the above query time is around 7.8s, which is a bit worse than no string escaping.  `patch2` seems work well, which means the scalar subquery performance is improved from 19s to 7.8s, which is a remarkable achievement. 

As a result, we have the following questions:
1. Why ` String FieldVisitorToString::operator() (const AggregateFunctionStateData & x) const` is called so many times for the scalar sub query?  Does this have close relationship with the number of partitions of the table data?

```
select partition from system.parts where table='trips';

115 rows in set
```

2. Perhaps some faster string find algorithms could be used to replace for  `find_first_symbols` , although it does not have the same remarkable achievements for performance improvements as the first point.

**Comment by alexey-milovidov** [comment]
The reason is escaping of zero bytes by `\0`.
Serialized aggregation state has multiple zero bytes and all of them are escaped. This is slow path of string escaping function.

> Why String FieldVisitorToString::operator() (const AggregateFunctionStateData & x) const is called so many times for the scalar sub query?

Because the value is constant string literal, it is used during query analysis for naming of columns. Probably in AST normalization. This can be easily fixed. Look at the `ASTLiteral::appendColumnNameImpl`. PS. It's a wild guess, better to find out code locations by printing stack traces or with gdb.

> Perhaps some faster string find algorithms could be used to replace for find_first_symbols

No, we use the fastest algorithm known as of 2019. Optimized for specific use case, that does not cover output of serialized aggregate function states in string literals.

**Comment by alexey-milovidov** [comment]
Could you please add a performance test to `dbms/tests/performance`?
The `default.trips_mergetree` is available in our CI, look at the example in `nyc_taxi.xml`.

Then we will make some tricks and try to improve performance.

**Comment by yingfeng** [comment]
@alexey-milovidov 
Thanks for your advice. We will add performance to CI later after we had got familiar with corresponding rules. 

Regarding to escaping of zero bytes by `\0`, it seems not that necessary due to the PR [6773](https://github.com/ClickHouse/ClickHouse/pull/6773), 

```
@@ -218,9 +218,11 @@ void DataTypeAggregateFunction::deserializeTextQuoted(IColumn & column, ReadBuff
}


-void DataTypeAggregateFunction::deserializeWholeText(IColumn &, ReadBuffer &, const FormatSettings &) const
+void DataTypeAggregateFunction::deserializeWholeText(IColumn & column, ReadBuffer & istr, const FormatSettings &) const
{
-    throw Exception("AggregateFunction data type cannot be read from text", ErrorCodes::NOT_IMPLEMENTED);
+    String s;
+    readStringUntilEOF(s, istr);
+    deserializeFromString(function, column, s);
}
```

`readStringUntilEOF` is used to deserialize in `DataTypeAggregateFunction` instead of original `readEscapedString`, as a result, even if zero bytes exist within the binary data of aggregate state, it could still be read correctly. This could be verified even if we remove escaping for zero bytes through `\0`:
```
--- a/dbms/src/IO/WriteHelpers.h
+++ b/dbms/src/IO/WriteHelpers.h
@@ -267,7 +267,7 @@ void writeAnyEscapedString(const char * begin, const char * end, WriteBuffer & b
     while (true)
     {
         /// On purpose we will escape more characters than minimally necessary.
-        const char * next_pos = find_first_symbols<'\b', '\f', '\n', '\r', '\t', '\0', '\\', quote_character>(pos, end);
+        const char * next_pos = find_first_symbols<'\\', quote_character>(pos, end);

         if (next_pos == end)
         {
```
The above modification could work correctly given bitmap aggregate state data. 


Regarding to `ASTLiteral::appendColumnNameImpl`, yes, after tracking, it's just the place leading to the many calling times of `String FieldVisitorToString::operator() (const AggregateFunctionStateData & x) const`, we will dive into and find how to improve.  However, through reviewing the code of `ASTLiteral::appendColumnNameImpl`, we've found special processing of `Array`:
```
void ASTLiteral::appendColumnNameImpl(WriteBuffer & ostr) const
{
    /// Special case for very large arrays. Instead of listing all elements, will use hash of them.
    /// (Otherwise column name will be too long, that will lead to significant slowdown of expression analysis.)
    if (value.getType() == Field::Types::Array
        && value.get<const Array &>().size() > 100)        /// 100 - just arbitrary value.
    {
        SipHash hash;
        applyVisitor(FieldVisitorHash(hash), value);
        UInt64 low, high;
        hash.get128(low, high);

        writeCString("__array_", ostr);
        writeText(low, ostr);
        ostr.write('_');
        writeText(high, ostr);
    }
    else
    {
        String column_name = applyVisitor(FieldVisitorToString(), value);
        writeString(column_name, ostr);
    }
}
```

It applies hashing function to array data, however, because array data is going to be encapsulated within `AST` and transferred to remote nodes for distributed queries, it might lead to deserialization error in that case?  We've made some experiments as a result:

```
WITH
    (
    SELECT groupArray(id)
    FROM customs
    WHERE channel = '100000010'
    ) AS array
SELECT count(cab_type_id)
FROM trips
WHERE has(array, toUInt32(id))``
```

The query of `SELECT groupArray(id) FROM customs WHERE channel = '100000010'` will return an array with length of above 100.  Such query could work normally for single node, but when it's send to a distributed table with two nodes, exceptions are thrown:
```
WITH
    (
    SELECT groupArray(id)
    FROM customs
    WHERE channel = '100000010'
    ) AS array
SELECT count(cab_type_id)
FROM dist_trips
WHERE has(array, toUInt32(id))``

Received exception from server (version 19.13.4):
Code: 179. DB::Exception: Received from localhost:9000. DB::Exception: Different expressions with the same alias array:
CAST([546771521, 549433648, 549715286, 386194904, 692932328, 696715589, 696852252, 696852735, 595281409, 363305567, 363586137, 365477584, 415805299, 416642412, 418745063, 419095330, 593466900, 434145463, 376742408, 376743306, 381575065, 382484052, 383600949, 463331812, 464456610, 464877411, 606837678, 609350509, 609420002, 597314687, 385778627, 393827445, 396069244, 398586337, 399492715, 399702809, 403690838, 421758882, 422386382, 426230693, 428123297, 428965128, 480342586, 481110374, 485943796, 486643277, 486719224, 487069783, 487136809, 487906140, 492735049, 435055715, 526548648, 528220435, 529903500, 531656295, 553358783, 557069233, 558399523, 560844435, 561682602, 562031633, 563929082, 568401186, 568753174, 570649793, 606067749, 689646825, 686635935, 583804265, 585414159, 586258385, 588077110, 590384936, 594935735, 600325450, 603123462, 604944462, 510230978, 510935483, 514859885, 522482329, 616007249, 618385184, 619363702, 619501497, 623849205, 642538104, 432673141, 498687812, 498753901, 505406053, 505479704, 505828484, 506319897, 507714864, 508137141, 478667969, 465926231, 465929633, 467467121, 467951541, 471737469, 644426367, 651355833, 652547979, 653528796, 390675312, 436879952, 438485804, 443803171, 444783816, 444852073, 632732064, 633922988, 635391306, 638896029, 591785626, 672214371, 673261142, 673689808, 674944487, 681383743, 682363499, 682858301, 433514137, 658219629, 658494729, 660805103, 662482269, 664374737, 670740320, 473838914], 'Array(UInt32)') AS array
and
CAST([553358783, 557069233, 558399523, 560844435, 561682602, 562031633, 563929082, 376742408, 376743306, 381575065, 382484052, 383600949, 385778627, 386194904, 390675312, 689646825, 692932328, 419095330, 363305567, 363586137, 365477584, 416642412, 421758882, 422386382, 426230693, 428123297, 428965128, 432673141, 433514137, 434145463, 435055715, 463331812, 464456610, 464877411, 436879952, 438485804, 443803171, 444783816, 444852073, 510230978, 510935483, 514859885, 522482329, 418745063, 480342586, 481110374, 485943796, 486643277, 486719224, 487069783, 487136809, 487906140, 492735049, 526548648, 528220435, 529903500, 531656295, 623849205, 498687812, 498753901, 505406053, 505479704, 505828484, 506319897, 507714864, 508137141, 546771521, 549433648, 549715286, 658219629, 658494729, 660805103, 662482269, 664374737, 583804265, 585414159, 586258385, 588077110, 590384936, 591785626, 593466900, 594935735, 595281409, 568401186, 568753174, 570649793, 616007249, 618385184, 619363702, 682858301, 686635935, 600325450, 603123462, 604944462, 606067749, 606837678, 609350509, 609420002, 632732064, 633922988, 635391306, 638896029, 642538104, 478667969, 465926231, 465929633, 467467121, 467951541, 471737469, 473838914, 393827445, 396069244, 398586337, 399492715, 399702809, 403690838, 644426367, 651355833, 652547979, 653528796, 597314687, 415805299, 672214371, 673261142, 673689808, 674944487, 681383743, 682363499, 619501497, 696715589, 696852252, 696852735, 670740320], 'Array(UInt32)') AS array

```

But it can work normally if array is send as const:
```
WITH
    (
    [1,2,3,355,123,123456,34566]
    ) AS array
SELECT count(cab_type_id)
FROM dist_trips
WHERE has(array, toUInt32(id))
```


Perhaps this is more suitable to propose an extra issue as a bug for array to be used in distributed queries.

**Comment by yingfeng** [comment]
This issue is bypassed by PR [7359](https://github.com/ClickHouse/ClickHouse/pull/7359)
