### ISSUE TITLE
now() was not working as expected

### ISSUE THREAD

**Issue by nagababu9652** [ClickHouse/ClickHouse#70774]
HI, I was working on a analytical project using clickhouse. In a table I was trying to insert a field which represent time at which row was inserted. So I was using now() to get the current time but it was giving wrong time ( time with 1 min 30 seconds less then actual time)

![image](https://github.com/user-attachments/assets/af556d34-d6dd-474c-bed5-22ac24f9cf47)

**How to reproduce**
I was getting data from kafka when comparing with kafka virtual field _timestamp and now() as insertdatetime 
![image](https://github.com/user-attachments/assets/b3ef61b5-7757-4545-ba41-ea2b1773e57f)

CREATE TABLE qtrackerdata (  deviceid String, tenantgroupuid String,   tenantuid String, speed Float32,    uniqueid Int32,ignitionstatus Int8,recordstatus Int8,devicedatetime DateTime64, listenerdatetime  DateTime64, latitude Float32,    longitude Float32, iostring String, reason UInt32, altitude Float32, analog0 Float32, analog1 Float32, analog2 Float32, analog3 Float32, analog4 Float32, analog5 Float32, analog6 Float32, analog7 Float32, analog8 Float32, analog9 Float32, analog10 Float32, btterylevel Float32, deviceinternalbattery Float32, dgpslatitude Float32, dgpslongitude Float32, gpsdirection Float32, hdop Float32, mainpower Float32, posaccuracy Float32, bintag1 String, bintag2 String, firmwareversion String, geofencenameen String, ibutton String, keysafetag String, locationen String, alarm UInt16, gpsfix UInt8, canodometer Float32, cantotalfuelused Float32, canvehiclespeed Float32, fmsenginehours Float32, fmsfuellevel Float32, fmsfuelused Float32, fmsodometer Float32, fmsservicedistance Float32, odometer Float32, pulseodometer Float32, rmseventtype String) ENGINE = Kafka SETTINGS kafka_broker_list ='192.168.57.20:3411,192.168.57.21:3411,192.168.57.22:3411',kafka_topic_list = 'common-livelocationdata',    kafka_group_name = 'clickhousegroup_2',    kafka_format = 'JSONEachRow',    kafka_num_consumers = 10;

CREATE TABLE tbltrackerdata (deviceid String, tenantgroupuid LowCardinality(String),   speed Float32,    uniqueid Int32,ignitionstatus Int8,recordstatus Int8,devicedatetime DateTime, insertdatetime DateTime, latitude Float32,    longitude Float32 ,vehicleid String, parserid Int16, devicetypeid Int16, active Int8,  devicetypename LowCardinality(String),  tenantgroupname LowCardinality(String), parsername  LowCardinality(String), iostring String, customer String, reason UInt32, altitude Float32, analog0 Float32, analog1 Float32, analog2 Float32, analog3 Float32, analog4 Float32, analog5 Float32, analog6 Float32, analog7 Float32, analog8 Float32, analog9 Float32, analog10 Float32, btterylevel Float32, deviceinternalbattery Float32, dgpslatitude Float32, dgpslongitude Float32, gpsdirection Float32, hdop Float32, mainpower Float32, posaccuracy Float32, bintag1 String, bintag2 String, firmwareversion String, geofencenameen String, ibutton String, keysafetag String, locationen String, alarm UInt16, gpsfix UInt8, canodometer Float32, cantotalfuelused Float32, canvehiclespeed Float32, fmsenginehours Float32, fmsfuellevel Float32, fmsfuelused Float32, fmsodometer Float32, fmsservicedistance Float32, odometer Float32, pulseodometer Float32, kafka_timestamp Datetime , listenerdatetime Datetime, rmseventtype String) ENGINE = MergeTree() ORDER BY devicedatetime TTL insertdatetime + INTERVAL 2 DAY;

create materialized view viewtrackerdata to tbltrackerdata as select qtd.deviceid as deviceid, qtd.tenantgroupuid as tenantgroupuid, speed, uniqueid, ignitionstatus, recordstatus, devicedatetime, **now()  as insertdatetime**, latitude, longitude, vehicleid, parserid, devicetypeid, active, devicetypename,  tenantgroupname, parsername, iostring, customer, reason , altitude , analog0, analog1, analog2, analog3, analog4, analog5, analog6, analog7, analog8, analog9, analog10, btterylevel, deviceinternalbattery, dgpslatitude, dgpslongitude, gpsdirection , hdop, mainpower, posaccuracy, bintag1, bintag2, firmwareversion, geofencenameen, ibutton, keysafetag, locationen, alarm, gpsfix, canodometer, cantotalfuelused, canvehiclespeed, fmsenginehours, fmsfuellevel, fmsfuelused, fmsodometer, fmsservicedistance, odometer, pulseodometer, **_timestamp as kafka_timestamp, ** listenerdatetime  from qtrackerdata qtd LEFT JOIN  viewcombineddata cd final on qtd.deviceid = cd.deviceid 

* Which ClickHouse server version to use
version 24.7.3

**Expected behavior**
I was expecting to get the current time

**Comment by larry-cdn77** [comment]
1 minute 30 seconds must be your ingest latency then?

**Comment by den-crane** [comment]
`now()` is a constant within an insert.

If you do `insert into .... values (now())` and this insert lasts for two hours then all rows will have the same time and it will be  equal the time when insert has started.

Try to define column default now() in the `tbltrackerdata` and don't fill this column in the matView.

**Comment by nagababu9652** [comment]
I have removed now() in insert into and alter the column definition by 
 ALTER TABLE tbltrackerdata MODIFY COLUMN insertdatetime DateTime DEFAULT now();
 
 but still having the same issue
 
 
 REATE TABLE default.tbltrackerdata
(
    `deviceid` String,
    `tenantgroupuid` LowCardinality(String),
    `speed` Float32,
    `uniqueid` Int32,
    `ignitionstatus` Int8,
    `recordstatus` Int8,
    `devicedatetime` DateTime,
    **`insertdatetime` DateTime DEFAULT now(),**
    `latitude` Float32,
    `longitude` Float32,
    `vehicleid` String,
 ......)
 
 
![image](https://github.com/user-attachments/assets/ba4a159e-d1e8-49cb-8ec2-d9431bf841b3)

**Comment by den-crane** [comment]
How many rows is in ` viewcombineddata` ?

Can you share 

```
select now(), _timestamp from qtrackerdata limit 10 settings stream_like_engine_allow_direct_select=1
```

**Comment by nagababu9652** [comment]
Hi @den-crane , 

There were about 90000 records were there in viewcombineddata 

![image](https://github.com/user-attachments/assets/ea0d0343-9d54-4077-9666-ea6f8c424146)

**Comment by den-crane** [comment]
I looks like the time of your broker(or producer) and clickhouse are not synced

**Comment by sunny19930321** [comment]
I have the same problem，the broker(or producer) and clickhouse time are the same
