### ISSUE TITLE
ReplacingMergeTree deduplication Efficiency.

### ISSUE THREAD

**Issue by AlekseyKanaev** [ClickHouse/ClickHouse#70773]
### Company or project name

Pet project.

### Question

I'm testing Clickhouse as possible PostgreSQL replacement  for my workloads. My current concern is handling duplicates. 
I deliberately populated my test table with duplicates (~2.5 factor), so I could observe efficiency of ReplacingMergeTree de-duplication. The test table holds approximately  1.2 billion of rows and it has been populated for 4 days. The issue is I don't see any de-duplication at all, - number of rows are exactly the same as it was when initial insertion was completed.
So, my concerns are whether such behavior is expected or did I do something wrong?

I executed deduplicate statement
`optimize TABLE comments2   deduplicate  SETTINGS optimize_throw_if_noop = 1;` and it returnes:
_There is no need to merge parts according to merge selector algorithm. Cannot select parts for optimization. (CANNOT_ASSIGN_OPTIMIZE) (version 24.9.2.42 (official build))_

Using `Final` is out of question, because its unexceptionably slow.

I have small server (2 cores, 4 GB RAM, 1 TB disk space), and configured Clickhouse according the recommendations for small servers.

```
CREATE TABLE default.comments
(

    `id` String,

    `text` String,

    `votes` String,

    `votes_number` UInt32,

    `heart` Bool,

    `reply` Bool,

    `parsed` DateTime,

    `processed` DateTime,

    `commenter_id` String,

    `video_id` String,

    `channel_id` String
)
ENGINE = ReplacingMergeTree
PRIMARY KEY (commenter_id,
 video_id,
 id)
ORDER BY (commenter_id,
 video_id,
 id)
SETTINGS index_granularity = 8192;
```

**Comment by nickitat** [comment]
deduplication happens during merge. if merges happen and your table deduplication key matches the logic you tried to implement - everything should be fine.
anyways optimize is not the way RMT is supposed to work. using `final` is the right way.
