### ISSUE TITLE
Unexpected behaviour with sleep and sleepEachRow

### ISSUE THREAD

**Issue by silviucpp** [ClickHouse/ClickHouse#7078]
Hello,

Using last master:

```sql
CREATE DATABASE mydb;

CREATE TABLE mydb.mytable (
  `index` Nullable(Int64),
  `timestamp` DateTime,
  `created_at` DateTime
) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY timestamp SETTINGS index_granularity = 8192
```

When executing:
 
```
curl -X POST 'http://127.0.0.1:8123/?timeout_overflow_mode=throw&max_execution_time=5' -d 'SELECT sleep(3), count(*) AS `value` FROM mydb.mytable FORMAT JSON'
```

Query is running for 12 seconds and returns:

```
{
	"meta":
	[
		{
			"name": "sleep(2)",
			"type": "UInt8"
		},
		{
			"name": "value",
			"type": "UInt64"
		}
	],

	"data":
	[
		{
			"sleep(2)": 0,
			"value": 0
		}
	],

	"rows": 1,

	"statistics":
	{
		"elapsed": 3.005157,
		"rows_read": 0,
		"bytes_read": 0
	}
}
```

Unexpected behavior for me is:

Query should return in 3 seconds not in 12 because I don't have any record in the table which can lead to multiple blocks (based on docs: Sleeps 'seconds' seconds on each data block).

I'm missing something ? I was trying to simulate an error generated by `max_execution_time` overflow but I'm blocked by this unexpected behavior. 

I tried the same on "system.numbers" and there it's working fine.

**Comment by silviucpp** [comment]
@alexey-milovidov my feeeling is that `isSuitableForConstantFolding` is not working properly. Problem is that function is executed several times during the query analysis.

**Comment by alexey-milovidov** [comment]
Fixed.
