### ISSUE TITLE
SYSTEM DROP REPLICA

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#7080]
Sometime you need to remove the 'dead' replica. 
attach + DROP is a bit too 'costy' and complicated.
removing nodes in zookeeper is also a bad option as requires knowledge of ClickHouse internals.  

It would be better to have a possibility to remove 'dead' replica from healthy one (only in case if it's offline and stale, exception otherwise).

**Comment by filimonov** [comment]
Typical usecase: server was off for a long time / replace replica with new one.

Currently it will not allow you to CREATE (replica already exists), ATTACH has not to much sense and will requite enabling replica recovery, and will try to 'execute' obsolete queue.

**Comment by cw9** [comment]
Hi, is there any timeline for supporting this? This would be a great feature.

**Comment by alexey-milovidov** [comment]
There is no timeline for this task. But it is easy to implement.

The only important thing is to check that replica is not active, and while removing - remove some nodes first in a multi transaction with check of `active` node - to avoid possible race condition.

**Comment by cw9** [comment]
Bump, is there any update on supporting this? This would be a super useful feature!

**Comment by cw9** [comment]
Hi, is it safe to `rmr /path/to/replica` on ZK for this case? Is there anything else to be deleted?

**Comment by alexey-milovidov** [comment]
Almost safe. You only have to check that the replica is not active within the same transaction.

**Comment by cw9** [comment]
Thank you!
