### ISSUE TITLE
CurrentMetric on the number of currently merging source parts.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#70809]
**Use case**

Check how many parts are held for current merges.

**Describe the solution you'd like**

`CurrentMetric::Increment` by the number of source parts.

**Comment by R3gardless** [comment]
@alexey-milovidov Hi, are you still working on this issue? If not, would it be okay for me to take it on as my first issue?

**Comment by alexey-milovidov** [comment]
@R3gardless, yes this will be wonderful!
