### ISSUE TITLE
Code: 252. DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts. (TOO_MANY_PARTS) 

### ISSUE THREAD

**Issue by smallemployees** [ClickHouse/ClickHouse#70822]
### Question

Code: 252. DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts. (TOO_MANY_PARTS)

**Comment by EminemJK** [comment]
You can reduce the speed of inserting data, and it is recommended to insert data in batches, such as 1000 rows in batches
