### ISSUE TITLE
Incomprehensible text in Chinese: 程序异常退出，日志没有提示

### ISSUE THREAD

**Issue by gaoyuan98** [ClickHouse/ClickHouse#70827]
verion   v23.12.6.19
程序异常退出，没有Error级别告警   麻烦看一下 谢谢 

2024.10.15 08:26:25.000768 [ 105196 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 4.07 GiB, peak 10.00 GiB, free memory in arenas 113.66 MiB, will set to 2.18 GiB (RSS), difference: -1.89 GiB
2024.10.15 08:26:25.345485 [ 105109 ] {91515b14-9007-40f7-b660-3fd2492b96eb::202410_40174_43525_483} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 25257 rows, containing 759 columns (759 merged, 0 gathered) in 0.716768121 sec., 35237.33723643103 rows/sec., 26.91 MiB/sec.
2024.10.15 08:26:25.484977 [ 105109 ] {91515b14-9007-40f7-b660-3fd2492b96eb::202410_40174_43525_483} <Trace> MergedBlockOutputStream: filled checksums 202410_40174_43525_483 (state Temporary)
2024.10.15 08:26:25.502762 [ 104521 ] {} <Trace> BaseDaemon: Received signal -1
2024.10.15 08:26:25.509780 [ 104521 ] {} <Trace> BaseDaemon: Received signal 6
2024.10.15 08:26:25.791689 [ 105118 ] {} <Debug> MemoryTracker: Peak memory usage background process to apply mutate/merge in table: 17.73 MiB.
2024.10.15 08:26:26.001394 [ 105196 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 2.08 GiB, peak 10.00 GiB, free memory in arenas 200.25 MiB, will set to 3.33 GiB (RSS), difference: 1.25 GiB
2024.10.15 08:26:27.000728 [ 105196 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.33 GiB, peak 10.00 GiB, free memory in arenas 200.16 MiB, will set to 3.46 GiB (RSS), difference: 126.11 MiB
2024.10.15 08:26:27.402942 [ 105075 ] {} <Debug> DNSResolver: Updating DNS cache
2024.10.15 08:26:27.403221 [ 105075 ] {} <Debug> DNSResolver: Updated DNS cache
2024.10.15 08:26:28.000732 [ 105196 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.46 GiB, peak 10.00 GiB, free memory in arenas 200.21 MiB, will set to 3.47 GiB (RSS), difference: 16.76 MiB
2024.10.15 08:26:29.027302 [ 105149 ] {} <Trace> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e): Found 2 old parts to remove. Parts: [202410_45401_46722_828, 202410_46723_46723_0]
2024.10.15 08:26:29.027337 [ 105149 ] {} <Debug> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e): Removing 2 parts from filesystem (serially): Parts: [202410_45401_46722_828, 202410_46723_46723_0]
2024.10.15 08:26:29.028568 [ 105149 ] {} <Debug> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e): Removing 2 parts from memory: Parts: [202410_45401_46722_828, 202410_46723_46723_0]
2024.10.15 08:26:29.972278 [ 109425 ] {} <Debug> SystemLogQueue (system.crash_log): Requested flush up to offset 1
2024.10.15 08:26:29.972310 [ 109425 ] {} <Information> SentryWriter: Not sending crash report
2024.10.15 08:26:29.972351 [ 105215 ] {} <Trace> SystemLog (system.crash_log): Flushing system log, 1 entries to flush up to offset 1
2024.10.15 08:26:29.972445 [ 105215 ] {} <Debug> SystemLog (system.crash_log): Creating new table system.crash_log for CrashLog
2024.10.15 08:26:29.977906 [ 105215 ] {} <Debug> system.crash_log (d9c264d0-aace-4578-907f-567e88a1a51c): Loading data parts
2024.10.15 08:26:29.978222 [ 105215 ] {} <Debug> system.crash_log (d9c264d0-aace-4578-907f-567e88a1a51c): There are no data parts
2024.10.15 08:26:29.979447 [ 105215 ] {} <Trace> system.crash_log (d9c264d0-aace-4578-907f-567e88a1a51c): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2024.10.15 08:26:29.979471 [ 105215 ] {} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 1.16 MiB.
2024.10.15 08:26:29.979800 [ 105215 ] {} <Trace> MergedBlockOutputStream: filled checksums all_1_1_0 (state Temporary)
2024.10.15 08:26:29.980016 [ 105215 ] {} <Trace> system.crash_log (d9c264d0-aace-4578-907f-567e88a1a51c): Renaming temporary part tmp_insert_all_1_1_0 to all_1_1_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2024.10.15 08:26:29.980136 [ 105215 ] {} <Trace> SystemLog (system.crash_log): Flushed system log up to offset 1
2024.10.15 08:26:30.001312 [ 105196 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.47 GiB, peak 10.00 GiB, free memory in arenas 199.23 MiB, will set to 3.47 GiB (RSS), difference: -2.75 MiB
2024.10.15 08:26:31.169537 [ 105211 ] {} <Trace> SystemLog (system.trace_log): Flushing system log, 1486 entries to flush up to offset 3937672
2024.10.15 08:26:31.175876 [ 105211 ] {} <Trace> system.trace_log (fae40af7-7125-40ac-adaa-330cd85afc0c): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2024.10.15 08:26:31.175960 [ 105211 ] {} <Trace> DiskLocal: Could not reserve 1.00 MiB on local disk `default`. Not enough unreserved space
2024.10.15 08:26:31.176001 [ 105211 ] {} <Trace> StoragePolicy (default): Could not reserve 1.00 MiB from volume index 0, total volumes 1
2024.10.15 08:26:31.185218 [ 105211 ] {} <Trace> SystemLog (system.trace_log): Flushed system log up to offset 3937672
2024.10.15 08:26:31.576736 [ 105156 ] {} <Trace> system.trace_log (fae40af7-7125-40ac-adaa-330cd85afc0c): Found 2 old parts to remove. Parts: [202410_41663_42462_666, 202410_42463_42463_0]
2024.10.15 08:26:31.576767 [ 105156 ] {} <Debug> system.trace_log (fae40af7-7125-40ac-adaa-330cd85afc0c): Removing 2 parts from filesystem (serially): Parts: [202410_41663_42462_666, 202410_42463_42463_0]
2024.10.15 08:26:31.578134 [ 105156 ] {} <Debug> system.trace_log (fae40af7-7125-40ac-adaa-330cd85afc0c): Removing 2 parts from memory: Parts: [202410_41663_42462_666, 202410_42463_42463_0]
2024.10.15 08:26:31.677386 [ 105169 ] {} <Trace> system.query_log (270b0af9-da81-447e-a075-1422b2fd5f57): Found 6 old parts to remove. Parts: [202410_23694_23876_34, 202410_23877_23877_0, 202410_23878_23878_0, 202410_23879_23879_0, 202410_23880_23880_0, 202410_23881_23881_0]
2024.10.15 08:26:31.677414 [ 105169 ] {} <Debug> system.query_log (270b0af9-da81-447e-a075-1422b2fd5f57): Removing 6 parts from filesystem (serially): Parts: [202410_23694_23876_34, 202410_23877_23877_0, 202410_23878_23878_0, 202410_23879_23879_0, 202410_23880_23880_0, 202410_23881_23881_0]
2024.10.15 08:26:31.678685 [ 105169 ] {} <Debug> system.query_log (270b0af9-da81-447e-a075-1422b2fd5f57): Removing 6 parts from memory: Parts: [202410_23694_23876_34, 202410_23877_23877_0, 202410_23878_23878_0, 202410_23879_23879_0, 202410_23880_23880_0, 202410_23881_23881_0]
2024.10.15 08:26:31.924607 [ 105193 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushing system log, 3661 entries to flush up to offset 169528895
2024.10.15 08:26:31.927467 [ 105193 ] {} <Trace> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2024.10.15 08:26:31.927504 [ 105193 ] {} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 3.31 MiB.
2024.10.15 08:26:31.928227 [ 105193 ] {} <Trace> MergedBlockOutputStream: filled checksums 202410_46254_46254_0 (state Temporary)
2024.10.15 08:26:31.928466 [ 105193 ] {} <Trace> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e): Renaming temporary part tmp_insert_202410_46254_46254_0 to 202410_46795_46795_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2024.10.15 08:26:31.928600 [ 105193 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Flushed system log up to offset 169528895
2024.10.15 08:26:31.928621 [ 105040 ] {} <Debug> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e) (MergerMutator): Selected 2 parts from 202410_45401_46789_895 to 202410_46790_46790_0
2024.10.15 08:26:31.928646 [ 105040 ] {} <Trace> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e): Trying to reserve 1.34 MiB using storage policy from min volume index 0
2024.10.15 08:26:31.928654 [ 105040 ] {} <Trace> DiskLocal: Reserved 1.34 MiB on local disk `default`, having unreserved 3.05 MiB.
2024.10.15 08:26:31.928876 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Debug> MergeTask::PrepareStage: Merging 2 parts: from 202410_45401_46789_895 to 202410_46790_46790_0 into Wide with storage Full
2024.10.15 08:26:31.929151 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Debug> MergeTask::PrepareStage: Selected MergeAlgorithm: Horizontal
2024.10.15 08:26:31.929223 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Debug> MergeTreeSequentialSource: Reading 623 marks from part 202410_45401_46789_895, total 5091042 rows starting from the beginning of the part
2024.10.15 08:26:31.929527 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Debug> MergeTreeSequentialSource: Reading 2 marks from part 202410_46790_46790_0, total 3661 rows starting from the beginning of the part
2024.10.15 08:26:32.001313 [ 105196 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.49 GiB, peak 10.00 GiB, free memory in arenas 153.52 MiB, will set to 3.46 GiB (RSS), difference: -23.35 MiB
2024.10.15 08:26:32.129813 [ 105208 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 7 entries to flush up to offset 324136
2024.10.15 08:26:32.154812 [ 105208 ] {} <Trace> system.metric_log (91515b14-9007-40f7-b660-3fd2492b96eb): Trying to reserve 1.00 MiB using storage policy from min volume index 0
2024.10.15 08:26:32.154859 [ 105208 ] {} <Trace> DiskLocal: Reserved 1.00 MiB on local disk `default`, having unreserved 2.02 MiB.
2024.10.15 08:26:32.162860 [ 105208 ] {} <Trace> MergedBlockOutputStream: filled checksums 202410_43020_43020_0 (state Temporary)
2024.10.15 08:26:32.167728 [ 105208 ] {} <Trace> system.metric_log (91515b14-9007-40f7-b660-3fd2492b96eb): Renaming temporary part tmp_insert_202410_43020_43020_0 to 202410_43526_43526_0 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2024.10.15 08:26:32.169244 [ 105208 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 324136
2024.10.15 08:26:32.743216 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Debug> MergeTask::MergeProjectionsStage: Merge sorted 5094703 rows, containing 5 columns (5 merged, 0 gathered) in 0.814438808 sec., 6255476.715937632 rows/sec., 98.62 MiB/sec.
2024.10.15 08:26:32.744316 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Trace> MergedBlockOutputStream: filled checksums 202410_45401_46790_896 (state Temporary)
2024.10.15 08:26:32.744711 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Trace> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e): Renaming temporary part tmp_merge_202410_45401_46790_896 to 202410_45401_46790_896 with tid (1, 1, 00000000-0000-0000-0000-000000000000).
2024.10.15 08:26:32.744764 [ 105108 ] {cb246afe-4de6-4822-b8c9-36dd87a6f76e::202410_45401_46790_896} <Trace> system.asynchronous_metric_log (cb246afe-4de6-4822-b8c9-36dd87a6f76e) (MergerMutator): Merged 2 parts: [202410_45401_46789_895, 202410_46790_46790_0] -> 202410_45401_46790_896
2024.10.15 08:26:32.744825 [ 105108 ] {} <Debug> MemoryTracker: Peak memory usage background process to apply mutate/merge in table: 17.73 MiB.
2024.10.15 08:26:33.001349 [ 105196 ] {} <Trace> AsynchronousMetrics: MemoryTracking: was 3.45 GiB, peak 10.00 GiB, free memory in arenas 178.27 MiB, will set to 3.47 GiB (RSS), difference: 18.69 MiB
2024.10.18 09:43:59.978584 [ 19797 ] {} <Information> Application: Will watch for the process with pid 19798
2024.10.18 09:43:59.978542 [ 19798 ] {} <Information> Application: Forked a child process to watch
2024.10.18 09:43:59.978695 [ 19798 ] {} <Information> StatusFile: Status file /var/run/clickhouse-server/clickhouse-server.pid already exists - unclean restart. Contents:
104507
2024.10.18 09:43:59.979021 [ 19798 ] {} <Information> SentryWriter: Sending crash reports is disabled
2024.10.18 09:43:59.979197 [ 19798 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB

**Comment by Algunenano** [comment]
> Received signal 6

This is an abort of the process. It's strange there wasn't other Fatal errors around it, but I guess it can happen.

23.12.6.19 is obsolete. You should update to a supported release, see https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md
