### ISSUE TITLE
SSIS incompatible with Clickhouse ODBC

### ISSUE THREAD

**Issue by hooman72** [ClickHouse/ClickHouse#7084]
Hi All

I am working in one of the biggest companies in the middle east and we are using clickhouse.
I want to build my ETL's with SSIS but I can't use clickhouse ODBC as a data-flow source.
I even get a preview of data but [data flow\odbc source] is unable to detect columns.
we used it in powerbi without any issues

visual studio 2019 
ssis: 3.1
clickhouse ODBC: 1.00.00.5435
clickhouse : 19.8.3.8

**Expected behavior**
it would be great if I can read data from clickhouse and insert it to an excel file using SSIS.

SSIS incompatible with Clickhouse ODBC

**Comment by den-crane** [comment]
Wrong repo. try https://github.com/ClickHouse/clickhouse-odbc

**Comment by filimonov** [comment]
https://github.com/ClickHouse/clickhouse-odbc/issues/202
