### ISSUE TITLE
Request: Real-time notification of new data part creation to enable streaming / continuous backups

### ISSUE THREAD

**Issue by ardigan6** [ClickHouse/ClickHouse#70866]
**Use case**

We'd like to run XXL single node CH instances with fast local disks and sharding / merging externally managed, since CH replicated mergetree is slower than large nodes with plain mergetree and replicated inserts are >10x more ops according to the docs.

Our plan is to accept up to N minutes of loss (i.e. much less than the retention window of our queues) on node failure and then replay inserts from the last row written to disk.

However, this requires a way to rapidly find new data parts and know approximately what's in them in order to sync them to backup.

Right now backups are too heavy to run every 60s / every N rows committed. We are self-hosters but I notice this is a feature gap in CH cloud too: backups are only daily.

**Describe the solution you'd like**

When a new data part is stored to disk, clickhouse-server should write an update to a domain socket or publish a message to a config-defined IP:port, at minimum with the filename of the new part and ideally with enough info to let an external index know the point from which to replay inserts.

**Describe alternatives you've considered**

Some not-beautiful workarounds were discussed here: https://github.com/Altinity/clickhouse-backup/issues/1030#issuecomment-2424961146

**Comment by UnamedRus** [comment]
BTW, PostgreSQL have hooks for such thing

https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-ARCHIVING-WAL

From other perspective, as CH doesn't remove parts for 8 minutes by default you have enough time to query system.part_log in loop, and find "new parts" manually

**Comment by alexey-milovidov** [comment]
ReplicatedMergeTree is the right way to do it.
