### ISSUE TITLE
Our usages of `argMax` broke when updating clickhouse version

### ISSUE THREAD

**Issue by saraiva132** [ClickHouse/ClickHouse#70887]
Hi! 

When updating from `23.4.2.11` to `24.9.2.42` all our usages of `argMax` than included Float + DateTime broke. We have integration tests using this image and they were okay. 

Example usage:

```
                "SELECT id, argMax(size, (time,size)) size
                 FROM my_table
                 WHERE id IN ({}) AND
                       time <= parseDateTimeBestEffort('{}', 'UTC')
                 GROUP BY id
                 ORDER BY id DESC;",
```

Conversion from AggregateFunction(argMax, Float64, Tuple(DateTime('UTC'), Float64)) to AggregateFunction(argMax, Float64, Tuple(time DateTime('UTC'), size Float64)) is not supported: While executing Remote 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000d66ad9b

Any recommendation ? I could not find an obvious solution.

**Comment by Algunenano** [comment]
Most likely related to https://github.com/ClickHouse/ClickHouse/issues/70830. 

Try disabling `enable_named_columns_in_function_tuple` (we are reverting the change to disable it by default) and please report a reproducer if possible so it can be improved in the future.

**Comment by saraiva132** [comment]
I am having a hard time reproducing because my integrations tests pass fine using the same version

**Comment by Algunenano** [comment]
Are you are using `tuple()` somewhere in your query? In 24.7 it was changed to return named tuples (via the setting `enable_named_columns_in_function_tuple`) and that's what seems to be causing issues

**Comment by saraiva132** [comment]
What I am sharing is the full query so no :/

**Comment by Algunenano** [comment]
`(time,size)` is calling tuple() implicitly. Sorry I didn't notice it before

**Comment by saraiva132** [comment]
@Algunenano you are a life saver. This did the trick. I will apply this to both of our service but tested in one and it works :) <3
