### ISSUE TITLE
Parquet file generated by ClickHouse can't be read by Spark due to missing codec field (ZSTD , LZ4 set in Spark configuration)

### ISSUE THREAD

**Issue by aol-59** [ClickHouse/ClickHouse#70888]
### Description:
I'm encountering an issue when trying to read a large Parquet file generated by ClickHouse using Apache Spark. The Parquet file is readable in ClickHouse, but Spark throws an error regarding a missing `codec` field in the Parquet metadata. Due to the size of the file, regenerating it is not an option.

I exported a smaller Parquet file using `output_format_parquet_compression_method = snappy`, and it worked successfully in Spark. I also tried using **LZ4** compression, but I am still facing the same issue. I’m looking for a solution to fix my old Parquet files, which are too large to regenerate, and still have the issue of missing codec fields.

### Steps to Reproduce:
1. Generate a Parquet file using ClickHouse without specifying compression.
2. Set **ZSTD** as the Parquet compression codec in Spark:
   ```scala
   spark.conf.set("spark.sql.parquet.compression.codec", "zstd")
   ```

3. Define a schema using `StructType` in Spark:
   ```scala
   import org.apache.spark.sql.types._

   val schema = StructType(Array(
       StructField("COL1", LongType, true),
       StructField("COL2", StringType, true)
       // Add other fields as necessary
   ))

   val df = spark.read.schema(schema).parquet("path_to_parquet_file")
   df.show()
   ```

4. The following error occurs during the read operation:
   ``` 
   caused by shaded.parquet.org.apache.thrift.protocol.TProtocolException: required field 'codec' was not present Struct: columnMetaData (type:INT64, encodings:[RLE_DICTIONARY, PLAIN, RLE], path_in_schema:[COL1], codec:null, num_values:1007489, total_uncompressed_size:1796777, total_compressed_size:1294597, data_page_offset:359149, dictionary_page_offset:4)
   ```

### Environment:
- **Apache Spark version**: 3.2.1
- **ClickHouse version**:  23.8.1.2992
- **Operating System**: Centos

### Workarounds Tried:
- I disabled vectorized reading in Spark using `spark.sql.parquet.enableVectorizedReader=false`, but the issue persists.
- I set `spark.conf.set("spark.sql.parquet.compression.codec", "zstd")` in Spark to explicitly specify the **ZSTD** codec, but it didn’t resolve the issue.
- I exported a smaller file using `output_format_parquet_compression_method = snappy`, and it worked.
- I also tried exporting with **LZ4** compression, but the issue with missing codec fields persists in my large files.

### Question:
I exported a smaller file with `output_format_parquet_compression_method = snappy`, and it worked. I also tried **LZ4**, but my large Parquet files still have missing codec fields. How can I fix these old Parquet files, which are too large to regenerate, so that Spark can read them properly?

---

This version includes the fact that you tried **LZ4** compression and still encountered the same issue. Let me know if this looks good for your GitHub or GitLab issue!

**Comment by den-crane** [comment]
23.8.1.2992 is out of support, check with 24.8.5.115
