### ISSUE TITLE
ClickHouse Insertion

### ISSUE THREAD

**Issue by wlzywang** [ClickHouse/ClickHouse#70907]
### Question

I have a table ta with ct rows

SELECT count()
FROM ta

yields ct

Run insertion

INSERT INTO ta SELECT *
FROM ta

Then count rows in ta again. I expect it to be twice ct.

This works pretty well when ct is small, but unexpected when ct is big like 20 million. Is this a bug?

**Comment by Algunenano** [comment]
> This works pretty well when ct is small, but unexpected when ct is big like 20 million. Is this a bug?

Please describe what you mean with "unexpected". What results are you getting? What results did you expect?

Also, what is the schema of `ta`? Are you using replicated tables (where insert_deduplicate enabled by default)?

**Comment by wlzywang** [comment]
ENGIN is ReplicatedMergeTree
The cluster has only 1 shard, 1 replica.
I feel the schema is not important here but the size matters
When ct is 16 million, I expect it becomes 32 million after the insertion but it becomes 20 million.
When ct is 20 million, I expect it becomes 40 million after the insertion but it becomes 26 million.
When ct is 26 million, I expect it becomes 52 million after the insertion but it becomes 28 million.
When ct is 28 million, I expect it becomes 56 million after the insertion but it becomes 31 million.
When ct is 102 million, I expect it becomes 204 million after the insertion but it becomes 187 million.
When ct is 187 million, I expect it becomes 374 million after the insertion but it becomes 256 million.

**Comment by alexey-milovidov** [comment]
See https://clickhouse.com/blog/common-getting-started-issues-with-clickhouse#5-deduplication-at-insert-time
