### ISSUE TITLE
ClickHouse is hang when CPU and memory usage is normal

### ISSUE THREAD

**Issue by aihuang195** [ClickHouse/ClickHouse#70910]
**Describe the unexpected behaviour**
I have a ClickHouse cluster with  6 nodes. Clickhouse-server version is  19.17.3.7.
Sometimes One of the nodes stopped accepting http connections from client.  The ClickHouse-server process is active and ports are opened. CPU and memory usage is normal.
I'm not sure if it has something to do with the bug: https://github.com/ClickHouse/ClickHouse/issues/7383
I want to know in which version this bug was fixed。

**Error message and/or stacktrace**
I ran pstack Clickhouse-Server-Process-ID and got many __lll_lock_wait.

[root@jd-p-bi-clickhouse03 logs]# grep -B 1 __lll_lock_wait ck_process_trace_20241001155501.log|more
Thread 1089 (Thread 0x7f01667fa700 (LWP 50830)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1088 (Thread 0x7f0164ff7700 (LWP 50833)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1069 (Thread 0x7f014e9f8700 (LWP 50859)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
#12 <signal handler called>
#13 0x00007f01971de54b in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1065 (Thread 0x7f01487f9700 (LWP 50866)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
#12 <signal handler called>
#13 0x00007f01971de54b in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1064 (Thread 0x7f0147ff8700 (LWP 50867)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1049 (Thread 0x7f01253ff700 (LWP 50908)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
#12 <signal handler called>
#13 0x00007f01971de54b in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1043 (Thread 0x7f0120175700 (LWP 50918)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
#12 <signal handler called>
#13 0x00007f01971de54b in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1033 (Thread 0x7f01109fd700 (LWP 50934)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
#12 <signal handler called>
#13 0x00007f01971de54b in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1029 (Thread 0x7f010d3fe700 (LWP 50939)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
#12 <signal handler called>
#13 0x00007f01971de54b in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1020 (Thread 0x7f0078c7f700 (LWP 50962)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0
--
Thread 1019 (Thread 0x7f0077c7d700 (LWP 50964)):
#0  0x00007f01971de54d in __lll_lock_wait () from /lib64/libpthread.so.0

[Uploading ck_process_trace_20241001155501.log…]()

**Additional context**

**Comment by Algunenano** [comment]
Please upgrade to a supported release. 19.17.3.7 is unsupported since several years ago

**Comment by aihuang195** [comment]
Our scenario uses a large number of HDFS engine tables. Can you recommend which version can be well integrated with HDFS and is not obsolete?  Thank you very much.

**Comment by Algunenano** [comment]
Not really, I've never used HDFS. Just test (and I really mean test) the latest stable release (24.9), see how it works for you and report any issues if you find them and are not reported.
