### ISSUE TITLE
How to download a specific release version of ClickHouse for aarch64v80compat(Compatibility version)?

### ISSUE THREAD

**Issue by honobi** [ClickHouse/ClickHouse#70911]
### Question

How to download a specific release version of ClickHouse for aarch64v80compat(Compatibility version)?

**Comment by hoperays** [comment]
The same question.

**Comment by Algunenano** [comment]
AFAICT, we keep:
* All build artifacts in the recent version for some months. For those you can go to the commit, it's CI report, `Builds` ->  binary_aarch64_v80compat`.
* For tagged releases, we keep only standard builds. For example: https://github.com/ClickHouse/ClickHouse/releases/tag/v24.8.5.115-lts

So there is no way to get an old release with `binary_aarch64_v80compat`. You'd need to build it yourself.

**Comment by honobi** [comment]
How to build the aarch64_v80compat version?
