### ISSUE TITLE
max_execution_time not working with 

### ISSUE THREAD

**Issue by silviucpp** [ClickHouse/ClickHouse#7091]
Hello,

I'm using last master and seems `max_execution_time` is not working with `CREATE TEMPORARY TABLE` queries.

Can be reproduced with:

```
CREATE TEMPORARY TABLE `temp_table_1` AS SELECT number FROM system.numbers FORMAT JSON
```

```
curl -X POST 'http://127.0.0.1:8123/?query_id=1232&max_execution_time=2&session_id=1' -d 'CREATE TEMPORARY TABLE `temp_table_1` AS SELECT number FROM system.numbers FORMAT JSON'
```

This query is running till will hit the max_memory limit no matter if you close the client connection.

**Comment by filimonov** [comment]
Can comment on that part:

> no matter if you close the client connection. 

By default HTTP doesn't kill the queries after disconnect, there is `cancel_http_readonly_queries_on_client_close` setting (which is broken in last releases it that report is correct: https://github.com/ClickHouse/ClickHouse/issues/7019 )

**Comment by silviucpp** [comment]
Thanks. good to know. I'll look into `cancel_http_readonly_queries_on_client_close` and debug a bit to see if I can fix the problem. 

Anyway this won't fix the `max_execution_time` so I will let this open.

**Comment by silviucpp** [comment]
@filimonov any idea if `max_execution_time` it suppose to work also with queries like `CREATE TEMPORARY TABLE` ?

For sure right now its not working but I don't know if it's a bug or by design

**Comment by den-crane** [comment]
@silviucpp In what CH version? It was fixed recently https://github.com/ClickHouse/ClickHouse/issues/8505

**Comment by silviucpp** [comment]
@den-crane on the master from sept 2019 :) . You are right next time I will put the commit id as well 

Silviu

**Comment by jackpgao** [comment]
```
xxx :) set max_execution_time = 1 ;

SET max_execution_time = 1

Ok.

0 rows in set. Elapsed: 0.001 sec.

xxx :) select sleep(3);

SELECT sleep(3)

┌─sleep(3)─┐
│        0 │
└──────────┘

1 rows in set. Elapsed: 3.001 sec.

xxx :) select version();

SELECT version()

┌─version()─┐
│ 20.3.7.46 │
└───────────┘

```

**Comment by jackpgao** [comment]
```sql
SELECT version()

┌─version()─┐
│ 20.3.8.53 │
└───────────┘

1 rows in set. Elapsed: 0.001 sec.

xxx :) set max_execution_time = 1 ;

SET max_execution_time = 1

Ok.

0 rows in set. Elapsed: 0.001 sec.

xxx :) select sleep(3);

SELECT sleep(3)

┌─sleep(3)─┐
│        0 │
└──────────┘

```

**Comment by jackpgao** [comment]
```sql
xxx :) set max_execution_time = 1 ;

SET max_execution_time = 1

Ok.

0 rows in set. Elapsed: 0.001 sec.

xxx :)
xxx :) select sleep(3);

SELECT sleep(3)

┌─sleep(3)─┐
│        0 │
└──────────┘

1 rows in set. Elapsed: 3.001 sec.

xxx :) select version();

SELECT version()

┌─version()─┐
│ 20.4.3.16 │
└───────────┘

```

**Comment by tavplubix** [comment]
@jackpgao, it is a known issue. Query can be killed or cancelled only in some points between processing of blocks in pipeline, where query checks elapsed time and some flags to determine if it should stop the execution. Query cannot check it when sleeping on row processing.
