### ISSUE TITLE
How to build the aarch64v80compat version of ClickHouse (based on ARMv8.0, rather than ARMv8.2)?

### ISSUE THREAD

**Issue by honobi** [ClickHouse/ClickHouse#70927]
### Question

How to build the aarch64v80compat version of ClickHouse (based on ARMv8.0, rather than ARMv8.2)?
If I build directly on a machine that only supports ARMv8.0, will the result be the aarch64v80compat version?

**Comment by Algunenano** [comment]
cmake with (adjust paths)
```
cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/linux/toolchain-aarch64.cmake -DNO_ARMV81_OR_HIGHER=1
```

The toolchain is optional if you are already building in an ARM machine, but the second one is the one defining the arch of the binary and it will default to arm 8.2 if not passed.
