### ISSUE TITLE
storage config: s3 endpoint parser failed 

### ISSUE THREAD

**Issue by saborforly** [ClickHouse/ClickHouse#70948]
**Describe what's wrong**
When the storage configuration use s3 and endpoint value is like this:
  http://bucket_name.cos.region.cos.domain

clickhouse_server will get error like this : Host not found cos.domain. we really dont have the Host, but we have cos.region.cos.domain.

**How to reproduce**

* Which ClickHouse server version to use: 21.8.15.7
* Which interface to use, if it matters: Mysql Shell
* Non-default settings, if any storage.xml configuration like this: 
```
<yandex>
  <storage_configuration>
    <disk>
      <cold_disk>
        <type>s3</type>
        <endpoint>http://bucket_name.cos.region.cos.domain</endpoint>
        <access_key_id>youId</access_key_id>
        <secret_access_ket>youKey</secret_access_ket>
      </cold_disk>
    </disk>
    <policies>
      <hot_to_cold>
        <volumes>
          <hot>
            <disk>default</disk>      
          </hot>
          <cold>
            <disk>cold_disk</disk>      
          </hot>
        </volumes>
        <move_factor>0.2</move_factor>
      </hot_to_cold>
    </policies>
  </storage_configuration>
</yandex>
```

* Sample data for all these tables, use ssb-dbgen(db_bench)
* the storage configuration will trigger some error, we can see these errors from clickhouse_server.log

**Expected behavior**

> A clear and concise description of what you expected to happen.

Error message: Poco::Exception: Code: 1000, e.code=0, e.displayText()= Host not found cos.domain

**Comment by nickitat** [comment]
current master produces the same error. if you want support for this endpoints to be added pls provide reference to the docs, we need uri format, how to match them to endpoints to access data and so on

**Comment by Felixoid** [comment]
@saborforly feel free to reopen if the `URI` format is provided
