### ISSUE TITLE
Missed validation in CountIf

### ISSUE THREAD

**Issue by aaa-user** [ClickHouse/ClickHouse#7095]
**Describe the bug or unexpected behaviour**
Aggregate function combinator 'If' used with 'Count' -> 'CountIf'. When our user put in arguments for CountIf 3 parameters like CountIf (a , b=c, d=e) it somehow works, but should't do It. The user received an incorrect result on the request.

Documentation https://clickhouse.yandex/docs/en/query_language/agg_functions/combinators/#agg-functions-combinator-if doesn't contain formulations like CountIf (a , b=c, d=e)

**Expected behavior**
We've recommended him to use record like CountIf (a , b=c and d=e) and then user got correct result. Please add a validation with text like  Exception: Aggregate function CountIf require two arguments"

**Comment by aaa-user** [comment]
Version of ClickHouse 19.9.2.4

**Comment by alexey-milovidov** [comment]
Current behaviour of function count is:
- accept any number of arguments and count how many times no arguments were NULL.

I checked that MySQL and PostgreSQL allows only single argument for function count:
http://sqlfiddle.com/#!17/0a28f/264

So, we can also allow only single argument or zero number of arguments. In this case, the `countIf` will accept only single or two arguments.

**Comment by Vdimir** [comment]
> So, we can also allow only single argument or zero number of arguments. In this case, the `countIf` will accept only single or two arguments.

Some tests uses `count` with 2 arguments, e.g [00425_count_nullable.sql](https://github.com/ClickHouse/ClickHouse/blob/6f758babf6912b7ecb5424b2e669b943c588317f/dbms/tests/queries/0_stateless/00425_count_nullable.sql#L4):
```
SELECT count(x, y) FROM (SELECT number AS x, number AS y FROM system.numbers LIMIT 10);
```

**Comment by alexey-milovidov** [comment]
Yes, we can remove support for this feature (and place a note about backward compatibility in changelog).
