### ISSUE TITLE
Improve internal logging API.

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#7096]
This is a meta-issue to track possible improvements of this API.

1) Have a logging function that only takes a message, and requires no additional arguments. LOG_TRACE that we have now requires you to specify some Logger, and it is totally not obvious where you get one. Many classes have a logger field, and some get the logger by name from some global function. All this is very cumbersome, and most of the time, I don't care about this, I just want to log to some current context, whatever it is. Logging should be as easy as possible, so that developers do not hesitate to add more trace logs, which are very important for debugging.

2) Switch to a printf-like format strings. Two reasons:
- the C++ stream thing we use now becomes impossible to read after it has more than a couple parameters. 
- format strings allow to compress/parse logs better: in `system.text_log`, we will be able to store the format string as LowCardinality(String), and store the parameters separately. This improves compression and allows performing more rich queries on logs, e.g. filter on a parameter value.

**Comment by abyss7** [comment]
I insist on supporting C++ streaming (maybe alongside with formatted strings), since it's much simpler to implement global `operator<<` for any custom structures and print them in a simple manner.

**Comment by alexey-milovidov** [comment]
> 1. Have a logging function that only takes a message

Ok.

> 2. Switch to a printf-like format strings.

Ok. The main reason is log compression proposed by @4ertus2 (exactly what you described).
Not with printf-like format strings but with python/boost::format/fmt-like format strings.
Formatting can continue to work via calling of `operator<<` internally.

**Comment by akuzm** [comment]
> I insist on supporting C++ streaming (maybe alongside with formatted strings), since it's much simpler to implement global `operator<<` for any custom structures and print them in a simple manner.

Printing custom structures with printf is not different, only you implement toString instead of operator<<. Performance-wise, it's probably worse, because you can't use some sort of string builder, but it's logging so we probably don't care.

Not that I'm against supproting <<, it shouldn't be difficult.

**Comment by abyss7** [comment]
I already made a prototype one day, but removed it later.

The API I suggest is as follows.

Implement some base tempate-class that provides all logging facilities and derive all other classes from it.

The syntax should be like:

```
LOG(WARN) << "some warning: " << additional_info;
LOG(INFO) << "useful formatted info: %d" << good_number;
LOG(FATAL) << "exit server now because " << ("formatted string %f"_f << number) << not_formatted_part;
DLOG(ERROR) << "something bad has happened, but in debug build only";
```

**Comment by alexey-milovidov** [comment]
> The syntax should be like

It doesn't support lazy evaluation of arguments (no evaluation when logging is disabled).

**Comment by amosbird** [comment]
P.S. C++20 will have std::format https://fmt.dev/Text%20Formatting.html

**Comment by alexey-milovidov** [comment]
That's exactly what we need.

**Comment by akuzm** [comment]
https://github.com/ClickHouse/ClickHouse/pull/7208

**Comment by akuzm** [comment]
Part 2 is done in https://github.com/ClickHouse/ClickHouse/pull/11137 and further.

**Comment by azat** [comment]
Any plans on doing the same for `DB::Exception`?

**Comment by alexey-milovidov** [comment]
@azat Yes, it's also done:  #11446

**Comment by alexey-milovidov** [comment]
@akuzm You may consider migrating to https://github.com/gabime/spdlog
I will close this task and we can specify what is remaining in a new task.
