### ISSUE TITLE
Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION java.lang.NoClassDefFoundError: org/apache/hc/client5/http/config/ConnectionConfig at

### ISSUE THREAD

**Issue by rahulraka** [ClickHouse/ClickHouse#70967]
### Company or project name

Personal Project

### Question

Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION java.lang.NoClassDefFoundError: org/apache/hc/client5/http/config/ConnectionConfig at

   <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>5.0.3</version>
        </dependency>

        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.6.1</version>
        </dependency>
        getting classnotfound exception when using these two dependencies simultaneouly, seems like compatibility issue.
        Can anyone helo here

**Comment by Algunenano** [comment]
Hi, please report issues related to the java client to https://github.com/ClickHouse/clickhouse-java
