### ISSUE TITLE
clickhouse benchmark <<< "SELECT now()" does not work on master

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7100]

**Comment by den-crane** [comment]
for search:

Code: 171. DB::Exception: Received from localhost:9000. DB::Exception: Cannot convert column ... because it is constant but values of constants are different in source and result.

workaround for now() -> materialize(now())

Issues persists at least in 19.14.6.12 stable.

**Comment by WesleyBatista** [comment]
I am running a query on top of a CSV file using clickhouse-local and experienced this problem. 
```
Code: 44, e.displayText() = DB::Exception: Cannot convert column `now64()` because it is constant but values of constants are different in source and result (version 20.12.5.14 (official build))
```

command is like this:
```
        clickhouse-local \
                --input-format=CSVWithNames \
                --input_format_allow_errors_num=2 \
                --table=$table \
                --input_format_with_names_use_header=0 \
                --format_csv_delimiter=";" \
                --structure="$table_schema_compat" \
                --query="$local_query_compat" < "$filename"
```
Using `materialize(now64())` did the trick for me :+1:

**Comment by alexey-milovidov** [comment]
@KochetovNicolai `now64` function should use FunctionBuilder in the same way as `now`.

**Comment by alexey-milovidov** [comment]
Fixed.
