### ISSUE TITLE
Segfaults when running Oracle Linux 6.9

### ISSUE THREAD

**Issue by op** [ClickHouse/ClickHouse#71017]
**Describe what's wrong**

The upcoming [Oracle Linux's][uek] version of the kernel makes the server segfault.

```bash
docker run clickhouse/clickhouse-server:latest
[..]
AT_* is out of range: 71 (maximum allowed is 64)
Aborted                 (core dumped)
```

The Linux UEK 6.8 seem to work fine. 6.11 on Arch seems fine too.

| Distro | Kernel | Works
| -- | -- | -- |
| OL | 6.10 | :boom: |
| OL | 6.9 | :boom: |
| OL | 6.8 | :heavy_check_mark:  |
| OL | 5.15 | :heavy_check_mark: 
| Ubuntu | 6.8 | :heavy_check_mark: |
| Arch | 6.11 | :heavy_check_mark: 

[uek]: https://github.com/oracle/linux-uek

**Comment by Algunenano** [comment]
It seems this should be reported to Oracle, which is who made the changes to the kernel and broke compatibility. Maybe they can explain what changes are required in userspace to support this change

**Comment by op** [comment]
That sounds fair. I reported the issue here: https://github.com/oracle/linux-uek/issues/29

Pushed a PR to make it work on the upcoming version of Oracle Linux.
