### ISSUE TITLE
optimize_read_in_order does not recognize that prefix is already sorted

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#7102]
create table ORX( A Int64, B Int64, V Int64) Engine=MergeTree order by (A,B)
insert into ORX select 111, number, number from numbers(10000000)

select * from ORX where **A = 111 order by B** limit 3;
3 rows in set. Elapsed: 0.232 sec. **Processed 10.00 million rows**

select * from ORX where **A = 111 order by A,B** limit 3;
3 rows in set. Elapsed: 0.019 sec. **Processed 245.76 thousand rows,**

**Comment by orloffv** [comment]
no updates?
