### ISSUE TITLE
Insert data error,  Cannot set modification time to file.

### ISSUE THREAD

**Issue by MamyAKKK** [ClickHouse/ClickHouse#71048]
### Question

My stack file : (it's working)
`
> version: "3.8"
> 
> services:
>   server:
>     ulimits:
>       nproc: 65535
>       nofile:
>         soft: 262144
>         hard: 262144
>     image: <my-repo>/clickhouse-server:24.3.12-alpine
>     networks:
>       - app-net
>     ports:
>       - target: 8123
>         published: 8123
>       - target: 9000
>         published: 9000
>     volumes:
>       - clickhouse-nas:/var/lib/clickhouse
>     environment:
>       CH_SHARD: S01
>       CH_REPLICA: R01
>     cap_add:
>       - SYS_NICE
>       - NET_ADMIN
>       - IPC_LOCK
>     deploy:
>       mode: replicated
>       replicas: 1
>       resources:
>         limits:
>           memory: 40960M
>         reservations:
>           memory: 10240M
> 
> volumes:
>   clickhouse-nas:
>     driver: local
>     driver_opts:
>       type: "cifs"
>       device: "//<nas-server>/olap/clickhouse/server"
>       o: "addr=<nas-server>,username=<user>,password=<password>,file_mode=0777,dir_mode=0777"
`

Table DDL : (it's working)

> create table test on cluster `cluster-in-replica`(
>    id UInt64 not null,
>    name String not null ,
>    sex FixedString(1) not null,
>    create_time DateTime64(0) not null,
>    create_time_long UInt64 not null 
> ) 
> ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test', '{replica}')
> PRIMARY KEY(id,create_time_long)

Data Insert : (It's wrong)
`
> insert into test(id,name,sex,create_time,create_time_long)values(7248304245097762847,'alex','M','2024-10-25 11:17:48',1729826268106);
`

Error Message :
`
Code: 481. xxx: Cannot set modification time to file:xxx,errno:1,strerror:Operation not permitted. (PATH_ACCESS_DENIED)
`

Who can help me ? What can i fix ??

**Comment by MamyAKKK** [comment]
I can create table & desc table , but can't insert data in table~

**Comment by Algunenano** [comment]
This looks like a docker issue. I'm guessing you are using some odd volume for storage, probably with WSL.

**Comment by MamyAKKK** [comment]
Actually, I am using an enterprise NAS service to store data. But, I don't know how to confirm if it's an issue with the NAS service format. Because it has no problem storing data from other services, such as Registry Distribution, Zookeeper, etc.

**Comment by MamyAKKK** [comment]
This NAS service has been used for shared storage of our internal containers. Do Clickhouse have any special requirements for NAS storage formats?

**Comment by MamyAKKK** [comment]
Discover an important difference , 
Old mount use CIFS [ https://docs.docker.com/engine/storage/volumes/#create-cifssamba-volumes ] . It's incorrect~
New mount use NFS [ https://docs.docker.com/engine/storage/volumes/#create-a-service-which-creates-an-nfs-volume ]  . It's correct ~
I think the above problem is caused by this reason , But who can tell me more details ~
