### ISSUE TITLE
FreeBSD memory "leak" 

### ISSUE THREAD

**Issue by snar** [ClickHouse/ClickHouse#71051]
**Describe what's wrong**

After about a week clickhouse starts complaining on "I'm out of memory" and refuses
to process further queries. Logs are like the following:

2024.10.23 13:36:04.216940 [ 139705 ] {} <Error> MergeTreeBackgroundExecutor: Exception while executing background task {cde850fc-3e14-4e0a-8de8-50fc3e14de0a::20241019_6519227_6525974_342}: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 25.54 GiB (attempt to allocate chunk of 4663939 bytes), current RSS 25.54 GiB, maximum: 17.97 GiB. OvercommitTracker decision: Memory overcommit isn't used. Waiting time or overcommit denominator are set to zero. (MEMORY_LIMIT_EXCEEDED)

Root cause seems to be simple: 
- FreeBSD uses jemalloc, so memory_worker is initialized with Jemalloc source:
https://github.com/ClickHouse/ClickHouse/blob/26f2c5b07b2cfbbe379ed0ac402bf9160e3a279c/programs/server/Server.cpp#L1057

- AsynchronousMetrics assumes that RSS will be updated by memory_worker and initialized with update_rss set to false (source is not None): https://github.com/ClickHouse/ClickHouse/blob/26f2c5b07b2cfbbe379ed0ac402bf9160e3a279c/programs/server/Server.cpp#L1079

- memory_worker.start() is not called because it's not OS_LINUX:
 https://github.com/ClickHouse/ClickHouse/blob/26f2c5b07b2cfbbe379ed0ac402bf9160e3a279c/programs/server/Server.cpp#L1255
https://github.com/ClickHouse/ClickHouse/blob/26f2c5b07b2cfbbe379ed0ac402bf9160e3a279c/programs/server/Server.cpp#L1356

As a result, RSS is not updated at all and clickhouse thinks that it uses much more memory that it actually does.

Found in ClickHouse local version 24.10.1.1405 (official build), still present in master.

PS: Looks like Darwin builds are affected too: they are also jemalloc-based and not Linux.

**Comment by gch1p** [comment]
I have similar issue, although I use older version 22.1.3.1 from the ports.
```
2024.10.24 00:28:50.539969 [ 113002 ] {} <Error> void DB::MergeTreeBackgroundExecutor<DB::MergeMutateRuntimeQueue>::routine(DB::TaskRuntimeDataPtr) [Queue = DB::MergeMutateRuntimeQueue]: Code: 241. DB::Exception: Memory limit (total) exceeded: would use 249.63 GiB (attempt to allocate chunk of 4250344 bytes), maximum: 230.26 GiB. (MEMORY_LIMIT_EXCEEDED)

```
