### ISSUE TITLE
Where can I find the official list of supported LTS versions?

### ISSUE THREAD

**Issue by patsevanton** [ClickHouse/ClickHouse#71075]
### Question

Hello ClickHouse Team,

I would appreciate it if you could provide the following information:

Where can I find the official list of supported LTS versions?

Thank you in advance for your assistance!

**Comment by Algunenano** [comment]
You can find it in https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md. At any time there are 2 supported LTS releases, right now that would be 24.8 and 24.3.
