### ISSUE TITLE
AWS Credentials should support AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE.

### ISSUE THREAD

**Issue by patrickdash** [ClickHouse/ClickHouse#71074]
**Describe the unexpected behaviour**

The current AWS environment variable credential look up only supports reading the Authorization header from `AWS_CONTAINER_AUTHORIZATION_TOKEN`.  However, EKS Pod Identity webhooks now inject the token via a file, whose path is provided in `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` (https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html).

**How to reproduce**
* Which ClickHouse server version to use: 24.9.2 and attempt to access S3 with a Clickhouse pod using EKS Pod Identity.

**Expected behavior**
Clickhouse will also use `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` to properly authorize its requests to `AWS_CONTAINER_CREDENTIALS_FULL_URI`.

**Comment by devunt** [comment]
This issue is not resolved. A valid environment variable name is `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE`, but in the PR it reads `AWS_CONTAINER_AUTHORIZATION_TOKEN_PATH` instead, which is not used in anywhere (https://www.google.com/search?q=AWS_CONTAINER_AUTHORIZATION_TOKEN_PATH)

**Comment by thevar1able** [comment]
Sorry @devunt, let me fix it once again
