### ISSUE TITLE
ARM64 Clickhouse High memory usage

### ISSUE THREAD

**Issue by isFxh** [ClickHouse/ClickHouse#71107]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When I used the clickhouse-22.8.9.24-alpine version of the docker arm64 image, there was less than 200M of data in clickhouse. When I started clickhouse, the memory usage was about 7G, but the memory continued to grow. I adjusted the container's memory limit to 64G, and the maximum memory used by clickhouse was configured to 32G. However, the memory of clickhouse increased from 7G to 63G within 1 hour, which eventually caused clickhouse to shut down abnormally and fail to provide services.

my runtime env
docker-compose file
![image](https://github.com/user-attachments/assets/518e38d1-e902-4d1e-9694-0b0ee668d032)

docker info
![image](https://github.com/user-attachments/assets/c9deb1d8-3181-4933-8901-869d4ff1589c)

### Expected behavior

When the amount of ClickHouse data is small, the memory usage should be less than 3G. I ran the same version of ClickHouse on an X86_64 server and this did not happen.

### Screenshots

![image](https://github.com/user-attachments/assets/e71709a6-16df-4efd-8a20-93494136e23b)
![image](https://github.com/user-attachments/assets/afaff3b2-cf85-4aa1-8b1a-4c0dae7da94a)
![image](https://github.com/user-attachments/assets/8416544d-4ef5-4dda-9b7c-c72e8dc37b2e)

### Environment

```markdown
- OS: openEuler 20.03 (LTS-SP3)
- ARCH: arm64
- Runtime: Docker
```

**Comment by den-crane** [comment]
22.8 is out of support,  you need to upgrade to supported version, try 24.8

Also Kernel Version 4.19 is suspiciously old.

**Comment by isFxh** [comment]
> 22.8 is out of support, you need to upgrade to supported version, try 24.8
> 
> Also Kernel Version 4.19 is suspiciously old.

@den-crane Thank you for your reply. I have another arm64 environment. The underlying runtime is Kubernetes. Click House is deployed using altinity clickhouse-operator. The same operating system (openEuler 20.03 LTS-SP3) and kernel version (4.19) are used. Clickhouse v24 is used. The memory usage is not very high. Could this be related to docker?
![image](https://github.com/user-attachments/assets/5304e08e-e4e6-4bea-b7de-b463ca19e1cf)
![image](https://github.com/user-attachments/assets/f8022b16-5635-41e5-9f58-88646406a5e8)
![image](https://github.com/user-attachments/assets/087a3d4d-851d-4aa2-9e21-58e39240d143)

**Comment by isFxh** [comment]
I tried 6.x version of the Linux kernel, launching clickhouse v22 and v24 versions through docker. There is currently no problem of excessive memory usage. I will continue to observe whether the above phenomenon will occur again.
![image](https://github.com/user-attachments/assets/e4ffd218-3dc6-4b23-8032-858c8ff560c2)
![image](https://github.com/user-attachments/assets/725114ef-e1b2-4fce-b9ed-05a44098575f)

**Comment by alexey-milovidov** [comment]
> altinity clickhouse-operator

This is not supported.

**Comment by huyouba1** [comment]
I have the same question。
docker image: clickhouse/clickhouse-server:24.5.8.10-alpine

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/b7520d34-ddb7-4728-85ed-fa354bd9b5c6" />
<img width="730" alt="image" src="https://github.com/user-attachments/assets/fe916dde-0f89-49f9-adc2-bd924b8fd97d" />

**Comment by huyouba1** [comment]
> I tried 6.x version of the Linux kernel, launching clickhouse v22 and v24 versions through docker. There is currently no problem of excessive memory usage. I will continue to observe whether the above phenomenon will occur again. ![image](https://private-user-images.githubusercontent.com/58544359/380991220-e4ffd218-3dc6-4b23-8032-858c8ff560c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NzQwNjcsIm5iZiI6MTczNDU3Mzc2NywicGF0aCI6Ii81ODU0NDM1OS8zODA5OTEyMjAtZTRmZmQyMTgtM2RjNi00YjIzLTgwMzItODU4YzhmZjU2MGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAyMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NDc4MjgzYzEzZDI3MzZjZGQ0YWQwNjYwNmI2MTgxMjk0MGQwNWM3MjM2NTdmZDgxNjEyODY3ZjExZDBlODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.APFakUx7pIAP9-bKUAyxxj7PIDV7Iy3BncoGP4FtKkQ) ![image](https://private-user-images.githubusercontent.com/58544359/380991424-725114ef-e1b2-4fce-b9ed-05a44098575f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NzQwNjcsIm5iZiI6MTczNDU3Mzc2NywicGF0aCI6Ii81ODU0NDM1OS8zODA5OTE0MjQtNzI1MTE0ZWYtZTFiMi00ZmNlLWI5ZWQtMDVhNDQwOTg1NzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAyMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDNiNGU1MDM3ZWUwMDk5YjI3NTk0MWE3N2I0MTdlOTUxMmNjZDRjN2Q5NzAzOTU0MzVkZTZlOTI4ZTUyZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w5SL-F5xGxd8b5jJOz-ic4P2GRVvItTpnmW7DsXXHRU)

Hello brother, can you provide the upgraded kernel?
