### ISSUE TITLE
An error occurred while cross-compiling ClickHouse.

### ISSUE THREAD

**Issue by honobi** [ClickHouse/ClickHouse#71131]
### Question

clickhouse branch：22.12
clang version 17.0.6
ninja version 1.8.2

The error occurred while trying to cross-compile ClickHouse for ARM machines on an x86 architecture：
---
ClickHouse/src/QueryPipeline/RemoteQueryExecutor.cpp:496:49: error: invalid operands to binary expression ('const SettingFieldSeconds' (aka 'const SettingFieldTimespan<SettingFieldTimespanUnit::Second>') and 'Poco::Timespan')
  496 |     if (context->getSettingsRef().drain_timeout != Poco::Timespan(-1000000))
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~
/root/ClickHouse/src/Client/ConnectionPool.h:191:13: note: candidate function not viable: no known conversion from 'const SettingFieldSeconds' (aka 'const SettingFieldTimespan<SettingFieldTimespanUnit::Second>') to 'const ConnectionPoolFactory::Key' for 1st argument
  191 | inline bool operator==(const ConnectionPoolFactory::Key & lhs, const ConnectionPoolFactory::Key & rhs)
---

**Comment by Algunenano** [comment]
22.12 is not supported anymore.

**Comment by alexey-milovidov** [comment]
You are using the version of clang that didn't exist at the time of release 22.12.

**Comment by honobi** [comment]
> You are using the version of clang that didn't exist at the time of release 22.12.

Where can I find the correspondence between the Clang version and the ClickHouse version?

**Comment by alexey-milovidov** [comment]
In the git history of the CI, related to Docker images: https://github.com/ClickHouse/ClickHouse/commits/master/docker/test/util/Dockerfile
