### ISSUE TITLE
Distributed table over parameterized view

### ISSUE THREAD

**Issue by tanner-bruce** [ClickHouse/ClickHouse#71158]
### Question

Is it possible to have a distributed table across a parameterized view? It works fine for a view with no params but I am unable to find how to do it for a parameterized one

https://fiddle.clickhouse.com/4f45f64d-f078-41c8-a3a5-0c66276994f3

We have tables like `lookup_sep` with varying `pk_*` columns and want to query across them all from a single place, something like `time_ranges_all` but as a distributed table

**Comment by Felixoid** [comment]
What is the replicated/sharded table in this case? Does `logs` contain only part of the data? Or `lookup_sep` is the sharded data?

Anyway, I feel like you rather want to build a `VIEW` on top of `Distributed` table, that looks on the  `lookup_sep`. Is it like that?

**Comment by tanner-bruce** [comment]
We have multiple `logs` tables, each with slightly different primary keys. The `lookup_sep` table is specific to each - it contains a mapping of IDs to time ranges, as well as the unique primary key values for that `logs` table. So in the fiddle I linked, `component` and `entrypoint` are the fields, so we have `pk_component` and `pk_entrypoint` in the `lookup_sep` table.

The (local) view is to transform queries to `lookup_sep` to handle the specific `pk_<..>` fields for each instance of `lookup_sep`, specifically line 55 in the fiddle is what changes across `logs` tables, so on any given node you could query the view while passing the `ID` parameter. My desire here is to have a distributed view I can give the ID, and have it query each local view so I don't need to know about the `pk_<..>` fields on each local table, they just get returned as map entries

**Comment by Felixoid** [comment]
What about having a local `VIEW` on top of `Distributed` tables for `lookup_sep`?

You want to have an entry point for the parametrized query, right? So, the scheme you're talking about 

```
--- -> for the data flow
logs_x tables -> MV -> `lookup_sep_x`;
view_x OVER lookup_sep_x
view_all OVER view_x
```

And somehow, you want to have Distributed in the scheme. A proper point for the `Distributed` I see here is `local view_x OVER Distributed OVED lookup_sep_x`. So you'd have the `view_x` and `view_all` on each node.
