### ISSUE TITLE
Dictionary: Use Backslash in connection string

### ISSUE THREAD

**Issue by nicolasblaye** [ClickHouse/ClickHouse#7117]
I have defined a dictionary using an odbc driver (mssql). We have multiple instance in the server, and we took the default one before and it was working
`<connection_string>DSN=ServerName;UID=username;PWD=pwd</connection_string>`

We wanted to use the proper instance for the cache, so we changed it to
`<connection_string>DSN=ServerName\InstanceName;UID=username;PWD=pwd</connection_string>`

and I got an error with
```SQLSTATE = IM002
Native Error Code = 0
[unixODBC][Driver Manager]Data source name not found, and no default driver specified
```

I can connect via dbeaver so I know that the name, username or password are correct. I wonder if this is because of the `\` but I can't find anything in the doc, either clickhouse or odbc to fix that. I try to escape it using `\\`but it didn't work either
Is there a way to use an instance name?

**Comment by alexey-milovidov** [comment]
Maybe it's an issue with `unixodbc` library. It need further investigation.
We need to check:
- how the connection string is being passed to unixodbc;
- what DSN is searched inside `unixodbc`.

**Comment by alexey-milovidov** [comment]
BTW, do you literally have `ServerName\InstanceName` in your odbc.ini or the backslash has some special meaning?

**Comment by nicolasblaye** [comment]
Yes we have \ in the name. It works when we connect via dbeaver or ssm.
I need to try without backlash but I doubt it will work

**Comment by alexey-milovidov** [comment]
Would it help if you write

`DSN={ServerName\InstanceName};UID=username;PWD=pwd`

(name in curly braces)

**Comment by nicolasblaye** [comment]
Will try that tomorrow :)

**Comment by nicolasblaye** [comment]
Sorry for the delay. It doesn't work with the data source name not found error

**Comment by filimonov** [comment]
Please start debugging with `isql` command line tool (provided as a part of unixODBC): https://www.easysoft.com/blog/isql-connection-string.html

About mssql: not all authentication options work properly from linux - check that:
* https://stackoverflow.com/a/57732870
* https://askubuntu.com/q/167491
* https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-2017

**Comment by blinkov** [comment]
@nicolasblaye, do you have any further questions?

**Comment by nicolasblaye** [comment]
@blinkov didn't have time to look at it, and we finally went around it. Thank you
