### ISSUE TITLE
Ability to Split large parts into smaller parts so that they will get picked up for merging for deduplication/LWD deletion.

### ISSUE THREAD

**Issue by shribigb** [ClickHouse/ClickHouse#71196]
In case of ReplacingMergeTree table or if Lightweight Deletes are run on the table, CH doesn't pick up parts that are already close to `max_bytes_to_merge_at_max_space_in_pool` for merging. This can lead to a lot of stale duplicates or marked deleted data in the table. The alternative is to run OPTIMIZE FINAL or increase `max_bytes_to_merge_at_max_space_in_pool` so that these parts can get picked up for merging, which makes things worse with the part sizes. 

Proposal 1: An ability to split the parts into smaller-sized parts so that they can get picked up for merging using SYSTEM Command. 
Proposal 2: A setting to limit the part size once the merge is finished. Parts will be picked up for merging up to `max_bytes_to_merge_at_max_space_in_pool`, but when the merging is done, the parts will be split up to the size limit set by this setting.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/56728

https://github.com/ClickHouse/ClickHouse/pull/58223

https://clickhouse.com/docs/en/operations/settings/merge-tree-settings#exclude_deleted_rows_for_part_size_in_merge

**Comment by shribigb** [comment]
@den-crane thank you for those links. 

This is useful for LWD but is still not foolproof. If the number of deleted rows is not enough for the part to be picked up for merging, these stale rows will stay in the part for a very long time.

Also, it will not work for ReplacingMergeTree.
