### ISSUE TITLE
HTTP Interface Does not have a provision to pass custom delimiters (dsv) in CSV

### ISSUE THREAD

**Issue by ashrith** [ClickHouse/ClickHouse#7121]
Currently, the clickhouse-client interface seems to have a flag to pass custom delimiters. 

`--format_csv_delimiter="|"`

And using that one can upload the data to clickhouse using clickhouse-client interface as follows

`clickhouse-client --format_csv_delimiter="|" --query="insert into alarm.alert_table format CSVWithNames" --password $1 < alarm_alert.txt`

But the same provision is not available (or not documented) when using the HTTP Interface. When you try to run it you end up getting a parsing error (which clearly seems to be from the delimiter)

```
$ cat alarm_alert.txt |POST 'http://localhost:8123/?query=insert into alarm.alert_table format CSVWithNames'
Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected , before: \ncomm|0.43||0|0||High Volume Historical Profile |3|150863588|1456943665|w|aml_100702|16863|n|0\ncomm|0.65||0|0|| Prof (version 19.14.6.12 (official build))
```
The delimiter we are using here is a `|`

**Comment by den-crane** [comment]
http://localhost:8123/?format_csv_delimiter="|"&query

`echo "1;2"|curl 'http://localhost:8123/?format_csv_delimiter=;query=INSERT%20INTO%20test.csv_stream%20format%20CSV' --data-binary @-`

**Comment by ashrith** [comment]
@den-crane thank you! Could this be a part of the documentation so that others who might be seeking this information is easily available?
