### ISSUE TITLE
Why is the ClickHouse binary file I built as large as 2.9 GB?

### ISSUE THREAD

**Issue by honobi** [ClickHouse/ClickHouse#71226]
### Question

<img width="315" alt="截屏2024-10-30 11 11 05" src="https://github.com/user-attachments/assets/41bba990-1ae5-44ac-803c-8dac7f119e5a">

The ClickHouse binary files released are only a few hundred megabytes. Why is the binary I built myself so large?
I cross-compiled a ClickHouse for ARM machines on an x86 machine, using the ARMv8.0 standard.

clickhouse branch: 23.8
clang: 16

### Build operation
```
cd ClickHouse
mkdir -p build-aarch64/cmake/toolchain/linux-aarch64

wget 'https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz?revision=2e88a73f-d233-4f96-b1f4-d8b36e9bb0b9&la=en' -O gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz

tar xJf gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz -C build-aarch64/cmake/toolchain/linux-aarch64 --strip-components=1

git submodule update --init

cmake . -Bbuild-arm64 -DCMAKE_TOOLCHAIN_FILE=cmake/linux/toolchain-aarch64.cmake -DNO_ARMV81_OR_HIGHER=1

ninja -C build-arm64

**Comment by alexey-milovidov** [comment]
It contains debug information. You can split or remove the debug information in the same way as it is done in the official continuous integration scripts.

**Comment by alexey-milovidov** [comment]
@zhangguanzhang, don't compile ClickHouse by yourself, use only official binaries.
