### ISSUE TITLE
system.part_log can not be created 

### ISSUE THREAD

**Issue by jackpgao** [ClickHouse/ClickHouse#7123]
The `system.part_log` table was not created on version `19.14.6.12` even with the following config.

```
  <part_log>
    <database>system</database>
    <table>part_log</table>
    <partition_by>toYYYYMM(event_date)</partition_by>
    <flush_interval_milliseconds>7500</flush_interval_milliseconds>
  </part_log>
```

No related logs.

**Comment by millb** [comment]
I can't detect the problem.  Are you sure that it isn't solved in this way?
> The `system.part_log` table is created after the first inserting data to the `MergeTree` table.

**Comment by alexey-milovidov** [comment]
@millb Thank you for the investigation! Can we add integration test that will check that the part_log is created?
