### ISSUE TITLE
indexOf() is not working for Array(LowCardinality(String))

### ISSUE THREAD

**Issue by kamilHipsz** [ClickHouse/ClickHouse#71257]
ClickHouse 24.8.5.115 LTS

```
SHOW CREATE TABLE system.query_log

CREATE TABLE system.query_log
(
...
    `Settings.Names` Array(LowCardinality(String)) ALIAS mapKeys(Settings)
...
```

`SELECT indexOf(ProfileEvents.Names, 'UserTimeMicroseconds')
FROM system.query_log
LIMIT 1`

Throws an error:

**DB::Exception: Invalid column type for ColumnUnique::insertRangeFrom. Expected String, got ColumnLowCardinality. (ILLEGAL_COLUMN)**

Worked fine on previous versions.

**Comment by Algunenano** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/issues/71256. Workaround, disable `optimize_functions_to_subcolumns`.
