### ISSUE TITLE
[deduplication] having both replica set feature and repeated data insertion simultaneously

### ISSUE THREAD

**Issue by mofard** [ClickHouse/ClickHouse#7126]
In my plan, I want to put many logs into clickhouse cluster.  I would have both repeated logs and replica set.
I have used both MergeTree and ReplicatedMergeTree engines separately. In first one, I can have repeated records but replica doesn’t work. 
In second one, replica set works properly, but I couldn’t find any way to have repeated log records because of deduplication.
Would you please give me some piece of advice?

**Comment by den-crane** [comment]
Deduplication works for blocks. 

So if your blocks / batches completely the same (though it's super unusual) you can add some fake column to your table (batchID UUID) to break deduplication. And add fill this column with uuid (the same uuid for whole insert). 

Or can disable deduplication. Just set insert_deduplication=0 in your SQL API.
