### ISSUE TITLE
Possible API for GraphQL

### ISSUE THREAD

**Issue by nwmcsween** [ClickHouse/ClickHouse#7127]
**Use case**
GraphQL Queries

**Describe the solution you'd like**
A suitable API to do subscriptions, etc similar to Hasura, Postgrest, etc.

**Describe alternatives you've considered**
A mess of backend stuff on top of Clickhouse that uses the HTTP API.

**Comment by filimonov** [comment]
https://github.com/bitquery/activecube-graphql

**Comment by alexey-milovidov** [comment]
Let's keep it in mind...
