### ISSUE TITLE
Can storage policies be configured using SQL in version 23.8?

### ISSUE THREAD

**Issue by zxl-wangwang** [ClickHouse/ClickHouse#71337]
### Question

Question 1: 

Storage configuration without predefined disks can be specified in the configuration file, which can then be configured at creation time using SQL.

<img width="798" alt="截屏2024-11-01 14 19 36" src="https://github.com/user-attachments/assets/186ec247-9734-4b10-8298-6babb18401bb">

But how to bind the storage policy through SQL and disk configuration in version 23.8?

**Comment by zxl-wangwang** [comment]
Questions 2:

```
<policies>
   <s3_main>
       <volumes>
           <main>
               <disk>s3</disk>
           </main>
       </volumes>
   </s3_main>
   <s3_tiered>
       <volumes>
           <hot>
               <disk>default</disk>
           </hot>
           <main>
               <disk>s3</disk>
           </main>
       </volumes>
       <move_factor>0.2</move_factor>
   </s3_tiered>
</policies>
```

In the above configuration, how do I set move_factor in cache and disk? Am I setting it correctly?

**Comment by melvynator** [comment]
> In the above configuration, how do I set move_factor in cache and disk using SQL? 

It is not possible to do it via SQL. You can only do that via configuration files.
