### ISSUE TITLE
insert_quorum breaks mutations

### ISSUE THREAD

**Issue by vanzi** [ClickHouse/ClickHouse#7133]
We have a problem with `insert_quorum` option as it seems to completely break mutations in a ClickHouse cluster (sharding with replication).

**Describe the bug or unexpected behaviour**
When INSERT queries are performed with `insert_quorum` set to the number of replicas, subsequent `ALTER TABLE ... DELETE` queries will not be finished (or even started, from what the system.mutations logs show).

**How to reproduce**
I've scripted the reproduction steps on the most recent version, 19.13.5.44. Please see https://github.com/vanzi/quorum_issue_repro. It just creates the replicated tables, inserts some data, performs mutation and waits for it to finish (which it seems to never do).

**Expected behavior**
Mutation should finish regardless of the `insert_quorum` parameter.

**Error message and/or stacktrace**
There seems to be no errors in the log, but the mutation does not start to be executed, it just waits in system.mutations table.

**Additional context**
Removing `insert_quorum` param removes the issue entirely. Also it seems that as long as the inserted data is in a single partition (i.e. single month in my case), the issue also does not occur.

**Comment by alesapin** [comment]
Trying to fix here  https://github.com/ClickHouse/ClickHouse/pull/9463/files.

**Comment by alesapin** [comment]
Fix in PR #9463. Will be available in all fresh patch releases.
