### ISSUE TITLE
clickhouse-keeper path gets deleted after ReplicatedMergeTree table recreation

### ISSUE THREAD

**Issue by youfu-fun** [ClickHouse/ClickHouse#71340]
### Question
Clickhouse Version: 24.9.1
Environment:
- ClickHouse cluster with 7 shards, 2 replicas each
- One machine in shard 6 failed and was replaced

Steps to reproduce:
1. Replaced failed machine in shard 6
2. Reconfigured the node and rejoined it to the cluster  (replica = 02)
3. Recreated the table using ZooKeeper path: ``` (' /clickhouse/tables/7e5645d5-6728-4c27-ba8b-b96ba2dcb9bd/06','{replica}')```
4. Table creation succeeded, Exec query ``` SELECT
    database,
    `table`,
    is_leader,
    is_readonly,
    total_replicas,
    active_replicas,
    zookeeper_path,
    queue_size,
    inserts_in_queue,
    merges_in_queue,
    log_max_index,
    log_pointer
FROM system.replicas
WHERE database = 'pro2_signoz_traces'  AND `table` = ''signoz_index_v2'') ```
> total_replicas=2 active_replicas=2
5. After a few minutes, the keeper path (/clickhouse/tables/7e5645d5-6728-4c27-ba8b-b96ba2dcb9bd/06/replicas/02) gets automatically deleted

6. The table still exists in ClickHouse  
> total_replicas=0 active_replicas=0

Questions:
1. What could cause the ZooKeeper path to be automatically deleted while the table remains?
2. How to properly recreate a replicated table after node failure?
Any debug logs or configuration details that would be helpful in diagnosing this issue?

**Comment by panzhilin007** [comment]
By default, ClickHouse will remove the zookeeeper path 480 seconds after you drop the table.

Try to use `drop table tableName sync` instead.

**Comment by youfu-fun** [comment]
> By default, ClickHouse will remove the zookeeeper path 480 seconds after you drop the table.默认情况下，ClickHouse 会在你放表后 480 秒删除 zookeeeper 路径。
> 
> Try to use `drop table tableName sync` instead.尝试改用 `drop table tableName sync`。

Problem solved, thanks ～
