### ISSUE TITLE
NEW JSON DATA TYPE Cannot parse JSON object

### ISSUE THREAD

**Issue by justwdh** [ClickHouse/ClickHouse#71346]
**Describe the unexpected behaviour**
i have use vector clickhouse sink by JSONEachRow ，it worked in version 23.2，but it failed in 24.8 and return 
```shell
DB::Exception: Cannot parse object
```
then i try new json data type in [https://clickhouse.com/docs/en/sql-reference/data-types/newjson](https://clickhouse.com/docs/en/sql-reference/data-types/newjson)
failed again return

```shell
Code: 117. DB::Exception: Cannot parse JSON object here: {"a" : {"b" : 42}, "c" : [1, 2, 3]}: while executing 'FUNCTION if(isNull(-dummy-0) : 3, defaultValueOfTypeName('JSON(`a.b` UInt32, SKIP `a.e`)') :: 2, _CAST(-dummy-0, 'JSON(`a.b` UInt32, SKIP `a.e`)') :: 4) -> if(isNull(-dummy-0), defaultValueOfTypeName('JSON(`a.b` UInt32, SKIP `a.e`)'), _CAST(-dummy-0, 'JSON(`a.b` UInt32, SKIP `a.e`)')) JSON(`a.b` UInt32, SKIP `a.e`) : 1': While executing ValuesBlockInputFormat. (INCORRECT_DATA) (version 24.8.5.115 (official build))

```

**Comment by justwdh** [comment]
![c1](https://github.com/user-attachments/assets/8775bbad-a6a6-4f60-8232-897d66b58757)
![c2](https://github.com/user-attachments/assets/1152d130-0e23-4365-9a0c-0481f73b2b9a)

**Comment by nikitamikhaylov** [comment]
Please provide a reproducible example in plaintext using [fiddle.clickhouse.com ](https://fiddle.clickhouse.com/)

**Comment by justwdh** [comment]
now i test 24.10.1.2812 version in Ubuntu 22.04.2 LTS's docker verion 27.2.1 works fine and 24.10.1.2812 version in debian 12.6's docker version 27.3.1 works bad.

**Comment by justwdh** [comment]
> now i test 24.10.1.2812 version in one Ubuntu 22.04.2 LTS's docker verion 27.2.1 works fine and 24.10.1.2812 version in debian 12.6's docker version 27.3.1 works bad.
> 
> another Ubuntu 24.04.1 LTS run failed
> 
> it looks like something wrong with high Kernel version
> 
> ```
> 2024.11.04 11:35:23.568072 [ 66 ] {5d4a5e9a-4801-4286-97f4-057bd172e79f} <Error> executeQuery: Code: 117. DB::Exception: Cannot parse JSON object here: {"a" : {"b" : 42}, "c" : [1, 2, 3]}: while executing 'FUNCTION if(isNull(-dummy-0) : 3, defaultValueOfTypeName('JSON') :: 2, _CAST(-dummy-0, 'JSON') :: 4) -> if(isNull(-dummy-0), defaultValueOfTypeName('JSON'), _CAST(-dummy-0, 'JSON')) JSON : 1': While executing ValuesBlockInputFormat. (INCORRECT_DATA) (version 24.10.1.2812 (official build)) (from 10.32.8.2:58744) (in query:  INSERT INTO test VALUES ), Stack trace (when copying this message, always include the lines below):
> 
> 0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000cf720fb
> 1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007ea888c
> 2. DB::Exception::Exception<std::basic_string_view<char, std::char_traits<char>>&>(int, FormatStringHelperImpl<std::type_identity<std::basic_string_view<char, std::char_traits<char>>&>::type>, std::basic_string_view<char, std::char_traits<char>>&) @ 0x000000000a0f0d2b
> 3. DB::SerializationJSON<DB::SimdJSONParser>::deserializeObject(DB::IColumn&, std::basic_string_view<char, std::char_traits<char>>, DB::FormatSettings const&) const @ 0x0000000007a4dff0
> 4. DB::SerializationJSON<DB::SimdJSONParser>::deserializeWholeText(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x0000000007a4dab9
> 5. DB::(anonymous namespace)::ConvertImplGenericFromString<true>::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long, std::shared_ptr<DB::Context const> const&) @ 0x000000000fc0850a
> 6. COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__function::__default_alloc_func<DB::(anonymous namespace)::FunctionCast::createObjectWrapper(std::shared_ptr<DB::IDataType const> const&, DB::DataTypeObject const*) const::'lambda'(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>>(std::__function::__policy_storage const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) @ 0x000000000fd727b4
> 7. COW<DB::IColumn>::immutable_ptr<DB::IColumn> std::__function::__policy_invoker<COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>::__call_impl<std::__function::__default_alloc_func<DB::(anonymous namespace)::FunctionCast::prepareRemoveNullable(std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::IDataType const> const&, bool) const::'lambda0'(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long), COW<DB::IColumn>::immutable_ptr<DB::IColumn> (std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long)>>(std::__function::__policy_storage const*, std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>>&, std::shared_ptr<DB::IDataType const> const&, DB::ColumnNullable const*, unsigned long) @ 0x000000000fdb38f6
> 8. DB::(anonymous namespace)::ExecutableFunctionCast::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const (.bbec4b369713e2406103dfff8e75fc70) @ 0x000000000fbfac16
> 9. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000fb8da07
> 10. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000fb8e25c
> 11. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000fb8f55d
> 12. DB::IFunctionBase::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x0000000007ec4b59
> 13. DB::ColumnFunction::reduce() const @ 0x00000000119dce7f
> 14. DB::maskedExecute(DB::ColumnWithTypeAndName&, DB::PODArray<char8_t, 4096ul, Allocator<false, false>, 63ul, 64ul> const&, DB::MaskInfo const&) @ 0x0000000011bf14d2
> 15. DB::(anonymous namespace)::FunctionIf::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x00000000111c0585
> 16. DB::FunctionToExecutableFunctionAdaptor::executeImpl(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0x000000000890077a
> 17. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000fb8da07
> 18. DB::IExecutableFunction::executeWithoutSparseColumns(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000fb8e31e
> 19. DB::IExecutableFunction::execute(std::vector<DB::ColumnWithTypeAndName, std::allocator<DB::ColumnWithTypeAndName>> const&, std::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x000000000fb8f55d
> 20. DB::ExpressionActions::execute(DB::Block&, unsigned long&, bool, bool) const @ 0x0000000010e020f9
> 21. DB::ExpressionActions::execute(DB::Block&, bool, bool) const @ 0x0000000010e0334e
> 22. DB::ConstantExpressionTemplate::evaluateAll(DB::BlockMissingValues&, unsigned long, std::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0x0000000012bebde7
> 23. DB::ValuesBlockInputFormat::read() @ 0x0000000012bdd374
> 24. DB::IInputFormat::generate() @ 0x00000000129bd116
> 25. DB::ISource::tryGenerate() @ 0x000000001299985b
> 26. DB::ISource::work() @ 0x0000000012999567
> 27. DB::ExecutionThreadContext::executeTask() @ 0x00000000129b3ce7
> 28. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x00000000129a7290
> 29. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000129a6564
> 30. DB::CompletedPipelineExecutor::execute() @ 0x00000000129a4e12
> 31. DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, std::shared_ptr<DB::Context>, std::function<void (DB::QueryResultDetails const&)>, DB::QueryFlags, std::optional<DB::FormatSettings> const&, std::function<void (DB::IOutputFormat&, String const&, std::shared_ptr<DB::Context const> const&, std::optional<DB::FormatSettings> const&)>) @ 0x000000001172c9c8
> ```

I'm sure it has nothing to do with the kernel. I've tried it on servers with different hardware using centos7 and the 3.10 kernel. One works, and the other doesn't.

**Comment by justwdh** [comment]
Also failed

**Comment by Avogar** [comment]
> version 24.7.6.8

New JSON type is avaliable since `24.8`. Old `Object` type (that had alias `JSON`) doesn't respect setting `allow_simdjson `

**Comment by justwdh** [comment]
My physical host CPU is Intel(R) Xeon(R) Gold 6278C CPU @ 2.60GHz. The default CPU type of the pve virtualization server is x86-64-v2-AES. I changed it to Skylake-Server and it worked. I don't know much about this, but it should be related to the CPU instruction set.
