### ISSUE TITLE
[Experimental] Insert into table with vector similarity index and other index throws `Expected data type Array(Float*)`

### ISSUE THREAD

**Issue by grzegorz-bielski** [ClickHouse/ClickHouse#71381]
**Describe what's wrong**

When using vector similarity indexes / approximate nearest neighbor search indexes with other index types (like set, full_search), `Code: 49. DB::Exception: Expected data type Array(Float*)` is thrown during inserts.

**Does it reproduce on the most recent release?**

Yes, tried `24.9.2.42-alpine` and `head-alpine`.

**How to reproduce**
https://fiddle.clickhouse.com/033646dc-2f4e-4d7e-9c30-10cc44d74739
https://fiddle.clickhouse.com/321f51e6-ca88-4e41-bf61-a1d59041a5ba
```SQL
SET allow_experimental_vector_similarity_index = 1;
SET allow_experimental_full_text_index = 1;

CREATE TABLE IF NOT EXISTS embeddings_table
(
  value String,
  embedding Array(Float32),
  INDEX ann_idx embedding TYPE vector_similarity('hnsw', 'cosineDistance'),
  INDEX inv_idx value TYPE full_text()
  -- or INDEX set_idx value TYPE set(100) GRANULARITY 100                                   
)
ENGINE = MergeTree()                                          
ORDER BY tuple();

INSERT INTO embeddings_table (value, embedding) VALUES ('doc content', [0.0]);

```

**Expected behavior**

I should be able to use both indexes on the same table.

**Error message and/or stacktrace**

```
Code: 49. DB::Exception: Expected data type Array(Float*). (LOGICAL_ERROR) (version 24.11.1.643 (official build))
```

**Comment by melvynator** [comment]
It also reproduce with other index https://fiddle.clickhouse.com/bd8944d7-1e89-4e22-9516-dc6fbf3c4c45 

GA blocker.
