### ISSUE TITLE
How to force ClickHouse to return column names prefixed with table names when INNER JOIN?

### ISSUE THREAD

**Issue by wlzywang** [ClickHouse/ClickHouse#71394]
### Question

For example:

CREATE TABLE ta
(
    `a` UInt32,
    `id` UInt32
)
ENGINE = MergeTree
ORDER BY id

CREATE TABLE tb
(
    `b` UInt32,
    `id` UInt32
)
ENGINE = MergeTree
ORDER BY id

insert into ta(*) VALUES (0,1)
insert into tb(*) VALUES (1,1)

WITH
    a AS
    (
        SELECT
            a,
            id
        FROM ta
    ),
    b AS
    (
        SELECT
            b,
            id
        FROM tb
    )
SELECT *
FROM a
INNER JOIN b ON a.id = b.id

This returns
┌─a─┬─id─┬─b─┬─b.id─┐
│ 0     │  1    │ 1     │    1 │
└───┴────┴───┴──────┘

How to force the returned qualified column names, i.e. a.a, a.id, b.b and b.id?

**Comment by amabilee** [comment]
In `ClickHouse`, column names are not automatically prefixed with their respective table names when performing a `join`. 

However, you can achieve this by explicitly specifying the column names in your `SELECT` statement. Here's an example that forces the returned qualified column names as a.a, a.id, b.b, and b.id:

```
CREATE TABLE ta
(
    a UInt32,
    id UInt32
)
ENGINE = MergeTree
ORDER BY id;

CREATE TABLE tb
(
    b UInt32,
    id UInt32
)
ENGINE = MergeTree
ORDER BY id;

INSERT INTO ta VALUES (0, 1);
INSERT INTO tb VALUES (1, 1);

WITH
    a AS
    (
        SELECT
            a,
            id
        FROM ta
    ),
    b AS
    (
        SELECT
            b,
            id
        FROM tb
    )
SELECT
    a.a AS `a.a`,
    a.id AS `a.id`,
    b.b AS `b.b`,
    b.id AS `b.id`
FROM a
INNER JOIN b ON a.id = b.id;
```
This will return:
```
┌─a.a─┬─a.id─┬─b.b─┬─b.id─┐
│  0  │   1  │  1  │   1  │
└─────┴──────┴─────┴──────┘
```

**Comment by wlzywang** [comment]
Yeah, actually the alias is what I am doing now but it is kinda tedious if I have many columns to select and several tables to join together. Thank you for confirming, Amabilee.
