### ISSUE TITLE
Aliases for anyLast_respect_nulls / any_respect_nulls with Camel case

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#71401]
`anyLast_respect_nullsStateIf` looks unpleasant. It will be much prettier `anyLastRespectNullsStateIf`.

Also the error message looks weird:
```sql
select anyLast_respect_nullsStateIf(10);

DB::Exception: Aggregate function anyLast_respect_nulls requires single argument. (NUMBER_OF_ARGUMENTS_DOESNT_MATCH)
```

**Comment by petern48** [comment]
I'll take care of this.

**Comment by petern48** [comment]
I'll look into the error message as a new issue. It seems like a problem for all `-If` functions, not just this one.
