### ISSUE TITLE
Does Clickhouse support converting CSVs or other file formats into serialized JSON and inserting that directly into a table?

### ISSUE THREAD

**Issue by rorylshanks** [ClickHouse/ClickHouse#71433]
### Question

We have a system that generates millions of CSV files, with thousands of different schemas. We would like to be able to serialize these CSV files into JSON, and then store them in clickhouse, alongside a few standardized columns. So the schema would look something like

```sql
(
    created_at DateTime,
    tag LowCardinality(String),
    ...
    event String
)
```

With the `event` column being the serialized JSON of the single row of the CSV file. The output of JSONEachRow is exactly what I need, but I cannot seem to find a way of INSERTing this serialized JSON output into another table. 

I have tried many things, but I can never seem to get the column names to allow me to use it in a named tuple() or map(), or even an array. The column names seem to be the issue. 

Is this possible in Clickhouse?

**Comment by rorylshanks** [comment]
Heya, thanks for the response! I store the CSV files in s3 and was hoping to be able to directly query the file from s3, convert it to JSON, and then insert the JSON serialized row into a clickhouse mergetree table. I would prefer to store it as JSON due to the many different schemas that these files have, and ideally in a single SQL query that queries from S3, converts to JSON, and inserts.

**Comment by alexey-milovidov** [comment]
Yes, you can format a record into a string containing a JSON, using the `formatRow` or `formatRowNoNewline` function:

```
SELECT formatRowNoNewline('JSONLines', *) FROM ...
```
