### ISSUE TITLE
Does clickhouse still support deflate_qpl with intel IAA?

### ISSUE THREAD

**Issue by Jae0504** [ClickHouse/ClickHouse#71442]
### Question

I saw this on the clickhouse 2024 change log.
- Remove the idxd-config library, which has an incompatible license. This also removes the experimental Intel DeflateQPL codec. [#70987](https://github.com/ClickHouse/ClickHouse/pull/70987) ([Alexey Milovidov](https://github.com/alexey-milovidov)).

Does clickhouse still support deflate_qpl with intel IAA?

**Comment by Algunenano** [comment]
> Does clickhouse still support deflate_qpl with intel IAA?

No, it does not. It might come back in the future

**Comment by Algunenano** [comment]
Of course you can. Versions prior to that change (prior to 24.10) will have it

**Comment by Jae0504** [comment]
Are there any instructions on how to enable QPL in the older version like (24.9 or 24.8)? I saw that "
Codec DEFLATE_QPL is now controlled via server setting "enable_deflate_qpl_codec" (default: false) instead of setting "allow_experimental_codecs". This marks DEFLATE_QPL non-experimental. [#50775](https://github.com/ClickHouse/ClickHouse/pull/50775) ([Robert Schulze](https://github.com/rschu1ze))." I am not sure where should I enable enable_deflate_qpl_codec.
