### ISSUE TITLE
Too many parts (3000 with average size of 8.26 KiB) in table 'MWLOGDB_ANALYSIS_2.SYSTEM_METRICS'. Merges are processing significantly slower than inserts. (TOO_MANY_PARTS) (version 23.6.1.1524 (official build))

### ISSUE THREAD

**Issue by XSWClevo** [ClickHouse/ClickHouse#71443]
### Question

I have a scheduled task, 30s will batch insert data into the data, each connection insert the number is 1000, now I encountered this problem, Too many parts (3000). Merges are processing significantly slower than inserts,  because my table is partitioned by month, but the local network is not stable. There are many connection timeouts in the connection to clickhouse, could this be the cause.

![image](https://github.com/user-attachments/assets/221ddce0-4fee-4c24-a6fe-319995dd348a)

I run 
`SELECT count(partition ), partition FROM system.parts WHERE table = 'your_table_name'  group by partition ` 
![image](https://github.com/user-attachments/assets/54728c7e-8933-48f4-838c-75c1ea062e6d)

This is my table structure
![image](https://github.com/user-attachments/assets/42ef5f5c-6024-4e09-9266-c06df46d47b3)

**Comment by cangyin** [comment]
According to kb https://clickhouse.com/docs/knowledgebase/exception-too-many-parts

I would suggest larger batch size like 50,000 per insert.
