### ISSUE TITLE
Unknown table engine Hive

### ISSUE THREAD

**Issue by rchaocai** [ClickHouse/ClickHouse#71453]
### Question

Received exception from server (version 22.9.7):
Code: 56. DB::Exception: Received from localhost:9000. DB::Exception: Unknown table engine Hive. Maybe you meant: ['File']. (UNKNOWN_STORAGE)

This is the error corresponding to the ARM64 version; the x86 version has no issues. Does the ARM version of ClickHouse not support the Hive engine?

**Comment by Algunenano** [comment]
In 22.9, no it didn't. Consider using a supported release.
