### ISSUE TITLE
I think sth is wrong with arrayDifference

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7147]
THIS IS FINE 

```
SELECT arrayDifference([1, 2, 3, 4])

┌─arrayDifference([1, 2, 3, 4])─┐
│ [0,1,1,1]                     │
└───────────────────────────────┘
```

BUT what `-1` mean ?
```
SELECT arrayDifference([1, 2, 2, 3, 3, 2])

┌─arrayDifference([1, 2, 2, 3, 3, 2])─┐
│ [0,1,0,1,0,-1]                      │
└─────────────────────────────────────┘
```

And this is not reasonable:
```
SELECT arrayDifference(['a', 'b'])

Received exception from server (version 19.5.3):
Code: 43. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: arrayDifference cannot process values of type String.
```
array(T) takes T type, but a function can not support String type......

**Comment by filimonov** [comment]
> BUT what -1 mean ?

`-1` means that last element of array (`2`) minus previous one (`3`) equals `2 - 3 = -1`

Isn't it the expected behaviour?

> array(T) takes T type, but a function can not support String type......

Does strings support substraction? What is the result of 'Hello' minus 'world!' ?

**Comment by Tasselmi** [comment]
> > BUT what -1 mean ?
> 
> `-1` means that last element of array (`2`) minus previous one (`3`) equals `2 - 3 = -1`
> 
> Isn't it the expected behaviour?
> 
> > array(T) takes T type, but a function can not support String type......
> 
> Does strings support substraction? What is the result of 'Hello' minus 'world!' ?

I thought arrayDifference means if they are not equal........ 1 means true and 0 means false
......
So I misunderstood..

**Comment by Tasselmi** [comment]
> > BUT what -1 mean ?
> 
> `-1` means that last element of array (`2`) minus previous one (`3`) equals `2 - 3 = -1`
> 
> Isn't it the expected behaviour?
> 
> > array(T) takes T type, but a function can not support String type......
> 
> Does strings support substraction? What is the result of 'Hello' minus 'world!' ?

I want to make [1, 2, 2, 3, 3, 2, 2]  -> [1, 2, 3, 2]
I am doing a program computing user-behaviour-path ~~~

**Comment by den-crane** [comment]
select arrayConcat([arr[1]], arrayFilter(x,y -> x = y, arraySlice(arr, 2), arraySlice(arr, 1, -1))) from (  select [1, 2, 2, 3, 3, 2, 2] arr )

SELECT arrayConcat([arr[1]], arrayFilter(x,y -> y!=0, arr ,arrayDifference(arr))) from (select [1, 2, 2, 3, 3, 2] arr)

**Comment by Tasselmi** [comment]
> select arrayConcat([arr[1]], arrayFilter(x,y -> x = y, arraySlice(arr, 2), arraySlice(arr, 1, -1))) from ( select [1, 2, 2, 3, 3, 2, 2] arr )
> 
> SELECT arrayConcat([arr[1]], arrayFilter(x,y -> y!=0, arr ,arrayDifference(arr))) from (select [1, 2, 2, 3, 3, 2] arr)

Thanks for your help ~

**Comment by Tasselmi** [comment]
> select arrayConcat([arr[1]], arrayFilter(x,y -> x = y, arraySlice(arr, 2), arraySlice(arr, 1, -1))) from ( select [1, 2, 2, 3, 3, 2, 2] arr )
> 
> SELECT arrayConcat([arr[1]], arrayFilter(x,y -> y!=0, arr ,arrayDifference(arr))) from (select [1, 2, 2, 3, 3, 2] arr)



The first method is more universal.  It takes parameters of any type, but arrayDifference can only take numeric type.

```
SELECT arrayConcat(array(event_list[1]), arrayFilter((x, y) -> (x != y), arraySlice(event_list, 2), arraySlice(event_list, 1, -1)))
FROM ( SELECT [1, 2, 2, 3, 2, 2] AS event_list ) m
```
