### ISSUE TITLE
Clickhouse process fails to start after upgrade from 24.9 to 24.10 - Problem with refreshable materialized views

### ISSUE THREAD

**Issue by SteZe85** [ClickHouse/ClickHouse#71508]
We were trying to upgrade Clickhouse from 24.9 to 24.10 and the Clickhouse process failed to start with this error message:

> ``` <Error> Application: Code: 722. DB::Exception: Waited job failed: Code: 695. DB::Exception: Load job 'load table dwh.wkz_campaigns_no_array' failed: Code: 36. DB::Exception: TO INNER UUID is not allowed for materialized views with REFRESH without APPEND: Cannot attach table `dwh`.`wkz_campaigns_no_array` from metadata file /var/lib/clickhouse/store/373/3732d6ca-1115-45bb-ae0a-57da1100a0a0/wkz_campaigns_no_array.sql from query ATTACH MATERIALIZED VIEW dwh.wkz_campaigns_no_array UUID '13dbfffb-738d-40c2-a3f5-6993d4b956ea' REFRESH EVERY 1 DAY OFFSET 4 HOUR TO INNER UUID 'aaeb47c8-259d-4e8d-8468-bdc3d523b4af' (`id` UInt32, `created_at` DateTime, `updated_at` DateTime, `campaign` String, `issuetype` String, `epic` Nullable(String), `summary` String, `date_from` Date, `date_to` Nullable(Date), `ausspielung` String, `target` Nullable(String), `target_pzn_ <Error> Application: Code: 722. DB::Exception: Waited job failed: Code: 695. DB::Exception: Load job 'load table dwh.wkz_campaigns_no_array' failed: Code: 36. DB::Exception: TO INNER UUID is not allowed for materialized views with REFRESH without APPEND: Cannot attach table `dwh`.`wkz_campaigns_no_array` from metadata file /var/lib/clickhouse/store/373/3732d6ca-1115-45bb-ae0a-57da1100a0a0/wkz_campaigns_no_array.sql from query ATTACH MATERIALIZED VIEW dwh.wkz_campaigns_no_array UUID '13dbfffb-738d-40c2-a3f5-6993d4b956ea' REFRESH EVERY 1 DAY OFFSET 4 HOUR TO INNER UUID 'aaeb47c8-259d-4e8d-8468-bdc3d523b4af' (`id` UInt32, `created_at` DateTime, `updated_at` DateTime, `campaign` String, `issuetype` String, `epic` Nullable(String), `summary` String, `date_from` Date, `date_to` Nullable(Date), `ausspielung` String, `target` Nullable(String), `target_pzn_split` Nullable(String), `target_pzn_` Nullable(String), `ausspielung_pzn_split` Nullable(String), `ausspielung_pzn_` Nullable(String), `mapping` Nullable(String), `cost` Nullable(Float64), `epic_campaign` Nullable(String), `epic_summary` Nullable(String), `pzn` Nullable(String), `pzn_name` Nullable(String), `manufacturer_id` Nullable(String), `manufacturer_name` Nullable(String), `brand` Nullable(String), `error` Nullable(String)) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 8192 AS...split` Nullable(String), `target_pzn_` Nullable(String), `ausspielung_pzn_split` Nullable(String), `ausspielung_pzn_` Nullable(String), `mapping` Nullable(String), `cost` Nullable(Float64), `epic_campaign` Nullable(String), `epic_summary` Nullable(String), `pzn` Nullable(String), `pzn_name` Nullable(String), `manufacturer_id` Nullable(String), `manufacturer_name` Nullable(String), `brand` Nullable(String), `error` Nullable(String)) ENGINE = MergeTree ORDER BY id SETTINGS index_granularity = 8192 AS...```

`wkz_campaigns_no_array` is a materialized view which was created under the former `allow_experimental_refreshable_materialized_view `setting. Is this connected to  #70550 ?

This is the view header:

```
CREATE MATERIALIZED VIEW dwh.wkz_campaigns_no_array
REFRESH EVERY 1 DAY OFFSET 4 HOUR
(

    id UInt32,

    created_at DateTime,

    updated_at DateTime,

    campaign String,

    issuetype String,

    epic Nullable(String),

    summary String,

    date_from Date,

    date_to Nullable(Date),

    ausspielung String,

    target Nullable(String),

    target_pzn_split Nullable(String),

    target_pzn_ Nullable(String),

    ausspielung_pzn_split Nullable(String),

    ausspielung_pzn_ Nullable(String),

    mapping Nullable(String),

    cost Nullable(Float64),

    epic_campaign Nullable(String),

    epic_summary Nullable(String),

    pzn Nullable(String),

    pzn_name Nullable(String),

    manufacturer_id Nullable(String),

    manufacturer_name Nullable(String),

    brand Nullable(String),

    error Nullable(String)
)
ENGINE = MergeTree
ORDER BY id
SETTINGS index_granularity = 8192
AS

<SQL HERE>
;
```

**Comment by alexey-milovidov** [comment]
Refreshable Materialized Views were experimental in 24.9, and they are production-ready in 24.10, which means, breaking changes were possible. If you recreate this materialized view, does it help?

**Comment by SteZe85** [comment]
Downgrading to 24.9 , deleting the materialized views, upgrading to 24.10 and recreating them worked.

Thank you!

**Comment by al13n321** [comment]
The incompatibility wasn't intended, here's a fix: https://github.com/ClickHouse/ClickHouse/pull/71556
