### ISSUE TITLE
sum function works unexpectedly when all values are null

### ISSUE THREAD

**Issue by macdonsp** [ClickHouse/ClickHouse#7157]
When trying to use the sum function on a column that only contains null values, it returns a value of null instead of zero.

For example:

```
SELECT sum(v)
FROM
(
    SELECT NULL AS v
)

┌─sum(v)─┐
│ ᴺᵁᴸᴸ   │
└────────┘
```

If there is a single non-null value, things work as expected:

```
SELECT sum(v)
FROM
(
    SELECT NULL AS v
    UNION ALL
    SELECT 0 AS v
)

┌─sum(v)─┐
│      0 │
└────────┘
```

**Comment by den-crane** [comment]
PG:
```
select sum(x) from (select cast(Null as int) x) as t;
 sum
-----

```

mysql> select sum(x) from (select Null as x) t;
+--------+
| sum(x) |
+--------+
|   NULL |
+--------+

**Comment by macdonsp** [comment]
Might just be a documentation issue - https://clickhouse.yandex/docs/en/query_language/agg_functions/

```
The sum function interprets NULL as 0. In particular, this means that if the function receives input of a selection where all the values are NULL, then the result will be 0, not NULL.
```

**Comment by den-crane** [comment]
documentation fixed https://github.com/ClickHouse/ClickHouse/pull/17259

**Comment by TheHett** [comment]
LOL

**Comment by TheHett** [comment]
Why did you remove it from the documentation, especially since the behavior differs from the standard SQL?
