### ISSUE TITLE
LIMIT infuences ORDER BY output

### ISSUE THREAD

**Issue by bkuschel** [ClickHouse/ClickHouse#71609]
## A clear and concise description of what works not as it is supposed to.

When inserting bulk data, (multiple rows, single select) LIMIT can influence results of a SELECT with an ORDER BY clause. When inserting rows one-by-one, problem is not exhibited.

## How to reproduce

```sql
CREATE TABLE test (name LowCardinality(String), age LowCardinality(String), uid UInt64) ENGINE=Memory;

INSERT INTO test (name, age, uid) VALUES (1, '1', 1692724401000), (2, '2', 1692724402000), (1, '1', 1692724402000), (3, '3', 1692724403000), (1, '1', 1692724403000), (2, '2', 1692724404000);

SELECT
    name,
    age,
    uid
FROM test
WHERE (uid >= 1692724386000) AND (uid < 1692724404000)
ORDER BY uid DESC
LIMIT 1
```

For any version < 24.3 [the (correct) result is:](https://fiddle.clickhouse.com/6bba2cbc-2629-4505-9035-697fbde45eb9)

```
3	3	1692724403000
```

For versions >=24.3 [the (incorrect) result is:](https://fiddle.clickhouse.com/513944a9-0c40-42ca-80ab-b217d72cd4b5)

```
1	1	1692724403000
```

## Which ClickHouse server version to use
Any version >= 24.3

**Expected behavior**

Results >= 24.3 should match those for < 24.3

**Comment by Algunenano** [comment]
`ORDER BY` isn't, and never has been, stable sorting. Both results are correct, since you are only sorting by uid. If you want a specific sort to break ties, include extra columns.

**Comment by bkuschel** [comment]
Agreed, in theory there are no guarantees here but the order **is** effected by the LIMIT where it was not previously.

**Comment by Algunenano** [comment]
Yes, and we make use of that lack of guarantees to introduce performance improvements.

A couple of examples:
* With LIMIT N, the permutation uses `partial_sort` instead of sorting the full column (using pdqsort). Neither of the 2 are stable.
* With LIMIT 1 and a valid type we use an architecture optimized algorithm to find the index of the min value (so not sorting even takes place).
