### ISSUE TITLE
If you run clickhouse-client in the multiline mode, pressing Ctrl+D should finish the input.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#71624]
Allow using Ctrl+D instead of typing a semicolon and pressing Enter.
Additionally, make Ctrl+D work as Enter in the single-line mode.

**Comment by Algunenano** [comment]
> Additionally, make Ctrl+D work as Enter in the single-line mode.

But please remember that Ctrl+D on empty input is used for exit

**Comment by wudidapaopao** [comment]
see https://github.com/ClickHouse/ClickHouse/pull/73293

**Comment by azat** [comment]
>Allow using Ctrl+D instead of typing a semicolon and pressing Enter

As far as I am aware, by default (readline) C-d simply removes char under cursor
Maybe this behavior better to bind to some C-Enter or Shift-Enter? Though apparently it does not work in readline
Then maybe `Ctrl-;`?

It is not a big deal, but I just mistyped M-d, which should remove the next word, but it executed the query instead

**Comment by rschu1ze** [comment]
@wudidapaopao

**Comment by alexey-milovidov** [comment]
Alt-D and Ctrl-D behave differently, this is ok.

**Comment by alexey-milovidov** [comment]
Reverted.

**Comment by azat** [comment]
Actually I realized that I do use `Ctrl-D` to remove char under cursor, so it will be nice to use different shortcut, i.e. `Ctrl-;`

**Comment by alexey-milovidov** [comment]
Ok, let me withdraw this feature request :)
