### ISSUE TITLE
Documentation missing for entropy() function

### ISSUE THREAD

**Issue by ifoo** [ClickHouse/ClickHouse#7165]
The entropy() function introduced in https://github.com/ClickHouse/ClickHouse/pull/4238 to calculate the Shannon entropy is not working inside arrayMap (or probably any higher order function).

Simple example:
This works: 
```
SELECT arrayMap(x -> x, ['hello', 'world'])

┌─arrayMap(lambda(tuple(x), x), ['hello', 'world'])─┐
│ ['hello','world']                                 │
└───────────────────────────────────────────────────┘
```

but this doesn't:
```
SELECT arrayMap(x -> entropy(x), ['hello', 'world'])

Received exception from server (version 19.14.6):
Code: 10. DB::Exception: Received from localhost:9000. DB::Exception: Not found column x in block. There are only columns: dummy.
```
Also the entropy() function is not showing up in the documentation at all.

ClickHouse version:
```
ClickHouse client version 19.14.6.12 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.14.6 revision 54425.
```

**Comment by filimonov** [comment]
It's an aggregate function. Probably you need `arrayReduce`.

**Comment by ifoo** [comment]
@filimonov thanks. i'll renaming the issue to missing documentation.
