### ISSUE TITLE
RFC: rework Buffer tables so they are more usable

### ISSUE THREAD

**Issue by vmihailenco** [ClickHouse/ClickHouse#71694]
Problems with the current Buffer table design:

1. Reads are blocked by flushes. For example, if flushing takes 10 seconds than SELECT queries will be blocked for 10 seconds. According to [this](https://github.com/ClickHouse/ClickHouse/pull/70864#issuecomment-2455955748) it is not necessary and is just an implementation detail.

This makes reading from Buffer tables unusable.

2. Buffer tables do not minimize number of flushes (and thus merges) and instead they actively try to make as many flushes as possible.

For example, if you have 8 Buffer layers, than ClickHouse will try to evenly fill all the layers and you will have 8 flushes even if you have inserted 8 rows (1 row per insert). I don't know why this is done this way, but presumably to parallelize reading which is unusable anyway. Another idea is to make synthetic benchmarks fast.

Instead, ClickHouse could try to wait 10-50ms for an existing buffer layer instead of creating a new one. This is **standard** practice when accumulating batches. This way ClickHouse will automatically scale number of buffer layers and minimize number of flushes/merges.

3. Presumably, you can tweak Buffer parameters (min_time, max_time, min_rows, max_rows, min_bytes, max_bytes) to make 2) less problematic, but this does not seem to be the case in my practice.

  - You can't have high max_time, because reading from the buffer table is awfully and randomly slow. So you try to avoid SELECTing any data from buffers which implies low max_time.
  - And you can't have high max_bytes/max_rows, because it will make flushes even more slower.
  - You can't really tweak number of layers, because low number of layers will limit the max number of rows you can insert. Am I supposed to dynamically change it as I need to insert more rows?

4. Presumably, such parameters as flush_time, flush_rows, flush_bytes might help, but I don't see any difference after enabling them. It either does not work at all or all layers are blocked flushing the data so the knobs are useless.

I do want to point out that the existence of these knobs indicate that users are having problems with buffer tables. But the proposed solution does not help.

5. Instead of fixing buffer tables, people suggest to try using asynchronous inserts. Async inserts don't support native protocol and have their own trade-offs/problems with tens of settings to tweak.

---

So what I suggest is to rework buffer layers:

1. Don't block reads during flushes.
2. Try to minimize number of active buffer layers by waiting 10-50ms for a layer to become free. I can elaborate more on this if needed.

The 2nd point might negatively affect synthetic benchmarks, but it will help with read world applications.

**Comment by alexey-milovidov** [comment]
@vmihailenco, Could you please take over this pull request? https://github.com/ClickHouse/ClickHouse/pull/70864
It was closed by the author, but the changes are small, and it could be easily finished after fixing the formatting.

**Comment by UnamedRus** [comment]
>  Async inserts don't support native protocol

They technically does, but possible that not all variations of them.

There was also idea of embedded "Buffer" engine in MergeTree tables
https://github.com/ClickHouse/ClickHouse/issues/40728

Having a lot of "proxy" tables on top of main table doesn't works too reliable TBH.

**Comment by vmihailenco** [comment]
>They technically does, but possible that not all variations of them.

I was able to get it working after some experiments.

**Comment by jptx1234** [comment]
@vmihailenco  This issue has been closed, but will the rework of Buffer table continue? The problems you mentioned does exist.
