### ISSUE TITLE
`toJSONString` is formatting integers as strings

### ISSUE THREAD

**Issue by pkese** [ClickHouse/ClickHouse#71717]
**Describe the unexpected behaviour**

If I store an integer into a JSON column, the value is stored as an integer, but `toJSONString` and normal JSON formatting is displaying it quoted (as a string).

```sql
CREATE OR REPLACE TABLE t ( json JSON ) ENGINE = Memory;
INSERT INTO t VALUES ( '{"x": 10}' ); -- we've inserted an integer
SELECT * FROM t;

   ┌─json───────┐
1. │ {"x":"10"} │ -- notice the number 10 being displayed as string: "10"
   └────────────┘

SELECT toJSONString(json) FROM t;

   ┌─toJSONString(json)─┐
1. │ {"x":"10"}         │ -- same thing
   └────────────────────┘
```
I initially thought that the problem is with input format inference (e.g. `input_format_try_infer_integers`) and I spent a bunch of time fiddling with these settings.

However then I found out that the database is correctly storing the value in correct numeric format  
so apparently the problem is in json formatting, e.g. `toJSONString`.
```sql
SELECT dynamicType(json.x) FROM t;

   ┌─dynamicType(json.x)─┐
1. │ Int64               │
   └─────────────────────┘
```

**Expected behavior**
I would expect the value to be printed as an integer:
```sql
SELECT * FROM t;

   ┌─json─────┐
1. │ {"x":10} │
   └──────────┘

```

**Additional context**
Occurring on:  
ClickHouse client version 24.10.1.2812 (official build).
Connected to ClickHouse server version 24.10.1.

**Comment by den-crane** [comment]
Because of [output_format_json_quote_64bit_integers](https://clickhouse.com/docs/en/operations/settings/formats#output_format_json_quote_64bit_integers)

https://fiddle.clickhouse.com/50c178b3-8732-4c66-8d84-ae560456a224
