### ISSUE TITLE
Question about Keeper Bench

### ISSUE THREAD

**Issue by Dnivd** [ClickHouse/ClickHouse#71714]
### Question

On the page https://github.com/ClickHouse/ClickHouse/tree/master/utils/keeper-bench

There is a description about Keeper Bench
In particular about the launch
_To run it call following command from the build folder:
./utils/keeper-bench --config benchmark_config_file.yaml_

Please tell me how to run it in the end, since the executable file is not specified and from the example it follows that you need to call the directory with the configuration file?

**Comment by hanfei1991** [comment]
To build keeper bench you need add `-DENABLE_UTILS=1` in cmake command, then you can find the binary under your build_directory/utils/

**Comment by Dnivd** [comment]
> https://clickhouse.com/docs/en/development/build

Thanks, I went to try, I didn't scroll through it apparently (

**Comment by Dnivd** [comment]
Установил пакеты
`$ sudo dnf install git cmake make clang python3 ccache lld nasm yasm gawk`

**Last metadata expiration check: 0:27:04 ago, Wed Nov 20 2024 20:45:46.
Package git-2.43.5-1.el9.x86_64 is already installed.
Package cmake-3.26.5-2.el9.x86_64 is already installed.
Package make-1:4.3-8.el9.x86_64 is already installed.
Package clang-19.1.3-1.el9.x86_64 is already installed.
Package python3-3.9.20-1.el9.x86_64 is already installed.
Package ccache-4.5.1-2.el9.x86_64 is already installed.
Package lld-19.1.3-1.el9.x86_64 is already installed.
Package nasm-2.15.03-7.el9.x86_64 is already installed.
Package yasm-1.3.0^20230922git9defefa-2.el9.x86_64 is already installed.
Package gawk-5.1.0-6.el9.x86_64 is already installed.
Dependencies are resolved.
No actions to perform.
Done!**

But the error remained: 

`make -S . -B build `

CMake Error at cmake/tools.cmake:4 (message): Compiler GNU is not supported Call Stack (most recent call first): CMakeLists.txt:18 (include) -- Configuring incomplete, errors occurred!


Maybe someone has experience in running on CentOS?

I'm already thinking about deploying ubuntu
But the question arose, did I understand correctly that Keeper Bench can be launched on any ubuntu, centos... server and in the config file benchmark_config_file.yaml (as an example) just specify the servers on which keeper or zookeeper is installed?

**Comment by hanfei1991** [comment]
@Dnivd it's not about centOS or ubuntu. it's about compiler ---- we use clang. Please read this https://clickhouse.com/docs/en/development/build#install-and-use-the-clang-compiler

**Comment by Dnivd** [comment]
The error still remains, I did
https://clickhouse.com/docs/en/development/build#install-and-use-the-clang-compiler
https://clickhouse.com/docs/en/development/build#install-rust-compiler

Apparently you need to switch to ubuntu and check on it

**Comment by Algunenano** [comment]
> Apparently you need to switch to ubuntu and check on it

If you are still getting the same error, either you haven't cleared your build folder or you are not passing clang, or both.

**Comment by hanfei1991** [comment]
@Dnivd Read the output of cmake carefully, you will find out what compiler cmake is using.

**Comment by Dnivd** [comment]
Today I rebooted the server, completely deleted the downloaded from git https://github.com/ClickHouse/ClickHouse

Runned
$ cmake --build build

"I was happy" probably too early and caught an error:

**[9748/14042] Building C object contrib/libssh-cmake/CMakeFiles/_ssh.dir/__/libssh/src/chachapoly.c.o
[9749/14042] Building C object contrib/libssh-cmake/CMakeFiles/_ssh.dir/__/libssh/src/buffer.c.o
[9749/14042] Building C object contrib/libssh-cmake/CMakeFiles/_ssh.dir/__/libssh/src/channels.c.o
[9750/14042] Building C object contrib/libssh-cmake/CMakeFiles/_ssh.dir/__/libssh/src/chachapoly.c.o
[9750/14042] Building C object contrib/libssh-cmake/CMakeFiles/_ssh.dir/__/libssh/src/client.c.o
[9751/14042] Building C object contrib/SimSIMD-cmake/CMakeFiles/_simsimd.dir/__/SimSIMD/c/lib.c.o
FAILED: contrib/SimSIMD-cmake/CMakeFiles/_simsimd.dir/__/SimSIMD/c/lib.c.o
/usr/bin/ccache /usr/bin/clang-17 --target=x86_64-linux-gnu --sysroot=/tmp/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DSIMSIMD_DYNAMIC_DISPATCH -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -D_LIBUNWIND_IS_NATIVE_ONLY -I/tmp/ClickHouse/base/glibc-compatibility/memcpy -isystem /tmp/ClickHouse/contrib/SimSIMD/include -isystem /tmp/ClickHouse/contrib/llvm-project/libcxxabi/include -isystem /tmp/ClickHouse/contrib/libunwind/include --gcc-toolchain=/tmp/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -fdiagnostics-color=always -Xclang -fuse-ctor-homing -Wno-enum-constexpr-conversion -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/tmp/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -ffp-contract=off -fdiagnostics-absolute-paths -w -ffunction-sections -fdata-sections -O2 -g -DNDEBUG -O3 -g -fno-pie -std=gnu11 -D OS_LINUX -Werror -Wno-deprecated-declarations -Wno-poison-system-directories -MD -MT contrib/SimSIMD-cmake/CMakeFiles/_simsimd.dir/__/SimSIMD/c/lib.c.o -MF contrib/SimSIMD-cmake/CMakeFiles/_simsimd.dir/__/SimSIMD/c/lib.c.o.d -o contrib/SimSIMD-cmake/CMakeFiles/_simsimd.dir/__/SimSIMD/c/lib.c.o -c /tmp/ClickHouse/contrib/SimSIMD/c/lib.c**

**[9752/14042] Building C object contrib/libssh-cmake/CMakeFiles/_ssh.dir/__/libssh/src/client.c.o
[9753/14042] Building C object contrib/libssh-cmake/CMakeFiles/_ssh.dir/__/libssh/src/channels.c.o
ninja: build stopped: subcommand failed.**

**Comment by Dnivd** [comment]
I'll try on Ubuntu

There's not enough space on centOS (, you need to rebuild the virtual server

**Comment by Dnivd** [comment]
on ubuntu
Done according to: https://clickhouse.com/docs/en/development/build#build-clickhouse
**cd ClickHouse
mkdir build
cmake -S . -B build**

According to the comment
https://github.com/ClickHouse/ClickHouse/issues/71714#issuecomment-2470385657

Done:
**cmake -S . -B build -DENABLE_UTILS=1$**

Execution log:
[log.txt](https://github.com/user-attachments/files/17902268/log.txt)

List of files in build_directory/utils/keeper-bench

**admincli@ubuntu-clickhouse:~/click/ClickHouse/build/utils$ pwd
/home/admincli/click/ClickHouse/build/utils
admincli@ubuntu-clickhouse:~/click/ClickHouse/build/utils$ ll keeper-bench/
total 20
drwxrwxr-x 3 admincli admincli 4096 Nov 25 18:01 ./
drwxrwxr-x 14 admincli admincli 4096 Nov 25 18:01 ../
drwxrwxr-x 3 admincli admincli 4096 Nov 25 18:01 CMakeFiles/
-rw-rw-r-- 1 admincli admincli 1292 Nov 25 18:01 cmake_install.cmake
-rw-rw-r-- 1 admincli admincli 319 Nov 25 18:01 CTestTestfile.cmake
admincli@ubuntu-clickhouse:~/click/ClickHouse/build/utils$**

After which I performed the installation:
sudo cmake -P cmake_install.cmake

Execution log:
[cmake_install.txt](https://github.com/user-attachments/files/17902368/cmake_install.txt)

But the installation of keeper-bench did not occur, there is no information in the installation log list

Please tell me where I made a mistake again? Unfortunately, I cannot find a description of the build on the Internet

**Comment by Dnivd** [comment]
Partially managed to achieve at least some victory
Maybe someone will need it

At the instruction step https://clickhouse.com/docs/en/development/build#build-clickhouse

The following sequence
**cd ClickHouse
mkdir build
cmake -S . -B build -DENABLE_UTILS=1
cmake --build build --target keeper-bench**

Then you can try to run testing
https://github.com/ClickHouse/ClickHouse/tree/master/utils/keeper-bench

It's a pity the test from https://github.com/ClickHouse/examples/tree/main/keeper-bench-suite stopped working

There was a record implementation in the DB for further analysis
