### ISSUE TITLE
24.9+ some OS-level metrics are now not available in containers (or if cgroups are used)

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#71733]
The system-wide metrics like LoadAverage1 OSProcessesRunning OSInterrupts etc. are not available after that change https://github.com/ClickHouse/ClickHouse/pull/62003

There are no cgroup-local analogue for LoadAverage, so IMHO it should stay (and it's ok that they are system-wide, should be just clearly stated in the metric description).

And if we talk about cgroup-specific metrics 'nice to have' but still not there:

/sys/fs/cgroup/<cgroup_name>/cpu.pressure
/sys/fs/cgroup/<cgroup_name>/memory.pressure
/sys/fs/cgroup/<cgroup_name>/io.pressure

(see https://docs.kernel.org/accounting/psi.html )

**Comment by nickitat** [comment]
nobody reads descriptions, people just assume that every existing signal is meaningful and then complain that numbers don't make sense.

**Comment by filimonov** [comment]
LoadAverage is meaningful :)

**Comment by filimonov** [comment]
If you run a lot of other things on the same host and don't want to expose that - maybe it would better to add a setting like 'collect_system_wide_metric' and disable it for your case.

**Comment by alexey-milovidov** [comment]
I like system-wide metrics. Let these metrics fall back to system-wide, as before.
No need to add any settings.
