### ISSUE TITLE
docker run clickhouse-client,  unknown flag: link

### ISSUE THREAD

**Issue by Dnivd** [ClickHouse/ClickHouse#71757]
### Question

In the file https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/README.md
In the block "connect to it from a native client"
When calling the command:
docker run -it --rm --link some-clickhouse-server:clickhouse-server --entrypoint clickhouse-client clickhouse/clickhouse-server --host clickhouse-server

I catch the error
Error: unknown flag: --link

either this flag was removed or I'm doing something wrong, please help

**Comment by Tiaonmmn** [comment]
Can you provide the output of `docker -v`?

**Comment by Algunenano** [comment]
https://lists.podman.io/archives/list/podman@lists.podman.io/thread/VP6ITQNQKNKVK275MBP42BSZOG5LH42T/

You are not using docker
