### ISSUE TITLE
Share Nothing?

### ISSUE THREAD

**Issue by nnovod** [ClickHouse/ClickHouse#7177]
This is a high level issue but I was hoping someone could tell me more...

I'm new to Clickhouse but have successfully transferred over a fairly large DB from Vertica to check it out.  Overall I've been quite impressed.  We're also planning on taking a look at Google's BigQuery and questions have come up about running ClickHouse vs. BigQuery on the cloud.  Any information you can give me about these questions would be very useful. 

Clickhouse appears to be a share nothing architecture.  As other cloud implementations such as BigQuery move to using shared storage I was wondering if Clickhouse has similar plans.

The obvious appeal of BigQuery's shared storage is that it's very easy to scale (just add more cpus), and can even be dynamically scaled.  Also, administrative costs (at least for the hardware and DBMS installation) are negligible.  On the other hand I believe (tell me if you disagree!) that a share nothing architecture will still perform significantly better if setup correctly.

Will Clickhouse always be share nothing?  Any other thoughts on Clickhouse vs. BigQuery?

**Comment by alexey-milovidov** [comment]
Yes, ClickHouse is using shared-nothing architecture.
We have a plan to add support for shared storage as an option.

Shared storage can provide benefits in scalability and lower maintenance costs only if it is tightly integrated in some cloud service (BigQuery, Snowflake). But ClickHouse can be used in public and private clouds and on premise.

In most cases, shared-nothing architecture can outperform shared variant - unless you have carefully engineered network (100G full mesh?) and the software that provides this shared storage.

I know some companies are using ClickHouse on Ceph and on MooseFS. But I don't think it is a good solution.

Mixed variants are possible: shared storage + local caches; shared storage for archive data.

**Comment by tbragin** [comment]
Separation of storage and compute is now possible in ClickHouse - see applicable documentation for AWS and GCP as examples 
https://clickhouse.com/docs/en/integrations/s3/s3-merge-tree
https://clickhouse.com/docs/en/integrations/s3/gcs-merge-tree

**Comment by den-crane** [comment]
@tbragin but compute nodes are not disposable. They store data anyway.

**Comment by tbragin** [comment]
@den-crane They store metadata. I simply want to make sure that ClickHouse users are aware that they can leverage object storage as a primary store for data in ClickHouse tables, with object storage being shared between compute nodes. When users ask me personally about "shared nothing architectures" and "separation of storage and compute" in ClickHouse, 9/10 times this is what is behind that question.
