### ISSUE TITLE
Support for filepath() Function to Retrieve Source File Path as a Column During Ingestion

### ISSUE THREAD

**Issue by rohithreddykota** [ClickHouse/ClickHouse#71792]
**Description:**

It would be highly beneficial if ClickHouse could natively support a filepath() function (or similar) to retrieve the full path of source files as a column when ingesting data from external storage systems, such as S3 or the local file system. This feature would streamline data ingestion workflows by automatically including the file path of each row’s source file as a column in SQL queries, especially when reading from multiple files.

**Use Case:**

In data engineering workflows, it’s often critical to know the origin of each row, particularly when working with partitioned or distributed datasets across multiple files. Currently, ClickHouse users must rely on external scripts to add file paths as columns, introducing unnecessary complexity. A filepath() function within SQL would greatly simplify this process, making ClickHouse more efficient and user-friendly for large-scale ingestion tasks.

**Example Syntax:**

This feature could look something like this:

```sql
SELECT *, filepath() AS source_file
FROM s3('https://bucket-name.s3.amazonaws.com/path/to/files/*.parquet', 'AWS_ACCESS_KEY', 'AWS_SECRET_KEY', 'Parquet');
```

In this example, filepath() would return the full path of each file being read, effectively adding a source_file column to the result with the path of each row’s source file.

**Comment by ucasfl** [comment]
Use `_path` virtual column: https://clickhouse.com/docs/en/engines/table-engines/integrations/s3#virtual-columns

```sql
SELECT *, filepath() AS source_file
FROM s3('https://bucket-name.s3.amazonaws.com/path/to/files/*.parquet', 'AWS_ACCESS_KEY', 'AWS_SECRET_KEY', 'Parquet');
```
can be 
```sql
SELECT *, _path AS source_file
FROM s3('https://bucket-name.s3.amazonaws.com/path/to/files/*.parquet', 'AWS_ACCESS_KEY', 'AWS_SECRET_KEY', 'Parquet');
```
