### ISSUE TITLE
How CH <-> Kafka works

### ISSUE THREAD

**Issue by boldakovds** [ClickHouse/ClickHouse#71797]
### Question

1) What's logic of work between kafka and CH?
a) consuming (for example)
CH read from kafka -> switch offset -> write to mv -> write to table -> remove data from mv
b) producing (for example)
insert into table -> write to mv -> remove data from mv -> write to kafka_engine -> write to kafka

2) If i make a restart service (or other reason of terminating CH service) on any of steps on point (1) can i lost/duplicate a data on consuming/producing?
for example (producing) - when i restart CH after write to kafka, but CH still hasn't delete data from mv and after starting data will be duplicating into kafka 
for example (consuming) - when i restart CH after read from kafka and switching offset, but not writing to mv

How i can protect myself from losting/duplicating a data?

3) We have a long pipeline of table/mv:
kafka_engine -> mv1 -> table1 -> mv2 -> table2 -> mv3 -> table3
When i restart CH we can have a situation:
attach kafka_engine -> mv1 -> table1 (starting parsing data from kafka)
attach something else
attach mv2 -> table2 -> mv3 -> table3

So we can lost a data between attach "kafka_engine -> mv1 -> table1" and "mv2 -> table2 -> mv3 -> table3", because mv2 will not knew about data parsing before attach. 

Is exist an order for attach mv/table and can i control it? How i can protect myself from losting a data on this case?

**Comment by antaljanosbenjamin** [comment]
> What's logic of work between kafka and CH?

That is a too broad question to answer it in details. As a start you can read our [docs](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka).

> a) consuming (for example)
> CH read from kafka -> switch offset -> write to mv -> write to table -> remove data from mv

ClickHouse only commits the offset to Kafka once the messages are written to all materialized views and tables. It is important that you don't enable `materialized_views_ignore_errors`.

> b) producing (for example)
> insert into table -> write to mv -> remove data from mv -> write to kafka_engine -> write to kafka 

In this case the materialized view doesn't really store the data, only passes it to the Kafka engine to produce the necessary messages.

> If i make a restart service (or other reason of terminating CH service) on any of steps on point (1) can i lost/duplicate a data on consuming/producing?

Yes. Currently for consuming messages we only support at least one semantics. That means you might have duplicated messages. E.g.: all the data is written to the tables but ClickHouse is forcefully terminated before it could commit the offset to Kafka. In that case ClickHouse will read the same messages again.

On the producing side you can lose data I think, but I am less confident about it. If you write data to a table and ClickHouse terminates before it is written to Kafka (as we don't store the data in materialized views) you can lose message. In general I think producing by default has at least once semantics.

> for example (producing) - when i restart CH after write to kafka, but CH still hasn't delete data from mv and after starting data will be duplicating into kafka

As we don't store data in materialized views used to write to Kafka, you can lose messages, but not duplicate them when producing.

> for example (consuming) - when i restart CH after read from kafka and switching offset, but not writing to mv

We first store the data and then commit the offset.

> We have a long pipeline of table/mv:
> kafka_engine -> mv1 -> table1 -> mv2 -> table2 -> mv3 -> table3
> When i restart CH we can have a situation:
> attach kafka_engine -> mv1 -> table1 (starting parsing data from kafka)
> attach something else
> attach mv2 -> table2 -> mv3 -> table3

If you attach the tables manually, then yes, this can happen. However if you are talking about ClickHouse automated loading of tables on startup, then it will first load the materialized views that has to be triggered upon insertion before loading the table, thus guaranteeing that materialized views will receive every inserted data.

**Comment by boldakovds** [comment]
Thanks for you answers!

When CH delete data from mv?
1) insert data to mv
2) insert data to table
3) delete data from mv
or
1) insert data to mv
3) delete data from mv
2) insert data to table

**Comment by antaljanosbenjamin** [comment]
> When CH delete data from mv?

Materialized views that are used to pass data from one table to another don't store any data. They only keep the data in memory and pass it to the target table. Storing the data is the responsibility of the target table.

**Comment by boldakovds** [comment]
So can i lose data when CH will be restarted in moment when data will be in memory (mv), but not in target table?
Can i protect myself from data lost on high-load CH with many mv on planning restart (or terminating on other reason)?

**Comment by antaljanosbenjamin** [comment]
> So can i lose data when CH will be restarted in moment when data will be in memory (mv), but not in target table?

If the source of the data is Kafka, then Kafka will insert the data again once it is recovered. If the source of the data is regular inserts, then you have to take care of the reinsertion as the insert will fail (unless you use the fire and forget (`async_insert = 1, wait_for_async_insert = 0`). And it is not connected to restarting services. On resarts ClickHouse takes care of materialized views properly.

> Can i protect myself from data lost on high-load CH with many mv on planning restart (or terminating on other reason)?

I think the best way is to do it to nodes one-by-one, stop replicated engines, do not allow new connections to the nodes and once all the connections are closed, restart the node.
