### ISSUE TITLE
toDayOfWeek on WHERE condition with primary key breaks on updating clickhouse (Bad get)

### ISSUE THREAD

**Issue by udiz** [ClickHouse/ClickHouse#71810]
**Describe the unexpected behaviour**
using `toDayOfWeek` as part of a WHERE condition in a select query fails after updating clickhouse to 24.8+.

reproduce here:
https://fiddle.clickhouse.com/8a03ec44-0ff7-4e45-8e85-8f3d9159e72c
fails on 24.8, succeeds on 24.7.

The error does not reproduce when the table is not ordered by the timestamp (https://fiddle.clickhouse.com/ee226b86-231d-4f6d-9815-14b0eab341d3), or when using a Memory table engine. Using this function in the SELECT part works. Also, similar functions like `toDayOfMonth` seem to work as usual.

Thanks!

**Comment by Algunenano** [comment]
Seems introduced in https://github.com/ClickHouse/ClickHouse/pull/68135
