### ISSUE TITLE
ClickHouse encounters persistent high memory levels

### ISSUE THREAD

**Issue by fdf1779** [ClickHouse/ClickHouse#71848]
### Question

Version: 22.x
I encountered a problem of ClickHouse memory loss and high memory usage for a long time while using it. Even after restarting the service, the memory usage still reached a high level in a short period of time.
![image](https://github.com/user-attachments/assets/4f9c36ff-88aa-44e4-9e92-5660da6f1a97)
No obvious abnormalities were found when investigating the memory usage of merge and query
But when I delete a MergeTree table, there will be a significant decrease in memory
![image](https://github.com/user-attachments/assets/df239c21-e866-4183-88da-769254faa5b9)
Based on this situation, I suspect that there may be a phenomenon of caching the entire MergeTree table in memory, and how to solve this problem.

**Comment by Algunenano** [comment]
Please report possible issues on supported releases.

**Comment by fdf1779** [comment]
> can you please share the output of
> 
> ```sql
> SELECT
>     sumIf(data_uncompressed_bytes, part_type = 'InMemory') as memory_parts,
>     formatReadableSize(sum(primary_key_bytes_in_memory)) AS primary_key_bytes_in_memory,
>     formatReadableSize(sum(primary_key_bytes_in_memory_allocated)) AS primary_key_bytes_in_memory_allocated
> FROM system.parts;
> 
> SELECT *, formatReadableSize(value) 
> FROM system.asynchronous_metrics 
> WHERE metric like '%Cach%' or metric like '%Mem%' 
> order by metric format PrettyCompactMonoBlock;
> 
> 
> SELECT formatReadableSize(sum(bytes_allocated)) FROM system.dictionaries;
> ```
> 
> Version: 22.x is out of support.

![image](https://github.com/user-attachments/assets/29093d7f-0fb2-490c-ae6f-2aed8819a01c)
![image](https://github.com/user-attachments/assets/811d6897-a33f-40ef-b9cb-e91250589310)
This is result

**Comment by fdf1779** [comment]
> can you please share the output of
> 
> ```sql
> SELECT
>     sumIf(data_uncompressed_bytes, part_type = 'InMemory') as memory_parts,
>     formatReadableSize(sum(primary_key_bytes_in_memory)) AS primary_key_bytes_in_memory,
>     formatReadableSize(sum(primary_key_bytes_in_memory_allocated)) AS primary_key_bytes_in_memory_allocated
> FROM system.parts;
> 
> SELECT *, formatReadableSize(value) 
> FROM system.asynchronous_metrics 
> WHERE metric like '%Cach%' or metric like '%Mem%' 
> order by metric format PrettyCompactMonoBlock;
> 
> 
> SELECT formatReadableSize(sum(bytes_allocated)) FROM system.dictionaries;
> ```
> 
> Version: 22.x is out of support.

![image](https://github.com/user-attachments/assets/23fff7fd-d7f9-4de2-94d0-8f77c2c282df)
![image](https://github.com/user-attachments/assets/2ef9662f-ddcf-4a5a-adaf-914009c6c595)
This is result
