### ISSUE TITLE
Merge as of functionality for  time series

### ISSUE THREAD

**Issue by feribg** [ClickHouse/ClickHouse#7184]
I'm wondering if a relative join on time series columns is currently  supported as an expression and if not what  would be  the most efficient way to achieve  that within CH. Here's a concrete example of a very common user case in financial time series, where we want  to correlate one stream with  the `last` price of another stream where  the two timestamps might not  match perfectly, but  one needs to precede  the other.

https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.merge_asof.html

**Comment by den-crane** [comment]
ASOF JOIN was implemented to solve this particular problem.


https://clickhouse.yandex/docs/en/query_language/select/

ASOF JOIN is useful when you need to join records that have no exact match.

**Comment by feribg** [comment]
Thanks @den-crane . And I assume the operator  is always `table_1.asof_column >= table2.asof_column` gt or equal, you can't  enforce strict inequality?

**Comment by blinkov** [comment]
@feribg this is a separate feature to implement, see #6337
