### ISSUE TITLE
Deduplication of ReplacingMergeTree and Count

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#7188]
I have table with 1B records unique by id field. I have more recent versions of that records with the same id. I'm using ReplacingMergeTree(version). I need count of that ids. I know that deduplication  is not realtime. 

So, I use uniqExact to count unique (id) which is very slow. 80 sec on standalone server. Uniq is very aproximate and it take 8 seconds to complete, count is 0.8 seconds. Is any way to speedup count or something like countLatest(version). 
I've read all issues but didn't find any answer.

**Comment by filimonov** [comment]
you can try also 
```
select count() from table xyz final;
```

**Comment by thyn** [comment]
doesn't help

count(1) takes 0.9 sec
uniqExact(id) takes 35 sec
count(1)  final takes 53 sec

**Comment by thyn** [comment]
didn't find any solution
