### ISSUE TITLE
Unable to run server of Clickhouse instances.

### ISSUE THREAD

**Issue by anilxoxo** [ClickHouse/ClickHouse#7189]
I have created two instances of config.xml as config-1.xml and config-2.xml .Just by copying the config.xml and I edited the following in config.xml file 
 I wanted to make Replication in two instances with one shard.
I used the following code to run the servers
clickhouse-server --config-file=/etc/clickhouse-server/config.xml

but I am unable to start. .Please tell me how to do replication in clickhouse

**Comment by alexey-milovidov** [comment]
> but I am unable to start

How does it look?

**Comment by blinkov** [comment]
@anilxoxo, do you have any further questions?
