### ISSUE TITLE
How to get the original json content? 

### ISSUE THREAD

**Issue by 9997766** [ClickHouse/ClickHouse#71905]
### Company or project name

abc

### Question

I create table use JSON type，as ：
create table test （ id String , data JSON）engine ReplicatedReplacingMergeTree(...) PRIMARY KEY (source,id);

insert into test  ( id,data) FORMAT Values (  '1',  '{"a" : "aaa","b" : "bbb"}' ); 
insert into test  ( id,data) FORMAT Values (  '2',  '{"c" : "ccc","d" : "ddd","e" : "e"}' ); 

when I query like this：
select id，toJSONString(data) from test  ;

I get :
 1,  {a : "aaa",b : "bbb",c:"",d:"",e:"”}
 2,  {a : "",b : "",c:"ccc",d:"ddd",e:"eee”}

I want to get the original structure: 
 1,  {a : "aaa",b : "bbb"}
 2,  {c:"ccc",d:"ddd",e:"eee”}

For  some reasons, I can not change "data" field to "String" type;  
Can I achieve the effect described above? How to ? 

Thanks very much!

**Comment by UnamedRus** [comment]
Which ClickHouse version?

https://fiddle.clickhouse.com/cb72a134-1cc8-4977-8c7a-2ddb805411f5

**Comment by 9997766** [comment]
the version is 23.8.2.7 

or  the latest version can make it ?

> Which ClickHouse version?
> 
> https://fiddle.clickhouse.com/cb72a134-1cc8-4977-8c7a-2ddb805411f5

**Comment by Avogar** [comment]
In 24.8 release we added new implementation of [JSON](https://clickhouse.com/docs/en/sql-reference/data-types/newjson) data type. You are using old experimental [Object](https://clickhouse.com/docs/en/sql-reference/data-types/object-data-type) data type that is deprecated and not supported anymore (it was always experimental and not ready for production)
