### ISSUE TITLE
Address: NULL pointer. Access: read. Unknown si_code in 24.4.4.113

### ISSUE THREAD

**Issue by seilerre** [ClickHouse/ClickHouse#71927]
**How to reproduce**

Version: 24.4.4.113

We updated our Kubernetes Cluster and Clickhouse Pods were restarted WITHOUT changing the version of the image. it is pinned to 24.4.4.113. Restarted Pods don't start again and fail with the error below

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

2024.11.14 13:45:40.964341 [ 68 ] {} <Information> ep_pyro_fhir_stage.observations_v1 (ReplicatedMergeTreePartCheckThread): Checking part all_2637089_2637089_0
2024.11.14 13:45:40.964641 [ 68 ] {} <Warning> ep_pyro_fhir_stage.observations_v1 (ReplicatedMergeTreePartCheckThread): We have part all_2636860_2637224_145 covering part all_2637089_2637089_0, will not check
2024.11.14 13:45:40.999435 [ 757 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: D24B0AE293FB8865389D17B996679AE9)
2024.11.14 13:45:40.999631 [ 757 ] {} <Information> SentryWriter: Not sending crash report
2024.11.14 13:45:40.999642 [ 757 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues
2024.11.14 13:45:44.855269 [ 758 ] {} <Fatal> BaseDaemon: ########## Short fault info ############
2024.11.14 13:45:44.855373 [ 758 ] {} <Fatal> BaseDaemon: (version 24.4.4.113 (official build), build id: CDE7BFE9A8091F68B6DEA9EF6BF85A71B80741CF, git hash: d63a54957bdd9b8f4c5bc78f5bbceec3b36bd528) (from thread 702) Received signal 11
2024.11.14 13:45:44.855425 [ 758 ] {} <Fatal> BaseDaemon: Signal description: Segmentation fault
2024.11.14 13:45:44.855457 [ 758 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.11.14 13:45:44.855488 [ 758 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000cc634a1 0x00007f948bd76420 0x00007f948bb88942 0x000000001728eea4 0x00000000172ac38d 0x000000000cafaac8 0x0000000012a9b524 0x0000000012ac2f98 0x0000000012b960b4 0x00000000103cdced 0x00000000103de41f 0x00000000103e225e 0x00000000103db9ae 0x00000000103f57fe 0x000000000ca6990d 0x00007f948bd6a609 0x00007f948bc85353
2024.11.14 13:45:44.855523 [ 758 ] {} <Fatal> BaseDaemon: ########################################
2024.11.14 13:45:44.855555 [ 758 ] {} <Fatal> BaseDaemon: (version 24.4.4.113 (official build), build id: CDE7BFE9A8091F68B6DEA9EF6BF85A71B80741CF, git hash: d63a54957bdd9b8f4c5bc78f5bbceec3b36bd528) (from thread 702) (no query) Received signal Segmentation fault (11)
2024.11.14 13:45:44.855584 [ 758 ] {} <Fatal> BaseDaemon: Address: NULL pointer. Access: read. Unknown si_code.
2024.11.14 13:45:44.855602 [ 758 ] {} <Fatal> BaseDaemon: Stack trace: 0x000000000cc634a1 0x00007f948bd76420 0x00007f948bb88942 0x000000001728eea4 0x00000000172ac38d 0x000000000cafaac8 0x0000000012a9b524 0x0000000012ac2f98 0x0000000012b960b4 0x00000000103cdced 0x00000000103de41f 0x00000000103e225e 0x00000000103db9ae 0x00000000103f57fe 0x000000000ca6990d 0x00007f948bd6a609 0x00007f948bc85353
2024.11.14 13:45:44.855694 [ 758 ] {} <Fatal> BaseDaemon: 0. signalHandler(int, siginfo_t*, void*) @ 0x000000000cc634a1
2024.11.14 13:45:44.855718 [ 758 ] {} <Fatal> BaseDaemon: 1. ? @ 0x00007f948bd76420
2024.11.14 13:45:44.855727 [ 758 ] {} <Fatal> BaseDaemon: 2. ? @ 0x00007f948bb88942
2024.11.14 13:45:44.855743 [ 758 ] {} <Fatal> BaseDaemon: 3. ? @ 0x000000001728eea4
2024.11.14 13:45:44.855759 [ 758 ] {} <Fatal> BaseDaemon: 4. ? @ 0x00000000172ac38d
2024.11.14 13:45:44.855782 [ 758 ] {} <Fatal> BaseDaemon: 5. DB::IAST::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x000000000cafaac8
2024.11.14 13:45:44.855803 [ 758 ] {} <Fatal> BaseDaemon: 6. DB::ASTCreateQuery::formatQueryImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x0000000012a9b524
2024.11.14 13:45:44.855821 [ 758 ] {} <Fatal> BaseDaemon: 7. DB::ASTQueryWithOutput::formatImpl(DB::IAST::FormatSettings const&, DB::IAST::FormatState&, DB::IAST::FormatStateStacked) const @ 0x0000000012ac2f98
2024.11.14 13:45:44.855851 [ 758 ] {} <Fatal> BaseDaemon: 8. DB::serializeAST(DB::IAST const&) @ 0x0000000012b960b4
2024.11.14 13:45:44.855876 [ 758 ] {} <Fatal> BaseDaemon: 9. DB::DDLTaskBase::formatRewrittenQuery(std::shared_ptr<DB::Context const>) @ 0x00000000103cdced
2024.11.14 13:45:44.855892 [ 758 ] {} <Fatal> BaseDaemon: 10. DB::DDLWorker::initAndCheckTask(String const&, String&, std::shared_ptr<zkutil::ZooKeeper> const&) @ 0x00000000103de41f
2024.11.14 13:45:44.855901 [ 758 ] {} <Fatal> BaseDaemon: 11. DB::DDLWorker::scheduleTasks(bool) @ 0x00000000103e225e
2024.11.14 13:45:44.855913 [ 758 ] {} <Fatal> BaseDaemon: 12. DB::DDLWorker::runMainThread() @ 0x00000000103db9ae
2024.11.14 13:45:44.855937 [ 758 ] {} <Fatal> BaseDaemon: 13. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<true, true>::ThreadFromGlobalPoolImpl<void (DB::DDLWorker::*)(), DB::DDLWorker*>(void (DB::DDLWorker::*&&)(), DB::DDLWorker*&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000103f57fe
2024.11.14 13:45:44.855961 [ 758 ] {} <Fatal> BaseDaemon: 14. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000ca6990d
2024.11.14 13:45:44.855974 [ 758 ] {} <Fatal> BaseDaemon: 15. ? @ 0x00007f948bd6a609
2024.11.14 13:45:44.855982 [ 758 ] {} <Fatal> BaseDaemon: 16. ? @ 0x00007f948bc85353
2024.11.14 13:45:44.995664 [ 758 ] {} <Fatal> BaseDaemon: Integrity check of the executable successfully passed (checksum: D24B0AE293FB8865389D17B996679AE9)
2024.11.14 13:45:44.995853 [ 758 ] {} <Information> SentryWriter: Not sending crash report
2024.11.14 13:45:44.995863 [ 758 ] {} <Fatal> BaseDaemon: Report this error to https://github.com/ClickHouse/ClickHouse/issues

**Additional context**

Running in Kubernetes

**Comment by Algunenano** [comment]
24.4 is not supported. Please update to a supported release
