### ISSUE TITLE
Discrepancy in using uniqExactState/Merge with different ORDER BY keys

### ISSUE THREAD

**Issue by sduluganti** [ClickHouse/ClickHouse#71953]
When I use materialized views with `uniqExactState` and later `uniqExactMerge` to view the results, I'm seeing different results between MV table vs running the same query against source table. 

**How to reproduce**

I think this happening with any (recent) version of CH.

Create test DB:
```sql
CREATE DATABASE IF NOT EXISTS SI_TEST_DB;
```

Create source table:
```sql
CREATE OR REPLACE TABLE SI_TEST_DB.main_table (
    pageview_guid                       String                         CODEC(ZSTD),
    tag_id                              LowCardinality(String)       CODEC(ZSTD),
    event_guid                          String                         CODEC(ZSTD)
) ENGINE = MergeTree()
PRIMARY KEY (tag_id);
```

Create table for MV:
```sql
CREATE OR REPLACE TABLE SI_TEST_DB.ag_tag_events_count (
    pageview_guid                String                                   CODEC(ZSTD),
    tag_id                       LowCardinality(String)                 CODEC(ZSTD),
    instances                    AggregateFunction(uniqExact, String)     CODEC(ZSTD)
) ENGINE = AggregatingMergeTree()
PRIMARY KEY (tag_id);
```

Create MV:
```sql
-- DROP VIEW SI_TEST_DB.mv_ag_tag_events_count; -- Drop the materialized view if it exists
CREATE MATERIALIZED VIEW SI_TEST_DB.mv_ag_tag_events_count TO SI_TEST_DB.ag_tag_events_count AS
SELECT
    pageview_guid,
    tag_id,
    uniqExactState(event_guid) as instances
FROM SI_TEST_DB.main_table
GROUP BY ALL;
```

Insert data to source table:
```sql
INSERT INTO SI_TEST_DB.main_table (pageview_guid, tag_id, event_guid) VALUES
('pageview_guid_1','tag_1','event_guid_1'),
('pageview_guid_3','tag_1','event_guid_3'),
('pageview_guid_2','tag_1','event_guid_2'),
('pageview_guid_4','tag_2','event_guid_4');
```

Query the source table:
```sql
SELECT 
    pageview_guid,
    tag_id,
    uniqExact(event_guid) AS instances
FROM SI_TEST_DB.main_table
GROUP BY ALL;
```

Result:
```
pageview_guid  |tag_id|instances|
---------------+------+---------+
pageview_guid_2|tag_1 |        1|
pageview_guid_3|tag_1 |        1|
pageview_guid_4|tag_2 |        1|
pageview_guid_1|tag_1 |        1|
```

Query the MV table:
```sql
SELECT 
    pageview_guid,
    tag_id,
    uniqExactMerge(instances) AS instances
FROM SI_TEST_DB.ag_tag_events_count
GROUP BY ALL;
```
**Unexpected** result:
```
pageview_guid  |tag_id|instances|
---------------+------+---------+
pageview_guid_2|tag_1 |        3|
pageview_guid_4|tag_2 |        1|
```

The end result when running the query against MV table must match with the result of querying the source table.

If I create the MV table `ag_tag_events_count` with `PRIMARY KEY (pageview_guid)`, I'm getting the correct result. It seems, here the ClickHouse is not considering the columns we specified in the GROUP BY clause of materialized view query. Rather it is using the PRIMARY KYE/ORDER BY columns to group the intermediate state data in `uniqExactState`.

**Comment by den-crane** [comment]
Your AggregatingMergeTree has incorrect KEY `PRIMARY KEY (tag_id)` has to be `PRIMARY KEY (tag_id, pageview_guid)`.
AggregatingMergeTree for all columns which are not part of the KEY and does not have Agg func. is calculated using `any`.

https://fiddle.clickhouse.com/fa3c1820-8299-4cce-a241-9af175e180b5

Also `uniqExact` is not the best approach to MATERIALIZED VIEW. Your queries against `ag_tag_events_count` will be always much slower than queries against `main_table` because `AggregateFunction(uniqExact` stores the raw data (the exact same data as `main_table`. Try to use other uniq functions https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/uniqhll12 or https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/uniqcombined64#agg_function-uniqcombined64

**Comment by den-crane** [comment]
>It seems, here the ClickHouse is not considering the columns we specified in the GROUP BY clause of materialized view query.

Materialized view is not aware about AggregatingMergeTree. AggregatingMergeTree is aware about Materialized view. They are decoupled.

https://den-crane.github.io/Everything_you_should_know_about_materialized_views_commented.pdf

**Comment by sduluganti** [comment]
>AggregatingMergeTree for all columns which are not part of the KEY and does not have Agg func. is calculated using `any`.

This is the key information I was missing. I didn't know the `AggregatingMergeTree` would aggregate all but `PRIMARY KEY` columns.

Thank you for linking the PDF. It is going to be a good reference doc.
