### ISSUE TITLE
Function formatReadableTimeDelta accepts only 2 parameters, not 3

### ISSUE THREAD

**Issue by PBorovskiy** [ClickHouse/ClickHouse#71962]
The function `formatReadableTimeDelta`, according to documentation, should accept 1 or 3 parameters:

[formatReadableTimeDelta docs](https://clickhouse.com/docs/en/sql-reference/functions/other-functions#formatreadabletimedelta
): `formatReadableTimeDelta(column[, maximum_unit, minimum_unit])
`

There are three attempts:

`select formatReadableTimeDelta(100000000)`      —>   3 years, 2 months, 1 day, 9 hours, 46 minutes and 40 seconds
`select formatReadableTimeDelta(100000000, 'hours')`   —> 27777 hours, 46 minutes and 40 seconds
`select formatReadableTimeDelta(100000000, 'hours', 'minutes')`   —> SQL Error [42] [07000]: Code: 42. DB::Exception: Number of arguments for function formatReadableTimeDelta doesn't match: passed 3, should be at most 2

**Expected behavior**
`select formatReadableTimeDelta(100000000, 'hours', 'minutes')` —>  27777 hours and 46 minutes

My ClickHouse version: 23.5.3.24

**Comment by Algunenano** [comment]
> My ClickHouse version: 23.5.3.24

Your CH version is old and did not support the 3rd argument. Please update to a supported release.
