### ISSUE TITLE
a few nginx logs through vector failed into clickhouse

### ISSUE THREAD

**Issue by marksmansj** [ClickHouse/ClickHouse#71961]
### Question

Hello everyone. In my senario. I use vector to send nginx log into clickhouse. most of the logs can be store into clickhouse correctly . but a few logs can not .

1、this is my nginx log
{"timestamp":"1731658748468","local_time":"2024-11-15T16:19:08+08:00","hostname":"pubng-01-zg.host.yyts.com","request_method":"GET","request_uri":"/index-1.html","status": "200","request_time":"0.014","request_length":"488","http_referer":"","http_user_agent":"Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)","http_host":"gold.yyts.com","http_x_forwarded_for":"116.179.32.230","remote_addr":"175.4.54.147","bytes_sent":"25797","body_bytes_sent":"25457","upstream_response_time":"0.014","upstream_addr":"10.10.0.158:80","upstream_cache_status":"EXPIRED","upstream_status":"200"}

2、vecor conf
sources:
        track_nginx_access:
                type: "file"
                include:
                        - "/nginx/logs/access.log"
                read_from: "end"

transforms:
        process_nginx_access:
                type: "remap"
                inputs:
                        - "track_nginx_access"
                source: |
                        .=parse_json!(.message)

sinks:
  clickhouse_nginx_access:
    type: clickhouse
    inputs:
      - process_nginx_access
    endpoint: http://192.168.0.120:8123
    database: lb
    table: nginx_log
    skip_unknown_fields: true
    date_time_best_effort: true

3、clickhouse error log
2024.11.15 16:19:09.394291 [ 203047 ] {7f4de812-f73c-41a8-88de-d56561cdf7ba} <Error> DynamicQueryHandler: Code: 27. DB::Exception: Cannot parse input: expected '"' before: '-11-15T08:19:08.463826760Z"}\n{"body_bytes_sent":"25457","bytes_sent":"25797","hostname":"pubng-01-zg.host.yyts.com","http_host":"gold.yyts.com","h': (while reading the value of key timestamp): (at row 10)
: While executing ParallelParsingBlockInputFormat. (CANNOT_PARSE_INPUT_ASSERTION_FAILED), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000daffc3b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000007e59fcc
2. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x0000000007e83d0b
3. DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) @ 0x000000000db78809
4. DB::SerializationNumber<unsigned long>::deserializeTextJSON(DB::IColumn&, DB::ReadBuffer&, DB::FormatSettings const&) const @ 0x0000000007a15849
5. DB::JSONUtils::readField(DB::ReadBuffer&, DB::IColumn&, std::shared_ptr<DB::IDataType const> const&, std::shared_ptr<DB::ISerialization const> const&, String const&, DB::FormatSettings const&, bool) @ 0x0000000013146cef
6. DB::JSONEachRowRowInputFormat::readJSONObject(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&) @ 0x000000001315b607
7. DB::JSONEachRowRowInputFormat::readRow(std::vector<COW<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::mutable_ptr<DB::IColumn>>>&, DB::RowReadExtension&) @ 0x000000001315bdce
8. DB::IRowInputFormat::read() @ 0x00000000130ae3bc
9. DB::IInputFormat::generate() @ 0x0000000013054556
10. DB::ISource::tryGenerate() @ 0x000000001303219b
11. DB::ISource::work() @ 0x0000000013031ea7
12. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ParallelParsingInputFormat::scheduleParserThreadForUnitWithNumber(unsigned long)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000131ad761
13. ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::worker(std::__list_iterator<ThreadFromGlobalPoolImpl<false, true>, void*>) @ 0x000000000dbd4649
14. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl<false, true>::ThreadFromGlobalPoolImpl<void ThreadPoolImpl<ThreadFromGlobalPoolImpl<false, true>>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>(void&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x000000000dbd8791
15. void* std::__thread_proxy[abi:v15007]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, void ThreadPoolImpl<std::thread>::scheduleImpl<void>(std::function<void ()>, Priority, std::optional<unsigned long>, bool)::'lambda0'()>>(void*) @ 0x000000000dbd7509
16. start_thread @ 0x00000000000081ca
17. clone @ 0x00000000000398d3
 (version 24.8.4.13 (official build))

4、this is the db schema：
(
    `timestamp` UInt64,
    `local_time` DateTime,
    `hostname` String,
    `request_method` LowCardinality(String),
    `request_uri` String,
    `status` Int64,
    `request_time` Float64,
    `request_length` Int64,
    `http_referer` String,
    `http_user_agent` String,
    `http_host` String,
    `http_x_forwarded_for` String,
    `remote_addr` String,
    `bytes_sent` Int64,
    `body_bytes_sent` Int64,
    `upstream_response_time` String,
    `upstream_addr` String,
    `upstream_cache_status` String,
    `ck_assembly_extension` String
)

anyone know how to resovle this issue ?

**Comment by ArctypeZach** [comment]
@marksmansj - can you share an example record that is failing?  Seems like it is unable to parse the timestamp field (according to the error message).  There are some settings that can be applied to adjust datetime parsing.  For example, you can try attaching the setting `date_time_input_format=best_effort`

**Comment by hanfei1991** [comment]
Could you provide more details to reproduce this case? Like how to create table, the insert statement, etc
