### ISSUE TITLE
uninstall clickhouse

### ISSUE THREAD

**Issue by anilxoxo** [ClickHouse/ClickHouse#7197]
I am unable to uninstall clickhouse from my machine ubuntu 16.04

**Comment by den-crane** [comment]
Please, show the output 
apt-get -y remove clickhouse*

**Comment by anilxoxo** [comment]
> Please, show the output
> apt-get -y remove clickhouse*

Not working.unable to remove file inside the **preprocessed**

**Comment by den-crane** [comment]
apt-get remove -y --force-yes clickhouse*

**Comment by alexey-milovidov** [comment]
When you uninstall database server, the data (including preprocessed files) remains. This is normal.

**Comment by derekmahar** [comment]
How does one remove ClickHouse after installing it using the command `curl https://clickhouse.com/ | sh`?

**Comment by derekmahar** [comment]
> How does one remove ClickHouse after installing it using the command `curl https://clickhouse.com/ | sh`?

The command in this [comment](https://github.com/ClickHouse/ClickHouse/issues/38877#issuecomment-1590562695) removes all ClickHouse binary, configuration, and log files from a system as well as user and group `clickhouse`.
