### ISSUE TITLE
Cache for primary index

### ISSUE THREAD

**Issue by CurtizJ** [ClickHouse/ClickHouse#71992]
**Use case**

In some extremely large workloads (trillions of rows) primary index may take significant amount of memory: tens or hundreds of GBs. Instead we can use cache for primary similar to mark cache instead of always storing index for parts.

**Describe the solution you'd like**

Use a cache similar to mark cache. If lazy load and primary index cache are enabled store index in that cache instead of storing it in data part.

**Describe alternatives you've considered**

Lazy load of index, but the problem is that index is never evicted and once primary index was analyzed for some query the index will be stored in memory until restart or `SYSTEM UNLOAD PRIMARY KEY` query.

**Comment by UnamedRus** [comment]
> In some extremely large workloads (trillions of rows) primary index may take significant amount of memory: tens or hundreds of GBs. Instead we can use cache for primary similar to mark cache instead of always storing index for parts.

Can CH just load not every mark, but every X mark instead?

**Comment by CurtizJ** [comment]
Yes, it's one possible solution. Basically it's the same as increasing `index_granularity` but more flexible because it can be easily changed. I'm afraid that it may affect performance significantly when you want to thin out index a lot. Maybe it's a good idea to make it adaptive and load every X mark, but start from X=1 for hot parts and increase X for colder ones.

**Comment by CurtizJ** [comment]
I agree that it is maybe a questionable feature (it will be disabled by default). It works in case when queries read mostly from fresh parts and other parts are filtered by `minmax` index of partition key columns (or by `minmax` index/statistic of any column in the future) or partition pruning. In that case performance won't be affectedby bigger ranges selected by PK analysis on a regular workload. Primary index cache works here as a safety measure in a complement to the lazy load of index, because now there may be a case when server works well on a regular workload but one inaccurate query may read indexes of all parts and consume a lot of memory and server will required manual intervention.
