### ISSUE TITLE
[HELP] Dask integration

### ISSUE THREAD

**Issue by kszucs** [ClickHouse/ClickHouse#720]
We're trying to integrate clickhouse to our current architecture (already using dask and mesos).

I'm planning to implement clickhouse support for [dask](https://github.com/dask/dask) and [distributed](https://github.com/dask/distributed).

Could You give me some advice? How to handle data locality? Where to deploy distributed workers? Should I just use HTTP client or work directly on clichouse files?

@frol migth be interested too

**Comment by kszucs** [comment]
Are there any batch processing frameworks already integrated with clickhouse?

**Comment by blinkov** [comment]
What exactly this integration is supposed to allow to do?

**Comment by cloudronin** [comment]
I am guessing It should allow to reading and writing dask dataframes from clickhouse using the HTTP API similar to how @kszucs did for pandas here: https://github.com/kszucs/pandahouse

**Comment by kszucs** [comment]
Well, I forgot about this one. For long term the best would be to implement a native clickhouse client in https://github.com/apache/arrow with python bindings, then We could efficiently read data from clickhouse to arrow/pandas.

**Comment by martindurant** [comment]
Worth saying: if you can read to pandas dataframes based on a query, would be simple enough to partition up that query and have dataframes read fro each part, to form a Dask dataframe. You could do this with `dask.delayed`, `dd.from_delayed`; a similar process is used for most of the dataframe input functions in Dask.

**Comment by kszucs** [comment]
If anyone interested to develop what @martindurant suggested, use [clickhouse-drive](https://github.com/mymarilyn/clickhouse-driver) or [ibis's clickhouse backend](https://github.com/ibis-project/ibis) instead of pandahouse.

**Comment by qoega** [comment]
>For long term the best would be to implement a native clickhouse client in https://github.com/apache/arrow with python bindings, then We could efficiently read data from clickhouse to arrow/pandas.

Can you look on the current state and tell what is left to be done, so if anyone would be interested it will be easier to start?
As I can see [here]( https://github.com/mymarilyn/clickhouse-driver/issues/128#issuecomment-737383837) clickhouse-driver supports numpy arrays and pandas dataframes.
FYI ClickHouse as for now supports gRPC API as well.

**Comment by pkit** [comment]
@blinkov 
> What exactly this integration is supposed to allow to do?

For example help CH to do real batch data processing (shuffle, resharding) in SQL
Right now there is no way to reshuffle tables if it's needed.
Dask engine can be served a proper batch SQL to do expensive operations: https://dask-sql.readthedocs.io/en/latest/sql.html

**Comment by martindurant** [comment]
Furthermore, if you have python-specific functions you need to run (the full pydata ecosystem), server size viz rendering or input of datasets from other sources - and you want to do all these things in parallel and chunk-wise - you need dask.

**Comment by pkit** [comment]
> Furthermore, if you have python-specific functions you need to run (the full pydata ecosystem), server size viz rendering or input of datasets from other sources - and you want to do all these things in parallel and chunk-wise - you need dask.

Not really.
Only in case where it's a part of batch job.
If it's online learning/inference - CH executable engine is good enough.
And doing SQL-like transformations in python is not a good idea too. Because of edge cases.

**Comment by amosbird** [comment]
This might be doable via https://github.com/chdb-io/chdb ?

**Comment by Alex-Cheng** [comment]
Is the issue still need help?

**Comment by kszucs** [comment]
Not from my side, closing it.
