### ISSUE TITLE
Implement optional Common Table Expression Materialization

### ISSUE THREAD

**Issue by jirislav** [ClickHouse/ClickHouse#72015]
**Use case**

When defining resource-heavy computation in a CTE and then referencing it multiple times, ClickHouse just blindly runs the CTE as many times as many times it was referenced.

PostgreSQL, on the other hand, has the [Common Table Expression Materialization](https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-CTE-MATERIALIZATION) feature, which by default picks the preferred way of assembling the query execution plan. It will either materialize a CTE, meaning it will cache the result, or not materialize it (for example if filter push-down can reduce the amount of data to read). User has the option to explicitly forbid CTE materialization by using `NOT MATERIALIZED`, or explicitly force CTE materialization by using `MATERIALIZED`.

Example of a real-life query that will suffer from this missing ClickHouse feature:

```sql
WITH prices AS (
  SELECT datetime, symbol, price
  FROM big_price_table

  UNION ALL

  SELECT datetime, symbol, price
  FROM another_big_price_table
), prices_ordered AS (
  SELECT * FROM prices
  ORDER BY datetime
)
SELECT
  t.datetime,
  t.symbol,
  t.amount,
  p.price,
  p_1s.price,
  p_5s.price
FROM small_trades_table t
LEFT ASOF JOIN prices_ordered AS p USING (symbol, datetime)
LEFT ASOF JOIN prices_ordered AS p_1s ON (p_1s.symbol = t.symbol AND p_1s.datetime <= t.datetime + INTERVAL 1 SECOND)
LEFT ASOF JOIN prices_ordered AS p_5s ON (p_5s.symbol = t.symbol AND p_5s.datetime <= t.datetime + INTERVAL 5 SECOND)
```

Both, the debug log and running an explain reveal that both the large price tables are read 3 times. Note that this get much worse once we decide to compute this for 10+ different time shifts.

**Describe the solution you'd like**

For starters, it would be nice to just explicitly ask for CTE materialization, like this:

```sql
WITH prices AS (
  SELECT datetime, symbol, price
  FROM big_price_table

  UNION ALL

  SELECT datetime, symbol, price
  FROM another_big_price_table
), prices_ordered AS MATERIALIZED (  -- <--- Only added MATERIALIZED clause here.
  SELECT * FROM prices
  ORDER BY datetime
)
SELECT
  t.datetime,
  t.symbol,
  t.amount,
  p.price,
  p_1s.price,
  p_5s.price
FROM small_trades_table t
LEFT ASOF JOIN prices_ordered AS p USING (symbol, datetime)
LEFT ASOF JOIN prices_ordered AS p_1s ON (p_1s.symbol = t.symbol AND p_1s.datetime <= t.datetime + INTERVAL 1 SECOND)
LEFT ASOF JOIN prices_ordered AS p_5s ON (p_5s.symbol = t.symbol AND p_5s.datetime <= t.datetime + INTERVAL 5 SECOND)
```

**Additional context**

I have prepared a [fiddle demo](https://fiddle.clickhouse.com/518021bc-f8ba-43b5-985b-f9075a9637e1), which confirms the behavior described above. I have put 60M rows to both price tables, yet ClickHouse plans to read 180M from each price table.

```
   ┌─database─┬─table───────────────────┬─parts─┬──────rows─┬─marks─┐
1. │ default  │ another_big_price_table │    18 │ 180000000 │ 21984 │
2. │ default  │ big_price_table         │    18 │ 180000000 │ 21984 │
3. │ default  │ small_trades_table      │     1 │        60 │     1 │
   └──────────┴─────────────────────────┴───────┴───────────┴───────┘
```

Here is the debug log as reported by the 24.10 ClickHouse server (96 vCPU, 768 GB RAM - r5b.24xlarge) to a 24.10 ClickHouse client, when running the demo: [debug.log](https://github.com/user-attachments/files/17788052/debug.log)

Apart from reading the large datasets multiple times (and unioning + sorting it), also note that the joins are waiting for each other. I'm not sure if this is expected, but it feels like it could be parallelized (as their columns are just appended, without any effect on the other join result).

Not sure if it's related, but comparing Real vs CPU time reveals that more than 90% of the time is spent waiting in `DB::ExecutionThreadContext::wait(std::__1::atomic<bool>&)#/usr/bin/clickhouse`:

![image](https://github.com/user-attachments/assets/155669db-6156-44e0-976c-9452e4aaecfb)

Another issue is that the memory usage is 3x higher than what it would be with cached CTE expression (the debug log confirms this with each join iteration).

![image](https://github.com/user-attachments/assets/5bdeb380-35f9-4a7c-a9ae-92ac4ca8196d)

Having more than 10 time shifts becomes unrealistic to compute as it would require a very large machine.

**Comment by UnamedRus** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/53449

**Comment by canhld94** [comment]
We have materialized CTE implemented internally, test with your [example](https://fiddle.clickhouse.com/518021bc-f8ba-43b5-985b-f9075a9637e1) and it helps, but not significantly faster:

```sql
-- Without materializing CTE
60 rows in set. Elapsed: 36.809 sec. Processed 360.00 million rows, 8.28 GB (9.78 million rows/s., 224.95 MB/s.)
Peak memory usage: 24.83 GiB.

-- With materializing CTE
60 rows in set. Elapsed: 23.788 sec. Processed 480.00 million rows, 11.04 GB (20.18 million rows/s., 464.10 MB/s.)
Peak memory usage: 20.97 GiB.
```

In fact, besides reading and sorting from big tables, the bottleneck of this query is in building the hash join for Aso. If we can build the hash join once and use it in many places, it will significantly save the time.
If it's not Asof but, say Any Left join, then we can have materialized CTE with explicit join table engine:

```
WITH
    prices AS
    (
        SELECT
            datetime,
            symbol,
            price
        FROM big_price_table
        UNION ALL
        SELECT
            datetime,
            symbol,
            price
        FROM another_big_price_table
    ),
    prices_ordered AS MATERIALIZED
    (
        SELECT *
        FROM prices
        ORDER BY datetime ASC
    ) ENGINE = JOIN(ANY, LEFT, symbol, datetime)
SELECT
    t.datetime,
    t.symbol,
    t.amount,
    p.price,
    p_1s.price,
    p_5s.price
FROM small_trades_table AS t
ANY LEFT JOIN prices_ordered AS p ON ...
ANY LEFT JOIN prices_ordered AS p_1s ON ...
ANY LEFT JOIN prices_ordered AS p_5s ON ...
```

Unfortunately the join engine doesn't support Asof now. And seem that hash join for Asof will depend on the join inequality, so not sure if we can reuse the hash join for different join conditions.

**Comment by yawnt** [comment]
@canhld94 that's amazing 😯😯, is there any timeline for making that available in ClickHouse? 🙏🏻🙏🏻

**Comment by UnamedRus** [comment]
```
, prices_ordered AS MATERIALIZED (  -- <--- Only added MATERIALIZED clause here.
  SELECT * FROM prices
  ORDER BY datetime
)
```

AFAIK, you don't need to presort data before ASOF JOIN

I would rather write something like this in CH for this particular case.

```
WITH
    prices AS
    (
        SELECT
            datetime,
            symbol,
            price
        FROM big_price_table
        UNION ALL
        SELECT
            datetime,
            symbol,
            price
        FROM another_big_price_table
    ),
    prices_ordered AS
    (
        SELECT *
        FROM prices
    )
SELECT
    t.datetime,
    t.symbol,
    any(t.amount) AS amount,
    argMaxIf(p.price, p.datetime, p.datetime = t.datetime) AS p,
    argMaxIf(p.price, p.datetime, p.datetime < (t.datetime + toIntervalSecond(1))) AS p_1s,
    argMaxIf(p.price, p.datetime, p.datetime < (t.datetime + toIntervalSecond(5))) AS p_5s,
    argMaxIf(p.price, p.datetime, p.datetime < (t.datetime + toIntervalMinute(1))) AS p_1m,
    argMaxIf(p.price, p.datetime, p.datetime < (t.datetime + toIntervalMinute(10))) AS p_10m
FROM prices AS p
INNER JOIN small_trades_table AS t ON (t.symbol = p.symbol) AND (p.datetime >= t.datetime) AND (p.datetime <= (t.datetime + toIntervalMinute(10)))
WHERE (t.symbol IN (
    SELECT symbol
    FROM small_trades_table
)) AND ((t.datetime >= (
    SELECT min(datetime)
    FROM small_trades_table
)) AND (t.datetime <= (
    SELECT max(datetime) + toIntervalMinute(10)
    FROM small_trades_table
)))
GROUP BY
    t.datetime,
    t.symbol
```

**Comment by vibl** [comment]
@canhld94  In this official ClickHouse video https://www.youtube.com/watch?v=DZ5nPZpqVng , it's repeated multiple times that the CTE "saves the result" of the SELECT statement Can you ask the person in charge to unpublished it?

**Comment by canhld94** [comment]
> @canhld94 In this official ClickHouse video https://www.youtube.com/watch?v=DZ5nPZpqVng , it's repeated multiple times that the CTE "saves the result" of the SELECT statement Can you ask the person in charge to unpublished it?

@vibl I'm not working at ClickHouse so I cannot do anything, cc @alexey-milovidov may know who's in charge of it.

Btw, I have submitted a [PR](https://github.com/ClickHouse/ClickHouse/pull/61086) for materialized CTE few months ago, nevertheless recently I has been too busy with my work, so cannot take care of it. Will see if I have time to make it to upstream.

**Comment by jirislav** [comment]
Thank you for mentioning your PR @canhld94, this is a huge contribution to the community!

Also thanks for pointing out that the hash join is the bottleneck in my example. I assumed it's not the case as the Real time was mostly (>90%) spent waiting for something unknown. But it might be because of the the ASOF hash join implementation being single-threaded.

Closing this issue as duplicate of #53449. Thanks @UnamedRus for pointing this out.

I will think about opening another issue to support Join table engine for ASOF join.

**Comment by jirislav** [comment]
Regarding your suggestion @UnamedRus to use `argMaxIf`, I would like to avoid this (regardless of its performance) because it is not fluent SQL. The reason is to enable analysts focus on the data itself instead of thinking about non-native "hacky" ways to join two distinct timeseries together.

But thanks for the effort, if your example turns out faster, it might be used as internal optimization.

**Comment by UnamedRus** [comment]
>  because it is not fluent SQL.

Technically, argMax variants exist in many SQL dialects, in this case you can think about it as argMax + FILTER (WHERE ) which in SQL standard (CH is also support it, but it's longer than -if

```
   argMax(p.price, p.datetime) FILTER (WHERE  p.datetime = t.datetime) AS p,
```
