### ISSUE TITLE
TimeZone Coversion Faulty

### ISSUE THREAD

**Issue by luck143** [ClickHouse/ClickHouse#7202]
TimeZone Conversion is returning wrong time zone for many timezones.
Example : This works fine 

`SELECT    now() AS now_local,    toDateTime(now(), 'Asia/Yekaterinburg') AS new_time;

```
───────────now_local─┬────────────new_time─┐
│ 2019-10-05 15:58:15 │ 2019-10-05 20:58:15 │
```

But if i use other timezones like Pacific/Kiritimati , Pacific/Fakaofo gives completely wrong result

```
SELECT    now() AS now_local,    toDateTime(now(), 'Pacific/Kiritimati') AS new_time;
┌───────────now_local─┬────────────new_time─┐
│ 2019-10-05 15:59:58 │ 2019-10-04 53:59:58 │

`
```
the above query converted Hour to 53 lol

I am using click house version - 19.9.5

**Comment by luck143** [comment]
On further experiment i found the following timezone fails to provide expected result

`select toStartOfDay(createdtimestr , 'Africa/El_Aaiun' ) AS timestring,count() AS clicks from clicks final where like(lower(nid),lower('210'))!= 0 and ( createdtimestr between '2019-10-05 00:00:00' and '2019-10-08 23:59:59' ) group by timestring order by timestring asc`

```
Africa/El_Aaiun
Asia/Pyongyang
Pacific/Kwajalein
Pacific/Apia
Pacific/Enderbury
Pacific/Fakaofo
Pacific/Kiritimati
```

**Comment by qonst** [comment]
Temporary solution:
`addHours(now(), 14)`

**Comment by alexey-milovidov** [comment]
It happens for time zones that have offset changed between positive and negative.
