### ISSUE TITLE
DuckDB's struct.* for ClickHouse maps

### ISSUE THREAD

**Issue by mneedham** [ClickHouse/ClickHouse#72040]
I want something like DuckDB's [`struct.*`](https://duckdb.org/docs/sql/expressions/star.html#:~:text=STRUCT.,handle%20any%20potential%20struct%20keys.) where you can explode the values of a struct/map out into columns named after their keys:

```sql
D select {'name': 'Alexey', 'favDb': 'ClickHouse'} AS map;
┌───────────────────────────────────────┐
│                  map                  │
│ struct("name" varchar, favdb varchar) │
├───────────────────────────────────────┤
│ {'name': Alexey, 'favDb': ClickHouse} │
└───────────────────────────────────────┘
D select map.* FROM (SELECT {'name': 'Alexey', 'favDb': 'ClickHouse'} AS map);
┌─────────┬────────────┐
│  name   │   favDb    │
│ varchar │  varchar   │
├─────────┼────────────┤
│ Alexey  │ ClickHouse │
└─────────┴────────────┘
```

So kinda like `untuple` but for maps

**Comment by den-crane** [comment]
But what if the first row has `{'name': 'Alexey'}` and 100000000-th row has `{'favDb': 'ClickHouse'}`?

ClickHouse executes queries in a streaming manner, so you cannot know beforehand which columns can happen in a result.

**Comment by UnamedRus** [comment]
What if can be feature of clickhouse-client for *monoblock format, to show maps/structs in special way.
Like BigQuery does

![image](https://github.com/user-attachments/assets/2d53d05f-7e85-4c42-9851-a5774a168d21)
