### ISSUE TITLE
arrayCompact function - remove consecutive identical elements.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7204]
**Use case**
`arrayCompact(['a', 'a', 'b', 'b', 'a']) = ['a', 'b', 'a']`

https://github.com/ClickHouse/ClickHouse/issues/7147

**Comment by dsmith47** [comment]
I would be interested in working on this. Test/structure wise, would it be fair to say that `arrayConcat` is a good model for adding functions?

**Comment by alexey-milovidov** [comment]
You can also look at `FunctionArrayMapped.h` and `arrayFilter.cpp`.
You can make this function as a higher order function similar to `arrayMap` and `arrayFiler`.

**Comment by divc99** [comment]
Can I work on this?

**Comment by alexey-milovidov** [comment]
@divc99 Sure. It will be very appreciated!

**Comment by jatin33** [comment]
Hi @alexey-milovidov,

Can I work on this?
Please assign it to me if possible.
Thanks in advance.

**Comment by alexey-milovidov** [comment]
@jatin33 Yes, you can work on this task.

**Comment by alexey-milovidov** [comment]
I can merge a pull request from @dsmith47, @divc99, @jatin33 - whoever will do it first or do it better.

**Comment by alexey-milovidov** [comment]
Note that GitHub does not allow to assign issues to people outside of the teams.
