### ISSUE TITLE
INSERT INTO by SELECT does not show all row inserted into by native clickhouse client

### ISSUE THREAD

**Issue by gonchik** [ClickHouse/ClickHouse#72072]
###  A bit confused by response from clickhouse client

0 rows in set. is confused me, but data input into destination table

```Ok.

0 rows in set. Elapsed: 38.856 sec. Processed 41.30 billion rows, 496.65 GB (1.06 billion rows/s., 12.78 GB/s.)
Peak memory usage: 326.58 MiB.
```

### code query
```sql

INSERT INTO test.gonchik_temp (uuid, login)
SELECT DISTINCT id  as uuid,
                login as login
FROM test.logs
WHERE  login <> 0;
```

### Expected behaviour

Don't show that if data inserted, or provide counter like this
`3218572 rows in set`

ClickHouse client version 24.11.1.695 (official build)

**Comment by den-crane** [comment]
`0 rows in set.` === a query returned 0 rows to a client.

**Comment by gonchik** [comment]
@den-crane  noted, thank you! :) 

Also, that duplicates that request
https://github.com/ClickHouse/ClickHouse/issues/9017
