### ISSUE TITLE
I set some server configurations, but they do not work

### ISSUE THREAD

**Issue by honobi** [ClickHouse/ClickHouse#72119]
### Question

clickhouse-server version:  24.3.12.75
<img width="1098" alt="截屏2024-11-20 11 10 33" src="https://github.com/user-attachments/assets/667d51a9-60c2-41eb-9634-0734020aed6c">

restart clickhouse-server
<img width="660" alt="截屏2024-11-20 11 11 15" src="https://github.com/user-attachments/assets/50db52c8-1cb4-46ce-8b1c-053534df267b">

**Comment by cangyin** [comment]
Is that queried from `server_settings` ?
```sql
SELECT * FROM system.server_settings
```

**Comment by honobi** [comment]
> Is that queried from `server_settings` ?
> 
> ```sql
> SELECT * FROM system.server_settings
> ```

yes
<img width="684" alt="截屏2024-11-20 11 30 36" src="https://github.com/user-attachments/assets/23f972df-2f69-40da-8b36-1ed6fbc0c9c1">

**Comment by cangyin** [comment]
Nop, please use `system.server_settings` instead of `system.settings`.

**Comment by honobi** [comment]
> Nop, please use `system.server_settings` instead of `system.settings`.
> 
> Settings like `background_*_pool_size` are moved from `settings` to `server_settings`, but left compatible in `settings`.
> 
> There are 3 types of settings, check the docs of each at:
> 
> 1. [settings](https://clickhouse.com/docs/en/operations/system-tables/settings)
> 2. [merge_tree_settings](https://clickhouse.com/docs/en/operations/system-tables/merge_tree_settings)
> 3. [server_settings](https://clickhouse.com/docs/en/operations/system-tables/server_settings)

thanks
