### ISSUE TITLE
How to reload the storage_configuration  in 23.8 version？

### ISSUE THREAD

**Issue by zxl-wangwang** [ClickHouse/ClickHouse#72138]
### Question

Env :

I created a new policy in the 23.8 version directory /etc/clickhouse-server/config.d as follows: 

![截屏2024-11-19 16 29 36](https://github.com/user-attachments/assets/b58fd9d7-bfe8-4b83-8951-87beb3b48ceb)

The log also shows that zxlpolicy1 is loaded.

![截屏2024-11-19 16 30 05](https://github.com/user-attachments/assets/14f5f5bf-4711-4ef3-9faa-6910d8b39c28)

You can also check the system table storage_policies.

![截屏2024-11-19 16 32 22](https://github.com/user-attachments/assets/c4ad5081-fcf0-4a25-afad-d5cd8cc7d114)

Question:

Based on the above, I delete zxlpolicy1 and create a new zxlpolicy2. The service log shows that zxlpolicy2 is loaded, but there is no zxlpolicy2 in system.storage_policies.
![image](https://github.com/user-attachments/assets/eb0dea4f-b1bd-4525-b07b-006076d4962b)

clickhouse-server log: 

![image](https://github.com/user-attachments/assets/b99f613c-aec9-46f0-8581-8bb274b16eda)

system.storage_policies：

![截屏2024-11-19 16 37 17](https://github.com/user-attachments/assets/c1a2aaae-8225-4f11-9559-ad03ee9e492e)

I have to restart the cluster system table to load zxlpolicy2.

How can I get the system tables to load into zxlpolicy2 without restarting the cluster?

**Comment by nikitamikhaylov** [comment]
This version is not supported anymore. The list of supported versions is here: https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md
