### ISSUE TITLE
Aliases not respected in JOIN

### ISSUE THREAD

**Issue by deangelo-llooker** [ClickHouse/ClickHouse#7214]
If a table is aliased, the table can still be referred to via its table name. This can cause particular issues in a self join.

```sql
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
   id Int32,
   name Nullable(String),
   age Nullable(Int32),
   created_at Nullable(DateTime),
   epoch_at Nullable(Int32),
   yyyymmdd_at Nullable(Int32)
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY (id)
;

INSERT INTO users (id,name,age,created_at,epoch_at,yyyymmdd_at) VALUES (1,'Warnk Pelger',49,'2010-10-07 17:07:54',1286471274,20101007);
INSERT INTO users (id,name,age,created_at,epoch_at,yyyymmdd_at) VALUES (2,'Kraemer Franc',87,'2010-10-11 09:12:16',1286788336,20101011);
INSERT INTO users (id,name,age,created_at,epoch_at,yyyymmdd_at) VALUES (3,'Nikolai Lingenfelter',69,'2011-01-01 00:46:58',1293842818,20110101);
INSERT INTO users (id,name,age,created_at,epoch_at,yyyymmdd_at) VALUES (4,'Reinoehl Augustinus',94,'2011-12-05 19:46:50',1323114410,20111205);
INSERT INTO users (id,name,age,created_at,epoch_at,yyyymmdd_at) VALUES (5,'Majcei Cullop',23,'2011-03-20 19:12:04',1300648324,20110320);
INSERT INTO users (id,name,age,created_at,epoch_at,yyyymmdd_at) VALUES (7,'Doela Warenius',57,'2010-10-26 02:49:35',1288061375,20101026);
```

```sql
SELECT users.id
FROM users AS A 
INNER JOIN 
users 
ON A.id = users.id
```

`Error: ClickHouse exception, code: 403, host: hostname, port: 8123; Code: 403, e.displayText() = DB::Exception: Invalid expression for JOIN ON. In expression id = id columns id and id are from the same table but from different arguments of equal function. Supported syntax: JOIN ON Expr([table.]column, ...) = Expr([table.]column, ...) [AND Expr([table.]column, ...) = Expr([table.]column, ...) ...] (version 19.15.2.2 (official build))`

In this case the alias `A` should take precedence over the table name. Any references with `A` should refer to the first table and any references with `users` should refer to the second table.

Admittedly the sample sql is a silly case. But this self join pattern is sometimes used to compare individual rows to aggregates from the same table.

**Comment by 4ertus2** [comment]
Reproduced

```
USE system;

SELECT dummy
FROM one AS A
INNER JOIN
one
ON A.dummy = one.dummy; -- error

SELECT dummy
FROM one
INNER JOIN
one AS A
ON A.dummy = one.dummy; -- OK
```

**Comment by 4ertus2** [comment]
Related #4567 
We need to detect ambiguous columns. It's possible to check table aliases at this phase.

**Comment by 4ertus2** [comment]
#7358
