### ISSUE TITLE
24.10 Maximum amount of backtracking (1000) exceeded in the parser. Consider rising max_parser_backtracks parameter

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#72160]
After upgrading from 24.9 to 24.10 I tried to add a column into a wide table (700 columns).

I got an exception:
Code: 718. DB::Exception: Maximum amount of backtracking (1000) exceeded in the parser. Consider rising max_parser_backtracks parameter. (TOO_SLOW_PARSING) (version 24.10.2.80 (official build))

The max_parser_backtracks parameter's default value is 1000000 and I haven't changed it.
There is the max_parser_depth parameter which default value is 1000, and increasing it helps with the adding a new column to the table.

Two unexpected things:
1. The name and the value of the parameter in the exception message do not match.
2. What changed in 24.10 that I cannot add a column anymore?

**Comment by SaltTan** [comment]
maybe #68574 is responsible?

**Comment by SaltTan** [comment]
No exception in 24.9 https://fiddle.clickhouse.com/ac36858a-c95f-400c-97e9-f2b7ed1b3843
Fails in 24.10 https://fiddle.clickhouse.com/17e3ba14-5b06-4b2a-8e1d-a21f8b3fd93c
Seems to be fixed in master https://fiddle.clickhouse.com/f7e5c64a-9a56-498d-9d0b-75ef608682cb
@antaljanosbenjamin FYI

**Comment by Algunenano** [comment]
https://github.com/ClickHouse/ClickHouse/pull/71498 I'll backport it to 24.10
