### ISSUE TITLE
Readonly Log Queries

### ISSUE THREAD

**Issue by isaachui** [ClickHouse/ClickHouse#7217]
Hello!

I'm trying to implement users and profiles in clickhouse. I would like the default user to be read only, but also be able to log queries. These settings below do not seem to do that, since it needs write access to write the logs. Is there a different setting to change to allow logging of `readonly` queries?

```
<yandex>
  <profiles>
    <default>
      <log_queries>1</log_queries>
      <readonly>1</readonly>
      <allow_ddl>0</allow_ddl>
    </default>
  </profiles>
</yandex>
```

**Comment by filimonov** [comment]
You overwrite default profile which also is used by several system tasks (including writing to query_log).

Please try to create one more profile, like `system`, which will be not readonly and put the name of that profile in config, here:
https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/server/config.xml#L126

**Comment by isaachui** [comment]
Thanks! That seemed to have worked!
