### ISSUE TITLE
An error was encountered while starting the service: <Error> Application: Code: 139

### ISSUE THREAD

**Issue by quanbeisheng** [ClickHouse/ClickHouse#72194]
### Company or project name

Personal database enthusiast

### Question

您好，我用clickhouse-xxxxx-24.8.7.41-amd64.tgz二进制方式部署在三台主机，每台主机运行两个应用实例，第一个实例服务集成keeper服务并随server启动，第二个只单纯作为server启动，并采用3分片2副本模式，config1.xml配置文件里存在<keeper_server>标签正常启动，config2.xml配置文件里无<keeper_server>标签，使用config2.xml启动后日志见（3.第一台主机实例2日志如下），请问如何解决？ 同时，描述的这个情况在clickhouse-24.3.3.102版本中运行正常，同样是3台主机每台各运行2个clickhouse应用实例（3shard\2replica），Thanks!

1.第一台主机实例1配置如下：
```
     <keeper_server>
        <tcp_port>9182</tcp_port>
        <!-- Must be unique among all keeper serves -->
        <server_id>1</server_id>
        <log_storage_path>/data/clickhouse-24.8.7.41/clickhouse-keeper/log</log_storage_path>
        <snapshot_storage_path>/data/clickhouse-24.8.7.41/clickhouse-keeper/snapshots</snapshot_storage_path>

        <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <min_session_timeout_ms>10000</min_session_timeout_ms>
                <session_timeout_ms>100000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
                <compress_logs>false</compress_logs>
                <!-- All settings listed in https://github.com/ClickHouse/ClickHouse/blob/master/src/Coordination/CoordinationSettings.h -->
         </coordination_settings>
     
         <!-- enable sanity hostname checks for cluster configuration (e.g. if localhost is used with remote endpoints) -->
         <hostname_checks_enabled>true</hostname_checks_enabled>
         <raft_configuration>
             <server>
                 <id>1</id>
                 <!-- Internal port and hostname -->
                 <hostname>xx.xx.xx.1</hostname>
                 <port>9235</port>
             </server>
             <server>
                 <id>2</id>
                 <!-- Internal port and hostname -->
                 <hostname>xx.xx.xx.2</hostname>
                 <port>9235</port>
             </server>
             <server>
                 <id>3</id> 
                 <!-- Internal port and hostname -->
                 <hostname>xx.xx.xx.3</hostname>
                 <port>9235</port>
             </server> 
          </raft_configuration>
    </keeper_server>
    <zookeeper>
        <node>
            <host>xx.xx.xx.1</host>
            <port>9182</port>
        </node>
        <node>
            <host>xx.xx.xx.2</host>
            <port>9182</port>
        </node>
        <node>
            <host>xx.xx.xx.3</host>
            <port>9182</port>
        </node>
    </zookeeper>
```

2.第一台主机实例2配置如下：
 ```
<zookeeper>
        <node>
            <host>xx.xx.xx.1</host>
            <port>9182</port>
        </node>
        <node>
            <host>xx.xx.xx.2</host>
            <port>9182</port>
        </node>
        <node>
            <host>xx.xx.xx.3</host>
            <port>9182</port>
        </node>
    </zookeeper>
```

3.第一台主机实例2日志如下：
2024.11.19 17:08:16.401669 [ 3792272 ] {} <Warning> Application: bool tryCreateDirectories(Poco::Logger *, const std::string &): when creating /opt/cores/, std::exception. Code: 1001, type
: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied ["/opt/cores"], Stack trace (when copying this message, always include
 the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x00000000110c14d5
1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:v15007](String const&, std::__fs::filesystem::path const&, std::error_code) @ 0x000000000a9915a1
2. void std::__fs::filesystem::__throw_filesystem_error[abi:v15007]<String&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::e
rror_code const&) @ 0x0000000011086d9a
3. std::__fs::filesystem::detail::(anonymous namespace)::ErrorHandler<bool>::report(std::error_code const&) const (.llvm.6656863861799227920) @ 0x000000001108a3c0
4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001108abd6
5. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x000000001108ac75
6. tryCreateDirectories(Poco::Logger*, String const&) @ 0x000000000aa6f0fb
7. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000aa6cfe9
8. DB::Keeper::initialize(Poco::Util::Application&) @ 0x00000000054fabcd
9. Poco::Util::Application::run() @ 0x0000000010466c5a
10. DB::Keeper::run() @ 0x00000000054fa990
11. Poco::Util::ServerApplication::run(int, char**) @ 0x000000001046ef67
12. mainEntryClickHouseKeeper(int, char**) @ 0x00000000054f95f2
13. main @ 0x00000000054f8550
14. ? @ 0x0000000000025b27
15. _start @ 0x0000000004d6f02e

Cannot print extra info for Poco::Exception (version 24.8.7.41 (official build))
2024.11.19 17:08:16.401792 [ 3792272 ] {} <Information> SentryWriter: Sending crash reports is disabled
2024.11.19 17:08:16.401977 [ 3792272 ] {} <Information> Application: Starting ClickHouse Keeper 24.8.7.41 (revision: 54495, git hash: e28553d4f2ba78643f9ef47b698954a2c54e6bcc, build id: 7F
E420C7EAFBC87760F20259783EE443A6C10BBF), PID 3792272
2024.11.19 17:08:16.402100 [ 3792272 ] {} <Information> Application: starting up
2024.11.19 17:08:16.402117 [ 3792272 ] {} <Information> Application: OS Name = Linux, OS Version = 4.19.90-2107.6.0.0192.8.oe1.bclinux.x86_64, OS Architecture = x86_64
2024.11.19 17:08:16.402364 [ 3792272 ] {} <Information> Jemalloc: Value for background_thread set to true (from false)
2024.11.19 17:08:16.404179 [ 3792272 ] {} <Error> Application: Code: 139. DB::Exception: Keeper configuration (<keeper_server> section) not found in config. (NO_ELEMENTS_IN_CONFIG), Stack 
trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000a92129b
1. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x0000000005507b6c
2. DB::Exception::Exception<>(int, FormatStringHelperImpl<>) @ 0x0000000005500bab
3. DB::Keeper::main(std::vector<String, std::allocator<String>> const&) @ 0x00000000054ff34c
4. Poco::Util::Application::run() @ 0x0000000010466c66
5. DB::Keeper::run() @ 0x00000000054fa990
6. Poco::Util::ServerApplication::run(int, char**) @ 0x000000001046ef67
7. mainEntryClickHouseKeeper(int, char**) @ 0x00000000054f95f2
8. main @ 0x00000000054f8550
9. ? @ 0x0000000000025b27
10. _start @ 0x0000000004d6f02e
 (version 24.8.7.41 (official build))
2024.11.19 17:08:16.404206 [ 3792272 ] {} <Information> Application: shutting down
2024.11.19 17:08:16.404213 [ 3792272 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2024.11.19 17:08:16.404419 [ 3792273 ] {} <Information> BaseDaemon: Stop SignalListener thread

**Comment by davenger** [comment]
Does your config.xml have top-level xml element like <clickhouse>?
It should look like this:

```
<clickhouse>

     <keeper_server>
        <tcp_port>9182</tcp_port>
        <!-- Must be unique among all keeper serves -->
        <server_id>1</server_id>
        <log_storage_path>/data/clickhouse-24.8.7.41/clickhouse-keeper/log</log_storage_path>
        <snapshot_storage_path>/data/clickhouse-24.8.7.41/clickhouse-keeper/snapshots</snapshot_storage_path>

        <coordination_settings>
                <operation_timeout_ms>10000</operation_timeout_ms>
                <min_session_timeout_ms>10000</min_session_timeout_ms>
                <session_timeout_ms>100000</session_timeout_ms>
                <raft_logs_level>information</raft_logs_level>
                <compress_logs>false</compress_logs>
                <!-- All settings listed in https://github.com/ClickHouse/ClickHouse/blob/master/src/Coordination/CoordinationSettings.h -->
         </coordination_settings>
     
         <!-- enable sanity hostname checks for cluster configuration (e.g. if localhost is used with remote endpoints) -->
         <hostname_checks_enabled>true</hostname_checks_enabled>
         <raft_configuration>
             <server>
                 <id>1</id>
                 <!-- Internal port and hostname -->
                 <hostname>xx.xx.xx.1</hostname>
                 <port>9235</port>
             </server>
             <server>
                 <id>2</id>
                 <!-- Internal port and hostname -->
                 <hostname>xx.xx.xx.2</hostname>
                 <port>9235</port>
             </server>
             <server>
                 <id>3</id> 
                 <!-- Internal port and hostname -->
                 <hostname>xx.xx.xx.3</hostname>
                 <port>9235</port>
             </server> 
          </raft_configuration>
    </keeper_server>
    <zookeeper>
        <node>
            <host>xx.xx.xx.1</host>
            <port>9182</port>
        </node>
        <node>
            <host>xx.xx.xx.2</host>
            <port>9182</port>
        </node>
        <node>
            <host>xx.xx.xx.3</host>
            <port>9182</port>
        </node>
    </zookeeper>
    
</clickhouse>
```

**Comment by quanbeisheng** [comment]
> 你的 config.xml 是否具有顶级 xml 元素，例如 ？它应该看起来像这样：
> 
> ```
> <clickhouse>
> 
>      <keeper_server>
>         <tcp_port>9182</tcp_port>
>         
>         <server_id>1</server_id>
>         <log_storage_path>/data/clickhouse-24.8.7.41/clickhouse-keeper/log</log_storage_path>
>         <snapshot_storage_path>/data/clickhouse-24.8.7.41/clickhouse-keeper/snapshots</snapshot_storage_path>
> 
>         <coordination_settings>
>                 <operation_timeout_ms>10000</operation_timeout_ms>
>                 <min_session_timeout_ms>10000</min_session_timeout_ms>
>                 <session_timeout_ms>100000</session_timeout_ms>
>                 <raft_logs_level>information</raft_logs_level>
>                 <compress_logs>false</compress_logs>
>                 
>          </coordination_settings>
>      
>          
>          <hostname_checks_enabled>true</hostname_checks_enabled>
>          <raft_configuration>
>              <server>
>                  <id>1</id>
>                  
>                  <hostname>xx.xx.xx.1</hostname>
>                  <port>9235</port>
>              </server>
>              <server>
>                  <id>2</id>
>                  
>                  <hostname>xx.xx.xx.2</hostname>
>                  <port>9235</port>
>              </server>
>              <server>
>                  <id>3</id> 
>                  
>                  <hostname>xx.xx.xx.3</hostname>
>                  <port>9235</port>
>              </server> 
>           </raft_configuration>
>     </keeper_server>
>     <zookeeper>
>         <node>
>             <host>xx.xx.xx.1</host>
>             <port>9182</port>
>         </node>
>         <node>
>             <host>xx.xx.xx.2</host>
>             <port>9182</port>
>         </node>
>         <node>
>             <host>xx.xx.xx.3</host>
>             <port>9182</port>
>         </node>
>     </zookeeper>
>     
> </clickhouse>
> ```

Yes, as you said, the configuration is declared in the top-level element<clickhouse>, with the goal of starting two clickhouse instance services on the same host. This is because the planned cluster will run on three hosts and six instance services, which is a 3-shard and 2-replica mode. I believe that the first service of each host should carry the<keeper.server>element and the<zookeeper>element, and the second service should only carry the<zookeeper>element. The planned embedded keeper service will only run on three instances. That's it. Do you mean that all 6 instances must carry the<Keeper_Server>element and<Zookeeper>element?
