### ISSUE TITLE
how to use multiple storage 

### ISSUE THREAD

**Issue by pyscala** [ClickHouse/ClickHouse#7219]
i find 
"support to use multiple storage volumes for tables with MergeTree engine. It's possible to store fresh data on SSD and automatically move old data to HDD" in https://clickhouse.yandex/docs/en/changelog/ ,but cannot find more information about it ?how to use ? thinks

**Comment by ifoo** [comment]
There is documentation on the russian version of the MergeTree page here: https://clickhouse.yandex/docs/ru/operations/table_engines/mergetree/#table_engine-mergetree-multiple-volumes_configure . Unfortunately, it's not in the english version yet. There are also some examples in a recent presentation here: https://htmlpreview.github.io/?https://github.com/ClickHouse/clickhouse-presentations/blob/master/meetup30/new_features/index.html .

**Comment by alexey-milovidov** [comment]
This is the better link: https://clickhouse.github.io/clickhouse-presentations/meetup30/new_features/#12

**Comment by pyscala** [comment]
> There is documentation on the russian version of the MergeTree page here: https://clickhouse.yandex/docs/ru/operations/table_engines/mergetree/#table_engine-mergetree-multiple-volumes_configure . Unfortunately, it's not in the english version yet. There are also some examples in a recent presentation here: https://htmlpreview.github.io/?https://github.com/ClickHouse/clickhouse-presentations/blob/master/meetup30/new_features/index.html .

i found it yestorday,thanks
