### ISSUE TITLE
Does a JOIN in ClickHouse preserve the order from an ORDER BY in a subquery?

### ISSUE THREAD

**Issue by AmalDarKhalil** [ClickHouse/ClickHouse#72201]
### Question

When I use an ORDER BY in a left table subquery and then perform a JOIN in ClickHouse, does the final result maintain the order of the rows as specified in the subquery, or does the JOIN operation affect the order?

**Comment by Algunenano** [comment]
Operations over a subquery are never guaranteed to keep the order. The only guarantees are ORDER BY on the final result.

It's entirely possible that order might be kept now in some cases and it might be broken in the future when improvements are included.
