### ISSUE TITLE
Very strange behavior: 3 tables with same data, different select speed

### ISSUE THREAD

**Issue by MahmoudGoda0** [ClickHouse/ClickHouse#7223]
Hi Team, I have a strange behavior, I created 2 tables from one month ago, and the 2 tables are identical (same creation statement and filled by the same insert statement), after the creation, when i run a query it takes 11 second on both tables, but now (after one month) its take 23 second on both tables, i didn't do any change in both tables !! Then, today i created the third table with the same data & same columns as well, the same query take 11 second on the third table !!!, Anyone have any idea why i have this strange behavior ?
CH version 19.14.3.3

**Comment by blinkov** [comment]
It probably has something to do with background process merging table into less files. Could you show either CREATE TABLE and SELECT queries?

**Comment by MahmoudGoda0** [comment]
It seems you are right, i just realized the below results
SELECT count(partition)
FROM system.parts
WHERE table = 'table1'
results = 75
-----------------------------------------------
SELECT count(partition)
FROM system.parts
WHERE table = 'table2'
results = 74
-------------------------------------------------
SELECT count(partition)
FROM system.parts
WHERE table = 'table3'
results = 255
--------------------------------------------------------------------------------------------------
CREATE TABLE (for the 3 tables):
CREATE TABLE table1 (`ext_rec_num` Nullable(UInt64), `xdr_id` Nullable(UInt64), `xdr_grp` Nullable(UInt64), `xdr_type` Nullable(UInt64), `xdr_subtype` Nullable(Int16), `xdr_direction` Nullable(Int16), `xdr_location` Nullable(Int16), `start_time` UInt64, `stop_time` UInt64, `transaction_duration` Nullable(UInt64), `response_time` Nullable(UInt64), `protocol` Nullable(Int16), `chunk_count` Nullable(Int16), `dpc` Nullable(Int32), `opc` Nullable(Int32), `first_link_id` String, `last_dpc` Nullable(Int32), `last_opc` Nullable(Int32), `last_link_id` String, `first_back_opc` Nullable(Int32), `first_back_link_id` String, `calling_ssn` Nullable(Int16), `called_ssn` Nullable(Int16), `called_sccp_address` String, `calling_party_address` String, `response_calling_address` String, `root_end_code` Nullable(Int32), `root_cause_code` Nullable(Int32), `root_cause_pl` Nullable(Int16), `root_failure` Int16, `root_equip` Nullable(Int16), `map_end_code` Nullable(Int32), `map_cause_code` Nullable(Int32), `map_cause_pl` Nullable(Int16), `sip_end_code` Nullable(Int32), `sip_cause_code` Nullable(Int32), `sip_cause_pl` Nullable(Int16), `isup_end_code` Nullable(Int32), `isup_cause_code` Nullable(Int32), `isup_cause_pl` Nullable(Int16), `inap_end_code` Nullable(Int32), `inap_cause_code` Nullable(Int32), `inap_cause_pl` Nullable(Int16), `subs_id` Nullable(UInt64), `mccmnc` Nullable(Int32), `imsi` String, `msisdn` String, `tac` Nullable(Int32), `imei` String, `msc_number` String, `vlr_number` String, `hlr_number` String, `service_key_1` Nullable(Int32), `camel_phases` Nullable(Int16), `camel_cpbt_handling` Nullable(Int16), `gsm_scf_address` String, `location_number` String, `old_lac` Nullable(Int32), `mcc` Nullable(Int32), `mnc` Nullable(Int32), `lac` Nullable(UInt64), `cell_id` Nullable(UInt64), `sms_length` Nullable(Int32), `service_center_address` String, `calling_number` String, `dialled_number` String, `connect_timestamp` Nullable(UInt64), `setup_time` Nullable(UInt64), `conversation_time` Nullable(UInt64), `cic` Nullable(Int32), `call_connected` Nullable(Int16), `release` Nullable(Int32), `forwarded` Nullable(Int16), `a_nature` Nullable(Int16), `a_num_plan` Nullable(Int16), `b_nature` Nullable(Int16), `b_num_plan` Nullable(Int16), `c_number` String, `c_nature` Nullable(Int16), `c_type` Nullable(Int16), `d_number` String, `d_type` Nullable(Int16), `e_number` String, `e_type` Nullable(Int16), `teleservice` Nullable(Int16), `leg1_1_event` Nullable(Int16), `leg1_2_event` Nullable(Int16), `leg1_3_event` Nullable(Int16), `leg2_1_event` Nullable(Int16), `leg2_2_event` Nullable(Int16), `leg2_3_event` Nullable(Int16), `leg3_1_event` Nullable(Int16), `leg3_2_event` Nullable(Int16), `leg3_3_event` Nullable(Int16), `sgsn_number` String, `sgsn_address` String, `apn_1` String, `apn_2` String, `apn_3` String, `apn_4` String, `apn_5` String, `call_id` String, `calling_ip_address` String, `calling_port` Nullable(Int32), `calling_id_user` String, `calling_id_host` String, `calling_id_name` String, `calling_realm` String, `calling_user_agent` String, `original_called_id_user` String, `original_called_id_host` String, `original_called_id_name` String, `called_id_user` String, `called_id_host` String, `called_id_name` String, `request_uri` String, `from_uri` String, `to_uri` String, `media_format` String) ENGINE = MergeTree() PARTITION BY toUInt32(intDiv(start_time, 3600000) * 3600) ORDER BY (start_time, imsi) SETTINGS index_granularity = 8192
-----------------------------------------------------------------------------------------------------------
SELECT QUERY (for the 3 tables):
select count(*) from table where start_time > (971128806382 + (3*86400000)) and start_time <(971222387788 + (3*86400000)) and (imsi = '938036742605759' or imsi = '938036641466635' or called_sccp_address = '33634331783' or called_sccp_address = '33634333103' or calling_number = '189380333' or calling_number = '171375347'

**Comment by MahmoudGoda0** [comment]
Hi @blinkov 
Do you have any idea why i have diff part numbers for the 3 tables ?

**Comment by MahmoudGoda0** [comment]
Kindly find below the results: Note that before running the 2 queries i run the below query to force the merge process in the third table
optimize table3 final
Now i have 105 part active for table 3 and 75 

First Table:
<Debug> executeQuery: (from [::1]:47416) SELECT count(*) FROM ts1day WHERE (start_time > (971128806382 + (1 * 86400000))) AND (start_time < (971222387788 + (1 * 86400000))) AND ((imsi = '938036742605759') OR (imsi = '938036641466635') OR (called_sccp_address = '33634331783') OR (called_sccp_address = '33634333103') OR (calling_number = '189380333') OR (calling_number = '171375347'))
← Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) [gojira] 2019.10.08 16:33:06.170855 {8653afd9-40dd-4f35-a022-f8584d065a68} [ 93 ] <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(imsi = '938036742605759') OR (imsi = '938036641466635') OR (called_sccp_address = '33634331783') OR (called_sccp_address = '33634333103') OR (calling_number = '189380333') OR (calling_number = '171375347')" moved to PREWHERE
[gojira] 2019.10.08 16:33:06.172218 {8653afd9-40dd-4f35-a022-f8584d065a68} [ 93 ] <Debug> default.ts1day (SelectExecutor): Key condition: (column 0 in [971215206383, +inf)), (column 0 in (-inf, 971308787787]), and, (column 1 in ['938036742605759', '938036742605759']), (column 1 in ['938036641466635', '938036641466635']), or, unknown, or, unknown, or, unknown, or, unknown, or, and
[gojira] 2019.10.08 16:33:06.172237 {8653afd9-40dd-4f35-a022-f8584d065a68} [ 93 ] <Debug> default.ts1day (SelectExecutor): MinMax index condition: (column 0 in [971215206383, +inf)), (column 0 in (-inf, 971308787787]), and, unknown, unknown, or, unknown, or, unknown, or, unknown, or, unknown, or, and
[gojira] 2019.10.08 16:33:06.531595 {8653afd9-40dd-4f35-a022-f8584d065a68} [ 93 ] <Debug> default.ts1day (SelectExecutor): Selected 75 parts by date, 75 parts by key, 382104 marks to read from 75 ranges
[gojira] 2019.10.08 16:33:06.536625 {8653afd9-40dd-4f35-a022-f8584d065a68} [ 93 ] <Debug> executeQuery: Query pipeline:
Expression
 Expression
  ParallelAggregating
   Expression × 16
    Filter
     MergeTreeThread

┌──count()─┐
│ 62415268 │
└──────────┘
[gojira] 2019.10.08 16:33:24.737384 {8653afd9-40dd-4f35-a022-f8584d065a68} [ 93 ] <Information> executeQuery: Read 3120727169 rows, 141.40 GiB in 18.567 sec., 168076287 rows/sec., 7.62 GiB/sec.
[gojira] 2019.10.08 16:33:24.737424 {8653afd9-40dd-4f35-a022-f8584d065a68} [ 93 ] <Debug> MemoryTracker: Peak memory usage (for query): 151.29 MiB.

1 rows in set. Elapsed: 18.569 sec. Processed 3.12 billion rows, 151.83 GB (168.07 million rows/s., 8.18 GB/s.) 
------------------------------------------------------------------------------------------------------

Third Table:
<Debug> executeQuery: (from [::1]:47416) SELECT count(*) FROM ts3day WHERE (start_time > (971128806382 + (3 * 86400000))) AND (start_time < (971222387788 + (3 * 86400000))) AND ((imsi = '938036742605759') OR (imsi = '938036641466635') OR (called_sccp_address = '33634331783') OR (called_sccp_address = '33634333103') OR (calling_number = '189380333') OR (calling_number = '171375347'))
→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) [gojira] 2019.10.08 16:27:53.112519 {366974c0-0eb5-4c9e-96ca-7821a133cde5} [ 93 ] <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(imsi = '938036742605759') OR (imsi = '938036641466635') OR (called_sccp_address = '33634331783') OR (called_sccp_address = '33634333103') OR (calling_number = '189380333') OR (calling_number = '171375347')" moved to PREWHERE
[gojira] 2019.10.08 16:27:53.113926 {366974c0-0eb5-4c9e-96ca-7821a133cde5} [ 93 ] <Debug> default.ts3day (SelectExecutor): Key condition: (column 0 in [971388006383, +inf)), (column 0 in (-inf, 971481587787]), and, (column 1 in ['938036742605759', '938036742605759']), (column 1 in ['938036641466635', '938036641466635']), or, unknown, or, unknown, or, unknown, or, unknown, or, and
[gojira] 2019.10.08 16:27:53.113951 {366974c0-0eb5-4c9e-96ca-7821a133cde5} [ 93 ] <Debug> default.ts3day (SelectExecutor): MinMax index condition: (column 0 in [971388006383, +inf)), (column 0 in (-inf, 971481587787]), and, unknown, unknown, or, unknown, or, unknown, or, unknown, or, unknown, or, and
[gojira] 2019.10.08 16:27:53.503043 {366974c0-0eb5-4c9e-96ca-7821a133cde5} [ 93 ] <Debug> default.ts3day (SelectExecutor): Selected 114 parts by date, 114 parts by key, 382353 marks to read from 114 ranges
[gojira] 2019.10.08 16:27:53.510634 {366974c0-0eb5-4c9e-96ca-7821a133cde5} [ 93 ] <Debug> executeQuery: Query pipeline:
Expression
┌──count()─┐
│ 62415268 │gregating
└──────────┘n × 16
[gojira] 2019.10.08 16:28:10.615105 {366974c0-0eb5-4c9e-96ca-7821a133cde5} [ 93 ] <Information> executeQuery: Read 3120727169 rows, 141.40 GiB in 17.503 sec., 178292739 rows/sec., 8.08 GiB/sec.
[gojira] 2019.10.08 16:28:10.615138 {366974c0-0eb5-4c9e-96ca-7821a133cde5} [ 93 ] <Debug> MemoryTracker: Peak memory usage (for query): 149.92 MiB.

1 rows in set. Elapsed: 17.505 sec. Processed 3.12 billion rows, 151.83 GB (178.27 million rows/s., 8.67 GB/s.)

**Comment by filimonov** [comment]
> when i run a query it takes 11 second on both tables, but now (after one month) its take 23 second on both tables, i didn't do any change in both tables !!

Are you sure it's not a page cache issue? Is that result stable when you repeat the queries multiple times? Maybe merged parts are too big for the page cache?

Can you repeat your experiment with forced DIRECT_IO? In that case clickhouse will bypass OS page cache for selects. To do that apply the following settings before running the queries:  
```SET min_bytes_to_use_direct_io=1, merge_tree_uniform_read_distribution=0```

> Kindly find below the results: Note that before running the 2 queries i run the below query to force the merge process in the third table

But those result have almost equivalent execution time (18.567 sec vs 17.505 sec), and practically the same execution pipeline. So not too helpful. 

> CREATE TABLE (for the 3 tables):

Consider following changes:
1) time with milliseconds is already too granular field (i.e. it have to high cardinality), it has no sense to add more fields after that in ORDER BY key. When you add some extra field in your ORDER BY key AFTER column with very high cardinality - it actually make the things worse (i.e. index is bigger, and it tries to
analyse that all the time, but it definitely will and up with a full scan anyway, so just waste of memory for huger index and waste of time for analysing that). Possible options:
  a) remove `imsi` at all from ORDER BY (it gives nothing right now)
  b) OR decrease the cardinality of column which is on the first position of ORDER BY key (it's a timestamp, so you can just use seconds or even minutes instead of milliseconds on a first position of key).
  c) OR reverse order of columns in ORDER BY key - i.e. `(imsi, start_time)` instead of `(start_time, imsi)`. If `imsi` is also too cardinal you can consider using some prefix of that, which will allow to filter by that prefix fast, and also giving a chance for filters by second column work.   
2) add `start_time_ts DateTime DEFAULT toDateTime( intDiv(start_time, 1000) )` it will twice faster to scan, index will be smaller. You will be able to use simple toStartOfHour() for your partitioning key. 
That means you will need to use conditions on that `start_time_ts` field for all your queries (and, optionally, if you need sub-second precision - also conditions on `start_time` **extra**). Another advantage - that you will be able to use human-readable timestamps in your queries. For example 
``` 
start_time_ts BETWEEN '2000-10-13 00:00:06' AND '2000-10-14 01:59:47'
```
instead of 
```
start_time > 971128806382 + 3 * 86400000 AND start_time < 971222387788 + 3 * 86400000
```
3) consider using numerical datatypes for storing numerical data - for example '938036742605759' can be stored in UInt64 (8 bytes), currently it stored as string and take 15 bytes of data + length prefix. That will lead to about twice faster scans of that value, and storage will work more efficient.

**Comment by alexey-milovidov** [comment]
You can look at the query metics and compare them:
https://clickhouse.github.io/clickhouse-presentations/dataops_2019/#29

(press "right" and look at the following slides)

**Comment by alexey-milovidov** [comment]
There can be multiple reasons why the same query on identical data in different tables may take different time. For example, the sequential read speed from HDD can depend on data location in sectors (close or far from the center of the disk). For ext4, it's typical that two files can be placed far from each other and you will see ~1.5x performance difference.
