### ISSUE TITLE
Stress test/Upgrade check failed with `Unknown, exit_code 1`

### ISSUE THREAD

**Issue by vdimir** [ClickHouse/ClickHouse#72248]
[ci](https://play.clickhouse.com/play?user=play#CldJVEgKICAgIGZhbHNlIGFzIG9ubHlfbWFzdGVyClNFTEVDVCAqCkZST00gKApTRUxFQ1QKICAgIHB1bGxfcmVxdWVzdF9udW1iZXIgYXMgcHJudW0sCiAgICBzdWJzdHIoY29tbWl0X3NoYSwgMSw5KSBhcyBzaGEsCiAgICByb3VuZCh0ZXN0X2R1cmF0aW9uX21zIC8gMTAwMCwgMikgYXMgZHVyLAogICAgY2hlY2tfc3RhcnRfdGltZSwKICAgIGZvcm1hdFJlYWRhYmxlVGltZURlbHRhKGludERpdihub3coKSAtIGNoZWNrX3N0YXJ0X3RpbWUsIDM2MDApICogMzYwMCkgYXMgYWdvLAogICAgY2hlY2tfbmFtZSwKICAgIGNoZWNrX3N0YXR1cywKICAgIHRlc3RfbmFtZSwKICAgIHJlcG9ydF91cmwsIGNvbW1pdF91cmwKRlJPTSBjaGVja3MKV0hFUkUgMQogICAgQU5EIGNoZWNrX3N0YXJ0X3RpbWUgPj0gbm93KCkgLSBJTlRFUlZBTCA3IERBWQogICAgQU5EIChwdWxsX3JlcXVlc3RfbnVtYmVyID0gMCBPUiBub3Qgb25seV9tYXN0ZXIpCiAgICBBTkQgdGVzdF9zdGF0dXMgIT0gJ1NLSVBQRUQnCiAgICBBTkQgdGVzdF9zdGF0dXMgTElLRSAnRiUnCiAgICBBTkQgY2hlY2tfc3RhdHVzICE9ICdzdWNjZXNzJwogICAgQU5EIHRlc3RfY29udGV4dF9yYXcgbGlrZSAnJVVua25vd24sIGV4aXRfY29kZSUnCiAgICBBTkQgKGNoZWNrX25hbWUgbGlrZSAnU3RyZXNzJScgT1IgY2hlY2tfbmFtZSBsaWtlICdVcGdyYWRlJScpCikKCk9SREVSIEJZIGNoZWNrX3N0YXJ0X3RpbWUgREVTQywgY2hlY2tfbmFtZSwgdGVzdF9uYW1lCkxJTUlUIDEgYnkgc2hh)

| prnum | sha | dur | check_start_time | ago | check_name | check_status | test_name | report_url | commit_url |
|-:|:-|-:|-:|:-|:-|:-|:-|:-|:-|
| 72027 | ee176bec6 | 0 | 2024-11-22 02:24:06 | 7 hours | Upgrade check (asan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/ee176bec6a98cac1185b7ecd996e2bd997f44f9c |
| 72233 | e5cfc7dae | 0 | 2024-11-22 01:57:03 | 8 hours | Upgrade check (msan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/e5cfc7daee6e376c9f635ac4033ddf57554ee469 |
| 71439 | 32891af06 | 0 | 2024-11-22 00:36:56 | 9 hours | Stress test (ubsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/32891af064c54922bb64c36cd63b84a882d18067 |
| 71784 | b5f6219a6 | 0 | 2024-11-22 00:23:55 | 9 hours | Upgrade check (debug) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/b5f6219a6bbdd5892d95254de7a0721260cb684d |
| 72229 | d67f2644c | 0 | 2024-11-21 23:59:00 | 10 hours | Upgrade check (tsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/d67f2644cf73eef27d1b9a771962d4db42ddf4fa |
| 72211 | f87013250 | 0 | 2024-11-21 23:47:06 | 10 hours | Upgrade check (tsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/f87013250b88064df00f084d8ec5a900ff45b685 |
| 72224 | 2c4c93873 | 0 | 2024-11-21 22:39:21 | 11 hours | Upgrade check (debug) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/2c4c938735d91dda8be5ae647633f30212e495d8 |
| 71577 | 62789dab3 | 0 | 2024-11-21 22:23:01 | 11 hours | Upgrade check (debug) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/62789dab310a2af861a5fc6e7e893c5095f8a62a |
| 69445 | 57d7a845d | 0 | 2024-11-21 21:49:50 | 12 hours | Upgrade check (debug) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/57d7a845da1d738fed05cbe677c8b29d23c33f95 |
| 72225 | 0ec58641d | 0 | 2024-11-21 21:21:14 | 12 hours | Stress test (tsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/0ec58641d382ba2716e1601b8d8e35aae14d390e |
| 0 | 3dd3cf1cf | 0 | 2024-11-21 20:35:39 | 13 hours | Stress test (tsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/3dd3cf1cf35edb59d491e5f0baa3f20ef2c0c9e7 |
| 0 | acb968a8c | 0 | 2024-11-21 20:30:03 | 13 hours | Stress test (msan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/acb968a8c66b9278b97469662784371e1712ac07 |
| 0 | f261c341c | 0 | 2024-11-21 20:18:31 | 13 hours | Stress test (ubsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/f261c341c8516ec55a701ceec29fb40122eed08b |
| 72219 | 04d99cc43 | 0 | 2024-11-21 19:19:51 | 14 hours | Stress test (asan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/04d99cc430e7e3997b753b7f161d9c56d6eb3de6 |
| 0 | e4c9b0222 | 0 | 2024-11-21 18:38:39 | 15 hours | Stress test (tsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/e4c9b022237992620c966d032cee495da8d0b5ac |
| 71995 | 9c542799d | 0 | 2024-11-21 15:38:47 | 18 hours | Upgrade check (tsan) | error | COMPLETED |  | https://github.com/ClickHouse/ClickHouse/commit/9c542799d83116eb620bdc283fb4efd283e80fa4 |

**Comment by maxknv** [comment]
yes. i reverted that breaking change.
