### ISSUE TITLE
Use of array from WITH section in where IN statement

### ISSUE THREAD

**Issue by alanrigele** [ClickHouse/ClickHouse#7225]
I have searched the interwebs for a possible reason or work around to my requirement. 

I am building a performance monitoring tool which will has a web based front end interface to define and build kpi calculations from various counters. The selection of counters and the formula in the WITH section are fine, but does not get applied in the WHERE counterName IN 

below is a sample 

with (select ['67183489','67183490']) as arr, (avg_cnt2/avg_cnt1) as formula, arrayJoin(arr) as dst
SELECT toStartOfHour(startDateTime) as dt, ID, 
splitByChar(',',splitByString('=',ID)[2])[1] as CellLabel,
splitByChar('/',splitByString('=',ID)[3])[1] as CellId,
splitByChar('/',splitByString('DEST Cell ID:',ID)[2])[1] as DestCellId,
sumIf(toFloat64(counterValue),counterName=arr[0]) as avg_cnt1,
sumIf(toFloat64(counterValue),counterName=arr[1]) as avg_cnt2,
formula*100 as HandOverRate
from RAN.RawCounters
where  counterName IN (arr)
--counterName IN (dst) and 
toDate(startDateTime) = '2019-10-02'
group by dt,ID,CellLabel,CellId,DestCellId

the filter counterName IN ('67183489','67183490') functions 100% correctly. 
I have tried using the array, arrayJoin(arr) and a few other options. 

Using counterName IN (arr) creates the following exception
ClickHouse exception, code: 53, host: 172.28.247.16, port: 8123; Code: 53, e.displayText() = DB::Exception: Types of column 1 in section IN don't match: Array(String) on the right, String on the left. (version 19.15.2.2)

Using the arrayJoin(arr) from the WITH section or in the IN filter provides
ClickHouse exception, code: 36, host: 172.28.247.16, port: 8123; Code: 36, e.displayText() = DB::Exception: Element of set in IN, VALUES or LIMIT is not a constant expression: dst (version 19.15.2.2)

If there is a way to do this, it would be greatly appreciated and would be a good example of the flexibility and power of clickhouse.

**Comment by blinkov** [comment]
@alanrigele, is this question still relevant?

**Comment by blinkov** [comment]
@alanrigele, do you have any further questions?

**Comment by ILYenBui** [comment]
Hi, 
For the filter of `where counterName IN (arr)` you can replace with the following code: `where has(arr, counterName) > 0`.
Regards,

**Comment by danieladoghe** [comment]
Solution:
Replace where counterName IN (arr) with where has(arr, counterName) > 0 and it should work.

**Comment by melvynator** [comment]
Closing given an answer has been provided.
