### ISSUE TITLE
100% CPU usage from spin_lock

### ISSUE THREAD

**Issue by Shonke** [ClickHouse/ClickHouse#72287]
**Describe the situation**
High CPU usage, everything is slow
<img width="739" alt="Snipaste_2024-11-22_22-19-49" src="https://github.com/user-attachments/assets/ba63ce9a-dbf3-44a4-b93a-f2301571b5b7">
<img width="868" alt="Snipaste_2024-11-22_22-19-28" src="https://github.com/user-attachments/assets/c1325308-ad7a-4ed9-995a-b45056493fb1">

**How to reproduce**
ClickHouse version：version 24.2.3.70 (official build)
Download from here: [registry.docker.com/clickhouse/clickhouse-server:24.2.3.70-alpine](http://registry.docker.com/clickhouse/clickhouse-server:24.2.3.70-alpine)

**Additional context**
[37847.statck.txt](https://github.com/user-attachments/files/17872654/37847.statck.txt)

**Comment by nickitat** [comment]
2 cores is not high usage. you need to upgrade to a supported version, check what CH is doing. first in `processlist`, then you could collect aggregated stacktraces (flamegraph or use our own `utils/postprocess-traces/postprocess-traces.pl`).

**Comment by Shonke** [comment]
The utilization rate of two cores is due to the allocation of only two cores. In addition, after conducting experiments, the problem was found to be caused by the use of wait_for_async_insert

Thank you for your reply @nickitat
