### ISSUE TITLE
Initialize macros from environment variables

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7229]
As below, we set replica = example05-02-1.yandex.ru , and example05-02-1.yandex.ru is our hostname.  
But if we have hundreds of machines ， we have to set for each one.
How about use a variable -- such as `<replica>${hostname}</replica>` ?
what do you guys think of my suggestion? I want to make our config files all the same for each machine like hadoop~

```
<macros>
    <layer>05</layer>
    <shard>02</shard>
    <replica>example05-02-1.yandex.ru</replica>
</macros>
```

**Comment by den-crane** [comment]
And how are going to set `<shard>` and `<layer>` ?
I just use `chech` and generate macros.xml using internal cmdb  which knows what node is which shard, and substitutes <replica with hostname.

**Comment by Tasselmi** [comment]
> cmdb

so how about make `layer `  `shard` `replica` all variable?
for example:
```
<macros>
    <layer>${sub_cluster_name}</layer>
    <shard>${shard_name}</shard>
    <replica>${hostname}</replica>
</macros>
```

**Comment by filimonov** [comment]
@Tasselmi it sound like you are looking for that:
#2741
#3483

BTW. Looks like from_env is not documented.

**Comment by Tasselmi** [comment]
> @Tasselmi it sound like you are looking for that:
> #2741
> #3483
> 
> BTW. @BayoNet looks like `from_env` is not documented.

actually I think `from_env` is little different from what I expect.
I want to parse `macros` from our server configuration.
for example:
```
<remote_servers>
    <cluster_1st>  --This is layer, it equals 'cluster_1st'
        <shard>  --This is shard number , it equals '1' or 'shard1'
            <weight>1</weight>
            <internal_replication>false</internal_replication>
            <replica>
                <host>TimeMachine01</host>   --This is replica, it equals hostname or ip
                <port>9000</port>
            </replica>
            <replica>    
                <host>TimeMachine02</host>   --This is replica, it equals hostname or ip
                <port>9000</port>
            </replica>
        </shard>
        <shard>  --This is shard number , it equals 2 , and so on
            <weight>1</weight>
            <internal_replication>false</internal_replication>
            <replica>  
                <host>TimeMachine03</host>   --This is replica, it equals hostname or ip
                <port>9000</port>
            </replica>
            <replica>  
                <host>TimeMachine04</host>    --This is replica, it equals hostname or ip
                <port>9000</port>
            </replica>
        </shard>
    </cluster_1st>
</remote_servers>
```
IF we have to configure env variable for each machine, it is the same complexity for Setting configure file for each machine. So it's a bad idea.

I think we should parse macros from `servers configure file`~

plz think twice about my advice. Thanks.

**Comment by Tasselmi** [comment]
> And how are going to set `<shard>` and `<layer>` ?
> I just use `chef` and generate macros.xml using internal cmdb which knows what node is which shard, and substitutes <replica with hostname.

hi，please see my latest comment. I think we should extract macros from `remote_servers ` configuration. How do u think? thus our configure file will be all the same.

**Comment by Tasselmi** [comment]
> @Tasselmi it sound like you are looking for that:
> #1616
> #2741
> #3483
> 
> BTW. @BayoNet looks like `from_env` is not documented.

hi，please see my latest comment. I think we should extract macros from `remote_servers` configuration. How do u think? thus our configure file will be all the same.

configuration in `remote_servers` -- the hostname and their order actually already tell us what replica and what shard belongs to.

**Comment by Tasselmi** [comment]
@filimonov @alexey-milovidov

**Comment by den-crane** [comment]
> configuration in `remote_servers` -- the hostname and their order actually already tell us what replica and what shard belongs to.

I have 4 clusters in remote_servers with 12 nodes. 1 shard * 12 replicas, 12 shards * 1 replica, 4 shards * 3 replicas, 6 shards * 2 replicas.
The same time a node have 4 different shard and replica values.

**Comment by Tasselmi** [comment]
> > configuration in `remote_servers` -- the hostname and their order actually already tell us what replica and what shard belongs to.
> 
> I have 4 clusters in remote_servers with 12 nodes.
> 1 shard * 12 replicas, 12 shards * 1 replica, 4 shards * 3 replicas, 6 shards * 2 replicas.
> The same time a node has 4 different shard and replica values.
> 
> Something close implemented in DatabaseReplicated #16193

so , what you mean is that you run multi clickhouse instances in one node, right ?  How could this happen, I've no idea, Is there any document? THx.

**Comment by den-crane** [comment]
> so , what you mean is that you run multi clickhouse instances in one node, right ? How could this happen, I've no idea, Is there any document? THx.

No. I mean that Clickhouse instance can a member of any number of clusters the same time.

**Comment by Tasselmi** [comment]
ok. I totally understand what you say.  In this situation , we can store some metadata, like each cluster layer and their shards and replicas.

**Comment by Tasselmi** [comment]
> > so , what you mean is that you run multi clickhouse instances in one node, right ? How could this happen, I've no idea, Is there any document? THx.
> 
> No. I mean that Clickhouse instance can be a member of any number of clusters at the same time.

ok. I totally understand what you say. In this situation , we can store some metadata, like each cluster layer and their shards and replicas.
