### ISSUE TITLE
Suspicious high bytes_on_disk value

### ISSUE THREAD

**Issue by artem-pershin** [ClickHouse/ClickHouse#72307]
### Question

Why bytes_on_disk is almost 10x of compressed_size? I suppose it should be almost equal (with respect to some padding)
Below is the result of the query from docs https://clickhouse.com/docs/knowledgebase/useful-queries-for-troubleshooting#compression-columns-percentage-as-well-as-the-size-of-primary-index-in-memory:

```Row 2:
parts.table:            tbl_shard
rows:                   4417625752
latest_modification:    2024-11-22 18:57:34
disk_size:              491.82 GiB
primary_keys_size:      3.09 MiB
engine:                 ReplicatedMergeTree
bytes_size:             528090154635
compressed_size:        36.42 GiB
uncompressed_size:      428.39 GiB
compression_ratio:      0.085
compression_percentage: 91.499
```

Disk size is almost like there is no compression at all, or i don't understand something about these numbers.

**Comment by den-crane** [comment]
it's a strange query, why does it need a system.columns and right_join?

try

```
SELECT
    database,
    table,
    formatReadableSize(sum(data_compressed_bytes) AS size) AS compressed,
    formatReadableSize(sum(data_uncompressed_bytes) AS usize) AS uncompressed,
    round(usize / size, 2) AS compr_rate,
    sum(rows) AS rows,
    count() AS part_count
FROM system.parts
WHERE (active = 1) AND (database LIKE '%') AND (table LIKE '%')
GROUP BY
    database,
    table
ORDER BY size DESC;
```

**Comment by artem-pershin** [comment]
Here is the result of the query:
```Row 1:
──────
database:     db
table:        tbl_shard
compressed:   36.59 GiB
uncompressed: 429.68 GiB
compr_rate:   11.74
rows:         4424812969
part_count:   297
```

Pretty much the same as the initial query. Total size on disk is:
```
495G	./69d
```

So, it's correct value in my first query (bytes_on_disk). Also total_bytes in system.tables shows the same value (495Gb). But it seems that i found where my space is (it's projections, three of them):

```
Row 1:
──────
database:     db
table:        tbl_shard
name:         proj_1
compressed:   260.33 GiB
uncompressed: 678.29 GiB
compr_rate:   2.61
rows:         4424812969
part_count:   297

Row 2:
──────
database:     db
table:        tbl_shard
name:         proj_2
compressed:   129.07 GiB
uncompressed: 530.31 GiB
compr_rate:   4.11
rows:         4424812969
part_count:   297

Row 3:
──────
database:     db
table:        tbl_shard
name:         proj_3
compressed:   67.75 GiB
uncompressed: 463.42 GiB
compr_rate:   6.84
rows:         4424812969
part_count:   297
```

If we sum up all parts from projections and all parts from system.parts table, it sums up to 495 G.
It's astonishing for me how 1 projection could take 8x size from initial data (sorted by id)...
