### ISSUE TITLE
Table engine 'dictionary' raise error on queries. Version of clickhouse - 19.15.2 revision 54426

### ISSUE THREAD

**Issue by twinky618** [ClickHouse/ClickHouse#7232]
fter upgrade clickhouse to 19.15.2.2 some queries to tables with engine 'dictionary' crashed with error:
`select * from city_dict`
error ->
`2019.10.08 17:24:17.202894 [ 88 ] {d2503d49-af1a-4ae5-88c1-0939ea87a65c} <Error> executeQuery: std::exception. Code: 1001, type: std::bad_variant_access, e.what() = Unexpected index, version = 19.15.2.2 (from [::ffff:172.31.102.63]:55352) (in query: select * from city_dict FORMAT TabSeparatedWithNamesAndTypes;)`

Direct access to dictionary work fine
` select dictGetString('city_dict','name', toUInt64(1))`

Table create DDL:
`create table if not exists city_dict
(
	id UInt64,
	name String
)
engine = Dictionary(city_dict);`

Dictionary config:
`<dictionary>
    <name>city_dict</name>
    <source>
      <odbc>
        <db>watchman_dev</db>
        <table>public.cities</table>
        <connection_string>DSN=postgres</connection_string>
      </odbc>
    </source>
    <layout>
      <sparse_hashed />
    </layout>
    <structure>
      <id>
        <name>id</name>
      </id>
      <attribute>
        <name>name</name>
        <type>String</type>
        <null_value></null_value>
      </attribute>
    </structure>
    <lifetime>50</lifetime>
</dictionary>`

**Comment by den-crane** [comment]
duplicate for https://github.com/ClickHouse/ClickHouse/issues/7194

**Comment by twinky618** [comment]
@den-crane yesterday we updated clickhouse to 19.15.2.2 yesterday on Oracle Linux Server through 
`yum install clickhouse-server`, however see this errors.
`2019.10.08 17:24:17.202894 [ 88 ] {d2503d49-af1a-4ae5-88c1-0939ea87a65c} <Error> executeQuery: std::exception. Code: 1001, type: std::bad_variant_access, e.what() = Unexpected index, version = 19.15.2.2 (from [::ffff:172.31.102.63]:55352) (in query: select * from city_dict FORMAT TabSeparatedWithNamesAndTypes;)`

**Comment by alesapin** [comment]
We will make bugfix release today.

**Comment by twinky618** [comment]
@alesapin we have updated clickhouse through yum. Version - 19.15.2.2-1.el7 and Repository - altinity_clickhouse. However see this error again(

**Comment by alesapin** [comment]
You should update to 19.15.3.6.

**Comment by twinky618** [comment]
@alesapin 
Colleagues, when you can upload to https://packagecloud.io/Altinity/clickhouse?

**Comment by den-crane** [comment]
@twinky618 you should ask Altinity or use official RPM https://repo.yandex.ru/clickhouse/rpm/stable/x86_64/

**Comment by filimonov** [comment]
> @alesapin
> Colleagues, when you can upload to https://packagecloud.io/Altinity/clickhouse?

Altinity build for ClickHouse RPMs v19.15.3.6-stable published
