### ISSUE TITLE
leadInFrame only produces default values when using `OVER (ORDER BY ...)`, but works for `OVER ()`

### ISSUE THREAD

**Issue by nielsreijers** [ClickHouse/ClickHouse#72354]
**Describe what's wrong**

`leadInFrame` only returns default values for `OVER (ORDER BY ...)`.
`lagInFrame` does work as expected, and `leadInFrame` also works when no sort order is specified.

```
SELECT
    number,
    lagInFrame(number, 1, 8472) OVER () AS lag,
    leadInFrame(number, 1, 8472) OVER () AS lead,
    lagInFrame(number, 1, 8472) OVER (ORDER BY number ASC) AS lagASC,
    leadInFrame(number, 1, 8472) OVER (ORDER BY number DESC) AS leadDESC,
    lagInFrame(number, 1, 8472) OVER (ORDER BY number DESC) AS lagDESC,
    leadInFrame(number, 1, 8472) OVER (ORDER BY number ASC) AS leadASC
FROM numbers(5)
ORDER BY number ASC

Query id: 28313677-2fe4-4b42-9cc8-ef55169431e4

   ┌─number─┬──lag─┬─lead─┬─lagASC─┬─leadDESC─┬─lagDESC─┬─leadASC─┐
1. │      0 │ 8472 │    1 │   8472 │     8472 │       1 │    8472 │
2. │      1 │    0 │    2 │      0 │     8472 │       2 │    8472 │
3. │      2 │    1 │    3 │      1 │     8472 │       3 │    8472 │
4. │      3 │    2 │    4 │      2 │     8472 │       4 │    8472 │
5. │      4 │    3 │ 8472 │      3 │     8472 │    8472 │    8472 │
   └────────┴──────┴──────┴────────┴──────────┴─────────┴─────────┘

5 rows in set. Elapsed: 0.003 sec. 
```

**Does it reproduce on the most recent release?**

Yes: https://fiddle.clickhouse.com/406814fa-15d4-419c-bf42-5a115e363ddc

**How to reproduce**

See fiddle link.

**Expected behavior**

I would expect leadInFrame with a sort order to be equivalent to lagInFrame with the reverse sort order.

For example, MariaDb produces this output:
```
MariaDB [testdb]> SELECT number
    ->     ,LAG(number) OVER (ORDER BY number ASC) lagASC
    ->     ,LEAD(number) OVER (ORDER BY number DESC) leadDESC
    ->     ,LAG(number) OVER (ORDER BY number DESC) lagDESC
    ->     ,LEAD(number) OVER (ORDER BY number ASC) leadASC
    -> FROM numbers
    -> ORDER BY number;
+--------+--------+----------+---------+---------+
| number | lagASC | leadDESC | lagDESC | leadASC |
+--------+--------+----------+---------+---------+
|      0 |   NULL |     NULL |       1 |       1 |
|      1 |      0 |        0 |       2 |       2 |
|      2 |      1 |        1 |       3 |       3 |
|      3 |      2 |        2 |       4 |       4 |
|      4 |      3 |        3 |    NULL |    NULL |
+--------+--------+----------+---------+---------+
5 rows in set (0.000 sec)
```

for a temporary `numbers` table created like this:
```
DROP TEMPORARY TABLE IF EXISTS numbers;
CREATE TEMPORARY TABLE IF NOT EXISTS numbers (number int);
INSERT INTO numbers(number) VALUES (0),(1),(2),(3),(4);
```

**Comment by den-crane** [comment]
It's expected behaviour. It's more a documentation issue.

Window frame is independent of a aggregate function. And with `(ORDER BY number ASC)` frame starts from the current element so the previous element simple not visible for `leadInFrame` because it's out of a frame scope.

Your query is missed of `rows between unbounded preceding and unbounded following`. https://clickhouse.com/docs/en/sql-reference/window-functions

* https://github.com/ClickHouse/ClickHouse/issues/67744

**Comment by nielsreijers** [comment]
Thanks for the quick response!

I now noticed the "To get behavior identical to `lag/lead`, use `rows between unbounded preceding and unbounded following`" in the docs, and that does indeed work: https://fiddle.clickhouse.com/4a421948-8a66-4029-a28a-66072809c013

But unfortunately that documentation isn't available on the pages for `lagInFrame` or `leadInFrame`, but only in the Windows Functions page, and it's not that easy to find what a frame is and how it's bounded.

I found the examples now, and they do explain the frame is bounded by the beginning of the partition and the current row when you do an `ORDER BY`, but the example "-- short form - no bound expression, no order by" isn't explicit about what the frame is. Is it unbounded in that case, since `leadInFrame(number) OVER ()` did work as expected?

I found it especially confusing that adding the `ORDER BY` changed the result, since just like with `numbers()` in the real query I was working on, the input was already sorted.
I only added the ORDER BY to make it explicit, and didn't expect that would change the result. (it only needs to handle a few thousand rows and doesn't need to be fast, so I didn't care about any potential performance hit)

So I agree it's all in the docs, but I think these two differences were very confusing for me:
- `leadInFrame` is not identical to `lagInFrame` with the reversed order
- that `leadInFrame(number) OVER ()` did work as expected, but `leadInFrame(number) OVER (ORDER BY number)` didn't.

I think it would be clearer for me if `leadInFrame(number) OVER ()` had used the same frame and only produced default values, but I guess changing that now would be a huge breaking change, if it's even technically possible.

I'm just writing down what caused my confusion here in case it helps for improving the docs. Thanks for that. :)


One thing I am still wondering is if this shouldn't be an error? If the query uses `leadInFrame(...) OVER (ORDER BY ...)` without specifying a `ROWS` window, are there scenarios where it can produce something meaningful?

If it's certain it's only going to produce default values, that's almost certainly not what the user wants, so maybe making a `ROWS` clause mandatory for `leadInFrame` to force the user to think about it would be helpful? Or alternatively throwing an error if ClickHouse can determine it's always going to produce the default would also help.
But of course both these options would also be a breaking change.

**Comment by den-crane** [comment]
Disclaimer: I am an ordinary guy from the internet not affiliated to Clickhouse.

------

>But unfortunately that documentation isn't available on the pages for lagInFrame or leadInFrame, but only in the Windows Functions page, and it's not that easy to find what a frame is and how it's bounded.

Right, I made a PR to fix it.

>I found the examples now, and they do explain the frame is bounded by the beginning of the partition and the current row when you do an ORDER BY, but the example "-- short form - no bound expression, no order by" isn't explicit about what the frame is.

Right, my bad. I'll fix it. 

`OVER ()` -- means `ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING` with arbitrary order (the order from the input stream
`OVER (order by X)` -- means `ORDER BY X BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`

 > Is it unbounded in that case, since leadInFrame(number) OVER () did work as expected?

No, it does not. ORDER of the rows in the frame is arbitrary in this case. It's unusable for lag/lead.

>I only added the ORDER BY to make it explicit, and didn't expect that would change the result. (it only needs to handle a few thousand rows and doesn't need to be fast, so I didn't care about any potential performance hit)

It's expected. WINDOW FUNCTION require  the proper ORDER BY in a WINDOW declaration. Otherwise the result can be mutated by SELECT's ORDER BY (it's true for any DBMS, not specific for Clickhouse).

>So I agree it's all in the docs, but I think these two differences were very confusing for me:
>leadInFrame is not identical to lagInFrame with the reversed order
>that leadInFrame(number) OVER () did work as expected, but leadInFrame(number) OVER (ORDER BY number) didn't.

Right, window functions are complicated and hard to realize. I suggest to play with them more in a fiddle. Also chatgpt can explain a lot. But it is a powerful tool https://github.com/ClickHouse/ClickHouse/discussions/63041#discussioncomment-9238027

>One thing I am still wondering is if this shouldn't be an error?

It's too complex question.

There are other examples like this:
```
SELECT toDateTime()('2023-01-01')  -- what is the () are doing here ?
   ┌─toDateTime('2023-01-01')─┐
1. │      2023-01-01 00:00:00 │
   └──────────────────────────┘
```

```
SELECT
  DENSE_RANK(a) OVER(ORDER BY id) DR,  -- DENSE_RANK does not accept arguments, (a) -- is not used here
  RANK(a) OVER(ORDER BY id) R -- RANK does not accept arguments, (a) -- is not used here
FROM (select 1111 a, 2 id )
┌─DR─┬─R─┐
│  1 │ 1 │
└────┴───┘
```
