### ISSUE TITLE
Partitioned S3 Table can't change {_partition_id} when using Materialized view

### ISSUE THREAD

**Issue by caoyang10** [ClickHouse/ClickHouse#72374]
### Question

reproduce: 
1, change user settings 
<s3_create_new_file_on_insert>1</s3_create_new_file_on_insert>

2, create s3 table 
create table s3 (
    p Int64
)
engine = S3('https://xxx-bucket.s3.amazonaws.com/xxx-path/{_partition_id}.json', 'xxx-ak', 'xxx-sk', 'JSONEachRow')
partition by p

3, create streaming table like kafka
CREATE TABLE kafka
(
    s Int64
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'xxx', kafka_topic_list = 'xxx', kafka_group_name = 'xxx', kafka_format = 'JSONEachRow'

4, create mv 
create materialized view mv to s3 as select s % 1 as p from kafka

then send some test data to kafka and data in s3 is like: 
 s3://xxx-bucket/xxx-path/{_partition_id}.1.json
 s3://xxx-bucket/xxx-path/{_partition_id}.2.json
...

which I expect is 
s3://xxx-bucket/xxx-path/1.1.json
 s3://xxx-bucket/xxx-path/1.2.json
...

Also, insert directly is the correct behavior
Insert into s3 values (1)
you can see the data at s3://xxx-bucket/xxx-path/1.json

How can I use {_partition_id} when using materialized view?

**Comment by Felixoid** [comment]
I tried to reproduce it in the following steps:

```sql
CREATE TABLE s3
(
    `p` Int64
)
ENGINE = S3('https://....s3.amazonaws.com/xxx-path/{_partition_id}.json', 'key', 'secret', 'session', 'JSONEachRow') partition by p SETTINGS s3_create_new_file_on_insert=1;

-- the following insert repeated 3 times

Insert into s3 values (1) ;
```


And that what I have in the bucket:

![image](https://github.com/user-attachments/assets/0477394b-9759-4dbe-b2c0-06c91073dd36)

Then I do the next:

```sql
-- 3 times
Insert into s3 values (2) ;
```

And the bucket content is the next:
![image](https://github.com/user-attachments/assets/f5866a01-c1f7-400f-8a94-9a18c1609301)

Another test:

```sql
Insert into s3 SELECT number % 4 FROM system.numbers LIMIT 10;
```

And there are new files:

![image](https://github.com/user-attachments/assets/e3a8c752-83ca-4886-aafe-0c82b44e666a)


The first time, it creates the file as it names without the prefix `1.json`, and then for the following inserts, it creates new files with suffices accordingly. Take a look at the size, especially, on `3.json` on the latest screenshot. It's created with two lines only once.

Does it explain the behavior?

**Comment by caoyang10** [comment]
@Felixoid I said Insert SQL is the correct behavior, but using Kafka and Materialized view is not. You can try it, thanks for replying me~

**Comment by caoyang10** [comment]
Also, I don't know how to mock streaming data. I'm sure that create MV from Kafka source to Partitioned S3 sink, `_partition_id` doesn't work

**Comment by caoyang10** [comment]
@Felixoid I find a simple way to reproduce it:
1, create partitioned s3 table
```
CREATE TABLE s3
(
    `p` Int64
)
ENGINE = S3('https://....s3.amazonaws.com/xxx-path/{_partition_id}.json', 'key', 'secret', 'session', 'JSONEachRow') partition by p SETTINGS s3_create_new_file_on_insert=1;
```

2, create mergetree table as source
```
CREATE TABLE source
(
    `s` Int64
) engine = MergeTree() partition by tuple() order by tuple()
```

3, create mv
`create materialized view mv to s3 as select s as p from source`

4, try some different insert query:
```
insert into s3 values (1);
insert into source values(2);
```

you will see that the data path will display as:
1.json
{_partition_id}.json

**Comment by Felixoid** [comment]
Cool thing. Here's the directory with a simple docker-compose.yml to reproduce it https://github.com/Felixoid/community-questions/tree/master/72374

**Comment by Felixoid** [comment]
The bug issue is created, thanks a lot for helping to reproduce it!
