### ISSUE TITLE
Add configuration parameter to hide addresses in stack traces.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7238]
**Use case**
This option may be enabled for security reasons.

Implementation details:

Do not enable it by default. Do not add this option as an example to configuration file, because we don't think it's a good idea to enable it. But the user can add it to config if it's really needed.

`<print_addresses_in_stack_traces>false</print_addresses_in_stack_traces>` (true by default)

Add static variable to `StackTrace` and change it on server initialization. Use it inside StackTrace.cpp.

**Comment by alexey-milovidov** [comment]
@loqutus Ok, now it's yours!

**Comment by alexey-milovidov** [comment]
Now this task is unassigned.

**Comment by denistarasov** [comment]
Did I get it right that I need to add a static field `static bool hide_addresses_in_stack_traces` (not sure if the naming is suitable), then I need to change these lines https://github.com/ClickHouse/ClickHouse/blob/7bc561dd55b9188fb2cb4948cd4b11ab763a4f29/dbms/src/Common/StackTrace.cpp#L28-L31

to something like this:

```
if (StackTrace::hide_addresses_in_stack_traces)
    error << "Address: hidden";
else
{
    if (nullptr == info.si_addr)
        error << "Address: NULL pointer.";
    else
        error << "Address: " << info.si_addr;
}
```

Some other questions:
- > change it on server initialization 

Does it mean adding settings to this [file](https://github.com/ClickHouse/ClickHouse/blob/e14f395001586d017c41f8b78f8429407c7971b8/dbms/src/Core/Settings.h)?
- Addresses should be hidden only in case of SIGSEGV?

**Comment by alexey-milovidov** [comment]
Not relevant after https://github.com/ClickHouse/ClickHouse/pull/8387
