### ISSUE TITLE
Documentation: Example from new  JSON type not working

### ISSUE THREAD

**Issue by AntonFriberg** [ClickHouse/ClickHouse#72436]
**Describe the issue**
Tried to execute the examples from https://clickhouse.com/docs/en/sql-reference/data-types/newjson#creating-json  specifically this example https://github.com/ClickHouse/ClickHouse/blob/master/docs/en/sql-reference/data-types/newjson.md?plain=1#L76

```sql
SET allow_experimental_json_type = 1;
SELECT (tuple(42 AS b) AS a, [1, 2, 3] AS c, 'Hello, World!' AS d)::JSON AS json;
```

I get the following error on v24.10.2.80 and v24.8.8.17

```
Received exception:
Code: 53. DB::Exception: Cast to JSON can be performed only from String. Got: Tuple(Tuple(UInt8), Array(UInt8), String): In scope SELECT CAST((tuple(42 AS b) AS a, [1, 2, 3] AS c, 'Hello, World!' AS d), 'JSON') AS json. (TYPE_MISMATCH)
```

**Additional context**
I have tried to get it to work in different versions of ClickHouse but has not been successful. Is it related to today's release of 24.11 perhaps?

**Comment by Avogar** [comment]
Conversion from Tuple to JSON was added in 24.11 release: https://fiddle.clickhouse.com/66ab49a8-748b-4723-b64b-4708c9bdf00d
This example also requires enabling `enable_named_columns_in_function_tuple` setting, I will update it.
