### ISSUE TITLE
AUTHENTICATION_FAILED during the creation of the dictionary

### ISSUE THREAD

**Issue by handgunman** [ClickHouse/ClickHouse#72461]
### Question

Hello!
When creating a dictionary, the host login and password are not specified. It is expected that the default user will be used.
This happens on all clickhaus installations used.
But on one of the installations the creation works only if login and password are specified explicitly.
What setting can be responsible for this behavior when connection without password does not work for the dictionary?

Best Regards!

**Comment by Felixoid** [comment]
I'd suggest starting from comparing one user to another with https://clickhouse.com/docs/en/operations/access-rights

**Comment by Felixoid** [comment]
I'm sorry, but it's a bit difficult to follow. If it would ease the conversation, we can continue in Russian.

You have two clusters. One struggle to request `SELECT * FROM remote('127.0.0.2', system.one)`, but it works with another one? And `remote('127.0.0.1', system.one)` works on both, right?

**Comment by Felixoid** [comment]
И это просто два разных инстанса КХ, которые на разных localhost слушают?

Если проверить через `clickhouse-local`, то работает также?

`clickhouse-local -q "SELECT * FROM remote('127.0.0.1', system.one)"`

Думаю, что отработает точно также. Тогда надо смотреть, что прописано в `/etc/clickhouse-server/users.*`. Видимо, у пользователя default где-то пароль стоит

**Comment by handgunman** [comment]
В обоих случаях установлен пароль для default.

и это кластеры сервиса, я не могу посмотреть что там в конфиге :( а поддержка гонит пургу

**Comment by Felixoid** [comment]
мм, это cloud сервис какого-то провайдера?

Если для дикта используется `remote`, то ты можешь попробовать использовать пароль для того, чтобы подключиться https://clickhouse.com/docs/en/sql-reference/table-functions/remote#syntax

**Comment by handgunman** [comment]
да, это cloud Яндекса. И ранее вс было там ок
Так же все ок на самоустановленном сервере.

Понятно, что можно задавать и логин и пароль и с ними все работает. Но это неудобно в схеме с разными разработчиками и отторгаемыми доступами. Оторвал доступ - отвалились словари.

Главное, не понятно, что именно они ограничили.
