### ISSUE TITLE
MySQL wire protocol: authentication issue

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#7248]
```
➜ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
➜ clickhouse-server --version
ClickHouse server version 19.15.1.1390.
➜ mysql --version
mysql  Ver 14.14 Distrib 5.5.57-38.9, for Linux (x86_64) using readline 5.1
➜ mysql -h 127.0.0.1 -P 9001
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0
➜ mysql -h 127.0.0.1 -P 9001 --user default
ERROR 2059 (HY000): Authentication plugin 'sha256_password' cannot be loaded: /usr/lib64/mysql/plugin/sha256_password.so: cannot open shared object file: No such file or directory
```

Same on docker (ubuntu).

**Comment by alexey-milovidov** [comment]
@yurriy 

> ➜ mysql -h 127.0.0.1 -P 9001 --user default
ERROR 2059 (HY000): Authentication plugin 'sha256_password' cannot be loaded: /usr/lib64/mysql/plugin/sha256_password.so: cannot open shared object file: No such file or directory

Do I understand correctly that ClickHouse server responds that it would like to use sha256_password authentication but mysql client cannot use it?

**Comment by alexey-milovidov** [comment]
And the workaround is to add sha1 password for ClickHouse user?

**Comment by yurriy** [comment]
> Do I understand correctly that ClickHouse server responds that it would like to use sha256_password authentication but mysql client cannot use it?

Yes.
It should work if password is specified using double sha1.
https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/server/users.xml#L45

**Comment by alexey-milovidov** [comment]
Ok. And if I understand correctly, sha256 is new authentication method that is only supported in newer mysql clients?

**Comment by alexey-milovidov** [comment]
@filimonov You can think on how we can make it as obvious to the user as possible.

**Comment by yurriy** [comment]
> Ok. And if I understand correctly, sha256 is new authentication method that is only supported in newer mysql clients?

Yes. In documentation, sha256 plugin [is defined](https://dev.mysql.com/doc/refman/5.6/en/sha256-pluggable-authentication.html) starting from version 5.6. Our tests use 5.7.

**Comment by filimonov** [comment]
> > Do I understand correctly that ClickHouse server responds that it would like to use sha256_password authentication but mysql client cannot use it?
> 
> Yes.
> It should work if password is specified using double sha1.
> [Tag in config](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/server/users.xml#L45) [How to generate](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/server/users.xml#L51)

Actually i was using paswordless default user. Why does it try sha256?

**Comment by yurriy** [comment]
> > > Do I understand correctly that ClickHouse server responds that it would like to use sha256_password authentication but mysql client cannot use it?
> > 
> > 
> > Yes.
> > It should work if password is specified using double sha1.
> > [Tag in config](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/server/users.xml#L45) [How to generate](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/server/users.xml#L51)
> 
> Actually i was using paswordless default user. Why does it try sha256?

Empty password isn't handled in a different way, since the plugin does it efficiently itself (without encryption).

**Comment by filimonov** [comment]
> > 
> > Actually i was using paswordless default user. Why does it try sha256?
> 
> Empty password isn't handled in a different way, since the plugin does it efficiently itself (without encryption).

I mean if sha1 is more 'portable', why don't we use that in such cases?

**Comment by yurriy** [comment]
It is possible, but it seems confusing as the authentication will work/not work depending only on whether the password is empty/non-empty.

**Comment by filimonov** [comment]
> It is possible, but it seems confusing as the authentication will work/not work depending only on whether the password is empty/non-empty.

I would rather exprect the for all plain (unencrypted) passwords, like `<password>qwerty123</password>` (also including empty password) use sha1 in mysql.

**Comment by yurriy** [comment]
> > It is possible, but it seems confusing as the authentication will work/not work depending only on whether the password is empty/non-empty.
> 
> I would rather exprect the for all plain (unencrypted) passwords, like `<password>qwerty123</password>` (also including empty password) use sha1 in mysql.

@alexey-milovidov Is it okay to use SHA1 plugin for plaintext passwords? It makes authentication more weak, since a client is expected to know SHA1 of a password, instead of a password itself.

**Comment by alexey-milovidov** [comment]
@yurriy Yes, we can activate SHA1 authentication for plaintext passwords.
Motivation: if the user use plaintext passwords for ClickHouse, it's already unsafe within native ClickHouse protocol (unless SSL is used), so it can be as safe in MySQL protocol.

**Comment by bishrtabbaa** [comment]
I still observe this error and installed Clickhouse using the `curl https://clickhouse.com/ | sh` approach recommended in the Quick Start.

I have also configured the specific user in the user.xml file to use a <password_sha256_hex> block and have confirmed authentication/authorization with that user using the vanilla/native Clickhouse client.

However, I continue to see this error when connecting using the vanilla MySQL client.

Any ideas on what else must be installed and configured?

Are there additional

**Comment by alexey-milovidov** [comment]
Older MySQL client versions require a different password hash: `double_sha1`
