### ISSUE TITLE
Automatically convert low-cardinality data to `LowCardinality` type

### ISSUE THREAD

**Issue by rschu1ze** [ClickHouse/ClickHouse#72489]
(I could swear this issue is registered already but I did not find it, so I opened a new ticket 😂)

ClickHouse should have logic which converts low cardinality data to type `LowCardinality`. This could either be done on the level of parts (where it may create consistency issues with the type as defined via DDL) or by a mutation that converts the column to the `LowCardinality` type in the background.

Kind of related: https://github.com/ClickHouse/ClickHouse/issues/70605

Cardinality statistics ([ticket](https://github.com/ClickHouse/ClickHouse/issues/55065)) will be very helpful to control the conversion.

**Comment by UnamedRus** [comment]
What the difference with https://github.com/ClickHouse/ClickHouse/issues/69916 ?
