### ISSUE TITLE
Resource Pools

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#7249]
If I recall correctly this is scheduled for Q4. Can we get few more details on the implementation and when to expect first commits? :)

**Comment by alexey-milovidov** [comment]
Start of work in Q4 (November..December).

We are considering two possible ways of implementation.
One of them is very natural but is blocked by https://github.com/ClickHouse/ClickHouse/pulls?q=is%3Apr+processors+author%3AKochetovNicolai
Another way is more hacky and we will use it only if first option will fail.

**Comment by nvartolomei** [comment]
#8449

**Comment by nvartolomei** [comment]
16433
