### ISSUE TITLE
Binary data not correctly parsed inside JSON

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#72547]
**Describe the bug**
If I dump binary data into JSON and then read back, the result is different.

**How to reproduce**
Run:
```sql
SET engine_file_truncate_on_insert = 1;
SELECT base64Encode(x'E0'); -- 4A==
INSERT INTO TABLE FUNCTION file('<path to file>', 'JSON', 'c0 String') SELECT x'E0';
SELECT base64Encode(c0) FROM file('<path to file>', 'JSON', 'c0 String'); -- 77+9
```
If I change the format to CSV, it gives the same output.

**Comment by Avogar** [comment]
It's not related to experimental JSON type, it's related to JSON output formats. And it's expected, as in JSON output format we always write valid UTF8 strings. And we have a note about it in the docs: https://clickhouse.com/docs/en/interfaces/formats#json

Use JSONEachRow format to have strings with binary data
