### ISSUE TITLE
Postgres table function fails with columns with empty arrays

### ISSUE THREAD

**Issue by xoelop** [ClickHouse/ClickHouse#72604]
**Company or project name**

Hi, I'm the [TheirStack.com](https://theirstack.com/) founder. We're migrating our main read database to use ClickHouse instead of Postgres

**Describe the unexpected behaviour**
We're using the [postgres table function](https://clickhouse.com/docs/en/sql-reference/table-functions/postgresql). It works well, except when array columns in postgres have empty arrays. In that case, we get an error like this:

```
Code: 36. DB::Exception: PostgreSQL cannot infer dimensions of an empty array: ch_job_read."commitments": while fetching postgresql table structure. (BAD_ARGUMENTS) (version 24.12.1.377 (official build)
 ```

**How to reproduce**
* Which ClickHouse server version to use

This is what some of the rows look like
![image](https://github.com/user-attachments/assets/406c6a5f-662e-4148-9bb9-c32a0e0af9ba)

As you can see, Postgres has the right type of the column - text[]. These are all the things I tried:

- doing `describe table ch_job_view`
- doing `insert into job select * from ch_job_view`
- doing `select * from ch_job_view`
- doing `select commitments from ch_job_view`
- doing `select commitments::varchar[] from ch_job_view`
- doing `select commitments::Array(String) from ch_job_view`

And the all let to the same error

**Expected behavior**
I'd like that column to be read as an `Array(String)` one, just like the others that have no empty values. This is a pretty common case and I'm not sure how to proceed

**Error message and/or stacktrace**
![image](https://github.com/user-attachments/assets/d575045f-e18c-48b7-8e9e-d962f62e3e0a)

I saw similar issues that had been closed, but I see this is still a problem, hence opening this one.

**Comment by Lawiss** [comment]
I have the same issue, I noticed that if the first rows of the PostgreSQL table contain non empty arrays values, ClickHouse succeed to infer the PostgreSQL array column as a Clickhouse array column. However if there is only empty arrays values in the first rows scanned by CH, it fails. I don't know how many rows scans CH to infer array dims but maybe it could be increased.

**Comment by lifeofzero** [comment]
+1 to getting this issue fixed.

**Comment by jsc0218** [comment]
Well, I think this is introduced in this [pr](https://github.com/ClickHouse/ClickHouse/pull/57436/files). There is some tradeoff here as in the pr's comments, and what Lawiss said is totally true. Probably add better hint so users know the reason and add a non empty row.

**Comment by xoelop** [comment]
My workaround for this that fixed it for us was casting the array column to a jsonb column in my Postgres view, and then using `JSONExtract` to parse that in ClickHouse.

The column in the Postgres view looks like this
```sql
    , CASE
        WHEN job.commitments IS NOT NULL THEN array_to_json(commitments)::jsonb
        ELSE array_to_json(ARRAY[]::text[])::jsonb
    END AS commitments
```

And then parsing on the CH side looks like this:

```sql
    JSONExtract(coalesce(commitments, '[]'),
                'Array(LowCardinality(String))')::Array(LowCardinality(String)) AS employment_statuses
```

Hope it helps
