### ISSUE TITLE
Incorrect type of `Date` is generated by mysql table function and MySQL database engine for corresponding DATE type of MySQL.

### ISSUE THREAD

**Issue by yakov-olkhovskiy** [ClickHouse/ClickHouse#72619]
**Company or project name**

CH

**Describe what's wrong**

CH mysql engine incorrectly places MySQL `DATE` type into its `Date` type, while it should be `Date32` type. Apparently CH is calculating date based on its interpretation of `Date32` type, where date is number of days around day zero at 1970-01-01 represented by Int32 - i.e. negative values represent dates before day zero. While it seems CH engine correctly calculates negative values, it then generates `Date` type - which is UInt32 (1970-01-01 and above), and puts negative value into this type which results in overflow with some meaningless date (represented by a complement of this negative value)

**Does it reproduce on the most recent release?**

yes

**How to reproduce**

Create table in MySQL containing DATE field, put some dates before 1970-01-01. Then select from this table in CH using `mysql` table function.

**Expected behavior**

CH field type should be `Date32` with correct dates before 1970-01-01

**Comment by zephyx** [comment]
Thx for report.

Additional note: a similar problem occurs with MySQL's DATETIME type, although the results are a little different:

MySQL values: 
INSERT INTO `test` (`date`) VALUES ('1924-01-01');
INSERT INTO `test` (`date`) VALUES ('1900-01-04');
INSERT INTO `test` (`date`) VALUES ('1975-01-04');

=> Results in CH from MySQL "DATE" type: 
2103-06-07 00:00:00
2079-06-10 00:00:00
1975-01-04 00:00:00

=> Results in CH from MySQL "DATETIME" type:
1970-01-01 00:00:00
1970-01-01 00:00:00
1975-01-04 00:00:00

**Comment by yakov-olkhovskiy** [comment]
this feature is already implemented as a setting `mysql_datatypes_support_level='date2Date32'`
