### ISSUE TITLE
 I know that using Nullable type affects performance but couldn't we have just solved it by putting NULL values in the column data file?

### ISSUE THREAD

**Issue by Baitur5** [ClickHouse/ClickHouse#72627]
### Question

What was the reason for storing null masks in separate file and putting default values in column data file. Is it because of the better compression or smth else?

**Comment by UnamedRus** [comment]
> couldn't we have just solved it by putting NULL values in the column data file? 

In that case, column data file for Null columns and non Null will be different. 

So, it will be no that straightforward to convert column to nullable type and back.
But there is multiple ideas of how nullable columns can be improved exist.
