### ISSUE TITLE
Table function nodes or cluster_nodes that queries all the nodes in the cluster

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#7262]
**Use case**

```sql
-- See all nodes in the cluster that are up.
SELECT hostName() from nodes('cluster-name', system.one)

-- Query logs on all nodes.
SELECT ... from nodes('cluster-name', system.query_log) SETTINGS skip_unavailable_shards=1
```

**Describe alternatives you've considered**
Create extra toplogy for `cluster-name` named `cluster-name-nodes` and use `cluster` table function.

**Comment by alexey-milovidov** [comment]
I also have this use case quite frequently. I'd like if it will be named `cluster_all_replicas`.

**Comment by kiransunkari** [comment]
Hi, I want to take this issue.
