### ISSUE TITLE
function fullHostName()

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#7263]
I need a function fullHostName because hostName is unusable for me.
hostName() returns `ch1` for all my hosts because of our naming system (ch1 is a name of LXC container).

**ch1**.host_name1.dc_name1.local
**ch1**.host_name2.dc_name1.local
**ch1**.host_name3.dc_name2.local
**ch1**.host_name4.dc_name2.local

Another option is hostName('full')

**Comment by alexey-milovidov** [comment]
As I understant, the function should return FQDN?

**Comment by alexey-milovidov** [comment]
PS. Separate function name is better than parameter.

**Comment by den-crane** [comment]
> As I understant, the function should return FQDN?

yes

**Comment by alexey-milovidov** [comment]
How to implement:
look at the `dbms/src/Functions/hostName.cpp` and `dbms/src/Common/getFQDNOrHostName.h`.

**Comment by den-crane** [comment]
works 
```

echo 'select  fullHostName()' |clickhouse-benchmark -c100 -i 1000
Loaded 1 queries.

Queries executed: 1000.

localhost:9000, queries 1000, QPS: 13633.102, RPS: 13633.102, MiB/s: 0.013, result RPS: 13633.102, result MiB/s: 0.442.


```
