### ISSUE TITLE
Cannot attach table

### ISSUE THREAD

**Issue by q2515045** [ClickHouse/ClickHouse#72653]
### Company or project name

精友科技

### Question

**我的集群节点服务器需要进行停机。
我先停止了上游写入的flink任务，然后通过命令停止clickhouse服务。
服务器启动后，我使用clickhouse命令启动服务，启动时报如下错误：
My cluster node server needs to be shut down.
I first stopped the Flink task written upstream, and then stopped the Clickhouse service through the command.
After the server started, I used the clickhouse command to start the service, and the following error occurred when starting:**

`2024.11.30 16:47:13.775909 [ 8664 ] {} <Error> Application: Caught exception while loading metadata: Code: 999. Coordination::Exception: Connection loss, path: /clickhouse_news/tables/canal_log/03/replicas/01/flags/force_restore_data: Cannot attach table `dl`.`canal_log` from metadata file /data1/clickhouse/data/store/c5c/c5cf5196-9e11-4bdc-b430-7bcd04a8a425/canal_log.sql from query ATTACH TABLE dl.canal_log UUID '7b865094-fa10-48e0-8f51-f2f658f1233b' (`log` String, `date` Date DEFAULT toDate(now())) ENGINE = ReplicatedMergeTree('/clickhouse_news/tables/canal_log/{shard}', '{replica}') PARTITION BY date ORDER BY date SETTINGS index_granularity = 8192. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) in /usr/bin/clickhouse
2. Coordination::Exception::Exception(Coordination::Error, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in /usr/bin/clickhouse
3. zkutil::ZooKeeper::existsWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) in /usr/bin/clickhouse
4. zkutil::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, DB::StorageReplicatedMergeTree::RenamingRestrictions) in /usr/bin/clickhouse
6. ? in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const in /usr/bin/clickhouse
8. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) in /usr/bin/clickhouse
9. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) in /usr/bin/clickhouse
10. ? in /usr/bin/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) in /usr/bin/clickhouse
12. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
14. ? in /usr/bin/clickhouse
15. start_thread in /usr/lib64/libpthread-2.17.so
16. __clone in /usr/lib64/libc-2.17.so
 (version 22.8.4.7 (official build))`

**我的clickhouse版本：22.8.4.7
我的zookeeper版本：3.4.14
我的集群模式为：3台物理主机，3分片2副本。
我的ck表一共有一百多张。
My clickhouse version: 22.8.4.7
My zookeeper version: 3.4.14
My cluster mode is: 3 physical hosts, 3 shards, and 2 replicas.
I have over a hundred CK watches in total.**

**我编写脚本尝试将无法附加的表全部移动到外部目录，然后启动ck服务。服务启动后我通过ck的sql命令将所有移动后的表元数据进行attach。所有表均被正常附加。并且集群查询表状态正常。
我对服务器上另一个副本执行了同样操作也成功启动。
I wrote a script to try moving all the tables that cannot be attached to an external directory, and then started the ck service. After the service is started, I attach all the moved table metadata using the SQL command 'ck'. All tables are attached normally. And the status of the cluster query table is normal.
I performed the same operation on another replica on the server and successfully started it.**

**我尝试查看clickhouse源代码，发现报错位置只是调用zk的existsWatch方法。这令我困惑，不太确定真实问题是什么，难道是clickhouse与zk的版本不兼容？
I tried to check the clickhouse source code and found that the error location was only when calling zk's existsWatch method. This confuses me and I'm not quite sure what the real problem is. Could it be that Clickhouse is incompatible with the zk version?**

**恳请各位开源大佬解惑，不胜感激。
I sincerely request all open-source experts to clarify their doubts. Thank you very much.**

**完整日志如下：
The complete log is as follows:**

`2024.11.30 16:47:36.024255 [ 8991 ] {} <Information> SentryWriter: Sending crash reports is disabled
2024.11.30 16:47:36.038641 [ 8991 ] {} <Trace> Pipe: Pipe capacity is 1.00 MiB
2024.11.30 16:47:36.142864 [ 8991 ] {} <Information> : Starting ClickHouse 22.8.4.7 with revision 54465, build id: 738D98C9EF0FBCDD, PID 8991
2024.11.30 16:47:36.143014 [ 8991 ] {} <Information> Application: starting up
2024.11.30 16:47:36.143027 [ 8991 ] {} <Information> Application: OS name: Linux, version: 3.10.0-693.el7.x86_64, architecture: x86_64
2024.11.30 16:47:36.153491 [ 8991 ] {} <Warning> Context: Linux transparent hugepages are set to "always". Check /sys/kernel/mm/transparent_hugepage/enabled
2024.11.30 16:47:36.164204 [ 8991 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/thermal
2024.11.30 16:47:36.164251 [ 8991 ] {} <Trace> AsynchronousMetrics: Scanning /sys/block
2024.11.30 16:47:36.164412 [ 8991 ] {} <Trace> AsynchronousMetrics: Scanning /sys/devices/system/edac
2024.11.30 16:47:36.164520 [ 8991 ] {} <Trace> AsynchronousMetrics: Scanning /sys/class/hwmon
2024.11.30 16:47:36.360368 [ 8991 ] {} <Information> Application: Integrity check of the executable successfully passed (checksum: DDB766AE7864510D22E9F432DBC7D99C)
2024.11.30 16:47:36.360400 [ 8991 ] {} <Information> Application: It looks like the process has no CAP_IPC_LOCK capability, binary mlock will be disabled. It could happen due to incorrect ClickHouse package installation. You could resolve the problem manually with 'sudo setcap cap_ipc_lock=+ep /usr/bin/clickhouse'. Note that it will not work on 'nosuid' mounted filesystems.
2024.11.30 16:47:36.360681 [ 8991 ] {} <Debug> Application: rlimit on number of file descriptors is 262144
2024.11.30 16:47:36.360687 [ 8991 ] {} <Debug> Application: Set max number of threads to 2061051 (was 4096).
2024.11.30 16:47:36.360691 [ 8991 ] {} <Debug> Application: Initializing DateLUT.
2024.11.30 16:47:36.360695 [ 8991 ] {} <Trace> Application: Initialized DateLUT with time zone 'Asia/Shanghai'.
2024.11.30 16:47:36.360731 [ 8991 ] {} <Debug> Application: Setting up /var/lib/clickhouse/tmp2/ to store temporary data in it
2024.11.30 16:47:36.379364 [ 8991 ] {} <Debug> Application: Initiailizing interserver credentials.
2024.11.30 16:47:36.379757 [ 8991 ] {} <Information> SensitiveDataMaskerConfigRead: 1 query masking rules loaded.
2024.11.30 16:47:36.383053 [ 8991 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config2.xml'
2024.11.30 16:47:36.392972 [ 8991 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/config2.xml', performing update on configuration
2024.11.30 16:47:36.394785 [ 8991 ] {} <Information> Application: Setting max_server_memory_usage was set to 453.22 GiB (503.57 GiB available * 0.90 max_server_memory_usage_to_ram_ratio)
2024.11.30 16:47:36.398458 [ 8991 ] {} <Information> CertificateReloader: One of paths is empty. Cannot apply new configuration for certificates. Fill all paths and try again.
2024.11.30 16:47:36.398475 [ 8991 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/config2.xml', performed update on configuration
2024.11.30 16:47:36.400729 [ 8991 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
2024.11.30 16:47:36.408764 [ 8991 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/users.xml', performing update on configuration
2024.11.30 16:47:36.409611 [ 8991 ] {} <Debug> ConfigReloader: Loaded config '/etc/clickhouse-server/users.xml', performed update on configuration
2024.11.30 16:47:36.409888 [ 8991 ] {} <Debug> Access(user directories): Added users.xml access storage 'users.xml', path: /etc/clickhouse-server/users.xml
2024.11.30 16:47:36.409975 [ 8991 ] {} <Debug> Access(user directories): Added local directory access storage 'local directory', path: /var/lib/clickhouse/access/
2024.11.30 16:47:36.409996 [ 8991 ] {} <Information> Application: Uncompressed cache policy name 
2024.11.30 16:47:36.411098 [ 8991 ] {} <Information> Context: Initialized background executor for merges and mutations with num_threads=16, num_tasks=32
2024.11.30 16:47:36.412360 [ 8991 ] {} <Information> Context: Initialized background executor for move operations with num_threads=8, num_tasks=8
2024.11.30 16:47:36.412710 [ 8991 ] {} <Information> Context: Initialized background executor for fetches with num_threads=8, num_tasks=8
2024.11.30 16:47:36.414005 [ 8991 ] {} <Information> Context: Initialized background executor for common operations (e.g. clearing old parts) with num_threads=8, num_tasks=8
2024.11.30 16:47:36.414196 [ 8991 ] {} <Information> Application: Loading user defined objects from /data2/clickhouse/data/
2024.11.30 16:47:36.414343 [ 8991 ] {} <Debug> UserDefinedSQLObjectsLoader: Loading user defined objects
2024.11.30 16:47:36.420020 [ 8991 ] {} <Debug> UserDefinedSQLObjectsLoader: Loading user defined object `JSONExtractDateTimeStringOrNull` from file /data2/clickhouse/data/user_defined/function_JSONExtractDateTimeStringOrNull.sql
2024.11.30 16:47:36.430491 [ 8991 ] {} <Debug> UserDefinedSQLObjectsLoader: Loading user defined object `JSONExtractStringOrNull` from file /data2/clickhouse/data/user_defined/function_JSONExtractStringOrNull.sql
2024.11.30 16:47:36.437076 [ 8991 ] {} <Debug> UserDefinedSQLObjectsLoader: Loading user defined object `JSONExtractIntOrNull` from file /data2/clickhouse/data/user_defined/function_JSONExtractIntOrNull.sql
2024.11.30 16:47:36.447322 [ 8991 ] {} <Debug> UserDefinedSQLObjectsLoader: Loading user defined object `JSONExtractFloatOrNull` from file /data2/clickhouse/data/user_defined/function_JSONExtractFloatOrNull.sql
2024.11.30 16:47:36.447825 [ 8991 ] {} <Debug> Application: Loaded user defined objects
2024.11.30 16:47:36.447856 [ 8991 ] {} <Information> Application: Loading metadata from /data2/clickhouse/data/
2024.11.30 16:47:36.538551 [ 8991 ] {} <Information> DatabaseAtomic (system): Metadata processed, database system has 6 tables and 0 dictionaries in total.
2024.11.30 16:47:36.538583 [ 8991 ] {} <Information> TablesLoader: Parsed metadata of 6 tables in 1 databases in 0.04722966 sec
2024.11.30 16:47:36.538619 [ 8991 ] {} <Information> TablesLoader: Loading 6 tables with 0 dependency level
2024.11.30 16:47:36.549814 [ 9045 ] {} <Debug> system.part_log (c90f3f02-7d42-46a9-9305-329fdae0c7e9): Loading data parts
2024.11.30 16:47:36.553242 [ 9047 ] {} <Debug> system.trace_log (af73b8da-0961-41ce-a0b3-971d4fc0d9e7): Loading data parts
2024.11.30 16:47:36.560640 [ 9044 ] {} <Debug> system.asynchronous_metric_log (21612023-73dd-466e-b1c8-0cf699390b94): Loading data parts
2024.11.30 16:47:36.563231 [ 9048 ] {} <Debug> system.query_log (bf800d8f-92d3-4fbb-91f4-232f3f663945): Loading data parts
2024.11.30 16:47:36.567139 [ 9043 ] {} <Debug> system.metric_log (1ccfa0d0-2c55-493d-b61d-f36f4f7ba747): Loading data parts
2024.11.30 16:47:36.589487 [ 9046 ] {} <Debug> system.query_views_log (ca2ab8a0-c7e0-4ac3-bb1b-40d37f1e9065): Loading data parts
2024.11.30 16:47:40.265041 [ 9046 ] {} <Debug> system.query_views_log (ca2ab8a0-c7e0-4ac3-bb1b-40d37f1e9065): Loaded data parts (46 items)
2024.11.30 16:47:40.523787 [ 9047 ] {} <Debug> system.trace_log (af73b8da-0961-41ce-a0b3-971d4fc0d9e7): Loaded data parts (112 items)
2024.11.30 16:47:41.796131 [ 9045 ] {} <Debug> system.part_log (c90f3f02-7d42-46a9-9305-329fdae0c7e9): Loaded data parts (127 items)
2024.11.30 16:47:41.796522 [ 9045 ] {} <Information> TablesLoader: 50%
2024.11.30 16:47:42.204278 [ 9044 ] {} <Debug> system.asynchronous_metric_log (21612023-73dd-466e-b1c8-0cf699390b94): Loaded data parts (105 items)
2024.11.30 16:47:42.374829 [ 9048 ] {} <Debug> system.query_log (bf800d8f-92d3-4fbb-91f4-232f3f663945): Loaded data parts (119 items)
2024.11.30 16:47:43.214921 [ 9043 ] {} <Debug> system.metric_log (1ccfa0d0-2c55-493d-b61d-f36f4f7ba747): Loaded data parts (89 items)
2024.11.30 16:47:43.218834 [ 8991 ] {} <Debug> SystemLog: Not creating system.text_log since corresponding section 'text_log' is missing from config
2024.11.30 16:47:43.221316 [ 8991 ] {} <Debug> SystemLog: Not creating system.filesystem_cache_log since corresponding section 'filesystem_cache_log' is missing from config
2024.11.30 16:47:43.222537 [ 8991 ] {} <Debug> SystemLog: Not creating system.zookeeper_log since corresponding section 'zookeeper_log' is missing from config
2024.11.30 16:47:43.222566 [ 8991 ] {} <Debug> SystemLog: Not creating system.session_log since corresponding section 'session_log' is missing from config
2024.11.30 16:47:43.222581 [ 8991 ] {} <Debug> SystemLog: Not creating system.transactions_info_log since corresponding section 'transactions_info_log' is missing from config
2024.11.30 16:47:43.234889 [ 8991 ] {} <Information> DatabaseCatalog: Found 0 partially dropped tables. Will load them and retry removal.
2024.11.30 16:47:43.404988 [ 8991 ] {} <Trace> PostgreSQLConnectionPool: PostgreSQL connection pool size: 16, connection wait timeout: 5000, max failover tries: 5
2024.11.30 16:47:43.405026 [ 8991 ] {} <Debug> PostgreSQLPoolWithFailover: Adding address host: 192.168.100.58, port: 5432 to connection pool
2024.11.30 16:47:43.405086 [ 8991 ] {} <Information> BackgroundSchedulePool/BgSchPool: Create BackgroundSchedulePool with 128 threads
2024.11.30 16:47:43.426822 [ 8991 ] {} <Information> DatabaseAtomic (default): Metadata processed, database default has 0 tables and 0 dictionaries in total.
2024.11.30 16:47:43.426824 [ 9190 ] {} <Debug> PostgreSQLConnectionPool: New connection to 192.168.100.58:5432
2024.11.30 16:47:43.472466 [ 8991 ] {} <Information> DatabaseAtomic (dl): Metadata processed, database dl has 12 tables and 0 dictionaries in total.
2024.11.30 16:47:43.481951 [ 8991 ] {} <Information> DatabaseAtomic (dm): Metadata processed, database dm has 1 tables and 0 dictionaries in total.
2024.11.30 16:47:43.496261 [ 8991 ] {} <Information> DatabaseAtomic (expertpart_jmsc_ec): Metadata processed, database expertpart_jmsc_ec has 2 tables and 0 dictionaries in total.
2024.11.30 16:47:43.512952 [ 8991 ] {} <Information> DatabaseAtomic (full_vehicle): Metadata processed, database full_vehicle has 3 tables and 0 dictionaries in total.
2024.11.30 16:47:43.527380 [ 8991 ] {} <Information> DatabaseAtomic (jzdj): Metadata processed, database jzdj has 2 tables and 0 dictionaries in total.
2024.11.30 16:47:43.948907 [ 8991 ] {} <Information> DatabaseAtomic (ods): Metadata processed, database ods has 133 tables and 0 dictionaries in total.
2024.11.30 16:47:43.999663 [ 8991 ] {} <Information> DatabaseAtomic (online_facade): Metadata processed, database online_facade has 13 tables and 0 dictionaries in total.
2024.11.30 16:47:44.019583 [ 8991 ] {} <Information> DatabaseAtomic (persistence_dwh): Metadata processed, database persistence_dwh has 3 tables and 0 dictionaries in total.
2024.11.30 16:47:44.050047 [ 8991 ] {} <Information> DatabaseAtomic (timely_update_price): Metadata processed, database timely_update_price has 8 tables and 0 dictionaries in total.
2024.11.30 16:47:44.050105 [ 8991 ] {} <Information> TablesLoader: Parsed metadata of 177 tables in 10 databases in 0.623347766 sec
2024.11.30 16:47:44.050152 [ 8991 ] {} <Information> TablesLoader: Loading 177 tables with 0 dependency level
2024.11.30 16:47:50.725226 [ 9179 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 8
2024.11.30 16:47:50.729175 [ 9179 ] {} <Debug> SystemLog (system.metric_log): Will use existing table system.metric_log for MetricLog
2024.11.30 16:47:50.742318 [ 9179 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 1.91 TiB.
2024.11.30 16:47:50.762901 [ 9179 ] {} <Trace> MergedBlockOutputStream: filled checksums 202411_1_1_0 (state Temporary)
2024.11.30 16:47:50.764374 [ 9179 ] {} <Trace> system.metric_log (1ccfa0d0-2c55-493d-b61d-f36f4f7ba747): Renaming temporary part tmp_insert_202411_1_1_0 to 202411_9168278_9168278_0.
2024.11.30 16:47:50.766289 [ 9179 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 8
2024.11.30 16:47:54.070836 [ 9213 ] {} <Trace> ZooKeeperClient: Failed to get API version: timeout
2024.11.30 16:47:54.070882 [ 9213 ] {} <Trace> ZooKeeper: Initialized, hosts: bigdata1:2181,sdw1:2181,sdw2:2181
2024.11.30 16:47:58.266536 [ 9179 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 8 entries to flush up to offset 16
2024.11.30 16:47:58.279862 [ 9179 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 1.91 TiB.
2024.11.30 16:47:58.293693 [ 9179 ] {} <Trace> MergedBlockOutputStream: filled checksums 202411_2_2_0 (state Temporary)
2024.11.30 16:47:58.294457 [ 9179 ] {} <Trace> system.metric_log (1ccfa0d0-2c55-493d-b61d-f36f4f7ba747): Renaming temporary part tmp_insert_202411_2_2_0 to 202411_9168279_9168279_0.
2024.11.30 16:47:58.296319 [ 9179 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 16
2024.11.30 16:48:04.071874 [ 9219 ] {} <Error> ZooKeeperClient: Code: 999. Coordination::Exception: Operation timeout (deadline already expired) for path: /keeper/api_version (Operation timeout). (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) in /usr/bin/clickhouse
2. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error) in /usr/bin/clickhouse
3. Coordination::ZooKeeper::receiveThread() in /usr/bin/clickhouse
4. ? in /usr/bin/clickhouse
5. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
6. ? in /usr/bin/clickhouse
7. start_thread in /usr/lib64/libpthread-2.17.so
8. __clone in /usr/lib64/libc-2.17.so
 (version 22.8.4.7 (official build))
2024.11.30 16:48:04.090048 [ 8991 ] {} <Error> Application: Caught exception while loading metadata: Code: 999. Coordination::Exception: Operation timeout, path: /clickhouse_news/tables/dl_lp_loss_cars_log/02/replicas/02/flags/force_restore_data: Cannot attach table `dl`.`dl_lp_loss_cars_log_bak` from metadata file /data2/clickhouse/data/store/c5c/c5cf5196-9e11-4bdc-b430-7bcd04a8a425/dl_lp_loss_cars_log_bak.sql from query ATTACH TABLE dl.dl_lp_loss_cars_log_bak UUID 'e0886ffa-9182-4a41-9dcf-30a437ae2dfc' (`topic` String, `database_name` String, `table_name` String, `pk_json` String, `op` String, `ts` UInt64, `data_json` String, `sys_time` DateTime DEFAULT now(), `ver` UInt64 DEFAULT ts, `date` Date DEFAULT toDate(sys_time)) ENGINE = ReplicatedReplacingMergeTree('/clickhouse_news/tables/dl_lp_loss_cars_log/{shard}', '{replica}') PARTITION BY toYYYYMM(date) ORDER BY (table_name, topic, database_name, pk_json) SETTINGS index_granularity = 8192. (KEEPER_EXCEPTION), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) in /usr/bin/clickhouse
1. Coordination::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Error, int) in /usr/bin/clickhouse
2. Coordination::Exception::Exception(Coordination::Error, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in /usr/bin/clickhouse
3. zkutil::ZooKeeper::existsWatch(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::function<void (Coordination::WatchResponse const&)>) in /usr/bin/clickhouse
4. zkutil::ZooKeeper::exists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Coordination::Stat*, std::__1::shared_ptr<Poco::Event> const&) in /usr/bin/clickhouse
5. DB::StorageReplicatedMergeTree::StorageReplicatedMergeTree(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, DB::StorageID const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::StorageInMemoryMetadata const&, std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::MergeTreeData::MergingParams const&, std::__1::unique_ptr<DB::MergeTreeSettings, std::__1::default_delete<DB::MergeTreeSettings> >, bool, DB::StorageReplicatedMergeTree::RenamingRestrictions) in /usr/bin/clickhouse
6. ? in /usr/bin/clickhouse
7. DB::StorageFactory::get(DB::ASTCreateQuery const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, std::__1::shared_ptr<DB::Context>, DB::ColumnsDescription const&, DB::ConstraintsDescription const&, bool) const in /usr/bin/clickhouse
8. DB::createTableFromAST(DB::ASTCreateQuery, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool) in /usr/bin/clickhouse
9. DB::DatabaseOrdinary::loadTableFromMetadata(std::__1::shared_ptr<DB::Context>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::QualifiedTableName const&, std::__1::shared_ptr<DB::IAST> const&, DB::LoadingStrictnessLevel) in /usr/bin/clickhouse
10. ? in /usr/bin/clickhouse
11. ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>) in /usr/bin/clickhouse
12. void std::__1::__function::__policy_invoker<void ()>::__call_impl<std::__1::__function::__default_alloc_func<ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda0'()>(void&&)::'lambda'(), void ()> >(std::__1::__function::__policy_storage const*) in /usr/bin/clickhouse
13. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) in /usr/bin/clickhouse
14. ? in /usr/bin/clickhouse
15. start_thread in /usr/lib64/libpthread-2.17.so
16. __clone in /usr/lib64/libc-2.17.so
 (version 22.8.4.7 (official build))
2024.11.30 16:48:04.090155 [ 8991 ] {} <Information> Application: Shutting down storages.
2024.11.30 16:48:04.090172 [ 8991 ] {} <Information> Context: Shutdown disk default
2024.11.30 16:48:04.090446 [ 9184 ] {} <Trace> SystemLog (system.query_log): Terminating
2024.11.30 16:48:04.090520 [ 9174 ] {} <Trace> SystemLog (system.query_thread_log): Terminating
2024.11.30 16:48:04.090563 [ 9182 ] {} <Trace> SystemLog (system.part_log): Terminating
2024.11.30 16:48:04.090686 [ 9175 ] {} <Trace> SystemLog (system.trace_log): Terminating
2024.11.30 16:48:04.090788 [ 9189 ] {} <Trace> SystemLog (system.crash_log): Terminating
2024.11.30 16:48:04.223504 [ 9179 ] {} <Trace> SystemLog (system.metric_log): Flushing system log, 5 entries to flush up to offset 21
2024.11.30 16:48:04.238085 [ 9179 ] {} <Debug> DiskLocal: Reserving 1.00 MiB on disk `default`, having unreserved 1.91 TiB.
2024.11.30 16:48:04.240804 [ 9179 ] {} <Trace> MergedBlockOutputStream: filled checksums 202411_3_3_0 (state Temporary)
2024.11.30 16:48:04.241924 [ 9179 ] {} <Trace> system.metric_log (1ccfa0d0-2c55-493d-b61d-f36f4f7ba747): Renaming temporary part tmp_insert_202411_3_3_0 to 202411_9168280_9168280_0.
2024.11.30 16:48:04.242950 [ 9179 ] {} <Trace> SystemLog (system.metric_log): Flushed system log up to offset 21
2024.11.30 16:48:04.242967 [ 9179 ] {} <Trace> SystemLog (system.metric_log): Terminating
2024.11.30 16:48:04.243047 [ 9170 ] {} <Trace> SystemLog (system.asynchronous_metric_log): Terminating
2024.11.30 16:48:04.243160 [ 9176 ] {} <Trace> SystemLog (system.opentelemetry_span_log): Terminating
2024.11.30 16:48:04.243255 [ 9180 ] {} <Trace> SystemLog (system.query_views_log): Terminating
2024.11.30 16:48:04.243356 [ 9185 ] {} <Trace> SystemLog (system.processors_profile_log): Terminating
2024.11.30 16:48:04.243629 [ 8991 ] {} <Debug> StorageDistributed (dl_rs_log_distributed): Joining background threads for async INSERT
2024.11.30 16:48:04.243662 [ 8991 ] {} <Debug> StorageDistributed (dl_rs_log_distributed): Background threads for async INSERT joined
2024.11.30 16:48:04.298091 [ 8991 ] {} <Trace> BackgroundSchedulePool/BgSchPool: Waiting for threads to finish.
2024.11.30 16:48:04.299488 [ 8991 ] {} <Debug> MemoryTracker: Peak memory usage (for query): 11.24 KiB.
2024.11.30 16:48:04.299597 [ 8991 ] {} <Debug> Application: Shut down storages.
2024.11.30 16:48:04.452225 [ 8991 ] {} <Debug> Application: Destroyed global context.
2024.11.30 16:48:04.460147 [ 8991 ] {} <Error> Application: Coordination::Exception: Operation timeout, path: /clickhouse_news/tables/dl_lp_loss_cars_log/02/replicas/02/flags/force_restore_data: Cannot attach table `dl`.`dl_lp_loss_cars_log_bak` from metadata file /data2/clickhouse/data/store/c5c/c5cf5196-9e11-4bdc-b430-7bcd04a8a425/dl_lp_loss_cars_log_bak.sql from query ATTACH TABLE dl.dl_lp_loss_cars_log_bak UUID 'e0886ffa-9182-4a41-9dcf-30a437ae2dfc' (`topic` String, `database_name` String, `table_name` String, `pk_json` String, `op` String, `ts` UInt64, `data_json` String, `sys_time` DateTime DEFAULT now(), `ver` UInt64 DEFAULT ts, `date` Date DEFAULT toDate(sys_time)) ENGINE = ReplicatedReplacingMergeTree('/clickhouse_news/tables/dl_lp_loss_cars_log/{shard}', '{replica}') PARTITION BY toYYYYMM(date) ORDER BY (table_name, topic, database_name, pk_json) SETTINGS index_granularity = 8192
2024.11.30 16:48:04.460209 [ 8991 ] {} <Information> Application: shutting down
2024.11.30 16:48:04.460221 [ 8991 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2024.11.30 16:48:04.460388 [ 8993 ] {} <Trace> BaseDaemon: Received signal -2
2024.11.30 16:48:04.460444 [ 8993 ] {} <Information> BaseDaemon: Stop SignalListener thread`

**Comment by sunny19930321** [comment]
Coordination::Exception: Connection loss ，make sure zookeeper is working？

**Comment by Algunenano** [comment]
Please update to a supported release

**Comment by q2515045** [comment]
> Please update to a supported release

谢谢，我会在合适的时间进行生产升级的，在这之前老版本还得支持运行一段时间。
Thank you, I will carry out the production upgrade at an appropriate time. Before that, the old version still needs to support running for a period of time.
