### ISSUE TITLE
24.11 toJSONString function is not full json string

### ISSUE THREAD

**Issue by huuns** [ClickHouse/ClickHouse#72667]
### Question

If toJSONString(tuple(node_id, data)) previously output something like:

{"node_id": 1, "data": ["tuple": 2]}
In version 2424.11, it now outputs:
[1, ["tuple", 2]]
This change indicates that the JSON serialization format for tuple in ClickHouse has been modified, resulting in a different structure when converting tuple to JSON.

**Comment by Algunenano** [comment]
This is the traditional output of tuples vs named tuples. For a few minor releases `tuple` starting generating named tuples instead of unnamed tuples and it changed how they are output. If you want a named tuple you can either create it or enable `enable_named_columns_in_function_tuple`
