### ISSUE TITLE
Support LIKE operator for Enum data type

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#72661]
**Use case**

LIKE/ILIKE should work no matter what data type is in the column.

**Describe the solution you'd like**

LIKE will search in string representation of Enum data type values.

Basically `enum_column::String LIKE '%abc%'` works and `enum_column LIKE '%abc%'` does not.

**Comment by zhanglistar** [comment]
I see, that's sounds reasonable.

**Comment by zhanglistar** [comment]
Then, should all string functions need to be smarter?

**Comment by geldot** [comment]
Applies equally to regex `match()`, likely other/all string matching functions

**Comment by zhanglistar** [comment]
@qoega Pls check this.
