### ISSUE TITLE
Is the ANY INNER JOIN feature disabled?

### ISSUE THREAD

**Issue by kratorman** [ClickHouse/ClickHouse#7276]
In changelog 19.14.3.3 written:
Disable ANY RIGHT JOIN and ANY FULL JOIN by default.

In fact, ANY INNER JOIN does not work either.

In code written:
if (table_join.kind != ASTTableJoin::Kind::Left) throw Exception
https://github.com/ClickHouse/ClickHouse/pull/6351/files

Wrong code or changelog?

**Comment by 4ertus2** [comment]
Code is correct. It's under the setting too. We are going to implement ANY INNER JOIN that means 'distinct keys for both sides'. Current ANY INNER JOIN could return duplicates from left table. That leads to inconsistency of ```t1 ANY INNER JOIN t2``` and ```t2 ANY INNER JOIN t1```. We'll need this consistency to implement JOIN optimizers. So only ANY LEFT JOIN is fully correct now. The others would change behaviour.

Related #5126

**Comment by blinkov** [comment]
@kratorman do you have any further questions?
