### ISSUE TITLE
clickhouse server become unresponsive 

### ISSUE THREAD

**Issue by mayankkandari** [ClickHouse/ClickHouse#72824]
### Company or project name

CIENA 

### Question

Hi, we are facing an issue with one of the clickhouse deployments where the clickhouse-server becomes unresponsive frequently.
 It's a 3-node cluster, and the engine ReplicatedReplacingMergeTree is used for all the tables. Clickhouse is running inside a Docker container. When Clickhouse is unresponsive, the CPU load average on the host goes high(> 100). 

Kill command doesn't work (even -9) and after restarting the docker also server remains unresponsive.

What log/info would be required to debug this problem?

max_thread_pool_size is 1000 and clickhouse-server version is 22.8. 
We do bulk write and max rows in a bulk write could be up to 100k.  

This is the file of stace info for docker instance 
[strace_849730.log](https://github.com/user-attachments/files/18017758/strace_849730.log)

**Comment by Algunenano** [comment]
Please upgrade to a [supported release](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#security-change-log-and-support).
