### ISSUE TITLE
The kafka engine has default values and the upgrade service cannot start

### ISSUE THREAD

**Issue by sunny19930321** [ClickHouse/ClickHouse#72821]
**Company or project name**

Tencent

**Describe what's wrong**

the kafka engine has default values and the upgrade service cannot start,It seems that this PR(https://github.com/ClickHouse/ClickHouse/pull/47138) introduced the problem

**Does it reproduce on the most recent release?**

23.8.9.1

**How to reproduce**

22.8 upgraded to 23.8

**Expected behavior**

The upgrade service starts normally

**Error message and/or stacktrace**

Application: Code: 36. DB::Exception: KafkaEngine doesn't support DEFAULT/MATERIALIZED/EPHEMERAL expressions for columns. See https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka/#configuration: Cannot attach table `tota`.`kafka_device_log_check_params` from metadata file /data/clickhouse/clickhouse-server/store/e26/e2688711-6284-4792-9fbc-766f65c29db9/kafka_device_log_check_params.sql from query ATTACH TABLE tota.kafka_device_log_check_params UUID 'd2d84599-4429-400b-8cef-ec590be54059' (`domain_code` String, `product_id` Int64, `sub_product_id` Int64, `device_id` String, `cmd_id` String, `is_test` Int8, `part_id` Int64, `chip_model_id` Int64, `client_time` DateTime, `server_time` DateTime, `create_time` DateTime DEFAULT now()) ENGINE = Kafka SETTINGS kafka_broker_list = '10.0.0.17:9092,10.0.0.8:9092,10.0.0.6:9092', kafka_topic_list = 'deviceLogCheckParamsCHTopic', kafka_group_name = 'iotClickhouseGroup', kafka_format = 'JSONEachRow', kafka_num_consumers = 2. (BAD_ARGUMENTS), Stack trace (when copying this message, always include the lines below):

**Comment by rschu1ze** [comment]
Both upgraded-from and upgraded-to versions are out of the maintenance window. If you drop the Kafka tables before the upgrade, and re-create it after upgrade, I think the upgrade will work.

**Comment by sunny19930321** [comment]
> Both upgraded-from and upgraded-to versions are out of the maintenance window. If you drop the Kafka tables before the upgrade, and re-create it after upgrade, I think the upgrade will work.

I think adding a configuration is compatible
