### ISSUE TITLE
What does RealTimeMicroseconds have to do with query_duration_ms

### ISSUE THREAD

**Issue by zhanyirong** [ClickHouse/ClickHouse#72843]
### Question

RealTimeMicroseconds includes a summary of what time, why some queries query_duration_ms are similar, RealTimeMicroseconds is much different, what is the conversion formula

**Comment by Algunenano** [comment]
Total (wall clock) time spent in processing threads (note that this is a sum). If there are 16 threads processing a query, this might be 16x higher than `query_duration_ms` (*1000 for ms to microseconds)

**Comment by zhanyirong** [comment]
Are you talking about max_threads in the Settings of the system.query_log table? I finished dividing the max_threads, but it is still several times higher than the query_duration_ms

**Comment by zhanyirong** [comment]
> Total (wall clock) time spent in processing threads (note that this is a sum). If there are 16 threads processing a query, this might be 16x higher than `query_duration_ms` (*1000 for ms to microseconds)


Are you talking about max_threads in the Settings of the system.query_log table? I finished dividing the max_threads, but it is still several times higher than the query_duration_ms(*1000 for ms to microseconds)

**Comment by nickitat** [comment]
There are also threads from thread pools

**Comment by zhanyirong** [comment]
> There are also threads from thread pools

How can you see the specific results of the execution of threads in these thread pools
