### ISSUE TITLE
"Tagging already tagged part" 

### ISSUE THREAD

**Issue by tmartin-gh** [ClickHouse/ClickHouse#7287]
I'm consistently seeing this error message from clickhouse server:
```
<Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 49, e.displayText() = DB::Exception: Tagging already tagged part 20191011-4_1_32_2. This is a bug., Stack trace:
// 
// 0. 0x55e728cdde90 StackTrace::StackTrace() /home/phage/vendor/ClickHouse/build/../dbms/src/Common/StackTrace.cpp:228
// 1. 0x55e728cddc65 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /home/phage/vendor/ClickHouse/build/../dbms/src/Common/Exception.h:27
// 2. 0x55e72c123567 DB::CurrentlyMergingPartsTagger::CurrentlyMergingPartsTagger(DB::FutureMergedMutatedPart const&, unsigned long, DB::StorageMergeTree&, bool) /usr/include/c++/9/bits/basic_string.h:222
// 3. 0x55e72c113eb8 DB::StorageMergeTree::merge(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:778
// 4. 0x55e72c119074 DB::StorageMergeTree::mergeMutateTask() /usr/include/c++/9/bits/basic_string.h:222
// 5. 0x55e72c1abf94 DB::BackgroundProcessingPool::threadFunction() /usr/include/c++/9/bits/std_function.h:690
// 6. 0x55e72c1ac90a ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::{lambda()#1}>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::{lambda()#1}&&)::{lambda()#1}::operator()() const /home/phage/vendor/ClickHouse/build/../dbms/src/Common/ThreadPool.h:150
// 7. 0x55e728d269dc ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/include/c++/9/bits/atomic_base.h:551
// 8. 0x55e72d7fce00 execute_native_thread_routine /home/phage/vendor/ClickHouse/build/dbms/programs/clickhouse
// 9. 0x7f90fa33d6db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
// 10. 0x7f90f9e6288f clone /lib/x86_64-linux-gnu/libc-2.27.so
// (version 19.16.1.1)
```

I can reproduce it when doing a high rate of multi-row inserts using the clickhouse-cpp library.  I've separated out the chunk of code causing this so I can post it.

Full CREATE TABLE statement is in the code attachment.  It involves the MergeTree engine and the table TTL feature.  Basic format is:
```
create table if not exists spam(
      date Date DEFAULT today(),
      datetime DateTime DEFAULT now(),
... bunch of other columns ...
   ENGINE = MergeTree() 
   PARTITION BY (toYYYYMMDD(date),toHour(datetime)) 
   ORDER BY datetime 
   TTL datetime + interval 1 minute 
   SETTINGS merge_with_ttl_timeout=60");
```

For the purpose of duplicating the bug, I made the TTL `datetime + interval 1 minute` and `merge_with_ttl_timeout=60`, but it happens if I use longer intervals (just takes longer to reproduce). 

The basic functionality/goal I'm after is writing ~5Gbps of this table data to the database and TTL-ing it out after a few days (e.g. TTL datetime + interval 3 days).  Partitioning by hour is useful based on the queries we expect.  In the production system, we have a lot of flexibility to batch up rows before inserting them.  We can do many rows in one big insert, or have multiple separate client processes doing smaller inserts.

I'm using the same version of client and server.  Compiling from github sources on ubuntu 18.04 using GCC 9.

**Comment by tmartin-gh** [comment]
Attaching example program that can reproduce the issue

//
// Test program to replicate
// <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 49, e.displayText() = DB::Exception: Tagging already tagged part 20191011-4_1_32_2. This is a bug., Stack trace:
// 
// 0. 0x55e728cdde90 StackTrace::StackTrace() /home/phage/vendor/ClickHouse/build/../dbms/src/Common/StackTrace.cpp:228
// 1. 0x55e728cddc65 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /home/phage/vendor/ClickHouse/build/../dbms/src/Common/Exception.h:27
// 2. 0x55e72c123567 DB::CurrentlyMergingPartsTagger::CurrentlyMergingPartsTagger(DB::FutureMergedMutatedPart const&, unsigned long, DB::StorageMergeTree&, bool) /usr/include/c++/9/bits/basic_string.h:222
// 3. 0x55e72c113eb8 DB::StorageMergeTree::merge(bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:778
// 4. 0x55e72c119074 DB::StorageMergeTree::mergeMutateTask() /usr/include/c++/9/bits/basic_string.h:222
// 5. 0x55e72c1abf94 DB::BackgroundProcessingPool::threadFunction() /usr/include/c++/9/bits/std_function.h:690
// 6. 0x55e72c1ac90a ThreadFromGlobalPool::ThreadFromGlobalPool<DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::{lambda()#1}>(DB::BackgroundProcessingPool::BackgroundProcessingPool(int)::{lambda()#1}&&)::{lambda()#1}::operator()() const /home/phage/vendor/ClickHouse/build/../dbms/src/Common/ThreadPool.h:150
// 7. 0x55e728d269dc ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/include/c++/9/bits/atomic_base.h:551
// 8. 0x55e72d7fce00 execute_native_thread_routine /home/phage/vendor/ClickHouse/build/dbms/programs/clickhouse
// 9. 0x7f90fa33d6db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
// 10. 0x7f90f9e6288f clone /lib/x86_64-linux-gnu/libc-2.27.so
// (version 19.16.1.1)
//
// Compiled as follows: (TODO FIXME there's way too much unnecessary stuff here, clean this up ...)
/*
   /usr/bin/g++-9 -Wall -Wextra -Wl,-rpath,../../../vendor/clickhouse-cpp/build/clickhouse/ \
       -Wpointer-arith -Wcast-align -Wwrite-strings -Wstrict-overflow=5 -Wcast-qual -Wconversion-null \
       -Wunreachable-code -Winit-self -Wpointer-arith -Wreturn-type -Wparentheses -Wunused-function \
       -Wunused-value -Wunused-variable -Wnon-virtual-dtor  -DBOOST_SYSTEM_NO_DEPRECATED -DUNALIGNED_OK \
       -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -fdiagnostics-color=always -pipe -msse4.1 -msse4.2 -mpopcnt \
       -fno-omit-frame-pointer -no-pie -O3 -fno-tree-loop-distribute-patterns -pthread -std=c++1z \
       -Iinc/ -I../../../vendor/clickhouse-cpp/ -o bug_test.o -c bug_test.cpp

   /usr/bin/g++-9 -Wall -Wextra -Wl,-rpath,../../../vendor/clickhouse-cpp/build/clickhouse/ \
      -Wpointer-arith -Wcast-align -Wwrite-strings -Wstrict-overflow=5 -Wcast-qual -Wconversion-null \
      -Wunreachable-code -Winit-self -Wpointer-arith -Wreturn-type -Wparentheses -Wunused-function \
      -Wunused-value -Wunused-variable -Wnon-virtual-dtor  -DBOOST_SYSTEM_NO_DEPRECATED -DUNALIGNED_OK \
      -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -fdiagnostics-color=always -pipe -msse4.1 -msse4.2 -mpopcnt \
      -fno-omit-frame-pointer -no-pie -O3 -fno-tree-loop-distribute-patterns -pthread -std=c++1z \
      -L../../../vendor/clickhouse-cpp/build/clickhouse/ bug_test.o -lclickhouse-cpp-lib -o bug_test


Run these queries to check TTL is working:
select datetime, count(1) from spam group by datetime order by datetime

select table,partition,name,marks,rows,data_uncompressed_bytes,bytes_on_disk,min_time,max_time,remove_time \
    from system.parts where active and table='spam' order by min_time

Sometimes doing an optimize can cause the bug to happen sooner, but it will happen eventually just with merging
optimize table spam final

*/ 

#include <unistd.h>
#include <clickhouse/client.h>

constexpr uint64_t NUM_ROWS_PER_INSERT = 8000000;
constexpr float SLEEP_BETWEEN_INSERTS_SECONDS = 10.;

int main(void)
{
	clickhouse::Client client(clickhouse::ClientOptions().SetHost("localhost"));
	client.Execute("create table if not exists spam(\
                          date Date DEFAULT today(),\
                          datetime DateTime DEFAULT now(),\
							x1 UInt64 , \
							x2 Int32, \
							x3 UInt64, \
							x4 UInt8, \
							x5 UInt8, \
							x6 UInt16, \
							x7 UInt32, \
							x8 UInt8, \
							x9 UInt8, \
							x10 UInt8, \
							x11 UInt8, \
							x12 UInt8, \
							x13 UInt8, \
							x14 UInt8, \
							x15 UInt8, \
							x16 UInt8, \
							x17 UInt8, \
							x18 UInt8, \
							x19 UInt8, \
							x20 UInt8, \
							x21 UInt8, \
							x22 Int32, \
							x23 Int32, \
							x24 Int16, \
							x25 Int16, \
							x26 Int16, \
							x27 Int16, \
                            x28 UInt64, \
							x29 UInt64) \
					   ENGINE = MergeTree() \
					   PARTITION BY (toYYYYMMDD(date),toHour(datetime)) \
					   ORDER BY datetime \
					   TTL datetime + interval 1 minute \
					   SETTINGS merge_with_ttl_timeout=60");

	for(uint64_t i = 0; i < 100; ++i) {
		clickhouse::Block block;
        auto x1 = std::make_shared<clickhouse::ColumnUInt64>();
        auto x2 = std::make_shared<clickhouse::ColumnInt32>();
        auto x3 = std::make_shared<clickhouse::ColumnUInt64>();
        auto x4 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x5 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x6 = std::make_shared<clickhouse::ColumnUInt16>();
        auto x7 = std::make_shared<clickhouse::ColumnUInt32>();
        auto x8 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x9 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x10 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x11 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x12 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x13 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x14 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x15 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x16 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x17 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x18 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x19 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x20 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x21 = std::make_shared<clickhouse::ColumnUInt8>();
        auto x22 = std::make_shared<clickhouse::ColumnInt32>();
        auto x23 = std::make_shared<clickhouse::ColumnInt32>();
        auto x24 = std::make_shared<clickhouse::ColumnInt16>();
        auto x25 = std::make_shared<clickhouse::ColumnInt16>();
        auto x26 = std::make_shared<clickhouse::ColumnInt16>();
        auto x27 = std::make_shared<clickhouse::ColumnInt16>();
        auto x28 = std::make_shared<clickhouse::ColumnUInt64>();
        auto x29 = std::make_shared<clickhouse::ColumnUInt64>();
        for (uint64_t k=0; k<NUM_ROWS_PER_INSERT; k++)
        {
            x1->Append(i*NUM_ROWS_PER_INSERT+k);
            x2->Append(i*NUM_ROWS_PER_INSERT+k);
            x3->Append(i*NUM_ROWS_PER_INSERT+k);
            x4->Append(i*NUM_ROWS_PER_INSERT+k);
            x5->Append(i*NUM_ROWS_PER_INSERT+k);
            x6->Append(i*NUM_ROWS_PER_INSERT+k);
            x7->Append(i*NUM_ROWS_PER_INSERT+k);
            x8->Append(i*NUM_ROWS_PER_INSERT+k);
            x9->Append(i*NUM_ROWS_PER_INSERT+k);
            x10->Append(i*NUM_ROWS_PER_INSERT+k);
            x11->Append(i*NUM_ROWS_PER_INSERT+k);
            x12->Append(i*NUM_ROWS_PER_INSERT+k);
            x13->Append(i*NUM_ROWS_PER_INSERT+k);
            x14->Append(i*NUM_ROWS_PER_INSERT+k);
            x15->Append(i*NUM_ROWS_PER_INSERT+k);
            x16->Append(i*NUM_ROWS_PER_INSERT+k);
            x17->Append(i*NUM_ROWS_PER_INSERT+k);
            x18->Append(i*NUM_ROWS_PER_INSERT+k);
            x19->Append(i*NUM_ROWS_PER_INSERT+k);
            x20->Append(i*NUM_ROWS_PER_INSERT+k);
            x21->Append(i*NUM_ROWS_PER_INSERT+k);
            x22->Append(i*NUM_ROWS_PER_INSERT+k);
            x23->Append(i*NUM_ROWS_PER_INSERT+k);
            x24->Append(i*NUM_ROWS_PER_INSERT+k);
            x25->Append(i*NUM_ROWS_PER_INSERT+k);
            x26->Append(i*NUM_ROWS_PER_INSERT+k);
            x27->Append(i*NUM_ROWS_PER_INSERT+k);
            x28->Append(i*NUM_ROWS_PER_INSERT+k);
            x29->Append(i*NUM_ROWS_PER_INSERT+k);
        }
        block.AppendColumn("x1", x1);
        block.AppendColumn("x2", x2);
        block.AppendColumn("x3", x3);
        block.AppendColumn("x4", x4);
        block.AppendColumn("x5", x5);
        block.AppendColumn("x6", x6);
        block.AppendColumn("x7", x7);
        block.AppendColumn("x8", x8);
        block.AppendColumn("x9", x9);
        block.AppendColumn("x10", x10);
        block.AppendColumn("x11", x11);
        block.AppendColumn("x12", x12);
        block.AppendColumn("x13", x13);
        block.AppendColumn("x14", x14);
        block.AppendColumn("x15", x15);
        block.AppendColumn("x16", x16);
        block.AppendColumn("x17", x17);
        block.AppendColumn("x18", x18);
        block.AppendColumn("x19", x19);
        block.AppendColumn("x20", x20);
        block.AppendColumn("x21", x21);
        block.AppendColumn("x22", x22);
        block.AppendColumn("x23", x23);
        block.AppendColumn("x24", x24);
        block.AppendColumn("x25", x25);
        block.AppendColumn("x26", x26);
        block.AppendColumn("x27", x27);
        block.AppendColumn("x28", x28);
        block.AppendColumn("x29", x29);
        client.Insert("spam", block);
		usleep(1000000.*SLEEP_BETWEEN_INSERTS_SECONDS);
	}
}

**Comment by doom369** [comment]
Same issue here:

```
2020.05.01 02:17:04.277285 [ 30977 ] {} <Error> void DB::BackgroundProcessingPool::threadFunction(): Code: 49, e.displayText() = DB::Exception: Tagging already tagged part 202004_297671_316874_302_339568. This i
s a bug., Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x10278d1c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x8f02989 in /usr/bin/clickhouse
2. DB::CurrentlyMergingPartsTagger::CurrentlyMergingPartsTagger(DB::FutureMergedMutatedPart&, unsigned long, DB::StorageMergeTree&, bool) @ 0xd53c3e5 in /usr/bin/clickhouse
3. DB::StorageMergeTree::merge(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::
allocator<char> >*) @ 0xd52c940 in /usr/bin/clickhouse
4. DB::StorageMergeTree::mergeMutateTask() @ 0xd5338ec in /usr/bin/clickhouse
5. DB::BackgroundProcessingPool::threadFunction() @ 0xd69c1ab in /usr/bin/clickhouse
6. ? @ 0xd69cb70 in /usr/bin/clickhouse
7. ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>) @ 0x8f25b07 in /usr/bin/clickhouse
8. ? @ 0x8f2400f in /usr/bin/clickhouse
9. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
10. clone @ 0x12188f in /lib/x86_64-linux-gnu/libc-2.27.so
 (version 20.3.2.1 (official build))

```

**Comment by alexey-milovidov** [comment]
Most likely fixed by https://github.com/ClickHouse/ClickHouse/pull/14444
