### ISSUE TITLE
formatDateTime %f inconsistent depending on scale/precision

### ISSUE THREAD

**Issue by dcheckoway** [ClickHouse/ClickHouse#72879]
**Company or project name**

Cribl

**Describe what's wrong**

When using `formatDateTime()`, the `%f` format doesn't conform to MySQL's definition.  It's supposed to be "Microseconds (000000..999999)" but the length seems to vary based on the scale/precision of the DateTime.

Easily reproduced:
https://fiddle.clickhouse.com/d17eb9b5-6cb0-4a7b-81c1-8163c799761c

**Does it reproduce on the most recent release?**

Yes

**How to reproduce**

Doesn't matter which server version/interface/settings.  See the Fiddle link above, or just run:

```sql
select
    formatDateTime(toDateTime64(now(), 2), '%f'),
    formatDateTime(toDateTime64(now(), 3), '%f'),
    formatDateTime(toDateTime64(now(), 4), '%f'),
    formatDateTime(now(), '%f')
```

**Expected behavior**

I'd expect 6 digits every time irrespective of the date's precision.  i.e. `000000` just as MySQL documented it.

**Comment by ollidraese** [comment]
Created a PR for this issue here: https://github.com/ClickHouse/ClickHouse/pull/73324
