### ISSUE TITLE
Add query setting that allows to override content-type

### ISSUE THREAD

**Issue by socketpair** [ClickHouse/ClickHouse#72873]
In my case, I use `FORMAT CustomSeparated`, while accessing CH by HTTP. `Content-Type` is returned as `text/plain; charset=UTF-8`. I need to set my own. It's important because the application that issues the HTTP request considers content-type. I would like to have something like `settings http_content_type='...'`

CH already has some header-related settings 
`select name from system.settings where name like '%http%'` but nothing can be used for that.

Or, possibly, some general way to tune any HTTP headers in output, with ability to override even auto-generated, or to remove some. Actually, I don't need this, but I think it would be nice to have such function.

**Comment by UnamedRus** [comment]
PR to implement header override https://github.com/ClickHouse/ClickHouse/pull/72656

**Comment by socketpair** [comment]
I had this problem for a ages!  Decided to report only today. But it was fixed 5 days before this issue! Unbelievable!
