### ISSUE TITLE
Add support for disabling checksumming of blocks over the TCP protocol (distributed / remote tables)

### ISSUE THREAD

**Issue by richardartoul** [ClickHouse/ClickHouse#7288]
**Use case**
I'd like to be able to disable checksumming of blocks sent in the native format over TCP (specifically during distributed / remote table queries) similar to how checksumming can be disabled via the HTTP interface with the `http_native_compression_disable_checksumming_on_decompress` setting.

**Describe the solution you'd like**
A new setting that allows me to toggle whether the Clickhouse server validates the checskum of native format blocks it receives from distributed / remote table calls.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm experimenting with using ClickHouse as the native query engine for a storage system that stores data outside of ClickHouse itself. My prototype involves streaming data for ClickHouse to process into ClickHouse during query execution time. I've managed to extract pretty solid performance with this setup, but I'm currently wasting a lot of CPU cycles performing the cityhash algorithm on my end. The data is being transferred over localhost so the checksumming is pretty much wasted CPU that I'd like to make available to ClickHouse to run my queries faster.

If you're ok with this feature and it's not too much work I could try and implement it myself also if you could point me in the right direction.

**Comment by richardartoul** [comment]
After looking through the code it seems like I would just need to add an optional call to `disableChecksumming` in `Connection.cpp` here:

```c++
void Connection::initBlockInput()
{
    if (!block_in)
    {
        if (!maybe_compressed_in)
        {
            if (compression == Protocol::Compression::Enable)
                maybe_compressed_in = std::make_shared<CompressedReadBuffer>(*in);
            else
                maybe_compressed_in = in;
        }

        block_in = std::make_shared<NativeBlockInputStream>(*maybe_compressed_in, server_revision);
    }
}
```

and then I would just need to add a new setting and switch on it and that would basically be it right?

Are all settings propagated for remote queries? I.E if I set a setting in the click house client and use that to issue a query against clickhouse server A, if that clickhouse server A then goes and makes a remote table call to another clickhouse instance B will B receive the same settings that the client passed to A?

**Comment by alexey-milovidov** [comment]
> If you're ok with this feature and it's not too much work I could try and  implement it myself also if you could point me in the right direction.

Yes, I'm totally Ok with that.

> After looking through the code it seems like I would just need to add an optional call to disableChecksumming in Connection.cpp here

Ok. Also note that it will not disable all the places where checksumming is performed:
- while reading from tables;
- while reading temorary data for external sorting/aggregation;
- while receiving data from replicad.

The setting should be named accordingly.
`tcp_disable_checksumming_on_decompress` looks like a good name.

> Are all settings propagated for remote queries?

Yes, unless the user in cluster configuration is readonly on remote server.

**Comment by richardartoul** [comment]
> > If you're ok with this feature and it's not too much work I could try and  implement it myself also if you could point me in the right direction.
> 
> Yes, I'm totally Ok with that.
> 
> > After looking through the code it seems like I would just need to add an optional call to disableChecksumming in Connection.cpp here
> 
> Ok. Also note that it will not disable all the places where checksumming is performed:
> 
> * while reading from tables;
> * while reading temorary data for external sorting/aggregation;
> * while receiving data from replicad.
> 
> The setting should be named accordingly.
> `tcp_disable_checksumming_on_decompress` looks like a good name.
> 
> > Are all settings propagated for remote queries?
> 
> Yes, unless the user in cluster configuration is readonly on remote server.

Can you clarify these?

```
while reading from tables;

while reading temorary data for external sorting/aggregation;

while receiving data from replicad.
```

When you say reading from tables, that only includes local tables right? As far as I can tell the remote table feature will use a client connection to stream blocks in so disabling checksumming there should stop it from checksumming data coming back from remote tables.

```
while reading temorary data for external sorting/aggregation
```
What does this mean? Is this when the client provides data as part of the query?

```
while receiving data from replicad
```
The way what I'm doing works is that I've written a server that basically pretends to be a remote clickhouse instance / replica. I thought that data served from my server to clickhouse via the remote table feature (and the distributed storage engine) would all be going through clickhouse's client so disabling checksumming at the client level would turn off checksumming for this functionality too. Is that not correct?

Thanks for the quick response!

**Comment by alexey-milovidov** [comment]
> When you say reading from tables, that only includes local tables right?

Yes.

> As far as I can tell the remote table feature will use a client connection to stream blocks in so disabling checksumming there should stop it from checksumming data coming back from remote tables.

True. This data will be first read from disk on the servers that store this data and then transferred over network. It will be checksummed while being read from disk but you can disable checksumming of the data received from network.

> The way what I'm doing works is that I've written a server that basically pretends to be a remote clickhouse instance / replica. I thought that data served from my server to clickhouse via the remote table feature (and the distributed storage engine) would all be going through clickhouse's client so disabling checksumming at the client level would turn off checksumming for this functionality too. Is that not correct?

That's correct.

(What I mean is communication between ReplicatedMergeTree tables that is a separate process)

**Comment by alexey-milovidov** [comment]
Have not implemented.
