### ISSUE TITLE
Select query using projection scans every data part

### ISSUE THREAD

**Issue by zavtrazavr** [ClickHouse/ClickHouse#72916]
I have a table with a sorting key. I also created a projection over that table with another sorting key.

When I run select query that uses the projection it scans every data part (8 parts) of the table, whereas I know that the result rows I need are placed in only one part. So query scans 65k rows instead of 8132 (table granularity index). Is this a normal behavior? If yes, does it mean that the same query will scan more rows as the number of data parts grows?

![image](https://github.com/user-attachments/assets/4cc12c1e-9cb5-4a95-a178-8f0a8fd62263)

**Comment by jsc0218** [comment]
Are you sure your query used the projection? You can force to use the projection by setting `SETTINGS optimize_use_projections = 1, force_optimize_projection = 1 `in your select query. Also what's your table and project definition? Best to have a simplified case.

**Comment by zavtrazavr** [comment]
> Are you sure your query used the projection? You can force to use the projection by setting `SETTINGS optimize_use_projections = 1, force_optimize_projection = 1 `in your select query. Also what's your table and project definition? Best to have a simplified case.

Table definition: 

```
CREATE TABLE ltc_data.txs_dev
(
    `address` String,
    `block_height` Int64,
    `timestamp` Int64,
    `tx_hash` String,
    `tx_id` Int64,
    `n` Int16,
    `tx_type` Int8,
    `failed` Bool,
    `fee` String,
    `direction_by_address` Int8,
    `value_by_address` String,
    `approx_fee_by_address` String,
    `sent_by_address` String,
    `recv_by_address` String,
    `txhash_sh` UInt64 DEFAULT sipHash64(tx_hash),
    `address_sh` UInt64 DEFAULT sipHash64(address),
    INDEX txid_dx tx_id TYPE minmax GRANULARITY 1,
    PROJECTION txs_txhash_index_sip
    (
        SELECT 
            txhash_sh,
            tx_hash,
            tx_id
        ORDER BY txhash_sh
    ),
    PROJECTION txs_address_index
    (
        SELECT 
            address_sh,
            block_height,
            tx_id,
            timestamp
        ORDER BY 
            address_sh,
            block_height,
            tx_id
    )
)
ENGINE = MergeTree
ORDER BY (block_height, tx_id)
SETTINGS index_granularity = 8192
```

I'm sure the query uses the projection at least because it doesn't full scan the table: 

```
EXPLAIN
SELECT tx_id
FROM ltc_data.txs_dev
WHERE txhash_sh = sipHash64('1201cbd0a6ff253891e5d07bfa7b3839cb32e975004aeffcb53b6faa302067bc')

Query id: 41ef016c-bf40-4d29-ac0e-442fe3630711

   ┌─explain──────────────────────────────────────┐
1. │ Expression ((Project names + Projection))    │
2. │   Filter                                     │
3. │     ReadFromMergeTree (txs_txhash_index_sip) │
   └──────────────────────────────────────────────┘

```

**Comment by den-crane** [comment]
>I just wonder if it is okay that the query scans every projection data part, whereas the query returns only one row (so that means that the result I need is placed in one data part)

It's by a projection's design. Projection is stored inside the part. 

You have 8 parts -> 8 projections. Need to check the indexes of 8 projections because the index of projections is also sparse. In some cases data reading can be avoided if the first index element is bigger than searched element.

Imagine you store a numbers in a column `x` from 1 to 10000 and you have 3 parts.
The granules will be like this

index of 1st part 466 (1 granule).
index of 2nd part 1, 9333 (2 granules).
index of 3d part 66, 9999 (2 granules).
 
If you search for x= 512 each part potentially can store 512. Need to read 8192*3 rows.
If you search for x= 77 only the 2nd and 3d parts potentially can store 77 (because the first has 466 as minimal val). Need to read 8192*2 rows.

There's no difference for projections.

**Comment by UnamedRus** [comment]
Could be improved by https://github.com/ClickHouse/ClickHouse/issues/72632

**Comment by zavtrazavr** [comment]
> Could be improved by #72632

thank you! worked for me!

**Comment by jsc0218** [comment]
Should be solved, I would close it.
