### ISSUE TITLE
Clickhouse Cluster - How many keeper nodes?

### ISSUE THREAD

**Issue by enzorevo** [ClickHouse/ClickHouse#72915]
### Question

Hi, I'm settuping a 5-node cluster with 3 keeper nodes and 2 server nodes.
Saw here: https://clickhouse.com/docs/en/guides/sizing-and-hardware-recommendations
That 256 GB RAM and 62 vCPUs are sufficient for the server nodes even in very big setups.

But about ClickHouse Keeper nodes: if i will scale to 100 server nodes, will i still be able to run everything with high performance with just 3 keeper nodes?
Or with which criteria do i need to scale them, if so?
Because I guess that if the keeper nodes do not need to be horizontally scaled, is it ok to size them very big (vertically) so that they are sufficiently big for future purposes.

Thanks!

**Comment by UnamedRus** [comment]
> is it ok to size them very big (vertically) so that they are sufficiently big for future purposes.

Even "big" setups, doesn't need huge keeper nodes.
We see that 4 vCPU, 8-16 GB of RAM, 100GB of fast disk for clusters with dozens of nodes.

So, i wouldn't expect that you need to go past 8 vCPU, 16GB of RAM for your setup.

**Comment by enzorevo** [comment]
> > is it ok to size them very big (vertically) so that they are sufficiently big for future purposes.
> 
> Even "big" setups, doesn't need huge keeper nodes. We see that 4 vCPU, 8-16 GB of RAM, 100GB of fast disk for clusters with dozens of nodes.
> 
> So, i wouldn't expect that you need to go past 8 vCPU, 16GB of RAM for your setup.

Thanks. And for clusters with 120 nodes, how many keeper nodes we need? Only 3, or more?

**Comment by UnamedRus** [comment]
>  how many keeper nodes we need?

Bigger keeper cluster -> slower keeper cluster for write operations (more nodes need to commit data to return OK) (but can withstand losing more nodes). I'd suggest to start with 3 nodes
Highest load on keeper is due INSERTs to ClickHouse, if you can batch them properly, load to keeper will be moderate.

**Comment by enzorevo** [comment]
> > how many keeper nodes we need?
> 
> Bigger keeper cluster -> slower keeper cluster for write operations (more nodes need to commit data to return OK) (but can withstand losing more nodes). I'd suggest to start with 3 nodes Highest load on keeper is due INSERTs to ClickHouse, if you can batch them properly, load to keeper will be moderate.

Makes sense. In those extremely big setups described in the documentations, do we know how many keeper nodes they have? Just as a future reference I need to know for example when to scale it bigger, but I guess I just need to keep an eye on the keeper nodes' usage and scale em accordingly when I see they're overloaded, right?

**Comment by UnamedRus** [comment]
> but I guess I just need to keep an eye on the keeper nodes' usage and scale em accordingly when I see they're overloaded, right?

Right.

> In those extremely big setups described in the documentations, do we know how many keeper nodes they have?

Depends on ingestion pattern, but i seen cases with 5 and may be even 7 keeper nodes.
Anyway, it's not a big deal to add additional keeper cluster, plus nodes are still somewhat small compared to "clickhouse-server" nodes, so it should be easy to do in case of need.
