### ISSUE TITLE
Issues with syntax in ALTER USER ADD/DROP PROFILE statements 

### ISSUE THREAD

**Issue by alsugiliazova** [ClickHouse/ClickHouse#72987]
1. This should be a syntax error, I used PROFILE instead of PROFILES:
https://fiddle.clickhouse.com/6972a1e2-d248-4c58-9885-42e3b36a8dc4
```sql
CREATE USER user1;

CREATE PROFILE a,b,c;

ALTER USER user1 ADD PROFILE a,b,c;

SHOW CREATE USER user1;
```
The same with `DROP PROFILE a,b,c`.

2. This query should not be valid:
https://fiddle.clickhouse.com/cbbe2b8d-e84a-4a60-bf18-6012e891d0bb
```sql
ALTER USER user1 DROP ALL PROFILES,,,,,,ADD PROFILE a;
```
3. This works as ADD PROFILE, but should throw an exception:
https://fiddle.clickhouse.com/e8069ccb-8bb8-41b6-a47d-2e04d20c0c5c
```sql
ALTER USER user1 PROFILES c;
```

**Comment by pufit** [comment]
> I used PROFILE instead of PROFILES:

SQL is not the English language. This behavior is intended. 

> This query should not be valid:

https://github.com/ClickHouse/ClickHouse/pull/73257

> This works as ADD PROFILE, but should throw an exception:

No, this has a completely different behavior - rewriting the profiles list.
