### ISSUE TITLE
Does not work join with LowCardinality datatype

### ISSUE THREAD

**Issue by DNEGREEV** [ClickHouse/ClickHouse#7301]
**Does not work join with LowCardinality datatype**
When i'm trying to join tables by lowcardinality attributes

**How to reproduce**
* ClickHouse server version - 19.6.2.1
* Database setting : join_use_nulls = 1
* create table EXAMPLE
(
    revenue Int16,
    name    LowCardinality(String)
)
    engine = MergeTree() ORDER BY name SETTINGS index_granularity = 8192;
* insert into EXAMPLE values (100, '123')
* select t.revenue from EXAMPLE t left join EXAMPLE t1 on t.name = t1.name

**Error message and/or stacktrace**
Code: 43, e.displayText() = DB::Exception: Nested type LowCardinality(String) cannot be inside Nullable type (version 19.6.2.11 (official build))

**Comment by alexey-milovidov** [comment]
Does it reproduce on recent releases?

**Comment by DNEGREEV** [comment]
It's works in version 19.15.3.6
Thank you!
