### ISSUE TITLE
Cross compilation for AArch64.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7302]
Allow to check build for AArch64 on x86_64.
Allow to build packages at least for one CPU variant (example: Cavium).
Add AArch64 build check to CI.

**Comment by alexey-milovidov** [comment]
Does it run successfully on Raspberry Pi, your Android phone and Cavium?

**Comment by abyss7** [comment]
Will test and then close this issue.

**Comment by alexey-milovidov** [comment]
I've tested. It works perfectly on Huawei Taishan.
