### ISSUE TITLE
Join one table multiple times

### ISSUE THREAD

**Issue by nhudinh2103** [ClickHouse/ClickHouse#7303]
Hi, I'm trying this query in clickhouse:

```
SELECT * from web_olap.sale_fact sale_fact
INNER JOIN web_olap.product_dim product_dim ON sale_fact.product_dim_id = product_dim.id
INNER JOIN web_olap.product_dim product_dim2 ON sale_fact.bundle_dim_id = product_dim2.id
```

Clickhouse raise exception:

**DB::Exception: Cannot refer column 'product_dim.id' to one table, Stack trace:**

> 0. 0x34293f8 StackTrace::StackTrace() /usr/local/bin/clickhouse
> 1. 0x3431e3f DB::Exception::Exception(std::string const&, int) /usr/local/bin/clickhouse
> 2. 0x5c10226 DB::InDepthNodeVisitorTemplate<DB::(anonymous namespace)::ColumnAliasesMatcher, true, std::shared_ptr<DB::IAST> const>::visit(std::shared_ptr<DB::IAST> const&) /usr/local/bin/clickhouse
> 3. 0x5c0ff09 DB::InDepthNodeVisitorTemplate<DB::(anonymous namespace)::ColumnAliasesMatcher, true, std::shared_ptr<DB::IAST> const>::visit(std::shared_ptr<DB::IAST> const&) /usr/local/bin/clickhouse
> 4. 0x5c11012 DB::JoinToSubqueryTransformMatcher::visit(DB::ASTSelectQuery&, std::shared_ptr<DB::IAST>&, DB::JoinToSubqueryTransformMatcher::Data&) /usr/local/bin/clickhouse
> 5. 0x5b83809 DB::InDepthNodeVisitorTemplate<DB::JoinToSubqueryTransformMatcher, true, std::shared_ptr<DB::IAST> >::visit(std::shared_ptr<DB::IAST>&) /usr/local/bin/clickhouse
> 6. 0x5b7a4a9 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&) /usr/local/bin/clickhouse
> 7. 0x5b7b1ab DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&) /usr/local/bin/clickhouse
> 8. 0x5ba43d1 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&) /usr/local/bin/clickhouse
> 9. 0x5b5ffaf DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) /usr/local/bin/clickhouse
> 10. 0x5c82e98 DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*, bool) /usr/local/bin/clickhouse
> 11. 0x5c856f5 DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>, std::function<void (std::string const&)>) /usr/local/bin/clickhouse
> 12. 0x34f1241 DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) /usr/local/bin/clickhouse
> 13. 0x34f36ff DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /usr/local/bin/clickhouse
> 14. 0x65f5ba0 Poco::Net::HTTPServerConnection::run() /usr/local/bin/clickhouse
> 15. 0x65f32cf Poco::Net::TCPServerConnection::start() /usr/local/bin/clickhouse
> 16. 0x65f3995 Poco::Net::TCPServerDispatcher::run() /usr/local/bin/clickhouse
> 17. 0x69b5eb1 Poco::PooledThread::run() /usr/local/bin/clickhouse
> 18. 0x69b3cf8 Poco::ThreadImpl::runnableEntry(void*) /usr/local/bin/clickhouse
> 19. 0x6f8cb8f execute_native_thread_routine /usr/local/bin/clickhouse
> 20. 0x7f9e96098dd5 start_thread /usr/lib64/libpthread-2.17.so
> 21. 0x7f9e959b5ead __clone /usr/lib64/libc-2.17.so

Can somebody help me how to do this query in clickhouse?

**Comment by nhudinh2103** [comment]
My clickhouse version is **19.15.2.2**

**Comment by den-crane** [comment]
>INNER JOIN web_olap.product_dim product_dim ON sale_fact.product_dim_id = product_dim.id

INNER JOIN web_olap.product_dim **product_dim1** ON sale_fact.product_dim_id = **product_dim1**.id

**Comment by 4ertus2** [comment]
Related #7214

**Comment by 4ertus2** [comment]
#7358
