### ISSUE TITLE
ClickHouse `initial_port` does not extract the port from proxy protocol header when present

### ISSUE THREAD

**Issue by incfly** [ClickHouse/ClickHouse#73090]
**Describe the unexpected behaviour**
Expected behavior: when proxy protocol header is present, both initial_address and initial_port are coming from the header, instead of port coming from the direct peer's network port.

**How to reproduce**

1. setup a client -> proxy (with proxy protocol header enabled) -> clickhouse cluster
2. make a curl
```
curl -u default:<pwd> 'https://xxxx.us-east-2.aws.clickhouse.cloud:8443' --data-binary 'SELECT 1' 
```
and run tcpdump

```
sudo tcpdump -i any tcp and host dummy-clickhouse-server.com and port 8443   
tcpdump: data link type LINUX_SLL2                                                            
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode                                                                                                                    listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
05:08:04.583655 ens4  Out IP local-machine.internal.64748 > dummy-clickhouse-server.com.8443: Flags [S], seq 2579366380, win 65320, options [mss 1420,sackOK,TS val 1708277899 ecr 0,nop,wscale 7], length 0
05:08:04.638403 ens4  In  IP dummy-clickhouse-server.com.8443 > local-machine.internal.64748: Flags [S.], seq 689054106, ack 2579366381, win 62643, options [mss 1460,sackOK,TS val 293089971 ecr 1708277899,nop,wscale 7], length 0
```

The port is `64748`

3. Check in the ClickHouse query log you will find the `initial_address` is handled correctly by extracting proxy protocol, but not the port. the port will be the middle proxy's port, instead of `64748`.

Some details https://clickhouse-inc.slack.com/archives/C02F2LML5UG/p1733876820252889

**Comment by yakov-olkhovskiy** [comment]
we indeed do not preserve original port and use proxy's instead:
https://github.com/ClickHouse/ClickHouse/blob/master/src/Server/TCPHandler.cpp#L2615
