### ISSUE TITLE
max_insert_block_size does not work for clickhouse-local

### ISSUE THREAD

**Issue by qiang5714** [ClickHouse/ClickHouse#73115]
**Describe the unexpected behaviour**
max_insert_block_size does not work when using clickhouse-local, it sticks to default value 1048545.

**How to reproduce**
1. Dataset to use: hacknernews.csv; `wget https://datasets-documentation.s3.eu-west-3.amazonaws.com/hackernews/hacknernews.csv.gz`
2. Command line to use: `clickhouse local --log-level TRACE --input_format_parallel_parsing 0  --max_insert_block_size=10000 -q " CREATE TABLE tmp ENGINE = MergeTree ORDER BY tuple() AS SELECT * FROM file('/mnt/d/tmp/hacknernews.csv', CSVWithNames, 'id Nullable(Int64), deleted Nullable(Int64), type Nullable(String), by Nullable(String), time Nullable(DateTime64(9)), text Nullable(String), dead Nullable(Int64), parent Nullable(Int64), poll Nullable(Int64), kids Array(Nullable(Int64)), url Nullable(String), score Nullable(Int64), title Nullable(String), parts Nullable(String), descendants Nullable(Int64)') "`
3. or, Command line 2:  `clickhouse local --log-level TRACE --max_insert_threads 1   --input_format_parallel_parsing 0 -q "set max_insert_block_size=1024;CREATE TABLE tmp ENGINE = MergeTree ORDER BY tuple() AS SELECT * FROM file('/mnt/d/tmp/hacknernews.csv', CSVWithNames, 'id Nullable(Int64), deleted Nullable(Int64), type Nullable(String), by Nullable(String), time Nullable(DateTime64(9)), text Nullable(String), dead Nullable(Int64), parent Nullable(Int64), poll Nullable(Int64), kids Array(Nullable(Int64)), url Nullable(String), score Nullable(Int64), title Nullable(String), parts Nullable(String), descendants Nullable(Int64)') "`
4. How to check result: `ls -t /tmp | head -1 | xargs -I__ cat /tmp/__/data/_local/tmp/all_1_1_0/count.txt` got result **1048545**

* Which ClickHouse server version to use
ClickHouse local version 22.3.2.1.

* Which interface to use, if matters
clickhouse local

* Non-default settings, if any
--input_format_parallel_parsing 0  
--max_insert_block_size=10000

* `CREATE TABLE` statements for all tables involved
**CREATE TABLE tmp ENGINE = MergeTree ORDER BY tuple() AS SELECT * FROM file('/mnt/d/tmp/hacknernews.csv', CSVWithNames, 'id Nullable(Int64), deleted Nullable(Int64), type Nullable(String), by Nullable(String), time Nullable(DateTime64(9)), text Nullable(String), dead Nullable(Int64), parent Nullable(Int64), poll Nullable(Int64), kids Array(Nullable(Int64)), url Nullable(String), score Nullable(Int64), title Nullable(String), parts Nullable(String), descendants Nullable(Int64)')**

* Sample data for all these tables, use [clickhouse-obfuscator]
hacknernews.csv; `wget https://datasets-documentation.s3.eu-west-3.amazonaws.com/hackernews/hacknernews.csv.gz`

* Queries to run that lead to unexpected result

**Expected behavior**
clickhouse generate a part with 10000 rows.

**Error message and/or stacktrace**
No Error.

**Additional context**

**Comment by qiang5714** [comment]
I'm using **seatunnel**, when processing  wide hive table or table with  large string columns , clickhouse local eats too much memory, we can confirm this by setting **_max_memory_usage_for_user=12000000000_**, like: 

> Code: 241. DB::Exception: Memory limit (for user) exceeded: would use 16.04 GiB (attempt to allocate chunk of 12889096192 bytes), maximum: 11.18 GiB: While executing CSVRowInputFormat: While executing File. (MEMORY_LIMIT_EXCEEDED)

**Comment by Algunenano** [comment]
For some reason we are reading from config the wrong key; `insert_format_max_block_size` vs `max_insert_block_size`. I see super old examples using `insert_format_max_block_size` instead, but I don't know where it comes from and where it went

**Comment by qiang5714** [comment]
> For some reason we are reading from config the wrong key; `insert_format_max_block_size` vs `max_insert_block_size`. I see super old examples using `insert_format_max_block_size` instead, but I don't know where it comes from and where it went

sorry, that does not work for 22.3.  I tried to `set min_insert_block_size_rows/bytes = 0`, it's better but I still wonder way max_insert_block_size not work.

**Comment by qiang5714** [comment]
problem solved, minimal argument combination is this: `--max_block_size 1024 --min_insert_block_size_rows 0 --min_insert_block_size_bytes 0 ` .
