### ISSUE TITLE
What is "active" znode means in Zookeeper?

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#7312]
When I check my zk, I found a 'actived' znode in the clickhouse path.I check the document but nothing found out.
so what's this znode means?
byw,when I use replicated table,every insert operation one znode would be created,should I need to delete znode manually after some days like a month to prevent so many znodes in zk?

**Comment by alexey-milovidov** [comment]
> so what's this znode means?

Replica has a session with ZooKeeper and can serve INSERT queries.

> byw,when I use replicated table,every insert operation one znode would be created,should I need to delete znode manually after some days like a month to prevent so many znodes in zk?

No, you don't need anything manually with ZK nodes.

**Comment by byx313** [comment]
> > so what's this znode means?
> 
> Replica has a session with ZooKeeper and can serve INSERT queries.
> 
> > byw,when I use replicated table,every insert operation one znode would be created,should I need to delete znode manually after some days like a month to prevent so many znodes in zk?
> 
> No, you don't need to do anything manually with ZK nodes.

thx！
