### ISSUE TITLE
Can not use comma-separated join tables with IN clause

### ISSUE THREAD

**Issue by nhudinh2103** [ClickHouse/ClickHouse#7314]
Here's the query I have tried

```
select *
from `web_olap`.`date_dim` as `date_dim`, `web_olap`.`sale_fact` as `sale_fact`
where `sale_fact`.`date_dim_id` = `date_dim`.`id`
  and (`sale_fact`.`order_id` in (1, 2))

```
It didn't work and throw exception

**Invalid expression for JOIN ON. Expected equals expression, got order_id IN (1, 2). Supported syntax: JOIN ON Expr([table.]column, ...) = Expr([table.]column, ...) [AND Expr([table.]column, ...) = Expr([table.]column, ...) ...], Stack trace:**

> 0. 0x34293f8 StackTrace::StackTrace() /usr/local/bin/clickhouse
> 1. 0x3431e3f DB::Exception::Exception(std::string const&, int) /usr/local/bin/clickhouse
> 2. 0x6183d30 DB::CollectJoinOnKeysMatcher::throwSyntaxException(std::string const&) /usr/local/bin/clickhouse
> 3. 0x6184a59 DB::CollectJoinOnKeysMatcher::visit(DB::ASTFunction const&, std::shared_ptr<DB::IAST> const&, DB::CollectJoinOnKeysMatcher::Data&) /usr/local/bin/clickhouse
> 4. 0x5c6506f DB::InDepthNodeVisitorTemplate<DB::CollectJoinOnKeysMatcher, true, std::shared_ptr<DB::IAST> const>::visit(std::shared_ptr<DB::IAST> const&) /usr/local/bin/clickhouse
> 5. 0x5c650b3 DB::InDepthNodeVisitorTemplate<DB::CollectJoinOnKeysMatcher, true, std::shared_ptr<DB::IAST> const>::visit(std::shared_ptr<DB::IAST> const&) /usr/local/bin/clickhouse
> 6. 0x5c650b3 DB::InDepthNodeVisitorTemplate<DB::CollectJoinOnKeysMatcher, true, std::shared_ptr<DB::IAST> const>::visit(std::shared_ptr<DB::IAST> const&) /usr/local/bin/clickhouse
> 7. 0x5c613c2 DB::SyntaxAnalyzer::analyze(std::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::vector<std::string, std::allocator<std::string> > const&, std::shared_ptr<DB::IStorage>, DB::NamesAndTypesList const&) const /usr/local/bin/clickhouse
> 8. 0x5b7a04e DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&) /usr/local/bin/clickhouse
> 9. 0x5b7b1ab DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&) /usr/local/bin/clickhouse
> 10. 0x5ba43d1 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&) /usr/local/bin/clickhouse
> 11. 0x5b5ffaf DB::InterpreterFactory::get(std::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) /usr/local/bin/clickhouse
> 12. 0x5c82e98 DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*, bool) /usr/local/bin/clickhouse
> 13. 0x5c856f5 DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>, std::function<void (std::string const&)>) /usr/local/bin/clickhouse
> 14. 0x34f1241 DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) /usr/local/bin/clickhouse
> 15. 0x34f36ff DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /usr/local/bin/clickhouse
> 16. 0x65f5ba0 Poco::Net::HTTPServerConnection::run() /usr/local/bin/clickhouse
> 17. 0x65f32cf Poco::Net::TCPServerConnection::start() /usr/local/bin/clickhouse
> 18. 0x65f3995 Poco::Net::TCPServerDispatcher::run() /usr/local/bin/clickhouse
> 19. 0x69b5eb1 Poco::PooledThread::run() /usr/local/bin/clickhouse
> 20. 0x69b3cf8 Poco::ThreadImpl::runnableEntry(void*) /usr/local/bin/clickhouse
> 21. 0x6f8cb8f execute_native_thread_routine /usr/local/bin/clickhouse
> 22. 0x7f686171cdd5 start_thread /usr/lib64/libpthread-2.17.so
> 23. 0x7f6861039ead __clone /usr/lib64/libc-2.17.so
>  (version 19.15.2.2)
>

**Comment by den-crane** [comment]
it should be
```

select *
from `web_olap`.`date_dim` as `date_dim` 
         join `web_olap`.`sale_fact` as `sale_fact` on  `sale_fact`.`date_dim_id` = `date_dim`.`id`
  where (`sale_fact`.`order_id` in (1, 2))
```

**Comment by nhudinh2103** [comment]
Thanks for quick response, but I currently use clickhouse-jdbc with Mondrian schema and it generates sql like above

```
select *
from `web_olap`.`date_dim` as `date_dim`, `web_olap`.`sale_fact` as `sale_fact`
where `sale_fact`.`date_dim_id` = `date_dim`.`id`
  and (`sale_fact`.`order_id` in (1, 2))
```

Can clickhouse somehow support this type of query please?

**Comment by den-crane** [comment]
Reproducible example:

create table ax (A Int64, B Int64) Engine=Memory;
create table bx (A Int64) Engine=Memory;

select * from bx, ax where ax.A=bx.A and ax.B in (1,2);


Received exception from server (version 19.16.1):
Code: 403. DB::Exception: Received from localhost:9000. DB::Exception: Invalid expression for JOIN ON. Expected equals expression, got B IN (1, 2)


------------

select * from ax,bx where ax.A=bx.A and ax.B in (1,2);

Ok.
0 rows in set. Elapsed: 0.002 sec.

**Comment by 4ertus2** [comment]
The problem is here: https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Interpreters/CrossToInnerJoinVisitor.cpp#L124

It's not easy to fix. It's hack to push IN clause down to subquery. And it looks like it depends on tables order. Related to #4731
