### ISSUE TITLE
Support Dates and DateTimes outside of 1970-2105 range.

### ISSUE THREAD

**Issue by drstrangelooker** [ClickHouse/ClickHouse#7316]
Dates are currently not supported outside of this range.

This may not be an issue for analyzing specific data sets like current web logs, but is a show stopper for using ClickHouse more generally. For example, if one wanted to include a user's birthdate with the web activity in order to do analysis by age cohort, this would not work. If one wanted to do analysis on historical data this is also an issue.

Date and DateTime values should be expanded to cover a much larger range.

**Comment by den-crane** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/4860
WIP  https://github.com/ClickHouse/ClickHouse/pull/7170

**Comment by Enmk** [comment]
@den-crane the #7170 will not add FULL support of dates outside of given range, that was planned for phase 2 of DateTime64 implementation.

Even more to that, now there is no way to lift that limitation completely in simple and efficient manner, since current calendar-related features (getting date/day name/month) rely on a lookup-tables, which can't be made infinitely large (for obvious reasons).

**Comment by den-crane** [comment]
@Enmk OK good to know. Thanks.

>now there is no way to lift that limitation 
Lazy cache. Do not see a problem to calculate and put into cache several days with i.e. 8000 year.

```
pg> select to_char(to_date('01-01-8000','DD-MM-YYYY'), 'day');
  to_char
-----------
 saturday
(1 row)

pg> select to_char(to_date('01-01-9000','DD-MM-YYYY'), 'day');
  to_char
-----------
 wednesday
(1 row)
```

**Comment by Enmk** [comment]
Yep, but current lookup table is pre-computed once the timezone is created, that means if we are to replace LUT with lazy cache, we'll get a performance degradation on first access on any particular time value.

Sure, we can have both precomputed LUT and lazy-cache, but this makes solution not quite simple and slightly less efficient for the most probable use pattern (in oversimplified pseudo-code):

```
if value is in LUT range:
    return LUT[value] // <== most likely to happen
else:
    if value is in lazyCache:
        return lazyCache[value]
    else:
        dateTimeInfo = computeCacheableValue(value)
        lazyCache[value] = v
        return v
```

At this point I am not sure if that second layer of caching would bring any benefits compared to the burden of maintaining two layers of cache.

**Comment by zhicwu** [comment]
Tried DateTime64 in 20.3.12.112 but wasn't able to save date like `1970-01-01 00:00:00.0` or older, and value looks weird when converting from a negative number(please refer to the last query below).

```bash
clickhouse :) select toDate('1970-01-01'), toDateTime('1970-01-01 00:00:00'), toDateTime64('1970-01-01 00:00:00.0', 3)

SELECT
    toDate('1970-01-01'),
    toDateTime('1970-01-01 00:00:00'),
    toDateTime64('1970-01-01 00:00:00.0', 3)

┌─toDate('1970-01-01')─┬─toDateTime('1970-01-01 00:00:00')─┬─toDateTime64('1970-01-01 00:00:00.0', 3)─┐
│           0000-00-00 │               0000-00-00 00:00:00 │                  0000-00-00 00:00:00.000 │
└──────────────────────┴───────────────────────────────────┴──────────────────────────────────────────┘

1 rows in set. Elapsed: 0.011 sec.

clickhouse :) select toDate(0), toDateTime(0), toDateTime64(0.0, 3)

SELECT
    toDate(0),
    toDateTime(0),
    toDateTime64(0., 3)

┌──toDate(0)─┬───────toDateTime(0)─┬─────toDateTime64(0., 3)─┐
│ 0000-00-00 │ 0000-00-00 00:00:00 │ 0000-00-00 00:00:00.000 │
└────────────┴─────────────────────┴─────────────────────────┘

1 rows in set. Elapsed: 0.006 sec.

clickhouse :) select toDate(-1), toDateTime(-1), toDateTime64(-1.0, 3)

SELECT
    toDate(-1),
    toDateTime(-1),
    toDateTime64(-1., 3)

┌─toDate(-1)─┬──────toDateTime(-1)─┬───toDateTime64(-1., 3)─┐
│ 2106-02-07 │ 2106-02-07 06:28:15 │ 1970-01-01 00:00:$.000 │
└────────────┴─────────────────────┴────────────────────────┘

1 rows in set. Elapsed: 0.005 sec.
```

**Comment by millin** [comment]
Since 21.4 version DateTime64 supports extended range, but Date & DateTime are still not.
@alexey-milovidov @Enmk are there plans to extend them too?

```
SELECT
    toDate('1969-01-01'),
    toDateTime('1969-01-01 00:00:00'),
    toDateTime64('1969-01-01 00:00:00.0', 3)

┌─toDate('1969-01-01')─┬─toDateTime('1969-01-01 00:00:00')─┬─toDateTime64('1969-01-01 00:00:00.0', 3)─┐
│           2148-06-07 │               1970-01-01 03:00:00 │                  1969-01-01 00:00:00.000 │
└──────────────────────┴───────────────────────────────────┴──────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
@millin Date is extended to `2149-06-06`.
DateTime cannot be extended for now, because 32 bits are just not enough.

Only after we will introduce support for multiple serializations and column representations for single data type.
