### ISSUE TITLE
Date functions fail silently when values are out of range or arguments are null

### ISSUE THREAD

**Issue by drstrangelooker** [ClickHouse/ClickHouse#7317]
I consider values out of range to be an error condition, but I can understand a counter argument that the following is ok.
`toDate('1969-12-31')` yields null.
`toDateTime('1969-12-31 23:59:59')` yields null.

This behavior is definitely wrong.
`toYear(toDate('1965-03-15'))` yields 1970.
`toYear(NULL)` yields 1970.
With very few exceptions (for example the coalesce function and aggregate functions) a function with a null argument should **ALWAYS** produce a null result.

This allows an error to propagate with no obvious impact.

**Comment by alexey-milovidov** [comment]
> a function with a null argument should ALWAYS produce a null result.

It already works this way and always worked this way.

```
SELECT toYear(NULL)

┌─toYear(NULL)─┐
│ ᴺᵁᴸᴸ         │
└──────────────┘
```
