### ISSUE TITLE
LIKE and MATCH don’t support column values or certain complex expressions

### ISSUE THREAD

**Issue by drstrangelooker** [ClickHouse/ClickHouse#7321]
Expressions where the right side can be reduced to a constant work fine.
`user.name LIKE  '%John%'`

But if the right side can't be reduced to a constant, the search does not work.
`user.name LIKE  CONCAT('%', orders.sales_rep, '%')`

**Comment by m1khal3v** [comment]
Is this functionality planned?

**Comment by alexey-milovidov** [comment]
It is in backlog.

**Comment by m1khal3v** [comment]
If someone really needs a match with expressions as a pattern, you can use custom functions right now
https://clickhouse.com/docs/en/sql-reference/functions/#executable-user-defined-functions

@alexey-milovidov looking forward to

**Comment by supermarat** [comment]
Any news here? @alexey-milovidov 

The solution that uses the custom function performs slowly, the real need is to use the inbuilt functions 'like' and 'match'

**Comment by den-crane** [comment]
ClickHouse release 22.6, 2022-06-16

Support non-constant pattern argument for LIKE, ILIKE and match functions. https://github.com/ClickHouse/ClickHouse/pull/37251 ([Robert Schulze](https://github.com/rschu1ze)).
