### ISSUE TITLE
DATEDIFF function does implicit rounding

### ISSUE THREAD

**Issue by drstrangelooker** [ClickHouse/ClickHouse#7322]
In most databases, DATEDIFF provides the whole number of intervals between the start and end dates. ClickHouse rounds those values. For example a 4 day interval registers as a week.

`SELECT DATEDIFF(week,toDate('2010-01-01'),toDate('2010-01-03'))` yields 0, expect 0
`SELECT DATEDIFF(week,toDate('2010-01-01'),toDate('2010-01-04'))` yields 1, expect 0
`SELECT DATEDIFF(week,toDate('2010-01-01'),toDate('2010-01-10'))` yields 1, expect 1
`SELECT DATEDIFF(week,toDate('2010-01-01'),toDate('2010-01-11'))` yields 2, expect 1

There is a workaround by finding the DATEDIFF in seconds, then dividing by the number of seconds in the requested interval and taking the floor. That works for minute, hour, day, and week. Month, quarter, and year are far more difficult to work around.

**Comment by den-crane** [comment]
I think it should be fixed or documented

**Comment by den-crane** [comment]
I guess it uses toRelativeWeekNum and should be documented.

```
WITH
    toDateTime('2021-02-28 00:00:00') AS from_date,
    toDateTime('2021-03-01 00:00:00') AS to_date
SELECT
    dateDiff('week', from_date, to_date),
    toRelativeWeekNum(from_date),
    toRelativeWeekNum(to_date)
Query id: 07291039-45a8-4573-8c8d-f04b9511c048
┌─dateDiff('week', from_date, to_date)─┬─toRelativeWeekNum(from_date)─┬─toRelativeWeekNum(to_date)─┐
│                                    1 │                         2669 │                       2670 │
└──────────────────────────────────────┴──────────────────────────────┴────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
@drstrangelooker 

> There is a workaround by finding the DATEDIFF in seconds, then dividing by the number of seconds in the requested interval and taking the floor.

This workaround is incorrect, because days may have different number of seconds due to daylight saving time.
Also it needs to be clarified how difference in months is supposed to work.

Please provide examples from other DBMS and excerpts from the SQL standard.

**Comment by alexey-milovidov** [comment]
PostgreSQL does not implement DATEDIFF at all :1st_place_medal: 
https://www.postgresql.org/docs/current/functions-datetime.html

MySQL does not implement DATEDIFF with arbitrary intervals :facepalm: 
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_datediff
and it has the order of arguments reversed.

Neither does SQLite :wastebasket: 
https://www.sqlite.org/lang_datefunc.html

Bigquery does it similar to ClickHouse:
https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_diff
But with different order of arguments.
and it provides some controls over week start.

MS SQL does it and agrees with ClickHouse:
`SELECT DATEDIFF(month, '2000/01/31', '2000/02/01') AS DateDiff;` returns 1 although the difference is only one day.

Snowflake agrees with ClickHouse:
https://docs.snowflake.com/en/sql-reference/functions/datediff.html
and provides some controls over week start.

Redshift is also consistent with ClickHouse:
https://docs.aws.amazon.com/redshift/latest/dg/r_DATEDIFF_function.html

SQL standard does not have DATEDIFF.
