### ISSUE TITLE
 Version 21.12.3.32. None of the nodes in the ClickHouse cluster are processing query requests at the same time, and login is not possible. Meanwhile, the cluster load is low, and the QPS is also low.

### ISSUE THREAD

**Issue by jasonchoi517** [ClickHouse/ClickHouse#73255]
```[tasklist]
### Tasks
```

**Comment by jasonchoi517** [comment]
2024.12.01 12:37:30.117847 [ 87143 ] {46aeefce-0a58-4dbc-8210-b8b0024795e0} <Information> executeQuery: Read 56 rows, 7.05 KiB in 0.000987862 sec., 56688 rows/sec., 6.97 MiB/sec.
2024.12.01 12:37:30.136519 [ 87143 ] {1eb96dae-2d84-4d6d-96fa-ee0efaa223f4} <Information> executeQuery: Read 56 rows, 7.05 KiB in 0.007697454 sec., 7275 rows/sec., 916.50 KiB/sec.
2024.12.01 12:37:30.156186 [ 87143 ] {ec1f04c3-660c-4fde-bdd7-ad8e433d0ffb} <Information> executeQuery: Read 56 rows, 7.05 KiB in 0.002221395 sec., 25209 rows/sec., 3.10 MiB/sec.
2024.12.01 12:37:30.177400 [ 87143 ] {16859cec-d922-460f-b197-871e0d6579c3} <Information> executeQuery: Read 48 rows, 14.66 KiB in 0.010738099 sec., 4470 rows/sec., 1.33 MiB/sec.
2024.12.01 12:37:30.917935 [ 87143 ] {1691d3c9-9154-4f8b-9edb-2978b06488d4} <Information> executeQuery: Read 5 rows, 14.63 KiB in 0.001324625 sec., 3774 rows/sec., 10.79 MiB/sec.
2024.12.01 12:37:33.975833 [ 310794 ] {71adb031-056d-4ccf-8ad9-294f6030cdb9} <Information> executeQuery: Read 3 rows, 8.56 KiB in 0.001200919 sec., 2498 rows/sec., 6.96 MiB/sec.
2024.12.01 12:38:05.123305 [ 181634 ] {dc79efd0-ddb6-4561-9c79-efd0ddb61561::20241129_9_14_1} <Information> MergeTask::PrepareStage: Some TTL values were not calculated for part 20241129_9_9_0. Will calculate them forcefully during merge.
2024.12.01 12:38:05.123310 [ 181634 ] {dc79efd0-ddb6-4561-9c79-efd0ddb61561::20241129_9_14_1} <Information> MergeTask::PrepareStage: Some TTL values were not calculated for part 20241129_10_10_0. Will calculate them forcefully during merge.
# login is not possible. ClickHouseMetrics_HTTPConnection raise up。 stop executeQuery
2024.12.01 12:38:14.918922 [ 264912 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:38:18.758500 [ 181859 ] {} <Information> xxxx_db.local_t_xxx (ReplicatedMergeTreeQueue): Loading 1 mutation entries: 0000207118 - 0000207118
2024.12.01 12:38:50.362041 [ 307717 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:38:50.370407 [ 307717 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:39:28.726078 [ 308196 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:40:08.817130 [ 308928 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:40:47.480392 [ 309240 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:41:24.624104 [ 50962 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:41:24.624239 [ 164039 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:42:01.061513 [ 309899 ] {} <Information> TCPHandler: Client has not sent any data.

**Comment by jasonchoi517** [comment]
Our company's ClickHouse cluster has 28 nodes. In recent months, we have encountered issues where the cluster becomes unresponsive, with low node load and QPS below 100. The cluster suddenly becomes inaccessible(can not login), ClickHouseMetrics_HTTPConnection indicator immediately increased，and  restart cluster is required to recover.

**Comment by jasonchoi517** [comment]
clickhouse-server.log
2024.12.01 12:37:30.917935 [ 87143 ] {1691d3c9-9154-4f8b-9edb-2978b06488d4} <Information> executeQuery: Read 5 rows, 14.63 KiB in 0.001324625 sec., 3774 rows/sec., 10.79 MiB/sec.
2024.12.01 12:37:33.975833 [ 310794 ] {71adb031-056d-4ccf-8ad9-294f6030cdb9} <Information> executeQuery: Read 3 rows, 8.56 KiB in 0.001200919 sec., 2498 rows/sec., 6.96 MiB/sec.
2024.12.01 12:38:05.123305 [ 181634 ] {dc79efd0-ddb6-4561-9c79-efd0ddb61561::20241129_9_14_1} <Information> MergeTask::PrepareStage: Some TTL values were not calculated for part 20241129_9_9_0. Will calculate them forcefully during merge.
2024.12.01 12:38:05.123310 [ 181634 ] {dc79efd0-ddb6-4561-9c79-efd0ddb61561::20241129_9_14_1} <Information> MergeTask::PrepareStage: Some TTL values were not calculated for part 20241129_10_10_0. Will calculate them forcefully during merge.
------- login is not possible. ClickHouseMetrics_HTTPConnection raise up。 stop executeQuery
------- no <Information> produce
2024.12.01 12:38:14.918922 [ 264912 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:38:18.758500 [ 181859 ] {} <Information>(ReplicatedMergeTreeQueue): Loading 1 mutation entries: 0000207118 - 0000207118
2024.12.01 12:38:50.362041 [ 307717 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:38:50.370407 [ 307717 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:39:28.726078 [ 308196 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:40:08.817130 [ 308928 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:40:47.480392 [ 309240 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:41:24.624104 [ 50962 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:41:24.624239 [ 164039 ] {} <Information> TCPHandler: Client has not sent any data.
2024.12.01 12:42:01.061513 [ 309899 ] {} <Information> TCPHandler: Client has not sent any data.

---- restart other nodes,  Current limiting queries  takes effect。
2024.12.01 12:42:24.708488 [ 345991 ] {d9b45d1e-9d77-4d5a-a79c-82e26a266bc5} <Error> executeQuery: Code: 202. DB::Exception: Too many simultaneous queries for user . Current: 108, maximum: 108. (TOO_MANY_SIMULTANEOUS_QUERIES) (version 21.12.3.32 (official build)) (from 10.25.25.245:54718) (in query: INSERT INTO FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):

**Comment by Algunenano** [comment]
21.12 is obsolete. Please upgrade to a supported release
