### ISSUE TITLE
No way to get weekday (Monday, Tuesday, etc)

### ISSUE THREAD

**Issue by drstrangelooker** [ClickHouse/ClickHouse#7325]
There is no way to produce the weekday from the date format.

Using `arrayElement(array('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'), toDayOfWeek(date_value))` as a workaround.

**Comment by hczhcz** [comment]
The weekday names are language-dependent. It is better to come with a setting item.

**Comment by alexey-milovidov** [comment]
Many questions arise even for english names:
- should the first letter be capitalized: `Monday` with `monday`;
- should the compact format will be used: `Mon`, `Tue`...

Let's look to other DBMS:

MySQL, MariaDB:
https://mariadb.com/kb/en/dayname/

Looks like the most natural to implement.

MS SQL Server:
https://docs.microsoft.com/en-us/sql/t-sql/functions/datename-transact-sql?view=sql-server-ver15

**Comment by alexey-milovidov** [comment]
@dankondr do you want to implement it?

**Comment by alexey-milovidov** [comment]
See also https://github.com/ClickHouse/ClickHouse/issues/7741

**Comment by arv-pyrna** [comment]
@alexey-milovidov : Is this issue open ? can i take it ?
