### ISSUE TITLE
No toStartOfWeek() function

### ISSUE THREAD

**Issue by deangelo-llooker** [ClickHouse/ClickHouse#7326]
There is no way to get the value of the first day of the week. A `toStartOfWeek()` function would help immensely.

**Comment by alexey-milovidov** [comment]
It is named `toMonday` intentionally to avoid confusion between europeian / north american / muslim weeks.

**Comment by den-crane** [comment]
https://clickhouse.yandex/docs/en/query_language/functions/date_time_functions/#tostartofweek-t-mode
```
SELECT toStartOfWeek(today())

┌─toStartOfWeek(today())─┐
│             2019-10-13 │
└────────────────────────┘
```

**Comment by deangelo-llooker** [comment]
I think I was using an older version of the server when I noted this. I'll close.
