### ISSUE TITLE
Does clickhouse support Nullable(Date) while loading from a csv file 

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#7330]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

**Comment by den-crane** [comment]
Null in CSV should be encoded as \N
Or use input_format_null_as_default
```

create table XDate(A Nullable(Date), O String) Engine = Memory;
insert into XDate format CSV \N,aaaa

SELECT * FROM XDate
┌────A─┬─O────┐
│ ᴺᵁᴸᴸ │ aaaa │
└──────┴──────┘

set input_format_null_as_default = 1

insert into XDate format CSV ,bbbb

SELECT * FROM XDate

┌────A─┬─O────┐
│ ᴺᵁᴸᴸ │ bbbb │
│ ᴺᵁᴸᴸ │ aaaa │
└──────┴──────┘
```
