### ISSUE TITLE
Сортировка уже созданного столбца

### ISSUE THREAD

**Issue by PlatonB** [ClickHouse/ClickHouse#7338]
ClickHouse client version 19.15.3.6 (official build).
ClickHouse server version 19.15.3 revision 54426.

Допустим, создаю таблицу со столбцами _a_, _b_ и _c_, и сортировать мне для начала достаточно только _a_ и _b_.
```
client.execute('''CREATE TABLE test_chdb_tbl
                  (a Int64 CODEC(ZSTD(22)), b Int64 CODEC(ZSTD(22)), c Int64 CODEC(ZSTD(22)))
                  ENGINE = MergeTree()
                  ORDER BY (a, b)''')
```

Заполняю таблицу какими-нибудь данными.
```
data = [{'a': randint(1, 99), 'b': randint(1, 99), 'c': randint(1, 99)} for i in range(10)]

client.execute('''INSERT INTO test_chdb_tbl
                  (a, b, c)
                  VALUES''', data)
```

После завершения формирования таблицы появляется необходимость отсортировать столбец _c_. Есть способ это сделать, не пересоздавая его с нуля?

**Comment by den-crane** [comment]
создавать новую таблицу с ORDER BY (a, b, с)
и переливать данные в нее

**Comment by PlatonB** [comment]
В том-то и суть, что нужно без перезаливов. Возможно, есть метод, который забыли отразить в документации.

**Comment by filimonov** [comment]
Данные уже отсортированы по `(a,b)` но не по `c`.
И в таком виде записаны на диск. Верно? 

Чтобы они стали отсортированы по (a,b,c) - нужно их:
1) прочитать с диска
2) распаковать
3) пересортировать (в этом месте возможна некая отпимизация с учетом того что данные уже посортированы по a,b) 
4) запаковать
5) записать на диск

С учетом стоимости (высокой) шагов 1,2,4,5 потенциальная (маленькая) оптимизация которая возможна на шаге 3 будет совсем незаметна.

На bigdata выполнение этих операций может длится днями и неделями, и если это делать inplace (без копирования в другую таблицу) - то это несёт дополнительные риски, из жанра: а что случится с нашей inplace пересортировкой если на 95% выполнения, вдруг произойдет какая-то ошибка / непредвиденная ситуация и в каком состоянии останутся наши данные?

Короче по сравнению с `INSERT ... SELECT` никаких явных преимуществ - ни по скорости выполнения, ни по юзабилити.

**Comment by PlatonB** [comment]
Будет ли оптимизация на шаге 3 столь же маленькой, если столбцов - тысячи, а досортировать надо один?

**Comment by den-crane** [comment]
если в индексе будут тысячи столбцов, то работать это не будет, даже на сотне столбцов индекс будет занимать слишком много памяти (индекс целиком помещается в память).

Более того на практике уже после 4,5 столбцов, последующие столбцы обычно не изменяют порядок строк. 
В общем это бессмыслица.

**Comment by PlatonB** [comment]
> последующие столбцы обычно не изменяют порядок строк.

Странно. В материале https://ruhighload.com/Колоночные+базы+данных написано "все данные в колоночной базе данных обычно хранятся в отсортированном виде (**каждая колонка отдельно**)". Насколько я понял по примечанию в скобках, сортировка столбца _a_ не должна влиять на сотрировку _b_, а, в свою очередь, _b_ - на _c_.

> Зачем вам кстати менять (a, b) на (a,b,c) ?

Это - планируемая фича моей будущей биоинформатической программы, преобразующей крупные TSV в базу и далее работающей с ней. При смене задач может потребоваться вытаскивать данные по столбцам, отличным от изначально сортированных. Оттуда и потребность адаптировать БД малой кровью.

> Короче по сравнению с INSERT ... SELECT никаких явных преимуществ - ни по скорости выполнения, ни по юзабилити.

Тогда вопрос. Как ведёт себя INSERT ... SELECT по отношению к оперативной памяти? Целиком помещает туда результаты SELECT и потом складывает в конечную таблицу? Или более по-умному?

**Comment by den-crane** [comment]
Сортируется все таблица (вообще все 100500 колонок) в порядке (a,b) .

вот так 

a | b
-- | --
1 | z
2 | a
2 | z

Если c -- высокардинальное поле (уникальный id), добавлять дальше колонки в индекс ...,c,d,e -- нет смысла -- ничего не изменится.

>При смене задач может потребоваться вытаскивать данные по 
>столбцам, отличным от изначально сортированных. 

Вам просто надо заново заливать данные в другую таблицу. 
У вас же нет проблемы с непрерывным потоком -- миллиард строк в час.

>Тогда вопрос. Как ведёт себя INSERT ... SELECT по отношению к оперативной памяти? >Целиком помещает туда результаты SELECT и потом складывает в конечную таблицу?

Стримится блоками по 65к строк (max_block_size). Читаем 65к, параллельно их пишем.
