### ISSUE TITLE
Median of an even set is wrong.

### ISSUE THREAD

**Issue by drstrangelooker** [ClickHouse/ClickHouse#7340]
Consider the following query...
```
SELECT medianExact(median_test.m) AS "median_test.median"
FROM (select 0 as m union all select 28 as m ) AS median_test
```
The median of an even set is defined as the middle element of a set with an odd number of elements, and the mean of the two elements nearest the middle for a set with an even number of elements.

ClickHouse returns 28 in this case, while the expected value is 14.

**Comment by akuzm** [comment]
`medianExact` is like median but it must return a value that is present in the input set -- not sure how it's called, a medoid? The `median` function computes a real median and returns 14.

Our docs wrongly assert that these functions are synonymous, this should be fixed:
https://clickhouse.yandex/docs/en/query_language/agg_functions/reference/#median-x

**Comment by alexey-milovidov** [comment]
@akuzm All `median` functions are synonims of the corresponding `quantile` functions with parameter `level` set to 0.5.
