### ISSUE TITLE
Queries with unicode characters in table names can't be queried

### ISSUE THREAD

**Issue by JC-85** [ClickHouse/ClickHouse#73439]
**Describe what's wrong**

When moving a logging application from InfluxDB to ClickHouse where some of the table names contain utf-8 characters, the data was imported correctly and the tables can be listed correctly. But when queried, both from the clickhouse-client and over http, the query fails with "Unrecognized Token".

Telegraf was used to create the tables so exact query is unknown. Telegraf uses the clickhouse-go library.

```

ccef8c14cc8a :) show tables

SHOW TABLES

Query id: d99c6318-fe7a-4e02-b773-9f94f623091d

   ┌─name────────────┐
1. │ KYL_1           │
2. │ KYL_2           │
3. │ RÖKSKÅP_1       │
4. │ RÖKSKÅP_2       │
5. │ RÖKSKÅP_2_annot │
   └─────────────────┘

5 rows in set. Elapsed: 0.004 sec.

```
```

ccef8c14cc8a :) select * from RÖKSKÅP_1

Syntax error: failed at position 16 ('�'):

select * from RÖKSKÅP_1

Unrecognized token: '�'
```

ClickHouse Version: 24.10.2.80

**Comment by Algunenano** [comment]
Use:
```sql
select * from `RÖKSKÅP_1`
```

You need to use quotes, the same way you need to use quotes to create the table.
