### ISSUE TITLE
Integer divide by zero

### ISSUE THREAD

**Issue by yd1261137568** [ClickHouse/ClickHouse#7344]
Error is always reported when starting the server
![image](https://user-images.githubusercontent.com/33176197/66890769-c31fca80-f019-11e9-9759-de406da52120.png)

**Comment by yd1261137568** [comment]
Execute the command 'show tables' on the client, and the server reports an error

**Comment by alexey-milovidov** [comment]
What version of ClickHouse do you use? Did you build your own fork of ClickHouse?

Hint: divizion by zero in std::unordered_map in gcc's standard library happens if someone was clobbered FPU state (e.g. using MMX instruction set).

**Comment by yd1261137568** [comment]
I use version 19.4.1.At present, the problem has been solved by upgrading the version.The upgraded version is 19.5.3.1

**Comment by alexey-milovidov** [comment]
Ok. It was a bug in simdjson library, fixed long time ago:
https://github.com/lemire/simdjson/issues/169

**Comment by yd1261137568** [comment]
Well, thank you
