### ISSUE TITLE
KafkaEngine: Polled offset INVALID after upgrade

### ISSUE THREAD

**Issue by xmariachi** [ClickHouse/ClickHouse#7348]
**Describe the bug or unexpected behaviour**
After rolling upgrade from `yandex/clickhouse-server:19.13.3.26` to `yandex/clickhouse-server:19.15.3.6`, several tables from different `ReplicatedReplacingMergeTree` are showing these errors on logs, and not showing any more data on them. For all partitions these messages are shown: 

```
2019.10.16 07:44:36.507453 [ 8 ] {} <Trace> StorageKafka (customers_kafka): Polled offset INVALID (topic: customers-0.0.1, partition: 0)
...
2019.10.16 07:44:36.507459 [ 8 ] {} <Trace> StorageKafka (customers_kafka): Polled offset INVALID (topic: customers-0.0.1, partition: 63)
```
However, consumer groups show no lag, so they are being advanced in Kafka Engine table.
There are many tables setup like this. In one database, 5/13 tables show this behaviour, in another database 1/13 tables do.

Set up is a KafkaEngine table, then a Materialized View that consumes from it and placing records into a distributed table that spans over `ReplicatedReplacingMergeTree` table.

2 servers, 1 shard each.

**How to reproduce**
Build that setup with many tables and do a rolling upgrade.

**Expected behavior**
It should keep consuming normally from where it left off before the rolling upgrade.

**Comment by filimonov** [comment]
Actually it's not an error, it's just a trace info.
Nevertheless it is confusing

**Comment by xmariachi** [comment]
It seems to be related, because it is showing it for those KafkaEngine tables that are consuming (offsets being advanced) but not inserting. 

But whether or not it is related, the issue stands. I see in the migration changelog that there is this entry related to KafkaEngine. May it be related? 

Every message read from Kafka is inserted atomically. This resolves almost all known issues with Kafka engine. [#6950](https://github.com/ClickHouse/ClickHouse/pull/6950)

**Comment by filimonov** [comment]
> It seems to be related, because it is showing it for those KafkaEngine tables that are consuming (offsets being advanced) but not inserting, though not for others.
> 
> But whether or not it is related, the issue stands. I see in the migration changelog that there is the entry below related to KafkaEngine. May it be related?
> 
It comes from that  
https://github.com/ClickHouse/ClickHouse/commit/5851316742794665b6c559d0f886cbe302782eb5

I didn't change that part of code, but add few debug prints (including you mention)

**Comment by abyss7** [comment]
It's really is just tracing message, and INVALID - is some internal rdkafka value.
