### ISSUE TITLE
Partition key convert to toYYYYMM(Date) when using MergeTree(partition_key, sort_key, 8192) to create table

### ISSUE THREAD

**Issue by awpengfei** [ClickHouse/ClickHouse#7349]
Partition key convert to `toYYYYMM(Date)` when using `MergeTree(partition_key, sort_key, 8192)` to create table, and the part directory is `20191016_20191016_1_1_0`.
```SQL
CREATE TABLE z_t1 (d Date, uid UInt32) ENGINE = MergeTree(d, (d, uid), 8192);
SELECT name, partition_key FROM system.tables WHERE name='z_t1';
INSERT INTO TABLE z_t1 VALUES ('2019-10-16', 111);
```
name | partiton_key
---|---
z_t1 | toYYYYMM(d)

But when using `MergeTree() PARTITION BY partition_key ORDER BY sort_key`, it works correctly. The part directory is `20191016_1_1_0`.
```SQL
CREATE TABLE z_t2 (d Date, uid UInt32) ENGINE = MergeTree() PARTITION BY d ORDER BY (d, uid);
SELECT name, partition_key FROM system.tables WHERE name='z_t2';
INSERT INTO TABLE z_t2 VALUES ('2019-10-16', 111);
```
name | partiton_key
---|---
z_t2 | d

**Comment by millin** [comment]
Not a bug.

```sql
CREATE TABLE z_t1 (d Date, uid UInt32) ENGINE = MergeTree(d, (d, uid), 8192);
```
This format for creating table is outdated and doesn't support custom partition key.
It only allow to define Date column for default key format, that is `toYYYYMM(Date)`.
