### ISSUE TITLE
DB::Exception: Window function count() OVER ()  is found in GROUP BY in query. (ILLEGAL_AGGREGATION)

### ISSUE THREAD

**Issue by ywangtht** [ClickHouse/ClickHouse#73501]
It does not work in version 24.11.1.2557 (official build)

**Describe what's wrong**

> count() over () with GROUP BY ALL does not work.
> It works if changed to GROUP BY uid
> It works in version 23.8

> A link to reproducer in [https://fiddle.clickhouse.com/9fc65860-bc31-4509-a9b8-038b035fa5b3]

**Does it reproduce on the most recent release?**
yes

CREATE TABLE users (uid Int16, name String, age Int16) ENGINE=Memory;

INSERT INTO users VALUES (1231, 'John', 33);
INSERT INTO users VALUES (6666, 'Ksenia', 48);
INSERT INTO users VALUES (8888, 'Alice', 50);

SELECT uid, count() over () FROM users group by ALL

Received exception from server (version 24.11.1):
Code: 184. DB::Exception: Received from localhost:9000. DB::Exception: Window function count() OVER () is found in GROUP BY in query. (ILLEGAL_AGGREGATION)
(query: SELECT uid, count() over () FROM users group by ALL)

**Comment by nikitamikhaylov** [comment]
`SET enable_analyzer=0` makes it work.
Also, replacing `ALL` to `uid, name, age` makes it work too: https://fiddle.clickhouse.com/12e0bc52-cb06-47d7-8dfd-fdde5d53bad1
