### ISSUE TITLE
UBSAN bad BFloat16 cast

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#73522]
**Describe the bug**
Converting a `BFloat16` value into `Int16` is out of range.

**How to reproduce**
Compile ClickHouse with UBSAN and run:
```sql
SET allow_experimental_bfloat16_type = 1;
SELECT (65535::BFloat16)::Int16;
```
UBSAN error:
```
base/base/../base/BFloat16.h:65:18: runtime error: 65280 is outside the range of representable values of type 'short'
```

**Comment by kssenii** [comment]
Seems the same https://s3.amazonaws.com/clickhouse-test-reports/73420/aa3027561be4e13613a10791e975de0f2c223ed4/ast_fuzzer__ubsan_.html

**Comment by geldot** [comment]
PR #72355 has a prospective fix for BFloat16 type checks, worth trying to see if it catches this case
