### ISSUE TITLE
New JSON datatype - can I query for metadata of subcolumns?

### ISSUE THREAD

**Issue by pakud** [ClickHouse/ClickHouse#73608]
### Question

I'm asking this query while using v24.11.1.2557

Query like below is very helpful when optimizing disk footprint of tables using regular data types:

```
SELECT name,type,formatReadableSize(data_compressed_bytes) AS size_compressed, formatReadableSize(data_uncompressed_bytes) AS size_raw, floor(data_uncompressed_bytes/data_compressed_bytes,2) as ratio, compression_codec from system.columns where table ='TABLE_NAME';
```

I've tried to find similar information but with breakdown of size for subcolumns introduced by the new JSON data type. Is it exposed in some way, or - for now - listing files in the local file system is the only way to go?

Thank you!

**Comment by Avogar** [comment]
> Is it exposed in some way, or - for now - listing files in the local file system is the only way to go?

Unfortunately right now there is no such information in system tables. But it's a good feature request. I will add it to the list of [imrovements](https://github.com/ClickHouse/ClickHouse/issues/68428).

**Comment by pakud** [comment]
thanks for considering implementation of it and great JSON datatype alltogether!
