### ISSUE TITLE
Add native Prometheus metrics endpoint

### ISSUE THREAD

**Issue by Nklya** [ClickHouse/ClickHouse#7369]
Hello.
I haven't found any related issue and decided to create a new feature request.
I think it's a good idea to implement native Prometheus metrics endpoint. So we don't need to use external exporters, which aren't supported and often don't work or deprecated. For example https://github.com/f1yegor/clickhouse_exporter

**Use case**
Prometheus is now the most popular open-source monitoring solution. Many products already implemented native Prometheus metrics. Even Nginx 😄 
I believe ClickHouse can do the same and add an optional metrics endpoint for Prometheus.

**Describe the solution you'd like**
A new option to enable **/metrics** endpoint with Prometheus metrics.

**Describe alternatives you've considered**
Only use exporters from the community. Which aren't in-sync with ClickHouse releases. For example, today we haven't any working exporer at all for new ClickHouse versions https://github.com/f1yegor/clickhouse_exporter/issues/39

* https://github.com/f1yegor/clickhouse_exporter - not maintained
* https://github.com/percona-lab/clickhouse_exporter - fork, but not updated too

So I found only one fork that is working with current ClickHouse atm https://github.com/ajardan/clickhouse_exporter

**Additional context**
None

**Comment by Vdimir** [comment]
As I understand ClickHouse have graphite support ([GraphiteWriter](https://github.com/ClickHouse/ClickHouse/blob/09f3d68f6e3adf74bd8106c6bb9532a4b9e3c82d/libs/libdaemon/include/daemon/GraphiteWriter.h#L15), [MetricsTransmitter](https://github.com/ClickHouse/ClickHouse/blob/4952c6bc65a42be52627ae0fdd66b3fa7d400c04/dbms/programs/server/MetricsTransmitter.h#L35))

Prometheus unlike Graphite uses pull strategy to get metrics. Possible solution is to use same method to retrieve metric values as `MetricsTransmitter` do, but serve results using  `HTTPHandler` like in [query server](https://github.com/ClickHouse/ClickHouse/blob/594c535bd419d153efe97bd9e93caef4b96cd692/dbms/programs/server/Server.cpp#L703)

Task seems interesting for me, I can try to start implementing it. But I'm not very familiar with Prometheus or ClickHouse internals. I think it is good to see any comments from someone from ClickHouse team.
