### ISSUE TITLE
cityHash64 returns negative value. 

### ISSUE THREAD

**Issue by ionkrutov** [ClickHouse/ClickHouse#73692]
Hi all. 

cityHash64() function return the negative value, but the returned value must be of type UInt64.

Version: 23.11.2.11

**How to reproduce**
```sql
SELECT cityHash64('AMR-WB/16000-6.60');
```
```bash
result: -5458793406395120989
```

**Expected behavior**

We expected to obtain a value in range [0, 2^64)

**Comment by den-crane** [comment]
It your JAVA? nodejs application.

https://fiddle.clickhouse.com/daa414c6-9d15-46d8-902c-1794eb860134

```
SELECT cityHash64('AMR-WB/16000-6.60')



   ┌─cityHash64('AMR-WB/16000-6.60')─┐
1. │            12987950667314430627 │ -- 12.99 quintillion
   └─────────────────────────────────┘
```

**Comment by ionkrutov** [comment]
Yes, it was Java. Thanks a lot!
