### ISSUE TITLE
Cannot insert into external disk

### ISSUE THREAD

**Issue by CafeParadiso** [ClickHouse/ClickHouse#73716]
OS: Ubuntu 22.04.3 LTS
ClickHouse server version 24.12.1.1614 (official build)

I've set a storage policy that points to an external disk
```
<clickhouse>
    <storage_configuration>
        <disks>
            <hdd>
                <type>local</type>
                <path>/media/mikejones/Elements/clickhouse/</path>
            </hdd>
        </disks>
        <policies>
            <hdd>
                <volumes>
                    <external>
                        <disk>hdd</disk>
                    </external>
                </volumes>
            </hdd>
        </policies>
    </storage_configuration>
</clickhouse>
```
When connecting to the db i can see the disk listed and its size recognized

```
default	/var/lib/clickhouse/	21.94 GiB	95.56 GiB	0.00 B
hdd	/media/mikejones/Elements/clickhouse/	1.75 TiB	1.82 TiB	0.00 B
```
I can see files created by clickhouse too inside the directory in the external disk.
I can properly create a table using the storage policy i defined
```
    CREATE TABLE IF NOT EXISTS num (
        adsh VARCHAR(50),
        PRIMARY KEY (adsh)
    )
    ENGINE=MergeTree
    SETTINGS storage_policy = 'hdd';`
```
But whenever i try to inset data into it I get this error 

`SQL Error [481] [07000]: Code: 481. DB::ErrnoException: Cannot set modification time to file: /media/mikejones/Elements/clickhouse/store/98b/98b5fc1a-1318-4372-8055-0ec22def1ea7/tmp_insert_all_7_7_0/: , errno: 1, strerror: Operation not permitted. (PATH_ACCESS_DENIED) (version 24.12.1.1614 (official build))
`
All users and groups have write permissions into this disk,clickhouse has already created several files and directories so what could be causing the issue?

**Comment by alexey-milovidov** [comment]
This happens if the operations on that disk are not possible for the `clickhouse` user.
This could also occur when using a limited filesystem, such as FAT32, exFAT, or NTFS, instead of ext4.

**Comment by CafeParadiso** [comment]
Thanks a lot I formated the disk to EXT4 and all seems to work properly!Maybe this detail could be included into this section of the [documentation](https://clickhouse.com/docs/en/operations/storing-data)
