### ISSUE TITLE
schema inference reintroduce parsing of dates with dots back

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/ClickHouse#73710]
**Describe the issue**
After improvement of inference made in https://github.com/ClickHouse/ClickHouse/pull/68382#discussion_r1874416938
ClickHouse now parse values like `2024.13.13` as String, instead of Date, like it was in before. 
Reason behind that is common strings with dots used for versions.

> I don't want to allow . delimiter because of cases like {"version" : "1.1.10"} that can be parsed as 2010-01-01 00:00:00. I faced this case during testing of new JSON type with public datasets

But i can imagine it's somewhat marginal use case (versions) compared to store dates like that.

Unfortunately, it's also wasn't labeled as breaking change.

**How to reproduce**

https://fiddle.clickhouse.com/896ef97d-5898-4aff-97d1-06113fc3d7c9

**Additional context**
It can be introduced under setting.

**Comment by alexey-milovidov** [comment]
Schema inference is provided as a courtesy, and if the results are not good enough for you - specify the exact schema as you want.

**Comment by alexey-milovidov** [comment]
A setting will be an overkill, we already have too many...

**Comment by UnamedRus** [comment]
> Schema inference is provided as a courtesy, and if the results are not good enough for you - specify the exact schema as you want.

Problem with such approach, that it basically does mean that it discourage people from using new releases(kind of opposite to message which you are trying to promote with "run bleeding edge(and report problems earlier)", not "altinity stable" ones) and particular features, as behavior of them will be changed by "developer convenience"  at any point of time. 

And cherry on top, is that it's not even mentioned as breaking change. 
It just, what happened with bitShift functions https://github.com/ClickHouse/ClickHouse/issues/65516

The funny thing here, that all (at least four of them) of those backward compat problems were discovered by **single team**, who just started testing upgrade to version 24.8. 
Why they weren't discovered earlier? Because people are slow in their approach to try new ClickHouse versions(again, opposite to what you are trying to promote) as there is steer number of such issues.
