### ISSUE TITLE
Cast to Enum with LIKE SEGV

### ISSUE THREAD

**Issue by PedroTadim** [ClickHouse/ClickHouse#73737]
**Describe the bug**
There seems to be an issue using an Enum cast for the LIKE operator with a random string.

**How to reproduce**
Run Fiddle: https://fiddle.clickhouse.com/f9fa6761-f36f-4348-8c60-a7ff7c892b79

UBSAN output:
```
src/Functions/FunctionsStringSearch.h:190:41: runtime error: member call on null pointer of type 'DB::ColumnVector<Int8>'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/Functions/FunctionsStringSearch.h:190:41
```

**Comment by alexey-milovidov** [comment]
Revert this immediately: https://github.com/ClickHouse/ClickHouse/pull/72732

**Comment by zhanglistar** [comment]
Fix is submitted.
