### ISSUE TITLE
Invalid protobuf format

### ISSUE THREAD

**Issue by SvetislavDobromirov** [ClickHouse/ClickHouse#73769]
### Question

Hello,

I am facing a problem and cannot resolve it.

In ClickHouse, I have a .proto schema like this:

`syntax = "proto3";
message Message {
    int32 value = 1;
}`

I am trying to send data from ClickHouse to Dart and Python, both of which use the same .proto schema. However, I receive the following bytecode:

Dart: [11, 8, 224, 252, 255, 255, 255, 255, 255, 255, 255, 1] (UInt8List)
Python: \x0b\x08\xe0\xfc\xff\xff\xff\xff\xff\xff\xff\x01 (ByteArray)
When I try to parse this data in Dart and Python, I get errors. In Dart, for example:

`InvalidProtocolBufferException: Protocol message end-group tag did not match the expected tag.`
A
fter researching, I found that the byte 11 (0x0b) might correspond to the start group wire type from Protobuf syntax proto2. This leads me to believe that ClickHouse might be generating data in the proto2 format instead of proto3, despite the schema specifying proto3.

Could you please help me understand this issue and provide a solution?

Thank you!

**Comment by den-crane** [comment]
Are you aware about the difference  Protobuf vs ProtobufSingle vs ProtobufList? 
https://clickhouse.com/docs/en/interfaces/formats#protobuf

I guess Dart and Python expect ProtobufSingle.

**Comment by SvetislavDobromirov** [comment]
yes......... THANKS!!!
