### ISSUE TITLE
max_execution_time=30 not real work。 clickhouse log show Timeout exceeded: elapsed 181.244368783 seconds, maximum: 30

### ISSUE THREAD

**Issue by linger000** [ClickHouse/ClickHouse#73771]
version 23.8.14.6

DB::Exception: Timeout exceeded: elapsed 181.244368783 seconds, maximum: 30. Stack trace:\n\n0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c624af7 in /usr/bin/clickhouse\n1. DB::Exception::Exception<double, double>(int, FormatStringHelperImpl<std::type_identity::type, std::type_identity::type>, double&&, double&&) @ 0x000000001130e422 in /usr/bin/clickhouse\n2. DB::ExecutionSpeedLimits::checkTimeLimit(Stopwatch const&, DB::OverflowMode) const @ 0x000000001130e340 in /usr/bin/clickhouse\n3. DB::PipelineExecutor::execute(unsigned long, bool) @ 0x00000000131974c1 in /usr/bin/clickhouse\n4. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<ThreadFromGlobalPoolImpl::ThreadFromGlobalPoolImpl<DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0>(DB::PullingAsyncPipelineExecutor::pull(DB::Chunk&, unsigned long)::$_0&&)::'lambda'(), void ()>>(std::__function::__policy_storage const*) @ 0x00000000131a4e0f in /usr/bin/clickhouse\n5. void* std::__thread_proxy[abi:v15000]<std::tuple<std::unique_ptr<std::__thread_struct, std::default_deletestd::__thread_struct>, void ThreadPoolImplstd::thread::scheduleImpl(std::function<void ()>, Priority, std::optional, bool)::'lambda0'()>>(void*) @ 0x000000000c7059e4 in /usr/bin/clickhouse\n6. start_thread @ 0x0000000000007dc5 in /usr/lib64/libpthread-2.17.so\n7. __clone @ 0x00000000000f621d in /usr/lib64/libc-2.17.so\n: While executing Remote. (TIMEOUT_EXCEEDED) (version 23.8.14.6 (official build))

**Comment by c-end** [comment]
@alexey-milovidov Could you point to a fix for this or explain why you think this is not possible anymore in more recent versions? We are hitting the exact same issue (a timeout exceeed error thrown much later than the actual timeout period) in 24.8 (with pretty much the same stack trace).
