### ISSUE TITLE
The merge task terminates after running for 30 minutes

### ISSUE THREAD

**Issue by biuboombiuboom** [ClickHouse/ClickHouse#73821]
# system.merges
![image](https://github.com/user-attachments/assets/d1b6856e-9554-42b2-b71e-6846dc1c5567)
![image](https://github.com/user-attachments/assets/3dad1906-69c9-45dc-b6b8-c7a1e1cf8579)
# log
2024.12.25 11:12:27.324353 [ 1426 ] {9046695f-d747-4b17-b393-3b51ba80372e} <Information>log_local: Remove 0 parts by covering them with empty 0 parts. With txn (1, 1, 00000000-0000-0000-0000-000000000000).
2024.12.25 11:12:27.324402 [ 1426 ] {9046695f-d747-4b17-b393-3b51ba80372e} <Information> log_local: Dropped partition with 0 parts by replacing them with new empty 0 parts. With txn (1, 1, 00000000-0000-0000-0000-000000000000)
2024.12.25 11:42:02.729805 [ 1427 ] {3f353c50-95a4-45b0-9539-a3a620649c25} <Information> log_local: Remove 0 parts by covering them with empty 0 parts. With txn (1, 1, 00000000-0000-0000-0000-000000000000).
2024.12.25 11:42:02.729839 [ 1427 ] {3f353c50-95a4-45b0-9539-a3a620649c25} <Information> log_local: Dropped partition with 0 parts by replacing them with new empty 0 parts. With txn (1, 1, 00000000-0000-0000-0000-000000000000)

**Comment by den-crane** [comment]
Clickhouse can cancel merges if drop partition is run against the table. 
https://github.com/ClickHouse/ClickHouse/issues/63586#issuecomment-2107266482

**Comment by biuboombiuboom** [comment]
> Clickhouse can cancel merges if drop partition is run against the table. [#63586 (comment)](https://github.com/ClickHouse/ClickHouse/issues/63586#issuecomment-2107266482)

I found a job that periodically performs partition deletion operations.
