### ISSUE TITLE
Materialized View unable to SELECT data mixed with null on Nullable fields

### ISSUE THREAD

**Issue by xmariachi** [ClickHouse/ClickHouse#7382]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**

Version: Server: 19.5.3
```
CREATE TABLE test.btest1 (`a` String, `b` Nullable(String)) ENGINE = MergeTree ORDER BY a SETTINGS index_granularity = 8192
CREATE TABLE test.btest2 (`a` String, `d` Nullable(DateTime('UTC'))) ENGINE = MergeTree ORDER BY a SETTINGS index_granularity = 8192 
CREATE MATERIALIZED VIEW test.bmv TO test.btest2 (`a` String, `d` Nullable(DateTime('UTC'))) AS SELECT a, if(isNull(b), NULL, toDateTime(toDateTime(substring(b, 1, 19), 'UTC'))) AS d FROM test.btest1

insert into btest1 (a, b)  values ('a', '2019-10-06T00:00:00.000Z')
Ok.

SELECT *
FROM btest2

┌─a─┬───────────────────d─┐
│ a │ 2019-10-06 00:00:00 │
└───┴─────────────────────┘

insert into btest1 (a, b)  values ('a', null)
Received exception from server (version 19.5.4):
Code: 41. DB::Exception: Received from clickhouse:9000. DB::Exception: Cannot parse datetime: Cannot parse DateTime('UTC') from String: while pushing to view test.bmv.


SELECT 
    b, 
    isNull(b), 
    if(isNull(b), NULL, toDateTime(substring(b, 1, 19), 'UTC'))
FROM btest1

┌─b────────────────────────┬─isNull(b)─┬─if(isNull(b), NULL, toDateTime(substring(b, 1, 19), 'UTC'))─┐
│ 2019-10-06T00:00:00.000Z │         0 │                                         2019-10-06 00:00:00 │
└──────────────────────────┴───────────┴─────────────────────────────────────────────────────────────┘
↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.5.4):
Code: 41. DB::Exception: Received from clickhouse:9000. DB::Exception: Cannot parse datetime: Cannot parse DateTime('UTC') from String. 

1 rows in set. Elapsed: 0.007 sec. 
```

Defining `btest1.b` as `DEFAULT NULL` shows the same problem. 

**Expected behavior**
Since both source table (btest1.b) and destination table (btest2.d) are nullable, and the mv `bmv` checks for null value coming in with an `if`, the function should return null and place it into the `btest2.d` field. The SELECT last shown should print both lines, the second one with `null` in the third column.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/1562

**Comment by xmariachi** [comment]
I see, thanks. Since this is not a numerical operation, I'm not finding a workaround for my case like the ones in #1562.

However, I see a discrepancy on how the null values are treated in a simple select as opposed to the select in the materialized view: 

This function in a simple select does not throw any exception when applied a null value(i.e. application of the critical function to a null value): 

```
SELECT toDateTime(substring(NULL, 1, 19), 'UTC')

┌─toDateTime(substring(NULL, 1, 19), 'UTC')─┐
│ ᴺᵁᴸᴸ                                      │
└───────────────────────────────────────────┘

1 rows in set. Elapsed: 0.003 sec. 
```
So, the calculation returns `null`, and there are no errors or stack traces in the logs. 

However, when the materialized view processes a null value from the input table ( a Nullable(DateTime('UTC')), which gets inserted as `null` ) applying this same function over the field, then it breaks by the message seen in the original post.

Where does this difference come from, and why does it happen? The destination table has a nullable type: `Nullable(DateTime('UTC'))` so it should be able to insert null there.

**Comment by filimonov** [comment]
```
if(isNull(b), 
  NULL,
  toDateTime(substring(ifNull(b, '0000-00-00 00:00:00'), 1, 19), 'UTC'))
```

**Comment by xmariachi** [comment]
Thanks, it works! I see, we just need a "dummy" value here to bypass the limitation, used for not breaking calculation but that will never be actually used.

**Comment by filimonov** [comment]
Closing: duplicate, workaround exists.
