### ISSUE TITLE
insert into xx select * from xxx bug  with dbeaver

### ISSUE THREAD

**Issue by a819721810** [ClickHouse/ClickHouse#73872]
> Please make sure that the version you're using is still supported (you can find the list [here](https://github.com/ClickHouse/ClickHouse/blob/master/SECURITY.md#scope-and-supported-versions)).
24.4.1.2088 (official build)

INSERT INTO stock_base.daily
        SELECT *
        FROM stock_base.tu_daily
        WHERE date = '20241226' SETTINGS insert_deduplicate=0
where i exec in dbevaer，it only insert 4932 rows into daily.
where i exec in clickhouse-client, it whill insert 5109 rows into daily

tu_daily:
```
CREATE TABLE stock_base.tu_daily_local
(

    `code` String COMMENT '证券代码',

    `date` Date COMMENT '日期',

    `exg` UInt8 COMMENT '交易所类型,
\n\r\n\r\n1为深市，2为沪市',

    `open` Nullable(Float64) COMMENT '开盘价',

    `high` Nullable(Float64) COMMENT '最高价',

    `low` Nullable(Float64) COMMENT '最低价',

    `close` Nullable(Float64) COMMENT '收盘价',

    `pclose` Nullable(Float64) COMMENT '昨收价',

    `change` Nullable(Float64) COMMENT '涨跌额',

    `pct_chg` Nullable(Float64) COMMENT '涨跌幅(未复权)',

    `volume` Nullable(Int64) COMMENT '成交量(股)',

    `amount` Nullable(Float64) COMMENT '成交额',

    `hfq` Nullable(Float64) COMMENT '复权因子',

    `ztprice` Nullable(Float64) COMMENT '涨停价',

    `dtprice` Nullable(Float64) COMMENT '跌停价'
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{uuid}/{shard}',
 '{replica}')
PARTITION BY toYYYYMM(date)
PRIMARY KEY (date,
 code)
ORDER BY (date,
 code)
SETTINGS index_granularity = 8192

create table  stock_base.tu_daily on cluster cb_cluster
as stock_base.tu_daily _local
ENGINE = Distributed(cb_cluster, stock_base, tu_daily _local,hiveHash(code))
```

daily is like tu_daily

exec in dbeaver:
INSERT INTO stock_base.daily
SELECT *
FROM stock_base.tu_daily
WHERE date = '20241226' SETTINGS insert_deduplicate=0

![image](https://github.com/user-attachments/assets/2ac65841-dc9e-4179-86a3-64436b24a566)
![image](https://github.com/user-attachments/assets/141a68a3-0211-482c-ad22-95dfe86d7859)

delete:
![image](https://github.com/user-attachments/assets/2e33273c-de75-4558-9b1b-8a13ba3d1553)

insert by clickhouse-client:
![image](https://github.com/user-attachments/assets/8684e7dc-6556-40dd-8dec-059a0f20bbd0)

i checkout log, find diff in on shared:
normal:
![1735284912760](https://github.com/user-attachments/assets/db7b7f87-1986-47bd-abd0-b37379097490)
error:
![1735284951250](https://github.com/user-attachments/assets/e38aa131-a250-467d-bce0-548d4ae60941)

just less 177 rows.  but local_table is normal:
![1735284842446](https://github.com/user-attachments/assets/1cce3e5a-7d09-4574-a144-b1b428abd13c)

**Comment by a819721810** [comment]
INSERT INTO stock_base.daily
        SELECT *
        FROM stock_base.tu_daily
        WHERE date = '20241226'  
   without  SETTINGS insert_deduplicate=0 is normal , but cannot insert into daily. because it is deduplicate

**Comment by den-crane** [comment]
It's because dbeaver sets `max_result_rows = 200` (ResultSet fetch rows = 200)

You need to set it to 0
<img width="958" alt="Screenshot 2024-12-27 at 10 10 00 AM" src="https://github.com/user-attachments/assets/fa82bd2a-3bb8-4581-ab07-7aa2f13d2d52" />

**Comment by a819721810** [comment]
> It's because dbeaver sets `max_result_rows = 200` (ResultSet fetch size = 200 -> 0)
> 
> You need to set it to 0 <img alt="Screenshot 2024-12-27 at 10 10 00 AM" width="958" src="https://private-user-images.githubusercontent.com/19737682/398952824-fa82bd2a-3bb8-4581-ab07-7aa2f13d2d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNTk4OTUsIm5iZiI6MTczNTM1OTU5NSwicGF0aCI6Ii8xOTczNzY4Mi8zOTg5NTI4MjQtZmE4MmJkMmEtM2JiOC00NTgxLWFiMDctN2FhMmYxM2QyZDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA0MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZjk0YzNkYTFkY2QwNDJiYTJmNzg4Mjg5NDgwZWE4MGM1Nzk3MGQ0OGFmNmI4NDcxZmU2ODFiOGE2NGYyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QxHJIve8uChBWdF7jSsJGwz3lzSL-RHSN49-DJy-7Bo">
yes, i success, can i ask why ?
