### ISSUE TITLE
groupArrayMovingSum uses 255 length window

### ISSUE THREAD

**Issue by vincenzon** [ClickHouse/ClickHouse#7387]
I am using the groupArrayMovingSum and I want the default behavior described in the docs:

[The function can take the window size as a parameter. If left unspecified, the function takes the window size equal to the number of rows in the column.](https://clickhouse.yandex/docs/en/query_language/agg_functions/reference/#agg_function-grouparraymovingsum)

This example shows that the window is resetting after 255 elements, both when using the default (no window specified) and setting the window very large.

```
select aI, aS, aW
from (
   select 1 as g, groupArray(a) as aI, groupArrayMovingSum(a) as aS, groupArrayMovingSum(10000)(a) as aW
   from (
      select 1 as a
      from numbers(1,1000)
   )
   group by g
)
array join aI, aS, aW
```

Output of rows 250-259: 
```
| aI | aS | aW
250 | 1 | 251 | 251
251 | 1 | 252 | 252
252 | 1 | 253 | 253
253 | 1 | 254 | 254
254 | 1 | 255 | 255
255 | 1 | 0 | 0
256 | 1 | 1 | 1
257 | 1 | 2 | 2
258 | 1 | 3 | 3
259 | 1 | 4 | 4
```

Is this expected, that the max window size is 255?

**Comment by filimonov** [comment]
The type of the data you sum is uint8.
Try to repeat the same test with `select toUInt64(1) from numbers`

**Comment by vincenzon** [comment]
That did it! Thanks.
