### ISSUE TITLE
DDL background thread is not initialized

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7391]
hey , guys.

TO support clickhouse , I bought 11 machines each with 64 cores/256GB RAM/2TB SSD. they cost me about  230K us dollar.

Recently I am doing some testing. But `DDL background thread is not initialized` made me confused.

```
clickhouse version:  ClickHouse server version 19.15.3 revision 54426
os: centos 7.4
shards: 11 (yes lack of money, so 1 replica)
internal_replication = false
```

I don't know why:
```
CREATE TABLE IF NOT EXISTS test.user_log ON CLUSTER cluster_1st
(
    `dt` Date,
    `app_id` Int8,
    `app_version_name` String,
    `event_id` String
)
ENGINE = MergeTree('/clickhouse/tables/{layer}-{shard}/user_log', '{replica}')
PARTITION BY dt
ORDER BY (app_id, app_version_name)
SETTINGS index_granularity = 8192

Received exception from server (version 19.15.3):
Code: 49. DB::Exception: Received from localhost:9000. DB::Exception: DDL background thread is not initialized..

0 rows in set. Elapsed: 0.001 sec.
```

SOS~~~

**Comment by den-crane** [comment]
ON CLUSTER uses Zookeeper.

**Comment by Tasselmi** [comment]
If I make 5 shards each with 2 replica , and 1 shard with 1 replica. Is that ok? I have odd number of machine(11)


| |
梁凡
邮箱：tasselmi@yeah.net
|

签名由 网易邮箱大师 定制

On 10/20/2019 00:14, Denis Zhuravlev wrote:

ON CLUSTER uses Zookeeper.

**Comment by den-crane** [comment]
ON CLUSTER  is not related to replication. 
You can use 11 shards with MergeTree tables (without replication) but CH needs at least one small standalone Zookeeper for ON CLUSTER.

**Comment by Tasselmi** [comment]
> ON CLUSTER is not related to replication.
> You can use 11 shards with MergeTree tables (without replication) but CH needs at least one small standalone Zookeeper for ON CLUSTER.

THanks for your advice.

**Comment by Tasselmi** [comment]
> ON CLUSTER is not related to replication.
> You can use 11 shards with MergeTree tables (without replication) but CH needs at least one small standalone Zookeeper for ON CLUSTER.

hi，I want to make it clear:
if I use 11 shards each with 1 replica, to use `on cluster` I have to deploy a standalone zookeeper and set `internal_replication = true`, right?   ` internal_replication = true` is necessary？

**Comment by hodgesrm** [comment]
Shards and replicas are not connected.  If you have sharded tables there is no replication between shards--the data are disjoint.  You don't need zookeeper in this case unless you plan to add replicas later. 

Note that if you don't use replication and a host drops out for some reason, any data on that host will become unavailable.  With replicas you would still have at least one copy of the data.  Also, if you plan to add replicas later you may want to start with ReplicatedMergeTree engine on replicated tables.  This avoids a migration at a future date and gets you used to managing zookeeper from the start.

**Comment by den-crane** [comment]
> hi，I want to make it clear:
> if I use 11 shards each with 1 replica, to use `on cluster` I have to deploy a standalone zookeeper and set `internal_replication = true`, right? ` internal_replication = true` is necessary？or I only need a standalone zookeeper and set `internal_replication = false` also be fine?

Zookeeper server and internal_replication = false. 

Replicated tables need internal_replication = true but you use MergeTree tables so your cluster needs internal_replication = false.

**Comment by Tasselmi** [comment]
> Shards and replicas are not connected. If you have sharded tables there is no replication between shards--the data are disjoint. You don't need zookeeper in this case unless you plan to add replicas later.
> 
> Note that if you don't use replication and a host drops out for some reason, any data on that host will become unavailable. With replicas you would still have at least one copy of the data. Also, if you plan to add replicas later you may want to start with ReplicatedMergeTree engine on replicated tables. This avoids a migration at a future date and gets you used to managing zookeeper from the start.

Lack of money to deploy replicas. Machine is so fuck expensive and our data is huge amount...
Thanks for your advice. All you said is right, I can not agree more. Maybe I will deploy 2 replicas next year (buy more machines) and do a migration.

**Comment by Tasselmi** [comment]
> > hi，I want to make it clear:
> > if I use 11 shards each with 1 replica, to use `on cluster` I have to deploy a standalone zookeeper and set `internal_replication = true`, right? ` internal_replication = true` is necessary？or I only need a standalone zookeeper and set `internal_replication = false` also be fine?
> 
> Zookeeper server and internal_replication = false.
> 
> Replicated tables need internal_replication = true but you use MergeTree tables so your cluster needs internal_replication = false.

ok, thanks.

**Comment by blinkov** [comment]
@Tasselmi, do you have any further questions?

**Comment by Tasselmi** [comment]
No thanks




| |
梁凡
邮箱：tasselmi@yeah.net
|

签名由 网易邮箱大师 定制

On 04/02/2020 00:54, Ivan Blinkov wrote:

@Tasselmi, do you have any further questions?
