### ISSUE TITLE
Does ClickHouse need us to create the index manually?

### ISSUE THREAD

**Issue by 564064202** [ClickHouse/ClickHouse#7399]
Does ClickHouse need us to create the index manually?What's will occur when we did not  create the index manually

**Comment by den-crane** [comment]
MergeTree table able to have only one index (primary key). Basically you cannot create a table without index. So when you create a MergeTree table you have to mention ORDER BY (primary key) section. This section sets rows order (all columns is sorted in that order).  The same time this creates sparsed index.

https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#selecting-the-primary-key


PS: Skip indexes have completely another nature  and they are not required. https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#table_engine-mergetree-data_skipping-indexes .

**Comment by 564064202** [comment]
Thansk sir,I mean:
does ClickHouse need us create index just like every  mysql query

**Comment by den-crane** [comment]
CH is a columnar database. Such databases have another nature. They don't require indexes for each query. But you should chose the main index (PRIMARY KEY) (TABLE ORDER) wisely before you create a table. When the table is created the index cannot be changed.

https://clickhouse.yandex/docs/en/operations/table_engines/#mergetree

**Comment by 564064202** [comment]
thank you sir.
