### ISSUE TITLE
data replication.

### ISSUE THREAD

**Issue by anilxoxo** [ClickHouse/ClickHouse#7400]
I am using two instances of CH using docker. Both CH is connected with one zookeeper. I created a table using ReplicatedMergeTree engine in CH1 . But I am able to see the same table in CH2 why??
My aim is to replicate the table.

**Comment by den-crane** [comment]
>But I am able to see the same table in CH2 why??

able or unable?

**Comment by anilxoxo** [comment]
Unable.

**Comment by filimonov** [comment]
Please check 
https://clickhouse.yandex/tutorial.html
especially section **ClickHouse deployment to cluster**

**Comment by blinkov** [comment]
@anilxoxo, do you have any further questions?
