### ISSUE TITLE
install ClickHouse is successful but start server failed

### ISSUE THREAD

**Issue by hungryforit** [ClickHouse/ClickHouse#7403]
First use
根据官方网站的CentOS的quick start进行安装成功:
sudo yum install yum-utils
sudo rpm --import https://repo.yandex.ru/clickhouse/CLICKHOUSE-KEY.GPG
sudo yum-config-manager --add-repo https://repo.yandex.ru/clickhouse/rpm/stable/x86_64
sudo yum install clickhouse-server clickhouse-client

但是,执行到命令$ sudo /etc/init.d/clickhouse-server start时报错:
[root@master ~]# /etc/init.d/clickhouse-server start
Start clickhouse-server service: Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
Changing owner of [/var/log/clickhouse-server/*] to [clickhouse:clickhouse]
chown: cannot access ‘/var/log/clickhouse-server/*’: No such file or directory
Changing owner of [/var/log/clickhouse-server] to [root:clickhouse]
UNKNOWN
[root@master ~]# 

我在我的CentOS服务器的/var/log目录下查看,确实没有自动生成clickhouse-server文件夹,于是我执行命令$ mkdir clickhouse-server 手动生成了clickhouse-server文件夹,想让程序能够找到,解决这个错误.但是,没有作用.

想知道哪里出现了问题?

**Comment by RaulGuo** [comment]
日志目录下的error日志里有什么？如果日志目录下什么也没有，说明是日志目录的权限的问题。

**Comment by zhang2014** [comment]
看起来像是权限问题，请确保log、data目录有足够的权限启动。
最好使用英语来描述issues（可以方便其他遇到相似问题的人查找）

**Comment by blinkov** [comment]
@hungryforit, do you have any further questions?
