### ISSUE TITLE
XOR function returns 255 instead of 1

### ISSUE THREAD

**Issue by ishirav** [ClickHouse/ClickHouse#7404]
As stated in the documentation, the xor function is supposed to return 0 or 1. Instead of 1 it returns 255:
```
SELECT xor(1, 0)

┌─xor(1, 0)─┐
│       255 │
└───────────┘
```
ClickHouse server version 19.15.3 revision 54426

**Comment by amosbird** [comment]
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Functions/FunctionsLogical.h#L87

And perhaps you want `bitXor`?

**Comment by alexey-milovidov** [comment]
Now it works as you expect.
