### ISSUE TITLE
Cannot detect left and right JOIN keys. JOIN ON section is ambiguous.

### ISSUE THREAD

**Issue by dpogorelov** [ClickHouse/ClickHouse#7406]
Hi,
I have the following version: 19.15.2.2 (official build)
Dunno if it's a bug or not but having such a table:

`create table demo.abc2 (key int, name String)  engine MergeTree ORDER BY key;
insert into clickhouse.demo.abc2 values (1, 'aaa'),(2, 'bbb'),(3, 'ccc');`

and running the query:

`select * from clickhouse.demo.abc2 a left join clickhouse.demo.abc2 b on 1 = 1;` 
("on 1 = 1" is actually "on true" - it can be just re-written as "1 = 1" condition)
I get the error message: Cannot detect left and right JOIN keys. JOIN ON section is ambiguous.

Though the same query works with usual join, it doesn't work only for left/right joins.
In postgresql/mysql/oracle/mssql the query works without any problems.

**Comment by 4ertus2** [comment]
What do you mean saying "query works with usual join"? It should not work for all join except CROSS JOIN. ClickHouse support equi-join algorithm that means you need columns from different tables in each ON clause.

There's related discussion on stackoverflow that sayes PG executes such JOINS as CROSS JOIN and some special LEFT JOIN https://stackoverflow.com/questions/35374860/join-select-ue-on-1-1

For now ClickHouse supports rewrite INNER JOIN with inequality into CROSS JOIN. It's not clear if we need support described JOIN convertions. You can use CROSS JOIN directly.

**Comment by dpogorelov** [comment]
> What do you mean saying "query works with usual join"?
ah, sorry, my fail, actually it's being rewritten to:
`SELECT t0.key, t0.name, t1.key, t1.name FROM demo.abc2 as t0, demo.abc2 as t1`

> For now ClickHouse supports rewrite INNER JOIN with inequality into CROSS JOIN. It's not clear if we need support described JOIN convertions. You can use CROSS JOIN directly.
ok, got it, this is what I expected to see in your reply.
