### ISSUE TITLE
What is the best way to manage schema on cluster?

### ISSUE THREAD

**Issue by svladykin** [ClickHouse/ClickHouse#7408]
Just use `ON CLUSTER` and run scripts against a single node?
Can anyone recommend tools for schema updates that work well with Clickhouse, maybe something like https://flywaydb.org/documentation/command/migrate?

**Comment by filimonov** [comment]
https://github.com/flyway/flyway/pull/2166

https://github.com/filimonov/ClickHouse/wiki/Clickhouse-database-schema-migrations 

And use ON CLUSTER queries. 

It will not work if you will try to add new replica with incremental schema (to add new replica you need to use on that the latest schema, not incremental changes).

**Comment by svladykin** [comment]
@filimonov 
Thanks a lot! 
Tried `migrate`, it looks promising but it seems that it does not support inserts.
How do you prepopulate the database with some initial data?
