### ISSUE TITLE
user not correct 

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7409]
`t_md_test_data_bz_ctdb_dis` is a distributed table.  I login a client on one of my cluster using `user test and it's passwd` and execute a query below:
```
SELECT *
FROM t_md_test_data_bz_ctdb_dis
```

But I got an exception:
```
Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.15.3):
Code: 194. DB::Exception: Received from localhost:9000. DB::Exception: Received from ubs-prd-10-193-96-149:9000. DB::Exception: Password required for user default.
```
user config file `test.xml` is under directory `users.d` at each machine on cluster.
So when I execute a distributed query, isn't it `user test` ? where user default come from?

**Comment by den-crane** [comment]
>where user default come from?

Distributed table uses the user/password you described with cluster definition

https://clickhouse.yandex/docs/en/operations/table_engines/distributed/
 ```
    </remote_servers>
       <test>
            <shard>
                <replica>
                    <host>host</host>
                    <port>port</port>
                    <user>username</user>
                    <password>password</password>
                </replica>
            </shard>
        </test>
    </remote_servers>
```

**Comment by Tasselmi** [comment]
> > where user default come from?
> 
> Distributed table uses the user/password you described with cluster definition
> 
> https://clickhouse.yandex/docs/en/operations/table_engines/distributed/
> 
> ```
>    <remote_servers>
>       <test>
>            <shard>
>                <replica>
>                    <host>host</host>
>                    <port>port</port>
>                    <user>username</user>
>                    <password>password</password>
>                </replica>
>            </shard>
>        </test>
>    </remote_servers>
> ```

This makes me so confused.
User config file is on every machine in the cluster, why not just use that config file?
If I login by user a then the cluster should communicates with user a, and so on user b... but not a constant user name~
Table is distributed , and the user config file is also distributed, that is so simple and reasonable.

**Comment by den-crane** [comment]
Does not matter. Works as documented. Not a bug.

**Comment by Tasselmi** [comment]
> Does not matter. Works as documented. Not a bug.

I think this might be a problem.
If I set user a with profile a(`max_memory_usage=x`), and user b with profile b(`max_memory_usage=y`).
If we use user b to communicate between cluster machines and if we login  with user a.
Then user a got the setting of user b , this will make resource restriction useless .
We want to control access rights and resource usage by user.

**Comment by den-crane** [comment]
It will not.
A current session's state of max_memory_usage (and all other settings) will be propagated through distributed from a node initiator.

**Comment by Tasselmi** [comment]
> It will not.
> A current session's state of max_memory_usage (and all other settings) will be propagated through distributed from a node initiator.

anyway, you suggest us not to specify password in plaintext, but this config method explode password of default user to all of the employees. This is not a safe approach.  I insist on that user password should be placed in each node(`users.d dir or users.xml file`) and not in plaintext.

**Comment by den-crane** [comment]
I suggest nothing.

You have options: 
* plain password in remote_servers for Distributed table
* passwordless auth with IP address restrictions for passwordless user.

https://github.com/ClickHouse/ClickHouse/issues/5823
https://github.com/ClickHouse/ClickHouse/issues/5441
https://github.com/ClickHouse/ClickHouse/issues/2290

**Comment by Tasselmi** [comment]
> I suggest nothing.
> 
> You have options:
> 
> * plain password in remote_servers for Distributed table
> * passwordless auth with IP address restrictions for passwordless user.
> 
> #5823
> #5441
> #2290

ok, thanks.   I will choose the second one.

**Comment by smallYellowCat** [comment]
@den-crane  
 if i don't config user and password in replica tag, query distribute table will get error **_Authentication failed: password is incorrect or there is no user with such name_**

Why does clickhouse have this limitation? is it each clickhouse server can set different user names and passwords independently, so does it need to know the user name and password information of each node when performing distributed queries? is it this reason?
