### ISSUE TITLE
how to config multiple storage

### ISSUE THREAD

**Issue by lzy305** [ClickHouse/ClickHouse#7410]
Today, I editor config.xml in order to support multi storage. 

[config.txt](https://github.com/ClickHouse/ClickHouse/files/3751540/config.txt)

then restart clickhouse . It is ok.

but I found that it does not take effect.

1. select * from system.disks

result: default,/data/clickhouse/data/,207526051840,1081114603520,0

2. select * from system.storage_policies

default,default,1,{default},0,0

**Comment by filimonov** [comment]
<disks> and <policies> should all go to <storage_configuration> subsection. 

Here is the working sample: https://github.com/ClickHouse/ClickHouse/blob/4575b6e4ffb35c9d613fd3fe8b6a6cabd2bbaec6/dbms/tests/integration/test_multiple_disks/configs/config.d/storage_configuration.xml

**Comment by alexey-milovidov** [comment]
https://clickhouse.github.io/clickhouse-presentations/meetup30/new_features/#12
