### ISSUE TITLE
Schema change in system.tables

### ISSUE THREAD

**Issue by rochoa** [ClickHouse/ClickHouse#7432]
I just realized that the schema of the `system.tables` table has changed recently (https://github.com/ClickHouse/ClickHouse/pull/6489), the `data_path` column is gone and a new `data_paths` column exists now.

This is already in the latest stable releases, but the documentation is not reflecting the new schema, neither is documented in the changelog.

Wouldn't you consider this a breaking/backwards-incompatible change?

**Comment by alexey-milovidov** [comment]
We don't enforce backward compatibility for system tables. But it should be mentioned in changelog and documentation.

**Comment by rochoa** [comment]
Understood. Thanks for the clarification.

**Comment by abraithwaite** [comment]
> We don't enforce backward compatibility for system tables. But it should be mentioned in changelog and documentation.

Why?  We depend on these tables for operations and system management.  It is not a nice experience to have those break suddenly upon upgrade.  Even in testing, where we discovered it, it requires additional toil to upgrade unnecessarily.

At the very least, it should be mentioned in the release notes.

**Comment by alexey-milovidov** [comment]
Ok, we should note all the changes in changelog as "backward incompatible changes".

Regarding the question of “why,” we simply do not have practice to keep them backward compatible. Maybe we should.
