### ISSUE TITLE
Cannot convert empty string in an Enum8 to Protobuf enum

### ISSUE THREAD

**Issue by champtar** [ClickHouse/ClickHouse#7438]
**Describe the bug or unexpected behaviour**
I have some Enum8 with empty strings, I cannot format them as protobuf

**How to reproduce**
* Which ClickHouse server version to use
19.15.3.6

* Which interface to use, if matters
CLI client

* `CREATE TABLE` statements for all tables involved
```
clickhouse-client --password=default --query="CREATE TABLE bug_enum (e Enum8('A'=0, 'B'=1, 'C'=2, ''=3)) ENGINE = Memory;"
clickhouse-client --password=default --query="INSERT INTO bug_enum VALUES ('');"
clickhouse-client --password=default --query="INSERT INTO bug_enum VALUES ('A');"
cat > bug_enum.proto <<'EOF'
syntax = "proto2";

enum tstenum {
  A = 0;
  B = 1;
  C = 2;
  EMPTY = 3;
}

message tst {
  required tstenum e = 1;
}
EOF
```

**Expected behavior**
It works ;)
```
# clickhouse-client --password=default --query="SELECT * FROM bug_enum WHERE e = 'A' FORMAT Protobuf" --format_schema='bug_enum.proto:tst' | hexdump -C
00000000  02 08 00                                          |...|
00000003
```

**Error message and/or stacktrace**
```
# clickhouse-client --password=default --query="SELECT * FROM bug_enum WHERE e = '' FORMAT Protobuf" --format_schema='bug_enum.proto:tst' | hexdump -C
Code: 436. DB::Exception: Could not convert value '3' to protobuf type 'enum' (field: e)
```

**Comment by champtar** [comment]
Actually clickhouse match the Enum8 string to Protobuf enum string, so not sure how to handle that except just using uint32

**Comment by alexey-milovidov** [comment]
@vitlibar Is it possible to fix? Should we look at the Enum indices instead of names?
If it's non trivial and too cumbersome - then just close this issue.

**Comment by vitlibar** [comment]
The current code matches the enum types by the names of the constants.
But there are other options: enum can be automatically converted to integer or string and vice versa. So the following script should work:

```
clickhouse-client --password=default --query="CREATE TABLE bug_enum (e Enum8('A'=0, 'B'=1, 'C'=2, ''=3)) ENGINE = Memory;"
clickhouse-client --password=default --query="INSERT INTO bug_enum VALUES ('');"
clickhouse-client --password=default --query="INSERT INTO bug_enum VALUES ('A');"
cat > bug_enum.proto <<'EOF'
syntax = "proto2";

message tst {
  required int32 e = 1;
}
EOF
```

**Comment by vitlibar** [comment]
The constants of a[Enum data type](https://clickhouse.tech/docs/en/sql-reference/data-types/enum/) are now matched to constants of a [protobuf enum](https://developers.google.com/protocol-buffers/docs/proto3?hl=ru#enum) first by name (case insensitively), then by value. So this example now works, and test was added (see `00825_protobuf_format_enum_mapping`).
