### ISSUE TITLE
ReplicatedReplacingMergeTree/ReplicatedCollapsingMergeTree

### ISSUE THREAD

**Issue by aditi6622** [ClickHouse/ClickHouse#7445]
Like we can convert Replacing Merge tree to Merge Tree, in similar way is it possible to convert Replicated Replacing merge tree to Replacing merge tree, and same with,  is conversion possible from Replicated Collapsing Merge Tree to Collapsing Merge tree.

**Comment by filimonov** [comment]
All tables from mergetree family use the same on-disk format. And parts can be moved between different variants of engines. Of course you still need to have requirement column set.
