### ISSUE TITLE
Broken pipe cause server exit

### ISSUE THREAD

**Issue by tencupofkaiwater** [ClickHouse/ClickHouse#7449]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
OS:  4.19.66-gentoo-ks #1 SMP Tue Sep 10 15:40:33 CST 2019 x86_64 Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz GenuineIntel GNU/Linux

Myself compile the source code.
 
**How to reproduce**
when much more client (10~40) to connection server cluster(3 computer), and execute insert data SQL,  then Ctrl + C client process。Any one clickhouse-server process exit in  cluster .

* Which ClickHouse server version to use
version 19.15.2.2 

* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
clickhouse-server process exit in cluster

**Error message and/or stacktrace**
2019.10.23 17:48:13.578856 [ 109 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer (version 19.15.2.2                                  
2019.10.23 17:48:13.584562 [ 137 ] {} <Fatal> BaseDaemon: ########################################
2019.10.23 17:48:13.584719 [ 137 ] {} <Fatal> BaseDaemon: (version 19.15.2.2) (from thread 136) Received signal Broken pipe (13).                                                                             
2019.10.23 17:48:13.584779 [ 137 ] {} <Fatal> BaseDaemon:
2019.10.23 17:48:13.584856 [ 137 ] {} <Fatal> BaseDaemon: Stack trace: 0x7fbae54ce982
2019.10.23 17:48:13.585024 [ 137 ] {} <Fatal> BaseDaemon: 4. 0x7fbae54ce982 ? /usr/lib64/libunwind.so.8.0.1 

**Additional context**

**Comment by filimonov** [comment]
It look like you're build differs from standard.
Can you show your system.build_options?
Can you try to reproduce the problem with official build?

1) Can you please show how excatly do you insert data
2) Can you please give a full stacktrace from logs. Also it would be cool if you will 'decode' addresses using `addr2line -afiCe /usr/bin/clickhouse 0x7fbae54ce982 (and other addresses from stacktrace)`

**Comment by tencupofkaiwater** [comment]
-O2 -pipe -g

**Comment by tencupofkaiwater** [comment]
2019.10.23 17:37:42.936693 [ 134 ] {} <Fatal> BaseDaemon: ########################################
2019.10.23 17:37:42.936785 [ 134 ] {} <Fatal> BaseDaemon: (version 19.15.2.2) (from thread 101) Received signal Broken pipe (13).
2019.10.23 17:37:42.936828 [ 134 ] {} <Fatal> BaseDaemon: 
2019.10.23 17:37:42.936866 [ 134 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f05c79f7982
2019.10.23 17:37:42.937001 [ 134 ] {} <Fatal> BaseDaemon: 4. 0x7f05c79f7982 ? /usr/lib64/libunwind.so.8.0.1
2019.10.23 17:37:47.308801 [ 109 ] {} <Error> ServerErrorHandler: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (192.168.1.102:45972), Stack trace:

0. 0x7f05cb7021c1 StackTrace::tryCapture() /usr/lib64/libclickhouse.so.19.15.2.2
1. 0x7f05cb40f2f5 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/lib64/libclickhouse.so.19.15.2.2
2. 0x7f05cb28e21b ? /usr/lib64/libclickhouse.so.19.15.2.2
3. 0x7f05cb44c723 DB::TCPHandler::runImpl() /usr/lib64/libclickhouse.so.19.15.2.2
4. 0x7f05cb44cb5a DB::TCPHandler::run() /usr/lib64/libclickhouse.so.19.15.2.2
5. 0x7f05c77b1316 Poco::Net::TCPServerConnection::start() /usr/lib64/libPocoNet.so.60
6. 0x7f05c77b24b5 Poco::Net::TCPServerDispatcher::run() /usr/lib64/libPocoNet.so.60
7. 0x7f05c476ab5e Poco::PooledThread::run() /usr/lib64/libPocoFoundation.so.60
8. 0x7f05c4767348 Poco::ThreadImpl::runnableEntry(void*) /usr/lib64/libPocoFoundation.so.60
9. 0x7f05c780145a ? /lib64/libpthread-2.29.so
10. 0x7f05c7924ece clone /lib64/libc-2.29.so
 (version 19.15.2.2)

**Comment by alexey-milovidov** [comment]
Note that shared linking is not tested and not recommended for production usage.

**Comment by alexey-milovidov** [comment]
Can you provide full build scenario (all modifications to code and all CMake options) to reproduce this issue?

**Comment by tencupofkaiwater** [comment]
CMake options :  -O2 -pipe -g

Don't modify any code.

**Comment by alexey-milovidov** [comment]
`/usr/lib64/libPocoNet.so.60`

It means you are using a library from OS instead of `contrib`. It can only be enabled with custom CMake options and it is unsupported build variant.

**Comment by tencupofkaiwater** [comment]
I know what you mean,  will rebuild, thank you very much!!
