### ISSUE TITLE
Uniform tracking for queries and background processes.

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#7455]
(aka add merges to query_thread_log)

We want to be able to track sever metrics, such as IO or CPU utilization, in a uniform way across both queries and background processes such as merges. This may be helpful for example when debugging high IO utilization. Currently there are some rough metrics on merges in part_log, but no ProfileEvents like in query_thread_log.

Solving this task would consist of:
1. Logging more metrics (ProfileEvents-like) for background processes.
2. Storing them in a uniform way with query thread metrics (by adding to query_thread_log or maybe some other table).

**Comment by alexey-milovidov** [comment]
BTW, I'm Ok if query_log, query_thread_log, trace_log will be reused for background processes: merges, fetches, etc.

**Comment by nvartolomei** [comment]
Maybe it will suffice to add ProfileEvents column to system.part_log? merges, fetches, moves are already recorded to system.part_log.

**Comment by alexey-milovidov** [comment]
@nvartolomei Yes, it will be a good solution.

**Comment by nvartolomei** [comment]
#10316
