### ISSUE TITLE
how to develop UDF in clickhouse

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7467]
Is there any instructions or guide？

and I find that some functions like `arraySplit` `arrayCompact` is already in clickhouse's code area， how can I use them？when I use these functions， clickhouse-client throws exception:
`Unknown function arraySplit. Maybe you meant: ['arraySort','arraySlice']`

**Comment by filimonov** [comment]
About UDF - see #11

For now the only possible way to create custom function is just add the to ClickHouse codebase. 

There are currently some UDF-related concepts & ideas, so maybe UDF support will be added in further versions. 

arraySplit is added in 19.16, https://github.com/ClickHouse/ClickHouse/pull/7294

arrayCompact PR is not finished yet: https://github.com/ClickHouse/ClickHouse/pull/7328

**Comment by blinkov** [comment]
@Tasselmi, do you have any further questions?

**Comment by Tasselmi** [comment]
No, thanks




| |
梁凡
邮箱：tasselmi@yeah.net
|

签名由 网易邮箱大师 定制

On 04/02/2020 00:54, Ivan Blinkov wrote:

@Tasselmi, do you have any further questions?
