### ISSUE TITLE
Default Part size for mutations

### ISSUE THREAD

**Issue by aditi6622** [ClickHouse/ClickHouse#7468]
when we do mutation, the default maximum for part size is 150GB. Is it possible to change this size, if yes kindly throw some light on same. how do we do it, kindly share the procedural details.
How will affect the mutation if we increase or decrease the size of it?

**Comment by filimonov** [comment]
You are looking for `<merge_tree>` setting called `max_bytes_to_merge_at_max_space_in_pool`

**Comment by alexey-milovidov** [comment]
@filimonov Are you sure that this setting should be used to limit mutations?

**Comment by alesapin** [comment]
Maximum part size `max_bytes_to_merge_at_max_space_in_pool` doesn't related to mutations. Actually mutations can only decrease the size of the part, so they don't perform any size checks for result part size (only checks for available space on disk). 

Changing maximum parts size is not recommended, but you can do it with query:
```
ALTER TABLE table_name MODIFY SETTING max_bytes_to_merge_at_max_space_in_pool = 200 * 1024 * 1024 * 1024
```

**Comment by alesapin** [comment]
If you have any questions, just reopen.
