### ISSUE TITLE
Use system thread id for logging.

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#7477]
Text logs and query_thread_log use the internal thread id, while sanitizer reports or segfaults report the system thread id. Finding out which ids correspond to which is currently impossible.

As a solution, we might just use system thread id for logging.

For the reference, see `ExtendedLogMessage::getFrom` and `getThreadNumber`.

**Comment by alexey-milovidov** [comment]
Approved.

You should replace thread_id with system thread id everywhere and get rid of the columns `os_thread_id` in system tables.

**Comment by Vinatorul** [comment]
Hi! I want to work on this as my first issue.
Am I correct that I should replace `thread_number` assignment logic with `os_thread_id` one (for example [here](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Common/ThreadStatus.cpp#L37))?
Firstly I thought I can change `getThreadNumber`, but have found that `getThreadNumber` used not only in logging as it said in `getThreadNumber.h`, but also [here](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Storages/StorageBuffer.cpp#L346) and changind `getThreadNumber` could possibly break distribution.

**Comment by alexey-milovidov** [comment]
> Hi! I want to work on this as my first issue.

That's great!

> Am I correct that I should replace thread_number assignment logic with os_thread_id one (for example here)?

Yes.

> Firstly I thought I can change getThreadNumber, but have found that getThreadNumber used not only in logging as it said in getThreadNumber.h, but also here and changing getThreadNumber could possibly break distribution.

This is the minor case. In worst case it will just make Buffer a little slower, but probably the difference will be unnoticeable. You can replace it freely :)

**Comment by Vinatorul** [comment]
I'm not sure that I am doing everything well. As I found out - I can't change `getThreadNumber` to use `CurrentThread`. I can get rid of it in most places `getThreadNumber`, but I am not sure in changes like
`DB::writeBinary(getThreadNumber(), out);` to `DB::writeBinary(CurrentThread::get().thread_number, out);` (at `faultSignalHandler` in `BaseDaemon.cpp`), as I am not sure that `current_thread` will be initialized here. Or I should use `TaskStatsInfoGetter::getCurrentTID()` here?

**Comment by alexey-milovidov** [comment]
Let's use `TaskStatsInfoGetter::getCurrentTID()`. To avoid the cost of system call, we can merge https://github.com/ClickHouse/ClickHouse/pull/8276

**Comment by alexey-milovidov** [comment]
And maybe better to move the code around: move it inside `getThreadNumber()` and use it in `TaskStatsInfoGetter`.

**Comment by alexey-milovidov** [comment]
@Vinatorul Hi! How is it going?

**Comment by Vinatorul** [comment]
@alexey-milovidov Hi! Everything seems fine, I'll try to build it today and if everything will be ok - open a PR. Full build takes about 7 hours on my pc now :(

**Comment by alexey-milovidov** [comment]
Ok. BTW, you can send PR in advance and it will be built in our CI - we can fix all issues quickly.

**Comment by alexey-milovidov** [comment]
@Vinatorul Hi and happy new year! Hope you have success building the code?

**Comment by alexey-milovidov** [comment]
@Vinatorul Hi! How is it going?
I will happy to hear some news...

**Comment by alexey-milovidov** [comment]
Don't you mind if we steal this task?

**Comment by alexey-milovidov** [comment]
@Vinatorul is everything all right?
