### ISSUE TITLE
mysql_port + grafana = 💔

### ISSUE THREAD

**Issue by morozovsk** [ClickHouse/ClickHouse#7495]
![screen447](https://user-images.githubusercontent.com/1822063/67624273-31913380-f837-11e9-98d9-e2b6a9627ac0.png)
**Describe the bug or unexpected behaviour**

Не получается в графане построить дашборд, используя стандартный MySQL Data Source, потому что вероятно числа возвращаются строками.

**How to reproduce**
Обновил кликхаус до последней версии 19.15.3.6
Указал в конфиге <mysql_port>8124</mysql_port>
Подключился с помощью графаны (версия 6.3.5) (MySQL Data Source)

* Queries to run that lead to unexpected result
SELECT toUInt32(t) AS time, category AS metric, count(*) as value 
FROM test
GROUP BY category, t 
ORDER BY t

**Expected behavior**
Если использовать в графане CLICKHOUSE Data Source от VERTAMEDIA, то не работают алерты.
Решил использовать mysql_port в кликхаусе совместно со стандартным mysql датасурсом в графане, но видимо числовые данные от кликхауса приходят строками, поэтому в графане не получается создать дашборд.

**Error message and/or stacktrace**

> Invalid type for column time, must be of type timestamp or unix timestamp, got: string 1569082218

**Comment by yurriy** [comment]
Да, конвертация в типы MySQL не дописана, и является основной запланированной доработкой MySQL протокола. Ожидаемый срок: 2 недели.

**Comment by morozovsk** [comment]
Заработало начиная с версии 20.1.2.4. Большое спасибо!
Пример запроса:
```sql
SELECT
    toStartOfInterval(t, INTERVAL $__interval_ms/1000 second) AS time
    count() as value,
    level as metric
FROM error_log
WHERE t BETWEEN toDateTime($__unixEpochFrom()) and toDateTime($__unixEpochTo())
GROUP BY time, metric
ORDER BY time, metric desc
```
