### ISSUE TITLE
How does the Clickhouse find other column data?

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#7499]
When I run a query with where statement like `select * from tbl1 where col1 = 'CH' `, Clickhouse find other columns which correspond with `col1 = 'CH'`.

Unlike row-base DBMS, ClickHouse is column-base DBMS that saves data by column. Then How CH find other column data with same row?

Could you explain a process step by step that the ClickHouse finds other columns data?

**Comment by hczhcz** [comment]
The expression `col1 = 'CH'` will yield a "condition column" of boolean values. Physically, it is one or more memory blocks containing UInt8 values.
Then, we can perform a for-loop within the range of the row numbers. Let the row number to be "i", the i-th element in the condition column will indicate whether the i-th row is selected. If so, we will visit each column, grab the i-th element, and append it to the corresponding result column.

**Comment by chu1070y** [comment]
It`s very helpful. Thanks.
