### ISSUE TITLE
Threads control

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#7502]
When I use different index, The Clickhouse use different number of parallel threads(streams).

I can refer to the max_threads settings in clickhouse documents.

but, It is only for max_threads.

Is there any other ways to control thread number by different index?

**Comment by filimonov** [comment]
ClickHouse  can decrease a number of working threads below `max_threads` automatically if selected datasize  is small enough.

**Comment by chu1070y** [comment]
Is there any way to increase a number of working threads?

**Comment by filimonov** [comment]
```
set max_threads = 1000;
```
Can also be adjusted for particular user profile, of globally in default profile in users.xml

**Comment by chu1070y** [comment]
oh, I mean min_threads. sometimes CH work with only one thread. I want to know that Is there any way to improve query`s execution time with parallel threads.

**Comment by chu1070y** [comment]
Thanks
