### ISSUE TITLE
How to shutdown clickhouse instance ?

### ISSUE THREAD

**Issue by Myshiner** [ClickHouse/ClickHouse#7503]
First time to use clickhouse, how can i close or shutdown clickhouse ? Can only use "kill -9 pid" ?
Thx.

**Comment by filimonov** [comment]
Sending SIG_KILL with `kill` command will work but recommended way is 
```
systemctl stop clickhouse-server
```

or  
```
/etc/init.d/clickhouse-server stop
```

**Comment by Myshiner** [comment]
Ok, thanks for your quick reply.
