### ISSUE TITLE
ClickHouse can display wrong symbol and file names in logs if the debuginfo binary was replaced to a different version.

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#7514]
... and gererate completely nonsense stacktraces... :)

Yesterday i've updated clickhouse-server, but debug symbols was not updated automatically. (i think that's already bug)

And libunwind silently 'accepted' debug symbols from old version and generate some really weird stacktraces :) (i think it should be able to check if symbols match to the binary somehow).

After updating  clickhouse-common-static-dbg and restarting clickhouse-server, it started working properly.

**Comment by alexey-milovidov** [comment]
It does not relate to `libunwind`.

**Comment by alexey-milovidov** [comment]
The relevant code is here: https://github.com/ClickHouse/ClickHouse/blob/594c535bd419d153efe97bd9e93caef4b96cd692/dbms/src/Common/SymbolIndex.cpp#L284

**Comment by alexey-milovidov** [comment]
How to check: https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html
