### ISSUE TITLE
The query on virtual view does't  behave predicate push down

### ISSUE THREAD

**Issue by yzzky** [ClickHouse/ClickHouse#7515]
In my situation, I had use the nest structure in clickhouse , unfortunately the nest grammar does‘t  match the interface . so i create a vitual view to adapt the interface. Everything seems ok, but when excute a query on the view ,i found that the system will scan the whole data of the table. so i guess the query on common view will not behave predicate push down.

**Comment by filimonov** [comment]
@yzzky can you please add a minimal example of schema?
