### ISSUE TITLE
How to set a default value and create second index in create table sql ?

### ISSUE THREAD

**Issue by Myshiner** [ClickHouse/ClickHouse#7516]
Hi, its my first time to use clickhouse, how can i set the default value  and create a second index in create table sql ?

Thx.

**Comment by stavrolia** [comment]
Hello!

> Hi, its my first time to use clickhouse, how can i set the default value and create a second index in create table sql ?

You can set default value when creating the table, the description with examples is [here](https://clickhouse.yandex/docs/en/query_language/create/#create-default-values) and all information about opportunities of indexes of ClickHouse is [here](https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#mergetree-data-storage). When you choose the schema to store your data in ClickHouse it is useful to know about [this section too](https://clickhouse.yandex/docs/en/query_language/create/#create-view).
