### ISSUE TITLE
Add column timeout issue on replicated table

### ISSUE THREAD

**Issue by cailin-lai** [ClickHouse/ClickHouse#7529]
Hi Team,
There is timeout issue when we try to add column to an existing replicated table on clickhouse cluster(version: 18.16.1) which with 4 nodes. It happens randomly on nodes, e.g. we tried 2 times to add same column to table on Oct 10 and Oct 28.  The 1st time happened on the 3rd node, but the 2nd time happened on the 1st node.
When this issue happening, by double checking zookeeper node, it's already applied column changes, but nothing changes to the clickhouse table structure. Well, the table would be broken for data inserts. We've to execute move data, drop & recreate table and attach data steps to recover the table!
After I go through the related issues on issues list,  looks like this issue hasn't been fixed yet.
It's really a pain. Is it a certain plan to fix this issue? Or are there any internal workarounds can perform adding column operation much smooth on replicated table?

Appreciate for help!

The detailed error trace was following,
2019.10.28 23:25:22.386660 [ 102204201 ] {eb10613b-2bdb-404c-95c0-03b89ddc1665} <Warning> db_shard_1.task_snapshot (StorageReplicatedMergeTree): Timeout when waiting for replica ck1 to apply ALTER. ALTER will be done asynchronously.
2019.10.28 23:25:22.425383 [ 102204201 ] {eb10613b-2bdb-404c-95c0-03b89ddc1665} <Error> executeQuery: Code: 341, e.displayText() = DB::Exception: Alter is not finished because timeout when waiting for some replicas: ck1 (replication_alter_columns_timeout = 60). Alter will be done asynchronously., e.what() = DB::Exception (from 127.0.0.1:56632) (in query: ALTER TABLE task_snapshot ADD COLUMN provider_id Int32), Stack trace:

0. /data/app/clickhouse/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x5e3f8b6]
1. /data/app/clickhouse/bin/clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2bce5cf]
2. /data/app/clickhouse/bin/clickhouse-server(DB::StorageReplicatedMergeTree::alter(DB::AlterCommands const&, std::string const&, std::string const&, DB::Context const&)+0x1bd6) [0x4fb3bb6]
3. /data/app/clickhouse/bin/clickhouse-server(DB::InterpreterAlterQuery::execute()+0x891) [0x5350a81]
4. /data/app/clickhouse/bin/clickhouse-server() [0x4eadeac]
5. /data/app/clickhouse/bin/clickhouse-server(DB::executeQuery(std::string const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x70) [0x4eaff90]
6. /data/app/clickhouse/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x547) [0x2bdc337]
7. /data/app/clickhouse/bin/clickhouse-server(DB::TCPHandler::run()+0x1c) [0x2bdd59c]
8. /data/app/clickhouse/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x5fc3dbf]
9. /data/app/clickhouse/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x5fc4186]
10. /data/app/clickhouse/bin/clickhouse-server(Poco::PooledThread::run()+0x77) [0x6275627]
11. /data/app/clickhouse/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x62717e8]
12. /data/app/clickhouse/bin/clickhouse-server() [0x6a7faaf]
13. /lib64/libpthread.so.0(+0x7e25) [0x7f64c91d6e25]
14. /lib64/libc.so.6(clone+0x6d) [0x7f64c89f6bad]

**Comment by den-crane** [comment]
It could be because of long-running selects which block alter.
Just increase a timeout `set replication_alter_columns_timeout = 6000;` or kill selects

**Comment by cailin-lai** [comment]
Thanks @den-crane for your comment. The database operations were executed in the middle night to reduce the impacts from data usage requests, and the data ingestion was stopped for the alter candidate nodes. We'd try to increase the "replication_alter_columns_timeout" flag to see whether it's helpful, next time.

**Comment by den-crane** [comment]
BTW,

>Well, the table would be broken for data inserts.
>We've to execute move data, drop & recreate table and 
>attach data steps to recover the table!

`Alter` should work despite the timeout. At the worst case scenario you able to fix using detach table / attach table.

**Comment by cailin-lai** [comment]
Thanks @den-crane !  We actually faced the worst case, since the inconsistencies between ck and zk, new ingested data was accumulated in distribute table, the data was not visible until we executed recover steps.  In the 2nd tries, we adjusted the data ingestion process that data skipped distribute table, wrote to data table directly, but the issue still impacted the data replication between 2 nodes.
You've mentioned that the merge activities might block the alter process, that is very helpful, we will be keeping an eye on merging process, even the ingestion is stopped before executing alter. Any other potential causes, please?
By the way,  in case of this issue happened, is there a way to change the zookeeper column definitions to make them be consistent with ck table structure again, as a workaround to shorten the breakdown?

**Comment by alexey-milovidov** [comment]
Fixed in master (20.6) in PR #11745.

**Comment by cailin-lai** [comment]
Some new updates, after upgrading version to v20.1.6, looks the issue has gone.  We've confirmed this in many add column stages.
Thanks to Team!
