### ISSUE TITLE
Sir,can I use shard config & use megertree engine  without zookeeper just like below

### ISSUE THREAD

**Issue by 564064202** [ClickHouse/ClickHouse#7555]
![image](https://user-images.githubusercontent.com/12368358/67938021-a7b3e280-fc09-11e9-88d0-951b651d1fb1.png)

![image](https://user-images.githubusercontent.com/12368358/67937831-3e33d400-fc09-11e9-8ae0-a78462711a37.png)

CREATE TABLE monchickey.image_label (
`label_id` UInt32,
 `label_name` String,
 `insert_time` Date
) ENGINE = MergeTree(insert_time, (label_id, insert_time), 8192);

CREATE TABLE image_label_all AS image_label ENGINE = Distributed(test22, monchickey, image_label, rand())

but I can execute  insert sql to insert image_label_all  ,and can't query from image_label_all,
error info : query timeout
![image](https://user-images.githubusercontent.com/12368358/67938290-2ad53880-fc0a-11e9-8976-6f762c27ad5d.png)

**Comment by den-crane** [comment]
Check CH /var/log/clickhouse/ logs at both servers

**Comment by 564064202** [comment]
> 在两个服务器上检查CH / var / log / clickhouse /日志

2019.11.01 00:43:43.535717 [ 47 ] {} <Error> image_label_all.Distributed.DirectoryMonitor: Code: 209, e.displayText() = DB::NetException: Timeout exceeded while reading from socket (10.255.52.40:30002), Stack trace:
30001 30002 just http port

**Comment by 564064202** [comment]
must use tcp port
