### ISSUE TITLE
Add users and Assign Database Permissions through Sql Query

### ISSUE THREAD

**Issue by IVRAMA** [ClickHouse/ClickHouse#7557]
Hi All,
Is there a way to add users and give database access permissions in clickhouse with sql statement, rather than modifying the users.xml.

**Comment by alexey-milovidov** [comment]
No, but @vitlibar is developing it right now in the following PRs: https://github.com/ClickHouse/ClickHouse/pulls?utf8=%E2%9C%93&q=is%3Apr+rbac
