### ISSUE TITLE
Sir,How I can config two server first one as master and  the another one is slave 

### ISSUE THREAD

**Issue by 564064202** [ClickHouse/ClickHouse#7563]
we want to add a server to sync another one's all data,but I don't know how to config it

**Comment by blinkov** [comment]
@564064202 see https://clickhouse.yandex/docs/en/operations/table_engines/replication/

**Comment by 564064202** [comment]
> @564064202 see https://clickhouse.yandex/docs/en/operations/table_engines/replication/

but there is only shard config (with zookeeper)

**Comment by blinkov** [comment]
@564064202, do you have any further questions?

**Comment by robot-clickhouse** [comment]
@564064202, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@564064202 ClickHouse does not have masters and slaves, all replicas are equal.
To create a new replica of existing table on a server, run CREATE TABLE command with the same zookeeper path and different replica path in ReplicatedMergeTree parameters.
