### ISSUE TITLE
[HTTP interface Question] About Transfer Encoding: chunked

### ISSUE THREAD

**Issue by kainever7** [ClickHouse/ClickHouse#7588]
**The problem I encountered：**

**my query**  : INSERTR INTO ads_dmp3 FORMAT TabSeparated 
**Why become** ： INSERTR INTO ads_dmp3 FORMAT TabSeparated el1    **the el1 is input.**

2019.11.02 11:44:52.206085 [ 54 ] {} <Trace> HTTPHandler-factory: HTTP Request for HTTPHandler-factory. Method: POST, Address: 10.32.7.105:56295, User-Agent: akka-http/10.1.10, Content Type: text/plain; charset=UTF-8, **Transfer Encoding: chunked**
2019.11.02 11:44:52.206203 [ 54 ] {} <Trace> HTTPHandler: **Request URI**: /?query=**INSERTR+INTO+ads_dmp3+FORMAT+TabSeparated**&send_progress_in_http_headers=0&readonly=0&enable_http_compression=0&profile=default&user=default&password=
2019.11.02 11:44:52.210900 [ 54 ] {29e13c1a-f3a0-4930-be9c-16ca44e0f211} <Debug> **executeQuery: (from 10.32.7.105:56295) INSERTR INTO ads_dmp3 FORMAT TabSeparated el1**
2019.11.02 11:44:52.210968 [ 54 ] {29e13c1a-f3a0-4930-be9c-16ca44e0f211} <Error> executeQuery: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1 (line 1, col 1): INSERTR INTO ads_dmp3 FORMAT TabSeparated
el1. Expected one of: ATTACH, DETACH, DROP, SHOW, SELECT, WITH, KILL, TRUNCATE, DESC, DESCRIBE, SYSTEM query, SELECT subquery, list of elements, ALTER query, ALTER TABLE, EXISTS, CREATE TABLE or ATTACH TABLE query, Query with output, SHOW PROCESSLIST query, SHOW PROCESSLIST, RENAME query, RENAME TABLE, SELECT query, possibly with UNION, SET query, SHOW [TEMPORARY] TABLES|DATABASES [[NOT] LIKE 'str'], EXISTS or SHOW CREATE query, SELECT query, subquery, possibly with UNION, USE query, CHECK TABLE, DESCRIBE query, DROP query, INSERT query, INSERT INTO, KILL QUERY query, OPTIMIZE query, OPTIMIZE TABLE, SELECT query, CREATE, SET, USE, Query (version 19.13.2.19) (from 10.32.7.105:56295) (in query: INSERTR INTO ads_dmp3 FORMAT TabSeparated el1), Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x30) [0x6f28600]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x316365f]
2. clickhouse-server(DB::parseQuery(DB::IParser&, char const*, char const*, std::string const&, unsigned long)+0xaa) [0x6732f9a]
3. clickhouse-server() [0x5ebb9fb]
4. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>, std::function<void (std::string const&)>)+0x1ef) [0x5ebe71f]
5. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x16dc) [0x31b19fc]
6. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x443) [0x31b4bb3]
7. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x2af) [0x6a76f2f]
8. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x6a6dc7f]
9. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x6a6e046]
10. clickhouse-server(Poco::PooledThread::run()+0x77) [0x70fd527]
11. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x70f96e8]
12. clickhouse-server() [0x76cb73f]
13. /lib64/libpthread.so.0(+0x7dc5) [0x7f5facfa3dc5]
14. /lib64/libc.so.6(clone+0x6d) [0x7f5fac9cf86d]

**Comment by zhang2014** [comment]
`el1` is probably in the post `request body`.  `ClickHouse` usually concat the `query param` with the post `request body` when Content-Type not equal `multipart/form-data`, 
for example:
the query 1:
```
echo 'SELECT 1' | curl 'http://localhost:8123/' --data-binary @-
```
equivalent to query 2:
```
echo ' 1 ' | curl 'http://localhost:8123/?query=SELECT' --data-binary @-
```

**Comment by alexey-milovidov** [comment]
@kainever7 You have write `INSERTR` instead of `INSERT`.
