### ISSUE TITLE
(ReplicatedMergeTreeQueue): Not executing log entry MUTATE_PART for part 201901_179354_179354_0_179570 because source parts size (1.99 KiB) is greater than the current maximum (0.00 B).

### ISSUE THREAD

**Issue by tlightsky** [ClickHouse/ClickHouse#7589]
**Describe the bug or unexpected behaviour**
All mutations got stuck, and server.log keep printing this log,
only 1 of our 6 servers have this problem

**Expected behavior**
All mutations being done in minuates

**Error message and/or stacktrace**
server.log
```
(ReplicatedMergeTreeQueue): Not executing log entry MUTATE_PART for part 201901_179354_179354_0_179570 because source parts size (1.99 KiB) is greater than the current maximum (0.00 B).
```

error.log(maybe not related)
```
Tried to add obsolete part 201909_0_97376_467_336068 covered by 201909_0_97376_467_336116 (state Committed)
```

**Comment by tlightsky** [comment]
disappear a day after all upgrade to 19.15

**Comment by onine007** [comment]
I got same issue in  20.1.*

**Comment by wenwei8268** [comment]
how to solve the problem ,?
