### ISSUE TITLE
ClickHouse SQL formal grammar or parser implementation

### ISSUE THREAD

**Issue by traceon** [ClickHouse/ClickHouse#7595]
Is there a reusable reference SQL parser implementation library or a formal grammar representation that could be used to build a reference parser for the ClickHouse version of SQL?

**Comment by alexey-milovidov** [comment]
No. But we have ANTLR4 grammar that is developed independently and mostly corresponds to the ClickHouse SQL parser. https://github.com/ClickHouse/ClickHouse/tree/master/utils/grammar

**Comment by yanggeorge** [comment]
I have tried ClickHouseParser.g4 ,but I found it not working properly.

**Comment by yanggeorge** [comment]
> No. But we have ANTLR4 grammar that is developed independently and mostly corresponds to the ClickHouse SQL parser. https://github.com/ClickHouse/ClickHouse/tree/master/utils/grammar

I have tried ClickHouseParser.g4 ,but I found it not working properly.

**Comment by knoguchi** [comment]
@yanggeorge here is the SELECT parser.  Take a look in the tests directory for other parsers.  
https://github.com/ClickHouse/ClickHouse/blob/master/src/Parsers/tests/select_parser.cpp

**Comment by filimonov** [comment]
Please see / follow https://github.com/ClickHouse/ClickHouse/pull/11298
