### ISSUE TITLE
[Create View]Performance is much worse than using distributed tables when using views for Join

### ISSUE THREAD

**Issue by kainever7** [ClickHouse/ClickHouse#7609]
The Explain is Different. Why? 
The way , I use it , is wrong ?
I need to use the view to point to the latest day's data.

![image](https://user-images.githubusercontent.com/8843886/68109531-b5c57400-ff25-11e9-8cf2-65a188514cf6.png)

**Comment by filimonov** [comment]
Can you please paste the text of queries and output, instead of screenshots?
What is the version of the clickhouse?
Did you change some settings from their default?

**Comment by den-crane** [comment]
No info. Closing
