### ISSUE TITLE
Bad size of marks file ... (version 19.6.2.1)

### ISSUE THREAD

**Issue by huang--yijian** [ClickHouse/ClickHouse#7610]
**Describe the bug or unexpected behaviour**
Our ClickHouse query fails with error:
Bad size of marks file '/data/clickhouse/data/spoor/transformed_ts_1minute/20191104_15374027_15374051_3/maxLongValue.mrk': 656, must be: 1264 (version 19.6.2.1)

**How to reproduce**
Clickhouse server version: 19.6.2.1
Query interface does not matter.
Settings are by default.

CREATE TABLE statement as follows:

CREATE TABLE transformed_ts_1minute (`metric` String, `domain` String, `tagKeys` Array(String), `tagValues` Array(String), `metricType` Int32, `valueType` Int32, `timestamp` DateTime, `longValue` Int64, `doubleValue` Float64, `minLongValue` Int64, `minIntValue` Int32, `minDoubleValue` Float64, `maxLongValue` Int64, `maxIntValue` Int32, `maxDoubleValue` Float64, `duration` Int64) ENGINE = MergeTree PARTITION BY toDate(timestamp) ORDER BY (metric, timestamp, domain) SETTINGS index_granularity = 8192

* Sample data for all these tables

metric | domain | tagKeys | tagValues | metricType | valueType | timestamp | longValue | doubleValue | minLongValue | minIntValue | minDoubleValue | maxLongValue | maxIntValue | maxDoubleValue | duration
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cgh_test | test | endpoint, k | cgh, v | 0 | 1 | 2019-09-12 14:50:00 | 100 | 100 | 50 | 0 | 0 | 150 | 0 | 0 | 60
XQLDownloadStatus | xql-test | download, endpoint | queue, test-a1-60-38 | 2 | 0 | 2019-09-20 18:30:42 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 60000
XQLWaitingQueue | xql-test | endpoint, queue | test-a1-60-38, jdbc-script | 2 | 0 | 2019-09-20 18:30:42 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 60000

* Queries to run that lead to unexpected result
SELECT domain, max(maxLongValue) as maxHeapUsed, count(*) AS cnt FROM transformed_ts_1minute_all WHERE metric = 'jvm.mem.heap.used'AND timestamp >= (now() - 3*24*60*60) GROUP BY domain HAVING cnt >= 30

**Expected behavior**
Query should succeed without this error.

**Comment by huang--yijian** [comment]
We can afford to delete/detach this bad part, so that the query does not fail. But how to delete/detach a specific part?

**Comment by huang--yijian** [comment]
We see an issue https://github.com/ClickHouse/ClickHouse/pull/6748 with the same error message. However, we are not using skip indices mentioned in issue 6748, so it is not related to ours.

**Comment by den-crane** [comment]
Stop queries / ingestion

detach table transformed_ts_1minute;
# mv /data/clickhouse/data/spoor/transformed_ts_1minute/20191104_15374027_15374051_3 /tmp
attach table transformed_ts_1minute;

start queries / ingestion

**Comment by huang--yijian** [comment]
> Stop queries / ingestion
> 
> ```
> detach table transformed_ts_1minute;
> # mv /data/clickhouse/data/spoor/transformed_ts_1minute/20191104_15374027_15374051_3 /tmp
> attach table transformed_ts_1minute;
> ```
> 
> start queries / ingestion

It works. Thank you for your help!
What's the root cause ? And is it fixed in later versions of ClickHouse ?

**Comment by alesapin** [comment]
I'm also interested in the root cause of this problem. @den-crane

**Comment by den-crane** [comment]
> It works. Thank you for your help!
> What's the root cause ? And is it fixed in later versions of ClickHouse ?

As I understood your first message it was a bit rot? Isn't it?

**Comment by huang--yijian** [comment]
I mean the damaged part was dropped successfully by your solution.

What's the root cause of why the part is damaged?  
Is this problem fixed in later versions of ClickHouse ?

**Comment by huang--yijian** [comment]
I mean the damaged part was dropped successfully by your solution.

What's the root cause of this damaged part?
Is this problem fixed in later versions of ClickHouse ?

**Comment by den-crane** [comment]
> What's the root cause of this damaged part?

I don't know. Accident memory / disk corruption?

**Comment by filimonov** [comment]
> What's the root cause of this damaged part?

You can try to find fist mention of that part name in the clickhouse logs. Maybe something happened at that moment? Maybe there was a problem with filesystem (like lack of disk space), maybe there was some hard restart or something like that.

Please update clickhouse to one of the recent versions. If you will see that problem again please create a new issue with more detail.
