### ISSUE TITLE
How should I define a cluster with three shards, and each shard has 2 replicas in three server node?

### ISSUE THREAD

**Issue by RaulGuo** [ClickHouse/ClickHouse#7611]
I have built a clickhouse with 3 nodes(let's say it is ip1, ip2, and ip3), now I tries to build a cluster in the metrica.xml. My plan is to build one with three shards, and each shards has two replicas when I use distributed table using this cluster, so I defined my cluster named distribute_cluster like this:

```
<distribute_cluster>
	<shard>
		<weight>1</weight>
		<internal_replication>true</internal_replication>
		<replica>
			<host>ip1</host>
			<port>9000</port>
		</replica>
		<replica>
			<host>ip2</host>
			<port>9000</port>
		</replica>
	</shard>
	<shard>
		<weight>1</weight>
		<internal_replication>true</internal_replication>
		<replica>
			<host>ip1</host>
			<port>9000</port>
		</replica>
		<replica>
			<host>ip3</host>
			<port>9000</port>
		</replica>
	</shard>
	<shard>
		<weight>1</weight>
		<internal_replication>true</internal_replication>
		<replica>
			<host>ip2</host>
			<port>9000</port>
		</replica>
		<replica>
			<host>ip3</host>
			<port>9000</port>
		</replica>
	</shard>
</distribute_cluster>
```

But when I tried to define a table using this cluster, error reported.

My create table statement is like this:

```
create table default.test_merge_tree_cluster on CLUSTER standard_cluster_new( 
`info` String, 
`type` String, 
`value` Int32 
) ENGINE = MergeTree() 
ORDER BY (info, value) 
SAMPLE BY value;
```
The error info is this:

> An error occured before execution: Code: 371, e.displayText() = DB::Exception: There are two exactly the same ClickHouse instances ip1:9000 in cluster distribute_cluster (version 19.14.6.12)

I can understand that this error occurs because there are two replicas using the same port in the cluster used here. But how should I define my cluster with only three machines on condition that I can have three shard and each one with two clusters（in other word, I have only three machine and each one has only one tcp port, but I want to have six replicas）? After all, there is only one port defined for tcp_port which is 9000, I cannot use other ports.

The xml definition looks bad formated, I will upload an attachment of it.
[standard_cluster.txt](https://github.com/ClickHouse/ClickHouse/files/3803963/standard_cluster.txt)

**Comment by den-crane** [comment]
https://www.altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse

But it's not fully supported:
* DDL on cluster won't work.
* Double distributed joins will fail with exception "Table not found"

**Comment by Tasselmi** [comment]
> I have built a clickhouse with 3 nodes(let's say it is ip1, ip2, and ip3), now I tries to build a cluster in the metrica.xml. My plan is to build one with three shards, and each shards has two replicas when I use distributed table using this cluster, so I defined my cluster named distribute_cluster like this:
> 
> ```
> <distribute_cluster>
> 	<shard>
> 		<weight>1</weight>
> 		<internal_replication>true</internal_replication>
> 		<replica>
> 			<host>ip1</host>
> 			<port>9000</port>
> 		</replica>
> 		<replica>
> 			<host>ip2</host>
> 			<port>9000</port>
> 		</replica>
> 	</shard>
> 	<shard>
> 		<weight>1</weight>
> 		<internal_replication>true</internal_replication>
> 		<replica>
> 			<host>ip1</host>
> 			<port>9000</port>
> 		</replica>
> 		<replica>
> 			<host>ip3</host>
> 			<port>9000</port>
> 		</replica>
> 	</shard>
> 	<shard>
> 		<weight>1</weight>
> 		<internal_replication>true</internal_replication>
> 		<replica>
> 			<host>ip2</host>
> 			<port>9000</port>
> 		</replica>
> 		<replica>
> 			<host>ip3</host>
> 			<port>9000</port>
> 		</replica>
> 	</shard>
> </distribute_cluster>
> ```
> 
> But when I tried to define a table using this cluster, error reported.
> 
> My create table statement is like this:
> 
> ```
> create table default.test_merge_tree_cluster on CLUSTER standard_cluster_new( 
> `info` String, 
> `type` String, 
> `value` Int32 
> ) ENGINE = MergeTree() 
> ORDER BY (info, value) 
> SAMPLE BY value;
> ```
> 
> The error info is this:
> 
> > An error occured before execution: Code: 371, e.displayText() = DB::Exception: There are two exactly the same ClickHouse instances ip1:9000 in cluster distribute_cluster (version 19.14.6.12)
> 
> I can understand that this error occurs because there are two replicas using the same port in the cluster used here. But how should I define my cluster with only three machines on condition that I can have three shard and each one with two clusters（in other word, I have only three machine and each one has only one tcp port, but I want to have six replicas）? After all, there is only one port defined for tcp_port which is 9000, I cannot use other ports.
> 
> The xml definition looks bad formated, I will upload an attachment of it.
> [standard_cluster.txt](https://github.com/ClickHouse/ClickHouse/files/3803963/standard_cluster.txt)

you can use only 1 replica.  that is, 3 machines and 3 shards.

**Comment by RaulGuo** [comment]
> https://www.altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse
> 
> But it's not fully supported:
> 
> * DDL on cluster won't work.
> * Double distributed joins will fail with exception "Table not found"
> 
> Personally I don't recommend this schema because second replicas kill performance (they use cache / I/O/ CPU).

Of course, more replica means less efficiency. But we need to make sure service is still provided when one replica is broken and no data loss. That is our trouble.

**Comment by Tasselmi** [comment]
> performance

you need ask boss for more money......

**Comment by RaulGuo** [comment]
> https://www.altinity.com/blog/2018/5/10/circular-replication-cluster-topology-in-clickhouse
> 
> But it's not fully supported:
> 
> * DDL on cluster won't work.
> * Double distributed joins will fail with exception "Table not found"
> 
> Personally I don't recommend this schema because second replicas kill performance (they use cache / I/O/ CPU).

And I have read about the article, but it doesn't work for me, same error still report. I think I cannot find a solution for this. I am using version 19.14.6, I think this article is overtime.

**Comment by RaulGuo** [comment]
> > performance
> 
> you need ask boss for more money......

more budget, less salary, lol and crying……

**Comment by den-crane** [comment]
> And I have read about the article, but it doesn't work for me, same error still report. I think I cannot find a solution for this. I am using version 19.14.6, I think this article is overtime.

Do you see why in this article in a cluster description replicas have  <default_database> section?
I don't see this  <default_database> in yours.

**Comment by RaulGuo** [comment]
> > And I have read about the article, but it doesn't work for me, same error still report. I think I cannot find a solution for this. I am using version 19.14.6, I think this article is overtime.
> 
> Do you see why in this article in a cluster description replicas have <default_database> section?
> I don't see this <default_database> in yours.

Yeah, I used the default databse, and I have checked the system.clusters table, the cluster is using two different databases. No matter which database I use to create the distributed table, it report that there are two instance using same port in the cluster.

**Comment by den-crane** [comment]
Please provide your <distribute_cluster> XML

**Comment by RaulGuo** [comment]
> database

My standard_cluster is defined like this:
```
<distribute_cluster>
	<shard>
		<weight>1</weight>
		<internal_replication>true</internal_replication>
		<replica>
			<host>ip1</host>
			<port>9000</port>
			<default_database>circular_replica_1</default_database>
		</replica>
		<replica>
			<host>ip3</host>
			<port>9000</port>
			<default_database>circular_replica_1</default_database>
		</replica>
	</shard>
	<shard>
		<weight>1</weight>
		<internal_replication>true</internal_replication>
		<replica>
			<host>ip2</host>
			<port>9000</port>
			<default_database>circular_replica_1</default_database>
		</replica>
		<replica>
			<host>ip3</host>
			<port>9000</port>
			<default_database>circular_replica_2</default_database>
		</replica>
	</shard>
	<shard>
		<weight>1</weight>
		<internal_replication>true</internal_replication>
		<replica>
			<host>ip1</host>
			<port>9000</port>
			<default_database>circular_replica_2</default_database>
		</replica>
		<replica>
			<host>ip2</host>
			<port>9000</port>
			<default_database>circular_replica_2</default_database>
		</replica>
	</shard>
</distribute_cluster>
```

My ReplicatedMergeTree table is created like this:

```
CREATE TABLE default.helloworld_dist_gogogo ON CLUSTER standard_cluster
(
    `info` String, 
    `type` String, 
    `value` Int32, 
    `date` Date
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/helloworld_dist_gogogo', '{replica}')
PARTITION BY date
PRIMARY KEY (info, value)
ORDER BY (info, value)
SAMPLE BY value
```

finally, my distributed table is created like this:
```
CREATE TABLE test_gogo_dist ON CLUSTER distribute_cluster AS helloworld_dist_gogogo
ENGINE = Distributed(distribute_cluster, '', helloworld_dist_gogogo, rand())
```
And all three nodes report the same error:
```
┌─host─────────┬─port─┬─status─┬─error───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─num_hosts_remaining─┬─num_hosts_active─┐
│ ip3  │ 9000 │    371 │ An error occured before execution: Code: 371, e.displayText() = DB::Exception: There are two exactly the same ClickHouse instances ip3:9000 in cluster distribute_cluster (version 19.14.6.12)  │                   2 │                0 │
│ ip2  │ 9000 │    371 │ An error occured before execution: Code: 371, e.displayText() = DB::Exception: There are two exactly the same ClickHouse instances ip2:9000 in cluster distribute_cluster (version 19.14.6.12) │                   1 │                0 │
│ ip1   │ 9000 │    371 │ An error occured before execution: Code: 371, e.displayText() = DB::Exception: There are two exactly the same ClickHouse instances ip1:9000 in cluster distribute_cluster (version 19.14.6.12)   │                   0 │                0 │
└──────────────┴──────┴────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
Forget about the silly table names here, I don't want to pay attention to make more names after several trials. 
Maybe I should ask the boss for more budget, lol.

**Comment by den-crane** [comment]
>CREATE TABLE test_gogo_dist ON CLUSTER

**DDL on cluster won't work.**  -- expected behavior.

**Comment by baciSmile** [comment]
@RaulGuo I ran into the same problem you had, and how did you solve it, or clickhouse distributed how to deploy using MergeTree table

**Comment by frankieci** [comment]
> @RaulGuo I ran into the same problem you had, and how did you solve it, or clickhouse distributed how to deploy using MergeTree table

Happy! I found its method to deploy for clickhouse distributed, then it works well

**Comment by den-crane** [comment]
@compasses do you speed up single query? or multiple parallel queries?

**Comment by smbanaie** [comment]
> > @RaulGuo I ran into the same problem you had, and how did you solve it, or clickhouse distributed how to deploy using MergeTree table
> 
> Happy! I found its method to deploy for clickhouse distributed, then it works well

Hi ,
Can you share your final solution. I stuck here !

**Comment by PancoCheong** [comment]
It is possible to set up 3 shards and 2 replicas on 3 server nodes...
but this setting requires some workaround, the detail is in the link below:

https://zhuanlan.zhihu.com/p/461792873

The workaround to solve this is to
- put each shard into a separate database
- set default_database for each shard
- set empty database parameter in the distributed table DDL script, the system will use the default database to route the query for a particular table to the right database in query time.
- set internal_replication of each shard to true

**Comment by vhp1360** [comment]
I ran into the same issue. how do others solve it?
this my cluster config part:
```
    <remote_servers>
        <cluster_1shards_2replicas>
            <shard>
                <replica>
                    <host>clickhouse1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>clickhouse2</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <host>clickhouse3</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cluster_1shards_2replicas>
        <cluster_3shards_2replicas>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>default</default_database>
                    <host>clickhouse1</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <default_database>default</default_database>
                    <host>clickhouse2</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>default</default_database>
                    <host>clickhouse2</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <default_database>default</default_database>
                    <host>clickhouse3</host>
                    <port>9000</port>
                </replica>
            </shard>
            <shard>
                <internal_replication>true</internal_replication>
                <replica>
                    <default_database>default</default_database>
                    <host>clickhouse3</host>
                    <port>9000</port>
                </replica>
                <replica>
                    <default_database>default</default_database>
                    <host>clickhouse1</host>
                    <port>9000</port>
                </replica>
            </shard>
        </cluster_3shards_2replicas>
    </remote_servers>
```
the 'cluster_1shards_2replicas' cluster definition is ok and works but the next return errors as the same errors you all got.
how do we solve it?

**Comment by pingulee** [comment]
I also need this function.

**Comment by pingulee** [comment]
> It is possible to set up 3 shards and 2 replicas on 3 server nodes... but this setting requires some workaround, the detail is in the link below:
> 
> https://zhuanlan.zhihu.com/p/461792873
> 
> The workaround to solve this is to
> 
> * put each shard into a separate database
> * set default_database for each shard
> * set empty database parameter in the distributed table DDL script, the system will use the default database to route the query for a particular table to the right database in query time.
> * set internal_replication of each shard to true

Is it still working?
