### ISSUE TITLE
clickhosue hdfs engine not work (version 19.15.4.10)

### ISSUE THREAD

**Issue by cocopc** [ClickHouse/ClickHouse#7614]
`
CREATE TABLE hdfs_engine_table (name String, value UInt32) ENGINE = HDFS('hdfs://x.x.x.x:9000/tmp/other_storage/csv-data.csv', 'CSV')

select * from hdfs_engine_table;
`
clickhouse-server error:

2019.11.04 23:30:12.175505 [ 51 ] {} <Fatal> BaseDaemon: ########################################
2019.11.04 23:30:12.175608 [ 51 ] {} <Fatal> BaseDaemon: (version 19.15.4.10) (from thread 27) Received signal Illegal instruction (4).
2019.11.04 23:30:12.175662 [ 51 ] {} <Fatal> BaseDaemon: Illegal operand.
2019.11.04 23:30:12.175777 [ 51 ] {} <Fatal> BaseDaemon: Stack trace: 0x33ddd41 0x357d55b 0x7fba601f7370
2019.11.04 23:30:12.297899 [ 51 ] {} <Fatal> BaseDaemon: 0. 0x33ddd41 StackTrace::StackTrace(ucontext const&) /usr/bin/clickhouse
2019.11.04 23:30:12.298048 [ 51 ] {} <Fatal> BaseDaemon: 1. 0x357d55b ? /usr/bin/clickhouse
2019.11.04 23:30:12.298107 [ 51 ] {} <Fatal> BaseDaemon: 2. 0x7fba601f7370 ? /usr/lib64/libpthread-2.17.so

**Comment by cocopc** [comment]
@weiqxu 
linux kernal:   3.10.0-957.5.1.el7.x86_64,
but clickhouse  version 19.4.5.35 works  ， version 19.15.4.10 not work。

**Comment by Aaronzk** [comment]
I have encountered the same problem。The log is exactly the same。
linux kernal is 3.10.0-327.el7.x86_64
both version 19.13.3.26 and 19.15.4.10 not work。

**Comment by alexey-milovidov** [comment]
Fixed by @amosbird long time ago.
