### ISSUE TITLE
clickhouse-server.log

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#7627]
> 2019.11.05 09:20:54.959748 [ 49 ] {93872e27-47b7-4fba-b749-bf987fb7e67c} <Debug> demo.order_manage (SelectExecutor): Selected 4 parts by date, 4 parts by key, 1030 marks to read from 4 ranges

What does it mean `4 parts by date`, `4 parts by key`, `1030 marks to read from 4 ranges`?

**Comment by den-crane** [comment]
That means that 4 parts will be read because 4 parts is suitable for WHERE conditions by partition key / primary key index. 1030 marks means that this range of marks need to read to solve the query.


```
create table ZZ (A Int64, B Int64, C String) Engine = MergeTree partition by A order by B;
insert into ZZ select 1, number, '' from numbers(16384);
insert into ZZ select 2, number,'' from numbers(1);
insert into ZZ select 2, number,'' from numbers(1);

set send_logs_level='debug'

-- No A condition (no partition pruning), need to read 3 parts but only 1 part has B=999 (1 parts by key)
select * from ZZ where B=999  format Null;
Selected 3 parts by date, 1 parts by key, 1 marks to read from 1 ranges

-- partition pruning (by date)
select * from ZZ where A=1 and B=999  format Null;
Selected 1 parts by date, 1 parts by key, 1 marks to read from 1 ranges

select * from ZZ where A=1 and B=1  format Null;
Selected 1 parts by date, 1 parts by key, 1 marks to read from 1 ranges

select * from ZZ where A=2 and B=0  format Null;
Selected 2 parts by date, 2 parts by key, 2 marks to read from 2 ranges
```

**Comment by chu1070y** [comment]
When I create table, I do not use partition key, Does the ClickHouse use partition key automatically?

**Comment by den-crane** [comment]
```
create table ZZ (A Int64, B Int64, C String) Engine = MergeTree order by B;
the same as 
create table ZZ (A Int64, B Int64, C String) Engine = MergeTree *partition by tuple()* order by B;

One partition == all. No partition pruning / elimination.
```

**Comment by chu1070y** [comment]
Thanks for explanation.

**Comment by den-crane** [comment]
tuple means 1-ary.
All data will be placed into the same one partition.

**Comment by chu1070y** [comment]
Is there any possible that the Clickhouse automatically creates more than one partition. becuz, when I created tables without partition key, partition is created like below.

> 2019.11.06 13:24:28.903168 [ 54 ] {1719ba64-2f5f-443b-84ad-25a0eeeeda2d} <Debug> demo.order_product (SelectExecutor): Selected 4 parts by date, 4 parts by key, 1113 marks to read from 4 ranges
