### ISSUE TITLE
centos 7.3 How to update clickhouse?

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7628]
my clickhouse version is 19.15
I want to update to 19.16. 
OS is centos 7.3.

How should I do?
thanks

**Comment by blinkov** [comment]
@Tasselmi which method you used to install ClickHouse in the first place?

**Comment by Tasselmi** [comment]
> place

I download all the 3 rpm files -- clickhosue-common, clickhouse-client, clickhouse-server  locally.
and use `yum localinstall xxxx` to install them.

**Comment by alesapin** [comment]
How your download URL looked like?

**Comment by blinkov** [comment]
@Tasselmi why haven't you just followed the official instruction from https://clickhouse.yandex/#quick-start ? (which shows up after clicking on CentOS/RedHad)

**Comment by Tasselmi** [comment]
@alesapin
```
wget http://hlzstest.oss-cn-hangzhou.aliyuncs.com/clickhouse/clickhouse-common-static-19.15.3.6-2.x86_64.rpm;
wget http://hlzstest.oss-cn-hangzhou.aliyuncs.com/clickhouse/clickhouse-server-19.15.3.6-2.noarch.rpm;
wget http://hlzstest.oss-cn-hangzhou.aliyuncs.com/clickhouse/clickhouse-client-19.15.3.6-2.noarch.rpm;
```

official downloading is in moscow, it is too slow.

**Comment by Tasselmi** [comment]
> @Tasselmi why haven't you just followed the official instruction from https://clickhouse.yandex/#quick-start ? (which shows up after clicking on CentOS/RedHat)

It is too too slow. about 10kb/s .

**Comment by filimonov** [comment]
@Tasselmi official repo is in Moscow only, but usually, it works very well, maybe there were some temporary network issues. Please retry.

For centos, you can also use repo from Altinity (it is not the mirror, it is clickhouse build on CentOS natively):  https://github.com/Altinity/clickhouse-rpm-install
