### ISSUE TITLE
Mutation with json operation in filter_expr fails.

### ISSUE THREAD

**Issue by the-horhe** [ClickHouse/ClickHouse#7638]
Trying to delete/update rows with column containing certain json field value but mutation fails with error "std::exception. Code: 1001, type: std::length_error, e.what() = basic_string::_M_create, version = 19.16.2.2 (official build)"

**How to reproduce**
Tested clickhouse versions versions: 19.15.3.6, 19.16.2.2

```
CREATE TABLE `default`.json_test (id UInt32, metadata String) ENGINE = MergeTree() ORDER BY id;

INSERT INTO `default`.json_test VALUES 
(1, '{"date": "2018-01-01", "task_id": "billing_history__billing_history.load_history_payments_data__20180101"}'),
(2, '{"date": "2018-01-02", "task_id": "billing_history__billing_history.load_history_payments_data__20180101"}');

ALTER TABLE `default`.json_test DELETE WHERE JSONExtractString(metadata, 'date') = '2018-01-01';
```

**Expected behavior**
Row with id 1 expected to be deleted.

**Error message**
Executed mutations in system.mutations has is_done = 0 and latest_fail_reason:
std::exception. Code: 1001, type: std::length_error, e.what() = basic_string::_M_create, version = 19.16.2.2 (official build)

**Comment by alesapin** [comment]
Fix https://github.com/ClickHouse/ClickHouse/pull/7664

**Comment by alesapin** [comment]
Will be available in all next stable releases.
