### ISSUE TITLE
When Join Clause in Select query, The query use index of join column?

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#7642]
orders - pk: order_id
order_product - pk: (order_id, product_no)

```sql
select o.o_zipcode, op.opt_id 
from orders o 
    inner join order_product op 
        on o.order_id = op.order_id;
```

Two tables has `order_id` as primary key. When I join two tables in select query, Does the query use index?

**Comment by den-crane** [comment]
Join does not use index. Because currently CH supports only HashJoin. And HashJoin puts a right table into memory into HashTable with joinKey as a lookup key.

**Comment by chu1070y** [comment]
:)
