### ISSUE TITLE
Change bitmapBuild result type from default UInt8

### ISSUE THREAD

**Issue by mrAndersen** [ClickHouse/ClickHouse#7647]
Hi there! Can i somehow change result type of bitmapBuild([1,2,3,4]) not to ```AggregateFunction(groupBitmap, UInt8)``` which i assume selects type by selecting max integer in set, but to ```AggregateFunction(groupBitmap, UInt32)``` without using hacks like bitmapBuild([1,2,3,4, 4294967295])

**Comment by alexey-milovidov** [comment]
CC @yuzhichang

**Comment by yuzhichang** [comment]
@mrAndersen You can cast array to UInt32 explicitly, for example `bitmapBuild(cast([1,2,3,4] as Array(UInt32)))`.

**Comment by mrAndersen** [comment]
Thanks!
