### ISSUE TITLE
ALTER TABLE FREEZE ON CLUSTER not working

### ISSUE THREAD

**Issue by ifoo** [ClickHouse/ClickHouse#7648]
_ALTER TABLE FREEZE_ doesn't seem to work _ON CLUSTER_.

Example:
```
ch1 :) alter table tbl_local on cluster 'clustername' freeze

ALTER TABLE tbl_local ON CLUSTER clustername
    FREEZE

Received exception from server (version 19.15.3):
Code: 48. DB::Exception: Received from ch1:9000. DB::Exception: Unsupported type of ALTER query.

0 rows in set. Elapsed: 0.062 sec.
```

_tbl_local_ is a ReplicatedMergeTree table.

Clickhouse version is 19.5.3.

**Comment by alexey-milovidov** [comment]
CC @sundy-li

**Comment by alexey-milovidov** [comment]
DDLWorker.cpp, `isSupportedAlterType`:
FREEZE is marked as unsupported. Is there any reason for it?

**Comment by alexey-milovidov** [comment]
We don't have this restriction in `DDLWorker` anymore.
