### ISSUE TITLE
Support for 16bit floating point types.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#7657]
**Use case**
Compact representation of coefficients for machine learning models.

**Describe the solution you'd like**
This is research task. We should implement `half`, `bfloat16` and `unum` variants and compare them.

**Comment by alexey-milovidov** [comment]
This task is assigned to @RuS2m

**Comment by alexey-milovidov** [comment]
It was half-way implemented, but looks like no one needs this feature.

**Comment by raulcarlomagno** [comment]
what about now? this could be very useful in terms of storage saving

**Comment by alexey-milovidov** [comment]
I need this feature!
We will start with BFloat16 only.

https://github.com/ClickHouse/ClickHouse/pull/64712

**Comment by alexey-milovidov** [comment]
Done.
