### ISSUE TITLE
system.data_skipping_indices table for data skipping indices

### ISSUE THREAD

**Issue by ifoo** [ClickHouse/ClickHouse#7659]
Currently the only way to get information about existing data skipping indices is via the `create_table_query` field of the `system.tables` table (or from the `metadata/` directory on the filesystem). Both of them are not easy to parse and are therefore not useful for automated processing.

I'd like to propose a system.* table dedicated to data skipping indices, similar to `system.columns`.

I would like to see at least the following information in the table:

```
select * from system.data_skipping_indices

┌─database─┬─table───┬─name──────────┬─type─────┬─expr───────┬─granularity─┐
│ default  │ metrics │ idx_skip_tags │ SET(100) │ tags_field │           4 │
└──────────┴─────────┴───────────────┴──────────┴────────────┴─────────────┘
```
Additionally, any type of statistics/metrics might be useful, but i don't know the internals of data skipping indices enough to give any meaningful input here.

**Comment by filimonov** [comment]
May be we can just list them inside columns? With a special column type? In that case we will also hale parts_columns 'for free'.

**Comment by alexey-milovidov** [comment]
@filimonov In this case we will have to always keep in mind that system.columns is not only for columns. It will break 3rd party tools.

Better to introduce a separate table.
