### ISSUE TITLE
Export all config settings

### ISSUE THREAD

**Issue by nvartolomei** [ClickHouse/ClickHouse#7663]
There are few settings which are not present in system.settings table and also can't change at runtime.

Examples: max_concurrent_queries, max_connections, mark_cache_size.

It would be useful to have these available for inspection at runtime.

**Comment by alexey-milovidov** [comment]
Trivial solution is to iterate over all config values and expose them in system table.
But it's unacceptable because too much info will be exposed (various auth info, path to SSL certificate, etc...).

Maybe we can expose only nodes at the first level of XML. This variant looks fragile.

**Comment by alexey-milovidov** [comment]
We don't have common repository of available config entries in code. Instead, any part of code can look up to any value in config.

This is unconvenient also because we cannot give user a warning about unknown config elements (in most cases).

**Comment by alexey-milovidov** [comment]
Another solution is to have a system table that will expose only a fixed list of settings specified directly in code. I don't like this solution because it will be hard to support (to keep it in mind when we add every new config value).

**Comment by filimonov** [comment]
Maybe something like system.zookeeper? + limit access by some xml attribute? 

I.e. 
```sql
SELECT * FROM system.server_settings WHERE path='max_connections'.
```
and in config
```
<password hide="1">secret</password>
```

?

**Comment by alexey-milovidov** [comment]
> Maybe something like system.zookeeper?

You just reminded me that `system.zookeeper` is also unsafe :) I'm sure that our information security team is not happy with it.

**Comment by nvartolomei** [comment]
I like @filimonov's proposal as long as we limit access to this table to a administrator who would have access to the config anyway.

**Comment by filimonov** [comment]
> > Maybe something like system.zookeeper?
> 
> You just reminded me that `system.zookeeper` is also unsafe :) I'm sure that our information security team is not happy with it.

As a tactical approach we can just introduce `<allow_server_management>` which will allow access
to system.zookeeper, system.server_settings and some (all?) `SYSTEM ...` queries, like `SYSTEM STOP MERGES`

**Comment by alexey-milovidov** [comment]
About access restriction for `system.zookeeper` table. Just hold before @vitlibar will implement RBAC and the issue solved.

**Comment by alexey-milovidov** [comment]
> <password hide="1">secret</password>

I don't like this solution, it introduces something to keep in mind.

**Comment by alexey-milovidov** [comment]
Maybe we can have this table with all config entries but only if access will be restricted by default.

**Comment by alexey-milovidov** [comment]
The #13924 is a good alternative.
