### ISSUE TITLE
How to load partitioned parquet or orc files.

### ISSUE THREAD

**Issue by guanlisheng** [ClickHouse/ClickHouse#7676]
Hey there,
Recently I am investigating ClickHouse as our OLAP engine and found an issue when loading our partitioned files in parquet or orc. I think the root cause is the partition key itself is not in the schema of the parquet/orc file.

Any advice or suggestions to handle this scenario?
Many thanks!

**Comment by alexey-milovidov** [comment]
This is not supported right now.

@stavrolia will add `_file` and `_path` virtual columns to HDFS, File, S3 and URL storage engines and you will be able to extract the value of partition key from filenames while reading multiple files with wildcards.

**Comment by kmatt** [comment]
@alexey-milovidov It appears the current S3 table function (v19.19.1) does not support path style access, so files in an (emulated) subdirectory are not accessible?

**Comment by alexey-milovidov** [comment]
@stavrolia will add support for wildcards.

**Comment by alexey-milovidov** [comment]
@stavrolia has added support for wildcards and virtual columns.

**Comment by stavrolia** [comment]
To be clear wildcards and virtual columns are implemented now only in HDFS anf File. The issue for s3 is [here](https://github.com/ClickHouse/ClickHouse/issues/7612).
