### ISSUE TITLE
view-level permissions

### ISSUE THREAD

**Issue by csnook** [ClickHouse/ClickHouse#7680]
**Use case**
We'd like to expose different subsets of data to different audiences without having to create separate databases for each combination of permissions, and without having to bulk copy historical data when granting or changing that access. This is similar to https://github.com/ClickHouse/ClickHouse/issues/523, but we don't need it that fine grained. The filters we have in mind can be expressed as views, so permissions on views would be adequate.

**Describe the solution you'd like**
Standard SQL grants would be ideal, but a configuration file would be fine.

**Describe alternatives you've considered**
We already have API services that populate pre-defined queries with user-supplied parameters after authorization checks, but it would be a lot less work if we could just express those as views and selectively grant access to those views, and would give us defense in depth for things that are sensitive enough to justify both.

**Additional context**
Grafana has a Clickhouse plugin, but access to datasources is all-or-nothing in Grafana, even with the Grafana Enterprise Datasource Permissions feature, so unprivileged users can issue arbitrary queries with the credentials configured in Grafana even if those queries aren't configured on any dashboard and they don't have Editor or Admin privileges. This makes it very dangerous to configure a Clickhouse datasource that contains any sensitive information.

**Comment by filimonov** [comment]
Work on access control is currently in progress. 

You can follow those PR
https://github.com/ClickHouse/ClickHouse/pull/6663
https://github.com/ClickHouse/ClickHouse/pull/7257
https://github.com/ClickHouse/ClickHouse/pull/7310

You can also check that:
https://github.com/ClickHouse/ClickHouse/pull/4792/files

**Comment by alexey-milovidov** [comment]
@vitlibar Please clarify how (and if) it's possible to configure with the new RBAC feature.

**Comment by alexey-milovidov** [comment]
@vitlibar did not respond.
