### ISSUE TITLE
JOIN with Dictionary (lookup join)

### ISSUE THREAD

**Issue by 4ertus2** [ClickHouse/ClickHouse#7688]
It's quite easy to implement LEFT|INNER JOIN over Dictionaty with better perfomace than we have with general JOINs. We could make fake HashMap wrapper over the Dictionary and use it in HashJoin algorithm instead of real HashMaps it uses. So we need no insertion phase of JOIN there. Selects are not limited by memory. Memory usage is managed by Dictionary itsefls.

In fact it's just a lookup join strategy with some cache managed by Dictionary type.

**Comment by alexey-milovidov** [comment]
+1.

After "DDL Dictionaries" feature, the user will have a table for every dictionary. And it will be very likely that the user will JOIN with this table instead of using dictGet.
