### ISSUE TITLE
too slow updating, how to solve?

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7691]
`
(3/3): clickhouse-common-static-19.16.2.2-2.x86_64.rpm                 
3% [==                                                           ] 6.6 kB/s | 3.6 MB  03:48:56 ETA
`

This makes me mad...

**Comment by alesapin** [comment]
I have asked our repository SRE to check this.

**Comment by Tasselmi** [comment]
Problem has been solved. Thanks




| |
梁凡
邮箱：tasselmi@yeah.net
|

签名由 网易邮箱大师 定制

On 11/09/2019 01:03, alesapin wrote:

I have asked our repository SRE to check this.
