### ISSUE TITLE
I can not find system query log table

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7694]
where is Query thread log table in version 19.16.2.2

**Comment by alexey-milovidov** [comment]
1. Make sure that `<query_thread_log>` is configured in `config.xml`. This is by default.
2. Make sure that the settings `log_queries` and `log_query_threads` are enabled for your queries. By default, `log_queries` is 0 and `log_query_threads` is 1. It means that if you enable `log_queries`, both tables `system.query_log` and `system.query_thread_log` will be used.
