### ISSUE TITLE
Show full or part of the bad formatted message when reading from the Kafka

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#7697]
Example:

> 2019.11.08 12:54:41.941739 [ 14 ] {} <Error> void DB::StorageKafka::threadFunc(): Code: 26, e.displayText() = DB::Exception: Cannot parse JSON string: expected opening quote: (while read the value of key needPromoPrice): (at row 1)

Log entry should contain part or the full message.

**Comment by filimonov** [comment]
+ topic / partition / offset

**Comment by alexey-milovidov** [comment]
@filimonov Please either accept or close.

**Comment by alexey-milovidov** [comment]
@filimonov restrained to either accept or close this issue.
