### ISSUE TITLE
Net work days function

### ISSUE THREAD

**Issue by caueteixeira** [ClickHouse/ClickHouse#7700]
Hi clickhouse team,

I would like to know if there is any built in function to find the net work days between to given dates. I would provide the holiday calendar and I would expect clickhouse to find the number of working days (excluding holidays + weekends)

Thanks!
Caue

**Comment by alexey-milovidov** [comment]
Here is an example:

```
WITH 
    toDate('2019-01-01') AS d1, 
    today() AS d2
SELECT length(arrayFilter(x -> ((toDayOfWeek(d1 + x) <= 5) AND ((d1 + x) NOT IN ('2019-01-01', '2019-01-02'))), range(toUInt64(d2 - d1)))) AS num_work_days

┌─num_work_days─┐
│           222 │
└───────────────┘
```

Here I create an array spanning all days between two dates, filter weekends and a list of public holidays (after NOT IN), then calculate the length.

But it's neither cute nor optimal.

**Comment by den-crane** [comment]
```
create table calendar (Day Date, is_holiday Int8) Engine=MergeTree order by Day;
insert into calendar select today()+number, number%7 from numbers(1000);

select count() from calendar where Day between '2019-12-30' and '2020-12-30' and not is_holiday;
```

**Comment by caueteixeira** [comment]
Thanks guys!

**Comment by zhikeke** [comment]
SELECT
'2022-06-18 10:10:10' AS d1,
'2022-06-20 10:10:10' AS d2,
toDate(d1) AS d1_date,
toDate(d2) AS d2_date,
addDays(d1_date, 1) AS d1_next_day,
toInt8('1') AS week_start_day,
toInt8('5') AS week_end_day,
arrayMap(x -> (x + d1_next_day), arrayFilter(x -> (week_start_day > toDayOfWeek(addDays(d1_next_day, x)) OR toDayOfWeek(addDays(d1_next_day, x)) > week_end_day),
CASE WHEN (d2_date - d1_next_day) < 0 THEN [] ELSE range(abs(d2_date - d1_next_day)) END
)) as nonworkdays,
dateDiff('minute', toDateTime(d1), toDateTime(d2)) - 24 * 60 * length(nonworkdays) AS all_minture,
CASE WHEN (week_start_day > toDayOfWeek(d1_date) OR toDayOfWeek(d1_date) > week_end_day) THEN dateDiff('minute', toDateTime(d1), addDays(toStartOfDay(d1_date), 1)) ELSE 0 END AS d1_minture,
CASE WHEN (week_start_day > toDayOfWeek(d2_date) OR toDayOfWeek(d2_date) > week_end_day) THEN dateDiff('minute', toStartOfDay(d2_date), toDateTime(d2)) ELSE 0 END AS d2_minture,
all_minture - d1_minture - d2_minture AS work_minture

**Comment by Spratty59** [comment]
> Here is an example:
> 
> ```
> WITH 
>     toDate('2019-01-01') AS d1, 
>     today() AS d2
> SELECT length(arrayFilter(x -> ((toDayOfWeek(d1 + x) <= 5) AND ((d1 + x) NOT IN ('2019-01-01', '2019-01-02'))), range(toUInt64(d2 - d1)))) AS num_work_days
> 
> Here I create an array spanning all days between two dates, filter weekends and a list of public holidays (after NOT IN), then calculate the length.
> 

Hey, when I try to use this (working with a table) I get an error on the 'range' section where is states that there are illegal types: DateTime64(3), any idea how to resolve this?
