### ISSUE TITLE
Multiple Clickhouse in one server

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#7702]
Hi, I want to build multiple clickhouse databases in a single server. so, I search for `.tar` file of clickhouse. but, I can`t find it.

**Comment by alexey-milovidov** [comment]
Do you want to build different clickhouse variants from source?
Or you want to run multiple clickhouse binaries on a single server?
What kind of tarball do you need?

**Comment by chu1070y** [comment]
I want to run multiple clickhouse binaries on a single server.

**Comment by den-crane** [comment]
> I want to run multiple clickhouse binaries on a single server.

Then you don't need tar ball. Just install CH version you need using deb or rpm and run using different configs.

clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server1.pid --config-file=/etc/clickhouse-server/config1.xml

clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server2.pid --config-file=/etc/clickhouse-server/config2.xml

clickhouse-server --daemon --pid-file=/var/run/clickhouse-server/clickhouse-server3.pid --config-file=/etc/clickhouse-server/config3.xml

**Comment by chu1070y** [comment]
Sorry, I misunderstood the question.

Could you tell me the way how to build different clickhouse variants?

**Comment by den-crane** [comment]
It's much much easier to unpack .deb or .rpm and take clickhouse binary.

If you really want to build here is the doc https://clickhouse.yandex/docs/en/development/build/
