### ISSUE TITLE
array/list support in clickhouse client for parquet and orc format

### ISSUE THREAD

**Issue by guanlisheng** [ClickHouse/ClickHouse#7704]
(you don't have to strictly follow this form)

**Use case**
we are generating many orc/parquet files every day and the array is heavily used.  it works well with HIVE/Presto while is not supported in ClickHouse client 

**Describe the solution you'd like**
ClickHouse client would support array/list 

**Describe alternatives you've considered**
reading the orc/parquet in the program and convert them to INSERT statements

**Comment by filimonov** [comment]
It would be good if you will provide more info: docs & samples  (data / schema files) 

Code is here:
https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Processors/Formats/Impl/ArrowColumnToCHColumn.cpp

Also #4903

**Comment by guanlisheng** [comment]
hi @filimonov 

i think [ArrowColumnToCHColumn.cpp](https://github.com/ClickHouse/ClickHouse/blob/817c93f5d05ad0c57663d40d996fefe6df15dd40/dbms/src/Processors/Formats/Impl/ArrowColumnToCHColumn.cpp#L55) had explained the array is not supported yet.

also the same desc from its [documentation](https://clickhouse.yandex/docs/v19.17/en/interfaces/formats/#data-format-parquet).

**Comment by guanlisheng** [comment]
or we just just a line as like `{arrow::Type::LIST, "Array"},`

**Comment by guanlisheng** [comment]
@proller and @alexey-milovidov ,  thoughts?

**Comment by filimonov** [comment]
Check https://github.com/ClickHouse/ClickHouse/pull/8334 + comments

**Comment by guanlisheng** [comment]
not quite sure what's the final conclusion after checking #8334, especially for the last comment saying Arrow supports Array/List already.

**Comment by alexey-milovidov** [comment]
Writing of Array into Parquet is not implemented at this moment.

**Comment by filimonov** [comment]
Apache Arrow recently added support for lists parsing from Parquet. 
https://issues.apache.org/jira/browse/ARROW-1644

And I guess now we can also add support for that. 

@maxulan are you interested in that task?

**Comment by Avogar** [comment]
Arrays support was added in https://github.com/ClickHouse/ClickHouse/pull/21770
