### ISSUE TITLE
arraySplit usage lead to: Data compressed with different methods exception

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7708]
```
Exception on client:
Code: 271. DB::Exception: Data compressed with different methods, given method byte 00, previous method byte 82: while receiving packet from localhost:9000
```

**Comment by alesapin** [comment]
Provide trace from clickhouse-server.log file, please.

**Comment by Tasselmi** [comment]
> Provide trace from clickhouse-server.log file, please.

```
WITH arrayFilter(x -> (x > 3), [0, 1, 2]) AS arr
SELECT arraySplit(x -> (x < 0), arr) AS sp

↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.)
Exception on client:
Code: 271. DB::Exception: Data compressed with different methods, given method byte 83, previous method byte 82: while receiving packet from localhost:9000

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.16.2 revision 54427.
```

maybe you can reproduce, very simple.

**Comment by alesapin** [comment]
Trace looks like this:
```
2019.11.11 15:56:14.150567 [ 116 ] {7c5a3220-80d7-4495-a171-6d53331fb08e} <Error> executeQuery: Code: 47, e.displayText() = DB::Exception: Missing columns: 'arr' while processing query: 'SELECT arraySplit(x -> (x < 0), arr) AS sp', required columns: 'arr', source columns: 'dummy' (version 19.15.1.1) (from [::1]:42930) (in query: SELECT arraySplit(x -> (x < 0), arr) AS sp), Stack t
race:

0. 0x67f00b7 StackTrace::StackTrace() /home/alesap/code/cpp/ClickHouse/dbms/src/Common/StackTrace.cpp:228
1. 0x9f8cb2d DB::SyntaxAnalyzerResult::collectUsedColumns(std::__1::shared_ptr<DB::IAST> const&, DB::NamesAndTypesList const&) /home/alesap/code/cpp/ClickHouse/dbms/src/Common/Exception.h:0
2. 0x9f91ef1 DB::SyntaxAnalyzer::analyze(std::__1::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::IStorage>, DB::NamesAndTypesList
 const&) const /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/new:238
3. 0x9d3fbee DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::
basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_1::operator()() const /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:4215
4. 0x9d3e1a8 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::
basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterSelectQuery.cpp:399
5. 0x9d3da87 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /home/a
lesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterSelectQuery.cpp:176
6. 0x9ea2f75 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >
 > const&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:2147
7. 0x9d2118e std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions>(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:2147
8. 0x9d207e6 DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterFactory.cpp:0
9. 0x9fd97a9 DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*, bool) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/executeQuery.cpp:0
10. 0x9fd8d74 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/executeQuery.cpp:568
11. 0x68a6986 DB::TCPHandler::runImpl() /home/alesap/code/cpp/ClickHouse/dbms/programs/server/TCPHandler.cpp:0
12. 0x68af89c DB::TCPHandler::run() /home/alesap/code/cpp/ClickHouse/dbms/programs/server/TCPHandler.cpp:0
13. 0xa6f6e0c Poco::Net::TCPServerConnection::start() /home/alesap/code/cpp/ClickHouse/contrib/poco/Net/src/TCPServerConnection.cpp:57
14. 0xa6f72b6 Poco::Net::TCPServerDispatcher::run() /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/atomic:1036
15. 0xac8b43a Poco::PooledThread::run() /home/alesap/code/cpp/ClickHouse/contrib/poco/Foundation/include/Poco/Mutex_STD.h:132
16. 0xac8905b Poco::ThreadImpl::runnableEntry(void*) /home/alesap/code/cpp/ClickHouse/contrib/poco/Foundation/include/Poco/SharedPtr.h:156
17. 0xac8a8ab void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), Poco::ThreadImpl*> >(void*) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:2648
18. 0x7f1dd18c96db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
19. 0x7f1dd13ee88f clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by Tasselmi** [comment]
> Trace looks like this:
> 
> ```
> 2019.11.11 15:56:14.150567 [ 116 ] {7c5a3220-80d7-4495-a171-6d53331fb08e} <Error> executeQuery: Code: 47, e.displayText() = DB::Exception: Missing columns: 'arr' while processing query: 'SELECT arraySplit(x -> (x < 0), arr) AS sp', required columns: 'arr', source columns: 'dummy' (version 19.15.1.1) (from [::1]:42930) (in query: SELECT arraySplit(x -> (x < 0), arr) AS sp), Stack t
> race:
> 
> 0. 0x67f00b7 StackTrace::StackTrace() /home/alesap/code/cpp/ClickHouse/dbms/src/Common/StackTrace.cpp:228
> 1. 0x9f8cb2d DB::SyntaxAnalyzerResult::collectUsedColumns(std::__1::shared_ptr<DB::IAST> const&, DB::NamesAndTypesList const&) /home/alesap/code/cpp/ClickHouse/dbms/src/Common/Exception.h:0
> 2. 0x9f91ef1 DB::SyntaxAnalyzer::analyze(std::__1::shared_ptr<DB::IAST>&, DB::NamesAndTypesList const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::shared_ptr<DB::IStorage>, DB::NamesAndTypesList
>  const&) const /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/new:238
> 3. 0x9d3fbee DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::
> basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)::$_1::operator()() const /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:4215
> 4. 0x9d3e1a8 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, std::__1::shared_ptr<DB::IBlockInputStream> const&, std::__1::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::
> basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterSelectQuery.cpp:399
> 5. 0x9d3da87 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /home/a
> lesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterSelectQuery.cpp:176
> 6. 0x9ea2f75 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::__1::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >
>  > const&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:2147
> 7. 0x9d2118e std::__1::__unique_if<DB::InterpreterSelectWithUnionQuery>::__unique_single std::__1::make_unique<DB::InterpreterSelectWithUnionQuery, std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions>(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::SelectQueryOptions&&) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:2147
> 8. 0x9d207e6 DB::InterpreterFactory::get(std::__1::shared_ptr<DB::IAST>&, DB::Context&, DB::QueryProcessingStage::Enum) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/InterpreterFactory.cpp:0
> 9. 0x9fd97a9 DB::executeQueryImpl(char const*, char const*, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, DB::ReadBuffer*, bool) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/executeQuery.cpp:0
> 10. 0x9fd8d74 DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum, bool, bool) /home/alesap/code/cpp/ClickHouse/dbms/src/Interpreters/executeQuery.cpp:568
> 11. 0x68a6986 DB::TCPHandler::runImpl() /home/alesap/code/cpp/ClickHouse/dbms/programs/server/TCPHandler.cpp:0
> 12. 0x68af89c DB::TCPHandler::run() /home/alesap/code/cpp/ClickHouse/dbms/programs/server/TCPHandler.cpp:0
> 13. 0xa6f6e0c Poco::Net::TCPServerConnection::start() /home/alesap/code/cpp/ClickHouse/contrib/poco/Net/src/TCPServerConnection.cpp:57
> 14. 0xa6f72b6 Poco::Net::TCPServerDispatcher::run() /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/atomic:1036
> 15. 0xac8b43a Poco::PooledThread::run() /home/alesap/code/cpp/ClickHouse/contrib/poco/Foundation/include/Poco/Mutex_STD.h:132
> 16. 0xac8905b Poco::ThreadImpl::runnableEntry(void*) /home/alesap/code/cpp/ClickHouse/contrib/poco/Foundation/include/Poco/SharedPtr.h:156
> 17. 0xac8a8ab void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void* (*)(void*), Poco::ThreadImpl*> >(void*) /home/alesap/code/cpp/ClickHouse/contrib/libcxx/include/memory:2648
> 18. 0x7f1dd18c96db start_thread /lib/x86_64-linux-gnu/libpthread-2.27.so
> 19. 0x7f1dd13ee88f clone /build/glibc-OTsEL5/glibc-2.27/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:97
> ```

add `\` as below:
```
WITH arrayFilter(x -> (x > 3), [0, 1, 2]) AS arr \
SELECT arraySplit(x -> (x < 0), arr) AS sp
```

**Comment by filimonov** [comment]
@alesapin there is no exception on the server side. But it do some wierd stuff.
```
echo 'WITH arrayFilter(x -> (x > 3), [0, 1, 2]) AS arr SELECT arraySplit(x -> (x < 0), arr) AS sp' | curl 'http://localhost:8123/' --data-binary @-
[[208]]
mfilimonov@laptop5591:~$ echo 'WITH arrayFilter(x -> (x > 3), [0, 1, 2]) AS arr SELECT arraySplit(x -> (x < 0), arr) AS sp' | curl 'http://localhost:8123/' --data-binary @-
[[224]]
```

**Comment by filimonov** [comment]
Bit simpler example 
```
echo 'SELECT arraySplit(x -> (x < 0),  emptyArrayUInt8() ) AS sp' | curl 'http://localhost:8123/' --data-binary @-
```
