### ISSUE TITLE
cannot parse CSV with '\x7F' as delmiter. \x7F is ascii code.

### ISSUE THREAD

**Issue by xuxudede** [ClickHouse/ClickHouse#7711]
$clickhouse-client --host dbt20 --port 9000 --format_csv_delimiter='\x7F' --query="INSERT INTO dwzc.twb_m_top_organization FORMAT CSV" < /data/test_data/test.txt 
Code: 19, e.displayText() = DB::Exception: A setting's value string has to be an exactly one character long, Stack trace:

0. 0x563fac3bd7b0 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x563fac3bd585 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x563fac0ba051 ? /usr/bin/clickhouse
3. 0x563fb03d2c5d boost::program_options::variables_map::notify() /usr/bin/clickhouse
4. 0x563fac48413c DB::Client::init(int, char**) /usr/bin/clickhouse
5. 0x563fac46feef mainEntryClickHouseClient(int, char**) /usr/bin/clickhouse
6. 0x563fac2f9fed main /usr/bin/clickhouse
7. 0x7f1c99a2e3d5 __libc_start_main /usr/lib64/libc-2.17.so
8. 0x563fac3632ea _start /usr/bin/clickhouse
 (version 19.16.2.2 (official build))

**Comment by alexey-milovidov** [comment]
You have specified four characters: \, x, 7, F, as a delimiter, because escape sequence is not interpreted by your shell interpreter.

Write
```
clickhouse-client --host dbt20 --port 9000 --format_csv_delimiter=$'\x7F' --query="INSERT INTO dwzc.twb_m_top_organization FORMAT CSV" < /data/test_data/test.txt
```
instead (if you use `bash` as a shell interpreter).

**Comment by alexey-milovidov** [comment]
`man bash`, `QUOTING` section.

**Comment by xuxudede** [comment]
> You have specified four characters: \, x, 7, F, as a delimiter, because escape sequence is not interpreted by your shell interpreter.
> 
> Write
> 
> ```
> clickhouse-client --host dbt20 --port 9000 --format_csv_delimiter=$'\x7F' --query="INSERT INTO dwzc.twb_m_top_organization FORMAT CSV" < /data/test_data/test.txt
> ```
> 
> instead (if you use `bash` as a shell interpreter).
> Note the dollar sign before quote.

TKS

**Comment by xuxudede** [comment]
close
