### ISSUE TITLE
Add more informed message for kafka 

### ISSUE THREAD

**Issue by bespilotnayakartoshka** [ClickHouse/ClickHouse#7715]
**Use case**
During push messages to kafka some field of some message can be corrupted, for example. And when CH inserts whole block with invalid field it throws an unreadable exception 

```
void DB::StorageKafka::streamThread(): Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected " before:  BC","my_field":"value"}: (while read the value of key some_field): (at row 660)
```

So i cant understand what field of what message was invalid in this batch of thousands records:< 

**Describe the solution you'd like**
It would be great to have a more informative message for such error. Or more backtrace, or something :D 

// Or maybe there are some setting for it ? 

Thanks.

**Comment by filimonov** [comment]
Closing in advance to https://github.com/ClickHouse/ClickHouse/issues/7697
