### ISSUE TITLE
Segmentation fault on ClickHouse copier 

### ISSUE THREAD

**Issue by zhenggang0707** [ClickHouse/ClickHouse#7728]
Hi，when i use clickhouse-copier command，the information is below：
#clickhouse-copier --config-file=zookeeper.xml --task-path /clickhouse/copytasks/task1
Segmentation fault (core dumped)

Version of ClickHouse: 19.16.3.6 
Operating system: Ubuntu 16.04
Kernel version: 4.4.0-142-generic

pls tell me how to slove this problem,THK

**Comment by filimonov** [comment]
Please provide full stacktrace from the copier log, also copier config (if possible)

**Comment by alexey-milovidov** [comment]
Not enough info.
