### ISSUE TITLE
cmake with -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON

### ISSUE THREAD

**Issue by tlightsky** [ClickHouse/ClickHouse#7729]
**Operating system**
docker

**Cmake version**
3.10.2

**Ninja version**
1.8.2

**Compiler name and version**
g++-9

**Full cmake and/or ninja output**
CMake Error at contrib/mariadb-connector-c/mariadb_config/CMakeLists.txt:53 (ADD_EXECUTABLE):
  The install of the mariadb_config target requires changing an RPATH from
  the build tree, but this is not supported with the Ninja generator unless
  on an ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may
  be set to avoid this relinking step.

CMake Error at contrib/protobuf/cmake/protoc.cmake:5 (add_executable):
  The install of the protoc target requires changing an RPATH from the build
  tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  contrib/protobuf/cmake/CMakeLists.txt:199 (include)

CMake Error at CMakeLists.txt:385 (_add_executable):
  The install of the config-processor target requires changing an RPATH from
  the build tree, but this is not supported with the Ninja generator unless
  on an ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may
  be set to avoid this relinking step.
Call Stack (most recent call first):
  utils/config-processor/CMakeLists.txt:1 (add_executable)

CMake Error at CMakeLists.txt:385 (_add_executable):
  The install of the corrector_utf8 target requires changing an RPATH from
  the build tree, but this is not supported with the Ninja generator unless
  on an ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may
  be set to avoid this relinking step.
Call Stack (most recent call first):
  utils/corrector_utf8/CMakeLists.txt:1 (add_executable)

CMake Error at CMakeLists.txt:385 (_add_executable):
  The install of the clickhouse-zookeeper-cli target requires changing an
  RPATH from the build tree, but this is not supported with the Ninja
  generator unless on an ELF-based platform.  The
  CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set to avoid this relinking
  step.
Call Stack (most recent call first):
  utils/zookeeper-cli/CMakeLists.txt:1 (add_executable)

CMake Error at CMakeLists.txt:385 (_add_executable):
  The install of the clickhouse target requires changing an RPATH from the
  build tree, but this is not supported with the Ninja generator unless on an
  ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH variable may be set
  to avoid this relinking step.
Call Stack (most recent call first):
  dbms/programs/CMakeLists.txt:113 (add_executable)

CMake Error at CMakeLists.txt:385 (_add_executable):
  The install of the clickhouse-odbc-bridge target requires changing an RPATH
  from the build tree, but this is not supported with the Ninja generator
  unless on an ELF-based platform.  The CMAKE_BUILD_WITH_INSTALL_RPATH
  variable may be set to avoid this relinking step.
Call Stack (most recent call first):
  dbms/programs/odbc-bridge/CMakeLists.txt:42 (add_executable)

-- Generating done
-- Build files have been written to: /server/build_docker
ninja: error: loading 'build.ninja': No such file or directory

**Comment by tlightsky** [comment]
to resolve:
```
cmake -G Ninja /server -DCMAKE_C_COMPILER=`which gcc-9` -DCMAKE_CXX_COMPILER=`which g++-9` \
  -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
```

**Comment by dmitriy-myz** [comment]
I faced with same issue. Resolved without changing cmdline after removing `CMakeCache.txt` file. Or entire `build_docker`` directory.

**Comment by tlightsky** [comment]
@dmitriy-myz thanks, i'll try this way.
maybe also need to upgrade cmake too

**Comment by tlightsky** [comment]
it seems disappear when i build second time without `-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON`
