### ISSUE TITLE
upgrade g++-8 to g++-9 in build.sh

### ISSUE THREAD

**Issue by tlightsky** [ClickHouse/ClickHouse#7730]
https://github.com/ClickHouse/ClickHouse/blob/master/docker/builder/Dockerfile#L13

https://github.com/ClickHouse/ClickHouse/blob/master/docker/builder/build.sh#L6

need to upgrade

**Comment by filimonov** [comment]
Can you just send a PR?

**Comment by tlightsky** [comment]
yes, i need to wait for my first build done(in docker),
it have been about 24h

**Comment by tlightsky** [comment]
https://github.com/ClickHouse/ClickHouse/pull/7766
