### ISSUE TITLE
Issues with Temporary tables and readonly/cancel_http_readonly_queries_on_client_close setting

### ISSUE THREAD

**Issue by silviucpp** [ClickHouse/ClickHouse#7736]
Hello,

I'm trying to create a temporary table while using `readonly=2` and `cancel_http_readonly_queries_on_client_close = 1` on ClickHouse master. Based on the code temporary tables should work properly with this settings.

Running the following query:

```
curl -X POST \
  'http://127.0.0.1:8123/?query_id=1232&session_id=2&readonly=2&cancel_http_readonly_queries_on_client_close=1' \
  -d 'CREATE TEMPORARY TABLE `table_tmp1` AS SELECT 1 FORMAT JSON'
```
  
- Will never return. Query will run forever. 
- Removing `readonly=2` or `cancel_http_readonly_queries_on_client_close = 1` - query will run as expected.

From my findings problems is in `HttpHandler.cpp` line 602:

```
appendCallback([&context, &socket](const Progress &)
{
    /// Assume that at the point this method is called no one is reading data from the socket any more.
    /// True for read-only queries.
    try
    {
        char b;
        int status = socket.receiveBytes(&b, 1, MSG_DONTWAIT | MSG_PEEK);
        if (status == 0)
            context.killCurrentQuery();
    }
    catch (Poco::TimeoutException &)
    {
    }
    catch (...)
    {
        context.killCurrentQuery();
    }
});
```
Line:

```
int status = socket.receiveBytes(&b, 1, MSG_DONTWAIT | MSG_PEEK);
```

Blocks forever and never returns till connection get closed.

**Comment by silviucpp** [comment]
Seems at some point ClickHouse did a patch over poco and enabled `POCO_BROKEN_TIMEOUTS` on all platforms. 

Looking to `receiveBytes`  implementation if `_isBrokenTimeout` is true `MSG_DONTWAIT` is not 
taken into account when the `poll` is executed and will wait for `_recvTimeout` ms instead returning immediately.

```c++
int SocketImpl::receiveBytes(void* buffer, int length, int flags)
{
	if (_isBrokenTimeout)
	{
		if (_recvTimeout.totalMicroseconds() != 0)
		{
			if (!poll(_recvTimeout, SELECT_READ))
				throw TimeoutException();
		}
	}
	
	int rc;
	do
	{
		if (_sockfd == POCO_INVALID_SOCKET) throw InvalidSocketException();
		rc = ::recv(_sockfd, reinterpret_cast<char*>(buffer), length, flags);
	}
	while (_blocking && rc < 0 && lastError() == POCO_EINTR);
	if (rc < 0)
	{
		int err = lastError();
		if (err == POCO_EAGAIN && !_blocking)
			;
		else if (err == POCO_EAGAIN || err == POCO_ETIMEDOUT)
			throw TimeoutException(err);
		else
			error(err);
	}
	return rc;
}
```

**Comment by silviucpp** [comment]
I can confirm without https://github.com/ClickHouse-Extras/poco/compare/ea2516be366a73a02a82b499ed4a7db1d40037e0...7a2d304c21549427460428c9039009ef4bbfd899#diff-4115d3841de351d4ca12d8813cfb9026 works fine

**Comment by champtar** [comment]
@alesapin @akuzm it seems `POCO_BROKEN_TIMEOUTS` (https://github.com/ClickHouse-Extras/poco/commits/clickhouse/Net/include/Poco/Net/SocketDefs.h) breaks `cancel_http_readonly_queries_on_client_close`

**Comment by silviucpp** [comment]
@champtar Yes this was my finding as well.
