### ISSUE TITLE
MONTHNAME function

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#7741]
Moved from https://github.com/ClickHouse/clickhouse-odbc/issues/126

> Tableau 10.5 is generating the following SQL which is not implemented on clickhouse ODBC side -
> {fn MONTHNAME(CAST(Custom_SQL_Query.time AS DATE))}
> 
> Tableau formula used - DATENAME - https://onlinehelp.tableau.com/current/pro/desktop/en-us/functions_functions_date.html
> DATENAME('month', [Test Date])
> 
> I could not find equivalent function in clickhouse to convert to.

/cc @savelov

**Comment by alexey-milovidov** [comment]
Easy task after https://github.com/ClickHouse/ClickHouse/pull/23085 is implemented.
