### ISSUE TITLE
MySQL engine: mention as well "insert" queries 

### ISSUE THREAD

**Issue by heyciao** [ClickHouse/ClickHouse#7745]
**Current situation:**
The page https://clickhouse.yandex/docs/en/operations/table_engines/mysql/ states currently:
"_The MySQL engine allows you to perform SELECT queries on data that is stored on a remote MySQL server._"

**Problem:**
That statement is not wrong but users might understand that it's possible to perform **only** select-queries.
This would be incorrect as I can currently (at least as of version 19.13.1.11-r3) execute e.g. "insert into [remote_mariadb_tbl] select [something] from [ch_tbl]".

**Basic improvement proposal:**
Mention as well the INSERT-capability, for example (english is not my mothertongue...):
_The MySQL engine allows you to perform SELECT queries on data that is stored on a remote MySQL server and INSERT queries (into remote MySQL tables) by sourcing data that is stored in the local Clickhouse database._

**Further potential improvements:**
1)
Maybe mention as well some details about the "insert"s?
E.g. are there explicit commits? (e.g. maybe one per row or one per "chunk" of rows or maybe only one at the very end of all inserts?)
2)
The page https://clickhouse.yandex/docs/en/database_engines/mysql/ mentions as well bits and pieces of information (e.g. data types) that are probably useful for the above URL => maybe both pages can be merged?
Additionally the "create database"-statement was a bit scary for me => I didn't try it out (yet) but I assume that it just provides access to all tables that exist in the remote MySQL database => it might be good to be a bit more explicit about this :)

Cheers & thanks for your great DB!
Stefano

**Comment by BayoNet** [comment]
Thanx for your comments :-). I'll review these aricles and try to make them more clear and consistent.

**Comment by morozovsk** [comment]
done, you can close this ticket.

https://github.com/ClickHouse/ClickHouse/pull/24937
https://clickhouse.tech/docs/en/engines/table-engines/integrations/mysql/

**Comment by heyciao** [comment]
Thank you :)
