### ISSUE TITLE
Select time for ENGINE = Merge is 10 times slower after v18.16.1  

### ISSUE THREAD

**Issue by Girgitt** [ClickHouse/ClickHouse#7748]
**Describe the situation**
Versions 1.1.5364, 18.1.0, 18.10.3 and 18.12.17 execute query below in about 2s
Beginning from version 18.14.8 execution is longer by 1s (only one CPU core utilized during first 1s of execution) 
Beginning from version 18.16.1 execution takes over 20s and again - during initial stage only singe CPU core is utilized at 100%.

**How to reproduce**
* Which ClickHouse server version to use: 18.16.1
* Which interface to use, if matters: clickhouse-client
* Non-default settings, if any: --max_threads=24
* `CREATE TABLE` statements for all tables involved

720 tables like each with ~1mln values:
```sql
CREATE TABLE default.PAR_5D40DA00
(
   d Date DEFAULT CAST(0, 'Date'),
   ts UInt32,
   ids UInt32,
   tss Int32,
   stat UInt16,
   val Float32
)
ENGINE = MergeTree(d, (ids, ts), 8192)
```

one merge table: 
```sql
CREATE TABLE default.partitions_merge
(
   d Date DEFAULT CAST(0, 'Date'),
   ts UInt32,
   ids UInt32,
   tss Int32,
   stat UInt16,
   val Float32
)
ENGINE = Merge(default, '^PAR*') 
```

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

It's difficult to provide sample data due to the size of the data set. Each PAR_XXXXXXXX table has rows similar to this: 
```
┌──────────d─┬─────────ts─┬─ids─┬─tss─┬─stat─┬───────val─┐
│ 2019-07-31 │ 1564534550 │ 754 │   0 │  132 │ -0.021702 │
│ 2019-07-31 │ 1564534599 │ 755 │   0 │    0 │  0.059681 │
│ 2019-07-31 │ 1564534453 │ 756 │   0 │  132 │ -0.021702 │
│ 2019-07-31 │ 1564534687 │ 757 │   0 │    0 │  0.020798 │
│ 2019-07-31 │ 1564534453 │ 759 │   0 │    0 │  0.018085 │
│ 2019-07-31 │ 1564534454 │ 760 │   0 │  132 │ -0.019894 │
│ 2019-07-31 │ 1564534659 │ 762 │   0 │  132 │  -0.32915 │
│ 2019-07-31 │ 1564534601 │ 763 │   0 │    0 │   0.19532 │
│ 2019-07-31 │ 1564534759 │ 764 │   0 │    0 │  0.224256 │
│ 2019-07-31 │ 1564534468 │ 766 │   0 │    0 │  0.108511 │
└────────────┴────────────┴─────┴─────┴──────┴───────────┘
```

* Queries to run that lead to slow performance
```sql
select
   min(ids),
   toStartOfFiveMinute(toDateTime(min(ts),'UTC')) as date,
   min(stat) as stat_mn,
   max(stat) as stat_mx,
   min(val) as min_v,
   avg(val) as avg_val,
   max(val) as max_v,
   toDateTime(min(ts*val)/min_v,'UTC') as min_ts,
   toDateTime(max(ts*val)/max_v,'UTC') as max_ts, 
   sum((val+runningDifference(val)/2)*runningDifference(ts))/sum(runningDifference(ts)) AS avg_by_time,
   bar(avg_val,-10,100,40) as bar
from partitions_merge
where
       d > toDate('2019-06-01','UTC')  and d < toDate('2019-07-01','UTC')
  and ids >= 754 and ids < 1000
  and toDateTime(ts,'UTC')  > '2019-06-01 00:00:00' and toDateTime(ts,'UTC') < '2019-07-01 00:00:00'
group by ids,intDiv(toRelativeMinuteNum(toDateTime(ts, 'UTC'),'UTC'),60),stat
order by ids,min(ts)
limit 10;
```

**Expected performance**
Here is the summary of execution times for different CLH versions with the same data and query: 

Clh version | Execution time [s] | Execution summary
-- | -- | --
1.1.5364 | 2.2 | 10 rows   in set. Elapsed: 2.208 sec. Processed 47.05 million rows, 752.88 MB (21.31   million rows/s., 340.90 MB/s.)
18.1.0 | 2 | Cold:   10 rows in set. Elapsed: 6.960 sec. Processed 47.05 million rows, 752.88 MB   (6.76 million rows/s., 108.18 MB/s.)   Hot:  10 rows in set. Elapsed: 1.840 sec.   Processed 47.05 million rows, 752.88 MB (25.57 million rows/s., 409.08 MB/s.)
18.10.3 | 2.6 | 10 rows   in set. Elapsed: 2.629 sec. Processed 47.05 million rows, 752.88 MB (17.90   million rows/s., 286.41 MB/s.)
18.12.17 | 2.4 | 10 rows   in set. Elapsed: 2.405 sec. Processed 47.05 million rows, 752.88 MB (19.57   million rows/s., 313.08 MB/s.)
18.14.8 | 3.5 | 10 rows   in set. Elapsed: 3.555 sec. Processed 47.05 million rows, 752.88 MB (13.24   million rows/s., 211.79 MB/s.)
18.14.19 | 3.6 | 10 rows   in set. Elapsed: 3.379 sec. Processed 47.05 million rows, 752.88 MB (13.93   million rows/s., 222.82 MB/s.)
18.16.1 | 23 | 10 rows   in set. Elapsed: 23.689 sec. Processed 47.05 million rows, 752.88 MB (1.99   million rows/s., 31.78 MB/s.)
  |   |  

**Additional context**
In versions never than 18.12 There is a kind of delay right after the query is issued. During this initial delay only singe CPU core is utilized no matter what max_threads value is used by the clickhouse-client. Debug logging is different for versions <= 18.12 compared to versions >= 18.14.8:

18.12 and older:
![image](https://user-images.githubusercontent.com/10582029/68731874-d5b60100-05d1-11ea-9a9b-81935c55b1de.png)

18.14.8 and never:
![image](https://user-images.githubusercontent.com/10582029/68731915-f4b49300-05d1-11ea-8a26-090c889087ea.png)

**Comment by nvartolomei** [comment]
Can you try latest version first?

**Comment by filimonov** [comment]
Can you also do 
```
SET send_logs_level='trace';
```
before running your select, and compare the output / find the place where it get slower.

**Comment by Girgitt** [comment]
> Can you try latest version first?

I did - the latest version is where I noticed the issue and then started testing from the oldest version I knew worked fine (1.1.5365) till the first experiencing the issue (minor delay started in 18.14.8 and the considerable delay started in 18.16.1 - at the same level as in the newest version I ran which was 19.16.3.6). All these versions come from repository Altinity_clickhouse.

> Can you also do
> SET send_logs_level='trace';

The delay happens right after the query is issued - without any logging output for ~15s.

**Comment by filimonov** [comment]
Can you try to minimize the query? I.e. remove the parts which does not change that problem appearence

**Comment by den-crane** [comment]
`for i in {1..1000}; do    echo "CREATE TABLE default.PAR_${i} ( d Date DEFAULT CAST(0, 'Date'),ts UInt32,ids UInt32,tss Int32,stat UInt16,val Float32)ENGINE = MergeTree(d, (ids, ts), 8192)"|clickhouse-client; done`

original query:  Elapsed: 11.748 sec.

```
select
   min(ids),
   toStartOfFiveMinute(toDateTime(min(ts),'UTC')) as date,
   min(stat) as stat_mn,
   max(stat) as stat_mx
from default.partitions_merge

Elapsed: 3.821 sec.
```



```
select
   min(ids)
from default.partitions_merge
Elapsed: 1.555 sec.
```


```
select * from default.partitions_merge
Elapsed: 0.822 sec.
```

does not matter: set compile=0, compile_expressions=0,enable_optimize_predicate_expression=0,max_threads=1

**Comment by den-crane** [comment]
Engine Log. 1000 tables. Elapsed: 0.047 sec.

I think partition pruning optimization.  https://github.com/ClickHouse/ClickHouse/pull/2468

**Comment by Girgitt** [comment]
> Can you try to minimize the query? I.e. remove the parts which does not change that problem appearance

I had no luck in minimizing the query so far - it seems like any field in select part or where part of the query contributes to the initial delay. The less fields included the shorter delay but it's always there. Removing the partitioning field (d) from the query does not change anything - but I am not sure the exact implication of "partitioning pruning optimization" @den-crane mentions above and if removing  partitioning field from the query should change something or not.

**Comment by Girgitt** [comment]
This issue could be related to #8939 (?)
