### ISSUE TITLE
Updates in replicated tables

### ISSUE THREAD

**Issue by aditi6622** [ClickHouse/ClickHouse#7749]
When we update a table, the update's status gets updated in system.mutations table, you can easily check it with column is_done. When we apply the updates in tables with replication configured, if the is_done is set to 1 in one table, does it make sure that update is done in it's other replicas too, or we need to explicitly check for them. Kindly help,

**Comment by blinkov** [comment]
@aditi6622, is this question still relevant?

**Comment by simPod** [comment]
@blinkov I'd be interested

**Comment by blinkov** [comment]
@aditi6622, do you have any further questions?

**Comment by alexey-milovidov** [comment]
You can set `mutations_sync` setting to 1 for the query. When this setting enabled, the query will return success to the client only after mutation will be executed on every replica.

But if query will not return success (e.g. one replica is unavailable), mutation will be executed nevertheless. In that case, you have to check `system.mutations` on every replica manually.

**Comment by alexey-milovidov** [comment]
@simPod 

Unfortunately, @blinkov made himself a robot.
