### ISSUE TITLE
T64 CODEC not supported for Array Types

### ISSUE THREAD

**Issue by ifoo** [ClickHouse/ClickHouse#7753]
Using the T64 codec for Array types does not work.

Example:
```
localhost :) alter table t3 add column target_file_size_t64 Array(UInt64) CODEC(T64, LZ4);

ALTER TABLE t3
    ADD COLUMN
    `target_file_size_t64` Array(UInt64) CODEC(T64, LZ4)


Received exception from server (version 19.16.2):
Code: 431. DB::Exception: Received from localhost:9000. DB::Exception: T64 codec is not supported for specified type.
```
To be honest, I'm not sure if T64 codec even makes sense for Array fields. Please close the ticket if you find that it would be useless.

**Comment by 4ertus2** [comment]
It's possible to make T64 codec for fixed sized Arrays that use own min-max pairs for each array position. It's also possible to make the codec for general Arrays with one min-max for all the Array's positions. Both cases have some restrictions.

I think we should not add such a support fo Arrays now but we may implement generalized packed ```Integer``` and ```UInteger``` in future. Then it would be ```Array(UInteger)``` in colum declaration and something like ```toUInt64(a[1])``` in use.
