### ISSUE TITLE
LowCardinality(FixedString(x)) with default value

### ISSUE THREAD

**Issue by zenwarr** [ClickHouse/ClickHouse#7754]
**Describe the bug or unexpected behaviour**
When using default value for a field with LowCardinality(FixedString(x)) type, a garbage values are returned instead of default values.

**How to reproduce**
ClickHouse 19.16.3.6

```
CREATE TABLE test
(
  id   UInt32,
  code LowCardinality(FixedString(2)) DEFAULT '--'
) ENGINE = MergeTree() PARTITION BY id ORDER BY id;

INSERT INTO test FORMAT CSV 1,RU

INSERT INTO test FORMAT CSV 1,

SELECT * FROM test;
```

**Expected behavior**
Should return the following rows:
```
1, '--'
1, 'RU'
```

Instead of it, first row contains garbage instead of default value, for example:

![screenshot-2019-11-13T18-11-09](https://user-images.githubusercontent.com/1969391/68762782-0ed98a00-0641-11ea-8b30-0c4989db6b53.png)

**Comment by alexey-milovidov** [comment]
Fixed in recent releases.
