### ISSUE TITLE
Broken multi-line paste in clickhouse-client

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#7757]
I paste multiple lines with queries into clickhouse-client, each on its line:

```
DROP TABLE IF EXISTS userid_test;

SET use_index_for_in_with_subqueries = 1;
```

I expect them to run one after another -- it worked this way at least in 19.15, it works this way in bash, psql, etc.

What I get instead:

```
:) DROP TABLE IF EXISTS userid_test;

SET use_index_for_in_with_subqueries = 1;

Syntax error (Multi-statements are not allowed): failed at position 33 (end of query) (line 1, col 33):
```

**Comment by filimonov** [comment]
I'm also hitting that last week. 

Also you always need to press Enter after pasting some query. 

One workaround is to run clickhouse with -nm parameters, but in that case `exit` command doesn't work (only Ctrl+C) :D

I think it's caused by https://github.com/ClickHouse/ClickHouse/pull/7492

**Comment by amosbird** [comment]
@akuzm multi-statement pasting now requires `-n` after https://github.com/ClickHouse/ClickHouse/pull/7492 . (I wonder if that should be the default value)

> Also you always need to press Enter after pasting some query.

 @filimonov  hmm, I favor the opposite, to validate (or do small changes to) the query that has been pasted instead of running it directly.

> but in that case exit command doesn't work  

Interesting! That deserves a fix.

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/7760

**Comment by akuzm** [comment]
I think we should not change the default behavior without a strong reason, even more so if we're changing it to something different from every other console client.

**Comment by amosbird** [comment]
Fair enough. I've made it optional and default to false.

**Comment by alexey-milovidov** [comment]
@amosbird If we will made it optional, it will not be used in 99.99% cases, and the code is non-trivial, so better to remove the code at all.

**Comment by amosbird** [comment]
Ok, I've changed to only enable `bracketed-paste` when multiline is disabled. I think it should be non-intrusive.

**Comment by amosbird** [comment]
Ok, I've changed it to only enable `bracketed-paste` when `multiquery` is enabled. This should be less intrusive.

**Comment by Tasselmi** [comment]
why not just learn from `scala` or spark?

`:paste` to start copy code , and `ctrl+d` to start interpret....
just advice.

actually `\` is not friendly , because I have to remove all the `\` to run in `tabix` or other  program.

**Comment by Tasselmi** [comment]
so  now  how can I input multi-line sql code?
can you guys give me a example?
I have work to accomplish. thanks

**Comment by filimonov** [comment]
@Tasselmi just run clickhouse-client with `-m` switch, and it start executing only after you finish the line with semicolon.
