### ISSUE TITLE
Drop in writes on high number of selects.

### ISSUE THREAD

**Issue by SreekanthMannari** [ClickHouse/ClickHouse#7765]
Version: ClickHouse 19.13.1.11
Server has 400GB RAM with 48 CPU cores. and 3.2 TB of HDD.
Insert batch size is 20K records (~40MB). Each insert is taking ~1.5secs.
Server has 12.5B records.
We are running parallel select queries of ~500. Selects include some count queries, some aggregations and group bys.
CPU and RAM are at their minimals (like 10% of CPU and 10GB of RAM used).
During this time, inserts are dropped. Noticed "TimeoutExceptions" on client side (Using Http Client for inserts)
Get below exception at high rate. (very few select queries went through)

Code: 202, e.displayText() = DB::Exception: Too many simultaneous queries. Maximum: 100 (version 19.13.1.11 (official build))

Tried to increase max simultaneous queries in config.xml (to 1000).
 <max_concurrent_queries>1000</max_concurrent_queries>

Even after increasing, exception still says Maximun: 100
Code: 202, e.displayText() = DB::Exception: Too many simultaneous queries. Maximum: 100 (version 19.13.1.11 (official build))

Seems my change is not taking effect.

How can I make sure that writes are not impacted due to reads?
Why cant I increase simultaneous queries in spite of having RAM and MEMORY available?
How can we support more selects? (we need little higher selects to build dashboards, aggregations, and for AD purposes)

**Comment by den-crane** [comment]
Did you restarted CH after setting max_concurrent_queries ?

**Comment by SreekanthMannari** [comment]
No. I haven't restarted.
But config.xml in "preprocessed_configs" folder shows my change.

**Comment by den-crane** [comment]
>But config.xml in "preprocessed_configs" folder shows my change.

It does not matter. All parameters from config.xml (except cluster & dictionaries configurations) require CH reboot.

**Comment by SreekanthMannari** [comment]
Thanks. Setting worked after CH reboot. 
Does reboot needed even for User.xml changes like max memory settings?

**Comment by den-crane** [comment]
>Does reboot needed even for User.xml changes like max memory settings?

No, changes in user.xml does not need reboot.

**Comment by haiertashu** [comment]
how to make sure the server settings modified such as 'max_concurrent_queries' taking effect ？ where/which system table can show the latest changes？ or any other way
