### ISSUE TITLE
add the trace_log config but the table is not created

### ISSUE THREAD

**Issue by anheicang** [ClickHouse/ClickHouse#7767]
version: 19.15.3.6

config.xml

      <metric_log>
          <database>system</database>
          <table>metric_log</table>
          <flush_interval_milliseconds>7500</flush_interval_milliseconds>
          <collect_interval_milliseconds>1000</collect_interval_milliseconds>
      </metric_log>
      <trace_log>
          <database>system</database>
          <table>trace_log</table>
          <partition_by>toYYYYMM(event_date)</partition_by>
          <flush_interval_milliseconds>7500</flush_interval_milliseconds>
       </trace_log>  
the metric_log is ok,but cant find trace_log.

**Comment by den-crane** [comment]
You have to enable logging in a session `set log_queries = 1;`
or in users's profie ` <log_queries>1</log_queries>`

**Comment by anheicang** [comment]
> You have to enable logging in a session `set log_queries = 1;`
> or in users's profie ` <log_queries>1</log_queries>`

log_queries already enable, and query_log,metric_log all in system,only trace_log not

**Comment by filimonov** [comment]
May be you should increase query_profiler_real_time_period_ns / query_profiler_cpu_time_period_ns ? By default it's 1000000000, i.e. 1 second, so if your queries finishes faster than 1 sec, you will not get anything in trace_log. 

Check the test:
https://github.com/ClickHouse/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00974_query_profiler.sql

**Comment by anheicang** [comment]
> May be you should decrease `query_profiler_real_time_period_ns` / `query_profiler_cpu_time_period_ns` ?
> 
> By default both are set to 1000000000, i.e. 1 second, so if your queries finishes faster than 1 sec, you will not get anything in `trace_log`. Try longer queries or smaller values for `query_profiler_real_time_period_ns` / `query_profiler_cpu_time_period_ns`.
> 
> Check the test:
> https://github.com/ClickHouse/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00974_query_profiler.sql

thanks a lot~!
