### ISSUE TITLE
Better understanding of ClickHouse memory usage

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#7778]
I’m trying to understand what ClickHouse is using memory for. It seems that the task is not obvious and you need to collect details in pieces:
* dictionaries
* marks cache
* uncompressed cache
* running queries
* currently executed materialized views
* buffer tables
* memory / temporary tables
* background merges
* kafka
etc.

It seems that this can / should be improved.

For example, it seems impossible to understand how much memory the tables with the Join / Set engine use.

Also: do all memory allocations happen through jemalloc? How can be explained the difference between RSS and jemalloc.resident / jemalloc.allocated? 

The number are usually quite close, but not always:
```bash
$ clickhouse-client --query="select formatReadableSize(value) from system.asynchronous_metrics where metric='jemalloc.allocated'";
1.39 GiB
$ cat /proc/$(pidof clickhouse-server)/status | grep RSS
VmRSS:   2082916 kB

➜ clickhouse-client --query="select formatReadableSize(value) from system.asynchronous_metrics where metric='jemalloc.resident'";
1.79 GiB
➜ cat /proc/$(pidof clickhouse-server)/status | grep RSS
VmRSS:   1487000 kB

# clickhouse-client --query="select formatReadableSize(value) from system.asynchronous_metrics where metric='jemalloc.allocated'";
6.77 GiB
# cat /proc/$(pidof clickhouse-server)/status | grep RSS
VmRSS:   5780148 kB
```

**Comment by filimonov** [comment]
Also  #6387

**Comment by hustnn** [comment]
In addition to memory profiler, how about also add the cpu usage profiler for each stream (operator)? 

I am looking at it.

**Comment by blinkov** [comment]
@filimonov, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@hustnn We already have CPU profiler for ClickHouse queries.

https://clickhouse.tech/docs/en/operations/optimizing-performance/sampling-query-profiler/

**Comment by alexey-milovidov** [comment]
> Also: do all memory allocations happen through jemalloc?

No, some allocations goes to mmap directly.

**Comment by alexey-milovidov** [comment]
> For example, it seems impossible to understand how much memory the tables with the Join / Set engine use.

Yes, Join and Set are not instrumented enough.

**Comment by robot-clickhouse** [comment]
@filimonov, do you have any further questions?

**Comment by alexey-milovidov** [comment]
I'm happy to say that Set, Join and Buffer tables has been instrumented and their memory usage info is available in `system.tables` table.

For other parts this task is too generic - not actionable.
