### ISSUE TITLE
Column is ambiguous on join

### ISSUE THREAD

**Issue by mah-most** [ClickHouse/ClickHouse#7781]
**Description**
When joining one table with another two that having same column name, if using an alias with the same name as the column, an exception will throw indicating the column is ambiguous.

**How to reproduce**
```
CREATE TABLE default.a (
 col1 UInt64
)
ENGINE = MergeTree
ORDER BY col1;

CREATE TABLE default.b (
 col1 UInt64
)
ENGINE = MergeTree
ORDER BY col1;

CREATE TABLE default.c (
 col1 UInt64
)
ENGINE = MergeTree
ORDER BY col1;

SELECT
  a.col1 AS col1
FROM
  `default`.a
LEFT JOIN `default`.b ON  a.col1 = b.col1
LEFT JOIN `default`.c ON  a.col1 = c.col1
```

The select query about will throw this exception:
```
SQL Error [352]: ClickHouse exception, code: 352, host: localhost, port: 8124; Code: 352, e.displayText() = DB::Exception: Column 'col1' is ambiguous (version 19.16.3.6 (official build))
```

The current problem happening on the official Docker version of 19.16 however on the version 19.4 the query execute with no problem.

**Comment by aslojno** [comment]
Have the same problem on 19.16. 19.4 worked properly

**Comment by aslojno** [comment]
The problem is solved by adding aliases for all duplicate column names, e.g.:

```
SELECT
  a.col1 AS col1
FROM
  `default`.a
LEFT JOIN (SELECT col1 AS "col1_from_b" FROM `default`.b) ON  a.col1 = b.col1_from_b
LEFT JOIN (SELECT col1 AS "col1_from_c" FROM `default`.c) ON  a.col1 = `c.col1_from_c
```

**Comment by 4ertus2** [comment]
Related #8169
