### ISSUE TITLE
Predicate push-down doesn't respect WITH FILL in the inner query

### ISSUE THREAD

**Issue by ghuname** [ClickHouse/ClickHouse#7784]
**Describe the bug or unexpected behaviour**

```
SELECT *
FROM (
	SELECT startOf15MinInterval
	FROM (
		SELECT toDateTime('2019-11-14 22:15:00') startOf15MinInterval
		UNION ALL
		SELECT toDateTime('2019-11-15 01:15:00') startOf15MinInterval
		)
	ORDER BY startOf15MinInterval
	WITH fill step 900
	)
where startOf15MinInterval < toDateTime('2019-11-15 00:15:00')
```

returns a single row, and it should return all rows less then 2019-11-15 00:15:00.

* Which ClickHouse server version to use

ClickHouse client version 19.16.3.6.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.16.3 revision 54427.

Regards.

**Comment by filimonov** [comment]
Workaround: 
`set enable_optimize_predicate_expression=0;`

It looks like that optimization should be disabled for WITH FILL.

/cc @zhang2014

**Comment by ghuname** [comment]
I confirm that workaround with select ... settings enable_optimize_predicate_expression=0 works.

**Comment by zhang2014** [comment]
@filimonov disabled it in #7789

**Comment by ghuname** [comment]
I confirm that workaround with select ... settings enable_optimize_predicate_expression=0 works.
