### ISSUE TITLE
ALTER TABLE FREEZE should return snapshot ID as result

### ISSUE THREAD

**Issue by ifoo** [ClickHouse/ClickHouse#7785]
Running `ALTER TABLE FREEZE` currently does not return the incremental snapshot ID. I can only get it from the `./shadow/increment.txt` file:

```
localhost :) ALTER TABLE stats FREEZE

ALTER TABLE stats
    FREEZE


Ok.

0 rows in set. Elapsed: 0.018 sec.
```
Assuming there are multiple processes making snapshots, I would like to know the snapshot ID when issuing the FREEZE query. Otherwise I can not be sure, which snapshot was the one that I issued.

What I would like to see:
```
localhost :) ALTER TABLE stats FREEZE

ALTER TABLE stats
    FREEZE

┌─snapshot_id─┐
│           3 │
└─────────────┘

1 rows in set. Elapsed: 0.001 sec.
```

Alternatively, also the 'outcome' could be reported (ok, error, ...) in the result.

**Comment by nvartolomei** [comment]
Can't think of a good way to change current behaviour as ALTERs can be chained.

Ie what should be returned in the following case?

```
ALTER TABLE t
    FREEZE,
    ADD COLUMN
    `x` UInt8


Ok.

0 rows in set. Elapsed: 0.004 sec
```

**Comment by nvartolomei** [comment]
Let's have a `FREEZE TABLE [db.]name [PARTITION partition_expr]`, @alexey-milovidov?

**Comment by nvartolomei** [comment]
Workaround 

```sql
ALTER TABLE system.query_log
    FREEZE WITH NAME 'random-string-xyz'
```

```txt
Freezing part 201912_41_41_0 snapshot will be placed at /home/nv/clickhouse-testbed/srv1/data/shadow/random%2Dstring%2Dxyz
```

**Comment by alexey-milovidov** [comment]
It's also possible to get the info with `SET send_logs_leve = 'trace'`.

**Comment by akuzm** [comment]
> Can't think of a good way to change current behaviour as ALTER commands can be chained.

Can we forbid the chaining in case there is a FREEZE? Apart from this, are there other reasons to add new syntax?

**Comment by nvartolomei** [comment]
> Can we forbid the chaining in case there is a FREEZE? Apart from this, are there other reasons to add new syntax?

Breaking change?

We might also output result if there is one alter command and do not output if there are no commands but code might get dirty and behaviour might be a bit surprising to users.

**Comment by alesapin** [comment]
Done here https://github.com/ClickHouse/ClickHouse/pull/13017
