### ISSUE TITLE
JSON serialization/deserialization for named tuples

### ISSUE THREAD

**Issue by millin** [ClickHouse/ClickHouse#7787]
**Use case**
Allow JSON-objects inside of JSON-bases formats.

**Describe the solution you'd like**
Currently, names are lost when named tuple serialized to JSON.
```
SELECT CAST((1, 'Test'), 'Tuple( a Int8,  b String)') AS j
FORMAT JSONEachRow

{"j":[1, "Test"]}
```

The idea is to use objects instead of arrays for serialization of named tuples
```
{"j":{"a": 1, "b": "Test"}}
```

**Comment by alexey-milovidov** [comment]
AFAIK it can be supported under a setting after #17310

**Comment by alexey-milovidov** [comment]
Formatting is already implemented by @akuzm here: #17175.

**Comment by alexey-milovidov** [comment]
This task is completely solved: both parsing and formatting of named Tuples work for now.

**Comment by sriram-adpusuhup** [comment]
Hey guys. Is there any documentation for this? 
The [documentation](https://clickhouse.com/docs/en/sql-reference/data-types/tuple/) for Tuples still say that json is treated as arrays. ( Attached Screenshot below )
<img width="1197" alt="Screenshot 2021-09-21 at 12 14 45 AM" src="https://user-images.githubusercontent.com/60172790/134057061-0f720feb-503b-4bf4-a4c2-2f13b80f8950.png">

**Comment by CurtizJ** [comment]
Formatting of named tuples in JSON formats is controlled  by setting `output_format_json_named_tuples_as_objects`. You are right, need to add it to documentation.

**Comment by frafra** [comment]
It has been added here: https://clickhouse.com/docs/en/sql-reference/data-types/json#displaying-json-columns
