### ISSUE TITLE
system table replication_queue is not documented in EN and RU documentation

### ISSUE THREAD

**Issue by shinguz** [ClickHouse/ClickHouse#78]
system table replication_queue is not documented in EN and RU documentation

https://clickhouse.yandex/reference_ru.html#%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D1%8B%D0%B5%20%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B

https://clickhouse.yandex/reference_en.html#System%20tables

please update.

**Comment by jackpgao** [comment]
+1

**Comment by olgarev** [comment]
@alexey-milovidov Documented, please remove the `comp-documentation` label.

**Comment by alexey-milovidov** [comment]
Alright.

**Comment by alexey-milovidov** [comment]
> please remove the comp-documentation label.

You mean: this task can be closed as fixed.
