### ISSUE TITLE
keyword with can not alias table_name

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7803]
```
WITH (SELECT dt, app_id, count() FROM test.test GROUP BY dt, app_id) AS tba
SELECT * FROM tba
UNION ALL
SELECT * FROM tba

Received exception from server (version 19.17.2):
Code: 60. DB::Exception: Received from localhost:9000. DB::Exception: Table default.tba doesn't exist..
```

**Comment by Tasselmi** [comment]
in hive, I can write it like this and it works fine :
```
WITH tba AS (SELECT * FROM test.test LIMIT 10)
SELECT * FROM tba
UNION ALL
SELECT * FROM tba
```

**Comment by zhang2014** [comment]
Try using ``WITH (SELECT dt, app_id, count() FROM test.test GROUP BY dt, app_id) AS `tba` ``

**Comment by den-crane** [comment]
for now CH supports only 

```
WITH (SELECT dt, app_id, count() FROM test.test GROUP BY dt, app_id) AS tba
SELECT * FROM tba
UNION ALL
WITH (SELECT dt, app_id, count() FROM test.test GROUP BY dt, app_id) AS tba
SELECT * FROM tba
```

**Comment by Tasselmi** [comment]
> for now CH supports only
> 
> ```
> WITH (SELECT dt, app_id, count() FROM test.test GROUP BY dt, app_id) AS tba
> SELECT * FROM tba
> UNION ALL
> WITH (SELECT dt, app_id, count() FROM test.test GROUP BY dt, app_id) AS tba
> SELECT * FROM tba
> ```

I tested, and it does not support at all.

**Comment by den-crane** [comment]
I see now.
CH `WITH` supports scalars only. 

with (select 1) as x select x

with (select 1) as x select x union all with (select 1) as x select x

select y from (with (select 1) as x select x as y)

**Comment by Tasselmi** [comment]
> I see now.
> CH `WITH` supports scalars only.
> 
> with (select 1) as x select x
> 
> with (select 1) as x select x union all with (select 1) as x select x
> 
> select y from (with (select 1) as x select x as y)

cry....
