### ISSUE TITLE
Select with field rename and condition performance degradation

### ISSUE THREAD

**Issue by dotNox** [ClickHouse/ClickHouse#7804]
Hello,

After an upgrade from a older version ( unfortunately I do not remember what version has been used previously ) to 19.15.3.6 noticed that same quite simple query takes significantly more time to execute. It turned out that for some reason it reads from disk more partitions that it should.

It seems that the cause of this is that we use the same "key" in select ( after AS ... ) and in condition. 

For example:
Table structure
```
CREATE TABLE nfa.flows3 (
`ts` DateTime, 
`type` Enum8('netflow' = 0, 'sflow' = 1), 
`datagram_version` UInt16, 
`ipver` Enum8('ipv4' = 1, 'ipv6' = 2),
`src_addr` String, `dst_addr` String,
`src_port` UInt16, `dst_port` UInt16,
`octets` UInt64, `packets` UInt64,
`sampling` UInt32,
`agent_addr` String, `source_id` UInt32)
ENGINE = MergeTree
PARTITION BY toDate(ts)
ORDER BY (ts, src_addr, dst_addr, src_port, dst_port, agent_addr, source_id)
SETTINGS index_granularity = 8192
```

Request:
```
SELECT toDateTime(intDiv(toUInt32(ts),7200)*7200) as ts, sum(octets) FROM flows3 WHERE ts BETWEEN '2019-11-01 00:00:00' AND '2019-11-16 00:00:00' GROUP BY ts limit 1
...
1 rows in set. Elapsed: 14.930 sec. Processed 11.57 billion rows, 52.36 GB (774.94 million rows/s., 3.51 GB/s.)
```

If we explicitly tell that we want to use in condition ts field from flows3
```
SELECT toDateTime(intDiv(toUInt32(ts),7200)*7200) as ts, sum(octets) FROM flows3 WHERE flows3.ts BETWEEN '2019-11-01 00:00:00' AND '2019-11-16 00:00:00' GROUP BY ts limit 1
1 rows in set. Elapsed: 2.855 sec. Processed 755.18 million rows, 9.06 GB (264.52 million rows/s., 3.17 GB/s.)
```

Or if we just use "AS ts2" and order by this field
```
SELECT toDateTime(intDiv(toUInt32(ts),7200)*7200) as ts2, sum(octets) FROM flows3 WHERE ts BETWEEN '2019-11-01 00:00:00' AND '2019-11-16 00:00:00' AND 1=1 GROUP BY ts2 limit 1
...
1 rows in set. Elapsed: 2.687 sec. Processed 755.18 million rows, 9.06 GB (281.07 million rows/s., 3.37 GB/s.)
```

we get a lot better performance because of correct selection of partitions.

This can be more a bug that performance issue. Also this can be expected behavior, but I could not find in documentation anything about this.

**Comment by den-crane** [comment]
But `toDateTime(intDiv(toUInt32(ts),7200)*7200) as ts ...... ts BETWEEN `
is not the same as result  `WHERE flows3.ts BETWEEN `

**Comment by dotNox** [comment]
I get the exact results ( same data, same number of output records ). The only thing that changes is how much data is read from storage.
```
# time clickhouse-client -n -d nfa -q "SELECT toDateTime(intDiv(toUInt32(ts),7200)*7200) as ts, sum(octets) FROM flows3 WHERE ts BETWEEN '2019-11-01 00:00:00' AND '2019-11-18 00:00:00' GROUP BY ts order by ts" > a.txt

real	0m16.078s
user	0m0.060s
sys	0m0.067s
# time clickhouse-client -n -d nfa -q "SELECT toDateTime(intDiv(toUInt32(ts),7200)*7200) as ts, sum(octets) FROM flows3 WHERE flows3.ts BETWEEN '2019-11-01 00:00:00' AND '2019-11-18 00:00:00' GROUP BY ts order by ts" > b.txt

real	0m3.428s
user	0m0.035s
sys	0m0.056s
# diff -u a.txt b.txt
#
# echo $?
0
```

As per my "intuitive" and documentation understanding, the renaming of output (in select) column must not affect the logic of WHERE expression, because this expression used to get data before all other operations ( theoretically including the expression that goes just after SELECT ).
Excerpt from https://clickhouse.yandex/docs/ru/query_language/select/#select-where
```
Позволяет задать выражение, которое ClickHouse использует для фильтрации данных перед всеми другими действиями в запросе кроме выражений, содержащихся в секции PREWHERE. Обычно, это выражение с логическими операторами.
```
(to be honest, english translation is a little weird at the beginning)

**Comment by den-crane** [comment]
I see 2 different issue here.

1. Not CH performance issue. But logical problem that `toDateTime(intDiv(toUInt32(t),7200)*7200) BETWEEN` and `ts between` are not equivalent and provide different results.
```
CREATE TABLE x (t DateTime) ENGINE = MergeTree PARTITION BY toDate(t) ORDER BY (t);
insert into x values('2019-11-01 23:59:00');
SELECT count()
FROM x 
WHERE toDateTime(intDiv(toUInt32(t),7200)*7200) BETWEEN '2019-11-01 00:00:00' AND '2019-11-01 22:00:00';
┌─count()─┐
│       1 │
└─────────┘

SELECT count()
FROM x 
WHERE t BETWEEN '2019-11-01 00:00:00' AND '2019-11-01 22:00:00';
0 rows in set. Elapsed: 0.001 sec.
```

2. Partition elimination does not work for complicated expression with and *it should not* . And I doubt that it worked before. If it worked before it was a *mistake/bug*.

```
insert into x select '2019-11-01 23:59:00' from numbers(1000000);
insert into x select '2018-11-01 23:59:00' from numbers(1000000);
SELECT count() FROM x WHERE (intDiv((t),7200)*7200) BETWEEN toDateTime('2019-11-01 00:00:00') AND toDateTime('2019-11-01 22:00:00');

Processed 2.00 million rows,

each part has min_max attribute for column x CH design expects something like this

SELECT count() FROM x WHERE t
BETWEEN  toStartOfInterval(toDateTime('2019-11-01 00:00:00'), INTERVAL 2 hour) AND toStartOfInterval(toDateTime('2019-11-01 22:00:00'),INTERVAL 2 hour)

0 rows in set. Elapsed: 0.002 sec.
```

So I don't see any issue.

**Comment by dotNox** [comment]
Now I understand what happens. Renames are also taken in consideration in WHERE clause, unlike in systems like MySQL or similar, where it is not possible ( as per my tests ) to use renamed fields in WHERE clause.
In this matter CH documentation is a little confusing.


Thank you for you help.

**Comment by den-crane** [comment]
Correct. Very useful feature.

CH: 
```
select 1 as x from (select 2 as x) t where x=2;
0 rows in set
```

PG:
```
select 1 as x from (select 2 as x) t where x=2;
 x
---
 1
```
