### ISSUE TITLE
How to delete data from Materialized View

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#7807]
I created a MaterializedView build in the mergetree engine.Our data TTL is 30 days so we use 'drop partition' to delete data,but I can not find a way to delete MaterializedView's data.Is it a plan to fix this problem?

**Comment by den-crane** [comment]
MaterializedView stores data in a usual table. This storage table can created explicitly (before MV) or implicitly (by MV). In the second case the name of the table will be '.inner.{MV_NAME}'

```
create table testx (A Int64, B Date) Engine=MergeTree partition by toYYYYMM(B) order by A;
create materialized view testxMV Engine=MergeTree partition by toYYYYMM(B) order by A as select * from testx;
insert into testx values (1, '2019-01-01');


select * from testxMV
┌─A─┬──────────B─┐
│ 1 │ 2019-01-01 │
└───┴────────────┘

select * from `.inner.testxMV`;
┌─A─┬──────────B─┐
│ 1 │ 2019-01-01 │
└───┴────────────┘

alter table `.inner.testxMV` drop partition 201901;

select * from testxMV;
Ok.
0 rows in set. Elapsed: 0.001 sec.
```

And you can use TTL as well https://clickhouse.yandex/docs/v19.17/en/operations/table_engines/mergetree/#table_engine-mergetree-ttl

**Comment by byx313** [comment]
> MaterializedView stores data in a usual table. This storage table can created explicitly (before MV) or implicitly (by MV). In the second case the name of the table will be '.inner.{MV_NAME}'
> 
> ```
> create table testx (A Int64, B Date) Engine=MergeTree partition by toYYYYMM(B) order by A;
> create materialized view testxMV Engine=MergeTree partition by toYYYYMM(B) order by A as select * from testx;
> insert into testx values (1, '2019-01-01');
> 
> 
> select * from testxMV
> ┌─A─┬──────────B─┐
> │ 1 │ 2019-01-01 │
> └───┴────────────┘
> 
> select * from `.inner.testxMV`;
> ┌─A─┬──────────B─┐
> │ 1 │ 2019-01-01 │
> └───┴────────────┘
> 
> alter table `.inner.testxMV` drop partition 201901;
> 
> select * from testxMV;
> Ok.
> 0 rows in set. Elapsed: 0.001 sec.
> ```
> 
> And you can use TTL as well https://clickhouse.yandex/docs/v19.17/en/operations/table_engines/mergetree/#table_engine-mergetree-ttl
> 
> ```
> alter table `.inner.testxMV` MODIFY TTL B + INTERVAL 1 Month;
> ```

thx for the reply.
I test the sql 'alter table `.inner.testxMV` drop partition 201901' and 'alter table testxMV drop partition 201901',all sql works.I would like to know what's the difference?

**Comment by den-crane** [comment]
No difference. Except early versions of CH did not support `drop partition` for MV.

**Comment by byx313** [comment]
> No difference. Except early versions of CH did not support `drop partition` for MV. I assumed that you created this issue because you are experiencing some issues with `drop partition`.

yep! thank you so much!
