### ISSUE TITLE
Got protobuf corrupted for kafka engine

### ISSUE THREAD

**Issue by korjavin** [ClickHouse/ClickHouse#7811]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
After creating table with kafka engine, I've got protobuf corrupted.
I checked with another consumer and protobuf is correct.

**How to reproduce**
Put this to /var/lib/clickhouse/format_schemas/md.proto
```
syntax = "proto3";             
                        
message mddata {
    int64 ts = 1;
    string instrument_id = 2;
    string exchange = 3;
    repeated double bid_sizes = 4;
    repeated double bid_prices = 5; 
    repeated double ask_sizes = 6;
    repeated double ask_prices = 7; 
}

```
Then create table 
```
create table kafka (   ts Int64,  `instrument_id` String, `exchange` String, `bid_sizes` Array(Float64), `bid_prices` Array(Float64), `ask_sizes` Array(Float64), `ask_prices` Array(Float64) ) ENGINE=Kafka('127.0.0.1:9092', 'mddata', 'mygroup', 'Protobuf', '', 'md:mddata');
```
* Which ClickHouse server version to use
ClickHouse client version 19.11.2.7 (official build).

* Sample data for all these tables, 

* Queries to run that lead to unexpected result
select * from kafka limit 1
**Expected behavior**
I expected to see a row

**Error message and/or stacktrace**
Code: 444. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Protobuf messages are corrupted or don't match the provided schema. Please note that Protobuf stream is length-delimited: every message is prefixed by its length in varint..

**Comment by filimonov** [comment]
Please try version 19.15 or above.

**Comment by den-crane** [comment]
Did  you try to load your data with insert (using clickhouse-client) ?

> Please note that Protobuf stream is length-delimited: every message is prefixed by its length in varint..

Do you supply message length?

**Comment by korjavin** [comment]
>Please try version 19.15 or above.

 I upgraded to ClickHouse client version 19.17.2.4 (official build).
and still see the same

>  Do you supply message length?

![image](https://user-images.githubusercontent.com/148765/69056130-5fc1f780-0a20-11ea-95c7-bbc82cc3080e.png)
as far as I understand there is some Lenght that I can see in kafkatool

**Comment by filimonov** [comment]
Please dump one message to a file (kafkacat or kafka-console-consumer).

Try to parse that file/insert into clickhouse with simple insert.

```
cat protobuf.file | clickhouse-client 'INSERT INTO sometable  FORMAT Protobuf SETTINGS format_schema = 'md:mddata'
```

**Comment by korjavin** [comment]
Not sure if I dumped correctly to the file.
But i've gotCode: 62. DB::Exception: Syntax error: failed at position 1: ...... Unrecognized token

**Comment by korjavin** [comment]
But I am able to read from kafka with another app using the same proto file.

**Comment by den-crane** [comment]
> as far as I understand there is some Lenght that I can see in kafkatool

It's a length of kafka message. CH expects that one message can contain several protobufs. And to parse the message need to know the lengths of protobufs.

`_VarintBytes(len(serialized_msg)) + serialized_msg` https://github.com/ClickHouse/ClickHouse/blob/7ba4e36e73c135ba8bcf65eb14cd9959621e904f/dbms/tests/integration/test_storage_kafka/test.py#L94

**Comment by kap6** [comment]
I thought i would chime in, as I am running into an issue that relates to protobuf and kafka engine. I am taking the binary data from 00825_protobuf_format.insh testcase file. I am sending the message to a kafka queue and am trying to read the same into a CH table (kafka engine, protobuf format). There are no errors, but the select * from <table> format CSV doesn't print data to screen. 

I would appreciate if you can help me understand why i am unable to see any rows ...

**Comment by den-crane** [comment]
@kap6 sounds like completely another issue. Did u check CH logs ?

**Comment by kap6** [comment]
Are you referring to logs in  /var/log/clickhouse-server ? 
Yes. I did. I don't see any thing there.

Here is my command line to inject data into kafka queue. I am not sure if i am doing this the right way:
bin/kafka-console-producer --broker-list localhost:9092 --topic binary5 < ~/orig/person.bin 

 i tested further by repeatedly executing select * from table, without sending additional messages. Eachtime i got different behaviour,

SELECT *
FROM test.Person00825
FORMAT CSV

↑ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.16.3):
Code: 436. DB::Exception: Received from localhost:9000. DB::Exception: Could not convert value '3104751' from protobuf field 'color' to data type 'UInt8'. 

0 rows in set. Elapsed: 0.504 sec. 

streamsets.us-central1-c.c.regal-welder-176912.internal :) select * from test.Person00825 FORMAT CSV

SELECT *
FROM test.Person00825
FORMAT CSV

Ok.

0 rows in set. Elapsed: 0.004 sec. 

streamsets.us-central1-c.c.regal-welder-176912.internal :) select * from test.Person00825 FORMAT CSV

SELECT *
FROM test.Person00825
FORMAT CSV
→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.16.3):
Code: 33. DB::Exception: Received from localhost:9000. DB::Exception: Cannot read all data. Bytes read: 15. Bytes e
xpected: 18446744073709551613.. 
0 rows in set. Elapsed: 0.503 sec. 
streamsets.us-central1-c.c.regal-welder-176912.internal :) select * from test.Person00825 FORMAT CSV
SELECT *
FROM test.Person00825
FORMAT CSV
Ok.
0 rows in set. Elapsed: 0.004 sec. 
streamsets.us-central1-c.c.regal-welder-176912.internal :) select * from test.Person00825 FORMAT CSV
SELECT *
FROM test.Person00825
FORMAT CSV
↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.16.3):
Code: 444. DB::Exception: Received from localhost:9000. DB::Exception: Protobuf messages are corrupted or don't mat
ch the provided schema. Please note that Protobuf stream is length-delimited: every message is prefixed by its leng
th in varint.. 
0 rows in set. Elapsed: 0.504 sec. 
streamsets.us-central1-c.c.regal-welder-176912.internal :) select * from test.Person00825 FORMAT CSV
SELECT *
FROM test.Person00825
FORMAT CSV
Ok.

**Comment by kap6** [comment]
I deleted the topic and started over. The issue is now resolved.
Thanks.
