### ISSUE TITLE
Array functions not working with Array(Array(LowCardinality(String))) data type

### ISSUE THREAD

**Issue by KuliginStepan** [ClickHouse/ClickHouse#7815]
**Describe the bug or unexpected behavior**
Array functions not working with `Array(Array(LowCardinality(String)))` data type

**How to reproduce**
* Which ClickHouse server version to use
19.14.7.15
* Which interface to use, if matters
http
* `CREATE TABLE` statements for all tables involved
```
create table test (
    arr Array(Array(LowCardinality(String)))
) engine = Memory
```
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
`insert into test(arr) values ([['a'], ['b', 'c']])`
* Queries to run that lead to unexpected result
`select arrayFilter(x -> 1, arr) from test`
**Expected behavior**
array functions works without exceptions

**Error message and/or stacktrace**
`Code: 49, e.displayText() = DB::Exception: Cannot capture column 2 because it has incompatible type: got Array(String), but Array(LowCardinality(String)) is expected. (version 19.14.7.15 (official build))`

**Comment by alexey-milovidov** [comment]
Works fine on master.
Test needed.
