### ISSUE TITLE
Performance Considerations section for INSERT INTO assumes partition by months

### ISSUE THREAD

**Issue by Dlougach** [ClickHouse/ClickHouse#7819]
[INSERT INTO](https://clickhouse.yandex/docs/en/query_language/insert_into/)  documentation page has the following paragraph:

> `INSERT` sorts the input data by primary key and splits them into partitions by month. If you insert data for mixed months, it can significantly reduce the performance of the `INSERT` query. To avoid this:
> 
> * Add data in fairly large batches, such as 100,000 rows at a time.
> * Group data by month before uploading it to ClickHouse.
>
> Performance will not decrease if:
> * Data is added in real time.
> * You upload data that is usually sorted by time.

It doesn't make much sense, because choice of partition key is part of the schema definition and therefore tables aren't necessarily partitioned by months.

**Comment by den-crane** [comment]
It's an outdated documentation.

Read it 

INSERT sorts the input data by primary key and splits them into partitions by **partition key expression**. If you insert data for mixed **partition expression (evaluated to several values)**, it can significantly reduce the performance of the INSERT query.
