### ISSUE TITLE
how do I query tables from distributed engine  in a cluster without zookeeper

### ISSUE THREAD

**Issue by junflefreeman** [ClickHouse/ClickHouse#7832]
I have a cluster of clickhouse servers running a cluster. All tables are mergeTree tables without replication.

1) can I query those sharded tables from my distribution engine without zookeeper? 
2) can I create duplicated tables in my cluster, if yes, how do I query those duplicated tables or join duplicated tables with sharded tables? 

Thanks,

**Comment by filimonov** [comment]
1. yes
2. yes. You should create tables on each server separately, best practice is to create exactly the same set of tables.  You can have multiple cluster configurations, so you can create table A (using sharded cluster config) and table B (using cluster config declaring the same servers as replicas), and do join between A an B.

**Comment by sundy-li** [comment]
> 1. can I query those sharded tables from my distribution engine without zookeeper?

It's fine without zookeeper when your tables are all none replicated tables.
But I suggest you better have zookeeper to use 'cluster ddls',  it'll be  easier to create tables on clusters.

> 2. can I create duplicated tables in my cluster, if yes, how do I query those duplicated tables or join duplicated tables with sharded tables?

Maybe you want is distribute table engine? You should read [distributed table](https://clickhouse.yandex/docs/en/operations/table_engines/distributed/)
