### ISSUE TITLE
Code: 48. DB::Exception: There are no UInt128 literals in SQL

### ISSUE THREAD

**Issue by victor-sushko** [ClickHouse/ClickHouse#7834]
This error occurs when a subquery returns a value of the type UUID.

**How to reproduce**
* ClickHouse server versions: 19.16.3, 19.17.3.7
* Create two tables:
`CREATE TABLE single_id(id UUID) ENGINE = Log`
`CREATE TABLE other_table(id UUID) ENGINE = Log`
* Sample data (single row):
`INSERT INTO single_id VALUES ('61f0c404-5cb3-11e7-907b-a6006ad3dba0')`
* Run query:
`SELECT * FROM other_table WHERE id = (SELECT * FROM single_id)`

**Expected behavior**
The query should return a table with one column and zero rows.

**Error message**
`Received exception from server (version 19.16.3):`
`Code: 48. DB::Exception: There are no UInt128 literals in SQL.`

**Comment by SergeyMirvoda** [comment]
Same error text also in #7463

**Comment by alexey-milovidov** [comment]
Still relevant in version 20.11.
