### ISSUE TITLE
Avoid `Too many partitions for single INSERT block` in Kafka Engine

### ISSUE THREAD

**Issue by LizardWizzard** [ClickHouse/ClickHouse#7849]
Hi! I'm using Kafka engine and getting this error: ```DB::Exception: Too many partitions for single INSERT block (more than 100). The limit is controlled by 'max_partitions_per_insert_block' setting. ...```
I understand why this error can occur in small inserts by hand (using clickhouse-client or http interface), but in case with Kafka engine documentation says: 
```
To improve performance, received messages are grouped into blocks the size of max_insert_block_size. If the block wasn't formed within stream_flush_interval_ms milliseconds, the data will be flushed to the table regardless of the completeness of the block.
```
So if I understand correctly Kafka engine should merge blocks before insert to increase performance and avoid this error. Also I can suspect the root of that error in my case is that in every kafka message is one `row` of data, so I suppose that blocks are merged but this does not reduce parts count. Is there a way to overcome this? Is it a bug? I'm hoping to avoid writing middleware pre-batching service, since Kafka engine does almost all needed things

I'm using version 19.15.5.18. Thanks in advance!

**Comment by den-crane** [comment]
>I understand why this error can occur in small inserts by hand

No. It's not about this.
It's about partitioning key in your MV. One insert into kafka (into MV) tries to create more than 100 partitions.

For example 
```

create table A( D Date) Engine=MergeTree partition by D order by D;
insert into A select number from numbers(365);
Code: 252. DB::Exception: Received from localhost:9000. DB::Exception: Too many partitions for single INSERT block (more than 100).
```

Error is secause this insert tries to create 365 partitions

```
create table A( D Date) Engine=MergeTree partition by toYYYYMM(D) order by D;
insert into A select number from numbers(365);
OK.
```
No error. Because this insert creates only 12 partitions.

**Comment by LizardWizzard** [comment]
Thank you so much for explanation! Got it :) Changed partition expression and error is gone
