### ISSUE TITLE
Confusion about Mutations syntax 

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#7855]
When I test the mutation syntax,I found out this syntax only support UINT8 type.What's the limitations or differences that can not support to all the data type?

**Comment by den-crane** [comment]
There is no type boolean in CH. UINT8 is just a substitute for this case. TRUE is any value UINT8 except zero.

WHERE 1 === true (UINT8)
WHERE 'a'=='a' === true (UINT8)
