### ISSUE TITLE
How to fix with command line ---> Code: 117. DB::Exception: Expected end of line

### ISSUE THREAD

**Issue by rccclr** [ClickHouse/ClickHouse#7861]
Hello
Please help for this error: Code: 117. DB::Exception: Expected end of line

CREATE TABLE IF NOT EXISTS  daitoCert.log03 (line String) ENGINE = Log 
clickhouse-client --format_csv_delimiter="|" --input_format_allow_errors_num=10000 
INSERT INTO  daitoCert.log03  FORMAT CSV' <  file.txt

How "clean" the file "file.txt"?

Thanks

**Comment by den-crane** [comment]
try invisible character

--format_csv_delimiter=$'\x0B'

**Comment by rccclr** [comment]
Hello
Many thanks for your response.

This is the file with problems (view image), some rows, has this problem and i need ignore, and load the rest.

When try:

clickhouse-client --format_csv_delimiter=$'\x0B' --format_csv_allow_double_quotes=0 --format_csv_allow_single_quotes=1 --input_format_allow_errors_num=10000 --host=172.16.100.131 --query='INSERT INTO  daito1018.log02  FORMAT CSV' <  file_with_problem.csv

show this error:
Code: 117. DB::Exception: Cannot parse CSV format: found \r (CR) not followed by \n (LF). Line must end by \n (LF) or \r\n (CR LF) or \n\r.

Many thanks for your help.

![image](https://user-images.githubusercontent.com/5550864/69250785-9dee2100-0bb0-11ea-997c-3f2ea559c716.png)

**Comment by den-crane** [comment]
I would replace all \r\n with \n  

`cat  file_with_problem.csv | tr '\r\n' '\n' | clickhouse-client --format_csv_delimiter=$'\x0B' ....`

or all \r with \n

`cat  file_with_problem.csv | tr '\r' '\n' | clickhouse-client --format_csv_delimiter=$'\x0B' ....`

**Comment by rccclr** [comment]
Many thanks for you help.
Clickhouse is the best...
