### ISSUE TITLE
How do you build your rpm or deb packages?

### ISSUE THREAD

**Issue by Mirraz** [ClickHouse/ClickHouse#7864]
Hello. Can you share the scripts with which you build your rpm and/or deb packages? Or you can share srpm package?

**Comment by filimonov** [comment]
Here is (unfinished) PR which builds ClickHouse natively and also produce srpm: 
https://github.com/ClickHouse/ClickHouse/pull/7120

Also Altinity rpm builder is able to produce srpm: https://github.com/Altinity/clickhouse-rpm
