### ISSUE TITLE
Escape double quote sign in CSV

### ISSUE THREAD

**Issue by goranc** [ClickHouse/ClickHouse#7865]
I have CSV file with comma as separator sign, but without quotes for column entries.

Issue I have is with double quote sign existing in string value for column,
when I try to escape it with another double quote ( "" ) for command line clickhouse-client
I got error and insert fails.

When I escape one double quote with backslash ( \" ) then it works but got backslash and quote in entry in column.

What is the proper way to escape double quote in CSV structure like I have ?

Clickhouse server version is 19.11.12

here is example for structures and data:
```
# testdata.csv
749a2c8c-3682-4745-aefe-c21b3164bade,name,""MY COMPANY"" COM
749a2c8c-3682-4745-aefe-c21b3164bade,hash,67FF87AF9E9E4BA9E4C03FAC4A23F21C

# table structure
CREATE TABLE temp.events (`event_id` String, `property_name` String, `property_value` String) ENGINE = MergeTree() PARTITION BY tuple() ORDER BY event_id SETTINGS index_granularity = 8192

#shell script to insert data
cat testdata.csv | clickhouse-client --host=localhost --query='INSERT INTO temp.events (event_id, property_name, property_value) FORMAT CSV'

Code: 117. DB::Exception: Expected end of line: (at row 1)

Row 1:
Column 0,   name: event_id,       type: String, parsed text: "749a2c8c-3682-4745-aefe-c21b3164bade"
Column 1,   name: property_name,  type: String, parsed text: "name"
Column 2,   name: property_value, type: String, parsed text: "<DOUBLE QUOTE><DOUBLE QUOTE>"
ERROR: There is no line feed. "M" found instead.
 It's like your file has more columns than expected.
And if your file have right number of columns, maybe it have unquoted string value with comma.
```

**Comment by den-crane** [comment]
--format_csv_allow_double_quotes=0
```
cat testdata.csv | clickhouse-client --format_csv_allow_double_quotes=0 --host=localhost --query='INSERT INTO events (event_id, property_name, property_value) FORMAT CSV'
```
or double
```

cat testdata.csv
749a2c8c-3682-4745-aefe-c21b3164bade,name,\"\"MY COMPANY\"\" COM
749a2c8c-3682-4745-aefe-c21b3164bade,hash,67FF87AF9E9E4BA9E4C03FAC4A23F21C
cat testdata.csv | clickhouse-client  --host=localhost --query='INSERT INTO events (event_id, property_name, property_value) FORMAT CSV'

```

**Comment by den-crane** [comment]
Though,  escaping seems broken
\\"\\"MY COMPANY\\"\\" COM

**Comment by den-crane** [comment]
Ah, double quote escaping works only inside quoted string.
```
749a2c8c-3682-4745-aefe-c21b3164bade,name,"""Y COMPANY"" COM"
749a2c8c-3682-4745-aefe-c21b3164bade,hash,67FF87AF9E9E4BA9E4C03FAC4A23F21C
```

**Comment by alexey-milovidov** [comment]
@den-crane backslash escaping is for TSV and escaping by doubling quotes is for CSV.

**Comment by goranc** [comment]
Thanks for info, sometimes is hard to find proper parameter.

Parameter "format_csv_allow_double_quotes" resolve the problem, and there is no need to escape double quote at all.
Other special characters should be escaped as usual.

**Comment by inkrement** [comment]
I have a related question: How would you handle a mixture between CSV & TSV (i.e., CSV with escaping instead of quotes)? TSV does not allow changing the delimiter, CSV hates the escapes, and I was unable to get CustomSeparated to work (although I set the comma as separator it detects the full row as single column).
