### ISSUE TITLE
Failed to do integration test on CentOS 7

### ISSUE THREAD

**Issue by yuzhichang** [ClickHouse/ClickHouse#7874]
**Describe the bug or unexpected behaviour**
Here's my development environment:
 -1 CentOS 7 physical machine, checkout Clickhouse code
 -2 Ubuntu 18.04 LTS container, mount Clickhouse code into container
 -3 Build Clickhouse binaries inside container
 -4 Copy clickhouse executable from container to /usr/bin outside. Run integration test outside container. 
I failed at step 4.

```
[root@gpu07 integration]# export PY_IGNORE_IMPORTMISMATCH=1                                                                                                                                   
[root@gpu07 integration]# ./runner --clickhouse-root /bigdata/zhichyu/2/ClickHouse/ 'test_partition'
clickhouse_integration_tests_volume
Start tests
ImportError while loading conftest '/ClickHouse/dbms/tests/integration/conftest.py'.
ImportMismatchError: ('conftest', '/bigdata/zhichyu/2/ClickHouse/dbms/tests/integration/conftest.py', local('/ClickHouse/dbms/tests/integration/conftest.py'))
Traceback (most recent call last):
  File "./runner", line 110, in <module>
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'docker run --net=host -it --rm --name clickhouse_integration_tests --privileged --volume=/usr/bin/clickhouse-odbc-bridge:/clickhouse-odbc-bridge --volume=/usr/bin/clickhouse:/clickhouse         --volume=/bigdata/zhichyu/2/ClickHouse/dbms/programs/server:/clickhouse-config --volume=/bigdata/zhichyu/2/ClickHouse/:/ClickHouse --volume=clickhouse_integration_tests_volume:/var/lib/docker -e PYTEST_OPTS='test_partition' yandex/clickhouse-integration-tests-runner ' returned non-zero exit status 4

```

I managed to run integration test on an Ubuntu 18.04 physical machine. However I prefer CentOS since it's more stable.

**Comment by tavplubix** [comment]
Most likely it happened because `.dockerignore` does not affect `--volume` bindings, so python cache files created outside container was used inside it. Try remove all `__pycache__` dirs and `*.pyc` files in `/bigdata/zhichyu/2/ClickHouse/dbms/tests/integration/` and sub-directories, it should help.

**Comment by yuzhichang** [comment]
@tavplubix Your suggestion works! Thanks.
It's better to set `PY_IGNORE_IMPORTMISMATCH=1` and remove all `__pycache__` dirs and `*.pyc` files at `dbms/tests/integration/image/dockerd-entrypoint.sh` or `runner.py`.
And it's even better to simplify integration framework. Python dependencies and container-in-container make things complicated.
