### ISSUE TITLE
unexpected answer using arrayIntersect function

### ISSUE THREAD

**Issue by shawel** [ClickHouse/ClickHouse#7886]
How does arrayIntersect work ? Consider 

```
SELECT arrayIntersect([5, 6], [800262, 800261]) AS result

┌─result─┐
│ [6,5]  │
└────────┘

```

Shouldn't this be an empty set? I am using  Clickhouse version 19.17.3 revision 5442

**Comment by filimonov** [comment]
It is already fixed in master: #7777

As a workaround - cast to a 'wider' integer type first.
```
SELECT arrayIntersect([toUInt32(5), 6], [toUInt32(800262), 800261]) AS result;
```
