### ISSUE TITLE
some users have query_log and some don't

### ISSUE THREAD

**Issue by Tasselmi** [ClickHouse/ClickHouse#7888]
I can get query log from `system.query_log` by users who execute query from `tabix` .
but users who execute query by `official jdbc`, I can't find their query_log.

Is there anything wrong?
I am so confused.

**Comment by tavplubix** [comment]
There is setting `log_queries`, which enables query logging (disabled by default) and it may have different values for different users and profiles.

**Comment by Tasselmi** [comment]
> There is setting `log_queries`, which enables query logging (disabled by default) and it may have different values for different users and profiles.

I've setted `log_queries`  in `config.xml`.

**Comment by alexey-milovidov** [comment]
@Tasselmi it's a user or query level setting, so it must be set in users.xml for a user profile.

**Comment by Tasselmi** [comment]
> @Tasselmi it's a user or query level setting, so it must be set in users.xml for a user profile.

OK.
It works fine now. Thanks.
