### ISSUE TITLE
What is best UUID hash function for sharding?

### ISSUE THREAD

**Issue by thyn** [ClickHouse/ClickHouse#7892]
I use cityHash64(toString(uuidfield)) It doesn't look optimal. May be I missed better option. 
What is best UUID hash function for sharding?

**Comment by den-crane** [comment]
select cityHash64(toString(toUUID('00da1615-acd3-48ec-8dfc-1cc78cae98ce'))) from numbers(1000000) format Null;

1000000 rows in set. Elapsed: 0.004 sec.


select xxHash32(toString(toUUID('00da1615-acd3-48ec-8dfc-1cc78cae98ce'))) from numbers(1000000) format Null;

1000000 rows in set. Elapsed: 0.003 sec.

**Comment by filimonov** [comment]
```
SELECT xxHash64(toString(generateUUIDv4()))
FROM numbers(1000000)
FORMAT Null


1000000 rows in set. Elapsed: 0.069 sec. Processed 1.05 million rows, 8.39 MB (15.26 million rows/s., 122.07 MB/s.) 

laptop5591 :) select xxHash64(reinterpretAsFixedString(generateUUIDv4())) from numbers(1000000) format Null;

SELECT xxHash64(reinterpretAsFixedString(generateUUIDv4()))
FROM numbers(1000000)
FORMAT Null


1000000 rows in set. Elapsed: 0.038 sec. Processed 1.05 million rows, 8.39 MB (27.25 million rows/s., 217.98 MB/s.) 

laptop5591 :) select xxHash64(reinterpretAsString(generateUUIDv4())) from numbers(1000000) format Null;

SELECT xxHash64(reinterpretAsString(generateUUIDv4()))
FROM numbers(1000000)
FORMAT Null


1000000 rows in set. Elapsed: 0.037 sec. Processed 1.05 million rows, 8.39 MB (28.72 million rows/s., 229.76 MB/s.) 
```

P.S. @den-crane : clickhouse understands that it's a constant value and calculate it once. You can use `materialize` as workaround for samples.

**Comment by alexey-milovidov** [comment]
@filimonov @den-crane Sorry, both answers are not good enough.

1. You should not use `toString` as now you can pass UUID to the hash function directly.

2. @filimonov You may have heard that `xxHash64` is the "fastest" hash function but actually it depends on the distribution of string lengths and on the way how the function was integrated in ClickHouse.

3. You should not send data to the client in benchmark queries.

Example:

```
SELECT count()
FROM system.numbers
WHERE NOT ignore(cityHash64(generateUUIDv4()))

↗ Progress: 12.35 billion rows, 98.83 GB (123.90 million rows/s., 991.24 MB/s.)
```

On old Xeon E5-2650 v2 this query is about four times faster that what you show.

And I still can say this is slow.
Because from fundamental reasons, using hash functions designed for variable length strings for UUIDs is suboptimal.

**Comment by den-crane** [comment]
I used toString cityHash64 does not support UUID

```
SELECT cityHash64(toUUID('00da1615-acd3-48ec-8dfc-1cc78cae98ce'))

Received exception from server (version 19.17.5):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Unexpected type UUID of argument of function cityHash64.
```
And I did not think about reinterpretAsFixedString

But generally I think UUID type should not require a hash function for sharding (Distributed shard expression)

**Comment by filimonov** [comment]
> you can pass UUID to the hash function

That is not true (at least it was't at the moment of writing my prev comment :)) 

> You may have heard that xxHash64 is the "fastest" hash function

I agree and I'm aware of that. I've just adjusted @den-crane sample a bit to make it more reliable.  xxHash is the best for long strings, and worse than city/farm for short strings. I needed it to interoperability with existing code in Python and perl. 

Actually for fixed-size data (i.e. UUID) we can/should have some specialized hash functions. 

For general purposes - recently several new hash functions appeared, for example XXHash3 is very promising. Or meow 
(bit controversial, but very fast), 
https://twitter.com/cmuratori/status/1060718409296437249

**Comment by Nefelim4ag** [comment]
I think that is the right way, but slow because we can't directly convert UUID to Uint in Clickhouse:
```
SELECT count()
FROM system.numbers
WHERE NOT ignore(UUIDStringToNum(toFixedString(toString(generateUUIDv4()), 36)))

Query id: f7c0dd5d-7cf3-4251-8ea9-70dc94651e06

↘ Progress: 1.65 billion rows, 13.20 GB (23.33 million rows/s., 186.63 MB/s.)```

UUID is already an even distributed random number you don't need to hash it, in an ideal situation it's enough to get the first byte in general.

**Comment by eugenecherepanov** [comment]
All cool, but UINT128 is not valid sharding key

https://github.com/ClickHouse/ClickHouse/blob/f48c5973ccec7fd71c71ca7a30c61af01725fd64/src/Storages/StorageDistributed.cpp#L1540C1-L1555C1
