### ISSUE TITLE
uniqExact and countDistinct use way more memory than expected

### ISSUE THREAD

**Issue by George3d6** [ClickHouse/ClickHouse#7895]
I have a table of about 300 billion rows which is ordered by a column called `account_id` (type UInt64) and partitioned by a column called `start_date` (type Date).

There are ~300 partitions and ~9.5M (+/- 0.5M) distinct values for the `account_id` column per partition (and around 15M distinct values for it across all partitions).

Attempting the follow query (either with uniqExact or with countDistinct) results in an OOM error when clickhouse tries to allocate over 350GiB (currently the memory limit):

```
SELECT start_date, uniqExact(account_id) FROM table GROUP BY start_date
```
I know `uniqExact` isn't as memory efficient as `uniq` and other approximation using derivatives, however, it seems very unintuitive that it should fail in this specific case.

Considering that clickhouse keeps 1 in memory table per partition as it executes this query that should be:

8 bytes (UInt64) * 10M distinct values per parition => 80MiB per parition
Multiply that by 300 paritions and I can see memory usage going up to 24GiB.

Granted, I understand that this "idealized" version doesn't taking into account the overhead needed to unpack the data, the overhead needed for the hash map and whatever other sacrifices are made in order to make the code for the hash table more generic. But still, I wouldn't expect the amount of necessary memory to be +15x times as large compared to that number.

To back up this intuition I tried to execute the query using group-bys instead of uniq:

```
SELECT count(*), start_date FROM (SELECT account_id, start_date FROM table GROUP BY start_date, account_id) GROUP BY start_date
```

And while it does take a while to execute, it managed to stay under 50GiB of memory (not sure about exact usage, I set the limit to 50GiB for the purpose of testing this)

Might there be something wrong with the implementation of uniqExact in this specific situation or in general ? Or do I just have a completely wrong understanding for how uniqExact works ? Is there another function I could be using here to get an exact result ?

**Comment by den-crane** [comment]
uniqExact & group by & ..... &...  does not take into account partitioning & sort oder.

**Comment by George3d6** [comment]
Ok, but even in that case, I see no reason why `uniqExact` should run oom when the group-by variant doesn't.

**Comment by den-crane** [comment]
It could be because CH chooses different aggregation algorithms. But it difficult to reproduce.

I did several tests and [select A, uniqExact(B) from testuniqExact group by A] always eats 2 times less than [select A, count(*) from(select A, B from testuniqExact group by A,B) group by A ]

```

create table testuniqExact(A Int64, B Int64) Engine = MergeTree() order by tuple();
insert into testuniqExact select number%1000000, number%1111111 from numbers(1000000000);

set send_logs_level='debug'

select A, uniqExact(B) from testuniqExact group by A format Null;
...
<Debug> MemoryTracker: Current memory usage: 21.00 GiB.
<Debug> MemoryTracker: Current memory usage: 22.00 GiB.
<Debug> MemoryTracker: Current memory usage: 23.00 GiB.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914aaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914caaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914baaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914daaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914faaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914eaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914gaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914haaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914iaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914jaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914kaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914laaaaa.
<Debug> MemoryTracker: Peak memory usage (for query): 23.71 GiB.


select A, countDistinct(B) from testuniqExact group by A format Null;
...
<Debug> MemoryTracker: Current memory usage: 22.00 GiB.
<Debug> MemoryTracker: Current memory usage: 23.00 GiB.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914maaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914naaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914oaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914paaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914qaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914raaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914saaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914taaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914uaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914vaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914waaaaa.
<Debug> MemoryTracker: Peak memory usage (for query): 23.67 GiB.



select A, count(*) from(select A, B from testuniqExact group by A,B) group by A format Null;
...
<Debug> MemoryTracker: Current memory usage: 22.01 GiB.
<Debug> MemoryTracker: Current memory usage: 23.00 GiB.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914xaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914yaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914zaaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914abaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914bbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914cbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914dbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914ebaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914fbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914gbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914hbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914ibaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914jbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914kbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914lbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914mbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914nbaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914obaaaa.
<Debug> Aggregator: Writing part of aggregation data into temporary file /var/lib/clickhouse/tmp/tmp399914pbaaaa.
<Debug> MemoryTracker: Peak memory usage (for query): 23.83 GiB.

```

**Comment by den-crane** [comment]
Though. I can.

```
create table testuniqExact(A Int64, B Int64) Engine = MergeTree() order by tuple();
insert into testuniqExact select number, number*2 from numbers(100000000);

select A, uniqExact(B) from testuniqExact group by A format Null;
Peak memory usage (for query): 21.27 GiB.

select A, count(*) from(select A, B from testuniqExact group by A,B) group by A format Null;
MemoryTracker: Peak memory usage (for query): 7.54 GiB.
```

I think an optimizer chooses sub-optimal groupby algorithm for this data.

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/4510
https://github.com/ClickHouse/ClickHouse/issues/6565

**Comment by alexey-milovidov** [comment]
The minimum size of the state for `uniqExact` is:
`3 * sizeof(ptr) + 128` = 152 bytes.

128 is the size of hash table to allocate 8 elements (the hash table of 16 cells 8 bytes each).
We have this for "automatic memory" to save allocations for small states.

For 100 000 000 elements, the amount of memory for states will be 15.2 GB.

Also memory is allocated for hash table for GROUP BY.
Each hash table cell is 16 bytes. The number of cells is 268 435 456 (maximum fill factor is 0.5).
It is 4 GiB = 4.3 GB.

In total we have 19.5 GB that roughly corresponds to 
> Peak memory usage (for query): 21.27 GiB.

At least the memory usage is consistent with my expectations.

**Comment by alexey-milovidov** [comment]
@den-crane You are reproducing a completely different use case that what is mentioned in the first message.

In your use case, we have exactly one value in uniqExact for each value of GROUP BY key.
The memory usage is consistent with expectations.

**Comment by alexey-milovidov** [comment]
@George3d6 It may happen due to parallel query execution, if every thread get the same `account_id`s in their aggregation state. You can lower the number of threads.

**Comment by alexey-milovidov** [comment]
`uniqExact` is special, because the `merge` operation has similar complexity to doing `update` for all elements again and parallel aggregation may not improve performance much.
