### ISSUE TITLE
Clickhouse failed to start, permission denied

### ISSUE THREAD

**Issue by alex-rsk** [ClickHouse/ClickHouse#7902]
Hello.
Ubuntu 18.04, after almost half of a year flawless working, after last update clickhouse-server refused to start.
Version: Clickhouse 19.17.4.11
How to reproduce: clickhouse-server --config-file=/etc/clickhouse-server/config.xml
**Expected behavior**
Clickhouse server had to start

**Error message and/or stacktrace**
clickhouse-server --config-file=/etc/clickhouse-server/config.xml
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Logging trace to console
2019.11.25 12:22:34.519721 [ 1 ] {} <Information> : Starting ClickHouse 19.17.4.11 with revision 54428
2019.11.25 12:22:34.521781 [ 1 ] {} <Information> Application: starting up
2019.11.25 12:22:34.523704 [ 1 ] {} <Warning> Application: Effective user of the process (alexrsk) does not match the owner of the data (clickhouse).
2019.11.25 12:22:34.523987 [ 1 ] {**} <Error> Application: DB::ErrnoException: Cannot open file /var/lib/clickhouse/status, errno: 13, strerror: Permission denied**
2019.11.25 12:22:34.524007 [ 1 ] {} <Information> Application: shutting down
2019.11.25 12:22:34.524017 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2019.11.25 12:22:34.524189 [ 2 ] {} <Information> BaseDaemon: Stop SignalListener thread
alexrsk@alexrsk-desktop:/etc/clickhouse-server$ 

After

`sudo pkill clickhouse` 

I tried to start it again and got another error
`
<Error> Application: Caught exception while loading metadata: Code: 6, e.displayText() = DB::Exception: Cannot parse definition from metadata file /var/lib/clickhouse/metadata/system//query_log_0.sql, error: DB::ErrnoException: Cannot open file /var/lib/clickhouse/metadata/system//query_log_0.sql, errno: 13, strerror: Permission denied, stack trace:
0. 0x5597ff505f60 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x5597ff5174f3 DB::ErrnoException::ErrnoException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&) /usr/bin/clickhouse
2. 0x5597ff04b258 DB::throwFromErrnoWithPath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) /usr/bin/clickhouse
3. 0x559803432cb9 DB::ReadBufferFromFile::ReadBufferFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, int, char*, unsigned long) /usr/bin/clickhouse
4. 0x559802f1fe7a DB::parseCreateQueryFromMetadataFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::Logger*) /usr/bin/clickhouse
5. 0x559802f2597e ? /usr/bin/clickhouse
6. 0x559802f220d7 DB::DatabaseOnDisk::iterateMetadataFiles(DB::IDatabase const&, Poco::Logger*, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&) /usr/bin/clickhouse
7. 0x559802f24b8f DB::DatabaseOrdinary::loadStoredObjects(DB::Context&, bool) /usr/bin/clickhouse
8. 0x559802899b06 DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) /usr/bin/clickhouse
9. 0x55980289a035 DB::InterpreterCreateQuery::execute() /usr/bin/clickhouse
10. 0x5598029f6933 ? /usr/bin/clickhouse
11. 0x5598029f7b75 DB::loadMetadataSystem(DB::Context&) /usr/bin/clickhouse
12. 0x5597ff444d40 DB::Server::main(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /usr/bin/clickhouse
13. 0x5598035c8e08 Poco::Util::Application::run() /usr/bin/clickhouse
14. 0x5597ff559c19 DB::Server::run() /usr/bin/clickhouse
15. 0x5598035df5a5 Poco::Util::ServerApplication::run(int, char**) /usr/bin/clickhouse
16. 0x5597ff5565c7 mainEntryClickHouseServer(int, char**) /usr/bin/clickhouse
17. 0x5597ff44234d main /usr/bin/clickhouse
18. 0x7f49701f9b97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344
19. 0x5597ff4aba9a _start /usr/bin/clickhouse
, Stack trace:

0. 0x5597ff505f60 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x5597ff505d35 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x5597ff314b53 ? /usr/bin/clickhouse
3. 0x559802f220d7 DB::DatabaseOnDisk::iterateMetadataFiles(DB::IDatabase const&, Poco::Logger*, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&) /usr/bin/clickhouse
4. 0x559802f24b8f DB::DatabaseOrdinary::loadStoredObjects(DB::Context&, bool) /usr/bin/clickhouse
5. 0x559802899b06 DB::InterpreterCreateQuery::createDatabase(DB::ASTCreateQuery&) /usr/bin/clickhouse
6. 0x55980289a035 DB::InterpreterCreateQuery::execute() /usr/bin/clickhouse
7. 0x5598029f6933 ? /usr/bin/clickhouse
8. 0x5598029f7b75 DB::loadMetadataSystem(DB::Context&) /usr/bin/clickhouse
9. 0x5597ff444d40 DB::Server::main(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /usr/bin/clickhouse
10. 0x5598035c8e08 Poco::Util::Application::run() /usr/bin/clickhouse
11. 0x5597ff559c19 DB::Server::run() /usr/bin/clickhouse
12. 0x5598035df5a5 Poco::Util::ServerApplication::run(int, char**) /usr/bin/clickhouse
13. 0x5597ff5565c7 mainEntryClickHouseServer(int, char**) /usr/bin/clickhouse
14. 0x5597ff44234d main /usr/bin/clickhouse
15. 0x7f49701f9b97 __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344
16. 0x5597ff4aba9a _start /usr/bin/clickhouse

`

**Comment by abyss7** [comment]
From what version have you upgraded?

**Comment by abyss7** [comment]
Also please provide the ACL information on `/var/lib/clickhouse/status`, `/var/lib/clickhouse/metadata/system//query_log_0.sql` and all intermediate folders - owner, group, access rights.

And tell under which user you're starting `clickhouse-server`?

**Comment by YogSotot** [comment]
I don't remember the version I upgraded from.
ACL info
`
  File: /var/lib/clickhouse/status
  Access: (0640/-rw-r-----)  Uid: (  136/clickhouse)   Gid: (  141/clickhouse)
  File: `/var/lib/clickhouse/metadata/system//query_log_0.sql 
 Access: (0640/-rw-r-----)  Uid: (  136/clickhouse)   Gid: (  141/clickhouse)
`
Ran under myself, non-root regular user:
alexrsk@my-desktop:/var/www/ghc-play$ clickhouse-server  --config=/etc/clickhouse-server/config.xml

**Comment by YogSotot** [comment]
ACL of intermediate folders: 

/var/lib/clickhouse
Access: (0777/drwxrwxrwx)  Uid: (  136/clickhouse)   Gid: (  141/clickhouse)

/var/lib/clickhouse/metadata
Access: (0777/drwxrwxrwx)  Uid: (  136/clickhouse)   Gid: (  141/clickhouse)

/var/lib
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)

**Comment by YogSotot** [comment]
Reinstalled clickhouse, no luck.

**Comment by abyss7** [comment]
> I don't remember the version I upgraded from.
> ACL info:
> 
> File: /var/lib/clickhouse/status
> Access: (0640/-rw-r-----) Uid: ( 136/clickhouse) Gid: ( 141/clickhouse)
> 
> File: `/var/lib/clickhouse/metadata/system//query_log_0.sql
> Access: (0640/-rw-r-----) Uid: ( 136/clickhouse) Gid: ( 141/clickhouse)
> 
> Ran under myself, non-root regular user:
> alexrsk@my-desktop:/var/www/kh-play$ clickhouse-server --config=/etc/clickhouse-server/config.xml

If you're not inside `clickhouse` user group, than you can't read those files - according to access rights. Are you?

**Comment by YogSotot** [comment]
Ok, i added myself through usermod -a -G 
```
groups alexrsk
alexrsk : alexrsk adm cdrom sudo dip plugdev lpadmin sambashare vboxusers clickhouse
```
This time a got an another error:

`Logging trace to console
2019.11.29 18:10:30.968014 [ 1 ] {} <Information> : Starting ClickHouse 19.17.4.11 with revision 54428
2019.11.29 18:10:31.021084 [ 1 ] {} <Information> Application: starting up
2019.11.29 18:10:31.423542 [ 1 ] {} <Warning> Application: Effective user of the process (alexrsk) does not match the owner of the data (clickhouse).
**2019.11.29 18:10:31.476405 [ 1 ] {} <Error> Application: DB::ErrnoException: Cannot open file /var/lib/clickhouse/status, errno: 13, strerror: Permission denied**
2019.11.29 18:10:31.476474 [ 1 ] {} <Information> Application: shutting down
2019.11.29 18:10:31.476484 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2019.11.29 18:10:31.476750 [ 2 ] {} <Information> BaseDaemon: Stop SignalListener thread
`

**Comment by YogSotot** [comment]
May you point me, how to downgrade to any stable version, please?

**Comment by den-crane** [comment]
> May you point me, how to downgrade to any stable version, please?

apt-get install clickhouse-server=19.17.4.11 clickhouse-client=19.17.4.11 clickhouse-common-static=19.17.4.11

Why do you start CH not with `sudo service clickhouse-server start` ?

**Comment by YogSotot** [comment]
> > May you point me, how to downgrade to any stable version, please?
> 
> apt-get install clickhouse-server=19.17.4.11 clickhouse-client=19.17.4.11 clickhouse-common-static=19.17.4.11
> 
> Why do you start CH not with `sudo service clickhouse-server start` ?

In official documentation
![image](https://user-images.githubusercontent.com/16610797/69882359-f9bb5700-12e0-11ea-8b72-ddf21d6760cf.png)

**Comment by den-crane** [comment]
>What if I don't need to start it as service..

Sure. Not a problem at all. 
And you can run as any user just change folders owner.

$ sudo service clickhouse-server stop
$ sudo chown -R denis.zhuravlev:Domain.Users /var/lib/clickhouse /var/log/clickhouse-server /etc/clickhouse-server /etc/clickhouse-client
$ clickhouse-server --config-file=/etc/clickhouse-server/config.xml

**Comment by vamirio-chan** [comment]
Short: incorrect users for one of my databases (i don't have a clue how it could happen because -ls lh displayed 'clickhouse' but I'm using WSL so it might be the reason).

I haven't checked what config clickhouse was using, but apparently not /etc/clickhouse-server/config.xml. So I used this command: 
`sudo -u clickhouse clickhouse-server --config=/etc/clickhouse-server/config.xml` and finally could get the error message: 
`<Error> Application: Access to file denied: /var/lib/clickhouse/data/default/hosts/7eb7dd371fd2695f17f27553fe93b0b9_1_22_4_41`. In my case I had a replica so all I've done was `sudo rm -rf /var/lib/clickhouse/data/default/hosts/` and could finally launch clickhouse by usual `sudo clickhouse-server start`.
