### ISSUE TITLE
Confusion about compression

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#7917]
When I go deep into ClickHouse compression,I got some questions.Hope to get the reply
(1)Q1
`<compression incl="clickhouse_compression">
    <case>
        <min_part_size>10000000000</min_part_size>
        <min_part_size_ratio>0.01</min_part_size_ratio>
        <method>zstd</method>
    </case>
</compression>
`

> ClickHouse checks min_part_size and min_part_size_ratio and processes the case blocks that match these conditions. If none of the <case> matches, ClickHouse applies the lz4 compression algorithm

Is it right that when I do a INSERT query and the data size is greater than 100MB(10000000000 *  0.01),the zstd compression algorithm will be used?What should I do if I would like to change the default algorithm to zstd not lz4?
(2)Q2
`value Float32 CODEC(Delta, ZSTD)`
The pipeline codec really confuse me.The second parameter is the compression algorithm,in my opinion,the first parameter is used to show the column data type clearly and help to get a better compression ratio and speed?

**Comment by den-crane** [comment]
>What should I do if I would like to change the default algorithm to zstd not lz4?

```
<compression>
<case>
<min_part_size>0</min_part_size>         
<min_part_size_ratio>0</min_part_size_ratio>    
<method>zstd</method> 
</case>
</compression> 
```

>Is it right that when I do a INSERT query and the data size is greater than 100MB(10000000000 * 0.01),

Right. But also merge process able to compress two small (Lz4) parts with size less 100 to a new part with Zstd (because of this case rules).

>value Float32 CODEC(Delta, ZSTD)
>The pipeline codec really confuse me.The second parameter is the compression algorithm,in my >opinion,the first parameter is used to show the column data type clearly and help to get a better >compression ratio and speed?

correct. Also try Gorilla CODEC for Float32

**Comment by byx313** [comment]
> > What should I do if I would like to change the default algorithm to zstd not lz4?
> 
> ```
> <compression>
> <case>
> <min_part_size>0</min_part_size>         
> <min_part_size_ratio>0</min_part_size_ratio>    
> <method>zstd</method> 
> </case>
> </compression> 
> ```
> 
> > Is it right that when I do a INSERT query and the data size is greater than 100MB(10000000000 * 0.01),
> 
> Right. But also merge process able to compress two small (Lz4) parts with size less 100 to a new part with Zstd (because of this case rules).
> 
> > value Float32 CODEC(Delta, ZSTD)
> > The pipeline codec really confuse me.The second parameter is the compression algorithm,in my >opinion,the first parameter is used to show the column data type clearly and help to get a better >compression ratio and speed?
> 
> correct. Also try Gorilla CODEC for Float32

thx!
