### ISSUE TITLE
is there a way to assign list of preferred replicas for fetching newly written blocks

### ISSUE THREAD

**Issue by agaurav** [ClickHouse/ClickHouse#7921]
Use case is to avoid any network load on the node where data is being inserted in order to avoid a bottleneck because of majority bandwidth used in replication.
So, once newly written block has been replicated to some other node in preferred list, then rest of the replicas use those nodes only.

Maybe clickhouse takes care of this itself by ensuring in case of lot of replica that blocks are fetched in some fan out manner that a node only transfer the data at max n times to another replicas. 
Another approach will be to fetch the block from replica with least load.

**Comment by den-crane** [comment]
There is no such settings.

CH does not take care. All replicas fetch parts from all other available replicas. If only one replica has a part all replicas will fetch from that replica.
