### ISSUE TITLE
argMax(arg,val) behavior with several different values of 'arg' for maximum values of 'val'

### ISSUE THREAD

**Issue by filleskin** [ClickHouse/ClickHouse#7927]
Hello!

In the [documentation ](https://clickhouse.yandex/docs/en/query_language/agg_functions/reference/#agg_function-argMax) is said "If there are several different values of 'arg' for maximum values of 'val', the first of these values encountered is output".

If there are two rows with the same val and i am running the script
`select argMax (col1, ts), argMax (col2, ts) from table `
must selected values of col1 and col2 belong to one row within one script execution or not?

Добрый день!

В [документации](https://clickhouse.yandex/docs/ru/query_language/agg_functions/reference/#agg_function-argMax) сказано "Если есть несколько разных значений arg для максимальных значений val, то выдаётся первое попавшееся из таких значений".

При этом, если существует две строки с одинаковым значением val и выполняется скрипт `select argMax (col1, ts), argMax (col2, ts) from table ` обязаны ли выбранные значения col1 и col2 принадлежать одной строке при выполнении такого скрипта?

**Comment by den-crane** [comment]
>must selected values of col1 and col2 belong to one row within one script execution or not

yes. they will.


>обязаны ли выбранные значения col1 и col2 принадлежать одной строке при выполнении такого скрипта

да обязаны.
-------------------

И все условия можно задавать tuple-м

select (1,6) > (1,7)
---
0

поэтому можно добавить логики
argMax (col1, (ts, col1)) или argMax (col1, (ts, -col)) 
и таким образом для одинаковых ts например всегда выбирать максимальное или минимальное значение col1 если это добавляет смысла

**Comment by filleskin** [comment]
Спасибо!
