### ISSUE TITLE
Slowdown of query execution speed when executing a query using FINAL

### ISSUE THREAD

**Issue by filleskin** [ClickHouse/ClickHouse#7928]
Hello!

What determines the slowdown of query execution speed when executing a query using FINAL, and in what dependence (engine CollapsingMergeTree)? Slow down linearly from the size of the table, slow down linearly from the size of the sample by condition? Or by some other principle?

Здравствуйте!

От чего зависит замедление скорости выполнения запроса при выполнении запроса с использованием FINAL и в какой зависимости (движок CollapsingMergeTree)? Замедлится линейно от размера таблицы, замедлится линейно от размера выборки по условию? Либо еще по какому-то принципу?

**Comment by den-crane** [comment]
FINAL выполняется после отсечения партиций, после поиска по первичному ключу и prewhere.
Зависит нелинейно.
```

create table collapsing(A Int64, B Int64, s Int8) Engine=CollapsingMergeTree(s) order by A;

insert into collapsing select number, 0, 1 from numbers(100000);
insert into collapsing select number, 1, -1 from numbers(100000);

select count() from collapsing;
0.001 sec.

select count() from collapsing FINAL;
0.015 sec.

select count() from collapsing where A>90000;
0.002 sec.

select count() from collapsing FINAL where A>90000;
0.004 sec.

truncate table collapsing;

insert into collapsing select number, 0, 1 from numbers(10000000);
insert into collapsing select number, 1, -1 from numbers(10000000);

select count() from collapsing;
0.001 sec.

select count() from collapsing FINAL;
1.680 sec.

select count() from collapsing where A>9000000;
0.008 sec.

select count() from collapsing FINAL where A>90000;
0.143 sec.

select count() from (
select sum(s) ss from collapsing group by A having ss>0);
0.893 sec.
```
