### ISSUE TITLE
Inconsistencies of inserts with default values

### ISSUE THREAD

**Issue by excitoon** [ClickHouse/ClickHouse#7943]
```
:) create table t (a Int DEFAULT 42, b Int DEFAULT 43) engine = MergeTree order by tuple() partition by tuple();

:) insert into t values ()

INSERT INTO t VALUES


Exception on client:
Code: 62. DB::Exception: Cannot parse expression of type Int32 here: )

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.18.1 revision 54429.

:) drop table t

:) create table t (a Int DEFAULT 42) engine = MergeTree order by tuple() partition by tuple();

:) insert into t values ()

INSERT INTO t VALUES

Ok.

1 rows in set. Elapsed: 0.002 sec. 

:) select * from t

SELECT *
FROM t

┌─a─┐
│ 0 │
└───┘

1 rows in set. Elapsed: 0.003 sec. 
```

I would like to add that documentation for `INSERT` needs to be actualized after f3b6d351670c0fdbc8f5bedbf2e698231aa2b477: https://github.com/ClickHouse/ClickHouse/search?q=strict_insert_defaults&type=Code

**Comment by nikitamikhaylov** [comment]
```sql
CREATE TABLE t
(
    `a` Int DEFAULT 42, 
    `b` Int DEFAULT 43
)
ENGINE = MergeTree
PARTITION BY tuple()
ORDER BY tuple()
```
You need to write comma separator and this query will be Ok.
```sql
INSERT INTO t VALUES (,)
```
But select query's answer is wrong.
```sql
SELECT *
FROM t

┌─a─┬─b─┐
│ 0 │ 0 │
└───┴───┘
```

**Comment by den-crane** [comment]
INSERT INTO t VALUES (,) -- passes empty not default values (converted to 0, or Null for Nullable)
INSERT INTO t() -- such query is impossible but it would pass default values

#6331 a feature request for `INSERT INTO t VALUES (default,default)` , not implemented yet

**Comment by tavplubix** [comment]
> You need to write comma separator and this query will be Ok.

But it should not be OK. It works only because `readIntTextUnsafe(...)` in `DataTypeNumberBase<T>::deserializeText(...)` doesn't throw an exception and doesn't change position in buffer when it cannot parse int, so zero is inserted. I think such behaviour of `deserializeText(...)` should be fixed
