### ISSUE TITLE
ClickHouse consuming lot of CPU while running many ALTER TABLE query for updating records.

### ISSUE THREAD

**Issue by adnanahsan** [ClickHouse/ClickHouse#7949]
Hello everyone,

i am building a web application and choosen clickhouse as the database solution. The problem that i am facing is when i ran queries to update records, i noticed clickhouse using lot of CPU (415% for example) .. my application will have to do many update queries to update records. when i update a single record, its alright, but when i ran a loop in application to run arround 1000 update queries, it eaten all the CPU, whereas RAM was fine just 2-3% ..
Please share your opinion/advises/experience with me .
I will be waiting

Thanks

**Comment by den-crane** [comment]
CH is an analytic database and it is not supposed to be used for web applications.
`Alter update` must not be used on a daily basis but for rare admin operations like GDPR compliance.
Basically `alter update` rewrites all data  on disk (with uncompress / compress) that's why utilizes all CPUs for a long time.

**Comment by adnanahsan** [comment]
> CH is an analytic database and it is not supposed to be used for web applications.
> `Alter update` must not be used on a daily basis but for rare admin operations like GDPR compliance.
> Basically each `alter update` rewrites all data (all rows) on disk (with uncompress / compress) that's why it utilizes all CPUs for a long time.

My web application will use CH for analytics / stats too, but obviously we will need to insert data first then we can read it for analytics :) .. if its not supposed to be used for web apps? then where else can we use it ? the problem is that my web app will read and write lot of data when huge traffic is running, mysql wont be good for that, i appreciate your opinion, if you have advises for me, please share with me , m waiting. Thanks

**Comment by den-crane** [comment]
>My web application will use CH for analytics / stats too

too??? It's the only use-case of CH -- analytics. CH is not a replacement for Mysql or other OLTP databases.  

Try ReplacingMergeTree / CollapsingMergeTree instead of `alter update`.

**Comment by adnanahsan** [comment]
Clickhouse site mentioned on its home page that the CH can be used for web applications you can check it on their home page in clickhouse use section.

**Comment by adnanahsan** [comment]
> > My web application will use CH for analytics / stats too
> 
> too??? It's the only use-case of CH -- analytics. CH is not a replacement for Mysql or other OLTP databases.
> 
> Try ReplacingMergeTree / CollapsingMergeTree instead of `alter update`.

Bro what if i use mysql as my main database for managing other parts, and just for hits and reporting on hits, i use clickhouse on same site same time ? what you think? instead of update, i will insert data in another table and on reporting i will use join to merge all records .. GIve opinion on this bro i will wait for you. Thanks in advance

**Comment by den-crane** [comment]
>Bro what if i use mysql as my main database for managing other parts, and 
>just for hits and reporting on hits, i use clickhouse on same site same time ? what you think?

That's OK.

>instead of update, i will insert data in another table and on 
>reporting i will use join to merge all records 

Try https://clickhouse.yandex/docs/en/operations/table_engines/replacingmergetree/
