### ISSUE TITLE
Question:: Using Multiple Block Devices for Data Storage

### ISSUE THREAD

**Issue by MahmoudGoda0** [ClickHouse/ClickHouse#7957]
Hi All, I have a question related to this topic "Storage policies configuration" we have a tag called "move_factor"  = 0.8, and based on the official doc, we have this statement (when the amount of available space gets lower than this factor, data automatically start to move on the next volume if any), My question is which parts will be moved ? the new data or the old data and what is the actual size that will be moved ?

**Comment by filimonov** [comment]
Largest first

**Comment by MahmoudGoda0** [comment]
> Largest first

Thanks!
What is the size will be moved ? 20 % of the first disk ?

**Comment by filimonov** [comment]
If you will set  move_factor to 0.8 it will try to preserve 80% of disk space free. So once the disk will be filled to 20.5% it will start moving parts (largest first) to the next volume.

**Comment by MahmoudGoda0** [comment]
Well, This means the process will not move any data from first disk to the next one if the available disk space is >= 80% ? I'm asking this question because i see its moved the data and the available disk space was 87%

**Comment by MahmoudGoda0** [comment]
> So once the disk will be filled to 20.5% it will start moving parts (largest first) to the next volume.

So it will move parts =  0.5 % of the disk space ?

**Comment by filimonov** [comment]
> Well, This means the process will not move any data from first disk to the next one if the available disk space is >= 80% ? I'm asking this question because i see its moved the data and the available disk space was 87%

It pushes data with move_factor between volumes, inside one volume it uses round-robin. 

> So it will move parts = 0.5 % of the disk space ?

It will just move the largest part to next volume once the free space on first volume will go below 
80%.  There are big chances that it will be larger that 0.5%.

**Comment by MahmoudGoda0** [comment]
Thanks for the details, I will try to re-test this case again to make sure "move_factor" working fine.
So, Considering the following example, If I have 4 disks (2 SSD, 2 HDD) and "move_factor" = 0.8 and I would like to have the fresh data in SSDs disks and the old data to be moved to HDDs disk based on the move factor, Then I received a fresh data, and this data is the largest part (comparing with the data already in SSD disks), and now the SSD disk is filled by 21 %, So the fresh data will moved to the HDD disk directly because its the largest part ?

**Comment by blinkov** [comment]
@MahmoudGoda0, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@MahmoudGoda0 

The logic is correct. But this scenario will not happen because largest parts appeared after merges and merges of larger parts appeared when parts are old enough and when they are already merged from smaller parts. So, largest parts cannot be the most fresh.
