### ISSUE TITLE
Queries on timezone fields don't respect the timezone

### ISSUE THREAD

**Issue by feribg** [ClickHouse/ClickHouse#7961]
The `timestamp` field is in `EDT` when I pass where `timezone=something`, `something` get's evaluated to UTC first. I tried looking if `toDateTime` takes a string and timezone parameter, but there doesn't seem to be an easy way to go about it.

The screenshot and schema should explain the issue. The expectation is that the string for datetime expressions is always in the zone of the column by default.

![Selection_021](https://user-images.githubusercontent.com/1943817/69849850-cc709980-124b-11ea-99ea-110a44310b49.png)

Schema:

https://pastebin.com/eYh8Tzdj

As an aside, do you see any way to optimize that schema, It's about 30 mb in parquet vs 80 in clickhouse. What would be the most effecient way to cast from a low cardinality string to regular string in order to export back to parquet and compare the CH parquet exporter compression levels? 

Thanks!

**Comment by den-crane** [comment]
>when I pass where timezone=something

What do you mean pass?

```
TZ=Europe/Moscow cl --use_client_time_zone=1
create table TT(D DateTime) Engine=Memory;
insert into TT select now();
SELECT *
FROM TT

┌───────────────────D─┐
│ 2019-11-29 19:02:46 │
└─────────────────────┘

SELECT *
FROM TT
WHERE D = toDateTime('2019-11-29 19:02:46', 'Europe/Moscow')

┌───────────────────D─┐
│ 2019-11-29 19:02:46 │
└─────────────────────┘
```

**Comment by feribg** [comment]
This works `SELECT * FROM TT WHERE D = toDateTime('2019-11-29 19:02:46', timezone the column is in)`

This casts the timezone to UTC  first and then compares which is weird if  the column has a non UTC timezone. Just not my expectation, but I can always cast them.

`SELECT * FROM TT WHERE D =  '2019-11-29 19:02:46'`

Thanks for the response. Do you usually recommend all UTC, are there any downsides in clickhouse from an operational standpoint to using other TZ's?

**Comment by den-crane** [comment]
> the column has a non UTC timezone

this column attribute just a hint to clients how to render this values to stings.

>Do you usually recommend all UTC

yes. It makes less confusion.
