### ISSUE TITLE
Mechanism for validating configuration files

### ISSUE THREAD

**Issue by vkolomiets** [ClickHouse/ClickHouse#7966]
Please advise if there is a mechanism for validating configuration files.
For example nginx web server have this: service nginx configtest or nginx -s reload.

**Comment by alexey-milovidov** [comment]
There is a tool named `clickhouse-extract-from-config`.
You can use it to preprocess configs and extract the value of some key.

Example:
```
$ clickhouse-extract-from-config --config-file /etc/clickhouse-server/config.xml --key path
/opt/clickhouse/
```

It will also validate config.

You can apply this tool to any configuration file: config.xml, users.xml, dictionary configs if any...
