### ISSUE TITLE
Failed to build on OSX Mojave with gcc-8

### ISSUE THREAD

**Issue by svetlyak40wt** [ClickHouse/ClickHouse#7970]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**

OSX Mojave 10.14.6

**Cmake version**

3.15.5

**Ninja version**

1.9.0

**Compiler name and version**

gcc-8 Homebrew GCC 8.3.0_1

**Full cmake and/or ninja output**

```
[art@art-osx:...ts/work/ClickHouse/build]% cmake .. -DCMAKE_CXX_COMPILER=`which g++-8` -DCMAKE_C_COMPILER=`which gcc-8`             (master|✔)
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-8
-- Check for working C compiler: /usr/local/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++-8
-- Check for working CXX compiler: /usr/local/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Disabling compiler -pipe option (have only 5570 mb of memory)
-- Performing Test HAVE_SSE41
-- Performing Test HAVE_SSE41 - Success
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Success
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Success
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Success
-- Performing Test HAVE_PCLMULQDQ
-- Performing Test HAVE_PCLMULQDQ - Success
-- Performing Test HAVE_POPCNT
-- Performing Test HAVE_POPCNT - Success
CMake Error at cmake/darwin/default_libs.cmake:4 (message):
  Darwin build is supported only for Clang
Call Stack (most recent call first):
  CMakeLists.txt:234 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/art/projects/work/ClickHouse/build/CMakeFiles/CMakeOutput.log
```

[CMakeOutput.log content](https://github.com/ClickHouse/ClickHouse/files/3905732/CMakeOutput.log).

**Comment by filimonov** [comment]
I see the message: "Darwin build is supported only for Clang" in the output. :)

**Comment by svetlyak40wt** [comment]
And what should I do with this information? I don't want to dig into what Clang is. Just want to built a command-line client to ClickHouse.

**Comment by svetlyak40wt** [comment]
@alexey-milovidov why did you mark this issue as "invalid"?

Pages  https://clickhouse.yandex/docs/en/development/build/ https://clickhouse.yandex/docs/en/development/build_osx/ say nothing about Clang. Build fails with this obscure error and there is no information about solving the issue.

**Comment by nikitamikhaylov** [comment]
Sorry. FYI: Clang is another compiler for C++. You can install **clang 8** and then compile without any problems.  We will update our documentation ASAP.

**Comment by abyss7** [comment]
> Sorry. FYI: Clang is another compiler for C++. You can install **clang 8** and then compile without any problems. We will update our documentation ASAP.

Did we do that?

**Comment by nikitamikhaylov** [comment]
> > Sorry. FYI: Clang is another compiler for C++. You can install **clang 8** and then compile without any problems. We will update our documentation ASAP.
> 
> Did we do that?

No :(

**Comment by liukun4515** [comment]
`cmake .. -DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang`` to is ok to compile project.

llvm --version

```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by liukun4515** [comment]
But I'm very confused, why not support the gcc compiler on the mac os?
@nikitamikhaylov

**Comment by alexey-milovidov** [comment]
We don't support gcc-8 anymore. Only gcc-9.
