### ISSUE TITLE
Enum as Int while inserting data in CSV

### ISSUE THREAD

**Issue by petrushenkovtb** [ClickHouse/ClickHouse#7971]
```
create table test
(
    Id Int32,
    EnumColumn Enum('sss' = 1, 'eee' = 2)
) ENGINE=ReplacingMergeTree()
    ORDER BY Id;
```

clickhouse-client --format_csv_delimiter="," --query="INSERT INTO test FORMAT CSV" < file.csv

file.csv contains the following data:
`4, 1`

Returned error:
Code: 49. DB::Exception: Unknown element '1' for type Enum8

But such insert works in case it is done in clickhouse client like:
insert into test (Id, EnumColumn) VALUES (4, 1);

Can you please confirm that inserting int for enum does not work at all for CSV import? Or there is some clickhouse setting that can solve it?

**Comment by nikitamikhaylov** [comment]
Which version of ClickHouse did you test?

**Comment by petrushenkovtb** [comment]
Latest Clickhouse in container

**Comment by petrushenkovtb** [comment]
ClickHouse client version 19.15.2.2 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.15.2 revision 54426.

**Comment by blinkov** [comment]
@petrushenkovtb, do you have any further questions?

**Comment by alexey-milovidov** [comment]
> Can you please confirm that inserting int for enum does not work at all for CSV import?

Yes, Enums are only parsed as their symbolic values - in all text formats like CSV, TSV, JSONEachRow...

But It works for numeric values for Values format because it does automatic implicit type conversions for SQL compatibility.

**Comment by alexey-milovidov** [comment]
It's easy to implement a feature to allow this behaviour under setting. #10682
