### ISSUE TITLE
Is Kafka engine same as Kafka consumer?

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#7977]
1. Is Kafka engine same as Kafka consumer?

2. When I implement `select` query to kafka engine, Does the Kafka engine not only check the storage but also access to Kafka cluster? or only check the storage?

3. When I create MATERIALIZED VIEW with kafka engine,
```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS m_view_test1 ENGINE = MergeTree() ORDER BY (CounterID, EventDate) AS SELECT * from test1;
```
Does MATERIALIZED VIEW implement select query at regular intervals? or more like detecting events?

**Comment by den-crane** [comment]
2. Kafka engine does not store data. Select from KafkaEngine reads kafka topic and moves offset.

>Does MATERIALIZED VIEW implement select query

Kafka engine pulls data from a topic and pushes to MV.

**Comment by chu1070y** [comment]
> Kafka engine pulls data from a topic and pushes to MV.

You are saying that Kafka engine is the one which sends the data to MV?

I was thinking MV is the one that pull data of itself.
