### ISSUE TITLE
always_quote_identifiers = true unconditionally though identifier_quoting_style can be None 

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#7984]
https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Storages/transformQueryForExternalDatabase.cpp#L203

This leads to an odbc-bridge exception

Code: 86, e.displayText() = DB::Exception: Received error from remote server /columns_info?connection_string=DSN%3ODBC_DSN%3BUID%3Dclickhouse_login%3BPWD%3Dclickhouse_password&schema=dbo&table=vOlolo. HTTP status code: 500 Internal Server Error, body: Error getting columns from ODBC 'Code: 36, e.displayText() = DB::Exception: Incompatible arguments: always_quote_identifiers = true && identifier_quoting_style == IdentifierQuotingStyle::None (version 19.15.2.2 (official build))'
 (version 19.15.2.2 (official build))

https://t.me/clickhouse_ru/130230

**Comment by alexey-milovidov** [comment]
What DBMS you are using in this particular case?
This info is needed to provide a test for #10821

**Comment by alexey-milovidov** [comment]
SAP ASE.

Looks like we will merge without a test.
