### ISSUE TITLE
MySQL Engine support column comments

### ISSUE THREAD

**Issue by tlightsky** [ClickHouse/ClickHouse#7994]
**Use case**
now desc mysql database engine table won't print the comment from mysql table,

**Describe the solution you'd like**
print comment from mysql too when using mysql database engine

**Comment by alexey-milovidov** [comment]
@zhang2014 Maybe you can take a look?

**Comment by zhang2014** [comment]
Ok, I will add it to my todo list.

**Comment by stigsb** [comment]
We have an intern (@sand6255) who can do this.

**Comment by stigsb** [comment]
Can someone assign to @sand6255 ? (@filimonov or @zhang2014 ?)
