### ISSUE TITLE
Add full support of h3 indices

### ISSUE THREAD

**Issue by hombit** [ClickHouse/ClickHouse#8000]
## Add full support of [h3](https://uber.github.io/h3/) spherical index

**Use case**
Spherical index is useful to make geospatial requests, e.g. to find all points inside a circle on sphere.

**Describe the solution you'd like**
Make it possible to call other `h3` functions in addition to `geoToH3`, first of all [grid traversal functions](https://uber.github.io/h3/#/documentation/api-reference/traversal), for instance `kRing` or `hexRange`. Then the circle search can be performed with a command

```sql
SELECT *
FROM some_table
WHERE some_table.h3index IN (
    kRing(
        geoToH3($lon, $lat, res),
        toInt(
            // the length of longest diagonal of a regular hexagon is twice the length of its edge
            ceil(radius / (2 * edgeLengthM(res)))
        )
    )
)
// Second part of the WHERE cause should be performed after previous one, I'm not sure that just AND is enough here
AND greatCircleDistance(some_table.lon, some_table.lat, $lon, $lat) <= radius
```

where `$lon` and `$lat` are coordinates of the circle center in degrees, `radius` is the circle radius in meters, `some_table.lon` and `some_table.lat` are coordinate columns of `some_table`, `some_table.h3index` is precomputed with `geoToH3(some_table.lon, some_table.lat, res)` function index column of `some_table` with resolution `res`, [`edgeLengthM`](https://uber.github.io/h3/#/documentation/api-reference/miscellaneous) returns hexagon edge length.

**Describe alternatives you've considered**
For now Clickhouse has limited support of spherical requests: one can find `h3` index value for some coordinates via `geoToH3`, and find distance between two coordinates on Earth surface via `greatCircleDistance`. User can perform all other logic of the request on the client side.

The another possibility is implementation of other kind of spherical index with new data type, see [`pgsphere` PostgreSQL extension](https://pgsphere.github.io) for example. Probably it is easier to make available other `h3` functions because it is already a part of Clickhouse codebase.

**Comment by javisantana** [comment]
Some suggestions to workaround that. I  think with the regular indexing features the performance is good enough, I wrote [this about geospatial processing with CH](https://carto.com/blog/geospatial-processing-with-clickhouse/)  some time ago but you have some possibilities:

- having `ORDER BY (lon, lat)` provides a good enough index to filter out most of the rows by index and then do the fine grained filtering by `greatCircleDistance` or `pointInPolygon`

- add a new column with the geohash and add it to the order by. Same than H3 but in this case you have `geohashesInBox` which is close to what you are asking for.

- using the first approach and wait for [zcurve branch](https://github.com/ClickHouse/ClickHouse/pull/6286) to be merged, I'd say that's the most interesting feature regarding performance of geospatial queries.

**Comment by hombit** [comment]
@javisantana Thank you for your answer!

In my case I need spherical coordinates not for common geographical problems so I cannot use this approach. I have to care of high longitude points and it could be very tricky to solve this problems on client side.
