### ISSUE TITLE
CH performance and memory utilization

### ISSUE THREAD

**Issue by SreekanthMannari** [ClickHouse/ClickHouse#8015]
Version: ClickHouse 19.13.1.11
Server has 400GB RAM with 48 CPU cores. and 3.2 TB of HDD.

Table has 70 columns. 
Table is partitioned by date. Most of the columns are of type LowCardinality(String)

CREATE TABLE db_dmweb.web_access_logs (
  `source_time` DateTime,
  `source_date` Date DEFAULT toDate(source_time),
  `user_agent_hash` Int64,
  `browser_family` LowCardinality(String),
  `browser_version` LowCardinality(String),
  `os_family` LowCardinality(String),
  `os_version` LowCardinality(String),
  `device_family` LowCardinality(String),
  `device_model` LowCardinality(String),
  `device_brand` LowCardinality(String),
  ----
  ----
) ENGINE = ReplicatedMergeTree(
  '/clickhouse/tables/{shard}/web_access_logs',
  '{replica}'
) PARTITION BY source_date
ORDER BY
  (
    cluster_name,
    x_ebay_pop_id,
    country_code,
    base_path,
    authority,
    usecase,
    referer_domain,
    browser_family,
    os_family,
    response_group,
    response,
    source_time
  ) SAMPLE BY cluster_name SETTINGS index_granularity = 8192

Rows per day = 550M
Table has 15 days of data.

From System.parts table:
Each part is ~37GB.

On a typical day, partitions are looking as below.
name				marks	rows		data_compressed_bytes	data_uncompressed_bytes
20191201_0_11252_6		29591	225326255	36327173543	104483234620
20191201_11253_22651_6		29894	228728641	39251424405	108411403646
20191201_22652_24970_5		6126	46572302	8305781898	22342092755
20191201_24971_27313_5		6156	47009435	8297363866	22510015550
20191201_27314_27881_4		1504	11393427	2002217201	5441708006
20191201_27882_27999_3		315	2365244		425571454	1132733497
20191201_28000_28105_3		278	2126884		384970910	1024416761
20191201_28106_29382_8		409	3099264		591241745	1529317871
20191201_29383_29720_55		21	144277		28899110	70300724
20191201_29721_34993_2435	32	162494		1421590		22947146
20191201_34994_34997_1		2	118		6132		19691

Running below query:
WITH INTERVAL 1 DAY AS interval_days
select count(duration) as total_count,
median(duration) AS duration_p50,
avg(duration) AS avg_p50
FROM db_dmweb.web_access_logs
WHERE source_date between today()-interval_days and today()

When there is no other read load on server above query takes 1.88secs.
When 10 clients are connected in parallel, above query takes 18secs. 
More the clients, higher the time (with 30 parallel connections above query takes almost a 100secs).

From system.query_log table:
When 10 parallel queries are running (same query 10 clients):
Read_rows: 1127891733
Read bytes: 6767350398
Memory_used: 312175718 = ~312MB

When single client is running:
Memory_used: 39764420 = ~39MB

Even though the system has 400GB memory, utlization per query is less. 
How can I improve the speediness of query by utilizing more available memory?
How can I support multiple simultaneous queries?

The settings I changed and tried so far are:
simultaneous queries 1000 in config.xml
(I had to increase simultaneous queries because, more read queries are blocking writes and causing data loss)

I have created a separate user for reads and profile is as below.
Commented memory setting are the once that I tried. But they didnt work.
 <readprofile>
    
	<preferred_block_size_bytes>42691732171</preferred_block_size_bytes>
	<max_block_size>259840308</max_block_size>
	
	<max_read_buffer_size>10485760</max_read_buffer_size>

    
    <use_uncompressed_cache>0</use_uncompressed_cache>            
    <load_balancing>random</load_balancing>
    <log_queries>1</log_queries>
</readprofile>

Can you recommend some optimal settings for my scenario.

**Comment by den-crane** [comment]
> <max_block_size>259840308</max_block_size>

Don't do it. 65k is optimal for the most usecases.


Check a size of duration column
```
select formatReadableSize(sum(column_data_compressed_bytes) as x) size, 
      formatReadableSize(sum(column_bytes_on_disk)), 
      formatReadableSize(sum(column_data_uncompressed_bytes))
      , database,table, column, partition
from system.parts_columns 
where active = 1 and table like '%web_access_logs%'  and  column = 'duration'
group by database,table, column, partition
order by x desc
```

>When there is no other read load on server above query takes 1.88secs.
>When 10 clients are connected in parallel, above query takes 18secs.

Basically it's about normal depends of type and size of `duration` column and it's slow because of `median` .

1.88 / 18 secs because of parallelism. 

```
set max_threads=1
select count(x),avg(x),median(x) from y prewhere day=today()-1
1 rows in set. Elapsed: 6.407 sec. Processed 801.48 million rows, 4.14 GB (125.09 million rows/s., 645.48 MB/s.)

set max_threads=48
select count(x),avg(x),median(x) from y prewhere day=today()-1
1 rows in set. Elapsed: 0.297 sec. Processed 801.48 million rows, 4.14 GB (2.70 billion rows/s., 13.93 GB/s.)
```

If you need faster pre-aggregate duration using MV and AggregatingMergeTree.

**Comment by den-crane** [comment]
Example with MV

```
CREATE TABLE web_access_logs (
date Date,
duration UInt64)
Engine = MergeTree order by date

create materialized view web_access_logs_mv Engine=AggregatingMergeTree partition by date order by date
as select date, sumState(toUInt64(1)) cntduration, avgState(duration) avgduration, medianState(duration) medianduration
from web_access_logs
group by date

insert into web_access_logs select today(), intDiv(rand64(), 6676786) from numbers(100000000);
 

set max_threads=1
select count(duration) as total_count,
median(duration) AS duration_p50,
avg(duration) AS avg_p50
FROM web_access_logs
WHERE date = today()

┌─total_count─┬──duration_p50─┬───────────avg_p50─┐
│   100000000 │ 1373750898144 │ 90025762744.36443 │
└─────────────┴───────────────┴───────────────────┘

1 rows in set. Elapsed: 2.199 sec. Processed 100.00 million rows, 1.00 GB (45.48 million rows/s., 454.83 MB/s.)

SELECT
    sumMerge(cntduration) AS total_count,
    medianMerge(medianduration) AS duration_p50,
    avgMerge(avgduration) AS avg_p50
FROM web_access_logs_mv
WHERE date = today()

┌─total_count─┬──duration_p50─┬───────────avg_p50─┐
│   100000000 │ 1390101646048 │ 90025762744.36443 │
└─────────────┴───────────────┴───────────────────┘

1 rows in set. Elapsed: 0.017 sec.


```
