### ISSUE TITLE
What it depends on that ClickHouse will trigger DELETE/UPDATE syntaxs

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#8017]
When I used the 

> ALTER TABLE [db.]table DELETE WHERE filter_expr

I found out that it took so many hours to delete all data.
I know the delete/update process is running in background,so I would like to know the mechanism that what it depends on that ClickHouse will trigger the operation?

**Comment by den-crane** [comment]
CH starts to execute`Alter delete`  in background  right after you called it (if it is not blocked by other running delete or a running merge). It takes so long because it rewrites all data.

Try `truncate table` or `drop partition` if you need to remove all rows.

**Comment by byx313** [comment]
> CH starts to execute`Alter delete` in background right after you called it (if it is not blocked by other running delete or a running merge). It takes so long because it rewrites all data.
> 
> Try `truncate table` or `drop partition` if you need to remove all rows.

Do you mean that （1）CH get all data （2） check data whether meet the delete expression （3）delete the data and rewrite the left data to the disk?

**Comment by den-crane** [comment]
Yes. CH evaluates which parts should be mutated (using where conditions) and do a special merge for those parts (CH writes each parts' columns to a new file excluding removed rows -> replaces old parts with new).

**Comment by byx313** [comment]
thx you so much!
