### ISSUE TITLE
fail to create the table 'ontime' when i import the Example Datasets

### ISSUE THREAD

**Issue by KingOfMonkey** [ClickHouse/ClickHouse#8018]
hello,  the version of my clickhouse is 1.1.54236, and i import the ontime data by Download of Prepared Partitions， when i restart the client-server, it show me this error:  Syntax error (in file /u01/clickhouse......../ontime.sql) failed at position 2876(line 114 col 1) : PARTITION BY toYYYYMM(FlightDate) ORDER BY (Year, FlightDate) SETTINGS index_granularity = 8192, please help me ,thanks !

**Comment by alesapin** [comment]
You use an outdated ClickHouse version, which doesn't support modern MergeTree DDL. It was introduced more than 2 years ago, so I recommend you to update your version to current stable (and also read compatibility notes).
