### ISSUE TITLE
clickhouse timezone question

### ISSUE THREAD

**Issue by orangeops** [ClickHouse/ClickHouse#8020]
Now we use pg2ch to synchronize the data in psotgres to Clickhouse. After synchronization, we find that the time in Clickhouse is 8 hours less. Then we check that the system time of Postgres is 00:00 on November 23, 2019 in East 8 time zone, PRC in Postgres, and 16:00 on November 22, 2019 in Clickhouse The system time of is the time of zone 8 in the East. In the configuration file config.xml of Clickhouse, configure the time zone as "Asia / Shanghai". 

Then we use DataGrid to query the time is December 3, 2019. The result of DataGrid query is November 2, 2019 at 16 o'clock

**Comment by den-crane** [comment]
Check this https://github.com/ClickHouse/ClickHouse/issues/7961#issuecomment-559833272

**Comment by blinkov** [comment]
@orangeops, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@orangeops You can explicitly specify the desired timezone in DateTime type to avoid this issue:
```
DateTime('Asia/Shanghai')
```
and I hope that pg2ch will understand that.
