### ISSUE TITLE
Use https://www.cyrusimap.org/sasl/ instead of https://www.gnu.org/software/gsasl/

### ISSUE THREAD

**Issue by dmitko** [ClickHouse/ClickHouse#8026]
Hello,

CH now uses https://www.gnu.org/software/gsasl/ which has LGPL license. Can you consider using https://www.cyrusimap.org/sasl/ instead that has a better license?

**Comment by alexey-milovidov** [comment]
CC @traceon

**Comment by alexey-milovidov** [comment]
@dmitko Is license the only concern?
We use it with full compliance with the license.

So the issue exists only in the case when all of the following conditions are met:
- you have created and redistribute your own modification of ClickHouse;
- without providing access to it's source code;
- with the SASL library enabled in build;
- with static linking to this library;
- without any other possibility for the users to relink your build with other compatible library.

Nevertheless, there is a chance that we will replace GSASL to Cyrus SASL.

**Comment by filimonov** [comment]
Since #12771 cyrus is included and used for rdkafka.

I think now we can also switch hdfs to use cyrus. Also openldap need to have cyrus

**Comment by alexey-milovidov** [comment]
Nothing was done.
