### ISSUE TITLE
A strange behavior with between operator

### ISSUE THREAD

**Issue by avointsev** [ClickHouse/ClickHouse#8031]
Hello,

I found a strange behavior if we using "between" operator with an incorrect second date, CH include an incorrect date in the calculations 
It only reproduced with months that have 30 days and we are put the 31st day (incorrectly)

`
:) select count(1) FROM events WHERE event_date BETWEEN '2019-09-01' AND '2019-09-31' ;

SELECT count(1)
FROM events
WHERE (event_date >= '2019-09-01') AND (event_date <= '2019-09-31')

┌──count(1)─┐
│ 179842712 │
└───────────┘

1 rows in set. Elapsed: 0.067 sec. Processed 179.85 million rows, 359.70 MB (2.69 billion rows/s., 5.38 GB/s.)

:) select count(1) FROM events WHERE event_date BETWEEN '2019-09-01' AND '2019-09-30' ;

SELECT count(1)
FROM events
WHERE (event_date >= '2019-09-01') AND (event_date <= '2019-09-30')

┌──count(1)─┐
│ 172895088 │
└───────────┘

1 rows in set. Elapsed: 0.069 sec. Processed 172.90 million rows, 345.79 MB (2.50 billion rows/s., 4.99 GB/s.)

:) SELECT event_date, count() AS cnt FROM events WHERE event_date BETWEEN '2019-09-01' AND '2019-09-31'  group by event_date ;

SELECT
    event_date,
    count() AS cnt
FROM events
WHERE (event_date >= '2019-09-01') AND (event_date <= '2019-09-31')
GROUP BY event_date

┌─event_date─┬─────cnt─┐
│ 2019-09-01 │ 5074149 │
│ 2019-09-02 │ 5402675 │
│ 2019-09-03 │ 5429046 │
│ 2019-09-04 │ 5273975 │
│ 2019-09-05 │ 5385207 │
│ 2019-09-06 │ 5237619 │
│ 2019-09-07 │ 4639369 │
│ 2019-09-08 │ 5545575 │
│ 2019-09-09 │ 5290333 │
│ 2019-09-10 │ 5080842 │
│ 2019-09-11 │ 5262414 │
│ 2019-09-12 │ 5374077 │
│ 2019-09-13 │ 5300370 │
│ 2019-09-14 │ 4965048 │
│ 2019-09-15 │ 5692718 │
│ 2019-09-16 │ 5163368 │
│ 2019-09-17 │ 5806017 │
│ 2019-09-18 │ 5533989 │
│ 2019-09-19 │ 6232366 │
│ 2019-09-20 │ 6626302 │
│ 2019-09-21 │ 6098978 │
│ 2019-09-22 │ 6851472 │
│ 2019-09-23 │ 6141789 │
│ 2019-09-24 │ 6265715 │
│ 2019-09-25 │ 6633357 │
│ 2019-09-26 │ 6510426 │
│ 2019-09-27 │ 6260755 │
│ 2019-09-28 │ 5945360 │
│ 2019-09-29 │ 7051704 │
│ 2019-09-30 │ 6820073 │
│ 2019-10-01 │ 6947624 │
└────────────┴─────────┘

31 rows in set. Elapsed: 0.113 sec. Processed 179.85 million rows, 359.70 MB (1.60 billion rows/s., 3.20 GB/s.)

:) select version();

SELECT version()

┌─version()──┐
│ 19.14.6.12 │
└────────────┘

1 rows in set. Elapsed: 0.002 sec.
`

**Comment by den-crane** [comment]
It's expected, not a bug.

https://clickhouse.yandex/docs/
_The behavior of parsing incorrect dates is implementation specific. ClickHouse may return zero date, throw an exception or do "natural" overflow._

**Comment by avointsev** [comment]
Den, thanks for the answer.
Could you provide information about how to control this behavior? For me prefer to get an exception instead of an incorrect result, if someone just does a mistake with date.
Unfortunately, I couldn't find these settings in the documentation (

**Comment by den-crane** [comment]
>Could you say if this possible to control this behavior? 

No. 

>implementation specific.

It means this behavior is different for different functions / parsers.
