### ISSUE TITLE
ClickHouse servers continually grow in RAM usage.

### ISSUE THREAD

**Issue by toby080508050805** [ClickHouse/ClickHouse#8039]
Clickhouse-server version:19.9.5.36

My test server has insert tsv files roughly  8Gb/ 15min.
I apply a following command to load tsv files to clickhouse 

> cat /home/tmp/test*.csv.gz | gzip -dc - | awk -v pu_id=9001 'BEGIN{FS="\t";OFS="\t";}{print $0;}' | clickhouse-client --max_insert_block_size 33554432 --max_memory_usage 100000000000 -q "insert into test_toby.test format TSV"

After that I will use insert select command to generate reports.

But after running a while, ClickHouse servers continually grow in RAM usage (125G+) until server crash or trigger os to restart clickhouse.

I try to figure out why this issue happen so I open htop and insert data by previous command. I found every time I insert data, Clickhouse servers  will allocate more memory and won't release.

The attachment is my clickhouse config.

Do I need to adjust any command or parameters?

Following is one of a table I created to insert tsv data:

>  CREATE TABLE table_lte_pos_all_agg.recent (`DATA_DATE` Date, `DATA_HOUR` Nullable(Int8), `BATCH` FixedString(4), `PU_ID` Int32, `CALL_ID` Nullable(UInt64), `CALL_SEG_ID` Nullable(UInt64), `DATE_TIME` Nullable(DateTime), `DATE_TIME_MS` Nullable(Int16), `EVENT_SEQ_ID` Nullable(Int32), `ERAB_SEQ_ID` Array(Nullable(Int32)), `MSG_ID` Nullable(UInt16), `EVENT_ID` Nullable(Int16), `SERVING_ENODEB_ID` Nullable(Int32), `SERVING_CELL_ID` Nullable(Int8), `SERVING_PCI` Nullable(Int16), `SERVING_RSRP` Nullable(Float64), `SERVING_RSRQ` Nullable(Float64), `SERVING_ENODEB_ID_SCELL` Nullable(String), `SERVING_CELL_ID_SCELL` Nullable(String), `SERVING_PCI_SCELL` Nullable(String), `SERVING_RSRP_SCELL` Nullable(String), `SERVING_RSRQ_SCELL` Nullable(String), `TARGET_SITE_ID` Array(Nullable(Int32)), `TARGET_CELL_ID` Array(Nullable(Int32)), `TARGET_PU_RNC_BSC_ID` Array(Nullable(Int32)), `TARGET_TAC_LAC` Array(Nullable(Int32)), `TARGET_ARFCN` Array(Nullable(Int32)), `TARGET_PCI_PSC_BSIC` Array(Nullable(Int32)), `TARGET_RSRP_RSCP_RSSI` Array(Nullable(Float64)), `TARGET_RSRQ_ECN0` Array(Nullable(Float64)), `NBR_ENODEB_ID_SCELL` Array(Nullable(Int32)), `NBR_CELL_ID_SCELL` Array(Nullable(Int32)), `NBR_PCI_SCELL` Array(Nullable(Int32)), `NBR_RSRP_SCELL` Array(Nullable(Float64)), `NBR_RSRQ_SCELL` Array(Nullable(Float64)), `UL_TRAFFIC_DUR` Nullable(Float64), `UL_TRAFFIC_VOL` Nullable(Float64), `UL_TPT_AVG` Nullable(Float64), `UL_TPT_MAX` Nullable(Float64), `DL_TRAFFIC_DUR` Nullable(Float64), `DL_TRAFFIC_VOL` Nullable(Float64), `DL_TPT_AVG` Nullable(Float64), `DL_TPT_MAX` Nullable(Float64), `DL_TRAFFIC_DUR_OPT` Nullable(Float64), `DL_TRAFFIC_VOL_OPT` Nullable(Float64), `DL_TPT_AVG_OPT` Nullable(Float64), `ERAB_ID` Array(Nullable(Int32)), `QCI` Array(Nullable(Int32)), `TA` Nullable(UInt16), `EVENT_CAUSE_ID` Nullable(Int32), `RESULT_IND` Nullable(Int8), `FAILURE_CAUSE_ID` Nullable(Int32), `VOLTE_FLAG` Nullable(Int8), `CA_FLAG` Nullable(Int8), `APN` Nullable(String), `APN_ID` Nullable(UInt16), `MDT_SHAPE_TYPE` Nullable(Int16), `MDT_LONGITUDE` Nullable(Float64), `MDT_LATITUDE` Nullable(Float64), `MDT_ALTITUDE` Nullable(Float64), `MDT_CONFIDENCE` Nullable(Int16), `MDT_ELLIPSOID_INFO` Nullable(String), `CQI1_CNT` Array(Nullable(Int32)), `CQI2_CNT` Array(Nullable(Int32)), `CQI3_CNT` Array(Nullable(Int32)), `CQI4_CNT` Array(Nullable(Int32)), `SINR_PUSCH_CNT` Array(Nullable(Int32)), `SINR_PUCCH_CNT` Array(Nullable(Int32)), `RANK_CNT` Array(Nullable(Int32)), `MIMO_INDICATOR` Nullable(UInt16), `MIMO_TYPE` Nullable(UInt16), `MIMO_4_4_TOTAL` Nullable(UInt16), `MIMO_TOTAL` Nullable(UInt16), `MIMO_NON_MIMO_TOTAL` Nullable(UInt16), `LOC_ID` Nullable(Int64), `TILE_ID` Nullable(Int64), `TILE_LON` Nullable(Float64), `TILE_LAT` Nullable(Float64), `DISTANCE_BEST_CELL` Nullable(Float64), `DISTANCE_SERVING_CELL` Nullable(Float64), `POS_CAUSE` Nullable(Int64), `CONF` Nullable(Int8), `VAR` Nullable(UInt16), `MOVING` Nullable(Int8), `INDOOR` Nullable(Int8), `LONGITUDE` Nullable(Float64), `LATITUDE` Nullable(Float64), `ALTITUDE` Nullable(Float64), `MOVING_S` Nullable(Float64), `MOVING_T` Nullable(Int8), `MOVING_D` Nullable(Int16), `PINGPONG_TIMEGAP` Nullable(Int64), `IMSI` Nullable(String), `M_TMSI` Nullable(String), `MCC` Nullable(String), `MNC` Nullable(String), `IMSI_GROUP_ID` Nullable(Int16), `IMEI` String, `MAKE_ID` Nullable(UInt16), `MODEL_ID` Nullable(Int32), `CALL_TYPE` Nullable(Int8), `CALL_STATUS` Nullable(Int8), `BEST_RSRP_RSCP_RSSI` Nullable(Int16), `BEST_RSRQ_ECN0` Nullable(Float64), `BEST_PCI` Nullable(Int16), `BEST_ENODEB_ID` Nullable(Int32), `BEST_CELL_ID` Nullable(Int8), `SERVING_TA` Nullable(UInt16), `TAREGT_TA` Nullable(UInt16), `INTERFERED_IND` Nullable(Int8), `INTERFERED_IND_TARGET_CELL` Array(Nullable(Int32)), `PATH_LOSS` Nullable(Float64), `PATH_LOSS_TARGET_CELL` Array(Nullable(Float64)), `RSRP_GAP` Nullable(Float64), `SERVING_OVERSHOOT_IND` Nullable(Int8), `SERVING_OVERSHOOT_IND_MAIN` Nullable(Int8), `TARGET_OVERSHOOT_IND` Array(Nullable(Int32)), `TARGET_OVERSHOOT_IND_MAIN` Array(Nullable(Int32)), `SERVING_TAC` Nullable(Int32), `SERVING_CELL_NAME` Nullable(String), `SERVING_EARFCN` Nullable(Int32), `SERVING_FREQUENCY` Nullable(Int16), `TARGET_CELL_NAME` Array(Nullable(String)), `TARGET_FREQUENCY` Array(Nullable(Int32)), `BEST_PU` Nullable(Int32), `BEST_TAC` Nullable(Int32), `BEST_CELL_NAME` Nullable(String), `BEST_EARFCN` Nullable(Int32), `BEST_FREQUENCY` Nullable(Int16), `SERVING_CELL_LAT` Nullable(Float64), `SERVING_CELL_LON` Nullable(Float64), `SERVING_CELL_AZIMUTH` Nullable(Int32), `TARGET_CELL_LAT` Array(Nullable(Float64)), `TARGET_CELL_LON` Array(Nullable(Float64)), `TARGET_CELL_AZIMUTH` Array(Nullable(Int32))) ENGINE = MergeTree PARTITION BY (DATA_DATE, PU_ID, toUInt32(BATCH)) ORDER BY IMEI SETTINGS index_granularity = 8192

[config.txt](https://github.com/ClickHouse/ClickHouse/files/3924996/config.txt)

**Comment by alesapin** [comment]
Hi, thank you for the report. Can you provide logs from `/var/log/clickhouse-server/clickhouse-server.log` at the moment when server restarts (killed by OOM)?

**Comment by toby080508050805** [comment]
Following attachment is whole log. In the very last page has record server restart moment. OOM dose not worked at this time so server crash at 2019.12.02 02:10:05.211791.  I manually restart a clickhouse server at  16:47:32.725068.

> 2019.12.02 02:01:27.948796 [ 94 ] {c6d771f5-35e7-4ec1-86ca-aeccc47584ba} <Warning> TCPHandler: Client has gone away.
> 2019.12.02 02:01:27.948824 [ 94 ] {c6d771f5-35e7-4ec1-86ca-aeccc47584ba} <Debug> MemoryTracker: Peak memory usage (for query): 1.02 MiB.
> 2019.12.02 02:01:27.948920 [ 94 ] {c6d771f5-35e7-4ec1-86ca-aeccc47584ba} <Information> TCPHandler: Processed in 2.242 sec.
> 2019.12.02 02:01:27.948934 [ 94 ] {} <Information> TCPHandler: Done processing connection.
> 2019.12.02 02:01:27.951519 [ 50 ] {cce2b721-5f45-4919-a1eb-a19495d61e8e} <Error> executeQuery: Code: 210, e.displayText() = DB::NetException: I/O error: Broken pipe, while writing to socket (10.34.32.71:56098) (version 19.9.5.36) (from 10.34.32.71:56098) (in query: SELECT ENB_SITE AS ENODEB_ID, sum(CALL_COUNT) AS dpi_cnt FROM gt_local_dpi.table_match_log  WHERE (DATA_DATE = '2019-12-01') AND (DATA_HOUR = 23) AND (TECH = 'LTE') GROUP BY ENODEB_ID), Stack trace:
> 
> 0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
> 1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x2ffea8f]
> 2. clickhouse-server(DB::WriteBufferFromPocoSocket::nextImpl()+0x6c3) [0x660e9e3]
> 3. clickhouse-server(DB::WriteBuffer::next()+0x26) [0x300b746]
> 4. clickhouse-server(DB::TCPHandler::processOrdinaryQuery()+0x972) [0x30060f2]
> 5. clickhouse-server(DB::TCPHandler::runImpl()+0x6c0) [0x3009a50]
> 6. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x300a95c]
> 7. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x667e90f]
> 8. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x166) [0x667ecd6]
> 9. clickhouse-server(Poco::PooledThread::run()+0x77) [0x6c62bf7]
> 10. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x6c5edb8]
> 11. clickhouse-server() [0x711163f]
> 12. /lib64/libpthread.so.0() [0x324c407a51]
> 13. /lib64/libc.so.6(clone+0x6d) [0x324c0e896d]
> 
> 2019.12.02 02:01:27.951633 [ 50 ] {cce2b721-5f45-4919-a1eb-a19495d61e8e} <Warning> TCPHandler: Client has gone away.
> 2019.12.02 02:01:27.951655 [ 50 ] {cce2b721-5f45-4919-a1eb-a19495d61e8e} <Debug> MemoryTracker: Peak memory usage (for query): 1.02 MiB.
> 2019.12.02 02:01:27.951752 [ 50 ] {cce2b721-5f45-4919-a1eb-a19495d61e8e} <Debug> MemoryTracker: Peak memory usage (total): 2.04 MiB.
> 2019.12.02 02:01:27.951772 [ 50 ] {cce2b721-5f45-4919-a1eb-a19495d61e8e} <Information> TCPHandler: Processed in 2.246 sec.
> 2019.12.02 02:01:27.951785 [ 50 ] {} <Information> TCPHandler: Done processing connection.
> 2019.12.02 02:05:04.996180 [ 94 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 10.34.32.71:57030
> 2019.12.02 02:05:05.579267 [ 50 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 10.34.32.71:57042
> 2019.12.02 02:05:40.190005 [ 50 ] {} <Debug> TCPHandler: Connected ClickHouse server version 1.1.0, revision: 54385, user: default.
> 2019.12.02 02:05:40.190597 [ 94 ] {} <Debug> TCPHandler: Connected ClickHouse server version 1.1.0, revision: 54385, user: default.
> 2019.12.02 02:05:40.272967 [ 50 ] {3c56234b-de11-4215-9116-ae22ea1849f5} <Debug> executeQuery: (from 10.34.32.71:57042, initial_query_id: 0f556f6d-8435-4b2c-9e14-e3a1c548cb00) SELECT TAC_LAC AS LAC, ENB_SITE AS CELL_ID, sum(CALL_COUNT) AS dpi_cnt FROM gt_local_dpi.table_match_log  WHERE (DATA_DATE = '2019-12-01') AND (DATA_HOUR = 23) AND (TECH = 'UMTS') GROUP BY LAC, CELL_ID
> 2019.12.02 02:05:40.274567 [ 94 ] {cd610c06-d655-4065-b9fb-e9df7fa186d9} <Debug> executeQuery: (from 10.34.32.71:57030, initial_query_id: 72296b01-d276-44d3-ab6a-6749c35e33be) SELECT ENB_SITE AS ENODEB_ID, sum(CALL_COUNT) AS dpi_cnt FROM gt_local_dpi.table_match_log  WHERE (DATA_DATE = '2019-12-01') AND (DATA_HOUR = 23) AND (TECH = 'LTE') GROUP BY ENODEB_ID
> 2019.12.02 02:05:40.349147 [ 94 ] {cd610c06-d655-4065-b9fb-e9df7fa186d9} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(DATA_HOUR = 23) AND (TECH = 'LTE')" moved to PREWHERE
> 2019.12.02 02:05:40.349617 [ 50 ] {3c56234b-de11-4215-9116-ae22ea1849f5} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(DATA_HOUR = 23) AND (TECH = 'UMTS')" moved to PREWHERE
> 2019.12.02 02:08:32.389325 [ 94 ] {cd610c06-d655-4065-b9fb-e9df7fa186d9} <Debug> gt_local_dpi.table_match_log (SelectExecutor): Key condition: (column 0 in [18231, 18231]), (column 1 in [23, 23]), unknown, and, and
> 2019.12.02 02:08:32.389382 [ 94 ] {cd610c06-d655-4065-b9fb-e9df7fa186d9} <Debug> gt_local_dpi.table_match_log (SelectExecutor): MinMax index condition: (column 0 in [18231, 18231]), unknown, unknown, and, and
> 2019.12.02 02:08:32.392775 [ 94 ] {cd610c06-d655-4065-b9fb-e9df7fa186d9} <Debug> gt_local_dpi.table_match_log (SelectExecutor): Selected 0 parts by date, 0 parts by key, 0 marks to read from 0 ranges
> 2019.12.02 02:08:32.392927 [ 94 ] {cd610c06-d655-4065-b9fb-e9df7fa186d9} <Trace> InterpreterSelectQuery: FetchColumns -> WithMergeableState
> 2019.12.02 02:09:39.406672 [ 50 ] {3c56234b-de11-4215-9116-ae22ea1849f5} <Debug> gt_local_dpi.table_match_log (SelectExecutor): Key condition: (column 0 in [18231, 18231]), (column 1 in [23, 23]), unknown, and, and
> 2019.12.02 02:10:05.211791 [ 166 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: 10.34.32.71:57821
> 2019.12.02 16:47:32.709448 [ 1 ] {} <Information> : Starting ClickHouse 19.9.5.36 with revision 54421
> 2019.12.02 16:47:32.725068 [ 1 ] {} <Information> Application: starting up
> 2019.12.02 16:47:32.822910 [ 1 ] {} <Information> StatusFile: Status file /data/clickhouse/status already exists - unclean restart. Contents:
> PID: 50671
> Started at: 2019-11-29 17:03:01
> Revision: 54421

[clickhouse-server.log.tar.gz](https://github.com/ClickHouse/ClickHouse/files/3930204/clickhouse-server.log.tar.gz)

**Comment by toby080508050805** [comment]
I try to  doing some test about parameter "--max_insert_block_size 33554432". I change it to 1481089. Memory growth is decrease from 1GB to 100Mb from every insert query.

**Comment by toby080508050805** [comment]
After updating to version 19.17.15, this issues already be fixed.
