### ISSUE TITLE
Scalability of Materialized Views

### ISSUE THREAD

**Issue by SreekanthMannari** [ClickHouse/ClickHouse#8040]
I have a table partitioned by date. Each day 450M rows are inserted. Batch size is 20K records.
I need to create 10 different MVs, Will it scale?
How does max_concurrent_queries config behave here? Will it consider MV trigger queries as well?

**Comment by nvartolomei** [comment]
@SreekanthMannari few settings to keep in mind

* parallel_view_processing
* max_threads (affects number of views to which you can write in parallel if parallel_view_processing is set, should be set for the user who initiates INSERT).

Does it scale? There is nothing better than benchmarks with real data on real schemas.
