### ISSUE TITLE
Support Settings for Distributed table

### ISSUE THREAD

**Issue by kaijianding** [ClickHouse/ClickHouse#8041]
**Use case**
First create a replicated table
```sql
CREATE TABLE test_local on cluster cluster01 (
  id UInt32,
  dt String
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/test_local', '{replica}') 
ORDER BY tuple()
SETTINGS index_granularity = 8192
```
Then create MV on it
```sql
CREATE MATERIALIZED VIEW test_view_local on cluster cluster01
ENGINE = AggregatingMergeTree()
    partition by dt
    ORDER BY tuple()
    SETTINGS index_granularity = 1
AS SELECT
    dt,
    groupBitmapState(id) as uv
FROM test_local
GROUP BY dt;
```
Finnaly create a Distributed on MV
```sql
CREATE TABLE test_view on cluster cluster01 as test_view_local
ENGINE = Distributed(cluster01, default, test_view_local, rand());
```
Then I met such a situation: the query result is slightly different when different test_view_local  replica is used.
```sql
select groupBitmapMerge(uv) from test_view
```
The test_view_local replicas got different data(I guess it is due to different replica has a different pace to ingest data from the base test_local, also the test_local replicas' data is not fully synchronized), causing the above sql not stable(the second time result can be smaller when I run the query twice)

Then I want to set `load_balancing=first_or_random` and `prefer_localhost_replica=0` for this `test_view`, but not in server level config file

**Describe the solution you'd like**
can use SETTING for Distributed table
```sql
CREATE TABLE test_view on cluster cluster01 as test_view_local
ENGINE = Distributed(cluster01, default, test_view_local, rand())
SETTINGS load_balancing = 'first_or_random', prefer_localhost_replica=0;
```

**Comment by den-crane** [comment]
test_view_local should replicated as well (ReplicatedAggregatingMergeTree)

`MV test_view_local .... FROM test_local` sees only local inserts into test_local.
So each replica has own partial in test_view_local

**Comment by kaijianding** [comment]
though test_view_local is not replicated, the based table test_local is ReplicatedMergeTree.
the test_view_local only sees the local inserts into test_local, but can't see the inserts from another test_local replica?

**Comment by den-crane** [comment]
MV never reads a source table. It just catches inserted rows from insert. So it does not get anything from inserts at another node. You should create MV with ReplicatedAggregatingMergeTree engine.
