### ISSUE TITLE
How to identify rows added by GROUP BY ROLLUP ?

### ISSUE THREAD

**Issue by XavierQuiniou** [ClickHouse/ClickHouse#8045]
ch 19.17.3.7
How to add appropriate labels 'total' and 'subtotal' to lines added by rollup?
Example :
`DROP TABLE IF EXISTS rollup;
CREATE TABLE rollup(A String, B Int32, C Int32) ENGINE = Memory;
INSERT INTO rollup VALUES   ('a', 1, 5),   ('a', 1, 5),   ('a', 2, 50),  ('a', 2, 50);
INSERT INTO rollup VALUES   ('b', 0, 100), ('b', 0, 100), ('b', 2, 200), ('b', 2, 200);
SELECT  A, B, sum(C), count()  from rollup GROUP BY ROLLUP(A, B) ORDER BY A, B FORMAT PrettyCompact; `

Result

<pre>
   +-A---B---sum(C)---count()-+
 1 ¦   ¦ 0 ¦    710 ¦       8 ¦   total
 2 ¦ a ¦ 0 ¦    110 ¦       4 ¦   sub-total val 'a'
 3 ¦ a ¦ 1 ¦     10 ¦       2 ¦
 4 ¦ a ¦ 2 ¦    100 ¦       2 ¦
 5 ¦ b ¦ 0 ¦    600 ¦       4 ¦   sub-total val 'b'
 6 ¦ b ¦ 0 ¦    200 ¦       2 ¦
 7 ¦ b ¦ 2 ¦    400 ¦       2 ¦
   +--------------------------+
</pre>

Line 5, displays '0' in column B. This is a default value. This value does not distinguish line 5 from line 6, whose Column value B is actually '0'. I tried to assign a default value 999999 to column B. But it seems like it does not work: 
Inconsistencies of inserts with default values #7943

**Comment by onine007** [comment]
I have the same question .

**Comment by blinkov** [comment]
@XavierQuiniou, do you have any further questions?

**Comment by XavierQuiniou** [comment]
No answer to my question?
I found a solution here 
 https://dzone.com/articles/implementing-subtotals-aggregations-in-clickhouse
But it's somewhat complex to do such a simple thing.

**Comment by den-crane** [comment]
```

SELECT
    multiIf(isNull(A) AND isNull(B), 'Total', isNull(B) AND isNotNull(A), 'Subtotal', '') AS desc,
    A,
    B,
    s,
    c
FROM
(
    SELECT
        CAST(A, 'Nullable(String)') AS A,
        CAST(B, 'Nullable(Int32)') AS B,
        sum(C) AS s,
        count() AS c
    FROM rollup
    GROUP BY
        A,
        B
        WITH ROLLUP
    ORDER BY
        A ASC,
        B ASC
)

┌─desc─────┬─A────┬────B─┬───s─┬─c─┐
│          │ a    │    1 │  10 │ 2 │
│          │ a    │    2 │ 100 │ 2 │
│ Subtotal │ a    │ ᴺᵁᴸᴸ │ 110 │ 4 │
│          │ b    │    0 │ 200 │ 2 │
│          │ b    │    2 │ 400 │ 2 │
│ Subtotal │ b    │ ᴺᵁᴸᴸ │ 600 │ 4 │
│ Total    │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │ 710 │ 8 │
└──────────┴──────┴──────┴─────┴───┘
```

**Comment by XavierQuiniou** [comment]
Thanks.
Solution is elegant :CAST (A, 'Nullable (String)') AS A
I will never have made the link between nullable () and my problem, although this instruction described in the documentation.
https://clickhouse.tech/docs/en/sql_reference/data_types/nullable/

**Comment by ltylty** [comment]
now grouping is better choice

if(grouping(key) = 1, 'total', key)
