### ISSUE TITLE
SimpleAggregateFunction summed by SummingMergeTree

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#8052]
create table test_table (
  a Int64,
  max_b AggregateFunction(MAX,UInt64),
  max_b_simple SimpleAggregateFunction(MAX, UInt64),
  ssum Int64
) engine = SummingMergeTree() order by a;

insert into test_table select 1 a, maxState(toUInt64(1)), 1, 1;
insert into test_table select 1 a, maxState(toUInt64(2)), 2, 1;

optimize table test_table final;
```
 select a, finalizeAggregation(max_b), max_b_simple from test_table
┌─a─┬─finalizeAggregation(max_b)─┬─max_b_simple─┐
│ 1 │                          2 │            3 │
└───┴────────────────────────────┴──────────────┘
```

expected

```
┌─a─┬─finalizeAggregation(max_b)─┬─max_b_simple─┐
│ 1 │                          2 │            2 │
└───┴────────────────────────────┴──────────────┘
```

19.18.1.1779

**Comment by filimonov** [comment]
Fixed in #18637
