### ISSUE TITLE
SimpleAggregateFunction SUM supports only [U]Int64

### ISSUE THREAD

**Issue by den-crane** [ClickHouse/ClickHouse#8053]
I would like to have ability to store 32, 16 bits sums. But SimpleAggregateFunction allows only 64.

```
create table test_table 
(
  a Int64,
  sum_simple SimpleAggregateFunction(SUM, UInt16),
  min_simple SimpleAggregateFunction(MIN, Int32),
  max_simple SimpleAggregateFunction(MAX, Int32)
 )
engine = AggregatingMergeTree() order by a

DB::Exception: Incompatible data types between aggregate function 'sum'
 which returns UInt64 and column storage type UInt16.
```

**Comment by akuzm** [comment]
Probably the reason is type promotion. We have 'sumWithOverflow' that does not promote the type, but it's not in the list of supported SimpleAggregateFunctions. If we just add it to the list, it should work.
