### ISSUE TITLE
InterpreterSelectQuery with storage complains that physical column is not found

### ISSUE THREAD

**Issue by vzakaznikov** [ClickHouse/ClickHouse#8057]
In the latest master ( `dbms/src/Interpreters/InterpreterSelectQuery.h`) when creating an instance of InterpreterSelectQuery using interface:

```
 /// Read data not from the table specified in the query, but from the specified `storage_`.
InterpreterSelectQuery(
        const ASTPtr & query_ptr_,
        const Context & context_,
        const StoragePtr & storage_,
        const SelectQueryOptions & = {});
```

with storage pointer specified and query pointer set for the query:
     `SELECT * FROM ( SELECT sum(a) FROM ( SELECT a FROM default.table) )`

an exception is raised that complains that physical column `sum(a)` is not found. 
This is invalid as `sum(a)` column should be calculated instead of being provided by the
storage.

For the same query as above but using the interface:
```
    InterpreterSelectQuery(
        const ASTPtr & query_ptr_,
        const Context & context_,
        const SelectQueryOptions &,
        const Names & required_result_column_names_ = Names{});
```
no exception is raised and query result is as expected.

**Comment by alexey-milovidov** [comment]
But you read from subquery, not from storage.
The argument `storage` is not "transitive", it applies only to outer SELECT.
