### ISSUE TITLE
Unsupported type FixedString(1) when selecting from mysql

### ISSUE THREAD

**Issue by alexmgit** [ClickHouse/ClickHouse#8060]
Есть примерно такая mysql таблица:
```
create table _test_binary
(
	id     int auto_increment
		primary key,
	status binary(1) null
);
```

Данные в таблице примерно такие:
```
INSERT INTO _test_binary (id, status) VALUES (1, 'a');
INSERT INTO _test_binary (id, status) VALUES (2, 'a');
INSERT INTO _test_binary (id, status) VALUES (3, 'a');
INSERT INTO _test_binary (id, status) VALUES (4, 'b');
INSERT INTO _test_binary (id, status) VALUES (5, 'c');
```

В clickhouse создаю аналог таблицы:
```
CREATE table _test_binary (
    id Int32,
    status String
) ENGINE = MergeTree() ORDER BY (id);
```

При попытке вставить данные из mysql в clickhouse:
`INSERT INTO _test_binary SELECT * FROM mysql_db._test_binary;`
получаю ошибку:
**Code: 50, e.displayText() = DB::Exception: Unsupported type FixedString(1) (version 19.17.4.11 (official build))**

При исключении поля status из запроса к mysql ошибка пропадает:
`INSERT INTO _test_binary SELECT id, '' FROM mysql_db._test_binary;`

При попытке отфильтровать по status в запросе к mysql ошибка присутствует:
`INSERT INTO _test_binary SELECT id, 'v' FROM mysql_db._test_binary WHERE status = 'v';`

**Comment by filimonov** [comment]
Duplicate #6556

**Comment by alexmgit** [comment]
Это не дубль задачи #6556. И дело не типе колонки clickhouse. Даже просто выполнив запрос SELECT * FROM mysql_db._test_binary; получаю ошибку Unsupported type FixedString(1) (version 20.2.1.2229 (official build)). Т.е. clickhouse не понимает тип binary(1) в mysql.

**Comment by alexmgit** [comment]
На данный момент есть решение с созданием представления таблицы, где колонка binary(1) конвертируется в CHAR(1):
CREATE OR REPLACE VIEW _test_binary_view (id, status) AS SELECT `id`, CONVERT(`status`, CHAR(1)) FROM _test_binary;
Но это колхоз, конечно же
