### ISSUE TITLE
max( empty set ) does not return null

### ISSUE THREAD

**Issue by ghuname** [ClickHouse/ClickHouse#8061]
If I am selecting from empty table (no records)

```
CREATE TABLE database.missing_intervals on cluster grabber (
`startOf15Min` DateTime,
 `missingCustomerId` String,
 `nrOfUniqExactCustomerIds` UInt64,
 `startOf15MinDay` Date DEFAULT toDate(startOf15Min)
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/...', '{replica}') 
PARTITION BY startOf15MinDay 
ORDER BY startOf15Min

select max(startOf15Min), ifNull(max(startOf15Min), 'test')  new_period 
from database.missing_intervals 
```

returns

```
SELECT 
    max(startOf15Min), 
    ifNull(max(startOf15Min), 'test') AS new_period
FROM ngaspevo.missing_intervals

┌───max(startOf15Min)─┬──────────new_period─┐
│ 0000-00-00 00:00:00 │ 0000-00-00 00:00:00 │
└─────────────────────┴─────────────────────┘

```

It should return 'test' as new_period. 
In dbeaver value 0000-00-00 00:00:00 is interpreted as [NULL].

**Comment by filimonov** [comment]
The thing is that max doesn't return null here.

```
SELECT max(number) FROM numbers(0)

┌─max(number)─┐
│           0 │
└─────────────┘
```

In recent ClickHouse versiosn you can use `maxOrNull` instead max to get nulls in case of empty dataset.

**Comment by ghuname** [comment]
Well, actually it returns '0000-00-00 00:00:00'. Is it null datetime or not?

**Comment by filimonov** [comment]
It is NOT null. It is default value for DateTime (it's zero for ints,  '0000-00-00 00:00:00' for DateTime, emty string for string etc)

**Comment by ghuname** [comment]
How can selecting from empty table return something that is not null?
Do you consider it as a bug or not? As I can see you removed bug label few days ago.
So, it is expected behavior or...?

**Comment by den-crane** [comment]
It's expected behavior. A feature not a bug.

Nullable types are slower up to 2-3 times that's why CH does not follow general SQL.

```
select max(a) from (select cast(1, 'Nullable(Int64)') a) where 0;
┌─max(a)─┐
│   ᴺᵁᴸᴸ │
└────────┘

 select max(a) from (select 1 a) where 0
┌─max(a)─┐
│      0 │
└────────┘
```

Moreover, e.g. I use

```
set empty_result_for_aggregation_by_empty_set=1
select max(a) from (select 1 a) where 0
Ok.

0 rows in set.
```

**Comment by ghuname** [comment]
It is quite pity how clickhouse handles null values, and that using null values causes performance issues.

Is there a possibility that handling null values will change in the future?

**Comment by den-crane** [comment]
The future's not set.

**Comment by ghuname** [comment]
I hope so.
