### ISSUE TITLE
[Gentoo] Poco::Net::SocketImpl::sendBytes related segfault 

### ISSUE THREAD

**Issue by shuliakovsky** [ClickHouse/ClickHouse#8064]
**clickhouse-server version**: version 19.15.2.2
**OS**: Linux clickhouse-dev-node-1 5.3.7-gentoo #1 SMP PREEMPT Wed Oct 23 12:06:22 MSK 2019 x86_64 Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz GenuineIntel GNU/Linux
**Cluster description**:
3 nodes clickhouse-cluster with zookeeper
**clickhouse-configuration:** 
users.xml distributed with installation
config.xml distributed with installation plus
additional configs in /etc/conf.d/

```
<yandex>
  <interserver_http_host>real_ip</interserver_http_host>
  <listen_host>real_ip</listen_host>
</yandex>
<yandex>
  <macros>
    <cluster>clickhouse_remote_servers</cluster>
            <shard>analytics</shard>
            <replica>real_ip</replica>
  </macros>
</yandex> 
```
```
<yandex>
  <remote_servers>
    <clickhouse_remote_servers>
      <shard>
        <internal_replication>true</internal_replication>
          <replica>
            <host>node1ip</host>
            <port>9000</port>
          </replica>
          <replica>
            <host>node2ip</host>
            <port>9000</port>
          </replica>
          <replica>
            <host>node3ip</host>
            <port>9000</port>
          </replica>
      </shard>
    </clickhouse_remote_servers>
  </remote_servers>
</yandex>
```
```
<yandex>
  <zookeeper>
    <node>
      <host>node1ip</host>
      <port>2181</port>
    </node>
    <node>
      <host>node2ip</host>
      <port>2181</port>
    </node>
    <node>
      <host>node3ip</host>
      <port>2181</port>
    </node>
  </zookeeper>
</yandex>
```
[clickhouse-server.err.log](https://github.com/ClickHouse/ClickHouse/files/3932181/clickhouse-server.err.log)

**Comment by filimonov** [comment]
How can we reproduce such a problem? What is 10.0.19.30 ? Why it open/close connections to ClickHouse all the time? 

Does it repeats?

**Comment by filimonov** [comment]
What kind of build do you use?

```
2019.12.06 12:37:43.695434 [ 155 ] {} <Fatal> BaseDaemon: ########################################
2019.12.06 12:37:43.695508 [ 155 ] {} <Fatal> BaseDaemon: (version 19.15.2.2) (from thread 143) Received signal Broken pipe (13).
2019.12.06 12:37:43.695566 [ 155 ] {} <Fatal> BaseDaemon: 
2019.12.06 12:37:43.695644 [ 155 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f3ad8bdd0af 0x7f3ad87cf627 0x7f3ad87d4baa 0x7f3adc90bee5 0x7f3adc5f7699 0x7f3adc2a5414 0x7f3adc5f6c1a 0x7f3ad87d5f86 0x7f3ad87d69ce 0x7f3ad72d658e 0x7f3ad72d4077 0x7f3ad8824426 0x7f3ad8bdb8ee
2019.12.06 12:37:43.695755 [ 155 ] {} <Fatal> BaseDaemon: 4. 0x7f3ad8bdd0af __send /lib64/libc-2.29.so
2019.12.06 12:37:43.697746 [ 155 ] {} <Fatal> BaseDaemon: 5. 0x7f3ad87cf627 Poco::Net::SocketImpl::sendBytes(void const*, int, int) /usr/lib64/libPocoNet.so.60
2019.12.06 12:37:43.702202 [ 155 ] {} <Fatal> BaseDaemon: 6. 0x7f3ad87d4baa Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) /usr/lib64/libPocoNet.so.60
2019.12.06 12:37:43.702286 [ 155 ] {} <Fatal> BaseDaemon: 7. 0x7f3adc90bee5 DB::WriteBufferFromPocoSocket::nextImpl() /usr/lib64/libclickhouse.so.19.15.2.2
2019.12.06 12:37:43.702334 [ 155 ] {} <Fatal> BaseDaemon: 8. 0x7f3adc5f7699 DB::WriteBuffer::next() /usr/lib64/libclickhouse.so.19.15.2.2
2019.12.06 12:37:43.702368 [ 155 ] {} <Fatal> BaseDaemon: 9. 0x7f3adc2a5414 ? /usr/lib64/libclickhouse.so.19.15.2.2
2019.12.06 12:37:43.702389 [ 155 ] {} <Fatal> BaseDaemon: 10. 0x7f3adc5f6c1a DB::TCPHandler::run() /usr/lib64/libclickhouse.so.19.15.2.2
2019.12.06 12:37:43.702404 [ 155 ] {} <Fatal> BaseDaemon: 11. 0x7f3ad87d5f86 Poco::Net::TCPServerConnection::start() /usr/lib64/libPocoNet.so.60
2019.12.06 12:37:43.702417 [ 155 ] {} <Fatal> BaseDaemon: 12. 0x7f3ad87d69ce Poco::Net::TCPServerDispatcher::run() /usr/lib64/libPocoNet.so.60
2019.12.06 12:37:43.702434 [ 155 ] {} <Fatal> BaseDaemon: 13. 0x7f3ad72d658e Poco::PooledThread::run() /usr/lib64/libPocoFoundation.so.60
2019.12.06 12:37:43.702447 [ 155 ] {} <Fatal> BaseDaemon: 14. 0x7f3ad72d4077 Poco::ThreadImpl::runnableEntry(void*) /usr/lib64/libPocoFoundation.so.60
```

**Comment by shuliakovsky** [comment]
> How can we reproduce such a problem? What is 10.0.19.30 ? Why it open/close connections to ClickHouse all the time?

it's our service IP  which write/read  to/from clickhouse   

> 
> Does the crash repeats?

yes often, few times per day

**Comment by shuliakovsky** [comment]
> What kind of build do you use?
> 
> ```
> 2019.12.06 12:37:43.695434 [ 155 ] {} <Fatal> BaseDaemon: ########################################
> 2019.12.06 12:37:43.695508 [ 155 ] {} <Fatal> BaseDaemon: (version 19.15.2.2) (from thread 143) Received signal Broken pipe (13).
> 2019.12.06 12:37:43.695566 [ 155 ] {} <Fatal> BaseDaemon: 
> 2019.12.06 12:37:43.695644 [ 155 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f3ad8bdd0af 0x7f3ad87cf627 0x7f3ad87d4baa 0x7f3adc90bee5 0x7f3adc5f7699 0x7f3adc2a5414 0x7f3adc5f6c1a 0x7f3ad87d5f86 0x7f3ad87d69ce 0x7f3ad72d658e 0x7f3ad72d4077 0x7f3ad8824426 0x7f3ad8bdb8ee
> 2019.12.06 12:37:43.695755 [ 155 ] {} <Fatal> BaseDaemon: 4. 0x7f3ad8bdd0af __send /lib64/libc-2.29.so
> 2019.12.06 12:37:43.697746 [ 155 ] {} <Fatal> BaseDaemon: 5. 0x7f3ad87cf627 Poco::Net::SocketImpl::sendBytes(void const*, int, int) /usr/lib64/libPocoNet.so.60
> 2019.12.06 12:37:43.702202 [ 155 ] {} <Fatal> BaseDaemon: 6. 0x7f3ad87d4baa Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) /usr/lib64/libPocoNet.so.60
> 2019.12.06 12:37:43.702286 [ 155 ] {} <Fatal> BaseDaemon: 7. 0x7f3adc90bee5 DB::WriteBufferFromPocoSocket::nextImpl() /usr/lib64/libclickhouse.so.19.15.2.2
> 2019.12.06 12:37:43.702334 [ 155 ] {} <Fatal> BaseDaemon: 8. 0x7f3adc5f7699 DB::WriteBuffer::next() /usr/lib64/libclickhouse.so.19.15.2.2
> 2019.12.06 12:37:43.702368 [ 155 ] {} <Fatal> BaseDaemon: 9. 0x7f3adc2a5414 ? /usr/lib64/libclickhouse.so.19.15.2.2
> 2019.12.06 12:37:43.702389 [ 155 ] {} <Fatal> BaseDaemon: 10. 0x7f3adc5f6c1a DB::TCPHandler::run() /usr/lib64/libclickhouse.so.19.15.2.2
> 2019.12.06 12:37:43.702404 [ 155 ] {} <Fatal> BaseDaemon: 11. 0x7f3ad87d5f86 Poco::Net::TCPServerConnection::start() /usr/lib64/libPocoNet.so.60
> 2019.12.06 12:37:43.702417 [ 155 ] {} <Fatal> BaseDaemon: 12. 0x7f3ad87d69ce Poco::Net::TCPServerDispatcher::run() /usr/lib64/libPocoNet.so.60
> 2019.12.06 12:37:43.702434 [ 155 ] {} <Fatal> BaseDaemon: 13. 0x7f3ad72d658e Poco::PooledThread::run() /usr/lib64/libPocoFoundation.so.60
> 2019.12.06 12:37:43.702447 [ 155 ] {} <Fatal> BaseDaemon: 14. 0x7f3ad72d4077 Poco::ThreadImpl::runnableEntry(void*) /usr/lib64/libPocoFoundation.so.60
> ```

https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-db/clickhouse/clickhouse-19.15.2.2.ebuild
we build clickhouse from that ebuild

**Comment by filimonov** [comment]
> > What kind of build do you use?
> > ```
> > 2019.12.06 12:37:43.695434 [ 155 ] {} <Fatal> BaseDaemon: ########################################
> > 2019.12.06 12:37:43.695508 [ 155 ] {} <Fatal> BaseDaemon: (version 19.15.2.2) (from thread 143) Received signal Broken pipe (13).
> > 2019.12.06 12:37:43.695566 [ 155 ] {} <Fatal> BaseDaemon: 
> > 2019.12.06 12:37:43.695644 [ 155 ] {} <Fatal> BaseDaemon: Stack trace: 0x7f3ad8bdd0af 0x7f3ad87cf627 0x7f3ad87d4baa 0x7f3adc90bee5 0x7f3adc5f7699 0x7f3adc2a5414 0x7f3adc5f6c1a 0x7f3ad87d5f86 0x7f3ad87d69ce 0x7f3ad72d658e 0x7f3ad72d4077 0x7f3ad8824426 0x7f3ad8bdb8ee
> > 2019.12.06 12:37:43.695755 [ 155 ] {} <Fatal> BaseDaemon: 4. 0x7f3ad8bdd0af __send /lib64/libc-2.29.so
> > 2019.12.06 12:37:43.697746 [ 155 ] {} <Fatal> BaseDaemon: 5. 0x7f3ad87cf627 Poco::Net::SocketImpl::sendBytes(void const*, int, int) /usr/lib64/libPocoNet.so.60
> > 2019.12.06 12:37:43.702202 [ 155 ] {} <Fatal> BaseDaemon: 6. 0x7f3ad87d4baa Poco::Net::StreamSocketImpl::sendBytes(void const*, int, int) /usr/lib64/libPocoNet.so.60
> > 2019.12.06 12:37:43.702286 [ 155 ] {} <Fatal> BaseDaemon: 7. 0x7f3adc90bee5 DB::WriteBufferFromPocoSocket::nextImpl() /usr/lib64/libclickhouse.so.19.15.2.2
> > 2019.12.06 12:37:43.702334 [ 155 ] {} <Fatal> BaseDaemon: 8. 0x7f3adc5f7699 DB::WriteBuffer::next() /usr/lib64/libclickhouse.so.19.15.2.2
> > 2019.12.06 12:37:43.702368 [ 155 ] {} <Fatal> BaseDaemon: 9. 0x7f3adc2a5414 ? /usr/lib64/libclickhouse.so.19.15.2.2
> > 2019.12.06 12:37:43.702389 [ 155 ] {} <Fatal> BaseDaemon: 10. 0x7f3adc5f6c1a DB::TCPHandler::run() /usr/lib64/libclickhouse.so.19.15.2.2
> > 2019.12.06 12:37:43.702404 [ 155 ] {} <Fatal> BaseDaemon: 11. 0x7f3ad87d5f86 Poco::Net::TCPServerConnection::start() /usr/lib64/libPocoNet.so.60
> > 2019.12.06 12:37:43.702417 [ 155 ] {} <Fatal> BaseDaemon: 12. 0x7f3ad87d69ce Poco::Net::TCPServerDispatcher::run() /usr/lib64/libPocoNet.so.60
> > 2019.12.06 12:37:43.702434 [ 155 ] {} <Fatal> BaseDaemon: 13. 0x7f3ad72d658e Poco::PooledThread::run() /usr/lib64/libPocoFoundation.so.60
> > 2019.12.06 12:37:43.702447 [ 155 ] {} <Fatal> BaseDaemon: 14. 0x7f3ad72d4077 Poco::ThreadImpl::runnableEntry(void*) /usr/lib64/libPocoFoundation.so.60
> > ```
> 
> https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-db/clickhouse/clickhouse-19.15.2.2.ebuild
> we build clickhouse from that ebuild

I'm afraid that could be the reason. Didn't you consider using ClickHouse binary from official yandex builds (it should be portable between linux distros)?

**Comment by shuliakovsky** [comment]
> > https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-db/clickhouse/clickhouse-19.15.2.2.ebuild
> > we build clickhouse from that ebuild
> 
> I'm afraid that could be the reason. Didn't you consider using ClickHouse binary from official yandex builds? It should be portable between linux distros.
> 
> If you want to build by your own - you need to use libs from contrib folder, not a system one.

Okay. I'll try change out binary with docker image and reopen issue if problem will not solve.
Thank You in advise.

**Comment by alexey-milovidov** [comment]
> /usr/lib64/libPocoNet.so.60

This indicated wrong, broken build.
We don't use shared linking and we don't use libraries from the system.
