### ISSUE TITLE
Translate website 'Overview of ClickHouse Architecture' to Russian

### ISSUE THREAD

**Issue by mgaidamak** [ClickHouse/ClickHouse#8074]
I want to translate 'Overview of ClickHouse Architecture part of development docs to Russian.
Or is there any reason to keep it in English?

**Comment by blinkov** [comment]
@mgaidamak the only reason this translation does not exist yet is lack of human resources. Also keep in mind that its a bit outdated (at least "processors" are not mentioned).

**Comment by alexey-milovidov** [comment]
It will be very appreciated.
I have written it in english to avoid duplicating the efforts.

**Comment by alexey-milovidov** [comment]
You can translate it regardless to the fact that it's a bit outdated and we will update it.
