### ISSUE TITLE
Behaviour of greatCircleDistance function has been changed

### ISSUE THREAD

**Issue by hombit** [ClickHouse/ClickHouse#8080]
**Describe the bug or unexpected behaviour**
The behaviour of `greatCircleDistance` function in current release differs from current master. Previous this function returned length of an arc on the surface of sphere with radius 6372797.560856 meters, but after commit ae2f5ad7d253243130c5f93557021a5fd4b0f91 the output of this function has been changed. It looks like now this function returns the distance between point of an ellipsoid, the constants in the code points to [WGS 84 system](https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84), but I'm not sure. The new behaviour doesn't allow us to name this function after great circle because the surface is not sphere any more.

**Example**

This example compares distances near the equator and the North pole.

**Release 19.17.5**
```sql
SELECT greatCircleDistance(0., 0., 0., 1.) / greatCircleDistance(0., 89., 0., 90.) AS x
```
```text
┌──────────────────x─┐
│ 0.9999999999999986 │
└────────────────────┘
```

**Master**
```sql
SELECT greatCircleDistance(0., 0., 0., 1.) / greatCircleDistance(0., 89., 0., 90.) AS x
```
```text
┌──────────────────x─┐
│ 0.9898663431043628 │
└────────────────────┘
```

**Conclusion**
I propose to keep old `greatCircleDistance` function and introduce some new function for ellipsoid distances.

**Comment by hombit** [comment]
Comparison new and old realisation with [WGS web calculator](https://www.cqsrg.org/tools/GCDistance/)

**Current realisation**
```sql
SELECT greatCircleDistance(0., 0., 0., 1.)
```
```text
┌─greatCircleDistance(0., 0., 0., 1.)─┐
│                           110567.33 │
└─────────────────────────────────────┘
```
**Old realisation**
```sql
SELECT greatCircleDistance(0., 0., 0., 1.)
```
```text
┌─greatCircleDistance(0., 0., 0., 1.)─┐
│                  111226.30000000089 │
└─────────────────────────────────────┘
```
**SQSRG**: 110574.389

**Current realisation**
```sql
SELECT greatCircleDistance(0., 89., 0., 90.)
```
```text
┌─greatCircleDistance(0., 89., 0., 90.)─┐
│                             111699.25 │
└───────────────────────────────────────┘
```
**Old realisation**
```sql
SELECT greatCircleDistance(0., 89., 0., 90.)
```
```text
┌─greatCircleDistance(0., 89., 0., 90.)─┐
│                    111226.30000000105 │
└───────────────────────────────────────┘
```
**SQSRG**: 111693.865

**Comment by hombit** [comment]
Comment to the new `greatCircleDistance` says that the origin of this code is 
https://github.com/sphinxsearch/sphinx/blob/409f2c2b5b2ff70b04e38f92b6b1a890326bad65/src/sphinxexpr.cpp#L3825.

Tests of this project compare the output of this code with [Vincenty's formula](https://en.wikipedia.org/wiki/Vincenty%27s_formulae) which is approximation for ellipsoid distance, WGS 84 ellipsoid is used:
https://github.com/sphinxsearch/sphinx/blob/409f2c2b5b2ff70b04e38f92b6b1a890326bad65/src/tests.cpp#L3577
https://github.com/sphinxsearch/sphinx/blob/409f2c2b5b2ff70b04e38f92b6b1a890326bad65/src/tests.cpp#L3682

**Comment by alexey-milovidov** [comment]
Ok, we should rename it to `WGS84Distance`.

**Comment by alexey-milovidov** [comment]
Please review the https://github.com/ClickHouse/ClickHouse/pull/8086

**Comment by hombit** [comment]
@alexey-milovidov looks fine!
