### ISSUE TITLE
Can't append records to HDFS engine table

### ISSUE THREAD

**Issue by vyrodovalexey** [ClickHouse/ClickHouse#8083]
Can't add records to HDFS engine table:

CREATE TABLE hdfs_engine_table on cluster cluster (name String, value UInt32) ENGINE=HDFS('hdfs://172.30.218.157:8020/clickhouse/test', 'TSV')
ok
INSERT INTO hdfs_engine_table VALUES ('threets', 5)                                                                         
INSERT INTO hdfs_engine_table VALUES

Ok.

1 rows in set. Elapsed: 0.035 sec.

INSERT INTO hdfs_engine_table VALUES ('threet', 6)

INSERT INTO hdfs_engine_table VALUES

Received exception from server (version 19.17.2):
Code: 36. DB::Exception: Received from 172.30.218.157:9000. DB::Exception: File: /clickhouse/test is already exists.

0 rows in set. Elapsed: 0.011 sec.

**Comment by stavrolia** [comment]
HDFS store immutable files, and the library we choose to integrate with HDFS allow only create file or overwrite it. If I understand correctly the main scenario of writing to HDFS is to add new file. So there is no easy way to append rows to file in HDFS by table in ClickHouse.

**Comment by filimonov** [comment]
You can try CREATE new_table ... AS (SELECT * from existring table union all select new_data)

**Comment by vyrodovalexey** [comment]
Thanks!

**Comment by ilejn** [comment]
Actually O_WRITE|O_APPEND is supported by libhdfs3.

**Comment by umlingo** [comment]
> Actually O_WRITE|O_APPEND is supported by libhdfs3.

Can this be used? Or clickhouse already built-in?
https://github.com/ClickHouse-Extras/libhdfs3

**Comment by umlingo** [comment]
> Actually O_WRITE|O_APPEND is supported by libhdfs3.
@ilejn 
Can this be used? Or clickhouse already built-in?
https://github.com/ClickHouse-Extras/libhdfs3
