### ISSUE TITLE
REORGANIZE PARTITIONS to merge a few partitions into one or split one partition into several

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#8089]
**Use case**
We know that we should keep the number of partitions to a minimum, but it is more convenient to store data in smaller partitions, since some data managing operations can only be performed at the partition level (drop, optimize, etc).
For example, it is easier to reload a day of data if we have a table with daily partitions.

**Describe the solution you'd like**
It would be great to have an ability to merge a few partitions into one or split one partition into several.
For example, in a table with daily partitions we could merge older data in monthly partitions to decrease the number of parts per table.

**Comment by filimonov** [comment]
Relates https://github.com/ClickHouse/ClickHouse/issues/13826

**Comment by alexey-milovidov** [comment]
This task is very difficult to implement.
