### ISSUE TITLE
Gentoo ebuild maintainer needed

### ISSUE THREAD

**Issue by vovan47** [ClickHouse/ClickHouse#8090]
Hi guys, Clickhouse Gentoo ebuild needs a new maintainer, please help:
https://packages.gentoo.org/packages/dev-db/clickhouse

**Comment by Perlovka** [comment]
Package has been dropped from the main tree.
Here is a simple binary ebuild, if anyone seeking to use Clickhouse on Gentoo:
https://github.com/Perlovka/portage-overlay/tree/master/dev-db/clickhouse-bin
