### ISSUE TITLE
how to make a distinction between  cube and source ? 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#8091]
Make sure to check documentation https://clickhouse.yandex/docs/en/ first. If the question is concise and probably has a short answer, asking it in Telegram chat https://telegram.me/clickhouse_en is probably the fastest way to find the answer. For more complicated questions, consider asking them on StackOverflow with "clickhouse" tag https://stackoverflow.com/questions/tagged/clickhouse 

If you still prefer GitHub issues, remove all this text and ask your question here.

 DB::Exception: Unknown function GROUPING

Get exception  from execute query :
SELECT fact_1_id,
       fact_2_id,
       SUM(sales_value) AS sales_value,
       GROUPING(fact_1_id) AS f1g, 
       GROUPING(fact_2_id) AS f2g
FROM   dimension_tab
GROUP BY CUBE (fact_1_id, fact_2_id)
HAVING f1g=1
ORDER BY fact_1_id, fact_2_id;

has any other ways

**Comment by ramazanpolat** [comment]
There is no function named as `GROUPING`. What do you want to achieve here?

**Comment by onine007** [comment]
@ramazanpolat 

SQL:
SELECT A, B, sum(C), count() from rollup GROUP BY ROLLUP(A, B) ORDER BY A, B FORMAT PrettyCompact;


   +-A---B---sum(C)---count()-+
 1 ¦   ¦ 0 ¦    710 ¦       8 ¦  
 2 ¦ a ¦ 0 ¦    110 ¦       4 ¦  
 3 ¦ a ¦ 1 ¦     10 ¦       2 ¦
 4 ¦ a ¦ 2 ¦    100 ¦       2 ¦
 5 ¦ b ¦ 0 ¦    600 ¦       4 ¦   
 6 ¦ b ¦ 0 ¦    200 ¦       2 ¦
 7 ¦ b ¦ 2 ¦    400 ¦       2 ¦
   +--------------------------+


i want to identify rows ''total'' and "normal"   like  row:5 and row:6

**Comment by den-crane** [comment]
try Nullable

cast (A, 'Nullable(Int64)') , cast(B,'Nullable(String)'),....

**Comment by onine007** [comment]
@den-crane  if  A  and B are Nullable  already ?

**Comment by den-crane** [comment]
@onine007 then no way.
