### ISSUE TITLE
Slow to download ClickHouse RPM from official repository to Shanghai, China

### ISSUE THREAD

**Issue by huang--yijian** [ClickHouse/ClickHouse#8093]
We follow the official instructions to download and install ClickHouse 19.17 by "sudo yum install clickhouse-server clickhouse-client".

We are in Shanghai, China. 
Downloading ClickHouse RPM from the official ClickHouse repository is very slow, with no more than 40KB/sec, as in the following picture:

![image](https://user-images.githubusercontent.com/7484190/70429099-e1062a80-1ab2-11ea-9592-1cd6170d861a.png)

Is there any way to make download faster, such as deploying the packages in a Chinese yum mirror (maybe mirrors.163.com) ?

**Comment by kaijianding** [comment]
maybe you can download the clickhouse rpm using `thunder` and transfer the file to your machine and install rpm directly

**Comment by huang--yijian** [comment]
> maybe you can download the clickhouse rpm using `thunder` and transfer the file to your machine and install rpm directly

Is it safe to download and install ClickHouse RPMs by "rpm -Fvh", in order to upgrade ClickHouse to 19.17 or later versions in production ?

It skips dependency check by yum install.

**Comment by alexey-milovidov** [comment]
@huang--yijian 
Yes, it is safe. We have removed all the dependencies that may prevent installation.
The `clickhouse` binary itself doesn't have any dependencies except old enough version of `libc` that already exists in the system.

**Comment by huang--yijian** [comment]
> @huang--yijian
> Yes, it is safe. We have removed all the dependencies that may prevent installation.
> The `clickhouse` binary itself doesn't have any dependencies except old enough version of `libc` that already exists in the system.

Thank you. We will install ClickHouse RPMs manually by 'rpm -Fvh'.

**Comment by huang--yijian** [comment]
By the way is http://repo.yandex.ru/clickhouse/rpm/stable/x86_64/clickhouse-common-static-dbg-19.17.6.36-2.x86_64.rpm  required to install ClickHouse 17.17.6 ?

**Comment by alexey-milovidov** [comment]
Debug package is not necessarily to install and usually it's not installed.
The only benefit is to see source files and line numbers in stack traces of exception messages.

**Comment by huang--yijian** [comment]
> Debug package is not necessarily to install and usually it's not installed.
> The only benefit is to see source files and line numbers in stack traces of exception messages.

Thank you for the quick response.
We will upgrade by installing the following 4 RPM packages only:
clickhouse-client-19.17.6.36-2.noarch.rpm
clickhouse-common-static-19.17.6.36-2.x86_64.rpm
clickhouse-server-19.17.6.36-2.noarch.rpm
clickhouse-test-19.17.6.36-2.noarch.rpm

**Comment by huang--yijian** [comment]
![image](https://user-images.githubusercontent.com/7484190/71956282-b03a2200-3225-11ea-959d-649044904961.png)

When we try to update from 19.6.2 (previously installed by Altinity el/6 RPM package) to 19.17.6, the above error in the screenshot happened.
The error is about unsatisfied dependency of version 19.6, while we are upgrading to 19.17. Why ?

**Comment by abcfy2** [comment]
https://mirrors.tuna.tsinghua.edu.cn/clickhouse/

**Comment by blinkov** [comment]
Earlier this year the official repository have moved to https://repo.clickhouse.tech which sits behind global CDN so it usually behaves better than the old one in terms of throughput, including downloads from China.
