### ISSUE TITLE
Unable to load data into table

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#8094]
Hi Trying to load data through CSV file using below command :

clickhouse-client -h xx.xxx.xx.xx0 -u default  --password xxxxxxxxxxasAsd --query="INSERT INTO database.table FORMAT CSV" < /folder/data.csv

Each time I try to load getting the below error 

**ERROR:**
Code: 27. DB::Exception: Cannot parse input: expected , before: \r\n191125467,facebook.comtxamarillo,Westland Corporation,1401 S Ross Blvd,,Amarillo,TX,Texas,79102,US,9999,,facebook.com,8063730430,45,Retail Trade,4533,Used Mer: (at row 1)

Can someone help me to overcome this issue at the earliest, please .

**Comment by ramazanpolat** [comment]
You CSV file is not in proper format. Luckily it is the first row. You can insert first row manually to see what the problem is.

**Comment by Crazylearner30** [comment]
@ramazanpolat : Thanks a lot for the quick response , reordering the file could help?

**Comment by alexey-milovidov** [comment]
Looks like the file contains less number of columns than the table.

**Comment by Crazylearner30** [comment]
@alexey-milovidov : Thanks for the response, initially I thought same and manually checked whether the file has fewer columns but, it has the exactly the same number of columns as in the table.

Keeping @ramazanpolat's comment above in mind I tried to reorder the file and it loaded all the records successfully. 
Am not sure why Clickhouse doesn't support unordered raw file directly into table :(

**Concern:**  if it's a huge file in billions or so reordering can never be a solution as its a memory consuming operation.

**Comment by alexey-milovidov** [comment]
@Crazylearner30 No, the order of file does not matter.

**Comment by alexey-milovidov** [comment]
Probably you have CSV with header but you specified CSV instead of CSVWithNames?

**Comment by Crazylearner30** [comment]
@alexey-milovidov file had no header and i had specified CSV

**Comment by filimonov** [comment]
> @alexey-milovidov file had no header and i had specified CSV

In that case you need to list all the needed columns in your insert statement in the proper order.
I.e. 
```
INSERT INTO table(col3,col1,col2) FORMAT CSV
```
