### ISSUE TITLE
Using compression=true on JDBC fails on FreeBSD

### ISSUE THREAD

**Issue by martenlindblad** [ClickHouse/ClickHouse#8101]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
Using compression=false works fine, setting compression=true results in an error:
`ClickHouse response without column names .`
**How to reproduce**
* Which ClickHouse server version to use
19.11.5.28
* Which interface to use, if matters
JDBC

**Expected behavior**
Connection just works

**Error message and/or stacktrace**
Output from `/var/log/clickhouse/clickhouse-server.err.log`:

`2019.12.09 16:27:59.522159 [ 277 ] {ea205269-440c-43b1-8984-94d6f55c44f6} <Error> virtual DB::WriteBufferFromHTTPServerResponse::~WriteBufferFromHTTPServerResponse(): Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Assertion violation: !_pStream in file "/wrkdirs/usr/ports/devel/poco/work/poco-1.9.0-all/Net/src/HTTPServerResponseImpl.cpp", line 69 (version 19.11.5.28)`

**Additional context**
`FreeBSD <hostname> 12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 GENERIC  amd64`

It seems that there is an issue to fix this but reporting bug anyway: [poco](https://github.com/pocoproject/poco/pull/1574)

**Comment by alexey-milovidov** [comment]
Does it reproduce if you build with bundled libraries (where Poco already contains this patch)?

**Comment by martenlindblad** [comment]
It does not reproduce, with prebundled libaries it works.

**Comment by alexey-milovidov** [comment]
We use multiple patches for Poco. Actually, using "stock" Poco version is not safe with ClickHouse.

**Comment by alexey-milovidov** [comment]
It should work with official binary: https://clickhouse.tech/docs/en/getting-started/install/#from-binaries-non-linux

But we did not validated it. It will be appreciated if you will try official binary and share the findings.
