### ISSUE TITLE
How to export a table into file?

### ISSUE THREAD

**Issue by maxnosib** [ClickHouse/ClickHouse#8102]
УЖАСНАЯ ДОКУМЕНТАЦИЯ ОТСУТСТВИЕ НОРМАЛЬНЫХ ПРИМЕРОВ И НОРМАЛЬНЫХ РАЗЪЯСНЕНИЙ !!!!!!!!!!!!!!!!!!!!!!!!!!!!
ВОПРОС: КАК ВЫГРУЗИТЬ ТАБЛИЦУ В ФАЙЛ. ОТВЕТ: ПРОЧИТАЙТЕ 10 ДРУГОЙ СТРАНИЦ И НЕ НАЙДИТЕ ОТВЕТА.

HORRIBLE DOCUMENTATION NO NORMAL EXAMPLES AND NORMAL EXPLANATIONS !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
QUESTION: HOW TO DOWNLOAD THE TABLE TO A FILE. ANSWER: READ 10 OTHER PAGES AND DO NOT FIND ANSWER.

**Comment by alexey-milovidov** [comment]
`SELECT * FROM table INTO OUTFILE 'file.tsv'`

**Comment by ortal650** [comment]
I tried this querie but got the issue: INTO OUTFILE is not allowed, e.what() = DB::Exception
Any idea how to make it work?

**Comment by den-crane** [comment]
> I tried this querie but got the issue: INTO OUTFILE is not allowed, e.what() = DB::Exception
> Any idea how to make it work?

it works only in clickhouse-client

**Comment by den-crane** [comment]
@ortal650 
https://clickhouse.tech/docs/en/getting_started/install/
https://clickhouse.tech/docs/en/interfaces/cli/

**Comment by NikolayPraydkin** [comment]
как в интерактивном режиме clickhouse-client загрузить tsv файл?

**Comment by den-crane** [comment]
@NikolayPraydkin  clickhouse-client такого не умеет. Можно загрузить sql командой `insert into select from file()` https://clickhouse.tech/docs/en/sql-reference/table-functions/file/ но в этом случае грузить будет clickhouse-server и файл должен быть доступен   clickhouse-server .
