### ISSUE TITLE
Is it possible to limit the results of first stage in query processing?

### ISSUE THREAD

**Issue by achimbab** [ClickHouse/ClickHouse#8110]
I want to limit the results of remote queries when I execute a distribute query.

Because the results of remote queries are too many so it became a bottleneck in my environment.

So I want to limit the results of remote queries although the result of final result will not be accurate.

For example, if executed a below query.

```SQL
SELECT type, count() AS c 
FROM table_distributed 
GROUP BY type
ORDER BY c DESC
LIMIT 10 
SETTINGS first_stage_limit = 20;
```

If the first_stage_limit options is set, it will be rewrote as to below.

The rewrote query will return only 20 countStates ordered by c.

```SQL
SELECT type, count() AS c 
FROM table_local 
GROUP BY type
ORDER BY c DESC
LIMIT 20 
-- With QueryProcessingStage::Enum::Complete
```

Is there a way to do this in ClickHouse?

Thank you.

**Comment by blinkov** [comment]
@achimbab, is this question still relevant?

**Comment by achimbab** [comment]
@blinkov 
Yes, I still wonder how to do this.
Thank you.

**Comment by blinkov** [comment]
@achimbab have you tried `max_rows_to_read=N` with `read_overflow_mode=break`?

**Comment by robot-clickhouse** [comment]
@achimbab, do you have any further questions?
