### ISSUE TITLE
How to let Material View stop checking new data

### ISSUE THREAD

**Issue by jsding** [ClickHouse/ClickHouse#8120]
Since I know no new data will match the material view's  SELECT query, Is there any way to tell clickhouse not to check new incoming data?

Thanks

**Comment by filimonov** [comment]
If your materialized view was created with TO syntax you can just drop materialized view.

**Comment by den-crane** [comment]
detach table MVname / attach table MVname.

Will be automatically attached on CH restart

**Comment by jsding** [comment]
Hi, 

I create material view by
`create MATERIALIZED view v_event_20191209 ENGINE = MergeTree() PARTITION BY (package_name) ORDER BY (package_name, campaign, toDate(it), event_token)  AS select * from rp_event where toDate(created_at/1000) = '2019-12-09'
`
All new data coming after 2019-12-09 will not match the query.

I still need the material view for quering ,but do not want it to hurt clickhouse performance.

**Comment by den-crane** [comment]
@jsding OK. What is your question then?

**Comment by jsding** [comment]
Hi, den,
Should I 
`
detach table .inner. v_event_20191209
`
Not
`detach table  v_event_20191209`

**Comment by den-crane** [comment]
@jsding what are you trying to achieve? Do you need to recreate existing MV ?

**Comment by jsding** [comment]
Hi, den,

We do not want to recreate the existing MVs,  We want to use these MVs but do not want clickhouse   checking new data and insert to these MVs.

Thanks

**Comment by jsding** [comment]
I asked this question, because I assumed too many mvs to one table should hurt the clickhouse performance? Is that true?

**Comment by den-crane** [comment]
> Hi, den,
> 
> We do not want to recreate the existing MVs, We want to use these MVs but do not want clickhouse checking new data and insert to these MVs.
> 
> Thanks

Do you mean you need a data in MV ? You can detach MV and rename .inner table to a table with normal name and remove MV.sql file.

**Comment by den-crane** [comment]
> I asked this question, because I assumed too many mvs to one table should hurt the clickhouse performance? Is that true?

How many? 10 ? 100? Of course any number impact on performance.

**Comment by jsding** [comment]
We roll data daily, so there will be 300+ mv for the table.

**Comment by nvartolomei** [comment]
Why do you need to create a MV per day instead of having a single one partitioned by day?

**Comment by jsding** [comment]
The original table is too big and uncontrollable increased, we have to query data daily and combine them in application layer.

**Comment by den-crane** [comment]
> The original table is too big and uncontrollable increased, we have to query data daily and combine them in application layer.

You are mistaken. @nvartolomei is right. 
You need one MV partitioned by day. 
CH SQL partition pruning works almost exactly the same a query to separated table.

There is no difference
select ... from T where date='2019-12-12'
VS
select ... from T_20191212 

In case of daily partitioning and `where date='2019-12-12'`. It will be separated partition with `'2019-12-12'` and separated set of files. And CH will read only this set of files/rows.

**Comment by jsding** [comment]
Thanks for the information.

BTW, is there any way to change the partitioning key? or I have to create a new table, and copy all data into this new table?

Appreciate for your help.

**Comment by nvartolomei** [comment]
@jsding you will have to create a new table and copy data.
