### ISSUE TITLE
"Too many open files" while loading data into table

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#8121]
Am getting the below error while loading data and only half of the data is being loaded into the table 

DB::Exception: Cannot open file /t-3tb-data/clickhouse/data/database/table/tmp_insert_0c87b3bf0c31a7766299a14d202c8da9_648_648_0/TI_verification_status.mrk, errno: 24, strerror: Too many open files.

Can someone help me quickly here.

**Comment by byx313** [comment]
> Am getting the below error while loading data and only half of the data is being loaded into the table
> 
> DB::Exception: Cannot open file /t-3tb-data/clickhouse/data/database/table/tmp_insert_0c87b3bf0c31a7766299a14d202c8da9_648_648_0/TI_verification_status.mrk, errno: 24, strerror: Too many open files.
> 
> Can someone help me quickly here.

You got too many files in OS.
Method 1,increase open files limit
check open files 
> ulimit -a

increase open files 
> ulimit -n 65536

Method 2,increase messege count in one batch/one insert operation.

**Comment by Crazylearner30** [comment]
@byx313 
I tried the first option but the problem is still same :(
Method2: You mean to say single insert will do than multiple inserts ?

**Comment by byx313** [comment]
> @byx313
> I tried the first option but the problem is still same :(
> Method2: You mean to say single insert will do than multiple inserts ?

Do 'ulimit -a' again to check whether the operation work.

> Method2: You mean to say single insert will do than multiple inserts ?
Yes.10w message a batch a insert is better than 1w message * 10 concurrent insert

**Comment by Crazylearner30** [comment]
@byx313
yes, I did ulimit -a to check and yes the change is reflected.

**Comment by byx313** [comment]
> @byx313
> yes, I did ulimit -a to check and yes the change is reflected.

may be you should try to change you insert frequency.What's the frequency now?

**Comment by Crazylearner30** [comment]
am loading one file after the other , once the first file is loaded starting with the next one.

**Comment by alexey-milovidov** [comment]
This happens because you are using too granular partition key in a table.
Solution: do not use `PARTITION BY`.

**Comment by Crazylearner30** [comment]
@alexey-milovidov  I have partitioned the table on state code which has some 60 values 

So if I don't use the PARTITION BY  it doesn't have impact on queries??

**Comment by Crazylearner30** [comment]
@alexey-milovidov Yes, I removed the PARTITION BY and without any error I could load the data :)
My worry is query returning time. 
Thank you.

**Comment by filimonov** [comment]
> @byx313
> yes, I did ulimit -a to check and yes the change is reflected.

Also for clickhouse user? What is your OS? How did you install/run clickhouse?

**Comment by blinkov** [comment]
@Crazylearner30, do you have any further questions?

**Comment by lookingGordo** [comment]
> > @byx313
> > yes, I did ulimit -a to check and yes the change is reflected.
> 
> Also for clickhouse user? What is your OS? How did you install/run clickhouse?
> 
> I'm asking because official packages should extend that limit during installation, and 9fficial docker readme mentions how to increase max number of opened files for clickhouse.

-----------------------------------------
excuse me, Can you send a link?
