### ISSUE TITLE
MATERIALIZED VIEW from Kafka doesn't insert Nested data

### ISSUE THREAD

**Issue by samuelblawrence** [ClickHouse/ClickHouse#8124]
I have a materialized view loading data from a Kafka table into another table. All works except for the nested data isn't copied across - other fields are correctly populated.

e.g.

```
CREATE TABLE k1 (
  bet_id UInt64,
  parts Nested
	(
		category_name String
	)
) ENGINE = Kafka('localhost:9092', 'fct_bet', 'fctBetGroup', 'JSONEachRow');

CREATE TABLE t1 (
  dt Date,
  bet_id UInt64,
  parts Nested
	(
		category_name String
	)
) ENGINE = MergeTree(dt, bet_id, 8192);

 CREATE MATERIALIZED VIEW v1 TO t1
 AS 
 SELECT	toDate(now()) as dt, bet_id, parts.category_name FROM k1;
```

If I insert ... select (i.e. "insert into t1 select toDate(now()) as dt, bet_id, parts.category_name FROM k1;") then it works correctly, so it's something related to the materialized view. I've also verified that it works correctly with a non-Kafka table as the source.

Sample JSON from Kafka -  {"parts":{"category_name":["Test1","Test2"]},"bet_id":1}

I added <input_format_import_nested_json>1</input_format_import_nested_json> to the default via users.xml (otherwise the nested structure didn't populate in the k1 table).

ClickHouse server version 19.17.4 revision 54428 / client 19.17.4.11 (official build)

No errors appear in the server log.

Hope you can help.

Thanks, S

**Comment by den-crane** [comment]
You've used not a `JSONEachRow`.

That what CH `JSONEachRow` expects

```
{"bet_id":"1","parts.category_name":["a","b"]}
```

```
CREATE TABLE k1 (
  bet_id UInt64, parts Nested (category_name String)) Engine = Memory;

insert into k1 values (1,['a','b']);


select * from k1 format JSONEachRow

SELECT *
FROM k1
FORMAT JSONEachRow

{"bet_id":"1","parts.category_name":["a","b"]}
```

**Comment by samuelblawrence** [comment]
Thanks - I don't have any issue with the data into the k1 table - it's in the right format and works correctly. My problem is with moving the data over to the t1 table - if I "insert into... select" everything works fine, so why should it be different when running from a materialized view?

**Comment by den-crane** [comment]
OK. 

>I added <input_format_import_nested_json>1</input_format_import_nested_json>
>to the default via users.xml 

Please show your users.xml (the part added).

**Comment by samuelblawrence** [comment]
okay - got it working - a server restart seems to have fixed the issue, I guess the users change wasn't picked up by the system process somehow? 

Anyway, appreciate your help - it's a great product!
