### ISSUE TITLE
Centos build the rpm package, not support autocomlete and uparrow command.

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#8125]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
Centos build the rpm package, not support autocomlete and uparrow command.

**How to reproduce**
System CentOS 7
https://github.com/Altinity/clickhouse-rpm.git
clickhouse-rpm builder.
./builder build --rpms --from-sources-in-SOURCES-dir 
then we will have 
clickhouse-client-19.8.3.8-1.el7.x86_64.rpm         clickhouse-debuginfo-19.8.3.8-1.el7.x86_64.rpm  clickhouse-server-common-19.8.3.8-1.el7.x86_64.rpm
clickhouse-common-static-19.8.3.8-1.el7.x86_64.rpm  clickhouse-server-19.8.3.8-1.el7.x86_64.rpm     clickhouse-test-19.8.3.8-1.el7.x86_64.rpm
then
Reinstall clickhouse
sudo yum -y remove clickhouse-common-static.x86_64
sudo yum -y remove clickhouse-server-common.x86_64

cd /data/software/clickhouse-rpm/rpmbuild/RPMS/x86_64

sudo rpm -ivh clickhouse-common-static-19.8.3.8-1.el7.x86_64.rpm
sudo rpm -ivh clickhouse-server-common-19.8.3.8-1.el7.x86_64.rpm
sudo rpm -ivh clickhouse-server-19.8.3.8-1.el7.x86_64.rpm
sudo rpm -ivh clickhouse-client-19.8.3.8-1.el7.x86_64.rpm

sudo service clickhouse-server restart

then 
connect to this server.
clickhouse-client 
press uparrow
client shows ^[[A^[[A
* Which ClickHouse server version to use
19.8.3.8 stable or above.

I have tried to use libtinfo.so and on the icu library, all failed. so help, appreciate in advance.

**Expected behavior**
When I press the uparrow it should show the previous command i input, empty if no command input previously input and Tab clickhosue client should autocomplete.
**Error message and/or stacktrace**
No error message in server's log.
**Additional context**

**Comment by den-crane** [comment]
????

This an Altinity -- unofficial build . Open a ticket in their github https://github.com/Altinity/clickhouse-rpm/issues
