### ISSUE TITLE
OSX build with line editing support

### ISSUE THREAD

**Issue by amosbird** [ClickHouse/ClickHouse#8131]
Current OSX build in CI doesn't provide line editing ability due to the lack of libreadline and libedit. Many MacOS developers would like to have a decent native clickhouse client. Nowadays they either build it by themselves or passing some non-official clickhouse binary around. 

Providing a OSX built with line editing on CI can serve as a good source for this kind of usage.

Following is what I did to build a readline enabled OSX client:

1. extend the yandex/clickhouse-binary-builder docker file with

```
COPY readline.tar.gz /        <-   rl binary is grabbed from macOS 10.15.1 with brew installed one (8.0.1)

RUN mkdir -p /usr/local/opt

RUN tar xzf /readline.tar.gz -C /usr/local/opt   <-   using this path might break non-OSX builds

```

2. provide additional flags to the cmake cmd args of OSX cross compilation:

```
-DENABLE_READLINE=1 

# this is needed because the cmake cxx check is broken when doing osx cross compilation  https://github.com/yandex/ClickHouse/blob/master/cmake/find/readline_edit.cmake#L46
-DHAVE_READLINE_HISTORY_EXITCODE=0  
```

3. build it

@abyss7 could you help implement this? We may need a better source of readline package (or libedit if it's better), and the line editing library finding logic requires update.

**Comment by filimonov** [comment]
I think it's not actual anymore, since we've switched to replxx?
