### ISSUE TITLE
Confused about partition

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#8136]
I know primary.idx is the index file of the belonging partition folder.
I would like to know when I do a query,How CH found the partition folder?Is there a 'big index' in memory,including all partition's index so that CH can hit the partition quickly?
And our partition policy is by day.I am confused that if I change the policy to by second,what's the advantage and disadvantage ?
The last question,If our table's partition is by 'toYYYYMM(date_column)',I do the query is 'date_column' not 'toYYYYMM(date_column)',can it still hit the partition?

**Comment by blinkov** [comment]
@byx313 so what's your question?

**Comment by byx313** [comment]
> @byx313 so what's your question?

Sorry I have changed the question.
Thanks in advance.

**Comment by volfco** [comment]
Partitions are how the data is stored on disk, when you run a query you don't need to worry about which partition your data resides in. Clickhouse will figure out everything. If you partition using `toStartOfDay`, all records from that day are grouped together.

If you do a query for data falling inside a single day, the query will be fast as it only has to look into the single partition. If you are querying data across two or more days, the query would be a bit slower as Clickhouse needs to reads two partitions.

**Comment by volfco** [comment]
The docs give a great overview of partitioning: https://clickhouse.yandex/docs/en/operations/table_engines/mergetree/#use-of-indexes-and-partitions-in-queries

**Comment by den-crane** [comment]
Every part has an attributes minmax_partitioncolumn.idx.
All parts is in memory with this minmax. 

So if your table partitioned by toYYYYMM(date_column) every part will have min and max values of date_column. A query analyzes (partition pruning) an intersection of a query's condition with min max ranges and selects a list of parts to process further with primary indexes and filtering of columns. Both conditions `date_column = > <` and `toYYYYMM(date_column) = > <` are good for partition pruning.
