### ISSUE TITLE
How to set distributed_ddl_task_timeout via HTTP Interface

### ISSUE THREAD

**Issue by andrisnoko** [ClickHouse/ClickHouse#8153]
I am trying to trigger optimization via scheduler that calls ClickHouse via HTTP. I get 
DB::Exception: Watching task /clickhouse/task_queue/ddl/query-0000000397 is executing longer than distributed_ddl_task_timeout (=180) seconds

```
OPTIMIZE TABLE some_local_table ON CLUSTER mycluster PARTITION 201905 
SETTINGS distributed_ddl_task_timeout=1800, optimize_throw_if_noop=1;
```
Seems the `distributed_ddl_task_timeout` is ignored. I also tried to set it as below.

```
http://clickhouse.my.net:8123/?distributed_ddl_task_timeout=1800&query=OPTIMIZE TABLE some_local_table ON CLUSTER mycluster PARTITION 201903  SETTINGS optimize_throw_if_noop=1'
```

I also tried `replication_alter_partitions_sync=2` and still get a timeout.

**Comment by blinkov** [comment]
@andrisnoko, is this question still relevant?

**Comment by blinkov** [comment]
@andrisnoko, do you have any further questions?

**Comment by azat** [comment]
Cannot reproduce it in upstream/master (0bc60e2d534e46975aa8d4816d2175360c602a03)
