### ISSUE TITLE
Problem with constant values in SELECT query to Merge table

### ISSUE THREAD

**Issue by MakarovYaroslav** [ClickHouse/ClickHouse#8165]
I can’t make a query to Merge table with constant values. Although everything worked before.

```
SELECT
    time_local
    response_code,
    'a' AS log_type
FROM test_merge
LIMIT 1

Received exception from server (version 19.17.4):
Code: 171. DB :: Exception: Cannot convert column log_type because it is non constant in source stream but must be constant in result.
```

Merge table created as:
```
CREATE TABLE default.test_merge AS default.test_distributed_v1
ENGINE = Merge (default, '^ test_distributed_v');
```

The same SELECT to the table test_distributed_v1 is **OK**:
```
SELECT
    time_local
    response_code,
    'a' AS log_type
FROM test_distributed_v1
LIMIT 1
┌──────────time_local─┬─response_code─┬─log_type─┐
│ 2019-10-31 07:00:05 │ 200 │ a │
└ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ └ └ ─ └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ 
```

Is this a bug or request format has changed?

**Comment by alexey-milovidov** [comment]
@KochetovNicolai It looks like the Merge table is created on top of Distributed tables, and one of the shards of Distributed table is local; and constants are materialized for remote shards but not for local shards?

**Comment by KochetovNicolai** [comment]
Indeed. We need to properly calculate common header for streams.

**Comment by MakarovYaroslav** [comment]
Are there any changes?

**Comment by KochetovNicolai** [comment]
Closed as duplicate was closed too.
