### ISSUE TITLE
Calculation of TTL for old data parts on ALTER.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#8167]
**Use case**
Otherwise old data won't be cleared when you do ALTER ... TTL.

**Comment by CurtizJ** [comment]
I suggest to make this functionality optional and implement it via mutations.

**Comment by alexey-milovidov** [comment]
That's ok.

**Comment by qoega** [comment]
ALTER ... MATERIALIZE TTL is implemented.

**Comment by alexey-milovidov** [comment]
@CurtizJ mentioned that TTL will be calculated for old parts automatically when adding TTLs, but I forget if this is already implemented or not.

**Comment by CurtizJ** [comment]
No, automatical run `ALTER ... MATERIALIZE TTL` for `ALTER ... MODIFY TTL` is not implemented yet. But now it's easy to do.

**Comment by alexey-milovidov** [comment]
@CurtizJ I don't remember whether it was fixed.

**Comment by CurtizJ** [comment]
It was fixed in #11042.
