### ISSUE TITLE
Allow alias left_table.col_name as col_name in queries with join

### ISSUE THREAD

**Issue by vincenzon** [ClickHouse/ClickHouse#8169]
I have a query of the form:

```
select t1.c1 as c1
from t1
any left join t2 on t1.c1 = t2.c1
```
and I am getting an error "column 'c1' is ambiguous". If I change the query to (say):

```
select t1.c1 as cc11
from t1
any left join t2 on t1.c1 = t2.c1
```

it works. The actual query is really a multiple join with more than just the one column but it seems that the error arises from the use of "as c1" when the two tables are joined using column c1. I do not see this error running against a server running version 19.13.1.11 but I do running against version 19.17.5.18. Did the interpretation of aliases change? Thanks for your help.

**Comment by 4ertus2** [comment]
Yes, we added a check for columns with same names cause there're some queries with wrong column selection in this case. For now it throws an error if it's not sure what column to select: from the first table or from the second one.

In particular in your query implementation needs to crop `t1.c1` into `c1` then it decided that the query already has `c1` as an alias (and it should prefer the alias after crop). It does not check that `c1` is just an alias for `t1.c1` (and crop makes no sense) so it throws cause it has to make a new `c1` but it can't.

**Comment by vincenzon** [comment]
@4ertus2,

Thanks for the quick response. Based on your response  and testing I see that:

```
select t1.c1
from t1 
left any join t2 on t1.c1 = t2.c1
```

works as expected. As it happens the queries in question are program generated so I can add a condition to do the check in my code. I see you did some retagging of this issue so I'm not sure I should close it or not, for me it's closed. Thanks again.

**Comment by vincenzon** [comment]
Well actually ...

I'm discovering this to be more troubling than I thought. In my constructions I have:
```
select c1 
from (
   select t1.c1  -- Breaking code was:  t1.c1 as c1
   from t1 
   any left join t2 on t1.c1 = t2.c1
)
```

So now with the change from `t1.c1 as c1` to `t1.c1` the outer select fails. I'm going to see if I can later the query generator to account for this change but I think this change breaks this useful construct. 

Would the relevant change be easy to undo if we were to opt to maintain a private branch?

In which version was the change made in case we just want to freeze our version for a time? 

Thanks for the help.

**Comment by vincenzon** [comment]
Well actually actually ...

It looks like the behaviour changes depending on whether the join is a single join or a multiple join.

This:

```
select t1.c1
from t1
left join t2 on t1.c1 = t2.c1
```
returns a column labelled "c1". However,

```
select t1.c1
from t1
left join t2 on t1.c1 = t2.c1
left join t3 on t2.c2 = t3.c2
```
returns a column labelled "t1.c1". This seems inconsistent to me and unnecessarily complicated to code around.

**Comment by vincenzon** [comment]
Here is a minimal reproducing example:

```
drop table if exists t1;
create table t1 (c1 String) ENGINE = Memory;
insert into t1 values ('A1');

drop table if exists t2;
create table t2 (c1 String, c2 String) ENGINE = Memory;
insert into t2 values ('A2', 'A3');

drop table if exists t3;
create table t3 (c2 String, c3 String) ENGINE = Memory;
insert into t3 values ('A3', 'A4');

select t1.c1 
from t1 
left join t2 on t1.c1 = t2.c1;

select t1.c1
from t1
left join t2 on t1.c1 = t2.c1
left join t3 on t2.c2 = t3.c2;
```
The output of the first select call is:

```
SELECT t1.c1
FROM t1
LEFT JOIN t2 ON t1.c1 = t2.c1

┌─c1─┐
│ A1 │
└────┘
```

and the second is:

```
SELECT t1.c1
FROM t1
LEFT JOIN t2 ON t1.c1 = t2.c1
LEFT JOIN t3 ON t2.c2 = t3.c2

┌─t1.c1─┐
│ A1    │
└───────┘
```

**Comment by 4ertus2** [comment]
> returns a column labelled "t1.c1". This seems inconsistent to me and unnecessarily complicated to code around.

It's not good but expected. Aliases are used to implement multiple join logic: first join would be rewritten with aliases and wrapped into subselect. For single query logic you'll get first table unqualified, for multiple joins - the last table would be unqualified.
It's possible to make them consistent but it could change one day. There're no guaranties here for now.

**Comment by 4ertus2** [comment]
> So now with the change from t1.c1 as c1 to t1.c1 the outer select fails.

I cannot reproduce. This code works.

`
drop table if exists t1;
drop table if exists t2;

create table t1 (c1 UInt8) Engine = Memory;
create table t2 (c1 UInt8) Engine = Memory;

select c1
from (
   select t1.c1
   from t1
   any left join t2 on t1.c1 = t2.c1
);

drop table t1;
drop table t2;
`

**Comment by vincenzon** [comment]
Sorry, I'm not a saying the queries don't work. I'm saying the resulting column labels are inconsistent. In the single join case the table prefix is dropped (c1 not t1.c1). In the double join case it is not (t1.c1 not c1). I don't have a preference for either (though if I did I'd expect to be able to enforce it using an alias). It's the inconsistency that I am having to code around.

**Comment by 4ertus2** [comment]
You may add an alias to subquery and acess via it. Doesn't it help?

```
select s1.c1
from (
   select t1.c1
   from t1
   any left join t2 on t1.c1 = t2.c1
) s1;
```

**Comment by 4ertus2** [comment]
OK. Reproduced. It's not possible to access t1.c1 via c1.

```
select c1
from (
   select t1.c1 as c1
   from t1
   any left join t2 on t1.c1 = t2.c1
   any left join t3 on t1.c1 = t3.c1
);
```

If there's no alias it sayes

```
Missing columns: 'c1' while processing query: 'SELECT c1 FROM (SELECT `--t1.c1` AS `t1.c1` FROM (SELECT * FROM t1 ANY LEFT JOIN t2 ON `--t1.c1` = `--t2.c1`) ANY LEFT JOIN t3 ON `--t1.c1` = t3.c1) AS s1', required columns: 'c1', source columns: 't1.c1'.
```

If the alias is present

```
Column 'c1' is ambiguous.
```

**Comment by vincenzon** [comment]
Right, that's the problem. I thought your table aliasing trick might subvert it and magically work but no luck. I've added the code to our query generator to check if the join is single or multiple and adapted the generated query to account for the difference. It just seems like a bit of a hack, but it definitely works.

**Comment by 4ertus2** [comment]
It's should be quite simple to make last table in multiple joins qualified too here:
https://github.com/ClickHouse/ClickHouse/blob/master/dbms/src/Interpreters/JoinToSubqueryTransformVisitor.cpp#L157

It may help I think.
