### ISSUE TITLE
Default database is used when creating distributed table

### ISSUE THREAD

**Issue by morigs** [ClickHouse/ClickHouse#8170]
When creating distributed table current database ignored in `as` clause. Also `currentDatabase()` returns `default` inside engine parameters.

For example:

```sql
use my_db;
create table if not exists spans_distributed on cluster '{cluster}' as spans
    engine = Distributed(`{cluster}`, currentDatabase(), spans, rand());
```

Returns error `Table default.spans doesn't exist.` But 

```sql
use my_db;
create table if not exists spans_distributed on cluster '{cluster}' as `my_db`.spans
    engine = Distributed(`{cluster}`, currentDatabase(), spans, rand());
```

works well. Even though... If I specify database explicitly in `as` clause table will be created, but won't work:

```sql
select * from spans_distributed;
```

`There is no table default.spans on server`

That may be only if `currentDatabase()` returns `default` in engine parameters.

**Deployment:** YC Managed service for ClickHouse
**Version**: 19.14.7.15
**Interface:** JDBC (DataGrip). Same for YC console

**Expected behavior**
May this is expected behavior but it's unclear and may be should be documented somewhere.

**Comment by filimonov** [comment]
Sounds familiar:  #6104

**Comment by morigs** [comment]
Yes, it seems this is delicate.
I'll leave comment about `as` alias in #6104 and I believe we can close this issue as a duplicate
