### ISSUE TITLE
[Kafka Engine] Method write is not supported by storage View

### ISSUE THREAD

**Issue by mobydi** [ClickHouse/ClickHouse#8174]
Updated from version 14 to 19.16.2.2 and now having a lot of exceptions: 
Could you add extra details to it? I would have MV name or Table name.

2019.12.12 14:10:02.794253 [ 36 ] {} <Error> void DB::StorageKafka::threadFunc(): Code: 48, e.displayText() = DB::Exception: Method write is not supported by storage View, Stack trace:

0. 0x559a47da77b0 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x559a47da7585 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x559a47a8abe8 DB::IStorage::write(std::shared_ptr<DB::IAST> const&, DB::Context const&) /usr/bin/clickhouse
3. 0x559a4b729631 DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool) /usr/bin/clickhouse
4. 0x559a4b100501 DB::InterpreterInsertQuery::execute() /usr/bin/clickhouse
5. 0x559a4b729a3e DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool) /usr/bin/clickhouse
6. 0x559a4b100501 DB::InterpreterInsertQuery::execute() /usr/bin/clickhouse
7. 0x559a4b66d952 DB::StorageKafka::streamToViews() /usr/bin/clickhouse
8. 0x559a4b66e511 DB::StorageKafka::threadFunc() /usr/bin/clickhouse
9. 0x559a4b680009 DB::BackgroundSchedulePoolTaskInfo::execute() /usr/bin/clickhouse
10. 0x559a4b68094a DB::BackgroundSchedulePool::threadFunction() /usr/bin/clickhouse
11. 0x559a4b6809ca ? /usr/bin/clickhouse
12. 0x559a47df1d5c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
13. 0x559a4db0f1e0 ? /usr/bin/clickhouse
14. 0x7ff0cd749dd5 start_thread /usr/lib64/libpthread-2.17.so
15. 0x7ff0cd066ead clone /usr/lib64/libc-2.17.so
 (version 19.16.2.2 (official build))

**Comment by filimonov** [comment]
Do you try to copy the data from Kafka to usual (non materialized) view? Can you show the structure of your tables?

**Comment by filimonov** [comment]
To find more details you can try to follow back log by the thread id `[ 36 ]`

**Comment by blinkov** [comment]
@mobydi, do you have any further questions?
