### ISSUE TITLE
Attach all detached partitions

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#8183]
Is there a way to attach all detached partitions?

Something like:

`ALTER TABLE table1 ATTACH PARTITION <all_expr>`

Thanks!

(tried `ALTER TABLE table1 ATTACH PARTITION 1=1` but nope 😄  )

**Comment by den-crane** [comment]
No.

I use

```
cd detached
let i=1;for f in `ls -1` ; do echo $i $f;((i++)); echo "alter table T attach part '$f';"|clickhouse-client ;sleep 1; done

```

**Comment by filimonov** [comment]
But actually it can be quite useful, especially during migration from MergeTree to Replicated.
Let's change it to feature request.

**Comment by simPod** [comment]
Perfect! Thanks for the command btw, will use it right now meanwhile.

**Comment by filimonov** [comment]
```
clickhouse-client --format=TSVRaw -q"select 'ALTER TABLE ' || database || '.' || table || ' ATTACH PARTITION ID \'' || partition_id || '\';\n' from system.detached_parts group by database, table, partition_id order by database, table, partition_id;" | clickhouse-client -mn
```

**Comment by alexey-milovidov** [comment]
@den-crane Attaching parts one by one will lead to data duplication if there are old parts after merge along with merged parts. I don't recommend ATTACH PART in a loop.

@filimonov This is way better!

**Comment by alexey-milovidov** [comment]
@filimonov Though your script is technically incorrect because it doesn't escape names properly.

**Comment by simPod** [comment]
Do you plan to somehow make this operation easier on ClickHouse side?

**Comment by mikhno-s** [comment]
A slightly fixed command which attaches all detached partitions :
```
clickhouse-client --format=TSVRaw -q"select 'ALTER TABLE ' || database || '.' || table || ' ATTACH PARTITION '|| partition_id ||' ;\n' from system.detached_parts group by database, table, partition_id order by database, table, partition_id;"  | clickhouse-client -mn
```
Also, I use this one to attach parts from non-replicated table to replicated one:
```
clickhouse-client --format=TSVRaw -q"select 'ALTER TABLE <database_name>.<replicated_table_name> ATTACH PARTITION  '|| partition ||' ;\n' from system.parts where table = 'non_replicated_table_name' group by partition" | clickhouse-client -mn
```
