### ISSUE TITLE
Index does not seem to get used with today() function in Where clause

### ISSUE THREAD

**Issue by olegkv** [ClickHouse/ClickHouse#8191]
Not sure if it is a bug or expected behavior.
If I use literal as a filter, index is used. If I use today() function, index is not used.
That does not seem ok, because the result of today() is expected to be constant for query duration.

Sample query is below. Both selects are expected to scan 100k rows, but the second one scans 200k rows instead.

create table test_index (id String, dt DateTime) 
ENGINE = MergeTree()
PARTITION BY toYYYYMM(dt)
ORDER BY (id, dt)
SETTINGS index_granularity=8192
;
insert into test_index (id, dt) select '1', today() from system.numbers limit 100000
;
insert into test_index (id, dt) select '1', today()-1 from system.numbers limit 100000
;
select count() from test_index where id = '1' and dt >= '2019-12-12 00:00:00'
;
select count() from test_index where id = '1' and dt >= today()
;
drop table test_index

**Comment by filimonov** [comment]
Date vs DateTime. 

Try: 
```
 select count() from test_index where id = '1' and dt >= toDateTime(today())
```

**Comment by olegkv** [comment]
toDateTime() solves it, thanks!
Wondering, if implicit conversion from Date to DateTime is done by CH, what does it lose during conversion so that index is not used anymore..

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/6287

**Comment by olegkv** [comment]
Thanks again! :)
