### ISSUE TITLE
Non-nested column with dot in name

### ISSUE THREAD

**Issue by geoffrank** [ClickHouse/ClickHouse#8193]
When multiple columns have names containing a '.', sharing the same prefix before the '.', and one of the columns is an array, then an insert that sets the array but not the other columns fails.

```
CREATE TABLE test (id UInt32, `prefix.id` UInt32, `prefix.arr` Array(String)) ENGINE = Memory()
INSERT INTO test (id) VALUES (1)
INSERT INTO test (id, prefix.arr) VALUES (2, [])
INSERT INTO test (id, prefix.arr) VALUES (3, ['a', 'b'])
INSERT INTO test (id, prefix.id, prefix.arr) VALUES (4, 4, [])
INSERT INTO test (id, prefix.id, prefix.arr) VALUES (5, 5, ['a', 'b'])
SELECT * FROM test
```
The 2nd and 3rd inserts fail with the error
```
Code: 368. DB::Exception: Received from localhost:9000. DB::Exception: Bad cast from type DB::DataTypeNumber<unsigned int> to DB::DataTypeArray.
```
The first type in the error depends on the type of the `prefix.id` column.

I'm guessing the default value of the `prefix.id` column is being cast to an array because of some side effect of the Nested data type logic. I do not want to use a Nested data type here. `prefix.id` is a single int per row and `prefix.arr` is a single array of strings per row. Their names contain '.' because it matches the schema of the system that inserts into and queries clickhouse.

Are non-Nested column names containing one or more '.' supported?

Tested on 19.17.5.18 from the http://repo.yandex.ru/clickhouse/deb/stable repo running on Ubuntu 18.04.3

**Comment by filimonov** [comment]
Indeed it is related to the Nested logic. 
I think the simpliest option would be just to use some other column naming schema.

**Comment by blinkov** [comment]
@geoffrank, do you have any further questions?

**Comment by geoffrank** [comment]
No, thanks. I've switched to using underscores instead of dots in column names for non-nested columns.
