### ISSUE TITLE
Replicated JOIN alternative?

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#8195]
Today I started migrating all tables to ReplicatedMerge engines.

I was wondering what to do with tables using JOIN engine as there's no ReplicatedJoin engine.

Is the only solution to create the same JOIN table in each replica and insert data to all replicas? Thanks!

**Comment by filimonov** [comment]
Right now - yes. You can create a distributed table above with special cluster configuration with internal_replication=false to fill 2 (or more) Engine=Join tables simultaniously.

**Comment by filimonov** [comment]
Also https://github.com/ClickHouse/ClickHouse/issues/7906

**Comment by simPod** [comment]
Will try, thanks! 

The linked RFC is IMO the way to go from here so perhaps can close? I just wonder whether the RFC is only about Distributed variant and not the Replicated one?

**Comment by filimonov** [comment]
> I just wonder whether the RFC Distributed variant and not the Replicated one?

It's just RFC, very unconcrete for now. But sounds like replicated needed too.
