### ISSUE TITLE
ALTER DICTIONARY support

### ISSUE THREAD

**Issue by alesapin** [ClickHouse/ClickHouse#8205]
Need to implement support of `ALTER DICTIONARY` queries for external dictionaries:
1) Attributes
2) Primary key
3) Layout
4) Source
5) Lifetime
6) Range for range_hashed dictionaries

**Comment by alexey-milovidov** [comment]
Maybe better to allow just `REPLACE DICTIONARY` query?

Support for all possible properties to ALTER will be too cumbersome.

**Comment by alesapin** [comment]
It can be implemented much faster and also seems useful!

**Comment by filimonov** [comment]
ALTER DICTIONARY SOURCE w/o dictionary recreation is needed for password rotation (may replace would be ok too)

**Comment by Strate** [comment]
Would be very great to implement altering of lifetime - to temporary pause dictionary refreshing without penalty of re-creation new dictionary
