### ISSUE TITLE
New Engine - *Replacing(Eventual)ConsistentMergeTree

### ISSUE THREAD

**Issue by krnaveen14** [ClickHouse/ClickHouse#8223]
**Use case**
We have tables with columns each ranging from 150 - 300. At most, only 20 - 30 random columns of each tables are used in the queries. Running those queries in PostgreSQL takes a pretty big performance / IO hit due to wide row size. Running the same in Clickhouse with tens of joins (15-20) is very much performant than PostgreSQL. But we are worried about the strategies involved to handle updates in Clickhouse.

- RepalcingMergeTree
  - Needs user query to be designed in such a way that it can handle / accept duplicates
  - Needs to run OPTIMIZE TABLE / include FINAL in SELECT query to have unique data automatically without special handling
- CollapsingMergeTree
  - Needs user queries to include aggregate functions which might pollute / complicate the query
  - Messing up with negate entries will make the results incorrect
  - Need to know the exact values of previous entry (which is expensive against clickhouse)
- VersionedCollapsingMergeTree
  - Same as CollapsingMergeTree

In one way or other either the user needs to handle it in SQL / use the negating entry and aggregate function strategy. There is no straightforward approach for tables with updating rows (updated row is inserted instead of ALTER UPDATE mutation)

**Describe the solution you'd like**
- No need for special handling in user queries (handling duplicates / using aggregate functions with sign)
- No need for negating entries

***Proposed Solution***
- Accept the user inserts (ReplacingEventualConsistentMergeTree)
  - Don't use the unmerged data for select queries until the actual merges / deduplication happens
- Accepts the user inserts with a version column (ReplacingConsistentMergeTree) (I would prefer this)
  - Regardless of merged / unmerged data, older versions are eliminated and uses only the newer version of row with same primary key in the queries.
  - Similar to PostgreSQL MVCC Architecture
  - Data Deduplication can happen in the background. Since there is no need for merges to finish for having unique data in queries, we could ease the merging threshold for this table.
  - Even we could have table engine with no deduplication features (configurable) as it might be acceptable for user to have the duplicate data in storage but the queries always use the latest version of rows.

**Describe alternatives you've considered**
Considered Replacing/CollapsingMergeTree but both have the pitfalls I've described. Even using OPTIMIZE without FINAL eagerly has pretty big IO hit comparing with lazy background merges.

**Additional context**

**Comment by den-crane** [comment]
the same as https://github.com/ClickHouse/ClickHouse/issues/5125

>Don't use the unmerged data for select queries until the actual merges / deduplication happens

![image](https://user-images.githubusercontent.com/19737682/70874412-65135300-1f88-11ea-8091-234abd4628e1.png)

**Comment by krnaveen14** [comment]
@den-crane Going through the Feature request you've mentioned, it seems that it is stale right now.

I was thinking that second proposed solution might be straightforward approach. Probably by always sorting the data blocks by primary key (after predicate pushdown) and removing the older version of rows while doing that, then running the actual query. There might be more thinking needed for implementation, it's just a high level approach.

Yes I understand ClickHouse currently supports relatime updates indirectly

**Comment by den-crane** [comment]
>I was thinking that second proposed solution might be straightforward approach. 

Isn't it the same as FINAL? `select ... from table FINAL` ?

**Comment by krnaveen14** [comment]
> Isn't it the same as FINAL? `select ... from table FINAL` ?

Yes it's. But usage of FINAL limits the query being single threaded. I've tested it with our dataset and found the performance hit to be pretty huge.

One thing I realised right now is, the limitation of single threaded which we have in FINAL usage might also apply when we design for the proposed / improved solutions. But essentially the inner working of FINAL and proposed ENGINE should be completely different for different trade-offs.

- FINAL is simply applying the pending merges and deduplictions on that table before actual query run. This is also the reason why it's limited to single threaded as it might be inconsistent if merging / deduplication happens concurrently.
- Proposed ENGINE is completely different by transparently using the latest version of rows
  - Without the need to internally run the pending merges / deduplications.
  - Similar to how PostgreSQL automatically eliminates the dead rows and using only the latest version of rows in queries.
  - Even we could have the ENGINE to enable / disable the deduplication based on table config
  - Deduplication ENABLED - similar to how ReplacingMergeTree works
  - Deduplication DISABLED - Table simply becomes a append only table, no need to remove the older versions. But append only is simply impractical due to performing re-ordering of rows by primary key in older and newer parts? Anyway, I guess you get my point.

These are all just some propositions and ideas which pops up right now. If we could have an ENGINE which handles the Duplicate records transparently, then I think it'll be huge benefit to all and ease the usage.

**Comment by den-crane** [comment]
I am not sure why `select final` is single threaded. Probably several threads processes own set of parts. The same key happens in different parts. Threads don't see keys in other threads.

IMHO: PostgreSQL MVCC, and other ideas they just don't fit into the paradigm of MergeTree / immutable parts.

**Comment by krnaveen14** [comment]
I understand this is not something which is possible with MergeTree. That's why we are having this thread right now.

Just like how ReplacingMergeTree and *CollapsingMergeTree have come up based on the use cases, we need to look it from a different perspective rather than in a fixed perspective of it doesn't suit the current design / implementations. That's why I propose to design a new Table Engine based on the use cases (which can be discussed extensively).

This is not something which can be implemented in a matter days, it might take some time and more to get into stable phase. Every software has its own existing architecture and evolution plan. If something different comes up conflicting with the existing design, we should not eliminate it right away. Rather we should try to understand the actual needs and how it might benefit the users.

**Comment by den-crane** [comment]
@krnaveen14 my opinion is not relevant. I am just a member of a CH community. I just wondered.

**Comment by filimonov** [comment]
> > Isn't it the same as FINAL? `select ... from table FINAL` ?
> 
> On the query output, yes it's. But usage of FINAL limits the query being single threaded.


https://github.com/ClickHouse/ClickHouse/pull/10463

**Comment by filimonov** [comment]
In general: in common case data does not land in a single part/partition. 

If your part has already a size of 150Gb it will never be merged currently (and it would be too heavy operation to merge 150Gb part with every incoming block). 

So the proposed solution can work in some very special use cases (with small data sized, unpartitioned, or partitioned by prefix of primary key).

**Comment by filimonov** [comment]
Closing that since the story/concept can't work for the general case, and the use case is actually about deduplication, so let's use #5125 to track that.
