### ISSUE TITLE
Way to force Buffer flush

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#8226]
When using a Buffer engine, there's not way to force flush it. This would be eg. useful in integration tests when testing write read to the target table through buffer tho.

```
Start test
-----
Execute some logic that triggers data insertion -> table A (Buffer) ->  table B (MergeTree)
Force flush table A
Execute some logic that reads from table B 
Assertions
-----
End test
```

Imagine a test that inserts one row into table A but the table will flush after reaching a max condition that is threshold of `100s`. That test now needs to run for 100s at least.

```sql
CREATE TABLE IF NOT EXISTS tableA AS tableB
ENGINE = Buffer(
    default,
    tableB,
    16,
    10,
    100,
    1,
    10000,
    1,
    10000000
)
```

**Comment by alexey-milovidov** [comment]
OPTIMIZE query should flush the Buffer table.

**Comment by simPod** [comment]
Works, thanks!
