### ISSUE TITLE
how deal with detached dictionary 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#8227]
how to  reduce  detached dictionary 

 CREATE TABLE my_sdap.dm_user_behavior_events (`dt` UInt32, `user_id` UInt32, `event_time` DateTime CODEC(DoubleDelta, LZ4), `event_month` UInt32 MATERIALIZED toYYYYMM(event_time),  ....) ENGINE = ReplicatedMergeTree('/clickhouse/tables/my_sdap/dm_user_behavior_events/{shard}', '{replica}') PARTITION BY event_dt ORDER BY (client_id, event_id, mode, dt, intHash64(user_id)) SAMPLE BY intHash64(user_id) TTL event_time + toIntervalDay(30) SETTINGS index_granularity = 8192 

<img width="388" alt="微信截图_20191216143132" src="https://user-images.githubusercontent.com/24770345/70884362-cd0d7c00-2010-11ea-83af-feac99df3b2e.png">

**Comment by onine007** [comment]
there are some dictionaries which  start with  broken_ ,ignored_   like ignored_20191203_902_907_1_908  and broken_20191022_17_17_0_try1      in  detached dictionary

**Comment by alesapin** [comment]
Seems like you dealing with tables, not dictionaries? Directories in `detached` directory called parts (parts of your table). If they start with `ignored_` or `broken_` and you sure, that all data is present in your table then you can remove them manually (`rm -r`) or use `DROP DETACHED` query https://clickhouse.yandex/docs/en/query_language/alter/#alter_drop-detached.

**Comment by onine007** [comment]
@alesapin thank you.
