### ISSUE TITLE
mysql connection in clickhouse

### ISSUE THREAD

**Issue by ashkank66** [ClickHouse/ClickHouse#8228]
I'm using clickhouse for a while now. I have inserted 1 million records so far and I intend to add to it to about 100 billion. It's blazing fast, and I like how it compresses data. 

The problem is that it keeps throwing an error every now and then, for example when I just login to clickhouse client:

Cannot load data for command line suggestions: Code: 1000, e.displayText() = DB::Exception: Received from localhost:9000. DB::Exception: mysqlxx::ConnectionFailed: Unknown MySQL server host 'host' (-2) ((nullptr):0). (version 19.17.5.18 (official build))

For doing ordinary tasks it seems to not affect the performance, but the main problem is that when I want to get partitions using command:

`SELECT partition FROM system.parts WHERE table='bars'`

again it throws the same exception. I went through the documentation, but I couldn't find a solution.

Any help would be appreciated...

PS: I used: Engine = MergeTree() Partition by isin Order by time primary key time

**Comment by KochetovNicolai** [comment]
It probably means that you have table with `MySQL` engine which can't connect to MySQL.
It also strange that we have `nullptr` in error message. May be a misconfiguration. 

Can you please check that all you MySQL configurations are correct?
And also find full stacktrace after this error in logs?

**Comment by alexey-milovidov** [comment]
> Unknown MySQL server host 'host' (-2) ((nullptr):0)

Probably you have specified `host` as hostname for MySQL server, like this:
`<host>host</host>`

The `(nullptr):0` part is Ok - it's what we have as the error message from the library.

**Comment by ashkank66** [comment]
I actually haven't configured MySQL on my clickhouse, and to be honest, I have to admit I tried to find a configuration for MySQL but I couldn't.
Could you tell me where should I configure it?

**Comment by ashkank66** [comment]
2019.12.17 10:46:30.000314 [ 44 ] {} <Information> Application: MYSQL: Connecting to database@host:0 as user user
2019.12.17 10:46:30.001630 [ 44 ] {} <Error> Application: mysqlxx::ConnectionFailed
2019.12.17 10:46:30.001943 [ 44 ] {} <Error> void DB::AsynchronousMetrics::run(): Poco::Exception. Code: 1000, e.code() = 2005, e.displayText() = mysqlxx::ConnectionFailed: Unknown MySQL server host 'host' (-2) ((nullptr):0) (version 19.17.5.18 (official build)

**Comment by alexey-milovidov** [comment]
It looks like you have configured MySQL table actually.

```
grep -r -i mysql /etc/clickhouse-server/
grep -i mysql /etc/metrika.xml
grep -r -i mysql /var/lib/clickhouse/
```

**Comment by ashkank66** [comment]
This is all the responses:

root@ashkanPC:/home/ashkan# grep -r -i mysql /etc/clickhouse-server/
/etc/clickhouse-server/users.xml:                 Restrictions of SHA256: impossibility to connect to ClickHouse using MySQL JS client (as of July 2019).
root@ashkanPC:/home/ashkan# grep -i mysql /etc/metrika.xml
grep: /etc/metrika.xml: No such file or directory
root@ashkanPC:/home/ashkan# grep -r -i mysql /var/lib/clickhouse/
/var/lib/clickhouse/preprocessed_configs/users.xml:                 Restrictions of SHA256: impossibility to connect to ClickHouse using MySQL JS client (as of July 2019).
/var/lib/clickhouse/preprocessed_configs/mysql_dictionary.xml:       /etc/clickhouse-server/mysql_dictionary.xml      -->
/var/lib/clickhouse/preprocessed_configs/mysql_dictionary.xml:    <comment>This dictionary is set to connect clickhouse to mysql</comment>
/var/lib/clickhouse/preprocessed_configs/mysql_dictionary.xml:	  <mysql>
/var/lib/clickhouse/preprocessed_configs/mysql_dictionary.xml:	  </mysql>
/var/lib/clickhouse/metadata/db_name.sql:ENGINE = MySQL('host:port', 'database', 'user', 'password')

**Comment by ashkank66** [comment]
I created a file mysql_dictionary in hope of getting rid of the error, but no proper result, so I deleted it later

**Comment by KochetovNicolai** [comment]
> /var/lib/clickhouse/metadata/db_name.sql:ENGINE = MySQL('host:port', 'database', 'user', 'password')

That means that you have `MySQL` database with name `db_name`, which has incorrect configuration (instead of `'host:port', 'database', 'user', 'password'` must be real values). And this database can't connect to MySql server.

You can just run `DROP DATABASE db_name` to remove it.

**Comment by ashkank66** [comment]
That's right, thank you.
