### ISSUE TITLE
Live View doesn't support Distributed engine 

### ISSUE THREAD

**Issue by jackpgao** [ClickHouse/ClickHouse#8245]
- `create LIVE VIEW lv as select ..... from distributed_tb`
- When running `select * from lv` , it will throw such error `DB::Exception: Distributed on Distributed is not supported`

**Comment by alex-zaitsev** [comment]
Live View currently does not support distributed tables. The error message is misleading.

**Comment by jackpgao** [comment]
It will be much more powerful if it does.

**Comment by alex-zaitsev** [comment]
Yes, we know. Stay tuned.

**Comment by amadrizwan** [comment]
Any news on this feature? This severely limits the use of live views in a replicated and sharded environment.
