### ISSUE TITLE
comments in a select query lead to the error

### ISSUE THREAD

**Issue by anna-afanasenko** [ClickHouse/ClickHouse#8257]
Any comments in the end of the select query to distributed view lead to the error:
SQL Error [1002]: ClickHouse exception, code: 1002

example:
`select * from default.campaign_txn_add  --some random comment`
SQL Error [1002]: ClickHouse exception, code: 1002, host: 192.168.235.119, port: 8123; null

`select * from default.campaign_txn_add ` - this works fine

This error is reproduced with any distributed table.

DDL:
```
CREATE TABLE default.campaign_txn_add (
...
) ENGINE = Distributed(clickhouse_cluster, default, campaign_txn_add_local, promotion_id)
```

clickhouse version:19.4.0
dbeaver Version 6.2.2.201910072100

BTW:
select count(1) from default.campaign_txn_add  /* some comments*/  
-this works ok

and in the clickhouse-client there is no problem at all

**Comment by den-crane** [comment]
```
curl 'http://localhost:8123/?query=select%201%20--hahah'
1
```
JDBC driver issue https://github.com/ClickHouse/clickhouse-jdbc/issues/208

**Comment by den-crane** [comment]
fixed https://github.com/ClickHouse/clickhouse-jdbc/pull/421 https://github.com/ClickHouse/clickhouse-jdbc/issues/208
