### ISSUE TITLE
wrong result with set enable_optimize_predicate_expression=true 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#8263]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use

19.15.4.10

* Which interface to use, if matters
* Non-default settings, if any

set enable_optimize_predicate_expression=true ;

* `CREATE TABLE` statements for all tables involved

CREATE TABLE my_sdap.dm_user_behavior_events (`dt` UInt32, `user_id` UInt32, `event_time` DateTime CODEC(DoubleDelta, LZ4), `event_month` UInt32 MATERIALIZED toYYYYMM(event_time), `event_week_begin` UInt32 MATERIALIZED toYYYYMMDD(toMonday(event_time)), `event_dt` UInt32 MATERIALIZED toYYYYMMDD(event_time), `event_hh` UInt8 MATERIALIZED toHour(event_time), `event_mi` UInt8 MATERIALIZED CAST(formatDateTime(event_time, '%M'), 'UInt8'), `event_id` UInt32, `client_platform` UInt8, `client_id` UInt8, `client_ver` Nullable(String) ...  , `mode` UInt8) ENGINE = ReplicatedMergeTree('/clickhouse/tables/my_sdap/dm_user_behavior_events/{shard}', '{replica}') PARTITION BY event_dt ORDER BY (client_id, event_id, mode, dt, intHash64(user_id)) SAMPLE BY intHash64(user_id) TTL event_time + toIntervalDay(30) SETTINGS index_granularity = 8192

CREATE TABLE my_sdap.events on cluster perftest_3shards_2replicas AS my_sdap.dm_user_behavior_events   ENGINE = Distributed( perftest_3shards_2replicas , my_sdap, dm_user_behavior_events, intHash64(user_id)) ;  

* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

SELECT
	toString(event_id) AS event_id,
	events_video_from,
	events_video_position,
	toFloat64OrZero(toString(count())) AS measure
FROM
	(
	SELECT
		event_id,
		events.video_from AS events_video_from,
		events.video_position AS events_video_position
	FROM
		(
		select
			*,
			event_id
		from
			(
			select
				event_id,
				event_dt,
				event_dt,
				client_id,
				event_attr12 AS video_from,
				event_attr2 AS video_position,
				mode,
				business_type_alias AS business_type_alias,
				info_type_alias AS info_type_alias,
				event_attr13 AS from_table,
				user_id
			from
				events
			where
				event_id = 52
				and ( (toInt32OrNull(events.event_attr3) in ( 1,
				3,
				4,
				5,
				8,
				9 ))
				and (toFloat32OrNull(events.event_attr6) >= 5 )
				and (events.info_type_alias in ( 2,
				3 ))
				and (events.business_type_alias in (2))
				and (toInt32OrNull(events.event_attr2) = 15 )
				and (events.event_attr1 in ( 'PregnancyTab',
				'HomeMotherTab',
				'ZiXxunTab' ))
				and (toInt32OrNull(events.event_attr12) in ( 1,
				8,
				9 )) )
				and ( ( events.event_dt >= 20191215
				and events.event_dt <= 20191215
				and events.client_id = 1 ) ) ) ) AS events
	WHERE
		**events.event_dt = 20191215
		and events.event_dt <= 20191215
		and events.client_id = 1
		AND** events.mode in (0)
		and events.business_type_alias in (2)
		and events.info_type_alias in (2)
		and toInt32OrNull(events.from_table) in ( 1,2 )
)
GROUP BY
	event_id,
	events_video_from,
	events_video_position
ORDER BY
	event_id,
	measure desc
LIMIT 200 BY event_id

(result is wrong )
52	9	15	412
52		15	123

when  set enable_optimize_predicate_expression=false ;

then  result is  correct : 
52	9	15	381

 and  query :  SELECT
	toString(event_id) AS event_id,
	events_video_from,
	events_video_position,
	toFloat64OrZero(toString(count())) AS measure
FROM
	(
	SELECT
		event_id,
		events.video_from AS events_video_from,
		events.video_position AS events_video_position
	FROM
		(
		select
			*,
			event_id
		from
			(
			select
				event_id,
				event_dt,
				event_dt,
				client_id,
				event_attr12 AS video_from,
				event_attr2 AS video_position,
				mode,
				business_type_alias AS business_type_alias,
				info_type_alias AS info_type_alias,
				event_attr13 AS from_table,
				user_id
			from
				events
			where
				event_id = 52
				and ( (toInt32OrNull(events.event_attr3) in ( 1,
				3,
				4,
				5,
				8,
				9 ))
				and (toFloat32OrNull(events.event_attr6) >= 5 )
				and (events.info_type_alias in ( 2,
				3 ))
				and (events.business_type_alias in (2))
				and (toInt32OrNull(events.event_attr2) = 15 )
				and (events.event_attr1 in ( 'PregnancyTab',
				'HomeMotherTab',
				'ZiXxunTab' ))
				and (toInt32OrNull(events.event_attr12) in ( 1,
				8,
				9 )) )
				and ( ( events.event_dt >= 20191215
				and events.event_dt <= 20191215
				and events.client_id = 1 ) ) ) ) AS events
	WHERE
		 events.mode in (0)
		and events.business_type_alias in (2)
		and events.info_type_alias in (2)
		and toInt32OrNull(events.from_table) in ( 1,2 )
)
GROUP BY
	event_id,
	events_video_from,
	events_video_position
ORDER BY
	event_id,
	measure desc
LIMIT 200 BY event_id

has the same result (correct ) : 
52	9	15	381

**Expected behavior**

then  result is  correct : 
52	9	15	381

**Error message and/or stacktrace**

**Additional context**

**Comment by alexey-milovidov** [comment]
Does it reproduce in 20.2 testing?
https://repo.yandex.ru/clickhouse/deb/testing/main/
