### ISSUE TITLE
CREATE DICTIONARY IF NOT EXISTS support

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#8264]
**Use case**
I need an opportunity to create dictionaries when it not exists

**Describe the solution you'd like**
Add support `CREATE DICTIONARY IF NOT EXISTS`, cause currently `DROP DICTIONARY IF EXISTS` works fine

**Comment by alesapin** [comment]
Already done https://github.com/ClickHouse/ClickHouse/pull/8032.
