### ISSUE TITLE
Error: parse backslash and double quotes in JSON.

### ISSUE THREAD

**Issue by AutopilotNN** [ClickHouse/ClickHouse#8268]
One of the JSON fields stores JSON as a string. Inside the second JSON in one of the fields was a string that had double quotes.

```
{
"id": 480,
"obj_oid": "d76a0c",
"date": "2019-11-05T01:22:19",
"custom_data": "{\"created_at\":\"2019-11-05 17:20:29  0300\",\"obj_id\":\"5191\",\"obj_title\":\"МЦ \\\"Нова\\\" НН\",\"order_id\":\"161\",\"price\":\"
134.2\",\"amo_sale\":\"1776\"}"
}
```
Field type 'custom_data' is a String.
Result:
Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected , before: Нова\\\\" НН\\",\\"order_id\\":\\"161\\",\\"price\\":\\"124.2\\",\\"amo_sale\\":\\"1776\\"}",\n  "call_type": "{\\"id\\":2,\\"name\\":\\"REPEATED\\"}",\n  "is_deferred: (at row 296)

**Comment by alexey-milovidov** [comment]
How do you insert this data into ClickHouse?
Your field escaping is correct. But it may broke before insertion.

Looks like everything is working fine:
```
clickhouse-local --input-format JSONEachRow -S "id UInt64, obj_oid String, date DateTime, custom_data String" <<< '{"id": 480, "obj_oid": "d76a0c", "date": "2019-11-05T01:22:19", "custom_data": "{\"created_at\":\"2019-11-05 17:20:29  0300\",\"obj_id\":\"5191\",\"obj_title\":\"МЦ \\\"Нова\\\" НН\",\"order_id\":\"161\",\"price\":\"134.2\",\"amo_sale\":\"1776\",\"amo_sale\":\"1776\"}"}' --query "SELECT * FROM table"
480     d76a0c  2019-11-05 01:22:19     {"created_at":"2019-11-05 17:20:29  0300","obj_id":"5191","obj_title":"МЦ \\"Нова\\" НН","order_id":"161","price":"134.2","amo_sale":"1776","amo_sale":"1776"}
```

**Comment by AutopilotNN** [comment]
/bin/sh
echo "INSERT INTO $CH_Name.$CH_Table FORMAT JSONEachRow $(cat $DIR/$CH_Name/calls_proper.json)" | curl --silent -u $CH_User:$CH_Pass $CH_Host --data-binary @-

**Comment by AutopilotNN** [comment]
You made me think. The my code is incorrect! So correctly:

`echo "INSERT INTO $CH_Name.$CH_Table FORMAT JSONEachRow " | cat - calls_tmp.json | curl -u $CH_User:$CH_Pass $CH_Host --data-binary @-
`
