### ISSUE TITLE
Dictionaries DDL: Poco::Exception. Code: 1000, e.code() = 1046, e.displayText() = mysqlxx::BadQuery: No database selected (127.0.0.1:3306) (version 19.17.4.11)

### ISSUE THREAD

**Issue by Slach** [ClickHouse/ClickHouse#8283]
**Describe the bug or unexpected behavior**
When use Dictionaries DDL via `CREATE DICTIONARY ... SOURCE(MYSQL(...))` load dictionary FAILED with last exсeption
```
Poco::Exception. Code: 1000, e.code() = 1046, e.displayText() = mysqlxx::BadQuery: No database selected (127.0.0.1:3306) (version 19.17.4.11)
```

**How to reproduce**
* Which ClickHouse server version to use
19.17.4.11
* Which interface to use, if matters
DataGrip - JAR, HTTP
* Queries to run that lead to unexpected result
```sql
CREATE DICTIONARY wister.dict_prod_pays(
    nom String,
    code String DEFAULT 'Unknown',
    cur String DEFAULT 'USD'
) PRIMARY KEY nom
SOURCE(
    MYSQL(port 3306 host '127.0.0.1' user 'user' password 'xxxx' database 'prod' table 'pays')
)
LAYOUT(COMPLEX_KEY_HASHED())
LIFETIME(MIN 300 MAX 600);
```
**Expected behavior**
Succreefully created and loaded Dictionary 

**Actual behavior**
Dictionary created but with status FAILED
`SELECT * FROM system.dictionaries`

**Error message and/or stacktrace**
Last execption
`Poco::Exception. Code: 1000, e.code() = 1046, e.displayText() = mysqlxx::BadQuery: No database selected (127.0.0.1:3306) (version 19.17.4.11`

**Additional context**
Wrong MySQL query send when try data load to dictionary
![image](https://user-images.githubusercontent.com/105560/71145857-d121df80-2244-11ea-8a53-2356e0bc69c3.png)

Error message saved to last exception column on system.dicrionaries
![image](https://user-images.githubusercontent.com/105560/71146290-7ab5a080-2246-11ea-912c-159fbee3e56d.png)

**Comment by alesapin** [comment]
You have to specifiy `db 'prod'`, not `database 'prod'`.
