### ISSUE TITLE
Support Dictionary with MySQL database

### ISSUE THREAD

**Issue by zhang2014** [ClickHouse/ClickHouse#8284]
**Use case**
It's just my thought, and I'm not sure it's right for implementation.

Currently, mysql database engine supported fetch mysql table as clickhouse mysql engine table. maybe we also can support fetch mysql table as clickhouse mysql engine dictionary

For example:
```
mysql :) CREATE DATABASE test;
mysql :) CREATE TABLE test.test_a ... ;

clickhouse :) CREATE DATABASE test_database ENGINE=MySQL('host_name:port', 'test', 'xxx', 'xxx') SETTINGS DICTIONARY_LAYOUT(COMPLEX_KEY_HASHED()) DICTIONARY_LIFETIME(MIN 300 MAX 600);
Ok.

clickhouse :) SHOW TABLES FROM test_database;
test_a

clickhouse :) SHOW DICTIONARIES FROM test_database;
test_a

```

**Comment by alexey-milovidov** [comment]
But it's hardly needed - you can easily create a dictionary with CREATE DICTIONARY on top of the tables from MySQL database. And creating dictionaries for every table from MySQL will be impractical (it's difficult to derive the structure and there will be concerns with memory usage).
