### ISSUE TITLE
Questions about clickhouse LTS ?

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#8285]
I'm glad to see the new release of clickhouse v19.14.8.9-lts,it's has a tag  **lts**. I want to know the lts is the meaning of "Long  Term Support"? if so how long do you release a LTS version and the LTS version's support period? and whether you update the documents about clickhouse release at the official document.
IN PRODUCTION i desire to use a stable and long support version.

**Comment by alexey-milovidov** [comment]
Long Term Support versions are introduced for big enterprise customers who don't like to update often. LTS version is released twice a year with limited support during one year. Limited support includes backports of bugfixes (only fixes that were easy to backport or that were required by customer).

For normal customers, stable versions should be preferred over LTS.

**Comment by vkingnew** [comment]
wow,the question is answered so quickly. Thanks!
Is LTS version open to common users？ And whether provided the packages like DEB and RPM for download ?

**Comment by alexey-milovidov** [comment]
Yes, LTS versions are available for everyone.
They are located in the same repository, just replace `stable` to `lts`:
https://repo.yandex.ru/clickhouse/deb/lts/main/
https://repo.yandex.ru/clickhouse/rpm/lts/x86_64/

**Comment by vkingnew** [comment]
@alexey-milovidov  That's a  Good news for enterprise users ! 
 v19.14.8.9-lts  , Whether this version is the first LTS Version  from clickhouse born so far ?

**Comment by alexey-milovidov** [comment]
Yes, the first LTS version is 19.14.
