### ISSUE TITLE
Clickhouse Roadmap  at 2020

### ISSUE THREAD

**Issue by vkingnew** [ClickHouse/ClickHouse#8293]
**Q1:What's the roadmap of clickhouse at 2020?**
If you have ,please update it at https://clickhouse.yandex/docs/en/roadmap/

**Q2: The roadmap at 2019 compeleted all  by the end of 2019?**
https://clickhouse.yandex/docs/en/roadmap/
Especially the functions:
>JOIN not limited by available memory

IN OUR situations this is ffrequently used. And the offical documents are update later.

**Q3: How do you think about Clickhouse at aliyun?**
https://help.aliyun.com/document_detail/146301.html?spm=a2c4g.11174283.3.1.299a4c78bEUbBG
As 2019.12.19,Alicloud announces the experiences of clickhouse on alicloud，it will be own money,whether Alicloud contributed the code to clickhouse ? and what do you think of this？

**Comment by den-crane** [comment]
Q1. https://github.com/ClickHouse/ClickHouse/blob/master/docs/ru/extended_roadmap.md Russian only.

Q2. `JOIN not limited by available memory` Almost ready. Probably in Q1 2020 in release.

Q3. CH license does not restrict it.

**Comment by alexey-milovidov** [comment]
We welcome the use of ClickHouse in AliCloud as in other cloud providers, services, appliances and commercial products.

**Comment by vkingnew** [comment]
@den-crane  It's not to read for non-Russian users，It's better to translate  it into English and update it to official docments.As so far I just to read it by translate software,maybe it not exact.

**Comment by filimonov** [comment]
Duplicate #8215

The roadmap should be translated soon. Stay tuned.
