### ISSUE TITLE
Bring back the old behaviour of `rows_before_limit_at_least `

### ISSUE THREAD

**Issue by Har01d** [ClickHouse/ClickHouse#8296]
We have a simple MergeTree table with ~1M records. Sometimes we need to get last 10 records ordered by id, but we’d also like to get the total number of rows returned by the query if there were no limit.

```
SELECT count()
FROM blocks

┌─count()─┐
│  600000 │
└─────────┘
```

Запрос

```
SELECT id
FROM blocks
ORDER BY id DESC
LIMIT 10
FORMAT JSON
```

ClickHouse v.19.17.5.18 (latest) yields `"rows_before_limit_at_least": 10,`
If we downgrade to v.18.16.1 it yields: `"rows_before_limit_at_least": 600000,`

Alexey says that this was done for performance optimization, but that was a very convenient way to get the needed results and in the same time the total number of results (e.g. to paginate them).

Is it possible to introduce a special setting to get the old behaviour back (it’s ok if it’d slow down the queries if enabled)?

Thanks!

**Comment by Har01d** [comment]
Possibly duplicates #6613

**Comment by alexey-milovidov** [comment]
We can add a setting `rows_before_limit_exact` that will force using `always_read_till_end` in `LimitBlockInputStream`.

**Comment by den-crane** [comment]
>Is it possible to introduce a special setting to get the old behaviour back

optimize_read_in_order = 0 ?

**Comment by Har01d** [comment]
> optimize_read_in_order = 0 ?

That doesn’t help unfortunately.

The latest version which supports the old behaviour is 19.13.6.51.

@alexey-milovidov @den-crane

**Comment by den-crane** [comment]
@Har01d Are you sure?

```
create table blocks (id Int64, A String) Engine=MergeTree order by id;
insert into blocks select number, 'aaa' from numbers(600000);
SELECT count()
FROM blocks
┌─count()─┐
│  600000 │
└─────────┘

SELECT id
FROM blocks
ORDER BY id DESC
LIMIT 10
FORMAT JSON
....
"rows_before_limit_at_least": 10,


SELECT id
FROM blocks
ORDER BY id DESC
LIMIT 10
FORMAT JSON SETTINGS optimize_read_in_order = 0
"rows_before_limit_at_least": 600000,
```

**Comment by Har01d** [comment]
Indeed, that setting worked, I was trying to use it in the wrong config section (server.xml instead of users.xml). It’s not really clear why optimization settings are on the user level.

Thanks for your help!
