### ISSUE TITLE
Run multiple queries with consistent results against replicated tables

### ISSUE THREAD

**Issue by svladykin** [ClickHouse/ClickHouse#8313]
I have replicated tables with relatively high insertion rate. I want to run multiple long queries so that they produce consistent results, but when the first query finishes more data gets already inserted to the table, so the subsequent queries will produce different results. 

Without replication I would just add a field like `insert_time DateTime materialized now()` and limit the data set by the same `insert_time` in each query to produce consistent results, but if I do this with replicated table I lose deduplication because the same batch inserted multiple times will have different `insert_time`.

Is there any workaround?

**Comment by den-crane** [comment]
Usually data itself has some natural datetime attributes. I have 5! different timestamps in my data so I can check data consistency among 4 different DWH systems (2 clusters of CH + 2 clusters of Vertica).

You can fill `insert_time DateTime` before inserting in CH in back-end -- `etl_time`

**Comment by svladykin** [comment]
@den-crane 

Yes, data itself contains timestamp but it is not monotonically increasing, a batch may contain any timestamp within the last 24 hours. So, it does not help much.

How `etl_time` is different from `insert_time`? In case of clickhouse replica failure or data writer failure we may end up with batch duplicate if it generate different `etl_time` for the same batch.

**Comment by den-crane** [comment]
If you re-generate a batch at ETL the second time how you guarantee the same row-order and the same row-set for deduplication?

**Comment by svladykin** [comment]
@den-crane 
We write data from Kafka to Clickhouse and collect batches of fixed size per partition separately. This way we guarantee at least once processing of a batch. Probably we could use `kafka_time` but we have more than 1 partition and partitions may go at different speeds.

**Comment by svladykin** [comment]
@alexey-milovidov 
Maybe it would be a good idea if deduplication will consider columns with `DEFAULT` expression but ignore `MATERIALIZED` columns. This way it will be possible to have 'insert_time MATERILAIZED now()' column and still have working deduplication.

**Comment by filimonov** [comment]
Maybe Kafka timestamp (accessible via _timestamp virtual column) will help you?

Also some minimal support for transactions is planned.

**Comment by svladykin** [comment]
@filimonov 
You mean Kafka engine in Clickhouse? We do not use it, since it looks pretty buggy and unstable right now.
We have an in-house solution for storing data from Kafka to Clickhouse, I'm not saying it is better, but at least we can quickly fix bugs in it ourselves when needed.

Yes, I was thinking about Kafka timestamp but since we have more than one partition and they may be processed at different speeds, it will not help much.

Kafka transactions in my understanding will not be of any help here, because they work in cases where you either produce multiple records to Kafka and then commit (all or nothing publishing) or read records from Kafka and publish records to Kafka and then commit (read-process-write pattern). But if you store the resulting data in some external system, it actually means that you have the same "at least once" semantics and you have to handle duplicates at the level of this external system. So I would still need deduplication from Clickhouse.

If you mean native transactions for Clickhouse, that would be interesting. For my case it would require "repeatable read" isolation. Please consider supporting it.

Though, for my case it would be sufficient to have a virtual `_insert_time` column. I understand the space/performance implications, but it can be disabled by default. Or maybe some columns (`materialized` from example) should be ignored by the deduplication.

**Comment by blinkov** [comment]
@svladykin, do you have any further questions?

**Comment by svladykin** [comment]
Yes. The problem was not solved. 
Thus it makes sense to treat this issue as a feature request but not a question.

**Comment by alexey-milovidov** [comment]
Deduplication works on top of an inserted batch of data, which means that the described problem is nonexistent.
