### ISSUE TITLE
Benchmarks of ClickHouse on Ceph

### ISSUE THREAD

**Issue by yingfeng** [ClickHouse/ClickHouse#8315]
In 2019.12.19, Alicloud announced to provide ClickHouse service within their public cloud, according to the [description](https://help.aliyun.com/document_detail/145984.html?spm=a2c4g.11174283.3.2.27714c78ynI4zb), as well as the Q&A with their technical supporters:
![](https://user-images.githubusercontent.com/7248/71246951-b2aa0a00-2352-11ea-8d67-9cbe9da25a5e.png)

We could know that the data of ClickHouse is stored within the distributed storage directly, which is very similar with EBS of AWS, even without remarkable performance degrading.

I am very suspicious of such a conclusion, as a result, has any one made any benchmark on similar solution as Ceph? Which means that to use a distributed storage(either object storage or block) to directly serve as the data layer of ClickHouse.

Additionally, according to the [2020 roadmap ](https://github.com/ClickHouse/ClickHouse/blob/master/docs/ru/extended_roadmap.md), I also notice that a VFS would be provided such that ClickHouse could run on different distributed storages as S3 or HDFS, what's the anticipated performance degrading for such design?

**Comment by alexey-milovidov** [comment]
> I am very suspicious of such a conclusion, as a result, has any one made any benchmark on similar solution as Ceph? Which means that to use a distributed storage(either object storage or block) to directly serve as the data layer of ClickHouse.

We also provide ClickHouse over Network Block Device (as an option) in Yandex Cloud.
It is indeed slower than on local SSD but I don't remember the exact numbers (need to check it again).

Also I know that a few customers has been using ClickHouse over Ceph, GlusterFS and MooseFS. But I don't know the exact performance numbers.

My collegues from Altinity have tested ClickHouse with FUSE over S3 and mabe they can share the results. This setup works but it's not near to be practical.

> Additionally, according to the 2020 roadmap , I also notice that a VFS would be provided such that ClickHouse could run on different distributed storages as S3 or HDFS, what's the anticipated performance degrading for such design?

We are going to have native support for S3 as storage. There are two proposed use cases:
- store all data on S3 and pay for computation resources on demand (pay for query);
- store fresh data on local storage and cold data on S3 as a cold storage.

It is expected to be slower from fundamental perspective: if you need to keep up with sequential throughput of single local NVMe SSD, you need at least 25 Gbit network bandwidth per each server node. But the setup can work as fast as with local storages if the cold storage will be actually cold.

**Comment by filimonov** [comment]
> My collegues from Altinity have tested ClickHouse with FUSE over S3 and mabe they can share the results. This setup works but it's not near to be practical.

ClickHouse works quite well in readonly mode with fuse + goofys above s3. That means data should be moved there manually, after that ClickHouse can read it.  

When it need to write data it uses renames & hardlinks quite intensively and that doesn't work at all in that scenario.

Can't add anything about ceph

**Comment by yingfeng** [comment]
We've made some experiments using Ceph as a Block device. The results show that ClickHouse instance running on Block Devices is only a bit slower (less than 10%) than that running on local disk for cold start queries, and the results are even more close for warm start queries because data in Ceph could also be cached within local disk page cache.  I'm not sure whether such features(disk page cache contains object from remote DFS(either block or object storage)) could exist for general cloud solutions, it seems to have ClickHouse run on such solution could be a good alternative for high availability.
