### ISSUE TITLE
Conflicting user configuration files created during update

### ISSUE THREAD

**Issue by stifstyle** [ClickHouse/ClickHouse#8316]
After updating Clickhouse as described in https://clickhouse.yandex/docs/en/operations/update/ from version 19.3.5 to 19.17.4.11, clickhouse-server service refused to start. I have Ubuntu 18.04.1 LTS.

**How to reproduce**
* Clickhouse version - 19.3.5, user settings stored in `/etc/clickhouse-server/users.xml`. Password for user "default" is stored in `<password_sha256_hex></password_sha256_hex>` block
* Updating to the newest version (19.17.4.11 in my case)
* During the update system asks for password for default user; I entered it
* Choose to keep previously created config files
* Restarting clickhouse-server daemon -> service doesn't start

**Expected behavior**
Service "clickhouse-server" restarts without errors after update.

**Error message and/or stacktrace**
When trying to start clickhouse-server:
`Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Cannot create file: Cannot create pid file. (version 19.17.5.18 (official build)`

In `/var/log/clickhouse-server/clickhouse-server.err.log`: 
`<Error> Application: DB::Exception: More than one field of 'password', 'password_sha256_hex', 'password_double_sha1_hex' is used to specify password for user default. Must be only one of them.`

**How I solved the problem**
Deleted "users.d" folder with conflicting settings that was created after an update.

**Comment by alexey-milovidov** [comment]
It may happen if you are upgrading from previously installed unofficial package (that was not asking for password).
So the fact that the password was already specified is not saved and it asks for password on upgrade.

**Comment by alexey-milovidov** [comment]
It indicates that something is wrong with installation or with debian machinery.
