### ISSUE TITLE
Unconsitant behavour between dictGet and  dictGetString

### ISSUE THREAD

**Issue by crakjie** [ClickHouse/ClickHouse#8320]
This request :
```
SELECT 
   dictGet('dictId', 'name', toUInt64(dictId)) AS name,
   dictGet( 'dictId', 'age',toUInt64(dictId)) AS age 
  FROM 
     users  
  GROUP BY name
```
Do not work because
`Column dictId is not under aggregate function and not in GROUP BY`
which seems expected because we are indeed not grouping on name.

But this query work and I dont enderstand why.
```
SELECT 
   dictGetString('dictId', 'name', toUInt64(dictId)) AS name,
   dictGet( 'dictId', 'age',toUInt64(dictId)) AS age 
  FROM 
     users  
  GROUP BY name
```
I'm afraid of a different implementation beween `dictGetString` and `dictGet`.

**Comment by alexey-milovidov** [comment]
Did you configured the `name` attribute as `injective`?

**Comment by amosbird** [comment]
Neither works on current master. And current master requires database name specified in dictGet* functions like `'default.dictId'`. Could you test against current master to see if it's still a confusion?

**Comment by crakjie** [comment]
@alexey-milovidov No I did not. In this case I could have understood.
@amosbird mmmh big change for existing queries. That was actually tested with 19.15.3.6
