### ISSUE TITLE
JSON type inference

### ISSUE THREAD

**Issue by ramazanpolat** [ClickHouse/ClickHouse#8327]
**Introduction**

JSON is a dynamic format. So there is no type definition for a JSON object. Although ClickHouse can use JSON, users are forced to know the type of a JSON element.

In the following example, user must know that `i` is an `int` type and `f` is a `float` type:

```sql
WITH '{"i": 1, "f": 1.2}' AS json
SELECT
    JSONExtract(json, 'i', 'Int8') AS i,
    JSONExtract(json, 'f', 'Float32') AS f

┌─i─┬─f─┐
│ 1 │ 0 │
└───┴───┘
```

Although there is a function for extracting raw value(`JSONExtractRaw`), the resulting type will always be the `String`:

```sql
WITH '{"i": 1, "f": 1.2}' AS json
SELECT
    JSONExtractRaw(json, 'i') AS i,
    JSONExtractRaw(json, 'f') AS f,
    toTypeName(i) AS i_type,
    toTypeName(f) AS f_type

┌─i─┬─f──────────────────┬─i_type─┬─f_type─┐
│ 1 │ 1.2000000000000002 │ String │ String │
└───┴────────────────────┴────────┴────────┘
```
There is also a function for checking JSON value type(`JSONType`).

```sql
WITH '{"i": 1, "f": 1.2}' AS json
SELECT JSONType(json, 'i') AS i_type

┌─i_type─┐
│ Int64  │
└────────┘
```

With combining these two functions, users will have a powerful JSON database like MongoDB. But the usage will be really ugly and slow because it must be in two steps:

1. User must issue an SQL using `JSONType` to get the type:

```sql
WITH '{"i": 1, "f": 1.2}' AS json
SELECT JSONType(json, 'i') AS i_type

┌─i_type─┐
│ Int64  │
└────────┘
```

2. Then user must build a second SQL statement using `JSONExtract` and use the type they get from first step:

```sql
WITH '{"i": 1, "f": 1.2}' AS json
SELECT
    JSONExtract(json, 'i', 'Int64') AS value,
    toTypeName(value) AS type

┌─value─┬─type──┐
│     1 │ Int64 │
└───────┴───────┘
```

**Using `JSONType` output as `CAST` parameter will not work:**

```sql
WITH
    '{"i": 1, "f": 1.2}' AS json,
    JSONType(json, 'i') AS type
SELECT JSONExtract(json, 'i', type)

Received exception from server (version 19.17.2):
Code: 368. DB::Exception: Received from some-clickhouse-server:9000. DB::Exception: std::bad_typeid.
```

**Use case**

Automatically inferring the type of a JSON value will make ClickHouse a great alternative for MongoDB and ElasticSearch like document stores.

Right now, we have to know the JSON schema, which is not so possible. But if this feature gets implemented, we will be able to freely query tables which will make ClickHouse best alternative for ElasticSearch.

Users will be able to send any JSON structure they want and they will be able to query for any field.

**Describe the solution you'd like**

Implementing a function that combines `JSONType` and `JSONExtract` functions will solve this problem.

A new function named `JSON` will first check the type of the value then use `JSONExtract` to extract the value and convert to value type:

```sql
WITH '{"i": 1, "f": 1.2}' AS json
SELECT
    JSON(json, 'i') AS value,
    toTypeName(value) AS type

┌─value─┬─type──┐
│     1 │ Int64 │
└───────┴───────┘
```

**Comment by alexey-milovidov** [comment]
This is not easy to implement.

In our query language, the function return type is determined by the types of its arguments and the values of the constant arguments. It cannot depend on the values of non-constant arguments.

Example:

```
SELECT JSON(json, 'k') FROM VALUES('json String', ('{"k":1}'), ('{"k":"hello"}'))
```

`json` is not constant and the type cannot be inferred.

**Comment by alexey-milovidov** [comment]
We have also improved the error message:

```
WITH
    '{"i": 1, "f": 1.2}' AS json,
    JSONType(json, 'i') AS type
SELECT JSONExtract(json, 'i', type)

Query id: 425614a8-7dc9-49a3-a049-2773a0a3c5bd


0 rows in set. Elapsed: 0.077 sec. 

Received exception:
Code: 44. DB::Exception: The last argument of function JSONExtract should be a constant string specifying the return data type, illegal value: type: While processing JSONExtract('{"i": 1, "f": 1.2}' AS json, 'i', JSONType(json, 'i') AS type). (ILLEGAL_COLUMN)
```
