### ISSUE TITLE
zk_watch_count increase and never descrease when use "drop PARTITION  on cluster"

### ISSUE THREAD

**Issue by lingfengsan** [ClickHouse/ClickHouse#8337]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
zk_watch_count increase and never descrease when use "drop partion on cluster"

**How to reproduce**
* Which ClickHouse server version to use 
19.11.5
* Which interface to use, if matters
ALTER TABLE table_name DROP PARTITION  on cluster

**Expected behavior**
I run the sql "ALTER TABLE table_name DROP PARTITION  on cluster".Then the zookeeper watch count increase . And after three days, watch count not decrease

**Comment by LB-J** [comment]
hi，do you have reslove thisproblems ？

**Comment by alexey-milovidov** [comment]
@LB-J does it reproduce on version 20.12?
It should be unlikely as we have the related fixes: #14693
