### ISSUE TITLE
CHECK TABLE documentation is inaccurate

### ISSUE THREAD

**Issue by ishirav** [ClickHouse/ClickHouse#8338]
The documentation of CHECK TABLE states:

> For MergeTree family engines, the CHECK TABLE query shows a check status for every individual data part of a table on the local server.

This is only true if `check_query_single_value_result=0`, but the documentation doesn't mention it.

**Comment by olgarev** [comment]
Internal documentation ticket: DOCSUP-8221

**Comment by olgarev** [comment]
@alexey-milovidov Documented, please remove the `comp-documentation` tag.
