### ISSUE TITLE
result of cityHash64 differs from python escherba/python-cityhash/CityHash64

### ISSUE THREAD

**Issue by bl17zar** [ClickHouse/ClickHouse#8354]
**Describe the bug or unexpected behaviour**
executing ```SELECT cityHash64('Moscow')```  in clickhouse-client produces 
```12507901496292878638```

while executing the following script in python3.7.x
```python
from cityhash import CityHash64
print(CityHash64('Moscow'))
```
produces 
```5992710078453357409```

Both of the algorithms reference original Google cityHash algorithm. What is the reason behind this behaviour?

**How to reproduce**
* CH image: ```yandex/clickhouse-server:19.17```
* python3.7 with https://github.com/escherba/python-cityhash

**Expected behavior**
equality of produced hash

**UPD: checked encoding**
both examples have valid utf8 sequence of bytes and still produces different results

**Comment by den-crane** [comment]
```
SELECT farmHash64('Moscow')

┌─farmHash64('Moscow')─┐
│  5992710078453357409 │
└──────────────────────┘
```

**Comment by den-crane** [comment]
https://pypi.org/project/clickhouse-cityhash/

**Comment by bl17zar** [comment]
This helped! Thanks

**Comment by alexey-milovidov** [comment]
CityHash has changed the algorithm after we have added it into ClickHouse.

CityHash documentation specifically notes that the user should not rely to specific hash values and should not save it anywhere or use it as sharding key.

But as we exposed this function to the user, we had to fix the version of CityHash (to 1.0.2). And now we guarantee that the behaviour of CityHash functions available in SQL will not change.

**Comment by bl17zar** [comment]
It makes it clear 😊

**Comment by ernado** [comment]
Note that `farmHash64` is not fully compatible with `cityHash64`, while having some collisions (e.g. on `Moscow` string).


| String                                                     | ClickHouse64         | CityHash64           | FarmHash64           |
| ---------------------------------------------------------- | -------------------- | -------------------- | -------------------- |
| `Moscow`                                                   | 12507901496292878638 | 5992710078453357409  | 5992710078453357409  |
| `How can you write a big system without C++?  -Paul Glick` | 6237945311650045625  | 749291162957442504   | 11716470977470720228 |

So don't use `farmHash64` to calculate CityHash64, it is invalid.
