### ISSUE TITLE
Any ideas for data rebalance when running on distributed block storage?

### ISSUE THREAD

**Issue by yingfeng** [ClickHouse/ClickHouse#8392]
In 2019.12.19, Alicloud announced to provide ClickHouse service within their public cloud, according to the [description](https://help.aliyun.com/document_detail/145984.html?spm=a2c4g.11174283.3.2.27714c78ynI4zb), the ClickHouse instances are running on Block Devices similar with AWS EBS. We've also made some experiments to compare the performance of ClickHouse running on between local disk and Ceph RBD, and the results do not show remarkable differences, either for cold start queries and warm start ones. As a result, it's a good idea to directly have ClickHouse instances run on such Block Devices, especially within public cloud environments, which makes the high availability pretty easy without depending on replicated merge tree engine.
However, under such circumstances, how to perform automatic data rebalance when adding or removing ClickHouse shard nodes?  The Alicloud claims to provide such feature without modifying the ClickHouse itself, does anyone have ideas on this?

**Comment by blinkov** [comment]
@yingfeng, is this question still relevant?

**Comment by blinkov** [comment]
@yingfeng, do you have any further questions?
