### ISSUE TITLE
Add replace/remove examples for configuration documentation

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#8394]
**Describe the issue**
Not enough examples how to write configuration files with replace/remove attributes.

**Additional context**
Feature is described [here](https://github.com/ClickHouse/ClickHouse/blame/master/docs/en/operations/configuration_files.md#L8)
But it is unclear for newbie what to do exactly.
XML attributes syntax requires some data set, but documentation describes only names `replace` and `remove`
`<element name="value">`

**Comment by BayoNet** [comment]
I have a global task on the configuration part of documentation CLICKHOUSEDOCS-292.  I'll do it there.

**Comment by alexey-milovidov** [comment]
This task was not done.
