### ISSUE TITLE
can't insert  NULL data into LowCardinality(Nullable(String)) 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#8406]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
A clear and concise description of what works not as it is supposed to.

**How to reproduce**
* Which ClickHouse server version to use
19.15.4.10

 clickhouse-client --host ck003 --query="INSERT INTO my_sdap.dm_user_behavior_events FORMAT Parquet " <  /data/dm_user_behavior_events/R2_1_0_0-0_TableSink1        

create table  

CREATE TABLE my_sdap.dm_user_behavior_events (`dt` UInt32, `user_id` UInt32, `event_time` DateTime CODEC(Delta(4), LZ4), `event_attr5` LowCardinality(Nullable(String)),***) ENGINE = ReplicatedMergeTree('/clickhouse/tables/my_sdap/dm_user_behavior_events/{shard}', '{replica}') PARTITION BY event_dt ORDER BY (client_id, event_id, mode, dt, intHash64(user_id)) SAMPLE BY intHash64(user_id) TTL event_time + toIntervalDay(30) SETTINGS index_granularity = 8192

**Error message and/or stacktrace**

Code: 349. DB::Exception: Can not insert NULL data into non-nullable column "event_attr5"

**Additional context**

**Comment by KochetovNicolai** [comment]
Must have been fixed by #8406
