### ISSUE TITLE
Division by zero when case when and Decimal

### ISSUE THREAD

**Issue by kaijianding** [ClickHouse/ClickHouse#8408]
**Describe the bug or unexpected behaviour**
unexpected `Division by zero`

**How to reproduce**
* Which ClickHouse server version to use
19.17.4.11
* Queries to run that lead to unexpected result
```sql
CREATE TABLE test (`i` Int64, `d` Decimal(38, 6)) ENGINE = MergeTree() ORDER BY tuple() SETTINGS index_granularity = 8192 ;`
insert into test values (0,4.9);
select case when i>0 then d/i else 0 end from test;
```
**Expected behavior**
the result should be `0`
**Error message and/or stacktrace**
`Code: 153. DB::Exception: Received from localhost:9000. DB::Exception: Division by zero.`

The result is correct if `d` is Float64

I found several similar issues have been reported, but this issue seems different

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/1562
