### ISSUE TITLE
nullIf non consistent behavior

### ISSUE THREAD

**Issue by ghuname** [ClickHouse/ClickHouse#8437]
Please look at this select:

```
SELECT 
    nullIf(nan, nan), 
    0 / 0, 
    nullIf(0 / 0, nan), 
    nullIf(nan, 0 / 0)

┌─nullIf(nan, nan)─┬─divide(0, 0)─┬─nullIf(divide(0, 0), nan)─┬─nullIf(nan, divide(0, 0))─┐
│             ᴺᵁᴸᴸ │          nan │                       nan │                       nan │
└──────────────────┴──────────────┴───────────────────────────┴───────────────────────────┘
```

How come that all nullIf expressions are not null?

ClickHouse client version 19.16.3.6.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.16.3 revision 54427.

**Comment by den-crane** [comment]
```
SELECT
    nan = nan,
    nan,
    0 / 0,
    nan = toFloat64(0 / 0),
    isNaN(0 / 0)

┌─equals(nan, nan)─┬─nan─┬─divide(0, 0)─┬─equals(nan, toFloat64(divide(0, 0)))─┬─isNaN(divide(0, 0))─┐
│                1 │ nan │          nan │                                    0 │                   1 │
└──────────────────┴─────┴──────────────┴──────────────────────────────────────┴─────────────────────┘
```

**Comment by alexey-milovidov** [comment]
```
SELECT 
    0 AS a, 
    0 + 0 AS b, 
    a = b, 
    a / a AS n1, 
    b / b AS n2, 
    n1 = n2, 
    nan = nan

┌─a─┬─b─┬─equals(0, plus(0, 0))─┬──n1─┬──n2─┬─equals(divide(0, 0), divide(plus(0, 0), plus(0, 0)))─┬─equals(nan, nan)─┐
│ 0 │ 0 │                     1 │ nan │ nan │                                                    0 │                1 │
└───┴───┴───────────────────────┴─────┴─────┴──────────────────────────────────────────────────────┴──────────────────┘
```

NaN comparison in ClickHouse has implementation specific behaviour.
Let me explain this behaviour.

There are about 2^53 bitwise different NaNs.

NaNs in ClickHouse can be compared with IEEE 754 semantics, in that case, all NaN are always not equal to each other even if they are bit-identical.

In many cases, we use bitwise comparison - for DISTINCT, IN, JOIN, GROUP BY.

Also we use common subexpression elimination and we can resolve comparison of identical expressions, so identical expression is always equal to itself.

**Comment by ghuname** [comment]
Thanks for clarification. It will be nice if you put in documentation what you have explained here.
Best regards.
