### ISSUE TITLE
Code: 393, e.displayText() = DB::Exception: There is no query

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#8452]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
A clear and concise description of what works not as it is supposed to.
When a table begins to merge, some error occurs and the exception log in system.replication_queue like this.
```
##### Exception from system.replication_queue table. #####
72 │ MUTATE_PART │ 2019-12-29 07:51:56 │               0 │ cluster01-03-3 │ 20181228_0_799_6_7740     │ ['20181228_0_799_6_7557']     │         0 │                      0 │        12 │ Code: 393, e.displayText() = DB::Exception: There is no query (version 19.8.3.8) │ 2019-12-29 08:07:01 │             0 │                 │ 0000-00-00 00:00:00 │
```
This kind of exception blocks the normal merge process, which fulfill the queue and the max_replicated_merges_in_queue = 16, and this mutation will retry again and again.  This should not work with this behaviour, I think.

**How to reproduce**
I just find this table has this kind of problem,it looks like some bugs.

* Which ClickHouse server version to use
19.8.3.8

* Which interface to use, if matters
No interface.
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**
## This is the function stack ##
Error> cloudatlas.trace_events_local: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 393, e.displayText() = DB::Exception: There is no query, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65b4e16]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x32aa7ff]
2. clickhouse-server(DB::Context::getQueryContext() const+0x49) [0x5c9b3c9]
3. clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, std::shared_ptr<DB::IBlockInputStream> const&, std::shared_ptr<DB::IStorage> const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&)+0xe96) [0x5cf0a46]
4. clickhouse-server(DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&)+0x3b) [0x5cf0f4b]
5. clickhouse-server(DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptr<DB::IAST> const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocator<std::string> > const&)+0x705) [0x5cfd7d5]
6. clickhouse-server(DB::interpretSubquery(std::shared_ptr<DB::IAST> const&, DB::Context const&, unsigned long, std::vector<std::string, std::allocator<std::string> > const&)+0x216) [0x624ffc6]
7. clickhouse-server(DB::ActionsVisitor::makeSet(DB::ASTFunction const*, DB::Block const&)+0x408) [0x62d5fe8]
8. clickhouse-server(DB::ActionsVisitor::visit(std::shared_ptr<DB::IAST> const&)+0x15cd) [0x62d7cfd]
Already at oldest change
9. clickhouse-server(DB::ActionsVisitor::visit(std::shared_ptr<DB::IAST> const&)+0xfd6) [0x62d7706]
10. clickhouse-server(DB::ExpressionAnalyzer::getRootActions(std::shared_ptr<DB::IAST> const&, bool, std::shared_ptr<DB::ExpressionActions>&, bool)+0xbf) [0x6211aef]
11. clickhouse-server(DB::ExpressionAnalyzer::appendWhere(DB::ExpressionActionsChain&, bool)+0x177) [0x62156b7]
12. clickhouse-server(DB::InterpreterSelectQuery::analyzeExpressions(DB::QueryProcessingStage::Enum, bool, std::shared_ptr<DB::FilterInfo> const&)+0x606) [0x5cecb76]
13. clickhouse-server(DB::InterpreterSelectQuery::executeImpl(DB::InterpreterSelectQuery::Pipeline&, std::shared_ptr<DB::IBlockInputStream> const&, bool)+0x6ce) [0x5cee56e]
14. clickhouse-server(DB::InterpreterSelectQuery::execute()+0x54) [0x5cf10f4]
15. clickhouse-server(DB::MutationsInterpreter::isStorageTouchedByMutations() const+0x3ed) [0x623416d]
16. clickhouse-server(DB::MergeTreeDataMergerMutator::mutatePartToTemporaryPart(DB::FutureMergedMutatedPart const&, std::vector<DB::MutationCommand, std::allocator<DB::MutationCommand> > const&, DB::MergeListEntry&, DB::Context const&)+0x81e) [0x5f6387e]
17. clickhouse-server(DB::StorageReplicatedMergeTree::tryExecutePartMutation(DB::ReplicatedMergeTreeLogEntry const&)+0x485) [0x5edbf35]
18. clickhouse-server(DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&)+0x8d) [0x5ee552d]
19. clickhouse-server() [0x5ee5d20]
20. clickhouse-server(DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>)+0x3e) [0x5fe995e]
21. clickhouse-server(DB::StorageReplicatedMergeTree::queueTask()+0x146) [0x5ec3116]
####
```
**Additional context**No.

**Comment by den-crane** [comment]
Please check and provide an output of `select * from system.mutations where not is_done;`

**Comment by wangzhen11aaa** [comment]
> select * from system.mutations where not is_done;

There are a lot of stuff .

**Comment by wangzhen11aaa** [comment]
> Please check and provide an output of `select * from system.mutations where not is_done;`
One row likes this:
select * from system.mutations where not is_done limit 1 FORMAT JSON;

SELECT *
FROM system.mutations
WHERE NOT is_done
LIMIT 1
FORMAT JSON

{
	"meta":
	[
		{
			"name": "database",
			"type": "String"
		},
		{
			"name": "table",
			"type": "String"
		},
		{
			"name": "mutation_id",
			"type": "String"
		},
		{
			"name": "command",
			"type": "String"
		},
		{
			"name": "create_time",
			"type": "DateTime"
		},
		{
			"name": "block_numbers.partition_id",
			"type": "Array(String)"
		},
		{
			"name": "block_numbers.number",
			"type": "Array(Int64)"
		},
		{
			"name": "parts_to_do",
			"type": "Int64"
		},
		{
			"name": "is_done",
			"type": "UInt8"
		},
		{
			"name": "latest_failed_part",
			"type": "String"
		},
		{
			"name": "latest_fail_time",
			"type": "DateTime"
		},
		{
			"name": "latest_fail_reason",
			"type": "String"
		}
	],

	"data":
	[
		{
			"database": "cloudatlas",
			"table": "cloudatlas_user_group_local",
			"mutation_id": "0000007195",
			"command": "DELETE WHERE source_type = 0",
			"create_time": "2019-11-26 02:49:21",
			"block_numbers.partition_id": ["all"],
			"block_numbers.number": ["2917182"],
			"parts_to_do": "1",
			"is_done": 0,
			"latest_failed_part": "",
			"latest_fail_time": "0000-00-00 00:00:00",
			"latest_fail_reason": ""
		}
	],

	"rows": 1,

	"rows_before_limit_at_least": 8183,

	"statistics":
	{
		"elapsed": 0.045221188,
		"rows_read": 8419,
		"bytes_read": 50204834
	}
}

**Comment by den-crane** [comment]
OK. I believe there is an issue `There is no query` with one of these of  8183 mutations.
Check `select * from system.mutations where not is_done and latest_fail_reason <> '';`

I would cancel all of them (8133) https://clickhouse.yandex/docs/en/query_language/misc/#kill-mutation starting from failed with non-empty latest_fail_reason.

**Comment by wangzhen11aaa** [comment]
> OK. I believe there is an issue `There is no query` with one of these of 8183 mutations.
> Check `select * from system.mutations where not is_done and latest_fail_reason <> '';`
> 
> I would cancel all of them (8133) https://clickhouse.yandex/docs/en/query_language/misc/#kill-mutation starting from the failed ones (with non-empty latest_fail_reason).

Take this 

select * from system.mutations where not is_done and latest_fail_reason <> '' and table ='trace_events_local' limit 1;

```
SELECT *
FROM system.mutations
WHERE NOT is_done AND (latest_fail_reason != '') AND (table = 'trace_events_local')
LIMIT 1

┌─database───┬─table──────────────┬─mutation_id─┬─command─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────create_time─┬─block_numbers.partition_id─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─block_numbers.number───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─parts_to_do─┬─is_done─┬─latest_failed_part─────┬────latest_fail_time─┬─latest_fail_reason───────────────────────────────────────────────────────────────┐
│ cloudatlas │ trace_events_local │ 0000004477  │ DELETE WHERE oiid IN (SELECT toInt32(order_item_id) FROM remote('10.9.7.11:9000', etl.t_mcq_order_item) FINAL  WHERE (order_datekey = 20191226) AND (order_status = 0)) │ 2019-12-26 18:00:46 │ ['19700823','19840414','20181201','20181202','20181203','20181204','20181205','20181206','20181207','20181208','20181209','20181210','20181211','20181212','20181213','20181214','20181215','20181216','20181217','20181218','20181219','20181220','20181221','20181222','20181223','20181224','20181225','20181226','20181227','20181228','20181229','20181230','20181231','20190101','20190102','20190103','20190104','20190105','20190106','20190107','20190108','20190109','20190110','20190111','20190112','20190113','20190114','20190115','20190116','20190117','20190118','20190119','20190120','20190121','20190122','20190123','20190124','20190125','20190126','20190127','20190128','20190129','20190130','20190131','20190201','20190202','20190203','20190204','20190205','20190206','20190207','20190208','20190209','20190210','20190211','20190212','20190213','20190214','20190215','20190216','20190217','20190218','20190219','20190220','20190221','20190222','20190223','20190224','20190225','20190226','20190227','20190228','20190301','20190302','20190303','20190304','20190305','20190306','20190307','20190308','20190309','20190310','20190311','20190312','20190313','20190314','20190315','20190316','20190317','20190318','20190319','20190320','20190321','20190322','20190323','20190324','20190325','20190326','20190327','20190328','20190329','20190330','20190331','20190401','20190402','20190403','20190404','20190405','20190406','20190407','20190408','20190409','20190410','20190411','20190412','20190413','20190414','20190415','20190416','20190417','20190418','20190419','20190420','20190421','20190422','20190423','20190424','20190425','20190426','20190427','20190428','20190429','20190430','20190501','20190502','20190503','20190504','20190505','20190506','20190507','20190508','20190509','20190510','20190511','20190512','20190513','20190514','20190515','20190516','20190517','20190518','20190519','20190520','20190521','20190522','20190523','20190524','20190525','20190526','20190527','20190528','20190529','20190530','20190531','20190601','20190602','20190603','20190604','20190605','20190606','20190607','20190608','20190609','20190610','20190611','20190612','20190613','20190614','20190615','20190616','20190617','20190618','20190619','20190620','20190621','20190622','20190623','20190624','20190625','20190626','20190627','20190628','20190629','20190630','20190701','20190702','20190703','20190704','20190705','20190706','20190707','20190708','20190709','20190710','20190711','20190712','20190713','20190714','20190715','20190716','20190717','20190718','20190719','20190720','20190721','20190722','20190723','20190724','20190725','20190726','20190727','20190728','20190729','20190730','20190731','20190801','20190802','20190803','20190804','20190805','20190806','20190807','20190808','20190809','20190810','20190811','20190812','20190813','20190814','20190815','20190816','20190817','20190818','20190819','20190820','20190821','20190822','20190823','20190824','20190825','20190826','20190827','20190828','20190829','20190830','20190831','20190901','20190902','20190903','20190904','20190905','20190906','20190907','20190908','20190909','20190910','20190911','20190912','20190913','20190914','20190915','20190916','20190917','20190918','20190919','20190920','20190921','20190922','20190923','20190924','20190925','20190926','20190927','20190928','20190929','20190930','20191001','20191002','20191003','20191004','20191005','20191006','20191007','20191008','20191009','20191010','20191011','20191012','20191013','20191014','20191015','20191016','20191017','20191018','20191019','20191020','20191021','20191022','20191023','20191024','20191025','20191026','20191027','20191028','20191029','20191030','20191031','20191101','20191102','20191103','20191104','20191105','20191106','20191107','20191108','20191109','20191110','20191111','20191112','20191113','20191114','20191115','20191116','20191117','20191118','20191119','20191120','20191121','20191122','20191123','20191124','20191125','20191126','20191127','20191128','20191129','20191130','20191201','20191202','20191203','20191204','20191205','20191206','20191207','20191208','20191209','20191210','20191211','20191212','20191213','20191214','20191215','20191216','20191217','20191218','20191219','20191220','20191221','20191222','20191223','20191224','20191225','20191226'] │ [4478,4482,6653,6601,5428,4744,6268,7618,5772,4721,6180,7767,6583,5200,7146,7612,6630,6086,7208,7688,8145,7519,7667,7414,8205,7525,7507,8213,7707,7558,7373,7851,6727,6856,7126,7236,7372,6953,8914,8132,8222,7647,9099,7804,7026,7919,7669,7533,7288,7152,7326,7105,7387,6799,6861,6855,6845,6443,6114,6108,5840,6059,5917,5734,5267,5058,4804,4620,4699,4758,4963,5066,5169,5453,5980,6205,6304,6535,6869,6586,6572,6767,6704,7276,7418,7139,6926,7275,7544,7587,7276,7064,7615,7422,7450,7228,8127,8505,7953,5608,6139,7133,6806,6808,6898,6805,6805,7096,7592,7699,6898,6868,6898,6808,6440,6813,6870,6901,6992,6989,6899,6713,6718,7081,7078,7050,6772,6344,6435,6936,7358,7176,7111,6309,5875,5782,9419,9842,9806,6443,5875,5873,5693,5971,5872,6337,6461,6342,5878,5846,5971,5782,5595,5725,5852,5970,6284,6465,6466,6464,6551,6340,6460,6219,6470,6463,7299,7985,7634,6965,6501,7122,6962,6961,6966,7326,6959,6655,7342,6959,6961,7422,6963,6810,7087,7646,7606,8094,7457,7455,6529,6904,9606,8633,8052,10590,9785,10043,9956,14010,10699,11870,11038,5936,5967,5875,6204,6061,6062,6249,6061,6204,6055,6245,6654,6593,6658,6584,6626,6219,6738,6638,6625,6711,6632,6658,6286,6767,6637,6608,6852,6638,6638,6269,6703,6614,6642,6752,6597,6706,6305,6713,6710,6891,6766,6777,6899,6544,7014,8667,8751,8810,7715,8378,6456,8028,7972,7445,5772,5806,5621,5454,6190,5785,6050,6221,6233,6156,5878,6179,6223,6340,6469,6539,6538,6251,6563,6548,6680,6732,7751,6730,6459,7971,7102,6873,6915,5497,5201,5404,5704,5653,6878,5700,5706,5717,5522,5731,5775,5768,5812,5833,5950,5739,5742,5458,5275,5366,5407,5483,5552,7249,10136,15834,5876,5831,5641,5678,7237,5846,5856,5893,7324,7249,6924,7498,7460,7681,7889,7893,6194,5886,6104,6045,6158,6161,6151,6087,5926,6360,6435,8518,6565,6568,6593,6308,6628,7173,6569,6506,6507,6491,7950,8793,8737,8724,8853,6682,6576,6281,6572,6519,6507,6544,18261,6448,6199,6682,6597,6612,6542,6509,6479,6175,6477,6438,6427,6456,6631,6232,5934,6204,6233,6141,6246,6298,10447,6173,38538,46298,44633,44402,25694] │         806 │       0 │ 20190117_0_1271_6_7151 │ 2019-12-29 11:49:03 │ Code: 393, e.displayText() = DB::Exception: There is no query (version 19.8.3.8) │
└────────────┴────────────────────┴─────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────┴─────────┴────────────────────────┴─────────────────────┴──────────────────────────────────────────────────────────────────────────────────┘

1 rows in set. Elapsed: 1.410 sec. Processed 8.37 thousand rows, 90.60 MB (5.94 thousand rows/s., 64.26 MB/s.)
```
as example, I just not understand the reason for this exception. For this row, we have the command,which will be interpreted as the query, right? Then, why clickhouse will tell me that, it does not get a query?

**Comment by den-crane** [comment]
>DELETE WHERE oiid IN (SELECT toInt32(order_item_id) FROM remote

CH does not support such alters. Kill them all. 
You should create a dictionary or a table with Engine JOIN on all replicas and populate it with required order_item_id, then run ` alter delete where dictHas...`

**Comment by wangzhen11aaa** [comment]
> > DELETE WHERE oiid IN (SELECT toInt32(order_item_id) FROM remote
> 
> CH does not support such alters. Kill them all.
> You should create a dictionary or a table with Engine JOIN on all replicas and populate it with required order_item_id, then run ` alter delete where dictHas...`

```
KILL MUTATION WHERE (database = 'cloudatals') AND (table = 'trace_events_local') ASYNC

Ok.

0 rows in set. Elapsed: 0.011 sec.

m6v-data-clickhouse02.bj :) select count(0) from system.mutations where not is_done and latest_fail_reason <> '' and database='cloudatlas' and table = 'trace_events_local' ;

SELECT count(0)
FROM system.mutations
WHERE NOT is_done AND (latest_fail_reason != '') AND (database = 'cloudatlas') AND (table = 'trace_events_local')

┌─count(0)─┐
│     3168 │
└──────────┘

1 rows in set. Elapsed: 1.323 sec. Processed 8.43 thousand rows, 91.28 MB (6.37 thousand rows/s., 68.98 MB/s.)

```
After launch the kill mutation command, I use the 
select count(0) from system.mutations where not is_done and latest_fail_reason <> '' and database='cloudatlas' and table = 'trace_events_local'  to count() the mutation,
while the number does not change.

**Comment by den-crane** [comment]
Maybe these 3168 are new ones? After you killed 8133 ?
Try kill again.

**Comment by wangzhen11aaa** [comment]
> OK. I believe there is an issue `There is no query` with one of these of 8183 mutations.
> Check `select * from system.mutations where not is_done and latest_fail_reason <> '';`
> 
> I would cancel all of them (8183) https://clickhouse.yandex/docs/en/query_language/misc/#kill-mutation starting from the failed ones (with non-empty latest_fail_reason).

```
m6v-data-clickhouse01.bj :) select count(0) from system.mutations where not is_done and latest_fail_reason <> '' and database='cloudatlas' and table = 'trace_events_local' ;

SELECT count(0)
FROM system.mutations
WHERE NOT is_done AND (latest_fail_reason != '') AND (database = 'cloudatlas') AND (table = 'trace_events_local')

┌─count(0)─┐
│        0 │
└──────────┘

1 rows in set. Elapsed: 0.005 sec.
```

I have executed this command and it is ok now.

**Comment by den-crane** [comment]
Mutations is not supposed to used on daily basis. It should be rare admin operations.
Check that a mutation is_done before run a next one.

**Comment by wangzhen11aaa** [comment]
> Mutations is not supposed to used on daily basis. It should be rare admin operations.
> Check that a mutation is_done before run a next one.

Thanks very much , you guys.
