### ISSUE TITLE
jdbc bridge password error

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#8461]
report ：
HTTP status code: 500 Server Error, body: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 193, host: 192.168.10.18, port: 8123; Code: 193, e.displayText() = DB::Exception: Wrong password for user root (version 19.16.2.2 (official build))

the password contains Special symbol

**Comment by ShadowDAssange** [comment]
I have resolved the question.
https://stackoverflow.com/questions/59518102/clickhouse-create-jdbc-engine-table/59523918#59523918

**Comment by filimonov** [comment]
Documentation should be fixed. Maybe test should be added (if absent)

**Comment by blinkov** [comment]
@ShadowDAssange, do you have any further questions?
