### ISSUE TITLE
Exposing Clickhouse to the Internet- Direct User Read Only Access?

### ISSUE THREAD

**Issue by volfco** [ClickHouse/ClickHouse#8466]
I'm considering exposing ClickHouse directly to the internet (via a proxy) so I can provide my users direct access to ClickHouse for visualizations (and to save work on building an API layer). If I do this, I would dynamically generate a users.xml file for each tenant in my system, restricting them to only view records attached to their account ID.

Is this idea insane to be considering? The accounts would be limited to read only, and would be restricted further by quotas and table filters.

**Comment by hczhcz** [comment]
Running untrusted SQL code is generally not safe.

Two possible ideas:
* Give each user an isolated ClickHouse instance
* Reconstruct a restricted query from the user's input

**Comment by pachico** [comment]
Have a look at chproxy, you won't need to expose real ch users and you can set rate limits too.

**Comment by volfco** [comment]
@pachico It looks like chproxy can be used in conjunction with clickhouse user filtering. It doesn't look like chproxy can restrict or filter data?

**Comment by pachico** [comment]
No, not in chproxy but, depending on what you mean by restricting or filtering data, you can do it in CH.
So yes, it seems like a combination of the two might be what you need.

**Comment by volfco** [comment]
Cool. I'll poke around and see how it works. If I could expose Clickhouse semi-directly to the user then that drastically reduces complexity of my system.

**Comment by pachico** [comment]
This is exactly what we do.
We use chproxy for:
- roundrobin between all nodes (it performs healthcheck to point only to healthy ones, which was our first and original reason to adopt it)
- avoid exposing internal credentials 
- apply rate limit

**Comment by blinkov** [comment]
@volfco, do you have any further questions?
