### ISSUE TITLE
create table and load data

### ISSUE THREAD

**Issue by rogerlzp** [ClickHouse/ClickHouse#8468]
hey, I failed in create table and load data with engine mergetree.
The version is mergetree 19.17.5.18 

tdh2 :)  CREATE TABLE report.rpt_market_kpi_mergetree3(id UInt16, `data_date` Nullable(String), `chnl_area` Nullable(String), `econcontr_xy` Nullable(String), `econcontr_sp` Nullable(String), `econcontr_xy_up` Nullable(String), `econcontr_sp_up` Nullable(String), `chnl_type` Nullable(String), `prov` Nullable(String), `chnl_name` Nullable(String), `ta_acct` Nullable(String), `net_name` Nullable(String), `fund_type` Nullable(String), `fund_name` Nullable(String), `amt` Nullable(String), `mgtfee` Nullable(String), `mgtfee_nav` Nullable(String), `mgtfee_nav_new` Nullable(String), `pur_amount` Nullable(String), `buy_amount` Nullable(String), `redeem_amount` Nullable(String), `sell_amount` Nullable(String), `pur_amount_nav` Nullable(String), `hdatasign` Nullable(String), `hloadtime` Nullable(String), `hbatchdate` Nullable(String), `hdatasrc` Nullable(String), `parmonth` Nullable(String), `create_date` Date) \
:-]  ENGINE = MergeTree \
:-]  ORDER BY id \
:-]  PRIMARY KEY id  \
:-]  AS \
:-] SELECT * FROM   \
:-] FROM mysql('172.30.83.201:3316', 'workflow_workflow3', 'rpt_market_kpi3', 'hbxyquery', 'hbxyquery');

Syntax error: failed at position 963 (line 5, col 2):

 CREATE TABLE report.rpt_market_kpi_mergetree3(id UInt16, `data_date` Nullable(String), `chnl_area` Nullable(String), `econcontr_xy` Nullable(String), `econcontr_sp` Nullable(String), `econcontr_xy_up` Nullable(String), `econcontr_sp_up` Nullable(String), `chnl_type` Nullable(String), `prov` Nullable(String), `chnl_name` Nullable(String), `ta_acct` Nullable(String), `net_name` Nullable(String), `fund_type` Nullable(String), `fund_name` Nullable(String), `amt` Nullable(String), `mgtfee` Nullable(String), `mgtfee_nav` Nullable(String), `mgtfee_nav_new` Nullable(String), `pur_amount` Nullable(String), `buy_amount` Nullable(String), `redeem_amount` Nullable(String), `sell_amount` Nullable(String), `pur_amount_nav` Nullable(String), `hdatasign` Nullable(String), `hloadtime` Nullable(String), `hbatchdate` Nullable(String), `hdatasrc` Nullable(String), `parmonth` Nullable(String), `create_date` Date) 
 ENGINE = MergeTree 
 ORDER BY id 
 PRIMARY KEY id  
 AS 
SELECT * FROM   
FROM mysql('172.30.83.201:3316', 'workflow_workflow3', 'rpt_market_kpi3', 'hbxyquery', 'hbxyquery');

Expected one of: NOT, SETTINGS, FORMAT, LIKE, AND, OR, IN, BETWEEN, TTL, token, IS, NOT LIKE, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark, PARTITION BY, SAMPLE BY, INTO OUTFILE

I can't find what needs to be specified from the log.
It succeed when I create a table with engine = Log.
However, I have tried many times with different options to create a table with engine mergetree, failed always.

from the doc:
CREATE TABLE [IF NOT EXISTS] [db.]table_name [ON CLUSTER cluster]
(
    name1 [type1] [DEFAULT|MATERIALIZED|ALIAS expr1] [TTL expr1],
    name2 [type2] [DEFAULT|MATERIALIZED|ALIAS expr2] [TTL expr2],
    ...
    INDEX index_name1 expr1 TYPE type1(...) GRANULARITY value1,
    INDEX index_name2 expr2 TYPE type2(...) GRANULARITY value2
) ENGINE = MergeTree()
[PARTITION BY expr]
[ORDER BY expr]
[PRIMARY KEY expr]
[SAMPLE BY expr]
[TTL expr [DELETE|TO DISK 'xxx'|TO VOLUME 'xxx'], ...]
[SETTINGS name=value, ...]

Could you please give me more details on which parameters are exactly needed, and which can be skipped?

Thanks,
Roger

**Comment by cliicy** [comment]
I encountered the same error.
