### ISSUE TITLE
Insert into from MySQL tables doesn't work when column is nullable

### ISSUE THREAD

**Issue by 272029252** [ClickHouse/ClickHouse#8471]
**Describe the bug or unexpected behaviour**
Insert into from MySQL tables doesn't work when column is nullable type and mysql value is NULL
 i get error msg
**How to reproduce**
  mysql table is:
  ```
CREATE TABLE test_mysql (
  id int(11) unsigned NOT NULL AUTO_INCREMENT,
  name varchar(20) NOT NULL,
  a decimal(10,2) DEFAULT NULL,
  b decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (id)
 ) ENGINE=InnoDB ;
```

- 
id  | name | a | b
---|---- | -----|----
 1  | jane |9.03| |
 2  | jack |8.03| |

  clickhouse table use ReplacingMergeTree engine,when i insert data use sql:
`INSERT INTO test_clickhouse SELECT * FROM mysql('127.0.0.1:3306', 'test', 'test_mysql', 'admin', '123456')`

is error:
 DB::Exception: Attempt to read after eof: while converting source column a to destination column b.

is ok:
`INSERT INTO(id,name,a) test_clickhouse SELECT id,name,a FROM mysql('127.0.0.1:3306', 'test', 'test_mysql', 'admin', '123456')`

* Which ClickHouse server version to use
  version 19.17.6

**Comment by filimonov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/7690
