### ISSUE TITLE
replicate error

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#8473]
on slave's log:
HTTP status code: 500 Internal Server Error, body: Code: 221, e.displayText() = DB::Exception: No interserver IO endpoint named DataPartsExchange:/clickhouse/tables/.../master

**Comment by ShadowDAssange** [comment]
sorry，Wrong configure

**Comment by beartom** [comment]
I got the same error. Could you please share what configuration is wrong?

**Comment by beartom** [comment]
> I got the same error. Could you please share what configuration is wrong?

I found out the wrong configuration my self. Value of Interserver_http_host in one of cluster node is wrong.

**Comment by ShanQincheng** [comment]
My situation is  two replica machine has **the same hostname**

We need to modify the setting in **config.xml**

make the **<interserver_http_host> be unique** in each machine on cluster.
