### ISSUE TITLE
The same sql returns Inconsistent result

### ISSUE THREAD

**Issue by wsxGit** [ClickHouse/ClickHouse#8488]
We have a distributed table, and occasionally the same sql statement appears with inconsistent results.
example:
first execute sql
sql : select count() from tables where toYYYYMMDD(time) = 20191212
result : count() 1500

seconf execute sql
sql : select count() from tables where toYYYYMMDD(time) = 20191212
result : count() 600

But after some time executing the same sql，result is 1500

**Comment by den-crane** [comment]
I believe your cluster is misconfigured. 

Please provide XML with remote_servers and show create table for your Distributed table.
select count() from shard_table from each node (replica/shard)

**Comment by wsxGit** [comment]
### config.xml
`<?xml version="1.0"?>



<yandex>

  <remote_servers>

    <cluster_uom_alert>

      <shard>

        <internal_replication>true</internal_replication>

        <replica>

          <host>10.230.226.16</host>

          <port>9000</port>

        </replica>

        <replica>

          <host>10.230.226.17</host>

          <port>9000</port>

        </replica>

      </shard>

      <shard>

        <internal_replication>true</internal_replication>

        <replica>

          <host>10.230.226.18</host>

          <port>9000</port>

        </replica>

        <replica>

          <host>10.230.226.19</host>

          <port>9000</port>

        </replica>

      </shard>

      <shard>

        <internal_replication>true</internal_replication>

        <replica>

          <host>10.230.226.20</host>

          <port>9000</port>

        </replica>

        <replica>

          <host>10.230.226.21</host>

          <port>9000</port>

        </replica>

      </shard>

      <shard>

        <internal_replication>true</internal_replication>

        <replica>

          <host>10.230.226.22</host>

          <port>9000</port>

        </replica>

        <replica>

          <host>10.230.226.23</host>

          <port>9000</port>

        </replica>

      </shard>

      <shard>

        <internal_replication>true</internal_replication>

        <replica>

          <host>10.230.226.24</host>

          <port>9000</port>

        </replica>

        <replica>

          <host>10.230.226.25</host>

          <port>9000</port>

        </replica>

      </shard>

    </cluster_uom_alert>

  </remote_servers>

</yandex>`
### ddl is
` CREATE TABLE alert.alert_f6def94016754e27bde1e3dad39a2013_all ( processTime DateTime,  dataSource String,  interface_code String,  idc_id String,  window_start_time DateTime,  avg_time_consuming String,  fail_num String,  num String) ENGINE = Distributed(cluster_uom_alert, 'alert', 'alert_f6def94016754e27bde1e3dad39a2013', rand())`
### shard_table
` CREATE TABLE alert.alert_f6def94016754e27bde1e3dad39a2013 ( processTime DateTime,  dataSource String,  interface_code String,  idc_id String,  window_start_time DateTime,  avg_time_consuming String,  fail_num String,  num String) ENGINE = ReplicatedMergeTree('/clickhouse/cluster_uom_alert/alert/alert_f6def94016754e27bde1e3dad39a2013/{shard_alert}', '{replica_alert}') PARTITION BY toYYYYMMDD(window_start_time) ORDER BY window_start_time SETTINGS index_granularity = 8192`

**Comment by wsxGit** [comment]
other config
`Node 226.16
<yandex>
  <macros>
    <replica>01</replica>
    <shard>01</shard>
    <replica_alert>01</replica_alert>
    <shard_alert>01</shard_alert>
  </macros>
</yandex>
Node:226.17
<yandex>
  <macros>
    <replica>02</replica>
    <shard>01</shard>
    <replica_alert>02</replica_alert>
    <shard_alert>01</shard_alert>
  </macros>
</yandex>
Node:226.18
<yandex>
  <macros>
    <replica>01</replica>
    <shard>02</shard>
    <replica_alert>01</replica_alert>
    <shard_alert>02</shard_alert>
  </macros>
</yandex>
Node:226.19
<yandex>
  <macros>
    <replica>02</replica>
    <shard>02</shard>
    <replica_alert>02</replica_alert>
    <shard_alert>02</shard_alert>
  </macros>
</yandex>
Node:226.20
<yandex>
  <macros>
    <replica>01</replica>
    <shard>03</shard>
    <replica_alert>01</replica_alert>
    <shard_alert>03</shard_alert>
  </macros>
</yandex>
Node:226.21
<yandex>
  <macros>
    <replica>02</replica>
    <shard>03</shard>
    <replica_alert>02</replica_alert>
    <shard_alert>03</shard_alert>
  </macros>
</yandex>
Node:226.22
<yandex>
  <macros>
    <replica>01</replica>
    <shard>01</shard>
    <replica_alert>01</replica_alert>
    <shard_alert>04</shard_alert>
    <replica_ares>01</replica_ares>
    <shard_ares>01</shard_ares>
<shard_ares2>01</shard_ares2>
<replica_ares2>01</replica_ares2>
  </macros>
</yandex>
Node:226.23
<yandex>
  <macros>
    <replica>03</replica>
    <shard>01</shard>
    <replica_alert>02</replica_alert>
    <shard_alert>04</shard_alert>
    <replica_ares>02</replica_ares>
    <shard_ares>01</shard_ares>

<shard_ares2>02</shard_ares2>
<replica_ares2>01</replica_ares2>

  </macros>
</yandex>
Node:226.24
<yandex>
  <macros>
    <replica>03</replica>
    <shard>02</shard>
    <replica_alert>01</replica_alert>
    <shard_alert>05</shard_alert>
    <replica_ares>01</replica_ares>
    <shard_ares>02</shard_ares>


<shard_ares2>03</shard_ares2>
<replica_ares2>01</replica_ares2>

  </macros>
</yandex>
Node:226.25
<yandex>
  <macros>
    <replica>03</replica>
    <shard>03</shard>
    <replica_alert>02</replica_alert>
    <shard_alert>05</shard_alert>
    <replica_ares>02</replica_ares>
    <shard_ares>02</shard_ares>

<shard_ares2>04</shard_ares2>
<replica_ares2>01</replica_ares2>

  </macros>
</yandex>`

**Comment by den-crane** [comment]
try to run several times 
```
select count(), hostName() 
from tables where toYYYYMMDD(time) = 20191212
group by hostName()
```
to get the difference, what nodes how many rows return

**Comment by wsxGit** [comment]
after run several times
`select count(), hostName() 
from tables where toYYYYMMDD(time) = 20191212
group by hostName()`
We found that the results of the two nodes **10.230.226.20** and **10.230.226.21** were **inconsistent**, 
but they were executed again **one minute later** and the results were **consistent**.

**Comment by den-crane** [comment]
10.230.226.20, 10.230.226.21 are replicas in the same shard so it's a replication delay because CH has eventual consistency. You can try stabilize results using load_balancing -- in_order or using quorum insert.

**Comment by wsxGit** [comment]
execute` curl http://10.230.226.20:8123/replicas_status?verbose=1`
Some tables appear occasionally  **Absolute delay: 47. Relative delay: 0.**

**Comment by den-crane** [comment]
>Absolute delay: 47

pretty big delay, check CH logs at both replicas and network between replicas.
