### ISSUE TITLE
A "where in" test is failing without distinct

### ISSUE THREAD

**Issue by vincenzon** [ClickHouse/ClickHouse#8490]
I have a tables of the form:

- t1 with column c1 
- t2 with column c2
- t3 with column c1 and c2

and a query, Q1, of the form:

```
select c1 from t1 
where c1 in (
     select c1 from t2 left join t3 using c2
)
```
The result of Q1 did not include a value of c1 that I expected (say "x") so I ran the two parts separately in queries Q2:
```
select c1 from t1
```
and Q3:
```
select c1 from t2 left join t3 using c2
```
both of Q2 and Q3 included the expected value ("x"). 

In trying to understand what was happening, modified Q1 into Q4:
```
select c1 from t1 
where c1 in (
     select disctinct c1 from t2 left join t3 using c2
)
```
The result of that query did include the expected value "x". 

Is it required that `where in` conditions use `distinct ` in their select clauses?

If not, is there some way for me to debug why the query Q1 did not include "x" when the component queries Q2 and Q3 do, and the modified query Q4 does as well? 

Or, as is always a possibility, am I completely missing something that may explain this?

Thanks in advance for any help.

Matt

**Comment by den-crane** [comment]
Please provide 
1. ClickHouse version
2. show create table t1 / t2 / t3

**Comment by vincenzon** [comment]
@den-crane the version is: 19.17.5 revision 54428

I can't share the real tables, but edited versions are:

```
CREATE TABLE t1 (`cA` String, `c1` String)
ENGINE = MergeTree 
PARTITION BY substring(cA, 1, 7) ORDER BY (cA, c1)
SETTINGS index_granularity = 8192
```
```
CREATE TABLE t2 (`cB` String, `c2` Float64)
ENGINE = MergeTree 
PARTITION BY substring(cB, 1, 7) ORDER BY (cB, c2)
SETTINGS index_granularity = 8192
```

```
CREATE TABLE t2 (`cC` String, `c2` Float64, `c1` Nullable(String))
ENGINE = MergeTree 
PARTITION BY substring(cC, 1, 7) ORDER BY (cC, c2)
SETTINGS index_granularity = 8192
```

**Comment by den-crane** [comment]
minimal example:

```
CREATE TABLE t1 (`cA` String, `c1` String) ENGINE = MergeTree  
ORDER BY (cA, c1);
insert into t1 select 'AAAAAAAAAAA', 'BBBBBB';

for i in `seq 1 50`; do echo -n " Result: "; clickhouse-client --empty_result_for_aggregation_by_empty_set=0 -q "select count() from t1 where c1 in (select 'BBBBBB' union all select null)"; done

Result: 0
 Result: 0
 Result: 1
 Result: 1
 Result: 1
 Result: 0
 Result: 1
 Result: 1
 Result: 0
 Result: 0
 Result: 0
 Result: 0
 Result: 0
 Result: 0
 Result: 0
```

**Comment by den-crane** [comment]
@alesapin 
Seems issue related to adaptive index granularity (only for parts with .mrk2) 19.10.+

**Comment by vincenzon** [comment]
@den-crane I made the fix you suggested, where c1 is not null, and it is working. Thank you for looking into this.

**Comment by den-crane** [comment]
Could not reproduce with current stable versions. Test added.
