### ISSUE TITLE
import csv into clickhouse failed. caused by double quotes and comma

### ISSUE THREAD

**Issue by BigBig-joe** [ClickHouse/ClickHouse#8491]
Hi guys. 

I just met a awkward scenario.   here is the data flow. 
(Source) SQL Server --(SQOOP)--> HDFS  --> CLICKHOUSE(Target File(CSV))

some columns contain special characters , double quotes and comma, and I can't change the value or CSV delimiter,  as some other programs are using this file.   Here is the sqoop setting
--escaped-by \\ --enclosed-by '\"'

if I add --format_csv_allow_double_quotes=0, the comma will make columns dislocation,  if I remove the format setting, will get error by the double quotes in string, like below

> There is no delimiter (,). "-" found instead

data likes this, 
COLUMN_A : "ABC, DE" , COLUMN_B: "EF \"G\" " 

is there a way I can deal with this problem?   it has been puzzling me days, thank you so much for any help..

**Comment by den-crane** [comment]
```
"ABC, DE" , "EF "G" "
```
This is not CSV. 
```
COLUMN_A : "ABC, DE" , COLUMN_B: "EF "G" "
```
This is also not CSV.
You should either change delimiter to not comma or quoting not to double quotes.

--format_csv_delimiter 
--format_csv_allow_single_quotes
--format_csv_allow_double_quotes

**Comment by BigBig-joe** [comment]
> COLUMN_A : "ABC, DE" , COLUMN_B: "EF "G" "
this is what it like in table. 

yes, I tried this, but not work.   here is a data sample. 
> "9AAAAAADW5__A6BA_BARGAINS \"N\" DEALZ"

> --escaped-by \\ --enclosed-by '"'

**Comment by den-crane** [comment]
I am confused. Can you show whole row sample for 
` --escaped-by \\ --enclosed-by '"'`
and 
for `--escaped-by \" --enclosed-by '"'`

**Comment by BigBig-joe** [comment]
in sqoop cmd,  I specify escaped-by = \\ , but the first \ is the escape for the second \ . so in the file, data shows like 

> "9AAAAAADW5__A6BA_BARGAINS \"N\" DEALZ"

the test data looks like below

> "Regular","No","Domestic Inc, seller","BARGAINS \\"N\\" DEALZ"

**Comment by den-crane** [comment]
Not a CH issue. This is not CSV. 
CH able supports CSV with any delimiter and with string quoting by " or ' with escaping by the quote with same quote type ( `aaaa|"sdfsdfsdfd""fsdsf"|"sdfsd" ).

**Comment by BigBig-joe** [comment]
Sorry to reply so late as on a leave yesterday. 

I think I can use the customize delimiter instead.  but, how to use the custom format settings?  I tried like this, but not work. does I get something wrong? 
`clickhouse-client --format_custom_field_delimiter='||'  --query="INSERT INTO default.File_Q_salesorderdetail_Combine_ForDruid_Current FORMAT CSV" < V_Q_InvoiceDetail_Combine_ForDruid_Current.csv`

**Comment by den-crane** [comment]
`--format_csv_delimiter`
```
create table Y(A String, B String) Engine=Memory;

=> cat text.csv
aaaa|bbb
"ffff""x"|'dfdf'ff'''fff

=> cat text.csv |clickhouse-client --format_csv_delimiter='|' --format_csv_allow_single_quotes=0 -q "insert into Y format CSV"

select * from Y;

┌─A──────┬─B──────────────┐
│ aaaa   │ bbb            │
│ ffff"x │ 'dfdf'ff'''fff │
└────────┴────────────────┘

```
