### ISSUE TITLE
Make JDBC/ODBC bridge more generic

### ISSUE THREAD

**Issue by zhicwu** [ClickHouse/ClickHouse#8492]
It's a great feature to connect external datasources via JDBC/ODBC. However, this is currently limited to table/view, which is inconvenient sometimes especially when you're not allowed to create view on external database. Would you please consider to enhance the implementation(and maybe the protocol) to make it more generic to cover scenarios like followings?
1) adhoc query
    ```sql
    select * from jdbc('datasource://some-db', '', 
        'select * from some_table order by created desc limit 10')
    ```
2) query parameters
    ```sql
    select * from jdbc('datasource://some-db?max_rows=1000&fetch_size=1000', '', 
        'select * from some_table order by created desc')
    ```
3) message queue
    ```sql
    select * from mq('datasource://some-mq?fetch_size=10', '', 'some-queue')
    ```
4) graphql
    ```sql
    select * from gql('http://some-url', '', 'query q{ some-field }')
    ```
5) streams like flink
    ```sql
    select * from stream('flink://some-url', '', 'some-job')
    ```

**Comment by ramazanpolat** [comment]
> 1. adhoc query
>    ```sql
>    select * from jdbc('datasource://some-db', '', 
>        'select * from some_table order by created desc limit 10')
>    ```

Why not using the following way?
```sql
select * from jdbc('datasource://some-db', '', 'some_table') order by created desc limit 10 
```

**Comment by zhicwu** [comment]
Thanks @ramazanpolat, it works for sure when the table is small(e.g. less than 1m rows?). However, it's not in our case since  push-down is not supported at this point. Also please excuse my bad example, adhoc query is usually more complex(e.g. with table joins or aggregations etc.).

**Comment by zhicwu** [comment]
FYI, I created a repo at https://github.com/zhicwu/clickhouse-datasource-bridge to demonstrate my thoughts. Will add more after holidays.

**Comment by zhicwu** [comment]
Close the issue as I'm happy with the custom jdbc-bridge implementation :)
