### ISSUE TITLE
 Get dictionary table data, the dictionary table source data is materialized view

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#8498]
My dictionary table is a materialized view. How can I achieve aggregation when accessing data?

Materialized view：
CREATE MATERIALIZED VIEW ptx_db.vor_xc_order_item_years ENGINE = AggregatingMergeTree PARTITION BY toYYYYMM(pay_nextyear)
ORDER BY (pay_nextyear, sku, account, country, asin, company_sku) SETTINGS index_granularity = 8192 populate AS 
SELECT
	toDate(purchase_date) as pay_nextyear,
	sumState(amount) AS yt_sum_amount,
	count(amazon_order_id) AS yt_order_num,
	any(rate) AS yt_rate,
	three_category_code,
	sku,
	account,
	country,
	asin,
	company_sku
FROM
	db1.or_xc_order_item
WHERE    (or_xc_order_item.order_status != 'Canceled')
GROUP BY
	pay_nextyear,
	sku,
	account,
	country,
	asin,
	company_sku,
	three_category_code;

Dictionary table configuration：
<yandex>
	<dictionary>
		<name>dim_order_item_year</name>
		<source>
			<clickhouse>
				<host>192.168.1.155</host>
				<port>9000</port>
				<user>XXX</user>
				<password>XXX</password>
				<db>db1</db>
				<table>vor_xc_order_item_years</table>
			</clickhouse>
		</source>
		<lifetime>
			<min>300</min>
			<max>360</max>
		</lifetime>
		<layout>
			<complex_key_hashed/>
		</layout>
		<structure>
			<key>
				<attribute>
					<name>sku</name>
					<type>String</type>
					<null_value>未知</null_value>
				</attribute>
				<attribute>
					<name>account</name>
					<type>String</type>
					<null_value>未知</null_value>
				</attribute>
				<attribute>
					<name>country</name>
					<type>String</type>
					<null_value>未知</null_value>
				</attribute>
				<attribute>
					<name>asin</name>
					<type>String</type>
					<null_value>未知</null_value>
				</attribute>
				<attribute>
					<name>company_sku</name>
					<type>String</type>
					<null_value>未知</null_value>
				</attribute>
				<attribute>
					<name>three_category_code</name>
					<type>String</type>
					<null_value>未知</null_value>
				</attribute>    
                                <attribute>
                                        <name>pay_nextyear</name>
                                        <type>Date</type>
                                        <null_value>0</null_value>
                                </attribute>
			</key>
			<attribute>
				<name>yt_sum_amount</name>
				<type>Decimal64(2)</type>
				<null_value>0</null_value>
			</attribute>
		</structure>
	</dictionary>
</yandex>

Data from dictionary table：
select 
toDate(purchase_date) as pay_days,
sku,
account,
country,
asin,
company_sku,
three_category_code,
sum(amount) as curr_day_amount,
dictGet('dim_order_item_year', 'yt_sum_amount', tuple(t.sku,t.account,t.country,t.asin,t.company_sku,t.three_category_code,subtractMonths(pay_days,1))) as months_amount
from or_xc_order_item t 
where toYYYYMM(purchase_date)=201707
    and order_status != 'Canceled'
	and sku = 'TBTBPA044AS-USAA1'
	and account = 'TB'
	and country = 'US'
	and asin = 'B06XDM61W3'
	and company_sku = 'TBPA044AS'
	and three_category_code = 'PA0202'
group by 
pay_days,
sku,
account,
country,
asin,
company_sku,
three_category_code;

Unable to extract the correct value, how do I extract the data after sumMerge;
![Uploading image.png…]()

**Comment by den-crane** [comment]
Make a View. 

create view ptx_db.vor_xc_order_item_years_view as select 
pay_nextyear, sku, account, country, asin, company_sk, sumMerge....
group by ....

and use this vor_xc_order_item_years_view in your dictionary.

**Comment by leoones** [comment]
> Make a View.
> 
> create view ptx_db.vor_xc_order_item_years_view as select
> pay_nextyear, sku, account, country, asin, company_sk, sumMerge....
> group by ....
> 
> and use this vor_xc_order_item_years_view in your dictionary.


I created the view and applied it in the dictionary, but the value obtained is not what I want, similar to this value (1396393677705.20), the correct value should be the value after sumMerge

**Comment by leoones** [comment]
> > Make a View.
> > create view ptx_db.vor_xc_order_item_years_view as select
> > pay_nextyear, sku, account, country, asin, company_sk, sumMerge....
> > group by ....
> > and use this vor_xc_order_item_years_view in your dictionary.
> 
> I created the view and applied it in the dictionary, but the value obtained is not what I want, similar to this value (1396393677705.20), the correct value should be the value after sumMerge


Is your suggestion to use a normal view instead of a materialized view?

**Comment by leoones** [comment]
> Make a View.
> 
> create view ptx_db.vor_xc_order_item_years_view as select
> pay_nextyear, sku, account, country, asin, company_sk, sumMerge....
> group by ....
> 
> and use this vor_xc_order_item_years_view in your dictionary.

Thank you very much for your reply
