### ISSUE TITLE
MemoryTracker exception despite unlimited memory setting

### ISSUE THREAD

**Issue by genzgd** [ClickHouse/ClickHouse#8506]
Received the following exception multiple times during writes to a node (stack trace at end).

`B::Exception: Memory limit (total) exceeded: would use 74.51 GiB (attempt to allocate chunk of 4217732 bytes), maximum: 74.51 GiB (version 19.17.4.11) `

I can't figure out what memory limit is being exceeded.  (These errors are happening during writes).  The 74.51GiB value is not configured anywhere, and the box itself has 792G of total memory, of which we are only using a small fraction.  The only configured limit on the default profile is per query of 100GiB `max_memory_usage_per_query = 107374182400`.

These errors seem to correspond to large merges; when the merge finally completed the errors cleared up.  Is ClickHouse possibly misreading the total available system memory? 

> 0. 0x3512b60 StackTrace::StackTrace() /usr/bin/clickhouse
> 1. 0x351195e MemoryTracker::alloc(long) /usr/bin/clickhouse
> 2. 0x3510d39 MemoryTracker::alloc(long) /usr/bin/clickhouse
> 3. 0x3510d39 MemoryTracker::alloc(long) /usr/bin/clickhouse
> 4. 0x3510d39 MemoryTracker::alloc(long) /usr/bin/clickhouse
> 5. 0x3561138 DB::WriteBufferFromFileBase::WriteBufferFromFileBase(unsigned long, char*, unsigned long) /usr/bin/clickhouse
> 6. 0x35443fb DB::WriteBufferFromFileDescriptor::WriteBufferFromFileDescriptor(int, unsigned long, char*, unsigned long) /usr/bin/clickhouse
> 7. 0x6bf42bc DB::WriteBufferFromFile::WriteBufferFromFile(std::string const&, unsigned long, int, unsigned int, char*, unsigned long) /usr/bin/clickhouse
> 8. 0x6c062d6 DB::createWriteBufferFromFileBase(std::string const&, unsigned long, unsigned long, unsigned long, int, unsigned int, char*, unsigned long) /usr/bin/clickhouse
> 9. 0x696c006 DB::IMergedBlockOutputStream::ColumnStream::ColumnStream(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, unsigned long, unsigned long) /usr/bin/clickhouse
> 10. 0x696c2e1 ? /usr/bin/clickhouse
> 11. 0x696a3c3 DB::IMergedBlockOutputStream::addStreams(std::string const&, std::string const&, DB::IDataType const&, std::shared_ptr<DB::ICompressionCodec> const&, unsigned long, bool) /usr/bin/clickhouse
> 12. 0x650fc0c DB::MergedBlockOutputStream::MergedBlockOutputStream(DB::MergeTreeData&, std::string const&, DB::NamesAndTypesList const&, std::shared_ptr<DB::ICompressionCodec>, bool) /usr/bin/clickhouse
> 13. 0x64dde7f DB::MergeTreeDataWriter::writeTempPart(DB::BlockWithPartition&) /usr/bin/clickhouse
> 14. 0x651b7c4 DB::ReplicatedMergeTreeBlockOutputStream::write(DB::Block const&) /usr/bin/clickhouse
> 15. 0x67a8726 DB::PushingToViewsBlockOutputStream::write(DB::Block const&) /usr/bin/clickhouse
> 16. 0x67b3f01 DB::SquashingBlockOutputStream::finalize() /usr/bin/clickhouse
> 17. 0x67b41d1 DB::SquashingBlockOutputStream::writeSuffix() /usr/bin/clickhouse
> 18. 0x609d2a5 DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*) /usr/bin/clickhouse
> 19. 0x62d73b1 DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::string const&)>, std::function<void (std::string const&)>) /usr/bin/clickhouse
> 20. 0x359e471 DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) /usr/bin/clickhouse
> 21. 0x35a14b1 DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /usr/bin/clickhouse
> 22. 0x6dbcc59 Poco::Net::HTTPServerConnection::run() /usr/bin/clickhouse
> 23. 0x6db98bf Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
> 24. 0x6db9fb5 Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
> 25. 0x723f481 Poco::PooledThread::run() /usr/bin/clickhouse
> 26. 0x723b208 Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
> 27. 0x791d69f ? /usr/bin/clickhouse
> 28. 0x7f5f8e934dd5 start_thread /usr/lib64/libpthread-2.17.so
> 29. 0x7f5f8e459ead __clone /usr/lib64/libc-2.17.so
>

**Comment by den-crane** [comment]
There is no such parameter `max_memory_usage_per_query`

Check your settings
```
SELECT
    name,
    value
FROM system.settings
WHERE name LIKE 'max%mem%'

┌─name─────────────────────────────┬─value───────┐
│ max_memory_usage                 │ 50659012608 │
│ max_memory_usage_for_user        │ 0           │
│ max_memory_usage_for_all_queries │ 50659012608 │
└──────────────────────────────────┴─────────────┘
```

**Comment by genzgd** [comment]
Sorry, I was thinking of it as max_memory_usage "per_query" since that's how it's referenced in the documentation and in error logs:

```
SELECT 
    name, 
    value
FROM system.settings
WHERE name LIKE 'max%mem%'

┌─name─────────────────────────────┬─value────────┐
│ max_memory_usage                 │ 107374182400 │
│ max_memory_usage_for_user        │ 0            │
│ max_memory_usage_for_all_queries │ 0            │
└──────────────────────────────────┴──────────────┘

3 rows in set. Elapsed: 0.002 sec. ```

**Comment by genzgd** [comment]
To be clear, I assumed that settings was not being referenced, since error messages for that setting look like `Memory limit (for query) exceeded`, not `Memory limit (total) exceeded`.  Examples of the "total" memory limit being exceeded are very rare based on my Google search.

**Comment by den-crane** [comment]
>B::Exception: Memory limit (total) exceeded: would use 74.51 GiB (attempt to allocate chunk of >4217732 bytes), maximum: 74.51 GiB (version 19.17.4.11) 

**(total) exceeded**
It could be a problem from other sessions which set max_memory_usage_for_all_queries=74GB because CH has an issue with `max_memory_usage_for_all_queries`

**Comment by genzgd** [comment]
That actually looks like the problem, we do have a different profile which just happens to have a 74.51 GB setting for that `max_memory_usage_for_all_queries` setting.  Do you have a link to that issue you mentioned.

**Comment by den-crane** [comment]
I don't remember the issue number.

STR:

```
for i in `seq 1 5000`; do echo -n " Result: "; clickhouse-client --max_memory_usage_for_all_queries=10000 -q "select sleep(1)"; done

clickhouse-client --max_memory_usage_for_all_queries=0 --max_memory_usage=0 --max_memory_usage_for_user=0 -q "create table X Engine=Memory as select * from numbers(10000000000);"
Received exception from server (version 19.17.5):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded: would use 4.00 MiB (attempt to allocate chunk of 4195072 bytes), maximum: 97.66 KiB.

```

**Comment by genzgd** [comment]
Will do,thanks so much!
