### ISSUE TITLE
About MATERIALIZED VIEW on AggregatingMergeTree

### ISSUE THREAD

**Issue by jencoldeng** [ClickHouse/ClickHouse#8509]
My Table in ClickHouse is like this:
-------------------------
## local table
CREATE TABLE IF NOT EXISTS dataDate201912_local (
  statdate Date,
  stattime DateTime,
  ip UInt32,
  domain String,
  type UInt8,
  flow UInt64,
  request UInt64,
)
ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/dataDate201912/{shard}', '{replica}')
PARTITION BY statdate 
ORDER BY (statdate,stattime,ip,domain,type)
SETTINGS index_granularity = 8192;

## distribute table
CREATE TABLE dataDate201912 AS dataDate201912_local
ENGINE = Distributed(kstat_shard, currentDatabase(), dataDate201912_local, intHash32(stattime));

##local table: summary by date-domain
CREATE MATERIALIZED VIEW IF NOT EXISTS dataMonth201912_local
ENGINE = AggregatingMergeTree() 
ORDER BY (statdate,ip,idcid,domain,type)
POPULATE AS SELECT
  statdate,
  ip,
  domain,
  type,
  maxState(flow) as flow,
  sumState(request) as request
FROM kstat.dataDate201912_local
group by statdate,ip,idcid,domain,type;

## distribute table 
CREATE TABLE dataMonth201912 AS dataMonth201912_local
ENGINE = Distributed(kstat_shard, currentDatabase(), dataDate201912_local, rand());
-------------------------

I inserted data to distribute table dataDate201912, and I want to get daily summary data juest like this two ways, I expected the results of the following two SQLs are the same:
--------------
select maxMerge(flow) as peek_flow, sumMerge(request) as sum_request
from dataMonth201912
where statdate='2019-12-30'
and ip=12345
and type=0
and domain='aaa.example.net';

select max(flow) as peek_flow ,sum(request) as sum_request
from kstat.dataDate201912
where statdate='2019-12-30'
and ip=12345
and type=0
and domain='aaa.example.net';
--------------

But the result is that, [sum_request] is correct, and [peek_flow] is not right. 
Can you tell me, is there anything wrong in the MATERIALIZED VIEW ?

**Comment by den-crane** [comment]
Your SummingMergeTree sums flow column, but AggregatingMergeTree calcs max.

Not really sure what you wanted to achieve here. You can calculate maxState in SummingMergeTree as well.

**Comment by jencoldeng** [comment]
> Your SummingMergeTree sums flow column, but AggregatingMergeTree calcs max.
> 
> Not really sure what you wanted to achieve here. You can calculate maxState in SummingMergeTree as well.

In [Date] table dataDate201912 , I want to summary the result of dimensions. 
For example, when ip="192.168.0.2" and domain="www.example.com", that row is the detail data.
when ip=0 and domain="www.example.com", the row is the totally [request] and [flow] of current domain in specified minute time.

so, in [Month] table dataMonth201912, I want to calculate the max flow and the totally request count of that day of each dimensions, such as ip, domain.

**Comment by den-crane** [comment]
>Not really sure what you wanted to achieve here.

I meant this:

```
CREATE TABLE IF NOT EXISTS dataDate201912_local (
statdate Date,stattime DateTime,ip UInt32,domain String,type UInt8,flow UInt64,request UInt64) 
ENGINE = SummingMergeTree PARTITION BY statdate ORDER BY (statdate,stattime,ip,domain,type);

insert into dataDate201912_local values 
('2019-12-01', '2019-12-01 00:00:00', 111, 'mydomain', 0, 1, 1),
('2019-12-01', '2019-12-01 00:00:00', 111, 'mydomain', 0, 1, 1),
('2019-12-01', '2019-12-01 00:00:00', 111, 'mydomain', 0, 100, 1);

SELECT
    max(flow) AS peek_flow,
    sum(request) AS sum_request
FROM dataDate201912_local
WHERE (statdate = '2019-12-01') AND (ip = 111) AND (type = 0) AND (domain = 'mydomain')

┌─peek_flow─┬─sum_request─┐
│       100 │           3 │
└───────────┴─────────────┘

OPTIMIZE TABLE dataDate201912_local FINAL

The same query different result, after a merge.

SELECT
    max(flow) AS peek_flow,
    sum(request) AS sum_request
FROM dataDate201912_local
WHERE (statdate = '2019-12-01') AND (ip = 111) AND (type = 0) AND (domain = 'mydomain')

┌─peek_flow─┬─sum_request─┐
│       102 │           3 │
└───────────┴─────────────┘

```
