### ISSUE TITLE
with a same query sql clickhouse returns different results

### ISSUE THREAD

**Issue by laoduo** [ClickHouse/ClickHouse#8510]
ClickHouse server version is 19.3.5

I have a distributed table:
CREATE TABLE db1.login_info (`ds` DateTime,` dataSource` String, ...)
ENGINE = ReplicatedMergeTree ('/ clickhouse / cluster / xxx / {shard}', '{replica}')
PARTITION BY toYYYYMMDD (ds) ORDER BY (ds)
SETTINGS index_granularity = 8192

The cluster has a total of 6 nodes (configured as 3 shard * 2 replica). The data ingest frequency is about write once per second to the cluster, with 1 record at a time. The "ds" field is basically near real-time.
The query sql is:
select count () from db1.login_info_distributed where ds>=toStartOfMinute(addMinutes(now(), -5)) and ds<toStartOfMinute(addMinutes(now(), -4))

So the problem is: the result of the same query sql may be unstable, sometimes the query result is displayed as 58, sometimes the result is 63, and so on ...
It seems the internal data synchronization takes too long,Is this related to data replication ? 

Added: 
max_replica_delay_for_distributed_queries parameter is 300s by default and has been modified to 60s.

**Comment by den-crane** [comment]
check this issue https://github.com/ClickHouse/ClickHouse/issues/8488#issuecomment-570436720

**Comment by laoduo** [comment]
It's indeed a same question.
