### ISSUE TITLE
how to config disks and policies

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#8512]
<disks>
       <data1>
            <path>/data1/clickhouse/data</path>
        </data1>
        <data>
            <path>/data/ck9099/data</path>
        </data>
    </disks>
    <path>/data1/clickhouse/data/</path>
in config.xml  then restart clickhouse-server
but there is a default  disk  in system.disks table

click_001018 :) select * from disks;

SELECT *
FROM disks

┌─name────┬─path────────────────────┬───free_space─┬───total_space─┬─keep_free_space─┐
│ default │ /data1/clickhouse/data/ │ 498028355584 │ 1538696589312 │               0 │
└─────────┴─────────────────────────┴──────────────┴───────────────┴─────────────────┘

1 rows in set. Elapsed: 0.002 sec.

**Comment by den-crane** [comment]
You missed `storage_configuration` tag.
```
<storage_configuration> 
   <disks>
   ....
   </disks>
</storage_configuration>
```

https://github.com/ClickHouse/ClickHouse/blob/master/dbms/tests/integration/test_ttl_move/configs/config.d/storage_configuration.xml
