### ISSUE TITLE
Crash ClickHouse after implement test with SimpleAggregateFunction

### ISSUE THREAD

**Issue by SergioSafonov** [ClickHouse/ClickHouse#8515]
After run "as is" sample code:
[00915_simple_aggregate_function.sql](https://github.com/yandex/ClickHouse/blob/master/dbms/tests/queries/0_stateless/00915_simple_aggregate_function.sql)
ClickHouse become crash and recover regularly after attempt to merge **test.simple** table (from example script). 
In `system.merges` we always see 1 rows with **test.simple**. 
Running command `System stop merges` cannot help. 
Also not possible drop table **test.simple**. 
ClickHouse 19.13.1.11
Logs and failed data files in attachments
[test.tar.gz](https://github.com/ClickHouse/ClickHouse/files/4019086/test.tar.gz)
[clickhouse-server.err.txt](https://github.com/ClickHouse/ClickHouse/files/4019088/clickhouse-server.err.txt)

**Comment by azat** [comment]
>After run "as is" sample code:
> 00915_simple_aggregate_function.sql

I guess you really means at least [this version](https://github.com/ClickHouse/ClickHouse/blob/458f596e187c75c4e77669bfc0831cfe20b3b986/dbms/tests/queries/0_stateless/00915_simple_aggregate_function.sql) (since in #8485 support for `groupBit*` added).

*P.S. when you are copying URLs to the files, press `y` before and the URL will be expanded to canonical form, i.e. will contain full sha over just ref name, which will be updated later*

> ClickHouse 19.13.1.11

I though that this can be related to #5311, but 19.13.1.11 definitely contains this patch.

Anyway I tried to reproduce this, and can't using:
- `yandex/clickhouse-server:19.13.1.11` docker image
- and the test from the repo (withoout #8485)

**Comment by azat** [comment]
I don't know why this tests makes the problem for you without any changes, but if you add `OPTIMIZE TABLE simple FINAL` before final `DROP TABLE simple` it will trigger the issue.

**Comment by azat** [comment]
And this is not related only to `SimpleAggregateFunction` but to `LowCardinality(Nullable())`

**Comment by den-crane** [comment]
The issue is not in the 00915_simple_aggregate_function.sql
I suspect (from previous conversation in telegram) that Sergio executed the 00915_simple_aggregate_function.sql (without drop part) at his production server and left the table. After some time CH started to merge it and caught crash-loop.

**Comment by azat** [comment]
>(without drop table part) at his production server and left the table.

Indeed, and now this makes sense

**Comment by azat** [comment]
>And this is not related only to SimpleAggregateFunction but to LowCardinality(Nullable())

Ignore this, this is only within `SimpleAggregateFunction`

**Comment by azat** [comment]
> alexey-milovidov added the obsolete version label 

This is reproduced even using version from upstream

AFAICS the problem is that output stream has `LowCardinality(Nullable())` while the input stream has `Nullable()` due to stripped `LowCardinality` in `AggregatingSortedBlockInputStream` (`RemovingLowCardinalityBlockInputStream`)

**Comment by azat** [comment]
At first glance - #8522

**Comment by SergioSafonov** [comment]
> The issue is not in the 00915_simple_aggregate_function.sql
> I suspect (from previous conversation in telegram) that Sergio executed the 00915_simple_aggregate_function.sql (without drop table part) at his production server and left the table. After some time CH started to merge it and caught crash-loop.

Exactly
