### ISSUE TITLE
hdfs engine exception

### ISSUE THREAD

**Issue by aa8808021** [ClickHouse/ClickHouse#8525]
Hi:
I created a XXX _HDFS HDFS engine table,  Execute the following statement: insert into XXX (key...) select key... From XXX _HDFS, with the following exception:

2020.01.04 05:28:35.141518 [ 379 ] {90a86a21-7ef2-4e29-b16c-fa563a84e528} <Error> executeQuery: Code: 210, e.displayText() = DB::Exception: Fail to read HDFS file: hdfs://myuser@IP::PORT/user/hive
/warehouse/mydb.db/my_table_tsv/000007_0 HdfsIOException: InputStreamImpl: cannot read file: /user/hive/warehouse/mydb.db/mytable_tsv/000007_0, from position 0, size: 1048576. Caused by: HdfsTimeoutException: Read 8 bytes timeout (version 19.16.4.12 (official build)) (from [::ffff:30.18.54.105]:38882) (in query: insert into

。。。

Stack trace:

0. 0x55a39713fed0 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x55a39713fca5 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x55a396fb534d ? /usr/bin/clickhouse
3. 0x55a39a9228dd DB::CSVRowInputFormat::readPrefix() /usr/bin/clickhouse
4. 0x55a39ad2642b DB::IRowInputFormat::generate() /usr/bin/clickhouse
5. 0x55a39a8f5dde DB::ISource::work() /usr/bin/clickhouse
6. 0x55a39a8d1385 DB::InputStreamFromInputFormat::readImpl() /usr/bin/clickhouse
7. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
8. 0x55a398db4e98 DB::OwningBlockInputStream<DB::ReadBuffer>::readImpl() /usr/bin/clickhouse
9. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
10. 0x55a39a6c8f98 ? /usr/bin/clickhouse
11. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
12. 0x55a39aa83efb DB::ExpressionBlockInputStream::readImpl() /usr/bin/clickhouse
13. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
14. 0x55a39aa83efb DB::ExpressionBlockInputStream::readImpl() /usr/bin/clickhouse
15. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
16. 0x55a39a4ca3b2 DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::loop(unsigned long) /usr/bin/clickhouse
17. 0x55a39a4caa75 DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long) /usr/bin/clickhouse
18. 0x55a39a4cb3ed ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::*)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>*, std::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::*&&)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>*&&, std::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::{lambda()#1}::operator()() const /usr/bin/clickhouse
19. 0x55a39718a47c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
20. 0x55a39cea6460 ? /usr/bin/clickhouse
21. 0x7efcdf5ea6ba start_thread /lib/x86_64-linux-gnu/libpthread-2.23.so
22. 0x7efcdef1482d __clone /lib/x86_64-linux-gnu/libc-2.23.so

2020.01.04 05:28:36.088689 [ 379 ] {90a86a21-7ef2-4e29-b16c-fa563a84e528} <Error> HTTPHandler: Code: 210, e.displayText() = DB::Exception: Fail to read HDFS file: hdfs://user@IP:PORT/user/hive/warehouse/ mydb.db/my_table_tsv 000007_0 HdfsIOException: InputStreamImpl: cannot read file: /user/hive/warehouse/ mydb.db/my_table_tsv/000007_0, from position 0, size: 1048576.  Caused by: HdfsTimeoutException: Read 8 bytes timeout, Stack trace:

0. 0x55a39713fed0 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x55a39713fca5 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x55a396fb534d ? /usr/bin/clickhouse
3. 0x55a39a9228dd DB::CSVRowInputFormat::readPrefix() /usr/bin/clickhouse
4. 0x55a39ad2642b DB::IRowInputFormat::generate() /usr/bin/clickhouse
5. 0x55a39a8f5dde DB::ISource::work() /usr/bin/clickhouse
6. 0x55a39a8d1385 DB::InputStreamFromInputFormat::readImpl() /usr/bin/clickhouse
7. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
8. 0x55a398db4e98 DB::OwningBlockInputStream<DB::ReadBuffer>::readImpl() /usr/bin/clickhouse
9. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
10. 0x55a39a6c8f98 ? /usr/bin/clickhouse
11. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
12. 0x55a39aa83efb DB::ExpressionBlockInputStream::readImpl() /usr/bin/clickhouse
13. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
14. 0x55a39aa83efb DB::ExpressionBlockInputStream::readImpl() /usr/bin/clickhouse
15. 0x55a39a3523c7 DB::IBlockInputStream::read() /usr/bin/clickhouse
16. 0x55a39a4ca3b2 DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::loop(unsigned long) /usr/bin/clickhouse
17. 0x55a39a4caa75 DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long) /usr/bin/clickhouse
18. 0x55a39a4cb3ed ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::*)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>*, std::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>::*&&)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::UnionBlockInputStream::Handler>*&&, std::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::{lambda()#1}::operator()() const /usr/bin/clickhouse
19. 0x55a39718a47c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
20. 0x55a39cea6460 ? /usr/bin/clickhouse
21. 0x7efcdf5ea6ba start_thread /lib/x86_64-linux-gnu/libpthread-2.23.so
22. 0x7efcdef1482d __clone /lib/x86_64-linux-gnu/libc-2.23.so
(version 19.16.4.12 (official build))

**Comment by alexey-milovidov** [comment]
It means that we cannot read data from HDFS data nodes. You need to check network connectivity - are data nodes accessible from ClickHouse server or they are closed by firewall.

**Comment by aa8808021** [comment]
> It means that we cannot read data from HDFS data nodes. You need to check network connectivity - are data nodes accessible from ClickHouse server or they are closed by firewall.
Ok, I'll check the Internet problem. Thanks

**Comment by aa8808021** [comment]
> It means that we cannot read data from HDFS data nodes. You need to check network connectivity - are data nodes accessible from ClickHouse server or they are closed by firewall.
hi：
In order to verify this problem, we put the server under the same computer room. This problem still occurs. I want to ask if there is a setting item that can extend the waiting timeout，thanks
