### ISSUE TITLE
The problem of using DateDiff function

### ISSUE THREAD

**Issue by 865357384** [ClickHouse/ClickHouse#8527]
Table structure：
![image](https://user-images.githubusercontent.com/24928399/71765035-64882f80-2f2a-11ea-83d6-386b1ba97109.png)

The problem is as follows：
![image](https://user-images.githubusercontent.com/24928399/71765032-589c6d80-2f2a-11ea-9f10-cc7b2b4d9b2a.png)

Add a column field：
![image](https://user-images.githubusercontent.com/24928399/71765047-94373780-2f2a-11ea-9697-8573b9ca5cef.png)

Version number：
19.15.4.10

**Comment by den-crane** [comment]
```
PREWHERE RDATE=20200104
WHERE dateDiff
```
Seems some of your RDATE columns has less than 6 digits.
WHERE conditions can be evaluated in any order.
**PREWHERE** forces to check RDATE=20200104 first

**Comment by 865357384** [comment]
thanks，My needs are solved.   But why not add columns?     In MySQL ,the statements is OK change same function.

**Comment by den-crane** [comment]
perhaps additional column changes a "query plan", and moves to prewhere different columns.

Check why the columns have less than six digits

```
select * from 
where  length(toString(RDATE)) < 6 or length(toString(PDATE))<6
limit 100
```

**Comment by 865357384** [comment]
![image](https://user-images.githubusercontent.com/24928399/71790068-791f1180-3069-11ea-999d-e4a90d9a167c.png)

the result  is  null  , I'm still very confused.

**Comment by den-crane** [comment]
oops. 20200104  - 8 digits not 6

```
select * from 
where  length(toString(RDATE)) < 8 or length(toString(PDATE))<8
limit 100
```

**Comment by 865357384** [comment]
![image](https://user-images.githubusercontent.com/24928399/71790417-51c94400-306b-11ea-85ce-b1fc165600a4.png)

Ah ha ha  ， this  is   8 result.

**Comment by den-crane** [comment]
No haha, you executed the wrong SQL.

I specifically asked about

```
select * from 
where  length(toString(RDATE)) < 8 or length(toString(PDATE))<8
limit 100
```

not about 
```
select * from 
where  length(toString(RDATE)) < 8 or length(toString(PDATE))<8
RDATE=20200104
limit 100
```

There is no order of checking conditions. 

```
SELECT *
FROM
(
    SELECT 0 AS RDATE
)
WHERE (RDATE = 20200104) AND (toDate(concat(substring(toString(RDATE), 1, 4), substring(toString(RDATE), 5, 2), substring(toString(RDATE), 7, 2))) = toDate('2020-01-04'))

Cannot parse date: value is too short: Cannot parse Date from String.
```

**Comment by 865357384** [comment]
Thank you very much.
