### ISSUE TITLE
About deleting new values every day affects performance

### ISSUE THREAD

**Issue by samz406** [ClickHouse/ClickHouse#8531]
A multi-million data table needs to delete a part of the data and add a new part every day. Will this affect the performance of ck query?

 ENGINE = MergeTree() ORDER BA_MONTH

**Comment by den-crane** [comment]
It's unclear how are you going to `delete a part`. 
In case of `alter table ... drop partition` there is no affection on performance.

**Comment by samz406** [comment]
no partition, first use ALTER TABLE table DELETE WHERE BA_MONTH='xxx', and insert data,Will this affect the performance  query?

**Comment by den-crane** [comment]
`ALTER TABLE table DELETE` is very heavy operation in comparison with `drop partition` which cases huge I/O and CPU usage. After it finishes it does not affect performance.

Consider to use `alter table ... drop partition` and table with monthly / daily partitioning. 
` drop partition` much more faster and more reliable operation.

**Comment by samz406** [comment]
ok. thank you
