### ISSUE TITLE
Read HDFS engine problem

### ISSUE THREAD

**Issue by aa8808021** [ClickHouse/ClickHouse#8543]
Hi:
I encountered the following problems when using clickhouse:
Clickhouse version: 19.16.4
Clickhouse environment configuration: 24C physical core 384G memory
I created an HDFS engine table (xxx_hdfs)
There is a table (xxx_temp) in clickhouse
I use the HDFS engine to synchronize HDFS data to the clickhouse table
The synchronized statement is: insert into xxx_temp (colnum...)The select colnum from xxx_hdfs
Data volume: 370 million
Encountered the following two problems:
Question 1:
The synchronization rate per insert select statement can only reach 500Mbps/s
Two insert selects are performed at a rate of 1000Mbps/s. Is there a limit?If there are restrictions, how can they be lifted
Question 2:
I used official JDBC to execute the SQL statement in the application. When the execution time exceeds one hour, the result of successful execution will not be returned to the application after the SQL execution.
I can only throw a link timeout exception if the 10-hour socket_timeout I set is reached
The attached picture is the synchronization rate
![20200106181033](https://user-images.githubusercontent.com/24413335/71811510-dd64c400-30af-11ea-8d1c-1295478d44f0.jpg)

**Comment by den-crane** [comment]
Q1: CH insert single-threaded
https://clickhouse.yandex/docs/en/introduction/performance/
 _To improve performance, you can make multiple INSERT queries in **parallel**, and performance will increase **linearly**._


Q2: by default idle_connection_timeout = 3600. You can change it user's profile. 
Maybe JDBC properties also allow to change idle_connection_timeout , I am not sure.
