### ISSUE TITLE
clickhouse table with repeated field

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#8551]
Apache Parquet is a columnar storage format widespread in the Hadoop ecosystem. ClickHouse supports read and write operations for this format.

As we know, not only parquet but protobuf has the repeated field in message structure.  

If I use command like this:
$ cat {filename} | clickhouse-client --query="INSERT INTO {some_table} FORMAT Parquet"

How does clickhouse adapt repeated fields in a certain message?

**Comment by den-crane** [comment]
CH Arrays?

```
CREATE TABLE some_table
(
    `col1` Array(Int64)
)
ENGINE = Memory;

cat test.parquet |clickhouse-client -q 'insert into some_table format Parquet'

SELECT *
FROM some_table

┌─col1────┐
│ [1,2,3] │
│ [2,8,9] │
└─────────┘
```
