### ISSUE TITLE
order by limit: out of bound

### ISSUE THREAD

**Issue by kaijianding** [ClickHouse/ClickHouse#8553]
**Describe the bug or unexpected behaviour**

**How to reproduce**
* Which ClickHouse server version to use
19.17.6.36 and later
* Queries to run that lead to unexpected result
`SELECT 42 as foo order by foo limit 2`

**Error message and/or stacktrace**
Code: 12, e.displayText() = DB::Exception: Parameters start = 0, length = 2 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 1). (version 19.17.6.36 (official build))

**Additional context**
works in version 19.17.4.11

this is an integration test fails in clickhouse jdbc driver: ru.yandex.clickhouse.integration.ClickHousePreparedStatementTest.testTrailingParameter()

**Comment by YiuRULE** [comment]
With trying to check the commit of the version `19.17`, from the `19.17` branch, it seem it's this PR who is responsible of this bug: ClickHouse/ClickHouse#8051 (or commit 107633ff1ae50bb445f2237a7078a19f5afaf504 on the branch `19.17`)

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/pull/8892
