### ISSUE TITLE
Creating index on an existing table 

### ISSUE THREAD

**Issue by Crazylearner30** [ClickHouse/ClickHouse#8556]
Hi 

I am trying to add index on an existing table , with the below syntax.

create table contact_in.....
(
.......
.....
......
) ENGINE = MergeTree PARTITION BY category
ORDER BY
  (topic, domain) SETTINGS index_granularity = 8192

1. I want to create an index on the topic column (granularity is 6020)

2. tried syntax from the documentation but unable to understand since there is no examples explaining the fields in it.

3. Tried the below 
alter table contact_in add index inx1 topic TYPE minmax granularity 1
not sure how it works (need a better understanding on this).

Can somebody quickly help me with this please.

**Comment by den-crane** [comment]
a. **You already have an index** on topic `ORDER BY(topic, domain)` -- as prefix of a primary index.
b. You can add only skip indexes -- this a special type of indexes and they work by another way, minmax index stores only min max values of an index granula, so for example with  6020, this minmax index will have one minmax values for each 6020*8192 = 49315840 rows and will allow to skip this granula if required value out of minmax.
c. (granularity of skip index = 6020) -- this is nonsense. try 1 or 2.

**Comment by Crazylearner30** [comment]
ok got it, thanks.
