### ISSUE TITLE
Расширение информации в `system`.functions

### ISSUE THREAD

**Issue by relieverz** [ClickHouse/ClickHouse#8562]
Здравствуйте, уважаемые разработчики. Хочу поблагодарить вас за ваш качественный и очень нужный программный продукт. В целях упрощения работы с ним хочу предложить расширить информацию в таблице `system`.functions. Предлагаю добавить след. поля:

1. description - краткое описание функции
2. param - входные параметры функции с их кратким описанием
3. exam - пример использования (желательно, всегда использовать примеры, так как понимание как правильно использовать лучше демонстрировать)

Translation for Dan:
Hello, dear developers. I want to thank you for your high-quality and very necessary software product. In order to simplify the work with it, I want to suggest expanding the information in the system.functions table. I propose to add the following fields: 

1. description - a brief description of the function param - 
2. input parameters of the function with their brief description 
3. exam - an example of use (it is advisable to always use examples, since understanding how to use it correctly is better to demonstrate)

**Comment by alexey-milovidov** [comment]
Мы хотим сделать, чтобы документация по однородным частям системы была расположена прямо в коде, была доступна из системных таблиц, и из неё уже генерировалась бы обычная  документация для сайта.

Это как раз входит в наш roadmap, но так как задача довольно объёмная, скорее всего мы только начнём работу по ней в Q1, и готово это будет начиная не с функций, а с более мелких вещей.

**Comment by DanRoscigno** [comment]
closed by https://github.com/ClickHouse/ClickHouse/pull/49300
