### ISSUE TITLE
Use zookeeper for storing remote_servers

### ISSUE THREAD

**Issue by luqasz** [ClickHouse/ClickHouse#8564]
**Use case**
Cloud provider ip addresses (e.g. AWS) are not predictable, thus first you need to launch instances and then provision config file. 

**Describe the solution you'd like**
* Each clickhouse node / process / instance registers itself in zookeeper
* Node can get all available nodes and update them while running

Problems that will be solved:
* automatic instance replacement (e.g. on AWS when it was marked for shutdown)
* upgrades
* no need to update config file and reload clickhouse

**Describe alternatives you've considered**
DNS names approach also will not work with cloud providers. IP addresses are not known up front.

**Comment by den-crane** [comment]
1. Each CH node can be member of any number of clusters in any configuration. What you going to discover automatically?

For example I have 3 CH node N1, N2, N3 with 4 clusters simultaneously

Cluster1 (each node as a shard): shard1=N1, shard2=N2, shard3=N3
Cluster2 (one shard 3 replica): shard1=N1,N2,N3
Cluster3 (one shard 2 replica): shard1=N1,N2
Cluster4 (3 shards, 2 replica, circle replication):  shard1=N1,N2 shard2=N2,N3, shard3=N3,N1


>DNS names approach also will not work with cloud providers. IP addresses are not known up front.

Just configure your system to register hosts in DNS on start with DHCP.

**Comment by luqasz** [comment]
> Changes of remote_servers does not require reload clickhouse

So I only need to edit config file and CH will pick those changes ?

> Each CH node can be member of any number of clusters in any configuration. What are you going to discover automatically?

So one CH instance can participate in multiple clusters. Ok that changes a lot. Well it disallows any kind of autoscaling as well. 

What I am after is to set CH so it can be replicates, sharded and scaled automaticly by e.g. AWS. Scaling here is important since this changes number of nodes.

**Comment by den-crane** [comment]
>So I only need to edit config file and CH will pick those changes ?

yes. Immediately. You can verify it with `select * from system.clusters`


>Scaling here is important since this changes number of nodes.

The big problem is that CH does not have automatic re-sharding. There is no easy way to add a new shard (or remove the existing) and move data accordingly to sharding rules.

I use rand() as sharding expression. To expand a cluster I spin-up a new node(s) with CH binaries, create databases/tables at them using my own atomation scripts (add new nodes into internal CMDB as a part of required clusters) and using chef apply a new config on nodes. This new nodes have less data than others but using weights I load more data into them. After several months they have the same amount of data as the old nodes.

**Comment by filimonov** [comment]
Also check `from_zk`

**Comment by luqasz** [comment]
Thx for info.

**Comment by alexey-milovidov** [comment]
`from_zk` is the answer on how to store cluster configuration in ZooKeeper.
Automatic discovery most likely will not be implemented soon due to considerations that @den-crane has mentioned.
