### ISSUE TITLE
Failed to upgrade from 19.6.2 (altinity el/6 package) to 19.17.6 with unsatisfied dependency of 19.6

### ISSUE THREAD

**Issue by huang--yijian** [ClickHouse/ClickHouse#8568]
**Describe the bug or unexpected behaviour**
![image](https://user-images.githubusercontent.com/7484190/71958417-3ad15000-322b-11ea-829b-a1a904b47e13.png)

When we try to update from 19.6.2 (previously installed by Altinity el/6 RPM package) to 19.17.6, the above error in the screenshot happened.
The error is about unsatisfied dependency of version 19.6, while we are upgrading to 19.17. Why ?

**How to reproduce**
1. Prepare a ClickHouse 19.6.2 server installed by Altinity el/6 package.
2. service clickhouse-server stop
3. Install these 19.17.6 RPM packages by "rpm -Fvh":
clickhouse-client-19.17.6.36-2.noarch.rpm (115376B)
clickhouse-common-static-19.17.6.36-2.x86_64.rpm (96893532B)
clickhouse-server-19.17.6.36-2.noarch.rpm (136087B)
clickhouse-test-19.17.6.36-2.noarch.rpm (1627976B)

They are downloaded from https://repo.yandex.ru/clickhouse/rpm/stable/x86_64

* Which ClickHouse server version to use
We try to upgrade from 19.6.2 to 19.17.6.

**Expected behavior**
The upgrade should succeed.

**Error message and/or stacktrace**
See the screenshot.

**Comment by filimonov** [comment]
When you try to upgrade clickhouse-common-static, it tries to uninstall the previous version first. But it is required by another package (clickhouse-server) and can't be uninstalled because of that.

The solution is to update both packages in one transaction, for example
```rpm -Fvh *.rpm```

**Comment by huang--yijian** [comment]
> When you try to upgrade clickhouse-common-static, it tries to uninstall the previous version first. But it is required by another package (clickhouse-server) and can't be uninstalled because of that.
> 
> The solution is to update both packages in one transaction, for example
> `rpm -Fvh *.rpm`

We put 19.6.2 RPMs (Altinity el/6 packages) and 19.17.6 RPMs in the same directory, and upgrade again. It does not work:

![image](https://user-images.githubusercontent.com/7484190/72042385-5ac74900-32e9-11ea-8ab2-bd0edad5f7a7.png)

**Comment by filimonov** [comment]
You had only rpms from 19.17 in that folder before :) Now you are trying to install both 19.16 and 19.17 at the same time. But you need to install v19.17, right? :)

Please list all rpms which need to be installed explicitly, or use appropriate wildcard.
```
rpm -Fvh *19.17.6*.rpm
```
or
```
rpm -Fvh  clickhouse-client-19.17.6.36-2.noarch.rpm clickhouse-common-static-19.17.6.36-2.x86_64.rpm clickhouse-server-19.17.6.36-2.noarch.rpm
```

**Comment by huang--yijian** [comment]
> You had only rpms from 19.17 in that folder before :) Now you are trying to install both 19.16 and 19.17 at the same time. But you need to install v19.17, right? :)
> 
> Please list all rpms which need to be installed explicitly, or use appropriate wildcard.
> 
> ```
> rpm -Fvh *19.17.6*.rpm
> ```
> 
> or
> 
> ```
> rpm -Fvh  clickhouse-client-19.17.6.36-2.noarch.rpm clickhouse-common-static-19.17.6.36-2.x86_64.rpm clickhouse-server-19.17.6.36-2.noarch.rpm
> ```

It still does not work, as in the following screenshot:
![image](https://user-images.githubusercontent.com/7484190/72581863-c2018080-391b-11ea-80fa-b9b856fbc115.png)

**Comment by huang--yijian** [comment]
Would you please re-open this issue, as it is not resolved yet it ?

**Comment by huang--yijian** [comment]
This issue is about failure to upgrade ClickHouse by RPM packages. 
We have shutdown ClickHouse server successfully before we start the upgrade.

#8736  is about failure to close ClickHouse thread pool which was not running at all when we started the upgrade. Why is #8736 going to fix this issue of our failed upgrade? I do not think they are related. @dingxiangfei2009

**Comment by dingxiangfei2009** [comment]
@huang--yijian Sorry, I type the wrong digit for my issue number.

**Comment by amarazm** [comment]
@dingxiangfei2009 

You trying to freshen package from one repo with package from different repo with different distributor.

You have to uninstall old version ad install new packages.
Or you could try --force flag to replace files\packages
For example: rpm --force -Uvh *19.17*

**Comment by huang--yijian** [comment]
> @huang--yijian Sorry, I type the wrong digit for my issue number.

What's the correct issue number you are referring to ?

**Comment by dingxiangfei2009** [comment]
@huang--yijian It was supposed to be #8569. Don't worry, that issue is totally irrelevant to this. :sweat_smile:

**Comment by huang--yijian** [comment]
> @dingxiangfei2009
> 
> You trying to freshen package from one repo with package from different repo with different distributor.
> 
> You have to uninstall old version ad install new packages.
> Or you could try --force flag to replace files\packages
> For example: rpm --force -Uvh _19.17_

We upgraded ClickHouse successfully by "rpm --force ...". Thank you for the support.
