### ISSUE TITLE
Import json which contains nested json and json array from kafka as json string

### ISSUE THREAD

**Issue by HungUnicorn** [ClickHouse/ClickHouse#8577]
In my kafka, one json message looks like the following:
```json
{
  "id": "1234",
  "ts": "2019-12-30T17:48:19.026+01:00",
  "external_id": "aabb",
  "processing_result": {
    "score": 100,
    "strategies": [
      {
        "decision": "eat"
      }]}
}
```

#### Failed approach 1: 
When using the SETTINGS as the documentation as the following, it throws`Cannot parse JSON string: expected opening quote: (while read the value of key processing_result): (at row 1)`

```sql
CREATE TABLE click_conn
(
    ts          String,
    id          String,
    external_id String,
    processing_result String
) ENGINE = Kafka()
    SETTINGS
        kafka_broker_list = 'localhost:9092',
        kafka_topic_list = 'clicks',
        kafka_group_name = 'clickhouse',
        kafka_format = 'JSONEachRow';
```
#### Failed approach 2:
When using the approach like https://github.com/ClickHouse/ClickHouse/issues/6368, that uses `kafka_format=TSV and kafka_row_delimiter='\n'` , it throws 
`DB::Exception: Cannot parse input: expected \t at end of stream.: (at row 1)`

Any setting can work for my case? my goal is to let `processing_result` become a json string.

#### Other code snippets
```sql
CREATE TABLE click
(
    day         Date,
    happened    DateTime,
    id          String,
    external_id String,
    processing_result String
) ENGINE = SummingMergeTree(day, (day, id), 8192);
```

```sql
CREATE MATERIALIZED VIEW consumer_click TO click
AS
SELECT toDate(substring(ts, 1, 19))     AS day,
       toDateTime(substring(ts, 1, 19)) as happened,
       id,
       external_id,
       processing_result
FROM click_conn;
```

**Comment by filimonov** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/8160

**Comment by HungUnicorn** [comment]
I saw #8160. it's fine for my case to import the json as String type, or perhaps I misunderstand?

**Comment by millin** [comment]
Nested json objects can be declared as named tuples, if anyone implements idea #7787
