### ISSUE TITLE
Non-printable symbols in the log

### ISSUE THREAD

**Issue by traceon** [ClickHouse/ClickHouse#8579]
If the query tracing is enabled, server log may contain non-printable symbols (from queries, but who knows where else they could theoretically come from).

To reproduce:
1. run `clickhouse-server` manually in a console with a logging level verbose enough for queries to be printed as they are received.
2. from another console, execute the following query using `clickhouse-client`:
```
clickhouse-client --query "SELECT '$(dd if=/dev/urandom bs=1000 count=1 | tr "'" x)'"
```

As a result, the output of the server (and the client too) will contain non-printable symbols, that sometimes may even mess up the terminal.

A suggested solution would be to use some standard printable representations of such non-printable symbols in the log/trace output, assuming that the destination encoding is UTF-8.

**Comment by alexey-milovidov** [comment]
I think that it's better to write bytes to log without any modification (including zero bytes and illegal UTF-8 sequences). This is useful for post-mortem analysis. Sometimes you will need the exact contents of these bytes.

**Comment by alexey-milovidov** [comment]
Some tweaks are possible. For example, if log is written to terminal and nowhere else, we can apply some filters.

**Comment by traceon** [comment]
Even a special flag that needs to be turned on manually to enable filtering/transformation would be useful.

**Comment by alexey-milovidov** [comment]
It is possible to configure with `query_masking_rules`.
```
        <rule>
            <name>ascii_esc</name>
            <regexp>\x27</regexp>
            <replace>\\e</replace>
        </rule>
```

**Comment by traceon** [comment]
Thanks, will try.
