### ISSUE TITLE
Casting a (system) table column to Nullable(String) and matching to a pattern with LIKE doesn't work as expected

### ISSUE THREAD

**Issue by traceon** [ClickHouse/ClickHouse#8580]
Trying to get `database` column of `system.tables` table, `CAST`'ed to `Nullable(String)` and matching using `LIKE`, but getting unexpected errors.

`SELECT database FROM system.tables WHERE database LIKE '%'` - works as expected
`SELECT database AS db FROM system.tables WHERE db LIKE '%'` - works as expected
`SELECT CAST(database, 'String') AS db FROM system.tables WHERE db LIKE '%'` - works as expected
`SELECT CAST('a string', 'Nullable(String)') AS str WHERE str LIKE '%'` - works as expected
`SELECT CAST(database, 'Nullable(String)') AS ndb FROM system.tables WHERE ndb LIKE '%'` - fails with error:
```
Code: 368. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: Bad cast from type DB::ColumnNullable to DB::ColumnVector<unsigned char>. 
```

**Comment by den-crane** [comment]
could not reproduce with 20.11.1.4897
