### ISSUE TITLE
 materialized view aggregation:Aggregation method:without_key SelectExecutor Key condition unkown 

### ISSUE THREAD

**Issue by kuncao** [ClickHouse/ClickHouse#8583]
(you don't have to strictly follow this form)

**Describe the situation**
What exactly works slower than expected?
yes,without the view, the  query can run at 0.5s,but use the view to query , the query is over 1 s.
**How to reproduce**
https://www.slideshare.net/Altinity/clickhouse-and-the-magic-of-materialized-views-by-robert-hodges-and-altinity-engineering-team
following the page 12 and page 14  to create my own  table load data and create materialized view
* Which ClickHouse server version to use
19.17.4.11-2
* Which interface to use, if matters
cli
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to slow performance
https://www.slideshare.net/Altinity/clickhouse-and-the-magic-of-materialized-views-by-robert-hodges-and-altinity-engineering-team
following the page 12 and page 14  to create my own  table load data and create materialized view
**Expected performance**
with view,the query so faster than query from the orginial table
What are your performance expectation, why do you think they are realistic? Has it been working faster in older ClickHouse releases? Is it working faster in some specific other system?

**Additional context**

**Comment by den-crane** [comment]
>following the page 12 and page 14

Are you kidding?

**Comment by kuncao** [comment]
@den-crane 
Thanks for your reply.
I can not upload the detail information.
Can you  send me the email : caokun.nj@huawei.com and I will reply with the detail information.
Thanks a lot.

**Comment by kuncao** [comment]
I will try to send the details Cao Jack 邮箱：caojack@gmail.com 签名由 网易邮箱大师 定制 On 01/09/2020 13:08, Denis Zhuravlev wrote: following the page 12 and page 14 Are you kidding? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kuncao** [comment]
发件人: Cao Jack [mailto:caojack@gmail.com]
发送时间: 2020年1月9日 15:42
收件人: ClickHouse/ClickHouse <reply@reply.github.com>
抄送: Caokun (Jack, Platform) <caokun.nj@huawei.com>
主题: Re: [ClickHouse/ClickHouse] materialized view aggregation:Aggregation method:without_key SelectExecutor Key condition unkown (#8583)


I will try to send the details

[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]

Cao Jack

邮箱：caojack@gmail.com<mailto:caojack@gmail.com>


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制
On 01/09/2020 13:08, Denis Zhuravlev<mailto:notifications@github.com> wrote:

following the page 12 and page 14

Are you kidding?

**Comment by den-crane** [comment]
@kuncao you mean it's a secret or what? Try to rename columns / tables and obfuscate your data sample. 
Email has no sense I am not a CH developer I am the member of CH community the same as you are.

**Comment by kuncao** [comment]
from the expert  Alexander Zaitsev ,who works in altinity.com,our issue is :
1. For sum() you do not need to use AggregateState (sumState) functions at all. SummingMergeTree would sum automatically. If you are using SummingMergeTree please change sumState() to sum(),
2. Alternativelly, you could use AggregatingMergeTree with SimpleAggregateFunction both for sum() and max(). See an example in the recent article: 
https://www.altinity.com/blog/2020/1/1/clickhouse-cost-efficiency-in-action-analyzing-500-billion-rows-on-an-intel-nuc
3. GROUP BY and ORDER BY (primary key) columns should match in MV. In your example you have zwtest_202 in GROUP BY but not in ORDER BY. It may result in weird data after the merge (that does not happen to you because of #4 problem). You need to change ORDER BY (zwtest_k1, zwtest_k202) . It also helps with filtering.
4. Both your queries scan the same amount of rows -- 1 billion. It looks like zwtest_k1 is a unique ID or something similar. In this case using of Summing/AggregatingMergeTree does not have any sense, and some extra processing overhead results in worse results.

according to the derection,the view is run 60X
