### ISSUE TITLE
Kafka large lag between  CURRENT-OFFSET and  LOG-END-OFFSET

### ISSUE THREAD

**Issue by KushnerykPavel** [ClickHouse/ClickHouse#8590]
I have used Clickhouse as consumer for Kafka, and see low consume velocity.

Current clickhouse settings:
` <max_block_size>600</max_block_size>
  <max_insert_block_size>2000</max_insert_block_size>`

Currently I have about 80k messages lag
I have tried, add more partition but it does not any effect.

**Comment by ifoo** [comment]
I can confirm this. I'm running ClickHouse server version 20.1.1 revision 54431 and I see max. ingestion speeds of around 1-2k/s and accumulating a lot of lag. `kafka_num_consumers` is set to 1. I'm consuming from a single topic with one partition.

**Comment by den-crane** [comment]
Today we cleared up with @KushnerykPavel that actually he had no problem, because a consuming rate is 50k/s, so a lag in that system is only 1second.

**Comment by filimonov** [comment]
Ok. The original case is cleared. 

@ifoo can you say smth more about your case? Did you update from one of the prev versions? Or it's new setup? Any non standard settings? Table schema and format?
