### ISSUE TITLE
Type's default value used upon insert via pipe instead of table's schema defined defaults

### ISSUE THREAD

**Issue by kancom** [ClickHouse/ClickHouse#86]
There's a table with default values for column:

> CREATE TABLE xdr_tst (
>   date Date,
>   answered Int8 DEFAULT -1,
>   end_date UInt64,
>   start_date UInt64
> ) ENGINE = MergeTree(date, (start_date, end_date), 8192);

I do insert of the following data:

> cat /tmp/zero.csv | od -c  
> 0000000   s   t   a   r   t   _   d   a   t   e  \t   e   n   d   _   d
> 0000020   a   t   e  \t   a   n   s   w   e   r   e   d  \t   d   a   t
> 0000040   e  \n   6   3   2   2   4   1   1   1   9   9   4   3   1   1
> 0000060   1   9   1   9   0  \t   6   3   2   2   4   1   1   1   9   9
> 0000100   4   3   1   1   1   9   1   9   0  \t  \t   2   0   1   6   -
> 0000120   0   8   -   2   4  \n
> 0000126

Note that data for the column with default values is missing

As the result I have:

> SELECT *
> FROM xdr_tst
> 
> ┌───────date─┬─answered─┬────────────end_date─┬──────────start_date─┐
> │ 2016-08-24 │        0 │ 6322411199431119190 │ 6322411199431119190 │
> └────────────┴──────────┴─────────────────────┴─────────────────────┘
> 
> 1 rows in set. Elapsed: 0.002 sec. 

But I expected that answered would be equal to -1 in this case.

commands and source data are attached
[req.txt](https://github.com/yandex/ClickHouse/files/436378/req.txt)

**Comment by alexey-milovidov** [comment]
Default values are evaluated only for columns, that are not listed in INSERT query.

For example, if you type
`INSERT INTO xdr_tst (start_date,end_date,date)`
and send CSV/TSV without column `answered` (without whole column, not with column of empty values), then default values will be evaluated.

Evaluation of default values for missing fields in data file is not supported right now.
We already have another request to implement it: https://github.com/yandex/ClickHouse/issues/75

**Comment by alexey-milovidov** [comment]
For TabSeparated, CSV, assumed semantic is not clear (in contrast to JSONEachRow format).

Unspecified numeric, Date, DateTime, Array field is easily distinguished,
but unspecified String field can not be distinguished from empty string.

Implementation only for all types except String is too hacky, and it's not appropriate.

It become even more unclear, when we introduce NULLs.
TabSeparated format usually have special syntax for NULLs: `\N` (ex: MySQL, Hive).
On INSERTion, NULLs are sometimes used to represent default values for NOT NULL fields (ex: MySQL).
But there is no way to represent default values in TabSeparated format for NULLable fields.

**Comment by kancom** [comment]
ok, thanks for the answer.
if you have by chance approx terms for NULLs or missing defaults evaluations I'd highly appreciate.
we're using -1 as NULL for unsigned types...

**Comment by blinkov** [comment]
There's more or less complete support of NULLs in ClickHouse already implemented, the documentation is coming.

**Comment by alexey-milovidov** [comment]
Fixed.
