### ISSUE TITLE
Statement execute  Question

### ISSUE THREAD

**Issue by 865357384** [ClickHouse/ClickHouse#8608]
This  table  structure：
![image](https://user-images.githubusercontent.com/24928399/72149950-4c5b5900-33df-11ea-8ecb-7db3560dd388.png)

this data:
![image](https://user-images.githubusercontent.com/24928399/72150078-a65c1e80-33df-11ea-8975-7fee88d0e690.png)

this question1 :
   
![image](https://user-images.githubusercontent.com/24928399/72150134-c390ed00-33df-11ea-9d6a-328ffa1b9895.png)

**Comment by 865357384** [comment]
this question2:
select 
    0 as PGID,
    sg.PGID AS PGID2
from tmp_data.sy_game sg

this result:
       ClickHouse exception, code: 10, host: 121.201.54.126, port: 8123; Code: 10, e.displayText() = DB::Exception: Not found column PGID in block. There are only columns: ID, 0 (version 19.15.4.10)


this question3:
select 
    sg.PGID AS PGID2,
    0 as PGID 
from tmp_data.sy_game sg

this result :
PGID2  PGID 
2	0
1	0

**Comment by den-crane** [comment]
OK. Column aliases are tricky. Good.
```
select 0 as PGID, PGID2 from 
   (select sg.PGID AS PGID2 from tmp_data.sy_game sg)
```

**Comment by 865357384** [comment]
OK, thanks
