### ISSUE TITLE
ubutntu aarch64  -- zstd linker command failed

### ISSUE THREAD

**Issue by haitang002** [ClickHouse/ClickHouse#8618]
root@deeb23de376a:/opt/ClickHouse/build/build-arm64# cd build-arm64 ;/usr/bin/clang++-8  -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -pipe   -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -fno-omit-frame-pointer -Werror -O2 -g -DNDEBUG -O3  -fno-pie  -fuse-ld=/usr/bin/ld.gold -rdynamic -Wl,--no-undefined -Wl,-no-pie   -rdynamic dbms/CMakeFiles/clickhouse_malloc.dir/src/Common/malloc.cpp.o utils/compressor/CMakeFiles/zstd_test.dir/zstd_test.cpp.o  -o utils/compressor/zstd_test  dbms/libclickhouse_new_delete.a contrib/jemalloc-cmake/libjemalloc.a contrib/zstd-cmake/libzstd.a libs/libcommon/libcommon.a dbms/libclickhouse_common_io.a libs/libcommon/libcommon.a contrib/cctz-cmake/libcctz.a contrib/poco/Util/libPocoUtil.a contrib/poco/Foundation/libPocoFoundation.a contrib/cityhash102/libcityhash.a contrib/boost-cmake/libboost_system_internal.a dbms/src/Common/StringUtils/libstring_utils.a libs/libwidechar_width/libwidechar_width.a contrib/double-conversion-cmake/libdouble-conversion.a contrib/ryu-cmake/libryu.a contrib/poco/Net/libPocoNet.a contrib/poco/XML/libPocoXML.a contrib/re2/libre2.a contrib/re2_st/libre2_st.a contrib/boost-cmake/libboost_program_options_internal.a libs/libcommon/libapple_rt.a contrib/croaring/libroaring.a contrib/poco/Data/libPocoData.a contrib/poco/NetSSL_OpenSSL/libPocoNetSSL.a contrib/poco/Crypto/libPocoCrypto.a contrib/poco/Net/libPocoNet.a contrib/poco/Util/libPocoUtil.a contrib/poco/XML/libPocoXML.a contrib/poco/JSON/libPocoJSON.a contrib/poco/Crypto/libPocoCrypto.a contrib/openssl-cmake/libssl.a contrib/openssl-cmake/libcrypto.a contrib/poco/Foundation/libPocoFoundation.a contrib/zlib-ng/libz.a -lpthread -ldl -lrt -pthread contrib/brotli-cmake/libbrotli.a -Wl,--start-group libs/libglibc-compatibility/libglibc-compatibility.a contrib/libcxx-cmake/libcxx.a contrib/libcxxabi-cmake/libcxxabi.a -lgcc_eh -Wl,--end-group -nodefaultlibs /usr/lib/llvm-8/lib/clang/8.0.0/lib/linux/libclang_rt.builtins-aarch64.a  -lc -lm -lrt -lpthread -ldl
bash: cd: build-arm64: No such file or directory
../../contrib/zstd/lib/compress/zstd_compress.c:1974: error: undefined reference to 'ZSTD_compressLiterals'
../../contrib/zstd/lib/compress/zstd_compress.c:2016: error: undefined reference to 'HIST_countFast_wksp'
../../contrib/zstd/lib/compress/zstd_compress.c:2019: error: undefined reference to 'ZSTD_selectEncodingType'
../../contrib/zstd/lib/compress/zstd_compress.c:2026: error: undefined reference to 'ZSTD_buildCTable'
../../contrib/zstd/lib/compress/zstd_compress.c:2042: error: undefined reference to 'HIST_countFast_wksp'
../../contrib/zstd/lib/compress/zstd_compress.c:2048: error: undefined reference to 'ZSTD_selectEncodingType'
../../contrib/zstd/lib/compress/zstd_compress.c:2054: error: undefined reference to 'ZSTD_buildCTable'
../../contrib/zstd/lib/compress/zstd_compress.c:2070: error: undefined reference to 'HIST_countFast_wksp'
../../contrib/zstd/lib/compress/zstd_compress.c:2074: error: undefined reference to 'ZSTD_selectEncodingType'
../../contrib/zstd/lib/compress/zstd_compress.c:2080: error: undefined reference to 'ZSTD_buildCTable'
../../contrib/zstd/lib/compress/zstd_compress.c:2097: error: undefined reference to 'ZSTD_encodeSequences'
../../contrib/zstd/lib/compress/zstd_opt.c:176: error: undefined reference to 'HIST_count_simple'
../../contrib/zstd/lib/compress/zstd_opt.c:176: error: undefined reference to 'HIST_count_simple'
../../contrib/zstd/lib/compress/zstd_opt.c:176: error: undefined reference to 'HIST_count_simple'
../../contrib/zstd/lib/compress/zstd_opt.c:176: error: undefined reference to 'HIST_count_simple'
../../contrib/zstd/lib/decompress/zstd_decompress.c:82: error: undefined reference to 'ZSTD_sizeof_DDict'
../../contrib/zstd/lib/decompress/zstd_decompress.c:150: error: undefined reference to 'ZSTD_freeDDict'
../../contrib/zstd/lib/decompress/zstd_decompress.c:493: error: undefined reference to 'ZSTD_getcBlockSize'
../../contrib/zstd/lib/decompress/zstd_decompress.c:713: error: undefined reference to 'ZSTD_DDict_dictContent'
../../contrib/zstd/lib/decompress/zstd_decompress.c:714: error: undefined reference to 'ZSTD_DDict_dictSize'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1171: error: undefined reference to 'ZSTD_DDict_dictContent'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1172: error: undefined reference to 'ZSTD_DDict_dictSize'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1180: error: undefined reference to 'ZSTD_copyDDictParameters'
../../contrib/zstd/lib/decompress/zstd_decompress.c:646: error: undefined reference to 'ZSTD_getcBlockSize'
../../contrib/zstd/lib/decompress/zstd_decompress.c:656: error: undefined reference to 'ZSTD_decompressBlock_internal'
../../contrib/zstd/lib/decompress/zstd_decompress.c:150: error: undefined reference to 'ZSTD_freeDDict'
../../contrib/zstd/lib/decompress/zstd_decompress.c:150: error: undefined reference to 'ZSTD_freeDDict'
../../contrib/zstd/lib/decompress/zstd_decompress.c:946: error: undefined reference to 'ZSTD_decompressBlock_internal'
../../contrib/zstd/lib/decompress/zstd_decompress.c:912: error: undefined reference to 'ZSTD_getcBlockSize'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1064: error: undefined reference to 'ZSTD_buildFSETable'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1077: error: undefined reference to 'ZSTD_buildFSETable'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1090: error: undefined reference to 'ZSTD_buildFSETable'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1171: error: undefined reference to 'ZSTD_DDict_dictContent'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1172: error: undefined reference to 'ZSTD_DDict_dictSize'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1180: error: undefined reference to 'ZSTD_copyDDictParameters'
../../contrib/zstd/lib/decompress/zstd_decompress.c:150: error: undefined reference to 'ZSTD_freeDDict'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1272: error: undefined reference to 'ZSTD_createDDict_advanced'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1272: error: undefined reference to 'ZSTD_createDDict_advanced'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1272: error: undefined reference to 'ZSTD_createDDict_advanced'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1272: error: undefined reference to 'ZSTD_createDDict_advanced'
../../contrib/zstd/lib/decompress/zstd_decompress.c:82: error: undefined reference to 'ZSTD_sizeof_DDict'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1171: error: undefined reference to 'ZSTD_DDict_dictContent'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1172: error: undefined reference to 'ZSTD_DDict_dictSize'
../../contrib/zstd/lib/decompress/zstd_decompress.c:1180: error: undefined reference to 'ZSTD_copyDDictParameters'
../../contrib/zstd/lib/compress/fse_compress.c:675: error: undefined reference to 'HIST_count_wksp'
../../contrib/zstd/lib/compress/huf_compress.c:674: error: undefined reference to 'HIST_count_wksp'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alexey-milovidov** [comment]
You don't have to build all targets.
To build clickhouse, just type `ninja clickhouse`.

**Comment by alexey-milovidov** [comment]
We also provide pre-build binaries.
Example: https://clickhouse-builds.s3.yandex.net/0/fd40b25107f68942be6878c777d9d985b9185746/report.html

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/8027#issuecomment-566671201

**Comment by haitang002** [comment]
> `ninja clickhouse`.

Thank you for your reply，I have successfully built clicokhouse on the aarch64 platform using this command. I hope clickhouse has better support for the aarch64 platform，Thank you again !!

**Comment by haitang002** [comment]
> You don't have to build all targets.
> To build clickhouse, just type `ninja clickhouse`.

ninja clickhouse.

Thank you for your reply，I have successfully built clicokhouse on the aarch64 platform using this command. I hope clickhouse has better support for the aarch64 platform，Thank you again !!
