### ISSUE TITLE
Use Clickhouse Handle  Simple Data ETL Process？

### ISSUE THREAD

**Issue by 865357384** [ClickHouse/ClickHouse#8627]
Can I use Clickhouse to do simple data ETL work, so I don't need to do ETL work in MySQL? Can this program be implemented?

**Comment by den-crane** [comment]
Maybe.
It depends. 
MySQL is much faster on "select by primary_key" and supports updates (CH `alter update` is much slower. )

**Comment by meob** [comment]
I reply from my personal experience...

We generally used ETL tools... but with ClickHouse is very easy to access MySQL tables:
   https://clickhouse.yandex/docs/en/operations/table_engines/mysql/
If the application logic is complex You can use MySQL views.
We generally have a complex OLTP DB design in MySQL, we create some MySQL views
with joins... and we upload the flat large table in CH.
The SQL script can be launched with a crontab in the night: easy and reasonably fast.
We used this approch in several projects with CH and we did not have any problem in 2 years.

A recent CH version (19.10) added the database integration to MySQL...

**Comment by 865357384** [comment]
OK ，Thank you very much for answering my question ！！！

**Comment by fenghaojiang** [comment]
> I reply from my personal experience...
> 
> We generally used ETL tools... but with ClickHouse is very easy to access MySQL tables: https://clickhouse.yandex/docs/en/operations/table_engines/mysql/ If the application logic is complex You can use MySQL views. We generally have a complex OLTP DB design in MySQL, we create some MySQL views with joins... and we upload the flat large table in CH. The SQL script can be launched with a crontab in the night: easy and reasonably fast. We used this approch in several projects with CH and we did not have any problem in 2 years.
> 
> A recent CH version (19.10) added the database integration to MySQL...

Good idea but still T+n. I want to make it real-time or within several seconds. Is it possible without writing codes? Or are there any softwares helping me?

**Comment by meob** [comment]
My original reply is 2 years old and it is a very long time for ClickHouse! 
The Database Engine MySQL and, even if it is still experimental,
the Database Engine MaterializeMySQL both offer a near real time
access to MySQL data from ClickHouse.
Give them a try...

**Comment by fenghaojiang** [comment]
> My original reply is 2 years old and it is a very long time for ClickHouse! The Database Engine MySQL and, even if it is still experimental, the Database Engine MaterializeMySQL both offer a near real time access to MySQL data from ClickHouse. Give them a try...

Thx. Really appreciated to your help.
