### ISSUE TITLE
why use lookup table affect performance so much

### ISSUE THREAD

**Issue by ZonghaoWang** [ClickHouse/ClickHouse#8629]
hi,
I use 
SELECT arrayReduce('sum', arrayMap(i -> (i * i), pq_index)) AS dis
FROM FeatureInt8Merged
ORDER BY dis DESC
LIMIT 10
this query, clickhouse can read 90m Rows/s.
but when I use
SELECT arrayReduce('sum', arrayMap(i -> ([1., 2, 3, 4, 5, 6, 7, 8][i + 2]), pq_index)) AS dis
FROM FeatureInt8Merged
ORDER BY dis DESC
LIMIT 10
this scan speed will descrese to 30m Rows/s
the length of pq_index is 32, type is Array(UInt8)
Is the input array cached in L2?

**Comment by blinkov** [comment]
@ZonghaoWang, is this question still relevant?

**Comment by ZonghaoWang** [comment]
describe ambiguous
