### ISSUE TITLE
clickhouse can not disable compression

### ISSUE THREAD

**Issue by cliicy** [ClickHouse/ClickHouse#8634]
create table with CODEC(NONE), I want disable/turn-off compression in clickhouse, so I create table with CODEC(NONE),but when the system.columns still shows there are lot of bytes compressed. please see the snapshot attached.
![vandat_tab](https://user-images.githubusercontent.com/8543587/72267848-ba13b900-365b-11ea-8a87-48cd49e34edd.png)
![comp](https://user-images.githubusercontent.com/8543587/72267869-bda74000-365b-11ea-96ed-67e71f367c52.png)

**Comment by den-crane** [comment]
they are just file's(streams) headers. 
Try to load more rows (million) and compare compressed VS uncompressed again

**Comment by cliicy** [comment]
hi ,
thanks for your information.
I load 59986052 rows data and compared the compressed with uncompressed. there are indeed very different.
compressed info:
![image](https://user-images.githubusercontent.com/8543587/72323017-aa8b8300-36e2-11ea-85c4-de2c2e01a44d.png)

uncompressed info:
![image](https://user-images.githubusercontent.com/8543587/72323053-c3943400-36e2-11ea-9fc8-0ee5cab01873.png)

it seems that the column named data_uncompressed_bytes is not changed at all regardless compressed or uncompressed. is it correct?

**Comment by alexey-milovidov** [comment]
Yes. Technically, when you choose codec NONE, data is still placed into compressed container but not compressed inside it. ClickHouse will report the size of this container as "data_compressed_bytes" regardless to the fact that data is not compressed inside it.

**Comment by cliicy** [comment]
thanks very much for your explanation. they are very helpful.
