### ISSUE TITLE
How to attach to an existing replicated table or create it

### ISSUE THREAD

**Issue by bgranvea** [ClickHouse/ClickHouse#8635]
I'm using the Docker image of Clickhouse with an init SQL script like this:

CREATE TABLE IF NOT EXISTS mytable
(columns)
ENGINE = AggregatingMergeTree('/clickhouse/{cluster}/tables/mytable/{shard}', '{replica}')
[...]

Now I would like to support the scenario where I restore my replica after a complete data loss as described in https://clickhouse.yandex/docs/en/operations/table_engines/replication/#recovery-after-complete-data-loss

I would like to use ATTACH TABLE instead of copying metadata from another node because this solution looks more elegant to me.

My initial idea was to:
- use ATTACH TABLE
- if I cannot attach to the replica declared in Zookeeper, use CREATE TABLE

The problem is that ATTACH TABLE returns no error if I give a non-existent Zookeeper path. Is that the expected behavior?

So maybe I should do it the other way round:
- CREATE TABLE
- if I get an error saying that the Zookeeper path exists, use ATTACH TABLE

Is that the right way to do it? Is there a way to do it in pure SQL statements??

**Comment by bgranvea** [comment]
2 possibilities to be able to do this in pure SQL:

- change ATTACH TABLE so that it returns an error if the Zookeeper path doesn't exist, and implement an ATTACH OR CREATE TABLE [IF NOT EXISTS]

- implement a CREATE OR ATTACH TABLE [IF NOT EXISTS]

**Comment by den-crane** [comment]
Attach with non-existing ZK path works without errors because it needed to start CH without ZK (in readonly mode) https://github.com/ClickHouse/ClickHouse/pull/4691

**Comment by den-crane** [comment]
I don't understand what problem are trying to solve. You don't have a knowledge is it new shard/replica or previously existent?

ZK does not store data only metadata (so to restore replica you need another live replica with data).
You can check zk_path existence using `select ... from system.zookeeper`.

**Comment by bgranvea** [comment]
Thanks I didn't know about the start without ZK. 

I could store somewhere the knowledge that I'm trying to restore a replica from scratch (so need to attach tables instead of create them) but I need some control logic when I execute the SQL script. My point was to have the same SQL statement which can do both (thus no duplication of column definition).

Anyway, I can't see how to do this for the moment, so I'm going on with templatized SQL scripts which generate either CREATE or ATTACH.
