### ISSUE TITLE
clickhouse crash " Received signal Segmentation fault"

### ISSUE THREAD

**Issue by kwai-code** [ClickHouse/ClickHouse#8636]
2020.01.13 23:43:56.376109 [ 969 ] {} <Fatal> BaseDaemon: ########################################
2020.01.13 23:43:56.376119 [ 970 ] {} <Fatal> BaseDaemon: ########################################
2020.01.13 23:43:56.376170 [ 969 ] {} <Fatal> BaseDaemon: (version 19.17.6.36 (official build)) (from thread 348) Received signal Segmentation fault (11).
2020.01.13 23:43:56.376178 [ 970 ] {} <Fatal> BaseDaemon: (version 19.17.6.36 (official build)) (from thread 88) Received signal Segmentation fault (11).
2020.01.13 23:43:56.376200 [ 969 ] {} <Fatal> BaseDaemon: Address: 0x10 Access: read. Address not mapped to object.
2020.01.13 23:43:56.376200 [ 970 ] {} <Fatal> BaseDaemon: Address: 0x10 Access: read. Address not mapped to object.
2020.01.13 23:43:56.377019 [ 970 ] {} <Fatal> BaseDaemon: Stack trace: 0x5624850f3c7c 0x562485166087 0x5624850ddc82 0x5624850de5e8 0x562485079e3f 0x56248507a7ed 0x5624816cc55c 0x562487470780 0x7f43d979fe25 0x7f43d90c134d
2020.01.13 23:43:56.377022 [ 969 ] {} <Fatal> BaseDaemon: Stack trace: 0x5624850f3c7c 0x562485166087 0x5624850ddc82 0x5624850de5e8 0x562485079e3f 0x56248507a7ed 0x5624816cc55c 0x562487470780 0x7f43d979fe25 0x7f43d90c134d
2020.01.13 23:43:56.377989 [ 969 ] {} <Fatal> BaseDaemon: 3. 0x5624850f3c7c void DB::Aggregator::executeImplCase<true, DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> > >(DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >&, DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >::State&, DB::Arena*, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*) const ?
2020.01.13 23:43:56.377990 [ 970 ] {} <Fatal> BaseDaemon: 3. 0x5624850f3c7c void DB::Aggregator::executeImplCase<true, DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> > >(DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >&, DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >::State&, DB::Arena*, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*) const ?
2020.01.13 23:43:56.378571 [ 970 ] {} <Fatal> BaseDaemon: 4. 0x562485166087 void DB::Aggregator::executeImpl<DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> > >(DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >&, DB::Arena*, unsigned long, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, bool, char*) const ?
2020.01.13 23:43:56.378572 [ 969 ] {} <Fatal> BaseDaemon: 4. 0x562485166087 void DB::Aggregator::executeImpl<DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> > >(DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >&, DB::Arena*, unsigned long, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, bool, char*) const ?
2020.01.13 23:43:56.379415 [ 970 ] {} <Fatal> BaseDaemon: 5. 0x5624850ddc82 DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> > > >&, bool&) ?
2020.01.13 23:43:56.379420 [ 969 ] {} <Fatal> BaseDaemon: 5. 0x5624850ddc82 DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> > > >&, bool&) ?
2020.01.13 23:43:56.379442 [ 970 ] {} <Fatal> BaseDaemon: 6. 0x5624850de5e8 DB::Aggregator::executeOnBlock(DB::Block const&, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> > > >&, bool&) ?
2020.01.13 23:43:56.379454 [ 969 ] {} <Fatal> BaseDaemon: 6. 0x5624850de5e8 DB::Aggregator::executeOnBlock(DB::Block const&, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> > > >&, bool&) ?
2020.01.13 23:43:56.379457 [ 970 ] {} <Fatal> BaseDaemon: 7. 0x562485079e3f DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long) ?
2020.01.13 23:43:56.379483 [ 969 ] {} <Fatal> BaseDaemon: 7. 0x562485079e3f DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long) ?
2020.01.13 23:43:56.379514 [ 970 ] {} <Fatal> BaseDaemon: 8. 0x56248507a7ed ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::{lambda()#1}::operator()() const ?
2020.01.13 23:43:56.379513 [ 969 ] {} <Fatal> BaseDaemon: 8. 0x56248507a7ed ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::{lambda()#1}::operator()() const ?
2020.01.13 23:43:56.379552 [ 970 ] {} <Fatal> BaseDaemon: 9. 0x5624816cc55c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) ?
2020.01.13 23:43:56.379554 [ 969 ] {} <Fatal> BaseDaemon: 9. 0x5624816cc55c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) ?
2020.01.13 23:43:56.379572 [ 970 ] {} <Fatal> BaseDaemon: 10. 0x562487470780 ? ?
2020.01.13 23:43:56.379572 [ 969 ] {} <Fatal> BaseDaemon: 10. 0x562487470780 ? ?
2020.01.13 23:43:56.379615 [ 970 ] {} <Fatal> BaseDaemon: 11. 0x7f43d979fe25 start_thread /usr/lib64/libpthread-2.17.so
2020.01.13 23:43:56.379615 [ 969 ] {} <Fatal> BaseDaemon: 11. 0x7f43d979fe25 start_thread /usr/lib64/libpthread-2.17.so
2020.01.13 23:43:56.379639 [ 970 ] {} <Fatal> BaseDaemon: 12. 0x7f43d90c134d clone /usr/lib64/libc-2.17.so
2020.01.13 23:43:56.379639 [ 969 ] {} <Fatal> BaseDaemon: 12. 0x7f43d90c134d clone /usr/lib64/libc-2.17.so

**Comment by alexey-milovidov** [comment]
What query do you execute? What is the structure of your tables and configuration of the cluster?

**Comment by den-crane** [comment]
>2020.01.13 23:43:56.376109 [ 969 ] {} BaseDaemon: 
>2020.01.13 23:43:56.376119 [ 970 ] {} BaseDaemon: 

It's kinda unusual. Two CH servers process?

**Comment by alexey-milovidov** [comment]
@den-crane It's Ok, we output messages from different segfaults in different threads (in recent versions).

**Comment by kwai-code** [comment]
> What query do you execute? What is the structure of your tables and configuration of the cluster?

we replayed all the query, no crash happened

**Comment by filimonov** [comment]
> > What query do you execute? What is the structure of your tables and configuration of the cluster?
> 
> we replayed all the query, no crash happened

If you're satisfied with the result 'it crashes only sometimes', you can close the issue. 

If you want to be sure that it is fixed and the problem will not return someday you need to provide more data about circumstances (as requested above). You can obfuscate columns names if you prefer to keep details of your schema / usecase in secret.

**Comment by alexey-milovidov** [comment]
> If you're satisfied with the result 'it crashes only sometimes', you can close the issue.

I'm not.

**Comment by filimonov** [comment]
> > If you're satisfied with the result 'it crashes only sometimes', you can close the issue.
> 
> I'm not.

Me neither :) May be @amosbird or @akuzm will be able to deduct what was that looking on the code only, since @kwai-code don't want to help us.

**Comment by songjiao** [comment]
we meet the same problem

> 2020.02.27 23:04:36.749619 [ 1338 ] {} <Fatal> BaseDaemon: 
2020.02.27 23:04:36.749734 [ 1338 ] {} <Fatal> BaseDaemon: (version 19.17.6.36 (official build)) (from thread 491) Received signal Segmentation fault (11).
2020.02.27 23:04:36.749846 [ 1338 ] {} <Fatal> BaseDaemon: Address: 0x10 Access: read. Address not mapped to object.
2020.02.27 23:04:36.749963 [ 1338 ] {} <Fatal> BaseDaemon: Stack trace: 0x561af548bc7c 0x561af54fe087 0x561af5475c82 0x561af54765e8 0x561af5411e3f 0x561af54127ed 0x561af1a6455c 0x561af7808780 0x7f788eadde25 0x7f788e3ff34d
2020.02.27 23:04:36.750183 [ 1338 ] {} <Fatal> BaseDaemon: 3. 0x561af548bc7c void DB::Aggregator::executeImplCase<true, DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> > >(DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >&, DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >::State&, DB::Arena*, unsigned long, DB::Aggregator::AggregateFunctionInstruction*, char*) const ?
2020.02.27 23:04:36.750368 [ 1338 ] {} <Fatal> BaseDaemon: 4. 0x561af54fe087 void DB::Aggregator::executeImpl<DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> > >(DB::AggregationMethodStringNoCache<TwoLevelStringHashMap<char*, Allocator<true, true>, StringHashMap> >&, DB::Arena*, unsigned long, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, DB::Aggregator::AggregateFunctionInstruction*, bool, char*) const ?
2020.02.27 23:04:36.750599 [ 1338 ] {} <Fatal> BaseDaemon: 5. 0x561af5475c82 DB::Aggregator::executeOnBlock(std::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >, unsigned long, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> > > >&, bool&) ?
2020.02.27 23:04:36.750772 [ 1338 ] {} <Fatal> BaseDaemon: 6. 0x561af54765e8 DB::Aggregator::executeOnBlock(DB::Block const&, DB::AggregatedDataVariants&, std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >&, std::vector<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> >, std::allocator<std::vector<DB::IColumn const*, std::allocator<DB::IColumn const*> > > >&, bool&) ?
2020.02.27 23:04:36.750973 [ 1338 ] {} <Fatal> BaseDaemon: 7. 0x561af5411e3f DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long) ?
2020.02.27 23:04:36.751434 [ 1338 ] {} <Fatal> BaseDaemon: 8. 0x561af54127ed ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::{lambda()#1}::operator()() const ?
2020.02.27 23:04:36.751560 [ 1338 ] {} <Fatal> BaseDaemon: 9. 0x561af1a6455c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) ?
2020.02.27 23:04:36.751581 [ 1338 ] {} <Fatal> BaseDaemon: 10. 0x561af7808780 ? ?
2020.02.27 23:04:36.751749 [ 1338 ] {} <Fatal> BaseDaemon: 11. 0x7f788eadde25 start_thread /usr/lib64/libpthread-2.17.so
2020.02.27 23:04:36.751776 [ 1338 ] {} <Fatal> BaseDaemon: 12. 0x7f788e3ff34d clone /usr/lib64/libc-2.17.so



we have a cluster with 99 server, 33 shards each shard have 3 server. 
cluster conf
>
           <shard>
              <weight>2</weight>
              <internal_replication>true</internal_replication>
              <replica>
                  <host>host1</host>
                  <port>9000</port>
                  <user>repl</user>
                  <password>xxx</password>
              </replica>
              <replica>
                  <host>host2</host>
                  <port>9000</port>
                  <user>repl</user>
                  <password>xxx</password>
              </replica>
              <replica>
                  <host>host3</host>
                  <port>9000</port>
                  <user>repl</user>
                  <password>xxx</password>
              </replica>
          </shard>

 during the crash, the server's cpu is very high and with very high network in/out io

don't  really know which sql cause the crash, we replayed all the query no crash happen

**Comment by amosbird** [comment]
There should be a query string in the trace log before the crash.

**Comment by nick-freeman** [comment]
> There should be a query string in the trace log before the crash.

do you use ArgMax(column, version) to aggregate data from shards? if you select more than one column, try doing it like this:
argMax(tuple(col1,col2,col3), version) FROM table
