### ISSUE TITLE
Code: 246: Partition value mismatch between two parts with the same partition ID.

### ISSUE THREAD

**Issue by lixiaolevae** [ClickHouse/ClickHouse#8643]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
A clear and concise description of what works not as it is supposed to.
When I use jdbc to write data，the following exception occurred: **_Code: 246, e.displayText() = DB::Exception: Partition value mismatch between two parts with the same partition ID. Existing part: 201711_9_1464_24, newly added part: 201711_72_72_0._** So I looked at the partitions of the corresponding table，found the wrong partition (as shown below). The data block whose name starts with '201711_9_1464_64' actually resolves into '201597' partition. That is so ridiculous!

system.parts table:
┌─table───────────────────┬─partition─┬─name───────────────┬─active─┐
│ es_coffee_ebos_products │ 201712    │ 201712_1504_1504_0 │      1 │
│ es_coffee_ebos_products │ 201712    │ 201712_1484_1484_0 │      0 │
│ es_coffee_ebos_products │ 201712    │ 201712_1469_1469_0 │      0 │
│ es_coffee_ebos_products │ 201712    │ 201712_10_1484_24  │      1 │
│ es_coffee_ebos_products │ 201712    │ 201712_10_1402_23  │      0 │
│ es_coffee_ebos_products │ 201597    │ 201711_9_1464_24   │      1 │
│ es_coffee_ebos_products │ 201710    │ 201710_8_1474_22   │      1 │
│ es_coffee_ebos_products │ 201709    │ 201709_7_1438_22   │      1 │
│ es_coffee_ebos_products │ 201709    │ 201709_1456_1456_0 │      1 │
│ es_coffee_ebos_products │ 201708    │ 201708_6_1443_23   │      1 │
│ es_coffee_ebos_products │ 201708    │ 201708_1451_1451_0 │      1 │
│ es_coffee_ebos_products │ 201707    │ 201707_5_1473_24   │      1 │
│ es_coffee_ebos_products │ 201706    │ 201706_4_1291_12   │      1 │
│ es_coffee_ebos_products │ 201706    │ 201706_1416_1416_0 │      1 │
│ es_coffee_ebos_products │ 201705    │ 201705_3_1415_16   │      1 │
│ es_coffee_ebos_products │ 201704    │ 201704_2_988_2     │      1 │
│ es_coffee_ebos_products │ 201704    │ 201704_1292_1292_0 │      1 │
│ es_coffee_ebos_products │ 197001    │ 197001_1_1466_24   │      1 │
└─────────────────────────┴───────────┴────────────────────┴────────┘

**How to reproduce**
* Which ClickHouse server version to use
version 19.11.3.11
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by Kozloff** [comment]
I can reproduce with another case:
```
CREATE DATABASE IF NOT EXISTS test;
CREATE TABLE IF NOT EXISTS test.test
(
    d Date,
    k String,
    v UInt64
)
ENGINE MergeTree PARTITION BY d ORDER BY k;
-- failed with code 246
INSERT INTO test.test
SELECT
    reinterpretAsDate(k) d,
    reinterpretAsString(rand()) k,
    rand64() v
FROM system.numbers
LIMIT 50;
-- work
INSERT INTO test.test
WITH reinterpretAsDate(k) AS d
SELECT
    if(toYear(d) > 2100, d - INTERVAL 50 YEAR, d),
    reinterpretAsString(rand()) k,
    rand64() v
FROM system.numbers
LIMIT 50;
```
```
[2020-04-28 16:49:04] Code: 246, e.displayText() = DB::Exception: Partition value mismatch between two parts with the same partition ID. Existing part: 21060207_7_7_0, newly added part: 21060207_14_14_0 (version 19.17.6.36 (official build))
```

**Comment by den-crane** [comment]
still relevant 20.11.1.4897

**Comment by SaltTan** [comment]
Related #10278
