### ISSUE TITLE
Can't set Multi Strategies  on table ttl

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#8658]
clickhouse server version : 19.15.4
ClickHouse client version 19.15.4.10

and the same at version 19.17.6 

sql 1  :      CREATE TABLE example_table 
(
    d DateTime,
    a Int
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(d)
ORDER BY d
TTL d + INTERVAL 1 MONTH DELETE,
    d + INTERVAL 1 WEEK TO VOLUME 'cold';

error: 

![image](https://user-images.githubusercontent.com/24770345/72417347-aaa78380-37b3-11ea-8888-5e5862c7661d.png)

SQL2 :  ALTER TABLE dm_user_behavior_events    MODIFY TTL event_time + INTERVAL 2 MONTH,event_time INTERVAL 30 DAY TO DISK 'cold';

![image](https://user-images.githubusercontent.com/24770345/72417366-b85d0900-37b3-11ea-8a19-ef83c0999181.png)

**Comment by excitoon** [comment]
@onine007 You will need newer version of ClickHouse, 19.19+.
