### ISSUE TITLE
Settings, lowercasing, locale

### ISSUE THREAD

**Issue by kassak** [ClickHouse/ClickHouse#8659]
User reported connectivity issue https://youtrack.jetbrains.com/issue/DBE-9900
> Code: 115, e.displayText() = DB::Exception: Unknown setting sessıon_ıd (version 19.17.6.36 (official build)).

Seems to be SESSION_ID lowercased using system (Turkish) locale, causing wrong letters (`ı`, not `i`)

Seems to be server issue, as `... this wasn't an issue in previous ClickHouse versions(like v19.15 or something)`

**Comment by filimonov** [comment]
ClickHouse dont lowercase the settings, ClickHouse does not work on Windows. So that sounds like jdbc issue.

**Comment by den-crane** [comment]
jdbc-driver 

https://github.com/ClickHouse/clickhouse-jdbc/blob/5ff82e2f902450ad5679d8a654f7557d2220c1cd/src/main/java/ru/yandex/clickhouse/settings/ClickHouseQueryParam.java#L285-L288

**Comment by filimonov** [comment]
@kassak for me the best solution is to put the setting in lowercase if possible to avoid problems with lowercasing. If you have better ideas / options - please send proposals (better in form of pull request) into https://github.com/ClickHouse/ClickHouse-jdbc project
