### ISSUE TITLE
Better ALTER FREEZE

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#8661]
In case of empty table it should create empty structure of folders (w/o that we can't restore the backup from metadata, will complain about lack of folder, recreating that manually is not nice)

Support for ALTER TABLE ... FREEZE (w/o partitions syntax) for non-merge tree tables - Log familty, Join, Set, Distributed, Buffer etc. For distributed / Buffer we just need to have empty folder structure (same motivation as above).

Reason: single way to backup/restore all different types of tables FREEZE all table + metadata folder should be enough to recover everything.

**Comment by filimonov** [comment]
Maybe metadata should be also included in backups?

**Comment by alexey-milovidov** [comment]
> Support for ALTER TABLE ... FREEZE (w/o partitions syntax) for non-merge tree tables - Log familty, Join, Set, Distributed, Buffer etc.

It doesn't fit the logic of FREEZE because files in Log* tables are mutable and hardlinks won't work. It cannot be implemented without locking and file copy. In simple terms, these tables are not lock-free.

**Comment by alexey-milovidov** [comment]
> In case of empty table it should create empty structure of folders

This is easy to implement. Maybe separate it into abother task?

**Comment by filimonov** [comment]
#13953
