### ISSUE TITLE
CLA for organizations rather than individual contributors

### ISSUE THREAD

**Issue by bgiard** [ClickHouse/ClickHouse#8677]
I would like to make a contribution, but I can't get approval from my company. Legal would like a CLA that is designed for organizations rather than individuals. 

> The Contributor License Agreement (CLA) which governs contributions to this project is intended to be signed (or otherwise agreed to) by individual developers, not by employees of a corporation or other legal entity. As a result, we cannot authorize employees to contribute to this project as doing so would require them to sign an agreement which covers intellectual property they do not own (and for which we cannot grant them permission to agree to a patent license).

Any way to make that happen?

**Comment by alexey-milovidov** [comment]
You can provide DCO instead of CLA: https://developercertificate.org/

**Comment by tchetwin** [comment]
@alexey-milovidov could you indicate on the repository somewhere that you accept DCO and indicate how a user should indicate in a contribution that they agree to it. Thanks!

**Comment by alexey-milovidov** [comment]
Ok. https://github.com/ClickHouse/ClickHouse/commit/774a98b4061c71fff99244879899eeecff25b8d5
