### ISSUE TITLE
The clickhouse.log occured lots of StorageReplicatedMergeTree errors,but can run regularly

### ISSUE THREAD

**Issue by jonhsonjs** [ClickHouse/ClickHouse#8682]
We use clickhouse version is 19.16.3.6, i find lots of error in clickhouse.log as bellow
`2020.01.16 17:19:08.518148 [ 94 ] {} <Trace> test.test: Executing log entry to merge parts 0b93ae75667e6d052fba5b93449b81c6_1_113_3, 0b93ae75667e6d052fba5b93449b81c6_114_554_4, 0b93ae7566
7e6d052fba5b93449b81c6_555_955_4, 0b93ae75667e6d052fba5b93449b81c6_956_1048_3, 0b93ae75667e6d052fba5b93449b81c6_1049_1155_3, 0b93ae75667e6d052fba5b93449b81c6_1156_1260_3, 0b93ae75667e6d052fba5b93449b81c6_1261_136
8_3, 0b93ae75667e6d052fba5b93449b81c6_1369_1393_2, 0b93ae75667e6d052fba5b93449b81c6_1394_1412_2, 0b93ae75667e6d052fba5b93449b81c6_1413_1436_2 to 0b93ae75667e6d052fba5b93449b81c6_1_1436_5
2020.01.16 17:19:08.518168 [ 10 ] {} <Error>test.test: DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Code: 243, e.displayText() = D
B::Exception: Cannot reserve 1.35 GiB, not enought space., Stack trace:

0. 0x56025719af90 StackTrace::StackTrace() ?
1. 0x56025719ad65 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) ?
2. 0x560256f21e38 ? ?
3. 0x56025a789fc9 DB::StorageReplicatedMergeTree::tryExecuteMerge(DB::ReplicatedMergeTreeLogEntry const&) ?
4. 0x56025a7999eb DB::StorageReplicatedMergeTree::executeLogEntry(DB::ReplicatedMergeTreeLogEntry&) ?
5. 0x56025a799b21 ? ?
6. 0x56025a8d7b41 DB::ReplicatedMergeTreeQueue::processEntry(std::function<std::shared_ptr<zkutil::ZooKeeper> ()>, std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&, std::function<bool (std::shared_ptr<DB::ReplicatedMergeTreeLogEntry>&)>) ?
7. 0x56025a76fcbf DB::StorageReplicatedMergeTree::queueTask() ?
8. 0x56025a7e5264 DB::BackgroundProcessingPool::threadFunction() ?
9. 0x56025a7e5bda ? ?
10. 0x5602571e553c ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) ?
11. 0x56025cf011e0 ? ?
12. 0x7f5f03280e65 start_thread /usr/lib64/libpthread-2.17.so
13. 0x7f5f02b9d88d __clone /usr/lib64/libc-2.17.so
 (version 19.16.3.6 (official build))`
This is not affect the clickhouse run regularly, we can select ,insert ,create ....  Can anyone help me .

**Comment by blinkov** [comment]
@jonhsonjs, is this question still relevant?

**Comment by alexey-milovidov** [comment]
We don't have this error message in master:
`grep -r -i -F enought src`

At least the typo was fixed.

**Comment by alexey-milovidov** [comment]
`DB::Exception: Cannot reserve 1.35 GiB, not enought space.`

It means that all remaining space was reserved for other merges and this is normal.

**Comment by alexey-milovidov** [comment]
This is not an error.
