### ISSUE TITLE
New installation on Ubuntu VM: Password required for user default. 

### ISSUE THREAD

**Issue by Taxel** [ClickHouse/ClickHouse#8686]
I can't get the initial setup to work on my newly created Ubuntu 18.04.3 LTS virtual machine.
I followed the instructions on the website by executing the following terminal commands:

```
sudo apt-get install dirmngr    # optional
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4    # optional
sudo apt-get update
sudo apt-get install clickhouse-client clickhouse-server
```

This should suffice, right? I then start the server, try to start the client and this is what happens:
```
taxel@taxel-VirtualBox:~$ sudo service clickhouse-server start
taxel@taxel-VirtualBox:~$ clickhouse-client
ClickHouse client version 19.17.6.36 (official build).
Connecting to localhost:9000 as user default.
Code: 194. DB::Exception: Received from localhost:9000. DB::Exception: Password required for user default. 
```
I also tried changing the default password from `<password></password>` to `<password>123</password>` and logging in via `clickhouse-client --password=123` but it outputs that the password is wrong (and yes, I have ensured the xml file is saved and the server is restarted)

Any help would be much appreciated.

**Comment by den-crane** [comment]
On install CH asked for a default password for default user and placed it to /etc/clickhouse-server/users.d/default-password.xml 
You can change this password or remove this file to empty password.

**Comment by Taxel** [comment]
Thanks, that fixed it!
