### ISSUE TITLE
Multiple ARRAY JOIN (per-row cartesian product of arrays)

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#8687]
```
CREATE TABLE test_multiple_array_join (
    id UInt64,
    person Nested (
        name String,
        surname String
    ),
    properties Nested (
        key String,
        value String
    )
) Engine=MergeTree ORDER BY id;

 
INSERT INTO test_multiple_array_join VALUES (1, ['Thomas', 'Michel'], ['Aquinas', 'Foucault'], ['profession', 'alive'], ['philosopher', 'no']);
INSERT INTO test_multiple_array_join VALUES (2, ['Thomas', 'Nicola'], ['Edison', 'Tesla'], ['profession', 'alive'], ['inventor', 'no']);

SELECT *
FROM test_multiple_array_join
ARRAY JOIN person
ARRAY JOIN properties

Received exception from server (version 19.18.1):
Code: 48. DB::Exception: Received from localhost:9000. DB::Exception: Support for more than one ARRAY JOIN in query is not implemented. 

0 rows in set. Elapsed: 0.004 sec. 
```

Workaround:
```
select * from (select * from test_multiple_array_join array join person) array join properties order by person.name,id;

SELECT *
FROM 
(
    SELECT *
    FROM test_multiple_array_join
    ARRAY JOIN person
)
ARRAY JOIN properties
ORDER BY 
    person.name ASC, 
    id ASC

┌─id─┬─person.name─┬─person.surname─┬─properties.key─┬─properties.value─┐
│  1 │ Michel      │ Foucault       │ profession     │ philosopher      │
│  1 │ Michel      │ Foucault       │ alive          │ no               │
│  2 │ Nicola      │ Tesla          │ profession     │ inventor         │
│  2 │ Nicola      │ Tesla          │ alive          │ no               │
│  1 │ Thomas      │ Aquinas        │ profession     │ philosopher      │
│  1 │ Thomas      │ Aquinas        │ alive          │ no               │
│  2 │ Thomas      │ Edison         │ profession     │ inventor         │
│  2 │ Thomas      │ Edison         │ alive          │ no               │
└────┴─────────────┴────────────────┴────────────────┴──────────────────┘

8 rows in set. Elapsed: 0.005 sec. 
```

**Comment by Hungsiro506** [comment]
Any one has a solution for it ?. Does nested join affect performance ?.

**Comment by zhuyoucui0909** [comment]
The workaround is not convenience for us to do auto sql generation. 
Is there any plan that ClickHouse will support multiple array join officially?

**Comment by zhuyoucui0909** [comment]
Is there any plan that ClickHouse will support multiple array join officially? 
The table has multiple Array type columns. The array type columns have different cardinality. We need a way to do multiple array join like follows.
`SELECT *
FROM multiple_arrayType_column_table
ARRAY JOIN arrayTypeColumn1
ARRAY JOIN arrayTypeColumn2
ARRAY JOIN arrayTypeColumn3
...`
A lot of query engines can support it. e.g. Presto. Is there any plan on ClickHouse side?

**Comment by akuzm** [comment]
The title is always confusing me. Do I get it right that we are talking about per-row cartesian product of arrays?
Now we can either zip (`ARRAY JOIN`) or do a cartesian product for all rows (`arrayJoin()`).

**Comment by alexey-milovidov** [comment]
`ARRAY JOIN x, y` - zip (working)
`ARRAY JOIN x ARRAY JOIN y` - product (the missing feature, only available with `arrayJoin` function)

**Comment by akuzm** [comment]
Yes, looks like a workaround with `arrayJoin` is also possible:

```
*2* :) SELECT arrayJoin(arrayZip(person.name, person.surname)), arrayJoin(arrayZip(properties.key, properties.value))　FROM test_multiple_array_join


┌─arrayJoin(arrayZip(person.name, person.surname))─┬─arrayJoin(arrayZip(properties.key, properties.value))─┐
│ ('Thomas','Edison')                              │ ('profession','inventor')                             │
│ ('Thomas','Edison')                              │ ('alive','no')                                        │
│ ('Nicola','Tesla')                               │ ('profession','inventor')                             │
│ ('Nicola','Tesla')                               │ ('alive','no')                                        │
└──────────────────────────────────────────────────┴───────────────────────────────────────────────────────┘
┌─arrayJoin(arrayZip(person.name, person.surname))─┬─arrayJoin(arrayZip(properties.key, properties.value))─┐
│ ('Thomas','Aquinas')                             │ ('profession','philosopher')                          │
│ ('Thomas','Aquinas')                             │ ('alive','no')                                        │
│ ('Michel','Foucault')                            │ ('profession','philosopher')                          │
│ ('Michel','Foucault')                            │ ('alive','no')                                        │
└──────────────────────────────────────────────────┴───────────────────────────────────────────────────────┘
```

**Comment by Zhile** [comment]
hi @alexey-milovidov, we also need `ARRAY JOIN x ARRAY JOIN y` feature. The workaround may be too tricky for us. 
Hope we can have it in ClickHouse soon.

**Comment by kashwy** [comment]
Hi @alexey-milovidov  and to whom it may concern:
I am reviewing this feature, and I have some consideration and want to get confirmed,



1. For the Syntax, the above example use keyword **ARRAY JOIN** for each array , do we need to repeat the keyword **ARRAY JOIN** every time? Maybe we can use one keyword for all arrays that need to be joined, current Multiple arrays can be comma-separated in the **ARRAY JOIN** clause. In this case, JOIN is performed with them simultaneously (the direct sum, not the cartesian product) , maybe we can use a different keyword like **MULTIARRAY JOIN** or use a different format (like use a bracket) , maybe the options like:

- keyword per array:
  ``` ARRAY JOIN arr1 ARRAY JOIN arr2 … ARRAY JOIN arrn```
- different keyword for all arrays:
 ``` MULTIARRAY JOIN  arr1, arr2,…., arrn```
- use a different format from the muilt array in ARRAY JOIN clause (may not a good idea, easy to confuse)
  ```ARRAY JOIN ( arr1, arr2,…arrn)```


2. LEFT join support, may look like:

- keyword per array:
```ARRAY JOIN arr1 LEFT ARRAY JOIN arr2 … ARRAY JOIN arrn```
- different keyword for all arrays:
```MULTIARRAY JOIN  arr1, arr2,…., arrn  LEFT MULTIARRAY JOIN  arrn+1,…., arrm ``` 
- use a different format from the muilt array in ARRAY JOIN clause (may not be a good idea, easy to be confused)
```ARRAY JOIN (arr1, arr2,…arrn)  LEFT ARRAY JOIN ( arrn+1,…arrm) ```

3. do we need to limit the numbers of array for the Multi array join?  Cause it may produce a big set 


Any suggestions and comments are welcome

Thanks

**Comment by zhaopinglu** [comment]
How about:
select number, arrayJoin(range(2020,2022)) year, arrayJoin(range(1,13)) period from numbers(2);

number|year|period|
------+----+------+
     0|2020|     1|
     0|2020|     2|
     0|2020|     3|
     0|2020|     4|
     0|2020|     5|
     0|2020|     6|
     0|2020|     7|
     0|2020|     8|
     0|2020|     9|
     0|2020|    10|
     0|2020|    11|
     0|2020|    12|
     0|2021|     1|
     0|2021|     2|
     0|2021|     3|
     0|2021|     4|
     0|2021|     5|
     0|2021|     6|
     0|2021|     7|
     0|2021|     8|
     0|2021|     9|
     0|2021|    10|
     0|2021|    11|
     0|2021|    12|
     1|2020|     1|
     1|2020|     2|
     1|2020|     3|
     1|2020|     4|
     1|2020|     5|
     1|2020|     6|
     1|2020|     7|
     1|2020|     8|
     1|2020|     9|
     1|2020|    10|
     1|2020|    11|
     1|2020|    12|
     1|2021|     1|
     1|2021|     2|
     1|2021|     3|
     1|2021|     4|
     1|2021|     5|
     1|2021|     6|
     1|2021|     7|
     1|2021|     8|
     1|2021|     9|
     1|2021|    10|
     1|2021|    11|
     1|2021|    12|

**Comment by alexey-milovidov** [comment]
Done.
