### ISSUE TITLE
Default ("simple") aggregate statistics functions extreme numeric instability

### ISSUE THREAD

**Issue by llasram** [ClickHouse/ClickHouse#8688]
**Describe the bug or unexpected behaviour**

The default aggregate statistics functions -- `varSamp()`, etc -- are far less numerically stable than a user could possibly expect.

**How to reproduce**

```sh
$ cat <<EOF | clickhouse client -m -n
DROP TABLE IF EXISTS aggstatbug;
CREATE TABLE aggstatbug (x Float32) ENGINE = Memory;
INSERT INTO aggstatbug VALUES (1000000000), (1000000000), (1000000000);
SELECT version(), varSamp(x) AS var FROM aggstatbug FORMAT PrettyCompact;
EOF
┌─version()──┬───────────var─┐
│ 19.17.6.36 │ -137438950000 │
└────────────┴───────────────┘
```

**Expected behavior**

I expect the reported variance in this case to be `0`.  In general, I expect the calculated variance to be forward stable, with error deltas reflecting unavoidable precision loss in representing the result.  At the very least, I expect computed variance values to be within the codomain of the variance function, which includes only non-negative numbers.

**Additional context**

The error in this particular example case can be avoided by using `Float64` instead of `Float32`, but that just changes the absolute size of the column values versus number of rows required to yield an incorrect/nonsense result.

The undocumented `-Stable` functions such as `varSampStable()` yield the expected results for a wider range of inputs.  If there's no appetite for changing the implementation of the default aggregate statistics functions, perhaps the documentation could be updated to mention numerical stability issues and the existence of the `-Stable` variants.

**Comment by alexey-milovidov** [comment]
At least Stable functions should be included in documentation and I think that changing the type for intermediate calculations to be always Float64 is also reasonable (it will make serialization of aggregation state backwards incompatible but it still ok to do).
