### ISSUE TITLE
Method createColumn() is not implemented for data type Function((String, String) -> String)

### ISSUE THREAD

**Issue by orloffv** [ClickHouse/ClickHouse#8689]
test case:
```
SELECT
    arrayJoin AS kv_key
FROM system.query_log
ARRAY JOIN ProfileEvents.Names AS arrayJoin
PREWHERE has(arrayMap(key -> key, ProfileEvents.Names), 'Query')
WHERE arrayJoin = 'Query'
LIMIT 1
```

problem in PREWHERE section
```
Method createColumn() is not implemented for data type Function((String, String) -> String)
```
ClickHouse server version 19.17.4 revision 54428

problem similar with https://github.com/ClickHouse/ClickHouse/issues/7799

**Comment by 4ertus2** [comment]
It's most probably related to #7497
There's some strange expectation about previous chain steps at line 719 here:
https://github.com/ClickHouse/ClickHouse/pull/7497/files#diff-22f780c9dde88bec19a9dac8ce578f1cR719
