### ISSUE TITLE
"SYSTEM RELOAD DICTIONARY my_dictionary" does not reload immediately

### ISSUE THREAD

**Issue by tdingus** [ClickHouse/ClickHouse#8690]
I have an external dictionary (postgresql). It works nicely!
ClickHouse Server version 19.17.5 revision 54428.

However, after I change a value inside postgres, and run SYSTEM RELOAD DICTIONARY my_dictionary, check in system.dictionaries, the loading_start_time does not change until the preset LIFETIME.

On the other hand, if run SYSTEM RELOAD DICTIONARIES, the loading_start_time changes right away.

**Comment by alexey-milovidov** [comment]
No answer.
