### ISSUE TITLE
SELECT on system.zookeeper returns "Coordination::Exception: No node" error

### ISSUE THREAD

**Issue by bgranvea** [ClickHouse/ClickHouse#8693]
**Describe the bug or unexpected behaviour**
A select on system.zookeeper with a non-existent ZK path returns an error.

**How to reproduce**
Clickhouse version 19.17.6.36

```
select 1 from system.zookeeper where path='any_non_existent_path';

<Error> executeQuery: Code: 999, e.displayText() = Coordination::Exception: No node, path: xxxxxxxxxxxxxx (version 19.17.6.36 (official build)) (from 127.0.0.1:36020) (in query: select 1 from system.zookeeper where path='xxxxxxxxxxx'), Stack trace:
```

**Expected behavior**
As system.zookeeper is presented like a (almost) standard table, IMHO it would be more consistent to return an empty result in this case. Moreover, 999 is a generic code for any Zookeeper exception, so I have to rely on the message to be sure it is a 'No node' expected error

**Comment by alexey-milovidov** [comment]
The table lists children nodes at the path provided.
If it will return empty dataset for non-existing node, how to distinguish it with the case of empty list of children?

Right now the behaviour directly resembles what is happening with the corresponding ZooKeeper request. We request the list of children and ZooKeepers answered with NoNode. That's very clear and obvious...

**Comment by bgranvea** [comment]
ok that makes sense
