### ISSUE TITLE
Sometimes logs remain open after SIGHUP

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#8696]
The server may open a new log file but still continue to write to the old log file.

**Comment by akuzm** [comment]
Reproduces as simple as changing the log file name in the config. The server continues writing to the old file. The snippet I'm using to check:
```
sed -i "s/log>clickhouse-server[0-9]*/log>clickhouse-server10/g" db/config.d/zz-logs.xml
sleep 1 # this sleep is important -- idk why
rm *.log ||:
while ls -lath /proc/$pid/fd | grep deleted
do
    kill -HUP $pid
    sleep 1
    clickhouse-client --query "select 1"
done
```
This loop never ends, and the logs go to the old file.

**Comment by akuzm** [comment]
This particular phenomenon is fixed by applying logging configuration changes only on server restart, so I'll close this issue.

**Comment by akuzm** [comment]
Ah, also, for posterity -- we've seen similar behavior on some Yandex servers, but for a different reason: the ЫТЬ dictionary library overwrites our signal handler. This is being tracked here: https://nda.ya.ru/t/LgxdmboX3Vx4Cu
