### ISSUE TITLE
ClickHouse happily accepts '2020-00-00 00:00:00' for DateTime

### ISSUE THREAD

**Issue by jmakov** [ClickHouse/ClickHouse#8706]
**Describe the bug or unexpected behaviour**
Inserting `'2020-00-00 00:00:00'` into a DateTime field makes ClickHouse write `2106-02-07 06:28:16` into the DB. Note that the month and day value should not be 0, but CK accepts it and writes some garbage into the DB without any warnings.

**How to reproduce**
* Which ClickHouse server version to use
ClickHouse 19.17.6.36
* Which interface to use, if matters
http://ui.tabix.io/
* Non-default settings, if any
None
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE IF NOT EXISTS test.datetime_test (
    dt DateTime CODEC(DoubleDelta, LZ4)
)
ENGINE = MergeTree() 
ORDER BY dt
```
* Queries to run that lead to unexpected result
`INSERT INTO test.datetime_test VALUES ('2020-00-00 00:00:00');`

**Expected behavior**
Should probably raise an error like it does if the inserted field is not in the right form (like it does if you use e.g. `'2020-01-01 00:00'` (which is of course not the form for a DateTime field - seconds missing). So the expected behavior would probably be returning some kind of an error and not let the DB accept the value and silently corrupt it. Returning e.g. `DB::Exception: Cannot parse datetime` would be OK.

**Comment by jmakov** [comment]
And inserting `'abcd-aa-aa 10:00:11'` makes CK write `1970-01-01 10:00:11`.

**Comment by alexey-milovidov** [comment]
This behaviour is by design - to gain some performance of parsing by allowing to have some implementation specific behaviour on incorrect input.

But we already support multiple parsing modes in code and we allow to switch between them with `date_time_input_format` setting. Modes `basic` and `best_effort` are available.

There are no modes that will carefully check for correct date/datetime. The implementation of this modes is considered as a feature request.

**Comment by alexey-milovidov** [comment]
@ucasFL Maybe you are interested?

**Comment by ucasFL** [comment]
Maybe we can check the validity of the parsed date like we just did in `parseDateTimeBestEffort`?

BTW, how to set `date_time_input_format` when insert `DateTime` data? @alexey-milovidov

**Comment by den-crane** [comment]
@ucasFL clickhouse-client --date_time_input_format=basic

**Comment by alexey-milovidov** [comment]
> Maybe we can check the validity of the parsed date like we just did in parseDateTimeBestEffort?

Yes, but we need to carefully check how it will affect performance.

**Comment by erikdubbelboer** [comment]
This issue is related/similar to https://github.com/ClickHouse/ClickHouse/issues/6481

**Comment by kosiakk** [comment]
Documentation states that: _During a read operation, incorrect dates and dates with times **can be parsed with natural overflow** or as null dates and times, without an error message._
