### ISSUE TITLE
The token 'NOT' didn't work in 'SHOW TABLES NOT LIKE' query

### ISSUE THREAD

**Issue by awpengfei** [ClickHouse/ClickHouse#8727]
The token 'NOT' didn't work in 'SHOW TABLES NOT LIKE' query with version 19.13.3.26, the following queries both show the tables start with 'example'.
```SQL
SHOW TABLES LIKE 'example%';
SHOW TABLES NOT LIKE 'example%';
```

**Comment by alexey-milovidov** [comment]
That's ridiculous! Will fix.
