### ISSUE TITLE
Streamable serialization format (suggestion)

### ISSUE THREAD

**Issue by hhell** [ClickHouse/ClickHouse#8738]
Continuing the https://github.com/ClickHouse/ClickHouse/pull/7841

**Use case**

Streaming the detailed information (metadata, data, totals, statistics, errors), deserializing data chunks as they arrive.

**Describe the solution you'd like**

I suggest implementing a format `JSONStreams` (all particular details are uncertain and discussion is highly welcomed),

which consists of 0 or more blocks `<metadata>\n<row>\n...<row>\n\n`, terminated by a special metadata block like `{"name": "end", …}`

Mockup example:

    {"name": "data", "schema": [{"name": "col1", "type": "String"}]}
    [""]

    {"name": "totals", "schema": [{"name": "col1", "type": "String"}]}
    [""]

    {"name": "statistics", "result_rows": 1, "statistics": {"elapsed": 0.00494638, "rows_read": 1, "bytes_read": 1}

    {"name": "end", "success": true}

Example of the terminating metadata block in case of an error:

    {"name": "end", "success": "false", "error_code": 396, "error_message": "Limit for result exceeded, max rows: 1.00 million, current rows: 1.00 million", "version": "20.20", ...}

**Describe alternatives you've considered**

Similar format `JSONCompactEachRowWithNamesAndTypes` cannot properly support statistics and errors/termination.

**Comment by filimonov** [comment]
realtes #208 #902 #2825 etc. See [label:comp-http](https://github.com/ClickHouse/ClickHouse/labels/comp-http) ). 

Possible alternative in 'general' case (for all formats): https://github.com/ClickHouse/ClickHouse/issues/6294

**Comment by hhell** [comment]
> Possible alternative in 'general' case (for all formats): #6294

Yes, that one is most relevant; but it is not exactly 'for all formats': serialization for all the events can vary (schema/progress/totals/statistics/summary/error/...).

**Comment by filimonov** [comment]
I think it's completely ok to serialize metadata always the same way (JSON sounds like a good choice), and datastream in the desired format.

I.e. you can have something like 

```
Content-Type: text/event-stream

event: meta
data: { "query_id": "82be54be-cb77-4c78-b116-8f0a9a4d9cc4", "format": "CSV","start_time":"2020-01-01 20:00:00"}

event: schema
data: {"schema": [{"name": "col1", "type": "String"},{"name": "col2", "type": "UInt64"}]}

event: logs
data: { "log":["[laptop5591] 2020.01.21 10:23:14.358231 {13d063c1-3946-49e3-98e5-fe8ee7be2ffa} [ 46 ] <Debug> executeQuery: (from 127.0.0.1:58880) SELECT number FROM numbers(100000000) WHERE ((number % 100000) = 0) AND (intDiv(number, number - 95000000) = 0)","[laptop5591] 2020.01.21 10:23:14.359125 {13d063c1-3946-49e3-98e5-fe8ee7be2ffa} [ 46 ] <Trace> InterpreterSelectQuery: FetchColumns -> Complete","[laptop5591] 2020.01.21 10:23:14.359289 {13d063c1-3946-49e3-98e5-fe8ee7be2ffa} [ 46 ] <Debug> executeQuery: Query pipeline:\nExpression\n Expression\n  Filter\n   Limit\n    Numbers"] }

data: "some row",323

event: progress
data: {"read_rows":"9764864","read_bytes":"78118912","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

data: "some row2",323
"some row3",323
"some row4",323

event: progress
data: {"read_rows":"20054016","read_bytes":"160432128","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: progress
data: {"read_rows":"30605312","read_bytes":"244842496","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: progress
data: {"read_rows":"41222144","read_bytes":"329777152","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: progress
data: {"read_rows":"51707904","read_bytes":"413663232","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: progress
data: {"read_rows":"62128128","read_bytes":"497025024","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: progress
data: {"read_rows":"72810496","read_bytes":"582483968","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: progress
data: {"read_rows":"83492864","read_bytes":"667942912","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: progress
data: {"read_rows":"94175232","read_bytes":"753401856","written_rows":"0","written_bytes":"0","total_rows_to_read":"100000000"}

event: error
data: { "code": 82, "description": "Code: 82, e.displayText() = DB::Exception: Database db_1_test_api already exists., e.what() = DB::Exception\n" }

data: "some row2",323
"some row3",323
"some row4",323

event: summary
data: {"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0"}
```

**Comment by hhell** [comment]
> I.e. you can have something like

Yes, that would be good.

Not sure how it would work with some of the formats (e.g. CSV, which can have any amount of newlines in data), but for many others (TSV, JSONCompactEachRow) it would be perfect.

**Comment by filimonov** [comment]
> CSV, which can have any amount of newlines in data

AFAIR you just need to replace any newline with `data: ` (need to reread the specs to ensure)

**Comment by alexey-milovidov** [comment]
Implemented in https://github.com/ClickHouse/ClickHouse/pull/66205
