### ISSUE TITLE
Performance drop too much with simple group 

### ISSUE THREAD

**Issue by sundy-li** [ClickHouse/ClickHouse#8772]
**Describe the situation**
I just did a simple OLAP query experiment. But ClickHouse not performs well as I expected.

**How to reproduce**
Version:
 ClickHouse server version 19.17.6 revision 54428.

```
CREATE TABLE default.a
(
    `d` Date,
    `os` String
)
ENGINE = MergeTree
PARTITION BY d
ORDER BY d;

insert into a select today() - 3, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);
insert into a select today() - 2, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);
insert into a select today() - 1, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);
insert into a select today() - 0, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);


select d, count() from a group by d;    
4 rows in set. Elapsed: 0.184 sec.

select os, count() from a group by os;  
4 rows in set. Elapsed: 0.777 sec.

select d,os, count() from a group by d,os;  
16 rows in set. Elapsed: 7.421 sec.

If I change the order by key to be `os`, performance is 
16 rows in set. Elapsed: 1.665 sec
```

**Expected performance**
 I expected the third query may be much faster, perhaps 2~3 s.

**Comment by krnaveen14** [comment]
Generally if you `PARTITION BY d`, then it would be useless to `ORDER BY d` as the data is already separated by `d`. So practical useful way is to `ORDER BY os`.

I would suggest the following schema for better performance and storage efficiency.

```
CREATE TABLE default.a 
(
    `d` Date, 
    `os` LowCardinality(String)
) 
ENGINE = MergeTree 
PARTITION BY d 
ORDER BY os;
```

**Comment by alexey-milovidov** [comment]
I have the following numbers on my machine:
```
select d, count() from a group by d;
0.091 sec.
select os, count() from a group by os;
0.353 sec.
select d,os, count() from a group by d,os;
0.703 sec.
```

It means that the issue is already fixed.

**Comment by alexey-milovidov** [comment]
> If I change the order by key to be `os`

That's expected because data will become sorted and compress better.

**Comment by sundy-li** [comment]
> It means that the issue is already fixed.

After verification in version  20.11, got an impressive improvement.
