### ISSUE TITLE
standard storage spec for HLLs (like datasketches-cpp/aggregateknowledge on druid / postgres) 

### ISSUE THREAD

**Issue by kushagra391** [ClickHouse/ClickHouse#8789]
**Use case**
It [seems](https://www.altinity.com/blog/2017/7/10/clickhouse-aggregatefunctions-and-aggregatestate) that creating native hyperloglog for clickhouse isnt possible unless the raw data is inserted and aggregated using something like `AggregateFunction(uniq, String)`.

It becomes vital for certain cases that this data is created outside the DB using mapreduce / spark. Eg:
- for summarizer jobs (reading TBs of raw data) that are aggregating on keys, are forced to keep HLL raw data in array form
- downstream jobs that aggregate further need access to the raw data. If this step happens outside clickhouse, its just not possible to deconstruct native clickhouse format
- hard for teams migrating from Postgres (AWS RDS) to clickhouse since the batch jobs building postgres HLLs need to be written a different way

For example, consider a table, 
```sql
create table events (
  date Date, 
  cookie String,
  advertiser String, 
  campaign String, 
  domain String,
  imp INT
)
```
table aggregated over cookie, domain
```sql
create table events_uniques (
  date Date, 
  advertiser String, 
  campaign String, 
  imp INT,
  cookie_uniques HLL
)
```
events dataset is in TBs while events_uniques could be a few MBs. 
It doesnt make sense to put events into clickhouse. Rather it would help if events_uniques can be built using `spark` and bulk uplaoded. 

**Describe the solution you'd like**
There are two prominent open source HLL implementations, 
- [incubator-datasketches-cpp](https://github.com/apache/incubator-datasketches-cpp): cpp version of [datasketches](https://datasketches.github.io/docs/Architecture.html) libarry used in druid
- [postgresql-hll](https://github.com/citusdata/postgresql-hll): java library used in postgres HLLs, [storage spec](https://github.com/aggregateknowledge/hll-storage-spec/blob/master/STORAGE.md)

Can clickhouse add support to build / aggregate HLLs using any of the two libraries ? 

**Describe alternatives you've considered**
I dont know a good way to prepare HLL data offline for clickhouse. I would have to insert raw data as a list and then create a new table in clickhouse to convert into HLLs
Either clickhouse should have a java / c++ library to expose HLL operations or follow an already available storage spec

**Additional context**
The problem statement might be confusing. Would request to read through https://databricks.com/blog/2019/05/08/advanced-analytics-with-apache-spark.html on the need for having a standard HLL storage format. 

BTW, am pretty new to clickhouse and evaluating options to migrate data from postgres into clikchouse. Would help if someone could share some pointers on possible implementation or blockers.

**Comment by jason-godden** [comment]
Look at aggregatingmergetree. This is exactly for the use case you describe where you can stream in millions of events and it will automatically construct aggregates and compact. It will be much faster than spark or druid.

**Comment by jason-godden** [comment]
If you can extract the finest granular level of the data in HLL format and reinsert it back into an aggregatingmergetree table that might work. Otherwise you don't need a raw events table. You can insert raw events directly into the aggregatingmergetree table and it will perform roll-up for you as you've specified.

**Comment by den-crane** [comment]
related https://github.com/ClickHouse/ClickHouse/issues/8646

**Comment by kushagra391** [comment]
thanks, yea seems `aggregatingmergetree` or `arrayReduce('uniqState', [A])` is probably the best bet for now. 

Context for a totally decoupled computation was: one may want to build following tables from `events`
- event_unique (with cookie_hll)
- domain_unique (with domain and cookie as HLL cols)
- campaign_uniques (with campaign / domain / cookie as HLL cols)

Its fine if its a simple aggregation but some metrics requires us to do extra filtering / joins before rolling rows up. So, in such cases it easier to do this step outside clickhouse with java / python libraries using custom spark UDAFs with sparkSQL Besides, we could use a large spark cluster to build the metrics quickly and tear it down, rather than introducing auto-scaling issues with clickhouse. 

There are a few other side effects of keeping a copy of raw data (array field in arrayReduce('uniqState', [A])) for backfills or future aggregation like GDPR. So, overall its more an issue of flexibility rather than performance.

**Comment by zhuyoucui0909** [comment]
@jason-godden Could you help to explain more how to insert into aggregatingMergeTree table data, without storing raw data? If possible, could you provide an example?
https://github.com/ClickHouse/ClickHouse/issues/8789#issuecomment-577472482

**Comment by kanterov** [comment]
HLL format is quite complicated, if you can afford to store extra bytes, you can use a roaring bitmap, and then materialize it to uniq state:

```
CREATE TABLE example (
  // byte payload for RoaringBitmap:
  // format: Byte(1), VarInt(SerializedSizeInBytes), ByteArray(RoaringBitmap)
  roaring_bitmap AggregateFunction(groupBitmap, UInt32), 
  uniq_state AggregateFunction(uniq, UInt32)  
            MATERIALIZED arrayReduce('uniqState', bitmapToArray(roaring_bitmap))
) ENGINE = Null
```
