### ISSUE TITLE
Comparison of Date field to DateTime field seems wrong

### ISSUE THREAD

**Issue by Marge-m** [ClickHouse/ClickHouse#8798]
Let's create a table with Date field and insert one row:

> use default
> create table default.td (date Date) Engine=TinyLog();
> insert into default.td (date) values ('2019-04-12')

The server timezone is UTC+3

Then try to convert field to DateTime and compare it to initial field

> select date,  toDateTime(date, 'GMT') as date_gmt, date < date_gmt from default.td

┌──date─┬────date_gmt─┬─less(date, toDateTime(date, 'GMT'))─┐
│ 2019-04-12 │ 2019-04-12 00:00:00 │                                   1                                │
└─────┴─────────┴──────────────────┘

So, date representation is less than datetime representation of _the same_ table cell.
Why? 

Also

> select toDateTime(date) as a, toDateTime(date, 'GMT') as b, a < b as a_is_less from td

┌────────a─┬────────b─┬─a_is_less─┐
│ 2019-04-12 00:00:00 │ 2019-04-12 00:00:00 │          1            │
└─────────┴─────────┴───────┘
It looks very strange. Why is a less than b?

**Comment by amarazm** [comment]
ClickHouse client version 20.1.2.4 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.1.2 revision 54431.

4a9eff2f417b :) select dt, toDateTime(dt,'GMT') dtt, dt = dtt from default.td r;

SELECT
    dt,
    toDateTime(dt, 'GMT') AS dtt,
    dt = dtt
FROM default.td AS r

┌─────────dt─┬─────────────────dtt─┬─equals(dt, toDateTime(dt, 'GMT'))─┐
│ 2019-04-12 │ 2019-04-12 00:00:00 │                                 1 │
└────────────┴─────────────────────┴───────────────────────────────────┘

1 rows in set. Elapsed: 0.020 sec.

**Comment by Marge-m** [comment]
@amarazm 
the problem was in ClickHouse version, the bug is not reproduced in v. 20+

**Comment by Marge-m** [comment]
@amarazm 
the problem was in ClickHouse version, the bug is not reproduced in v. 20+
