### ISSUE TITLE
Support JOIN predicates

### ISSUE THREAD

**Issue by 4ertus2** [ClickHouse/ClickHouse#8802]
It's possible in SQL to write complex ON section. Something like this
```
SELECT * FROM a
JOIN b ON a.id = b.id
    AND (func1(a.x, a.y, a.z) OR func2(a.x, b.x) OR ...)
```
It's OK cause it has equality `a.id = b.id` and we could make it via equi-join. But we should move complex `(func1(a.x, a.y, a.z) OR func2(a.x, b.x) OR ...)` to `WHERE` or support complex filters in JOIN.

**Comment by den-crane** [comment]
Please be careful.  JOIN ON (prejoin predicates) WHERE (postjoin predicates)
You can't just move.

```
psql
create table t(a int, b int);
insert into t values(1,1);

create table s(a int, b int);
insert into s values(1,1);
insert into t values(2,2)

select t.*, s.* from t left outer join s on (t.a=s.a and t.a<>1);
 a | b | a | b
---+---+---+---
 1 | 1 |   |
 2 | 2 |   |
(2 rows)

select t.*, s.* from t left outer join s on (t.a=s.a) where t.a<>1;
 a | b | a | b
---+---+---+---
 2 | 2 |   |
(1 row)
```

**Comment by 4ertus2** [comment]
Yup, we have to move them into subquery's WHERE, not into query's one. It's possible if complex function depends only on one side columns. For expression that depends on both JOIN sides we have to make special filter logic inside JOIN itself (or just throw an exception in first version).

**Comment by mateng0915** [comment]
Does this join predicate pushdown feature is under implementation ?

**Comment by alexey-milovidov** [comment]
@vdimir Please take a look. Maybe it's already implemented?

**Comment by vdimir** [comment]
Solved with https://github.com/ClickHouse/ClickHouse/pull/24420 but still there's some unfinished code

The `hash` and `partial_merge` support predicates in `ON` section:

```sql
SELECT * FROM ( SELECT arrayJoin([1,2,3,4,5,6]) as x ) AS t1
JOIN ( SELECT arrayJoin([2,3,4,5,6,7]) as x ) AS t2
ON t1.x = t2.x AND (t1.x <= 3 OR 5 <= t1.x) AND (t2.x % 2 = 0 OR t2.x % 3 = 0);
```

But it's not allowed to mix columns from `t1` and `t2` in one `AND` argument
```sql
SELECT * FROM ( SELECT arrayJoin([1,2,3,4,5,6]) as x ) AS t1
JOIN ( SELECT arrayJoin([2,3,4,5,6,7]) as x ) AS t2
ON t1.x = t2.x AND (t1.x + t2.x > 0);
-- Code: 403. DB::Exception: Unsupported JOIN ON conditions. Unexpected '(x + t2.x) > 0': While processing (x + t2.x) > 0. (INVALID_JOIN_ON_EXPRESSION) (version 22.8.1.726 (official build))
```
