### ISSUE TITLE
Clichouse shut down after "Cannot schedule a task"

### ISSUE THREAD

**Issue by NursultanKariev** [ClickHouse/ClickHouse#8814]
2020.01.24 10:02:30.791914 [ 3928 ] {391cf19f-14cc-4e91-bf46-7e838bd7817d} executeQuery: Code: 439, e.displayText() = DB::Exception: Cannot schedule a task (version 19.13.2.19) (from [::ffff:172.28.171.217]:59938) (in query: Select * from KPI.K_4G_Util_eNB_CPU FORMAT CSVWithNames ), Stack trace:

clickhouse-server(StackTrace::StackTrace()+0x30) [0x6f28600]
clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x316365f]
clickhouse-server(void ThreadPoolImpl::scheduleImpl(std::function<void ()>, int, std::optional)::{lambda()#1}::operator()() const+0x7e) [0x318fb9e]
clickhouse-server(void ThreadPoolImpl::scheduleImpl(std::function<void ()>, int, std::optional)+0x841) [0x3193031]
clickhouse-server(ThreadPoolImpl::schedule(std::function<void ()>, int)+0x4a) [0x319313a]
clickhouse-server(DB::Aggregator::mergeBlocks(std::map<int, std::list<DB::Block, std::allocatorDB::Block >, std::less, std::allocator<std::pair<int const, std::list<DB::Block, std::allocatorDB::Block > > > >, DB::AggregatedDataVariants&, unsigned long)+0x568) [0x6443778]
clickhouse-server(DB::Aggregator::mergeStream(std::shared_ptrDB::IBlockInputStream const&, DB::AggregatedDataVariants&, unsigned long)+0x5e1) [0x6445851]
clickhouse-server(DB::MergingAggregatedBlockInputStream::readImpl()+0x3fb) [0x63d253b]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63b451a]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63b451a]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63b451a]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ConcatBlockInputStream::readImpl()+0xb4) [0x5db3844]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::Aggregator::execute(std::shared_ptrDB::IBlockInputStream const&, DB::AggregatedDataVariants&)+0x395) [0x644d555]
clickhouse-server(DB::AggregatingBlockInputStream::readImpl()+0x425) [0x6378625]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63b451a]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63b451a]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ConvertingBlockInputStream::readImpl()+0x2e) [0x6396d9e]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::MaterializingBlockInputStream::readImpl()+0x25) [0x63ca045]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63b451a]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]
clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x63b451a]
clickhouse-server(DB::IBlockInputStream::read()+0x238) [0x5c53178]

**Comment by alexey-milovidov** [comment]
This happens if total number of query processing threads is too large.

What is the size of your cluster? How many queries do you process concurrently?
What is the value of max_threads setting?

**Comment by alexey-milovidov** [comment]
Duplicate: https://github.com/ClickHouse/ClickHouse/issues/6833

**Comment by filimonov** [comment]
version 19.13.2.19?

May be it's just another manifestation of https://github.com/ClickHouse/ClickHouse/issues/7383? Actually it shouldn't happen on 19.13 unless you enable trace_log manually (it was enabled in 19.14).

Normally clickhouse rather not create so many threads... So i would focus on looking for the reason of that. Gdb stacktraces would be the best option

**Comment by winter7** [comment]
Hi, I'm wondering if this deadlock bug will not occur without enabling trace_log?

**Comment by filimonov** [comment]
No. Most probably it is #6833 (was fixed recenly). Please update to one of the latest ClickHouse versions 
v19.16.16.72-stable
v20.1.9.54-stable
or
v20.3.5.21-stable (there are few unfixed regressions here yet).

**Comment by winter7** [comment]
@filimonov thanks! You guys release so fast
