### ISSUE TITLE
EXISTS without TABLE literals emit "Аварийный останов"

### ISSUE THREAD

**Issue by TimonKK** [ClickHouse/ClickHouse#8818]
If I create table
`CREATE TABLE test_exists_fail (text String) ENGINE=MergeTree() PARTITION BY tuple() ORDER BY text`
and execute query:
`EXISTS TABLE test_exists_fail` then result is ok.

But if I execute `EXISTS test_exists_fail` I get "Аварийный останов" and go away from `clickhouse-client`

Clickhouse version in 19.17.4.11 (from deb-package), Debian 9.

**Comment by alexey-milovidov** [comment]
We already have bugfix release.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickHouse/blob/master/CHANGELOG.md#clickhouse-release-v1917636-2019-12-27
