### ISSUE TITLE
Send Query Parameters through POST body

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#8842]
I'd like to be able to pass [Query Parameters](https://clickhouse.yandex/docs/en/interfaces/http/#cli-queries-with-parameters) through POST body

`$ curl -sS "<address>?param_id=2&param_phrase=test" -d "SELECT * FROM table WHERE int_column = {id:UInt8} and string_column = {phrase:String}"`

When having high amount of parameters it produces very long URL. Would it make sense to have an option to pass it through POST body as well?

**Comment by alexey-milovidov** [comment]
Yes, we need to implement it.

**Comment by zhang2014** [comment]
It has been implemented in customhttp

**Comment by simPod** [comment]
@zhang2014 do you have a link/reference? Is it this? https://github.com/ClickHouse/ClickHouse/pull/7572  
Thanks!

**Comment by alexey-milovidov** [comment]
@zhang2014 Thank you! Your PR has suspended for unknown reason, I will take it.

**Comment by tavplubix** [comment]
In #7572 query parameters can be sent through URL parameters or request headers for any HTTP method, but looks like it does not allow sending query parameters through POST body.

**Comment by zhang2014** [comment]
I forgot about it when I was trying to resolve the conflict. let me check again.

**Comment by filimonov** [comment]
@zhang2014 are you still planning to fix it?

**Comment by filimonov** [comment]
See one more extra test in https://github.com/ClickHouse/ClickHouse/issues/16383

**Comment by ruslantalpa** [comment]
It seems to be implemented...
This works for me
```
> clickhouse-server --version
ClickHouse server version 22.6.1.411 (official build).
```
```
> curl -X POST -F 'query=select {p1:UInt8} + {p2:UInt8}' -F "param_p1=3" -F "param_p2=4" 'http://default:default@localhost:8123/'
7
