### ISSUE TITLE
ODBC Postgres, Error on select from table with long columns names

### ISSUE THREAD

**Issue by AppKiv** [ClickHouse/ClickHouse#8853]
version 19.17.6.36, ODBC to postgres.
on postgres there is a empty table whith 220 columns, and I try to select data via ODBC, and received ERROR, but it works without exception on version 19.14.3.3

Detail:
on postgres:
drop table if exists tmp.odbc_test;
create table tmp.odbc_test(
sourcename_tablename_fieldname_description_1 text
,sourcename_tablename_fieldname_description_2 text
,sourcename_tablename_fieldname_description_3 text
.....
,sourcename_tablename_fieldname_description_220 text
);

[script_postgres.txt](https://github.com/ClickHouse/ClickHouse/files/4117346/script_postgres.txt)

on click:
select * from odbc('DSN=DWH;','tmp','odbc_test')

Code: 86, e.displayText() = DB::Exception: Received error from remote server .....&max_block_size=65536. HTTP status code: 400 Bad Request, body: (version 19.17.6.36 (official build))
[click.txt](https://github.com/ClickHouse/ClickHouse/files/4117350/click.txt)

**Comment by filimonov** [comment]
Related #9363 ?

**Comment by AppKiv** [comment]
no, I think it's not related,  #9363 - about data, this issue about names - table definition/headers, maybe http-get restriction.
