### ISSUE TITLE
Bad error message when SHOW CREATE TABLE nonexistent.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#8864]
It writes something like "metadata file at /path.../table.sql doesn't exist".

It should check if table doesn't exist and write something like "Table doesn't exist" in that case.

**Comment by filimonov** [comment]
Special case is system tables (which do exists but have no metadata).

**Comment by alexey-milovidov** [comment]
They will continue to have bad exception message (because there was no create table statement).

**Comment by alexey-milovidov** [comment]
We can add some explanation in this case too.
