### ISSUE TITLE
JSONAnalyze aggregate function

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#8867]
**Use case**
The aggregate function takes String argument with JSON and outputs Array with all distinct paths in JSON along with the smallest data type that can accomodate all data values.

Example: 

```
{"a": 123, "b": "2020-01-01T01:02:03Z"}
{"c": [123, 456], "b": "2020-01-01T01:02:03Z", "d": {"a": -1}}
```

The function should return 
```
[
('a', 'Nullable(UInt8)'),
('b', 'DateTime'),
('c', 'Array(UInt16)'),
('d.a', 'Nullable(Int8)')
]
```

**Comment by freedomDR** [comment]
Maybe I can achieve it ？

**Comment by alexey-milovidov** [comment]
@freedomDR This will be very helpful!

**Comment by alexey-milovidov** [comment]
The function should return the inferred type name, as the schema inference would do under the same settings.
Let's start with an ordinary function that will analyze just a single JSON.

**Comment by alexey-milovidov** [comment]
It lost the relevance.
