### ISSUE TITLE
void Coordination::ZooKeeper::receiveThread(): Code: 33, e.displayText() = DB::Exception: Cannot read all data.

### ISSUE THREAD

**Issue by muligolan** [ClickHouse/ClickHouse#8871]
Thanks for the DB, we are currently in stage phase and its performance is amazing!

We load data from with golang to a stage table in clickhouse and as soon as there is enough data in the stage table we move the data to the production table (we deduplicate in order to make sure the data is not already in production).

In ~95% of the times, everything works great but then sometimes we get errors and some of the rows are missing:
```
<Error> void Coordination::ZooKeeper::receiveThread(): Code: 33, e.displayText() = DB::Exception: Cannot read all data. Bytes read: 0. Bytes expected: 4., Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x6d0c010]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x30ee99f]
2. /usr/bin/clickhouse-server() [0x644b17a]
3. /usr/bin/clickhouse-server(Coordination::ZooKeeper::receiveEvent()+0x2a) [0x644c01a]
4. /usr/bin/clickhouse-server(Coordination::ZooKeeper::receiveThread()+0x212) [0x644dd72]
5. /usr/bin/clickhouse-server() [0x644e244]
6. /usr/bin/clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x6642978]
7. /usr/bin/clickhouse-server() [0x74ae81f]
8. /lib64/libpthread.so.0(+0x7dd5) [0x7f8bb65dadd5]
9. /lib64/libc.so.6(clone+0x6d) [0x7f8bb6001ead]
 (version 19.11.4.24)
```

is this related to configuration?
this is my relevant sections:

```xml
<zookeeper>
  <node index="1">
    <host>10.10.100.147</host>
    <port>2181</port>
  </node>
  <node index="2">
    <host>10.10.100.70</host>
    <port>2181</port>
  </node>
  <node index="3">
    <host>10.10.200.223</host>
    <port>2181</port>
  </node>
</zookeeper>
```

my configuration is:
shards - 3
have 1 distributed table in each of the shards and I insert the data into this distributed table.
I have a materialized view on this distributed table however the data is neither in materialized view nor the original tables.

Clickhouse server version: `19.11.4.24`

Thanks for the help

**Comment by den-crane** [comment]
Do you use dedicated servers for Zookeeper nodes?

Check Zookeeper's logs in the same time period.

**Comment by muligolan** [comment]
it happened few days ago and the log of the zookeeper rolled over this part.
the zookeeper servers are separated from clickhouse servers

**Comment by alexey-milovidov** [comment]
It means that ZooKeeper server has closed connection on its own.
ClickHouse will reestablish connection with different ZooKeeper server and continue to work.

Whenever you got an exception on INSERT, you have to repeat the same INSERT with the same data.
