### ISSUE TITLE
LowCardinality(String) is 5-6 times slower than predefined Enum type for same dataset

### ISSUE THREAD

**Issue by krnaveen14** [ClickHouse/ClickHouse#8873]
**Describe the situation**
LowCardinality(String) is 5-6 times slower than predefined Enum type for the same dataset.

**How to reproduce**
```
CREATE TABLE i_8772_lc_order 
(
    `d` Date, 
    `os` LowCardinality(String)
) 
ENGINE = MergeTree 
PARTITION BY d 
ORDER BY os;

insert into i_8772_lc_order select today() - 3, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);
insert into i_8772_lc_order select today() - 2, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);
insert into i_8772_lc_order select today() - 1, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);
insert into i_8772_lc_order select today() - 0, ['aa','bb','cc','dd'][number % 4 + 1] from  numbers(100000000);

select d, os, count() from i_8772_lc_order group by d, os order by d, os;
-- 16 rows in set. Elapsed: 6.107 sec. Processed 400.00 million rows, 1.20 GB (65.49 million rows/s., 196.54 MB/s.)

CREATE TABLE i_8772_enum_order 
(
    `d` Date, 
    `os` Enum8('aa' = 1, 'bb' = 2, 'cc' = 3, 'dd' = 4)
) 
ENGINE = MergeTree 
PARTITION BY d 
ORDER BY os;

insert into i_8772_enum_order select * from i_8772_lc_order;

select d, os, count() from i_8772_enum_order group by d, os order by d, os;
-- 16 rows in set. Elapsed: 1.162 sec. Processed 400.00 million rows, 1.20 GB (344.24 million rows/s., 1.03 GB/s.)
```

**Expected performance**
The underlying structure of Enum might be more compact and efficient than LowCardinality because of predefined values. But the slowness of 5-6 times for this case when using LowCardinality might have some room for performance improvement by utilising the special compact structure of LowCardinality.

**Additional context**
The table structure and data was taken from Issue #8772

**Comment by yuzhichang** [comment]
Similar problem. I notice that `hasAny(arr1, Array(LowCardinality(String)))` is ~70x slower than `hasAny(arr1, Array(UInt32))`.

**Comment by alex-zaitsev** [comment]
Array performance is a known issue, see #6005. We plan to address it soon.

**Comment by alexey-milovidov** [comment]
Performance of array operations was improved.
Performance of GROUP BY multiple fields, with LowCardinality in one of them is still slower than Enum, because the dictionary is dynamic and can be different in different blocks of data.
