### ISSUE TITLE
Implement support of the rest quantiles for Decimal types

### ISSUE THREAD

**Issue by Felixoid** [ClickHouse/ClickHouse#8879]
**Use case**
Put nginx logs with ms after the decimal point and query quantilesTiming on it.

**Describe the solution you'd like**
All quantile* functions will be supported by ClickHouse

**Additional context**
In #5304 support for some of the quantiles were implemented

**Comment by alexey-milovidov** [comment]
The `quantileTiming` function is expected to take the number of milliseconds without the decimal point.
Example: 1234 - 1 second 234 milliseconds.
