### ISSUE TITLE
DB::Exception: Parameters start = 49152, length = 8192 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 54655). (version 20.1.2.4 (official build))

### ISSUE THREAD

**Issue by weery28** [ClickHouse/ClickHouse#8888]
This works fine: 
SELECT a, b, c
FROM t

and this too: 
SELECT a, b
FROM t
WHERE a = 130

but when i do this: 

SELECT a, b, c
FROM t
WHERE a = 130

then clickhouse throws 
 Code: 12, e.displayText() = DB::Exception: Parameters start = 49152, length = 8192 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 54655). (version 20.1.2.4 (official build)). 

This requests worked fine on 19.17...

**Comment by alesapin** [comment]
Maybe you can provide a table definition of `t` and sample data?

**Comment by weery28** [comment]
> Maybe you can provide a table definition of `t` and sample data?

-- auto-generated definition
create table messages1
(
  id                         UUID             default generateUUIDv4(),
  time                       DateTime,
  ident                      String,
  longitude                  Nullable(Float32),
  latitude                   Nullable(Float32),
  altitude                   Nullable(Float32),
  speed                      Nullable(Float32),
  custom                     Nullable(String),
  driver_ident               Nullable(String),
  screw_blocked              Nullable(UInt8),
  screw_active               Nullable(UInt8),
  bunker_fill_sensor         Nullable(Int64),
  carrier                    Nullable(String),
  takeout_id                 Nullable(String),
  takeout_flags              Nullable(String),
  unit_id                    UInt64           default CAST(0, 'UInt64'),
  sats                       Nullable(UInt8),
  hdop                       Nullable(Float32),
  voltage                    Nullable(Float32),
  trailer                    Nullable(String),
  receive_time               DateTime         default now(),
  protocol                   Nullable(String),
  original                   Nullable(String),
  sufficient_onboard_voltage Nullable(UInt8),
  fuel_pulses                Nullable(UInt32),
  fuel_sensor_values         Array(Nullable(Float32)),
  h3_14_index                Nullable(UInt64) default if(isNotNull(longitude) AND isNotNull(latitude),
                                                         geoToH3(toFloat64(assumeNotNull(longitude)),
                                                                 toFloat64(assumeNotNull(latitude)), 14), NULL)
)
  engine = MergeTree()
    PARTITION BY toYYYYMM(time) ORDER BY (ident, time)
    SETTINGS index_granularity = 8192, enable_mixed_granularity_parts = 1;

Same exception on empty table

**Comment by weery28** [comment]
I create same table as select from old and requests from new works fine.

**Comment by jason-godden** [comment]
I encountered the same problem and had to set optimize_move_to_prewhere = 0 for established queries to work.

**Comment by Puwka** [comment]
We are facing the same problem

**Comment by alexey-milovidov** [comment]
This issue is not possible to reproduce without data.
But most likely it was already fixed.
