### ISSUE TITLE
S3 storage credentials renewal error

### ISSUE THREAD

**Issue by jordivilaseca** [ClickHouse/ClickHouse#8897]
I was trying the S3 storage feature for some time (with authentication enabled), at the beginning everything was right and I could read and write data to S3, but after some time the same exact queries were failing. After checking the logs I found some errors related to S3 authentication and it seems it is not able the renew the signature after it expires. 

Clickhouse version: 20.1.2
Query example:
```
INSERT INTO FUNCTION s3('https://<endpoint>/<bucket>/<object>', '<access_key>', '<secret_key>', 'Native', 'ts UInt64') SELECT ts FROM default.<table>
```
Stack trace:
```
20.01.28 10:37:07.373079 [ 71 ] {842650f6-c56b-446d-bcd1-05414d61d95a} <Warning> AWSClient: AWSClient: If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2020.01.28 10:37:07.373100 [ 71 ] {842650f6-c56b-446d-bcd1-05414d61d95a} <Warning> AWSClient: AWSClient: Request failed, now waiting 1600 ms before attempting again.
2020.01.28 10:37:08.980003 [ 71 ] {842650f6-c56b-446d-bcd1-05414d61d95a} <Error> AWSClient: CurlHttpClient: Curl returned error code 27 - Out of memory
2020.01.28 10:37:08.980106 [ 71 ] {842650f6-c56b-446d-bcd1-05414d61d95a} <Error> AWSClient: AWSClient: HTTP response code: -1
```

After some debugging, I could find out that that error does not happen when HTTP protocol is being used (it affects S3 and HTTPS)

**Comment by alexey-milovidov** [comment]
@filimonov It could be related to the OpenSSL issue.

**Comment by filimonov** [comment]
https://github.com/aws/aws-sdk-cpp/issues/931

**Comment by filimonov** [comment]
I think the problem should go away in 20.5 (now Poco HTTP client is used instead of curl).
See also https://github.com/ClickHouse/ClickHouse/pull/11230
