### ISSUE TITLE
Work with GDPR Consent String

### ISSUE THREAD

**Issue by asurovenko** [ClickHouse/ClickHouse#8922]
Hello!
There is a document: [Consent String and Vendor List Format](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md)
There you can look at the table with a bit offset and what it's meaning. If I store those String's in ClickHouse how I can group by values from bits?
For example: in ClickHouse row I store "12345", in binary it's "0011000100110010001100110011010000110101", how I can group values by first 6 bits?
Maybe will be a good idea to add the ability to work with GDPR Consent String in ClickHouse functions.
Thanks!

**Comment by qoega** [comment]
Currently I can propose to read about functions that work with binary representations that can be found in [`bitmap`](https://clickhouse.tech/docs/en/query_language/functions/bitmap_functions/) docs section.

ClickHouse is an OpenSource project where you are welcome to contribute and add any functions, that can be useful for your scenarios. More information about [how to contribute](https://github.com/ClickHouse/ClickHouse/blob/master/CONTRIBUTING.md)

**Comment by blinkov** [comment]
@asurovenko, do you have any further questions?

**Comment by alexey-milovidov** [comment]
Two ways:

1. Convert it to binary with `bin` function and store it in String or FixedString data type. Convert back with `unbin` and select bits with `substring`.
2. Extract all the info into multiple columns before storing the data in a table: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md#vendor-consent-string-format-

**Comment by filimonov** [comment]
That reminds me pack / unpack from python / perl:

https://perldoc.perl.org/perlpacktut
https://docs.python.org/3/library/struct.html
