### ISSUE TITLE
max_result_rows behaviour in new server versions

### ISSUE THREAD

**Issue by xzkostyan** [ClickHouse/ClickHouse#8927]
I've a question about setting `max_result_rows`.

In 19.17.6.36 server version we have exception:

```
ClickHouse client version 19.17.6.36 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.17.6 revision 54428.

xxx :) SET max_result_rows = 5;

SET max_result_rows = 5

Ok.

0 rows in set. Elapsed: 0.007 sec. 

xxx :) SELECT arrayJoin(range(10));

SELECT arrayJoin(range(10))

→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) Received exception from server (version 19.17.6):
Code: 396. DB::Exception: Received from localhost:9000. DB::Exception: Limit for result exceeded, max rows: 5.00, current rows: 10.00. 

0 rows in set. Elapsed: 0.113 sec. 
```

In 20.1.2.4 server version the same query works despite of `max_result_rows` setting:

```
ClickHouse client version 20.1.2.4 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.1.2 revision 54431.

yyy :) SET max_result_rows = 5;

SET max_result_rows = 5

Ok.

0 rows in set. Elapsed: 0.006 sec. 

yyy :) SELECT arrayJoin(range(10));

SELECT arrayJoin(range(10))

┌─arrayJoin(range(10))─┐
│                    0 │
│                    1 │
│                    2 │
│                    3 │
│                    4 │
│                    5 │
│                    6 │
│                    7 │
│                    8 │
│                    9 │
└──────────────────────┘

10 rows in set. Elapsed: 0.007 sec. 
```

What is expected behaviour for this query and `max_result_rows = 5`? In other words: which version contains bug the old or the new one?

Query `SELECT number FROM system.numbers LIMIT 10` works fine in both versions.

**Comment by filimonov** [comment]
It is still actual.

**Comment by alexey-milovidov** [comment]
It works as documented. Slightly more than `max_result_rows` can be returned if more rows are in the same block.

Don't mix up "query complexity settings" with the LIMIT clause.
If you want to limit the number of rows, you should use LIMIT clause.

When you use query complexity settings, the server will check these settings whenever appropriate and act accordingly without any additional efforts - it will stop query execution after first block when the limit is exceeded but it will not do additional work to cut this block precisely.

**Comment by alexey-milovidov** [comment]
New versions work correctly (as documented), the old version (19.17) not.
