### ISSUE TITLE
Close connections to MySQL dictionary source

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#893]
Please close dictionary connections to MySQL source (could by configurable). When there are many nodes and dictionaries, connections rapidly ramp up. For example, we have 100+ dictionaries and 60 nodes -- this results in 6000+ open connections. It is certainly possible to add more memory to MySQL or have several MySQL replicas, but there is no rationale to keep connections open all time as well. MySQL connection is very fast to open when needed but consumes server resources. 

Please consider.

**Comment by bzed** [comment]
@alex-zaitsev using proxysql as a workaround should work (wild guess, never tried it together with clickhouse)

**Comment by alex-zaitsev** [comment]
There are multiple workarounds possible. At the moment we reduced wait_timeout on MySQL side to terminate inactive connections.
