### ISSUE TITLE
Query from Merge table is starting slowly.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#8939]
```
mtexample01i.metrika.yandex.net :) SELECT count() FROM merge(deduplicator_events_deduplicated_hashes, '^DeduplicatedHash')
```

There are 43104 matching tables.

I have already fixed this issue, but the fix was lost after refactoring.

**Comment by alexey-milovidov** [comment]
@CurtizJ is it fixed?
@KochetovNicolai what do you think?

**Comment by CurtizJ** [comment]
Maybe #16988 will fix. But need to check, anyway.

**Comment by KochetovNicolai** [comment]
I did not change anything in StorageMerge
