### ISSUE TITLE
Add support for 'Unspecified' timezone on DateTime

### ISSUE THREAD

**Issue by ikopylov** [ClickHouse/ClickHouse#8941]
**Use case**
Currently when timezone is not specified on `DateTime`, ClickHouse assumes that it is a `DateTime` in local timezone, which sometimes becomes a problem. In my project, I need to store `DateTime` as the local date and time for the timezone from which the data was received. The timezone offset itself is stored in a separate column. In this case it is incorrect to perform any timezone related conversions, the time should be processed as is. To support such functionality I suggest adding a special timezone called 'Unspecified'.

**Describe the solution you'd like**
DateTime with 'Unspecified' timezone (`DateTime('Unspecified')`) should be processed by operations without any timezone related conversion (at least from the user's point of view):
1. `toDateTime('2020-01-01 12:00:00', 'Unspecified')` converts string representation into an offset from Unix epoch to `2020-01-01 12:00:00`.
2. `toString(toDateTime('2020-01-01 12:00:00', 'Unspecified'))` displays `2020-01-01 12:00:00` no matter what local timezone is.
3. `toTimeZone(toDateTime('2020-01-01 12:00:00'), 'Unspecified')`,  `toTimeZone(toDateTime('2020-01-01 12:00:00', 'UTC'), 'Unspecified')`, `toTimeZone(toDateTime('2020-01-01 12:00:00', 'Europe/Moscow'), 'Unspecified')` should give the same `DateTime('Unspecified')` value. From the user's point of view, it simply discards the timezone specification without conversion of date and time. From the internal point of view, it adjusts internal value by the timezone offset.
4. `toTimeZone(toDateTime('2020-01-01 12:00:00', 'Unspecified'), 'UTC')`, `toTimeZone(toDateTime('2020-01-01 12:00:00', 'Unspecified'), 'Europe/Moscow')` do the opposite conversion to the p.3. From the user's point of view, it simply adds back concrete timezone specification without date and time conversion.
5. All comparison operations between `DateTime` in `Unsepcified` timezone and `DateTime` with specified one should implicitly convert the latter to `Unspecified` according to the rules stated in p.3.

**Describe alternatives you've considered**
There is a alternative solution for my particular case - to implement `DateTimeOffset` data type, which additionally  stores the offset component for the concrete timezone, but this is a separate much more complicated task (#8942).

**Comment by alexey-milovidov** [comment]
DateTime is stored as a number containing unix timestamp (the number of seconds from 1970-01-01 00:00:00 UTC).

To convert text (calendar) representation to unix timestamp and vice-versa, you have to use some timezone (probably UTC). But you cannot avoid using timezone.

> 1. toDateTime('2020-01-01 12:00:00', 'Unspecified') converts string representation into an offset from Unix epoch to 2020-01-01 12:00:00.

This is simply not possible. You cannot calculate the offset in seconds to calendar date and time without the knowledge of time zone offset and all time zone conversions that have been done.

**Comment by alexey-milovidov** [comment]
> 2. toString(toDateTime('2020-01-01 12:00:00', 'Unspecified')) displays 2020-01-01 12:00:00 no matter what local timezone is.

It already works this way regardless to the timezone.

**Comment by alexey-milovidov** [comment]
> 3. toTimeZone(toDateTime('2020-01-01 12:00:00'), 'Unspecified'), toTimeZone(toDateTime('2020-01-01 12:00:00', 'UTC'), 'Unspecified'), toTimeZone(toDateTime('2020-01-01 12:00:00', 'Europe/Moscow'), 'Unspecified') should give the same DateTime('Unspecified') value. From the user's point of view, it simply discards the timezone specification without conversion of date and time. From the internal point of view, it adjusts internal value by the timezone offset.

`toTimeZone` function does not adjust the internal value. This function is free, it only changes the type metadata and does not modify data. Unix timestamp is independent of time zone.

**Comment by alexey-milovidov** [comment]
> There is a alternative solution for my particular case - to implement DateTimeOffset data type, which additionally stores the offset component for the concrete timezone, but this is a separate much more complicated task.

Yes, you can store time zone offset. But care should be taken because single time zone may have variable time zone offset for different points in time.
