### ISSUE TITLE
DB::Exception: Missing columns: while processing query on computed columns based on subselect with count

### ISSUE THREAD

**Issue by instplanet** [ClickHouse/ClickHouse#8959]
Hi,

I have some issues when trying to create a computed column based on count on subselect using the following structure of query
```
SELECT
    COLUMN_A,
    (SELECT COUNT(PK) FROM TABLE_B WHERE TABLE_B.PK = TABLE_A.PK) AS TOTAL,
FROM TABLE_A
```

This is supposed to work, but throw the following error:
```
DB::Exception: Missing columns: while processing query (version 19.17.6.36 (official build))
```

Thank you very much

**Comment by den-crane** [comment]
Correlated subqueries are not supported. Use Joins.
