### ISSUE TITLE
Type name case sensitivity

### ISSUE THREAD

**Issue by killwort** [ClickHouse/ClickHouse#8962]
The documentation states that everything except SQL keywords is case sensitive:
https://clickhouse.tech/docs/v20.1/en/query_language/syntax/#syntax-keywords
However this SQL is considered valid:
```
create table if not exists DoubleTimeArchive 
     (tag String,time datetime , value Float64 , changeStamp  datetime) 
       ENGINE = MergeTree()  ORDER BY  (time,changeStamp);
```
And it creates the table preserving type name casing in result row schemas. This behavior confuses clients (my .NET driver is unable to parse such types) and JetBrains DataGrip says that it doesn't know about "datetime" type.

Should I implement case-folding in my .NET driver and the documentation be fixed to follow actual implementation or is it a bug and type names should remain case sensitive?

**Comment by filimonov** [comment]
Motivation is very simple - it IS a SQL keyword :/

https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15

https://dev.mysql.com/doc/refman/8.0/en/datetime.html

Etc. 

In general - check `system.data_type_families` table, it has the answer to that question.

**Comment by killwort** [comment]
Ok, I'd implement type aliasing in my driver 'cause there are some weird cases when case folding is inappropriate: TINYBLOB->String.

Still, this functionality must be explicitly documented.

**Comment by alexey-milovidov** [comment]
The issue is related to this PR https://github.com/ClickHouse/ClickHouse/pull/8370
It is questionable and we're considering that it can be partially or fully reverted.

**Comment by alexey-milovidov** [comment]
About the question "Type name case sensitivity".

We support case insensitive names when they correspond to the SQL standard or when they correspond to the implementation of some popular DBMS (MySQL or Postgres).

**Comment by killwort** [comment]
Why bother with MySQL/PSQL type-compatibility if other SQL parts are not compatible with anything else? E.g. CREATE syntax, bulk INSERT syntax, SELECT/JOIN syntax.

**Comment by alexey-milovidov** [comment]
@killwort We have intention to make most of the typical use cases compatible.

We'll make CREATE syntax compatible: by adding support for complex type expressions like CHAR VARYING NOT NULL...

**Comment by alexey-milovidov** [comment]
We have implemented SQL compatible data types that are also case-insensitive. Example:
```
CREATE TEMPORARY TABLE test (x char varying not null)
```
