### ISSUE TITLE
Insert failed due to "Too many parts" after zookeeper restarted

### ISSUE THREAD

**Issue by liwanxue** [ClickHouse/ClickHouse#8968]
We were testing our clickhouse cluster(3 zk, 10 shard, each shard 2 replica) 
When we restart one zookeeper, we found that insert failed due to "Too many parts". 

Our data flow as, go application will write data using jdbc to a buffer tables. and a table which is replicated summing merge tree, also 3 materilize view based on that. 
After we restart one zookeeper, we found a zk disconnect, but data flow is still working. around 20 minutes later, we found all the write failed due to "Too many parts". But at this time, zk already started and works good. 

But after 2hrs later, the write success again. We're confused about this behavior. 
From clickhouse server logs, it looks "ReplicatedMergeTreeCleanupThread" and "ReplicatedMergeTreeRestartingThread" isn't running during that time. Somehow, it starts running after 2hrs. 

Do you have any clue about this?  I guess it might related to lifecycle of part. Could you share some insight about lifecycle and "ReplicatedMergeTreeCleanupThread" and "ReplicatedMergeTreeRestartingThread"?

**Comment by den-crane** [comment]
Clickhouse version?
Logs?

**Comment by liwanxue** [comment]
version: 19.14.7.15
it's huge log,put it here  link: https://pan.baidu.com/s/1EaOSMU6u6riLu2Rob2MnNw     verification code: 339s 
restart time is "2020.01.20 05:33" and recover time is "2020.01.20 07:13"

**Comment by liwanxue** [comment]
> Clickhouse version?
> Logs?

Information as above. Do you have any clue?

**Comment by den-crane** [comment]
I've never downloaded that file, I don't speak Chinese.

**Comment by filimonov** [comment]
@liwanxue I've tried to download the logs, but it looks like that is possible only if you have an account in Baidu, which requires a Chinese mobile phone. 

You can try to put it into some other file sharing service.

In general, after zookeeper disconnects, it makes take some time to recover/restart threads.
During that time the merge queue may grow.

**Comment by gubinjie** [comment]
@filimonov @den-crane  Hello
We use hdfs engine: table1, data volume 400 million data volume, more than 500 columns
Insert table1 data into ClickHouse's MergeTree table, there are too many parts abnormal problems, are there any parameters or other solutions that need to be changed?
Our version number: 20.1.4.14
Thank you

**Comment by liwanxue** [comment]
I already figure out the root cause of my issue, it caused by wrong configuration of zookeeper, which lead to zookeeper can't elected leader or brain split, which caused too many parts. Thanks all of you.
