### ISSUE TITLE
Push down predicate for View doesn't work

### ISSUE THREAD

**Issue by TimonKK** [ClickHouse/ClickHouse#8971]
I have:
1. table:
`CREATE TABLE loadstat (`date` Date, `userId` String, `_id` String, `host` String) ENGINE = ReplacingMergeTree() PARTITION BY date ORDER BY (host, userId, _id) SETTINGS index_granularity = 8192`

2. data:
`INSERT INTO loadstat SELECT toDate(now() - (1000000 - number) * 1) AS date, toUUID(number % 1000) AS userId, toUUID(number), CONCAT('ya', toString(number % 1000), '.ru') FROM system.numbers LIMIT 1000000 SETTINGS max_partitions_per_insert_block = 100000`

2. view for table:
`CREATE VIEW loadstat_view (`date` Date, `userId` String, `_id` String, `host` String) AS SELECT * FROM loadstat ` 

When I do query for table:
`SELECT 
    toStartOfMonth(date) AS dt, 
    count(*)
FROM loadstat
WHERE date >= '2020-01-29'
GROUP BY dt
ORDER BY dt ASC`
it works as expected:
`2 rows in set. Elapsed: 0.008 sec. Processed 481.12 thousand rows, 962.23 KB (63.99 million rows/s., 127.98 MB/s.)` - Clickhouse uses predicate `date >= '2020-01-29'` for table.

But if I do query for view I get:
`2 rows in set. Elapsed: 0.024 sec. Processed 1.00 million rows, 2.00 MB (41.20 million rows/s., 82.39 MB/s.) ` - I get full scan all table's data

Optimizations `enable_optimize_predicate_expression` and `enable_optimize_predicate_expression_to_final_subquery` are enable.

Before update to 20.1.3.7 push down predicate used to work

**Comment by 4ertus2** [comment]
Related #6767 #6972

**Comment by TimonKK** [comment]
Any idea how to "fix" it? I use a lot of views and my instance of Clickhouse make useless io
