### ISSUE TITLE
Clickhouse Table Addtion - ZooKeeper Sync Issue

### ISSUE THREAD

**Issue by sundarv85** [ClickHouse/ClickHouse#8976]
clickhouse server v18.14.13

We are using replication merge tree with zookeeper. We have 3 shards and 3 replicas (total 6) clickhouse nodes.

We wanted to add 4 new fields in a particular table. We added it successfully in all the 5 nodes except 1 node. This 1 node, when we tried to alter the table, it said the zookeeper and this node were not in sync, so it was not allowing us to add these 4 fields. Also, we were not able to restart the clickhouse server (it kept saying that the metadata/_table__shard.sql file is not in sync with zookeeper).

So what we did was, we manually edited this file (table-shard.sql) alone in this node and inserted the 4 fields, and then restarted the clickhouse server.  This got us working and data is also now written in all clickhouse servers. 

However,  zookeeper keeps creating logs/snapshots continuously and eventually all the 3 zookeeper nodes run out of hard disk space. The error we see in zookeeper.log file is

> 2020-02-03 15:53:15,407 - INFO  [NIOServerCxn.Factory:/10.132.1.33:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /10.132.1.33:38546
>
> 2020-02-03 15:53:15,410 - WARN  [NIOServerCxn.Factory:/10.132.1.33:2181:NIOServerCnxn@357] - caught end of stream exception
> EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
>
> 	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:230)
> 	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
> 	at java.lang.Thread.run(Thread.java:748)
>
> 2020-02-03 15:53:15,410 - INFO  [NIOServerCxn.Factory:/10.132.1.33:2181:NIOServerCnxn@1008] - Closed socket connection for client /10.132.1.33:38546 (no session established for client)

Any thoughts on how to solve it?

**Comment by den-crane** [comment]
>clickhouse server v18.14.13

And it's not supported. Only 20.1.2, 19.17, 19.16 are supported.

>We added it successfully in all the 5 nodes except 1 node. 

??? You need to add new columns only at 3 servers (alter is replicated by ReplicatedMergeTree).

>it said the zookeeper and this node were not in sync

Need CH logs.

-----


>keeps creating logs/snapshots continuously and eventually 
>all the 3 zookeeper nodes run out of hard disk space

Expected behavior unrelated to the issue. And it's default ZK behavior.
https://clickhouse.tech/docs/en/operations/tips/#zookeeper

_With the default settings, ZooKeeper is a time bomb:
    >The ZooKeeper server won't delete files from old snapshots and logs when using the default 
   >configuration (see autopurge), and this is the responsibility of the operator.
This bomb must be defused._

**Comment by sundarv85** [comment]
@den-crane The logs when the issue happened in Clickhouse are not available any longer. However, now the clickhouse is working correctly and there are no other logs that we see in Clickhouse.

The only error seems to be in zookeeper itself and its log shows only this information, as posted in the issue. Posting it again here

```

2020-02-03 15:53:15,407 - INFO [NIOServerCxn.Factory:/10.132.1.33:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /10.132.1.33:38546

2020-02-03 15:53:15,410 - WARN [NIOServerCxn.Factory:/10.132.1.33:2181:NIOServerCnxn@357] - caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket

at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:230)
at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
at java.lang.Thread.run(Thread.java:748)

2020-02-03 15:53:15,410 - INFO [NIOServerCxn.Factory:/10.132.1.33:2181:NIOServerCnxn@1008] - Closed socket connection for client /10.132.1.33:38546 (no session established for client)
```

We also connected in the zookeeper zkCli and did a `sync /` and it was Ok. Still we keep seeing this error. Any other tips on what to look for?

**Comment by blinkov** [comment]
@sundarv85, do you have any further questions?

**Comment by sundarv85** [comment]
@blinkov we still were not able to figure out what is causing this issue? We are currently just deleting the snapshots using the cron. Any pointers on how to fix this would be really helpful

**Comment by blinkov** [comment]
@sundarv85 I think nobody has actually tried to reproduce it, at least because you are using an obsolete version, have you managed to upgrade to some recent one that's still supported?

**Comment by sundarv85** [comment]
@blinkov how safe is it to  upgrade to the latest version.. this is production db.. so we are not really sure if we could just upgrade.. Btw, does clickhouse offer any LTS releases..

**Comment by blinkov** [comment]
@sundarv85 you need to see for yourself on your testing/preproduction environments. And don't forget to check the changelog for warnings and incompatible changes.

The latest LTS release is 20.3, they are supported for a year.

**Comment by sundarv85** [comment]
Thanks @blinkov We will try upgrading and check.
