### ISSUE TITLE
Missing data parts after restoring it from older CH version onto newer 

### ISSUE THREAD

**Issue by Garnek20** [ClickHouse/ClickHouse#8979]
In order to perform CH upgrade from version  to `19.16.10.44` we followed the following steps:
- we spawned entirely new cluster `v19.16.10.44`
- we created tables (tables as in prod)
- restored data from s3 (previously backed up from prod in a NATIVE format - copy of all the parts) - copied into detached folder and then attach accordingly
- restart all nodes in order to apply setting `enable_mixed_granularity_parts` for MergeTree Engine

After restart we've noticed the following logs:
```DB::Exception: No <column>.mrk file checksum for column <column> in part .../20190201_1_1_0/```
Followed by: ```Considering to remove broken part .../20190201_1_1_0 because it's impossible to repair ```

And eventually, after some time:
``` 
2020.01.30 16:49:41.760398 [ 31 ] {} <Warning> (ReplicatedMergeTreePartCheckThread): Checking part 20190201_1_1_0
2020.01.30 16:49:41.760904 [ 31 ] {} <Warning> (ReplicatedMergeTreePartCheckThread): Checking if anyone has a part covering 20190201_1_1_0.
2020.01.30 16:49:41.775452 [ 31 ] {} <Error> (ReplicatedMergeTreePartCheckThread): No replica has part covering 20190201_1_1_0 and a merge is impossible: we didn't find smaller parts with either the same min block or the same max block.
2020.01.30 16:49:41.777693 [ 31 ] {} <Error> (ReplicatedMergeTreePartCheckThread): Part 20190201_1_1_0 is lost forever.
```

That resulted in lost partitions.

Tables on production are using `ReplicatedCollapsingMergeTree` engine. They were create on version `19.4.1.1`. After some times we altered them in order to add some columns. It seems that parts that do not contain added columns are being `lost forever`.

Table DDL
```
CREATE TABLE table_name ON CLUSTER '{cluster_name}'
(
  sign Int8, --field needed for the CollapsingMergeTree
  
  date Date,
  id1 UInt32,
  id2 UInt64,
  screen_height UInt16,
  screen_width UInt16,
  session_number_of_views UInt16, 
  session_duration_msec UInt32, 
  language LowCardinality(String),
  city LowCardinality(String),
  country_code LowCardinality(String),
  nested_thingy Nested 
  (
    key String,
    value String
  ),
  version LowCardinality(String),
  browser_name LowCardinality(String), 
  browser_major_version UInt16,
  browser_version LowCardinality(String),
  platform_name LowCardinality(String),
  platform_version LowCardinality(String),
  referer_url String,
  custom_vars_session Nested
  ab_test_info Nested
  (
    abtest_id UInt32, 
    abtest_version UInt16
  ),
  external Nested
  (
    id String,
    hashed_id UInt64,
    provider UInt8
  ),
  has_playback_recorded UInt8, 
  density Float32,
  session_connectivity_types UInt8,
  os_version UInt64,
  sdk_build_number UInt64,
  manufacturer LowCardinality(String),
  model LowCardinality(String),
  precomputed_random Int32, 
) ENGINE = ReplicatedCollapsingMergeTree('/{cluster_name}-{env}/tables/shard{shard}/table_name', '{replica}', sign)
PARTITION BY (date)
ORDER BY (...)
SAMPLE BY id
SETTINGS index_granularity=16834
;

```

**Comment by huiwangcs** [comment]
@alesapin would it be possible to explain the root cause of this problem?

**Comment by Garnek20** [comment]
@alesapin Hello, did you get some time to take a look at this issue?

**Comment by ropiteaux** [comment]
@alesapin Hello, any news on this? Would it work with `20.3.8.53`? Thks

**Comment by filimonov** [comment]
> copied into detached folder and then attach accordingly

How did you do that? Do you use FREEZE or stop the server ? When you back up a active working copy you can get inconsistant copy.

> B::Exception: No <column>.mrk file checksum for column <column> in part .../20190201_1_1_0/

Does the folder have that file?

**Comment by den-crane** [comment]
I could not reproduce this issue.
Maybe it needs more than 1 replica
```

18.14.19 
create table TX(A Int64, B String) Engine = MergeTree order by tuple();
insert into TX values(1, '1');
alter table TX add column Y String;
alter table TX freeze partition tuple();

ls shadow/.../all_1_1_0 
A.bin  A.mrk  B.bin  B.mrk  checksums.txt  columns.txt	count.txt

!!! No  Y  column in freezed part

19.16.10.44

CREATE TABLE dw.TX ( A Int64,  B String,  Y String) ENGINE = ReplicatedMergeTree('/test/txxxxxx', '1')  ORDER BY tuple()
insert into TX values(2, '2', '2');
cp all_1_1_0  ../detached
alter table TX attach partition tuple()

SELECT * FROM TX

┌─A─┬─B─┬─Y─┐
│ 2 │ 2 │ 2 │
└───┴───┴───┘
┌─A─┬─B─┬─Y─┐
│ 1 │ 1 │   │
└───┴───┴───┘

ls all_0_0_0
A.bin  A.mrk2  B.bin  B.mrk2  checksums.txt  columns.txt  count.txt  Y.bin  Y.mrk2

ls all_1_1_0/
A.bin  A.mrk  B.bin  B.mrk  checksums.txt  columns.txt	count.txt

enable_mixed_granularity_parts=1
restart 

SELECT * FROM TX

┌─A─┬─B─┬─Y─┐
│ 2 │ 2 │ 2 │
└───┴───┴───┘
┌─A─┬─B─┬─Y─┐
│ 1 │ 1 │   │
└───┴───┴───┘


enable_mixed_granularity_parts=0
restart fails  Table contains parts with adaptive and non adaptive marks, but `setting enable_mixed_granularity_parts` is disabled,


enable_mixed_granularity_parts=1
restart

SELECT * FROM TX

┌─A─┬─B─┬─Y─┐
│ 2 │ 2 │ 2 │
└───┴───┴───┘
┌─A─┬─B─┬─Y─┐
│ 1 │ 1 │   │
└───┴───┴───┘



```

**Comment by ropiteaux** [comment]
> > copied into detached folder and then attach accordingly
> 
> How did you do that? Do you use FREEZE or stop the server? When you back up an active working copy you can get inconsistent copy.
We have a backup job in golang that does the backup to S3 every day, it does so by using FREEZE yes. (the backup job use SQL statements on CH). Moreover, the restoration of data worked perfectly on the same version of ClickHouse (19.4.1.1) but failed on the mentioned partition for 19.16.10.44...

> > B::Exception: No .mrk file checksum for column  in part .../20190201_1_1_0/
> 
> Does the folder have that file?
We only have retention of 13month, so no access to that folder anymore, but as @den-crane showed, the column is not present in an ancient partition and it shouldn't be an issue.

Additional info: we are using 6 shards composed of 2 replicas each for our cluster. We couldn't reproduce the failing behavior locally with docker-compose.

**Comment by alesapin** [comment]
Hi, sorry for the long answer. It seems like index granularity is not relevant to this issue. This error says that checksum in file `checksums.txt` is absent for file `<column>.mrk`. So probably you have broken checksums in your back, but to investigate I'd like to look at `checksums.txt` file. Also, it's not clear, but is it possible to reproduce the error somehow? Also, I recommend updating to at least the latest LTS version 20.3.

@den-crane's test is correct and this behavior is expected.
