### ISSUE TITLE
ZooKeeper heap size is increasing

### ISSUE THREAD

**Issue by simPod** [ClickHouse/ClickHouse#8980]
Hello, I have completely migrated my ClickHouse to replicated merge tree family, even though I'm running only one replica.

Our zookeeper memory usage started to grow

![image](https://user-images.githubusercontent.com/327717/73679544-ebabfd00-46ba-11ea-9652-1387e791df84.png)

Have anyone encountered the same issue? What might be causing it? The utilisation before was stable. Current heap size is set to 1 GB.

`use_minimalistic_part_header_in_zookeeper` is set to 1

**Comment by den-crane** [comment]
Zookeeper is in-memory DB

Check your DB size
```
echo mntr | nc zoo1 2181|grep data_size
zk_approximate_data_size	122079537
```

1GB is tiny for real production. I use `-Xms8g`

**Comment by simPod** [comment]
Ah kk cool. Thanks for info. We did not know what values to expect so we have initially set it rather low. Thanks for confirmation it's fine. It has stopped growing on about 2G.
