### ISSUE TITLE
Choosing partition key for tickdata database

### ISSUE THREAD

**Issue by mvcalder-xbk** [ClickHouse/ClickHouse#8987]
We are using clickhouse to store tickdata for tens of thousands of instruments for thousands of days, and we are wondering if using date ('yyyy-mm-dd') as the partition key will result in performance degradation.

What impacts performance, the number of partitions in a table, or the number of partitions spanned by a query?

We expect our query patterns to span no more than 3 dates, but from the [documentation](https://clickhouse.tech/docs/en/operations/table_engines/custom_partitioning_key/) it sounds like performance will suffer if we have more than ~1000 dates in our table (even if a particular query spans only a couple of partitions).

```
This means you shouldn't make overly granular partitions (more than about a thousand partitions).
Otherwise, the SELECT query performs poorly because of an unreasonably large number of files in
the file system and open file descriptors.
```

**Comment by den-crane** [comment]
>We expect our query patterns to span no more than 3 dates

Then daily partitioning is reasonable and will improve your performance. 

>but from the documentation it sounds like performance

performance MAY suffer if your query have to process 1000 partitions instead of 10 partitions.

But you need to write SQL queries wisely and check that partition pruning works against them.

**Comment by mvcalder-xbk** [comment]
Thanks @den-crane that clarifies things.
