### ISSUE TITLE
Error while creating the build

### ISSUE THREAD

**Issue by vigneshrajarr** [ClickHouse/ClickHouse#8990]
**OS** - Mac Catalina - 10.15.1
**Cmake version** - 3.15.5
**Ninja version** - 1.10.0

**Compiler name and version**
AppleClang 11.0.0.11000033
LLVM 8

**Full cmake and/or ninja output**
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using custom linker by name: /usr/local/llvm-8/bin/ld.lld
-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Disabling compiler -pipe option (have only 5747 mb of memory)
-- Performing Test HAVE_SSE41
-- Performing Test HAVE_SSE41 - Failed
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Failed
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Failed
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Failed
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Failed
-- Performing Test HAVE_PCLMULQDQ
-- Performing Test HAVE_PCLMULQDQ - Failed
-- Performing Test HAVE_POPCNT
-- Performing Test HAVE_POPCNT - Failed
-- Default libraries: -nodefaultlibs  -lc -lm -lpthread -ldl
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/darwin/default_libs.cmake:30 (find_package)
  CMakeLists.txt:245 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/vignesh-4257/clickhouse/ClickHouse/build/CMakeFiles/CMakeOutput.log".
See also "/Users/vignesh-4257/clickhouse/ClickHouse/build/CMakeFiles/CMakeError.log".

[CMakeError.log](https://github.com/ClickHouse/ClickHouse/files/4151699/CMakeError.log)
[CMakeOutput.log](https://github.com/ClickHouse/ClickHouse/files/4151700/CMakeOutput.log)

**Comment by vigneshrajarr** [comment]
Can anyone help me here ?

**Comment by abyss7** [comment]
We don't support build with Apple Clang. Please, get the Clang Compiler Suite from LLVM - via Brew, downloading binary from their website, or building it on your own.

**Comment by vigneshrajarr** [comment]
Even tried with llvm compiler, error occurs again

-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/local/Cellar/llvm@8/8.0.1_1/bin/clang
-- Check for working C compiler: /usr/local/Cellar/llvm@8/8.0.1_1/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Cellar/llvm@8/8.0.1_1/bin/clang++
-- Check for working CXX compiler: /usr/local/Cellar/llvm@8/8.0.1_1/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using custom linker by name: /usr/local/Cellar/llvm@8/8.0.1_1/bin/ld.lld
-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE is not set, set to default = RELWITHDEBINFO
-- CMAKE_BUILD_TYPE: RELWITHDEBINFO
-- Disabling compiler -pipe option (have only 5771 mb of memory)
-- Performing Test HAVE_SSE41
-- Performing Test HAVE_SSE41 - Failed
-- Performing Test HAVE_SSE42
-- Performing Test HAVE_SSE42 - Failed
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Failed
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Failed
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Failed
-- Performing Test HAVE_PCLMULQDQ
-- Performing Test HAVE_PCLMULQDQ - Failed
-- Performing Test HAVE_POPCNT
-- Performing Test HAVE_POPCNT - Failed
-- Default libraries: -nodefaultlibs  -lc -lm -lpthread -ldl
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/darwin/default_libs.cmake:30 (find_package)
  CMakeLists.txt:245 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/vignesh-4257/clickhouse/ClickHouse/build/CMakeFiles/CMakeOutput.log".
See also "/Users/vignesh-4257/clickhouse/ClickHouse/build/CMakeFiles/CMakeError.log".

`which clang` - **/usr/local/Cellar/llvm@8/8.0.1_1/bin/clang**
Installed using `brew`

setting PATH to `/usr/bin/clang` builds successfully. But then again `ninja` throws warnings and errors.

[clang_success.txt](https://github.com/ClickHouse/ClickHouse/files/4230385/run.txt)
[ninja_output.txt](https://github.com/ClickHouse/ClickHouse/files/4230384/ninja_output.txt)

**Comment by abyss7** [comment]
Please, provide the contents of CMakeFiles/CMakeError.log

**Comment by vigneshrajarr** [comment]
[CMakeError.log](https://github.com/ClickHouse/ClickHouse/files/4230842/CMakeError.log)
[CMakeOutput.log](https://github.com/ClickHouse/ClickHouse/files/4230844/CMakeOutput.log)

**Comment by alexey-milovidov** [comment]
> We don't support build with Apple Clang.

Let's add a check in CMake with a proper error message?

**Comment by abyss7** [comment]
What version of ClickHouse do you try to build?

**Comment by abyss7** [comment]
Probably the problem is with the linker: /usr/local/Cellar/llvm@8/8.0.1_1/bin/ld.lld - you should use native linker (ld.ld64 I guess).

**Comment by vigneshrajarr** [comment]
>What version of ClickHouse do you try to build?

How can I check that ?
Latest one in CHANGELOG.md is v20.1.2.4. Will this help ?

>Probably the problem is with the linker: /usr/local/Cellar/llvm@8/8.0.1_1/bin/ld.lld - you should use native linker (ld.ld64 I guess).

Do you mean `ld64.lld` ? Removing `ld.lld` directly invokes the `lld` driver.

**Comment by abyss7** [comment]
You should use CMake option `-DLINKER_NAME=/path/to/linker` to force using native linker.

**Comment by fredchenbj** [comment]
using the native linker "/usr/bin/ld" would be ok. @vigneshrajarr

**Comment by vigneshrajarr** [comment]
Thanks @fredchenbj , it helped. After CMake, `ninja` built CH with some warnings, but no errors. PFA.

After that, `~/Clickhouse/build/dbms/programs/clickhouse-server` is not starting the server, throwing the following error.

`Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = File not found: config.xml (version 20.2.1.1)`

Any `config.xml` need to be created manually ? There are no such mentions in the [documentation](https://clickhouse.tech/docs/en/development/build_osx/).

[ninja_output.txt](https://github.com/ClickHouse/ClickHouse/files/4244970/ninja_output.txt)

**Comment by alexey-milovidov** [comment]
configs are located in source directory:

`~/Clickhouse/dbms/programs/server`

You can go to the source directory and create a symlink `clickhouse-server` to the built binary.

**Comment by vigneshrajarr** [comment]
My issues have been fixed.
For reference:
While installing in MAC, following changes have been made for making it to work.
1. Installing dependencies and clone is done as given in docs.
2. While compiling using CMake, native compiler is used.
By passing the param, `-DLINKER_NAME=/usr/bin/ld`
3. Again follow the doc, and update `maxfiles` system variable.
4. The `config.xml` file is present in the `<root>/dbms/programs/server`. It is needed to start the CH server.
Either a symbolic link is created or the path is passed to the param `--config`.
like `./dbms/programs/clickhouse-server --config=../dbms/programs/server/config.xml`
