### ISSUE TITLE
uniqState memory leak

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#8995]
**Describe the bug or unexpected behaviour**
PR #4277 states that there is a memory leak in uniqState.

At least it was in version
ClickHouse: v19.1.6

**How to reproduce**

```
for i in {1..1000}; do clickhouse-client --max_memory_usage 100000000 <<< "SELECT uniqExactState(number) FROM system.numbers GROUP BY number % 1000"; done
```

**Expected behavior**
Memory usage should be bounded.

**Additional context**
We should check if bug is still present and fix it.

**Comment by filimonov** [comment]
BTW if we will just create a test showing the memory leak - won't address sanitizer just show the place?
https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer

**Comment by alexey-milovidov** [comment]
@filimonov Yes, it will show memory leak (assuming the process is correctly terminated).

**Comment by alexey-milovidov** [comment]
@akuzm just forgot about this task.

**Comment by akuzm** [comment]
> @akuzm just forgot about this task.

Thankfully we have github so we don't have to remember. The reason I'm not doing anything about this task is that it doesn't seem a particularly high priority to me, and there is always a lot of other things to do.

**Comment by azat** [comment]
Correct me if I'm wrong, but I guess this is not a leak (i.e. RSS/VIRT is fine) but the memory tracking issue (i.e. `MemoryTracking` from the `asynchronous_metrics`, that also uses for memory limit checks).
If my assumption is correct then I've already have a fix for it (came to it while I was on #10818).

P.S. actually 20.4 already has a [quirk](https://github.com/ClickHouse/ClickHouse/blob/1ccd4fb9788e4f40cc774da560bda9bda17ce183/src/Interpreters/AsynchronousMetrics.cpp#L154) to fix this

**Comment by azat** [comment]
>Correct me if I'm wrong, but I guess this is not a leak

Ignore this message, didn't look carefully, sorry

**Comment by alexey-milovidov** [comment]
@akuzm memory leak is the top priority bug. It just should not exist.
