### ISSUE TITLE
geospatial h3 functions missing

### ISSUE THREAD

**Issue by rsurgiewicz** [ClickHouse/ClickHouse#8996]
Hi there,

I'm trying to use h3 geospatial features build-in clickhouse.
function `geoToH3` works great but others are missing(?)

sample:
`h3ToParent` missing
`h3ToString`  missing
I'm getting: 
`host: localhost, port: 8123; Code: 46, e.displayText() = DB::Exception: Unknown function h3ToString. Maybe you meant: ['toString','h3kRing'] (version 20.1.3.7 (official build))`

According to docs should work: https://clickhouse.tech/docs/en/query_language/functions/geo/#h3tostring

clickhouse: version 20.1.3.7 (official build)

**Comment by den-crane** [comment]
They are not released yet. Try night-built https://repo.yandex.ru/clickhouse/deb/testing/main/
20.2.1.2308 for example.

**Comment by rsurgiewicz** [comment]
oh sorry for pointing-out but why is stated in docs or am I blind?

**Comment by den-crane** [comment]
Because by default the documentation reflects master branch
<img width="672" alt="Screen Shot 2020-02-04 at 11 05 37 AM" src="https://user-images.githubusercontent.com/19737682/73756780-8568be00-473e-11ea-9f8e-736c43c15caf.png">

**Comment by rsurgiewicz** [comment]
clear, thanks
