### ISSUE TITLE
Create MATERIALIZED VIEW against ReplicatedMergeTree and Distributed tables

### ISSUE THREAD

**Issue by hatrena** [ClickHouse/ClickHouse#8999]
I am trying to create VM for my cluster. before getting to the point here is the details:

I have 2 shards and 2 replicas in each.

Details:

cluster name: _clicks_cluster_

I have a replicated table:
```
CREATE TABLE default.clicks_replicated
(
    ...
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/default/clicks_replicated', '{replica}')
PARTITION BY (...)
ORDER BY (...)
SETTINGS index_granularity = 8192;
```

Then I created the distributed from it:
```
CREATE TABLE IF NOT EXISTS default.clicks_distributed AS default.clicks_replicated
ENGINE = Distributed(clicks_cluster, default, clicks_replicated, cityHash64(my_column));
```

Now I want to create a VM.:

But I found out I don't get the new data if I create it against `clicks_distributed`  with `ENGINE = SummingMergeTree` 

Also creating it against `clicks_replicated` will lead to incomplete data per replica. 

what would be the query for creating VM in this case?

**Comment by den-crane** [comment]
Materialized View is an insert trigger. It gets data from INSERT. It never reads/selects a source table.

The most used schema to create at **all nodes** the **same set of tables / MVs**. MV's also **replicated** Engine.


CREATE TABLE default.clicks_replicated
(
)
ENGINE = ReplicatedMergeTree

CREATE MATERIALIZED VIEW default.clicks_replicatedMV 
Engine= **ReplicatedSummingMergeTree**
as select .... **from default.clicks_replicated**

....
CREATE TABLE IF NOT EXISTS default.clicks_distributed AS default.clicks_replicated
ENGINE = Distributed(clicks_cluster, default, clicks_sharded, cityHash64(my_column));

**Comment by hatrena** [comment]
ReplicatedSummingMergeTree requires 2 to 3 parameters. 

And if I do: 

`Engine = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/default/clicks_replicated', '{replica}')` 


I get this error: 

`Existing table metadata in ZooKeeper differs in mode of merge operation. Stored in ZooKeeper: 0, local: 2`

**Comment by den-crane** [comment]
SummingMT completely another table. ZK Path should be different

ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/default/clicks_replicated_sumXXXMyFirstMV', '{replica}')

**Comment by hatrena** [comment]
Damn, I totally missed that part. my bad. Now it works perfectly fine. Thanks a lot for your quick response. 👍

**Comment by hatrena** [comment]
I tested the MV in our staging where we have 1 shard and 2 replicas. everything is fine. 

Then I have tested it in our production where we have 2 shards and 2 replicas in each. we also have 4 Kubernetes pods. 

I have checked in all 4 pods and the MV does exist in all of them, but the result of the same query is different on each pod. data is increasing, but only in a very specific pod. 

```
CREATE MATERIALIZED VIEW IF NOT EXISTS default.vm_click_line_chart
ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/default/vm_click_line_chart', '{replica}')
ORDER BY date POPULATE AS
SELECT
    count() AS clicks,
    toDate(request_time) AS date,
    organization_id
FROM default.clicks_sharded
WHERE (today() - toDate(request_time)) <= 180
GROUP BY
    date,
    organization_id;
```

Any clue of such behavior?

**Comment by den-crane** [comment]
> but the result of the same query is different on each pod

What query?

**Comment by hatrena** [comment]
a simple query for checking stats like
`SELECT SUM(clicks), date FROM default.vm_click_line_chart WHERE date > '2020-02-01' AND organization_id = 'XXX' group by date`

The result of that query differs in every pod.

**Comment by mirajgodha** [comment]
@hatrena  Were you able to get the same results on all the pods, if yes how?

**Comment by hatrena** [comment]
@mirajgodha , as @den-crane said
> The most used schema is to create at all nodes the same set of tables / MVs. MV's also replicated Engine.

**Comment by mazensibai** [comment]
> I tested the MV in our staging where we have 1 shard and 2 replicas. everything is fine.
> 
> Then I have tested it in our production where we have 2 shards and 2 replicas in each. we also have 4 Kubernetes pods.
> 
> I have checked in all 4 pods and the MV does exist in all of them, but the result of the same query is different on each pod. data is increasing, but only in a very specific pod.
> 
> ```
> CREATE MATERIALIZED VIEW IF NOT EXISTS default.vm_click_line_chart
> ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/default/vm_click_line_chart', '{replica}')
> ORDER BY date POPULATE AS
> SELECT
>     count() AS clicks,
>     toDate(request_time) AS date,
>     organization_id
> FROM default.clicks_sharded
> WHERE (today() - toDate(request_time)) <= 180
> GROUP BY
>     date,
>     organization_id;
> ```
> 
> Any clue of such behavior?

the mistake that you did is that you have created the MV as sharded .. that is why you are getting different result ...
