### ISSUE TITLE
system.columns returns zero size for columns of Log-family table engine

### ISSUE THREAD

**Issue by vladimir-golovchenko** [ClickHouse/ClickHouse#9001]
It needs to define the size of columns Log-family table.

*data_uncompressed_bytes*-field is a zero in *system.column*-table. Is it intended behaviour?

Found the once way to define size is to request the file system:
1. find out the location of table files
```sql
SELECT *
FROM system.tables
WHERE name = '{table name}'
FORMAT Vertical

/* Result:
Row 1:
──────
..
data_paths:                 ['/var/lib/clickhouse/data/test/log_engine_001/']
..
*/
```
2. list all files in this directory
```bash
sudo ls -lsh /var/lib/clickhouse/data/test/log_engine_001

# Result:
# total 88K
# 4.0K -rw-r----- 1 clickhouse clickhouse  64 Feb  3 20:28 __marks.mrk
#  40K -rw-r----- 1 clickhouse clickhouse 40K Feb  3 20:28 id.bin
#  40K -rw-r----- 1 clickhouse clickhouse 40K Feb  3 20:28 name.bin
# 4.0K -rw-r----- 1 clickhouse clickhouse 100 Feb  3 20:28 sizes.json
```

This way requires to have access to the server file system that can be restricted.

[ClickHouse server version 19.17.5 revision 54428]

**Comment by filimonov** [comment]
Not sure if it's always easy (i.e. StripeLog)

**Comment by blinkov** [comment]
@vladimir-golovchenko, do you have any further questions?

**Comment by alexey-milovidov** [comment]
It can be implemented for Log and TinyLog in trivial way.
And also for StripeLog - because it has an index to seek for specific column.

**Comment by alexey-milovidov** [comment]
We cannot easily calculate uncompressed size (in contrast for compressed size) - let's simply return 0.
