### ISSUE TITLE
sipHash64 func possibly returns wrong result

### ISSUE THREAD

**Issue by art-ivaschenko** [ClickHouse/ClickHouse#9007]
**Describe the bug or unexpected behaviour**

ClickHouse sipHash64 function returns different result from the ones that are returned in Python or Go libraries. 

For example if I do:  `SELECT sipHash64('hello') AS SipHash, toTypeName(SipHash) AS type`
it returns this number: `10,142,490,492,830,961,664`.

If I do sipHash64 in any Python or Go library I get this number: `10,142,490,492,830,962,361`.
Usually last 2-4 digits are different.
Python library uses C extension which is based on the same code as here https://github.com/veorq/SipHash

**How to reproduce**
* Clickhouse version: 19.14.6 revision 54425
* Run query: `SELECT sipHash64('hello') AS SipHash, toTypeName(SipHash) AS type`
* Use any other sipHash64 generator for `hello` string
* Compare results

**Expected behavior**
sipHash64 results should match

**Comment by den-crane** [comment]
???

```
20.2.1.2278

SELECT
    sipHash64('hello') AS SipHash,
    toTypeName(SipHash) AS type

┌──────────────SipHash─┬─type───┐
│ 10142490492830962361 │ UInt64 │
└──────────────────────┴────────┘

19.13.6.51

SELECT
    sipHash64('hello') AS SipHash,
    toTypeName(SipHash) AS type

┌──────────────SipHash─┬─type───┐
│ 10142490492830962361 │ UInt64 │
└──────────────────────┴────────┘

18.14.18

SELECT
    sipHash64('hello') AS SipHash,
    toTypeName(SipHash) AS type

┌──────────────SipHash─┬─type───┐
│ 10142490492830962361 │ UInt64 │
└──────────────────────┴────────┘

```

**Comment by art-i-svsg** [comment]
@den-crane thank you for clarification. now it works.

**Comment by art-ivaschenko** [comment]
@den-crane thank you for clarification. now it works as expected.
