### ISSUE TITLE
Get inserted row count

### ISSUE THREAD

**Issue by buxom-man** [ClickHouse/ClickHouse#9017]
Hi! I would like to know if it's possible to retrieve the amount of rows inserted with an `INSERT` query.

Say I have something like this: `INSERT INTO table_1 SELECT a, b, c FROM table_2`. And I would love to know how many of entries I have inserted without making a second `SELECT COUNT()` query. Is it possible?

**Comment by den-crane** [comment]
It's not possible. There is no such feature.

**Comment by buxom-man** [comment]
thanks

**Comment by filimonov** [comment]
`system.query_log` should have that info AFAIR
