### ISSUE TITLE
Broken indicies and inconsistent queries results

### ISSUE THREAD

**Issue by the-tinderbox** [ClickHouse/ClickHouse#9019]
Hi! 

After updating Clickhouse from 19.13.1.11 version to 20.1.3.7 and when we run queries like this:

```
select courseId, uniqExact(learnerId) from entities_attempts_distributed group by courseId order by courseId
```
and 
```
select uniqExact(learnerId) from entities_attempts_distributed where courseId = 41
``` 
we have different results. For example first query returns 21500 unique values for courseId = 41 and second query returns 3500 unique values for courseId = 41.

If we change second query to 
```
select uniqExact(learnerId) from entities_attempts_distributed where identity(courseId) = 41
``` 
we have same result with first query. So, it's possible that in some moment table indicies was corrupted.

We have ReplicatedMergeTree table with structure:

```
CREATE TABLE cursometr.entities_attempts_replicated (`learnerId` UInt64, `courseId` UInt64, `actorId` UInt64, `entityIri` String, `startedAt` DateTime, `attemptNumber` UInt16, `attemptLearningNumber` UInt16, `attemptRepeatingNumber` UInt16, `attemptBeforePassedNumber` UInt16, `attemptAfterPassedNumber` UInt16, `endedAt` DateTime, `passed` UInt8, `success` UInt8, `learning` UInt8, `repeating` UInt8, `beforePassed` UInt8, `afterPassed` UInt8, `result` Float32, `durationTotal` UInt32, `durationLearning` UInt32, `durationRepeating` UInt32, `durationBeforePassed` UInt32, `durationAfterPassed` UInt32, `reject` UInt8, `version` DateTime, `hash` UInt64, `queryId` UInt64) ENGINE = ReplicatedMergeTree('/clickhouse/tables/cursometr/{shard}/entities_attempts', '{replica}') PARTITION BY toStartOfDay(version) ORDER BY (courseId, learnerId, hash, entityIri) SETTINGS index_granularity = 8192
```

Inserts in this table performs via temporary table with same structure. When data successfully inserted in temporary table we move partitions to main table `entities_attempts_replicated` with query 
```
alter table entities_attempts_replicated attach partition $partition from $temp_table_name
```
When partitions successfully moved to main table we drop temporary table.

Sometimes we run queries to delete old data by column `hash`. To perform consistent mutation we collect list of actual hashes and insert them into memory table. Query looks like 
```
alter table entities_attempts_replicated delete where hash not in (select hash from $temporary_hashes_table)
```

So, we don't know at which moment data corrupts, but we can try to make step-by-step reproducing manual if needed.

**Comment by den-crane** [comment]
related: https://github.com/ClickHouse/ClickHouse/issues/8982

**Comment by filimonov** [comment]
>  but we can try to make step-by-step reproducing manual if needed

It will really be cool if you will be able to create a [complete & reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by aopetrov86** [comment]
Same issue after upgrade from 19.14 to 21.1. 
And problem in one part:
```sql
SELECT topic_id,
       _part,
       uniqExact(step_id) as total_steps
 FROM content
 WHERE dt  BETWEEN '2020-01-28 23:05:57' AND '2020-01-31 15:45:00' AND identity(topic_id) = 113
   AND topic_id > 0
   AND step_id > 0
GROUP BY topic_id, _part
```
| topic\_id | \_part | total\_steps |
| :--- | :--- | :--- |
| 113 | 202001\_515944\_522463\_109\_544810 | 216 |
| 113 | 202001\_511489\_515943\_128\_544810 | 10 |

**Comment by aopetrov86** [comment]
After `OPTIMIZE TABLE content PARTITION 202001;`

| topic\_id | \_part | total\_steps |
| :--- | :--- | :--- |
| 113 | 202001\_404744\_523930\_152\_544810 | 10 |

**Comment by den-crane** [comment]
@aopetrov86 I understood nothing and your outputs proofed nothing. I recommend you to open own issue with table DDL and some examples
