### ISSUE TITLE
Has rows after delete or drop partition 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9027]
create table : CREATE TABLE dmp.dm_user_behavior_events (`dt` UInt32, `event_type` UInt16, `user_id` Int64, `event_month` UInt32, `event_week_begin` UInt32, `event_dt` UInt32, `event_hh` UInt8, `event_mi` UInt16, `event_id` UInt32, `event_item` Int32, `event_item_value` String, `client_platform` Int16, `client_version` String, `app_platform` Int16, `app_version` String, `mode` Int8, `ip` String, `ip_province` Int32, `ip_city` Int32, `ip_area` Int16, `ip_citylevel` Int8, `phone_manufacturer` Int32, `phone_price_sub` Int16, `phone_model_code` Int32, `apn` Int8, `opt` Int8, `phone_size` String) ENGINE = ReplicatedMergeTree('/clickhouse/tables/dmp/dm_user_behavior_events/{shard}', '{replica}') PARTITION BY (dt, event_type) ORDER BY (event_id, event_dt, event_item, mode, intHash64(user_id)) SAMPLE BY intHash64(user_id) SETTINGS index_granularity = 8192 ;

 CREATE TABLE dmp.dm_user_behavior_events_all (`dt` UInt32, `event_type` UInt16, `user_id` Int64, `event_month` UInt32, `event_week_begin` UInt32, `event_dt` UInt32, `event_hh` UInt8, `event_mi` UInt16, `event_id` UInt32, `event_item` Int32, `event_item_value` String, `client_platform` Int16, `client_version` String, `app_platform` Int16, `app_version` String, `mode` Int8, `ip` String, `ip_province` Int32, `ip_city` Int32, `ip_area` Int16, `ip_citylevel` Int8, `phone_manufacturer` Int32, `phone_price_sub` Int16, `phone_model_code` Int32, `apn` Int8, `opt` Int8, `phone_size` String) ENGINE = Distributed(perftest_3shards_2replicas, dmp, dm_user_behavior_events, intHash64(user_id))

drop  sql :ALTER TABLE dmp.dm_user_behavior_events  DROP PARTITION (20200205,9);
delete sql : ALTER TABLE dmp.dm_user_behavior_events  delete where dt=20200205 and event_type=9 ;

query sql : select event_type,count() from dmp.dm_user_behavior_events where dt=20200205 and event_type=9 group by event_type;

result : 

alihb2a_click_001019 :) select event_type,count() from dmp.dm_user_behavior_events where dt=20200205 and event_type=9 group by event_type;

SELECT 
    event_type, 
    count()
FROM dmp.dm_user_behavior_events
WHERE (dt = 20200205) AND (event_type = 9)
GROUP BY event_type

┌─event_type─┬─count()─┐
│          9 │   21967 │
└────────────┴─────────┘

1 rows in set. Elapsed: 0.025 sec. Processed 21.97 thousand rows, 131.80 KB (891.48 thousand rows/s., 5.35 MB/s.)

**Comment by den-crane** [comment]
Check CH log. What was the messages after CH received  DROP PARTITION

**Comment by onine007** [comment]
2020.02.06 12:43:30.496520 [ 13 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://alihb2a_click_001020:9019/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdmp%2Fdm_user_behavior_events%2Fshard-02%2Freplicas%2Freplica-02&part=20200205-3_580024_580024_0&client_protocol_version=1&compress=false
2020.02.06 12:43:30.497249 [ 83 ] {edf24620-d4e2-42ca-b2b3-993de07395c2} <Trace> dmp.dm_user_behavior_events: Renaming temporary part tmp_insert_20200205-9_165514_165514_0 to 20200205-9_1928173_1928173_0.
2020.02.06 12:43:30.497398 [ 77 ] {9d8ecb25-343d-4ca7-86cb-fc9e3a177abc} <Trace> dmp.dm_user_behavior_events: Renaming temporary part tmp_insert_20200205-3_165513_165513_0 to 20200205-3_580028_580028_0.
2020.02.06 12:43:30.498198 [ 13 ] {} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 367.57 GiB.
2020.02.06 12:43:30.499610 [ 27 ] {} <Debug> dmp.dm_user_behavior_events (ReplicatedMergeTreeQueue): Pulled 2 entries to queue.
2020.02.06 12:43:30.499629 [ 20 ] {} <Debug> dmp.dm_user_behavior_events: Fetched part 20200205-9_1928163_1928163_0 from /clickhouse/tables/dmp/dm_user_behavior_events/shard-02/replicas/replica-02
2020.02.06 12:43:30.499965 [ 83 ] {edf24620-d4e2-42ca-b2b3-993de07395c2} <Debug> MemoryTracker: Peak memory usage (for query): 52.29 MiB.
2020.02.06 12:43:30.500071 [ 77 ] {9d8ecb25-343d-4ca7-86cb-fc9e3a177abc} <Debug> MemoryTracker: Peak memory usage (for query): 56.33 MiB.
2020.02.06 12:43:30.500132 [ 83 ] {edf24620-d4e2-42ca-b2b3-993de07395c2} <Information> TCPHandler: Processed in 0.022 sec.
2020.02.06 12:43:30.500212 [ 77 ] {9d8ecb25-343d-4ca7-86cb-fc9e3a177abc} <Debug> MemoryTracker: Peak memory usage (total): 108.61 MiB.
2020.02.06 12:43:30.500244 [ 77 ] {9d8ecb25-343d-4ca7-86cb-fc9e3a177abc} <Information> TCPHandler: Processed in 0.023 sec.
2020.02.06 12:43:30.501029 [ 77 ] {f0fcd2f3-cf22-4818-b08f-10057de5979d} <Debug> executeQuery: (from 10.0.1.20:41819) INSERT INTO dmp.dm_user_behavior_events (dt, event_type, user_id, event_month, event_week_begin, event_dt, event_hh, event_mi, event_id, event_item, event_item_value, client_platform, client_version, app_platform, app_version, mode, ip, ip_province, ip_city, ip_area, ip_citylevel, phone_manufacturer, phone_price_sub, phone_model_code, apn, opt, phone_size) VALUES
2020.02.06 12:43:30.501344 [ 16 ] {} <Debug> dmp.dm_user_behavior_events: Fetched part 20200205-3_580023_580023_0 from /clickhouse/tables/dmp/dm_user_behavior_events/shard-02/replicas/replica-02
2020.02.06 12:43:30.501371 [ 15 ] {} <Trace> dmp.dm_user_behavior_events: Executing log entry to merge parts 20200205-3_528718_580008_11797, 20200205-3_580009_580017_1 to 20200205-3_528718_580017_11798
2020.02.06 12:43:30.501380 [ 13 ] {} <Trace> dmp.dm_user_behavior_events: Renaming temporary part tmp_fetch_20200205-3_580024_580024_0 to 20200205-3_580024_580024_0.
2020.02.06 12:43:30.502357 [ 15 ] {} <Debug> DiskSpaceMonitor: Reserving 1.75 MiB on disk `default`, having unreserved 367.57 GiB.
2020.02.06 12:43:30.502415 [ 15 ] {} <Debug> dmp.dm_user_behavior_events (MergerMutator): Merging 2 parts: from 20200205-3_528718_580008_11797 to 20200205-3_580009_580017_1 into tmp_merge_20200205-3_528718_580017_11798
2020.02.06 12:43:30.502795 [ 15 ] {} <Debug> dmp.dm_user_behavior_events (MergerMutator): Selected MergeAlgorithm: Vertical
2020.02.06 12:43:30.503130 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.503388 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.503734 [ 77 ] {f0fcd2f3-cf22-4818-b08f-10057de5979d} <Debug> DiskSpaceMonitor: Reserving 1.00 MiB on disk `default`, having unreserved 367.56 GiB.
2020.02.06 12:43:30.506362 [ 77 ] {f0fcd2f3-cf22-4818-b08f-10057de5979d} <Debug> dmp.dm_user_behavior_events (Replicated OutputStream): Wrote block with ID '20200205-3_969699528913458035_7608111891700009423', 1 rows
2020.02.06 12:43:30.508280 [ 14 ] {} <Debug> dmp.dm_user_behavior_events: Fetching part 20200205-9_1928164_1928164_0 from /clickhouse/tables/dmp/dm_user_behavior_events/shard-02/replicas/replica-02
2020.02.06 12:43:30.510077 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.510156 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.510832 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.510906 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.511350 [ 5 ] {} <Trace> dm_user_behavior_events_all.Distributed.DirectoryMonitor: Finished processing `/data/clickhouse/data/data/dmp/dm_user_behavior_events_all/default@ck003:9000,default@ck002:9099/1178018.bin`
2020.02.06 12:43:30.511374 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.511380 [ 5 ] {} <Trace> dm_user_behavior_events_all.Distributed.DirectoryMonitor: Started processing `/data/clickhouse/data/data/dmp/dm_user_behavior_events_all/default@ck003:9000,default@ck002:9099/1178019.bin`
2020.02.06 12:43:30.511464 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.512086 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.512154 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.512735 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.512813 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.513847 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.513926 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.515767 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 15 marks from part 20200205-3_528718_580008_11797, total 120698 rows starting from the beginning of the part
2020.02.06 12:43:30.515858 [ 15 ] {} <Trace> MergeTreeSequentialBlockInputStream: Reading 1 marks from part 20200205-3_580009_580017_1, total 9 rows starting from the beginning of the part
2020.02.06 12:43:30.518317 [ 73 ] {} <Trace> InterserverIOHTTPHandler-factory: HTTP Request for InterserverIOHTTPHandler-factory. Method: POST, Address: 10.0.1.20:40226, User-Agent: none, Content Type: , Transfer Encoding: identity
2020.02.06 12:43:30.518417 [ 73 ] {} <Trace> InterserverIOHTTPHandler: Request URI: ?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdmp%2Fdm_user_behavior_events%2Fshard-02%2Freplicas%2Freplica-01&part=20200205-9_1928165_1928165_0&client_protocol_version=1&compress=false
2020.02.06 12:43:30.518447 [ 73 ] {} <Trace> dmp.dm_user_behavior_events (Replicated PartsService): Sending part 20200205-9_1928165_1928165_0
2020.02.06 12:43:30.520836 [ 73 ] {} <Information> InterserverIOHTTPHandler: Done processing query
2020.02.06 12:43:30.521984 [ 9 ] {} <Debug> dmp.dm_user_behavior_events: Fetching part 20200205-3_580025_580025_0 from /clickhouse/tables/dmp/dm_user_behavior_events/shard-02/replicas/replica-02

**Comment by den-crane** [comment]
I don't see `ALTER TABLE dmp.dm_user_behavior_events DROP PARTITION (20200205,9);`
Are you sure you executed DROP/DELETE аgainst this shard?

**Comment by onine007** [comment]
@den-crane yes, i executed ALTER TABLE dmp.dm_user_behavior_events on cluster *** DROP PARTITION (20200205,9);

and executed  ALTER TABLE dmp.dm_user_behavior_events DROP PARTITION (20200205,9) on every nodes

**Comment by den-crane** [comment]
> result is increase
>this result is fast changing .

So you are still inserting data. It could be delayed inserts from Distributed tables.

>I can see a lot of dictionary like 20200205-9*** in table data dictionary

What stands for dictionary? table data dictionary? What do you mean?

**Comment by onine007** [comment]
@den-crane 

> > result is increase
> > this result is fast changing .
> 
> So you are still inserting data. It could be delayed inserts from Distributed tables.
> 
No , I don't  insert any data .  how long time can be delayed ? it takes 2 days ? 

> > I can see a lot of dictionary like 20200205-9*** in table data dictionary
> 
> What stands for dictionary? table data dictionary? What do you mean?

Sorry ,  they  are   folders  not  dictionaries .

**Comment by den-crane** [comment]
>No , I don't insert any data . how long time can be delayed ? it takes 2 days ?

Maybe.

>Sorry , they are folders not dictionaries .

Can you output `ls -l`. I don't quite understand what folders.

**Comment by onine007** [comment]
@den-crane it may be delayed inserts from Distributed tables. 
I droped Distributed tables   and  recreated it ,  then solved !
