### ISSUE TITLE
Add used databases and tables to query_log

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#9030]
We should add this info to `query_log` in form of two parallel arrays:
```
tables.database Array(String),
tables.table Array(String)
```

_Originally posted by @alexey-milovidov in https://github.com/ClickHouse/ClickHouse/pull/6431#issuecomment-520234896_

**Comment by alexey-milovidov** [comment]
@amosbird is going to implement this feature.

It will be in just `tables` array with values in form of "db.table" strings.
It will be added along with the `columns` field with strings in form of "db.table.column".

(it's better than Nested data structure to avoid duplication of databases and tables values)

**Comment by amosbird** [comment]
https://github.com/ClickHouse/ClickHouse/pull/17726
