### ISSUE TITLE
result set is encoded through the MySQL client 

### ISSUE THREAD

**Issue by sakthi7** [ClickHouse/ClickHouse#9032]
Hi All,

I am trying to connect the Clickhouse with the MySQL client . But, the result set is coming something encoded .

Anything I missed ?

mysql -h127.0.0.1 -P9001 -udefault -pSakthi@321

mysql> show databases;
+------------------+
| name             |
+------------------+
| 0x64656661756C74 |
| 0x6A65737573     |
| 0x73797374656D   |
+------------------+
3 rows in set (0.00 sec)
Read 3 rows, 354.00 B in 0.000 sec., 6478 rows/sec., 746.55 KiB/sec.

**Comment by den-crane** [comment]
CH version?

cc @yurriy

**Comment by sakthi7** [comment]
Hi @den-crane ,


Thanks for the revert .

[root@ip-172-31-8-156 ~]# clickhouse-server --version
ClickHouse server version 19.17.4.11.
[root@ip-172-31-8-156 ~]# clickhouse-client --version
ClickHouse client version 19.17.4.11.

**Comment by sakthi7** [comment]
Hi @den-crane ,


Thanks for the hint . I have tried with the MySQL 5.7 client . It is working fine for me .

**Logs :**

[root@ip-172-31-8-156 bin]# ./mysql --version
./mysql  Ver 14.14 Distrib 5.7.28, for linux-glibc2.12 (x86_64) using  EditLine wrapper
[root@ip-172-31-8-156 bin]# 
[root@ip-172-31-8-156 bin]# 
[root@ip-172-31-8-156 bin]# ./mysql -h127.0.0.1 -P9001 -udefault -pJesus@7sakthI
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 16
Server version: 19.17.4.11-ClickHouse 

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+---------+
| name    |
+---------+
| default |
| jesus   |
| system  |
+---------+
3 rows in set (0.00 sec)
Read 3 rows, 354.00 B in 0.000 sec., 6166 rows/sec., 710.56 KiB/sec.



Now, why it is not working with MySQL 8 ? It is because of the character set ? Because the default charset is UTF8MB4 on MySQL 8 .

 
Thanks !!!

**Comment by yurriy** [comment]
> Now, why it is not working with MySQL 8 ? It is because of the character set ? Because the default charset is UTF8MB4 on MySQL 8 .

I will look into that.

**Comment by sakthi7** [comment]
Thank you !!!

**Comment by blinkov** [comment]
@sakthi7, do you have any further questions?

**Comment by alexey-milovidov** [comment]
@yurriy is not working on this issue right now, we have to reassign.

**Comment by yurriy** [comment]
> @yurriy is not working on this issue right now, we have to reassign.

It was fixed in #9079. Probably @den-crane reopened it because it wasn't released at that moment.

**Comment by alexey-milovidov** [comment]
Ok, thank you!
