### ISSUE TITLE
drop partition for all shard in one DDL execution

### ISSUE THREAD

**Issue by karlchan-cn** [ClickHouse/ClickHouse#9045]
version:19.11.3
background:
three servers:A,B,C ares running clickhouse cluster.
2 shard 1 replicas config looks like below:
``` 
<cluster_test>
        <shard>
            <replica>
                <host>B</host>
                <port>9000</port>
            </replica>
        </shard>
        <shard>
            <replica>
                <host>C</host>
                <port>9000</port>
            </replica>
        </shard>
</cluster_test>  
```

In server A,there is a test.hist_all table created by below script:
**CREATE TABLE hits_all AS tutorial.hits_local
ENGINE = Distributed(cluster_test, test, hits_local, rand());**

In server B&C,there are concrete table test.hist to store data created by below script:
**CREATE TABLE test.hits_local (...) ENGINE = MergeTree PARTITION BY dayno ....**

Question:
Can I drop patition data with SQL below **in just one execution**.
#ALTER TABLE hist on cluster cluster_test DROP PARTITION 20200114;#

**Comment by den-crane** [comment]
Not sure about 19.11. In latest (supported) 19.16+ versions you can.


>in just one execution.

Anyway, even `on cluster` is not atomic.

**Comment by filimonov** [comment]
@den-crane drop partition on Distributed?

Distributed doesn't have any partitions, why should you drop partitions from it? 

@karlchan-cn, what's about:
```
ALTER TABLE hits_local on cluster cluster_test DROP PARTITION 20200114;
```

**Comment by den-crane** [comment]
My understanding that `test.hits` is MergeTree not Distributed

**Comment by filimonov** [comment]
> My understanding that `test.hits` is MergeTree not Distributed

You probably right: 'test.hist to store data created by below script: CREATE TABLE test.hits_local'. Misleading. :confused:

**Comment by karlchan-cn** [comment]
Sorry for some wrong description.
The problems is I want to delete data in server B&C on table hits_local  in just one SQL execution with script like below
#ALTER TABLE hits_local on cluster cluster_test DROP PARTITION 20200114;#.

@den-crane Thanks for your kindly answering ,i will try the new version and check the result.

> Not sure about 19.11. In latest (supported) 19.16+ versions you can.
> 
> > in just one execution.
> 
> Anyway, even `on cluster` is not atomic.

Right now , my solutions is to execute DDL script on both B&C server,so the script has to be executed twice.@filimonov thanks for your concern, right now i did as you mentioned.
