### ISSUE TITLE
DISTINCT with optimize_skip_unused_shards=1 returns duplicates (19.17.4.11)

### ISSUE THREAD

**Issue by VaBezruchko** [ClickHouse/ClickHouse#9046]
Hello,

   the following query with option optimize_skip_unused_shards=1 leaves duplicates in the result

`   select distinct id, column1  from table1_d  prewhere dated >= '2012-05-01' and dated <= '2019-06-28'  and (id = '36579210000000') where is_surrogate = 0 limit 1000001`

Table description:

```
 CREATE TABLE IF NOT EXISTS data.table1_local on cluster cluster1
( 
 dated Date, 
 id String, 
 column1 String, 
 is_surrogate UInt8 
) ENGINE = ReplicatedReplacingMergeTree(...)
 PARTITION BY (toYYYYMM(dated)) 
 ORDER BY (id, dated, column1)

 
 CREATE TABLE IF NOT EXISTS data.table1_d ON CLUSTER cluster1 as data.table1_local ENGINE = Distributed(cluster1, data, table1_local, cityHash64(id));
```

The query with optimize_skip_unused_shards=0 works as expected.

**Comment by 4ertus2** [comment]
It's not clear what nodes are used for replication and what are distributed. It's also not clear where you insert same keys: in any replica or "one key - one replica" mode.

I can imagine a configuration then you will have stale ids cause of insertion is in all replicas, Distributed is on replicated nodes and there's no guaranty that replication is finished.

**Comment by VaBezruchko** [comment]
Artem, 

does "select distinct " guarantee unique results? Is it matter data replication and sharding for unique result with "select distinct" query?

Data was inserted by followed query:
`INSERT INTO data.table1_d (dated,  id, column1, is_surrogate) values(?,?,?,?)`

The problem is in parameter 'optimize_skip_unused_shards=1'.

**Comment by den-crane** [comment]
reproduced: 20.2.1.2362, 19.17.4

STR:

at two shards:

```
CREATE TABLE table1_local (id String) ENGINE = MergeTree ORDER BY tuple();

CREATE table table1_d as table1_local ENGINE = 
Distributed(test_cluster_two_shards, currentDatabase(), table1_local, cityHash64(id));

INSERT INTO table1_d select toString(number) from numbers(10);
INSERT INTO table1_d select toString(number) from numbers(10);
INSERT INTO table1_d select toString(number) from numbers(10);

set optimize_skip_unused_shards=0
select distinct id from table1_d where (id = '1');
┌─id─┐
│ 1  │
└────┘

select distinct id from table1_d where (id = '2');
┌─id─┐
│ 2  │
└────┘




set optimize_skip_unused_shards=1;
select distinct id from table1_d where (id = '1');
┌─id─┐
│ 1  │
└────┘
┌─id─┐
│ 1  │
└────┘
┌─id─┐
│ 1  │
└────┘


select distinct id from table1_d where (id = '2');
┌─id─┐
│ 2  │
└────┘
┌─id─┐
│ 2  │
└────┘
┌─id─┐
│ 2  │
└────┘

select distinct id from table1_d where (id = '2');
┌─id─┐
│ 2  │
└────┘
┌─id─┐
│ 2  │
└────┘

2 rows in set.  

2 rows ???????????????????????????????? Why????
```


workaround:
```
set optimize_skip_unused_shards=1;
select  id from table1_d where (id = '1') group by id
┌─id─┐
│ 1  │
└────┘
```

**Comment by 4ertus2** [comment]
> Artem,
> 
> does "select distinct " guarantee unique results?

Yup, you're right. I've missed `distinct` in your query.

**Comment by azat** [comment]
FWIW upstream (6550aa5e6cf26deb7935f29c3a75df3cf194937c) does not affected

**Comment by azat** [comment]
Nope, affected (though not with the first try of https://github.com/ClickHouse/ClickHouse/issues/9046#issuecomment-586011358)
