### ISSUE TITLE
Profile settings in config.d silently ignored

### ISSUE THREAD

**Issue by akuzm** [ClickHouse/ClickHouse#9051]
Put the `log_queries.xml` from test configs to `config.d` instead of `users.d`, and enjoy your server working perfectly and not logging the queries despite all the config files looking correct.

Should throw an error.

**Comment by filimonov** [comment]
Not sure if it's a good idea

**Comment by akuzm** [comment]
> Not sure if it's a good idea

Why not, is it going to break something?

**Comment by filimonov** [comment]
1) conf.d content added both to users.xml and config.xml
2) i think warning may be good, but exception can make pain for updates (clickhouse just don't start with same config is bad UX)

**Comment by alexey-milovidov** [comment]
We have received second complaing about this usability issue.
