### ISSUE TITLE
 DB::Exception: Too many parts (300). Merges are processing significantly slower than inserts

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9053]
The cluster has 3 shards and 2 replicas .
All data are loaded by 
query:  clickhouse-client   --query="INSERT INTO my_sdap.dm_user_behavior_events FORMAT Parquet " < file   
on every shards

a shard  occured Too many parts   Exception

**Comment by den-crane** [comment]
Check this https://github.com/ClickHouse/ClickHouse/issues/6720#issuecomment-526045768
