### ISSUE TITLE
Query performance for data type Date

### ISSUE THREAD

**Issue by vicchen7** [ClickHouse/ClickHouse#9059]
ClickHouse server version : 19.17.5.18 (official build)

Is there any difference of query performance about below condition?
I tested but sometimes #1 is better and sometimes #2 is better.
I can't know which one is better for performance.

column : COL_DATE Date (and its partition key)

1. COL_DATE BETWEEN BETWEEN '2019-12-21' AND '2019-12-27'

2. COL_DATE in ('2019-12-21','2019-12-22','2019-12-23','2019-12-24','2019-12-25','2019-12-26','2019-12-27')

And is there any different that using function toDate() and only using string? 
e.g. 
 BETWEEN toDate('2019-12-21') AND toDate('2019-12-27')
 or 
 BETWEEN '2019-12-21' AND '2019-12-27'

For last one if CH will add function toDate() to transform correct data type automatically?

**Comment by filimonov** [comment]
>  I tested but sometimes 1 is better and sometimes 2 is better.
>  I can't know which one is better for performance.

I think they should work ~ the same speed. Maybe you have difference due to cache hit/miss?

**Comment by den-crane** [comment]
>I tested but sometimes #1 is better and sometimes #2 is better.

Should be the same speed. Use what is more natural for your code.

>BETWEEN toDate('2019-12-21') AND toDate('2019-12-27')
>BETWEEN '2019-12-21' AND '2019-12-27'

No difference from performance perspective. 
BUT toDate('2019-12-21') is more reliable especially in` mutations where`
