### ISSUE TITLE
Cannot OPTIMIZE table: Cannot select parts for optimization

### ISSUE THREAD

**Issue by Zhile** [ClickHouse/ClickHouse#9060]
Hi, 
After inserting the data into table, I want to do optimize table immediately. However, when I do optimize there's an exception threw like below: 
`2020.02.10 11:08:02.743761 [ 317 ] {e51df32d-065b-414c-8f27-a57e95c15ec4} <Error> executeQuery: Code: 388, e.displayText() = DB::Exception: Cannot OPTIMIZE table: Cannot select parts for optimization (version 19.14.7.15 (official build)) (from [::ffff:10.23.16.61]:60628) (in query: OPTIMIZE TABLE test.test FINAL), Stack trace:

0. 0x556b471d11e0 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x556b471d0fb5 DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /usr/bin/clickhouse
2. 0x556b46f9801b ? /usr/bin/clickhouse
3. 0x556b4a455f29 DB::InterpreterOptimizeQuery::execute() /usr/bin/clickhouse
4. 0x556b4a59a5f0 ? /usr/bin/clickhouse
5. 0x556b4a59ba9c DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) /usr/bin/clickhouse
6. 0x556b47251e9e DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&) /usr/bin/clickhouse
7. 0x556b47254249 DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&) /usr/bin/clickhouse
8. 0x556b4b028d69 Poco::Net::HTTPServerConnection::run() /usr/bin/clickhouse
9. 0x556b4b023b40 Poco::Net::TCPServerConnection::start() /usr/bin/clickhouse
10. 0x556b4b02425d Poco::Net::TCPServerDispatcher::run() /usr/bin/clickhouse
11. 0x556b4c707571 Poco::PooledThread::run() /usr/bin/clickhouse
12. 0x556b4c70531c Poco::ThreadImpl::runnableEntry(void*) /usr/bin/clickhouse
13. 0x556b4ce7ab60 ? /usr/bin/clickhouse
14. 0x7f602d59add5 start_thread /usr/lib64/libpthread-2.17.so
15. 0x7f602ceb802d __clone /usr/lib64/libc-2.17.so`

The optimize query is: 
`OPTIMIZE TABLE test.test FINAL`

Why this happens? And how can I do the OPTIMIZE? 
Thanks.

**Comment by 4ertus2** [comment]
Most probably it means there's a mutation on some of your parts and this function returned false

```
        auto can_merge = [this, &lock] (const DataPartPtr & left, const DataPartPtr & right, String *)
        {
            return !currently_merging_mutating_parts.count(left) && !currently_merging_mutating_parts.count(right)
                && getCurrentMutationVersion(left, lock) == getCurrentMutationVersion(right, lock);
        };
```

The OPTIMIZE query could be not allowed even if you make it FINAL.

**Comment by Zhile** [comment]
So for this case, I didn't kill the mutation by query but wait for the mutations finish. 
There's a setting `optimize_throw_if_noop` which will give me an error if the OPTIMIZE doesn't do anything. Then I wait and retry until the OPTIMIZE complete. This way helps me to do the OPTIMIZE.
