### ISSUE TITLE
Connection failed at try №1, reason: Code: 32, e.displayText() = DB::Exception: Attempt to read after eof 

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#9071]
I found this error in the log.

What causes it?
![Capture](https://user-images.githubusercontent.com/30060632/74221793-d738b780-4ced-11ea-8bea-582d5bf3d64a.PNG)

**Comment by 4ertus2** [comment]
You've got some error for query that run through ConnectionPoolWithFailover. Probably it's some distributed query that aborted at destination for some reason. Or it could be just an anavaliable node. You may get the times of errors and find other errors on destinations. There could be real errors there.

**Comment by ShadowDAssange** [comment]
How to resolve this ?

**Comment by sszc** [comment]
I also encountered this problem, the version is 20.6.6.7

**Comment by chelsEg** [comment]
I also encountered this problem, the version is 20.6.7.4

**Comment by moon03432** [comment]
I also encountered this problem, the version is 20.4.8.99

**Comment by catalina-ch** [comment]
I also encountered this problem, the version is 20.6.8.5

**Comment by woozhijun** [comment]
I also encountered this problem, the version is 19.13.3.26
