### ISSUE TITLE
Memory leak in function topK(N)(x) with version v19.13.3.26

### ISSUE THREAD

**Issue by awpengfei** [ClickHouse/ClickHouse#9072]
There may be memory leak in function `topK(N)(x)` with version v19.13.3.26.
Executing the following query several times, and the host's used memory increase from 30GB to 40GB.
```SQL
SELECT c1, topK(10)(c2) FROM ttt GROUP BY c1;
```
![image](https://user-images.githubusercontent.com/53896468/74226698-fb00fb00-4cf7-11ea-89c9-7926ca2191c3.png)

**Comment by den-crane** [comment]
jemalloc (jemalloc.net) caches memory to save allocations/deallocations.

```
create table ttt(c1 Int64, c2 Int64) Engine=MergeTree order by c1;
insert into ttt select number,number%103 from numbers(1000000)
```
1 hour / 2 benchmarks in parallel
```
echo 'SELECT c2, topK(10)(c1) FROM ttt GROUP BY c2'|clickhouse-benchmark
queries 164828, QPS: 39.183
echo 'SELECT c1, topK(10)(c2) FROM ttt GROUP BY c1'|clickhouse-benchmark
queries 4162, QPS: 0.966
```

![Screen Shot 2020-02-11 at 2 04 44 PM](https://user-images.githubusercontent.com/19737682/74264847-c9783780-4cd7-11ea-8049-9ce8ff15690a.png)

**Comment by den-crane** [comment]
two hours idleness after benchmarks
![Screen Shot 2020-02-11 at 4 10 32 PM](https://user-images.githubusercontent.com/19737682/74274769-0c8ed680-4ce9-11ea-86a8-d81f1adc5959.png)

**Comment by den-crane** [comment]
Do not see any issue, closing.
