### ISSUE TITLE
Codecs: allow to reference default compression

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#9074]
In some cases default compression should be used in the CODEC definition.

Like 'preprocess data with Delta(T64) encoding' and pack it with default compression algorithm (which may depend on part size.

I propose to create a name for a default compression, and allow it to use in compression codecs definition, like 
```
value UInt64 CODEC(Delta, DefaultCompression), -- delta + default compression
value UInt64 CODEC(Delta),  -- delta uncompressed
value UInt64 CODEC(DefaultCompression), -- the same as lack of codec specification
```

**Comment by den-crane** [comment]
value UInt64 CODEC(DefaultCompression) -- solves https://github.com/ClickHouse/ClickHouse/issues/6227

**Comment by alexey-milovidov** [comment]
This task is almost trivial to implement.

**Comment by mjodeh** [comment]
`alter table db.tbl modify column testFloat Nullable(Float32) DEFAULT NULL CODEC(DefaultCompression)` throws an exception:
`Exception: Unknown codec family: DefaultCompression`
The same exception if a non-nullable type is used

- So how to remove a codec and use a nullable type `Nullable(Float32)`?
- What does `Codec(NONE)` mean?
