### ISSUE TITLE
New repository layout proposal

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#9080]
Since we're going to integrate (and sync) with Yandex internal repository, I suggest to make some changes to the current folders layout, and introduce basic dependency principles for the future.

Path | Previous location | Description
----- | ------ | -------
/benchmark | unchanged | public data for benchmarking and comparing different products
/cmake | all cmake files | all helpful modules to build with CMake
/debian | unchanged | everything required to build public .deb packages
/docker | unchanged | everything required to build public binary docker images
/docs | unchanged | documentation
/src/base | moved from **/libs** | common part for **/src/lib** and **/src/bin**, may depend on **/src/contrib**
/src/bin | moved from **/dbms/programs** | main binaries of Clickhouse, may depend on **/src/base**, **/src/contrib** and **/src/lib**
/src/contrib | moved from **/contrib** | external sources, may depend on other parts from **/contrib**
/src/lib | moved from **/dbms/src** | separatable part for internal usage inside Yandex, may depend on **/src/base** and **/src/contrib**
/tests | moved from /dbms/tests | data used for automated testing in CI
/utils | unchanged | helpful scripts for debugging etc
/website | unchanged | website contents

All required changes in source code and CMake files should be implemented in appliance with this proposal.

**Comment by qoega** [comment]
OK for me.

**Comment by alesapin** [comment]
We need motivation for each rename. Now I don't see any motivation at all. Not OK for me.

**Comment by proller** [comment]
Integration with Yandex internal repository was performed many times as is without all these moves.

/src/bin -  'bin' usually means already compiled files.

/src/contrib -  looks like sabotage
