### ISSUE TITLE
Duplicated data in MATERIALIZED VIEW

### ISSUE THREAD

**Issue by hatrena** [ClickHouse/ClickHouse#9081]
Considering the following schema, I am experiencing duplicated rows in the result views.

```
CREATE MATERIALIZED VIEW IF NOT EXISTS default.click_bar_chart_replica
ENGINE = ReplicatedMergeTree(
     '/clickhouse/tables/{shard}/default/click_bar_chart_replica',
     '{replica}',
     date,
     cityHash64(organization_id),
     (date, cityHash64(organization_id)),
     8192
)
POPULATE AS
SELECT
    organization_id,
    toDate(request_time) AS date,
    SUM(rejected) AS clr,
    (count() - clr) AS cla,
    sumIf(revenue, rejected = 1) AS rr,
    sumIf(revenue, rejected = 0) AS ra,
    sumIf(payout, rejected = 1) AS pr,
    sumIf(payout, rejected = 0) AS pa
FROM default.clicks_sharded
WHERE (today() - date) <= 180
GROUP BY
    date,
    organization_id
ORDER BY date;

CREATE TABLE default.click_bar_chart AS default.click_bar_chart_replica
ENGINE = Distributed(clicks_cluster, default, click_bar_chart_replica);
```

Now if query the view `click_bar_chart` like:
```
select * from click_bar_chart where organization_id = 'XXX' and date = '2020-02-06'
```

I will get the following result:
```
organization_id | date | clr | cla | rr | ra | pr | pa
XXX | 2020-02-06 | 11364 | 114419 | 113.64000000002123 | 1144.1899999991044 | 0 | 0
XXX | 2020-02-06 | 11233 | 112861 | 112.33000000002056 | 1128.6099999991186 | 0 | 0
XXX | 2020-02-06 | 11233 | 112861 | 112.33000000002056 | 1128.6099999991186 | 0 | 0
```

The second and third rows are identical, and according to the real data, the correct result is sum of the first 2 rows.

Any things should I change here?

**Comment by den-crane** [comment]
`POPULATE AS`

you have 2 replicas

clicks_sharded R1 (1 row XXXX)
clicks_sharded R2 (1 row XXXX) -- the same one row

Now create MV POPULATE the first replica will select 1 row XXXX and will insert it locally to it's storage. The second replica also will select 1 row XXXX and will insert it locally to it's storage. 
But MV replicated so they both will replicate XXXX to each other, you will get XXXX doubled.

So be careful and run POPULATE only once at each shard.

**Comment by hatrena** [comment]
In the meantime, I also made this change and it solved the problem. how does it explain?

```
POPULATE AS
SELECT
    SUM(rejected) AS clr,
    (count() - clr) AS cla,
    sumIf(revenue, rejected = 1) AS rr,
    sumIf(revenue, rejected = 0) AS ra,
    sumIf(payout, rejected = 1) AS pr,
    sumIf(payout, rejected = 0) AS pa,
    organization_id,
    toDate(request_time) AS date,
FROM default.clicks_sharded
WHERE (today() - toDate(request_time)) <= 180
GROUP BY
    date,
    organization_id
ORDER BY date;
```

>So be careful and run POPULATE only once at each shard.

I also take note, thanks

**Comment by den-crane** [comment]
>how does it explain?

Your luckiness https://clickhouse.tech/docs/en/operations/table_engines/replication/
Read _"Data blocks are deduplicated."_ part.

---

BTW, never use legacy syntax. It can be canceled in the future.

WRONG:
```
ENGINE = ReplicatedMergeTree(
     '/clickhouse/tables/{shard}/default/click_bar_chart_replica',
     '{replica}',
     date,
     cityHash64(organization_id),
     (date, cityHash64(organization_id)),
     8192
)
```

RIGHT
```
ENGINE = ReplicatedMergeTree(
     '/clickhouse/tables/{shard}/default/click_bar_chart_replica',
     '{replica}')
PARTITION BY toYYYYMM(date)
ORDER BY (date, cityHash64(organization_id))
SAMPLE BY  cityHash64(organization_id)
```

Also `ORDER BY` looks weird. I would expect (organization_id, date, cityHash64(organization_id))
Also I would use ReplicatedSummingMergeTree not ReplicatedMergeTree.

**Comment by hatrena** [comment]
It works perfectly fine now. Thanks for the help
