### ISSUE TITLE
multiple update queries at the same time

### ISSUE THREAD

**Issue by chu1070y** [ClickHouse/ClickHouse#9083]
If I send more than one update query at the same time and the queries update same data, How does the ClickHouse handle data??

Does the ClickHouse handle query sequentially? If so, afterward update query is waiting for forward update query? 

If the queries update data at the same time, How does the ClickHouse keep data integrity?

**Comment by den-crane** [comment]
Sequentially. Though several mutations can be combined into one. But still data will be updated as updates applied sequentially.

>How does the ClickHouse keep data integrity

Data will be consistent after all updates ended (eventually). But during mutations your selects will see partially updated data because mutations are not atomic.

**Comment by chu1070y** [comment]
Thank you.
