### ISSUE TITLE
Take 478M disk size for 1459 records.

### ISSUE THREAD

**Issue by RangerWolf** [ClickHouse/ClickHouse#9084]
Hi Team,

I use Clickhouse to store some ads related data.  for Ads Account table, there are only 1459 records, but I found it took 478M disk size.  
I think I may a little misuse clickhouse, because our business need to update this table at least 1 hour a time. 
So may I know if this is normal.
```sql
-- get records count
SELECT count(*)
FROM ads_account

┌─count()─┐
│    1459 │
└─────────┘

-- get version
SELECT version()

┌─version()──┐
│ 19.13.7.57 │
└────────────┘
```
```bash
# get disk size
du -lsh .
478M
```

Thanks

**Comment by den-crane** [comment]
It could be a system tables with logs. Or crashdumps.

Check what tables sizes really are with: 
```
  select round(sum(bytes)/1024/1024/1024) size, count() parts_count, sum(rows),database,table
  from system.parts 
  where   active 
  group by database,table
  order by size desc
```

**Comment by RangerWolf** [comment]
Hi, 
Thanks for you help, I run the sql the the table actual size is 3M.  

I checked files in the directory, most are something like :
```
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f5f61b319bd8ff5933ad028f3a7c2ca3_681_109969_23_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f63dfff75a1d208fd29999c548ca0568_1150_110438_28_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f64db43374a5c325ec2cc4097bb4aad4_90_109378_28_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f669e83f3f2eaf21f5029a810a94eda0_1216_110504_28_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f66be90a84b327a576c6d66ddcfb752f_893_110181_28_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f67248ab1c1a564af04b1cf480ddd045_275_109563_24_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f682eca2f7f0d6d0d0a2918e136e99c9_137_109425_28_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f721f867cafe1b9d7471033aa617405c_961_110249_28_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f740fd2eb7c649879db7b4bd7a46acfb_442_109729_24_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f754b4d797668fa3374771214e95d124_727_110015_23_111268/
drwxr-x--- 2 systemd-resolve systemd-journal  4096 Feb 12 01:47 f758c4fbf315b93aa9836d3228fe8b9c_1319_110609_23_111268/

```
maybe there are too many write in my situation, I found the could be very slow after 2~3 days.
I alreay force optimize with `FINAL DEDUPLICATED`  serveral hours a time. seems a little help.

may I know how to maintain it better?

Sometimes same query will cost 10s+ after 2~3 days usage.

Thanks!

**Comment by RangerWolf** [comment]
The root cause is found. It is because we use AWS VM and the iops is slow. It is only 150
After increase to 2500, everything works OK

**Comment by den-crane** [comment]
`f5f61b319bd8ff5933ad028f3a7c2ca3_681_109969_23_111268/`

@RangerWolf 

f5f61b319bd8ff5933ad028f3a7c2ca3 -- what's your table `PARTITION BY` and why? 

111268 -- do you use mutations and daily bases operations? Consider to ReplacingMergeTree https://clickhouse.tech/docs/en/operations/table_engines/replacingmergetree/

**Comment by RangerWolf** [comment]
@den-crane 
Hi,
This table does not have date related columns.  It contains columns like :
account_id / account_name / refresh_token / budget ...

I thought there are only around 1K records, so I use account_id as partition key and sort key.

Any suggestion?

**Comment by den-crane** [comment]
@RangerWolf 

My strongly suggestion is to use single partition.

create table .... Engine=ReplacingMergeTree order by account_id -- `partition by -- ommited`

And stop using alter update. And use `insert into + optimize` instead.

Consider to switch to external dictionaries https://clickhouse.tech/docs/en/query_language/dicts/

**Comment by RangerWolf** [comment]
@den-crane 
So many thanks!  I will have a try. 
but one thing I am not clear is that, you metioned `insert into + optimize`  
do you mean trigger `optimize` just after `insert into`?

Thanks again!

**Comment by den-crane** [comment]
>do you mean trigger optimize just after insert into

Yes. Or you can use `from final`. 

SELECT count(*) FROM ads_account **FINAL**

It will work fine against such small table.
