### ISSUE TITLE
Can't move partition to another table 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9086]
CH version  19.15.4

alihb2a_click_001020 :) ALTER TABLE dmp.dm_user_behavior_events MOVE PARTITION (20200209,9) TO TABLE dmp.dm_user_behavior_events_mid ;

Syntax error: failed at position 72:

ALTER TABLE dmp.dm_user_behavior_events MOVE PARTITION (20200209,9) TO TABLE dmp.dm_user_behavior_events_mid ;

Expected one of: NOT, LIKE, AND, OR, IN, BETWEEN, token, IS, NOT LIKE, NOT IN, GLOBAL IN, GLOBAL NOT IN, QuestionMark

**Comment by 4ertus2** [comment]
Most probable you use too old version. Could you reproduce it on 20.1?

**Comment by den-crane** [comment]
>CH version 19.15.4

https://github.com/ClickHouse/ClickHouse/pull/6168 
I think it's not even in release yet.

Though it's working in 20.2.1.234

**Comment by den-crane** [comment]
@onine007  meantime you can use https://clickhouse.tech/docs/en/query_language/alter/#alter_attach-partition-from
