### ISSUE TITLE
ReplicatedMergeTree can't replicated data to other replicas

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9087]
I get log :
2020.02.12 14:51:11.671844 [ 6 ] {} <Trace> dmp.dm_user_behavior_events: Number of queued merges (36) and part mutations (0) is greater than max_replicated_merges_in_queue (16), so won't select new parts to merge or mutate.
2020.02.12 14:51:16.674829 [ 68 ] {} <Trace> dmp.dm_user_behavior_events: Number of queued merges (36) and part mutations (0) is greater than max_replicated_merges_in_queue (16), so won't select new parts to merge or mutate.

**Comment by 4ertus2** [comment]
You may look at system.merges and system.replicated_queue tables content. You may have too much inserts or too small inserts or too slow hardware.

The idea is you need progress in both queues: merges and replication. It's possible if you have enough hardware and optimezed inserts (in big portions of data). It looks like you have too much merges and replication has no resource. Also you are able to add CPU for merges and replication with `background_pool_size` and `background_schedule_pool_size` settings.
