### ISSUE TITLE
Multithread Insert into Distributed table

### ISSUE THREAD

**Issue by artbeglaryan** [ClickHouse/ClickHouse#9095]
Hi. I'm trying to insert big dataset(3-4 tables, each have few billion rows) into Distributed table(2 shard, 1 replica each, non replicated MergeTree tables), and I have sharding_key like `cityHash64(string_column)` and `string_column` is available on all tables.  Dataset are exported from Amazon Redshift and there are ~1000 gzip file for each table. Everything is ok, when I'm inserting with single thread. But when I'm inserting with multiple threads to speedup inserts, nobody use clickhouse, only my inserts (using tmux, command looks like `zcat test_table_[0,1,2,3...].gz | clickhouse-client --query="INSERT INTO test_table FORMAT TSV`), my disk get's full because of Distributed `*.bin` files didn't flushed to remote machines with multiple threads. I tried to set `distributed_directory_monitor_batch_inserts=1` for default profile, but clickhouse-server flushes 2-3 `*.bin`files at one time. I tried also following with `distributed_directory_monitor_batch_inserts=1` settings

1. `SYSTEM STOP DISTRIBUTED SENDS`
2. Insert few files. it generates ~30-40 `*.bin` files
3. `SYSTEM STOP DISTRIBUTED SENDS` 

ClickHouse still flushes maximum 2-3 `*.bin` files at 1 time instead of all.

Is there a way to enforce to flush all bin files or some settings that can help me?

Tested on 
```
ClickHouse client version 20.1.3.7 (official build).
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.1.3 revision 54431.
```

Thanks

**Comment by yuzhichang** [comment]
@artbeglaryan Try the following in  `dbms/src/Core/Settings.h`: `min_insert_block_size_rows`, `min_insert_block_size_bytes`

**Comment by alexey-milovidov** [comment]
@artbeglaryan Yes, sending data to every shard is single-treaded when you use asynchronous INSERTS (that send data in background) and asynchronous mode is by default.

You can enable synchronous INSERTS with setting `insert_distributed_sync` set to 1.
With synchronous INSERTS, when you execute multiple queries concurrently, data will be also sent concurrenlty. Even more, it will eliminate unnecessarity writes and reads of data on filesystem.

The drawback of synchronous INSERTS is that they are unreliable for large clusters.
