### ISSUE TITLE
Insert error with DEFAULT expression

### ISSUE THREAD

**Issue by TimonKK** [ClickHouse/ClickHouse#9096]
I have table like this:
`
CREATE TABLE IF NOT EXISTS session_temp (
		ClientID UUID,
		FirstName String,
		Address String,
		City String,
		StartDate DateTime DEFAULT now()
	) ENGINE = MergeTree()
	PRIMARY KEY ClientID 
	ORDER BY ClientID
`

And I insert data like this:
`
INSERT INTO session_temp Values (generateUUIDv4(), 'Ber', 'Russua', 'Rostov')
`

But I get error:
`
Exception on client:
Code: 62. DB::Exception: Cannot parse expression of type String here: 'Rostov')
`

I expect error text with StartDate column, like you miss column. Or "Column count doesn't match value count" as into MySQL.

Clickhouse verssions:
`
ClickHouse client version 20.1.3.7 (official build).
Connecting to 127.0.0.1:9000 as user default.
Connected to ClickHouse server version 20.1.3 revision 54431.
`

**Comment by TimonKK** [comment]
If I use node js [lib](https://www.npmjs.com/package/clickhouse) and insert like [this](https://pastebin.com/ibqWdaQj) I get error about ClientID:
`
No such column ClientID in table session_temp
`


Full stack trace:
`
2020.02.13 00:43:58.989567 [ 78 ] {a5d5127c-9366-434e-bf7f-8bffabe052d3} <Debug> executeQuery: (from 127.0.0.1:60598) INSERT INTO session_temp (ClientID, FirstName, Address, City) FORMAT TabSeparated
2020.02.13 00:43:58.989812 [ 78 ] {a5d5127c-9366-434e-bf7f-8bffabe052d3} <Debug> MemoryTracker: Peak memory usage (total): 0.00 B.
2020.02.13 00:43:58.989892 [ 78 ] {a5d5127c-9366-434e-bf7f-8bffabe052d3} <Error> executeQuery: Code: 16, e.displayText() = DB::Exception: No such column ClientID in table session_temp (version 20.1.3.7 (official build)) (from 127.0.0.1:60598) (in query: INSERT INTO session_temp (ClientID, FirstName, Address, City) FORMAT TabSeparated ), Stack trace (when copying this message, always include the lines below):

0. 0xbc3212c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4f6cbc9 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x4b891c5 ?  in /usr/bin/clickhouse
3. 0x8beae49 DB::InterpreterInsertQuery::execute()  in /usr/bin/clickhouse
4. 0x8dc0778 ?  in /usr/bin/clickhouse
5. 0x8dc3b6b DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)  in /usr/bin/clickhouse
6. 0x4ffdaaf DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)  in /usr/bin/clickhouse
7. 0x5001993 DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)  in /usr/bin/clickhouse
8. 0x9bb8f7c Poco::Net::HTTPServerConnection::run()  in /usr/bin/clickhouse
9. 0x9bb5a07 Poco::Net::TCPServerConnection::start()  in /usr/bin/clickhouse
10. 0x9bb5dfd Poco::Net::TCPServerDispatcher::run()  in /usr/bin/clickhouse
11. 0xbca488f Poco::PooledThread::run()  in /usr/bin/clickhouse
12. 0xbca1958 Poco::ThreadImpl::runnableEntry(void*)  in /usr/bin/clickhouse
13. 0xbca31f9 ?  in /usr/bin/clickhouse
14. 0x8064 start_thread  in /lib/x86_64-linux-gnu/libpthread-2.19.so
15. 0xe862d clone  in /lib/x86_64-linux-gnu/libc-2.19.so

2020.02.13 00:43:58.990019 [ 78 ] {a5d5127c-9366-434e-bf7f-8bffabe052d3} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.
2020.02.13 00:43:58.990081 [ 78 ] {} <Error> HTTPHandler: Code: 16, e.displayText() = DB::Exception: No such column ClientID in table session_temp, Stack trace (when copying this message, always include the lines below):

0. 0xbc3212c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4f6cbc9 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x4b891c5 ?  in /usr/bin/clickhouse
3. 0x8beae49 DB::InterpreterInsertQuery::execute()  in /usr/bin/clickhouse
4. 0x8dc0778 ?  in /usr/bin/clickhouse
5. 0x8dc3b6b DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)  in /usr/bin/clickhouse
6. 0x4ffdaaf DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)  in /usr/bin/clickhouse
7. 0x5001993 DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)  in /usr/bin/clickhouse
8. 0x9bb8f7c Poco::Net::HTTPServerConnection::run()  in /usr/bin/clickhouse
9. 0x9bb5a07 Poco::Net::TCPServerConnection::start()  in /usr/bin/clickhouse
10. 0x9bb5dfd Poco::Net::TCPServerDispatcher::run()  in /usr/bin/clickhouse
11. 0xbca488f Poco::PooledThread::run()  in /usr/bin/clickhouse
12. 0xbca1958 Poco::ThreadImpl::runnableEntry(void*)  in /usr/bin/clickhouse
13. 0xbca31f9 ?  in /usr/bin/clickhouse
14. 0x8064 start_thread  in /lib/x86_64-linux-gnu/libpthread-2.19.so
15. 0xe862d clone  in /lib/x86_64-linux-gnu/libc-2.19.so
 (version 20.1.3.7 (official build))

`

**Comment by tavplubix** [comment]
`Cannot parse expression of type String here: 'Rostov'` indeed caused by mismatching of columns count (parser expects `,` after `'Rostov'`, not `)`) and we should make exception message clear. 

Default expressions in `Values` format can be inserted this way:
```
INSERT INTO session_temp (ClientID, FirstName, Address, City) Values (generateUUIDv4(), 'Ber', 'Russua', 'Rostov')
```
or
```
SET input_format_null_as_default=1;
INSERT INTO session_temp Values (generateUUIDv4(), 'Ber', 'Russua', 'Rostov', NULL);
```

As for `No such column ClientID in table session_temp`, I cannot reproduce it on 20.1.3 by using clickhouse-client directly, the following works fine:
```
$ echo -e "12345678-1234-4000-8000-123456789abc\tBer\tRussua\tRostov" | clickhouse client -q "INSERT INTO session_temp (ClientID, FirstName, Address, City) FORMAT TabSeparated"
```
and the same with Values works too:
```
$ clickhouse client -q "INSERT INTO session_temp (ClientID, FirstName, Address, City) Values (generateUUIDv4(), 'Ber', 'Russua', 'Rostov')"
```

**Comment by tavplubix** [comment]
Related: #7882, #7943

**Comment by josephcomisi** [comment]
Hello, same issue here. Any news on that ?

CREATE TABLE test (
    id INT NOT NULL,
    inserted_at DateTime64(9, 'UTC') DEFAULT now64(9, 'UTC')
) ENGINE = MergeTree
ORDER BY id;

INSERT INTO test VALUES (1)
-> Return: Code: 62. DB::Exception: Cannot parse expression of type Int32 here: 1): While executing ValuesBlockInputFormat. (SYNTAX_ERROR) (version 22.12.3.5 (official build))

INSERT INTO test VALUES (1, '')
-> Return 'OK', but with inserted_at = 1970-01-01 00:00:00.000000000

INSERT INTO test VALUES (1, NULL)
-> Return 'OK' with right value

**Comment by den-crane** [comment]
@josephcomisi everything works as expected in your example.

Probably you should use `materialized`

```sql
CREATE TABLE test (
id INT NOT NULL,
inserted_at DateTime64(9, 'UTC') materialized now64(9, 'UTC')
) ENGINE = MergeTree
ORDER BY id;

INSERT INTO test VALUES (1);

select id, inserted_at from test;
┌─id─┬───────────────────inserted_at─┐
│  1 │ 2023-01-13 16:12:48.745541089 │
└────┴───────────────────────────────┘
```
