### ISSUE TITLE
delete operate and romate  clickhouse

### ISSUE THREAD

**Issue by 865357384** [ClickHouse/ClickHouse#9097]
I have two clickhouses, one of which processes ETL data and synchronizes it to another host for query. When synchronizing, delete the host data first, and then desynchronize.

step 1：（host 1）
      ALTER TABLE dws_data.pay_hour_pgcr_stat DELETE WHERE STORE_DAY=20200212

step 2：（host 1）
     insert into dws_data.pay_hour_pgcr_stat
     select *
     from temp
     where STORE_DAY=20200212

step 3：（host 2）
      ALTER TABLE dws_data.pay_hour_pgcr_stat DELETE WHERE STORE_DAY=20200212

step 4：（host 2）
      insert into dws_data.pay_hour_pgcr_stat
      SELECT *
      FROM remote(' host 1:9000 ',dws_data.pay_hour_pgcr_stat,'username','passwd')
     WHERE STORE_DAY=20200212

question：
        Why are the data processed in step 1 and step 2 correct? But when step 3 and step 4 come, the data of the second host will be multiplied or a little more than the data of the first host. How should this problem be avoided?

**Comment by 4ertus2** [comment]
Is `dws_data.pay_hour_pgcr_stat` a Replicated table? What do you have in system.repllication_queue and system.merges on both nodes before `insert select`?

The ALTER DELET command is not a transaction. It finishes when accordng queues would finish.

**Comment by blinkov** [comment]
@865357384, do you have any further questions?

**Comment by alexey-milovidov** [comment]
No answer.
