### ISSUE TITLE
Add information about all tables used in query to system.query_log

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#9099]
**Use case**
To determine trivially which tables were used in query without query parsing. 
**Describe the solution you'd like**
Nested structure (database String, table String) in system.query_log

**Comment by alexey-milovidov** [comment]
Maybe it can be trivially implemented with hook in getTable method in query context, that will store this data in the query context. Thoughts @tavplubix ?

**Comment by alexey-milovidov** [comment]
@tavplubix said that it's better to extract them in AST level.

**Comment by filimonov** [comment]
> @tavplubix said that it's better to extract them in AST level.

Engine=Merge, distributed - too?

**Comment by alexey-milovidov** [comment]
We decided to extract tables in AST level. It will work for tables that are mentioned in SQL query, not for tables that are actually used.

**Comment by alexey-milovidov** [comment]
Duplicate of #9030
