### ISSUE TITLE
Try recently open-sourced google/tcmalloc

### ISSUE THREAD

**Issue by chhetripradeep** [ClickHouse/ClickHouse#9102]
Google recently open-sourced new and improved version of tcmalloc (https://github.com/google/tcmalloc). The one which we are using right now is the older one (https://github.com/gperftools/gperftools)

It will be nice to have a build for this new tcmalloc allocator and do some performance tests. I would love to benchmark clickhouse if we can provide a build.

**Comment by alexey-milovidov** [comment]
#11590

**Comment by alexey-milovidov** [comment]
It's complicated. Currently the new tcmalloc does not provide any performance benefits, only regressions.
