### ISSUE TITLE
alter modify column type from String to IPv4 wont work

### ISSUE THREAD

**Issue by alekon** [ClickHouse/ClickHouse#9119]
**Describe the bug or unexpected behaviour**
I wanted to change data type for column from String to IPv4. I've read docs that it's possible by statement alter table xxx modify column yyy type
But unexpectedly server returns error
DB::Exception: Cannot parse string '176.59.200.124' as IPv4: syntax error at position 3 (parsed just '176'). Note: there are toIPv4OrZero and toIPv4OrNull functions, which returns zero/NULL instead of throwing exception..

**How to reproduce**
* Which ClickHouse server version to use
20.1.4 revision 54431 (from Ubuntu 18.04 LTS repo)

* Which interface to use, if matters
cli (clickhouse-client 20.1.4.14 (official build) )

* Non-default settings, if any
No

* `CREATE TABLE` statements for all tables involved
CREATE DATABASE IF NOT EXISTS test_alter;
CREATE TABLE test_alter.t (event_time UInt32, event_date Date DEFAULT toDate(event_time), ip String) ENGINE = MergeTree(event_date, (event_time), 8192);

* Sample data for all these tables
insert  into test_alter.t (event_time, ip) values(1581679033, '176.59.200.124');

* Queries to run that lead to unexpected result
alter table t modify column ip IPv4;

**Expected behavior**
Alter query returned Ok. Column data-type changed and data converted through toIPv4() function as stated in documentation

**Error message and/or stacktrace**

ALTER TABLE t
    MODIFY COLUMN 
    `ip` IPv4

Received exception from server (version 20.1.4):
Code: 6. DB::Exception: Received from localhost:9000. DB::Exception: Cannot parse string '176.59.200.124' as IPv4: syntax error at position 3 (parsed just '176'). Note: there are toIPv4OrZero and toIPv4OrNull functions, which returns zero/NULL instead of throwing exception.. 

0 rows in set. Elapsed: 0.007 sec. 

**Additional context**

**Comment by alexey-milovidov** [comment]
Duplicate: #11999
