### ISSUE TITLE
Back quotes do not work with analiased subselects

### ISSUE THREAD

**Issue by LittleMaverick** [ClickHouse/ClickHouse#9124]
```
CREATE DATABASE IF NOT EXISTS temp

CREATE TABLE temp.keyword_test 
   (
       number Int64
   ) 
ENGINE = Memory;
```

I try to execute such query:
```
SELECT interval
FROM (
    SELECT
        number AS interval
      FROM (
        SELECT number
        FROM temp.keyword_test
    )
)
```

But it throws an exception:
```
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 75 (line 4, col 9): number AS interval
      FROM (
        SELECT number
        FROM temp.keyword_test
    )
)

 FORMAT JSON . Expected one of: AND, OR, alias, token, AS, NOT, BETWEEN, LIKE, IS, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark (version 20.1.4.14 (official build))
```

but, rename 'interval' to something else, 'interval1', for example, and it works how expected.

**Comment by 4ertus2** [comment]
It's OK to have special words. They should be masked by back quotes. But there's really a bug with the last notation.

```
SELECT * FROM (SELECT number AS `interval` FROM (SELECT number FROM numbers(1)));

SELECT s.`interval` FROM (SELECT number AS `interval` FROM (SELECT number FROM numbers(1))) s;

SELECT `interval` FROM (SELECT number AS `interval` FROM (SELECT number FROM numbers(1)));
```

**Comment by LittleMaverick** [comment]
SELECT number AS interval FROM (SELECT number FROM temp.keyword_test) - ok. But if add one more SELECT FROM - fail. Is it expected behavior? @4ertus2

**Comment by 4ertus2** [comment]
It's zone of uncertainty should we support aliases that have names of functions. Specifically in this case it's an error cause we allow to have alias in one case but disallow in another. But it's probably OK both do disable or enable it if its have the same behaviour in all cases. It's better to use back quotes in all such cases. It's even better to make all subqueries aliased too.

**Comment by LittleMaverick** [comment]
@4ertus2  
Which words are special and should be masked by back quotes?

**Comment by 4ertus2** [comment]
INTERVAL is SQL data type and could be parsed in special way in some context. If you make an alias with name of a type, e.x. `select x as UInt32` or function name `select x as round` you may have troubles without back quotes.
