### ISSUE TITLE
Get help division by zero

### ISSUE THREAD

**Issue by lzy305** [ClickHouse/ClickHouse#9145]
create table default.test(
    d_rt_qty Decimal(18, 4),
    package_qty Decimal(18 ,4)
) engine  = Log;

insert into default.test(d_rt_qty, package_qty)
values (1, 0),
       (2, 4);

select multiIf(package_qty=0, 0 , d_rt_qty / package_qty)  from default.test;

result:
Code: 153, e.displayText() = DB::Exception: Division by zero (version 19.17.4.11)

**Comment by lzy305** [comment]
(package_num = 0 ? toDecimal128(0.0000, 4) : d_rt_qty) / (package_num = 0 ? toDecimal128(1.0000, 4) : package_num)

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/1562
check this https://github.com/ClickHouse/ClickHouse/issues/4411#issuecomment-464329721
