### ISSUE TITLE
Out of bound in ColumnVector  error

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9153]
query : 
SELECT 
    event_dt, 
    mode, 
    countDistinct(user_id) AS measure
FROM events
WHERE (events.event_dt = 20200216) AND (events.client_id = 1) AND (events.event_id = 4) AND ((toInt32OrNull(events.event_attr16) IN (2)) AND (events.client_ver >= '0757'))
GROUP BY 
    event_dt, 
    mode

Received exception from server (version 20.1.3):
Code: 12. DB::Exception: Received from localhost:9000. DB::Exception: Received from ck003:9000. DB::Exception: Parameters start = 17658, length = 8 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 13269).. 

but  work well  on  version  19.15.4

**Comment by onine007** [comment]
> query :
> SELECT
> event_dt,
> mode,
> countDistinct(user_id) AS measure
> FROM events
> WHERE (events.event_dt = 20200216) AND (events.client_id = 1) AND (events.event_id = 4) AND ((toInt32OrNull(events.event_attr16) IN (2)) AND (events.client_ver >= '0757'))
> GROUP BY
> event_dt,
> mode
> 
> Received exception from server (version 20.1.3):
> Code: 12. DB::Exception: Received from localhost:9000. DB::Exception: Received from ck003:9000. DB::Exception: Parameters start = 17658, length = 8 are out of bound in ColumnVector::insertRangeFrom method (data.size() = 13269)..
> 
> but work well on version 19.15.4

The same to 
https://github.com/ClickHouse/ClickHouse/issues/8888

**Comment by onine007** [comment]
Error  log :
2020.02.17 13:45:02.396495 [ 90 ] {ac085a34-77a5-43dc-8d6b-f878fc6d1c06} <Error> executeQuery: Code: 12, e.displayText() = DB::Exception: Parameters start = 17658, length = 8 are out of bound in ColumnVector<T>::insertRangeFrom method (data.size() = 13269). (version 20.1.3.7 (official build)) (from 10.0.1.18:50796) (in query: SELECT countDistinct(user_id) AS measure FROM my_sdap.dm_user_behavior_events WHERE (event_dt = 20200216) AND (client_id = 1) AND (event_id = 4) AND ((toInt32OrNull(event_attr16) IN (2)) AND (client_ver >= '0757')) GROUP BY event_dt, mode), Stack trace (when copying this message, always include the lines below):

0. 0xbc3212c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4f6cbc9 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x8e72898 DB::ColumnVector<unsigned int>::insertRangeFrom(DB::IColumn const&, unsigned long, unsigned long)  in /usr/bin/clickhouse
3. 0x97a295b DB::MergeTreeRangeReader::ReadResult::shrink(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&)  in /usr/bin/clickhouse
4. 0x97a483b DB::MergeTreeRangeReader::ReadResult::optimize()  in /usr/bin/clickhouse
5. 0x97a51dd DB::MergeTreeRangeReader::executePrewhereActionsAndFilterColumns(DB::MergeTreeRangeReader::ReadResult&)  in /usr/bin/clickhouse
6. 0x97a5be4 DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
7. 0x97a591d DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
8. 0x97684c6 DB::MergeTreeBaseSelectProcessor::readFromPartImpl()  in /usr/bin/clickhouse
9. 0x9769cc3 DB::MergeTreeBaseSelectProcessor::generate()  in /usr/bin/clickhouse
10. 0x91a4c87 DB::ISource::work()  in /usr/bin/clickhouse
11. 0x91d6e84 DB::TreeExecutorBlockInputStream::execute()  in /usr/bin/clickhouse
12. 0x91d70a3 DB::TreeExecutorBlockInputStream::readImpl()  in /usr/bin/clickhouse
13. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
14. 0x94a6871 DB::FilterBlockInputStream::readImpl()  in /usr/bin/clickhouse
15. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
16. 0x949c1c8 DB::ExpressionBlockInputStream::readImpl()  in /usr/bin/clickhouse
17. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
18. 0x94e9580 DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)  in /usr/bin/clickhouse
19. 0x94e9b05 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::'lambda'()::operator()() const  in /usr/bin/clickhouse
20. 0x4fa3a77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
21. 0x4fa202f ?  in /usr/bin/clickhouse
22. 0x7e25 start_thread  in /usr/lib64/libpthread-2.17.so
23. 0xf834d __clone  in /usr/lib64/libc-2.17.so

**Comment by CurtizJ** [comment]
It should be fixed in #8914. The fix is available in version 20.1.4.14.
