### ISSUE TITLE
A lot of  unfinished mutations   

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9176]
version :  19.15.4
query: select database,table,count() from  system.mutations where is_done=0 group by database,table 
┌─database─┬─table───────────────────┬─count()─┐
│ my_sdap  │ dm_user_behavior_events │    5491 │
└──────────┴─────────────────────────┴─────────┘

1 rows in set. Elapsed: 0.502 sec. Processed 5.79 thousand rows, 35.63 MB (11.54 thousand rows/s., 70.99 MB/s.)

**Comment by den-crane** [comment]
select **latest_fail_reason** from system.mutations  where is_done=0 limit 3;

**Comment by onine007** [comment]
@den-crane 
result is empty. 
┌─latest_fail_reason─┐
│                    │
│                    │
│                    │
└────────────────────┘

3 rows in set. Elapsed: 0.507 sec. Processed 5.79 thousand rows, 35.63 MB (11.43 thousand rows/s., 70.33 MB/s.)

**Comment by den-crane** [comment]
Does this number 5491 change? Basically everything works as expected. 
You should understand each mutation could re-write whole dm_user_behavior_events table completely. It could take a lot of time, need to read, decompress, filter, compress, write rows in many or all parts (all rows in a table). 

Mutation should not be used on a daily basis as business operations. Consider ReplacingMergeTree or CollapsingMergeTree instead.

**Comment by onine007** [comment]
@den-crane  5491 is not changed  ,    63 delete  queries is requested  per day .

**Comment by onine007** [comment]
> Does this number 5491 change? Basically everything works as expected.
> You should understand that each mutation could re-write whole dm_user_behavior_events table completely. It could take a lot of time, need to read, decompress, filter, compress, write rows in many or all parts (all rows in a table).
> 
> Mutation should not be used on a daily basis as business operations. Consider ReplacingMergeTree or CollapsingMergeTree instead.

Re-write whole table   ?   not some partitions  ?

**Comment by den-crane** [comment]
>Re-write whole table ? not some partitions ?

it could. it depends on mutation WHERE and table partition by / order by

**Comment by onine007** [comment]
@den-crane 

│ my_sdap  │ dm_user_behavior_events │ 0000010881  │ DELETE WHERE (event_dt >= 20191123) AND (event_dt <= 20191125) AND (dt = 20191125) AND (event_id IN (29)) │ 2019-12-03 16:46:09 │ ['20190412','20190505','20190506','20190511','20190512','20190513','20190515','20190516','20190517','20190519','20190520','20190521','20190522','20190524','20190525','20190526','20190527','20190528','20190529','20190530','20190531','20190602','20190603','20190604','20190605','20190606','20190607','20190608','20190609','20190612','20190613','20190614','20190615','20190616','20190617','20190618','20190619','20190620','20190621','20190622','20190623','20190624','20190625','20190626','20190627','20190628','20190629','20190630','20190701','20190702','20190703','20190704','20190705','20190706','20190707','20190708','20190709','20190710','20190711','20190712','20190713','20190714','20190715','20190716','20190717','20190718','20190719','20190720','20190721','20190722','20190723','20190724','20190725','20190726','20190727','20190728','20190729','20190730','20190731','20190801','20190802','20190803','20190804','20190805','20190806','20190807','20190808','20190809','20190810','20190811','20190812','20190813','20190814','20190815','20190816','20190817','20190818','20190819','20190820','20190821','20190822','20190823','20190824','20190825','20190826','20190827','20190828','20190829','20190830','20190831','20190901','20190902','20190903','20190904','20190905','20190906','20190907','20190908','20190909','20190910','20190911','20190912','20190913','20190914','20190915','20190916','20190917','20190918','20190919','20190920','20190921','20190922','20190923','20190924','20190925','20190926','20190927','20190928','20190929','20190930','20191001','20191002','20191003','20191004','20191005','20191006','20191007','20191008','20191009','20191010','20191011','20191012','20191013','20191014','20191015','20191016','20191017','20191018','20191019','20191020','20191021','20191022','20191023','20191024','20191025','20191026','20191027','20191028','20191029','20191030','20191031','20191101','20191102','20191103','20191104','20191105','20191106','20191107','20191108','20191109','20191110','20191111','20191112','20191113','20191114','20191115','20191116','20191117','20191118','20191119','20191120','20191121','20191122','20191123','20191124','20191125','20191126','20191127','20191128','20191129','20191130','20191201','20191202'] │ [8749,9741,10781,10271,10266,10267,10271,8610,10267,10267,10267,10267,10261,10267,10270,10268,10274,10811,10278,10281,10272,10266,10277,6566,10256,10275,10261,10276,10274,10274,10277,10309,10337,10284,10272,10246,10337,10286,10321,10315,10277,10292,10729,10274,10759,10278,10286,10286,10338,10357,10867,10856,10314,10303,10302,10296,10320,10316,10295,10299,10390,10366,10833,10360,10411,10403,10354,10359,10369,10372,11024,10894,11011,10431,11010,10466,11075,15363,19814,25326,25328,25148,25440,25552,25164,25154,25293,25163,25359,25571,25439,25680,25940,26614,26740,26755,27032,27297,26865,27499,27417,27353,27264,27596,28006,28159,28138,28032,28330,29198,30536,30619,31482,31241,31100,30616,30537,31234,33294,33033,33204,28617,28892,28375,27140,26932,30422,30058,30134,24134,24089,24209,24180,23867,23730,23707,24039,23713,22778,22073,22238,22748,22908,22829,22816,23072,23306,23451,23007,22210,21469,20982,21141,21176,21347,21164,20919,20780,20916,21293,20819,20286,19394,17037,14051,11619,10464,9914,9931,10046,9926,9911,12515,12803,13525,9677,8244,4864,4683,4561,4637,4755,4914,4751,4610,4372,4347,4324,4250,4331,4349,4225,4161,4455,4552,4556,4327,4187,4100,3981,3967,2855,1525] │          10 │       0 │                    │ 0000-00-00 00:00:00 │                    │


PARTITION BY event_dt ORDER BY (client_id, event_id, mode, dt, intHash64(user_id)) SAMPLE BY intHash64(user_id)

it is normal ?

**Comment by den-crane** [comment]
@onine007  it should be fine `AND (dt = 20191125) AND (event_id IN (29)` it will read and process only `'20191125'` . 
Is it replicated table? Check system.replication_queue how many mutations is processed right now.

**Comment by onine007** [comment]
@den-crane  yes, it is replicated table .  
query:  select count() from system.replication_queue where is_currently_executing
return  0 
  select count() from system.replication_queue
return 13

**Comment by onine007** [comment]
@den-crane
It is partition by event_dt , not dt . and also be fine (dt = 20191125) AND (event_id IN (29) ?

yes, it is replicated table .
query: select count() from system.replication_queue 
return 0

**Comment by onine007** [comment]
May be re-write whole table 

│ my_sdap  │ dm_user_behavior_events │ 0000016363  │ DELETE WHERE (event_dt = 20191127) AND (dt = 20191129) AND (event_id IN (2228)) │ 2020-02-18 14:24:40 │ ['20190412','20190505','20190506','20190511','20190512','20190513','20190515','20190516','20190517','20190519','20190520','20190521','20190522','20190524','20190525','20190526','20190527','20190528','20190529','20190530','20190531','20190602','20190603','20190604','20190605','20190606','20190607','20190608','20190609','20190612','20190613','20190614','20190615','20190616','20190617','20190618','20190619','20190620','20190621','20190622','20190623','20190624','20190625','20190626','20190627','20190628','20190629','20190630','20190701','20190702','20190703','20190704','20190705','20190706','20190707','20190708','20190709','20190710','20190711','20190712','20190713','20190714','20190715','20190716','20190717','20190718','20190719','20190720','20190721','20190722','20190723','20190724','20190725','20190726','20190727','20190728','20190729','20190730','20190731','20190801','20190802','20190803','20190804','20190805','20190806','20190807','20190808','20190809','20190810','20190811','20190812','20190813','20190814','20190815','20190816','20190817','20190818','20190819','20190820','20190821','20190822','20190823','20190824','20190825','20190826','20190827','20190828','20190829','20190830','20190831','20190901','20190902','20190903','20190904','20190905','20190906','20190907','20190908','20190909','20190910','20190911','20190912','20190913','20190914','20190915','20190916','20190917','20190918','20190919','20190920','20190921','20190922','20190923','20190924','20190925','20190926','20190927','20190928','20190929','20190930','20191001','20191002','20191003','20191004','20191005','20191006','20191007','20191008','20191009','20191010','20191011','20191012','20191013','20191014','20191015','20191016','20191017','20191018','20191019','20191020','20191021','20191022','20191023','20191024','20191025','20191026','20191027','20191028','20191029','20191030','20191031','20191101','20191102','20191103','20191104','20191105','20191106','20191107','20191108','20191109','20191110','20191111','20191112','20191113','20191114','20191115','20191116','20191117','20191118','20191119','20191120','20191121','20191122','20191123','20191124','20191125','20191126','20191127','20191128','20191129','20191130','20191201','20191202','20191203','20191204','20191205','20191206','20191207','20191208','20191209','20191210','20191211','20191212','20191213','20191214','20191215','20191216','20191217','20191218','20191219','20191220','20191221','20191222','20191223','20191224','20191225','20191226','20191227','20191228','20191229','20191230','20191231','20200101','20200102','20200103','20200104','20200105','20200106','20200107','20200108','20200109','20200110','20200111','20200112','20200113','20200114','20200115','20200116','20200117','20200118','20200119','20200120','20200121','20200122','20200123','20200124','20200125','20200126','20200127','20200128','20200129','20200130','20200131','20200201','20200202','20200203','20200204','20200205','20200206','20200207','20200208','20200209','20200210','20200211','20200212','20200213','20200214','20200215','20200216','20200217'] │ [14232,15224,16268,15753,15748,15749,15753,14092,15749,15749,15749,15749,15743,15749,15752,15750,15756,16293,15760,15763,15754,15748,15759,12048,15738,15757,15743,15758,15756,15756,15759,15791,15819,15766,15754,15728,15819,15768,15803,15797,15759,15774,16213,15756,16242,15760,15768,15768,15825,15839,16349,16338,15800,15785,15784,15778,15802,15801,15777,15781,15872,15848,16315,15842,15893,15885,15836,15841,15851,15854,16532,16378,16493,15913,16492,15948,16563,20869,25336,30866,30870,30695,30987,31102,30712,30701,30840,30703,30907,31125,30999,31240,31500,32172,32298,32315,32591,32857,32420,33056,32973,32908,32818,33150,33562,33715,33692,33587,33884,34753,36091,36173,37037,36796,36657,36170,36068,36769,38824,38591,38761,34171,34448,33931,32697,32503,36034,35697,35764,29774,29726,29839,29815,29506,29370,29349,29680,29359,28415,27709,27886,28406,28569,28485,28472,28734,28970,29136,28693,27895,27158,26679,26840,26833,27015,26839,26608,26463,26595,26985,26512,25968,25081,22721,19735,17301,16149,15604,15620,15740,15612,15614,18214,18512,19261,15435,13961,10596,10437,10329,10333,10472,10626,10471,10337,10101,10086,10065,10047,10281,10470,10456,10466,10760,10753,10801,10707,10872,10767,10866,11510,12220,12710,12516,12390,12235,12663,12461,12096,10889,10429,10202,9983,9925,9883,9614,9696,9587,10041,9905,9575,9512,9177,8881,8473,8279,8083,8470,8718,8821,7900,7361,7448,7419,7367,7475,7426,7354,7103,7004,6887,6876,6771,6758,6574,6554,6440,6322,6229,6091,5997,5638,5490,5186,5056,4943,5183,5257,5370,5403,5407,5379,5407,5419,5395,5360,5190,5113,5049,4958,4913,4865,4812,4738,4646,4600,4517,4452,3085,1679] │          10 │       0 │                    │ 0000-00-00 00:00:00 │                    │

**Comment by onine007** [comment]
query:select database,table,is_done,count() from system.mutations  group by database,table,is_done
result : 
my_sdap crowd_bitmap_result_replicated  1       100
my_sdap crowd_bitmap_result_replicated  0       445
my_sdap dm_user_behavior_events 0       5491
my_sdap dm_user_behavior_events 1       100
my_sdap bookmark_task_bitmap_result_replicated  1       100


all table is_done=1 are 100 ;
 other nodes  is_done=1 are 100  too .

**Comment by den-crane** [comment]
>(event_dt >= 20191123) AND (event_dt <= 20191125) 

also OK.

check
```
select latest_fail_reason from system.mutations where is_done=0 limit 3;
select count() from system.replication_queue
```
at all other nodes.

You can restart mutations. 
`detach table dm_user_behavior_events; attach table dm_user_behavior_events;`
And check in CH log why they are stuck.

I assume they all (5491) combine into one super-mutation and it stucks for some reason. 

But anyway even if you fix this issue in two weeks it will appear again because 

> Mutation should not be used on a daily basis as business operations. Consider ReplacingMergeTree or CollapsingMergeTree instead.

**Comment by onine007** [comment]
@den-crane I restart mutations ,but also no data  in table system.replication_queue  and  no change 
 in table system.mutations ; 

It has not this problem  in my test   environment . 
Test environment  has  less partitions than prod   ,  but the same partition data  in  2  environments .

**Comment by den-crane** [comment]
I advised to restart mutations and read clickhouse log (trace) what is going with mutations and where they stuck

**Comment by onine007** [comment]
[ch.log](https://github.com/ClickHouse/ClickHouse/files/4242895/ch.log)
@den-crane is it because partition key is a MATERIALIZED ? 

ddl:

 CREATE TABLE my_sdap.dm_user_behavior_events (`dt` UInt32, `user_id` UInt32, `event_time` DateTime, `event_month` UInt32 MATERIALIZED toYYYYMM(event_time), `event_week_begin` UInt32 MATERIALIZED toYYYYMMDD(toMonday(event_time)), `event_dt` UInt32 MATERIALIZED toYYYYMMDD(event_time), `event_hh` UInt8 MATERIALIZED toHour(event_time), `event_mi` UInt8 MATERIALIZED CAST(formatDateTime(event_time, '%M'), 'UInt8'), `event_id` UInt32, `client_platform` UInt8, `client_id` UInt8, `client_ver` Nullable(String), `mode` UInt8, `is_married` Nullable(Int8), `tad` UInt16, `active_days` UInt16, `is_first_day` UInt8 ALIAS IF(active_days = 0, 1, 0), `age` Nullable(Int8), `duration_phase` Nullable(Int8), `duration_phase_days` Nullable(Int8), `gestation_stage` Nullable(Int8), `gestation_weeks` Nullable(Int16), `baby_months` Nullable(Int16), `baby_weeks` Nullable(Int16), `pregnancy_months` Nullable(Int16), `channel` Nullable(String), `province` Nullable(Int32), `city` Nullable(Int32), `phone_manufacturer` Nullable(Int16), `phone_model_code` Nullable(Int32), `apn` Nullable(Int8), `opt` Nullable(Int8), `ab_exp_group` Array(String), `ab_isol` Array(String), `business_type` Int8 MATERIALIZED CAST(multiIf(event_id IN (47, 46, 45, 44, 6, 48), multiIf(event_attr10 IN ('1', '4'), 1, event_attr10 IN ('2', '3', '5'), 2, event_attr10 IN ('6', '7'), 3, 0), event_id IN (100), multiIf(event_attr11 IN ('1', '4'), 1, event_attr11 IN ('2', '3', '5'), 2, event_attr11 IN ('6', '7'), 3, 0), event_id IN (32, 40, 73, 38, 41), multiIf(event_attr13 IN ('1', '4'), 1, event_attr13 IN ('2', '3', '5'), 2, event_attr13 IN ('6', '7'), 3, 0), event_id IN (31), multiIf(event_attr14 IN ('1', '4'), 1, event_attr14 IN ('2', '3', '5'), 2, event_attr14 IN ('6', '7'), 3, 0), event_id IN (60, 59, 52), multiIf(event_attr15 IN ('1', '4'), 1, event_attr15 IN ('2', '3', '5'), 2, event_attr15 IN ('6', '7'), 3, 0), event_id IN (68, 67, 71, 66, 70, 69), multiIf(event_attr16 IN ('1', '4'), 1, event_attr16 IN ('2', '3', '5'), 2, event_attr16 IN ('6', '7'), 3, 0), event_id IN (61, 20, 15, 19, 14, 18, 13, 17, 62, 16, 112, 113, 120), multiIf(event_attr17 IN ('1', '4'), 1, event_attr17 IN ('2', '3', '5'), 2, event_attr17 IN ('6', '7'), 3, 0), event_id IN (84, 85), multiIf(event_attr18 IN ('1', '4'), 1, event_attr18 IN ('2', '3', '5'), 2, event_attr18 IN ('6', '7'), 3, 0), event_id IN (30, 29, 28), multiIf(event_attr20 IN ('1', '4'), 1, event_attr20 IN ('2', '3', '5'), 2, event_attr20 IN ('6', '7'), 3, 0), event_id IN (4), multiIf(event_attr24 IN ('1', '4'), 1, event_attr24 IN ('2', '3', '5'), 2, event_attr24 IN ('6', '7'), 3, 0), event_id IN (24), multiIf(event_attr6 IN ('1', '4'), 1, event_attr6 IN ('2', '3', '5'), 2, event_attr6 IN ('6', '7'), 3, 0), event_id IN (23, 22, 34, 21, 33), multiIf(event_attr7 IN ('1', '4'), 1, event_attr7 IN ('2', '3', '5'), 2, event_attr7 IN ('6', '7'), 3, 0), 0), 'Int8'), `push46_day` Nullable(Int8) ALIAS CAST(if((event_id IN (44, 45, 46, 47, 48)) AND (event_attr1 = '46'), substring(splitByString('|', ifNull(toString(event_attr5), '0|0|0'))[3], 4, 2), NULL), 'Nullable(Int8)'), `push46_content` Nullable(Int8) ALIAS CAST(if((event_id IN (44, 45, 46, 47, 48)) AND (event_attr1 = '46'), substring(splitByString('|', ifNull(toString(event_attr5), '0|0|0'))[3], 2, 2), NULL), 'Nullable(Int8)'), `push46_stage` Nullable(Int8) ALIAS CAST(if((event_id IN (44, 45, 46, 47, 48)) AND (event_attr1 = '46'), substring(splitByString('|', ifNull(toString(event_attr5), '0|0|0'))[3], 1, 1), NULL), 'Nullable(Int8)'), `baby_age` Int8 ALIAS CAST(multiIf((baby_months >= 0) AND (baby_months <= 12), baby_months, (baby_months >= 13) AND (baby_months <= 24), 24, (baby_months >= 25) AND (baby_months <= 36), 36, (baby_months >= 37) AND (baby_months <= 48), 48, (baby_months >= 49) AND (baby_months <= 60), 60, (baby_months >= 61) AND (baby_months <= 72), 72, baby_months >= 73, 73, -1), 'Int8'), `age_sub` Int8 ALIAS CAST(multiIf((age > 0) AND (age <= 14), 1, age IN (15, 16, 17, 18), 2, age IN (19, 20, 21, 22), 3, age IN (23, 24, 25, 26, 27, 28, 29, 30), 4, age IN (31, 32, 33, 34, 35), 5, age IN (36, 37, 38, 39, 40), 6, age > 40, 7, -1), 'Int8'), `event_attr1` Nullable(String), `event_attr2` Nullable(String), `event_attr3` Nullable(String), `event_attr4` Nullable(String), `event_attr5` Nullable(String), `event_attr6` Nullable(String), `event_attr7` Nullable(String), `event_attr8` Nullable(String), `event_attr9` Nullable(String), `event_attr10` Nullable(String), `event_attr11` Nullable(String), `event_attr12` Nullable(String), `event_attr13` Nullable(String), `event_attr14` Nullable(String), `event_attr15` Nullable(String), `event_attr16` Nullable(String), `event_attr17` Nullable(String), `event_attr18` Nullable(String), `event_attr19` Nullable(String), `event_attr20` Nullable(String), `event_attr21` Nullable(String), `event_attr22` Nullable(String), `event_attr23` Nullable(String), `event_attr24` Nullable(String), `event_attr25` Nullable(String), `event_attr26` Nullable(String), `event_attr27` Nullable(String), `event_attr28` Nullable(String), `event_attr29` Nullable(String), `event_attr30` Nullable(String), `event_attr31` Nullable(String), `event_attr32` Nullable(String), `event_attr33` Nullable(String), `event_attr34` Nullable(String), `event_attr35` Nullable(String), `event_attr36` Nullable(String), `event_attr37` Nullable(String), `event_attr38` Nullable(String), `event_attr39` Nullable(String), `event_attr40` Nullable(String), `event_attr41` Nullable(String), `event_attr42` Nullable(String), `event_attr43` Nullable(String), `event_attr44` Nullable(String), `event_attr45` Nullable(String), `event_attr46` Nullable(String), `event_attr47` Nullable(String), `event_attr48` Array(String), `event_attr49` Array(String), `event_attr50` Array(String), `business_type_alias` Int8 ALIAS CAST(if(event_dt >= 20191127, business_type, multiIf(event_id IN (47, 46, 45, 44, 6, 48), multiIf(event_attr10 IN ('1', '4'), 1, event_attr10 IN ('2', '3', '5'), 2, event_attr10 IN ('6', '7'), 3, 0), event_id IN (100), multiIf(event_attr11 IN ('1', '4'), 1, event_attr11 IN ('2', '3', '5'), 2, event_attr11 IN ('6', '7'), 3, 0), event_id IN (32, 40, 73, 38, 41), multiIf(event_attr13 IN ('1', '4'), 1, event_attr13 IN ('2', '3', '5'), 2, event_attr13 IN ('6', '7'), 3, 0), event_id IN (31), multiIf(event_attr14 IN ('1', '4'), 1, event_attr14 IN ('2', '3', '5'), 2, event_attr14 IN ('6', '7'), 3, 0), event_id IN (60, 59, 52), multiIf(event_attr15 IN ('1', '4'), 1, event_attr15 IN ('2', '3', '5'), 2, event_attr15 IN ('6', '7'), 3, 0), event_id IN (68, 67, 71, 66, 70, 69), multiIf(event_attr16 IN ('1', '4'), 1, event_attr16 IN ('2', '3', '5'), 2, event_attr16 IN ('6', '7'), 3, 0), event_id IN (61, 20, 15, 19, 14, 18, 13, 17, 62, 16, 112, 113, 120), multiIf(event_attr17 IN ('1', '4'), 1, event_attr17 IN ('2', '3', '5'), 2, event_attr17 IN ('6', '7'), 3, 0), event_id IN (84, 85), multiIf(event_attr18 IN ('1', '4'), 1, event_attr18 IN ('2', '3', '5'), 2, event_attr18 IN ('6', '7'), 3, 0), event_id IN (30, 29, 28), multiIf(event_attr20 IN ('1', '4'), 1, event_attr20 IN ('2', '3', '5'), 2, event_attr20 IN ('6', '7'), 3, 0), event_id IN (4), multiIf(event_attr24 IN ('1', '4'), 1, event_attr24 IN ('2', '3', '5'), 2, event_attr24 IN ('6', '7'), 3, 0), event_id IN (24), multiIf(event_attr6 IN ('1', '4'), 1, event_attr6 IN ('2', '3', '5'), 2, event_attr6 IN ('6', '7'), 3, 0), event_id IN (23, 22, 34, 21, 33), multiIf(event_attr7 IN ('1', '4'), 1, event_attr7 IN ('2', '3', '5'), 2, event_attr7 IN ('6', '7'), 3, 0), 0)), 'Int8'), `info_type` Int8 MATERIALIZED CAST(multiIf((event_id IN (7, 6)) AND (event_attr12 >= '0'), multiIf(event_attr12 IN ('0'), 1, event_attr12 IN ('10'), 2, event_attr12 IN ('4'), 4, event_attr12 IN ('2'), 8, event_attr12 IN ('14'), 9, event_attr12 IN ('15'), 10, event_attr12 IN ('1', '11'), 11, 0), (event_id IN (52)) AND (event_attr16 >= '0'), multiIf(event_attr16 IN ('0'), 1, event_attr16 IN ('10'), 2, event_attr16 IN ('4'), 4, event_attr16 IN ('2'), 8, event_attr16 IN ('14'), 9, event_attr16 IN ('15'), 10, event_attr16 IN ('1', '11'), 11, 0), (event_id IN (59, 60)) AND (event_attr19 >= '0'), multiIf(event_attr19 IN ('0'), 1, event_attr19 IN ('10'), 2, event_attr19 IN ('4'), 4, event_attr19 IN ('2'), 8, event_attr19 IN ('14'), 9, event_attr19 IN ('15'), 10, event_attr19 IN ('1', '11'), 11, 0), (event_id IN (28, 38, 66, 71, 32, 41, 68, 31, 70, 30, 40, 67, 73, 29, 69)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('0'), 1, event_attr2 IN ('10'), 2, event_attr2 IN ('4'), 4, event_attr2 IN ('2'), 8, event_attr2 IN ('14'), 9, event_attr2 IN ('15'), 10, event_attr2 IN ('1', '11'), 11, 0), (event_id IN (4)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('0'), 1, event_attr3 IN ('10'), 2, event_attr3 IN ('4'), 4, event_attr3 IN ('2'), 8, event_attr3 IN ('14'), 9, event_attr3 IN ('15'), 10, event_attr3 IN ('1', '11'), 11, 0), (event_id IN (48)) AND (event_attr8 >= '0'), multiIf(event_attr8 IN ('0'), 1, event_attr8 IN ('10'), 2, event_attr8 IN ('4'), 4, event_attr8 IN ('2'), 8, event_attr8 IN ('14'), 9, event_attr8 IN ('15'), 10, event_attr8 IN ('1', '11'), 11, 0), (event_id IN (41, 40, 38)) AND (event_attr1 >= '0'), multiIf(event_attr1 IN ('1', '2', '3'), 1, event_attr1 IN ('12'), 2, event_attr1 IN ('4', '5', '11'), 3, event_attr1 IN ('6'), 4, event_attr1 IN ('9', '10'), 5, event_attr1 IN ('8'), 6, event_attr1 IN ('14'), 7, 0), (event_id IN (59, 60)) AND (event_attr17 >= '0'), multiIf(event_attr17 IN ('1', '2', '3'), 1, event_attr17 IN ('12'), 2, event_attr17 IN ('4', '5', '11'), 3, event_attr17 IN ('6'), 4, event_attr17 IN ('9', '10'), 5, event_attr17 IN ('8'), 6, event_attr17 IN ('14'), 7, 0), (event_id IN (85, 84, 22, 21)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('1', '2', '3'), 1, event_attr2 IN ('12'), 2, event_attr2 IN ('4', '5', '11'), 3, event_attr2 IN ('6'), 4, event_attr2 IN ('9', '10'), 5, event_attr2 IN ('8'), 6, event_attr2 IN ('14'), 7, 0), (event_id IN (52, 4)) AND (event_attr26 >= '0'), multiIf(event_attr26 IN ('1', '2', '3'), 1, event_attr26 IN ('12'), 2, event_attr26 IN ('4', '5', '11'), 3, event_attr26 IN ('6'), 4, event_attr26 IN ('9', '10'), 5, event_attr26 IN ('8'), 6, event_attr26 IN ('14'), 7, 0), (event_id IN (68, 24, 67, 73, 69, 66)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('1', '2', '3'), 1, event_attr3 IN ('12'), 2, event_attr3 IN ('4', '5', '11'), 3, event_attr3 IN ('6'), 4, event_attr3 IN ('9', '10'), 5, event_attr3 IN ('8'), 6, event_attr3 IN ('14'), 7, 0), (event_id IN (23)) AND (event_attr4 >= '0'), multiIf(event_attr4 IN ('1', '2', '3'), 1, event_attr4 IN ('12'), 2, event_attr4 IN ('4', '5', '11'), 3, event_attr4 IN ('6'), 4, event_attr4 IN ('9', '10'), 5, event_attr4 IN ('8'), 6, event_attr4 IN ('14'), 7, 0), (event_id IN (14, 19, 62, 13, 18, 61, 17, 16, 15, 20, 112, 113, 120)) AND (event_attr6 >= '0'), multiIf(event_attr6 IN ('1', '2', '3'), 1, event_attr6 IN ('12'), 2, event_attr6 IN ('4', '5', '11'), 3, event_attr6 IN ('6'), 4, event_attr6 IN ('9', '10'), 5, event_attr6 IN ('8'), 6, event_attr6 IN ('14'), 7, 0), (event_id IN (48)) AND (event_attr9 >= '0'), multiIf(event_attr9 IN ('1', '2', '3'), 1, event_attr9 IN ('12'), 2, event_attr9 IN ('4', '5', '11'), 3, event_attr9 IN ('6'), 4, event_attr9 IN ('9', '10'), 5, event_attr9 IN ('8'), 6, event_attr9 IN ('14'), 7, 0), (event_id IN (71, 70)) AND (event_attr23 >= '0'), multiIf(event_attr23 IN ('1', '2', '3'), 1, event_attr23 IN ('4'), 3, 0), 0), 'Int8'), `info_type_alias` Int8 ALIAS CAST(if(event_dt >= 20191127, info_type, multiIf((event_id IN (7, 6)) AND (event_attr12 >= '0'), multiIf(event_attr12 IN ('0'), 1, event_attr12 IN ('10'), 2, event_attr12 IN ('4'), 4, event_attr12 IN ('2'), 8, event_attr12 IN ('14'), 9, event_attr12 IN ('15'), 10, event_attr12 IN ('1', '11'), 11, 0), (event_id IN (52)) AND (event_attr16 >= '0'), multiIf(event_attr16 IN ('0'), 1, event_attr16 IN ('10'), 2, event_attr16 IN ('4'), 4, event_attr16 IN ('2'), 8, event_attr16 IN ('14'), 9, event_attr16 IN ('15'), 10, event_attr16 IN ('1', '11'), 11, 0), (event_id IN (59, 60)) AND (event_attr19 >= '0'), multiIf(event_attr19 IN ('0'), 1, event_attr19 IN ('10'), 2, event_attr19 IN ('4'), 4, event_attr19 IN ('2'), 8, event_attr19 IN ('14'), 9, event_attr19 IN ('15'), 10, event_attr19 IN ('1', '11'), 11, 0), (event_id IN (28, 38, 66, 71, 32, 41, 68, 31, 70, 30, 40, 67, 73, 29, 69)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('0'), 1, event_attr2 IN ('10'), 2, event_attr2 IN ('4'), 4, event_attr2 IN ('2'), 8, event_attr2 IN ('14'), 9, event_attr2 IN ('15'), 10, event_attr2 IN ('1', '11'), 11, 0), (event_id IN (4)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('0'), 1, event_attr3 IN ('10'), 2, event_attr3 IN ('4'), 4, event_attr3 IN ('2'), 8, event_attr3 IN ('14'), 9, event_attr3 IN ('15'), 10, event_attr3 IN ('1', '11'), 11, 0), (event_id IN (48)) AND (event_attr8 >= '0'), multiIf(event_attr8 IN ('0'), 1, event_attr8 IN ('10'), 2, event_attr8 IN ('4'), 4, event_attr8 IN ('2'), 8, event_attr8 IN ('14'), 9, event_attr8 IN ('15'), 10, event_attr8 IN ('1', '11'), 11, 0), (event_id IN (41, 40, 38)) AND (event_attr1 >= '0'), multiIf(event_attr1 IN ('1', '2', '3'), 1, event_attr1 IN ('12'), 2, event_attr1 IN ('4', '5', '11'), 3, event_attr1 IN ('6'), 4, event_attr1 IN ('9', '10'), 5, event_attr1 IN ('8'), 6, event_attr1 IN ('14'), 7, 0), (event_id IN (59, 60)) AND (event_attr17 >= '0'), multiIf(event_attr17 IN ('1', '2', '3'), 1, event_attr17 IN ('12'), 2, event_attr17 IN ('4', '5', '11'), 3, event_attr17 IN ('6'), 4, event_attr17 IN ('9', '10'), 5, event_attr17 IN ('8'), 6, event_attr17 IN ('14'), 7, 0), (event_id IN (85, 84, 22, 21)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('1', '2', '3'), 1, event_attr2 IN ('12'), 2, event_attr2 IN ('4', '5', '11'), 3, event_attr2 IN ('6'), 4, event_attr2 IN ('9', '10'), 5, event_attr2 IN ('8'), 6, event_attr2 IN ('14'), 7, 0), (event_id IN (52, 4)) AND (event_attr26 >= '0'), multiIf(event_attr26 IN ('1', '2', '3'), 1, event_attr26 IN ('12'), 2, event_attr26 IN ('4', '5', '11'), 3, event_attr26 IN ('6'), 4, event_attr26 IN ('9', '10'), 5, event_attr26 IN ('8'), 6, event_attr26 IN ('14'), 7, 0), (event_id IN (68, 24, 67, 73, 69, 66)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('1', '2', '3'), 1, event_attr3 IN ('12'), 2, event_attr3 IN ('4', '5', '11'), 3, event_attr3 IN ('6'), 4, event_attr3 IN ('9', '10'), 5, event_attr3 IN ('8'), 6, event_attr3 IN ('14'), 7, 0), (event_id IN (23)) AND (event_attr4 >= '0'), multiIf(event_attr4 IN ('1', '2', '3'), 1, event_attr4 IN ('12'), 2, event_attr4 IN ('4', '5', '11'), 3, event_attr4 IN ('6'), 4, event_attr4 IN ('9', '10'), 5, event_attr4 IN ('8'), 6, event_attr4 IN ('14'), 7, 0), (event_id IN (14, 19, 62, 13, 18, 61, 17, 16, 15, 20, 112, 113, 120)) AND (event_attr6 >= '0'), multiIf(event_attr6 IN ('1', '2', '3'), 1, event_attr6 IN ('12'), 2, event_attr6 IN ('4', '5', '11'), 3, event_attr6 IN ('6'), 4, event_attr6 IN ('9', '10'), 5, event_attr6 IN ('8'), 6, event_attr6 IN ('14'), 7, 0), (event_id IN (48)) AND (event_attr9 >= '0'), multiIf(event_attr9 IN ('1', '2', '3'), 1, event_attr9 IN ('12'), 2, event_attr9 IN ('4', '5', '11'), 3, event_attr9 IN ('6'), 4, event_attr9 IN ('9', '10'), 5, event_attr9 IN ('8'), 6, event_attr9 IN ('14'), 7, 0), (event_id IN (71, 70)) AND (event_attr23 >= '0'), multiIf(event_attr23 IN ('1', '2', '3'), 1, event_attr23 IN ('4'), 3, 0), 0)), 'Int8')) ENGINE = ReplicatedMergeTree('/clickhouse/tables/my_sdap/dm_user_behavior_events/{shard}', '{replica}') PARTITION BY event_dt ORDER BY (client_id, event_id, mode, dt, intHash64(user_id)) SAMPLE BY intHash64(user_id) TTL event_time + toIntervalDay(1000) SETTINGS index_granularity = 8192

**Comment by onine007** [comment]
Or   is it no data to delete ?

**Comment by den-crane** [comment]
it's only 2 seconds of log. I don't see any issue in it.

**Comment by onine007** [comment]
[delete.log](https://github.com/ClickHouse/ClickHouse/files/4285848/delete.log)
Then, MemoryTracker  is increase to

**Comment by blinkov** [comment]
@onine007, do you have any further questions?
