### ISSUE TITLE
ClusterCopier: allow materialized/aliased columns in the push table?

### ISSUE THREAD

**Issue by dingxiangfei2009** [ClickHouse/ClickHouse#9177]
**Use case**
ClusterCopier currently removes materialized and aliased columns from the push table `CREATE TABLE` statement, cf. https://github.com/ClickHouse/ClickHouse/blob/c76a82777c8b28608a3dfa0640cc6a003b1746bb/dbms/programs/copier/ClusterCopier.cpp#L2159-L2161

There are use cases that materialized columns are desirable. Having row keys defined as a hash of other key columns of the table and stored in a materialized column, preserving this information can be helpful after copying to enable optimization in further processing in the target cluster.

**Describe the solution you'd like**
There are a few ways to configure the behavior, if it is deemed a useful feature. One can opt-in those materialized or aliased columns in the task description; or opt-out the selected columns and create the other materialized or aliased columns by default.

Also, for safety, an ordered list of column names to be inserted into should be made explicit in the distributed `INSERT INTO` statement and `SELECT` statement, stating which columns should be inserted into which.

**Describe alternatives you've considered**
I am all ears. Suggestions and alternatives are welcome.

**Additional context**
Maybe related to #9159, in case a unified column description is desirable. When designing the configuration options, considerations can be made for both these feature requests.

I am showing interesting to add more details and materialize this feature, if this is a good idea. :smile:

**Comment by nikitamikhaylov** [comment]
But if you explicitly create target tables by yourself, everything will work pretty well. Copier removes materialized and aliased columns only for internal service tables. It is needed to not to send useless data over the network.

**Comment by nikitamikhaylov** [comment]
Will be implemented in #23518
