### ISSUE TITLE
Any idea to replace etcd with zookeeper

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#9180]
Is the clickhouse cluster too dependent on zookeeper？

With the growth of shard and data, will the pressure of zookeeper increase linearly?

**Comment by den-crane** [comment]
>Is the clickhouse cluster too dependent on zookeeper？

YES. CH supports and works properly only with ZK.

https://github.com/ClickHouse/ClickHouse/issues/777
https://github.com/ClickHouse/ClickHouse/issues/479

>With the growth of shard and data, will the pressure of zookeeper increase linearly?

With proper table design small zk server (32GB RAM, SSD disk) is enough for a huge cluster with upto 1000 nodes with petabytes of data.

**Comment by filimonov** [comment]
There are some plans to use clickhouse, there are chances that some experimental support for etcd will appear in mid of 2020. 
https://clickhouse.tech/docs/ru/extended_roadmap/#19-2-podkliuchenie-etcd-ili-consul-kak-alternativy-zookeeper
