### ISSUE TITLE
Partitions are not removed if the time went backwards after startup

### ISSUE THREAD

**Issue by blind-oracle** [ClickHouse/ClickHouse#9189]
**Describe the bug or unexpected behaviour**

On one of the cluster nodes system time (due to hypervisor problems) at boot was set ~1 month in future (20.02.2020). Then, after some minutes, it got synced by *ntpd* and then went fine.

Clickhouse was started when the time was wrong and it probably caused Clickhouse to stop removing partitions after it merged them. This led to fast disk space exhaustion.

After CH was restarted it pruned 99% of inactive partitions, but the ones from the future still remain:

```
# ls -l | grep Mar
drwxr-x--- 2 clickhouse clickhouse 4096 Mar 20  2020 202002_431472_431521_9
drwxr-x--- 2 clickhouse clickhouse 4096 Mar 20  2020 202002_431472_431547_10
drwxr-x--- 2 clickhouse clickhouse 4096 Mar 20  2020 202002_431472_431552_11
drwxr-x--- 2 clickhouse clickhouse 4096 Mar 20  2020 202002_431472_431557_12
drwxr-x--- 2 clickhouse clickhouse 4096 Mar 20  2020 202002_431472_431562_13
drwxr-x--- 2 clickhouse clickhouse 4096 Mar 20  2020 202002_431472_431576_14
...

# ls -l | grep Mar | wc -l
102
```
They're marked in system.parts as inactive.

Before restart there were a lot (tens of thousands) of other inactive parts which had correct ctime on the filesystem (created after the time sync probably), but they were not automatically removed too.

**How to reproduce**
* Clickhouse 19.16.12.49
* Boot system and start CH with time in future
* Sync time
* Ingest data
* Observe inactive parts not removed

**Comment by alexey-milovidov** [comment]
We are using part modification time to remove old parts. For existing parts it is initialized with directory modification time on filesystem and for parts created in runtime it is set to wall clock time. So, this is expected to happen. Let's think what we can change...

**Comment by blind-oracle** [comment]
@alexey-milovidov 

Hmm, this probably should not cause this effect.

Let's consider a case:
1. OS boots, time is wrong and in future, some existing parts on disk with time in past (relative to server time), if they're inactive they will be immediately purged, that's expected.
2. CH starts, clients connect and ingest data, CH creates parts with server wall clock ctime (in the future)
3. Time syncs (goes backwards), the parts created in (2) are in the distant future relative to wall clock. I guess that they're not cleaned up properly until this time arrives, that's expected.
4. New parts are created, they are getting correct (current) ctime on the directory. And in CH in-memory they should have correct time (wall clock). But they **are not** removed and occupy disk space until CH is restarted.

My very wild guess is that has to do with time going backwards and non-monotonic clocks used by CH.
