### ISSUE TITLE
Query performance not reflecting partition

### ISSUE THREAD

**Issue by mvcalder-xbk** [ClickHouse/ClickHouse#9200]
We are storing time series data in a single table. For each date we have multiple (~10K) ids with several thousand values indexed by a timestamp, so tuples of `(date, id, timestamp, value)`. We partition the table by date, and use the tuple `(date, id, timestamp)` as the order key. 

We are measuring query performance using `system.query_log` and are noticing that queries are taking longer and consuming more memory as we add additional dates to the table even though the queries themselves are limited to single dates. For example,

```
select id, avg(value) 
from ts_table 
where timestamp >= '2020-02-08 00:00:00' and timestamp <=  '2020-02-08 23:59:59'
```

We expected that because the timestamp filters to a specific partition of the data, that query time and memory usage would not increase when we add data for more days. Is our understanding correct? Thanks for any suggestions.

**Comment by den-crane** [comment]
You made two mistakes. 
* You did not mention partition key (date) in WHERE
* You put date as the first field but again did not mention  date in WHERE

Right now you can fix it
```
where 
   date between '2020-02-08' and '2020-02-08' and
   timestamp >= '2020-02-08 00:00:00' and timestamp <=  '2020-02-08 23:59:59'
```

But better use this
```
....
Partition by toYYYYMMDD(timestamp)
Order by (id, timestamp)

where timestamp >= '2020-02-08 00:00:00' and timestamp <=  '2020-02-08 23:59:59'
```

https://stackoverflow.com/a/60155974/11644308

**Comment by mvcalder-xbk** [comment]
Thanks @den-crane,

I guess I misunderstood how the partitioning mechanism worked. In our actual database (the example was simplified for the  question) we were computing the date from the timestamp (both are strings here) via `substr(timestamp,1,10)`. I thought CH would "figure out" the partition, in hindsight that is probably a lot to ask. We've run some experiments using an explicit date column, partitioning on that, and including it in our query and that gives us the desired result that query time and resources are independent of the presence of unused partitions. Thank you for your help,

Matt

**Comment by den-crane** [comment]
If you do like this
```
create table XX (timestamp String, date String default substring(timestamp,1,10), K Int64, S String ) 
Engine=MergeTree 
partition by date
order by (date, K, timestamp);
insert into XX(timestamp, K) select '2019-01-01 00:00:00', number from numbers(1000000);
insert into XX(timestamp, K) select '2020-01-01 00:00:00', number from numbers(1000000);

select count() 
from XX 
where timestamp between  '2019-01-01 00:00:00' and  '2019-02-01 00:00:00'
Processed 2.00 million rows,
```
CH SELECT is not legit to assume that date filled with default and related to timestamp so pruning does not work.

It will work for date column conditions

```
SELECT count()
FROM XX
WHERE (date >= substring('2019-01-01 00:00:00', 1, 10)) AND (date <= substring('2019-02-01 00:00:00', 1, 10))

Processed 1.00 million rows
```

You can partition by expression `substring(timestamp,1,10)` then pruning will work for timestamp

```
create table XX (timestamp String, date String default substring(timestamp,1,10), K Int64, S String ) 
Engine=MergeTree 
partition by substring(timestamp,1,10)
order by (K, timestamp);
insert into XX(timestamp, K) select '2019-01-01 00:00:00', number from numbers(1000000);
insert into XX(timestamp, K) select '2020-01-01 00:00:00', number from numbers(1000000);

SELECT count()
FROM XX
WHERE (timestamp >= '2019-01-01 00:00:00') AND (timestamp <= '2019-02-01 00:00:00')

Processed 1.00 million rows```

**Comment by mvcalder-xbk** [comment]
Thanks @den-crane for a great explanation. What we had been doing was effectively as you do in your last example, with the partition key `substring(timestamp,1,10)` except our `where` clause was also using `substring(timestamp,1,10)`. Doing that:

```
SELECT count()

FROM XX

WHERE (substring(timestamp, 1, 10) >= '2019-01-01') AND (substring(timestamp, 1, 10) <= '2019-02-01')

┌─count()─┐

│ 1000000 │

└─────────┘

1 rows in set. Elapsed: 0.018 sec. Processed 2.00 million rows, 56.00 MB (110.22 million rows/s., 3.09 GB/s.)
```

It makes sense this doesn't take advantage of the partitioning as the pruning algo would have to special case that the function in the where clause matched the partition key funciton or somehow peer into it to see that it was prunable. Based on your last example we changed our queries to use the timestamp explicitly and see the positive results your example indicates. Thank you.

**Comment by den-crane** [comment]
>except our where clause was also using substring(timestamp,1,10).

So you doing it wrong again. See in my example `Processed 1.00 million rows` VS your `Processed 2.00 million rows`

CH stores in parts minmax value of timestamp '2019-01-01 00:00:00' and stores substring(timestamp,1,10) NOWHERE. So select unable to use `substring(timestamp,1,10)` for pruning.

explanation https://stackoverflow.com/a/60155974/11644308

**Comment by mvcalder-xbk** [comment]
Yes, I think we are agreeing, my example was intended to demonstrate our original mistake.

**Comment by den-crane** [comment]
ah. OK. :thumbsup:
