### ISSUE TITLE
errorlog doesn't contain sql query for fatal errors but does for usual errors

### ISSUE THREAD

**Issue by morozovsk** [ClickHouse/ClickHouse#9215]
I have logger level **warning** and for errors with level **Error** I have additional info 
like this:

> Syntax error: failed at position 1978: $where GROUP BY carrier, t HAVING n > 0 AND uniq(device_id) > 10 ORDER BY t, n desc LIMIT 9 by t

But for errors with level **Fatal** I have only:
>query_id: a97101ea-61be-488e-9811-c26197624b9a 

So I need change logger level from **warning** to **trace** for logging every query (write gigabytes to disk) and wait for one error and after change logger level back.

I think it is unexpected behaviour.
Please add sql query for fatal errors.

**Comment by abyss7** [comment]
I will check in which cases and on what log-levels we get full sql query associated with query-id in server logs.

**Comment by alexey-milovidov** [comment]
@abyss7 FATAL errors are reports for deadly signal (segfault, abort, etc). We transfer data that will be logged through the pipe. See https://github.com/ClickHouse/ClickHouse/issues/5826

It's possible to also transfer pointer to the query and print it.

**Comment by alexey-milovidov** [comment]
Unassigned because nothing was done.

**Comment by alexey-milovidov** [comment]
Implemented.
