### ISSUE TITLE
Build all contribs using our own CMake files

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#9226]
All contribs should be based on common template:

```
option (ENABLE_XXX)
if (ENABLE_XXX)
    option (USE_INTERNAL_XXX)
    if (USE_INTERNAL_XXX)
        …
    else ()
        add_library (xxx UNKNOWN IMPORT)
        find_library(…) # use library names
        find_path(…) # find include dirs
        set_property(TARGET xxx PROPERTY IMPORTED_LOCATION …)

        # check that external library compiles
    endif ()
    target_compile_definitions (xxx PUBLIC USE_XXX=1)
else ()
    add_library (xxx INTERFACE)
    target_compile_definitions (xxx INTERFACE USE_XXX=0)
endif ()
```

It allows to always depend on required libraries and give the explicit and determenistic control for their enabling to user. It also removes unnecessary configuration, install and export steps that makes our own CMake files more complicated.

List of contribs to fix:

- [ ] abseil-cpp
- [x] arrow
- [x] avro
- [x] aws*
- [x] base64
- [x] boost
- [x] brotli
- [x] capnproto
- [x] cassandra
- [x] cctz
- [x] cppkafka
- [x] curl
- [x] double-conversion
- [x] fastops
- [ ] fastfloat
- [ ] flatbuffers
- [x] googletest
- [ ] grpc
- [x] gcem
- [x] h3
- [x] hyperscan
- [x] icu
- [x] jemalloc (special case)
- [x] libgsasl
- [x] libhdfs3
- [x] librdkafka
- [x] libunwind (special case)
- [x] libxml2
- [ ] llvm
- [x] lz4
- [x] mariadb-connector-c
- [x] openssl
- [x] orc
- [x] poco
- [x] protobuf
- [x] rapidjson
- [x] re2
- [x] ryu
- [x] sentry-native
- [x] simdjson
- [x] snappy
- [x] sparsehash-c11
- [x] thrift
- [x] unixodbc
- [x] xz
- [x] zlib-ng
- [x] zstd

And maybe some others that are not yet in contrib folder

**Comment by alexey-milovidov** [comment]
I have checked the marks for contribs with our own CMake.

**Comment by alexey-milovidov** [comment]
Continued here: #35630
