### ISSUE TITLE
Build stable branch error

### ISSUE THREAD

**Issue by templarzq** [ClickHouse/ClickHouse#9234]
Make sure that `git diff` result is empty and you've just pulled fresh master. Try cleaning up cmake cache. Just in case, official build instructions are published here: https://clickhouse.yandex/docs/en/development/build/

**Operating system**
OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.
centos7.2
**Cmake version**
3.16.4
**Ninja version**
1.10.0
**Compiler name and version**
gcc9.2

**Full cmake and/or ninja output**

cmake .. -DGLIBC_COMPATIBILITY=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
CMake Warning (dev) at CMakeLists.txt:1 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- IPO/LTO not enabled.
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Tests are enabled
-- Building for: Linux-3.10.0-327.el7.x86_64 x86_64  ; USE_STATIC_LIBRARIES=ON MAKE_STATIC_LIBRARIES=ON SPLIT_SHARED= UNBUNDLED=OFF CCACHE=CCACHE_FOUND-NOTFOUND
-- Using ssl=1: /home/ck/ck/stable/ClickHouse/contrib/ssl/include : ssl;crypto
-- Found the following ICU libraries:
--   i18n (required)
--   uc (required)
--   data (required)
-- Using icu=1: /usr/include : /usr/lib64/libicui18n.so;/usr/lib64/libicuuc.so;/usr/lib64/libicudata.so
-- Using Boost: /home/ck/ck/stable/ClickHouse/contrib/boost : boost_program_options_internal,boost_system_internal,boost_filesystem_internal;boost_system_internal,boost_regex_internal
-- Using zlib-ng: /home/ck/ck/stable/ClickHouse/contrib/zlib-ng;/home/ck/ck/stable/ClickHouse/build/contrib/zlib-ng : zlibstatic
-- Using zstd: /home/ck/ck/stable/ClickHouse/contrib/zstd/lib : zstd
-- Using termcap: /usr/lib64/libtermcap.so
-- Using odbc=1:  : unixodbc
-- Using Poco: /home/ck/ck/stable/ClickHouse/contrib/poco/Foundation/include/;/home/ck/ck/stable/ClickHouse/contrib/poco/Util/include/;/home/ck/ck/stable/ClickHouse/contrib/zlib-ng/;/home/ck/ck/stable/ClickHouse/build/contrib/zlib-ng/ : PocoFoundation,PocoUtil,PocoNet,PocoNetSSL;ssl;crypto,PocoCrypto;ssl;crypto,PocoXML,PocoData,PocoDataODBC;unixodbc,,,PocoMongoDB; MongoDB=1, DataODBC=1, NetSSL=1
-- Using lz4: /home/ck/ck/stable/ClickHouse/contrib/lz4/lib : lz4
-- Using xxhash=1: /home/ck/ck/stable/ClickHouse/contrib/lz4/lib : lz4
-- Using sparsehash: /home/ck/ck/stable/ClickHouse/contrib/libsparsehash
-- Using rt:
-- Using line editing libraries (readline): /usr/include : /usr/lib64/libreadline.so;/usr/lib64/libtermcap.so
-- Using re2: /home/ck/ck/stable/ClickHouse/contrib/re2 : re2;  : re2_st
-- Using librdkafka=1: /home/ck/ck/stable/ClickHouse/contrib/librdkafka/src : rdkafka cppkafka
-- Using capnp=1: /home/ck/ck/stable/ClickHouse/contrib/capnproto/c++/src : capnpc
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Using cpuid=1: /home/ck/ck/stable/ClickHouse/contrib/libcpuid/include : cpuid
-- Using libgsasl: /home/ck/ck/stable/ClickHouse/contrib/libgsasl/src;/home/ck/ck/stable/ClickHouse/contrib/libgsasl/linux_x86_64/include : libgsasl
-- Using libxml2: /home/ck/ck/stable/ClickHouse/contrib/libxml2/include;/home/ck/ck/stable/ClickHouse/contrib/libxml2-cmake/linux_x86_64/include : libxml2
-- Using brotli=1: /home/ck/ck/stable/ClickHouse/contrib/brotli/c/include : brotli
-- Using protobuf=1: /home/ck/ck/stable/ClickHouse/contrib/protobuf/src : libprotobuf
-- Using pdqsort: /home/ck/ck/stable/ClickHouse/contrib/pdqsort
-- Using hdfs3=1: /home/ck/ck/stable/ClickHouse/contrib/libhdfs3/include : hdfs3
-- Using consistent-hashing:  : consistent-hashing
-- Using hyperscan=1: /home/ck/ck/stable/ClickHouse/contrib/hyperscan/src : hs
-- Using cityhash:  : cityhash
-- Using farmhash:  : farmhash
-- Using metrohash: /home/ck/ck/stable/ClickHouse/contrib/libmetrohash/src : metrohash
-- Using btrie:  : btrie
-- Using double-conversion: /home/ck/ck/stable/ClickHouse/contrib/double-conversion : double-conversion
-- Using snappy=1: /home/ck/ck/stable/ClickHouse/contrib/snappy : snappy
-- Using Parquet: arrow_static: ; parquet_static: ; thrift_static
-- Using gtest=1: /home/ck/ck/stable/ClickHouse/contrib/googletest/googletest : gtest_main;gtest :
-- Using jemalloc=1: /home/ck/ck/stable/ClickHouse/contrib/jemalloc-cmake/include;/home/ck/ck/stable/ClickHouse/contrib/jemalloc-cmake/include_linux_x86_64 : jemalloc
-- Using cctz: /home/ck/ck/stable/ClickHouse/contrib/cctz/include : cctz
-- Using mysqlclient=1:  : mysqlclient; staticlib=
-- Using unwind=1: /home/ck/ck/stable/ClickHouse/contrib/libunwind/include : unwind
-- compiler C   = /data/zhangqiang/softwares/gcc-9.2.0/bin/gcc  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt -fno-omit-frame-pointer  -Wall  -no-pie -O2 -g -DNDEBUG -O3
-- compiler CXX = /data/zhangqiang/softwares/gcc-9.2.0/bin/g++  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -O2 -g -DNDEBUG -O3
-- LINKER_FLAGS =
-- ZSTD VERSION 1.3.17
-- Architecture: x86_64
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/deflate_quick.c;arch/x86/fill_window_sse.c;arch/x86/crc_folding.c;arch/x86/crc_pclmulqdq.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: RelWithDebInfo (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * SSE2, Use the SSE2 instruction set, using "-msse2"
 * SSE4_CRC, Support CRC hash generation using the SSE4.2 instruction set, using "-msse4"
 * SSE4DEFLATE, Support SSE4.2-accelerated quick decompression
 * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mpclmul"

-- The following OPTIONAL packages have been found:

 * Threads
 * ICU

-- The following OPTIONAL packages have not been found:

 * LLVM (required version >= 5)

-- Using OpenSSL from /home/ck/ck/stable/ClickHouse/contrib/ssl
-- Using odbc: /home/ck/ck/stable/ClickHouse/contrib/unixodbc/include : unixodbc
-- checking compiler: GCC (9.9.)
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- no
-- Build type RELWITHDEBINFO
-- Boost version: 1.69.0
-- Build date: 2000-01-01
-- gcc version 9.2.0
-- g++ version 9.2.0
-- generator is Ninja
-- Building without AVX512 support
-- Building for current host CPU:
-- Sphinx not found, unable to generate developer reference
-- Checking for module 'libpcre>=8.41'
--   Requested 'libpcre >= 8.41' but version of libpcre is 8.32
-- PCRE version 8.41 or above not found
-- PCRE 8.41 or above not found
-- Link jemalloc: jemalloc
-- /home/ck/ck/stable/ClickHouse/utils: Have 19039 megabytes of memory. Limiting concurrent linkers jobs to 5 and compiler jobs to OFF
-- /home/ck/ck/stable/ClickHouse/dbms: Have 19039 megabytes of memory. Limiting concurrent linkers jobs to 5 and compiler jobs to 7
-- Will build ClickHouse 19.5.3.1 revision 54417
-- Using internal=OFF compiler=0: headers=/usr/share/clickhouse/headers/19.5.3.1 :  /usr/local/bin/clickhouse-clang  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor  -Wextra -Werror -O2 -g -DNDEBUG -O3  -std=c++1z -x c++ -march=native -fPIC -fvisibility=hidden -fno-implement-inlines -nostdinc -nostdinc++ -Wno-unused-command-line-argument -Bprefix=/usr/share/clickhouse -isysroot=/usr/share/clickhouse/headers/19.5.3.1; clickhouse-lld
-- Target check already exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ck/ck/stable/ClickHouse/build

**Comment by templarzq** [comment]
[1297/4003] Building CXX object contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/concurrency/Util.cpp.o
FAILED: contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/concurrency/Util.cpp.o
/data/zhangqiang/softwares/gcc-9.2.0/bin/g++  -DARROW_WITH_LZ4 -DARROW_WITH_SNAPPY -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -D__STDC_FORMAT_MACROS -Icontrib/arrow-cmake -isystem ../contrib/thrift/lib/cpp/src -isystem ../contrib/boost -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -fno-omit-frame-pointer  -Wall  -Wnon-virtual-dtor -no-pie -Wno-old-style-cast -Wno-unused-function -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-result -Wno-deprecated-declarations -Wno-non-virtual-dtor -Wno-maybe-uninitialized -Wno-format -Wno-misleading-indentation -Wno-implicit-fallthrough -Wno-class-memaccess -Wno-sign-compare -std=c++1z -O2 -g -DNDEBUG -O3    -std=c++14 -MD -MT contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/concurrency/Util.cpp.o -MF contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/concurrency/Util.cpp.o.d -o contrib/arrow-cmake/CMakeFiles/thrift_static.dir/__/thrift/lib/cpp/src/thrift/concurrency/Util.cpp.o -c ../contrib/thrift/lib/cpp/src/thrift/concurrency/Util.cpp
In file included from ../contrib/thrift/lib/cpp/src/thrift/thrift-config.h:23,
                 from ../contrib/thrift/lib/cpp/src/thrift/concurrency/Util.cpp:20:
contrib/arrow-cmake/thrift/config.h:1:1: error: expected unqualified-id before ‘.’ token
    1 | ../../../thrift/build/cmake/config.h.in
      | ^
In file included from ../contrib/thrift/lib/cpp/src/thrift/thrift-config.h:23,
                 from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:25,
                 from ../contrib/thrift/lib/cpp/src/thrift/concurrency/Util.cpp:22:
contrib/arrow-cmake/thrift/config.h:1:1: error: expected unqualified-id before ‘.’ token
    1 | ../../../thrift/build/cmake/config.h.in
      | ^
In file included from ../contrib/thrift/lib/cpp/src/thrift/Thrift.h:30,
                 from ../contrib/thrift/lib/cpp/src/thrift/concurrency/Util.cpp:22:
/usr/include/sys/types.h:33:9: error: ‘__u_char’ does not name a type
   33 | typedef __u_char u_char;
      |         ^~~~~~~~

**Comment by templarzq** [comment]
operations:
 git clone clickhouse  on windows
then copy files to centos7

**Comment by alexey-milovidov** [comment]
`stable` branch is obsolete and no longer needed.
You should checkout the latest stable tag instead that looks like 

```
$ git tag --list | grep -F -- '-stable' | sort -rV | head
v20.1.4.14-stable
v20.1.3.7-stable
v20.1.2.4-stable
v19.17.9.60-stable
v19.17.8.54-stable
v19.17.7.52-stable
v19.17.6.36-stable
v19.17.5.18-stable
v19.17.4.11-stable
v19.17.3.7-stable
```

**Comment by filimonov** [comment]
1. stable branch is not supported currently (we removed it today). Use the `master` branch for development, or some particular tag to build a concrete version. 
2. windows filesystem doesn't support symlinks properly, and when you clone repo with symlinks, they are converted to text files containing the path of target file. So that does not work. Clone to linux directly.

**Comment by dmyers** [comment]
FYI the docs still say to use the `stable` branch:
https://clickhouse.tech/docs/en/development/build_osx/

**Comment by alexey-milovidov** [comment]
Changed, thank you!
