### ISSUE TITLE
oom when execute delete query

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9243]
version  : 20.1.4

delete SQL :  ALTER TABLE my_sdap.dm_user_behavior_events  DELETE WHERE event_dt>=20200215 and event_dt<=20200217 and dt=20200217 and event_id in(44) ; 

create SQL :    ReplicatedMergeTree('/clickhouse/tables/my_sdap/dm_user_behavior_events/{shard}', '{replica}') PARTITION BY event_dt ORDER BY (client_id, event_id, mode, dt, intHash64(user_id)) SAMPLE BY intHash64(user_id) TTL event_time + toIntervalDay(20), event_time + toIntervalDay(15) TO DISK 'cold' SETTINGS index_granularity = 8192, enable_mixed_granularity_parts = 1 

system error : 
Service_perfdata: rsyslog_count=4  2020-02-20 16:25:46 kern err  Out of memory: Kill process 2071 (clickhouse-serv) score 876 or sacrifice child
2020-02-20 16:25:46 kern err  Killed process 2071 (clickhouse-serv), UID 0, total-vm:82921384kB, anon-rss:59330736kB, file-rss:1036kB, shmem-rss:0kB
2020-02-20 16:27:47 kern err  Out of memory: Kill process 23170 (clickhouse-serv) score 864 or sacrifice child
2020-02-20 16:27:47 kern err  Killed process 23170 (clickhouse-serv), UID 0, total-vm:81180576kB, anon-rss:58504592kB, file-rss:940kB, shmem-rss:0kB

clickhouse  log :

**Comment by alesapin** [comment]
Maybe you can provide server logs after `ALTER` query begins? Also, it would be nice if you can provide data to reproduce the OOM. You can send it privately to our mailing lists clickhouse-feedback@yandex-team.ru.

**Comment by onine007** [comment]
It reproduced on MergeTree table   .

[delete_oom.log](https://github.com/ClickHouse/ClickHouse/files/4247570/delete_oom.log)
[restart_after_delete.log](https://github.com/ClickHouse/ClickHouse/files/4247571/restart_after_delete.log)

delete query:
 alter table   test.test_dm_user_behavior_events delete where event_dt=20200213 and dt=20200213 and event_id in (1,4);
DDL:
CREATE TABLE test.test_dm_user_behavior_events (`dt` UInt32, `user_id` UInt32, `event_time` DateTime CODEC(Delta(4), LZ4), `event_month` UInt32 MATERIALIZED toYYYYMM(event_time), `event_week_begin` UInt32 MATERIALIZED toYYYYMMDD(toMonday(event_time)), `event_dt` UInt32, `event_hh` UInt8 MATERIALIZED toHour(event_time), `event_mi` UInt8 MATERIALIZED CAST(formatDateTime(event_time, '%M'), 'UInt8'), `event_id` UInt32, `client_platform` UInt8, `client_id` UInt8, `client_ver` Nullable(String), `mode` UInt8, `is_married` Nullable(Int8), `tad` UInt16 CODEC(T64, LZ4), `active_days` UInt16, `is_first_day` UInt8 ALIAS IF(active_days = 0, 1, 0), `age` Nullable(Int8), `duration_phase` Nullable(Int8), `duration_phase_days` Nullable(Int8), `gestation_stage` Nullable(Int8), `gestation_weeks` Nullable(Int16), `baby_months` Nullable(Int16), `baby_weeks` Nullable(Int16), `pregnancy_months` Nullable(Int16), `channel` Nullable(String), `province` Nullable(Int32), `city` Nullable(Int32), `phone_manufacturer` Nullable(Int16), `phone_model_code` Nullable(Int32), `apn` Nullable(Int8), `opt` Nullable(Int8), `ab_exp_group` Array(String), `ab_isol` Array(String), `business_type_alias` Int8 ALIAS CAST(if(event_dt >= 20191127, business_type, multiIf(event_id IN (47, 46, 45, 44, 6, 48), multiIf(event_attr10 IN ('1', '4'), 1, event_attr10 IN ('2', '3', '5'), 2, event_attr10 IN ('6', '7'), 3, 0), event_id IN (100), multiIf(event_attr11 IN ('1', '4'), 1, event_attr11 IN ('2', '3', '5'), 2, event_attr11 IN ('6', '7'), 3, 0), event_id IN (32, 40, 73, 38, 41), multiIf(event_attr13 IN ('1', '4'), 1, event_attr13 IN ('2', '3', '5'), 2, event_attr13 IN ('6', '7'), 3, 0), event_id IN (31), multiIf(event_attr14 IN ('1', '4'), 1, event_attr14 IN ('2', '3', '5'), 2, event_attr14 IN ('6', '7'), 3, 0), event_id IN (60, 59, 52), multiIf(event_attr15 IN ('1', '4'), 1, event_attr15 IN ('2', '3', '5'), 2, event_attr15 IN ('6', '7'), 3, 0), event_id IN (68, 67, 71, 66, 70, 69), multiIf(event_attr16 IN ('1', '4'), 1, event_attr16 IN ('2', '3', '5'), 2, event_attr16 IN ('6', '7'), 3, 0), event_id IN (61, 20, 15, 19, 14, 18, 13, 17, 62, 16, 112, 113, 120), multiIf(event_attr17 IN ('1', '4'), 1, event_attr17 IN ('2', '3', '5'), 2, event_attr17 IN ('6', '7'), 3, 0), event_id IN (84, 85), multiIf(event_attr18 IN ('1', '4'), 1, event_attr18 IN ('2', '3', '5'), 2, event_attr18 IN ('6', '7'), 3, 0), event_id IN (30, 29, 28), multiIf(event_attr20 IN ('1', '4'), 1, event_attr20 IN ('2', '3', '5'), 2, event_attr20 IN ('6', '7'), 3, 0), event_id IN (4), multiIf(event_attr24 IN ('1', '4'), 1, event_attr24 IN ('2', '3', '5'), 2, event_attr24 IN ('6', '7'), 3, 0), event_id IN (24), multiIf(event_attr6 IN ('1', '4'), 1, event_attr6 IN ('2', '3', '5'), 2, event_attr6 IN ('6', '7'), 3, 0), event_id IN (23, 22, 34, 21, 33), multiIf(event_attr7 IN ('1', '4'), 1, event_attr7 IN ('2', '3', '5'), 2, event_attr7 IN ('6', '7'), 3, 0), 0)), 'Int8'), `info_type_alias` Int8 ALIAS CAST(if(event_dt >= 20191127, info_type, multiIf((event_id IN (7, 6)) AND (event_attr12 >= '0'), multiIf(event_attr12 IN ('0'), 1, event_attr12 IN ('10'), 2, event_attr12 IN ('4'), 4, event_attr12 IN ('2'), 8, event_attr12 IN ('14'), 9, event_attr12 IN ('15'), 10, event_attr12 IN ('1', '11'), 11, 0), (event_id IN (52)) AND (event_attr16 >= '0'), multiIf(event_attr16 IN ('0'), 1, event_attr16 IN ('10'), 2, event_attr16 IN ('4'), 4, event_attr16 IN ('2'), 8, event_attr16 IN ('14'), 9, event_attr16 IN ('15'), 10, event_attr16 IN ('1', '11'), 11, 0), (event_id IN (59, 60)) AND (event_attr19 >= '0'), multiIf(event_attr19 IN ('0'), 1, event_attr19 IN ('10'), 2, event_attr19 IN ('4'), 4, event_attr19 IN ('2'), 8, event_attr19 IN ('14'), 9, event_attr19 IN ('15'), 10, event_attr19 IN ('1', '11'), 11, 0), (event_id IN (28, 38, 66, 71, 32, 41, 68, 31, 70, 30, 40, 67, 73, 29, 69)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('0'), 1, event_attr2 IN ('10'), 2, event_attr2 IN ('4'), 4, event_attr2 IN ('2'), 8, event_attr2 IN ('14'), 9, event_attr2 IN ('15'), 10, event_attr2 IN ('1', '11'), 11, 0), (event_id IN (4)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('0'), 1, event_attr3 IN ('10'), 2, event_attr3 IN ('4'), 4, event_attr3 IN ('2'), 8, event_attr3 IN ('14'), 9, event_attr3 IN ('15'), 10, event_attr3 IN ('1', '11'), 11, 0), (event_id IN (48)) AND (event_attr8 >= '0'), multiIf(event_attr8 IN ('0'), 1, event_attr8 IN ('10'), 2, event_attr8 IN ('4'), 4, event_attr8 IN ('2'), 8, event_attr8 IN ('14'), 9, event_attr8 IN ('15'), 10, event_attr8 IN ('1', '11'), 11, 0), (event_id IN (41, 40, 38)) AND (event_attr1 >= '0'), multiIf(event_attr1 IN ('1', '2', '3'), 1, event_attr1 IN ('12'), 2, event_attr1 IN ('4', '5', '11'), 3, event_attr1 IN ('6'), 4, event_attr1 IN ('9', '10'), 5, event_attr1 IN ('8'), 6, event_attr1 IN ('14'), 7, 0), (event_id IN (59, 60)) AND (event_attr17 >= '0'), multiIf(event_attr17 IN ('1', '2', '3'), 1, event_attr17 IN ('12'), 2, event_attr17 IN ('4', '5', '11'), 3, event_attr17 IN ('6'), 4, event_attr17 IN ('9', '10'), 5, event_attr17 IN ('8'), 6, event_attr17 IN ('14'), 7, 0), (event_id IN (85, 84, 22, 21)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('1', '2', '3'), 1, event_attr2 IN ('12'), 2, event_attr2 IN ('4', '5', '11'), 3, event_attr2 IN ('6'), 4, event_attr2 IN ('9', '10'), 5, event_attr2 IN ('8'), 6, event_attr2 IN ('14'), 7, 0), (event_id IN (52, 4)) AND (event_attr26 >= '0'), multiIf(event_attr26 IN ('1', '2', '3'), 1, event_attr26 IN ('12'), 2, event_attr26 IN ('4', '5', '11'), 3, event_attr26 IN ('6'), 4, event_attr26 IN ('9', '10'), 5, event_attr26 IN ('8'), 6, event_attr26 IN ('14'), 7, 0), (event_id IN (68, 24, 67, 73, 69, 66)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('1', '2', '3'), 1, event_attr3 IN ('12'), 2, event_attr3 IN ('4', '5', '11'), 3, event_attr3 IN ('6'), 4, event_attr3 IN ('9', '10'), 5, event_attr3 IN ('8'), 6, event_attr3 IN ('14'), 7, 0), (event_id IN (23)) AND (event_attr4 >= '0'), multiIf(event_attr4 IN ('1', '2', '3'), 1, event_attr4 IN ('12'), 2, event_attr4 IN ('4', '5', '11'), 3, event_attr4 IN ('6'), 4, event_attr4 IN ('9', '10'), 5, event_attr4 IN ('8'), 6, event_attr4 IN ('14'), 7, 0), (event_id IN (14, 19, 62, 13, 18, 61, 17, 16, 15, 20, 112, 113, 120)) AND (event_attr6 >= '0'), multiIf(event_attr6 IN ('1', '2', '3'), 1, event_attr6 IN ('12'), 2, event_attr6 IN ('4', '5', '11'), 3, event_attr6 IN ('6'), 4, event_attr6 IN ('9', '10'), 5, event_attr6 IN ('8'), 6, event_attr6 IN ('14'), 7, 0), (event_id IN (48)) AND (event_attr9 >= '0'), multiIf(event_attr9 IN ('1', '2', '3'), 1, event_attr9 IN ('12'), 2, event_attr9 IN ('4', '5', '11'), 3, event_attr9 IN ('6'), 4, event_attr9 IN ('9', '10'), 5, event_attr9 IN ('8'), 6, event_attr9 IN ('14'), 7, 0), (event_id IN (71, 70)) AND (event_attr23 >= '0'), multiIf(event_attr23 IN ('1', '2', '3'), 1, event_attr23 IN ('4'), 3, 0), 0)), 'Int8'), `info_type` Int8 MATERIALIZED CAST(multiIf((event_id IN (7, 6)) AND (event_attr12 >= '0'), multiIf(event_attr12 IN ('0'), 1, event_attr12 IN ('10'), 2, event_attr12 IN ('4'), 4, event_attr12 IN ('2'), 8, event_attr12 IN ('14'), 9, event_attr12 IN ('15'), 10, event_attr12 IN ('1', '11'), 11, 0), (event_id IN (52)) AND (event_attr16 >= '0'), multiIf(event_attr16 IN ('0'), 1, event_attr16 IN ('10'), 2, event_attr16 IN ('4'), 4, event_attr16 IN ('2'), 8, event_attr16 IN ('14'), 9, event_attr16 IN ('15'), 10, event_attr16 IN ('1', '11'), 11, 0), (event_id IN (59, 60)) AND (event_attr19 >= '0'), multiIf(event_attr19 IN ('0'), 1, event_attr19 IN ('10'), 2, event_attr19 IN ('4'), 4, event_attr19 IN ('2'), 8, event_attr19 IN ('14'), 9, event_attr19 IN ('15'), 10, event_attr19 IN ('1', '11'), 11, 0), (event_id IN (28, 38, 66, 71, 32, 41, 68, 31, 70, 30, 40, 67, 73, 29, 69)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('0'), 1, event_attr2 IN ('10'), 2, event_attr2 IN ('4'), 4, event_attr2 IN ('2'), 8, event_attr2 IN ('14'), 9, event_attr2 IN ('15'), 10, event_attr2 IN ('1', '11'), 11, 0), (event_id IN (4)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('0'), 1, event_attr3 IN ('10'), 2, event_attr3 IN ('4'), 4, event_attr3 IN ('2'), 8, event_attr3 IN ('14'), 9, event_attr3 IN ('15'), 10, event_attr3 IN ('1', '11'), 11, 0), (event_id IN (48)) AND (event_attr8 >= '0'), multiIf(event_attr8 IN ('0'), 1, event_attr8 IN ('10'), 2, event_attr8 IN ('4'), 4, event_attr8 IN ('2'), 8, event_attr8 IN ('14'), 9, event_attr8 IN ('15'), 10, event_attr8 IN ('1', '11'), 11, 0), (event_id IN (41, 40, 38)) AND (event_attr1 >= '0'), multiIf(event_attr1 IN ('1', '2', '3'), 1, event_attr1 IN ('12'), 2, event_attr1 IN ('4', '5', '11'), 3, event_attr1 IN ('6'), 4, event_attr1 IN ('9', '10'), 5, event_attr1 IN ('8'), 6, event_attr1 IN ('14'), 7, 0), (event_id IN (59, 60)) AND (event_attr17 >= '0'), multiIf(event_attr17 IN ('1', '2', '3'), 1, event_attr17 IN ('12'), 2, event_attr17 IN ('4', '5', '11'), 3, event_attr17 IN ('6'), 4, event_attr17 IN ('9', '10'), 5, event_attr17 IN ('8'), 6, event_attr17 IN ('14'), 7, 0), (event_id IN (85, 84, 22, 21)) AND (event_attr2 >= '0'), multiIf(event_attr2 IN ('1', '2', '3'), 1, event_attr2 IN ('12'), 2, event_attr2 IN ('4', '5', '11'), 3, event_attr2 IN ('6'), 4, event_attr2 IN ('9', '10'), 5, event_attr2 IN ('8'), 6, event_attr2 IN ('14'), 7, 0), (event_id IN (52, 4)) AND (event_attr26 >= '0'), multiIf(event_attr26 IN ('1', '2', '3'), 1, event_attr26 IN ('12'), 2, event_attr26 IN ('4', '5', '11'), 3, event_attr26 IN ('6'), 4, event_attr26 IN ('9', '10'), 5, event_attr26 IN ('8'), 6, event_attr26 IN ('14'), 7, 0), (event_id IN (68, 24, 67, 73, 69, 66)) AND (event_attr3 >= '0'), multiIf(event_attr3 IN ('1', '2', '3'), 1, event_attr3 IN ('12'), 2, event_attr3 IN ('4', '5', '11'), 3, event_attr3 IN ('6'), 4, event_attr3 IN ('9', '10'), 5, event_attr3 IN ('8'), 6, event_attr3 IN ('14'), 7, 0), (event_id IN (23)) AND (event_attr4 >= '0'), multiIf(event_attr4 IN ('1', '2', '3'), 1, event_attr4 IN ('12'), 2, event_attr4 IN ('4', '5', '11'), 3, event_attr4 IN ('6'), 4, event_attr4 IN ('9', '10'), 5, event_attr4 IN ('8'), 6, event_attr4 IN ('14'), 7, 0), (event_id IN (14, 19, 62, 13, 18, 61, 17, 16, 15, 20, 112, 113, 120)) AND (event_attr6 >= '0'), multiIf(event_attr6 IN ('1', '2', '3'), 1, event_attr6 IN ('12'), 2, event_attr6 IN ('4', '5', '11'), 3, event_attr6 IN ('6'), 4, event_attr6 IN ('9', '10'), 5, event_attr6 IN ('8'), 6, event_attr6 IN ('14'), 7, 0), (event_id IN (48)) AND (event_attr9 >= '0'), multiIf(event_attr9 IN ('1', '2', '3'), 1, event_attr9 IN ('12'), 2, event_attr9 IN ('4', '5', '11'), 3, event_attr9 IN ('6'), 4, event_attr9 IN ('9', '10'), 5, event_attr9 IN ('8'), 6, event_attr9 IN ('14'), 7, 0), (event_id IN (71, 70)) AND (event_attr23 >= '0'), multiIf(event_attr23 IN ('1', '2', '3'), 1, event_attr23 IN ('4'), 3, 0), 0), 'Int8'), `business_type` Int8 MATERIALIZED CAST(multiIf(event_id IN (47, 46, 45, 44, 6, 48), multiIf(event_attr10 IN ('1', '4'), 1, event_attr10 IN ('2', '3', '5'), 2, event_attr10 IN ('6', '7'), 3, 0), event_id IN (100), multiIf(event_attr11 IN ('1', '4'), 1, event_attr11 IN ('2', '3', '5'), 2, event_attr11 IN ('6', '7'), 3, 0), event_id IN (32, 40, 73, 38, 41), multiIf(event_attr13 IN ('1', '4'), 1, event_attr13 IN ('2', '3', '5'), 2, event_attr13 IN ('6', '7'), 3, 0), event_id IN (31), multiIf(event_attr14 IN ('1', '4'), 1, event_attr14 IN ('2', '3', '5'), 2, event_attr14 IN ('6', '7'), 3, 0), event_id IN (60, 59, 52), multiIf(event_attr15 IN ('1', '4'), 1, event_attr15 IN ('2', '3', '5'), 2, event_attr15 IN ('6', '7'), 3, 0), event_id IN (68, 67, 71, 66, 70, 69), multiIf(event_attr16 IN ('1', '4'), 1, event_attr16 IN ('2', '3', '5'), 2, event_attr16 IN ('6', '7'), 3, 0), event_id IN (61, 20, 15, 19, 14, 18, 13, 17, 62, 16, 112, 113, 120), multiIf(event_attr17 IN ('1', '4'), 1, event_attr17 IN ('2', '3', '5'), 2, event_attr17 IN ('6', '7'), 3, 0), event_id IN (84, 85), multiIf(event_attr18 IN ('1', '4'), 1, event_attr18 IN ('2', '3', '5'), 2, event_attr18 IN ('6', '7'), 3, 0), event_id IN (30, 29, 28), multiIf(event_attr20 IN ('1', '4'), 1, event_attr20 IN ('2', '3', '5'), 2, event_attr20 IN ('6', '7'), 3, 0), event_id IN (4), multiIf(event_attr24 IN ('1', '4'), 1, event_attr24 IN ('2', '3', '5'), 2, event_attr24 IN ('6', '7'), 3, 0), event_id IN (24), multiIf(event_attr6 IN ('1', '4'), 1, event_attr6 IN ('2', '3', '5'), 2, event_attr6 IN ('6', '7'), 3, 0), event_id IN (23, 22, 34, 21, 33), multiIf(event_attr7 IN ('1', '4'), 1, event_attr7 IN ('2', '3', '5'), 2, event_attr7 IN ('6', '7'), 3, 0), 0), 'Int8'), `push46_day` Nullable(Int8) ALIAS CAST(if((event_id IN (44, 45, 46, 47, 48)) AND (event_attr1 = '46'), substring(splitByString('|', ifNull(toString(event_attr5), '0|0|0'))[3], 4, 2), NULL), 'Nullable(Int8)'), `push46_content` Nullable(Int8) ALIAS CAST(if((event_id IN (44, 45, 46, 47, 48)) AND (event_attr1 = '46'), substring(splitByString('|', ifNull(toString(event_attr5), '0|0|0'))[3], 2, 2), NULL), 'Nullable(Int8)'), `push46_stage` Nullable(Int8) ALIAS CAST(if((event_id IN (44, 45, 46, 47, 48)) AND (event_attr1 = '46'), substring(splitByString('|', ifNull(toString(event_attr5), '0|0|0'))[3], 1, 1), NULL), 'Nullable(Int8)'), `baby_age` Int8 ALIAS CAST(multiIf((baby_months >= 0) AND (baby_months <= 12), baby_months, (baby_months >= 13) AND (baby_months <= 24), 24, (baby_months >= 25) AND (baby_months <= 36), 36, (baby_months >= 37) AND (baby_months <= 48), 48, (baby_months >= 49) AND (baby_months <= 60), 60, (baby_months >= 61) AND (baby_months <= 72), 72, baby_months >= 73, 73, -1), 'Int8'), `age_sub` Int8 ALIAS CAST(multiIf((age > 0) AND (age <= 14), 1, age IN (15, 16, 17, 18), 2, age IN (19, 20, 21, 22), 3, age IN (23, 24, 25, 26, 27, 28, 29, 30), 4, age IN (31, 32, 33, 34, 35), 5, age IN (36, 37, 38, 39, 40), 6, age > 40, 7, -1), 'Int8'), `position` Nullable(Int8) ALIAS CAST(multiIf((event_id IN (28, 29)) AND (event_attr8 = '1') AND (event_attr9 = '1'), 1, (event_id IN (28, 29)) AND (event_attr8 = '5') AND (event_attr9 IN ('1', '4')), 2, (event_id IN (28, 29)) AND (event_attr8 = '2') AND (event_attr9 IN ('1', '96')), 3, (event_id IN (28, 29)) AND (event_attr9 = '75'), 4, (event_id IN (28, 29)) AND (event_attr9 = '7'), 5, 0, 6, 0, 7, (event_id IN (28, 29)) AND (event_attr9 IN ('44', '102')), 8, (event_id IN (28, 29)) AND (event_attr9 = '16'), 9, 0, 10, 0, 11, 0, 12, (event_id IN (28, 29)) AND (event_attr9 = '78'), 13, (event_id IN (28, 29)) AND (event_attr9 = '79'), 14, (event_id IN (28, 29)) AND (event_attr9 = '80'), 15, ((event_id IN (28, 29)) AND (event_attr8 = '6') AND (event_attr9 = '1')) OR ((event_id IN (28, 29)) AND (event_attr9 = '81')), 16, 0, 17, 0, 18, 0, 19, 0, 20, (event_id IN (28, 29)) AND (event_attr9 = '83'), 21, (event_id IN (28, 29)) AND (event_attr9 = '88'), 22, (event_id IN (28, 29)) AND (event_attr9 IN ('90', '101')), 23, (event_id IN (28, 29)) AND (event_attr9 = '91'), 24, 0, 25, (event_id IN (28, 29)) AND (event_attr10 = '1'), 26, (event_id IN (28, 29)) AND (event_attr10 = '2'), 27, (event_id IN (28, 29)) AND (event_attr10 = '3'), 28, (event_id IN (28, 29)) AND (event_attr10 = '5'), 29, 0, 30, 0, 31, (event_id IN (28, 29)) AND (event_attr9 = '114'), 32, NULL), 'Nullable(Int8)'), `event_attr1` Nullable(String), `event_attr2` Nullable(String), `event_attr3` Nullable(String), `event_attr4` Nullable(String), `event_attr5` Nullable(String), `event_attr6` Nullable(String), `event_attr7` Nullable(String), `event_attr8` Nullable(String), `event_attr9` Nullable(String), `event_attr10` Nullable(String), `event_attr11` Nullable(String), `event_attr12` Nullable(String), `event_attr13` Nullable(String), `event_attr14` Nullable(String), `event_attr15` Nullable(String), `event_attr16` Nullable(String), `event_attr17` Nullable(String), `event_attr18` Nullable(String), `event_attr19` Nullable(String), `event_attr20` Nullable(String), `event_attr21` Nullable(String), `event_attr22` Nullable(String), `event_attr23` Nullable(String), `event_attr24` Nullable(String), `event_attr25` Nullable(String), `event_attr26` Nullable(String), `event_attr27` Nullable(String), `event_attr28` Nullable(String), `event_attr29` Nullable(String), `event_attr30` Nullable(String), `event_attr31` Nullable(String), `event_attr32` Nullable(String), `event_attr33` Nullable(String), `event_attr34` Nullable(String), `event_attr35` Nullable(String), `event_attr36` Nullable(String), `event_attr37` Nullable(String), `event_attr38` Nullable(String), `event_attr39` Nullable(String), `event_attr40` Nullable(String), `event_attr41` Nullable(String), `event_attr42` Nullable(String), `event_attr43` Nullable(String), `event_attr44` Nullable(String), `event_attr45` Nullable(String), `event_attr46` Nullable(String), `event_attr47` Nullable(String), `event_attr48` Array(String), `event_attr49` Array(String), `event_attr50` Array(String)) ENGINE = MergeTree() PARTITION BY event_dt ORDER BY (client_id, event_id, mode, dt, intHash64(user_id)) SAMPLE BY intHash64(user_id) TTL event_time + toIntervalDay(200) SETTINGS index_granularity = 8192, enable_mixed_granularity_parts = 1 ;

**Comment by onine007** [comment]
If  delete  query  affect  no rows  then will not OOM .

**Comment by filimonov** [comment]
Most probably it's the same as #9850 #9873
Please update.
