### ISSUE TITLE
Memory is not returned when ENGINE=Memory table is dropped

### ISSUE THREAD

**Issue by Akazz** [ClickHouse/ClickHouse#9248]
**Describe the bug or unexpected behaviour**
Memory is not returned when a table with ENGINE=Memory is dropped!

**How to reproduce**
* ClickHouse server version 20.+
* Running the following snippet will waste around 4Gb of RAM
```(sql)
CREATE DATABASE IF NOT EXISTS test_memory_leak
CREATE TABLE test_memory_leak.table1 (x1 UInt8) ENGINE = Memory
INSERT INTO test_memory_leak.table1 SELECT materialize(0) AS x1 FROM numbers(4000000000)

SELECT 1

TRUNCATE TABLE test_memory_leak.table1
DROP TABLE test_memory_leak.table1
DROP DATABASE test_memory_leak
```
* Running it in a loop eventually gets ClickHouse server OOMed

**Comment by Akazz** [comment]
Also it should be noted that the destructor `~StorageMemory()` gets called consistently.

**Comment by alexey-milovidov** [comment]
I have tested with data size 100000000 in a loop with 1000 iterations and cannot confirm the leak.

**Comment by alexey-milovidov** [comment]
It looks like wasted if I test with data size 4000000000 as in your example. Need to investigate...

**Comment by alexey-milovidov** [comment]
Everything looks perfect so far.

But there are some inefficiencies:

1. The INSERT SELECT query has squashing of blocks: SELECT produces blocks of 65536 rows and they are squashed to 1048576 rows before INSERT. This can be avoided and PR #12195 will address this.

2. IO buffers of 1 MiB are allocated and freed for every query - why don't make them adaptive.

3. PaddedPODArray adds padding and rounds up to power of two. For example, we need a column with 1048576 values of type UInt8. It adds 16 bytes before and 15 bytes after and it becomes 1048607 bytes, then it's rounded up to power of two that becomes 2097152 bytes. This will lead to excessive memory requirement for Memory tables.

**Comment by alexey-milovidov** [comment]
(1) and (3) have been fixed.
