### ISSUE TITLE
Propagate error messages for DDL queries

### ISSUE THREAD

**Issue by abyss7** [ClickHouse/ClickHouse#9259]
When we run DDL queries on cluster it will be very helpful to see original error message from the failed node:

> DDLWorker: Query ALTER TABLE …  wasn't finished successfully: Code: 36, e.displayText() =
> DB::Exception: You must set the setting `allow_experimental_data_skipping_indices` to 1 before using data skipping indices.

Instead of:

> Cannot execute replicated DDL query on leader

**Comment by veqryn** [comment]
I was about to make a new issue for this exact problem.
I spent hours trying to debug something that was just a typo in a query, and I had I had seen the original error message just telling me it was a simple typo.

**Comment by tavplubix** [comment]
Fixed in #13450
