### ISSUE TITLE
Want to get query result with max_result_rows, just as limit

### ISSUE THREAD

**Issue by 42997455** [ClickHouse/ClickHouse#9271]
If I set the max_result_rows for clickhouse, then run a query which result is more than the max_result_rows setting, then the query will be cancelled(Exception will happen) by clickhouse.
I want to know if there is a way to get the limit result, and know the result is limited? thanks!

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/operations/settings/query_complexity/#result-overflow-mode

_What to do if the volume of the result exceeds one of the limits: 'throw' or 'break'. By default, throw. Using 'break' is similar to using LIMIT._

but it could be broken.

**Comment by 42997455** [comment]
Thanks a lot!

**Comment by 42997455** [comment]
Hi @den-crane , I test the result-overflow-mode with 'break', found it really will not throw exception for a query which result should be more than my max_result_rows setting(10 rows), but I found it will return all the result rows(4955 rows), it is not what I expected, I think it should be like limit 10, and return 10 rows.

My Clickhouse version: ClickHouse client version 19.14.7.15 (official build).

Do you think is it a bug for this version clickhouse or the result-overflow-mode is not like limit? Thanks!

**Comment by filimonov** [comment]
May relate to https://github.com/ClickHouse/ClickHouse/issues/8505

**Comment by den-crane** [comment]
it breaks on blocks and should be used along with limit.

```
18.14.19

create table testMRR(A Int64) Engine=MergeTree Order by tuple();
insert into testMRR select number from numbers(100000);
set max_threads=1, max_result_rows = 333, result_overflow_mode='break', max_block_size=3333;

select * from testMRR format Null
3333 rows in set.

20.2.1.2362

set max_threads=1, max_result_rows = 333, result_overflow_mode='break', max_block_size=3333;
select * from numbers(100000);
3333 rows in set
```

**Comment by den-crane** [comment]
`Break` interrupts execution only at the block level. This means that amount of returned rows is greater than [max_result_rows](#setting-max_result_rows), multiple of [max_block_size](settings.md#setting-max_block_size) and depends on [max_threads](settings.md#settings-max_threads).
