### ISSUE TITLE
Timeout exceeded when select from system.mutations

### ISSUE THREAD

**Issue by Tri0L** [ClickHouse/ClickHouse#9276]
OS Version: `Ubuntu 16.04` 
CH Version:  `20.1.2.4 (official build)`

Query:
```
select now(), sum(parts_to_do) from system.mutations where is_done = 0;

SELECT 
    now(), 
    sum(parts_to_do)
FROM system.mutations
WHERE is_done = 0

Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
```

**Comment by Tri0L** [comment]
```
:) KILL MUTATION WHERE database = 'db' AND table = 'table';

KILL MUTATION WHERE (database = 'db') AND (table = 'table') ASYNC

Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.

```

**Comment by filimonov** [comment]
1) Are you able to create reproducible example? 
2) If the problem will happen again - please run the following command from console:
```
apt-get install clickhouse-common-static-dbg=$(clickhouse-client --version-clean)
for i in $(ls -1 /proc/$(pidof clickhouse-server)/task/); do kill -TSTP $i; done
```

And attach here the line will will be added at the end of /var/log/clickhouse-server/clickhouse-server.err.log

**Comment by Tri0L** [comment]
Logs during query `select now(), sum(parts_to_do) from system.mutations;`
https://pastebin.com/8dqQ5Y1N

Query results:
```
:) select now(), sum(parts_to_do) from system.mutations;

SELECT 
    now(), 
    sum(parts_to_do)
FROM system.mutations

Timeout exceeded while receiving data from server. Waited for 300 seconds, timeout is 300 seconds.
Cancelling query.
```

**Comment by filimonov** [comment]
The code around mutations was significantly refactored in 20.3. Please update to 20.3 or newer

**Comment by dzt-studio** [comment]
![image](https://user-images.githubusercontent.com/84053867/132487321-7750a083-dd20-4bd1-ba17-345be2d79669.png)
the same question!!!
How to solve？
version : 21.1.2.15
