### ISSUE TITLE
Supporting date functions for dates before 1970 for birth dates, ....

### ISSUE THREAD

**Issue by yehiaelbehery** [ClickHouse/ClickHouse#9277]
Do you plan to support date functions for dates before 1970 for birth dates, ... and other historic dates. Can you explain the philosohy behind the decision (if not time and resources)?
And shouldn't it throw an exception if the date is lower than 1970 instead of returning an incorrect convertion result?
Thank you.

**Comment by alexey-milovidov** [comment]
We plan to support them via separate data types: Date32, DateTime64.

**Comment by den-crane** [comment]
duplicate https://github.com/ClickHouse/ClickHouse/issues/7316
