### ISSUE TITLE
Ubuntu 19.10 and ClickHouse 20.1+ clickhouse-client login server error

### ISSUE THREAD

**Issue by snowzjy** [ClickHouse/ClickHouse#9303]
(you don't have to strictly follow this form)

**Describe the bug or unexpected behaviour**
Ubuntu 19.10 and ClickHouse 20.1+ clickhouse-client login server error 

**How to reproduce**
install ClickHouse 20.1+ in Ubuntu 19.10 by .deb package
start server
use clickhouse-client to login server
* Which ClickHouse server version to use
20.1.4.14 or 20.2.4.14
* Which interface to use, if matters
clickhouse-client
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/dbms/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**
Nomally connect to server

**Error message and/or stacktrace**
╰─$ clickhouse-client -u default  --ask-password                                                                                                                         
Code: 27, e.displayText() = DB::Exception: Cannot parse input: expected eof before: G, Stack trace (when copying this message, always include the lines below):

0. 0xbc34d6c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) /build/obj-x86_64-linux-gnu/../contrib/poco/Foundation/src/Exception.cpp:27 in /usr/lib/debug/usr/bin/clickhouse
1. 0x4f6e129 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) /build/obj-x86_64-linux-gnu/../dbms/src/Common/Exception.cpp:35 in /usr/lib/debug/usr/bin/clickhouse
2. 0x496cadd DB::throwAtAssertionFailed(char const*, DB::ReadBuffer&) (.cold) /build/obj-x86_64-linux-gnu/../dbms/src/IO/ReadHelpers.cpp:84 in /usr/lib/debug/usr/bin/clickhouse
3. 0x4f8db9b DB::assertEOF(DB::ReadBuffer&) /build/obj-x86_64-linux-gnu/../dbms/src/IO/ReadHelpers.cpp:127 in /usr/lib/debug/usr/bin/clickhouse
4. 0x8a4e450 DB::SettingNumber<unsigned long>::set(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /build/obj-x86_64-linux-gnu/../dbms/src/Core/SettingsCollection.cpp:65 in /usr/lib/debug/usr/bin/clickhouse
5. 0x504e054 DB::Client::initialize(Poco::Util::Application&) /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/string:2133 in /usr/lib/debug/usr/bin/clickhouse
6. 0x9d3b875 Poco::Util::Application::run() /build/obj-x86_64-linux-gnu/../contrib/poco/Util/src/Application.cpp:335 in /usr/lib/debug/usr/bin/clickhouse
7. 0x501f3a9 mainEntryClickHouseClient(int, char**) /build/obj-x86_64-linux-gnu/../dbms/programs/client/Client.cpp:2028 in /usr/lib/debug/usr/bin/clickhouse
8. 0x4eb08f9 main /build/obj-x86_64-linux-gnu/../contrib/libcxx/include/vector:461 in /usr/lib/debug/usr/bin/clickhouse
9. 0x271e3 __libc_start_main /build/glibc-4WA41p/glibc-2.30/csu/../csu/libc-start.c:342 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.30.so
10. 0x4f13eba _start  in /usr/lib/debug/usr/bin/clickhouse
 (version 20.1.4.14 (official build))

**Additional context**

**Comment by filimonov** [comment]
Can't reproduce on 20.2.1.2369 

Can you check the contents of /etc/clickhouse-client/config.xml 
?

**Comment by snowzjy** [comment]
> Can't reproduce on 20.2.1.2369
> 
> Can you check the contents of /etc/clickhouse-client/config.xml
> ?

`

<config>
    <openSSL>
        <client> 
	<caConfig>/usr/local/share/ca-certificates/</caConfig>		
	<extendedVerification>false</extendedVerification>
	<loadDefaultCAFile>true</loadDefaultCAFile>
            <cacheSessions>true</cacheSessions>
            <disableProtocols>sslv2,sslv3</disableProtocols>
            <preferServerCiphers>true</preferServerCiphers>
            
            <invalidCertificateHandler>
                
                <name>RejectCertificateHandler</name>
            </invalidCertificateHandler>
        </client>
    </openSSL>
    
    <prompt_by_server_display_name>
        <default>{display_name} :) </default>
        <test>{display_name} \x01\e[1;32m\x02:)\x01\e[0m\x02 </test> 
        <production>{display_name} \x01\e[1;31m\x02:)\x01\e[0m\x02 </production> 
    </prompt_by_server_display_name>
</config>

`

**Comment by filimonov** [comment]
config look like default. Maybe you pass some more command line parameters?
