### ISSUE TITLE
DATETIME Datatype Issues near begining of unix epoch

### ISSUE THREAD

**Issue by chhaya-sharma** [ClickHouse/ClickHouse#9335]
Hi Team.
I am trying to insert a row in a table with datetime type column.
```
CREATE TABLE test.table1 (
`pc` String,
 `pf` String,
 `gi` UInt32,
 `gu` UInt32,
 `d0` Nullable(DateTime),
 timestamp DateTime
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/{cluster}/tables/{shard}/test-table1', '{replica}') PARTITION BY toYYYYMM(timestamp) ORDER BY (pc, pf, gi, gu) SETTINGS index_granularity = 8192; 

insert into test.table1(pc, pf, gi, gu, d0) Values('test','java',12,0,'1970-01-01 05:50:34');
insert into test.table1(pc, pf, gi, gu, d0) Values('test','java',11,0,toUnixTimestamp('1970-01-01 05:50:34'));
```
These insert queries gets save successfully, but when we fetch the result from clickhouse the data is not correct;
![clickhouse](https://user-images.githubusercontent.com/15169061/75136827-e23b1100-570b-11ea-8ab4-2225c7fe26b4.png)

DateTime column Data stored in clickhouse gets corrupted.
Please assist here.

**Comment by filimonov** [comment]
DateTime type does not support properly the dates close to beginning of the epoch. Dates after 1970-01-02 should work properly.

DateTime64 - will have that support (work in progress).

For now, the best workaround is to store such dates as numbers of as strings, and do conversions outside of clickhouse.

**Comment by den-crane** [comment]
It works in UTC

SELECT *
FROM table1
```

┌─pc───┬─pf───┬─gi─┬─gu─┬──────────────────d0─┬───────────timestamp─┐
│ test │ java │ 12 │  0 │ 1970-01-01 05:50:34 │ 0000-00-00 00:00:00 │
└──────┴──────┴────┴────┴─────────────────────┴─────────────────────┘
┌─pc───┬─pf───┬─gi─┬─gu─┬──────────────────d0─┬───────────timestamp─┐
│ test │ java │ 11 │  0 │ 1970-01-01 05:50:34 │ 0000-00-00 00:00:00 │
└──────┴──────┴────┴────┴─────────────────────┴─────────────────────┘
```

If you use Japan Standard Time  GMT+9, then this issue expected. CH does not support timestamps before UTC 0

**Comment by chhaya-sharma** [comment]
@den-crane It doesn't work for me in UTC.
As the table was created without providing any zone value, so the default value of datetime would be UTC based. And as you saw in my previous comment, it returned corrupted values on retrieval.

**Comment by alexey-milovidov** [comment]
I can reproduce the issue with the following queries:
```
SELECT toDateTime('1970-01-01 05:50:34', 'Asia/Calcutta');
SELECT toDateTime(toUnixTimestamp('1970-01-01 05:50:34'), 'Asia/Calcutta');
```
