### ISSUE TITLE
Kafka headers

### ISSUE THREAD

**Issue by MikeZaharov** [ClickHouse/ClickHouse#9337]
Hi! We intend to use the Kafka Engine (https://clickhouse.tech/docs/ru/operations/table_engines/kafka/) for storing events in Clickhouse.
Also, some of the necessary information is stored in the Kafka's headers (https://issues.apache.org/jira/browse/KAFKA-4208) and we would like to store them too.
Is there a way to achive this ?

**Comment by filimonov** [comment]
Right now it's not supported.

We can add support for that in future version in pair of virtual columns like
```
_header_names Array(String),
_header_values Array(String)
```
Would such a solution satisfy your needs?

**Comment by nickshatilo** [comment]
@filimonov We are willing to have this feature too. Would be very helpful.

**Comment by admsev** [comment]
Would it be also possible to make it like 
```
_header_value(String)
```
where String  is the name of header?

**Comment by MikeZaharov** [comment]
It's ok for us to use 2 arrays if this approach guarantees the order. 
I mean we'll be able to get header's value somehow like this: 
`arrayElement(header_values, indexOf(header_names, 'header_name')) as header_name`

**Comment by admsev** [comment]
@filimonov It would be great to have it indeed, thanks a lot!
