### ISSUE TITLE
Confusion about implementation of runningDifference

### ISSUE THREAD

**Issue by leiysky** [ClickHouse/ClickHouse#9340]
https://github.com/ClickHouse/ClickHouse/blob/21270b587e0688bb91e2b90cee7009641fc821f1/dbms/src/Functions/runningDifference.h#L58

What's the difference between `prev` and  `src[i-1]`? Since the last one seems to be more natural.

Is there any concern about performance?

**Comment by filimonov** [comment]
Please consider the case when `i=0`.

**Comment by leiysky** [comment]
@filimonov Adding an if to deal with it is fine.
I'm just curious about whether there is any concern about optimization or not, since there are many magic codes in this project to do so.
