### ISSUE TITLE
Forward and backward filling

### ISSUE THREAD

**Issue by feribg** [ClickHouse/ClickHouse#9349]
Does clickhouse support forward and backward fill queries either at query time or as an update?  (similar to pandas ffill). For time series it would be very useful to get the last valid entry for the column in a given range and propagate it forward.

**Comment by blinkov** [comment]
@feribg, is this question still relevant?

**Comment by ivishnevs** [comment]
Sounds good for me too

**Comment by alexey-milovidov** [comment]
Yes, ClickHouse supports WITH FILL modifier to ORDER BY.
https://clickhouse.tech/docs/en/sql-reference/statements/select/order-by/#orderby-with-fill

**Comment by freelectron** [comment]
With Filll is not really for forward/backword filling but for interpolation. You can use try to use anyLastIf (with OVER PARTITION)
