### ISSUE TITLE
Why is Clickhouse so fast?

### ISSUE THREAD

**Issue by BernieJiangDL** [ClickHouse/ClickHouse#9350]
We all know that clickhouse is much much faster than other OLAP engines or other DBMS. But Could someone briefly summarize why it is faster  and has better performance than others from  a technique view? Are there some advantages that the other don't have, like druid or kylin? Thanks~

**Comment by BernieJiangDL** [comment]
For example, clickhouse can scan faster than others. but why?

**Comment by ivanikonomov** [comment]
This should be nice start https://www.youtube.com/watch?v=ZOZQCQEtrz8
