### ISSUE TITLE
Not support index as column name

### ISSUE THREAD

**Issue by XLPE** [ClickHouse/ClickHouse#9352]
When create table,I can't use 'index' as column name.Such exception occur in V19 and above

sql:
CREATE TABLE test (**index** Int32) ENGINE = Memory;

**Comment by alexey-milovidov** [comment]
You can use `index` as a column name if you quote it as identifier (in double quotes or backticks)

```
CREATE TABLE test (`index` Int32) ENGINE = Memory;
```

```
CREATE TABLE test ("index" Int32) ENGINE = Memory;
```

**Comment by alexey-milovidov** [comment]
And we already have a test for it: `00933_reserved_word.sql`

**Comment by alexey-milovidov** [comment]
Inability to write `index` without quotes is expected, because it's the part of index definition syntax.
