### ISSUE TITLE
MergeTree auto-increment primary key

### ISSUE THREAD

**Issue by jangorecki** [ClickHouse/ClickHouse#9361]
I have a csv file that I am using as source data for different data processing tools, ClickHouse is one of those tools.
In all other tools I can easily import this data as-is. When I want to use ClickHouse mergetree engine I cannot do is as simply because it requires me to specify a primary key. None of the fields existing in the source data should be considered to be primary key, as a result I have manually pre-process the data by adding new, auto incremented, column `id0`. I used following command for that.
```sh
awk -F',' -v OFS=',' 'NR == 1 {print "id0", $0; next} {print (NR-1), $0}' data.csv > data2.csv
```
Then I can load this new data2.csv and use newly created column as a primary key.
```sql
CREATE TABLE mytable (id0 Int32, ...) ENGINE = MergeTree() ORDER BY (id0)
```
```sh
clickhouse-client --query="INSERT INTO mytable FORMAT CSVWithNames" < "data2.csv"
```

----

My feature request is about easing this process, and giving option to handle that internally within ClickHouse. So that I can `CREATE TABLE` and specify `id0 Int32 auto-increment` so it will be loaded from ClickHouse sequence rather than from the source file during INSERT process.

My workaround does work but I am not much satisfied with it. I have multiple different datasets, multiple of them are 50GB csv files. Thus having to duplicate and pre-process each csv just for ClickHouse is inconvenient and error prone. If ClickHouse would add this kind of auto-increment feature that would make this process much easier. Note that most of other databases have auto increment feature.

**Comment by filimonov** [comment]
>  When I want to use ClickHouse mergetree engine I cannot do is as simply because it requires me to specify a primary key. 

you can use `ORDER BY tuple()`

**Comment by den-crane** [comment]
CH does not require uniq primary key.
ORDER BY (id0) -- the worst idea as it can be -- **NEVER NEVER DO IT.**  

https://clickhouse.tech/docs/en/operations/table_engines/mergetree/#selecting-the-primary-key

You don't need autoincrement, you don't need  (id0) 
Choose some of your columns to sort the table to achieve better compression by putting similar columns values closer.

**Comment by jangorecki** [comment]
@filimonov 

> 1. you can use ORDER BY tuple()

what does it do?

@den-crane

> ORDER BY (id0) -- the worst idea as it can be -- NEVER EVER DO THAT.

why?

> Choose some of your columns to sort the table to achieve better compression by putting similar columns' values closer.

I don't want to sort the data, I actually want data to be sorted as in the original source csv file.

**Comment by den-crane** [comment]
>>ORDER BY tuple()
>what does it do?

A table will be without any order key.  (Order by 1).

>>ORDER BY (id0) -- the worst idea as it can be -- NEVER EVER DO THAT.
>why?

Because the idea behind OLAP columnar db is to place a big data into some sort order which allows to compress data better and the same time use this orderness for filtering.

**Comment by jangorecki** [comment]
> A table will be without any order key. (Order by 1).

By not having any order, you mean that its retain the order of the original data during insert, or data are inserted in random order?

> > > ORDER BY (id0) -- the worst idea as it can be -- NEVER EVER DO THAT.
> > > why?
> 
> Because the idea behind OLAP columnar db is to place a big data into some sort order which allows to compress data better and the same time use this orderness for filtering.

I understand the concept, and also do run my benchmark against sorted data. Goal is to have complete coverage of performance measures, both for sorted and unsorted data as well. I think "never" does not apply here then.

**Comment by filimonov** [comment]
You can try smth like.
```
insert_order DEFAULT bitOr(bitShiftLeft(toUInt64(now64()),24), rowNumberInAllBlocks()) 
```

**Comment by jangorecki** [comment]
@filimonov what does it mean?

**Comment by jangorecki** [comment]
@filimonov would you mind claryfing what is the behavior of that?

**Comment by filimonov** [comment]
> By not having any order, you mean that it retains the order of the original data during insert, or data are inserted in random order? 

No guarantees are provided here.

> @filimonov what does it mean?

It's just timestamp multiplied by 2^24 + rownumber in insert block, but using bit operations which are more efficient.

It's similar to:
```
DEFAULT toUnixTimestamp(now64())*16777216 + rowNumberInAllBlocks()
```
If you don't do more than a single insert (with up to 16 mln rows inside) it will give you incrementing sequence (but obviously with 'holes' inside). 

For more frequent inserts you can use smth like 
```
DEFAULT toUnixTimestamp64Milli(now64())*1000000 + rowNumberInAllBlocks()
```

It's NOT the same as autoincrement. But can be used to preserve insert order (while for now, i don't see any practical use cases for that).

**Comment by kokizzu** [comment]
what does `rowNumberInAllBlocks()` do?
I tried query it on the terminal, it shows 0 to 9999 '__')
