### ISSUE TITLE
The unexpected value of alias of the alias which redefines column name

### ISSUE THREAD

**Issue by sergekzhr** [ClickHouse/ClickHouse#9369]
Alias of redefined column name redefines itself once more time

**How to reproduce**
Version 19.9.4.34
```
SELECT number * 2 AS number,
       number,
       number     AS number_alias
FROM (SELECT 1000 AS number);
```

number | number | number_alias
-- | -- | --
2000 | 2000 | _4000_

**Expected behavior**
The value of a column alias equals the value of the column
number_alias = number

**Comment by den-crane** [comment]
That is how CH column aliases works. Expected behavior.

You can use table aliases
```

SELECT
    number * 2 AS number,
    x.number,
    x.number AS number_alias
FROM
(
    SELECT 1000 AS number
) AS x

┌─number─┬─x.number─┬─number_alias─┐
│   2000 │     1000 │         1000 │
└────────┴──────────┴──────────────┘
```

**Comment by blinkov** [comment]
@sergekzhr, do you have any further questions?
