### ISSUE TITLE
Allow configurable NULL representation for TSV

### ISSUE THREAD

**Issue by jason-godden** [ClickHouse/ClickHouse#9375]
When using TSVWithNamesAndTypes or other TSV variants \N is used to represent NULL and \ is used to escape the expected characters in a string sequence. For tools such as pandas, the read_csv method allows you to specify the escape sequence to parse escaped strings correctly however this results in the escaped \ being stripped from the NULL representation.

Can the NULL representation be made configurable?

**Comment by alexey-milovidov** [comment]
Yes, it will be very easy to add support for custom substitution for NULL.

**Comment by alexey-milovidov** [comment]
@jason-godden
Congrats, @Avogar has implemented this feature!

**Comment by jason-godden** [comment]
@Avogar - thanks so much!

Thanks @alexey-milovidov!
