### ISSUE TITLE
Folder start with delete_tmp_  in table data folder 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9402]
version : 21.1.4
![微信截图_20200227112904](https://user-images.githubusercontent.com/24770345/75409826-bc547d00-5954-11ea-83ff-0b9c5f976c2a.png)
The delete_tmp_   folder is created at  Sep 15  ;
Is it restart clickhouse-server when executing delete query ?
How can i deal with it ?

**Comment by blinkov** [comment]
@onine007, is this question still relevant?

**Comment by alexey-milovidov** [comment]
Simply ignore or delete it manually.

**Comment by alexey-milovidov** [comment]
Yes, it is left from unfinished delete. This folder is not used by the server anymore.
