### ISSUE TITLE
How to use "max_concurrent_queries_for_user"?

### ISSUE THREAD

**Issue by 42997455** [ClickHouse/ClickHouse#9405]
**Use case:**
I want to control concurrent queries by user.
For example, I have two users A and B, I want to control user A max concurrent queries as 10, and control user B max concurrent queries as 20. Do you know how to apply this setting in config.xml or user.xml?

I found there is a setting "max_concurrent_queries_for_user", I have tried to set the setting in config.xml as:
`<max_concurrent_queries>100</max_concurrent_queries>
 <max_concurrent_queries_for_user>1</max_concurrent_queries_for_user>`
And login as user A, tried run 2 queries in same time, found both queries run successfully, but as I set the max_concurrent_queries_for_user as 1, I expect only one query is allow to run in one time, could you please help me understand how to use "max_concurrent_queries_for_user", thanks!

**Comment by nikitamikhaylov** [comment]
Are you sure that your queries are really concurrent? If they are rather quick, they will be executed successively. Otherwise the exception will be thrown 
https://github.com/ClickHouse/ClickHouse/blob/6e37d765e678edcb7e1813dc463dc2b690ee0854/dbms/src/Interpreters/ProcessList.cpp#L116

**Comment by 42997455** [comment]
Thanks @nikitamikhaylov , I may not quit understand the really concurrent, I guess it mean how many queries run in same time?

what I have set in config.xml is:
`
<yandex>
...
<max_concurrent_queries>100</max_concurrent_queries>
<max_concurrent_queries_for_user>1</max_concurrent_queries_for_user>
...
</yandex>
`

but after I check it in clickhouse in system.settings, the 'max_concurrent_queries_for_user' is still 0.

So my first question is how to set the 'max_concurrent_queries_for_user' in config.xml?

Then I use set max_concurrent_queries_for_user=1; in clickhouse client, then I check the 'max_concurrent_queries_for_user' is 1 now.

I open 3 client windows with same user 'web' and run 2 same queries in same time in 2 windoes, use another window to run sql and got: 
`SELECT count(*)
FROM processes

┌─count()─┐
│       3 │
└──────┘`

So I think it is not expected, for the queries in processes are all the user 'web' queries, but I expect only one query can be run in same time for user 'web', for I have set the 'max_concurrent_queries_for_user' to 1.

So my second question is how to make 'max_concurrent_queries_for_user' working for me, thanks!

**Comment by 42997455** [comment]
Hi @nikitamikhaylov , the 'max_concurrent_queries_for_user' working for me now, I thought it is global parameter before, add in config.xml, under the max_concurrent_queries wrong place.

Now I put it in users.xml, and working for me now, thanks!
