### ISSUE TITLE
Can I controll the insert rate of syntex 'INSERT INTO SELECT'?

### ISSUE THREAD

**Issue by byx313** [ClickHouse/ClickHouse#9406]
I would like to know what is the factor that controll the insert rate of syntex 'INSERT INTO SELECT'?It depends on ClickHouse internal calculation?
Any parameter can I change to increase or decrease the insert rate?

**Comment by den-crane** [comment]
No. 

Currently `INSERT INTO SELECT` works in one thread (insert part).
In the next stable release (20.2) will be implemented **Parallel INSERT in INSERT SELECT query** ://github.com/ClickHouse/ClickHouse/pull/8166 and a setting `max_insert_threads`.

But still where is no ability and plans for ability to control insert rate in MB/s or rows/s.


As workaround you can use Linux utility pv set the rate:

```
clickhouse-client -q 'select * from T format Native' |pv --rate-limit=1M | clickhouse-client -q 'insert into T1 format Native'
```

**Comment by byx313** [comment]
> No.
> 
> Currently `INSERT INTO SELECT` works in one thread (insert part).
> In the next stable release (20.2) will be implemented **Parallel INSERT in INSERT SELECT query** #8166 and a setting `max_insert_threads`.
> 
> But still where is no ability and plans for ability to control insert rate in MB/s or rows/s.
> 
> As workaround you can use Linux utility pv set the rate:
> 
> ```
> clickhouse-client -q 'select * from T format Native' |pv --rate-limit=1M | clickhouse-client -q 'insert into T1 format Native'
> ```

thank you for the reply guy
