### ISSUE TITLE
Data Aggregation & Hybrid Engine Issues

### ISSUE THREAD

**Issue by ccwud** [ClickHouse/ClickHouse#9423]
**clickhouse version: 19.17.4.11 (official build)**
**1) Description:** Clickhouse's SummingMergeTree table engine, how to quickly aggregate data, now it is found that the data has not been aggregated for a long time, can I query the aggregated data within a controllable range, now I have two methods here.
1: Use group by when querying, but feel poor performance.
2: Use optimize table t_sum_1 final to force data aggregation.
**Question:** What other methods can be used to query, the performance is better, and you can also query the data after aggregation

------

**2)Description & Question**: When using Clickhouse's SummingMergeTree table engine, I also want to continue using other data aggregation methods in this table, that is, I want to use multiple table engines in a table, and now I want to ask if there is such support, business It is possible to have such a requirement, and there are other table engines that can meet it, just want to ask if it can support hybrid engines?

**Comment by den-crane** [comment]
1) You should always use sum / group by when querying SummingMergeTree. 
Please provide an example (DDL/Dataset/Query) of bad performance.

2) You can use AggregatingFunctions with SummingMergeTree.
