### ISSUE TITLE
Where clause not working with the ClickHouse view

### ISSUE THREAD

**Issue by avashist004** [ClickHouse/ClickHouse#9425]
I am trying to create a view on a source table and then select the data for a specific timestamp range from the view and put it into the targe table.

We have a source table:

```
CREATE TABLE IF NOT EXISTS source (
  CELL          String,
  TIMESTAMP     DateTime,
  COUNTER1      Float32,
  COUNTER2      Float32,
  COUNTER3      Float32,
  COUNTER4      Float32,
  COUNTER5      Float32,
  COUNTER6      Float32,
  InsertionTime DateTime DEFAULT now(),      /* Insertion Time */
  QHour         DateTime DEFAULT toStartOfFifteenMinutes(TIMESTAMP)
) ENGINE=ReplacingMergeTree()
PARTITION BY toYYYYMM(TIMESTAMP)
ORDER BY (QHour, TIMESTAMP, CELL)
SETTINGS index_granularity = 31768
```

1 Million rows are pushed to the source table which corresponds to data from 1 January to 31 January.

Now, we created a view on the source table.

```
CREATE VIEW IF NOT EXISTS ThreeCell_KPI_QHour_View
  AS SELECT
    CELL,
    QHour,
    toStartOfFifteenMinutes(TIMESTAMP) 	    AS ViewQHour,
	100 * sum(COUNTER1) / sum(COUNTER2)	    AS KPI1
  FROM ( 
    SELECT
        CELL,
        TIMESTAMP,
		any(QHour) as QHour
        argMax(COUNTER1, InsertionTime)     AS COUNTER1,
        argMax(COUNTER2, InsertionTime)     AS COUNTER2
    FROM ThreeGCell
    GROUP BY TIMESTAMP, CELL, QHour)
GROUP BY ViewQHour, CELL
ORDER BY ViewQHour, CELL
```
Now, on the view I need to select the data for a time period from view: 1 January to 10th January.

```
SELECT * 
FROM myView 
WHERE QHour >= toDateTime('2020-01-01 00:00:00') AND QHour <= toDateTime('2020-01-10 00:00:00')
```
The select query on the view results in 1 million rows which is whole January data while I am looking for data for specific period only 1 January to 10th January.

I have following questions:

1. Can we modify the query on the view to only process the specific time period?
2. Can we generate a view on the latest dataset pushed in the source table on the fly? I mean we have only the filtered dataset from source table and use the filtered data in the view? Can such filters be modified to use different time ranges? For example, we have data from 1 January to 10th January in the view. Then in second run, we have data from 11th Janury to 20th January in the view.

**Comment by den-crane** [comment]
Create a view without ORDER BY 
and `any(QHour) as QHour`
It's impossible to pushdown  `any(QHour)`

```
SELECT *
FROM
(
    SELECT
        CELL,
        QHour,
        toStartOfFifteenMinutes(TIMESTAMP) AS ViewQHour,
        (100 * sum(COUNTER1)) / sum(COUNTER2) AS KPI1
    FROM
    (
        SELECT
            CELL,
            TIMESTAMP,
            QHour,
            argMax(COUNTER1, InsertionTime) AS COUNTER1,
            argMax(COUNTER2, InsertionTime) AS COUNTER2
        FROM source
        GROUP BY
            TIMESTAMP,
            CELL,
            QHour
    )
    GROUP BY
        ViewQHour,
        QHour,
        CELL
)
WHERE QHour = toDateTime('2019-01-01 00:00:00')
FORMAT Null

Ok.

0 rows in set. Elapsed: 0.011 sec. Processed 31.77 thousand rows, 921.27 KB (2.90 million rows/s., 83.96 MB/s.)
```

Also you partitioned by toYYYYMM(TIMESTAMP) but don't use TIMESTAMP in where clause so partition pruning does not work.
