### ISSUE TITLE
External data for query processing is not sent when data is empty

### ISSUE THREAD

**Issue by xzkostyan** [ClickHouse/ClickHouse#943]
When I send query with external data and actual data in it, it's proceed normally:
```bash
$ echo -ne "3\n" | clickhouse-client --query="SELECT * FROM _data" --external --file=- --types=Int8
3
```
![pic1](https://i.gyazo.com/cbea4174843aebf4ef4e5f578456b22f.png)

But when data is empty, it's proceed with error:
```bash
$ echo -ne "" | clickhouse-client --query="SELECT * FROM _data" --external --file=- --types=Int8Received exception from server:
Code: 60. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Table default._data doesn't exist.. 
```

No data for 'external data' appear in payload:

![pic2](https://i.gyazo.com/c0cd52ba438be5057da9e9a9237c8fd7.png)

Expected behaviour: empty "_data" table is sent to the server.

ClickHouse server version: 1.1.54236.
ClickHouse client version: 1.1.54213/1.1.54236.

**Comment by alexey-milovidov** [comment]
Fixed some time ago.
I've added a test in #10926.
