### ISSUE TITLE
Support for sasl+md5 authentication in zookeeper

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#9431]
https://cwiki.apache.org/confluence/display/ZOOKEEPER/Client-Server+mutual+authentication

**Comment by FavonianKong** [comment]
Hi，Is there any new progress on this proposal? Does the clickhouse support only SSL currently?

**Comment by alexey-milovidov** [comment]
No progress. Most likely this feature will never be implemented.
