### ISSUE TITLE
"ephemeral" or "dematerialized" columns

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#9436]
Special type of column. This column can be INSERTed and can be referred in default expressions of another columns, but it is not stored in a table and cannot be SELECTed.

**Use case**
Calculate other columns on top of input data but don't store the source column. Example: extract something from JSON.

**Alternatives**
You can use table function `input` for the same result. It is just a little less convenient.

**Comment by KochetovNicolai** [comment]
@yakov-olkhovskiy is working on this task
