### ISSUE TITLE
Punycode encode/decode.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#9437]
**Use case**
Add two functions to work with punycode.

**Describe the solution you'd like**
A tight loop with no extra allocations or copying, as usual.
`libidn2` may suffice but it's unclear.

**Comment by alexey-milovidov** [comment]
Still relevant.

**Comment by syominsergey** [comment]
@alexey-milovidov Alexey. hello!
Could you explain, please, why did you say that `libidn2 may suffice but it's unclear`?
What are the problems with `libidn2`?
I don't know `libidn2`, so my question is honest.
Maybe I can take this task if it is actual and not already taken by somebody, but I want to know the backgroud.

**Comment by alexey-milovidov** [comment]
It was unclear if the library requires extra allocations to process data. But it looks ok https://www.gnu.org/software/libidn/manual/libidn.html#Header-file-punycode_002eh

Also need to check performance. Most likely it will suffice.

**Comment by alexey-milovidov** [comment]
Yes, you can take this task!

**Comment by syominsergey** [comment]
@alexey-milovidov  Alexey. thank you for explanation. Please, assign it to me.

**Comment by syominsergey** [comment]
@alexey-milovidov Alexey, I checked performance for ascii --> unicode decoding.
I used some list of real punycode encoded domains ([this](https://cctld.ru/files/docs/pendingdelete/RFDelList20210917.zip) file from [this](https://cctld.ru/service/dellist/) site - the best list I have found).
And release [libidn2-2.3.2](https://ftp.gnu.org/gnu/libidn/libidn2-2.3.2.tar.gz) of `libidn2` library.
For testing purposes I have wrote some [simple program](https://gist.github.com/syominsergey/0702a85366820998304f5aa9c504005a).

On my `Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz` I have following results:
```
lines processed: 369
it lasted 0.520916 milliseconds
in average 0.0014117 ms per line
```

is it ok result for ascii --> unicode decoding?
is it good idea to do such test for unicode --> ascii encoding?

**Comment by alexey-milovidov** [comment]
It's better to integrate the library into ClickHouse and then test performance.

PS. 

Performance is less than one million rows/sec. that is small, but mostly it because the benchmark is not 100% correct.

```
char *unicode_buf;
int rc = idn2_to_unicode_8z8z(input_line.c_str(), &unicode_buf, 0);
```

We should use version that does not allocate memory.

**Comment by syominsergey** [comment]
@alexey-milovidov Alexey, thank you for your comment.
I thought that it is better to measure performance before integrating into ClickHouse. Because what if it is not good enough?
But if result may be uncorrect... So, I understand now that it is better to integrate it before measuring performance.
Thank you for your comment about need to use version that does not allocate memory.
That was not obvious desire for me but now I understand,

**Comment by alexey-milovidov** [comment]
If the performance is not good enough, we replace the library with a code snippet that does the same. I know a few places where to get it :)

**Comment by syominsergey** [comment]
Just for information.
I'm trying to understand how to use `punycode_decode`:
https://github.com/libidn/libidn2/blob/master/lib/decode.c#L95

it is not so trivial as using high level `idn2_to_unicode_8z8z`

**Comment by syominsergey** [comment]
it looks like `punycode_decode` is some kind of middleware function that takes only part of work when decoding punycode

**Comment by syominsergey** [comment]
I think we need to copypaste sources of `idn2_to_unicode_8z8z`, `idn2_to_unicode_8z4z` and other related and modify then to use preallocated memory instead of allocating memory in this functions as done in oriiginal `libidn2` library

**Comment by syominsergey** [comment]
@alexey-milovidov Alexey, what dou you think about this? ^

**Comment by alexey-milovidov** [comment]
It's not ok, because these sources are under LGPL. You can write your own implementation on top of punycode_encode/punycode_decode.

**Comment by syominsergey** [comment]
Suddenly some question appeared.

Do we need he to only support punycode encoding decoding as described, for example, [here](https://en.m.wikipedia.org/wiki/Punycode)? Or we need to support internationalized domain names encoding and decoding as described, for example, [here](https://en.m.wikipedia.org/wiki/Internationalized_domain_name). Sorry for such question. Because IDN is based on Punycode, maybe I confused about what we want to implement here. So, please, could you clarify the answer on my question about purpose of this issue - only Punycode or IDN too?

**Comment by alexey-milovidov** [comment]
Ideally we should do both, like

punycodeEncode
punycodeDecode
IDNEncode
IDNDecode

**Comment by syominsergey** [comment]
Thank you for clarification.
I will try to implement punycodeEncode and punycodeDecode at first using ready functions from libidn2 suitable for us and then think what to do with IDNEncode and IDNDecode

**Comment by alexey-milovidov** [comment]
@syominsergey Hi, how is it?

**Comment by syominsergey** [comment]
Unfortunately, I must note that there is no significant progress

if someone wants to take this task, it would be better to give it to him

if not, I will try to return to it in the future and bring it to the end

**Comment by AndreyTokmakov** [comment]
Hi,
If you don't mind I would like to take this issue

Wanted to clarify, the idea is to implement something like the space-time efficient wrapper around punycode_encode() and punycode_decode() which we have in Net/src/DNS.cpp?

**Comment by alexey-milovidov** [comment]
Yes. Looks like these functions are fairly dry (no copies, allocations) and we need to make wrappers for them to be available as SQL functions.

**Comment by AndreyTokmakov** [comment]
I need a little advice, I wanted to agree/clarify on the data formats (signature):
1. punycodeDecode(): should convert UTF-8 --> UTF-32
at the input we get std::string as far as I understand
we assume that the string is already encoded in punycode? and we actually do punycode decoding
We can return std::u32string or uint32_t array
 
2. punycodeEncode():
Can we assume that we should get some kind of 4-byte array (std::u32string or uint32_t array) ?
as input and return the instance std::string (punycode encoding)

**Comment by alexey-milovidov** [comment]
@AndreyTokmakov 

Both functions should assume UTF-8 input and return UTF-8 output (String -> String).
Example:

```
punycodeEncode('https://ввв.яндекс.рф/') = 'https://xn--b1aaa.xn--d1acpjx3f.xn--p1ai/'
punycodeDecode('https://xn--b1aaa.xn--d1acpjx3f.xn--p1ai/') = 'https://ввв.яндекс.рф/'
```

**Comment by AndreyTokmakov** [comment]
Thanks

**Comment by AndreyTokmakov** [comment]
@alexey-milovidov hello
i've created a pull request https://github.com/ClickHouse/ClickHouse/pull/34439
its still in “WIP”  status,  but in general, I think it can at least be reviewed/discussed that you understand whether this implementation is suitable at all or not

**Comment by M4t7e** [comment]
@AndreyTokmakov do you plan to finish your work in #34439? It looks very promising to me and @vitlibar suggested only a few minor changes in his code review.

I'm looking for the punycode encode/decode functions for a longer time and it is a pity I can't do this directly in CH. You would be doing me and many others a huge favor 😊

**Comment by alexey-milovidov** [comment]
There are fairly ok functions in base/poco/Net/src/DNS.cpp

**Comment by alexey-milovidov** [comment]
The implementation in #34439 uses it.

**Comment by alexey-milovidov** [comment]
Wow, it's done!
