### ISSUE TITLE
Extremely bad font rendering on Linux

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#9458]
Examples:

1. ![Screenshot_20200301_175142](https://user-images.githubusercontent.com/18581488/75627908-64807500-5be5-11ea-8fe0-933609c443b1.png)
2. ![Screenshot_20200301_175202](https://user-images.githubusercontent.com/18581488/75627911-65190b80-5be5-11ea-869a-645f9fda10cd.png)

Recently we have used "Yandex" font and it was perfect.
But now we have switched to some unknown combination of open-source fonts that displays extremely creepy. Linux users is our main audience (for example, I am using Linux and all our developers are using Linux). Bad fonts rendering can compromise the reputation of our product.

Solutions considered:
- continue using "Yandex" font;
- find some normal open-source font;
- buy some normal font for our website.

Every solution should be validated on my PC.

**Comment by blinkov** [comment]
@alexey-milovidov please uninstall `fonts-liberation` and `fonts-liberation2` deb packages, reboot your PC and provide screenshots of same content after that.

**Comment by alexey-milovidov** [comment]
> please uninstall fonts-liberation and fonts-liberation2 deb packages

This is not an option. I have tested on two machines and font rendering are bad on both of them. If the "Liberation" font has low quality, we just should not use it instead of insisting users to uninstall it.

**Comment by alexey-milovidov** [comment]
We decided to replace
```
300 14pt/200% -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji,Segoe UI Emoji
```
to
```
300 14pt/200% -apple-system, BlinkMacSystemFont, Segoe UI, Noto Sans, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji
```

Please also note that the whitespace has been added after the last comma.

PS. This strange list of fonts comes from unknown open-source template.

**Comment by alexey-milovidov** [comment]
Fixed on the new website by https://github.com/ClickHouse/ClickHouse/issues/9458#issuecomment-594123762

**Comment by alexey-milovidov** [comment]
Now it looks perfect.
