### ISSUE TITLE
Proposal: faster ReplacingSortedBlockInputStream

### ISSUE THREAD

**Issue by innerr** [ClickHouse/ClickHouse#947]
MergingSortedBlockInputStream is a key streaming module in my opinion.
Although it may not directly be responsible for the read/write operations.

It's implement as I saw, are throwing all the rows to a priority queue and popping them out.

I did some tests, the IO throughput of this module is about 80-90MB/s on my computer, since the SSD has 400MB/s bandwidth.

So I wander if it can run faster, here is a little thought:

1. Use multi threads pipelining, sort and prepare next batch of blocks even current blocks are not fully sorted yet. Some of the blocks of the current batch may be cut off by a selected checkpoint (say, a random block's last row).

2. Check each block's lower and upper bounds, if one's upper bound greater than others (in ASC sorting), that it can be directly read without row comparing.

3. Use binary search instead of priority queue in some condition (2-3 streams, values are clustered), it may reduce comparing times, and use batch copy rather then row-by-row copy.

What do you think?

**Comment by ludv1x** [comment]
Thank you for your detail proposal :+1: .

There are two usecases of MergingSortedBlockInputStream: implementation of ORDER BY and background merges.

1. Prefetching is implemented for ORDER BY, see [here](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Interpreters/InterpreterSelectQuery.cpp#L1131) and AsynchronousBlockInputStream class. But prefetching is really is not performed during merges, each merge uses only one thread, so we have optimisation possibilities here.
2. Similar check is performed [here](https://github.com/yandex/ClickHouse/blob/55bfaca662f68123cd14d916d43923aadaba3b95/dbms/src/DataStreams/MergingSortedBlockInputStream.cpp#L218)
3. Yes, It really looks like `std::priority_queue` is slow, but we didn't investigate it in detail yet. I think we have good optimisation possibilities here also.

**Comment by alexey-milovidov** [comment]
Also we don't repeatedly push and pop from priority_queue if we have a sequence of values all of them are lower than other: https://github.com/yandex/ClickHouse/blob/55bfaca662f68123cd14d916d43923aadaba3b95/dbms/src/DataStreams/MergingSortedBlockInputStream.cpp#L282

For background merges, priority_queue is not a bottleneck, because most of time is spent for moving data rather than calculating in what order to move it.

It becomes a bottleneck for large ORDER BY without small LIMIT, when sorted rows are thin.

**Comment by innerr** [comment]
I'm sorry I made a big mistake.
What I actually saying is ReplacingSortedBlockInputStream, some how I mixed up with MergingSortedBlockInputStream, apologize again.

The ReplacingSortedBlockInputStream have a much simpler implement in the "merge" method, and truely have the problem as I mentioned.

It caused a slow merging progress, that noticed me.

**Comment by alexey-milovidov** [comment]
Don't worry, we are always interested in optimization possibilities.

About `Replacing`: the main concern is that `Vertical` merge algorithm is not enabled for this mode.
This is easily doable and with `Vertical` algorithm, merges will run significantly faster (in case of wide tables).

**Comment by innerr** [comment]
Thanks a lot!

**Comment by alexey-milovidov** [comment]
No one was interested in this task.
