### ISSUE TITLE
Keep edits in history while navigating with up/down keys in client.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#9474]
**Use case**
1. Open clickhouse-client in interactive mode.
2. Press "up" to edit previous query from the history.
3. Start editing the query.
4. Accidentially press "up" or "down".
5. Undo the action with "down" or "up" correspondingly.
6. Edits to the query from the history are lost.

This is a disappointing behaviour of `replxx` in comparison to `readline`.

**Comment by amosbird** [comment]
It's not easy to have complete readline history editing persistency feature in replxx. However simply prevent `Accidentially up and down` can be achieved.  

https://github.com/ClickHouse-Extras/replxx/pull/4
