### ISSUE TITLE
Multiline query from the history can present with strange \R characters.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#9475]
**Describe the bug or unexpected behaviour**
1. Open `clickhouse-client -n`
2. Paste one or multiple multiline queries.
3. Execute them.
4. Press "up" to open them again.

**Comment by amosbird** [comment]
I cannot reproduce this one

**Comment by alexey-milovidov** [comment]
Fixed in one of PRs, thank you!

**Comment by alexey-milovidov** [comment]
I'm using kUbuntu 19.10 (eoan) with Konsole as a terminal emulator and Kate as a text editor.
I'm copying a multiline text from Kate with selection and Ctrl+C.
```
SELECT *
FROM system.replicas
WHERE table = 'elog'
```

Then I'm pasting it into `clickhouse-cleint` with Ctrl+Shift+V or with middle mouse button or with Shift+Insert.

The text is pasted as:
```
SELECT *^JFROM system.replicas^JWHERE table = 'elog'^J
```

But if I press "Enter" it will be interpreted correctly.
It does not matter if `clickhouse-client` is run with or without `-n` option.

If I paste the same text into `bash` instead of `clickhouse-client`, it works without this issues (as usual multiline paste).

**Comment by alexey-milovidov** [comment]
Fixed in https://github.com/ClickHouse-Extras/replxx/pull/5
