### ISSUE TITLE
clickhouse  how to import columns to one table at different time ？

### ISSUE THREAD

**Issue by wushiming540** [ClickHouse/ClickHouse#9478]
different columns  join by did。

first time: import column1 and column2.
did, column1, column2

second time: import column3 and column4.
did, column3, column4

the final table is  : did, column1, column2,column3, column4

**Comment by den-crane** [comment]
You can use Replacing Collapsing or Aggregating mergeTreee

https://gist.github.com/den-crane/d03524eadbbce0bafa528101afa8f794

**Comment by sundy-li** [comment]
What about a triggered material view?

Just a prototype
```
create table a (did String,  c1 String, c2 String, ingestTime DateTime );
create table b (did String, c3 String, c4 String, ingestTime DateTime);
create table a_b (did String, c1 String, c2 String, c3 String, c4 String);


CREATE MATERIALIZED VIEW a_b_mv TO a_b TRIGGERED BY a,b   AS
SELECT
    a.did,
    a.c1,
    a.c2,
    b.c3,
    b.c4
FROM a
INNER JOIN b ON a.did = b.did
WHERE (a.b.ingestTime >= (now() - 3600)) AND (b.ingestTime >= (now() - 3600))


```
