### ISSUE TITLE
delete data or drop partition?

### ISSUE THREAD

**Issue by qietingfengling** [ClickHouse/ClickHouse#9479]
When clickhouse deletes the data, there is no increase in the number of zk tpcs and nodes, and the drop is small; when drop partition, the number of zk nodes can decrease, but the watch_count of zk will increase significantly, unless the clickhouse cluster is restarted. What about deleting the question?

**Comment by blinkov** [comment]
@qietingfengling, is this question still relevant?

**Comment by alexey-milovidov** [comment]
> but the watch_count of zk will increase significantly

The number of active watches in ZK is not an issue. There are some scenarios when watches may "leak" but you should not worry.
