### ISSUE TITLE
Feature: possibility to pin data of MergeTree in uncomressed_cache to increase speed for real-time data

### ISSUE THREAD

**Issue by inv2004** [ClickHouse/ClickHouse#948]
Hello,

CH is very fast database even on servers without much RAM, but some tasks request more speed and less insert-available latency for recent and actual data. Usually it is also possible to keep this data in memory on HW with 128Gb-1TB and more RAM.

CH has use_uncompressed_cache flag, which creates in-mem data to increase speed, but there are two problems to emulate in-mem behavior:
1) Not possible to pin some data in-mem (set condition which data should be in memory), only LVC algorithm.
2) To have data in uncompressed_cache it is necessary to:
   a) insert
   b) -> compress and save on disk
   c) -> select and load into cache.
  Access to the data would be more real-time if it would be possible to avoid this chain and have data in cache right after insert.
3) another problem with uncomressed String type, but I suppose it would be better to separate it into another issue/feature.

It would help to compete CH with in-mem databases and significantly increase benchmarks on HW with more RAM.

Thank you.

**Comment by inv2004** [comment]
Found ~ the same discussion in google-groups: https://groups.google.com/d/msg/clickhouse/EuKcaYw_NaM/iKy1cDpECgAJ

**Comment by alexey-milovidov** [comment]
We have two approaches to make it possible:

1. There is support for multiple storage volumes in ClickHouse with customizeable storage policies to control data placement. A volume may be mounted to tmpfs. https://presentations.clickhouse.tech/meetup36/new_features/#12

2. There is a feature in development to support in-memory format for small (recently inserted) data.
