### ISSUE TITLE
Data loss in CollapsingMergreTree may be a bug

### ISSUE THREAD

**Issue by nshah14285** [ClickHouse/ClickHouse#9480]
Hello,

It looks like a bug with the latest version (20.1.4.14) of the clickhouse.
Clickhouse delete the record where -1 sign is not present for PageViews 7.

`SELECT * FROM UAct`

┌──────────────UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│ 4324182021466249494 │         5 │      146 │   -1 │
│ 4324182021466249494 │         6 │      185 │    1 │
└─────────────────────┴───────────┴──────────┴──────┘
┌──────────────UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│ 4324182021466249494 │         5 │      146 │    1 │
└─────────────────────┴───────────┴──────────┴──────┘
┌──────────────UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│ 4324182021466249494 │         7 │      185 │    1 │
└─────────────────────┴───────────┴──────────┴──────┘

From the above result, expecting output is 2 records i.e PageViews 6 and PageViews 7 but after sometime when I again ran the query it output only 1 record

 `SELECT * FROM UAct`

┌──────────────UserID─┬─PageViews─┬─Duration─┬─Sign─┐
│ 4324182021466249494 │         6 │      185 │    1 │
└─────────────────────┴───────────┴──────────┴──────┘

How the record with PageViews 7 got deleted?

Thanks,
Nishit

**Comment by den-crane** [comment]
Works as expected. Yes, collapsingMT replaces rows with the same sign.

```
create table c (A Int64, B String, S Int8) Engine=CollapsingMergeTree(S) order by A;
insert into c values(1, '1', 1);
insert into c values(1, '2', 1);

select * from c final;
┌─A─┬─B─┬─S─┐
│ 1 │ 2 │ 1 │
└───┴───┴───┘

optimize table c final;

select * from c;
┌─A─┬─B─┬─S─┐
│ 1 │ 2 │ 1 │
└───┴───┴───┘
```
