### ISSUE TITLE
How to install clickhouse odbc driver from binary

### ISSUE THREAD

**Issue by Vibhooti123** [ClickHouse/ClickHouse#9485]
I am trying to build a dremio-clickhouse connector for this i am trying to install clickhouse odbc driver. But i unable to untar the tar file and not clear for next step. Please help me to find out the right way of downloading the clickhouse odbc driver.

**Comment by filimonov** [comment]
You can install clickhouse-odbc on ubuntu like that 
```
wget "https://github.com/ClickHouse/clickhouse-odbc/releases/download/v1.1.4.20200302/clickhouse-odbc-1.1.4-Linux.tar.gz" 
tar xvzf clickhouse-odbc-1.1.4-Linux.tar.gz
```

After that you may need to install it like that:
```
apt-get install unixodbc
cp clickhouse-odbc-1.1.4-Linux/lib64/*.so /usr/local/lib/
odbcinst -i -d -f clickhouse-odbc-1.1.4-Linux/share/doc/clickhouse-odbc/config/odbcinst.ini.sample
odbcinst -i -s -l -f clickhouse-odbc-1.1.4-Linux/share/doc/clickhouse-odbc/config/odbc.ini.sample
```

**Comment by Vibhooti123** [comment]
I am working on Redhat Centos8

**Comment by filimonov** [comment]
So you need to intsall packages using yum instead of apt-get
```
sudo yum install unixODBC
```
I don't remember the location of libs folder on centos, but i think `/usr/local/lib/` should work.

**Comment by Vibhooti123** [comment]
Ohkk thanks for your help. I will try this.

**Comment by traceon** [comment]
> cp clickhouse-odbc-1.1.4-Linux/lib64/*.so /usr/local/lib/

BTW, it's always a good idea to install the driver to the dedicated prefix, like under `/opt/clickhouse-odbc/1.1.4/`
