### ISSUE TITLE
Error in system.replication_queue 

### ISSUE THREAD

**Issue by onine007** [ClickHouse/ClickHouse#9504]
version  20.2.1

There is  an error in table system.replication_queue  .

 Not executing log entry for part 20200213_2040_2040_1_2016 because another log entry for the same part is being processed. This shouldn't happen often.

┌─database─┬─table───────────────────┬─replica_name─┬─position─┬─node_name────────┬─type────────┬─────────create_time─┬─required_quorum─┬─source_replica─┬─new_part_name─────────────┬─parts_to_merge────────────────┬─is_detach─┬─is_currently_executing─┬─num_tries─┬─last_exception─┬───last_attempt_time─┬─num_postponed─┬─postpone_reason─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──last_postpone_time─┐
│ my_sdap  │ dm_user_behavior_events │ replica-001  │        0 │ queue-0000104788 │ MERGE_PARTS │ 2020-03-04 07:46:52 │               0 │ replica-001    │ 20200213_2040_2040_1_2016 │ ['20200213_2040_2040_0_2016'] │         0 │                      0 │         0 │                │ 0000-00-00 00:00:00 │          3801 │ Not executing log entry for part 20200213_2040_2040_1_2016 because another log entry for the same part is being processed. This shouldn't happen often. │ 2020-03-04 08:36:43 │

**Comment by alexey-milovidov** [comment]
This is normal system behaviour.

**Comment by alexey-milovidov** [comment]
And this is not an error but `postpone_reason`.

**Comment by onine007** [comment]
OK  ,thank you!
