### ISSUE TITLE
Clickhouse SQL implementation populates data

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#9505]
I need to implement the month between 20171001 and 20180101. The country field is filled with "Au" and the rate field is filled with 0.888.
In the month between 20180201 and 20181101, the country field is filled with "Au" and the rate field is filled with 0.7089.
How can I achieve it ！！！！

SQL：
SELECT
a.dates,
b.country,
b.rate
FROM
(
SELECT toInt32(toYYYYMMDD(subtractMonths(toDate('2020-01-01'), months_t - 1))) AS dates
FROM
(
WITH
(
SELECT toUInt64(dateDiff('month', toDate('2016-01-01'), addMonths(today(), 1)))
) AS months
SELECT arrayJoin(arrayMap(x -> (x + 1), range(months))) AS months_t
)
ORDER BY dates ASC
) AS a
LEFT JOIN
(
SELECT *
FROM s_finance_rate_country
WHERE country = 'AU'
) AS b ON a.dates = b.rate_date
WHERE (a.dates >= 20171001) AND (a.dates < 20181201)

query results：

[
![image](https://user-images.githubusercontent.com/40047678/75837540-1a271000-5e00-11ea-8254-7f34196774a3.png)
](url)

Really needed results:

[
![image](https://user-images.githubusercontent.com/40047678/75837551-24490e80-5e00-11ea-8ee7-a30e03997219.png)
](url)

**Comment by filimonov** [comment]
Did you consider `order by ...  With fill`?

**Comment by leoones** [comment]
> Did you consider `order by ... With fill`?
With fill and arrayfill functions are used to implement the！！！
Thank you for your reply  ！！！
