### ISSUE TITLE
Will the update operation destroy the data?

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#9518]
Yesterday, I performed the update operation in ClickHouse Cluster when Inserting.
Now, I found that a lot of data is not what I expected.

So, Will the update mutation destroy the correctness of the data while insert a lot of data?

**Comment by den-crane** [comment]
No, mutations make a list of parts which already exist and process this list only. Mutations does not see parts (data) inserted after and does not intersect with inserts.

**Comment by ShadowDAssange** [comment]
Is it possible that the failed mutation caused dirty data?

**Comment by den-crane** [comment]
> Is it possible that the failed mutation caused dirty data?

It could. We know that `alter delete` corrupts data in 20.1 https://github.com/ClickHouse/ClickHouse/issues/8821 . Maybe `alter update` corrupts it too. 

Please provide reproducible example and more information: CH version, DDL, logs, data samlples, etc.
