### ISSUE TITLE
DB::Exception: Seek position is beyond the decompressed block

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#9520]
When I use `select count() from table`, clickHouse throws this error?
`DB::Exception: Seek position is beyond the decompressed block (pos: 336, block size: 0): (while reading column {Column}): (while reading from part /var/lib/clickhouse/data/{db}/{table}/09007dd2ea901b5a4f6f7bf0268fe3bf_282587_301069_695/ from mark 0 with max_rows_to_read = 327680)`

**Comment by alesapin** [comment]
This error looks like a bug, but we need clickhouse version, your table definition, and data sample to investigate the error.
