### ISSUE TITLE
Некорректный перевод алгоритма CollapsingMergeTree в русской документации

### ISSUE THREAD

**Issue by PavelProkhorov** [ClickHouse/ClickHouse#9522]
Привет! 

https://clickhouse.tech/docs/ru/operations/table_engines/collapsingmergetree/

В описании алгоритма CollapsingMergeTree  1 и 4 пункт на русском неправильно сформулирован: 

- Первую строку отмены состояния и последнюю строку состояния, если количество строк обоих видов совпадает (не хватает "и последняя строка - строка состояния")
- Ни в одну из строк во всех остальных случаях (лишняя "в")

**Comment by BayoNet** [comment]
Fixed in #10649
