### ISSUE TITLE
Can DDLWorker be modified to execute query asynchronously?

### ISSUE THREAD

**Issue by nicelulu** [ClickHouse/ClickHouse#9523]
Quickly execute the next one.

**Comment by alexey-milovidov** [comment]
DDLWorker runs in the background. What kind of asynchronouty do you need?

**Comment by filimonov** [comment]
Check  `distributed_ddl_task_timeout` setting

**Comment by nicelulu** [comment]
> DDLWorker runs in the background. What kind of asynchronouty do you need?

Because some time-consuming queries block the following DDL queries.

For example, when the data volume is large, execute ```ALTER TABLE table_name ON CLUSTER xxx MODIFY COLUMN column_name Int64```. Or a ```ReplicatedMergeTree``` table become readonly mode, and then drop the data of this table using ```ON CLUSTER xxx```.

**Comment by blinkov** [comment]
@nicelulu, do you have any further questions?

**Comment by alexey-milovidov** [comment]
Your question: is it possible to execute distributed queries out of order?
No, we don't know what are possible dependencies between queries, so it will be unsafe in general.

**Comment by nicelulu** [comment]
https://github.com/ClickHouse/ClickHouse/pull/14684
