### ISSUE TITLE
Backward compativility issue client 20.2 ->server 20.3

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#9539]
hit it by accident (updated server, and did type query in old client session)
i think on client-side `send_logs_level` was enabled.

```
Ubuntu-1804-bionic-64-minimal :) select 1;

SELECT 1


Exception on client:
Code: 10. DB::Exception: Not found column thread_number in block. There are only columns: event_time, event_time_microseconds, host_name, query_id, thread_id, priority, source, text

Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 20.3.1 revision 54433.

ClickHouse client version is older than ClickHouse server. It may lack support for new features.

Ubuntu-1804-bionic-64-minimal :) show processlist;
-- the same
```

**Comment by alexey-milovidov** [comment]
I also have hit this issue and added a remark for changelog.

**Comment by filimonov** [comment]
I didn't check what's going exactly, if it doesn't affect server-to-server connections - it's not important.

**Comment by alexey-milovidov** [comment]
The client cannot read logs that are sent with `send_logs_level` setting.
In distributed setup, servers will forward logs to the initiator server, then they are sent to the client and the client will show an error.
