### ISSUE TITLE
Materialized View with targeting past data

### ISSUE THREAD

**Issue by hatrena** [ClickHouse/ClickHouse#9541]
I am having an issue with a Materialized View which targets the past data. I know that MV works like a trigger for inserts to a table. 

I need a Materialized View only for yesterday. I have the following MV:

```
CREATE MATERIALIZED VIEW default.chart_yesterday
ENGINE = ReplicatedSummingMergeTree(
     '/clickhouse/tables/{shard}/default/chart_yesterday',
     '{replica}')
     PARTITION BY toYYYYMM(date)
     ORDER BY (date, hour, cityHash64(organization_id)
)
SAMPLE BY cityHash64(organization_id)
SETTINGS index_granularity = 8192
POPULATE AS
SELECT
     SUM(rejected) AS clr,
     (count() - clr) AS cla,
     toDate(request_time) AS date,
     toHour(request_time) as hour,
     organization_id
FROM mytable_sharded
WHERE date = yesterday()
GROUP BY date, hour, organization_id
ORDER BY hour;
```

After creating the VM, I have data only for yesterday, everything fine. but after a day, the VM has no data

Does it mean that since there is no trigger for yesterday's data, so VM doesn't get triggered, so no data?

**Comment by den-crane** [comment]
>WHERE date = yesterday()

You MV will get a new data only if `insert into mytable_sharded` will insert `date = yesterday()`

**Comment by hatrena** [comment]
I used `PARTITION BY toYYYYMMDD(date)` with `table TTL`, and it worked perfectly. thanks
