### ISSUE TITLE
Kafka Engine pull is slower after upgrade to 20.1.4.14

### ISSUE THREAD

**Issue by shayrybak** [ClickHouse/ClickHouse#9544]
**Describe the situation**
After upgrading Clickhouse to the latest version (20.1.4.14)  from 13.X we are seeing the pull rate from Kafka is much lower and also the rate per partition consumed is different
**How to reproduce**
Clickhouse version: 20.1.4.14
Our setup is a 3 node Clickhouse cluster consuming from 2 Kafka topics. there are 3 copies of the Kafka table, one on each node. the number of consumers was defined to be equal to the amount of the partitions in the Kafka topics. 8 consumers for 2 topics with 8 partitions each.

I don't know if it's relevant but the Kafka tables are being consumed by 2 materialized views on each node that save to a distributed table that's sharded on all 3 nodes.

**Expected performance**
Before the upgrade, we were able to process spikes of ~100k messages per second, after the upgrade the max rate of reading is about 15k messages per second when all partitions are behind. if some partitions are caught up the rate slows down even more.
**Additional context**

**Comment by filimonov** [comment]
Which format do you use? Can you attach a table schema and a message sample?

**Comment by filimonov** [comment]
Also - please use the latest 20.1 release (there were few bugs fixed just 2 days ago)

**Comment by shayrybak** [comment]
Hi @filimonov thank you for your quick reply.

All of kafka_max_block_size, stream_poll_timeout_ms, stream_flush_interval_ms are left default.

We use the JSONEachRow format.

each message is one row.

Here is the table scheme

`CREATE TABLE default.kafka (`args` String, `browser_hash` String, `captcha_vld_str` String, `challenge_status` String, `client_local_ip` String, `computed_passed` UInt8, `conf__client_flat_log_files` UInt8, `conf__account_id` String, `conf__partner_ref` String, `conf__domain_id` String, `content_type` String, `conviction__action` String, `conviction__incident_id` String, `conviction__penalty` String, `conviction__phase` String, `conviction__priority` UInt16, `conviction__reference_id` String, `conviction__rule_id` String, `conviction__rule_name` String, `conviction__scope` String, `conviction__status` UInt16, `conviction__template` String, `conviction__data` String, `cookies` String, `country` String, `custom_data` String, `ddos_mode` UInt8, `ddos_status` String, `domain` String, `fp__flash` String, `fp__hash` String, `fp__headers` String, `fp__js` String, `headers_truncated` UInt8, `host` String, `http_version` String, `id` String, `ip` String, `is_injected` UInt8, `js_exe_status` String, `log_type` String, `method` String, `mode` String, `organization` String, `passed` UInt8, `passed_captcha` String, `passed_incident_id` String, `range` String, `real_domain` String, `request_headers` String, `request_props__is_api` UInt8, `request_props__is_static` UInt8, `request_props__is_ajax` UInt8, `request_type` String, `research_info` String, `response_headers` String, `response_source` String, `response_time` UInt32, `scheme` String, `session_id` String, `session_request_number` UInt32, `shell_script_status` String, `source` String, `status_code` UInt16, `timestamp` Float64, `tags` String, `tags_shield` String, `ua` String, `ua_parsed__client` String, `ua_parsed__client_type` String, `ua_parsed__client_version` String, `ua_parsed__client_version_float` String, `ua_parsed__cpu` String, `ua_parsed__device` String, `ua_parsed__device_type` String, `ua_parsed__engine` String, `ua_parsed__os` String, `ua_parsed__toolbar` String, `ua_parsed__cpu_bus` String, `ua_parsed__app_bus` String, `ua_parsed__client_priority` String, `ua_parsed__base_browser` String, `ua_parsed__base_browser_version` String, `ua_parsed__base_browser_version_float` String, `ui_data` String, `ui_events` String, `uri` String, `url` String, `user_tag__hash` String, `user_tag__type` String, `version` String) ENGINE = Kafka SETTINGS kafka_broker_list = 'broker-node1,broker-node2,broker-node3', kafka_topic_list = 'topic1,topic2', kafka_group_name = 'clickhouse_prod_consumer', kafka_format = 'JSONEachRow', kafka_skip_broken_messages = 1, kafka_num_consumers = 1`

An example message looks like reducted sensitive data obviously. 
`{
	"args": "<string>",
	"challenge_status": "<string>",
	"conf__account_id": "<number>",
	"conf__partner_ref": "<string>",
	"conf__domain_id": "<number>",
	"content_type": "<string>",
	"conviction__action": "<string>",
	"conviction__incident_id": "<string>",
	"conviction__phase": "<string>",
	"conviction__priority": < number > ,
	"conviction__reference_id": "<string>",
	"conviction__rule_id": "<number>",
	"conviction__rule_name": "<string>",
	"conviction__scope": "<string>",
	"conviction__template": "<string>",
	"cookies": "<string>",
	"country": "<string>",
	"ddos_status": "<string>",
	"domain": "<string>",
	"fp__hash": "<string>",
	"fp__headers": "<string>",
	"host": "<string>",
	"http_version": "<string>",
	"id": "<string>",
	"ip": "<ip>",
	"js_exe_status": "<string>",
	"log_type": "<string>",
	"method": "<string>",
	"mode": "<string>",
	"organization": "<string>",
	"origin": "<string>",
	"range": "<string>",
	"real_domain": "<string>",
	"request_headers": "<string>",
	"request_type": "<string>",
	"response_source": "<string>",
	"response_time": <number>,
	"scheme": "<string>",
	"session_id": "<string>",
	"session_request_number": <number>,
	"source": "<string>",
	"status_code": <number>,
	"timestamp": < number > ,
	"tags": "<string>",
	"ua": "<string>",
	"ua_parsed__client": "<string>",
	"ua_parsed__client_type": "<string>",
	"ua_parsed__client_version": "<string>",
	"ua_parsed__client_version_float": "<string>",
	"ua_parsed__cpu": "<string>",
	"ua_parsed__device": "<string>",
	"ua_parsed__device_type": "<string>",
	"ua_parsed__engine": "<string>",
	"ua_parsed__os": "<string>",
	"ua_parsed__cpu_bus": "<string>",
	"ui_data": "<string>",
	"ui_events": "<string>",
	"uri": "<string>",
	"url": "<string>",
	"user_tag__hash": "<string>",
	"user_tag__type": "<string>",
	"version": "<string>"
}`

The average message size is about 1.2 KB. 

We will try upgrading to the 20.1.6 version and see if that helps as well.

**Comment by shayrybak** [comment]
Also tried setting the kafka_max_block_size parameter to 512k as well at the `stream_poll_timeout_ms =100, stream_flush_interval_ms = 800` settings and we were able to pull at about 60k rows per second. which is a big improvement it appears. so this might have been the issue. I'll update if we get more data.

**Comment by filimonov** [comment]
> We will try upgrading to the 20.1.6 version and see if that helps as well

It will not help with performance, but it will Improve stability.

For performance - main direction of adjustments is `kafka_max_block_size`. Try values in range 512k - 2M. 

Rather  leave   `stream_poll_timeout_ms` and  `stream_flush_interval_ms` default.

**Comment by shayrybak** [comment]
I can confirm those settings work much better (similar to older version).

I'm going to close the case, but maybe the defaults should change to reflect that?
