### ISSUE TITLE
Performance issue in simple join in subquery

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#9556]
```
SELECT
	TEMP_ENRG.FA,
	T2.FA
FROM
	(
	SELECT
		SERVER_ID ,
		DATA_ID ,
		TV,
		addHours(TV,
		-1) PRE_TV,
		FA,
		FR
	from
		MDM.ENERGY_C_T  T1
	where
		T1.SERVER_ID = 1
		AND T1.DATA_ID = '711688325') AS TEMP_ENRG,
	MDM.ENERGY_C_T T2
where
	T2.TV = TEMP_ENRG.PRE_TV
	and T2.SERVER_ID = TEMP_ENRG.SERVER_ID
	and T2.DATA_ID = TEMP_ENRG.DATA_ID
```

table have 320 million records
this query use for calculate energy use of customer
only select on consumer

**Comment by mbtolou** [comment]
```
SELECT
	TEMP_ENRG.FA,
	T2.FA
FROM
	MDM.ENERGY_C_T  TEMP_ENRG,
	MDM.ENERGY_C_T  T2
where
	T2.TV = TEMP_ENRG.TV
	and T2.SERVER_ID = TEMP_ENRG.SERVER_ID
	and T2.DATA_ID = TEMP_ENRG.DATA_ID
	AND TEMP_ENRG.SERVER_ID = 1		AND TEMP_ENRG.DATA_ID = '711688325'
```

Simple join for one table in triple column join !!

SQL Error [241]: ClickHouse exception, code: 241, host: 127.0.0.1, port: 33758; Code: 241, e.displayText() = DB::Exception: Memory limit (for query) exceeded: would use 42.58 GiB (attempt to allocate chunk of 21473459696 bytes), maximum: 37.25 GiB (version 19.17.4.11)

**Comment by den-crane** [comment]
Join does not use indexes. Because currently CH supports only HashJoin. And HashJoin puts a right table into memory into HashTable with joinKey as a lookup key.

Try to swap tables 

`MDM.ENERGY_C_T  TEMP_ENRG, MDM.ENERGY_C_T  T2` -->`MDM.ENERGY_C_T  T2, MDM.ENERGY_C_T  TEMP_ENRG`

Try `SET partial_merge_join = 1`

**Comment by mbtolou** [comment]
This query not end normaly
```
SELECT 
TEMP_ENRG.FA, 
T2.FA 
FROM 
MDM.ENERGY_C_T  T2, 
MDM.ENERGY_C_T  TEMP_ENRG 
where 
TEMP_ENRG.SERVER_ID = 1
AND TEMP_ENRG.DATA_ID = '711688325' 
AND T2.TV = TEMP_ENRG.TV 
AND T2.SERVER_ID = TEMP_ENRG.SERVER_ID 
AND T2.DATA_ID = TEMP_ENRG.DATA_ID 

```
**1155** rows in set. Elapsed: **1341.021 sec.** Processed 523.82 million rows, 13.27 GB (390.61 thousand rows/s., 9.89 MB/s.) 



```
SELECT 
TEMP_ENRG.FA
FROM  
MDM.ENERGY_C_T  TEMP_ENRG 
where 
TEMP_ENRG.SERVER_ID = 1
AND TEMP_ENRG.DATA_ID = '711688325'  
```

**1753** rows in set. Elapsed: **0.009 sec**. Processed 57.34 thousand rows, 1.27 MB (6.70 million rows/s., 147.82 MB/s.)

**Comment by den-crane** [comment]
Try to swap table order in FROM!!!!
`MDM.ENERGY_C_T T2, MDM.ENERGY_C_T TEMP_ENRG`

CH does not have proper cost-based query optimizer yet. It's your responsibility to write SQL in proper way.

Try ANSI conventional way : 
```
SELECT
	TEMP_ENRG.FA, T2.FA
FROM
  MDM.ENERGY_C_T T2 join 
	    (SELECT SERVER_ID , DATA_ID , TV, addHours(TV, -1) PRE_TV, FA, FR
	     from MDM.ENERGY_C_T  T1
	     where T1.SERVER_ID = 1 AND T1.DATA_ID = '711688325') AS TEMP_ENRG
	join on ( T2.TV = TEMP_ENRG.PRE_TVand T2.SERVER_ID = TEMP_ENRG.SERVER_ID and T2.DATA_ID = TEMP_ENRG.DATA_ID)
```

**Comment by mbtolou** [comment]
Thanks.

1697 rows in set. Elapsed: 4.089 sec. Processed 338.67 million rows, 8.57 GB (82.82 million rows/s., 2.10 GB/s.) 

1753 rows in set. Elapsed: 0.009 sec. Processed 57.34 thousand rows, 1.27 MB (6.70 million rows/s., 147.82 MB/s.)

can you offer index for this table ?

> Try to swap table order in FROM!!!!
> `MDM.ENERGY_C_T T2, MDM.ENERGY_C_T TEMP_ENRG`
> 
> CH does not have proper cost-based query optimizer yet. It's your responsibility to write SQL in proper way.
> 
> Try ANSI conventional way :
> 
> ```
> SELECT TEMP_ENRG.FA, T2.FA
> FROM MDM.ENERGY_C_T T2 join 
>     (SELECT SERVER_ID , DATA_ID , TV, addHours(TV, -1) PRE_TV, FA, FR
>      from MDM.ENERGY_C_T  T1
>      where T1.SERVER_ID = 1 AND T1.DATA_ID = '711688325') AS TEMP_ENRG
>  on ( T2.TV = TEMP_ENRG.PRE_TVand T2.SERVER_ID = TEMP_ENRG.SERVER_ID 
>     and T2.DATA_ID = TEMP_ENRG.DATA_ID)
> ```
result after use your query :
1697 rows in set. Elapsed: 4.089 sec. Processed 338.67 million rows, 8.57 GB (82.82 million rows/s., 2.10 GB/s.) 

this result for without join select : 
```
SELECT 
TEMP_ENRG.FA
FROM  
MDM.ENERGY_C_T  TEMP_ENRG 
where 
TEMP_ENRG.SERVER_ID = 1
AND TEMP_ENRG.DATA_ID = '711688325'  
```
1753 rows in set. Elapsed: 0.009 sec. Processed 57.34 thousand rows, 1.27 MB (6.70 million rows/s., 147.82 MB/s.)

**Comment by mbtolou** [comment]
```
select 
T1.SERVER_ID , 
T1.DATA_ID , 
T1.TV , 
(T2.FA-T1.FA) USE_A, 
(T2.FR-T1.FR) USE_R 
from MDM.ENERGY_C_T  T2 join MDM.ENERGY_C_T  T1  
on ( T2.TV = addHours(T1.TV, -1) and T2.SERVER_ID = T1.SERVER_ID 
    and T2.DATA_ID = T1.DATA_ID) 
where T1.SERVER_ID =1
```

this is my final query for calculate delta between each record .
i run this query in oracle for create table .
table created after 2400 second but in CH this query not response after long time .

other performance test on CH 50x to 400x faster than oracle .
Why?

**Comment by den-crane** [comment]
READ CAREFULLY: 
**1. Join does not use indexes.**
**2. It's your responsibility to write SQL in proper way.**

Try 
```
SELECT TEMP_ENRG.FA, T2.FA
FROM MDM.ENERGY_C_T T2 join 
    (SELECT SERVER_ID , DATA_ID , TV, addHours(TV, -1) PRE_TV, FA, FR
     from MDM.ENERGY_C_T  T1
     where T1.SERVER_ID = 1 AND T1.DATA_ID = '711688325') AS TEMP_ENRG
 on ( T2.TV = TEMP_ENRG.PRE_TVand T2.SERVER_ID = TEMP_ENRG.SERVER_ID 
    and T2.DATA_ID = TEMP_ENRG.DATA_ID)
where T2.TV, T2.SERVER_ID, T2.DATA_ID in 
    (SELECT PRE_TVand, SERVER_ID, DATA_ID from MDM.ENERGY_C_T WHERE  
      SERVER_ID = 1 AND DATA_ID = '711688325')
```

**Comment by den-crane** [comment]
>1697 rows in set. Elapsed: 4.089 sec. Processed 338.67 million rows

It works as expected because of CH design JOIN.

>table created after 2400 second but in CH this query not response after long time .
>other performance test on CH 50x to 400x faster than oracle .
>Why?

It works as expected because of CH design JOIN. Just don't use JOINs.
