### ISSUE TITLE
service clickhouse-server status returns clickhouse-server service is stopped despite it running

### ISSUE THREAD

**Issue by yehiaelbehery** [ClickHouse/ClickHouse#9561]
This is probably a minor issue, but if run a fresh installation with 
Docker version 19.03.5, build 633a0ea on CentOS Linux release 7.7.1908 (Core)

> run -d --name clickhouse-server --ulimit nofile=262144:262144 --restart always --network host --cap-add NET_ADMIN yandex/clickhouse-server

Then you enter into the container with:

> docker exec -it [container_id] bash

and  run:

> service clickhouse-server status

it returns > "clickhouse-server service is stopped" although it up and working normally.

**Comment by filimonov** [comment]
Software packaged for docker is executed as a single process (not as a systemd/initV service). 
Once the process finishes it also stop docker container.

The proper way to check status of docker container is to use commands like
```
docker ps
docker inspect
docker logs
```
etc.
