### ISSUE TITLE
Why modify table TTL doesn't effect？

### ISSUE THREAD

**Issue by DaiDaDao** [ClickHouse/ClickHouse#9568]
I want to let my data auto expiry and delete， I use alter table TTL sql，like this

```
ALTER TABLE recom.mobile_hot_page_recom ON CLUSTER bigdata MODIFY TTL CAST(dateline / 1000, 'DateTime') + INTERVAL 3 DAY
```

my clickhouse version is 20.1

and now the table desc is :

```
CREATE TABLE recom.mobile_hot_page_recom (
  `uid` String,
  `actionCode` String,
  `rpos` String,
  `sub_rt` String,
  `userType` String,
  `rt` String,
  `dateline` UInt64,
  `minuteTime` Int64,
  `create_date` Date DEFAULT toDate(now())
) ENGINE = ReplicatedMergeTree(
  '/clickhouse/tables/{layer}-{shard}/mobile_hot_page_recom',
  '{replica}'
) PARTITION BY toYYYYMMDD(CAST(dateline / 1000, 'DateTime'))
ORDER BY
  dateline TTL CAST(dateline / 1000, 'DateTime') + toIntervalDay(3) SETTINGS index_granularity = 8192
```

I can see the TTL is setting seccuess on my table ,but when I search the data , the data what write by 3 days age is also can be searched,  and the partition active status is still 1.

Also try  OPTIMIZE  search and try change the TTL column from dateline cast-expression to create_data , both not work,  

Maybe I get something wrong with me use the TTL ,So I need help for how to let my data auto expiry.

Thank you very much for wathing,   I am looking forward to your reply！

**Comment by DaiDaDao** [comment]
I want to let my data auto expiry and delete，

**Comment by DaiDaDao** [comment]
Oh, I found the issue  [6462](https://github.com/ClickHouse/ClickHouse/issues/6462),maybe it can answer my question,

**Comment by excitoon** [comment]
Probably after you did ALTER TTL there were old parts which did not contain new information about TTL time. There is new functionality for `ALTER TABLE nnn MATERIALIZE TTL` introduced in #8775 in 20.3. Can you try it out?

**Comment by sunny19930321** [comment]
I have the same problem，Is there a good solution? @DaiDaDao

**Comment by blinkov** [comment]
@DaiDaDao, do you have any further questions?

**Comment by filimonov** [comment]
Check https://github.com/ClickHouse/ClickHouse/issues/8167#event-3488197913
