### ISSUE TITLE
macos cross-build cpp compiler -Werror not supported 

### ISSUE THREAD

**Issue by huiwang** [ClickHouse/ClickHouse#9571]
Building CH in MacOS locally fails due to warnings because warnings are considered as errors thanks to this option `-Werror`.However, the cross-build in the CI still passes because `-Werror` is not supported for cpp compiler. 

Example here (https://clickhouse-builds.s3.yandex.net/9538/6134a046cb1a20d3df527a0c3391e5ab98cf2673/build_log_624908327_1583513885.txt)

> -- Performing Test SUPPORTS_CXXFLAG_error
> -- Performing Test SUPPORTS_CXXFLAG_error - Failed
> -- Performing Test SUPPORTS_CFLAG_error
> -- Performing Test SUPPORTS_CFLAG_error - Success
> CMake Warning at cmake/add_warning.cmake:15 (message):
>   Flag -Werror is unsupported
> Call Stack (most recent call first):
>   CMakeLists.txt:240 (add_warning) 

But when I checked the option inside the docker (`docker/packager/binary/Dockerfile`) manually by compiling a simple file, this option is indeed supported. Someone else has already noticed this problem?

**Comment by alexey-milovidov** [comment]
@abyss7 Maybe checks are done by trying to compile and run the binary on the host system that is build for the target system (it will obviously fail).

**Comment by alexey-milovidov** [comment]
@huiwang by the way, as MacOS is a second class platform, we are Ok with not having -Werror enabled on that platform.

**Comment by huiwang** [comment]
@alexey-milovidov i understand MacOS is a second class platform and ignore some warnings is not big deals. But i still see the value of enable this flag. 

If it's really too hard to fix the issue, at least we can make it consistent between CI and local for Mac developers. 

For example, in CMakeList.txt here, we can change the check from `OS_LINUX OR OS_DARWIN` to `OS_LINUX OR` only.

```
if (UNBUNDLED OR NOT (OS_LINUX OR OS_DARWIN) OR ARCH_32)
    # Using system libs can cause a lot of warnings in includes (on macro expansion).
    option (WERROR "Enable -Werror compiler option" OFF)
else ()
    option (WERROR "Enable -Werror compiler option" ON)
endif ()```

**Comment by huiwang** [comment]
in the meantime, i continue the investigation. according the source code here, the program used to check flags seems to be platform independence.

https://github.com/Kitware/CMake/blob/master/Modules/CheckCXXCompilerFlag.cmake#L49
`  check_cxx_source_compiles("int main() { return 0; }" ${_var}`

however, as explained in the [doc](https://cmake.org/cmake/help/latest/module/CheckCXXCompilerFlag.html), it's possible to have false negatives. 
` Since the try_compile() command forwards flags from variables like CMAKE_CXX_FLAGS, unknown flags in such variables may cause a false negative for this check.`

**Comment by huiwang** [comment]
please note the flag is supported by the c compiler but not cpp.

**Comment by huiwang** [comment]
hello @abyss7, do you have some time to have a look? I'm trying to reproduce this behavior on my local machine with the binary packager.

**Comment by huiwang** [comment]
Here is the log of cmake with trace enabled. however, i can't find the reason why it failed :(
<pre>
/build/CMakeLists.txt(236):  option(WERROR Enable -Werror compiler option ON )
/build/CMakeLists.txt(239):  if(WERROR )
/build/CMakeLists.txt(240):  add_warning(error )
/build/cmake/add_warning.cmake(6):  string(REPLACE - _ underscored_flag error )
/build/cmake/add_warning.cmake(7):  string(REPLACE + x underscored_flag ${underscored_flag} )
/build/cmake/add_warning.cmake(9):  check_cxx_compiler_flag(-Werror SUPPORTS_CXXFLAG_${underscored_flag} )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(39):  set(SAFE_CMAKE_REQUIRED_DEFINITIONS ${CMAKE_REQUIRED_DEFINITIONS} )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(40):  set(CMAKE_REQUIRED_DEFINITIONS -Werror )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(43):  set(_CheckCXXCompilerFlag_LOCALE_VARS LC_ALL LC_MESSAGES LANG )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(44):  foreach(v ${_CheckCXXCompilerFlag_LOCALE_VARS} )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(45):  set(_CheckCXXCompilerFlag_SAVED_${v} $ENV{${v}} )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(46):  set(ENV{${v}} C )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(45):  set(_CheckCXXCompilerFlag_SAVED_${v} $ENV{${v}} )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(46):  set(ENV{${v}} C )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(45):  set(_CheckCXXCompilerFlag_SAVED_${v} $ENV{${v}} )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(46):  set(ENV{${v}} C )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(48):  CHECK_COMPILER_FLAG_COMMON_PATTERNS(_CheckCXXCompilerFlag_COMMON_PATTERNS )
/usr/share/cmake-3.10/Modules/CMakeCheckCompilerFlagCommonPatterns.cmake(10):  set(_CheckCXXCompilerFlag_COMMON_PATTERNS FAIL_REGEX [Uu]nrecogni[sz]ed .*option FAIL_REGEX unknown .*option FAIL_REGEX optimization flag .* not supported FAIL_REGEX unknown argument ignored FAIL_REGEX ignoring unknown option FAIL_REGEX warning D9002 FAIL_REGEX option.*not supported FAIL_REGEX invalid argument .*option FAIL_REGEX ignoring option .*argument required FAIL_REGEX ignoring option .*argument is of wrong type FAIL_REGEX [Uu]nknown option FAIL_REGEX [Ww]arning: [Oo]ption FAIL_REGEX command option .* is not recognized FAIL_REGEX command option .* contains an incorrect subargument FAIL_REGEX Option .* is not recognized.  Option will be ignored. FAIL_REGEX not supported in this configuration. ignored FAIL_REGEX File with unknown suffix passed to linker FAIL_REGEX [Uu]nknown switch FAIL_REGEX WARNING: unknown flag: FAIL_REGEX Incorrect command line option: FAIL_REGEX Warning: illegal option FAIL_REGEX [Ww]arning: Invalid suboption )
/usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake(49):  CHECK_CXX_SOURCE_COMPILES(int main() { return 0; } SUPPORTS_CXXFLAG_error FAIL_REGEX command line option .* is valid for .* but not for C\\\\+\\\\+ ${_CheckCXXCompilerFlag_COMMON_PATTERNS} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(64):  if(NOT DEFINED SUPPORTS_CXXFLAG_error )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(65):  set(_FAIL_REGEX )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(66):  set(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(67):  foreach(arg FAIL_REGEX;command line option .* is valid for .* but not for C\\+\\+;FAIL_REGEX;[Uu]nrecogni[sz]ed .*option;FAIL_REGEX;unknown .*option;FAIL_REGEX;optimization flag .* not supported;FAIL_REGEX;unknown argument ignored;FAIL_REGEX;ignoring unknown option;FAIL_REGEX;warning D9002;FAIL_REGEX;option.*not supported;FAIL_REGEX;invalid argument .*option;FAIL_REGEX;ignoring option .*argument required;FAIL_REGEX;ignoring option .*argument is of wrong type;FAIL_REGEX;[Uu]nknown option;FAIL_REGEX;[Ww]arning: [Oo]ption;FAIL_REGEX;command option .* is not recognized;FAIL_REGEX;command option .* contains an incorrect subargument;FAIL_REGEX;Option .* is not recognized.  Option will be ignored.;FAIL_REGEX;not supported in this configuration. ignored;FAIL_REGEX;File with unknown suffix passed to linker;FAIL_REGEX;[Uu]nknown switch;FAIL_REGEX;WARNING: unknown flag:;FAIL_REGEX;Incorrect command line option:;FAIL_REGEX;Warning: illegal option;FAIL_REGEX;[Ww]arning: Invalid suboption )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(69):  set(_key ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(68):  if(${arg} MATCHES ^(FAIL_REGEX)$ )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(70):  elseif(_key )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(71):  list(APPEND _${_key} ${arg} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(77):  set(MACRO_CHECK_FUNCTION_DEFINITIONS -DSUPPORTS_CXXFLAG_error ${CMAKE_REQUIRED_FLAGS} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(79):  if(CMAKE_REQUIRED_LIBRARIES )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(82):  else()
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(83):  set(CHECK_CXX_SOURCE_COMPILES_ADD_LIBRARIES )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(85):  if(CMAKE_REQUIRED_INCLUDES )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(88):  else()
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(89):  set(CHECK_CXX_SOURCE_COMPILES_ADD_INCLUDES )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(91):  file(WRITE ${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/src.cxx int main() { return 0; }\n )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(94):  if(NOT CMAKE_REQUIRED_QUIET )
-- Performing Test SUPPORTS_CXXFLAG_error
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(95):  message(STATUS Performing Test SUPPORTS_CXXFLAG_error )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(97):  try_compile(SUPPORTS_CXXFLAG_error ${CMAKE_BINARY_DIR} ${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/src.cxx COMPILE_DEFINITIONS ${CMAKE_REQUIRED_DEFINITIONS} ${CHECK_CXX_SOURCE_COMPILES_ADD_LIBRARIES} CMAKE_FLAGS -DCOMPILE_DEFINITIONS:STRING=${MACRO_CHECK_FUNCTION_DEFINITIONS} ${CHECK_CXX_SOURCE_COMPILES_ADD_INCLUDES} OUTPUT_VARIABLE OUTPUT )
CMake Warning (dev) at /usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake:97 (try_compile):
  Policy CMP0066 is not set: Honor per-config flags in try_compile()
  source-file signature.  Run "cmake --help-policy CMP0066" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  For compatibility with older versions of CMake, try_compile is not honoring
  caller config-specific compiler flags (e.g.  CMAKE_C_FLAGS_DEBUG) in the
  test project.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake:49 (CHECK_CXX_SOURCE_COMPILES)
  cmake/add_warning.cmake:9 (check_cxx_compiler_flag)
  CMakeLists.txt:240 (add_warning)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake:97 (try_compile):
  Policy CMP0067 is not set: Honor language standard in try_compile()
  source-file signature.  Run "cmake --help-policy CMP0067" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  For compatibility with older versions of CMake, try_compile is not honoring
  language standard variables in the test project:

    CMAKE_CXX_STANDARD_REQUIRED
    CMAKE_CXX_EXTENSIONS

Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/CheckCXXCompilerFlag.cmake:49 (CHECK_CXX_SOURCE_COMPILES)
  cmake/add_warning.cmake:9 (check_cxx_compiler_flag)
  CMakeLists.txt:240 (add_warning)
This warning is for project developers.  Use -Wno-dev to suppress it.

/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(106):  foreach(_regex ${_FAIL_REGEX} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(107):  if(${OUTPUT} MATCHES ${_regex} )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(112):  if(SUPPORTS_CXXFLAG_error )
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(121):  else()
/usr/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake(122):  if(NOT CMAKE_REQUIRED_QUIET )
-- Performing Test SUPPORTS_CXXFLAG_error - Failed

</pre>

**Comment by huiwang** [comment]
finally, i found out why. it's due to the following error

<pre>
Performing C++ SOURCE FILE Test SUPPORTS_CXXFLAG_error failed with the following output:
Change Dir: /build/build_docker/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_20d5b"
[1/2] Building CXX object CMakeFiles/cmTC_20d5b.dir/src.cxx.o
FAILED: CMakeFiles/cmTC_20d5b.dir/src.cxx.o
/usr/bin/clang++-8 --target=x86_64-apple-darwin    -std=c++17 -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -gdwarf-aranges -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall -Wno-unused-command-line-argument  -Wnon-virtual-dtor -fno-omit-frame-pointer -Wl,-U,_inside_main -DSUPPORTS_CXXFLAG_error -isysroot /build/cmake/toolchain/darwin-x86_64   -Werror -o CMakeFiles/cmTC_20d5b.dir/src.cxx.o -c src.cxx
error: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
1 error generated.
ninja: build stopped: subcommand failed.

Source file was:
int main() { return 0; }
</pre>

@alexey-milovidov could you please review #9665 and run the CI? Now I expect the build job to fail because warnings will be considered as errors and there are indeed warnings in ThreadFuzzer.
if the assumption is validated, i'll then fix the warnings.

**Comment by huiwang** [comment]
fixed in the pr mentioned above.
