### ISSUE TITLE
Clickhouse does not work on Windows for Linux subsystem

### ISSUE THREAD

**Issue by serak** [ClickHouse/ClickHouse#9578]
(you don't have to strictly follow this form)

**Use case**
most developer around the world use windows as a development environment and its sad to see these platform not supported 

**Describe the solution you'd like**
it should work on windows  os or either Linux for windows 

**Describe alternatives you've considered**
Linux for windows support on Ubuntu 18 LTS

**Additional context**

**Comment by filimonov** [comment]
That is not officially supported but we know it should be possible. See:
https://github.com/ClickHouse/ClickHouse/issues/6480

ClickHouse is an open-source project, if you have some experience & goodwill - please
participate, you can become a supporter of ClickHouse on WSL. :)

**Comment by den-crane** [comment]
probably it's fixed in the master two days ago. Try testing release https://github.com/ClickHouse/ClickHouse/releases which will be publish tomorrow or day after tomorrow

**Comment by Relecto** [comment]
Can confirm that after upgrading clickhouse-client from 20.1.3.7 to 20.3.2.1 on wsl ubuntu it began working just fine, thanks!

**Comment by serak** [comment]
@Relecto is have tested the latest release. same issue. here is the screenshot
![image](https://user-images.githubusercontent.com/3592372/76675767-0af94c80-65ce-11ea-8cb7-c0694dc71da1.png)

**Comment by den-crane** [comment]
@serak did setup password during CH installation? Then you should use this password with clickhouse-client.

Or you can remove a file /etc/clickhouse-server/users.d/default-password.xml

**Comment by serak** [comment]
thanks its working now, clickhouse must include this post install configuration step on the quick manual :)

![image](https://user-images.githubusercontent.com/3592372/76757748-409e6100-6799-11ea-9518-828aa48f0264.png)

**Comment by filimonov** [comment]
Thanks for confirming!
