### ISSUE TITLE
19.16+ Exception in FULL JOIN on a LowCardinality column

### ISSUE THREAD

**Issue by SaltTan** [ClickHouse/ClickHouse#9601]
How to reproduce:
```
CREATE TABLE left 
(
  lc   LowCardinality(String)
)
ENGINE = Memory;

CREATE TABLE right 
(
  lc   LowCardinality(String)
)
ENGINE = Memory;

insert into right values ('FNRNaHOZUErO');

SELECT * FROM left FULL JOIN right USING (lc)
```
19.13.7
```
┌─lc───────────┐
│ FNRNaHOZUErO │
└──────────────┘
1 rows in set. Elapsed: 0.002 sec.
```
19.16.14
Received exception from server (version 19.16.14):
Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (for query) exceeded: would use 128.00 TiB (attempt to allocate chunk of 140737488355544 bytes), maximum: 47.03 GiB.

20.1.6
Exception on client:
Code: 271. DB::Exception: Data compressed with different methods, given method byte 69, previous method byte 82: while receiving packet from localhost:9000

**Comment by jackpgao** [comment]
same problem
