### ISSUE TITLE
Cannot parse string '1103138‬' as Float64

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#9614]
What is this mean?

**Comment by ShadowDAssange** [comment]
The string '1103138' can't be parsed as Float64 ?

**Comment by YiuRULE** [comment]
Not sure exactly which string you send, but `select toFloat64('1103138‬‬')` return the correct output

**Comment by ShadowDAssange** [comment]
I have fixed this.
`insert into .. select (MySQL)`
Caused by MySQL field type error
