### ISSUE TITLE
ALTER TABLE DELETE and free disk space

### ISSUE THREAD

**Issue by tetafro** [ClickHouse/ClickHouse#9627]
I run a delete query on a big table
```sql
ALTER TABLE t DELETE WHERE field = 'x'
```

After that free space on sever started to decrease very fast. I had to kill a mutation using
```sql
KLLL MUTATION WHERE mutation_id = '0000000000'
```

The disk space remained on the same level. Is there any temporary files that can be deleted to free space, and is there a way to not use all the disk on delete operation?

**Comment by den-crane** [comment]
Mutations book a disk space of twice time of parts size to be mutated. Because mutations write mutated parts to new files and delete old files. Disk space will be freed on the end of mutations (after 8 minutes after mutations finish).
