### ISSUE TITLE
Possible deadlock with concurrent "create table" and "select * system.tables"

### ISSUE THREAD

**Issue by krakozabrik** [ClickHouse/ClickHouse#9630]
When concurrent "creat table" and "select from system.tables", I get an error.
version 19.17.4.11 (official build)

`DB::ExceptionDB::Exception: Possible deadlock avoided. Client should retry.. `

**Comment by alesapin** [comment]
It's OK, just retry your query as message clearly says.

**Comment by filimonov** [comment]
https://github.com/ClickHouse/ClickHouse/issues/9637#issuecomment-599651023
