### ISSUE TITLE
please make table lines align in Chinese doc

### ISSUE THREAD

**Issue by l1t1** [ClickHouse/ClickHouse#9681]
(you don't have to strictly follow this form)

**Describe the issue**
in Chinese doc, some parts of the content of a table shows in colors, this leads to the lines not align,
while in English doc, all contents of a table in black, and it shows align. 

eg.
the table above "Virtual Columns"

English 
![2020-03-16_195119](https://user-images.githubusercontent.com/23301704/76756699-2d06f080-67c1-11ea-90a5-835133b87bec.png)

Chinese 

![2020-03-16_195137](https://user-images.githubusercontent.com/23301704/76756727-3c863980-67c1-11ea-9d1c-dd042e53a2df.png)

**Comment by alexey-milovidov** [comment]
It looks like that SQL highlighter is used despite the fact these examples contains not only the SQL query but also the results. Example: https://clickhouse.tech/docs/zh/query_language/select/

**Comment by hczhcz** [comment]
Your web browser supports sub-pixel character width. But it does not calculate the width of `<span>` in the same way.

**Comment by l1t1** [comment]
i compared the pdfs, not webpages
namely
https://clickhouse.tech/docs/zh/single/clickhouse_zh.pdf page 149
and
https://clickhouse.tech/docs/en/single/clickhouse_en.pdf page 151
and i tried many pdf readers, they all shows the same results.

**Comment by l1t1** [comment]
and tables of the webpages are all align. 
https://clickhouse.tech/docs/en/operations/table_engines/merge/
all contents are in blcaks
https://clickhouse.tech/docs/zh/operations/table_engines/merge/
some parts of the contents are in colors

**Comment by blinkov** [comment]
I think I have accidentally fixed this.

**Comment by l1t1** [comment]
i think the old pdf is better than the new pdf
both the lines and the Chinese character of new pdf are unreadable   
new
![new_pdf2020-04-04_161059](https://user-images.githubusercontent.com/23301704/78422179-10f3c200-7690-11ea-8cd5-c9886f7f9ffc.png)
old
![old_pdf2020-04-04_161032](https://user-images.githubusercontent.com/23301704/78422187-24069200-7690-11ea-8f0f-ffc970854cc6.png)

**Comment by l1t1** [comment]
and the old English pdf is also better than new
new English
![new_en2020-04-04_163619](https://user-images.githubusercontent.com/23301704/78422570-c6277980-7692-11ea-8079-d77d38d7bf1a.png)
old English 
![old_en2020-04-04_163555](https://user-images.githubusercontent.com/23301704/78422579-d7708600-7692-11ea-8350-00e2c07cf078.png)

**Comment by l1t1** [comment]
please restore tha fonts of pdf

(you don't have to strictly follow this form)

**Describe the issue**
the new font isnt well readable. espsially UKaiCN, and the font for scripts and codes

the fonts of the pdf  file in Mar 18.
the fonts of the pdf file in Apr 9.
