### ISSUE TITLE
replica password in metrika.xml and password in user.xml

### ISSUE THREAD

**Issue by ShadowDAssange** [ClickHouse/ClickHouse#9697]
I changed `<password>password</password>` to `<password_sha256_hex>password_sha256_hex</password_sha256_hex>`

Then I found that Whether  the replica password  changed, It does not affect replication

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/operations/server_settings/settings/#server-settings-interserver_http_credentials

interserver_http_credentials -- config.xml

**Comment by ShadowDAssange** [comment]
Another problem.
But the replica password in metrica.xml is still been password, not password_sha256_hex.
I edit metrica.xml like this:
```
                 <replica>
                     <host>host1</host>
                     <port>9000</port>
                     <user>root</user>
                     <password>password_sha256_hex</password>
                 </replica>
```
This didn't work;
```
                 <replica>
                     <host>host1</host>
                     <port>9000</port>
                     <user>root</user>
                     <password>password</password>
                 </replica>
```
This works.

**Comment by filimonov** [comment]
you need to know the real password to login to clickhouse. 
ClickHouse also needs to know the real password to login to another clickhouse.

To check if the password which arrived from the client is correct `password_sha256_hex` in enough.

I.e. server-part can have a password or password hash, but the client part needs plain password..

**Comment by den-crane** [comment]
https://github.com/ClickHouse/ClickHouse/issues/2290#issuecomment-384790034
