### ISSUE TITLE
how to make MATERIALIZED VIEW update automatically when several origin-tables were inserted

### ISSUE THREAD

**Issue by zhouxiujue** [ClickHouse/ClickHouse#9701]
Create two origin-tables with only two fields, associated by id：
```
CREATE TABLE default.test0 (
`id` String,
 `name` String
) ENGINE = MergeTree PARTITION BY id ORDER BY id SETTINGS index_granularity = 8192

CREATE TABLE default.test00 (
`id` String,
 `name2` String
) ENGINE = MergeTree PARTITION BY id ORDER BY id SETTINGS index_granularity = 8192
```
create the MATERIALIZED VIEW：
```
create  MATERIALIZED VIEW default.test_view  ENGINE = MergeTree PARTITION BY id ORDER BY id SETTINGS index_granularity = 8192
AS select t0.id,name,name2 from `default`.test0 t0 join `default`.test00 t00 on t0.id=t00.id
```
Insert into origin-tables，test0 and test00：
```
insert into `default`.test0 values ('1','name1')

insert into `default`.test00 values ('1','name10')
```
then select from the view：
`select * from default.test_view `

but the resultset is empty.

> id|name|name2|
> --|----|-----|

But if I create a 'MATERIALIZED VIEW' for a single table, the view can auto update after the single table was inserted.like:
```
create  MATERIALIZED VIEW default.test_view0  ENGINE = MergeTree PARTITION BY id ORDER BY id SETTINGS index_granularity = 8192
AS select  id,name FROM `default`.test0 
```

Please tell me how to make the MATERIALIZED VIEW update automatically after origin-tables were inserted?  Thank you!

**Comment by filimonov** [comment]
Materialiezed view is updated when new block of data is inserted in the left-most table. 
You can think about that as AFTER INSERT trigger.

> after origin-tables were inserted

ClickHouse can't know if you already finish inserting or plan to insert more. 

You can just fire `INSERT INTO target_table SELECT .... FROM src_table1 LEFT JOIN src_table2  where condition`

**Comment by zhouxiujue** [comment]
Thank you！
