### ISSUE TITLE
Cannot allocate block number in ZooKeeper

### ISSUE THREAD

**Issue by InasaXia** [ClickHouse/ClickHouse#9703]
Suddenly，it came out this.
In java Application's log:
`DB::Exception: Cannot allocate block number in ZooKeeper: Coordination::Exception: Connection loss`
and
`No route to host (Host unreachable)`

In clickhouse's log:
`DB::Exception: Cannot allocate block number in ZooKeeper: Coordination::Exception: Connection loss (version 19.16.2.2 (official build))`
` Coordination::Exception: Session expired (Session expired)`
`ZooKeeper session has expired. Switching to a new session.`

This phenomenon only occurs for a period of time

**Comment by filimonov** [comment]
It look like some issue with zookeeper, or with connection zookeeper - clickhouse. 

May be you run zookeeper and clickhouse on the same server?

**Comment by ShadowDAssange** [comment]
Yes. What happens if I run zookeeper and clickhouse on the same server?
I didn't find the CPU and memory abnormal.

**Comment by Mango-Hu** [comment]
I got the same problem like you，it came out suddenly this morning。
logs: 
DB::Exception: Cannot allocate block number in ZooKeeper: Coordination::Exception: Connection loss (version 19.7.5.27)
The error may involve defaultParameterMap
The error occurred while setting parameters
SQL: INSERT INTO ...

**Comment by Mango-Hu** [comment]
> I got the same problem like you，it came out suddenly this morning。
> logs:
> DB::Exception: Cannot allocate block number in ZooKeeper: Coordination::Exception: Connection loss (version 19.7.5.27)
> The error may involve defaultParameterMap
> The error occurred while setting parameters
> SQL: INSERT INTO ...

There is something wrong with my Zookeeper , they are all unavailable.

**Comment by blinkov** [comment]
@InasaXia, do you have any further questions?

**Comment by KelovpString** [comment]
I got the same problem, I already checked my Zookeeper cluster.It's work,but the click-cluster some ck-server throw this error. How to check this problem? It must be Zookeeper's error?

**Comment by smedoji** [comment]
Facing the same problem. Also observed that this is happening with only one specific distributed table. The zookeeper is good and I don't see any errors at that instance.

**Comment by KelovpString** [comment]
Thanks Reply
Yes, After many times cheked, this is happening with only one specific distributed table,so just rebuild table or create the  duplicate table to solve this problem.At the same time, I also noticed that most of the ZK related errors can be fixed by rebuilding, which often occurs in distributed tables. It may be necessary to delete the wrong metadata from the node directory of ZK, so that the error data can be completely cleaned up. Of course, the specific error must be analyzed and solved by the specific error log.

**Comment by smedoji** [comment]
We are now observing the same issue on different distributed tables of the same cluster. While inserting data we are getting this error randomly and job fails. Next when we try to drop the partition, that command just hangs and doesn't do anything. Not sure if both are related. 

Any help from devs would be great.

**Comment by Jokser** [comment]
I've faced the same problem and it was related to request throttling on ZK side due to the high load.
Try to set property `zookeeper.globalOutstandingLimit` to higher values for ZK servers (default is 1000).
