### ISSUE TITLE
issue with postinstall script on ubuntu 16

### ISSUE THREAD

**Issue by VonShtirlitz** [ClickHouse/ClickHouse#9706]
**Describe the bug**
Broken Ubuntu 16 installation

**How to reproduce**
sudo apt-get install clickhouse-client clickhouse-server

* Which ClickHouse server version to use
20.3.3.6

**Expected behavior**
creates /nonexistent vs /var/lib/clickhouse/

**Error message and/or stacktrace**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  clickhouse-common-static
Suggested packages:
  clickhouse-common-static-dbg
The following NEW packages will be installed:
  clickhouse-client clickhouse-common-static clickhouse-server
0 upgraded, 3 newly installed, 0 to remove and 30 not upgraded.
Need to get 117 MB of archives.
After this operation, 394 MB of additional disk space will be used.
Do you want to continue? [Д/н] y
Get:1 http://repo.clickhouse.tech/deb/stable main/ clickhouse-common-static 20.3.3.6 [116 MB]
Get:2 http://repo.clickhouse.tech/deb/stable main/ clickhouse-client 20.3.3.6 [126 kB]                                                                          
Get:3 http://repo.clickhouse.tech/deb/stable main/ clickhouse-server 20.3.3.6 [142 kB]                                                                          
Fetched 117 MB in 6s (17,5 MB/s)                                                                                                                                
Preconfiguring packages ...
Selecting previously unselected package clickhouse-common-static.
(Reading database ... 111973 files and directories currently installed.)
Preparing to unpack .../clickhouse-common-static_20.3.3.6_amd64.deb ...
Unpacking clickhouse-common-static (20.3.3.6) ...
Selecting previously unselected package clickhouse-client.
Preparing to unpack .../clickhouse-client_20.3.3.6_all.deb ...
Unpacking clickhouse-client (20.3.3.6) ...
Selecting previously unselected package clickhouse-server.
Preparing to unpack .../clickhouse-server_20.3.3.6_all.deb ...
Unpacking clickhouse-server (20.3.3.6) ...
Processing triggers for systemd (229-4ubuntu21.27) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Setting up clickhouse-common-static (20.3.3.6) ...
Setting up clickhouse-client (20.3.3.6) ...
Setting up clickhouse-server (20.3.3.6) ...
ClickHouse init script has migrated to systemd. Please manually stop old server and restart the service: sudo killall clickhouse-server && sleep 5 && sudo service clickhouse-server restart
Synchronizing state of clickhouse-server.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable clickhouse-server
Path to data directory in /etc/clickhouse-server/config.xml: /var/lib/clickhouse/
Creating directory '/nonexistent'.
/var/lib/dpkg/info/clickhouse-server.postinst: 86: [: /var/lib/clickhouse/: unexpected operator
ln: target '/etc/clickhouse-server/preprocessed' is not a directory
Processing triggers for systemd (229-4ubuntu21.27) ...
Processing triggers for ureadahead (0.100.0-19.1) ...

**Comment by filimonov** [comment]
Is it really Ubuntu 16? 

can you show the contents of `/etc/debian_version` ?

https://github.com/ClickHouse/ClickHouse/blob/7aca050684e7cedce0549bc6724fa41eb397806b/debian/clickhouse-server.postinst#L46-L47

And I'm not sure what is happening on the line 86.
We can add quotes around $CLICKHOUSE_DATADIR_FROM_CONFIG but it looks correct as is.

**Comment by filimonov** [comment]
Tried on fresh VM:

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

ANd it's working.

**Comment by VonShtirlitz** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

cat /etc/debian_version
stretch/sid

**Comment by VonShtirlitz** [comment]
mkdir /var/lib/clickhouse
chown -R clickhouse:clickhouse /var/lib/clickhouse
sudo apt-get uninstall clickhouse-client clickhouse-server
sudo apt-get remove clickhouse-client clickhouse-server

and now it's working

**Comment by filimonov** [comment]
Can you review the post-install script? Can you see what's went wrong in your case?

**Comment by VonShtirlitz** [comment]
![image](https://user-images.githubusercontent.com/10995977/77055931-bf3a0f00-69e2-11ea-8981-cf41eb16af5b.png)

I looked into the postinstall code and also did not find a problem. Сlean installation showed that everything is ok. most likely a problem elsewhere.

close the issue
