### ISSUE TITLE
ALTER TABLE table_name slows when comes across many partitions.

### ISSUE THREAD

**Issue by wangzhen11aaa** [ClickHouse/ClickHouse#9722]
**Describe the situation**
What exactly works slower than expected?

When I execute the query like `ALTER TABLE table_name DELETE where dt='2020-02-03' and column_x in()`  where the dt is date type and used as parittion column.  The table uses ReplicatedMergeTree Engine. The most effecient way to process this sql query is to generate the mutation which only update the partition related. But the clickhouse actually will update the partitions with adding the mutation_versions +1. In this condition, the server will be slower when the partitions gets more.

**How to reproduce**

```sql
ALTER TABLE table_name DELETE where dt='2020-02-03' and column_x in() 
```

* Which ClickHouse server version to use
Version Clickhouse 19.8.3

* Which interface to use, if matters
void ReplicatedMergeTreeQueue::updateMutations.

The line which looks buggy is in
https://github.com/ClickHouse/ClickHouse/blob/48a2b46499300d2ab2b8d1302e8ab45feb20fa57/dbms/src/Storages/MergeTree/ReplicatedMergeTreeQueue.cpp#L602-L603

** Queries to run that lead to slow performance **
```sql
ALTER TABLE table_name DELETE where dt='2020-02-03' and column_x in().
```

You will see this phenomenon from the information from the local_directory and mutations child.

**Expected performance**
The most efficient way to process this SQL query is to generate the mutation which only updates the partition related.

**Comment by wangzhen11aaa** [comment]
Use zk-shell
/.../mutations/ 
get  0000077325
format version: 1
create time: 2020-03-18 13:45:02
source replica: cluster01-01-6
block numbers count: 478
19700823	77327
19840414	77331
20181101	72955
20181102	68951
20181201	79785
20181202	79450
20181203	78277
20181204	77593
20181205	79117
20181206	80467
20181207	78621
20181208	77570
20181209	79029
20181210	80616
20181211	79432
20181212	78049
20181213	79995
20181214	80461
20181215	79479
20181216	78935
20181217	80057
20181218	80537
20181219	80994
20181220	80368
20181221	80516
20181222	80263
20181223	81054
20181224	80374
20181225	80356
20181226	81062
20181227	80556
20181228	80407
20181229	80222
20181230	80700
20181231	79576
20190101	79705
20190102	79975
20190103	80085
20190104	80221
20190105	79802
20190106	81763
20190107	80981
20190108	81071
20190109	80496
20190110	81948
20190111	80653
20190112	79875
20190113	80768
20190114	80518
20190115	80382
20190116	80137
20190117	80001
20190118	80175
20190119	79954
20190120	80236
20190121	79648
20190122	79710
20190123	79704
20190124	79694
20190125	79292
20190126	78963
20190127	78957
20190128	78689
20190129	78908
20190130	78766
20190131	78583
20190201	78116
20190202	77907
20190203	77653
20190204	77469
20190205	77548
20190206	77607
20190207	77812
20190208	77915
20190209	78018
20190210	78302
20190211	78829
20190212	79054
20190213	79153
20190214	79384
20190215	79718
20190216	79435
20190217	79421
20190218	79616
20190219	79553
20190220	80125
20190221	80267
20190222	79988
20190223	79775
20190224	80124
20190225	80393
20190226	80436
20190227	80125
20190228	79913
20190301	80464
20190302	80271
20190303	80299
20190304	80077
20190305	80976
20190306	81354
20190307	80802
20190308	78457
20190309	78988
20190310	79982
20190311	79655
...
20200318 xxx
-----------------------------------
Execute the Shell script.
find ./ -type d -mmin +120|sort
And the partition names's mutation is something like this:
 /20190311_1553_2036_4_79655
./20190311_2037_2309_4_79655
./20190311_2310_2328_2_79655
./20190312_1556_2055_4_79657
./20190312_2056_2307_4_79657
./20190312_2308_2330_2_79657
./20190313_1615_2131_4_79747
./20190313_2132_2420_4_79747

You will see that the parition is only updated on the 20190311 partition. And I already get the latest mutation entry 0000077456 which is 104  larger than 0000077325. That is the problem.

**Comment by den-crane** [comment]
>But the clickhouse actually will update the partitions with adding the mutation_versions +1

CH always mutates and adds the mutation_versions +1 **to ALL PARTS.**
New versions / new parts are created for alll parts using **HARDLINKS**
Only new parts those  match `where dt='2020-02-03'` will be re-written by file read/file write.

**Comment by wangzhen11aaa** [comment]
> > But the clickhouse actually will update the partitions with adding the mutation_versions +1
> 
> CH always mutates and adds the mutation_versions +1 **to ALL PARTS.** (consistency requirement)
> New versions / new parts are created for alll parts using **HARDLINKS**
> Only new parts those match `where dt='2020-02-03'` will be re-written by file read/file write.

I know that, But when there are a lot parts and ddl is frequent (there may be hundred of thousands of add action), It will slow the ddl. It may have some improvements in the future.
