### ISSUE TITLE
Constant propagation for JOINs.

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickHouse#9733]
**Describe the situation**
```
SELECT a.*, b.*
FROM 
    (SELECT ...) a 
    INNER JOIN 
    (SELECT ...) b
    ON a.k = b.k
WHERE a.k = 123
```

We should automatically derive that `b.k = 123` and pushdown the condition into `b` table.

**Comment by Algunenano** [comment]
It's done https://github.com/ClickHouse/ClickHouse/pull/61216
