### ISSUE TITLE
about implementation of data replication

### ISSUE THREAD

**Issue by peaksnail** [ClickHouse/ClickHouse#9741]
hi 
  I have some questions about the data replication when try to use ReplicatedMergeTree these days

  why use the ReplicatedMergeTree to implement data replication, but not apply shielding to upper layers, like the data shard. We just do some configuration  and It will replicate data depends on the configuration
 
 Could you share how you thought about it? thanks

**Comment by den-crane** [comment]
CH has specific design -- all nodes are independent without the singe point of failure so nodes has zero knowledge about other nodes. 
ReplicatedMT knows nothing about a sharding and knows how to publish information about its parts using ZK. 
All shards ReplicatedMT are different tables.

**Comment by alexey-milovidov** [comment]
It's also worth to note that replication is implement on per-table basis.
For example, you can have one table replicated three times, other table replicated ten times and other table not replicated at all.
