### ISSUE TITLE
DB::Exception: mysqlxx::BadQuery: Unknown column 'external_table' in 'where clause'

### ISSUE THREAD

**Issue by TimonKK** [ClickHouse/ClickHouse#9756]
I have table `m_test` in mariadb server and clickhouse table `ch_test` with ENGINE=MySQL, which looks at `m_test`.

When I make query with [external data](https://clickhouse.tech/docs/en/operations/table_engines/external_data/)  like this
```sql
SELECT
 *
FROM other_ch_table AS i 
LEFT JOIN (
  SELECT
    *
  FROM ch_test
  WHERE id IN external_table
) AS n ON(n.id = i.id)
```
I have error
Code: 1000. DB::Exception: Received from 127.0.0.1:9000. DB::Exception: mysqlxx::BadQuery: Unknown column 'external_table' in 'where clause' (127.0.0.1:3306).

But if I change query to
```sql
SELECT
 *
FROM other_ch_table AS i 
LEFT JOIN (
  SELECT
    *
  FROM ch_test
  WHERE id IN (SELECT id FROM external_table)
) AS n ON(n.id = i.id)
```
error disappear.

This error appear after upgrade 20.1.2.4 to 20.3.3.6.

Versions:
- mariadb server 10.2.7-MariaDB-10.2.7+maria~jessie-log
- clickhouse 20.3.3.6

**Comment by ShonT** [comment]
Facing a similar issue  
Code: 1000. DB::Exception: Received from localhost:9000. DB::Exception: mysqlxx::BadQuery
The query below was working on version 19.16.14.65 but not on 20.3.12.112 The latest Altinity LTS

`select mysql_db.a_table.geo_region_id,
       mysql_db.a_table.domain_id,
       mysql_db.b_table.name,
       mysql_db.b_table.a_column,
       mysql_db.c_table.list_id

from mysql_db.a_table
         inner join
     mysql_db.b_table
     on mysql_db.a_table.domain_id = mysql_db.b_table.id
         and mysql_db.a_table.geo_region_id = toInt64(999)
         inner join
     mysql_db.c_table
     on mysql_db.c_table.a_column = mysql_db.b_table.a_column
where mysql_db.a_table.geo_region_id =999
  and mysql_db.c_table.list_id = 126`

The below query now works 


```
select mysql_db.a_table.geo_region_id,
       mysql_db.a_table.domain_id,
       mysql_db.b_table.name,
       mysql_db.b_table.a_column,
       mysql_db.c_table.list_id

from mysql_db.a_table
         inner join
     mysql_db.b_table
     on mysql_db.a_table.domain_id = mysql_db.b_table.id
         and mysql_db.a_table.geo_region_id = toInt64(999)
         inner join
     mysql_db.c_table
     on mysql_db.c_table.a_column = mysql_db.b_table.a_column
where mysql_db.c_table.list_id = 126
```

 
Something that would be helpful is if Can I see the aliased query that is being run on MySQL from clickhouse.
