### ISSUE TITLE
Add INFORMATION_SCHEMA database

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#9770]
to satisfy (at least some) of SQL92 requirements:

http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt

We can easily fill those from system:
21.2.4  SCHEMATA view
21.2.7  TABLES view
21.2.8  VIEWS view
21.2.9  COLUMNS view

Rest - should be reviewed, we can fill (where possible), skip or create empty.
 
And that should allow to improve SQL 92 compatibility and fix issues like
https://github.com/ClickHouse/ClickHouse/issues/9769
https://github.com/ClickHouse/ClickHouse/issues/9336 (partially)

The problematic part here is the case insensitivity of those.

**Comment by alexey-milovidov** [comment]
I put this comment to indicate that this feature is nice to have...
