### ISSUE TITLE
DROP TABLE causes strange queries rebalancing

### ISSUE THREAD

**Issue by tetafro** [ClickHouse/ClickHouse#9776]
Setup:

- version: 19.9.3.31;
- 4 nodes cluster: 2 slow (hdd) and 2 fast (ssd);
- applications write to slow nodes, read from fast nodes;
- all tables are replicated + distributed (2 replicas, 2 shards);
- distributed tables are used for all selects/inserts with [in_order](https://clickhouse.tech/docs/en/operations/settings/settings/#load_balancing-in_order) load balancing, fast nodes are in priority.

After `table drop` (on a table which is not currently used by anybody) clickhouse starts sending select queries from distributed tables to slow nodes for a while. It looks like this:

![pic](https://user-images.githubusercontent.com/11755173/77160713-02ff4800-6ab9-11ea-8646-2ef006927d6c.png)

Green and blue - slow nodes, orange and red - fast.

At the same time insert rate per node does not change.

This happens only for tables that were under read/write load for some time. It's not happening for empty tables.

Not sure what debug info can I add. I see nothing suspicious in logs or clickhouse metrics.

**Comment by filimonov** [comment]
Is it possible that the table you dropped was used by some distibuted tables?

**Comment by tetafro** [comment]
First I drop distributed table and materialized view trigger who writes in this table (if there is any), and only then I drop the table itself.
Maybe dropping distributed tables and views is async operation and should check somewhere that it is complete?

**Comment by den-crane** [comment]
Drop MT table causes `mark cache dropping`. Probably cache invalidation causes queries timeouts and Distributed table switches to other replica.

**Comment by tetafro** [comment]
I tried to manually drop cache using `SYSTEM DROP MARK CACHE`, and it didn't affect cluster that much.

---

I will try to update clickhouse and check if the issue remains.
