### ISSUE TITLE
Date Filter not work on less than

### ISSUE THREAD

**Issue by mbtolou** [ClickHouse/ClickHouse#9793]
Hi,
DateTime between not work correctly.

https://github.com/ClickHouse/ClickHouse/releases/tag/v20.3.4.10-stable

```sql
CREATE TABLE TESTDB.TAB_DATE100 (
`SERVER_ID` Int32,
 `TV` DateTime
) ENGINE =  MergeTree PARTITION BY toYYYYMM(TV) ORDER BY (SERVER_ID) SETTINGS index_granularity = 8192;




set max_partitions_per_insert_block=1000000;

INSERT into TESTDB.TAB_DATE100
SELECT 
	number%3 as SERVER_ID,
	toDateTime(addHours(toDate('2019-01-01'),number)) as TV
from numbers(100000);
```

```sql
select max(TV),min(TV)
from TESTDB.TAB_DATE100;
--2030-05-29 00:00:00	2019-01-01 00:00:00
```

👍 
```
select *
from TESTDB.TAB_DATE100
where TV > toDate('2020-01-01');
```

❌ 
```
select *
from TESTDB.TAB_DATE100
where TV < toDate('2020-01-01');
```

❌ 
```sql
select *
from TESTDB.TAB_DATE100
where TV BETWEEN toDate('2020-01-01') and toDate('2020-03-01');
```

**Comment by mbtolou** [comment]
SELECT *
FROM TEST.POWER AS bpdct
WHERE (TV >= toDate('2020-01-01')) AND (TV <= toDate('2020-03-01'))

[srv-TEST01] 2020.03.21 13:43:04.877440 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Debug> executeQuery: (from [::ffff:127.0.0.1]:33486) SELECT * FROM TEST.POWER AS bpdct WHERE (TV >= toDate('2020-01-01')) AND (TV <= toDate('2020-03-01'))
↘ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) [srv-TEST01] 2020.03.21 13:43:04.878254 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Debug> InterpreterSelectQuery: MergeTreeWhereOptimizer: condition "(TV >= toDate('2020-01-01')) AND (TV <= toDate('2020-03-01'))" moved to PREWHERE
[srv-TEST01] 2020.03.21 13:43:04.878961 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Trace> AccessRightsContext (default): Access granted: SELECT(SERVER_ID, DATA_ID, TV, RECEIVE_TIME, P_AV, P_AV_L1, P_AV_L2, P_AV_L3, P_FA, P_FA_MAX, P_FA_MIN, P_FR, P_FR_MAX, P_FR_MIN, P_FA_L1, P_FA_L2, P_FA_L3, P_FR_L1, P_FR_L2, P_FR_L3, P_FA_L1_MAX, P_FA_L2_MAX, P_FA_L3_MAX, P_FR_L1_MAX, P_FR_L2_MAX, P_FR_L3_MAX, P_FA_L1_MIN, P_FA_L2_MIN, P_FA_L3_MIN, P_FR_L1_MIN, P_FR_L2_MIN, P_FR_L3_MIN, P_AV_MIN, P_AV_MAX) ON TEST.POWER
[srv-TEST01] 2020.03.21 13:43:04.879323 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Debug> TEST.POWER (SelectExecutor): Key condition: unknown, unknown, and
[srv-TEST01] 2020.03.21 13:43:04.879374 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Debug> TEST.POWER (SelectExecutor): MinMax index condition: (column 0 in [18262, +inf)), (column 0 in (-inf, 18322]), and
[srv-TEST01] 2020.03.21 13:43:04.879423 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Debug> TEST.POWER (SelectExecutor): Selected 0 parts by date, 0 parts by key, 0 marks to read from 0 ranges
[srv-TEST01] 2020.03.21 13:43:04.879681 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Trace> InterpreterSelectQuery: FetchColumns -> Complete
[srv-TEST01] 2020.03.21 13:43:04.880369 [ 42504 ] {c3921553-e10a-4d27-8bea-c5e3fdd7d10b} <Debug> MemoryTracker: Peak memory usage (for query): 0.00 B.

**Comment by filimonov** [comment]
Looks like numeric value of Date (numer of days) compared with numeric value of DateTime (number of seconds). 

Workaround is trivial.

**Comment by mbtolou** [comment]
When remove  
`
PARTITION BY toYYYYMM(TV) 
`

in 

```
CREATE TABLE TESTDB.TAB_DATE100 (
`SERVER_ID` Int32,
 `TV` DateTime
) ENGINE =  MergeTree **PARTITION BY toYYYYMM(TV)** ORDER BY (SERVER_ID) SETTINGS index_granularity = 8192;
```

All query work correctly.

also when change **toDate('2020-01-01')**  to **toDateTime('2020-01-01 00:00:00')** soo all query work correctly .

**Comment by den-crane** [comment]
Duplicate https://github.com/ClickHouse/ClickHouse/issues/6287
