### ISSUE TITLE
Import database from binary files

### ISSUE THREAD

**Issue by samz406** [ClickHouse/ClickHouse#9806]
hi: i want  import database from other ck database, i copy /var/lib/clickhouse/data and /var/lib/clickhouse/metadata  to new database,  I can export successfully in this way before，but now it's not work . the some log as follow 
`020.03.22 22:13:47.553686 [ 24 ] {} <Error> xxx.ST_CATEGORY_TOP5_RESULT: Considering to remove broken part /var/lib/clickhouse/data/xxx/ST_CATEGORY_TOP5_RESULT/all_1_1_0 because it's impossible to repair.
2020.03.22 22:13:47.554512 [ 24 ] {} <Debug> xxx.ST_CATEGORY_TOP5_RESULT: Loaded data parts (0 items)
2020.03.22 22:13:47.604053 [ 22 ] {} <Error> void DB::MergeTreeData::loadDataParts(bool): Code: 226, e.displayText() = DB::Exception: Marks file '/var/lib/clickhouse/data/xxx/ST_COM_MAIN_INDEX/all_46_55_2/INDEX_TYPE.mrk' doesn't exist, Stack trace:
`
what's going on

**Comment by den-crane** [comment]
>INDEX_TYPE.mrk' doesn't exist,

Recently index adaptive granularity was introduced. Parts with adaptive granules does not have .mrk files but do have .mrk2 instead. So old versions CH does not able to attach such parts because they does not support index adaptive granularity and  .mrk2 marks files.

**Comment by samz406** [comment]
thx
