### ISSUE TITLE
Why does InsertedRows in system.events decrease?

### ISSUE THREAD

**Issue by xuyatian** [ClickHouse/ClickHouse#9816]
Hi,
    We are monitoring the InsertedRows in system.events. We find this value decreases sometimes. How and why does it happen? Thanks.

**Comment by filimonov** [comment]
I have no ideas, it should only increment.

https://github.com/ClickHouse/ClickHouse/blob/461c4919d3dc6a76424976697df5ba40ab8a0882/dbms/src/DataStreams/CountingBlockOutputStream.cpp#L22

Maybe just some silly rounding error of your monitoring tool, or your clickhouse-server was restarted?
 
Can you show some graphs?

**Comment by xuyatian** [comment]
Thanks for the tips. @filimonov 
Our monitor tool recalculates the inserted rows by "system.events.InsertedRows/uptime". so there was a decrement.

**Comment by xuyatian** [comment]
close the issue.
