### ISSUE TITLE
After add new field ,query the new field ,server get Segmentation fault

### ISSUE THREAD

**Issue by muyuqianjia** [ClickHouse/ClickHouse#9821]
**Describe the bug**
My Version is 20.1.3.7 (official build)，After I add a new field, query the field, and the server reports an error:<Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object. Received signal Segmentation fault (11).

**How to reproduce**
my table ddl is 
CREATE TABLE default.like_log (
`shop_id` UInt32 COMMENT '商铺ID',
 `user_id` UInt32 COMMENT '店主或者店员ID',
 `pages` String COMMENT '小程序/h5页面路径',
 `guest_id` UInt32 COMMENT '访客的ID',
 `ip` String COMMENT 'IP地址',
 `relate_id` UInt32 COMMENT '关联ID',
 `article_detail_id` UInt32 COMMENT '文章详情ID',
 `created_ymd` Date COMMENT '创建日期(如2019-12-19)',
 `created_at` UInt32 COMMENT '创建时间戳',
 `source` UInt8 DEFAULT 1 COMMENT '类型1-小程序,2-h5'
) ENGINE = MergeTree() PARTITION BY created_ymd ORDER BY (shop_id, created_ymd) SETTINGS index_granularity = 8192

when i execute：
ALTER TABLE `default`.like_log ADD COLUMN  `type` UInt8 DEFAULT 1 COMMENT '1-资讯2-商品3-案例'  AFTER `source` ;

then query

SELECT `type`  FROM like_log ll  WHERE (shop_id=1) AND (user_id=1) ORDER BY created_at DESC;

Clickhouse server process exited
The error log :

<Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
<Fatal> BaseDaemon: Stack trace: 0x8e51c1e 0x97a27f5 0x97a5f3f 0x97684c6 0x9769cc3 0x91a4c87 0x91d6e84 0x91d70a3 0x8a6d24f 0x94a6871 0x8a6d24f 0x949c
1c8 0x8a6d24f 0x94ef67b 0x8a6d24f 0x94c1278 0x8a6d24f 0x8a5f834 0x8a60ff4 0x4fa4557 0x4fa4b84 0x4fa3a77 0x4fa202f 0x7fe59d4dcaa1 0x7fe59ce1dbcd
<Fatal> BaseDaemon: ########################################
 <Fatal> BaseDaemon: (version 20.1.3.7 (official build)) (from thread 56) (query_id: 85e3b2c2-4c96-49b7-bcd5-ae7d60ef4f2a) Received signal Segmentatio
n fault (11).

**Comment by alexey-milovidov** [comment]
Could you please also share the textual stack trace from log?
It is located right after the messages
```
BaseDaemon: ########################################
BaseDaemon: (version 20.1.3.7 (official build)) (from thread 56) (query_id: 85e3b2c2-4c96-49b7-bcd5-ae7d60ef4f2a) Received signal Segmentation fault (11).
```

**Comment by muyuqianjia** [comment]
> Could you please also share the textual stack trace from log?
> It is located right after the messages
> 
> ```
> BaseDaemon: ########################################
> BaseDaemon: (version 20.1.3.7 (official build)) (from thread 56) (query_id: 85e3b2c2-4c96-49b7-bcd5-ae7d60ef4f2a) Received signal Segmentation fault (11).
> ```

2020.03.23 20:23:42.411890 [ 298 ] {} <Fatal> BaseDaemon: ########################################
2020.03.23 20:23:42.411953 [ 298 ] {} <Fatal> BaseDaemon: (version 20.1.3.7 (official build)) (from thread 92) (query_id: 2a0370df-c5e4-4ec4-aaaf-4723347d0d8b) Received signal Segmentati
on fault (11).
2020.03.23 20:23:42.411994 [ 298 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.03.23 20:23:42.412036 [ 298 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e51c1e 0x97a27f5 0x97a5f3f 0x97684c6 0x9769cc3 0x91a4c87 0x91d6e84 0x91d70a3 0x8a6d24f 0x94a6871 0x8a6d24f 0x949
c1c8 0x8a6d24f 0x94ef67b 0x8a6d24f 0x94c1278 0x8a6d24f 0x8a5f834 0x8a60ff4 0x4fa4557 0x4fa4b84 0x4fa3a77 0x4fa202f 0x7f20696b8aa1 0x7f2068ff9bcd
2020.03.23 20:23:42.413319 [ 299 ] {} <Fatal> BaseDaemon: ########################################
2020.03.23 20:23:42.413371 [ 299 ] {} <Fatal> BaseDaemon: (version 20.1.3.7 (official build)) (from thread 81) (query_id: 2a0370df-c5e4-4ec4-aaaf-4723347d0d8b) Received signal Segmentati
on fault (11).
2020.03.23 20:23:42.413401 [ 299 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.03.23 20:23:42.413437 [ 299 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e51c1e 0x97a27f5 0x97a5f3f 0x97684c6 0x9769cc3 0x91a4c87 0x91d6e84 0x91d70a3 0x8a6d24f 0x94a6871 0x8a6d24f 0x949
c1c8 0x8a6d24f 0x94ef67b 0x8a6d24f 0x94c1278 0x8a6d24f 0x8a5f834 0x8a60ff4 0x4fa4557 0x4fa4b84 0x4fa3a77 0x4fa202f 0x7f20696b8aa1 0x7f2068ff9bcd
2020.03.23 20:23:42.413489 [ 300 ] {} <Fatal> BaseDaemon: ########################################
2020.03.23 20:23:42.413521 [ 300 ] {} <Fatal> BaseDaemon: (version 20.1.3.7 (official build)) (from thread 83) (query_id: 2a0370df-c5e4-4ec4-aaaf-4723347d0d8b) Received signal Segmentati
on fault (11).
2020.03.23 20:23:42.413550 [ 300 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.03.23 20:23:42.413583 [ 300 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e51c1e 0x97a27f5 0x97a5f3f 0x97684c6 0x9769cc3 0x91a4c87 0x91d6e84 0x91d70a3 0x8a6d24f 0x94a6871 0x8a6d24f 0x949
c1c8 0x8a6d24f 0x94ef67b 0x8a6d24f 0x94c1278 0x8a6d24f 0x8a5f834 0x8a60ff4 0x4fa4557 0x4fa4b84 0x4fa3a77 0x4fa202f 0x7f20696b8aa1 0x7f2068ff9bcd
2020.03.23 20:23:42.414108 [ 301 ] {} <Fatal> BaseDaemon: ########################################
2020.03.23 20:23:42.414154 [ 301 ] {} <Fatal> BaseDaemon: (version 20.1.3.7 (official build)) (from thread 86) (query_id: 2a0370df-c5e4-4ec4-aaaf-4723347d0d8b) Received signal Segmentati
on fault (11).
2020.03.23 20:23:42.414184 [ 301 ] {} <Fatal> BaseDaemon: Address: 0x18 Access: read. Address not mapped to object.
2020.03.23 20:23:42.414231 [ 301 ] {} <Fatal> BaseDaemon: Stack trace: 0x8e51c1e 0x97a27f5 0x97a5f3f 0x97684c6 0x9769cc3 0x91a4c87 0x91d6e84 0x91d70a3 0x8a6d24f 0x94a6871 0x8a6d24f 0x949
c1c8 0x8a6d24f 0x94ef67b 0x8a6d24f 0x94c1278 0x8a6d24f 0x8a5f834 0x8a60ff4 0x4fa4557 0x4fa4b84 0x4fa3a77 0x4fa202f 0x7f20696b8aa1 0x7f2068ff9bcd
2020.03.23 20:23:42.451718 [ 299 ] {} <Fatal> BaseDaemon: 3. 0x8e51c1e DB::ColumnVector<unsigned int>::filter(DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> con
st&, long) const  in /usr/bin/clickhouse
2020.03.23 20:23:42.451764 [ 300 ] {} <Fatal> BaseDaemon: 3. 0x8e51c1e DB::ColumnVector<unsigned int>::filter(DB::PODArray<unsigned char, 4096ul, Allocator<false, false>, 15ul, 16ul> con
st&, long) const  in /usr/bin/clickhouse
"/var/log/clickhouse-server/clickhouse-server.err.log" 47894L, 5138786C                                                                                                 47778,1       99%
2020.03.23 20:23:42.452473 [ 300 ] {} <Fatal> BaseDaemon: 15. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452238 [ 299 ] {} <Fatal> BaseDaemon: 16. 0x94ef67b DB::PartialSortingBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452495 [ 300 ] {} <Fatal> BaseDaemon: 16. 0x94ef67b DB::PartialSortingBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452500 [ 299 ] {} <Fatal> BaseDaemon: 17. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452512 [ 300 ] {} <Fatal> BaseDaemon: 17. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452515 [ 299 ] {} <Fatal> BaseDaemon: 18. 0x94c1278 DB::MergeSortingBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452528 [ 300 ] {} <Fatal> BaseDaemon: 18. 0x94c1278 DB::MergeSortingBlockInputStream::readImpl()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452531 [ 299 ] {} <Fatal> BaseDaemon: 19. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452545 [ 300 ] {} <Fatal> BaseDaemon: 19. 0x8a6d24f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452548 [ 299 ] {} <Fatal> BaseDaemon: 20. 0x8a5f834 DB::AsynchronousBlockInputStream::calculate()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452562 [ 300 ] {} <Fatal> BaseDaemon: 20. 0x8a5f834 DB::AsynchronousBlockInputStream::calculate()  in /usr/bin/clickhouse
2020.03.23 20:23:42.452565 [ 299 ] {} <Fatal> BaseDaemon: 21. 0x8a60ff4 ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.452577 [ 300 ] {} <Fatal> BaseDaemon: 21. 0x8a60ff4 ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.452589 [ 299 ] {} <Fatal> BaseDaemon: 22. 0x4fa4557 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>)  in /usr/bin/
clickhouse
2020.03.23 20:23:42.452595 [ 300 ] {} <Fatal> BaseDaemon: 22. 0x4fa4557 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>)  in /usr/bin/
clickhouse
2020.03.23 20:23:42.452625 [ 300 ] {} <Fatal> BaseDaemon: 23. 0x4fa4b84 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1:
:function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1
::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.03.23 20:23:42.452642 [ 299 ] {} <Fatal> BaseDaemon: 23. 0x4fa4b84 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1:
:function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1
::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.03.23 20:23:42.452651 [ 300 ] {} <Fatal> BaseDaemon: 24. 0x4fa3a77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhou
se
2020.03.23 20:23:42.452477 [ 301 ] {} <Fatal> BaseDaemon: 21. 0x8a60ff4 ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.452272 [ 298 ] {} <Fatal> BaseDaemon: 21. 0x8a60ff4 ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.452687 [ 301 ] {} <Fatal> BaseDaemon: 22. 0x4fa4557 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>)  in /usr/bin/
clickhouse
2020.03.23 20:23:42.452692 [ 298 ] {} <Fatal> BaseDaemon: 22. 0x4fa4557 ThreadPoolImpl<ThreadFromGlobalPool>::worker(std::__1::__list_iterator<ThreadFromGlobalPool, void*>)  in /usr/bin/
clickhouse
2020.03.23 20:23:42.452666 [ 300 ] {} <Fatal> BaseDaemon: 25. 0x4fa202f ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.452720 [ 301 ] {} <Fatal> BaseDaemon: 23. 0x4fa4b84 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1:
:function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1
::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.03.23 20:23:42.452747 [ 300 ] {} <Fatal> BaseDaemon: 26. 0x7aa1 start_thread  in /lib64/libpthread-2.12.so
2020.03.23 20:23:42.452751 [ 301 ] {} <Fatal> BaseDaemon: 24. 0x4fa3a77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhou
se
2020.03.23 20:23:42.452770 [ 301 ] {} <Fatal> BaseDaemon: 25. 0x4fa202f ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.452774 [ 300 ] {} <Fatal> BaseDaemon: 27. 0xe8bcd clone  in /lib64/libc-2.12.so
2020.03.23 20:23:42.452804 [ 301 ] {} <Fatal> BaseDaemon: 26. 0x7aa1 start_thread  in /lib64/libpthread-2.12.so
2020.03.23 20:23:42.452829 [ 301 ] {} <Fatal> BaseDaemon: 27. 0xe8bcd clone  in /lib64/libc-2.12.so
2020.03.23 20:23:42.452667 [ 299 ] {} <Fatal> BaseDaemon: 24. 0x4fa3a77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhou
se
2020.03.23 20:23:42.452718 [ 298 ] {} <Fatal> BaseDaemon: 23. 0x4fa4b84 ThreadFromGlobalPool::ThreadFromGlobalPool<void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1:
:function<void ()>, int, std::__1::optional<unsigned long>)::'lambda1'()>(void&&, void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1
::optional<unsigned long>)::'lambda1'()&&...)::'lambda'()::operator()() const  in /usr/bin/clickhouse
2020.03.23 20:23:42.453001 [ 299 ] {} <Fatal> BaseDaemon: 25. 0x4fa202f ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.453014 [ 298 ] {} <Fatal> BaseDaemon: 24. 0x4fa3a77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhou
se
2020.03.23 20:23:42.453025 [ 299 ] {} <Fatal> BaseDaemon: 26. 0x7aa1 start_thread  in /lib64/libpthread-2.12.so
2020.03.23 20:23:42.453029 [ 298 ] {} <Fatal> BaseDaemon: 25. 0x4fa202f ?  in /usr/bin/clickhouse
2020.03.23 20:23:42.453052 [ 298 ] {} <Fatal> BaseDaemon: 26. 0x7aa1 start_thread  in /lib64/libpthread-2.12.so
2020.03.23 20:23:42.453060 [ 299 ] {} <Fatal> BaseDaemon: 27. 0xe8bcd clone  in /lib64/libc-2.12.so
2020.03.23 20:23:42.453072 [ 298 ] {} <Fatal> BaseDaemon: 27. 0xe8bcd clone  in /lib64/libc-2.12.so

**Comment by alexey-milovidov** [comment]
Does the issue present if you update to 20.1.8 or 20.3.4?

**Comment by alesapin** [comment]
Possibly connected with https://github.com/ClickHouse/ClickHouse/issues/9846.

**Comment by muyuqianjia** [comment]
> Does the issue present if you update to 20.1.8 or 20.3.4?

When I upgrade to 20.3.4.10, this problem no longer appears.
