### ISSUE TITLE
AvroConfluent Schema registry changes not considered ?

### ISSUE THREAD

**Issue by tgdkere2** [ClickHouse/ClickHouse#9822]
Thanks for the AvroConfluent support in Clickhouse. 

We ingest data from Kafka with Format AvroConfluent. 

It is working well, until there is a change in the Confluent schema registry, e.g. updating the schema registry with a new schema version of an existing topic. 

Clickhouse always uses the old schema (or probably schema version 1) for the kafka topic. 
It should use the latest schema version from the schema registry. 
Or maybe the schemas are cached within clickhouse but not updated. 

How can we force Clickhouse to reread the schema registry and use the latest schema version of the kafka topic ? 

Tested CH version: 20.3.3.6

**Comment by alexey-milovidov** [comment]
Yes, the schemas are cached.
We can introduce special SYSTEM query to flush this cache.

**Comment by alexey-milovidov** [comment]
@oandrew

**Comment by tgdkere2** [comment]
Thanks for the answer. 
In the meantime, is there any way I can flush the cache manually ?

**Comment by alexey-milovidov** [comment]
Currently there is no way to flush it manually.

**Comment by oandrew** [comment]
@tgdkere2 
You can't change the schema of messages on a topic because each  message already contains a schema id which is used by ClickHouse to find the schema.
Schema id is globally unique and should not cause any issues when schema is cached. 

In other words: ClickHouse doesn't even know which topic it consumes from, all that matters is the schema id that's already embedded in the messages.

**Comment by maqroll** [comment]
My two cents... 
A schema (subject + version) pushed into schema registry is (should be) inmutable. 
A flush shouldn't be necessary.

**Comment by tgdkere2** [comment]
Hello @oandrew @maqroll , 
You are right, the problem was the long retention time configured in the Kafka topic. 
Therefore it was still trying to get the old schema for the old records. 
Thank you !
