### ISSUE TITLE
How to use Materialized view SummingMergeTree with time window (last 1h, 2h, 3h, etc)

### ISSUE THREAD

**Issue by bzon** [ClickHouse/ClickHouse#9838]
Is this achievable with a Materialized View? For simplicity, let's say I want the total count per time window (3h, 6h, 12h, etc). 

```sql
CREATE TABLE visits_6h (
    total UInt64,
    sum(status != 200) AS failed_total,
    user String
)
ENGINE = SummingMergeTree()
PARTITION BY tuple()
ORDER BY (user)
```

```sql
CREATE MATERIALIZED VIEW visits_6h_mv
TO downloads_6h
AS
SELECT
    count(*) AS total,
    sum(status != 200) AS failed_total,
    user
FROM visits
AND date >= now() - toIntervalHour(6)
GROUP BY user
```

I thought that the aggregate table will eventually catch up with the result of the original query but it never did on my live environment.

```sql
SELECT
    count(*) AS total,
    sum(status != 200) AS failed_total,
    user
FROM visits
AND date >= now() - toIntervalHour(6)
GROUP BY user
```

I also tried the POPULATE syntax but that is not recommended on a live environment where inserts are flowing.

**Comment by den-crane** [comment]
MV is an insert trigger. 
You can store hourly numbers in one MV and calc using sum where ... and drop data older than 12h (using TTL or manually - drop partition).

also check LiveViews https://www.altinity.com/blog/tag/Live+Views

**Comment by bzon** [comment]
@den-crane thanks! 

This is the new tables.

```sql
CREATE TABLE visits_6h (
    hour DateTime,
    total UInt64,
    sum(status != 200) AS failed_total,
    user String
)
ENGINE = SummingMergeTree()
PARTITION BY hour
ORDER BY (hour, user)
TTL hour + INTERVAL 12 HOUR;
```

```sql
CREATE MATERIALIZED VIEW visits_6h_mv
TO downloads_6h
AS
SELECT
    toStartOfHour(date),
    count(*) AS total,
    sum(status != 200) AS failed_total,
    user
FROM visits
WHERE date >= 'some time ahead'
GROUP BY user
```

Then manually populate the table after the MV starts populating using the same SELECT query but inverting the WHERE date filter to `<`.

I will also have a look at live tables.
