### ISSUE TITLE
export table to json file

### ISSUE THREAD

**Issue by ortal650** [ClickHouse/ClickHouse#9844]
I want to export a whole table from clickhouse to json file. I can't find q way, how should I do?

**Comment by maqroll** [comment]
select * from table into OUTFILE 'table.json' FORMAT JSON;

exports both data and schema in json format.

**Comment by ortal650** [comment]
thanks but I get this error:
Syntax error (Multi-statements are not allowed): failed at position 97 (line 2, col 66): JSON;

Also, I'd like to to export the table to a local json file, so what is the path I should make for this?

**Comment by maqroll** [comment]
open your client with multi-statement support if you need it (flag -n).
Path is local.

**Comment by ortal650** [comment]
Sorry I am new in clickhouse and I don't really understand how it works.
Im using Tabix platform to create table and make queries. I did the querie you sent me in tabix and there I get the error. Is it the right way to do it? I dont really understand what I should do about the multi statement you talked about... Im kind of lost... Can you please explain me a little bit what to do? thank you so much

**Comment by ortal650** [comment]
I removed semicolon from the query end and I dont have multi statement error anymore.
but I get the error : FORMAT JSON . Expected identifier, e.what() = DB::Exception
When I try to remove the FORMAT JSON, then I get error: INTO OUTFILE is not allowed, e.what() = DB::Exception
What is making a problem?

**Comment by maqroll** [comment]
I have no experience with tabbix but probably is using clickhouse http interface. it makes sense that INTO OUTFILE is not allowed.

**Comment by den-crane** [comment]
Ask tabix author?
using curl 
`echo 'SELECT 1 FORMAT JSON' | curl -o out.json 'http://localhost:8123/?user=user&password=password' -d @-`

**Comment by ortal650** [comment]
Indeed clickhouse use http interface. I made the querie from client side, uside http get request but I still get error and really dont understand the problem.

the querie made is : 
SELECT * FROM mytable INTO OUTFILE  'file.json'  LIMIT 20 FORMAT JSON 

and the error:
Syntax error: failed at position 64: LIMIT 20 FORMAT JSON\n. Expected FORMAT, e.what() = DB::Exception

Please help me find the solution

**Comment by maqroll** [comment]
SELECT * FROM mytable LIMIT 20 INTO OUTFILE 'file.json' FORMAT JSON

**Comment by den-crane** [comment]
@ortal650 ` INTO OUTFILE` is part of clickhouse-client functionality.

use curl
echo 'SELECT 1 FORMAT JSON' | **curl -o out.json '** http://localhost:8123/?user=user&password=password' -d @-

**Comment by ortal650** [comment]
Thank you for your responses.
@den-crane Im using a nodejs server and from this server I want to export my table. I tried to make the select query by doing a http get request but I still get the error of INTO OUTFILE not allowed... Do you know what I should do to make a request as client from nodejs server? 
Im really lost and tried everything I dont know what to do anymore

**Comment by den-crane** [comment]
In case of nodejs just do an http get request and save output stream into a file. https://stackoverflow.com/a/42297912/11644308

your question is not related to Clickhouse but to nodejs/javascript.

You obviously cannot use `INTO OUTFILE` with nodejs / http because this feature is a part of a specific application -- clickhouse-client.
