### ISSUE TITLE
Parameter out of bound in IColumnString::insertRangeFrom method

### ISSUE THREAD

**Issue by mvcalder-xbk** [ClickHouse/ClickHouse#9849]
I get the above error in a query that is of the form:

`
select a, b, c, any(d)
from t
group by a,b,c
`

It seems to linked to a specific column, say `b`, in that if I comment it out the problem goes away. Any ideas on how to work around / troubleshoot?

**Comment by alexey-milovidov** [comment]
What version of ClickHouse do you use?

**Comment by mvcalder-xbk** [comment]
Sorry, I realize my message was sparse on details, but I didn't need to leave out knowable things:

ClickHouse client version 19.17.6.36 (official build).
Connected to ClickHouse server version 20.1.2 revision 54431.

I'm happy to try to isolate the problem. The actual query I'm using is just too complex to put here.

**Comment by mvcalder-xbk** [comment]
I extracted the stacktrace from the log. This is a different query that gives the same error:

`
 │ Code: 12, e.displayText() = DB::Exception: Parameter out of bound in IColumnString::insertRangeFrom method. (version 20.1.2.4 (official build)) │ 0. 0xbc31d9c Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
1. 0x4f6ccd9 DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)  in /usr/bin/clickhouse
2. 0x4bc4784 ?  in /usr/bin/clickhouse
3. 0x97a25fb DB::MergeTreeRangeReader::ReadResult::shrink(std::__1::vector<COW<DB::IColumn>::immutable_ptr<DB::IColumn>, std::__1::allocator<COW<DB::IColumn>::immutable_ptr<DB::IColumn> > >&)  in /usr/bin/clickhouse
4. 0x97a44db DB::MergeTreeRangeReader::ReadResult::optimize()  in /usr/bin/clickhouse
5. 0x97a4e7d DB::MergeTreeRangeReader::executePrewhereActionsAndFilterColumns(DB::MergeTreeRangeReader::ReadResult&)  in /usr/bin/clickhouse
6. 0x97a5884 DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
7. 0x97a55bd DB::MergeTreeRangeReader::read(unsigned long, std::__1::vector<DB::MarkRange, std::__1::allocator<DB::MarkRange> >&)  in /usr/bin/clickhouse
8. 0x9768166 DB::MergeTreeBaseSelectProcessor::readFromPartImpl()  in /usr/bin/clickhouse
9. 0x9769963 DB::MergeTreeBaseSelectProcessor::generate()  in /usr/bin/clickhouse
10. 0x91a4c27 DB::ISource::work()  in /usr/bin/clickhouse
11. 0x91d6e24 DB::TreeExecutorBlockInputStream::execute()  in /usr/bin/clickhouse
12. 0x91d7043 DB::TreeExecutorBlockInputStream::readImpl()  in /usr/bin/clickhouse
13. 0x8a6d32f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
14. 0x949c168 DB::ExpressionBlockInputStream::readImpl()  in /usr/bin/clickhouse
15. 0x8a6d32f DB::IBlockInputStream::read()  in /usr/bin/clickhouse
16. 0x94e9520 DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::thread(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long)  in /usr/bin/clickhouse
17. 0x94e9aa5 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*, std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long&>(void (DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>::*&&)(std::__1::shared_ptr<DB::ThreadGroupStatus>, unsigned long), DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler>*&&, std::__1::shared_ptr<DB::ThreadGroupStatus>&&, unsigned long&)::'lambda'()::operator()() const  in /usr/bin/clickhouse
18. 0x4fa3b77 ThreadPoolImpl<std::__1::thread>::worker(std::__1::__list_iterator<std::__1::thread, void*>)  in /usr/bin/clickhouse
19. 0x4fa212f ?  in /usr/bin/clickhouse
20. 0x76db start_thread  in /lib/x86_64-linux-gnu/libpthread-2.27.so
21. 0x12188f clone  in /lib/x86_64-linux-gnu/libc-2.27.so`

**Comment by alexey-milovidov** [comment]
We have bugfixes for similar issue recently.
Does it reproduce on 20.1.8 or 20.3.4?

**Comment by mvcalder-xbk** [comment]
I'll check.

**Comment by alexey-milovidov** [comment]
It looks like https://github.com/ClickHouse/ClickHouse/pull/8914 that was fixed in 20.3 and also backported in 20.1 starting from 20.1.4

**Comment by mvcalder-xbk** [comment]
Fixed with the upgrade, thank you.

**Comment by SeaAndHillMe** [comment]
i meet the same exception at the version 20.1.2.4 ,but another environment not throw this error with same version , what version do you upgrade to ? @mvcalder-xbk

**Comment by alexey-milovidov** [comment]
@SeaAndHillMe 

```
curl https://clickhouse.com/ | sh
```

**Comment by SeaAndHillMe** [comment]
> @SeaAndHillMe
> 
> ```
> curl https://clickhouse.com/ | sh
> ```

the latest version ? 22. ？ do you mean ?

**Comment by alexey-milovidov** [comment]
It will install 22.10.
