### ISSUE TITLE
/etc/clickhouse-server/users.xml and /etc/clickhouse-server/config.d/users.xml behave differently

### ISSUE THREAD

**Issue by ghuname** [ClickHouse/ClickHouse#9858]
**Describe the bug**
Difference between /etc/clickhouse-server/users.xml and /etc/clickhouse-server/config.d/users.xml

According to documentation, https://clickhouse.tech/docs/en/operations/configuration_files/, we should left original config.xml and users.xml as they are, but in config.d directory create new files with keys that we want to change.

I tried to follow this procedure on my previous project but with partial success. Sometimes the value set in config.d directory was applied, sometime wasn't, so on that project I ended up modifying original files and I deleted config.d directory.

Now I have an access to a single clickhouse server on which I would like to find out whether procedure described on link above works or not.

I decided to set option <send_logs_level>trace</send_logs_level>. 
At first I have set it in original /etc/clickhouse-server/users.xml (first line bellow "users" tag):

```
...
           <readonly>1</readonly>
        </readonly>
    </profiles>

    <!-- Users and ACL. -->
    <users>
        <send_logs_level>trace</send_logs_level>
        <!-- If user name was not specified, 'default' user is used. -->
        <default>
            <!-- Password could be specified in plaintext or in SHA256 (in hex format).
...
```

After doing it I got an error log:

```
2020.03.25 11:28:21.365771 [ 27 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
2020.03.25 11:28:21.367054 [ 27 ] {} <Error> ConfigReloader: Error updating configuration from '/etc/clickhouse-server/users.xml' config.: Code: 36, e.displayText() = DB::Exception: Either 'password' or 'password_sha256_hex' or 'password_double_sha1_hex' must be specified for user send_logs_level., Stack trace:

0. 0x3512b60 StackTrace::StackTrace() /usr/bin/clickhouse
1. 0x351cdaf DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
2. 0x6919b77 DB::User::User(std::string const&, std::string const&, Poco::Util::AbstractConfiguration const&) /usr/bin/clickhouse
3. 0x62c2e3e DB::UsersManager::loadFromConfig(Poco::Util::AbstractConfiguration const&) /usr/bin/clickhouse
4. 0x61627e7 DB::Context::setUsersConfig(Poco::AutoPtr<Poco::Util::AbstractConfiguration> const&) /usr/bin/clickhouse
5. 0x35620fa ? /usr/bin/clickhouse
6. 0x6a08822 DB::ConfigReloader::reloadIfNewer(bool, bool, bool) /usr/bin/clickhouse
7. 0x6a099ef DB::ConfigReloader::run() /usr/bin/clickhouse
8. 0x6a09bb5 ThreadFromGlobalPool::ThreadFromGlobalPool<void (DB::ConfigReloader::*)(), DB::ConfigReloader*>(void (DB::ConfigReloader::*&&)(), DB::ConfigReloader*&&)::{lambda()#1}::operator()() const /usr/bin/clickhouse
9. 0x3554f13 ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>) /usr/bin/clickhouse
10. 0x791d69f ? /usr/bin/clickhouse
11. 0x7f7e96433dc5 start_thread /usr/lib64/libpthread-2.17.so
12. 0x7f7e95f5d28d clone /usr/lib64/libc-2.17.so
 (version 19.17.4.11)
```

Now I deleted <send_logs_level> key from /etc/clickhouse-server/users.xml, and I have put it in /etc/clickhouse-server/config.d/users.xml as follows:

```
<?xml version="1.0"?>
<yandex>
    <users>
        <default>
            <send_logs_level>trace</send_logs_level>
        </default>
    </users>
</yandex>
```

Upon saving config.d/users.xml, in log I have found:

`2020.03.25 11:40:49.646907 [ 26 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/config.xml'`

but no error at all.

I expect that I should get the same message as if I set this config in /etc/clickhouse-server/config.xml

Furthermore, second log shows "Loading config '/etc/clickhouse-server/config.xml'`", but not config.d/users.xml. I can provoke this message whenever I change and save config.d/users.xml.

If database functions like this, we are never sure which file has been read and whether setting is applied or not (apart from not having enough info about where to put which settings. config.xml? users.xml, under which xml key?).

My question is why I am not getting the same error mesagge?

Regards.

* Which ClickHouse server version to use

ClickHouse client version 19.17.4.11.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 19.17.4 revision 54428.

**Comment by ghuname** [comment]
Now I have put in system.d/users.xml "log_queries" tag so my file looks like:

```
<?xml version="1.0"?>
<yandex>
    <profiles>
        <default>
            <log_queries>1</log_queries>
        </default>
    </profiles>
</yandex>
```

server recognized change in its log:

`2020.03.25 12:33:54.775735 [ 1 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'`

Again, it reports /etc/clickhouse-server/users.xml not /etc/clickhouse-server/config.d/users.xml

`select * from system.query_log` reports:

```
2020.03.25 12:39:30.063086 [ 50 ] {1313ec03-7c52-40d7-9602-ce49ca434b38} <Error> HTTPHandler: Code: 60, e.displa
yText() = DB::Exception: Table system.query_log doesn't exist., Stack trace:
```

Now I deleted key from config.d/users.xml and put it in /etc/clickhouse-server/users.xml bellow "default" key:

```
<?xml version="1.0"?>
<yandex>
    <!-- Profiles of settings. -->
    <profiles>
        <!-- Default settings. -->
        <default>
            <log_queries>1</log_queries>
            <!-- Maximum memory usage for processing single query, in bytes. -->
            <max_memory_usage>10000000000</max_memory_usage>

            <!-- Use cache of uncompressed blocks of data. Meaningful only for processing many of very short queries. -->

```
server reported: 
`2020.03.25 12:42:16.957036 [ 40 ] {} <Debug> ConfigReloader: Loading config '/etc/clickhouse-server/users.xml'
`

And it works now, `select * from system.query_log` shows records.

Again, why I cannot set `<log_queries>1</log_queries>` in config.d/users.xml?

Maybe I am missing something.

**Comment by ghuname** [comment]
I believe that modified users.xml should be in /etc/clickhouse-server/users.d directory.

On https://clickhouse.tech/docs/en/operations/configuration_files/ there is an error in sentence:
"In addition, users_config may have overrides in files from the **users_config.d** directory (for example, users.d) and substitutions. For example, you can have separate config file for each user like this:"

I will close this issue.

**Comment by alexey-milovidov** [comment]
You're right. Actually, the documentation is correct, because you can set up alternative name (istead of users.xml) for users config in config.xml. But it's very unclear, we need to fix it.
