### ISSUE TITLE
single row SELECT query with ClickHouse

### ISSUE THREAD

**Issue by hatrena** [ClickHouse/ClickHouse#9867]
We have a case that we have to use a `SELECT` query to return a single row record in a hundred million rows in ClickHouse. we need to do it so often that it may be risky for `RAM` usage.

We also know that 
If the query omits the `DISTINCT`, `GROUP BY` and `ORDER BY` clauses and the `IN` and `JOIN` subqueries, the query will be completely stream processed, using O(1) amount of `RAM`.
Otherwise, the query might consume a lot of `RAM` if the appropriate restrictions are not specified: `max_memory_usage`, `max_rows_to_group_by`, `max_rows_to_sort`, `max_rows_in_distinct`, `max_bytes_in_distinct`, `max_rows_in_set`, `max_bytes_in_set`, `max_rows_in_join`, `max_bytes_in_join`, `max_bytes_before_external_sort`, `max_bytes_before_external_group_by`.

So is there any clause or syntax that we can use to make this frequent single row `SELECT` query smooth?

**Comment by den-crane** [comment]
CH streaming blocks not rows, an in multiple threads. 
So it could be that your query will process 96*65536 rows to retrieve 1 row.

Try `set max_threads=1, max_block_size=1024`
