### ISSUE TITLE
Use of sampling key in partition key instead of primary key

### ISSUE THREAD

**Issue by ekimekim** [ClickHouse/ClickHouse#9869]
We have a case where we want to use a sampling key in order to make use of `max_parallel_replicas=2` to split queries across replicas.

However, it is important to us that our data be time ordered, so putting the sampling key before the time in our ordering key (and subsequently in our primary key) is not a good option. Putting the sampling key after the time, to my understanding, would also not be ideal since we would need to read the entire range and only discard data based on sampling after reading. This is our primary concern since most of our queries are bottlenecked on reading data from disk, most of which is then filtered out by other WHERE clauses.

Since we don't care about actually sampling the data beyond splitting it into two halves in order to parallelize queries, we are considering having a "partition" column with only two distinct values, and then using this as the partitioning key and the sampling key.

(I see from https://github.com/ClickHouse/ClickHouse/issues/5185#issuecomment-552431754 that we will need to pick our two distinct values carefully to ensure they actually end up in two different sample ranges, but I'm ignoring that for simplicity for now)

For example, we are considering something like this:
```
CREATE TABLE example (
  time DateTime,
  partition uint32,
  <some other columns...>
) ENGINE = MergeTree()
PARTITION BY (partition)
ORDER BY (time)
SAMPLE BY (partition)
```

However, when we try this we get an error `Sampling expression must be present in the primary key`. But looking through the code I found the setting `settings.compatibility_allow_sampling_expression_not_in_primary_key` (added here: https://github.com/ClickHouse/ClickHouse/commit/6aff58c747d2cf6114d662b83937a1c1f8f27efc). This is fairly explicitly stated to only be intended for backwards compatability with tables created before this requirement, but I can't seem to find any explicit rationale for the change (the check was added here: https://github.com/ClickHouse/ClickHouse/commit/75c65c7b59be5620e1e4db305eb4e879531f37f3 but the commit was not illuminating).

Is this simply meant to protect people against picking a sampling key that would not be efficient to filter against? Having the sampling key in the partition key should solve that problem. Or is this kind of setup a bad idea for other reasons?

If this setup is valid, is there any chance we could relax the check to allow sampling keys to be in the primary _or_ partitioning keys?

**Comment by den-crane** [comment]
In 99.9999% cases `max_parallel_replicas=2` improves nothing because it's nature.

Moreover `max_parallel_replicas` is buggy and returns wrong results https://github.com/ClickHouse/ClickHouse/issues/9202

Do a proper tests to find out is it reasonable to use `max_parallel_replicas` or not.

**Comment by alexey-milovidov** [comment]
@ekimekim Sampling expression is meant to be uniformly distributed across its domain.
But if your sampling key is UInt32 and it's uniformly distributed and you use it as partition key, you will end up with billions of partitions. This is not practical at all. Even for UInt16 it's not practical.

**Comment by alexey-milovidov** [comment]
So, the recommendation is to just give up this idea.

**Comment by alexey-milovidov** [comment]
Why the `max_parallel_replicas` setting is implemented via sampling?
It is needed to provide consistent split of data, regardless to how the data was merged on different replicas.

But reading sample of data is not always N times faster than reading the whole data. It depends on the sampling key and if data is not ordered accordingly, it cannot read ranges of data faster.

**Comment by alexey-milovidov** [comment]
We need to implement different way for efficient query processing across multiple replicas.
