### ISSUE TITLE
data lose when use SummingMergeTree MATERIALIZED VIEW and sum result is 0

### ISSUE THREAD

**Issue by undeadwing** [ClickHouse/ClickHouse#9876]
1.create table t2

create table t2
(
    birth Date,
    id    UInt16,
    name  String,
    point UInt16,
    ver   UInt8
) ENGINE = MergeTree ORDER BY (id, name)

2.next create MATERIALIZED VIEW t2_view

CREATE MATERIALIZED VIEW t2_view
    ENGINE = SummingMergeTree((point, ver)) ORDER BY (id, name)
AS
SELECT id,
       name,
       point,
       ver
FROM t2

3.then insert 2 record
insert into t2(birth, id, name, point, ver) values ('2017-04-01', 1, 'qwe', 0, 0);
insert into t2(birth, id, name, point, ver) values ('2017-04-01', 1, 'qwe', 0, 0);

4.select * from t2_view    can get 2 records  
1,qwe,0,0
1,qwe,0,0

but use final ,select * from t2_view final get 0 record

so,is this a bug?
or this is just a design in clickhouse?
thank you

**Comment by den-crane** [comment]
https://clickhouse.tech/docs/en/operations/table_engines/summingmergetree/
....
**If the values were 0 in all of the columns for summation, the row is deleted.**
...

**Comment by undeadwing** [comment]
@den-crane ok,thank you for the answer
