### ISSUE TITLE
Something like query_log / part_log  for materialized views

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#9877]
Right now the execution of materialized view(s) doesn't leave any traces (i.e. how many rows was processed / inserted / how much memory did it take / was there any error during MV execution).

The single insert can lead to several MV calculation (sometimes heavy - with subselects, joins etc), we need to see how each MV behave - so I would expect one row per each MV to see the exact place of the problem.

Quite often the problems are visible only for the side which inserts the data, which can silently ignore the error (very bad) or do reties in the loop (still can be quite hard to find).

**Comment by nvartolomei** [comment]
There are some traces in query_thread_log if parallel mv insert is enabled and there are more than 1 mv attached per source.
