### ISSUE TITLE
Decimals and Floats can not be used in expressions without explicit type cast

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#9881]
(you don't have to strictly follow this form)

**Describe the bug**
Decimals and floats can not be used in expressions without explicit conversion.

**How to reproduce**

```
SELECT toDecimal32(3, 5) * 1.2

Received exception from server (version 20.3.2):
Code: 43. DB::Exception: Received from localhost:9000. DB::Exception: Illegal types Float64 and Decimal(9, 2) of arguments of function multiply. 
```

**Expected behavior**

Perform implicit type conversion to the proper data type, as it works with floats and integers. E.g. 'SELECT toDecimal32(3, 5) + 1' works fine.

In real applications we can expect Decimal columns and expressions over them.

**Comment by qoega** [comment]
There is a problem that `1.2` literal is treated as float, but not as decimal. For correct results for example there should be conditional parsing of literals with `.`. Otherwise there would be error if number would be converted from float to decimal.

**Comment by filimonov** [comment]
> There is a problem that `1.2` literal is treated as float, but not as decimal. For correct results for example there should be conditional parsing of literals with `.`. Otherwise there would be error if number would be converted from float to decimal.

```
select CAST(0.11111111111111111111111111111111111111 AS Decimal128(38))
┌─CAST(0.1111111111111111, 'Decimal128(38)')─┐
│   0.11111111111111110860978869272892669952 │
└────────────────────────────────────────────┘
```
:(

**Comment by filimonov** [comment]
But
```
SELECT CAST('0.11111111111111111111111111111111111111', 'Decimal128(38)')

┌─CAST('0.11111111111111111111111111111111111111', 'Decimal128(38)')─┐
│                           0.11111111111111111111111111111111111111 │
└────────────────────────────────────────────────────────────────────┘
```

**Comment by alexey-milovidov** [comment]
Multiplication of float * decimal should work and produce float.
Reason: multiplication by float implies loss of precision.

Interpretation of literals like `0.1` as float or decimal is completely different task and can be solved separately.

**Comment by alexey-milovidov** [comment]
When multiplying float by decimal, any kind of decimal should be converted to Float64 before multiplication.
