### ISSUE TITLE
How does $rate() macro work?

### ISSUE THREAD

**Issue by AbhinandanKurakure** [ClickHouse/ClickHouse#9898]
I am a beginner to clickhouse DB.I am using clickhouse DB to store the values and using clickhouse plugin for grafana.I wanted to know how does $rate() function works as there is only one example in [https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource](url) .

**Comment by nvartolomei** [comment]
`$rate` is implemented by the Grafana plugin and has nothing to do with ClickHouse itself.
It is documented here https://github.com/Vertamedia/clickhouse-grafana#ratecols---converts-query-results-as-change-rate-per-interval

If you have more questions it is more appropriate to ask them there https://github.com/Vertamedia/clickhouse-grafana/issues
