### ISSUE TITLE
Build fail (flatc, no SSE 4)

### ISSUE THREAD

**Issue by evgenmur** [ClickHouse/ClickHouse#9902]
**Operating system**
Linux Mint 19.3

**Cmake version**
cmake version 3.10.2

**Ninja version**
1.8.2

**Compiler name and version**
gcc-9 (Ubuntu 9.2.1-17ubuntu1~18.04.1) 9.2.1 20191102

**Full cmake and/or ninja output**
[2199/7097] Running flatc compiler on /home/evgeny/...ckHouse/contrib/arrow/cpp/src/arrow/ipc/feather.fbs
FAILED: contrib/arrow-cmake/arrow_gen_headers/arrow/ipc/File_generated.h contrib/arrow-cmake/arrow_gen_headers/arrow/ipc/Message_generated.h contrib/arrow-cmake/arrow_gen_headers/arrow/ipc/feather_generated.h contrib/arrow-cmake/arrow_gen_headers/arrow/ipc/Schema_generated.h contrib/arrow-cmake/arrow_gen_headers/arrow/ipc/SparseTensor_generated.h contrib/arrow-cmake/arrow_gen_headers/arrow/ipc/Tensor_generated.h 
cd /home/evgeny/bin/build/contrib/arrow-cmake && /home/evgeny/bin/build/contrib/flatbuffers/flatc -c -o /home/evgeny/bin/build/contrib/arrow-cmake/arrow_gen_headers/arrow/ipc/ /home/evgeny/bin/ClickHouse/contrib/arrow/format/Message.fbs /home/evgeny/bin/ClickHouse/contrib/arrow/format/File.fbs /home/evgeny/bin/ClickHouse/contrib/arrow/format/Schema.fbs /home/evgeny/bin/ClickHouse/contrib/arrow/format/Tensor.fbs /home/evgeny/bin/ClickHouse/contrib/arrow/format/SparseTensor.fbs /home/evgeny/bin/ClickHouse/contrib/arrow/cpp/src/arrow/ipc/feather.fbs
Illegal instruction
[2201/7097] Building CXX object contrib/avro-cmake/...les/avrocpp.dir/__/avro/lang/c++/impl/Compiler.cc.o
ninja: build stopped: subcommand failed.

I can't understand what is wrong in building.

**Comment by alexey-milovidov** [comment]
It means that your system does not support CPU instruction set that we use for ClickHouse (SSE 4.2).
It happens on build time because the intermediate build tool `flatc` is also build with this instruction set but it cannot run.

This is build issue. Intermediate tools must be built with the CPU instruction set of the host system.

**Comment by evgenmur** [comment]
> It means that your system does not support CPU instruction set that we use for ClickHouse (SSE 4.2).
> It happens on build time because the intermediate build tool `flatc` is also build with this instruction set but it cannot run.
> 
> This is build issue. Intermediate tools must be built with the CPU instruction set of the host system.

Is it possible to replace flatc compiler if I already built flatc compiler in my system?

**Comment by alexey-milovidov** [comment]
You can rewrite the `flatc` binary in `CMakeFiles` with your own binary and continue build.

**Comment by evgenmur** [comment]
> You can rewrite the `flatc` binary in `CMakeFiles` with your own binary and continue build.

I have replaced all files in /ClickHouse/build/contrib/flatbuffers with compiled files from /flatbuffers/CMakeFile and also added flatc binary but error the same

**Comment by alexey-milovidov** [comment]
After https://github.com/ClickHouse/ClickHouse/pull/12181 we don't need `flatc` for build anymore.
