### ISSUE TITLE
rowNumberInBlock / rowNumberInAllBlocks usage in asof join

### ISSUE THREAD

**Issue by mvcalder-xbk** [ClickHouse/ClickHouse#9906]
I have data in the form:

```
id     | timestamp                        | field          | value
ABC | 2020-01-09T15:44:24.000 | BEST_ASK | 144.82
ABC | 2020-01-09T15:44:24.000 | BEST_ASK | 144.83
ABC | 2020-01-09T15:44:24.000 | BEST_BID | 144.82
ABC | 2020-01-09T15:44:24.000 | BEST_BID | 144.81
ABC | 2020-01-09T15:44:24.000 | BEST_BID | 144.81
```

Here there are multiple BEST_BID and BEST_ASK for a single timestamp. I want to choose the closest trailing BEST_ASK for each BEST_BID. I'm using `rowNumberInBlock()` in an `ASOF` join but I am getting results that depend on the range of timestamps I ask for. If I ask for a narrow range of timestamps I get the results I expect, but when I try to process a whole day (10K+ rows) I get results that look like the two separate sequences of row-numbers were calculated even though the form of the row-number query is the same:

```
            select timestamp_bid, timestamp_ask, pr_bid, pr_ask
            from (
                select id, timestamp as timestamp_bid, value as pr_bid, dt
                from (
                    select id, field, timestamp , value,  rowNumberInBlock() as dt
                    from tickdb.tickdata
                    where id = 'ABC' and timestamp = '2020-03-27''
                )
                where field = 'BEST_BID' 
            ) asof join (
                select id, timestamp as timestamp_ask, value as pr_ask, dt
                from (
                    select id, field, timestamp , value,  rowNumberInBlock() as dt
                    from tickdb.tickdata
                    where id = 'ABC' and timestamp = '2020-03-27'
                )
                where field = 'BEST_ASK' 
            ) using (id, dt)
```

I can tell the sequences are out of alignment because of the respective timestamps:

```
	        timestamp_bid	                timestamp_ask	                pr_bid	pr_ask
107871	2020-01-09T15:37:41.000	2020-01-09T15:08:12.000	144.70	144.49
107872	2020-01-09T15:37:41.000	2020-01-09T17:33:07.000	144.69	143.49
107873	2020-01-09T15:37:41.000	2020-01-09T20:07:39.000	144.70	143.87
107874	2020-01-09T15:37:41.000	2020-01-09T18:12:17.000	144.69	143.39
107875	2020-01-09T15:37:41.000	2020-01-09T18:54:06.000	144.69	143.67
```

I'm guessing the fact that my timestamps are not unique is not helping here, btw they are strings not DateTimes. Is there a way to accomplish what I am after, to get the closest trailing value based on the value present in another column? Thanks, let me know if any of this needs clarification.

Matt

**Comment by blinkov** [comment]
@mvcalder-xbk, is this question still relevant?

**Comment by mvcalder-xbk** [comment]
My markdown in the original question was malformed, sorry. I corrected that and would like to simplify the question. I want to be able to access the row number of rows in the table.

If I start with a parquet file and create a table from it is it safe to assume the rows of the table in the order that they are in in the parquet file?

Assuming they are. Is there a way to preserve the original order in a query, so that neighbor(field, 1) returns the next field based on the order of the table?

If I append a row number to the original parquet file than I could accomplish this, but is there a way to do it using built in commands?

My example above shows that roowNumberInBlocks does not quite accomplish this. A simpler test is to take a large table and query:

```
select *, rowNumberInBlocks() as n from large_table
```

The in the result, the value of n is not simply a monotonically increasing count, it jumps forward and backward at points.

Thanks for any help on this.

**Comment by 4ertus2** [comment]
You get such behaviour cuse `rowNumberInBlock` return a number in block and when you JOIN big left table you will have several blocks for sure. Blocks are some intermediate form of data. You can manage it with several settings in different points of query execution but in fact you have no guarinties about their size or order of execution.

> If I start with a parquet file and create a table from it is it safe to assume the rows of the table are in the order that they are in in the parquet file?

If you're talking about 'file -> MergeTree' extraction, it's not true. Data would be inserted into MergeTree in parts and reordered according to `ORDER BY` statement in MergeTree description. You may apply `ORDER BY` to it in query, but it does not bring us any closer to result.

Returning to the first your question you may `ASOF JOIN` by `dt` column but group BID and ASK values in arrays with `groupArray()` function for each `dt` and find `min` and `max` in these arrays using array functions before JOIN https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/ Something linke that

```
SELECT ... FROM
(
    SELECT id, arrayReverseSort(groupArray(pr_bid))[1], dt FROM table
    GROUP BY dt
)
ASOF JOIN
(
    SELECT id, arraySort(groupArray(pr_ask))[1], dt FROM table
    GROUP BY dt
)
USING (id, dt)
```

**Comment by 4ertus2** [comment]
Also if you need just the closest ask and big in some time range you need just an `ASOF JOIN ... USING (id, value)` instead of `ASOF JOIN ... USING (id, dt)`. Your original JOIN tryes to find the closest dates first.

If you need to find the closest `dt` first and the closest `value` in result you have to make additional subselect or emulate it via arrays as described above. There's no `ASOF JOIN` with several inequalities yet.

**Comment by mvcalder-xbk** [comment]
Thanks @4ertus2 that is helpful information. We ended up adding a separate indexing column upstream to our data so we can disambiguate equal timestamps which was the root cause of the difficulty we were having. Thank you.
