### ISSUE TITLE
Online documentation for previous versions

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#9912]
Could you please make documentation for versions before 19.8 available online?
(I'm using version 18.16)

**Comment by blinkov** [comment]
Well, we don't really have an infrastructure for that at the moment. Documentation is completely rebuilt on each release (including all languages and old versions) and it takes way too long even with current limited depth.

**Comment by blinkov** [comment]
@FedericoCeratto btw you could just browse through documentation sources, they are more or less readable even on GitHub: https://github.com/ClickHouse/ClickHouse/tree/v18.16/docs/en

**Comment by FedericoCeratto** [comment]
Thanks!
