### ISSUE TITLE
Log to journald

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#9913]
ClickHouse should log to Journald where available.

Currently the systemd unit logs into journald already. E.g. it can be monitored with `journalctl -f -u clickhouse-server`

Journald supports structured logging using key-value pair. It indexes them and allow filtering on them.
With native support people could be filter e.g. by component `component=HTTPHandler` or even function name e.g. `CODE_FUNC=readFloatText`

**Comment by alexey-milovidov** [comment]
No one was interested in implementing this feature.

**Comment by alexey-milovidov** [comment]
I'm also not interested, because logging into journald will introduce dependency from journald, while we want ClickHouse to be more self-contained.
