### ISSUE TITLE
toStartHour doesn't work in MV?

### ISSUE THREAD

**Issue by knoguchi** [ClickHouse/ClickHouse#9915]
**Describe the bug**
`toStartOfHour`  in a MV returns 0.

**How to reproduce**
* Which ClickHouse server version to use: `20.3.4.10 (official build)` in Ubuntu bionic
* Which interface to use, if matters: `clickhouse-client -m -n`
* Non-default settings, if any: none 
* `CREATE TABLE` statements for all tables involved
```
CREATE TABLE test.a (
  t DateTime
)
ENGINE=Memory();
CREATE TABLE test.b
(
  t DateTime
)
ENGINE=Memory();
CREATE MATERIALIZED VIEW test.a2b TO test.b AS
SELECT
    toStartOfHour(t)
FROM test.a;
```
* Sample data for all these tables, use [clickhouse-obfuscator]
```
INSERT INTO test.a (t) VALUES ('2020-03-28 11:22:33');
```
* Queries to run that lead to unexpected result
```
SELECT * FROM test.b;
```
**Expected behavior**
I expected one row from table `b`
```
2020-03-28 11:00:00
```
The actual result is table `b` is empty.

**Error message and/or stacktrace**
No errors in the log.

**Additional context**
One row is inserted if a column is added.  The value for column `t` is still wrong.

```
CREATE TABLE test.a (
  t DateTime,
  name String
)
ENGINE=Memory();
CREATE TABLE test.b
(
  t DateTime,
  name String
)
ENGINE=Memory();
CREATE MATERIALIZED VIEW test.a2b TO test.b AS
SELECT
    toStartOfHour(t),
    name
FROM test.a;
INSERT INTO test.a (t, name) VALUES ('2020-03-28 11:22:33', 'myname');
SELECT * FROM test.b;
```
The output is
```
0000-00-00 00:00:00	myname
```

The same SELECT returns correct values if I run it manually in the client.

```
SELECT
    toStartOfHour(t),
    name
FROM test.a

┌────toStartOfHour(t)─┬─name───┐
│ 2020-03-28 11:00:00 │ myname │
└─────────────────────┴────────┘
```

**Comment by den-crane** [comment]
Column names must be the same in a MV select and the target (TO) table 

CREATE MATERIALIZED VIEW test.a2b TO test.b AS
SELECT
    toStartOfHour(t) **as t**
FROM test.a;

**Comment by knoguchi** [comment]
ouch.  I overlooked it.  Thanks!
