### ISSUE TITLE
 Seeking an clickhouse architecture diagram

### ISSUE THREAD

**Issue by Sallery-X** [ClickHouse/ClickHouse#9925]
Seeking an clickhouse architecture diagram

**Comment by blinkov** [comment]
@SalleryWang, is this question still relevant?

**Comment by alexey-milovidov** [comment]
The is no global architecture diagram of ClickHouse.

But there are diagrams for various parts:
- indexes and MergeTree;
- distributed query processing;
- replication.

They can be found in presentations published here: https://github.com/ClickHouse/clickhouse-presentations
