### ISSUE TITLE
ClickHouse/18.16.1: port of test suite to python3

### ISSUE THREAD

**Issue by sandrotosi** [ClickHouse/ClickHouse#9926]
Hello,
i've updated the test suite of version 18.16.1 (it's the one we have in Debian right now) to python3, you can find it attached here.

it would be good if you can merge it upstream and port the remaining pieces of ClickHouse using python2 (i think the documentation for sure, maybe something else) to python3.

Thanks!
[clickhouse_python3.txt](https://github.com/ClickHouse/ClickHouse/files/4400538/clickhouse_python3.txt)

**Comment by alexey-milovidov** [comment]
Thank you! Let me apply this patch and look what will happen...

**Comment by alexey-milovidov** [comment]
#14886
