### ISSUE TITLE
Dictionaries with Executable dictionary source is not allowed. 

### ISSUE THREAD

**Issue by zcw5116** [ClickHouse/ClickHouse#9928]
(you don't have to strictly follow this form)

**Describe the issue**
When I create a dictionary of executable files, I get an error: Dictionaries with Executable dictionary source is not allowed. 
version： 20.1.4
My testing process is as follows:

##################### **start** ###################
DROP DATABASE IF EXISTS dictdb;

CREATE DATABASE dictdb ENGINE=Ordinary;

CREATE DICTIONARY dictdb.restricted_dict (
  key UInt64,
  value String
)
PRIMARY KEY key
SOURCE(EXECUTABLE(COMMAND 'echo -E "1\thello"' FORMAT TabSeparated))
LIFETIME(MIN 0 MAX 1)
LAYOUT(CACHE(SIZE_IN_CELLS 10));

-- because of lazy load we can check only in dictGet query
select dictGetString('dictdb.restricted_dict', 'value', toUInt64(1)); 

##################### **end** ###################

When querying, an error is reported：
Code: 482. DB::Exception: Received from localhost:9001. DB::Exception: Dictionaries with Executable dictionary source is not allowed.

My example is from GitHub, link: [example](https://github.com/ClickHouse/ClickHouse/blob/017b8b6638909a1c03af8ca4e51da0465efe735b/dbms/tests/queries/0_stateless/01045_dictionaries_restrictions.sql) What's wrong with this?

Thank You Very Much.

**Comment by filimonov** [comment]
You can configure executable dictionaries only via XML configuration file.
Otherwise, every DB user will have a possibility to execute some malicious code on your ClickHouse server.
See  https://github.com/ClickHouse/ClickHouse/pull/8127/

**Comment by zcw5116** [comment]
> You can configure executable dictionaries only via XML configuration file.
> Otherwise, every DB user will have a possibility to execute some malicious code on your ClickHouse server.
> See #8127

Thank you very much
