### ISSUE TITLE
Quota <execution_time> issue

### ISSUE THREAD

**Issue by hagen1778** [ClickHouse/ClickHouse#993]
ClickHouse server version 1.1.54236

Configuration:
```
   <users>
         <web>
            <password></password>
             <quota>statbox</quota>
        </web>
   </users>

  <quotas>
    <statbox>
        <interval>
            <duration>360</duration>
            <queries>2</queries>
            <execution_time>5</execution_time>
        </interval>
    </statbox>
    </quotas>
```
Connect via `clickhouse-client -u web`. Execute some heavy query to local table

Expected: 
quota exceeding error

Got:
`
Elapsed: 15.644 sec. Processed 96.27 million rows, 3.45 GB (6.15 million rows/s., 220.45 MB/s.)
`

I can run out of  `<queries>2</queries>` and get error. But` <execution_time>` never stops the query or disallows to run another one

**Comment by ztlpn** [comment]
Confirmed. Currently `execution_time` quotas are checked only when (and if) resulting output blocks appear. So e.g. if the query is an aggregation returning small number of rows, this quota is checked only at the very end. And if the query returns zero rows, the quota is never checked.

**Comment by lamber-ken** [comment]
@alexey-milovidov  @ztlpn  hi, also met the bug, can't kill query, `<execution_time>` do not work

**Comment by qoega** [comment]
Isn't it already fixed?

**Comment by alexey-milovidov** [comment]
@qoega No, it's not fixed. Moreover it is considered minor and was not intended to work anyway.

**Comment by alexey-milovidov** [comment]
Summary: Quota on queries only counts when query has finished. It does not adjust limits for a single query.

**Comment by alexey-milovidov** [comment]
This feature can be implemented in the scope of another task.
