### ISSUE TITLE
clickhouse view dictionary error: code 393 There is no query

### ISSUE THREAD

**Issue by testlujing** [ClickHouse/ClickHouse#9932]
### view sql is:
CREATE VIEW shared_dwd.dim_district AS
SELECT
t1.id AS id,
t1.name AS name,
t1.last_modified_date AS last_modified_datetime,
t2.country_name AS country_name
FROM
shared_ods.view_dist_district t1
GLOBAL ANY LEFT JOIN shared_ods.view_dist_country t2 ON t2.id = t1.country_id AND t2.enabled = '1';

**dictionary file is:**
`<yandex> <comment>dim_district</comment> <dictionary> <name>district</name> <source> <clickhouse> <host>localhost</host> <port>9000</port> <user>default</user> <password>*****</password> <db>shared_dwd</db> <table>dim_district</table> </clickhouse> </source> <layout> <complex_key_hashed /> </layout> <structure> <key> <attribute> <name>id</name> <type>String</type> </attribute> </key> <attribute> <name>name</name> <type>String</type> <expression>assumeNotNull(name)</expression> <null_value></null_value> <injective>true</injective> </attribute> <attribute> <name>country_name</name> <type>String</type> <expression>assumeNotNull(country_name)</expression> <null_value></null_value> <injective>true</injective> </attribute> </structure> <lifetime> <min>10</min> <max>60</max> </lifetime> <odbc> <invalidate_query>select max(last_modified_datetime) from shared_dwd.dim_district limit 1</invalidate_query> </odbc> </dictionary> </yandex>`

**error message is :**
ExternalDictionariesLoader: Could not load external dictionary 'label', next update is scheduled at 2020-03-30 16:17:
05: Code: 393, e.displayText() = DB::Exception: There is no query, Stack trace:

0x3512b60 StackTrace::StackTrace() /usr/bin/clickhouse
0x351cdaf DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
0x61639c9 DB::Context::getQueryContext() const /usr/bin/clickhouse
0x6163a09 DB::Context::getSampleBlockCache() const /usr/bin/clickhouse
0x61f8853 DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::shared_ptrDB::IAST const&, DB::Context const&) /usr/bin/clickhouse
0x68a725a DB::getNamesAndTypeListFromTableExpression(DB::ASTTableExpression const&, DB::Context const&) /usr/bin/clickhouse
0x68b4d6c DB::getDatabaseAndTablesWithColumnNames(DB::ASTSelectQuery const&, DB::Context const&) /usr/bin/clickhouse
0x62a9756 DB::SyntaxAnalyzer::analyze(std::shared_ptrDB::IAST&, DB::NamesAndTypesList const&, std::vector<std::string, std::allocatorstd::string > const&, s
td::shared_ptrDB::IStorage, DB::NamesAndTypesList const&) const /usr/bin/clickhouse
0x61cbf9f ? /usr/bin/clickhouse
0x61cd387 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, std::shared_ptrDB::IBlockInputStream const&
, std::shared_ptrDB::IStorage const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cde4b DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<s
td::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61f7e63 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions con
st&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cda9f DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, std::shared_ptrDB::IBlockInputStream const
&, std::shared_ptrDB::IStorage const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cde4b DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<s
td::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61f7e63 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions con
st&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cda9f DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, std::shared_ptrDB::IBlockInputStream const
&, std::shared_ptrDB::IStorage const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cde4b DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<s
td::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61f7e63 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions con
st&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x69675da DB::StorageView::read(std::vector<std::string, std::allocatorstd::string > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcess
ingStage::Enum, unsigned long, unsigned int) /usr/bin/clickhouse
0x61eb9c5 void DB::InterpreterSelectQuery::executeFetchColumnsDB::InterpreterSelectQuery::Pipeline(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery
::Pipeline&, std::shared_ptrDB::SortingInfo const&, std::shared_ptrDB::PrewhereInfo const&, std::vector<std::string, std::allocatorstd::string > const&, DB::
QueryPipeline&) /usr/bin/clickhouse

**query sql is:**
SELECT
    id,
    dictGetString('distributor','name',tuple(assumeNotNull(id))) AS name
FROM
    shared_dwd.dim_distributor;

please help me solve this problem， thank you so much

**Comment by filimonov** [comment]
That looks like one more reincarnation of the old bug (lack of query context). 
It should be easy to fix, in the meanwhile you will need to use some workaround (like do the join before).

**Comment by testlujing** [comment]
> That looks like one more reincarnation of the old bug (lack of query context).
> It should be easy to fix, in the meanwhile you will need to use some workaround (like do the join before).

my clickhouse version is ClickHouse 19.17.4.11
how to do the jion before? using MATERIALIZED VIEW?
but do not update previous data by MATERIALIZED VIEW

**complete SQL statement is：**
SELECT
	t1.id AS id,
	t1.country_id AS country_id,
	t1.level AS level,
	t1.code AS code,
	t1.name AS name,
	t1.name_pinyin AS name_pinyin,
	t1.parent_id AS parent_district_id,
	t1.parent_code AS parent_code,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[1] AS district_id_level1,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[2] AS district_id_level2,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[3] AS district_id_level3,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[4] AS district_id_level4,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[5] AS district_id_level5,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[6] AS district_id_level6,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[7] AS district_id_level7,
	splitByString(',', assumeNotNull(t1.ancestor_ids))[8] AS district_id_level8,
	t1.longitude AS longitude,
	t1.latitude AS latitude,
	t1.longitude_gcj02 AS longitude_gcj02,
	t1.latitude_gcj02 AS latitude_gcj02,
	t1.created_date AS created_datetime,
	t1.last_modified_date AS last_modified_datetime,
	t1.enabled AS enabled,
	t1.version AS version,
	t1.disabled_date AS disabled_datetime,
	t1.remarks AS remarks,
	t2.country_code AS country_code,
	t2.country_name AS country_name,
	t2.country_alias AS country_alias
FROM
	(select * from shared_ods.view_dist_district where (id,rksj) global in(select id,max(rksj) from shared_ods.view_dist_district group by id)) t1
	GLOBAL ANY LEFT JOIN (select * from shared_ods.view_dist_country where (id,rksj) global in(select id,max(rksj) from shared_ods.view_dist_country group by id)) t2 ON t2.id = t1.country_id AND t2.enabled = '1';

**Comment by testlujing** [comment]
> That looks like one more reincarnation of the old bug (lack of query context).
> It should be easy to fix, in the meanwhile you will need to use some workaround (like do the join before).
**MATERIALIZED VIEW**
I convert the update operation to version control by field（rksj）

When I create materialized view 
and Insert some data about the primary key data contained before
Materialized view has more data with the same primary key

Thank you for your reply

**Comment by filimonov** [comment]
For example you can recreate the table in cron, smth like:
```
drop table if exists dim_district;
CREATE TABLE dim_district AS SELECT ... 
```

**Comment by alexey-milovidov** [comment]
@filimonov Could you please write a test using CREATE DICTIONARY query?

**Comment by podshumok** [comment]
Try creating a cascading view:
```sql
CREATE VIEW shared_dwd.dim_district_workaround AS SELECT * FROM shared_dwd.dim_district;
```
and point your dictionary to it instead.

**Comment by alexey-milovidov** [comment]
Need info from @filimonov

**Comment by filimonov** [comment]
> @filimonov Could you please write a test using CREATE DICTIONARY query?

I was not able to reproduce it using CREATE DICTIONARY:

```
DROP TABLE IF EXISTS dictionary_source_en;
DROP TABLE IF EXISTS dictionary_source_ru;
DROP TABLE IF EXISTS dictionary_source_view;
DROP DICTIONARY IF EXISTS flat_dictionary;

CREATE TABLE dictionary_source_en
(
    id UInt64,
    value String
) ENGINE = TinyLog;

INSERT INTO dictionary_source_en VALUES (1, 'One'), (2,'Two'), (3, 'Three');

CREATE TABLE dictionary_source_ru
(
    id UInt64,
    value String
) ENGINE = TinyLog;

INSERT INTO dictionary_source_ru VALUES (1, 'Один'), (2,'Два'), (3, 'Три');

CREATE VIEW dictionary_source_view AS  SELECT id, dictionary_source_en.value as value_en, dictionary_source_ru.value as value_ru  FROM  dictionary_source_en LEFT JOIN dictionary_source_ru USING (id);

select * from dictionary_source_view;

CREATE DICTIONARY flat_dictionary
(
    id UInt64,
    value_en String,
    value_ru String
)
PRIMARY KEY id
SOURCE(CLICKHOUSE(HOST 'localhost' PORT 9000 USER 'default' PASSWORD '' TABLE 'dictionary_source_view'))
LIFETIME(MIN 1 MAX 1000)
LAYOUT(FLAT());

SELECT
    dictGet(concat(currentDatabase(), '.flat_dictionary'), 'value_en', number + 1),
    dictGet(concat(currentDatabase(), '.flat_dictionary'), 'value_ru', number + 1)
FROM numbers(3);
```

**Comment by filimonov** [comment]
But may be behavior with xml differs.

**Comment by alexey-milovidov** [comment]
Ok. Looks like it is no longer relevant.
