### ISSUE TITLE
Server is frequently stopped by OOM

### ISSUE THREAD

**Issue by FedericoCeratto** [ClickHouse/ClickHouse#9945]
ClickHouse 18.16.1 is being killed by the OOM Killer while running on a Debian Buster host, kernel 5.4.20, with 4GB of RAM:
`[2004280.553712] Out of memory: Killed process 28751 (clickhouse-serv) total-vm:9435880kB, anon-rss:2477208kB, file-rss:0kB, shmem-rss:0kB, UID:107 pgtables:16508kB oom_score_adj:0`

There might be different issues at play here:
* The default configuration has no memory limit set and the database appears to increase its memory use indefinitely
* Setting max_memory_usage and max_memory_usage_for_all_queries to 2G appeared to be ignored
* The systemd unit file does not automatically restart the daemon when killed

**Comment by den-crane** [comment]
1. memory leak https://github.com/ClickHouse/ClickHouse/issues/3976
set in users profile  compile_expressions=0 

2. reduce config.xml:    <mark_cache_size>5368709120</mark_cache_size>
from 5 Gb to 500MB

3. Add swap 16 GB

**Comment by FedericoCeratto** [comment]
I reproduced the issue on a host with 32GB of RAM, kernel 4.19.0-8-cloud-amd64, same version of ClickHouse:
```
[ 9380.054067] Out of memory: Kill process 1779 (clickhouse-serv) score 818 or sacrifice child
[ 9380.062029] Killed process 1779 (clickhouse-serv) total-vm:55547844kB, anon-rss:26644232kB, file-rss:0kB, shmem-rss:0kB
[ 9382.430131] oom_reaper: reaped process 1779 (clickhouse-serv), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB```

**Comment by den-crane** [comment]
Did you tune  `compile_expressions=0`?

Do you have some graphics with memory usage?

Do you know SQL query which causes the issue?
Need at least /var/log/clickhouse-server/clickhouse-server.log with logging level trace to find out what causes it.

**Comment by arslanhashmi** [comment]
@den-crane how do we add swap? I don't seem to find it in CH documentation..

**Comment by den-crane** [comment]
@arslanhashmi swap is in Linux not in Clickhouse.

https://www.google.com/search?client=firefox-b-d&q=how+to+add+swap

**Comment by KanchanaAmarathunga** [comment]
[Mon May 31 14:16:35 2021] Out of memory: Kill process 9043 (clickhouse-serv) score 929 or sacrifice child
[Mon May 31 14:16:35 2021] Killed process 9043 (clickhouse-serv), UID 399, total-vm:63205848kB, anon-rss:23652388kB, file-rss:0kB, shmem-rss:0kB

I'm currently experiencing this on my single node click house. Have enough physical memory and swap memory left on the server, although CPU usage is getting high frequently.

**Comment by qinglin** [comment]
@KanchanaAmarathunga Did you solve the problem, I met the same problem, have enough physical memory and swap memory but killed by oom, and the log shows same info as:

Killed process 9043 (clickhouse-serv), UID 399, total-vm:63205848kB, anon-rss:23652388kB, file-rss:0kB, shmem-rss:0kB
