### ISSUE TITLE
drop partition vs insert_quorum 

### ISSUE THREAD

**Issue by filimonov** [ClickHouse/ClickHouse#9946]
Scenario:
1) some data from the past arrived
2) external сleanup script (cron) did drop part / partition before it get replicated.
3) insert_quorum stuck ('Quorum for previous write has not been satisfied yet ... ')

Expected:
DROP PARTITION / PART should also clean /quorum znode if it removes corresponding partition.

**Comment by alex-zaitsev** [comment]
The same problem is reproduced with TTL deletes -- if TTL drops a partition with data non in quorum, quorum gets stuck forever.
