### ISSUE TITLE
Steps in "Testing Hardware" look to be out of date

### ISSUE THREAD

**Issue by pbadenski** [ClickHouse/ClickHouse#9951]
Step 2 says 
> Click on the first green check mark or red cross with green “ClickHouse Build Check” and click on the “Details” link near “ClickHouse Build Check”.

But there is not "Details" link that I can see... 
<img width="790" alt="Screenshot 2020-03-30 at 19 11 21" src="https://user-images.githubusercontent.com/68713/77946481-45dfcd80-72ba-11ea-908e-eba53caa671c.png">

**Comment by qoega** [comment]
Commits to documentation do not fire CI builds for binaries etc. Thus makes them greener than master itself.

**Comment by alexey-milovidov** [comment]
@pbadenski You're right! You have to find any recent commit with changes in code, not only documentation (documentation commits don't have builds).

**Comment by alexey-milovidov** [comment]
We've fixed it, now we have permanent link to the latest build:
https://builds.clickhouse.tech/master/amd64/clickhouse

https://clickhouse.tech/docs/en/operations/performance-test/
Please submit new results!
