### ISSUE TITLE
Date&Time improvements

### ISSUE THREAD

**Issue by qoega** [ClickHouse/ClickHouse#9959]
- [x] Add getTimeZone function. Trivial, but can help user to answer question about timezone in all cases - `toTypeName` for `DateTime` without timezone does not answer this question and you need to read the docs
``` sql
getTimeZone(now()) = timezone()
```
- [ ] Add modifier in formatDateTime to print 'Time offsets from UTC' in following formats `"+02:00","+0200", or "+02".` Note: `+00:00` should be printed with no offset.

- [x] Add parseDateTimeBestEffort description. At least describe arguments. Probably move out of type conversions. 

- [ ] dateDiff documentation is incomplete. Probably we should define function behavior more strictly.

**Comment by alexey-milovidov** [comment]
> Note: +00:00 should be printed with no offset.

ISO 8601 also allows Z.

**Comment by hhell** [comment]
> getTimeZone

A bit of a hack, but it can be implemented by
`if(toTypeName(val) like 'DateTime%(%', splitByChar('\'', toTypeName(val))[2], NULL))`

Example:
```(sql)
select
    toDateTime(now(), 'Europe/Moscow') as val,
    if(
        toTypeName(val) = 'DateTime',
        timezone(),
        if(
            toTypeName(val) like 'DateTime%(%',
            splitByChar('\'', toTypeName(val))[2],
            NULL))
    as val_tz
format JSONCompact
```

**Comment by grundrauschen** [comment]
It would also be great to add a modifier to formatDateTime to print subsecond values when used in conjunction with DateTime64. Together with the timezone offset from above I would then be able to get a full ISO-8601 timestamp from DateTime64 like `2020-11-27T14:54:10.123456Z`.

**Comment by alexey-milovidov** [comment]
The function was added under `timezoneOf` name.

**Comment by alexey-milovidov** [comment]
Closing in favor of #40103.
