### ISSUE TITLE
Clickhouse complex view(is not materialized view) cannot use to be dictionary

### ISSUE THREAD

**Issue by testlujing** [ClickHouse/ClickHouse#9977]
**clickhosue version:**
ClickHouse 19.17.4.11

**when i use view sql is(successful):**
CREATE VIEW shared_dwd.view_dim_district AS 
SELECT
	*(ellipsis)
FROM
	(select * from shared_ods.view_dist_district where (id,rksj) global in(select id,max(rksj) from shared_ods.view_dist_district group by id)) t1

**when i use view sql is(failed):**
SELECT
	*(ellipsis)
FROM
	(select * from shared_ods.view_dist_district where (id,rksj) global in(select id,max(rksj) from shared_ods.view_dist_district group by id)) t1
       GLOBAL ANY LEFT JOIN (select * from shared_ods.view_dist_country where (id,rksj) global in(select id,max(rksj) from shared_ods.view_dist_country group by id)) t2 ON t2.id = t1.country_id AND t2.enabled = '1';

**when i use view sql is(successful):**
SELECT
	*(ellipsis)
FROM
	shared_ods.view_dist_district t1
        GLOBAL ANY LEFT JOIN shared_ods.view_dist_country t2 ON t2.id = t1.country_id AND t2.enabled = '1';

**when i use view is(failed):**
SELECT
	*(ellipsis)
FROM
	shared_ods.view_dist_district t1
        GLOBAL ANY LEFT JOIN shared_ods.view_dist_country t2 ON t2.id = t1.country_id AND t2.enabled = '1'
        GLOBAL ANY LEFT JOIN shared_ods.view_dist_level t3 ON t3.id = t1.level_id AND t3.enabled = '1';

**dictionary file :**
[district_dictionary.txt](https://github.com/ClickHouse/ClickHouse/files/4412284/district_dictionary.txt)

**use dictionary sql:**
SELECT
    id,
    dictGetString('distict','name',tuple(assumeNotNull(id))) AS name
FROM
    shared_dwd.dim_district;

**failed message is:**

ExternalDictionariesLoader: Could not load external dictionary 'district', next update is scheduled at 2020-03-30 16:17:
05: Code: 393, e.displayText() = DB::Exception: There is no query, Stack trace:

0x3512b60 StackTrace::StackTrace() /usr/bin/clickhouse
0x351cdaf DB::Exception::Exception(std::string const&, int) /usr/bin/clickhouse
0x61639c9 DB::Context::getQueryContext() const /usr/bin/clickhouse
0x6163a09 DB::Context::getSampleBlockCache() const /usr/bin/clickhouse
0x61f8853 DB::InterpreterSelectWithUnionQuery::getSampleBlock(std::shared_ptrDB::IAST const&, DB::Context const&) /usr/bin/clickhouse
0x68a725a DB::getNamesAndTypeListFromTableExpression(DB::ASTTableExpression const&, DB::Context const&) /usr/bin/clickhouse
0x68b4d6c DB::getDatabaseAndTablesWithColumnNames(DB::ASTSelectQuery const&, DB::Context const&) /usr/bin/clickhouse
0x62a9756 DB::SyntaxAnalyzer::analyze(std::shared_ptrDB::IAST&, DB::NamesAndTypesList const&, std::vector<std::string, std::allocatorstd::string > const&, s
td::shared_ptrDB::IStorage, DB::NamesAndTypesList const&) const /usr/bin/clickhouse
0x61cbf9f ? /usr/bin/clickhouse
0x61cd387 DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, std::shared_ptrDB::IBlockInputStream const&
, std::shared_ptrDB::IStorage const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cde4b DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<s
td::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61f7e63 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions con
st&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cda9f DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, std::shared_ptrDB::IBlockInputStream const
&, std::shared_ptrDB::IStorage const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cde4b DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<s
td::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61f7e63 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions con
st&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cda9f DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, std::shared_ptrDB::IBlockInputStream const
&, std::shared_ptrDB::IStorage const&, DB::SelectQueryOptions const&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61cde4b DB::InterpreterSelectQuery::InterpreterSelectQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions const&, std::vector<s
td::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x61f7e63 DB::InterpreterSelectWithUnionQuery::InterpreterSelectWithUnionQuery(std::shared_ptrDB::IAST const&, DB::Context const&, DB::SelectQueryOptions con
st&, std::vector<std::string, std::allocatorstd::string > const&) /usr/bin/clickhouse
0x69675da DB::StorageView::read(std::vector<std::string, std::allocatorstd::string > const&, DB::SelectQueryInfo const&, DB::Context const&, DB::QueryProcess
ingStage::Enum, unsigned long, unsigned int) /usr/bin/clickhouse
0x61eb9c5 void DB::InterpreterSelectQuery::executeFetchColumnsDB::InterpreterSelectQuery::Pipeline(DB::QueryProcessingStage::Enum, DB::InterpreterSelectQuery
::Pipeline&, std::shared_ptrDB::SortingInfo const&, std::shared_ptrDB::PrewhereInfo const&, std::vector<std::string, std::allocatorstd::string > const&, DB::
QueryPipeline&) /usr/bin/clickhouse

please help me solve this problem， thank you so much

**Comment by filimonov** [comment]
I think I've already answered you in #9932 - It is a bug in clickhouse, which should be fixed. 
I'm closing this one and reopening the prev one. Please keep it opened, that way it will be prioritized and fixed.
