### ISSUE TITLE
Second argument to CAST must be a constant string describing type  error when doing operations on Nullable(UInt64) type column

### ISSUE THREAD

**Issue by deepanwita-roy** [ClickHouse/ClickHouse#9978]
**Describe the bug**
I have a table with column  column1 of type Nullable(UInt32). I cannot do operations on that data-type like
select * from table_name where column1 is not NULL or even simple operations like
select * from table_name where column1 !=0. It used to work in the previous versions
A clear and concise description of what works not as it is supposed to.

* Which ClickHouse server version to use
19.16.10.44

* Queries to run that lead to unexpected result
select * from table_name where column1 !=0
**Error message and/or stacktrace**
Second argument to CAST must be a constant string describing type

**Additional context**

**Comment by filimonov** [comment]
That sounds weird. May be you have some issue with your schema. We need a minimal table schema reproducing the issue.
