### ISSUE TITLE
mutation  is stuck, Merges took a long time

### ISSUE THREAD

**Issue by leoones** [ClickHouse/ClickHouse#9980]
Update a table frequently. Merge is too slow to run for about 20 hours. After using system stop merges fct_apa_report_sp_productads, merges does not stop. What's a good way to quickly stop the executing merge；

Data volume：
SELECT count(1)
FROM fct_apa_report_sp_productads;

┌──count(1)─┐
│ 681415034 │
└───────────┘

mutation  sql ：
alter table fct_apa_report_sp_productads UPDATE flag = flag + 1 WHERE (flag IN (0, 1)) AND (report_date = '20200320') AND (profile_id = '686840925875071')

Table structure:
CREATE TABLE ptx_db.fct_apa_report_sp_productads (`uuid` UUID DEFAULT generateUUIDv4(),
`batch_number` UInt64,
`profile_id` String,
`foreign_id` UInt64,
`account` String,
`country` String,
`report_date` String,
`attributedUnitsOrdered1dSameSKU` Int64,
`attributedSales7d` Int64,
`attributedSales30d` Int64,
`attributedUnitsOrdered30d` Int64,
`attributedSales1d` Int64,
`attributedConversions1d` Int64,
`attributedSales1dSameSKU` Int64,
`attributedConversions30d` Int64,
`adGroupId` String,
`attributedConversions7d` Int64,
`attributedConversions14d` Int64,
`currency` String,
`sku` String,
`attributedConversions7dSameSKU` Int64,
`attributedUnitsOrdered7dSameSKU` Int64,
`attributedConversions1dSameSKU` Int64,
`cost` Int64,
`adGroupName` String,
`attributedUnitsOrdered7d` Int64,
`attributedSales7dSameSKU` Int64,
`campaignId` String,
`attributedSales14dSameSKU` Int64,
`attributedSales30dSameSKU` Int64,
`impressions` Int64,
`attributedUnitsOrdered1d` Int64,
`attributedConversions30dSameSKU` Int64,
`adId` String,
`attributedUnitsOrdered14dSameSKU` Int64,
`attributedConversions14dSameSKU` Int64,
`clicks` Int64,
`asin` String,
`attributedSales14d` Int64,
`campaignName` String,
`attributedUnitsOrdered30dSameSKU` Int64,
`attributedUnitsOrdered14d` Int64,
`flag` UInt8 DEFAULT 0,
`request_time` DateTime,
`create_date` DateTime DEFAULT now()) ENGINE = MergeTree PARTITION BY toYYYYMM(create_date)
ORDER BY
(report_date,
country,
account) SETTINGS index_granularity = 8192;

SELECT 
    formatReadableSize(total_size_bytes_compressed) AS a, 
    formatReadableSize(memory_usage) AS b, 
    (elapsed / 60) / 60 AS c, 
    *
FROM system.merges
WHERE table = 'fct_apa_report_sp_productads';

[
![image](https://user-images.githubusercontent.com/40047678/78108642-6038b900-742a-11ea-93c2-5ce259a4becd.png)
](url)

**Comment by alesapin** [comment]
At least we need to know ClickHouse version and `clickhouse-server.log` to investigate the issue.

**Comment by filimonov** [comment]
Logs would be helpful. 

Did you try `Kill mutation` Command?

**Comment by leoones** [comment]
> At least we need to know ClickHouse version and `clickhouse-server.log` to investigate the issue.

version 19.15.3.6

**Comment by leoones** [comment]
> Logs would be helpful.
> 
> Did you try `Kill mutation` Command?

I  try "Kill mutation" and "system stop merges  fct_apa_report_sp_productads" 
But it didn't work .
System.merges table is still displayed in merge。
Merge is running continuously。
After I restart the Clickhouse service, merge is released.

**Comment by blinkov** [comment]
@leoones, do you have any further questions?

**Comment by leoones** [comment]
> @leoones, do you have any further questions?

When merge is running, the system stop merges table cannot stop quickly。
Is there any way to quickly stop the merge of a table ?

**Comment by alexey-milovidov** [comment]
There is no way to stop the merge quickly.
Up to single minutes delay is expected.
