### ISSUE TITLE
How do we guarantee data consistency in Clickhouse?

### ISSUE THREAD

**Issue by kindred77** [ClickHouse/ClickHouse#9981]
Hi, we always insert a large mount of data into Clickhouse using JDBC(http) batch.
The data will be split by max_insert_block_size in each batch.
Does it mean Clickhouse will not guarantee data consistency in each batch?
since some of the split insertion may fail.

**Comment by den-crane** [comment]
Yes, it does. CH guarantees atomicity on part level but not on insert level.

To achieve atomicity for insert you have to do insert into one partition only and tune parameters
You need to increase max_insert_block_size 

max_insert_block_size=200000000,
min_insert_block_size_rows=200000000,
min_insert_block_size_bytes=20000000000

see https://gist.github.com/den-crane/21a84a9a8a9e5203195a7f023a0ec363

https://github.com/ClickHouse/ClickHouse/issues/5148
