### ISSUE TITLE
Unable to connect to S3 while reading data in clickhouse from S3

### ISSUE THREAD

**Issue by hilesha** [ClickHouse/ClickHouse#9988]
i have created clickhouse cluster on EKS using  clickhouse-operator. 

i was trying to read data into CH from S3 object store using “select * from s3(url, [access_key_id, secret_access_key,] format, structure)“. i was able to launch the query. however, it is unable to connect to s3 with a DB exception - Unable to connect to endpoint: While executing S3.

clickhouse.server.log files shows that aws sdk for s3 is injecting default region of us-east-1 and i am operating in ap-south-1, could this be an issue that is leading to the connection error. is there a way to inject region paramater just like secrets.

adding more details to the error logs:
[error_logs.txt](https://github.com/ClickHouse/ClickHouse/files/4415848/error_logs.txt)

saw an error log while establishing connection to S3
2020.04.01 14:27:12.539530 [ 129 ] {} <Error> AWSClient: CurlHttpClient: Curl returned error code 77 - Problem with the SSL CA cert (path? access rights?)

**Comment by hilesha** [comment]
upon changing the URL from https to http, i got following error:
Unable to parse ExceptionName: AuthorizationHeaderMalformed Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-south-1': While executing S3 (version 20.3.5.21 (official build))

**Comment by alexey-milovidov** [comment]
@excitoon Looks like it's already fixed in recent pull requests?
