### ISSUE TITLE
Add multiExtractAll similar to multiMatchAllIndices but doing actual extract

### ISSUE THREAD

**Issue by alex-zaitsev** [ClickHouse/ClickHouse#9990]
**Use case**
Need to extract multiple expressions in an efficient way. 

**Describe the solution you'd like**
```
SELECT multiMatchAllIndices('abc=111, def=222, ghi=333', ['abc=', 'klm=', 'ghi='])

┌─multiMatchAllIndices('abc=1, def=2, ghi=3', ['abc=', 'klm=', 'ghi='])─┐
│ [1,3]                                                                 │
└───────────────────────────────────────────────────────────────────────┘
```
The function should follow the same logic but return actual matching expressions with respect to capture groups:

```
SELECT multiExtractAll('abc=111, def=222, ghi=333', ['abc=("[^"]*?"|[\\w]*)', 'klm=("[^"]*?"|[\\w]*)', 'ghi=("[^"]*?"|[\\w]*)'])

should return

['111',333']
```

Combined with reuse of aliases (#2283) it allows to extract multiple things from a row in a single pass.

The alternative is to run multiple regexp searches that is expensive when multiple matches are required.

See #7299 for multiMatchAllIndices implementation details.

**Comment by Enmk** [comment]
Currently, Hyperscan does not support that:
https://github.com/intel/hyperscan/issues/189

>     * Hyperscan doesn't support _greedy_ or _ungreedy_ semantics but reports all matches instead. So in your case, `"2"`, `"20"`, `"201"` and `"2018"` are all valid matches for `[0-9]+`.
>       You can refer to http://intel.github.io/hyperscan/dev-reference/compilation.html#semantics for more details.
> 
>     * Hyperscan doesn't support capturing so you are not able to get matched sub-strings from your input.
> 
> 
> In general, Hyperscan's major targeting use case is networking which takes performance as top priority so as to avoid deny of services. The underlying design of Hyperscan, differing from traditional regex matching library like PCRE, Boost, etc, avoid using backtracking-based approach that doesn't have worst performance guarantee. Greediness and capturing need to be addressed with backtracking so we don't support them so far.

https://github.com/intel/hyperscan/issues/189#issuecomment-542471139

Even though there is seems to be an [API that does that](https://github.com/intel/hyperscan/blob/865c256dbba20f7f1e1d562b574a3b691af8c47d/src/hs_runtime.h#L125
), in practice it does not work: [the `from` value is always 0](https://github.com/intel/hyperscan/blob/865c256dbba20f7f1e1d562b574a3b691af8c47d/src/report.h#L268) and there is no easy way to fix it.

**Comment by filimonov** [comment]
That sound like more about captured groups in regexps (i.e. smth like `xyz=([0-9]+)([a-z]+)`). 

Here we need to return whole match (by several regexps)

**Comment by alexey-milovidov** [comment]
For single regular expression we can add `extractGroups` that will return an array of captured groups starting from 1 in the first match. Also we can add `extractAllGroups` that will return two-dimensional array of groups from all matches.

**Comment by filimonov** [comment]
> @filimonov
> 
> For single regular expression we can add `extractGroups` that will return an array of captured groups starting from 1 in the first match. Also we can add `extractAllGroups` that will return two-dimensional array of groups from all matches.

Yep. Re2-based, based on extractAll , w/o 'multi-' prefix and w/o hyperscan (as @Enmk mentioned hyperscan does not support capture groups).

**Comment by alex-zaitsev** [comment]
I like extractAllGroups. Taking the example above

```SELECT extractAllGroups('abc=111, def=222, ghi=333', '("[^"]*?"|[\\w]*)=("[^"]*?"|[\\w]*)')

should return

[['abc','def','ghi'], ['111','333','333']]
```

**Comment by alexey-milovidov** [comment]
@alex-zaitsev 
```
[['abc', 111], ['def', 222], ['ghi', 333]]
```

**Comment by alex-zaitsev** [comment]
@alexey-milovidov , I prefer two arrays that maps better to nested structures. Also not sure it makes sense to perform type inference. The data may be dirty.

**Comment by alexey-milovidov** [comment]
Reopen, because the function `extractGroups` is not implemented.
It's pointless to have `extractAllGroups` without `extractGroups` function.
