### ISSUE TITLE
Performance issue of WHERE with primary key and applied `toString` to the column

### ISSUE THREAD

**Issue by garrettlish** [ClickHouse/ClickHouse#9991]
We are NOT able to use index to filter out non-match data granules in merge tree data select function if we applied toString function to the PK column. The following SQL `pool` is the primary key.

>SELECT typename, status, pool, toStartOfMinute(unixtime) AS t, sumMerge(sumcount) as _sumMerge_ FROM sherlockio.appevent_1min WHERE toUInt64(unixtime) < 1585644416 AND toUInt64(unixtime) >= 1585643216 AND toString(pool)='XXX' AND status!='0' AND typename NOT IN ('xom','ERROR') GROUP BY typename, status, pool, t ORDER BY t
```
→ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) [chi1-events-4-0-0] 2020.03.31 09:25:43.384739 {dfa8519a-8d2b-4758-a708-1d4d18e204bd} [ 6904 ] <Debug> sherlockio.appevent_1min_mv_inner2 (SelectExecutor): Key condition: (toUInt64(column 11) in (-inf, 1585644415]), (toUInt64(column 11) in [1585643216, +inf)), and, (toString(column 1) in ['XXX', 'XXX']), and, (column 8 not in ['0', '0']), and, (column 7 notIn 2-element set), and
[chi1-events-4-0-0] 2020.03.31 09:25:43.448596 {dfa8519a-8d2b-4758-a708-1d4d18e204bd} [ 6904 ] <Debug> sherlockio.appevent_1min_mv_inner2 (SelectExecutor): Selected 7 parts by date, 7 parts by key, 13613 marks to read from 475 ranges
[chi1-events-4-0-0] 2020.03.31 09:25:43.448854 {dfa8519a-8d2b-4758-a708-1d4d18e204bd} [ 6904 ] <Trace> sherlockio.appevent_1min_mv_inner2 (SelectExecutor): Reading approx. 111517696 rows with 24 streams
585 rows in set. Elapsed: 59.411 sec. Processed 1.12 billion rows, 106.91 GB (18.83 million rows/s., 1.80 GB/s.)
```

**Expected performance**
>SELECT typename, status, pool, toStartOfMinute(unixtime) AS t, sumMerge(sumcount) as _sumMerge_ FROM sherlockio.appevent_1min WHERE toUInt64(unixtime) < 1585644416 AND toUInt64(unixtime) >= 1585643216 AND pool='XXX' AND status!='0' AND typename NOT IN ('xom','ERROR') GROUP BY typename, status, pool, t ORDER BY t 
```
↓ Progress: 0.00 rows, 0.00 B (0.00 rows/s., 0.00 B/s.) [chi1-events-4-0-0] 2020.03.31 09:12:47.438601 {8ecb0548-1556-4457-b398-cfdad4e73883} [ 6895 ] <Debug> sherlockio.appevent_1min_mv_inner2 (SelectExecutor): Key condition: (toUInt64(column 11) in (-inf, 1585644415]), (toUInt64(column 11) in [1585643216, +inf)), and, (column 1 in ['XXX', 'XXX']), and, (column 8 not in ['0', '0']), and, (column 7 notIn 2-element set), and
[chi1-events-4-0-0] 2020.03.31 09:12:47.450188 {8ecb0548-1556-4457-b398-cfdad4e73883} [ 6895 ] <Debug> sherlockio.appevent_1min_mv_inner2 (SelectExecutor): Selected 9 parts by date, 9 parts by key, 30 marks to read from 22 ranges
[chi1-events-4-0-0] 2020.03.31 09:12:47.450473 {8ecb0548-1556-4457-b398-cfdad4e73883} [ 6895 ] <Trace> sherlockio.appevent_1min_mv_inner2 (SelectExecutor): Reading approx. 245760 rows with 9 streams
585 rows in set. Elapsed: 0.074 sec. Processed 1.72 million rows, 165.47 MB (23.12 million rows/s., 2.22 GB/s.)
```

**Summary**
The SQL which applied toString function to the PK column (`pool`), it processed 1.12 billion rows. However, the same SQL which don't apply toString function to the PK column, it only processed 1.72 million rows. Seems that with toString function we are NOT able to use index to filter out non-match data granules.

**Comment by den-crane** [comment]
So your table have an index -- ORDER BY pool .... Not ORDER BY **toString**(pool) ? Right?

Why do you expect such behaviour? 

toString function is not monotonic. 
See a different result 

```
SELECT
    11 > 9,
    toString(11) > toString(9)

┌─greater(11, 9)─┬─greater(toString(11), toString(9))─┐
│              1 │                                  0 │
└────────────────┴────────────────────────────────────┘
```

**Comment by garrettlish** [comment]
@den-crane thanks for your reply. We are trying to use ClickHouse as one of Prometheus storage backend. As you know, Prometheus only supports string type for labels. So we'd like to apply `toString` to all columns. 

Yes, my table only has `ORDER BY pool` but not `ORDER BY toString(pool)`, but the `pool` is defined as string in my table, `toString(pool)` should be equivalent to `pool`, right?

```
│ pool        │ LowCardinality(String)          │              │                    │         │                  │                │
```

**Comment by den-crane** [comment]
BUT LowCardinality(String) is a string. And can be used with  `= '....' ` without any casting.

moreover `toString` does nothing for LowCardinality(String). 
Your toString is completely useless and harmful.
```
desc (select toString(x) from (select toLowCardinality('aaa') x))

─type───────────────────┬
 LowCardinality(String) │
────────────────────────┴
```

**Comment by garrettlish** [comment]
@den-crane Actually we applied `toString` to all columns since prometheus only supports `string` for labels. Yes, for `pool` column, the type is `LowCardinality(String)`, `toString` is completely useless here. We can check the type and skip `toString` for the column which type is `LowCardinality(String)`.

I am just curious, why adding `toString` for the column will impact using index to filter out non-match data granules in merge tree data select function.

**Comment by den-crane** [comment]
>Actually we applied toString to all columns since prometheus only supports string for labels.

What API do you use with prometheus? 
Perhapse `low_cardinality_allow_in_native_format` can do it automatically
--low_cardinality_allow_in_native_format arg                     Use LowCardinality type in Native format. Otherwise, convert LowCardinality columns to ordinary for select query, and convert ordinary columns to required.

>I am just curious, why adding toString 

I am curious why it should not. Try where `someindexedfield+0 = 1` in any RDMS. Then you apply a function to column it always breaks index access. Actually CH is an exemption in this case. But not with toString function.

**Comment by garrettlish** [comment]
Yes, CH is an exemption, we can use `startsWith`, etc. to use index to filter out non-match data granules (https://clickhouse.tech/docs/en/operations/table_engines/mergetree/#functions-support). Actually `toString` does nothing for `LowCardinality(String)` column, don't know why it breaks index access.

**Comment by den-crane** [comment]
toString function is not monotonic.
See a different result
```
SELECT
    11 > 9,
    toString(11) > toString(9)

┌─greater(11, 9)─┬─greater(toString(11), toString(9))─┐
│              1 │                                  0 │
└────────────────┴────────────────────────────────────┘

```

**Comment by garrettlish** [comment]
thanks @den-crane, seems that `KeyCondition` only supports few functions but not `toString`.
https://github.com/ClickHouse/ClickHouse/blob/ea6f90b4f2c3cc2f7d8b846c769b7f3e84907e47/src/Storages/MergeTree/KeyCondition.cpp#L109-L263

**Comment by den-crane** [comment]
@garrettlish Except you are missing this:

create table XA (A DateTime, F Float) Engine=MergeTree order by A;
insert into XA select toDateTime('2020-01-01 00:00:00')+intDiv(number,10), 0 from numbers(10000000);


select count() from XA
│ 10000000 │
1 rows in set. Elapsed: 0.002 sec. Processed 10.00 million rows, 40.00 MB (4.90 billion rows/s., 19.59 GB/s.)


select count() from XA where toYYYYMMDD(A) = 20200101
│  864000 │
1 rows in set. Elapsed: 0.003 sec. **Processed 868.35 thousand rows**, 3.47 MB (306.44 million rows/s., 1.23 GB/s.)


select count() from XA where toDate(A) = toDate('2020-01-01')
│  864000 │
1 rows in set. Elapsed: 0.004 sec. **Processed 983.04 thousand rows,** 3.93 MB (227.97 million rows/s., 911.89 MB/s.)


select count() from XA where toString(toDate(A)) = '2020-01-01'
│  864000 │
1 rows in set. Elapsed: 0.009 sec. **Processed 983.04 thousand rows**, 3.93 MB (111.72 million rows/s., 446.89 MB/s.)

select count() from XA where toUInt16(toDate(A)) = toUInt16(toDate('2020-01-01'))
│  864000 │
1 rows in set. Elapsed: 0.004 sec. **Processed 983.04 thousand rows**, 3.93 MB (228.71 million rows/s., 914.86 MB/s.)


select count() from XA where toString(toUInt16(toDate(A))) = 
│  864000 │
1 rows in set. Elapsed: 0.007 sec. **Processed 983.04 thousand rows**, 3.93 MB (139.76 million rows/s., 559.02 MB/s.)


select count() from XA where toString(toUInt16(toDate(A))) = '18262'
│  864000 │
1 rows in set. Elapsed: 0.007 sec. **Processed 983.04 thousand rows**, 3.93 MB (131.59 million rows/s., 526.36 MB/s.)
